### ISSUE TITLE
CLI add_graphs.php always use "previous" Graph Template title

### ISSUE THREAD

**Issue by KnpA** [Cacti/cacti#1000]
Hello,

We have noticed what appears to be a bug when we use the CLI script add_graphs.php (in Cacti 1.1.15):

This is our **Graph Template title**: "toto"
![capture1](https://user-images.githubusercontent.com/6367927/30817363-f666824a-a218-11e7-8827-afd9e504f0f4.PNG)

We want to customise our **Graph title** with a specific name, here "test"
![capture2](https://user-images.githubusercontent.com/6367927/30817369-f7cc303a-a218-11e7-9ae3-59ac4d6ae0c1.PNG)

In the graph list, the graph name is the **previous** Graph Template name:
![capture3](https://user-images.githubusercontent.com/6367927/30817371-faa65e2a-a218-11e7-93e8-88b2ee9d8b04.PNG)

And when I want to look at our Graph Template, the Graph Template title has changed to "test"!
![capture4](https://user-images.githubusercontent.com/6367927/30817378-fc6218e4-a218-11e7-80c5-2e3b30848913.PNG)

I've tried with and without the "Use Per-Graph Value" and I got the same issue.

Is it already fixed in 1.1.24 ?

**Comment by 995599** [comment]
the same on the v1.1.25 
For specific host id and graph id plus adding --graph-title"some name" ir changes name to ALL graphs

2. another problem on the CLI add_graphs.php 
adding "--input-fields=" got PHP Notice: Undefined offset
Graph and DS is created, but input field is empty
example ->

![test](https://user-images.githubusercontent.com/32635039/31331792-7129e5fc-acec-11e7-8770-6e9fb359f3da.PNG)

**Comment by cigamit** [comment]
Should both be resolved now.  Please verify.

**Comment by 995599** [comment]
Working. Thank You!
