### ISSUE TITLE
Mariadb errors upgrading 0.8.8h to 1.1.21

### ISSUE THREAD

**Issue by Sargastic** [Cacti/cacti#1002]
Gentoo platform, Mariadb 10.2.28. Upgrade to Php 7.0 forces us to upgrade Cacti (0.8.8h to 1.1.21).

The database upgrade fails. Here are the failed statements (and internal db version). Everything goes ok till upgrade to db version 1.0.5

**version 1.0.5**
[Fail] 
`UPDATE data_template_data SET data_source_profile_id = WHERE data_source_profile_id = 0`

Here, obviously, there is stg missing before the WHERE. All other errors (below) seem legit syntax.

**Version: 1.1.2**
[Fail] 
```
ALTER TABLE `graph_templates_item`
DROP INDEX `local_graph_id`,
ADD INDEX `local_graph_id_sequence` (`local_graph_id`, `sequence`)
```

[Fail] 
```
ALTER TABLE `graph_tree_items`
DROP INDEX `parent`,
ADD INDEX `parent_position` (`parent`, `position`)
```

[Fail] 
`ALTER TABLE `graph_tree` ADD INDEX `sequence` (`sequence`)`

**Version: 1.1.20**
[Fail] 
```
ALTER TABLE snmpagent_cache_notifications
MODIFY COLUMN `name` VARCHAR(50) NOT NULL,
MODIFY COLUMN `mib` VARCHAR(50) NOT NULL,
MODIFY COLUMN `attribute` VARCHAR(50) NOT NULL,
ADD PRIMARY KEY (`name`,`mib`,`attribute`,`sequence_id`)
```

[Fail] 
```
ALTER TABLE snmpagent_cache_textual_conventions
MODIFY COLUMN name VARCHAR(50) NOT NULL,
MODIFY COLUMN mib VARCHAR(50) NOT NULL,
MODIFY COLUMN type VARCHAR(50) NOT NULL,
ADD PRIMARY KEY (`name`,`mib`,`type`)
```

[Fail] 
```
ALTER TABLE snmpagent_managers_notifications
MODIFY COLUMN `notification` VARCHAR(50) NOT NULL,
MODIFY COLUMN `mib` VARCHAR(50) NOT NULL,
ADD PRIMARY KEY (`manager_id`,`notification`,`mib`)
```

**Comment by cigamit** [comment]
We have not fully supported 10.2 yet.  Can you please execute these queries by hand and post the specific errors?

**Comment by Sargastic** [comment]
Sorry for the long delay... Here are the errors for each failed upgrade statement.

**version 1.0.5**
```
UPDATE data_template_data SET data_source_profile_id = WHERE data_source_profile_id = 0

ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE data_source_profile_id = 0' at line 1
```

Obviously, the 
> SET data_source_profile_id = WHERE

is missing something after the = character.

**Version: 1.1.2**
```
ALTER TABLE `graph_templates_item`
DROP INDEX `local_graph_id`,
ADD INDEX `local_graph_id_sequence` (`local_graph_id`, `sequence`)

ERROR 1091 (42000): Can't DROP INDEX `local_graph_id`; check that it exists
```

```
ALTER TABLE `graph_tree_items`
DROP INDEX `parent`,
ADD INDEX `parent_position` (`parent`, `position`)

ERROR 1061 (42000): Duplicate key name 'parent_position'
```

**Version 1.1.20**

```
ALTER TABLE snmpagent_cache_notifications
MODIFY COLUMN `name` VARCHAR(50) NOT NULL,
MODIFY COLUMN `mib` VARCHAR(50) NOT NULL,
MODIFY COLUMN `attribute` VARCHAR(50) NOT NULL,
ADD PRIMARY KEY (`name`,`mib`,`attribute`,`sequence_id`)

ERROR 1068 (42000): Multiple primary key defined
```

```
ALTER TABLE snmpagent_cache_textual_conventions
MODIFY COLUMN name VARCHAR(50) NOT NULL,
MODIFY COLUMN mib VARCHAR(50) NOT NULL,
MODIFY COLUMN type VARCHAR(50) NOT NULL,
ADD PRIMARY KEY (`name`,`mib`,`type`)

ERROR 1068 (42000): Multiple primary key defined
```

```
ALTER TABLE snmpagent_managers_notifications
MODIFY COLUMN `notification` VARCHAR(50) NOT NULL,
MODIFY COLUMN `mib` VARCHAR(50) NOT NULL,
ADD PRIMARY KEY (`manager_id`,`notification`,`mib`)

ERROR 1068 (42000): Multiple primary key defined
```

**Comment by cigamit** [comment]
The last issue is resolved (with the three snmpagent tables) in 1.1.28 once released.  The first issue is a major deal and indicates some other more troubling error earlier in the upgrade process.  These are likely some failures from 0.8.x to 1.0.0.

What I would like you to so is in your /etc/my.cnf.d/server.cnf, set the following:

`sql_mode=NO_ENGINE_SUBSTITUTION`

And then restart MariaDB, after which perform the upgrade one more time.  I suspect a bunch of this will fall away.  Do it from the Develop branch and not the 1.1.27 release code, unless 1.1.28 is released by the time you get upto doing this.

**Comment by cigamit** [comment]
Can you please retest with the pending 1.1.30 release.  The develop branch is the current version as of the time of this post.

**Comment by cigamit** [comment]
Closing.  No feedback.

**Comment by netniV** [comment]
I am going to run through testing this. I have got a CentOS 6 and 7 test VM setup but haven’t got to it yet. Leave it closed for now until I can verify it since we got no feedback.

**Comment by cigamit** [comment]
I'm pretty sure it's the SQL_MODE.  We've been having these issues for years.  Oracle keeps attempting to nudge the community to Oracle standard conventions.  There may be something to some of the changes as the query optimizer in some cases can take shortcuts if they don't have to support certain syntax's.

**Comment by MrDibbley** [comment]
just running 1.2.9 from 0.8.8.h same error @ 1.0.5 update:

![image](https://user-images.githubusercontent.com/20700791/75874569-e5b85180-5e09-11ea-8a8f-ef64eb57e532.png)

set setmode as above and retested same result?

Thanks

**Comment by netniV** [comment]
That statement looks wrong as there is no assignment to the data source profile id.
