### ISSUE TITLE
Fix of Issue #995 in 1.1.25 introduces a major polling problem

### ISSUE THREAD

**Issue by ikorzha** [Cacti/cacti#1003]
After installing the upgrade to 1.1.25 from 1.1.24 master Cacti polling times went from 35sec to 274sec on master poller. On remote poller, polling went from 7sec to 67sec
![remote-poller](https://user-images.githubusercontent.com/11211789/30930367-85c0c9e2-a38f-11e7-8b38-9cda1ee5e28e.jpeg)
I have reverted back to 1.1.24 and problem went away, I have since applied 1.1.25 file changes manually and determined the problem to be cause by Issue #995, change in lib/poller.php
![change](https://user-images.githubusercontent.com/11211789/30930524-eec7af0a-a38f-11e7-8390-343d374af06e.jpeg)

Please correct this major problem at your earliest convenience.

**Comment by imax64** [comment]
i agree, same thing here .

your proposed workaround works: modifying #995 (the 2 lines in lib\poller.php solved the problem, i'm now getting proper poller execution time

**Comment by cigamit** [comment]
Should be reverted.  Confirm and then close please.

**Comment by ikorzha** [comment]
Revert is tested and confirmed, thank you for taking care of it.
