### ISSUE TITLE
Template Issue

### ISSUE THREAD

**Issue by raikone14** [Cacti/cacti#1007]
I am trying to import a vpn template, but I am facing this following error:
<arg_num_indexes> missing in XML file, 'Index Count Changed' emulated by counting arg_index entries

My cacti is version 1.1.24, there is any way to solve this issue .

This is the XML :

<interface>
        <name>Get Cisco ASA/PIX VPN Statistics</name>
        <script_path>perl |path_cacti|/scripts/query_lan2lan_cisco.pl</script_path>
        <arg_prepend>|host_snmp_community| |host_hostname| ASA</arg_prepend>
        <arg_index>index</arg_index>
        <arg_query>query</arg_query>
        <arg_get>get</arg_get>
        <output_delimeter>:</output_delimeter>
        <index_order>PeerIP</index_order>
        <index_order_type>numeric</index_order_type>
        <index_title_format>|chosen_order_field| IPSec Traffic</index_title_format>

        <fields>
                <PeerIP>
                        <name>Peer IP</name>
                        <direction>input</direction>
                        <query_name>index</query_name>
                </PeerIP>

                <RX>
                        <name>Received Traffic</name>
                        <direction>output</direction>
                        <query_name>RX</query_name>
                </RX>
                <TX>
                        <name>Transmitted Traffic</name>
                        <direction>output</direction>
                        <query_name>TX</query_name>
                </TX>
        </fields>
</interface>

[XML.txt](https://github.com/Cacti/cacti/files/1344400/full.txt)

Thank you for any help.

**Comment by cigamit** [comment]
That is not something you import.  That XML file likely goes in the |path_cacti|/resource/snmp_query directory.  You are importing the wrong file.  If you are re-indexing, that warning is not anything to worry about.  Its informational.  You should post a question like this on the forums and not here.
