### ISSUE TITLE
Errors in log when viewing graps and searching

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#1008]
2017/10/02 13:42:11 - CMDPHP Input Validation Not Performed for 'thumbnails' Backtrace: (/graph_view.php: 175 get_request_var)(/lib/html_utility.php: 324 html_log_input_error)(/lib/html_validate.php: 44 cacti_debug_backtrace)

**Comment by cigamit** [comment]
Resolved. Thanks!
