### ISSUE TITLE
RealTime Problem

### ISSUE THREAD

**Issue by dabeani** [Cacti/cacti#1009]
Hi,

found some issue, when realtime is started. Version 1.1.25 - it was also in Version 1.1.21!
Next i copy&past the error message to solve that bug.

03-Oct-2017 14:03:51 - CMDPHP PHP ERROR NOTICE Backtrace: (/cmd_realtime.php: 148 CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)
--
03-Oct-2017 14:03:51 - ERROR PHP NOTICE: Undefined index: max_oids in file: /var/www/html/cacti/cmd_realtime.php on line: 148
03-Oct-2017 14:03:51 - CMDPHP PHP ERROR NOTICE Backtrace: (/cmd_realtime.php: 148 CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)
03-Oct-2017 14:03:51 - ERROR PHP NOTICE: Undefined index: ping_retries in file: /var/www/html/cacti/cmd_realtime.php on line: 148

**Comment by reboot1983** [comment]
I looks like the query for your hostname doesn't has any result:

`$host = db_fetch_row_prepared('SELECT ping_retries, max_oids FROM host WHERE hostname = ?', array($item['hostname']));`

Can you please run the query on your database and let us know what the result is?

`SELECT ping_retries, max_oids FROM host WHERE hostname = '<put_hostname_here>'`

**Comment by cigamit** [comment]
This is resolved.  It's quite possible that the hostname was changed outside of the cacti API making the hostname in the poller_item table not match the host table.  So, I switched this to use the host_id instead.
