### ISSUE TITLE
Creating graph in advanced mode: Can't select any data source

### ISSUE THREAD

**Issue by shavenne** [Cacti/cacti#101]
While the selection of the device and the graph template is fixed now in the next step I can't choose the data sources.

![bc](https://cloud.githubusercontent.com/assets/20374265/21531449/79f17aee-cd48-11e6-9cf4-aa7eedafef53.png)

There's just no input field.

**Comment by cigamit** [comment]
Unlock the graph, and you should be able to do what you want.  It's an extra step, but was added to address some serious performance issues on some larger systems.

**Comment by shavenne** [comment]
Ah okay. Didn't see that. Thank you :)
