### ISSUE TITLE
[Cacti-1.1.25]PAW theme breaks weathermap

### ISSUE THREAD

**Issue by imax64** [Cacti/cacti#1013]
using PAW theme, weathermap (latest 0.98a from howie) tab only shows a blank page (no maps)
PHP console returns in error: complaining that treeView, listView and previewView are undefined. This performs flawless on classic theme.

i noticed that the problem resides in include/themes/paw/main.js (line 109, 110, 111):

>                                 +'<ul id="submenu-' + submenu_counter + '" class="submenuoptions" style="display:none;">'
>                                         +'<li><a href="'+urlPath+'graph_view.php?action=tree">'+treeView+'</a></li>'
>                                         +'<li><a href="'+urlPath+'graph_view.php?action=list">'+listView+'</a></li>'
>                                         +'<li><a href="'+urlPath+'graph_view.php?action=preview">'+previewView+'</a></li>'

if i comment them, it works just fine.

>                                 +'<ul id="submenu-' + submenu_counter + '" class="submenuoptions" style="display:none;">'
>                                         //+'<li><a href="'+urlPath+'graph_view.php?action=tree">'+treeView+'</a></li>'
>                                         //+'<li><a href="'+urlPath+'graph_view.php?action=list">'+listView+'</a></li>'
>                                         //+'<li><a href="'+urlPath+'graph_view.php?action=preview">'+previewView+'</a></li>'

**Comment by imax64** [comment]
sadly, you can no longer scroll vertically after this workaround ...

**Comment by cigamit** [comment]
Sorry, this is an issue for Mr. Jones.

**Comment by imax64** [comment]
thank you, i'll open a issue to him. it seemed like a PAW issue, not a weathermap itself
