### ISSUE TITLE
Upgrade issue with Spine

### ISSUE THREAD

**Issue by andermat8** [Cacti/cacti#1021]
I have Cacti, Spine, and Mysql running on the D: drive of my server but when I do an upgrade it will always install Spine on the C: drive.  It would be nice if we could select the location where spine will be installed

![image](https://user-images.githubusercontent.com/29753529/31338209-55a63da0-accc-11e7-8e9f-e54bb795501b.png)

**Comment by cigamit** [comment]
I have forwarded this to the author of the installer for his action.

**Comment by BSOD2600** [comment]
@andermat8  could you post the contents of the registry key HKLM\software\cacti\ ?  I have a hunch the existing install path is C:\ which is why its getting reused for an upgrade.

**Comment by andermat8** [comment]
Looks like it:
![image](https://user-images.githubusercontent.com/29753529/31498952-560e4550-af31-11e7-8386-0d6d15751ed0.png)

Path shows C:, so if I modify this to D: I'll be golden?

**Comment by andermat8** [comment]
Tested,
![image](https://user-images.githubusercontent.com/29753529/31499335-7f1e2cfc-af32-11e7-9d63-0fb51cdb1fa6.png)
Still getting the following performing the upgrade:
![image](https://user-images.githubusercontent.com/29753529/31499372-946d13fc-af32-11e7-97c8-b47756492cab.png)

**Comment by BSOD2600** [comment]
Which cacti installer version are you using?
After changing the Path key, you restarted the installer and it still used C:\ ?

**Comment by andermat8** [comment]
On one Windows 2012 server I'm running 1.1.12 and trying to upgrade to 1.1.25 and on another server I upgraded from 1.1.21 to 1.1.25.  The results are the same for both.  Is there another location in the registry I need to check or in the DB?   This behavior has happened in previous upgrades as well.

**Comment by BSOD2600** [comment]
Found the bug with the installer and it'll be fixed with the next release out shortly.
