### ISSUE TITLE
[1.1.24] Discovery network stuck in "running" state does not return results

### ISSUE THREAD

**Issue by jhonnyx82** [Cacti/cacti#1022]
Hi Everyone,

I have configured and scheduled Discovery processes for all our 56 networks but while most of them are working OK, some discoveries are just stuck in "running".

Cancelling or disabling the discovery doesn't help, and in the **cacti.automation_process** table I see these network listed as "done" but no results are returned (even I am sure there must be as I tried network and SNMP connectivity).

Let me give you some samples

![image](https://user-images.githubusercontent.com/26431888/31345877-71bcbfa0-ad17-11e7-8dd1-2dfd0eb8f2ca.png)

![image](https://user-images.githubusercontent.com/26431888/31345909-852881b4-ad17-11e7-946d-b4166a6b8ba3.png)

![image](https://user-images.githubusercontent.com/26431888/31345937-957f1384-ad17-11e7-9933-c6f607c14763.png)

**Comment by jhonnyx82** [comment]
+ There is no automation process running on the Pollers,

I thought it may be stuck there but it seems that it's not the case

**Comment by jhonnyx82** [comment]
Sorry for posting again, but wanted to give an hint from what I have found:

Normal Behavior seems to be that a master process is called and then opens up a number of threads that runs  the discoveries, each of those are a process on the poller and an entry in the **cacti.automation_process** table.

Seems that for 2 of my pollers the master process fails, the process is closed on the poller and the additional threads also, this implies also that the master process cacti.automation_process entry is removed but the two thread entries not.

Some screenshots here:

Master process starts:
![image](https://user-images.githubusercontent.com/26431888/31347300-30433702-ad1c-11e7-9080-cfec3e8575fe.png)

Master process is started on the poller:
![image](https://user-images.githubusercontent.com/26431888/31347388-7c48b0a0-ad1c-11e7-9040-b3cb9a9c07c9.png)

But then it exits and no thread is started:
![image](https://user-images.githubusercontent.com/26431888/31347424-9dd7bbf8-ad1c-11e7-90f6-0bd51c70d0db.png)

in **cacti.automation_process** the entries are still there ... but the master process entry is removed:
![image](https://user-images.githubusercontent.com/26431888/31347451-b7f1eedc-ad1c-11e7-9975-1afb192e16af.png)

**Comment by jhonnyx82** [comment]
I tried launch manually the discovery process on the remote pollers that are not working and this is the result...any thought?

Seems like the thread fails and never really starts, meanwhile the master process closes and remove its entry from the automation_process table, but this does not happen for the threads that never starts and doesnt remove their own entry in the automation_process table

```
# sudo -u apache /bin/php -q /var/www/html/cacti/poller_automation.php --poller=5 --network=18 --force --debug
Thread master about to launch collector threads
Killing any prior running threads
Removing any orphan entries
11/Oct/2017 15:25:53 - AUTOM8 Network Discover is now running for Subnet Range '18'
A Total of 254 IP Addresses Primed
Automation will use 2 Threads
Launching Thread 1
11/Oct/2017 15:25:54 - POLLER: Poller[5] DEBUG: About to Spawn a Remote Process [CMD: /bin/php, ARGS: -q /var/www/html/cacti/poller_automation.php --poller=5 --thread=1 --network=18 --force --debug]
Launching Thread 2
11/Oct/2017 15:25:54 - POLLER: Poller[5] DEBUG: About to Spawn a Remote Process [CMD: /bin/php, ARGS: -q /var/www/html/cacti/poller_automation.php --poller=5 --thread=2 --network=18 --force --debug]
Checking for Running Threads
Found 0 Threads
```

**Comment by cigamit** [comment]
First, on the remote data collector, you should do some testing.  First make a backup copy of poller_automation.php to something like poller_automation_test.php.  Then, edit this poller_automation_text.php and where it runs 'exec_background', simply comment it out.

Then, in one window, force the master process start again, and in another window, run the debug version of the child threads and look for any apparent errors, and post what you find.

Optionally, you can place the poller_automation.php file into debug mode Console > Settings > General, and check the debug log on the remote data collection.

On a follow-up note, I'm glad to see such a large implementation of the new Cacti.

**Comment by jhonnyx82** [comment]
Thank you for your input, before I post any data allow me to say that I am happy to provide my feedback on our CACTI deployment. It consists of 5 pollers in several continents: 3 in Europe, 1 in NA and 1 in ASIA.

The issue is experienced on the pollers in ASIA and NA (main poller is in Europe).

I wrote that because the test you suggested produced a positive result, so I commented both the exec_background operations and ran the master process manually and immediately after the thread manually too.

Surprisingly everything is going as it should be : 

- Master process created a tmaster task in the autmation.process tab of the main poller cacti database
- After manually running one thread process, the master process identified it and kept on running

From some test I noticed that the operation fail if there is more than 5 seconds difference from the start of the master process and the threads, hence I have a feeling that it may be related to some delay with the communication to the database on the main poller (remember these 2 are some continents away, so latency may be up to 150 msec  while on the others in Europe is barely 30-40 msec).

Let me give you anyway some screenshot as you requested:

Failed attempt ( more than 5 seconds away)
```
# date
Thu Oct 12 13:06:36 UTC 2017
# sudo -u apache /bin/php -q /var/www/html/cacti/poller_automation_test.php --poller=4 --network=28 --force --debug
Thread master about to launch collector threads

# date
Thu Oct 12 13:06:43 UTC 2017
# sudo -u apache /bin/php -q /var/www/html/cacti/poller_automation_test.php --poller=4 --thread=1 --network=28 --force --debug
12/Oct/2017 13:06:50 - AUTOM8 Network XXXXX 1 Finished, 0 IPs Scanned, 0 IPs Responded to Ping, 0 Responded to SNMP, 0 Device Added, 0 Graphs Added to Cacti
```

Successful attempt (up to 5 seconds away)

```
# date
Thu Oct 12 13:08:10 UTC 2017
# sudo -u apache /bin/php -q /var/www/html/cacti/poller_automation_test.php --poller=4 --network=28 --force --debug
Thread master about to launch collector threads
Killing any prior running threads
NOTE: Process 3836 claims to be running but not found
Removing any orphan entries
12/Oct/2017 13:08:17 - AUTOM8 Network Discover is now running for Subnet Range '28'
A Total of 254 IP Addresses Primed
Automation will use 2 Threads
Launching Thread 1
Launching Thread 2
Checking for Running Threads
Found 1 Threads
Found 1 Threads

# date
Thu Oct 12 13:08:15 UTC 2017
# sudo -u apache /bin/php -q /var/www/html/cacti/poller_automation_test.php --poller=4 --thread=1 --network=28 --force --debug
Device: 10.xx.x.254, Checking DNS: Found 'xxxxxx', Status: Already in Cacti
Device: 10.xx.x.253, Checking DNS: Not found, Status: Not in Cacti, Ping:  No response
Device: 10.xx.x.252, Checking DNS: Not found, Status: Not in Cacti, Ping:  No response
Device: 10.xx.x.251, Checking DNS: Not found, Status: Not in Cacti, Ping:  No response
Device: 10.xx.x.250, Checking DNS: Not found, Status: Not in Cacti, Ping:  No response

```

**Comment by cigamit** [comment]
Hmm, it looks more like there is some issue with the ipaddress prepping, that no ip's are primed, or maybe someone else is removing the entries.  It's like there  might be a rogue DELETE somewhere.  We need to review the automation code and see if there is some issue with DELETE sql statements.

**Comment by jhonnyx82** [comment]
Hi,

Just wanted to give an update for this topic: 

I have tried also with the latest version of cacti (1.1.27) and the problem persist.

As I mentioned it is related only to the pollers that I have on sites that are around 200 ms "far" from the main poller, so I suspect that it may be a timeout on the master process while the thread are started (since they both create entries in the main poller database).

If you need more test please let me know, I will perform them starting monday but I am happy to make this work as I have now a fully (Wannabe :) ) automated Cacti

**Comment by cigamit** [comment]
Hopefully you have time in December.  Honestly, that will be my first opportunity to spend any quality time on this.

**Comment by jhonnyx82** [comment]
Thanks for your efforts, I hope this can get fixed on any of the upcoming releases (and that it's still not considered as **unverified** )

**Comment by jhonnyx82** [comment]
Version 1.1.28

Problem is still there

**Comment by cigamit** [comment]
See my comments on your /etc/php.ini from the other post.  Let's look for errors.  Also, what is your default max_execution_time in php.ini?

**Comment by jhonnyx82** [comment]
Thanks for your help,

**max_execution_time** in PHP is set to _30 seconds_ for all pollers.

Do you suggest increasing it for the remote pollers affected?

**Comment by cigamit** [comment]
The RTT should have no impact on this.  It really does not matter.

**Comment by jhonnyx82** [comment]
Thanks for the reply.

If you wish me to try anything on my setup let me know.

**Comment by jhonnyx82** [comment]
Happy new year,

Do you have any tip on what should I try? Probably @cigamit you had no time to work on this but let me know if you need any debug or information or if I should try modifying any parameter on our PHP/MARIADB/APACHE setup.

Thanks

**Comment by cigamit** [comment]
I'm working on things today.  I'll need for you to setup the error_log=/tmp/php_errors.log in /etc/php.ini on each of the pollers and then track that for errors if you have not done so already.  If you can get me some details that will help.  Also, when they are stuck has the process been removed from the remote system, or is it in fact no longer running?  Let me know ASAP as I have today and tomorrow.

**Comment by jhonnyx82** [comment]
Thanks for your reply,

I enabled the error logging as you suggested but for both pollers there is no log entry during and after the automation is launched.

When I start a discovery happens the following:

- The master process is triggered, it launch the threads for the discovery process (in the meanwhile there is still no entry on the **automation_process** table of the main poller)
- The discovery processes terminates beforehand (almost immediately) and the **automation_process** table contains for a second the entry for the master process
- refreshing 2 -3 seconds later the **automation_process** table I can see that the master process entry is removed and the threads entries are there but referring to Process ID that are already terminated and being also disjoint from the referring master process entry (that was already removed).

I hope this helps, in case let me know what else can I do to provide you other info and please consider that this happens only to pollers that are subject to higher latency than other pollers, my lucky guess is that the time necessary to write the entries in the **automation_process** table is too long for the php process to read from it and start the necessary discovery threads but I am just guessing.

**Comment by cigamit** [comment]
Yea, that helps.  I'll review the logic and see if we can include this in tomorrows release.  Keep your ears to the ground.

**Comment by cigamit** [comment]
So, when you force them to run from the GUI, is all okay?

**Comment by jhonnyx82** [comment]
No unfortunately not,

I were able to run only with the testing method you wrote on Oct 12, 2017.

No other way works, scheduled or manually.

**Comment by cigamit** [comment]
Okay, please attempt to use the lastest two files.  So, that is interesting that the remote agent is not working.  You might want to check the apache log on the remote server when forcing a run if these files don't get it.

**Comment by cigamit** [comment]
The I've changed a few of the output statements from a 'print' to a 'cacti_log()' to help debug also.

**Comment by jhonnyx82** [comment]
I included the latest poller_automation.php as you requested and ran some tests.

I added it to all my pollers including the main poller.

I ran a manual discovery but the outcome is the same as I described, in the apache error_log I found no entries, in the access_log i found the following : 

(ip of main cacti poller) - - [13/Jan/2018:18:17:45 +0000] "GET /cacti/remote_agent.php?action=discover&network=26 HTTP/1.0" 200 - "-" "-"

(ip of main cacti poller) - - [13/Jan/2018:20:47:33 +0000] "GET /cacti/remote_agent.php?action=discover&network=26 HTTP/1.0" 200 - "-" "-"

(ip of main cacti poller) - - [13/Jan/2018:20:55:06 +0000] "GET /cacti/remote_agent.php?action=discover&network=26 HTTP/1.0" 200 - "-" "-"

**Comment by jhonnyx82** [comment]
I would like to add that I ran them also manually so as follow : 

I opened 3 ssh console where on the first I ran the following command for the master process: 

> sudo -u apache /bin/php -q /var/www/html/cacti/poller_automation.php --poller=4 --network=32 --force

and right **1 second** after running the master process, on the second and third ssh console I ran 

> sudo -u apache /bin/php -q /var/www/html/cacti/poller_automation.php --poller=4 --thread=1 --network=32 --force
sudo -u apache /bin/php -q /var/www/html/cacti/poller_automation.php --poller=4 --thread=2 --network=32 --force

This created the following entries in the **automation_process table**

![image](https://user-images.githubusercontent.com/26431888/34910110-ce78788c-f8ae-11e7-97dd-76fb7709da0b.png)

And the discovery is ongoing...

 Now considering that there are 4 threads, while my discovery setup works with 2 threads and 2 threads i ran manually, I believe that the ones I ran manually populated the list of ip address to query without running into the delay problems that I can see when I trigger only the master process.

Also, same entries on accessl_log and no entries on error_log

**Comment by cigamit** [comment]
The way that the process should work is that you run the master process, and the threads take off.  So, to manually run you run 'php -q poller_automation.php --network-id=X --force --debug'.  The poller_id will be take from config.php.  Even though --poller is an option, should should not have to specify it.

What happens when you do that from the command line?

**Comment by cigamit** [comment]
Also, on the remote poller, if there are issues, you should be seeing more entries in the cacti.log on the remote data collector/poller.

**Comment by jhonnyx82** [comment]
This is the screenshot of the CACTI log when I execute the command as you mentioned:

![image](https://user-images.githubusercontent.com/26431888/34911056-21e4fdfc-f8c2-11e7-98ee-6f03d1e20685.png)


At console instead this is the log:

# sudo -u apache /bin/php -q /var/www/html/cacti/poller_automation2.php --poller=4 --network=32 --force --debug
Thread master about to launch collector threads
Killing any prior running threads
13/Jan/2018 23:28:49 - AUTOM8 WARNING: Process 18860 claims to be running but not found for Network ID: 32
13/Jan/2018 23:28:49 - AUTOM8 WARNING: Process 18858 claims to be running but not found for Network ID: 32
Removing any orphan entries
13/Jan/2018 23:28:49 - AUTOM8 Network Discover is now running for Subnet Range '32'
A Total of 254 IP Addresses Primed
Automation will use 2 Threads
Launching Thread 1
13/Jan/2018 23:28:50 - POLLER: Poller[4] DEBUG: About to Spawn a Remote Process [CMD: /bin/php, ARGS: -q /var/www/html/cacti/poller_automation.php --poller=4 --thread=1 --network=32 --force --debug]
Launching Thread 2
13/Jan/2018 23:28:50 - POLLER: Poller[4] DEBUG: About to Spawn a Remote Process [CMD: /bin/php, ARGS: -q /var/www/html/cacti/poller_automation.php --poller=4 --thread=2 --network=32 --force --debug]
Checking for Running Threads
Found 0 Threads

**Comment by cigamit** [comment]
Also, since you don't mention it, do you have selinux enabled?  It seems more like the processes are not launching.

**Comment by jhonnyx82** [comment]
SeLinunx is disabled

```
# sestatus
SELinux status:                 disabled
```

**Comment by cigamit** [comment]
Have you rebooted since you disabled it?  Also, is there anything in the /tmp/error_log?

**Comment by cigamit** [comment]
This is smelling like a configuration issue.  When you run by hand, what is the poller_id of the entries that remain in the table and have to be cleared?  Also, what is the poller_id in $config.php?

**Comment by cigamit** [comment]
The other issue could be that the subnet ranges are not being primed properly.  What you can do is manually place an 'exit;' right after the priming is done.  Do that, and the report if the ip_addresses are in the 'automation_ips' table.  The log message is telling us that no ip's were scanned for each thread, which might mean that how we prime the database may be flawed.  If that is the case, I need your ip range for that network.  You can obfuscate the digits.

**Comment by cigamit** [comment]
Lastly, check the timezone setting in /etc/php.ini on the remote data collectors.  It's a long shot, and I'm not certain it would have any impact.  It all depends on if we are using date() PHP function calls in the poller.

**Comment by jhonnyx82** [comment]
- SeLinux was disabled and after the system was rebooted
- Poller ID is coherent with the poller ID of the remote poller I am working on and network ID too, performing the scan on another poller that is in the same continent with the same command (poller ID and network ID are obviously different) works OK
- date.timezone = "UTC" in /etc/php.ini for all pollers (date is synced to the same NTP server globally)
- > What you can do is manually place an 'exit;' right after the priming is done. Do that, and the report if the ip_addresses are in the 'automation_ips' table.
  -

**Comment by jhonnyx82** [comment]
The issue is now fixed! 

Thank you very much on spending time on this and providing a viable solution, very much appreciated!

**Comment by netniV** [comment]
Good to know! Can you close the issue now then as well?
