### ISSUE TITLE
[Cacti-1.1.25] Dutch language not working

### ISSUE THREAD

**Issue by djrodek** [Cacti/cacti#1024]
After upgrade from 1.1.24 the dutch language is not working. I tested to switch to french and that worked. If i choose dutch the language is english.

**Comment by cigamit** [comment]
Please check for some more recent updates.  There have been several dutch language updates recently.  Check the permissions of your mo file as well.  You may simply have a permissions issue.  I suspect it's that.  Once you resolve this, please close this ticket.

**Comment by djrodek** [comment]
The permissions where fine. After updating the mo file with the current version from Github it works! Thanks!
