### ISSUE TITLE
Poller broken after upgrade to 1.1.25

### ISSUE THREAD

**Issue by eventhorizon5** [Cacti/cacti#1025]
Hi, we're trying to upgrade our Cacti installation from 0.8.8h to 1.1.25, but after the upgrade the poller breaks.  The poller.php output repeatedly shows "Waiting on 4 of 4 pollers" when running, and if I launch a cmd.php poller process manually, this shows up and it quits after:

/usr/bin/php5-cgi -q "/var/www/cacti-1.1.25/cmd.php" --poller=1 --first=0 --last=337 --mibs
<b>Warning</b>:  session_start(): Cannot send session cookie - headers already sent in <b>/var/www/cacti-1.1.25/include/global.php</b> on line <b>262</b><br />
<b>Warning</b>:  session_start(): Cannot send session cache limiter - headers already sent in <b>/var/www/cacti-1.1.25/include/global.php</b> on line <b>262</b><br />

Does anyone have an ideas what could be causing this issue?

**Comment by cigamit** [comment]
I suspect that you did not upgrade properly.  If you upgraded Cacti properly, it will not use sessions inside of the poller functions.  So, something is dreadfully wrong with your upgrade.

I suggest that you will get more/better response from the forums that from here.  I suggest you look at your config.php, or if you made any modifications to global.php, you should reverse them.  You should never need to update global.php in a modern Cacti install.

In any even, we would need more details, though as I suspect it a PEBKAC.

**Comment by eventhorizon5** [comment]
Thanks for your help, and I posted this on the forum.  One thing to add, is that when upgrading to version 1.0.6, the poller appears to work fine.

**Comment by eventhorizon5** [comment]
After investigating, I found that the poller breaks with version 1.1.4.  The poller shows this at the end of the run:

2017-10-12 12:20:01 - POLLER: Poller[1] Maximum runtime of 298 seconds exceeded. Exiting.
2017-10-12 12:20:01 - SYSTEM STATS: Time:298.8465 Method:cmd.php Processes:4 Threads:N/A Hosts:99 HostsPerProcess:25 DataSources:2233 RRDsProcessed:0

**Comment by cigamit** [comment]
Sure, put cmd.php into debug mode and see what is going on.  Else try spine.  I think you will find it much more resilient.

**Comment by eventhorizon5** [comment]
I switched to Spine and it's working properly - I set it up wrong last time, which is why I was trying to get cmd.php working.  Cmd.php doesn't show anything in debug mode.

**Comment by cigamit** [comment]
My guess is it's just slow cmd.php.  We can't just abandon it.  But any serious install is going to use it anyway.  I'm going to close this for now since you are back in business.
