### ISSUE TITLE
[1.1.24] Poller - illegal attempt to update using time

### ISSUE THREAD

**Issue by CRCinAU** [Cacti/cacti#1026]
Trying a fresh install of cacti on a fresh install of F27:

$ rpm -qa | egrep '(cacti|rrd)'
rrdtool-1.7.0-4.fc27.x86_64
cacti-1.1.24-1.fc27.noarch

After setting up two hosts, I have noticed that the graphs do not update.

From debugging the poller, I see the first loop works fine:
2017/10/10 15:00:02 - POLLER: Poller[1] NOTE: Poller Int: '300', Cron Int: '300', Time Since Last: '301.11', Max Runtime '298', Poller Runs: '1'
Waiting on 1 of 2 pollers.
OK u:0.00 s:0.01 r:0.00
OK u:0.00 s:0.01 r:0.00
OK u:0.00 s:0.01 r:0.00
....
OK u:0.01 s:0.02 r:1.30
OK u:0.01 s:0.02 r:1.30
2017/10/10 15:00:04 - SYSTEM STATS: Time:2.4305 Method:cmd.php Processes:4 Threads:N/A Hosts:2 HostsPerProcess:1 DataSources:30 RRDsProcessed:24

The second and any further run of the poller will error with time problems:
2017/10/10 15:05:01 - POLLER: Poller[1] NOTE: Poller Int: '300', Cron Int: '300', Time Since Last: '299.93', Max Runtime '298', Poller Runs: '1'
Waiting on 1 of 2 pollers.
ERROR: /usr/share/cacti/rra/spin-gw_crc_id_au_cpu_nice_1.rrd: illegal attempt to update using time 1507608302 when last update time is 1507647602 (minimum one second step)
ERROR: /usr/share/cacti/rra/spin-gw_crc_id_au_cpu_system_2.rrd: illegal attempt to update using time 1507608302 when last update time is 1507647602 (minimum one second step)
ERROR: /usr/share/cacti/rra/spin-gw_crc_id_au_cpu_user_3.rrd: illegal attempt to update using time 1507608302 when last update time is 1507647602 (minimum one second step)
.....
2017/10/10 15:05:03 - SYSTEM STATS: Time:1.2364 Method:cmd.php Processes:4 Threads:N/A Hosts:2 HostsPerProcess:1 DataSources:30 RRDsProcessed:24

I'm not sure if this is fixed in 1.1.25 - which I note was released on Sept 27 - as I don't see anything in the changelog that may relate to this.

I'm also not 100% sure if this is related to cacti or rrdtool. The error message is from rrdtool - but that's about all I've been able to find out.

Fedora BZ report: https://bugzilla.redhat.com/show_bug.cgi?id=1500441

**Comment by CRCinAU** [comment]
as a note, if I remove all .rrd files, the first run of the poller is always successful again. After the first run, the illegal attempts occur.

**Comment by mortenstevens** [comment]
Please check your date.timezone value in /etc/php.ini

**Comment by CRCinAU** [comment]
That did it :(

Is there any reason why it picks such a different clock between the two runs? I seemed to notice ~8 hours difference at times - but that doesn't seem to align with any timezone I could think it was trying to use...

**Comment by cigamit** [comment]
Closing, though we should put that in the installation.

**Comment by CRCinAU** [comment]
Should I lodge a new RFE to get the installer scripts check a timezone is set?

**Comment by cigamit** [comment]
Please.
