### ISSUE TITLE
Cacti 1.1.26 "Auto" Log administration refresh broken.

### ISSUE THREAD

**Issue by ikorzha** [Cacti/cacti#1028]
How to replicate:
Click Console-> System Utilities -> Log Administration -> Change refresh to 5 sec and wait for refresh to happen.

End result after 5 sec attached:
![empty-log-page](https://user-images.githubusercontent.com/11211789/31475144-23fa9834-aecd-11e7-8367-2262ce695142.gif)

Tested in Firefox and Chrome with cache cleared.

**Comment by cigamit** [comment]
This is resolved.  Thanks for bringing to our attention and living on the edge 👍
