### ISSUE TITLE
Script/Command with multiple output fields not working

### ISSUE THREAD

**Issue by shavenne** [Cacti/cacti#103]
Me again! ;)

It seems that data input methods with multiple output fields doesn't work.
In the log their output seem fine like this for "Unix - Get Load Average":
_2016-12-29 05:51:04 - POLLER: Poller[1] Device[1] DS[65] CMD: perl /var/www/cacti/scripts/loadavg_multi.pl, output: 1min:0.01 5min:0.03 10min:0.00_
But the rrd-file is not being created and I get his warning in the log:
_WARNING: Poller Output Table not Empty. Issues Found: 2, Data Sources: (DS[64]), (DS[65])_
([64] is also one which is not working which is a input method I've made for myself).
It seems there is no other error or warning related to that.

Methods with a single output field like "Unix - Ping Host" are working fine.

**Comment by smiles1969** [comment]
+1 on this.. I'm also seeing issues with the latest commits where scripts are not updating the rrd files. Cacti log also showing same indications, and rrd_name field in poller_output table has no data for these:

mysql> select * from poller_output;
+---------------+----------+---------------------+-----------------------------------------------------------+
| local_data_id | rrd_name | time                | output                                                    |
+---------------+----------+---------------------+-----------------------------------------------------------+
|          1074 |          | 2016-12-29 10:05:52 | vh:20 vh_state:19 tools_run:17 tools_nrun:0 tools_ninst:3 |
|          1128 |          | 2016-12-29 10:05:52 | vh:20 vh_state:19 tools_run:17 tools_nrun:0 tools_ninst:3 |
|           681 |          | 2016-12-29 10:05:25 | Ping:15.988 Download:263.26 Upload:84.38                  |
|           682 |          | 2016-12-29 10:05:25 | Ping:15.841 Download:367.05 Upload:82.69                  |
|           706 |          | 2016-12-29 10:05:25 | vh:25 vh_state:22 tools_run:19 tools_nrun:3 tools_ninst:3 |
|          1127 |          | 2016-12-29 10:05:25 | vh:25 vh_state:22 tools_run:19 tools_nrun:3 tools_ninst:3 |
|          1125 |          | 2016-12-29 10:05:52 | vh:29 vh_state:27 tools_run:25 tools_nrun:2 tools_ninst:2 |
|           509 |          | 2016-12-29 10:05:02 | Ping:16.061 Download:368.57 Upload:81.96                  |
|           510 |          | 2016-12-29 10:05:02 | Ping:5.958 Download:590.57 Upload:474.68                  |
|             5 |          | 2016-12-29 10:05:02 | 1min:0.14 5min:0.26 10min:0.29                            |
|          1126 |          | 2016-12-29 10:05:52 | vh:29 vh_state:27 tools_run:25 tools_nrun:2 tools_ninst:2 |
+---------------+----------+---------------------+-----------------------------------------------------------+
11 rows in set (0.04 sec)

**Comment by cigamit** [comment]
So far, I am unable to reproduce.  Keeping open for now until we get a pull request, or are able to reproduce.

**Comment by cigamit** [comment]
smiles1969, that helps a lot.  I think I can find where this is happening now.

**Comment by smiles1969** [comment]
2016-12-29 00:16:08 - SPINE: Poller[1] Device[30] TH[1] DS[682] SCRIPT: /var/www/html/cacti/scripts/Speedtest_Chicago.sh , output: Ping:16.15 Download:199.31 Upload:101.65
2016-12-29 00:16:08 - SPINE: Poller[1] DEVDBG: SQL:'INSERT INTO poller_output (local_data_id, rrd_name, time, output) VALUES (681,'','2016-12-29 00:15:34','Ping:16.134 Download:213.88 Upload:99.41'),(682,'','2016-12-29 00:15:34','Ping:16.15 Download:199.31 Upload:101.65') ON DUPLICATE KEY UPDATE output=VALUES(output)'
2016-12-29 00:16:08 - SPINE: Poller[1] DEVDBG: SQL:'UPDATE poller_item SET rrd_next_step=IF((rrd_next_step-300)>=0, (rrd_next_step-300), (rrd_step-300)) WHERE host_id=30 AND poller_id=1'
2016-12-29 00:16:08 - SPINE: Poller[1] Device[30] TH[1] Total Time:    34 Seconds
2016-12-29 00:16:08 - SPINE: Poller[1] DEVDBG: SQL:'UPDATE host SET polling_time=1482992168.301 - 1482992134.578 WHERE id=30'
2016-12-29 00:16:08 - SPINE: Poller[1] Device[30] TH[1] DEBUG: HOST COMPLETE: About to Exit Device Polling Thread Function

**Comment by cigamit** [comment]
Hmm, that did not help, and was not the output I was looking for.  I'm looking for something like:

Parsed MULTI output field...

**Comment by cigamit** [comment]
But again, this helps :)

**Comment by smiles1969** [comment]
I threw some extra cacti log lines in lib/poller.php to find out why I'm not getting to the Parsed MULTI log entry and it's not passing line 431 if (isset($rrd_field_names[$item['data_template_id'] . '_' . $matches[0]])) { check

**Comment by smiles1969** [comment]
I would assume it was this change that broke it:

c5e1e8a0b3ea95bfc00db8ef875231a21b3d49a5

Updates for remote polling 3 days ago

**Comment by cigamit** [comment]
Yea, that is it.  Working on it now.

**Comment by cigamit** [comment]
Just fixed it I think.  Let me know.

**Comment by dabeani** [comment]
nope... u must change the fielt from 'data_source_name' to 'data_source_names' i think...

Error message:
2016-12-29 19:00:02 - DBCALL ERROR: SQL Assoc Failed!, Error: Unknown column 'data_source_name' in 'field list'
2016-12-29 19:00:02 - DBCALL ERROR: SQL Assoc Failed!, Error:1054, SQL:"SELECT SQL_NO_CACHE CONCAT(data_template_id, "_", data_name) AS keyname, data_source_name FROM poller_data_template_field_mappings"

**Comment by cigamit** [comment]
Okay, just a few more minutes.

**Comment by cigamit** [comment]
Try again.

**Comment by dabeani** [comment]
so far, i dont see any more errors while poller is running...

**Comment by cigamit** [comment]
Cool.  Go ahead and close once you have confirmed all is okay.

**Comment by smiles1969** [comment]
Still not updating rrd files for me

**Comment by cigamit** [comment]
Is your poller_data_template_field_mappings table full of records?

**Comment by cigamit** [comment]
smiles1969, here is what I need you to do.  Pick one of the data templates, and then output the contents of the poller_data_template_field_mappings for me, then show me the raw output of the script for those data templates.

**Comment by smiles1969** [comment]
my poller_data_template_field_mappings has NO records.

I've been reviewing the changes to cacti.sql to see if I've missed something applying the database changes.

Not seeing anything in the logs that are useful.

**Comment by dabeani** [comment]
i habe now (i think) a problem which is from th same source?

2016-12-29 20:44:10 - POLLER: Poller[1] Parsed MULTI output field 'Upload:25.65' [map Upload->U]
2016-12-29 20:44:10 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php: 495 process_poller_output)(/lib/poller.php: 432 CactiErrorHandler)(/lib/functions.php: 4184 cacti_debug_backtrace)
2016-12-29 20:44:10 - ERROR PHP WARNING: Illegal string offset 'data_source_name' in file: /usr/share/cacti/lib/poller.php on line: 432
2016-12-29 20:44:10 - POLLER: Poller[1] Parsed MULTI output field 'Download:13.23' [map Download->D]
2016-12-29 20:44:10 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php: 495 process_poller_output)(/lib/poller.php: 432 CactiErrorHandler)(/lib/functions.php: 4184 cacti_debug_backtrace)
2016-12-29 20:44:10 - ERROR PHP WARNING: Illegal string offset 'data_source_name' in file: /usr/share/cacti/lib/poller.php on line: 432
2016-12-29 20:44:10 - POLLER: Poller[1] Parsed MULTI output field 'Ping:27.34' [map Ping->P]
2016-12-29 20:44:10 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php: 495 process_poller_output)(/lib/poller.php: 432 CactiErrorHandler)(/lib/functions.php: 4184 cacti_debug_backtrace)
2016-12-29 20:44:10 - ERROR PHP WARNING: Illegal string offset 'data_source_name' in file: /usr/share/cacti/lib/poller.php on line: 432

Output from my Database:
CREATE TABLE `poller_data_template_field_mappings` (
  `data_template_id` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `data_name` varchar(25) NOT NULL DEFAULT '',
  `data_source_names` varchar(120) NOT NULL DEFAULT '',
  `last_updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Tracks mapping of Data Templates to their Data Source Names';

--
-- Dumping data for table `poller_data_template_field_mappings`
--

INSERT INTO `poller_data_template_field_mappings` (`data_template_id`, `data_name`, `data_source_names`, `last_updated`) VALUES
(11, '10min', 'load_15min', '2016-12-29 18:39:19'),
(11, '1min', 'load_1min', '2016-12-29 18:39:19'),
(11, '5min', 'load_5min', '2016-12-29 18:39:19'),
(13, 'kilobytes', 'mem_buffers', '2016-12-29 18:39:19'),
(15, 'kilobytes', 'mem_swap', '2016-12-29 18:39:19'),
(16, 'proc', 'proc', '2016-12-29 18:39:19'),
(17, 'users', 'users', '2016-12-29 18:39:19'),
(18, 'out_ms', 'ping', '2016-12-29 18:39:19'),
(52, 'pool', 'pool', '2016-12-29 18:39:19'),
(52, 'sensor1', 'sensor1', '2016-12-29 18:39:19'),
(52, 'sensor2', 'sensor2', '2016-12-29 18:39:19'),
(52, 'sensor3', 'sensor3', '2016-12-29 18:39:19'),
(67, 'Download', 'Download', '2016-12-29 18:39:19'),
(67, 'Ping', 'Ping', '2016-12-29 18:39:19'),
(67, 'Upload', 'Upload', '2016-12-29 18:39:19');

i hope you can find the Problem.

**Comment by smiles1969** [comment]
I made the database changes manually, not with upgrade_database.php.

When I try to run it, I get this:

root@ctcv-cacti2:/var/www/html/cacti/cli# php upgrade_database.php 
Your Cacti is already up to date.

Do I have to use the forcever with an argument to re-run it?

**Comment by cigamit** [comment]
Yes --forcever=1.0.0

**Comment by cigamit** [comment]
You guys all set now?

**Comment by dabeani** [comment]
root@bmk-cacti-01:/usr/share/cacti/cli# php -q upgrade_database.php --forcever=1.0.0
Your Cacti is already up to date.

so, there was no automatic upgrade of the Database. But i added already (i checked now 2 times the History) the missing fields and removed also the fields which should be removed....

**Comment by smiles1969** [comment]
Doesn't appear to run even with force

root@ctcv-cacti2:/var/www/html/cacti/cli# php upgrade_database.php --forcever=1.0.0
Your Cacti is already up to date.

**Comment by cigamit** [comment]
Oh, my bad :)

--forcever=my_old_version

if running 0.8.8h, then you would:

--forcever=0.8.8h

**Comment by smiles1969** [comment]
What if I was already on 1.0.0?

**Comment by smiles1969** [comment]
I ran it with --forcever=0.8.8h and I now have mappings. Will see what happens now with the multi field script

**Comment by cigamit** [comment]
The database_upgrade.php script is designed to rerun from an old version.  It helps with you guys helping out testing.

**Comment by smiles1969** [comment]
Some times that 5 minute polling cycle seems like forever... tick tick... LOL

**Comment by smiles1969** [comment]
mysql> select * from poller_data_template_field_mappings where data_template_id like '61';
+------------------+-----------+------------------+---------------------+
| data_template_id | data_name | data_source_name | last_updated        |
+------------------+-----------+------------------+---------------------+
|               61 | Download  | Download         | 2016-12-29 14:13:21 |
|               61 | Ping      | Ping             | 2016-12-29 14:25:09 |
|               61 | Upload    | Upload           | 2016-12-29 14:25:09 |
+------------------+-----------+------------------+---------------------+
3 rows in set (0.00 sec)

root@ctcv-cacti2:/var/www/html/cacti/scripts# ./Speedtest_Brd.sh 
Ping:10.758 Download:597.97 Upload:407.69

**Comment by cigamit** [comment]
Ouch.  That is a change to the upgrade logic from last night.  Have to fix it.

**Comment by cigamit** [comment]
Just fixing the lib/database.php to handle the upgrade script.  Try again with the latest updates.

**Comment by dabeani** [comment]
i created a request for a small fix. after that i am able to reuse the multi field script.

**Comment by cigamit** [comment]
Yea, I saw it.

**Comment by shavenne** [comment]
Yeah. DB Upgrade worked and the polling is also working now :)

**Comment by smiles1969** [comment]
Still not working for me after this update. And it's still not getting past the check on line 431

if (isset($rrd_field_names[$item['data_template_id'] . '_' . $matches[0]])) {

Do I need up re-run the database upgrade again? My mappings looked right??

**Comment by dabeani** [comment]
Same here, all things what we discussed about is now working for me :)

**Comment by cigamit** [comment]
smiles1969, when I look at your poller_output and the field mappings, it should be working.  Can you attached your instrumented code and log output?

**Comment by smiles1969** [comment]
The problem is the cacti.sql file creates the table "data_source_name" and the query is "data_source_names"

I renamed my table to use "data_source_names" and its working now.

**Comment by cigamit** [comment]
Thanks for all the help on this one guys.

**Comment by smiles1969** [comment]
I'm going to assume you either need to change the query or the cacti.sql to match.

**Comment by cigamit** [comment]
Oh, I missed that point entirely.  I've standardized on 'names' since there can be more than one, and additionally, I've widened to 255 characters.
