### ISSUE TITLE
v1.1.26 webpage breaks after auto refresh in "preview" mode

### ISSUE THREAD

**Issue by SergejLT** [Cacti/cacti#1039]
url -> /cacti/graph_view.php?**action=preview** 
webpage breaks after auto refresh ->

![cacti_2](https://user-images.githubusercontent.com/32635039/31711945-618c04fa-b402-11e7-8a27-0d23031ea775.PNG)

 url -> /cacti/graph_view.php
webpage after auto refresh not breaking

![cacti_1](https://user-images.githubusercontent.com/32635039/31711993-83729ce6-b402-11e7-85e8-021fd439d6a7.PNG)

**Comment by DavidLiedke** [comment]
I can confirm this issue.

**Comment by cigamit** [comment]
Just in paw?

**Comment by SergejLT** [comment]
in "modern" the same

**Comment by DavidLiedke** [comment]
I use the Modern Template.

**Comment by cigamit** [comment]
Yea, so htmlspecialchars() has an option not to double escape.  Seem's it does not always work.  I'm trying strip_tags() as we are really trying to prevent XSS and this should handle that pretty well.  Please test the lastest update.

**Comment by SergejLT** [comment]
working! thank you

**Comment by ikorzha** [comment]
Cigamit thank you, the fix did fix the F5 refresh problem in graphs and F5 Weathermaps refresh..
