### ISSUE TITLE
Window refresh problems

### ISSUE THREAD

**Issue by eventhorizon5** [Cacti/cacti#1041]
Hi, I'm having an issue with the automatic window refresh in Cacti.  This has been tested with the current version (1.1.26) on both Firefox on Linux, and Chrome on Windows.  In "Tree View", the window refreshes fine, but in both "List View" and "Preview View", the page ends up being blank (usually with a second bar at the top) when automatically refreshing, requiring a manual page refresh for the content to come back.  I've attached a picture of this issue.  Is anyone else experiencing this?  I might try digging deeper to find out what version introduced this issue.

![problem](https://user-images.githubusercontent.com/13081337/31745040-f2cf7900-b426-11e7-9dc6-0c156bdd1227.jpg)

**Comment by cigamit** [comment]
Please update your include/global_session.php from the develop branch.  This was reported earlier today and resolved there.
