### ISSUE TITLE
Superlinks Plugin HTTP 500

### ISSUE THREAD

**Issue by evans-jacob** [Cacti/cacti#1042]
The superlinks plugin is not working with the latest version of cacti, it gives a http 500 error when adding pages.

In the PHP log it gives reference to a MySQL function that has been removed from PHP 7.

**Comment by cigamit** [comment]
You need to be much more specific.  Try again.

**Comment by cigamit** [comment]
Also, we do not provide support for 0.8.x here.  If you are using the old superlinks plugin, best you close this one.
