### ISSUE TITLE
Cacti 1.1.27 fresh install mysql import error

### ISSUE THREAD

**Issue by Exaltia** [Cacti/cacti#1043]
Hello.
I tried to install a fresh cacti 1.1.27 on a mysql.
Server version: 5.7.19-0ubuntu0.16.04.1 (Ubuntu)
Here is the server config:
[tempsqlconfig.txt](https://github.com/Cacti/cacti/files/1407352/tempsqlconfig.txt)
Command used : mysql cacti -h sqlxx.somewhere.com -u cacti -p < ./cacti.sql
Error : 
ERROR 1067 (42000) at line 286: Invalid default value for 'next_start'
(line 286 is line 308 from a vim point of view)
The line :
`next_start` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',

The same default value is on line (still on a vim point of view) : 316, 327, 342, 1334, 1377, 1744, 1749, 1831, 1832, 2045; 2046, 2059, 2125, 2137, 2159, 2192; 2206; 2207, 2625

Is there a workaround? is it ok if i remplace all those values with 1970-01-01 00:00:01.000000 ?

According to https://dev.mysql.com/doc/refman/5.7/en/datetime.html:

> and the range for TIMESTAMP values is '1970-01-01 00:00:01.000000' to '2038-01-19 03:14:07.999999'

**Comment by cigamit** [comment]
We are going to be working on this issue likely over the winter break.  In the mean time, edit your /etc/my.cnf and set:

`sql_mode=NO_ENGINE_SUBSTITUTION`

Then restart MySQL/MariaDB, and your problem will be solved.
