### ISSUE TITLE
Trouble deleting Data Input Method Output Fields

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#1045]
Take a look!

![peek 2017-10-23 23-37](https://user-images.githubusercontent.com/12864741/31926426-96faa73e-b84b-11e7-8972-787e7cd2cc37.gif)

**Comment by cigamit** [comment]
Lovely.

**Comment by cigamit** [comment]
Saw the code defect right away.  It affected multiple pages.  Should be fixed good now.

**Comment by cigamit** [comment]
Please confirm, then close.  Thanks!
