### ISSUE TITLE
Have some problems when I install cacti  

### ISSUE THREAD

**Issue by Howard-Chang** [Cacti/cacti#1046]
Hi everyone, I am new in cacti, and I have some problems when I install it.
In the install page it shows the Pre-installation Checks, but I don't have idea to solve it :(
I can't find the module in php and the setting config in mysql.  p,s. I use XAMPP.
![image](https://user-images.githubusercontent.com/19474557/31954748-04b91a30-b919-11e7-9d41-db38e68b0a76.png)
![image](https://user-images.githubusercontent.com/19474557/31954775-12b1eaea-b919-11e7-97dc-31127beb6430.png)

thank you in advance.

**Comment by pautiina** [comment]
Hello.
First write your OS.
All that is red - you need to install in the system.
