### ISSUE TITLE
Add support for full-size-mode for graph images

### ISSUE THREAD

**Issue by thurban** [Cacti/cacti#1047]
CAn we add support for the full-size-mode feature of the rrdtool since 1.3 ( which seems to be the lowest Cacti 1.x supported version), so we don't have to resize images dynamicaly (cycle, columns), but have a native graph ?

The resize makes the graphs blurry which is unpleasant to look at.

From rrdtool manpage:
If you specify the --full-size-mode option, the width and height specify the final dimensions of the output image and the canvas is automatically resized to fit.

**Comment by cigamit** [comment]
I need Andi to take this.  You two are in the same timezone, you should share some beer and get this resolved.  For the GUI to be responsive though, we need to resize as the screen is resized.  So, we can not eliminate entirely, but we can make it better.

**Comment by netniV** [comment]
Is this still an issue?

**Comment by TheWitness** [comment]
If you use SVG instead of PNG, everything will look perfect in all pages and all zoom levels.
