### ISSUE TITLE
Missing "/" in cacti/lib/import.php, which causes import template to fail

### ISSUE THREAD

**Issue by chtay** [Cacti/cacti#1048]
I not sure whether is this already reported or not. If not, here is the finding on both v1.1.26 and v1.1.27.
Under the file of cacti/lib/import.php,
For v1.1.26, it is in line 1320.
For v1.1.27, it is in line 1330.
include_once($config['library_path'] . 'vdef.php');

The include_once for "vdef,php" is missing the "/". Without the "/", the whole include become {TheCactiPhysicalPath}/cacti/libvdef.php instead. When doing "Import Templates", the cacti will fail because it expect to include {TheCactiPhysicalPath}/cacti/libvdef.php instead...which does not exists.

Tested by changing to:
include_once($config['library_path'] . '/vdef.php');
and it works!

**Comment by cigamit** [comment]
Wow, thanks and resolved.
