### ISSUE TITLE
Automation rule enhancement (rule sequence) 

### ISSUE THREAD

**Issue by g1augusto** [Cacti/cacti#1050]
Hi Everyone,

Since I am building up automation for out CACTI monitoring system I think it would be better to give an option to choose the sequence of the rules.

An example: 

Since the rules are matched top down from the  first one in the database to the last, it makes sense to create more specific rules at the top and more generic rule at the bottom to facilitate the regex matching.

our network devices may contain the following words in the hostname : DMZ or DMZSW or SWDMZ to identify a DMZ switch and of course a simple switch contains just SW. Each one of them has a device template

now if the DMZ regex matching rule -*DMZ.* comes first and the generic switch matching rule - .*SW.* , all is fine, if instead it's the opposite, every DMZ switch would be paired by a generic SW template.

I temporarily corrected this by looking at the automation_templates table and reorder manually the indexes in the database, it would be of course better to have such a feature in the web interface.

Also, if someone is thinking about extending the regex match pattern with negative exclusion: consider the amount of match of a simple lookahead against a complex regex match and indeed it can be quite hard.

Thanks!

**Comment by cigamit** [comment]
We've had two requests like this.  One to do a full stop once an exit code is reached, and two for sequencing.  Totally agree.  My next good block of development time will be in December though.

**Comment by jhonnyx82** [comment]
Thanks for looking into this,

I don't mean to profit about your kindness, but could we add an exclusion statement in the automation network definition? 

reason : sometimes High Availability in active/standby devices gets populated twice (obviously) so it would be good to avoid adding the standby unit.

example : 
we have a subnet for management like

10.1.1.0/24
but our Cisco ASA firewalls in HA uses 10.1.1.10 (active) and 10.1.1.11 (standby)
if we scan the whole subnet we get them both and I know we can add ranges (what i am doing currently) but it would be more elegant to just add exclusion, especially when there is more than two or three of them (that would a bit complicate the range generation)

Thanks (btw, this is not so important)

**Comment by cigamit** [comment]
Yea, we will consider for the 1.2 pipeline.

**Comment by TheWitness** [comment]
Related to #412.  @g1augusto, We are doing a major re-design of Automation in 1.3.  It would be good if you could evaluate.  I'm going to mark this complete.  If you feel it's not entirely right, simply open a new issue.
