### ISSUE TITLE
ICMP Ping to and IPv6 address fails to gather data for Ping Latency / CentOS 7.4

### ISSUE THREAD

**Issue by jwomack** [Cacti/cacti#1058]
On a CentOS 7.4 VM, running version cacti 1.1.24, the ping.pl script reports a "U" back to cacti.
Even using the current development branch, ping.pl reports back a "U".

The installed version of ping from iputils-20160308-10.el7.x86_64, reports back a different error message:
ping: ipv6.google.com: Name or service not known

Updating the script to account for the new error message resolves the issue.

`[root@netmon tmp]# diff -u ping.pl ping.pl.orig
--- ping.pl     2017-11-01 19:53:41.130704992 -0700
+++ ping.pl.orig        2017-11-01 19:52:37.901373928 -0700
@@ -21,12 +21,12 @@

 # old linux version use 'icmp_seq'
 # newer use 'icmp_req' instead
-open(PROCESS, "ping -c 1 $host 2>&1 | grep -E '(icmp_[s|r]eq.*time|unknown host|Unknown host|not supported|Name or service not known)' 2>/dev/null |");
+open(PROCESS, "ping -c 1 $host 2>&1 | grep -E '(icmp_[s|r]eq.*time|unknown host|Unknown host|not supported)' 2>/dev/null |");
 $ping = <PROCESS>;
 close(PROCESS);
 chomp($ping);

-if (($ping =~ 'unknown host') || ($ping =~ 'Unknown host') || ($ping =~ 'not supported') || ($ping =~ 'Name or service not known')) {
+if (($ping =~ 'unknown host') || ($ping =~ 'Unknown host') ||  ($ping =~ 'not supported')) {
        if ((-f '/bin/ping6') || (-f '/sbin/ping6')) {
                open(PROCESS, "ping6 -c 1 $host 2>&1 | grep 'icmp_[s|r]eq.*time' 2>/dev/null |");
                $ping = <PROCESS>;
`

**Comment by cigamit** [comment]
Thanks for taking time to report.  Will be resolved in 1.2.28.  Again thanks!
