### ISSUE TITLE
Aggregate DBCALL ERROR

### ISSUE THREAD

**Issue by Izmenoff** [Cacti/cacti#1059]
Cacti 1.1.27
MariaDB 10.2.9

03-11-2017 13:00:35 - CMDPHP SQL Backtrace: (/aggregate_graphs.php: 62 graph_edit)(/aggregate_graphs.php: 672 aggregate_items)(/aggregate_graphs.php: 1113 db_fetch_cell)(/lib/database.php: 233 db_fetch_cell_prepared)(/lib/database.php: 280 cacti_debug_backtrace)
--
03-11-2017 13:00:32 - CMDPHP SQL Backtrace: (/aggregate_graphs.php: 62 graph_edit)(/aggregate_graphs.php: 672 aggregate_items)(/aggregate_graphs.php: 1130 db_fetch_assoc)(/lib/database.php: 360 db_fetch_assoc_prepared)(/lib/database.php: 401 cacti_debug_backtrace)
03-11-2017 13:00:32 - DBCALL ERROR: SQL Assoc Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'gtg.title_cache LIKE '%%borisov%%') AND(gtg.graph_template_id=40) ORDER BY `tit' at line 1
03-11-2017 13:00:32 - DBCALL ERROR: SQL Assoc Failed!, Error:1064, SQL:'SELECT gtg.id, gtg.local_graph_id, gtg.height, gtg.width, gtg.title_cache, agi.local_graph_id AS agg_graph_id FROM graph_templates_graph AS gtg INNER JOIN graph_local AS gl ON gtg.local_graph_id=gl.id LEFT JOIN ( SELECT DISTINCT local_graph_id FROM aggregate_graphs_items WHERE aggregate_graph_id=19) AS agi ON gtg.local_graph_id=agi.local_graph_id WHERE (gtg.title_cache LIKE '%%internet%%'gtg.title_cache LIKE '%%borisov%%') AND(gtg.graph_template_id=40) ORDER BY `title_cache` ASC LIMIT 0,1000'

**Comment by cigamit** [comment]
I've resolved this by making the Items filter use a regular expression.  The previous logic, though interesting, was a one-off, and therefore, since regular expressions are just as capable, I've move the logic to regular expressions.

Thanks for reporting BTW!
