### ISSUE TITLE
ERROR PHP NOTICE: Undefined offset: 3 

### ISSUE THREAD

**Issue by Owned67** [Cacti/cacti#1064]
just signal a error with php5.7 (debian 9)

2017/11/04 16:12:00 - CMDPHP PHP ERROR NOTICE Backtrace: (/automation_templates.php: 65 template_edit)(/automation_templates.php: 350 CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)
--
2017/11/04 16:12:00 - ERROR PHP NOTICE: Undefined offset: 3 in file: /var/www/html/cacti/automation_templates.php on line: 350

**Comment by cigamit** [comment]
Cacti version?

**Comment by cigamit** [comment]
Never mind.  Fixing.

**Comment by cigamit** [comment]
Resolved.  Thanks for reporting.
