### ISSUE TITLE
[1.1.27] Poller Output Table not Empty. Issues on Data sources

### ISSUE THREAD

**Issue by jhonnyx82** [Cacti/cacti#1065]
I am facing some issues on a lot of Data source, this happened after a reboot of two of my remote pollers and I would like to understand if this is a bug or if there is  some process I can implement to recover these data sources either on the RRD or on the database.

I tried restarting the mariadb service on the remote and the main poller, I tried rebuilding the cache, nothing.
Thanks in advance:

06/Nov/2017 15:39:07 - POLLER: Poller[2] WARNING: Poller Output Table not Empty. Issues: **1282**, DS[11177, 13247, 13487, 13474, 11246, 11208, 13465, 14780, 14215, 14215, 14215, 13443, 14454, 14454, 14454, 11217, 13419, 11177, 13397, 13364], Additional Issues Remain. Only showing first 20

**Comment by jhonnyx82** [comment]
I deleted the impacted Data sources and I recreated the graphs, apparently these recreated has no issues (at the moment...) but it seems that some other data sources are getting impacted that before had no issue...

Should it be something about the latency or the DB management? any tip? a bug ?

**Comment by jhonnyx82** [comment]
Just wanted to give an update:

I were able to resolve this issue by identifying which device these DS belong to and in the device pane click on the **SAVE** button, this to my memory recache the poller for that specific device only.

Now on the top of this empiric resolution, I am thinking **_it may be good to have a command to select specific devices to rebuild the poller cache for._**

Also I noticed that this happens mostly after automation discovery, so when a certain number of devices are added at the same time due to discovery (seems to not happen when only few are added, namely 1 or 2 at the same time )

**Comment by cigamit** [comment]
Hmm.  That's interesting.  Please let me know the data input methods of the items that were left in the poller_output_table after the automation run.  This might be something to do with the push_out_*** functions.  So, it's important that we know if they are scripts, script servers, or snmp calls.

**Comment by jhonnyx82** [comment]
I have all SNMP calls, almost no scripts

**Comment by cigamit** [comment]
Okay, thanks.

**Comment by jhonnyx82** [comment]
UP

Installed version 1.1.28

Had some recurring errors time by time : 
**_SPINE: Poller[2] ERROR: Spine Timed Out While Waiting for Threads to End_**

Decided to configure for some devices to **Number of Collection Threads** : 2

Result : 

**POLLER: Poller[2] WARNING: Poller Output Table not Empty. Issues: 5452, DS[13722, 13722, 13722, 17864, 17864, 18149, 18149, 18149, 16509, 16509, 16509], Additional Issues Remain. Only showing first 20**

5000+ DS with problems on the output table.

Well I tried repopulating the cache via php cli command on each poller and main poller.
I tried opening each device and click on the SAVE button (to repopulate the cache)
I tried **rebuild_poller_cache.php** on the device I identified

I ended up deleting the DS that were having the issue...

result : I reduced the number of the issues but other DS get the same problem, is this caused by the version (bug) by the threads or by something else?

Do you have any tip ? this is making the whole system very unstable

**Comment by jhonnyx82** [comment]
UP (2):

On a side note I am finding so many issues on stability regardless of performances that I think that I will proceed in one of the following or some of them.

- give another 3 months for version 1.2
- go for standalone cacti installations (I start to believe all my problems comes from the BOOST architecture, as for our old 0.8.x standalone installs we had no issues)
- stick with our old 0.8 install and then move to a different monitoring system.

I think that 1 year is a long time to have some stability.

**Comment by jhonnyx82** [comment]
UP (3) : 

I checked that actually some of these values are not flushed out on the **poller_output** table and some DS items has double values.

Somehow the RRD file is also not updated and at this point I doubt if it's a problem on writing to the RRD file that generate the double entries on the **poller_output** table or if it's the oppsite, so the **poller_output** table that does not gets totally processed and rrd files are not populated with data.

Let me give you an example:  

This is the poller_output table for one of the recurring DS that has problems:
At the time of writing the poller for the same RRD name had 2 different entries
![image](https://user-images.githubusercontent.com/26431888/33172661-52063882-d051-11e7-850a-0b9fd8b28b89.png)

but  DS 18268 is a 5 minute data source, meaning that the timestamp on the older value belongs to a previous poll cycle.

What worries me is that this somehow implies also missing updates of the RRD file from a certain point on, let me show the screenshot of the RRD file info:

![image](https://user-images.githubusercontent.com/26431888/33173124-2744ce40-d053-11e7-8242-dde83d21258f.png)

It would be nice to know why this is happening (now only on one poller) and what can we do to prevent or fix the troubled Data sources

**Comment by cigamit** [comment]
Setup your /etc/php.ini to set the error_log = /tmp/php_errors.log.  Run the system for a while, look for entries in that file.  Upload if possible.

There are some cases where the poller output table will not entirely empty:

1) The poller crashes while emptying
2) Your poller is overrunning its polling time
3) You script, data source, etc are not outputing all information
4) You updated a data template and added or removed data sources, without deleting the existing graphs based upon it first.

Which is your case?

**Comment by jhonnyx82** [comment]
Thanks for your usual support,

I enabled the logs as you requested, I will provide them in case something happens.

**max_execution_time** in PHP is set to _30 seconds_ for all pollers

let me reply in line to your comment:

> The poller crashes while emptying

I haven't read of any log related to unexpected crash of the poller

> Your poller is overrunning its polling time

Yes, I had 1 or 2  overrunning poller process on 2 of my remote pollers.
Each time a BOOST sync was in place, the remote pollers had overrunning processes (so in my case every 30 minutes). I verified all the old logs to confirm this

> You script, data source, etc are not outputing all information

I would exclude this, data source impacted were also local on the same site where the poller is, also I checked in the poller_item table that the affected DS had consistent data during the time the issue occurred

> You updated a data template and added or removed data sources, without deleting the existing graphs based upon it first.

No, I didn't modify data templates and is my habit to delete graph and confirm the deletion of the related data source to avoid such an issue.

**Comment by jhonnyx82** [comment]
Here an example, Main poller BOOST process delays all remote pollers execution time:

Main Poller
--------------------------
![image](https://user-images.githubusercontent.com/26431888/33190116-94229a8c-d0a9-11e7-985f-a00f53f9a513.png)


Remote poller 1
--------------------------
![image](https://user-images.githubusercontent.com/26431888/33190092-6a9b9ce0-d0a9-11e7-9edf-2a42fb3add30.png)

Remote poller 2
----------------------
![image](https://user-images.githubusercontent.com/26431888/33190132-b9b499da-d0a9-11e7-8de1-a43408c2df0d.png)

**Comment by jhonnyx82** [comment]
UP

I modified the settings for BOOST to run more often but with lower impact on the overall performances of the main poller : 

Let me know what do you think, up to now I am checking that the delay on the remote poller is much less and not for all of them at the same time like before : 

![image](https://user-images.githubusercontent.com/26431888/33204236-316c900a-d103-11e7-981c-073ccc52c8d1.png)

so actually with 250K max records the updates happens every 12-15 minutes but I will possibly increase it a little.

Will let you know if this is giving any benefit

**Comment by jhonnyx82** [comment]
UP 2

Seems that decreasing the amount of max records gave some benefits on the overall stability of the main poller, I changed again the settings by 

- lowering the **Maximum Data Source Items Per Pass** to _5000_ (any concern on doing this?)
- Raising the **Maximum Records** to 300.000 

Just I notice that I have some gaps on the graphs but the related remote pollers has no error (either SNMP timeout or Poller Output Table not Empty) so I am assuming that maybe during the copy to RRD something went wrong.

![image](https://user-images.githubusercontent.com/26431888/33224823-ded4fc86-d16d-11e7-9a53-c824adafa936.png)


The idea is that since the main poller cannot really handle large amount of data to be copied, it would be better to just copy a smaller amount of data but more often (I guess that when all the DS will be there from the whole network it would be every 10-15 minutes with 300.000 MAX records BOOST for copy

Here my settings:

![image](https://user-images.githubusercontent.com/26431888/33224990-0ac0b662-d170-11e7-8070-c42a5991e336.png)

- Another question is a about **Enable direct population of poller_output_boost table**

Is it worth to enable it since my poller tables (besides poller_item) are all MEMORY tables?

![image](https://user-images.githubusercontent.com/26431888/33224967-bf15a74a-d16f-11e7-8210-00fd48a7dcf5.png)

**Comment by jhonnyx82** [comment]
UP

I can confirm that reducing the amount of **Maximum Records** (hence, increasing the frequency of the RRD write to disk from the BOOST poller table) does not generate the poller output sync issue seen before but I have gaps in my graphs exactly at the time the BOOST process is performed on the main poller.

on the remote pollers I have no log showing any issue and this is only for some graphs coming from the same device

example : 

On the main poller I had a BOOST update  at this time : 
26/Nov/2017 06:49:30 - SYSTEM BOOST STATS: Time:21.0600 RRDUpdates:309083

and here i got some graphs with this gap at exactly the same time
 
![image](https://user-images.githubusercontent.com/26431888/33240229-33a799ee-d2b3-11e7-8422-ca9ddeba2ff1.png)

**Comment by cigamit** [comment]
You will have to update your entire Cacti log for us to review.

**Comment by jhonnyx82** [comment]
I assume main and remote poller, in a minute I will upload them here

**Comment by jhonnyx82** [comment]
Note : 
The pollers are in hosted on the same site so there is no delay in communication between them and bandwidth is of course not an issue.

Load on both pollers looks not excessive : 

## **main poller**
![image](https://user-images.githubusercontent.com/26431888/33243520-56c556e8-d2e8-11e7-848e-27ab587feb5d.png)

## **remote poller**
![image](https://user-images.githubusercontent.com/26431888/33243524-6b381a2a-d2e8-11e7-97a6-c99bc8fe335a.png)


## **main poller logs**

The graph with gaps from my previous post refers to the main poller logs at line 5978 (where the BOOST copy is recorded)

_26/Nov/2017 06:49:30 - SYSTEM BOOST STATS: Time:21.0600 RRDUpdates:309083_


[cacti_main_poller_log.txt](https://github.com/Cacti/cacti/files/1504163/cacti_main_poller_log.txt)

## **remote poller logs**

on the remote poller logs the related line is 2010 : 

_25/Nov/2017 06:50:21 - SYSTEM STATS: Time:17.9311 Method:spine Processes:2 Threads:30 Hosts:94 HostsPerProcess:47 DataSources:4800 RRDsProcessed:0_


[cacti_remote_poller_log.txt](https://github.com/Cacti/cacti/files/1504164/cacti_remote_poller_log.txt)

**Comment by jhonnyx82** [comment]
UP 

Meanwhile I reduced the size of the output field to 128 VARCHAR from 256 on the following tables

- poller_output
- poller_output_boost

hoping that the reduction of 50% of memory usage (these are memory tables) and the consequent amount of data to be read and written. Do you think this may bring a benefit?

**Comment by reboot1983** [comment]
I believe this has not effect.

https://dev.mysql.com/doc/refman/5.7/en/char.html

This will only have affect with char columns, varchar has a dynamical length (1 or 2 bytes + data). Char always has the same length (right padded with spaces)l to the specified length).

**Comment by jhonnyx82** [comment]
Thanks for the reply, 

I am graphing the BOOST table size, actually I started from 512 (!!!) VARCHAR for the output field, then 256 and 128 (now).

What I can see is that actually the BOOST table size is 1/4 of what was before with the same (actually more...) Data Sources.

![image](https://user-images.githubusercontent.com/26431888/33245001-fc27164e-d301-11e7-87a8-c45fa43dd63a.png)

But I can also see that I am not seeing much benefits from this, as it looks to be directly related to the number of DS involved during the BOOST process running, it gives a delay on all other poller spine process + (strangely) I see some gaps on certain graphs where I instead see no errors on the remote pollers logs.

Strange gaps because when I left the default setting of 1.000.000 DS max for BOOST process and 30 minutes frequency I did not have such gaps but I had a problem (from the title) of increasing Data sources getting the **_Poller Output Table not Empty_** error on all pollers (most probably given by the added delay during the BOOST process itself from the main poller to the remote pollers).

Limiting the max amount of DS for BOOST cycle helped on this but now I got the gaps :(

**Comment by jhonnyx82** [comment]
UP

Gaps still there, trying with micro updates (65K) record limit for BOOST to copy to disk.

Will let you know the outcome

**Comment by jhonnyx82** [comment]
No joy with micro updates.

Disabled BOOST updates...just to see how it goes, will update during the day

**Comment by jhonnyx82** [comment]
nothing to do, I will then wait for version 1.2.x hoping there will be distributed storage and processing of RRDs, meanwhile I will decide if I will : 

- Build 5 different pollers at 1 minute polling 
- keep the central management but scale up to 5 minutes polling

first option would scale down to the number of RRDs to process, drawback is management burden.

second option would provide more time for the processing time before additional DS are updated, drawback is loss of detail (a lot...500% less precise)

Suggestions?

**Comment by cigamit** [comment]
Please change boost so that it only updates once an hour and see how that goes.  Running boost too often is not a good idea.

**Comment by cigamit** [comment]
The parallel boost concept is coming in 1.2 only as previously mentioned.

**Comment by jhonnyx82** [comment]
Thanks for your comment,

I am currently going for 5 minutes polling since I don't have yet dedicated hardware for the master poller and also I modified the BOOST process to happen every 30 minutes (had some gaps before every 15 minutes...) will raise it to 1 hour as you suggest (with 5 minutes polling I have plenty of time).

Since you mentioned 1.2 ... can you give some info on how things will change? 

- RRD stored on remote pollers
  - is it an option from the current design or a total change?
  - Graph view would be always accessed from the main poller or the idea would be to access each remote poller? (I expect they would "pull" the data for the RRD files for the graph they doesn't host)
    -  would it slow down graph view from the main poller instead? in case the main poller does not host anymore all RRDfiles
- Pollers dependencies
  - Will the remote pollers be more independent from the main poller? in which way?
  - Will the remote pollers have their own process settings for spine ?
  - Will the remote pollers use a local LDAP agent to verify the user authentication?

**Comment by cigamit** [comment]
Responses below.

- RRD stored on remote pollers - No, we are not going to do remote storage.  This was something that I had thought about, but it will create limits, for example Aggregate Graphs would not be possible in those cases.
- Pollers dependencies
  - Will the remote pollers be more independent from the main poller? in which way? - Just as independent as before, but they will use the local data always and either push to the local output table or back to the main system table depending on it's availability.  This will make the data collectors more responsive.
  - Will the remote pollers have their own process settings for spine ? - Already completed in the feature 1.2 branch both for spine and cacti
  - Will the remote pollers use a local LDAP agent to verify the user authentication? - Good point.  If the main LDAP is not available, then how will the admin log in.  I suspect your LDAP should be a vip/rrdns anyway.  However, unless you were using Web Basic, there should always be a local account fallback for when the main system is not available.  So, this should not be a major issue.

**Comment by jhonnyx82** [comment]
This sounds promising!

Will the automation discovery change as well?

TBH I still have issues on running the network discovery on pollers that have more delay (due to distance) from my main poller.

As you know there is another thread for this but just wanted to know if it will be fixed or if in your opinion I should change something, by knowing how Autom8 works,

**Comment by jhonnyx82** [comment]
UP

I have a doubt about how the BOOST process works in terms of RRDupdates: My statistics shows always different numbers of RRDupdates...does that mean that some RRD files are not being updated? (All DS are 5 minutes so I would expect always the same)

![image](https://user-images.githubusercontent.com/26431888/33552482-48bfb224-d8f5-11e7-89e4-51c19c1d9130.png)

**Comment by jhonnyx82** [comment]
> Pollers dependencies
Will the remote pollers be more independent from the main poller? in which way? - Just as independent as before, but they will use the local data always and either push to the local output table or back to the main system table depending on it's availability. This will make the data collectors more responsive.

Will this affect somehow also Automation Discovery?

**Comment by arno-st** [comment]
I jump into the thread, since I have the same kind of trouble, but with a single server, but also a lot of Poller Output Table not Empty. and Spine can't go through all the RRD !
And by the way I have no RRDprocessed !!

2017/12/19  13:25:04 - SYSTEM STATS: Time:3.0542 Method:spine Processes:10  Threads:50 Hosts:996 HostsPerProcess:100 DataSources:3734  RRDsProcessed:0

Even if graph are updated
I add last night almost 2100 device with a home made plugin that discover the network via CDP and add each device it find on cacti and the related link, with the api api_device_save and create graphs with a call to automation_execute_graph_template for the CPU and create_complete_graph_from_template for the interface graphs.
If that's a path to explore

**Comment by jhonnyx82** [comment]
Hi Arno,

the RRDsProcessed at 0 may be related to the BOOST process being enabled.

As I can tell the RRD files processed are at 0 in that case because the system saves them at regular interval all together, you possibly have this entry in your logs:

 SYSTEM BOOST STATS: Time:XX RRDUpdates:YY

**Comment by cigamit** [comment]
No input for many days.  The tuning of spine especially around processes x threads, when too high can lead to all sorts of nasty issues.  I'm going to close this for now as I think it's primarily a training excercise.

**Comment by cigamit** [comment]
@jhonnyx82, Showing different amounts of records updating in Cacti 1.x is not an issue.  It means that you have multiple collector intervals in your system, and you are leveraging them.  That's all.

**Comment by sirjana** [comment]
I am having problem on cacti and all the graph seems broken.  Error from cacti log file is seen as:
POLLER: Poller[0] WARNING: Poller Output Table not Empty. Issues Found: 276270, Data Sources: traffic_in(DS[24]), traffic_out(DS[24]),.
Anyone have idea?

**Comment by blackbrayn** [comment]
> Just wanted to give an update:
> 
> I were able to resolve this issue by identifying which device these DS belong to and in the device pane click on the **SAVE** button, this to my memory recache the poller for that specific device only.
> 
> Now on the top of this empiric resolution, I am thinking **_it may be good to have a command to select specific devices to rebuild the poller cache for._**
> 
> Also I noticed that this happens mostly after automation discovery, so when a certain number of devices are added at the same time due to discovery (seems to not happen when only few are added, namely 1 or 2 at the same time )



> Just wanted to give an update:
> 
> I were able to resolve this issue by identifying which device these DS belong to and in the device pane click on the **SAVE** button, this to my memory recache the poller for that specific device only.
> 
> Now on the top of this empiric resolution, I am thinking **_it may be good to have a command to select specific devices to rebuild the poller cache for._**
> 
> Also I noticed that this happens mostly after automation discovery, so when a certain number of devices are added at the same time due to discovery (seems to not happen when only few are added, namely 1 or 2 at the same time )

Just broke my graphs adding devices (many) from the discovery plugin.
I will try the save methon on the hosts and rebuild after, see if i can resurct my server , cpu usage is 90+ at the moment.

**Comment by sirjana** [comment]
@blackbrayn I tried as per your process but still it is not working. 
Now, I have decided to migrate graph on new server.
