### ISSUE TITLE
Issue with Cacti Boost, records get stuck in "Archived Boost Records"

### ISSUE THREAD

**Issue by ikorzha** [Cacti/cacti#1074]
Lately as my large Cacti system grows I have encountered a major issue with boost. With each boost run it is unable to process all records and get stuck continuously running with small number of records pending in temporary Archived Boost. As the result unprocessed records keeps increasing to 30+ millions of records to the point when I have to stop the poller, let boost catch up and than delete the temp archive boost table for it to finish processing..

This is a major issue for me I need help, Boost unable to complete a run successfully. I see no errors in the log, and there is nothing special about these records as far I can tell.
_________________________________________________________________________________________________________
**Additional Info:  Records that get stuck, are being polled by remote poller that has "80ms" response time due to physical distance. When I move the "polled device" to a master poller, records no longer get stuck in archived table.**
_________________________________________________________________________________________________________
 

Can some sort of cleanup procedures be put in place to fix the boost issue?

![archived-table](https://user-images.githubusercontent.com/11211789/32694070-d884d69e-c704-11e7-8f4f-5191182d03c9.jpeg)
![boost-table](https://user-images.githubusercontent.com/11211789/32694073-da07b752-c704-11e7-94d0-2eb7b2fcf0d2.jpeg)

**Comment by reboot1983** [comment]
I've found something strange in the code (boost.php#742 in the development branch) which might be generating this issue.
My editor informes me there are 3 undefined variables (underlined red). This is definately wrong code, but i'm not sure how to fix it.

![image](https://user-images.githubusercontent.com/20405704/32698126-efca8498-c79f-11e7-859a-f4b3b8caaef4.png)

**Comment by cigamit** [comment]
That's not the issue, your editor does not comprehend the fact that the variables, though set later in the function are really never called until there are $vals_in_buffer.  I can remove this error though if you like.

What can you tell me of the local_data_id's stuck in the archive tables?

**Comment by ikorzha** [comment]
Cigamit thank you for looking into it:
Looks like a single data source is causing the the boost process to hang.:
He is the info with regards to it: (I have also uploaded the actual rrd file...

Please let me know if there is any additional info I need to provide...

![rrd-info](https://user-images.githubusercontent.com/11211789/32701521-8c8fe962-c7a5-11e7-95fd-c2521272a3be.jpeg)
![rrd-info-2](https://user-images.githubusercontent.com/11211789/32701523-8f50722a-c7a5-11e7-8814-57013063e1a9.jpeg)

[cactione-uk-poller_aaa_com_traffic_in_29836.zip](https://github.com/Cacti/cacti/files/1464922/cactione-uk-poller_aaa_com_traffic_in_29836.zip)

**Comment by cigamit** [comment]
Can you check the archive table's local_data_id's and see if there are still in the database in data_local?  I'm wondering if there is an issue with some race condition around data removal.

**Comment by ikorzha** [comment]
Below is screenshot of "data_local" table the very end of it.  ID "29836" is current absolute dead last record in my system.. It does seems that it gets stuck in boost cleanup but only if the poller to poll that object has high latency and long polling times...

![data_local_id](https://user-images.githubusercontent.com/11211789/32703159-bd8cbf9e-c7bf-11e7-8197-376d2e8681a9.jpeg)

**Comment by cigamit** [comment]
Before your last comment, I was looking at the code, and saying to myself "doesn't this just exit out on the last data source without processing it?".  Haha, it won't make it into 1.1.28 version.  I'll be able to clean up this mess in the next 24 hours.

**Comment by ikorzha** [comment]
Cigamit, I here daily looking forward to test the patch!

**Comment by ikorzha** [comment]
Thank you for the fix Cigamit, I believe the boost issue is now resolved with your yesterday commit.
I have tested the fix and do not see the problem any more
