### ISSUE TITLE
Search graph permissions not functioning in user setup

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#1076]
Check this out ... these graphs show up in a query for a brief moment, then disappear .... 
![peek 2017-11-13 00-58](https://user-images.githubusercontent.com/12864741/32715095-023c6664-c80e-11e7-81df-e32701682a74.gif)

**Comment by cigamit** [comment]
Bring up the browsers debug windows and capture the two callbacks.  Paste them here.

**Comment by cigamit** [comment]
Any updates?

**Comment by eschoeller** [comment]
Really strange I can't reproduce it now. And I had closed and restarted the browser before posting that. I guess go ahead and close this out, if it comes up again I'll re-open. Sorry for the hassle.

**Comment by cigamit** [comment]
Okay.
