### ISSUE TITLE
cacti can't show the graph.

### ISSUE THREAD

**Issue by Howard-Chang** [Cacti/cacti#1077]
Hi, I am new in cacti.
My OS is windows 10
this is the device I set up.
![image](https://user-images.githubusercontent.com/19474557/32763160-01a6a62a-c939-11e7-9f66-fbdfc4654372.png)
![image](https://user-images.githubusercontent.com/19474557/32763173-1b8428e2-c939-11e7-809a-6b08f28dce8f.png)

I found the graph can't show.
thank you in advance.

**Comment by cigamit** [comment]
I think this issue belongs on the forums.  Can you please raise that issue there.  Closing.
