### ISSUE TITLE
Undefined index: cactiApplDeviceIndex in file lib/snmpagent.php on line: 357 

### ISSUE THREAD

**Issue by arno-st** [Cacti/cacti#1079]
I had to delete all my device, and now I have this error, and I can't find where it come from.
I just upgrade to the latest version, but still, the error didn't disappear !
My snmpagent_cache dosen't have a record into the row cactiApplDeviceIndex, so it' s looke like if you delete all device, this table/function is invalid

**Comment by arno-st** [comment]
Rhaa I have to recreate the localhost record, then rebuild the snmpagent_cache

but cacti should be able to work even if the localhost dosen't exist

**Comment by cigamit** [comment]
Resolved.  Thanks for reporting.
