### ISSUE TITLE
Login redirect / permission auth problem with user groups

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1083]
The LOGIN OPTIONS section at the bottom of groups is not very clear on what is actually occuring.  If you have multiple groups associated to a user and select different options, there should be a warning that another group option is higher than your current value.   As such, if you create four groups and set each to a different setting, only the maximum value setting would actually apply!

Therefore, a user who only has View Graphs permission, would fail to login because index.php would be denied access since realm_id 8 wasn't present but realm_id 7 was, yet the redirect didn't occur due to the mixture of groups.  As a result, the user first time around seems to end up with a blank page, but on a refresh with re submission does get a permission denied page.

**Comment by cigamit** [comment]
Good point netniV.  Suggestions welcome.

**Comment by netniV** [comment]
Well, I was trying to think about that.  Since you know what members are within the group, highlight if/when some members have a different group overriding the current groups setting on the members tab?  It's not ideal but at least gives information that we need to look elsewhere.

Another idea may be to introduce a redirect priority.  That way, one group may have more say that another over the value to be used.  If the priority was unique to each group, that would prevent a clash between two different settings at the same priority.
