### ISSUE TITLE
Call to undefined function html_log_input_error() in /usr/share/cacti-1/lib/html_utility.php on line 324

### ISSUE THREAD

**Issue by arno-st** [Cacti/cacti#1085]
Hi have some strange stinks on cacti.
First I have some line that appear in my log without reason:
Graphs['se-se46-8502 - Packet - Gi0/1 - tel IP + PC --- '] DS[20141]
the line come just like that, I can't find any information to where it come from.

So I decide to push the log to a higher level to see if I can find any useful information, so I did:
Log level developper, and tick all logging option.

but know I can't go back to a low level logging and I'm getting this error in my log:
[Wed Nov 15 08:21:33.758666 2017] [:error] [pid 29646] [client 10.85.116.16:61500] PHP Fatal error: Call to undefined function html_log_input_error() in /usr/share/cacti-1/lib/html_utility.php on line 324, referer: http://lslcact01.lausanne.ch/cacti1/settings.php

To solve the issue the only way is to comment the line 324 on html_utility.php then remove the mark for developer level under cacti on the settings tab.

I'm using cacti 1.1.27

**Comment by cigamit** [comment]
Resolved.  Please update include/global.php and if solved, please close.

**Comment by cigamit** [comment]
Going to close.  I've verified in my environment.
