### ISSUE TITLE
[Cacti 1.1.27] Automation discovery - no Rerun Data Queries 

### ISSUE THREAD

**Issue by jhonnyx82** [Cacti/cacti#1086]
Hi Everyone,

Thanks in advance for your help, this may not be a bug:

Let me describe the issue I am seeing on this feature of the discovery process : **Rerun Data Queries**

The way I expected this feature to work is that our network devices would actually have up-to-date interface descriptions after a network discovery process, so scheduling a network discovery would also update the current existing graphs.

I tried it but unfortunately it doesn't work, I am unsure if it is supposed to only create new graphs for new interfaces or if it should also update the existing ones.

PS : I tried modifying the **Re-Index Method** but either in _uptime_ and _Index count_ worked, with _Verify All_ it was recaching all time the the device and that was way too much processing intensive.

to be clear, I am referring to this : 
![image](https://user-images.githubusercontent.com/26431888/32896428-46d1073a-cae3-11e7-893e-03561c22c70a.png)

**Comment by cigamit** [comment]
Thanks for the heads-up.  Investigating.

**Comment by cigamit** [comment]
Resolved, thanks for reporting.
