### ISSUE TITLE
CLI add_device.php won't add duplicate IPs to the database with option --proxy

### ISSUE THREAD

**Issue by vancefan** [Cacti/cacti#1087]
Use add_device.php add a device with option --proxy shows error, please refer to the screenshot:

![image](https://user-images.githubusercontent.com/15649628/32900120-ad4770d2-cb27-11e7-8ee8-2406bc75424f.png)

I try to use the latest version of cacti, it also show the same error.
could you please invertigate.

**Comment by cigamit** [comment]
I see the reason, --proxy was intended more for snmp proxies, but I see where you are going.

**Comment by cigamit** [comment]
Resolved.  Please test and if it's working for you, please close.

**Comment by vancefan** [comment]
Tested， it works now, thanks a lot.
