### ISSUE TITLE
Call to remote pollers has no timeout

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#1088]
I posted a help query to the forums about setting up remote pollers but never got a response. There doesn't appear to be any documentation out there about it, so I've been tinkering around with it. What I'm confused about is how the Cacti configuration is shared between the Main poller and the Remote poller. It seems as if a remote poller doesn't use the configuration in the local mysql database but rather uses the configuration from the main poller. I have triple checked by configuration and I know the remote poller has the correct config (as I understand it):

<pre>
/* make sure these values reflect your actual database/host/user/password */

$database_type     = 'mysql';
$database_default  = 'cacti';
$database_hostname = 'localhost';
$database_username = 'www-data';
$database_password = 'password';
$database_port     = '3306';
$database_ssl      = false;

/* when the cacti server is a remote poller, then these entries point to
 * the main cacti server.  otherwise, these variables have no use. 
 * and must remain commented out. */

$rdatabase_type     = 'mysql';
$rdatabase_default  = 'cactitest';
$rdatabase_hostname = '192.168.252.1';
$rdatabase_username = 'apache';
$rdatabase_password = 'password';
$rdatabase_port     = '3306';
$rdatabase_ssl      = false;
</pre>

The problems I am running into are numerous. These are different O/Ses with different configurations (/usr/local/rrdtool/bin/rrdtool vs /usr/bin/rrdtool as an example). Sharing the same paths is just kind of a nightmare (but I hacked around it with symlinks). The main poller is configured as http://host/cacti-test/ and the remote poller is setup as http://hostb/cacti/. This triggers another problem shown below, where this configuration sharing trips me up again:

` 2017/11/17 21:18:24 - ERROR PHP WARNING: file_get_contents(http://192.168.252.2/cacti-test/remote_agent.php?action=ping&amp;host_id=6): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
 in file: /cacti/cacti-1.1.23-test/lib/api_device.php  on line: 396
2017/11/17 21:18:24 - CMDPHP PHP ERROR WARNING Backtrace: (/host.php: 123 api_device_ping_device)(/lib/api_device.php: 396 file_get_contents)(CactiErrorHandler)(/lib/functions.php: 4416 cacti_debug_backtrace) `

Sorry in advance this might be more of a help request instead of a bug, but I'm really not understanding what is going on here. One thing for sure, I can switch the polling location for a device and see it attempt to run on the remote poller (even though it's failing to run the script for some reason).

**Comment by eschoeller** [comment]
Just to play around with this a bit more I blocked all outbound tcp traffic to port 3306 from my remote poller. In theory I would imagine the remote poller to still function but just say "offline" on the main console page. All I end up with is a spinning hour glass that never completes ...

**Comment by cigamit** [comment]
Sorry about the lack of documentation, it's going to change a little in 1.2 as well.  It won't change from a setup perspective, but rather from an operational one.  First, let me explain the setup:

* The main and remote pollers first require a consistent setup, which means same paths, etc.
* The main and remote pollers must be able to communicate with each other over the mysql and http[s] ports.
* The main poller does not require the $rdatabase_* settings
* The remote poller requires the $rdatabase_* settings to point to the main poller

Now lets talk about operation:

* When a remote poller can not communicate to the main poller over 3306, it will go into offline mode and store the poller_output data into the local poller_output_boost table.
* If the remote poller can reach the main poller over 3306, it will obtain it's poller_item, host, and data_source information from the main poller.  
* When the remote poller again can reach the main poller, if the remote poller was in offline mode, and there are poller_output_boost times to flush, it will spawn a process to do that before it comes online again.  
* Until the remote poller empties it's poller_output_boost table, it will remain offline
* Until the remote poller is online, it will still write to the local poller_output_boost table.

The change in the 1.2 version will be that the remote poller will be the following:
* It will always use it's local host, data source, and poller_item tables
* It will store it's own spine settings for threads and processes

I hope that's clear.

With regard to your problem around timeouts, I guess we should have a common function to query the remote poller, and ping it before every transaction, that way the spinner would not occur.  Let's change the title of this bug as such.

**Comment by cigamit** [comment]
Using the script timeout as the context timeout.  Resolved.

**Comment by eschoeller** [comment]
Can we talk more about the initial synchronization procedure between the two cacti instances? I am having trouble getting the main poller to register the remote poller. There doesn't seem to be a way to "kick off" this process ... it appears to happen in the background, and if there's some issue with this process I can't see any logged errors to indicate so. I see mysql traffic between the two machines, but that's about it. It also seemed like there was a requirement to have certain directories within the cacti remote poller writable by the webserver, at lest there were errors logged to indicate I needed to resolve that.
