### ISSUE TITLE
[1.1.27] missing parameter for Cacti external event logger ip address

### ISSUE THREAD

**Issue by jhonnyx82** [Cacti/cacti#1090]
Hi Everyone,

I would like to send cacti event logs to an external syslog server, in order to generate automated emails when errors or specific warnings are in place, just in the **Cacti settings -> Event Logging** panel I do not see the option to specify the ip address of the syslog server ... 

- where is it configured or managed?
- Should it be added there for a specific server? (I am thinking this because in case it is tied to the one used by the hosting server, then I would prefer to not send all server data and just the Cacti ones...should be different)
- How the remote pollers can be configured to send events to a syslog server? In my case, depending on the location it will be required that they use different servers each of them, in case of a single configuration entry from the main poller, this would become difficult

**Comment by cigamit** [comment]
Well, the forward statement belongs in your syslog.conf or /etc/rsyslog.d/cacti.conf and not in the core of Cacti.  If you ensure that you systems syslog is setup properly, then this problem is solved.
