### ISSUE TITLE
Slow GUI on large instances due to authentication queries

### ISSUE THREAD

**Issue by rprofijt** [Cacti/cacti#1091]
On large Cacti instances (120.000 graphs, 400.000 data sources) we see that clicking trough the pages in either preview or list mode is taking quite some time.

These kind of queries seem to be the cause:

SELECT DISTINCT id, name   FROM (SELECT DISTINCT gtg.graph_template_id AS id, gt.name,    uap0.user_id AS user0, uap1.user_id AS user1, uap2.user_id AS user2    FROM graph_templates_graph AS gtg    INNER JOIN graph_local AS gl    ON gl.id=gtg.local_graph_id    LEFT JOIN graph_templates AS gt    ON gt.id=gl.graph_template_id    LEFT JOIN host AS h    ON h.id=gl.host_id    LEFT JOIN user_auth_perms AS uap0 ON (gl.id=uap0.item_id AND uap0.type=1 AND uap0.user_id=75) LEFT JOIN user_auth_perms AS uap1 ON (gl.host_id=uap1.item_id AND uap1.type=3 AND uap1.user_id=75) LEFT JOIN user_auth_perms AS uap2 ON (gl.graph_template_id=uap2.item_id AND uap2.type=4 AND uap2.user_id=75)         HAVING (user0 IS NULL OR (user1 IS NULL OR user2 IS NULL))   ) AS rs   WHERE id > 0   AND name != ''   ORDER BY name

I know these are large instances, but is there any way to optimize this?

**Comment by cigamit** [comment]
Please run an `explain` on this query and post the results.

**Comment by rprofijt** [comment]
Of course:

+----+-------------+------------+------------+--------+-----------------+----------------+---------+----------------------------------------+--------+----------+----------------------------------------------+
| id | select_type | table      | partitions | type   | possible_keys   | key            | key_len | ref                                    | rows   | filtered | Extra                                        |
+----+-------------+------------+------------+--------+-----------------+----------------+---------+----------------------------------------+--------+----------+----------------------------------------------+
|  1 | PRIMARY     | <derived2> | NULL       | ALL    | NULL            | NULL           | NULL    | NULL                                   | 113490 |    30.00 | Using where; Using temporary; Using filesort |
|  2 | DERIVED     | gl         | NULL       | ALL    | PRIMARY         | NULL           | NULL    | NULL                                   | 111366 |   100.00 | Using temporary                              |
|  2 | DERIVED     | gt         | NULL       | eq_ref | PRIMARY         | PRIMARY        | 3       | cacti.gl.graph_template_id             |      1 |   100.00 | NULL                                         |
|  2 | DERIVED     | h          | NULL       | eq_ref | PRIMARY         | PRIMARY        | 3       | cacti.gl.host_id                       |      1 |   100.00 | Using index                                  |
|  2 | DERIVED     | gtg        | NULL       | ref    | local_graph_id  | local_graph_id | 3       | cacti.gl.id                            |      1 |   100.00 | NULL                                         |
|  2 | DERIVED     | uap0       | NULL       | eq_ref | PRIMARY,user_id | PRIMARY        | 7       | const,cacti.gl.id,const                |      1 |   100.00 | Using index                                  |
|  2 | DERIVED     | uap1       | NULL       | eq_ref | PRIMARY,user_id | PRIMARY        | 7       | const,cacti.gl.host_id,const           |      1 |   100.00 | Using index                                  |
|  2 | DERIVED     | uap2       | NULL       | eq_ref | PRIMARY,user_id | PRIMARY        | 7       | const,cacti.gl.graph_template_id,const |      1 |   100.00 | Using index                                  |
+----+-------------+------------+------------+--------+-----------------+----------------+---------+----------------------------------------+--------+----------+----------------------------------------------+

**Comment by cigamit** [comment]
Have you run the 'convert_innodb.php' script in the cli directory?  Have you followed the tuning recommendations in the installer?  What version of MariaDB/MySQL are you running?

**Comment by rprofijt** [comment]
Yes, all tables are either innodb or memory. Yes, these settings have been applied. The version is MySQL 5.7.20

**Comment by rprofijt** [comment]
The MySQL query cache is disabled by default since 5.7, if the query_cache_type is set to 1 the GUI gets a lot snappier. However, this feature is depreciated and will be removed in 8.0

**Comment by cigamit** [comment]
How long does it take that query to run generally?  I can tell you the optimizer is working differently in MySQL than MariaDB too.  The reason that it's slow it that it's putting all the records into a temporary table, which is going to slow things.  We should ensure that that temp table be in memory.

Next, what are the values of:

`tmp_table_size`
`default_tmp_storage_engine`
`innodb_tmpdir`
`tmpdir`
`join_buffer_size`
`max_join_size`

And is the tmpdir on flash/memory partition?

**Comment by rprofijt** [comment]
The query takes around 4 seconds, but the fact that is is run every time a users goes to the next page does not seem optimal.

tmp_table_size = 128M
default_tmp_storage_engine = InnoDB
innodb_tmpdir = <empty>
tmpdir = /opt/mysql/tmp (ssd storage)
join_buffer_size = 128M
max_join_size = 18446744073709551615

The entire database is on ssd storage.

**Comment by cigamit** [comment]
Well, there are two options:

* There is a short circuit option where if the user or groups have no lock down on the graph permissions, then just return the list.
* The second options is to allow the Console -> Graphs to have no security check.

What do you think?  I really don't want to give up on this security model, but it has to scale at the same time.

**Comment by rprofijt** [comment]
I'm not sure what you mean by the first option? As for your question: In our use case we have no need for limiting permissions on graphs. So maybe an option to bypass this on large systems?

**Comment by reboot1983** [comment]
I've made some small effort looking into this query (queries). I was able to refactor some of it. It's 33% lighter with less use of 'temporary file' and table scans. 

I do not have such a large environment as @rprofijt has, but I do notice an incremental performance win.
Where my 'develop' environment has 30% profit, my production environment has more than 40% profit (with only 15 devices). Can you please check this if it works for you?

**Comment by cigamit** [comment]
Looks like a good optimization.  I'll go ahead and merge.  Great work!

**Comment by cigamit** [comment]
Going to close.  The optimization removes a temp table  and fullscan which as he mentioned netted a fairly large performance increase.
