### ISSUE TITLE
Graph Tree - Minor display issue with right click menu

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1092]
There is a minor issue with the right click menu on a graph.  If you right click on a graph to get the menu, but the left click on another tree element, the menu remains.  Hoovering over a new graph does clear the menu which should have happened during the left click on the menu.

**Comment by cigamit** [comment]
Yea, a known issue.

**Comment by netniV** [comment]
Oh OK :)

**Comment by cigamit** [comment]
This should be pretty much resolve now.  Check in 1.1.31.

**Comment by netniV** [comment]
Yes, appears to be resolved.
