### ISSUE TITLE
Blank page after adding a weathermap to display

### ISSUE THREAD

**Issue by VictorJ76** [Cacti/cacti#1093]
Hi, 
I Use cacti 0.8.8f with phpweathermap 0.98. I want to display my map and I have to add it via the page below :  

`http://IP/cacti/plugins/weathermap/weathermap-cacti-plugin-mgmt.php

Everything works great until I add my map and Iand to this blank page
 `http://IP/cacti/plugins/weathermap/weathermap-cacti-plugin-mgmt.php?action=addmap&file=simple.conf

Do something is broken ? I see nothing in logs. 

On my web browser, I get a 500 error.

**Comment by cigamit** [comment]
We don't support Weathermap here.  Please see the Weathermap Github page for help.
