### ISSUE TITLE
Can't add "duplicate" graph from cli script

### ISSUE THREAD

**Issue by stormonts** [Cacti/cacti#1094]
When we attempt to add a graph from the command line, the procedure fails if there is already a graph for that server using the same template.  In the graph template, we have checked the "Multiple Instances" box.

In this example, we are trying to add graphs for MSSQL instances.  On the MSSQL server, there is an S: drive that has numerous mounted volumes distinguished by volume name.  The image below shows the current data source (10812) for the NETWORK_UTIL_01 volume which is working fine:
![image](https://user-images.githubusercontent.com/25824323/33082402-b173154a-ceaa-11e7-8952-4cf1d6460daa.png)

As an example of our current process (and what we are attempting in the command line, we can manually create a new datasource, enter a different label (APPVOL_01), and then associated graph.  However when attempting that from the command line something is getting tripped up as it thinks we are trying to create a duplicate.
![image](https://user-images.githubusercontent.com/25824323/33082529-050e2da2-ceab-11e7-846e-14a79d8aac5e.png)

**Comment by cigamit** [comment]
Please use the --proxy add_device.php option.

**Comment by stormonts** [comment]
But we don't want to add an entirely new device, we want to be able to add multiple graphs that use the same template to one device..

It sounds like the only way to do it is via the GUI, by going to "New Graphs", select the template from the drop down, clicking create, and then populating the settings for each instance.
