### ISSUE TITLE
LDAP user creation defaults

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1096]
Currently, when an LDAP user logs in, he will have a copy of the template as any local user creation would.  However, this also takes the template Full Name so when a bunch of users register, they all show as "Standard User Template" under the name column.

As the user information is coming from LDAP, it would also be useful to pull their full name in as well, only falling back to the template if we are unable to retrieve that information for some reason.  Another field that could be pulled in is the email address.  A windows AD has this information available via LDAP.

Other LDAP sources may not have the fields or information available to them, so they should probably be either optional or only used if the LDAP field name is specified.  Maybe even using a combo box of standard names with the option to customise? eg, None, Email, PrimarySmtpAddress, Custom

**Comment by cigamit** [comment]
This is already merged in the 1.2 branch.
