### ISSUE TITLE
SNMP values displayed as HEX instead of STRING

### ISSUE THREAD

**Issue by dschall** [Cacti/cacti#1098]
I've downloaded and installed Cacti v1.1.28 on a fresh Ubuntu 16.04 LTS machine and the Interface Statistics shows the interface description as hex instead of strings.
snmpwalk on the console returns the string values.

More system information:
Date | Thu, 23 Nov 2017 11:52:12 -0800
-- | --
Cacti Version | 1.1.28
Cacti OS | unix
RSA Fingerprint | 57:e0:a8:54:30:0b:96:2b:19:f3:55:ac:6c:a4:c1:ec
NET-SNMP Version | NET-SNMP version: 5.7.3
PHP Version | 7.0.22-0ubuntu0.16.04.1
-- | --

I've downloaded the MIBs (using download-mibs on Linux), and tried with and without the MIBs files.

Strangly enough, it only happens to Windows devices, Linux devices show the device description correctly.

Snippet from the debug Data Query result for a Windows host:
```
Total: 0.71, Delta: 0, Located input field 'ifDescr' [walk]
--
Total: 0.89, Delta: 0.18, Executing SNMP walk for data @ '.1.3.6.1.2.1.2.2.1.2'
Found item [ifDescr='53:6F:66:74:77:61:72:65:20:4C:6F:6F:70:62:61:63:6B:20:49:6E:74:65:72:66:61:63:65:20:31:00'] index: 1 [from value]
Found item [ifDescr='57:41:4E:20:4D:69:6E:69:70:6F:72:74:20:28:53:53:54:50:29:00'] index: 2 [from value]
Found item [ifDescr='57:41:4E:20:4D:69:6E:69:70:6F:72:74:20:28:50:50:54:50:29:00'] index: 3 [from value]
Found item [ifDescr='54:41:50:2D:57:69:6E:33:32:20:41:64:61:70:74:65:72:20:56:39:00'] index: 4 [from value]
Found item [ifDescr='57:41:4E:20:4D:69:6E:69:70:6F:72:74:20:28:4E:65:74:77:6F:72:6B:20:4D:6F:6E:69:74:6F:72:29:00'] index: 5 [from value]
[...]
```

For comparison, a Linux host returns this debug output:
```
Total: 0.47, Delta: 0, Located input field 'ifDescr' [walk]
--
Total: 0.58, Delta: 0.12, Executing SNMP walk for data @ '.1.3.6.1.2.1.2.2.1.2'
Found item [ifDescr='lo'] index: 1 [from value]
Found item [ifDescr='tunl0'] index: 2 [from value]
Found item [ifDescr='sit0'] index: 3 [from value]
Found item [ifDescr='eth0'] index: 4 [from value]
Found item [ifDescr='eth1'] index: 5 [from value]
[...]
```

Issue seems related to #580.

**Comment by cigamit** [comment]
Do you have php-snmp installed?  If so, uninstall is and try again using the binaries.

**Comment by dschall** [comment]
Earlier, I checked php.ini and the php-snmp module was not commented out.

However, it seems that's not how PHP on Ubuntu works.
I disabled the php-snmp module now using the command ``phpdismod snmp`` and that seems to do the trick.

Thank you, closing this bug.
