### ISSUE TITLE
ERROR in cli/poller_output_empty.php

### ISSUE THREAD

**Issue by dabeani** [Cacti/cacti#110]
hi,

i found one error message when i try to run cli/poller_output_empty.php.

following error message:
root@bmk-cacti-01:/usr/share/cacti/cli# php poller_output_empty.php 
PHP Fatal error:  Uncaught Error: Call to undefined function dsstats_poller_output() in /usr/share/cacti/lib/poller.php:488
Stack trace:
#0 /usr/share/cacti/cli/poller_output_empty.php(81): process_poller_output(Resource id #34, false)
#1 {main}
  thrown in /usr/share/cacti/lib/poller.php on line 488
root@bmk-cacti-01:/usr/share/cacti/cli#

it is the latest git version (8c25f9c).

br
Bernhard

**Comment by cigamit** [comment]
Resolved.  Thanks.  Keep testing.
