### ISSUE TITLE
Structured path not created when using remote poller and Update On-Demand

### ISSUE THREAD

**Issue by thurban** [Cacti/cacti#1100]
With the bugfix from #376 the structured path is only created by the poller. When using remote pollers with the On-Demand Update option, the structued path for new devices is only created after the specific time or max item limit has been reached.

Maybe an  option to force-run the creation with the next poller cycle for new data sources would help.

Current workaround is to wait for the normal update to kick in, or set th max-item limit to a very low number (e.g. 1) so the rrd update is forced to run.

**Comment by cigamit** [comment]
Thomas, we would welcome a pull request if you can muster the creative energy to crease one.

**Comment by netniV** [comment]
The poller is only kicked in on schedule by cron (or task scheduler on windows) as far as I was aware.  Therefore, you can't force it to kick in from the website.  Instead, we should be handling gracefully that the files may not exist yet if we are in a structured approach by possibly adding a "requires update" flag which gets cleared by the poller.

**Comment by thurban** [comment]
This may be related to https://github.com/Cacti/cacti/issues/4850

**Comment by TheWitness** [comment]
Marking this one closed then.
