### ISSUE TITLE
data_sources.php: Cannot delete datasources with search filter

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#1102]
1. Find something
2. Choose few things
3. Choose to delete from "Choose an actions"

Your choiced data sources is unchosen and all the positions are gray.
If it's a feature that checks if data source got graphs in my opinion there should be an error message no only coloring it as gray and Your choice should not be unchoosed.

**Comment by cigamit** [comment]
That is by design.  There is a column 'Deletable', it will be 'No' for those Data Sources since there exist from one to many graphs using those Data Sources.

**Comment by interduo** [comment]
Ok - didn't see that column for first time.
Thanks ;-)
