### ISSUE TITLE
Fixed PHP NOTICE when using LDAP authenication

### ISSUE THREAD

**Issue by gabiann** [Cacti/cacti#1111]
Hello,

I just updated from 1.0.27 to 1.0.28 and LDAP authentication stopped working.
I have the following in my logs:

23/Nov/2017 15:38:32 - ERROR PHP NOTICE: Undefined variable: user in file: /store/cacti/cacti-1.1.28/auth_login.php on line: 209
23/Nov/2017 15:38:32 - CMDPHP PHP ERROR NOTICE Backtrace: (/index.php: 25 include)(/include/auth.php: 82 include)(/auth_login.php: 209 CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)
23/Nov/2017 15:38:32 - ERROR PHP NOTICE: Undefined variable: user in file: /store/cacti/cacti-1.1.28/auth_login.php on line: 227
23/Nov/2017 15:38:32 - CMDPHP PHP ERROR NOTICE Backtrace: (/index.php: 25 include)(/include/auth.php: 82 include)(/auth_login.php: 227 CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)
23/Nov/2017 15:38:32 - ERROR PHP NOTICE: Undefined variable: user in file: /store/cacti/cacti-1.1.28/auth_login.php on line: 242
23/Nov/2017 15:38:32 - CMDPHP PHP ERROR NOTICE Backtrace: (/index.php: 25 include)(/include/auth.php: 82 include)(/auth_login.php: 242 CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)

Local authentication is working properly.

Thank you
Regards

**Comment by netniV** [comment]
Can you let me know what you have set for your authentication method?  Either via Settings -> Authentication -> Authentication Method or using the following SQL:

```
select * from settings where name = 'auth_method';
+-------------+-------+
| name        | value |
+-------------+-------+
| auth_method | 4     |
+-------------+-------+
```

I believe that a value of 3 is LDAP Auth and 4 is Multi-LDAP auth

**Comment by gabiann** [comment]
Hi netniV,
The authentication method is set to LDAP Authentication

select * from settings where name = 'auth_method';
+-------------+-------+
| name        | value |
+-------------+-------+
| auth_method | 3     |
+-------------+-------+
1 row in set (0.00 sec)

**Comment by netniV** [comment]
OK, I'll take a look.  I suspect that you are hitting an error condition that isn't populating the $user variable with an array.  It should always populate it, even if it's just an empty array.
