### ISSUE TITLE
Cannot select one checkbox

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#112]
data_sources.php.

You can choose all checkboxes by clicking at select-all checkbox.
You can't choose one in list.

**Comment by interduo** [comment]
data_source_profiles.php <--- the same here

**Comment by interduo** [comment]
data_templates.php also :)

**Comment by interduo** [comment]
data_queries.php <--- here You can choose not deleteable

**Comment by cigamit** [comment]
Okay, fixed now.
