### ISSUE TITLE
Local user login fails with Multi/Single LDAP enabled

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1122]
This seems to be linked to Issue #446 where local auth was disabled if using LDAP because of the "break" in the case statement.  I think a flag needs to be defined that determines whether to try local auth if a user is not found via LDAP or Multi-LDAP.

I am working on a fix for this.

**Comment by netniV** [comment]
There are some logic issues, which I have sorted out locally relating to authentication.  I have also updated the secpass_login_process() so that it doesn't pull back all users but just the user we are attempting to update.  This makes sense given that whilst looping through all users it was checking for a match against the username anyway!

However, I still seemed to be unable to login as a test user, so I added some extra debug info:

...
$p = get_nfilter_request_var('login_password');
$stored_pass = substr($stored_pass, 0, 60);
$valid = password_verify($p, $stored_pass);
$test_pass = password_hash($p, PASSWORD_DEFAULT);
$test_valid = password_verify($p, $test_pass);

cacti_log("DEBUG: User '" . $username . "' password is " . ($valid?'':'in') . "valid", false, 'AUTH');
cacti_log("DEBUG: User '" . $username . "' password test is " . ($test_valid?'':'in') . "valid, has does " . ($stored_pass == $test_pass ? "":"NOT ") . " match ('" . $stored_pass . "' vs '". $test_pass . "')", false, 'AUTH');
...

and it returned the following:

```
2017/12/01 17:32:30 - AUTH DEBUG: User 'testuser' password is invalid
2017/12/01 17:32:31 - AUTH DEBUG: User 'testuser' password test is valid, has does NOT match ('$2y$10$UM8tiLphZrAp2gwg7t9UF.31iSLYhqjKLRNOjnMXXCGlvbaIXGv1y' vs '$2y$10$EMX5Vx37TzekFd3q1qhumewhfFVmPC5XLnRwXlIBjREviLYmm.AeK')
...

Then I updated the users password via the edit form but still ended up with:

...
2017/12/01 17:33:30 - AUTH DEBUG: User 'testuser' password is invalid
2017/12/01 17:33:30 - AUTH DEBUG: User 'testuser' password test is valid, has does NOT match ('$2y$10$UM8tiLphZrAp2gwg7t9UF.31iSLYhqjKLRNOjnMXXCGlvbaIXGv1y' vs '$2y$10$DhjdruFFt3yqW3AAPDrhFOwaK40j0S8hEOearXVoAVWDVBezWLV3K')
```

Note that the first hash is the stored hash, the second is the calculated hash based off the password that was entered on the login form.  In between these two lines, I updated the users password, or at least thought I had, but the password does not seem to have taken.

**Comment by netniV** [comment]
I have already fixed up a problem where secpass_login_process does not check for the presence of password_verify and just uses md5.  I am wondering if this is a problem elsewhere.

**Comment by cigamit** [comment]
There might be an issue here in that we are using strong passwords in newer versions of PHP.  We only fall back to md5() for older PHP versions.  So, there might be an issue here.

**Comment by netniV** [comment]
Yeah my thoughts where that not all code is doing it right. Part way through my proposed fix, I will have it finished on. Monday

**Comment by cigamit** [comment]
Thanks for your help.  We appreciate it!

**Comment by netniV** [comment]
I have now created pull request #1129  which includes fixes for local user login error and corrects password update functionality.  Let me know if there is anything I need to tweak on that, took a while due to debugging it and then introducing the new functions.
