### ISSUE TITLE
DB table 'poller_output_boost' very large

### ISSUE THREAD

**Issue by pautiina** [Cacti/cacti#1127]
Hello.
I don't use **boost**, but the table `poller_output_host` in the database is constantly growing, and I have to clean it from time to time, as the disk space ends. Perhaps this is a bug, but maybe I'm doing something wrong?
![64](https://user-images.githubusercontent.com/11805503/33547962-57719c4e-d8ee-11e7-8d81-603cd84b373d.png)
![65](https://user-images.githubusercontent.com/11805503/33548153-f140050e-d8ee-11e7-8042-c63c90914e10.png)

**Comment by cigamit** [comment]
If running remote pollers, boost is a requirement.  If not, just truncate the table between polling cycles.

**Comment by pautiina** [comment]
I'm using local poller.
Some time ago I turned on the boost, but due to the fact that the network-wethermao plugin did not work correctly, I disabled the boost.
I truncate table from time to time, but I do not always have time to finish the disk space

**Comment by SergejLT** [comment]
Same with me. cacti v1.1.26
I'm also using local poller.
2 weeks ago enabled poller boost at same day then deactivated. But boost table size keeps increasing from that point.


![cacti_boost](https://user-images.githubusercontent.com/32635039/33702159-213171b0-db2b-11e7-903c-4ff3ad32ee10.PNG)


![cacti_boost_2](https://user-images.githubusercontent.com/32635039/33702167-27a31eea-db2b-11e7-9320-52e70a618939.PNG)

**Comment by SergejLT** [comment]
I found what was causing this.
Need to nutick **direct population to poller_boost table** and then disable RRD on-demand updating and save :)

![cacti_boost_3](https://user-images.githubusercontent.com/32635039/33704576-b85b2ac2-db35-11e7-9fdc-5567aa161504.PNG)

I think it needs to be by default when disabling **on-demand RRD update** the **direct population to poller_boost table** option also disables.

**Comment by pautiina** [comment]
@SergejLT thanks for help.
I also think that  **direct population to poller_boost table** must be disabled, when we disabled Boost globaly

**Comment by cigamit** [comment]
Oh, this would be a spine bug.  Can soneone open there?
