### ISSUE TITLE
PHP Warning:  Illegal string offset 'password_change' in lib/functions.php

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1128]
Whilst debugging, noticed the following error in my logs:

`PHP Warning:  Illegal string offset 'password_change' in /usr/share/cacti/site/lib/functions.php on line 414, referer: https://man.gouldhall.com/cacti/user_admin.php?action=user_edit&tab=general&id=12`

I think this is because a custom message can be set which is purely just a string value.  So when using raise_message() if a custom message has been used in place of an array, it tries to use the string value as an index in the string.

Need to review the raise_message() and display_output_messages() functionality to better handle this.

**Comment by cigamit** [comment]
What version of Cacti are you working from?

**Comment by netniV** [comment]
I think the problem is that somewhere, a custom message is being set which replaces the array.  As such, when trying to set element 'password_change' in the array, it fails.  I'll check my php version but I don't think that will matter.  This was using the master branch.

**Comment by cigamit** [comment]
Well, the default behavior would be that if it's not an array, let's say it's a string, we should whack it and change it into an array, and just set the element.  It seems like some PHP bug.  Though I could be wrong.

I can not see how this would ever fail:

`$_SESSION['sess_messages'][$message_id] = $message_id;`

**Comment by netniV** [comment]
Because sess_messages is a string,, setting sess_messages[‘password_change’] makes it invalid.

**Comment by cigamit** [comment]
Okay, just tested.  Got it now.  So, it's somewhere in the code where you attempt to 'raise_message()' twice in a row.  This is likely due to your recent changes in the authentication pull request.  Have to hunt it down.  Might be in the custom message function.

**Comment by netniV** [comment]
You may be correct.  Due to the rejig it may be hitting raise_message more than once... which I guess could always have potentially occurred depending on what was happening for someone to do.

**Comment by cigamit** [comment]
So, the raise_message function is not called in a few cases in the code.  The frist is in data_sources.php and the second is in csrf-magic.php.  There are also a few plugins attempting to set the 'sess_messages' session variable.  These are the cases where this problem will occur.  I think both can be migrated to using the standard $messages array, but it also identifies a weakness of the API.  There is presently no way to set a custom error message.  This problem has been around for several years, and some plugins have worked around this in various ways.  More info to follow.

**Comment by cigamit** [comment]
I'm going to mark this as closed now.  We should open a feature request asking to enhance message handling though.
