### ISSUE TITLE
cacti_log() - POLLER_VERBOSITY_xxx level check incorrect

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1130]
When recording to the system log file via the cacti_log() function, you can pass  one of the following constants:

```
POLLER_VERBOSITY_NONE   => __('NONE - Syslog Only if Selected'),
POLLER_VERBOSITY_LOW    => __('LOW - Statistics and Errors'),
POLLER_VERBOSITY_MEDIUM => __('MEDIUM - Statistics, Errors and Results'),
POLLER_VERBOSITY_HIGH   => __('HIGH - Statistics, Errors, Results and Major I/O Events'),
POLLER_VERBOSITY_DEBUG  => __('DEBUG - Statistics, Errors, Results, I/O and Program Flow'),
POLLER_VERBOSITY_DEVDBG => __('DEVEL - Developer DEBUG Level')
```

However, if the system is currently set to LOW, the system is actually only recording those with NONE.  In lib/functions.php's cacti_log():

`} elseif ($level >= $logVerbosity) {`

should actually be

`} elseif ($level > $logVerbosity) {`

Otherwise, you will never be able to actually record DEBUG only level items.  DEVDBG is a special case that only records NONE and DEVDBG items (useful if you want to only see specific log calls without the rest at a given level.

For example I was trying to record a LOW message about user authentication failing and the lock increasing in Issue #1122/PR #1129 but I couldn't ever see it until I switched to MEDIUM.  Using the above change this correctly worked,

I haven't created a pull request or changed committed code yet just in case I am wrong about how this functionality should work.

**Comment by netniV** [comment]
I have further strengthened my belief that this is wrong based off the spine_log() level checks.

#define SPINE_LOG(format_and_args)        (spine_log format_and_args)
#define SPINE_LOG_LOW(format_and_args)    (void)(set.log_level >= POLLER_VERBOSITY_LOW && spine_log format_and_args)
#define SPINE_LOG_MEDIUM(format_and_args) (void)(set.log_level >= POLLER_VERBOSITY_MEDIUM && spine_log format_and_args)
#define SPINE_LOG_HIGH(format_and_args)   (void)(set.log_level >= POLLER_VERBOSITY_HIGH && spine_log format_and_args)
#define SPINE_LOG_DEBUG(format_and_args)  (void)(set.log_level >= POLLER_VERBOSITY_DEBUG && spine_log format_and_args)
#define SPINE_LOG_DEVDBG(format_and_args) (void)(set.log_level >= POLLER_VERBOSITY_DEVDBG && spine_log format_and_args)

Whilst I know the above is spine code, this uses an inverted check to cacti_log().  These macro's check that the level is at that level or higher before running the spine_log command.  cacti_log() is checking if a level is below or equal to it, and if so returning without logging.  This means there is definitely inconsistency in the logging levels.

**Comment by cigamit** [comment]
Developer debug only logs SQL calls and statistics.  That's it's intent anyway.  I would suggest you use either MEDIUM, or put the auth_login.php into debug mode when testing.

**Comment by netniV** [comment]
Useful to know about the intent of the DEVDBG, though I think it's being used for more than that in some places ;-)

However, the issue I have is that the logging level is not correctly applied.  Hence, if you set the logging level to LOW and LOW marked logs will not actually be logged.

**Comment by cigamit** [comment]
Well that is odd.  So you are saying you are using cacti_log(...., LOW); and it's not logging at 'LOW' level?

**Comment by netniV** [comment]
Yes, that what I found.  If you look at the [Line 569-582](https://github.com/Cacti/cacti/blob/develop/lib/functions.php#L569) which caculates whether to log or not.  It works inversely to the way that spine does but does not correct have the inverted way.  So, either cacti is wrong or spine is ;-)

Here is a commented version of the code to demonstrate

```
        // By default $force_level will be blank, unless a page/device is marked as being always debuggable
	if ($force_level == '') {
                // If we have been provided with a level, lets check it
                // Otherwise we assume that we want to log it at all times
		if ($level != '') {
                        // Get the log setting for debug.
			$logVerbosity = read_config_option('log_verbosity');
                        // Are we in the special DEVDBG mode?
			if ($logVerbosity == POLLER_VERBOSITY_DEVDBG) {
                                // Yes, so lets check whether the logging level is DEVDBG
				if ($level != POLLER_VERBOSITY_DEVDBG) {
                                        // No, but is the level above LOW ?
					if ($level > POLLER_VERBOSITY_LOW) {
                                                // Yes it's not low, so lets not record it
						return;
					}
				}
                        // Log setting isn't DEVDBG, is the level equal to or greater than the setting?
			} elseif ($level >= $logVerbosity) {
                                // Yes, the setting is equal or greater than it so DON'T record it, just return
				return;
			}
		}
	}
```

I'd of created a patch for it, but as it was so small I figured you'd just change it ;-)

**Comment by cigamit** [comment]
Do a pull.  Thanks!
