### ISSUE TITLE
Path-Based Cross-Site Scripting (XSS)

### ISSUE THREAD

**Issue by andermat8** [Cacti/cacti#1137]
Running Windows 2012 Cacti version 1.1.28 and had a security scan done on the system and it is showing several XSS issues.  I'll try and attach the results 
[High_Vuln_for_application_cacti.xlsx](https://github.com/Cacti/cacti/files/1556512/High_Vuln_for_application_cacti.xlsx)

file for viewing.

**Comment by netniV** [comment]
I'm no expect on XSS as it can be quite troublesome.  However, I did notice that the requestURI is appearing in a javascript output so I would imagine that is one place this fails.  It would be nice if there were some more explanation behind how it fails not just that it did.

**Comment by netniV** [comment]
For reference, the XSS requestURI that I mentioned is because of the line in global_session.php which just places the requestURI in to the script without any sanitation.

```
<script type='text/javascript'>
	var cactiVersion='<?php print $config['cacti_version'];?>';
	var theme='<?php print get_selected_theme();?>';
	var refreshIsLogout=<?php print $refreshIsLogout;?>;
	var refreshPage='<?php print $myrefresh['page'];?>';
	var refreshMSeconds=<?php print $myrefresh['seconds']*1000;?>;
	var urlPath='<?php print $config['url_path'];?>';
	var previousPage='';

        // THE FOLLOWING  LINE IS WRITTEN OUT WITHOUT ANY CHECKS
	var requestURI='<?php print $_SERVER['REQUEST_URI'];?>';

	var searchFilter='<?php print __('Enter a search term');?>';
	var searchRFilter='<?php print __('Enter a regular expression');?>';
	var clearFilter='<?php print __('Press Ctrl+Shift+X to Clear Filter');?>';
	var noFileSelected='<?php print __('No file selected');?>';
	var timeGraphView='<?php print __('Time Graph View');?>';

```

However, I am not yet versed in how that requestURI variable is used.  @cigamit or @ronytomen I think are better placed to answer that.

**Comment by netniV** [comment]
There is an old issue that also seems to refer to this problem [Issue 479](https://github.com/Cacti/cacti/issues/479) but from a different angle.  The fix suggested there is one possible way, though I believe cacti has it's own sanitation routines now anyway.

**Comment by andermat8** [comment]
Thanks for looking into this netniV.  I keep upgrading but the scans keep finding this issue.

**Comment by pautiina** [comment]
On my system (Freebsd) I dont have this problem

**Comment by netniV** [comment]
@pautiina I have this problem with the latest source.  Can you check your global_session.php file to see if it has the lines I mentioned?

**Comment by cigamit** [comment]
This is not an issue.  The person submitting this bug is not using the latest version of Cacti.  If you have any concern, diff your version of global_session.php with the released version.  They are different.

**Comment by andermat8** [comment]
I'm running version 1.1.28.  It is the latest version for Windows.

**Comment by cigamit** [comment]
Did you install from source, or from the installer?  If using the installer, this might be a packaging issue.  Either way, it's not an issue with the latest version of Cacti.  Please let us know how you installed/updated.

**Comment by andermat8** [comment]
I used the Windows installer.

**Comment by netniV** [comment]
@cigamit It is an issue as I get it myself using the git clone

**Comment by cigamit** [comment]
The requestURI is sanitized by the sanitize_uri() function which prevents injection.  I've looked at the cases and they are safe when presented in the when they are rendered in the dom.  So, this should be a non-issue.

**Comment by netniV** [comment]
I wil double check this again later but I believe when I looked at my live source it was not.

**Comment by cigamit** [comment]
The package maintainer for the Windows package has confirmed that the global_session.php does include the call to the sanitize_uri() function.  So, you can put this one on the bottom of your list from my perspective.  Thanks for all your help otherwise.

**Comment by netniV** [comment]
I have also verified that my source does have that around it.  I think I must have been looking at an older version folder when I was looking at another issue such as the database upgrade ones. 

However, there does lie an issue in that pen testers will be marking CACTI as having XSS issues when in fact it does not... plus the script tags I put on the URL did end up in my javascript source that was embedded in the page.
