### ISSUE TITLE
Cacti 1.1.28 After create custom graph template, impossible to aggregate it with Data Queries

### ISSUE THREAD

**Issue by Izmenoff** [Cacti/cacti#1138]
![image](https://user-images.githubusercontent.com/17400240/33979293-bfba11a0-e0b4-11e7-904d-940cb398ac82.png)
![image](https://user-images.githubusercontent.com/17400240/33979346-f749e3de-e0b4-11e7-904a-7cb58a9cc29e.png)

**Comment by cigamit** [comment]
You have to be more specific.  I really don't know what you are talking about.
