### ISSUE TITLE
Cacti-1.1.28 / Weathermap 0.98 - (increase memory_limit in php.ini ) warning logs related to a used WEATHERMAP 

### ISSUE THREAD

**Issue by Kallyx** [Cacti/cacti#1140]
Hi,

System: RHEL7, php 5.4.45
I have encountered below warnings related to a WEATHERMAP map. Could you please have a look and let me know if you have found a fix for this?
 WEATHERMAP [Map 5] preprod.conf: **About to write image file. If this is the last message in your log, increase memory_limit in php.ini [WMPOLL01]**
Attached the logs below:
[logs.txt](https://github.com/Cacti/cacti/files/1563095/logs.txt)

**Comment by pautiina** [comment]
It's not cacti problem. WEATHERMAP not ready for new cacti yet.

**Comment by netniV** [comment]
as @pautiina has said Weathermap has it's own Issues section for reporting problems.  However, you may be reminded that the version of Weathermap out is not offically 1.x compatible as far as I am away.

https://github.com/howardjones/network-weathermap

In the meantime, PHP has a memory limit and the combination of all the catci and plugin's are probably using more memory on a given call than the default limit.  You can set this in various places, though its normal to put this in the sites .htaccess file if it's only one site that needs more memory.

Take a look at http://www.php.net/manual/en/ini.core.php#ini.memory-limit and http://docs.presscustomizr.com/article/171-fixing-maximum-upload-and-php-memory-limit-issues which shows the steps you'd be expected to take for wordpress though they are the same for cacti as long as you ignore the wp-config parts

**Comment by pautiina** [comment]
@Kallyx you also can look for error hear http://network-weathermap.com/manual/0.97b/pages/errorcodes.html

**Comment by Kallyx** [comment]
Hi,

Thanks! Fond this, in provided ducumentation:

**[WMPOLL01]**

    "About to write image file. If this is the last message in your log, increase memory_limit in php.ini"

    PHP has a hard memory limit, to stop runaway scripts from killing your server. Depending on the version of PHP, this can be quite low (8M in older versions). Weathermap uses a lot (relatively) of memory to produce the large image files. If it hits the PHP memory limit, then PHP just kills the script with no warning. Because it log that it is dead (because it is dead), it logs just before the 'risk' happens. **_If this log message is not the last message in your log file, then nothing is wrong!_**

-Not sure what they wanted to say with above highlighted phrase. According to them everything is ok if that message is not the last one in the log file.

Attached the last logs.
[last-logs.txt](https://github.com/Cacti/cacti/files/1567679/last-logs.txt)


    You can disable some messages like this one by changing settings in Cacti. Go to Settings..Misc and set Weathermap Logging to 'Quiet'. If you suddenly get a mystery where Weathermap is only updating some maps, turn it back to 'Chatty' to see what is happening.

**Comment by pautiina** [comment]
Yes, it's all right. I also have such messages, but everything is working fine

**Comment by netniV** [comment]
OK, Basically, in order to give you some indication that Weathermaps is failing, it records a "dummy" message that is nothing more than "if you see this message last, your problem is this".  As you are not seeing it as the last message, you can safely ignore it.  The "Wrote map" line which follows shows that it correctly wrote the map so you can ignore the "dummy" message.

**Comment by Kallyx** [comment]
Understood, the point is that currently I've created only 3 maps, but I should create around 30/ 35 Weathermap maps and the  Memory Limit of PHP (Version 5.4.45) is set to 128M. I think in this scenario it would be a problem, right? Could you please help with a suggestion? How should I solve this?
Thank you!

**Comment by netniV** [comment]
If you are worried about the memory usage, you could add the memory usage to the end of the "placeholder" message using the php function:
[memory_get_usage()](http://php.net/manual/en/function.memory-get-usage.php)

As you add more graphs, this will give you an idea of how the usage is increasing.

**Comment by cigamit** [comment]
I'm going to close this, but carry on if you like since it is not a cacti issue.
