### ISSUE TITLE
Graph List Mode issue

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#1141]
There is a bug I keep running into with the list mode function. I select 91 or so graphs for a device, but after viewing the graphs I am limited to only seeing 50 graphs. When I'm shot over to the graphs I do get a "1 to 50 of 91" graphs, but I hit the "next" button and I'm presented with "All 50 graphs". Peek has stopped functioning reliably on my machine for some reason, so I can't share this behavior. I'll keep trying though.

**Comment by eschoeller** [comment]
![peek 2017-12-15 21-44](https://user-images.githubusercontent.com/12864741/34067365-4b004338-e1e1-11e7-842b-f0de6b727f43.gif)

had to act real fast on this, the longer I run peek for the more unreliable it gets. I hope you can see what I'm referring to.

**Comment by netniV** [comment]
What release are you working with?

**Comment by eschoeller** [comment]
1.1.27

**Comment by netniV** [comment]
I have 1745 graphs, and when I select all my entries, then click to preview, it displays the page.  Then when you first hit next, it doesn't actually move forward until you click it a second time.  If you use a smaller selection, (ie, 10 per page) does that happen?  I think that is what is occurring.

I also noticed, if I click into the URL and hit return, it resets back to page one, which suggests that it is down to the large URL being used. I'll take a look later today to see what might be causing these two things.

**Comment by netniV** [comment]
Actually, I just did this with a smaller selection and there is an issue with the selection process.  Using just 10 items selected, click on View, it shows the 10 graphs.  Reduce that to 4 graphs in the filters section and it correctly shows **`1-4 of 10 [ 1 2 3 ]`** but then click on 1 2 or 3 and the page reloads with **`1 to 4 of 1745 [ 1 2 3 4 5 ... 437 ]`** which is neither the page number I clicked on nor the selections I had made.

**Comment by eschoeller** [comment]
Yeah I think it's some kind of strange session / caching issue.

**Comment by netniV** [comment]
It may be a similar issue that I've fixed before where the URL parameters are kind of ignored when they shouldn't be.  Normally because they weren't passed before.  Though I did notice that no URL differences where noticable during my quick test so tomorrow I will have to see if it's a combination of using the AJAX calls not updating the local URL or parameter properly.

**Comment by netniV** [comment]
These are the steps I went through once on the list view

### Select just 10 per page

> /graph_view.php?action=list&header=false&page=1&host_id=-1&rows=10&graph_template_id=0&rfilter=&graph_list=&graph_add=&graph_remove=

```
action                  list
header                  false
page                    1
host_id                 -1
rows                    10
graph_template_id       0
rfilter        
graph_list        
graph_add        
graph_remove        
```

### Select ALL then click page 2 

> /graph_view.php?action=list&header=false&page=2&graph_list=&graph_add=1938,1975,1954,1955,1956,1957,1958,1972,1988,1951&graph_remove=

```
action                  list
header                  false
page                    2
graph_list        
graph_add               1938,1975,1954,1955,1956,1957,1958,1972,1988,1951
graph_remove        
```

### Tick another graph and click on view

> /graph_view.php?action=preview&rfilter=&host_id=-1&graph_template_id=0&style=selective&graph_add=&graph_remove=&graph_list=1938,1975,1954,1955,1956,1957,1958,1972,1988,1951,1952&reset=1&header=false

```
action                  preview
rfilter                 -1
host_id        
graph_template_id       0 
style                   selective
graph_add        
graph_remove        
graph_list              1938,1975,1954,1955,1956,1957,1958,1972,1988,1951,1952
reset                   1
header                  false
```

### Filter to just 4 graphs per page **

> /graph_view.php?action=preview&rfilter=&host_id=-1&columns=3&graphs=4&graph_template_id=0&thumbnails=true&header=false

```
action                  preview
rfilter        
host_id                 -1
columns                 3
graphs                  4
graph_template_id       0
thumbnails              true
header                  false
```

### Select next but display is still first page **

> /graph_view.php?header=false&page=2&graph_list=1938,1975,1954,1955,1956,1957,1958,1972,1988,1951&graph_add=&graph_remove=

```
header                  false
page                    2
graph_list              1938,1975,1954,1955,1956,1957,1958,1972,1988,1951
graph_add        
graph_remove        
```

So, on testing this, it would appear the problem isn't with the returned JSON (well not directly) as that appears to update to the correct page as you go through.  However, the page does not reflect the JSON correct, so it may be a problem with the gotopage() function in some way.

Time to brush up on my javascript skills and see what else is going on.

**Comment by cigamit** [comment]
There are some parts of the code that I don't really like, this is one of them.

**Comment by cigamit** [comment]
I hear you.  I'll take a look at it.  It's definitely broken at this time.

**Comment by cigamit** [comment]
Resolved.  This bug was introduced when we took the navigation from list most to preview mode through an ajax callback.  The patch resolves this issue.

**Comment by eschoeller** [comment]
I upgraded to 1.1.28 and then put in this patch. Everything I was seeing (this issue, and possibly one or two other oddities) are resolved and I'm not seeing any strange behavior anymore. Thanks a lot for fixing this! I was actually having some real difficulty looking at some graphs that I really needed to see.
