### ISSUE TITLE
Reporting schedule not saving proper time

### ISSUE THREAD

**Issue by jhonnyx82** [Cacti/cacti#1144]
For Reporting (aka Nectar) the time selected in the main settings page is not propagated in the future events and it keeps only the time of when the report was saved.

NOTE : the days are ok

![image](https://user-images.githubusercontent.com/26431888/34117307-97a8b67a-e41b-11e7-8523-9ba68d86ad82.png)

![image](https://user-images.githubusercontent.com/26431888/34117326-a3d9b7f0-e41b-11e7-92af-68ac896b2273.png)

**Comment by netniV** [comment]
Can you give me the steps to reproduce this and I'll see if I can spot anything.  I don't use the reporting much so someone else may have a better idea.

**Comment by jhonnyx82** [comment]
Just create a weekly report to start at a specific datecand time in the
future and you will see in the events tab that it will be scheduled for the
saved time rather thsn the set time

**Comment by netniV** [comment]
OK, I couldn't get this to replicate but my date format was appearing in reverse format when I created it.  This could be down to the system date setting, what are your default date formats?

**Comment by netniV** [comment]
Additionally, if you create a new report and set the report to be in the future, but don't fill in any other details bar the title, what date appears when the page reloads asking for more information?

**Comment by netniV** [comment]
@jhonnyx82 Have you had a chance to try the suggestions I made above?

**Comment by jhonnyx82** [comment]
> Additionally, if you create a new report, set the title, click the enable option and set the report to be in the future, but don't fill in any other details, what date appears when the page reloads asking for more information?

It keeps the date i set in the **Next Timestamp for Sending Mail Report**

**Comment by netniV** [comment]
Hmm, OK. What do you have set within settings for date time?
![image](https://user-images.githubusercontent.com/9052188/34301132-2049140c-e723-11e7-9aa2-ded847e2fc18.png)

**Comment by jhonnyx82** [comment]
Day / month name / year

 

/ as separator

**Comment by netniV** [comment]
What language region is your browser in?  I will see if I can get this replicated in the new year.

**Comment by jhonnyx82** [comment]
English

**Comment by netniV** [comment]
OK, thanks, I just wanted to check as I noticed the email was in Italian.  I'm having trouble replicating your issue at the moment, so I may add some debug statements to a patch and get you to try those out.

**Comment by netniV** [comment]
Oh, one other thing, which version of cacti are you running?

**Comment by jhonnyx82** [comment]
1.1.28

**Comment by cigamit** [comment]
This is one thing that I do not like about the nectar reporting.  The events display is for future events, and does not include real events in the past.  I would prefer it use the same scheduler as we are using for the Automation that we use today.  So, it's a sizable project.  Also, I would like to abstract what we have done in for Automation to a class with it's own tables, then migrate both the Automation and Nectar during the upgrade process.

netniV and pautina, do either of you have interest in taking that project?

**Comment by pautiina** [comment]
Hello. 
At the moment I do not use this functionality. while there is no interest.

**Comment by netniV** [comment]
I've not looked at it with any great detail yet so I'm not entirely sure what parts you'd like to extract.  The automation plugin is one I've not looked into at all so far.

However, if you have any pointers, I could give it go :)

**Comment by cigamit** [comment]
Thanks Alex.  No problem.

**Comment by cigamit** [comment]
netniV,

What I would like to pull out is the scheduler piece for sure.  So, there is the dropdowns (multi-select), and the 'base time'.  Then, the scheduler API in the poller function.  I've attached four images here capturing the columns that are required, there are some underlying columns required in the database for things like the last runtime.

I would suggest a new schedules table that includes the columns, and then, change the automation_networks to point to the schedule_id, and the same with nectar/reports.  Then write an API function to determine if now is the time to run, maybe a few class functions like 'time till next run' or 'next run date/time'.  Also class functions like create, modify, remove, etc.

![schedulerimage1](https://user-images.githubusercontent.com/957322/34441976-b48c89a8-ec84-11e7-9fb7-349103439134.png)
![schedulerimage2](https://user-images.githubusercontent.com/957322/34441977-b70579d8-ec84-11e7-81c6-5f46b72c7c73.png)
![schedulerimage3](https://user-images.githubusercontent.com/957322/34441978-b999ab9c-ec84-11e7-85f3-8a57310d429f.png)
![schedulerimage4](https://user-images.githubusercontent.com/957322/34441980-bba4e88e-ec84-11e7-8f82-36733aa6e22d.png)

**Comment by netniV** [comment]
I've made a start on this.  Out of curiosity, when you say create a class, do you mean a proper PHP class or just a file with the functions in ?  Just so I know which direction of coding to do.  Long term, Classes are always better but most of cacti doesn't use them so I'm not sure if that's a direction the code is heading to at all.

**Comment by cigamit** [comment]
Yes, a genuine class if you can pull it off.

**Comment by netniV** [comment]
I have updated my repo with a class-based scheduler but it's not complete yet.  It will however, tell you a daily or weekly schedule given a start date.

**Comment by cigamit** [comment]
Good.

**Comment by netniV** [comment]
I've been thinking some more on this.  Would it not be better to allow the user to enter a cron-like schedule?

**Comment by cigamit** [comment]
I gave this some thought over night, and we need to provide a decent mechanism.  As long as cron can support the mix of options in the images above, then it's fine.  Otherwise, we will have to be more creative.  I'll have some additional comments once I get a little time to prototype some things.

**Comment by netniV** [comment]
Basically, cron supports multiple minutes, hours, days, weeks. But in our case, we could extend that syntax to also support F and L prefixes for first and last.
```
+-------------- Minute            (range: 0-59)
|   +---------- Hour              (range: 0-23)
|   | +-------- Day of the Month  (range: 1-31)
|   | | +------ Month of the Year (range: 1-12)
|   | | | +---- Day of the Week   (range: 1-7, 1 standing for Monday)
|   | | | | +-- Year              (range: 1900-3000)
|   | | | | | 

L   * * * * *   - would run on the last minute (59) of every hour of every day of every week of every year.
*/5 * * * * *   - would run 5 times an hour for every hour of every day of every week of every year.
*   * F * * *   - would run every minute of every hour on the first day of every week of every year.
*   * F * 2 *   - would run every minute of every hour on the first Tuesday of every week of every year.
```

**Comment by jhonnyx82** [comment]
I know I am being a pain here, but setting it in a calendar would be nice for larger deployments.

**Comment by cigamit** [comment]
You mean 'seeing' it in a Calendar, totally agree.  Setting it using a calendar is nice too.

**Comment by cigamit** [comment]
Well as long as it is GPL2 and supports ALL the options currently available on the automation page, we can look more closely at it.

**Comment by netniV** [comment]
Hmm, I assume you mean the license, https://github.com/dragonmantank/cron-expression/blob/master/LICENSE but that appears to be MIT based not GPL.  However, from what little I know as long as there is a copyright mention, we are free to use and modify it.

As for the options, that is why I'm thinking we have an interface class between the GUI and the cron expressions.  Then the background code all uses the cron expressions for calculations which would just work.

**Comment by cigamit** [comment]
An email to developers@cacti.net asking Linegod for interpretation would is required.  Give it a whirl, though I think you may be right, this is one of his specialties.

**Comment by netniV** [comment]
Done. Assume you'll see a copy that's sent there, if not I'll forward it to the git email address.

**Comment by netniV** [comment]
So, I decided to stick with the coding I started purely because there are some custom timing mechanisms that wouldn't fit with the Cron formats (the last two fields of a cron expression are effectively an OR statement).

You can take a look at the work so far at https://github.com/netniV/cacti/tree/Scheduler

Still to do is to add isDue() etc.  But for now that can be manually achieved via getNextRun().

**Comment by netniV** [comment]
I've now tested this under CentOS 6.9 with PHP 5.4.12 and the test_scheduler.php now runs from my Scheduler branch

**Comment by cigamit** [comment]
We will have to get back to this after the release.

**Comment by cigamit** [comment]
The original problem as reported has been closed.  We already have a separate ticket on the scheduler topic.
