### ISSUE TITLE
Cacti 1.1.28-problem about saving a snmp query data_template in live hosts

### ISSUE THREAD

**Issue by frontierliu** [Cacti/cacti#1145]
Problem:
When I save a snmp query data template (interface traffic) which has been used in live hosts，the graphs associated that data template collect no data anymore.

analyze:
In the table poller_item , check the  poller item of Interface traffic records, the  column "rrd_num" changed from 2 to 4. That led to collect data fault. It is because the rebuild poller_item procedure has a bug on update the data_input_data table when saving the interface traffic data template.

solved:
check the "lib/template.php",line 106 and line 109:
$did_vals .= ($did_cnt == 0 ? '':',') . '(' . $input_field['id'] . ', ' . $data_source['id'] . ', ' . db_qstr($template_input_fields[$input_field['id']['value']) . ')';
change to:
$did_vals .= ($did_cnt == 0 ? '':',') . '(' . $input_field['id'] . ', ' . $data_source['id'] . ', ' . db_qstr($input_field['value']) . ')';

I has checked the Cacti old version, this problem started at 0.8.7h. In the code before 0.8.7h, It was "($input_field['value'])", which work fine.

**Comment by netniV** [comment]
I will take a look and create an fix using you suggestion

**Comment by netniV** [comment]
Actually looking at the first code you pasted, it appears to be missing a closing square bracket, so that may be the answer rather than just removing it. I’ll tske a look at the file history tomorrow.

**Comment by frontierliu** [comment]
please take a look at the code "lib/template.php" that build $template_input_field array,   it is the original reason. actually , the structure $template_input_field shoud be remove totally, I thought.

**Comment by netniV** [comment]
Question, where did this template come from? Was it a 0.8.8 installation?

**Comment by netniV** [comment]
There was a commit [b04367203bc42d7464e944d3d3a2c09093fad824 - Fixed issue with custom data source information being lost when saved…](https://github.com/Cacti/cacti/commit/b04367203bc42d7464e944d3d3a2c09093fad824#diff-0c9f52f055c45e1dfd9100f0ad744d48) which introduced the templated field value.  This would suggest that your template is older than this and hence is having the problem.

**Comment by cigamit** [comment]
Please submit a screen shot of the data template, and the data query for the broken graphs.

**Comment by frontierliu** [comment]
thanks for your repid reply，I have checked the" rony's commit" which netniv suggested，it had already been in my cacti source code, but it is not relative to this problem. 
I was upgraded from cacti 0.8.8h to 1.1.28  about a month ago,  and when I changed the data template "Interface traffic" any properties,  I found that problem - all interface traffice graphs collected no data anymore.

**Comment by frontierliu** [comment]
here is the screenshot of  the data query "snmp - Interface Statistics":

the data query:
![20171222101255](https://user-images.githubusercontent.com/24820773/34282878-b01d900a-e703-11e7-8920-1823fafd8efc.jpg)

**Comment by frontierliu** [comment]
herer is the screenshot of data template "Interface -traffic":
![qq 20171222103612](https://user-images.githubusercontent.com/24820773/34283081-bf4c9ce6-e704-11e7-8091-c34b8d5c3f52.jpg)
![qq 20171222103637](https://user-images.githubusercontent.com/24820773/34283082-bf7e4d22-e704-11e7-80ef-0092719c527d.jpg)
![qq 20171222103651](https://user-images.githubusercontent.com/24820773/34283083-bfac9e34-e704-11e7-9b5c-7ee8ab92e2ee.jpg)

**Comment by cigamit** [comment]
Your issue is that the checkboxes on the three most important components of the template went unchecked.  So you lost the association.  You will have to recheck, and then save.  Maybe you will get lucky and the associations will be preserved, but I doubt it.  See the image below:

https://github.com/Cacti/cacti/issues

**Comment by cigamit** [comment]
Closing due to no response.
