### ISSUE TITLE
Required template to monitor the Cyberoam UTM box

### ISSUE THREAD

**Issue by komathodivijay** [Cacti/cacti#1147]
I'm using the Cyberoam CR300iNG and plan to monitor this devices using cacti 1.1.2 Version. Pls let us know is there any template for the same. I attached the MIB file for your reference.
[CYBEROAM-MIB.txt](https://github.com/Cacti/cacti/files/1578220/CYBEROAM-MIB.txt)

**Comment by cigamit** [comment]
This form is for reporting issues with Cacti, please take these types of questions to the forums.
