### ISSUE TITLE
[Cacti 1.1.28]: Issue on Automation Graph Rules - err:SQL Assoc Failed! "not any object is matching with set rules"

### ISSUE THREAD

**Issue by Kallyx** [Cacti/cacti#1149]
Hi Guys,

Could you please have a look on below issue?
[System used:RHEL 7, MariaDB 10.1.22-1 , PHP 5.4.45.]
I have created **Automation graph rules** below and seems, the added devices are matching with rules for device selection criteria, but **there are not any matching Objects.**

- In screenshot below you could find discovered interfaces by the applied data query template.

![create_graph_data_query](https://user-images.githubusercontent.com/27009071/34297476-0bd40466-e721-11e7-91b8-97d1b5fa028a.jpg)

- In screenshot below you can find the created automation rules for added devices.

![graph_automation_rule](https://user-images.githubusercontent.com/27009071/34297481-10d1a9be-e721-11e7-93b4-a30c72106c8c.jpg)

- Attached the received error logs:
[error_logs.txt](https://github.com/Cacti/cacti/files/1582407/error_logs.txt)

Appreciate any help on this matter. 
Thanks a lot!

**Comment by Kallyx** [comment]
copied "affected" rows from api_automation.php indicated by the output error.
/lib/**api_automation.php**: 816 db_fetch_assoc  
/*row 816         $total_rows = sizeof(db_fetch_assoc($rows_query));    */
/lib/**api_automation.php**: 824 db_fetch_assoc
/*row 824 	$snmp_query_indexes = db_fetch_assoc($sql_query);  */

**Comment by netniV** [comment]
The problem appears to be with the last WHERE statement.  For some reason, there is an AND inserted at the front of it, I will see if I can see a reason why that would be.

This is your query in SQL form (reformatted for easier viewing)
```
SELECT
  *
FROM (
  SELECT
    h.hostname AS automation_host,
    host_id,
    h.disabled,
    h.status,
    snmp_query_id,
    snmp_index,
    MAX(
      CASE WHEN field_name = 'ifAdminStatus' THEN field_value ELSE NULL  END
    ) AS 'ifAdminStatus',
    MAX(
      CASE WHEN field_name = 'ifAlias' THEN field_value ELSE NULL END
    ) AS 'ifAlias',
    MAX(
      CASE WHEN field_name = 'ifDescr' THEN field_value ELSE NULL END
	) AS 'ifDescr',
	MAX(
  	  CASE WHEN field_name = 'ifHighSpeed' THEN field_value ELSE NULL END
	) AS 'ifHighSpeed',
	MAX(
	  CASE WHEN field_name = 'ifHwAddr' THEN field_value ELSE NULL END
	) AS 'ifHwAddr',
    MAX(
        CASE WHEN field_name = 'ifIndex' THEN field_value ELSE NULL END
    ) AS 'ifIndex',
    MAX(
        CASE WHEN field_name = 'ifIP' THEN field_value ELSE NULL END
    ) AS 'ifIP',
    MAX(
        CASE WHEN field_name = 'ifMtu' THEN field_value ELSE NULL END
    ) AS 'ifMtu',
    MAX(
        CASE WHEN field_name = 'ifOperStatus' THEN field_value ELSE NULL END
    ) AS 'ifOperStatus',
    MAX(
        CASE WHEN field_name = 'ifSpeed' THEN field_value ELSE NULL END
    ) AS 'ifSpeed',
    MAX(
        CASE WHEN field_name = 'ifType' THEN field_value ELSE NULL END
    ) AS 'ifType',
    MAX(
        CASE WHEN field_name = 'ifName' THEN field_value ELSE NULL END
    ) AS 'ifName'
  FRON
    host_snmp_cache AS hsc
  LEFT JOIN HOST AS
    h ON(hsc.host_id = h.id)
  LEFT JOIN
    host_template AS ht ON(h.host_template_id = ht.id)
  WHERE
    snmp_query_id = 11 AND(`h`.`description` LIKE '%LAB%' AND `h`.`status` IS NOT NULL)
  GROUP BY
    host_id,
    snmp_query_id,
    snmp_index
  ORDER BY
    automation_host,
    CAST(snmp_index AS UNSIGNED)
) AS a
WHERE
  (AND a.`ifDescr` LIKE '%ETHERNET%')

```

**Comment by Kallyx** [comment]
Thanks! attached also the err screenshot.
![errors](https://user-images.githubusercontent.com/27009071/34300179-99e0b8cc-e72f-11e7-9df7-0e8c1b48befa.jpg)

**Comment by netniV** [comment]
The problem here is that your filter rules are only include the field "ifType" though it's actually renaming it to ifDescr in the SQL above.  It is missing all other fields before it.

[Line 1603 of api_automation](https://github.com/Cacti/cacti/blob/develop/lib/api_automation.php#L1603) is what is doing the work of creating the filter.  I am now curious what is being passed into the $automation_rule_items and whether it has all the right details.

I will see if I can replicate this with my own system but I don't tend to automatically create graphs.

**Comment by netniV** [comment]
In fact, I can see the issue now.  Your very first field under the Graph Creation Criteria has "AND" against it rather than "" (Blank)

Please change that and see if it works

**Comment by Kallyx** [comment]
Wow. Brilliant :)
Thank a lot and Happy Holidays to you all guys! See you next year! :)
Cheers!

**Comment by cigamit** [comment]
Closing since this is a usage issue and not really a bug.  However, maybe the first item should never include and AND or an OR.  Maybe we can look at that as a bug.
