### ISSUE TITLE
[1.1.29] auto crawler returns errors

### ISSUE THREAD

**Issue by paulgevers** [Cacti/cacti#1157]
As you know by now, I run a recursive wget on the Debian package of Cacti as part of continuous integration. With my upload of Cacti 1.1.29, I get the following new output in the cacti.log file:
```
12/28/2017 02:11:27 - IMPORT NOTE: File is Signed Correctly
12/28/2017 02:11:27 - IMPORT parse_xml_hash ERROR wrong hash format for hash: name
12/28/2017 02:11:28 - IMPORT NOTE: File is Signed Correctly
12/28/2017 02:11:28 - IMPORT parse_xml_hash ERROR wrong hash format for hash: name
12/28/2017 02:11:29 - IMPORT NOTE: File is Signed Correctly
12/28/2017 02:11:29 - IMPORT parse_xml_hash ERROR wrong hash format for hash: name
12/28/2017 02:11:29 - IMPORT parse_xml_hash ERROR wrong hash format for hash: name
12/28/2017 02:11:29 - IMPORT parse_xml_hash ERROR wrong hash format for hash: name
12/28/2017 02:11:29 - IMPORT parse_xml_hash ERROR wrong hash format for hash: name
12/28/2017 02:11:29 - IMPORT parse_xml_hash ERROR wrong hash format for hash: name
12/28/2017 02:11:31 - IMPORT NOTE: File is Signed Correctly
12/28/2017 02:11:31 - IMPORT parse_xml_hash ERROR wrong hash format for hash: name
12/28/2017 02:11:36 - DBCALL ERROR: SQL Assoc Failed!, Error:1064, SQL:'(SELECT gti.id, CONCAT('Branch: ', gti.title) AS name   FROM graph_tree AS gt   INNER JOIN graph_tree_items AS gti   ON gti.graph_tree_id = gt.id   AND gti.host_id = 0   AND gti.local_graph_id=0   LEFT JOIN user_auth_perms AS uap0    ON (gt.id=uap0.item_id AND uap0.type=2 AND uap0.user_id=1)    WHERE gt.enabled="on" AND ( uap0.user_id IS NULL))   UNION   (SELECT gti.id, CONCAT('Device: ', h.description) AS name   FROM graph_tree AS gt   INNER JOIN graph_tree_items AS gti   ON gti.graph_tree_id = gt.id   INNER JOIN host AS h   ON h.id=gti.host_id   AND h.id IN()   LEFT JOIN user_auth_perms AS uap0    ON (gt.id=uap0.item_id AND uap0.type=2 AND uap0.user_id=1)    WHERE gt.enabled="on" AND ( uap0.user_id IS NULL))   ORDER BY name   '
12/28/2017 02:11:36 - DBCALL ERROR: SQL Assoc Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')   LEFT JOIN user_auth_perms AS uap0    ON (gt.id=uap0.item_id AND uap0.type=2 ' at line 1
12/28/2017 02:11:36 - CMDPHP SQL Backtrace: (/reports_admin.php: 28 include_once)(/lib/html_reports.php: 319 get_allowed_branches)(/lib/auth.php: 1454 db_fetch_assoc)(/lib/database.php: 360 db_fetch_assoc_prepared)(/lib/database.php: 401 cacti_debug_backtrace)
12/28/2017 02:11:36 - CMDPHP SQL Backtrace: (/reports_admin.php: 28 include_once)(/lib/html_reports.php: 319 get_allowed_branches)(/lib/auth.php: 1455 db_fetch_cell)(/lib/database.php: 233 db_fetch_cell_prepared)(/lib/database.php: 280 cacti_debug_backtrace)
12/28/2017 02:11:38 - DBCALL ERROR: SQL Assoc Failed!, Error:1064, SQL:'(SELECT gti.id, CONCAT('Branch: ', gti.title) AS name   FROM graph_tree AS gt   INNER JOIN graph_tree_items AS gti   ON gti.graph_tree_id = gt.id   AND gti.host_id = 0   AND gti.local_graph_id=0   LEFT JOIN user_auth_perms AS uap0    ON (gt.id=uap0.item_id AND uap0.type=2 AND uap0.user_id=1)    WHERE gt.enabled="on" AND ( uap0.user_id IS NULL))   UNION   (SELECT gti.id, CONCAT('Device: ', h.description) AS name   FROM graph_tree AS gt   INNER JOIN graph_tree_items AS gti   ON gti.graph_tree_id = gt.id   INNER JOIN host AS h   ON h.id=gti.host_id   AND h.id IN()   LEFT JOIN user_auth_perms AS uap0    ON (gt.id=uap0.item_id AND uap0.type=2 AND uap0.user_id=1)    WHERE gt.enabled="on" AND ( uap0.user_id IS NULL))   ORDER BY name   '
12/28/2017 02:11:38 - DBCALL ERROR: SQL Assoc Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')   LEFT JOIN user_auth_perms AS uap0    ON (gt.id=uap0.item_id AND uap0.type=2 ' at line 1
12/28/2017 02:11:38 - CMDPHP SQL Backtrace: (/reports_admin.php: 28 include_once)(/lib/html_reports.php: 319 get_allowed_branches)(/lib/auth.php: 1454 db_fetch_assoc)(/lib/database.php: 360 db_fetch_assoc_prepared)(/lib/database.php: 401 cacti_debug_backtrace)
12/28/2017 02:11:38 - CMDPHP SQL Backtrace: (/reports_admin.php: 28 include_once)(/lib/html_reports.php: 319 get_allowed_branches)(/lib/auth.php: 1455 db_fetch_cell)(/lib/database.php: 233 db_fetch_cell_prepared)(/lib/database.php: 280 cacti_debug_backtrace)
```
All output can be found [here](https://ci.debian.net/data/autopkgtest/unstable/amd64/c/cacti/20171228_020327/log.gz).

I guess I'll have to white-list "IMPORT NOTE: File is Signed Correctly", but the others look like real issues.

**Comment by netniV** [comment]
The get_allowed_branches() I think is the new function that I introduced as part of PR #1117. I'll take another look to see why it would fail with this error.

**Comment by netniV** [comment]
OK, I see the problem, for some reason a host_id was not passed to the function.  As such, the second part of the union has `AND h.id in ()`.  I'll take a further look at this tomorrow to see why that would be.

**Comment by netniV** [comment]
I've found a problem with the COUNT() of the SQL query which I've created a fix for, and I'm just checking through the SQL that your installation has generated to see if I can see how that occurred.  I don't suppose you have the full WGET that was used to generate the error?

**Comment by netniV** [comment]
Can you try that fix? I think this should resolve all the issues now.

**Comment by netniV** [comment]
I just installed a clean 1.1.29 test system, found that those import errors appear as a result of the installation, I think so will create a separate issue on that one.

**Comment by paulgevers** [comment]
I am going to check your fix.

You can find the script responsible for the test here: https://anonscm.debian.org/cgit/pkg-cacti/cacti.git/tree/debian/tests/check-all-pages.

**Comment by cigamit** [comment]
I've fixed the first half of this with the permissions api.  Looking at the second now.

**Comment by cigamit** [comment]
Likely we need to add those hashes to the hashes array since they were initially created with a early hash.  More details to follow.

**Comment by netniV** [comment]
@cigamit If you check out my commit above, there is more that needs to be changed.  You did add the same bit (moving the device list) I did though so glad I saw that ;-)

I was waiting to create a pull request until I was sure it was right.

**Comment by cigamit** [comment]
Feel free to do a pull request.  I have to head out on the road in a bit and won't have time again until late afternoon.  I'll pick up where you left off.  The hash error seems quite odd, so I'm doing more testing, and fixing up a few things I found upgrading a live system.

**Comment by cigamit** [comment]
This issue is resolved now.  The XML parse issues are now resolved.

**Comment by netniV** [comment]
One question I have from reviewing the code again, does it need the array_rekey, etc after the get_allowed_devices?  Could that code be reduced?

**Comment by cigamit** [comment]
Well, I've noticed slow performance with almost 1000 devices in this function, especially if you have access to 'all' devices.  We need to maybe look at the inverse, what devices am I 'not' allowed to access to increase the performance of the get_allowed_branches().

We really need some trace logic to get timing when we get over 500k graphs and 30k devices which you see in a lot of enterprise deployments.

**Comment by netniV** [comment]
Whilst I have a few (~130), I definitely don't have that many so tricky for me to judge.  However, I can see how the "IN" made up from the get_allowed_devices could slow down the query.  Other than look at what is not allowed, would be to include the logic of get_allowed_devices into the SQL statement directly so we aren't pulling that data back only referencing the allowed devices.

I think with that many devices, you could end up with the same issue if you are allowing users/customers access to one small subset of devices which are their own and you are managing a lot of other devices.

From any SQL view point, it's always quicker performing a match than a non-match.

**Comment by paulgevers** [comment]
I confirm that the issue is fixed. I now only get items that I'll have to add to my whitelist:
```
01/07/2018 06:11:32 - IMPORT NOTE: File is Signed Correctly
01/07/2018 06:11:32 - IMPORT Importing XML Data for Local_Linux_Machine.xml
01/07/2018 06:11:32 - IMPORT NOTE: File is Signed Correctly
01/07/2018 06:11:32 - IMPORT Importing XML Data for Generic_SNMP_Device.xml
01/07/2018 06:11:34 - IMPORT NOTE: File is Signed Correctly
01/07/2018 06:11:34 - IMPORT Importing XML Data for NetSNMP_Device.xml
01/07/2018 06:11:36 - IMPORT NOTE: File is Signed Correctly
01/07/2018 06:11:36 - IMPORT Importing XML Data for Cisco_Router.xml
```

**Comment by netniV** [comment]
Thanks @paulgevers good to hear!
