### ISSUE TITLE
CLOG does not show values from log files

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1158]
When using the CLOG to view the log file, it parses off the values.  

This comes from the forum post:
https://forums.cacti.net/viewtopic.php?f=14&t=58228&p=270253#p270253

The reason the value never appears is because of the DS conversion to links at lines 282-322.  If you don't have a datasource, just a device in the line, everything else is copied (see line 325).

That raises a couple of questions
* Is that by design? 
* Should the value be shown by default?
* Should an option to include the value be added?

From my own thoughts, I think the answers should be to hide the value by default, but give an option to display it if necessary so that you don't have to go back to the log files at command line level.

**Comment by cigamit** [comment]
The core of this function is to replace DS[...], with the data source names and graphs, and Device[...] with with additional detail.  Both would point to a link to provide more detailed information from the log (href's basically) to speed debugging (only if authorized).  It's a messy function that for someone who knows regex's well could write it more elegantly.

**Comment by netniV** [comment]
So I should create a PR to include the extra detail and if possible, fix up the messy code?

**Comment by cigamit** [comment]
Yup, go for it.

**Comment by netniV** [comment]
As the PR is now merged this issue can be closed
