### ISSUE TITLE
Filtering string appears after delete

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#116]
Problem scenario:
- write string into search bar
- delete it using CTRL+A and Hit Enter

Result: This searched string appears again

**Comment by cigamit** [comment]
Which page?

**Comment by interduo** [comment]
hosts.php all of the pages whitch consists a filterbar status

**Comment by cigamit** [comment]
I can not reproduce on host.php

**Comment by interduo** [comment]
I am using Firefox / Linux / Debian.

**Comment by interduo** [comment]
Detailed problem scenario:
- write string into search bar
- delete it using: CTRL+A, Backspace and Hit Enter very quickly after pushing backspace

**Comment by cigamit** [comment]
Ah, this is a known browser quirk, when you delete the last space, and then hit a backspace, it becomes a browser refresh.  Kind of sucks.  Not sure how to fix that.
