### ISSUE TITLE
user_admin.php - raise_message() errors are not displayed

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1162]
I was trying to see why a local user's password was not updating when I found a bigger issue.  When the save function is called, any raise_message() functions do not appear to be displayed to the end user.  As such, it would appear everything was successful, when in fact nothing happened!

This could be an issue with more than just user_admin.php but that is the page I was concentrating on.

**Comment by netniV** [comment]
I think this is because display_output_messages() in functions.php is not called.  I'm trying to see where the header is included and whether there is  flag being set which bypasses the display of the messages.

**Comment by netniV** [comment]
OK, I think I now understand what is happening here.  The lib/html_form.php automatically creates a javascript function form_end() which prevents the normal form submit call and makes it perform an ajax call instead.  

This call suppresses the header when it is returned via the ajax call and as such does not get shown to the end user.  A fix for this is to add the following check:

```
        case 'user_edit':
                top_header();
+               if (is_error_message() && get_nfilter_request_var('header')) {
+                       display_output_messages();
+               }
                user_edit();
                bottom_footer();
```

This causes the display of the error message:

![image](https://user-images.githubusercontent.com/9052188/34487768-a770218e-efcd-11e7-8fcc-916b1b206830.png)

**Comment by cigamit** [comment]
Merged.  Closing.
