### ISSUE TITLE
New User - Default Language

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1166]
When creating a new user, the default language appears to be Bulgarian, probably because this is the first item in the list.  Shouldn't the default language default to either the system locale (if in the list) or potentially even English?  

I might be biased, but I suspect there are not as many people who know Bulgarian.  This caught me out when I was updating a test user.

![image](https://user-images.githubusercontent.com/9052188/34515003-fecef88e-f067-11e7-9e6e-2e0ebe66beb7.png)

![image](https://user-images.githubusercontent.com/9052188/34515014-0f7f7212-f068-11e7-8bae-89208b0745e3.png)

Querying the MySQL database shows:
```
> select id,username from user_auth where username = 'lang_test' or username = 'test';
+----+-----------+
| id | username  |
+----+-----------+
|  5 | lang_test |
|  4 | test      |
+----+-----------+
2 rows in set (0.00 sec)

 select * from settings_user where useR_id in (4,5) and name = 'user_language';
+---------+---------------+-------+
| user_id | name          | value |
+---------+---------------+-------+
|       4 | user_language | en    |
+---------+---------------+-------+
```

So this would appear to be a default selection problem.

**Comment by netniV** [comment]
Changing global_settings.php for the settings_user array appears to correct this.

```
--- a/include/global_settings.php
+++ b/include/global_settings.php
@@ -1820,7 +1820,7 @@ $settings_user = array(
             'friendly_name' => __('User Language'),
             'description' => __('Defines the preferred GUI language.'),
             'method' => 'drop_array',
-            'default' => 'us',
+            'default' => 'en',
             'array' => get_installed_locales()
             ),
                'show_graph_title' => array(
```

Going to check where 'us' is used because that change could potentially break other systems.  I found the correct local by adding the following to global_languages.php:

```
--- a/include/global_languages.php
+++ b/include/global_languages.php
@@ -515,6 +515,8 @@ function get_installed_locales(){

        asort($supported_languages);

+       file_put_contents("/tmp/language.log","Locales: ".var_export($supported_languages,true));
+
        return $supported_languages;
 }
```

This returned:
```
Locales: array (
  'bg' => 'Bulgarian',
  'zh-cn' => 'Chinese (China)',
  'nl' => 'Dutch',
  'en' => 'English',
  'fr' => 'French',
  'de' => 'German',
  'ja' => 'Japanese',
  'ru' => 'Russian',
  'es' => 'Spanish',
  'sv' => 'Swedish',
```

**Comment by netniV** [comment]
From what I can see, 'us' should be used against Country, but 'en' should be used for language/locale so I will create a PR for that.  If I need to correct it further, let me know. :)

**Comment by cigamit** [comment]
Resolved.
