### ISSUE TITLE
In cacti version 1.1.23 aggregated graph 

### ISSUE THREAD

**Issue by chathurag** [Cacti/cacti#1173]
In cacti version 1.1.23 aggregated graph it is unable to get total In/Out traffic.
Highlighted option are disabled.
please check.

![screenshot_2](https://user-images.githubusercontent.com/35136010/34606511-b5e44e42-f235-11e7-871a-6090e6de7686.png)
![screenshot_3](https://user-images.githubusercontent.com/35136010/34606605-13306036-f236-11e7-8703-e6370b85d400.png)

**Comment by netniV** [comment]
I believe what you need to do is move the dynamic text from the comment to a GPRINT after the comment (include the <HR> too).

**Comment by cigamit** [comment]
This is a feature request.  The reason that it is disabled at the time was intentional.

**Comment by chathurag** [comment]
@cigamit 
Is there a way to enable that in the current version 1.1.23

**Comment by cigamit** [comment]
The only way is to create the graph one item at a time.  It works, it's jobs a lot slower than using the plugin.

**Comment by cigamit** [comment]
Closing since we have a separate issue opened for this.
