### ISSUE TITLE
Drag and drop available on /tree.php?action=edit before edit is clicked

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1174]
You have the ability to drag and drop from the two columns on the right hand side over to the left side column when you have no ability to actually add items.  These two columns should be disabled unless you are editing (ie, when the Edit Tree button has been clicked enable the columns, disable on Finish Editing)

**Comment by cigamit** [comment]
Please upload an animation.  Thanks!

**Comment by netniV** [comment]
The following animation shows what I was referring to.  In better terms, drag is allowed by drop is disabled before the Edit Tree button is used.  Dragging should really be disabled and the columns potentially a dulled colour to show that editing is not available?

![cacti-graph-drag](https://user-images.githubusercontent.com/9052188/34612260-e73c374e-f220-11e7-9d83-ffa53fed6e97.gif)

**Comment by cigamit** [comment]
Needs to be a css class.  Easy to do though.

**Comment by cigamit** [comment]
Resolved.  Used javascript.
