### ISSUE TITLE
Automatic logout inconsistent redirect

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1175]
Automatic logout due to idle timeout gives different appearances depending on where you are. The three types of display I've seen so far are:

- Some pages fully redirect to the logout page `/logout.php?action=timeout` 
- Others (especially those using AJAX) seem to present a blank main section but still have all the sidebars and top menu
- Graph_View does not logout since it uses the timeout to refresh, but if you have another page open, this causes a logout resulting in a blank page (Other pages may also be affected by that same issue).

### clog.php
![image](https://user-images.githubusercontent.com/9052188/34611529-d56fc40c-f21d-11e7-8f12-bf6d197723a8.png)

### graph_view.php
![image](https://user-images.githubusercontent.com/9052188/34611476-90c8d744-f21d-11e7-9b8b-05a928635edc.png)

### index.php
![image](https://user-images.githubusercontent.com/9052188/34611487-9cd28f26-f21d-11e7-882b-e271b9b3ebd5.png)

**Comment by cigamit** [comment]
Oh that is bad.  I myself always use "Keep me signed in" so never saw that.  Thanks for catching.

**Comment by netniV** [comment]
Actually, ignore the index.php screen shot, that comes after the /logout.php page.

**Comment by netniV** [comment]
I normally do to, but for my test systems I am not because I've been testing the refresh of the graph view filter logging in as different users.

**Comment by cigamit** [comment]
Kind of odd.  Did you experience this directly after an upgrade?  I've set the session.gc_maxlifetime real low, and I'm still not able to reproduce.  Let me try reproducing by removing the session data.  Oh, and let me know if you are writing your session data to the database, or using local files?

**Comment by netniV** [comment]
I wonder if this is a Google Chrome issue then.  I'll try with a few browsers.  My sessions table is defined as so

```> show create table sessions\G;
*************************** 1. row ***************************
       Table: sessions
Create Table: CREATE TABLE `sessions` (
  `id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `remote_addr` varchar(25) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `access` int(10) unsigned DEFAULT NULL,
  `data` mediumblob,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Used for Database based Session Storage'
1 row in set (0.02 sec)
```

**Comment by cigamit** [comment]
It might be csrf too.  The redirects on that page are not sane.  I've made a change.  Will test over the weekend.  Keep testing.

**Comment by netniV** [comment]
Oh, and my cacti_db_session is set to false in includes/config.php

**Comment by cigamit** [comment]
The only part that I was unable to do real well is when you open a branch for the first time, you can see the tree change just before you get re-directed to the login page.  There is a way to resolve using jstree's 'check_callback' functionality, but I had no time for it.

**Comment by cigamit** [comment]
I'm going to close this for now.  Let's hope we went far enough.
