### ISSUE TITLE
Changing system language should refresh entire page

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1176]
If you change the system language within Settings -> General -> Language the system applies the new language via AJAX when saved but the menu / sidebar are still showing the original language.  Additionally the language drop down is showing all Languages in English rather than the i18n version.

![image](https://user-images.githubusercontent.com/9052188/34614584-dc3918fe-f229-11e7-85b6-a7bff746a9dd.png)

![image](https://user-images.githubusercontent.com/9052188/34614639-08290956-f22a-11e7-895e-1bdabca26f36.png)

![image](https://user-images.githubusercontent.com/9052188/34614603-ee37c712-f229-11e7-9be2-dee3afe188ec.png)

**Comment by netniV** [comment]
Closed without comment ? ;-)

**Comment by cigamit** [comment]
Just a little grumpy.  The cacti_version_compare() thing is upsetting.  I think it'll be good moving forward though.

**Comment by netniV** [comment]
This one isn't a version_compare issue though, is it?
