### ISSUE TITLE
Warn during installation if installing moving to older version

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1179]
At the moment, the upgrade system merely shows what version you are on and what version you are going to.  If you start to use an older source, the system should show you a large warning because no database changes will occur post confirmation and the older source may not be compatible with the database.

It may even be worth having a checkbox that confirms the user really wants that to occur.

I noticed this because I switched to a branch that is currently on the 1.1.29 source, not the 1.1.30 which the database had already been marked at.

![screen shot 2018-01-06 at 12 31 25](https://user-images.githubusercontent.com/9052188/34639751-b414e362-f2dd-11e7-8700-4f58c628b619.png)

**Comment by netniV** [comment]
![screen shot 2018-01-06 at 12 31 25](https://user-images.githubusercontent.com/9052188/34639751-b414e362-f2dd-11e7-8700-4f58c628b619.png)

**Comment by cigamit** [comment]
Oh, that is odd ;)  Roman needs to review this one.

**Comment by ronytomen** [comment]
Indeed odd.....

**Comment by ronytomen** [comment]
Fixed in develop branch, do you care to test?  I hope I got the logic right.. :)

**Comment by ronytomen** [comment]
Commit: bfee1c86d256a0eee2e0abfe7df01289e4fe8b58

**Comment by netniV** [comment]
Coding looks good on my mobile but I’ll test when I’m home.

**Comment by netniV** [comment]
Yeah seems to work.  Updated my verison able to 1.1.31 and then ran the code, it showed me the correct message.  However, maybe we should also change the button to read 'DOWNGRADE' in big letters for those who don't bother reading the message as that still says 'Upgrade'?  ;-)
