### ISSUE TITLE
spine configure error

### ISSUE THREAD

**Issue by stalker37** [Cacti/cacti#1180]
debian 9 (stretch)

configure:13199: checking if Net-SNMP needs crypto support
configure:13212: gcc -c -I/usr/include/mysql -g -O2  conftest.c >&5
conftest.c:56:29: fatal error: net-snmp-config.h: No such file or directory
 #include <net-snmp-config.h>
                             ^
compilation terminated.
configure:13212: $? = 1

dpkg -L  libsnmp-dev | grep net-snmp-config.h
/usr/include/net-snmp/net-snmp-config.h

**Comment by cigamit** [comment]
Belongs in spine github.  Please test with the current develop branch.  Open issue there if the problem remains.

**Comment by stalker37** [comment]
On fresh git clone
./configure --with-mysql --with-snmp

checking whether we are using Linux Capabilities... no
configure: error: Cannot find SNMP header files under yes

**Comment by stalker37** [comment]
| #define HAVE_STRTOLL 1
| /* end confdefs.h.  */
| #include <sys/capability.h>
configure:13072: result: no
configure:13072: checking for sys/capability.h
configure:13072: result: no
configure:13082: checking whether we are using Linux Capabilities
configure:13151: result: no
configure:13270: error: Cannot find SNMP header files under yes

**Comment by netniV** [comment]
Hi @stalker37 , can you close this issue and repost in https://github.com/cacti/spine as any work would be done over there?  Be sure to include your last two posts of information too.
