### ISSUE TITLE
Scheduler drop downs off screen when near bottom of window

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1181]
If you click on the scheduler drop downs, these are showing off screen when they are near the bottom of the window.  Additionally, scrolling a page does not move these boxes so whether in the middle of the window or at the bottom, they stay fixed resulting in being out of place

### Off screen
![screen shot 2018-01-06 at 14 10 13](https://user-images.githubusercontent.com/9052188/34640488-82d80bea-f2eb-11e7-9c01-3745b2b35610.png)
![screen shot 2018-01-06 at 14 09 27](https://user-images.githubusercontent.com/9052188/34640489-859f9a6e-f2eb-11e7-9602-0576b61c25ea.png)

### Off screen after scrolling
![screen shot 2018-01-06 at 14 13 04](https://user-images.githubusercontent.com/9052188/34640501-c4a7063e-f2eb-11e7-91d9-de6652e6fd7d.png)

### Center of screen after scrolling
![screen shot 2018-01-06 at 14 12 06](https://user-images.githubusercontent.com/9052188/34640494-9e9aefa0-f2eb-11e7-8ad2-5df91a2e55c5.png)

**Comment by cigamit** [comment]
This one will be a little tricky.  We need to upstream our changes to the jquery multiselect to Eric Hynds GitHub and then work on the flip and follow calculations with that team.

**Comment by netniV** [comment]
I've seen him mentioned a couple of times but being new to the scene, not followed who he is so far :)

**Comment by netniV** [comment]
Just to confirm, this still exists in 1.2.2+

**Comment by cigamit** [comment]
There has been a number of changes in the jQuery-Multiselect widget lately.  We need to merge our changes into it.  Likely this is fixed now.  They are working on a 3.0 release.

**Comment by cigamit** [comment]
This issue is resolved with the latest jQueryMultiSelect.
