### ISSUE TITLE
Theme selection when missing a theme

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1183]
If a theme is removed from the system, the resulting display is a jumbled mess.  The system should attempt to revert back to the default theme of Modern or Classic (assuming the predefined default theme isn't the one removed).

This can occur if a user has a theme set and removes or renames the theme folder.  I think we should follow the same logic we would for language selection, ie, if a user has a theme that is not present, try the system configured theme, if a system theme is not present default to a predefined theme.  If that's not present... do we try the first theme we find in the folder if any?
 
![screen shot 2018-01-06 at 21 14 00](https://user-images.githubusercontent.com/9052188/34644003-93ca3460-f326-11e7-9fba-3faf0c8dc71f.png)

Just lucky here I was on the settings window so I can change the theme again :)

**Comment by cigamit** [comment]
Awesome!

**Comment by cigamit** [comment]
Resolved, thanks for reporting!
