### ISSUE TITLE
Improve Data Input Methods editability and message handling

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1184]
I updated a data input template with a new field and updated the associated php script to expect the new field.  However, the field did not come into play until I went back and saved the data source.  If there had been a lot of data sources associated with the template, this would have taken some time.

Is there an easy way to update these?  Shouldn't saving the template provide 

- a prompt that to update sources that are based upon it
- a button to update the data sources that depend on the tempalte when editing a data input
- an option to reapply the data input change from the selection/search list if a data input is selected

**Comment by cigamit** [comment]
There should be a push_out_data_input_method() function in the lib/utility.php.  Maybe it has an issue with not repopulating the poller cache for items that are impacted by the change.  It's entirely possible that was a late code change in the 0.8.8 branch.

**Comment by cigamit** [comment]
I did a cursory review of what is happening in data_templates.php and I believe that the data_templates.php save process is a bit messy to say the least.  Though it has kind of worked for a long time, there is a lot of wasted cycles spent on things that don't have to be spent on.  Plus there are some dangerous transactions.

It's all a little too much work for 1.1.36.  But it seems we can resolve this issue, and increase performance when updating Data Templates at the same time.

**Comment by netniV** [comment]
I wonder if any of our recent changes have addressed this or if it's still an ongoing issue?

**Comment by cigamit** [comment]
No changes as of now.  I'm improving the messages for the time being, and then we can open a new issue.  The problem with blindly pushing out is going to be with the law of unintended consequences.

**Comment by cigamit** [comment]
New messages and removal of editing of output fields added, so I'll close this for now.
