### ISSUE TITLE
Layout issue with Graphs having large number of data columns

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1185]
![image](https://user-images.githubusercontent.com/9052188/34672594-f408f734-f476-11e7-904d-8f579d57ef96.png)

The above is a screenshot taken by a user over on the [forums](https://forums.cacti.net/viewtopic.php?f=12&t=10049&p=270435#p270435).  It would seem if a datasource has a large number of fields, it pushes the graph off the screen.

**Comment by ITATG** [comment]
Hello, I'm the user that posted that.  I have a solution for that: add an "overflow-x:scroll" to the BODY tag, attribute STYLE of graph.php
It's not the best but seems to work

**Comment by cigamit** [comment]
That's a lot of columns.  I'll have to think about this one.  Likely have to give the table some overflow:scroll and allow it to float on the page.

**Comment by cigamit** [comment]
Should be better now.  Please test and comment.

**Comment by ITATG** [comment]
Hello,
I've added the updated version of graph.php and graph_xport.php but nothing changed, the graph is still pushed off the screen.

Thank you

**Comment by pautiina** [comment]
Confirm. Not resolved.

**Comment by cigamit** [comment]
Yea, not working on my machine this morning either.  I must have broken something when removing debug code.  Back at it.  Honestly it was working last night.

**Comment by cigamit** [comment]
Okay, all better now.  Please confirm.

**Comment by pautiina** [comment]
Niw I have scrolling and look good.

**Comment by cigamit** [comment]
Okay, cool.  Closing then.
