### ISSUE TITLE
Allow ability to sort tree list by name asc/des

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1189]
![image](https://user-images.githubusercontent.com/9052188/34772736-0bdca5a0-f601-11e7-889a-2c910e3e08f8.png)

Taken from: https://forums.cacti.net/viewtopic.php?f=21&t=58328&p=270575#p270575

At the moment if you have a large number of trees, you have to manually click up and down to sort the order that you wish the trees to appear in.  This can be quite time consuming and mistake prone if you are also using automation or cli to create them.

Propose to add two actions to the tree list table actions to "Sort All (Ascending)" and "Sort All (Descending)"

**Comment by kpmayhue** [comment]
Hi NetniV, the actual problem is when you try to sort, it "randomly" places the tree name in different positions, meaning you cannot get this to sort alphabetically.

**Comment by netniV** [comment]
I'll look into that further,  Weirdly, I tried it on my test system and I thought I got it to fail on the first click but then it appeared to work.  Think I need to generate a bunch of empty trees and then test again.

**Comment by netniV** [comment]
It appears no graph has a sequence number so I'll create a separate issue to track that one.

**Comment by cigamit** [comment]
We have to rework the fixes.  Looks like QuickTree plugin (modified by someone) is not setting a sequence.

**Comment by netniV** [comment]
I have helped with a mod to the QuickTree plugin, I can check that out.  How do you mean rework the fixes though?

**Comment by cigamit** [comment]
Marking closed.
