### ISSUE TITLE
Tree Sequence value is not set or checked

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1191]
Because the tree.sequence is not set any use of the tree_up/tree_down functions result in erratic functionality.  Need to resequence any 0 value tree to be higher than the last existing one on save and to run the same from tree_up() and tree_down() before updating the sequence.

**Comment by netniV** [comment]
```
cacti_test> select id,name,sequence from graph_tree;
+----+------------------------------------+----------+
| id | name                               | sequence |
+----+------------------------------------+----------+
|  1 | Default Tree                       |        1 |
|  7 | saved quicktree for user 'admin' 2 |        0 |
|  8 | saved quicktree for user 'admin' 1 |        0 |
|  9 | saved quicktree for user 'admin'   |        0 |
| 10 | saved quicktree for user 'admin' 4 |        0 |
| 11 | saved quicktree for user 'admin' 6 |        0 |
| 12 | saved quicktree for user 'admin' a |        0 |
+----+------------------------------------+----------+
7 rows in set (0.03 sec)
```

**Comment by cigamit** [comment]
Looks like this might just be a plugin issue.  We should consider merging that plugin at some point.

**Comment by netniV** [comment]
That would be Mr. Jones' baby as I modified it to work under 1.x.  I didn't recall touching anything to do with sequences though (maybe that's the problem).

However, it's an overall problem because any plugin could produce the same result.

**Comment by netniV** [comment]
Because there isn't an API way of adding a tree, there is a reliance on third party code to correctly apply a sequence.  If there was an API way, this would prevent the issue (at least for people doing it the correct way).

At the moment, the only way to fix the issues seen by the user is to user the methods I've created.  Either way, the tree_up()/tree_down() functions make no check for duplicate sequences in use.  The other alternative is to make the sequence a unique DB field, thus any plugin creating a zero sequence tree can only do so once?

**Comment by cigamit** [comment]
Most of the code was good, just the method to 'sort' was not following a standard.  I gave it some thought last night while laying on my pillow, and the filter/table design is lacking some functionality.  I'm thinking that adding the buttons to the filter table header is the way to go.  Will give it some thought later today.  I'm up against a day job deadline though.  I'm suspecting passing an array to the html_start_box() is the way to go.  So, if the 'add' is a string, use legacy behavior.  If the add is an array with the following structure, you know what to do:

`$add[] = array('class' => 'fa fathis', 'href' => 'something', 'callback' => true|false, 'title' => __('Some title'));`

Make sense?

![newbuttonsonfiltertable](https://user-images.githubusercontent.com/957322/34877764-01a5f16e-f76d-11e7-9229-60c528e76501.png)

**Comment by netniV** [comment]
Yeah, I think that's a good idea because I was just looking at the quicktree plugin to do the same thing for that where I wanted my own custom buttons.  Maybe an array such as:

```
{
    showDefaultButtons: <true/false>,
    items: {
        { title: <title>, label: <text>, class: <class>, icon: <icon>, href: <link> }
        { title: <title>, label: <text>, class: <class>, icon: <icon>, href: <link> }
        { title: <title>, label: <text>, class: <class>, icon: <icon>, href: <link> }
    }
}
```

That will need some corresponding jQuery code to correctly identify if the icon or class was populated to use them, etc.  Would take me a while to do as I'm still getting my heard around jQuery lol.

**Comment by netniV** [comment]
Still think the add_tree should become an API function (lib/api_tree.php) rather than in the /tree.php

**Comment by cigamit** [comment]
Agree on the API point.  Feel free to do a pull on that one.  jQuery is awesome, you have already made a pretty good start.  We can drop the 'icon' and 'label' attributes as we will only permit the glyphs. Though it does press the point that part of the API is meant to replace the buttons on the filter.  Never the less, this is good collaboration.

On Howies design, it appears that he is moving more GUI components to Javascript, which is consistent if he were to adopt something like a react framework in the future.

**Comment by netniV** [comment]
Well, I've just created an update to QuickTree to properly utilise the themes on the latest update I just did for my version of QuickTree.  Since I couldn't utilise the additional buttons, I created a drop actions part.  The only difference to the normal base style is that this appears above all the graphs on its own if the user collapses the info part.

**Comment by netniV** [comment]
This appears to work now.  However, it reminded me of an issue with the buttons... the layout can be a little tricky to hit the right part and sometimes when I got to add a device I end up collapsing the filter instead.

![image](https://user-images.githubusercontent.com/9052188/34941858-770f8fd2-f9ed-11e7-90f9-7e9817f00209.png)

**Comment by cigamit** [comment]
Yea, we may simply have to increase the size of the objects bounding box and make it a block element to provide more click area.  Also, it appears to be hiding too much, which is a bug.

**Comment by cigamit** [comment]
I've coded a small solution, I will commit to the dark theme momentarily.  Test it out.

**Comment by netniV** [comment]
So I've highlight the span that goes around each <A> element:
![image](https://user-images.githubusercontent.com/9052188/34943349-3db395de-f9f3-11e7-9e29-604e07174367.png)

The blue is the span, the yellow is the clickable area.  This has made it better, though there is still a large area between the buttons which can be clicked to collapse the header since the span will revert the click back up to the cactiTableButton which in turn reverts to cactiTableTitle.

Maybe a span around all the buttons themselves, which prevents the click bubbling?  There is still a filter and collapse button (additionally I don't think it need both?)

**Comment by cigamit** [comment]
The anchors are attached to the spans.  So, we should be good.  The note on the filter, was put there for mobile browsers.  I was just lazy and left it there for everyone else.  I guess it could be removed.  You have today to get any pull requests in, unless you find some big issues today.

**Comment by cigamit** [comment]
I see, the behavior is different between firefox and chrome.  Awesome!

**Comment by cigamit** [comment]
Okay, I think it's right now.

**Comment by netniV** [comment]
![double_tooltip](https://user-images.githubusercontent.com/9052188/34947444-088a71d4-fa02-11e7-8c9d-88602ab7c23d.gif)

So, this is the last issue that I can see with the layout changes, but it's a minor visual one so shouldn't have an impact on functionality.  It did lead me to try out the buttons and I suddenly realised, if a user **_had_** spent ages sorting my layout, we haven't put a confirmation box in to make sure the user want to do it?

**Comment by cigamit** [comment]
On the confirmation side, if you would like to put something together, that would be great.  You could add the dialog right in the tree.php code.  So, basically, make the href='#' then assign an 'click' event to the class (or better yet 'id').  I guess we need to add the id to the html_start_box() $add array ('id' => 'myid') to make things easier and more consistent.  

Thought that show/hide issue was resolved.  Lovely.

**Comment by cigamit** [comment]
I've added the id attribute to the function.

**Comment by cigamit** [comment]
I'm unable to reproduce the hover behavior you know.  Try reloading your CSS and JS>

**Comment by netniV** [comment]
Can't get it to do it every movement, but if you do it just right, it still occurs ;-)

**Comment by cigamit** [comment]
Yea, once I start, I'm like a train.  It takes a while to slow down.

**Comment by cigamit** [comment]
I found that if you add more padding to the anchor you can completely remove the possibility of a false hover.  One thing at a time though.

**Comment by cigamit** [comment]
I will open a new bug relative to the confirmation.  In the mean time I added Drag and Drop to the Tree to make things easy.
