### ISSUE TITLE
CPU Total - Does not appear to be working

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1193]
![image](https://user-images.githubusercontent.com/9052188/34828099-5078a08c-f6d4-11e7-87b8-9f414221eca3.png)

I got a THOLD email notifying me of high CPU usage today, so I decided to actually go look and see what the graphs showed.  For some reason, I have a deviation line which appears to be above the graph data, but what I noticed more was that the CPU Total graph appears broken.

Looking at the data and I saw:
![image](https://user-images.githubusercontent.com/9052188/34828200-b109cafc-f6d4-11e7-9067-03778bcf3af5.png)

This suggests that it isn't being populated properly.  The Graph shows that it's datasource is the db1 CPUTotal.  The datasource says it's getting Total from Host MIB - CPU Utilization. 

So I went to look at Data Query Cache and this has the following (Device, Query Name, Index, Field Name, Field Value)
![image](https://user-images.githubusercontent.com/9052188/34828464-8d058bd6-f6d5-11e7-960d-767d5fec1f9a.png)

Now here's the strange part.  I figured that since there were so many missing values for Total but all the others seemed to have a value, then there must be an issue with the script. So I ran the following:

```
for i in {0,1,2,3,4000}; do php /usr/share/cacti/site/scripts/ss_host_cpu.php '<ip>' '131' '2:161:3000:5:10:public::::::' 'get' 'usage' $i; echo;done;
3
61
38
7
27
Which were the values I would expect.  'query' 'index' and 'index' both correctly return the indexes, so I'm now stumped as what might be causing this.

**Comment by cigamit** [comment]
What does the poller cache look like for this entry?

**Comment by netniV** [comment]
![image](https://user-images.githubusercontent.com/9052188/34866891-0d41424a-f776-11e7-9fa6-4b2ce8cda19c.png)

Seems fine to me.  That's where I took the command line from.

**Comment by netniV** [comment]
The blank spots are just the IP/Serial numbers.

**Comment by cigamit** [comment]
Looks good to me.  I guess I'm baffled.  You can run the script server test and then just paste that line into the script server:

`php -q script_server.php`
`Script Server has started ...`
`/path_to_file/something.php some_function_name arg1 arg2 arg3 ...`
`some_output_value`
`quit`

That's it.

**Comment by netniV** [comment]
I'll take a look next week then.

**Comment by netniV** [comment]
It returned the value that I expected.

**Comment by netniV** [comment]
So I dumped out the RRD data to xml, then wrote a quick PHP script to read down that XML and compare the results.  This is a snapshot of one of them:
```
x R18/20 - D01/01 - R0001/0700 : 0 [  43.60000000000000142109] 2 [  49.79999999999999715783] Total [                      NaN]
                                 1 [  54.39999999999999857891] 3 [  80.33333333299999878818]  Calc [  57.03333333324999898650]
                                 0 [      2018-01-04 06:00:00] 2 [      2018-01-04 06:00:00]
                                 1 [      2018-01-04 06:00:00] 1 [      2018-01-04 06:00:00]
x R18/20 - D01/01 - R0002/0700 : 0 [   3.04999999999999982236] 2 [   7.15000000000000035527] Total [                      NaN]
                                 1 [  43.10000000000000142109] 3 [  55.95000000000000284217]  Calc [  27.31250000000000000000]
                                 0 [      2018-01-04 06:30:00] 2 [      2018-01-04 06:30:00]
                                 1 [      2018-01-04 06:30:00] 1 [      2018-01-04 06:30:00]
x R18/20 - D01/01 - R0003/0700 : 0 [   4.00000000000000000000] 2 [   2.39999999999999991118] Total [                      NaN]
                                 1 [  11.73333333299999914345] 3 [  84.86666666700000405399]  Calc [  25.75000000000000000000]
                                 0 [      2018-01-04 07:00:00] 2 [      2018-01-04 07:00:00]
                                 1 [      2018-01-04 07:00:00] 1 [      2018-01-04 07:00:00]
x R18/20 - D01/01 - R0004/0700 : 0 [   4.90000000000000035527] 2 [   6.79999999999999982236] Total [                      NaN]
                                 1 [   5.75000000000000000000] 3 [  92.20000000000000284217]  Calc [  27.41250000000000142109]
                                 0 [      2018-01-04 07:30:00] 2 [      2018-01-04 07:30:00]
                                 1 [      2018-01-04 07:30:00] 1 [      2018-01-04 07:30:00]
x R18/20 - D01/01 - R0005/0700 : 0 [   5.95000000000000017764] 2 [   7.70000000000000017764] Total [  28.00000000000000000000]
                                 1 [  66.84999999999999431566] 3 [  29.39999999999999857891]  Calc [  27.47500000000000142109]
                                 0 [      2018-01-04 08:00:00] 2 [      2018-01-04 08:00:00]
                                 1 [      2018-01-04 08:00:00] 1 [      2018-01-04 08:00:00]
x R18/20 - D01/01 - R0006/0700 : 0 [   9.09999999999999964473] 2 [  16.94999999999999928946] Total [                      NaN]
                                 1 [  30.19999999999999928946] 3 [  67.34999999999999431566]  Calc [  30.89999999999999857891]
                                 0 [      2018-01-04 08:30:00] 2 [      2018-01-04 08:30:00]
                                 1 [      2018-01-04 08:30:00] 1 [      2018-01-04 08:30:00]
x R18/20 - D01/01 - R0007/0700 : 0 [   4.40000000000000035527] 2 [  21.85000000000000142109] Total [                      NaN]
                                 1 [  36.50000000000000000000] 3 [  72.75000000000000000000]  Calc [  33.87500000000000000000]
                                 0 [      2018-01-04 09:00:00] 2 [      2018-01-04 09:00:00]
                                 1 [      2018-01-04 09:00:00] 1 [      2018-01-04 09:00:00]
x R18/20 - D01/01 - R0008/0700 : 0 [   7.00000000000000000000] 2 [  22.19999999999999928946] Total [                      NaN]
                                 1 [  13.00000000000000000000] 3 [  91.04999999999999715783]  Calc [  33.31250000000000000000]
                                 0 [      2018-01-04 09:30:00] 2 [      2018-01-04 09:30:00]
                                 1 [      2018-01-04 09:30:00] 1 [      2018-01-04 09:30:00]
x R18/20 - D01/01 - R0009/0700 : 0 [   3.10000000000000008882] 2 [   3.50000000000000000000] Total [                      NaN]
                                 1 [   3.10000000000000008882] 3 [  92.15000000000000568434]  Calc [  25.46250000000000213163]
                                 0 [      2018-01-04 10:00:00] 2 [      2018-01-04 10:00:00]
                                 1 [      2018-01-04 10:00:00] 1 [      2018-01-04 10:00:00]
x R18/20 - D01/01 - R0010/0700 : 0 [   2.04999999999999982236] 2 [  19.60000000000000142109] Total [                      NaN]
                                 1 [  90.59999999999999431566] 3 [  13.40000000000000035527]  Calc [  31.41250000000000142109]
                                 0 [      2018-01-04 10:30:00] 2 [      2018-01-04 10:30:00]
                                 1 [      2018-01-04 10:30:00] 1 [      2018-01-04 10:30:00]
x R18/20 - D01/01 - R0011/0700 : 0 [   5.95000000000000017764] 2 [   8.09999999999999964473] Total [                      NaN]
                                 1 [  13.75000000000000000000] 3 [  45.25000000000000000000]  Calc [  18.26249999999999928946]
                                 0 [      2018-01-04 11:00:00] 2 [      2018-01-04 11:00:00]
                                 1 [      2018-01-04 11:00:00] 1 [      2018-01-04 11:00:00]
x R18/20 - D01/01 - R0012/0700 : 0 [   0.94999999999999995559] 2 [   2.10000000000000008882] Total [                      NaN]
                                 1 [   4.75000000000000000000] 3 [   0.20000000000000001110]  Calc [   2.00000000000000000000]
                                 0 [      2018-01-04 11:30:00] 2 [      2018-01-04 11:30:00]
                                 1 [      2018-01-04 11:30:00] 1 [      2018-01-04 11:30:00]
x R18/20 - D01/01 - R0013/0700 : 0 [   2.04999999999999982236] 2 [   4.45000000000000017764] Total [                      NaN]
                                 1 [   3.25000000000000000000] 3 [   7.29999999999999982236]  Calc [   4.26250000000000017764]
                                 0 [      2018-01-04 12:00:00] 2 [      2018-01-04 12:00:00]
                                 1 [      2018-01-04 12:00:00] 1 [      2018-01-04 12:00:00]
x R18/20 - D01/01 - R0014/0700 : 0 [   3.00000000000000000000] 2 [   2.14999999999999991118] Total [                      NaN]
                                 1 [   2.29999999999999982236] 3 [  14.94999999999999928946]  Calc [   5.59999999999999964473]
                                 0 [      2018-01-04 12:30:00] 2 [      2018-01-04 12:30:00]
                                 1 [      2018-01-04 12:30:00] 1 [      2018-01-04 12:30:00]
x R18/20 - D01/01 - R0015/0700 : 0 [   1.00000000000000000000] 2 [   6.04999999999999982236] Total [   4.00000000000000000000]
                                 1 [   0.05000000000000000278] 3 [   4.04999999999999982236]  Calc [   2.78749999999999964473]
                                 0 [      2018-01-04 13:00:00] 2 [      2018-01-04 13:00:00]
                                 1 [      2018-01-04 13:00:00] 1 [      2018-01-04 13:00:00]
x R18/20 - D01/01 - R0016/0700 : 0 [   2.20000000000000017764] 2 [   2.26666666669999994355] Total [                      NaN]
                                 1 [   3.20000000000000017764] 3 [   9.00000000000000000000]  Calc [   4.16666666667499985266]
                                 0 [      2018-01-04 13:30:00] 2 [      2018-01-04 13:30:00]
                                 1 [      2018-01-04 13:30:00] 1 [      2018-01-04 13:30:00]
x R18/20 - D01/01 - R0017/0700 : 0 [   1.86666666670000003236] 2 [   2.86666666670000003236] Total [                      NaN]
                                 1 [   4.73333333330000005645] 3 [   8.53333333329999987882]  Calc [   4.50000000000000000000]
                                 0 [      2018-01-04 14:00:00] 2 [      2018-01-04 14:00:00]
                                 1 [      2018-01-04 14:00:00] 1 [      2018-01-04 14:00:00]
x R18/20 - D01/01 - R0018/0700 : 0 [   4.00000000000000000000] 2 [   3.06666666670000021000] Total [                      NaN]
                                 1 [   2.06666666670000021000] 3 [   9.19999999999999928946]  Calc [   4.58333333334999970532]
                                 0 [      2018-01-04 14:30:00] 2 [      2018-01-04 14:30:00]
                                 1 [      2018-01-04 14:30:00] 1 [      2018-01-04 14:30:00]
x R18/20 - D01/01 - R0019/0700 : 0 [   1.05000000000000004441] 2 [   5.04999999999999982236] Total [                      NaN]
                                 1 [   2.10000000000000008882] 3 [   4.00000000000000000000]  Calc [   3.04999999999999982236]
                                 0 [      2018-01-04 15:00:00] 2 [      2018-01-04 15:00:00]
                                 1 [      2018-01-04 15:00:00] 1 [      2018-01-04 15:00:00]
x R18/20 - D01/01 - R0020/0700 : 0 [   1.00000000000000000000] 2 [  13.50000000000000000000] Total [                      NaN]
                                 1 [   4.00000000000000000000] 3 [   9.15000000000000035527]  Calc [   6.91249999999999964473]
 ```

As you can see by swiping left/right on the above code output, the Total field always seems to be NaN for some reason on this particular RRA.

**Comment by netniV** [comment]
So I think I stumbled across what may be the issue with this.  If you have the Host MIB plugin installed, it would appear to interfere with the SNMP Processor Information templates.

![image](https://user-images.githubusercontent.com/9052188/35215559-88fec108-ff5c-11e7-929e-b6bb43fa9880.png)

**Comment by cigamit** [comment]
That may be the case in that the hmib plugin never comprehended this index.  Also, it indexes the CPU's in the database based upon their real index.  Should be a pretty minor fixup though.

**Comment by netniV** [comment]
So, I've now confirmed this by copying the ss_host_cpu.php that gets installed via the SNMP templates during a standard install to my forked copy of plugin_hmib.  The problem has now gone away.  This means that the hmib plugin is overriding another template with its own details.

**Comment by cigamit** [comment]
Well, you need to merge your forked hmib since this change was addressed in the hmib plugin some time ago.  Check the history on the hmib plugin.

**Comment by cigamit** [comment]
I thought that it had not been done, but saw the changes there.

**Comment by netniV** [comment]
So I tired (and failed) to find how the template for hmib is automatically loaded into the system.  I searched the code for ".gz" and the only locations I could find where the install/functions.php.  So then I wondered if it was related to phptwig, but as far as I could tell that isn't even used at all.

Then I actually read the HMIB readme.md and noticed you manually install the template (doh!).  However, when I tried to do this on my latest dev version of cacti, I get an invalid hash notice:
```
IMPORT parse_xml_hash ERROR wrong hash format for hash: info
```
What do I do to fix this up?  Additionally, I'll be making a mod to the templates_import.php to actually show the error because currently it looks like the forms reset (which it kinda has) rather than it had a problem.  This comes down to lib/import.php raising a message but the form isn't checking for one.

**Comment by netniV** [comment]
Still so much to learn ;-)

So the above .GZ is the package version which outputs the various XML files.  Instead, I previewed the file `cacti_data_query_host_mib_-_get_processor_information.xml` and this shows that the Host MIB replaces the default SNMP templates which I think is incorrect.

### Output

<table id="templates_import1_child" class="cactiTable" style="padding:3px;"><tbody><tr class="odd"><td><p class="textArea">Cacti would make the following changes if the Template was imported:</p>
<p><strong>GPRINT Preset</strong></p>
<span class="monoSpace"><span class="success">[preview]</span> Normal <span class="deviceUp">[unchanged]</span>
</span><br>
<span class="monoSpace"><span class="success">[preview]</span> Exact Numbers <span class="deviceUp">[unchanged]</span>
</span><br>
<p><strong>Data Input Method</strong></p>
<span class="monoSpace"><span class="success">[preview]</span> Get Script Server Data (Indexed) <span class="deviceUp">[unchanged]</span>
</span><br>
<p><strong>Data Template</strong></p>
<span class="monoSpace"><span class="success">[preview]</span> Host MIB - CPU Utilization <span class="updateObject">[updated]</span>
</span><br>
<ul class="monoSpace"><li>Table: data_template_rrd, Column: rrd_maximum, New Value: '100', Old Value: '0'</li>
</ul><p><strong>Graph Template</strong></p>
<span class="monoSpace"><span class="success">[preview]</span> Host MIB - CPU Utilization <span class="updateObject">[updated]</span>
</span><br>
<ul class="monoSpace"><li>Found Orphaned Graph Items, Type: LINE1, Text Format: , Value: </li>
</ul><ul class="monoSpace"><li>Table: graph_templates_graph, Column: height, New Value: '120', Old Value: '200'</li>
<li>Table: graph_templates_graph, Column: width, New Value: '500', Old Value: '600'</li>
<li>Table: graph_templates_graph, Column: auto_scale, New Value: 'on', Old Value: ''</li>
<li>Table: graph_templates_graph, Column: upper_limit, New Value: '100', Old Value: '110'</li>
<li>Table: graph_templates_item, Column: alpha, New Value: 'FF', Old Value: '7F'</li>
<li>Table: graph_templates_item, Column: hard_return, New Value: '', Old Value: 'on'</li>
</ul><p><strong>Data Query</strong></p>
<span class="monoSpace"><span class="success">[preview]</span> Host MIB - Get Processor Information <span class="updateObject">[updated]</span>
</span><br>
<ul class="monoSpace"><li>Table: snmp_query, Column: name, New Value: 'Host MIB - Get Processor Information', Old Value: 'SNMP - Get Processor Information'</li>
<li>Table: snmp_query, Column: xml_path, New Value: '&lt;path_cacti&gt;/plugins/hmib/templates/resource/script_server/host_cpu.xml', Old Value: '&lt;path_cacti&gt;/resource/script_server/host_cpu.xml'</li>
</ul></td></tr></tbody></table>

**Comment by netniV** [comment]
The same thing also appears to be true of the other HMIB templates, this was the host_disk one:

<table id="templates_import1_child" class="cactiTable" style="padding:3px;"><tbody><tr class="odd"><td><p class="textArea">Cacti would make the following changes if the Template was imported:</p>
<p><strong>GPRINT Preset</strong></p>
<span class="monoSpace"><span class="success">[preview]</span> Normal <span class="deviceUp">[unchanged]</span>
</span><br>
<p><strong>Data Input Method</strong></p>
<span class="monoSpace"><span class="success">[preview]</span> Get Script Server Data (Indexed) <span class="deviceUp">[unchanged]</span>
</span><br>
<p><strong>Data Template</strong></p>
<span class="monoSpace"><span class="success">[preview]</span> Host MIB - Hard Drive Space <span class="deviceUp">[unchanged]</span>
</span><br>
<p><strong>Graph Template</strong></p>
<span class="monoSpace"><span class="success">[preview]</span> Host MIB - Available Disk Space <span class="updateObject">[updated]</span>
</span><br>
<ul class="monoSpace"><li>Found Orphaned Graph Items, Type: LINE1, Text Format: , Value: </li>
<li>Found Orphaned Graph Items, Type: LINE1, Text Format: , Value: </li>
</ul><ul class="monoSpace"><li>Table: graph_templates_graph, Column: height, New Value: '120', Old Value: '200'</li>
<li>Table: graph_templates_graph, Column: width, New Value: '500', Old Value: '600'</li>
<li>Table: graph_templates_item, Column: alpha, New Value: 'FF', Old Value: '7F'</li>
<li>Table: graph_templates_item, Column: alpha, New Value: 'FF', Old Value: '7F'</li>
</ul><p><strong>Data Query</strong></p>
<span class="monoSpace"><span class="success">[preview]</span> Host MIB - Get Mounted Partitions <span class="updateObject">[updated]</span>
</span><br>
<ul class="monoSpace"><li>Table: snmp_query, Column: name, New Value: 'Host MIB - Get Mounted Partitions', Old Value: 'SNMP - Get Mounted Partitions'</li>
<li>Table: snmp_query, Column: xml_path, New Value: '&lt;path_cacti&gt;/plugins/hmib/templates/resource/script_server/host_disk.xml', Old Value: '&lt;path_cacti&gt;/resource/script_server/host_disk.xml'</li>
</ul></td></tr></tbody></table>

**Comment by netniV** [comment]
Not sure how to proceed with this now @cigamit, any suggestions?

**Comment by cigamit** [comment]
Well, replacing is not a bad thing.  However, the path that points the resource xml to the plugin directory is a big deal.  Is this the default package or from the hmib plugin?  If it's the hmib plugin, we should fix that there.

**Comment by cigamit** [comment]
I've made an update in the hmib plugin.  I suggest you take the actions that were articulated there:

1) Update the plugin to latest develop
2) Re-import the host disk and host_cpu templates
3) Repopulate the poller cache
4) Delete the two files in hmib/templates/resource/script_server (host_disk.xml, host_cpu.xml)
5) Delete the two files in hmib/templates/scripts (ss_host_disk.php, ss_host_cpu.php)

**Comment by netniV** [comment]
Won't that cause an issue if the user doesn't apply the base SNMP templates?

**Comment by cigamit** [comment]
Potentially.

**Comment by netniV** [comment]
Since my issue has now been resolved by this.  I will mark this as closed.
