### ISSUE TITLE
Convert Cacti's use of $.get(), $.getJSON, and $.post() to $.ajax() in order to trap and handle errors

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1195]
When click on a tab, if there is an error 500 (for example) then the console side bar.  For example, I was modifying the quicktree plugin, and missed a semi-colon (that age old developer issue) and then the tab was just collapsing and expanding the side bar.  Only when I opened the tab in a new window did the error actually appear.

**Comment by cigamit** [comment]
Well, I'm not sure we should do anything about that one.  It involves changing our wrappers loadPageNoHeader() and loadPage() from using the $.get() shortcut to using the $.ajax() function call.  

It can be done, but it's not the highest on my priority.  You would have to search out all the $.get() and $.getJSON() and $.post() calls on all the pages and rework them.  Then have a common function, likely in layout.js to handle presenting some error message like "Your code broke the web server" :)

**Comment by netniV** [comment]
Well, it's comments like this post:
https://forums.cacti.net/viewtopic.php?p=270671#p270671

That make me think we should.  If we allow plugin's to directly add UI elements, we should at least make sure they respond correctly if we are using AJAX to switch to them.  If it had been a direct HTTP request via the location bar, the error would be seen (for example, open it in a new tab).  Without a change, it just looks weird, broken and confusing to a normal end user.

**Comment by cigamit** [comment]
I'm just about to commit something that will trap a large number of these errors.  You can use it as a template to get the other ones.  I will add it as a feature, and we will keep this bug open.  There are at least 37 more of these in  the various base directory files, and likely some in lib.

**Comment by cigamit** [comment]
This could be beautified by using jQueryUI dialog I guess.  What do you think?

![callbackerrordisplay](https://user-images.githubusercontent.com/957322/35009961-fbb1615a-fac6-11e7-8cc8-17c5a077cfab.png)

**Comment by netniV** [comment]
As a first pass it works, the beautifying can come later.  Once we got the basic functionality in, it's just a simply mode to getFormatHTTPError() to make it look really pretty, maybe with a sad cacti?

**Comment by cigamit** [comment]
I like this better.

![callbackerrordisplay](https://user-images.githubusercontent.com/957322/35012792-9ecfdf7a-fad0-11e7-9a58-dbf588ea2f1f.png)

**Comment by pautiina** [comment]
Hello.
I like last version :)

**Comment by cigamit** [comment]
lol

**Comment by netniV** [comment]
Slight typo in the commit message, but as the screenshot looks a look better, I didn't notice it ;-)

I'm more looking at the wording now, thinking that you are saying it's a warning and an error... slight confusion there.  Also, do we need the "Reason:" or "Error:" parts since they are self explainitory?  Not sure if I would change it or not slightly.

**Comment by cigamit** [comment]
Feel free to word smith it and do a pull.  Remember the global_session.php change too.  Roney won't release for a few hours.

**Comment by netniV** [comment]
![image](https://user-images.githubusercontent.com/9052188/35013205-897010ee-fb04-11e7-9f6f-246c9fede7fe.png)

Don't know why but I expected a green bar

**Comment by netniV** [comment]
Global session change? Have I forgotten something?

**Comment by cigamit** [comment]
Take a look at global_session.php in the include directory, it includes translated strings into variables.  

Relative to colors, we have a project to implement jQueryUI 1.12.1 where we have to rebuild all the themes jQueryUI css.  That'll be a good project for someone.  As Paul Gevers stated in the other thread, all the jQueryUI css is pretty much based off the smoothness theme.  I just have been reluctant to go down that path.  It got too creepy until I found that you can not just use the old css, you have to start over.

If we could get some help on that, we would have it placed into the feature 1.2 branch.

**Comment by netniV** [comment]
Oh yeah, the JavaScript variables are primed from global_session.

I may create a branch, pull in jQuery 1.12.1 and see what the big diff is ;-)

**Comment by cigamit** [comment]
Cool.  How bout the word smithing?

**Comment by netniV** [comment]
OK, Give me a minute.

**Comment by netniV** [comment]
OK, I have created a commit https://github.com/Cacti/cacti/commit/977559a61bc145dd6747115e7e197a04a8626598 which changes the layout slight to:

![image](https://user-images.githubusercontent.com/9052188/35015429-4037fee8-fb0c-11e7-9e55-c2064e50b440.png)

Still wondering if we should change the title to be a static title rather than the returning value so that we don't overrun the title.  The styling is all in the JS at the moment, so you may want that to be in the css.

**Comment by cigamit** [comment]
Well, this looks much better.  I'd say stick a fork in it.

**Comment by netniV** [comment]
Just added a bunch of other changes for the .get and .getJSON calls.  Haven't had a chance to test it all so haven't created a PR yet but feel free to try it out.

**Comment by netniV** [comment]
So the above commit has now been incorporated into the #1269 patch so it can be fully tested.

**Comment by cigamit** [comment]
Marking closed.
