### ISSUE TITLE
Lose historical data after upgrading cacti

### ISSUE THREAD

**Issue by allistair-griffith** [Cacti/cacti#1196]
Good Day,

I recently upgraded from an old cacti server (0.8.7g) to a new server (1.1.25). Everything has been working successfully without any errors. I've now upgraded from 1.1.25 to 1.1.30 and it says it was upgraded successfully but i lost all my historical data.
Is it possible you can identify why that was the case? Everything is polling fine now but when i upgrade again i would not like to lose any data.
Any suggestions?

**Comment by allistair-griffith** [comment]
I meant the historical graph data. After the upgrade, I lost all previous info. Graphs currently are fine and are updating correctly. When i click the cog icon it provides me with the correct and updated info but previous info is lost.
Any ideas on what i did wrong? 
![image](https://user-images.githubusercontent.com/35377723/34892106-fc444ebc-f7a5-11e7-971e-ec23fbe00b4b.png)


![image](https://user-images.githubusercontent.com/35377723/34891994-973dce30-f7a5-11e7-8e1f-a02e6ce60d11.png)

**Comment by netniV** [comment]
That would mean that the RRD file has either been removed, or in some way the data source has been changed and generated a new RRD.

**Comment by cigamit** [comment]
In my opinion you must have accidentally removed or moved your original RRDfile's.  You should look for them.  As I did not perform your upgrade, I have no idea what you did do or did do wrong, I can't be of much help.  This is likely better suited for the forums.  I'll close, but feel free to comment, there are people watching.
