### ISSUE TITLE
Data Source Profile/Poller Interval

### ISSUE THREAD

**Issue by smiles1969** [Cacti/cacti#1197]
In regard to creating custom data source profiles-

Is it possible to add more options to the Poller Interval dropdown to allow the poller to run only once daily? Currently the max allowed is every 4 hours.

Before data source profiles were implemented, there was a way to create custom data source templates and define the steps, heartbeat, and consolidation. Now I am unsure how to accomplish once per day polling.

**Comment by cigamit** [comment]
That would be a feature enhancement.  It would of course work and is not too big of a deal.  Are you wanting 1 day average to be the only RRA?

**Comment by smiles1969** [comment]
For this particular application, that's all I would need. 

I want to retain the granularity/history over time and keep the daily polled results, and not have them averaged by week or longer.

**Comment by cigamit** [comment]
Okay, it's in.  Have fun!
