### ISSUE TITLE
Deleting a data input field generates extra dialog

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1198]
I was removing an erroneous field that I'd added to a template and when I did so, the screen presented a dialog on top of another dialog.  This may have occurred after saving the the data input haivng re-arranged the fields (which allowed them to be removed).

Once I had closed both dialogs, I could then click again and it presented properly.  But until I closed both dialogs, the continue button refused to work.

Initial view:
![screen shot 2018-01-12 at 19 06 20](https://user-images.githubusercontent.com/9052188/34891145-512bccc2-f7cc-11e7-9471-93344fb44126.png)

With the blank dialog out of the way:
![screen shot 2018-01-12 at 19 07 48](https://user-images.githubusercontent.com/9052188/34891148-5850f784-f7cc-11e7-9151-42b59389c4b2.png)

**Comment by cigamit** [comment]
Please verify you have the latest data_input.php.  That issue was resolved a few releases ago.

**Comment by netniV** [comment]
I think you may be correct.  I was testing compatibility of versions for the quicktree plugin and forgot to roll back forward.  I'll close it for now.
