### ISSUE TITLE
Documention and Plugins sections of website

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1199]
I'm not sure it's really a code issue for here, but I have noticed quite a few users looking over the past few months at the main website, particularly the documentation and plugins sections to find information for v1.1.x when really most of that information is outdated.

At the very least, there should be a warning to people about this (preferably in something nice, big, red, can't miss it) that redirects them to either GitHub and/or the forums?

**Comment by cigamit** [comment]
I had spent some time on this over the weekend.  Let me know if it looks a bit better.  There is more work to be done.  I discussed this with Roney over the weekend.  We eventually want to move everything to the GitHub Wiki.  Give the doco website a review and comment here.

**Comment by netniV** [comment]
Nice big warnings on the plugins page, quite useful.  Also on the plugins page themselves too.  The only area which seems to have been missed is the home page on the documentation:
https://docs.cacti.net/

**Comment by cigamit** [comment]
Take another look.  We will also be releasing the packaging plugin at some point in the near future.  It's on the list of things to do.  Packages are also up there now too.

**Comment by jpobeda** [comment]
What's the plan to make Github Wiki works?

**Comment by netniV** [comment]
There is a small typo "You should use that whenever possible as it installs the dependent XML files and scripts for ~~your~~you automatically. "

**Comment by netniV** [comment]
I am curious though as to how I go about making a package out of the bits I have done. heh.

**Comment by cigamit** [comment]
Yea, it'll be released.  Just have to work at the signing piece so that you can sign your packages.

**Comment by cigamit** [comment]
As far as the Wiki is concerned.  For the moment, I'm trying to get the DokuWiki (http://docs.cacti.net) up to snuff.  It provides us I think a better user experience at the moment.  Just need to give a a better skin.  The whole website needs a facelift honestly.

**Comment by netniV** [comment]
I didn't want to say anything about that ;-)

**Comment by cigamit** [comment]
Got it as good as it's going to get for this week anyway.  Going to be busy the rest of the week.  Closing.  Hopefully someone has time to invest in the documentation.

**Comment by cigamit** [comment]
I'm going to vote for DokuWiki for the time being.  I have to talk to Roney and JP once I get a few days rest.  Been busting my brains out the last few days.  Out of gas.

**Comment by jpobeda** [comment]
@cigamit how can someone actually contribute to the documentation?  It seems to be locked out to people with valid logins.

**Comment by cigamit** [comment]
When we shut down our Mantis site, we blew up the authentication.  JP, who maintains the DocuWiki and the old Mantis sites, needs to spend some time over the weekend, if he has some, determining next steps.  Until then, hang tight.  Sorry about that.

**Comment by cigamit** [comment]
One of the things I would like to see is new sections added for the new stuff.  All using either Modern, or one of the other themes (has to be a lighter one).

Then, rip out and replace all the images that used to be in the old Classic theme and moved to images based upon the Modern theme.  I would capture all images in Chrome, as the scroll bars render much nicer with it.

Those are the starters.  If you are not familiar with DokuWiki, it'll take you a little time to find your legs.

**Comment by jpobeda** [comment]
I'm happy to help, not familiar with DocuWiki though.

Let me know if you want me to go through https://github.com/Cacti/documentation/tree/develop/images and get the replacement screenshots based upon modern theme or whatever.

**Comment by cigamit** [comment]
Please do.  When create pull requests along the way.

**Comment by netniV** [comment]
The link provided has the single documentation manual page in the GitHub WIki format (.md), what format/naming convention should we use for the DocuWiki parts or is that what your hoping to discuss at the weekend?

**Comment by cigamit** [comment]
I think the DokuWiki may be a bit of a stronger language.  The Cacti Group needs a meeting to review.  Your guys input is important, so weigh in.  I personally want the documentation closer to the web site.  However, I may be misguided.

**Comment by netniV** [comment]
Depends which theme you go for... I prefer PAW so as long as the documentation follows that style... ;-)

**Comment by cigamit** [comment]
Awesome!

**Comment by cigamit** [comment]
I think this is far enough along to close.
