### ISSUE TITLE
Cacti 1.1.30 Graph trees order

### ISSUE THREAD

**Issue by chathurag** [Cacti/cacti#1201]
Even though there is an option to sort items in graph trees, we are unable to change order of graph trees in the Tree View.

**Comment by netniV** [comment]
There is already a fix coming in 1.1.31 for this. There will be two new buttons at the top right to sort the entire tab alphabetically ascending/descending. 

It also fixes issues where the sequence number is not properly set by whichever code was saving a tree. 

If you need to sort individual items, click on the Order column and up/down arrows will appear. But prior to 1.1.31 you will see some weird jumping around as most trees will have a sequence of 0 which causes the sorting problem.

**Comment by netniV** [comment]
See issue #1191 for more information.

**Comment by cigamit** [comment]
Correct.  This will be resolved in 1.1.31.  We are hoping to have it released in a day or so.  The release manager has allocated a block of time for this today, assuming we can get everything planned in.  Right now it's mostly regression and little things that are being fine tuned.
