### ISSUE TITLE
Backspace in textboxes

### ISSUE THREAD

**Issue by chathurag** [Cacti/cacti#1202]
When deleting texts in searching textboxes using backspace, and after deleting last character page get refreshed with all the text in the text box

**Comment by netniV** [comment]
I had noticed this but didn’t report it as had assumed it was a problem with chrome since if you highlight and delete the entire text it didn’t refresh the page.

**Comment by DavidLiedke** [comment]
No it is already reported. 

#629

**Comment by netniV** [comment]
Yeah, it's a known and well discussed issue apparently:
https://bugs.chromium.org/p/chromium/issues/detail?id=608016

**Comment by netniV** [comment]
After doing some digging, I believe adding:
```
$(document).on("keydown", function (e) {
    if (e.which === 8 && !$(e.target).is("input:not([readonly]):not([type=radio]):not([type=checkbox]), textarea, [contentEditable], [contentEditable=true]")) {
        e.preventDefault();
    }
});
``` 
To layout.js may help us here.  I will test this on my test system before proposing the change.

**Comment by netniV** [comment]
OK, so when actually testing this, it turns out that the functionality was already there.  However, there is a bug in that it uses the .keyup event:

```
function ajaxAnchors() {
    ... snipped ...

        $('#filter, #rfilter').keyup(function(event) {
                if (event.keyCode == 8 && $(this).val() == '') {
                        handlePopState();
                }
        });
}
```

This should read:
```
function ajaxAnchors() {
    ... snipped ...

        $('#filter, #rfilter').keydown(function(event) {
                if (event.keyCode == 8 && $(this).val() == '') {
                        handlePopState();
                }
        });
}
```

The reason this bugs is that when you delete the last character from the input, 'a' on keydown is present, but on keyup has already been removed.   I'm creating the pull request now for this.

**Comment by netniV** [comment]
Here is a screenshot showing the functionality working properly:
![backspace](https://user-images.githubusercontent.com/9052188/34941973-cc20b3d4-f9ed-11e7-8d40-64065eeba6eb.gif)

**Comment by cigamit** [comment]
Works perfectly.

**Comment by ronytomen** [comment]
Duplicate of Issue#629

**Comment by netniV** [comment]
Yes, it was as @DavidLiedke pointed out.  Fixed now.
