### ISSUE TITLE
Consulta SQL?

### ISSUE THREAD

**Issue by hramose** [Cacti/cacti#1205]
Que consulta realizar para ver las gráficas a que árbol pertenecen y la .rrd asociada a esta grafica?

**Comment by cigamit** [comment]
Vous utiliseriez ce qui suit pour obtenir les graphiques pour un arbre donné:

select local_graph_id de graph_tree_items où id =?

Pour les noms de fichiers, c'est un peu plus compliqué, vous devez d'abord déterminer le local_data_id, puis à partir de là, vous pouvez utiliser la table poller_items et mapper ces poller_item rrd_paths au fichier. Il y a des sujets de forum autour de ceci sur http://forums.cacti.net. Il suffit d'utiliser google et d'inclure le "site: forums.cacti.net" sur votre filtre de recherche pour ces renvois.
