### ISSUE TITLE
graph.php in list mode fails to allow time selections

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1209]
This comes from a bug reported for the quicktree plugin https://github.com/netniV/cacti-quicktree/issues/1 but is actually an issue that is with the graph.php.  When you highlight an area to operate a time-based selection, it fails with some PHP errors about the index being wrong.

Steps to reproduce are:

1. Click Graphs
2. Click the List View mode
3. Select a graph
4. Use the click and select method to highlight a subset of time
5. Watch nothing happen, but the click and select is now also unavailable

**Comment by netniV** [comment]
@jpobeda will be interested in a fix once one is available 👍

**Comment by cigamit** [comment]
That the reason you have bug databases.  I know about this issue, but it completely slipped my mind.  I think it has higher priority.  Let me see if I can get it fixed before the 1.1.31 release.

**Comment by cigamit** [comment]
Looks like I fixed it on my system.  Might have forgotten to commit the fix though.  Checking now.

**Comment by cigamit** [comment]
Okay, did a full audit.  Have you applied #1161 to your system?

**Comment by netniV** [comment]
Umm, yeah but no? 😨   I reverted to 1.1.21 to simulate @jpobeda 's issue.  I didn't have it until then lol.  @jpobeda You need v1.1.30 or above to fix this issue :)

**Comment by jpobeda** [comment]
@cigamit , @netniV 

Confirmed it works on 1.1.30. Thanks!

**Comment by cigamit** [comment]
It thought I was loosing my mind.  Proves two things: 1) faling memory, 2) mind lost
I did think it had been fixed, so I guess 2) is not entirely true.

**Comment by netniV** [comment]
Yeah, I think I'm going to add a plugin that reports the current cacti version to a massive header so I can't miss it! :)

**Comment by cigamit** [comment]
I actually have plans for the main page.  Just not enough time to do it.  You guys keep finding other things for me to do.

**Comment by netniV** [comment]
Lol.  Sorry, I'm good at breaking things... or running the wrong version apparently.

**Comment by cigamit** [comment]
That would be my problem.  Right now, I'm trying to run one install, but it's a half pregnant 1.2 version.  I'm going to abandon that and just run a separate instance.  Github keeps me honest and I'm fighting it by hacking around which leads to mistakes like reverting #1212 and #1213.  You won't see much from me for the next several days.  Going to get busy.
