### ISSUE TITLE
Installation/Upgrade page should show version

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1215]
When you first start Cacti, it automatically defaults to the /install/index.php folder to begin an installation or upgrade.  The first thing it displays is the license agreement and whilst that is obviously a requirement, there should be something to say what version of the software you are agreeing to.  It may even be worth adding the version you are upgrading from to make it clear on this first screen what is occurring.

**Comment by netniV** [comment]
This is how the window did look:
![image](https://user-images.githubusercontent.com/9052188/34983578-f1f480d2-faa5-11e7-8822-b404b06f86b1.png)
This is how it now looks:
![image](https://user-images.githubusercontent.com/9052188/34983543-d1f55b58-faa5-11e7-99fc-e839e48b6761.png)

**Comment by cigamit** [comment]
Yea, looks good.  Just fix that one minor comment and I'll merge.
