### ISSUE TITLE
Graph with more than 80 lines causes RRDTool to die

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1222]
If a graph is over 80 lines of data, RRD tool dies.
> /usr/bin/rrdtool graph - --imgformat=PNG --start='-86400' --end='-300' --title='examplebox (1.13) - 32 CPU Utilization' --rigid --base='1000' --height='120' --width='500' --upper-limit='3200' --lower-limit='0' --vertical-label='Percent' --slope-mode --font TITLE:10: --font AXIS:7: --font LEGEND:8: --font UNIT:7: DEF:a='/var/lib/cacti/rra/examplebox_cpu_6075.rrd':'cpu':AVERAGE DEF:b='/var/lib/cacti/rra/examplebox_cpu_6076.rrd':'cpu':AVERAGE DEF:c='/var/lib/cacti/rra/examplebox_cpu_6077.rrd':'cpu':AVERAGE DEF:d='/var/lib/cacti/rra/examplebox_cpu_6078.rrd':'cpu':AVERAGE DEF:e='/var/lib/cacti/rra/examplebox_cpu_6079.rrd':'cpu':AVERAGE DEF:f='/var/lib/cacti/rra/examplebox_cpu_6080.rrd':'cpu':AVERAGE DEF:g='/var/lib/cacti/rra/examplebox_cpu_6081.rrd':'cpu':AVERAGE DEF:h='/var/lib/cacti/rra/examplebox_cpu_6082.rrd':'cpu':AVERAGE DEF:i='/var/lib/cacti/rra/examplebox_cpu_6083.rrd':'cpu':AVERAGE DEF:j='/var/lib/cacti/rra/examplebox_cpu_6084.rrd':'cpu':AVERAGE DEF:ba='/var/lib/cacti/rra/examplebox_cpu_6085.rrd':'cpu':AVERAGE DEF:bb='/var/lib/cacti/rra/examplebox_cpu_6086.rrd':'cpu':AVERAGE DEF:bc='/var/lib/cacti/rra/examplebox_cpu_6087.rrd':'cpu':AVERAGE DEF:bd='/var/lib/cacti/rra/examplebox_cpu_6088.rrd':'cpu':AVERAGE DEF:be='/var/lib/cacti/rra/examplebox_cpu_6089.rrd':'cpu':AVERAGE DEF:bf='/var/lib/cacti/rra/examplebox_cpu_6090.rrd':'cpu':AVERAGE DEF:bg='/var/lib/cacti/rra/examplebox_cpu_6091.rrd':'cpu':AVERAGE DEF:bh='/var/lib/cacti/rra/examplebox_cpu_6092.rrd':'cpu':AVERAGE DEF:bi='/var/lib/cacti/rra/examplebox_cpu_6093.rrd':'cpu':AVERAGE DEF:bj='/var/lib/cacti/rra/examplebox_cpu_6094.rrd':'cpu':AVERAGE DEF:ca='/var/lib/cacti/rra/examplebox_cpu_6095.rrd':'cpu':AVERAGE DEF:cb='/var/lib/cacti/rra/examplebox_cpu_6096.rrd':'cpu':AVERAGE DEF:cc='/var/lib/cacti/rra/examplebox_cpu_6097.rrd':'cpu':AVERAGE DEF:cd='/var/lib/cacti/rra/examplebox_cpu_6098.rrd':'cpu':AVERAGE DEF:ce='/var/lib/cacti/rra/examplebox_cpu_6099.rrd':'cpu':AVERAGE DEF:cf='/var/lib/cacti/rra/examplebox_cpu_6100.rrd':'cpu':AVERAGE DEF:cg='/var/lib/cacti/rra/examplebox_cpu_6101.rrd':'cpu':AVERAGE DEF:ch='/var/lib/cacti/rra/examplebox_cpu_6102.rrd':'cpu':AVERAGE DEF:ci='/var/lib/cacti/rra/examplebox_cpu_6103.rrd':'cpu':AVERAGE DEF:cj='/var/lib/cacti/rra/examplebox_cpu_6104.rrd':'cpu':AVERAGE DEF:da='/var/lib/cacti/rra/examplebox_cpu_6105.rrd':'cpu':AVERAGE DEF:db='/var/lib/cacti/rra/examplebox_cpu_6106.rrd':'cpu':AVERAGE CDEF:cdefa='TIME,1516174472,GT,a,a,UN,0,a,IF,IF,TIME,1516174472,GT,b,b,UN,0,b,IF,IF,TIME,1516174472,GT,c,c,UN,0,c,IF,IF,TIME,1516174472,GT,d,d,UN,0,d,IF,IF,TIME,1516174472,GT,e,e,UN,0,e,IF,IF,TIME,1516174472,GT,f,f,UN,0,f,IF,IF,TIME,1516174472,GT,g,g,UN,0,g,IF,IF,TIME,1516174472,GT,h,h,UN,0,h,IF,IF,TIME,1516174472,GT,i,i,UN,0,i,IF,IF,TIME,1516174472,GT,j,j,UN,0,j,IF,IF,TIME,1516174472,GT,ba,ba,UN,0,ba,IF,IF,TIME,1516174472,GT,bb,bb,UN,0,bb,IF,IF,TIME,1516174472,GT,bc,bc,UN,0,bc,IF,IF,TIME,1516174472,GT,bd,bd,UN,0,bd,IF,IF,TIME,1516174472,GT,be,be,UN,0,be,IF,IF,TIME,1516174472,GT,bf,bf,UN,0,bf,IF,IF,TIME,1516174472,GT,bg,bg,UN,0,bg,IF,IF,TIME,1516174472,GT,bh,bh,UN,0,bh,IF,IF,TIME,1516174472,GT,bi,bi,UN,0,bi,IF,IF,TIME,1516174472,GT,bj,bj,UN,0,bj,IF,IF,TIME,1516174472,GT,ca,ca,UN,0,ca,IF,IF,TIME,1516174472,GT,cb,cb,UN,0,cb,IF,IF,TIME,1516174472,GT,cc,cc,UN,0,cc,IF,IF,TIME,1516174472,GT,cd,cd,UN,0,cd,IF,IF,TIME,1516174472,GT,ce,ce,UN,0,ce,IF,IF,TIME,1516174472,GT,cf,cf,UN,0,cf,IF,IF,TIME,1516174472,GT,cg,cg,UN,0,cg,IF,IF,TIME,1516174472,GT,ch,ch,UN,0,ch,IF,IF,TIME,1516174472,GT,ci,ci,UN,0,ci,IF,IF,TIME,1516174472,GT,cj,cj,UN,0,cj,IF,IF,TIME,1516174472,GT,da,da,UN,0,da,IF,IF,TIME,1516174472,GT,db,db,UN,0,db,IF,IF,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+' AREA:cdefa#FF00FFFF:'Total CPU'  GPRINT:cdefa:LAST:'Current\:%8.2lf %%'  GPRINT:cdefa:MIN:'Min\:%8.2lf %%'  GPRINT:cdefa:MAX:'Max\:%8.2lf %%\n'  LINE1:a#0000FFFF:'CPU0\:'  GPRINT:a:LAST:'    Current\:%8.2lf %%'  GPRINT:a:MIN:'Min\:%8.2lf %%'  GPRINT:a:MAX:'Max\:%8.2lf %%\n'  LINE1:b#00A348FF:'CPU1\:'  GPRINT:b:LAST:'    Current\:%8.2lf %%'  GPRINT:b:MIN:'Min\:%8.2lf %%'  GPRINT:b:MAX:'Max\:%8.2lf %%\n'  LINE1:c#C4FD3DFF:'CPU2\:'  GPRINT:c:LAST:'    Current\:%8.2lf %%'  GPRINT:c:MIN:'Min\:%8.2lf %%'  GPRINT:c:MAX:'Max\:%8.2lf %%\n'  LINE1:d#FF0000FF:'CPU3\:'  GPRINT:d:LAST:'    Current\:%8.2lf %%'  GPRINT:d:MIN:'Min\:%8.2lf %%'  GPRINT:d:MAX:'Max\:%8.2lf %%\n'  LINE1:e#000000FF:'CPU4\:'  GPRINT:e:LAST:'    Current\:%8.2lf %%'  GPRINT:e:MIN:'Min\:%8.2lf %%'  GPRINT:e:MAX:'Max\:%8.2lf %%\n'  LINE1:f#00BED9FF:'CPU5\:'  GPRINT:f:LAST:'    Current\:%8.2lf %%'  GPRINT:f:MIN:'Min\:%8.2lf %%'  GPRINT:f:MAX:'Max\:%8.2lf %%\n'  LINE1:g#FF5F00FF:'CPU6\:'  GPRINT:g:LAST:'    Current\:%8.2lf %%'  GPRINT:g:MIN:'Min\:%8.2lf %%'  GPRINT:g:MAX:'Max\:%8.2lf %%\n'  LINE1:h#AAABA1FF:'CPU7\:'  GPRINT:h:LAST:'    Current\:%8.2lf %%'  GPRINT:h:MIN:'Min\:%8.2lf %%'  GPRINT:h:MAX:'Max\:%8.2lf %%\n'  LINE1:i#96E78AFF:'CPU8\:'  GPRINT:i:LAST:'    Current\:%8.2lf %%'  GPRINT:i:MIN:'Min\:%8.2lf %%'  GPRINT:i:MAX:'Max\:%8.2lf %%\n'  LINE1:j#562B29FF:'CPU9\:'  GPRINT:j:LAST:'    Current\:%8.2lf %%'  GPRINT:j:MIN:'Min\:%8.2lf %%'  GPRINT:j:MAX:'Max\:%8.2lf %%\n'  LINE1:ba#B90054FF:'CPU10\:'  GPRINT:ba:LAST:'   Current\:%8.2lf %%'  GPRINT:ba:MIN:'Min\:%8.2lf %%'  GPRINT:ba:MAX:'Max\:%8.2lf %%\n'  LINE1:bb#CCBB00FF:'CPU11\:'  GPRINT:bb:LAST:'   Current\:%8.2lf %%'  GPRINT:bb:MIN:'Min\:%8.2lf %%'  GPRINT:bb:MAX:'Max\:%8.2lf %%\n'  LINE1:bc#FFDB87FF:'CPU12\:'  GPRINT:bc:LAST:'   Current\:%8.2lf %%'  GPRINT:bc:MIN:'Min\:%8.2lf %%'  GPRINT:bc:MAX:'Max\:%8.2lf %%\n'  LINE1:bd#96E78AFF:'CPU13\:'  GPRINT:bd:LAST:'   Current\:%8.2lf %%'  GPRINT:bd:MIN:'Min\:%8.2lf %%'  GPRINT:bd:MAX:'Max\:%8.2lf %%\n'  LINE1:be#941342FF:'CPU14\:'  GPRINT:be:LAST:'   Current\:%8.2lf %%'  GPRINT:be:MIN:'Min\:%8.2lf %%'  GPRINT:be:MAX:'Max\:%8.2lf %%\n'  LINE1:bf#FECEA8FF:'CPU15\:'  GPRINT:bf:LAST:'   Current\:%8.2lf %%'  GPRINT:bf:MIN:'Min\:%8.2lf %%'  GPRINT:bf:MAX:'Max\:%8.2lf %%\n'  LINE1:bg#E8CDEFFF:'CPU16\:'  GPRINT:bg:LAST:'   Current\:%8.2lf %%'  GPRINT:bg:MIN:'Min\:%8.2lf %%'  GPRINT:bg:MAX:'Max\:%8.2lf %%\n'  LINE1:bh#ED5394FF:'CPU17\:'  GPRINT:bh:LAST:'   Current\:%8.2lf %%'  GPRINT:bh:MIN:'Min\:%8.2lf %%'  GPRINT:bh:MAX:'Max\:%8.2lf %%\n'  LINE1:bi#FF4C4CFF:'CPU18\:'  GPRINT:bi:LAST:'   Current\:%8.2lf %%'  GPRINT:bi:MIN:'Min\:%8.2lf %%'  GPRINT:bi:MAX:'Max\:%8.2lf %%\n'  LINE1:bj#FF5576FF:'CPU19\:'  GPRINT:bj:LAST:'   Current\:%8.2lf %%'  GPRINT:bj:MIN:'Min\:%8.2lf %%'  GPRINT:bj:MAX:'Max\:%8.2lf %%\n'  LINE1:ca#ED7600FF:'CPU20\:'  GPRINT:ca:LAST:'   Current\:%8.2lf %%'  GPRINT:ca:MIN:'Min\:%8.2lf %%'  GPRINT:ca:MAX:'Max\:%8.2lf %%\n'  LINE1:cb#FF3932FF:'CPU21\:'  GPRINT:cb:LAST:'   Current\:%8.2lf %%'  GPRINT:cb:MIN:'Min\:%8.2lf %%'  GPRINT:cb:MAX:'Max\:%8.2lf %%\n'  LINE1:cc#F5F800FF:'CPU22\:'  GPRINT:cc:LAST:'   Current\:%8.2lf %%'  GPRINT:cc:MIN:'Min\:%8.2lf %%'  GPRINT:cc:MAX:'Max\:%8.2lf %%\n'  LINE1:cd#FF5F00FF:'CPU23\:'  GPRINT:cd:LAST:'   Current\:%8.2lf %%'  GPRINT:cd:MIN:'Min\:%8.2lf %%'  GPRINT:cd:MAX:'Max\:%8.2lf %%\n'  LINE1:ce#F39034FF:'CPU24\:'  GPRINT:ce:LAST:'   Current\:%8.2lf %%'  GPRINT:ce:MIN:'Min\:%8.2lf %%'  GPRINT:ce:MAX:'Max\:%8.2lf %%\n'  LINE1:cf#FFDB87FF:'CPU25\:'  GPRINT:cf:LAST:'   Current\:%8.2lf %%'  GPRINT:cf:MIN:'Min\:%8.2lf %%'  GPRINT:cf:MAX:'Max\:%8.2lf %%\n'  LINE1:cg#CDCFC4FF:'CPU26\:'  GPRINT:cg:LAST:'   Current\:%8.2lf %%'  GPRINT:cg:MIN:'Min\:%8.2lf %%'  GPRINT:cg:MAX:'Max\:%8.2lf %%\n'  LINE1:ch#E4C576FF:'CPU27\:'  GPRINT:ch:LAST:'   Current\:%8.2lf %%'  GPRINT:ch:MIN:'Min\:%8.2lf %%'  GPRINT:ch:MAX:'Max\:%8.2lf %%\n'  LINE1:ci#E8CDEFFF:'CPU28\:'  GPRINT:ci:LAST:'   Current\:%8.2lf %%'  GPRINT:ci:MIN:'Min\:%8.2lf %%'  GPRINT:ci:MAX:'Max\:%8.2lf %%\n'  LINE1:cj#FF897CFF:'CPU29\:'  GPRINT:cj:LAST:'   Current\:%8.2lf %%'  GPRINT:cj:MIN:'Min\:%8.2lf %%'  GPRINT:cj:MAX:'Max\:%8.2lf %%\n'  LINE1:da#FFD660FF:'CPU30\:'  GPRINT:da:LAST:'   Current\:%8.2lf %%'  GPRINT:da:MIN:'Min\:%8.2lf %%'  GPRINT:da:MAX:'Max\:%8.2lf %%\n'  LINE1:db#F39034FF:'CPU31\:'  GPRINT:db:LAST:'   Current\:%8.2lf %%'  GPRINT:db:MIN:'Min\:%8.2lf %%'  GPRINT:db:MAX:'Max\:%8.2lf %%\n'

Would return
> ERROR: don't understand 'cf,cf,UN,0,cf,IF,IF,TIME,1516174472,GT,cg,cg,UN,0,cg,IF,IF,TIME,1516174472,GT,ch,ch,UN,0,ch,IF,IF,TIME,1516174472,GT,ci,ci,UN,0,ci,IF,IF,TIME,1516174472,GT,cj,cj,UN,0,cj,IF,IF,TIME,1516174472,GT,da,da,UN,0,da,IF,IF,TIME,1516174472,GT,db,db,UN,0,db,IF,IF,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+'

It appears the indexing convention conflicts at "cf,cf"

**Comment by netniV** [comment]
Taken from https://forums.cacti.net/viewtopic.php?f=21&t=58355

**Comment by godsyn** [comment]
Please note, adding a 'k' doesn't resolve the issue.
You need to remove the 'c' as well.
there are 10 characters there, that correspond to the base 10 counting used for graph creation.
The fix above will be ignored.
The string should read :

```
function generate_graph_def_name($graph_item_id) {
        $lookup_table = array("a","b","d","e","f","g","h","i","j","k");

        $result = "";

        for ($i=0; $i<strlen(strval($graph_item_id)); $i++) {
                $result .= $lookup_table{substr(strval($graph_item_id), $i, 1)};

        }

        return $result;
}
```

**Comment by netniV** [comment]
Ah I’ll get that amend as I missed that out. The weird part is I did count the characters to check and somehow I miscounted :/

**Comment by cigamit** [comment]
We should do a rotation as high as we need to a..z aa..zz aaa...zzz ...  But use a slightly different algorythm after.  So: a -> z, aa -> az, ba -> bz, ...  The other thing I wanted to do in this area, is to name the def's in the templates, it makes the CDEF's a bit less fragile, but that's a story for another day.

**Comment by cigamit** [comment]
Yea, there are reserved words like CF, DEF, CDEF, ...

**Comment by netniV** [comment]
As long as there's only one two character reserved word, then the above should fix it :)

**Comment by netniV** [comment]
I submitted the difference as another pull request

**Comment by cigamit** [comment]
Marking this solved.

**Comment by netniV** [comment]
It should be noted that this change may break existing custom formulas:
https://forums.cacti.net/viewtopic.php?f=12&t=58377

**Comment by netniV** [comment]
Additional report:
https://forums.cacti.net/viewtopic.php?f=21&t=58378

**Comment by cigamit** [comment]
The solution on the forums is incorrect.  Can you please update people on the forums to NOT use this approach.  We have to revert the specific change in lib/functions.php.

**Comment by cigamit** [comment]
Simply adding the 'c' back to the function would fix this.  However, note that other reserved words need to be checked for.  A preg followed by adding 'zz' to the front of matching words should be enough.

**Comment by cigamit** [comment]
Roney is performing a release 1.1.33.  I have to take time off to work on other things for a time.  So, I needed this to be handled sooner than later.

**Comment by netniV** [comment]
Understood. I'll get back to the scheduler, etc.

**Comment by godsyn** [comment]
Where is the new change that should fix this?

**Comment by cigamit** [comment]
The way it is fixed is by appending special characters to the def name for very large numbers of DEF's.  Now, the way it works, it the function get's the total count of defs, say 100.  What Cacti does is the following:

It converts the number 100, into a three character string "100", then it take each character of the string and converts it to the associated letter in the array 'a', 'b', 'c', ...

That array requires a total of 10 elements corresponding to the ten digits between 0-9.  So, back to the string, in our test case, it was "100".  So, the last DEF name will be:

"1" => "a"
"2" => "b"
"99" => "jj"
"100" => "baa"

The change appends 'zz' to all reserved names that can occur in this range.  Those reserved words include:

"cf" => 36 << Likely in an aggregate graph

"cdef" => 3678 << Not Likely
"def" => 678 << Not Likely

Does this make sense now?  By the way, I had looked at making the DEF's nameable by the template author so that you could have a little more control of this, but in the end, left it as is.

**Comment by godsyn** [comment]
Thank you.
