### ISSUE TITLE
Reapply Suggested Names dont work after upgrade to 1.1.31

### ISSUE THREAD

**Issue by Cramin** [Cacti/cacti#1225]
Upgraded from 1.1.30 to 1.1.31 i can not use function to update port names in switches.
I Reload Query and go to device and Graph List or Data Source List, select changed port on switch, choose Reapply Suggested Names and click OK, button grayed and nothing happens.

**Comment by netniV** [comment]
Can you check if you are seeing any errors in either the apache logs or the cacti log?

**Comment by netniV** [comment]
I just tried this on my machine and it correct navigated forward.  This may be related to your navigational issues you mentioned on the #1226

**Comment by Cramin** [comment]
Update lib/html.php solved the problem.
