### ISSUE TITLE
Problem with filter bars

### ISSUE THREAD

**Issue by Cramin** [Cacti/cacti#1226]
After upgrade to 1.1.31 i have problem with filters, when i click in search bar or i want change filter setting all filter setting are closing.
https://i.imgur.com/jlITmO4.png

**Comment by pautiina** [comment]
Ctrl+F5

**Comment by netniV** [comment]
Can you use GifCam to make an animated recording of what you are seeing?  Also, have you tried to refresh your cache etc?  The best way to do this is to navigate to your themes main.css and main.js (in your case /include/themes/paw/main.css and main.js) then hit refresh a couple of times.

Out of curiosity, I noticed that you didn't have the display issue I had first thing this morning, have you applied any fixes for that?

**Comment by cigamit** [comment]
Update the lib/html.php from develop.  This was an issue due to an api change that did not get enough QA time.

**Comment by Cramin** [comment]
Updated lib/html.php solved the problem.
