### ISSUE TITLE
Any tree or branch with a long name force main content off screen

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1228]
If a user or plugin creates a tree/branch that has an extra large name, or the tree has many many nests of branches, the main filter/content ends up off screen.

![image](https://user-images.githubusercontent.com/9052188/35090847-dc5fd0c6-fc32-11e7-911f-40fdd1378425.png)

One possible fix would be to set a max width of the tree panel

**Comment by cigamit** [comment]
I'm not a fan of hidden, but maybe scroll could work and do like we did in the 0.8.9 days, and put a slider there.

**Comment by netniV** [comment]
The alternative is to trim the text but keep the full version on hover like a lot of apps do?

**Comment by cigamit** [comment]
Nah, but lets worry about some other issues for the moment.  I don't see this as a real high priority.

**Comment by netniV** [comment]
Noted :)

**Comment by pautiina** [comment]
Hello. Maybe I have find problem.
I have the latest commit, and on brovser console have this error:

```
layout.js:1298 Uncaught TypeError: Cannot read property 'match' of undefined
    at getPresentHTTPError (layout.js:1298)
    at Object.<anonymous> (layout.js:1866)
    at fire (jquery.js:3317)
    at Object.fireWith [as rejectWith] (jquery.js:3447)
    at done (jquery.js:9274)
    at Object.abort (jquery.js:8995)
    at Object.<anonymous> (layout.js:90)
    at Function.each (jquery.js:368)
    at Object.abortAll (layout.js:88)
    at applyGraphFilter (layout.js:1853)
```

**Comment by cigamit** [comment]
Resolving this shortly.
