### ISSUE TITLE
Cacti 1.1.31 issue - autohide filter

### ISSUE THREAD

**Issue by Izmenoff** [Cacti/cacti#1229]
Filter is autohide after use in Chrome browser  64.0.3282.99. In Mozilla/IE works without problem.

**Comment by netniV** [comment]
Couple of quesitons

- Which page is this on?  
- Can you provide the steps that you take?  
- What theme are you using?

**Comment by Izmenoff** [comment]
for example - change presets
![image](https://user-images.githubusercontent.com/17400240/35092309-089e96dc-fc50-11e7-8cc9-c11ec292381a.png)
click on and the filter hides
![image](https://user-images.githubusercontent.com/17400240/35092369-338a08c2-fc50-11e7-932f-20328ca48116.png)

**Comment by Izmenoff** [comment]
Cleaned browser cache resolved the problem

**Comment by cigamit** [comment]
Refreshing CSS and JS through Chrome is not easy.  You have to either clear your browser cache, wait until the cows come home, or open the files and press F5 on each.  It's not easy.

**Comment by netniV** [comment]
Hmm, I don't seem to get issues with that.  Maybe it's because I have the developer tools open.

**Comment by Izmenoff** [comment]
Thanks, I have already done it. It works 18.01.2018, 14:57, "Jimmy Conner" <notifications@github.com>:Refreshing CSS and JS through Chrome is not easy. You have to either clear your browser cache, wait until the cows come home, or open the files and press F5 on each. It's not easy.—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.
