### ISSUE TITLE
Call to undefined function get_max_tree_sequence()

### ISSUE THREAD

**Issue by spawnzao** [Cacti/cacti#1230]
[php7:error] [pid 30870] [client 172.16.48.16:56046] PHP Fatal error:  Uncaught Error: Call to undefined function get_max_tree_sequence() in /usr/share/cacti/tree.php:488\nStack trace:\n#0 /usr/share/cacti/tree.php(93): form_save()\n#1 {main}\n  thrown in /usr/share/cacti/tree.php on line 488

                if (empty($save['sequence'])) {
 			$save['sequence'] = get_max_tree_sequence() + 1;
 		}

**Comment by netniV** [comment]
Yes, that is a bug.  The actual function name is tree_get_max_sequence() so if you rename that in your copy it should fix the issue and I'll submit a PR for that.

**Comment by cigamit** [comment]
We will try to get 1.1.32 out this weekend.  Sorry about that.
