### ISSUE TITLE
I can't edit devices with the mactrack plugin enabled

### ISSUE THREAD

**Issue by spawnzao** [Cacti/cacti#1231]
Here are the errors that happen when I try to edit a device:

[Thu Jan 18 21:47:49.277400 2018] [php7:notice] [pid 30864] [client 172.16.48.16:56494] PHP Notice:  Undefined index: device_id in /usr/share/cacti/plugins/mactrack/mactrack_actions.php on line 182
[Thu Jan 18 21:47:49.277552 2018] [php7:notice] [pid 30864] [client 172.16.48.16:56494] PHP Notice:  Undefined index: site_id in /usr/share/cacti/plugins/mactrack/mactrack_actions.php on line 184
[Thu Jan 18 21:47:49.277669 2018] [php7:notice] [pid 30864] [client 172.16.48.16:56494] PHP Notice:  Undefined index: scan_type in /usr/share/cacti/plugins/mactrack/mactrack_actions.php on line 187
[Thu Jan 18 21:47:49.277798 2018] [php7:notice] [pid 30864] [client 172.16.48.16:56494] PHP Notice:  Undefined index: snmp_options in /usr/share/cacti/plugins/mactrack/mactrack_actions.php on line 188
[Thu Jan 18 21:47:49.277914 2018] [php7:notice] [pid 30864] [client 172.16.48.16:56494] PHP Notice:  Undefined index: snmp_retries in /usr/share/cacti/plugins/mactrack/mactrack_actions.php on line 200
[Thu Jan 18 21:47:49.278126 2018] [php7:notice] [pid 30864] [client 172.16.48.16:56494] PHP Notice:  Undefined index: ignorePorts in /usr/share/cacti/plugins/mactrack/mactrack_actions.php on line 202
[Thu Jan 18 21:47:49.278261 2018] [php7:notice] [pid 30864] [client 172.16.48.16:56494] PHP Notice:  Undefined index: user_name in /usr/share/cacti/plugins/mactrack/mactrack_actions.php on line 204
[Thu Jan 18 21:47:49.278442 2018] [php7:notice] [pid 30864] [client 172.16.48.16:56494] PHP Notice:  Undefined index: user_password in /usr/share/cacti/plugins/mactrack/mactrack_actions.php on line 205
[Thu Jan 18 21:47:49.278608 2018] [php7:notice] [pid 30864] [client 172.16.48.16:56494] PHP Notice:  Undefined index: term_type in /usr/share/cacti/plugins/mactrack/mactrack_actions.php on line 206
[Thu Jan 18 21:47:49.278766 2018] [php7:notice] [pid 30864] [client 172.16.48.16:56494] PHP Notice:  Undefined index: private_key_path in /usr/share/cacti/plugins/mactrack/mactrack_actions.php on line 207
[Thu Jan 18 21:47:49.284594 2018] [php7:notice] [pid 30864] [client 172.16.48.16:56494] PHP Notice:  Undefined index: device_id in /usr/share/cacti/plugins/mactrack/mactrack_actions.php on line 211

**Comment by netniV** [comment]
Each of the columns you have listed are found in the mac_track_devices table.  Make sure that exists within your MySQL or MaraDB database. If it does, it may be that there is no host entry in that table for the device that is being edited.  I did notice that the code checks if the snmp_engine_id is set on the $mt_device array and if not sets that element to blank.  However, it doesn't actually get that $mt_device is valid before doing so, so I think that may be causing the issue with the is_array statement that follows since it would now be an array.

**Comment by cigamit** [comment]
Please open this bug in the mactrack issues list.  Going to close here.
