### ISSUE TITLE
 Please help me  Cacti 1.1.31 No Trees In graphs label 

### ISSUE THREAD

**Issue by gaojianberkeley** [Cacti/cacti#1237]
click  Tree Mode “load...“ is show，but very quickly disappeared。after  nothing is show please help me Thank you very much! 
”![default](https://user-images.githubusercontent.com/35594862/35143234-ef015920-fd3b-11e7-96bf-a2a1bfd07efb.png)

**Comment by netniV** [comment]
Try applying this fix:
https://github.com/Cacti/cacti/commit/25644cf39b2f4feb53a1a9c8fffcc4cd8b34cf9f

**Comment by gaojianberkeley** [comment]
Thanks very much！but don’t sloved problem！

**Comment by cigamit** [comment]
That's definitely it.  Also, please verify that you have no javascript errors by bringing up the debug console in firefox and paste any error messages there.

**Comment by cigamit** [comment]
Resolved now.  Latest lib/html.php did it.

**Comment by gaojianberkeley** [comment]
Thank you very much netniv and cigamit！I try it！
