### ISSUE TITLE
New Installation: Cacti 1.1.31 : issue - Graphing not working-No Data has been collected

### ISSUE THREAD

**Issue by haneesibm** [Cacti/cacti#1238]
issue - Graphing not working-No Data has been collected.

--clog--

01/19/2018 11:48:50 - CMDPHP PHP ERROR WARNING Backtrace: (/cmd.php: 659 cacti_snmp_session_get)(/lib/snmp.php: 541 get)(CactiErrorHandler)(/lib/functions.php: 4475 cacti_debug_backtrace)
01/19/2018 11:48:50 - ERROR PHP WARNING: SNMP::get(): Invalid object identifier: in file: /var/www/html/lib/snmp.php on line: 541
01/19/2018 03:23:51 - CMDPHP PHP ERROR WARNING Backtrace: (/cmd.php: 659 cacti_snmp_session_get)(/lib/snmp.php: 541 get)(CactiErrorHandler)(/lib/functions.php: 4475 cacti_debug_backtrace)
01/19/2018 03:23:51 - ERROR PHP WARNING: SNMP::get(): Invalid object identifier: in file: /var/www/html/lib/snmp.php on line: 541
01/19/2018 03:22:57 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4518 cacti_debug_backtrace)

**Comment by cigamit** [comment]
It appears that your snmpagent is not able to query some OID's.  You should check your Poller Cache and verify things.  In the mean time, this is a bug in that we never covered this error case in our ignore logic.

**Comment by cigamit** [comment]
The reporting of Invalid object identifier has been resolved and will be included in 1.1.32.  The general question should be taken up on the forums.  Thanks for reporting this error.
