### ISSUE TITLE
session_start() failing in PHP 7.1+

### ISSUE THREAD

**Issue by reubenfarrelly** [Cacti/cacti#124]
As of the last 24+ hours I've been unable to log into my up-to-date -git installation of Cacti.  The login box appears and I enter valid credentials, but after submitting the page refreshes and re-requests me log in again.

Polling of objects appears to be working as indicated in the logs.

This is logged in the cacti.log file:

2017-01-01 07:05:53 - ERROR PHP : session_start(): Failed to read session data: user (path: /var/tmp) in file: /var/www/cacti-new.reub.net/htdocs/include/global.php  on line: 251
2017-01-01 07:05:53 - CMDPHP PHP ERROR WARNING Backtrace: (/index.php: 25 include)(/include/auth.php: 27 include)(/include/global.php: 251 session_start)(CactiErrorHandler)(/lib/functions.php: 4194 cacti_debug_backtrace)
2017-01-01 07:05:55 - ERROR PHP : session_start(): Failed to read session data: user (path: /var/tmp) in file: /var/www/cacti-new.reub.net/htdocs/include/global.php  on line: 251
2017-01-01 07:05:55 - CMDPHP PHP ERROR WARNING Backtrace: (/index.php: 25 include)(/include/auth.php: 27 include)(/include/global.php: 251 session_start)(CactiErrorHandler)(/lib/functions.php: 4194 cacti_debug_backtrace)
2017-01-01 07:05:56 - AUTH LOGIN: User 'reuben' Authenticated
2017-01-01 07:05:56 - ERROR PHP : session_start(): Failed to read session data: user (path: /var/tmp) in file: /var/www/cacti-new.reub.net/htdocs/include/global.php  on line: 251
2017-01-01 07:05:56 - CMDPHP PHP ERROR WARNING Backtrace: (/index.php: 25 include)(/include/auth.php: 27 include)(/include/global.php: 251 session_start)(CactiErrorHandler)(/lib/functions.php: 4194 cacti_debug_backtrace)

I also attempted recreating the database (by dropping and then recreating it), and still see the same issue.

The temp directory in the logs above is correct namely /var/tmp, and there is space, inodes and indeed other processes able to write session files.  Only cacti is having this problem (original 0.8.8 cacti with the same php binaries and same php config is working OK).

I'm running php-7.1 on Gentoo x86_64.

**Comment by cigamit** [comment]
Sound like you might be out of disk space?  That's generally when these types of things happen.

**Comment by reubenfarrelly** [comment]
No - definitely not out of space:

/dev/sda5       9.8G  3.7G  5.6G  40% /var
/dev/sda7       4.8G   12M  4.6G   1% /var/tmp

None of the other partitions are anywhere near even 50% full too.

**Comment by reubenfarrelly** [comment]
After some further testing by rolling back in -git to code from late November the issue still remained although it's unclear why it only became an issue in the last few days.  However it does not seem to be an issue with Cacti-0.8.8h which still was working OK.

I then downgraded to php-7.0 and everything started working again from git HEAD.

So it appears that there may be some compatibility issues with Cacti and php-7.1.  A Google search indicates a few other projects seem to have had issues with changes to session cookies in 7.1 too - see release notes http://php.net/ChangeLog-7.php .  In my case I'm running an almost plain php.ini, no special databases or session handlers etc

**Comment by cigamit** [comment]
Okay, definitely a major PHP issue I think don't you?  I scanned through the release notes, and they looked mostly like bug fixes.  We will have to take a deeper look as bug changes should not be breaking 13 year old behavior.

**Comment by cigamit** [comment]
Okay, so, they are trying to force projects to use the setcookie*() functions to set cookies instead of using the header function.  I could propose a diff if you are willing to test.  I have to look back at session management to figure out, with this new behavior what is apparently broken and what needs to be fixed.  Stay tuned.

**Comment by cigamit** [comment]
Just did a review, we are not doing anything special.  I guess it's time to setup a sandbox.

**Comment by reubenfarrelly** [comment]
I'm certainly able to help testing.  I have two separate installations - one which I care about somewhat (for home use but has quite a few useful things in it) and a second installation tracking the development branch essentially for an early preview of features.
I can change to/from php 7.0/7.1 with ease as both are installed in parallel.

**Comment by cigamit** [comment]
I reviewed the bolt projects method of addressing this, and it seemed that the reason that the session cookies were not working was related to the size of the session variable not matching what was in their php.ini file.  This issue may end up resolving itself.  The dev's are having a discussion as to whether the fix belongs with the php distribution packagers, or if we have to force things just as bolt did.

**Comment by morganm** [comment]
Just coming to let you know this is not an isolated issue. I run Cacti on Arch and I noticed it was broken after some recent updates. Tonight I finally got around to fixing it all up, only to ultimately run into the issue reported here a few months ago. It appears there is no fix available yet?

Version info:
php 7.1.1-1
cacti 1.0.1-1
Linux 3.10.104-6-ARCH armv7l

**Comment by cigamit** [comment]
We are not in a hurry to update to 7.1 at the moment.  Which distro are you using?

**Comment by cigamit** [comment]
As predicted, this issue seems to be resolved in PHP 7.1.3 as reported in Issue #481.  Therefore, I will close this one.
