### ISSUE TITLE
Edit Device - SNMP Ping - Error unclear

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1246]
When you edit a device and you see SNMP Error at the top of the page, it is unclear what kind of error this actually is.  If you take a look at forum post https://forums.cacti.net/viewtopic.php?p=270825#p270825 I think we should add a more descriptive reason to help narrow down the type of error.

Looking at the code for that top section, it would appear that one of three types of error can occur.
- Cacti was unable to start an SNMP session to the device in question
- Cacti was unable to retrieve oid '.1.3.6.1.2.1.1.1.0' using the created session
- Cacti found a blank string as a result of that oid on session (after a little manipulation for some bad device results)

Of these, for some reason only the middle one stops the ping results from appearing.  Should that be the case?  Should they all prevent the ping results from appearing?  Should they all display the ping results?

**Comment by netniV** [comment]
![image](https://user-images.githubusercontent.com/9052188/35182477-e496a70a-fdcd-11e7-9974-37746cb4cde1.png)
This was returned during the timeout, wondering if the message should read "Timeout or Undefined"?

**Comment by cigamit** [comment]
Well, it guess it could be a timeout too couldn't it?  Or it could be some of the other errors.  Since this goes through the lib/snmp.php, we could set a global on the IgnoreErrorHandler for banned strings and use that in host.php to store the list of errors.  Maybe that is asking too much since there are multiple calls.  A static array would fix that up though.  I may be over thinking this.

**Comment by netniV** [comment]
Well, normally we just see SNMP Error because that is all done after the calls are made by checking the result.  Since the result isn't passed back (and could break plugins etc if it was), then there is little we can do to get the actual result (unless the snmp session stores its own last error?).

**Comment by cigamit** [comment]
It's a global.  See below.  It's in lib/functions.php

![ignorehandler](https://user-images.githubusercontent.com/957322/35185233-77bbdc42-fdc6-11e7-887b-68a05148e433.png)

**Comment by cigamit** [comment]
Maybe have some i18n implications if the locale of the web server is anything other than english though.

**Comment by netniV** [comment]
Ah, so that is probably what is causing the result to be blank on the session or value to be blank

**Comment by cigamit** [comment]
correct.  Just echo the global variable if it's set, though it may be set even after second call.  Not sure it's cleared the beginning of every call.

**Comment by cigamit** [comment]
I double verified that the snmp_error was cleared before each call.  So, now you can properly create the enhancement.

**Comment by netniV** [comment]
Really?  I can't see it being cleared.  I can see that it is referenced, but it's only updated by IgnoreCactiHandler().  So for a quick fix, I can clear that global variable before making the calls and then check for its presence in this circumstance.

**Comment by netniV** [comment]
OK, updated the code.

**Comment by netniV** [comment]
Oh, I see what you mean about the snmp_error, I hadn't got the latest develop branch on the issue branch.
