### ISSUE TITLE
issue with poller data collector status is down. 

### ISSUE THREAD

**Issue by haneesibm** [Cacti/cacti#1248]
01/20/2018 19:34:18 - AUTOM8 ERROR: The Network ID: 1 is disabled. You must use the 'force' option to force it's execution.

**Comment by netniV** [comment]
This means that you have not ticked the network's Enabled property.

**Comment by haneesibm** [comment]
why is the data collector status is shown "Unknown/Down"

**Comment by netniV** [comment]
Which part are you seeing the data collector status on?

**Comment by anarkia1976** [comment]
Do you have checked if cron.d and poller are executed on the remote poller?

**Comment by haneesibm** [comment]
Hi, 
the problem has been solved by after adding a crontab with the required line. 

thanks for the help guys.

**Comment by liarevalo** [comment]
Hi, how can I do? the contab is there!!
![screenshot from 2018-10-27 19-15-33](https://user-images.githubusercontent.com/16836088/47610865-eb837300-da1c-11e8-8be9-b5463eacaa26.png)
![screenshot from 2018-10-27 19-15-48](https://user-images.githubusercontent.com/16836088/47610866-eb837300-da1c-11e8-9337-dfe9eda41f7f.png)
![screenshot from 2018-10-27 19-15-58](https://user-images.githubusercontent.com/16836088/47610867-eb837300-da1c-11e8-82c2-f9f95acd3942.png)

**Comment by liarevalo** [comment]
Logs

![image](https://user-images.githubusercontent.com/16836088/47611033-cfce9b80-da21-11e8-9566-c2b39109b7cb.png)

**Comment by netniV** [comment]
Yo7 are using 1.1.38 on PHP 7.2+ downgrade unsupported, downgrade PHP or upgrade Cacti

**Comment by liarevalo** [comment]
:-(
![image](https://user-images.githubusercontent.com/16836088/47623261-f39ee980-dad4-11e8-845f-41af8986edd7.png)

**Comment by liarevalo** [comment]
either downgrading the php version, neither of the propose worked  
![image](https://user-images.githubusercontent.com/16836088/47686800-aab56680-dba2-11e8-9232-10549d13d6a7.png)
![image](https://user-images.githubusercontent.com/16836088/47686807-b4d76500-dba2-11e8-8e97-7c98f69d5cd3.png)
![image](https://user-images.githubusercontent.com/16836088/47686816-c1f45400-dba2-11e8-8d14-07dbed9e1bd2.png)
![image](https://user-images.githubusercontent.com/16836088/47686828-cde01600-dba2-11e8-989c-a1cacdc8d682.png)

**Comment by netniV** [comment]
That looks like a MySQL version problem too.  I'm guessing that your OS installed one of the newer MariaDB or MySQL editions.
