### ISSUE TITLE
Zoom out through middle button on mouse - default turned on

### ISSUE THREAD

**Issue by Poslik** [Cacti/cacti#1251]
Hello, I was frustrated from lost of the zoom out functionality through right clicking on mouse so I decide to implement zoom out functionality through middle click from the "advanced" zoom out mode to "quick" mode. Would it be possible to implement it to cacti as default?

I inserted to /usr/share/cacti/include/js/jquery.zoom.js "case 2" part:
`

    $("#zoom-box").off("mouseup").on("mouseup", function(e) {
    	switch(e.which) {
    		/* leaving the left mouse button will execute a zoom in */
    		case 1:
    			if (zoom.attr.start != 'none') {
    				zoomAction_zoom_in();
    			}
    		break;
    		
    		case 2:
    			/* hide context menu if open */
    			zoomContextMenu_hide();
    			if (zoom.custom.zoom3rdMouseButton == 'zoom_in') {
    				zoomAction_zoom_in();
    			} else {
    				zoomAction_zoom_out( zoom.custom.zoomOutFactor );
    			}
    		break;						
    		
    	}
    });
    
    /* register the mouse up event */
    $("#zoom-area").off("mouseup").on("mouseup", function(e) {
    	switch(e.which) {
    		/* leaving the left mouse button will execute a zoom in */
    		case 1:
    			if (zoom.attr.start != 'none') {
    				zoomAction_zoom_in();
    
    			}
    		break;
    		
    		case 2:
    			/* hide context menu if open */
    			zoomContextMenu_hide();
    			if (zoom.custom.zoom3rdMouseButton == 'zoom_in') {
    				zoomAction_zoom_in();
    			} else {
    				zoomAction_zoom_out( zoom.custom.zoomOutFactor );
    			}
    		break;						
    	}
    });
`

I changed the context menu info:
`

	+ '<div class="first_li">'
	+ 		'<div class="ui-icon ui-icon-zoomout zoomContextMenuAction__zoom_out"></div>'
	+ 		'<span class="zoomContextMenuAction__zoom_out">Zoom Out (2x)</span>'
	+ 		'<div class="inner_li">'
	+ 			'<span class="zoomContextMenuAction__zoom_out__2">2x</span>'
	+ 			'<span class="zoomContextMenuAction__zoom_out__4">4x</span>'
	+ 			'<span class="zoomContextMenuAction__zoom_out__8">8x</span>'
	+ 			'<span class="zoomContextMenuAction__zoom_out__16">16x</span>'
	+ 			'<span class="zoomContextMenuAction__zoom_out__32">32x</span>'
	+ 		'</div>'
	
	+ 		'<hr size="1" width=70% noshade="" align="center" color="silver">'
	+ 		'<div class="ui-icon ui-icon-info"></div>'
	+ 		'<span style="color: #A4A4A4">or do a middle click on your mouse</span>'
	
	+ '</div>'
`

and width in jquery.zoom.css in /usr/share/cacti/include/themes/*

`
.zoom-menu .first_li span {
    /*width:110px;*/
    width:200px;
    display:block;
    padding:5px 10px;
    cursor:pointer
}
`

The result look like this:
![image](https://user-images.githubusercontent.com/35453993/35211318-4a664138-ff56-11e7-948c-ea7698eb4810.png)

**Comment by cigamit** [comment]
This should be committed through a pull request.  If you could do that, it would be apprecaiated.  Also, I prefer that you do not add the 'or do a middle' piece, but just add something like a setting that eludes to this being available.  Browniebraun should review and comment as well.

**Comment by browniebraun** [comment]
I dislike that special message/hint, but I appreciate your idea of making the third button configuration available for both modes and set the default to zoom out.
Regards
-Andi
