### ISSUE TITLE
Undefined index: snmp_community in file: /var/www/html/automation_snmp.php on line: 656

### ISSUE THREAD

**Issue by Cramin** [Cacti/cacti#1259]
`01/23/2018 17:06:03 - CMDPHP PHP ERROR NOTICE Backtrace: (/automation_snmp.php: 89 automation_snmp_edit)(/automation_snmp.php: 656 CactiErrorHandler)(/lib/functions.php: 4482 cacti_debug_backtrace)`
`01/23/2018 17:06:03 - ERROR PHP NOTICE: Undefined index: snmp_community in file: /var/www/html/automation_snmp.php on line: 656`
Cacti 1.1.33 new install.

**Comment by netniV** [comment]
See issue #1258 and close this one

**Comment by Cramin** [comment]
`alter table `automation_snmp_items` change `snmp_readstring` `snmp_community` varchar(50) NOT NULL DEFAULT "";`
`alter table `automation_snmp_items` change `snmp_auth_protocol` `snmp_auth_protocol` varchar(6) NULL DEFAULT "";`
Solved
