### ISSUE TITLE
Tab images not rendering due to improperly compiled php-gd module

### ISSUE THREAD

**Issue by dqsuper** [Cacti/cacti#1260]
Upgrade Cacti form 1.1.30 to 1.1.33 ，thold is not work.
thold_develop.zip(1.0.4)
cacti.log
01/24/2018 08:13:08 - ERROR PHP ERROR: Uncaught Error: Call to undefined function imagettfbbox() in /usr/local/nginx/html/cacti/lib/functions.php:4344
01/24/2018 08:13:08 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4520 cacti_debug_backtrace)
01/24/2018 08:13:11 - ERROR PHP ERROR: Uncaught Error: Call to undefined function imagettfbbox() in /usr/local/nginx/html/cacti/lib/functions.php:4344
01/24/2018 08:13:11 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4520 cacti_debug_backtrace)
01/24/2018 08:13:12 - ERROR PHP ERROR: Uncaught Error: Call to undefined function imagettfbbox() in /usr/local/nginx/html/cacti/lib/functions.php:4344
01/24/2018 08:13:12 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4520 cacti_debug_backtrace)
01/24/2018 08:13:13 - ERROR PHP ERROR: Uncaught Error: Call to undefined function imagettfbbox() in /usr/local/nginx/html/cacti/lib/functions.php:4344
01/24/2018 08:13:13 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4520 cacti_debug_backtrace)
01/24/2018 08:13:13 - ERROR PHP ERROR: Uncaught Error: Call to undefined function imagettfbbox() in /usr/local/nginx/html/cacti/lib/functions.php:4344
01/24/2018 08:13:13 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4520 cacti_debug_backtrace)

**Comment by Izmenoff** [comment]
I have the same error with (/lib/functions.php: 4520 cacti_debug_backtrace) after upgrade to 1.131
/lib/functions.php: 4520 cacti_debug_backtrace)
https://github.com/Cacti/cacti/issues/1255

**Comment by netniV** [comment]
Have you used the latest develop code of the plugins? They don’t appear to be released on the same cycle as Cacti

**Comment by netniV** [comment]
I've just checked my live site, I'm not having these errors.  More over, thold does not even seem to call (directly) 'imagettfbbox'.  So I went and checked the base cacti code, this appears to be a function for using the Classic theme.

The strange part is, this function should be part of your base php installation: http://php.net/manual/en/function.imagettfbbox.php

Although there is a note on the PHP website which says:
> **Note:** This function is only available if PHP is compiled with freetype support (**--with-freetype-dir=DIR **)

So, the question is, do you have freetype support turned on?

**Comment by anarkia1976** [comment]
I have tested latest cacti with latest thold and i don't have this error.
👍

**Comment by cigamit** [comment]
This is a php-gd dependency issue as per the prior post.  Though we did have a problem with this in an old bug, but apparently we did not fix it completely.

**Comment by cigamit** [comment]
We can use imagestring() instead of imagettfbbox() when the later is not defined.  So, let's keep this open.

**Comment by netniV** [comment]
I've submitted a PR for this now

Example without spaces:
![image](https://user-images.githubusercontent.com/9052188/35443592-99e75e22-02a3-11e8-92b5-d37a3b3a8547.png)

Example with spaces:
![image](https://user-images.githubusercontent.com/9052188/35443620-aa4be800-02a3-11e8-92af-ab7334db5b31.png)

**Comment by cigamit** [comment]
Thanks for all the good work netniV!  Closing.  To be part of 1.1.34.
