### ISSUE TITLE
Create utility to audit the Cacti schema for issues

### ISSUE THREAD

**Issue by cigamit** [Cacti/cacti#1263]
Over the years, Cacti upgrades can result in inconsistencies between the published Cacti schema and the actual user schema.  Create a utility that audits and/or repairs schemas that are not upto specification.

**Comment by netniV** [comment]
One issue you will have with this, because plugins have direct access to the database via the functions db_execute, etc, they can add their own fields to the core tables.  Best practice would be that shouldn't be allowed because it modifies the core schema.  One example is thold which although a cacti-owned plugin is not present on every database; yet this plugin actively creates fields in the base host table.

It could be useful to have the plugins supply details of the tables/fields that they create in order to properly check against these too.

**Comment by cigamit** [comment]
There is an API for that (which includes a table too), but not all plugins use it.  So, we would have to work around things that are 'new' and simply identify them.

**Comment by cigamit** [comment]
I dropped in an audit tool.  It does not currently verify plugin tables or columns.  It checks for sequencing, and I know some plugins did not respect sequencing.  So, may have to pull that out.  There is a lot of work required for the indexes and make sure little things don't cause false positives.

**Comment by cigamit** [comment]
More updates, makes doing the check easy, but still some things are not caught, like the engine, and missing indexes, and missing columns.  Also, right now no repair is performed.

**Comment by netniV** [comment]
Looks good so far.  Will have to remember to update this on any DB change now too ;-)

Just wondering if the primer should be done during upgrade so it's only done once?

**Comment by cigamit** [comment]
I was thinking about that last night too.  My schema was a little wrecked too.  Most of it inconsequential, but still not right.

**Comment by cigamit** [comment]
Now that I cleaned up most of my schema and can see the forest from the trees, I've found a few indexes missing from the default schema and a few columns that were supposed to have been dropped.

**Comment by cigamit** [comment]
This utility is implemented and not working pretty well.  In addition, it was used to remediate all the issues when upgrading from earlier version of Cacti.  Going to close this.

**Comment by netniV** [comment]
Not working well? Think that is a typo there ;-)

Additionally, I just had a thought that if this generated a warning for a mismatch of the database, TravIs CI would be able to pick that up which could help ensure we have the cacti.sql file updated?

**Comment by cigamit** [comment]
Reach out to Rony via traditional email.  He currently owns the Travis process.  If it's doable in a pull request, all the better.
