### ISSUE TITLE
How to update cacti 1.1.28 to 1.1.33

### ISSUE THREAD

**Issue by ginesgb** [Cacti/cacti#1264]
Hello everyone, where I can get a guide to update 1.1.28 to 1.1.33.?
Greetings and thank you

**Comment by DavidLiedke** [comment]
This is **no** issue.


> Hello everyone, where I can get a guide to update 1.1.28 to 1.1.33.?

See the comment from @netniV in #1255

**Comment by cigamit** [comment]
This is an issue best kept on the forums.  This is not a place to share opinions bug verified bugs with documentation.  I'll leave this ticket open for a day or so.  But unless you can go beyond simple statements, it really ads no value.

**Comment by cigamit** [comment]
Changed my mind.  You can still comment though.

**Comment by ginesgb** [comment]
I have carried out all the steps indicated, but it does not update, and it still does not paint the graphics of all the equipment I have, the version that appears on the web is 1.1.28. Will not it be necessary to make some more changes to carry out the update? Greetings and thank you

**Comment by netniV** [comment]
This would suggest that the path your cacti code is in is different to the one used in my example. If it is Ubuntu this may be /usr/share/cacti but it could be different again if you’ve manually placed it. Check your apache configuration for the actual location.
