### ISSUE TITLE
Plugin installation error (Current Version 1.1.33)

### ISSUE THREAD

**Issue by haneesibm** [Cacti/cacti#1265]
Dears, 
I had a problem with the plugin installation. then didn't find any solution for the issue, so thought of upgrading the cacti version from 1.1.31 to 1.1.33 but unfortunately, the error message is same even after upgrading to the newer version.

List of Plugins that I have to try to install:
- Mactrack 4.2
- Thresholds 1.0.4

error:
--
Validation error for variable id with a value of mactrack4.1. See backtrace below for more details.
(/plugins.php: 51 get_filter_request_var)(/lib/html_utility.php: 439 die_html_input_error)(/lib/html_validate.php: 60 cacti_debug_backtrace)
--

kindly help me on this issue. 

Thanks 
Hanees M.

**Comment by netniV** [comment]
This would appear to be an error because of the 4.1.  The ID should be just mactrack I think so the chances are you've named your directory incorrectly underneath the plugins folder.

Here is an example from my test system:
```
p$ ls plugins/
hmib  index.php  mactrack  monitor  quicktree  thold  weathermap
```

**Comment by haneesibm** [comment]
Dear, 
Thanks for the reply. and you are right. when I renamed the directory then I was able to install the plugins without any issue.

Thank you.
