### ISSUE TITLE
Joins without indexes

### ISSUE THREAD

**Issue by Cramin** [Cacti/cacti#1267]
I have problem with new cacti servers.
I have old server + Cacti 1.1.33 upgraded from 1.0.4 many times to current versions.
mysqltuner.pl says `[OK] No joins without indexes`
I install Cacti in new servers and mysqltuner.pl says `[!!] Joins performed without indexes: 18456`
`Adjust your join queries to always utilize indexes`

**Comment by netniV** [comment]
You can see these using:

- the MySQL slow query logging 
   [Log Queries Not Using Indexes](https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_log_queries_not_using_indexes)
   [Slow Query Log](https://dev.mysql.com/doc/refman/5.7/en/slow-query-log.html)

- or if you aren't able to enable that log, you can try to capture the output of mysql using tcpdump:
   [How to find unindexed queries in mysql without using the log](https://www.xaprb.com/blog/2009/08/18/how-to-find-un-indexed-queries-in-mysql-without-using-the-log/)

**Comment by netniV** [comment]
Btw, if you have enabled certain plugins, I know there are some that do not use joins but where statements instead.  One such plugin is routerconfig where there was a join statement not working correctly so the change was reverted.
https://github.com/Cacti/plugin_routerconfigs/pull/23

**Comment by Cramin** [comment]
This is new server, only Cacti and added 100 devices.
https://pastebin.com/ZKPSVmhT
```
# Time: 180125 10:46:58
# User@Host: cactidb[cactidb] @ localhost []
# Thread_id: 2  Schema: cacti  QC_hit: No
# Query_time: 0.000699  Lock_time: 0.000444  Rows_sent: 1  Rows_examined: 1
# Rows_affected: 0
use cacti;
SET timestamp=1516873618;
SELECT cacti FROM version LIMIT 1;
# User@Host: cactidb[cactidb] @ localhost []
# Thread_id: 2  Schema: cacti  QC_hit: No
# Query_time: 0.000063  Lock_time: 0.000022  Rows_sent: 1  Rows_examined: 1
# Rows_affected: 0
SET timestamp=1516873618;
SELECT cacti FROM version;
# User@Host: cactidb[cactidb] @ localhost []
# Thread_id: 2  Schema: cacti  QC_hit: No
# Query_time: 0.000867  Lock_time: 0.000729  Rows_sent: 0  Rows_examined: 1
# Rows_affected: 0
SET timestamp=1516873618;
SELECT id, title, extendedstyle   FROM external_links   WHERE style="CONSOLE"   AND enabled="on"   ORDER BY extendedstyle, sortorder, id;
```
I get this in log file.

**Comment by cigamit** [comment]
The version table has been doing this for years.  It has one row.  It's a bit of a red herring but does pollute the metrics.  The external links 'might' need some tuning.  The version table also tics a full table scan on the metrics, but again one record.

**Comment by netniV** [comment]
Maybe adding a KEY to both would reduce that?

**Comment by Cramin** [comment]
cigamit did you look at the pastebin link?

**Comment by cigamit** [comment]
I'm looking now.  It appears that some of the non-indexed queries are based upon an order clause.  So, in the case of the SELECT DISTINCT gt.id ... query, if you reduce the name column to where the index on the name field can be totally encompassed within the name index (right now it's only the first 191 characters), then the no-index log will go away.  The same applies from the SELECT * FROM plugin_realms, if you create an index on the "default" column, it goes away.

This would be a nice project for you, now that you have these tips.  Can you invest any time in creating an upgrade script and a revised cacti.sql to minimize these?  We would appreciate the help.  There is no reason for the name column to be 255 characters, for example.

**Comment by netniV** [comment]
Two questions
- Which 'you' were you referring to?
- Where does the 191 come from?

**Comment by cigamit** [comment]
Sorry, it was for Cramin.  The 191 is the index length.  If you look at cacti.sql, you will see some 'KEY' lines that look like the following:

`KEY name(name(191))`

What this does is create a partial key since key lengths in utf8mb4 collations are limited to right around that number of characters (4*191).  But a column like name, need be no more than say 128 characters.  Even that may be a little long.  The reason you get a table scan in these cases is that the index does not cover the entire length of the field.  So, the database engine has to get the rows from that index and ensure that there is not anything different in the un-indexed portion, and therefore, you get dinged on the query without an index stat.

Follow now?

**Comment by netniV** [comment]
Ah yeah, not come across that before.  I'll add that to my "what I learned today" along with GD / TFF / Image processing 🛩 🌔 👍

**Comment by cigamit** [comment]
@Cramin, can you review this again once 1.1.34 is released?

**Comment by Cramin** [comment]
Hello again.
I don't have enough knowledge to fix that. And I don't know when it happens.
I tested new servers, new installs of Cacti and in this new install mysqltuner.pl says:
`[OK] No joins without indexes`
Installed new instance 1.1.35.

**Comment by cigamit** [comment]
There will be a few.  But for now, I'll close this.  The audit we did in the 1.1.34 release took care of the lions share of these.  We will open a separate ticket to handle very long indexes and reduce their column widths where it's appropriate in a future release.  Thanks for spending what time you did on auditing and reporting this.
