### ISSUE TITLE
CACTI - Version 1.1.33 - Log Search filter problem

### ISSUE THREAD

**Issue by anarkia1976** [Cacti/cacti#1268]
When i wrote "down" in the search filter i have this error:

![image](https://user-images.githubusercontent.com/1744639/35430355-34a21db6-0278-11e8-888d-bd78ee5cad34.png)

if i wrote "prova", "test", ecc i don't have problems.

thanks a lot

**Comment by SergejLT** [comment]
Can confirm. log search filter not working correctly
![cacti_log](https://user-images.githubusercontent.com/32635039/35431240-602485da-0284-11e8-9667-37e5db4a3bc1.PNG)

**Comment by netniV** [comment]
this is related to the issue #1256 I think.  I'll get onto this now and see if I can track it down since it's causing an issue with the log filtering.

**Comment by netniV** [comment]
Oh, the quick fix for now, make it a REGEX string by simply adding brackets around what you want to search for.  I think we are going to need to add a new filter type that is REGEX_OR_STRING but for now I may just modify the validate_is_regex function to check for a pure string (ie A-Za-z0-9:space:) and assume that is also a valid regex

**Comment by anarkia1976** [comment]
@netniV 
It working with your quick fix suggested.
thanks a lot.

**Comment by netniV** [comment]
The real issue is two fold:
- custom_error messages are not being handled properly.  
- rfilter was changed on graph_view.php to allow regex properly, but other pages need the same update

**Comment by netniV** [comment]
If anyone wants to try out this patch, it should correct the issues fully including that blank display of error messages.

**Comment by netniV** [comment]
This is now in the main develop code for anyone who is running from a GIT CLONE of that.

**Comment by cigamit** [comment]
Thanks for all the good work netniV!  Closing.  To be part of 1.1.34.
