### ISSUE TITLE
Paw Theme: host.php

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#127]
1. Please center text in columns:
- ID,
- GRAPHS,
- Data Sources,
- Uptime,
- Poll Time,
- Current (ms),
- Average,
- Avability.

It would be much more clear for read. 

2. It would be very useful if there would be a filter 'Select Minimum Criticaly'.

**Comment by cigamit** [comment]
Being that the author has not touched this in quite some time, I'm going to consider this a non-starter.
