### ISSUE TITLE
Bad result from ss_host_cpu.php

### ISSUE THREAD

**Issue by Fireball2k15** [Cacti/cacti#1274]
In some circumstances you get a bar result by using a value of array $arr

Issue is solved when replacing the line:
https://github.com/Cacti/cacti/blob/5d4eb04de3b45365ffb55326723a4a6029227f1f/scripts/ss_host_cpu.php#L115

with the following code:
if (isset($arr_index[$index]) && isset($arr[$index])) {

Fireball

**Comment by netniV** [comment]
That should happen only there is a device timing out between the index walk and value walk... but the check looks good to verify that.

**Comment by Fireball2k15** [comment]
Hi,
this would be perfect for me, because I've some very slow answering Linux machines. Otherwise the log is filld up with anoying error messages ;-)
thx Fireball

**Comment by netniV** [comment]
There are actually two versions of this script.  One with the base Cacti system and a similar one in the plugin_hmib code.

**Comment by netniV** [comment]
I've created that patch.  Thanks for that.

**Comment by netniV** [comment]
This has now been included in the develop code.  Please test and close this issue.

**Comment by Fireball2k15** [comment]
Woks fine - thx
