### ISSUE TITLE
SNMP v3 authPriv Crashes

### ISSUE THREAD

**Issue by maforshaw** [Cacti/cacti#1275]
I upgraded from Cacti 1.1.16 to 1.1.33 and my SNMP connections stopped working. The logs indicated a crash:

ERROR PHP NOTICE: Undefined variable: sec_details in file: /lib/snmp.php on line: 204 

It appears authentication details are not being set any more when the security level is "authPriv".

The fix is to search for every "authPriv" in snmp.php and define $sec_details, for example:

```php
$sec_level = 'authPriv';
$sec_details = ' -a ' . snmp_escape_string($auth_proto) . ' -A ' . snmp_escape_string($password);
```

**Comment by netniV** [comment]
I've created a patch for this, do you want to test it out?

**Comment by maforshaw** [comment]
Thank you @netniV I tested the patch and it works great.

**Comment by cigamit** [comment]
@maforshaw, the pull was merged differently.  Please test with the actual lib/snmp.php that was just committed to the develop branch.  Thanks.

**Comment by maforshaw** [comment]
@cigamit I just tested the new commit and can confirm my authPriv devices still work fine, thank you.
