### ISSUE TITLE
Remove redundant code from lib/snmp.php

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1280]
In the cacti_snmp_walk function, there is the following bit of code:

```php
if ($temp_array === false) {
        if ($temp_array === false) {
                cacti_log("WARNING: SNMP Error:'$snmp_error', Device:'$hostname', OID:'$oid'", false);
        } elseif ($oid == '.1.3.6.1.2.1.47.1.1.1.1.2' ||
                $oid == '.1.3.6.1.4.1.9.9.68.1.2.2.1.2' ||
                $oid == '.1.3.6.1.4.1.9.9.46.1.6.1.1.5' ||
                $oid == '.1.3.6.1.4.1.9.9.46.1.6.1.1.14' ||
                $oid == '.1.3.6.1.4.1.9.9.23.1.2.1.1.6') {
                /* do nothing */
        } else {
                cacti_log("WARNING: SNMP Error, Device:'$hostname', OID:'$oid'", false);
        }
}
```
This makes no sense to me, as it's performing the same check on the inner if as the outer if, which should surely mean it's only going to hit the first condition?

**Comment by cigamit** [comment]
That code is pretty evil.  Let's just whack it.  But before that's done, let's see what gandalf had intended when he wrote it.  I'm guessing is has something to do with increasing oid checks.  Maybe these OID's are subject to these issues.

**Comment by cigamit** [comment]
Resolved.

**Comment by netniV** [comment]
Just for reference, those OID's refer to:

OID | Name | MIB
--- | --- | ---
.1.3.6.1.2.1.47.1.1.1.1.2 | enPhysicalDescr | Entity
.1.3.6.1.4.1.9.9.68.1.2.2.1.2 | vmVlans | Cisco VLAN
.1.3.6.1.4.1.9.9.46.1.6.1.1.5 | vlanTrunkPortNativeVlan | Cisco VTP
.1.3.6.1.4.1.9.9.46.1.6.1.1.14 | vlanTrunkPortDynamicStatus | Cisco VTP
.1.3.6.1.4.1.9.9.23.1.2.1.1.6 | cdpCacheDeviceId | Cisco CDP
