### ISSUE TITLE
The variable max_oids is for bulkget and not bulkwalk operations

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1281]
Looking at the code of the cacti_snmp_walk() function, this has a $max_oids value which can be passed in and defaults to 10.  However, this value is only used under the following conditions:

- snmp_get_method('walk') does not return SNMP_METHOD_PHP
- configuration option 'path_snmpbulkwalk' has been set to command that exists
- snmp version is greater than 1 and the $max_oid has been set to more than 1.

This means that all other versions of the code will return as many OIDs as they can find which must lead to inconsistent behaviour.

**Comment by cigamit** [comment]
Sorry about this.  The max oid's setting was originally setup for performing bulk get's in spine, and somehow lost it's direction.  It somehow bled into the walk, and more importantly bulkwalk functions.

This is something that should be reviewing for sure.

**Comment by cigamit** [comment]
Resolved.
