### ISSUE TITLE
It does not paint graphics in Cacti 1.1.33

### ISSUE THREAD

**Issue by ginesgb** [Cacti/cacti#1284]
Hello, I have updated Cacti to version 1.1.33 (before version 1.1.28) and indicating that the front-end indicates that it was done correctly, but the graphics did not make them, I deleted a router and returned it to register, but it gave me the error that the file found , since it may not be able to create it.
Capture of the attached database. What mistake do you have now? Have  myself take a step?
https://www.cacti.net/downloads/docs/html/upgrade.html

![image](https://user-images.githubusercontent.com/4158441/35570069-5affc0b8-05ce-11e8-8f40-5c5891a3bf69.png)

![image](https://user-images.githubusercontent.com/4158441/35570044-45f56f7e-05ce-11e8-99e1-526346d1035a.png)

I have followed the update reference manual that you have available on the website. And I have configured the database as requested. What error is there now?
Greetings and thank you

**Comment by anarkia1976** [comment]
Do you have updated rrdtool also?

**Comment by ginesgb** [comment]
Yes,  RRDtool 1.7.x

This reviewing the log and in de mariadb, this appears to me

2018-01-30 16:00:00 140703138654976 [Warning] Unsafe statement written to the binary log using statement format since BINLOG_FORMAT = STATEMENT. The statement is unsafe because it uses a LIMIT clause. This is unsafe because the set of rows included cannot be predicted. Statement: UPDATE `snmpagent_cache`    SET `value` = '1517328000'   WHERE `mib` = 'CACTI-MIB'   AND `name` = 'cactiStatsLastUpdate'   LIMIT 1
2018-01-30 16:00:00 140703138654976 [Note] Suppressing warnings of type 'The statement is unsafe because it uses a LIMIT clause. This is unsafe because the set of rows included cannot be predicted.' for up to 300 seconds because of flooding

**Comment by anarkia1976** [comment]
Can you try with rrdt 1.6?

**Comment by ginesgb** [comment]
Yes, I have tried it, but it does not work,  now it is a virtual machine with the centos 7 and i do the procedure to install it, doing the installation of cactus 1.1.33, now I am processing the templates, the installation has been clean and I did not have any conflict with no file, I still need to know if it really makes the graphics now. I will comment, thank you very much

**Comment by cigamit** [comment]
This is not a Cacti problem, this is more of a support problem that should be handled on the forums.  The easy fix is to disable binary replication in mysql and repair the database if it's damaged.  You should also take a look at permissions.  Often times people do stupid things like either change the permissions on the RRA folder, or literally remove the old RRDfiles during upgrades.  Either way, good problem for the forums.
