### ISSUE TITLE
BackupConfig Plugin for Graylog is not showing

### ISSUE THREAD

**Issue by komathodivijay** [Cacti/cacti#1285]
Plugin is not reflecting in Graylog Console.
Version:- Graylog v2.4.0 
1. Download the  BackupConfig Plugin 1.0.2 and place the .jar file in Graylog plugin directory.
2. Restart graylog-server 
![graylog plugin](https://user-images.githubusercontent.com/26949629/35605658-25870b2e-0670-11e8-9f79-c69d7f081354.JPG)

Pls help to sort this issue.

**Comment by anarkia1976** [comment]
Do you have open an issue in the wrong repository?

**Comment by netniV** [comment]
I think so @anarkia1976 especially as Cacti doesn't really do threat intelligence.

**Comment by cigamit** [comment]
I'm not sure what this has to do with us.  Closing.
