### ISSUE TITLE
JSON calls return validation error in HTML format

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1287]
When making JSON calls to pages, some responses may come back in HTML format if a validation error occurs.  These calls should include a JSON marker so that the validation errors can be returned using either JSON or with a true error (including response text) so that the true error is displayed to the end user.

This relates to issue #1266 and possible #1286

**Comment by cigamit** [comment]
This has been resolved in the latest commits for #1286.  Still discussing whether or not the method was correct though.  Marking closed none the less.
