### ISSUE TITLE
Console sidebar appearing on plugins

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1288]
So when I was looking at some plugin issues, I noticed that the side menu was appearing for the QuickTree plugin.  Whilst that wasn't necessary a problem itself, it did lead to some confusion over whether I was on QuickTree or the Console as clicking any of the sidebar menus, left me in the QuickTree tab.

Once I realised what was happening, I switched to QuickTree's code to check what headers it was including etc.  I need some clarification over which header() function I should be using, and I'm now wondering if there should be one specifically for plugins to utilise so it doesn't get corrupted by changes to the base tabs.

- top_header() displays the tabs, the breadcrumbs and the sidebar
- general_header() displays the tabs and the breadcrumbs (though displays as Console > <Plugin Name>)
- top_graph_header() displays the same as top_graph_header() (or at least appears to).

**Comment by netniV** [comment]
@cigamit Thought you'd have provided a quick comment on this by now 👍

**Comment by cigamit** [comment]
You know, I've got so many things going on.  It's hard to stay focused on this.  Here is an explanation of top tabs and breadcrumbs and some topics around them.

1) The breadcrumbs are a bit of a nightmare as the larger the framework becomes, the more overhead they place on the system.  We discussed moving the array to a table to allow MySQL/MariaDB caching to assist, but these things have to be prioritized, and though the array is a) large, b) difficult to understand, they still work.

2) Breadcrumbs are represented as a hierarchy with the 'mapping' attribute controlling their presentation, from left to right.  Any child (generally the first child) that is index.php will map to the 'Console'.  So, if you take the following example from the $nav array:
`'mapping' => 'index.php:,graphs.php:,graphs.php:graph_edit'`

it means breadcrumbs will be presented as:

`Console -> Graph Management -> (Edit)`

3) If you happen to screw up and call general_header() in your php file when your breadcrumb is based on 'index.php', well, it'll make no sense.  The two behaviors are independent from one another.

4) As a team we had multiple discussions over the years of moving away from top_header() and bottom_footer() and replace it with a framework approach.  Yes, Cacti itself is it's own framework, but the header and footer piece is a bit of legacy, where if we were to start fresh on Cacti in 2018, we would never do.  When Cacti was originally written, Ajax was a dream in fact.  It think in that light, it's fared well.

5)  We had initially planned to make the top tabs and the rendering of top tab changes to all be done via callbacks in 1.2, but as you can imagine, with the number of issues we have been working through, it's still a way off.  It you think about it, it should not be too difficult.

6) However, when doing so, we need to continue to support deep linking, and that is always the problem with moving to a callback design.  We almost have it with the exception of the Tree which was broken when we moved to jstree (there is an open bug for it).

7) For plugins, the mapping should always start with a plugin page, and then nest from there, unless it's menu pick is on the console, in which the base of the mapping will be `index.php:`

I hope this helps.

**Comment by cigamit** [comment]
No changes in the current cacti required for this change as it's a designed behavior.  So, closing now.

**Comment by netniV** [comment]
Yeah appreciate the busy part, hence I thought i'd stick a reminder in 👍 

Some useful info, was after more which function to use an in which situation really :)

**Comment by cigamit** [comment]
I was reading Howies blog last night, and he was somewhat critical of the shit show that is the Cacti API.  We want to change that over time, but we've been attempting to hold onto the old framework for a while, maybe too long.  Either way, better API documentation, and moving more and more functionality to the API layer so that we can eventually separate user experience from business logic will help.

**Comment by netniV** [comment]
I haven't read that.  I'll go take a look.

**Comment by netniV** [comment]
Didn't find it, maybe you could provide a link?

**Comment by cigamit** [comment]
https://network-weathermap.com/blog/

**Comment by netniV** [comment]
Oh the one from around Christmas?  Yeah I'd seen that. Thought there was a newer more scathing one.  Oh well.  Maybe for 5.0 we can get to classes ? ;-)
