### ISSUE TITLE
issue #485 is back

### ISSUE THREAD

**Issue by fherb** [Cacti/cacti#1292]
Looks like the issue from #485 is back in todays release. Only seems to work correctly in Firefox.

**Comment by fherb** [comment]
Contacting device with the updating/spinning icon that never completes. 
Upgraded to v 1.1.33

**Comment by netniV** [comment]
Are you getting any errors? It's working fine for me.

**Comment by cigamit** [comment]
you need to open the Firefox developers tools, goto the console there, and look for JavaScript errors.

**Comment by fherb** [comment]
I don't get an error in Firefox, but in Chrome I get this:
Uncaught ReferenceError: setSNMP is not defined
    at changeHostForm (<anonymous>:131:3)
    at HTMLDocument.<anonymous> (<anonymous>:200:3)
    at mightThrow (jquery.js:3570)
    at process (jquery.js:3638)

**Comment by netniV** [comment]
That seems impossible because function `setSNMP` should be in layout.js which is included globally.

**Comment by fherb** [comment]
I've got a bunch of users who it's happening to. All chrome users. Is it possible its declared in more than one spot?

**Comment by fherb** [comment]
When selecting a device, console -> devices -> device name

Uncaught ReferenceError: setSNMP is not defined
    at changeHostForm (<anonymous>:131:3)
    at HTMLDocument.<anonymous> (<anonymous>:200:3)
    at mightThrow (jquery.js:3570)
    at process (jquery.js:3638)

When attempting to perform an action on a device, console -> device -> check device box -> select place on tree -> go

Uncaught ReferenceError: checkForLogout is not defined
    at Object.<anonymous> (<anonymous>:9:6)
    at fire (jquery.js:3305)
    at Object.fireWith [as resolveWith] (jquery.js:3435)
    at done (jquery.js:9242)
    at XMLHttpRequest.<anonymous> (jquery.js:9484)

**Comment by netniV** [comment]
Well both of those functions are defined in layout.js.  Browse to <cacti>/include/layout.js and search for those functions prefixing the name with "n " (sans quotes).

It sounds to me like you've either got a caching issue or a corrupted layout.js

**Comment by cigamit** [comment]
Chrome in it's management of JavaScript files is horrible.  It refuses to detect changes and recache unless you literally open the file as follows: `http://my.dns.entry/cacti/include/layout.js`, and with that file shown in the browser, hit F5 or Ctrl+R.  It's horrible.

**Comment by cigamit** [comment]
Closing as this is a bogus browser error.  There are some that believe that if we add a random number to something like '&version=random' to the source attribute of the script tag that this would be a workaround.  However, this comes at a cost of having to continually download the file and not utilize caching at all.  The real work around is to release Cacti less often ;)

**Comment by netniV** [comment]
Rather than use a random one, maybe just an updated hash of the layout.js added to the include?

**Comment by cigamit** [comment]
Great idea, you can pull that value from the resource cache table to save time.  Pull request would be great.

**Comment by netniV** [comment]
Err, remind me where that is again? I'm having a mental block.

**Comment by cigamit** [comment]
table poller_resource_cache:

`SELECT md5sum FROM poller_resource_cache WHERE path='include/layout.js';`

Make it a function call.  Include in all the top*header() files in the include directory.

**Comment by cigamit** [comment]
One thing is that in cases where there are no remote pollers, this table might be empty.  Have to look back at the code.  Maybe if the table is empty, manually perform the md5sum once and cache it in the session.

**Comment by cigamit** [comment]
It's not primed on Windows, so you will have to cache it from time to time.  Just performed the code review.

**Comment by netniV** [comment]
Working on it now.

**Comment by netniV** [comment]
I have created a pull request for this functionality.  I tested it on the modern theme and all appears to be working as expected.
