### ISSUE TITLE
Option to allow OIDs that are not in order

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1293]
I have been trying to add a HPE OfficeConnect 1920 to MacTrack and whilst I've worked out most parts I have found that the HPE returns the OIDs out of sequence.  When I went to look into how to correct this, it would seem that there isn't a way using the original snmp_xxx functions, but from php 5.4 there is a SNMP class which would accept it (http://php.net/manual/en/snmp.walk.php)

From stackoverflow (https://stackoverflow.com/a/36407842):
```php
<?php
  $dataSNMP = array();  
  $ipDevice = "10.206.4.38";

  $SNMP = new SNMP(1, $ipDevice, "public");
  $SNMP->oid_increasing_check = false;
  $dataSNMP = $SNMP->walk("1.3.6.1.4.1.14988.1.1.1.3.1.8");
  $SNMP->close();
?>
```

Now if I disable PHP SNMP so that the code uses snmpwalk etc, I would need a way to add the -Cc option to disable the increasing check.

**Comment by cigamit** [comment]
Goto Configuration > Settings > Poller and check 'Disable increasing OID check'.

**Comment by netniV** [comment]
I don't know how I missed that.  Been switching between issues too much I think.

**Comment by netniV** [comment]
This issue should be re-opened because I still have the same problem.  Because we are not using the classed based walk, the code is ignoring the option you have set.

![image](https://user-images.githubusercontent.com/9052188/35680974-dd026d0a-0753-11e8-86b4-f5ca3ca546d6.png)

```
DEBUG: Adding IfInterfaces Records
DEBUG: ifInterfaces assembly complete.
PHP Warning:  snmp2_real_walk(): Error: OID not increasing: .1.3.6.1.2.1.17.4.3.1.3.80.101.243.57.160.233 in /usr/share/cacti/develop/lib/snmp.php on line 568
PHP Warning:  snmp2_real_walk(): Error: OID not increasing: .1.3.6.1.2.1.17.4.3.1.3.48.7.77.179.99.15 in /usr/share/cacti/develop/lib/snmp.php on line 568
PHP Warning:  snmp2_real_walk(): Error: OID not increasing: .1.3.6.1.2.1.17.4.3.1.3.0.39.13.2.184.65 in /usr/share/cacti/develop/lib/snmp.php on line 568
PHP Warning:  snmp2_real_walk(): Error: OID not increasing: .1.3.6.1.2.1.17.4.3.1.3.160.72.28.162.208.76 in /usr/share/cacti/develop/lib/snmp.php on line 568
PHP Warning:  snmp2_real_walk(): Error: OID not increasing: .1.3.6.1.2.1.17.4.3.1.3.160.224.175.2.139.131 in /usr/share/cacti/develop/lib/snmp.php on line 568
PHP Warning:  snmp2_real_walk(): Error: OID not increasing: .1.3.6.1.2.1.17.4.3.1.3.188.131.133.245.2.214 in /usr/share/cacti/develop/lib/snmp.php on line 568
PHP Warning:  snmp2_real_walk(): Error: OID not increasing: .1.3.6.1.2.1.17.4.3.1.3.160.224.175.86.157.29 in /usr/share/cacti/develop/lib/snmp.php on line 568
PHP Warning:  snmp2_real_walk(): Error: OID not increasing: .1.3.6.1.2.1.17.4.3.1.3.0.35.36.49.2.246 in /usr/share/cacti/develop/lib/snmp.php on line 568
PHP Warning:  snmp2_real_walk(): Error: OID not increasing: .1.3.6.1.2.1.17.4.3.1.3.0.12.41.77.169.228 in /usr/share/cacti/develop/lib/snmp.php on line 568
PHP Warning:  snmp2_real_walk(): Error: OID not increasing: .1.3.6.1.2.1.17.4.3.1.3.164.209.210.179.99.70 in /usr/share/cacti/develop/lib/snmp.php on line 568
```

**Comment by netniV** [comment]
On further investigation, I am wondering if this is a problem of the caller.  I'm now investigating mactrack_functions.php for cacti_snmp_walk

**Comment by netniV** [comment]
So each `cacti_snmp_walk` from mactrack_functions.php is called with no `$value_output_format` specified.  This means that it should be `SNMP_STRING_OUTPUT_GUESS`.  Walk, then calls `snmp_get_method` passing in `'walk'` and the `$value_output_format` which must be returning `SNMP_METHOD_PHP`

Looking at the function it appears this should never happen, until you re-read this section of code:
```php
} elseif ($type == 'walk' && file_exists('path_snmpbulkwalk')) {
        return SNMP_METHOD_BINARY;
 ```
which should actually be
```php
} elseif ($type == 'walk' && file_exists(read_config_option('path_snmpbulkwalk'))) {
        return SNMP_METHOD_BINARY;
 ```

**Comment by netniV** [comment]
So it would also seem that the #1297 issue is also causing confusion on this issue.  Because the warning kept appearing in the log file, it looked like the walk wasn't working when in fact it was (although it was using the PHP version).

**Comment by cigamit** [comment]
Yea, the walk merge had me cross-eyed.
