### ISSUE TITLE
Cacti error logging reports suppressed errors

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1296]
If a function is called using the @ symbol, Cacti is still reporting the errors even though PHP is not reporting them.  According to http://uk.php.net/manual/en/language.operators.errorcontrol.php this is because even though PHP is suppressing the error, it still calls the error handler.

Therefore, the Error Handler should check error_reporting() to see if it is set at 0.  An example of this demonstration is:

```php
error_reporting(E_ALL & ~(E_STRICT|E_NOTICE));
echo "1: " . error_reporting() . "\n";
error_reporting(0);
echo "2: " . error_reporting() . "\n";
error_reporting(E_ALL & ~(E_STRICT|E_NOTICE));
echo "3: " . error_reporting() . " vs ". @error_reporting() . "\n";
```
which produces the output:
```
1: 30711
2: 0
3: 30711 vs 0
```

**Comment by cigamit** [comment]
Marking closed.
