### ISSUE TITLE
cacti.sql - Key column 'data_source_name' doesn't exist in table

### ISSUE THREAD

**Issue by BSOD2600** [Cacti/cacti#130]
fresh cacti db install with mysql 5.7

ERROR 1072 (42000) at line 2841 in file: 'C:\Apache24\htdocs\cacti\cacti.sql': Key column 'data_source_name' doesn't exist in table

Name is inconsistent as both data_source_name and data_source_name**s** are present...

**Comment by cigamit** [comment]
Resolved thanks!

**Comment by BSOD2600** [comment]
Would it make sense to add some basic mysql testing of cacti.sql to Travis CI to proactively identify this type of issue in the future?
