### ISSUE TITLE
auth_changepassword.php return button not working

### ISSUE THREAD

**Issue by mortenstevens** [Cacti/cacti#1310]
Hello,

I see a small issue with the latest cacti releases. If you navigate to /cacti/auth_changepassword.php and pressing the "Return" button is not working...  I have tested it with Google Chrome and Firefox. But sometimes it works if you press it multiple times.

Best regards,

Morten

**Comment by netniV** [comment]
I will test this now.

**Comment by netniV** [comment]
So, the return button is designed to go back in your history.  It uses javascript to run window.history.go(-1);  This may be part of a larger issue where the history functions aren't 100% and push you forwards to exactly where you were.  See #1301 and #430 which I am going to be reviewing over the next week or so to see if I can correct.

**Comment by mortenstevens** [comment]
@netniV 

Thank you. It was working fine with 1.1.28. But sometime between 1.1.28 and 1.1.33 it doesn't work....

Best regards,

Morten

**Comment by netniV** [comment]
Probably related to the ajax calls.  I can run through the releases and find out which broken it and see if I can see why.  That may also give some help on the larger issue that quite often you want to hit back on your browser window but unless you right click and select the history item you want, you find yourself yo-yo'ing between the previous link and back your current page automatically.

Best to keep it on that other issue thread though to keep track of these things.

**Comment by cigamit** [comment]
I've fixed this, just waiting for non-work hours to commit.

**Comment by cigamit** [comment]
This should be resolved now.  Update layout.js and global_session.php from develop, logout and then back in again.

**Comment by cigamit** [comment]
Close if it's working well.

**Comment by cigamit** [comment]
I've tested this and it's now back to normal.  Thanks for catching it.
