### ISSUE TITLE
Fedora/Redhat RPM packaging shebang warnings

### ISSUE THREAD

**Issue by mortenstevens** [Cacti/cacti#1311]
Hello,

I'm packaging cacti for Fedora and Fedora-EPEL (RHEL). On Fedora rawhide I got some shebang warnings packaging the latest cacti release after running /usr/lib/rpm/redhat/brp-mangle-shebangs

[cacti-shebangs.txt](https://github.com/Cacti/cacti/files/1699123/cacti-shebangs.txt)

Buildlog is here: https://kojipkgs.fedoraproject.org//packages/cacti/1.1.34/1.fc28/data/logs/noarch/build.log

Maybe we can fix this upstream by cacti?

Thank you.

Best regards,

Morten

**Comment by netniV** [comment]
Looking at this none of those files should be executable with the exception of maybe `cmd.php`  Looks like @ronytomen will be correcting this.

**Comment by ronytomen** [comment]
Corrected in commit# 6c0ad97cd83570d3b865700fa25c490888084c24

**Comment by mortenstevens** [comment]
Thank you.

Best regards,

Morten
