### ISSUE TITLE
I can't add new  graph from graph management in cacti 1.1.24 

### ISSUE THREAD

**Issue by joellin** [Cacti/cacti#1314]
Hello 
I already update cacti from Version 0.8.7g to version 1.1.24 .
I can't find button "add" from graph management to create new graph.
How to do to create new graph not from device ??

version cacti 0.8.7g
![image](https://user-images.githubusercontent.com/36221419/35902771-77fe2840-0c17-11e8-9784-5b905d4b0dc7.png)

version cacti 1.1.24
![image](https://user-images.githubusercontent.com/36221419/35902725-45a53eb0-0c17-11e8-86e2-bced3f0b9216.png)

I try to create like this graph from cacti 1.1.24, but I don't how to do.
this graph is from version cacti 0.8.7g,
![cacti bandwith2](https://user-images.githubusercontent.com/36221419/35903745-749f8cf8-0c1b-11e8-81ec-cf39597ff6d8.jpg)

![default](https://user-images.githubusercontent.com/36221419/35903762-7fed06d0-0c1b-11e8-8bd0-8f1598e90ba3.jpg)

When I use "aggregate" to create graph from cacti 1.1.24, I can't up or down any items.
![image](https://user-images.githubusercontent.com/36221419/35904178-233987f4-0c1d-11e8-920e-510fd5b196c6.png)

![image](https://user-images.githubusercontent.com/36221419/35904228-569dcd08-0c1d-11e8-90c9-c54a5fc7fb5e.png)

Kind regards
thanks
Joel

**Comment by pautiina** [comment]
Go to you cacti setings and look for option `Graph/Data Source Creation Method` it must be set for **advansed**
![image](https://user-images.githubusercontent.com/11805503/35904557-2f1fe99a-0bec-11e8-8ebc-517a799a0ee4.png)

**Comment by netniV** [comment]
Thanks @pautiina  

@joellin If the above worked, can you make this as closed.

This is just my opinion but I think of the advanced method as the old way of doing things.  If you can, I would stick to using New Graphs (simple) as the method of creating things to ensure proper correlation and reduced issues.

**Comment by cigamit** [comment]
Nice graph though.
