### ISSUE TITLE
Cacti Develop Branch - Realtime not working

### ISSUE THREAD

**Issue by anarkia1976** [Cacti/cacti#1315]
I have this error when i try to use it:

2018/02/07 09:41:48 - DBCALL ERROR: SQL Assoc Failed!, Error: Unknown column 'Array' in 'where clause'
--
2018/02/07 09:41:48 - DBCALL ERROR: SQL Assoc Failed!, Error:1054,  SQL:'SELECT *    FROM poller_item    WHERE host_id = ?    AND  local_data_id IN(Array)'
2018/02/07 09:41:48 - CMDPHP PHP ERROR NOTICE Backtrace:  (/cmd_realtime.php: 182 implode)(CactiErrorHandler)(/lib/functions.php:  4524 cacti_debug_backtrace)
2018/02/07 09:41:48 - ERROR PHP NOTICE: Array to string conversion in file: /usr/share/cacti/cmd_realtime.php  on line: 182

2018/02/07  09:44:42 - CMDPHP SQL Backtrace: (/cmd_realtime.php: 183  db_fetch_assoc_prepared)(/lib/database.php: 401 cacti_debug_backtrace)
--
2018/02/07 09:44:42 - DBCALL ERROR: SQL Assoc Failed!, Error: Unknown column 'Array' in 'where clause'
2018/02/07 09:44:42 - DBCALL ERROR: SQL Assoc Failed!, Error:1054,  SQL:'SELECT *    FROM poller_item    WHERE host_id = ?    AND  local_data_id IN(Array)'
2018/02/07 09:44:42 - CMDPHP PHP ERROR NOTICE Backtrace:  (/cmd_realtime.php: 182 implode)(CactiErrorHandler)(/lib/functions.php:  4524 cacti_debug_backtrace)
2018/02/07 09:44:42 - ERROR PHP NOTICE: Array to string conversion in file: /usr/share/cacti/cmd_realtime.php  on line: 182

**Comment by pautiina** [comment]
I confirm.

**Comment by netniV** [comment]
So, PHP is saying that $local_data_ids is an array at line 182:
```php
local_data_id IN(' . implode(',', $local_data_ids) . ')
```

Which is true because at line 137 we have:
```php
$local_data_ids = array(
        'local_data_ids' => $local_data_ids
);
```
This is basically making the $local_data_ids an array of itself.  But this means we have an array of an array because way back up at line 71, we read $local_data_ids from the database so this is an array of SQL row data
```php
/* get poller_item for graph_id */
$local_data_ids = db_fetch_assoc_prepared('SELECT DISTINCT dtr.local_data_id, dl.host_id
        FROM graph_templates_item AS gti
        LEFT JOIN data_template_rrd AS dtr
        ON gti.task_item_id=dtr.id
        LEFT JOIN data_local AS dl
        ON dl.id=dtr.local_data_id
        WHERE gti.local_graph_id = ?
        AND dtr.local_data_id IS NOT NULL',
        array($graph_id));
```

In commit 5948a7874519a0372940381fb85c33a98ce6f312 @cigamit changed the coding to work better with remote pollers as per #993 but I think the problem is the line 137 should be:
```php
$local_data_ids = $idbyhost[$host_id];
```

**Comment by netniV** [comment]
Try this patch to see if it works for you, if so I'll submit the PR:
```diff
diff --git a/cmd_realtime.php b/cmd_realtime.php
index b8a3d13..12a8c59 100644
--- a/cmd_realtime.php
+++ b/cmd_realtime.php
@@ -85,6 +85,7 @@ if (!count($local_data_ids)) {

 $ids   = array();
 $hosts = array();
+$idbyhost = array();
 foreach ($local_data_ids as $row) {
        $ids[$row['local_data_id']]  = $row['local_data_id'];
        $hosts[$row['host_id']]      = $row['host_id'];
@@ -134,9 +135,12 @@ if (sizeof($idbyhost)) {
                        FROM host
                        WHERE id = ?', array($host_id));

-               $local_data_ids = array(
-                       'local_data_ids' => $local_data_ids
-               );
+               if (!array_key_exists($host_id,$idbyhost)) {
+                       cacti_log('ERROR: Failed to find local data ids for host '.$host_id,false,'REALTIME')
+                       continue;
+               }
+
+               $local_data_ids = $idbyhost[$host_id];

                if ($col_poller_id > 1) {
                        $hostname = db_fetch_cell_prepared('SELECT hostname
```

**Comment by pautiina** [comment]
I cannot apply you patch. Patch rejected.

**Comment by pautiina** [comment]
Ok, I have test you propose code but Realtime not working and on clog I don't have any error message about Realtime.

**Comment by cigamit** [comment]
I've fixed this, won't be able to commit till off hours CDT (US).

**Comment by pautiina** [comment]
@cigamit thanks for information

**Comment by cigamit** [comment]
Resolved now. There are actually two fixes here.  Should work with remote data collectors now much better too.

**Comment by cigamit** [comment]
Commit is here: https://github.com/Cacti/cacti/commit/8e7b84963dcb4cc67114beb4c8d784a7ac500d94

**Comment by anarkia1976** [comment]
It's working very good now. thanks a lot.
