### ISSUE TITLE
CDEF Item Value dialog doesn't update creating items

### ISSUE THREAD

**Issue by k4y53r** [Cacti/cacti#1316]
Hi,

When you try to create items on CDEF function, the field for CDEF Item Value doesn't refresh after select CDEF Item Type, always shows options for "function"

Fails on Firefox, IE and Chrome

It shows error below on Firefox debug console:
SyntaxError: expected expression, got ';'

DOMEval
http://CACTI_IP/cacti/include/js/jquery.js:82:3
domManip
http://CACTI_IP/cacti/include/js/jquery.js:5788:8
append
http://CACTI_IP/cacti/include/js/jquery.js:5924:10
html/<
http://CACTI_IP/cacti/include/js/jquery.js:6018:5
access
http://CACTI_IP/cacti/include/js/jquery.js:3981:5
html
http://CACTI_IP/cacti/include/js/jquery.js:5985:10
loadPage/<
http://CACTI_IP/cacti/include/layout.js:1212:5
fire
http://CACTI_IP/cacti/include/js/jquery.js:3317:11
fireWith
http://CACTI_IP/cacti/include/js/jquery.js:3447:7
done
http://CACTI_IP/cacti/include/js/jquery.js:9272:5
callback/<
http://CACTI_IP/cacti/include/js/jquery.js:9514:9

I coud edit existing cdef items, only fail to create new items

Tested on Cacti v 1.1.33 and 1.1.31

**Comment by cigamit** [comment]
Should be resolved in latest develop.  Update cdef.php.  If resolved, please close.

**Comment by k4y53r** [comment]
Ok, i'll check it, thanks

**Comment by k4y53r** [comment]
Checked with 1.1.34 and works fine

Thanks again :)
