### ISSUE TITLE
FrontEnd + Remote Poller - Connection timeout issue

### ISSUE THREAD

**Issue by anarkia1976** [Cacti/cacti#1319]
The network infrastructure is as follows:
Frontend (Centos 7.4.1708) --> MPLS (private net point-to-point) --> Poller (Centos 6.9 Final)

Frontend
Centos 7.4.1708
PHP 5.4.16
Apache/2.4.6
mysql  Ver 15.1 Distrib 10.1.31-MariaDB
NET-SNMP version:  5.7.2

Poller
Centos 6.9 Final
PHP 5.5.38
Apache/2.2.15
mysql  Ver 15.1 Distrib 10.1.30-MariaDB
NET-SNMP version:  5.5

On some occasions when creating or modifying a device we have the following error:
2018/02/08 10:34:58 - CMDPHP PHP ERROR WARNING Backtrace: (/host.php: 123 api_device_ping_device)(/lib/api_device.php: 403 file_get_contents)(CactiErrorHandler)(/lib/functions.php: 4519 cacti_debug_backtrace)
2018/02/08 10:34:58 - ERROR PHP WARNING: file_get_contents(https://192.168.1.10/cacti/remote_agent.php?action=ping&host_id=1167): failed to open stream: HTTP request failed! in file: /usr/share/cacti/lib/api_device.php on line: 403

The browser remains in hang and never finishes availability/reachability.

The only way to unlock the situation is a restart of the apache server. 

the strange thing is that all the other web services on the server continue to work properly and only the cacti crashes.

Thanks a lot.

**Comment by netniV** [comment]
The common solution to this when searching would be to use curl in a function like:
```php
[__b__]function file_get_contents_curl($url) {
$ch = curl_init();
curl_setopt($ch, CURLOPT_HEADER, 0);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1); //Set curl to return the data instead of printing it to the browser.
curl_setopt($ch, CURLOPT_URL, $url);
$data = curl_exec($ch);
curl_close($ch);
return $data;
}
```
However, I know that @cigamit said just recently that moving to curl isn't an option at the moment.

**Comment by anarkia1976** [comment]
I have read about this.
The problem for us is given by the fact that the server is also used by people who do not have the bases to manage low-level systems and perform restart of services.
I look forward to if you can make some fixes.
thanks

**Comment by netniV** [comment]
The other question is whether it's just a simple timeout related issue.  Can you run tests from the main server to that url using curl or wget at the command line?  If you repeat the request a bunch of times, do you see any errors?

For example, I have been looking at a different issue with JSON graph images and it seems the server being called isn't returning data properly which was shown by doing 100 requests concurrently.

**Comment by anarkia1976** [comment]
When it works we have immediatly a response:
XXXXX - (ASA) (93.63.194.3)
SNMP Information
System SNMP error - SNMP::get(): No response from 93.63.194.3

if it happens I will follow your advice to test through curl / wget, I keep you updated.

**Comment by anarkia1976** [comment]
Just an update, if it happen also for exmaple realtime didn't working:

2018/02/08 12:00:15 - CMDPHP PHP ERROR WARNING Backtrace: (/cmd_realtime.php: 158 file_get_contents)(CactiErrorHandler)(/lib/functions.php: 4519 cacti_debug_backtrace)
2018/02/08 12:00:15 - ERROR PHP WARNING: file_get_contents(https://x.x.x.x/cacti//remote_agent.php?action=polldata&host_id=1728&local_data_ids%5B0%5D=1532&local_data_ids%5B1%5D=1531&poller_id=4vebpsdrupdnrogadu42u7pe73): failed to open stream: HTTP request failed! in file: /usr/share/cacti/cmd_realtime.php on line: 158

Only apache restart fix the problem temporarily.

**Comment by netniV** [comment]
https://stackoverflow.com/questions/47265936/phps-file-get-contents-provokes-crash would seem to suggest that there is a chance of that happening.  Again, the only suggestion there was cURL, but that will need to wait for @cigamit  to weigh in.

**Comment by cigamit** [comment]
Well, there are other suggestions to set the context timeout that effectively do the same thing.  The question is, do we want to have any retries attempted.  So, back to @anarkia1976, is this intermittent, of if the connection fails, should we simply report something like 'unable to reach remote collector (you have a shitty overloaded circuit right now)'.

**Comment by netniV** [comment]
We would have to be careful there, since we already have retry logic when communicating with the actual device?  Also, it sounds like we aren't getting back from file_get_contents as apache2 locks up or am I missing something there?

**Comment by cigamit** [comment]
Okay, this should be resolved now.  Make sure you are at 1.1.34, and then apply the six files from the develop branch.

**Comment by cigamit** [comment]
Close is satisfied.  There was a timeout, but it could have been pretty large.  Plus there is an option to ignore errors, and I enabled it.  I've suppressed the error messages for now.

**Comment by anarkia1976** [comment]
Thanks  a lot. Patch under testing. i keep you posted.

**Comment by anarkia1976** [comment]
Very good, all seem ok now, overall interface is superfast. Thanks a lot.
I have a small donation to Cacti paypal account from my personal budge (sorry it's not much).
