### ISSUE TITLE
Enhance form layout for readability

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1323]
I think the Change Settings screen is a little unintuitive because it forces you to tick the box below the option that you are wanting to set.  Worse, you might miss the fact that you have to tick that box because you can change the setting and continue on down the screen.  

The enhancement to this would be to moving the tick box to the left of the option text, and disabling the value entry so that nothing can be changed until that option has been ticked.  This would also remove the need to repeat the "Update this field" text making the entire set of options a lot shorter and more visible on the screen at the same time.

**Comment by cigamit** [comment]
Screen shots will help your description a bit.  I'm at a loss.  Could be my current state of mind.  Not sure.

**Comment by cigamit** [comment]
I'm good with that, can you have it done by Sunday?  Rony will do 1.1.35 on Sunday.

**Comment by netniV** [comment]
![image](https://user-images.githubusercontent.com/9052188/36006330-2778cc40-0d34-11e8-8404-f83c77570267.png)

No, think it will have to wait for 1.1.36 or later.  I'm working solid this weekend unless something changes on Tuesday.

**Comment by cigamit** [comment]
Need a title attribute __('Update this field');

**Comment by netniV** [comment]
Over the checkbox, or over the disabled controls, or both?

**Comment by cigamit** [comment]
Checkbox I think.  Or if the whole div, then __('Click the checkbox to update this field');

**Comment by cigamit** [comment]
I might be able to knock it out in a few minutes.  I can not remember if this thing is some of that old code where everything was done by hand, or if it's controlled by an API.  Let me take a peak.

**Comment by cigamit** [comment]
Okay, this is an API change.  So 'might' be easy.  Depends on whether or not it can be done without CSS changes.

**Comment by cigamit** [comment]
Was not all that difficult...

**Comment by cigamit** [comment]
Okay, done.  Being that it's leveraging the API, bot the Data Templates and the Graph Templates benefited from this change also.  Makes the pages quite a bit more compressed.
![changedevicesettings](https://user-images.githubusercontent.com/957322/36008526-4c68a088-0d0d-11e8-895b-fd72e3b1168d.PNG)
![graphtemplates](https://user-images.githubusercontent.com/957322/36008527-4f14f1e2-0d0d-11e8-8eae-69df044b9df4.PNG)
![datatemplates](https://user-images.githubusercontent.com/957322/36008531-517ab6a6-0d0d-11e8-8117-93d079304cfd.PNG)

**Comment by cigamit** [comment]
Close if good.

**Comment by netniV** [comment]
The only thing I think it needs is to disable the value input unless checked. But I haven’t tested yet. Will do later.

**Comment by anarkia1976** [comment]
Very good guys, now it's superclean. thanks.

**Comment by netniV** [comment]
So I have been so impressed with the above, I decided to add the disable options myself.  However, this does require a CSS and JS change (unless you have a functions somewhere else that does the same job).

**Comment by netniV** [comment]
@anarkia1976 Do you fancy testing this latest patch?  You should be able to see a visual difference in the greyed out input fields and the inability to actually click on them.

**Comment by netniV** [comment]
Meh, just thought I'd hunt around to see the differences on different sections.  It all looks good until I found a problem with these changes in graph_template_inputs.php (probably just needs the api updating):

![screen shot 2018-02-09 at 09 35 22](https://user-images.githubusercontent.com/9052188/36021122-bf1f5dfa-0d7c-11e8-8e81-40ae248da738.png)

**Comment by anarkia1976** [comment]
Sorry, but until monday i can't test new patches. :)

**Comment by cigamit** [comment]
This is why we need to test more before release ;)

**Comment by cigamit** [comment]
The Graph Item Inputs.  That whole screen has been a thorn in my side for a decade.  It's very confusing, but was important in the past as it helped you 'fix' some things, but no one should ever have to see it.  It's dangerous.  I'll fix this new issue, but we really need to think about making it less incomprehensible.

**Comment by netniV** [comment]
On the testing front, I was reading about a headless chrome that you can automate through the website.  If we created a script that produced screenshots and notified about differences in layouts at the end of a day when there was development change (timezone?) that could also help.

**Comment by cigamit** [comment]
Well, that would be so awesome!

**Comment by cigamit** [comment]
Okay, I've got the graph_templates_inputs.php squared away. Converted the Associated Graph Items to a table to take up less space.

**Comment by netniV** [comment]
The styling that I proposed on #1325 does work against this form.  Not sure if that matters or not.

**Comment by cigamit** [comment]
Show me some screen shot's of what you propose, I'm off to the day job.  We have till Sunday night EST to work things out.

**Comment by netniV** [comment]
I merely mean that it doesn't disable the input field.  Also, the onChange of the checkbox probably isn't assigned since it's writing it's own checkbox.  I am assuming that the checkbox is to enable use of the field to the left on data_template_input? If not, may need some table headers for explanation.

**Comment by cigamit** [comment]
Okay, I've implemented this in host.php specifically.  We can think of a more generic approach for 1.2.  Look over how I implemented this and feel free to continue the discussion here for now.  Can you see the projects tab on the GitHub gui by the way.  We should be opening projects for large scale gui improvement there.  It's better to have those conversations there.

**Comment by netniV** [comment]
Yes, I can see there are two projects open there.

**Comment by cigamit** [comment]
Great, if you come across additional ideas, and you can create projects, start creating them there.  We can first kick the can there, and then open the issue once we have figured out the right path.

**Comment by netniV** [comment]
Oh, whilst I can see, I can't create, modify etc.

**Comment by cigamit** [comment]
Okay, I'll mention that to Rony tomorrow.
