### ISSUE TITLE
Search for the word "disk" in graphs or data sources turns to regex

### ISSUE THREAD

**Issue by stormonts** [Cacti/cacti#1326]
When I try and search for the word "disk" Cacti changes it to "v+$" once you hit enter or the Go button.  We are running version 1.1.33.

![image](https://user-images.githubusercontent.com/25824323/36030746-5c5ade52-0d76-11e8-8b88-0e7df0ca82d3.png)

**Comment by netniV** [comment]
This has already been fixed in 1.1.34 as part of #1268, so please close this and upgrade.

**Comment by browniebraun** [comment]
Currently I only have version 1.1.34 to test, but there it works faultlessly.

**Comment by browniebraun** [comment]
*lol*

**Comment by netniV** [comment]
I know, the timing on that 👍

**Comment by browniebraun** [comment]
rt ;)
