### ISSUE TITLE
Update Device Template Packages to latest version

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1327]
So I just did a fresh install of the 1.2.x branch to work on the scheduler next week, and noticed straight away that there is a difference between the source ss_host_cpu.php and after the final steps of the install. Presumably this is one of the packages that is updating the data so we need to make sure that they are all consistent.

**Comment by cigamit** [comment]
I've resolved this by updating the device template packages in the develop branch to version 1.1.35.  Once I merge this back to the 1.2 branch, this issue should be resolved.
