### ISSUE TITLE
Data Query Cache search does not include indexes

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1333]
When searching the Data Query Cache Items, it would appear that the index column isn't included in the search.  I tried to search for an index '1073741827.0' and it brought up 

![image](https://user-images.githubusercontent.com/9052188/36100591-ae7d33a8-0ffe-11e8-9969-1d2cc4010c3c.png)

However, if you remove the search filter and use the browser search feature, you can see there are more.

![image](https://user-images.githubusercontent.com/9052188/36100503-5fac4fc0-0ffe-11e8-90ea-4a485e1c0d40.png)

**Comment by cigamit** [comment]
This should not be too difficult to fix.

**Comment by cigamit** [comment]
I'm fine with that.  Take a look at it.  If it's just a few lines to add additional WHERE clauses, it can make it to the 1.1.36.  Do the change, create a pull, and then I will assess it.

**Comment by cigamit** [comment]
This issue is resolved now.  I changed the layout to better align with the Poller Cache pick.  Too much was crammed on the one filter line.  So, it's two now.

**Comment by netniV** [comment]
I'll take a look but yeah makes sense from what you're saying :)
