### ISSUE TITLE
Debian test suite reports php errors

### ISSUE THREAD

**Issue by paulgevers** [Cacti/cacti#1336]
Several php errors appear in the syslog when I run the Debian test suite on a fresh Cacti installation. The Debian test suite runs a recursive wget on index.php.

```
02/12/2018 21:25:25 - ERROR PHP WARNING: ini_set(): Cannot change zlib.output_compression - headers already sent in file: /usr/share/cacti/site/lib/import.php  on line: 144
02/12/2018 21:25:25 - CMDPHP PHP ERROR WARNING Backtrace: (/usr/share/cacti/cli/import_package.php: 119 import_package)(/lib/import.php: 144 ini_set)(CactiErrorHandler)(/lib/functions.php: 4619 cacti_debug_backtrace)
02/12/2018 21:25:35 - ERROR PHP WARNING: ini_set(): Cannot change zlib.output_compression - headers already sent in file: /usr/share/cacti/site/lib/import.php  on line: 144
02/12/2018 21:25:35 - CMDPHP PHP ERROR WARNING Backtrace: (/usr/share/cacti/cli/import_package.php: 119 import_package)(/lib/import.php: 144 ini_set)(CactiErrorHandler)(/lib/functions.php: 4619 cacti_debug_backtrace)
02/12/2018 21:26:03 - ERROR PHP WARNING: ini_set(): Cannot change zlib.output_compression - headers already sent in file: /usr/share/cacti/site/lib/import.php  on line: 144
02/12/2018 21:26:03 - CMDPHP PHP ERROR WARNING Backtrace: (/usr/share/cacti/cli/import_package.php: 119 import_package)(/lib/import.php: 144 ini_set)(CactiErrorHandler)(/lib/functions.php: 4619 cacti_debug_backtrace)
02/12/2018 21:26:46 - ERROR PHP WARNING: ini_set(): Cannot change zlib.output_compression - headers already sent in file: /usr/share/cacti/site/lib/import.php  on line: 144
02/12/2018 21:26:46 - CMDPHP PHP ERROR WARNING Backtrace: (/usr/share/cacti/cli/import_package.php: 119 import_package)(/lib/import.php: 144 ini_set)(CactiErrorHandler)(/lib/functions.php: 4619 cacti_debug_backtrace)
02/12/2018 21:27:28 - ERROR PHP NOTICE: Undefined variable: config in file: /usr/share/cacti/site/data_source_profiles.php  on line: 977
02/12/2018 21:27:28 - CMDPHP PHP ERROR NOTICE Backtrace: (/data_source_profiles.php: 93 profile)(/data_source_profiles.php: 977 CactiErrorHandler)(/lib/functions.php: 4624 cacti_debug_backtrace)
```

**Comment by netniV** [comment]
The ZLIB error must be to do with the change in bebbb7f8ed1ca0a42eab36178776927910b816a5 which was implmented to stop some packaging problems.  

The $config being missing in data_source_profiles.php is more worrying.  Do you know what URL was used that page which generated the error?

**Comment by netniV** [comment]
Actually, I think I have already narrowed it down to $config not being in the global line at the top of the `profile()` function

**Comment by netniV** [comment]
Has this error not appeared before? I find that strange because the last few commits for that file does not seem to have changed the global line for that function.

**Comment by paulgevers** [comment]
@netniV the Debian test suite has failed the for the last Cacti, the previous one that was packaged was 1.1.31 which didn't show this IIRC.

Most recently due to "nofollow" being added to the headers.

**Comment by netniV** [comment]
I'll check the differences between that release and now.

**Comment by netniV** [comment]
OK, I can see that between .31 and .35 the function was updated to include lines that reference $config but the global wasn't.  In fact, it is the latest commit https://github.com/Cacti/cacti/commit/eb1eae4c34f21719d8924b2de3358b5972e9fd8b#diff-0b849c1ddd18d07e343434a299b10ad1 that has this in.

I've now created a pull request for this.

**Comment by cigamit** [comment]
After some research, it turns out that though the zlib compression option should be read-writable, that in some cases it becomes read only.  So, we will have to use a different method to guarantee that the compression and decompression of packages is consistent.

**Comment by cigamit** [comment]
This issue is resolved now.  Paul is there a way your test could be added to our Travis audits?  It would really help to have that done here first.

**Comment by cigamit** [comment]
I reviewed your test-all-pages script.  Very nice.  Can we 'borrow' that for our Travis tests?

**Comment by paulgevers** [comment]
@cigamit, yes, feel free to use it and improve it. My work on the Debian package is licensed under GPL-2+ like nearly everything in the Cacti source.

If you include it in the source, I'll even drop it from the Debian specific part of the package and just call your test. Do you have more tests, that I could run as well in Debian?

**Comment by netniV** [comment]
I have been considering running this script or at least parts of it against other OS's as well.  One thing I did notice was that under Debian/Ubuntu, even if the user does not select templates to install at the end of the GUI installation process, they are already imported by the Debian scripts so an initial device is automatically created.

This may be another example of where we should have a project to guide what we do since on other platforms, unless they run the same commands, most other systems will not have the templates by default etc. so there's a difference in the experience when using all defaults.

https://forums.cacti.net/viewtopic.php?f=21&t=58444

```bash
# Only create common files (logfile) and grant permissions on first install
if [ ! -n "$2" ] ; then
    touch /var/log/cacti/rrd.log /var/log/cacti/cacti.log /var/log/cacti/poller-error.log
    chmod 0640 /var/log/cacti/rrd.log /var/log/cacti/cacti.log /var/log/cacti/poller-error.log
    chown -R www-data:www-data /var/log/cacti/

    # Check if
    # - the admin wanted dbconfig to help
    # - there is a password to use
    # - if the dbconfig installation went ok (e.g. no noninteractive fail)
    #   see also bug 822945
    if [ "$dbc_install" = "true" ] && [ -n "$dbc_dbpass" ] && [ "${_dbc_on_error_option}" != "ignore" ] ; then
        # An upstream clean install has a well-known admin password and
        # triggers a change before one can continue. However, on Debian we
        # already have a good password that we can communicate to the admin, so
        # make the setup safe from the start.
        dbc_mysql_exec_command "UPDATE user_auth SET password=md5('$dbc_dbpass'), must_change_password='' WHERE id=1"

        # An upstream clean install triggers some questions before you can use
        # Cacti for the first time. However, on Debian that should already be
        # alright. Prevent triggering these questions by filling the latest
        # version number into the database.
        cacti_upstream_ver=$(dpkg-query -f '${Version}' -W 'cacti' | sed s/\+ds[0-9]-.*//)
        dbc_mysql_exec_command "UPDATE version SET cacti='$cacti_upstream_ver'"

        # Until now (2016-04-01) the versions of rrdtool in Cacti are always of
        # the form rrd-[0-9].[0-9].x, so let's assume that.
        rrd_ver=$(dpkg-query -f '${Version}' -W 'rrdtool')
        dbc_mysql_exec_command "INSERT INTO settings SET name='rrdtool_version', value='rrd-${rrd_ver%%[0-9]-*}x'"

        # Since cacti version 1.0.0, by default there aren't any templates
        # loaded anymore which leaves an empty experience. More so because
        # there is no web interface that tells you of the existence, nor is
        # able to load the "packages". So let's load the default ones here.
        #
        # Because we want to keep the debsums checksums constant, we don't
        # actually want to change the scripts (they are not equal, see
        # https://github.com/Cacti/cacti/issues/810). So, make sure we run
        # these commands as the www-data user, because that can execute the
        # MySQL calls, but can't change the files (and that is OK).
        echo -n "Loading default cacti templates (may take some time)."
        su --shell /bin/sh www-data -c "/usr/share/cacti/cli/import_package.php \
            --filename=/usr/share/cacti/site/install/templates/Local_Linux_Machine.xml.gz" > /dev/null
        echo -n "."
        su --shell /bin/sh www-data -c "/usr/share/cacti/cli/import_package.php \
            --filename=/usr/share/cacti/site/install/templates/Generic_SNMP_Device.xml.gz" > /dev/null
        echo -n "."
        su --shell /bin/sh www-data -c "/usr/share/cacti/cli/import_package.php \
            --filename=/usr/share/cacti/site/install/templates/NetSNMP_Device.xml.gz" > /dev/null
        echo -n "."
        su --shell /bin/sh www-data -c "/usr/share/cacti/cli/import_package.php \
            --filename=/usr/share/cacti/site/install/templates/Cisco_Router.xml.gz" > /dev/null
        echo "  done."

        # And since we don't pass through the install script anymore, we need
        # to rebuild the poller cache now (but suppress normal output as it
        # looks scary during install).
        php /usr/share/cacti/cli/rebuild_poller_cache.php > /dev/null
    fi
fi

# Make sure the database is up-to-date
if [ -n "$2" ] ; then
    { echo "Running cli/upgrade_database.php as part of package update..." ; \
      php /usr/share/cacti/cli/upgrade_database.php ; } | \
        if [ -f /usr/bin/ts ] ; then LC_TIME=C ts "%m/%d/%Y %I:%M:%S %p" | tee -a /var/log/cacti/cacti.log ; \
        else tee -a /var/log/cacti/cacti.log ; fi
fi
```

Personally, I don't think that is a bad thing, because having something there to look at makes sense, I just wonder if we should actually enable the import by default so a user clicking next next next, doesn't miss it

**Comment by cigamit** [comment]
Good point @netniV.  There are a a number of things that I would like to test beyond this too.

On the package front topic, in the very near future, maybe as early as 1.3, when we plan to release the pakcage plugin, I would like to allow users to obtain a somewhat validated list of packages from either GitHub or the Cacti web site, and add those packages to the list of available packages to install at install time.  The same would apply to plugins.

**Comment by cigamit** [comment]
Thanks @paulgevers.  One thing at a time ;)
