### ISSUE TITLE
Allow automation to be run in debug mode from GUI

### ISSUE THREAD

**Issue by jhonnyx82** [Cacti/cacti#1338]
Hi,

This is just a small change request: it can be useful to add a "verbose" or "debug" option for the networks scans that are ran from the GUI as it can show a lot of information on why a device was not added to CACTI, currently is only possible from CLI.

Thanks a lot

**Comment by netniV** [comment]
This is a feature request so will likely be scheduled for one of the milestone releases.

**Comment by cigamit** [comment]
My hopes is for 1.1.36 to be the last point release in the 1.1.x series.  We have a number of enterprise features that have waited too long.

**Comment by cigamit** [comment]
I've tested this.  Nice work.
