### ISSUE TITLE
status of ongoing issue

### ISSUE THREAD

**Issue by chathurag** [Cacti/cacti#1341]
Could anyone update the status of issue #1200 

This was not resolved in 1.1.35

**Comment by netniV** [comment]
As per #1342, there is no point creating additional issues for existing ones.  Please comment on the existing issues for full tracability.

**Comment by chathurag** [comment]
No one is answering previous issue . thats why I have opened new issue

**Comment by netniV** [comment]
The answer was on that issue, it's in the pipeline. Not a top priority at the moment.  You would have had the same answer if you posted this on that issue.

**Comment by chathurag** [comment]
@netniV - This is much important feature to us that's why we are requesting to make it priority
according to @cigamit  this was disabled intentionally but I don't see any harm that could do. If anyone doesn't want to use it they may left as it is.

By the way as its not resolved yet can anyone provide us temporary solution, that would be much appreciated.
