### ISSUE TITLE
cacti1.1.33 I want to create new CDEF items  "Custom String " but  I can't write down the text  cdefa or cdeb ?? WHY?

### ISSUE THREAD

**Issue by joellin** [Cacti/cacti#1343]
HI 
I use cacti 1.1.33
I have a question, when I want to create new CDEF items  "Custom String " but  I can't write down the text  cdefa or cdeb ..........?? WHY?
The Drop-down menu shows SIN? LOG?EXP?FLOOR?CEIL?@#$!%!....... 
I really don't understand, somebody can help me ?? 
Thanks  

![image](https://user-images.githubusercontent.com/36221419/36153570-a6874b14-1109-11e8-8c70-f4f4fd603dac.png)

**Comment by cigamit** [comment]
Update to 1.1.35.  This was resolved there.
