### ISSUE TITLE
[Question] OID to SNMPv2-TC DisplayString via Data Queries XML?

### ISSUE THREAD

**Issue by thecityofguanyu** [Cacti/cacti#1352]
Is it possible to use a data queries XML file to convert octets of an OID to DisplayString? 

I'm working with a sequence table defined in a device's MIB. That table has uniquely indexed and named items. The problem is that the table does not have a dedicated OID to output the index item's "name" as the value for a given OID. Instead, the name is just inside of the OID in numeric form.

Example OID that I am working with:

```
PERIMETA-MIB::adjStatSrcActivatingCalls."testAdjacency".summaryPeriod1Current5Minutes 1
```

After referencing some of the data query documentation, I was able to get basically what I'm looking for here in terms of indexing:

```xml
<interface>
        <name>Get Perimeta Adjacency Stats</name>
        <description>Queries a host for a list of Perimeta SBC Adjacency Stats</description>
        <oid_index>.1.2.826.0.1.1578918.8.3.2.1.11</oid_index>
        <oid_index_parse>OID/REGEXP:^.{31}(.*)</oid_index_parse>
        <index_order>vsIndex</index_order>
        <index_order_type>alphabetic</index_order_type>
        <fields>
                <vsIndex>
                        <name>Index</name>
                        <source>index</source>
                        <direction>input</direction>
                </vsIndex>
```

The issue now is that, although the values are now properly indexed, I only have index numbers to go off of when selecting a data source from the Cacti WebUI. And sadly, I cannot do the OID->DisplayString conversions in my head. 

My solution was to (hopefully) take that same `OID/REGEXP:^.{31}(.*)` that I am using to index, and then convert it to a DisplayString for use as another "input" item -- to the effect of...

``` xml
                <adjName>
                        <name>Adjacency Name</name>
                        <method>walk</method>
                        <source>OID/REGEXP:^.{31}(.*)</source>
                        # unknown thing that would hopefully convert to DisplayString Textual Convention
                        <direction>input</direction>
                        <oid>.1.2.826.0.1.1578918.8.3.2.1.11</oid>
                </adjName>
```

Is my goal here something that is achievable?

**Comment by netniV** [comment]
Do you have an snmpwalk to show this in effect? It’s just not really sticking in my head from your description above.  I think I understand what you are after but not quite.  And if it’s what I think, you may need to look at using script_server or a script query to generate the value.

**Comment by thecityofguanyu** [comment]
Sorry about that. I have a tendency to be a little wordy.

Here is a walk:

```
~/ snmpbulkwalk -Oq -v2c -c public 10.9.38.10  -M ~/mibs:/tmp/mibs -m ALL perimetaAdjacencies
PERIMETA-MIB::perimetaAdjacencyNumber 79
PERIMETA-MIB::adjStatSrcActiveCalls."ANI".summaryPeriod1Current5Minutes 6
```

And here is the same walk with `-On` instead of `Oq`:

```
.1.2.826.0.1.1578918.8.3.1 = Gauge32: 79
.1.2.826.0.1.1578918.8.3.2.1.11.3.65.78.73.1 = Counter64: 6
```

I want to take ".3.65.78.73" from the OID and convert it to "ANI".

**Comment by cigamit** [comment]
As @netniV states, we need some walk data.  Also, this is better suited for the Forums.  However, with that said, we will keep this open for a bit.

**Comment by thecityofguanyu** [comment]
>As @netniV states, we need some walk data.

Was the walk data from my previous comment not enough? If not, I'll run a full walk and sanitize/paste the full output. I can also provide the MIB. 

> Also, this is better suited for the Forums.

Sorry. I asked in IRC and didn't much direction, so I posted here before it slipped my mind. I'll remember to use the forum for future inquiries.

**Comment by cigamit** [comment]
Technically, you can use the OID/REGEXP:, you will have to trim away the base values leaving behind the ASCII characters, and the index on the end.  Cacti will, scan the remaining characters, and if they are all in the printable ASCII range (between 31 and 127) it will represent the remaining octets as ASCII text automatically.

So, there are a few things you have to consider:

1) Method has to be walk.
2) If you need to preprocess  the index, you need to add the `<oid_index_parse>` must be a valid REGEX that returns the index from the walk value
3) Use `<source>` value of `OID/REGEXP:regular_expression` to strip away the prefix leaving only the ASCII portion and the index at the very end.
4) Test, test again, and eventually be an expert.

If you want to review the code, it's lib/data_query.php starting at line 694.  This should be enough to go on right?

**Comment by thecityofguanyu** [comment]
@cigamit thanks for the feedback!

Unless I'm misreading something, I believe that my .xml file was already in line with what you outlined in your bullet points -- method is walk, index is pre-processed, source as OID/REGEXP:regex is stripping away prefix. Unfortunately, Cacti does not seem to be representing those octets as ascii. See screenshot below.

![screenshot](https://i.imgur.com/WuYj4Gi.png)

My full data query XML file:

```xml
<interface>
        <name>Get Perimeta Adjacency Stats</name>
        <description>Queries a host for a list of Perimeta SBC Adjacency Stats</description>
        <oid_index>.1.2.826.0.1.1578918.8.3.2.1.11</oid_index>
        <oid_index_parse>OID/REGEXP:^.{31}(.*)</oid_index_parse>
        <index_order>vsIndex</index_order>
        <index_order_type>alphabetic</index_order_type>
        <fields>
                <vsIndex>
                        <name>Index</name>
                        <source>index</source>
                        <direction>input</direction>
                </vsIndex>
                <adjName>
                        <name>Adjacency Name</name>
                        <method>walk</method>
                        <source>OID/REGEXP:^.{31}(.*)</source>
                        <direction>input</direction>
                        <oid>.1.2.826.0.1.1578918.8.3.2.1.11</oid>
                </adjName>
                <adjStatSrcActiveCalls>
                        <name>adjStatSrcActiveCalls</name>
                        <method>walk</method>
                        <source>value</source>
                        <direction>output</direction>
                        <oid>.1.2.826.0.1.1578918.8.3.2.1.11</oid>
                </adjStatSrcActiveCalls>
        </fields>
</interface>
```

Output from Data Query Debug Information within Cacti:

https://paste.debian.net/1010429/

Excerpt from MIB:

https://paste.debian.net/1010424/

Another example walk:

```shell
~/ snmpbulkwalk -v2c -c public 10.9.38.10  -M ~/mibs:/tmp/mibs -m ALL adjStatSrcActiveCalls
PERIMETA-MIB::adjStatSrcActiveCalls."MetasphereCFS2".summaryPeriod1Current5Minutes = Counter64: 6
PERIMETA-MIB::adjStatSrcActiveCalls."MetasphereCFS3".summaryPeriod1Current5Minutes = Counter64: 4
PERIMETA-MIB::adjStatSrcActiveCalls."MetasphereCFS4".summaryPeriod1Current5Minutes = Counter64: 0
PERIMETA-MIB::adjStatSrcActiveCalls."MetasphereCFS5".summaryPeriod1Current5Minutes = Counter64: 0
PERIMETA-MIB::adjStatSrcActiveCalls."MetasphereCFS6".summaryPeriod1Current5Minutes = Counter64: 1
PERIMETA-MIB::adjStatSrcActiveCalls."MetasphereCFS7".summaryPeriod1Current5Minutes = Counter64: 3
PERIMETA-MIB::adjStatSrcActiveCalls."MetasphereCFS8".summaryPeriod1Current5Minutes = Counter64: 1
PERIMETA-MIB::adjStatSrcActiveCalls."MetasphereCFS9".summaryPeriod1Current5Minutes = Counter64: 0

~/ snmpbulkwalk -v2c -On -c public 10.9.38.10  -M ~/mibs:/tmp/mibs -m ALL adjStatSrcActiveCalls
.1.2.826.0.1.1578918.8.3.2.1.11.14.77.101.116.97.115.112.104.101.114.101.67.70.83.50.1 = Counter64: 6
.1.2.826.0.1.1578918.8.3.2.1.11.14.77.101.116.97.115.112.104.101.114.101.67.70.83.51.1 = Counter64: 4
.1.2.826.0.1.1578918.8.3.2.1.11.14.77.101.116.97.115.112.104.101.114.101.67.70.83.52.1 = Counter64: 0
.1.2.826.0.1.1578918.8.3.2.1.11.14.77.101.116.97.115.112.104.101.114.101.67.70.83.53.1 = Counter64: 0
.1.2.826.0.1.1578918.8.3.2.1.11.14.77.101.116.97.115.112.104.101.114.101.67.70.83.54.1 = Counter64: 1
.1.2.826.0.1.1578918.8.3.2.1.11.14.77.101.116.97.115.112.104.101.114.101.67.70.83.55.1 = Counter64: 3
.1.2.826.0.1.1578918.8.3.2.1.11.14.77.101.116.97.115.112.104.101.114.101.67.70.83.56.1 = Counter64: 1
.1.2.826.0.1.1578918.8.3.2.1.11.14.77.101.116.97.115.112.104.101.114.101.67.70.83.57.1 = Counter64: 0
```

**Comment by netniV** [comment]
You need to change the {31} to {34} 👍

**Comment by netniV** [comment]
If you would like to see this in action, check out:
https://regex101.com/r/vYKCeP/1

**Comment by cigamit** [comment]
@thecityofguanyu, have you worked around this yet?

**Comment by thecityofguanyu** [comment]
@netniV I apologize for the delay. Unfortunately, changing from {31} to {34} or {35} did not have any impact on the issue. It still just shows numeric OID octets instead of printing the ASCII DisplayString value.

>You really should try to match against what you expect to ensure you don't get rogue data.

Ideally I would, but I'm not exactly sure how to get more specific than the way the regex is set up now. The strings are names, so they are aren't really "predictable" -- aside from the quotation marks.

**Comment by cigamit** [comment]
Since this conversation has not had an update in 17 days, I'm assuming the user has figured out the proper regex and will close.
