### ISSUE TITLE
PHP Syntax error poller_maintenance.php line 162 on RHEL6.9

### ISSUE THREAD

**Issue by cigamit** [Cacti/cacti#1354]
PHP Parse error: syntax error, unexpected T_OBJECT_OPERATOR in /var/www/html/cacti/poller_maintenance.php on line 162

We need to continue to support RHEL6.  The approach of using DateTime has to be modified to correctly parse.

**Comment by cigamit** [comment]
Resolved.

**Comment by netniV** [comment]
I thought I had commented on this but the reuse of the $date field causes an issue where all date fields will be the same object.  You have to either create a new DateTime object or clone it to be able to modify it without affecting the original.  I have no idea why they return the same object since most languages won't but I think because of that, they created DateTimeImmutable which works the "correct" way of not modifying the original.  However, that has a PHP >= 5.5 requirement and since you still want to support 5.4 we can't use that.

**Comment by cigamit** [comment]
RHEL6.9 is php5.3.3.  So, that makes things even worse.  Committing the fix momentarily.

**Comment by netniV** [comment]
OK, that's why CI didn't fail it.  CI is only going back to 5.4

**Comment by cigamit** [comment]
Well, the agreement with @ronytomen, was RHEL6.9.  But he's likely running Gentoo everywhere so this is why it slipped.  Until now, we never had an issue, so I just let it go.

**Comment by netniV** [comment]
So should we add 5.3.3 to the CI tests to be sure?

**Comment by cigamit** [comment]
Yea, assuming that Travis is supporting them.  I think that might have been the reason that @ronytomen removed it now that I think about it.  Seems like Travis was failing getting the package.

**Comment by ronytomen** [comment]
I can not be more clear about this.  We support PHP 5.4 and higher. 

It is outlined in the documentation.

Testing will not be added.

**Comment by cigamit** [comment]
We also support RHEL6.9 and it's on PHP5.3.3.

**Comment by ronytomen** [comment]
We do not

**Comment by ronytomen** [comment]
PHP 5.4 or greater, pretty simple.

**Comment by netniV** [comment]
You can install 5.4 on RHEL 6.9:
https://doc.owncloud.org/server/8.1/admin_manual/installation/php_54_installation.html

**Comment by cigamit** [comment]
@netniV, good to know.  That will help.  We don't have to support it.  But I will make sure it continues to work until RHEL6 is EOL since that is my primary upgrade/test box.  If we are going to force people onto PHP 5.4, we should provide a link to these instructions.

**Comment by ronytomen** [comment]
It's really not our responsibility to support a version of PHP that was released in 2009 and support was concluded in 2014.  

We should not make compromises in code or modify 3rd party libraries to work with PHP 5.3, if we are doing that we are failing.

**Comment by cigamit** [comment]
Point made, and this is likely why Red Hat provided an update path to PHP5.4 via the document provided by @netniV.  So, I think we are all good.  Maybe we add a comment to the installer pointing to that document if we encounter a RHEL6.x system with PHP5.3 installed.  Until it's EOSL, it does not sound like a bad idea.
