### ISSUE TITLE
Tree mode display devices: first graph not drawn in subsequent pages in 1.35

### ISSUE THREAD

**Issue by gmuellerfr** [Cacti/cacti#1358]
Hello,
since switching to 1.35 I see that the first graph is missing, if I hit the next button or select a page.
 If I change for instance the number of columns, the page will be redrawn and the graph is present, even if I change to the former number of columns. If I hit the page number, I am on, the first graph is missing again.

![cacti-tree-1](https://user-images.githubusercontent.com/25848039/36254655-21ee4012-124c-11e8-86b9-64ace8b7b762.png)

Select Page 1 again

![cacti-tree-2](https://user-images.githubusercontent.com/25848039/36254670-30b9c486-124c-11e8-9d45-4dabb3642d07.png)

Resizing to three columns

![cacti-tree-3](https://user-images.githubusercontent.com/25848039/36254687-3d246d52-124c-11e8-8a9c-3076bdc3419e.png)

Thank you for listening.
Guenter

**Comment by cigamit** [comment]
This has been resolved in the pending 1.1.36 release.  You have to update html_utility.php from the github if you want it before then.

**Comment by gmuellerfr** [comment]
It works,
thank you
