### ISSUE TITLE
Settings page can generate error if expected tab not found

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1359]
```
2018/02/15 16:23:37 - CMDPHP PHP ERROR NOTICE Backtrace: (/settings.php: 216 CactiErrorHandler)(/lib/functions.php: 4624 cacti_debug_backtrace)
--
2018/02/15 16:23:37 - ERROR PHP NOTICE: Undefined index: misc in file: /usr/share/cacti/develop/settings.php on line: 216
```
The above error was generated by removing a plugin (router_configs) which had added the Misc tab of settings  Since there were no longer any misc tab items, the tab is no longer available.  However, clicking back through browser history generates the above error because the tab has now been removed.

**Comment by netniV** [comment]
Recommendation is to change $current_tab to be the first tab if the specified tab name was not found.  Haven't created a patch for this, maybe at the weekend.

**Comment by cigamit** [comment]
Done.  Man nailing those nooks and crannies.

**Comment by netniV** [comment]
Sorry, I do tend to find bugs others normally miss.  I remember using a product for one company I worked at.  About 7 years later, when I picked up that product up at another company, they still remembered me at their support desk.... coz I was always finding issues others would not hit or just didn't report.  Hopefully in a good way 👍

**Comment by cigamit** [comment]
All good here ;)
