### ISSUE TITLE
path_webroot changes automatically

### ISSUE THREAD

**Issue by chathurag** [Cacti/cacti#1363]
In 1.1.35 I have changed the path_webroot in database to /var/www/cacti as it makes easy to update to with rra files to new versions. However after sometimes that changed to /var/www/cacti-1.1.35 automatically. Is ther anyway to make this permanent.

/var/www/cacti is a sysmbolic link to /var/www/cacti-1.1.35

**Comment by netniV** [comment]
The code will automatically work out where it is being run from and set that appropriately.  That is part of the core functionality to ensure plugins etc know where to find the root folder.

**Comment by cigamit** [comment]
@chathurag,

I saw your post about upgrades.  The process recommended in the documentation, I never use.  How I upgrade is pretty simple.  Here are the steps.

1. Tar up the cacti install but --exclude both log and rrd files.
2. Untar the distribution, remove the cache, rra, and log directories from it
3. cp -rp new_cacti old_cacti (or wherever)
4. Goto the console and execute any database upgrade.

No need to use symlinks, that just makes your life more difficult.  Backoff (sans database changes) is to untar the previous backup.  If you use this procedure, you won't have to worry about the path_webroot spoiling your fun.

**Comment by netniV** [comment]
I prefer using Git to do the work for me ;-) But you do need to have knowledge of how that works.  Switching between release tags is far easier.   Except when I make mistakes and forget I've gone to an earlier release then report a bug for you to loopy as you swear you've already fixed it;-)

**Comment by cigamit** [comment]
@netniV, hahaha

**Comment by cigamit** [comment]
Okay, closing now.

**Comment by chathurag** [comment]
How can we upgrade via git

**Comment by netniV** [comment]
You use `git clone` to copy the repository, then `git pull` to download updates.  To stick to a specific release, use `git checkout release/x.x.x`
