### ISSUE TITLE
Plugin Management - Reject invalid folder names

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1365]
Since most plugins hard code the folder that they are expecting to find themselves in, we should disallow the install and enable functions for any folder where the plugins folder name does not match the INFO file.

Should also ensure that Poller or the include/ code should also skip any plugin folder from being included if it is not installed and enabled. I think it may already do so but want to be sure.

**Comment by cigamit** [comment]
Good idea.  We always have people simply untaring the plugin_blah into the plugins folder with no hint that they did not read the instructions first.

**Comment by netniV** [comment]
Or using git clone, which keeps the repository name.  Actually, maybe we keep the install button but have it display one of our nice dialogs saying, 'Sorry, you didn't RTFM so go rename the directory'

**Comment by cigamit** [comment]
That would be a good option.  @ronytomen, would love to hand-craft the error message.

**Comment by cigamit** [comment]
Resolved.  I'm bored.

**Comment by netniV** [comment]
I was working on that too but I’m out now. I’ll take a look when I’m back.

**Comment by netniV** [comment]
One thing, I did add _ and space as valid characters for plugin folder names or you get a validation error when someone tries to click install on them.

**Comment by cigamit** [comment]
Yea, sorry about that.  In the future, just assign it to yourself, and I'll leave it be.  We all appreciate your support.

**Comment by netniV** [comment]
Don't think I can do that can I ? But it was no bigger anyway just ran out of time myself 👍

**Comment by cigamit** [comment]
Just pushed your validation recommendation and a few other corner case tweaks to prevent errors.  Got my .vimrc moved over too.

**Comment by netniV** [comment]
I'm running the latest develop code, but I'm seeing no errors or warnings or anything when I try to install plugins_monitor as a plugin.  has the new error message UI got in the way of this?
