### ISSUE TITLE
Improve error/info message display

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1366]
Currently, if you save an item and an error occurs, if you blink you can miss the message.  I'm working on a change that will display this in a proper dialog with the same automatic timeout if it is not an error so it doesn't clutter the screen.

Should have it ready in the morning.

**Comment by cigamit** [comment]
Putting it in a dialog would not be so bad.  What do you think?  It might be annoying for people who are trying to move fast.

**Comment by netniV** [comment]
It might annoying but if it’s an error that is the point if it’s an error. It should be seen not partially seen.

**Comment by netniV** [comment]
This is now in PR #1368

**Comment by cigamit** [comment]
Going to close this one now.
