### ISSUE TITLE
At Install time, allow official packages to be downloaded and installed from cacti.net or github.

### ISSUE THREAD

**Issue by cigamit** [Cacti/cacti#1375]
Right now, we only show a static list of Packages that are a part of the install.  It would be much nicer if Cacti allowed a user to either place official packages in a known directory, or accessed the list of official packages from cacti.net or GitHub locations.

**Comment by TheWitness** [comment]
So we sort of delivered this in the 1.3 release so I'm going to go ahead and close this.
