### ISSUE TITLE
user permissions descriptions missing from permissions tab

### ISSUE THREAD

**Issue by texashoser** [Cacti/cacti#1377]
Haven't really messed with these before and not sure how long the display has been like this, but at least on 1.1.35 there is no description of what exactly all the permissions are - just checkboxes.

Doing some searching, I finally found a post that listed the two appropriate arrays (user_auth_roles and user_auth_realms) and their descriptions and this matches up with the checkboxes, but wouldn't it be beneficial to list the realm descriptions in the browser interface?

I've checked this using three different browsers.

Thanks.

**Comment by netniV** [comment]
This is a known issue and has been resolved already. It will be corrected with the 1.1.36 release.

**Comment by texashoser** [comment]
I apologize.  I searched for an hour and did not find a report of this.  Well, at least searching 'permissions' didn't yield any results.  Thank you - please close.

**Comment by netniV** [comment]
It's no problem, This is the report https://github.com/Cacti/cacti/issues/1334 which we fixed it against.  Just hit close when you're satisfied 👍

**Comment by texashoser** [comment]
Thanks!
