### ISSUE TITLE
Avoid performing upgrades during a boost update

### ISSUE THREAD

**Issue by anarkia1976** [Cacti/cacti#1379]
I have updated to the latest Cacti/Spine (rrdtool 1.6 - always this version from begin) but when i create a new graph i have these errors:

Log1:
2018/02/20  09:16:48 - CMDPHP SQL Backtrace: (/graph_json.php: 220  rrdtool_function_graph)(/lib/rrd.php: 1475  variable_bandwidth_summation)(/lib/graph_variables.php: 518  bandwidth_summation)(/lib/graph_variables.php: 223  rrdtool_function_fetch)(/lib/rrd.php: 780  boost_fetch_cache_check)(/lib/boost.php: 243  boost_process_poller_output)(/lib/boost.php: 681  db_fetch_assoc)(/lib/database.php: 360  db_fetch_assoc_prepared)(/lib/database.php: 401 cacti_debug_backtrace)
2018/02/20 09:16:48 - DBCALL ERROR: SQL Assoc Failed!, Error: Table 'cacti.poller_output_boost' doesn't exist
2018/02/20 09:16:48 - DBCALL ERROR: SQL Assoc Failed!, Error:1146,  SQL:' (SELECT local_data_id, UNIX_TIMESTAMP(time) AS timestamp,  rrd_name, output   FROM poller_output_boost   WHERE local_data_id = 154    AND time < FROM_UNIXTIME(1519114608)) ORDER BY timestamp ASC,  rrd_name ASC '
2018/02/20 09:16:48 - CMDPHP SQL Backtrace: (/graph_json.php: 220  rrdtool_function_graph)(/lib/rrd.php: 1475  variable_bandwidth_summation)(/lib/graph_variables.php: 518  bandwidth_summation)(/lib/graph_variables.php: 223  rrdtool_function_fetch)(/lib/rrd.php: 780  boost_fetch_cache_check)(/lib/boost.php: 243  boost_process_poller_output)(/lib/boost.php: 681  db_fetch_assoc)(/lib/database.php: 360  db_fetch_assoc_prepared)(/lib/database.php: 401 cacti_debug_backtrace)
2018/02/20 09:16:48 - DBCALL ERROR: SQL Assoc Failed!, Error: Table 'cacti.poller_output_boost' doesn't exist
2018/02/20 09:16:48 - DBCALL ERROR: SQL Assoc Failed!, Error:1146,  SQL:' (SELECT local_data_id, UNIX_TIMESTAMP(time) AS timestamp,  rrd_name, output   FROM poller_output_boost   WHERE local_data_id = 154    AND time < FROM_UNIXTIME(1519114608)) ORDER BY timestamp ASC,  rrd_name ASC '

Log2:

2018/02/20  11:23:05 - CMDPHP SQL Backtrace: (/graph_json.php: 220  rrdtool_function_graph)(/lib/rrd.php: 1148  boost_graph_cache_check)(/lib/boost.php: 321  boost_process_poller_output)(/lib/boost.php: 681  db_fetch_assoc)(/lib/database.php: 360  db_fetch_assoc_prepared)(/lib/database.php: 401 cacti_debug_backtrace)
2018/02/20 11:23:05 - DBCALL ERROR: SQL Assoc Failed!, Error: Table 'cacti.poller_output_boost' doesn't exist
2018/02/20 11:23:05 - DBCALL ERROR: SQL Assoc Failed!, Error:1146,  SQL:' (SELECT local_data_id, UNIX_TIMESTAMP(time) AS timestamp,  rrd_name, output   FROM poller_output_boost   WHERE local_data_id = 157    AND time < FROM_UNIXTIME(1519122185)) ORDER BY timestamp ASC,  rrd_name ASC '

**Comment by netniV** [comment]
This sounds like you haven't upgraded properly.  The table `poller_output_boost` was created by the v1.0.0 upgrade and exists also within the cacti.sql file.

So regardless of which method of installation you went through, that table should always exist.

If you have the latest version of cacti, I would suggest running the `php cli/upgrade_database.php --forcever=0.8.8`

**Comment by anarkia1976** [comment]
I'm always use same steps from release to release.

The problem was born only during transition from 1.1.35 to 1.1.36.

I'm always doing:
php upgrade_database.php  --forcever
php audit_database.php --report
service httpd restart

**Comment by netniV** [comment]
You should never really need to manually do the upgrade_database.php as long as you browse the website after doing the upgrade.

The audit may be useful just to see what the state of place is but isn't required.

**Comment by cigamit** [comment]
This was likely caused by doing a database upgrade in the middle of a boost run.  We should change this bug to something like 'avoid performing an upgrade during boost processing'.  Recreating the table will resolve the issue.

**Comment by anarkia1976** [comment]
I have dropped sql table and now no problem so far. thanks a lot guys. 
The problem was related to a database corruption.

**Comment by cigamit** [comment]
More than likely database corruption, there is a very minor chance of this happening from time to time due to the command "rename table" not being allowed within a MySQL/MariaDB transaction.  If they fix this, then this problem will no longer appear.
