### ISSUE TITLE
Clog tab is duplicated funtionality

### ISSUE THREAD

**Issue by ronytomen** [Cacti/cacti#138]
Move `Clog` functionality into `Utilities` -> `View Cacti Log File`.

Also rename `View Cacti Log File` to `View Cacti Log`

**Comment by cigamit** [comment]
I suggest we disable the realms by default.  Moving it will cause quite a backlash.

**Comment by cigamit** [comment]
Resolved through removal of realm from Admin user by default.  Also renamed all instances of 'Log File' to 'Log'.
