### ISSUE TITLE
Potential failure when updating script type

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1380]
If you have a data query, and you change the script type, it doesn't seem to reflect across the data sources:

As per https://github.com/netniV/cisco-sfp/issues/1#issuecomment-367027270, I created some test code (which you can see just above the linked post) and it is spewing out that all the data sources are in script query mode, not script query server.  This is despite making sure it's correct in the GUI.

Probably one for you @cigamit

**Comment by netniV** [comment]
@cigamit what is wrong with this code?

I am getting the wrong names for my cisco-sfp template (https://github.com/netniv/cisco-sfp/)

```sql
SELECT SQL_NO_CACHE
        data_input.id input_id,
        data_input.name,
        snmp_query.name query_name,
        data_template_data.active,
        data_template_data.name as template_name,
        data_template_data.name_cache as template_cache,
        data_template_data.id,
        data_template_data.data_template_id,
        data_template_data.data_input_id,
        data_template_data.local_data_id,
        data_input.type_id,
        data_input.input_string
        FROM snmp_query
        LEFT JOIN data_input ON data_input.id = snmp_query.data_input_id
        LEFT JOIN data_template_data ON data_template_data.data_input_id = data_input.id
        LEFT JOIN data_template ON data_template.id = data_template_data.data_template_id
        WHERE snmp_query.name like '%SFP%'
```

**Comment by netniV** [comment]
If you look at the link in the first post of this issue, I have been trying to diagnose why Cacti isn't updating the script path properly to include the function name despite having the script server (indexed) set.  So, I just threw this together to try and see if I can get the SQL right to verify what is occurring against the code.

The other thread is a long read but if you skip to the last parts, I created a test script that pulls out the data input, and tries to validate using the same basic functionality as the code does for updating a script path.  It reckons my query is just a query, not a script server query.  So I'm getting a difference between type 4 and type 6.... 

I think this may even answer a LOT of questions we've had on the forums and here over the months/years as to why some templates aren't working for users.  I think there is a flaw in the logic... but I can't get my head around it.

**Comment by cigamit** [comment]
I've talked about re-writing it for years, but need more quality time.  Would take at least a week to do it without my head exploding.

**Comment by netniV** [comment]
So... without rewriting, why does one code thing I'm type 4 and another type 6??

**Comment by cigamit** [comment]
I'll look at it this morning in just a few minutes.  One way to tell what code I have not fully evaluated is to look for tables without aliases in the query.  If you don't see me aliasing a table like `graph_local AS gl`, you know I have not closely scrutinized this part of the code.  Second clue is if you see a bunch of natural joining using `FROM (tableA, tableB, tableC)`.  I despise that notation and try to eliminate it as much as possible.  But you will still see it in parts.

**Comment by netniV** [comment]
I'm starting by adding
```php

        $log = sprintf('UPDATE_POLLER_CACHE: data_source: %s (\'%s\'), data_input: %s (\'%s\') - data_input_type: %s (%s)',
                $data_source['id'], $data_source['name'],
                $data_input['id'], $data_input['name'],
                $data_input['type_id'], $input_types[$data_input['name']]);
        cacti_log($log);
```
To my utility.php, as I am sure the clue is in there.

**Comment by cigamit** [comment]
Check to see that data_template_rrd.data_source_type_id is updating with the change.

**Comment by cigamit** [comment]
Sorry, bad call.

**Comment by cigamit** [comment]
When you edit the data query, the first issue, is that when you change the data input type, there is no push-out activity.  Could take a long time.  I would say to make that field read_only after graphs are created.  That is the first change.

But before we do that, let's see what else we can dig up by re-populating the poller cache.  Good thing this is a test system ;)

**Comment by cigamit** [comment]
Okay, I've done some hacking in data_queries.php that works around the issue.  But this should be done in the api.  After a bit more testing, I will commit, but we need to find out why the disconnect.

**Comment by netniV** [comment]
This query shows up the issue:
```sql
select 'snmp_query' `table`, id `id`, name `name`, 'table:data_input_id' `link`, data_input_id `link_id` from snmp_query where name like '%sfp%'
union
select 'data_input(sq)' `table`, id `id`, name `name`, 'var:input_types' `link`, type_id `link_id` from data_input where id in (select data_input_id from snmp_query where name like '%sfp%')
union
select 'data_template_data' `table`, id `id`, name `name`, 'table:data_input_id' `link`, data_input_id `link_id` from data_template_data where name like '%sfp%'
union
select 'data_input(dtd)' `table`, id `id`, name `name`, 'var:input_types' `link`, type_id `link_id` from data_input where id in (select data_input_id from data_template_data where name like '%sfp%')
```

```
+--------------------+----+------------------------------------------------------+---------------------+---------+
| table              | id | name                                                 | link                | link_id |
+--------------------+----+------------------------------------------------------+---------------------+---------+
| snmp_query         |  7 | Cisco - 65xx - SFP statistics                        | table:data_input_id |      12 |
| data_input(sq)     | 12 | Get Script Server Data (Indexed)                     | var:input_types     |       6 |
| data_template_data | 92 | |host_description| - SFP Statistics - |query_device| | table:data_input_id |      11 |
| data_input(dtd)    | 11 | Get Script Data (Indexed)                            | var:input_types     |       4 |
+--------------------+----+------------------------------------------------------+---------------------+---------+
```

**Comment by netniV** [comment]
The problem is in the XML file that is imported.  I have taken it over from @oxygen8 I think it was so it's historical but shows an issue....

https://github.com/netniV/cisco-sfp/blob/master/cacti_data_query_cisco_65xx_sfp_statistics.xml

Search for 03001880e9e4c4191a5da189ae26d0e237f015 and you will see that it is input method type 4, but also appears in later too

Search for 030018332111d8b54ac8ce939af87a7eac0c06 and you will see that it is input method type 6 which appears on the heading.

So we have a bad bad XML file that is saying it's Type 6 for the SNMP Query, but Type 4 for the data.

**Comment by cigamit** [comment]
Please test out the latest commit.  It's only the beginning of the issue.  We should make these thing R/O after Graphs have been created.

**Comment by netniV** [comment]
True.  I was gonna say a dev would be annoyed by that but then they'd just have to delete and wait.

**Comment by netniV** [comment]
The only think with the change is that it does mean we need to change the id to make it fixed.   If we used a reworked version of above, could we not find any data_template_data via data_local that didn't match the snmp_query ?  Thus on any save, it would fix up any bad usage.  Is there ever a point were you would want to have different type ids?

**Comment by netniV** [comment]
Furthermore, could we add that as an upgrade warning?

**Comment by cigamit** [comment]
I'll comment later this evening when it's not work hours.

**Comment by cigamit** [comment]
Do we want to spend any more time on this before the release?

**Comment by netniV** [comment]
I’ve posted my above sql check to a post on the forum where someone had a similar issue.  There may be a need to flag up potential issues, or offer to update the data template where it doesn’t match the SNMP query?

**Comment by cigamit** [comment]
Okay, so look for a way to 'unbreak' peoples templates on update.  Let me think about that one.

**Comment by netniV** [comment]
It's either that, or where we have an snmp_query, we use the type from there only.

**Comment by cigamit** [comment]
Fixed up now.  The latest change should unbreak them.  We should be digging into Templates in more detail as previously mentioned.  Very dangerous though.

**Comment by cigamit** [comment]
Marking this one resolved now.
