### ISSUE TITLE
Avail report plugin

### ISSUE THREAD

**Issue by chathurag** [Cacti/cacti#1381]
Is there any plugin for device availability reporting such as availreport for 1.1.x

**Comment by netniV** [comment]
Do you mean sending an email of current device state?

**Comment by chathurag** [comment]
Such as showing availability graph per device and also better if we can send email per month.

**Comment by netniV** [comment]
Are you referring to the data held by thold or by monitor?  By default, cacti core does not actually maintain a history of availability as far as I have seen (could be wrong). That functionality comes from THold (or maybe Monitor).

If so, again, you would be better opening the issue there so it can be tracked with the plugin.  If it is core, could you let me know where you think this comes in as I've not noticed it?

**Comment by cigamit** [comment]
Correct, but plugins provide this.  As such, I'll close this one.

**Comment by chathurag** [comment]
Earlier in 0.8.x cacti had plugin called avail report. However in 1.1.x we are unable to use those older plugins due to compatibility issues
