### ISSUE TITLE
CSRF Timeout does not obey session timeout

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1383]
So today I finally got a message saying that a CSRF Timeout occurred.  I think this was down to the changes we've made to the messaging system which clearly made it work better 👍 

However, I was being timed out way shorter than my session settings should have been based on the settings for the user/system.

**Comment by cigamit** [comment]
Yea, we are still not getting a GUI error but rather a blank main, until you navigate though.  Still not optimal.

**Comment by cigamit** [comment]
The readme explains how to properly set this thing up.

**Comment by netniV** [comment]
It does?  There's a readme??

**Comment by cigamit** [comment]
&lt;path_cacti&gt;/include/csrf/README.  I'll take it you were joking ;)

The CSRF check should go way up front, before any output, and then, if the value is bad, load up all the session value with the field values posted, and redirect back to the calling page.  That way the user does not loose their information.  I tried at one time doing the header('Location: ...'); call, but it did not work.  So, I've been punting on this one.  All you if you want to tackle it before the weekend is over.

**Comment by netniV** [comment]
Nope, never looked at it. Didn't even know that existed.  I think I need a day or two off given I can't even recall the correct plugin versions this week.  I may have a look tomorrow night, it's in my To Fix list.

**Comment by netniV** [comment]
So, I had a different aspect of this today.  I'd left my graph creation (graphs_new.php) page open on my live site but I was working on a feature request before I came back to create a CPU graph.  When I clicked on create, all I got was a white screen.  

So I refreshed the screen, and was then presented with:
![image](https://user-images.githubusercontent.com/9052188/37649979-76465598-2c2b-11e8-9079-0a2c2b4742f5.png)

So there's definitely a bug somewhere that doesn't refresh/redirect properly on a CSRF timeout.

**Comment by netniV** [comment]
(and I almost fooled myself into clicking the above OK button when I posted that comment as I thought it'd appeared here before remember, this is github!)

**Comment by ronytomen** [comment]
I just recently encountered a white screen after accepting the license on installation.  Stopped the release over this, tracked it down into the CSRF code.  Still need to continue to track it down.

**Comment by netniV** [comment]
I think considering that this issue has been ongoing, it's not worth holding the release over since it's no worse than it was before this release.  However, I do think we should try and track it down for 1.2 so it's clean from the start.

I just installed fresh onto Fedora 27, with a few hiccups due to differences in default packages/firewall configuration.  Because my VM is slow though, I did get timeouts on the final stage of the install.  Again, that's something I've suggested for 1.2 where we should display an update progress, maybe a list of items we are attempting to perform, then check them off once completed.

**Comment by ronytomen** [comment]
I would normally agree with not holding the release.  But, from my perspective, this is a stop ship issue.  As I'm unable to start an upgrade installation and that needs to be figured out.

**Comment by netniV** [comment]
OK, that's different.  I have not had that situation at all and i've been installing on quite a few different platforms, but they were not always upgrades.  Are you still sure it's CSRF if you are getting it every time?

**Comment by netniV** [comment]
I can simulate an upgrade on CentOS 6, 7, Fedora, Ubuntu 16 and 17 by setting git back to a specific release, emptying the database and loading from the cacti.sql of that release, then rolling forward.

**Comment by ronytomen** [comment]
Yes, @cigamit didn't have issues as well.  I'm running Fedora Core 26 (apache2) on my build/test box with a multiple Cacti installs in subdirectories under the virtual host.

This might be browser related, tested on latest Firefox and Safari.  Both failed the same way.

This ultimately could be an issue with my installation or web browsers setup, but it would sure be nice to figure that out.

**Comment by netniV** [comment]
If you want to email me, I can test the upgrade part since it requires no authentication (currently - though i've tried to start looking at that).

**Comment by netniV** [comment]
Alternatively, check over my wiki that I put together on my Fedora 27 install.  It may help out with something:
https://github.com/netniV/cacti/wiki/Testing-Environment:-Fedora

**Comment by ronytomen** [comment]
Nothing I do not already know.

**Comment by netniV** [comment]
Fair enough 👍

**Comment by netniV** [comment]
I presume you’ve tried disabling the timeout to see if it’s definitely that?

**Comment by netniV** [comment]
Have you managed to resolve this yet @ronytomen ?

**Comment by vishnubraj** [comment]
any workaround for this? i keep getting this message whenever i do "Apply automation rules " for 1000+ graphs.

**Comment by dsclassen** [comment]
I'm seeing a blank page when I attempt to duplicate a device template, but if I manually navigate to another page I see this popup.

<img width="615" alt="csrf_error" src="https://user-images.githubusercontent.com/8882563/39554123-e00e983e-4e25-11e8-81a7-1f878ce7c576.png">

**Comment by netniV** [comment]
I’ll see if I can figure this out later. Never looked into it myself but guess I should try.

**Comment by netniV** [comment]
From what I can see, everything appears to be configured OK.  There are some changes we could do such as using the DEFER option so we can check manually the status of CSRF and report accordingly.  That might prevent the white screen issue.

However, what I need to do is try and get a test case were I can break the CSRF everytime.  So far, that doesn't seem to be possible so it's a struggle to find out what exactly is causing it (short of putting a whole bunch of logging into the CSRF code).

I am on patch 8f4d2cfc7874bc5d7049980887435cb477286f16 of the develop branch and I can duplicate device templates just fine.  Once thing I did notice was that the AJAX calls in host_templates.php were setting the csrf magic value which is normally done automatically by the csrf-magic.js functions.  Whether that has a bearing on the outcome or not, I'm unsure.

What browser were you using @dsclassen ?

**Comment by dsclassen** [comment]
I’m using Safari when on my Mac and Firefox when on Linux machines. However, shortly after posting the message yesterday I quit and relaunched my browser and things starting working. So maybe a corrupt session or something?

**Comment by cigamit** [comment]
Resolved now.  No more blank pages.
