### ISSUE TITLE
When installing/enabling plugins, current user and admin should get permissions

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1384]
When a user is installing a plugin, they should be automatically given full rights to the plugin.  Otherwise, you have to remember to go to Users, edit yourself, and THEN refresh to make sure you can see everything.

Any permission a plugin offers should be automatically ticked when either installing and/or enabling.

An alternative would be if there is a default admin group selected within settings, there could be an extra option to automatically enable that group too.  That group would have to be made unavailable for deletion though to prevent issues.

**Comment by cigamit** [comment]
Resolved.

**Comment by cigamit** [comment]
Making too many mistakes.  This global development stuff is working when you are real agile.
