### ISSUE TITLE
User and group permissions item checkbox label is blank

### ISSUE THREAD

**Issue by rcalpha** [Cacti/cacti#1385]
In user and groups permissions, each permission checkbox is not showing the label to know what it is. It happens with "Show Form/Setting Help Inline" check and unchecked. The version is 1.1.35

![cacti-error-permissions](https://user-images.githubusercontent.com/3718709/36490123-eff38f48-16fd-11e8-8e6b-b0fb6a19fc61.png)

**Comment by netniV** [comment]
This is a know issue and has already been fixed as per https://github.com/Cacti/cacti/issues/1377 and https://github.com/Cacti/cacti/issues/1334 

You can either update to the latest develop branch sources or wait for the 1.1.36 release.

**Comment by rcalpha** [comment]
Thanks... I could not find this issue
