### ISSUE TITLE
form_selectable_cell() ignores width if no style_or_class is passed

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1386]
When using the form api, form_selectable_cell() does not set width if password if style or class is not passed.  Therefore, you have to pass an invalid class just to get width to work.  Is this by design?

**Comment by cigamit** [comment]
FYI, Rony has not committed to doing a release earlier than Sunday.  He's mega busy.  So, we have more time for simple stuff.

**Comment by cigamit** [comment]
Resolved.
