### ISSUE TITLE
Cacti 1.3.6 (develop branch) many duplicate options on user permisson settings

### ISSUE THREAD

**Issue by pautiina** [Cacti/cacti#1388]
Hello.
I have plugins Weathermap and after update code from develop branch I have some problem with settings:
![image](https://user-images.githubusercontent.com/11805503/36527278-f55cab4c-17b9-11e8-9d0f-cde031dbc804.png)
And plugin tab not showing.
On cacti log:

```
2018/02/22 10:16:01 - CMDPHP PHP ERROR NOTICE Backtrace: (/user_admin.php: 55 user_edit)(/user_admin.php: 2105 user_realms_edit)(/user_admin.php: 1748 CactiErrorHandler)(/lib/functions.php: 4587 cacti_debug_backtrace)
--
2018/02/22 10:16:01 - ERROR PHP NOTICE: Undefined offset: 2459 in file: /var/www/cacti/user_admin.php on line: 1748
2018/02/22 10:16:01 - CMDPHP PHP ERROR NOTICE Backtrace: (/user_admin.php: 55 user_edit)(/user_admin.php: 2105 user_realms_edit)(/user_admin.php: 1746 CactiErrorHandler)(/lib/functions.php: 4587 cacti_debug_backtrace)
2018/02/22 10:16:01 - ERROR PHP NOTICE: Undefined offset: 2459 in file: /var/www/cacti/user_admin.php on line: 1746
2018/02/22 10:16:01 - CMDPHP PHP ERROR NOTICE Backtrace: (/user_admin.php: 55 user_edit)(/user_admin.php: 2105 user_realms_edit)(/user_admin.php: 1748 CactiErrorHandler)(/lib/functions.php: 4587 cacti_debug_backtrace)
2018/02/22 10:16:01 - ERROR PHP NOTICE: Undefined offset: 2461 in file: /var/www/cacti/user_admin.php on line: 1748
2018/02/22 10:16:01 - CMDPHP PHP ERROR NOTICE Backtrace: (/user_admin.php: 55 user_edit)(/user_admin.php: 2105 user_realms_edit)(/user_admin.php: 1746 CactiErrorHandler)(/lib/functions.php: 4587 cacti_debug_backtrace)
2018/02/22 10:16:01 - ERROR PHP NOTICE: Undefined offset: 2461 in file: /var/www/cacti/user_admin.php on line: 1746
2018/02/22 10:16:01 - CMDPHP PHP ERROR NOTICE Backtrace: (/user_admin.php: 55 user_edit)(/user_admin.php: 2105 user_realms_edit)(/user_admin.php: 1748 CactiErrorHandler)(/lib/functions.php: 4587 cacti_debug_backtrace)
2018/02/22 10:16:01 - ERROR PHP NOTICE: Undefined offset: 2460 in file: /var/www/cacti/user_admin.php on line: 1748
2018/02/22 10:16:01 - CMDPHP PHP ERROR NOTICE Backtrace: (/user_admin.php: 55 user_edit)(/user_admin.php: 2105 user_realms_edit)(/user_admin.php: 1746 CactiErrorHandler)(/lib/functions.php: 4587 cacti_debug_backtrace)
2018/02/22 10:16:01 - ERROR PHP NOTICE: Undefined offset: 2460 in file: /var/www/cacti/user_admin.php on line: 1746


```

**Comment by netniV** [comment]
That would appear to be a weathermap issue, not a cacti issue. However, I think there may still be a bug were if the realm isn't found, it still tries to display it (based on a quick glance at user_admin.php)

**Comment by pautiina** [comment]
I have two servers Cacti (develop-branch). On one plugin weathermap I constantly update and test from the develop branch. On the second server, I have not touched the plugin weathermap for a very long time.
And the problem is observed on two servers.

**Comment by netniV** [comment]
I have other plugins that I am constantly updated and they do not exhibit this issue.  It's going to be something between the core code and the way he's creating his realms.

**Comment by pautiina** [comment]
I also have other plugins and there are no problems with them. The only thing that I sin yet, it's on the plugin THOLD. I updated it today and it turned out that way.

**Comment by netniV** [comment]
So updating a plugin is duplicating the realms?

**Comment by pautiina** [comment]
Maybe. I can not repeat the bug. And I do not know why it happened. I now want to remove extra realm and then watch what happens.

**Comment by netniV** [comment]
Well, your permissions are based on a realm.  So, if you remove the newer realms, it should be OK.  eg, keep the first realm matching the plugin and file.  Remove the others.

**Comment by netniV** [comment]
I think I see a problem.  I decided to look.

```diff
--- a/lib/plugins.php
+++ b/lib/plugins.php
@@ -672,7 +672,7 @@ function api_plugin_register_realm ($plugin, $file, $display, $admin = true) {
                AND file = ?',
                array($plugin, $file), false);

-       if (!empty($exists)) {
+       if ($exists === false) {
                db_execute_prepared('INSERT INTO plugin_realms
                        (plugin, file, display)
                        VALUES (?, ?, ?)',
```

**Comment by pautiina** [comment]
@netniV you patch resolve problem

**Comment by netniV** [comment]
Err, I updated the patch as I pasted the wrong one haha

**Comment by pautiina** [comment]
What do you mean?
I have your patch working. Only I first deleted all realms associated with the Weathermap

**Comment by netniV** [comment]
Let me tripple check it..  but Weathermaps IS spamming the register_realm function.  See an update on the weathermaps issue.

**Comment by netniV** [comment]
Well, it would appear that either works.  
```
2018/02/22 09:46:12 - CMDPHP api_plugin_register_realm('quicktree', 'quicktree.php', 'Plugin -> QuickTree: Access', 1 ) , set = Yes, empty = Yes, false = Yes, sizeof = 1
```
Smallest change is the removal of the ! but checking `$exists === false` is equally valid apparently 👍

**Comment by netniV** [comment]
https://github.com/Cacti/cacti/commit/160a42c1e6ca35f006bdf24c7ae4c81a16c732e4 is where this broke as part of #1384

**Comment by cigamit** [comment]
Yea, woops.

**Comment by cigamit** [comment]
Okay, resolved.

**Comment by netniV** [comment]
I'll have to update my sources now to reflect your change lol.
