### ISSUE TITLE
Have Plugin Uninstall prompt user before Uninnstalling

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1390]
Uninstalling a plugin is very dangerous because it wipes all configuration data for a plugin if the plugin is written correctly. Therefore, when uninstalling I think we should go to another page which shows a warning about this and requests a validation (either by typing the plugin name or a verification code).

This is to prevent issues when people are upgrading plugins and are new to the system not realising you shouldn't uninstall only disable (if at all).

**Comment by cigamit** [comment]
Resolved.  If you want to change the wording, do a pull request.
