### ISSUE TITLE
Message notification is repeated if you switch tabs quick enough

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1391]
More a slight annoyance than an issue but when you hit save, if you then click on the logs tab, you will see the same message again.

**Comment by cigamit** [comment]
Yea, I'm not sure I can repeat that.

**Comment by netniV** [comment]
All I did was click save, then as soon as the dialogue appears switch to the eh log tab but I’ll get the steps tomorrow

**Comment by cigamit** [comment]
It's odd.  We need to unset the json before we show the dialog.  I bet that is the issue.

**Comment by cigamit** [comment]
I figured you were busy with plugins.  So, that we have cool down time before Sunday, I just fixed this one.

**Comment by netniV** [comment]
I am.  More routerconfigs about to come very shortly.

**Comment by cigamit** [comment]
I was just thinking that the way that it's written now, it could be migrated into the API.  Let me see if I have the energy to pull that one off.

**Comment by netniV** [comment]
You'll hate me, but I've thought of another issues mwahah.

**Comment by cigamit** [comment]
In the API now.  More testing and more i18n.

**Comment by cigamit** [comment]
Keep logging them.
