### ISSUE TITLE
AJAX handled errors do not notify Admins that page errors exist

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1392]
If a plugin is clicked on, an AJAX error is correctly handled if error 500 occurs.  However, the plugin itself is not disabled and there is no evidence of the error 500 in the Cacti log since it occurs before Cacti can even start.

Have a simple API page to receive a single name of the plugin to disable (with validation code?) which can be called without checking the status from the jQuery HTTP error handler if /plugins/ is detected in the url.

**Comment by cigamit** [comment]
I thought about this one, and for a minute, I thought to myself, who cares it's the GUI.  It's going to be tricky though.  We may never know which plugin per se as plugins can inject code just about anywhere.

**Comment by netniV** [comment]
That is quite true. Unless there is a backtrace in the output.

**Comment by TheWitness** [comment]
I would rather see the error log of the syntax error.  So, a callback to indicate that there was a problem with such and such a page is a better idea.  Has to be a global link though, which is the bitch -1 realm.

**Comment by TheWitness** [comment]
Then have an Admin Error Email based upon that Callback.

**Comment by TheWitness** [comment]
Turned this into a detection for 500 or better and will send an Administrative email and log a Cacti error when it occurs.
