### ISSUE TITLE
Allow queuing of graphs to add to a report via the graph page

### ISSUE THREAD

**Issue by cigamit** [Cacti/cacti#1394]
Allow users to tag graphs that they wish to add a a Nectar report through the graphs interface.  This could include tree and tree branches as well.

Once on the reports page, they could apply those queue graphs to their report as Graph or Tree items.

**Comment by cigamit** [comment]
Add to this the need from the Graphs and Trees console pages for an admin to add to a Report.  Possibly also the List view mode.  These three enhancements could conceivably be easier to accomplish than pure queuing.

**Comment by TheWitness** [comment]
I was about to close this till I saw "Devices" and "Trees" since Graphs have been added already.

**Comment by TheWitness** [comment]
Going to close anyway since the original enhancement was delivered already.
