### ISSUE TITLE
Distinguish between plugin tabs and core tabs in settings

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1397]
I know at the moment, plugins can tap their settings in anywhere they like.  However, one enhancement I think would be benefitial would be to provide all plugin tabs within the settings page from the right hand side (sorted alphabetically would also help I think).

Thus you would have something like:

General | Paths | &lt;etc&gt; | Mail  | | | | | GExport | Monitor | Thresholds
--- | --- | --- | --- | --- | --- | --- | --- | --- | --- | ---

**Comment by cigamit** [comment]
Going to run into issues with @browniebrauns themes I think.  Thought he was using ellipsis.  Oh, wait, maybe he's only doing that with the top tabs.  I would prefer generalized ellipsis myself.  Maybe a different class/color?

**Comment by netniV** [comment]
I think it just makes for a cleaner separation myself.  I guess it is partly a personal preference.  Location over colour.  A different class/color would help distinguish it too I guess.

**Comment by cigamit** [comment]
That can be done entirely in CSS or the main.js for the theme.  We just need to add a class attribute to the css for the plugin tabs.

**Comment by cigamit** [comment]
I've added a class called 'pluginTab' to distinguish.  I would leave the rest to the theme of your choice.  Once you have a new theme that you like, you should create a pull request.  No rush.
