### ISSUE TITLE
Implement an interactive web based Plugin upgrade process

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1398]
When upgrading a plugin, no version or requirement checks appear to be performed before calling the plugin code. This can lead to errors such as calls to undefined functions which may be in newer versions of the requirements.

Example is https://github.com/Cacti/plugin_monitor/issues/51

**Comment by cigamit** [comment]
Yea, good point.  Installing is one thing, upgrading is missed.  We should be publishing released versions and allowing direct download and install.  This applies on both a new install and point during operations.  Just like a 'yum upgrade/update'.

**Comment by netniV** [comment]
@jpobeda and @jhonnyx82 - I've updated the title to better reflect that we mean both plugins and templates.

**Comment by jhonnyx82** [comment]
Thank you, I think it will be useful such a process, but from my end is mainly important to have a cooperative approach to the templates and plugins

**Comment by TheWitness** [comment]
Renaming this one as the Template/Package import will be dynamic in 1.2.23.

**Comment by TheWitness** [comment]
This is now resolved in a large group of commits.
