### ISSUE TITLE
Plugins should have a version requirement for dependencies

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1399]
Similar to #1398 plugins should be able to specify minimum versions of other plugins.

**Comment by cigamit** [comment]
Minor syntax change to the 'requires' INI variable.

**Comment by cigamit** [comment]
I would suggest:

`requires = thold:1.0.4 monitor:2.1`

Assuming it means &gt;= to.

**Comment by netniV** [comment]
Looks good to me, if no version found, assume any version?

**Comment by cigamit** [comment]
Yup.  1.2.

**Comment by netniV** [comment]
This has now been implemented for 1.2 in PR #1436
