### ISSUE TITLE
User settings should have checkbox to enable overriding of global settings

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1400]
Here is an idea I had the other day whilst in a queue... make things optional... and then I thought about the settings fields which can be overridden, such as user settings vs global settings.  

If they had an 'optional' => true, display a checkbox and then only save that settings if it was ticked.  Otherwise, remove it as the setting is no longer being overridden.  This would prevent the mess were if you set one field to be overridden, it saves all of them on that page.

**Comment by cigamit** [comment]
I'm not clear.  Cite a specific case and screen shot if you can.  I know you are like burning things down, and I'm trying to keep up, but you have to be a little more descriptive, and a picture or two, with circles and arrows tells 1000 words.

**Comment by cigamit** [comment]
Oh jeez.  I just re-read that in a much more semi conscious state (more awake).  What most modern applications are doing now is taking away the save button entirely, and dynamically changing the setting based upon change events.

Though this is pretty cool, it worries me in that people will fiddle with things and not know what they changed, and all hell breaks loose.  That is why I prefer the current behavior.  I'll keep this open though.  Maybe someone will correct my assumptions.

**Comment by netniV** [comment]
I'm not talking about the general save methods.  On a side note, I have really big like/dislike for automatic save because it's a nightmare in undoing something easily but it's quick and you know its done.

What I'm more talking about is things like when editing a user, then clicking the Settings tab

![image](https://user-images.githubusercontent.com/9052188/36639798-f7357080-1a0b-11e8-9d0b-7ce973b4c3d8.png)

Pretty much every one of these settings are optional.  And if they are optional, why are we storing and saving EVERY setting just because you hit save.

**Comment by cigamit** [comment]
Well, then this would be the right page to remove the save/return button.  We need someplace to put the 'setting saved' message.  I suggest the end of the previous header, right or left aligned div (leave it to the theme).

So for example, you change the Default Time Range in your example, then we do the callback saving only that field, and put a 'Setting Saved' in the 'Time Spanning/Shifting' header, make it go away after two seconds using a timer.

**Comment by cigamit** [comment]
Maybe we re-position the return button too.  Having it at the bottom is annoying.  Same with the save button on other forms.

**Comment by cigamit** [comment]
Today is another QA day, though the plugin stuff I did yesterday kind of went beyond just simple QA.  I found a number of smaller bugs that I was able to correct yesterday.  Need to update the language file before release too.

I was planning on spending all weekend on Template -&gt; Package conversion this weekend for many of the contributed Templates, but alas, how perfect was that timing.  I can get things from the Weyback machine.  Just waiting on @ronytomen, though he tells me it's an evening activity.

**Comment by netniV** [comment]
Whilst I like what your suggesting to a degree, it doesn't give the flexibility to remove the override.

**Comment by cigamit** [comment]
Checkbox is a hot mess though, too many things to change to make the update.  For the 'Change Host Settings' we don't have much choice.  Let's play with things after 1.1.36 is done.  This is a very easy change.

**Comment by netniV** [comment]
Oh I wasn't thinking this was going to be a quick fix and in this release.  It was one of those things that had always bugged me and I couldn't come up with a reasonable solution to it.  Working on the templates brought the idea forward of checkboxes since it's an override effectively.

**Comment by cigamit** [comment]
Going to close this now.
