### ISSUE TITLE
Shorten interface names for HP switches in cacti

### ISSUE THREAD

**Issue by AlexZalyalowa** [Cacti/cacti#1404]
Add option, that will let to shorten interface names for HP switches like Bridge-Aggregation4 into BAGG4, GigabitEthernet1/0/25 into Gi1/0/25, etc.

**Comment by cigamit** [comment]
Sounds like the best thing to do it to write a snmp based data query with a scriptlet for an input item.  Also, if you can do this with a regular expression, then this is already supported.

**Comment by AlexZalyalowa** [comment]
I've added this template (it must take only 2 first letters of interface name and all last digits and "/"):
        <ifNameHP>
            <name>Name (IF-MIB)</name>
            <method>walk</method>
            <source>VALUE/REGEXP:^[A-Za-z]{2}|[0-9/]{1,7}$</source>
            <direction>input</direction>
            <oid>.1.3.6.1.2.1.31.1.1.1.1</oid>
        </ifNameHP>
to interface.xm, set name and title "|\|host_description\| - Unicast Packets - \|query_ifNameHP\|" for In/Out Unicast Packets in Data Queries, but nothing nad happened - titles for graphs are all the same.

**Comment by AlexZalyalowa** [comment]
> Sounds like the best thing to do it to write a snmp based data query with a scriptlet for an input item. Also, if you can do this with a regular expression, then this is already supported.

Can you give me an example of such scriptlet. It seems to me that my method only takes interface name with such regexp.

**Comment by cigamit** [comment]
Well, do this, goto Console > Settings > Visual and decrease the maximum graph title length, and when you do, the graphs page should display less information.  Otherwise, you can use an input direction VALUE:REGEXP to trim/modify the input direction.  Look at ifOperStatus in &lt;path_cacti&gt;/resource/snmp_queries/interface.xml

**Comment by cigamit** [comment]
That's how you should handle this for now.
