### ISSUE TITLE
When Data Query columns are wide, they cause rendering issues

### ISSUE THREAD

**Issue by lumkalac** [Cacti/cacti#1405]
There is a bug in column width in graphs_new. If the width of the column is too large, other columns will fall away! (minimal column width = length text = fixed length ?)

Duplicate bug: create new graph -> based on Windows machine -> Look at Data query [SNMP - Interface Statistics] -> if the length of value in column Description is lengthy -> then there's no room for the other colums left -> hence they will not be visible!

I suspect some will not even notice that it actually is a bug rather than a shortcoming.

**Comment by cigamit** [comment]
After playing with this today, I'm still trying to find a way to force enable ellipsis support inside of a table that the column resizing will work with.  In the mean time, shorten the title...

**Comment by cigamit** [comment]
This should be resolved on the graphs new page now.
