### ISSUE TITLE
Merge Debug plugin into 1.2

### ISSUE THREAD

**Issue by cigamit** [Cacti/cacti#1407]
We should probably merge the debug plugin into the 1.2 Feature branch.  It could use a good bit of TLC along the way also.

**Comment by netniV** [comment]
Should I re-write it for you then ? just kidding ;-)

**Comment by netniV** [comment]
Should probably change it's name to DSDEBUG too since it's more than a general debugger.  Added a couple of minor fixes. Bumped up the first requirement as I found my changes didn't work below 1.1.20 (you might see the reason for that).

**Comment by netniV** [comment]
This is now part of PR #1785
