### ISSUE TITLE
Plugin mangement: Automatic disabled plugins should notify admins

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1409]
If a plugin is automatically disabled, there should be a method to notify the admins so that they are aware of this without having to search back through the log files.  Plugins can become disabled at random hours of the night or when there are a lot of other errors occurring which can mask the lack of plugin functionality.

**Comment by cigamit** [comment]
Good idea.

**Comment by netniV** [comment]
This would link in nicely with the primary admin concept we were discussing.

**Comment by netniV** [comment]
Apparently, this was already done as part of 9a5cf5ae5446c847709e01ac3da0664135b77e3b
