### ISSUE TITLE
Save is reported as successful even though SQL statement fails

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1412]
When saving, operation is often reported as being successful even though the save actually failed.

**Comment by cigamit** [comment]
I would like to suggest that this be something that we don't address here.  If the API/GUI is working, these messages should not appear.  Otherwise it's a bug.

**Comment by netniV** [comment]
I've confused by that or I'm not understanding what your point is. How can hitting save and seeing a success message be right?  You still get log entries saying that the SQL statement failed, but to the operator they can believe everything was fine.  This is especially true on some save operations that then redirect to another page.
