### ISSUE TITLE
Graph Legend - Line Label with Percentage Sign

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1413]
So had an issue thrown at me today, how to add a percentage sign to a graph legend.  So, doing it with the data value was fairly simple, create a GPRINT preset and use %% in the format of the item.  

However, tried to add the same thing to the label, and it vanishes.  In fact, the only way I could get it to stay was to cheat and use the HTML escaped value of the sign: &amp;#37;  

The only snag with that, any time you edit the item, you have to reinsert that escaped value every time.

**Comment by bernisys** [comment]
Same here with cacti 1.1.35 ... just stepped into that little trap :)
interesting, that even &percnt; does not work - you have to resort to the &#37; notation

any news on that issue?

**Comment by cigamit** [comment]
This is a tricky issue with escaping of RRDtool command components.  It's not real high on my list.  A pull request would be appreciated if you can muster one.

**Comment by netniV** [comment]
I believe that this was fixed with https://github.com/Cacti/cacti/pull/3098
