### ISSUE TITLE
CLog: preg_match can blow up log file

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1419]
So this morning I search for todays date with the time being of the hour of midnight.  To achieve this I used a filter of something like:

```
2018-02-28 00:00
```

This resulted in functions.php spitting it's dummy out that 0 was an invalid modifier.  And as a result of that, for every log line, a new entry appeared.

Offending code is:
```php
return (strpos(strtolower($line), $filter) !== false || preg_match('/' . $filter . '/i', $line));
```
I think we need to add an @ in front of the preg_match to make sure that doesn't occur and silently fails.

**Comment by cigamit** [comment]
There is a validation function for regular expressions.

**Comment by cigamit** [comment]
Resolved.
