### ISSUE TITLE
Data Input Methods: Select unused field when adding new input fields

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1422]
When adding data input fields, the next unused field should be automatically selected to enable faster creation of fields.  Additionally, using a previously selected field should present a warning since that field will be inserted twice and used in the "field order" making every field offset.

**Comment by netniV** [comment]
I have created a pull request for this so will now close the issue.

**Comment by cigamit** [comment]
Can you upload an animation of before and after behavior?  Seeing is believing.

**Comment by netniV** [comment]
Before, it always selects the very first field.  So, if you create a data input method, set it:

```
ss_method <first> <second> <third> <fourth>
```
You then go to add an input field, before the fix, will ALWAYS select <first> as the field.

This change detects that you've previously used <first>, so picks <second> as the default field you want to use.  Which is logical, why would you use first again?  If all fields have been used, it will always end up defaulting to <first> if you try to add subsequent fields.

And don't forget that it uses the sequence order anyway, so I'm not sure you should be allowed to use a field more than once? That may be a further modification.  As for an animation, I can do that next week but this doesn't take any functionality away only switches the default field used when creating a new input field
