### ISSUE TITLE
Messsaging: Hitting Return does not close dialog

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1423]
If you are trying to move quickly between screens creating objects, you might hit return to clear the 5-second autoclosing success messgae, but this in fact pauses the window and forces you to use the mouse to close the dialog which will now remain until you do.

**Comment by cigamit** [comment]
You will have to demonstrate this using an animation.  Use ScreenToGif to create animation.

**Comment by netniV** [comment]
I'll have to find a mac alternative or record it at work tomorrow on my lunch break (already have a gif screen grabber there).

Steps to reproduce are simple:
1. Save something.
2. Hit return when the confirmation appears
3. Dialog thinks that you've hit pause, try hitting return again

It's not a massive issue, but I use the keyboard a lot so I have a tendency to use the keyboard where I can.  i'm sure there will be others out there who'd do the same 👍

**Comment by netniV** [comment]
![mar-04-2018 17-29-58](https://user-images.githubusercontent.com/9052188/36948356-c224d6d0-1fd1-11e8-9eca-1dd2147c7175.gif)

This screenshot demonstrates what I mean. You can see the click of the mouse on the Save button (just to demonstrate it's captured it normally i'd hit return).  When the dialog appears, I then hit return and the pause button vanishes and the count down vanishes (which indicates that I clicked on pause).

**Comment by cigamit** [comment]
Okay this is resolved with the latest update to layout.js.
