### ISSUE TITLE
Cacti Version 1.1.36 - Poller Server Logs

### ISSUE THREAD

**Issue by anarkia1976** [Cacti/cacti#1426]
I have update my lab to the latest release but i have this error on remote poller:

2018/03/01  11:35:05 - SYSTEM STATS: Time:0.5970 Method:spine Processes:2 Threads:2  Hosts:0 HostsPerProcess:0 DataSources:0 RRDsProcessed:0
2018/03/01 11:35:04 - POLLER: Poller[Cacti-Poller] NOTE: Poller Int: '300', Cron Int: '300', Time Since Last: '300.61', Max Runtime '298', Poller Runs: '1'
2018/03/01 11:35:03 - POLLER: Poller[Cacti-Poller] ERROR: PHP Source File '/usr/share/cacti/include/csrf/csrf-secret.php' from Cache has a Syntax error!

**Comment by netniV** [comment]
That occurs if the poller is writing out a field and finds it has an error when running php -l against it.
```
php -l /usr/share/cacti/include/csrf/csrf-secret.php
```
If you run that it will tell us what the error is as the poller doesn't appear to capture that.

**Comment by anarkia1976** [comment]
Very strange, no problem after command execution:
php -l /usr/share/cacti/include/csrf/csrf-secret.php
No syntax errors detected in /usr/share/cacti/include/csrf/csrf-secret.php

but i have the error logged:
2018/03/02 08:30:05 - SYSTEM STATS: Time:0.3322 Method:spine Processes:2 Threads:2 Hosts:0 HostsPerProcess:0 DataSources:0 RRDsProcessed:0
2018/03/02 08:35:05 - POLLER: Poller[2] ERROR: PHP Source File '/usr/share/cacti/include/csrf/csrf-secret.php' from Cache has a Syntax error!
2018/03/02 08:35:06 - POLLER: Poller[2] NOTE: Poller Int: '300', Cron Int: '300', Time Since Last: '300.87', Max Runtime '298', Poller Runs: '1'
2018/03/02 08:35:06 - SYSTEM STATS: Time:0.3763 Method:spine Processes:2 Threads:2 Hosts:0 HostsPerProcess:0 DataSources:0 RRDsProcessed:0
2018/03/02 08:40:04 - POLLER: Poller[2] ERROR: PHP Source File '/usr/share/cacti/include/csrf/csrf-secret.php' from Cache has a Syntax error!
2018/03/02 08:40:05 - POLLER: Poller[2] NOTE: Poller Int: '300', Cron Int: '300', Time Since Last: '299.92', Max Runtime '298', Poller Runs: '1'
2018/03/02 08:40:05 - SYSTEM STATS: Time:0.3774 Method:spine Processes:2 Threads:2 Hosts:0 HostsPerProcess:0 DataSources:0 RRDsProcessed:0
2018/03/02 08:45:05 - POLLER: Poller[2] ERROR: PHP Source File '/usr/share/cacti/include/csrf/csrf-secret.php' from Cache has a Syntax error!
2018/03/02 08:45:06 - POLLER: Poller[2] NOTE: Poller Int: '300', Cron Int: '300', Time Since Last: '301.87', Max Runtime '298', Poller Runs: '1'
2018/03/02 08:45:06 - SYSTEM STATS: Time:0.5066 Method:spine Processes:2 Threads:2 Hosts:0 HostsPerProcess:0 DataSources:0 RRDsProcessed:0

**Comment by netniV** [comment]
Hmm, so how do you have an error that isn't an error....

Try this temporary patch and see if it helps:
```diff
diff --git a/lib/poller.php b/lib/poller.php
index 9df0d4d..9cb8ffb 100644
--- a/lib/poller.php
+++ b/lib/poller.php
@@ -879,7 +879,11 @@ function resource_cache_out($type, $path) {
                                                                                        cacti_log("ERROR: Cache in cannot write to '" . $mypath . "', purge this location");
                                                                                }
                                                                        } else {
-                                                                               cacti_log("ERROR: PHP Source File '" . $mypath . "' from Cache has a Syntax error!", false, 'POLLER');
+                                                                               cacti_log("ERROR: PHP Source File '" . $mypath . "' from Cache has a Syntax error ($exit)!", false, 'POLLER');
+                                                                               $lines = explode("\n",$output);
+                                                                               foreach ($lines as $line) {
+                                                                                       cacti_log("ERROR: PHP Source File '" . $mypath . "': $line!", false, 'POLLER');
+                                                                               }
                                                                        }

                                                                        unlink($tmpfile);
```

**Comment by netniV** [comment]
There were no lines afterwards?

**Comment by netniV** [comment]
Just one exclamation?

**Comment by netniV** [comment]
Error 127 means that the command was not found. Is your PHP path defined on the remote server?

Add the following line:
```
cacti_log("ERROR: PHP Source File '$mypath' attempted to run: $php_path -l $tmpfile", false, 'POLLER');
```
Between the cacti_log() and explode() lines.

**Comment by anarkia1976** [comment]
diff --git a/lib/poller.php b/lib/poller.php
index 9df0d4d..9cb8ffb 100755
--- a/lib/poller.php
+++ b/lib/poller.php
@@ -879,7 +879,11 @@ function resource_cache_out($type, $path) {
                                                                                        cacti_log("ERROR: Cache in cannot write to '" . $mypath . "', purge this location");
                                                                                }
                                                                        } else {
-                                                                               cacti_log("ERROR: PHP Source File '" . $mypath . "' from Cache has a Syntax error!", false, 'POLLER');
+                                                                               cacti_log("ERROR: PHP Source File '" . $mypath . "' from Cache has a Syntax error ($exit)!", false, 'POLLER');
+                                                                               $lines = explode("\n",$output);
+                                                                               foreach ($lines as $line) {
+                                                                                       cacti_log("ERROR: PHP Source File '" . $mypath . "': $line!", false, 'POLLER');
+                                                                               }
                                                                        }

                                                                        unlink($tmpfile);

**Comment by netniV** [comment]
Your missing the ```diff around the code there :)

**Comment by anarkia1976** [comment]
sorry :+1:

**Comment by netniV** [comment]
Err, yeah between those first two + lines, add the extra code I gave you above.  That shows the command that's being run.

**Comment by anarkia1976** [comment]
I have applied the patch, do you see diff between my diff and yours?

**Comment by anarkia1976** [comment]
I have deleted the file and impoted the same from my production cacti and now the problem is fixed, no more error in the log file.
Do you want to close this thread as resolved?
thanks

**Comment by netniV** [comment]
I was after the command it was running.  I suspect that it was running against a temporary file and it was that temporary file that caused the issue.  That was why I also wanted you to add:

```
cacti_log("ERROR: PHP Source File '$mypath' attempted to run: $php_path -l $tmpfile", false, 'POLLER');
```
Which would have listed the command used and the temporary file.

Full diff would have been:
```diff
diff --git a/lib/poller.php b/lib/poller.php
index 9df0d4d..9cb8ffb 100644
--- a/lib/poller.php
+++ b/lib/poller.php
@@ -879,7 +879,12 @@ function resource_cache_out($type, $path) {
 											cacti_log("ERROR: Cache in cannot write to '" . $mypath . "', purge this location");
 										}
 									} else {
-										cacti_log("ERROR: PHP Source File '" . $mypath . "' from Cache has a Syntax error!", false, 'POLLER');
+										cacti_log("ERROR: PHP Source File '" . $mypath . "' from Cache has a Syntax error ($exit)!", false, 'POLLER');
+										cacti_log("ERROR: PHP Source File '$mypath' attempted to run: $php_path -l $tmpfile", false, 'POLLER');
+										$lines = explode("\n",$output);
+										foreach ($lines as $line) {
+											cacti_log("ERROR: PHP Source File '" . $mypath . "': $line!", false, 'POLLER');
+										}
 									}
 
 									unlink($tmpfile);
```

**Comment by anarkia1976** [comment]
The problem occur every time you change a file on the main cacti and the resource is updated from cache on the poller.

This is the output without the new patch:
2018/03/02 12:25:03 - POLLER: Poller[Cacti-Poller] ERROR: PHP Source File '/usr/share/cacti/lib/poller.php' from Cache has a Syntax error!

This is the output with the new patch:
2018/03/02 12:30:03 - POLLER: Poller[2] ERROR: PHP Source File '/usr/share/cacti/resource/snmp_queries/prova.php' from Cache has a Syntax error (127)!
2018/03/02 12:30:03 - POLLER: Poller[2] ERROR: PHP Source File '/usr/share/cacti/resource/snmp_queries/prova.php' attempted to run: /bin/php -l /tmp/cachecheck.php
2018/03/02 12:30:03 - POLLER: Poller[2] ERROR: PHP Source File '/usr/share/cacti/resource/snmp_queries/prova.php': !
2018/03/02 12:30:04 - POLLER: Poller[2] NOTE: Poller Int: '300', Cron Int: '300', Time Since Last: '300.53', Max Runtime '298', Poller Runs: '1'
2018/03/02 12:30:05 - SYSTEM STATS: Time:0.4098 Method:spine Processes:2 Threads:2 Hosts:0 HostsPerProcess:0 DataSources:0 RRDsProcessed:0

**Comment by netniV** [comment]
Does cachecheck.php exist?

**Comment by anarkia1976** [comment]
no. :+1:

**Comment by netniV** [comment]
Hmm, OK, I will create another patch for you... this will create the output php file as a temporary file and then prevent the unlink() from occurring.  That ensures that the output file is unique and that we can then verify the file ourselves afterwards.

**Comment by netniV** [comment]
Try this patch, you would be best doing `git checkout lib/poller.php` if you are using git, or reverting back to the original version at least.

```diff
diff --git a/lib/poller.php b/lib/poller.php
index 9df0d4d..f398d6b 100644
--- a/lib/poller.php
+++ b/lib/poller.php
@@ -860,15 +860,10 @@ function resource_cache_out($type, $path) {

                                                /* if the file type is PHP check syntax */
                                                if ($extension == 'php') {
-                                                       if ($config['cacti_server_os'] == 'win32') {
-                                                               $tmpfile = '%TEMP%' . DIRECTORY_SEPARATOR . 'cachecheck.php';
-                                                               $tmpdir  = '%TEMP%';
-                                                       } else {
-                                                               $tmpfile = '/tmp/cachecheck.php';
-                                                               $tmpdir  = '/tmp';
-                                                       }
+                                                       $tmpdir = sys_get_temp_dir();
+                                                       $tmpfile = tempnam($tmpdir,'ccp').'php';

-                                                       if ((is_writeable($tmpdir) && !file_exists($tmpfile)) || (file_exists($tmpfile) && !is_writable($tmpfile))) {
+                                                       if ((is_writeable($tmpdir) && !file_exists($tmpfile)) || (file_exists($tmpfile) && is_writable($tmpfile))) {
                                                                if (file_put_contents($tmpfile, $contents) !== false) {
                                                                        $output = system($php_path . ' -l ' . $tmpfile, $exit);
                                                                        if ($exit == 0) {
@@ -879,10 +874,15 @@ function resource_cache_out($type, $path) {
                                                                                        cacti_log("ERROR: Cache in cannot write to '" . $mypath . "', purge this location");
                                                                                }
                                                                        } else {
-                                                                               cacti_log("ERROR: PHP Source File '" . $mypath . "' from Cache has a Syntax error!", false, 'POLLER');
+                                                                               cacti_log("ERROR: PHP Source File '" . $mypath . "' from Cache has an error whilst checking syntax ($exit)!", false, 'POLLER');
+                                                                               cacti_log("ERROR: PHP Source File '" . $mypath . "' tried to execute: $php_path -l $tmpfile", false, 'POLLER');
+                                                                               $lines = explode("\n",$output);
+                                                                               foreach ($lines as $line) {
+                                                                                       cacti_log("ERROR: PHP Source File '" . $mypath . "': $line!", false, 'POLLER');
+                                                                               }
                                                                        }

-                                                                       unlink($tmpfile);
+                                                                       //unlink($tmpfile);
                                                                } else {
                                                                        cacti_log("ERROR: Unable to write file '" . $tmpfile . "' for PHP Syntax verification", false, 'POLLER');
                                                                }
```

I think this patch should be merged eventually anyway so I'll create a PR for it once we knuckle down the issue.

**Comment by anarkia1976** [comment]
I have applied the patch, no more cache erros.

**Comment by netniV** [comment]
So I think the chances are, there was a timing conflict.  Two different processes trying to write to it at the same time.  I'll create the PR and you continue to see if you can break it lol.

**Comment by anarkia1976** [comment]
good. closed.

**Comment by netniV** [comment]
This is now in pr #1431
