### ISSUE TITLE
Cacti Version 1.1.36 - LDAP Auth Error

### ISSUE THREAD

**Issue by anarkia1976** [Cacti/cacti#1427]
I have update my lab to the latest release but i have this error when i try to authenticate with ldap:

2018/03/01 11:32:23 - AUTH LOGIN: LDAP Error: Unable to find users DN
2018/03/01 11:32:23 - AUTH LDAP_SEARCH: Unable to find users DN
2018/03/01 11:32:23 - CMDPHP PHP ERROR WARNING Backtrace:  (/index.php: 25 include)(/include/auth.php: 103  include)(/auth_login.php: 126 cacti_ldap_search_dn)(/lib/ldap.php: 152  Search)(/lib/ldap.php: 489  ldap_search)(CactiErrorHandler)(/lib/functions.php: 4586  cacti_debug_backtrace)
2018/03/01 11:32:23 - ERROR PHP WARNING: ldap_search(): Search:  Operations error in file: /usr/share/cacti/lib/ldap.php  on line: 489

**Comment by netniV** [comment]
What version were you using before?

**Comment by anarkia1976** [comment]
Cacti Version 1.1.35.

**Comment by netniV** [comment]
There has been no change to the auth code as far as I am aware.  If you roll back to 1.1.35 does it go away?

**Comment by anarkia1976** [comment]
I think the problem was also on version 1.1.35, but i don't have specific logs.
I remember the same problem, it occur only when you make a fresh install and ldap settings.

**Comment by netniV** [comment]
So, the default setting isn't working? OK, that gives me something to look at.

**Comment by netniV** [comment]
Is your PHP path defined on the remote server?
Add the following line:
```
cacti_log("ERROR: PHP Source File '$mypath' attempted to run: $php_path -l $tmpfile", false, 'POLLER');
```
Between the cacti_log() and explode() lines.

**Comment by anarkia1976** [comment]
I have made these steps:
- fresh install of cacti version 1.1.36

- enabled ldap auth like this screenshot whithout error:
![capture](https://user-images.githubusercontent.com/1744639/36889956-70869146-1dfc-11e8-9b07-6b9a46eb208f.PNG)

- after this when we try to authenticate log says:
AUTH LDAP: insufficient access

- changed mod from "no searching" to "anonymous" and log says:
2018/03/01 11:32:23 - CMDPHP PHP ERROR WARNING Backtrace: (/index.php: 25 include)(/include/auth.php: 103 include)(/auth_login.php: 126 cacti_ldap_search_dn)(/lib/ldap.php: 152 Search)(/lib/ldap.php: 489 ldap_search)(CactiErrorHandler)(/lib/functions.php: 4586 cacti_debug_backtrace)
2018/03/01 11:32:23 - ERROR PHP WARNING: ldap_search(): Search: Operations error in file: /usr/share/cacti/lib/ldap.php on line: 489
and then after fill login form:
2018/03/01 11:32:23 - AUTH LOGIN: LDAP Error: Unable to find users DN
2018/03/01 11:32:23 - AUTH LDAP_SEARCH: Unable to find users DN

- changed mod from "anonymous" to "no searching" and now ldap authentication work like a charm

**Comment by netniV** [comment]
Did you set the mode originally, or was it just defaulted?

**Comment by anarkia1976** [comment]
Now it is set like this:
![capture](https://user-images.githubusercontent.com/1744639/36890121-0108c392-1dfd-11e8-9003-fae2876d9dbb.PNG)

**Comment by netniV** [comment]
What I am trying to understand is, was the searching mode already there, You didn't change it the first time when you got the first error, you just saved as it was?

**Comment by netniV** [comment]
If you could do it one more time, but after you do the initial save can you run the following query:
```sql
select * from settings where name='ldap_mode'
```

**Comment by anarkia1976** [comment]
I don't have see errors when i have set it the first time, but the authentication diden't work and ldap log say:
AUTH LDAP: insufficient access

**Comment by anarkia1976** [comment]
with "anonymous search":
MariaDB [cacti]> select * from settings where name='ldap_mode';
+-----------+-------+
| name      | value |
+-----------+-------+
| ldap_mode | 1     |
+-----------+-------+
1 row in set (0.00 sec)

with "no searching":

MariaDB [cacti]> select * from settings where name='ldap_mode'
    -> ;
+-----------+-------+
| name      | value |
+-----------+-------+
| ldap_mode | 0     |
+-----------+-------+
1 row in set (0.00 sec)

**Comment by netniV** [comment]
Yeah, I wanted to see what the value was like before you set it anything including anonymous.

**Comment by netniV** [comment]
Lets simulate this, do the following
```sql
delete from settings where name = 'ldap_mode';
```
Then go to the LDAP settings and then just hit save

Then run the SQL query again:
```sql
select * from settings where name='ldap_mode';
```

**Comment by anarkia1976** [comment]
MariaDB [cacti]> delete from settings where name = 'ldap_mode';
Query OK, 1 row affected (0.00 sec)

MariaDB [cacti]> select * from settings where name='ldap_mode';
Empty set (0.01 sec)

MariaDB [cacti]> select * from settings where name='ldap_mode';
+-----------+-------+
| name      | value |
+-----------+-------+
| ldap_mode | 0     |
+-----------+-------+
1 row in set (0.00 sec)

**Comment by netniV** [comment]
OK not what I expected 👎

**Comment by netniV** [comment]
The log you pasted at the start, was that from the CLOG page or direct from the log file? (ie, was it in reverse order).

**Comment by anarkia1976** [comment]
CLog page. It's impossible now to reproduced. sorry.
