### ISSUE TITLE
Graphs: Add more information to error image

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1428]
Currently, no matter whether there is a problem with the poller not polling, or some other error no data is created and the generic, unable to find RRD file error is used.  This should be updated to show that the item was never even polled (which occurs when CRON is broken or not setup), a permission error creating the RRD file (this can be tested within the script), etc.

This would be more beneficial within the graph error in helping diagnosing why a graph isn't displaying.

**Comment by cigamit** [comment]
Resolved.
