### ISSUE TITLE
Graph Templates: Data Source Input does not show source

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1429]
When editing a Graph Template, you can click on the data source for the template and it shows the associated fields.  You can click and untick graph items to associate them with that data source.  However, you have no real idea what data source that is if the data source has been badly named as it does not appear on the screen.

Or worse, should you have two fields of the same name from different sources, the data source can show the same name... but you have no idea which one you are on (unless you can figured it out from the ticked graph items).

![image](https://user-images.githubusercontent.com/9052188/36848394-0849b020-1d59-11e8-8713-9e633c81df5e.png)

**Comment by netniV** [comment]
@cigamit This is actually not so straight forward because apparently, you can tick the fields to say they are associated with this data source, they can still be expecting to find a field name that isn't even present in that data source.

For example, I was creating NTP templates and I had Association and Entity objects with the same fields.  Association where via Get SNMP Data (Indexed) whilst the Entity were direct Get SNMP Data.  But a lot of the field names are the same between the two object types (for example Jitter, Dispersion, etc).  The steps I took were:

1. Copied the graph template:
2. Edited a graph item and changed the field from _NTP Association Delay (Delay)_ to _NTP Entity Delay (Delay)_ 
3. Repeated for each graph item for the same field change.
4. Deleted the duplicated data source (which interestingly had the same name).
5. Copied the graph template again
6. Saved the first field after correcting (as pre step 2)
7. Edited the new data source and ticked all fields to transfer them over.
8. Graph Item shows small field name (eg, Dispersion) so looked ok
9. Double checked graph items and realised they were still on NTP Association (Dispersion) except for the first one I had actually changed.

This raises two questions, why allow selection of a field that won't be in the data source, and why allow migration via the tick boxes from one data source to another?

**Comment by cigamit** [comment]
As previously mentioned, the 'Associated Graph Items' is a legacy from the past that confuses just about everyone who uses Cacti.  There needs to be a better way of editing templates.

**Comment by cigamit** [comment]
I would prefer that we remove the 'Graph Item Inputs' entirely except that it is also when prompting the user at create time for certain graph item data.

**Comment by netniV** [comment]
I like the simple answer to remove it from the gui/api (as much as possible) and just have it created automatically.  The only thing I am unsure of, does that affect aggregate graphs?

**Comment by cigamit** [comment]
Well, for now let's table this.

**Comment by netniV** [comment]
Would you object if I put code in to at least display the source ( as seen when editing the field? )

**Comment by cigamit** [comment]
Nope.  That's fine.

**Comment by netniV** [comment]
I believe that due to other changes we have made, the data source names already appear on the data source items now.
