### ISSUE TITLE
Plugin install hover message sometimes shows line breaks rather than formatted text

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1437]
If you quickly move between plugin rows from and to a row that has the install icon, if the icon has dependancy errors, then sometimes the <br> tags are displayed rather than interpreted by the browser.

![screen shot 2018-03-03 at 00 11 45](https://user-images.githubusercontent.com/9052188/36927881-9a684672-1e78-11e8-8629-64427c5c8f03.png)

**Comment by netniV** [comment]
This is how it looks when it's working properly.  I think it's a timing issue somehow... but I can't for the life of me see why it would work one time and then not the other:

![image](https://user-images.githubusercontent.com/9052188/36938246-ef5df674-1f16-11e8-88bb-ec142bdf8387.png)

**Comment by netniV** [comment]
Try this:

![mar-04-2018 17-26-24](https://user-images.githubusercontent.com/9052188/36948330-3da901ce-1fd1-11e8-8776-a76acd7e889d.gif)

**Comment by cigamit** [comment]
Seems like a jQueryUI issue.  What it does it removes the title attribute during display, and then returns it to the prior setting once you hover off the element.  So, must have something to do with jQueryUI.

**Comment by netniV** [comment]
Yeah I figured it's a timing issue, not quite sure why it would display the <br /> sometimes and others it would be interpreted.  It seem like it's escaping the characters like via htmlescape sometimes.

**Comment by cigamit** [comment]
Yea, it's in jQueryUI.  Another reason to update.  Might be fixed there.  Since you have a repeatable case, you might want to test using the latest.

**Comment by netniV** [comment]
I am wondering if I managed to get the HTML working when it shouldn't be given:
http://jqueryui.com/upgrade-guide/1.10/#tooltip

**Comment by cigamit** [comment]
Review the jQueryUI page demonstrations.  HTML is used in some of them.  Check this example: http://jqueryui.com/tooltip/#custom-content

**Comment by netniV** [comment]
Yeah, that would suggest I'm not doing anything strange with the jQuery.  It may be worth raising a bug report with them.  I may do that this weekend if I figure out how.

**Comment by cigamit** [comment]
See if you can reproduce in 1.12.  If not, then it's likely already been resolved.

**Comment by cigamit** [comment]
I resolved this in a semi grubby way, but it's fixed.
