### ISSUE TITLE
Editing tree moves item to top

### ISSUE THREAD

**Issue by chris-technicate** [Cacti/cacti#1440]
I find when I edit any tree, upon saving it moves the tree branch under edit to the top requiring the order to be resorted each time you add a graph or host or even branch.

Especially cumbersome if you are not using alphabetical order.

**Comment by netniV** [comment]
That sounds like the code isn't saving the sequences.  A problem I swore I fixed recently in #1201 and I know you're on a later version already.  But this seems to be related to the branches within a tree so it's probably a similar issue.

**Comment by cigamit** [comment]
Could be that the tree, or the tree branch has alphabetic ordering too.  These things are automatic.

**Comment by cigamit** [comment]
No feedback.

**Comment by netniV** [comment]
That’s my bad. Not got around to it

**Comment by cigamit** [comment]
Should I re-open?

**Comment by netniV** [comment]
Oops, look what I can do now :D

I'll follow this up next week with @chris-technicate and confirm it's fully resolved.

**Comment by cigamit** [comment]
I'm going to close this.  Branches always go before Graphs or Devices.  It's just the way the UI works.  Sorting is controlled first by branches, and then by devices/graphs.
