### ISSUE TITLE
Cacti Template- Cyberoam UTM

### ISSUE THREAD

**Issue by komathodivijay** [Cacti/cacti#1444]
Required the template to add the Cyberoam UTM box in Cacti. Attached the MIB File.
[5425_CYBEROAM-MIB.txt](https://github.com/Cacti/cacti/files/1779744/5425_CYBEROAM-MIB.txt)

**Comment by cigamit** [comment]
Well, when you have it completed, please create a pull request and we will see about adding it to our templates.  What will be more appropriate to do is to post your completed template to the Cacti Forums.  There is a forum area specifically create for people to publish their work.
