### ISSUE TITLE
Devices - Create Graphs - UI selection does not work on existing items

### ISSUE THREAD

**Issue by BSOD2600** [Cacti/cacti#145]
Latest e3f5ee822c492cda90e5980caa61e545ba4e94e0
IE11

In this picture, the Virtual & Physical Memory data sources have already been created, but hovering the mouse over them does not highlight (like it does for the D: drive)... nor are the checkboxes checked/disabled/etc to show the user they cannot select them.  something in the UI needs to change.

![image](https://cloud.githubusercontent.com/assets/5741811/21669766/4da67e1e-d2c3-11e6-95e8-491d4921f681.png)

proof they do already exist:
![image](https://cloud.githubusercontent.com/assets/5741811/21669771/5c72d4b0-d2c3-11e6-8703-3c6815424c99.png)

**Comment by cigamit** [comment]
Resolved.  Good catch.  Was some unfinished business.
