### ISSUE TITLE
Cacti Version 1.1.36 "Enable On-demand RRD Updating.The permission real going wrong

### ISSUE THREAD

**Issue by gllewellyn** [Cacti/cacti#1455]
Hi am new to cacti and have just done a new install. Any help , pointers , or tell me where I am just missing the point would be good.

Cacti Server is running :

Cacti Version 1.1.36
Cacti OS unix
NET-SNMP version: 5.7.2
RRDtool Version RRDtool 1.4.x
PHP Version 5.4.16
version 10.2.13-MariaDB
Linux version 3.10.0-693.17.1.el7.x86_64 (rhel 7.4)

I am have a few problems. :(

1) Permissions on /rra keep messing up. I have the below set. And the poller is running as cactiuser.

chown -R cactiuser.cacti /usr/share/cacti/rra/
chmod -R 777 /usr/share/cacti/rra/
chmod g+s -R /usr/share/cacti/rra/

Is there a good document with more detail on best practice for that should be set. Or an idiots guide :)

It seems to get worse if I enable "Enable On-demand RRD Updating" the permission real going wrong. it start changing graphs to apatche (It is driving me mad!)

2) I am using automation to add device. Which works well. But when i try automation for graphs I fail. Graphs for each device show up in the list of Matching Objects. Put do not create even though the rule is enable. I run "apply Automation rules" to one device manually that does not work either. (I can create graphs manually ok)

I am seeing these message in the log (when I run Appliy Automation rules")

2018/03/07 13:52:17 - CMDPHP SQL Backtrace: (/host.php: 62 form_actions)(/host.php: 337 automation_update_device)(/lib/api_automation.php: 3644 automation_execute_data_query)(/lib/api_automation.php: 2078 create_dq_graphs)(/lib/api_automation.php: 2329 db_fetch_assoc)(/lib/database.php: 360 db_fetch_assoc_prepared)(/lib/database.php: 401 cacti_debug_backtrace)
2018/03/07 13:52:17 - DBCALL ERROR: SQL Assoc Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1
2018/03/07 13:52:17 - DBCALL ERROR: SQL Assoc Failed!, Error:1064, SQL:'SELECT * FROM (SELECT host_id, snmp_query_id, snmp_index, MAX(CASE WHEN field_name ='ifDescr' THEN field_value ELSE NULL END) AS 'ifDescr', MAX(CASE WHEN field_name ='ifHighSpeed' THEN field_value ELSE NULL END) AS 'ifHighSpeed', MAX(CASE WHEN field_name ='ifHwAddr' THEN field_value ELSE NULL END) AS 'ifHwAddr', MAX(CASE WHEN field_name ='ifIndex' THEN field_value ELSE NULL END) AS 'ifIndex', MAX(CASE WHEN field_name ='ifName' THEN field_value ELSE NULL END) AS 'ifName', MAX(CASE WHEN field_name ='ifOperStatus' THEN field_value ELSE NULL END) AS 'ifOperStatus', MAX(CASE WHEN field_name ='ifSpeed' THEN field_value ELSE NULL END) AS 'ifSpeed', MAX(CASE WHEN field_name ='ifIP' THEN field_value ELSE NULL END) AS 'ifIP' FROM host_snmp_cache AS hsc WHERE snmp_query_id=1 AND host_id=262 GROUP BY snmp_query_id, snmp_index) as a WHERE'

**Comment by netniV** [comment]
It will change the user to apache because that is the user that the website runs as and you've asked the website to do the updating.

**Comment by cigamit** [comment]
There are multiple examples on the Website, or if you read Thomas Urban's book, he explains how to put a sticky bit on the group permissions to work around this.  Running both the cron and the website as the same user is the easiest, though can present other challenges.
