### ISSUE TITLE
Increase minimum php version maintaining support for RHEL6

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1456]
After the recent debate over OS versions to PHP versions, I came across another issue.  Despite the official minimum version being 5.4+ when you install, the minimum listed is 5.2

![screen shot 2018-03-07 at 19 19 50](https://user-images.githubusercontent.com/9052188/37113197-8eaccd86-223c-11e8-8815-e00fec594c54.png)

The installer should be reviewed to make sure the minimum requirements match the supported requirements from v1.2

**Comment by anarkia1976** [comment]
@cigamit @netniV 
guys, latest release it working very good (main + poller solution), thanks a lot for all.

**Comment by cigamit** [comment]
What version of PHP?

**Comment by cigamit** [comment]
Resolved.

**Comment by cigamit** [comment]
I know.  However, I don't want to have people have to R&R php in the distro.  Once we release 1.2, we will hold firm on that since the 1.1.x branch is pretty darn good right now.
