### ISSUE TITLE
Error in logs when creating new graphs

### ISSUE THREAD

**Issue by iceking2nd** [Cacti/cacti#1458]
03/09/2018  04:51:59 - ERROR PHP WARNING: sizeof(): Parameter must be an array or  an object that implements Countable in file:  /home/cacti/lib/template.php  on line: 805
--
03/09/2018 04:51:59 - CMDPHP PHP ERROR WARNING Backtrace:  (/graphs_new.php: 37 form_save)(/graphs_new.php: 123  host_new_graphs)(/graphs_new.php: 395  host_new_graphs_save)(/graphs_new.php: 259  create_complete_graph_from_template)(/lib/template.php: 1033  change_graph_template)(/lib/template.php: 805  sizeof)(CactiErrorHandler)(/lib/functions.php: 4586  cacti_debug_backtrace)

------

[root@cacti lib]# php -v
PHP 7.2.2 (cli) (built: Feb  4 2018 10:14:07) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.2, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans

**Comment by netniV** [comment]
That basically means that it was unable to find an RRD file linked by the graph template item.  You may have a broken template.

**Comment by netniV** [comment]
The problem here is that local_data_ids is using fetch_cell_prepared with a group_concat, but the following line on 808 is checking for an array using sizeof().  I think the sizeof() should be strlen()

**Comment by cigamit** [comment]
@netniV, good catch.  Resolved.
