### ISSUE TITLE
Problems with Graph Automation -C/host.php: 337 automation_update_device)(/lib/api_automation.php: 3644 automation_execute_data_query)(/lib/api_automation.php: 2078 create_dq_graphs)(/lib/api_automation.php: 2329 db_fetch_assoc)(/lib/database.php: 360 db_fetch_assoc_prepared)(/lib/database.php: 401 cacti_debug_backtrace)

### ISSUE THREAD

**Issue by gllewellyn** [Cacti/cacti#1459]
I am having problems with Graph Automation.

Cacti Server is running :

Cacti Version 1.1.36
 Cacti OS unix
 NET-SNMP version: 5.7.2
 RRDtool Version RRDtool 1.4.x
 PHP Version 5.4.16
 version 10.2.13-MariaDB
 Linux version 3.10.0-693.17.1.el7.x86_64 (rhel 7.4)

I am using automation to add device. Which works well. But when i try automation for graphs I fail. Graphs for each device show up in the list of Matching Objects. Put do not create even though the rule is enable. I run "apply Automation rules" to one device manually that does not work either. (I can create graphs manually ok)

I am seeing these message in the log (when I run Appliy Automation rules")

2018/03/07 13:52:17 - C/host.php: 337 automation_update_device)(/lib/api_automation.php: 3644 automation_execute_data_query)(/lib/api_automation.php: 2078 create_dq_graphs)(/lib/api_automation.php: 2329 db_fetch_assoc)(/lib/database.php: 360 db_fetch_assoc_prepared)(/lib/database.php: 401 cacti_debug_backtrace)
 2018/03/07 13:52:17 - DBCALL ERROR: SQL Assoc Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1
 2018/03/07 13:52:17 - DBCALL ERROR: SQL Assoc Failed!, Error:1064, SQL:'SELECT * FROM (SELECT host_id, snmp_query_id, snmp_index, MAX(CASE WHEN field_name ='ifDescr' THEN field_value ELSE NULL END) AS 'ifDescr', MAX(CASE WHEN field_name ='ifHighSpeed' THEN field_value ELSE NULL END) AS 'ifHighSpeed', MAX(CASE WHEN field_name ='ifHwAddr' THEN field_value ELSE NULL END) AS 'ifHwAddr', MAX(CASE WHEN field_name ='ifIndex' THEN field_value ELSE NULL END) AS 'ifIndex', MAX(CASE WHEN field_name ='ifName' THEN field_value ELSE NULL END) AS 'ifName', MAX(CASE WHEN field_name ='ifOperStatus' THEN field_value ELSE NULL END) AS 'ifOperStatus', MAX(CASE WHEN field_name ='ifSpeed' THEN field_value ELSE NULL END) AS 'ifSpeed', MAX(CASE WHEN field_name ='ifIP' THEN field_value ELSE NULL END) AS 'ifIP' FROM host_snmp_cache AS hsc WHERE snmp_query_id=1 AND host_id=262 GROUP BY snmp_query_id, snmp_index) as a WHERE'

**Comment by netniV** [comment]
This may be related to #1347 but if that SQL query is complete, then it's very obviously broken somehow.

**Comment by netniV** [comment]
What rules do you have in place?

**Comment by netniV** [comment]
I can already see a bug:
```diff
diff --git a/lib/api_automation.php b/lib/api_automation.php
index 3964c6b..3b068ba 100644
--- a/lib/api_automation.php
+++ b/lib/api_automation.php
@@ -2317,7 +2317,7 @@ function create_dq_graphs($host_id, $snmp_query_id, $rule) {

        $sql_filter = build_rule_item_filter($automation_rule_items, ' a.');

-       if (sizeof($sql_filter)) $sql_filter = ' WHERE' . $sql_filter;
+       if (strlen($sql_filter)) $sql_filter = ' WHERE' . $sql_filter;

        /* add the additional filter settings to the original data query.
         IMO it's better for the MySQL server to use the original one
```

**Comment by gllewellyn** [comment]
Made that change and now graphs add ok :). Thanks for your quick responce and help.

**Comment by netniV** [comment]
Cool.  Go ahead and close this issue then.
