### ISSUE TITLE
Data Query Cache Items - Count wrong

### ISSUE THREAD

**Issue by BSOD2600** [Cacti/cacti#146]
latest e3f5ee822c492cda90e5980caa61e545ba4e94e0
IE11

The cache shows 207 items (for 1 windows host) but a user is unable to click on the numbers or the Next button to advance. No errors logged. 
![image](https://cloud.githubusercontent.com/assets/5741811/21669825/e216f5a6-d2c3-11e6-96da-3c18280a4540.png)

**Comment by cigamit** [comment]
I can not reproduce this.  Can you please check and see if you have potentially a JavaScript error?  Compare the row count to your table host_snmp_cache and let me know if the numbers are at least accurate.

**Comment by BSOD2600** [comment]
errors in IE11
```

DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
File: utilities.php
HTML1300: Navigation occurred.
File: utilities.php
SEC7115: :visited and :link styles can only differ by color. Some styles were not applied to :visited.
File: utilities.php
```

yes, there are 207 rows
````
mysql> select count(*) from host_snmp_cache;
+----------+
| count(*) |
+----------+
|      207 |
+----------+
1 row in set (0.00 sec)

```

**Comment by cigamit** [comment]
BSOD, let me try with IE.  Working in other browsers.

**Comment by cigamit** [comment]
In testing session with BSOD, we were unable to reproduce with the latest build.
