### ISSUE TITLE
Setting output_format on input type causes no values to be returned

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1461]
I was trying to diagnose a problem for @chris-technicate where his aliases were not working. He had already had a large number of templates created and modified but the base SNMP ones for interfaces and disk partitions were either not present or working properly.  So a week or two back we used the import package to refresh the templates and everything was good.

However, there was an issue with aliases not being found against interfaces were previously they had.  After digging around the code, I could find no issues so I took a look at what was different between git and the installed version.  It found the following different:

```diff
diff --git a/resource/snmp_queries/interface.xml b/resource/snmp_queries/interface.xml
index 7bf3c33..97b1a86 100644
--- a/resource/snmp_queries/interface.xml
+++ b/resource/snmp_queries/interface.xml
@@ -39,6 +39,7 @@
                <ifAlias>
                        <name>Alias (IF-MIB)</name>
                        <method>walk</method>
+                       <output_format>ascii</output_format>
                        <source>value</source>
                        <direction>input</direction>
                        <oid>.1.3.6.1.2.1.31.1.1.1.18</oid>
@@ -46,6 +47,7 @@
                <ifType>
                        <name>Type</name>
                        <method>walk</method>
+                       <output_format>ascii</output_format>
                        <source>value</source>
                        <direction>input</direction>
                        <oid>.1.3.6.1.2.1.2.2.1.3</oid>
```
Upon removing the output_format, all is good once again.  However, given the output_format is ascii which the values are, this shouldn't be an issue.

**Comment by netniV** [comment]
Note, this has now been reported by another user on the forums too:
https://forums.cacti.net/viewtopic.php?p=271541#p271541

**Comment by cigamit** [comment]
Well, that is not good.

**Comment by netniV** [comment]
Another forum user reporting the issue:
https://forums.cacti.net/viewtopic.php?f=21&t=58517

**Comment by chris-technicate** [comment]
I am not sure if it helps, but this box was originally deployed in February 2013 using the latest verision at the time 0.87x, and was upgraded up to 0.88f

Never had issue with this functionality until upgrade.
Hope that helps, though I doubt it.

Most switches/routers are Cisco IOS 12.2 or 15.1 with a few sporadic NX-OS and IOE-XE

**Comment by netniV** [comment]
No it wasn't hex.  It was an ASCII string, hence it works without the output type in.  There's a flaw in the logic which I couldn't quite see when I was looking at it but effectively, it ends up returning nothing rather than a value.

**Comment by cigamit** [comment]
Resolved now.  Issue in lib/data_query.php
