### ISSUE TITLE
Installer: Finish should display status page of tasks in progress

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1463]
When clicking Finish, there can be a long pause especially if templates are being installed.  The page should display a status of what is actually happening and upon completion a link to the main site.

**Comment by netniV** [comment]
I've installed a couple of times now, and on slower machines you can end up with a 'Response timed out' error.

**Comment by cigamit** [comment]
Yea, we should do a `ini_set('max_execution_time', 300);` in the installer right in the beginning.  I think 300 seconds should be good, but maybe not so good after we open up to downloading a dozen or three packages from GitHub during installation.  I was thinking about parsing the packages, and importing them one at a time, and then updating the gui as they are importing.

By the way, on my slowest box (before I bought an SSD), it took about 1 minute to do all the default packages.  Now after an SSD, it takes like 5 seconds ;)

**Comment by netniV** [comment]
This is on my test VM box where there are now 8-10 VMs all fighting each other so probably a lot slower.  However, I think just setting execution time isn't enough really.  The final page should show some form of status all be it temporary via a JSON call to get an updated status set by the longer running process.

**Comment by cigamit** [comment]
Well, doing it in a loop, and then returning the results via either html or some json object should do it.  People will be more tolerant if it's no more than 30 seconds between updates.  A modal interface with a spinner helps too.  We've been using page progress bars, but they don't always work.

**Comment by netniV** [comment]
This is now in the new 1.2 installer I've been working on.
