### ISSUE TITLE
No scrollbars in mobile browsers (1.1.36) 

### ISSUE THREAD

**Issue by sd3m0n** [Cacti/cacti#1466]
There are no scrollbars in mobile browsers (chrome, Samsung browser). So there is no chance to scale anything. The graphs page is truncated and scales like a static image. I don't remember when did it broke. But some versions ago it definitely was OK. And as I remember, I've already posted such issue some time ago and it was fixed. Used skin - modern. 
![20180311_173300](https://user-images.githubusercontent.com/25234512/37255259-6ed2eac2-2552-11e8-81b3-6f3fd60cbe75.png)

**Comment by cigamit** [comment]
If you have more graphs than fit onto the screen, then you will get scroll bars.  You have to hover, over the tree to get a scroll bar over that though.  Should simply be represented by a depression or swipe in that area.

**Comment by sd3m0n** [comment]
Well, if I show up about 20 graphs they don't fit onto the screen. By swyping I can navigate them vertically. Still no scrollbar showing the vertical progress. But the real problem is that there is no horizontal scaling. No horizontal scrollbar. All graphs are just truncated at the right side (as in the screenshot). No matter if it is 1 or more columns to show. Whatever I do, I can't view the full graph. The right part is always truncated.
There is a scrollbar at the log tab therefore. 
![20180311_202320](https://user-images.githubusercontent.com/25234512/37256925-1a096224-256a-11e8-8ed6-99b3b37b2a6b.png)

**Comment by cigamit** [comment]
Should be much better with the 1.1.37 release.

**Comment by sd3m0n** [comment]
Thanx a lot. You are doing a great work!
