### ISSUE TITLE
MySQL timezone and PHP timezone

### ISSUE THREAD

**Issue by TakeMeNL** [Cacti/cacti#1467]
Hey guys, just shooting this in here because i can't find it in the code.
My MySQL server had a different timezone then the PHP was set to, this resulted in the pollers.php showing my poller was unknown/down because of the hour time diff.

Now i see that for updating time rows we use `NOW()` and comparing that to `time()` in PHP. That explains the diff. But this shouldn't be the case right?

Could we maybe think for a solution?
Example not using NOW() but time() or setting the connection to same timezone as php.
Or even better use UTC everywhere and convert to locale (kinda lots of work?)

**Comment by cigamit** [comment]
Just fix the timezones to be correct, and restart apache.  Things will figure themselves out in a few hours at the latest.

**Comment by netniV** [comment]
We could probably add that to the installer as a check?

**Comment by YATV** [comment]
I have a similar problem. My database server must be in the GTM. And monitoring server must be in  + 3GTM. It would be very good, if you could choose the time zone of the monitoring server and it was not dependent on the time zone setting of the database server operating system or the server with php.

**Comment by netniV** [comment]
This will be an issue for all fields or plugins storing simple date values rather than UTC/Timeoffset date values or using unix timestamp (which is timezone independent too).

**Comment by YATV** [comment]
I'm aware of this. It is necessary to add the ability to select the time zone for the monitoring server in the settings. It is also necessary to ask all developers of plugins to draw his attention to this setting. And ask them to change their plugins.

**Comment by netniV** [comment]
The only way to enforce something like that would be for a major release and require that a plugin has a minimum level of requirement set to that release.  However, that does not ensure that the plugin is validated to work as there is no review process of third party plugins.

**Comment by cigamit** [comment]
Just thinking over this, we need to add the zone information of the remote data collector form and a new column in the pollers table, and then a check during connection to swtich the zone during initial connection.  Affects both spine and Cacti.  Not too complicated.

**Comment by bad-crc** [comment]
I think that better way is not using MySQL or PHP timezones and store data in UTC + add in include/config.php something like $time_offset_database and $time_offset_php
For example, when MySQL in Chicago (CDT), but poller in Beijing (CST) we put in config.php this:
```
$time_offset_database = -300; // (60*3) note the minus sign!
$time_offset_php      = 480;  // (60*8)
```
All that Cacti need to do is simple date/time calculation (-:

**Comment by netniV** [comment]
I think I've already mentioned above the issue isn't with the majority of the UNIX_TIMESTAMP fields but more DATE fields and plugins.  Changing our code would be done, tested, etc. However, third parties would also need to do the same work to be compatible.

**Comment by cigamit** [comment]
So, with Cacti 1.2, we will allow you to specify the timezone of the Remote Data Collectors.  The commit is here if you want to hack into a version prior to 1.2.

https://github.com/Cacti/cacti/commit/012ea3965339013f8c49c09e6b1a1c3c90c51873

**Comment by cigamit** [comment]
Please let me know if you believe that this is sufficient, and then please close if so.  Note that all datetime columns will need to be converted to timestamps in the various plugins, and this is beyond the scope of this feature.

**Comment by cigamit** [comment]
Second half of this change is done now.  When the remote data collector is edited, you can now specify the timezone which will then adjust the timezone of the database session to match.  This will ensure that dates are in the correct format.

However, this also does beg the question that we store a number of timestamps in the settings table that does not get this evaluation applied to them.  I'm suspecting that all dates should be stored there in UTC so that we can adjust them.  Also suggest they should always be stored as integers.  Separate issue for now.
