### ISSUE TITLE
Undefined function found in global_languages.php

### ISSUE THREAD

**Issue by tsimmons** [Cacti/cacti#1471]
Hard to say how this happened, but somehow my language (I think established in the $_SESSION) got munged to vi-VN (instead of en-US) which then resulted in 500 errors, PHP complaining about:

    PHP Fatal error:  Call to undefined function set_user_config_option() in /website/cacti/include/global_languages.php on line 56

There is no function named "set_user_config_option" defined in ./lib/functions.php but instead there is a set_config_option() ... should this be changed in global_languages() or is there a yet-to-be-defined user option saving function? 

This is running Cacti 1.1.36 on Apache 2.2.29 with PHP 5.4.45 (MacOS 10.9, Mavericks).

FYI, clearing cookies resolved the issue for me, but I suspect there is a code error as well.

**Comment by netniV** [comment]
I agree, that function does not exist within cacti.  Weirdly, that has been around since 2016 so makes me wonder if the function itself was removed for some reason.

**Comment by netniV** [comment]
I have gone all the way back to 1.0.1 and there has never been a function definition for set_user_config_option.  I'm guessing that we should have the function but @cigamit may suggest that we remove the call instead as we would be automatically overwritting the user preference with what we've detected.

**Comment by tsimmons** [comment]
Yeah, I figured I may have stumbled into a one-off error.

**Comment by cigamit** [comment]
Well, that is embarrassing.

**Comment by cigamit** [comment]
Resolved.  Thanks for catching!

**Comment by netniV** [comment]
And that explains why I couldn't find the function, it was named different than what I expected 👍
