### ISSUE TITLE
Change Device Options - Style needs updating

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1472]
![image](https://user-images.githubusercontent.com/9052188/37391311-b62bf988-2762-11e8-8e6e-9d183925e3ad.png)

When using Console->Management->Devices and selecting many devices, some options show as being editable when nothing is ticked (though they are aren't) on the mass Change Device Options .  

Also, when you have 50+ devices, as the device list is just one continuous list that has a lot of scrolling involved.  I think (somehow) the style show allow it to flow sideways to answer the available space so that if more columns are available it can use them.

**Comment by cigamit** [comment]
Resolved.
