### ISSUE TITLE
Check possibility for creation of temporary tables on install

### ISSUE THREAD

**Issue by gdsotirov** [Cacti/cacti#1474]
Cacti's [plugin functionality](https://docs.cacti.net/plugins) relays on the possibility for creation of temporary tables in MySQL/MariaDB. This requires [CREATE TEMPORARY TABLES privilege](https://dev.mysql.com/doc/refman/5.7/en/privileges-provided.html#priv_create-temporary-tables) to be granted to the cacti user. If this privilege isn't granted (like it was in my case - see topic [Plugins not showing within cacti](https://forums.cacti.net/viewtopic.php?p=271654#p271654)), the Plugins Management page in Cacti would just display "No Plugins Found" message without any indication of the possible problem and even though plugins are properly installed in `cacti/plugin` directory. As suggested by @netniV in the forum "_it may be worth getting the installer to check for that by trying to create a temporary table_". I think perhaps the installer could check directly for the necessary privileges (e.g. with [SHOW GRANTS](https://dev.mysql.com/doc/refman/5.7/en/show-grants.html)). And I would like to suggest having [cacti/plugins.php](https://github.com/Cacti/cacti/blob/develop/plugins.php) checking and displaying SQL errors (as creation of temporary table without CREATE TEMPORARY TABLES privilege would returns ERROR 1044 (42000): Access denied...) or at least logging them, so that the problem is traceable in debug mode (e.g. as the permission may be incidentally revoked after installation/upgrade).

**Comment by cigamit** [comment]
I'm looking at this during my morning ritual, and I don't see any easy way other than to do what you suggested @netniV.

**Comment by cigamit** [comment]
Resolved.

**Comment by gdsotirov** [comment]
Thanks!
