### ISSUE TITLE
query_ifAlias not working on all interfaces

### ISSUE THREAD

**Issue by gllewellyn** [Cacti/cacti#1475]
Hi have seen posts regarding "Maximum OID's per Get Request" but tried that and does not seem to make any differences.

I am have the same result on all switch interfaces over different / makes / and port count. If I do am SNMP walk I see the info.

Cacit is running the version below listed.

General Information
--
Date | Thu, 15 Mar 2018 17:45:43 +0000
Cacti Version | 1.1.36
Cacti OS | unix
RSA Fingerprint | c4:26:76:95:9d:94:49:00:87:4d:dc:fc:7e:77:c7:3c
NET-SNMP Version | NET-SNMP version: 5.7.2
RRDtool Version | RRDtool 1.4.x
Devices | 48
Graphs | 4,738
Data Sources | Script/Command: 5SNMP Query: 4,734Total: 4,739

Interval | 300
Type | SPINE 1.1.36  Copyright 2004-2017 by The Cacti Group
Items | Action[0]: 9,468Action[1]: 5Total: 9,473
Concurrent Processes | 1
Max Threads | 1
PHP Servers | 1
Script Timeout | 25
Max OID | 10
Last Run Statistics | Time:12.8385 Method:spine Processes:1 Threads:1 Hosts:48 HostsPerProcess:48 DataSources:9473 RRDsProcessed:4739

MemTotal | 16,268.27 MB
MemFree | 11,695.47 MB
Buffers | 247.64 MB
Cached | 3,034.72 MB
Active | 2,524.4 MB
Inactive | 1,640.74 MB
SwapTotal | 2,097.15 MB
SwapFree | 2,097.15 MB

PHP Version | 5.6.34
PHP OS | Linux
PHP uname | Linux nl0123vsm0038.dir.slb.com 3.10.0-693.21.1.el7.x86_64 #1 SMP Fri Feb 23 18:54:16 UTC 2018 x86_64
PHP SNMP | Installed
max_execution_time | 30
memory_limit | 160M

Variable   Current Value   Recommended Value   Comments    version 10.2.13-MariaDB >= 5.6 | version | 10.2.13-MariaDB | >= 5.6

version | 10.2.13-MariaDB | >= 5.6

This is output if i do a verbose query on a device (cisco cat 2960 48 port) Every thing else gets populated apart from ifAlias.

Click to show Data Query output for field 'ifAlias'
--
Total: 0.200000, Delta: 0.010000, Located input field 'ifAlias' [walk] Total: 0.320000, Delta: 0.120000, Executing SNMP walk for data @ '.1.3.6.1.2.1.31.1.1.1.18' |   | Total: 0.200000, Delta: 0.010000, Located input field 'ifAlias' [walk] | Total: 0.320000, Delta: 0.120000, Executing SNMP walk for data @ '.1.3.6.1.2.1.31.1.1.1.18' |  
 
Total: 0.200000, Delta: 0.010000, Located input field 'ifAlias' [walk]
Total: 0.320000, Delta: 0.120000, Executing SNMP walk for data @ '.1.3.6.1.2.1.31.1.1.1.18'

**Comment by netniV** [comment]
This has already been fixed in #1461

**Comment by gllewellyn** [comment]
That worked. thanks

**Comment by gllewellyn** [comment]
mmmm.. Now aplied fix 1461 i get 'ifAlias' if i do a verbos 

Click to show Data Query output for field 'ifAlias'
Total: 3.190000, Delta: 0.110000, Located input field 'ifAlias' [walk]
Total: 4.300000, Delta: 1.110000, Executing SNMP walk for data @ '.1.3.6.1.2.1.31.1.1.1.18'
Found item [ifAlias=''] index: 83886080 [from value]
Found item [ifAlias='TRUNK | 80G | nl0123-hp-itt'] index: 369098752 [from value]
Found item [ifAlias='TRUNK | 40G | nl0123-7k-core_po3'] index: 369098754 [from value]
Found item [ifAlias='SHUTDOWN | not in use | nl0123-3750-1_p01'] index: 369098755 [from value]
Found item [ifAlias='SWP| 20G | nl0123sfbbe01'] index: 369098771 [from value]
Found item [ifAlias='SWP | 20G | nl0123sfboos01'] index: 369098772 [from value]
Found item [ifAlias='SWP | 20G | nl0123sfbmed01'] index: 369098773 [from value]
Found item [ifAlias='SWP | 20G | nl0123sfbfe6'] index: 369098774 [from value]
Found item [ifAlias='SWP | 20G | nl0123sfbfe5'] index: 369098775 [from value]
Found item [ifAlias='SWP | 20G | nl0123sfbfe4'] index: 369098776 [from value]
Found item [ifAlias='SWP | 20G | nl0123sfbfe3'] index: 369098777 [from value]
Found item [ifAlias='SWP | 20G | nl0123sfbfe2'] index: 369098778 [from value]
Found item [ifAlias='SWP | 20G | nl0123sfbfe1'] index: 369098779 [from value]
Found item [ifAlias='SWP | 20G | nl0123sfbedge02_intdmz'] index: 369098780 [from value]
Found item [ifAlias='SWP | 2G | nl0123sfbedge02_dmz'] index: 369098781 [from value]
Found item [ifAlias='SWP | 20G | nl0123sfbedge01_intdmz'] index: 369098782 [from value]
Found item [ifAlias='SWP | 2G | nl0123sfbedge01_dmz'] index: 369098783 [from value]
Found item [ifAlias='TRUNK | 2G | nl0123-gp-portal-pa1'] index: 369098792 [from value]
Found item [ifAlias='TRUNK | 2G | nl0123-gp-portal-pa2'] index: 369098793 [from value]
Found item [ifAlias='TRUNK | 2G | nl0123_monitoring_server'] index: 369098803 [from value]
Found item [ifAlias='TRUNK | 2G | nl0123-hyp01.dir.slb.com'] index: 369098804 [from value]
Found item [ifAlias='TRUNK | 2G | nl0123-ofc-eaf-wlc1'] index: 369098806 [from value]
Found item [ifAlias='TRUNK | 2G | nl0123-ofc-eaf-wlc2'] index: 369098807 [from value]
Found item [ifAlias='SWP | infoblox_internet_facing | 20G'] index: 369098808 [from value]
Found item [ifAlias='SWP | 20G | VDI BLADE'] index: 369098812 [from value]
Found item [ifAlias='SWP | 20G | VDI BLADE'] index: 369098813 [from value]
Found item [ifAlias='SWP | 20G | VDI BLADE'] index: 369098814 [from value]

But now if up apply 

Suggested Values - Graphs
Name
	Order
	Equation
title 		|host_description| - Traffic - |query_ifName| - |query_ifAlias| 	
title 		|host_description| - Traffic - |query_ifName| 	
title 		|host_description| - Traffic - |query_ifAlias| 	
title 		|host_description| - Traffic - |query_ifDescr|/|query_ifIndex| 	
title 		|host_description| - Traffic - |query_ifIP| (|query_ifDescr|) 

And then reply sugested names to graphs I get 👎 

    nl0123-2960-mgmt-1.mgmt.slb.net - Traffic - 466130
    nl0123-2960-mgmt-1.mgmt.slb.net - Traffic - 4769312f302f31
    nl0123-2960-mgmt-1.mgmt.slb.net - Traffic - 4769312f302f3130
    nl0123-2960-mgmt-1.mgmt.slb.net - Traffic - 4769312f302f3131

Before at least geting |host_description| - Traffic - |query_ifName|

**Comment by netniV** [comment]
When you say you are getting these names, where are you getting these names? There are several different suggested names which are at the Graph and Data Source level.  Data Source comes from the data templates, the graph comes from the graph title.

**Comment by gllewellyn** [comment]
So See attached screen shots. After I add fix. 

first I checked I was see in ifAlias

Click to show Data Query output for field 'ifAlias'
 Total: 3.190000, Delta: 0.110000, Located input field 'ifAlias' [walk]
 Total: 4.300000, Delta: 1.110000, Executing SNMP walk for data @ '.1.3.6.1.2.1.31.1.1.1.18'
 Found item [ifAlias=''] index: 83886080 [from value]
 Found item [ifAlias='TRUNK | 80G | nl0123-hp-itt'] index: 369098752 [from value]
 Found item [ifAlias='TRUNK | 40G | nl0123-7k-core_po3'] index: 369098754 [from value]
 Found item [ifAlias='SHUTDOWN | not in use | nl0123-3750-1_p01'] index: 369098755 [from value]
 Found item [ifAlias='SWP| 20G | nl0123sfbbe01'] index: 369098771 [from value]
 Found item [ifAlias='SWP | 20G | nl0123sfboos01'] index: 369098772 [from value]
 Found item [ifAlias='SWP | 20G | nl0123sfbmed01'] index: 369098773 [from value]
 Found item [ifAlias='SWP | 20G | nl0123sfbfe6'] index: 369098774 [from value]
 Found item [ifAlias='SWP | 20G | nl0123sfbfe5'] index: 369098775 [from value]
 Found item [ifAlias='SWP | 20G | nl0123sfbfe4'] index: 369098776 [from value]
 Found item [ifAlias='SWP | 20G | nl0123sfbfe3'] index: 369098777 [from value]
 Found item [ifAlias='SWP | 20G | nl0123sfbfe2'] index: 369098778 [from value]
 Found item [ifAlias='SWP | 20G | nl0123sfbfe1'] index: 369098779 [from value]
 Found item [ifAlias='SWP | 20G | nl0123sfbedge02_intdmz'] index: 369098780 [from value]
 Found item [ifAlias='SWP | 2G | nl0123sfbedge02_dmz'] index: 369098781 [from value]
 Found item [ifAlias='SWP | 20G | nl0123sfbedge01_intdmz'] index: 369098782 [from value]
 Found item [ifAlias='SWP | 2G | nl0123sfbedge01_dmz'] index: 369098783 [from value]
 Found item [ifAlias='TRUNK | 2G | nl0123-gp-portal-pa1'] index: 369098792 [from value]
 Found item [ifAlias='TRUNK | 2G | nl0123-gp-portal-pa2'] index: 369098793 [from value]
 Found item [ifAlias='TRUNK | 2G | nl0123_monitoring_server'] index: 369098803 [from value]
 Found item [ifAlias='TRUNK | 2G | nl0123-hyp01.dir.slb.com'] index: 369098804 [from value]
 Found item [ifAlias='TRUNK | 2G | nl0123-ofc-eaf-wlc1'] index: 369098806 [from value]
 Found item [ifAlias='TRUNK | 2G | nl0123-ofc-eaf-wlc2'] index: 369098807 [from value]
 Found item [ifAlias='SWP | infoblox_internet_facing | 20G'] index: 369098808 [from value]
 Found item [ifAlias='SWP | 20G | VDI BLADE'] index: 369098812 [from value]
 Found item [ifAlias='SWP | 20G | VDI BLADE'] index: 369098813 [from value]
 Found item [ifAlias='SWP | 20G | VDI BLADE'] index: 369098814 [from value]

Then I check my data quirie settings

![data queries - seting](https://user-images.githubusercontent.com/37145853/37508850-c9cfd154-28ec-11e8-9568-798ff8934a93.png)

Then I did a Reapply Suggested Names on a few grahs (you can see in screen shot)

![graphmanagement](https://user-images.githubusercontent.com/37145853/37508879-dfcf060a-28ec-11e8-87a9-28c5bfc351e7.png)

Then did same for devicesource

![datasource](https://user-images.githubusercontent.com/37145853/37508884-e49f8eb6-28ec-11e8-9cc1-64eae25369df.png)

**Comment by gllewellyn** [comment]
Here is where I check am getting the correct info, 

![to confirm i am gettng ifalias info](https://user-images.githubusercontent.com/37145853/37510394-d8465478-28f2-11e8-9fd6-22798b1aefc8.png)
![ouput](https://user-images.githubusercontent.com/37145853/37510407-de079066-28f2-11e8-8973-d5aff0aa8146.png)

**Comment by gllewellyn** [comment]
Also now see the below in the logs regarding data_query.php ,which is new only since I did this fix.

![data_query php](https://user-images.githubusercontent.com/37145853/37510753-217bd612-28f4-11e8-8276-e20167605c98.png)

**Comment by netniV** [comment]
Just to be clear, which fix did you apply?  The @cigamit patch or my removal of the <output_type> ?

**Comment by gllewellyn** [comment]
https://github.com/Cacti/cacti/commit/827bf550c9c6d3315d80db13d118a9dffbe34796

The data_query.php changes ( cigamit )

**Comment by cigamit** [comment]
Are your ifAlias' in another language?

**Comment by netniV** [comment]
I've noticed a problem this morning.  Went to add two devices, both show the description as hex characters.  I am wonder if this is a combination of my and your changes since I would have both.

**Comment by cigamit** [comment]
What was happening in the previous 'GUESS' mode on formatting snmp characters, if if the characters were outside of the normal printable range (lib/snmp.php), they would be removed from the string.  With the output format ASCII, we let unicode characters slide through the cracks.

At that point, the formatting function fails the regular expression match.  I've made an update to attempt to process the character encoding for output that just wants to be left along now.  If it finds an encoding match, it will leave the data alone now.

Honestly, this is some interesting code.

**Comment by gllewellyn** [comment]
adding change now and testing.

**Comment by netniV** [comment]
This has made no difference to me.  In fact, I ran through a test and wierdly the test came back OK:

```php
<?php
$hex = '57:41:4E:20:4D:69:6E:69:70:6F:72:74:20:28:4E:65:74:77:6F:72:6B:20:4D:6F:6E:69:74:6F:72:29:2D:51:6F:53:20:50:61:63:6B:65:74:20:53:63:68:65:64:75:6C:65:72:2D:30:30:30:30:00';
$val = hex2bin(str_replace(":","",$hex));
echo "Hex: $hex\nVal: $val\nmb: ". mb_detect_encoding($val) . "\n";
```

This returned:
```
Hex: 57:41:4E:20:4D:69:6E:69:70:6F:72:74:20:28:4E:65:74:77:6F:72:6B:20:4D:6F:6E:69:74:6F:72:29:2D:51:6F:53:20:50:61:63:6B:65:74:20:53:63:68:65:64:75:6C:65:72:2D:30:30:30:30:00
Val: WAN Miniport (Network Monitor)-QoS Packet Scheduler-0000
mb: ASCII
```

**Comment by netniV** [comment]
This is the output from the SNMP-WALK:
```
iso.3.6.1.2.1.2.2.1.2.22 = Hex-STRING: 57 41 4E 20 4D 69 6E 69 70 6F 72 74 20 28 4E 65
74 77 6F 72 6B 20 4D 6F 6E 69 74 6F 72 29 2D 51
6F 53 20 50 61 63 6B 65 74 20 53 63 68 65 64 75
6C 65 72 2D 30 30 30 30 00
```

**Comment by gllewellyn** [comment]
OK. Will I have tested one switch so far, requered SNMP the under management - device. And then reapply recomended names and it change frorm HEX back to what i expect.
![output](https://user-images.githubusercontent.com/37145853/37595709-b2c9b06a-2b71-11e8-8925-90f0e6514c1d.png)

**Comment by netniV** [comment]
I'm guessing because it's already in Hex-String, I need the "ASCII" type to convert it back to asciii from a HexString.  So, I'll try adding the "ouptut_type" back in again to the XML file and see if that corrects it.

**Comment by netniV** [comment]
Made no difference for me, unless I'm missing something.  Also, the description field never had output format on it, so that doesn't seem to apply.

**Comment by gllewellyn** [comment]
![before](https://user-images.githubusercontent.com/37145853/37596076-dcc0ada0-2b72-11e8-9f00-99273b375507.png)

Above was what I was getting until I appiled your last change, I re-pull the snmp in management - device and in management - graphs reaply recomended names it changes to what I would expect

**Comment by netniV** [comment]
Can you do a verbose query against that device (Edit the Device -> Interface Statistics -> Verbose Query)?

I'm just curious as to whether you see the same kind of output I do?  I can't see what's now wrong with mine.

**Comment by gllewellyn** [comment]
![3](https://user-images.githubusercontent.com/37145853/37596598-a107f2bc-2b74-11e8-97d0-e8a21e9cdbd8.png)
![4](https://user-images.githubusercontent.com/37145853/37596600-a12f7256-2b74-11e8-8495-5eb0f85a6179.png)
![1](https://user-images.githubusercontent.com/37145853/37596603-a187d324-2b74-11e8-8b72-f3b4aa7384ab.png)
![2](https://user-images.githubusercontent.com/37145853/37596604-a1d9aac8-2b74-11e8-81b7-e1f4e789f57b.png)

**Comment by netniV** [comment]
If you snmpwalk that at the command line, are the values returned as Hex-STRING or just string?

The OID should be 1.3.6.1.2.1.2.2.1.2 for description.

**Comment by gllewellyn** [comment]
[root@nl0123vsm0038 gllewellyn]# snmpwalk -v 2c -c ffggdfg 128.58.69.16 1.3.6.1.2.1.2.2.1.2
IF-MIB::ifDescr.83886080 = STRING: mgmt0
IF-MIB::ifDescr.369098752 = STRING: port-channel1
IF-MIB::ifDescr.369098753 = STRING: port-channel2
IF-MIB::ifDescr.369098754 = STRING: port-channel3
IF-MIB::ifDescr.369098755 = STRING: port-channel4
IF-MIB::ifDescr.369098756 = STRING: port-channel5
IF-MIB::ifDescr.369098757 = STRING: port-channel6
IF-MIB::ifDescr.369098758 = STRING: port-channel7
IF-MIB::ifDescr.369098759 = STRING: port-channel8
IF-MIB::ifDescr.369098761 = STRING: port-channel10
IF-MIB::ifDescr.369098762 = STRING: port-channel11
IF-MIB::ifDescr.369098763 = STRING: port-channel12
IF-MIB::ifDescr.369098764 = STRING: port-channel13
IF-MIB::ifDescr.369098765 = STRING: port-channel14
IF-MIB::ifDescr.369098766 = STRING: port-channel15
IF-MIB::ifDescr.369098767 = STRING: port-channel16
IF-MIB::ifDescr.369098768 = STRING: port-channel17
IF-MIB::ifDescr.369098769 = STRING: port-channel18
IF-MIB::ifDescr.369098771 = STRING: port-channel20
IF-MIB::ifDescr.369098772 = STRING: port-channel21
IF-MIB::ifDescr.369098773 = STRING: port-channel22
IF-MIB::ifDescr.369098774 = STRING: port-channel23
IF-MIB::ifDescr.369098775 = STRING: port-channel24
IF-MIB::ifDescr.369098776 = STRING: port-channel25
IF-MIB::ifDescr.369098777 = STRING: port-channel26
IF-MIB::ifDescr.369099651 = STRING: port-channel900
IF-MIB::ifDescr.436207616 = STRING: Ethernet1/1
IF-MIB::ifDescr.436211712 = STRING: Ethernet1/2
IF-MIB::ifDescr.436215808 = STRING: Ethernet1/3
IF-MIB::ifDescr.436219904 = STRING: Ethernet1/4
IF-MIB::ifDescr.436224000 = STRING: Ethernet1/5
IF-MIB::ifDescr.436228096 = STRING: Ethernet1/6
IF-MIB::ifDescr.436232192 = STRING: Ethernet1/7
IF-MIB::ifDescr.436236288 = STRING: Ethernet1/8
IF-MIB::ifDescr.436240384 = STRING: Ethernet1/9
IF-MIB::ifDescr.436244480 = STRING: Ethernet1/10
IF-MIB::ifDescr.436248576 = STRING: Ethernet1/11
IF-MIB::ifDescr.436252672 = STRING: Ethernet1/12
IF-MIB::ifDescr.436256768 = STRING: Ethernet1/13
IF-MIB::ifDescr.436260864 = STRING: Ethernet1/14
IF-MIB::ifDescr.436264960 = STRING: Ethernet1/15
IF-MIB::ifDescr.436269056 = STRING: Ethernet1/16
IF-MIB::ifDescr.436273152 = STRING: Ethernet1/17
IF-MIB::ifDescr.436277248 = STRING: Ethernet1/18
IF-MIB::ifDescr.436281344 = STRING: Ethernet1/19
IF-MIB::ifDescr.436285440 = STRING: Ethernet1/20
IF-MIB::ifDescr.436289536 = STRING: Ethernet1/21
IF-MIB::ifDescr.436293632 = STRING: Ethernet1/22
IF-MIB::ifDescr.436297728 = STRING: Ethernet1/23
IF-MIB::ifDescr.436301824 = STRING: Ethernet1/24
IF-MIB::ifDescr.436305920 = STRING: Ethernet1/25
IF-MIB::ifDescr.436310016 = STRING: Ethernet1/26
IF-MIB::ifDescr.436314112 = STRING: Ethernet1/27
IF-MIB::ifDescr.436318208 = STRING: Ethernet1/28
IF-MIB::ifDescr.436322304 = STRING: Ethernet1/29
IF-MIB::ifDescr.436326400 = STRING: Ethernet1/30
IF-MIB::ifDescr.436330496 = STRING: Ethernet1/31
IF-MIB::ifDescr.436334592 = STRING: Ethernet1/32
IF-MIB::ifDescr.436338688 = STRING: Ethernet1/33
IF-MIB::ifDescr.436342784 = STRING: Ethernet1/34
IF-MIB::ifDescr.436346880 = STRING: Ethernet1/35
IF-MIB::ifDescr.436350976 = STRING: Ethernet1/36
IF-MIB::ifDescr.436355072 = STRING: Ethernet1/37
IF-MIB::ifDescr.436359168 = STRING: Ethernet1/38
IF-MIB::ifDescr.436363264 = STRING: Ethernet1/39
IF-MIB::ifDescr.436367360 = STRING: Ethernet1/40
IF-MIB::ifDescr.436371456 = STRING: Ethernet1/41
IF-MIB::ifDescr.436375552 = STRING: Ethernet1/42
IF-MIB::ifDescr.436379648 = STRING: Ethernet1/43
IF-MIB::ifDescr.436383744 = STRING: Ethernet1/44
IF-MIB::ifDescr.436387840 = STRING: Ethernet1/45
IF-MIB::ifDescr.436391936 = STRING: Ethernet1/46
IF-MIB::ifDescr.436396032 = STRING: Ethernet1/47
IF-MIB::ifDescr.436400128 = STRING: Ethernet1/48
IF-MIB::ifDescr.437190656 = STRING: Ethernet2/1
IF-MIB::ifDescr.437194752 = STRING: Ethernet2/2
IF-MIB::ifDescr.437198848 = STRING: Ethernet2/3
IF-MIB::ifDescr.437202944 = STRING: Ethernet2/4
IF-MIB::ifDescr.437207040 = STRING: Ethernet2/5
IF-MIB::ifDescr.437211136 = STRING: Ethernet2/6
[root@nl0123vsm0038 gllewellyn]#

**Comment by netniV** [comment]
OK thanks for that. It that would explain thins as you're getting back what is expected as a string, where as in my case the string is coming back from a Windows platform as Hex-STRING so is not being converted.  @cigamit's changes

**Comment by gllewellyn** [comment]
Yes I have tested all my switches now and your change has fixed my problem.

**Comment by cigamit** [comment]
@netniV, Check lib/snmp.php line number 737-749, see if is_hex_string() is returning false, or if there is some bug in the logic.

**Comment by netniV** [comment]
```
format_snmp_string('Hex- 57 41 4E 20 4D 69 6E 69 70 6F 72 74 20 28 4E 65
74 77 6F 72 6B 20 4D 6F 6E 69 74 6F 72 29 2D 57
46 50 20 4E 61 74 69 76 65 20 4D 41 43 20 4C 61
79 65 72 20 4C 69 67 68 74 57 65 69 67 68 74 20
46 69 6C 74 65 72 2D 30 30 30 30 00', , 1); [.1.3.6.1.2.1.2.2.1.2.22] {
        Hex String: , Hex Match: 1, Mac Address:
```

This shows that the hex string is returning false, but the preg_match is returning true.

**Comment by netniV** [comment]
tbh, I'm not sure why the function is_hex_string isn't using a preg_match anyway itself.

**Comment by netniV** [comment]
I applied this fix to my code, not sure if that would affect anything for anyone else:

```diff
diff --git a/lib/snmp.php b/lib/snmp.php
index 0ee0ea2..dc8c5c4 100644
--- a/lib/snmp.php
+++ b/lib/snmp.php
@@ -730,6 +730,12 @@ function format_snmp_string($string, $snmp_oid_included, $value_output_format =
                }
        }

+       $hasHexPrefix = preg_match('/hex- ?/i', $string);
+       if ($hasHexPrefix) {
+               /* strip off the 'Hex-STRING:' */
+               $string = preg_replace('/hex- ?/i', '', $string);
+       }
+
        /* Trim the string of trailing and leading spaces */
        $string = trim($string);

@@ -748,12 +754,9 @@ function format_snmp_string($string, $snmp_oid_included, $value_output_format =
                } else {
                        $string = $output;
                }
-       } elseif (preg_match('/hex-/i', $string)) {
+       } elseif ($hasHexPrefix) {
                $output = '';

-               /* strip off the 'Hex-STRING:' */
-               $string = preg_replace('/hex- ?/i', '', $string);
-
                /* normalize some forms */
                $string = str_replace(array(' ', '-', '.'), ':', $string);
                $parts  = explode(':', $string);
```

However, this also affected the output of ifHwAddr.  Presumably because is_hex_string now returns true, which I thought it should complain at because there are non-ascii characters.

**Comment by netniV** [comment]
So, this patch seems to work for both circumstances.  However, I can foresee this causing an issue when all characters in a ifHwAddr are all valid ascii characters.

```diff
diff --git a/lib/functions.php b/lib/functions.php
index c711dc8..e0e3d53 100644
--- a/lib/functions.php
+++ b/lib/functions.php
@@ -1095,6 +1095,11 @@ function is_hex_string($result) {
                if (ctype_xdigit($part) == false) {
                        return false;
                }
+
+               $dec = hexdec($part);
+               if ($dec < 32 || $dec > 127) {
+                       return false;
+               }
        }

        return true;
diff --git a/lib/snmp.php b/lib/snmp.php
index 0ee0ea2..197e0ee 100644
--- a/lib/snmp.php
+++ b/lib/snmp.php
@@ -730,6 +730,16 @@ function format_snmp_string($string, $snmp_oid_included, $value_output_format =
                }
        }

+       $hasHexPrefix = preg_match('/hex- ?/i', $string);
+       if ($hasHexPrefix) {
+               /* strip off the 'Hex-STRING:' */
+               $string = preg_replace('/hex- ?/i', '', $string);
+               $hasHexZeros = preg_match('/00 ?$/', $string);
+               if ($hasHexZeros) {
+                       $string = preg_replace('/00 ?$/', '',  $string);
+               }
+       }
+
        /* Trim the string of trailing and leading spaces */
        $string = trim($string);

@@ -748,14 +758,14 @@ function format_snmp_string($string, $snmp_oid_included, $value_output_format =
                } else {
                        $string = $output;
                }
-       } elseif (preg_match('/hex-/i', $string)) {
+       } elseif ($hasHexPrefix) {
                $output = '';

-               /* strip off the 'Hex-STRING:' */
-               $string = preg_replace('/hex- ?/i', '', $string);
-
                /* normalize some forms */
                $string = str_replace(array(' ', '-', '.'), ':', $string);
+               if ($hasHexZeros) {
+                       $string .= ':00';
+               }
                $parts  = explode(':', $string);

                if (is_mac_address($string)) {
```

**Comment by cigamit** [comment]
Do it in a pull request.

**Comment by netniV** [comment]
I'm not convinced it's right, but I'll submit it.

**Comment by gllewellyn** [comment]
Just a quick question could the change I appided to "data_query.php" have stopped "Thresholds" getting current values ?

I have just noticed values have stopped updating. They were working a few days back and just notice they have stopped updating threshold current value.

![threshold](https://user-images.githubusercontent.com/37145853/37664450-4b96dea8-2c53-11e8-9314-d434f3ae5933.png)

**Comment by cigamit** [comment]
First, don't update from every patch here, or expect that you may have to roll things back.  In the case of the changed suggested by @netniV and his last patch recommendation, it was not accepted in the end.  If your graphs are working and the thold is not, please open a thold bug.  I'm going to close this now.

**Comment by netniV** [comment]
I can't see why the changes would stop THold.  If you are getting the values, you should be getting your THolds.
