### ISSUE TITLE
Different outputs from different Cacti's

### ISSUE THREAD

**Issue by MOFOGH** [Cacti/cacti#1477]
Hi folks,

I am working within IT network and security.
One of my responsibilities is to globally monitor all network devices from the company.
Around 1800 devices.

Before i started at my company, there was already a Cacti. But pretty outdated v. **0.8.8b**

I created two new Cacti servers, one for production and one for test v. **1.1.36** 

Everything works as it should. But when i compare the graphs from 0.8.8b and 1.1.36 - they are VERY different.

Here is an example, from the same device on the same interface:

**v. 0.8.8b:**

Log:
03/19/2018 04:27:06 AM - CMDPHP: Poller[0] Host[145] RECACHE DQ[1] OID: .1.3.6.1.2.1.2.2.1.2.3, output: GigabitEthernet1/1
03/19/2018 04:27:06 AM - CMDPHP: Poller[0] Host[382] DS[3674] SNMP: v2: 10.8.3.1, dsname: traffic_in, oid: .1.3.6.1.2.1.2.2.1.10.3, output: 721789520
03/19/2018 04:27:06 AM - CMDPHP: Poller[0] Host[2081] RECACHE DQ[1] OID: .1.3.6.1.2.1.2.2.1.2.10003, output: FastEthernet0/3
03/19/2018 04:27:06 AM - CMDPHP: Poller[0] Host[2081] RECACHE DQ[1] OID: .1.3.6.1.2.1.2.2.1.2.10004, output: FastEthernet0/4
03/19/2018 04:27:06 AM - CMDPHP: Poller[0] Host[217] RECACHE DQ[1] OID: .1.3.6.1.2.1.2.2.1.2.10, output: GigabitEthernet1/8
03/19/2018 04:27:06 AM - CMDPHP: Poller[0] Host[2081] RECACHE DQ[1] OID: .1.3.6.1.2.1.2.2.1.2.10005, output: FastEthernet0/5
03/19/2018 04:27:06 AM - CMDPHP: Poller[0] Host[2217] RECACHE DQ[1] OID: .1.3.6.1.2.1.2.2.1.2.25, output: Loopback161
03/19/2018 04:27:06 AM - CMDPHP: Poller[0] Host[2081] RECACHE DQ[1] OID: .1.3.6.1.2.1.2.2.1.2.10006, output: FastEthernet0/6
03/19/2018 04:27:06 AM - CMDPHP: Poller[0] Host[2302] RECACHE DQ[1] OID: .1.3.6.1.2.1.2.2.1.2.10005, output: FastEthernet0/5
03/19/2018 04:27:06 AM - CMDPHP: Poller[0] Host[2081] RECACHE DQ[1] OID: .1.3.6.1.2.1.2.2.1.2.10007, output: FastEthernet0/7
03/19/2018 04:27:06 AM - CMDPHP: Poller[0] Host[382] DS[3674] SNMP: v2: 10.8.3.1, dsname: traffic_out, oid: .1.3.6.1.2.1.2.2.1.16.3, output: 1168155631
03/19/2018 04:27:06 AM - CMDPHP: Poller[0] Host[2268] RECACHE DQ[1] OID: .1.3.6.1.2.1.2.2.1.2.3, output: FastEthernet2
03/19/2018 04:27:06 AM - CMDPHP: Poller[0] Host[2081] RECACHE DQ[1] OID: .1.3.6.1.2.1.2.2.1.2.10008, output: FastEthernet0/8
03/19/2018 04:27:06 AM - CMDPHP: Poller[0] Host[145] RECACHE DQ[1] OID: .1.3.6.1.2.1.2.2.1.2.34, output: Vlan50
03/19/2018 04:27:06 AM - CMDPHP: Poller[0] Host[2081] RECACHE DQ[1] OID: .1.3.6.1.2.1.2.2.1.2.10009, output: FastEthernet0/9
03/19/2018 04:27:06 AM - CMDPHP: Poller[0] Host[217] RECACHE DQ[1] OID: .1.3.6.1.2.1.2.2.1.2.11, output: GigabitEthernet1/9
03/19/2018 04:27:06 AM - CMDPHP: Poller[0] Host[2460] DS[6109] SNMP: v2: 10.14.53.1, dsname: traffic_in, oid: .1.3.6.1.2.1.2.2.1.10.1, output: 3692483448
03/19/2018 04:27:06 AM - CMDPHP: Poller[0] Host[2081] RECACHE DQ[1] OID: .1.3.6.1.2.1.2.2.1.2.10010, output: FastEthernet0/10
03/19/2018 04:27:06 AM - CMDPHP: Poller[0] Host[2180] RECACHE DQ[1] OID: .1.3.6.1.2.1.2.2.1.2.16, output: FastEthernet0/16
03/19/2018 04:27:06 AM - CMDPHP: Poller[0] Host[2217] RECACHE DQ[1] OID: .1.3.6.1.2.1.2.2.1.2.26, output: ATM0.101-atm subif
03/19/2018 04:27:06 AM - CMDPHP: Poller[0] Host[2081] RECACHE DQ[1] OID: .1.3.6.1.2.1.2.2.1.2.10011, output: FastEthernet0/11
03/19/2018 04:27:06 AM - CMDPHP: Poller[0] Host[2081] RECACHE DQ[1] OID: .1.3.6.1.2.1.2.2.1.2.10012, output: FastEthernet0/12
03/19/2018 04:27:06 AM - CMDPHP: Poller[0] Host[1522] RECACHE DQ[1] OID: .1.3.6.1.2.1.2.2.1.2.5, output: FastEthernet4
03/19/2018 04:27:06 AM - CMDPHP: Poller[0] Host[382] DS[7948] SNMP: v2: 10.8.3.1, dsname: traffic_in, oid: .1.3.6.1.2.1.2.2.1.10.1, output: 2775519662^C

![image](https://user-images.githubusercontent.com/37545640/37601792-3676cdf8-2b8b-11e8-9dc3-d00da1a64b20.png)

**v. 1.1.36**

Log:
19/03/2018 04:36:00 - DBCALL DEVEL: SQL Cell: "SELECT 1 FROM `snmpagent_cache` WHERE `oid` = ?"
19/03/2018 04:36:00 - DBCALL DEVEL: SQL Exec: "INSERT INTO `snmpagent_cache`      (name, value, oid)      VALUES ('cactiStatsDeviceMinTime', '9.99999', '.1.3.6.1.4.1.23925.2.9.1.3.371'), ('cactiStatsDeviceMaxTime', '392.91850', '.1.3.6.1.4.1.23925.2.9.1.4.371'), ('cactiStatsDeviceCurTime', '11.86050', '.1.3.6.1.4.1.23925.2.9.1.5.371'), ('cactiStatsDeviceAvgTime', '12.85814', '.1.3.6.1.4.1.23925.2.9.1.6.371'), ('cactiStatsDeviceTotalPolls', '46338', '.1.3.6.1.4.1.23925.2.9.1.7.371'), ('cactiStatsDeviceFailedPolls', '162', '.1.3.6.1.4.1.23925.2.9.1.8.371'), ('cactiStatsDeviceAvailability', '99.65039', '.1.3.6.1.4.1.23925.2.9.1.9.371')      ON DUPLICATE KEY UPDATE value=VALUES(value)"
19/03/2018 04:36:00 - DBCALL DEVEL: SQL Cell: "SELECT 1 FROM `snmpagent_cache` WHERE `oid` = ?"
19/03/2018 04:36:00 - DBCALL DEVEL: SQL Exec: "INSERT INTO `snmpagent_cache`      (name, value, oid)      VALUES ('cactiApplDeviceStatus', '3', '.1.3.6.1.4.1.23925.1.14.1.4.372'), ('cactiApplDeviceEventCount', '0', '.1.3.6.1.4.1.23925.1.14.1.5.372'), ('cactiApplDeviceFailDate', '2018-03-17 22:06:03', '.1.3.6.1.4.1.23925.1.14.1.6.372'), ('cactiApplDeviceRecoveryDate', '2018-03-17 23:21:40', '.1.3.6.1.4.1.23925.1.14.1.7.372'), ('cactiApplDeviceLastError', 'SNMP not performed due to setting or ping result., ICMP ping Timed out', '.1.3.6.1.4.1.23925.1.14.1.8.372')      ON DUPLICATE KEY UPDATE value=VALUES(value)"
19/03/2018 04:36:00 - DBCALL DEVEL: SQL Cell: "SELECT 1 FROM `snmpagent_cache` WHERE `oid` = ?"
19/03/2018 04:36:00 - DBCALL DEVEL: SQL Exec: "INSERT INTO `snmpagent_cache`      (name, value, oid)      VALUES ('cactiStatsDeviceMinTime', '9.99999', '.1.3.6.1.4.1.23925.2.9.1.3.372'), ('cactiStatsDeviceMaxTime', '854.86300', '.1.3.6.1.4.1.23925.2.9.1.4.372'), ('cactiStatsDeviceCurTime', '86.10600', '.1.3.6.1.4.1.23925.2.9.1.5.372'), ('cactiStatsDeviceAvgTime', '38.25545', '.1.3.6.1.4.1.23925.2.9.1.6.372'), ('cactiStatsDeviceTotalPolls', '40100', '.1.3.6.1.4.1.23925.2.9.1.7.372'), ('cactiStatsDeviceFailedPolls', '145', '.1.3.6.1.4.1.23925.2.9.1.8.372'), ('cactiStatsDeviceAvailability', '99.63840', '.1.3.6.1.4.1.23925.2.9.1.9.372')      ON DUPLICATE KEY UPDATE value=VALUES(value)"
19/03/2018 04:36:00 - DBCALL DEVEL: SQL Cell: "SELECT 1 FROM `snmpagent_cache` WHERE `oid` = ?"
19/03/2018 04:36:00 - DBCALL DEVEL: SQL Exec: "INSERT INTO `snmpagent_cache`      (name, value, oid)      VALUES ('cactiApplDeviceStatus', '1', '.1.3.6.1.4.1.23925.1.14.1.4.373'), ('cactiApplDeviceEventCount', '20', '.1.3.6.1.4.1.23925.1.14.1.5.373'), ('cactiApplDeviceFailDate', '2018-03-19 03:02:29', '.1.3.6.1.4.1.23925.1.14.1.6.373'), ('cactiApplDeviceRecoveryDate', '2018-03-18 12:17:29', '.1.3.6.1.4.1.23925.1.14.1.7.373'), ('cactiApplDeviceLastError', 'SNMP not performed due to setting or ping result., ICMP ping Timed out', '.1.3.6.1.4.1.23925.1.14.1.8.373')      ON DUPLICATE KEY UPDATE value=VALUES(value)"
19/03/2018 04:36:00 - DBCALL DEVEL: SQL Cell: "SELECT 1 FROM `snmpagent_cache` WHERE `oid` = ?"
19/03/2018 04:36:00 - DBCALL DEVEL: SQL Exec: "INSERT INTO `snmpagent_cache`      (name, value, oid)      VALUES ('cactiStatsDeviceMinTime', '9.99999', '.1.3.6.1.4.1.23925.2.9.1.3.373'), ('cactiStatsDeviceMaxTime', '833.85150', '.1.3.6.1.4.1.23925.2.9.1.4.373'), ('cactiStatsDeviceCurTime', '37.40950', '.1.3.6.1.4.1.23925.2.9.1.5.373'), ('cactiStatsDeviceAvgTime', '40.77092', '.1.3.6.1.4.1.23925.2.9.1.6.373'), ('cactiStatsDeviceTotalPolls', '45608', '.1.3.6.1.4.1.23925.2.9.1.7.373'), ('cactiStatsDeviceFailedPolls', '90', '.1.3.6.1.4.1.23925.2.9.1.8.373'), ('cactiStatsDeviceAvailability', '99.80267', '.1.3.6.1.4.1.23925.2.9.1.9.373')      ON DUPLICATE KEY UPDATE value=VALUES(value)"
19/03/2018 04:36:00 - DBCALL DEVEL: SQL Cell: "SELECT 1 FROM `snmpagent_cache` WHERE `oid` = ?"^C

![image](https://user-images.githubusercontent.com/37545640/37601834-551f66c0-2b8b-11e8-8c95-91eb4679103d.png)

Poller, crontab etc are all set to the same settings, between Cacti 0.8.8b and 1.3.36

Someone .. Please help me ..

**Comment by netniV** [comment]
Did you create the 1.1.36 graphs with the 64-bit counters?

**Comment by MOFOGH** [comment]
This is how 1.1.36 is setup

![image](https://user-images.githubusercontent.com/37545640/37607936-8a19e4be-2b99-11e8-97f3-a30e5b6de829.png)

**Comment by cigamit** [comment]
Re-import the package on the old cacti and make sure you use the --remove-orphans option.  Backup your database before you do this though.  It will update all your legacy graph templates and graphs to the new format.  You may then want to goto the Cacti Graph Templates page, and select the Graph Templates that are different, and select the 'Sync Graphs' option.  Then you should be all set.

**Comment by cigamit** [comment]
Oh, and as @netniV points out, you should use 64bit counters unless your devices don't support them.  Those graphs will be ugly.  In Cacti 1.x, you can simply change the template for the Graphs and they will be switched automatically.  This can be done en-mass on the Graph Management page.
