### ISSUE TITLE
HMIB and default templates

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1478]
There is some cross over between the default package templates and the HMIB plugin.  This can lead to a situation were different versions of scripts are applied, and due to template overwritting, you can end up thinking you can disable HMIB but this actually stops the original templates from working as they have now been overwritten.

For example, I spent the best part of an hour trying to work out why I couldn't get an CPU stats from a new device.  It turns out that HMIB had redirected the XML and functions to it's own plugins/hmib/templates/scripts/ss_host_cpu.php.  For some reason, these did not work with my Windows servers where the template package (the one from install/templates) does.

**Comment by netniV** [comment]
I feel we should separate out the HASH used by these templates.  Not sure how that would work, but I think we should be naming one Generic and the other HMIB.  That would apply to Host CPU, Interface and Disk.

**Comment by cigamit** [comment]
We should actually remove it from the hmib plugin.  There are hooks in the current scripts that hmib traps.  So, they can be removed from the package.

**Comment by cigamit** [comment]
Closing this here.  Should be in the plugin_hmib section.
