### ISSUE TITLE
SQL Backtrace - pollers.php: 158 pollers

### ISSUE THREAD

**Issue by BSOD2600** [Cacti/cacti#148]
latest e3f5ee822c492cda90e5980caa61e545ba4e94e0

`2017-01-04 21:38:09 - CMDPHP SQL Backtrace: (C:\Apache24\htdocs\cacti\pollers.php: 158 pollers)(C:\Apache24\htdocs\cacti\pollers.php: 576 db_fetch_assoc)(C:\Apache24\htdocs\cacti\lib\database.php: 310 db_fetch_assoc_prepared)(C:\Apache24\htdocs\cacti\lib\database.php: 348 cacti_debug_backtrace)`

**Comment by cigamit** [comment]
I can not see anywhere in the code where this might happen.  You may have to setup DEVDBG or get a repeatable case to share.

**Comment by simnv** [comment]
Got that issue with git cloned weathermap plugin folder.
Failed on requests `INSERT INTO poller_resource_cache (path, id, resource_type, md5sum, update_time, contents)`...

After deleting .git folder in weathermap everything went fine.

**Comment by cigamit** [comment]
Can you do a scan of your weathermap folder and let me know the size of the largest file, and it's file type.  

This resource cache table is a part of how Cacti will support remote data collection.  It uses the resource cache to replicate Cacti's website to the remote data collectors and real large files can cause the resource cache to overflow and subsequently this error.

You should also check your 'max_allowed_packet' variable in my.cnf.  We make a recommendation under Utilities -> Technical Support.  

Also, attach a few images of the Weather-Map's look under Cacti 1.0.  Thanks!

**Comment by simnv** [comment]
1. Largest file is in git folder, yes:
```
$ find . -printf '%s %p\n' | sort -nr | head -10
26523013 ./.git/objects/pack/pack-78c975d62dcc0827cf0ee818bbd7f04b6732e06c.pack
5165056 ./test-suite/tools/compare.exe
537941 ./images/testpattern-hd-1080.png
384491 ./old-tests/last-release-suite-2.png
303724 ./.git/objects/pack/pack-78c975d62dcc0827cf0ee818bbd7f04b6732e06c.idx
283974 ./docs/howto.png
244963 ./vendor/jquery/dist/jquery.js
197892 ./test-suite/data/uk1024.png
197892 ./images/uk1024.png
160540 ./test-suite/data/caveman.gdf
```
2. max_allowed_packet is 32M, which is quite big and bigger than this 26M file in .git folder. And bigger than recommended 16M.

3. I'm not there yet. Trying to make it run on my test system. Cacti doesn't work, there are some typos and other errors. I'm preparing PRs now.

**Comment by cigamit** [comment]
Yea, but after encoding, it'll grow.  I don't see any reason to copy these files over.  I'll put the *.pack and *.exe files in the exclude list.  What is the *.pack file for?  Do you know?

**Comment by cigamit** [comment]
Forget my comments about '*.pack'.  I get it now.  Closing this, but keeping that change in place, for now anyway.  If people start to get 'remote_collect' integrated into their plugins, we will look at possibly bringing the *.exe back for Windows users.

The original issue for which this ticket was opened has now been resolved.
