### ISSUE TITLE
Create New Graphs - Paw Styling Issue

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1483]
So, I noticed a strange styling issue on the Create New Graphs screen under the Paw theme.  This doesn't seem to affect other themes and I've narrowed it down to the use of line-height: 22px; on the cactiTableButton and cactiTableTitle classes:

![image](https://user-images.githubusercontent.com/9052188/37650650-77e6a25c-2c2d-11e8-88a7-0ba162cc4468.png)

If you change the .cactiTableButton to have a line-height of 24px, this inverts the problem, where the green header becomes like the red ones (except the blank line is all across the left and the red headers become like the green ones.

![image](https://user-images.githubusercontent.com/9052188/37650779-d38cb8e4-2c2d-11e8-8ed3-5c56bb9d8c59.png)

**Comment by netniV** [comment]
Oh and for reference, at 23px they both have the problem!

**Comment by netniV** [comment]
I suspect @cigamit will say this is one for @browniebraun

**Comment by cigamit** [comment]
Resolved.

**Comment by netniV** [comment]
Was that all it was? 👍
