### ISSUE TITLE
Double Scroll bars in realtime view

### ISSUE THREAD

**Issue by chathurag** [Cacti/cacti#1484]
I noticed there are double scroll bars in real time view of cacti 1.1.36

![cacti](https://user-images.githubusercontent.com/35136010/37657404-dc175986-2c70-11e8-8977-1bb13a5d3cb9.png)

**Comment by cigamit** [comment]
Please test with develop.  There have been some changes there.

**Comment by cigamit** [comment]
As mentioned, this is fixed in 1.1.37.  We introduce a new Profile setting to either do the realtime in a popup or inline.
