### ISSUE TITLE
Unable to create a gaph Cacti 1.1.36

### ISSUE THREAD

**Issue by tangosan** [Cacti/cacti#1485]
Hello,

I'm trying to install Cacti 1.1.36 on windows server 2016, with server IIS 10.0, PHP7 and MySql 8.0.

Everything seems to be fine but i can't create graphe and I find this log on my cacti log :

 CMDPHP PHP ERROR NOTICE Backtrace:  (C:\inetpub\wwwroot\cacti\graphs_new.php: 37  form_save)(C:\inetpub\wwwroot\cacti\graphs_new.php: 123  host_new_graphs)(C:\inetpub\wwwroot\cacti\graphs_new.php: 362  CactiErrorHandler)(C:\inetpub\wwwroot\cacti\lib\functions.php: 4591  cacti_debug_backtrace)
--
2018/03/20 18:20:42 - ERROR PHP NOTICE: Undefined index:  graph_template_name in file: C:\inetpub\wwwroot\cacti\graphs_new.php  on  line: 362

I search how to fix it on the Internet but don't find anything about graphs_new.php error. I replace cacti install with another, the problem is not fix, same error.

Regards,

**Comment by netniV** [comment]
That would suggest that for the given template ID it failed to find the template.  I presume this is only happening on one type of graph template, or is it all of them?

**Comment by tangosan** [comment]
Thanks for answer, is it for all of them

**Comment by cigamit** [comment]
Very odd.  I can not imaging that variable not being set unless maybe you have a damaged table.  You should run the cli script to repair your tables, and also the convert_innodb.php cli script to move to a more stable db format.  Don't do this unless you followed the recommendations that you were afforded during install time.  I've also made a few tweaks to the graphs_new.php interface, but none of that should effect your outcome.

**Comment by tangosan** [comment]
Plop,

When i import a template from my ubuntu cacti 0.8.8b to my windows cacti 1.1.36 the import works, i have no graph, RDD tool say Unknown RDD error, and no RRA appears in cacti/rra folder.
 But the plugin REALTIME works, i have a graph on that :-) I don't understand, the template on cacti website for package 1.X are not compatible with windows cacti 1.1.36 ? 

Thanks for your advice

Regards

**Comment by netniV** [comment]
There was a problem a while ago with standard template imports.  If it is the basic templates that come with cacti, these are imported using the CLI import_package.php command.  Not just the standard import/export features.

**Comment by cigamit** [comment]
Please upload your problem template.

**Comment by tangosan** [comment]
Hello,

I try to import template with import_package.php command and it works perfectly :-) 

Problem solved, thank you for your time !

Regards,

**Comment by netniV** [comment]
Cool.  Go ahead and hit the close button unless @cigamit beats you to
