### ISSUE TITLE
Cacti version 1.1.37 (develop branch) - PHP Ldap error

### ISSUE THREAD

**Issue by anarkia1976** [Cacti/cacti#1487]
I have update cacti to latest and now i have this error with ldap auth:

2018/03/21 15:34:20 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4625 cacti_debug_backtrace)
2018/03/21 15:34:20 - ERROR PHP ERROR: Undefined class constant 'ConnectionUnavaialble' in file: /usr/share/cacti/lib/ldap.php on line: 220
2018/03/21 15:34:20 - AUTH LDAP: Setting protocol version to 3
2018/03/21 15:33:48 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4625 cacti_debug_backtrace)
2018/03/21 15:33:48 - ERROR PHP ERROR: Undefined class constant 'ConnectionUnavaialble' in file: /usr/share/cacti/lib/ldap.php on line: 220

No problem with local autentication.

thanks a lot

**Comment by netniV** [comment]
Hmm, I'll check this again as i'm running multi-LDAP on my cacti server and my code hasn't pop'd up with that message, but it suggests that it was unable to find your LDAP server.  I had a change for 1.2 which updated the LDAP class with constants to ensure consistent error results, but it would appear there is a constant that is missing.

**Comment by netniV** [comment]
I've submitted a fix for the constant issue.

**Comment by cigamit** [comment]
Resolved.

**Comment by anarkia1976** [comment]
thanks a lot.
