### ISSUE TITLE
Fatal Error - Cacti Database Not Initialized - missing mysql grant command

### ISSUE THREAD

**Issue by BSOD2600** [Cacti/cacti#149]
On the **Fatal Error - Cacti Database Not Initialized** page, it's missing a mysql grant command for mysql.time_zone_name

`GRANT SELECT ON mysql.time_zone_name TO cactiuser@localhost IDENTIFIED BY 'cactipw';`

![image](https://cloud.githubusercontent.com/assets/5741811/21670461/38f0616e-d2c9-11e6-91c8-8b7de2690036.png)

**Comment by BSOD2600** [comment]
Also this line
`mysql -uroot -p < /pathcacti/cacti.sql`
is missing the database selection
`mysql -uroot -p cacti < /pathcacti/cacti.sql`

otherwise a user would get:
> ERROR 1046 (3D000) at line 12: No database selected

**Comment by cigamit** [comment]
Resolved thanks!
