### ISSUE TITLE
New clis: for adding data template to host and for repairing association between graph and datasource

### ISSUE THREAD

**Issue by dimaslv** [Cacti/cacti#1491]
We are using Cacti 0.8.8e for a few installations with largest polling 2.5k devices and 500k datasources every minute.
One of the problem we have is an inability to add new line to existing graph template, so that it would be propagated to all existing host graphs. Upon adding new line no new datasource was added to hosts and association between graph and datasource show None as datasource. Even more, after exporting and importing such template to another cacti instance (where previous version of same template exist and is applied to hosts) additionally one of the old line-ds association breaks.
This of course could be solved with removing all corresponding graphs from host and applying new graph template, but in such a case you will loos all the history of those graphs and this is not something acceptable in production environment.
I have not tried v1.0 or v1.1 and I don't think we will plan upgrade in the nearest future as the number of new features doesn't make me feel safe. I'd prefer to have two line of releases - "lts" (with bugfixes only) and "latest" as only lts could be appropriate for production monitoring system.

So, anyway, as a solution to our problem I have made two cli scripts:
- [add_datasource.php.txt](https://github.com/Cacti/cacti/files/1841713/add_datasource.php.txt) - for adding data template to host
- [repair_graphs.php.txt](https://github.com/Cacti/cacti/files/1841712/repair_graphs.php.txt) - for repairing association between host graph and host datasources

Complete algorithm of adding line to graph should be like:
1. add new data template
2. add new line to graph template
3. prepare list of hosts which use this graph template
4. php add_datasource.php --data-template-id=X --host-id=Y
5. php repair_graphs.php --data-template-id=X --host-id=Y --graph-template-id=Z --execute

And even more, if you are importing template over existing, then before step 4 you should enter new line editing in graph template ad click save without making any changes. Without it new template does not applies to hosts.
Not very elegant solution, but it works.

I don't know if this should be considered as a bug report, feature request or pull request, so feel free to interpret it as you wish or close at once.

Hope it will help someone.

**Comment by netniV** [comment]
It would be a feature more than a bug.  The cli's are welcome.  Pull Requests are were the code can be examined and pulled in automatically if approved.  I wrote a wiki article on my forked cacti repo to remind me how to do it when I first started (you can use that as a basis for how to create your own pull request: https://github.com/netniV/cacti/wiki/Creating-Pull-Requests)

**Comment by dimaslv** [comment]
Just wasn't sure that you are interested in such CLIs and problem still exist in newer versions. I will make PR a bit later, thanks for documentation.

**Comment by netniV** [comment]
Always interested in problems... even more so if they come with fixes 👍

**Comment by cigamit** [comment]
@netniV, you got this one?  Rony is going to rock my world this weekend, and I'm not ready for it.

**Comment by cigamit** [comment]
Okay.  Sitting tight then.

**Comment by netniV** [comment]
This was merged several months ago and so can be closed.
