### ISSUE TITLE
Can't create tree branches with '#' sign

### ISSUE THREAD

**Issue by bad-crc** [Cacti/cacti#1493]
Assume we have switches
- Switch number 1
- Switch number 2
- Switch number 3

Let's try to create branches named
```
Switch #1
Switch #2
Switch #3
```
The result will be:
```
Switch <space>1
Switch <space>2
Switch <space>3
```
There are no '#' sign at all
Bug?

**Comment by netniV** [comment]
No, I don’t think this is a bug but rather that the name of a node is expected to be alphanumeric.  You may find that hyphens and underscores are also being used.

**Comment by cigamit** [comment]
I'll have to check the code.  I think that jstree can handle it, but we may be tossing those characters out.

**Comment by cigamit** [comment]
Resolved.  Should be out tomorrow.
