### ISSUE TITLE
Unable to Deep Link/Bookmark Trees

### ISSUE THREAD

**Issue by chathurag** [Cacti/cacti#1494]
When we right click on graph tree and select open in new tab, that tree won't get opened in new tab.

**Comment by cigamit** [comment]
Known issue.  I'ts a duplicate.  I'll find the id and then close this one.

**Comment by DavidLiedke** [comment]
@cigamit #1340

**Comment by cigamit** [comment]
No, that one is fixed.  Looking for it now but could not find it.  I'll just update the title on this one.

**Comment by chathurag** [comment]
Is there any fix for this in 1.1.37

**Comment by netniV** [comment]
You would normally receive a notification in the thread if any fix has been applied to the system, so I would imagine not.

**Comment by chathurag** [comment]
My concern is I can't open specific tree in new tab by right click on that

**Comment by cigamit** [comment]
There are only so many hours in a day guys and this is not my day job.  It's on the list though.

**Comment by netniV** [comment]
I was thinking over this and it should be possible given that we maintain the links when editing the tree.    It just might use more memory to do so since jstree would maintain the node id's too.

**Comment by cigamit** [comment]
This issue is finally resolved.
