### ISSUE TITLE
Upgrade from 1.1.34 to anything higher, next button grayed out

### ISSUE THREAD

**Issue by tjswe** [Cacti/cacti#1497]
Hi!

Having trouble upgrading our 1.1.34 to anything beyond where the "next" button is grayed out in the installation script. See attached image.

First it was an issue upgrading 1.1.33 to 1.1.36 a few weeks ago. Tested 1.1.33->1.1.37 today, same problem. 1.1.33->1.1.35, same issue. 

1.1.33->1.1.34 worked. 1.1.34->1.1.37 not working.

Tested with Chrome 64.0.3282.186, IE 11 and Firefox 38.2.0

The problem with grayed "next" button has been an issue with Chrome since we started with Cacti 1.0.5, but doing the upgrade in IE 11 always worked.

I have done around 10-12 upgrades on the way from 1.0.5 but no changes to other components like database, Apache etc that i know of. The previous upgrade was from 1.1.25->1.1.33

The two red recommended(?) values in the image (Ldap and DB-version) has been red since 1.0.5 and not an issue.

Running on centos-release-7-3.1611.el7.centos.x86_64, PHP 5.4.16,

Any idea where to start? (I am in a corporate environment so i can not completely rule out any firewalls or proxies/web filters, but it seems unlikely.)

![cactifail](https://user-images.githubusercontent.com/26895402/37904290-983f2538-30fb-11e8-8c39-2a6356a7729d.PNG)

**Comment by netniV** [comment]
this would be down to the MariaDB version.  It's too low for what is supported. You need to upgrade to 5.6 or higher as per the red line.

**Comment by ronytomen** [comment]
I was looking a this earlier and was thinking it really isn't clear.  There should be a message stating that installation is not supported in the current environment due to the items indicated in red or something like that.

**Comment by tjswe** [comment]
These values (ldap and database version) has been the same (red) since we did the initial install at 1.0.5 and red at every update (about 10 or so) since. Between 1.1.34 and 1.1.35 they must have become mandatory and not just _recommended values_ as the table states (or some gui-bug that was fixed in 1.1.35, which actually greyed the "next" button in all browsers)

**Comment by netniV** [comment]
Yeah, looking again, I think they are recommendations.  If you are below this recommendations, the SQL *should* still work but those are the stable realises that have been tested against.  There may even be code that checks for a minimum version of SQL but I'd have to double check on that.

What I did miss, as I was scrolling upwards was the LDAP module.  This is a REQUIRED module even if you are not using LDAP for authentication.  I don't believe that module was moved from optional, but I'd have to double check the code history.

```
Required PHP Module Support
Cacti requires several PHP Modules to be installed to work properly. If any of these are not installed, you will be unable to continue the installation until corrected. In addition, for optimal system performance Cacti should be run with certain MySQL system variables set. Please follow the MySQL recommendations at your discretion. Always seek the MySQL documentation if you have any questions.

The following PHP extensions are mandatory, and MUST be installed before continuing your Cacti install.
```

As @ronytomen pointed out, amongst the sea of green, it should be fairly obvious to see the parts that fail.  Maybe we should highlight the recommendations in blue or some other colour to highlight that they don't stop the installation, but you may have issues of your own doing by continuing.  Another thing I've wondered in the past is whether we should record for our support purposes what the installation was performed with to give an idea when problems occur what if any differences there were between installation, recommendation and currently running.

**Comment by tjswe** [comment]
Ok!  LDAP required, that i missed since 10-12 upgrades has been running smoothly from 1.0.5 until now without LDAP. But then being able to continue might have been the bug then :)

I will do another try tomorrow (evening here in Europe) with LDAP and bite into a database upgrade also.

Many thanks for quick responses and for this wonderful software in general!

**Comment by tjswe** [comment]
Added the LDAP-module and after that no problem upgrading from 1.1.34 to 1.1.37. 

This issue was then mainly due to my ability to read simple instructions (and a liitle bit some way being able to complete installation i IE11 even though requirements where not met)

Thanks again!

**Comment by netniV** [comment]
At least it was easily resolved 👍   Are you still seeing the ability to complete via IE 11 even with unmet requirements though? That's still a bug if so.

**Comment by tjswe** [comment]
That was the start of this "issue" :)  IE11 is now correctly graying NEXT out after 1.1.34.

So no longer a bug.

**Comment by netniV** [comment]
Ah, I see!  OK, Case closed, my dear Watson.
