### ISSUE TITLE
weekly,monthly,yearly graph problem Daily graph is ok

### ISSUE THREAD

**Issue by whyitellu** [Cacti/cacti#1500]
Problem: whicle checking daily graph we get proper data, but while viewing the weekly/monthly/yearly graph we can see 2 lines are plotting.

Snap Attached.

![cccapture](https://user-images.githubusercontent.com/11717960/37958996-985aa8a6-31cf-11e8-8fdf-34de850a798c.PNG)

Cacti Version | 1.1.36

NET-SNMP Version | NET-SNMP version: 5.7.3
-- | --
RRDtool Version | RRDtool 1.6.x
Devices | 5
Graphs | 130
Data Sources | Script/Command: 5SNMP Get: 14SNMP Query: 115Total: 134

Poller Interval | 300
-- | --
Type | cmd.php
Items | Action[0]: 244Action[1]: 5Total: 249
Concurrent Processes | 1
Max Threads | 1
PHP Servers | 1
Script Timeout | 25
Max OID | 10

PHP Version | 7.0.27-0+deb9u1
-- | --

-- | --

**Comment by netniV** [comment]
What version of cacti are you running?

**Comment by whyitellu** [comment]
Cacti Version | 1.1.36

**Comment by anarkia1976** [comment]
The same in cacti version 1.1.37 latest develop branch.
rrdtool 1.7.0.
php 5.4.
poller 5 min.
spine.
thanks.

**Comment by cigamit** [comment]
Oh, one other thing, you are missing a Hard Rule at the end of the second legend.

**Comment by cigamit** [comment]
Closing.  Not an issue.
