### ISSUE TITLE
 Cacti 1.2.0: Call to undefined function clearstatscache

### ISSUE THREAD

**Issue by pautiina** [Cacti/cacti#1503]
2018/03/28 22:32:21 - ERROR PHP ERROR: Uncaught Error: Call to undefined function clearstatscache() in /var/www/data/cacti/lib/dsstats.php:164 Stack trace: #0 /var/www/data/cacti/lib/dsstats.php(71): dsstats_obtain_data_source_avgpeak_values('/var/www/data/c...', 'daily', Array) #1 /var/www/data/cacti/poller_dsstats.php(191): dsstats_get_and_store_ds_avgpeak_values('daily') #2 {main} thrown in file: /var/www/data/cacti/lib/dsstats.php on line: 164

**Comment by netniV** [comment]
Thanks AJ.  I'll submit a pull request shortly.  The fix is to change `clearstatscache()` to `clearstatcache()`

**Comment by netniV** [comment]
PR has now been created.

**Comment by pautiina** [comment]
Change please first line at file from:
`s<?php`
to:
`<?php`

**Comment by netniV** [comment]
Mine does not have that.

**Comment by cigamit** [comment]
Resolved.  Good work guys.
