### ISSUE TITLE
Cacti 1.1.37 : The abnormal display of the page

### ISSUE THREAD

**Issue by YangSheghui** [Cacti/cacti#1504]
CentOS 7
Cacti Version  1.1.37
PHP 7.0.27
Apache 2.4.6

hello, some pages are not normal, as shown below :

![1_the abnormal display of the page](https://user-images.githubusercontent.com/37231882/38075212-261bd562-3364-11e8-9555-16378aade127.jpg)

![2_the abnormal display of the page](https://user-images.githubusercontent.com/37231882/38075224-339ae8cc-3364-11e8-84d2-46566d2d571c.jpg)

How should I solve it ?

**Comment by netniV** [comment]
I can confirm that this is a bug.  We will have to look into how/why that this has crept in so please bare with us.

**Comment by netniV** [comment]
So the problem does not appear to be with the page itself.  More than likely, it's a fix for the recent XSS changes which may have caused the value to be escaped.

**Comment by cigamit** [comment]
I don't want to remove the escaping due to the security issues.  So, I will solve this a bit differently.

**Comment by cigamit** [comment]
You should be able to pull a patch off the last commit to fix the issue.

**Comment by netniV** [comment]
I just noticed this issue with the email test page.  I thought this had been fixed by commit https://github.com/Cacti/cacti/commit/c96d59c043d234427c5decec89624981df23ffc9 but it would appear to be still broken as I have that installed.

**Comment by netniV** [comment]
Turns out I was using my live site.  Which doesn't have this patch.

**Comment by YangSheghui** [comment]
The problem has been solved. Thank you very much!   @cigamit @netniV   You're doing a great job!

**Comment by YangSheghui** [comment]
The problem has been solved. Thank you very much!  @cigamit @netniV  You're doing a great job!

**Comment by netniV** [comment]
@YangSheghui That's good to hear, can you close this issue now then as I think you accidentally reopened it.
