### ISSUE TITLE
Feature: Option to go from Graph Preview/Tree to Device

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1505]
At the moment, if you are on the Graph View and realise you need to edit the device, there is no easy way back that I can see.  We should add a breadcrumb and/or right-click context option to edit the device.

**Comment by cigamit** [comment]
We had taken that feature out some time ago.  Due to space constraints.  Need to figure out how to bring it back without taking a lot of real-estate.  How about a right click context menu option?

**Comment by netniV** [comment]
Yeah or another icon on the breadcrumb list.

**Comment by cigamit** [comment]
Yea, that is another option, but @browniebraun hides the breadcrumbs on the page, maybe we just use a small glyph to the right of the device on the tree that appears on hover for users who have edit permissions.

**Comment by netniV** [comment]
Could do the same over the graph.  When do the breadcrumbs get hidden? I hadn't noticed that effect.

**Comment by cigamit** [comment]
A graph glyph to edit the device is more practical and a quick fix.

**Comment by cigamit** [comment]
Just resolved.  Give it a look over.
