### ISSUE TITLE
WARNING: Poller Output Table not Empty

### ISSUE THREAD

**Issue by tertius1** [Cacti/cacti#1511]
Sometimes, after a device reboot and subsequent recache, "WARNING: Poller Output Table not Empty." messages begin to appear in the log and the corresponding data is not inserted into to *.rrd file any more. For me, this happens ever since I started using Cacti 1.0.x.

```
03/30/2018 16:57:31 - POLLER: Poller[Main Poller] WARNING: Poller Output Table not Empty. Issues: 1, Graphs[pi - Traffic - eth0, pi - Traffic - eth0] DS[pi - Traffic - 10.1.0.1 - eth0]
03/30/2018 16:57:04 - SYSTEM STATS: Time:3.2286 Method:spine Processes:1 Threads:2 Hosts:8 HostsPerProcess:8 DataSources:36 RRDsProcessed:16
03/30/2018 16:57:01 - POLLER: Poller[Main Poller] WARNING: Poller Output Table not Empty. Issues: 1, Graphs[pi - Traffic - eth0, pi - Traffic - eth0] DS[pi - Traffic - 10.1.0.1 - eth0]
03/30/2018 16:56:33 - SYSTEM STATS: Time:2.2272 Method:spine Processes:1 Threads:2 Hosts:8 HostsPerProcess:8 DataSources:36 RRDsProcessed:23
03/30/2018 16:56:31 - POLLER: Poller[Main Poller] WARNING: Poller Output Table not Empty. Issues: 1, Graphs[pi - Traffic - eth0, pi - Traffic - eth0] DS[pi - Traffic - 10.1.0.1 - eth0]
03/30/2018 16:56:03 - SYSTEM STATS: Time:2.2263 Method:spine Processes:1 Threads:2 Hosts:8 HostsPerProcess:8 DataSources:36 RRDsProcessed:20
03/30/2018 16:56:01 - POLLER: Poller[Main Poller] WARNING: Poller Output Table not Empty. Issues: 1, Graphs[pi - Traffic - eth0, pi - Traffic - eth0] DS[pi - Traffic - 10.1.0.1 - eth0]
03/30/2018 16:55:33 - SYSTEM STATS: Time:2.2260 Method:spine Processes:1 Threads:2 Hosts:8 HostsPerProcess:8 DataSources:36 RRDsProcessed:22
03/30/2018 16:55:31 - POLLER: Poller[Main Poller] WARNING: Poller Output Table not Empty. Issues: 1, Graphs[pi - Traffic - eth0, pi - Traffic - eth0] DS[pi - Traffic - 10.1.0.1 - eth0]
03/30/2018 16:55:07 - SYSTEM STATS: Time:6.2349 Method:spine Processes:1 Threads:2 Hosts:8 HostsPerProcess:8 DataSources:36 RRDsProcessed:20
03/30/2018 16:55:01 - POLLER: Poller[Main Poller] WARNING: Poller Output Table not Empty. Issues: 1, Graphs[pi - Traffic - eth0, pi - Traffic - eth0] DS[pi - Traffic - 10.1.0.1 - eth0]
03/30/2018 16:54:33 - SYSTEM STATS: Time:2.2292 Method:spine Processes:1 Threads:2 Hosts:8 HostsPerProcess:8 DataSources:34 RRDsProcessed:21
03/30/2018 16:54:31 - POLLER: Poller[Main Poller] WARNING: Poller Output Table not Empty. Issues: 1, Graphs[pi - Traffic - eth0, pi - Traffic - eth0] DS[pi - Traffic - 10.1.0.1 - eth0]
03/30/2018 16:54:27 - RECACHE STATS: Poller: RecacheTime:1.5761 DevicesRecached:1
03/30/2018 16:54:26 - PCOMMAND Device[7] Device[pi] WARNING: Recache Event Detected for Device
03/30/2018 16:54:26 - SYSTEM STATS: Time:24.2545 Method:spine Processes:1 Threads:2 Hosts:8 HostsPerProcess:8 DataSources:34 RRDsProcessed:18
03/30/2018 16:54:24 - CMDPHP ERROR: Invalid Return Value in ss_host_cpu.php for get 2 and host_id 7
2018/03/30 16:54:24 - SPINE: Poller[Main Poller] Device[7] Device[pi] TH[1] NOTICE: Spike Kill in Effect for 'pi'
2018/03/30 16:54:24 - SPINE: Poller[Main Poller] Device[7] Device[pi] TH[1] ASSERT: '50170' .lt. '778' failed. Recaching host 'pi', data query #10
2018/03/30 16:54:24 - SPINE: Poller[Main Poller] Device[7] Device[pi] TH[1] NOTICE: Spike Kill in Effect for 'pi'
2018/03/30 16:54:24 - SPINE: Poller[Main Poller] Device[7] Device[pi] TH[1] ASSERT: '50170' .lt. '778' failed. Recaching host 'pi', data query #9
2018/03/30 16:54:24 - SPINE: Poller[Main Poller] Device[7] Device[pi] TH[1] NOTICE: Spike Kill in Effect for 'pi'
2018/03/30 16:54:24 - SPINE: Poller[Main Poller] Device[7] Device[pi] TH[1] ASSERT: '50170' .lt. '778' failed. Recaching host 'pi', data query #8
2018/03/30 16:54:24 - SPINE: Poller[Main Poller] Device[7] Device[pi] TH[1] NOTICE: Spike Kill in Effect for 'pi'
2018/03/30 16:54:24 - SPINE: Poller[Main Poller] Device[7] Device[pi] TH[1] ASSERT: '50170' .lt. '778' failed. Recaching host 'pi', data query #2
2018/03/30 16:54:24 - SPINE: Poller[Main Poller] Device[7] Device[pi] TH[1] NOTICE: Spike Kill in Effect for 'pi'
2018/03/30 16:54:24 - SPINE: Poller[Main Poller] Device[7] Device[pi] TH[1] ASSERT: '50170' .lt. '778' failed. Recaching host 'pi', data query #1
2018/03/30 16:54:22 - SPINE: Poller[Main Poller] Device[10] Device[mail] Hostname[mail.wombaz.de] NOTICE: HOST EVENT: Device Returned from DOWN State
03/30/2018 16:54:01 - POLLER: Poller[Main Poller] WARNING: Poller Output Table not Empty. Issues: 1, Graphs[pi - Traffic - eth0, pi - Traffic - eth0] DS[pi - Traffic - 10.1.0.1 - eth0]
```

About my configuration: I added a "1 minute polling" and "30 seconds polling" data source profile, and the data sources in question are all on the 1 minute poller intverval. I also have some other data sources running on 30 seconds. Looking into the cacti database into the table cacti.poller_item for that data source, I see this:

163 | 1 | 7 | 0 | 1 | 2018-03-30 17:56:02 | pi | xxxxxxx | 2 |   |   |   |   |   |   |   | 161 | 1000 | traffic_in | /usr/share/cacti/rra/pi_traffic_in_163.rrd | 2 | 60 | 30 | .1.3.6.1.2.1.31.1.1.1.6.2
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
163 | 1 | 7 | 0 | 1 | 2018-03-30 17:56:02 | pi | xxxxxxx | 2 |   |   |   |   |   |   |   | 161 | 1000 | traffic_out | /usr/share/cacti/rra/pi_traffic_in_163.rrd | 2 | 60 | 0 | .1.3.6.1.2.1.31.1.1.1.10.2

The next to last column is "rrd_next_step", and whenever the warning occurs, either traffic_in contains 30 in that column and traffic_out contains 0, or vice versa. It toggles every 30 seconds. If I manually write a 0 to both records with Mysql Workbench, or both to 30, the warning ceases and the data is recorded and graphed fine again. Until the next recache.
I tried to debug the php code that uses this table, but unfortunately this is so complex I wasn't able to get it.

Cacti settings: Cron interval is 5 minutes, poller interval is 30 seconds.
Data sources in question run on a data profile with 60 seconds poller interval.
Happens with cmd.php and spine.
A tiny installation with 8 devices at home.
Current version I use and where problem still happens: 1.1.36.

**Comment by tertius1** [comment]
Poller interval is at 30 seconds. Cron job is started every 5 minutes.
![image](https://user-images.githubusercontent.com/26193033/38302513-3c65e328-3803-11e8-8ef0-609b208909a9.png)
And I repopulated the poller cache so many times, I cannot count. Does not repair. I have 2 devices that exhibit that behavior, sometimes it starts to happen after repopulating the poller cache, sometimes it stops after repopulating the poller cache, and sometimes simply nothing changes if I repopulate the poller cache. Usually, it starts to happen after device reboot or whenever I edit a device in cacti and save the device data.
If it helps, I can attach a dump of the mysql database - it is tiny and contains no corporate confidential data.

**Comment by cigamit** [comment]
Okay, I re-read your last post and the rrd_next_step should be the same for each data source.  So, something is wrong.  Have to check things out.

**Comment by cigamit** [comment]
Run the following and post the results:

`select local_data_id, rrd_num, rrd_step, rrd_next_step from poller_item where rrd_num>1 order by local_data_id;`

**Comment by cigamit** [comment]
Also post the last 1000 lines or your "SYSTEM STATS:" from the Cacti log file.

**Comment by tertius1** [comment]
Sql output:
[poller_item_csv.txt](https://github.com/Cacti/cacti/files/1879399/poller_item_csv.txt)

Last 1000 lines from cacti.log:
[cacti_log.txt](https://github.com/Cacti/cacti/files/1879422/cacti_log.txt)

**Comment by cigamit** [comment]
Okay, just about to fix the ASSERT issue.  This was a combination of php-snmp and php version.

**Comment by cigamit** [comment]
I've got a fix for the poller output not empty.  Hopefully, it'll be permanent.

**Comment by cigamit** [comment]
Okay, update poller.php and cmd.php from develop, and I believe this issue is fully resolved.  If things are cleared up, just close this ticket.

**Comment by cigamit** [comment]
Thanks for testing!   All fixed up now.
