### ISSUE TITLE
Cacti 1.1.37: there are a lot of chaotic characters on the thresholds interface

### ISSUE THREAD

**Issue by YangSheghui** [Cacti/cacti#1513]
Hello, when i fix 1504 , i find there are a lot of chaotic characters on the thresholds interface, as shown below :
![aa](https://user-images.githubusercontent.com/37231882/38226151-b3d6d23e-372a-11e8-8b37-b18224ce825d.jpg)

Have you met?

**Comment by netniV** [comment]
Yes, this is related to #1504 and #1516

**Comment by cigamit** [comment]
This is resolved in the following commit.  Please apply by hand.  There are a few additional commits.  We are working on a patch.  https://github.com/Cacti/cacti/commit/3861cf8d726e4b917e53cd2d2ebaaef58039340f
