### ISSUE TITLE
Realtime pop up has very high processor load

### ISSUE THREAD

**Issue by majed17** [Cacti/cacti#1515]
Health be upon you. Before this long awaited feature, there was no problem with processor load in inline mode for real time. now, with 8 popups, 1 hour window, 2 minute refresh, the processor frequently reaches over 90%, particularly in ie 11. I haven't tried it on firefox, yet. Years ago, when there used to be popups for real time, there was no such issue.

**Comment by cigamit** [comment]
Sorry, this was NOT resolved here https://github.com/Cacti/cacti/commit/3861cf8d726e4b917e53cd2d2ebaaef58039340f.  Typo.

**Comment by cigamit** [comment]
Well that is very odd.  Can you capture the screen output from your process list sorted by process and copy here.  Also, put IE into debug mode and then goto the Network panel and clear it.  Do you see continual calls to the backend even though the timing is per 2 minutes?

**Comment by majed17** [comment]
I opened 9 windows in FF with the same settings and there is no such problem here. after hibernating the pc, the windows became white even though the theme is dark. I changed the theme to sunrise, and the windows turned black again, and now with 9 ff windows and 8 ie the load is around 20% even though i changed the setting on the ie windows to 1 hour window 15 sec refresh. any sense to you?

**Comment by cigamit** [comment]
Can you post the output from the network panel of the debug window when this is occurring?

**Comment by majed17** [comment]
Sorry, you'll have to wait until my vacation is over!

**Comment by majed17** [comment]
you talk to me like i am an assistant who helps you in programming, what "network panel of the debug window"? and just out of interest, I opened 12 windows on an 8 core cpu, and ie was not the first in the list in cpu consumption, unlike like it is at work, with less than 21% cpu load!

**Comment by cigamit** [comment]
Closing.

**Comment by majed17** [comment]
Well normal open source software has an obvious donate button somewhere which people who like it use. I tried unchecking ie11 and checking it back in but that didn't help. Since it is not a cacti problem the I will see what I can do!

**Comment by cigamit** [comment]
There is a donate button on the main Cacti page.

**Comment by anarkia1976** [comment]
I can confirm, i have made a donation some time ago! _)

**Comment by majed17** [comment]
Well hiding it doesn't help you and even an internet search links to a dead link!
