### ISSUE TITLE
Special Characters in cacti settings

### ISSUE THREAD

**Issue by chathurag** [Cacti/cacti#1516]
![cacti](https://user-images.githubusercontent.com/35136010/38243896-9307ed8c-3756-11e8-8065-50f4cd0b3423.png)

Greater than and less than symbols in above image is shown as numbers

**Comment by netniV** [comment]
This appears to be related to #1504

**Comment by cigamit** [comment]
Resolved in this commit https://github.com/Cacti/cacti/commit/3861cf8d726e4b917e53cd2d2ebaaef58039340f
