### ISSUE TITLE
Aggregates Breaking

### ISSUE THREAD

**Issue by andermat8** [Cacti/cacti#1517]
Testing in 1.1.29, 1.1.36, and 1.1.37 with same results.  Is there a limit in how many graphs you can have in an aggregate or the amount of data being combined perhaps?  I'm creating aggs with a variety of different graphs and it will work up to a point until I add a certain number and then I just get a Cactus picture.  If I remove other graphs and keep the new ones that were added when it broke it will work again.  Currently have 17 graphs in an agg and it works but if I add another it will break.  Same issue when creating aggregates from aggregate.

**Comment by cigamit** [comment]
Cut and paste the Debug information into a shell window and redirect the output to a file.  What kind of errors are you getting?  What is your Cacti server OS type?  If Windows, migrate to Linux.

**Comment by andermat8** [comment]
![image](https://user-images.githubusercontent.com/29753529/38306938-1c9caa54-37e0-11e8-85a1-f2eda2decd80.png)

RRDtool Command:
d:/rrdtool/rrdtool.exe graph - \
--imgformat= \
--start="-180000" \
--end="-300" \
--pango-markup  \
--title="TEST AGG" \
--slope-mode \
--height=0 \
--width=0 \
--tabwidth "30" \
--upper-limit="0" \
--lower-limit="0" \
--border 1 --font TITLE:9: \
--font AXIS:7: \
--font LEGEND:8: \
--font UNIT:7: \
--font WATERMARK:8: \
--slope-mode \
--watermark "Network Engineering" \
DEF:a="D\:/inetpub/wwwroot/cacti/rra/10_193_70_50_traffic_in_33131.rrd":"traffic_in":AVERAGE \
DEF:b="D\:/inetpub/wwwroot/cacti/rra/10_193_70_50_traffic_in_33131.rrd":"traffic_out":AVERAGE \
DEF:c="D\:/inetpub/wwwroot/cacti/rra/10_193_70_100_traffic_in_33164.rrd":"traffic_in":AVERAGE \
DEF:d="D\:/inetpub/wwwroot/cacti/rra/10_193_70_100_traffic_in_33164.rrd":"traffic_out":AVERAGE \
DEF:e="D\:/inetpub/wwwroot/cacti/rra/fbdinwcrt002_traffic_in_34693.rrd":"traffic_in":AVERAGE \
DEF:f="D\:/inetpub/wwwroot/cacti/rra/fbdinwcrt002_traffic_in_34693.rrd":"traffic_out":AVERAGE \
DEF:g="D\:/inetpub/wwwroot/cacti/rra/fbdinwcrt001_traffic_in_34694.rrd":"traffic_in":AVERAGE \
DEF:h="D\:/inetpub/wwwroot/cacti/rra/fbdinwcrt001_traffic_in_34694.rrd":"traffic_out":AVERAGE \
DEF:i="D\:/inetpub/wwwroot/cacti/rra/dbninwcrt002_traffic_in_34705.rrd":"traffic_in":AVERAGE \
DEF:j="D\:/inetpub/wwwroot/cacti/rra/dbninwcrt002_traffic_in_34705.rrd":"traffic_out":AVERAGE \
DEF:ba="D\:/inetpub/wwwroot/cacti/rra/dbninwcrt001_traffic_in_34706.rrd":"traffic_in":AVERAGE \
DEF:bb="D\:/inetpub/wwwroot/cacti/rra/dbninwcrt001_traffic_in_34706.rrd":"traffic_out":AVERAGE \
DEF:bc="D\:/inetpub/wwwroot/cacti/rra/bgainwcrt002_traffic_in_34719.rrd":"traffic_in":AVERAGE \
DEF:bd="D\:/inetpub/wwwroot/cacti/rra/bgainwcrt002_traffic_in_34719.rrd":"traffic_out":AVERAGE \
DEF:be="D\:/inetpub/wwwroot/cacti/rra/bgainwcrt001_traffic_in_34819.rrd":"traffic_in":AVERAGE \
DEF:bf="D\:/inetpub/wwwroot/cacti/rra/bgainwcrt001_traffic_in_34819.rrd":"traffic_out":AVERAGE \
DEF:bg="D\:/inetpub/wwwroot/cacti/rra/lmrinwcrt001_traffic_in_35896.rrd":"traffic_in":AVERAGE \
DEF:bh="D\:/inetpub/wwwroot/cacti/rra/lmrinwcrt001_traffic_in_35896.rrd":"traffic_out":AVERAGE \
DEF:bi="D\:/inetpub/wwwroot/cacti/rra/lmrinwcrt002_traffic_in_35905.rrd":"traffic_in":AVERAGE \
DEF:bj="D\:/inetpub/wwwroot/cacti/rra/lmrinwcrt002_traffic_in_35905.rrd":"traffic_out":AVERAGE \
DEF:ca="D\:/inetpub/wwwroot/cacti/rra/pdginwcrt001_traffic_in_37494.rrd":"traffic_in":AVERAGE \
DEF:cb="D\:/inetpub/wwwroot/cacti/rra/pdginwcrt001_traffic_in_37494.rrd":"traffic_out":AVERAGE \
DEF:cc="D\:/inetpub/wwwroot/cacti/rra/pdginwcrt002_traffic_in_37498.rrd":"traffic_in":AVERAGE \
DEF:cd="D\:/inetpub/wwwroot/cacti/rra/pdginwcrt002_traffic_in_37498.rrd":"traffic_out":AVERAGE \
DEF:ce="D\:/inetpub/wwwroot/cacti/rra/kmpinwcrt001_traffic_in_42723.rrd":"traffic_in":AVERAGE \
DEF:zzcf="D\:/inetpub/wwwroot/cacti/rra/kmpinwcrt001_traffic_in_42723.rrd":"traffic_out":AVERAGE \
DEF:cg="D\:/inetpub/wwwroot/cacti/rra/bphcrmdrt001_traffic_in_44640.rrd":"traffic_in":AVERAGE \
DEF:ch="D\:/inetpub/wwwroot/cacti/rra/bphcrmdrt001_traffic_in_44640.rrd":"traffic_out":AVERAGE \
DEF:ci="D\:/inetpub/wwwroot/cacti/rra/bphcrmdrt002_traffic_in_44659.rrd":"traffic_in":AVERAGE \
DEF:cj="D\:/inetpub/wwwroot/cacti/rra/bphcrmdrt002_traffic_in_44659.rrd":"traffic_out":AVERAGE \
DEF:da="D\:/inetpub/wwwroot/cacti/rra/chacrwdsw002_traffic_in_45062.rrd":"traffic_in":AVERAGE \
DEF:db="D\:/inetpub/wwwroot/cacti/rra/chacrwdsw002_traffic_in_45062.rrd":"traffic_out":AVERAGE \
DEF:dc="D\:/inetpub/wwwroot/cacti/rra/mmathray01-fsr53_traffic_in_46971.rrd":"traffic_in":AVERAGE \
DEF:dd="D\:/inetpub/wwwroot/cacti/rra/mmathray01-fsr53_traffic_in_46971.rrd":"traffic_out":AVERAGE \
DEF:de="D\:/inetpub/wwwroot/cacti/rra/mmathray01-fsr54_traffic_in_46972.rrd":"traffic_in":AVERAGE \
DEF:df="D\:/inetpub/wwwroot/cacti/rra/mmathray01-fsr54_traffic_in_46972.rrd":"traffic_out":AVERAGE \
DEF:dg="D\:/inetpub/wwwroot/cacti/rra/tacinwcrt001_traffic_in_46973.rrd":"traffic_in":AVERAGE \
DEF:dh="D\:/inetpub/wwwroot/cacti/rra/tacinwcrt001_traffic_in_46973.rrd":"traffic_out":AVERAGE \
DEF:di="D\:/inetpub/wwwroot/cacti/rra/tacinwcrt002_traffic_in_46974.rrd":"traffic_in":AVERAGE \
DEF:dj="D\:/inetpub/wwwroot/cacti/rra/tacinwcrt002_traffic_in_46974.rrd":"traffic_out":AVERAGE \
DEF:ea="D\:/inetpub/wwwroot/cacti/rra/sw2inwcrt001_traffic_in_46977.rrd":"traffic_in":AVERAGE \
DEF:eb="D\:/inetpub/wwwroot/cacti/rra/sw2inwcrt001_traffic_in_46977.rrd":"traffic_out":AVERAGE \
DEF:ec="D\:/inetpub/wwwroot/cacti/rra/sw2inwcrt002_traffic_in_46978.rrd":"traffic_in":AVERAGE \
DEF:ed="D\:/inetpub/wwwroot/cacti/rra/sw2inwcrt002_traffic_in_46978.rrd":"traffic_out":AVERAGE \
CDEF:cdefa="a,0,*" \
CDEF:cdefc="b,0,*" \
CDEF:cdefe="c,0,*" \
CDEF:cdefg="d,0,*" \
CDEF:cdefi="e,0,*" \
CDEF:cdefba="f,0,*" \
CDEF:cdefbc="g,0,*" \
CDEF:cdefbe="h,0,*" \
CDEF:cdefbg="i,0,*" \
CDEF:cdefbi="j,0,*" \
CDEF:cdefca="ba,0,*" \
CDEF:cdefcc="bb,0,*" \
CDEF:cdefce="bc,0,*" \
CDEF:cdefcg="bd,0,*" \
CDEF:cdefci="be,0,*" \
CDEF:cdefda="bf,0,*" \
CDEF:cdefdc="bg,0,*" \
CDEF:cdefde="bh,0,*" \
CDEF:cdefdg="bi,0,*" \
CDEF:cdefdi="bj,0,*" \
CDEF:cdefea="ca,0,*" \
CDEF:cdefec="cb,0,*" \
CDEF:cdefee="cc,0,*" \
CDEF:cdefeg="cd,0,*" \
CDEF:cdefei="ce,0,*" \
CDEF:cdeffa="zzcf,0,*" \
CDEF:cdeffc="cg,0,*" \
CDEF:cdeffe="ch,0,*" \
CDEF:cdeffg="ci,0,*" \
CDEF:cdeffi="cj,0,*" \
CDEF:cdefga="da,0,*" \
CDEF:cdefgc="db,0,*" \
CDEF:cdefge="dc,0,*" \
CDEF:cdefgg="dd,0,*" \
CDEF:cdefgi="de,0,*" \
CDEF:cdefha="df,0,*" \
CDEF:cdefhc="dg,0,*" \
CDEF:cdefhe="dh,0,*" \
CDEF:cdefhg="di,0,*" \
CDEF:cdefhi="dj,0,*" \
CDEF:cdefia="ea,0,*" \
CDEF:cdefic="eb,0,*" \
CDEF:cdefie="ec,0,*" \
CDEF:cdefig="ed,0,*" \
CDEF:cdefii="TIME,1522843396,GT,a,a,UN,0,a,IF,IF,TIME,1522843396,GT,c,c,UN,0,c,IF,IF,TIME,1522843396,GT,e,e,UN,0,e,IF,IF,TIME,1522843396,GT,g,g,UN,0,g,IF,IF,TIME,1522843396,GT,i,i,UN,0,i,IF,IF,TIME,1522843396,GT,ba,ba,UN,0,ba,IF,IF,TIME,1522843396,GT,bc,bc,UN,0,bc,IF,IF,TIME,1522843396,GT,be,be,UN,0,be,IF,IF,TIME,1522843396,GT,bg,bg,UN,0,bg,IF,IF,TIME,1522843396,GT,bi,bi,UN,0,bi,IF,IF,TIME,1522843396,GT,ca,ca,UN,0,ca,IF,IF,TIME,1522843396,GT,cc,cc,UN,0,cc,IF,IF,TIME,1522843396,GT,ce,ce,UN,0,ce,IF,IF,TIME,1522843396,GT,cg,cg,UN,0,cg,IF,IF,TIME,1522843396,GT,ci,ci,UN,0,ci,IF,IF,TIME,1522843396,GT,da,da,UN,0,da,IF,IF,TIME,1522843396,GT,dc,dc,UN,0,dc,IF,IF,TIME,1522843396,GT,de,de,UN,0,de,IF,IF,TIME,1522843396,GT,dg,dg,UN,0,dg,IF,IF,TIME,1522843396,GT,di,di,UN,0,di,IF,IF,TIME,1522843396,GT,ea,ea,UN,0,ea,IF,IF,TIME,1522843396,GT,ec,ec,UN,0,ec,IF,IF,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,8,*" \
CDEF:cdefjb="TIME,1522843396,GT,a,a,UN,0,a,IF,IF,TIME,1522843396,GT,c,c,UN,0,c,IF,IF,TIME,1522843396,GT,e,e,UN,0,e,IF,IF,TIME,1522843396,GT,g,g,UN,0,g,IF,IF,TIME,1522843396,GT,i,i,UN,0,i,IF,IF,TIME,1522843396,GT,ba,ba,UN,0,ba,IF,IF,TIME,1522843396,GT,bc,bc,UN,0,bc,IF,IF,TIME,1522843396,GT,be,be,UN,0,be,IF,IF,TIME,1522843396,GT,bg,bg,UN,0,bg,IF,IF,TIME,1522843396,GT,bi,bi,UN,0,bi,IF,IF,TIME,1522843396,GT,ca,ca,UN,0,ca,IF,IF,TIME,1522843396,GT,cc,cc,UN,0,cc,IF,IF,TIME,1522843396,GT,ce,ce,UN,0,ce,IF,IF,TIME,1522843396,GT,cg,cg,UN,0,cg,IF,IF,TIME,1522843396,GT,ci,ci,UN,0,ci,IF,IF,TIME,1522843396,GT,da,da,UN,0,da,IF,IF,TIME,1522843396,GT,dc,dc,UN,0,dc,IF,IF,TIME,1522843396,GT,de,de,UN,0,de,IF,IF,TIME,1522843396,GT,dg,dg,UN,0,dg,IF,IF,TIME,1522843396,GT,di,di,UN,0,di,IF,IF,TIME,1522843396,GT,ea,ea,UN,0,ea,IF,IF,TIME,1522843396,GT,ec,ec,UN,0,ec,IF,IF,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,query_ifHighSpeed000000,/,100,*,8,*" \
CDEF:cdefjg="TIME,1522843396,GT,b,b,UN,0,b,IF,IF,TIME,1522843396,GT,d,d,UN,0,d,IF,IF,TIME,1522843396,GT,f,f,UN,0,f,IF,IF,TIME,1522843396,GT,h,h,UN,0,h,IF,IF,TIME,1522843396,GT,j,j,UN,0,j,IF,IF,TIME,1522843396,GT,bb,bb,UN,0,bb,IF,IF,TIME,1522843396,GT,bd,bd,UN,0,bd,IF,IF,TIME,1522843396,GT,bf,bf,UN,0,bf,IF,IF,TIME,1522843396,GT,bh,bh,UN,0,bh,IF,IF,TIME,1522843396,GT,bj,bj,UN,0,bj,IF,IF,TIME,1522843396,GT,cb,cb,UN,0,cb,IF,IF,TIME,1522843396,GT,cd,cd,UN,0,cd,IF,IF,TIME,1522843396,GT,zzcf,zzcf,UN,0,zzcf,IF,IF,TIME,1522843396,GT,ch,ch,UN,0,ch,IF,IF,TIME,1522843396,GT,cj,cj,UN,0,cj,IF,IF,TIME,1522843396,GT,db,db,UN,0,db,IF,IF,TIME,1522843396,GT,dd,dd,UN,0,dd,IF,IF,TIME,1522843396,GT,df,df,UN,0,df,IF,IF,TIME,1522843396,GT,dh,dh,UN,0,dh,IF,IF,TIME,1522843396,GT,dj,dj,UN,0,dj,IF,IF,TIME,1522843396,GT,eb,eb,UN,0,eb,IF,IF,TIME,1522843396,GT,ed,ed,UN,0,ed,IF,IF,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,8,*" \
CDEF:cdefjj="TIME,1522843396,GT,b,b,UN,0,b,IF,IF,TIME,1522843396,GT,d,d,UN,0,d,IF,IF,TIME,1522843396,GT,f,f,UN,0,f,IF,IF,TIME,1522843396,GT,h,h,UN,0,h,IF,IF,TIME,1522843396,GT,j,j,UN,0,j,IF,IF,TIME,1522843396,GT,bb,bb,UN,0,bb,IF,IF,TIME,1522843396,GT,bd,bd,UN,0,bd,IF,IF,TIME,1522843396,GT,bf,bf,UN,0,bf,IF,IF,TIME,1522843396,GT,bh,bh,UN,0,bh,IF,IF,TIME,1522843396,GT,bj,bj,UN,0,bj,IF,IF,TIME,1522843396,GT,cb,cb,UN,0,cb,IF,IF,TIME,1522843396,GT,cd,cd,UN,0,cd,IF,IF,TIME,1522843396,GT,zzcf,zzcf,UN,0,zzcf,IF,IF,TIME,1522843396,GT,ch,ch,UN,0,ch,IF,IF,TIME,1522843396,GT,cj,cj,UN,0,cj,IF,IF,TIME,1522843396,GT,db,db,UN,0,db,IF,IF,TIME,1522843396,GT,dd,dd,UN,0,dd,IF,IF,TIME,1522843396,GT,df,df,UN,0,df,IF,IF,TIME,1522843396,GT,dh,dh,UN,0,dh,IF,IF,TIME,1522843396,GT,dj,dj,UN,0,dj,IF,IF,TIME,1522843396,GT,eb,eb,UN,0,eb,IF,IF,TIME,1522843396,GT,ed,ed,UN,0,ed,IF,IF,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,query_ifHighSpeed000000,/,100,*,8,*" \
CDEF:cdefbae="TIME,1522843396,GT,b,b,UN,0,b,IF,IF,TIME,1522843396,GT,d,d,UN,0,d,IF,IF,TIME,1522843396,GT,f,f,UN,0,f,IF,IF,TIME,1522843396,GT,h,h,UN,0,h,IF,IF,TIME,1522843396,GT,j,j,UN,0,j,IF,IF,TIME,1522843396,GT,bb,bb,UN,0,bb,IF,IF,TIME,1522843396,GT,bd,bd,UN,0,bd,IF,IF,TIME,1522843396,GT,bf,bf,UN,0,bf,IF,IF,TIME,1522843396,GT,bh,bh,UN,0,bh,IF,IF,TIME,1522843396,GT,bj,bj,UN,0,bj,IF,IF,TIME,1522843396,GT,cb,cb,UN,0,cb,IF,IF,TIME,1522843396,GT,cd,cd,UN,0,cd,IF,IF,TIME,1522843396,GT,zzcf,zzcf,UN,0,zzcf,IF,IF,TIME,1522843396,GT,ch,ch,UN,0,ch,IF,IF,TIME,1522843396,GT,cj,cj,UN,0,cj,IF,IF,TIME,1522843396,GT,db,db,UN,0,db,IF,IF,TIME,1522843396,GT,dd,dd,UN,0,dd,IF,IF,TIME,1522843396,GT,df,df,UN,0,df,IF,IF,TIME,1522843396,GT,dh,dh,UN,0,dh,IF,IF,TIME,1522843396,GT,dj,dj,UN,0,dj,IF,IF,TIME,1522843396,GT,eb,eb,UN,0,eb,IF,IF,TIME,1522843396,GT,ed,ed,UN,0,ed,IF,IF,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+" \
LINE1:cdefa#00CF00FF:""  \
AREA:cdefa#00CF0033:""  \
AREA:cdefc#002A9719:""  \
LINE1:cdefc#002A97FF:""  \
LINE1:cdefe#00CF00FF:""  \
AREA:cdefe#00CF0033:""  \
AREA:cdefg#002A9719:""  \
LINE1:cdefg#002A97FF:""  \
LINE1:cdefi#00CF00FF:""  \
AREA:cdefi#00CF0033:""  \
AREA:cdefba#002A9719:""  \
LINE1:cdefba#002A97FF:""  \
LINE1:cdefbc#00CF00FF:""  \
AREA:cdefbc#00CF0033:""  \
AREA:cdefbe#002A9719:""  \
LINE1:cdefbe#002A97FF:""  \
LINE1:cdefbg#00CF00FF:""  \
AREA:cdefbg#00CF0033:""  \
AREA:cdefbi#002A9719:""  \
LINE1:cdefbi#002A97FF:""  \
LINE1:cdefca#00CF00FF:""  \
AREA:cdefca#00CF0033:""  \
AREA:cdefcc#002A9719:""  \
LINE1:cdefcc#002A97FF:""  \
LINE1:cdefce#00CF00FF:""  \
AREA:cdefce#00CF0033:""  \
AREA:cdefcg#002A9719:""  \
LINE1:cdefcg#002A97FF:""  \
LINE1:cdefci#00CF00FF:""  \
AREA:cdefci#00CF0033:""  \
AREA:cdefda#002A9719:""  \
LINE1:cdefda#002A97FF:""  \
LINE1:cdefdc#00CF00FF:""  \
AREA:cdefdc#00CF0033:""  \
AREA:cdefde#002A9719:""  \
LINE1:cdefde#002A97FF:""  \
LINE1:cdefdg#00CF00FF:""  \
AREA:cdefdg#00CF0033:""  \
AREA:cdefdi#002A9719:""  \
LINE1:cdefdi#002A97FF:""  \
LINE1:cdefea#00CF00FF:""  \
AREA:cdefea#00CF0033:""  \
AREA:cdefec#002A9719:""  \
LINE1:cdefec#002A97FF:""  \
LINE1:cdefee#00CF00FF:""  \
AREA:cdefee#00CF0033:""  \
AREA:cdefeg#002A9719:""  \
LINE1:cdefeg#002A97FF:""  \
LINE1:cdefei#00CF00FF:""  \
AREA:cdefei#00CF0033:""  \
AREA:cdeffa#002A9719:""  \
LINE1:cdeffa#002A97FF:""  \
LINE1:cdeffc#00CF00FF:""  \
AREA:cdeffc#00CF0033:""  \
AREA:cdeffe#002A9719:""  \
LINE1:cdeffe#002A97FF:""  \
LINE1:cdeffg#00CF00FF:""  \
AREA:cdeffg#00CF0033:""  \
AREA:cdeffi#002A9719:""  \
LINE1:cdeffi#002A97FF:""  \
LINE1:cdefga#00CF00FF:""  \
AREA:cdefga#00CF0033:""  \
AREA:cdefgc#002A9719:""  \
LINE1:cdefgc#002A97FF:""  \
LINE1:cdefge#00CF00FF:""  \
AREA:cdefge#00CF0033:""  \
AREA:cdefgg#002A9719:""  \
LINE1:cdefgg#002A97FF:""  \
LINE1:cdefgi#00CF00FF:""  \
AREA:cdefgi#00CF0033:""  \
AREA:cdefha#002A9719:""  \
LINE1:cdefha#002A97FF:""  \
LINE1:cdefhc#00CF00FF:""  \
AREA:cdefhc#00CF0033:""  \
AREA:cdefhe#002A9719:""  \
LINE1:cdefhe#002A97FF:""  \
LINE1:cdefhg#00CF00FF:""  \
AREA:cdefhg#00CF0033:""  \
AREA:cdefhi#002A9719:""  \
LINE1:cdefhi#002A97FF:""  \
LINE1:cdefia#00CF00FF:""  \
AREA:cdefia#00CF0033:""  \
AREA:cdefic#002A9719:""  \
LINE1:cdefic#002A97FF:""  \
LINE1:cdefie#00CF00FF:""  \
AREA:cdefie#00CF0033:""  \
AREA:cdefig#002A9719:""  \
LINE1:cdefig#002A97FF:""  \
LINE1:cdefii#00CF00FF:""  \
AREA:cdefii#00CF0033:"Total In"  \
GPRINT:cdefii:LAST:"Current\:%8.2lf %s"  \
GPRINT:cdefjb:LAST:"(%3.2lf%%)"  \
GPRINT:cdefii:AVERAGE:"Average\:%8.2lf %s"  \
GPRINT:cdefjb:AVERAGE:"(%3.2lf%%)"  \
GPRINT:cdefii:MAX:"Maximum\:%8.2lf %s"  \
GPRINT:cdefjb:MAX:"(%3.2lf%%)\n"  \
AREA:cdefjg#002A9719:""  \
LINE1:cdefjg#002A97FF:"Out"  \
GPRINT:cdefjg:LAST:"Current\:%8.2lf %s"  \
GPRINT:cdefjj:LAST:"(%3.2lf%%)"  \
GPRINT:cdefjg:AVERAGE:"Average\:%8.2lf %s"  \
GPRINT:cdefjj:AVERAGE:"(%3.2lf%%)"  \
GPRINT:cdefjg:MAX:"Maximum\:%8.2lf %s"  \
GPRINT:cdefjj:MAX:"(%3.2lf%%)"  \
COMMENT:" \n"  \
COMMENT:"CIRCUIT SPEED\: |query_ifHighSpeed| Mb/s\n" 

RRDtool Says:

**Comment by andermat8** [comment]
I'm running Cacti on Windows Server 2012 and can't easily convert over to Linux at this time.

**Comment by cigamit** [comment]
You will need to post a screen shot of your Aggregate Template, as the debug looks incorrect, but might work just the same.  The reason I ask about Windows, is that there is a 8192 character limit on commands sent to a shell.  That limit is pretty much indefinite on Linux.  So, though the debug output is bad, you may still be hitting the shell limit.  Show me the aggregate both before and after it breaks.

**Comment by andermat8** [comment]
![image](https://user-images.githubusercontent.com/29753529/38330742-60ce8cf8-381f-11e8-843c-a0993c5d2cdf.png)
![image](https://user-images.githubusercontent.com/29753529/38330791-82b2319e-381f-11e8-8b1a-634276187200.png)
![image](https://user-images.githubusercontent.com/29753529/38330804-8f14901c-381f-11e8-897a-ace136c7d43e.png)
![image](https://user-images.githubusercontent.com/29753529/38330832-a0027a60-381f-11e8-8c33-a6a8fa8f5fab.png)
![image](https://user-images.githubusercontent.com/29753529/38330849-ac4d1064-381f-11e8-9a54-15b4fab0b2e3.png)

**Comment by andermat8** [comment]
Thanks.  I can move toward a Linux platform but it will take months to do.  I'm assuming this works fine with OEL.

**Comment by cigamit** [comment]
I would suspect so.  It's a very close analog to RHEL.  It's more like CentOS than RHEL though.  I'm sure Oracle would beg to differ, but that is not my problem.  I'm just going to close this for now.  We've got a rash of other Aggregate features, and I'll add my discovery from this ticket to one of the others.
