### ISSUE TITLE
Cacti 1.2.0 - Latest Develop Branch

### ISSUE THREAD

**Issue by anarkia1976** [Cacti/cacti#1519]
Hi,
after a full update i have these errors into cacti logs:
2018/04/04 11:09:53 - CMDPHP PHP ERROR NOTICE Backtrace: (/graph_json.php: 158 rrdtool_function_graph)(/lib/rrd.php: 1785 rrd_substitute_host_query_data)(/lib/rrd.php: 2366 substitute_host_data)(/lib/variables.php: 182 CactiErrorHandler)(/lib/functions.php: 4599 cacti_debug_backtrace)
2018/04/04 11:09:53 - ERROR PHP NOTICE: Undefined index: location in file: /usr/share/cacti/lib/variables.php on line: 182
2018/04/04 11:09:53 - CMDPHP PHP ERROR NOTICE Backtrace: (/graph_json.php: 158 rrdtool_function_graph)(/lib/rrd.php: 1956 rrd_substitute_host_query_data)(/lib/rrd.php: 2366 substitute_host_data)(/lib/variables.php: 182 CactiErrorHandler)(/lib/functions.php: 4599 cacti_debug_backtrace)
2018/04/04 11:09:53 - ERROR PHP NOTICE: Undefined index: location in file: /usr/share/cacti/lib/variables.php on line: 182
2018/04/04 11:09:53 - CMDPHP PHP ERROR NOTICE Backtrace: (/graph_json.php: 158 rrdtool_function_graph)(/lib/rrd.php: 1785 rrd_substitute_host_query_data)(/lib/rrd.php: 2366 substitute_host_data)(/lib/variables.php: 182 CactiErrorHandler)(/lib/functions.php: 4599 cacti_debug_backtrace)
2018/04/04 11:09:53 - ERROR PHP NOTICE: Undefined index: location in file: /usr/share/cacti/lib/variables.php on line: 182
2018/04/04 11:09:53 - CMDPHP PHP ERROR NOTICE Backtrace: (/graph_json.php: 158 rrdtool_function_graph)(/lib/rrd.php: 1785 rrd_substitute_host_query_data)(/lib/rrd.php: 2366 substitute_host_data)(/lib/variables.php: 182 CactiErrorHandler)(/lib/functions.php: 4599 cacti_debug_backtrace)
2018/04/04 11:09:53 - ERROR PHP NOTICE: Undefined index: location in file: /usr/share/cacti/lib/variables.php on line: 182
Thanks a lot.

**Comment by pautiina** [comment]
How did you update? Through Git? Which version of Cacti?
I just updated myself from the development branch and I do not have such a problem

**Comment by pautiina** [comment]
Ok, I think that it's problem with upgrading database.
Try run on cli:
` php -q cli/upgrade_database.php --forcever=1.2.0`

**Comment by anarkia1976** [comment]
The database is ok, i have doing the same you have suggested after upgrade.

**Comment by anarkia1976** [comment]
Ok, i have found the problem is related to intropage, closed this ticket open on developer git. sorry. :)
