### ISSUE TITLE
Web email test can't send 1.1.37

### ISSUE THREAD

**Issue by raynewstar** [Cacti/cacti#1520]
Hi.
I updated cacti 1.1.36 to 1.1.37 version. And in the Web menu, settings > mail/reporting/dns , you can see 

Emailing Options div id="emailtest" class="emailtest">Send a Test  Email /div

And I can't send test email.

Does anyone have such a problem, after update?
How to fix it?

**Comment by raynewstar** [comment]
![cacti](https://user-images.githubusercontent.com/32352346/38348968-b5fd25d4-38c6-11e8-9564-50705cc7edad.png)

**Comment by netniV** [comment]
this is a known issue and has been resolved in the latest develop code.  However, as that is now all 1.2, I would not advise doing a straight update to that without being prepared for issues.  There may be a fix coming to address the problem which was introduced when attempting to resolve and plug some XSS security issues.

See #1516, #1514, #1513, #1504

**Comment by cigamit** [comment]
Duplicate.  We should have a patch out this weekend.  Sorry about that.  You can cherry pick the fix from three commits if you can't wait.
