### ISSUE TITLE
Force boost to be enabled when there are Remote Data Collectors

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#1521]
Our DB admin notified me that we began running out of disk space for binary logs all of the sudden a few days ago. 
At the time I had just recently done an upgrade to 1.1.37 but the timing doesn't match-up exactly. What does correlate to the increase is my attempt to enable "On-demand RRD Updating". But I quickly backed out of this for reasons mentioned in another issue. 

Our DB admin had this to say:
"I did a quick analysis of one of the binary logs; 85% of the database updates (insert, update, delete) are coming from just 5 actions:

Pct    (count)    action
25% (261263) UPDATE host SET (polling_time 85%; status 15%)
18% (190247) INSERT INTO poller_output
18% (188532) INSERT INTO poller_output_boost
14% (154829) INSERT INTO `snmpagent_cache`
10% (104986) UPDATE poller_reindex SET (assert_value 100%)
"
I am curious if you have any thoughts on this.

**Comment by netniV** [comment]
There was a bug a while back were once you enabled boost, it pretty much stayed on.  However, I was sure that had been fixed.  If you are using a remote poller though it may be that it's always on (my knowledge on the remote poller architecture is limited unfortunately).  @cigamit would be the guru on that one.

**Comment by eschoeller** [comment]
I don't have any remote pollers active yet, but that's the goal I'm working towards. Right now the feature is off:
![image](https://user-images.githubusercontent.com/12864741/38378253-4c9d7a96-38ba-11e8-8ef8-edee0c962ea3.png)
But given the activity on the poller_output_boost table I'd suspect that I'm getting hit with this bug somehow. What else should I do to track down what the problem could be? If I get some time I will go try and search for the previous bug.

**Comment by cigamit** [comment]
The poller_output and poller_output_boost and the snmpagent_cache should not be replicated IMHO.

**Comment by eschoeller** [comment]
This is activity on the main (and the only) poller, not on any remote pollers (those aren't up yet). So the fact that the main poller is writing to the poller_output_boost table with these options disabled leads me to believe something is amiss ...?

**Comment by cigamit** [comment]
I see an issue that maybe instead of just writing into the poller_output_boost table, the poller_id, that we should be writing out the hostname of who is doing the writing.  Not to say that this is the issue, but I wonder.

**Comment by eschoeller** [comment]
well I certainly have a bit of a problem. I don't think Cacti handles turning this feature on/off very well. I now have a 20GB "poller_output_boost_arch_1523245079" table which is taking forever to drop from the database. My logs are flooded with these messages:
2018/04/08 22:54:00 - CMDPHP SQL Backtrace: (/graph_json.php: 158 rrdtool_function_graph)(/lib/rrd.php: 1148 boost_graph_cache_check)(/lib/boost.php: 321 boost_process_poller_output)(/lib/boost.php: 600 db_fetch_cell)(/lib/database.php: 233 db_fetch_cell_prepared)(/lib/database.php: 280 cacti_debug_backtrace)
Still trying to figure out what has happened and how I can get back up and running.

**Comment by eschoeller** [comment]
I can also see the size of the poller_output_boost table increasing despite having the feature turned off.

**Comment by eschoeller** [comment]
I have a suspicion that if you disable the setting 'boost_rrd_update_system_enable' it still leaves the 'boost_redirect' turned on. I think this is what caused the system to continue building the poller_output_boost table but not actually doing anything with it. I will tinker with this more later today to confirm.

**Comment by cigamit** [comment]
There are two variables that control Boost. Just remove them from the settings table, and then remove all traces of the archive tables and truncate the boost table.

`TRUNCATE TABLE poller_output_boost;
DELETE FROM settings WHERE name LIKE 'boost_rrd_update%enable';`

**Comment by cigamit** [comment]
Wait a few minutes, and then see if the system one is re-enabled, if so, remove it again.  Renaming poller_boost.php for a small time would help too until this is fixed.

**Comment by cigamit** [comment]
I'm only guessing, buy you may have a poller inserting data from another system.  Maybe not though.  This is why I said something about hostname or maybe better yet IP Address of the inserter is important.

**Comment by netniV** [comment]
I am sure I submitted a fix to correct the variable issue with the boost tables a while back.

**Comment by cigamit** [comment]
I almost closed this one.

**Comment by eschoeller** [comment]
Yeah, tough to know what to do with it. I was certainly screwing around and breaking things. But somehow I was writing to boost output tables, creating boost archive tables, without having boost enabled. So none of it was ever getting flushed, it was just growing bigger and bigger.

**Comment by cigamit** [comment]
When you have multiple data collectors, boost is mandatory.  Let' me do a nice fix tonight on this.

**Comment by cigamit** [comment]
I've forced boost on when the number of remote data collectors is > 0.  So, I'm going to close this now.
