### ISSUE TITLE
Feature: Installer should only show summary of problems

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1522]
During the requirements and recommendations phase, the installer should show a concise list of the missing requirements and a count of the recommendations that are not met.  This will greatly increase the user experience of identifying problems with continuing the install rather than seeing a long list of green items and missing potential issues.  

Two buttons should be provided, one to see more detail (including the green items), the other to show recommendations that are not met.

For things like missing modules, a link to documentation that explains how to install those modules may be welcome too.

**Comment by cigamit** [comment]
Yea, wrap it in a little javascript to show and hide the details.  That way things like 'what data source profile would you like to make default' will stick out more.

**Comment by netniV** [comment]
This has now been added to the new 1.2 installer I am working on.
