### ISSUE TITLE
Graph open in new tabl

### ISSUE THREAD

**Issue by chathurag** [Cacti/cacti#1526]
Right click on graph and open in new tab does not work in 1.1.37

**Comment by netniV** [comment]
Can you be more specific about where and how you are attempting to do this?

**Comment by anarkia1976** [comment]
No problem here, please be more specific otherwise close the issue. thanks.

**Comment by cigamit** [comment]
Two screen shots too, first showing the right click menu highlighting what you clicked, and the second of the results.

**Comment by cigamit** [comment]
No feeback.
