### ISSUE TITLE
Saving a device can result in WARNINGS related to string vs. array handling

### ISSUE THREAD

**Issue by mikepiko** [Cacti/cacti#1528]
When doing an enable of disabled Devices i get php errors:

![php](https://user-images.githubusercontent.com/38277702/38603364-b7ea58c0-3d6d-11e8-8f93-b53cc7603181.jpg)

Used the latest Github release and php 7.2.4 on Debian.

Is there a Fix available ?! :) 

Thx

Mike

**Comment by cigamit** [comment]
You are likely running the develop version.  You need to run the database upgrade script and force say version 1.1.37 as the starting point.  The location column maybe missing.  I'll peak a little at this now.

**Comment by cigamit** [comment]
Never mind.  It's a bug ;)

**Comment by cigamit** [comment]
Resolved.  Thanks for reporting.
