### ISSUE TITLE
Allow Aggregate Graphs to Sum Bandwidth and Percentile COMMENTS

### ISSUE THREAD

**Issue by YangSheghui** [Cacti/cacti#1529]
![11](https://user-images.githubusercontent.com/37231882/38655474-6aa71f8c-3e47-11e8-9856-49c3a7a585a6.jpg)

When will this function be added ? Dear author, do you forget it https://github.com/Cacti/cacti/issues/900 ? ^_^

**Comment by cigamit** [comment]
This issue is resolved.  You can backport this change to 1.1.38 without issue.
