### ISSUE TITLE
[1.1.37] auto crawler returns: undefined index

### ISSUE THREAD

**Issue by paulgevers** [Cacti/cacti#1539]
The Debian CI test for 1.1.37 shows¹ one new issue with the code:
```
04/13/2018 16:09:04 - ERROR PHP NOTICE: Undefined index: type_id in file: /usr/share/cacti/site/data_input.php  on line: 469
```

https://ci.debian.net/data/autopkgtest/unstable/amd64/c/cacti/149990/log.gz

**Comment by netniV** [comment]
HI Paul, thanks as always.  

I think I see the problem.  Somehow, you have a URL that specified an id that does not exist.  The code tries to check for that but is using `isset()` and against `$data_input`.  The problem with that is that the database code will likely return false as a value if it fails to find the data input row.  Additionally, if this is a new data input, the code creates an empty array which against passes the `isset()` but fails to contain the necessary element of 'type_id';

I'll create a patch tomorrow for it which is probably something as simple as changing from `isset()` to `sizeof()`

**Comment by cigamit** [comment]
Resolved.
