### ISSUE TITLE
RRD.PHP exceeds PHP memory limit

### ISSUE THREAD

**Issue by tyit** [Cacti/cacti#1542]
Action failed
Close
Sorry, we could not process your last action.

Error:	500 Internal Server Error
Reason:	The response to the last action was unexpected.
![default](https://user-images.githubusercontent.com/31933126/38854479-2d4c449a-4253-11e8-8fc6-2b65fd87a0c2.png)

**Comment by anarkia1976** [comment]
Please post detailed information about your machine.
Have you tuned all parameters (ex: php, sql) like in the examples during wizard install?

**Comment by tyit** [comment]
CentOS Linux release 7.4.1708 (Core) 
php-5.4
httpd-2.4.6
mysql-community-server-5.6
Adjusted PHP, MySQL，My English isn't good.

**Comment by anarkia1976** [comment]
can you try to increase memory over 128M into php.ini?

**Comment by tyit** [comment]
![4](https://user-images.githubusercontent.com/31933126/38858506-839332fe-425e-11e8-8e22-af935c8fd1f5.png)



![5](https://user-images.githubusercontent.com/31933126/38858628-cec9ee20-425e-11e8-8b9d-09b0ad73ff5d.png)
![2](https://user-images.githubusercontent.com/31933126/38858635-d3c07728-425e-11e8-9050-1102ea745da6.png)
![66](https://user-images.githubusercontent.com/31933126/38858674-eee9bd34-425e-11e8-9e4f-4d098e5eebf4.png)

**Comment by tyit** [comment]
The problem is, I set the data saved for three months, every five minutes every three months, but choose a month to guide out, found the wrong page reported 500, I do not know how to solve, you will be like this, or I debug bad, can you help me point out, very grateful

**Comment by anarkia1976** [comment]
Can you explain step by step how to reproduced your settings?

**Comment by tyit** [comment]
![123](https://user-images.githubusercontent.com/31933126/38865354-0f42efa4-4270-11e8-96cf-a1b3895eb8bc.png)
![456](https://user-images.githubusercontent.com/31933126/38865362-136bfe68-4270-11e8-95d4-95bf6c10dfa8.png)
![789](https://user-images.githubusercontent.com/31933126/38865375-1cd9dc86-4270-11e8-8f10-5f2a079e3382.png)

    
The first step is to add the data interval to the data file, then add the device to select a month of data export, and there is an error 500

**Comment by anarkia1976** [comment]
What is the benefit of this configuration? The probllem is related to max number of rows. Can you try to decrease your settings?

**Comment by netniV** [comment]
I'm guessing that if you have a look in your apache error.log files, you'll find that there will be a PHP timeout error.

**Comment by tyit** [comment]
@netniV
 Yes, there was no such problem in the old version of 0. 8.8. Did I misconfigure it or not? -What's wrong? The new version has improved a lot. Can you write a new version of the user documentation? -What's wrong? Thank you very much.

**Comment by tyit** [comment]
@anarkia1976 
The advantage is that within three months, data can be derived for analysis every five minutes.

**Comment by anarkia1976** [comment]
@tyit i have used template for traffic in/out without 95th and it seem working. Can you try to switch to:
![image](https://user-images.githubusercontent.com/1744639/38914539-22979ca6-42e0-11e8-8e7a-cc1fb0bc3d25.png)

**Comment by tyit** [comment]
@anarkia1976 
Thank you very much. I'm going to reinstall it.

**Comment by tyit** [comment]
![123](https://user-images.githubusercontent.com/31933126/38915439-3d193e64-4316-11e8-9e9b-5d679be47787.png)

1 is the old version 2 is the new version of the exported data how two identical INT and out,

**Comment by tyit** [comment]
![123](https://user-images.githubusercontent.com/31933126/38915456-5227dca2-4316-11e8-9148-3767950222a6.png)
1 is the old version 2 is the new version of the exported data how two identical INT and out,

**Comment by tyit** [comment]
![123](https://user-images.githubusercontent.com/31933126/38915468-650f1ff6-4316-11e8-8b01-5c9a61ceee01.png)
1 is the old version 2 is the new version of the exported data how two identical INT and out,

**Comment by tyit** [comment]
@anarkia1976 
![456](https://user-images.githubusercontent.com/31933126/38915515-91da88ae-4316-11e8-9934-53adc959e3f0.png)

**Comment by tyit** [comment]
@anarkia1976 
![123](https://user-images.githubusercontent.com/31933126/38926539-9a5d735a-4335-11e8-8ea2-f1beed3c4628.png)
Hello, just reinstalled, what's the problem with this warning?

**Comment by tyit** [comment]
@anarkia1976 
![456](https://user-images.githubusercontent.com/31933126/38927318-f3272cb8-4337-11e8-8b21-086262af7220.png)
Just reassembled. Did you find this color doesn't match the font?

**Comment by netniV** [comment]
When you did the install, did you install all the required items?  There are some optional ones too, but I would always recommend installing them.

On the warning front, that is a known issue that is caused by the Automation setup.  By default the installer creates an example automation scan of the network but sets this to disabled to make sure that it doesn't run until you want it to.  Given that it's an example, the range used may not even work anyway.  However, when the poller kicks in, it notices that there is a network that can't be polled and lists it as a warning.

**Comment by tyit** [comment]
@netniV 
Thank you very much.

**Comment by cigamit** [comment]
Please close once you have gotten your bearings on this issue.  Thanks!
