### ISSUE TITLE
Graph Preview appends header=false too many times

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1543]
When you leave Graph Preview alone to refresh using the page timeout, it appends header=false repeatedly:

eg
```
graph_view.php?header=false&header=false&header=false
```

I'm not sure yet what the source of the issue is but I have a fix for this which is in the associated pull request.  We should probably use the `appendHeaderSuppress()` to any javascript that is actively adding the parameter.

**Comment by cigamit** [comment]
Resolved.
