### ISSUE TITLE
Color picker dropdown - bulky color selection 

### ISSUE THREAD

**Issue by bernisys** [Cacti/cacti#1545]
In short:
The color select list could be showing more than just 14 entries.

Long story:
I enter "red" for example as filter, and i get more than 14 entries with "red" in the name, but only the first 14 are displayed. So i will rarely have a real chance to select from a proper full set of search, if i don't know the correct color name in advance. This gets even more inconvenient with all the unnamed entries.

Would it be somehow easily possible to rise the number of list items?
I have already grep'ed across the code a bit, but did not find any suitable point where i can change the item count.

Suggestions:
 - Configurable color-dropdown list length
 - multi-column list-box with more entries
 - open a popup window where all colors are shown

Any chance to get that fixed in one of the suggested ways?

reference: https://forums.cacti.net/viewtopic.php?f=21&t=57581

**Comment by cigamit** [comment]
There is a setting for this under Console > Configure > Settings > Visual > Autocomplete Rows.  It's all performed via callback.  Let me know if that setting does not work.

**Comment by cigamit** [comment]
Ope, I just checked and it's not using that setting....  So, it's a bug in my opinion.

**Comment by netniV** [comment]
I would think that even if it does, the autocomplete box doesn't have an option for "More Items..." if there more?  Some systems have a process were if you scroll and hit the bottom, it automatically loads in the next page of items thus you can access more than just the limit.

**Comment by bernisys** [comment]
Indeed, this "scroll-down + load more" option would be another nice and elegant solution as well. The advantage would be that only a few items are loaded at a time, so that the environment stays responsive. Good thinking, I like it!

Would be great if this could be somehow implemented.
Unfortunately I'm personally not too much of a JS/PHP guy ...

**Comment by netniV** [comment]
Neither was I until about 6 months ago 🥇

**Comment by cigamit** [comment]
Okay, on this one.  The way that the color dropdown works is based upon the current filter.  If you clear the text, you see all the colors.  This is an autocomplete with typeahead.  We might want to consider something like jQuery-select2.  It's a nice enhancement to the jQueryUI stuff.  So, I don't think there is anything to change at this point in time.

**Comment by bernisys** [comment]
Tending to disagree ...

In the "modern" theme I still only see just 14 entries if i clear the field...
