### ISSUE TITLE
Yum update from 1.1.35 to 1.1.37 purged installed plugins

### ISSUE THREAD

**Issue by gundalba** [Cacti/cacti#1550]
OS: CentOS 7
---
Under 1.1.35, I had a list of plugins (about 10 or so) under Cacti Plugin and did install about 3-4 plugins and running them.
Saw the newer version (1.1.37) from the yum and did the update.
After the update and initial configuration from Web API, I found all the plugins were gone and had to re-install them again.
One item I noticed was that from re-installed MACTrack, all the Vendor MAC from IEEE was still there without having to re-import.

**Comment by netniV** [comment]
I suspect that what you saw was all plugins disabled, not uninstalled.  If cacti had uninstalled a plugin, it would remove it completely and that would include the plugin tables if a plugin is written properly.  Most upgrades do NOT disable plugins, however, so I am curious as to how that would have happened.  I am wondering if there was an error which was perceived to have occurred in each of the plugins.

Check through the cacti.log file on the day of the upgrade and make sure there are no errors listed.

**Comment by gundalba** [comment]
May be the plugins were just disabled as you say but from Cacti, the plugin management screen was blank and missing all the plugins that was there after initial Cacti installation.
Few of them were selected to be installed/enabled before Cacti upgrade but they were no longer listed on management screen after upgrade.
Attached is the current Plugin management screen showing only two that I have added manually.
There used to be a list of 10 or so which I did select a few to install/enable prior to upgrade.

![plugininstl_postupg](https://user-images.githubusercontent.com/17301473/38960196-16a62d36-4353-11e8-88e5-56203113f89f.png)

**Comment by gundalba** [comment]
BTW, ~cactiuser/plugins/ folder after the upgrade to 1.1.37 was pretty much empty as well.
I noticed this when I tried manual installation after the upgrade...

**Comment by netniV** [comment]
OK, that sounds far more likely that it was the package management that removed the contents of the plugin folder.  Either that, or the actual location of the cacti site has changed and thus there would be no plugins under the new folder.

Can you check by listing the directory above the site folder and see if it's a link or a proper directory?

**Comment by gundalba** [comment]
If you are referring to ~cactiuser folder location in the Cacti server, it is at /usr/share/cacti/, not a link.

# pwd
/usr/share/cacti
# latr
total 2012
drwxr-xr-x.  4 cactiuser cacti      35 Sep 20  2017 locales/
-rw-r--r--.  1 root      root    28395 Mar 25 17:49 vdef.php
-rw-r--r--.  1 root      root    90609 Mar 25 17:49 utilities.php
-rw-r--r--.  1 root      root    86019 Mar 25 17:49 user_group_admin.php
  ::
-rw-r--r--.  1 root      root    53398 Mar 25 17:49 aggregate_graphs.php
-rw-r--r--.  1 root      root     4298 Mar 25 17:49 about.php
lrwxrwxrwx.  1 root      root       20 Apr 17 15:48 cache -> /var/lib/cacti/cache/
lrwxrwxrwx.  1 root      root       18 Apr 17 15:48 cli -> /var/lib/cacti/cli/
drwxr-xr-x.  2 root      root      156 Apr 17 15:48 formats/
drwxr-xr-x.  2 root      root     4096 Apr 17 15:48 images/
drwxr-xr-x.  4 root      root       95 Apr 17 15:48 install/
drwxr-xr-x.  2 root      root     4096 Apr 17 15:48 lib/
lrwxrwxrwx.  1 root      root       15 Apr 17 15:48 log -> /var/log/cacti//
drwxr-xr-x.  2 root      root       90 Apr 17 15:48 mibs/
drwxr-xr-x.  5 apache    apache     86 Apr 17 15:48 resource/
lrwxrwxrwx.  1 root      root       18 Apr 17 15:48 rra -> /var/lib/cacti/rra/
lrwxrwxrwx.  1 root      root       22 Apr 17 15:48 scripts -> /var/lib/cacti/scripts/
drwxr-xr-x. 13 root      root     4096 Apr 17 15:48 include/
drwxr-xr-x.  5 root      root       74 Apr 17 16:51 plugins/
drwxr-xr-x.  4 cactiuser cacti     158 Apr 17 18:44 InstlLog/

**Comment by netniV** [comment]
I have a CentOS 7 box, I'll try and see if I can expect that package that Yum uses, or failing that create another VM and install a specific package version, then try the upgrade.

**Comment by cigamit** [comment]
Note that we do not maintain the epel Cacti rpm.  You should log a bug at Fedora as well so that they can respond to this directly.  Last time I tried it, it seemed not complete.

**Comment by gundalba** [comment]
If yum distro is suspected, here is what I got and where from.
Apr 17 15:48:16 Updated: cacti-1.1.37-1.el7.noarch
From repo   : epel

Many thanks for looking into this and hope this helps...

**Comment by cigamit** [comment]
I'm going to close, but feel free to continue to update us.
