### ISSUE TITLE
Poller does not set rrd_step_counter correctly if no steps taken

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1553]
#### Log
```
04/16/2018 10:30:07 - CMDPHP ERROR: A DB Exec Failed!, Error: Column 'value' cannot be null
04/16/2018 10:30:07 - DBCALL ERROR: A DB Exec Failed!, Error:1048, SQL:'REPLACE INTO settings (name, value) VALUES ('rrd_step_counter', ?)'
SQL Call
04/16/2018 10:30:07 - CMDPHP SQL Backtrace: (/poller_commands.php: 112 run_data_query)(/lib/data_query.php: 154 update_poller_cache_from_query)(/lib/utility.php: 90 update_poller_cache)(/lib/utility.php: 311 api_poller_cache_item_add)(/lib/api_poller.php: 87 api_poller_get_rrd_next_step)(/lib/api_poller.php: 149 db_execute_prepared)(/lib/database.php: 209 cacti_debug_backtrace)
```

The above log shows that the rrd_step_counter was being updated with a null value.  

I believe that this will occur within `api_poller_get_rrd_next_step()` (located in lib/api_poller.php) if there is no rrd_step_counter set in the configuration file or the database settings table.  After reading those two options, no check is done that rrd_step_counter is in fact a valid integer value.

**Comment by netniV** [comment]
Not sure, but looking at the code, to me it seems possible to have a null value if nothing was returned by $config['rrd_step_counter'] or read_config_option('rrd_step_counter')

**Comment by cigamit** [comment]
Review the latest commit and let me know if this is sufficient.

**Comment by netniV** [comment]
Seems OK.  Notice the end has been change to use the set function too.  I did a quick check of what happens when you do empty($rrd_step_counter = 0) and that apparently is considered empty too so there's no worries of it uses the else part to multiple the modulus by 0.
