### ISSUE TITLE
Aggregate

### ISSUE THREAD

**Issue by discotab311** [Cacti/cacti#1555]
Hi - 

Just upgraded to 1.1.38 from 1.1.36 and noticed an issue with my aggregate graph not totaling the first column correctly.  Any help is apprectiated!
![aggtotals](https://user-images.githubusercontent.com/6343065/39001291-f279ce7e-43c3-11e8-99c1-85fa085e7c3a.jpg)

/usr/bin/rrdtool graph - \
--imgformat=PNG \
--start='-180000' \
--end='-300' \
--pango-markup  \
--title='Perimeta - Aggregate SIP Subscribers' \
--vertical-label='Subscribers' \
--slope-mode \
--base=1000 \
--height=240 \
--width=1200 \
--tabwidth '30' \
--alt-autoscale-max \
--lower-limit='0' \
--border 1 --slope-mode \
--watermark 'TPx Communications' \
DEF:a='/data/www/cacti/rra/perimeta_-_ds1_ssc_activesubscribers_49838.rrd':'ActiveSubscribers':AVERAGE \
DEF:b='/data/www/cacti/rra/perimeta_-_ds2_ssc1_activesubscribers_49930.rrd':'ActiveSubscribers':AVERAGE \
DEF:c='/data/www/cacti/rra/perimeta_-_ds1_ssc2_activesubscribers_50128.rrd':'ActiveSubscribers':AVERAGE \
DEF:d='/data/www/cacti/rra/perimeta_-_ds3_isc1_-_a_activesubscribers_50200.rrd':'ActiveSubscribers':AVERAGE \
DEF:e='/data/www/cacti/rra/perimeta_-_ds4_isc1_activesubscribers_50259.rrd':'ActiveSubscribers':AVERAGE \
DEF:f='/data/www/cacti/rra/perimeta_-_ds2_isc1_activesubscribers_50559.rrd':'ActiveSubscribers':AVERAGE \
DEF:g='/data/www/cacti/rra/perimeta_-_ds3_isc2_activesubscribers_51520.rrd':'ActiveSubscribers':AVERAGE \
DEF:h='/data/www/cacti/rra/perimeta_-_ds3_ssc1_activesubscribers_51544.rrd':'ActiveSubscribers':AVERAGE \
DEF:i='/data/www/cacti/rra/perimeta_-_ds1_isc1_activesubscribers_51594.rrd':'ActiveSubscribers':AVERAGE \
DEF:j='/data/www/cacti/rra/perimeta_-_cht_isc1_activesubscribers_53772.rrd':'ActiveSubscribers':AVERAGE \
DEF:ba='/data/www/cacti/rra/perimeta_-_ds5_-_isc2_activesubscribers_53856.rrd':'ActiveSubscribers':AVERAGE \
CDEF:cdefef='TIME,1524150896,GT,a,a,UN,0,a,IF,IF,TIME,1524150896,GT,b,b,UN,0,b,IF,IF,TIME,1524150896,GT,c,c,UN,0,c,IF,IF,TIME,1524150896,GT,d,d,UN,0,d,IF,IF,TIME,1524150896,GT,e,e,UN,0,e,IF,IF,TIME,1524150896,GT,f,f,UN,0,f,IF,IF,TIME,1524150896,GT,g,g,UN,0,g,IF,IF,TIME,1524150896,GT,h,h,UN,0,h,IF,IF,TIME,1524150896,GT,i,i,UN,0,i,IF,IF,TIME,1524150896,GT,j,j,UN,0,j,IF,IF,TIME,1524150896,GT,ba,ba,UN,0,ba,IF,IF,+,+,+,+,+,+,+,+,+,+' \
AREA:a#004359FF:'PERIMETA - Santa Ana SSC1 -  Active Subscribers'  \
GPRINT:a:LAST:'Current\:%8.0lf'  \
GPRINT:a:AVERAGE:'Average\:%8.0lf'  \
GPRINT:a:MAX:'Maximum\:%8.0lf\n'  \
AREA:b#005D57FF:'PERIMETA - ds2 SSC1 -  Active Subscribers   ':STACK \
GPRINT:b:LAST:'Current\:%8.0lf'  \
GPRINT:b:AVERAGE:'Average\:%8.0lf'  \
GPRINT:b:MAX:'Maximum\:%8.0lf\n'  \
AREA:c#00694AFF:'PERIMETA - Santa Ana SSC2 -  Active Subscribers':STACK \
GPRINT:c:LAST:'Current\:%8.0lf'  \
GPRINT:c:AVERAGE:'Average\:%8.0lf'  \
GPRINT:c:MAX:'Maximum\:%8.0lf\n'  \
AREA:d#157419FF:'PERIMETA - ds3 ISC1 -  Active Subscribers   ':STACK \
GPRINT:d:LAST:'Current\:%8.0lf'  \
GPRINT:d:AVERAGE:'Average\:%8.0lf'  \
GPRINT:d:MAX:'Maximum\:%8.0lf\n'  \
AREA:e#008A6DFF:'PERIMETA - ds4 ISC1 -  Active Subscribers   ':STACK \
GPRINT:e:LAST:'Current\:%8.0lf'  \
GPRINT:e:AVERAGE:'Average\:%8.0lf'  \
GPRINT:e:MAX:'Maximum\:%8.0lf\n'  \
AREA:f#009F67FF:'PERIMETA - ds2 ISC1 -  Active Subscribers   ':STACK \
GPRINT:f:LAST:'Current\:%8.0lf'  \
GPRINT:f:AVERAGE:'Average\:%8.0lf'  \
GPRINT:f:MAX:'Maximum\:%8.0lf\n'  \
AREA:g#00A348FF:'PERIMETA - ds3 ISC2 -  Active Subscribers   ':STACK \
GPRINT:g:LAST:'Current\:%8.0lf'  \
GPRINT:g:AVERAGE:'Average\:%8.0lf'  \
GPRINT:g:MAX:'Maximum\:%8.0lf\n'  \
AREA:h#35962BFF:'PERIMETA - ds3 SSC1 -  Active Subscribers   ':STACK \
GPRINT:h:LAST:'Current\:%8.0lf'  \
GPRINT:h:AVERAGE:'Average\:%8.0lf'  \
GPRINT:h:MAX:'Maximum\:%8.0lf\n'  \
AREA:i#6EA100FF:'PERIMETA - Santa Ana ISC2 -  Active Subscribers':STACK \
GPRINT:i:LAST:'Current\:%8.0lf'  \
GPRINT:i:AVERAGE:'Average\:%8.0lf'  \
GPRINT:i:MAX:'Maximum\:%8.0lf\n'  \
AREA:j#00BD27FF:'PERIMETA - ds5 ISC1 -  Active Subscribers ':STACK \
GPRINT:j:LAST:'Current\:%8.0lf'  \
GPRINT:j:AVERAGE:'Average\:%8.0lf'  \
GPRINT:j:MAX:'Maximum\:%8.0lf\n'  \
AREA:ba#00BF47FF:'PERIMETA - ds5 ISC2 -  Active Subscribers ':STACK \
GPRINT:ba:LAST:'Current\:%8.0lf'  \
GPRINT:ba:AVERAGE:'Average\:%8.0lf'  \
GPRINT:ba:MAX:'Maximum\:%8.0lf\n'  \
COMMENT:' \n'  \
LINE1:cdefef#00CF00FF:'Total                                          '  \
GPRINT:cdefef:LAST:'Current\:%8.0lf'  \
GPRINT:cdefef:AVERAGE:'Average\:%8.0lf'  \
GPRINT:cdefef:MAX:'Maximum\:%8.0lf\n'

**Comment by netniV** [comment]
At least you sorted it :)
