### ISSUE TITLE
1.2 Graph View selection tabs not working

### ISSUE THREAD

**Issue by dsclassen** [Cacti/cacti#1557]
cacti f3006cc3b5c036792a88c6df002ad03cc908580b
Mac OS 10.13.4
Safari 11.1
The various graph view selection tabs in the upper right are not selectable.

<img width="370" alt="graph_view_problem" src="https://user-images.githubusercontent.com/8882563/39061886-a04284e0-447a-11e8-850d-6d42b12fe5c1.png">

**Comment by pautiina** [comment]
Confirm.
Problem with CSS.

**Comment by cigamit** [comment]
Resolved.  Hey if you guys find bugs with 1.2, can you prefix the bug report with 1.2.  I would greatly appreciate it.
