### ISSUE TITLE
cacti1.1.38 Icons are not neat

### ISSUE THREAD

**Issue by tyit** [Cacti/cacti#1558]
![123](https://user-images.githubusercontent.com/31933126/39068389-bd44a3a4-450e-11e8-9115-60afda228d30.png)
Hello, please ask why the new version 1.1.38   of the icon is not neat blurred  , and the old version  0.8.8  h  will  not  be, can you tell me why ?  Thank you

One 1.1.38      Two 0.8.8h

Environmental Science
CentOS Linux release 7.4.1708 (Core) 
Server version: Apache/2.4.6 (CentOS)
PHP 5.4.16 
mysql  Ver 14.14 Distrib 5.6.39, for Linux (x86_64) using  EditLine wrapper

**Comment by netniV** [comment]
It looks more like a font issue.  Are you using the same version of RRDTool on both versions too?

**Comment by tyit** [comment]
@netniV
1.1.38  RRdtool version 1.7.0   0.8.8h Rrdtool version 1.4.8   Rrdtool's problem?

**Comment by netniV** [comment]
Potentially, only one way to know for sure :)

**Comment by cigamit** [comment]
1000% RRDtool issue.  Back off the 1.1.38 version to RRDtool between 1.3 - 1.6.  Bet the issue is fixed.  Close if you find that his is true.

**Comment by tyit** [comment]
@cigamit @netniV 
Thanks very much

**Comment by tyit** [comment]
![123](https://user-images.githubusercontent.com/31933126/39104274-332a1dae-46e2-11e8-84aa-4d8373099f79.png)
![456](https://user-images.githubusercontent.com/31933126/39104276-37e7f0be-46e2-11e8-84ea-c18f1c2321a1.png)

Hello, I tried to change several versions of RRDtool, but the graphics are still untidy.  Can you tell me the reason?  Thank you

**Comment by cigamit** [comment]
Are you using SVG or PNG output format?  Edit the Graph Templates and see.  If using SVG, switch to PNG.

**Comment by cigamit** [comment]
Could be your font too.

**Comment by tyit** [comment]
@cigamit 
![123](https://user-images.githubusercontent.com/31933126/39160049-bb045fe6-479b-11e8-8eb9-ef957b9f2840.png)

 Installation, default, no modification, what is your environment like? I'm going to reinstall it  Thank you

**Comment by anarkia1976** [comment]
No problem in my cacti env, i think problem on yuor side:
![image](https://user-images.githubusercontent.com/1744639/39168169-1cd8b5a4-4793-11e8-8fd9-04b195454b0e.png)

**Comment by tyit** [comment]
@anarkia1976 
what is your environment like? I'm going to reinstall it . Thank you

**Comment by anarkia1976** [comment]
i have 2 env: cacti 1.1.37 and cacti 1.2.0, no problem so far.

**Comment by tyit** [comment]
@netniV @cigamit @anarkia1976 


Reinstall and solve this problem Thank you very much.


![qq 20180425124728](https://user-images.githubusercontent.com/31933126/39226741-e3c0da4a-4886-11e8-870b-4fbc997d4e54.png)
