### ISSUE TITLE
Warning that escapeshellarg() is escaping a null

### ISSUE THREAD

**Issue by jagmeetbhinder** [Cacti/cacti#1560]
I am noticing below errors in the log file after upgrade.

2018/04/21 14:53:22 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4628 cacti_debug_backtrace)
--
2018/04/21 14:53:22 - ERROR PHP ERROR: escapeshellarg(): Input  string contains NULL bytes in file: /var/www/html/lib/functions.php on  line: 3482

**Comment by cigamit** [comment]
There should be more of a backtrace.  Can you please upload the entirety of the backtrace?

**Comment by cigamit** [comment]
I have resolved, but please do upload the backtrace.

**Comment by jagmeetbhinder** [comment]
Validated...! this is fixed. Thanks for quick look into this issue.

**Comment by cigamit** [comment]
No worries.  Just going to close.  Thanks!
