### ISSUE TITLE
Downgrading 1.2.x to 1.1.38

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#1563]
I accidently(?) upgraded to 1.2.0 when it was created.
I would like to jump in to 1.1.38 stable.

So how to downgrade?
I did a git checkout origin/master.

The installer gets an error:
Error: Invalid Cacti version 1.2.0, cannot upgrade to 1.1.38.

I could not continue or ommit the error.

**Comment by cigamit** [comment]
Just replace the files and manually drop the columns create in the install/updates/1_2_0.php file.

**Comment by netniV** [comment]
Also update the version table to 1.1.38 so that you avoid the installer.  Normally, you should not do this but that is the way to go for now.

**Comment by interduo** [comment]
I am stucked at error:

```
Error
Invalid Cacti version 1.2.0, cannot upgrade to 1.1.38.

```
On installer with no button and no action.


How to debug this?

**Comment by netniV** [comment]
```sql
update version set cacti_version = '1.1.38';
```

^^^ Use that with caution though.  You should also revert any changes made to the DB by the install/upgrades/1_2_0.php file.  Otherwise, you may find that 1.1.38 starts complaining about missing values for fields etc when creating new items.

**Comment by interduo** [comment]
Aaaaa I forgot to change that. 
OK thanks for that. 

BTW Do You know when 1.2.x will be released?

**Comment by pautiina** [comment]
@netniV good work. Beautifully:)

**Comment by netniV** [comment]
@pautiina You can grab a copy of this from the Installer branch of my repo.  If you could give it a go, it'd be nice to see what your thoughts are.
