### ISSUE TITLE
1.2 Device Add Location open list button

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#1565]
![cacti_location](https://user-images.githubusercontent.com/17087236/39177464-ae5d4a1e-47af-11e8-9b5b-c785bfa8a669.png)

It's broken. I use newest Firefox.
Branch: develop.

**Comment by cigamit** [comment]
Thanks for that.  Forgot to convert that widget.

**Comment by cigamit** [comment]
Resolved.  Test again.

**Comment by interduo** [comment]
This is OK.

This lucky elephant is for You as revard.
![slonik](https://user-images.githubusercontent.com/17087236/39185323-1a3ccc0c-47c7-11e8-8427-1e69794877aa.jpg)
