### ISSUE TITLE
Warning should be raised if Spine not same release as Cacti

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1567]
Since Spine is released with Cacti, should the version of spine be checked and a warning generated if it is not the same version? This could happen from within Spine or Cacti itself?

**Comment by netniV** [comment]
I think I like the idea of merging the debug plugin.

**Comment by cigamit** [comment]
Put it in Technical support.  Serious issues might deserve a hint on the main console, in addition to some phone home on a periodic basis (automatic email).

**Comment by xmacan** [comment]
something like this?
![cacti_versions](https://user-images.githubusercontent.com/26485719/41579693-40cdd95e-7398-11e8-97d8-9c41e4eba397.png)

**Comment by netniV** [comment]
This has now been merged.
