### ISSUE TITLE
1.2.0 color selector dropdown menus are not displaying color previews

### ISSUE THREAD

**Issue by dsclassen** [Cacti/cacti#1569]
<img width="1631" alt="color_select_glitch" src="https://user-images.githubusercontent.com/8882563/39259743-20285884-486c-11e8-9b8a-e61434486722.png">

**Comment by cigamit** [comment]
Oops, that one is still there.  Likely the same fix.

**Comment by cigamit** [comment]
Resolved.  It was a pain.  jQuery is more like a dark art in some corners.
