### ISSUE TITLE
Enhancement: Allow the export of all data via GUI

### ISSUE THREAD

**Issue by tyit** [Cacti/cacti#1570]
A switch port is too many ports to export data is too cumbersome. Is there any way to export the All data of the specified All port at once ?

**Comment by netniV** [comment]
Can you give more of an explanation of what you are attempting to do and what steps you currently have to take, plus what you would prefer to do?

**Comment by tyit** [comment]
I want to export the data of all the ports of a switch. Currently, it is a port. There is no switch. It is too much trouble. Can I have a way to batch export the data of all the ports of each switch or want to The port is added in and then exported one time is convenient and quick

**Comment by tyit** [comment]
@netniV
i am sorry It's not good in English but I really want this feature

**Comment by tyit** [comment]
one  one Switchboard  data to  prot one by one export , too much   trouble   Can there   be a way to bulk export port data or their own custom port and then bulk export  

Can you see what I mean?

**Comment by netniV** [comment]
You would like to export the data at a device level not a datasource level?

**Comment by tyit** [comment]
Cacti is monitoring the data Batch export Because the device is more than one port Manual one by   one export cvs  data efficiency   too low, Is there any  way or script software like that can be achieved Batch export cvs data Can help tell me  ？ thanks you

**Comment by tyit** [comment]
@cigamit
Graphic data

**Comment by cigamit** [comment]
If you are looking for simply peak and average values, consider enabling Data Source Statistics.

**Comment by tyit** [comment]
@cigamit
I am exporting the cvs data of each port to batch export. Is there any way ?

**Comment by netniV** [comment]
At the moment, no such export exists in the core product and I don't believe any of our plugins would help either.  GExport would be the closest since it exports graphs but you need a DExport really.

**Comment by netniV** [comment]
Wait, would ReportIT not do that for you?  I believe that can export data for a given timeframe as a CSV, XML or XLS and email it to whomever you like.  Therefore, I believe what you want already exists.

**Comment by tyit** [comment]
@netniV  
Thank you very much. I 'll try.
