### ISSUE TITLE
Automation doesn't create all tholds

### ISSUE THREAD

**Issue by xmacan** [Cacti/cacti#1571]
My version 1.1.37
I have Device template with Interface errors  tholds (error in, error out, discard in, discard out):
![cacti_problem_1](https://user-images.githubusercontent.com/26485719/39296275-c13c0a8e-4940-11e8-9974-60df2996b20e.png)

Thold definition:
![cacti_problem_1 5](https://user-images.githubusercontent.com/26485719/39296328-ea0b803e-4940-11e8-9ff6-b4164c688f75.png)

Automations works well (discovery device, add, create graphs), but if I do "Apply threshold" on switch, only one thold is created (errors in, missing errors out and both discards)
![cacti_problem_3](https://user-images.githubusercontent.com/26485719/39299947-6708fd38-494a-11e8-8def-0c54fabf96d3.png)

**Comment by cigamit** [comment]
Can you please open this bug in the thold plugin issue tracker.  Thanks!
