### ISSUE TITLE
1.2 - User templates are not correctly being applied

### ISSUE THREAD

**Issue by anarkia1976** [Cacti/cacti#1574]
Hi,
i have these error when new user i created:

2018/04/27 09:42:07 - CMDPHP PHP ERROR NOTICE Backtrace: (/index.php: 25 include)(/include/auth.php: 103 include)(/auth_login.php: 253 CactiErrorHandler)(/lib/functions.php: 4604 cacti_debug_backtrace)
2018/04/27 09:42:07 - ERROR PHP NOTICE: Undefined offset: 0 in file: /usr/share/cacti/auth_login.php on line: 253
2018/04/27 09:42:07 - AUTH NOTE: User 'xxxxx' does not exist, copying template user
2018/04/27 09:42:07 - AUTH LOGIN: LDAP User 'xxxx' Authenticated
2018/04/27 09:42:07 - AUTH LDAP: Setting protocol version to 3
2018/04/27 09:41:25 - CMDPHP Input Validation Not Performed for 'user_template' Backtrace: (/settings.php: 171 get_request_var)(/lib/html_utility.php: 328 html_log_input_error)(/lib/html_validate.php: 44 cacti_debug_backtrace)

One question, How can i set corretly this check "Full name and Email from LDAP Configuration":
2018/04/27 09:42:07 - AUTH LOGIN: Email Address and Full Name fields not found code: 0

Thanks a lot

**Comment by netniV** [comment]
I will take a look for you now.

**Comment by netniV** [comment]
What the code is doing there is using the "user_template" field to make it disabled if it has a value.  The value should be the id of the user whose acting as a template.  This was a fix I requested probably as far back as 1.1.28 (before I was so active) to stop a template user being able to login.  After all, a template user should be just that, a template, not an actual user.

Are you able to find out what value was being posted into the user_template field when you go into settings?

**Comment by netniV** [comment]
The other thing is, try doing this command, as I suspect that the user_template field has been updated:
```sql
select * from settings where name = 'user_template';
```

**Comment by netniV** [comment]
Third update, I have also found that the 0.8.7 database upgrade actually sets the field to a name:
```
install/upgrades/0_8_7.php:     db_install_execute("UPDATE `settings` SET name = 'user_template' WHERE name = 'ldap_template'");
```
This may be causing the issue if you ran a full database upgrade from 0.8.7 for some reason.

**Comment by anarkia1976** [comment]
These are my setting, but i didn't work:
![image](https://user-images.githubusercontent.com/1744639/39353055-e201f17c-4a06-11e8-974f-638b275dae62.png)

**Comment by netniV** [comment]
Yeah, that user is wrong.  It should be a number of the id within the user_auth table.

```sql
select id, name from user_auth where name = 'admin';
```

But beware, if admin is your only admin user, you should not be setting them as a template as it will block you from logging in as an admin (unless you have a templated admin user 😀 )

**Comment by anarkia1976** [comment]
Admin is my only local user and it is used as template for other users. 
I have tested on my 1.1.38 box and i don't see any errors with the same configuration:
2018/04/27 11:35:51 - AUTH LOGIN: User 'xxxxx' Authenticated
2018/04/27 11:35:51 - AUTH WARN: User 'xxxxx' does not exist, copying template user
2018/04/27 11:35:51 - AUTH LOGIN: LDAP User 'xxxxx' Authenticated
2018/04/27 11:35:51 - AUTH LDAP: Setting protocol version to 3
thanks

**Comment by netniV** [comment]
Please try this latest fix.  It should work for you and if so, you can close this issue.

**Comment by anarkia1976** [comment]
I have made 2 changes:
```diff
diff --git a/auth_login.php b/auth_login.php
index d9d21a9..a0d4395 100755
--- a/auth_login.php
+++ b/auth_login.php
@@ -251,10 +251,10 @@ if (get_nfilter_request_var('action') == 'login') {
                                        user_copy($user_template['username'], $username, 0, $realm, false, $data_override);
                                } else {
                                        cacti_log('LOGIN: Email Address and Full Name fields not found ' . $ldap_cn_search_response[0] . 'code: ' . $ldap_cn_search_response['error_num'], false, 'AUTH');
-                                       user_copy($user_template['username']), $username, 0, $realm);
+                                       user_copy($user_template['username'], $username, 0, $realm);
                                }
                        } else {
-                               user_copy(user_template['username'], $username, 0, $realm);
+                               user_copy($user_template['username'], $username, 0, $realm);
                        }

                        /* requery newly created user */
```

I have this error:
![image](https://user-images.githubusercontent.com/1744639/39361769-35025fa2-4a24-11e8-9760-25d22a6ea6b9.png)

**Comment by netniV** [comment]
Yeah, that should be as expected.  If you go to your settings now, you should see that selecting the templated user will work properly.  Like I said though, make sure you have another admin account to login as an admin or it will be disabled with no admin access.

**Comment by netniV** [comment]
And thanks for those two changes, I'll add them.

**Comment by anarkia1976** [comment]
It work, but these error are yet in the logs:
2018/04/27  14:55:34 - CMDPHP PHP ERROR NOTICE Backtrace: (/index.php: 25  include)(/include/auth.php: 103 include)(/auth_login.php: 253  CactiErrorHandler)(/lib/functions.php: 4604 cacti_debug_backtrace)
2018/04/27 14:55:34 - ERROR PHP NOTICE: Undefined offset: 0 in file: /usr/share/cacti/auth_login.php  on line: 253

**Comment by netniV** [comment]
This has now been merged.
