### ISSUE TITLE
Traffic graphs on new device do not work - Confirmed issue exists

### ISSUE THREAD

**Issue by ron-slc** [Cacti/cacti#158]
In regards to CLOSED issue #135.   (Posting this new issue, as I'm not sure comments on closed issues are 'seen'??)

I confirm. This does occur on a new-installation of cacti-develop, as downloaded from GitHub 15 minutes ago.

RRDTool Error: invalid y-grid format

DEBUG OUTPUT:
RRDTool Command:
/usr/bin/rrdtool graph - \
--imgformat=PNG \
--start='-86400' \
--end='-300' \
--title='itr-colo-MDS00 - Traffic - eth0' \
--vertical-label='bits per second' \
--slope-mode \
--base=1000 \
--height=120 \
--width=500 \
--y-grid='on' \
--rigid \
--alt-autoscale-max \
--lower-limit='0' \
--y-grid='on' \
--color BACK#F3F3F3 \
--color CANVAS#FDFDFD \
--color SHADEA#CBCBCB \
--color SHADEB#999999 \
--color FONT#000000 \
--color AXIS#2C4D43 \
--color ARROW#2C4D43 \
--color FRAME#2C4D43 \
--border 1 --font TITLE:11:'Ariel' \
--font AXIS:8:'Ariel' \
--font LEGEND:8:'Courier' \
--font UNIT:8:'Ariel' \
--font WATERMARK:6:'Ariel' \
--slope-mode \
--watermark 'Copyright (C) 2004-2017 The Cacti Group' \
DEF:a='/data/cacti-develop/rra/itr-colo-mds00_traffic_in_22.rrd':'traffic_in':AVERAGE \
DEF:b='/data/cacti-develop/rra/itr-colo-mds00_traffic_in_22.rrd':'traffic_out':AVERAGE \
CDEF:cdefa='a,8,*' \
CDEF:cdefe='b,8,*' \
AREA:cdefa#00CF00FF:"Inbound "  \
GPRINT:cdefa:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefa:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdefa:MAX:'Maximum\:%8.2lf %s\n'  \
LINE1:cdefe#002A97FF:'Outbound'  \
GPRINT:cdefe:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefe:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdefe:MAX:'Maximum\:%8.2lf %s\n' 

RRDTool Says:
ERROR: invalid y-grid format

RRDtool Version 1.5.5
OS: Ubuntu 16.04 / Xenial

**Comment by cigamit** [comment]
I've finally found the root cause of this issue.  Start with a fresh install to make things easy using the latest Git.
