### ISSUE TITLE
[1.1.38 Enhancement]  External links auto refresh 

### ISSUE THREAD

**Issue by jhonnyx82** [Cacti/cacti#1593]
Hi,

It would be very useful to apply a _**refresh interval**_ for external links created in CACTI

**Comment by netniV** [comment]
Currently external links are not opened within the cacti site.  They are purely opened externally so we don't have control over them.  Additionally, there are plenty of sites with security measures to try and prevent themselves from being run in a frame and will 'pop' themselves out of one if detected. 

@cigamit may have an alternative though but I don't think this is something we can control unless it's within a frame / within the cacti site.

**Comment by cigamit** [comment]
Great idea.  Resolved.
