### ISSUE TITLE
SPINE: Poller[Main Poller] WARNING: Invalid Response, Device[3] Device

### ISSUE THREAD

**Issue by tyit** [Cacti/cacti#1595]
![cacti](https://user-images.githubusercontent.com/31933126/39502696-30d7b458-4df4-11e8-86b4-99ab4eaec4d1.png)

What can this error tell me?

**Comment by anarkia1976** [comment]
Please, close isn't an issue:
https://github.com/Cacti/spine/issues/37
thanks
