### ISSUE TITLE
Cacti 1.1.37 : a very abnormal burst value

### ISSUE THREAD

**Issue by YangShenghui2018** [Cacti/cacti#1596]
![11](https://user-images.githubusercontent.com/37231882/39505036-6c123968-4e02-11e8-8d6a-9a038aefdeba.jpg)

As shown above :
The maximum value of the interface 1/0/24 is 10G,  but a burst value of 5 minutes is much higher than the maximum value of the interface. Have you ever met ?

**Comment by pautiina** [comment]
This occurs when you clean the counters on your equipment or for some reason the previous values of the nebyl are written to the rrd file.
You need to run a spikill, which removes similar jumps from your graph.

**Comment by pautiina** [comment]
The button on the spikekill should be next to your schedule, but I do not see it on your graph. What version of Cacti do you use?
![image](https://user-images.githubusercontent.com/11805503/39509585-780302ce-4def-11e8-939f-c6ac1532ece5.png)
There are several options for cleaning by different algorithms.
![image](https://user-images.githubusercontent.com/11805503/39509700-dc5c0aea-4def-11e8-939d-0b5b40b83936.png)
You can first analyze which option is more suitable, and then use it

**Comment by YangShenghui2018** [comment]
@pautiina Thank you very much for your patience and enthusiasm. I solved it according to your prompt.
