### ISSUE TITLE
Multi-poller script sync - permissions

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#1597]
I've found that scripts synchronized to a remote poller from the main poller lose the executable bit that was set. In some cases these scripts are called directly from within Cacti, without an interpreter prepended to the data input command. So, the remote poller is unable to get any output from them, since the O/S returns a "permission denied" when the script is called directly (aka without a /bin/bash or /bin/perl). Is this by design? What's the best fix? I added a +x to the first script I had trouble with, but I suspect that the automagic sync will reset that back to -x at some point?

**Comment by netniV** [comment]
I have created a feature patch for 1.2 to include this.  Are you able to test out the change? It is not currently merged with the base development branch yet.

**Comment by eschoeller** [comment]
I'm still back at 1.1.36 right now

**Comment by netniV** [comment]
In that case, I'll close this for now.  If you do get a change to try it out in a test environment that would be great.
