### ISSUE TITLE
Aggregate Graphs can not include some classes of COMMENT

### ISSUE THREAD

**Issue by chathurag** [Cacti/cacti#1601]
@cigamit - on 1.1.38 can select comment on total
But total does not show the accurate value. Check the attached image.

<img src="https://user-images.githubusercontent.com/35136010/39465269-0c1bc500-4d40-11e8-9e56-f463ae331ebc.png">

**Comment by chathurag** [comment]
RRDtool Command:
/bin/rrdtool graph - \
--imgformat=PNG \
--start='1525696478' \
--end='1525710828' \
--pango-markup  \
--title='XXX' \
--vertical-label='bits per second' \
--slope-mode \
--base=1000 \
--height=300 \
--width=900 \
--rigid \
--alt-autoscale-max \
--lower-limit='0' \
COMMENT:"From 07/05/2018 18\:04\:38 To 07/05/2018 22\:03\:48\c" \
COMMENT:"  \n" \
--border 1 --font TITLE:10: \
--font AXIS:8: \
--font LEGEND:8: \
--font UNIT:8: \
--font WATERMARK:8: \
--slope-mode \
--watermark 'Generated by Cacti' \
DEF:a='/var/www/cacti-live/rra/device_traffic_in_27.rrd':'traffic_in':MAX \
DEF:b='/var/www/cacti-live/rra/device_traffic_in_27.rrd':'traffic_in':AVERAGE \
DEF:c='/var/www/cacti-live/rra/device_traffic_in_28.rrd':'traffic_in':MAX \
DEF:d='/var/www/cacti-live/rra/device_traffic_in_28.rrd':'traffic_in':AVERAGE \
DEF:e='/var/www/cacti-live/rra/device_traffic_in_29.rrd':'traffic_in':MAX \
DEF:f='/var/www/cacti-live/rra/device_traffic_in_29.rrd':'traffic_in':AVERAGE \
DEF:g='/var/www/cacti-live/rra/device_traffic_in_639.rrd':'traffic_in':MAX \
DEF:h='/var/www/cacti-live/rra/device_traffic_in_639.rrd':'traffic_in':AVERAGE \
DEF:i='/var/www/cacti-live/rra/device_traffic_in_667.rrd':'traffic_in':MAX \
DEF:j='/var/www/cacti-live/rra/device_traffic_in_667.rrd':'traffic_in':AVERAGE \
DEF:ba='/var/www/cacti-live/rra/device_traffic_in_668.rrd':'traffic_in':MAX \
DEF:bb='/var/www/cacti-live/rra/device_traffic_in_668.rrd':'traffic_in':AVERAGE \
DEF:bc='/var/www/cacti-live/rra/device_traffic_in_670.rrd':'traffic_in':MAX \
DEF:bd='/var/www/cacti-live/rra/device_traffic_in_670.rrd':'traffic_in':AVERAGE \
DEF:be='/var/www/cacti-live/rra/device_traffic_in_731.rrd':'traffic_in':MAX \
DEF:bf='/var/www/cacti-live/rra/device_traffic_in_731.rrd':'traffic_in':AVERAGE \
CDEF:cdefa='a,8,*' \
CDEF:cdeff='c,8,*' \
CDEF:cdefba='e,8,*' \
CDEF:cdefbf='g,8,*' \
CDEF:cdefca='i,8,*' \
CDEF:cdefzzcf='ba,8,*' \
CDEF:cdefda='bc,8,*' \
CDEF:cdefdf='be,8,*' \
CDEF:cdefeb='TIME,1525710853,GT,a,a,UN,0,a,IF,IF,TIME,1525710853,GT,c,c,UN,0,c,IF,IF,TIME,1525710853,GT,e,e,UN,0,e,IF,IF,TIME,1525710853,GT,g,g,UN,0,g,IF,IF,TIME,1525710853,GT,i,i,UN,0,i,IF,IF,TIME,1525710853,GT,ba,ba,UN,0,ba,IF,IF,TIME,1525710853,GT,bc,bc,UN,0,bc,IF,IF,TIME,1525710853,GT,be,be,UN,0,be,IF,IF,+,+,+,+,+,+,+,8,*' \
CDEF:cdefef='TIME,1525710853,GT,b,b,UN,0,b,IF,IF,TIME,1525710853,GT,d,d,UN,0,d,IF,IF,TIME,1525710853,GT,f,f,UN,0,f,IF,IF,TIME,1525710853,GT,h,h,UN,0,h,IF,IF,TIME,1525710853,GT,j,j,UN,0,j,IF,IF,TIME,1525710853,GT,bb,bb,UN,0,bb,IF,IF,TIME,1525710853,GT,bd,bd,UN,0,bd,IF,IF,TIME,1525710853,GT,bf,bf,UN,0,bf,IF,IF,+,+,+,+,+,+,+' \
AREA:cdefa#59E8177F:'device Pos2/0/0 \:  Inbound            '  \
GPRINT:cdefa:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefa:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdefa:MAX:'Maximum\:%8.2lf %s'  \
COMMENT:'Total In\:  1.79 TB\n'  \
AREA:cdeff#D462FF7F:'device Pos2/0/1 \:  Inbound            ':STACK \
GPRINT:cdeff:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdeff:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdeff:MAX:'Maximum\:%8.2lf %s'  \
COMMENT:'Total In\:  2.23 TB\n'  \
AREA:cdefba#0000FF7F:'device Pos5/0/0 \:  Inbound            ':STACK \
GPRINT:cdefba:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefba:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdefba:MAX:'Maximum\:%8.2lf %s'  \
COMMENT:'Total In\:  1.63 TB\n'  \
AREA:cdefbf#FFFF007F:'device GigabitEthernet6/0/1 \:  Inbound':STACK \
GPRINT:cdefbf:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefbf:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdefbf:MAX:'Maximum\:%8.2lf %s'  \
COMMENT:'Total In\:  433.57 KB\n'  \
AREA:cdefca#FF00007F:'device GigabitEthernet7/0/2 \:  Inbound':STACK \
GPRINT:cdefca:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefca:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdefca:MAX:'Maximum\:%8.2lf %s'  \
COMMENT:'Total In\:  2.16 TB\n'  \
AREA:cdefzzcf#00FFFF7F:'device GigabitEthernet8/0/2 \:  Inbound':STACK \
GPRINT:cdefzzcf:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefzzcf:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdefzzcf:MAX:'Maximum\:%8.2lf %s'  \
COMMENT:'Total In\:  3.61 TB\n'  \
AREA:cdefda#817C4E7F:'device GigabitEthernet7/0/3 \:  Inbound':STACK \
GPRINT:cdefda:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefda:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdefda:MAX:'Maximum\:%8.2lf %s'  \
COMMENT:'Total In\:  2.23 TB\n'  \
AREA:cdefdf#52D0177F:'device GigabitEthernet4/0/0 \:  Inbound':STACK \
GPRINT:cdefdf:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefdf:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdefdf:MAX:'Maximum\:%8.2lf %s'  \
COMMENT:'Total In\:  0.00 B\n'  \
 \
LINE1:cdefeb#0000007F:'Total Download \:  Inbound                   '  \
GPRINT:cdefeb:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefeb:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdefeb:MAX:'Maximum\:%8.2lf %s'  \
COMMENT:'Total In\:  0.00 B\n' 
RRDtool Says:
OK

**Comment by cigamit** [comment]
Okay, should have known that.  More research has to be done on this one.

**Comment by chathurag** [comment]
I will be grateful if you can fix this ASAP.

**Comment by cigamit** [comment]
I'll try to get to this this weekend, but no promises.

**Comment by chathurag** [comment]
@cigamit - In 1.1.38 still Can't mark the tick for comments. Is it only on 1.2.0 which was not yet released?

**Comment by cigamit** [comment]
This is resolved now for most of the use cases.  There is still one corner case, but it's a rare instance.  You will have to change the total method to not totalling, save, and then change the totalling type back, and then save again to resolved the issue.

**Comment by chathurag** [comment]
Is this included in 1.2.0?
1.2.0 cannot be downloaded via cacti.net yet

**Comment by netniV** [comment]
1.2 is still in development and can only be downloaded from here.  It is still being developed and should be used with caution.
