### ISSUE TITLE
PHP ERROR: Call to undefined function api_data_source_cache_crc_update()

### ISSUE THREAD

**Issue by gundalba** [Cacti/cacti#1602]
OS: CentOS 7
Cacti : 1.1.37

I am seeing this error as I am trying to save a MacTrack device....

2018/05/03 09:00:30 - SYSTEM DSSTATS STATS: Type:HOURLY, Time:0.0479
**_2018/05/03 09:01:16 - ERROR PHP ERROR: Call to undefined function api_data_source_cache_crc_update() in file: /usr/share/cacti/lib/utility.php on line: 658_**
2018/05/03 09:01:16 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4628 cacti_debug_backtrace)
2018/05/03 09:02:35 - ERROR PHP ERROR: Call to undefined function api_data_source_cache_crc_update() in file: /usr/share/cacti/lib/utility.php on line: 658
2018/05/03 09:02:35 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4628 cacti_debug_backtrace)

**Comment by netniV** [comment]
I'm trying to track down how this would be occurring but the backtrace doesn't seem to be going back far enough. It seems to be part of the `push_out_host` function.  From there I can tell that `api_device_save` calls `push_out_host` and I know that MacTrack saves using `api_device_save`

I did notice that neither api_device.php doesn't seem to include either lib/utility.php or lib/api_data_source.php so they would need to be included somewhere higher up.  I'm going to have a word with one of the guys about this before I submit a PR to bring the includes in.

**Comment by cigamit** [comment]
This should at least be resolved in the core Cacti now.  Checking the plugins shortly.

**Comment by cigamit** [comment]
Looks like cycle and mikrotik may be potentially impacted.  I would think cycle is not real, but mikrotik makes sense.

**Comment by cigamit** [comment]
Should be resolved now.
