### ISSUE TITLE
Boost next runtime occurs in the past

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#1607]
There should probably be a check somewhere that ensures the next scheduled boost runtime occurs in the future, and not in the past, as is the case in my current situation:
<pre>
mysql> select * from settings where name like 'boost_last_run_time' or name like 'boost_next_run_time' or name like 'boost_poller_status' or name like 'boost_rrd_update_interval' or name like 'stats_boost';
+---------------------------+-----------------------------------------+
| name                      | value                                   |
+---------------------------+-----------------------------------------+
| boost_last_run_time       | 2018-05-04 17:03:38                     |
| boost_next_run_time       | 2018-05-04 17:33:38                     |
| boost_poller_status       | complete - end time:2018-05-04 18:31:46 |
| boost_rrd_update_interval | 30                                      |
| stats_boost               | Time:5288.3300 RRDUpdates:28048793      |
+---------------------------+-----------------------------------------+
5 rows in set (0.00 sec)

mysql> select now();
+---------------------+
| now()               |
+---------------------+
| 2018-05-04 18:49:45 |
+---------------------+
1 row in set (0.00 sec)
</pre>

**Comment by netniV** [comment]
This may be due to a timezone issue.  Especially given the timings look right if you adjust for an hour.

**Comment by eschoeller** [comment]
Interesting idea. What would be the best way to troubleshoot that?

**Comment by eschoeller** [comment]
It's eventually worked itself out ... 
<pre>
mysql> select * from settings where name like 'boost_last_run_time' or name like 'boost_next_run_time' or name like 'boost';
+---------------------+--------------------+
| name                | value              |
+---------------------+--------------------+
| boost_last_run_time | 2018-05-06 0:05:30 |
| boost_next_run_time | 2018-05-06 0:35:30 |
+---------------------+--------------------+
2 rows in set (0.00 sec)

mysql> select now();
+---------------------+
| now()               |
+---------------------+
| 2018-05-06 00:14:20 |
+---------------------+
1 row in set (0.00 sec)
</pre>

**Comment by cigamit** [comment]
Are you running any remote data collectors?

**Comment by cigamit** [comment]
What is your poller interval and grep "SYSTEM STATS:" from the Cacti log and post some output here as well.

**Comment by eschoeller** [comment]
Yes I am running remote collectors. Poller interval is 1 minute. I can get you some more info later tomorrow.

**Comment by eschoeller** [comment]
Here are some stats from the main poller
<pre>
2018/05/10 10:52:21 - SYSTEM STATS: Time:18.9623 Method:spine Processes:2 Threads:32 Hosts:7 HostsPerProcess:4 DataSources:1448 RRDsProcessed:0
2018/05/10 10:53:22 - SYSTEM STATS: Time:20.7111 Method:spine Processes:2 Threads:32 Hosts:7 HostsPerProcess:4 DataSources:1429 RRDsProcessed:0
2018/05/10 10:54:22 - SYSTEM STATS: Time:20.6040 Method:spine Processes:2 Threads:32 Hosts:7 HostsPerProcess:4 DataSources:1447 RRDsProcessed:0
2018/05/10 10:55:19 - SYSTEM STATS: Time:17.8155 Method:spine Processes:2 Threads:32 Hosts:7 HostsPerProcess:4 DataSources:1466 RRDsProcessed:0
2018/05/10 10:56:18 - SYSTEM STATS: Time:16.5852 Method:spine Processes:2 Threads:32 Hosts:7 HostsPerProcess:4 DataSources:1455 RRDsProcessed:0
2018/05/10 10:57:21 - SYSTEM STATS: Time:20.0301 Method:spine Processes:2 Threads:32 Hosts:7 HostsPerProcess:4 DataSources:1448 RRDsProcessed:0
2018/05/10 10:58:16 - SYSTEM STATS: Time:14.5425 Method:spine Processes:2 Threads:32 Hosts:7 HostsPerProcess:4 DataSources:1429 RRDsProcessed:0
2018/05/10 10:59:20 - SYSTEM STATS: Time:17.8558 Method:spine Processes:2 Threads:32 Hosts:7 HostsPerProcess:4 DataSources:1447 RRDsProcessed:0
2018/05/10 11:00:18 - SYSTEM STATS: Time:16.8191 Method:spine Processes:2 Threads:32 Hosts:7 HostsPerProcess:4 DataSources:1466 RRDsProcessed:0
2018/05/10 11:01:16 - SYSTEM STATS: Time:14.2796 Method:spine Processes:2 Threads:32 Hosts:7 HostsPerProcess:4 DataSources:1455 RRDsProcessed:0
2018/05/10 11:02:20 - SYSTEM STATS: Time:18.6336 Method:spine Processes:2 Threads:32 Hosts:7 HostsPerProcess:4 DataSources:1448 RRDsProcessed:0
2018/05/10 11:03:14 - SYSTEM STATS: Time:12.4615 Method:spine Processes:2 Threads:32 Hosts:7 HostsPerProcess:4 DataSources:1429 RRDsProcessed:0
2018/05/10 11:04:22 - SYSTEM STATS: Time:20.4424 Method:spine Processes:2 Threads:32 Hosts:7 HostsPerProcess:4 DataSources:1447 RRDsProcessed:0
2018/05/10 11:05:17 - SYSTEM STATS: Time:15.7928 Method:spine Processes:2 Threads:32 Hosts:7 HostsPerProcess:4 DataSources:1466 RRDsProcessed:0
2018/05/10 11:06:19 - SYSTEM STATS: Time:17.8256 Method:spine Processes:2 Threads:32 Hosts:7 HostsPerProcess:4 DataSources:1455 RRDsProcessed:0
2018/05/10 11:07:27 - SYSTEM STATS: Time:25.9973 Method:spine Processes:2 Threads:32 Hosts:7 HostsPerProcess:4 DataSources:1448 RRDsProcessed:0
</pre>

And some boost stats. I had a "hiccup" last night with boost. I don't really have any other logs to see what could have caused that.

<pre>
2018/05/09 18:09:52 - SYSTEM BOOST STATS: Time:32.0200 RRDUpdates:463382
2018/05/09 18:24:49 - SYSTEM BOOST STATS: Time:31.4400 RRDUpdates:466153
2018/05/09 18:41:59 - SYSTEM BOOST STATS: Time:35.3600 RRDUpdates:532954
2018/05/09 18:55:51 - SYSTEM BOOST STATS: Time:30.6300 RRDUpdates:434397
2018/05/09 21:19:29 - SYSTEM BOOST STATS: Time:309.5800 RRDUpdates:4302293
2018/05/09 21:28:50 - SYSTEM BOOST STATS: Time:30.5500 RRDUpdates:435146
2018/05/09 21:42:55 - SYSTEM BOOST STATS: Time:30.3500 RRDUpdates:439998
2018/05/09 21:58:59 - SYSTEM BOOST STATS: Time:33.7400 RRDUpdates:496756
2018/05/09 22:12:49 - SYSTEM BOOST STATS: Time:31.7200 RRDUpdates:430221
2018/05/09 22:28:53 - SYSTEM BOOST STATS: Time:33.4600 RRDUpdates:499428
2018/05/09 22:41:55 - SYSTEM BOOST STATS: Time:28.6300 RRDUpdates:408943
2018/05/09 22:56:53 - SYSTEM BOOST STATS: Time:32.3500 RRDUpdates:464689
</pre>

Do you want any data from the remote collectors?

**Comment by cigamit** [comment]
I've done a fix for this.  Weird things can happen when you do force runs.  I think I've corrected that now.
