### ISSUE TITLE
Remote pollers update 'stats_poller' on main poller

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#1609]
I have 3 remote pollers running. As the polling cycles for each poller complete, I can see the 'stats_poller' value in the settings table update from each of the poller runs. This is skewing the poller runtime graph on the main poller, essentially only showing the runtime of the longest running remote poller. The stats_poller value is not being updated on the remote pollers, making it not possible to graph those poller runtimes locally. 

On the main poller:
<pre>
mysql> select value from settings where name='stats_poller';
+---------------------------------------------------------------------------------------------------------------+
| value                                                                                                         |
+---------------------------------------------------------------------------------------------------------------+
| Time:19.0785 Method:spine Processes:2 Threads:32 Hosts:28 HostsPerProcess:14 DataSources:2859 RRDsProcessed:0 |
+---------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> select value from settings where name='stats_poller';
+-----------------------------------------------------------------------------------------------------------------+
| value                                                                                                           |
+-----------------------------------------------------------------------------------------------------------------+
| Time:17.2889 Method:spine Processes:2 Threads:32 Hosts:141 HostsPerProcess:71 DataSources:21559 RRDsProcessed:0 |
+-----------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> select value from settings where name='stats_poller';
+---------------------------------------------------------------------------------------------------------------+
| value                                                                                                         |
+---------------------------------------------------------------------------------------------------------------+
| Time:38.2778 Method:spine Processes:2 Threads:32 Hosts:77 HostsPerProcess:39 DataSources:4788 RRDsProcessed:0 |
+---------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> select value from settings where name='stats_poller';
+---------------------------------------------------------------------------------------------------------------+
| value                                                                                                         |
+---------------------------------------------------------------------------------------------------------------+
| Time:42.2699 Method:spine Processes:2 Threads:32 Hosts:76 HostsPerProcess:38 DataSources:5052 RRDsProcessed:0 |
+---------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
</pre>

These queries are run periodically throughout the polling cycle. You can see the Hosts/HostsPerProcess/DataSources change, indicating the data is coming from different sources.

Then on a remote poller:
<pre>
MariaDB [cacti]> select value from settings where name='stats_poller';
+------------------------------------------------------------------------------------------------------------+
| value                                                                                                      |
+------------------------------------------------------------------------------------------------------------+
| Time:0.0156 Method:cmd.php Processes:1 Threads:N/A Hosts:0 HostsPerProcess:0 DataSources:0 RRDsProcessed:0 |
+------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
</pre>

Pretty clearly not being updated. If there's an intentional reason for this, my apologies, I'll have to tweak with ss_poller.php to fetch data from somewhere else.

**Comment by netniV** [comment]
I think the correct fix for this would be to supply the local_database_id to the stats query when it is being run on a remote poller. That makes it use the local database instead of the remote (main) one.

**Comment by cigamit** [comment]
Resolved.
