### ISSUE TITLE
Default value y-axis=on doesn't work with rrdtool 1.6

### ISSUE THREAD

**Issue by simnv** [Cacti/cacti#161]
```rrdtool -v
RRDtool 1.6.0  Copyright by Tobias Oetiker <tobi@oetiker.ch>
               Compiled Jun 30 2016 18:30:05
```

This doesn't work:
$ /bin/rrdtool graph - --imgformat=PNG --start='-180000' --end='-300' --title='127.0.0.1 cacti - Traffic - enp2s0' --vertical-label='bits per second' --slope-mode --base=1000 --height=120 --width=500 --rigid --alt-autoscale-max --lower-limit='0' **--y-grid='on'** --color BACK#F3F3F3 --color CANVAS#FDFDFD --color SHADEA#CBCBCB --color SHADEB#999999 --color FONT#000000 --color AXIS#2C4D43 --color ARROW#2C4D43 --color FRAME#2C4D43 --border 1 --font TITLE:11:'Ariel' --font AXIS:8:'Ariel' --font LEGEND:8:'Courier' --font UNIT:8:'Ariel' --font WATERMARK:6:'Ariel' --slope-mode --watermark 'Copyright (C) 2004-2016 The Cacti Group' DEF:a='rra/1/29.rrd':'traffic_in':AVERAGE DEF:b='rra/1/29.rrd':'traffic_out':AVERAGE CDEF:cdefa='a,8,*' CDEF:cdefe='b,8,*' AREA:cdefa#00CF00FF:"Inbound "  GPRINT:cdefa:LAST:'Current\:%8.2lf %s'  GPRINT:cdefa:AVERAGE:'Average\:%8.2lf %s'  GPRINT:cdefa:MAX:'Maximum\:%8.2lf %s\n'  LINE1:cdefe#002A97FF:'Outbound'  GPRINT:cdefe:LAST:'Current\:%8.2lf %s'  GPRINT:cdefe:AVERAGE:'Average\:%8.2lf %s'  GPRINT:cdefe:MAX:'Maximum\:%8.2lf %s\n' >/dev/null
**ERROR: invalid y-grid format**

This works:
$ /bin/rrdtool graph - --imgformat=PNG --start='-180000' --end='-300' --title='127.0.0.1 cacti - Traffic - enp2s0' --vertical-label='bits per second' --slope-mode --base=1000 --height=120 --width=500 --rigid --alt-autoscale-max --lower-limit='0' --color BACK#F3F3F3 --color CANVAS#FDFDFD --color SHADEA#CBCBCB --color SHADEB#999999 --color FONT#000000 --color AXIS#2C4D43 --color ARROW#2C4D43 --color FRAME#2C4D43 --border 1 --font TITLE:11:'Ariel' --font AXIS:8:'Ariel' --font LEGEND:8:'Courier' --font UNIT:8:'Ariel' --font WATERMARK:6:'Ariel' --slope-mode --watermark 'Copyright (C) 2004-2016 The Cacti Group' DEF:a='rra/1/29.rrd':'traffic_in':AVERAGE DEF:b='rra/1/29.rrd':'traffic_out':AVERAGE CDEF:cdefa='a,8,*' CDEF:cdefe='b,8,*' AREA:cdefa#00CF00FF:"Inbound "  GPRINT:cdefa:LAST:'Current\:%8.2lf %s'  GPRINT:cdefa:AVERAGE:'Average\:%8.2lf %s'  GPRINT:cdefa:MAX:'Maximum\:%8.2lf %s\n'  LINE1:cdefe#002A97FF:'Outbound'  GPRINT:cdefe:LAST:'Current\:%8.2lf %s'  GPRINT:cdefe:AVERAGE:'Average\:%8.2lf %s'  GPRINT:cdefe:MAX:'Maximum\:%8.2lf %s\n' >/dev/null

Had to change all unit_value to '' in cacti graph templates:
`UPDATE graph_templates_graph SET unit_value = '' WHERE unit_value='on';`

**Comment by cigamit** [comment]
Correct.  I will be adding to the installer, then when rerunning the installer, these issues will be fixed.

**Comment by cigamit** [comment]
Resolved, thanks for caching this.  For testers, you can now 'fully' run:

php -q upgrade_database.php --forcever=0.8.8h

To resolve this problem.
