### ISSUE TITLE
Cannot view Realtime Graph

### ISSUE THREAD

**Issue by toannguyen0908** [Cacti/cacti#1612]
Hi,

I have installed cacti version 1.1.19 via rpm installing. I added devices but when I click Real-time, it returns results "Permission Denied" as below picture:
![image](https://user-images.githubusercontent.com/39041939/39684780-9eba9a92-51e8-11e8-982e-6cd24561c50a.png)
I changed the cache  directory  permission in /var/lib/cacti/ to 777 but It isn't solve.
Please help me check this issue.

Thanks & Best Regards!

**Comment by toannguyen0908** [comment]
Hi pautiina,
Thank for your guide. I viewed real-time graphs.
Thanks!

**Comment by pautiina** [comment]
Close Issue please.
