### ISSUE TITLE
Cacti Thold sound

### ISSUE THREAD

**Issue by Iamahao** [Cacti/cacti#1613]
Hello everybody
I am a newbie using cacti;
I use monitor to sound alarm;
but now 
I want to trigger a threshold use sound alarm.
How to let him do it
Thanks^^

**Comment by pautiina** [comment]
I think it should be placed in the plugin [THOLD](https://github.com/Cacti/plugin_thold)

**Comment by netniV** [comment]
Only monitor provides the sound notification of an alert.  But if you have a feature request you should open it on the THold plugin section as @pautiina correctly points out.

**Comment by Iamahao** [comment]
ok!! Thanks
