### ISSUE TITLE
[1.2.0] - Graph management not display graph names

### ISSUE THREAD

**Issue by pautiina** [Cacti/cacti#1614]
![image](https://user-images.githubusercontent.com/11805503/39689053-da6e3428-51dd-11e8-8b9f-f28fd4201a4d.png)
![image](https://user-images.githubusercontent.com/11805503/39689097-130239ba-51de-11e8-9a12-7040b2472c50.png)

**Comment by pautiina** [comment]
The problem is that the value title_cache is incorrectly substituted:
```
2018/05/07 10:19:46 - DBCALL DEVEL: SQL Exec: "UPDATE graph_templates_graph SET title_cache = ? WHERE local_graph_id = ?"
2018/05/07 10:19:46 - DBCALL DEVEL: SQL Row: "SELECT gl.host_id, gl.snmp_query_id, gl.snmp_index, gtg.local_graph_id, gtg.t_title, gtg.title FROM graph_templates_graph AS gtg INNER JOIN graph_local AS gl ON gtg.local_graph_id = gl.id WHERE gl.id = ?"
2018/05/07 10:19:46 - DBCALL DEVEL: SQL Exec: "INSERT INTO graph_templates_graph (`id`, `local_graph_template_graph_id`, `graph_template_id`, `image_format_id`, `title`, `height`, `width`, `upper_limit`, `lower_limit`, `vertical_label`, `slope_mode`, `auto_scale`, `auto_scale_opts`, `auto_scale_log`, `scale_log_units`, `auto_scale_rigid`, `auto_padding`, `base_value`, `unit_value`, `unit_exponent_value`, `alt_y_grid`, `right_axis`, `right_axis_label`, `right_axis_format`, `no_gridfit`, `unit_length`, `tab_width`, `dynamic_labels`, `force_rules_legend`, `legend_position`, `legend_direction`, `right_axis_formatter`, `left_axis_formatter`, `local_graph_id`) VALUES (7510, 2, 2, 1, '|host_description| - Traffic - |query_ifName| -- |query_ifAlias| -1', 150, 550, '100', '0', 'bits per second', 'on', 'on', 2, '', '', 'on', 'on', 1000, '', '', '', '', '', 0, '', '', '', '', '', '0', '0', '0', '0', 7402) ON DUPLICATE KEY UPDATE `local_graph_template_graph_id`=VALUES(`local_graph_template_graph_id`), `graph_template_id`=VALUES(`graph_template_id`), `image_format_id`=VALUES(`image_format_id`), `title`=VALUES(`title`), `height`=VALUES(`height`), `width`=VALUES(`width`), `upper_limit`=VALUES(`upper_limit`), `lower_limit`=VALUES(`lower_limit`), `vertical_label`=VALUES(`vertical_label`), `slope_mode`=VALUES(`slope_mode`), `auto_scale`=VALUES(`auto_scale`), `auto_scale_opts`=VALUES(`auto_scale_opts`), `auto_scale_log`=VALUES(`auto_scale_log`), `scale_log_units`=VALUES(`scale_log_units`), `auto_scale_rigid`=VALUES(`auto_scale_rigid`), `auto_padding`=VALUES(`auto_padding`), `base_value`=VALUES(`base_value`), `unit_value`=VALUES(`unit_value`), `unit_exponent_value`=VALUES(`unit_exponent_value`), `alt_y_grid`=VALUES(`alt_y_grid`), `right_axis`=VALUES(`right_axis`), `right_axis_label`=VALUES(`right_axis_label`), `right_axis_format`=VALUES(`right_axis_format`), `no_gridfit`=VALUES(`no_gridfit`), `unit_length`=VALUES(`unit_length`), `tab_width`=VALUES(`tab_width`), `dynamic_labels`=VALUES(`dynamic_labels`), `force_rules_legend`=VALUES(`force_rules_legend`), `legend_position`=VALUES(`legend_position`), `legend_direction`=VALUES(`legend_direction`), `right_axis_formatter`=VALUES(`right_axis_formatter`), `left_axis_formatter`=VALUES(`left_axis_formatter`), `local_graph_id`=VALUES(`local_graph_id`)"
```
```

mysql> SELECT * FROM `graph_templates_graph` WHERE `id` = 7510;
+------+-------------------------------+----------------+-------------------+-------------------+-----------------+---------+---------------------------------------------------------------------+---------------------------------------------------------------------+----------+--------+---------+-------+---------------+-------------+---------------+-------------+------------------+-----------------+--------------+------------+--------------+------------+-------------------+-----------------+------------------+----------------+-------------------+-----------------+--------------------+------------------+----------------+--------------+--------------+------------+------------+----------+--------------+------------+-----------------------+---------------------+--------------+------------+--------------+------------+--------------------+------------------+---------------------+-------------------+------------------------+----------------------+-----------------------+---------------------+--------------+------------+---------------+-------------+-------------+-----------+------------------+----------------+----------------------+--------------------+-------------------+-----------------+--------------------+------------------+
| id   | local_graph_template_graph_id | local_graph_id | graph_template_id | t_image_format_id | image_format_id | t_title | title                                                               | title_cache                                                         | t_height | height | t_width | width | t_upper_limit | upper_limit | t_lower_limit | lower_limit | t_vertical_label | vertical_label  | t_slope_mode | slope_mode | t_auto_scale | auto_scale | t_auto_scale_opts | auto_scale_opts | t_auto_scale_log | auto_scale_log | t_scale_log_units | scale_log_units | t_auto_scale_rigid | auto_scale_rigid | t_auto_padding | auto_padding | t_base_value | base_value | t_grouping | grouping | t_unit_value | unit_value | t_unit_exponent_value | unit_exponent_value | t_alt_y_grid | alt_y_grid | t_right_axis | right_axis | t_right_axis_label | right_axis_label | t_right_axis_format | right_axis_format | t_right_axis_formatter | right_axis_formatter | t_left_axis_formatter | left_axis_formatter | t_no_gridfit | no_gridfit | t_unit_length | unit_length | t_tab_width | tab_width | t_dynamic_labels | dynamic_labels | t_force_rules_legend | force_rules_legend | t_legend_position | legend_position | t_legend_direction | legend_direction |
+------+-------------------------------+----------------+-------------------+-------------------+-----------------+---------+---------------------------------------------------------------------+---------------------------------------------------------------------+----------+--------+---------+-------+---------------+-------------+---------------+-------------+------------------+-----------------+--------------+------------+--------------+------------+-------------------+-----------------+------------------+----------------+-------------------+-----------------+--------------------+------------------+----------------+--------------+--------------+------------+------------+----------+--------------+------------+-----------------------+---------------------+--------------+------------+--------------+------------+--------------------+------------------+---------------------+-------------------+------------------------+----------------------+-----------------------+---------------------+--------------+------------+---------------+-------------+-------------+-----------+------------------+----------------+----------------------+--------------------+-------------------+-----------------+--------------------+------------------+
| 7510 |                             2 |           7402 |                 2 | 0                 |               1 | 0       | |host_description| - Traffic - |query_ifName| -- |query_ifAlias| -1 | |host_description| - Traffic - |query_ifName| -- |query_ifAlias| -1 | 0        |    150 | 0       |   550 | 0             | 100         | 0             | 0           | 0                | bits per second | 0            | on         | 0            | on         | 0                 |               2 | 0                |                | 0                 |                 | 0                  | on               | 0              | on           | 0            |       1000 | 0          |          | 0            |            | 0                     |                     |              |            |              |            |                    |                  |                     |                 0 |                        | 0                    |                       | 0                   |              |            |               |             |             |           |                  |                |                      |                    |                   | 0               |                    | 0                |
+------+-------------------------------+----------------+-------------------+-------------------+-----------------+---------+---------------------------------------------------------------------+---------------------------------------------------------------------+----------+--------+---------+-------+---------------+-------------+---------------+-------------+------------------+-----------------+--------------+------------+--------------+------------+-------------------+-----------------+------------------+----------------+-------------------+-----------------+--------------------+------------------+----------------+--------------+--------------+------------+------------+----------+--------------+------------+-----------------------+---------------------+--------------+------------+--------------+------------+--------------------+------------------+---------------------+-------------------+------------------------+----------------------+-----------------------+---------------------+--------------+------------+---------------+-------------+-------------+-----------+------------------+----------------+----------------------+--------------------+-------------------+-----------------+--------------------+------------------+
1 row in set (0.00 sec)


```

**Comment by pautiina** [comment]
@cigamit It just happened after everything you said

**Comment by cigamit** [comment]
Check your host_snmp_cache and verify the ifAlias is actually there for these interfaces.  Seems like something may have changed for sure.  Verbose query from the device page too.

**Comment by pautiina** [comment]
**Data Sources** is displayed normally:
![image](https://user-images.githubusercontent.com/11805503/39854903-722e003a-5432-11e8-9295-f9b87cbaeead.png)

host_snmp_cache have valide data for this device:
```
mysql> SELECT * FROM `host_snmp_cache` WHERE `host_id` = 399 and snmp_index = 518 ;
+---------+---------------+--------------+-------------------+------------+------------------------------+---------+---------------------+
| host_id | snmp_query_id | field_name   | field_value       | snmp_index | oid                          | present | last_updated        |
+---------+---------------+--------------+-------------------+------------+------------------------------+---------+---------------------+
|     399 |             1 | ifAlias      |                   | 518        | .1.3.6.1.2.1.31.1.1.1.18.518 |       1 | 2018-05-08 15:20:26 |
|     399 |             1 | ifDescr      | ge-0/0/17         | 518        | .1.3.6.1.2.1.2.2.1.2.518     |       1 | 2018-05-08 15:20:26 |
|     399 |             1 | ifHighSpeed  | 0                 | 518        | .1.3.6.1.2.1.31.1.1.1.15.518 |       1 | 2018-05-08 15:20:26 |
|     399 |             1 | ifHwAddr     | 00:1F:12:3A:D1:14 | 518        | .1.3.6.1.2.1.2.2.1.6.518     |       1 | 2018-05-08 15:20:26 |
|     399 |             1 | ifIndex      | 518               | 518        | .1.3.6.1.2.1.2.2.1.1.518     |       1 | 2018-05-08 15:20:26 |
|     399 |             1 | ifName       | ge-0/0/17         | 518        | .1.3.6.1.2.1.31.1.1.1.1.518  |       1 | 2018-05-08 15:20:26 |
|     399 |             1 | ifOperStatus | Down              | 518        | .1.3.6.1.2.1.2.2.1.8.518     |       1 | 2018-05-08 15:20:26 |
|     399 |             1 | ifSpeed      | 0                 | 518        | .1.3.6.1.2.1.2.2.1.5.518     |       1 | 2018-05-08 15:20:26 |
|     399 |             1 | ifType       | ethernetCsmacd(6  | 518        | .1.3.6.1.2.1.2.2.1.3.518     |       1 | 2018-05-08 15:20:26 |
+---------+---------------+--------------+-------------------+------------+------------------------------+---------+---------------------+
9 rows in set (0.01 sec)

```
I tried this for another device, the situation is the same.

maybe you misunderstood me. SNMP polls everything correctly and draws correct values on the graph:
 **| host_description |** and **| query_ifName |** and **| query_ifAlias |**.
The problem is that in the graph manager's tab all graphs titles are displayed identically. And so I need to go into the settings of each graph to see they belong to which interface.
![image](https://user-images.githubusercontent.com/11805503/39855845-35f49986-5436-11e8-91cc-6c8199042b79.png)
![image](https://user-images.githubusercontent.com/11805503/39855905-6c7d9fd4-5436-11e8-8e1e-8af3228d20cf.png)

**Comment by netniV** [comment]
If you notice the cache didn’t have a value for ifAlias so it is this part that has gone wrong.

**Comment by pautiina** [comment]
@netniV I tried to leave only | host_description | - the same effect

**Comment by pautiina** [comment]
I do not understand anything, I have a second host with Cacti 1.2.0, I also update it from the develop branch and everything is fine

**Comment by netniV** [comment]
Soirry, I was using CodeHub on my iPad to view things as I’m sat on a plane waiting to takeoff.  I switched to a browser so I could zoom in and I see the problem now.  It’s not even running the variable replacement logic is it?  

The reason I was questioning it, was the difference between the interface you were highlghting and the index you used to get the data out didn’t seem to match plus the ifAlias was blank.  @cigamit will likely correct this as I’m working abroad for the next two days.

**Comment by pautiina** [comment]
This problem affects all the graphs templates, not just the interfaces

**Comment by pautiina** [comment]
I'm worried that there is no such problem on the second server

**Comment by netniV** [comment]
I appreciate now that it affects everything, but the examples you gave didn't line up (at least to me).

**Comment by tigerdjohnson** [comment]
I ran into this issue as well.  Turns out t_title got set to 0 for all the graph IDs showing this way. get_graph_title in lib/functions.php requires t_title be empty before substituting variables for the title cache.  So, clearing it will let you reapply suggested names... 

`UPDATE cacti.graph_templates_graph SET t_title = '' WHERE t_title = '0' AND graph_template_id = '140'`

I'm not sure what I did to set t_title=0, but I'm sort of stumbling my way through the code to figure it out.

**Comment by tigerdjohnson** [comment]
I forgot to mention I'm running 1.1.38 right now, not 1.2.x. The problem first appeared on 1.1.37 and persisted through 1.1.38 until I cleared t_title.

**Comment by pautiina** [comment]
@eschoeller it's not like your situation

**Comment by pautiina** [comment]
Today I removed some of the graphs from the device and recreated them on a new one. And now everything is displayed normally. But the old graphs with the use of names of the situation has not changed.
I do not understand anything.
![image](https://user-images.githubusercontent.com/11805503/39982001-98c229de-575b-11e8-86f2-7f10eee3ede8.png)

**Comment by netniV** [comment]
I've done a difference between 1.1.37 and 1.1.38 and I can not see anything that would explicitly cause this issue.  Can you select a good and bad graph to show the fields in MySQL including t_cache

**Comment by cigamit** [comment]
Okay, so, look up the host_id in graph_local, then check to see if that device still exists in the host table.  Let me know that it's still there.  Also, provide a screen shot of the suggested names in the Data Query for this specific Graph Template.

**Comment by cigamit** [comment]
Okay, actually @eschoeller is likely correct.  If you review this graph:

![image](https://user-images.githubusercontent.com/957322/40054614-193fe52e-580b-11e8-8f74-f4a0c4dcd7ed.png)

You will see that the Graph Title is editable, which means that the checkbox to the left of the specific Graph Template was either perceived to be checkable due to a database issue as @eschoeller indicated, or it was checked inadvertently without knowledge of it's implications, this was then propagated to the graphs.  Now, if you review the following graph, you will see that the Graph Title is not editable, which is correct.

![graphedit](https://user-images.githubusercontent.com/957322/40054752-913af03c-580b-11e8-850d-9715a0ddb4f4.png)

In my opinion, in any event, it is a bug, but now we know where to search to find it.  Unfortunately, I'm going to be pretty busy over the next weeks.  Maybe @netniV will have the time to track things down.  First step is to audit your Graph Template and verify that the Graph Title does not have the checkbox checked (just resave it).  Second would be to follow @eschoeller advice, and then Re-apply the suggested names once more.

Keep us posted and we will address this issue as soon as possible.

**Comment by pautiina** [comment]
I removed the check box in the Graph  template
![image](https://user-images.githubusercontent.com/11805503/40064540-687993a8-5868-11e8-8da8-3189bcbc5b03.png)
Reapply suggested names for all graph and nov have 
I  reapply suggested names for all Graphs and now have 1086 of 2546 incorrectly signed schedules:
![image](https://user-images.githubusercontent.com/11805503/40065558-c1210aca-586a-11e8-90dc-6ff22e3bda0a.png)
The remaining graphics used the proposed names normally.

**Comment by netniV** [comment]
I think you may also need to use the Sync Graph option.  Select the graph template in question on Management -> Graph Templates, then at the bottom right there should be Sync and it will lead to a screen that explains this.

**Comment by netniV** [comment]
If you have sync'd try now reapplying the suggesting names.

**Comment by pautiina** [comment]
Unfortunately, I tried all the options. And I did a reindex device, and synchronized the template, and applied the suggested graph names. All tried in different versions - for these objects names do not apply. Those. half of the devices are now normal, and the second half does not display the normal name of the graphs

**Comment by pautiina** [comment]
Hello. 
And so, the method of rollback versions I've found that it stopped working on the release/1.1.37.
Now I'm looking for a commit on which I have stopped working.

**Comment by pautiina** [comment]
b1894a6638396b9bb2cb739d49ba70dd5a406fac - this is the last commit in which there is no problem

**Comment by netniV** [comment]
I am not sure why it would be putting a zero in there, that seems wrong to me.  However, if we change the check to be empty() that should work since both 0 and '' are classed as being empty if I remember rightly.

**Comment by pautiina** [comment]
It's all the same device.
Now I left the line like this:
`if (strstr($graph['title'], '|') && !empty($graph['host_id']) && $graph['t_title'] == '0') {`
```
mysql> SELECT gl.host_id, gl.snmp_query_id, gl.snmp_index, gtg.local_graph_id, gtg.t_title, gtg.title FROM graph_templates_graph AS gtg INNER JOIN graph_local AS gl ON gtg.local_graph_id = gl.id WHERE gl.id = 9630;
+---------+---------------+------------+----------------+---------+-----------------------------------------------+
| host_id | snmp_query_id | snmp_index | local_graph_id | t_title | title                                         |
+---------+---------------+------------+----------------+---------+-----------------------------------------------+
|     399 |             1 | 509        |           9630 |         | |host_description| - Traffic - |query_ifName| |
+---------+---------------+------------+----------------+---------+-----------------------------------------------+
1 row in set (0.00 sec)

mysql>
```

```
mysql> SELECT gl.host_id, gl.snmp_query_id, gl.snmp_index, gtg.local_graph_id, gtg.t_title, gtg.title FROM graph_templates_graph AS gtg INNER JOIN graph_local AS gl ON gtg.local_graph_id = gl.id WHERE gl.id = 7391;
+---------+---------------+------------+----------------+---------+-----------------------------------------------+
| host_id | snmp_query_id | snmp_index | local_graph_id | t_title | title                                         |
+---------+---------------+------------+----------------+---------+-----------------------------------------------+
|     399 |             1 | 516        |           7391 | 0       | |host_description| - Traffic - |query_ifName| |
+---------+---------------+------------+----------------+---------+-----------------------------------------------+
1 row in set (0.00 sec)
```
![image](https://user-images.githubusercontent.com/11805503/40132421-6657fcbc-5945-11e8-8b70-7830960b216c.png)
I just looked through the commit and started experimenting to get at least some results.

**Comment by pautiina** [comment]
This happened due to incorrect upgrade from Version 0.8.8b.
I run:
` php cli/upgrade_database.php --forcever=0.8.8`
and now have:
```
mysql> SELECT t_title,COUNT(t_title) FROM `graph_templates_graph` GROUP BY t_title;
+---------+----------------+
| t_title | COUNT(t_title) |
+---------+----------------+
|         |           4317 |
| on      |             36 |
+---------+----------------+
2 rows in set (0.02 sec)

```
It is necessary to make some decision: either close Issue or change the code?

**Comment by netniV** [comment]
I think we need to be handling the situation.  However, for 1.2 we could add an extra upgrade step that performs the same update to the t_title value so that it is corrected.

If it goes wrong after that, there is clearly a code issue somewhere.

**Comment by xefil** [comment]
Hello,
sorry, I'm having same issue after upgrading from 1.1.6 to 1.1.38.
What should I do to have my graph titles back?
On the generated image they are ok, but not on the management -> graphs list (graph name).
Thanks, Simon

**Comment by netniV** [comment]
Try this patch to see if it works for you:

```diff
diff --git a/lib/functions.php b/lib/functions.php
index 91736b05..fe2788a8 100644
--- a/lib/functions.php
+++ b/lib/functions.php
@@ -1378,7 +1378,7 @@ function get_graph_title($local_graph_id) {
 		array($local_graph_id));
 
 	if (sizeof($graph)) {
-		if (strstr($graph['title'], '|') && !empty($graph['host_id']) && $graph['t_title'] == '') {
+		if (strstr($graph['title'], '|') && !empty($graph['host_id']) && empty($graph['t_title'])) {
 			$graph['title'] = substitute_data_input_data($graph['title'], $graph, 0);
 			return expand_title($graph['host_id'], $graph['snmp_query_id'], $graph['snmp_index'], $graph['title']);
 		} else {
```

**Comment by xefil** [comment]
Thanks, it works :-)

**Comment by netniV** [comment]
@pautiina - Does this also work for you Alex?

**Comment by pautiina** [comment]
Now I can not check it anymore. I fixed it all, through a forced update from version 0.8.8.
I'm think that it can work

**Comment by netniV** [comment]
I think this is the correct call so I’ll create a PR for it

**Comment by pautiina** [comment]
@netniV ok.

**Comment by netniV** [comment]
I'll see about adding that in too.

**Comment by cigamit** [comment]
Part one of two committed.

**Comment by cigamit** [comment]
Resolved now.

**Comment by netniV** [comment]
I'll scrap that PR then ;-)

**Comment by cigamit** [comment]
Yea, I've been away.  Back for a weekend anyway.
