### ISSUE TITLE
Cacti 1.2.0 - Latest Develop Branch - External Link

### ISSUE THREAD

**Issue by anarkia1976** [Cacti/cacti#1616]
Hi,
after the last changes i have these errors into cacti.log when i try to create a new external link tab:

2018/05/07 14:56:05 - DBCALL ERROR: SQL Save Failed for Table 'external_links'. SQL:'INSERT INTO external_links (`id`, `title`, `style`, `enabled`, `refresh`, `contentfile`, `sortorder`, `extendedstyle`) VALUES (0, 'DB Clienti', 'TAB', 'on', '300', 'https://x.x.x.x/portale/', 12, '') ON DUPLICATE KEY UPDATE `title`=VALUES(`title`), `style`=VALUES(`style`), `enabled`=VALUES(`enabled`), `refresh`=VALUES(`refresh`), `contentfile`=VALUES(`contentfile`), `sortorder`=VALUES(`sortorder`), `extendedstyle`=VALUES(`extendedstyle`)'
2018/05/07 14:56:05 - CMDPHP SQL Backtrace: (/links.php: 97 sql_save)(/lib/database.php: 1013 _db_replace)(/lib/database.php: 960 db_execute)(/lib/database.php: 147 db_execute_prepared)(/lib/database.php: 220 cacti_debug_backtrace)
2018/05/07 14:56:05 - CMDPHP ERROR: A DB Exec Failed!, Error: Unknown column 'refresh' in 'field list'
2018/05/07 14:56:05 - DBCALL ERROR: A DB Exec Failed!, Error:1054, SQL:'INSERT INTO external_links (`id`, `title`, `style`, `enabled`, `refresh`, `contentfile`, `sortorder`, `extendedstyle`) VALUES (0, 'DB Clienti', 'TAB', 'on', '300', 'https://x.x.x.x/portale/', 12, '') ON DUPLICATE KEY UPDATE `title`=VALUES(`title`), `style`=VALUES(`style`), `enabled`=VALUES(`enabled`), `refresh`=VALUES(`refresh`), `contentfile`=VALUES(`contentfile`), `sortorder`=VALUES(`sortorder`), `extendedstyle`=VALUES(`extendedstyle`)'
2018/05/07 14:56:05 - CMDPHP PHP ERROR NOTICE Backtrace: (/links.php: 97 sql_save)(/lib/database.php: 990 CactiErrorHandler)(/lib/functions.php: 4703 cacti_debug_backtrace)
2018/05/07 14:56:05 - ERROR PHP NOTICE: Undefined index: refresh in file: /usr/share/cacti/lib/database.php on line: 990
2018/05/07 14:56:05 - CMDPHP PHP ERROR NOTICE Backtrace: (/links.php: 97 sql_save)(/lib/database.php: 989 CactiErrorHandler)(/lib/functions.php: 4703 cacti_debug_backtrace)
2018/05/07 14:56:05 - ERROR PHP NOTICE: Undefined index: refresh in file: /usr/share/cacti/lib/database.php on line: 989
2018/05/07 14:56:05 - CMDPHP PHP ERROR NOTICE Backtrace: (/links.php: 97 sql_save)(/lib/database.php: 988 CactiErrorHandler)(/lib/functions.php: 4703 cacti_debug_backtrace)
2018/05/07 14:56:05 - ERROR PHP NOTICE: Undefined index: refresh in file: /usr/share/cacti/lib/database.php on line: 988
2018/05/07 14:56:05 - CMDPHP PHP ERROR NOTICE Backtrace: (/links.php: 97 sql_save)(/lib/database.php: 987 CactiErrorHandler)(/lib/functions.php: 4703 cacti_debug_backtrace)
2018/05/07 14:56:05 - ERROR PHP NOTICE: Undefined index: refresh in file: /usr/share/cacti/lib/database.php on line: 987
2018/05/07 14:55:41 - DBCALL ERROR: SQL Save Failed for Table 'external_links'. SQL:'INSERT INTO external_links (`id`, `title`, `style`, `enabled`, `refresh`, `contentfile`, `sortorder`, `extendedstyle`) VALUES (0, 'DB CLienti', 'TAB', 'on', '0', 'https://x.x.x.x/portale/', 12, '') ON DUPLICATE KEY UPDATE `title`=VALUES(`title`), `style`=VALUES(`style`), `enabled`=VALUES(`enabled`), `refresh`=VALUES(`refresh`), `contentfile`=VALUES(`contentfile`), `sortorder`=VALUES(`sortorder`), `extendedstyle`=VALUES(`extendedstyle`)'
2018/05/07 14:55:41 - CMDPHP SQL Backtrace: (/links.php: 97 sql_save)(/lib/database.php: 1013 _db_replace)(/lib/database.php: 960 db_execute)(/lib/database.php: 147 db_execute_prepared)(/lib/database.php: 220 cacti_debug_backtrace)
2018/05/07 14:55:41 - CMDPHP ERROR: A DB Exec Failed!, Error: Unknown column 'refresh' in 'field list'
2018/05/07 14:55:41 - DBCALL ERROR: A DB Exec Failed!, Error:1054, SQL:'INSERT INTO external_links (`id`, `title`, `style`, `enabled`, `refresh`, `contentfile`, `sortorder`, `extendedstyle`) VALUES (0, 'DB CLienti', 'TAB', 'on', '0', 'https://x.x.x.x/portale/', 12, '') ON DUPLICATE KEY UPDATE `title`=VALUES(`title`), `style`=VALUES(`style`), `enabled`=VALUES(`enabled`), `refresh`=VALUES(`refresh`), `contentfile`=VALUES(`contentfile`), `sortorder`=VALUES(`sortorder`), `extendedstyle`=VALUES(`extendedstyle`)'
2018/05/07 14:55:41 - CMDPHP PHP ERROR NOTICE Backtrace: (/links.php: 97 sql_save)(/lib/database.php: 990 CactiErrorHandler)(/lib/functions.php: 4703 cacti_debug_backtrace)
2018/05/07 14:55:41 - ERROR PHP NOTICE: Undefined index: refresh in file: /usr/share/cacti/lib/database.php on line: 990
2018/05/07 14:55:41 - CMDPHP PHP ERROR NOTICE Backtrace: (/links.php: 97 sql_save)(/lib/database.php: 989 CactiErrorHandler)(/lib/functions.php: 4703 cacti_debug_backtrace)
2018/05/07 14:55:41 - ERROR PHP NOTICE: Undefined index: refresh in file: /usr/share/cacti/lib/database.php on line: 989
2018/05/07 14:55:41 - CMDPHP PHP ERROR NOTICE Backtrace: (/links.php: 97 sql_save)(/lib/database.php: 988 CactiErrorHandler)(/lib/functions.php: 4703 cacti_debug_backtrace)
2018/05/07 14:55:41 - ERROR PHP NOTICE: Undefined index: refresh in file: /usr/share/cacti/lib/database.php on line: 988
2018/05/07 14:55:41 - CMDPHP PHP ERROR NOTICE Backtrace: (/links.php: 97 sql_save)(/lib/database.php: 987 CactiErrorHandler)(/lib/functions.php: 4703 cacti_debug_backtrace)
2018/05/07 14:55:41 - ERROR PHP NOTICE: Undefined index: refresh in file: /usr/share/cacti/lib/database.php on line: 987

thanks a lot

**Comment by netniV** [comment]
A new field was added to the database.  If you already did a 1.2 upgrade, that field would not be present.  There are two choices, manually add the table or use the following SQL then run through the upgrade again:

```sql
update version set cacti = '1.1.38';
```

**Comment by anarkia1976** [comment]
I have merged cacti.sql after the git pull, is it updated?

**Comment by netniV** [comment]
Not sure.  We will be running an audit prior to release to ensure that it is but for now there may be inconsistencies

**Comment by anarkia1976** [comment]
i have make your suggestions, but with no clue. :(

**Comment by anarkia1976** [comment]
It's work. Only for info purpose for users like me after a "git pull":
- connect to "cacti" database
- update version set cacti = '<previous version>';
- php -q upgrade_database.php
thanks a lot

**Comment by netniV** [comment]
You can use upgrade_database.php or you can simply navigate to the website and run through the installer code.  Personally, I wouldn't set the version to blank, I would set it to the previous valid version, eg, "1.1.38"
