### ISSUE TITLE
PHP ERROR: Call to undefined function  api_data_source_cache_crc_update() in file:  /usr/share/cacti/lib/utility.php on line: 658

### ISSUE THREAD

**Issue by gundalba** [Cacti/cacti#1620]
OS: CentOS 7
Cacti : 1.1.37
MACTrack: 4.2
 
May be two separate issues I am reporting here...
I am seeing following errors (cacti.log) when MacTrack is being installed and activated from Cacti.
It may or may not be related but added device on MT shows up with "Unknown" status... 
--
2018/05/08 13:30:30 - MACTRACK ERROR: No device types have been found.
2018/05/08 13:23:31 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4628 cacti_debug_backtrace)
2018/05/08 13:23:31 - ERROR PHP ERROR: Call to undefined function  api_data_source_cache_crc_update() in file:  /usr/share/cacti/lib/utility.php on line: 658

**Comment by netniV** [comment]
This was already reported by you in #1602
