### ISSUE TITLE
Realtime Popup can cause automatic logout

### ISSUE THREAD

**Issue by chathurag** [Cacti/cacti#1621]
Cacti get automatic logout during realtime window.

**Comment by netniV** [comment]
Did you have any other tabs open?  This may happen if you have realtime set to be a new window

**Comment by chathurag** [comment]
Since I need to run real time for more than one graphs in different trees I have set real time to be in new windows not tab.

**Comment by netniV** [comment]
Windows/Tabs make no real difference, but do you have any cacti tabs left open that are not on realtime displays?  If so, these may be cause the logout.

**Comment by netniV** [comment]
If ANY pages OTHER than real-time is open, that page will cause a logout.

**Comment by chathurag** [comment]
Logout happens even though none other tabs kept than realtime.

**Comment by cigamit** [comment]
Resolved.
