### ISSUE TITLE
Cacti graph no data 

### ISSUE THREAD

**Issue by imadtranscend** [Cacti/cacti#1622]
Hi 
I installed cacti on cent0s 7, everything well but the graph shows me no data !! 
Note machine localhost there is data! 

any help?

![capture](https://user-images.githubusercontent.com/39050051/39813788-8df89106-539a-11e8-9b20-1edb5dba462c.PNG)

**Comment by anarkia1976** [comment]
Enable verbose log, and analyze it, please first search over the git or forum for a possible solution.
Post all tech infos about your env and a step by step configuration for replicate your issue.

**Comment by cigamit** [comment]
There are three real things to check right off the bat.
1) Is the cron running (check the cacti log for stats)?
2) Are permissions right in the rra directory?  Can the cron user write there?
3) Is your poller interval correct?

This issue has been answered dozens of times on the Cacti forums and that's where issues like this belong.
