### ISSUE TITLE
Logo Proposal for Cacti

### ISSUE THREAD

**Issue by baranpirincal** [Cacti/cacti#1629]
Hey, I am graphic designer and my aim is make my portfolio better with supporting open source project in field of graphic. I can contribute on your project with making a logo design.  I saw that you have a logotype and a cute cactus but I can use it with different way. I can show my portfolio if you want it. and I would be very pleased if you interested. I am waiting your feedback, have a nice day! :)

Best Regards,
Baran Pirincal
Visual Communication Designer

**Comment by cigamit** [comment]
Sorry, that image is trademarked.  Please reach out to troman@cacti.net if you would like to have additional conversations about this and/or other topics.
