### ISSUE TITLE
Devices - UI - column headers missing background color

### ISSUE THREAD

**Issue by BSOD2600** [Cacti/cacti#163]
latest 7e18aa65f650cae5c3d7507836c06170d7ed8d44 
Chrome 55

column headers color missing from both
Associated Graph Templates
Associated Data Queries

![image](https://cloud.githubusercontent.com/assets/5741811/21754191/0c6ec178-d5b0-11e6-8790-624eac0d35cc.png)
![image](https://cloud.githubusercontent.com/assets/5741811/21754198/221fd5a2-d5b0-11e6-8b47-41bb94d98b77.png)

**Comment by cigamit** [comment]
This is a chrome caching issue.  It was reported a few days ago, and corrected.  I'm not quite sure how to get Chrome to forcibly refresh it's cascading style sheets.  It seems not to follow the standard these days.
