### ISSUE TITLE
Cacti Issue v. 1.1.15

### ISSUE THREAD

**Issue by Jack9198** [Cacti/cacti#1630]
Hi, I have this error in cacti (version 1.1.15).
Could someone help me?

2018/05/11 10:56:17 - CMDPHP PHP ERROR NOTICE Backtrace: (/host.php: 78 host_add_query)(/host.php: 529 api_device_dq_add)(/lib/api_device.php: 114 run_data_query)(/lib/data_query.php: 78 query_snmp_host)(/lib/data_query.php: 629 cacti_snmp_session_walk)(/lib/snmp.php: 465 walk)(/include/phpsnmp/classSNMP.php: 225 cacti_snmp_walk)(/lib/snmp.php: 733 format_snmp_string)(/lib/snmp.php: 805 CactiErrorHandler)(/lib/functions.php: 4394 cacti_debug_backtrace)
2018/05/11 10:56:17 - ERROR PHP NOTICE: Use of undefined constant SNMP_VALUE_NUMERIC - assumed 'SNMP_VALUE_NUMERIC' in file: /opt/cacti/lib/snmp.php on line: 805
2018/05/11 10:56:17 - CMDPHP PHP ERROR NOTICE Backtrace: (/host.php: 78 host_add_query)(/host.php: 529 api_device_dq_add)(/lib/api_device.php: 114 run_data_query)(/lib/data_query.php: 78 query_snmp_host)(/lib/data_query.php: 629 cacti_snmp_session_walk)(/lib/snmp.php: 465 walk)(/include/phpsnmp/classSNMP.php: 225 cacti_snmp_walk)(/lib/snmp.php: 733 format_snmp_string)(/lib/snmp.php: 805 CactiErrorHandler)(/lib/functions.php: 4394 cacti_debug_backtrace)
2018/05/11 10:56:17 - ERROR PHP NOTICE: Use of undefined constant SNMP_VALUE_NUMERIC - assumed 'SNMP_VALUE_NUMERIC' in file: /opt/cacti/lib/snmp.php on line: 805
2018/05/11 10:56:17 - CMDPHP PHP ERROR NOTICE Backtrace: (/host.php: 78 host_add_query)(/host.php: 529 api_device_dq_add)(/lib/api_device.php: 114 run_data_query)(/lib/data_query.php: 78 query_snmp_host)(/lib/data_query.php: 629 cacti_snmp_session_walk)(/lib/snmp.php: 465 walk)(/include/phpsnmp/classSNMP.php: 225 cacti_snmp_walk)(/lib/snmp.php: 733 format_snmp_string)(/lib/snmp.php: 805 CactiErrorHandler)(/lib/functions.php: 4394 cacti_debug_backtrace)
2018/05/11 10:56:17 - ERROR PHP NOTICE: Use of undefined constant SNMP_VALUE_NUMERIC - assumed 'SNMP_VALUE_NUMERIC' in file: /opt/cacti/lib/snmp.php on line: 805
2018/05/11 10:56:17 - CMDPHP PHP ERROR NOTICE Backtrace: (/host.php: 78 host_add_query)(/host.php: 529 api_device_dq_add)(/lib/api_device.php: 114 run_data_query)(/lib/data_query.php: 78 query_snmp_host)(/lib/data_query.php: 629 cacti_snmp_session_walk)(/lib/snmp.php: 465 walk)(/include/phpsnmp/classSNMP.php: 225 cacti_snmp_walk)(/lib/snmp.php: 733 format_snmp_string)(/lib/snmp.php: 805 CactiErrorHandler)(/lib/functions.php: 4394 cacti_debug_backtrace)

Thanks!

**Comment by cigamit** [comment]
Please upgrade.  Thanks.
