### ISSUE TITLE
Cacti Logo update - Proposed

### ISSUE THREAD

**Issue by k-syusteem** [Cacti/cacti#1633]
### Hi @cigamit! 

I have accomplished something well related to the logo for your project "Cacti". This is one contribution I can make to you, because I am just a graphic designer. Here is the final result of the design:

![cover](https://user-images.githubusercontent.com/38687140/39938890-a3f672c6-557e-11e8-9c09-affebe7369f1.png)

![last result2](https://user-images.githubusercontent.com/38687140/39938835-6ca82e40-557e-11e8-9cbb-fb1c3686ccbc.png)

![last result](https://user-images.githubusercontent.com/38687140/39938842-70ebe000-557e-11e8-9cf2-22e29e6a9ed6.png)

<b>Every color just follows than the basic theme of Cacti is Green color, I hope you use this, and I am also willing to fulfill your every suggestion and further request.</b>

<b><i>Regards @k-syusteem</i></b>

**Comment by cigamit** [comment]
Again, you know who to email.  This type of communication does not belong here.
