### ISSUE TITLE
Send a test email 1.1.37 - html displaying

### ISSUE THREAD

**Issue by brianandcamera** [Cacti/cacti#1637]
Shows as `'Emailing Options<div id="emailtest" class="emailtest">Send a Test Email</div>' `

Button is not clickable. Fresh install from EPEL 

![image](https://user-images.githubusercontent.com/23463190/40007363-8a6e6640-576a-11e8-97dc-f6016c347c26.png)

**Comment by netniV** [comment]
This is a known issue and has been resolved in 1.1.38.
