### ISSUE TITLE
Graph Tree renaming

### ISSUE THREAD

**Issue by chathurag** [Cacti/cacti#1638]
Renaming graph tree moves the tree to the top of all trees and we have get it down to earlier place one by one manually

**Comment by netniV** [comment]
What version of Cacti are you running? I'm sure this was fixed a version or two ago.

**Comment by chathurag** [comment]
1.1.38 which is latest one at cacti.net site

**Comment by cigamit** [comment]
Enable drag and drop from Console > Settings > General.  But you should ensure that you simply don't have the list sorted by name too.  I suspect that is the issue.
