### ISSUE TITLE
Cacti Version 1.2.0 - Can't disable rrdupdate ondemand

### ISSUE THREAD

**Issue by anarkia1976** [Cacti/cacti#1642]
Hi, 
in the latest version i can't disable this feature:
![image](https://user-images.githubusercontent.com/1744639/40224101-6c55a4b6-5a85-11e8-90a6-ad20c7990952.png)
thanks

**Comment by cigamit** [comment]
Do you have a remote data collector defined?

**Comment by anarkia1976** [comment]
Where can i verify this?

**Comment by anarkia1976** [comment]
I have a problem with boost enabled and "Data Input Methods: Script/Command":
![image](https://user-images.githubusercontent.com/1744639/40905605-bfc7c258-67de-11e8-9593-01863e1314db.png)

With old 1.1.38 and boost disabled, no problems so far:
![image](https://user-images.githubusercontent.com/1744639/40905634-d9ffed08-67de-11e8-9df7-700005242cee.png)

do you have suggestions?

thanks a lot

**Comment by cigamit** [comment]
More than likely a permission problem.  I generally solve this by having the web server and the cron entry user run as the same user, but you can also use the group sticky bit on the rra directory to permit two users from the same group to write to the directory.

**Comment by anarkia1976** [comment]
Strange, values are corretly written but with every tot hours we have loss of infos like in the graph below.

**Comment by cigamit** [comment]
I only experience these problems when there are permission problems.  Also, you should maybe check the width of the output column in the boost table and make it match the poller_output table, though this would not be a problem in that case.  It might also be that the Apache server or SELinux is preventing your web service from having write access into that directory.

**Comment by cigamit** [comment]
Do you have remote data collectors yes or no?

**Comment by anarkia1976** [comment]
Yes

**Comment by cigamit** [comment]
The update on demand is required when you have remote data collectors.  You have a permission problem.  You web server is unable to write the RRDfiles.  You should correct that.

**Comment by netniV** [comment]
Please note, from 1.2, the web server will tell you when it does not have RRD folder or file permissions. (see Issue #1734 and associated PR #1755).  There is no recorded warning yet from the poller.
