### ISSUE TITLE
Cacti Version 1.2.0 - Only first 12 graphs display

### ISSUE THREAD

**Issue by anarkia1976** [Cacti/cacti#1643]
Hi,
in the tree panel i can see only first 12 graphs:
![image](https://user-images.githubusercontent.com/1744639/40224171-a6c4d5c2-5a85-11e8-8677-8166b6a4f045.png)
thanks

**Comment by dsclassen** [comment]
Same here.
<img width="1313" alt="extra_graph_widgets" src="https://user-images.githubusercontent.com/8882563/40248765-d08f5dd2-5a85-11e8-88c7-b8260148d8f8.png">

**Comment by netniV** [comment]
So, we are running too many trying to be displayed?  That should be relatively easy to fix

**Comment by cigamit** [comment]
Resolved.  Thanks for reporting.
