### ISSUE TITLE
Graphs has no new data

### ISSUE THREAD

**Issue by lucousin** [Cacti/cacti#1644]
Hello, 

I've just upgraded from 0.8.8d with multipollerserver to 1.1.38.

I have one web server and one remote data collector. 

I managed to get this poller running but no RRDs are processed.
Additionally it seems I have an issue between the remote agent and main server.

2018/05/18 12:21:37 - SYSTEM STATS: Time:92.4469 Method:spine Processes:12 Threads:18 Hosts:161 HostsPerProcess:14 DataSources:1271 RRDsProcessed:0

2018/05/18 12:16:54 - CMDPHP Unauthorized remote agent access attempt from {REMOTE_poller}

They both ping correctly using the "Web Site Hostname" from the data collector page.

Feel free to ask for infos.

Thanks for any help you can provide.

**Comment by anarkia1976** [comment]
Do you use hostnames or ip for remote/main poller?

**Comment by lucousin** [comment]
Hi anarkia, 

I'm using hostnames.

**Comment by netniV** [comment]
On the remote poller, the website user should have read/write access as well as the polling user from cron.  As a standard, I also try to do the same on the local poller.

What you need to do is ensure that either the IP or the hostname is listed against the poller in the pollers table under the hostname column.  If using the hostname, it must be the name when the IP is resolved.  This is shown in what is logged as the full message will end with `<resolved name> (<ip>)`

**Comment by lucousin** [comment]
Now facing the following issue:

Remote poller runs but no RRD processed.

Main poller down/unknown with below error:

2018/05/18 18:46:08 - ERROR PHP ERROR: Call to undefined function mb_strlen() in file: /var/www/html/cacti/lib/rrd.php on line: 1503
2018/05/18 18:46:08 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4628 cacti_debug_backtrace)

**Comment by lucousin** [comment]
As an additional info, I'm not using a localhost databse on the main poller but I'm connecting to a remote database.

![image](https://user-images.githubusercontent.com/7765540/40358579-f7c3e80e-5dbf-11e8-8f7b-ac7ad154cbb7.png)

In the above screenshot my main poller has no info related to db whereas the remote poller does have some.

**Comment by lucousin** [comment]
Also getting unalbe to establish mysql conenction with remote poller when using the "full sync" function. 

I did execute all the grants on both sides.

Does the 1.1.x no longer work with a remote database ?

**Comment by netniV** [comment]
You don't have the correct php mod's enabled hence the error above about MultiByte being missing.

**Comment by cigamit** [comment]
Closing for lack of feedback.
