### ISSUE TITLE
Cacti Version 1.1.38 - Can't create aggregate graphic 

### ISSUE THREAD

**Issue by 311villagehead** [Cacti/cacti#1645]
Hi,
in the this version, i can't create aggregate graphic

![qq2018](https://user-images.githubusercontent.com/29101156/40247452-05f8a1a8-5aff-11e8-90b7-6eabcd663dcd.jpg)

but in cacti version 0.88h,I can easily create aggregated graphics in the same way.Can you tell me how to solve this problem? Thanks.

**Comment by pautiina** [comment]
Use Graph management not data source menu.

**Comment by 311villagehead** [comment]
wow, I use the graph management menu to create an aggregation graph, but in the aggregation graph menu, 95th percentile related options cannot be edited.As shown below，
![qq 20180519105716](https://user-images.githubusercontent.com/29101156/40264355-36a12140-5b54-11e8-9019-c6275521bc0c.jpg)
I can't find related options in the template menu.Can you tell me how to solve this problem? Thanks.

**Comment by YangShenghui2018** [comment]
hi, please look here https://github.com/Cacti/cacti/issues/1529

**Comment by 311villagehead** [comment]
@YangShenghui2018 Does it means that this problem has not been solved yet?

**Comment by cigamit** [comment]
This is operating by design in the develop (1.2) branch.  If you feel you would like it to change.  Please submit a very specific request as a new ticket.
