### ISSUE TITLE
Erros in Log File on Remote Data Collector 

### ISSUE THREAD

**Issue by The-Mafioso** [Cacti/cacti#1647]
Many errors are showing up after upgrading to 1.1.38 from 1.1.36 on the Remote Data Poller and not the Main Cacti Server. Errors below:
2018/05/20 02:43:07 - CMDPHP PHP ERROR WARNING Backtrace: (/poller_commands.php: 112 run_data_query)(/lib/data_query.php: 154 update_poller_cache_from_query)(/lib/utility.php: 103 poller_update_poller_cache_from_buffer)(/lib/utility.php: 541 sizeof)(CactiErrorHandler)(/lib/functions.php: 4585 cacti_debug_backtrace)
2018/05/20 02:43:07 - ERROR PHP WARNING: sizeof(): Parameter must be an array or an object that implements Countable in file: /var/www/cacti/lib/utility.php on line: 541
2018/05/20 02:43:04 - DBCALL ERROR: SQL Assoc Failed!, Error: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'cactidb.snmpagent_cache.oid' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
2018/05/20 02:43:04 - DBCALL ERROR: SQL Assoc Failed!, Error:1055, SQL:'SELECT * FROM `snmpagent_cache` WHERE `oid` LIKE ? GROUP BY name ORDER BY oid' 

![01](https://user-images.githubusercontent.com/27900099/40274196-32c36788-5bd9-11e8-978d-8a2d5d95e614.png)
![02](https://user-images.githubusercontent.com/27900099/40274197-364eb060-5bd9-11e8-8796-79b30229f47f.png)

**Comment by netniV** [comment]
This has already been patched in 1.2.  Basically, the $ids field should be a string but is initialized as an array, then later checked as an array using sizeof().  However, in between it's actually built up as a string so should have been using a strlen() instead.

If you check the same function in the 1.2 code you'll see the differences.
