### ISSUE TITLE
"Unknown RRDtool Error" when opening Graph Management

### ISSUE THREAD

**Issue by adiprnm** [Cacti/cacti#1648]
Hi,
I've recently installed Cacti on my laptop. When I opened Graph Management, I got an error said "Unknown RRDtool Error".

![capture](https://user-images.githubusercontent.com/18739617/40291982-9ac2f8e8-5cf2-11e8-9757-0031432ed340.PNG)

Can you tell me how to fix this error? Thank you.

**Comment by cigamit** [comment]
The Issue tracker is for bugs in Cacti, please ask for help on the cacti forums instead of here.
http://cacti.net
