### ISSUE TITLE
User Login History - purge not complete

### ISSUE THREAD

**Issue by BSOD2600** [Cacti/cacti#165]
1) when purging the user login history, it's not deleting ALL of the entries. The first login still remains.

![image](https://cloud.githubusercontent.com/assets/5741811/21754280/0c39fa18-d5b2-11e6-9124-44645d86fddd.png)

2) After the purge, a NEW entry should be written (user or cacti log) stating the log has been cleared by X user.

**Comment by cigamit** [comment]
Actually, the behavior is to save the last login for each user.  So, this behavior is expected.
