### ISSUE TITLE
Batch data export

### ISSUE THREAD

**Issue by tyit** [Cacti/cacti#1650]
How to batch export port data of all switches to xls files ?

**Comment by cigamit** [comment]
You could also use MacTrack to get all the port data.  It's a bit of a stretch if you are not interested in using all the features of MacTrack.

**Comment by tyit** [comment]
@cigamit 
Thank you Does this MacTrack support the latest version 1.1.38 ?

**Comment by tyit** [comment]
@netniV 
Thank you

**Comment by tyit** [comment]
This is very good. cacti getting better and better. Thank you guys.
