### ISSUE TITLE
Check temporary folder has write access during import

### ISSUE THREAD

**Issue by sd3m0n** [Cacti/cacti#1651]
Cacti ver. 1.1.38 and 1.2.0
Cacti server is on Ubuntu Server 16.04.4
Client - Windows 10

I'm trying to import the device template. Cacti is on http NOT on https. I choose xml template file from windows local folder. In Google Chrome it sais "C:\fakepath\..." in Microsoft Edge it shows full path to file. But in both cases after clicking "Import" button nothing happens and template doesnt appear in the template list.

Earlier, when there was a field to put the xml code in it instead of selecting a single file it worked well (the template is 100 percent working). I've even exported these templates before reinstalling cacti. Ant then I tried to import these files to the clean cacti inst.

**Comment by netniV** [comment]
Are you seeing any errors in your log files?

**Comment by sd3m0n** [comment]
No, nothing in logs. When clicking the import button the interface only blinks once and then nothing happens.

Here is that very template in txt file.

[cacti_host_template_apc_smart_ups_nmc2.txt](https://github.com/Cacti/cacti/files/2049981/cacti_host_template_apc_smart_ups_nmc2.txt)

**Comment by cigamit** [comment]
This imports fine on my system.  What browser are you using?  If using Chrome, you need to clear your browser cache likely.  Logoff and login again.  If not, or if you can not fix this, use a different browser, with Firefox and IE, you can his F5 to refresh the cache.  If it still does not work, open the browsers debug window, goto the network panel and attempt the import and post the response from the network posts response tab.  Also, look to the browsers debug console for JavaScript errors.  It might be a plugin possibly.

**Comment by sd3m0n** [comment]
I'm sorry, but in Chrome, Firefox, Microsoft Edge the situation is the same. I run the browser on Windows 10 and am trying to import template from it. The template is in local folder. When I choose the file in Chrome it shows "C:\fakepath\cacti_host_template_apc_smart_ups_nmc2.xml" ofcourse it is the wrong path (the same thing is with Firefox). And nothing happens after clicking the import button. Microsoft Edge shows the correct path "D:\templates\_\cacti_host_template_apc_smart_ups_nmc2.xml" but after clicking the import button nothing happens either. In all ways the page only blinks once and there is no template in the list under templates->device.

I tried to turn on the debug mode in Chrome (F12) and I don't see errors under network tab...

![1](https://user-images.githubusercontent.com/25234512/40731423-b10da172-6439-11e8-9d1c-97f60244d58c.png)

**Comment by sd3m0n** [comment]
I also tried mobile Chrome on Android 8 and the same situation...

**Comment by netniV** [comment]
the fakepath thing is a standard thing with IE/Chrome.  

https://stackoverflow.com/questions/18254118/fakepath-issue-in-chrome-browser
https://stackoverflow.com/questions/4851595/how-to-resolve-the-c-fakepath

I'm not sure if the element we are using is an input or some other element, but there could potentially be an issue if it's not an input according to one of those links.

**Comment by sd3m0n** [comment]
I don't think the reason is in "C:\fakepath..." anyway. I've made some research with my poor php knowledge... 

So... The code is in templates_import.php as far as I anderstood. Clicking the Import button we "reload" this script and submit all inputs on the form (`print "<form method='post' action='templates_import.php' enctype='multipart/form-data'>\n";`), right? I added `print_r($_POST);` and `print_r($_REQUEST);` at the begining of templates_import.php right before includes just to see what is in this variables after submitting form inputs by clicking the button. I get the output like Array() Array() - so the variables are empty. And thus `function form_save()` is unreachable because `if ($is_save && $action == 'save')` condition never goes to TRUE in my case... I also added echo to the form_save() function to know if somhow it is reachable, but no output....

PS: I also tried to import template (mentioned above) in FireFox on Ubuntu 18.04. Everywhere: Win, Linux, Android, any browser - the result is the same.

I used the latest version from git (1.2.0) through git clone to install cacti.

**Comment by netniV** [comment]
Actually, I have also just imported this template successfully.  This suggests a problem with either your server or your browser.  Try checking that $_REQUEST is being set properly using `echo “<pre>Request data:\n” . var_export($_REQUEST,true) . “</pre>”`

**Comment by netniV** [comment]
The reason for this could be if you have the system set not to register the standard PHP global variables such as $_SERVER and $_REQUEST etc

**Comment by sd3m0n** [comment]
I verified server settings (php and nginx) and didn't find any suspicious things. I've attached my conf files to post with hope You have a sharper eye and much more knowledge.

[cacti.txt](https://github.com/Cacti/cacti/files/2064353/cacti.txt)
[nginx.conf.txt](https://github.com/Cacti/cacti/files/2064354/nginx.conf.txt)
[php.ini.txt](https://github.com/Cacti/cacti/files/2064355/php.ini.txt)
[php-fpm.conf.txt](https://github.com/Cacti/cacti/files/2064356/php-fpm.conf.txt)

**Comment by cigamit** [comment]
So, back to my original request.  Once you have the network page open, just before you press the import button.  Hit the big red button in the upper left corner of the debug panel.  That will remove all the lines as shown in your earlier screen shot.  Then, press the import button.  You will see one more entry line there.  Select that entry line and goto the Params tab.  Send us a screen shot of all the variables there.

Can you verify that SE Linux is disabled, or configured to allow you to actually submit the form.  If enabled, then ensure that the mode is permissive.  If not, change to permissive and reboot, then you should try again and then check your syslog for a warning telling you what to do to allow this form submission from Apache.  Take those actions and you should be set.  If you don't care about SE Linux, just disable and reboot.  If the server is internet facing though, I would not do that.

**Comment by sd3m0n** [comment]
At first, my software: ubuntu server 16.04.4, php 7.0, mysql 5.7, nginx, php-fpm, cacti-latest (1.2.0)

I've reinstalled everything from scratch. But still having this issue.
I don't have SE Linux. Now using FireFox for debug.

Import-Templates->Paused Network Log->Select a file to import->Press Import button->A lot of GET requests ant 1 POST at the top->Click on in->Go to Params tab.

![2](https://user-images.githubusercontent.com/25234512/40886490-7a95623c-6741-11e8-94ed-9c5a50db58b0.png)
![1](https://user-images.githubusercontent.com/25234512/40886474-31b8498a-6741-11e8-88d6-10280c081778.png)

And the output from Params tab is in the txt file.
[2.txt](https://github.com/Cacti/cacti/files/2065927/2.txt)

**Comment by cigamit** [comment]
Okay, that all looks good.  Let's look at the next item on the network list.  Can you post it's response?

**Comment by sd3m0n** [comment]
Here are screenshots:
![01](https://user-images.githubusercontent.com/25234512/40890716-282dc330-6783-11e8-95c5-dd205efa5daa.png)
![02](https://user-images.githubusercontent.com/25234512/40890718-2a3ee32a-6783-11e8-92dc-ee2d93d3b6e9.png)

Params tab is empty for this item and "Response payload" is in file:
[02.txt](https://github.com/Cacti/cacti/files/2066311/02.txt)

**Comment by cigamit** [comment]
This has to have something to do with your web server, the post is good, but the response has not import information.

**Comment by netniV** [comment]
To me that would lead back to something I suggested earlier where the file size is too large, PHP/Apache can ignore the data and that is configurable.

**Comment by sd3m0n** [comment]
I will check all the options and double check nginx and php-fpm params.

**Comment by sd3m0n** [comment]
At last the problem is found. I turned on logging everything. And after researching logs I found that when loading up template file "cacti" can't create/put it to /tmp dir. So in cacti virtual host conf file I added /tmp to open_basedir var and import is working now. Simple solution... ridiculous problem...

Anyway thanks everyone for your help.

**Comment by netniV** [comment]
Interesting, I think we should leave this open for now so we can attempt to identify that and then patch it.

**Comment by netniV** [comment]
Checking that the TMP directory is writable is actually something the 1.2 installer does, btw.  Does at least at install time it should give you that warning.  We need to add it to the various import/export functions as a secondary check so that we prevent the actions if we don't have temporary directory access.

**Comment by cigamit** [comment]
What a wacky problem.

**Comment by netniV** [comment]
This is now displayed as follows:
![image](https://user-images.githubusercontent.com/9052188/43638711-c1d55b84-9711-11e8-96b9-edd5718dc487.png)

Since the PR is now open, I will close this issue.
