### ISSUE TITLE
Data source forgetting index value and index type

### ISSUE THREAD

**Issue by DigitalPackrat** [Cacti/cacti#1652]
I use the monitor running process from https://forums.cacti.net/viewtopic.php?t=6661 on Cacti 1.1.38.
It requires a change to the data source for each item monitored where the index value has the process name and index type is set as hrSWRunName. Randomly all index values and index types for an entire device reset where index value becomes blank and index type reverts to hrSWRunIndex which causes monitoring to break when a system is restarted.

It has occurred on multiple devices, some are repeat offenders. I only find out it has happened after a device is restarted and monitoring breaks for the processes. I have randomly checked on some devices but I have been unable to pinpoint when the data source resets.

**Comment by cigamit** [comment]
The only way to monitor PID's accurately, is to use the hmib plugin.  You should not rely on the PID as a primary key.  Can you please update the forum post on this one?

**Comment by DigitalPackrat** [comment]
I am not monitoring the PID, I am using the hrSWRunName with the name of the process which isn't an issue. The issue is the data source forgetting the settings.

**Comment by DigitalPackrat** [comment]
This wasn't an issue with 8.8h before upgrading to the 1.1 branch. I am aware of the PID changing when a process is restarted which is why the process name is used. The issue is not matched to when a process is restarted. It is when I notice the graph not working but some of the data sources have reverted settings outside of the process being restarted. Its purely an issue in cacti right now and I have hundreds of processes being monitored which can't be moved to the hmib plugin.

This may be related to issue 1449 were the Re-Index Method not maintained after migration from 8.8h to 1.1.36.
