### ISSUE TITLE
Data source forgetting index value and index type

### ISSUE THREAD

**Issue by DigitalPackrat** [Cacti/cacti#1654]
This is not an issue with PID changing, it is an issue with cacti forgetting data source settings.

I use the monitor running process from https://forums.cacti.net/viewtopic.php?t=6661 on Cacti 1.1.38.
It requires a change to the data source for each item monitored where the index value has the process name and index type is set as hrSWRunName. Randomly all index values and index types for an entire device reset where index value becomes blank and index type reverts to hrSWRunIndex which causes monitoring to break when a system is restarted.

It has occurred on multiple devices, some are repeat offenders. I only find out it has happened after a device is restarted and monitoring breaks for the processes. I have randomly checked on some devices but I have been unable to pinpoint when the data source resets.

This wasn't an issue with 8.8h before upgrading to the 1.1 branch. I am aware of the PID changing when a process is restarted which is why the process name is used. The issue is not matched to when a process is restarted. It is when I notice the graph not working but some of the data sources have reverted settings outside of the process being restarted. Its purely an issue in cacti right now and I have hundreds of processes being monitored which can't be moved to the hmib plugin.

This may be related to issue 1449 were the Re-Index Method not maintained after migration from 8.8h to 1.1.36.

**Comment by cigamit** [comment]
Upload the resource xml file please.

**Comment by cigamit** [comment]
I went and reviewed it.  Evil.  Let me see what changed between 0.8.8 and 1.x.

**Comment by hb9xar** [comment]
Something similar happens for Interface Statistics. My guess is, it has the same origin.

E.g.:
- having a Network device 'ppp0'
- data source is indexed by ifDescr ('ppp0'), reindexing method is "Verify All"
- the PPP session dies and is reestablished, causing it to appear at a different index in the ifTable
- during the next polling cycle, cacti detects the need for reindexing
- during re-indexing, the data source loses its Index Type and Index Value.

I tracked this down to update_snmp_index_order() where the corresponding SQL record in table data_input_data is re-populated from the host_snmp_cache table. I'm not sure what the actual purpose is to *always* overwrite the existing Index Type and Index Value. In the above case, this results in an *empty* Index Value to be written into data_input_data, effectively rendering the data source inoperable. Editing the data source in Cacti and placing the correct Index Value fixes the situation and the data source will collect again data.

In my case (using cacti-1.1.37 from EPEL repository) I could solve this by only overwriting the data_input_data record *if* a Index Value is found in host_snmp_cache, otherwise leave the existing settings unchanged.

lib/data_query.php: 
```
diff --git a/lib/data_query.php b/lib/data_query.php
index 5044569..8b24dbf 100644
--- a/lib/data_query.php
+++ b/lib/data_query.php
@@ -1627,22 +1627,24 @@ function update_snmp_index_order($data_query) {
                        AND snmp_index = ?',
                        array($data_query['host_id'], $data_query['snmp_query_id'], $data_query['snmp_index_on'], $data_query['snmp_index']));
 
-               db_execute_prepared('REPLACE INTO data_input_data
-                       (data_input_field_id, data_template_data_id, t_value, value)
-                       VALUES
-                       (?, ?, "", ?),
-                       (?, ?, "", ?),
-                       (?, ?, "", ?)',
-                       array(
-                               /* save the value to index on (ie. ifindex, ifip, etc) */
-                               $data_input_field['index_type'], $data_query['data_template_data_id'], $data_query['snmp_index_on'],
-                               /* save the actual value (ie. 3, 192.168.1.101, etc) */
-                               $data_input_field['index_value'], $data_query['data_template_data_id'], $snmp_cache_value,
-                               /* set the expected output type (ie. bytes, errors, packets) */
-                               $data_input_field['output_type'], $data_query['data_template_data_id'], $data_query['snmp_query_graph_id']
-                       )
-               );
-
+               /* only update data source index if there actually *is* an index returned from host_snmp_cache */
+               if (!empty($snmp_cache_value)) {
+                       db_execute_prepared('REPLACE INTO data_input_data
+                               (data_input_field_id, data_template_data_id, t_value, value)
+                               VALUES
+                               (?, ?, "", ?),
+                               (?, ?, "", ?),
+                               (?, ?, "", ?)',
+                               array(
+                                       /* save the value to index on (ie. ifindex, ifip, etc) */
+                                       $data_input_field['index_type'], $data_query['data_template_data_id'], $data_query['snmp_index_on'],
+                                       /* save the actual value (ie. 3, 192.168.1.101, etc) */
+                                       $data_input_field['index_value'], $data_query['data_template_data_id'], $snmp_cache_value,
+                                       /* set the expected output type (ie. bytes, errors, packets) */
+                                       $data_input_field['output_type'], $data_query['data_template_data_id'], $data_query['snmp_query_graph_id']
+                               )
+                       );
+               }
                /* now that we have put data into the 'data_input_data' table, update the snmp cache for ds's */
                update_data_source_data_query_cache($data_query['local_data_id']);
        }
```

__Not sure what this change breaks, though...__

Note: There is another issue with cacti and reindexing - see Pull request #1789 

/Thomas

**Comment by cigamit** [comment]
@hb9xar, can you open a bull request on this one?

**Comment by hb9xar** [comment]
PR #1790
see comment there about re-indexing.

**Comment by cigamit** [comment]
This topic is not resolved in the latest develop branch.

**Comment by DigitalPackrat** [comment]
So this issue was verified, marked as a bug then not resolved but closed. Please let me know if I am missing something but it looks like this just slid through the cracks. 

I have been logging this issue for the last few months. I cannot find anything consistent in the logs as a source but have narrowed it down to a group of devices that all revert their settings at the same random time.

**Comment by netniV** [comment]
There was another issue opened and a PR if you read through the comments above, that is probably why this one was closed.
