### ISSUE TITLE
Correct Cacti to handle new MySQL 8.0 reserved word `system`

### ISSUE THREAD

**Issue by solarcellsky** [Cacti/cacti#1655]
Database server
Server: localhost via TCP/IP
Server type: MySQL
Server version: 8.0.11 - MySQL Community Server - GPL
Protocol version: 10
User: root@localhost
Server charset: UTF-8 Unicode (utf8)

![image](https://user-images.githubusercontent.com/546897/40756595-fced1ca8-64b6-11e8-888c-055421596eb3.png)

**Comment by netniV** [comment]
What OS are you running this on?

**Comment by netniV** [comment]
Waiting on feedback from you @solarcellsky

**Comment by cigamit** [comment]
Likely they made the word 'system' a reserved word.  Yup:

https://dev.mysql.com/doc/refman/8.0/en/keywords.html#keywords-in-current-series

**Comment by cigamit** [comment]
Resolved.  Thanks for reporting.  Let us know what else you find.
