### ISSUE TITLE
How can this be done? ?

### ISSUE THREAD

**Issue by tyit** [Cacti/cacti#1656]
![cacti](https://user-images.githubusercontent.com/31933126/40766175-2bbc7ab8-64e1-11e8-909e-29b79de18449.png)

**Comment by cigamit** [comment]
Please state your question, and there is no reason to display a large image just to tell us the Cacti version

**Comment by tyit** [comment]
Aggregate cannot add 95th and percentage graphics modes

**Comment by tyit** [comment]
#1529

**Comment by netniV** [comment]
That is an existing question which is already open as an issue. Please use the search feature to locate it.
