### ISSUE TITLE
Cacti 1.1.38

### ISSUE THREAD

**Issue by Jack99891** [Cacti/cacti#1657]
Hello everyone,

I have a problem with a fresh installation of cacti (v 1.1.38)
I can see graph only in real time mode. Otherwise I see  "cannot opening /opt/cacti/rra/..."
The permissions are ok.
I tried to rebuild the poller with :
"php -q rebuild_poller_cache.php"
CMDPHP Validation Error, Variable:graph_start, Value:- Backtrace: (/graph_realtime.php: 44 get_filter_request_var)(/lib/html_utility.php: 443 die_html_input_error)(/lib/html_validate.php: 64 cacti_debug_backtrace)

Someone have this issue?

Thanks

**Comment by Jack99891** [comment]
If I run this command:
php -q poller.php --force 
on the rra direcory, the rrd files are wirtten. But there's no data on the graphs
![cattura](https://user-images.githubusercontent.com/39792857/40788343-1e205eb0-64f0-11e8-977d-75f63c9f4c26.JPG)

**Comment by cigamit** [comment]
This issue should be addressed in the Cacti forums.  Can you please address your question there?  This seems more of a new user issue.  You should get help there.

**Comment by Jack99891** [comment]
Ok no problema, thanks!
