### ISSUE TITLE
Input Field with variable hostname not automatically provisioned

### ISSUE THREAD

**Issue by emeidi** [Cacti/cacti#1661]
Cacti 1.1.36

Hi Cacti Community

Although I specified an Input Field for a new Data Input Method ...

<img width="1218" alt="screen shot 2018-06-07 at 10 37 24" src="https://user-images.githubusercontent.com/849604/41088086-db7da99c-6a3e-11e8-8be9-627c0c0cd7c6.png">

... and assigned it the device variable `hostname` ...

<img width="1214" alt="screen shot 2018-06-07 at 10 34 08" src="https://user-images.githubusercontent.com/849604/41088095-e27935b8-6a3e-11e8-90e1-00bc7eb47cbb.png">

... the IP address was **not automatically** passed to the script by Cacti.

I deleted the graph and data sources created with this template and activated the checkbox in the Data Source template:

<img width="546" alt="screen shot 2018-06-07 at 10 39 34" src="https://user-images.githubusercontent.com/849604/41088183-212bf5de-6a3f-11e8-9593-420d07a1836c.png">

Then I recreated the graphs again, for each device.

Now I have to provide the IP address of each device when creating the graphs (which is silly, because Cacti already knows this attribute), but then at least the value gets properly passed to the script.

What am I doing wrong?

Thank you & best regards
Mario

**Comment by SergejLT** [comment]
It is opposite. You need to untick in Custom Data "IP Adress of Server". Then ds will take IP of your hostname automatically.

**Comment by netniV** [comment]
What does the poller cache have for that device?  Please provide a copy of it as it shows what it would try and send to the script.  Also, it should be noted that you used the field hostname, not ip but as long as that's what you've entered in the hostname field, it should work.

You may also try rebuilding the poller cache.

**Comment by cigamit** [comment]
@emeidi was correct, you should only tick that box if you want to overwrite a setting.  For the ip address of the hostname for example, you should always keep it unticked.

**Comment by eschoeller** [comment]
Funny, I am having some problems with this right now myself. For whatever reason the 'hostname' attribute is simply blank no matter what I've tried. Running 1.1.38 and building a new template. 
The debug output shows this:
`2018/06/26 21:30:47 - SPINE: Poller[1] Device[8] TH[1] DS[84] SCRIPT: perl /cacti/cacti-1.1.38-test/scripts/query_cellwatch.pl --hostname  --temperature, output: U`
And I have the data input method setup like this:
![image](https://user-images.githubusercontent.com/12864741/41951688-6138ae34-7989-11e8-8203-ac1066be7389.png)
![image](https://user-images.githubusercontent.com/12864741/41951694-6e8d0cce-7989-11e8-8e84-eae46f5742b0.png)
No idea what is causing this problem. I've rebuilt the poller cache plenty of times. I still get this:
![image](https://user-images.githubusercontent.com/12864741/41951731-9c6d7b2e-7989-11e8-9fea-156da8afe278.png)

**Comment by eschoeller** [comment]
And I have a valid IP address set in the "hostname" field for the device. I've tried with having SNMP enabled, and disabled. No difference. I've deleted and added the host back in several times.

**Comment by netniV** [comment]
Does the standard Unix - Ping Host data query work with this host?  That also specifies a hostname field as a parameter.

**Comment by eschoeller** [comment]
Yes, the Unix - Ping Host works. But there is an odd bug here. I started to replace parts of the Unix - Ping Host data input method to match my own data input method I was trying to create, and it mostly worked - until I changed "\<ip>" to "\<hostname>". Suddenly the Name of the data input method was changed to the Friendly Name of the first input field!
![image](https://user-images.githubusercontent.com/12864741/42009418-7121e7de-7a47-11e8-8484-ec8469e63d66.png)
And now it is broken. Same as the data input method I had originally created. 
So I have gone back and decided to recreate the Data Input Method again. I am seeing this same strange behavior ... as I add more Output Fields the Name of the Data Input Method keeps changing to match the Friendly Name of the last Output Field I entered:
![image](https://user-images.githubusercontent.com/12864741/42009855-58cfbd76-7a49-11e8-9cc3-eddde23cd73d.png)
But now, finally after recreating the data input method (and not making any mistakes along the way), changing the data input method name back to what it should be after adding all the output fields, then re-associating it with the necessary data sources (which had to be disassociated first in order to delete the bad data input method) I have it working as expected. 
Moral of the story, you can't make any mistakes and great care and attention is required to work around this bug. I just don't know exactly what it is. The renaming of the Data Input Method is a good first start.

**Comment by eschoeller** [comment]
And I would bet money that if I change "\<ip>" to "\<hostname>" (which is I believe what I did originally to end up here) the whole thing would blow up again.

**Comment by eschoeller** [comment]
Oh, and this is happening firefox, but not in chrome.

**Comment by netniV** [comment]
Hmm, in that case, I wonder if Firefox is seeing the HTMl fields and doing something with it.  Lets check what you have in the database.

```sql
[10:33:07] (cacti) cacti1> select * from data_input_fields where data_name = 'hostname';
+----+----------------------------------+---------------+------------+-----------+--------------+------------+----------+-----------+--------------+-------------+
| id | hash                             | data_input_id | name       | data_name | input_output | update_rra | sequence | type_code | regexp_match | allow_nulls |
+----+----------------------------------+---------------+------------+-----------+--------------+------------+----------+-----------+--------------+-------------+
| 29 | 5fbadb91ad66f203463c1187fe7bd9d5 |            10 | IP Address | hostname  | in           |            |        1 | hostname  |              |             |
+----+----------------------------------+---------------+------------+-----------+--------------+------------+----------+-----------+--------------+-------------+
1 row in set (0.00 sec)

[10:33:48] (cacti) cacti1> select * from data_input where id in (10);
+----+----------------------------------+------------------+----------------------------------------------+---------+
| id | hash                             | name             | input_string                                 | type_id |
+----+----------------------------------+------------------+----------------------------------------------+---------+
| 10 | 8bd153aeb06e3ff89efc73f35849a7a0 | Unix - Ping Host | perl <path_cacti>/scripts/ping.pl <hostname> |       1 |
+----+----------------------------------+------------------+----------------------------------------------+---------+
1 row in set (0.00 sec)
```
In the second query, the (10) is a comma separated list of ids.  So if you had three rows from the first query of `1`, `40` and `52`, you would replace `(10)` with `(1, 40, 52)`.  If you do the same queries with both browsers, see if there is any change.

**Comment by netniV** [comment]
Closed due to no further response.

**Comment by eschoeller** [comment]
I am just getting back from being on vacation. I may make an effort to wrap my head around this again and respond to your post on 7/1. My apologies for dropping off the radar!

**Comment by krishnachaitanya9** [comment]
@eschoeller asked me to work on this. Here is the solution for guys who will be stumbling upon this link in the future:
First In the (Management -> Devices -> Your Custom Device Name)Device, have the hostname IP correctly indicated
![image](https://user-images.githubusercontent.com/9385832/83219044-8af27580-a12c-11ea-991d-1d54359d709f.png)
In my case, it's localhost (127.0.0.1) as shown in the above pic.

Next in the Data Input Method (Data Collection -> Data Input Methods -> Your custom Data Input Method -> Click on one of the input methods)

In the "Special Type Code" field input "hostname" as shown in the below pic. The input field name is "IP".
![image](https://user-images.githubusercontent.com/9385832/83219913-d9a10f00-a12e-11ea-86ef-d50c0ca8a87c.png)
Now in the Data Sources (Templates -> Data Sources -> Your Custom Data Source Name -> Input Method) data input method, keep the data input method blank
![image](https://user-images.githubusercontent.com/9385832/83220113-5c29ce80-a12f-11ea-99f6-3db63af00d99.png)
Which in my case it is "IP" is kept blank.

Save all and re-check the poller cache. The hostname is detected and passed to your script correctly.
