### ISSUE TITLE
Unkown RRDTool error

### ISSUE THREAD

**Issue by ktngoykalolo** [Cacti/cacti#1662]
Hi all,
I have a fresh install of cacti on Windows, and I have the following issues :

- I create graphs but I got the feedback : _Unkown RRDTool error_
- I checked the RRD files and they are not created. 

any indications of what could be the issue ?
I am running on cacti 1.1.38

**Comment by ktngoykalolo** [comment]
I have an improvement, it seems it is because the poller.php file is not running. 
I am looking into a way to get it running on a scheduled task.

**Comment by cigamit** [comment]
This isn't a bug, please submit these sort of help requests on the Cacti forums.  Thanks!
