### ISSUE TITLE
Cacti stopped graphing local host since last php-snmp update (rawhide)

### ISSUE THREAD

**Issue by david-hill** [Cacti/cacti#1663]
Cacti stopped graphing local host since last php-snmp update (rawhide) ... Well that's the only thing I can see so far.   It loops with this error message since approximately the time of the upgrade:

2018/06/08 23:40:03 - POLLER: Poller[1] Device[2] STATUS: Device '127.0.0.1' is UP.
2018/06/08 23:40:03 - POLLER: Poller[1] Device[2] RECACHE: Processing 2 items in the auto reindex cache for '127.0.0.1'.
2018/06/08 23:40:03 - POLLER: Poller[1] ASSERT: '395522<0:1:10:37.62' failed. Recaching host '127.0.0.1', data query #1
2018/06/08 23:40:03 - POLLER: Poller[1] Device[2] NOTICE: Spike Kill in Effect for '127.0.0.1'.
2018/06/08 23:40:03 - POLLER: Poller[1] ASSERT: '395547<0:1:10:37.62' failed. Recaching host '127.0.0.1', data query #6
2018/06/08 23:40:03 - POLLER: Poller[1] Device[2] NOTICE: Spike Kill in Effect for '127.0.0.1'.

It's as if the net-snmp timestamp was converted in a given way but when compared to the content of the databse, the timestamp is converted to something like "hours:minutes:seconds.ms" instead of the timestamp and it never matches.

Packages:
    Upgraded php-snmp-7.2.6-1.fc29.x86_64                               @rawhide
    Upgrade           7.2.7~RC1-1.fc29.x86_64                           @rawhide

**Comment by david-hill** [comment]
Well well well.   It appears like doing this:
              if (($assert_fail) &&
                (($index_item['op'] == '<') || ($index_item['arg1'] == '.1.3.6.1.2.1.1.3.0'))) {
                /* don't spike kill unless we are certain */
                if (!empty($output)) {
                  //$set_spike_kill = true;

                  //cacti_log("Device[$host_id] NOTICE: Spike Kill in Effect for '" . $item['hostname'] . "'.", $print_data_to_stdout, 'POLLER', debug_level($host_id, POLLER_VERBOSITY_DEBUG));
                }
              }

"solved" the problem.

**Comment by netniV** [comment]
I'm not sure that solved the problem, rather hid the problem.

**Comment by david-hill** [comment]
Yeah I agree with you here, I put it between quotes just because of that.  It's not really solved hence it's "solved" ...  

I only have this issue with the local snmp polling but the remote snmp polling works as expected for my other nodes.   Before opening this bug, I restarted snmpd and crond because the poller runs every 5 minutes in the polling.  What I don't understand is why I get this assertion ?  The indexed time will always be lower than the current running time no ?

**Comment by netniV** [comment]
I believe this to have been fixed:
https://github.com/Cacti/cacti/issues/1634

So, I'm going to close it for now since you have your own solution but when 1.2 is released then the full fix will be available.
