### ISSUE TITLE
Selecting a graph to add to Tree Items should be a drill-down process.

### ISSUE THREAD

**Issue by NotAProfessionalDeveloper** [Cacti/cacti#1666]
(Enhancement)

In Management - Trees:

Currently all available devices and graphs are always shown.

It would make more sense once a device has been selected (or a filter applied) to only show the graphs belonging to that device.

You should still be able to not filter for devices and search for graphs directly (as it is now).

**Comment by netniV** [comment]
There is a change in 1.2 for the graph/device tree process.  I will have to check if that's what you've described but I do think it's been made into a more simplified process.

**Comment by cigamit** [comment]
The number of Graphs, Devices, Sites shown is controlled by setting.  Not all rows are shown, and you can query using the filter to reduce the number.  But it is certainly not the total number unless you have asked for it to be displayed that way.  What theme are you using by the way?

**Comment by netniV** [comment]
Closing due to lack of feedback.

**Comment by jmroth** [comment]
Lack of feedback? What exactly would you like to know? What theme I am using? What would that have to do with anything? It's the default theme BTW.

**Comment by cigamit** [comment]
I know what this is about.  It's a mirror of what we did with Dual pane that was removed in 1.x since it was essentially broken in 0.8.x.  It's more an analog of how the tree works in Grafana.  So, I'll mark this as a feature enhancement and re-open.  It won't happen in 1.2 which is scheduled for beta within the week.

**Comment by TheWitness** [comment]
This was delivered via a pull request some time ago.
