### ISSUE TITLE
Reapplying suggested names on "old" graphs breaks title

### ISSUE THREAD

**Issue by jmroth** [Cacti/cacti#1667]
After reapplying suggested names to graphs that have existed in Cacti 0.x (or early 1.x versions) changes their title to the raw template string. The title in the graph itself is still correctly expanded from the template.

![image](https://user-images.githubusercontent.com/277893/41364493-2b91419e-6f37-11e8-9c96-99ffc02f88c7.png)

**Comment by pautiina** [comment]
Double and fixed on:https://github.com/Cacti/cacti/issues/1614
