### ISSUE TITLE
Graphs page doesn't load unless I refresh manually

### ISSUE THREAD

**Issue by chennasathish** [Cacti/cacti#1668]
Hello Guys,

I have updated Cacti from 0.8.8a to 1.1.38. After upgrade, everything works fine except the below:

1. Whenever I switch to Graphs page, the page goes blank. I need to refresh the page manually to get the graphs
2. Once the graphs page is loaded, the graphs are refreshed continuously. I tried updating the "Real-time Graphs" under "Console => Configuration => Settings=> Visual => Real-time Graphs", but no luck.

Request you to check and suggest.

Thank you in advance !!!

**Comment by chennasathish** [comment]
Adding to the mentioned:
I don't see any errors in cacti.log. But, I do see errors in "/var/log/httpd/access_log".

Whenever I switch to graphs page, error message with "header=false" gets continuously appended.
And, this gets stopped when I manually refresh the page.

GET /cacti/graph_view.php?header=false&header=false&header=false

**Comment by netniV** [comment]
That last problem is one I have already identified and fixed for 1.2.  The other uses JavaScript to refresh dependant on your settings of the Refresh option.

**Comment by chennasathish** [comment]
Could you please let me know how can I get/update my instance with this fix

**Comment by chennasathish** [comment]
Thank you for the update. I have updated my instance with 1.2v, With this, the 1st issue was resolved.

But, I could see the below messages in "/var/log/httpd/access_log" that contains "header=false" info when I access graphs page. As a result, the graphs page is continuously getting refreshed. And, the moment i apply a graph filter, I don't see "header=false"and the issue gets resolved. Could you please check and suggest.

================================================
"POST /cacti/index.php HTTP/1.1" 302 - "http://myserver.abc.com/cacti/index.php"
"GET /cacti/graph_view.php HTTP/1.1" 200 14667 "http://myserver.abc.com/cacti/index.php"
"GET /cacti/graph_view.php?action=get_node&tree_id=0&id=%23 HTTP/1.1" 200 678 "http://myserver.abc.com/cacti/graph_view.php"
"GET /cacti/graph_view.php?action=tree&header=false HTTP/1.1" 200 2375 "http://myserver.abc.com/cacti/graph_view.php"
"GET /cacti/graph_view.php?action=get_node&tree_id=0&id=tree_anchor-11 HTTP/1.1" 200 569 "http://myserver.abc.com/cacti/graph_view.php"
"GET /cacti/graph_view.php?action=tree_content&header=false HTTP/1.1" 200 2983 "http://myserver.abc.com/cacti/graph_view.php"
"GET /cacti/graph_view.php?action=get_node&tree_id=0&id=tbranch-3139 HTTP/1.1" 200 201 "http://myserver.abc.com/cacti/graph_view.php"
"GET /cacti/graph_view.php?action=tree_content&header=false HTTP/1.1" 200 2983 "http://myserver.abc.com/cacti/graph_view.php"
"GET /cacti/graph_view.php?action=get_node&tree_id=0&id=tbranch-3140 HTTP/1.1" 200 512 "http://myserver.abc.com/cacti/graph_view.php"
"GET /cacti/graph_view.php?action=tree_content&header=false HTTP/1.1" 200 2983 "http://myserver.abc.com/cacti/graph_view.php"
"GET /cacti/graph_view.php?action=tree_content&node=tbranch-3146&site_id=-1&host_id=-1&host_template_id=-1&hgd= HTTP/1.1" 200 25921 "http://myserver.abc.com/cacti/graph_view.php"
"GET /cacti/graph_view.php?action=tree_content&header=false HTTP/1.1" 200 25773 "http://myserver.abc.com/cacti/graph_view.php"
================================================

**Comment by netniV** [comment]
The header=false is automatically appended when the call being made is effectively an ajax call. That is normal.  It has little to do with automatic refresh.  However, I will try and test it out over the weekend to see whether there is any issue that I can see.

**Comment by netniV** [comment]
I didn't see anything.  Can you get a screen capture of the steps you make including the cursor movement?  Use a screen to gif program if you can and upload the output here.

**Comment by chennasathish** [comment]
I suspect some issue with http/dependency configurations. So, I provisioned a new server and configured cacti along with other dependencies. It worked fine without any issues. 

Thank you once again for all the assistance.
