### ISSUE TITLE
Console log header grammar issue

### ISSUE THREAD

**Issue by jmroth** [Cacti/cacti#1669]
"No Other Filter in Affect" ??? --> "No other filter active" (or "Unfiltered"?) (or don't mention this at all)

"Additional Filter in Affect" --> "Additional filter active" (or just "Filter active", maybe in bold, if no mention of no filters as suggested above)

**Comment by netniV** [comment]
I hear what you are saying about the language of the filter.  I presume this was on the logs screen or is on others too?

**Comment by cigamit** [comment]
Resolved.  Thanks for reporting.

**Comment by jmroth** [comment]
I took a look at the commit.
Is it possible that you mixed up the changes?

**Comment by cigamit** [comment]
Yea, just re-fixed it.
