### ISSUE TITLE
fontawesome-webfont - Failed to load resource

### ISSUE THREAD

**Issue by BSOD2600** [Cacti/cacti#167]
Chrome 55 reporting the following on http://localhost/cacti/data_sources.php 

```
http://localhost/cacti/include/fa/fonts/fontawesome-webfont.woff2?v=4.6.3 Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost/cacti/include/fa/fonts/fontawesome-webfont.woff?v=4.6.3 Failed to load resource: the server responded with a status of 404 (Not Found)
```

Files do appear to be present:
![image](https://cloud.githubusercontent.com/assets/5741811/21754396/eda21174-d5b3-11e6-9766-32efca92de97.png)

**Comment by cigamit** [comment]
We are going to defer this one.

**Comment by cigamit** [comment]
Making this a pure enhancement.  It is not a show stopper for now.

**Comment by BSOD2600** [comment]
Firefox 49 also reports this error
```
downloadable font: download failed (font-family: "FontAwesome" style:normal weight:normal stretch:normal src index:1): status=2147746065 source: http://localhost/cacti/include/fa/fonts/fontawesome-webfont.woff2?v=4.6.3font-awesome.css:7:12
downloadable font: download failed (font-family: "FontAwesome" style:normal weight:normal stretch:normal src index:2): status=2147746065 source: http://localhost/cacti/include/fa/fonts/fontawesome-webfont.woff?v=4.6.3font-awesome.css:7:12
```

**Comment by cigamit** [comment]
This is a Web Server configuration issue.  Please follow the approximate resolution on the page below.  It seems like a packaging issue.

https://github.com/FortAwesome/Font-Awesome/issues/5559

**Comment by cigamit** [comment]
Maybe this should be in the documentation.

**Comment by cigamit** [comment]
This issue was fixed upstream in fontawesome some time ago.

**Comment by tamilselvank** [comment]
Node JS: Install the below command
npm i --save @fortawesome/fontawesome
