### ISSUE TITLE
Improve Graph Management to show type of source for a graph

### ISSUE THREAD

**Issue by jmroth** [Cacti/cacti#1670]
Graph Management dialog shows template names that don't correspond to anything.

Also, the template names shown when using "Change graph template" don't correspond to any actual graph template either.

This is Cacti 1.1.38 upgraded from early 1.x. (Not sure if this bug existed previously, as only currently I'm again intensively using Cacti.)

![image](https://user-images.githubusercontent.com/277893/41480422-bdb57dfe-70ce-11e8-9d2e-7de9ab2a2470.png)

**Comment by jmroth** [comment]
I've another example.

I've got two graphs 
"web02 - Disk Space - /dev/sda1"
and 
"data02 - Used Space - /"

and for both the GUI refers to a template called "Available Disk Space".

graph_templates_graph -> title_cache = "web02 - Disk Space - /dev/sda1" --> graph_template_id 21
graph_templates: graph_template_id = 21 --> Unix - Available Disk Space

graph_templates_graph -> title_cache =  "data02 - Used Space - /"  --> graph_template_id 26
graph_templates: graph_template_id = 26 --> Host MIB - Available Disk Space

For both items the GUI however shows a template called "Available Disk Space" which seems to be a string occuring in the "snmp_query_graph" table in the "name" column, where it refers to graph_template_id 21 and 26, respectively....

I've tried to reproduce in a vanilla 1.2.0 install where I added disk space checks to localhost. While there are no duplicates (because the new install has less queries configured), it is also not showing the actual template name, but the stuff from the snmp_queries table.....

**Comment by cigamit** [comment]
In Cacti 1.x, for Data Queries, we use the Data Query associated Graph Template name and not the actual Graph Template name.  In prior versions of Cacti it was very easy for the names to be different as there was no helper function.  This is a change from Cacti 0.x releases.

**Comment by jmroth** [comment]
That is very confusing. I guess it is a consequence of retrofitting the data queries into the existing architecture at some point.

How can we make this more understandable to newbies and existing users alike? I propose the following:

1) The top of the page containing the "Template" dropdown (and all others places reading "Template" where actually "Template/Query" is meant, like table headers etc.) should be changed and read what it is: "Template/Query" (or a new description should be devised).

2) "Templates" derived indirectly from Queries should be displayed differently than those derived directly from Data Input Methods. I propose a simple measure: adding for example an asterisk (*) behind those derived from queries. At least that would help distinguish what is what. You could even add a tooltip (text appears when hovering the element) displaying the actual graph template behind that associated query name. I guess the data is there, we just need to display it.

What do you think?

This really needs to be discussed.

**Comment by cigamit** [comment]
Yea, having some visual indicator that it's Data Query based vs. a Raw Template sounds like a good idea.  Yes, and it's a little confusion, I have to admit that.

**Comment by netniV** [comment]
I have made an update that will show the type of source for a given graph:

![image](https://user-images.githubusercontent.com/9052188/42951493-30586128-8b6e-11e8-803d-a61b96c04d69.png)

**Comment by netniV** [comment]
We have now merged this into 1.2's development.
