### ISSUE TITLE
Duplicate Graph Template does not duplicate Data Query Graph Template Mappings

### ISSUE THREAD

**Issue by jmroth** [Cacti/cacti#1671]
How to reproduce:
* Duplicate the "available disk space" template for example.
* Goto a graph created using the original template and use "change graph template".
* The previously duplicated and otherwise unchanged graph template cannot be selected even though it is identical. Only the original template is shown in the "New Graph Template" dropdown.

**Comment by cigamit** [comment]
When changing the Graph Templates all the Data Source names must identical as must the count.  If not, then it will not be permitted to be changed.

**Comment by jmroth** [comment]
So from my initial description would that be the case or not when trying to change to a template that was duplicated from the initial template and not modified?

![image](https://user-images.githubusercontent.com/277893/41498868-0211ec36-7178-11e8-8dd1-2019bda56e00.png)

**Comment by cigamit** [comment]
Okay, I did an audit of the code and found that the duplication of the template does not duplicate any data query graph associations.  This is why, for this data query, you don't see any other options.  The step that was no replicated, and I'm thinking that is the real bug, is that when you duplicate the Graph Template (that is used in a Data Query), you should also duplicate the Data Query associations.

Near term, you should make those Data Query associations manually, and then you will be able to 'change graph template'.  I did also find some minor issue that I will be making commit's for shortly, but this has no impact on your issue.

**Comment by cigamit** [comment]
This issue is resolved now, but only for new Graph Templates that are duplicated.
