### ISSUE TITLE
Wrong french translation for "Last month" preset

### ISSUE THREAD

**Issue by louisvolant** [Cacti/cacti#1673]
Hi guys,

I've seen that your translation for "Last month" in the preset is wrong.

In French, Month=> Mois with an S at the end :
![image](https://user-images.githubusercontent.com/195804/41664806-d5e2c59a-74a6-11e8-8f54-e6d54377f262.png)

Thanks !

**Comment by netniV** [comment]
Would you be willing to look over the translations and double check them all in the current development branch?

**Comment by netniV** [comment]
Hi @louisvolant would you be able to review the translations?  These can be found in locales/LC_MESSAGES/french_france.mo

**Comment by netniV** [comment]
Hi @louisvolant, just thought I'd try to reach out to you again to see if you would be able to help with our french translations?

**Comment by louisvolant** [comment]
Hi @netniV, didn't have time to do it yet, please ask me again in 1 month if you remember.

**Comment by netniV** [comment]
Thanks @louisvolant, will do.  Be a better time then as we should have stopped any new features going into 1.2 at the point so text/prompts shouldn't be changing.
