### ISSUE TITLE
Automation not creating devices with same sysname

### ISSUE THREAD

**Issue by holbor** [Cacti/cacti#1676]
I'm using 1.2.0 and setup automation to scan a network with Motorola Cable Modems.  I get the following log messages.

Found 'Test-Motorola1.cm.mydomain.net', Status: Not in Cacti, Ping: Responded, SNMP: SB6121, Skipping sysName 'SB6121' already in Cacti!

I've done this  number of times previously and am open to having missed a step or checkbox, but cannot for the life of me figure out where.  As you can see DNS is reporting a different name.  In past releases I believe it's used the DNS name for the title.

/rh

**Comment by netniV** [comment]
The DNS name is not necessarily the sysName.  sysName is reported by SNMP which on linux can be manually configured to have it's own name.  Check the SNMP settings on the device in question and make sure that the system name matches the hostname.

**Comment by holbor** [comment]
Thanks, I get that.. I've _thousands_ of these cable modems and we don't set the sysname on them ever.  Previous versions of either Discovery or Automation have not cared whether the sysname is the same and have used the DNS name when adding them.  Like I said... could be something I missed, but I don't recall having to set anything in previous versions of Cacti to make discovery for these work.
/rh

**Comment by holbor** [comment]
Anyone?? Really need discovery to work.  
I went and checked and I have a version of 8.8b running the old plugin and tons of the sysnames are the same, so this is definitely a change.
/thanks

**Comment by netniV** [comment]
I have made changes which I was QA'ing today.  These will be in 1.2 development branch

**Comment by holbor** [comment]
Just an update to say that this change did resolve and now I have devices being created via automation.  Still getting following errors in log but graphs are created.
/thanks

2018/07/11 14:19:16 - CMDPHP PHP ERROR NOTICE Backtrace: (/poller_automation.php: 350 discoverDevices)(/poller_automation.php: 592 CactiErrorHandler)(/lib/functions.php: 4733 cacti_debug_backtrace)
--
2018/07/11 14:19:16 - ERROR PHP NOTICE: Undefined index: same_sysname in file: /var/www/html/cacti/poller_automation.php on line: 592

**Comment by netniV** [comment]
As per my other post, that would be because if you have already running 1.2, you have to manually apply the db upgrade.  Or you can also run the upgrade_database.php script using the forcever option to force it to reapply the 1.2 updates.
