### ISSUE TITLE
Data Sources - Unable to delete

### ISSUE THREAD

**Issue by BSOD2600** [Cacti/cacti#168]
1) select a data source
![image](https://cloud.githubusercontent.com/assets/5741811/21754403/2e7955fe-d5b4-11e6-8b08-4d3de2e9971e.png)

2) select action: Delete.  
The row becomes unhighlighted. None of the rows are now selectable.
![image](https://cloud.githubusercontent.com/assets/5741811/21754406/4cb15242-d5b4-11e6-8e2d-ad45617a2dd1.png)

3) click Go. receive error: You must select at least one data source.
![image](https://cloud.githubusercontent.com/assets/5741811/21754408/6123a93c-d5b4-11e6-815f-f38c90cb418e.png)

**Comment by BSOD2600** [comment]
Same problem for trying to delete Data Queries.

**Comment by cigamit** [comment]
Data Sources can not be deleted when there are graphs that are consuming them.  Note that this is a change in bahavior.  Notice also the 'Deletable' column is set to 'No'.  So, this is expected behavior.
