### ISSUE TITLE
Enhancement: Allocate neccessary amount of device threads / consolidate availability checks

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#1680]
I created a device which currently has 1 data source. But I set the device threads to '6'. (it will eventually have more data sources). 
I found that even while the device has just 1 data source spine still created 6 threads. The first thread spawned a device availability check and then executed a script to collect some data. The remaining 5 threads all spawned additional availability checks but then did nothing else. 
I'd think that we could achieve a performance/resource boost by intelligently allocating the right number of threads, even if the user has specified 6 threads (say it's a global setting or standard) that doesn't mean 6 threads should be created - especially if the number of data sources being queried for that polling cycle is less than the overall thread count for that device. 
Second, I'm not sure why each thread needs to execute an availability check. This is certainly resource hungry for both the polling machine and the device itself. Couldn't a single availability check be executed and that result is shared between all the threads?

**Comment by cigamit** [comment]
Well that is odd.  Can you please create this bug in the spine repo though.  I'm going to close here, but it should be pretty easy to accomplish.
