### ISSUE TITLE
Slow Select Statement lib/api_automation.php

### ISSUE THREAD

**Issue by MatJ13** [Cacti/cacti#1682]
Hello,

We have an estate of 12k switching and routing devices in Cacti and whilst it was discovering all our devices and adding graphs our server was maxing CPU on 2 x 22 cores. We noticed the main culprit was Mysql and viewing 'show full processlist' it showed that the below SQL statement was the main culprit. In the code it's being executed in the function "create_dq_graphs":

SQL:
```SELECT DISTINCT field_name FROM host_snmp_cache AS hsc WHERE snmp_query_id= 2;```

PHP: 
```
$field_names = db_fetch_assoc_prepared('SELECT DISTINCT
    field_name
    FROM host_snmp_cache AS hsc
    WHERE snmp_query_id= ?',
    array($snmp_query_id);
```

For reference 'snmp_query_id' 2 our system is the SNMP - Interface Query which is on every single device in Cacti but the field names would be the same for all. 

The query was being repeatedly executed and in some cases SQL was waiting for 50+ seconds for a query cache lock, only to get the exact same information back for each host...  Given the repetitive nature of the field names in this table a select distinct without a host_id means a very large set to derive unique entries from. I have found altering the query to provide the host id field stopped us maxing all the cores out auto-creating graphs. See altered code below:

```
$field_names = db_fetch_assoc_prepared('SELECT DISTINCT
    field_name
    FROM host_snmp_cache AS hsc
    WHERE snmp_query_id= ? AND host_id= ?',
    array($snmp_query_id, $host_id));
```
Comparison in speed, not using cache and with the server under no load:

```
MariaDB [cacti]> SELECT COUNT(*) FROM host_snmp_cache;
+----------+
| COUNT(*) |
+----------+
|  3389773 |
+----------+

```
```
MariaDB [cacti]> SELECT SQL_NO_CACHE DISTINCT field_name  FROM host_snmp_cache AS hsc  WHERE snmp_query_id=2;
+----------------------------+
| field_name                 |
+----------------------------+
| ifAlias                    |
| ifCIR                      |
| ifDescr                    |
| ifHighSpeed                |
| ifHwAddr                   |
| ifIndex                    |
| ifIP                       |
| ifIPv6                     |
| ifName                     |
| ifOperStatus               |
| ifSpeed                    |
| ifType                     |
| vlanTrunkPortDynamicStatus |
+----------------------------+
13 rows in set (1.78 sec)
```

```
MariaDB [cacti]> SELECT SQL_NO_CACHE DISTINCT field_name  FROM host_snmp_cache AS hsc  WHERE snmp_query_id=2 and host_id=43;
+----------------------------+
| field_name                 |
+----------------------------+
| ifAlias                    |
| ifCIR                      |
| ifDescr                    |
| ifHighSpeed                |
| ifHwAddr                   |
| ifIndex                    |
| ifIP                       |
| ifName                     |
| ifOperStatus               |
| ifSpeed                    |
| ifType                     |
| vlanTrunkPortDynamicStatus |
+----------------------------+
12 rows in set (0.00 sec)
```

Can someone check this and perhaps add this into the next release please. Perhaps it would be even more efficient to cache the result of the statement somewhere - the field names would only require checking once and apply to all hosts would they not?

Appreciate all the effort from everyone contributing so far - Many Thanks

**Comment by netniV** [comment]
Unfortunately not.  The cache is per host because each host could be a different device.  Whilst we do tend to retrieve the same information, as far as I am aware different systems may present different fields. It may be something that could be done per template rather than per host but that would be quite a change.  Not sure if that's something being considered  yet.

**Comment by cigamit** [comment]
Use the following alter statement and see if the timing changes:

`alter table host_snmp_cache add index snmp_query_id_host_id (snmp_query_id, host_id);`

Let us know if the numbers are better.

**Comment by cigamit** [comment]
After a code review, I see you point.  Good catch.  Resolved.
