### ISSUE TITLE
Cacti alert to the Line

### ISSUE THREAD

**Issue by panhala** [Cacti/cacti#1683]
Does anyone tell me how to send alert to the line such as image below?
![image](https://user-images.githubusercontent.com/11862935/42025647-49b6ba6e-7aef-11e8-8b86-2e58f83ca736.png)

**Comment by panhala** [comment]
I use Threshold and monitor to provide alerts for abnormal values and for hosts that are downed or rebooted. Then send the abnormal activities to the gmail. when I search the Internet, I saw that they can send the alert to the Line App but I don't know how to do it. could you tell me about this one?

**Comment by netniV** [comment]
If the Line App accepts emails as a source for alerting, you just need to have the address configured as a recipient.  However, a few people have asked for a way to alert via more mediums than just email but this will require changes to the core of Cacti I think or an additional plugin which handles this.

**Comment by cigamit** [comment]
This would appear to be a pre-cacti 1.x issue.  We actually are not presently supporting the manage plugin.  Have you contacted that plugins author?
