### ISSUE TITLE
Add Ip as a prefix if duplicated by sysName in Automation Networks

### ISSUE THREAD

**Issue by Slawka** [Cacti/cacti#1684]
Add to **Network Discovery Range [edit:** the ability to add ip to sysName in case of duplication.
Add a checkbox:, Add Ip as a prefix if duplicated by sysName
sysName-IP

**Comment by netniV** [comment]
Issue #1694 covers this same sort of thing.  This could be an extension of that by offering a different mode of operation eg:

- Allow Dupes
- Prefix Dupes
- Prevent Dupes

**Comment by TheWitness** [comment]
Closing this one.
