### ISSUE TITLE
Missing index in Aggregate graph

### ISSUE THREAD

**Issue by sedennial** [Cacti/cacti#1686]
Having an issue creating aggregate graphs. I've tested with just single graphs as the source (a simple CPU graph, and also a single interface graph), and with multiple graphs of the same type (64 bit interface with total bandwidth).

The initial error (I think all following errors are related) is that the `$rra['steps']` array index isn't defined.

> 2018/07/02 17:20:49 - CMDPHP PHP ERROR NOTICE Backtrace: (/graph.php: 266 CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)
> 2018/07/02 17:20:49 - ERROR PHP NOTICE: Undefined index: steps in file: /usr/share/cacti/site/graph.php  on line: 268

Mysql logging shows that the SQL queries in graph.php:268 and 283 are returning null values.

> 2018-07-02T23:22:43.254474Z      2167 Query     SELECT  data_template_data.rrd_step  FROM (data_template_data,data_template_rrd,graph_templates_item)  WHERE graph_templates_item.task_item_id=data_template_rrd.id  AND data_template_rrd.local_data_id=data_template_data.local_data_id  AND graph_templates_item.local_graph_id = '1789'  LIMIT 1
> 
> mysql> SELECT  data_template_data.rrd_step  FROM (data_template_data,data_template_rrd,graph_templates_item)  WHERE graph_templates_item.task_item_id=data_template_rrd.id  AND data_template_rrd.local_data_id=data_template_data.local_data_id  AND graph_templates_item.local_graph_id = '1789'  LIMIT 1;
> Empty set (0.00 sec)

![cacti-agg-settings-1](https://user-images.githubusercontent.com/22405156/42227160-b58edf10-7e95-11e8-81d3-604c14289dec.PNG)
![cacti-agg-timestamp-rrdsyntax](https://user-images.githubusercontent.com/22405156/42227162-b5afe7dc-7e95-11e8-9ce1-667cef58eb23.PNG)

> Cacti Version   1.1.38
> Cacti OS   unix
> NET-SNMP Version   NET-SNMP version: 5.7.3
> RRDtool Version   RRDtool 1.7.x
> Devices   21
> Graphs   1790
> 
> PHP Version   7.2.5-0ubuntu0.18.04.1
> PHP OS   Linux
> PHP uname   Linux cacti 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64
> PHP SNMP   Installed
> 
> Mysql Version: 5.7.22-0ubuntu18.04.1

**Comment by cigamit** [comment]
Could you please post the parameters section of the graph rendering page.  I'm looking for the rra_id, local_graph_id, etc from the request.  You can find this on the browsers debug page on the network subpage and then select the graph.php callback.

**Comment by cigamit** [comment]
No feedback.
