### ISSUE TITLE
Graph aggregation and 95th issues

### ISSUE THREAD

**Issue by blackboar** [Cacti/cacti#1687]
Cacti Version 1.1.38

Why does the 95th disappear after the graphics are aggregated?

![1](https://i.loli.net/2018/07/03/5b3add15bdaf0.png)

![2](https://i.loli.net/2018/07/03/5b3addfe5e171.png)

![2](https://i.loli.net/2018/07/03/5b3add15c71fa.png)

**Comment by netniV** [comment]
Have you checked #1656, #1600, #900 and #871 to see if they answer your question?

**Comment by taozongwang** [comment]
the same issue,it's 95th appeared in an interface,but when I aggregate with all interface and 95th disppeared. I don't what happened it.
Cacti Version 1.1.38

**Comment by netniV** [comment]
Hi @taozongwang did you check those previous issues? Are they what you are experiencing?

**Comment by taozongwang** [comment]
Hello @netniV Sorry,I checked previous issues,and updated rrdtool from 1.4.8 to 1.7.0,but the issue again.
 I need |95:bits:0:aggregate_max:2| and (|95:bits:6:aggregate_sum:2| mbit in+out). when i aggregated but the selection box is still gray。

**Comment by cigamit** [comment]
Please test under the develop branch.  This issue was resolved, or at least I thought it was.

**Comment by cigamit** [comment]
No feedback.

**Comment by ryswork1993** [comment]
> 您好@netniV对不起，我检查过以前的问题，并将rrdtool从1.4.8更新到1.7.0，但问题再次出现。
> 我需要| 95：位：0：aggregate_max：2 | 和（| 95：位：6：aggregate_sum：2 | mbit输入+输出）。当我聚合但选择框仍然是灰色的。

I am also the same problem. After adding the aggregated graphic, there is no 95 value. The item of the aggregated graphic cannot be edited. Can you solve it?

**Comment by superkily086** [comment]
Did you solve it?I have the same  problem.

**Comment by superkily086** [comment]
请问楼主解决问题了吗，我搞研究了好久依然没有搞定，求指导。
