### ISSUE TITLE
Settings Save followed by clicking Logs tab

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1688]
There is a bug where you can click on Save in the settings window and as it is reloading, the logs tab can be clicked.  If the logs tab returns faster than the Settings window, it is possible to be on the logs tab with the settings displayed (as would normally happen from just the save).

Reloading the window does resolve the issue.  May the introduction of a modal overlay to simulate an action is occurring with a spinner would help alleviate the chances of this.

**Comment by TheWitness** [comment]
This should have been resolved by the implementation of the $.ajaxQ.abortAll() function in loadTopTab().  So, this should no longer be an issue in 1.2.
