### ISSUE TITLE
RRDTool Says: <nothing>

### ISSUE THREAD

**Issue by BSOD2600** [Cacti/cacti#169]
Previous Cacti versions in graph debug, the RRDTool Says: would show "OK". Blank typically was a sign of issues (specifically permission issues on Windows). Notice its back to being blank, but the graph is working.  This the intended interaction now?

graph is working:
![image](https://cloud.githubusercontent.com/assets/5741811/21754459/6ea2194e-d5b5-11e6-8a99-4a6ae80545fc.png)
![image](https://cloud.githubusercontent.com/assets/5741811/21754465/8f599f0e-d5b5-11e6-9c57-49cbc3b8ee73.png)

**Comment by cigamit** [comment]
Ouch, that is a segfault.  Likely realted to RRDtool issue.  We won't fix for this release.  I remember this was an issues in the 1.2 branch of RRDtool.

**Comment by cigamit** [comment]
We need to upgrade RRDtool for the installer.

**Comment by BSOD2600** [comment]
using rrdtool 1.4.5... same ver for the last 5 years, lol. 
What should be shown?

**Comment by cigamit** [comment]
I can not reproduce this on Linux.  Can you reproduce this for all graphs?  Is it possible to instrument rrd.php or check the Application log for an rrdtool.exe crash?

**Comment by cigamit** [comment]
Resolved, thanks!
