### ISSUE TITLE
Feature Request - Add a 'Copy graph' option to context menu of graphs

### ISSUE THREAD

**Issue by StoneCut** [Cacti/cacti#1691]
It would be great if there a way to enable some sort of "copy image to clipboard" function in the context menu for graphs. This would be useful for a rather laborious report I need to generate. Using "Graph" -> "Open in new tab" and then choosing copy image there is rather tedious.

Alternatively, it would be nice to be able to disable the context menu altogether so I can simply right-click on the image and use the browser's built-in functions for this. Sort of like the really old behaviour.

Thank you!

**Comment by StoneCut** [comment]
Yes, that would be great.

**Comment by netniV** [comment]
I've had a quick check as this would be similar to the copy to clipboard feature I implemented on the Device Verbose Query sections. One caveat seems to be that it would have to be copied as HTML so would not necessarily paste directly into an image editor in the same way the standard right click menu would.

**Comment by netniV** [comment]
Apparently MSPaint should handle it so I will give it a go and see what happens.

**Comment by netniV** [comment]
No, JavaScript is specifically limited in this fashion because it will only allow you to copy out of the document tree and whilst an image is an element, it's not a normal image in the browser sense.

**Comment by netniV** [comment]
This is now in the development branch for 1.2
