### ISSUE TITLE
Cacti web interface still showing as old version after upgrade to new 1.1.38

### ISSUE THREAD

**Issue by b0b21** [Cacti/cacti#1693]
I've upgraded cacti from 1.1.19 to 1.1.38. Everything goes well and migration successful. I've copied all rra/ log/ cache/ resource/ scripts/ from old_cacti to new_cacti directory. Services (httpd, snmp, mysqld) are restarted too. But when browse http:cacti_ip/cact , web interface still showing as old version. I did restart the server and clear the browser cache as well. no luck :( 

Any suggestions and advises are welcomed! Thanks.

**Comment by pautiina** [comment]
Hello.
Please run on mysql shell next command and show hear:
```SELECT * FROM `version`  ```

**Comment by b0b21** [comment]
@pautiina Thank you for your reply. Output as below

mysql> select * from version;
+--------+
| cacti  |
+--------+
| 1.1.38 |
+--------+
1 row in set (0.00 sec)

mysql>

**Comment by pautiina** [comment]
It's strange. This is definitely somewhere in the cache or you did not change the directory path to the new version of Cacti on your httpd config file.

**Comment by b0b21** [comment]
Thanks @pautiina for your kind input. Now problem is solved! Actually nothing wrong with migration steps but "theme" set to classic view LOL ;) after change it to "modern" everything's ok.

Thanks again for your contribution.

Regards,
