### ISSUE TITLE
Unknown RDDtool error

### ISSUE THREAD

**Issue by boomerang11** [Cacti/cacti#1697]
I cannot create graph from cacti. I has error 

CMDPHP PHP ERROR WARNING Backtrace: (C:\xampp\htdocs\cacti\graphs_new.php: 37 form_save)(C:\xampp\htdocs\cacti\graphs_new.php: 123 host_new_graphs)(C:\xampp\htdocs\cacti\graphs_new.php: 397 host_new_graphs_save)(C:\xampp\htdocs\cacti\graphs_new.php: 266 push_out_host)(C:\xampp\htdocs\cacti\lib\utility.php: 650 poller_update_poller_cache_from_buffer)(C:\xampp\htdocs\cacti\lib\utility.php: 541 sizeof)(CactiErrorHandler)(C:\xampp\htdocs\cacti\lib\functions.php: 4585 cacti_debug_backtrace)
--
07/09/2018 11:24:11 - ERROR PHP WARNING: sizeof(): Parameter must be an array or an object that implements Countable in file: C:\xampp\htdocs\cacti\lib\utility.php on line: 541

cacti Version 1.1.38

**Comment by netniV** [comment]
This is because you are using PHP 7.2 which is not supported official by Cacti 1.1.38.  Only the development version 1.2 has had any work done to be 7.2 compatible.

**Comment by netniV** [comment]
Closed as this is covered by issue #1579

**Comment by boomerang11** [comment]
Thank you so much.
