### ISSUE TITLE
Cacti .88E superlinks pointing to a cacti 1.1.38 Tree

### ISSUE THREAD

**Issue by denalijb** [Cacti/cacti#1698]
We often link cacti servers via the superlinks plugin.  Upon placing the URL of the newer 1.1.38 Server in the .88 servers GUI for superlinks, we can't get the tree to display from the 1.1.38 system.

**Comment by netniV** [comment]
Can you provide more details of the link you are using and a screenshot of the effect you are having, plus what you should b having?

**Comment by denalijb** [comment]
Sure.  We have a number of cacti Installations that monitor cluster usage.  A few of them are a supported version of Cacti called RTM (read Larry Adams at IBM).  These run Cacti .88 and we install the SuperLinks (1.42) plugin to connect to other cacti installations monitoring other parts of the clusters.  The servers that are still .88 display correctly on the .88 server running SuperLinks 1.42, the cacti servers with 1.1.38 are not displaying content at all on the same .88 server with SuperLinks 1.42.  Attached are 2 screen shots from 2 tabs on the same server.  Fairshare_CYB02 points to a 1.1.38 installation, Fairshare_ATL02 points to a .88 installation.  
![superlinks 88___1 1 38cacti_cyb02](https://user-images.githubusercontent.com/41039640/42522703-1132c118-8429-11e8-9d0d-c68330c47ede.PNG)
![superlinks 88___ 88cacti_atl02](https://user-images.githubusercontent.com/41039640/42522704-1146cb9a-8429-11e8-96e5-1657f7122e71.PNG)
![cacti 88_superlinks_links_detail](https://user-images.githubusercontent.com/41039640/42522705-115cba72-8429-11e8-96dd-cd90ca2d7fce.PNG)

Cheers, thanks for any help.

Jeff

**Comment by denalijb** [comment]
Refused to display 'http://cybvmon00.amd.com/cacti/graph_view.php?action=tree&node=tree_anchor-2&hgd=&hyper=true' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

**Comment by netniV** [comment]
I would imagine this is part of recent XSS attack protections that has gone into the code.  There were a number of vulnerabilities found which were patched.  I can't find the specific point of entry right now because it was on the older develop branch which was merged into 1.2 as 6261531

**Comment by netniV** [comment]
You will find this in include/global.php as:
```php
header('X-Frame-Options: SAMEORIGIN');
```
You can comment this out if you like, but any upgrade would naturally reintroduce this.

**Comment by denalijb** [comment]
Thanks.  I will test this today.

**Comment by denalijb** [comment]
This essentially makes the superlinks tab on .88 into a link to the new system.  It's a usable workaround, but not necessarily ideal.  Is there a way to  keep the data in the frame on the .88b system when displaying from the 1.+?

**Comment by netniV** [comment]
1.x has the concept of external links.  Though I don't know that it keeps it in a frame.  That functionality is built into the core without need of a plugin.  The real question next would be if superlinks has an update to work under 1.x?

**Comment by netniV** [comment]
Are you still needing assistance on this @denalijb ?
