### ISSUE TITLE
cacti cannot plot graph

### ISSUE THREAD

**Issue by boomerang11** [Cacti/cacti#1704]
I cannot plot graph with cacti.It show error as below.

07/11/2018 10:23:33 AM - SYSTEM STATS: Time:1.3630 Method:cmd.php Processes:4 Threads:N/A Hosts:4 HostsPerProcess:1 DataSources:12 RRDsProcessed:6
--
07/11/2018 10:23:33 AM - CMDPHP: Poller[0] Host[4] DS[45] WARNING: Result from SNMP not valid. Partial Result: U
07/11/2018 10:23:33 AM - CMDPHP: Poller[0] WARNING: SNMP Get Timeout for Host:'x.x.x.x', and OID:'.1.3.6.1.2.1.31.1.1.1.10.61'
07/11/2018 10:23:33 AM - CMDPHP: Poller[0] Host[4] DS[45] WARNING: Result from SNMP not valid. Partial Result: U
07/11/2018 10:23:33 AM - CMDPHP: Poller[0] WARNING: SNMP Get Timeout for Host:'x.x.x.x', and OID:'.1.3.6.1.2.1.31.1.1.1.6.61'
07/11/2018 10:23:33 AM - CMDPHP: Poller[0] Host[3] DS[15] WARNING: Result from SNMP not valid. Partial Result: U
07/11/2018 10:23:33 AM - CMDPHP: Poller[0] WARNING: SNMP Get Timeout for Host:'x.x.x.x', and OID:'.1.3.6.1.2.1.2.2.1.16.10148'
07/11/2018 10:23:33 AM - CMDPHP: Poller[0] Host[3] DS[15] WARNING: Result from SNMP not valid. Partial Result: U
07/11/2018 10:23:33 AM - CMDPHP: Poller[0] WARNING: SNMP Get Timeout for Host:'x.x.x.x', and OID:'.1.3.6.1.2.1.2.2.1.10.10148'

**Comment by netniV** [comment]
Have you made sure you can query the host from the commandline using SNMPWALK?

**Comment by boomerang11** [comment]
Dear netniV
Now I have new issue with error "Unknown RRDtool Error"

RRDtool Command:
c:/rrdtool/rrdtool.exe graph - \ 
--imgformat=PNG \ 
--start="-86400" \ 
--end="-300" \ 
--pango-markup  \ 
--title="10.244.16.111 - Traffic - Vlan10/10" \ 
--vertical-label="bits per second" \ 
--slope-mode \ 
--base=1000 \ 
--height=150 \ 
--width=550 \ 
--rigid \ 
--alt-autoscale-max \ 
--lower-limit="0" \ 
--color BACK#F3F3F3 \ 
--color CANVAS#FDFDFD \ 
--color SHADEA#CBCBCB \ 
--color SHADEB#999999 \ 
--color FONT#000000 \ 
--color AXIS#2C4D43 \ 
--color ARROW#2C4D43 \ 
--color FRAME#2C4D43 \ 
--border 1 --font TITLE:11:"Arial" \ 
--font AXIS:8:"Arial" \ 
--font LEGEND:8:"Courier" \ 
--font UNIT:8:"Arial" \ 
--font WATERMARK:6:"Arial" \ 
--slope-mode \ 
--watermark "Generated by Cacti®" \ DEF:a="C\:/Apache24/htdocs/cacti/rra/10_244_16_111_traffic_in_1.rrd":"traffic_in":MAX \ DEF:b="C\:/Apache24/htdocs/cacti/rra/10_244_16_111_traffic_in_1.rrd":"traffic_in":AVERAGE \ DEF:c="C\:/Apache24/htdocs/cacti/rra/10_244_16_111_traffic_in_1.rrd":"traffic_out":MAX \ DEF:d="C\:/Apache24/htdocs/cacti/rra/10_244_16_111_traffic_in_1.rrd":"traffic_out":AVERAGE \ CDEF:cdefa="a,8,*" \ 
CDEF:cdefb="b,8,*" \ 
CDEF:cdeff="c,8,*" \ 
CDEF:cdefg="d,8,*" \ 
LINE1:cdefa#00CF00FF:""  \ 
AREA:cdefb#00CF007F:"Inbound "  \ 
GPRINT:cdefb:LAST:"Current\:%8.2lf %s"  \ 
GPRINT:cdefb:AVERAGE:"Average\:%8.2lf %s"  \ 
GPRINT:cdefb:MAX:"Maximum\:%8.2lf %s\n"  \ 
LINE1:cdeff#002A97FF:""  \ 
AREA:cdefg#002A977F:"Outbound"  \ 
GPRINT:cdefg:LAST:"Current\:%8.2lf %s"  \ 
GPRINT:cdefg:AVERAGE:"Average\:%8.2lf %s"  \ 
GPRINT:cdefg:MAX:"Maximum\:%8.2lf %s\n" 
RRDtool Says:

Mark : cacti Version 1.1.38
--

**Comment by netniV** [comment]
Did RRDTool report the cacti version or is that just what you have added?

**Comment by boomerang11** [comment]
I uninstall cacti and install cacti new version on windows server 2016.
***
cacti 1.138
rrdtool 1.4.x

**Comment by cigamit** [comment]
Looks like RRDtool is crashing.  I would paste that command into a shell and then redirect the output to a file.  Check that the RRDtool version on the Settings page matches your RRDtool version.  Looks like an rrdtool segfault though.

**Comment by boomerang11** [comment]
Dear cigamit ,
Did rrdtool 1.4 can support cacti 1.138?
Do you have rrdtool 1.7 for windows os?

**Comment by netniV** [comment]
Sources and binaries for RRD Tool can be downloaded from:
https://oss.oetiker.ch/rrdtool/download.en.html

**Comment by netniV** [comment]
Do you have cygwin installed?

**Comment by boomerang11** [comment]
Installed done.

**Comment by netniV** [comment]
Here is a small guide on compiling rrdtool: https://perceptionistruth.com/2012/01/compiling-rrdtool-on-cygwin/comment-page-1/

You may find others on the internet.

**Comment by boomerang11** [comment]
Thank you so much.

**Comment by cigamit** [comment]
It is supported, but that does not mean it's not bug free.  Building with Cygwin works perfectly.  Cygwin is pretty darn complete these days, you just have to get all the pre-requisites installed, which will take the most time.  If you want to keep it lean, then disable things like perl and ruby.  Running "./configure --help" will provide you all the prompts for enabling/disabling features.
