### ISSUE TITLE
Cacti SQL recommendations

### ISSUE THREAD

**Issue by christopher1991** [Cacti/cacti#1707]
Hello,

We have a large Cacti setup and like to optimize the SQL database. There is only a short documentation at: https://www.cacti.net/downloads/docs/html/unix_configure_cacti.html

1) Does Cacti support MySQL 8.0 and MariaDB 10.x
2) Recommendations for charset and collation (I guess UTF8 and utf8_bin)

Maybe you can add some documentation to the SQL section.

And a specific question: Our current setup uses latin1_swedish_ci as collation. What's the best way to convert to UTF8 and utf8_bin? Do we have to expect any issues converting the cacti database from latin1_swedish_ci to utf8_bin?

Thank you.

Chris

**Comment by netniV** [comment]
Cacti 1.2 actually expects to be able to use utf8mb4_unicode_ci to be multi-language supporting.  Generally, if you are converting from Latin1 to UTF8, there are no issues that I'm aware of but i'm by no means a MySQL/MariaDB guru.

On the MySQL 8.0 and MariaDB 10 front, we are currently testing along with PHP 7.2 as there have been a number of breaking changes in each version which has caused some minor issues.  I believe most have been rectified but we are still testing it to be sure.

**Comment by cigamit** [comment]
So far MariaDB 10.x has not been a problem.  We have had no reports from MySQL 8.x yet.

**Comment by cigamit** [comment]
Let me be more clear on that, all the known issues are resolved in 1.2.  1.1.38 has some outstanding issues that have been remediated.

**Comment by cigamit** [comment]
Since there is no further discussion on this, I will close.
