### ISSUE TITLE
Site - TimeZone dropdown has no content

### ISSUE THREAD

**Issue by BSOD2600** [Cacti/cacti#171]
no errors logged either

![image](https://cloud.githubusercontent.com/assets/5741811/21754567/cd385c46-d5b7-11e6-8c03-cae2303ef974.png)

**Comment by cigamit** [comment]
In your installer, you have to follow the following instructions.  I will keep this issue open.  You can close when you installer is all set.

http://www.geeksengine.com/article/populate-time-zone-data-for-mysql.html

**Comment by BSOD2600** [comment]
Cacti Install wizard should check for lack of timezone and alert/force the user to fix before continuing.

**Comment by cigamit** [comment]
Resolved, thanks.  On the dependency check page, we check for permissions to the time zone name table and issue an error if the permissions are not set and if the zone information has not been loaded.  So, all set.
