### ISSUE TITLE
RRDtool create command causes first update to fail

### ISSUE THREAD

**Issue by cigamit** [Cacti/cacti#1710]
When not using boost, the rrdfile is created with the current time, and not the rrdtool update time causing the first update to fail.

**Comment by cigamit** [comment]
Resolved.

**Comment by sam-san91** [comment]
I think there is a problem with realtime now. The function now expects one more parameter than given in the poller_realtime.php

**Comment by netniV** [comment]
Can you give more explanation as to how you arrived at your suspicion and what bit of could you suspect? If you put that in as a separate issue, it would be best so it can be tracked properly.

**Comment by cigamit** [comment]
Yea, my bad.  Fixed now.
