### ISSUE TITLE
Cacti upgrade does not migrate automation rules

### ISSUE THREAD

**Issue by rprofijt** [Cacti/cacti#1714]
We are finally migrating our legacy Cacti systems to 1.1.3.8

It seems that the database autom8 upgrade script does not work if I upgrade from 0.8.7i to 1.1.3.8

I could manually migrate the rules by doing:

`INSERT INTO automation_graph_rule_items SELECT * from plugin_autom8_graph_rule_items;
INSERT INTO automation_graph_rules SELECT * from plugin_autom8_graph_rules;
INSERT INTO automation_match_rule_items SELECT * from plugin_autom8_match_rule_items;
UPDATE automation_match_rule_items SET field=REPLACE(field, 'host_template.', 'ht.');
UPDATE automation_match_rule_items SET field=REPLACE(field, 'host.', 'h.');
UPDATE automation_match_rule_items SET field=REPLACE(field, 'graph_templates.', 'gt.');
UPDATE automation_match_rule_items SET field=REPLACE(field, 'graph_templates_graph.', 'gtg.');`

**Comment by rprofijt** [comment]
Here you go, all the plugin_autom8* tables, I have omitted the data.

[cacti-autom8-issue1714.sql.gz](https://github.com/Cacti/cacti/files/2206227/cacti-autom8-issue1714.sql.gz)

**Comment by netniV** [comment]
What version of autom8 are you using?  Do you have any other plugins installed?

```
select * from plugin_config
```

**Comment by rprofijt** [comment]
+----+-----------+-------------------------+--------+-----------------+----------------------------------------+---------+
| id | directory | name                    | status | author          | webpage                                | version |
+----+-----------+-------------------------+--------+-----------------+----------------------------------------+---------+
| 12 | thold     | Thresholds              |      1 | Jimmy Conner    | http://docs.cacti.net/plugin:thold     | 0.4.9   | 
|  2 | autom8    | Automate Cacti Tasks    |      1 | Reinhard Scheck | http://docs.cacti.net/plugin:autom8    | 0.35    | 
|  4 | settings  | Global Plugin Settings  |      1 | Jimmy Conner    | http://cactiusers.org                  | 0.7     | 
|  5 | rrdclean  | RRD File Cleaner        |      1 | Reinhard Scheck | http://docs.cacti.net/plugin:rrdclean  | 0.41    | 
|  7 | aggregate | Create Aggregate Graphs |      1 | Reinhard Scheck | http://docs.cacti.net/plugin:aggregate | 0.75    | 
|  8 | nectar    | Send Graphs via EMail   |      1 | Reinhard Scheck | http://docs.cacti.net/plugin:nectar    | 0.35a   | 
+----+-----------+-------------------------+--------+-----------------+----------------------------------------+---------+

**Comment by cigamit** [comment]
It looks like what happened is that someone created the new tables by hand before the upgrade.  I've changed the logic in the file `install/updates/1_0_0.php` to force drop the new table if it exists and then rename the old table.  The schema looks good though.  Please update that file, and try your upgrade again.  Let us know if it's working.

**Comment by netniV** [comment]
Closing due to lack of response.
