### ISSUE TITLE
New User - any error resets entire form

### ISSUE THREAD

**Issue by BSOD2600** [Cacti/cacti#173]
Creating a new user. If there is any displayed error during the Create, the form is cleared and the user is not created.  Not very user friendly to start fresh again.

1) fields before clicking create
![image](https://cloud.githubusercontent.com/assets/5741811/21754679/d72fe4c4-d5b9-11e6-9ebb-9c0ec767456b.png)

2) error displayed & now empty form
![image](https://cloud.githubusercontent.com/assets/5741811/21754686/ee710910-d5b9-11e6-8638-9768a868903d.png)

**Comment by cigamit** [comment]
We are going to make this an enhancement, though I do agree.

**Comment by cigamit** [comment]
The specific password issue was resolved in Cacti 1.0.0.  Therefore, going to close this one.
