### ISSUE TITLE
Correct UTF8 table conversion script name

### ISSUE THREAD

**Issue by jackouille-ch** [Cacti/cacti#1732]
I downloaded the full develop structure for 1.2.0 and start install.
At step 8 I'm stuck with following warning:
WARNING

One or more tables are too large to convert during the installation. You should use the cli/convert_tables.php script to perform the conversion.

/usr/bin/php -q cli/convert_database.php -u -i

But this file is not present on repository.

Root cause on my side is the following:
table host_snmp_cache contains over 490'000 entries. So I clear this table in order to be able to go further.

So no more warning on page but while trying to go Next (but same with Previous), got the following error:
Sorry, we could not process your last action.
Error:
414 Request-URI Too Long
Reason:
The response to the last action was unexpected.

Here is the source HTML from this page:
<!DOCTYPE html>
<html>
<head>
		<meta http-equiv='X-UA-Compatible' content='IE=Edge,chrome=1'>
	<meta content='width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0' name='viewport'>
	<meta name='apple-mobile-web-app-capable' content='yes'>
	<meta name='mobile-web-app-capable' content='yes'>
	<meta name='robots' content='noindex,nofollow'>
	<title>Cacti Server v1.2.0 - Install/Version Change</title>
	<meta http-equiv='Content-Type' content='text/html;charset=utf-8'>
	<script type='text/javascript'>var theme='modern';</script>
	<link href='/cacti/include/themes/modern/images/favicon.ico' rel='shortcut icon'>
	<link href='/cacti/include/themes/modern/images/cacti_logo.gif' rel='icon' sizes='96x96'>
	<link href='/cacti/include/themes/modern/jquery.zoom.css?aabc6f45db68bd321ca27338899ef75d' type='text/css' rel='stylesheet'>
<link href='/cacti/include/themes/modern/jquery-ui.css?a7406d654968e3c1531207059a9d15d2' type='text/css' rel='stylesheet'>
<link href='/cacti/include/themes/modern/default/style.css?b16e44c8ea2180ea769a22921bc369ad' type='text/css' rel='stylesheet'>
<link href='/cacti/include/themes/modern/jquery.multiselect.css?e8d1b3ce433249ef1f2f15343caa74fb' type='text/css' rel='stylesheet'>
<link href='/cacti/include/themes/modern/jquery.timepicker.css?431ab7d4ef48afd9c39a647c5c990b0a' type='text/css' rel='stylesheet'>
<link href='/cacti/include/themes/modern/jquery.colorpicker.css?fd70588fc7990c783ba6b2722371b9bd' type='text/css' rel='stylesheet'>
<link href='/cacti/include/themes/modern/c3.css?4aef467349628c8e407ecc205eac5375' type='text/css' rel='stylesheet'>
<link href='/cacti/include/themes/modern/pace.css?813d842ea49d68287a59d7f49575aaa6' type='text/css' rel='stylesheet'>
<link href='/cacti/include/fa/css/fontawesome.css?c33e55a3e79984d24f3309545701cb1b' type='text/css' rel='stylesheet'>
<link href='/cacti/include/themes/modern/main.css?e66980c84337ab6b8af6290a68f9e741' type='text/css' rel='stylesheet'>
<script type='text/javascript' src='/cacti/include/js/screenfull.js?f3fee4f35cb108c8187062e386985fe7'></script>
<script type='text/javascript' src='/cacti/include/js/jquery.js?2f0d15c70b7e652d5d61ed4032eb44af'></script>
<script type='text/javascript' src='/cacti/include/js/jquery-migrate.js?bbbaafe34a8ab17085741d8d0e7db751'></script>
<script type='text/javascript' src='/cacti/include/js/jquery-ui.js?f1f075fe32aca8216e55c5d00106fba7'></script>
<script type='text/javascript' src='/cacti/include/js/jquery.ui.touch.punch.js?4195aad6f616651c00557e84c6721646'></script>
<script type='text/javascript' src='/cacti/include/js/jquery.cookie.js?0b804d4f90de70b032a9986b22165b75'></script>
<script type='text/javascript' src='/cacti/include/js/js.storage.js?dbcd4e6ad90c47adfa9dd509ceb55eb9'></script>
<script type='text/javascript' src='/cacti/include/js/jstree.js?b371a59bea924b430bb6b60904fbaac8'></script>
<script type='text/javascript' src='/cacti/include/js/jquery.hotkeys.js?fbf82bcab286e9fc5cdf863eb067230f'></script>
<script type='text/javascript' src='/cacti/include/js/jquery.tablednd.js?a33b14ebf8ce2abf7911e62cbc19e0c5'></script>
<script type='text/javascript' src='/cacti/include/js/jquery.zoom.js?14baec77613b475dbf11624075ace2f7'></script>
<script type='text/javascript' src='/cacti/include/js/jquery.multiselect.js?d4188f31d19285683731418f0f8854e8'></script>
<script type='text/javascript' src='/cacti/include/js/jquery.multiselect.filter.js?eb99fd8e2b0736c839c1b0a736af21c0'></script>
<script type='text/javascript' src='/cacti/include/js/jquery.timepicker.js?f29132ab24085f909242175ad11cfcbc'></script>
<script type='text/javascript' src='/cacti/include/js/jquery.colorpicker.js?4a5021ca49f95df1c61ba53873a1e70a'></script>
<script type='text/javascript' src='/cacti/include/js/jquery.tablesorter.js?29b1ca9fd1a3c48aa723af8359409c41'></script>
<script type='text/javascript' src='/cacti/include/js/jquery.tablesorter.widgets.js?f71512a4c990f2e0a94aceaa24bb0d45'></script>
<script type='text/javascript' src='/cacti/include/js/jquery.tablesorter.pager.js?8ca32d30195c98492cd028f582f07c8c'></script>
<script type='text/javascript' src='/cacti/include/js/jquery.metadata.js?bdd7532ce75cce796a5451bd4322d61f'></script>
<script type='text/javascript' src='/cacti/include/js/jquery.sparkline.js?c7638b825bc7deb1cf58c990825d35b2'></script>
<script type='text/javascript' src='/cacti/include/js/Chart.js?b3c4f8661a73c6997c7f0aad0583a9db'></script>
<script type='text/javascript' src='/cacti/include/js/dygraph-combined.js?b5b448f71f8c3eb4a39506299bd81b0c'></script>
<script type='text/javascript' src='/cacti/include/js/d3.js?fa31e071b81cbaf76bc3b63964b9dbbb'></script>
<script type='text/javascript' src='/cacti/include/js/c3.js?9413c7bea6680c3c7eaed85714b99a6c'></script>
<script type='text/javascript' src='/cacti/include/js/pace.js?30fbf6c62d78d3367fa50bd51913200c'></script>
<script type='text/javascript' src='/cacti/include/realtime.js?faa335ee6aa54e84403a41f9cdaacd98'></script>
<script type='text/javascript' src='/cacti/include/layout.js?a76da4b1b12c7c30c9791a5b8f721edc'></script>
<script type='text/javascript' src='/cacti/include/themes/modern/main.js?94744c4e1f087422166eedf5189ca305'></script>
	<script type='text/javascript' src='/cacti/install/install.js?866e3e61291482ee716b61717b4c8a42'></script>
	<link href='/cacti/install/install.css?dc0e11c7f062be16b4f4b9cf0d78665f' type='text/css' rel='stylesheet'>
	<link href='/cacti/include/vendor/flag-icon-css/css/flag-icon.css?216e807dd0b784846799cb18051f250d' type='text/css' rel='stylesheet'>
<script type="text/javascript">if (top != self) {top.location.href = self.location.href;}</script><script type="text/javascript">var csrfMagicToken = "sid:f15c2cb9313b527e23343a9c72810dbcdff54fbc,1532332063";var csrfMagicName = "__csrf_magic";</script><script src="/cacti/include/vendor/csrf/csrf-magic.js" type="text/javascript"></script></head>
<body>
	<div class='cactiInstallTable'>
		<div class='cactiTableTitleRow cactiBorderWall'>
			<div class='textHeaderDark'>Cacti Server v1.2.0 - Installation Wizard</div>
		</div>
		<div class='cactiInstallArea cactiBorderWall'>
			<div class='cactiInstallAreaContent' id='installContent'>
<h2 class='cactiInstallSectionTitle'>Initializing</h2><p class='cactiInstallSection cactiInstallSectionNormal'>Please wait while the installation system for Cacti Version 1.2.0 initializes.  You must have JavaScript enabled for this to work.</p>			</div>
		</div>
		<div class='cactiInstallButtonArea saveRow'>
			<input class='installButton' id='buttonPrevious' type='button' value='Previous' style='display: none'>
			<input class='installButton' id='buttonNext' type='button' value='Next' style='display: none'>
			<input class='installButton' id='buttonTest' type='button' value='Test' style='display:none'>
			<input id='installData' type='hidden'>
		</div>
		<div id='installDebug'></div>
		<div class='cactiInstallCopyrightArea textHeaderDark'>Copyright (C) 2004-2018 The Cacti Group</div>
	</div>
<script type='text/javascript'>
	var cactiVersion='1.2.0';
	var cactiServerOS='unix';
	var theme='modern';
	var refreshIsLogout=true;
	var refreshPage='/cacti/logout.php?action=timeout';
	var refreshMSeconds=1440000;
	var urlPath='/cacti/';
	var previousPage='';
	var searchFilter='Enter a search term';
	var searchRFilter='Enter a regular expression';
	var noFileSelected='No file selected';
	var timeGraphView='Time Graph View';
	var filterSettingsSaved='Filter Settings Saved';
	var spikeKillResuls='SpikeKill Results';
	var utilityView='Utility View';
	var realtimeClickOn='Click to view just this Graph in Realtime';
	var realtimeClickOff='Click again to take this Graph out of Realtime';
	var treeView='Tree View';
	var listView='List View';
	var previewView='Preview View';
	var cactiHome='Cacti Home';
	var cactiProjectPage='Cacti Project Page';
	var cactiCommunityForum='Cacti Community Forum';
	var reportABug='Report a bug';
	var aboutCacti='About Cacti';
	var spikeKillResults='SpikeKill Results';
	var showHideFilter='Click to Show/Hide Filter';
	var clearFilterTitle='Clear Current Filter';
	var clipboard='Clipboard';
	var clipboardID='Clipboard ID';
	var clipboardNotAvailable='Copy operation is unavailable at this time';
	var clipboardCopyFailed='Failed to find data to copy!';
	var clipboardUpdated='Clipboard has been updated';
	var clipboardNotUpdated='Sorry, your clipboard could not be updated at this time';
	var defaultSNMPSecurityLevel='authPriv';
	var defaultSNMPAuthProtocol='MD5';
	var defaultSNMPPrivProtocol='DES';
	var passwordPass='Passphrase length meets 8 character minimum';
	var passwordTooShort='Passphrase too short';
	var passwordMatchTooShort='Passphrase matches but too short';
	var passwordNotMatchTooShort='Passphrase too short and not matching';
	var passwordMatch='Passphrases match';
	var passwordNotMatch='Passphrases do not match';
	var errorOnPage='Sorry, we could not process your last action.';
	var errorNumberPrefix='Error:';
	var errorReasonPrefix='Reason:';
	var errorReasonTitle='Action failed';
	var errorReasonUnexpected='The response to the last action was unexpected.';
	var sessionMessageTitle='Operation successful';
	var sessionMessageSave='The Operation was successful.  Details are below.';
	var sessionMessage=[];
	var sessionMessageOk='Ok';
	var sessionMessagePause='Pause';
	var zoom_i18n_zoom_in='Zoom In';
	var zoom_i18n_zoom_out='Zoom Out';
	var zoom_i18n_zoom_out_factor='Zoom Out Factor';
	var zoom_i18n_timestamps='Timestamps';
	var zoom_i18n_zoom_2='2x';
	var zoom_i18n_zoom_4='4x';
	var zoom_i18n_zoom_8='8x';
	var zoom_i18n_zoom_16='16x';
	var zoom_i18n_zoom_32='32x';
	var zoom_i18n_zoom_out_positioning='Zoom Out Positioning';
	var zoom_i18n_mode='Zoom Mode';
	var zoom_i18n_graph='Graph';
	var zoom_i18n_quick='Quick';
	var zoom_i18n_advanced='Advanced';
	var zoom_i18n_newTab='Open in new tab';
	var zoom_i18n_save_graph='Save graph';
	var zoom_i18n_copy_graph='Copy graph';
	var zoom_i18n_copy_graph_link='Copy graph link';
	var zoom_i18n_on='Always On';
	var zoom_i18n_auto='Auto';
	var zoom_i18n_off='Always Off';
	var zoom_i18n_begin='Begin with';
	var zoom_i18n_center='Center';
	var zoom_i18n_end='End with';
	var zoom_i18n_disabled='Disabled';
	var zoom_i18n_close='Close';
	var zoom_i18n_settings='Settings';
	var zoom_i18n_3rd_button='3rd Mouse Button';
</script>
<script type="text/javascript">CsrfMagic.end();</script></body>
</html>

Restarted install and still get stuck at the same page: Database Collation

**Comment by netniV** [comment]
That would be my bad.  The name of the script got changed to better reflect the function it was doing.  It doesn't actually convert a database, but the collation of the tables.  As such, it was now called `cli/convert_tables.php`

I will correct this later today.

**Comment by jackouille-ch** [comment]
Yes with php -q ./convert_tables.php -u -i it works much better.
Only got another error:

UPDATE TABLE poller SET processes = 10, threads = 20 | [Fail]

I made the change manually ;-)

**Comment by jackouille-ch** [comment]
At the end of process I was redirected to my URL without /cacti, generating the "You don't have permission to access / on this server." error.

**Comment by netniV** [comment]
Did you have cacti_url set in your config.php?

**Comment by netniV** [comment]
Can you log the other two issues separately for me so we can track them properly?

**Comment by cigamit** [comment]
Some Cacti installs have very big tables that for various performance reasons, the users may not want to convert to InnoDB.  We should provide the ability to select which tables they want to convert.  By default, the tables that are 'built-in' should be converted without question, but some of these various plugin tables can get really big, and may perform better on MyISAM.

**Comment by cigamit** [comment]
I have yet to test the latest installer, I'll look for this though.

**Comment by netniV** [comment]
The installer currently checks for collation, not for engine type. We could add that in the same fashion.  The cli/convert_tables.php already has an InnoDB option, though it does not check whether a table should be converted (eg, if one should stay a memory table abort)

**Comment by jackouille-ch** [comment]
Maybe you could either not import values from table host_snmp_cache
This table was blocking my process (because of more than 490'000 entries, breaking the 300'000 limit defined), either with the fact that remote keys check must be disabled.
I don't see the added value to keep data because it's a cache table and will be filled again while in production again.

**Comment by netniV** [comment]
That is a good point.  Most other cache tables are memory tables.  However, because the cache is designed to last across polling sessions so that we aren't constantly trying to get various bits of data on every call, it's a proper table.

**Comment by netniV** [comment]
Could you open the host_snmp_cache issue as another issue as I'm going to close this one since we resolved the original problem.
