### ISSUE TITLE
1.2.0 Visual enhancement for missing RRD

### ISSUE THREAD

**Issue by jackouille-ch** [Cacti/cacti#1734]
With current graph we cannot see which RRD is concerned:
![image](https://user-images.githubusercontent.com/35721406/43069389-3b2cd622-8e6d-11e8-8b20-aaacfbbd35f6.png)

Possible corrections:
- split text : ERROR<br>'/usr/shrae/cacti/rra/'<br>'rest of path'<br> No such file or Directory
- reduce text font

**Comment by netniV** [comment]
That is unfortunately slightly out of our hands.  The main reason being that different systems will build that path different and there is nothing stopping someone having a path of `/usr/share/myexceptionallystupidlylongpathbecauseIamanumpty/` which would still be cut off the screen.

What we can do, is simply say that the subpart that can not be opened, eg, 1/3/1234.rrd were the 1/3 are the cacti made directories.  The admin would need to know where his RRA folder is, and would more than likely know.

**Comment by jackouille-ch** [comment]
Or add text under picture with full path

**Comment by netniV** [comment]
I've just added this functionality as a PR.  Let me know what you think of the messages now?

**Comment by jackouille-ch** [comment]
Which file did you update?

**Comment by netniV** [comment]
https://github.com/Cacti/cacti/pull/1755/files

**Comment by jackouille-ch** [comment]
Updated the 2 files, restarted Apache but still the same:
![image](https://user-images.githubusercontent.com/35721406/43266615-1f87552e-90ec-11e8-9003-754e44c32741.png)

**Comment by netniV** [comment]
Check the lib/rrd.php file, do you have a parse_error() function?

**Comment by jackouille-ch** [comment]
Nope. My file has 3'445 lines

**Comment by netniV** [comment]
Then you aren’t pulling the files from my repo.  It’s not merged in yet. If you follow the link above then for each file do view then raw, you’ll get the raw source.

**Comment by netniV** [comment]
This is now merged.
