### ISSUE TITLE
1.2.0 Selection lists appear to be selecting all devices even when not selected

### ISSUE THREAD

**Issue by jackouille-ch** [Cacti/cacti#1735]
Despite you select only one device on full device list to be enabled or disabled, the full list is taken.

**Comment by netniV** [comment]
That doesn't seem right, I'll take a look.

**Comment by netniV** [comment]
This does seem to be the case:
![image](https://user-images.githubusercontent.com/9052188/43075410-ab347cbc-8e78-11e8-8aba-10aa8ec8e031.png)

I will apply a fix for this.

**Comment by netniV** [comment]
This issue actually affects all lists.

**Comment by netniV** [comment]
![image](https://user-images.githubusercontent.com/9052188/43079858-2abec174-8e86-11e8-993c-27986fcb9b76.png)

The above shows some of the headers being sent which unfortunately is too much according to:
```php
/* loop through each of the host templates selected on the previous page and get more info about them */
foreach ($_POST as $var => $val) {
        if (preg_match('/^chk_([0-9]+)$/', $var, $matches)) {
                /* ================= input validation ================= */
                input_validate_input_number($matches[1]);
                /* ==================================================== */

                $host_list .= '<li>' . html_escape(db_fetch_cell_prepared('SELECT description FROM host WHERE id = ?', arra$
                $host_array[] = $matches[1];
        }
}
```

It would appear that most selection code doesn't check that the name has a value, merely that it exists.

**Comment by cigamit** [comment]
This is resolved now.
