### ISSUE TITLE
Realtime graphs not working properly

### ISSUE THREAD

**Issue by sam-san91** [Cacti/cacti#1744]
`PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function rrdtool_function_create(), 2 passed in /var/lib/cacti/poller_realtime.php on line 215 and at least 3 expected in /var/lib/cacti/lib/rrd.php:475
Stack trace:
#0 /var/lib/cacti/poller_realtime.php(215): rrdtool_function_create('124826', true)
#1 /var/lib/cacti/poller_realtime.php(159): process_poller_output_rt(Resource id #37, '743e75c6uagan8b...', 5)
#2 {main}
  thrown in /var/lib/cacti/lib/rrd.php on line 475
`

After the latest commits the realtime graphes won't work properly because the rrd files can't get created. I suspect this has something to do with #1710

**Comment by netniV** [comment]
The problem is with the following two files:

datasource.php:
```php
<pre><?php print @rrdtool_function_create(get_request_var('id'), true);?></pre>
```

and poller_realtime.php:
```php
$command = @rrdtool_function_create($item['local_data_id'], true);
```

Neither are supplying the $initial_time field that was added and non-optional.  I think a quick workaround would be to change the parameter to be optional with `$initial_time = time()`

**Comment by cigamit** [comment]
This should be resolved now.  Thanks for reporting.
