### ISSUE TITLE
SNMP timeout

### ISSUE THREAD

**Issue by hellspawndf** [Cacti/cacti#1745]
I keep getting this error:
24/Jul/2018 11:15:01 - CMDPHP PHP ERROR WARNING Backtrace: (/cmd.php: 661 cacti_snmp_session_get)(/lib/snmp.php: 472 get)(CactiErrorHandler)(/lib/functions.php: 4585 cacti_debug_backtrace)

24/Jul/2018 11:20:02 - CMDPHP PHP ERROR WARNING Backtrace: (/cmd.php: 661 cacti_snmp_session_get)(/lib/snmp.php: 472 get)(CactiErrorHandler)(/lib/functions.php: 4585 cacti_debug_backtrace)

24/Jul/2018 11:20:02 - ERROR PHP WARNING: SNMP::get(): Fatal error: Timeout in file: /usr/share/cacti/site/lib/snmp.php on line: 472

PHP7.2, php-snmp and php7.2-snmp installed on a fresh Ubuntu system, cacti 1.1.38 installed via apt-get.

Can anyone help me?

Looks like same error described here: https://github.com/Cacti/cacti/issues/535
Followed cigamit instructions and created a new bug here.

**Comment by netniV** [comment]
PHP 7.2 isn't supported for 1.1.38.  You will need to either downgrade your version of PHP or upgrade your version of cacti to the latest development version.

**Comment by hellspawndf** [comment]
Thanks, netniV. I'been using Cacti for more than 10 years, on Debian, CentOS and SLES. Decided to be bold and go to Ubuntu. Apparently not a good choice. I am now using version 1.2.0. Tough I know it is in development stage, it seems ok by now. Congrats!

**Comment by netniV** [comment]
I'm using Ubuntu 18.04 as my development environment to make sure things work with PHP 7.2 etc.  So far, I haven't noticed any real problems.

**Comment by cigamit** [comment]
Try disabling php-snmp and see if that helps.
