### ISSUE TITLE
Enhancement: Allow filter restriction for sources when editing graphs

### ISSUE THREAD

**Issue by jackouille-ch** [Cacti/cacti#1756]
And would it be possible to filter data source and take only requested ones?
I have traffic_in and traffic_out but I only need traffic_out (which is either the value you are showing).
Or having a full dynamic auto-complete for data sources (following case https://github.com/Cacti/cacti/issues/1726)

**Comment by cigamit** [comment]
They are dynamic, you just have to clear the current text.  I'm looking at Select2 as a possible replacement for the jQueryUI selectmenu which might helps us with multiple issues.

**Comment by jackouille-ch** [comment]
Yes it's dynamic but my meaning was adding the right data source within query.
If your data Source is Traffic_in, only data sources Traffic_in will be displayed, currently it's all data sources related to the interface.

**Comment by netniV** [comment]
If I am understanding this right, I can see why you would want that. However, I'm sure there are some cases where people template their fields for some parts, but then want to change which field is being used and it isn't the same as the templated one.  For example, I have the multi-cpu templates which has a template for 2, 4, 6, 8, 12, 16, 20 cpu's.  For each one of those, the template'd source isn't the source I actually use.

**Comment by jackouille-ch** [comment]
Ok I understand your way. From my side I try to use always the same data source as defined in my graph template.

**Comment by TheWitness** [comment]
Closing this one.  Not on my or anyone's radar screen at the moment.
