### ISSUE TITLE
[1.2.0] - SQL error for automation_devices

### ISSUE THREAD

**Issue by jackouille-ch** [Cacti/cacti#1757]
![image](https://user-images.githubusercontent.com/35721406/43309713-d82efa16-9185-11e8-8cc3-bc6f6062c028.png)

And faulty request in text mode:
ALTER TABLE automation_devices ADD COLUMN id BIGINT unsigned auto_increment FIRST, ADD COLUMN network_id INT unsigned NOT NULL default '0' AFTER id, ADD COLUMN snmp_port int(10) unsigned NOT NULL DEFAULT '161' AFTER snmp_version, ADD COLUMN snmp_engine_id varchar(30) DEFAULT '' AFTER snmp_context, DROP PRIMARY KEY, ADD PRIMARY KEY(id), ADD UNIQUE INDEX ip(ip); ADD INDEX network_id(network_id), COMMENT='Table of Discovered Devices'

**Comment by netniV** [comment]
Which section was this in?  What does the log say about the SQL ? (it should have been recorded in the cacti.log file)

**Comment by jackouille-ch** [comment]
Nothing found in my logs (neither in cacti_debug.log or cacti.log) but ran the request on MySQLAdmin:
ALTER TABLE automation_devices ADD COLUMN id BIGINT unsigned auto_increment FIRST, ADD COLUMN network_id INT unsigned NOT NULL default '0' AFTER id, ADD COLUMN snmp_port int(10) unsigned NOT NULL DEFAULT '161' AFTER snmp_version, ADD COLUMN snmp_engine_id varchar(30) DEFAULT '' AFTER snmp_context, DROP PRIMARY KEY, ADD PRIMARY KEY(id), ADD UNIQUE INDEX ip(ip); ADD INDEX network_id(network_id), COMMENT='Table of Discovered Devices'

Error #1016 - Name of field 'id' already in use

**Comment by cigamit** [comment]
The problem is here that you have both copies of the legacy and new tables in place.  You are basically upgrading your system again after you have manually added the old discovery tables back into your system.  I think this is more of a problem with your setup than it is with Cacti.
