### ISSUE TITLE
[1.2.0] Cacti on localhost : cannot change values

### ISSUE THREAD

**Issue by jackouille-ch** [Cacti/cacti#1758]
This a strange behaviour: if you edit Cacti localhost, you cannot change it's IP or SNMP community.
Chnages are committed but not saved.
From my side I changed the SNMP community from release 0.8.8 to 1.2.0 on physical server but it was impossible to changed it via Cacti, I do the change directly in DB.

**Comment by netniV** [comment]
There will likely have been an error in your log file when you try to do the save.  Can you post the lines around it to give some context.

**Comment by jackouille-ch** [comment]
That's the trouble, I didn't see any error but values are not changed. Have you tried on your Cacti?

**Comment by netniV** [comment]
I'm able to edit without issue.  Lets check your table, do the following query in MySQL:
```sql
select * from information_schema.columns where table_name = 'host' and table_schema = '<cacti_db_name>';
```

**Comment by jackouille-ch** [comment]
![image](https://user-images.githubusercontent.com/35721406/43318761-58c9cfd6-91a2-11e8-9586-310ad0b29fe4.png)

**Comment by netniV** [comment]
Ideally, can you use the command line so that I can manipulate the text?

**Comment by jackouille-ch** [comment]
Yes sorry:
mysql> select * from information_schema.columns where table_name = 'host' and table_schema = 'cacti' ;
+---------------+--------------+------------+------------------------+------------------+---------------------+-------------+------------+--------------------------+------------------------+-------------------+---------------+--------------------+--------------------+--------------------+-----------------------+------------+-----------------------------+---------------------------------+----------------+-----------------------+
| TABLE_CATALOG | TABLE_SCHEMA | TABLE_NAME | COLUMN_NAME            | ORDINAL_POSITION | COLUMN_DEFAULT      | IS_NULLABLE | DATA_TYPE  | CHARACTER_MAXIMUM_LENGTH | CHARACTER_OCTET_LENGTH | NUMERIC_PRECISION | NUMERIC_SCALE | DATETIME_PRECISION | CHARACTER_SET_NAME | COLLATION_NAME     | COLUMN_TYPE           | COLUMN_KEY | EXTRA                       | PRIVILEGES                      | COLUMN_COMMENT | GENERATION_EXPRESSION |
+---------------+--------------+------------+------------------------+------------------+---------------------+-------------+------------+--------------------------+------------------------+-------------------+---------------+--------------------+--------------------+--------------------+-----------------------+------------+-----------------------------+---------------------------------+----------------+-----------------------+
| def           | cacti        | host       | id                     |                1 | NULL                | NO          | mediumint  |                     NULL |                   NULL |                 7 |             0 |               NULL | NULL               | NULL               | mediumint(8) unsigned | PRI        | auto_increment              | select,insert,update,references |                |                       |
| def           | cacti        | host       | poller_id              |                2 | 1                   | NO          | int        |                     NULL |                   NULL |                10 |             0 |               NULL | NULL               | NULL               | int(10) unsigned      | MUL        |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | site_id                |                3 | 1                   | NO          | int        |                     NULL |                   NULL |                10 |             0 |               NULL | NULL               | NULL               | int(10) unsigned      | MUL        |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | host_template_id       |                4 | 0                   | NO          | mediumint  |                     NULL |                   NULL |                 7 |             0 |               NULL | NULL               | NULL               | mediumint(8) unsigned |            |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | description            |                5 |                     | NO          | varchar    |                      150 |                    600 |              NULL |          NULL |               NULL | utf8mb4            | utf8mb4_unicode_ci | varchar(150)          |            |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | hostname               |                6 |                     | YES         | varchar    |                      100 |                    400 |              NULL |          NULL |               NULL | utf8mb4            | utf8mb4_unicode_ci | varchar(100)          | MUL        |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | location               |                7 | NULL                | YES         | varchar    |                       40 |                    160 |              NULL |          NULL |               NULL | utf8mb4            | utf8mb4_unicode_ci | varchar(40)           |            |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | notes                  |                8 | NULL                | YES         | mediumtext |                 16777215 |               16777215 |              NULL |          NULL |               NULL | utf8mb4            | utf8mb4_unicode_ci | mediumtext            |            |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | external_id            |                9 | NULL                | YES         | varchar    |                       40 |                    160 |              NULL |          NULL |               NULL | utf8mb4            | utf8mb4_unicode_ci | varchar(40)           | MUL        |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | snmp_community         |               10 | NULL                | YES         | varchar    |                      100 |                    400 |              NULL |          NULL |               NULL | utf8mb4            | utf8mb4_unicode_ci | varchar(100)          |            |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | snmp_version           |               11 | 1                   | NO          | tinyint    |                     NULL |                   NULL |                 3 |             0 |               NULL | NULL               | NULL               | tinyint(1) unsigned   |            |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | snmp_username          |               12 | NULL                | YES         | varchar    |                       50 |                    200 |              NULL |          NULL |               NULL | utf8mb4            | utf8mb4_unicode_ci | varchar(50)           |            |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | snmp_password          |               13 | NULL                | YES         | varchar    |                       50 |                    200 |              NULL |          NULL |               NULL | utf8mb4            | utf8mb4_unicode_ci | varchar(50)           |            |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | snmp_auth_protocol     |               14 |                     | YES         | char       |                        6 |                     24 |              NULL |          NULL |               NULL | utf8mb4            | utf8mb4_unicode_ci | char(6)               |            |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | snmp_priv_passphrase   |               15 |                     | YES         | varchar    |                      200 |                    800 |              NULL |          NULL |               NULL | utf8mb4            | utf8mb4_unicode_ci | varchar(200)          |            |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | snmp_priv_protocol     |               16 |                     | YES         | char       |                        6 |                     24 |              NULL |          NULL |               NULL | utf8mb4            | utf8mb4_unicode_ci | char(6)               |            |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | snmp_context           |               17 |                     | YES         | varchar    |                       64 |                    256 |              NULL |          NULL |               NULL | utf8mb4            | utf8mb4_unicode_ci | varchar(64)           |            |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | snmp_engine_id         |               18 |                     | YES         | varchar    |                       64 |                    256 |              NULL |          NULL |               NULL | utf8mb4            | utf8mb4_unicode_ci | varchar(64)           |            |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | snmp_port              |               19 | 161                 | NO          | mediumint  |                     NULL |                   NULL |                 7 |             0 |               NULL | NULL               | NULL               | mediumint(5) unsigned |            |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | snmp_timeout           |               20 | 500                 | NO          | mediumint  |                     NULL |                   NULL |                 7 |             0 |               NULL | NULL               | NULL               | mediumint(8) unsigned |            |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | snmp_sysDescr          |               21 |                     | NO          | varchar    |                      300 |                   1200 |              NULL |          NULL |               NULL | utf8mb4            | utf8mb4_unicode_ci | varchar(300)          |            |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | snmp_sysObjectID       |               22 |                     | NO          | varchar    |                      128 |                    512 |              NULL |          NULL |               NULL | utf8mb4            | utf8mb4_unicode_ci | varchar(128)          |            |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | snmp_sysUpTimeInstance |               23 | 0                   | NO          | int        |                     NULL |                   NULL |                10 |             0 |               NULL | NULL               | NULL               | int(10) unsigned      |            |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | snmp_sysContact        |               24 |                     | NO          | varchar    |                      300 |                   1200 |              NULL |          NULL |               NULL | utf8mb4            | utf8mb4_unicode_ci | varchar(300)          |            |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | snmp_sysName           |               25 |                     | NO          | varchar    |                      300 |                   1200 |              NULL |          NULL |               NULL | utf8mb4            | utf8mb4_unicode_ci | varchar(300)          |            |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | snmp_sysLocation       |               26 |                     | NO          | varchar    |                      300 |                   1200 |              NULL |          NULL |               NULL | utf8mb4            | utf8mb4_unicode_ci | varchar(300)          |            |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | availability_method    |               27 | 1                   | NO          | smallint   |                     NULL |                   NULL |                 5 |             0 |               NULL | NULL               | NULL               | smallint(5) unsigned  |            |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | ping_method            |               28 | 0                   | YES         | smallint   |                     NULL |                   NULL |                 5 |             0 |               NULL | NULL               | NULL               | smallint(5) unsigned  |            |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | ping_port              |               29 | 0                   | YES         | int        |                     NULL |                   NULL |                10 |             0 |               NULL | NULL               | NULL               | int(12) unsigned      |            |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | ping_timeout           |               30 | 500                 | YES         | int        |                     NULL |                   NULL |                10 |             0 |               NULL | NULL               | NULL               | int(12) unsigned      |            |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | ping_retries           |               31 | 2                   | YES         | int        |                     NULL |                   NULL |                10 |             0 |               NULL | NULL               | NULL               | int(12) unsigned      |            |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | max_oids               |               32 | 10                  | YES         | int        |                     NULL |                   NULL |                10 |             0 |               NULL | NULL               | NULL               | int(12) unsigned      |            |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | device_threads         |               33 | 1                   | NO          | tinyint    |                     NULL |                   NULL |                 3 |             0 |               NULL | NULL               | NULL               | tinyint(2) unsigned   |            |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | disabled               |               34 |                     | YES         | char       |                        2 |                      8 |              NULL |          NULL |               NULL | utf8mb4            | utf8mb4_unicode_ci | char(2)               | MUL        |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | manage                 |               35 |                     | NO          | char       |                        3 |                     12 |              NULL |          NULL |               NULL | utf8mb4            | utf8mb4_unicode_ci | char(3)               |            |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | thold_send_email       |               36 | 1                   | NO          | int        |                     NULL |                   NULL |                10 |             0 |               NULL | NULL               | NULL               | int(10)               |            |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | thold_host_email       |               37 | NULL                | NO          | int        |                     NULL |                   NULL |                10 |             0 |               NULL | NULL               | NULL               | int(10)               |            |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | monitor                |               38 | on                  | NO          | char       |                        3 |                     12 |              NULL |          NULL |               NULL | utf8mb4            | utf8mb4_unicode_ci | char(3)               |            |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | monitor_text           |               39 | NULL                | NO          | mediumtext |                 16777215 |               16777215 |              NULL |          NULL |               NULL | utf8mb4            | utf8mb4_unicode_ci | mediumtext            |            |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | status                 |               40 | 0                   | NO          | tinyint    |                     NULL |                   NULL |                 3 |             0 |               NULL | NULL               | NULL               | tinyint(2)            | MUL        |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | status_event_count     |               41 | 0                   | NO          | mediumint  |                     NULL |                   NULL |                 7 |             0 |               NULL | NULL               | NULL               | mediumint(8) unsigned |            |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | status_fail_date       |               42 | 0000-00-00 00:00:00 | NO          | timestamp  |                     NULL |                   NULL |              NULL |          NULL |                  0 | NULL               | NULL               | timestamp             |            |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | status_rec_date        |               43 | 0000-00-00 00:00:00 | NO          | timestamp  |                     NULL |                   NULL |              NULL |          NULL |                  0 | NULL               | NULL               | timestamp             |            |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | status_last_error      |               44 |                     | YES         | varchar    |                      255 |                   1020 |              NULL |          NULL |               NULL | utf8mb4            | utf8mb4_unicode_ci | varchar(255)          |            |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | min_time               |               45 | 9.99999             | YES         | decimal    |                     NULL |                   NULL |                10 |             5 |               NULL | NULL               | NULL               | decimal(10,5)         |            |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | max_time               |               46 | 0.00000             | YES         | decimal    |                     NULL |                   NULL |                10 |             5 |               NULL | NULL               | NULL               | decimal(10,5)         |            |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | cur_time               |               47 | 0.00000             | YES         | decimal    |                     NULL |                   NULL |                10 |             5 |               NULL | NULL               | NULL               | decimal(10,5)         |            |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | avg_time               |               48 | 0.00000             | YES         | decimal    |                     NULL |                   NULL |                10 |             5 |               NULL | NULL               | NULL               | decimal(10,5)         |            |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | polling_time           |               49 | 0                   | YES         | double     |                     NULL |                   NULL |                22 |          NULL |               NULL | NULL               | NULL               | double                |            |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | total_polls            |               50 | 0                   | YES         | int        |                     NULL |                   NULL |                10 |             0 |               NULL | NULL               | NULL               | int(12) unsigned      |            |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | failed_polls           |               51 | 0                   | YES         | int        |                     NULL |                   NULL |                10 |             0 |               NULL | NULL               | NULL               | int(12) unsigned      |            |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | availability           |               52 | 100.00000           | NO          | decimal    |                     NULL |                   NULL |                 8 |             5 |               NULL | NULL               | NULL               | decimal(8,5)          |            |                             | select,insert,update,references |                |                       |
| def           | cacti        | host       | last_updated           |               53 | CURRENT_TIMESTAMP   | NO          | timestamp  |                     NULL |                   NULL |              NULL |          NULL |                  0 | NULL               | NULL               | timestamp             |            | on update CURRENT_TIMESTAMP | select,insert,update,references |                |                       |
+---------------+--------------+------------+------------------------+------------------+---------------------+-------------+------------+--------------------------+------------------------+-------------------+---------------+--------------------+--------------------+--------------------+-----------------------+------------+-----------------------------+---------------------------------+----------------+-----------------------+
53 rows in set (0.00 sec)

**Comment by netniV** [comment]
The only main differences between the two tables that I can see may be an issue are these extra fields:

TABLE_CATALOG | TABLE_SCHEMA | TABLE_NAME | COLUMN_NAME | ORDINAL_POSITION | COLUMN_DEFAULT | IS_NULLABLE | DATA_TYPE | CHARACTER_MAXIMUM_LENGTH | CHARACTER_OCTET_LENGTH | NUMERIC_PRECISION | NUMERIC_SCALE | DATETIME_PRECISION | CHARACTER_SET_NAME | COLLATION_NAME | COLUMN_TYPE | COLUMN_KEY | EXTRA | PRIVILEGES | COLUMN_COMMENT | GENERATION_EXPRESSION 
--- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | ---
def | cacti | host | manage | 35 | | NO | char | 3 | 12 | NULL | NULL | NULL | utf8mb4 | utf8mb4_unicode_ci | char(3) | | | select,insert,update,references | | 
def | cacti | host | thold_send_email | 36 | 1 | NO | int | NULL | NULL | 10 | 0 | NULL | NULL | NULL | int(10) | | | select,insert,update,references | | 
def | cacti | host | thold_host_email | 37 | NULL | NO | int | NULL | NULL | 10 | 0 | NULL | NULL | NULL | int(10) | | | select,insert,update,references | |
def | cacti | host | monitor | 38 | on | NO | char | 3 | 12 | NULL | NULL | NULL | utf8mb4 | utf8mb4_unicode_ci | char(3) | | | select,insert,update,references | | 
def | cacti | host | monitor_text | 39 | NULL | NO | mediumtext | 16777215 | 16777215 | NULL | NULL | NULL | utf8mb4 | utf8mb4_unicode_ci | mediumtext | | | select,insert,update,references | | 

If you look closely, you'll see that there are plugin columns, not the Core columns and they are all not nullable... yet the default value for some is .... NULL!

**Comment by cigamit** [comment]
Can this be closed now?  Are there any errors in the log?

**Comment by jackouille-ch** [comment]
Here is how it shows today:
![localhost2](https://user-images.githubusercontent.com/35721406/43710836-157dd020-9971-11e8-9458-8116443e13de.gif)

I also put Logs in Debug mode and got the following entries:
![image](https://user-images.githubusercontent.com/35721406/43711182-31b2c07e-9972-11e8-8304-f3d79e946a17.png)

**Comment by cigamit** [comment]
Re-install monitor and the column will be re-added.
