### ISSUE TITLE
[1.2.0] Graph edition : template is not selected by default when changing a graph

### ISSUE THREAD

**Issue by jackouille-ch** [Cacti/cacti#1759]
When editing a graph for the second time, the original graph template is replaced with the 1st on in the sorted graph list.

**Comment by netniV** [comment]
Can you provide two screenshots and highlight the chance?

**Comment by jackouille-ch** [comment]
First graph edition:
![image](https://user-images.githubusercontent.com/35721406/43317203-3b54a0f8-919c-11e8-8b11-57140082660a.png)

Filling values, saving and while reopening:
![image](https://user-images.githubusercontent.com/35721406/43317244-6aa9fc86-919c-11e8-92c1-fa7a12a968c3.png)

So you can see that graph template has been changed.

**Comment by cigamit** [comment]
This was corrected a day or so ago.

**Comment by jackouille-ch** [comment]
Could you please send the link for updated files according to this ticket please?

**Comment by jackouille-ch** [comment]
I took files from https://github.com/Cacti/cacti but it doesn't work, autocomplete doesn't work either. I was obliged to revert to my current release.
On Github, graph.php has been modified 3 months ago. And I used the develop site.
Where did you sync your files?

**Comment by cigamit** [comment]
The changes are in lib.  Your best to use a full develop sync.  

1) Just copy the cacti-develop.zip to your Linux host, 
2) unzip it to /tmp, 
3) remove the rra and log directories there, 
4) cp -rp /tmp/cacti-develop/* /your/cacti/directory
5) cd /your/cacti/directory/cli
6) upgrade_database.php or simply goto the website

**Comment by netniV** [comment]
If you do update your version to a later version of develop, it's always worth running the upgrade script again using the --force-ver=1.1.38 option so that it reapplies any of the 1.1.38 to 1.2 upgrades (including those introduced since your last download which would otherwise not get applied and cause an issue).

**Comment by cigamit** [comment]
@jackouille-ch, please use the Screen2Gif application to make an animation of the steps you are taking to reproduce this.  Upload that animation to this ticket.

**Comment by jackouille-ch** [comment]
Here it is:
![1759](https://user-images.githubusercontent.com/35721406/43368729-3c31362c-9362-11e8-86a0-e7fcb7ff35af.gif)

**Comment by jackouille-ch** [comment]
Yes from my side I still have the issue but I'm taking care when I edit graphs (some of them have over 30 data sources).
As originally written, while in graph list, the right template is displayed but when editing this graph, the first graph template is taken instead of the right one.
