### ISSUE TITLE
Data Query - Unable to click on Associated Graph Templates

### ISSUE THREAD

**Issue by BSOD2600** [Cacti/cacti#176]
It's not very clear for a user why clicking on an newly created associated graph template does not work.... until hoving over the link, where the "association read only until XML file located" is displayed.  

![image](https://cloud.githubusercontent.com/assets/5741811/21754864/c1567c18-d5bd-11e6-82cc-804868179153.png)

**Comment by cigamit** [comment]
We will handle this after the 1.0 release.

**Comment by cigamit** [comment]
I think this is a minor point and will close for now.
