### ISSUE TITLE
[1.2.0] Automatic refresh for Time Graph View - Enhancement

### ISSUE THREAD

**Issue by jackouille-ch** [Cacti/cacti#1763]
Is there a possibility to refresh automatically the page for following urls:
https://cacti.example.ch/cacti/graph_view.php?action=tree&node=tbranch-1171&site_id=-1&host_id=-1&host_template_id=-1&hgd=&hyper=true 

Meaning with refresh each 1/5/15/60 minutes and setting default value into Configuration/settings ?

**Comment by cigamit** [comment]
That page does automatically refresh.  Be more specific as I'm not sure what you are asking for.

**Comment by jackouille-ch** [comment]
Nope, I have opened this page at 19:15 and it was still the same at 21:15:
![image](https://user-images.githubusercontent.com/35721406/43369815-a319de72-9374-11e8-91df-86c8f5d08b7a.png)
And here is the page source HTML: [1763.txt](https://github.com/Cacti/cacti/files/2239095/1763.txt)

**Comment by cigamit** [comment]
Now I understand.  Correct, that page has no auto-refresh.  Let me take a quick look.

**Comment by jackouille-ch** [comment]
Thanks, which file should I download for it ?

**Comment by jackouille-ch** [comment]
Ok found, it's only graph.php

**Comment by cr4m3** [comment]
Hi guys, i've installed 1.26, i also found the commit for 1763 issue, but i experice same problem. 
On Time Graph View page there is no refresh.

There is something i've to enable?

Thanks

**Comment by netniV** [comment]
The strange thing is that this issue has no issue tags or milestone assigned to it.  Based on the date of the commit alone, it should have been 1.2.6 which was released at the beginning of September already.
