### ISSUE TITLE
[1.2.0] Graph Trees - Missing graphs

### ISSUE THREAD

**Issue by rtripon** [Cacti/cacti#1765]
Hello,
I've run into a problem after pulling the last version of 1.2.0(today, didnt upgrade for some time).
Servers says graphs are missing if I try to view them via Tree View. However if I got in console, I see the graphs, I can view them on preview mode also.
Got this errors in cacti log.

2018/07/29  18:54:38 - CMDPHP PHP ERROR NOTICE Backtrace: (/graph_view.php: 352  grow_right_pane_tree)(/lib/html_tree.php: 1206  get_host_graph_list)(/lib/html_tree.php: 1400  CactiErrorHandler)(/lib/functions.php: 4756 cacti_debug_backtrace)
--
2018/07/29 18:54:38 - ERROR PHP NOTICE: Undefined variable:  data_query_index in file: /var/www/html/cacti/lib/html_tree.php  on  line: 1400
2018/07/29 18:54:38 - CMDPHP PHP ERROR NOTICE Backtrace:  (/graph_view.php: 352 grow_right_pane_tree)(/lib/html_tree.php: 1206  get_host_graph_list)(/lib/html_tree.php: 1400  CactiErrorHandler)(/lib/functions.php: 4756 cacti_debug_backtrace)
2018/07/29 18:54:38 - ERROR PHP NOTICE: Undefined variable:  data_query_index in file: /var/www/html/cacti/lib/html_tree.php  on  line: 1400

![graph view](https://user-images.githubusercontent.com/28921178/43368151-65f2c9c2-9361-11e8-9c7c-2ffee1aa9ebc.jpg)
![preview view](https://user-images.githubusercontent.com/28921178/43368154-6aba0a1a-9361-11e8-8700-da8f9e6a4dfe.jpg)

**Comment by rtripon** [comment]
Hello,
Sadly , the problem persists, 'tho now I have no errors in logs.

**Comment by rtripon** [comment]
Any hints in what I could do? I see no error, but graphs are missing. It seems that only some hosts have this problems, for others I can see graphs.
![graphs ok](https://user-images.githubusercontent.com/28921178/43643272-7001b704-9733-11e8-845d-980ef689f193.jpg)
![graphs missing in tree mode](https://user-images.githubusercontent.com/28921178/43643289-7f099e9c-9733-11e8-94c9-af4e1b2feaae.jpg)

**Comment by netniV** [comment]
Can you export your database and email it to developers@cacti.net so we can examine the raw data?  This may be some form of corruption but without seeing what we are working with it'll be tricky to locate.

**Comment by cigamit** [comment]
Okay, I've got this fixed now.  Test again.

**Comment by rtripon** [comment]
Hello,
That it is fixed, but it seems now other plugins/functions are broken. The intropage plugin isnt working, I got this error in logs via CLI.
2018/08/07 14:25:42 - ERROR PHP NOTICE in  Plugin 'intropage': Undefined index: sess_user_id in file: /var/www/html/cacti/plugins/intropage/include/settings.php  on line: 63
2018/08/07 14:25:42 - CMDPHP PHP ERROR NOTICE Backtrace: (/index.php: 101 api_plugin_hook)(/lib/plugins.php: 74 api_plugin_run_plugin_hook)(/lib/plugins.php: 177 intropage_console_after)(/plugins/intropage/include/settings.php: 63 CactiErrorHandler)(/lib/functions.php: 4818 cacti_debug_backtrace)
2018/08/07 14:25:42 - CMDPHP ERROR: A DB Cell Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1
2018/08/07 14:25:42 - CMDPHP SQL Backtrace: (/index.php: 101 api_plugin_hook)(/lib/plugins.php: 74 api_plugin_run_plugin_hook)(/lib/plugins.php: 177 intropage_console_after)(/plugins/intropage/include/settings.php: 63 db_fetch_cell)(/lib/database.php: 293 db_fetch_cell_prepared)(/lib/database.php: 304 db_execute_prepared)(/lib/database.php: 267 cacti_debug_backtrace)
2018/08/07 14:25:42 - ERROR PHP NOTICE in  Plugin 'intropage': Undefined index: sess_user_id in file: /var/www/html/cacti/plugins/intropage/display.php  on line: 83
2018/08/07 14:25:42 - CMDPHP PHP ERROR NOTICE Backtrace: (/index.php: 101 api_plugin_hook)(/lib/plugins.php: 74 api_plugin_run_plugin_hook)(/lib/plugins.php: 177 intropage_console_after)(/plugins/intropage/include/settings.php: 69 display_information)(/plugins/intropage/display.php: 83 CactiErrorHandler)(/lib/functions.php: 4818 cacti_debug_backtrace)
2018/08/07 14:25:42 - CMDPHP ERROR: A DB Row Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1
2018/08/07 14:25:42 - CMDPHP SQL Backtrace: (/index.php: 101 api_plugin_hook)(/lib/plugins.php: 74 api_plugin_run_plugin_hook)(/lib/plugins.php: 177 intropage_console_after)(/plugins/intropage/include/settings.php: 69 display_information)(/plugins/intropage/display.php: 83 db_fetch_row)(/lib/database.php: 326 db_fetch_row_prepared)(/lib/database.php: 335 db_execute_prepared)(/lib/database.php: 267 cacti_debug_backtrace)
2018/08/07 14:25:42 - ERROR PHP NOTICE in  Plugin 'intropage': Undefined index: sess_user_id in file: /var/www/html/cacti/plugins/intropage/display.php  on line: 92
2018/08/07 14:25:42 - CMDPHP PHP ERROR NOTICE Backtrace: (/index.php: 101 api_plugin_hook)(/lib/plugins.php: 74 api_plugin_run_plugin_hook)(/lib/plugins.php: 177 intropage_console_after)(/plugins/intropage/include/settings.php: 69 display_information)(/plugins/intropage/display.php: 92 CactiErrorHandler)(/lib/functions.php: 4818 cacti_debug_backtrace)

Also, the "logout" icon/button is missing and I cant access the "LOG" button.


2018/08/07  14:35:27 - CMDPHP SQL Backtrace: (/poller.php: 845  dsdebug_poller_bottom)(/lib/dsdebug.php: 145  db_fetch_assoc)(/lib/database.php: 353  db_fetch_assoc_prepared)(/lib/database.php: 362  db_execute_prepared)(/lib/database.php: 267 cacti_debug_backtrace)
--
2018/08/07 14:35:27 - CMDPHP ERROR: A DB Row Failed!, Error: Table 'cacti.data_debug' doesn't exist
2018/08/07 14:35:26 - SYSTEM STATS:  Time:25.1473 Method:spine Processes:1 Threads:1 Hosts:210  HostsPerProcess:210 DataSources:4062 RRDsProcessed:0
2018/08/07 14:35:25 - CMDPHP SQL Backtrace:  (/poller.php: 619 process_poller_output)(/lib/poller.php: 520  dsdebug_poller_output)(/lib/dsdebug.php: 118  db_fetch_assoc)(/lib/database.php: 353  db_fetch_assoc_prepared)(/lib/database.php: 362  db_execute_prepared)(/lib/database.php: 267 cacti_debug_backtrace)
2018/08/07 14:35:25 - CMDPHP ERROR: A DB Row Failed!, Error: Table 'cacti.data_debug' doesn't exist
2018/08/07 14:35:24 - CMDPHP SQL Backtrace:  (/poller.php: 619 process_poller_output)(/lib/poller.php: 520  dsdebug_poller_output)(/lib/dsdebug.php: 118  db_fetch_assoc)(/lib/database.php: 353  db_fetch_assoc_prepared)(/lib/database.php: 362  db_execute_prepared)(/lib/database.php: 267 cacti_debug_backtrace)

**Comment by cigamit** [comment]
You need to force a database upgrade from the CLI.  Force the 1.1.38 version as your starting point.  Then, those issues will go away as long as your are running the latest develop.

**Comment by rtripon** [comment]
Tried that, but ran into some issues(I never upgraded the database from cli, all updates were made via git pull).

php  /var/www/html/cacti/cli/upgrade_database.php --debug --forcever=1_2_0.php
Invalid Cacti version 1_2_0.php, cannot upgrade to 1.2.0

Tried multiple versions(I dont have the 1.1.38.php file).

**Comment by netniV** [comment]
Use the version number before the one you are on and it'll upgrade the latest.  For 1.2.0, you use 1.1.38 since that was the last in the 1.1.x line.

If you use the web or cli installer, it will only do this once unless you set the version back in the database to the previous version.  The cli also has the ability to use --forcever=<version> to force the previous version.

I tried to update the readme earlier today to include the this information but it's not merged yet.

```
sudo -u <website user> php -q <cacti>/cli/upgrade_database.php --forcever=<version>
```
or
```
update version set cacti = '1.1.38';
```

**Comment by rtripon** [comment]
Did that...after that accesing the website it prompted me for an upgrade from 1.1.38 to 1.2.0, everthing went smooth, but the problems are still there.
The logout button is missing(I tried from different computers and browsers, it automatically logs me), I cant access the LOG from web and I have this errors on cacti.log:

2018/08/07 23:22:18 - CMDPHP ERROR: A DB Row Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1
2018/08/07 23:22:18 - CMDPHP SQL Backtrace: (/index.php: 101 api_plugin_hook)(/lib/plugins.php: 74 api_plugin_run_plugin_hook)(/lib/plugins.php: 177 intropage_console_after)(/plugins/intropage/include/settings.php: 69 display_information)(/plugins/intropage/display.php: 105 db_fetch_assoc)(/lib/database.php: 353 db_fetch_assoc_prepared)(/lib/database.php: 362 db_execute_prepared)(/lib/database.php: 267 cacti_debug_backtrace)
2018/08/07 23:22:18 - ERROR PHP WARNING in  Plugin 'intropage': Invalid argument supplied for foreach() in file: /var/www/html/cacti/plugins/intropage/display.php  on line: 107
2018/08/07 23:22:18 - CMDPHP PHP ERROR WARNING Backtrace: (/index.php: 101 api_plugin_hook)(/lib/plugins.php: 74 api_plugin_run_plugin_hook)(/lib/plugins.php: 177 intropage_console_after)(/plugins/intropage/include/settings.php: 69 display_information)(/plugins/intropage/display.php: 107 CactiErrorHandler)(/lib/functions.php: 4813 cacti_debug_backtrace)
2018/08/07 23:22:18 - ERROR PHP NOTICE in  Plugin 'intropage': Undefined index: sess_user_id in file: /var/www/html/cacti/plugins/intropage/display.php  on line: 131
2018/08/07 23:22:18 - CMDPHP PHP ERROR NOTICE Backtrace: (/index.php: 101 api_plugin_hook)(/lib/plugins.php: 74 api_plugin_run_plugin_hook)(/lib/plugins.php: 177 intropage_console_after)(/plugins/intropage/include/settings.php: 69 display_information)(/plugins/intropage/display.php: 131 CactiErrorHandler)(/lib/functions.php: 4818 cacti_debug_backtrace)
2018/08/07 23:22:18 - ERROR PHP NOTICE in  Plugin 'intropage': Undefined index: sess_user_id in file: /var/www/html/cacti/plugins/intropage/include/data.php  on line: 186
2018/08/07 23:22:18 - CMDPHP PHP ERROR NOTICE Backtrace: (/index.php: 101 api_plugin_hook)(/lib/plugins.php: 74 api_plugin_run_plugin_hook)(/lib/plugins.php: 177 intropage_console_after)(/plugins/intropage/include/settings.php: 69 display_information)(/plugins/intropage/display.php: 146 analyse_login)(/plugins/intropage/include/data.php: 186 CactiErrorHandler)(/lib/functions.php: 4818 cacti_debug_backtrace)
2018/08/07 23:22:21 - ERROR PHP NOTICE in  Plugin 'intropage': Undefined index: sess_user_id in file: /var/www/html/cacti/plugins/intropage/include/data.php  on line: 763
2018/08/07 23:22:21 - CMDPHP PHP ERROR NOTICE Backtrace: (/index.php: 101 api_plugin_hook)(/lib/plugins.php: 74 api_plugin_run_plugin_hook)(/lib/plugins.php: 177 intropage_console_after)(/plugins/intropage/include/settings.php: 69 display_information)(/plugins/intropage/display.php: 146 graph_thold)(/plugins/intropage/include/data.php: 763 CactiErrorHandler)(/lib/functions.php: 4818 cacti_debug_backtrace)
2018/08/07 23:22:21 - CMDPHP ERROR: A DB Cell Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND realm_id IN (SELECT id + 100 FROM plugin_realms WHERE file LIKE '%thold%')' at line 1
2018/08/07 23:22:21 - CMDPHP SQL Backtrace: (/index.php: 101 api_plugin_hook)(/lib/plugins.php: 74 api_plugin_run_plugin_hook)(/lib/plugins.php: 177 intropage_console_after)(/plugins/intropage/include/settings.php: 69 display_information)(/plugins/intropage/display.php: 146 graph_thold)(/plugins/intropage/include/data.php: 763 db_fetch_cell)(/lib/database.php: 293 db_fetch_cell_prepared)(/lib/database.php: 304 db_execute_prepared)(/lib/database.php: 267 cacti_debug_backtrace)
2018/08/07 23:22:21 - ERROR PHP NOTICE in  Plugin 'intropage': Undefined index: sess_user_id in file: /var/www/html/cacti/plugins/intropage/include/settings.php  on line: 111
2018/08/07 23:22:21 - CMDPHP PHP ERROR NOTICE Backtrace: (/index.php: 101 api_plugin_hook)(/lib/plugins.php: 74 api_plugin_run_plugin_hook)(/lib/plugins.php: 177 intropage_console_after)(/plugins/intropage/include/settings.php: 78 intropage_display_hint)(/plugins/intropage/include/settings.php: 111 CactiErrorHandler)(/lib/functions.php: 4818 cacti_debug_backtrace)
2018/08/07 23:22:21 - CMDPHP ERROR: A DB Cell Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1
2018/08/07 23:22:21 - CMDPHP SQL Backtrace: (/index.php: 101 api_plugin_hook)(/lib/plugins.php: 74 api_plugin_run_plugin_hook)(/lib/plugins.php: 177 intropage_console_after)(/plugins/intropage/include/settings.php: 78 intropage_display_hint)(/plugins/intropage/include/settings.php: 111 db_fetch_cell)(/lib/database.php: 293 db_fetch_cell_prepared)(/lib/database.php: 304 db_execute_prepared)(/lib/database.php: 267 cacti_debug_backtrace)
2018/08/07 23:23:31 - CMDPHP ERROR: A DB Cell Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AS id) FROM graph_templates_graph AS gtg INNER JOIN graph_local AS gl ON gl.id=g' at line 1
2018/08/07 23:23:31 - CMDPHP SQL Backtrace: (/graph_view.php: 352 grow_right_pane_tree)(/lib/html_tree.php: 878 get_allowed_graph_templates)(/lib/auth.php: 1300 db_fetch_cell)(/lib/database.php: 293 db_fetch_cell_prepared)(/lib/database.php: 304 db_execute_prepared)(/lib/database.php: 267 cacti_debug_backtrace)

**Comment by netniV** [comment]
Have you updated to today's sources? We fixed a bunch of problems so you shouldn't still have this issue.

**Comment by rtripon** [comment]
Ok then..back in business, thank you. Everything seems back to normal.
