### ISSUE TITLE
[1.2.0] CSRF error

### ISSUE THREAD

**Issue by jackouille-ch** [Cacti/cacti#1767]
I am using Let's Encrypt for my Cacti and it works fine.
But sometimes I got the following error message:
![image](https://user-images.githubusercontent.com/35721406/43369038-09423702-9367-11e8-988a-178b721e3753.png)
It's only an information and task I did previously is ignored and I must do it again.
Any hint?

**Comment by cigamit** [comment]
This is normal if you have not updated the page for a long time, by default 2 hours.  If you want to increase that, you have to change the default CSRF timeout in global.php.

**Comment by jackouille-ch** [comment]
Thanks for the answer, could you please provide an example because by default it's not in config.php.dist, neither in comment?

**Comment by netniV** [comment]
Be aware that having multiple tabs open can trigger this sooner than you think.  I don't think we moved the timeout completely to the back end yet (or did we, I forget).  We discussed this not so long back because i was constantly seeing CSRF timeouts especially as I didn't have automatic login ticked.

**Comment by jackouille-ch** [comment]
Yes that's why I always have a Tab with logs so that session is kept alive.
How can I set the timeout value? Could you please give me your config?

**Comment by netniV** [comment]
Having a tab with logs open won't actually keep your session alive s a tab without it will expire.

**Comment by jackouille-ch** [comment]
Ok I changed global.php with csrf_conf('expires', 14400);
But I will need to remember to change it each time I will use a newer release from Cacti (develop or prod).
Could it be possible to add this to config.php or directly within DB?
