### ISSUE TITLE
[1.2.0] Tree: graph not sorted

### ISSUE THREAD

**Issue by jackouille-ch** [Cacti/cacti#1768]
So graphs are sorted by inverse at the beginning:
![image](https://user-images.githubusercontent.com/35721406/43383487-74be0f64-93db-11e8-9af7-53ea91f94a5c.png)

And at the end they are not sorted:
![image](https://user-images.githubusercontent.com/35721406/43383544-9adaa50e-93db-11e8-8476-4234a527d706.png)

Changing Sorting Type doesn't change display. Are they really sorted?

**Comment by jackouille-ch** [comment]
Yes I finished editing but still the same.
Right clic shows me only Browser shortcuts. I'm suing Firefox x64

**Comment by netniV** [comment]
Right the folder whilst editing, sorry.

**Comment by jackouille-ch** [comment]
Now it's OK, without doing further changes, will see if I can reproduce it within other trees.
![image](https://user-images.githubusercontent.com/35721406/43396095-b988ea86-9400-11e8-944a-cb55e59500c9.png)

**Comment by jackouille-ch** [comment]
And I was now able to see the flying menu with right clic, very nice and usefull, congratulations.
So you can close this ticket. If I can reproduce it I will ask to reopen it.
