### ISSUE TITLE
[1.2.0] Graph edit: set bigger fields for Data Sources

### ISSUE THREAD

**Issue by jackouille-ch** [Cacti/cacti#1769]
It would be gret to have more space for data source names while editing a graph:
![graph_edit_bigger field](https://user-images.githubusercontent.com/35721406/43387267-4c796b88-93e6-11e8-90b0-17d47526cd9c.gif)

Two possibilities: 
1. check on DB which entry is the longest and use this length
2. Add space for 20 or 32 chars than default Data Source

**Comment by netniV** [comment]
The problem here is the length of the field defined in the form setup, not the backing data.  The data is an index pointer so it's just a number, whereas the entry is probably set with a small maximum value.  Should be easier enough to fix.

**Comment by netniV** [comment]
I believe this has now been addressed in a later commit.
