### ISSUE TITLE
[1.2.0] Mails are trying to be sent to Administrator

### ISSUE THREAD

**Issue by jackouille-ch** [Cacti/cacti#1772]
Since release from 2018-07-31, I got the following entries in my log:
2018/07/31  18:17:02 - MAILER Mail Failed from 'Cacti-Prod 2  <cacti@example.ch>' to 'Administrator <>', Subject:  'Cacti System Warning'
2018/07/31 18:17:02 - POLLER: Poller[Main Poller] WARNING: Poller Output Table not Empty.  Issues: 3, DS[_DC_Elec1 - CPU Stats - _Total] Graphs[_DC_Elec1 CPU _Total Usage]

These entries are coming only after the Poller warning.

**Comment by jackouille-ch** [comment]
I would like to know where I can define a valid email address (instead of <>) and how can I enable/disable it ?

**Comment by cigamit** [comment]
Look under the Authentication tab.  It defaults to the Admin account.  When you edit the Admins account, you can set an email.  I'm adding a setting momentarily to enable/disable that feature.
