### ISSUE TITLE
Lock installer to single admin

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1773]
Installer should be locked to a single admin after first page to ensure that there is not a conflict occurring between two different admins trying to upgrade at the same time.

Additionally, there should be a logout option that 'unlocks' this so another admin may take over.

**Comment by TheWitness** [comment]
This was achieved by adding a Lockout button on the Support > General page as shown below.

![image](https://github.com/user-attachments/assets/7359e755-9e88-451c-badd-acca0882a94e)

The lockout will last 30 minutes and be auto-released if the admin does not take action in 30 minutes.  The message that the admin will get on the Support > General page will look as follows:

![image](https://github.com/user-attachments/assets/077c9ccc-2a7a-47ee-ad37-1bb5ae052bd3)

Users will get this message.

![image](https://github.com/user-attachments/assets/f49d05c8-b5a6-441e-a274-485649f577e4)
