### ISSUE TITLE
CMDPHP PHP error

### ISSUE THREAD

**Issue by aliyagoob** [Cacti/cacti#1776]
08/02/2018 09:06:53 - CMDPHP PHP ERROR WARNING Backtrace: (/utilities.php: 39 repopulate_poller_cache)(/lib/utility.php: 56 poller_update_poller_cache_from_buffer)(/lib/utility.php: 541 sizeof)(CactiErrorHandler)(/lib/functions.php: 4585 cacti_debug_backtrace)
--
08/02/2018 09:06:53 - ERROR PHP WARNING: sizeof(): Parameter must be an array or an object that implements Countable in file: /var/www/html/lib/utility.php on line: 541
08/02/2018 09:04:13 - CMDPHP PHP ERROR WARNING Backtrace: (/utilities.php: 39 repopulate_poller_cache)(/lib/utility.php: 56 poller_update_poller_cache_from_buffer)(/lib/utility.php: 541 sizeof)(CactiErrorHandler)(/lib/functions.php: 4585 cacti_debug_backtrace)

**Comment by netniV** [comment]
If this is on version 1.1.38 or before, it's a known issue and usually means you are running PHP 7.2 or later.

**Comment by netniV** [comment]
see #1579
