### ISSUE TITLE
Monitor plugin is not working, New installation Cent OS 7 - cacti - 1.1.37

### ISSUE THREAD

**Issue by abhisheksahnii** [Cacti/cacti#1778]
monitor plugin is not working.

Error 1 - Plugin does not include an INFO File

created a fake file with a name INFO in the same plugin directory

$ touch INFO

Then I got another error,

Error 2 - Plugin directory is not correct. Should be "  but is 'monitor'

Selinux is permissive.

**Comment by abhisheksahnii** [comment]
Hey, 

Thanks for your prompt response - I have downloaded it from the below link,

- https://docs.cacti.net/plugin:monitor

**Comment by netniV** [comment]
Make sure you've downloaded the latest version for 1.x not for 0.8.x.  If you are unsure, there is a release on the GitHub for monitor.
