### ISSUE TITLE
Installer: Buttons are hard to see

### ISSUE THREAD

**Issue by ronytomen** [Cacti/cacti#178]
Do not know why but the theme in the install is odd and they buttons are hard to see.  The seem to blend into the background.
![screen shot 2017-01-08 at 10 12 59 pm](https://cloud.githubusercontent.com/assets/5140624/21756470/bce3a2e6-d5ef-11e6-8bf2-74b3c67d721f.png)

**Comment by cigamit** [comment]
This is a characteristic of jQueryUI 1.11.4.  Things are more bootstrap'ish in jQueryUI 1.12, but that is a large change since it's using pseudo-classes, and will require a rewrite of all the skins.  I suggest this be a feature enhancement for the next release.

**Comment by netniV** [comment]
Do we want to change the style of the buttons? They are still relatively hard to see on some screens.

![cacti install beta 2](https://user-images.githubusercontent.com/9052188/39266020-b8376a62-48c0-11e8-95e1-2918f9ff5925.gif)

We could use the same black look as the title bar to keep consistent feels?

**Comment by cigamit** [comment]
This one has effectively been addressed through the new installer.
