### ISSUE TITLE
[1.2.0] Graph edition : Search field replaced

### ISSUE THREAD

**Issue by jackouille-ch** [Cacti/cacti#1780]
Here is a very strange behaviour: I search all graphs containing We11 but while "jumping" on page 2, "We11" is replace by "Y?u", any idea ?

So in order to find the missing graphs I add the number of graph displayed but error is still present.
![search_field_changed](https://user-images.githubusercontent.com/35721406/43615076-57c49a94-96b6-11e8-9cb8-5bcb5c7a3e27.gif)

**Comment by netniV** [comment]
Looks like we've reintroduced the regex bug we had fixed previously.  Probably because of the form objects we are now storing to save a copy of data to check for changes.

And I thought I recognised it because I fixed it last time haha...
https://github.com/Cacti/cacti/issues/1268

**Comment by jackouille-ch** [comment]
Great so it means that it might be solved quickly ;-)

**Comment by cigamit** [comment]
Seems it working for me, I don't think it's really ever been fixed.  What is your systems language?  It must have something to do with other charset's other than latin1 or utf8.

**Comment by cigamit** [comment]
Also, is this 1.2?

**Comment by jackouille-ch** [comment]
It's CentOS 7 and here are the other data:
![image](https://user-images.githubusercontent.com/35721406/43626975-8fd9e0f4-96f4-11e8-91e9-8ed58247c3d5.png)
![image](https://user-images.githubusercontent.com/35721406/43627000-b10fa9c0-96f4-11e8-9e7b-652a31462d13.png)
It looks like you changed Recommanded values for DB, while I was performing install for 1.2.0, they were all black, will correct these 2 values now...

**Comment by jackouille-ch** [comment]
Nope it was me, after installation, I saw that memory was used (I put 8 GB), then I increase it to 16, my fault...
![image](https://user-images.githubusercontent.com/35721406/43627146-695226e8-96f5-11e8-9b8e-e3b0a27f4a1c.png)

**Comment by netniV** [comment]
We have an open issue for the MySQL recommendations.  The installer does not appear to be warning/erroring correctly for them.

**Comment by netniV** [comment]
Does that mean we can now close this?

**Comment by jackouille-ch** [comment]
Nope, installer was right, but as said before, I installed more RAM so your dynamic recommendation were not right, this is my fault.
Now it has been corrected (and MySQL has been restarted) but Problem is still present: searched value is replaced for page 2 as shown on my first entry.

**Comment by netniV** [comment]
Not quite sure I follow you?  If you are not meeting the recommendations and they are showing you this, that to me says that there is no issue with Cacti, it's a performance/host configuration issue.  If Cacti is telling you that your values are wrong, that then they are wrong.  

Another user recently had the same issue were he believed that he'd set his mysql configuration but in truth, it did not pick them up and did not display an error.

**Comment by netniV** [comment]
Oh wait, you are saying that the search value is being replaced.  I would recommend updating to the latest GitHub sources to be sure things are correct.  To make like easier for you, using GIT to copy (clone) and update (pull) will help during the beta testing phase.

**Comment by jackouille-ch** [comment]
Here is my current status:
![image](https://user-images.githubusercontent.com/35721406/43630526-da79ef4e-9700-11e8-85a8-39d235607aa8.png)

Ok I will use the latest sources and test it again, but not now.

**Comment by netniV** [comment]
Also check your cacti.log and apache log files for errors.  For now, I can't replicate this as I don't have any issues either.  If you can, load up the search page, do your first search, then open the chrome dev tools and click the network tab.  Then go back and click page 2 and finally post the request headers.

You may remove information you think is sensitive, but we are interested in the various form data and parameter values.

**Comment by jackouille-ch** [comment]
Ok solved with current release.
