### ISSUE TITLE
[1.2.0] Installer does not warn when mysql optimizations not set.

### ISSUE THREAD

**Issue by cigamit** [Cacti/cacti#1781]
We need to check if the recommended settings have not been followed and show the right color.  Right now, there is no warning/error.

**Comment by cigamit** [comment]
Yea, and the recommendations, though we are making progress are still not entirely complete.

**Comment by netniV** [comment]
I will check and correct this morning.

**Comment by netniV** [comment]
So, no, it would appear recommendations were always broken.  However, this has now been correct with a PR that is about to be submitted and make recommendations look as followings:

![image](https://user-images.githubusercontent.com/9052188/43635569-620efc3c-9707-11e8-8e29-cc17c3ed34e3.png)

which expands as:

![image](https://user-images.githubusercontent.com/9052188/43635611-85354806-9707-11e8-9340-ae70fc66ffe2.png)

See PR for more information as it contains corrections for a number of issues.

**Comment by netniV** [comment]
The above PR takes care of this so I'm going to close it now.
