### ISSUE TITLE
[1.1.38] Browser Back button still does not working

### ISSUE THREAD

**Issue by frontierliu** [Cacti/cacti#1783]
I haved checked in Microsoft IE/Edge, Chrome, Firefox, when I click the back button, it just change the URL, but the browser does not reload the page. It is a java script problem.

resolved in cacti/include/layout.js ,  line 1537:
origin code:

                $(window).on('popstate',` function(event) {
                        handlePopState();
                });

                $('#filter, #rfilter').keydown(function(event) {
                        if (event.keyCode == 8 && $(this).val() == '') {
                                handlePopState();
                        }
                });
                
changed to:

        $(function() {
                $(window).on('popstate', function(event) {
                        handlePopState();
                });

                $('#filter, #rfilter').keydown(function(event) {
                        if (event.keyCode == 8 && $(this).val() == '') {
                                handlePopState();
                        }
                });
        });

the resolved code also have been checked in IE/Edge, Chrome, FireFox, It works.

**Comment by cigamit** [comment]
Resolved.  I have no idea why it was buried so deep in the initialization routine.  I moved it almost to the top and seems to work for me.

**Comment by networkjackbb** [comment]
v.1.2.5
Tested with Chrome and Safari. browser back button does nothing.

**Comment by netniV** [comment]
Works for me, can you be more specific?
