### ISSUE TITLE
Create New Graph

### ISSUE THREAD

**Issue by smiles1969** [Cacti/cacti#1788]
I just updated to the most recent commit. 

I have observed odd behavior on creating new graphs. The graphic that is displayed says "Website does not have write access to folder, may be unable to create/update RRDs:"

However I have verified this is not correct, the rra folder and all rrd files have cactiuser:cacti for permissions. 

After some debugging, I noticed the fields snmp_query_id and snmp_index are blank when the new record is written to data_local table. If I manually populate these fields with the correct data, everything works as it should.

**Comment by netniV** [comment]
We are about to integrate a data source debugger which will show the user that the website runs underneath and the user that the poller runs as for a given data source. 

If the website says that it doesn’t have the permission then it should be correct as that code was only added recently and heavily tested. 

What user do they run as and what are the permissions for the folder in question?

**Comment by smiles1969** [comment]
This is a cacti instance that has been running for over a year. The OS and permissions have been correct for months and have not been touched. The data source and graph templates are the same as the last time I added a new graph for this device. The only change is the recent commit. 

The cron job for the poller is run as cactiuser:

*/1 * * * * cactiuser php /var/www/html/cacti/poller.php >> /var/log/cacti_poller.log 2>&1

the permissions for /var/www/html/cacti/rra are:

root@ctcv-cacti3:/var/www/html/cacti# ls -l |grep rra
drwxr-xr-x  2 cactiuser cacti  77824 Aug  3 17:32 rra

Like I said, if I populate 2 fields in the database table, it writes the files fine, how would that possibly be a permission issue?

Last time I had strange behavior like this after an update turned out to be missing changes to the database, but I religiously run the cli upgrade script when I upgrade so unless that process is somehow missing changes, I would rule that out.

Does this DS debugger differ from the one on Cigamits repo?

**Comment by netniV** [comment]
They are one and the same, with the integrated one having a few touch ups to make it work more in line with the base code and now also reports the running user for website and poller.  If you are using the 1.2 code, make sure you run the upgrade script with every pull just in case add something (as we did with the DSDEBUG).  

What I would do now that it is integrated, select the datasource in question and run the test.  Then post the results so we can verify things.  There is a newer function called is_resource_writable() that gets used by the graph creation and dsdebug routines to make sure that a file is writable.

One other thing, is this a normal folder or a symlink?

**Comment by smiles1969** [comment]
Folder, not symlink.. I have fixed the permissions related issue just by chmod 777 for now.

It appears there are entries in host_snmp_query that are becoming corrupted after a device data query reindex, those fields are in turn corrupting the entries in data_local.

**Comment by cigamit** [comment]
@smiles1969, is this the develop version of an earlier version?  We had two recent fixes one of which might have blown things up for a few targeted device id's.  The device id's would have been a crap shot, but always the same ones.  Please clarify.

**Comment by cigamit** [comment]
Okay, on second read, it looks like you did a recent update.  For the Data Query that is resulting in broken entries, is that a Data Query where the indexes changes frequently?  Can you please name the Data Query where this is happening?  Where did you obtain it?

**Comment by smiles1969** [comment]
This is a custom snmp data query to pull stats from a Metaswitch soft switch. I am not sure if the indexes change frequently, but it's quite possible. Wrote the query and graphs myself. I've been using them for a few years.

**Comment by cigamit** [comment]
@smiles1969, we just found a recent but.  Update to latest develop, and then rerun an upgrade from like 0.8.8h and let the poller run again.  The issue was in verify all fields handling.

**Comment by smiles1969** [comment]
Updated to latest commit, ran the cli upgrade script. Created a new graph, same issue still persists.

Graph view still shows "failed to open data file, poller may not have run yet". data_local table missing snmp_query_id and snmp_index values. 

Also, in the table host_snmp_query, the sort_field and title_format fields for this custom data query continue to get overwritten with bogus values. Not sure what triggers that, but assume its related to re-indexing as you said.

**Comment by smiles1969** [comment]
So, after digging into this a bit more. I was not seeing the same behavior for the cacti default/included interface.xml data query, as the graphs were being created fine... It would appear that my custom query was missing the  <index_order> tags. Since I only have a single input field, I apparently incorrectly assumed I didn't need to specify an order. After adding this tag to the .xml file with only a single value, my new custom graphs appear to be building correctly now.

However, If I perform a manual "reload query", the sort_field and title_format fields are still becoming corrupted.

**Comment by netniV** [comment]
Hi Smiles, 

Can you describe what this custom query does?  I am wondering I can run the same query on my network?

Mark.

**Comment by smiles1969** [comment]
It queries a Metaswitch Softswitch for available business group indexes, then uses the indexes to reference business group statistics. For example, number of internal and external lines in use. Unless you have a Metaswitch, not likely. But I would be happy to host a teamview session or set up a vpn to this cacti box.

**Comment by netniV** [comment]
Send me some details to netniv@cacti.net and lets see if I can spot anything. I don't have a full team viewer license so the VPN would likely be a better choice.

**Comment by smiles1969** [comment]
Sent to cacti.net and hotmail accounts both.

**Comment by netniV** [comment]
Thanks, been busy beavering away so haven't had chance to action it yet (as I'm sure you've noticed) ;-) . cacti.net is better as hotmail is where most junk goes heh

**Comment by cigamit** [comment]
I've just fixed a pretty major bug in Data Query Re-Index.  Hopefully this is resolved now.  Test with the latest development, and if you find that this is still happening after you have re-indexed your devices, please request to re-open.

**Comment by smiles1969** [comment]
Confirmed, this is fixed with latest commit.

**Comment by majed17** [comment]
I tried creating 64 bit multicast packets for nexus 9000 switches, (on 1.2 beta 4) and I got the error:
Website does not have write access to folder, maybeunable to create update RRDs:
/rra/
@cacti /var/www/localhost/htdocs/cacti/rra $ ls -l
total 206724
-rw-rw-r-- 1 cactiuser cacti 188464 Dec 10 10:00 acs_errors_in_65.rrd
-rw-rw-r-- 1 cactiuser cacti  94816 Dec 10 10:00 acs_traffic_in_63.rrd
-rw-rw-r-- 1 cactiuser cacti  94816 Dec 10 10:00 acs_unicast_in_64.rrd
-rw-rw-r-- 1 cactiuser cacti   5348 Mar 26  2018 auth_changepassword.php
-rw-rw-r-- 1 cactiuser cacti  14294 Mar 26  2018 auth_login.php

**Comment by netniV** [comment]
So, that would appear to be correct.  Those files are created as the user 'cactiuser' and the group 'cacti'.  Depending on your server setup, the website could be running as 'apache','ngix','www', 'www-data' or something else. If they are not part of the 'cacti' group, they will not have write access to those files.

**Comment by majed17** [comment]
ok i added the web user to cacti, but now i have a new error.
```
Failed to open data file, poller may not have run yet: 
RRA Folder: Root
```
tried restarting the web server and cron, all the rest are graphing...

**Comment by netniV** [comment]
Has a polling cycle completed?

**Comment by majed17** [comment]
Well, it has been over an hour and the rest are still graphing!

**Comment by netniV** [comment]
If you put that device debug mode (click Enable Device Debug top right when editing the device), can you see any issues?

**Comment by majed17** [comment]
Did that, also tried deleting the graphs and recreating them.
the log shows:

```
2018/12/11  08:45:19 - SYSTEM STATS: Time:17.9252 Method:spine Processes:1  Threads:1 Hosts:35 HostsPerProcess:35 DataSources:3939  RRDsProcessed:1578
--
2018/12/11 08:45:07 - SPINE: Poller[Main Poller] DEBUG: The Value of Active Threads is 0 for Device ID 26
2018/12/11 08:45:07 - SPINE: Poller[Main Poller] Device[Nexus  C] HT[1] DEBUG: HOST COMPLETE: About to Exit Device Polling Thread Function
2018/12/11 08:45:07 - SPINE: Poller[Main Poller] Device[Nexus C] HT[1] Total Time:  0.55 Seconds


```

**Comment by netniV** [comment]
That doesn't look like it has actually polled for anything, which means it wouldn't create/update the RRD file, thus you wouldn't have a graph since there is no file to create a graph from.
