### ISSUE TITLE
[1.2.0] Access to log

### ISSUE THREAD

**Issue by jackouille-ch** [Cacti/cacti#1792]
With latest release I got a strange behaviour:

![accesstolog](https://user-images.githubusercontent.com/35721406/43708984-fdd5bae6-996b-11e8-80e8-b3caab03906e.gif)

And another issue:
![accesstolog2](https://user-images.githubusercontent.com/35721406/43709003-08049d66-996c-11e8-8f15-e030572f7887.gif)

**Comment by netniV** [comment]
I've just tested this and I don't appear to have this issue.  Can you show me the permission settings for your user?  Also, try logging out and back in, see if it persists?

**Comment by jackouille-ch** [comment]
Yes that would be nice but watch my videos, logout button is no more present on top right.

**Comment by netniV** [comment]
OK, and the permissions? Also what browser?

**Comment by jackouille-ch** [comment]
It's Firefox Quantum x64 61.0.1 and permissions seems to be right:
![image](https://user-images.githubusercontent.com/35721406/43710637-782a1090-9970-11e8-9144-eb92498450c0.png)

By the way, I cannot change my permissions, is this something known or should I open a ticket?

**Comment by jackouille-ch** [comment]
Can you Log Out on your release ?

**Comment by netniV** [comment]
No, I'm having no issues with Firefox.  Looking at the function that determines authorisation, the variable is set once at session level when you goto the page.  If the system has had a problem for some reason, you will always be denied until the next session is started (once logged out).

Since you can't seem to see the logout option, trying going to <cacti>/logout.php

**Comment by jackouille-ch** [comment]
With URL/logout.php, I am still not unlogged...

**Comment by netniV** [comment]
That's weird given the first thing logout does (aside from including global) is:
```php
/* Clear session */
setcookie(session_name(), '', time() - 3600, $config['url_path']);
session_destroy();
```

**Comment by jackouille-ch** [comment]
I either try with Chrome and here is the result:
![accesstolog3](https://user-images.githubusercontent.com/35721406/43715743-d7348032-9981-11e8-9cce-11e1d77bd445.gif)

I will quit Cacti and wait one hour and log in again...

**Comment by netniV** [comment]
Try killing any cookies that you have for the site and then attempt to login in again but do not tick the save option.

**Comment by jackouille-ch** [comment]
I try to open Cacti 1.2.0 from another computer (first time on it) and I was logged automatically : not asked for user/pwd !!!
And within User log my connection didn't appear, seems to be a critical bug !

**Comment by jackouille-ch** [comment]
This is maybe the root cause while I cannot logout: because I'm not recognized as logged in

**Comment by netniV** [comment]
This is due to an issue with the read_config_option() and we have a patch coming for this.

**Comment by cigamit** [comment]
This should be resolved now.  However, I'll keep this open until @jackouille-ch updates and provides feedback.

**Comment by jackouille-ch** [comment]
Still having one error:
![image](https://user-images.githubusercontent.com/35721406/43762036-1b19f840-9a27-11e8-92af-34f53befaa13.png)

**Comment by netniV** [comment]
I'm not getting this issue which makes me suspect it's something to do with your data which we are not handling correctly.

**Comment by interduo** [comment]
It's true that I haven't data_debug table. 
Maybe some upgrade script is broken?

**Comment by interduo** [comment]
Is it possible to rerun upgrade script? 

http://cacti/install gives me
![installprogres](https://user-images.githubusercontent.com/17087236/43782102-ce32b458-9a5e-11e8-84a6-30e334eedda5.png)

**Comment by netniV** [comment]
No, wrong issue, doesn't help.  You need https://github.com/Cacti/cacti/issues/1791

**Comment by netniV** [comment]
But good to see that functionality is working 👍

**Comment by interduo** [comment]
I manualy add those table from PR and no dirty errors are in log now :)
Thanks.
