### ISSUE TITLE
Enhancement: create graphs with poling time

### ISSUE THREAD

**Issue by jackouille-ch** [Cacti/cacti#1795]
When I enter the Device list we have now the polling time, this is great.
Would it be possible to create graphs per devices with polling time?

**Comment by cigamit** [comment]
You mean create a graph template that tracks polling time?

**Comment by jackouille-ch** [comment]
Exactly

**Comment by jackouille-ch** [comment]
And why not putting other stats such as # of DS, Graphs, ping response time.
This should become a default graph for each device. Because Cacti has all these values, it might be easy to create an RRD for that purpose.

**Comment by cigamit** [comment]
Yea, I had thought about that some time ago, but there are some users of Cacti that have more than 30k devices.  So, it has to be optional.

I would be okay with adding to the default packages though.  It's a simple thing.

**Comment by jackouille-ch** [comment]
Great, thanks

**Comment by nuno-silva** [comment]
This is a good idea.

A graph/template for the global poller time would also be nice.

**Comment by cigamit** [comment]
That is pretty tricky to do.  It would have to be done at the DS level, and then rolled upto the Graph.  I could never enable that by default, but it might be a good debug option, say at the device level.  Large systems with 1M+ graphs could never keep up with double the IOPs.

**Comment by jackouille-ch** [comment]
I see something like:
- store starting time
- perform device polling
- when polling for the device is finished, calculate diff time (but this seems to be already done)
- update RRD with current time, polling time and # of OID grabbed

**Comment by TheWitness** [comment]
This has been implemented in the latest Cacti Device packages.

**Comment by jackouille-ch** [comment]
Great, thanks for it, could you please provide me the URL so that I can try?

**Comment by TheWitness** [comment]
Just use GitHub.

**Comment by TheWitness** [comment]
Oh, just install one of the newer versions of the various packages.

**Comment by jackouille-ch** [comment]
Sorry to bother you but do you have a link to provide?

**Comment by TheWitness** [comment]
Just import the Net-SNMP Device Package fro 1.2.9 or 1.2.10.

**Comment by jackouille-ch** [comment]
Are you speaking from this one ? https://docs.cacti.net/template:package:netsnmp

**Comment by TheWitness** [comment]
No, take the one from the 1.2.9 or 1.2.10 GitHub releases.

**Comment by jackouille-ch** [comment]
Please provide the URL, I checked and didn't find it on https://github.com/Cacti/cacti

**Comment by TheWitness** [comment]
Check the install/templates directory.

**Comment by jackouille-ch** [comment]
Great I was able to download the.gz file from https://github.com/Cacti/cacti/tree/develop/install/templates

But import failed, file has been decompressed and within GUI I receive the following error:
Note, we could not process all your actions. Details are below.

XML parse error.
The Template Import Failed. See the cacti.log for more details.

And within Logs:

2020/03/21 10:56:15 - IMPORT ERROR: Import or Preview failed!
--
2020/03/21 10:56:15 - IMPORT parse_xml_hash ERROR wrong hash format for hash: info

**Comment by jackouille-ch** [comment]
Sorry I forgot that imports shall be performed from CLI, import successfull
