### ISSUE TITLE
[1.2.0] Primary Admin account not set

### ISSUE THREAD

**Issue by jackouille-ch** [Cacti/cacti#1797]
I got the following error:
![image](https://user-images.githubusercontent.com/35721406/43727599-bd82bc8c-99a2-11e8-9f89-bca8db220cec.png)

How can I solve it?

**Comment by cigamit** [comment]
It's under the Console > Settings > Authentication tab.

**Comment by jackouille-ch** [comment]
Ok thanks. It was already defined as admin.

**Comment by netniV** [comment]
Does it have an email address though?

**Comment by jackouille-ch** [comment]
Yes of course but the enhancement where Mails should be sent to admin seems to be currently disabled or still under development

**Comment by netniV** [comment]
So I've checked and the messaging is not right because it's checking for both the admin user to be set, and that notifications are turned on.  However, since you may have an admin user, but not turned on notifications, the message isn't accurate so I'm going to apply a patch for this.

**Comment by cigamit** [comment]
I'm pretty happy with these fixes.  So, I'll close this now.
