### ISSUE TITLE
Default User log sort should be date descending

### ISSUE THREAD

**Issue by jackouille-ch** [Cacti/cacti#1799]
While entering into User Log, oldest entries are displayed first:
![image](https://user-images.githubusercontent.com/35721406/43728288-e873c614-99a4-11e8-8909-86da40698341.png)

Could you please reverse sorting by default?

**Comment by netniV** [comment]
We believe that most of the problems you are experiences are due to a change in the read_config_option function.  We have a patch coming that should hopefully correct it.

**Comment by cigamit** [comment]
This was is legit.  Resolved.

**Comment by jackouille-ch** [comment]
Still facing the case where oldest user log entries are displayed first

**Comment by netniV** [comment]
Mine are sorted in the correct order.  Can you double check the Display Order on Log page filters.  
-

**Comment by jackouille-ch** [comment]
Yes but try to logout and login, sort will be ascending. Current view is kept but when you login again it is reset to oldest first.

**Comment by jackouille-ch** [comment]
![logs](https://user-images.githubusercontent.com/35721406/43762771-2474d610-9a29-11e8-978d-f47fd8132f29.gif)

**Comment by netniV** [comment]
Oh OK.  That might be a different thing.  There is no sort order on that page bar the column that is selected.  However, it's likely that the filter on the clog page is the same name, thus applies when you return back to the user log.

**Comment by netniV** [comment]
This has probably always been an issue.

**Comment by netniV** [comment]
Scrap that, when I watched the gif on full screen I saw what you did.  You clicked on the date column which then sets the order. This gets stored at session level so it remembers it when you next visit the page.  However, I think the default sort order should be reverse since you aren't really interested in things from a year ago (which is the first thing that appears in mine!)

**Comment by jackouille-ch** [comment]
Exactly and in my case it's entries from 2013...

**Comment by cigamit** [comment]
Yea, my bad.  Too many other things going on.
