### ISSUE TITLE
[1.2.0-dev] - unreal memory use

### ISSUE THREAD

**Issue by pautiina** [Cacti/cacti#1800]
When I try open  graphs tab I have next error:
```
Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 7306073349089486224 bytes) in /var/www/cacti/lib/database.php on line 219
```
With commented line 219  - everything works fine

**Comment by netniV** [comment]
We have had an issue with several things due to some changes at the weekend.  There is a patch coming tonight which should hopefully resolve some of this.

**Comment by cigamit** [comment]
This is resolved now.

**Comment by pautiina** [comment]
I manually change version on database on 1.1.38 and run update and have next error on browser:
![image](https://user-images.githubusercontent.com/11805503/43758196-096125ea-9a24-11e8-8339-626a3ea37e93.png)

**Comment by netniV** [comment]
Can you paste the line of code that is at 226 of your database.php file?  I am not seeing anything wrong with this myself under PHP 7.2.7-0ubuntu0.18.04.2 and that seems to be stricter about these kind of issues.

**Comment by pautiina** [comment]
@netniV 
`                                db_echo_sql('db_' . $execute_name . '_return_func: params ' . clean_up_lines(var_export($return_array, true)) . "\n");`

**Comment by netniV** [comment]
I had a feeling you were going to say that.  I don't actually see an issue there, but you can remove both of those db_echo_sql() lines safely without causing any other issues.  They are for debugging purposes.

**Comment by pautiina** [comment]
I have just commented on this line, but I want to understand what causes the error.

**Comment by netniV** [comment]
I am guessing there is something in the data variable that is being exported that generated it because if you look at the variables actually being used, they conform to standard variable names.  If you really want to test it for me, replace the var_export() with a simple 'test' string. 

If the error still appears, that would be strange.

**Comment by pautiina** [comment]
After changing the function var_export () to simple 'test' string - the error does not appear

**Comment by pautiina** [comment]
Tried on the second server Cacti, which is a physical server - the error does not appear. I think this is the problem of a virtual machine or an version of an PHP. I will try to update everything on VM

**Comment by netniV** [comment]
Again, this is what makes me think it may be down to the host name or something similar that's appearing in the var_export()

**Comment by cigamit** [comment]
So, this could be a PHP bug?  If so, we need to find it's domain, we may have to change the way we are doing things.

**Comment by netniV** [comment]
Well, I think it's a corner case.  We wouldn't normally var_export the parameters so it's a developer issue really  especially now that the debugging options are merged properly.

**Comment by pautiina** [comment]
I have not yet updated all the packages. This process is long time on FreebSD, since I'm updating everything from ports.

**Comment by netniV** [comment]
They've ported 1.2 already?? That shouldn't be the case as its not been released.

**Comment by pautiina** [comment]
I use git to update cactus, and for other packages use ports tree, including php I install from ports.

**Comment by netniV** [comment]
Oh, in that case, what I've said above is correct.  It'll be something to do with the variable being exported I reckon.  And that won't occur now if you update via git to the latest changes we made.

**Comment by pautiina** [comment]
I saw what variables you define for debugging: https://github.com/Cacti/cacti/commit/147c152eb7ef6d7d5649c42703d1ec23bf929efc

**Comment by netniV** [comment]
Yeah, those changes should prevent that warning from appearing.

**Comment by pautiina** [comment]
After update php and define next options:

```
define('DEBUG_READ_CONFIG_OPTION', true);
define('DEBUG_READ_CONFIG_OPTION_DB_OPEN', true);
define('DEBUG_SQL_CMD', true);
define('DEBUG_SQL_FLOW', true);
```
and fixes issue #1814 all works fine

**Comment by netniV** [comment]
You should leave the above defines active unless you really need them.

**Comment by pautiina** [comment]
In production I will not use these options, but when debugging, I think they will help me and you :)
And I still think the problem is with PHP. After the update, everything is fine
