### ISSUE TITLE
Installer: Template Setup

### ISSUE THREAD

**Issue by ronytomen** [Cacti/cacti#181]
![screen shot 2017-01-08 at 10 21 46 pm](https://cloud.githubusercontent.com/assets/5140624/21756578/e8b0a90e-d5f0-11e6-82c5-2c024c2c991b.png)

There should be a warning if permissions will not allow the correct installation of the templates at install time.

![screen shot 2017-01-08 at 10 23 19 pm](https://cloud.githubusercontent.com/assets/5140624/21756589/1986abdc-d5f1-11e6-89bf-110daeeef431.png)

Clicking the row did not always allow the checking of the box.  Clicking of the box does not check the checkbox, odd....  Also, you can get the row highlight out of sync with the checkbox.

**Comment by cigamit** [comment]
Right now, until permissions are correct, you can not progress to this page.  So, point 1 is covered already.

The second issue was resolved in this commit.

https://github.com/Cacti/cacti/commit/3c3a83b1a00e657e87c8e6b62450cff661858cff
