### ISSUE TITLE
Log errors after update

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#1811]
2018/08/07  16:05:30 - CMDPHP SQL Backtrace: (/poller.php: 845  dsdebug_poller_bottom)(/lib/dsdebug.php: 145  db_fetch_assoc)(/lib/database.php: 353  db_fetch_assoc_prepared)(/lib/database.php: 362  db_execute_prepared)(/lib/database.php: 267 cacti_debug_backtrace)
--
2018/08/07 16:05:30 - CMDPHP ERROR: A DB Row Failed!, Error: Table 'cacti.data_debug' doesn't exist
2018/08/07 16:05:28 - SYSTEM STATS: Time:26.5536 Method:spine  Processes:1 Threads:1 Hosts:503 HostsPerProcess:503 DataSources:7317  RRDsProcessed:4234
2018/08/07 16:05:28 - CMDPHP SQL Backtrace: (/poller.php: 604  process_poller_output)(/lib/poller.php: 520  dsdebug_poller_output)(/lib/dsdebug.php: 118  db_fetch_assoc)(/lib/database.php: 353  db_fetch_assoc_prepared)(/lib/database.php: 362  db_execute_prepared)(/lib/database.php: 267 cacti_debug_backtrace)
2018/08/07 16:05:28 - CMDPHP ERROR: A DB Row Failed!, Error: Table 'cacti.data_debug' doesn't exist

**Comment by netniV** [comment]
This was already answered here: https://github.com/Cacti/cacti/issues/1792

**Comment by interduo** [comment]
Sorry for double. I did not try to find that in smart way ;)

**Comment by netniV** [comment]
No worries.  A quick close looks good on our stats... if we were maintaining any that is haha

**Comment by netniV** [comment]
Oh wait, I linked the wrong issue: https://github.com/Cacti/cacti/issues/1791
