### ISSUE TITLE
Grapical ON/OFF switches in Settings

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#1813]
Now - You need to learn how does that works.
Those indicators should be red when off and green when on.

I am talking about this
![indicators](https://user-images.githubusercontent.com/17087236/43784998-b7c8e69a-9a65-11e8-8a2c-2f893c185b0d.png)

**Comment by netniV** [comment]
I think it’s fairly obvious, dark land left off light and right on. Red doesn’t really go with the theme either. The dark themes are not so obvious so we will be changing the colour to be the selection colour

**Comment by interduo** [comment]
The obvious is only the color red and green. Left and right side is not so obvious. There are many places even in many machines where the directions - speaking polite are fucked up. People use cacti in many countries even in those where are writing from right to left.

I suggest don't use directions as only way to tell the user of the switch state.  In my opinion this switch is too less noticeable on first look.

**Comment by netniV** [comment]
Tooltip should definitely be included to make things obvious.

**Comment by interduo** [comment]
But You need to hover. Make things simpler not harder. :)

**Comment by interduo** [comment]
Red color is not as bad as You think in theme. Maybe You don't need to fill the whole switch but do only distinction by setting red color to border?

**Comment by cigamit** [comment]
Tooltip messages are back due to this commit: https://github.com/Cacti/cacti/commit/76e9691bfc515c843ed37c38b178f1d05bcec1a0

I've thought about appending some status text along with the tooltip, but have not locked in on that yet.

**Comment by cigamit** [comment]
I'm going to close this.  People who have been around gui's long enough will figure this out in like < 5 seconds.

**Comment by cigamit** [comment]
You have this week to make a suggestion in the form of a pull request.  It's not a high priority for me.

**Comment by interduo** [comment]
OK :)

Is Your roadmap publicly shared?

**Comment by netniV** [comment]
Not currently as it's very much dependant on our personal lives and how much time we can release to the group work.

**Comment by interduo** [comment]
I completly understand that! :) Maybe You could do some Roadmap but without dates?
I don't want to get a date with releases but would only like to know about the features You will code in future.

**Comment by interduo** [comment]
I do also very admire and appreciate Your work! Thanks :)

**Comment by netniV** [comment]
Generally speaking, it's either in our heads as an idea for improvement, or more often than not, created as an issue on the relevant repo, then marked as 'Enhancement'.  If it's going to be in a given release, it'll get a Milestone too.

**Comment by netniV** [comment]
For example, this is the list of milestone attributed issues that exist (closed means either dealt with or felt unwarranted):
https://github.com/Cacti/cacti/issues?page=1&q=is%3Aissue+milestone%3A%22Cacti+1.2%22&utf8=%E2%9C%93
