### ISSUE TITLE
[1.2.0] - use high space on disk

### ISSUE THREAD

**Issue by pautiina** [Cacti/cacti#1816]
I deleted define option about debug from  file: `include/config.php`
But the size of the files **/var/tmp/cacti-option.log** and **/var/tmp/cacti-sql.log** is constantly growing

**Comment by cigamit** [comment]
Well that is odd.  I'll let @netniV answer this one.

**Comment by pautiina** [comment]
```
[root@noc /var/www/cacti]# ls -lah /tmp/cacti-*
-rw-r--r--  1 root  wheel   1,1G  8 авг.  02:03 /tmp/cacti-option.log
-rw-r--r--  1 root  wheel   127K  8 авг.  02:03 /tmp/cacti-sql.log
[root@noc /var/www/cacti]#

```

**Comment by netniV** [comment]
Quick fix whilst I investigate is to set the variables in `include/global.php` to false rather than using `defined()`.  The false setting should stop it as false is counted as empty.

**Comment by netniV** [comment]
OK, that's weird because I'm not getting the logs.  If you had only just removed the defines, it's possible the poller was still running.

**Comment by pautiina** [comment]
I killed all the processes of spine. So far this has helped. Now to sleep. Tomorrow I'm test it . I had to restore the database due to disk overflow: (

**Comment by pautiina** [comment]
Today I tested again the options:

```
define('DEBUG_READ_CONFIG_OPTION', true);
define('DEBUG_READ_CONFIG_OPTION_DB_OPEN', true);
define('DEBUG_SQL_CMD', true);
define('DEBUG_SQL_FLOW', true);
```

After a while I turned off these options, but the file size continues to grow. Also I tried to kill all of the poller's - but that does not help.

```
[root@noc /var/www/cacti]# ls -lah /tmp/cacti-*
-rw-r--r--  1 www  wheel   3,7G  8 авг.  10:10 /tmp/cacti-option.log
-rw-r--r--  1 www  wheel   4,3M  8 авг.  10:10 /tmp/cacti-sql.log
[root@noc /var/www/cacti]#
```

**Comment by netniV** [comment]
If you look in the files, they will have a process id after the date and time.  Check that process id is changing and not the same one.  Also, what OS are you running on?  These files being in /tmp/ suggest it's a cli based script that's running.

**Comment by pautiina** [comment]
```
<[ 2018-08-08 10:25:32.305455 |   33498 ]> -- db_fetch_row_prepared('SELECT value FROM settings WHERE name = ?', $params = ('selective_debug'), $log = , $db_conn = false)
<[ 2018-08-08 10:25:32.579211 |   33563 ]> -- db_fetch_row_prepared('SELECT value FROM settings WHERE name = ?', $params = ('selective_debug'), $log = , $db_conn = false)
<[ 2018-08-08 10:25:32.934284 |   33498 ]> -- db_fetch_row_prepared('SELECT value FROM settings WHERE name = ?', $params = ('selective_debug'), $log = , $db_conn = false)
<[ 2018-08-08 10:25:33.156717 |   33563 ]> -- db_fetch_row_prepared('SELECT value FROM settings WHERE name = ?', $params = ('selective_debug'), $log = , $db_conn = false)
<[ 2018-08-08 10:25:33.564361 |   33498 ]> -- db_fetch_row_prepared('SELECT value FROM settings WHERE name = ?', $params = ('selective_debug'), $log = , $db_conn = false)
<[ 2018-08-08 10:25:33.746211 |   33563 ]> -- db_fetch_row_prepared('SELECT value FROM settings WHERE name = ?', $params = ('selective_debug'), $log = , $db_conn = false)
<[ 2018-08-08 10:25:34.136987 |   33498 ]> -- db_fetch_row_prepared('SELECT value FROM settings WHERE name = ?', $params = ('selective_debug'), $log = , $db_conn = false)
<[ 2018-08-08 10:25:34.282270 |   33563 ]> -- db_fetch_row_prepared('SELECT value FROM settings WHERE name = ?', $params = ('selective_debug'), $log = , $db_conn = false)
<[ 2018-08-08 10:25:34.704382 |   33498 ]> -- db_fetch_row_prepared('SELECT value FROM settings WHERE name = ?', $params = ('selective_debug'), $log = , $db_conn = false)

```

And after the next killall of the process /var/www/cacti/poller.php the file growth stopped

**Comment by pautiina** [comment]
The problem is solved only by killing all processes poller.php.

If you forget about these options, then you can make trouble in the system.
Now the problem is solved. I think you can close the ticket.
For information  - I use FreeBSD

**Comment by netniV** [comment]
OK so if you have your poller set to run for 5 minutes, it will take five minutes for the change to take effect when it recycles.  However, these options you tested out are purely for developers who are testing the low level stuff and should not normally be used.  This is why thy are turned off by default.
