### ISSUE TITLE
Removing Graphs using CLI

### ISSUE THREAD

**Issue by grotnicki** [Cacti/cacti#1819]
I'm using a script that scans network and checks for new interfaces to add to Cacti. It also checks for old unused interfaces that are already in Cacti and needs to be deleted.

It would be nice to be able to delete graphs and data sources using CLI.

**Comment by gadzet21** [comment]
I confirm,, I'm looking forward to have this one as well.

**Comment by netniV** [comment]
Fancy having a crack at a PR? We are currently trying to round things off for a 1.2 beta, so we aren't looking to introduce new features right now.  However, if you have the time and manage to produce something usable, we may include it.

**Comment by cigamit** [comment]
Resolved.  Please feel free to test.
