### ISSUE TITLE
[1.2.0] Syslog Plugin 1.22 not working

### ISSUE THREAD

**Issue by jackouille-ch** [Cacti/cacti#1822]
I took the Syslog plugin and install it but it seems to have a problem:
![syslog](https://user-images.githubusercontent.com/35721406/43968960-f633dc4a-9cc8-11e8-9345-795048db6e5a.gif)

How can I solve it ?

**Comment by cigamit** [comment]
You need to use the plugin from
https://github.com/Cacti/plugin_syslog
Also, you should use the Issue tracker on there for any issues
