### ISSUE TITLE
[1.2.0] Cannot delete Data Sources

### ISSUE THREAD

**Issue by jackouille-ch** [Cacti/cacti#1823]
I tried to delete a DS and while selecting Action Delete, all rows are grayed and individual rows cannot be selected:
![deleteds](https://user-images.githubusercontent.com/35721406/43969500-9c03d2c8-9cca-11e8-9f73-129e22d03944.gif)

**Comment by cigamit** [comment]
You see how it says Deletable: No and Active: Yes?  That means it has a graph associated with it.  Delete it instead.
