### ISSUE TITLE
CMDPHP Validation Error, Variable:graph_start, Value:-undefined Backtrace: (/graph_realtime.php

### ISSUE THREAD

**Issue by Izmenoff** [Cacti/cacti#1828]
Cacti 1.1.37
10.2.16-MariaDB

Plz, hepl to fix it:

13-Aug-2018 09:26:57 - CMDPHP Validation Error, Variable:graph_start, Value:-undefined Backtrace: (/graph_realtime.php: 44 get_filter_request_var)(/lib/html_utility.php: 443 die_html_input_error)(/lib/html_validate.php: 64 cacti_debug_backtrace)
--
2018-08-13 09:26:57 - DBCALL DEVEL: SQL Cell: "SELECT cacti FROM version LIMIT 1"
2018-08-13 09:26:57 - DBCALL DEVEL: SQL Exec: "SET SESSION sql_mode = "NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION""
2018-08-13 09:26:57 - DBCALL DEVEL: SQL Cell: "SELECT @@sql_mode"

**Comment by netniV** [comment]
There should be a corresponding message on the screen saying why it failed and what the name of the variable was that caused the failure.  Based of the line number, I would say that graph_start is not a number.

**Comment by Izmenoff** [comment]
it is all
![image](https://user-images.githubusercontent.com/17400240/44019201-c863a320-9ee6-11e8-9012-88821936e428.png)

**Comment by netniV** [comment]
The point is, something is accessing the realtime page and does not have a valid graph_start parameter when doing so.  You need to find out what is causing that.

**Comment by Izmenoff** [comment]
netniV, thanks. I will find the reason

**Comment by cigamit** [comment]
This was resolved in the 1.2 branch already.
