### ISSUE TITLE
[1.2.0] Device list incomplete

### ISSUE THREAD

**Issue by jackouille-ch** [Cacti/cacti#1829]
While in Graph Management, only 44 devices are selectable:
![missingdevices](https://user-images.githubusercontent.com/35721406/44025460-83692e7a-9ef0-11e8-8ab6-cc66ca33f3e0.gif)
You can see that devices starting with TVT are missing for example

**Comment by netniV** [comment]
This is by design.  The dropdown is actually an auto-complete box.  In order to speed up the UI, we only select the first x amount (a configurable option under settings).  If you were to start typing the name of the device, you will find the dropdown starts to filter down to what you've typed.

**Comment by jackouille-ch** [comment]
Great, thanks for your feedback.
Mybe you could add a small icon with AC (Auto Complete) before such kind of auto completed fields, this might avoid dummy requests as this one
