### ISSUE TITLE
Graphs not showing created in `New Graphs`

### ISSUE THREAD

**Issue by ronytomen** [Cacti/cacti#183]
![screen shot 2017-01-08 at 10 35 39 pm](https://cloud.githubusercontent.com/assets/5140624/21756723/e4337fda-d5f2-11e6-9972-ed2c9740862d.png)

All but 5 of these graphs have been created.  But they are not "disabled" looking, I can not click them, but they do look like you can.

**Comment by cigamit** [comment]
Resolved, thanks!
