### ISSUE TITLE
thold graph (can not get data)

### ISSUE THREAD

**Issue by Initarts** [Cacti/cacti#1830]
The threshholds  item can not get the current value.  why
![thold1](https://user-images.githubusercontent.com/8800508/44027566-923973cc-9f29-11e8-90b9-d93e5f925283.png)
![thold2](https://user-images.githubusercontent.com/8800508/44027578-9b1b082a-9f29-11e8-9ed9-34cc35f3220d.png)
![thold3](https://user-images.githubusercontent.com/8800508/44027589-9f13304c-9f29-11e8-9484-24c8cc11c821.png)

How can we get the right data? can you help me? thanks

**Comment by cigamit** [comment]
This is not the proper place for this issue.  The plugin has its own Issue Tracker.  
https://github.com/Cacti/plugin_thold
