### ISSUE TITLE
[1.2.0] Graph export

### ISSUE THREAD

**Issue by jackouille-ch** [Cacti/cacti#1832]
I didn't find the configuration setting for export graphs.
I need to export only a few graphs but with all timestamps (Daily, Weekly, Monthly, etc).
How should I proceed?

**Comment by netniV** [comment]
You need to check out the graph export plugin which is separated as of 1.0.0.  This is find on the cacti.net website, with the repository at: https://github.com/cacti/plugin_gexport/

As such, any issues relating to Graph Export should be opened there.
