### ISSUE TITLE
1.2 Does not allow for multiple processes

### ISSUE THREAD

**Issue by rich9000** [Cacti/cacti#1833]
No matter what the setting is in the DB there is always only one process running. The code has a typo that always resolves as false setting the number of processes to 1. 

Starting at line 187 poller.php

if (!isset(**$concurrent_process**) || **inval**($concurrent_processes) < 1) {
	$concurrent_processes = 1;
}

$concurrent_process does not exist. It should be $concurrent_processes and inval probably should be intval. I do not know why it didn't throw and error for inval so it must be defined somewhere.

**Comment by netniV** [comment]
This is a problem in the code, as the function should have been intval()

**Comment by cigamit** [comment]
Resolved, good catch!

**Comment by rich9000** [comment]
$concurrent_process needs to be $concurrent_processes. $concurrent_process is undefined and will always be unset. $concurrent_processess will always = 1 as a result.

**Comment by cigamit** [comment]
Got it
