### ISSUE TITLE
PHP ERROR NOTICE Backtrace: (/graphs_new.php

### ISSUE THREAD

**Issue by liketommy** [Cacti/cacti#1838]
Hi, please help. I can't solve this problem. 
I'm Cacti user in ver 1.1.38. When I trying added new graphs to device from template, nothing is added.
Devices, which I had added before works properly.
And in logtrace I retrieve below notification:

CMDPHP PHP ERROR NOTICE Backtrace: (/graphs_new.php: 37 form_save)(/graphs_new.php: 123 host_new_graphs)(/graphs_new.php: 397 host_new_graphs_save)(/graphs_new.php: 264 CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)

ERROR PHP NOTICE: Undefined index: local_data_id in file: /var/www/c2/graphs_new.php on line: 264

![image](https://user-images.githubusercontent.com/42421490/44173574-a8358b80-a0e0-11e8-96d8-81071e8b2ad7.png)

Name C2 is correct. This is my default path to new Cacti.

**Comment by cigamit** [comment]
You need to explain how you are using the interface.  Use screen2gif to make an animation and upload it.

**Comment by liketommy** [comment]
I was forced to take steps that eventually solved the problem. I've reinstalled the whole environment. Most likely **I did not execute some commands during the migration process** and that caused later problems.  Now the system is working properly. 
The installation instructions should be read with the correct accuracy. Before better ;) 
Thank you very much for your willingness to help.
