### ISSUE TITLE
[1.1.37 - 1.2]Dummy cosmetic bug on down device selection option

### ISSUE THREAD

**Issue by jpobeda** [Cacti/cacti#1839]
When you select type ping it shows you by default 'UDP Ping' method which by the look of the options (eg.: not showing udp port) is really ICMP Ping instead.

![2018-08-16_09-24-04](https://user-images.githubusercontent.com/13456559/44174486-62f07880-a137-11e8-898f-8ae47232b4f5.gif)

Tested on 1.2.x and 1.1.37

**Comment by netniV** [comment]
That is an interesting one, almost like it doesn’t think there is a value selected even though there should be.

**Comment by cigamit** [comment]
Resolved.
