### ISSUE TITLE
[1.2.0] Error after upgrade

### ISSUE THREAD

**Issue by jackouille-ch** [Cacti/cacti#1840]
I took the latest release from today (2018/08/17) and got the following error within logs:
![image](https://user-images.githubusercontent.com/35721406/44252602-fb046580-a1fc-11e8-973b-1527194e3bc3.png)

**Comment by netniV** [comment]
Would have been easier to check for a define and if not exist, include the contents after defining said control define. However, will take a full look at the error later.

**Comment by jackouille-ch** [comment]
Sorry but it was blocking all pollings so I made the easiest for me in order to not perform a version rollback.

**Comment by netniV** [comment]
Yeah, I appreciate that, just letting your know of an easier way if you believe it becomes the entire file.  On my way to the day job at the moment and I’ve overslept so won’t be able to look at it till later.

**Comment by jackouille-ch** [comment]
I didn't know the structure from Cacti but now it works for me again so I can wait. Have a good working day

**Comment by cigamit** [comment]
This should be resolved now.  Can you please update to the latest develop and confirm.

**Comment by dsclassen** [comment]
I just pulled commit 28062bef02d63446e2992bf39dccef1f53794bd8 and I'm getting this error.

**Comment by netniV** [comment]
I thought that had been resolved.  I know that my system doesn't have the error, so I may create a patch that has my resolution.

**Comment by jackouille-ch** [comment]
Sorry for the delay, I just got time to upgrade with commit a574fd9.

I also performed the following:
cp -rp /tmp/cacti-develop/* /usr/share/cacti
chown -R apache.apache /usr/share/cacti/resource/
chown -R apache.apache /usr/share/cacti/scripts
chown -R apache.apache /usr/share/cacti/cache/

But still got the same error:
![image](https://user-images.githubusercontent.com/35721406/44617140-f1fb4000-a85d-11e8-8716-7bc8d1b95294.png)

I also correct lib/reports.php such as follow and it works now:
[reports-20180825.txt](https://github.com/Cacti/cacti/files/2320553/reports-20180825.txt)

And now it works again:
![image](https://user-images.githubusercontent.com/35721406/44617155-3a1a6280-a85e-11e8-8892-49c0380a0f16.png)

The big problem when this occurs is that polling doesn't work so I lose data..

**Comment by jackouille-ch** [comment]
And now I got sometimes the following errors:
![image](https://user-images.githubusercontent.com/35721406/44619950-51247900-a88d-11e8-9475-a261b6d9160a.png)

**Comment by cigamit** [comment]
You need to update all the files, not just cherry pick.  Please update the entire cacti.

**Comment by jackouille-ch** [comment]
That's what I did this morning:
root@cacti2:/usr/share/cacti# ll
total 2248
-rw-r--r--   1 root   root     4348 Aug 24 16:07 about.php
-rw-r--r--   1 root   root    56511 Aug 24 16:07 aggregate_graphs.php
-rw-r--r--   1 root   root    18116 Aug 24 16:07 aggregate_items.php
-rw-r--r--   1 root   root    24252 Aug 24 16:07 aggregate_templates.php
-rw-r--r--   1 root   root    13661 Aug 24 16:07 auth_changepassword.php
-rw-r--r--   1 root   root    28124 Aug 24 16:07 auth_login.php
-rw-r--r--   1 root   root    16078 Aug 24 16:07 auth_profile.php
-rw-r--r--   1 root   root    22616 Aug 24 16:07 automation_devices.php
-rw-r--r--   1 root   root    36837 Aug 24 16:07 automation_graph_rules.php
-rw-r--r--   1 root   root    42719 Aug 24 16:07 automation_networks.php
-rw-r--r--   1 root   root    30200 Aug 24 16:07 automation_snmp.php
-rw-r--r--   1 root   root    18890 Aug 24 16:07 automation_templates.php
-rw-r--r--   1 root   root    38698 Aug 24 16:07 automation_tree_rules.php
-rw-r--r--   1 root   root     2946 Aug 24 16:07 boost_rrdupdate.php
drwxr-xr-x   6 apache apache     80 Jul 29 10:01 cache
lrwxrwxrwx   1 root   root       20 Aug 22 21:46 cache;5b7dbd87 -> /var/lib/cacti/cache
-rw-r--r--   1 root   root   120497 Aug 24 16:07 cacti.sql
-rw-r--r--   1 root   root    29214 Aug 24 16:07 cdef.php
drwxr-xr-x   2 root   root     4096 Aug 17 08:53 cli
-rw-r--r--   1 root   root     1900 Aug 24 16:07 clog.php
-rw-r--r--   1 root   root     1906 Aug 24 16:07 clog_user.php
-rw-r--r--   1 root   root    30301 Aug 24 16:07 cmd.php
-rw-r--r--   1 root   root     8778 Aug 24 16:07 cmd_realtime.php
-rw-r--r--   1 root   root    24421 Aug 24 16:07 color.php
-rw-r--r--   1 root   root    13194 Aug 24 16:07 color_templates_items.php
-rw-r--r--   1 root   root    22238 Aug 24 16:07 color_templates.php
-rw-r--r--   1 root   root    12911 Aug 24 16:07 data_debug.php
-rw-r--r--   1 root   root    34670 Aug 24 16:07 data_input.php
-rw-r--r--   1 root   root    49431 Aug 24 16:07 data_queries.php
-rw-r--r--   1 root   root    34498 Aug 24 16:07 data_source_profiles.php
-rw-r--r--   1 root   root    60596 Aug 24 16:07 data_sources.php
-rw-r--r--   1 root   root    41343 Aug 24 16:07 data_templates.php
drwxr-xr-x   3 root   root       65 Aug 25 11:24 docs
lrwxrwxrwx   1 cacti  apache     18 Jul 23 09:34 export -> /home/cacti/graphs
-rw-r--r--   1 root   root     6405 Aug 24 09:15 export-VMN.php
drwxr-xr-x   2 root   root      150 Aug 25 11:24 formats

You can see the commit release and the time where I perform the copy (Aug 25 at 11:24)

**Comment by cigamit** [comment]
This is fully resolved now.
