### ISSUE TITLE
Data Source Stats table not properly migrated from pre 1.x Cacti plugin

### ISSUE THREAD

**Issue by jackouille-ch** [Cacti/cacti#1841]
I think I already got this error previously:
![image](https://user-images.githubusercontent.com/35721406/44255144-55092900-a205-11e8-8eed-b3614fbc9bea.png)

**Comment by netniV** [comment]
In MySQL, can you do:
```sql
SHOW CREATE TABLE `data_source_stats_hourly_last`\G
```

**Comment by jackouille-ch** [comment]
mysql> SHOW CREATE TABLE `data_source_stats_hourly_last`;
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table                         | Create Table                                                                                                                                                                                                                                                                                                                                                            |
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| data_source_stats_hourly_last | CREATE TABLE `data_source_stats_hourly_last` (
  `local_data_id` mediumint(8) unsigned NOT NULL,
  `rrd_name` varchar(19) COLLATE utf8mb4_unicode_ci NOT NULL,
  `value` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL,
  `calculated` double NOT NULL,
  PRIMARY KEY (`local_data_id`,`rrd_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci |
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

**Comment by netniV** [comment]
I think the simple answer is to allow NULL's, so I'm going to update the code to do this. You will need to either manually change the columns, or use the `sudo -u <website user> php -q update_database.php --forcever=1.1.38` once the patch is merged.

**Comment by netniV** [comment]
Actually, I have just looked at the installation code, they all have it set to NULL, and not NOT NULL.  So, the question becomes, how did they change?  Change your DB to NULL and the problem should go away.

**Comment by cigamit** [comment]
This issue is that the value column is supposed to be the following:

`value DOUBLE DEFAULT NULL`

The following query will resolve:

`alter table data_source_stats_hourly_last modify column value double default null;`

**Comment by cigamit** [comment]
You might want to verify your data_source_stats% schema columns against the default.  I suspect this is an upgrade error.  You were likely running dsstats before 1.x.

**Comment by cigamit** [comment]
Okay, this is resolved.  You can either run the command above, or just force the upgrade_database.php again.
