### ISSUE TITLE
[1.2.0] Automation error, just hangs

### ISSUE THREAD

**Issue by sam-san91** [Cacti/cacti#1842]
Log leaves something like:
`2018-08-17 16:53:22 - ERROR PHP ERROR: Uncaught Error: Call to undefined function create_complete_graph_from_template() in /usr/share/cacti/lib/api_automation.php:2432 Stack trace: #0 /usr/share/cacti/lib/api_automation.php(2135): create_dq_graphs('3', '1', Array) #1 /usr/share/cacti/lib/api_automation.php(3759): automation_execute_data_query('3', '1') #2 /usr/share/cacti/host.php(377): automation_update_device('3') #3 /usr/share/cacti/host.php(62): form_actions() #4 {main} thrown in file: /usr/share/cacti/lib/api_automation.php on line: 2432`

Problem is in the function of the given line the lib/template.php is missing
Should be like this:
```
function create_dq_graphs($host_id, $snmp_query_id, $rule) {
        global $config, $automation_op_array, $automation_oper;
        include_once($config['base_path'] . '/lib/template.php');
```

Don't know how to do a pull request 😆

**Comment by sam-san91** [comment]
The current develop version

**Comment by netniV** [comment]
When you say Develop, do you have the commit or the date you downloaded it?

**Comment by netniV** [comment]
Never mind, I've double checked and confirmed that there is no include_once.  That may have to be at the top of the file for completeness.  So that it has been included no matter what.

**Comment by cigamit** [comment]
Resolved.  Thanks for reporting.
