### ISSUE TITLE
SNMPAgent not sending traps

### ISSUE THREAD

**Issue by atl30339-dev** [Cacti/cacti#1849]
SNMPAgent not sending traps nor receiving logs on Cacti 1.1.38
A solution was found in https://forums.cacti.net/viewtopic.php?f=17&t=58470
Need the development team to review, amend and include the fix to the source branch for future release.

**Comment by cigamit** [comment]
Thanks for reporting.  Just in time for beta!

**Comment by cigamit** [comment]
Resolved.  Update the forums is you would please.
