### ISSUE TITLE
Issue in cacti automation

### ISSUE THREAD

**Issue by vaghelabhavesh32** [Cacti/cacti#1851]
i am using cacti 1.1.36, i fount device and object matched in graph rules under automation option but it is not able to  create automatic graph for matched object..
Note : device is already added no automation rules for device..
![cacti issue](https://user-images.githubusercontent.com/42531502/44322889-34430c80-a46d-11e8-8ab9-91659850d113.png)
(url)

**Comment by netniV** [comment]
You can turn on debugging for automation, which will show you all the steps it takes.  However, it's not very readable before 1.2.  It requires a little bit of detective work to understand the debug in 1.1.38 and before but that would be your best bet to see why something is missing.

**Comment by cigamit** [comment]
No feedback.
