### ISSUE TITLE
overload every night

### ISSUE THREAD

**Issue by Izmenoff** [Cacti/cacti#1856]
Hello,
Has Cacti some task in 02:30-02:40 am ? CPU overload and poller doesn't enough time for polling all devices and I have graphs with lost information. The problem repeat every night except weekend.
In crontab nothing crime.

_21-Aug-2018 02:36:29 - SYSTEM STATS: Time:27.4013 Method:spine Processes:1 Threads:50 Hosts:405 HostsPerProcess:405 DataSources:32558 RRDsProcessed:15610
21-Aug-2018 02:36:25 - SYSTEM THOLD STATS: Time:0.3180 Tholds:27 TotalDevices:405 DownDevices:30 NewDownDevices:0
21-Aug-2018 02:35:47 - SYSTEM STATS: Time:42.0390 Method:spine Processes:1 Threads:50 Hosts:405 HostsPerProcess:405 DataSources:32559 RRDsProcessed:15610
21-Aug-2018 02:34:42 - SYSTEM STATS: Time:40.2230 Method:spine Processes:1 Threads:50 Hosts:405 HostsPerProcess:405 DataSources:32556 RRDsProcessed:15614
21-Aug-2018 02:33:42 - SYSTEM THOLD STATS: Time:0.5836 Tholds:29 TotalDevices:405 DownDevices:30 NewDownDevices:0
21-Aug-2018 02:33:35 - SYSTEM STATS: Time:33.4113 Method:spine Processes:1 Threads:50 Hosts:405 HostsPerProcess:405 DataSources:32576 RRDsProcessed:15620
21-Aug-2018 02:32:36 - SYSTEM STATS: Time:34.8320 Method:spine Processes:1 Threads:50 Hosts:405 HostsPerProcess:405 DataSources:32576 RRDsProcessed:16996
2018-08-21 02:32:12 - SPINE: Poller[Main Poller] ERROR: Spine Timed Out While Waiting for Threads to End
21-Aug-2018 02:32:09 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php: 632 CactiErrorHandler)(/lib/functions.php: 4585 cacti_debug_backtrace)
21-Aug-2018 02:32:03 - POLLER: Poller[Main Poller] WARNING: There are '1' detected as overrunning a polling process, please investigate
21-Aug-2018 02:32:00 - SYSTEM STATS: Time:51.6132 Method:spine Processes:1 Threads:50 Hosts:405 HostsPerProcess:405 DataSources:32568 RRDsProcessed:13267
21-Aug-2018 02:32:00 - POLLER: Poller[Main Poller] Maximum runtime of 58 seconds exceeded. Exiting.
21-Aug-2018 02:30:19 - SYSTEM STATS: Time:18.4291 Method:spine Processes:1 Threads:50 Hosts:405 HostsPerProcess:405 DataSources:32557 RRDsProcessed:15607
21-Aug-2018 02:29:30 - SYSTEM STATS: Time:28.6559 Method:spine Processes:1 Threads:50 Hosts:405 HostsPerProcess:405 DataSources:32556 RRDsProcessed:15615
21-Aug-2018 02:28:25 - SYSTEM THOLD STATS: Time:0.0907 Tholds:29 TotalDevices:405 DownDevices:30 NewDownDevices:0
21-Aug-2018 02:28:14 - SYSTEM STATS: Time:13.3061 Method:spine Processes:1 Threads:50 Hosts:405 HostsPerProcess:405 DataSources:32569 RRDsProcessed:15616
21-Aug-2018 02:27:29 - SYSTEM THOLD STATS: Time:0.1641 Tholds:27 TotalDevices:405 DownDevices:30 NewDownDevices:0
21-Aug-2018 02:27:16 - SYSTEM STATS: Time:14.2381 Method:spine Processes:1 Threads:50 Hosts:405 HostsPerProcess:405 DataSources:32569 RRDsProcessed:15536
21-Aug-2018 02:26:30 - SYSTEM THOLD STATS: Time:0.2258 Tholds:27 TotalDevices:405 DownDevices:30 NewDownDevices:0
21-Aug-2018 02:26:15 - SYSTEM STATS: Time:13.7334 Method:spine Processes:1 Threads:50 Hosts:405 HostsPerProcess:405 DataSources:32568 RRDsProcessed:15604_
![image](https://user-images.githubusercontent.com/17400240/44381210-f0591180-a517-11e8-8a7c-d51ecde9f877.png)

**Comment by netniV** [comment]
Something is clearly holding up your process.  This may not necessarily be down to your CPU, it could be network or device related.  Since you are using spine, I would increase the number of processes that spine uses to match your cores and see how that fairs.  It will stop one process which is locking up from affecting the others.

**Comment by Izmenoff** [comment]
Thanks, I'll try

**Comment by netniV** [comment]
You may need to lower the number of threads though because 50 * 8 for example would be 400 threads trying to hit the MySQL db.

**Comment by Izmenoff** [comment]
When I decreased the number of threads I lost more information from 02:30 to 02:40 am

**Comment by cigamit** [comment]
Use boost and you may not get the gaps.  Do you have a backup running at this time?  If running a backup, you should exclude the memory tables and set `--lock-tables=false`.

**Comment by cigamit** [comment]
Those setting would drive an overload about once an hour.  Is that how often the overload is happening?

**Comment by cigamit** [comment]
Click the "Enable direct population..." checkbox and then goto System Utilities > View Boost stats to see if your memory tables can be large enough to hold an hours worth of data.

**Comment by cigamit** [comment]
Once you enable and tune boost, this issue will be gone.  Did not see that you did not have boost enabled.
