### ISSUE TITLE
[1.2.0] Color dropdown does not select properly

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1857]
When you attempt to click into a color dropdown, it only sometimes works.  Sometimes, it appears to fill the background color in like you have clicked, others it drops down and further still, can sometimes do nothing.

**Comment by cigamit** [comment]
Named Colors are disabled.  Maybe we need to make it more obvious.

**Comment by netniV** [comment]
There seems to be an issue with Chrome and the drop down.  Long delays in displaying which may be related to the disabled problem.

**Comment by cigamit** [comment]
Resolved.
