### ISSUE TITLE
Support udp6: prefix for hosts polled by PHP SNMP module

### ISSUE THREAD

**Issue by mhoran** [Cacti/cacti#1865]
Breaking out from #1416.

It is not possible to specify that Cacti should prefer IPv6 over IPv4 when connecting to hosts. This may be desirable if a host has an SNMP daemon listening on IPv6 but not IPv4. The Net-SNMP package instructs users to prefix hosts with `udp6:` if it is desired to prefer IPv6.

Today, specifying `udp6:` in the hostname field today results in the following error on the host page:
```
 System SNMP error - SNMP::get(): Could not open snmp connection: Unknown host (udp6) (Invalid argument) 
```

The following error show up in my Cacti log:
```
2018/08/22 15:35:02 - CMDPHP Device[10] Device[brooklyn] ERROR: HOST EVENT: Device is DOWN Message: Device did not respond to SNMP
```

Trying to view any graph in real-time also fails, and all my graphs fail to update any longer.

I'm using the following data templates:
* Host MIB - CPU Utilization
* Unix - Ping Host
* Interface - Traffic
* Host MIB - Hard Drive Space

I've worked around this for the time being by removing the paths to all Net-SNMP tools from my Cacti configuration. This forces Cacti to use the PHP SNMP libraries, which prefer IPv6. However, this doesn't seem like the right thing to do long term, as this implicit configuration seems error prone.

**Comment by netniV** [comment]
Please give an example of how you are specifying the IPv6 host name.

**Comment by netniV** [comment]
Also, the Net-SNMP binaries are actually prefered over the PHP ones currently as the PHP ones don't handle results properly like Net-SNMP does.

**Comment by mhoran** [comment]
> Please give an example of how you are specifying the IPv6 host name.
`udp6:brooklyn.example.com`

**Comment by netniV** [comment]
Try the usage as udp6:[brooklyn.example.com], not sure if that will work or not as it's usually the IP in between the square brackets.

**Comment by mhoran** [comment]
> Try the usage as udp6:[brooklyn.example.com], not sure if that will work or not as it's usually the IP in between the square brackets.

Yeah, that doesn't work, since the brackets indicate an IP address. Note that on the command line, the Net-SNMP commands work just fine with `udp6:brooklyn.example.com`. FWIW, putting the IP address in the brackets doesn't work either.

> Also, the Net-SNMP binaries are actually prefered over the PHP ones currently as the PHP ones don't handle results properly like Net-SNMP does.

Understood. However, it seems many scripts (or, at least the ones I use) leverage only the PHP libraries. I have another host that never exhibited the behavior reported in the original issue, because all those scripts also use only the PHP libraries.

Any scripts that do call out to Net-SNMP should work here, since Net-SNMP does handle the `udp6:` prefix correctly. The PHP scripts then need to look at the `udp6:` prefix and signal the PHP libraries to prefer IPv6 (they do by default -- but then I'd expect the `udp4` prefix should work as well, so something needs to be done there.)

I put all the paths to the Net-SNMP utilities back in place and left the host as `udp6:brooklyn.example.com`. I'm seeing the same errors reported in my initial comment.

Happy to provide access to the environment if that would help.

**Comment by mhoran** [comment]
I changed downed host detection to ping to try and force the poller to run with all the Net-SNMP binaries back in place and the `udp6:` prefix. Here's what I see in my Cacti log now:

```
2018/08/22 17:20:06 - SYSTEM THOLD STATS: Time:0.8008 Tholds:0 TotalDevices:5 DownDevices:0 NewDownDevices:0
--
2018/08/22 17:20:05 - SYSTEM STATS: Time:5.4002 Method:cmd.php  Processes:1 Threads:N/A Hosts:5 HostsPerProcess:5 DataSources:74  RRDsProcessed:52
2018/08/22 17:20:04 - POLLER: Poller[Main Poller] WARNING: Invalid Response(s), Errors[2] Device[10] Device[brooklyn] Thread[1] Graphs[brooklyn - Traffic - Internet, brooklyn - Traffic - Internet] Graphs[brooklyn - Traffic - LAN, brooklyn - Traffic - LAN] DS[brooklyn - Traffic - Internet, brooklyn - Traffic - LAN]
2018/08/22 17:20:02 - CMDPHP WARNING: SNMP Error:'', Device:'udp6:brooklyn.example.com', OID:'.1.3.6.1.2.1.25.2.3.1.5.35'
2018/08/22 17:20:02 - CMDPHP WARNING: SNMP Error:'', Device:'udp6:brooklyn.example.com', OID:'.1.3.6.1.2.1.25.2.3.1.6.35'
2018/08/22 17:20:02 - CMDPHP WARNING: SNMP Error:'', Device:'udp6:brooklyn.example.com', OID:'.1.3.6.1.2.1.25.2.3.1.5.34'
2018/08/22 17:20:02 - CMDPHP WARNING: SNMP Error:'', Device:'udp6:brooklyn.example.com', OID:'.1.3.6.1.2.1.25.2.3.1.6.34'
2018/08/22 17:20:02 - CMDPHP WARNING: SNMP Error:'', Device:'udp6:brooklyn.example.com', OID:'.1.3.6.1.2.1.25.2.3.1.5.33'
2018/08/22 17:20:02 - CMDPHP WARNING: SNMP Error:'', Device:'udp6:brooklyn.example.com', OID:'.1.3.6.1.2.1.25.2.3.1.6.33'
2018/08/22 17:20:02 - CMDPHP WARNING: SNMP Error:'', Device:'udp6:brooklyn.example.com', OID:'.1.3.6.1.2.1.25.2.3.1.5.32'
2018/08/22 17:20:02 - CMDPHP WARNING: SNMP Error:'', Device:'udp6:brooklyn.example.com', OID:'.1.3.6.1.2.1.25.2.3.1.6.32'
2018/08/22 17:20:02 - CMDPHP WARNING: SNMP Error:'', Device:'udp6:brooklyn.example.com', OID:'.1.3.6.1.2.1.25.2.3.1.5.31'
2018/08/22 17:20:02 - CMDPHP WARNING: SNMP Error:'', Device:'udp6:brooklyn.example.com', OID:'.1.3.6.1.2.1.25.2.3.1.6.31'
2018/08/22 17:20:02 - CMDPHP WARNING: SNMP Error:'', Device:'udp6:brooklyn.example.com', OID:'.1.3.6.1.2.1.25.2.3.1.5.2'
2018/08/22 17:20:02 - CMDPHP WARNING: SNMP Error:'', Device:'udp6:brooklyn.example.com', OID:'.1.3.6.1.2.1.25.2.3.1.6.2'
2018/08/22 17:20:02 - CMDPHP WARNING: SNMP Error:'', Device:'udp6:brooklyn.example.com', OID:'.1.3.6.1.2.1.25.2.3.1.5.1'
2018/08/22 17:20:02 - CMDPHP WARNING: SNMP Error:'', Device:'udp6:brooklyn.example.com', OID:'.1.3.6.1.2.1.25.2.3.1.6.1'
2018/08/22 17:20:02 - CMDPHP WARNING: SNMP Error:'', Device:'udp6:brooklyn.example.com', OID:'.1.3.6.1.2.1.25.2.3.1.6.10'
2018/08/22 17:20:02 - CMDPHP WARNING: SNMP Error:'', Device:'udp6:brooklyn.example.com', OID:'.1.3.6.1.2.1.25.2.3.1.5.10'
2018/08/22 17:20:02 - CMDPHP PHP ERROR WARNING Backtrace: (/cmd.php:  503 open_snmp_session)(/cmd.php: 98 cacti_snmp_session)(/lib/snmp.php:  67 __construct)(CactiErrorHandler)(/lib/functions.php: 4585  cacti_debug_backtrace)
2018/08/22 17:20:02 - ERROR PHP WARNING: SNMP::__construct():  php_network_getaddresses: getaddrinfo failed: hostname nor servname  provided, or not known in file: /usr/local/share/cacti/lib/snmp.php  on  line: 67
```

The only graph that seems to be updating at this point is my CPU graph. All others have stopped updating.

**Comment by cigamit** [comment]
Remove php-snmp, and this issue will be resolved.  php-snmp needs a major update to support IPv6.  Please test under spine.  It works with IPv6 IP Addresses, but I'm uncertain of hostname.  Should work as well.  This php-snmp issue is a known one.

**Comment by mhoran** [comment]
php-snmp is not an issue for me. It works fine -- better than Net-SNMP for my case because it prefers IPv6 out of the box.

I'm happy to remove php-snmp to test, but I'm confused about what we're trying to achieve here. The conversation in https://github.com/Cacti/cacti/issues/1416#issuecomment-414183759 led me to open this issue. Was that not the right thing to do?

I am also happy to test with spine, but that seems like an unnecessary complication for my installation. I just have a few personal systems that I'm monitoring, and a persistent daemon running on a resource strapped host seems a bit overkill.

Anyway, just trying to figure out how to move forward here. I thought this was the best course of action, based on our previous discussion. The current behavior is a bit confusing, though I'll accept that it's also unique.

**Comment by mhoran** [comment]
I disabled the PHP SNMP module and the `udp6:` prefix works as expected. With the SNMP module enabled this results in mixed success, because many of the pollers have mixed preference of the PHP SNMP module vs. Net-SNMP commands.

**Comment by mhoran** [comment]
Interesting, polling time seems to have almost doubled since disabling the PHP SNMP module.

**Comment by mhoran** [comment]
Okay, I started looking into how this might be implemented. The PHP SNMP functions don't have any way to signal whether IPv6 should be preferred, so far as I can tell. There is a way to signal to `SNMP::__construct` that IPv6 should be preferred by surrounding either a hostname or IP address in brackets, but that is non-standard and somewhat confusing.

I think the only way to do this would be to use the `cacti_gethostbyname` function and signal a `$type` of `DNS_AAAA` for all hosts with `udp6` or `tcp6` prefixed. Then, instead of passing the hostname directly to the PHP SNMP functions, the resolved IP address would be passed as the hostname. This would force the PHP SNMP functions to use IPv6 (or IPv4) as desired.

Note that there seems to be no way to signal to the PHP SNMP functions that TCP should be preferred over UDP. I guess that's just a missing feature of those functions. I see now why y'all are recommending against using them.

It seems that there's no easy way to fix this issue, and each approach comes with downsides. It would seem that the *right* approach would be to fix the PHP SNMP functions -- but that's not something I'm prepared to do myself.

**Comment by cigamit** [comment]
Not using php-snmp generates a bit of overhead that we don't like, but unfortunately, until someone fixes the php-snmp module for this, and a few additional other issues, we are stuck with it.  @netniV and I have been discussing this.  So, there is some hope.
