### ISSUE TITLE
Cacti Login doesn't work........

### ISSUE THREAD

**Issue by ferialjober** [Cacti/cacti#1866]
I am new at Cacti and I was trying to make things work (graphs would not display) so I went into settings/authentication and I changed 2 things: 
- guest user= admin 
- template user= admin 

After that i came back to the User Login, but my Username & Password weren't Right anymore

**Comment by netniV** [comment]
To fix, run the following SQL statements:

```sql
DELETE FROM settings WHERE name in ('user_template', 'guest_user')
UPDATE user_auth SET enabled = 'on', password=md5('admin') WHERE username = 'admin'
```

That should hopefully get you back in

**Comment by ferialjober** [comment]
Thx I am loged in now. Now i want to send a test email

**Comment by netniV** [comment]
You can do that within the settings.  As the original issue has now been resolved, I'm going to close this.
