### ISSUE TITLE
Test Email Results --> You must provide at least one recipient email address. 

### ISSUE THREAD

**Issue by ferialjober** [Cacti/cacti#1867]
I should add a other email, but where??….

**Comment by netniV** [comment]
Console -> Configuration -> Settings -> Mail -> Test Email

**Comment by ferialjober** [comment]
Ok Test Email = recipient Email
from Email = Sender email? is that Right

**Comment by ferialjober** [comment]
Now i have a SMTP connect() failed.

**Comment by cigamit** [comment]
Can we please take this to the forums?  This is a fairly common error for beginners.  Answered a number of times on the forums.  Use google to search the forums.  In your search add the following "site:forums.cacti.net"

**Comment by ferialjober** [comment]
Now everything works ;-)
I only changed one setting
