### ISSUE TITLE
[1.2.0] Installer error if Json module not available

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1870]
```
Fatal error: Interface 'JsonSerializable' not found in /usr/share/cacti/site/lib/installer.php on line 24
```
FreeBSD does not provide many packages by default when installing apache24.

**Comment by netniV** [comment]
Other errors:
```
PHP Fatal error:  Call to undefined function simplexml_load_string() in /usr/share/cacti/site/install/functions.php on line 315
```

```
PHP Warning:  file_get_contents(): Unable to find the wrapper &quot;compress.zlib&quot; - did you forget to enable it when you configured PHP? in /usr/share/cacti/site/install/functions.php on line 313
```

On FreeBSD, these were corrected by performing:
```console
pkg install -y \
php56-mysql php56-mysqli php56-xml php56-ldap php56-gmp php56-mbstring \
php56-pdo php56-pdo_mysql php56-gd php56-snmp php56-session php56-zlib \
php56-simplexml rrdtool
```

**Comment by pautiina** [comment]
Stop, try install php71 or php72

**Comment by netniV** [comment]
I'm trying different versions on purpose 👍

**Comment by pautiina** [comment]
I think I need to change the title of this issue. These are not mistakes, it's just that you begin to enter our ranks and not everyone has fully understood :)

**Comment by netniV** [comment]
Well, no, I'd like the Installer to handle the error.  Currently, it just lands with a partial installer page.  I agree that it is an admin error by not installing all the required packages, but we can handle some of them so should at least display a warning to that effect.

**Comment by netniV** [comment]
Probably won't get all of them covered but at the same time, we should probably have a fatal handler which still returns a result which is handled.

**Comment by pautiina** [comment]
When we install the Cacti from the port tree or the packages database, it automatically pulls all the necessary dependencies. I think it's better to call it an improvement, which will check the dependencies when installing Cacti already through the web interface.

**Comment by netniV** [comment]
It will be an improvement, but it's still an error that prevents the page even running if it's not there.  People who use sources would have to make sure they had all the modules.  Better to display a message saying to check for the pre-requisites than a blank page.

**Comment by pautiina** [comment]
If you look at the Makefile from the ports, then the whole dependency relationship for Cacti, which we can partially verify via extension_loaded.
Part of file `/usr/ports/net-mgmt/cacti/Makefile`:
```
# $FreeBSD: head/net-mgmt/cacti/Makefile 467020 2018-04-11 00:32:33Z dbaio $

PORTNAME=       cacti
PORTVERSION=    1.1.37
CATEGORIES=     net-mgmt www
MASTER_SITES=   http://www.cacti.net/downloads/ \
                ftp://ftpmirror.uk/freebsd-ports/cacti/

MAINTAINER=     freebsd-ports@dan.me.uk
COMMENT=        Web-driven graphing interface for RRDTool

LICENSE=        GPLv2+
LICENSE_FILE=   ${WRKSRC}/LICENSE

RUN_DEPENDS=    rrdtool:databases/rrdtool

USES=           cpe mysql php:web shebangfix
USE_PHP=        ctype filter gd gettext gmp hash json ldap mbstring openssl pcre pdo pdo_mysql posix session simplexml sockets snmp xml zlib

```

**Comment by netniV** [comment]
Yeah, it's good that it's covered via `portsnap` or `pkg` but all too often there are instructions on how to install the latest version of Cacti which often rely solely on manually selecting the packages, then downloading a source of cacti rather than a packaged version.  

So I like your suggestion about the extension loaded part, though I think I'll restrict it to the list at least allows the installer to start.  One thing I did notice was that even though the required modules were not enabled you could still continue the install.

**Comment by netniV** [comment]
```
Notice: Use of undefined constant FILTER_VALIDATE_INT - assumed 'FILTER_VALIDATE_INT' in /usr/share/cacti/site/lib/html_utility.php on line 358
```
Another error due to missing modules

**Comment by cigamit** [comment]
I'm wondering if we have a chance to fix all these before release.

**Comment by cigamit** [comment]
I've updated the dependencies.  Can you see if the installer is now working?

**Comment by cigamit** [comment]
Closing as all of these are now captured in the defaults.

**Comment by netniV** [comment]
Actually, I'm going to re-open it because some of these dependencies missing will cause the installer to not work at all.  We need to add a check to the master page, so that we don't end up with errors because JSON or another installer-required dependency is missing.

**Comment by netniV** [comment]
The following updates are coming as part of this:
* Added new message if PHP MySQL module not enabled.
  * Web based;
     ![image](https://user-images.githubusercontent.com/9052188/45363741-3281ea00-b5d0-11e8-8d20-89faa570cbfc.png)

   * Cli based:
     ![image](https://user-images.githubusercontent.com/9052188/45363767-4594ba00-b5d0-11e8-90de-5cfeeca815d2.png)

* Added new message on Installer window if Json not detected

* Fixed up error handling of required PHP modules.
