### ISSUE TITLE
[1.2.0] Graph Debug Mode should flow on Console->Management->Graphs

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1872]
![image](https://user-images.githubusercontent.com/9052188/44569478-6953a580-a772-11e8-8b12-5544c1bd1d7a.png)

The graph debug mode is turned on but when you scroll down the page, nothing appears.  If you look to the right, you can see that the text is very partially there instead (and you can see it if you scroll to the right).  The div containing the debug information should flow for smaller screens.

**Comment by netniV** [comment]
Weirdly, after resolving issue #1873, my debug started to appear below the graph.

**Comment by cigamit** [comment]
Used the approach here **https://github.com/Cacti/cacti/issues/1840** I like this better anyway.
