### ISSUE TITLE
Aggregate Graph printing extra legend item

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1873]
The Host MIB - CPU Utilization template defines its Graph Items as such:
![image1](https://user-images.githubusercontent.com/9052188/44570449-d157bb00-a775-11e8-8448-381420d382a2.png)

Given this template, it generates the following graph:
![image2](https://user-images.githubusercontent.com/9052188/44570480-ecc2c600-a775-11e8-9971-a9d1d45289b4.png)

You then create the Aggregate Template based off this Graph Template and the items look as such:
![image3](https://user-images.githubusercontent.com/9052188/44570569-2d224400-a776-11e8-8efa-8bed5afe58fe.png)

Which in turn is used to create an Aggregate graph which has it's items as such:
![image4](https://user-images.githubusercontent.com/9052188/44570592-45925e80-a776-11e8-8afe-35be345acaec.png)

But leads to a graph with an extra legend item appearing as such:
![image5](https://user-images.githubusercontent.com/9052188/44570601-504cf380-a776-11e8-9e0d-5ac8c78f0eef.png)

Resyncing the graph template nor reording the items didn't seem to change anything (as soon above).  The graph debug showed that an extra STACK item was being generated:

```diff
diff --git a/tmp/2 b/tmp/1
index d774c10..7f011a0 100644
--- a/tmp/2
+++ b/tmp/1
@@ -1,10 +1,9 @@
-       RRDtool Command:
 /usr/bin/rrdtool graph - \
 --imgformat=PNG \
 --start='-180000' \
 --end='-60' \
 --pango-markup  \
---title='Server-Name - CPU Utilization - CPU0' \
+--title='Server-Name - CPU Utilization' \
 --vertical-label='percent' \
 --slope-mode \
 --base=1000 \
@@ -31,12 +30,39 @@
 --font WATERMARK:6:'Arial' \
 --slope-mode \
 --watermark 'Company Name <AE>' \
-DEF:a='/usr/share/cacti/site/rra/58/1388.rrd':'cpu':MAX \
-DEF:b='/usr/share/cacti/site/rra/58/1388.rrd':'cpu':AVERAGE \
-LINE1:a#FF0000FF:  \
-AREA:b#FF00007F:'CPU Utilization'  \
-GPRINT:b:LAST:'Current\:%8.0lf'  \
-GPRINT:b:AVERAGE:'Average\:%8.0lf'  \
-GPRINT:b:MAX:'Maximum\:%8.0lf\n'
-RRDtool Says:
-OK
+DEF:a='/usr/share/cacti/site/rra/58/1388.rrd':'cpu':AVERAGE \
+DEF:b='/usr/share/cacti/site/rra/58/1388.rrd':'cpu':MAX \
+DEF:c='/usr/share/cacti/site/rra/58/1389.rrd':'cpu':AVERAGE \
+DEF:d='/usr/share/cacti/site/rra/58/1389.rrd':'cpu':MAX \
+DEF:e='/usr/share/cacti/site/rra/58/1390.rrd':'cpu':AVERAGE \
+DEF:f='/usr/share/cacti/site/rra/58/1390.rrd':'cpu':MAX \
+DEF:g='/usr/share/cacti/site/rra/58/1391.rrd':'cpu':AVERAGE \
+DEF:h='/usr/share/cacti/site/rra/58/1391.rrd':'cpu':MAX \
+DEF:i='/usr/share/cacti/site/rra/58/1999.rrd':'cpu':AVERAGE \
+DEF:j='/usr/share/cacti/site/rra/58/1999.rrd':'cpu':MAX \
+AREA:a#FF00007F:'Server-Name CPU Utilization'  \
+GPRINT:a:LAST:'Current\:%8.0lf'  \
+GPRINT:a:AVERAGE:'Average\:%8.0lf'  \
+GPRINT:a:MAX:'Maximum\:%8.0lf\n'  \
+AREA:b#FF0000FF:'\n':STACK \
+AREA:c#FF00007F:'Server-Name CPU Utilization':STACK \
+GPRINT:c:LAST:'Current\:%8.0lf'  \
+GPRINT:c:AVERAGE:'Average\:%8.0lf'  \
+GPRINT:c:MAX:'Maximum\:%8.0lf\n'  \
+AREA:d#FF0000FF:'\n':STACK \
+AREA:e#FF00007F:'Server-Name CPU Utilization':STACK \
+GPRINT:e:LAST:'Current\:%8.0lf'  \
+GPRINT:e:AVERAGE:'Average\:%8.0lf'  \
+GPRINT:e:MAX:'Maximum\:%8.0lf\n'  \
+AREA:f#FF0000FF:'\n':STACK \
+AREA:g#FF00007F:'Server-Name CPU Utilization':STACK \
+GPRINT:g:LAST:'Current\:%8.0lf'  \
+GPRINT:g:AVERAGE:'Average\:%8.0lf'  \
+GPRINT:g:MAX:'Maximum\:%8.0lf\n'  \
+AREA:h#FF0000FF:'\n':STACK \
+AREA:i#FF00007F:'Server-Name CPU Utilization':STACK \
+GPRINT:i:LAST:'Current\:%8.0lf'  \
+GPRINT:i:AVERAGE:'Average\:%8.0lf'  \
+GPRINT:i:MAX:'Maximum\:%8.0lf\n'  \
+AREA:j#FF0000FF:'\n':STACK
+
```

However, when I edited the legend because I wanted the cpu number (missing on the above preview), I changed the Graph Item 2 on the Graph Template as such:

```diff
- CPU Utilization - CPU
+ CPU Utilization - CPU|query_hrProcessorFrwID|
```

This then results in a correct looking graph of:
![image6](https://user-images.githubusercontent.com/9052188/44570774-d10bef80-a776-11e8-876a-7420ce843a91.png)

**Comment by cigamit** [comment]
you need to skip the MAX CF, also, you need to include |query_something| for the graph prefix within the Aggregate Template.  This is really not a bug.

**Comment by netniV** [comment]
Yeah I had to modify the default Host MIB template to make it work.  Which makes me wonder if that template should actually use this by default for its templates, CPU/Disk/Interface?

**Comment by cigamit** [comment]
Make sure you skip what does not make sense to aggregate.

**Comment by netniV** [comment]
I'm not sure why you closed this as it's making perfect sense to me.  The repeated graph items are not clear in an aggregate graph using the default templates.  There needs to be a way to either add the index number or something to more clearly identify the aggregated items.  It also had an issue with extra legend items appearing which was clearly a bug.
