### ISSUE TITLE
[1.2.0] right-click at graph not work

### ISSUE THREAD

**Issue by skyjou** [Cacti/cacti#1874]
Right-click on graph not work. Functions in the popup menu cannot select.

**Comment by netniV** [comment]
What browser are you using? Can you check your browser console for any javascript errors and post them here.

**Comment by netniV** [comment]
Also, this may be related to #1863

**Comment by skyjou** [comment]
Both Chrome and Firefox are not work.
Here is console log for Firefox:

TypeError: $(...).children(...).size is not a function
	zoomContextMenu_init/< http://172.31.250.122/cacti/include/js/jquery.zoom.js:924:11
	handle http://172.31.250.122/cacti/include/js/jquery.js:5536:11
	dispatch http://172.31.250.122/cacti/include/js/jquery.js:5182:16
	add/elemData.handle http://172.31.250.122/cacti/include/js/jquery.js:4991:6

**Comment by cigamit** [comment]
On what page?

**Comment by cigamit** [comment]
Never mind.  Fixed.
