### ISSUE TITLE
Data Input Method not parsing all results from multiple output

### ISSUE THREAD

**Issue by sst17** [Cacti/cacti#1876]
Running 1.1.28 and cmd poller.

Only some results from bash script are parsed when running script through Data Input Method.

Parsing of mapped fields "upsInfoLoadValue, upsInfoRealPowerValue, upsInfoRealPowerNominal, upsBatteryChargeValue, upsBatteryVoltageValue, upsBatteryRuntimeValue" parsed successfully. The mapped field "upsOutputVoltageValue" did not parse (nothing in logs). The output of a bash script is as follows:  

upsInfoLoadValue:16.00 upsInfoDelayStart:30.00 upsInfoDelayShutdown:20.00 upsInfoTimerStart:0.00 upsInfoTimerShutdown:0.00 upsInfoTestInterval:2592000.00 upsInfoEffciency:87.00 upsInfoPowerValue:139.00 upsInfoPowerNominal:850.00 upsInfoRealPowerValue:84.00 upsInfoRealPowerNominal:600.00 upsBatteryChargeValue:100.00 upsBatteryChargeLow:20.00 upsBatteryChargeRestart:0.00 upsBatteryVoltageValue:27.20 upsBatteryVoltageNominal:24.00 upsBatteryCapacity:7.20 upsBatteryRuntimeValue:2981.00 upsInputVoltageNominal:230.00 upsInputFrequencyNominal:50.00 upsOutputVoltageValue:232.00 upsOutputVoltageNominal:230.00 upsOutputFrequencyValue:49.90 upsOutputFrequencyNominal:50.00 upsOutputCurrentValue:0.60 upsDriverPollInterval:5.00 upsDriverPollFrequency:30.00

However if the output is limited to just a few pairs then the field "upsOutputVoltageValue" is parsed successfully. Shortened output:

upsInfoLoadValue:16.00 upsInfoRealPowerValue:84.00 upsInfoRealPowerNominal:600.00 upsBatteryChargeValue:100.00 upsBatteryVoltageValue:27.20 upsBatteryRuntimeValue:2774.00 upsOutputVoltageValue:233.89

It looks like cacti is unable to parse the full result and is dropping the last few pairs for larger outputs.

**Comment by cigamit** [comment]
You need to increase the width of the output column in the two tables: poller_output and poller_output_boost.  It's likely a varchar that is too narrow.  We don't recommend having very long output as it negatively impacts enterprise performance.

**Comment by sst17** [comment]
That did indeed solve the problem. It looks like the column is set to a
length of 512 by default. Doubling it to 1024 solved the problem without
any apparent problems.

**Comment by cigamit** [comment]
Good.  Closing this then.
