### ISSUE TITLE
Reports.php stops polling.

### ISSUE THREAD

**Issue by smiles1969** [Cacti/cacti#1877]
Updated to latest commit and I'm getting the following error in the poller log (using spine):

PHP Fatal error:  Cannot redeclare duplicate_reports() (previously declared in /var/www/html/cacti/lib/reports.php:29) in /var/www/html/cacti/lib/reports.php on line 70

Polling was not happening due to this error.

I had to roll back to commit 2b61c1bba3eb5146d1bacbef93b84c59eb43c3ef to restore the polling process again.

**Comment by cigamit** [comment]
Can you track down which file it's happening in?  Not the library, but the actual file being called?  Is it the poller process.

**Comment by smiles1969** [comment]
I rolled lib/reports.php back to commit 2b61c1b and the poller error stopped and it's been polling fine.

This was a result of the cron job that gets called every 1 minute with the following:

*/1 * * * * cactiuser php /var/www/html/cacti/poller.php >> /var/log/cacti_poller.log 2>&1

and the PHP fatal error is showing repeatedly every minute in /var/log/cacti_poller.log, and no graphs are being updated.

**Comment by cigamit** [comment]
What OS is this?  What plugins do you have installed?

**Comment by cigamit** [comment]
Should be resolved with the latest commit now.  Assuming that a plugin was including.

**Comment by smiles1969** [comment]
root@ctcv-cacti3:/var/www/html/cacti# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"

![image](https://user-images.githubusercontent.com/17500126/44796816-69d5ad00-ab73-11e8-8315-0a1327d8ea55.png)

**Comment by smiles1969** [comment]
Confirmed poller still working after upgrading to latest commit. Nice work, thanks.

**Comment by smiles1969** [comment]
root@ctcv-cacti3:/var/www/html/cacti/plugins/monitor# grep reports.php * | grep include
grep: images: Is a directory
grep: locales: Is a directory
grep: sounds: Is a directory
grep: themes: Is a directory
poller_monitor.php:include_once($config['base_path'] . '/lib/reports.php');
setup.php:      include_once($config['base_path'] . '/lib/reports.php');

**Comment by cigamit** [comment]
Yea, that's a bug ;)

**Comment by cigamit** [comment]
Okay, that is interesting.  I did some commit this morning only to find that there is a function being called in from lib/reports.php.  So, it guess it has to stay for now.  But since this issue is resolved in develop, I'll close this one.
