### ISSUE TITLE
I need a Map Plugin for Cacti 1.1.38, but none of them i found works

### ISSUE THREAD

**Issue by ferialjober** [Cacti/cacti#1878]
I need a Map Plugin for Cacti 1.1.38, but none of them i found works

**Comment by cigamit** [comment]
Try this one.  It's not finished.
[gpsmap.tar.gz](https://github.com/Cacti/cacti/files/2327721/gpsmap.tar.gz)

**Comment by ferialjober** [comment]
THX

**Comment by Izmenoff** [comment]
I have installed the gsmmap, but

29-Aug-2018 09:34:18 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php: 723 api_plugin_hook)(/lib/plugins.php: 73 api_plugin_run_plugin_hook)(/lib/plugins.php: 170 gpsmap_poller_bottom)(/plugins/gpsmap/includes/polling.php: 89 callRegion)(/plugins/gpsmap/includes/polling/functions.php: 27 region)(/plugins/gpsmap/includes/polling/processregion.php: 199 fclose)(CactiErrorHandler)(/lib/functions.php: 4585 cacti_debug_backtrace)
--
29-Aug-2018 09:34:18 - ERROR PHP WARNING in Plugin 'gpsmap': fclose() expects parameter 1 to be resource, boolean given in file: /var/www/html/cacti/plugins/gpsmap/includes/polling/processregion.php on line: 199
29-Aug-2018 09:34:18 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php: 723 api_plugin_hook)(/lib/plugins.php: 73 api_plugin_run_plugin_hook)(/lib/plugins.php: 170 gpsmap_poller_bottom)(/plugins/gpsmap/includes/polling.php: 89 callRegion)(/plugins/gpsmap/includes/polling/functions.php: 27 region)(/plugins/gpsmap/includes/polling/processregion.php: 198 fwrite)(CactiErrorHandler)(/lib/functions.php: 4585 cacti_debug_backtrace)
29-Aug-2018 09:34:18 - ERROR PHP WARNING in Plugin 'gpsmap': fwrite() expects parameter 1 to be resource, boolean given in file: /var/www/html/cacti/plugins/gpsmap/includes/polling/processregion.php on line: 198
29-Aug-2018 09:34:18 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php: 723 api_plugin_hook)(/lib/plugins.php: 73 api_plugin_run_plugin_hook)(/lib/plugins.php: 170 gpsmap_poller_bottom)(/plugins/gpsmap/includes/polling.php: 89 callRegion)(/plugins/gpsmap/includes/polling/functions.php: 27 region)(/plugins/gpsmap/includes/polling/processregion.php: 197 fopen)(CactiErrorHandler)(/lib/functions.php: 4585 cacti_debug_backtrace)
29-Aug-2018 09:34:18 - ERROR PHP WARNING in Plugin 'gpsmap': fopen(/var/www/html/cacti/plugins/gpsmap/XML/172.172.172.-top.html): failed to open stream: Permission denied in file: /var/www/html/cacti/plugins/gpsmap/includes/polling/processregion.php on line: 197

**Comment by ferialjober** [comment]
SAME HERE :(

**Comment by anarkia1976** [comment]
I don't have find a valid plugin, all of them are out of date. :)

**Comment by Izmenoff** [comment]
It seems like a new PHP version doesn't work with old code of The gpsmap plugin

**Comment by ferialjober** [comment]
I now…. The Weathermap Plugin are out of date & the GPSMAP Plugin also

**Comment by ferialjober** [comment]
know*

**Comment by ferialjober** [comment]
That's very nice!

**Comment by cigamit** [comment]
I have more updates for the gpsmap this morning.  There are still some issues to resolve though.  You will have to re-install the plugin once you download it though.

**Comment by Izmenoff** [comment]
Thanks! It works, but spam in log file

30-Aug-2018 15:36:18 - CMDPHP PHP ERROR Backtrace: (/poller.php: 723 api_plugin_hook)(/lib/plugins.php: 73 api_plugin_run_plugin_hook)(/lib/plugins.php: 170 gpsmap_poller_bottom)(/plugins/gpsmap/includes/polling.php: 78 callRegion)(/plugins/gpsmap/includes/polling/functions.php: 27 region)(/plugins/gpsmap/includes/polling/processregion.php: 32 include_once)(/plugins/gpsmap/includes/polling/processregion.php: 32 CactiErrorHandler)(/lib/functions.php: 4598 cacti_debug_backtrace)
30-Aug-2018 15:36:18 - ERROR PHP DEPRECATED in Plugin 'gpsmap': Methods with the same name as their class will not be constructors in a future version of PHP; host has a deprecated constructor in file: /var/www/html/cacti/plugins/gpsmap/class/hosts_class.php on line: 22

**Comment by cigamit** [comment]
Okay, good catch.  Let me fix that, but please open new bugs under the plugin itself.

**Comment by cigamit** [comment]
Resolved now.  New bugs in plugin_gpsmap

**Comment by Izmenoff** [comment]
Thanks for fast debug!!!
