### ISSUE TITLE
Problems with CACTI FLOWVIEW

### ISSUE THREAD

**Issue by ferialjober** [Cacti/cacti#1879]
I installed the Flowview Plugin, but I got this email: "Can not find the 'flow-cat' binary at '/bin', please check your Flowtools Path Setting!"..
I don't know, where i find the "Flow-Tools", because i should install this…

I really Need help guys.

**Comment by cigamit** [comment]
Please take these issues up on the forums.  You have to install flowtools.  If you find a bug, please open the issue in the flowtools plugin repo as well.  We have a lot of work to do on the flowtools to migrate the flow reports away from Flash.  It's at the tail end of a very long list of things to do.
