### ISSUE TITLE
Data Queries - Unable to delete unused

### ISSUE THREAD

**Issue by BSOD2600** [Cacti/cacti#188]
fresh install.

a test data query just created is not able to get deleted.  After changing the Action dropdown to Delete, none of the rows are selectable, even though the column shows 0 graphs are using it. 

![image](https://cloud.githubusercontent.com/assets/5741811/21796801/eb29a896-d6bf-11e6-80cc-2ec826c3cfeb.png)

**Comment by cigamit** [comment]
There may not be a graph using the Data Query, but apparently, there is a template.  It's likely related to the other bug you submitted which we have targeted for a future release.  Simply edit the data query, and remote the template association, and you will be all set.
