### ISSUE TITLE
[1.2.0-dev] - debug option for plugins not working

### ISSUE THREAD

**Issue by pautiina** [Cacti/cacti#1885]
No any debug logs on cacti.log when enable this option on global config.

**Comment by netniV** [comment]
Hi Paultina, are you sure this is the case?  Can you provide some more details? My logging seems to be working OK.

**Comment by pautiina** [comment]
![cacti6](https://user-images.githubusercontent.com/11805503/45908709-89749400-be06-11e8-9bec-af554e4b73ad.gif)

**Comment by netniV** [comment]
@pautiina I am having no issues with debugging and base off recent posts, I think this is working for you too?

**Comment by pautiina** [comment]
I'm testing now

**Comment by pautiina** [comment]
I do not have any debug messages from plugins.

>Any files used by this plugin will be treated as they are in Debug mode.

If I correctly understood this message, then when debugging is enabled in the plugins, the debug messages of these selected plugins should appear in the CLOG. 
I have no such messages.
Or am I misunderstanding something?
![image](https://user-images.githubusercontent.com/11805503/46813339-32b40780-cd7f-11e8-9031-621b2e595b85.png)

**Comment by netniV** [comment]
For example, if you purposefully break a query that exists in say the monitor plugin, then run the code that should show not only the error but the SQL being used;

```
cacti_log('ERROR: A DB ' . $execute_name . ' Failed!, Error: ' . $en . ', SQL: \'' . clean_up_lines($sql) . '\'', false, 'DBCALL', POLLER_VERBOSITY_DEBUG);
cacti_log('ERROR: A DB ' . $execute_name . ' Failed!, Error: ' . $errorinfo[2], false);
```
Without selective plugin debug set, only the second line will appear in your logs.  This is because your normal logging level would be higher than debug (I hope!)

**Comment by netniV** [comment]
so I tested this with ReportIT and got the following without debug:
```
2018/10/11 18:30:36 - CMDPHP SQL Backtrace: (/plugins/reportit/reports.php[66]:standard(), /plugins/reportit/reports.php[334]:db_fetch_cell(), /lib/database.php[360]:db_fetch_cell_prepared(), /lib/database.php[376]:db_execute_prepared())
2018/10/11 18:30:36 - CMDPHP ERROR: A DB Cell Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
```

With plugin debug activated, I get the following and can see the extra comma:
```
2018/10/11 18:37:19 - CMDPHP SQL Backtrace: (/plugins/reportit/reports.php[66]:standard(), /plugins/reportit/reports.php[334]:db_fetch_cell(), /lib/database.php[360]:db_fetch_cell_prepared(), /lib/database.php[376]:db_execute_prepared())
2018/10/11 18:37:19 - CMDPHP ERROR: A DB Cell Failed!!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
2018/10/11 18:37:19 - DBCALL ERROR: A DB Cell Failed!, Error: 1064, SQL: 'SELECT COUNT(a.id) FROM plugin_reportit_reports AS a WHERE a.description LIKE '%','
```

Therefore, I am happy that plugin debug operation is working as expected.

**Comment by pautiina** [comment]
We have slightly different concepts about debug information. But I am not against your decision.

**Comment by netniV** [comment]
No we don't.  I have been changing plugins where I can from using their own debug options to align more with the base.  That way, debug is debug!
