### ISSUE TITLE
[Version 1.1.38]Current and Ave Ms is 100000 

### ISSUE THREAD

**Issue by koriks1111** [Cacti/cacti#1894]
Hi, 

Can you help us check why my current and ave Ms is 100000 when im using tcpping,

![image](https://user-images.githubusercontent.com/42999735/45101666-a2225000-b15e-11e8-9b0c-675d35887482.png)

but inside the device is different

![image](https://user-images.githubusercontent.com/42999735/45101732-c4b46900-b15e-11e8-8327-8ff5cc53b42f.png)

only happened in tcp ping

Cacti Version 1.1.38
SPINE 1.1.38
PHP 5.6.37

**Comment by koriks1111** [comment]
UP^

**Comment by koriks1111** [comment]
hi, 

anyone have clue on this case that i am facing?

**Comment by pautiina** [comment]
I'm use only ICMP ping. Later I will try to test TCP

**Comment by cigamit** [comment]
I really have no idea on this one.  Can you clear the statistics and see if it happens again?

**Comment by koriks1111** [comment]
yes, i did try to clear the statistics, but it will display 100000MS again after few min. 
and as mentioned, only on display having this, but inside the device have the correct MS result

**Comment by koriks1111** [comment]
Like This!

![image](https://user-images.githubusercontent.com/42999735/45205391-92b51b00-b2b4-11e8-9671-2f1f3177efaf.png)


![image](https://user-images.githubusercontent.com/42999735/45205425-abbdcc00-b2b4-11e8-99d9-aa65f80bc203.png)

**Comment by pautiina** [comment]
I tried changing the setting to TCP ping and everything is normally displayed

**Comment by koriks1111** [comment]
same version 1.1.38? :'(

**Comment by cigamit** [comment]
What data collector are you using?  Do you have either SELinux enabled?

**Comment by cigamit** [comment]
Ope, see you are using spine.

**Comment by koriks1111** [comment]
i have disabled my selinux already

**Comment by cigamit** [comment]
Run the following and provide output:

`./spine -R -V 5 -S -f the_host_id -f the_host_id`

I think `the_host_id` is 5 in your case.  Post the output.

**Comment by koriks1111** [comment]
this what im having as result
2018/09/11 15:10:43 - SPINE: Poller[1] ERROR: -f can only be used once (Spine init)

**Comment by koriks1111** [comment]
it should be like this right? 

[root@localhost bin]# ./spine -R -V 5 -S -f 5 6
SPINE: Using spine config file [../etc/spine.conf]
2018/09/11 15:15:43 - SPINE: Poller[1] DEBUG: The path_php_server variable is /usr/share/cacti/script_server.php
2018/09/11 15:15:43 - SPINE: Poller[1] DEBUG: The path_cactilog variable is /usr/share/cacti/log/cacti.log
DEBUG: The log_destination variable is 4 (STDOUT)
DEBUG: The path_php variable is /bin/php
DEBUG: The availability_method variable is 2
DEBUG: The ping_recovery_count variable is 5
DEBUG: The ping_failure_count variable is 10
DEBUG: The ping_method variable is 2
DEBUG: The ping_retries variable is 1
DEBUG: The ping_timeout variable is 400
DEBUG: The snmp_retries variable is 3
DEBUG: The log_perror variable is 0
DEBUG: The log_pwarn variable is 0
DEBUG: The boost_redirect variable is 0
DEBUG: The boost_rrd_update_enable variable is 0
DEBUG: The log_pstats variable is 0
DEBUG: The threads variable is 10
DEBUG: The polling interval is 60 seconds
DEBUG: The number of concurrent processes is 1
DEBUG: The script timeout is 180
DEBUG: The selective_device_debug variable is 7,17
DEBUG: The spine_log_level variable is 0
DEBUG: The number of php script servers to run is 1
DEBUG: StartDevice='5', EndDevice='6', TotalPHPScripts='0
DEBUG: The PHP Script Server is Not Required
DEBUG: The Maximum SNMP OID Get Size is 10
Selective Debug Devices 7,17
Version 1.1.38 starting
DEBUG: MySQL is Thread Safe!
DEBUG: Spine is running asroot.
SPINE: Initializing Net-SNMP API
DEBUG: Issues with SNMP Header Version information, assuming old version of Net-SNMP.
SPINE: Initializing PHP Script Server(s)
NOTE: Spine will support multithread device polling.
DEBUG: Initial Value of Active Threads is 0
DEBUG: Valid Thread to be Created
DEBUG: In Poller, About to Start Polling of Device for Device ID 6
SPINE: Active Threads is 1, Pending is 1
DEBUG: Valid Thread to be Created
DEBUG: In Poller, About to Start Polling of Device for Device ID 5
SPINE: Active Threads is 2, Pending is 2
Device[6] DEBUG: Entering TCP Ping
Device[5] DEBUG: Entering TCP Ping
Device[5] DEBUG: TCP Device Alive, Try Count:1, Time:1536650143910.0759 ms
Device[5] PING: Result TCP: Device is Alive
Device[5] TH[1] Device has no information for recache.
Device[5] TH[1] Total Time: 0.0017 Seconds
Device[5] TH[1] DEBUG: HOST COMPLETE: About to Exit Device Polling Thread Function
DEBUG: The Value of Active Threads is 1 for Device ID 5
POLLR: Active Threads is 1, Pending is 1
Device[6] DEBUG: TCP Device Alive, Try Count:1, Time:1536650144012.4841 ms
Device[6] PING: Result TCP: Device is Alive
Device[6] TH[1] Device has no information for recache.
Device[6] TH[1] Total Time:  0.11 Seconds
Device[6] TH[1] DEBUG: HOST COMPLETE: About to Exit Device Polling Thread Function
DEBUG: The Value of Active Threads is 0 for Device ID 6
POLLR: Active Threads is 0, Pending is 0
SPINE: The Final Value of Threads is 0
DEBUG: Thread Cleanup Complete
DEBUG: PHP Script Server Pipes Closed
DEBUG: Allocated Variable Memory Freed
DEBUG: MYSQL Free & Close Completed
DEBUG: Net-SNMP Close Completed
Time: 1.0191 s, Threads: 10, Devices: 2

**Comment by koriks1111** [comment]
is this related with my timezone and Universal time with my CentOS Machine?

   Local time: Tue 2018-09-11 16:02:51 +08
  Universal time: Tue 2018-09-11 08:02:51 UTC
        RTC time: Tue 2018-09-11 08:02:51
       Time zone: Asia/Manila (+08, +0800)
     NTP enabled: yes
NTP synchronized: yes
 RTC in local TZ: no
      DST active: n/a

**Comment by koriks1111** [comment]
Hi Netniv, 

sorry, i didn't understand your instruction, how should i run this?

**Comment by netniV** [comment]
I looked at the TIMEVAL_TO_DOUBLE macro, and made a slight alteration.  Applying this patch and recompiling spine:
```
diff --git a/spine.h b/spine.h
index 25e7584..1c7e037 100644
--- a/spine.h
+++ b/spine.h
@@ -298,7 +298,7 @@
 #define STRIMATCH(a,b) (strcasecmp((a),(b)) == 0)

 /* convert timeval to double (rounding to the nearest microsecond) */
-#define TIMEVAL_TO_DOUBLE(tv)  ( (tv).tv_sec + ((double) (tv).tv_usec / 1000000) )
+#define TIMEVAL_TO_DOUBLE(tv)   ( (double) ((tv.tv_sec * 1000000 + tv.tv_usec) / 1000000.0) )

 /* When any kind of poller wants to set an undefined value; this particular
  * value used ('U') springs from the requirements of rrdupdate. We also
```
This patch was against the latest development version, but as it's a one liner, you should be able to back port it with ease.

**Comment by koriks1111** [comment]
after adding this 
#define TIMEVAL_TO_DOUBLE(tv)   ( (double) ((tv.tv_sec * 1000000 + tv.tv_usec) / 1000000.0) )
i need to reinstall the spine?

**Comment by koriks1111** [comment]
i dont know why, but i have one device that successfully getting the correct ms result
![image](https://user-images.githubusercontent.com/42999735/45353886-bc40b000-b5ee-11e8-8dce-9ddb01eb5329.png)
![image](https://user-images.githubusercontent.com/42999735/45353938-f27e2f80-b5ee-11e8-9729-b6990e5437e3.png)

but due to confidential i will not show the URL, but the settings is same with others.

**Comment by cigamit** [comment]
No, this is related to a spine issue that may have something to do with your processor or some artifact with regard to floating point math.  I have made an update to spine.  Download the current develop version and test.

**Comment by netniV** [comment]
If he's on 1.1.38, won't the poller table be missing columns that spine expects?

**Comment by koriks1111** [comment]
the MS now is 0 for both current and Ave and having this in logs

![image](https://user-images.githubusercontent.com/42999735/45357449-d8e1e580-b5f8-11e8-9d81-9092fdf36452.png)

**Comment by cigamit** [comment]
Good point.  @koriks1111 , you should put the old spine back and then simply update ping.c from the the develop branch into the 1.1.38 source and remake and install that version.

**Comment by netniV** [comment]
To be clear @koriks1111, download [spine v1.1.38](https://github.com/Cacti/spine/archive/release/1.1.38.tar.gz), and then download the develop version of [ping.c](https://raw.githubusercontent.com/Cacti/spine/develop/ping.c) to the same directory as the extracted v1.1.38 sources before you compile it.
