### ISSUE TITLE
Notice: Undefined variable: error_class in /usr/share/cacti/lib/html_form.php on line 541

### ISSUE THREAD

**Issue by gitthismoney** [Cacti/cacti#1895]
anyone else seeing this error on path fields when in Cacti > Console > Settings > Paths?
https://imgur.com/a/k1VFpg3
appreciate the help

**Comment by netniV** [comment]
What version of cacti?

**Comment by netniV** [comment]
Forget that, just saw the image.  You can actually paste images directly into GitHub using the entry box (just hit Ctrl-V on a PC or Cmd-V on Mac).

**Comment by netniV** [comment]
Thanks for reporting this, I have now created a patch for it which will be merged later.

**Comment by cigamit** [comment]
Resolved.
