### ISSUE TITLE
[1.2.0] Beta Title should include beta version number

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1897]
Although we may only produce one beta release, we should prepare in case we decide to release others and include a version number of the beta itself.  This will allow us to create an additionally release should there be a significant change and be easier to identify/support.

**Comment by netniV** [comment]
This now also adds the beta moniker to the command line tools, plus shows the DB version (helpful to see if there is a difference)

```console
Cacti Database Upgrade Utility, Version 1.2.0 - Beta 0 (DB: 1.2.0), Copyright (C) 2004-2018 The Cacti Group
```

**Comment by cigamit** [comment]
Nice change!
