### ISSUE TITLE
Right icons for actions missing in IE11

### ISSUE THREAD

**Issue by BSOD2600** [Cacti/cacti#190]
In a Device, the collapse, delete, and refresh icons on the far right are missing.

Chrome 55:
![image](https://cloud.githubusercontent.com/assets/5741811/21796947/03618f90-d6c1-11e6-9cea-e2023e35c4f4.png)

IE11:
![image](https://cloud.githubusercontent.com/assets/5741811/21796958/1500072c-d6c1-11e6-8c19-0743d903efdb.png)

**Comment by cigamit** [comment]
This issue is related to your woff and woff2 mime types not working.  You need to add the mime-types and this issue will be resolved.
