### ISSUE TITLE
host.php and devices filtering by Device Criticality

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#191]
There is no possibility to filter devices with specified 'Device Criticality' in UI.
In my opinion this filter is important than any other.

It's serious thing if You have more than 500 devices and use grouping devices by 'Device Criticality'.

**Comment by cigamit** [comment]
This will be resolved in Monitor.  I would appreciate if you could open plugin bugs in the plugin area and not in the main Cacti area.

**Comment by interduo** [comment]
Why this is a monitor plugin bug and not cacti? 
I meant a host.php not monitor.php page.
