### ISSUE TITLE
Auto Graph of Template

### ISSUE THREAD

**Issue by mdrons** [Cacti/cacti#1915]
I am running the latest git pull of cacti and when I added a new cisco router, the Cisco Router CPU graph was auto created.   Where is this configuration?  As I want to enable some additional templates to auto create graphs.

Thanks, Mike

**Comment by netniV** [comment]
Console -> Templates -> Device

**Comment by mdrons** [comment]
I dont see it.   









   On Tuesday, September 11, 2018, 11:16:57 AM EDT, Mark Brugnoli-Vinten <notifications@github.com> wrote:  
 
 
Console -> Templates -> Device

**Comment by netniV** [comment]
Check the Automation section, this is likely to be enabled and adding the graph based off matching criteria then.

**Comment by cigamit** [comment]
Correct @netniV, it's Console > Configuration > Settings > General, then search for Automation and enable Automatic Graph Creation.  If you want Data Query based graphs created automatically, you will have to do that under Console > Automation > Graph Rules.
