### ISSUE TITLE
[1.2.0] Cannot save User Settings

### ISSUE THREAD

**Issue by skyjou** [Cacti/cacti#1916]
Configuration -> Users -> User Settings cannot be save except the admin.

**Comment by netniV** [comment]
Please give more information.

**Comment by skyjou** [comment]
For example, I try to change "Preview Thumbnail Columns" setting in "Graph Thumbnail Settings" page and save it. Everything seems good, but the columns setting will not change  to new setting.

The post data in Chrome debug is here:
`selected_theme: modern
default_view_mode: 1
user_language: en-US
hide_disabled: on
default_date_format: 4
default_datechar: 1
page_refresh: 300
preview_graphs_per_page: 10
realtime_mode: 1
default_rra_id: 1
default_timespan: 7
default_timeshift: 7
allow_graph_dates_in_future: on
first_weekdayid: 1
day_shift_start: 07:00
day_shift_end: 18:00
thumbnail_section_preview: on
**num_columns: 1**
**num_columns_tree: 1**
default_height: 100
default_width: 300
default_tree_id: 2
treeview_graphs_per_page: 10
title_size: 12
title_font: 
legend_size: 10
legend_font: 
axis_size: 8
axis_font: 
unit_size: 8
unit_font: 
id: 4
tab: settings
save_component_graph_settings: 1
action: save
__csrf_magic: sid:53f4c4f531b89abcdd2e3dbb16c592310908d549,1536711783`

I get same result in Chrome 69 and Firefox 62.

**Comment by skyjou** [comment]
No, I do not see any error in my cacti log.

**Comment by cigamit** [comment]
I would suspect this is due to a CSRF timeout.  If you hit F5, then try to save, does it work then?

**Comment by skyjou** [comment]
No, I refresh the page then try to save, but it still not works. Also, I drop the database and reinstall Cacti, and I get the same issue.

**Comment by cigamit** [comment]
Under the network panel, what is the response from the callback?

**Comment by skyjou** [comment]
HTTP/1.1 302 Found
Date: Thu, 13 Sep 2018 01:42:52 GMT
Server: Apache
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Last-Modified: Thu, 13 Sep 2018 01:42:52 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
X-Frame-Options: SAMEORIGIN
P3P: CP="CAO PSA OUR"
Location: user_admin.php?action=user_edit&header=false&id=4
Content-Length: 0
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: text/html; charset=UTF-8

**Comment by cigamit** [comment]
Okay, figured it out there were some changes to save_user_settings in conjunction with failing to pass the userid into the function.  Noted commit fixes.

**Comment by cigamit** [comment]
Going to close things I have confirmed on this one.
