### ISSUE TITLE
[1.2.0] Cannot make data template with multiple data sources (snmp indexed)

### ISSUE THREAD

**Issue by skyjou** [Cacti/cacti#1924]
I cannot make multiple data source in one data template (get snmp data indexed). When I use "+" to add data source, it will show more than one ds here, but them will disappear after I press save button. And I will find another data template in data source template list page with the same name I just try to create.

**Comment by netniV** [comment]
Please can you give the exact steps and options are you are setting as we will need to replicate to be able to diagnose this.

**Comment by skyjou** [comment]
I try to execute the same step in 0.8.8c and 1.2.0-Beta0:

![cacti_data_template](https://user-images.githubusercontent.com/13309854/45581003-087b4100-b8ca-11e8-8469-e6185761f4df.gif)

**Comment by skyjou** [comment]
I try to execute same step on 0.8.8c and 1.2.0-beta0:

![cacti_data_template](https://user-images.githubusercontent.com/13309854/45581088-30b76f80-b8cb-11e8-952c-ee354e84df79.gif)

**Comment by cigamit** [comment]
Thanks for testing.  This is resolved now.
