### ISSUE TITLE
Incorrect  behavior in graphs and datasources (500 rows)

### ISSUE THREAD

**Issue by xmacan** [Cacti/cacti#1925]
I'm trying Reapply suggested names (console -> graphs or data sources) with 500 rows. I can choose all rows and on next page I have this:
![screenshot_2018-09-13 console - graph management](https://user-images.githubusercontent.com/26485719/45509810-d4ecc980-b798-11e8-8170-33c5d6cc1786.png)

Reapply works only for correctly named lines. Lines |host_description| - Traffic - |query_ifName| remain unchanged.

Tested on 1.1.38

**Comment by netniV** [comment]
There was an issue already opened on here for this.  it's actually a bug with the t_name field being populated with 0.  If it's the same bug, please close this one.

**Comment by xmacan** [comment]
Sorry, you are right. It is #328. 
Workaround is reapply only for one data template.

**Comment by pautiina** [comment]
@You are not right
It is #1614.

**Comment by netniV** [comment]
I think you'll find it's also a bit of #1617 and #1530.  Currently there is a backport for #1530 in #1880
