### ISSUE TITLE
Deselecting items should present warning or disable GO button

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1926]
When you select a list of items to be removed, you may inadvertenly select a non-deletable item.  These are unselected automatically, which is correct.  However, you may not realise this and so it can lead to the scenario were you attempt to do this, click Go and then are presented with a warning saying that you need to select items. This can cause confusion as you had previously selected items.

Alternatively, the GO button should be disabled unless items are selected (if required).

**Comment by pautiina** [comment]
I also think that he simply forgot. Created a issue to see it.

**Comment by cigamit** [comment]
This is resolved IMHO.
