### ISSUE TITLE
[1.2.0] Get a lot of error message in cacti log after update to commit #83b6372

### ISSUE THREAD

**Issue by skyjou** [Cacti/cacti#1927]
After update to commit [83b6372](https://github.com/Cacti/cacti/commit/83b63720b6511311b97f0caf7dbd601c2a70d0dd), cacti log show a lot of error messages:
`2018/09/15 11:18:05 - CMDPHP SQL Backtrace: (/poller.php[585]:db_fetch_cell_prepared(), /lib/database.php[356]:db_execute_prepared())`

`2018/09/15 11:18:05 - CMDPHP ERROR: A DB Cell Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '*) FROM poller_time WHERE poller_id = '1' AND end_time >'0000-00-00 00:00:00'' at line 1`

**Comment by netniV** [comment]
That commit has introduced SQL errors.  I will create a patch for this shortly.

**Comment by netniV** [comment]
I've submitted a fix and will try and get it committed asap.

**Comment by netniV** [comment]
This has now been merged. Please redownload.
