### ISSUE TITLE
[1.2.0] Device with ping detection method never update status

### ISSUE THREAD

**Issue by skyjou** [Cacti/cacti#1928]
Device monitoring via ping method seems not work:
![image 1](https://user-images.githubusercontent.com/13309854/45584914-4ac67180-b90e-11e8-9353-255e50fac39a.png)

I have test this on 1.1.38, and it work fine.

**Comment by netniV** [comment]
Are you using CMD.PHP or Spine?

**Comment by skyjou** [comment]
I use spine.

**Comment by netniV** [comment]
Please run the following to give more information:

```
<path to spine>/spine -f=<id of host> -l=<id of host> -C=<path to spine conf>/spine.conf -V=5 -R
```

**Comment by skyjou** [comment]
./spine -f=10 -l=10 -C=../etc/spine.conf -V=5 -R
SPINE: Using spine config file [../etc/spine.conf]
2018/09/15 20:34:30 - SPINE: Poller[1] DEBUG: The path_php_server variable is /opt/cacti-web/script_server.php
2018/09/15 20:34:30 - SPINE: Poller[1] DEBUG: The path_cactilog variable is /opt/cacti-web/log/cacti.log
2018/09/15 20:34:30 - SPINE: Poller[1] DEBUG: The log_destination variable is 1 (FILE)
2018/09/15 20:34:30 - SPINE: Poller[1] DEBUG: The path_php variable is /usr/bin/php
2018/09/15 20:34:30 - SPINE: Poller[1] DEBUG: The availability_method variable is 2
2018/09/15 20:34:30 - SPINE: Poller[1] DEBUG: The ping_recovery_count variable is 3
2018/09/15 20:34:30 - SPINE: Poller[1] DEBUG: The ping_failure_count variable is 2
2018/09/15 20:34:30 - SPINE: Poller[1] DEBUG: The ping_method variable is 2
2018/09/15 20:34:30 - SPINE: Poller[1] DEBUG: The ping_retries variable is 1
2018/09/15 20:34:30 - SPINE: Poller[1] DEBUG: The ping_timeout variable is 400
2018/09/15 20:34:30 - SPINE: Poller[1] DEBUG: The snmp_retries variable is 3
2018/09/15 20:34:30 - SPINE: Poller[1] DEBUG: The log_perror variable is 1
2018/09/15 20:34:30 - SPINE: Poller[1] DEBUG: The log_pwarn variable is 0
2018/09/15 20:34:30 - SPINE: Poller[1] DEBUG: The boost_redirect variable is 0
2018/09/15 20:34:30 - SPINE: Poller[1] DEBUG: The boost_rrd_update_enable variable is 0
2018/09/15 20:34:30 - SPINE: Poller[1] DEBUG: The log_pstats variable is 0
2018/09/15 20:34:30 - SPINE: Poller[1] DEBUG: The threads variable is 10
2018/09/15 20:34:30 - SPINE: Poller[1] DEBUG: The polling interval is 60 seconds
2018/09/15 20:34:30 - SPINE: Poller[1] DEBUG: The number of concurrent processes is 1
2018/09/15 20:34:30 - SPINE: Poller[1] DEBUG: The script timeout is 25
2018/09/15 20:34:30 - SPINE: Poller[1] DEBUG: The selective_device_debug variable is 10
2018/09/15 20:34:30 - SPINE: Poller[1] DEBUG: The spine_log_level variable is 0
2018/09/15 20:34:30 - SPINE: Poller[1] DEBUG: The number of php script servers to run is 1
2018/09/15 20:34:30 - SPINE: Poller[1] DEBUG: StartDevice='10', EndDevice='10', TotalPHPScripts='0'
2018/09/15 20:34:30 - SPINE: Poller[1] DEBUG: The PHP Script Server is Not Required
2018/09/15 20:34:30 - SPINE: Poller[1] DEBUG: The Maximum SNMP OID Get Size is 10
2018/09/15 20:34:30 - SPINE: Poller[1] Selective Debug Devices 10
2018/09/15 20:34:30 - SPINE: Poller[1] Version 1.2.0 starting
2018/09/15 20:34:30 - SPINE: Poller[1] DEBUG: MySQL is Thread Safe!
2018/09/15 20:34:30 - SPINE: Poller[1] DEBUG: Spine running as 1000 UID, 0 EUID
2018/09/15 20:34:30 - SPINE: Poller[1] DEBUG: Spine is running as root.
ERROR: Spine Log File Could Not Be Opened/Created
2018/09/15 20:34:30 - SPINE: Poller[1] DEBUG: Spine has got ICMP
2018/09/15 20:34:30 - SPINE: Poller[1] SPINE: Initializing Net-SNMP API
2018/09/15 20:34:30 - SPINE: Poller[1] DEBUG: Issues with SNMP Header Version information, assuming old version of Net-SNMP.
2018/09/15 20:34:30 - SPINE: Poller[1] SPINE: Initializing PHP Script Server(s)
2018/09/15 20:34:30 - SPINE: Poller[1] NOTE: Spine will support multithread device polling.
2018/09/15 20:34:30 - SPINE: Poller[1] DEBUG: Initial Value of Active Threads is 0
2018/09/15 20:34:30 - SPINE: Poller[1] DEBUG: Valid Thread to be Created
2018/09/15 20:34:30 - SPINE: Poller[1] SPINE: Active Threads is 1, Pending is 1
2018/09/15 20:34:30 - SPINE: Poller[1] DEBUG: In Poller, About to Start Polling of Device for Device ID 10
2018/09/15 20:34:30 - SPINE: Poller[1] Device[10] DEBUG: Entering ICMP Ping
2018/09/15 20:34:30 - SPINE: Poller[1] Device[10] DEBUG: ICMP Device Alive, Try Count:1, Time:20.6411 ms
2018/09/15 20:34:30 - SPINE: Poller[1] Device[10] PING: Result ICMP: Device is Alive
2018/09/15 20:34:30 - SPINE: Poller[1] Device[10] TH[1] Device has no information for recache.
2018/09/15 20:34:30 - SPINE: Poller[1] Device[10] TH[1] Total Time: 0.025 Seconds
2018/09/15 20:34:30 - SPINE: Poller[1] Device[10] TH[1] DEBUG: HOST COMPLETE: About to Exit Device Polling Thread Function
2018/09/15 20:34:30 - SPINE: Poller[1] DEBUG: The Value of Active Threads is 0 for Device ID 10
2018/09/15 20:34:30 - SPINE: Poller[1] POLLER: Active Threads is 0, Pending is 0
2018/09/15 20:34:31 - SPINE: Poller[1] SPINE: The Final Value of Threads is 0
2018/09/15 20:34:31 - SPINE: Poller[1] DEBUG: Thread Cleanup Complete
2018/09/15 20:34:31 - SPINE: Poller[1] DEBUG: PHP Script Server Pipes Closed
2018/09/15 20:34:31 - SPINE: Poller[1] DEBUG: Allocated Variable Memory Freed
2018/09/15 20:34:31 - SPINE: Poller[1] DEBUG: MYSQL Free & Close Completed
2018/09/15 20:34:31 - SPINE: Poller[1] DEBUG: Net-SNMP Close Completed
2018/09/15 20:34:31 - SPINE: Poller[1] Time: 1.0716 s, Threads: 10, Devices: 1

**Comment by netniV** [comment]
So, clearly, it pinged the device successfully.  Let me see what comes next in setting the status.

**Comment by skyjou** [comment]
I am so sorry... I check my setting on test server again, and I find it use cmd.php as poller. When I switch it to spine, the status update well.

**Comment by netniV** [comment]
So this appears to be a CMD.PHP ping problem?

**Comment by netniV** [comment]
Out of interest, do you have SELinux enabled?

**Comment by skyjou** [comment]
No, I use Ubuntu 18.04.
