### ISSUE TITLE
No timeout option

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#194]
In our NOC room there is a computer with always_poweredon_cacti.
How to show turn off timeout for specified user?

**Comment by cigamit** [comment]
Goto Settings->Authentication and enable Authentication Cookies.  The user should then log out and back in again and when doing so, check 'Remember Me'.  Cacti does not log you out automatically when Authentication Cookies are enabled.

The other approach is to edit your php.ini file and set session.gc_maxlifetime to a very large value and restart Apache.  This will in effect do the same thing, but note you will get session files languishing that way.

**Comment by cigamit** [comment]
I'm going to close this as the gc_maxlifetime is the way we went.  Going to stick with that for the moment.

**Comment by interduo** [comment]
What is  gc_maxlifetime ?
