### ISSUE TITLE
Open in New Tab problem

### ISSUE THREAD

**Issue by fouadmfam** [Cacti/cacti#1943]
Dears.
I hope your doing good.
I have cacti V 1.1.38 
Issue 👍 
when i open Graphs in Tree Mode then select branch from the list in the left side it open normally.
but if i open a branch in tab1 and right click  (open in new tab) on another branch from list in same tab, its open the old branch in tab 1.
why this issue happen, kindly advice.
not its happened in browser IE, FireFox, chrom
thank you.

**Comment by netniV** [comment]
This has been addressed in v1.2 that will be out in beta shortly.
