### ISSUE TITLE
The select all checkbox in console-->devices does not work

### ISSUE THREAD

**Issue by dsclassen** [Cacti/cacti#195]
The "select all" checkbox at the top of the check box column will uncheck selections, but does not appear to select.
![host_check_all](https://cloud.githubusercontent.com/assets/8882563/21816323/a04bea1e-d714-11e6-979c-aa886c71649c.png)

**Comment by cigamit** [comment]
Either F5 (most browsers), or Ctrl+R (Chrome), to refresh your layout.js, then it'll start working.
