### ISSUE TITLE
Installer says GMP is Required and Optional PHP Module

### ISSUE THREAD

**Issue by ronytomen** [Cacti/cacti#1952]
We should confirm it is "Required" or "Optional" and then make sure it's not both in the installer.

**Comment by netniV** [comment]
I noticed this when I updated the documentation recommendations.  I haven't applied it back to the code though as I was waiting on an answer as to which way it should be.

**Comment by ronytomen** [comment]
A quick search shows that only `vendor/phpseclib` optionally use the `gmp` or `bcmath` PHP modules.

`bcmath` on the other hand is used by the poller.

- `bcmath` is required
- `gmp` is optional

**Comment by netniV** [comment]
Is it optional only if you don't have a remote poller though?

**Comment by browniebraun** [comment]
GMP is required to run a RRDproxy as data backend due to RSA encryption.

Outlook for Android<https://aka.ms/ghei36> herunterladen

________________________________

**Comment by netniV** [comment]
I think the same thing is used by the pollers too.  So, rather than have one optional component that is probably used, do we just say that it is required anyway?

**Comment by netniV** [comment]
OK, that just leaves SNMP module as optional.

**Comment by netniV** [comment]
This now matches with the [Requirements](https://github.com/Cacti/documentation/blob/develop/Requirements.md) documentation
