### ISSUE TITLE
Installer Warning previous version needs fixing

### ISSUE THREAD

**Issue by ronytomen** [Cacti/cacti#1954]
> WARNING: If you are upgrading from a previous version please close all Cacti browser sessions and clear cache before continuing. Additionally, after this script is complete, you will also have to refresh your page to load updated JavaScript so that the Cacti pages render properly. In Firefox and IE, you simply press F5. In Chrome, you may have to clear your browser cache for the Cacti web site.

This needs to be reworded and not so technical.

Something like "Make sure all users have logged off Cacti before continuing.  If users experience issues with Cacti after upgrade has been completed make sure to clear appropriate site and cookies from their web browsers."

**Comment by netniV** [comment]
Yeah, I would agree with that.  It's the same warning that's existed forever, but could be split into a two part description of non-technical then more detailed info.  To be honest, I do not believe this is an issue since we introduced the md5 hash onto the URL's used to include javascript, css etc.

**Comment by netniV** [comment]
I'm not really sure how to re (word|work) this... The `WARNING:` should be a short warning I think, but whether the `English` version of the text goes before/after the warning or `Technical` information is something I am struggling to decide upon.  Also, `English` is like my umpteenth language after all the programming ones I know ;-)

**Comment by netniV** [comment]
![image](https://user-images.githubusercontent.com/9052188/45926528-43f5bb00-bf1b-11e8-8f3e-170d822e5b07.png)

> WARNING:	In the event of issues, It is highly recommended that you clear your browser cache, closing then reopening your browser (not just the tab Cacti is on) and retrying, before raising an issue with The Cacti Group
>
>On rare occasions, we have had reports from users who experience some minor issues due to changes in the code. These issues are caused by the browser retaining pre-upgrade code and whilst we have taken steps to minimise the chances of this, it may still occur. If you need instructions on how to clear your browser cache, https://www.refreshyourcache.com/ is a good starting point.
>
>If, after clearing your cache and restarting your browser, you still experience issues please raise the issue with us and we will try to identify the cause of it.

My latest QA patch has this change.
