### ISSUE TITLE
Allow linking to graph previews of a host by it's external id

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#1969]
We use CRM called LMS and there we have an netdevice ID column in DB. 
In Cacti we have externalid in device propeties whitch is an id from LMS.

We would like to create link for LMS to see graphs for device with special external id.
For example "https://cacti/graph.php?externalid=123"

Could You implement this feature? It would be very usefull and this is few lines of code.

**Comment by interduo** [comment]
Yes.

**Comment by netniV** [comment]
So this will be added to 1.2
