### ISSUE TITLE
SpikeKill Menu does not display properly

### ISSUE THREAD

**Issue by pautiina** [Cacti/cacti#1973]
![cacti8](https://user-images.githubusercontent.com/11805503/46002830-bc917e80-c0b7-11e8-84bb-415dc7cdfa91.gif)

**Comment by netniV** [comment]
They say a picture says a thousand words... so an animated gif means you've just written an entire thesis? ;-)

Which browser were you in?

**Comment by pautiina** [comment]
On Firefox also have this issue:
![image](https://user-images.githubusercontent.com/11805503/46005680-7855ac80-c0be-11e8-84aa-55f353d44911.png)
![image](https://user-images.githubusercontent.com/11805503/46005693-80ade780-c0be-11e8-8d20-b2366457b188.png)

**Comment by netniV** [comment]
So as I've never used that feature before... I can't actually find it.  I looked at graphs tab, device graphs, etc.  Maybe I need a spike for it to appear?

**Comment by pautiina** [comment]
This button is located in the device tree near each chart. Perhaps you need to check the permissions to use this function in the user settings

**Comment by netniV** [comment]
I have managed to fix some of this.  I will have to do more later though as it's meeting time now.

**Comment by netniV** [comment]
![menu](https://user-images.githubusercontent.com/9052188/46028352-39d4e780-c0e8-11e8-86da-5cde9ad20989.gif)

Ooo look at this spanky looking menu... 👍

**Comment by netniV** [comment]
This should now be resolved with the exception of #1978 and #1979
