### ISSUE TITLE
Default admin permissions do not allow everything?

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1976]
![image](https://user-images.githubusercontent.com/9052188/46013770-177da280-c0c5-11e8-9f30-6f0b2ca21489.png)

This is from a fresh install.  Should the admin be blocked from the areas that are currently disallowed?

**Comment by pautiina** [comment]
I think that `Primary Admin` must have allowing for all options

**Comment by cigamit** [comment]
Resolved.
