### ISSUE TITLE
[1.2.0] when creating graphs for the first time, the data sources do not apply the name

### ISSUE THREAD

**Issue by pautiina** [Cacti/cacti#1981]
![cacti9](https://user-images.githubusercontent.com/11805503/46071474-c20ac980-c188-11e8-85ed-3a4ccedbc7b2.gif)

**Comment by skyjou** [comment]
I have same issue, too.

**Comment by cigamit** [comment]
Update lib/data_query.php and check again.

**Comment by netniV** [comment]
Wouldn't they also need the updated lib/utility.php too?

**Comment by cigamit** [comment]
Yes, thanks for pointing that out.

**Comment by skyjou** [comment]
I use the [latest commit](https://github.com/Cacti/cacti/commit/b3ea9a94b906efe2dea664ac4210d46cd0d901b7), but it still need manual update for ds name.

**Comment by netniV** [comment]
Ok, thanks.

**Comment by pautiina** [comment]
Confirm, not fixed yet.

**Comment by cigamit** [comment]
Can you guys check with the latest updates?  I can not reproduce this.

**Comment by pautiina** [comment]
Not fixed

**Comment by netniV** [comment]
On a brand new install, I can't replicate this either.  Creation of graphs and data sources appear to have the correct name.  When I attempt to reapply, no changes are seen.

**Comment by pautiina** [comment]
I can provide access to teamviewer. If you agree write to mail.

**Comment by netniV** [comment]
Sorry, I won't have time today.

**Comment by anarkia1976** [comment]
the same here.

**Comment by cigamit** [comment]
If this does not work, I will resort to instrumentation.

**Comment by pautiina** [comment]
Unfortunately - not fixed

**Comment by skyjou** [comment]
Not working in my machine too.

**Comment by pautiina** [comment]
In my opinion, when I created graph for 32 bit counters, it created names only for those interfaces that had an IP address

**Comment by pautiina** [comment]
![image](https://user-images.githubusercontent.com/11805503/46671203-d9ac6e00-cbdc-11e8-8857-11b85569fcb3.png)
Now I try to make them identical.

**Comment by pautiina** [comment]
Unfortunately, the names are not applied to 64-bit counters, even when I made Data Queries the same as for 32-bit counters

**Comment by cigamit** [comment]
So, it's working with the 32bit graphs?

**Comment by skyjou** [comment]
No, both of them are not working.

**Comment by cigamit** [comment]
I've made a small change to lib/variables.php.  You should be able to simply re-apply suggested names.

**Comment by pautiina** [comment]
> So, it's working with the 32bit graphs?
For 32-bit counters, it only partially works:
> it created names only for those interfaces that had an IP address

**Comment by cigamit** [comment]
Just saw it.  Update the lib/variables.php, and test again.  I'm concerned about that other issue of course.

**Comment by pautiina** [comment]
I have full update by `git pull` but not fixed :(

**Comment by pautiina** [comment]
How about a TeamViewer?

**Comment by pautiina** [comment]
fixed
