### ISSUE TITLE
Certain hooks should occur within api functions rather than UI functions

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1982]
For example, when removing devices, if this is done via the API, no hook is performed.  However, the UI will call `api_plugin_hook_function('device_remove', $devices_to_act_on)` but only AFTER the devices are removed which is too late to get any information about the device or ever prevent it.

**Comment by arno-st** [comment]
It can be great if the $device_to_act_on send to the hook is not just the host_id, but also the whole record of the host, so the plugin can use any information to react correctly

**Comment by cigamit** [comment]
We can do this for devices now.  I don't have a problem with that.  For other hooks, we should have a business case.

**Comment by cigamit** [comment]
Resolved.

**Comment by netniV** [comment]
I'm not following, api_hooks should occur within API's, not GUI's... so I would say that whilst this specific example is to do with device removal, there are many more. It's a bigger project than just this one example.
