### ISSUE TITLE
set_default_action() should warn if more than one action provided

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1983]
The `set_default_action()` function should warn if more than one action is being provided.  If the actions are different, an error should be logged and message should be raised to alert to the problem.

For example, reportit was having an issue with exporting templates under 1.2-beta-0 and it turns out that the posted variables are wrong:

```
__csrf_magic: sid:4f4769e104608f9826c9a2e6ec6459f0e1bd7604,1537979403
action: template_export
template_id: 0
template_description: 
template_author: 
template_verion: 
template_contact: 
action: save
```
I left all fields blank, hence no values, but there are two actions and only the first is the one that is valid.

**Comment by cigamit** [comment]
Resolved.
