### ISSUE TITLE
Cookie should be properly verified against password

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1985]
I believe that currently, if the password has been verified and the "Save password" option ticked during login, a cookie is created which links to the username.  However, if the password is changed, the cookie will still be valid thus allowing someone who had stored the password access when they should not have.

**Comment by cigamit** [comment]
My suggesting at this time is that we do the following:
More short term, I suggest the following:

1) Provide option to log out everywhere on password change.
2) When changing the password, if that option is set, the token table should be cleared of all logins except the current.
3) Though unrelated, when all but the Admin changes a users email, prompt for the users password.

**Comment by netniV** [comment]
I like that suggestion.

**Comment by netniV** [comment]
https://stackoverflow.com/a/43742898/697159

```php
function destroy_third_party_session($in_session_id){
  session_id($in_session_id); // Sets the session id;
  session_start(); // starts the session as that session id
  session_destroy(); // destroy the session
  session_commit();
}
```
I like this idea, only instead of destroying the session, it should set a session flag so that a user is forced to logout on the next call.  This would be safer since it doesn't affect any running sessions until they check for the logout indicator allowing operations to be properly completed.

**Comment by TheWitness** [comment]
This issue is fixed now.

**Comment by ddb4github** [comment]
How about change password by some admin at user_admin.php
