### ISSUE TITLE
Upgrade rrdtool 1.4 to 1.7 cacti

### ISSUE THREAD

**Issue by randymendes123** [Cacti/cacti#1986]
Hi all 
someone can help me to Upgrade rrdtool 1.4 to 1.7 cacti centos 7

**Comment by netniV** [comment]
That's not really a topic for this repo.  You could ask on our forums:
https://forums.cacti.net

If you need to google for something, look for those words in google.

**Comment by randymendes123** [comment]
thanks @netniV
