### ISSUE TITLE
[1.2.0] Device Add - When you pick a preset Device Template it is not used when creating new device

### ISSUE THREAD

**Issue by cigamit** [Cacti/cacti#1989]
Once you set the default Device Template under Settings > Device Defaults, it should be used during creation and right now that is apparently not working.

**Comment by netniV** [comment]
Is that a 1.2 thing or does it occur in 1.1.38 too?

**Comment by cigamit** [comment]
It was a new feature, but let me double check.

**Comment by cigamit** [comment]
Yea, new feature.

**Comment by cigamit** [comment]
Resolved.
