### ISSUE TITLE
Plugin Realm should have a 'role' to help maintain changes between plugins

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1990]
Table `plugin_realms` should have a new column added called `role` along with updating existing functions to be able to pass `role`.  If no role is passed, assume 'common' as a default role (this enables backwards compatibility).

This will allow plugin owners to update their realms without creating duplicates as seen in cacti/plugin_reportit#49

**Comment by cigamit** [comment]
This way, we can group all realms instead of by plugin, by role.  Current roles includes:

* normal user, 
* template editor, 
* general administration, 
* system administration

**Comment by cigamit** [comment]
It also makes it easier to update realms.  Right now realm management for plugins is pretty much broken.

**Comment by TheWitness** [comment]
Moving this forward a bit to the 1.2.11 release.  Plugins will have to adopt.

**Comment by TheWitness** [comment]
Fixed.  Also responsive using flexi-grid layout.
