### ISSUE TITLE
Create new Device, Edit Device, Loss of place

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1994]
Weird bug:

1. Create a new device, fill in the details, click create
2. On the edit screen that appears, Create a new Device
3. Realise you're an idiot and meant to click Create new graphs
4. Click back to go click Create new graphs
5. Realise, your still at Create a new device... because it's lost the device info of the device you were editing

**Comment by cigamit** [comment]
I know exactly what you are talking about.  Done it myself.

**Comment by TheWitness** [comment]
This appears to be resolved.  Therefore, I'm going to close this one.
