### ISSUE TITLE
Installer should detect an empty database and offer to populate

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1996]
If the installer sees an empty database, it should have the ability to populate with the cacti.sql supplied.  That way a new system can be up and running within a single CLI command or by going directly to the website and does not require an end user or admin, to launch mysql and source the cacti.sql manually.

**Comment by cigamit** [comment]
Yea, you would have to check on the CREATE TABLE permission.  Should be doable.

**Comment by netniV** [comment]
Didn't we already add that check somewhere?  Maybe it was in a plugin, I can't recall.

**Comment by cigamit** [comment]
Same here.  Don't remember.  The one that keeps biting us is the ability to create temporary tables.

**Comment by netniV** [comment]
This was partially done in 40ed06a2a86f2de70400455fbe1847a9191e5b66 to detect an empty database.

Currently, it doesn't offer to populate from the local cacti source.

**Comment by TheWitness** [comment]
Closing this one.  I don't think it's realistic.  The web service likely does not have the permissions anyway.  It's a small thing anyway.
