### ISSUE TITLE
We should party like it's #1999

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1999]
With all the recent changes, fixes, enhancements we have been doing, I think we deserve a small party like it's 1999!

![](https://thumbs.gfycat.com/DiscretePointedAustralianshelduck-size_restricted.gif)![](https://media.giphy.com/media/RMY8y3A3lr19S/giphy.gif)![](https://2r62j11x4zsy3ytak02nzvbk24y-wpengine.netdna-ssl.com/wp-content/uploads/2016/04/giphy-88.gif)![](https://media.giphy.com/media/BYc20U4C2PDHO/200.gif)![](https://media.giphy.com/media/6Ft0CNloTrRAs/giphy.gif)![](http://pa1.narvii.com/6383/c5fa99a2b9db060b2f4350ad4f05bdc03dfdb604_00.gif)
![](http://38.media.tumblr.com/12f34ba68aa2a1534fcc3e4b4eb48dc3/tumblr_ml4acfiWnX1s95oy9o2_500.gif)

**Comment by eschoeller** [comment]
hahaha heck yeah!!

**Comment by jpobeda** [comment]
Count me in hehe

**Comment by eschoeller** [comment]
So does this mean there's an official 1.2.0 release right around the corner?

**Comment by TheWitness** [comment]
Let's hope so!

**Comment by jhonnyx82** [comment]
good luck really :)

**Comment by ronytomen** [comment]
😃
