### ISSUE TITLE
Graphs Management, Filtering Option "Template" Broken

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#200]
graphs.php, Modern Skin

If I open list Template there are doubled position:

54x In/Out Non-Unicast Packets
54x In/Out Errors Discarded Packets
54x In/Out Bits
54x In/Out with total bandwidth
and others from Interface Traffic

**Comment by interduo** [comment]
Maybe this will help.

2017-01-11 11:59:31 - CMDPHP Filter Variable: graph_template_id, Must have a default and none is set
2017-01-11 11:59:25 - CMDPHP Filter Variable: graph_template_id, Must have a default and none is set 
(?)

**Comment by cigamit** [comment]
It's not related to that section of code, but I did sweep the code and found a few areas where if a user had not set a default, one is set automatically.

**Comment by interduo** [comment]
You did a cleaning in code but it partly resolved this issue.

graphs.php, Modern Skin

If I open list Template there are doubled position:

54x In/Out Non-Unicast Packets
54x In/Out Errors Discarded Packets
54x In/Out Bits
54x In/Out with total bandwidth
and others from Interface Traffic

Please reopen It.

**Comment by interduo** [comment]
![zrzut ekranu z 2017-01-11 11-57-49](https://cloud.githubusercontent.com/assets/17087236/21849727/88ee6fce-d807-11e6-877f-f557034e791c.png)

**Comment by cigamit** [comment]
I believe I fixed this last night in this commit
https://github.com/Cacti/cacti/commit/01b29eb7544194bd1b9b747d3eb4e3154f787b1a

**Comment by interduo** [comment]
Thank You.
