### ISSUE TITLE
Cacti 1.2 fresh install - PHP ERRORs

### ISSUE THREAD

**Issue by jpobeda** [Cacti/cacti#2000]
Primary server install.

Not much to add, fresh install and right after I had these errors on clog.

```markdown
2018/09/30  10:37:03 - CMDPHP PHP ERROR WARNING Backtrace:   (/poller.php[758]:poller_replicate_check(),  /poller.php[791]:CactiErrorHandler())
--
2018/09/30 10:37:03 - ERROR PHP WARNING: Invalid argument supplied  for foreach() in file: /var/www/html/cacti/poller.php  on line: 791
2018/09/30 10:37:03 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'last_sync' in 'where clause'
```

**Comment by jpobeda** [comment]
Done, I'll give it a couple of cycles and update.

```shell
[root@cacti12 cli]# php -q upgrade_database.php --forcever=1.1.38
Upgrading from v1.1.38
Upgrading from v1.1.38 (DB 1.2.0 - Beta 0 (DB: 1.2.0)) to v1.2.0
+++++++++++-+++++++++++++++++++
```

**Comment by netniV** [comment]
I believe this was a fresh install, nothing should be missing?

**Comment by jpobeda** [comment]
Yep, it was a fresh install.

**Comment by jpobeda** [comment]
OK, that fixed it. But don't forget it was a fresh install and whatever it was should have been covered during the installation process.

**Comment by cigamit** [comment]
It's there.  See below.  Not sure what you did wrong.

![pollers](https://user-images.githubusercontent.com/957322/46251545-ccdc8d00-c41a-11e8-95cf-d4063807700b.PNG)

**Comment by jpobeda** [comment]
What table is that? I'll create a new db and do a fresh install so I can then check the table.
Or even better, is there a way to run that upgrade_database in debug mode to see what has been fixed?

**Comment by cigamit** [comment]
It's the poller table.

**Comment by jpobeda** [comment]
I ran a git pull and did a full fresh install, no issues seen.

**Comment by netniV** [comment]
I saw this issue today.  So, it may not actually be resolved.
