### ISSUE TITLE
Installer MySQL Recommendations and MariaDB 10.1

### ISSUE THREAD

**Issue by cigamit** [Cacti/cacti#2004]
When upgrading you get this MySQL recommendation

> Database Collation
> Your database default collaction does NOT appear to be UTF8 compliant
> 
> WARNING:	Any tables created by plugins may have issues linked against Cacti Core tables if the > collation is not matched
> 
> Please ensure your database is changed from 'latin1_swedish_ci' to 'utf8mb4_unicode_ci' by modifying your MySQL/MariaDB service' configuration file. This is typically located in /etc/mysql/my.cnf or similar.
> 
> Under the [mysqld] section, locate the entries named 'character-set-server' and 'collation-server' and set them as follows:
> 
> [mysqld]
> character-set-server=utf8mb4
> collation-server=ubt8mb4_unicode_ci

but the last line
> collation-server=ubt8mb4_unicode_ci

with MariaDB 10.1 will cause your MySQL Server to not start up.  This is the error
**[ERROR] Unknown collation: 'ubt8mb4_unicode_ci'**

**Comment by cigamit** [comment]
ubt8mb4_unicode_ci
should probably be
utf8mb4_unicode_ci

**Comment by cigamit** [comment]
Fixed

**Comment by netniV** [comment]
Correct. Javier did send that as a fix earlier, I thought it had been added.

**Comment by cigamit** [comment]
Ya, I am just going through again and seeing what I can find now.

**Comment by cigamit** [comment]
I do notice that even if I set that on MariaDB 10.1, it doesn't change my default collation.

SHOW VARIABLES LIKE  "collation_database"
collation_database    latin1_swedish_ci

**Comment by netniV** [comment]
What OS?

**Comment by cigamit** [comment]
Centos 7.  Still debugging this.  I changed the Cacti table itself to have the correct collation also, and the above SQL query shows the correct collation, but I still get the warning message.

**Comment by cigamit** [comment]
Ok, seems to be working now after changing it directly in the schema.

**Comment by jpobeda** [comment]
I've noticed the same thing even after changing the char set and collation manually the warning was still showing up. But I didn't go as far as cigamit so I'd be nice to know the extra step so I put it on my notes as well hehe

**Comment by ronytomen** [comment]
Might be cached in the DB connection.  Try restarting the web server and see if it still warns.

**Comment by jpobeda** [comment]
Tried that, didn't make any difference. 

It's a bit odd because the first time I saw it I added these lines and restarted mariadb and bingo. All happy.

```markdown
[mysqld]
character-set-server=utf8mb4
collation-server=utf8mb4_unicode_ci
```

Now I'm puzzled because the only thing it changed between the first install and the second was the database I dropped and re created.

**Comment by netniV** [comment]
If the DB already exists it’s coalition is already set. Maybe that’s the reason
