### ISSUE TITLE
Upgrading causes InnoDB Table Conversions even when unselected

### ISSUE THREAD

**Issue by cigamit** [Cacti/cacti#2005]
When upgrading, if you unselect tables to not convert to InnoDB, it will still attempt to convert them during the upgrade process.

Below, the 3 tables were unselected in the UI.

2018/09/30 16:12:50 - CMDPHP SQL Backtrace: (/cli/convert_tables.php[181]:db_execute(), /lib/database.php[176]:db_execute_prepared())
2018/09/30 16:12:50 - CMDPHP ERROR: A DB Exec Failed!, Error: Specified key was too long; max key length is 767 bytes
2018/09/30 16:12:50 - INSTALL: always: Converting Table #3 'sessions'
2018/09/30 16:12:50 - CMDPHP SQL Backtrace: (/cli/convert_tables.php[181]:db_execute(), /lib/database.php[176]:db_execute_prepared())
2018/09/30 16:12:50 - CMDPHP ERROR: A DB Exec Failed!, Error: Specified key was too long; max key length is 767 bytes
2018/09/30 16:12:50 - INSTALL: always: Converting Table #2 'poller_resource_cache'
2018/09/30 16:12:50 - CMDPHP SQL Backtrace: (/cli/convert_tables.php[181]:db_execute(), /lib/database.php[176]:db_execute_prepared())
2018/09/30 16:12:50 - CMDPHP ERROR: A DB Exec Failed!, Error: Specified key was too long; max key length is 767 bytes
2018/09/30 16:12:50 - INSTALL: always: Converting Table #1 'host_snmp_cache'
2018/09/30 16:12:50 - INSTALL: always: Found 3 tables to convert

**Comment by cigamit** [comment]
Doing more research, we should add the following to recommended config

`innodb_large_prefix=1`
`innodb_file_format=Baracuda`

**Comment by jpobeda** [comment]
But make it `innodb_file_format=Barracuda` with double 'R'

**Comment by cigamit** [comment]
Granted, this won't fix the original issue though.  Since it is upgrading the tables even though we unselect them so it doesn't.

**Comment by netniV** [comment]
Yes, I will look at why the tables upgraded.  That functionality was tried and tested a long time ago in the installer's life time, so something has changed which means it's assuming they all need doing.  The INNODB things are recorded separately (I think) so will address those over there.

**Comment by netniV** [comment]
@cigamit This should now be resolved in my QA patch, once its installed, only selected templates should get installed.  Also, made the command line conversion requirement a bit more prominent so that it didn't get lost at the end of the table listing.
