### ISSUE TITLE
Data Source Profile RRAs: Aggregation Level and Default Timespan for a Decade long graph

### ISSUE THREAD

**Issue by jayslovak** [Cacti/cacti#2006]
Version 1.1.38 (Debian testing)

I have just upgraded from 0.8.8, where I had a Decade long graphs using appropriately designed RRAs. After upgrading to 1.1.38 version, I am no longer able to create such RRAs via the web frontend, because "Aggregation Level" and "Default Timespan" options are no longer a freely editable field, but a drop down (the actual values are probably calculated automagicaly). 
I was able to edit the SQL directly, and the RRAs/graphs work as before. Could you implement some flexibility how these two options are entered in the GUI? Could we have an 'advanced input' functionality for experts please? I would love to be able to specify the numbers directly.

`UPDATE data_source_profiles_rra SET timespan = 315576000 where id = 9;`

![1](https://user-images.githubusercontent.com/10856567/46263041-338ca400-c50a-11e8-9b71-1fc158ab5963.png)
![2](https://user-images.githubusercontent.com/10856567/46263043-37b8c180-c50a-11e8-9309-b035ebed3969.png)

Thank you!

**Comment by cigamit** [comment]
By default, after you have created graphs  using a Data Source Profile we mark it read only.  For new Data Source Profiles, you can add and edit as you see fit.  I've noted the gap hear, and we will extend the array during our Beta.

**Comment by jayslovak** [comment]
I understand that once a Profile is used in a graph, it becomes RO. I have also tested my issue with a new Data Source Profile, but the screenshots are from my 'production' one.

How would 'extending the array' look like? Will you just add more entries to Aggregation level (say 1 week) and Default Timespan (10 years), or will it be more flexible?

Thank you for considering this issue and I am looking forward to the fix.

**Comment by cigamit** [comment]
This is resolved in 1.2.

**Comment by jayslovak** [comment]
Could we also add an option for weekly aggregation? Perhaps that wasn't clear from issue description. Currently the maximum is Daily; otherwise the RRD files get absurdly big.

![3](https://user-images.githubusercontent.com/10856567/46277712-4207a980-c564-11e8-9754-2901a7d32afe.png)

Thanks

**Comment by jayslovak** [comment]
Thank you again.
