### ISSUE TITLE
For kernel 3.2+, "Linux - Memory - Free" should grep for "MemAvailable:", not "MemFree:"

### ISSUE THREAD

**Issue by Kadigan** [Cacti/cacti#2012]
`MemFree` is an unhelpful gauge since it doesn't reflect memory that's allocated but not being actively used (such as buffers and cache, which are _generally_ available immediately upon request, but are nevertheless not considered strictly "free").

`MemAvailable` is the statistic you'd be interested in, because that's the memory that is available for any program you might want to launch w/o the immediate need to swap for it. In this context `MemFree` is not very helpful in determining the available resources on the system, and [here's a great StackOverflow explanation on why](https://stackoverflow.com/questions/1407643/how-is-the-linux-calculating-memfree#1407673), but it basically boils down to:

> In fact, `MemFree` is generally controlled to be only 5-10% of total physical RAM, with any extra free RAM being co-opted into cache as time goes on. As such, `MemFree` alone is a very incomplete view of the overall memory situation.

[Here is a more in-depth explanation of the `MemAvailable` value (git.kernel.org)](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=34e431b0ae398fc54ea69ff85ec700722c9da773), and the relevant excerpt:

```
+MemAvailable: An estimate of how much memory is available for starting new
+              applications, without swapping. Calculated from MemFree,
+              SReclaimable, the size of the file LRU lists, and the low
+              watermarks in each zone.
+              The estimate takes into account that the system needs some
+              page cache to function well, and that not all reclaimable
+              slab will be reclaimable, due to items being in use. The
+              impact of those factors will vary from system to system.
```

**Comment by netniV** [comment]
I can see the sound logic there.  Are you able to make the change into a pull request?

**Comment by Kadigan** [comment]
I have no idea where the changes need to be made, so I'll look into it when I get home.

**Comment by ronytomen** [comment]
The change should be selective.

As in if MemAvailable doesn't exist fallback to the old way.

**Comment by netniV** [comment]
In that case, you would need a common name and the script would need to work which of the two to use.  the other thing, if you update a system so that becomes available (not sure if it could) then the data would suddenly skew.

**Comment by cigamit** [comment]
What the utilities page does is as follows:

1) look for the following files, in order.  The first one it finds, it opens and parses, and splays out whatever it finds: /proc/meminfo, /linux/proc/meminfo, /compat/linux/proc/meminfo, /usr/compat/linux/proc/meminfo
2) If it does not find any of these files, it runs the free command in /usr/bin, then it get's more specific.

@Kadigan, in your case, which is the browser going after?

**Comment by cigamit** [comment]
Okay, resolved this one.

**Comment by netniV** [comment]
Is there a separate commit for this as the changes I saw did not appear to affect things?
