### ISSUE TITLE
Cacti 1.1.38 reporting tree preview not showing and empty mail received

### ISSUE THREAD

**Issue by aminelami** [Cacti/cacti#2016]
Hello,
I've just installed the latest version of Cacti 1.1.38. I'm trying to schedule a new report containing all the graphs from a tree, however the tree grahs are not shown in the preview section, and I receive an empty mail. Could someone help please?
PS: the problem is only for tree type but not with graph type.
sorry about my english

**Comment by cigamit** [comment]
Please update to the develop version.   We hope to have the beta1 of Cacti 1.2 released today.  As such, I'm going to close this one.

**Comment by aminelami** [comment]
I tryed to upgrade but it's already up to date. it's a fresh installation of Cacti 1.1.38.

[root@localhost cli]# php -q upgrade_database.php
Your Cacti is already up to date.

**Comment by aminelami** [comment]
![image](https://user-images.githubusercontent.com/43894743/46575641-58c15c80-c9b9-11e8-884e-5edccecce5dc.png)
