### ISSUE TITLE
Upgrade script error

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#202]
Ok so in this script there is a querry:
ALTER TABLE `plugin_aggregate_graphs_graph_item` ADD `graph_type_id` tinyint(3) NOT NULL default CURRENT_TIMESTAMP AFTER t_graph_type_id", 141^C) = 141

You cannot use tinyint(3) and DEFAULT CURRENT_TIMESTAMP() because this field is to small to carry on that data. The 'timestamp' type would be suitable for that.

This querry loops the whole upgrade script.

**Comment by cigamit** [comment]
Can you check as to how this happened.  I see no where in the code where this could happen.

**Comment by cigamit** [comment]
Maybe your lib/database.php is out of date?

**Comment by interduo** [comment]
I did every try:
git pull -a 

Did You find the mistake?
