### ISSUE TITLE
Installer - Directory Permissions

### ISSUE THREAD

**Issue by ronytomen** [Cacti/cacti#2023]
While upgrading to the latest `develop` branch I have some concerns about the **_Ensure Host Process Has Access_** section of the **_Directory Permission Checks_**.

**Concerns:**
- Has no checks on Windows (I'm ok with this)
- It assumes in the example that Apache is the web server and more importantly the user and group are as well.  Different distros do widely different things.  Centos/RHEL rename `apache` to `httpd`, Gentoo calls it `apache2`, Ubuntu calls it `apache`, etc...  And not to mention the different usernames associated with them as well.
- The context of the **_Ensure Host Process Has Access_** was lost on me when I saw it.  Initially read implied that I need to give read and write to the "Host Process".  I think, debate welcomed, that the title should be **_Ensure web server has permissions_**.   And say with the example something like "If you are running the Apache web server and the server is running as the user apache you can use the following command to remedy the issue, otherwise adjust for your web server and web server user." **AND** This block is moved at the end of the affected sections (Permanent and Temporary), yes it could be duplicated.
- The **NOTE** should be removed because the installer should prompt us after package install to return the permission to the proper run-time values.

**Added Functionality**
Any directories or files that the installer insists on having write permissions to for the sake of installing files should be checked at the end of upgrade/install and ask the admin to set the permissions back.  We could even "save" what they were previously and suggest the appropriate commands and syntax.

**Comment by ronytomen** [comment]
![cacti_installer_ensure_host_process_has_access](https://user-images.githubusercontent.com/5140624/46576957-1f441d80-c9c8-11e8-925b-a7042e44a555.png)

**Comment by netniV** [comment]
![image](https://user-images.githubusercontent.com/9052188/46579595-ef6b3900-ca0c-11e8-9785-4e3c95c8a425.png)

The installer knows what user you are running as, but it is impossible to find which group should be set since a user can have many and it may well be a non-primary group that is the user.  However, in most cases, there is a group of the same name as the user.

The username itself is calculated by the `get_running_user()` function which defaults back to apache when all else fails.  Since it is an *example*, not the actual command required, that should be more than adequate for the admin to work out what they need to do.  If we could accurately work out what should be used with 100% certainty, it would simply list the commands wanted, not just a one liner.

**Comment by ronytomen** [comment]
So in reviewing the code, I realize it was looking at the running user, which is great!  :) That removes assumptions!

But....
```                /* Print help message for unix and windows if directory is not writable */
                if (($config['cacti_server_os'] == 'unix') && isset($writable)) {
                        $output .= Installer::sectionSubTitleEnd();

                        $running_user = get_running_user();

                        $sections['host_access'] = DB_STATUS_WARNING;
                        $output .= Installer::sectionSubTitle(__('Ensure Host Process Has Access'),'host_access');
                        $output .= Installer::sectionNormal(__('Make sure your webserver has read and write access to the entire folder structure.'));
                        $output .= Installer::sectionNormal(__('Example:'));
                        if ($config['cacti_server_os'] == 'win32') {
                                $output .= Installer::sectionCode(__('%s should have MODIFY permission to the above directories', $running_user));
                        } else {
                                $output .= Installer::sectionCode(sprintf('chown -R %s.%s %s/resource/', $running_user, $running_user, $config['base_path']));
                                $output .= Installer::sectionNormal(__('For SELINUX-users make sure that you have the correct permissions or set \'setenforce 0\' temporarily.'));
                        }
                } elseif (($config['cacti_server_os'] == 'win32') && isset($writable)){
                        $output .= Installer::sectionNormal(__('Check Permissions'));
                }else {
                        $output .= Installer::sectionNormal('<font color="#008000">' . __('All folders are writable') . '</font>');
                }
```
There is a logic problem related to checking for `win32`, you see it if you look. 

Back to the issue at hand, as long as we qualify the generated command as an "Example" then we are fine. 

After sleeping and thinking about this issue, I would like to see each permission section show an appropriate "Example" command when things are not correct.  The "hanging" section just seems out of place and context was clear as to if it referring to permanent or temporary permissions.

**Comment by netniV** [comment]
I think win32 wise that has always been that way... but needs something though waiting on the installer code before reviewing.

**Comment by ronytomen** [comment]
Look closer...  The inner if will never equal "win32"... :smile:

**Comment by netniV** [comment]
No it won't and I had seen that but my comment was more that I hadn't reviewed any of that until I am properly looking at a windows installation.

**Comment by netniV** [comment]
Linux:
![image](https://user-images.githubusercontent.com/9052188/46610442-adbcba00-cb02-11e8-8b5a-9462c1b2d0e8.png)

Windows:
![image](https://user-images.githubusercontent.com/9052188/46610481-c75e0180-cb02-11e8-81dc-7266ba48dceb.png)

Windows is still incomplete until I start testing cacti on Windows.

**Comment by netniV** [comment]
This has now been committed.

**Comment by cigamit** [comment]
Thanks!
