### ISSUE TITLE
Installer - Busy Indicator causes seizures... 

### ISSUE THREAD

**Issue by ronytomen** [Cacti/cacti#2024]
Simplicity is majestic:
- Blurring is evil, darkening is devilish, lightening is heavenly and nothing is divine.
- Spiny is vomit inducing, mock movement is sublime.
- Absence of progress is progress

All joking aside, it gets in the way and things like this should never get in the way.  Can we use the title bar or a simple mock progress bar (in green of course) to show processing?  We also should not show it on the installation log portion.

![screen shot 2018-10-06 at 8 19 56 pm](https://user-images.githubusercontent.com/5140624/46576961-37b43800-c9c8-11e8-9ff9-75f18c5dcc36.png)

**Comment by netniV** [comment]
Resolved in QA patch

**Comment by cigamit** [comment]
Just re-installed and still getting the cacti circling.

**Comment by netniV** [comment]
The circle was only to be suppressed during the log refresh. It’s epilepsy inducing there.

**Comment by ronytomen** [comment]
Please alter the behavior as per the issue.

**Comment by netniV** [comment]
Confused. You asked for it to be suppressed during refresh, it is.

**Comment by ronytomen** [comment]
Before that statement I expressed my idea about what it should look like.. :)

**Comment by netniV** [comment]
Can you mock it up?
