### ISSUE TITLE
Sorting one subtree unsorts another one

### ISSUE THREAD

**Issue by RussellSenior** [Cacti/cacti#2026]
cacti 1.1.38-1 on Arch Linux. I have many devices, distributed in several trees. They are supposed to be sorted alphabetically. I find some of them are not sorted. I edit the tree, drag a device, and the rest of the devices within the tree sort correctly. I save and stop editing that subtree, but find that another subtree is now out of order. Repeating for the second tree unsorts the first tree.

**Comment by cigamit** [comment]
Right click on the branch and what is the sort order set to?  Cacti will respect the branch ordering.

**Comment by cigamit** [comment]
No feedback.
