### ISSUE TITLE
Themes missing dropdown arrow from top right menu icons

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#2029]
The top right icons should have the same drop down glyph as the Graphs menu item.
![image](https://user-images.githubusercontent.com/9052188/46596286-f610b380-cad3-11e8-9e7b-a53aa530370a.png)

![image](https://user-images.githubusercontent.com/9052188/46596312-0a54b080-cad4-11e8-818b-645ec4468989.png)

**Comment by cigamit** [comment]
I would debate this.  I don't think it's necessary.  A review of many web site that provide profile and help actually do not provide drop downs like this.  I think they are pretty self explanatory as is.

**Comment by netniV** [comment]
Then we should remove it from Graphs?

**Comment by cigamit** [comment]
Graphs have a completely different function, as do the ellipsis.

**Comment by netniV** [comment]
They are still a menu.
