### ISSUE TITLE
Database activity should close session before commencing

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#2030]
Since most database work is actually perform by `db_execute_prepared()` and following a like of thought from the #2010 and #2008 issues, I think we should be closing the PHP session whilst we update the database.  This would prevent a long running database query from locking out the UI since the session would no longer remain open.

**Comment by TheWitness** [comment]
@netniV, I think this is done now.  Need some better feedback before and some interlocks though.

**Comment by TheWitness** [comment]
Going to open a separate issue related to this.
