### ISSUE TITLE
Cacti 1.2.0  (Latest) - Remote Poller PHP Errors

### ISSUE THREAD

**Issue by anarkia1976** [Cacti/cacti#2031]
I have update Main/Poller to latest release but i have these errors from cacti log file:

MAIN Server
2018/10/08 15:35:02 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php[758]:poller_replicate_check(), /poller.php[791]:CactiErrorHandler())
2018/10/08 15:35:02 - ERROR PHP WARNING: Invalid argument supplied for foreach() in file: /usr/share/cacti/poller.php on line: 791
2018/10/08 15:35:02 - CMDPHP SQL Backtrace: (/poller.php[758]:poller_replicate_check(), /poller.php[789]:db_fetch_assoc(), /lib/database.php[438]:db_fetch_assoc_prepared(), /lib/database.php[452]:db_execute_prepared())
2018/10/08 15:35:02 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'last_sync' in 'where clause'
2018/10/08 15:30:02 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php[758]:poller_replicate_check(), /poller.php[791]:CactiErrorHandler())
2018/10/08 15:30:02 - ERROR PHP WARNING: Invalid argument supplied for foreach() in file: /usr/share/cacti/poller.php on line: 791
2018/10/08 15:30:02 - CMDPHP SQL Backtrace: (/poller.php[758]:poller_replicate_check(), /poller.php[789]:db_fetch_assoc(), /lib/database.php[438]:db_fetch_assoc_prepared(), /lib/database.php[452]:db_execute_prepared())
2018/10/08 15:30:02 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'last_sync' in 'where clause'
2018/10/08 15:30:02 - SYSTEM STATS: Time:0.1625 Method:spine Processes:2 Threads:2 Hosts:0 HostsPerProcess:0 DataSources:0 RRDsProcessed:0
2018/10/08 15:29:36 - CMDPHP PHP ERROR NOTICE Backtrace: (/pollers.php[211]:pollers(), /pollers.php[770]:CactiErrorHandler())
2018/10/08 15:29:36 - ERROR PHP NOTICE: Undefined index: last_sync in file: /usr/share/cacti/pollers.php on line: 770
2018/10/08 15:27:45 - CMDPHP PHP ERROR NOTICE Backtrace: (/pollers.php[211]:pollers(), /pollers.php[770]:CactiErrorHandler())
2018/10/08 15:27:45 - ERROR PHP NOTICE: Undefined index: last_sync in file: /usr/share/cacti/pollers.php on line: 770

POLLER Server
2018/10/08 15:33:57 - CMDPHP PHP ERROR NOTICE Backtrace: (/remote_agent.php[74]:ping_device(), /remote_agent.php[282]:api_device_ping_device(), /lib/api_device.php[563]:CactiErrorHandler())
2018/10/08 15:33:57 - ERROR PHP NOTICE: Undefined index: disabled in file: /usr/share/cacti/lib/api_device.php on line: 563
2018/10/08 15:33:57 - CMDPHP PHP ERROR NOTICE Backtrace: (/remote_agent.php[74]:ping_device(), /remote_agent.php[282]:api_device_ping_device(), /lib/api_device.php[462]:CactiErrorHandler())
2018/10/08 15:33:57 - ERROR PHP NOTICE: Undefined index: disabled in file: /usr/share/cacti/lib/api_device.php on line: 462
2018/10/08 15:33:57 - CMDPHP PHP ERROR NOTICE Backtrace: (/remote_agent.php[74]:ping_device(), /remote_agent.php[282]:api_device_ping_device(), /lib/api_device.php[443]:CactiErrorHandler())
2018/10/08 15:33:57 - ERROR PHP NOTICE: Undefined index: poller_id in file: /usr/share/cacti/lib/api_device.php on line: 443
2018/10/08 15:33:57 - CMDPHP PHP ERROR NOTICE Backtrace: (/remote_agent.php[74]:ping_device(), /remote_agent.php[282]:api_device_ping_device(), /lib/api_device.php[440]:CactiErrorHandler())
2018/10/08 15:33:57 - ERROR PHP NOTICE: Undefined index: availability_method in file: /usr/share/cacti/lib/api_device.php on line: 440
2018/10/08 15:32:29 - CMDPHP PHP ERROR NOTICE Backtrace: (/remote_agent.php[74]:ping_device(), /remote_agent.php[282]:api_device_ping_device(), /lib/api_device.php[563]:CactiErrorHandler())
2018/10/08 15:32:29 - ERROR PHP NOTICE: Undefined index: disabled in file: /usr/share/cacti/lib/api_device.php on line: 563
2018/10/08 15:32:29 - CMDPHP PHP ERROR NOTICE Backtrace: (/remote_agent.php[74]:ping_device(), /remote_agent.php[282]:api_device_ping_device(), /lib/api_device.php[462]:CactiErrorHandler())
2018/10/08 15:32:29 - ERROR PHP NOTICE: Undefined index: disabled in file: /usr/share/cacti/lib/api_device.php on line: 462
2018/10/08 15:32:29 - CMDPHP PHP ERROR NOTICE Backtrace: (/remote_agent.php[74]:ping_device(), /remote_agent.php[282]:api_device_ping_device(), /lib/api_device.php[443]:CactiErrorHandler())
2018/10/08 15:32:29 - ERROR PHP NOTICE: Undefined index: poller_id in file: /usr/share/cacti/lib/api_device.php on line: 443
2018/10/08 15:32:29 - CMDPHP PHP ERROR NOTICE Backtrace: (/remote_agent.php[74]:ping_device(), /remote_agent.php[282]:api_device_ping_device(), /lib/api_device.php[440]:CactiErrorHandler())
2018/10/08 15:32:29 - ERROR PHP NOTICE: Undefined index: availability_method in file: /usr/share/cacti/lib/api_device.php on line: 440
2018/10/08 15:32:14 - CMDPHP PHP ERROR NOTICE Backtrace: (/remote_agent.php[74]:ping_device(), /remote_agent.php[282]:api_device_ping_device(), /lib/api_device.php[563]:CactiErrorHandler())
2018/10/08 15:32:14 - ERROR PHP NOTICE: Undefined index: disabled in file: /usr/share/cacti/lib/api_device.php on line: 563
2018/10/08 15:32:14 - CMDPHP PHP ERROR NOTICE Backtrace: (/remote_agent.php[74]:ping_device(), /remote_agent.php[282]:api_device_ping_device(), /lib/api_device.php[462]:CactiErrorHandler())
2018/10/08 15:32:14 - ERROR PHP NOTICE: Undefined index: disabled in file: /usr/share/cacti/lib/api_device.php on line: 462
2018/10/08 15:32:14 - CMDPHP PHP ERROR NOTICE Backtrace: (/remote_agent.php[74]:ping_device(), /remote_agent.php[282]:api_device_ping_device(), /lib/api_device.php[443]:CactiErrorHandler())
2018/10/08 15:32:14 - ERROR PHP NOTICE: Undefined index: poller_id in file: /usr/share/cacti/lib/api_device.php on line: 443
2018/10/08 15:32:14 - CMDPHP PHP ERROR NOTICE Backtrace: (/remote_agent.php[74]:ping_device(), /remote_agent.php[282]:api_device_ping_device(), /lib/api_device.php[440]:CactiErrorHandler())
2018/10/08 15:32:14 - ERROR PHP NOTICE: Undefined index: availability_method in file: /usr/share/cacti/lib/api_device.php on line: 440

Thanks a lot.

**Comment by netniV** [comment]
This is likely because you already had 1.2, you need to run the cli upgrade as per previous issues where this has been logged.

**Comment by anarkia1976** [comment]
Strange:
php -q cli/upgrade_database.php --forcever=`cat include/cacti_version`
Your Cacti is already up to date (v1.2.0 vs v1.2.0)

Are you sure?

**Comment by netniV** [comment]
You are forcing the wrong version.  1.1.38 👍

**Comment by anarkia1976** [comment]
it work, thanks a lot.
