### ISSUE TITLE
Is there a way to view max and current value of a graph in cacti report?

### ISSUE THREAD

**Issue by aminelami** [Cacti/cacti#2037]
Hello,
I'm new in cacti, and I want just to ask if there is a way to view max and current value of a graph when scheduling a report. I can see that when just viewing the graph the max, average and current values are shown, but in the report sent by my mail there is non.
Any help please?

**Comment by netniV** [comment]
This is what appears in my email when I used the basic reporting features in Cacti
![image](https://user-images.githubusercontent.com/9052188/46657244-bd420e80-cba7-11e8-9aad-b69bc8758441.png)

You may need to adjust which format is being used in the email, but as far as I am aware, you get what appears on the graph.

**Comment by netniV** [comment]
Note, there is a more advanced reporting tool called ReportIT which is 90% upgraded to 1.x standards.  I can't recall if I have finished the emailing functionality yet, but it's pretty much ready for use.

**Comment by aminelami** [comment]
![img_20181009_100148](https://user-images.githubusercontent.com/43894743/46658512-c97b9b00-cbaa-11e8-833b-78bb8067b541.jpg)
Many thanks for your prompt really!
I'm using cacti 1.1.38 which integrates already the plugin ReportIT I believe. I only get graphs similar to the attached, no details about it. I'm using inline jpeg inserted format. Shall I used another format?

**Comment by netniV** [comment]
No, the reporting that was integrated into Cacti was the Nectar reporting plugin.  ReportIT is more advanced.  There is a report format advanced option under the built in Reporting configuration, you may need to change that (it's not the image attachment format).

**Comment by aminelami** [comment]
I understand now, so with reportIT, the emailing functionality is not read for use right?

**Comment by netniV** [comment]
I honestly can't remember as it's been a week since I last look at it and with all the fixes I was doing, I haven't remembered exactly where I was up to.

**Comment by aminelami** [comment]
Okay sir, I will check and see. Many thanks for your reply!

**Comment by aminelami** [comment]
The emailing functionality is included but not working yet in reportIT. Could you please tell me which format should I use to obtain the same graph as yours using the basic reporting feature?

**Comment by netniV** [comment]
Now that is a good question and I can't remember, I just recall overriding it (probably with cacti-standard.format as that seems to ring a bell).  I will be working on the ReportIT emailing this week.

**Comment by aminelami** [comment]
Many thanks sir, looking forward to the upcoming repotIT.

**Comment by cigamit** [comment]
I'm going to close this one.
