### ISSUE TITLE
When editing a tree, disabled items are not disabled at first

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#2038]
# First load:

![image](https://user-images.githubusercontent.com/9052188/46658417-9802cf80-cbaa-11e8-9032-c92f52035ec8.png)

# After clicking sort type:

![image](https://user-images.githubusercontent.com/9052188/46658397-8de0d100-cbaa-11e8-95ba-de8499a9202a.png)

**Comment by cigamit** [comment]
Resolved.
