### ISSUE TITLE
[1.2.0] Need to ensure all packages are re-packaged and in sync

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#2043]
Need to ensure that all packages included with release are re-packaged and any with files that are normally included in the scripts/resource directory are using the same sources.  Last time I checked, there was a difference between the git sources and what was updated after package installation.

**Comment by cigamit** [comment]
Yup, the re-packaging of 1.2 version captured this, though it'll happen again.  As we get closer to finally releasing the packaging plugin, we will need to call this out.  Need to update the Wiki too.

**Comment by cigamit** [comment]
This is resolved now.  New interfaces.xml in place.
