### ISSUE TITLE
Add ability to select the Index Type at Device and Device Template levels

### ISSUE THREAD

**Issue by pautiina** [Cacti/cacti#2044]
When creating network index graphs, need to add an index type selection for the data source. 
For example: `ifDescr` `ifName` `ifIndex` etc.

And also it is necessary to make it so that the index type of the data source does not get lost when the device is rebooted or on re-query :) (Now it's bug. Related on this https://github.com/Cacti/cacti/issues/454)

**Comment by cigamit** [comment]
We should allow the user to force type type at the Device level, and set a preset at the Device Template level.  We will enhance this post the 1.2 release.

**Comment by cigamit** [comment]
We had a discussion on this as a team and believe that by simply making ifName the default, that this issue will resolve itself.  We simply picked the wrong default.  So, I'm closing this now.

**Comment by cigamit** [comment]
We changed the default is issue #2064
