### ISSUE TITLE
[IE11] install.js - Expected ')'

### ISSUE THREAD

**Issue by BSOD2600** [Cacti/cacti#2045]
On Windows 2012R2 with IE11, the installer fails on the first screen with:

SCRIPT1006: Expected ')'
File: install.js, Line: 205, Column: 36

This does NOT occur with Chrome 69

![image](https://user-images.githubusercontent.com/5741811/46779350-3dfa2b00-cccc-11e8-8f55-8fbb3ec95733.png)

**Comment by netniV** [comment]
When I used Safari, Chrome or Firefox, I do not get this issue.  I will test with IE shortly.

**Comment by netniV** [comment]
Confirmed that it is only IE that bugs out.  I will attempt to diagnose why.

**Comment by cigamit** [comment]
No IE11 in my household ;)

**Comment by netniV** [comment]
Reason is actually quite simple.  IE11 sucks.  However, to work around that suckage, any function with a parameter default has to be changed from:

```js
function toggleHeader(key, initial = null) {
```

to 

```js
function toggleHeader(key, initial) {
	if (typeof initial == 'undefined') {
		initial = null;
	}
```

**Comment by netniV** [comment]
This has now been committed to the development code.
