### ISSUE TITLE
[Win32] Critical Binary Locations and Versions - path issues

### ISSUE THREAD

**Issue by BSOD2600** [Cacti/cacti#2046]
On the Critical Binary Locations and Versions page, there are several issues with the defaults for Windows

1) sendmail is defaulting to the rrdtool path for some reason, when the code appears to show it should be set to blank. 
2) Spine config path - no path set, yet the green checkbox is present.  How can that be valid?  It should default to the same path as spine.exe, plus either looking for spine.conf.dist and/or spine.conf
3) Minor UI issue with the width of the Poller STandard error log path (Chrome 69).  Make slightly wider?

![image](https://user-images.githubusercontent.com/5741811/46780260-8ae00080-ccd0-11e8-89df-89d24267e0b0.png)

**Comment by cigamit** [comment]
I think we should remove the sendmail path from settings on Windows installs as well as the dropdown in the Mail/DNS settings page.  @BSOD2600 can you confirm this makes sense?

**Comment by cigamit** [comment]
@BSOD2600, what should the default spine paths be on Windows?

**Comment by netniV** [comment]
The spine configuration path has never had a default setting applied to it. This is true regardless of the OS.

**Comment by netniV** [comment]
On the GUI width front, that will always become an issue dependant on where the default installations are pointing at.  One thing we could do is to ensure the text is selected upon entry with the cursor at the end so you can see the end clearly.  This would also allow you to simply overtype to enter a new value or hit delete to empty it.

I had thought that functionality had been put in.

**Comment by BSOD2600** [comment]
Agreed, does not make sense to have sendmail present on Windows. 
Default path for Spine on Windows has been %SystemDrive%\Spine\.  Makes sense for the config to reside there too.

**Comment by netniV** [comment]
Agree, makes sense, just clarifying that neither windows nor Linux have specified a default location for a configuration file as far as I am aware.

**Comment by netniV** [comment]
Sendmail is now removed from the path list and mail settings under windows.
