### ISSUE TITLE
[1.2.0] Theme changes not working

### ISSUE THREAD

**Issue by BSOD2600** [Cacti/cacti#2047]
During the installation wizard, the dark theme was used. See screenshot in https://github.com/Cacti/cacti/issues/2046

Once cacti was successfully set up, the Theme showed it was Dark, but clearly it was not:
![image](https://user-images.githubusercontent.com/5741811/46781114-d98f9980-ccd4-11e8-84f9-18737421f6ba.png)

Changed the theme to anything else, clicked save. Now the theme IS dark:
![image](https://user-images.githubusercontent.com/5741811/46781126-edd39680-ccd4-11e8-865f-9b425e5ac6bf.png)

however, now the theme is stuck on Dark and cannot be changed to anything else.  Clearly this is not 
'sunrise'
No errors logged in Chrome console, php error log, or cacti.log. 
![image](https://user-images.githubusercontent.com/5741811/46781158-24a9ac80-ccd5-11e8-86e9-0eb1e6c2d7d0.png)

**Comment by netniV** [comment]
This is likely connected to the 0.8.8 fixes that @cigamit introduced and I tweaked recently as the settings_user table isn’t present for them when upgrading. However, since I am assuming yours would be fresh... that doesn’t compute. Shall have to test it tonight. If you get a chance, try adding `log_install` with a value of 2. That should give some basic telemetry on what it believes it’s doing, into `log/install-*`

**Comment by cigamit** [comment]
@netniV, I think this issue has been around for a while.  When the user selects a theme, are we setting it at both the user and the global level.  I think we may be doing one and not the other.  I've noticed it too.  At install time, I switch to dark, then after the install is done, I am in Modern again.

**Comment by netniV** [comment]
This is now in the main development code, please check and close if issue is resolved.

**Comment by netniV** [comment]
For reference, we are now setting the system default, the install option, the user setting, and the session variable... can't do much more than that ;-)

**Comment by netniV** [comment]
If a user other than the one performing the installation has a different theme selected, they will retain their theme selection.

**Comment by cigamit** [comment]
@BSOD2600, closing on your behalf.  You should validate the lib/rrd.php issue.
