### ISSUE TITLE
[1.2.0] failed to open stream - \lib\rrd.php on line 3300

### ISSUE THREAD

**Issue by BSOD2600** [Cacti/cacti#2049]
[10-Oct-2018 22:23:07 America/Los_Angeles] PHP Warning:  file_put_contents(/tmp/rrd): failed to open stream: No such file or directory in C:\Apache24\htdocs\cacti\lib\rrd.php on line 3300

Create a new graph for a device
View the new graph. Picture shows 'unknown rrdtool error'
graph debug shows empty "rrdtool says"
The rrd file referenced in the debugging output does not exist yet (poller hasnt ran).

After the poller runs and creates the file, this error does not occur.

**Comment by netniV** [comment]
I have removed some debug code that was left in.  

This is now in the main development code, please check and close if issue is resolved.

**Comment by cigamit** [comment]
Thanks for your help @BSOD2600!
