### ISSUE TITLE
[1.2.0 Beta 1] Search in Graphs with error

### ISSUE THREAD

**Issue by DavidLiedke** [Cacti/cacti#2050]
I had this error with the stable (1.1.38) and beta (1.2.0 beta 1) release.

Console --> Management --> Graphs

If i go to the second result page i get the following error:

![2018-10-11_09-13-27](https://user-images.githubusercontent.com/25581728/46786907-96fea900-cd36-11e8-8e46-30401d161aea.gif)

1.2.0 beta 1:
![firefox_2018-10-11_09-22-59](https://user-images.githubusercontent.com/25581728/46787196-476cad00-cd37-11e8-973d-3bf82ee953ba.png)

1.1.38:
![firefox_2018-10-11_09-23-38](https://user-images.githubusercontent.com/25581728/46787228-5ce1d700-cd37-11e8-8f58-bfc1bd8388a5.png)

**Comment by cigamit** [comment]
Okay, resolved on both the Graphs and the Data Sources pages.

**Comment by netniV** [comment]
I think it is also the fact that the message didn't show the original message, only the unknown one.  Does it now show the correct message when using a bad regex?
