### ISSUE TITLE
[1.2.0] - after change index type and Reload Query - data source lost data

### ISSUE THREAD

**Issue by pautiina** [Cacti/cacti#2051]
Step for reproduce:
1. Create graphs for interface statisitcs
When creating graphs, the index type is `ifDescr`.
2. Go to data source and edit some interface, for example:
 `SWITCH - Traffic - 1/28 -- CORE-SWITCH-2`
change index type from `ifDescr ` -> `ifName `
change index value from `D-Link DGS-1210-28XS/ME Rev.B1/7.02.B051 Port 28` -> `1/28`
3. After this change all good.
4. Go to device and `reload query`.
after this data source not have valid data 

related on this https://github.com/Cacti/cacti/issues/2044

**Comment by cigamit** [comment]
Thanks for all your help yesterday.  This issue has been around for a long time, and now it just works.

**Comment by netniV** [comment]
1.2.1? Or 1.2.0 Beta 2?

**Comment by pautiina** [comment]
>1.2.1? Or 1.2.0 Beta 2?

I think 1.2.1

**Comment by netniV** [comment]
1.2.0 isn't an official release yet though ... it's only in beta 👍
