### ISSUE TITLE
[1.2.0] Case-Insensitive define causes RRDProxy to fail

### ISSUE THREAD

**Issue by pornmailbox** [Cacti/cacti#2054]
cacti.log shows this 2 errors:

2018/10/11  12:48:03 - CMDPHP PHP ERROR Backtrace:   (/poller_reports.php[135]:reports_log(), /lib/reports.php[272]:define(),  CactiErrorHandler())
--
2018/10/11 12:48:03 - ERROR PHP DEPRECATED: define(): Declaration of  case-insensitive constants is deprecated in file:  /var/www/localhost/htdocs/cacti/lib/reports.php  on line: 272

rrdproxy in debug mode indicates:
....
rrdp#
[ACL] Default connection request #473[IP: ::ffff:192.168.1.61] granted.
rrdp#
[IPC] IPC connection #473 closed by child process
....

If I delete graphs, cacti recreate empty one. After that *.rrd files has no updates (modification time is the same as creation time). Real-time graphs works fine.

no other errors in log.

**Comment by pornmailbox** [comment]
**OS & Version** - Linux cacti-server 4.15.18-7-pve #1 SMP PVE 4.15.18-26
**PHP Version** - PHP 7.3.0RC3 (cli) (built: Oct 11 2018 14:00:08) ( ZTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.0-dev, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.0RC3, Copyright (c) 1999-2018, by Zend Technologies
Same problem with PHP 7.2.10 on another cacti server.
**Cacti Version** - 1.2.0-beta1
**Plugin name/version** - no.
**Backtrace** - few minutes of cacti.log in development mode. 
[cacti.log](https://github.com/Cacti/cacti/files/2469170/cacti.log)
Nginx cacti_error.log - 
[cacti-error.log](https://github.com/Cacti/cacti/files/2469189/cacti-error.log)
Nginx itself has no errors in server's log.
php-fpm shows only notice about pm.max_children setting: 
[11-Oct-2018 14:56:09] WARNING: [pool www] server reached pm.max_children setting (5), consider raising it

**Comment by netniV** [comment]
You didn't include the OS but that's fine.  If you grab the latest development source, it should now be resolved.

**Comment by netniV** [comment]
Thanks for your system info.  You confirmed something I had suspected. You are running 7.3 which hasn't been tested against Cacti yet.  However, do let us know if you find anything else.

https://wiki.php.net/rfc/case_insensitive_constant_deprecation

**Comment by pornmailbox** [comment]
Ok. but the graps still empty with latest commit.

**Comment by pornmailbox** [comment]
php-fpm[1206841]: segfault at 7f4357e00000 ip 000055d80acf8f2a sp 00007ffccd65cd10 error 4 in php-fpm[55d80aa15000+e67000]
It seems to me that something gone starnge in lxc ...
I have to investigate php before.
