### ISSUE TITLE
[1.2.0 Beta 1] When doing the first install, warnings are logged

### ISSUE THREAD

**Issue by cigamit** [Cacti/cacti#2057]
There are two warnings logged on a fresh install that are spurious.

`WARNING: Attempt to set user settings 'selected_theme', with no user id:`
`WARNING: Attempt to set user settings 'user_language', with no user id:`

**Comment by netniV** [comment]
That should not happen as you should always be logged in to run the installer.  The only time I can think this may happen is at the command line.

**Comment by cigamit** [comment]
That explains it then, I have an active browser session (and good cookie) open, then I wipe everything out and simply refresh the browser.  So no login since I already have a valid session cookie.  Do we want to address this, or just tell the operator not to test around corners?

**Comment by netniV** [comment]
I think it may also affect the background installer.  I had not considered that the installer is not user-based, so I will make a check for an active user before applying a user setting.

**Comment by netniV** [comment]
This should now be resolved, but needs further testing to ensure install is clean.

**Comment by cigamit** [comment]
This is clean now.  Thanks!
