### ISSUE TITLE
undefined remote_paths for Remote pollers 

### ISSUE THREAD

**Issue by Carlimeunier** [Cacti/cacti#206]
Hello,
I get this error when I install a new remote poller  : 
ERROR PHP NOTICE: Undefined variable: remote_paths in file: /data/www/cacti/install/index.php on line: 945

Thanks

**Comment by cigamit** [comment]
Resolved in commit below.  Thanks!

https://github.com/Cacti/cacti/commit/a8c560966a0c98dda54325ebe5fd8b314fff6372
