### ISSUE TITLE
Time Graph View can't be manually (F5) refreshed

### ISSUE THREAD

**Issue by RadekHvizdos** [Cacti/cacti#2066]
In legacy 0.8 Cacti, I am able to manually refresh the graph by pressing F5. After upgrading to Version 1.1.38, pressing F5 causes my browser to navigate back to the previous page.

I am aware that in 1.2, the Time Graph View refreshes automatically, I am not sure if this means that F5 will work again. 

Old vs New cacti url:
![new](https://user-images.githubusercontent.com/10856567/46877336-e6310080-ce40-11e8-879f-c38e6ede7995.png)

Will I be able to use F5 in 1.2? If not, could you either add graph id parameter to the url, or implement a cookie for the browser to remember the exact url?

Thank you

**Comment by cigamit** [comment]
That would not be the correct way to resolve that issue.  We will have to think about it.  Time View from the Graph Tree might be more work.

**Comment by TheWitness** [comment]
Instead of a F5, we might be able to easy add a refresh button of some sort.  F5 does not work from certain page types and I think it's a low priority.

**Comment by TheWitness** [comment]
I'm going to close this one as complete Cacti has become much more reliable in the 1.2.x++ series.
