### ISSUE TITLE
[1.2.0 Beta 1] Error on install for no gmp, but latest version installed

### ISSUE THREAD

**Issue by KnoAll** [Cacti/cacti#2067]
Running Centos7 coming from Cacti v1.1.37. 
CentOS Linux release 7.4.1708 (Core)

Install I get an error that gmp is required but not installed. when i yum install I get:
Package 1:gmp-6.0.0-15.el7.x86_64 already installed and latest version
Nothing to do.

Any suggestions?

**Comment by KnoAll** [comment]
Bonehead move. Installed php-gmp and all is well.

**Comment by netniV** [comment]
Sometimes, you can have it installed but not enabled too.
