### ISSUE TITLE
meminfo on Freebsd

### ISSUE THREAD

**Issue by Carlimeunier** [Cacti/cacti#207]
Hello,

I have this error on freebsd : 

ERROR PHP NOTICE: Undefined variable: memInfo in file: /data/www/cacti/lib/utility.php on line: 987 

Is it a way to get Freebsd meminfo from cacti?

Thanks

**Comment by duantianyu** [comment]
Just a NOTICE, You can ignore it.

**Comment by cigamit** [comment]
Can you please mount the procfs in /etc/fstab and then see if this problem goes away?  FreeBSD does not mount the /proc file system by default.

**Comment by cigamit** [comment]
It turns out that FreeBSD will support /linux/proc/meminfo or /compat/linux/proc/meminfo.  If either of these two files exist, we will now try that.  Otherwise, it'll look for the free command in /usr/bin.

Just committed that.  Let me know if it works, and what method worked if so.

**Comment by cigamit** [comment]
Any updates guys?

**Comment by Carlimeunier** [comment]
Since 10.3 and later, Freebsd support /compat/linux/proc/meminfo.

Here is what i have on my Freebsd 10.3. But i can't mount that on freebsd 10.2
` cat /usr/compat/linux/proc/meminfo
             total:    used:    free:  shared: buffers:  cached:
Mem:  4266172416 696991744 3569180672 53526528 0 987136
Swap: 2147483648 0 2147483648
MemTotal:   4166184 kB
MemFree:    3485528 kB
MemShared:    52272 kB
Buffers:          0 kB
`

**Comment by cigamit** [comment]
Okay, so just to clarify it's /usr/compat/linux/proc/meminfo and not /compat/linux/proc/meminfo?  In the article I read there were different mount points for different versions of FreeBSD.  So, that's why I included multiple checks.  Please double confirm the path, and I'll make the change.

**Comment by cigamit** [comment]
Test again.  should be resolved now for the 10.3 for sure.  If you want to propose something for older versions of FreeBSD.  Please submit a pull request with you suggestions.
