### ISSUE TITLE
cacti-1.1.38 aggregates graph ERROR: invalid rpn expression in: ,8,*

### ISSUE THREAD

**Issue by aminelami** [Cacti/cacti#2074]
Hello,
I'm using cacti-1.1.38. At first I was able to create aggregates graphs without any problem, but after a week I'm getting the following rrd error. I'm trying to obtain the total of graph similar to data source.
Note that I faced exactelly the same problem a month ago with cacti-1.1.20 so I jumped to cacti-1.1.38 but same issue. Could this be an aggregates bug?
Please help :'(

![image](https://user-images.githubusercontent.com/43894743/46914764-1cd25c80-cfa2-11e8-9fa2-18e1ba36141c.png)

![image](https://user-images.githubusercontent.com/43894743/46914883-e1d12880-cfa3-11e8-894e-a05021690b2b.png)

**Comment by netniV** [comment]
Potentially, do you have any issues with the source graphs?

**Comment by aminelami** [comment]
No, all the source graphs are shown with no problem.

**Comment by aminelami** [comment]
Please can anybody help ?

**Comment by pautiina** [comment]
Read this issue https://github.com/Cacti/cacti/issues/599

**Comment by netniV** [comment]
You probably have the auto option ticked.  So it adds them for you.

**Comment by aminelami** [comment]
How can I remove the unecessary items please @netniV

**Comment by netniV** [comment]
Wait, I was confusing myself with ReportIT which works in a similar fashion.  Your items are being ignored if the "Skip" column is ticket.  Only those with Total are output.

**Comment by aminelami** [comment]
I didn't have the chance to test the features in 1.2, however I finally solved the problem by deleting the unneeded items from the graph template "Interface - Traffic (bits/sec)", although I didn't add any item manually, I wander how I got them?
Items with problem:
![image](https://user-images.githubusercontent.com/43894743/47284373-68f74f80-d5e7-11e8-92f9-01b5f6a2b6ef.png)

Items without problem:
![image](https://user-images.githubusercontent.com/43894743/47284396-7d3b4c80-d5e7-11e8-808c-4a16ddacea44.png)
