### ISSUE TITLE
cacti log storage directory

### ISSUE THREAD

**Issue by puraan** [Cacti/cacti#2077]
Hello! 
I have installed cacti v1.1.10 in centos 6.5. Now i want to backup by cacti server's main config files and graphs logs. But i am not getting directory for these. So please help me. I am in trouble.

**Comment by netniV** [comment]
Cacti stores information in several places:

1. &lt;cacti&gt;/log/
2. &lt;cacti&gt;/include/config.php
3. MySQL db defined in &lt;cacti&gt;/include/config.php
4. If you are using spine, it has it's own configuration file.
