### ISSUE TITLE
Cacti 1.2.0 - poller_replicate_check in poller.php is spawning multiple processes

### ISSUE THREAD

**Issue by thurban** [Cacti/cacti#2078]
The function is spawning a new poller_replicate.php process at each runtime, causing mutliple full sync replications to start.  This only happens with slow WAN links (i.e. Germany -> Korea) where the sync takes longer then the polling runtime permits

```
cacti     1885     1  0 13:05 ?        00:00:00 /usr/bin/php -q /var/www/html/cacti-1.1.35/cli/poller_replicate.php --poller=69
cacti     4279     1  0 13:06 ?        00:00:00 /usr/bin/php -q /var/www/html/cacti-1.1.35/cli/poller_replicate.php --poller=69
cacti     6212     1  0 13:07 ?        00:00:00 /usr/bin/php -q /var/www/html/cacti-1.1.35/cli/poller_replicate.php --poller=69
cacti     8184     1  0 13:08 ?        00:00:00 /usr/bin/php -q /var/www/html/cacti-1.1.35/cli/poller_replicate.php --poller=69
cacti    10232     1  0 13:09 ?        00:00:00 /usr/bin/php -q /var/www/html/cacti-1.1.35/cli/poller_replicate.php --poller=69
cacti    12360     1  0 13:10 ?        00:00:00 /usr/bin/php -q /var/www/html/cacti-1.1.35/cli/poller_replicate.php --poller=69
cacti    14442     1  0 13:11 ?        00:00:00 /usr/bin/php -q /var/www/html/cacti-1.1.35/cli/poller_replicate.php --poller=69
cacti    16474     1  0 13:12 ?        00:00:00 /usr/bin/php -q /var/www/html/cacti-1.1.35/cli/poller_replicate.php --poller=69
cacti    30220     1  0 13:03 ?        00:00:00 /usr/bin/php -q /var/www/html/cacti-1.1.35/cli/poller_replicate.php --poller=69
cacti    32208     1  0 13:04 ?        00:00:00 /usr/bin/php -q /var/www/html/cacti-1.1.35/cli/poller_replicate.php --poller=69
```
Some sort of check should be implemented to see if another poller_replicate.php is already running.

Btw, poller_sync_interval is not yet implemented in the Cacti settings dialog.

**Comment by netniV** [comment]
I have now added the missing setting option, though the values may get adjusted upon review. I threw in a whole bunch as I wasn't sure what people may actually want.  Some of the lower settings may get removed since we would most likely not recommend syncing that often without a reason.

**Comment by netniV** [comment]
![image](https://user-images.githubusercontent.com/9052188/46956799-1d482180-d08e-11e8-8ba1-4c2d61610f97.png)

**Comment by netniV** [comment]
I was thinking whilst looking at this that there should be an override at a poller level, similar to what we have done with the collection/thread settings.  That would require a DB change though and we are trying to keep those to a minimum.  The good news is, that I have already had to modify the `pollers` table for SSL settings which would cause a big problem if left off.  That means it may be allowed since it's the same table being modified.

**Comment by netniV** [comment]
This is one I was pass back as feed to the team.

**Comment by netniV** [comment]
I do believe that there are some changes coming in the upcoming beta 2 that will make a full sync become less necessary.  So, it should only be run with less frequency once that work has been completed.

**Comment by thurban** [comment]
Great. I am more than happy to go for beta2 when it's finished.

The sync itself is a great feature itself but it also causes issues if you have different versions running (by source install on master vs. Debian based apt install on remote pollers) and also don't want to have everything synced (i.e plugins).

Looking forward to 1.2 beta2 !

**Comment by netniV** [comment]
Code wise, everything should be in sync or it could cause issues with compatibility/database structures.  I'm adding the setting to the pollers table, should be ready soon.

**Comment by netniV** [comment]
I've added some code for the sync timing to the Data Collector edit screen.  I have also corrected the status display on the listing portion of the same code file as it would Down when the server may actually be up, but no heartbeat has been detected.  So, I've labelled a new status of 'Heartbeat' for that situation.

Additionally, I corrected a couple of minor issues that I found with variables not being set correctly during install relating the remote pollers.  I think that more work needs to be done to prevent respawning of the poller_replicate so the original issue has not yet been resolved but we are getting closer.

**Comment by netniV** [comment]
![image](https://user-images.githubusercontent.com/9052188/46976018-27831380-d0c0-11e8-8047-85da51c46f6f.png)

**Comment by netniV** [comment]
The above commit also corrected a daylights saving issue where my pollers said they were down even though I'd received an update seconds earlier.  The problem was comparing a UTC time with a BST time (+1 hour) which resulted in a down value too.

**Comment by cigamit** [comment]
Yes, the Beta2 will includes a whole new method to sync graph, data source and device operations.  If the remote database is reachable, the sync will happen on the fly.  Then, the only time you will need a full sync is for things like the authentication database for offline operation.  Additionally, when a remote data collector is disconnected from the main server, after it comes back online, the first thing it will do is send it's updated re-index information and device status back to the main collector to reduce the likelihood of getting bad data for data collection.  It will do this in bulk as it does today.

**Comment by cigamit** [comment]
I'm reducing the number of dropdowns.  The minimum re-sync will not be 30 minutes, though I would suggest once a day or manual after Beta 2.

**Comment by cigamit** [comment]
Marking resolved.
