### ISSUE TITLE
[Cacti 1.2.0 Beta1 - Last] - Input Validation

### ISSUE THREAD

**Issue by anarkia1976** [Cacti/cacti#2079]
Hi,

i have a lot of these messagges:

2018/10/15  15:22:06 - CMDPHP Input Validation Not Performed for 'node' Backtrace:   (/graph_view.php[218]:top_graph_header(),  /lib/functions.php[3092]:include(),  /include/top_graph_header.php[28]:draw_navigation_text(),  /lib/functions.php[2346]:get_request_var(),  /lib/html_utility.php[334]:html_log_input_error(),  /lib/html_validate.php[44]:cacti_debug_backtrace())
2018/10/15 15:00:41 - CMDPHP Input Validation Not Performed for 'id'  Backtrace:  (/user_admin.php[46]:form_save(),  /user_admin.php[611]:get_request_var(),  /lib/html_utility.php[334]:html_log_input_error(),  /lib/html_validate.php[44]:cacti_debug_backtrace())
2018/10/15  09:15:35 - CMDPHP Input Validation Not Performed for 'graph_nolegend'  Backtrace:  (/graph_realtime.php[66]:load_current_session_value(),  /lib/html_utility.php[839]:get_request_var(),  /lib/html_utility.php[334]:html_log_input_error(),  /lib/html_validate.php[44]:cacti_debug_backtrace())
2018/10/15 09:15:35 - CMDPHP Input Validation Not Performed for  'size' Backtrace:   (/graph_realtime.php[65]:load_current_session_value(),  /lib/html_utility.php[839]:get_request_var(),  /lib/html_utility.php[334]:html_log_input_error(),  /lib/html_validate.php[44]:cacti_debug_backtrace())
2018/10/15 09:15:35 - CMDPHP Input Validation Not Performed for  'graph_start' Backtrace:   (/graph_realtime.php[64]:load_current_session_value(),  /lib/html_utility.php[839]:get_request_var(),  /lib/html_utility.php[334]:html_log_input_error(),  /lib/html_validate.php[44]:cacti_debug_backtrace())
2018/10/15 09:15:35 - CMDPHP Input Validation Not Performed for  'ds_step' Backtrace:   (/graph_realtime.php[63]:load_current_session_value(),  /lib/html_utility.php[839]:get_request_var(),  /lib/html_utility.php[334]:html_log_input_error(),  /lib/html_validate.php[44]:cacti_debug_backtrace())
2018/10/15 09:15:30 - CMDPHP Input Validation Not Performed for  'graph_nolegend' Backtrace:   (/graph_realtime.php[66]:load_current_session_value(),  /lib/html_utility.php[839]:get_request_var(),  /lib/html_utility.php[334]:html_log_input_error(),  /lib/html_validate.php[44]:cacti_debug_backtrace())

The last update is super awesome. thanks a  lot.

**Comment by netniV** [comment]
This would mean that various options are not being validated by the system before they are used.  You are likely seeing these because you have certain debug options activated as they are normally suppressed except for developer viewing.

**Comment by cigamit** [comment]
This is a good find.  We want to ensure that all input variables are properly checked as a security measure.  These warnings were designed for just this case.  Thanks for testing!

**Comment by cigamit** [comment]
Resolved.
