### ISSUE TITLE
Classic theme, "execute action" butten problem

### ISSUE THREAD

**Issue by dabeani** [Cacti/cacti#208]
hi,

on each page, if you have the possibility to check more lines (like in the device tab, or sites, trees,...) you can select the lines, and you can choose some "action" from the dropdown, but you cannot press the "go" button. its also not working if you select only one line - or more lines - no chance to 'enable' this button.

i tried to debug with firefox and firebug this actions, but if i click on the dropdown - to change the action - i did not see any console output - and the "go" button is still disabled.

BR
bernhard

**Comment by dabeani** [comment]
one more,...

Configuration / External Links -> because of that issue what i explained, i can not delete some entries - there is only the possibility to disable if you click on each line the edit symbol.

**Comment by cigamit** [comment]
Resolved, thanks!
