### ISSUE TITLE
[1.2.0] Beta 1 (8766f24 ) Notification list issue

### ISSUE THREAD

**Issue by jackouille-ch** [Cacti/cacti#2081]
This morning an ISP issue happens for some of my customers and I receive the notifications about these outages.
While reviewing messages I saw that for some devices, the Global List is defined BUT another user has received the notifications for devices that doesn't belongs to him.
For example:
dev1 -> GL
dev2->User1
User1 has rceived notification from dev1
GL contains only my mailaddress but User1 contains user mail + Mine

**Comment by cigamit** [comment]
This presently belongs in the thold bug area.  We are contemplating bringing Notification Lists to the core of Cacti, but right now, there belong in the thold bug area.
