### ISSUE TITLE
[1.2.0] Beta 1 (8766f24 ) Still having issue in Config/Parameters - Mail/Reporting/DNS

### ISSUE THREAD

**Issue by jackouille-ch** [Cacti/cacti#2082]
When I simply clic on tab menus I face this issue:
![mrdns](https://user-images.githubusercontent.com/35721406/47000515-bc215c00-d128-11e8-92b3-ac1a72804640.gif)

**Comment by cigamit** [comment]
Open you debug console.  You will find the column that is causing the issues in the console.  Can you post what you find there?

**Comment by pautiina** [comment]
I think need open browser console

**Comment by cigamit** [comment]
Yes, it has nothing to do with Cacti log.  It's all about the browsers debug console.  You can open in Firefox using F12, then you will find a Console tab.  The offending field will be logged.

**Comment by jackouille-ch** [comment]
Yes thanks, here is the error:
Index:-settings_smtp_password_confirm-:Submit:, Orig:Password@cacti

**Comment by cigamit** [comment]
Okay, yea, I'm found another way to fix this.  Just about to commit.  This is due to stupid browser doing autocomplete of your stored login id and password from your login.

**Comment by cigamit** [comment]
Just update lib/html_form.php or wait for Beta 2.
