### ISSUE TITLE
[1.2.0 Beta 1] Real-Time Graphs error, non-numeric Value

### ISSUE THREAD

**Issue by Cramin** [Cacti/cacti#2084]
Hi.
I have this error in log, and RealTime graphs not working.

```
2018/10/16 17:38:24 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_realtime.php[138]:CactiErrorHandler())
--
2018/10/16 17:38:24 - ERROR PHP WARNING: A non-numeric value encountered in file: /var/www/html/cacti/graph_realtime.php on line: 138
2018/10/16 17:38:24 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_realtime.php[137]:CactiErrorHandler())
2018/10/16 17:38:24 - ERROR PHP WARNING: A non-numeric value encountered in file: /var/www/html/cacti/graph_realtime.php on line: 137

```

**Comment by netniV** [comment]
Can you provide the following information:

- OS & Version
- PHP Version
- Cacti Version
- If applicable:
   - Backtrace
   - Plugin name/version

Also, are there any errors in the web server log and/or cacti log?

**Comment by Cramin** [comment]
Yes.
Ubuntu 18.04
PHP 7.2.10-0ubuntu0.18.04.1, MySQL 5.7.23-0ubuntu0.18.04.1
Cacti 1.2.0 cloned today from git. Spine SPINE 1.1.38

**Comment by cigamit** [comment]
Resolved now.  Make sure you reload your realtime.js if using chrome.

**Comment by cigamit** [comment]
Should be automatic if you simply close/open the browser.
