### ISSUE TITLE
Cacti-1.1.38 outputs zero values from OID

### ISSUE THREAD

**Issue by aminelami** [Cacti/cacti#2090]
Hello helpers,

I'm running cacti-1.1.38
I believe I've followed all steps correctly to custom a graph collecting the number of red alarms on Juniper router which have the OID 1.3.6.1.4.1.2636.3.4.2.3.2.0 
I've created a data_template and graph_template using this OID.

When I run the snmpwalk I can tell, I get the correct output from the router for that value (23 in this case):

[root@localhost ~]# snmpwalk -v2c -c ccccc x.x.x.x 1.3.6.1.4.1.2636.3.4.2.3.2.0
SNMPv2-SMI::enterprises.2636.3.4.2.3.2.0 = Gauge32: 23

the same result is obtained from the router itself:
router-juniper> show snmp mib get 1.3.6.1.4.1.2636.3.4.2.3.2.0 
jnxRedAlarmCount.0 = 23

but cacti output shows always 0:
2018/10/18 14:50:01 - POLLER: Poller[Main Poller] Device[12] Device[xxx] Graphs[xxx] DS[red alarm] SNMP: v2: x.x.x.x, dsname: snmp_oid, oid: 1.3.6.1.4.1.2636.3.4.2.3.2.0, output: 0 

![image](https://user-images.githubusercontent.com/43894743/47159842-f9374b00-d2ee-11e8-87b3-999abb4e91a3.png)

Any ideas? Any help would be appreciated.

PS: with the same way I graphed the temperature with OID 1.3.6.1.4.1.2636.3.1.13.1.7.9.1.0.0 and it works perfectlly:
2018/10/18 14:50:01 - POLLER: Poller[Main Poller] Device[12] Device[xxx] Graphs[xxx] DS[test -temperature] SNMP: v2: x.x.x.x, dsname: snmp_oid, oid: 1.3.6.1.4.1.2636.3.1.13.1.7.9.1.0.0, output: 37 

Regards!

**Comment by netniV** [comment]
What does a walk of the temperature produce?

**Comment by aminelami** [comment]
Thnak you @netniV for your usual reply.

[root@localhost ~]#  snmpwalk -v2c -c ccccc x.x.x.x 1.3.6.1.4.1.2636.3.1.13.1.7.9.1.0.0
SNMPv2-SMI::enterprises.2636.3.1.13.1.7.9.1.0.0 = Gauge32: 27

**Comment by aminelami** [comment]
PHP-SNMP is installed, but I have no idea whether is enabled or not. Could you please give a hint how to disable/enable it?

![image](https://user-images.githubusercontent.com/43894743/47212528-bdf15680-d398-11e8-8912-ab4443644561.png)

**Comment by netniV** [comment]
If you are using ubuntu, you would `sudo phpdismod snmp` but it depends on your flavour of linux.

**Comment by aminelami** [comment]
I'm using centos 7, I'm not sure but I deleted the line "extension=snmp.so" from "/etc/php.d/snmp.ini" and restarted httpd.service, unfortenutally it gave the same results:

2018/10/19 11:55:03 - POLLER: Poller[Main Poller] Device[12] Device[xxx] Graphs[red-alarm-test] DS[red alarm] SNMP: v2: x.x;x;x, dsname: snmp_oid, oid: 1.3.6.1.4.1.2636.3.4.2.3.2.0, output: 0
--
2018/10/19 11:55:03 - POLLER: Poller[Main Poller] Device[12] Device[xxx] Graphs[temp ver4] DS[temperature] SNMP: v2: x.x;x;x, dsname: snmp_oid, oid: 1.3.6.1.4.1.2636.3.1.13.1.7.9.1.0.0, output: 38

**Comment by netniV** [comment]
Is it showing as installed still?  The chances are there is a separate ini for the apache service.

**Comment by aminelami** [comment]
No, it's showing not installed now:
![img_20181019_124713](https://user-images.githubusercontent.com/43894743/47216790-0bbc8d80-d39e-11e8-820f-5c7ce78f0a28.png)

**Comment by netniV** [comment]
Can you do a verbose data query for that OID ?

**Comment by aminelami** [comment]
is it possible to do a verbose data query for an "Associated Graph Template" ?
I mean I'm using this OID  as a graph template and not data query, so how would I convert it to data query?

**Comment by netniV** [comment]
You are correct, I was thinking data query.  I am going to assume that you are using CMD.PHP as the processor, not spine?

**Comment by aminelami** [comment]
Yeah exactly.

**Comment by netniV** [comment]
Can you try spine out of curiosity?

**Comment by aminelami** [comment]
Wouldn't that affect other graphs?

**Comment by aminelami** [comment]
Wait a minute, I created the device once again (duplicate) now I see the output is ok! So I deleted the graph from the first device and created it again, but same problem. As a work around I can keep the second created device, but not sure what change solved it!

**Comment by aminelami** [comment]
I didn't try spine BTW.

**Comment by cigamit** [comment]
Can you please walk the 2.3.2 OID?

**Comment by netniV** [comment]
This may be related to the ifName change.

**Comment by netniV** [comment]
Is this graph now working OK?

**Comment by aminelami** [comment]
yes it is
