### ISSUE TITLE
ifDescr with dots in Data Source Index not parsed correctly...

### ISSUE THREAD

**Issue by reubenfarrelly** [Cacti/cacti#2091]
In the last few days something committed to git master appears to have broken the usability of Index Type = IfDescr in Cacti.

I have an Index Type of ifDescr and an Index Value of for example tunnel.40 .  In/Out Bits (64 bit counters).

This SNMP query now always fails.  Logs show:

2018/10/19 11:15:05 - SPINE: Poller[Main Poller] WARNING: Invalid Response, Device[FIREWALL - firewall-1] TH[1] DS[FIREWALL - firewall-1 - Traffic - |query_ifName|] Graphs[FIREWALL - firewall-1 - Traffic - tunnel.40 Primary IPSec Tunnel ] SNMP: v2: firewall-1, dsname: traffic_out, oid: .1.3.6.1.2.1.31.1.1.1.10.tunnel.40, value: U

...notice how the ifDescr is inserted into the OID.  It only seems to be a problem with interfaces that have a dot ( . ) in the ifDescr value.

If I change the ifDescr value to the numeric value 400000040 it all works again.

**Comment by netniV** [comment]
The master branch hasn't been changed in six months.  If you are using the develop branch, what was the last commit that you can see?

**Comment by netniV** [comment]
Also, are you sure it's still using ifDescr?  ifName has become the new default for interface.xml-based queries.

**Comment by reubenfarrelly** [comment]
Sorry - yes - the develop branch.  Where all the fixes are going in :-)

Definitely still set to use ifDescr.  This was an existing installation that worked until very recently.  Now a bunch of interfaces are no longer working (failing to poll):

![image](https://user-images.githubusercontent.com/8552189/47211033-36c7d100-d3e0-11e8-9c74-80ff09600f6b.png)

**Comment by netniV** [comment]
Try changing that to ifName?  Does that change anything?

**Comment by reubenfarrelly** [comment]
Yes, with the one data source I tested with it seems to be working again now.

**Comment by cigamit** [comment]
We have moved the default in the interfaces.xml to be ifName.  So, just make that change, re-index and this problem will be gone.  Looks like you may have already started this.

**Comment by reubenfarrelly** [comment]
That's fine - except that it means I have to go through the system logs finding datasources and fix the ones which were working, but are now broken.

I'm guessing my explanation was not clear but I think there are two problems:

1.  Existing indexes where the index type is ifDescr (yes, legacy existing) and where the index value has a dot in it have broken.  It wasn't before.  This means an existing ifDescr and Eth1 still works, but ifDescr and Eth1.1 now breaks.  That seems to be to be unintended, at least.  I don't see how changing the default would break that.

2. Changing the default should really not require changes to existing pre-configured configuration.  That seems to me to be a regression.  Shouldn't the change of default only apply to any new sources created post the change?

I don't imagine there was any plan to break existing setups.  But as it stands now it looks like there has been some sort of non-backward compatible change which will break some setups, and it's not documented anywhere as far as I can see.  Which means for people out there post 1.2 betas, stuff will break in a non obvious way, and as per last comment it's a manual process to fix.

**Comment by netniV** [comment]
This is likely due to the work that @cigamit did recently over the re-indexes.  We will review and come back to you on that.
