### ISSUE TITLE
[1.2.0 Beta 1] Processes/Threads settings

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#2096]
Looks like when the processes and threads settings moved out of the main configuration and into each data collector they were reset to a default value of '1'. I think the previous values (at least for the main poller) should be migrated over.

**Comment by netniV** [comment]
If you check the code in install/upgrades/1_2_0.php it should have that in there.

**Comment by cigamit** [comment]
It's wrong.

**Comment by cigamit** [comment]
Resolved now.
