### ISSUE TITLE
[1.2.0 Beta 1] Graph Page Rendering and Alignment

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#2097]
Not sure how I pulled this off, I think resizing the window did it. Linux/Chrome. 

Chromium	67.0.3396.99 (Official Build) Built on Ubuntu , running on Ubuntu 17.10 (64-bit)
Revision	8ef023c8bf48f152812e2068fc21827bc5503917-
OS	Linux
JavaScript	V8 6.7.288.46
Flash	(Disabled)
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/67.0.3396.99 Chrome/67.0.3396.99 Safari/537.36
Command Line	/usr/lib/chromium-browser/chromium-browser --enable-pinch --flag-switches-begin --flag-switches-end
Executable Path	/usr/lib/chromium-browser/chromium-browser
Profile Path	/home/eric/.config/chromium/Default

![spectacle x15351](https://user-images.githubusercontent.com/12864741/47261997-cdf05f80-d498-11e8-99b2-7ed876efe57b.png)

**Comment by cigamit** [comment]
This is resolved now.  Make sure you close all your browsers and re-open.
