### ISSUE TITLE
[1.2.0 Beta 1] Upgrading Data Collectors

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#2099]
I attempted to upgrade some Cacti data collectors but it didn't work out. When I went to the website for the remote poller I was taken straight into the interface, and I was not run through the installer. I tried clearing cache/history, and even a completely different browser. But no matter what the installer would not fire up. I went directly to the cacti/install/install.php and the install page came up, with a spinning Cacti symbol. Eventually I got a 500 timeout, due to the php max execution time getting hit. I increased that to 90 seconds and waited, still timed out. 
So what's the best procedure here? Is running the installer on a remote data collector not necessary?

**Comment by cigamit** [comment]
They will pull updated files from the master and self upgrade.  Though that is not clearly documented.

**Comment by eschoeller** [comment]
Oh! Well, this should be interesting then .. since I've done somethings manually ...

**Comment by eschoeller** [comment]
OK, this has been kinda rough. But I'm getting through it. 
First, it would be really good to have something splash across the screen on a remote poller indicating that it is upgrading from the main poller. Or something in the log. Or something in the data collector list on the main poller. Maybe a 'status' column that says "synced and upgraded". 
Somehow, the configs of these collectors got jacked up. The "Hostname" of the remote database server for 2/3 of my collectors was "localhost". That obviously was confusing and breaking things. 
I did a "Full Sync" on 2/3 of the pollers and they started to come back to life, but they had no devices re-assigned to them yet. For the poller that had 150 devices the Full Sync would not run. It kept hitting the php max_execution_time. So I bumped this up to 90 seconds and it finally went through, and just like magic it started polling all those devices again. 

I'm not sure what real recommendations I have for this ... obviously I could have had some lurking problems before the upgrade, and I'm not entirely sure I've fixed everything yet. One thing is for sure though, a max_execution_time of 30 seconds really doesn't work for the poller Full Sync. Perhaps in the installer we'd check that and recommend something like 60 or 90 seconds. Or maybe it shouldn't really take as long as it did ... ?

**Comment by netniV** [comment]
This should now be back to a 1 minute recommendation.

The installer did have a recommended limit of 5 minutes, but a change was made to make this 1 minute. I just reviewed that the code and it is not quite right as the conversion from minutes to seconds has also been changed from *60 to *10 which makes it a 10 second limit recommendation.

**Comment by cigamit** [comment]
Great suggestion on the remote sync auto-upgrade.

**Comment by cigamit** [comment]
I've added the version table to the table replication.

**Comment by cigamit** [comment]
When the upgrade to 1.2 is finalized, a full sync will be executed at the next polling interval that should upgrade all of the data collectors.
