### ISSUE TITLE
Database creation error when utf8mb4 is used

### ISSUE THREAD

**Issue by rprofijt** [Cacti/cacti#210]
mysql -u root cacti </opt/cacti/cacti.sql 
ERROR 1071 (42000) at line 2560: Specified key was too long; max key length is 767 bytes

It seems like the key for this table is too long when the utf8mb4 charset is being used. This is the default in MariaDB as packaged in Debian: https://mariadb.com/kb/en/mariadb/differences-in-mariadb-in-debian/

Changing it back to latin1 fixes the issue.

I don't know if this can really be considered a bug, but setting the character set in cacti.sql would help.

**Comment by cigamit** [comment]
Can you please try the import again using the utf8mb4 with the new cacti.sql and let me know if there are any more issues.  Thanks!

**Comment by rprofijt** [comment]
Same error.

Did some more searching, it seems that any index greater than 191 characters is not going to work because MySQL/MariaDB reserve 4 bytes for every character in utf8. There is an innodb_large_prefix setting which increases the limit to 3072 but that still is not enough for the host_snmp_cache table.

Setting the innodb_large_prefix AND switching from utf8m4 to utf8 does work..

info:
http://stackoverflow.com/questions/6172798/mysql-varchar255-utf8-is-too-long-for-key-but-max-length-is-1000-bytes

**Comment by cigamit** [comment]
I did a small audit, and I believe that the cacti.sql is now utf8m4 compliant.  Some columns are actually longer than they need to be, but we will make that a separate issue.  If you still have time, you might want to test the latest cacti.sql.

**Comment by cigamit** [comment]
All clear on my side.  I'm going to go ahead and close.  Thanks for your help.

**Comment by smiles1969** [comment]
I ran into this as well with mysql as it is the recommended charset on the Cacti System Utilities->Tech support page.

**Comment by rprofijt** [comment]
There are still keys larger than 191 characters, for example on line 2036 an 2097.

**Comment by cigamit** [comment]
Okay, updated the two missing.  Thanks!

**Comment by cigamit** [comment]
I may get back to flowview this week.
