### ISSUE TITLE
[1.2.0 Beta 1] Change Toggle Box Colors when Disabled

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#2100]
The option slider won't switch to disable boost :(
![peek 2018-10-20 21-33](https://user-images.githubusercontent.com/12864741/47262826-d607c980-d4af-11e8-81bf-4a3afaf8ac85.gif)

**Comment by eschoeller** [comment]
Ah, shucks nevermind. I found if I disable the data collectors I can switch it. Also helps if I read the documentation. But, perhaps we could make the slider grayed out? The fact that it was green made me to believe I could switch it. Maybe also indicate that simply disabling the data collectors will enable the option.

**Comment by eschoeller** [comment]
So I was able to disable it, but, I'm still seeing RRDsProcessed:0 each poller run, and the Pending Boost Records is still increasing. So, this is still a bit misleading!

**Comment by cigamit** [comment]
How many active Data Collectors?  Boost is mandatory when you have multiple Data Collectors.

**Comment by cigamit** [comment]
I like the idea of changing the colors when disabled through.

**Comment by eschoeller** [comment]
I have 3 remote data collectors ... which aren't really working so great yet!

**Comment by netniV** [comment]
How about making the green border remain, leaving the background transparent? Or fading the Cacti icon?  We have to be careful introducing another color that it doesn't cause confusion.

**Comment by netniV** [comment]
Actually, I think the better thing to do would be to give the stop mouse pointer, since that is a clearer clue that you can't do something.

**Comment by netniV** [comment]
So I went with my last idea, see what you think
