### ISSUE TITLE
[1.2.0 Beta 1] Installer innodb_buffer_pool_instances calculation

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#2101]
I found this very confusing. The tool tip states the maximum size is 64, however the conditional check is showing '8 >= 769" in my case ...

![screenshot_20181020_151215](https://user-images.githubusercontent.com/12864741/47262939-9d1d2400-d4b2-11e8-8df3-d1178befb85d.png)

**Comment by cigamit** [comment]
That one is funny!

**Comment by cigamit** [comment]
Resolved.

**Comment by netniV** [comment]
Yeah my bad.  We decided to update the recommendations for a couple of items to be more dynamic. I didn't actually read the descriptions (from overly reading them as I had ever time I reinstalled (which is like 1000+ I'm sure).  There may be one or two others that are now dynamic, but the descriptions are not.
