### ISSUE TITLE
[1.2.0 Beta 1] log_verbosity is not synchronized or used by remote data collectors

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#2105]
I can set the log_verbosity on the main cacti server to any setting, and on the remote data collectors I can see this changed in the configuration (leading me to believe the remote collectors are reading the settings table from the main poller). But the log_verbosity setting on the local mysql database for the remote pollers stays at the same value as it had found before, and the logging on those devices does not change. When I execute a "Full Sync" for that data collector the log_verbosity does change, and the logging on that data collector reflects what it should be. Furthermore, if I'm logged into a remote data collector and execute a change to the log_verbosity the main collector changes, but the remote poller does not. 
So the only way to change the logging verbosity on a remote poller is to change it (from anywhere) and then execute a Full Sync for that poller. Is this by design? It seems like any time a settings change is made there should be a hook to execute a sync of the settings table to the data collectors, or probably more efficiently just propagate whatever change was made. I so see this note in the Beta 2 release notes "Enhancement to sync remote pollers when device, graph or data source update occur." but it doesn't seem like this addresses a settings change?

**Comment by netniV** [comment]
If you login on a remote poller UI it’s actually the main poller unless the connection is offline. .

**Comment by eschoeller** [comment]
Ok, that makes sense. So should these settings be propagated to remote data collectors in real-time or is the Full Sync the only option?

Eric.

**Comment by cigamit** [comment]
This is resolved now.  When you save settings that should be replicated, they will now.
