### ISSUE TITLE
form_file function does not support customized file field name because hardcode label.for property

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#2107]
```diff
index cf7a9010..72c0c513 100644
--- a/lib/html_form.php
+++ b/lib/html_form.php
@@ -462,7 +462,7 @@ function form_submit($form_name, $value, $title = '', $action = '') {
    @arg $form_size - the size (width) of the textbox */
 function form_file($form_name, $form_size = 30) {
        print "<div>\n";
-       print "<label class='import_label' for='import_file'>" . __('Select a File'). "</label>\n";
+       print "<label class='import_label' for='$form_name'>" . __('Select a File'). "</label>\n";
        print "<input type='file'";

        if (isset($_SESSION['sess_error_fields']) && !empty($_SESSION['sess_error_fields'][$form_name])) {
```

**Comment by netniV** [comment]
This change could break other functions.  Have you verified it does not affect any other file uploads?

**Comment by ddb4github** [comment]
> This change could break other functions. Have you verified it does not affect any other file uploads?

1. By code logic, "other file uploads" should be not workable now if it use form_file function and field name is not "import_file"
2.  Only two pages use 'form_file' function, and both of them use 'import_file' as field name: 
     * cacti/templates_import.php
     * plugin_thold/thold_templates.php, 

    All other pages like to directly output '<input type=file', like:
    * cacti/color.php,  
    * plugin_hmib/hmib_types.php
    * plugin_mactrack/mactrack_device_types.php
    * plugin_mactrack/mactrack_devices.php
    * plugin_reportit/templates.php

**Comment by ddb4github** [comment]
Actually,  param "$form_name" should be renamed to "form_field_name". It is a "<input type=file name=", and is not a "<form name=".
BTW, "<label for=" use "form field id" that might equal "form field name" under most scenario.

**Comment by netniV** [comment]
This has now been committed to the development code.
