### ISSUE TITLE
Poller is reading archived log files

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#2111]
It appears to me that poller.php is not only reading the entire contents of the cacti.log file on every poller run, but it's somehow reading other files in the cacti log directory as well. This was causing some pretty bad problems for me. 
I noticed one of my data collectors was completely I/O bound. And it was all read operations, coming from poller.php. Hooking it up to strace it looked like read() from a log file. Looking into it further with lsof, I found that it was reading data from '/var/log/cacti/cacti.log.1' which was 17G (a file I had manually archived away). Then I had a 5G cacti.log file which it was reading too. I moved both of these files while the poller was running, and sure enough the lsof output changed to reflect the new location of the files. After a subsequent run with a clean /var/log/cacti directory the poller runtime plummeted and there was no more I/O issue. 
So, what is going on here!!
I realize these files are astronomically large, but while I'm troubleshooting things they can grow. But to even have Cacti reading in other files in the directory which have been archived? This seems very unnecessary to me!!!
This solves a mystery I was chasing around for a long time ... as these files were getting larger my pollers seemed to start, but do absolutely nothing for a very long time and then finally start the polling process. It seems clear to me now that I was waiting for the poller to read the entire log file before it did any polling.

**Comment by cigamit** [comment]
I'm not sure where this is taking place.  There was a change between 1.1 and 1.2.  Researching.

**Comment by cigamit** [comment]
Thanks for pointing out.  Good thing we caught this one.
