### ISSUE TITLE
unknown rrdtool error

### ISSUE THREAD

**Issue by el3den** [Cacti/cacti#2113]
i can poll device by snmp which is working fine, i can see interfaces but when i view the graph section all graphs showing cacti logo with "unknown rrdtool error"

**Comment by netniV** [comment]
Has your poller run via cron?

**Comment by netniV** [comment]
Can you provide the following information:

- OS & Version
- PHP Version
- Cacti Version
- If applicable:
   - Backtrace
   - Plugin name/version

Also, are there any errors in the web server log and/or cacti log?

**Comment by el3den** [comment]
-Windows server 2012 R2
-PHP 7.2.11
-cacti 1.1.38
i am using xampp.
i can see some logs:

2018/10/23  12:51:21 - CMDPHP PHP ERROR WARNING Backtrace:  (C:\xampp\htdocs\cacti\graphs_new.php: 37  form_save)(C:\xampp\htdocs\cacti\graphs_new.php: 123  host_new_graphs)(C:\xampp\htdocs\cacti\graphs_new.php: 397  host_new_graphs_save)(C:\xampp\htdocs\cacti\graphs_new.php: 266  push_out_host)(C:\xampp\htdocs\cacti\lib\utility.php: 650  poller_update_poller_cache_from_buffer)(C:\xampp\htdocs\cacti\lib\utility.php:  541 sizeof)(CactiErrorHandler)(C:\xampp\htdocs\cacti\lib\functions.php:  4585 cacti_debug_backtrace)
--
2018/10/23 12:51:21 - ERROR PHP WARNING: sizeof(): Parameter must be  an array or an object that implements Countable in file:  C:\xampp\htdocs\cacti\lib\utility.php  on line: 541

yes poller is default not spine

 am using xampp folder rrdtool that i have put rrdtool in it, in cacti settings it says minimum version 1.3, while windows available version is 1.2

**Comment by netniV** [comment]
Cacti 1.1.38 is NOT compatible with PHP 7.2+
