### ISSUE TITLE
thold sent but not received

### ISSUE THREAD

**Issue by rexfrist** [Cacti/cacti#2114]
cacti:1.1.38
Thresholds:1.0.3

my test is work,thold sends a message in the logs ,But the mail was not received.No matter which email I use.

test mail:
This is a test message generated from Cacti. This message was sent to test the configuration of your Mail Settings.

Your email settings are currently set as follows

Method: PHP's Mailer Class

cacti logs:
10/23/2018 17:13:12 - MAILER Mail Successfully Sent to 'test@gmail.com,', Subject: 'ALERT: test1 - Used Space - C: Label: Serial Number e4795b25 [hdd_used] went above threshold of 80 with 82.4192'
10/23/2018 17:13:11 - MAILER Mail Successfully Sent to 'test@gmail.com,', Subject: 'ALERT: test2 - Used Space - C: Label: Serial Number e4795b25 [hdd_used] went above threshold of 80 with 95.7189'
10/23/2018 17:13:11 - MAILER Mail Successfully Sent to 'test@gmail.com,', Subject: 'ALERT: test3 - Used Space - C: Label: Serial Number e4795b25 [hdd_used] went above threshold of 80 with 93.9272'
10/23/2018 17:13:09 - SYSTEM STATS: Time:4.7201 Method:cmd.php Processes:4 Threads:N/A Hosts:7 HostsPerProcess:2 DataSources:29 RRDsProcessed:17
10/23/2018 17:09:08 - SYSTEM THOLD STATS: Time:0.1057 Tholds:0 TotalDevices:7 DownDevices:0 NewDownDevices:0
10/23/2018 17:09:06 - SYSTEM STATS: Time:4.7383 Method:cmd.php Processes:4 Threads:N/A Hosts:7 HostsPerProcess:2 DataSources:29 RRDsProcessed:17
10/23/2018 17:05:09 - SYSTEM THOLD STATS: Time:0.6391 Tholds:1 TotalDevices:7 DownDevices:0 NewDownDevices:0

**Comment by netniV** [comment]
This is a thold issue, not a cacti core issue.
