### ISSUE TITLE
chinese_china_simplified.po bug

### ISSUE THREAD

**Issue by hxbzh021** [Cacti/cacti#2115]
The total number of graphics is incomplete, only the graphics of the current page can be seen, and the next page cannot be clicked.

cacti/locales/po/chinese_china_simplified.po
12939 Rows: msgid "%d to %d of %s [ %s ]"
12940 Rows: msgstr "%s [ %s ] 中 %d 到 %d" --> msgstr "%d 到 %d 共 %s [ %s ]"

**Comment by netniV** [comment]
Can you submit the fix as a PR ?  This may seem cheeky but if you could also review the other lines, that would be good too. :)

**Comment by netniV** [comment]
@hxbzh021 Just in case you are only getting notifications if you are tagged, is this something you could submit a change ?

**Comment by cigamit** [comment]
Resolved.
