### ISSUE TITLE
[1.2.0 beta2] Cannot find 'output' field in 'Data Templates' edit page

### ISSUE THREAD

**Issue by skyjou** [Cacti/cacti#2116]
In 1.1.38 the 'output' and 'internal data source name' can be mapping in this field:
![screenshot from 2018-10-25 14-13-27](https://user-images.githubusercontent.com/13309854/47479849-f2fe1d00-d860-11e8-8fa2-9510020aed6d.png)

But in 1.2.0 Beta2, I cannot find the field:
![screenshot from 2018-10-25 14-13-44](https://user-images.githubusercontent.com/13309854/47479899-1de87100-d861-11e8-98dd-39d54ad3a7b2.png)

**Comment by cigamit** [comment]
Export your template and attach here.  Include dependencies.

**Comment by skyjou** [comment]
This issue happen to any template, include a whole new one and the build-in template.

Here is 'Unix - Load Average' date template in 1.1.38:
![screenshot from 2018-10-26 13-56-52](https://user-images.githubusercontent.com/13309854/47547813-8438c680-d929-11e8-8251-c35e0a9147e8.png)

Here is 'Unix - Load Average' date template in 1.2.0 Beta:
![screenshot from 2018-10-26 13-57-07](https://user-images.githubusercontent.com/13309854/47547839-99adf080-d929-11e8-9c64-65d2e53aa5f0.png)

**Comment by netniV** [comment]
Please can you export and attach a copy of your template, that way we can verify there hasn't been any corruption of the template.

**Comment by netniV** [comment]
Forget that.  I can confirm that this is a bug.  i will look into it shortly.

**Comment by netniV** [comment]
OK, not entirely sure that this is actually a bug.  This template does not hold any INPUT fields, so correctly the form is telling you that there are not any.  The three fields that you see are all output fields so have no data to be edited.

**Comment by netniV** [comment]
So. find the data input using the name, reveals that the ID is 4.
```sql
select id, name from data_input where name = 'Unix - Get Load Average';
+----+-------------------------+
| id | name                    |
+----+-------------------------+
|  4 | Unix - Get Load Average |
+----+-------------------------+
```

Finding all the fields for data input 4, reveals that there are no input fields:

```sql
select id, data_input_id, name, data_name, input_output 
from data_input_fields where data_input_id = 4;
+----+---------------+-------------------+-----------+--------------+
| id | data_input_id | name              | data_name | input_output |
+----+---------------+-------------------+-----------+--------------+
| 17 |             4 | 1 Minute Average  | 1min      | out          |
| 18 |             4 | 5 Minute Average  | 5min      | out          |
| 19 |             4 | 10 Minute Average | 10min     | out          |
+----+---------------+-------------------+-----------+--------------+
3 rows in set (0.00 sec)
```

**Comment by skyjou** [comment]
I don't understand, the missing one is 'output field', not the input. I can import template that made in 1.1.38 into 1.2.0, and it will work. But if there is no output field in edit page. How can I mapping multiple key:value from script's output?

**Comment by netniV** [comment]
Each field is it's own tab.  I notice that you've logged a separate issue about which field that maps to.
