### ISSUE TITLE
[1.2.0 beta 2]  FATAL: Connection to Cacti database failed

### ISSUE THREAD

**Issue by YangShenghui2018** [Cacti/cacti#2117]
Hello，I deployed Cacti [1.2.0 beta 2] on the new server. Everything seems normal, but when testing is executed, the following mistakes are reported. When I manually connect to the database at the command line, it is normal.

operating system:  CentOS release 6.6
PHP Version        :  PHP 5.3.3
MySQL Version   :  5.7.23

/usr/bin/php  /web/cacti/poller.php
The error message is as follows: 
FATAL: Connection to Cacti database failed. Please ensure
    - the PHP MySQL module is installed and enabled.
    - the database is running.
    - the credentials in config.php are valid.

I checked everything according to the wrong information, and all of them were normal. Therefore, I would like to receive your advice or help.  Thank you！
@cigamit    @netniV

**Comment by netniV** [comment]
Are you using an IP address to connect or hostname?  If hostname, is the server listening on an address other than just the local loop back if the server name is not localhost?  Also, your PHP version is less than the minimum supported version for Cacti 1.2 which is PHP 5.4

**Comment by YangShenghui2018** [comment]
I'm sorry to give you feedback so long. I checked everything again, but the problem still persists. Even if I changed the new server, I still had the same mistake.

![11](https://user-images.githubusercontent.com/37231882/47774119-16284100-dd27-11e8-8056-bff50db9d51d.png)


![22](https://user-images.githubusercontent.com/37231882/47774420-f9d8d400-dd27-11e8-9711-89154190460c.png)

![33](https://user-images.githubusercontent.com/37231882/47774440-02310f00-dd28-11e8-80cd-93e2314952eb.png)

![44](https://user-images.githubusercontent.com/37231882/47774561-52a86c80-dd28-11e8-92e7-5f5b8d21c438.png)

**Comment by YangShenghui2018** [comment]
@netniV @cigamit

**Comment by anarkia1976** [comment]
Hi,
check sintax related to connection to your database.

On my box after exe the command i have "cacti database connection ok prompt":
mysql -u xxxxx -p cacti
MariaDB [cacti]>

thanks.

**Comment by netniV** [comment]
His syntax seems correct. For the -u and -p parameter's, he is putting them in at command line so they are immediately following them (no space required).   The -h means the server you are connecting to.  The final part is the database.

So, can we be clear here.  Is it the command line running poller.php that is failing or the website?

**Comment by netniV** [comment]
I would restart your apache/ngix service just to be sure it's not interfering.

**Comment by YangShenghui2018** [comment]
@anarkia1976 Thank you very much for your attention.
@netniV I found some anomalies.  When I use the command test, the execution fails, and the error log is shown in the following picture :
![11](https://user-images.githubusercontent.com/37231882/47837748-1ccabd00-dde8-11e8-962f-c65a37608f45.png)
![22](https://user-images.githubusercontent.com/37231882/47837878-83e87180-dde8-11e8-8071-c0f667b1bbac.png)

According to the web search results, I modified the php.ini configuration file. I added a value to the pdo_mysql.default_socket directive, then restart the Apache service.
![33](https://user-images.githubusercontent.com/37231882/47838089-38829300-dde9-11e8-8f50-fead4836ca9d.png)

The surprise is that the order has been executed successfully.  But Web installation is still a failure, I checked the Apache log and found the following error: 

![555](https://user-images.githubusercontent.com/37231882/47838734-3ae5ec80-ddeb-11e8-8bd0-ff2a86fa5e21.png)

![66](https://user-images.githubusercontent.com/37231882/47838468-759b5500-ddea-11e8-9ec0-f9d7a6b69c0b.png)

Where is the problem? I am so sad that I can not find the answer for so long.

**Comment by netniV** [comment]
What was that full "redclare" error because it sounds like something is being included twice.

**Comment by YangShenghui2018** [comment]
Hello, I have solved the problem. I installed php56 version using Yum instead of source code compilation. Thank you!
