### ISSUE TITLE
[1.2.0 Beta2] Any data template with script data input method missing 'output field'

### ISSUE THREAD

**Issue by skyjou** [Cacti/cacti#2118]
The 'output field' is missing in data template edit page:
![image 2](https://user-images.githubusercontent.com/13309854/47571778-f29e7880-d96b-11e8-9f68-06abeced8eee.png)

Compare to 1.1.38:
![image 1](https://user-images.githubusercontent.com/13309854/47571959-63459500-d96c-11e8-9729-25b8e1a9ca26.png)

Without this field, user cannot map multiple key:value from script output to the ds in data template.

**Comment by netniV** [comment]
The reason you cannot see that field is because the code has a check to see what the type_id of the input is.   In the case of the above template that is type 1.  For any inputs that are type 1 - 4 or 6, the editing of that field is disabled.

**Comment by skyjou** [comment]
I do not understand type_id. I cannot map script output like 'key1:value1 key2:value2' into data template anymore?

**Comment by netniV** [comment]
This was part of this commit so I will defer to @cigamit as to the correctness of this:
```
commit 4db6d4638b11af729bc1bc6043edfbfac1598fee
Author: cigamit <jimmy@sqmail.org>
Date:   Sat Aug 18 09:11:44 2018 -0500

    Feature: Remove confusion when dealing with snmp get

    - Do not allow second data source to be added to an SNMP Get data
    - Additionally clean up some messy code
    - Do data source rra removal through callback
```

**Comment by eschoeller** [comment]
Hmm, I might have some templates impacted by this

**Comment by skyjou** [comment]
In fact, even if there is only one ds in script data template, this change still causes a problem. An output of script may be "enqueued:1000". Although this format is correct, it will not be accepted by template made by Cacti 1.2. Because of script data template has no mapping info now, Cacti cannot recognize script's output that have "keys".

Here is the debug message with my Cacti 1.2:

> 2018/10/27 08:30:01 - SPINE: Poller[Main Poller] Device[Cacti] HT[1] DS[Cacti - Syslog Status] Graphs[Cacti - Syslog Stats] SCRIPT: bash /opt/cacti-web/scripts/enqueued.sh, output: enqueued:17810

Above message shows Cacti now put whole "enqueued:17810" as the "value". This is incorrect. 

If I import a script data template made by Cacti 1.1.38, which has correct mapping info, the debug message will be:
> 2018/10/27 08:30:01 - SPINE: Poller[Main Poller] Device[Cacti] HT[1] DS[Cacti - Syslog Status] Graphs[Cacti - Syslog Stats] SCRIPT: bash /opt/cacti-web/scripts/enqueued.sh 'enqueued:', output: 17810

This change may break [script output format](https://www.cacti.net/downloads/docs/html/making_scripts_work_with_cacti.html).

**Comment by netniV** [comment]
So, the simply way to correct this would to remove the type restriction, I'm just waiting on confirmation before I do that is to the impact reinstating that may have against fixes put in.

**Comment by cigamit** [comment]
That was likely midnight logic.  Resolved.
