### ISSUE TITLE
[1.2.0 Beta 1] Looping sql query

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#2119]
My main data collector has started to execute the same sql query over and over again at the end of a poller run, this is causing what normally is a 20 second runtime to extend to about 120 seconds. This is what I'm picking up from a mysql full processlist:
` SELECT dtr.data_source_name, dif.data_name FROM data_template_rrd AS dtr INNER JOIN data_input_fields AS dif ON dtr.data_input_field_id=dif.id WHERE dtr.local_data_id = '31897'`
It's always the same data source ID. I have disabled this particular data source, but the problem persists. I am contemplating deleting the data source entirely ... but I thought it would be better to keep it around for troubleshooting ... I'm just not sure what I need to investigate next.

**Comment by netniV** [comment]
I noticed you’d logged this as Beta 1 have you tried updating to Beta 2? Don’t forget to run the upgrade database cli as there are some DB column changes.

**Comment by eschoeller** [comment]
Yeah, I'm still on Beta 1. I suppose it's time to jump up to Beta 2. I ran this query on the db:
`select data_source_name, data_name from data_template_rrd inner join data_input_fields on data_input_field_id where local_data_id='31897';`
I got 869 rows back of some really random stuff ...

**Comment by eschoeller** [comment]
OK, I'm running Beta 2. Still see the same problem.

**Comment by netniV** [comment]
So, that is a piece of code that is supposed to be handling the scenario were you can have data sources without a template.  It uses the local data id to look these up.  The local data id's are found using this query:

```sql
"SELECT po.output, po.time,
                UNIX_TIMESTAMP(po.time) as unix_time, po.local_data_id, dl.data_template_id,
                pi.rrd_path, pi.rrd_name, pi.rrd_num
                FROM poller_output AS po
                INNER JOIN poller_item AS pi
                ON po.local_data_id=pi.local_data_id
                AND po.rrd_name=pi.rrd_name
                INNER JOIN data_local AS dl
                ON dl.id=po.local_data_id
                ORDER BY po.local_data_id
```

**Comment by netniV** [comment]
Is this issue still on going?

**Comment by cigamit** [comment]
This was fixed by the spine fix I think.

**Comment by eschoeller** [comment]
yeah, I think this one is fixed. At least I know my poller runtimes are back to normal.
