### ISSUE TITLE
[1.2.0 Beta 2] Remote Data Collector Pollers / trouble with poller_time table

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#2121]
I'm getting closer to a more complete report on this issue, but I've run short on time. 
As it stands right now, my remote data collectors are completing all polling functions in a normal amount of time, but they do not finish until they are terminated by the poller max runtime is exceeded. 
I think there is an issue with how they are interacting with their local poller_runtime table. Entries are not being deleted, so the entries in the table are ever increasing. But it appears that the remote data collectors are actually attempting to calculate $finished_processes by querying the main data collector's poller_time table? And this is not receiving any poller start_time data because that's being written locally? 
Also, this output:
<pre>print 'Waiting on ' . ($started_processes - $finished_processes) . ' of ' . $started_processes . " pollers.\n";</pre>
Doesn't really appear to go anywhere. 
This is all happening in poller.php around lines 625-650. 
Sorry this is half-baked right now, but maybe this has an obvious fix?

**Comment by netniV** [comment]
I think that spine should be inserting this into both DB's, and so should CMD.PHP. The main reason being that if the remote poller goes offline during a cycle, it still needs to update it's polled time.

I can create a patch for you to test if you like, but I won't be committing it to the main code without checking things out further as it could turn out that I am heading in the wrong direction.

**Comment by netniV** [comment]
Try this and let me know what you find:

```diff
diff --git a/spine.c b/spine.c
index d487bfb..b8636bc 100644
--- a/spine.c
+++ b/spine.c
@@ -211,7 +211,9 @@ int main(int argc, char *argv[]) {
 	pthread_attr_t attr;
 
 	int* ids = NULL;
+	int mode = REMOTE;
 	MYSQL mysql;
+	MYSQL mysqlr;
 	MYSQL_RES *result  = NULL;
 	MYSQL_RES *tresult = NULL;
 	MYSQL_ROW mysql_row;
@@ -526,6 +528,13 @@ int main(int argc, char *argv[]) {
 	/* connect to database */
 	db_connect(LOCAL, &mysql);
 
+	if (set.poller_id > 1 && set.mode == REMOTE_ONLINE) {
+		db_connect(REMOTE, &mysqlr);
+		mode = REMOTE;
+	} else {
+		mode = LOCAL;
+	}
+
 	/* Since MySQL 5.7 the sql_mode defaults are too strict for cacti */
 	db_insert(&mysql, LOCAL, "SET SESSION sql_mode = (SELECT REPLACE(@@sql_mode,'NO_ZERO_DATE', ''))");
 	db_insert(&mysql, LOCAL, "SET SESSION sql_mode = (SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY', ''))");
@@ -629,7 +638,11 @@ int main(int argc, char *argv[]) {
 
 	/* mark the spine process as started */
 	snprintf(querybuf, BIG_BUFSIZE, "INSERT INTO poller_time (poller_id, pid, start_time, end_time) VALUES (%i, %i, NOW(), '0000-00-00 00:00:00')", set.poller_id, getpid());
-	db_insert(&mysql, LOCAL, querybuf);
+	if (mode == REMOTE)
+		db_insert(&mysqlr, REMOTE, querybuf);
+	} else {
+		db_insert(&mysql, LOCAL, querybuf);
+	}
 
 	/* initialize threads and mutexes */
 	pthread_attr_init(&attr);
@@ -822,7 +835,11 @@ int main(int argc, char *argv[]) {
 	}
 
 	snprintf(querybuf, BIG_BUFSIZE, "UPDATE poller_time SET end_time=NOW() WHERE poller_id=%i AND pid=%i", set.poller_id, getpid());
-	db_insert(&mysql, LOCAL, querybuf);
+	if (mode == REMOTE) {
+		db_insert(&mysqlr, REMOTE, querybuf);
+	} else {
+		db_insert(&mysql, LOCAL, querybuf);
+	}
 
 	/* cleanup and exit program */
 	pthread_attr_destroy(&attr);
@@ -848,6 +865,10 @@ int main(int argc, char *argv[]) {
 	db_free_result(result);
 	db_disconnect(&mysql);
 
+	if (set.poller_id > 1 && set.mode == REMOTE_ONLINE) {
+		db_disconnect(&mysqlr);
+	}
+
 	SPINE_LOG_DEBUG(("DEBUG: MYSQL Free & Close Completed"));
 
 	/* close snmp */
```

**Comment by eschoeller** [comment]
I get scads of errors trying to build spine with that patch. Do you want to see them?

**Comment by eschoeller** [comment]
Sorry I've made other debug log changes so I'm probably offset from you. 
<pre>
if (mode == REMOTE)
</pre>
should be
<pre>
if (mode == REMOTE) {
</pre>

**Comment by netniV** [comment]
Oh yeah. That’s my bad. I wrote it but didn’t test it.

**Comment by netniV** [comment]
Are you sayin* that works?

**Comment by eschoeller** [comment]
Yep, I've been running with this new code for a few hours and the pollers are exiting properly and things appear to be working really well.

**Comment by netniV** [comment]
I'll close this now then as I've pushed the fix to Spine's develop branch.
