### ISSUE TITLE
[1.2.0 Beta2] Spine Poller Path error - Remote data collector

### ISSUE THREAD

**Issue by anarkia1976** [Cacti/cacti#2125]
I have this issue:

MAIN
![image](https://user-images.githubusercontent.com/1744639/47635798-85027000-db56-11e8-8c68-e2b786cd4f47.png)

POLLER
![image](https://user-images.githubusercontent.com/1744639/47635807-8e8bd800-db56-11e8-9dc9-625be2ab5472.png)

I have checked all settings but i can't resolve this problem.

thanks a lot

**Comment by netniV** [comment]
If you do the following SQL query:

```sql
SELECT name,value FROM settings where name like 'path_%';
```

Can you verify the are set correctly?

**Comment by anarkia1976** [comment]
Poller don't have rows related to settings.

MAIN
MariaDB [cacti]> SELECT name,value FROM settings where name like 'path_%';
+---------------------------+---------------------------------------+
| name                      | value                                 |
+---------------------------+---------------------------------------+
| path_boost_log            |                                       |
| path_cactilog             | /usr/share/cacti/log/cacti.log        |
| path_php_binary           | /usr/bin/php                          |
| path_rrdtool              | /opt/rrdtool-1.7.0/bin/rrdtool        |
| path_rrdtool_default_font |                                       |
| path_snmpbulkwalk         | /usr/bin/snmpbulkwalk                 |
| path_snmpget              | /usr/bin/snmpget                      |
| path_snmpgetnext          | /usr/bin/snmpgetnext                  |
| path_snmptrap             | /usr/bin/snmptrap                     |
| path_snmpwalk             | /usr/bin/snmpwalk                     |
| path_spine                | /usr/local/spine/bin/spine            |
| path_spine_config         | /usr/local/spine/etc/spine.conf       |
| path_stderrlog            | /usr/share/cacti/log/cacti_stderr.log |
| path_webroot              | /usr/share/cacti                      |
+---------------------------+---------------------------------------+

POLLER
MariaDB [cacti]> SELECT name,value FROM settings where name like 'path_%';
+--------------+------------------+
| name         | value            |
+--------------+------------------+
| path_webroot | /usr/share/cacti |
+--------------+------------------+
1 row in set (0.00 sec)

**Comment by netniV** [comment]
I have a feeling this is a catch 22 issue with the error I got using a different OS for a remote poller.  A change was made to the settings code, this may have caused this so I want to be sure which commit you are updated to.

**Comment by anarkia1976** [comment]
All updated, only the poller have this problem.

**Comment by anarkia1976** [comment]
I have updated to the latest spine/cacti but the problem is the same:
FROM POLLER:
2018/10/31 09:55:03 - POLLER: Poller[Cacti-Poller] ERROR: The spine path: is invalid. Poller can not continue!

**Comment by netniV** [comment]
This is because the settings are not being transferred to the remote system.  For now, you will have to manually insert them into the remote poller's settings table until we have rectified this.

**Comment by anarkia1976** [comment]
@netniV thanks a lot

**Comment by cigamit** [comment]
Talk about the law of unintended consequences...

**Comment by cigamit** [comment]
Okay, it's sort of fixed.  Will give this a little more thought prior to release.

**Comment by anarkia1976** [comment]
resolved. thanks a lot.
