### ISSUE TITLE
[CACTI 1.2.0 Beta2] error on api_device.php, call to unknown function

### ISSUE THREAD

**Issue by arno-st** [Cacti/cacti#2126]
I have an error on a call on api_device.php.
The call I made is on the stack trace, and it's to api_device_save
Here is the output:

Fatal error: Uncaught Error: Call to undefined function poller_push_to_remote_db_connect() in /usr/share/cacti/lib/api_device.php:658
Stack trace:
#0 /usr/share/cacti/plugins/linkdiscovery/findhosts.php(600): api_device_save('0', '6', 'se-ch9-40', 'se-ch9-40.recol...', 'telvlsn', '2', '', '', '161', '500', false, '2', '2', '23', '400', '1', 'Added by Link D...', '', '', '', '', '', 10, 1, 1, 0)

I think it's just a missing lib/poller.php as include file

**Comment by netniV** [comment]
I've added this to the latest development code.
