### ISSUE TITLE
[CACTI 1.2.0 Beta2] Error on duplication of graph template

### ISSUE THREAD

**Issue by arno-st** [Cacti/cacti#2127]
I try to duplicate the Interface - Traffic (bits/sec) to Interface -> Traffic (bits/sec) plus/minus
and i have this error:
Sorry we could not process your last action
SQL save on table 'snmp_query_graph' Column 'snmp_query_graph_id' does not exist unable to save

but the copy did succeed

And the log give:
```
2018/10/29 09:05:14 - CMDPHP SQL Backtrace: (/graph_templates.php[49]:form_actions(), /graph_templates.php[261]:api_duplicate_graph(), /lib/api_graph.php[390]:sql_save())
2018/10/29 09:05:14 - DBCALL ERROR: SQL Save on table 'snmp_query_graph': Column 'snmp_query_graph_id' does not exist, unable to save!
```

```
MariaDB [cacti]> desc snmp_query_graph;
+-------------------+-----------------------+------+-----+---------+----------------+
| Field             | Type                  | Null | Key | Default | Extra          |
+-------------------+-----------------------+------+-----+---------+----------------+
| id                | mediumint(8) unsigned | NO   | PRI | NULL    | auto_increment |
| hash              | varchar(32)           | NO   |     |         |                |
| snmp_query_id     | mediumint(8) unsigned | NO   | MUL | 0       |                |
| name              | varchar(100)          | NO   |     |         |                |
| graph_template_id | mediumint(8) unsigned | NO   | MUL | 0       |                |
+-------------------+-----------------------+------+-----+---------+----------------+
```

**Comment by netniV** [comment]
OK, so I think the cause of this is a failure to reset the $save variable.  Thus it still have left over elements from one of the linked tables that was being duplicated.  It does mean that the duplication would not have worked fully so you should remove the duplicates and recreate once you get the latest development code.  

If you are still running 1.1.38, then you can apply a fix yourself by adding an `unset($save)` just inside the `foreach` above the erroring `sql_save()` line.

**Comment by arno-st** [comment]
No I'm testing 1.2 beta 2

**Comment by netniV** [comment]
@arno-st have you had a change to test this yet?

**Comment by arno-st** [comment]
I try to upgrade with the develop code and get that:
Fatal error: Cannot redeclare exec_poll() (previously declared in /usr/share/cacti/lib/poller.php:28) in /usr/share/cacti/lib/poller.php on line 52

**Comment by arno-st** [comment]
Oups sory my mistake
ok it' solve at least with the code of October 29
You can close it

**Comment by ddb4github** [comment]
> Oups sory my mistake
> ok it' solve at least with the code of October 29
> You can close it

No. It is not resolved.   root cause is lib/installer.php include lib/poller.php again. should use include_once.

**Comment by netniV** [comment]
Err, that has nothing to do with the error reported in this issue.
