### ISSUE TITLE
wrong message shows when save a device..

### ISSUE THREAD

**Issue by vishnubraj** [Cacti/cacti#2128]
Cacti version 1.2.0 beta 1
Please find the below pic.. 

![screenshot 2018-10-29 at 7 38 06 pm](https://user-images.githubusercontent.com/11851188/47655118-51edca00-dbb2-11e8-9d10-2275580d9637.png)

**Comment by netniV** [comment]
Can you please review your cacti log (CLOG) as there will likely be a stack trace there that shows a problem.  Can also provide the steps or a small gif of the action you were performing?

**Comment by netniV** [comment]
Can you provide the following information:

- OS & Version
- PHP Version
- If applicable:
   - Backtrace
   - Plugin name/version

Also, are there any errors in the web server log and/or cacti log?

**Comment by vishnubraj** [comment]
I could not find a strace for this in the logs..

OS version : CentOS Linux release 7.4.1708 (Core)
PHP version:  PHP 7.1.18


![cacti_save_error](https://user-images.githubusercontent.com/11851188/47658867-c7a96400-dbb9-11e8-99ce-f78f13e3fe11.gif)

**Comment by netniV** [comment]
If you have any plugins enabled, can you temporarily disable them one by one and see if the problem disappears.  If so, it may be plugin related.

**Comment by arno-st** [comment]
Hi saw the same issue

**Comment by cigamit** [comment]
Seems like maybe the stacking of messages may not be working.

**Comment by pautiina** [comment]
![image](https://user-images.githubusercontent.com/11805503/48208028-9e879100-e37a-11e8-9b26-77f114f41807.png)
But tholds graphs created normally

**Comment by cigamit** [comment]
This has been resolved as of today.  It's a 1.2 beta issue caused by the restructuring of the error message handling.
