### ISSUE TITLE
Problem parsing Multi SNMP OIDs

### ISSUE THREAD

**Issue by vishnubraj** [Cacti/cacti#2129]
I recently upgraded to 1.2.0.. after this i am getting the bellow error for some of the devices..

Can you please check this....

![screenshot 2018-10-29 at 8 33 37 pm](https://user-images.githubusercontent.com/11851188/47659051-16ef9480-dbba-11e8-8c1f-743f1623b192.png)

**Comment by cigamit** [comment]
No feedback.
