### ISSUE TITLE
[1.2.0 Beta 2] Device Template menu (and others?) arrow key scrolling issue

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#2130]
Using the arrow keys to scroll through the device template menu (and possibly other menus) the highlighted option does not advance to the next option when the list scrolls ... it jumps a few selections backwards.
![peek 2018-10-29 12-00](https://user-images.githubusercontent.com/12864741/47670288-6ca04e80-db72-11e8-964a-dd0c5fc10f9c.gif)

**Comment by eschoeller** [comment]
Hmm, indeed it is. I guess for some reason that seemed counter-intuitive and rather frustrating to me!

**Comment by netniV** [comment]
Yeah common I’m afraid as I hit that all the time. Hence I knew immediately upon watching.

**Comment by netniV** [comment]
That is common UI issue not limited to Cacti

**Comment by netniV** [comment]
It's a UI issue i've seen on the web and native apps.  Whilst we could potentially write code for it, I don't feel it's really worth that effect given it's the browsers default mode and it only takes a small movement of the mouse whilst the drop down is open to make it work properly.

**Comment by eschoeller** [comment]
Yep, I understand. Certainly a lot of other things to focus on right now.
