### ISSUE TITLE
[1.2.0 Beta 2] Cannot delete devices

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#2131]
I tried to delete a device. It stayed in the device list but the hostname and description were blank. I highlighted it again and selected delete. It disappears briefly, but upon a reload it pops back up:
![image](https://user-images.githubusercontent.com/12864741/47677744-9020c480-db85-11e8-946f-f73051f486f0.png)

**Comment by eschoeller** [comment]
Can't explain how, but I tried deleting these devices again tonight and I finally got them to go away. I think I used Firefox this time, as opposed to Chrome the first time. If that would even have any impact... 
If I can find another couple devices I don't need I'll try between the two browsers and see if I can recreate this.

**Comment by cigamit** [comment]
Let us know if it was from a remote data collector.

**Comment by eschoeller** [comment]
uh, shucks I don't remember. I know I tried to delete them from the main data collector, I never do work directly on the remote ones. But were they devices associated with a remote data collector at the time? Gosh I don't know. 
For what it's worth I just found another device I don't care much about and it's been running on a remote data collector. I removed it via the main data collector interface and it was gone. But, a couple minutes later I got that blank entry again pop up on the device (host.php) list on the main data collector GUI. So, it looks like this is reproducible, and as you suspected it's a problem with devices that are assigned to remote collectors. 
If you come up with a fix I can test it, as it seems like I can easily reproduce it now (and probably have a few more devices I wouldn't mind axing)
I'll leave this device in the half-deleted state, in case you want any more info from it.

**Comment by eschoeller** [comment]
heh, I also have a background audit script that runs every 15 minutes and here's what it had to say about the deletion:
```
# IP ADDRESS CHANGES #
NAME: hostXXX	NEW IP: 	OLD IP: hostXXX.int.colorado.edu

# HOST TEMPLATE CHANGES #
NAME: hostXXX	NEW TEMPLATE: 0		OLD TEMPLATE: 46

# HOSTNAME CHANGES #
OLD: hostXXX	 NEW:
```

**Comment by cigamit** [comment]
It's almost as if the main Cacti server is unable to talk to the remote.  And the log's are clear?

**Comment by cigamit** [comment]
This might have something to do with your automation too.

**Comment by cigamit** [comment]
Okay, figured this one out.  It is resolved now.

**Comment by eschoeller** [comment]
Still broken in 1.2.0 - Beta 4.
