### ISSUE TITLE
1.1.38 Does not display 95 values after adding a multiport aggregate graphic，1.2 Is there a problem?

### ISSUE THREAD

**Issue by ryswork1993** [Cacti/cacti#2132]
![image](https://user-images.githubusercontent.com/44529247/47690686-f6f7b980-dc29-11e8-8f20-a485001728aa.png)
![image](https://user-images.githubusercontent.com/44529247/47690214-23123b00-dc28-11e8-9fac-da7076f755b5.png)
![image](https://user-images.githubusercontent.com/44529247/47690313-95831b00-dc28-11e8-81eb-d9a073b6b3af.png)
1.1.38 Does not display 95 values after adding a multiport aggregate graphic，1.2 Is there a problem?

**Comment by ryswork1993** [comment]
1.1.38 Does not display 95 values after adding a multiport aggregate graphic，1.2 Is there a problem?

**Comment by cigamit** [comment]
This should be resolved already in 1.2.  Please install a test system with 1.2, and if it's not resolved to your satisfaction, please open another ticket.  Will want to see screen shots.
