### ISSUE TITLE
[1.2.0 Beta 2] cacti log rotation should keep file ownership and permissions

### ISSUE THREAD

**Issue by mortenstevens** [Cacti/cacti#2134]
Hello,

Just testing cacti 1.2.0-beta2 for building Fedora packages. In Fedora and Fedora-EPEL we use cacti:apache as owner for /var/log/cacti/cacti.log. The internal cacti log rotation changes it to cacti:cacti after rotating log files.

Is it possible to keep the the predefined file permissions (cacti:apache) set by our RPM packages?

Thank you.

Best regards,

Morten

**Comment by netniV** [comment]
The permissions would be inherited by from the folder I would have imagined.  What permissions are you seeing?

**Comment by mortenstevens** [comment]
@netniV 

Yes, the new owner (after cacti rotates the logfiles) is cacti:cacti, but it should be cacti:apache since httpd needs permissions to access cacti logfiles. 

The folder permission for /var/log/cacti is also set to cacti:apache.

Another question: Normally, we were using our own log rotation for Fedora and RHEL (EPEL).  I guess for some distributions it would be overall better to use our own log rotation. Is is possible to turn cacti log rotation off by default?

Best regards,

Morten

**Comment by netniV** [comment]
Log rotation is a setting within Cacti and could be turned off with a simple MySQL statement.  If you are using your own log rotation, it MUST keep to the filenames that we are generating with our rotation or users will not be able to view the logs from the site for previous days.

I think we should implement the ownership status since others who install manually may not apply log rotation via commands like `logrotate` etc.

**Comment by netniV** [comment]
OK, so I have reviewed this and we do appear to be populating the owner/group.  

```php
if ($owner !== false) {
        $ext = $date->format('Ymd');

        if (file_exists($log . '-' . $ext)) {
                $ext_inc = 1;
                while (file_exists($log . '-' . $ext . '-' . $ext_inc) && $ext_inc < 99) {
                        $ext_inc++;
                }
                $ext = $ext . '-' . $ext_inc;
        }

        if (rename($log, $log . '-' . $ext)) {
                touch($log);
                chown($log, $owner);
                chgrp($log, $group);
                chmod($log, $perms);
```

**Comment by netniV** [comment]
There is a chance that the website would create a new cacti log before the poller had finished.

**Comment by mortenstevens** [comment]
@netniV 

Yes, I can fully understand that for "normal" users installing cacti to the default webserver directory it's a nice feature that the internal cacti logrotation is turned on by default.

But I'm packaging cacti rpms for Fedora and Fedora-EPEL and we are using our own log rotation by default. More details about our RPM packaging for Fedora: https://src.fedoraproject.org/rpms/cacti

But we can switch to cacti's logrotation, if cacti will keep our file permissions.

Best regards,

Morten

**Comment by mortenstevens** [comment]
> OK, so I have reviewed this and we do appear to be populating the owner/group.
> 
> ```
> if ($owner !== false) {
>         $ext = $date->format('Ymd');
> 
>         if (file_exists($log . '-' . $ext)) {
>                 $ext_inc = 1;
>                 while (file_exists($log . '-' . $ext . '-' . $ext_inc) && $ext_inc < 99) {
>                         $ext_inc++;
>                 }
>                 $ext = $ext . '-' . $ext_inc;
>         }
> 
>         if (rename($log, $log . '-' . $ext)) {
>                 touch($log);
>                 chown($log, $owner);
>                 chgrp($log, $group);
>                 chmod($log, $perms);
> ```

Thank you. Looks good.

**Comment by mortenstevens** [comment]
> I'm guessing the new owner/group are cacti:cacti? That's not strictly permissions btw ;-)

Of course,  file ownership and permissions :) Updated the subject.

**Comment by netniV** [comment]
There is one thing I have though of.  If the file is not present, it will default to the users primary group, which is normally the user themselves.  So, if cacti is in the apache group, it should probably have that as it's default primary group.

Additionally, you may want to create a cacti.log file with the appropriate permissions, so they are replicated on rotation.

**Comment by mortenstevens** [comment]
@netniV 

When installing the cacti rpm it will initially create an empty cacti.log file with the correct file ownership cacti:apache.

But I'm not sure if this is enough if the user cacti runs the cronjob to keep cacti:apache as owner after the cacti cronjob has rotated the logfiles?

**Comment by netniV** [comment]
It should be as long as the filegroup() returns the correct group to the PHP script.  And that we are able to set that with the chgrp() because we use touch() to create the new file immediately after renaming a log.

**Comment by netniV** [comment]
Hi Morten, 

Am I right in thinking that you seem to be maintaining the Cacti RPM's for Fedora? Could you send me an email to netniv@cacti.net to discuss some things regarding them?

Thanks,

Mark.

**Comment by mortenstevens** [comment]
Hi Mark,

Yes, I sent you an email.

Best regards,

Morten

**Comment by cigamit** [comment]
Morten, I'm guessing you are trying to use /etc/logrotate.d/cacti to do this.  It does make sense.  From a packaging perspective, this may make sense.  Please confirm.  If you are working at finalizing the pre and post scripts, I would be willing to introduce a new option 'Use logrotate setting' rotation option to make it clearer.  They might conflict though.

**Comment by netniV** [comment]
Simply turning Log Rotation off via the setting would be enough as long as there was a logrotate.d entry.

**Comment by mortenstevens** [comment]
@cigamit 
@netniV 

Yes, for Fedora and Fedora-EPEL we are using /etc/logrotate.d/cacti to rotate cacti logfiles. 

It would be great for us (and I guess also for other linux distros) to have an option to turnoff cacti's own logrotation when installing the cacti RPM package.

**Comment by netniV** [comment]
Running the following will disable logrotation:
```sql
REPLACE INTO settings VALUES ('logrotate_enabled', '');
```

**Comment by mortenstevens** [comment]
@netniV 

We can't execute sql commands during cacti rpm package installation, because Fedora users installing cacti (dnf install cacti) have to setup the database (dbname/username/password) themselves.

**Comment by mortenstevens** [comment]
@netniV 

Yes, we can use a distro specific patched cacti.sql file with the logrotation setting disabled by default for Fedora.

Btw: Here are our installation instructions for users installing the cacti rpm package:
https://src.fedoraproject.org/rpms/cacti/blob/master/f/cacti.README.fedora

**Comment by netniV** [comment]
Then if you have that setting disabled by default, we would not provide it.  Are you looking for a way to also suppress the user from enabling that setting as well?

**Comment by mortenstevens** [comment]
@netniV 

I think we just need a way to have cacti's logration turned off by default after users installing our RPM packages. So we have to patch the cacti.sql as shipped with our RPM packages, right?

**Comment by netniV** [comment]
Yes.  That is the simplest way.  By default, we do not insert any settings into the settings table until the installer is run.  If the setting already exists, it should keep it.

**Comment by mortenstevens** [comment]
@cigamit 
@netniV 

After thinking about it, I guess it would be better for users and distros to move the log rotation option to config.php or turn if off by default. Is that possible?

Actually, I think it's not a good idea to maintain a distro specific downstream patch against cacti.sql.

**Comment by netniV** [comment]
@mortenstevens 	

Debian currently do exactly that.  @paulgevers also initialises the database and secures the users used which is a stage above what you do.  He even runs his own tests to ensure that the log files are only outputting information he expects.

**Comment by netniV** [comment]
You could keep any specific modificaitons in a separate file that is just append to the end of the cacti.sql file since you are only updating the settings table.

**Comment by paulgevers** [comment]
> You could keep any specific modificaitons in a separate file that is just append to the end of the cacti.sql file since you are only updating the settings table.

That is indeed more or less what I do.

**Comment by cigamit** [comment]
I've resolved this issue by adding a config.php.dist option $disable_log_rotation = true;  If that setting is set to true, then log rotation will be disabled from the Cacti poller_maintenance.php script and the user interface.  @paulgevers and @mortenstevens please note.

**Comment by mortenstevens** [comment]
@cigamit 

Thank you. That makes it much easier for us.

**Comment by paulgevers** [comment]
@cigamit thanks
