### ISSUE TITLE
api_tree_lock() and api_tree_unlock() forcing redirection incorrectly

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#2135]
Both api_tree_lock() and api_tree_unlock() are forcing a UI redirection if the runtime is in web mode.  This is incorrect as API's should be redirecting.  As a result, some plugins (eg, cycle) can be forced to redirect to another page when they are simply meant to be displaying graphs.

It is up to the caller of these functions to redirect if they are in web mode.

Additionally, the Location: value is incorrect as it does not include the $config['url_path'] prefix to redirect to the correct page and can result in 404 errors if this occurs within a plugin since the browser will take its location, ignoring the chdir(../../) that a plugin may apply.

**Comment by cigamit** [comment]
Resolved.

**Comment by netniV** [comment]
I think this needs to be taken further as it also appears to affect other API calls.  API calls should NOT be forcing redirection, that should occur at the caller level.

**Comment by cigamit** [comment]
Agreed and resolved.
