### ISSUE TITLE
Unsaved Changes Detected in Settings-->MailReporting

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#2136]
It gets all the time.

Browser: Chrome,
Branch: develop/synchronized,

Just click Settings-->MailReporting and then some other panel for example "General".

**Comment by pautiina** [comment]
Write here https://github.com/Cacti/cacti/issues/1826

**Comment by netniV** [comment]
Yes, please add this to the issue @pautiina has linked.  We can then track it as a repeated task.
