### ISSUE TITLE
php audit_database.php --repair

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#2137]
php audit_database.php --repair

```
Executing : ALTER TABLE `data_local` ADD INDEX `snmp_index` (`snmp_index`) USING BTREE - Success
Executing : ALTER TABLE `poller_reindex` MODIFY COLUMN `arg1` varchar(255) NOT NULL DEFAULT '' - Success
Executing : ALTER TABLE `poller_resource_cache` MODIFY COLUMN `path` varchar(191) DEFAULT '' - Success
Executing : ALTER TABLE `user_auth_cache` ADD INDEX `hostname` (`hostname`) USING BTREE - Success
Executing : ALTER TABLE `user_auth_cache` ADD PRIMARY KEY BTREE (`id`) USING BTREE - Failed
Executing : ALTER TABLE `user_auth_cache` ADD UNIQUE INDEX `tokenkey` (`token`) USING BTREE - Failed
Executing : ALTER TABLE `user_auth_cache` ADD INDEX `user_id` (`user_id`) USING BTREE - Success
```

and in logs:

```
2018/10/31 17:53:45 - CMDPHP SQL Backtrace: (/cli/audit_database.php[65]:repair_database(), /cli/audit_database.php[102]:db_execute(), /lib/database.php[188]:db_execute_prepared())
--
2018/10/31 17:53:45 - CMDPHP ERROR: A DB Exec Failed!, Error: Specified key was too long; max key length is 767 bytes
2018/10/31 17:53:45 - CMDPHP SQL Backtrace: (/cli/audit_database.php[65]:repair_database(), /cli/audit_database.php[102]:db_execute(), /lib/database.php[188]:db_execute_prepared())
2018/10/31 17:53:45 - CMDPHP ERROR: A DB Exec Failed!, Error: Key column 'id' doesn't exist in table

```

**Comment by cigamit** [comment]
Yea, I know some people that have a much long snmp_index.  I think this issue needs to be resolved before release.  Thanks for catching.

**Comment by cigamit** [comment]
There is something wrong with your table user_auth_cache.  Can you please run the following command:

`mysql cacti -e 'desc user_auth_cache'`

**Comment by cigamit** [comment]
Sorry, this was not the issue I thought it was.  There is another audit issue that does need to be resolved.  This issue is still not validated.

**Comment by netniV** [comment]
Since this is a replication issue, are both systems running the same version of MySQL/MariaDB?

**Comment by interduo** [comment]
We use: Server version: 10.1.26-MariaDB-0+deb9u1 Debian 9.1

@cigamit 

+-------------+------------------+------+-----+-------------------+-------+
| Field       | Type             | Null | Key | Default           | Extra |
+-------------+------------------+------+-----+-------------------+-------+
| user_id     | int(10) unsigned | NO   | MUL | 0                 |       |
| hostname    | varchar(100)     | NO   | MUL |                   |       |
| last_update | timestamp        | NO   | MUL | CURRENT_TIMESTAMP |       |
| token       | varchar(1024)    | NO   |     |                   |       |
+-------------+------------------+------+-----+-------------------+-------+

**Comment by cigamit** [comment]
@interduo, Since your table structure is pre 1.x release (thanks for all your help by the way), I am going to suggest that for now you just drop and re-add the user_auth_cache table.  This is a pretty narrow corner case for now.  So, closing.
