### ISSUE TITLE
[1.2.0 Beta2] Error on automation: creation of a new tree rule

### ISSUE THREAD

**Issue by arno-st** [Cacti/cacti#2139]
When I try to create a new tree rule, as soon as I change the leaf item type to equipment, i got an error, and I can't create my tree rule

Change Leaf Type

WARNING:You are changing the leaf type to "Device" which does not support Graph-based object matching/creation.By changing the leaf type, all invalid rules will be automatically removed and will not be recoverable.

Are you sure you wish to continue?

And then when you clique continue then name is cleared and setting is set back as new (no name, default tree and graphics)

To resolve this issue, I have to set a name, save it, then re-open it and change the setting after that

**Comment by cigamit** [comment]
Good catch.  I actually noted this false error as well, but forgot to log it.  It happens for new items.  Let me see if I can fix it now.

**Comment by cigamit** [comment]
Resolved.
