### ISSUE TITLE
Getting an error creating a user, stills shows "permission" tabs, etc.

### ISSUE THREAD

**Issue by groentebroer** [Cacti/cacti#214]
Some comments when creating a user.

* Error messages are shown very short, maybe a little longer (especially when you have multiple error messages)
* When you get an error any entered data is lost. (I can understand it for the password fields, but other fields should be left filled in as they were?)
* When getting an error, still the "persmission" tab, (and other settings for that user) show up. (This should not happen, because no actual user is created to set any permissions for.)

**Comment by cigamit** [comment]
Increased the duration.  Still have to look at the other two issues.

**Comment by cigamit** [comment]
I have resolved the third part of this issue.  However, I can not reproduce the second.  For me, if I create a bogus user, all other form values are retained.  Please confirm.  Maybe you clicked on of of those bogus tabs?

**Comment by cigamit** [comment]
Closing.  Please re-open if you are able to reproduce the error.  If you able to reproduce, we'll need some specific step by step instructions.

**Comment by groentebroer** [comment]
Updated to latest GIT commit.

* Logged in as Admin.
* Go to users
* Click add
* Enter a username and a full name
* Press "must change password at next login" (Do not enable "change password")

An error is thrown that changing the password must be enabled, to let the user change the password at next login.
Attached a small video to display the issue.

[cacti_user_creation_issue.zip](https://github.com/Cacti/cacti/files/710545/cacti_user_creation_issue.zip)

Using FireFox 50.1.0 on Windows 10

**Comment by groentebroer** [comment]
Hi @cigamit I am not able to re-open an item which I have not closed myself. Can you re-open it?

**Comment by cigamit** [comment]
I'm still getting used to the issue tracker.  The requester should be able to re-open.  That's a personal opinion though.

**Comment by cigamit** [comment]
I've resolved this corner case through JavaScript.  Thanks for adding it.  Feel free to open a new issue if you find more issues.
