### ISSUE TITLE
[1.2.0 Beta 2] MySQL aborted connections (error writing communication packets)

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#2141]
I am getting these in a mysql log, near the beginning of every polling cycle, only on a master poller. 
```
[Warning] Aborted connection 92380 to db: 'cacti' user: 'apache' host: 'localhost' (Got an error writing communication packets)
```

I turned on query logging. In each case this is the transaction log for that connection:
```
92380 Connect   apache@localhost on cacti
                92380 Query     SET SESSION sql_mode = (SELECT REPLACE(@@sql_mode,'NO_ZERO_DATE', ''))
                92380 Query     SET SESSION sql_mode = (SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY', ''))
                92380 Query     SHOW COLUMNS FROM host LIKE 'poller_id'
                92380 Query     SHOW COLUMNS FROM host LIKE 'device_threads'
                92380 Query     SELECT id, device_threads FROM host WHERE disabled='' AND id BETWEEN 0 AND 713 AND host.poller_id=1 ORDER BY polling_time DESC
                92380 Query     INSERT INTO poller_time (poller_id, pid, start_time, end_time) VALUES (1, 16402, NOW(), '0000-00-00 00:00:00')
                92380 Query     SELECT COUNT(*) FROM poller_item WHERE host_id=693 AND rrd_next_step <=0
                92380 Query     SELECT COUNT(*) FROM poller_item WHERE host_id=480 AND rrd_next_step <=0
```
Any ideas? Maybe a problem with host_id 480?

I knocked down my thread count across all my data collectors. I doubled wait_timeout to 57600. I quadrupled max_allowed_packet to 16777216. Still getting the errors.

**Comment by eschoeller** [comment]
I disabled host_id 480. It was in a 'down' state, and it was the first device (in sequential order) that was not 'up' or 'disabled'. Now the output from the query log has changed slightly, and varies a bit more:
```
189597 Connect  apache@localhost on cacti
                189597 Query    SET SESSION sql_mode = (SELECT REPLACE(@@sql_mode,'NO_ZERO_DATE', ''))
                189597 Query    SET SESSION sql_mode = (SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY', ''))
                189597 Query    SHOW COLUMNS FROM host LIKE 'poller_id'
                189597 Query    SHOW COLUMNS FROM host LIKE 'device_threads'
                189597 Query    SELECT id, device_threads FROM host WHERE disabled='' AND id BETWEEN 0 AND 713 AND host.poller_id=1 ORDER BY polling_time DESC
                189597 Query    INSERT INTO poller_time (poller_id, pid, start_time, end_time) VALUES (1, 51708, NOW(), '0000-00-00 00:00:00')
                189597 Query    SELECT COUNT(*) FROM poller_item WHERE host_id=693 AND rrd_next_step <=0
                189597 Query    SELECT COUNT(*) FROM poller_item WHERE host_id=677 AND rrd_next_step <=0
                189597 Query    SELECT CEIL(COUNT(*)/6) FROM poller_item WHERE host_id=677 AND rrd_next_step <=0
                189597 Query    SELECT COUNT(*) FROM poller_item WHERE host_id=677 AND rrd_next_step <=0
```

**Comment by netniV** [comment]
The host being down shouldn't be an issue as all communication between SQL and Cacti should be done when the device isn't being queried for data.  However, it can be because the server has not received any input from the open DB connection in a given period of time.

Percona (who write some cacti and nagios scripts) actually have a blog about this issue that's worth a read.

https://www.percona.com/blog/2016/05/16/mysql-got-an-error-reading-communication-packet-errors/

**Comment by eschoeller** [comment]
Yes, I found that article and perused it for awhile, which is where I got some of the ideas for the mysql configuration changes. I could not, for the life of me, find out where in the code these particular SQL queries are coming from. I figured the CEIL(COUNT(*)/6) would be very unique, but I can't find it anywhere. 

So I went about it another way, and looked at host_ids referenced in these queries. I have traced this issue back to what I believe is a single device. So, this is likely a "personal" problem. Moreover, it's a device template that I created. If I disable the device the aborted connections disappear. Also, if I move the device to a remote poller (which can still access the device) the aborted connections also disappear. It's only when this device is enabled and running on the main poller that I see these aborted connections. The query log for the aborted connection isn't always the same, but after hunting down the individual host_ids referenced in the aborted queries I finally found the culprit. 
Here is the configuration of the device:
![image](https://user-images.githubusercontent.com/12864741/47949187-3cef9e80-df04-11e8-97d3-4dad8da275ea.png)
The device has 5 Script/Command data input methods associated with it. It does not use SNMP. I don't think I did anything wrong by creating this device template and associated graph/data templates and data input methods. I don't necessarily want to write it off because it could affect other people who create templates like this. Not sure where to go from here yet.

**Comment by eschoeller** [comment]
I switched the Ping Method to UDP Ping. While I still got one aborted connection, it appears this was a dsstats related query that got tripped up. Otherwise I was getting about 2 of these messages per polling cycle and after switching to UDP I've gone 10 polling cycles with no problems. 
So I could refer to this as "MySQL Aborted Connections while using Ping/ICMP Ping downed device detection on RHEL Workstation release 6.10"

**Comment by eschoeller** [comment]
The endpoint device is a windows machine. I don't recall the version.

**Comment by netniV** [comment]
I am going to suggest that you share your DB with us. You’ve had a number of issues which seem to be revolving around your personal data. If you could email developers@cscti.net with details for the dump that would be good. This will allow us to more quickly analyse the data next week.

**Comment by eschoeller** [comment]
I appreciate the offer to look at this. I’ve probably been carrying along this db for 8+ years. I’ve done the best I can to keep it in one piece:) Is the email address developers@cacti.net or cscti.net?

**Comment by netniV** [comment]
cacti, my mac likes to eat keys :)

**Comment by eschoeller** [comment]
I have three data sources which appear in the poller_item table, but they do not have corresponding entries in the data_local table. I am getting an error indicating an issue with these three data sources on each poller run:
```
POLLER: Poller[1] WARNING: Poller Output Table not Empty.  Issues: 3, DS[59728, 59729, 59730]
```
It doesn't look like running repair_database would identify and fix that. Could also be other lurking issues in there. But this particular problem could be tripping up dsstats for sure.

**Comment by netniV** [comment]
Yes, I would say so.  I'll be talking with others in the group to see their views and come back to you later.

**Comment by cigamit** [comment]
Check the poller_item tables for all your data collectors and see if those local_data_id's exist in one of them.  Also, see if they are in the main pollers poller_item table.  If they are in the poller_item table on the main system, note the device id and see if it still exists.  Let me know what you come back with.

**Comment by eschoeller** [comment]
OK. Those three bad data sources only exist within the poller_item table on the main data collector. There is no trace of them in either the poller_item table or the data_local tables on the remote collectors. The device in question is 127.0.0.1 - and these data sources were part of the cacti user stats template code. I think this was a really old template, and it wasn't working, and I didn't really care about user stats, so on or around 10/20/2018 I removed them. I think I deleted the graphs and instructed Cacti to remove the associated data sources. But they didn't get all the way out I guess. I never had this device associated with any other remote collector since it's specifically designed to be localhost. 
I also wrote a quick script to query all the local_data_id from the poller_item table and verify they exist in the data_local table. The script runs clean on all my remote collectors, but the main data collector fails on just the three aforementioned data sources. So, something went wrong when I deleted these graphs/data sources. It's probably having a cascading effect into other areas of the code now.

**Comment by cigamit** [comment]
What version of MySQL/MariaDB?

**Comment by eschoeller** [comment]
mysql  Ver 14.14 Distrib 5.6.23, for Linux (x86_64) on the main data collector. 
mysql  Ver 15.1 Distrib 10.1.26-MariaDB, for debian-linux-gnu (x86_64) on the remote data collectors

**Comment by eschoeller** [comment]
Very interesting. Hopefully my db admin will be willing to do that.

**Comment by cigamit** [comment]
Pretty sure this is the issue. So, I'll close.
