### ISSUE TITLE
[1.2.0 Beta 2] Installer: innodb_additional_mem_pool_size is DEPRECATED

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#2142]
This option is deprecated, and should probably removed/replaced in the installer. Or the installer should detect the MySQL version and adjust it's suggestions accordingly.
```
InnoDB: Warning: Using innodb_additional_mem_pool_size is DEPRECATED. This option may be removed in future releases, together with the option innodb_use_sys_malloc and with the InnoDB's internal memory allocator
```

**Comment by netniV** [comment]
I will take a look at this and find out which version we need to be ignoring this from.

**Comment by netniV** [comment]
We no longer recommend that option if the version is 5.6 or greater.
