### ISSUE TITLE
Device Management "Status" column does not sort properly

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#2144]
Sorting a list of devices based on 'Status' does not organize the devices by their status. In this screenshot you can see that "Up" devices are mixed in with "Disabled" devices.

![image](https://user-images.githubusercontent.com/12864741/47948891-f2b7ee80-defe-11e8-88a2-1c27bedf9d79.png)

**Comment by netniV** [comment]
To clarify, is this on the host.php listing table?

**Comment by eschoeller** [comment]
Yep, host.php.

**Comment by cigamit** [comment]
Yea, this is due to 'disabled' being a separate column, so it'll never sort well.  I think that this can be fixed, but let's do it after 1.2.

**Comment by eschoeller** [comment]
Sounds good to me. It will be helpful to have it.

**Comment by cigamit** [comment]
We have a bit more time due to some issues, so fixing this one.  @eschoeller if you want this fix earlier, just run the following SQL command:

`update host set status = 0 where disabled="on";`
