### ISSUE TITLE
[1.2.0] Not able to change the process and threads

### ISSUE THREAD

**Issue by vishnubraj** [Cacti/cacti#2146]
When i try to change the number of process and threads in the data collector it is throwing errors..

![cacti_data_collector](https://user-images.githubusercontent.com/11851188/47956116-bb604500-dfc5-11e8-8929-575bb4478c1c.gif)

**Comment by netniV** [comment]
When this fails, there should be a log in the error log

**Comment by vishnubraj** [comment]
No there is no log in the error log.. I tried enable the debug also.. but didnot see any log..

**Comment by netniV** [comment]
Try the following SQL, and see if you can then save:
```sql
ALTER TABLE `poller` 
CHANGE `last_update` `last_update` TIMESTAMP NULL DEFAULT NULL, 
CHANGE `last_status` `last_status` TIMESTAMP NULL DEFAULT NULL, 
CHANGE `last_sync` `last_sync` TIMESTAMP NULL DEFAULT NULL;
```

It should be noted that this is for testing purposes, this shouldn't normally be used as it's not the recommended defaults.

**Comment by cigamit** [comment]
This was resolved in develop here https://github.com/Cacti/cacti/commit/0f60b10f3cfb1bdee803dd2a063bab5fe64f407f#diff-0dbfaaeeca9a17e4a5cfe733fd739138 and here https://github.com/Cacti/cacti/commit/f79fef2e1d4a47e6a9fcc7da3884232bf2f3b37a#diff-0dbfaaeeca9a17e4a5cfe733fd739138

**Comment by cigamit** [comment]
So, simply update to the develop version.

**Comment by netniV** [comment]
Ah yes, I'd forgotten about that one.

**Comment by vishnubraj** [comment]
i updagraded to the latest github release.. and updated the process and thread value to 10,20 , within few minutes cacti server CPU utilization went to 100% and stopped working.. The MYSQL COnnected thread reached 15K.. the same setting was working on old cacti 1.1.38.. is there anything changed?
Can you please check this.. 

![image](https://user-images.githubusercontent.com/11851188/48218356-b299b580-e3af-11e8-8272-318a24c245fc.png)
![image](https://user-images.githubusercontent.com/11851188/48218364-b6c5d300-e3af-11e8-984d-c33cea405f1d.png)
<img width="649" alt="screenshot 2018-11-08 at 11 42 51 pm" src="https://user-images.githubusercontent.com/11851188/48218557-25a32c00-e3b0-11e8-957b-8ecd80ff15a3.png">

**Comment by vishnubraj** [comment]
below kernel message i am getting in cacti.. CPU is still high at 85% now.. 

Nov  8 18:19:33 cacti1a kernel: perf: interrupt took too long (2506 > 2500), lowering kernel.perf_event_max_sample_rate to 79000
Nov  8 18:19:33 cacti1a kernel: [ 1494.971363] perf: interrupt took too long (2506 > 2500), lowering kernel.perf_event_max_sample_rate to 79000

**Comment by netniV** [comment]
It would be good if you could provide a zoomed in version of those first two graphs to see the time period it went over.
