### ISSUE TITLE
Support for Items drag and drop re-ordering

### ISSUE THREAD

**Issue by DoubleBeast** [Cacti/cacti#2147]
When i work on graphs/reports with several items the up/down arrows method for reordering in my opinion could be inefficient, is there a chance of add a drag and drop method for easy reordering those items? or maybe i´m missing a function already present which could be more efficient than the arrows?

Thanks in advance.

**Comment by netniV** [comment]
Drag and drop would be a nice enhancement. We will consider it for a future release but it won’t be in the 1.2 release.

**Comment by DoubleBeast** [comment]
Excellent guys, looking forward to this! thanks!

**Comment by TheWitness** [comment]
This is actually already fixed. So I'm going to go ahead and close now.
