### ISSUE TITLE
1.2 Real-time traffic viewing function automatically disappeared

### ISSUE THREAD

**Issue by ryswork1993** [Cacti/cacti#2148]
![image](https://user-images.githubusercontent.com/44529247/48042109-0d1df080-e1bb-11e8-9030-6a4de9b6233d.png)
Question 1：1.2 Real-time traffic viewing function automatically disappeared
Question 2：Can the aggregated graphics display only one 95 result

**Comment by cigamit** [comment]
You have to enable it in 1.1.38.  See my other comments about 95th ptile.
