### ISSUE TITLE
The sanitize_unserialize_selected_items()  in "lib/functions.php" is not flexible

### ISSUE THREAD

**Issue by YongBoLiu** [Cacti/cacti#2151]
The sanitize_unserialize_selected_items() is too strict checked, that only support numeric.  When the key of the selected item is not numeric (such as string), it will always return false although unserialize is succeed.

How about add a parameter to control checking value or not? As below.

function sanitize_unserialize_selected_items($items, $checkvalue = true) {
	if ($items != '') {
		$items = unserialize(stripslashes($items));

		if (is_array($items)) {
			if($checkvalue){
				foreach ($items as $value) {
					if (is_array($value)) {
						return false;
					}elseif (!is_numeric($value) && ($value != '')) {
						return false;
					}
				}
			}
		}else{
			return false;
		}
	}else{
		return false;
	}

	return $items;
}

**Comment by netniV** [comment]
This function is designed to work with indexed IDs which will always be numerical.

**Comment by TheWitness** [comment]
@YongBoLiu, feel free to create a pull request with either a new function to handle the non-numeric case, or a minor change in the case where your index cannot be numeric.  If updating the current function, the default should be numeric of course.

**Comment by netniV** [comment]
@YongBoLiu, one more thing I will mention is that the value should ALWAYS be checked, even if it's just to make sure it only contains valid AlphaNumeric characters, email address, etc.  

Maybe the optional parameter should be to specify which filter should be applied with a default to numeric.  As @TheWitness said, feel free to create a pull request with the update if it's needed for something else and we can look at including it.

**Comment by YongBoLiu** [comment]
Thanks @netniV @TheWitness , I'll add a new function in our plugin.

**Comment by netniV** [comment]
Look forward to reviewing it.

**Comment by cigamit** [comment]
@YongBoLiu, if you feel like merging this function.  Simply open a pull request.
