### ISSUE TITLE
When editing a device, should show disable/enable option

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#2152]
Unless I missed it, when you edit a device, there is no Disable/Enable device option.  There is on for the debug, etc.  But that can mean that you need to get back to the listing before you can disable a device if you've redirected to the device from the logs for example,

**Comment by cigamit** [comment]
Yea, this feature has been missing for a while.

**Comment by cigamit** [comment]
Just checked, the option is there, but the disable activity was not being executed when the device is disabled.  So, made that update.  Since we have another week before Beta3, taking this time to fix this.

**Comment by netniV** [comment]
Oh, I realised what the issue is, I was expecting it here:

![image](https://user-images.githubusercontent.com/9052188/48350526-68e6ee80-e67f-11e8-9711-209cc62ba77c.png)

When in fact on that page it is:

![image](https://user-images.githubusercontent.com/9052188/48350546-7603dd80-e67f-11e8-8b71-1a901a9aff54.png)
