### ISSUE TITLE
Utilities page issues the wrong hook for tabs

### ISSUE THREAD

**Issue by YongBoLiu** [Cacti/cacti#2153]
I don't understand why api_plugin_hook('user_admin_tab') in both ./user_admin.php and ./utilities.php, but not in auth_profile.php.

Why input it in ./utilities.php after 'Technical Support' clicked? Any reason can share?

I think we'd put api_plugin_hook('user_admin_tab') in ./user_admin.php and auth_profile.php is more valuable.

**Comment by netniV** [comment]
At first I thought the hook was being called correctly from utilities but it would appear to be the wrong hook name called from utilities when looking at the [Plugin Hook API Ref](https://github.com/Cacti/documentation/blob/develop/Plugin-Hook-API-Ref.md).  Therefore I have renamed the utilities one to 'utilities_tab' and created a new documented entry in the API ref.

With regards to auth_profile.php, that utilises the $settings_user global array and does not provide the option of tabs.  It is purely settings focused, not permissions.  

When creating a plugin, any custom settings are normally inserted during plugin initialisation include the tab those settings should appear on.  One thing to note though is that auth_profile does not display things in tabs, but adds a header separator for each tab.

**Comment by YongBoLiu** [comment]
Thanks for the response. @netniV .

So, for a normal user, who has no 'User Management' permission, he only can edit his settings from $settings_user on auth_profile.php. 

But the auth_profile.php is ugly when the setting options is huge. I strongly suggest to change it to tab style and add a hook. This will help look and feel when so many plugins may have setting options.

**Comment by YongBoLiu** [comment]
Even the auth_profile.php  can shrink/collapse, a hook of tab is more flexible because plugins can have its own setting DB tables. Better for plugin to install/uninstall and clean its data, not all setting data in settings_user table.

**Comment by netniV** [comment]
Whilst I would agree that the single continuous page isn’t the greatest looking, off the top of my head you would also have to handle 

- changes to read_user_setting which allows for caching of the settings from the DB for user specific stuff, 
- $settings_user is used by the user edit page to allow an admin to edit a users settings. 

Currently all a plugin need do is update the array.  By the hook method it would also need to implement the drawing, validating and updating of those settings. 

If you can create a PR for what you propose then we can review it.

**Comment by ddb4github** [comment]
table settings_user include three field(user_id, name, value). It is not friendly for plugins that include duplicate name cross plugin.

suggestion is:
-   Open a hook to enable plugin-manage-settings-by-self in auth_profile.php
-   Or add extra field 'plugin name' into table settings_user
