### ISSUE TITLE
[1.2.0 Beta 2] Main and remote poller installation

### ISSUE THREAD

**Issue by jpobeda** [Cacti/cacti#2154]
Hi there,

I've setup a main poller on CentOS7 all good and running

Installation dir is

`/var/www/html/cacti-1.2.0-beta2`

Then I installed a remote poller under another vm on CentOS7, all good BUT

It looked like the installation finished, yet the screen got stuck here. I could see the remote poller on my main poller console and ran the first cycle and everything.

![2018-11-08_14-20-52](https://user-images.githubusercontent.com/13456559/48171825-70965280-e362-11e8-83bb-a62dfe6699c8.png)

I went and opened a new tab and browse to the remote poller and I got

`System log file is not available for writing, please enable write access Log: /var/www/html/cacti-1.2.0-beta2/log/cacti.log `

It looks like the remote poller has got main poller's path settings since remote poller installation directory is `/var/www/html/cacti/`

MUST these two have to have exactly the same installation paths? 

I know it's easy to workaround but that's not the question.

Fresh install on both btw

**Comment by netniV** [comment]
We have been experiencing issues when we took out the paths section of variables to allow for different OS syncing as it did not set the spine path whilst enabling the spine settings. The recommendations are to have the same arch and layout across pollers

**Comment by cigamit** [comment]
Right now, we require a uniform name space.  It's not optional.  So, Cacti has to be installed in the same paths presently.  After 1.2 we will look at other options.

**Comment by tg12** [comment]
**System log file is not available for writing, please enable write access Log: /var/www/html/cacti/log/cacti.log**

Same error with fresh install of 1.2, Ubuntu 18.10 brand new fresh server as well,

**Comment by lux4rd0** [comment]
Just trying out a remote poller for the first time and I hit this same issue. Disabling SELINUX solved this for me...
