### ISSUE TITLE
[1.2.0 Beta 2] User Permission Layout Issue

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#2155]
The layout of permissions needs to be corrected as it can lead to confusion over which permission is on/off due to wrapping.

![image](https://user-images.githubusercontent.com/9052188/48192262-3071a880-e33f-11e8-82a8-02c39d794b98.png)

**Comment by cigamit** [comment]
We need to convert those nasty buttons to toggles.

**Comment by cigamit** [comment]
Resolved.
