### ISSUE TITLE
Add Location List Editing Capabilities

### ISSUE THREAD

**Issue by jmtig** [Cacti/cacti#2156]
Currently, DESCRIPTION and HOSTNAME are displayed in email alerts. It would be great to see the LOCATION of the device as well.  

Please add the capability to allow the location field, in Management > Devices > General section, to be configured in the down device message and/or recovering device message fields in Configuration > Settings > Thresholds.

Thanks in advance.

**Comment by cigamit** [comment]
This would be a feature request.  Right now the locations that appear for a site are a function of the locations you enter at the device level.  It's not a traditional Cacti thing where you manage that list independently.

**Comment by TheWitness** [comment]
@jmtig, can you please open an issue on the thold issue list and in the monitor issue list.  The feature enhancement to filter and mass change on the Device page is completed.  However, the other features need to go into their respective plugin issue lists.
