### ISSUE TITLE
Hook 'auth_profile_tabs' should be function not method

### ISSUE THREAD

**Issue by YongBoLiu** [Cacti/cacti#2158]
It seems we need to change 
api_plugin_hook('auth_profile_tabs');
To
api_plugin_hook_function('auth_profile_tabs', $tabs);

Because  $tabs is set before loop check the $tab, and api_plugin_hook() is in the middle. If call api_plugin_hook() without param, we can't change $tabs, then the loop logic is no useful.

**Comment by netniV** [comment]
This has now been committed to the development code.
