### ISSUE TITLE
Charts do not render for Ubuntu/Debian using Cacti package

### ISSUE THREAD

**Issue by Axel577** [Cacti/cacti#2159]
Ubuntu versions in cacti repository don't update the Chart.js file. There might be some problems. One porblem occurs when using intropage plugin.
The file is located in /usr/share/cacti/site/include/js/ directory

**Comment by netniV** [comment]
It’s in hand. I’ll update this fully tomorrow

**Comment by netniV** [comment]
The crux of this is that @Axel577 reported issues with the Intropage plugin having errors and not displaying things properly.  Whilst providing a minor fix to the javascript for it, it was also noticed that he didn't have charts were others did.

https://github.com/xmacan/plugin_intropage/issues/45

After trying to ensure that he had the data that was supposed to be returned, checking that the symlink worked, and ensuring that the browser was receiving the correct code, @paulgevers noticed that @Axel577 had shown the outputted Chart.js file was showing version 1.0.2.

I had Axel download directly from our development version and this rectified the issue and charts were being displayed.

So, whilst this is not a cacti bug, it is a third party packaging issue and has been filed here:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=913385

I have notified @paulgevers of the bug report.

Thanks,

Mark.

**Comment by netniV** [comment]
I'm reopening this as it's still an outstanding issue with the Debian packaging system.

**Comment by netniV** [comment]
Received an update email this morning:
```
gitlab was locked to 1.0.2, but they have also moved to 2.7.2 so I will
update soon. Can someone check if python3-ontospy is also compatible?

$ reverse-depends libjs-chartjs
Reverse-Depends
===============
* cacti
* ocsinventory-reports
* python3-ontospy
* ruby-rails-assets-chartjs

 reverse-depends -b libjs-chartjs
Reverse-Build-Depends
=====================
* ontospy
```

**Comment by netniV** [comment]
Received an update

> I have uploaded 2.7.3 to experimental. Since browserify is not available in the archive, I have used rollup to build the umd bundle. Please review, test and confirm if it is working as expected and I can upload to unstable.

And the bug tracker was updated with:

> Source: node-chart.js
> Source-Version: 2.7.3+dfsg-1
>
> We believe that the bug you reported is fixed in the latest version of node-chart.js, which is due to be installed in the Debian FTP archive.
> 
> A summary of the changes between this version and the previous one is attached.
> 
> Thank you for reporting the bug, which will now be closed.  If you have further comments please address them to 896468@bugs.debian.org, and the maintainer will reopen the bug report if appropriate.
>
> Debian distribution maintenance software
> pp.
> Pirate Praveen <praveen@debian.org> (supplier of updated node-chart.js package)

@paulgevers - I believe that is now in experimental, do you know how long that will take it to get over to stable?  I’m presuming that you need it to be in stable?

**Comment by paulgevers** [comment]
Pirate explicitly asked people to test it. That would be a great add. With positive feed-back he may quickly push it to unstable. Yes, Cacti needs this in buster (= the next stable).

**Comment by netniV** [comment]
Is there an experiential cacti package that uses it?

**Comment by netniV** [comment]
I will try and give it a go.  I'll have to remind myself how to select which package repo I want as it's been a while 👍

**Comment by netniV** [comment]
@paulgevers wasn't this placed in the testing repo for buster?  Can we close this now?

**Comment by paulgevers** [comment]
```
paul@testavoira ~ $ rmadison libjs-chart.js
libjs-chart.js | 2.7.3+dfsg-3  | testing    | all
libjs-chart.js | 2.7.3+dfsg-3  | unstable   | all
```
and
```
paul@testavoira ~ $ grep -B10 chart cacti/debian/control 
Package: cacti
Architecture: all
Depends: dbconfig-common (>= 2.0.9~),
         dbconfig-mysql | dbconfig-no-thanks,
         fonts-dejavu-core,
         fonts-dejavu-extra,
         fonts-fork-awesome,
         javascript-common,
         libapache2-mod-php | php,
         libjs-c3,
         libjs-chart.js,
```

So yes, this is fixed in Debian unstable and testing (soon to be buster).

**Comment by netniV** [comment]
Cool, will close for now then.  We can always reopen if the issue raises itself again.
