### ISSUE TITLE
Missing a hook, the auth_profile  page will be blank if current tab is not general.

### ISSUE THREAD

**Issue by YongBoLiu** [Cacti/cacti#2162]
We'd add a hook in auth_profile.php as below, otherwise the auth_profile  page will be blank if current tab is not gerenal (auth_profile.php?tab=others).

```diff
diff --git a/auth_profile.php b/auth_profile.php
index 3fc658e..d1557a1 100644
--- a/auth_profile.php
+++ b/auth_profile.php
@@ -99,6 +99,8 @@ switch (get_request_var('action')) {
                if ($current_tab == 'general') {
                        settings();
                        settings_javascript();
+               }else{
+                       api_plugin_hook_function('auth_profile_run_action', get_request_var('tab'));
                }
 
                bottom_footer();
```

**Comment by YongBoLiu** [comment]
It occurs when click other tab, navigate to other pages, go back click 'Edit Profile', because default tab( 
$current_tab) changed to others, but not be handled.

**Comment by netniV** [comment]
I've edited your post above to have three backticks (`) and the word diff on the starting line.  This provides the visual representation above (something to keep in mind for next time so things format properly).

Thanks for the patch, I'll apply this now.

**Comment by netniV** [comment]
This has now been committed to the development code.
