### ISSUE TITLE
cacti 1.1.38 emails notification

### ISSUE THREAD

**Issue by raghadobeid** [Cacti/cacti#2165]
hello!
I was used cacti 0.8.8 and the emails notifications are working well . but when I use cacti 1.1.38 I take the same information from the previous version for SMTP , but it's not work and have this message : 

Checking Configuration...
Method: SMTP
Ping Results: SMTP error: Connect failed:
Message Not Sent due to ping failure.

**Comment by cigamit** [comment]
More than likely a configuration option though we have made some changes.  Best bet is for the near term to run the develop branch.  We are close to the release of beta3.

**Comment by cigamit** [comment]
Since this is resolved in 1.2, I'm going to close this one.

**Comment by raghadobeid** [comment]
can you send for me the link for 1.2 ?

**Comment by raghadobeid** [comment]
> Since this is resolved in 1.2, I'm going to close this one.

can you please send to me the link for 1.2 ??
