### ISSUE TITLE
Graph template Title not handling replacement variable

### ISSUE THREAD

**Issue by dsclassen** [Cacti/cacti#2167]
I have some network interfaces that return netifDescr values:

```
[netifDescr='comput2-02:a2a'] 
[netifDescr='comput2-02:a2a-10']
[netifDescr='comput2-02:a2a-20']
[netifDescr='comput2-02:a2a-30']
```

The Graph template has the following setting for Title:

```
|host_description| - |query_netifDescr| - Traffic
```

but the actual titles of the 4 graphs ends up looking like this:

```
NetApp - comput2-02:a2a - Traffic
NetApp - comput2-02:a2a- - Traffic
NetApp - comput2-02:a2a- - Traffic
NetApp - comput2-02:a2a- - Traffic
```

It seems that the trailing digits (i.e. 10, 20, 30)  are getting clipped off for some reason.

I've tried to "Reapply Suggested Names", but this does not fix the Title.

**Comment by netniV** [comment]
Can you provide the following information:

- OS & Version
- PHP Version
- Cacti Version
- If applicable:
   - Backtrace
   - Plugin name/version

Also, are there any errors in the web server log and/or cacti log?

**Comment by dsclassen** [comment]
CentOS Linux release 7.5.1804
PHP 7.1.24
Cacti 1.2.0 (beta2 I think)
There are no errors in the cacti.log file or the web server log files.
Just a lack of the complete query_netifDescr string.

**Comment by dsclassen** [comment]
I think it the string is getting clipped after 15 characters.

**Comment by netniV** [comment]
There is a limitation based on the Console -> Settings -> Visual -> Maximum Title Length
