### ISSUE TITLE
[1.2.0 Beta2] Graph in graph.php doesn't align with center

### ISSUE THREAD

**Issue by skyjou** [Cacti/cacti#2168]
Graph in graph.php doesn't align with center (Chrome 70 and Firefox 63).

**Comment by netniV** [comment]
Please be more specific with examples.

**Comment by skyjou** [comment]
It seem related to this [commit](https://github.com/Cacti/cacti/commit/cef4bd8671d5f7e3b6f164e3670329109bb5a921).

If I change line 131 of graph.php:
`<td class='center'>` -> `<td align='center'>`

Graphs will be in the center of page.

**Comment by skyjou** [comment]
With the latest commit:
![image](https://user-images.githubusercontent.com/13309854/48619190-a7114480-e9d6-11e8-9463-f431edb65add.png)

Change 'class' to 'align':
![image](https://user-images.githubusercontent.com/13309854/48619216-bee8c880-e9d6-11e8-9e01-88913ae77d9c.png)

**Comment by netniV** [comment]
OK, thanks that helps me know to what look for.  Hopefully, I will have a fix for this shortly.

**Comment by netniV** [comment]
This has now been committed to the development code.
