### ISSUE TITLE
[1.2.0] Poller_graphs_reapply_names.php is not taking effect

### ISSUE THREAD

**Issue by vishnubraj** [Cacti/cacti#2169]
The script is not taking effect also the GUI option also doesnt work. Please check...

![reapply_suggested_names](https://user-images.githubusercontent.com/11851188/48605545-110ff680-e9a3-11e8-9b19-bac9a97d3685.gif)

**Comment by pautiina** [comment]
First you need reload query for interfaces.

**Comment by vishnubraj** [comment]
i did interface query reload... The second interface doesn't exist anymore...
previously it used to rename the interface with |query_ifname| |query_ifAlias| and then we goahed and delete all the interfaces which has the query in the name.. But it is not doing that with the latest version... can this be fixed?

**Comment by cigamit** [comment]
@vishnubraj, we will not be re-implementing that bug in the code.  We were looking at the possibility of adding an 'orphan' graph option.  I think that makes more sense don't you?

**Comment by pautiina** [comment]
@vishnubraj I think now you need manualy change DS. I think your DS use index type ifdesc and you need change this for ifname and change value for index

**Comment by cigamit** [comment]
In Cacti 1.2, there is an 'Orphaned' checkbox that will identify those graphs that no longer have an interface.  So, this ticket is redundant.
