### ISSUE TITLE
GUI inconsistancies 

### ISSUE THREAD

**Issue by 0xygen8** [Cacti/cacti#217]
1. in the Modern theme:
create new graphs -> tick the 'select All' -> create new graphs 
now in other themes when you do this again you'll see that these graphs are already being graphed (text on selected item is gray) but in the Modern theme only the selector boxes are grayed  out (not really visible) in the dark/paw theme all text is made gray (more visible)

2. ticking 'select all' is not cleared when graph type is altered -- in the above situation when you have selected all -> created the graphs -> select all again (nothing is selected) switch to other graph template the select all is still selected.

3. in the above situation clicking on the check-box does not do anything (only when the line is clicked) 

4. after you have added a new host it is impossible (you get a red X) to add it to the default tree (with drag and drop) until you add "a root branch item" after that you can drag a new host to that tree (as a root item)

5. impossible to delete datasouces, select a datasource -> select delete - refreshes the screen leaves the datasource intact but now the datasource is not selectable anymore

**Comment by cigamit** [comment]
1) Noted, minor
2) Noted, again minor, but worth some investment
3) I'm not entirely sure what you mean
4) Yea, good catch.  Should be a separate trackable bug.
5) Seems like some theme issue.  You will note that there is a column called 'Deletable', what was it set to when you attempted to delete the data source?  By default, you should not be able to delete something that is marked not deletable.  There may have been a JavaScript bug on that page.  Please see if you can reproduce with the developer mode console open and look for JavaScript errors.  If you find them, please indicate: browser and version, os version, and detailed steps to reproduce.

**Comment by 0xygen8** [comment]
4 is now a new bug

**Comment by 0xygen8** [comment]
3. when the user clicks the square selector box it can not be selected -- only when the user clicks the line the box gets selcted

**Comment by cigamit** [comment]
3. keeps rearing it's ugly self.  Confirmed and looking into it.

**Comment by 0xygen8** [comment]
5. tested this with modernand dark firefox and safari datasources are not deleteable
select a datasource -> in the selector choose delete -> looses the selection

**Comment by cigamit** [comment]
Perfect 5 is as designed.

**Comment by cigamit** [comment]
3 should be resolved now.  Please test again and provide feedback.

**Comment by 0xygen8** [comment]
3 is confirmed fixed

**Comment by cigamit** [comment]
Thanks for testing!

**Comment by 0xygen8** [comment]
1 and 2 are also fixed

**Comment by 0xygen8** [comment]
would you be so kind to explain why it is not possible anymore to delete a datasource (why it is as designed) since the GUI lets you select the datasource select delete and then suddenly the selection is gone and the selected item is 'locked' (you have to reload to make it selectable again)

**Comment by cigamit** [comment]
A Data Source will be locked until it's parent graph is removed.  So, if you simply delete the Graph or Graphs the Data Sources will be removed as well.

Since in Cacti 1.0 a Data Source can be used by multiple Graphs we felt it better this way.

**Comment by 0xygen8** [comment]
Ok, makes sense. 
confirmed that it works when there is no graph left that references the datasource 👍
