### ISSUE TITLE
Introduce Device and Graph Template Caching to Speed UI

### ISSUE THREAD

**Issue by cigamit** [Cacti/cacti#2173]
Reported from a large site today, there are a number of interface pages that lag due to complex queries taking a long period of time.  There are three areas that are slows for different reasons.  They include:

1) Returning long host lists from the various device dropdowns
2) Viewing graphs from the Tree and Preview page due to slow queries for allowed graph templates
3) Console pages Data Sources and Graph dues to deletable on the Data Sources page, and due to permission checks on the Graphs page.

These issues need to be addressed in the 1.2 release.

**Comment by TheWitness** [comment]
This has already been fixed.
