### ISSUE TITLE
Please Describe Cacti's API's

### ISSUE THREAD

**Issue by zhaoqiang341** [Cacti/cacti#2174]

**Comment by cigamit** [comment]
What type of API are you looking for?  Much of Cacti's information is in a Database, and the API for that is SQL, for the RRDtool data, we use a function called rrdtool_function_fetch().  We are looking forward to a SQL interface to the RRDtool data, but we have to get the 1.2 release done first.  So, please ask again and provide more specific requirements.

**Comment by cigamit** [comment]
Closing since this question has been answered.
