### ISSUE TITLE
Cacti Slow loading   How to optimize

### ISSUE THREAD

**Issue by tyit** [Cacti/cacti#2177]
![cacti888](https://user-images.githubusercontent.com/31933126/48926781-e88c7d00-ef0b-11e8-84ab-026ee7436102.png)

**Comment by netniV** [comment]
What plugins do you have enabled?

**Comment by cigamit** [comment]
Please provide some statistics about system:
1) # of users
2) # of devices
3) # of graphs
4) # of data sources
5) Boost enabled or disabled
6) du -hs rra
7) free output

Thanks.

**Comment by tyit** [comment]
two users
twenty four devices
Eight hundred graphs
Seven hundred forty eight data sources

![cacti5](https://user-images.githubusercontent.com/31933126/48974693-1d2e3f00-f09a-11e8-8b0a-92a1721a08c9.png)
![cacti7](https://user-images.githubusercontent.com/31933126/48974695-1ef80280-f09a-11e8-8899-9b4fc6471f8b.png)
![cacti6](https://user-images.githubusercontent.com/31933126/48974696-20c1c600-f09a-11e8-8bc2-6518e398ffdd.png)
![cacti4](https://user-images.githubusercontent.com/31933126/48974697-23242000-f09a-11e8-878c-0cd11337f36c.png)

**Comment by cigamit** [comment]
1. It seems like you are on a very old version of Cacti (0.8 branch).  You will get very limited support for it.  These has been tons of performance enhancements since the 0.8 branch.
2.  Your poller and Cacti is fine, it seems that your system itself is really slow.  Most likely from using really slow disks / high disk I/O.  You should watch the system itself as you attempt to load the pages.  See if your I/O Wait spikes during it.

**Comment by tyit** [comment]
![cacti1](https://user-images.githubusercontent.com/31933126/48996728-23024e00-f188-11e8-8488-42b52376cb8f.png)

**Comment by tyit** [comment]
![cacti666](https://user-images.githubusercontent.com/31933126/48997167-fbac8080-f189-11e8-937f-1cda1df2e95f.png)

Find the reason, a graphics load is slow, this graph is a summary of forty ports.
Thank you

**Comment by tyit** [comment]
@cigamit
 Is there any way to optimize?

**Comment by netniV** [comment]
Your system is serving up the web page in a reasonable amount of time.  However, your image creation is taking longer.  If that is the load time for a single graph, your system is taking 4 seconds to both retrieve the data from the RRA and then display the result.

If you use the graph debug mode and graph info links (which may not be present in your version) you should get more information about what is going on.  You could try running the command that Cacti runs yourself at the command line and see how long that takes.

You should also make sure that your log files are not too large.  Updating log files can slow a system down if they are not regularly cycled.

**Comment by cigamit** [comment]
Enable boost image cache and move from physical disks to flash/ssd.  Also, upgrade to latest RRDtool as there have been some improvements on the whole graph rendering process that would appear to significantly reduce rendering times.
