### ISSUE TITLE
[1.2.0 Beta 3] Graph Zooming Requires Manual Refresh

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#2179]
In Beta 3 when you initiate a zoom the time range changes, but the graphs do not auto-reload to reflect the new time frame until you hit "refresh". Is this by design?
![peek 2018-11-25 18-26](https://user-images.githubusercontent.com/12864741/48987950-ea0e9e80-f0df-11e8-9389-836f9d5cfa13.gif)

**Comment by eschoeller** [comment]
Same behavior with the right-click menu now too.

**Comment by netniV** [comment]
This is because there is an undefined variable in the JavaScript:
"myGraphLocation is not defined"

**Comment by netniV** [comment]
The same variable is also used on line 815.

**Comment by netniV** [comment]
Again, I believe this to be releated to #2182

**Comment by cigamit** [comment]
We are taking beta3 down.  There will be a beta4 soon.  Hopefully today.  Holidays are not good times to do beta releases.

**Comment by netniV** [comment]
I can confirm that the latest develop version is working again.

**Comment by eschoeller** [comment]
Lol yeah sorry to hear that. I’ll go Beta4 right away when it’s available. 

Eric.
