### ISSUE TITLE
Data profile gets ignored on new data source

### ISSUE THREAD

**Issue by rprofijt** [Cacti/cacti#218]
What I have done:

- Created a new data source profile under Presets-> Data Source. (with 1 minute polling)
- Assigned this data source profile to all data templates.
- Changed poller interval in settings and in cron.
- Deleted all graphs and data sources.
- Created new graphs and data sources based on the data source templates with the new 1 minute polling profile.

The new data sources still say "5 minutes" in the "Poller Interval" column and the created rrd's still have the  <step>300</step>  setting.

Am I missing something or is this a bug?

**Comment by cigamit** [comment]
I'm thinking it's a bug.  Will look into it.  Did you do a mass change using the main Data Source Templates screen pick?

**Comment by rprofijt** [comment]
Yes I did, thanks!

**Comment by cigamit** [comment]
Try again with the latest data_templates.php.  Just committed.

**Comment by rprofijt** [comment]
That did the trick, thanks.

**Comment by cigamit** [comment]
Cool, thanks and closing.  Thank you for testing!
