### ISSUE TITLE
[1.2.0 Beta 3] Graph List Mode Broken

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#2180]
I can't select a device and list out graphs to display anymore.
![peek 2018-11-25 21-30](https://user-images.githubusercontent.com/12864741/48993176-6e215000-f0f9-11e8-9797-07764edc3147.gif)

**Comment by netniV** [comment]
This is working for me so please check the browser console to see if there are any errors appearing.

**Comment by netniV** [comment]
Actually, I think this may be releated to #2182 ... can you see if you have any other errors?  I'm assuming you are on Beta3, but I guess you may still be on Beta2?

**Comment by cigamit** [comment]
We are taking beta3 down.  There will be a beta4 soon.  Hopefully today.  Holidays are not good times to do beta releases.

**Comment by netniV** [comment]
I can confirm that the latest develop version is working again.
