### ISSUE TITLE
[1.2.0] Graph View missing 'html_graph_template_multiselect()' function

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#2182]
![image](https://user-images.githubusercontent.com/9052188/49003596-25e64a00-f15a-11e8-91ca-b6fe402a0389.png)

```
Error:	500 List Mode
Reason:	Select the Report to add the selected Graphs to.
```
The above error appears somehow when I clicked on Graph Preview, then after selecting a device which had no graphs showing, tried to select Graph List.  Also, once the first message appears, clicking Console then Graphs generates the same error.

**Comment by netniV** [comment]
```
PHP Fatal error:  Uncaught Error: 
Call to undefined function html_graph_template_multiselect() in /graph_view.php:940\nStack trace:\n#0 {main}
thrown in /graph_view.php on line 940
```
This seems to have been introduced by cbf6f818 - Resolving Issue #2173 (5 days ago) <cigamit> and appears to be a missing function.  This function is only used on this line.

**Comment by cigamit** [comment]
We are taking beta3 down.  There will be a beta4 soon.  Hopefully today.  Holidays are not good times to do beta releases.

**Comment by netniV** [comment]
I can confirm that the latest develop version is working again.
