### ISSUE TITLE
html_host_filter() does not handle host_id consequently

### ISSUE THREAD

**Issue by browniebraun** [Cacti/cacti#2184]
host_id delivered as parameter will be completely ignored for both options "noany" and "nonone".

**Comment by netniV** [comment]
Not sure what was supposed to come after consequently in the title? (if it isn't a typo)

**Comment by cigamit** [comment]
We need more info @browniebraun.

**Comment by cigamit** [comment]
@browniebraun, please provide additional documentation.

**Comment by browniebraun** [comment]
Take a look at line 1907/1908 in /lib/html.php:

```
<?php if (!$noany) {?><option value='-1'<?php if (get_request_var('host_id') == '-1') {?> selected<?php }?>><?php print __('Any');?></option><?php }?>
<?php if (!$nonone) {?><option value='0'<?php if (get_request_var('host_id') == '0') {?> selected<?php }?>><?php print __('None');?></option><?php }?>
```

Here GET parameter host_id will be used instead of the original host_id parameter being included into the function call: 

`function html_host_filter($host_id = '-1', $call_back = 'applyFilter', $sql_where = '', $noany = false, $nonone = false)`

**Comment by cigamit** [comment]
Got it.  Resolved.
