### ISSUE TITLE
SNMP uptime ping false Down indication

### ISSUE THREAD

**Issue by llowrey** [Cacti/cacti#2185]
I recently "upgraded" from fedora 28 to fedora 29. After the upgrade, my graphs have tons of gaps and many hosts are listed as Down when they are up and responding well to SNMP queries.

The problem appears related to the log line below which indicates that the timeout is -0.001ms. That seems clearly wrong.

```
2018/11/25 22:20:54 - PING Device[34] SNMP: Device did not respond to SNMP
2018/11/25 22:20:54 - CMDPHP WARNING: SNMP Error:'Timeout (-0.001 ms)', Device:'host.somewhere.com', OID:'.1.3.6.1.2.1.1.3.0'
```
The timeouts for those hosts are set to either 400 or 500ms.

I've managed to get all the hosts to show as Up by changing them to UDP ping but I'm still getting a ton of these -0.001ms timeouts in the log.

Poller is cmd.php

cacti-1.1.38-3.fc29.noarch

**Comment by netniV** [comment]
Are you using spine or cmd.php as your poller?

**Comment by llowrey** [comment]
Poller is cmd.php

**Comment by netniV** [comment]
As far as I am aware, unless you are using spine, you can't use ICMP ping as that will require raw socket privileges which is not available by default to ordinary users.  The user your poller is running as will likely not have root privileges to do that.

**Comment by llowrey** [comment]
Correct.

All my hosts were set to 'SNMP Uptime' for 'Downed Device Detection'. I had to change that to 'Ping' with 'Ping Method' 'UDP Ping' to get them to show as Up.

The problem, as indicated in my original comment is that I'm seeing SNMP timeouts for hosts that are up and responding well and quickly to SNMP queries.

**Comment by netniV** [comment]
If you have PHP-SNMP enabled, can you try disabling that?  Also what version of Cacti/PHP/MySQL/NET-SNMP are you running?

**Comment by cigamit** [comment]
Is this a virtual machine?  Cause your timestamps are off too and the ping time is negative.  This should never happen.  Also, increase your ping timeout.  Lastly, just use spine, it's going to be a better data collector.  Let us know the OS', version, etc.  in either case.

**Comment by llowrey** [comment]
Ok, it was a local configuration issue. When I "upgraded" from Fedora 28 to 29 NetworkManager got re-enabled. I stopped and disabled it and now everything is working normally.

**Comment by cigamit** [comment]
Oh, that is interesting.  Should that dependency be added to the installation documentation?

**Comment by llowrey** [comment]
No need to document it. My local config is a bit odd. I have several NICs that are only used by VMs so they are 'up' but don't have IPs on the host. That seemed to confuse NetworkManager. It appears that NetworkManager was messing with the route table in a way that caused the the cacti UDP ping and snmp packets to sometimes go out the wrong NICs.
