### ISSUE TITLE
Boost generates invalid SQL during on demand update

### ISSUE THREAD

**Issue by ze6ra** [Cacti/cacti#2186]
I take error: 2018-11-25 13:14:03 - DBCALL ERROR: A DB Exec Failed!, Error:1064, SQL:'INSERT INTO poller_output_boost (local_data_id, rrd_name, time, output) VALUES ,('27208','traffic_out','2018-11-25 13:14:01','0')('27208','traffic_in','2018-11-25 13:14:01','0'),('27209','traffic_out','2018-11-25......
It is SQL syntax error delimiter after VALUES and no delimitr between first pair of brackets.

If string lenght is more  $max_allowed_packe tail will insert in next string  with start delimiter.  

Problem piece of code:
if (($out_length + $overhead) > $max_allowed_packet) {
						db_execute($sql_prefix . $outbuf . $sql_suffix, true, $conn);
						$outbuf     = $outbuf2;
						$out_length = strlen($outbuf2);
						$i          = 1;
					} else {
						$outbuf .= $outbuf2;
						$i++;
					}

**Comment by netniV** [comment]
It would be useful if you could give the line numbers and if possible your suggested fix?

**Comment by netniV** [comment]
This should now be corrected in the latest development commit.  If you need this updating in 1.1.38 or earlier, you will have to manually edit your code to match.
