### ISSUE TITLE
in a new tree it is inpossible to add a host

### ISSUE THREAD

**Issue by 0xygen8** [Cacti/cacti#219]
After you have added a new host it is impossible (you get a red X) to add it to the default tree (with drag and drop) until you add "a root branch item" after that you can drag a new host to that tree (as a root item)

**Comment by cigamit** [comment]
I have made it easier to drop onto the tree, after the updates, make sure you reload the style sheets using either Ctrl+R or F5 depending on your browser.

**Comment by 0xygen8** [comment]
confirmed
