### ISSUE TITLE
Upgrade shows error during final step

### ISSUE THREAD

**Issue by ryswork1993** [Cacti/cacti#2192]
![image](https://user-images.githubusercontent.com/44529247/49277161-a4751b80-f4bb-11e8-9be6-380c6083e88b.png)
![image](https://user-images.githubusercontent.com/44529247/49277173-ae971a00-f4bb-11e8-8358-193d1022e8fc.png)
![image](https://user-images.githubusercontent.com/44529247/49277187-b787eb80-f4bb-11e8-885b-0499d36bea52.png)
![image](https://user-images.githubusercontent.com/44529247/49277200-c373ad80-f4bb-11e8-9db2-c9c4d29e3345.png)
![image](https://user-images.githubusercontent.com/44529247/49277205-ca022500-f4bb-11e8-93c5-4505d1df5ae7.png)

**Comment by cigamit** [comment]
This may be due to the feature, yet implemented, that allows no more than one upgrade to happen concurrently from the GUI.

**Comment by netniV** [comment]
There have been a number of enhancements that have enhanced various functions within the installer in v1.2.2.  These have included background cli checks, dual cli/web module checks which were causing the background installation routine to fall over.  As such, I believe this is resolved now.
