### ISSUE TITLE
Failed to create aggregate graph

### ISSUE THREAD

**Issue by ryswork1993** [Cacti/cacti#2193]
![image](https://user-images.githubusercontent.com/44529247/49283069-b8c11480-f4cb-11e8-8819-b2c7f339caa6.png)
![image](https://user-images.githubusercontent.com/44529247/49283088-c4acd680-f4cb-11e8-992a-5d840cc840f9.png)
![image](https://user-images.githubusercontent.com/44529247/49283100-cb3b4e00-f4cb-11e8-9213-ec666bf592ea.png)

**Comment by pautiina** [comment]
Read this please:
https://github.com/Cacti/cacti/issues/599 https://github.com/Cacti/cacti/issues/2074

**Comment by cigamit** [comment]
Yea, Aggregate still needs some work.  There are some aggregates that are impossible, but the GUI does not prevent you from attempting to create them anyway.

**Comment by cigamit** [comment]
Marked as duplicate.  So, closing.  Feel free to add additional comments on this page even though it's a closed ticket.
