### ISSUE TITLE
Boost drops stale poller data although option '--skip-past-updates' is in use

### ISSUE THREAD

**Issue by browniebraun** [Cacti/cacti#2194]
see /lib/boost.php lines 851 and 1296.

**Comment by netniV** [comment]
Isn't that what skip-past-updates means?? It's considered stale so drops it?  Or am I missing the point here.

**Comment by browniebraun** [comment]
If you use skip-past-updates then RRDtool just ignores those outdated values and in this case Boost does not have to sort them out.

**Comment by netniV** [comment]
Oh, so what you are saying is that if we are using --skip, don't filter the values?  Do you know what version --skip was introduced in?  It may be something where we need to ensure that the RRDTool version is at that level.

**Comment by browniebraun** [comment]
This option has been introduced with RRDtool 1.5.0.

**Comment by cigamit** [comment]
When implementing the skip option, I did not think of simplifying/optimizing the internal algo's.  Good point.

**Comment by cigamit** [comment]
This issue has been resolved for a long time now.  Closing.

**Comment by Lashinkof** [comment]
after migration from 0.8.8h to 1.2.10 I faceing same issue  and I'm useing RRDTool version 1.7

**Comment by netniV** [comment]
Have you updated your RRDTool version compatibility within settings?

**Comment by Lashinkof** [comment]
yes it is same I have 1.7.1 and in the settings is 1.7.1+
