### ISSUE TITLE
js error when select 'Classic' theme in User Profile

### ISSUE THREAD

**Issue by YongBoLiu** [Cacti/cacti#2196]
When select 'Classic' theme in User Profile, got the error in the Firefox develop Console as below, other themes have no such error.

Error: cannot call methods on selectmenu prior to initialization; attempted to call method 'destroy' jquery.js:305:9
	error http://9.119.129.91/cacti/include/js/jquery.js:305:9
	$.widget.bridge/$.fn[name]/< http://9.119.129.91/cacti/include/js/jquery-ui.js:246:14
	each http://9.119.129.91/cacti/include/js/jquery.js:354:10
	each http://9.119.129.91/cacti/include/js/jquery.js:189:10
	$.widget.bridge/$.fn[name] http://9.119.129.91/cacti/include/js/jquery-ui.js:236:5
	renderLanguages http://9.119.129.91/cacti/include/layout.js:748:2
	applySkin http://9.119.129.91/cacti/include/layout.js:744:2
	<anonymous> http://9.119.129.91/cacti/include/layout.js:2314:2
	mightThrow http://9.119.129.91/cacti/include/js/jquery.js:3534:21
	resolve/</process< http://9.119.129.91/cacti/include/js/jquery.js:3602:12

**Comment by YongBoLiu** [comment]
It's in Beta4. Log it, although don't see any feature effect yet.

**Comment by cigamit** [comment]
Resolved.  Thanks!
