### ISSUE TITLE
[1.2.0 Beta 4] 414 Request-URI Too Long

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#2197]
When I leave a Cacti window open for a long time (several days) I'll come back to this prompt:

![image](https://user-images.githubusercontent.com/12864741/49347182-40885980-f659-11e8-8984-11298d0806e0.png)

This has been going on for a long time, and I've been mostly ignoring it, but I thought I'd report the issue.

**Comment by cigamit** [comment]
Darn, thought I had fixed that.  All good now after testing graph refresh.  Please confirm.

**Comment by eschoeller** [comment]
Ok, I've put those changes in. I'll leave some windows open now for awhile in a few places and see what happens!

**Comment by cigamit** [comment]
I'm pretty sure it'll work.  I was able to reproduce the problem or what would eventually be the problem, and remediate.  Keep us posted though.

**Comment by cigamit** [comment]
Figuring this is fixed now ;)

**Comment by eschoeller** [comment]
My apologies! I just checked my two browsers and they are still humming along just fine with no errors so I'm looking pretty good over here now. Thanks!
