### ISSUE TITLE
[1.1.38] Cacti graphs.php : non existent graph template

### ISSUE THREAD

**Issue by sysres-dev** [Cacti/cacti#2199]
Cacti shows us a non existent graph template for the graphs.php page ("In/Out Bits") :
![cacti-bug-flout](https://user-images.githubusercontent.com/45565495/49379852-83f1cf00-f710-11e8-9f3d-6baad4c3867c.PNG)
![cacti-bug-2](https://user-images.githubusercontent.com/45565495/49379851-83f1cf00-f710-11e8-9c08-ad87566af2df.png)

It seems to be a frontend error, since, when i click on graphs i end up on graph with the correct template.
Also, ids are consistent in database, here is an example for one affected device :
![cacti-bug-3](https://user-images.githubusercontent.com/45565495/49382460-c4544b80-f716-11e8-9973-c6e97e05ffaf.png)

**Comment by cigamit** [comment]
The graph management interface in Cacti 1.x lists the templates by their name under Data Collection -> Data Queries -> SNMP - Interface Statistics (edit) -> Associated Graph Templates.  That is why you are not seeing what you expect.  This enhancement was placed on this page only to allow users to know which of the specific Data Query templates the graph is using.  It's not a bug, but confusing, until we finish the documentation.

**Comment by cigamit** [comment]
I'm going to close, but you may continue to comment.  If you want the Template named differently, you would do it from the Data Queries interface.
