### ISSUE TITLE
after a clean install XML files are not installed

### ISSUE THREAD

**Issue by 0xygen8** [Cacti/cacti#220]
After a fresh install and selected some templates the XML (in sinstaller) files for these templates are not installed
Example:

Data Queries -> Host MIB - Host Type Graphs 

XML Path : <path_cacti>/plugins/hmib/templates/resource/script_server/hmib_host_types.xml

directory structure and XML files are not created

**Comment by cigamit** [comment]
Going to pull this package from the installer.  The plugin should be installed first.

**Comment by cigamit** [comment]
Resolved, thanks!  Will add this to the hmib plugin.

**Comment by 0xygen8** [comment]
confirmed
