### ISSUE TITLE
Can't set Graph Title via add_graph.php

### ISSUE THREAD

**Issue by pweibbre** [Cacti/cacti#2201]
Hi,

I'm using Cacti Version 1.1.38.
I want to create a greater bunch of new graphs from one grapjtemplate with the add_graph.php script.

For all graphs i would use the same graphtemplate.
The graph template is marked for "multiple instances" and also in common option the field Title is marked.
I have filled out the template field for title with this entry:
|host_description| - WLS JMS Queue |queuename|

( Ok, the |queuename| as replacement variable also did not work, maybe i did not understood what i have to fill in here.
queuename is a parameter of my data source.

it doesnt work so i tryed it with the add_graph.php which is also not working in th right manner.

I did the following:
my host has ID 14

I was asking the script for template ID and input fields:

```
php add_graphs.php --list-graph-templates
...
138     WLS Universal Single Queue
```

OK, ID is 138

```
php add_graphs.php --list-input-fields --graph-template-id=138
Known Input Fields:(name, default, description)
117:queuename           WLS Queue
```

OK, i see the Input field queuename

Next i have created the graph:
`php add_graphs.php --graph-type=cg --graph-template-id=138 --host-id=14 --graph-title="A/T WLS JMS Queue: JMS_EILOG" --input-fields="117:queuename=JMS_EILOG"`

The graph was created, but the title was not what i've expected:
xxyyzz123 - App1 B aktiv - WLS JMS Queue |queuename|

|host_description| of the template was filled correct but |queuname| not. OK, i thought i made an error whith this variable. removed the graph and giv it a next try while defining the title with the commandline:

`php add_graphs.php --graph-type=cg --graph-template-id=138 --host-id=14 --graph-title="A/T WLS JMS Queue: JMS_EILOG" --input-fields="117:queuename=JMS_EILOG"`

the --graph-title option was completely ignored. the resulting graph has again the title from the prefilled template :-(

**Comment by netniV** [comment]
It is always best to submit two separate issues in different trackers.  That makes any fixes, questions and updates clearer since it isn't a mixture of two different issues.

**Comment by pweibbre** [comment]
moved the second issue in a different, new bug

**Comment by cigamit** [comment]
This should be fully resolved now.
