### ISSUE TITLE
realtime error in cacti 0.8.8a

### ISSUE THREAD

**Issue by chiragvaidya** [Cacti/cacti#2203]
@cigamit

after installing realtime pluggin i am getting broken image and when i check path it shows 

The requested URL /plugins/realtime/plugins/realtime/graph_image_rt.php was not found on this server.

Please help dear

**Comment by cigamit** [comment]
This issue tracker is for tracking of bugs in the current branch of Cacti. If you are having issues with an exceptionally old version of Cacti, it is recommended you use the Cacti forums.  Either way, it looks like your url_path isn't set correctly in your include/config.php

**Comment by chiragvaidya** [comment]
> This issue tracker is for tracking of bugs in the current branch of Cacti. If you are having issues with an exceptionally old version of Cacti, it is recommended you use the Cacti forums. Either way, it looks like your url_path isn't set correctly in your include/config.php

@cigamit one last help dear. in my config currently url path is **$url_path = "";** and my cacti install is /var/www/html/cacti/.  what changes do i have to do in config.php file?

**Comment by netniV** [comment]
```php
$url_path = '/'
```
That is what you should be using for a root cacti site.
