### ISSUE TITLE
Allow admins to disable RRDtool watermark

### ISSUE THREAD

**Issue by browniebraun** [Cacti/cacti#2205]
Although I've haven't found a hint within RRDtool's Changelog, graph option "--disable-rrdtool-tag" will be supported by RRDtool >= 1.5. Tiny add-on and if not already in we should add it to 1.3 to allow disabling Tobi's Watermark. More a reminder for myself and the team.

**Comment by netniV** [comment]
I can't say I've ever noticed his watermark, but then I have used the option of specifically setting my own, would that suppress it?

**Comment by browniebraun** [comment]
Hey Mark,
it does not suppress your customized watermark below the chart, but the "RRDTOOL / TOBI OETIKER" hint in the right upper corner.

Regards
-Andi

**Comment by netniV** [comment]
I've never noticed that, I'm off to check it out lol.

**Comment by netniV** [comment]
OK, I've never seen that even though it's been right there all this time lol.  We should totally add that as an option as I know some people would prefer to have it removed.

**Comment by TheWitness** [comment]
Like Andi said, not really documented unless you read the code.

**Comment by netniV** [comment]
# Before
![watermark_pre](https://user-images.githubusercontent.com/9052188/80864952-01ab6880-8c7e-11ea-822d-601f5708e6fd.png)

# After
![watermark_post](https://user-images.githubusercontent.com/9052188/80864957-0708b300-8c7e-11ea-99c1-1a8ace870937.png)

**Comment by netniV** [comment]
And yes, it looks like my local system is dead jim (but not as we know it!)
