### ISSUE TITLE
Cacti uses an unsupported phpmailer version

### ISSUE THREAD

**Issue by StCyr** [Cacti/cacti#2206]
Cacti uses version 5.2.26 of PHPMailer, but:

> The 5.2 branch will not receive security updates after December 31st 2018.

(https://github.com/PHPMailer/PHPMailer)

**Comment by netniV** [comment]
I will check what versions of the newer versions of PHP mailer are like and test this out.  We are due for a full release soon so I wouldn't normally recommend changing something as fundamental as this but with the lack of support/security fixes, I personally think we should be updating it so I will be speaking to the team about this.

**Comment by netniV** [comment]
Looking over https://github.com/PHPMailer/PHPMailer/blob/master/UPGRADING.md, there will be some necessary testing to ensure that things are working as they should if we did move forward to the 6.0 branch.

Some changes may even break things in our functions library.

So, we are going to have to properly review the possibility of upgrading the mailer at this late stage of the process.  It may have to be something we update in the first patch.

**Comment by paulgevers** [comment]
@netniV in Debian, we are preparing for the freeze for our next release: https://release.debian.org/buster/freeze_policy.html. If I don't do anything, Cacti may be dropped from the next Debian release due to this [issue.](https://bugs.debian.org/905254) What is your estimate on fixing this issue and releasing 1.2.0?

**Comment by cigamit** [comment]
@paulgevers, I'm reviewing right now.  Does not look as big of a change as we thought.

**Comment by cigamit** [comment]
This is resolved now @paulgevers.
