### ISSUE TITLE
remote poller doesn't work

### ISSUE THREAD

**Issue by Carlimeunier** [Cacti/cacti#221]
Hello, 

I have this issue when i associate an equipement with a remote poller. But There is no log entry

![issue_remote poller](https://cloud.githubusercontent.com/assets/5239792/22032665/a8ff7ca8-dce5-11e6-954b-cfc32684b02e.PNG)

Any idea?

**Comment by cigamit** [comment]
Goto Console -> Data Collectors and edit the hostname of the main Cacti server to match what the remote data collector would to using a gethostbyname() call.  The authorization service gathers the IP address of the connect request and attempts to match it to either the IP address or the IP address of the gethostbyname() call.  In the worst case, just use the IP address.

**Comment by cigamit** [comment]
Any feedback?

**Comment by Carlimeunier** [comment]
It works. Thanks
