### ISSUE TITLE
Stored XSS in "Website Hostname" field

### ISSUE THREAD

**Issue by SegfaultMasters** [Cacti/cacti#2212]
**Description** - 
There's no escape being done before printing out the value of `Hostname` value in the Data collectors table. 
<br>
**Cacti version** - v1.1.38

<br>

**Steps to reproduce** -

- Navigate to http://localhost/cacti/pollers.php?action=edit&id=1 & add the below shared payload as the `Hostname` field value.

     Payload - `<img src=xss onerror=alert(1)>`

- Visit http://localhost/cacti/pollers.php, payload will be triggered.

<br>
<img width="732" alt="cacti" src="https://user-images.githubusercontent.com/42465102/50042544-67e41b00-008a-11e9-849c-0ae9d7164810.png">

<img width="730" alt="cacti1" src="https://user-images.githubusercontent.com/42465102/50042557-8813da00-008a-11e9-8ac0-1722a257ae3b.png">

**Comment by cigamit** [comment]
Resolved.  Thanks!
