### ISSUE TITLE
Stored XSS in "Website Hostname" field - Devices

### ISSUE THREAD

**Issue by SegfaultMasters** [Cacti/cacti#2213]
**Description** - 
There's no escape being done before printing out the value of `Hostname` value in the Tree table. 
<br>
**Cacti version** - v1.1.38

<br>

**Steps to reproduce** -

- Navigate to http://localhost:4040/cacti/host.php?action=edit&id=1 & add the below shared payload as the `Hostname` field value.

     Payload - `<img src=xss onerror=alert(1)>`

- Visit http://localhost:4040/cacti/tree.php?action=edit&id=1, payload will be triggered.

<br>
<img width="683" alt="cacti2" src="https://user-images.githubusercontent.com/42465102/50050299-e6899880-011c-11e9-8e8d-09ea6c58bdfc.png">
<img width="685" alt="cacti3" src="https://user-images.githubusercontent.com/42465102/50050300-e6899880-011c-11e9-9c50-c2e66771488c.png">

**Comment by cigamit** [comment]
Resolved.  Thanks for testing!  Note, there were a few more too.  All fixed up now.
