### ISSUE TITLE
Stored XSS in "Vertical Label" field - Graph

### ISSUE THREAD

**Issue by SegfaultMasters** [Cacti/cacti#2214]
**Description** - 
There's no escape being done before printing out the value of `Vertical Label`  in the Graphic templates page. 
<br>
**Cacti version** - v1.1.38

<br>

**Steps to reproduce** -

- Navigate to http://localhost:4040/cacti/graph_templates.php?action=template_edit&id=1 & add the below shared payload as the `Vertical label` field value.

     Payload - `label<img src=xss onerror=alert(1)>`

- Visit http://localhost:4040/cacti/graph_templates.php, the payload will be triggered.

<br>
<img width="641" alt="cacti4" src="https://user-images.githubusercontent.com/42465102/50050353-e9d15400-011d-11e9-934a-fdebca472c83.png">
<img width="641" alt="cacti5" src="https://user-images.githubusercontent.com/42465102/50050354-e9d15400-011d-11e9-9ea5-67ed291d8e20.png">

**Comment by cigamit** [comment]
Resolved.  Thanks for testing!
