### ISSUE TITLE
Stored XSS in "Name" field - Color 

### ISSUE THREAD

**Issue by SegfaultMasters** [Cacti/cacti#2215]
**Description** - 
There's no escape being done before printing out the value of `Name`  in the Color Template page. 
<br>
**Cacti version** - v1.1.38

<br>

**Steps to reproduce** -

- Navigate to http://localhost:4040/cacti/color_templates.php?action=template_edit & add the below shared payload as the `Name` field value.

     Payload - `<img src=xss onerror=alert(1)>`

- Visit http://localhost:4040/cacti/color_templates.php?action=template_edit, the payload will be triggered.

<br>
<img width="700" alt="cacti6" src="https://user-images.githubusercontent.com/42465102/50050365-73812180-011e-11e9-8979-94c8c2ccfa9b.png">
<img width="702" alt="cacti7" src="https://user-images.githubusercontent.com/42465102/50050366-73812180-011e-11e9-97b4-8cb0b75acc19.png">

**Comment by cigamit** [comment]
Resolved.  Thanks for testing!
