### ISSUE TITLE
[1.2.0 Beta 4] Cannot delete devices

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#2219]
I tried to delete a device. It stayed in the device list but the hostname and description were blank. 
![image](https://user-images.githubusercontent.com/12864741/50198854-d33c2000-030a-11e9-8fa9-20678ec9b440.png)

Same before as in #2131

I can delete them a second time, and they go away.

**Comment by cigamit** [comment]
This is a race condition either to an offline data collector, or removing a device in the middle of a polling cycle.  @netniV and I disscused this topic this morning.  In the next day or two, we will make a table and code change.  We have to do this before release.

**Comment by cigamit** [comment]
@eschoeller I have made an update.  @netniV please review too since this has been marked as a blocker.  Thanks!

**Comment by cigamit** [comment]
I'm going to close this one.  Please let us know if it happens again.
