### ISSUE TITLE
Cacti has wrong downtime

### ISSUE THREAD

**Issue by polawatkanouan** [Cacti/cacti#222]
Hi 

The monitor plugin under Cacti 0.8.8.b When a monitored device goes down, 
Monitor reports show 
" Host Previously UP for: 736745d 8h 12m 6s " , 
" Host Previously DOWN for: 736745d 8h 7m 5s "

**Comment by cigamit** [comment]
The 0.8.8x branches, and likely every plugin from supported in that branch of development, is frozen.  If you want a better version of Monitor, it's best to move to the Cacti 1.0 release.  It's completely different, and a much better visual experience.

**Comment by polawatkanouan** [comment]
Wow , Thank you for very very fast answer . next step I will try to find solution "้how to migrate plugin 0.8.8 to 1.0"
