### ISSUE TITLE
[1.2.0 Beta 4] Strange Reindex Warning Messages

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#2220]
```
grep 'REINDEX WARN' /var/log/cacti/cacti.log | cut -b 23- | sort | uniq -c
    130 REINDEX WARNING: Sort Field has Changed.  Old Sort:dskDevice, New Sort:dskIndex.  Re-mapping issues may occur!
    280 REINDEX WARNING: Sort Field has Changed.  Old Sort:dskIndex, New Sort:dskDevice.  Re-mapping issues may occur!
     14 REINDEX WARNING: Sort Field has Changed.  Old Sort:ifDescr, New Sort:.  Re-mapping issues may occur!
     69 REINDEX WARNING: Sort Field has Changed.  Old Sort:ifDescr, New Sort:ifIndex.  Re-mapping issues may occur!
     96 REINDEX WARNING: Sort Field has Changed.  Old Sort:ifDescr, New Sort:ifName.  Re-mapping issues may occur!
     20 REINDEX WARNING: Sort Field has Changed.  Old Sort:ifIndex, New Sort:ifDescr.  Re-mapping issues may occur!
      1 REINDEX WARNING: Sort Field has Changed.  Old Sort:ifIndex, New Sort:ifName.  Re-mapping issues may occur!
      2 REINDEX WARNING: Sort Field has Changed.  Old Sort:ifName, New Sort:.  Re-mapping issues may occur!
      5 REINDEX WARNING: Sort Field has Changed.  Old Sort:ifName, New Sort:ifDescr.  Re-mapping issues may occur!
     76 REINDEX WARNING: Sort Field has Changed.  Old Sort:ifName, New Sort:ifIndex.  Re-mapping issues may occur!
```
I don't think this remote poller even has anything that uses dskDevice or dskIndex. Nonetheless, this error really needs to indicate which data source or device ID is triggering this ... I don't know where to look.

**Comment by cigamit** [comment]
Yea, for sure, and we should not be changing the re-index sort field to nothing.  That is a bug.  I'm wondering if this is also related to the reindex issues.  Could be timeout related, but we certainly don't this sort field changing as a result of a timeout.

**Comment by eschoeller** [comment]
Thanks, I've applied this fix. I'll see what comes back.

**Comment by cigamit** [comment]
So, for those host/data query combination, you may have to clean things up manually.  However, if you simply remove the data query from the device, and then re-add it, does the snmp cache look good?  After which you will have to edit the data source and set the Index Value to what it needs to be.

After this, we will have to watch the log some more to see what is happening.

**Comment by eschoeller** [comment]
I think removing the data query and then adding it back in will recreate all the data sources and graphs defined for it, right?

**Comment by eschoeller** [comment]
haha this is pretty bad. and it just so happens I rebooted a lot of these devices 497 days ago for a firmware upgrade so the 32bit timeticks counter is rolling over on all of them triggering a recache and blowing away the right index values. Not even sure how widespread of an issue this is or how on earth it happened either.

**Comment by cigamit** [comment]
Okay, well, first of all, you can remove Data Query from Device -> Edit and add it back without impact.  However, you will still likely have to fix the Index Value and Index Types (at least for the ones broken).

**Comment by eschoeller** [comment]
A bit more history/context here (as I begin to remember things from 5+ years ago). 
This looks like a group of 23 devices that mostly had an older device template defined for them. At one point an upgraded device template was available and several of these devices had their device template changed. This brought in a new set of data queries, which now appear to be having these index issues. For what it's worth, I just bumped into a device still using the old device template. I changed it to reflect the newer version, and the new graphs and data queries came along with it. When the data queries were added, they appropriately set the Index Type to 'index' and had a numerical Index Value. So, this may partially answer your question, when added to a device the data query works correctly. Still unsure if I can remove it and add it back in while preserving the existing data sources. I'm going through and fixing these one at a time right now.

**Comment by eschoeller** [comment]
OK, I removed the data query and added it back in. The verbose output from the data query is identical to the other devices, however, in the case of the device where the query was removed and added back in, it's failing to detect the 38 items and 2 rows. Despite the verbose output showing this data. Having to click through all these banners that expand and contract in the verbose output is more than slightly cumbersome to sort through the output. 
So I don't know what's going on. 
I'm going to keep going through the rest of these impacted devices to manually fix the indexes for now. 
Sorry I'm probably another corner case again. But this has been working just fine for years and suddenly started having issues. But since it's a template I created, its possible there's something quirky about it and its my fault somehow ;)

**Comment by eschoeller** [comment]
Here's part of the verbose output. Now, there are some 'U' outputs mixed in here. Those have always been there, but the template has worked fine without that data. Is it possible this is tripping things up now?
![image](https://user-images.githubusercontent.com/12864741/50387785-6a152d80-06b9-11e9-88fc-0eb7f02b590e.png)
![image](https://user-images.githubusercontent.com/12864741/50387790-7ac5a380-06b9-11e9-9c37-13b27f9b5b31.png)

**Comment by cigamit** [comment]
Okay, well, you have Mark and my attention right now.  However, it's also xmas and I have stuff to drink too ;)  We did the collapse thing to reduce the clutter, but I get your point.

**Comment by eschoeller** [comment]
The collapse thing is ok:) I just realized I can individually select which ones to "open" and "close" which is helpful. Maybe the default should be open. I dunno. I have stuff to drink too:) And family to avoid! lol

**Comment by cigamit** [comment]
As long as there is not 'U' in anything that is indexed, you are okay.  Otherwise, Cacti is looking for a unique index.  If you think there will be lot's of 'U's in an indexed column, you might want to add the index type of nonunique to allow for bad indexes.

**Comment by cigamit** [comment]
<index_type>nonunique</index_type>

**Comment by eschoeller** [comment]
OK, sorry, shifting back to what this issue was originally opened for. 
I have collected some output with the new logging information:
```
2018/12/23 14:52:42 - REINDEX WARNING: Sort Field has Changed for Device[680] and DQ[2].  Old Sort:dskDevice, New Sort:dskIndex.  Re-mapping issues may occur!
2018/12/23 14:56:30 - REINDEX WARNING: Sort Field has Changed for Device[680] and DQ[2].  Old Sort:dskIndex, New Sort:dskDevice.  Re-mapping issues may occur!
2018/12/23 15:28:08 - REINDEX WARNING: Sort Field has Changed for Device[680] and DQ[2].  Old Sort:dskDevice, New Sort:dskIndex.  Re-mapping issues may occur!
```
I've found the problematic device and the associated data query. Honestly, this is data I really don't care about at all. It's the ucd/net monitored partitions template (could have guessed that from the dsk*) but it's for a device which I don't need this data for. So, I'm going to delete it. The device does timeout occasionally, but those timeout events do not always correlate with these reindex warning messages. This is a small embedded device which may not even fully implement the ucd disk RFC. I'll keep watching to see if something else trips up on this. I'd suspect at some point the interface statistics will also fall victim to this same issue

**Comment by cigamit** [comment]
I'm going to close this and the other ticket.  Once you get to 1.2 and have it in production, we can re-visit the topic.

**Comment by eschoeller** [comment]
I am still running into this sort field changed issue after upgrading to 1.2.3. 
It's scary as it starts to weasel it's way through my entire system. I have to manually change the Index Type and Index Value back to what they should be.

**Comment by fskale** [comment]
Hi, i ran into the same problem when updating from 0.8.8c.
I used the upgrade_database.php script which didn't give me an error.
Before enabling the poller, i did check the scripts.
So, the SNMP - Interface Statistics data query is handled by cacti and you changed the index order ? 
Why ?
What are the implications ?
Old:
<pre>
<index_order>ifDescr:ifName:ifHwAddr:ifIndex</index_order>
</pre>
New:
<pre>
<index_order>ifName:ifDescr:ifHwAddr:ifIndex</index_order>
</pre>
IMHO, i would simply change the xml to reflect the old sort order ?
Is my presumption right ?

Rgds.
Franz

**Comment by cigamit** [comment]
That's your call.  The movement to ifName as the default was a decision made with much discussion.  However, I strongly recommend you get to the 1.2.7 as soon as it's released.  We had some bumps in the road with 1.2.0 to 1.2.5.

**Comment by fskale** [comment]
@cigamit ,
thanks for the info.
Will repackage on monday.
We found some graphical issues and check if they have been fixed too.

**Comment by chrcoluk** [comment]
Hi cigamit, any public disclosure on the reasoning for the change?

Seems is still some more bumps as I have hit this problem as well, details here.

https://forums.cacti.net/viewtopic.php?f=21&t=59642&p=280119#p280119

For now I have disabled auto reindexing on my troublesome device.
