### ISSUE TITLE
[1.2.0 Beta 4] Perpetual Recache Events (APC Devices; Others)

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#2221]
Something happened on 11/7/2018 and I just started noticing it now, but there are lots of recache events for devices that are set to recache on a change in the UPTIME object ... but these devices are not rebooting that often.

```
grep "Recache Event" /var/log/cacti/cacti.log | cut -b 23-  | sort | uniq -c
   3576 PCOMMAND Device[121] WARNING: Recache Event Detected for Device
   3532 PCOMMAND Device[281] WARNING: Recache Event Detected for Device
   3532 PCOMMAND Device[282] WARNING: Recache Event Detected for Device
   3532 PCOMMAND Device[283] WARNING: Recache Event Detected for Device
   3532 PCOMMAND Device[284] WARNING: Recache Event Detected for Device
   3532 PCOMMAND Device[285] WARNING: Recache Event Detected for Device
   3532 PCOMMAND Device[286] WARNING: Recache Event Detected for Device
   3532 PCOMMAND Device[287] WARNING: Recache Event Detected for Device
   3532 PCOMMAND Device[288] WARNING: Recache Event Detected for Device
   3532 PCOMMAND Device[289] WARNING: Recache Event Detected for Device
   3532 PCOMMAND Device[290] WARNING: Recache Event Detected for Device
   3532 PCOMMAND Device[291] WARNING: Recache Event Detected for Device
   3532 PCOMMAND Device[292] WARNING: Recache Event Detected for Device
   3532 PCOMMAND Device[300] WARNING: Recache Event Detected for Device
   3532 PCOMMAND Device[301] WARNING: Recache Event Detected for Device
   3532 PCOMMAND Device[302] WARNING: Recache Event Detected for Device
   3576 PCOMMAND Device[390] WARNING: Recache Event Detected for Device
   3576 PCOMMAND Device[680] WARNING: Recache Event Detected for Device
```
That's from this month. Most of these are APC InRow cooling units. This the output from 1/4 pollers. The other 3 have almost no recache events, except for this one random linux machine (which given who runs it ... there could be other issues):

```
grep "Recache Event" /var/log/cacti/cacti.log | cut -b 23-  | sort | uniq -c
   1145 PCOMMAND Device[722] WARNING: Recache Event Detected for Device
```

**Comment by cigamit** [comment]
Do you think you have a timeout issue?

**Comment by eschoeller** [comment]
```2018/12/19 10:29:26 - SPINE: Poller[4] Device[281] HT[2] DQ[40] RECACHE OID: .1.3.6.1.2.1.1.3.0, (assert: 151507490 < output: 151507510)
```
sorry, in a hurry and can't look more closely right now. But that looks like a 20 second delta? Why is it triggering a recache? Or maybe my clocks are wrong on those devices ... ?

**Comment by eschoeller** [comment]
Yeah maybe, can't say for sure yet. Sorry I fired off these issues and now I'm racing to get on a plane. I'll really try to look into this more in 2-3 days.

**Comment by netniV** [comment]
If you could, we are hoping to get a release ready soon and until your last few issues, all other reports were very minor.  If there is a major issue, it'll need investigating/testing/delaying.

**Comment by eschoeller** [comment]
I’ll get back to it this afternoon 

Eric.

**Comment by eschoeller** [comment]
Where is this uptime information cached in the database?

**Comment by cigamit** [comment]
host.snmp_sysUpTimeInstance

**Comment by eschoeller** [comment]
Hmm. I didn't find the upTimeInstance there. Only in poller_reindex

**Comment by eschoeller** [comment]
```
Every 1.0s: /usr/local/mysql/bin/mysql -q -ss -u apache  cacti -e "select * from poller_reindex where host_id=281;"     Thu Dec 20 16:14:14 2018

281     40	0	1	<	162134460	.1.3.6.1.2.1.1.3.0
281     41	0	1	<	162134460	.1.3.6.1.2.1.1.3.0
```

```
Every 1.0s: snmpwalk -v2c -c public 192.168.10.7 .1.3.6.1.2.1.1.3.0                       Thu Dec 20 16:15:14 2018

DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (162222440) 18 days, 18:37:04.40
```

```
2018/12/20 16:15:21 - SPINE: Poller[4] Device[281] HT[6] DQ[41] RECACHE OID: .1.3.6.1.2.1.1.3.0, (assert: 162217360 < output: 162223200)
2018/12/20 16:15:22 - SPINE: Poller[4] Device[281] HT[1] DQ[40] RECACHE OID: .1.3.6.1.2.1.1.3.0, (assert: 162217360 < output: 162223230)
2018/12/20 16:15:22 - SPINE: Poller[4] Device[281] HT[1] DQ[41] RECACHE OID: .1.3.6.1.2.1.1.3.0, (assert: 162217360 < output: 162223230)
```

**Comment by eschoeller** [comment]
I've been looking at this a bit more today. There are certain scenarios where the recache events stop. What I've found in this scenario is that the poller_reindex data for this device is not synchronized between the remote poller and the main poller. The main poller will retain a very old uptime timeticks value while the remote poller updates the value every poller run. Then at some point both the local and remote poller_reindex data becomes updated for the device (however two data queries don't match, as seen below) and when this starts happening the recache events are kicked off every poller run. 

So this is what both DBs look like while the recache events are happening:
```
281     40      0       1       <       179024900       .1.3.6.1.2.1.1.3.0
281     41      0       1       <       179025150       .1.3.6.1.2.1.1.3.0
```

When things are working properly, the remote poller looks like this:
```
281     40      0       1       <       179072000       .1.3.6.1.2.1.1.3.0
281     41      0       1       <       179072000       .1.3.6.1.2.1.1.3.0
```
while the main poller looks like this:
```
281     40      0       1       <       179067380       .1.3.6.1.2.1.1.3.0
281     41      0       1       <       179067380       .1.3.6.1.2.1.1.3.0
```

Not sure if this helps at all.

**Comment by cigamit** [comment]
Taking a second look at this this morning.

**Comment by cigamit** [comment]
Okay, three files to update: lib/api_device.php, lib/poller.php, lib/data_query.php.  Please update and report back.

**Comment by eschoeller** [comment]
Applied the fixes. Sadly, I'm still seeing lots of recache events.

**Comment by netniV** [comment]
Are the recache events happening on the main or remote poller?

**Comment by eschoeller** [comment]
Remote poller. 

Eric.

**Comment by cigamit** [comment]
Any more updates since we patched the data query stuff?

**Comment by eschoeller** [comment]
OK, and here's something else that's super strange. I'm seeing recache events on this poller for devices that are running on a different poller. These devices were on this poller at one point, but were moved to another poller a day ago.

**Comment by cigamit** [comment]
Can you please goto Console > Data Collection > Data Collectors and edit each remote data collector and ensure that you can test the connection and everything works.  This is starting to sound like you have problems communicating to the remote database when you make changes to a device.

**Comment by eschoeller** [comment]
The "Test Connection" for each data collector passes.

**Comment by cigamit** [comment]
Okay, just made another change.  Let's see how that goes.  How often are you doing a full sync?

**Comment by cigamit** [comment]
Think I found the issue now in the last update to poller.php.  Re-caching should stop cold turkey.

**Comment by eschoeller** [comment]
ok, I upgraded to latest develop (couldn't apply those changes to my current version). I'll let it run and let you know. Probably 24 hours.

**Comment by eschoeller** [comment]
Darn, still have recache events. 44 of them, for just two devices. I'll re-assign them to a different poller and see what happens. The main poller and the other two remote pollers have no recache events.

**Comment by eschoeller** [comment]
done.

**Comment by eschoeller** [comment]
recache events are present on another poller now. Just three devices. I'm moving two of them back to the main poller. I'm going to take a closer look at the other one, I think it's a troubled device.

**Comment by eschoeller** [comment]
Hmm. One of the devices that was having recache problems actually produces this error on the device page:
![image](https://user-images.githubusercontent.com/12864741/50529911-ada2d980-0ab5-11e9-85b6-69b7a1d63fd8.png)

**Comment by cigamit** [comment]
Man, you are having sync issues.  Any chance we can do a remote session so I can take a closer look at your logs?  I would be interested to set your cacti.log's from the various pollers and the stderr logs.  You can email them to developers at cacti dot net.

**Comment by cigamit** [comment]
@eschoeller, happy new year.  We are still interested in taking a peek at your system and logs.

**Comment by eschoeller** [comment]
Yes, happy new year! Congrats on the 1.2.0 release, it's a big one! 
Sorry I owe you guys some updates. I had a slight mishap skiing so I'm running a little slower than normal right now. I'll get onto it soon. I am working on improving the logging between the remote pollers so that all the logs filter in through syslog to one place, but also keep logging individually. It should really help with the troubleshooting. 
One of the pollers is now dropping out periodically and polling nothing for about 30 minutes and then picking back up again. Seems like you're onto something that this could be a sync issue. Seems like something I need to catch "in the act". 
No more recache events though (and I have not applied your most recent lib/data_query.php patch yet)

**Comment by cigamit** [comment]
Well, I put some real good 'protections' in the final 1.2 product to prevent bad things from happening when recache does not go well.  So, it all ended good from my perspective.

**Comment by cigamit** [comment]
I'm going to close this and the other ticket.  Once you get to 1.2 and have it in production, we can re-visit the topic.

**Comment by eschoeller** [comment]
For what it's worth, the problematic poller had the same type of trouble after a 1.2.3 upgrade. I evacuated all the devices from it and got this message along the way:
```
2019/04/28 18:34:11 - CMDPHP ERROR: A DB Exec Failed!, Error: Duplicate entry '2-3-413' for key 'PRIMARY'
2019/04/28 18:34:11 - CMDPHP SQL Backtrace:  (/poller_commands.php[146]:api_device_purge_from_remote(), /lib/api_device.php[105]:db_execute_prepared())
2019/04/28 18:34:11 - CMDPHP ERROR: A DB Exec Failed!, Error: Duplicate entry '2-3-523' for key 'PRIMARY'
2019/04/28 18:34:11 - CMDPHP SQL Backtrace:  (/poller_commands.php[146]:api_device_purge_from_remote(), /lib/api_device.php[105]:db_execute_prepared()
```
It then proceeded to produce this logging:

```
2019/04/28 19:00:03 - SYSTEM STATS: Time:1.1114 Method:spine Processes:1 Threads:16 Hosts:1 HostsPerProcess:1 DataSources:0 RRDsProcessed:0
2019/04/28 19:01:03 - SYSTEM STATS: Time:1.1150 Method:spine Processes:1 Threads:16 Hosts:1 HostsPerProcess:1 DataSources:0 RRDsProcessed:0
2019/04/28 19:02:02 - SYSTEM STATS: Time:1.1135 Method:spine Processes:1 Threads:16 Hosts:1 HostsPerProcess:1 DataSources:0 RRDsProcessed:0
2019/04/28 19:03:03 - SYSTEM STATS: Time:1.1122 Method:spine Processes:1 Threads:16 Hosts:1 HostsPerProcess:1 DataSources:0 RRDsProcessed:0
2019/04/28 19:04:03 - SYSTEM STATS: Time:1.1125 Method:spine Processes:1 Threads:16 Hosts:1 HostsPerProcess:1 DataSources:0 RRDsProcessed:0
2019/04/28 19:05:02 - SYSTEM STATS: Time:0.0061 Method:spine Processes:1 Threads:16 Hosts:0 HostsPerProcess:0 DataSources:0 RRDsProcessed:0
2019/04/28 19:06:01 - SYSTEM STATS: Time:0.0061 Method:spine Processes:1 Threads:16 Hosts:0 HostsPerProcess:0 DataSources:0 RRDsProcessed:0
2019/04/28 19:07:01 - SYSTEM STATS: Time:0.0047 Method:spine Processes:1 Threads:16 Hosts:0 HostsPerProcess:0 DataSources:0 RRDsProcessed:0
```
So it randomly at some point gave up on the last phantom device. Once it was free and clear of all devices I moved them all back over. Something got buggered up in the database I guess. Typical for me!
