### ISSUE TITLE
[1.2.0 Beta 4] : fakepath for import

### ISSUE THREAD

**Issue by jackouille-ch** [Cacti/cacti#2223]
Hi Folks

I used commit  2c0de32  (but it is till the same since 1.2.0 Beta 1) and I cannot import a template:
I enter the right path on my local Windows machine (Server is CentOS7) but my path is always changed to fakepath:
![image](https://user-images.githubusercontent.com/35721406/50248350-05b54e00-03db-11e9-9eb8-163c81be2744.png)

What should I do to correct this issue ?

**Comment by netniV** [comment]
Nothing.  This is actually the browsers doing and is intended to mask the real location of the file. The upload should still work.

**Comment by jackouille-ch** [comment]
Unfortunately not, despite the fakepath displayed, no data are imported: I never see the import result and my template for Synology is not present within my Device Template list.
Could you please test it on your side?
By the way I either must import other templates, especially for Linux because some graph data are missing since the switch from 0.8.8 to 1.2.0, I found the template but cannot import them.

**Comment by netniV** [comment]
You can use the cli program that also imports graphs, but what OS/Browser are you using to do the upload?

**Comment by jackouille-ch** [comment]
For Uploading I am using Windows 7x64 Pro with Firefox 64x64.
Which commands can I use with CLI ? Wasn't knowking about his feature...

**Comment by netniV** [comment]
No, sorry busy times at work and home.

**Comment by cigamit** [comment]
Please open the debug window on your browser and then the console tab and look for JavaScript errors.  I have tested both the current import and export and they are functioning perfectly.  You either have a server side rule, or a browser extension or plugin that is causing this issue.  There may be also some php specific error.  You should edit your apache's php.ini file and set the error_log = /tmp/somefile.log, and then check that log for errors as well.  Remember to restart apache after making that change.

**Comment by jackouille-ch** [comment]
Great thanks, that helps, here is the error message:
2018/12/23 19:02:33 - IMPORT parse_xml_hash ERROR wrong hash format for hash: hash_02a7a07b84c8dfaa27a6742fb48e80e45b

**Comment by jackouille-ch** [comment]
I also try to import netsnmp from https://docs.cacti.net/templates

And here is my error:
2018/12/23 19:09:24 - IMPORT parse_xml_hash ERROR wrong hash format for hash: info

Hoping this might help

**Comment by cigamit** [comment]
Yea, let me look at the xml file.  This xml may have been created pre the official 1.x release.  Will take a look in either case.

**Comment by netniV** [comment]
If this is to do with the NetSNMP memory template, I did a repo to hold the latest version I could find of it and have it work for 1.x here:
https://github.com/netniV/cacti-netsnmp-memory

I believe that was only for the memory portion though.

**Comment by cigamit** [comment]
Closing this now.

**Comment by jackouille-ch** [comment]
Thanks Cigamit, it works now fine.
@ netniV: I was not able to timport your file, I receive another error. Tested before and after commit from Cigamit. Just for your info.

**Comment by cigamit** [comment]
Was this from a working Cacti 1.2 instance?

**Comment by cigamit** [comment]
Please attach your xml file that failed please.

**Comment by jackouille-ch** [comment]
No idea if it was working before.
Here is one file (from netniV) that I cannot import.
[netsnmp_device.zip](https://github.com/Cacti/cacti/files/2716573/netsnmp_device.zip)

In fact for all my Linux devices, I cannot collect volume usage, I got empty graphs. I suspect that I import old templates (from 0.8.8), that's why I was trying to reimport the default templates.

**Comment by cigamit** [comment]
Closing in that we are dealing with a package and not a template.
