### ISSUE TITLE
CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())

### ISSUE THREAD

**Issue by tyit** [Cacti/cacti#2224]
![wx20181221-165125](https://user-images.githubusercontent.com/31933126/50333650-036d0400-0541-11e9-9aea-382b07a76985.png)

**Comment by netniV** [comment]
This is not actually a cacti issue but an issue with the libraries for RRDTool.  Ensure you have updated the libraries that RRDTool dependsd on as it would appear there is a missing function name.
