### ISSUE TITLE
The new version of the phone display does not look good

### ISSUE THREAD

**Issue by tyit** [Cacti/cacti#2226]
![wx20181221](https://user-images.githubusercontent.com/31933126/50341360-6e2a3980-0559-11e9-8446-9286864feb02.png)
![wx20181222](https://user-images.githubusercontent.com/31933126/50341364-71252a00-0559-11e9-99d2-7c8839a84f34.png)

 How can the new version of the layout be the same as the old one?

Thank you

**Comment by cigamit** [comment]
This has been resolved today.  Thanks for letting us know.
