### ISSUE TITLE
Undefined variable: poller_id

### ISSUE THREAD

**Issue by sd3m0n** [Cacti/cacti#223]
Here is the log (right after login):

CMDPHP PHP ERROR NOTICE Backtrace: (/index.php: 76 CactiErrorHandler)(/lib/functions.php: 4230 cacti_debug_backtrace)
ERROR PHP NOTICE: Undefined variable: poller_id in file: /mnt/data1/web/cacti/index.php on line: 76

Can you please help with this error.

**Comment by smiles1969** [comment]
Do you have:


$poller_id = 1;

defined in your include/config.php file?

**Comment by cigamit** [comment]
Yea, that's the source.  However, I changed it to $config['poller_id'].  That should do it.  Resolved.

**Comment by smiles1969** [comment]
Haha, just trying to help with the easy ones..

**Comment by sd3m0n** [comment]
Thank's )
