### ISSUE TITLE
Allow for Purging of Data Source Statistics from the GUI

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#2236]
The MySQL tables for the data source statistics have grown to 1.3GB on my system. I'm not sure if this is by design, if it's normal, or what. It could likely be due to the errors I'm still getting with dsstats (which I'm going to disable for now). 
But, I think it would be a good idea to have a function in place to clear these statistics out of the db so you can start over.
```
du -hsc data_source_stats_*ibd
401M    data_source_stats_daily.ibd
14M     data_source_stats_hourly.ibd
341M    data_source_stats_hourly_cache.ibd
14M     data_source_stats_hourly_last.ibd
173M    data_source_stats_monthly.ibd
177M    data_source_stats_weekly.ibd
161M    data_source_stats_yearly.ibd
1.3G    total
```

**Comment by eschoeller** [comment]
My settings:
![image](https://user-images.githubusercontent.com/12864741/50506899-42ff8880-0a38-11e9-9e56-7c92191676bd.png)

**Comment by eschoeller** [comment]
Just a bit of poking around ... I found that a data source had 138 rows associated with it when the template itself only has 2 data items associated with it. So there's tons of garbage that's been accumulated into these tables.

**Comment by cigamit** [comment]
Good idea.  Marking as a feature request.  Data Source Statistics will rebuild things when re-enabled.

**Comment by TheWitness** [comment]
This is fixed now.
