### ISSUE TITLE
Allow Import and Export to be more controlled

### ISSUE THREAD

**Issue by cigamit** [Cacti/cacti#2239]
I oftentimes have a situation where I find a Device Template that someone has published, but unfortunately, it attempts to alter some Data Queries and Graph Templates that I do now want altered.

I would prefer if the import would take two steps.  The first step would be to validate what is in the XML file, then the second step would allow the user to import just what components they wish from the XML file.

In my case above, I would avoid, for example, importing a legacy Interface template that is not what I wish to use long term.

**Comment by TheWitness** [comment]
Marking this one as resolved since we added Selective Import in 1.2.23 which solves the purpose and making selective Export mute.

**Comment by TheWitness** [comment]
Resolved here:

https://github.com/Cacti/cacti/issues/4820

and here:

https://github.com/Cacti/cacti/issues/4762
