### ISSUE TITLE
Cacti Database error

### ISSUE THREAD

**Issue by SayeedG** [Cacti/cacti#2249]
Hi Team,

I have been stuck with this error when trying to create any graphs of my devices:

CMDPHP: Poller[0] ERROR: SQL Assoc Failed!, Error:'1146', SQL:"select data_template_data.rrd_step, rra.x_files_factor, rra.steps, rra.rows, rra_cf.consolidation_function_id, (rra.rows*rra.steps) as rra_order from data_template_data left join data_template_data_rra on (data_template_data.id=data_template_data_rra.data_template_data_id) left join rra on (data_template_data_rra.rra_id=rra.id) left join rra_cf on (rra.id=rra_cf.rra_id) where data_template_data.local_data_id=88 and (rra.steps is not null or rra.rows is not null) order by rra_cf.consolidation_function_id,rra_order"
--
12/31/2018 12:50:15 PM - CMDPHP: Poller[0] ERROR: There are no RRA's assigned to local_data_id: 88.

**When I run a mysqlcheck on the database this is the output:**

cacti.aggregate_graph_templates                    OK
cacti.aggregate_graph_templates_graph              OK
cacti.aggregate_graph_templates_item               OK
cacti.aggregate_graphs                             OK
cacti.aggregate_graphs_graph_item                  OK
cacti.aggregate_graphs_items                       OK
cacti.automation_devices                           OK
cacti.automation_graph_rule_items                  OK
cacti.automation_graph_rules                       OK
cacti.automation_ips
note     : The storage engine for the table doesn't support check
cacti.automation_match_rule_items                  OK
cacti.automation_networks                          OK
cacti.automation_processes
note     : The storage engine for the table doesn't support check
cacti.automation_snmp                              OK
cacti.automation_snmp_items                        OK
cacti.automation_templates                         OK
cacti.automation_tree_rule_items                   OK
cacti.automation_tree_rules                        OK
cacti.cdef                                         OK
cacti.cdef_items                                   OK
cacti.color_template_items                         OK
cacti.color_templates                              OK
cacti.colors                                       OK
cacti.data_input                                   OK
cacti.data_input_data                              OK
cacti.data_input_fields                            OK
cacti.data_local                                   OK
cacti.data_source_profiles                         OK
cacti.data_source_profiles_cf                      OK
cacti.data_source_profiles_rra                     OK
cacti.data_source_purge_action                     OK
cacti.data_source_purge_temp                       OK
cacti.data_source_stats_daily                      OK
cacti.data_source_stats_hourly                     OK
cacti.data_source_stats_hourly_cache
note     : The storage engine for the table doesn't support check
cacti.data_source_stats_hourly_last
note     : The storage engine for the table doesn't support check
cacti.data_source_stats_monthly                    OK
cacti.data_source_stats_weekly                     OK
cacti.data_source_stats_yearly                     OK
cacti.data_template                                OK
cacti.data_template_data                           OK
cacti.data_template_rrd                            OK
cacti.external_links                               OK
cacti.graph_local                                  OK
cacti.graph_template_input                         OK
cacti.graph_template_input_defs                    OK
cacti.graph_templates                              OK
cacti.graph_templates_gprint                       OK
cacti.graph_templates_graph                        OK
cacti.graph_templates_item                         OK
cacti.graph_tree                                   OK
cacti.graph_tree_items                             OK
cacti.host                                         OK
cacti.host_graph                                   OK
cacti.host_snmp_cache                              OK
cacti.host_snmp_query                              OK
cacti.host_template                                OK
cacti.host_template_graph                          OK
cacti.host_template_snmp_query                     OK
cacti.plugin_config                                OK
cacti.plugin_db_changes                            OK
cacti.plugin_hooks                                 OK
cacti.plugin_realms                                OK
cacti.poller                                       OK
cacti.poller_command                               OK
cacti.poller_data_template_field_mappings          OK
cacti.poller_item                                  OK
cacti.poller_output
note     : The storage engine for the table doesn't support check
cacti.poller_output_boost                          OK
cacti.poller_output_boost_processes
note     : The storage engine for the table doesn't support check
cacti.poller_output_realtime                       OK
cacti.poller_reindex                               OK
cacti.poller_resource_cache                        OK
cacti.poller_time                                  OK
cacti.reports                                      OK
cacti.reports_items                                OK
cacti.sessions                                     OK
cacti.settings                                     OK
cacti.settings_tree                                OK
cacti.settings_user                                OK
cacti.settings_user_group                          OK
cacti.sites                                        OK
cacti.snmp_query                                   OK
cacti.snmp_query_graph                             OK
cacti.snmp_query_graph_rrd                         OK
cacti.snmp_query_graph_rrd_sv                      OK
cacti.snmp_query_graph_sv                          OK
cacti.snmpagent_cache                              OK
cacti.snmpagent_cache_notifications                OK
cacti.snmpagent_cache_textual_conventions          OK
cacti.snmpagent_managers                           OK
cacti.snmpagent_managers_notifications             OK
cacti.snmpagent_mibs                               OK
cacti.snmpagent_notifications_log                  OK
cacti.user_auth                                    OK
cacti.user_auth_cache                              OK
cacti.user_auth_group                              OK
cacti.user_auth_group_members                      OK
cacti.user_auth_group_perms                        OK
cacti.user_auth_group_realm                        OK
cacti.user_auth_perms                              OK
cacti.user_auth_realm                              OK
cacti.user_domains                                 OK
cacti.user_domains_ldap                            OK
cacti.user_log                                     OK
cacti.vdef                                         OK
cacti.vdef_items                                   OK
cacti.version                                      OK

**Please assist; thank you!**

**Comment by cigamit** [comment]
What version of Cacti?  Looks like old stuff.

**Comment by SayeedG** [comment]
0.8.8f, this was the version that automatically downloaded using apt-get. I am running Ubuntu 16.

**Comment by SayeedG** [comment]
Thank you very much. To reiterate, I should do a fresh install with cacti 1.1.38?

**Comment by netniV** [comment]
If you have not started using the system in anger yet, yes I would advise that.

**Comment by cigamit** [comment]
Well, I hope you have a backup, cause unless it's the RRA table, you are going to have problems getting back into business.  Since this is not a bug, I'm going to push the back to the forums.  It's always good to do backups.  We will put that function into Cacti soon enough.  But that's is not an excuse for not doing backups.

**Comment by cigamit** [comment]
Ope, I just noticed that your database is already at version 1.  But you query is asking for the rra table.  You likely have a poorly migrated plugin, or some script in the scripts directory.  You will have to grep for parts of this query in your install.  But it's not a Cacti issue.

**Comment by SayeedG** [comment]
Thank you!

**Comment by netniV** [comment]
For some reason, you have an extra / at the end of your filepath

**Comment by SayeedG** [comment]
When I delete the extra ‘/‘ in the GUI and refresh it reverts back with the / and the error. Should I just delete the ‘/‘ and move forward?
