### ISSUE TITLE
realtime with remote poller

### ISSUE THREAD

**Issue by Carlimeunier** [Cacti/cacti#225]
When I try to made realtime with host polls by a remote poller, i have an error 

- In the main poller : 
`2017-01-20 14:02:00 - CMDPHP PHP ERROR NOTICE Backtrace: (/cmd_realtime.php: 137 CactiErrorHandler)(/lib/functions.php: 4230 cacti_debug_backtrace)
2017-01-20 14:02:00 - ERROR PHP NOTICE: Undefined variable: local_data_id in file: /data/www/cacti/cmd_realtime.php on line: 137`

- In the remote poller : 
`2017-01-20 14:02:00 - CMDPHP PHP ERROR NOTICE Backtrace: (/remote_agent.php: 48 poll_for_data)(/remote_agent.php: 360 CactiErrorHandler)(/lib/functions.php: 4230 cacti_debug_backtrace)
2017-01-20 14:02:00 - ERROR PHP NOTICE: Undefined variable: output in file: /data/www/cacti/remote_agent.php on line: 360`

I think the **local_data_id**  in the remote url should be replaced by $data_source ( around line 131 cmd_realtime.php)

Thanks

**Comment by cigamit** [comment]
Thanks for reporting this.

**Comment by cigamit** [comment]
Resolved, thanks!
