### ISSUE TITLE
DB Errors

### ISSUE THREAD

**Issue by mdrons** [Cacti/cacti#2252]
I am seeing these errors in the log after an git update to the most recent version.

Database says it is upgraded to release 1.2.0
2019/01/02 17:10:01 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'deleted' in 'where clause'
2019/01/02 17:10:01 - CMDPHP SQL Backtrace:  (/poller.php[350]:db_fetch_assoc_prepared(), /lib/database.php[463]:db_execute_prepared())
2019/01/02 17:10:01 - ERROR PHP WARNING: array_merge(): Argument #2 is not an array in file: /var/www/html/cacti/poller.php  on line: 350
2019/01/02 17:10:01 - CMDPHP PHP ERROR WARNING Backtrace:  (/poller.php[350]:array_merge(), CactiErrorHandler())
2019/01/02 17:10:01 - ERROR PHP WARNING: Invalid argument supplied for foreach() in file: /var/www/html/cacti/poller.php  on line: 562
2019/01/02 17:10:01 - CMDPHP PHP ERROR WARNING Backtrace:  (/poller.php[562]:CactiErrorHandler())
2019/01/02 17:10:01 - SYSTEM STATS: Time:0.1734 Method:spine Processes:1 Threads:1 Hosts:-1 HostsPerProcess:-1 DataSources:36606 RRDsProcessed:0
2019/01/02 17:10:02 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'last_sync' in 'where clause'
2019/01/02 17:10:02 - CMDPHP SQL Backtrace:  (/poller.php[767]:poller_replicate_check(), /poller.php[798]:db_fetch_assoc(), /lib/database.php[449]:db_fetch_assoc_prepared(), /lib/database.php[463]:db_execute_prepared())
2019/01/02 17:10:02 - ERROR PHP WARNING: Invalid argument supplied for foreach() in file: /var/www/html/cacti/poller.php  on line: 800
2019/01/02 17:10:02 - CMDPHP PHP ERROR WARNING Backtrace:  (/poller.php[767]:poller_replicate_check(), /poller.php[800]:CactiErrorHandler())
2019/01/02 17:10:05 - SYSTEM THOLD STATS: Time:0.7113 Tholds:0 TotalDevices:96 DownDevices:2 NewDownDevices:0
2019/01/02 17:10:05 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'deleted' in 'where clause'
2019/01/02 17:10:05 - CMDPHP SQL Backtrace:  (/poller_maintenance.php[146]:api_device_purge_deleted_devices(), /lib/api_device.php[109]:db_fetch_assoc_prepared(), /lib/database.php[463]:db_execute_prepared())
2019/01/02 17:10:05 - SYSTEM WEBSEER STATS: Total Time:0.002, Service Checks:0, Servers:0

not sure where to begin looking and where the issue might be.

Thanks, Mike

**Comment by cigamit** [comment]
You must have been using an older 1.2 or develop branch.  Rung the database cli:

`php -q update_database.php --forcever=1.1.38`

That will fix it.  However, please let us know from what version you upgraded.

**Comment by hmorandell** [comment]
Hi,

the correct command is: 

php -q upgrade_database.php --forcever=1.1.38

(not update)

and it worked for me!

thanks!

**Comment by mdrons** [comment]
that fixed the issue.   I had tried that command before but used 1.2.0 as the forced version.

Thanks,
Mike
