### ISSUE TITLE
Spine configuration file path is blank on Windows

### ISSUE THREAD

**Issue by BSOD2600** [Cacti/cacti#2254]
This was reported and apparently fixed in https://github.com/Cacti/cacti/issues/2046 but its back with the latest beta.

![image](https://user-images.githubusercontent.com/5741811/50624048-21107500-0f14-11e9-8c02-8569f96545cf.png)

In the Installation Wizard, on the Critical Binary Locations and Versions page, the Spine Config File Path is empty during a Windows install.   Instead of setting it blank, at the very least should default to c:/spine/spine.conf  and/or try a few common locations for Spine.exe.  Even better is to use the WHERE command to see if spine (and the other windows binaries) are already in the PATH and locatable.

**Comment by netniV** [comment]
Thanks @BSOD2600, I will take a look at making this work right under a windows environment.  I was sure we had addressed this already but I'll take on the further enhancements too.

**Comment by netniV** [comment]
@BSOD2600 is this still and issue with 1.2.5?

**Comment by BSOD2600** [comment]
Yes, this is still an issue with latest 1.2.5 dev branch.

![image](https://user-images.githubusercontent.com/5741811/60938941-c7a24d80-a28a-11e9-8d32-17f6cabdc708.png)

**Comment by netniV** [comment]
Looking at the code, this path is never set by Cacti or the installer whether it is windows or linux.  The spine program does have defaults for the location of its configuration file, so maybe the configuration file isn't in a default place that spine is looking at if the field is empty ?

This field is also marked as optional so I do not believe that it should be an issue.

**Comment by cigamit** [comment]
Correct.  As a result, closing.
