### ISSUE TITLE
Problems after upgrade 1.2.0-beta4 to 1.2.0 final

### ISSUE THREAD

**Issue by hmorandell** [Cacti/cacti#2255]
Hi,
after upgrading my installtion all host dissapeared in the device view, although in the database they are still there.
in the logfile I see:

```
2019/01/03 08:27:02 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php[582]:CactiErrorHandler())
--
2019/01/03 08:27:02 - ERROR PHP WARNING: Invalid argument supplied for foreach() in file: /var/www/html/poller.php on line: 582
2019/01/03 08:27:02 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php[370]:array_merge(), CactiErrorHandler())
2019/01/03 08:27:02 - ERROR PHP WARNING: array_merge(): Argument #2 is not an array in file: /var/www/html/poller.php on line: 370
2019/01/03 08:27:02 - CMDPHP SQL Backtrace: (/poller.php[370]:db_fetch_assoc_prepared(), /lib/database.php[463]:db_execute_prepared())
2019/01/03 08:27:02 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'deleted' in 'where clause'
2019/01/03 08:26:04 - CMDPHP SQL Backtrace: (/poller_maintenance.php[146]:api_device_purge_deleted_devices(), /lib/api_device.php[109]:db_fetch_assoc_prepared(), /lib/database.php[463]:db_execute_prepared())
```

and the devices in the sql are all now escaped strangely with \" \" and so on...?!?

the install script says eveything is fine... but nothing works now... any idea?

**Comment by hmorandell** [comment]
running:

php -q upgrade_database.php --forcever=1.1.38

from CLI folder seemed to have fixed the problem.... I check now evereything and will let you know if this issue can be closed!

**Comment by netniV** [comment]
That is correct.  There was one extra column added after Beta 4 requiring a database upgrade again.  In the future, we will try to make it so that beta and full releases can be upgraded from properly.  Running the above is the correct solution.
