### ISSUE TITLE
When changing system default language, Polish still seems to be shown when English selected

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#2261]
I changed to Polish and get back to English in Settings.

Now I have got 50/50.

Just look
![ui-language](https://user-images.githubusercontent.com/17087236/50634032-9d737a00-0f4d-11e9-8fd5-cd6432fdef95.png)

**Comment by netniV** [comment]
You are changing the system default language if a user does not have a language.  You will also need to modify your own language under Edit Profile (top right) as the system has already saved a preference for your account.

**Comment by interduo** [comment]
I have set:
`Default language for this system: English`

`User Language: Defines the preferred GUI language: Angielski`

**Comment by netniV** [comment]
So, you also changed it by going to Edit Profile:
![image](https://user-images.githubusercontent.com/9052188/50635012-6cdd1180-0f48-11e9-9a2b-9e9c5eb4d9ef.png)

Then User Language?
![image](https://user-images.githubusercontent.com/9052188/50635050-90a05780-0f48-11e9-9730-1c0e4672e8d2.png)

**Comment by interduo** [comment]
I changed to Bulgarian then back to English and It looks corectly.
