### ISSUE TITLE
When a page is rendered and user does not have permission errorimage should show reasonable output

### ISSUE THREAD

**Issue by DavidLiedke** [Cacti/cacti#2262]
![2019-01-03_12-25-16](https://user-images.githubusercontent.com/25581728/50635646-4bcdee00-0f53-11e9-86f7-a8ab9b185853.gif)

After i get the "Permission Denied" Error (#2259) and i want to go back over the tree menu on the left side. In this situation i cant do anything in the webinterface until i reload the whole site.

If i go back over the "Return" Button in the "Permission Denied" Message i have no problems.

**Comment by cigamit** [comment]
Duplicate of #2259

**Comment by netniV** [comment]
I believe that whilst issue #2259 did cause this issue to be shown, the underlying problem still exists were a permission denied page will cause the UI to break.

**Comment by TheWitness** [comment]
This is fixed isn't it?  @DavidLiedke can you confirm on the 1.2.x branch?

**Comment by TheWitness** [comment]
This one has been resolved for a while.
