### ISSUE TITLE
Graph Field Limits Save Failed: Field Input Error - |query_ifSpeed|

### ISSUE THREAD

**Issue by flippind** [Cacti/cacti#2265]
I'm running into the same issue reported in [this forum thread](https://forums.cacti.net/viewtopic.php?f=2&t=49814&hilit=+query_ifSpeed+in+upper+limit+for+graph+template).  Noticed the last hit on the thread suggests the bug report, but I'm unable to find existing.  In my case, I am able to pull the expected value in the graph title via |query_ifSpeed| but am unable to populate that variable in either individual graphs nor graph template.  Attempts to suggest via the associated Data Query Suggested Values -graphs (specifically upper-limit) has no discernible effect.   It looks like this may have been [resolved in the 0.8.8 release](https://web.archive.org/web/20120322074034/http://bugs.cacti.net/view.php?id=1585), but [returned as early as 0.8.8b](https://forums.cacti.net/viewtopic.php?p=178473)

```
   Total: 0.310000, Delta: 0.000000, Located input field 'ifSpeed' [walk]
   --
   Total: 0.350000, Delta: 0.040000, Executing SNMP walk for data @ '.1.3.6.1.2.1.2.2.1.5'
   Found item [ifSpeed='1000000000'] index: 1 [from value]
   Found item [ifSpeed='1000000000'] index: 2 [from value]
   Found item [ifSpeed='20000000'] index: 3 [from value]
   
   Cacti Version | 1.1.38
   Cacti OS | unix
   NET-SNMP Version | NET-SNMP version: 5.7.2
   RRDtool Version | RRDtool 1.4.x
```

In this image you can see the error thrown when using |query_ifSpeed| in the Graph Fields.  Note that the graph title is successfully using |query_ifSpeed|.
![1-3-2019 8-28-33 am](https://user-images.githubusercontent.com/39351714/50645815-a35b6200-0f31-11e9-9672-8268f39fc763.jpg)

**Comment by cigamit** [comment]
Looks like a nice enhancement request.

**Comment by TheWitness** [comment]
Oh this is interesting, there is all sorts of code for this in the code, but you can not save in the template.  Actually you can in the Graph Template "Graph Template Input" section, but that seems to be have been removed from the default template some releases ago.  @gan-dalf had written this in almost a decade ago.
