### ISSUE TITLE
[1.2.0] The given path is misformatted or contained invalid characters

### ISSUE THREAD

**Issue by BSOD2600** [Cacti/cacti#2266]
Noticed the following errors in apache's error log, which appear to be related to the install wizard.

Windows 2012 R2
Apache 2.4.37
IE11

> 
> [Thu Jan 03 21:11:00.095217 2019] [mpm_winnt:notice] [pid 2104:tid 380] AH00455: Apache/2.4.37 (Win64) configured -- resuming normal operations
> [Thu Jan 03 21:11:00.095217 2019] [mpm_winnt:notice] [pid 2104:tid 380] AH00456: Apache Lounge VC15 Server built: Nov 21 2018 11:51:35
> [Thu Jan 03 21:11:00.095217 2019] [core:notice] [pid 2104:tid 380] AH00094: Command line: 'C:\\Apache24\\bin\\httpd.exe -d C:/Apache24'
> [Thu Jan 03 21:11:00.095217 2019] [mpm_winnt:notice] [pid 2104:tid 380] AH00418: Parent: Created child process 3116
> [Thu Jan 03 21:11:00.345205 2019] [mpm_winnt:notice] [pid 3116:tid 416] AH00354: Child: Starting 64 worker threads.
> [Thu Jan 03 21:11:05.798452 2019] [core:error] [pid 3116:tid 940] (20024)The given path is misformatted or contained invalid characters: [client ::1:49235] AH00127: Cannot map GET /cacti/C:/Apache24/htdocs/cacti/include/js/LC_MESSAGES/jquery.ui.datepicker-english_usa.js?f24d22dcdfc1748eb5c0093681bfb361 HTTP/1.1 to file, referer: http://localhost/cacti/install/install.php
> [Thu Jan 03 21:15:14.741579 2019] [core:error] [pid 3116:tid 940] (20024)The given path is misformatted or contained invalid characters: [client ::1:49374] AH00127: Cannot map GET /cacti/C:/Apache24/htdocs/cacti/include/js/LC_MESSAGES/jquery.ui.datepicker-english_usa.js?f24d22dcdfc1748eb5c0093681bfb361 HTTP/1.1 to file, referer: http://localhost/cacti/

**Comment by cigamit** [comment]
Seems like possibly an Apache bug on Windows.

**Comment by cigamit** [comment]
@BSOD2600, can you please verify that this issue continues with the current 1.2.5/develop branch?

**Comment by cigamit** [comment]
@BSOD2600, one more bump before I close this one.

**Comment by BSOD2600** [comment]
These errors no longer occur.
