### ISSUE TITLE
Remove unnecessary includes in aggregate template code

### ISSUE THREAD

**Issue by woutd** [Cacti/cacti#2267]
Got an include error with Cacti 1.2.0:
`2019/01/04 10:14:47 - ERROR PHP WARNING: include_once(/XXX/cacti-1.2.0/api_aggregate.php): failed to open stream: No such file or directory in file: /XXX/cacti-1.2.0/aggregate_templates.php  on line: 259`

The line reads:
`	include_once($config['base_path'] . '/api_aggregate.php');`

I think this should be:
`	include_once($config['base_path'] . '/lib/api_aggregate.php');`

**Comment by cigamit** [comment]
Resolved.
