### ISSUE TITLE
Feature Request: Data Profiles

### ISSUE THREAD

**Issue by DavidLiedke** [Cacti/cacti#2268]
Console --> Presets --> Data Profiles --> Profile X 
---> Consolidation Functions
![firefox_2019-01-04_10-42-59](https://user-images.githubusercontent.com/25581728/50681997-afb4ed00-100d-11e9-890f-d48d1a3ef0d2.png)

If the data profile is used and read only i am unable to see the two selected "Consolidation Functions".

It would also be nice to be able to copy an existing data profile.

**Comment by cigamit** [comment]
This one seems pretty trivial and yes, a little problematic when the profile is Disabled.  After a small code review, it looks also like I was in the middle of implementing the Duplicate function, but likely moved on to more pressing issues at the time.

**Comment by TheWitness** [comment]
One line change.  No sense in keeping it a feature enhancement.  It's a usability bug.

**Comment by DavidLiedke** [comment]
> It would also be nice to be able to copy an existing data profile.

This was the reason for the feature request.

**Comment by TheWitness** [comment]
Oh, well, I thought it was the can not view.  Okay.  Let me see about re-opening 👍

**Comment by TheWitness** [comment]
I was in low hanging fruit mode, just crushing features.  Thanks for checking my math.

**Comment by TheWitness** [comment]
@DavidLiedke, your wish is my command.  Thanks for sticking with the team!
