### ISSUE TITLE
[1.2.0] Mistranslation in /cacti/locales/po/german_germany.po

### ISSUE THREAD

**Issue by TIKA0902** [Cacti/cacti#2269]
Hi all!

In sites.php "Latitude" is translated as "Längengrad". That would have to be called "Breitengrad".

Greetings and thank you!

**Comment by TIKA0902** [comment]
Sorry, that's beyond my current time budget. I've just seen a beautician error: "Automation / Discovered Devices" should be called "Erkannte Geräte".

Regards

**Comment by cigamit** [comment]
We are preparing a site where all you have to do is register, search for the term and fix it.  Easier actually than opening this bug.  We will formally announce it as soon as we have our minds made up about a few things.

**Comment by cigamit** [comment]
Closing as this is really dealing with the broader issue of making sure we can do better than Google.
