### ISSUE TITLE
incorrect datetime format

### ISSUE THREAD

**Issue by vaultwiki** [Cacti/cacti#227]
Most MySQL queries fail because the default value of 0000-00-00 00:00:00 which is used for many database tables' fields is an incorrect datetime format. The default value should be 1970-01-01 00:00:00

I was able to create a host/device by issuing the insert query directly to the MySQL server with the corrected datetime values.

This is one of many errors I have encountered that has made Cacti unusable:
- There was an infinite redirect loop after first login w/ admin, admin. It appears that this is due to a webbasic_enabled config value which is set to NULL by default, and should probably be 'on'. I had to comment out the redirect to auth_changepassword.php in the source code, and manually access it. My understanding is that this leaves Cacti vulnerable. Anyway, people should not need to figure this out - a similar issue was reported on the forums in March 2016 and never received a response.
- Once the admin password is changed, and we can access the control panel, we have issues because the control panel overuses AJAX. Every AJAX request fails because the server thinks the user is not logged in. Rather than showing the login screen, the user is given a blank main frame. Thus every action in the control panel is inaccessible unless the URL is manually accessed. It appears that this might be related to the auth type not being set to web-basic, or the auth-cache not being on. Eventually this stopped happening to me after modifying a lot of files and changing various settings.
- However, it is not possible for me to create any graphs because of a Javascript error which makes the Create > New Graphs page blank: Uncaught ReferenceError: gt_created_graphs is not defined
    at HTMLTableRowElement.<anonymous> (layout.js:289)
    at Function.each (jquery.js:368)
    at jQuery.fn.init.each (jquery.js:157)
    at applySelectorVisibilityAndActions (layout.js:286)
    at applySkin (layout.js:476)
    at Object.success (layout.js:555)
    at fire (jquery.js:3243)
    at Object.fireWith [as resolveWith] (jquery.js:3373)
    at done (jquery.js:9098)
    at XMLHttpRequest.<anonymous> (jquery.js:9340)

**Comment by cigamit** [comment]
This is likely due to your database being set in strict_mode.  Edit your /etc/my.cnf and remove the SQL mode 'STRICT_TRANS_TABLES', restart MySQL and try again.

**Comment by cigamit** [comment]
Also, please run 'mysql --version' and let us know your MySQL version.

**Comment by cigamit** [comment]
We will completely disable the STRICT_TRANS_TABLE for now.

**Comment by vaultwiki** [comment]
/etc/my.cnf does not activate strict mode.
sql_mode=NO_ENGINE_SUBSTITUTION,TRADITIONAL

MySQL is MariaDB  10.1.21

**Comment by cigamit** [comment]
Well, that was unexpected.  Did you install yourself, or did it come this way from the OS vendor/packager?  The 'TRADITIONAL' will introduce the same issues.  If you remove TRADITIONAL, and restart MariaDB, this problem will go away.  I will add this case to the checks that we are currently doing for compatibility checks.
