### ISSUE TITLE
realtime graphs consuming too much memory

### ISSUE THREAD

**Issue by majed17** [Cacti/cacti#2270]
Doesn't matter what browser i use, after a few hours of graphing, all 16GB of ram get consumed and i have to end the browser task in task manager. this is on win 10 1809. I tried the 1.2 beta but with the size feature, the ram seems to be used even faster! on the 1.2.0, the problem remains with 9 graphs open, with settings: 1 hour 20 sec refresh. what is the root of the problem?

**Comment by cigamit** [comment]
Are you using realtime in a popup window or inline on the graphs page?  What browser and version of browser are you using for this?  We've had this reported, but both Chrome and Firefox, though they did consume memory over time, they released that memory dynamically.  This test was done for inline graphs and not popup.  Please confirm.

**Comment by cigamit** [comment]
This should be resolved now.  In the end, I did a leak hunt, but the big culprit was some stuff going on, or that should have been going on in jQueryUI.  There is an open bug.  There was a published workaround.  So, I used it.

**Comment by cigamit** [comment]
Please test the few files that were a part of this set.

**Comment by cigamit** [comment]
Working like a champ now.

**Comment by majed17** [comment]
so i tested it for a few days before i open my mouth, and indeed it is pure magic! :)
