### ISSUE TITLE
Cacti 1.2.0 - HTML formatting issue in Sunrise Theme

### ISSUE THREAD

**Issue by jplgps** [Cacti/cacti#2271]
Under Management/Devices:

Double stacked tick boxes on right side of table causing extra space between lines
First box at right top of table is partially out of bounds.

Checked in Safari (v12.0.2), Chrome (v71.0.3578.98), and Firefox (v64.0)- all exhibit the same behavior.

Are there supposed to be two tick boxes per line?

Cacti version: 1.2.0
CentOS 7.6 kernel 3.10.0-957.1.3.el7.x86_64
Apache v2.4.6

Theme is Sunrise

![cactiformatproblem](https://user-images.githubusercontent.com/46383490/50705394-ee4fa500-1017-11e9-9823-1279b1129ecb.jpg)

**Comment by netniV** [comment]
Have you ensured that you have cleared your cache and obtained the latest CSS ?  I will have to take a peek later to see if I see the same issue but we had no previous reports of it with sunrise.

**Comment by jplgps** [comment]
Hi - thanks for the response.

I was sure to clear the cache and forced a CSS update in Chrome and Safari. Firefox was a fresh install.

**Comment by netniV** [comment]
I can now confirm that this is a bug with the sunrise theme.

**Comment by netniV** [comment]
The fix for this has been applied to the 1.2.x and development branches.
