### ISSUE TITLE
1.2.0 Site graphs in tree mode

### ISSUE THREAD

**Issue by DoubleBeast** [Cacti/cacti#2272]
Trying to use the new feature of site graphs in tree mode i found 2 problems:

1-If you only put Sites in the tree the sites don´t appear in the tree mode, they only are shown if you add additional devices or graphs to that tree/branch.
2-Even hen the sites are shown the internal graph section of the sites says "graph not found"

At least this is hapenning in my case, anyone can confirm or deny this?

**Comment by cigamit** [comment]
This is what happens when you introduce new features, you forget to full test.  We are tracking a few additional minor issues that will justify cutting another minor release.  Keep hunting and reporting thanks!

**Comment by reubenfarrelly** [comment]
I'm fairly sure I am seeing the same problem too.
2c0de32cb380fd6e3ae3ff33dec301cc8e63f194   (19 Dec)  was the last commit for me that worked with Tree Mode.  Something broke in the commit following that one.

**Comment by cigamit** [comment]
Yea, we were trying to resolve some re-index issues, added a new column, and then things here appeared to break without us knowing it.  Just about to commit the fix.

**Comment by cigamit** [comment]
Just update the two files, and things should be better.

**Comment by cigamit** [comment]
Resolved.

**Comment by cigamit** [comment]
You will need to also update lib/api_tree.php

**Comment by DoubleBeast** [comment]
> 
> 
> Trying to use the new feature of site graphs in tree mode i found 2 problems:
> 
> 1-If you only put Sites in the tree the sites don´t appear in the tree mode, they only are shown if you add additional devices or graphs to that tree/branch.
> 2-Even hen the sites are shown the internal graph section of the sites says "graph not found"
> 
> At least this is hapenning in my case, anyone can confirm or deny this?

Hello guys, sorry for the late reply but just now i´m having the time to test with cacti 1.2.1:

The second point is solved but the first one remains, i really don´t know if it sholud work as described or is a bug but i think that the tree should show even when there are only sites associated to the tree.

the other thing is that i´m not sure if i should open a new issue for this or continue here since it´s the same issue but about a month old.
