### ISSUE TITLE
cacti 1.2.0 thold

### ISSUE THREAD

**Issue by Initarts** [Cacti/cacti#2277]
![image](https://user-images.githubusercontent.com/8800508/50733221-a15d0180-11c4-11e9-83fd-066f50fdee33.png)
![image](https://user-images.githubusercontent.com/8800508/50733198-3f040100-11c4-11e9-8ac2-6fad8f7c1c45.png)

**Comment by hmorandell** [comment]
well... not everyone is able or understands chinese... may you explain your matter?

**Comment by TheWitness** [comment]
Okay, two things, and not being rude to anyone.

1) Post thold issues on the thold issue tracker
2) Until 1.2 of thold is tagged, it is considered alpha/beta.  There is still one large feature that is in process to be backported in a way that is more elegant than it currently behaves.

So, just run and install the latest tag for now.  I think that's 1.0.6.
