### ISSUE TITLE
[1.2.0 Beta 4] Data Query values for HRULE graph objects not functioning

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#2283]
Sorry I'm not on 1.2.0 yet. Maybe this is fixed there. But probably not, I think I'm really close to that release. 

See this graph command:
```
/usr/local/rrdtool/bin/rrdtool graph - \
--imgformat=PNG \
--start='-86400' \
--end='-60' \
--pango-markup  \
--title='smcdu-r4 - TowerB[UPSB] - Load' \
--vertical-label='amps' \
--slope-mode \
--base=1000 \
--height=130 \
--width=600 \
--tabwidth '30' \
--alt-autoscale \
--color BACK#F3F3F3 \
--color CANVAS#FDFDFD \
--color SHADEA#CBCBCB \
--color SHADEB#999999 \
--color FONT#000000 \
--color AXIS#2C4D43 \
--color ARROW#2C4D43 \
--color FRAME#2C4D43 \
--border 1 --font TITLE:10: \
--font AXIS:8: \
--font LEGEND:8: \
--font UNIT:8: \
--font WATERMARK:8: \
--slope-mode \
DEF:a='/cacti/cacti-1.2.0-beta4-prod/rra/smcdu-r4_infeedload3_14542.rrd':'infeedLoad1':AVERAGE \
DEF:b='/cacti/cacti-1.2.0-beta4-prod/rra/smcdu-r4_infeedload3_14542.rrd':'infeedLoad2':AVERAGE \
DEF:c='/cacti/cacti-1.2.0-beta4-prod/rra/smcdu-r4_infeedload3_14542.rrd':'infeedLoad3':AVERAGE \
CDEF:cdefa='a,100,/' \
CDEF:cdeff='b,100,/' \
CDEF:cdefba='c,100,/' \
LINE1:cdefa#7020F0FF:'TwrB_XY[UPSB](BA)'  \
GPRINT:cdefa:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefa:MIN:'Min\:%8.2lf %s'  \
GPRINT:cdefa:AVERAGE:'Avg\:%8.2lf %s'  \
GPRINT:cdefa:MAX:'Max\:%8.2lf %s\n'  \
LINE1:cdeff#DE0056FF:'TwrB_YZ[UPSB](BB)'  \
GPRINT:cdeff:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdeff:MIN:'Min\:%8.2lf %s'  \
GPRINT:cdeff:AVERAGE:'Avg\:%8.2lf %s'  \
GPRINT:cdeff:MAX:'Max\:%8.2lf %s\n'  \
LINE1:cdefba#0C4E5DFF:'TwrB_XZ[UPSB](BC)'  \
GPRINT:cdefba:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefba:MIN:'Min\:%8.2lf %s'  \
GPRINT:cdefba:AVERAGE:'Avg\:%8.2lf %s'  \
GPRINT:cdefba:MAX:'Max\:%8.2lf %s\n'  \
COMMENT:' \n'  \
HRULE:|query_infeedLoadHighThresh|#FF5F00FF:'Infeed Load High Threshold\: |query_infeedLoadHighThresh|' \
HRULE:|query_infeedCapacity|#FF0000FF:'Infeed Load Capacity\: |query_infeedCapacity|                '
```
The "HRULE:|query_infeedCapacity|#FF0000FF:'Infeed Load Capacity\: |query_infeedCapacity|" is the problem. Both instances of |query_infeedCapacity| in this line need to be translated to a real integer value before being passed to rrdtool. Right now it's completely choking the command with no error output at all. 
I think this is a feature request I asked for a long time ago, so it's likely that I could be the only one using it, and affected by it. It's a really nifty feature though.

**Comment by eschoeller** [comment]
I think the feature was added pre-github ... can't see to find a record of it.

**Comment by cigamit** [comment]
Reviewed the code, the feature is there.  Could it be that these columns are missing from your host_snmp_cache for the device?

**Comment by cigamit** [comment]
Test this again with 1.2.2 once it's released.  You can open a new bug if it's not resolved.

**Comment by eschoeller** [comment]
I'm on 1.2.1 now. Check this out, I noticed it the other day:
![today](https://user-images.githubusercontent.com/12864741/53304802-cd951600-3836-11e9-8693-0c3f74793ee5.png)

It's kinda mind boggling why one graph shows the HRULE and the other completely ignores it ... Now, I'm seeing a slight difference in the graph commands:

The one without the HRULE:
```
/usr/local/rrdtool/bin/rrdtool graph - \
--imgformat=PNG \
--start='1550953200' \
--end='1551039551' \
--pango-markup  \
--title=' - Master_Cord_A - Power Factor' \
--vertical-label='pf' \
--slope-mode \
--base=1000 \
--height=130 \
--width=550 \
--tabwidth '30' \
--alt-autoscale \
--upper-limit='1.05' \
--lower-limit='.65' \
COMMENT:"From 2019/02/23 13\:20\:00 To 2019/02/24 13\:19\:11\c" \
COMMENT:"  \n" \
--color BACK#F3F3F3 \
--color CANVAS#FDFDFD \
--color SHADEA#CBCBCB \
--color SHADEB#999999 \
--color FONT#000000 \
--color AXIS#2C4D43 \
--color ARROW#2C4D43 \
--color FRAME#2C4D43 \
--border 1 --font TITLE:10: \
--font AXIS:8: \
--font LEGEND:8: \
--font UNIT:8: \
--font WATERMARK:8: \
--slope-mode \
DEF:a='_cordpowerfactor_62981.rrd':'CordPowerFactor':AVERAGE \
CDEF:cdefa='a,100,/' \
LINE1:cdefa#311F4EFF:'Master_Cord_A(AA)'  \
GPRINT:cdefa:LAST:'Current\:%8.2lf'  \
GPRINT:cdefa:MIN:'Min\:%8.2lf'  \
GPRINT:cdefa:AVERAGE:'Avg\:%8.2lf'  \
GPRINT:cdefa:MAX:'Max\:%8.2lf\n'  \
AREA:cdefa#311F4E7F:  \
HRULE:0.4#FF5F00FF:'Low Warning\: 0.4' \
HRULE:0.3#FF0000FF:'Low Alarm\: 0.3'
```
The one WITH the HRULE:
```
/usr/local/rrdtool/bin/rrdtool graph - \
--imgformat=PNG \
--start='1550953320' \
--end='1551039682' \
--pango-markup  \
--title=' - Link1_Cord_A - Power Factor' \
--vertical-label='pf' \
--slope-mode \
--base=1000 \
--height=130 \
--width=550 \
--tabwidth '30' \
--alt-autoscale \
--upper-limit='1.05' \
--lower-limit='.65' \
COMMENT:"From 2019/02/23 13\:22\:00 To 2019/02/24 13\:21\:22\c" \
COMMENT:"  \n" \
--color BACK#F3F3F3 \
--color CANVAS#FDFDFD \
--color SHADEA#CBCBCB \
--color SHADEB#999999 \
--color FONT#000000 \
--color AXIS#2C4D43 \
--color ARROW#2C4D43 \
--color FRAME#2C4D43 \
--border 1 --font TITLE:10: \
--font AXIS:8: \
--font LEGEND:8: \
--font UNIT:8: \
--font WATERMARK:8: \
--slope-mode \
DEF:a='_cordpowerfactor_62982.rrd':'CordPowerFactor':AVERAGE \
CDEF:cdefa='a,100,/' \
LINE1:cdefa#311F4EFF:'Link1_Cord_A(BA)'  \
GPRINT:cdefa:LAST:'Current\:%8.2lf'  \
GPRINT:cdefa:MIN:'Min\:%8.2lf'  \
GPRINT:cdefa:AVERAGE:'Avg\:%8.2lf'  \
GPRINT:cdefa:MAX:'Max\:%8.2lf\n'  \
AREA:cdefa#311F4E7F:  \
HRULE:0.8#FF5F00FF:'Low Warning\: 0.8' \
HRULE:0.3#FF0000FF:'Low Alarm\: 0.3'
```

Same graph template. Obviously I have a slight configuration difference between the thresholds on these two devices (which I'm going to fix). So, I'm wondering if this is an rrdtool bug/feature?? If the value of the HRULE is outside the graph range, it doesn't even bother printing it in the legend?? I've never seen that behavior before! I'm on rrdtool 1.7.0

**Comment by eschoeller** [comment]
And viola, if I change the threshold on the "Link1_Cord_A" device from "Low Warning .8" to "Low Warning .4" (as it should be) the HRULE completely disappears from the graph.

**Comment by eschoeller** [comment]
However ... I've gone back to the original device that was having the problem and I still can't fix it.

It's still showing this:
```
COMMENT:' \n'  \
HRULE:|query_infeedLoadHighThresh|#FF5F00FF:'Infeed Load High Threshold\: |query_infeedLoadHighThresh|' \
HRULE:|query_infeedCapacity|#FF0000FF:'Infeed Load Capacity\: |query_infeedCapacity|                '
RRDtool Says:
```
Despite having this in the host_snmp_cache:
```
mysql> select * from host_snmp_cache where host_id=364 and field_name like '%infeedCapacity%' or host_id=364 and field_name like '%infeedLoadHighThresh%';
+---------+---------------+----------------------+-------------+------------+-----+---------+---------------------+
| host_id | snmp_query_id | field_name           | field_value | snmp_index | oid | present | last_updated        |
+---------+---------------+----------------------+-------------+------------+-----+---------+---------------------+
|     364 |            45 | infeedCapacity       | 30          | 1          |     |       1 | 2019-02-24 13:39:30 |
|     364 |            45 | infeedCapacity       | 30          | 2          |     |       1 | 2019-02-24 13:39:30 |
|     364 |            45 | infeedLoadHighThresh | 24          | 1          |     |       1 | 2019-02-24 13:39:30 |
|     364 |            45 | infeedLoadHighThresh | 24          | 2          |     |       1 | 2019-02-24 13:39:30 |
+---------+---------------+----------------------+-------------+------------+-----+---------+---------------------+
```
So, something is still not working right in this case.

**Comment by cigamit** [comment]
I can possibly see a 'Cacti' feature enhancement to watch the HRULE values and compare them to both max and min and change the upper and lower rigid values, if they exist.  If they don't exist, then there is not much we can do to make it easy.

I would say that this should be considered a bug in RRDTool.  In your case, you have a rigid boundary, at the lower end, of 0.65 in your Graph Template, but you have threshold values of 0.4 and 0.3, which are literally off the canvas.

An easy fix would be to place the rigid lower boundary at 0.2, then everything will work as expected.  However, RRDTool should, in my opinion be where that change of behavior should happen.

Hope that helps.  You are going to hit yourself when you finish reading this.

**Comment by cigamit** [comment]
The other issue is that this is a thold issue and not a Cacti core issue.  Log the bug over there.

**Comment by cigamit** [comment]
Forget that last comment....

**Comment by cigamit** [comment]
Once you are at 1.2.2, update the lib/rrd.php in develop, and let me know if the replacement issues in the HRULE are corrected.

**Comment by eschoeller** [comment]
OK, I'm on 1.2.3 now. Sorry for the delay, I went dark for awhile. 
Yes, I am seeing the expected behavior on these now. All the graphs have the HRULE data in the legend, as I would expect, albeit some of them don't actually have the HRULE painted since I have upper and lower limits defined. Graphing power factors is a tricky business, but I've hacked at this for awhile to get somewhere close where I wanted to be. Granted with the way this graph is defined if the data falls outside the upper or lower limit those limits are ignored, and then the HRULEs start to appear.

**Comment by eschoeller** [comment]
Some examples:
![image](https://user-images.githubusercontent.com/12864741/56926810-cd600380-6a8f-11e9-8638-05dfd62a1d3e.png)
![image](https://user-images.githubusercontent.com/12864741/56926838-dc46b600-6a8f-11e9-8e0d-34306f2d8a10.png)

**Comment by netniV** [comment]
Based off the scale of that graph, it isn't showing things below 0.6 hence the HRULE is missing at 0.4.  If you set your minimum to be either zero or 0.1, that would make it appear.
