### ISSUE TITLE
Enhancement: Indexed SNMP data graph/data collection creation

### ISSUE THREAD

**Issue by rfc4711** [Cacti/cacti#2287]
When it comes to adding new indexed SNMP data to cacti, the tool is quite complex, why cant we have a module to parse the MIB structure and create "input" / "output" data fields to store as new queries as well as enhance the graph template creation on indexed SMMP queries b automatically adding the graph components with option flags to have Line and GPRINT (Last/Average/Max) during the graph template creation.

**Comment by cigamit** [comment]
That would likely be something like the MacTrack plugin.  When running MacTrack, your Data Templates 'could' gather data from there.  However, it would not have the granularity that people want.  The Templating concept is somewhat advanced, but most people for the better part of two decades have been able to deal with that complexity.  Some have repeatedly complained about it, but odly there are still hundreds of graph templates out in the wild.  Some things are just complex.  You should try Microsoft Excel for example.  Quite complex indeed.  We can make things better, and that is a separate dashboarding discussion that we should not have in an issue.
