### ISSUE TITLE
Can't set different sub-tree item from root in tree rules automation

### ISSUE THREAD

**Issue by Carlimeunier** [Cacti/cacti#229]
When creating a tree rule, it is not possible to set/change sub-tree Item. It alway sets to [root] after applying

![image](https://cloud.githubusercontent.com/assets/5239792/22211141/6cff0dee-e18c-11e6-8c67-a92f0e822295.png)

Thanks

**Comment by cigamit** [comment]
Resolved, thanks for testing!
