### ISSUE TITLE
[1.2.0] Language dropdown size

### ISSUE THREAD

**Issue by BSOD2600** [Cacti/cacti#2290]
Minor issue with the size of the dropdown for the language selection.  
IE11, default 100% zoom.

![image](https://user-images.githubusercontent.com/5741811/50841929-a43f2a00-135d-11e9-98e7-e27a60d52c2b.png)

**Comment by cigamit** [comment]
Can you use the snipping tool to show what it looks like when opened?

**Comment by cigamit** [comment]
This is resolved now.  Came from cloning as opposed to downloading the release package.
