### ISSUE TITLE
Realtime 1s

### ISSUE THREAD

**Issue by lbsou** [Cacti/cacti#2292]
Hi !

I would like to know if it would be possible to get module realtime to poll data at 1 sec interval.

Our 3750 and 3600 update IfOutOctets and IfInOctets every seconds.

As the next question will be why would you want to do that, I will answer straight away

We dont have console access to the switch, only snmp view and we manage approx. 2000 of them.

When we need to clarify to a customer that either he need to activate QoS or that there is no saturation, I want to be as precise as I can. I don't need that polling on every day basis, only when we do diagnostic.

Thank you!
Louis

**Comment by cigamit** [comment]
You can also implement this yourself.  Just edit include/global_arrays.php line 1400, follow your nose to add 1 second.  Let us know if it's responsive enough and we can implement.  Though 2 seconds might be better.  Either way, let us know.

**Comment by cigamit** [comment]
You also have to edit poller_realtime.php and change the step on line 212 to initialize at something like 1, right now it defaults to what you have asked for.  Likely a bit of a bad design (right now, the rrdfiles will be created at 10 second step, so if you change to 5, you don't get an update every polling.).

**Comment by cigamit** [comment]
Works find for me.  Took only a few minutes to do.
