### ISSUE TITLE
[1.2.0 Beta 4] Legacy Aggregate Graphs have disappeared

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#2293]
I can see several legacy aggregate graphs in the Management->Graphs page. They still render correctly here. But they are gone from the Tree view from where they once were present. I also cannot find them in the Graph List View either. I realize old Aggregate graphs are a thorn in everyone's side, but I still have lots of them that I need and cannot easily re-create. Not really sure how to provide more information about this easily ... 
![image](https://user-images.githubusercontent.com/12864741/50870349-e4f66d80-1374-11e9-971d-2c4deaf3cf49.png)

**Comment by netniV** [comment]
Hi Eric,

This will definitely be one of those situations where we need access to the data to properly diagnose the situation.  We would need to delve through multiple tables and code to see why they disappeared but it may be related to a fix that will be in 1.2.1.

Are you running the 1.2.0 release or the latest GitHub develop?

**Comment by eschoeller** [comment]
Sure, no problem. Should we coordinate a remote session over e-mail? I can be available all day this coming Friday (1/11).
I'm currently on a release somewhere between 1.2.0 Beta 4 and 1.2.0. I'll see if I can get up to 1.2.0 tomorrow ... or perhaps the latest develop branch if that's what you'd prefer.

**Comment by netniV** [comment]
Yes, it would be better to get up to date. If you are using GitHub, update to the latest version and run the upgrade_database.php with forcever again.

**Comment by cigamit** [comment]
@eschoeller and @netniV any updates?  The latest Aggregate has fixed a number of issues.

**Comment by eschoeller** [comment]
I have seen the aggregate graphs again in the version I upgraded to. Traveling this week, back at a computer next week 

Eric.

**Comment by cigamit** [comment]
So, are we good to close then @eschoeller?

**Comment by cigamit** [comment]
Closing due to lack of feedback.  Figure it's fixed anyway.

**Comment by eschoeller** [comment]
Yes, they are working again! Sorry I forgot to get back to you.
