### ISSUE TITLE
Reporting - Form issue

### ISSUE THREAD

**Issue by smiles1969** [Cacti/cacti#2296]
When creating a new report, when I populate the "To Email Addresses" field, several form fields get populated with a full or partial email address entered. 

These form fields include:

Report Name, Next Timestamp for Sending Mail Report, Interval Frequency, Subject, From Name, and From Email Address.

**Comment by netniV** [comment]
Are you sure that isn't your browser trying to be clever with it's autocomplete?

**Comment by smiles1969** [comment]
It's chrome, I didn't think autocomplete would affect several other form fields for an onchange event, but it appears browser specific. It does not happen on Mozilla or Exploder.

**Comment by netniV** [comment]
That is what I thought.  Chrome does that to me all the time because it will even go backwards and update some fields at times which can catch you out.
