### ISSUE TITLE
page nav bar wrongly show '...' when current page no is 1 or 4

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#2297]
Currently, nav bar wrongly show '...'  between same page no under case below:
1. total pages is 4, current pageno is 1
2. total pages is 5, current pageno is 4

ALso, nav bar wrongly show '...'  between two adjacent page no under case below:
1. total pages is large, current pageno is 4
2. total pages is large, current pageno is (total pages - 3)

Detail ref attached img:
![image](https://user-images.githubusercontent.com/17589018/50944620-19307200-14cc-11e9-875f-f9329df9a965.png)

**Comment by cigamit** [comment]
Please create a pull request.  Thanks for doing this.  It's been bugging me for a while, just a low priority to fix.

**Comment by netniV** [comment]
There is a pull request outstanding for it.

**Comment by netniV** [comment]
Oh my bad, when I looked on the iPad earlier there was an open pull request and this change was showing in it.

**Comment by ddb4github** [comment]
requested
