### ISSUE TITLE
Cacti 1-2-0 permission problem

### ISSUE THREAD

**Issue by chathurag** [Cacti/cacti#2299]
Time graph view of aggregate graphs show doe not work. Says no permissions.

**Comment by DavidLiedke** [comment]
Issue is already fixed. See #2259 

Fix will be included in the next release.

**Comment by netniV** [comment]
Thanks for that @DavidLiedke and I can confirm that has been fixed already in the development code.  There are a couple of issues we are investigating right now but 1.2.1 will hopefully be released over the next two weeks.
