### ISSUE TITLE
1 minute polling: graphs use wrong step size

### ISSUE THREAD

**Issue by rprofijt** [Cacti/cacti#230]
I have created graphs with one minute polling after #218 was fixed.

Data template used:
![cacti-1min-template](https://cloud.githubusercontent.com/assets/12047685/22222158/14cedb8e-e1b6-11e6-80f7-50a46be7320a.png)

The RRD that is created looks alright:

<pdp_per_row>1</pdp_per_row> 
<pdp_per_row>5</pdp_per_row> 
<pdp_per_row>30</pdp_per_row> 
<pdp_per_row>120</pdp_per_row> 
<pdp_per_row>1440</pdp_per_row> 

But some graphs are drawn with the wrong step size:

Hourly (1 Minute Average) = step 60 = ok
Daily (5 Minute Average) = step 900 = wrong
Weekly (30 Minute Average) = step 1800 = ok
Monthly (2 Hour Average) = step 1800 = wrong
Yeartly (1 Day Average) = step 86400 = ok

**Comment by cigamit** [comment]
In this release, we are letting RRDtool make the decision on the correct RRA to use.  Looks like it may not be doing so well on it's own.  If you click on the cog, you can view the graph syntax and zoom in/out as required.  We may need to force the RRA to use for rendering, which may have to wait until after release to fix.

**Comment by CapitalF** [comment]
It looks like this issue was caused by the fact that at some point, Timespans, which used to be configurable on RRAs, has been removed from Cacti. Is that right, or is this something else?

**Comment by cigamit** [comment]
I believe that this was fixed here. https://github.com/Cacti/cacti/pull/341
