### ISSUE TITLE
Problem with "Notify Primary Admin of Issues" function

### ISSUE THREAD

**Issue by DoubleBeast** [Cacti/cacti#2303]
I recently enable this new feature and get "MAILER ERROR: Invalid address: (to): Admin" when the mail should be send, aparently the funtion is trying to use the user "Full Name" field instead of the user "Email Address" field.

If i send a test mail it works fine, and thold notifications are fine too.

**Comment by cigamit** [comment]
Do can you be specific what notifications we are talking about?

**Comment by DoubleBeast** [comment]
I´m talking about this one: 

![notification](https://user-images.githubusercontent.com/37849594/51075465-2b441900-1662-11e9-924d-d4bb54f3baaa.png)

**Comment by cigamit** [comment]
Oh, that was embarrassing.  Okay fixed.

**Comment by DoubleBeast** [comment]
> 
> 
> Oh, that was embarrassing. Okay fixed.

nothing embarrassing man, just to much work and details. Great that it is fixed now.
