### ISSUE TITLE
Installation progress stays at 0%

### ISSUE THREAD

**Issue by WirthmU** [Cacti/cacti#2304]
I am updating from a fully working v1.1.38 on a Synology NAS to the latest V1.2.1. The update process works fine until I start the cacti website on the server to finalize the installation (cacti server installation wizard). The progress bar stays at 0% and installation goes forever without any result.

Browser command line says:
http://192.168.1.136/cacti/install/install.php?data={"Step":"97","Eula":"1"}

**Comment by cigamit** [comment]
You must have some issue on the php/apache backend.  I would check the Apache error_log.  Can you follow this issue on the forums though.  Thanks.

**Comment by netniV** [comment]
As part of #2315 I have updated the code to provide better detection of invalid scenario's. If possible, could you update to the latest develop code and see if that works for you?

**Comment by netniV** [comment]
@WirthmU have you had a chance to review these changes?

**Comment by WirthmU** [comment]
Yes - I did a complete re-install on my Synology.

Unfortunately it is even worse since it already give an error message right at the license agreement page where I can choose language and default theme:

When I confirm the setting it says:
Action failed
Error 200 OK
Reason: The response to the last action was unexpected

**Comment by netniV** [comment]
Can you see if there are any errors in your web/cacti log ?  That usually means that for some reason JSON isn't being returned and since the javascript code is issuing a JSON call, it bugs out.

**Comment by WirthmU** [comment]
The  cacti_stderr.log shows:

  - the PHP MySQL module is installed and enabled.
  - the database is running.
  - the credentials in config.php are valid.
FATAL: Connection to Cacti database failed. Please ensure:

**Comment by netniV** [comment]
Sorry, that seems to be either cut off or badly formatted.  Any change you can email me the cacti.log, and cacti_stderr.log ?  Also, if you have an error log for the web server (eg, apache or ngix) that would also be good.

If you'd like to keep those private, email them to developers@cacti.net and I will take a look to see if I can spot anything obvious.

**Comment by TheWitness** [comment]
@WirthmU, I'm pretty familiar with the Synology as I have a DS1515+.  I went through the process of setting up the Web Station and the various PHP and Apache versions available from the Download Center.

The real problem with getting Cacti up on the Synology right now is that it has a core dependence on PHP5.6 (which is basically EOL by the way).  You can install PHP7 and PHP72, but only PHP7 can be sued for the Web Station.

The problem with the PHP7 is that it currently does not contain all the modules required for Cacti to operate well.  The PHP72 version that they allow you to download has everything, but does not work with the Web Station.

Reading on the Synology forums, it would appear that there will be a release of DSM7 sometime this year (hopefully Q1) that should start to use PHP72 as the core PHP version.  Once that happens, Cacti should play real well on the device.  I'm looking forward to it actually.

There are other package managers available for Synology, but I personally won't go there.  I would suggest that you are pushing on a string right now.  Better wait it out for a bit.  Go get a Raspberry Pi in the mean time.

**Comment by WirthmU** [comment]
Thank you for taking care of my concerns - I will be patient then an wait for the next Synology release.

iPadPro
