### ISSUE TITLE
BOOST PROGERR: ERRNO:'8'

### ISSUE THREAD

**Issue by xdracco** [Cacti/cacti#2305]
When debug is enabled:

13/Jan/2019 08:15:03 - BOOST PROGERR: ERRNO:'8' TYPE:'Notice' MESSAGE:'Undefined variable: delim_length' IN FILE:'/usr/share/cacti/site/lib/boost.php' LINE NO:'190'
13/Jan/2019 08:15:03 - BOOST PROGERR: ERRNO:'8' TYPE:'Notice' MESSAGE:'Undefined variable: delim_length' IN FILE:'/usr/share/cacti/site/lib/boost.php' LINE NO:'190'
13/Jan/2019 08:15:03 - BOOST PROGERR: ERRNO:'8' TYPE:'Notice' MESSAGE:'Undefined variable: delim_length' IN FILE:'/usr/share/cacti/site/lib/boost.php' LINE NO:'190'
13/Jan/2019 08:15:03 - BOOST PROGERR: ERRNO:'8' TYPE:'Notice' MESSAGE:'Undefined variable: delim_length' IN FILE:'/usr/share/cacti/site/lib/boost.php' LINE NO:'190'
13/Jan/2019 08:15:03 - BOOST PROGERR: ERRNO:'8' TYPE:'Notice' MESSAGE:'Undefined variable: delim_length' IN FILE:'/usr/share/cacti/site/lib/boost.php' LINE NO:'190'
13/Jan/2019 08:15:03 - BOOST PROGERR: ERRNO:'8' TYPE:'Notice' MESSAGE:'Undefined variable: delim_length' IN FILE:'/usr/share/cacti/site/lib/boost.php' LINE NO:'190' 

I added to line 145 in boost.php to resolve the error message.

Installed Cacti Version: 1.2 (beta 4)

**Comment by cigamit** [comment]
Resolved.  Thanks for reporting.
