### ISSUE TITLE
Plugin thold eror

### ISSUE THREAD

**Issue by yosephafebrian** [Cacti/cacti#2306]
Hi i have problem with plugin thold,

2019/01/14 08:17:27 - CMDPHP SQL Backtrace: (/plugins/monitor/monitor.php: 120 draw_page)(/plugins/monitor/monitor.php: 138 render_default)(/plugins/monitor/mo   nitor.php: 686 db_fetch_assoc)(/lib/database.php: 359 db_fetch_assoc_prepared)(/lib/database.php: 400 cacti_debug_backtrace)
2019/01/14 08:17:31 - DBCALL ERROR: SQL Assoc Failed!, Error:1146, SQL:'SELECT DISTINCT dl.host_id    FROM thold_data AS td    INNER JOIN data_local AS dl    O   N td.local_data_id=dl.id    WHERE thold_alert > 0    AND thold_enabled = "on"'
2019/01/14 08:17:31 - DBCALL ERROR: SQL Assoc Failed!, Error: Table 'cactiMSIG.thold_data' doesn't exist
2019/01/14 08:17:31 - CMDPHP SQL Backtrace: (/plugins/monitor/monitor.php: 102 check_tholds)(/plugins/monitor/monitor.php: 375 db_fetch_assoc)(/lib/database.ph   p: 359 db_fetch_assoc_prepared)(/lib/database.php: 400 cacti_debug_backtrace)
2019/01/14 08:17:31 - DBCALL ERROR: SQL Assoc Failed!, Error:1146, SQL:'SELECT DISTINCT h.*  FROM host AS h  LEFT JOIN thold_data AS td ON td.host_id=h.id  WHE   RE h.disabled = ""   AND h.monitor = "on"   AND (h.availability_method>0 OR h.snmp_version>0    OR (td.thold_enabled="on" AND td.thold_alert>0)   )  ORDER BY d   escription'

please help

**Comment by netniV** [comment]
Issue for thold should be posted on the thold repo

https://github.com/cacti/thold/issues
