### ISSUE TITLE
DB Call Error

### ISSUE THREAD

**Issue by yosephafebrian** [Cacti/cacti#2307]
iam see this eror, when i click refresh on tab monitor

DBCALL ERROR: SQL Assoc Failed!, Error:1146, SQL:'SELECT DISTINCT dl.host_id    FROM thold_data AS td    INNER JOIN data_local AS dl    ON td.local_data_id=dl.id    WHERE thold_alert > 0    AND thold_enabled = "on"'
DBCALL ERROR: SQL Assoc Failed!, Error: Table 'cactiMSIG.thold_data' doesn't exist

please help

Thanks
Yosep

**Comment by netniV** [comment]
This is a problem for Thold or Monitor (depending on which plugin you are using).

Please post your issue on the appropriate repo

https://github.com/cacti/plugin_monitor
https://github.com/cacti/plugin_thold
