### ISSUE TITLE
Feature Request: Reporting/Trees allow non templated graphs.

### ISSUE THREAD

**Issue by smiles1969** [Cacti/cacti#2313]
I've opened a previous ticket on this issue (#2230), but did not have the option to re-open it.

I am requesting that support be re-added to allow non-templated graph items to be included on a report. The form no longer gives the option as it used to. In the previous ticket, I provided an example of a graph that pulls from multiple hosts and multiple interfaces. I can still view the graph if I drill into it, but have lost the ability to browse it in trees, and include it on reports.

Is it a major coding obstacle to bring this functionality back to reporting and tree view?

**Comment by cigamit** [comment]
This was resolved as part of the 1.2.1 release.  We had a late change that bit us in the bum that caused the error to re-emerge.

**Comment by smiles1969** [comment]
Confirmed resolved in 1.2.1 for both reports and trees. Thank you very much!

**Comment by netniV** [comment]
Please note that 1.2.1 isn't actually released yet, if you are running from develop there will be more changes by the weekend.
