### ISSUE TITLE
Issue with parsing index in SNMP query xml 

### ISSUE THREAD

**Issue by Carlimeunier** [Cacti/cacti#232]
I created a SNMP query that has the speficity to parse the OID index result with a regex like this 
`<oid_index>.1.3.6.1.4.1.6527.3.1.2.3.1.1.4</oid_index>`
`<oid_index_parse>OID/REGEXP:^.{31}(.*)$</oid_index_parse>`

When i run the query, i have this output : 
`Total: 0.04, Delta: 0, index_parse at OID: '.1.3.6.1.4.1.6527.3.1.2.3.1.1.4.1' results: '.1'`
`Total: 0.04, Delta: 0, index_parse at OID: '.1.3.6.1.4.1.6527.3.1.2.3.1.1.4.2' results: '.2'`

So i have an index started with dot (.) in the "create graph" view

For information, this request works correctly on version 0.8.8h

Is there any changes on the way to define a SNMP query when retrieved index with regex?

Thanks

**Comment by cigamit** [comment]
Pleas provide the verbose output from 0.8.8h and the verbose output from 1.0.0.  I suspect that it's possibly having something to do with the leading period in the OID since we are only off by one.

There have been many changes with this release to the various OID manipulation logic, but we have to determine if the problem is there, or potentially somewhere else.

**Comment by Carlimeunier** [comment]
Here is the verbose output 
- from 0.8.8h
![verbose_snmp_query_088h](https://cloud.githubusercontent.com/assets/5239792/22284705/c4bcf7fa-e2e8-11e6-83a0-b5a1417e4d58.PNG)

- From 1.0.0 ( not the same device but the same type)
![verbose_snmp_query_1 0 0](https://cloud.githubusercontent.com/assets/5239792/22284752/f2c33f42-e2e8-11e6-8841-57c23835b13a.PNG)

As we can see, there is one period in the return parsed index

**Comment by cigamit** [comment]
Change your {31} to a {32}.  The data query was written assuming that the object notation for the snmp OID would not be numeric.  Since we ALWAYS use numeric now, the number of digits is off by two.
