### ISSUE TITLE
Installer should identify that program versions are not returning a valid value

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#2320]
When performing checks against executables, extra code should be run to retrieve the version numbers to ensure that programs can actually run.  For example, my basic installation of rrdtool on CentOS 7.5 gave the following error:

```
rrdtool -V
rrdtool: symbol lookup error: /lib64/libpango-1.0.so.0: undefined symbol: g_log_structured_standard
```

Where possible, program specific version should be obtained to ensure that a program can actually run.

**Comment by justmace** [comment]
that error appears because the version of glib2 installed does not contain that symbol. upgrading to glib2-2.56.1-2.el7.x86_64 fixed it on my side. this version contains the extra symbol

**Comment by netniV** [comment]
Yes, it does.  That is the fix for the specific rrdtool issue, though in general, I think Cacti should be verifying the versions of tools to ensure that it is getting a valid response from the programs (the above was an example).
