### ISSUE TITLE
Date separator is ignored on graphs

### ISSUE THREAD

**Issue by tinola** [Cacti/cacti#2321]
OS: FreeBSD 11.2-STABLE, Cacti is installed from the ports tree (cacti-1.2.0_2)
How to reproduce? In user settings change the default date separator  "/" to "-", save change and refresh your graphs.
Date format remains Y/m/d but should be Y-m-d

**Comment by netniV** [comment]
Can you provide a screenshot highlighting this issue?

**Comment by netniV** [comment]
Also, what are the system settings for date/time?

**Comment by tinola** [comment]
if I understood correctly, I paste the screenshot below

![graph](https://user-images.githubusercontent.com/3160125/51383921-0eed2400-1b1b-11e9-8d61-0fb5afd68bda.png)

And after "click" ;)
```
RRDtool Command:

/usr/local/bin/rrdtool graph - \
--imgformat=PNG \
--start='1547722680' \
--end='1547808788' \
--pango-markup  \
--title='(cutted) - Traffic - igb1' \
--vertical-label='bits per second' \
--slope-mode \
--base=1000 \
--height=200 \
--width=700 \
--rigid \
--alt-autoscale-max \
--lower-limit='0' \
COMMENT:"From 2019/01/17 11\:58\:00 To 2019/01/18 11\:53\:08\c" \
COMMENT:"  \n" \
--color BACK#F3F3F3 \
--color CANVAS#FDFDFD \
--color SHADEA#CBCBCB \
--color SHADEB#999999 \
--color FONT#000000 \
--color AXIS#2C4D43 \
--color ARROW#2C4D43 \
--color FRAME#2C4D43 \
--border 1 --font TITLE:11:'Arial' \
--font AXIS:8:'Arial' \
--font LEGEND:8:'Courier' \
--font UNIT:8:'Arial' \
--font WATERMARK:6:'Arial' \
--slope-mode \
DEF:a='/var/db/cacti/rra/(cutted)_traffic_in_50.rrd':'traffic_in':MAX \
DEF:b='/var/db/cacti/rra/(cutted)_traffic_in_50.rrd':'traffic_in':AVERAGE \
DEF:c='/var/db/cacti/rra/(cutted)_traffic_in_50.rrd':'traffic_out':MAX \
DEF:d='/var/db/cacti/rra/(cutted)_traffic_in_50.rrd':'traffic_out':AVERAGE \
CDEF:cdefa='a,8,*' \
CDEF:cdefb='b,8,*' \
CDEF:cdefg='c,8,*' \
CDEF:cdefh='d,8,*' \
LINE1:cdefa#00CF00FF:  \
AREA:cdefb#00CF007F:'Inbound '  \
GPRINT:cdefb:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefb:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdefb:MAX:'Maximum\:%8.2lf %s'  \
COMMENT:'Total In\:  4.26 GB\n'  \
LINE1:cdefg#002A97FF:  \
AREA:cdefh#002A977F:'Outbound'  \
GPRINT:cdefh:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefh:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdefh:MAX:'Maximum\:%8.2lf %s'  \
COMMENT:'Total Out\: 654.97 MB\n' 

RRDtool Says:
OK
```

**Comment by netniV** [comment]
```
COMMENT:"From 2019/01/17 11\:58\:00 To 2019/01/18 11\:53\:08\c" \
```
So this bit here is the part that is wrong.  We will investigate and come back to you.  You didn't say what the system settings were though for date/time ?  You've only posted the user specific settings?

**Comment by tinola** [comment]
Oh, do you mean OS date/time settings? I didn't touch it, just default.

# env | grep LANG
LANG=pl_PL.UTF-8
# date
pt. 18 sty 2019 14:07:43 CET
# LANG=en_EN.UTF-8 date
Fri Jan 18 14:08:21 CET 2019

In php.ini timezone variable is set as 'Europe/Warsaw'.

**Comment by netniV** [comment]
No, I mean under Console -> Configuration -> Settings -> General -> Other Defaults 👍

**Comment by tinola** [comment]
Here you are :)

![general](https://user-images.githubusercontent.com/3160125/51390104-9a23e500-1b2e-11e9-984b-2eb85efc83af.png)

**Comment by tinola** [comment]
Thx! problem has gone 👍
