### ISSUE TITLE
Poller Replicate Memory Issue

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#2327]
```
ERROR PHP ERROR: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 256 bytes) in file: /cacti/cacti-prod/lib/database.php on line: 473
CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
```
This continues over and over again, for poller #2.

**Comment by eschoeller** [comment]
I doubled my PHP memory_limit from 1024MB to 2048MB. It was able to get through whatever it needed to do.

**Comment by cigamit** [comment]
See my note on the database upgrade issues for this one.

**Comment by cigamit** [comment]
Put that `ini_set` in the poller_replicate.php file at the very top.

**Comment by cigamit** [comment]
You may have to put it in poller.php if you are manually doing full sync.

**Comment by eschoeller** [comment]
Won't this change get blown away each time I upgrade, or is this a change you're making in the code base as well?

**Comment by cigamit** [comment]
Updating pollers.php and cli/polller_replicate.php should resolve this issue now.
