### ISSUE TITLE
I want to change translate

### ISSUE THREAD

**Issue by whsir** [Cacti/cacti#2330]
I want to change translate

msgid "Chinese (zh_CN)"
msgstr "中文（简体）"

msgid "Chinese (zh_TW)"
msgstr "中文（繁体）"

What do you think

**Comment by ddb4github** [comment]
I'm sure comments below code effort now.
Prefer to some MobilePhone, show language option by language self in Profile(edit). Like:
- English
- Deutsch
- Le français
- 中文（简体）
- 中文（繁體）

**Comment by ddb4github** [comment]
Oh! My comments is not about politicization. Just for usability. whatever any word in '()'.
Just prefer show language text by self language, like 'Deutsch', and  'Le français'

**Comment by netniV** [comment]
I would agree with @ddb4github.  It should be in the local language though some debate will likely start up when there's sub-localisation of a language.  For English, at least the American's were clever enough to leave English alone and not bastardise it to 'Englizh' 😆 🤣

**Comment by cigamit** [comment]
When we added Taiwan, we meant to be adding Traditional vs. Simplified.  Was not looking for a political debate.  Now we find that there are several major dialects in China (lot's of people there).  It's almost like Mark Twain English vs. William Wordsworth English.
