### ISSUE TITLE
Cacti RRDs using RAMdisk

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#2332]
Is it somehow possible to make cacti using ramdrive instead of SSD?
I would like to automaticly make a copy of RRDs to HDD few times a day and when reboot only.

I have big uptime so and so on there is no need to make single write to HDD per pull and overwrite this by the next pull. The data is not so critical that any animal would be hurt :) But there is a big ioload to drives - whitch in my opinion is not needed at all.

**Comment by netniV** [comment]
Have you tried configuring and enabling Boost?  That reduces the update frequency if configured properly I believe.

**Comment by cigamit** [comment]
Cacti has always been able to use a ramdisk.  However, it's a good idea to rsync your data frequently, which is not a big deal either if you are okay loosing some data from time to time (though very infrequently).

**Comment by cigamit** [comment]
Ope, you wanted to keep this open ;)

**Comment by cigamit** [comment]
Closing.
