### ISSUE TITLE
The ability to export/import preset data profiles

### ISSUE THREAD

**Issue by camerabob** [Cacti/cacti#2333]
I would like to have the ability export and import preset data profiles between installs of Cacti.

Thank you

**Comment by cigamit** [comment]
If you simply export a device template or any other object, these profiles can be imported from the foreign system.  Can you please confirm that?

**Comment by netniV** [comment]
I think there should be a way of doing that without needing a device template, and all the extras that could bring with it.

**Comment by camerabob** [comment]
Creating from scratch is a very non intuitive process. I’m not sure it even works as designed. If you could even point me in the direction of where those are stored, I can attempt to copy them myself.

Excuse any misspellings. I'm still getting used to this iGadget!

**Comment by camerabob** [comment]
Read these in the wrong order. I will try this. 

Excuse any misspellings. I'm still getting used to this iGadget!

**Comment by camerabob** [comment]
Is the site down? I am unable to reach it. 

Excuse any misspellings. I'm still getting used to this iGadget!
