### ISSUE TITLE
After updating the previous path of the log file is changed.

### ISSUE THREAD

**Issue by pautiina** [Cacti/cacti#2337]
Before the update, I had the path `/var/log/cacti.log`, after the update it was `/var/www/cacti/log/cacti.log`

**Comment by netniV** [comment]
Cacti itself wouldn’t update this unless ti was changed during the installation. Are you using a package manager?

**Comment by pautiina** [comment]
I update code from github. 
I do not use the package manager. and that changed just after installation.

**Comment by netniV** [comment]
FreeBSD right?

**Comment by pautiina** [comment]
@netniV  of course you're right :)

**Comment by cigamit** [comment]
So, is this an issue or was it some form of human error?

**Comment by pautiina** [comment]
@cigamit It's bug.
I returned the value to my `/var/log/cacti.log`, but today, after updating the Cacti, it has changed to `/var/www/cacti/log/cacti.log`

**Comment by cigamit** [comment]
Okay, all fixed up now.  Too many assumptions in the installer.

**Comment by pautiina** [comment]
I think that I can definitely check only when upgrading to the next version, when it will be.
For now I closing this issue , if it repeat on version 1.2.3, I’ll re-open.
