### ISSUE TITLE
MAILER WARNING: Mail failed from ... Message: You must provide at least one recipient email address.

### ISSUE THREAD

**Issue by xdracco** [Cacti/cacti#2339]
Cacti is failing to send email (for reports, issues, etc) when there is a plus sign in the recipient email address, in my case, **ubuntusv+orion@mydomain.com**. If that's the only recipient defined, mail will not be sent out. If there are more than one recipients defined, mail is sent out but only to recipients without the plus sign in the email address.

Email addresses in **settings_test_email** in the settings table and **email** in the reports table are both saved with plus sign.

I can replicate this issue every time.

**Comment by cigamit** [comment]
Never mind.  Loving regex borrowed.

**Comment by cigamit** [comment]
Resolved.

**Comment by gdsotirov** [comment]
I have the same problem with a mail address containing dash (-).

**Comment by cigamit** [comment]
Better now?

**Comment by gdsotirov** [comment]
Yes. Already tested it on my installation.

**Comment by cigamit** [comment]
hehe, yup.  All good on this side too.  Thanks for the help.

**Comment by DoubleBeast** [comment]
I have a similar issue with the "Notify Primary Admin of Issues" funtion, the log show this:

09-02-2019  09:25:41 - MAILER WARNING: Mail failed from '"Cacti"  <probando@gmail.com>', to '', cc '', Subject 'Cacti System  Warning', Message: You must provide at least one recipient email  address.

The selected user in authentication page has a valid email address and the test/thold emails works fine.

I'm using stable 1.2.1, is this issue solved in development branch?

**Comment by cigamit** [comment]
It is, though that format does not seem quite right.  Update lib/functions.php and test away though.  If this is a new install, you might just want to clone as there are several other changes that may introduce bugs if you do not pull the remainder of the files.  Not too many file though.

**Comment by netniV** [comment]
No feedback, closed.

**Comment by justmace** [comment]
```
2019/03/14 16:58:00 - MAILER WARNING: Mail failed via PHP Mail() Function from 'Cacti <something@gmail.com>', to '', cc '', Subject 'Cacti Test Message', Error: You must provide at least one recipient email address.
2019/03/14 16:58:00 - CMDPHP PHP ERROR WARNING Backtrace: (/settings.php[254]:email_test(), /lib/functions.php[3837]:send_mail(), /lib/functions.php[3263]:mailer(), /lib/functions.php[3418]:parse_email_details(), /lib/functions.php[3637]:split_emaildetail(), /lib/functions.php[3683]:preg_match(), CactiErrorHandler())
2019/03/14 16:58:00 - ERROR PHP WARNING: preg_match(): Compilation failed: invalid range in character class at offset 29 in file: /usr/share/cacti/lib/functions.php on line: 3683
2019/03/14 16:58:00 - CMDPHP PHP ERROR WARNING Backtrace: (/settings.php[254]:email_test(), /lib/functions.php[3837]:send_mail(), /lib/functions.php[3263]:mailer(), /lib/functions.php[3386]:parse_email_details(), /lib/functions.php[3637]:split_emaildetail(), /lib/functions.php[3683]:preg_match(), CactiErrorHandler())
2019/03/14 16:58:00 - ERROR PHP WARNING: preg_match(): Compilation failed: invalid range in character class at offset 29 in file: /usr/share/cacti/lib/functions.php on line: 3683
2019/03/14 16:58:00 - CMDPHP PHP ERROR WARNING Backtrace: (/settings.php[254]:email_test(), /lib/functions.php[3837]:send_mail(), /lib/functions.php[3263]:mailer(), /lib/functions.php[3386]:parse_email_details(), /lib/functions.php[3637]:split_emaildetail(), /lib/functions.php[3683]:preg_match(), CactiErrorHandler())
2019/03/14 16:58:00 - ERROR PHP WARNING: preg_match(): Compilation failed: invalid range in character class at offset 29 in file: /usr/share/cacti/lib/functions.php on line: 3683 
```

Sorry if I wasn't supposed to reply here, I can open another issue, but it's a continuation of this one. 

I'm using cacti 1.2.2. 
With PHP 7.1 and 7.2, the test email works perfectly, but as soon as I upgraded it to PHP 7.3 it stopped working ( log section above )
Tried clean installs with PHP 7.1, 7.2 and 7.3, it only failed with PHP 7.3.
( btw, tried all mail services, the results are the same)

**Comment by netniV** [comment]
I will have to get PHP 7.3 installed and test it out.

**Comment by netniV** [comment]
Btw, can you also open this as a new issue since it isn't the same problem?

**Comment by justmace** [comment]
sure, issue https://github.com/Cacti/cacti/issues/2523 . thanks!
