### ISSUE TITLE
unknown status for devices polled by remote data collector

### ISSUE THREAD

**Issue by Carlimeunier** [Cacti/cacti#234]
After adding devices to be polled by remote data collector, i made a full sync.
The polling works quite well except minor issues ( The remote poller is always on recovery mode, the polling time always be around 298s while all spine processes are completed ( ps command ) ).
But the main problem is that the device status is unkown. Is there any way to raise the status of the device on the main server ( database ) ?

Thanks

**Comment by cigamit** [comment]
Run 'php -q poller_recovery.php --force --debug' and let us know the output

**Comment by Carlimeunier** [comment]
There is no error. Everything lokks ok.

I think the problem came from database settings in config.php and spine.conf for the remote data collector
For both, I set : 
 - Database(db) to the local database (on remote data collector) 
 - Remote database (rdb) points to the main cacti database

But it seems like spine uses local database (db) and poller.php, remote db (rdb). In this case it can't have the rigth poller_time table, hence the 298s

I also enabled "direct populaion of poller_output_boost table", maybe the reason why i had the "recovery" mode

Also, I would like to mention that the full sync doesn't work when there is a lot data

thanks

**Comment by cigamit** [comment]
Spine uses the remote database when the --mode option is set to 'online'.  In both 'offline', and 'recovery' spine will use the local database.

Please keep that in mind.  When you run spine by hand you need to specify the mode.  poller.php does this automatically.

Please let me know what tables are failing sync, and the MySQL error you are getting.  Thanks!

**Comment by cigamit** [comment]
No feedback.
