### ISSUE TITLE
Export hooks no longer work due to missing default keyword

### ISSUE THREAD

**Issue by YongBoLiu** [Cacti/cacti#2343]
Some code after 'break;', the code will never be executed. Missing a 'default:' in lib/export.php , make the logic error. 
Introduced in https://github.com/Cacti/cacti/commit/22d9444c31357109cf9c7cdacfa80a76e76eb768

It should be as below,

 					$xml_text .= "\n" . data_source_profile_to_xml($dep_id);
 					break;
 
+				default:
 					$param = array(); 					$xml_text .= "\n" . data_source_profile_to_xml($dep_id);
 					break;
 
+				default:
 					$param = array();
 					$param['dep_id']   = $dep_id;
 					$param['dep_type'] = $dep_type;

 					$param['dep_id']   = $dep_id;
 					$param['dep_type'] = $dep_type;

**Comment by YongBoLiu** [comment]
`+++ lib/export.php	2019-01-25 14:49:14.635851970 +0800
@@ -1117,6 +1117,7 @@
 					$xml_text .= "\n" . data_source_profile_to_xml($dep_id);
 					break;
 
+				default:
 					$param = array();
 					$param['dep_id']   = $dep_id;
 					$param['dep_type'] = $dep_type;
`
in function get_item_xml()

**Comment by netniV** [comment]
This is now in the main development code, please check and close if issue is resolved.

**Comment by YongBoLiu** [comment]
It's works in my Env. Thanks.
