### ISSUE TITLE
How to set this red dot? How is this blue line thickened?

### ISSUE THREAD

**Issue by tyit** [Cacti/cacti#2344]
![image](https://user-images.githubusercontent.com/31933126/51731490-12058880-20b6-11e9-8a5b-278551d21ae1.png)

Can you give me some instructions? Thank you very much.

**Comment by netniV** [comment]
They are defined by the graph template and/or graph itself.

**Comment by cigamit** [comment]
I'm pretty sure that this is a VRULE.  Not sure that they can be thickened.  Please check the documentation here.  You might be able to goto Tobi Oetikers GitHub and submit a pull request to add a feature though.  Merely suggesting that a feature be added is not sufficient though.  He will simply ask you to create it.

https://oss.oetiker.ch/rrdtool/doc/rrdgraph_graph.en.html
