### ISSUE TITLE
Cacti 1.2.1 Instalation

### ISSUE THREAD

**Issue by rcsmota** [Cacti/cacti#2348]
Hi;

I'm having a problem installing at the PHP - Module Support.

![image](https://user-images.githubusercontent.com/31240306/51767045-2193ca00-20d4-11e9-8422-7071e507aaf3.png)

I'm not a PHP expert but after search i think i have all modules or almost

/etc/php/7.0/mods-available# ls 
calendar.ini  exif.ini      gd.ini       iconv.ini  mbstring.ini  mysqlnd.ini  pdo_mysql.ini  readline.ini   snmp.ini     sysvsem.ini    wddx.ini       xmlwriter.ini
ctype.ini     fileinfo.ini  gettext.ini  json.ini   mcrypt.ini    opcache.ini  phar.ini       shmop.ini      sockets.ini  sysvshm.ini    xml.ini        xsl.ini
dom.ini       ftp.ini       gmp.ini      ldap.ini   mysqli.ini    pdo.ini      posix.ini      simplexml.ini  sysvmsg.ini  tokenizer.ini  xmlreader.ini

I dont know if I miss anything.

Thanks.

**Comment by netniV** [comment]
What OS are you on?  Make sure that you have enabled the modules for CLI, as it appears you have only enabled them for the web.

**Comment by pautiina** [comment]
I think you must install php-cli for your system

**Comment by rcsmota** [comment]
It's a Debian 9 (stretch) I tried using the phpmodmod command but no success. 

@pautiina I instaled now

apt install php-cli
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  php-cli
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 5,098 B of archives.
After this operation, 12.3 kB of additional disk space will be used.
Get:1 http://ftp.pt.debian.org/debian stretch/main amd64 php-cli all 1:7.0+49 [5,098 B]
Fetched 5,098 B in 0s (9,505 B/s)   
Selecting previously unselected package php-cli.
(Reading database ... 40380 files and directories currently installed.)
Preparing to unpack .../php-cli_1%3a7.0+49_all.deb ...
Unpacking php-cli (1:7.0+49) ...
Setting up php-cli (1:7.0+49) ...

But the same problem

I dont know if can help, these are depenecy intaled on Debian before cacti.

apache2 php libapache2-mod-php php-mcrypt php-mysql php-snmp php-xml php-ldap php-mbstring php-gmp snmp php-gd rrdtool mysql-server libssl-dev

and this is a output of command php -m

[PHP Modules]
calendar
Core
ctype
date
dom
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
json
ldap
libxml
mbstring
mcrypt
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
snmp
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zlib

[Zend Modules]
Zend OPcache

**Comment by rcsmota** [comment]
Hi @netniV 

After test i recived the follow messenge

PHP Fatal error:  Allowed memory size of 2097152 bytes exhausted (tried to allocate 20480 bytes) in /opt/cacti/lib/functions.php on line 4202

This was strange becouse I had changed the values in php.ini as it showed on Cacti's check

![image](https://user-images.githubusercontent.com/31240306/51774604-d638e600-20ea-11e9-9aa5-e6f6f81a5013.png)

After look,  I changed the file /etc/php/7.0/apache2/php.ini but need change too /etc/php/7.0/cli/php.ini

After this all work fine.

![image](https://user-images.githubusercontent.com/31240306/51774771-5c552c80-20eb-11e9-9f1f-e686826ff4cd.png)

Many thanks for help

**Comment by netniV** [comment]
OK, so I need to add some new checks for that.  Did the PHP recommendations (cli) not show the memory issue?

**Comment by netniV** [comment]
Yeah, we have had numerous issues in the past were people didn't realise and most got away with it for the most part.  However, there have been plenty of strange issues and the revamp to the 1.2 installer means it's checking a lot more of these things.

If it didn't warn you about the PHP memory at the CLI level, that would man it expects you would have had enough.  Can you mail me the json output to developers@cacti.net ? I just want to see how much was returned.

**Comment by rcsmota** [comment]
Of course! I am sending right now

**Comment by hoangh2** [comment]
I have same this problem, too.

My cacti install is running by php-fpm, how can i skip this CLI check ?

Thanks .

**Comment by hoangh2** [comment]
Can't next to step 3

**Comment by netniV** [comment]
You can't skip the cli check, it's required because we use the CLI.  Those modules must be enabled.

**Comment by hoangh2** [comment]
Hi,
How can I skip that CLI check ?
Thanks,

**Comment by netniV** [comment]
As stated above, you can't.

**Comment by wqmeng** [comment]
Hello, 

I got a error as this too.  After check the code,  I find that the 

$php = read_config_option('path_php_binary', true);  always return an empty string. 

So that, read the path_php_binary during the install process is not okay? Or I missing something in the config.php file, that I can setup the path_php_binary value in it before the install to get the var $php? 

The problem is in the function utility_php_extensions，utility_php_extensions and utility_php_optionals. 

Here I have a quick fix, hope it is useful for you.

[utility.php.txt](https://github.com/Cacti/cacti/files/3125037/utility.php.txt)

**Comment by wqmeng** [comment]
Aslo,  the $args = ' -q'; cause the php do not run correctly in cli.   So it is another small fix. 
[installer.php.txt](https://github.com/Cacti/cacti/files/3125119/installer.php.txt)


My PHP version is 7.3.4

PHP 7.3.4 (cli) (built: Apr 27 2019 19:27:16) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.4, Copyrigh
t (c) 1998-2018 Zend Technologies

I add the patch file here.

**Comment by netniV** [comment]
I'll take a look at both your patches. It can't make things worse; -)

With regards to the installer patch, I believe that code was added recently by one of my colleagues so I will have to double check what it's attempting to achieve and if/how it's affected the arguments because that will likely cause a problem when the test for a valid PHP installation is made as I suspect you've discovered.

**Comment by dedefri** [comment]
> 
> 
> Try doing the following
> 
> ```shell
> sudo -u www-data php -q /path/to/cacti/install/cli_check.php extensions
> ```
> 
> Then post the results which should be in JSON form.

hello, i have same problem (all module Cli - No). but im using windows 7x86 and cacti version 1.2.3
how can i solve this problem?? 

C:\Cacti\php>php -m
[PHP Modules]
bcmath
calendar
com_dotnet
Core
ctype
date
dom
filter
gd
gettext
gmp
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
Phar
readline
Reflection
session
SimpleXML
snmp
sockets
SPL
standard
tokenizer
wddx
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

![cacti](https://user-images.githubusercontent.com/50319643/57216638-9bfcb000-701a-11e9-9bde-b2fd6b6b4e69.png)

**Comment by sunchao19880719** [comment]
Hi,same problem in 1.2.4,has anyone slove this？

**Comment by sunchao19880719** [comment]
I've sloved this problem, just add a php program symbolic link to /bin/php

**Comment by darshakamodi** [comment]
how to solve that in windows ? I am getting same errors

**Comment by netniV** [comment]
Make sure the settings table in MySQL has an entry for path_php_binary which points to the correct php.exe location.

**Comment by netniV** [comment]
Starting with 1.2.5 the recommendations table will now notify if the php call fails to return the expected structure and what to do to correct it.

**Comment by blkwindy** [comment]
> 
> 
> how to solve that in windows ? I am getting same errors

I have the same problem in win2008.how to solve it?

**Comment by blkwindy** [comment]
and where is the settings table in MySQL?

**Comment by blkwindy** [comment]
i've solved the problem,thank you

**Comment by alisiddiqui1987** [comment]
Hi

I have the problem with cacti 1.2.7 version, I am using xampp latest version for apache and php on windows 10.

![cacti error](https://user-images.githubusercontent.com/56796839/67162422-79204700-f381-11e9-8a9f-a423f68e4b8a.PNG)


can some body please help. I am not familiar with any of the programming language so please help with step by step guide to get it fixed.

**Comment by netniV** [comment]
This basically means that your CLI version of PHP does not have those modules enabled and you need to ensure that it does.

**Comment by dsyun** [comment]
sunchao19880719
I've sloved this problem. I compiled php. 
So,  ln -s /<php compiled directory>/php/bin/php /bin/

**Comment by wqmeng** [comment]
@netniV 

The matter is not caused by the PHP modules. It is caused by the $php can not get a valid value. It is empty when the php bin not in the regular path such a /bin/php.  It can be fixed in the code by add a empty($php) condition if the php in a environment variables configurated path. 

Or ln -s create a link to the real php as /bin/php .

**Comment by netniV** [comment]
I swore there is a check performed to test for that,

**Comment by wqmeng** [comment]
In my case, 
```
[root@localhost ~]# whereis php
php: /usr/bin/php /usr/lib64/php /usr/local/php
```
The installer will show this error.  I have posted two patch files before.  Just add code $php = 'php', It will run the /usr/bin/php to pass this check. 

I suppose to test this, just move the php of /bin/php to other directory, it will show this error.  So the fix should be simple.

**Comment by praveenyeragani** [comment]
I'm getting the same Cli-No issue on widnows cacti install. please help me.

**Comment by netniV** [comment]
> My cacti install is running by php-fpm, how can i skip this CLI check ?

Using php-fpm is purely for the web side of things.  The CLI is likely to have its own php to run and so has its own checks.  Normally, the cli will have its work separate INI file too.

> In my case,
>
> ```[root@localhost ~]# whereis php
> php: /usr/bin/php /usr/lib64/php /usr/local/php
> ```
> The installer will show this error. I have posted two patch files before. Just add code $php = 'php', It will run the /usr/bin/php to pass this check.

There have been some improvements made to utilise the windows path to find PHP and also the environment var PHP_BINDIR, plus finally a configuration file option that will explicitly tell the installer which version of PHP should be the default.  However, if you have previously set path_php_binary in the settings table, that is the ultimate ruler.

**Comment by wildweaselmi** [comment]
I apologize but could use some help understanding how to finish my cacti install of version 1.2.10 on my CentOS 7 server with PHP 7.3
Required php modules I'm stuck on
gmp - Cli No
ldap - Cli No
snmp - Cli No
I have tried to remove PHP and reinstall, I have upgraded from 7.1 to 7.2 to 7.3 and they all have the same issue. I have searched the internet for any possible solution and running into walls.
We don't even use ldap and rely on local authentication.

Tried suggestions above which included installing php-cli and it doesn't work because its already installed
# yum install php-cli
Loaded plugins: fastestmirror, priorities
Loading mirror speeds from cached hostfile
 * base: centos.host-engine.com
 * centos-sclo-rh: bay.uchicago.edu
 * centos-sclo-sclo: linux.mirrors.es.net
 * epel: fedora-epel.mirror.lstn.net
 * extras: centos.sonn.com
 * remi-php71: fr2.rpmfind.net
 * remi-php73: fr2.rpmfind.net
 * remi-safe: fr2.rpmfind.net
 * updates: centos.mirrors.hoobly.com
Package php-cli-7.3.16-1.el7.remi.x86_64 already installed and latest version
Nothing to do

# whereis php
php: /usr/bin/php /usr/lib64/php /etc/php.d /etc/php.ini /usr/local/bin/php /usr/local/lib/php /usr/include/php /usr/local/php /usr/share/php /usr/share/man/man1/php.1.gz

Any help is appreciated

**Comment by TheWitness** [comment]
Go back to PHP5.4, otherwise use the official RH streams for the PHP7 stuff.

**Comment by TheWitness** [comment]
The other problem may be that you have two PHP installs somewhere and they are getting confused with one another.  I find that the stock RHEL/CentOS7 stuff just works.  No hacking required.

**Comment by wildweaselmi** [comment]
Thanks, when you mention go back to the RHEL/CentOS7 stuff, can you help me understand what you are asking.  Sorry I usually thumb my way through stuff but not sure how to approach your suggestions.  I already removed all php (sudo yum remove php*) and then re-installed with no difference.

**Comment by wildweaselmi** [comment]
Ok, I removed all extra repos and am just using CentOS/RHEL repos which when installing php currently installs php 5.4
Now I'm getting what everyone else appears to be getting which is all Cli - No for all required modules.  I installed php-cli but not sure what else needs to be done to fix this.

Modules installed
# php -m
[PHP Modules]
bz2
calendar
Core
ctype
curl
date
ereg
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
json
ldap
libxml
mbstring
mhash
mysql
mysqli
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
snmp
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
zip
zlib

[Zend Modules]

**Comment by netniV** [comment]
What memory limit do you have set against the cli's php.ini ? It is possible that if this memory limit is set too low, it will fail to run our code.

**Comment by wqmeng** [comment]
> 
> 
> I apologize but could use some help understanding how to finish my cacti install of version 1.2.10 on my CentOS 7 server with PHP 7.3
> Required php modules I'm stuck on
> gmp - Cli No
> ldap - Cli No
> snmp - Cli No
> I have tried to remove PHP and reinstall, I have upgraded from 7.1 to 7.2 to 7.3 and they all have the same issue. I have searched the internet for any possible solution and running into walls.
> We don't even use ldap and rely on local authentication.
> 
> Tried suggestions above which included installing php-cli and it doesn't work because its already installed
> # yum install php-cli
> 
> Loaded plugins: fastestmirror, priorities
> Loading mirror speeds from cached hostfile
> 
>     * base: centos.host-engine.com
> 
>     * centos-sclo-rh: bay.uchicago.edu
> 
>     * centos-sclo-sclo: linux.mirrors.es.net
> 
>     * epel: fedora-epel.mirror.lstn.net
> 
>     * extras: centos.sonn.com
> 
>     * remi-php71: fr2.rpmfind.net
> 
>     * remi-php73: fr2.rpmfind.net
> 
>     * remi-safe: fr2.rpmfind.net
> 
>     * updates: centos.mirrors.hoobly.com
>       Package php-cli-7.3.16-1.el7.remi.x86_64 already installed and latest version
>       Nothing to do
> 
> 
> # whereis php
> 
> php: /usr/bin/php /usr/lib64/php /etc/php.d /etc/php.ini /usr/local/bin/php /usr/local/lib/php /usr/include/php /usr/local/php /usr/share/php /usr/share/man/man1/php.1.gz
> 
> Any help is appreciated

@netniV 

Hi，

Just create a soft link of the /usr/bin/php to /bin/php,  you will pass it.

ln -s /usr/bin/php /bin/php

**Comment by TheWitness** [comment]
This is not the place for questions like this.  Just use the pho54 that comes with rhel7 and it works fine, or go-to rhel8, but you will have more steps.
