### ISSUE TITLE
snmp_sysDescr field contains mangled data

### ISSUE THREAD

**Issue by maforshaw** [Cacti/cacti#2352]
I've noticed that some of my Linux devices have mangled data in the snmp_sysDescr field. This field is set from the sysDescr OID and is included in alert e-mails.

Having confirmed that raw data from an snmpget is correct, I tracked the problem down to the function "format_snmp_string" in lib\snmp.php.

There is a block near the bottom that does the following regex:

`preg_match('/(hex:\?)?([a-fA-F0-9]{1,2}(:|\s)){5}/i', $string)`

That seems to be matching certain strings when it shouldn't. For example, consider the following sysDescr value:

`Linux hostname 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64`

That is mangled and output from "format_snmp_string" as:

`14:45:28:UTC:2018:X86_64`

I have other examples. It seems to be triggered by certain date/time values in the string?

I've worked around it with a nasty hack but I'm sure there is a proper fix for this:

`(preg_match('/(hex:\?)?([a-fA-F0-9]{1,2}(:|\s)){5}/i', $string) && (strpos($string, 'Linux ') === false))`

**Comment by netniV** [comment]
Actually, I think this would be a better capturing expression as it bypasses strings that may be time values:
```
([a-fA-F0-9]{1,2}(:[a-fA-F0-9]{1,2}){3,})
```
This would actually remove the need for the "Linux" check.  See: https://regex101.com/r/cCHBlb/1

**Comment by cigamit** [comment]
The whole thing was evil.  Now resolved by the way.  You have to update lib/functions.php and lib/snmp.php to resolve in production, or wait for 1.2.2.
