### ISSUE TITLE
Reindexing in Automation Not Updating Graph and Data Source Titles

### ISSUE THREAD

**Issue by maxstech** [Cacti/cacti#2354]
Hello
I use cacti 1.2.1 with ~1500 hosts and ~ 10000 graphs.  All these data  i getting with automation rules in cacti (graph rules, tree rules) and all it  excellent work when i creating my graphs. I getting only those graph which have "description" on my hardware.  
But  there are some problems with updates and changes data in automatic mode:
after i changed "description" on my hardware (switch)  I hope to receive new name in graph or the fact that this chart will be deleted because it no longer has a description and no longer falls under the rules of automation.
But this does not happen, i see old description. 
If i press reload query in  Management - Devices - Associated Data Queries then i see true description.   
By default , Re-Index Method -  Uptime, changing this does not help with automation. Only manual reload query. 
what can be done to automate this ???
p.s  Rerun Data Queries  - enabled  in automation - networks.
P.P.S.  i see to display the actual description, simply click: management -devices - edit my device - save (without even calling reload query).
But it not the solution, make saving for 1500 devices - manually unreal
I will wait for your comments, thank you.

**Comment by gebster** [comment]
I've run into the same issue. Would love to see what solutions could be make.

**Comment by cigamit** [comment]
I added some trace logic, and the re-indexes are indeed happening when the re-index option is checked for the network.  Can you please confirm that the re-index options is checked there?

**Comment by maxstech** [comment]
"when the re-index option is checked for the network."
Where are these options included?

**Comment by maxstech** [comment]
in "automation"  - > "networks"  i dont see any options for re-index.  If only talking about  option "Rerun Data Queries" -  it is enable. 
or are you talking about something else?

**Comment by cigamit** [comment]
Nope, that is it.  Ill have to tak a closer look to find differences.  What os is this, and did you yum/apt install or install some other way?

**Comment by maxstech** [comment]
![graph](https://user-images.githubusercontent.com/47040342/52057360-dbc47f00-2575-11e9-9e6d-37d98f7dfbd7.jpg)
![network](https://user-images.githubusercontent.com/47040342/52057361-dbc47f00-2575-11e9-8c32-071ca14fdfd3.jpg)
![tree](https://user-images.githubusercontent.com/47040342/52057362-dc5d1580-2575-11e9-944f-e86506ece816.jpg)

**Comment by maxstech** [comment]
I continue the test and see that even the automation process does not see the new description on my device.

![auto start](https://user-images.githubusercontent.com/47040342/52059654-72476f00-257b-11e9-9d57-b8ab1462465c.jpg)

Automation sees that all graphs are repeated.  But really graph with name "testwrite3"  was renamed on "testwrite4".

![default](https://user-images.githubusercontent.com/47040342/52059875-0d404900-257c-11e9-9f17-f6c06552f4f4.jpg)

now I go to in Management - Devices - this device 
and simply press  save

![save](https://user-images.githubusercontent.com/47040342/52060021-69a36880-257c-11e9-9ec0-ba77e46580b4.jpg)

and voila

![actual](https://user-images.githubusercontent.com/47040342/52060074-8344b000-257c-11e9-9ea3-c8413a3ed07e.jpg)

**Comment by cigamit** [comment]
Ope, that is different.  Tells me a lot...

**Comment by cigamit** [comment]
Okay, I've reverted to the pre 1.x behavior.  It'll make the re-indexing slower, but it's better to have good data then speed in this case.

**Comment by maxstech** [comment]
Thank you. Which files should I update ? Or completely reinstall cacti?

**Comment by cigamit** [comment]
Basically,  if and only if you are at 1.2.0 or better, just that file.  If you are on the 1.1.x series, just those three lines, but they may go someplace different.  This is due to a massive re-index design change in 1.2.0.  But since you are on 1.2.1, yup, just overwrite that file.

**Comment by maxstech** [comment]
Thanks. I will do this within two or three days and unsubscribe.

**Comment by maxstech** [comment]
it solved the problem, thank you.
