### ISSUE TITLE
Issue Cacti Version 1.1.38

### ISSUE THREAD

**Issue by c00k13z** [Cacti/cacti#2356]
I've issue with cacti Version 1.1.38, when I'am trying verbose query snmp, I got error this
![cacti](https://user-images.githubusercontent.com/12779223/51952321-a2531d00-246a-11e9-8d2c-62037c9434bc.PNG)

**Comment by c00k13z** [comment]
and this error manual rebuild poller cache
![cacti1](https://user-images.githubusercontent.com/12779223/51952443-1db4ce80-246b-11e9-81dd-5bd85012958a.PNG)

**Comment by cigamit** [comment]
This is due to the use of php7.  Either backoff php to version before php7 or upgrade Cacti to 1.2.1.
