### ISSUE TITLE
Poller issuing WARNINGS will little way to diagnose

### ISSUE THREAD

**Issue by jdcoats** [Cacti/cacti#2357]
I'm having trouble understanding this issue since I've upgraded from 1.1.38 to 1.2.1. Every time boost runs my poller runs long and I get the Poller Output Table not Empty. Ive tried reducing the data and increasing but it doesn't seem to make any difference.
![screen shot 01-30-19 at 09 03 am](https://user-images.githubusercontent.com/42470924/51986971-679fb380-246f-11e9-88c6-c7204915ab8a.PNG)

**Comment by cigamit** [comment]
Setup the MySQL/MariaDB slow query log to like 1 second and capture stats around that time.  See which table is blocking.

**Comment by jdcoats** [comment]
There does not appear to be anything out of the ordinary from the slowlog during the issue.

> syslog01 /var/log/mysql # cat slowquery.log
# Time: 190130 15:17:37
# User@Host: cacti123[cacti123] @ localhost []
# Thread_id: 265939  Schema: syslog  QC_hit: No
# Query_time: 2.171571  Lock_time: 0.000122  Rows_sent: 0  Rows_examined: 90790
# Rows_affected: 45395
SET timestamp=1548879457;
INSERT INTO `syslog`.`syslog` (logtime, priority_id, facility_id, program_id, host_id, message) SELECT TIMESTAMP(`date`, `time`), priority_id, facility_id, program_id, host_id, message FROM (SELECT date, time, priority_id, facility_id, program_id, host_id, message FROM syslog_incoming AS si INNER JOIN syslog_hosts AS sh ON sh.host=si.host INNER JOIN syslog_programs AS sp ON sp.program=si.program WHERE status=10) AS merge;
# Time: 190130 15:18:50
# User@Host: cacti123[cacti123] @ localhost []
# Thread_id: 270068  Schema: syslog  QC_hit: No
# Query_time: 2.892002  Lock_time: 0.000115  Rows_sent: 0  Rows_examined: 119968
# Rows_affected: 59984
SET timestamp=1548879530;
INSERT INTO `syslog`.`syslog` (logtime, priority_id, facility_id, program_id, host_id, message) SELECT TIMESTAMP(`date`, `time`), priority_id, facility_id, program_id, host_id, message FROM (SELECT date, time, priority_id, facility_id, program_id, host_id, message FROM syslog_incoming AS si INNER JOIN syslog_hosts AS sh ON sh.host=si.host INNER JOIN syslog_programs AS sp ON sp.program=si.program WHERE status=41) AS merge;
# Time: 190130 15:19:46
# User@Host: cacti123[cacti123] @ localhost []
# Thread_id: 274191  Schema: syslog  QC_hit: No
# Query_time: 2.519348  Lock_time: 0.000127  Rows_sent: 0  Rows_examined: 102028
# Rows_affected: 51014
SET timestamp=1548879586;
INSERT INTO `syslog`.`syslog` (logtime, priority_id, facility_id, program_id, host_id, message) SELECT TIMESTAMP(`date`, `time`), priority_id, facility_id, program_id, host_id, message FROM (SELECT date, time, priority_id, facility_id, program_id, host_id, message FROM syslog_incoming AS si INNER JOIN syslog_hosts AS sh ON sh.host=si.host INNER JOIN syslog_programs AS sp ON sp.program=si.program WHERE status=93) AS merge;
# Time: 190130 15:20:47
# User@Host: cacti123[cacti123] @ localhost []
# Thread_id: 278312  Schema: syslog  QC_hit: No
# Query_time: 2.438350  Lock_time: 0.000107  Rows_sent: 0  Rows_examined: 94152
# Rows_affected: 47076
SET timestamp=1548879647;
INSERT INTO `syslog`.`syslog` (logtime, priority_id, facility_id, program_id, host_id, message) SELECT TIMESTAMP(`date`, `time`), priority_id, facility_id, program_id, host_id, message FROM (SELECT date, time, priority_id, facility_id, program_id, host_id, message FROM syslog_incoming AS si INNER JOIN syslog_hosts AS sh ON sh.host=si.host INNER JOIN syslog_programs AS sp ON sp.program=si.program WHERE status=49) AS merge;
# Time: 190130 15:21:48
# User@Host: cacti123[cacti123] @ localhost []
# Thread_id: 282433  Schema: syslog  QC_hit: No
# Query_time: 2.843300  Lock_time: 0.000114  Rows_sent: 0  Rows_examined: 113810
# Rows_affected: 56905
SET timestamp=1548879708;
INSERT INTO `syslog`.`syslog` (logtime, priority_id, facility_id, program_id, host_id, message) SELECT TIMESTAMP(`date`, `time`), priority_id, facility_id, program_id, host_id, message FROM (SELECT date, time, priority_id, facility_id, program_id, host_id, message FROM syslog_incoming AS si INNER JOIN syslog_hosts AS sh ON sh.host=si.host INNER JOIN syslog_programs AS sp ON sp.program=si.program WHERE status=34) AS merge;
# Time: 190130 15:22:58
# User@Host: cacti123[cacti123] @ localhost []
# Thread_id: 286558  Schema: syslog  QC_hit: No
# Query_time: 3.176440  Lock_time: 0.000147  Rows_sent: 0  Rows_examined: 129026
# Rows_affected: 64513
SET timestamp=1548879778;
INSERT INTO `syslog`.`syslog` (logtime, priority_id, facility_id, program_id, host_id, message) SELECT TIMESTAMP(`date`, `time`), priority_id, facility_id, program_id, host_id, message FROM (SELECT date, time, priority_id, facility_id, program_id, host_id, message FROM syslog_incoming AS si INNER JOIN syslog_hosts AS sh ON sh.host=si.host INNER JOIN syslog_programs AS sp ON sp.program=si.program WHERE status=111) AS merge;
# Time: 190130 15:23:54
# User@Host: cacti123[cacti123] @ localhost []
# Thread_id: 290677  Schema: syslog  QC_hit: No
# Query_time: 2.621358  Lock_time: 0.000103  Rows_sent: 0  Rows_examined: 98656
# Rows_affected: 49328
SET timestamp=1548879834;
INSERT INTO `syslog`.`syslog` (logtime, priority_id, facility_id, program_id, host_id, message) SELECT TIMESTAMP(`date`, `time`), priority_id, facility_id, program_id, host_id, message FROM (SELECT date, time, priority_id, facility_id, program_id, host_id, message FROM syslog_incoming AS si INNER JOIN syslog_hosts AS sh ON sh.host=si.host INNER JOIN syslog_programs AS sp ON sp.program=si.program WHERE status=21) AS merge;
# Time: 190130 15:25:35
# User@Host: cacti123[cacti123] @ localhost []
# Thread_id: 295283  Schema: syslog  QC_hit: No
# Query_time: 4.115833  Lock_time: 0.000095  Rows_sent: 0  Rows_examined: 159740
# Rows_affected: 79870
SET timestamp=1548879935;
INSERT INTO `syslog`.`syslog` (logtime, priority_id, facility_id, program_id, host_id, message) SELECT TIMESTAMP(`date`, `time`), priority_id, facility_id, program_id, host_id, message FROM (SELECT date, time, priority_id, facility_id, program_id, host_id, message FROM syslog_incoming AS si INNER JOIN syslog_hosts AS sh ON sh.host=si.host INNER JOIN syslog_programs AS sp ON sp.program=si.program WHERE status=2) AS merge;
# Time: 190130 15:25:36
# User@Host: cacti123[cacti123] @ localhost []
# Thread_id: 295283  Schema: syslog  QC_hit: No
# Query_time: 1.255461  Lock_time: 0.000054  Rows_sent: 0  Rows_examined: 79870
# Rows_affected: 79870
SET timestamp=1548879936;
DELETE FROM `syslog`.`syslog_incoming` WHERE status=2;
# Time: 190130 15:25:41
# User@Host: cacti123[cacti123] @ localhost []
# Thread_id: 299147  Schema: syslog  QC_hit: No
# Query_time: 1.002520  Lock_time: 0.000103  Rows_sent: 0  Rows_examined: 40490
# Rows_affected: 20245
SET timestamp=1548879941;
INSERT INTO `syslog`.`syslog` (logtime, priority_id, facility_id, program_id, host_id, message) SELECT TIMESTAMP(`date`, `time`), priority_id, facility_id, program_id, host_id, message FROM (SELECT date, time, priority_id, facility_id, program_id, host_id, message FROM syslog_incoming AS si INNER JOIN syslog_hosts AS sh ON sh.host=si.host INNER JOIN syslog_programs AS sp ON sp.program=si.program WHERE status=111) AS merge;
# Time: 190130 15:26:49
# User@Host: cacti123[cacti123] @ localhost []
# Thread_id: 303269  Schema: syslog  QC_hit: No
# Query_time: 2.496374  Lock_time: 0.000126  Rows_sent: 0  Rows_examined: 102528
# Rows_affected: 51264
SET timestamp=1548880009;
INSERT INTO `syslog`.`syslog` (logtime, priority_id, facility_id, program_id, host_id, message) SELECT TIMESTAMP(`date`, `time`), priority_id, facility_id, program_id, host_id, message FROM (SELECT date, time, priority_id, facility_id, program_id, host_id, message FROM syslog_incoming AS si INNER JOIN syslog_hosts AS sh ON sh.host=si.host INNER JOIN syslog_programs AS sp ON sp.program=si.program WHERE status=26) AS merge;

**Comment by cigamit** [comment]
Yea, quite weird.  Do you have more than one data collector?  Do a top during this period to watch load.

**Comment by jdcoats** [comment]
no significant load issues but i do find that every now and then script_server process will hang and will need to be killed. There were 2 hung this morning that had been there for 16hrs and now another 2 that have been hung for over an hour:
root     12761 99.6  0.1 150356 28560 ?        R    09:28  73:18 /usr/bin/php -q /var/www/localhost/htdocs/cacti/script_server.php spine 1
root     32330 98.3  0.1 155028 28924 ?        R    09:27  73:20 /usr/bin/php -q /var/www/localhost/htdocs/cacti/script_server.php spine 1

The spine Problems parsing Multi SNMP OID! are new with this version of spine.
[spine.txt](https://github.com/Cacti/cacti/files/2817978/spine.txt)
[Uploading spineV7.txt…]()

**Comment by cigamit** [comment]
Okay, you have some damaged Data Sources.  Were you running any of the 1.2 Betas?  Let me know.  For each of those Data Source with the issue, edit the Data Source and re-establish the correct index for the Data Sources and the issue will go away.  This was a bug introduced in one of the 1.2 Beta's.

**Comment by jdcoats** [comment]
I went directly from 1.1.38 to 1.2.1 no betas. I may have to delete all graphs and DS then, it seems wide spread as far as which devices are left hanging. Is there an easier way to determine which are causing it? I did already delete over 10k DS (mostly esxi host queries(changed all of the esxi to ping only until i can sort this out)) just trying to get it as stable as it is now so that I can troubleshoot.

**Comment by cigamit** [comment]
Search the poller cache with arg1 that ends with a period.

`SELECT COUNT(*) FROM poller_item WHERE arg1 LIKE '%.';`

Let me know what type of Data Template they are coming from.  Also, what device type.

**Comment by jdcoats** [comment]
`MariaDB [cacti]> SELECT COUNT(*) FROM poller_item WHERE arg1 LIKE '%.';
+----------+
| COUNT(*) |
+----------+
|    12550 |
+----------+
1 row in set (0.00 sec)
`

**Comment by cigamit** [comment]
Keep me posted.

**Comment by jdcoats** [comment]
most prevalent when running reindex is 

> PHP Notice:  Undefined offset: 0 in /var/www/localhost/htdocs/cacti/scripts/ss_host_disk.php on line 93
PHP Notice:  Undefined offset: 1 in /var/www/localhost/htdocs/cacti/scripts/ss_host_disk.php on line 93
PHP Notice:  Undefined offset: 2 in /var/www/localhost/htdocs/cacti/scripts/ss_host_disk.php on line 93
PHP Notice:  Undefined offset: 3 in /var/www/localhost/htdocs/cacti/scripts/ss_host_disk.php on line 93
PHP Notice:  Undefined offset: 4 in /var/www/localhost/htdocs/cacti/scripts/ss_host_disk.php on line 93
PHP Notice:  Undefined offset: 5 in /var/www/localhost/htdocs/cacti/scripts/ss_host_disk.php on line 93
PHP Notice:  Undefined offset: 6 in /var/www/localhost/htdocs/cacti/scripts/ss_host_disk.php on line 93
PHP Notice:  Undefined offset: 7 in /var/www/localhost/htdocs/cacti/scripts/ss_host_disk.php on line 93

**Comment by cigamit** [comment]
Okay, the undefined indexes are a pretty big deal.  I'll look at that.  But could you also get one of the Windows deivces back up, and after the subsequent re-index, verify that the indexes remap properly, then take it back down again and then re-attempt a re-index and let me know what happens?

**Comment by jdcoats** [comment]
Yes I will, It sure would be nice if on the Datasources and Graphs page you could filter by "device type" It would be a lot easier to find them all. :) I'm close.
`MariaDB [cacti]> SELECT COUNT(*) FROM poller_item WHERE arg1 LIKE '%.';
+----------+
| COUNT(*) |
+----------+
|     1095 |
+----------+
1 row in set (0.05 sec)`

**Comment by jdcoats** [comment]
![untitled](https://user-images.githubusercontent.com/42470924/52159124-f417c500-266d-11e9-9c51-d435b63dce2a.png)

windows host query

**Comment by cigamit** [comment]
Oh holy crap.  Is that for timed out devices and before or after the changes?

**Comment by cigamit** [comment]
I think you should remove those entries from the various tables.  Can you tell me if those devices are on a remote data collector?  I'm trying to understand how html streams were inserted into the table.

I will make a change to remove those cleared indexes from the poller cache, and issue a periodic warning, and then ensure that when the poller cache is re-populated, that they don't wind up back in the poller cache.

In the mean time, tell me more about the devices with the bogus information in their snmp cache.

**Comment by cigamit** [comment]
Okay, note the device ID, and due the following:

`DELETE FROM host_snmp_cache WHERE host_id = ?`

Do that and then re-index, does the problem go away, at least for the disk data query?  If it continues for the process data query, you should upload the php script here and we can fix it and make it part of the package, though if I remember, if it was the snmpwalk one, it's horribly unreliable.  Better to use hmib.

**Comment by jdcoats** [comment]
no, refresh just re-populates it.

**Comment by cigamit** [comment]
It's weird cause that is not even cacti responses.  Can you tcpdump it and see what is going on?  Very odd.  In the mean time, since I'm working on Plugins today, I'll re-install hmib.  I've got to repackage the templates anyway due to this script change.  Might as well get to it.  But that html is not coming from any Cacti system, so I'm wondering where it's coming from...

Can you run the re-indexing script by hand?  Basically:

`cd scripts
php -q ss_host_disk.php ...`

Just run a verbose query and copy the line you see there into a shell script on the server.  Let's see what that returns.

**Comment by jdcoats** [comment]
I have to leave town unexpectedly. I’ll be back to troubleshooting this on Monday.


——
Dan

On February 2, 2019 at 9:38:13 AM EST, Jimmy Conner <notifications@github.com> wrote:

CAUTION! This email came from outside Tallahassee Memorial HealthCare. Exercise extra caution clicking links and opening attachments from any and all senders.


________________________________
It's weird cause that is not even cacti responses. Can you tcpdump it and see what is going on? Very odd. In the mean time, since I'm working on Plugins today, I'll re-install hmib. I've got to repackage the templates anyway due to this script change. Might as well get to it. But that html is not coming from any Cacti system, so I'm wondering where it's coming from...

Can you run the re-indexing script by hand? Basically:

cd scripts php -q ss_host_disk.php ...

Just run a verbose query and copy the line you see there into a shell script on the server. Let's see what that returns.

**Comment by cigamit** [comment]
I've made an update that will do the following:
1) Remove bad items from the poller cache on Re-Index or Device save
2) Provide semi daily warning messages of the presence of these bad indexes
3) Provide a way for you to filter the bad indexes from the Data Sources page

I hope this is enough to at lease uncover the scope of the issue.  We still need to correct scripts of course that have issues.

**Comment by jdcoats** [comment]
FYI, if you didn't figure this part out this weekend, the html being inserted is directly from ss_host_disk.php and ss_host_cpu.php

**Comment by cigamit** [comment]
Somehow that does not make sense.  I saw &lt;span&gt; tags, which those scripts don't include.

**Comment by jdcoats** [comment]
Instead of a screenshot, I copy and paste.
`

DOCTYPE html> | DOCTYPE html> | DOCTYPE html> |  
-- | -- | -- | --
--  '"` --><!-- </textarea></xmp>  --></option></form><form  action="/site/dismiss_signup_prompt" accept-charset="UTF-8"  method="post"><input name="utf8" type="hidden" value="✓"  /><input type="hidden" name="authenticity_token"  value="qiGDKh9GV6nyzr0tWd58AvY2LVxXKRAVcgsfKJnhG855iyO+U3S802/me+nonuzWwP5m3cwP69GJQY5vUj4u9A=="  /> | --  '"` --></option></form><form  action="/site/dismiss_signup_prompt" accept-charset="UTF-8"  method="post"><input name="utf8" type="hidden" value="✓"  /><input type="hidden" name="authenticity_token"  value="qiGDKh9GV6nyzr0tWd58AvY2LVxXKRAVcgsfKJnhG855iyO+U3S802/me+nonuzWwP5m3cwP69GJQY5vUj4u9A=="  /> | --  '"` --></option></form><form  action="/site/dismiss_signup_prompt" accept-charset="UTF-8"  method="post"><input name="utf8" type="hidden" value="✓"  /><input type="hidden" name="authenticity_token"  value="qiGDKh9GV6nyzr0tWd58AvY2LVxXKRAVcgsfKJnhG855iyO+U3S802/me+nonuzWwP5m3cwP69GJQY5vUj4u9A=="  /> |  
<span  class="pl-pds">'</span></span> <span  class="pl-k">.</span> <span class="pl-s"><span  class="pl-pds">"</span>Unknown<span  class="pl-cce">\n</span><span  class="pl-pds">"</span></span>;</span></td> | <span  class="pl-pds">'</span></span> <span  class="pl-k">.</span> <span class="pl-s"><span  class="pl-pds">"</span>Unknown<span  class="pl-cce">\n</span><span  class="pl-pds">"</span></span>;</span></td> | <span  class="pl-pds">'</span></span> <span  class="pl-k">.</span> <span class="pl-s"><span  class="pl-pds">"</span>Unknown<span  class="pl-cce">\n</span><span  class="pl-pds">"</span></span>;</span></td> |  
</span><span  class="pl-c1">isset</span>(<span  class="pl-smi">$called_by_script_server</span>))  {</span></td> | </span><span  class="pl-c1">isset</span>(<span  class="pl-smi">$called_by_script_server</span>))  {</span></td> | </span><span  class="pl-c1">isset</span>(<span  class="pl-smi">$called_by_script_server</span>))  {</span></td> |  
</span><span  class="pl-c1">isset</span>(<span  class="pl-smi">$arr</span>[<span  class="pl-smi">$i</span>][<span class="pl-s"><span  class="pl-pds">'</span>value<span  class="pl-pds">'</span></span>]))  {</span></td> | </span><span  class="pl-c1">isset</span>(<span  class="pl-smi">$arr</span>[<span  class="pl-smi">$i</span>][<span class="pl-s"><span  class="pl-pds">'</span>value<span  class="pl-pds">'</span></span>]))  {</span></td> | </span><span  class="pl-c1">isset</span>(<span  class="pl-smi">$arr</span>[<span  class="pl-smi">$i</span>][<span class="pl-s"><span  class="pl-pds">'</span>value<span  class="pl-pds">'</span></span>]))  {</span></td> |  
<span  class="pl-pds">'</span></span> <span  class="pl-k">.</span> <span  class="pl-smi">$arr</span>[<span  class="pl-smi">$i</span>] <span  class="pl-k">.</span> <span class="pl-s"><span  class="pl-pds">"</span><span  class="pl-cce">\n</span><span  class="pl-pds">"</span></span>;</span></td> | <span  class="pl-pds">'</span></span> <span  class="pl-k">.</span> <span  class="pl-smi">$arr</span>[<span  class="pl-smi">$i</span>] <span  class="pl-k">.</span> <span class="pl-s"><span  class="pl-pds">"</span><span  class="pl-cce">\n</span><span  class="pl-pds">"</span></span>;</span></td> | <span  class="pl-pds">'</span></span> <span  class="pl-k">.</span> <span  class="pl-smi">$arr</span>[<span  class="pl-smi">$i</span>] <span  class="pl-k">.</span> <span class="pl-s"><span  class="pl-pds">"</span><span  class="pl-cce">\n</span><span  class="pl-pds">"</span></span>;</span></td> |  
--  '"` --><!-- </textarea></xmp>  --></option></form><form class="js-jump-to-line-form  Box-body d-flex" action="" accept-charset="UTF-8"  method="get"><input name="utf8" type="hidden" value="✓" /> | --  '"` --></option></form><form class="js-jump-to-line-form  Box-body d-flex" action="" accept-charset="UTF-8"  method="get"><input name="utf8" type="hidden" value="✓" /> | --  '"` --></option></form><form class="js-jump-to-line-form  Box-body d-flex" action="" accept-charset="UTF-8"  method="get"><input name="utf8" type="hidden" value="✓" /> |  
-- blob contrib key: blob_contributors:v21:c33965b20d69ff71118c8a2f0080ce53 --> | -- blob contrib key: blob_contributors:v21:c33965b20d69ff71118c8a2f0080ce53 --> | -- blob contrib key: blob_contributors:v21:c

Then i grep for blob_contributors and find them. 


`

**Comment by jdcoats** [comment]
from the graph creation page when refreshing or hitting the back button it will do this.
![screen shot 02-04-19 at 08 53 am](https://user-images.githubusercontent.com/42470924/52212476-8f6d8d80-285a-11e9-8ea4-5e38669c46e7.PNG)

**Comment by jdcoats** [comment]
okay, If i clear the cache from a host
`MariaDB [cacti]> DELETE FROM host_snmp_cache WHERE host_id = 3245;
`
Then requery now, the snmp hrstoragetable and snmp get processor information works but the get mounted partitions does not. at least it isnt populating with the html. Now I have to figure out how to clean up the rest of them.

**Comment by jdcoats** [comment]
Total: 0.000000, Delta: 0.000000, Running Data Query [8]. Total: 0.000000, Delta: 0.000000, Found Type = '6' [Script Query - Script Server]. Total: 0.000000, Delta: 0.000000, Found data query XML file at  '/var/www/localhost/htdocs/cacti/resource/script_server/host_disk.xml' Total: 0.000000, Delta: 0.000000, XML file parsed ok. Total: 0.280000, Delta: 0.280000, Executing script for num of  indexes '"/usr/bin/php" -q  /var/www/localhost/htdocs/cacti/scripts/ss_host_disk.php '10.9.75.227'  '3245' '2:161:1000:2:10:weARE#1!::::::' 'num_indexes'' Total: 0.280000, Delta: 0.000000, Found number of indexes: 5 Total: 0.550000, Delta: 0.270000, ERROR: Data Query returned no indexes. | Total: 0.000000, Delta: 0.000000, Running Data Query [8]. | Total: 0.000000, Delta: 0.000000, Found Type = '6' [Script Query - Script Server]. | Total: 0.000000, Delta: 0.000000, Found data query XML file at  '/var/www/localhost/htdocs/cacti/resource/script_server/host_disk.xml' | Total: 0.000000, Delta: 0.000000, XML file parsed ok. | Total: 0.280000, Delta: 0.280000, Executing script for num of  indexes '"/usr/bin/php" -q  /var/www/localhost/htdocs/cacti/scripts/ss_host_disk.php '10.9.75.227'  '3245' '2:161:1000:2:10:weARE#1!::::::' 'num_indexes'' | Total: 0.280000, Delta: 0.000000, Found number of indexes: 5 | Total: 0.550000, Delta: 0.270000, ERROR: Data Query returned no indexes.
-- | -- | -- | -- | -- | -- | -- | --
Total: 0.000000, Delta: 0.000000, Running Data Query [8].
Total: 0.000000, Delta: 0.000000, Found Type = '6' [Script Query - Script Server].
Total: 0.000000, Delta: 0.000000, Found data query XML file at  '/var/www/localhost/htdocs/cacti/resource/script_server/host_disk.xml'
Total: 0.000000, Delta: 0.000000, XML file parsed ok.
Total: 0.280000, Delta: 0.280000, Executing script for num of  indexes '"/usr/bin/php" -q  /var/www/localhost/htdocs/cacti/scripts/ss_host_disk.php '10.9.75.227'  '3245' '2:161:1000:2:10:weARE#1!::::::' 'num_indexes''
Total: 0.280000, Delta: 0.000000, Found number of indexes: 5
Total: 0.550000, Delta: 0.270000, ERROR: Data Query returned no indexes.

**Comment by jdcoats** [comment]
`

2019/02/04  09:38:14 - CMDPHP PHP ERROR NOTICE Backtrace:   (/scripts/ss_host_disk.php[17]:call_user_func_array(), ss_host_disk(),  /scripts/ss_host_disk.php[66]:CactiErrorHandler())
--
2019/02/04 09:38:14 - ERROR PHP NOTICE: Undefined variable:  return_array in file:  /var/www/localhost/htdocs/cacti/scripts/ss_host_disk.php  on line: 66
2019/02/04 09:38:03 - CMDPHP PHP ERROR NOTICE Backtrace:   (/scripts/ss_host_disk.php[17]:call_user_func_array(), ss_host_disk(),  /scripts/ss_host_disk.php[66]:CactiErrorHandler())
2019/02/04 09:38:03 - ERROR PHP NOTICE: Undefined variable:  return_array in file:  /var/www/localhost/htdocs/cacti/scripts/ss_host_disk.php  on line: 66

`

**Comment by cigamit** [comment]
Look at issue #2372 as well.  Fixing this shortly.

**Comment by cigamit** [comment]
Closing.
