### ISSUE TITLE
Realtime Plugin not create rrd

### ISSUE THREAD

**Issue by pautiina** [Cacti/cacti#236]
Realtime Plugin not create rrd file and create empty png.
Poller is SPINE.
Table poller_output_realtime MySQL have data
The problem was that the field poller_id varhar = 30, and session_id () 32 characters long. The problem is solved as follows:
ALTER TABLE `poller_output_realtime` CHANGE `poller_id` `poller_id` VARCHAR(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';

**Comment by cigamit** [comment]
Resolved, thanks for reporting.  You should change the width to 256 as that is the max supported by php7.1.

**Comment by pautiina** [comment]
My configuration server: 
```
Apache/2.4.25 (FreeBSD) PHP/7.0.15
Версия клиента базы данных: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: b5c5906d452ec590732a93b051f3827e02749b83 $
```
```
Тип сервера: MySQL
Версия сервера: 5.6.35 - Source distribution
```
And if I'm change:
```
ALTER TABLE `poller_output_realtime` CHANGE `poller_id` `poller_id` VARCHAR(256) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';
```
Mysql have error:
`#1071 - Указан слишком длинный ключ. Максимальная длина ключа составляет 767 байт`

I enter VARCHAR(255) and all GOOD:

`ALTER TABLE `poller_output_realtime` CHANGE `poller_id` `poller_id` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''`
Mysql report good:
` MySQL вернула пустой результат (т.е. ноль строк). (Запрос занял 0.0178 сек.)`

**Comment by cigamit** [comment]
You should retest.  This has been resolved.  Thanks for testing.

**Comment by pautiina** [comment]
Thanks, now works. All is well
