### ISSUE TITLE
When retrieving database / table / column information, schema name is not always applied

### ISSUE THREAD

**Issue by dbrummer** [Cacti/cacti#2360]
Hello,
I just upgraded to 1.2.1 from 1.1.38 and ran into an interesting issue.  When first attempting to login I receive the following error message:

Failed to alter password field length, can not continue as may corrupt password

After investigating the code I saw that it was die'ng at lib/database.php db_check_password_length().  I put in a few echo statements to investigate the length that was being returned and the value was always '50'.  I tried recreating the 'admin' username in MySQL but it still was only '50'.  I eventually pulled the INSERT statement for username 'admin' from a fresh install and it still died.  I eventually just commented out line 1416 in lib/database.php and it allowed me to login and then requested my password be changed.

Is '80' the right length to be checking for because it seems to always die on my length '50' passwords.

Thanks.

**Comment by netniV** [comment]
Sounds more like the password field length isn't right in the DB on the user_auth table or you have a minimum length specified within your settings table.

**Comment by cigamit** [comment]
Any update?  This sounds significant.

**Comment by dbrummer** [comment]
secpass_minlen is set to '8' and my password was 8 characters in length before being forced to change.

**Comment by cigamit** [comment]
So, then is this issue resolved?

**Comment by dbrummer** [comment]
For me it's not - I have a workaround in place that comments out the 'die' in lib/database.php.  If I remove my workaround I still receive the "Failed to alter password field length, can not continue as may corrupt password" error message.

**Comment by cigamit** [comment]
Figured it out.  'password' is a reserved word now.

**Comment by cigamit** [comment]
Take that back.  Works fine.

**Comment by netniV** [comment]
As your cacti DB user, can you run the following?
```sql
SELECT COLUMN_NAME,CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns WHERE table_name = 'user_auth' and column_name IN ('password')
    -> ;
+-------------+--------------------------+
| COLUMN_NAME | CHARACTER_MAXIMUM_LENGTH |
+-------------+--------------------------+
| password    |                     2048 |
+-------------+--------------------------+
1 row in set (0.00 sec)
```

**Comment by dbrummer** [comment]
`MariaDB [cacti]> SELECT COLUMN_NAME,CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns WHERE table_name = 'user_auth' and column_name IN ('password');
+-------------+--------------------------+
| COLUMN_NAME | CHARACTER_MAXIMUM_LENGTH |
+-------------+--------------------------+
| password    |                      256 |
| password    |                       50 |
| password    |                       50 |
+-------------+--------------------------+
3 rows in set (0.12 sec)
`

I think I see the problem there...

**Comment by netniV** [comment]
That can't be right... three columns called password???

**Comment by dbrummer** [comment]
Looks like the user_auth table is triplicated:

> MariaDB [cacti]> SELECT COLUMN_NAME,CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns WHERE table_name = 'user_auth';
+------------------------+--------------------------+
| COLUMN_NAME            | CHARACTER_MAXIMUM_LENGTH |
+------------------------+--------------------------+
| id                     |                     NULL |
| username               |                       50 |
| password               |                      256 |
| realm                  |                     NULL |
| full_name              |                      100 |
| email_address          |                      128 |
| must_change_password   |                        2 |
| password_change        |                        2 |
| show_tree              |                        2 |
| show_list              |                        2 |
| show_preview           |                        2 |
| graph_settings         |                        2 |
| login_opts             |                     NULL |
| policy_graphs          |                     NULL |
| policy_trees           |                     NULL |
| policy_hosts           |                     NULL |
| policy_graph_templates |                     NULL |
| enabled                |                        2 |
| lastchange             |                     NULL |
| lastlogin              |                     NULL |
| password_history       |                     4096 |
| locked                 |                        3 |
| failed_attempts        |                     NULL |
| lastfail               |                     NULL |
| reset_perms            |                     NULL |
| id                     |                     NULL |
| username               |                       50 |
| password               |                       50 |
| realm                  |                     NULL |
| full_name              |                      100 |
| must_change_password   |                        2 |
| show_tree              |                        2 |
| show_list              |                        2 |
| show_preview           |                        2 |
| graph_settings         |                        2 |
| login_opts             |                     NULL |
| policy_graphs          |                     NULL |
| policy_trees           |                     NULL |
| policy_hosts           |                     NULL |
| policy_graph_templates |                     NULL |
| enabled                |                        2 |
| id                     |                     NULL |
| username               |                       50 |
| password               |                       50 |
| realm                  |                     NULL |
| full_name              |                      100 |
| must_change_password   |                        2 |
| show_tree              |                        2 |
| show_list              |                        2 |
| show_preview           |                        2 |
| graph_settings         |                        2 |
| login_opts             |                     NULL |
| policy_graphs          |                     NULL |
| policy_trees           |                     NULL |
| policy_hosts           |                     NULL |
| policy_graph_templates |                     NULL |
| enabled                |                        2 |
+------------------------+--------------------------+

Should I try blowing it out and recreating it?

**Comment by netniV** [comment]
Multiple databases?

**Comment by dbrummer** [comment]
I did have a few old backed up cacti databases.  After re-running the query it appears correct:

> MariaDB [(none)]> SELECT COLUMN_NAME,CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns WHERE table_name = 'user_auth' and column_name IN ('password');
+-------------+--------------------------+
| COLUMN_NAME | CHARACTER_MAXIMUM_LENGTH |
+-------------+--------------------------+
| password    |                      256 |
+-------------+--------------------------+
1 row in set (0.00 sec)

**Comment by netniV** [comment]
I wonder if the code is including the schema name... maybe it isn't and that would be why you had the issue.  Let me check...

**Comment by dbrummer** [comment]
You guys rock, thanks!
