### ISSUE TITLE
No way to default an interface speed when ifSpeed and ifHighSpeed come back as zero

### ISSUE THREAD

**Issue by kruegerj** [Cacti/cacti#2362]
original forum post:

Hello,

in my Data Queries "SNMP - Interface Statistics" is configured if i use Associated Graph Templates "In/Out Bits (64-bit Counters)", that the Suggested Values - Data Sources "rrd_maximum" should set with Equation |query_ifHighSpeed|. But it looks like that's not applied.

If i create graphs, with this Graph Templates, the rrd_maximum is set to "U". 

Cacti Version: 1.2.1

ifHighSpeed is available:
`Found item [ifHighSpeed='10'] index: 1 [from value]`
`Found item [ifHighSpeed='1000'] index: 2 [from value]`

rrdtool will create rrd with "U":
`/bin/rrdtool create \`
`/home/cacti/cacti-1.2.1/rra/1/83122.rrd \`
`--start -900 --step 300  \`
`DS:traffic_in:COUNTER:600:0:U \`
`DS:traffic_out:COUNTER:600:0:U \`
`RRA:AVERAGE:0.5:1:600 \`
`RRA:AVERAGE:0.5:6:700 \`
`RRA:AVERAGE:0.5:24:775 \`
`RRA:AVERAGE:0.5:288:797 \`
`RRA:MIN:0.5:1:600 \`
`RRA:MIN:0.5:6:700 \`
`RRA:MIN:0.5:24:775 \`
`RRA:MIN:0.5:288:797 \`
`RRA:MAX:0.5:1:600 \`
`RRA:MAX:0.5:6:700 \`
`RRA:MAX:0.5:24:775 \`
`RRA:MAX:0.5:288:797 \`
`RRA:LAST:0.5:1:600 \`
`RRA:LAST:0.5:6:700 \`
`RRA:LAST:0.5:24:775 \`
`RRA:LAST:0.5:288:797 \`

Suggested Value Config:
![rrd_max](https://user-images.githubusercontent.com/8223375/52049237-91c7a300-254d-11e9-8934-3a641c31db30.PNG)

**Comment by cigamit** [comment]
The only case this should fail is if the values for those two items came back empty.  Not likely unless there was some timeout issue.  Might take a few days to get to this.  In the mean time you should run the rrdtool tune command to fix the max values.

**Comment by cigamit** [comment]
Do me a favor, goto the rra folder, move one of the broken RRDfiles to a new name, let the poller re-create it and tell us if the value is saved properly.  Then, you can move the old file back and use the gap fill feature of spikekill to remove the gap.

**Comment by cigamit** [comment]
Just about to make a change that will allow a user to specify a default interface speed if ifSpeed or ifHighSpeed come back zero.  It'll be a system wide default.

**Comment by kruegerj** [comment]
i've updated my local lab cacti to actual fetch from github, i see the settings in Device Defaults Section so i test the creation of a new graph, but i think it doesn't work:
![image](https://user-images.githubusercontent.com/8223375/52200035-f6de0a00-2867-11e9-9524-41100f4323bb.png)
we see, the values are present, 2Gbps Eth Trunk Interface, but for RRD it's applied the default Value 1Gbps:
![image](https://user-images.githubusercontent.com/8223375/52200134-3147a700-2868-11e9-818a-1bb981e34b34.png)
do you need any additional informations?

**Comment by cigamit** [comment]
Nope, can not believe this was not caught before today honestly.  Thanks for reporting.

**Comment by cigamit** [comment]
Ok, reproduced, verified and resolved.

**Comment by cigamit** [comment]
If you remember, you removed the suggested Data Source Name 'rrd_maximum' with a value of '|query_ifSpeed|', but that back and it should start to work.  I've tested it locally and it works fine now.

**Comment by kruegerj** [comment]
no, nothing removed. look:
![image](https://user-images.githubusercontent.com/8223375/52278990-c0cc8300-2958-11e9-8b90-bb0c6a66c2a9.png)

**Comment by cigamit** [comment]
You only need the |query_ifSpeed|.

**Comment by cigamit** [comment]
I have confirmed a re-confirmed.  This issue is resolved.  Please wait for the update to 1.2.2.
