### ISSUE TITLE
Error while creating a graph?

### ISSUE THREAD

**Issue by beckblurry** [Cacti/cacti#2367]
02/02/2019 14:37:15 - CMDPHP PHP ERROR NOTICE Backtrace: (/graphs_new.php: 63 graphs)(/graphs_new.php: 1035 CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)
02/02/2019 14:49:51 - ERROR PHP NOTICE: Undefined index: host_template_id in file: /usr/share/cacti/graphs_new.php  on line: 1035
02/02/2019 14:49:51 - CMDPHP PHP ERROR NOTICE Backtrace: (/graphs_new.php: 63 graphs)(/graphs_new.php: 1035 CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)
02/02/2019 14:50:13 - ERROR PHP NOTICE: Undefined index: host_template_id in file: /usr/share/cacti/graphs_new.php  on line: 1035
02/02/2019 14:50:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/graphs_new.php: 63 graphs)(/graphs_new.php: 1035 CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)

Cacti Version 1.1.38

**Comment by cigamit** [comment]
Okay, thanks for that.  This will be officially fixed in 1.2.2.
