### ISSUE TITLE
Could not get SNMP info when create device which has non printable characters in a OID string

### ISSUE THREAD

**Issue by zhouleon** [Cacti/cacti#2370]
My Chinese network manage device: Sangfor, has non printable characters in a OID .1.3.6.1.2.1.1.1.0 string.
When I create the device, Cacti could not get the SNMP info.

I debug it, and find root cause is lib\snmp.php
$string = preg_replace('/[^\PC\s]/u', '', $string);
this will remove all the string of .1.3.6.1.2.1.1.1.0, and return blank string. even it has a few non printable.

For now, I just replace it with:
$string = preg_replace('/[^[:print:]\r\n]/', '', $string);
which strip everything except basic printable ASCII characters.

https://stackoverflow.com/questions/1176904/php-how-to-remove-all-non-printable-characters-in-a-string

Please check if that is OK.
thanks.

**Comment by cigamit** [comment]
If you could, please test out the combination of lib/functions.php and lib/snmp.php in the develop branch and let us know if the string handling is working well now.
