### ISSUE TITLE
automation where clause issue.

### ISSUE THREAD

**Issue by jdcoats** [Cacti/cacti#2373]
`

2019/02/04 16:42:54 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'a.ifAlias' in 'where clause'
--
2019/02/04 16:42:43 - CMDPHP SQL Backtrace:   (/cli/poller_reindex_hosts.php[141]:run_data_query(),  /lib/data_query.php[335]:automation_execute_data_query(),  /lib/api_automation.php[2148]:create_dq_graphs(),  /lib/api_automation.php[2406]:db_fetch_assoc(),  /lib/database.php[449]:db_fetch_assoc_prepared(),  /lib/database.php[463]:db_execute_prepared())

2019/02/04 16:43:34 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'a.ifAlias' in 'where clause' 

`

**Comment by cigamit** [comment]
You know I've seen this recently too, but blew it off.  It must happen if the interface does not contain any ifAlias'.  I'll have to check it out.  You might want to look at issue #2372.  It also impacts you.

**Comment by jdcoats** [comment]
I only noticed it if the automation graph rule contained alias. The rule works as far as I can tell.

Dan Coats
IT/Network VoIP Engineer
Tallahassee Memorial Healthcare
Office 850-431-7014
Cell 850-567-2201
dan.coats@tmh.org<mailto:dan.coats@tmh.org>

*CONFIDENTIALITY NOTICE* The information contained in this email message is intended only for the personal and confidential use of the designated recipient(s) named above. This message may be an attorney/client or physician/patient communication, and as such, is privileged and confidential. If the reader of this message is not the intended recipient, you are hereby notified that you have received this document in error, and that any review, dissemination, distribution, or copying of this message is strictly prohibited. If you have received this email communication in error, please notify me immediately by telephone.

**Comment by cigamit** [comment]
Should be fixed now.
