### ISSUE TITLE
lib/database.php: is_file and open_basedir

### ISSUE THREAD

**Issue by crequill** [Cacti/cacti#2374]
Hello,

On line 82 of lib/dabase.php there is:
```
if (is_file($device) && filetype($device) == 'socket') {
```
Use is_file to test device is a problem. In my case there is localhost in $device. With this an error occured:

PHP Warning:  filetype(): open_basedir restriction in effect. File(localhost) is not within the allowed path(s) (...) in /usr/share/webapps/cacti/lib/database.php on line 82.

I propose to use !empty($device) as test to resolve it:
```
if (!empty($device) && filetype($device) == 'socket') {
```

**Comment by cigamit** [comment]
I resolved this just a little bit differently.  Please test out the solution.

**Comment by crequill** [comment]
OK for me. Thanks.
