### ISSUE TITLE
Error when adding a device discovered by Automation manually

### ISSUE THREAD

**Issue by hmorandell** [Cacti/cacti#2376]
Hi,
when I try to add a device manually discovered by Automation, I get the following error in the logfile:

```
2019/02/06 09:27:19 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
2019/02/06 09:27:19 - ERROR PHP ERROR: Uncaught Error: Call to undefined function create_complete_graph_from_template() in /var/www/html/lib/api_automation.php:2445 Stack trace: #0 /var/www/html/lib/api_automation.php(2148): create_dq_graphs('11727', '1', Array) #1 /var/www/html/lib/data_query.php(335): automation_execute_data_query('11727', '1') #2 /var/www/html/lib/api_device.php(861): run_data_query('11727', '1') #3 /var/www/html/lib/api_device.php(779): api_device_update_host_template('11727', 5) #4 /var/www/html/lib/api_automation.php(2803): api_device_save('0', 5, 'NOME_DEVICE_...', 'XX.XX.XX.XX', 'COMMUNITY', '2', '', '', '161', '3000', '', 1, '1', '23', '3000', '2', 'Added manually ...', 'MD5', '', '[None]', '', '', 10, 1, 1, '0') #5 /var/www/html/automation_devices.php(103): automation_add_device(Array, true) #6 /var/www/html/automation_devices.php(60): form_actions() #7 {main} thrown in file: /var/www/html/lib/api_automation.php on line: 2445
```

The device is added anyway, but I have then to create the graphs manually (it seems that the graph rules won't get applied).
Any idea whats wrong and why this error is triggered?

**Comment by netniV** [comment]
What version of Cacti are you using and from which source?

**Comment by hmorandell** [comment]
Hi,
sorry - Version 1.2.1 from official release

**Comment by cigamit** [comment]
Describe how your 'manually' run automation.

**Comment by hmorandell** [comment]
Hi. I make a discovery of a subnet but have "Automatically add to Cacti" not selected (for a few reasons)
Some of the discovered devices I add them by selecting them and by choosing "Add Device" from the dropdown menu. Then I get a new screen, click then save and that where the error is triggered,
Tomorrow I can attach some screenshots as I have a new discovery running right now.

**Comment by cigamit** [comment]
Well, that's odd.  Thought that had been fixed.

**Comment by cigamit** [comment]
Resolved now.

**Comment by hmorandell** [comment]
Hi, I changed the file automation_devices.php with the one from the repository, now another error ist thrown in the log file and the device is not even added:

``
2019/02/08 10:31:14 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
2019/02/08 10:31:14 - ERROR PHP ERROR: Uncaught Error: Call to undefined function api_device_save() in /var/www/html/lib/api_automation.php:2798 Stack trace: #0 /var/www/html/automation_devices.php(113): automation_add_device(Array, true) #1 /var/www/html/automation_devices.php(70): form_actions() #2 {main} thrown in file: /var/www/html/lib/api_automation.php on line: 2798
``

**Comment by cigamit** [comment]
Try again.  Was being sloppy.

**Comment by hmorandell** [comment]
everything working now! great, thanks!
