### ISSUE TITLE
Cacti Interface Operation Status

### ISSUE THREAD

**Issue by jdcoats** [Cacti/cacti#2379]
Cacti should contain interface operational status DS and graph template by default

**Comment by cigamit** [comment]
@jdcoats, can you be more specific?

**Comment by jdcoats** [comment]
I’ve had a really old installation (over 10 years) and decided with all the errors and issues lately since upgrade to 1.x I decided to start over from scratch. I’m making progress through rebuilding (with lots of table exports) but when the time comes to create thresholds for interfaces there is no native interface operation status available in snmp interface statistics on a new install. I guess I need to install it myself like I did back 10 years ago or so. It seems to me that after 10+ years that there would be more default DS and graph templates made default after install. Especially after the big jump from 0.x to 1.x. There have been so many contributions over the years, it just seems logical that some of these would make it into the native install. Sharing the contributions and making the system more full featured out of the box.



——
Dan

**Comment by jdcoats** [comment]
The interface operational status was a really basic example. But so
May contributions have been made. Netscaler stats, Cisco ASA,  APC UPS, Cisco Wireless Conteoller, and more. It’s just a suggestion to make them part of the native install. When you google cacti templates it produces the current 1.0 official templates but most of the contributions over the years are not for the 1.x version yet. This is/could be causing enormous post upgrade issues.


——
Dan

On February 6, 2019 at 10:27:51 PM EST, Coats, Dan <Dan.Coats@tmh.org> wrote:
I’ve had a really old installation (over 10 years) and decided with all the errors and issues lately since upgrade to 1.x I decided to start over from scratch. I’m making progress through rebuilding (with lots of table exports) but when the time comes to create thresholds for interfaces there is no native interface operation status available in snmp interface statistics on a new install. I guess I need to install it myself like I did back 10 years ago or so. It seems to me that after 10+ years that there would be more default DS and graph templates made default after install. Especially after the big jump from 0.x to 1.x. There have been so many contributions over the years, it just seems logical that some of these would make it into the native install. Sharing the contributions and making the system more full featured out of the box.



——
Dan

**Comment by pautiina** [comment]
@cigamit I think he mean about this https://forums.cacti.net/about17722.html

**Comment by cigamit** [comment]
Understood guys, but we need some help here.  Between Mark and myself, we are only two people.  What I would suggest is that the two of you team up and start creating pull requests with what you think are well structured Device/Host Templates.  Place the Template XML files into a 'templates' sub-directory of the install, and any scripts and resource XML in their designated directories.

Then, Mark or I can merge them and subsequently create package scripts after we have audited your work.  We really need this help as we don't have access to the same equipment that you guys do.

I really hope you take us up on this offer.

**Comment by cigamit** [comment]
More specifically &lt;path_cacti&gt;/install/templates

**Comment by cigamit** [comment]
We are hoping at some point to release our packaging plugin.  Again, there is only so much time in a day, and we are only a small but agile team.

**Comment by cigamit** [comment]
If you would like to take this on.  Create an Issue for each Device Template that needs to be migrated.  This is your wish list, and then assign them to the same projects as this ticket has been assigned.  After that, you know what to do.

**Comment by jdcoats** [comment]
Ive been trying but don't do xml well. I'm having a hard time with it for sure.

**Comment by cigamit** [comment]
The right way to do this is import the one you want first, then import the default again choosing to prune.  We will have a feature out soon that will allow you to select the specific templates to import.  Either way, there should be no hand editing of the XML if you follow the steps above.  Yea, it's a pain, and that is why it is going to change.

**Comment by jdcoats** [comment]
That was definitely easier than what I was attempting. Here it is.
[InterfaceStatus.zip](https://github.com/Cacti/cacti/files/2848017/InterfaceStatus.zip)

**Comment by cigamit** [comment]
Can you do it in a pull request?

**Comment by tyit** [comment]
@jdcoats 
It's interesting
Can you do it in a pull request?

**Comment by xmacan** [comment]
I would like to help with this. I was thinking about this earlier.

Is there any list of requested templates or shall I choose?

**Comment by xmacan** [comment]
Is here any progress? I would like to add few device templates (aruba, esxi,  ...) to cacti installation. Cacti is great but a lot of useful templates is missing after fresh installation.

**Comment by TheWitness** [comment]
@xmacan, we are working on a few things that you will be very happy with.  Please give us just a little more time to work though things.

**Comment by KnoAll** [comment]
I too am hoping for an aruba ap template

**Comment by xmacan** [comment]
@KnoAll  - I created template for Aruba instant cluster and for Aruba controller too. Which version you need? It is first version, I need betatesters :-)

**Comment by KnoAll** [comment]
I would be happy to test. I only have the Instant Cluster

**Comment by xmacan** [comment]
[cacti_host_template_aruba_instant_cluster.zip](https://github.com/Cacti/cacti/files/4824049/cacti_host_template_aruba_instant_cluster.zip)

**Comment by KnoAll** [comment]
The zip appears to be missing the data query. aruba_instant_ap_stats.xml

**Comment by xmacan** [comment]
[resource.zip](https://github.com/Cacti/cacti/files/4827287/resource.zip)

**Comment by KnoAll** [comment]
OK, getting some graph stats now.

Question, Should this only need to be pulled from a single device for an entire site? It will grab stats on all items for all APs?

**Comment by xmacan** [comment]
Right way is query Virtual controller AP. I haven't tested query any AP. Virtual controller AP gives me information about all APs in cluster. If you have any question, please write me to pm@kostax.cz. This issue is for different thing.

**Comment by cafetera** [comment]
I know this is an old thread, but I installed this today and it is missing the scripts ss_aruba_instant_ap.php and 'ss_aruba_instant_ap.php

**Comment by xmacan** [comment]
[aruba.zip](https://github.com/Cacti/cacti/files/6735759/aruba.zip)

Try these files

**Comment by cafetera** [comment]
Thank you, I will try them
Luis
    On Tuesday, June 29, 2021, 03:01:53 p.m. EDT, Petr Macek ***@***.***> wrote:  
 
 


aruba.zip

Try these files

**Comment by TheWitness** [comment]
This one is mostly done now, but I have to repackage everything before release.

**Comment by TheWitness** [comment]
Closing this one now.
