### ISSUE TITLE
Cacti 1.2.2 cannot parse CF error

### ISSUE THREAD

**Issue by rtripon** [Cacti/cacti#2381]
Hello, I'm having some small issues with a few graphs. I have hosts for wich some graphs shows : cannot parse CF.
Cacti 1.2.2
Spine 1.2.1

RRDtool Command:

/bin/rrdtool graph - \
--imgformat=PNG \
--start='-86400' \
--end='-300' \
--pango-markup  \
--title='sw1-Gi1 - Traffic - Defect' \
--vertical-label='bits per second' \
--slope-mode \
--base=1000 \
--height=200 \
--width=700 \
--rigid \
--alt-autoscale-max \
--lower-limit='0' \
COMMENT:"From 2019/02/06 15\:59\:56 To 2019/02/07 15\:54\:56\c" \
COMMENT:"  \n" \
--color BACK#F3F3F3 \
--color CANVAS#FDFDFD \
--color SHADEA#CBCBCB \
--color SHADEB#999999 \
--color FONT#000000 \
--color AXIS#2C4D43 \
--color ARROW#2C4D43 \
--color FRAME#2C4D43 \
--border 1 --font TITLE:11:'Arial' \
--font AXIS:8:'Arial' \
--font LEGEND:8:'Courier' \
--font UNIT:8:'Arial' \
--font WATERMARK:6:'Arial' \
--slope-mode \
--watermark 'Generated by Cacti®' \
DEF:a='/var/www/html/cacti/rra/sw1-gi1_traffic_in_163.rrd':'traffic_in': \
DEF:b='/var/www/html/cacti/rra/sw1-gi1_traffic_in_163.rrd':'traffic_out': \
CDEF:cdefa='a,8,*' \
CDEF:cdeff='b,8,*' \
LINE1:cdefa#00CF00FF:  \
AREA:cdefa#00CF007F:'Inbound '  \
GPRINT:cdefa:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefa:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdefa:MAX:'Maximum\:%8.2lf %s\n'  \
LINE1:cdeff#002A97FF:  \
AREA:cdeff#002A977F:'Outbound'  \
GPRINT:cdeff:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdeff:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdeff:MAX:'Maximum\:%8.2lf %s\n' 

RRDtool Says:
ERROR: Cannot parse CF in 'DEF:a=/var/www/html/cacti/rra/sw1-gi1_traffic_in_163.rrd:traffic_in:'

Another host:

RRDtool Command:

/bin/rrdtool graph - \
--imgformat=PNG \
--start='-86400' \
--end='-300' \
--pango-markup  \
--title='TENSIUNE_BALON2 - Traffic - 127.0.0.1 (lo)' \
--vertical-label='bits per second' \
--slope-mode \
--base=1000 \
--height=200 \
--width=700 \
--rigid \
--alt-autoscale-max \
--lower-limit='0' \
COMMENT:"From 2019/02/06 16\:06\:37 To 2019/02/07 16\:01\:37\c" \
COMMENT:"  \n" \
--color BACK#F3F3F3 \
--color CANVAS#FDFDFD \
--color SHADEA#CBCBCB \
--color SHADEB#999999 \
--color FONT#000000 \
--color AXIS#2C4D43 \
--color ARROW#2C4D43 \
--color FRAME#2C4D43 \
--border 1 --font TITLE:11:'Arial' \
--font AXIS:8:'Arial' \
--font LEGEND:8:'Courier' \
--font UNIT:8:'Arial' \
--font WATERMARK:6:'Arial' \
--slope-mode \
--watermark 'Generated by Cacti®' \
DEF:a='/var/www/html/cacti/rra/tensiune_balon2_traffic_in_181.rrd':'traffic_in': \
DEF:b='/var/www/html/cacti/rra/tensiune_balon2_traffic_in_181.rrd':'traffic_out': \
CDEF:cdefa='a,8,*' \
CDEF:cdeff='b,8,*' \
LINE1:cdefa#00CF00FF:  \
AREA:cdefa#00CF007F:'Inbound '  \
GPRINT:cdefa:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefa:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdefa:MAX:'Maximum\:%8.2lf %s\n'  \
LINE1:cdeff#002A97FF:  \
AREA:cdeff#002A977F:'Outbound'  \
GPRINT:cdeff:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdeff:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdeff:MAX:'Maximum\:%8.2lf %s\n' 

RRDtool Says:
ERROR: Cannot parse CF in 'DEF:a=/var/www/html/cacti/rra/tensiune_balon2_traffic_in_181.rrd:traffic_in:'

Meanwhile in logs I have this errors:

2019/02/07 16:07:01 - POLLER: Poller[Main Poller] WARNING: Poller Output Table not Empty. Issues: 1, DS[ro-ar01a-sw1-Gi1 - Traffic] Graphs[sw1-Gi1 - Traffic - Defect] 

I tried deleting the host, creating new graphs, rebuild poller cache.
Also I've notice that rra's arent created for those interfaces.

**Comment by oshiewan** [comment]
Check your graph template, as it doesn't seem to have a Consolidation Function selected.
In the rrdtool output the CF is missing:
DEF:a='/var/www/html/cacti/rra/sw1-gi1_traffic_in_163.rrd':'traffic_in':**<CF-MISSING-HERE>**
DEF:b='/var/www/html/cacti/rra/sw1-gi1_traffic_in_163.rrd':'traffic_out':**<CF-MISSING-HERE>**

**Comment by rtripon** [comment]
For one host I used GENERIC SNMP ENABLE template, for other I used Cisco Router, both installed with Cacti 1.2.2. I see the CF is missing for those graphs, but why only for those graps?. Both hosts have other graphs wich are working properly.

**Comment by rtripon** [comment]
Also, randomly I keep getting errors for Poller Output. Not everytime is the same graph.

2019/02/07 19:32:01 - POLLER: Poller[Main Poller] WARNING: Poller Output Table not Empty. Issues: 1, DS[ro-ar01a-sw1-Gi1 - Traffic] Graphssw1-Gi1 - Traffic - Backup-to-N]

**Comment by cigamit** [comment]
We had some issues in the 1.2.1 release that have people have been running into, but your problem looks more severe than that.  The fact that you are missing the consoldation functions and your cdefs are damaged leads me to believe these is more to your issue.  Please upload your Cacti log, and then export the Generic OID Graph Template and post here as well.

In fact, if this is a new install, I would strongly suggest you just grab develop and re-install from there.

**Comment by rtripon** [comment]
Hello,
I've reinstalled everything from scratch. Its ok now, no poller output not empty errors.
Before this I had 1.2.1 from git, and was pull'ing everytime for updates(this is how I got to 1.2.2). Maybe something went wrong in the process. This can be closed.

**Comment by cigamit** [comment]
Good to know.  We are trying to make the UI as bug proof as possible.  Once we have that done, we will start moving on to the 100 or so open feature requests.  Hoping 1.2.2 will be that release.
