### ISSUE TITLE
Cacti-1.2.1 Graphs and Sync to Device Template

### ISSUE THREAD

**Issue by Cramin** [Cacti/cacti#2382]
Hi again.
I have problem in my graphs and devices.
Problem in steps:
1. I create device, set device template and click Save.
2. Device added to Cacti with two graphs from device template and SNMP - Interface Statistics Data Query.
I have graph rules in Automation that create graphs for device with specific SNMP Decryption.
3. In device settings i click Reload Query and the graphs are created.
If i change device template, there are new graphs created. And i have in cacti log a lot of Warnings and Errors like this:

```
2019/02/07 20:02:11 - SPINE: Poller[Main] WARNING: Invalid Response, Device[test.mikrotik] HT[1] DS[test.mikrotik - Errors - \|query_ifIndex\| - \|query_ifAlias\|] Graphs[test.mikrotik - Errors - 1 - Klient] SNMP: v2: 172.21.206.147, dsname: errors_out, oid: .1.3.6.1.2.1.2.2.1.20**.ether1**, value: U
2019/02/07 20:02:11 - SPINE: Poller[Main] WARNING: Invalid Response, Device[test.mikrotik] HT[1] DS[test.mikrotik - Errors - \|query_ifIndex\| - \|query_ifAlias\|] Graphs[test.mikrotik - Errors - 1 - Klient] SNMP: v2: 172.21.206.147, dsname: errors_in, oid: .1.3.6.1.2.1.2.2.1.14**.ether1**, value: U
2019/02/07 20:02:11 - SPINE: Poller[Main] Device[test.mikrotik] ERROR: Problems parsing Multi SNMP OID! (oid: .1.3.6.1.2.1.2.2.1.18**.wlan1**), Set MAX_OIDS to 1 for this host to isolate bad OID
2019/02/07 20:02:11 - SPINE: Poller[Main] Device[test.mikrotik] ERROR: Problems parsing Multi SNMP OID! (oid: .1.3.6.1.2.1.2.2.1.12**.wlan1**), Set MAX_OIDS to 1 for this host to isolate bad OID
```
Every time i change device template new graphs are created.

**Comment by cigamit** [comment]
I suggest you update lib/data_query.php, lib/template.php and lib/functions.php from develop, and then re-index your devices.  We experienced a fairly significant bug in the 1.2.x release that has recently been resolved.  Close after re-indexing the devices if this issue has been correct.  We hope to have a 1.2.2 out shortly to address this and a few additional issues.

**Comment by Cramin** [comment]
That resolve the problem with duplicated graphs end errors. Thank You.
I'm start fighting with `Old Sort:, New Sort:ifName. Re-mapping issues may occur!`

**Comment by cigamit** [comment]
Yea, that is a new message introduced in 1.2.0 that captures sort field changes.  It's not an issue per se.  It should rarely happen, and only at Re-Index time.  Since you were Re-Indexing, and fixing everything that was buggered up by the 1.2 upgrade, you will see that message.  But after everything is Re-Indexed, it should be rare if at all happening.
