### ISSUE TITLE
If current authentication method is set to None, change to Builtin

### ISSUE THREAD

**Issue by cigamit** [Cacti/cacti#2384]
A user recently reported that they were having issues locking and unlocking trees.  They had inadvertently set authentication to none.  The upgrade was allowed, but the authentication was was not changed to 'builtin' after the upgrade was complete.

This cause an issue that should not have happened.

We should:
1) Issue a WARNING that authentication will be changed to Builtin
2) If this warning was set, after the upgrade is complete, redirect them to the logout after they press the 'Get Started' button.

**Comment by netniV** [comment]
To achieve this, the code will look for a valid administration user that will be used to reset the password.  This is achieved by searching for the Primary Admin, and then any admin with console access.  Once an admin has been found, the must_change_password and change_password flags are set, the password is cleared and the user is automatically logged in before being forced to change the empty password.

If no admin can be located, the script will die to prevent issues and allow manual fixing of the problem.  The simpliest way to do this would be to utilise the INSERT statement that is used for the 'admin' user in the cacti.sql's user_auth table, plus the INSERT for user_id 1 into the user_auth_realm table.
