### ISSUE TITLE
cacti 1.2.0 nectar reports

### ISSUE THREAD

**Issue by chathurag** [Cacti/cacti#2386]
Unable to add graphs to existing nectar reports in cacti-1.2.0

**Comment by cigamit** [comment]
Please be more specific as to how you are adding graphs to the report as there are multiple methods to do this.  Also, what errors are in the Cacti log.  Lastly describe the behavior of the user interface that leads to this blocking condition.

**Comment by netniV** [comment]
If you are using 1.2.0 you need to update as there were fixes to the nectar reports so it would be useful to know if your problem has actually been already resolved.

**Comment by cigamit** [comment]
That's correct.  This will be resolved in the 1.2.2 release.  You can pull develop in the mean time.  We don't expect much to change between now and release.
