### ISSUE TITLE
Graph are blank

### ISSUE THREAD

**Issue by moth1995** [Cacti/cacti#2387]
Hi! im having some touble and i still cant find any solution to this, my graph were working until yesterday, 

CACTI  Version 1.1.38 

1- SNMP works to all hosts
![imagen](https://user-images.githubusercontent.com/36039932/52522983-e44e4100-2c6a-11e9-834e-6b1b1f5e8b4c.png)

(Also i did snmpwalk to all hosts and they print something)
2- Main poller status is idle
![imagen](https://user-images.githubusercontent.com/36039932/52522974-d00a4400-2c6a-11e9-92d1-43a1bf89d6d1.png)

3-  RRDtool Says: OK

![imagen](https://user-images.githubusercontent.com/36039932/52522941-7efa5000-2c6a-11e9-8874-affc0b170a76.png)

4- Under data profile they are working
![imagen](https://user-images.githubusercontent.com/36039932/52522966-bf59ce00-2c6a-11e9-8c6e-40ed88ac52d9.png)

But my graphs still like this

![imagen](https://user-images.githubusercontent.com/36039932/52522991-0647c380-2c6b-11e9-8d44-e2807a21fcd4.png)

All of them, i'm missing something??

**Comment by cigamit** [comment]
What version?

**Comment by moth1995** [comment]
Hi, im using  Version 1.1.38

**Comment by moth1995** [comment]
This problem started yesterday around 15:10 ~ 15:20 i take a look at the clog and got this

![imagen](https://user-images.githubusercontent.com/36039932/52523171-32644400-2c6d-11e9-8061-e065ab6877cc.png)

![imagen](https://user-images.githubusercontent.com/36039932/52523188-62134c00-2c6d-11e9-887f-d6ed267db671.png)

**Comment by cigamit** [comment]
You upgraded yourself to php7 which is not compatible with Cacti 1.1.38.  Please update to the development version ASAP to resolve this issue.

**Comment by moth1995** [comment]
THANKS!!! it took me the afternoon but i got it working!!
