### ISSUE TITLE
Boost backtrace 

### ISSUE THREAD

**Issue by jdcoats** [Cacti/cacti#2389]
Just sync'd up and now I get this every polling cycle.

>2019/02/09  14:09:15 - CMDPHP SQL Backtrace:   (/poller_boost.php[132]:boost_get_total_rows(),  /lib/boost.php[51]:db_fetch_cell(),  /lib/database.php[360]:db_fetch_cell_prepared(),  /lib/database.php[376]:db_execute_prepared())
--
2019/02/09 14:09:15 - CMDPHP ERROR: A DB Cell Failed!, Error: You  have an error in your SQL syntax; check the manual that corresponds to  your MariaDB server version for the right syntax to use near '' at line 1

**Comment by netniV** [comment]
Ah should now be resolved.
