### ISSUE TITLE
[1.2.2 Develop] Index Type for Data Query Data Source is no longer a drop-down

### ISSUE THREAD

**Issue by jayslovak** [Cacti/cacti#2390]
Hello,

While testing 1.2.2 from Develop, I have noticed Index Type for Data Query Data Source is no longer a drop-down, but now it is a text field:

![image](https://user-images.githubusercontent.com/10856567/52527724-b0583780-2ccd-11e9-8393-2f11fc01224c.png)

Was there a reason for this change? I think a drop-down is more suitable for this field, like it was in 1.2.1 before:

![image](https://user-images.githubusercontent.com/10856567/52527770-4ee49880-2cce-11e9-8e14-a599e854c9b0.png)

Thanks

**Comment by jayslovak** [comment]
Output Type ID field should also be a dropdown...

**Comment by netniV** [comment]
According to the above screen it is

**Comment by cigamit** [comment]
The dropdowns are back.  I have no idea how that happened.

**Comment by jayslovak** [comment]
Thank you, this has fixed the issue.

**Comment by netniV** [comment]
Oh I see it now, I missed that at first glance.
