### ISSUE TITLE
When reindexing a device, Graph Automation creates duplicate graphs every time

### ISSUE THREAD

**Issue by vishnubraj** [Cacti/cacti#2393]
**Describe the bug**
Whenever i run the reindex script cacti automation rule create duplicate graphs... If i disable the rule it doesnt happen.  Can you please check this. 

![screenshot 2019-02-11 at 3 59 59 pm](https://user-images.githubusercontent.com/11851188/52557801-89594d00-2e16-11e9-8185-47576495bf9f.png)

**Comment by hmorandell** [comment]
Hi,
I have a similar issue, but only with certain data query types. It seems not to happen with "SNMP - Interface Statistics", but it happens with a couple of my own created data query types
Maybe an error in my templates? Had not yet the time to check it, but it is somehow good to know that I'm not the only one to have such issues...

**Comment by cigamit** [comment]
We need much more information, the rule screen shot would be a good start.

**Comment by vishnubraj** [comment]
Please find the rule screen shot

![screenshot 2019-02-20 at 5 17 40 pm](https://user-images.githubusercontent.com/11851188/53089808-94595f00-3533-11e9-8351-e2e225013786.png)
![screenshot 2019-02-20 at 5 18 20 pm](https://user-images.githubusercontent.com/11851188/53089818-9ae7d680-3533-11e9-9a8b-44e1e2e8d7f0.png)

**Comment by cigamit** [comment]
Well, that rule is so strait forward.  No reason it should not be working.

**Comment by cigamit** [comment]
Can you edit the data sources for each of those graphs and see if there is anything funny with the indexes?

**Comment by vishnubraj** [comment]
Actually i dont see a data source created for this graph.. At the same time for some other graphs for the same template the data source created.. In Automation rules matching objects it still shows the graph has to be created.. 

<img width="735" alt="screenshot 2019-02-21 at 5 50 39 pm" src="https://user-images.githubusercontent.com/11851188/53168777-765a3000-3601-11e9-9b00-20285ac17d15.png">
<img width="1110" alt="screenshot 2019-02-21 at 5 49 17 pm" src="https://user-images.githubusercontent.com/11851188/53168778-76f2c680-3601-11e9-858b-a30559a22fa8.png">

**Comment by ian351c** [comment]
I am seeing the same thing as @vishnubraj in the built-in rule "Traffic 64 bit Server". I also have seen multiple graphs created for the interfaces on the items listed in the "matching objects" list. The duplicate graphs all refer to the same data sources for each device. (So multiple graphs for "eth0" on "Device A" all refer to the same RRD file when I look at the graphs in debug mode).

I'm not sure if this is definitive, but the devices where I'm seeing multiple graphs are devices that I added new data queries/data sources/graphs to AFTER adding the graphs for the interfaces (using 64 bit counters).

**Comment by cigamit** [comment]
The duplication of the Data Sources should not happen.  That is the expected behavior.  However, we need to see what is going on with the creation of the second graph.

**Comment by cigamit** [comment]
This is resolved now.  Code was not re-written to handle the fact that Data Sources are no longer duplicated.  It was looking at the Data Source and not the graph, so automation broke.
