### ISSUE TITLE
getHostsByDescription() uses wrong field for indexed join

### ISSUE THREAD

**Issue by oshiewan** [Cacti/cacti#2394]
In api_automation_tools.php function getHostsByDescription
The SQL statement has a typo 

SELECT h.id, h.description 
		FROM host AS h
		INNER JOIN host_template AS ht
		ON h.host_template_id = **h.id**
		$sql_where
		ORDER BY h.description
		
should be 
SELECT h.id, h.description 
		FROM host AS h
		INNER JOIN host_template AS ht
		ON h.host_template_id = **ht.id**
		$sql_where
		ORDER BY h.description

**Comment by netniV** [comment]
This has now been committed to the development code.
