### ISSUE TITLE
CDEF Percent calculation for 10Gbps interface

### ISSUE THREAD

**Issue by vishnubraj** [Cacti/cacti#2395]
Can someone give me the CDEF example for the 10G interface..
i am using the below formula and i am not getting the proper output. Please check..

![screenshot 2019-02-11 at 4 38 50 pm](https://user-images.githubusercontent.com/11851188/52560050-1d2e1780-2e1d-11e9-9e23-190e78b2df10.png)

**Comment by netniV** [comment]
Have you tested your formula using an RPN calculator?  I haven't investigated the values you would have, but I do recall that ifHighSpeed is not in a raw value so I think you are correct to multiply it but without further evidence, or work on my part, I can't really say whether you are right or wrong at this moment in time with the overall formula.

**Comment by vishnubraj** [comment]
Yes @netniV  i test the formula using RPN calculator.. 
for example.
consider i have a 10Gbps interface with 200Mbps traffic..
i.e:
CDEF=CURRENT_DATA_SOURCE,8,100,*,*,|query_ifHighSpeed|,1000000,*,/
CURRENT_DATA_SOURCE = 25000000(Byte value of 200Mbps)
query_ifHighSpeed = 10000
25000000,8,100,*,*,10000,*,/ = 2
i am getting the above value 2 correctly by using the RPN calculator..
I am using this CDEF in Cacti thold plugin for interface alert when the traffic goes beyond 75%, but i am always getting alert from cacti saying the interface reached beyond the threshold. One thing i suspect is that this CDEF function is not used by any graph. Does that matter for using the CDEF in thold plugin?

![screenshot 2019-02-12 at 5 46 54 pm](https://user-images.githubusercontent.com/11851188/52634864-52566a80-2eee-11e9-8a3a-5716c9ee4699.png)

Please let me know if i am making anything wrong..

**Comment by netniV** [comment]
Threshold works against a data source not a specific graph.

**Comment by netniV** [comment]
what is your threshold definition set to?

**Comment by vishnubraj** [comment]
Threshold is set to High/Low value.. 75 is the threshold value..
<img width="872" alt="screenshot 2019-02-12 at 7 55 06 pm" src="https://user-images.githubusercontent.com/11851188/52642047-3bb90f00-2f00-11e9-91fd-36d532c63569.png">

**Comment by netniV** [comment]
From your picture, your alert threshold is lower than your warning, so I'd imagine you may not hit a warning.  Otherwise, it looks OK.  What does the threshold value show you when you view it in the listing?

**Comment by vishnubraj** [comment]
<img width="1436" alt="screenshot 2019-02-12 at 8 09 48 pm" src="https://user-images.githubusercontent.com/11851188/52643048-3361d380-2f02-11e9-9792-c2c37dd7acdb.png">

Above is the alert i am seeing..

**Comment by netniV** [comment]
Given the following:
```
CDEF=CURRENT_DATA_SOURCE,8,100,*,*,|query_ifHighSpeed|,1000000,*,/
CURRENT_DATA_SOURCE = 122002.8(value from your threshold)
query_ifHighSpeed = 10000
```

```
Step 1:        8 x 100        = 800
Step 2: 122002.8 x 800        = 97602240
Step 3:     1000 x 1000000    = 1000000000
Step 4: 97602240 / 1000000000 = 0.098 (rounded to 3 dp)
```
Which would appear to be well below the threshold.  What values do you have against the actual data source?

**Comment by oshiewan** [comment]
I use the RPN expression directly in the threshold template as below but it's essentially the same as the CDEF, replacing CURRENT_DATA_SOURCE with |ds:traffic_in| and it works fine.

|ds:traffic_in|,|query_ifHighSpeed|,/,0.0008,*

**Comment by vishnubraj** [comment]
@netniV  sorry i didnt understand the question. But if you asking about the actual traffic.. then below is  the graph..

<img width="1436" alt="screenshot 2019-02-12 at 8 09 48 pm" src="https://user-images.githubusercontent.com/11851188/52645627-25fb1800-2f07-11e9-9916-51a1c833eedd.png">

**Comment by vishnubraj** [comment]
Just an update.. the same formula works fine with interfaces with less than 1Gbps traffic.. When the traffic reaches above 1Gbps the Thold plugin is misbehaving and showing the wrong values..
Please find the below pic.. only the first 6 interfaces are having the traffic more than 1Gbps..  Please help fix this issue..

![screenshot 2019-02-18 at 7 25 33 pm](https://user-images.githubusercontent.com/11851188/52955598-0fdfd280-33b3-11e9-98d5-d230fd616a5a.png)

**Comment by vishnubraj** [comment]
I just enabled the thold debug log and found below errors.. Please see if this is relavant..

```

2019/02/18 14:07:08 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php[656]:process_poller_output(), /lib/poller.php[532]:api_plugin_hook_function(), /lib/plugins.php[114]:api_plugin_run_plugin_hook_function(), /lib/plugins.php[221]:thold_poller_output(), /plugins/thold/includes/polling.php[347]:thold_get_currentval(), /plugins/thold/thold_functions.php[629]:CactiErrorHandler())
--
2019/02/18 14:07:08 - ERROR PHP WARNING in Plugin 'thold': A non-numeric value encountered in file: /var/www/cacti/plugins/thold/thold_functions.php on line: 629
2019/02/18 14:07:08 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php[656]:process_poller_output(), /lib/poller.php[532]:api_plugin_hook_function(), /lib/plugins.php[114]:api_plugin_run_plugin_hook_function(), /lib/plugins.php[221]:thold_poller_output(), /plugins/thold/includes/polling.php[347]:thold_get_currentval(), /plugins/thold/thold_functions.php[629]:CactiErrorHandler())
2019/02/18 14:07:08 - ERROR PHP WARNING in Plugin 'thold': A non-numeric value encountered in file: /var/www/cacti/plugins/thold/thold_functions.php on line: 629
```

**Comment by oshiewan** [comment]
I would guess your formula is going above a variable size limit as you are doing lots of multiplying first, if you used the simpler formula I posted above I think you will have more success.
CDEF=CURRENT_DATA_SOURCE,|query_ifHighSpeed|,/,0.0008,*

**Comment by vishnubraj** [comment]
hi @oshiewan  i modified the CDEF formula to "CURRENT_DATA_SOURCE,|query_ifHighSpeed|,/,0.0008,*" but still the current value remains same.  Looks like this is a bug..

**Comment by cigamit** [comment]
Please open this ticket in the plugin_thold issue tracker.  Closing here.

**Comment by netniV** [comment]
It was already created there so no need to create a new one.  It also appaars to be resolved there too.
