### ISSUE TITLE
Enhancement: Ability to duplicate site settings and/or provide default template settings for sites

### ISSUE THREAD

**Issue by jdcoats** [Cacti/cacti#2400]
It would be nice to be able to configure site defaults in cacti settings. I'm rebuilding from scratch and having to create 50+ sites and enter the same City, State,Country,Timezone over and over is sort of redundant. I will just do it from the cli in the database for now but thought id mention it while i'm thinking about it.

**Comment by TheWitness** [comment]
Fixed

**Comment by netniV** [comment]
This is not a bug, it was an enhancement.
