### ISSUE TITLE
[1.2.1] PHP ERROR NOTICE Backtrace - /lib/snmpagent.php

### ISSUE THREAD

**Issue by DavidLiedke** [Cacti/cacti#2401]
**Describe the bug**
openSUSE 15.0
PHP 7.2.5
MariaDB 10.2.15

See the following error in die cacti.log with cacti version 1.2.1:

2019/02/12  08:23:54 - CMDPHP PHP ERROR NOTICE Backtrace:   (/poller.php[788]:snmpagent_poller_bottom(),  /lib/snmpagent.php[410]:CactiErrorHandler())

2019/02/12 08:23:54 - ERROR PHP NOTICE: Undefined index:  cactiStatsDeviceIndex in file: /srv/www/cacti/lib/snmpagent.php  on  line: 410

**Comment by DavidLiedke** [comment]
My cacti installation was very slow. I was unable to change anything. After that i want to change the debug level in the database.  The database was broken.

After restore a backup of the database the issue was fixed.

**Comment by netniV** [comment]
So this was a low level DB issue not a cacti issue?

**Comment by DavidLiedke** [comment]
I dont know. Maybe #2403
