### ISSUE TITLE
Interface configuration in multiple states in one graph

### ISSUE THREAD

**Issue by tyit** [Cacti/cacti#2402]
Interface configuration in multiple states in one graph, such as: CRC ERROR UP Down hwEntityOpticalRxPower Related examples?

Thank you

**Comment by netniV** [comment]
I'm not sure I follow what you are after or trying to describe?

**Comment by tyit** [comment]
Sorry, English is not good, it is not clear.

**Comment by netniV** [comment]
Try posting it in your native language, someone may be able to help translate it.
