### ISSUE TITLE
removing graphs in automation that no longer have titles in data source

### ISSUE THREAD

**Issue by maxstech** [Cacti/cacti#2406]
Hello team. 
I do not know. Consider it a problem or not. But I would like a solution. I have already addressed problem #2354 and it has been solved. 
But what about charts that no longer contain a description (ifalias). 
I think that after the next automation schedule they should be removed from the trees, as they no longer fall under the automation rules (see #2354)
But this is not happening.  I see an empty graph with the last "ifalias".
Is it possible to delete charts that no longer fall under automation rules ?
I understand that someone may need the old logs (for example, the old client)
But I would like to have a choice: delete charts that are no longer relevant or leave.  For example, to make such a button in the automation segment.

**Comment by netniV** [comment]
I don’t believe that we have an automation removal ruleset at the moment. You could potentially use the CLi to achieve that by getting a list of graphs and titles then removing those you desire

**Comment by maxstech** [comment]
Understood. It would be great if in the future there will be such functionality in cacti.
