### ISSUE TITLE
Device restrictions not working (Release 1.2.1)

### ISSUE THREAD

**Issue by DoubleBeast** [Cacti/cacti#2409]
i have been working with the tree - site grouping feature and notice that there is not a permitions setting for the site but beside that i also detect that the site bypass the other permitions, for example a user with restricted access to a device can access to that device througt the site.

**Comment by cigamit** [comment]
Can you edit the users permissions and see if the user has any effective access to the graphs for that device.  If that's the case, then the user will see the device.  Show a screen shot of Graphs from a specific Device (obfuscated) and the effective permissions.

**Comment by DoubleBeast** [comment]
i tested the perms and it seems to be a general problem with the permisions because i can see restricted devices even when they are out os the site, those are the captures.

Here is a restricted device for the specific user:
![perm](https://user-images.githubusercontent.com/37849594/53193282-0048cf80-35e7-11e9-951a-07d8dbccaa46.png)

and this are the graphs for that device using the restricted user:

with the device outside the site:
![tree](https://user-images.githubusercontent.com/37849594/53193395-3d14c680-35e7-11e9-8627-9979c4cb9a6e.png)

and with the device inside the site:
![site](https://user-images.githubusercontent.com/37849594/53193451-5f0e4900-35e7-11e9-80ec-2ae8bc915850.png)

so it appears that is not related with the sites, i test this behavior in 2 diferent cacti installments (both windows with cacti 1.2.1) i don't know if anyone can confirm this bug.

**Comment by cigamit** [comment]
Goto the users Graph Permissions page, and show us the 'Effective' permissions for those graphs.

**Comment by DoubleBeast** [comment]
![perm2](https://user-images.githubusercontent.com/37849594/53289490-e20cdc00-376c-11e9-9eec-667e09a318dd.png)

as aditional comment the same restriction configuration was working the last time i check (cacti 1.1.37)

**Comment by cigamit** [comment]
So, Cacti is behaving correctly since the user has access to at least one device, he get's access to the device, for at least viewing permitted graphs.   If you use 'Restrictive' graph access instead of 'Permissive' Console > Settings > General, you will get the expected behavior.

**Comment by DoubleBeast** [comment]
Damn i'm so dumb, you are totally right @cigamit i'm very sorry for wasting your time with my error.

PD: still think could be a good idea to add site perms.

**Comment by netniV** [comment]
Open a request for site permissions enhancement.
