### ISSUE TITLE
1.0.0 - Authentication Method: None - menu's & links missing

### ISSUE THREAD

**Issue by SjonHortensius** [Cacti/cacti#241]
When I use *Authentication: None* some things break:

* I have no menu on the left side
* I have no links to the settings

This used to work fine in cacti-0.8. To fix this I can manually navigate to `/settings.php?tab=authentication` and switch to Built-in. This fixes everything

**Comment by ronytomen** [comment]
Are you using apache?  If so, make sure that your do not have some old PHP directives defined for the virtual host or directory for Cacti.

**Comment by SjonHortensius** [comment]
No this is nginx :) What sort of directives are you thinking of?

**Comment by cigamit** [comment]
This issue is resolved.  Thanks for reporting this.
