### ISSUE TITLE
I had a problem updating an old version to a recent version of the cacti

### ISSUE THREAD

**Issue by pgmeister** [Cacti/cacti#2410]
**Describe the bug**
I tried to update version 0.8.7g to version 1.2.1, however, there were problems updating the database in its version 1.1.34, graphic attached:

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/47627139/52776223-ed9b2d00-301f-11e9-9770-9886a69d94f6.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by netniV** [comment]
This was recently corrected in the 1.2.2 development branch.  You will likely have the primary key already there or multiple entries in the version table.  Replace your 1_1_34.php file with this one:

https://github.com/Cacti/cacti/blob/develop/install/upgrades/1_1_34.php

The original issue for this was #2358 (Upgrade step to 1.1.34 fails)

**Comment by cigamit** [comment]
Closing as duplicate.
