### ISSUE TITLE
Error upgrading from cacti 1.2.0 bet4 to 1.2.1

### ISSUE THREAD

**Issue by arno-st** [Cacti/cacti#2412]
And not the same as #2316 since it's an upgrade from the official cacti release, not the develop version.

UPDATE host SET deleted='' WHERE deleted IS NULL | [Fail]
ALTER TABLE host MODIFY COLUMN deleted char(3) NOT NULL default '' | [Fail]

So what is my option now ?

**Comment by netniV** [comment]
Actually, as confusing as it is, it is the same.  It was a beta release, not an official release. Follow the advice and you should be OK.  In future, the plan is to make beta releases properly upgrade-able to full versions but in 1.2 that was not the case.

**Comment by arno-st** [comment]
ok I change the DB manually, and run the script upgrade DB to be sure it was ok and so far it's working
