### ISSUE TITLE
Polling fails after agent restart; 1.39

### ISSUE THREAD

**Issue by ibatten** [Cacti/cacti#2415]
With 1.39, and I think this is relatively new, restarting an agent results in the failure of polling.  The agent is working correctly, as tested with snmpget/snmpwalk, but the poller fails to add new data to the rrd file (rrdtool dump below).  originally with rrdtool 1.6 on debian, but I have out of interest installed rrdtool 1.7.1.  The "Devices" screen shows the agent as Up, and after a few days the polling appears to start working again.  My intuition is that the period that the polling fails is not related to how long the agent had been up prior to the restart, but I have not tested this.

			 <row><v>4.9564596640e+07</v><v>2.1455805860e+07</v></row>
			 <row><v>4.9563860160e+07</v><v>2.1456272000e+07</v></row>
			 <row><v>4.9563180720e+07</v><v>2.1456351640e+07</v></row>
			 <row><v>NaN</v><v>NaN</v></row>
			 <row><v>NaN</v><v>NaN</v></row>
			 <row><v>NaN</v><v>NaN</v></row>
			 <row><v>NaN</v><v>NaN</v></row>
			 <row><v>NaN</v><v>NaN</v></row>

**Comment by cigamit** [comment]
There is no version 1.1.39.  I would suggest that you check the device and ensure that it is up.  If you are using the develop version, I suggest you resync to the latest github and then re-index your devices.  Going to mark unverified as a result.

**Comment by netniV** [comment]
He may be talking about RRDTool 1.3.9

**Comment by cigamit** [comment]
Good point.

**Comment by cigamit** [comment]
I suspect this problem will be resolved with 1.2.2.  Please update when released.  Make sure you re-index your devices when the upgrade is complete.  There is a CLI script for re-indexing devices.  Closing for now.

**Comment by ibatten** [comment]
For various reasons I have not upgraded from 1.1.38. (which is what I meant).  I have, however, fixed this problem, which may or may not matter for the future.  The problem was that rebuilding of the cache was failing because at line 543 in utility.php an attempt is made to call sizeof() on what is actually a string (it was initially an array, but was overridden as a string).  I replaced it with equality to the null string and it now works correctly.

        # if (sizeof($ids)) {
        if ($ids != '') {
                db_execute("DELETE FROM poller_item WHERE present=0 AND local_data_id IN ($ids)");
        } else {
                /* only handle explicitely given local_data_ids */
        }

**Comment by netniV** [comment]
I believe that error was already corrected in one of our subsequent patches which you won't have had as you've not updated.

**Comment by ibatten** [comment]
I’d love to update, but I just can’t get it to work.  I follow the instructions, install the tar ball (1.2.5 this time, but I have tried 1.2.0, 1.2.1 and 1.2.2 as well) and I get the Install, please wait screen and nothing happens.  I have tried 1.2.5 tonight, and once I had fixed up the problem that the installer requests include/csrf/csrf-magic.js but that directory is actually include/vendor/csrf, nothing, same problem.  I have tried with Safari and Chrome in case it’s a browser issue.  A small number of changes are made to the database (I have diff’d the pre-upgrade backup and a similar backup I took post upgrade) but it doesn’t work: visiting the root of the installation always puts up the “Initialising upgrade” screen and then nothing more happens.  Nothing seems to be logged anywhere.  I’m at a loss as to know how to upgrade, and I am acutely aware that I am drifting further from the development trunk.  This isn’t by first rodeo: I have run everything from 0.8.7 (I think) onwards and done a lot of upgrades, but getting from 1.1.38 to 1.2.X appears to defeat me.  So I’m continuing to hack and fix 1.1.38, sadly :-(

**Comment by netniV** [comment]
The CSRF should be correct or we would have had more problems (I think).  However, feel free to log that as a separate issue as you did with the urlpath.

**Comment by ibatten** [comment]
It’s presumably the same problem: fixing urlpath fixed everything, and I’m a happy 1.2.5 bunny.

ian
