### ISSUE TITLE
cacti snmp notifications warnings even when snmp notifications are disabled.

### ISSUE THREAD

**Issue by jdcoats** [Cacti/cacti#2417]
snmp notifications are disabled and no snmp noitification receivers are configured but the log message is still generated.

2019/02/14 16:58:13 - SNMPAGENT WARNING: No notification receivers configured for event: cactiNotifyDeviceDown (CACTI-MIB)

**Comment by netniV** [comment]
This occurs because you have not disabled the snmpagent and the severity is either high or critical.

![image](https://user-images.githubusercontent.com/9052188/52864929-427b9800-3133-11e9-995c-6ae026085a69.png)
