### ISSUE TITLE
Upgrade problem MySQL Timezone

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#242]
ERROR: Your MySQL TimeZone database is not populated. Please populate this database before proceeding.

How to do this?

I edited:

/etc/php5/apache2/php.ini:date.timezone = Europe/Warsaw
/etc/php5/cli/php.ini:date.timezone = Europe/Warsaw

And 
SET @@global.time_zone = '+01:00';
SET @@session.time_zone = "+01:00";

This did not work.

Also tried to dpkg-reconfigure tzdata and restart mysql.

System: Debian Jessie.

Is it possible to add a short info how to do that or postpone upgrade?

**Comment by ronytomen** [comment]
Really not a Cacti problem.  Sounds like you are missing the MySQL time zone data.

https://dev.mysql.com/doc/refman/5.7/en/mysql-tzinfo-to-sql.html

**Comment by interduo** [comment]
We should be able to postpone the upgrade.

**Comment by pautiina** [comment]
It's not problem.
On FreeBSD:
```
cd /usr/local/share/mysql 
mysql -u root mysql < mysql_test_data_timezone.sql 
```
Other UNIX:
```
cd /usr/share/mysql 
mysql -u root mysql < mysql_test_data_timezone.sql 
```
If you have mysql root passrword:
`mysql -u root -p mysql < mysql_test_data_timezone.sql `

And you must add access cacti databes user for databases mysql or only for table:
`mysql.time_zone_name`

**Comment by pnyet** [comment]
Here is to add privileges for cacti database to time_zone_name table:

GRANT SELECT  ON mysql. time_zone_name TO 'cacti'@'localhost' IDENTIFIED BY 'your-db-password';

**Comment by interduo** [comment]
I did forgot about that @pautiina. Thank You.

**Comment by imax64** [comment]
works for me as well, thanks
