### ISSUE TITLE
Cannot manage plugins after upgrade to developing version

### ISSUE THREAD

**Issue by skyjou** [Cacti/cacti#2423]
**Describe the bug**
Cannot manage plugins after upgrade to developing version.

**To Reproduce**
1. Go to 'Confiuration'
2. Click on 'Plugins'
3. Click on 'Plugin Name'
4. It will link to 'https://www.cacti.net/'

**Expected behavior**
It shoud be the management page.

**Screenshots**
I put cursor on the plugin name, and we can see it link to Cacti home.
![screenshot from 2019-02-18 12-54-24](https://user-images.githubusercontent.com/13309854/52928817-9b8a3c80-337c-11e9-933b-74f8e278115b.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chrome
 - Version: 1.2.2(Develop)

**Comment by cigamit** [comment]
Plugins don't typically have a manage page.  Instead that is a link to the developer of the plugin.  Yours just happens to be developed by us.  Installing / Uninstalling / Enabling / Disabling are all done via the links to the left of that.

**Comment by skyjou** [comment]
My mistake. Sorry.
