### ISSUE TITLE
Input Value is Missing in Data Query after upgrade to 1.2.2 developing version

### ISSUE THREAD

**Issue by skyjou** [Cacti/cacti#2424]
**Describe the bug**
IP address value (HEX format) in Data Query Input filed is missing.

**To Reproduce**
1. Go to 'Management \ Devices \ Device Description'
2. Click on 'Verbose Query'
3. Scroll down to 'Data Query Output'
4. The return value is empty (or only one character)

**Expected behavior**
In version 1.2.1, it can show the IP Address like this:
![screenshot from 2019-02-18 16-02-18](https://user-images.githubusercontent.com/13309854/52936272-9d60f980-3396-11e9-822d-2d36aa3f26cf.png)

**Screenshots**
Cacti verbose query output is here:
![screenshot from 2019-02-18 15-58-19](https://user-images.githubusercontent.com/13309854/52936337-c97c7a80-3396-11e9-98d8-9beee2bf9f8b.png)

And the snmp command from same server do work:
> snmpget -v2c -c TEST 172.30.0.254 .1.3.6.1.4.1.12356.101.14.4.4.1.3.1.16.70.80.50.50.49.66.51.88.49.52.48.49.53.49.51.56
SNMPv2-SMI::enterprises.12356.101.14.4.4.1.3.1.16.70.80.50.50.49.66.51.88.49.52.48.49.53.49.51.56 = Hex-STRING: AC 1F FC 03

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chrome
 - Version: 1.2.2 (develop)

**Comment by skyjou** [comment]
Reference to offical template: interface.xml. I try to add '<output_format>hex</output_format>' to the field of IP address in my SNMP query XML file.
Now I can get value like this:
![image](https://user-images.githubusercontent.com/13309854/52954726-d82e5600-33c5-11e9-90dc-11bc514126f6.png)

I cannot find documents about this to confirm if it is a new design.

**Comment by skyjou** [comment]
Although I can get value now, the output of verbose query does not display correctly:
![screenshot from 2019-02-19 09-04-30](https://user-images.githubusercontent.com/13309854/52983401-f62ba300-3425-11e9-85e2-1af70eaa5356.png)

**Comment by cigamit** [comment]
I'm just trying to figure out the best way to handle this one.  First of all, it's a hex-string.  Which means it should be a string.  But it has 4 hex bytes.  Wish there was some way to tell us that those 4 bytes are an IP address without breaking other things.

**Comment by cigamit** [comment]
Update lib/snmp.php.  Reindex.  Close if resolved.

**Comment by skyjou** [comment]
Thank you.
