### ISSUE TITLE
Reporting issue - multiple recipients do not receive e-mails

### ISSUE THREAD

**Issue by penguininternet** [Cacti/cacti#2427]
When setting up multiple e-mail recipients in the reporting function, only the first recipient is sent an e-mail. Any additional recipients or bcc contacts do not receive this. Additionally the logs do not show their address.

If you set up a report to be sent to user1@domain.com and user2.comain.com (comma separated) and also optionally add an address to the bcc field, then run the report (or have it scheduled).

The report runs, but only ever sends to the first e-mail address listed and never to the bcc address.

The cacti logs shows the e-mail being sent, but not the additional recipients listed in the log either, eg:

```console
2019/02/15 07:00:06 - MAILER INFO: Mail successfully sent from 
'Cacti Monitoring  <cacti@domain.com>', to  'user1@domain.com',  
cc '', Subject 'Transit Report'

2019/02/15 07:00:06 - MAILER INFO: Mail successfully sent from 
'Cacti Monitoring  <cacti@domain.com>', to  'user1@domain.com', 
cc '', Subject 'Transit Report'
```

In the above example, the recipients are set to user1@domain.com and user2@domain.com with the bcc address as bcc@domain.com

The database does show the correct e-mail addresses:

```sql
MariaDB [cacti]> select id,enabled,subject,email from reports;
+----+---------+--------------------------------+----------------------------------------------+
| id | enabled | subject                        | email                                        |
+----+---------+--------------------------------+----------------------------------------------+
|  1 |         | Test Report                    | user@domain.com                              |
|  2 |         | Test Report 2                  | user@domain.com                              |
|  3 | on      | Transit Report                 | user1@domain.com,user2@domain.com            |
+----+---------+--------------------------------+----------------------------------------------+
3 rows in set (0.00 sec)
```

**Comment by netniV** [comment]
I've tested the functionality and it seems to work as expected.  Can you update to the latest development version which will give more information on the cacti.log

**Comment by cigamit** [comment]
Please update to 1.2.2 once it is released.  Open a new bug if this issue continues.
