### ISSUE TITLE
Plugins --> name column does not match "name field value" in INFO file

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#2428]
Under https://github.com/Cacti/documentation/blob/develop/Plugin-Guidelines.md#plugin-data-entry
I do not find 'name' field definition. But most Cacti official plugin INFO file have 'name' field.

If 'name' field is valid(or valid in future),  how about show "plugin name"  as diff below if INFO.name is a specified format, e.g. ` ionCube`
```diff
--- plugins.php   2019-01-26 12:40:13.000000000 +0800
+++ plugins.php   2019-02-19 17:21:10.542168108 +0800
@@ -217,7 +217,7 @@
                                                (directory, name, status, author, webpage, version, requires, infoname)
                                                VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
                                                array(
-                                                       $file,
+                                                       (strtolower($file) == strtolower($cinfo[$file]['name']) ? $cinfo[$file]['name'] : $file),
                                                        $cinfo[$file]['longname'],
                                                        $cinfo[$file]['status'],
                                                        $cinfo[$file]['author'],
```

**Comment by netniV** [comment]
Because that would break directory checking functionality as it's the directory name that you are modifying there.  The "name" should match the directory folder (and in most cases, this is in lower case).

**Comment by ddb4github** [comment]
Yes,  above solution(diff) show "INFO defined name" only when lower(directory) equal with "lower(INFO.name)"

**Comment by netniV** [comment]
That is the SQL insert statement, though.  Not just a display unless I'm missing somethere there.

**Comment by ddb4github** [comment]
Yes, you are correct.  This page design to collect all plugin info into a tmp table, installed from 'plugin_config' table, non-installed from 'plugins' directory.
Then directly display plugin-list from that tmp table.

So need to modify more lines if I want to make sure INFO.name as display with some uppercase(not only first char, e.g. `ionCube`, `SLES`), and directory.name is only lowercase(`ioncube`, `sles`)

**Comment by netniV** [comment]
Yes, currently directory is case sensitive on Linux but not so on Windows.

**Comment by ddb4github** [comment]
So,  to easily plugin usage and avoid plugin conflict(on linux),  PIA should enforce plugin-developer to always keep directory name with lowercase. 

Also for display,  mixed upper/lower case can provide more readability than upfirst. But require more coding  for each line about directory reading/comparing  :trollface:

**Comment by ddb4github** [comment]
> Yes, you are correct. This page design to collect all plugin info into a tmp table, installed from 'plugin_config' table, non-installed from 'plugins' directory.
> Then directly display plugin-list from that tmp table.
> 
> So need to modify more lines if I want to make sure INFO.name as display with some uppercase(not only first char, e.g. `ionCube`, `SLES`), and directory.name is only lowercase(`ioncube`, `sles`)

As previous comments above,  solution need more coding than my first diff. I'll create a another PR as soon
