### ISSUE TITLE
Allow Device SNMP Options to be Templated

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#2429]
**Is your feature request related to a problem? Please describe.**
Currently Automation and RouterConfigs have their own methods of provding template SNMP options to allow for easier SNMP management.  However, the core does not have this feature so when you need to update the SNMP options for many devices, the only way to do this is via the Host listing and doing a mass edit.

Additionally, when bringing a new device on board without automation, you have to ensure you are entering all the correct details which can be cumbersome especially when you have v3 auth/priv settings.

**Describe the solution you'd like**
Introduce a core, snmp template system.

**Describe alternatives you've considered**
Automation/RouterConfigs have the ability already, Automation's could be reused since it is already within the core product.

**Comment by TheWitness** [comment]
This one is duplicate.  Moving up on the pipeline.

**Comment by TheWitness** [comment]
1) Move SNMP Options to Presets
2) Make the change after that
3) User can always override

**Comment by TheWitness** [comment]
This is resolved now.

**Comment by TheWitness** [comment]
Working after QA: 

![image](https://github.com/user-attachments/assets/91258891-fb01-46ef-ace7-38594e064602)
