### ISSUE TITLE
1.0.0 - SMTP issue

### ISSUE THREAD

**Issue by imax64** [Cacti/cacti#243]
hello,

 I've recently upgraded from 0.8.8h (that included settings plugin) to 1.0.0 and now cacti no longer sends email. not even the most basic setting (SMTP).

i used SMTP in the old version and it worked fine. (it doesn't require authentication or SSL, user and pass fields are left empty)

the error message is: 

> Checking Configuration...
> Method: SMTP
> Ping Results: SMTP error: Authentication failed: 501 5.7.3 Cannot decode arguments
> Message Not Sent due to ping failure.
> 

But SMTP works fine, i have ping and port 25 connectivity to mailserver :

> [root@adcacti02 cacti]# telnet xxxxxxxxxx.internal.vodafone.com 25
> Trying X.Y.Z.P...
> Connected to xxxxxxxxxx.internal.vodafone.com.
> Escape character is '^]'.
> 220 xxxxxxxxxx.internal.vodafone.com Microsoft ESMTP MAIL Service, Version: 8.5.9600.16384 ready at  Wed, 1 Feb 2017 00:57:44 +0100 
> 
> EHLO xxxxxxxxxx.internal.vodafone.com
> 250-xxxxxxxxxx.internal.vodafone.com Hello [X.Y.Z.P]
> 250-AUTH NTLM LOGIN
> 250-AUTH=LOGIN
> 250-TURN
> 250-SIZE
> 250-ETRN
> 250-PIPELINING
> 250-DSN
> 250-ENHANCEDSTATUSCODES
> 250-8bitmime
> 250-BINARYMIME
> 250-CHUNKING
> 250-VRFY
> 250 OK
> MAIL FROM:yyyyyyyy@vodafone.nl
> 250 2.1.0 yyyyyyyy@vodafone.nl....Sender OK
> RCPT TO:xxxxxxxxx@vodafone.com
> 250 2.1.5 xxxxxxxxx@vodafone.com 
> data
> 354 Start mail input; end with <CRLF>.<CRLF>
> Subject: test
> test
> .
> 250 2.6.0 <NLRAT-WIMX0018r6beU0012c8b6@xxxxxxxxxx.internal.vodafone.com> Queued mail for delivery
> quit
> 221 2.0.0 xxxxxxxxxx.internal.vodafone.com Service closing transmission channel
> Connection closed by foreign host.
> 

surprisingly, there are no logs in cacti.log, even with the highest debug setting.

**Comment by imax64** [comment]
Update:
it works if you type a user/pass for authentication . The downside was i had to configure authentication on my server ...

it doesnt want to mail with blank username or pass

**Comment by cigamit** [comment]
Thanks for reporting this.  Will look into it shortly.

**Comment by cigamit** [comment]
Resolved, thanks for reporting!
