### ISSUE TITLE
"New Device" menu item showing as selected incorrect when "Devices" clicked

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#2430]
**Describe the bug**
Both "Create -> New Device" and "Management -> Device" are selected when clicking on "Management -> Device" under the Paw theme.

**To Reproduce**
1. Go to Console
2. Click on Management, then Device
3. See error

**Expected behavior**
Only Device should be selected.  Clicking "Create -> New Device" does not automatically selected the Device menu item.

**Screenshots**
![image](https://user-images.githubusercontent.com/9052188/53012731-c7b8c280-343b-11e9-89a7-a11995e94ce3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome / Firefox
 - Version: 74.0.3702.0 / 65.0.1

**Comment by cigamit** [comment]
That's not going to be easy to fix since it's the same filename.  I suspect you should implement the accordion menu view on the theme as the fix.

**Comment by cigamit** [comment]
Fixing this one now.
