### ISSUE TITLE
Enable/Disable Data Source generates warnings when snmp_index is bad (blank)

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#2434]
**Describe the bug**
If you attempt to enable or disable a data source that has no snmp index, a backtrace is generated in the cacti.log as the 'id' column is missing.

```

2019/02/19 15:32:54 - CMDPHP PHP ERROR NOTICE Backtrace: (/data_sources.php[56]:form_actions(), /data_sources.php[410]:api_data_source_enable(), /lib/api_data_source.php[338]:update_poller_cache(), /lib/utility.php[454]:CactiErrorHandler())
2019/02/19 15:32:54 - ERROR PHP NOTICE: Undefined index: id in file: /usr/share/cacti/site/lib/utility.php on line: 454
2019/02/19 15:32:54 - CMDPHP PHP ERROR NOTICE Backtrace: (/data_sources.php[56]:form_actions(), /data_sources.php[410]:api_data_source_enable(), /lib/api_data_source.php[338]:update_poller_cache(), /lib/utility.php[177]:CactiErrorHandler())
2019/02/19 15:32:54 - ERROR PHP NOTICE: Undefined index: id in file: /usr/share/cacti/site/lib/utility.php on line: 177
2019/02/19 15:32:54 - CMDPHP PHP ERROR NOTICE Backtrace: (/data_sources.php[56]:form_actions(), /data_sources.php[410]:api_data_source_enable(), /lib/api_data_source.php[338]:update_poller_cache(), /lib/utility.php[168]:CactiErrorHandler())
2019/02/19 15:32:54 - ERROR PHP NOTICE: Undefined index: id in file: /usr/share/cacti/site/lib/utility.php on line: 168
```

**To Reproduce**
1. Go To Management -> Data Sources
2. Click on any data source that has a bad index (ensure it's ticked)
3. Scroll down to the actions drop down and select Enable or Disable
4. See error in cacti.log though the data source is updated

**Expected behavior**
There should be no error but this occurs due to the index being blank and the update_poller_cache() function relying on an index existing.

**Comment by cigamit** [comment]
I can not reproduce this.

**Comment by cigamit** [comment]
Looked at the code, see what is happening.  Try again.

**Comment by netniV** [comment]
I can confirm that this is now resolved.  For reference, this was a datasource with a bad index (the disk is missing out of a server currently).  The above change seems to have resolved the issue.
