### ISSUE TITLE
Unknown column 'dl.snmp_index' in 'where clause'

### ISSUE THREAD

**Issue by jdcoats** [Cacti/cacti#2436]
> 

2019/02/20  03:21:51 - CMDPHP SQL Backtrace:   (/poller_commands.php[139]:run_data_query(),  /lib/data_query.php[331]:update_poller_cache_from_query(),  /lib/utility.php[109]:db_fetch_assoc_prepared(),  /lib/database.php[464]:db_execute_prepared())
--
2019/02/20 03:21:51 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'dl.snmp_index' in 'where clause'

**Comment by cigamit** [comment]
Resolved now.
