### ISSUE TITLE
Allow CDEF to be used as a filter for Graph/Data Sources

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#2439]
**Is your feature request related to a problem? Please describe.**
You can currently see in the list of CDEF's the number of graphs/templates using that CDEF.  There is no method to filter the graph/template lists to find just the ones using the CDEF.

**Describe the solution you'd like**
Make the counters clickable which then link to the graph/template lists with just those that are using the CDEF.

**Describe alternatives you've considered**
Currently the only alternative is to use manual database queries.

**Comment by TheWitness** [comment]
Same can be said of VDEF's and other presets.

**Comment by netniV** [comment]
This might slow down the graph queries page if it's added in.  The reason being that it would need to get to the graph_template_id to see the vdef which isn't included in the queries currently.  Unless, I'm missing something.
