### ISSUE TITLE
HTTP 500 error after upgrading to cacti 1.0.0

### ISSUE THREAD

**Issue by amazen123** [Cacti/cacti#244]
Good Day,

I have a bit  of a problem after I upgrade to 1.0.0, when i load the page it gives me http 500 error in IE and blank page when accessing it to chrome or mozilla.
I downloaded cacti 1.0.0 copy the rra and plugins folder in old cacti directory, edit database password in config.php, restart IIS service, access the cacti in browser and all I see is white page.
I also test the cacti 1.0.0 without copying any folder and editing of config file but has the problem.
Thanks,

OS : Windows Server 2008 R2 Standard
Cacti version 1.0.0
PHP version 5.6.3
MySQL version 5.6

**Comment by pautiina** [comment]
Try a clean install, if the problem persists, it is likely an error somewhere in the services. If a clean install is successful, it means that the problem in the tables. I have been like on FreeBSD, I had to clean the base of the handles junk and edit my.cnf file

**Comment by amazen123** [comment]
Clean install the cacti only or all cacti and its pre-requisite (PHP, MySQL, net-snmp)?

**Comment by pautiina** [comment]
cacti and its pre-requisite (PHP, MySQL, net-snmp).
When you clean install- Cacti show you what need install, and what you need change on config file php.ini and my.cnf.

**Comment by amazen123** [comment]
okay, I'll try that tomorrow :)

**Comment by amazen123** [comment]
Good Day,

The 1.0.0 works now after i clean install :)
Thanks @pautiina 
But I don't have any problems last time when upgrading using the previous patches.
Did someone try to upgrade their cacti to 1.0.0 without clean install?

**Comment by cigamit** [comment]
If you took the latest development branch, then there were some changes made.  However, I do not think they should have impacted you.  It appears that we may have a per-requisite check issue in the installer when upgrading.  So, there may be another fix coming soon.

**Comment by amazen123** [comment]
Thank you @cigamit 
I'll wait for the fix.
