### ISSUE TITLE
Enhance boost to consume less I/O for traditional disk drives during boost updates

### ISSUE THREAD

**Issue by jdcoats** [Cacti/cacti#2441]
I cannot figure out why spine runs so long for 2 polling cycles immediately after boost runs and then resumes normal. Its driving me crazy making a few random gaps in graphs. right after boost completes I have a bunch of slowlog entries like attached.

![screen shot 02-21-19 at 03 26 pm](https://user-images.githubusercontent.com/42470924/53200048-9cc2a000-35ee-11e9-8ba0-d635b9e212b2.PNG)
[slowlog.txt](https://github.com/Cacti/cacti/files/2891153/slowlog.txt)

**Comment by netniV** [comment]
This would suggest that the MySQL process doesn't have enough resources unless there's a key missing.

**Comment by jdcoats** [comment]
Ive been tuning for 2 weeks and cant seem to find the deficiency in resources. IO is not extreme during the boost runs but the poller that started during that run and the poller immediately after run between 50-65 sec and then resume back to ~4sec

I did just raise innodb_buffer_pool_instances to 64 as the cacti tech support suggests even though  mysqltuner suggest it be at 16. The same thing still happens.

**Comment by jdcoats** [comment]
Iv'e thrown so many resources at this thing that i cant believe it is a resource issue. It happens with 1 minute polling and if boost happens to run in 40 sec and spine starts somewhere outside of this cycle its okay, but if boost is running and spine starts then the following 2 polling cycles are delayed up to a minute. This should not happen with a poller that can normally run at 4-5sec. there is no extreme IO happening at this time, This is a new install with a relatively small 12G rra dir. I can watch iotop during the run and never get reads or writes over 50mb where these disks are not ssd but will do above 150-200mb without causing this. This is new since upgrade to 1.x, I just cant get to the bottom of it.

**Comment by jdcoats** [comment]
attached is the slowquerylog for the past couple hours keeping in mind that the only time slow queries happen are every 30 minutes a few seconds after boost has completed and spine is hung up running slow
[slowquerylog.txt](https://github.com/Cacti/cacti/files/2896262/slowquerylog.txt)
.

**Comment by netniV** [comment]
What sizes are your database and tables?  Are there other databases on here?

**Comment by jdcoats** [comment]
only cacti and syslog

syslog01 ~ # du -h /var/lib/mysql/cacti/
868M    /var/lib/mysql/cacti/
syslog01 ~ # du -h /var/lib/mysql/syslog
11G     /var/lib/mysql/syslog
 syslog is set to 1 day so does not get much larger.

**Comment by jdcoats** [comment]
this problem exists even if syslogtomysql is disabled with no input.

**Comment by jdcoats** [comment]
for example there was just a run of routerconfigs during a poller cycle which has more db activity than both boost and the poller but no poller overruns
![example](https://user-images.githubusercontent.com/42470924/53280535-2191e480-36e9-11e9-9551-00cd75456ab3.png)
 take place.

**Comment by cigamit** [comment]
This really looks like disk I/O to me.  Its not about the # of Mbps written, its that we are writing lots of data to lots of different files, causing it to jump all over the disk, thus requiring a lot of seek times.  Check your I/O Wait % in top when Boost is writing.  This ofcourse is where SSDs really shine.

**Comment by jdcoats** [comment]
So Cacti 1.x only works with ssd’s? The spine and boost should be able to run at the same time. What I’m saying is that even after boost completes, the following spine run is held up.


——
Dan

On February 22, 2019 at 11:25:15 PM EST, Jimmy Conner <notifications@github.com> wrote:
CAUTION! This email came from outside Tallahassee Memorial HealthCare. Exercise extra caution clicking links and opening attachments from any and all senders.


________________________________

This really looks like disk I/O to me. Its not about the # of Mbps written, its that we are writing lots of data to lots of different files, causing it to jump all over the disk, thus requiring a lot of seek times. Check your I/O Wait % in top when Boost is writing. This ofcourse is where SSDs really shine.

**Comment by netniV** [comment]
No, I am running on SATA drives but I do not have the vast amounts of data that you seem to be processing. When you are talking about large volumes of data, you need the speed/power of faster hardware.  For Hard Disks, that is SSDs.

**Comment by cigamit** [comment]
It is likely just that, boost is taking I/O away from the physical disks likely due to it being so efficient at writing.  However, if your disks are ext3 and even xfs, I've not seen this problem before.

I know you have a large number of disks in the array.  Can you do a few things for us:

1) Check for a degraded status on your disk array
2) Describe your format type and layout (xfs, brtfs, extX, block size, etc.)
3) Run "iostat -k 1 device" during boost updates and let's see what you disk is doing. 
4) Post the results of the iostat

**Comment by jdcoats** [comment]
15krpm sas raid 6 reiserfs
![imc2](https://user-images.githubusercontent.com/42470924/53289309-8178a180-3762-11e9-88ea-d7c773023979.jpg)
![imc1](https://user-images.githubusercontent.com/42470924/53289310-8178a180-3762-11e9-94e1-ec7f2544d2bd.jpg)
[disk.txt](https://github.com/Cacti/cacti/files/2897016/disk.txt)

ill get you the iostat next boost run

**Comment by jdcoats** [comment]
[10.9.76.4820190223.log](https://github.com/Cacti/cacti/files/2897027/10.9.76.4820190223.log)

iostat through boost run, then I stopped and started it after boost completed where spine ran slow for 2 polls

**Comment by cigamit** [comment]
When you expand top (hit the 1 key) on that device, how many cpu's does it show?  Also, that was not 1 second, that was 5 or  10 second intervals right?  Looks like 6 drives right?  So, that means on a normal slow disk, you will get ~420 transactions per second.  Get me those clarifications.

**Comment by jdcoats** [comment]
10 cpu,
top - 12:27:27 up 21:42,  2 users,  load average: 1.97, 2.21, 2.65
Tasks: 203 total,   2 running, 201 sleeping,   0 stopped,   0 zombie
%Cpu0  :  1.0 us,  1.4 sy,  0.0 ni, 97.6 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu1  :  1.7 us,  1.7 sy,  0.0 ni, 96.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu2  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu3  : 54.5 us, 14.0 sy,  0.0 ni, 31.4 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu4  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu5  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu6  :  8.1 us,  2.7 sy,  0.0 ni, 85.5 id,  3.7 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu7  : 97.3 us,  0.3 sy,  0.0 ni,  2.3 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu8  : 15.3 us, 10.9 sy,  0.0 ni, 73.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu9  :  3.0 us,  1.0 sy,  0.0 ni, 96.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :  54974.2 total,    301.8 free,  29889.5 used,  24782.8 buff/cache
MiB Swap:   7640.3 total,   7640.3 free,      0.0 used.  24682.2 avail Mem

no that was 1sec intervals (iostat -k 1)

**Comment by cigamit** [comment]
Looks like 1 second, but odd.

**Comment by cigamit** [comment]
Well, from the looks of it, we just have to idle boost for non-ssd disks (aka slow it down).  I have some thoughts about a 1.3 release that I can flip you.  But won't make it into 1.2.2 release (today).

**Comment by jdcoats** [comment]
sounds good, ill definitely try it out. Thanks!

**Comment by jdcoats** [comment]
btw, those stats were during a mactrack poller run also, so thats about as busy as it gets with boost,mactrack,syslog and spine writing

**Comment by cigamit** [comment]
okay, so let's do the following:
1) Edit lib/boost.php
2) Goto ~line 814 you will see a call to boost_rrdtool_function_update
3) Add a call to 'usleep(100000)' right after that call, which will slow down the updates.  There is one more call a little later, add the usleep there too.
4) There is a more interesting approach, but in the mean time, this will keep your poller more happy.  Just tweak that number up until things settle down.

Let us know what a good number ended up being for the usleep...

**Comment by jdcoats** [comment]
okay 100000 may be extreme, that took boost from 60 sec to 30 minutes and iowait never went above 1%. I'll continue to test different sleep times and let you know. Thanks!

**Comment by jdcoats** [comment]
okay, preliminary results are that  usleep(80000); is best for my setup. I was able to change to 1hr/1500000 records and get a little separation between runs for now.
![boost2](https://user-images.githubusercontent.com/42470924/53291598-bf39f200-3783-11e9-953c-c2419947458d.png)
![boost](https://user-images.githubusercontent.com/42470924/53291599-bf39f200-3783-11e9-9ace-9110ed1374cc.png)
![boost3](https://user-images.githubusercontent.com/42470924/53291608-ec86a000-3783-11e9-99bf-2cb33321a42b.png)

**Comment by netniV** [comment]
Good work!

**Comment by jdcoats** [comment]
update5 sec I do not think that this issue is completely identified or resolved. We have slowed down boost enough to prove that IO is not causing the issue itself but spine still hangs randomly and will cause this message. Now even when boost isn't running spine will go from 5 sec polls to +60sec polls and overrun. I have now changed spine from 1min/50 processes to 1min/10 processes to try to slow the hang ups. I think there is a bug its just that over the years we have just made things faster by design that they have overcome the disk speed? I have another server I can migrate too with ssd's to see if this is true but it will take a lot of work. It really seems like what has been working fine for 10 years which was migrated to new hardware 4 years ago and was running fine on 0.8.8h should be able to perform. I've seen numerous posts over the past year that were similar and assumed they had been resolved but, I'm still experiencing the same results. Instability and gaps in graphs despite trying to slow things down that shouldn't have to be slowed.

**Comment by jdcoats** [comment]
is it just ironic that in trying to make things faster over the years that now they are to fast for the average hardware? :)

**Comment by jdcoats** [comment]
ive slowed spine down to 1 process and 5 threads to see if it stops the random hang up

**Comment by netniV** [comment]
I think it's less to do with slowing things down and more to do with finding the source of the inter-process block.  Obviously, slowing things down will reduce the likelihood of the block.

What timeouts do you have on devices? If you have 3 second timeouts for SNMP and PING, that can be 6 seconds for one device to be considered offline.  So, if you end up with 10-15 of them being slow to respond, that can overrun instantly.  

Additionally, if you have devices all respond in about 15ms for ping and 15ms for SNMP, then by my calculations (and i'm sure @cigamit will correct me if I'm wrong) that would be approx 33 devices/second.  Over the course of 60 seconds that would be an average of about 2,000 devices.  If you think back to our 6 second timeout about, that one timeout would be the equivalent of 198 devices.

**Comment by netniV** [comment]
Also, have you attempted to monitor CPU/Disk usage via top whilst all this is going on?  If there is no block there, then it is either Network or MySQL related.

**Comment by jdcoats** [comment]
that's easier said than done when spine will run every minute for hours and then all of a sudden hang up for a polling cycle or 2. It would be nice if I could make it output individual device polling stats so maybe I could catch it hanging on a device or get a clue as to what is causing it.

**Comment by netniV** [comment]
That would be possible, though it would have to be in memory until the end so it could be written in bulk.
