### ISSUE TITLE
Undefined index:  snmp_sysUpTimeInstance in file:  functions.php  on line: 4172

### ISSUE THREAD

**Issue by jdcoats** [Cacti/cacti#2442]
> 

2019/02/21  16:16:39 - CMDPHP PHP ERROR NOTICE Backtrace:   (/automation_devices.php[81]:display_discovery_page(),  /automation_devices.php[302]:get_uptime(),  /lib/functions.php[4172]:CactiErrorHandler())
--
2019/02/21 16:16:39 - ERROR PHP NOTICE: Undefined index:  snmp_sysUpTimeInstance in file:  /var/www/localhost/htdocs/cacti/lib/functions.php  on line: 4172

**Comment by netniV** [comment]
This is now in the main development code, please check and close if issue is resolved.
