### ISSUE TITLE
Interface traffic data source do not apply the name (1.2.2 develop)

### ISSUE THREAD

**Issue by skyjou** [Cacti/cacti#2443]
**Describe the bug**
Interface traffic data source do not apply the name.

**To Reproduce**
1. Create traffic graph for device
2. Data source name of interface traffic will not apply the name, even by manual update.

**Expected behavior**
It should apply the suggested name automatically.

**Screenshots**
Reference to [issue 1981](https://github.com/Cacti/cacti/issues/1981).
Different from issue 1981, it will not apply the name on manual update.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chrome
 - Version: 72

**Comment by jdcoats** [comment]
iv'e tried to reproduce this and cannot. It uses your data query/data query name/associated graph template. If you change the suggested name order or add a new suggested name as i have |host_description|-|query_ifName|-|query_ifAlias| and then go to graphs and filter for graph template and select all to reapply suggested names it will change the names of them as designed. Is this not what you expect?

**Comment by cigamit** [comment]
Nice graph BTW!

**Comment by skyjou** [comment]
The data source name and graph title need not be the same. So, I don't understand the meaning of jdcoats's graph. Reference to issue 1981, my cacti not apply the interface traffic 'dsname' defined in 'Data Query' when graph just create. Even by manual update, it still not apply the top one naming rule. I just remove the rule and re-create it again, and it works now. That's weird, but it really works now.

Thank you for try to reproduce it.
