### ISSUE TITLE
Status how to add

### ISSUE THREAD

**Issue by tyit** [Cacti/cacti#2445]
![wx20190222-174848](https://user-images.githubusercontent.com/31933126/53234422-75410580-36ca-11e9-86b4-f10f5a91d962.png)

thank you very much

**Comment by netniV** [comment]
I would recommend duplicating the interface graph template, then edit and add the additional data source.  You will need just gprint items from the status template as plotting 0 and 1 just would not show up on the graph.  In duplicating the template, you don't affect interfaces that are not being monitored for their status and allows you to create/play with the template/graphs without affecting existing ones.

**Comment by tyit** [comment]
@netniV thank you very much
