### ISSUE TITLE
Strip potential extra '.' when performing <rewrite_index>

### ISSUE THREAD

**Issue by tbilan** [Cacti/cacti#2448]
Bug
In the verbose query below there is a situation that allowed the creation of a malformed OID by concatenating two '.' next to each other.  This happens in the <rewrite_index> function.  I'm running version 1.2.1.

Example of the error:
```
Fixing wrong 'method' field for 'devName' since 'rewrite_index' or 'oid_suffix' is defined
--
Total: 0.640000, Delta: 0.000000, Located input field 'devName' [get]
Executing SNMP get for 14 oids (.1.3.6.1.4.1.29671.1.1.4.1.11..0.24.10.10.169.152, .1.3.6.1.4.1.29671.1.1.4.1.11..0.24.10.10.169.152, .1.3.6.1.4.1.29671.1.1.4.1.11..0.24.10.10.169.152, .1.3.6.1.4.1.29671.1.1.4.1.11..0.24.10.10.169.152, .1.3.6.1.4.1.29671.1.1.4.1.11..0.24.10.10.169.152, .1.3.6.1.4.1.29671.1.1.4.1.11..0.24.10.10.169.152, .1.3.6.1.4.1.29671.1.1.4.1.11..0.24.10.10.169.152, .1.3.6.1.4.1.29671.1.1.4.1.11..0.24.10.59.225.198, .1.3.6.1.4.1.29671.1.1.4.1.11..0.24.10.59.225.198, .1.3.6.1.4.1.29671.1.1.4.1.11..0.24.10.59.225.198, .1.3.6.1.4.1.29671.1.1.4.1.11..0.24.10.59.225.198, .1.3.6.1.4.1.29671.1.1.4.1.11..0.24.10.59.225.198, .1.3.6.1.4.1.29671.1.1.4.1.11..0.24.10.59.225.198, .1.3.6.1.4.1.29671.1.1.4.1.11..0.24.10.135.91.90)
Found result for data @ '.1.3.6.1.4.1.29671.1.1.4.1.11..0.24.10.10.169.152' [value='U']
Found result for data @ '.1.3.6.1.4.1.29671.1.1.4.1.11..0.24.10.59.225.198' [value='U']
Found result for data @ '.1.3.6.1.4.1.29671.1.1.4.1.11..0.24.10.135.91.90' [value='U']
Setting result for data @ '.1.3.6.1.4.1.29671.1.1.4.1.11..0.24.10.10.169.152' [key='0', value='U']
```

I debugged the PHP and created the following solution if someone wouldn't mind adding it to future releases.

In data_query.php:
```
852c852
<                                               $oid .= '.' . $oid_suffix;
---
>                                                 $oid .= '.' . preg_replace('/^\.{0,}([0-9.]+)/', '\1', $oid_suffix);  //Create the OID but make sure we don't have two '..' next to each other
```

Example after fix

```
Fixing wrong 'method' field for 'devName' since 'rewrite_index' or 'oid_suffix' is defined
--
Total: 0.690000, Delta: 0.000000, Located input field 'devName' [get]
Executing SNMP get for 14 oids (.1.3.6.1.4.1.29671.1.1.4.1.11.0.24.10.10.169.152, .1.3.6.1.4.1.29671.1.1.4.1.11.0.24.10.10.169.152, .1.3.6.1.4.1.29671.1.1.4.1.11.0.24.10.10.169.152, .1.3.6.1.4.1.29671.1.1.4.1.11.0.24.10.10.169.152, .1.3.6.1.4.1.29671.1.1.4.1.11.0.24.10.10.169.152, .1.3.6.1.4.1.29671.1.1.4.1.11.0.24.10.10.169.152, .1.3.6.1.4.1.29671.1.1.4.1.11.0.24.10.10.169.152, .1.3.6.1.4.1.29671.1.1.4.1.11.0.24.10.59.225.198, .1.3.6.1.4.1.29671.1.1.4.1.11.0.24.10.59.225.198, .1.3.6.1.4.1.29671.1.1.4.1.11.0.24.10.59.225.198, .1.3.6.1.4.1.29671.1.1.4.1.11.0.24.10.59.225.198, .1.3.6.1.4.1.29671.1.1.4.1.11.0.24.10.59.225.198, .1.3.6.1.4.1.29671.1.1.4.1.11.0.24.10.59.225.198, .1.3.6.1.4.1.29671.1.1.4.1.11.0.24.10.135.91.90)
Found result for data @ '.1.3.6.1.4.1.29671.1.1.4.1.11.0.24.10.10.169.152' [value='Union']
```

**Comment by cigamit** [comment]
Same instructions as the other issue.  Known, and resolved.

**Comment by tbilan** [comment]
I just pulled the latest develop branch and it still has the original problem code.  Can someone update data_query.php?  Thanks!

**Comment by tbilan** [comment]
I found a workaround using existing code by extending my <oid_index_parse> regex by 1 character to include the "." so that when it parsed out the suffix it didn't start with a "." and then get all messed up in the data_query.xml and the poller_table.

<oid_index_parse>OID/REGEXP:^.{29}(.*)</oid_index_parse> instead of <oid_index_parse>OID/REGEXP:^.{28}(.*)</oid_index_parse>

Example:
.1.3.6.1.4.1.29671.1.1.5.1.7.0.24.10.10.169.152.0 was split to .1.3.6.1.4.1.29671.1.1.5.1.7 and .0.24.10.10.169.152.0  

When recombined it was becoming .1.3.6.1.4.1.29671.1.1.5.1.7..0.24.10.10.169.152.0. as seen by the SQL query: select host_id, arg1 from poller_item;

I {29} regex changed grabed the last "." on the first half so now it's .1.3.6.1.4.1.29671.1.1.5.1.7. and 0.24.10.10.169.152.0   Cacti likes this much better and seems to work so I'll go with that.

My 2 cents is it may be nice to have some kind of string check for ".." anytime an OID is built since a '.' is added in the middle of the join just to make sure it's impossible to get a '..' because the snmp functions hate malformed OIDs.

Typing all this up because there are not a lot of docs on <oid_index_parse> and it may help someone in the future.
