### ISSUE TITLE
Fatal Error when running add_data_query.php via CLI

### ISSUE THREAD

**Issue by dumporama** [Cacti/cacti#2452]
Hi I'm new here, I hope this bug report is described okay.

**Describe the bug**
When running add_data_query.php via CLI I get the below error:
Cacti version 1.2.1

```
Fatal error: Uncaught Error: Call to undefined function getSNMPQueries() in C:\Apache24\htdocs\cacti\cli\add_data_query.php:138
Stack trace:
#0 {main}
  thrown in C:\Apache24\htdocs\cacti\cli\add_data_query.php on line 138
```

**To Reproduce**
 php -q add_data_query.php --list-data-queries

**Expected behavior**
expected to return a list of available data queries

**Screenshots**
none

**Desktop (please complete the following information):**
cygwin on windows, command line

**Additional context**

getSNMPQueries() is a function of api_automation_tools.php but this file hasn't been included in add_data_query.php

If I add the following line:
    require_once($config['base_path'] . '/lib/api_automation_tools.php');
then add_data_query.php seems to operate as expected and doesn't throw a fatal error. 

```
$ php -q add_data_query.php --list-data-queries
Known SNMP Queries: (id, name)
1       SNMP - Interface Statistics
2       Unix - Get Mounted Partitions
3       Net-SNMP -  Get Monitored Partitions
4       SNMP - Get Mounted Partitions
5       SNMP - Get Processor Information
6       Net-SNMP - Get Device I/O
```

**Comment by netniV** [comment]
This is now in the main development code, please check and close if issue is resolved.
