### ISSUE TITLE
Memory leak in jQueryUI causing TimeZone dropdown to become progressively slower every time it's opened

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#2454]
**Describe the bug**
When editing a device, you have the ability to select the timezone that you are in. Currently, the list appears to be unlimited so takes a long time to display and often requires multiple clicks.

**To Reproduce**
1. Go to Console -> Sites
2. Click on a site to edit it
3. Scroll down to 'TimeZone' and click the combo box

**Expected behavior**
The box should use the same auto filter logic as the device name list to make it appear faster.

**Screenshots**
This was the quickest I got it to appear, othertimes I've had to wait up to 30 seconds.

![timezone](https://user-images.githubusercontent.com/9052188/53329976-4d79b980-38e5-11e9-85b0-40edcebfe2c1.gif)

**Comment by cigamit** [comment]
I am unable to reproduce this.  I have verified that the 'Site' page is using the drop_callback method, so it should be performing well.  Use the browsers debug network tab to find the source of the slowdowns.  The timezone table is relatively small and should respond almost instantaneously.

**Comment by netniV** [comment]
It wasn’t the sites page, it was editing a device.

**Comment by cigamit** [comment]
What plugin is that coming from?  Is it the GPS Maps?

**Comment by cigamit** [comment]
It's not GPS Maps either.  Are you sure?  It has to be a plugin.

**Comment by netniV** [comment]
Hmm, let me see if it's a plugin.

**Comment by netniV** [comment]
You know what, my bad, it is sites not devices.  On my dev box I seem to have like 5 or 6 entries.  However, on a live server, there are a lot more.  Clicking the dropdown results in the following (each line is a click):

1. seems relatively fast
2. nothing happens
3. seems slower
4. nothing happens
5. quite slower
6. nothing happens
7. appears same as 5

![image](https://user-images.githubusercontent.com/9052188/53555816-99716c00-3b3a-11e9-8215-cd37a35ac026.png)

Looking at the network speeds, it's not that slow so makes me wonder if it is another nice "event/jqueryui" bug where it leaks something on Chrome.
