### ISSUE TITLE
Weird bug when device stays online, but doesn't respond to SNMP anymore

### ISSUE THREAD

**Issue by hmorandell** [Cacti/cacti#2458]
**Describe the bug**
I have a series of routers which work with SNMP, but they have a bug and suddenly they do not respond via SNMP anymore. So I get a timeout and no data is collected.
They still respond via PING. Now the strange thing comes up:

my standard Availability Check is: "PING AND SNMP". Obviously, when the device is not responding at SNMP request anymore, I get the device signed ass "DOWN". 
When I change the availability mode from "PING AND SNMP" to "PING OR SNMP", the expected behaviour should be that the device is marked as UP again and the SNMP data is collected the next time the router is restarted.

What happens now is that Cacti still gives me the device in DOWN state, and the POLLER is running made, increasing poller time from average 29seconds to 59s seconds producing all the time log errors for Spine timeout (I have 1 Minute poller interval).

![image](https://user-images.githubusercontent.com/7601690/53429275-95cfcf00-39ec-11e9-9f9b-2f3e487579ed.png)

The problem get fixed, and poller runtime back to normal, as soon as I delete this device! It sound strange, but that what happens and it took me a couple of hours to find out... 
Anyone else having a similar problem? The router I wrote before does respond at ping, tested from CLI from my cacti server installation, just for info!

**Comment by netniV** [comment]
You didn't fill in all the other important information in your bug report, such as PHP, OS, etc.

**Comment by hmorandell** [comment]
Sorry - you're right:

```
Ubuntu Linux 2016-04 LTS
PHP version 7.0.33-0ubuntu0.16.04.1
MariaDB: 10.0.38-MariaDB-0ubuntu0.16.04.1
Cacti: 1.2.1
Spine: 1.2.1
```

hope that's it. One more thing I forgot to mention before: this strange behviour started when changing availability method from "PING AND SNMP" to "PING OR SNMP". Before when I had "PING AND SNMP" Cacti simply showed me the device in down status, but didn't have this starnge behaviour with the Spine timing out for each Cycle which only happened when I switched the availability method to "PING OR SNMP"

**Comment by cigamit** [comment]
The OR option is not for the faint of heart.  I would NEVER use it.  Someone asked for it years ago.  It makes no sense in my opinion.

But if using spine and NOT cmd.php with a reasonable timeout and thread count, you can still scale using it, though you will get issues.

My advice, don't use the OR option.

**Comment by hmorandell** [comment]
Ok I'll change it and keep in mind of that weird behaviour.
I close this question, just one more thing.: if you consider the Or option never to be used and only integrated because someone asked once for it, wouldn't it be better to get rid of this settings or at least mark them as obsolet?

**Comment by jdcoats** [comment]
I can confirm this and I do think it is a bug. If I have a host that is up but snmp stops responding It should not hang up spine an additional 40secs+ no matter if it is set to AND or OR. It should still use the snmp timeout specified. If set to OR the timeout is ignored and spine hangs there. If set to AND the snmp timeout is adhered to. The OR specification is very useful in that we do not necessarily want to be notified that a host is down when snmp crashed or stops for another reason.

**Comment by jdcoats** [comment]
Here is an polling illustration when switching 1 device between AND/OR where a single device will hang up spine if set to OR. snmp timeout is 2000

``
2019/03/07 11:58:54 - SYSTEM STATS: Time:51.8794 Method:spine Processes:1 Threads:50 Hosts:1926 HostsPerProcess:1926 DataSources:34824 RRDsProcessed:0
2019/03/07 11:57:06 - SYSTEM STATS: Time:4.7844 Method:spine Processes:1 Threads:50 Hosts:1926 HostsPerProcess:1926 DataSources:34824 RRDsProcessed:0
2019/03/07 11:56:06 - SYSTEM STATS: Time:5.0011 Method:spine Processes:1 Threads:50 Hosts:1926 HostsPerProcess:1926 DataSources:34824 RRDsProcessed:0
2019/03/07 11:55:51 - SYSTEM STATS: Time:49.8212 Method:spine Processes:1 Threads:50 Hosts:1926 HostsPerProcess:1926 DataSources:34824 RRDsProcessed:0
```

**Comment by netniV** [comment]
What are your SNMP and Ping timeouts set to for the given device?

**Comment by jdcoats** [comment]
snmp timeout is 2000 and ping is udp 400 but that doesn't really matter, If you try to reproduce i bet it will be apparent. 
Take a ping and snmp device and stop snmp and you will see spine continue as expected but if you then change that device to ping or snmp then spine will hang up.
Even easier take a ping only device and change it to ping or snmp and watch spine hang on it.

**Comment by netniV** [comment]
What are your retries for both?

**Comment by jdcoats** [comment]
1
