### ISSUE TITLE
ss_host_disk.php attempts to return an empty array instead of a string

### ISSUE THREAD

**Issue by jdcoats** [Cacti/cacti#2459]
```
2019/02/26 12:19:36 - CMDPHP PHP ERROR NOTICE Backtrace:  (/scripts/ss_host_disk.php[11]:CactiErrorHandler())
2019/02/26 12:19:36 - ERROR PHP NOTICE: Array to string conversion  in file: /var/www/localhost/htdocs/cacti/scripts/ss_host_disk.php  on  line: 11
```

**Comment by netniV** [comment]
You should learn the correct formatting for log/code entries using three backticks ``` (see https://github.com/Cacti/documentation/blob/develop/Standards-Documentation.md for examples). It would save me having to keep editing your posts repeatedly 👍 

You also haven't stated your cacti version (which I know we ask for all the time but that's because of the number of different users and the fact you could have changed it or be on a different server).

This is now resolved in the main development code, please check and close if issue is resolved.

**Comment by jdcoats** [comment]
1.2.2 dev

**Comment by jdcoats** [comment]
I wont make you edit my posts anymore, thanks for pointing out the correct way to handle it.

**Comment by netniV** [comment]
If you hadn't already noticed, download the latest ss_host_disk.php from development and it should resolve this issue.
