### ISSUE TITLE
Data Source Deletion Greyed Out

### ISSUE THREAD

**Issue by reubenfarrelly** [Cacti/cacti#246]
I have a handful of data sources which I would like to delete.  These data sources do not have any Graphs associated with them (yet).

I would have expected I can go into Management -> Data Sources, choose 'Delete' from the action list at the bottom of the page and then select the sources I want to delete (and then Go).

However as soon as I select the Delete option, all of the checkboxes for each data source are greyed out and I can no longer select any Data Sources at all.

The only workaround for this is to create a new Graph, associate the Data Source and then delete the graph (as the system then asks if I wish to delete the data source as well).

This was a clean install of Cacti-1.0.0 .

**Comment by cigamit** [comment]
This is a feature.  We do not allow the removal of Data Sources as long as there are Graphs using them.  It's better if you Delete the Graph and take the Data Source with it.  I hope this helps.
