### ISSUE TITLE
Plugin dependency check during upgrade

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#2461]
**Is your feature request related to a problem? Please describe.**
When upgrading a plugin, you can easily upgrade to a version that requires a higher level of the core of cacti or dependency plugin without realising (see https://github.com/Cacti/plugin_thold/issues/261 as an example though others have come before it).

**Describe the solution you'd like**
When a plugin's version no longer matches the INFO file, the dependencies should be checked and if not met, the plugin disabled with an email to the primary admin.

**Comment by cigamit** [comment]
Just generating a warning message and disabling will trigger the admin notification.  Should be enough.

**Comment by cigamit** [comment]
@netniV, this is like the one remaining bug before 1.2.3.  Are you working on it right now?

**Comment by netniV** [comment]
I'm going to move this to 1.3 since it will be new functionality rather than fixing a bug as it has always been operating the existing way.

**Comment by netniV** [comment]
Whilst looking into this, I think there is a problem with being able to implement it.  The issue with this is that most plugins do their own handling of upgrade detection. the core knows nothing of this or that it is even occurring.
