### ISSUE TITLE
Cacti SNMP function removing data from string

### ISSUE THREAD

**Issue by arno-st** [Cacti/cacti#2462]
In my country, like many other, we have ' (single quote) in city state etc.
So as snmp provide a fields for location, and doing a geocoding of it to be able to display on a map, I need that the location on the device is correct and given back to cacti as it should be.

So I have in the past a problem with the snmp get function because cacti forat the return string in some way, that mean didn't give back to the caller (program, plugin or whatever) the result as it was receive by snmp. The result that I had to rewrite a whole snmp library so my plugin was able to receive the value as it should without false interpretation by cacti.

And again Its look like cacti (developer) by the library decide that the string has to be represented in some way that is not reflecting the truth !

Either way or cacti allow plugin and give to the plugin the value as it read, or cacti (developer) doesn't allow plugin at all.
But returning false value is wrong.
so here is the wrong code:
in lib/snmp.php you filter the string receive from an snmp query and filter it:
714:
        /* remove ALL quotes, and other special delimiters */
        $string = str_replace(array('"', "'", '>', '<', "\\", "\n", "\r"), '', $string);

And I need single quote, or double quote, and you souldn't remove it.
The program calling the snmp.php library should take care of the presentation it need, but in now way cacti should decide (the developer in this case).

**Comment by netniV** [comment]
So I appreciate that English may not be your first language so I'm going to post what I believe you are after?

You need a method of being able to hook the raw value without any manipulation from Cacti?  (the issue being that half the time, we do have to interpret what comes back such as Hex-STRING etc).

The strange thing here is that we recently had an issue were strings were containing quotes - see https://github.com/Cacti/plugin_monitor/issues/77

You believe that given the line of code above, it is removing that for you.  Is that just with that one function or with the other SNMP functions too?

**Comment by netniV** [comment]
OK so this was done 14 years ago in response to a bug report:
```
commit f7b641537efc59c8e6238510fe1bc0051ee0f09c
Author: Ian Berry <iberry@cacti.net>
Date:   Sat Jun 19 18:17:32 2004 +0000

    strip single quotes from snmp descriptions (bug#0000175)


    git-svn-id: svn+ssh://repo.cacti.net/var/data/svnroot/cacti/trunk/cacti@1599 860744bd-22fc-0310-8c96-e9fe5004b5ca

diff --git a/lib/snmp.php b/lib/snmp.php
--- a/lib/snmp.php
+++ b/lib/snmp.php
@@ -127,2 +127,2 @@
        $string = str_replace("\"", "", $string);
-
+       $string = str_replace("'", "", $string);
```

**Comment by netniV** [comment]
Just in case you are thinking that may not be the same one, it was optimized last may in a7e3a76e00907403ff7058ddc8ca3a40778c4ba8

**Comment by netniV** [comment]
This was the original report by user 'Bookmarc1':

```
When I list the interfaces of a Cisco PIX in the "New Graph" page, the description doesn't appear in the table.

A PIX interface description looks like this :
PIX Firewall 'inside' interface

The single quotes seem to be the problem. A solution to this is to add the following line in lib/snmp.php

$string = str_replace("'", "", $string); 

This as been posted before on the forum. Just making sure it is merged in the next version.
Thx !
```

**Comment by netniV** [comment]
OK so `cacti_snmp_get()` tends to assume that you are dealing with numeric data.  What you probably want is `cacti_snmp_get_raw()`.  If you try that, you should be happier.

**Comment by arno-st** [comment]
Yes you understand correctly my problem/request!

And ok yes cacti_snmp_get_raw is a solution, I have to do some filtering.
But That I'm think I should do.

thanks
