### ISSUE TITLE
Manual data source creation is broken

### ISSUE THREAD

**Issue by tosiara** [Cacti/cacti#2466]
**Describe the bug**
Manual data source creation is not working as it worked in previous version

**To Reproduce**
1. Go to Settings/General/Other Settings
2. Set "Graph/Data Source Creation Method" to "Advanced"
3. Go to Management/Data Sources
4. Create a new datasource
5. After save the new datasource is not on the list
6. However after multiple tries I found that multiple data sources have been created with the same name
7. rrd file also created and being updated, and contains valid data

**Expected behavior**
The data source should have been created and visible immediately in the list. This worked in 1.1 versions for sure

**Screenshots**
![image](https://user-images.githubusercontent.com/3600973/53554635-de9c9a80-3b48-11e9-8340-ad476bba47e8.png)

Video of a test: [cacti.zip](https://github.com/Cacti/cacti/files/2914196/cacti.zip)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser: Chrome

**Cacti version**
 - Version: 1.2.2, latest master

**Comment by cigamit** [comment]
This was due to a bug in our Caching algo that did not properly cache host_id 0 entries in the permissions for a user.  Can you please download the updated lib/auth.php, then logout and back in again and see if you can reproduce it?

**Comment by tosiara** [comment]
Made git pull:
```
$ git rev-parse HEAD
ecfded4734ad56b3da8160c9a54aa7bfee0da16e
```
So I'm on the latest `develop`
Logged out, restarted Apache

Seems not resolved. Still, don't see all my created Data Sources. Tried to create a new one - did not appear, but Graph is able to pick it up

**Comment by cigamit** [comment]
Okay, where is it missing, it's the Data Source list right?  Is it associated with a device, or to device 'None'?

**Comment by tosiara** [comment]
It is missing in the Data Source List: `/cacti/data_sources.php`
Device is "Local Linux Machine" which was there as default right after installing cacti. Template is "None". Data source is not in the list, but I can edit it by entering direct URL: `/cacti/data_sources.php?action=ds_edit&id=12`

**Comment by netniV** [comment]
Try running the following for me:
```sql
SELECT DISTINCT
   dl.id,
   gti.local_graph_id, 
    (CASE WHEN gti.id IS NOT NULL THEN 0 ELSE 1 END) AS Deletable, 
    (CASE WHEN dtr.id IS NOT NULL THEN 'Found' ELSE 'Missing' END) AS data_template_rrd, 
    (CASE WHEN gl.id IS NOT NULL THEN 'Found' ELSE 'Missing' END) AS graph_local, 
    (CASE WHEN gti.id IS NOT NULL THEN 'Found' ELSE 'Missing' END) AS graph_template_item, 
    (CASE WHEN gtg.id IS NOT NULL THEN 'Found' ELSE 'Missing' END) AS graph_template_graph, 
    gtg.title, gtg.title_cache
FROM data_local AS dl
LEFT JOIN data_template_rrd AS dtr
ON dl.id=dtr.local_data_id
LEFT JOIN graph_templates_item AS gti
ON gti.task_item_id=dtr.id
LEFT JOIN graph_local AS gl
ON gl.id = gti.local_graph_id
LEFT JOIN graph_templates_graph as gtg
ON gtg.local_graph_id = gti.local_graph_id
WHERE dl.id = ?
```
Replace the question mark with your DS id.

**Comment by tosiara** [comment]
```
$ mysql -u cacti -p cacti < cacti.sql
Enter password:
id      local_graph_id  Deletable       data_template_rrd       graph_local     graph_template_item     graph_template_graph    title   title_cache
10                5            0                  Found              Found            Found              Found                    ds            ds
```

**Comment by cigamit** [comment]
Should be fixed now.  Give it a shot.  If fixed, just go ahead and close.

**Comment by tosiara** [comment]
Yes, I can confirm, the issue is resolved in the latest develop branch. Thanks
