### ISSUE TITLE
Automation - Graph rules - filtered and unfiltered matching object problem

### ISSUE THREAD

**Issue by xmacan** [Cacti/cacti#2467]
I have few conditions in Graph creation criteria. If I enable Show matching objects I see blue coloured list of "affected" object. There are objects which doesn't  meet the conditions (maybe I have wrong conditions, I tried more combinations, but it isn't important now).  If is used Matching object filter, the result is different. 

**To Reproduce**
1. Make similar Graph rules
2. Click "Show matching objects"
3. You will see result
4. Use Matching Objects filter and input IP address of any matching object
5. You will see different result (less rows, maybe only one)
6) Result 3. and 5. should be the same

**Expected behavior**
Filtered and unfiltered result should be the same.

**Screenshots**
Screenshot 1 - conditions
![screenshot_2019-02-28 console - graph rules - edit](https://user-images.githubusercontent.com
/26485719/53558478-6635d980-3b48-11e9-8acf-630912056aa6.png)

Screenshot 2 - unfiltered
![screenshot_2019-02-28 console - graph rules - edit 1](https://user-images.githubusercontent.com/26485719/53558509-6fbf4180-3b48-11e9-9ff4-a2ec98d0a2a1.png)

Screenshot 3 - filtered
![screenshot_2019-02-28 console - graph rules - edit 2](https://user-images.githubusercontent.com/26485719/53558530-7b126d00-3b48-11e9-8f60-9eb8d2e81c2f.png)

**Desktop (please complete the following information):**
Ubuntu 18.10
Firefox
65

The same behavior was in 1.1.38

**Comment by netniV** [comment]
When creating a new issue, try to follow the template we have provided as it helps maximise the details that are presented to us which helps.  Also, I would have created these as two separate issues since you are even considering them two separate ones.  

For the second part, you haven't really given any details as to why that is a problem, you are changing a search filter field and it correctly updates the page as a result.

**Comment by xmacan** [comment]
sorry, I will make two issues better :-)

**Comment by netniV** [comment]
You could have just edited this one, then created a second ;-)

**Comment by xmacan** [comment]
This issue is fixed

**Comment by cigamit** [comment]
Pretty sure this is fixed in #2469 now.

**Comment by xmacan** [comment]
Maybe I wrote it incorrectly. In this issue is problem with filtered/unfiltered result. I updated issue, please see screenshot 2 and 3. In both cases I expected 6 objects but with filter I got only one.

**Comment by xmacan** [comment]
It isn't resolved in #2469, it is another problem. Please read issue again I specified it better
