### ISSUE TITLE
Automation - Graph rules - matching object filter - unexpected redirect

### ISSUE THREAD

**Issue by xmacan** [Cacti/cacti#2469]
**Describe the bug**
If I use this filter and change and try to change object number, I'm redirected to another page

**To Reproduce**
1. Go to automation - > graph rules, choose one
2. Enable "Show matching objects"
3. Use filter "Matching objects" (for example insert any hostname from matching objects)
4. in the same filter try to change Objects from default to any number
5. You will be redirected to Automation -> Graph rules

**Expected behavior**
After step 4 I'm expecting stay in the same page and change only filter result. But I'm redirected to list of Graph rules and data from Matching object filter are filled in this form.

**Screenshots**
Screenshot 1 - changing object number
![screenshot_2019-02-28 console - graph rules - edit 3](https://user-images.githubusercontent.com/26485719/53559372-3ee00c00-3b4a-11e9-9d68-68b83dc67e1e.png)

Screenshot 2 - redirect to another page
![screenshot_2019-02-28 console - graph rules - edit 4](https://user-images.githubusercontent.com/26485719/53559408-50c1af00-3b4a-11e9-86b5-6ae5591a416f.png)

**Desktop (please complete the following information):**
Ubuntu 18.10
Firefox 65

Same behaviour in 1.1.38

**Comment by cigamit** [comment]
All fixed up.  Close is satisfied.
