### ISSUE TITLE
Hosts without Downed Device Detection or with no Uptime do not appear in Tree Available Devices

### ISSUE THREAD

**Issue by reubenfarrelly** [Cacti/cacti#247]
I have two devices currently configured which do not show up in the Tree Available Devices list.

One is a VMware ESXi host which currently has no Data Sources, but is pollable and is configured with SNMP in Cacti.
The other is a 'fake' host I have that is used to collect Weatherstation Data.  This 'host' is not real, but it has data sources and graphs associated to it as it is used to poll my weatherstation and scape data which I then graph.  So it has a Downed Device Detection set to 'None'.

What is in common to these two devices is that both are showing up with Uptime of N/A.  The ESXi host is up but has no data sources, the weatherstation host will never show up as it is not a real host.

These two devices should be showing up as selectable for the Tree View, if for no other reason than I want to add them to a Tree View now even though I have not yet finished adding graphs for them.  The weatherstation 'device' is actually gathering data and producing graphs right now but cannot be added to any tree as it does not show up in the Tree View.

This is with Cacti-1.0.0 on a Gentoo Server.

**Comment by cigamit** [comment]
Are you using spine to collect data?

**Comment by reubenfarrelly** [comment]
No - not using spine (yet).

**Comment by cigamit** [comment]
Please keep in mind that the device list is controlled using autocomplete and will only show the top 20 or matching devices.  Try to search for the missing devices.  I'm thinking you will find them.

**Comment by reubenfarrelly** [comment]
That accounts for the weatherstation device - which I have now added successfully.  Thanks.

Only 19 devices are showing up in the Available Devices list, not 20 (I have 21 hosts in total to add that tree).  The weatherstation device above was found by doing a search.

The remaining device (Cisco UCS, net-snmp type) does not show up in a search for either it's hostname nor it's friendly name.  This one is the one that is showing a status of Unknown, even though it is pollable and responding to ICMP Pings and an SNMP get from the Management -> Device list.  As of now it has no data sources or graphs - it's the only device which does not have any (yet - but it will later on).

**Comment by cigamit** [comment]
After a code review, I found an issue with an API function, and found a few form issues when searching for graphs and devices.  It should work now, and be just slightly faster at rendering.  Thanks for catching, and taking the time to report this issue.

**Comment by reubenfarrelly** [comment]
Much better.  Confirmed as fixed now - thanks.
