### ISSUE TITLE
Don`t work escape brackets in search graphs 

### ISSUE THREAD

**Issue by maxstech** [Cacti/cacti#2470]
Hello,
use cacti 1.2.1
Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-43-generic x86_64)
PHP 7.0.32-0ubuntu0.16.04.1

Found the problem with finding graphs that contain brackets in title
![cacti escape brackets](https://user-images.githubusercontent.com/47040342/53563069-0ea56700-3b64-11e9-9068-8efc0f84df74.jpg)

**Comment by maxstech** [comment]
![cacti escape 2](https://user-images.githubusercontent.com/47040342/53563573-7ad49a80-3b65-11e9-9703-e4cfff98e491.jpg)

**Comment by netniV** [comment]
That is because most search fields are regular expressions.  As such, using a brackets is considered a capture group.  If you wish to search on brackets, you must prefix them with a slash to escape them.
