### ISSUE TITLE
REGEXP_SNMP_TRIM does not handle Gauge fields properly

### ISSUE THREAD

**Issue by fbellet** [Cacti/cacti#2474]
I think commit e9800f03 changed the REGEXP_SNMP_TRIM value in a way that now prevents it to correctly remove the "Gauge32:" prefix. Since this commit,  "gauge" without ":" is matched, and "32" remains in the resulting string

**Comment by netniV** [comment]
Thanks! Should be corrected in the latest development commit.

**Comment by fbellet** [comment]
oups, it looks like a typo in commit a32dfb6a: guage

**Comment by netniV** [comment]
💥

**Comment by netniV** [comment]
### Looks fine to me
(in 86e2e33a)
