### ISSUE TITLE
Unable to manually add Data Sources or Graphs

### ISSUE THREAD

**Issue by reubenfarrelly** [Cacti/cacti#248]
I have a quite specific use for a few hosts that I monitor, where I want to be able to poll for a specific OID on the host and graph it.  In many cases these are things like IP SLA tests I have running on a router.  The results of these SLA tests (often things like latency tests) are available via SNMP and I have with Cacti-0.8.8 been able to poll and add these and attach them to a host.

However in Cacti-1.0.0 there is no 'Add' option available to either the Management -> Data Sources nor the Management -> Graphs.  This makes the above exercise impossible.  I suppose I could create a whole lot of unique templates but most of the graphs are one-off OID's (I template everything else except the OID that I want to poll - but without the ability to Add Data Sources and Graphs even the OID cannot be added).

This functionality was in Cacti-0.8.8 so I suspect the Add option was omitted by accident in 1.0.0.

This is with Cacti-1.0.0 on Windows, with Chrome.  [NB all of the testing and bug reports I have submitted so far are with the Modern theme]

**Comment by cigamit** [comment]
This is a new setting under Setting -> General -> Other Settings -> Graph/Data Source Creation Method.  Set that to 'Advanced', and you will get that legacy feature back.
