### ISSUE TITLE
When upgrading past 1.1.34, upgrade attempts to drop a non-existing primary key

### ISSUE THREAD

**Issue by ycaoxa** [Cacti/cacti#2482]
**Mariadb version:**
[root@rtm73t ~]# mysql -V
mysql  Ver 15.1 Distrib 5.5.52-MariaDB, for Linux (x86_64) using readline 5.1

**version table in my ENV**
MariaDB [cacti]> show create table version;
+---------+-------------------------------------------------------------------------------------------------+
| Table   | Create Table                                                                                    |
+---------+-------------------------------------------------------------------------------------------------+
| version | CREATE TABLE `version` (
  `cacti` char(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 |
+---------+-------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

**Error as below:**

Upgrading from v1.1.31 (DB 1.1.31) to v1.1.34
++++-++++++++++++++++++++-+-++-+-++-+++-+++++++++-+-+++++-++x++
################################
[Fail]       -   DB Exec Failed!, Error 1091: Can't DROP 'PRIMARY'; check that column/key exists
+------------------------------+
ALTER IGNORE TABLE version DROP PRIMARY KEY

**Comment by netniV** [comment]
Apply this change to your local files and you should be OK: https://github.com/Cacti/cacti/commit/be50141315b1c474cbca33e9ad26cacc0ef9c110
