### ISSUE TITLE
Cacti Notification Reboot - possibility to ommit notifications by time range

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#2483]
**Is your feature request related to a problem? Please describe.**
Yes. When we upgrade firmware there is unneded mail notification. Those are everyday actions.

**Describe the solution you'd like**
Abbility to set date DATE_FROM and DATE_TO whitch notifications are going to /dev/null.

**Describe alternatives you've considered**
Abbility to set DATE_FROM and DATE_TO whitch notifications are sent.

**Comment by interduo** [comment]
Or it could be button like "one time restart - don't sent notification"

**Comment by netniV** [comment]
There is a plugin called Maint that would handle that for you I believe.  I don't know if it goes down to the host level.

**Comment by interduo** [comment]
If We need to use it fast as every day action we need two things:

1. Option in host form:
![expeted_1](https://user-images.githubusercontent.com/17087236/53742854-e38b8200-3e99-11e9-971e-f97e6d619df7.png)

2. Option in devices list form in dropdown menu:
![zrzut ekranu z 2019-03-04 16-23-05](https://user-images.githubusercontent.com/17087236/53743093-5b59ac80-3e9a-11e9-8ed1-3a7f75e2bec0.png)

**Comment by cigamit** [comment]
Both the notifications and the maintenance comes from plugins, not from base Cacti.  You should open a ticket on the particular plugins page instead.
https://github.com/Cacti/plugin_maint/

**Comment by interduo** [comment]
I didn't know about maint plugin. I created issue there. Thanks for helping me.

**Comment by netniV** [comment]
Rather than close and reopen, the issue should have been transferred really.

**Comment by interduo** [comment]
Is it possible with github to transfer issues between repositories?

**Comment by netniV** [comment]
Well, I certainly can.  But that doesn't mean just anyone can necessarily.

![image](https://user-images.githubusercontent.com/9052188/53746392-fc476800-3e98-11e9-84e7-28a14ef9def0.png)
