### ISSUE TITLE
Importing Template requires you to upload the same file after previewing

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#2485]
**Describe the bug**
When uploading a template, the default action is to preview to ensure that your template won't overwrite anything important.  However, if you are satisfied with the import, you must then return to the import screen, select your file and then upload it again.

**Expected behavior**
After previewing, there should be an option to import the template immediately.  This may be best to be disabled unless a checkbox has been ticked to confirm that the template is OK (especially if there is something being updates, not just exists/new).

**Comment by cigamit** [comment]
This is easier said than done in that the browser obfuscates the actual path.  So, even though we can save a path, we can never save the real path, which makes the attempt to short circuit this security measure impossible.  So, I suggest we close this bug.

**Comment by netniV** [comment]
I think we can circumvent that by storing the upload in a cache directory with a random name.  That way, we can then say to import that randomly named file safely after a preview.  If the file isn't imported, the cache cleanup routines can remove it if it's older than 30 minutes.

It also means that for larger templates you wouldn't need to upload twice, during which time you may have modified your template but not realised that you'd not previewed again.

If you were uploading without preview, that could follow the same uploading to a random name, but then jump straight to importing.

**Comment by cigamit** [comment]
Hmm, that might work.  Post 1.2.3 though.

**Comment by netniV** [comment]
I'd say make it a 1.3 think as we'll likely be starting on that soon.

**Comment by TheWitness** [comment]
This is resolved now.
