### ISSUE TITLE
Allow Automation to update the device description based upon sysName

### ISSUE THREAD

**Issue by maxstech** [Cacti/cacti#2487]
Hello,
cacti 1.2.1 
Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-43-generic x86_64)
PHP 7.0.32-0ubuntu0.16.04.1

![current name](https://user-images.githubusercontent.com/47040342/53803458-daf88180-3f55-11e9-9808-7dad644b467b.jpg)

![new name](https://user-images.githubusercontent.com/47040342/53803468-e0ee6280-3f55-11e9-913c-8e6ae12cfa97.jpg)

![manual name](https://user-images.githubusercontent.com/47040342/53803476-e5b31680-3f55-11e9-88ac-6f49141bc5d9.jpg)

To update manually for me not option, all devices (about 1500) and graphics I receive using automation rules

**Comment by cigamit** [comment]
This is a pretty interesting feature request.  We will have to put it on the roadmap.  We have a pretty large backlog.  Some help would be appreciated.

**Comment by bmfmancini** [comment]
Glad I found this on the roadmap !
This would be really useful !

**Comment by bmfmancini** [comment]
Coming back to this I'm willing to send in a more of a donation for this feature  really need it

**Comment by TheWitness** [comment]
By default, I think it will use the sysName if it's SNMP and the reverse DNS does not resolved to one.

**Comment by EmilAndersson-SE** [comment]
Wow, we would appreciate this alot. Many operators, re-using IP-adresses of switches and servers and I can tell you, i'm the only one here who maintaining our Cacti-machine but everybody want to use it as read-only user.

**Comment by netniV** [comment]
So we should probably spec out properly what fields needs updating and under what circumstances.  After all, what happens if you have an IP conflict and a temporary device has a been placed onto the network?  That would really mess with things.

Also, if you are update the name/description, should it really be using the same graphs/templates since that IP may be a different device type.

**Comment by maxstech** [comment]
p.s the problem of temporary devices should be controlled by the admin.

new graphs equal for new hostname and old device(old ip) but old graphs saves. 
new device (old ip) -  create but new graphs.

**Comment by TheWitness** [comment]
1) Update table schema
2) Provide an Option, default to off
3) Log a Warning when the change is made
