### ISSUE TITLE
Parts of the graphs are missing

### ISSUE THREAD

**Issue by kaba1ah** [Cacti/cacti#2488]
Hello,

Latest Debian Stretch 9.8 (with all packages being installed via standard Debian repositories) with Cacti 1.2.1.

`$ uname -a`
`Linux SRVMON01 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux`

I'm having some issues with parts of some graphs missing like the ones below:

![untitled](https://user-images.githubusercontent.com/39156163/53814393-d3d67100-3f5f-11e9-8d5b-5d4343bc3979.png)

![untitled1](https://user-images.githubusercontent.com/39156163/53815009-16e51400-3f61-11e9-9274-1e53c35b8722.png)

I'm experiencing this issue with 8-10 graphs only (out of ~1000 graphs) on different devices (network switches).

No errors in the logs, and recreating doesn't help.

Any hints would be greatly appreciated.

Thank you.

**Comment by netniV** [comment]
Do you see anything about timeouts or exceeding polling time? What are your polling stats?

**Comment by kaba1ah** [comment]
No timeout errors in /var/www/html/cacti/log/cacti.log file (I think this is the right one).

Here is my crontab:

`*/5 * * * * /usr/bin/php /var/www/html/cacti/poller.php > /var/www/html/cacti/log/cron.log 2>&1`

I've just reduced it to run it every 1 min.

Here are stats:

`2019/03/05 16:48:07 - SYSTEM STATS: Time:6.3422 Method:spine Processes:1 Threads:1 Hosts:20 HostsPerProcess:20 DataSources:1362 RRDsProcessed:794`

What is a bit strange is that those graphed interfaces are 10Gb, and I don't see anything higher than 1Gb in the graphs, however if I occasionally look at the interface utilization I see 2-3GB load:

`Rate info:`
`Input 1987.031928 Mbits/sec, 168564 packets/sec, 20.14% of line-rate`
`Output 16.307388 Mbits/sec, 19361 packets/sec, 0.19% of line-rate`

All graphs are set to 'In/Out Bits (64-bit Counters)', and I do have other monitored interfaces (on the same switch) reporting correctly the load higher than 3-5GB.

**Comment by gadzet21** [comment]
Hey,
Try to run in console: 
rrdtool tune ../cacti/rra/xxx.rrd --maximum inbound:343597383680
rrdtool tune ../cacti/rra/xxx.rrd --maximum outbound:343597383680

Replace the directory and name (inbound, outbound) with yours.

I have the same problem in the cacti version 0.8.7g

Jacek

**Comment by cigamit** [comment]
If this was an upgraded system, it's likely from that system.  We have addressed this problem in Cacti 1.2.2 a bit differently.  However, there are cases where the reported ifSpeed and ifHighSpeed are not reported correctly by SNMP.  So, in those cases, there is not much we can do, you will have to hand tune.
