### ISSUE TITLE
Data Source Info suggests commands RRDTool can't honor

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#2491]
**Describe the bug**
There was a datasource with a number of issues most of which the tune sorted out.  But it also showed, and still does, the following:
```
Required RRD step size is '60'
RRD maximum for Data Source 'traffic_in' should be 'NaN'
RRD maximum for Data Source 'traffic_out' should be 'NaN'
File RRA '0' has same CF/steps (AVERAGE, 1) as '1'
File RRA '1' has same CF/steps (AVERAGE, 1) as '0'
File RRA '9' has same CF/steps (MAX, 1) as '10'
File RRA '10' has same CF/steps (MAX, 1) as '9'
/usr/bin/rrdtool tune /usr/share/cacti/rra/501/10287.rrd --maximum traffic_in:NaN
/usr/bin/rrdtool tune /usr/share/cacti/rra/501/10287.rrd --maximum traffic_out:NaN
```

However, running the tune commands failed because RRDTool 1.6 does not support NaN as a valid value.

**Expected behavior**
The NaN should really be U

**Comment by cigamit** [comment]
Additionally, the Max values are being incorrectly calculated in some cases.  One user reported an ifHighSpeed of 2000, and Cacti was recommending a maximum values of 1000.
