### ISSUE TITLE
Can't find Preview/Treeview under Graph tab in some themes, such as paw, paper-plane in 1.2.2

### ISSUE THREAD

**Issue by YongBoLiu** [Cacti/cacti#2495]
Is it a design, or a bug? I am not sure.

**Comment by netniV** [comment]
Looks good to me.  Are the permissions correct?

![image](https://user-images.githubusercontent.com/9052188/54016950-73704b00-417c-11e9-88ba-ab62c5c924fc.png)

**Comment by YongBoLiu** [comment]
Got it. Thanks @netniV .
