### ISSUE TITLE
Graph URL's missing either graph_start or graph_end but not both result in both taking defaults

### ISSUE THREAD

**Issue by standaniel** [Cacti/cacti#2497]
We use 0.8.8c

We take graphs links into a html which refreshes each 10 seconds, the link is:

http://site-name/graph_image.php?local_graph_id=394&rra_id=0&graph_height=55&graph_width=370&graph_nolegend=true&graph_start=-3600

graph_start=-3600 - this gives us the last hour updated graphs - so we have the last hour graphs refreshed every 10 seconds.

When upgrading to 1.2.2 graph_start=-3600 does not work and we only get last 24hours, no matter what we try, any idea why?

**Comment by cigamit** [comment]
Add '&graph_end=-300" or "&graph_end=-60" depending on your poller interval and this will work.  In the mean time, we'll get this fixed.

**Comment by cigamit** [comment]
@standaniel, should be fixed now.  Update lib/rrd.php.  If satisfied, please close the issue.

**Comment by standaniel** [comment]
fixed, indeed.
