### ISSUE TITLE
SNMP::walk(): Fatal error: Failure in sendto (Invalid argument) in file snmp.php line 437 & 474

### ISSUE THREAD

**Issue by jdcoats** [Cacti/cacti#2501]
The below errors came up a few times during php poller_reindex_hosts.php --id=all
```

2019/03/09 15:33:47 - ERROR PHP WARNING: SNMP::walk(): Fatal error: Failure in sendto (Invalid argument) in file: /var/www/localhost/htdocs/cacti/lib/snmp.php on line: 437
--
2019/03/09 15:33:47 - CMDPHP PHP ERROR WARNING Backtrace: (/cli/poller_reindex_hosts.php[141]:run_data_query(), /lib/data_query.php[103]:query_snmp_host(), /lib/data_query.php[737]:cacti_snmp_session_get(), /lib/snmp.php[474]:SNMP->get(), CactiErrorHandler())
2019/03/09 15:33:47 - ERROR PHP WARNING: SNMP::get(): Fatal error: Failure in sendto (Invalid argument) in file: /var/www/localhost/htdocs/cacti/lib/snmp.php on line: 474

```

**Comment by netniV** [comment]
That would usually mean you have an invalid hostname/ip address.

**Comment by jdcoats** [comment]
cant imagine what that would be but I'm looking.

**Comment by jdcoats** [comment]
so if I had an invalid hostname/ip address then it would be "not up" correct? I do have a few down and disabled devices but none are invalid as far as I can tell.

**Comment by cigamit** [comment]
What php version is that?  Is php-snmp installed?  Please advise.

**Comment by jdcoats** [comment]
PHP 7.1 and yes php-snmp is built in.

**Comment by cigamit** [comment]
@jdcoats, you guessed it, that's the issue.  It's a PHP bug.  This should be a warning, and not a fatal error in php-snmp.  Someone needs to open a bug in the PHP bug tracker.  If you open it, could you post the link and bug number here?
