### ISSUE TITLE
Improve Data Source Statistics performance by using RRDtool functions to calculate average and peak values

### ISSUE THREAD

**Issue by vishnubraj** [Cacti/cacti#2505]
**Describe the bug**
poller_boost process is consuming 100% CPU utilisation  and rrdtool is consuming 1.3 Gb to 3.3Gb  memory  is this expected

Cacti Version: 1.2.2
php version: 7.1
rrdtool version1: 1.7.0 

![Screenshot 2019-03-11 at 6 38 36 PM](https://user-images.githubusercontent.com/11851188/54126391-70e84c80-442d-11e9-8892-724ae707a39a.png)

Below is my poller boost config 

![Screenshot 2019-03-11 at 6 45 03 PM](https://user-images.githubusercontent.com/11851188/54126591-ee13c180-442d-11e9-8e76-01b680b19554.png)

**Desktop (please complete the following information):**
 - OS: Centos
 - Browser Chrome
 - Version

**Comment by cigamit** [comment]
please strace the pid with 'strace -tt -s 2500 -p pid'.  Post some output.

**Comment by vishnubraj** [comment]
[cacti_strace.txt](https://github.com/Cacti/cacti/files/2955497/cacti_strace.txt)


Please find the attached file..

**Comment by cigamit** [comment]
This boost is running the daily aggregation for DSSTATs, which you have enabled.  How long does it run?  What disk type do the RRDfile stay on?  If it's flash or ssd, I would not be surprised that during this boost run, should be like once a day, that the cpu of the php process is pegged at 100% for the duration of that run.

**Comment by cigamit** [comment]
By the way, looking at the code, written by others, when it was written, there were a number of functions that RRDtool did not perform, that may be better served by using some internal RRDtool functions.  This would reduce the PHP cpu consumption, and move that consumption to RRDfile.  It will also allow us to parallelize the process to spread out the CPU load.  Something that we can do as a feature enhancement.

**Comment by vishnubraj** [comment]
> This boost is running the daily aggregation for DSSTATs, which you have enabled. How long does it run? What disk type do the RRDfile stay on? If it's flash or ssd, I would not be surprised that during this boost run, should be like once a day, that the cpu of the php process is pegged at 100% for the duration of that run.

it runs for ~20mins.. if i run it in cli it completes it within seconds.. The RRD's are stored in SSD..

**Comment by vishnubraj** [comment]
@cigamit also this happens very often.. not once a day..

**Comment by cigamit** [comment]
I understand that after looking at more detail in the code.  How many rrdfiles do you have in your installation and how larger are they

```shell
cd /var/www/html/cacti/rra
ls -1 | wc -l
du -hs .
```

**Comment by vishnubraj** [comment]
```[FREE:vishnu:admin3@cacti1a.ams2 /var/www/cacti/rra]$ ls -l */  | wc -l
45662
[FREE:vishnu:admin3@cacti1a.ams2 /var/www/cacti/rra]$ du -hs .
31G	.
[FREE:vishnu:admin3@cacti1a.ams2 /var/www/cacti/rra]$ ```

**Comment by cigamit** [comment]
I'll see if I can build a prototype of the new method this weekend.  No promises though.

**Comment by cigamit** [comment]
@vishnubraj,

Okay, this has been resolved.  I would like to see from you the difference in performance between the version you are running, and the latest.  Just update poller_dsstats.php and lib/dsstats.php and compare.

**Comment by cigamit** [comment]
@netniV, should we be attempting the insert statement to attempt to create the grant?  Seems like SQL purists will kill us if we do that.  The emperor with no clothes.

**Comment by netniV** [comment]
@cigamit I think that comment was for a different issue.  I haven't even commented on this and I see no reference to an insert statement.

**Comment by vishnubraj** [comment]
Great Thanks @cigamit !!!

The performance is increased a lot. 

![cacti_graph_2](https://user-images.githubusercontent.com/11851188/54585272-a3063980-4a3f-11e9-8eb3-a8c2a097a47c.png)
![cacti_graph_37381](https://user-images.githubusercontent.com/11851188/54585282-a8fc1a80-4a3f-11e9-8823-daaa52413ddf.png)

**Comment by vishnubraj** [comment]
Cacti is throwing below errors in the log..

```

2019/03/19 06:45:03 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
--
2019/03/19 06:45:03 - ERROR PHP ERROR: Uncaught Error: Call to undefined function dsstats_poller_output() in /var/www/cacti/lib/poller.php:529 Stack trace: #0 /var/www/cacti/poller.php(676): process_poller_output(Resource id #65) #1 {main} thrown in file: /var/www/cacti/lib/poller.php on line: 529


```

**Comment by vishnubraj** [comment]
actually its not fixed.. i still see 100% CPU. but this time multiple process.. 
The file permission was wrong, thats why i got confused. Sorry for the confusion..

![Screenshot 2019-03-19 at 12 38 43 PM](https://user-images.githubusercontent.com/11851188/54586799-232e9e00-4a44-11e9-9448-6b0f5f57edf8.png)


![Screenshot 2019-03-19 at 12 40 55 PM](https://user-images.githubusercontent.com/11851188/54586849-41949980-4a44-11e9-94c9-eac1bbbcc246.png)


![cacti_graph_2_rra4](https://user-images.githubusercontent.com/11851188/54586859-48bba780-4a44-11e9-9960-fb0c51957cc0.png)

**Comment by cigamit** [comment]
I think that this is fine.  The fact that RRDtool is taking 100% is not a problem actually.  It's never going to get more efficient that it is today.  So, I think this is fine to close.

**Comment by vishnubraj** [comment]
@cigamit  does using rrdcached will solve this issue? any plans of adding it to cacti?
