### ISSUE TITLE
Poller not running , no graph appears

### ISSUE THREAD

**Issue by fadhilrajabian** [Cacti/cacti#2506]
have updated Cacti from 0.8.8 to 1.2.1 and I have also done a number of things below:

1. Rebuild poller Cache
2. Change the ownership and permission of / var / lib / cacti / rra / *
3. Setting the SNMP community on the host that I monitor

but what happens is that graph doesn't appear,

![image](https://user-images.githubusercontent.com/47592794/54174410-e3ead500-44b8-11e9-8a88-bf777af72292.png)

![image](https://user-images.githubusercontent.com/47592794/54174253-1ba54d00-44b8-11e9-901b-f5136896bc2f.png)

**Comment by cigamit** [comment]
What does your logs say?

Also, try "Troubleshooting >> Data Sources"
Change "Debugging" to "All" and select one of the Data Sources with issues.  Then select the Action "Run Check" and let it run.

**Comment by fadhilrajabian** [comment]
the logs say this : 
![image](https://user-images.githubusercontent.com/47592794/54177885-70e85b00-44c6-11e9-9a4e-0d5570528882.png)

after i run the result only like this : 
![image](https://user-images.githubusercontent.com/47592794/54179018-25d04700-44ca-11e9-8103-5c17aa708764.png)

and there is another log : 
![image](https://user-images.githubusercontent.com/47592794/54179054-40a2bb80-44ca-11e9-8f27-cffee708bfdd.png)

**Comment by cigamit** [comment]
Likely spine is broken.  Can you please run it by hand:

```shell
cd /usr/local/spine/bin
./spine -R -V 3 -S
```

**Comment by fadhilrajabian** [comment]
@cigamit 

the result is:

![image](https://user-images.githubusercontent.com/47592794/54247913-53220100-456d-11e9-872a-e12c7fe0c573.png)

**Comment by cigamit** [comment]
What is in your spine.conf?  What version of spine is this?  Does it match the Cacti version?  Until you solve this problem, your poller will not complete and you will get no data.  You can test the values in the spine.conf by runing the following from the server with spine:

```shell
mysql -ucacti -ppassword cacti
```

Replace 'password' with your password.  Until that works, spine won't work.

**Comment by fadhilrajabian** [comment]
i use spine 0.8.8f, is it problem?
![image](https://user-images.githubusercontent.com/47592794/54249545-2375f780-4573-11e9-9c89-d45e1de385bc.png)


This is my spine.conf
![image](https://user-images.githubusercontent.com/47592794/54249275-19072e00-4572-11e9-98b8-6544fa57e0a6.png)

mysql -ucacti -ppassword cacti 
-> i can connect to mysql using cacti user.
![image](https://user-images.githubusercontent.com/47592794/54249376-8dda6800-4572-11e9-939b-2aa36d18b7a1.png)

**Comment by cigamit** [comment]
```shell
DB_Host localhost
```

**Comment by cigamit** [comment]
or use the real hostname, but be prepared for a different permission denied message.  You can do the grant on the real hostname as well.  Just review the message you get from mysql and follow that hostname convention.

**Comment by fadhilrajabian** [comment]
@cigamit yes i try with localhost and ipaddress the result is still same.

**Comment by netniV** [comment]
Are you sure that mysql is definitely listening on that port?  Check the `netstat -an` to see if you can find the listening process.

**Comment by fadhilrajabian** [comment]
@netniV 
![image](https://user-images.githubusercontent.com/47592794/54265063-0a873980-45a7-11e9-89a3-6a9b1ff71e5c.png)

 this is mysql listen port

**Comment by netniV** [comment]
That appears to be listening on IPv6 only.

**Comment by fadhilrajabian** [comment]
@netniV so the port 3306 only for IPv6 ? how to add localhost or IPv4 for listen on 3306?

**Comment by fadhilrajabian** [comment]
@netniV now i add a shortcut for local host with 0.0.0.0 , but still cannot .
![image](https://user-images.githubusercontent.com/47592794/54273209-fb5cb780-45b7-11e9-80f2-f3f52699dcd7.png)

**Comment by cigamit** [comment]
That output is misleading.  It is listening for an IPv6, but the way the stack works it that it's still listening on IPv4.  It's just the way netstat works.  You can do a tcpdump when running the mysql command and see for yourself.  Verify with tcpdump and wireshark as to what is happening.  It has to be the grant.

**Comment by netniV** [comment]
Interesting coz on my system, I have an IPv4 listening port:

```
netstat -an | grep 3306 | grep "LISTEN"
tcp        0      0 0.0.0.0:3306            0.0.0.0:*               LISTEN
```

**Comment by netniV** [comment]
This would seem to agree with what you've said though it is also talking about windows as well. (learn something new every day)
https://superuser.com/a/733575/387788

> I've finally had time to dig into the mysql 5.6 source. Line 2405 of mysqld.cc seems to hold some answers.
> 
   ```
   /*
      For interoperability with older clients, IPv6 socket should
      listen on both IPv6 and IPv4 wildcard addresses.
      Turn off IPV6_V6ONLY option.
   
      NOTE: this will work starting from Windows Vista only.
      On Windows XP dual stack is not available, so it will not
      listen on the corresponding IPv4-address.
    */
   if (a->ai_family == AF_INET6)
   {
     arg= 0;
   
     if (mysql_socket_setsockopt(ip_sock, IPPROTO_IPV6, IPV6_V6ONLY,/* Line: 2405 */
                                 (char *) &arg, sizeof (arg)))
     {
       sql_print_warning("Failed to reset IPV6_V6ONLY flag (error: %d). "
                         "The server will listen to IPv6 addresses only.",
                         (int) socket_errno);
     }
   }
   ```
>
> Setting this socket option causes the extra line 0.0.0.0:3306 to show up in netstat. However, I'm still not able to connect by specifying 127.0.0.1 to telnet.
>
> The comments do make it sound like this option should only be used when wildcard is applied, but it seems the option is applied even when bind-address is specified.
>
> Possibly related discussion here: http://serverdown.ttwait.com/que/486038
> 
> google cache: http://webcache.googleusercontent.com/search?q=cache:14aq4-3tRLsJ:serverdown.ttwait.com/que/486038+&cd=4&hl=en&ct=clnk&gl=us
>
> **EDIT**: In the bug report (which is still in triage), I've proposed MySQL only clear IPV6_V6ONLY when binding to the wildcard address *. This seems to give the most flexibility of configuration in my.ini. If some admins are binding :: and then connecting to 127.0.0.1 they could be surprised. Binding * instead of :: would fix it.

**Comment by fadhilrajabian** [comment]
hi @netniV  and @cigamit 

i found this https://www.youtube.com/watch?v=kea-2yFFrl0

i give the **skip-grant-tables=TRUE** on the **my.cnf**

after that i can run **./spine -R -V 3 -S**

i think the problem is grant user for user cacti.

this is the result : 

![image](https://user-images.githubusercontent.com/47592794/54336924-0408c880-4660-11e9-9c2b-f6fdd6e6b0cb.png)


thankyou for all of your help @netniV  @cigamit 

really appreciated

**Comment by cigamit** [comment]
Please continue to research this setting.  For now, I will close this.
