### ISSUE TITLE
I'm considering install memcached or redis  to improve the overall Cacti system performance.  Does Cacti need to be modified in some way in order to use memcached or redis ?

### ISSUE THREAD

**Issue by tyit** [Cacti/cacti#2510]
Hi 

I'm considering install memcached or redis  to improve the overall Cacti system performance. 
Does Cacti need to be modified in some way in order to use memcached or  redis  ?

Thanks in advance! 
And sorry for my poor English...

**Comment by cigamit** [comment]
My recommendation is always to use either Enterprise class NVMe or PCIe Flash for enterprise class installs.  Enterprise SSD (eMLC - Means spare chips/memory to handle progressive failures over the lifetime) is also acceptable depending on your system size.  Some users use a memory based mounts to store the RRDfiles as well, but this adds the added complexity of periodically rsync'ing the files from time to time.  The latest generations of Enterprise PCIe Flash promise > 40PB's of write, and their wear level can be tracked in Cacti easy.  Most systems Flash and/or NVMe, if the databases are dedicated to Cacti and there are not any other applications on top of it, can easily sustain a 3-5 year lifecycle of the server.

One of the worst recommendations for both Database or RRDfile storage is NFS in that the latency between the storage and both the Database and the RRDtool command and the files significantly affect performance overall performance.  There is also the issue of the noisy neighbor problem with NFS that can impact performance.  Some users do not have a choice though, but they are always warned, if they ask on the forums, or now here, that that deployment comes with it's limitations, and those limitations are on performance, scalability, and stability.  So, buyer beware.

This same noisy neighbor problem occurs for VM's as well.  Though for many smaller systems, VM's are fine.  Also, with the advent of Flash and NVMe, some of the classic noisy neighbor problems are reduced.
