### ISSUE TITLE
Possible problem with mariadb 10.2.2+

### ISSUE THREAD

**Issue by xmacan** [Cacti/cacti#2511]
**Describe the bug**
Strict mode is on in version 10.2.2
(https://mariadb.com/kb/en/library/xtradbinnodb-strict-mode/)
It causes problem with table poller_output_boost because there is ROW_FORMAT=FIXED.
It is described here (see ROW_FORMAT):
https://mariadb.com/kb/en/library/create-table/

**To Reproduce**
I found it when I migrated cacti (1.1.38) to new server and make mysqldump and import. With row_format=fixed import sql fail.

**Additional context**
Maybe Cacti update should do:
ALTER TABLE poller_output_boost ROW_FORMAT=DYNAMIC;

**Comment by netniV** [comment]
I am guessing the reason for using the FIXED mode was for speed as every record would be of the same size so makes indexing faster (no major calculations necessary).  

> Strict mode is useful when using the ROW_FORMAT and KEY_BLOCK_SIZE clauses with CREATE TABLE, ALTER_TABLE and CREATE INDEX statements. If the specified KEY_BLOCK_SIZE is too small to contain a row and the strict mode is on, an error is returned by the statement.

Looking that over though I would have said that all we needed to do was set the values correctly when using the FIXED format.  However, the following links do not show FIXED as a valid format for storage:

https://mariadb.com/kb/en/library/innodb-storage-formats/
https://mariadb.com/kb/en/library/xtradbinnodb-file-format/

I'll let @cigamit weigh in on this one.

**Comment by jdcoats** [comment]
or just turn off strict mode :)

**Comment by netniV** [comment]
Yes, but even without strict mode, essentially the format is invalid.

**Comment by jdcoats** [comment]
yeah, I only noticed the change right away because all of my syslog to mysql inserts were failing miserably. Disabled it just to get that working again.

**Comment by cigamit** [comment]
A couple of things need to happen in my opinion.

1) Change innodb_file_format to Baracuda if supported.
2) Change innodb_large_prefix to 1 if supported.
3) Change ROW_FORMAT to dynamic if it's fixed or compressed.

The third item is a bit harder as it requires you to inspect the SQL file prior to import.  Which we don't really have in the UI right now.

**Comment by cigamit** [comment]
@xmacan, can you open an issue in the documentation repo, or generate a pull request that shows how to alter the database backup from prior releases to replace 'ROW_FORMAT=FIXED' with '' using sed?

**Comment by cigamit** [comment]
Closing as this is a documentation issue.  I've found now way in the mysql command to skip incompatible directives.  You can skip on error, but then, you don't get the table.
