### ISSUE TITLE
Errors occur when aggregate graph is being calculated for 95th percentile

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#2512]
**Describe the bug**
2019/03/13 09:38:38 - CMDPHP PHP ERROR NOTICE Backtrace: (/graph_json.php[158]:rrdtool_function_graph(), /lib/rrd.php[1522]:variable_nth_percentile(), /lib/graph_variables.php[419]:nth_percentile(), /lib/graph_variables.php[33]:rrdtool_function_stats(), /lib/graph_variables.php[132]:nth_percentile_fetch_statistics(), /lib/graph_variables.php[206]:CactiErrorHandler())
2019/03/13 09:38:38 - ERROR PHP NOTICE: Undefined index: p95n in file: /var/www/html/cacti/lib/graph_variables.php on line: 206
2019/03/13 09:38:38 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_json.php[158]:rrdtool_function_graph(), /lib/rrd.php[1522]:variable_nth_percentile(), /lib/graph_variables.php[419]:nth_percentile(), /lib/graph_variables.php[33]:rrdtool_function_stats(), /lib/graph_variables.php[132]:nth_percentile_fetch_statistics(), /lib/graph_variables.php[149]:CactiErrorHandler())

**Comment by netniV** [comment]
That particular line of code was changed back in February on commit cd14f260dde6499bec829753a026a1e1f37a67a5 as part of a fix for Aggregate.  Sounds like it's asking for a datasource that is not present in the data.

**Comment by interduo** [comment]
Thanks for defining my issue more precisly.

**Comment by cigamit** [comment]
Well, that is odd.  Making an update to lib/graph_variables.php.  Let me know if the nth percentile looks good afterwards.

**Comment by interduo** [comment]
After update I didn't see any messages like that in log.

**Comment by stefanbrudny** [comment]
What exactly I can do get rid of this message and have the graphs produced?

CMDPHP PHP ERROR NOTICE Backtrace: (/graph_json.php[158]:rrdtool_function_graph(), /lib/rrd.php[1509]:variable_nth_percentile(), /lib/graph_variables.php[419]:nth_percentile(), /lib/graph_variables.php[33]:rrdtool_function_stats(), /lib/graph_variables.php[136]:nth_percentile_fetch_statistics(), /lib/graph_variables.php[206]:CactiErrorHandler())

**Comment by interduo** [comment]
@stefanbrudny did You upgrade to newest version?

**Comment by netniV** [comment]
This fix is due to be released as a part of 1.2.3 next weekend.
