### ISSUE TITLE
Support multiple SNMP ports when adding devices via CLI

### ISSUE THREAD

**Issue by sysres-dev** [Cacti/cacti#2515]
The `cli/add_device.php` does not support creating devices with a new SNMP port when the hostname already exists, it is only possible to create new devices with a different community when using the `--proxy` option.

The `--proxy` option should allow different SNMP ports when creating new devices. It is already possible in the WebUI, so it is supported by Cacti.

I have implemented a solution in PR #2514.

**Comment by netniV** [comment]
This is now in the main development code, please check and close if issue is resolved.
