### ISSUE TITLE
Compatibility with Google Cloud SQL

### ISSUE THREAD

**Issue by mhoran** [Cacti/cacti#2516]
There are two issues preventing Cacti compatibility with Google Cloud SQL. First off, it is not possible to grant access to the `mysql.time_zone_name` table to a Cacti-specific user. This is because the `root` user in Google Cloud SQL does not have `SUPER` permissions, which is required to `GRANT` `SELECT` access to the mysql.time_zone_name table.

Second, I've set my PHP timezone to the desired timezone. However, Google Cloud SQL sets the default timezone to the timezone of the region where the instance resides. In my case, those two timezones are not the same.

It is possible to override the `default_time_zone` in Cloud SQL configuration. However, the value must be a numeric offset, not a name. This means whenever DST happens, I'll have to remember to change the value or my poller will be out of sync with local time.

For the first issue, perhaps an alternative `mysql.time_zone_name` lookup could be used for the Cacti user. I can read `mysql.time_zone_name` as `root`, so I could dump that table to another location accessible by the Cacti user. For the second issue, I propose that the limitation to configure the timezone of the poller be removed.

**Comment by cigamit** [comment]
The question I have is how were you able to complete the install since we required the mysql.time_zone_name to be populated?  You can disregard my question in the pull request as you comment above seems to answer things a bit.

**Comment by cigamit** [comment]
The default in my opinion would be to create an array of "GMT +/- [nn:nn]" offsets, and use that.  In my opinion, Google Cloud should also 1) populate that table with time zone names, 2) grant select access to everyone.  Seems to me to be a Google Cloud build issue more than a Cacti issue.

**Comment by mhoran** [comment]
> The question I have is how were you able to complete the install since we required the mysql.time_zone_name to be populated? You can disregard my question in the pull request as you comment above seems to answer things a bit.

This is an older install that I moved over to Cloud SQL. Hence the install was run on a machine where the Cacti user _did_ have access to `mysql.time_zone_name`. I only noticed that this was an issue when working on #2517.

> The default in my opinion would be to create an array of "GMT +/- [nn:nn]" offsets, and use that.

The problem with offsets is that they don't respect DST. I can set the `default_time_zone` to `-04:00` and that'll be fine until the fall, when I'll have to change it again. The same would be true for a table of offsets.

> Also, in my opinion, Google Cloud should:

>     populate that table with time zone names,
>     grant select access to everyone.

> Seems to me to be a Google Cloud build issue more than a Cacti issue.

I reached out to support and was informed that they cannot grant access to the `mysql.time_zone_name` table. However, the `root` user does have access to this table. I could run Cacti as the `root` user, but I'd prefer not to.

I've seen reports that in the past this table was _not_ populated, but support would populate it at request. It seems that this is now standard procedure, however because the `root` user that Cloud SQL creates for me does not have `SUPER` permissions, I cannot `GRANT SELECT ON mysql.time_zone_name`.

**Comment by netniV** [comment]
It's not ideal but can you update the `mysql.tables_priv` directly?  If you cloned the setup of the user from a working system (non-cloud) to a test instance?

https://mariadb.com/kb/en/library/mysqltables_priv-table/

**Comment by mhoran** [comment]
> It's mainly for testing purposes but can you update the mysql.tables_priv directly? If you cloned the setup of the user from a working system (non-cloud) to a test instance?

Yeah, that worked. A bit scary, though!

Alternatively, I found that creating a view (as the privileged user) in the Cacti DB allowed select with no further configuration; perhaps that's a good alternative?

**Comment by netniV** [comment]
We could make a note of that in the installation instructions.  Do you have the exact steps you used?

**Comment by mhoran** [comment]
The following worked for me to grant `SELECT` on `mysql.time_zone_name` to my Cacti user (in the example, `cacti_user`.):

`INSERT INTO mysql.tables_priv (Host, Db, User, Table_name, Grantor, Table_priv) VALUES ('%', 'mysql', 'cacti_user', 'time_zone_name', 'root@localhost', 'Select');`

Combined with #2517, I'm able to set the appropriate poller timezone:

![Screenshot at 2019-03-15 09-41-59](https://user-images.githubusercontent.com/5330/54436628-40dcca00-4709-11e9-8a9f-658eabb1449a.png)

**Comment by netniV** [comment]
We could add this to the documentation with a massive warning that it's at the DBA's own risk.  I don't really like showing anyone how to do something that's not fully supported but if it is the only thing that is going to work for them...

**Comment by netniV** [comment]
@ronytomen @cigamit what are your views on that?

**Comment by cigamit** [comment]
I would place the hack into the documentation though a normal install would be blocked due to the missing access or empty table.  So, I suspect it'll have to be a pre-packaged container of some sort.

**Comment by mhoran** [comment]
Sorry for the confusion; there were two proposed solutions above and one should work just fine for new installs. So long as the user has `INSERT` access to `mysql.tables_priv`, the following should work:

```
INSERT INTO mysql.tables_priv (Host, Db, User, Table_name, Grantor, Table_priv) VALUES ('%', 'mysql', 'cacti_user', 'time_zone_name', 'root@localhost', 'Select');
```

That current works on Google Cloud SQL, so perhaps that could be added to the docs?

The alternative solution of the `VIEW` would of course not work out of the box. Should Google take away `INSERT` access to `mysql.tables_priv`, we can revisit this.

**Comment by netniV** [comment]
Do you think you could add a caveat for that on the documentation repo?

**Comment by mhoran** [comment]
Done.

**Comment by netniV** [comment]
👍
