### ISSUE TITLE
Data Source Profile RRAs - Type letters instead of numbers in the "Rows" line

### ISSUE THREAD

**Issue by DavidLiedke** [Cacti/cacti#2518]
**Describe the bug**

**To Reproduce**
1. Go to Presets --> Data Profiles
2. Choose one Profile
3. Add / Edit one Data Source Profile RRAs
4. Type letters instead of numbers in the "Rows" line

**Expected behavior**
(/data_source_profiles.php[57]:get_filter_request_var(),
/lib/html_utility.php[459]:die_html_input_error(),  
/lib/html_validate.php[64]:cacti_debug_backtrace())

(/data_source_profiles.php[74]:get_size(),  /data_source_profiles.php[720]:get_filter_request_var(),  
/lib/html_utility.php[459]:die_html_input_error(),  
/lib/html_validate.php[64]:cacti_debug_backtrace())

Cacti.log:

2019/03/14 09:04:36 - CMDPHP PHP ERROR WARNING Backtrace:  (/data_source_profiles.php[67]:CactiErrorHandler())
2019/03/14 09:04:36 - ERROR PHP WARNING: A non-numeric value  encountered in file: /srv/www/cacti/data_source_profiles.php  on line:  67
2019/03/14 09:04:36 - CMDPHP PHP ERROR WARNING Backtrace:   (/data_source_profiles.php[74]:get_size(),  /data_source_profiles.php[722]:CactiErrorHandler())
2019/03/14 09:04:36 - ERROR PHP WARNING: A non-numeric value  encountered in file: /srv/www/cacti/data_source_profiles.php  on line:  722

**Screenshots**
![2019-03-14_09-01-21](https://user-images.githubusercontent.com/25581728/54340706-43232380-4638-11e9-9296-42b68b70dd0f.gif)

**Comment by netniV** [comment]
That shouldn't have made it past the request filtering in the first place as it's an invalid value for the filter. We will investigate that.

**Comment by cigamit** [comment]
I've got this one.
