### ISSUE TITLE
Dragging and Droping Devices not working as expected

### ISSUE THREAD

**Issue by cigamit** [Cacti/cacti#2524]
**Describe the bug**
The copy node functions is placing the wrong devices on the Tree's

**To Reproduce**
1. Goto Trees
2. Edit a Tree and Place in Edit mode
3. Drag various Devices onto the tree.  Note the wrong Device will be added in many cases

**Expected behavior**
Proper Devices should be placed on the Tree.

**Comment by cigamit** [comment]
Trying hard to reproduce this, which I can.  I just don't know the keysteps that are causing this.  Something to do about new branches.

**Comment by netniV** [comment]
If you can't locate it, it will have to be bumped to the next patch.

**Comment by netniV** [comment]
Are we bumping this one?

**Comment by cigamit** [comment]
Yea, I have been unable to determine the cause.  Since it's intermittent, let's jut hold off.
