### ISSUE TITLE
THOLD does not show thresholds 

### ISSUE THREAD

**Issue by Lalbee99** [Cacti/cacti#2526]
**Describe the bug**
I have upgraded my cacti from 0.8.8b to 1.2.2 with thold plugin version: 1.2.1 . I can create graphs which update perfectly fine. I can create and then see my thresholds under Management -> Thresholds for the host. I do not however see any thresholds for the host when looking under the THOLD tab. 
**To Reproduce**
1. Create a device 
2. Create Graphs for this Device
3. Auto-create Thresholds

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Explorer Microsoft Edge  
- Version 38.14393.2068.0

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Lalbee99** [comment]
General Information
Date 	Fri, 15 Mar 2019 13:44:35 -0400
Cacti Version 	1.2.2
Cacti OS 	unix
RSA Fingerprint 	83:6e:3c:63:23:d1:d1:7e:8b:1f:5f:f5:72:4d:75:8c
NET-SNMP Version 	NET-SNMP version: 5.7.2
RRDtool Version Configured 	1.4.0+
RRDtool Version Found 	1.4.8
Devices 	178
Graphs 	2563
Data Sources 	Script/Command: 387
SNMP Get: 130
SNMP Query: 1902
Script Query: 81
Script Server: 112
Total: 2612
Poller Information
Interval 	300
Type 	SPINE 1.2.2 Copyright 2004-2017 by The Cacti Group
Items 	Action[0]: 4028
Action[1]: 660
Action[2]: 106
Total: 4794
Concurrent Processes 	10
Max Threads 	15
PHP Servers 	5
Script Timeout 	40
Max OID 	60
Last Run Statistics 	Time:123.2908 Method:spine Processes:5 Threads:60 Hosts:158 HostsPerProcess:32 DataSources:4830 RRDsProcessed:0
System Memory
MemTotal 	15.15 G
MemFree 	1.96 G
MemAvailable 	6.01 G
Buffers 	378.03 M
Cached 	3.90 G
Active 	10.26 G
Inactive 	2.44 G
SwapTotal 	3.91 G
SwapFree 	3.91 G
PHP Information
PHP Version 	5.4.16
PHP Version 5.5.0+ is recommended due to strong password hashing support.
PHP OS 	Linux
PHP uname 	Linux cactiprd2 3.10.0-693.el7.x86_64 #1 SMP Thu Jul 6 19:56:57 EDT 2017 x86_64
PHP SNMP 	Installed
max_execution_time 	60
memory_limit 	1024M

**Comment by Lalbee99** [comment]
Can't get screenshots to upload

**Comment by cigamit** [comment]
Please log this bug in the thold issue tracker.
