### ISSUE TITLE
Remote Data Collector install process will not start

### ISSUE THREAD

**Issue by cigamit** [Cacti/cacti#2528]
**Describe the bug**
When installing a Remote Data Collector, you expect the installer to show up as soon as you source the database and restart the web site.  But in the current develop, you simply login and get to 'Offline' mode and the install will not commence.  The install can be finished by going to cacti/install and then the install will start.

**To Reproduce**
1. Install primary server
2. Ensure that config.php $cacti_db_session = true;
3. Goto the second server and attempt to install

**Expected behavior**
Remote Data Collector install should be triggered.

**Additional Context**
I think that this has something to do with the $cacti_db_session being set to true.

**Comment by stefanbrudny** [comment]
Confirmed on Cacti 1.2.2.

**Comment by cigamit** [comment]
For now, you can get around this recently introduced defect by going to cacti/install.  Then, the installation will complete.

**Comment by netniV** [comment]
So, to be clear, I need to have a previous version of 1.2 up and running with a remote collector, then upgrade the primary, and then try and upgrade the remote?

**Comment by cigamit** [comment]
Resolved.
