### ISSUE TITLE
Cacti admin documentation: multi-poller architecture 

### ISSUE THREAD

**Issue by stefanbrudny** [Cacti/cacti#2530]
Sysadmin is unable to understand multi poller architecture without testing. 

I expect documentation about the networking requirements, what are the Cacti components , ho dot they communicate with devices, with another cacti, with spine etc. 
What needs to be included in the docs:
* details of communication from Cacti main to Cacti additional pollers
* details of database communication: whether Cacti main communicates in any other way that through database, as...
* as it seems so, out of these nasty errors ("The requested URL /cacti.sql/remote_agent.php was not found on this server.""
* drawing of the architecture or intended architectures in layer 3 and layer 7.

Additional context:
I tried configuration and ultimately failed, because I tried too sophisticated configuration, which is completely unsupported, what is NOT clear. I tried to separate spine from Cacti, so app had different view to network than spine.  

My intended configuration is as follows;
Single central Cacti.
Two additional Cacti to poll for data (called Cacti  domain1 and domain2)
All three Cactis are on same server and use same MariaDB process. Each of the Cacti uses separate databases, so from application perspective they are remote to each other. 
Main Poller is located in global network namespace.
Domain1 and domain2 Cactis are located on same global network domain, but spine is launched from with domain1 and domain2, eg: 

*/1 * * * *     root **ip netns exec domain1** /usr/bin/php /var/www/cacti-dm20/poller.php

This approach NEARLY worked. It appears Cacti (as from php) have to always have access to device, which is not the case anymore, as the Cacti (apache / php) is located in different network domain than spine. Routing is outscoped: the reason is the two domains (customers) use same IP address space, so no ability to insert a route towards a network.

Small modifications to poller.php to spawn different spines were needed. 

To fix this, separate processes have to be spawned for http server in relevant domains and host the Cacti. Hopefully, not for database. But this I can't tell without architecture.

**Comment by cigamit** [comment]
Please open this bug in the documentation repo.  Also, just to note that there are several types of people in the world, including those who complain about things, those who take concrete steps to correct what is wrong in the world, and those who attempt to hide from the world.  I for one am glad you are not hiding, but I also wanted to add that we do, of course, take pull requests there at to documentation repo.

**Comment by stefanbrudny** [comment]
Sigh... can't we have it all behind us?... every project, same developers... No one complaints. Cacti is a Pluto in my Solar system. 

I may, at some point, prepare sensible / initial drawing of architecture with example of layer 3 with some comments, if there is really none?...
