### ISSUE TITLE
Graph cache array is not holding the correct details

### ISSUE THREAD

**Issue by NotAProfessionalDeveloper** [Cacti/cacti#2532]
**The following is a symptom**
After upgrading from 1.1.13 to 1.2.2, creating new graphs (from previously unused graph templates) for a certain host, no longer shows the graph template below that host in tree view.

We clearly see there are at least two templates used for that device in screenshot 1.

![b1](https://user-images.githubusercontent.com/277893/54499740-6f2ef500-4915-11e9-9ce5-1a07f66ec863.jpg)

Alas, screenshot 2 (tree view) does not show for example the "Interface Errors" template.

![b2](https://user-images.githubusercontent.com/277893/54499741-735b1280-4915-11e9-8803-6ea24a04a9e9.jpg)

Note that "Interface Errors" graphs based on that template for the item above existed before the upgrade.

**In the following you see that even the graph list under "Management" does not show that template being used**

![b3](https://user-images.githubusercontent.com/277893/54499930-c9c95080-4917-11e9-9dd4-724ac14de7f9.png)

Also, in the same screen, whether I choose to display graphs belonging to that device with Template = "none" or with "Orphaned" displays nothing

Note that the graph template in the dropdown is displayed if Device = Any or None is selected in the Device dropdown.

**Comment by netniV** [comment]
We saw something briefly in https://github.com/Cacti/cacti/issues/1614, that may not have been applied to the List View of graphs tab

**Comment by NotAProfessionalDeveloper** [comment]
TBH not sure what you fixed or if you understood the problem correctly :)

I don't know exactly what happened, but the problem is gone overnight, meaning: devices for which the graph template wasn't shown yesterday evening, show it now. However this happened at least in two steps:

1) Last night I went into the data query and saved it again (without changing anything). That made the graph templates appear everywhere (dropdowns, tree, ...) except for the device for which I only added the graphs a few minutes before.

2) Today, the single device for which the related template was still missing shows it now.

I even created a database dump last night, and not too many things changed:

```
--- mysql.cacti.2   2019-03-18 01:17:04.81360140
+++ mysql.cacti.3   2019-03-18 15:02:56.74717691
-INSERT INTO `data_input_data` VALUE
+INSERT INTO `data_input_data` VALUE
-INSERT INTO `host` VALUES (6,1,1,9,
+INSERT INTO `host` VALUES (6,1,1,9,
-INSERT INTO `host_snmp_cache` VALUE
+INSERT INTO `host_snmp_cache` VALUE
-INSERT INTO `host_snmp_query` VALUE
+INSERT INTO `host_snmp_query` VALUE
-INSERT INTO `poller` VALUES (1,'','
+INSERT INTO `poller` VALUES (1,'','
-INSERT INTO `poller_item` VALUES (3
-INSERT INTO `poller_item` VALUES (2
+INSERT INTO `poller_item` VALUES (3
+INSERT INTO `poller_item` VALUES (2
-INSERT INTO `poller_reindex` VALUES
+INSERT INTO `poller_reindex` VALUES
-INSERT INTO `poller_time` VALUES (3
+INSERT INTO `poller_time` VALUES (3
-INSERT INTO `settings` VALUES ('0',
+INSERT INTO `settings` VALUES ('0',
-INSERT INTO `snmpagent_cache` VALUE
+INSERT INTO `snmpagent_cache` VALUE
-INSERT INTO `user_auth_cache` VALUE
+INSERT INTO `user_auth_cache` VALUE
-INSERT INTO `user_log` VALUES ('',0
+INSERT INTO `user_log` VALUES ('',0
```

I will now try adding another device and using the same queries to see what happens.

**Comment by netniV** [comment]
Maybe I didn't... either way, we've both fixed an issue... 👍

**Comment by NotAProfessionalDeveloper** [comment]
> Maybe I didn't... either way, we've both fixed an issue... 👍

😄  still we need to find out what's going on here, because it's still not entirely ok, I'll keep digging

**Comment by NotAProfessionalDeveloper** [comment]
It's due to caching

```
function get_allowed_graph_templates($sql_where = '', $order_by = 'gt.name', $limit = '', &$total_rows = 0, $user = 0, $graph_template_id = 0) {
  $hash      = get_allowed_type_hash('graph_templates', $sql_where, $order_by, $limit, $graph_template_id, $user);
  $init_rows = $total_rows;

  if ($hash !== false) {
    $cached = get_cached_allowed_type($hash, $init_rows);

    if (is_array($cached) && sizeof($cached)) {
      return $cached;    <----- we end up here: the newly created template using which the graphs were created are not returned
    }
  }
```

**Comment by NotAProfessionalDeveloper** [comment]
Ehm, I see you changed the title of my report. Are you working on the layout of the page? My request was not about layout. It was about data being incorrectly displayed.

**Comment by NotAProfessionalDeveloper** [comment]
Again, in the following screenshot note the dropdown not showing all the templates being used for that actual device:

![image](https://user-images.githubusercontent.com/277893/54543240-90d3bf00-499d-11e9-9fd7-4c737f15c9ab.png)

We clearly see in the list that two graphs originating from different templates exist for the device. However, the dropdown at the top only shows one of the templates. Probably it's the same issue due to caching than the missing stuff in tree view.

**Comment by netniV** [comment]
I'm not too hot on how the caching is working (without deep diving into it) @cigamit may have a quick answer to it.

**Comment by cigamit** [comment]
The template cache should be wiped any time you

1) Import a new Graph Template, 
2) Create a new Template.

Otherwise, it should continue to use the Cacti for performance reasons.  Let me double check the work done here.

**Comment by cigamit** [comment]
I've made a change to the import to clear the cache on import.  Maybe that's it.

**Comment by NotAProfessionalDeveloper** [comment]
Does it also clear the cache when a new template is created? (since that was the other case you mentioned)
