### ISSUE TITLE
Tree Mode: Site Title lags 1 refresh behind

### ISSUE THREAD

**Issue by AiYoriAoshi** [Cacti/cacti#2537]
**Describe the bug**
I've upgraded Cacti yesterday from 1.2.1 to 1.2.2. Since then, the site title lags behind 1 refresh.
If I hit refresh (F5), the correct title will be displayed
If I select another tree item, the previously selected item will now be shown in the title.

**To Reproduce**
1. Go to Tree Mode
2. Have a Tree with multiple tree items
3. Click on different tree items and check site title

**Expected behavior**
Graph title showing the current selected tree item

**Screenshots**
![2we8bk](https://user-images.githubusercontent.com/9052188/54600515-db544a80-4a34-11e9-837b-b1e0897c15cd.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 65, Edge

**Additional context**
I tried to find out where the title is actually modified but I couldn't find the correct file/script.
I compared the folders from the backup and the new version with diff and it seems there was no modification to any function that sets the title, so it must be another change. Since I couldn't find out where the title is set, I couldn't go from there through the code to find that change.

**Comment by cigamit** [comment]
Resolved, thanks for reporting.
