### ISSUE TITLE
Custom stylesheet

### ISSUE THREAD

**Issue by sysres-dev** [Cacti/cacti#2541]
**Is your feature request related to a problem? Please describe.**
We want to overwrite css attributes in order to adapt the ui (increase inputs/labels size, etc.)

**Describe the solution you'd like**
Allow the possibility to overwrite css classes attributes

**Describe alternatives you've considered**
Include a blank custom stylesheet in html.php which can be overwrite by users

**Comment by netniV** [comment]
The only issue with applying a custom stylesheet is that there is a lot of customisation between the themes.  The only thing would be that we would need to remember to ask people to remove any custom CSS should they experience any glitches.  Feel free to create a system-wide setting for the css file location.

**Comment by TheWitness** [comment]
This should be done in a custom plugin using the 'page_head' hook.  That way you can check the current theme, and overload your CSS at the bottom of the head, which will override anything before it.  Make sense?  I don't think this needs to be a core feature.
