### ISSUE TITLE
Cacti incorrectly displays 0 rows when selecting a data query that has items.

### ISSUE THREAD

**Issue by godsyn** [Cacti/cacti#2545]
Cacti version :
    Version 1.2.2 on linux.

Issue: Attempting to create a graph with cacti. I add "SNMP - Get Processor Information" among others, and refresh the data. I receive:

> Data Query Debug Information
```
Total: 0.000000, Delta: 0.000000, Running Data Query [9].
--
Total: 0.000000, Delta: 0.000000, Found Type = '6' [Script Query - Script Server].
Total: 0.000000, Delta: 0.000000, Found data query XML file at '/var/www/cacti/resource/script_server/host_cpu.xml'
Total: 0.000000, Delta: 0.000000, XML file parsed ok.
Total: 0.100000, Delta: 0.100000, Executing script for num of indexes '"/usr/bin/php" -q /var/www/cacti/scripts/ss_host_cpu.php '192.168.1.100' '948' '2:161:5000:1:50:4cacti::::::' 'num_indexes''
Total: 0.100000, Delta: 0.000000, Found number of indexes: 3
Total: 0.210000, Delta: 0.110000, Executing script for list of indexes '"/usr/bin/php" -q /var/www/cacti/scripts/ss_host_cpu.php '192.168.1.100' '948' '2:161:5000:1:50:4cacti::::::' 'index'', Index Count: 3
```
>Click to show Data Query output for 'index'
```
Found index: 0
Found index: 1
Found index: Total
```
>Click to show Data Query output for field 'hrProcessorFrwID'
```
Total: 0.320000, Delta: 0.110000, Checking for Sort Field change. No changes detected.
--
Total: 0.320000, Delta: 0.000000, Update Data Query Sort Cache complete
Total: 0.320000, Delta: 0.000000, Index Association with Local Data complete
Total: 0.330000, Delta: 0.010000, No Index Changes Detected, Skipping Re-Index and Poller Cache Re-population
Total: 0.330000, Delta: 0.000000, Automation Executing for Data Query complete
Total: 0.330000, Delta: 0.000000, Plugin hooks complete
```
Regardless of the re-index method, the results are pretty much the same, and look correct.

Move over to *Create Graphs for this Device" and we're presented with
>Data Query [SNMP - Get Processor Information]
>All 3 Items
```
This Data Query returned 0 rows, perhaps there was a problem executing this Data Query.You can run this Data Query in debug mode From there you can get more information.
```
I've tried  `php poller_reindex_hosts.php --id=948 --debug` to no avail, and have gone so far as to delete and re-add the host.

All other hosts are fine. This one has issues. It is just a standard windows box. One of many.
![2019-03-20 04_01_52-Window](https://user-images.githubusercontent.com/508678/54668351-0f774c00-4ac5-11e9-9e98-e9a1fc766dc8.png)

**Comment by netniV** [comment]
On datasources, do you have anything showing when you set the status filter to bad indexes?

![image](https://user-images.githubusercontent.com/9052188/54670209-08fbcb00-4aeb-11e9-8a50-549d31968ff8.png)

**Comment by godsyn** [comment]
`No Data Sources Found`
![2019-03-20 13_21_52-Window](https://user-images.githubusercontent.com/508678/54705451-3c525000-4b13-11e9-8952-c5c1f2b23322.png)

**Comment by godsyn** [comment]
I've a couple of other devices with this issue. All are windows based.

**Comment by cigamit** [comment]
What cacti version?  I think this is resolved.  Just update the scripts/ss_host_disk.php from the GitHub 'develop' branch.  After doing this, re-index.

**Comment by godsyn** [comment]
Downloading and (most importantly) reindexing after upping the timeout seems to have resolved the issue. Thank you. I'm considering this closed unless I come across a situation that I cannot proceed with the above resolution.

Thanks again.
