### ISSUE TITLE
Logs display Order vs head or tail

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#2548]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Suggest use "**Head** lines" for "Display Order => Oldest First'
And keep current 'Tail lines" for "Display Order => Newest First'

**Comment by netniV** [comment]
Can you be more explainatory?  As far as I am aware, that is exactly how it works.

**Comment by ddb4github** [comment]
Current "Logs(tab)"  design is:
 - **tail** some lines of selected cacti.log file, **then** show them by timestamp.
 - head of selected cacti.log is not able to display by current filter combination.

My idea is:
 -  head or tail some lines of selected cacti.log, then show them by timestamp.
 -  Then we can freely read logfile whatever get from head or tail,  display them by ordest or newest first.
Like
![image](https://user-images.githubusercontent.com/17589018/54749336-304bb880-4c0f-11e9-9897-1e275a1c7911.png)

My Case is:

    - When I found my cacti have some problem around midnight 00:00,  I want to check tail of
      yesterday cacti.log-<date> and head of today cacti.log;
    - I checked tail of last cacti.log by "Logs(tab) ->  (Display Order=Newest First)"
    - I get few confusion when I want to check head of today cacti.log by  "Logs --> (Display Order=Oldest First)"

**Comment by netniV** [comment]
I think introducing the Head/Tail options would potentially speed up some searches but since the number of rows is linked to the filtered results of a search... it could get extremely confusing and lead to misunderstanding of what's being displayed in the results.

**Comment by netniV** [comment]
So currently, having just been through this to add a feature to 1.3, the code loops through every line in the file to determine if it should display it and get an accurate line count.  Once that is done, it then calculates the number of pages it would have from the displayed lines and then caclulates the start line and the end line.

With all that info, it then reads the file for a second time and displays those appropriate lines that should be displayed.  Currently, the code actually calculates whether to display a line twice so I have speeded that be up in 1.3 by caching the result.  You may not notice that speed difference though as it would be tiny, especially given the following enhancement that may have an opposite effect:

See https://github.com/Cacti/cacti/issues/3679 and its associated commit for more info.

**Comment by TheWitness** [comment]
This is resolved now.
