### ISSUE TITLE
When checking MySQL configuration values, consider ON/OFF to be equal to 1/0

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#2551]
On MySQL site:
   Suggestion value should boolean value 'On' 
   https://dev.mysql.com/doc/refman/5.5/en/innodb-parameters.html#sysvar_innodb_large_prefix

![image](https://user-images.githubusercontent.com/17589018/54733643-961b4e80-4bd5-11e9-902d-4ec886179561.png)

**Comment by netniV** [comment]
I would agree with that.

**Comment by netniV** [comment]
In fact, we should probably allow that for each of the boolean checks.
