### ISSUE TITLE
Database Upgrade - Version 1.0.0 - keeps failing 

### ISSUE THREAD

**Issue by Vards0** [Cacti/cacti#2553]
I am trying to upgrade from 0.8.8b to ver 1.2.2.

It looks like the upgrade keeps failing with the same error:-

UPDATE settings SET name=REPLACE(name, 'autom8', 'automation') WHERE name LIKE 'autom8%' | [Fail]
-- | --

All other upgrade processes appear to be successful.

I have copied the latest  1_0_0.php file from the repo but it doesn't seem to make a difference.

Any ideas?

Thank you

**Comment by netniV** [comment]
If you run that command manually what happens? That's a straight for command which changes all autom8_xxx names into automation_xxx names.  The only thing i can think of is that you have already got automation_xxx variables for some reason.

**Comment by Vards0** [comment]
Thanks for responding NetniV.

When I run the command, nothing seem to happen:-

#php 1_0_0.php 

No output on the screen at all.  Just a new command line.

I would send a screenshot but it doesn't appear to be an option.

**Comment by netniV** [comment]
Then that suggests that the command works so I’m not sure why you would see a fail when upgrading on that line.

**Comment by netniV** [comment]
OK, try the following
```
replace into settings ('log_install','3')
```
Run through the upgrade again and then email your install_complete.log (in the log folder) to developers@cacti.net

**Comment by cigamit** [comment]
This issue is resolved now.  It was caused by a duplicate column name.  Likely an automation setting was in the database before hand.
