### ISSUE TITLE
Sorting by name_cache slow on Data Sources page

### ISSUE THREAD

**Issue by cigamit** [Cacti/cacti#2563]
**Describe the bug**
On very large Cacti installs, the Data Sources page may be slow due to a missing index on the name_cache column

**To Reproduce**
1. Go to Data Source apge
2. Sort by the ID column, measure time
3. Sort by the Name column, measure time
4. Not the increase in time

**Expected behavior**
Behavior should be consistent between sorted columns

**Comment by netniV** [comment]
@TheWitness may need to check for that on Thresholds too where it was added recently.
