### ISSUE TITLE
For large systems, the sort buffer should be optimized for large tables

### ISSUE THREAD

**Issue by cigamit** [Cacti/cacti#2567]
**Describe the bug**
When you have over several hundred thousand Data Sources or Graphs, additional sort variables should be tuned including 'innodb_sort_buffer_size' and 'sort_buffer_size' to have the sort indexes created in memory.

**To Reproduce**
1. Source Data Sources by Name Cache for very large number of Data Sources
2. Adjust the innodb_sort_buffer_size to a larger number like 200M
3. Restart mariadb and warm up the table
4. Sort again and see the performance difference

**Expected behavior**
Better performance.

**Additional context**
There are notes that starting with MySQL 5.6, the sort buffer size is dynamic upto the max settings, so it does not have the same significant effect as it used to have in prior MySQL versions.

**Comment by TheWitness** [comment]
We have a recommendation for this right now, but since it's a client setting, we have to be careful.  Therefore, I'm considering this one closed/complete.
