### ISSUE TITLE
Cacti 1.2.2: Multi Poller: execute refresh or debug query works only on remote poller

### ISSUE THREAD

**Issue by stefanbrudny** [Cacti/cacti#2568]
**Describe the bug**
when executing debug query on indexed interfaces on Central Cacti user is given no results. Same time, this query can be executed with success on remote Poller. 

Workaround:
reindex interfces on remote hosts only? 
cact

**To Reproduce**
Use central cacti to execute debug query for a device attached to remote poller.

**Expected behavior**
It is expected Central Cacti is able to execute debug query from remote host.

**Comment by cigamit** [comment]
You mean a verbose query?  It works for me.  What are you getting back from the verbose query?  Looks like maybe a communication issue between the primary server and the remote data collector.  The primary/central server/collector uses the hostname in the remote data collector to communicate over port 80 or 443 to exchange debug.  It could be that the hostname that you are using is not known to the main server, or port 80/443 are not open.

**Comment by stefanbrudny** [comment]
Sorry, that was slightly in hurry.

Look, this is verbose query for a device belonging to remote poller, query is executed from main cacti:
![image](https://user-images.githubusercontent.com/6334806/55040437-a2b20380-5028-11e9-8554-d1329d27c1c8.png)

All good. Let's add a bridge to the host and re-execute the query:

![image](https://user-images.githubusercontent.com/6334806/55040527-03414080-5029-11e9-9cdd-8ee79a91e008.png)

Now I have three interfaces but two available for Cacti.

Workaround: execute query from remote poller, and not exactly to which the device belongs to.

THis is further confirmed here:
![image](https://user-images.githubusercontent.com/6334806/55040614-6e8b1280-5029-11e9-8649-f7414ae57128.png)

Reload query doesn't work either.

**Comment by cigamit** [comment]
grep for "remote_agent" and then "reload" in the apache access log on the remote data collector, let me know if it's running.  Is the remote data collector in online mode?  The fact that it's returning data means that it's working.  The only reason it would not return results back to the main server through the mysql connection would be if the remote collector is in offline mode for some undefined reason.

**Comment by cigamit** [comment]
On a hunch, I tested, and verified the issue.
