### ISSUE TITLE
ERROR PHP NOTICE: Undefined offset: 20 in file cmd.php  on line: 497

### ISSUE THREAD

**Issue by YongBoLiu** [Cacti/cacti#2569]
**Describe the bug**

Errors in Clog as below in each poller interval,

2019/03/26 11:20:02 - ERROR PHP NOTICE: Undefined offset: 20 in file: /opt/cacti/cmd.php  on line: 497
2019/03/26 11:20:02 - CMDPHP PHP ERROR NOTICE Backtrace:  (/cmd.php[497]:CactiErrorHandler())
2019/03/26 11:20:02 - ERROR PHP NOTICE: Undefined offset: 20 in file: /opt/cacti/cmd.php  on line: 500
2019/03/26 11:20:02 - CMDPHP PHP ERROR NOTICE Backtrace:  (/cmd.php[500]:CactiErrorHandler())
2019/03/26 11:20:02 - ERROR PHP NOTICE: Undefined offset: 20 in file: /opt/cacti/cmd.php  on line: 500
2019/03/26 11:20:02 - CMDPHP PHP ERROR NOTICE Backtrace:  (/cmd.php[500]:CactiErrorHandler())
2019/03/26 11:20:02 - ERROR PHP NOTICE: Undefined offset: 20 in file: /opt/cacti/cmd.php  on line: 501
2019/03/26 11:20:02 - CMDPHP PHP ERROR NOTICE Backtrace:  (/cmd.php[501]:CactiErrorHandler())
2019/03/26 11:20:02 - ERROR PHP NOTICE: Undefined offset: 20 in file: /opt/cacti/cmd.php  on line: 501
2019/03/26 11:20:02 - CMDPHP PHP ERROR NOTICE Backtrace:  (/cmd.php[501]:CactiErrorHandler())
2019/03/26 11:20:02 - ERROR PHP NOTICE: Undefined offset: 20 in file: /opt/cacti/cmd.php  on line: 503
2019/03/26 11:20:02 - CMDPHP PHP ERROR NOTICE Backtrace:  (/cmd.php[503]:CactiErrorHandler())
2019/03/26 11:20:02 - ERROR PHP NOTICE: Undefined offset: 20 in file: /opt/cacti/lib/functions.php  on line: 1110
2019/03/26 11:20:02 - CMDPHP PHP ERROR NOTICE Backtrace:  (/cmd.php[503]:update_host_status(), /lib/functions.php[1110]:CactiErrorHandler())

**To Reproduce**
1. Add some graphs on a host.
2. Wait the graphs are show up in normal.
3. Disable the host.
4. Wait one poller cycle, check the clog 

**Expected behavior**
No errors show up in Clog.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: RHEL7
 - Browser Firefox
 - Version [1.2.0]

**Smartphone (please complete the following information):**

**Additional context**

In cmd.php, the $hosts is from host table without disabled, while the ($host_id = $item['host_id']) is from poller_item table.
So, the poller_item can has the $host_id which not in the $hosts array. we need to check the $hosts[$host_id] is set or not as below, to avoid the errors in the clog.
```
diff --git a/cmd.php b/cmd.php
index 3672408..2fcadb6 100644
--- a/cmd.php
+++ b/cmd.php
@@ -503,7 +503,7 @@ if ((cacti_sizeof($polling_items) > 0) && (read_config_option('poller_enabled')
 
                $host_id = $item['host_id'];
 
-               if (($new_host) && (!empty($host_id))) {
+               if (($new_host) && (!empty($host_id)) && (isset($hosts[$host_id]))) {
                        $ping->host = $item;
                        $ping->port = $hosts[$host_id]['ping_port'];
 
```

**Comment by netniV** [comment]
As far as I am aware, that should not happen but we will look into it.

**Comment by cigamit** [comment]
Resolved.
