### ISSUE TITLE
view page for external link without permission has error 

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/cacti#2571]
**To Reproduce**
1. Go to utilitites - External link page
2. Add a External link 
3. Go to Configuration - Users - Permission tab to disable the permisson for external link 
4. Go back to utilitites - External link page
5. Click view page button, no action 

**Expected behavior**
Cacti should check permission when click view page option, if no real permission, logout automatically and give message. 

**Screenshots**
![Screen Shot 2019-03-26 at 5 06 02 PM](https://user-images.githubusercontent.com/47589910/54984419-cdc93280-4fe9-11e9-9247-36601752091c.png)
![Screen Shot 2019-03-26 at 5 05 37 PM](https://user-images.githubusercontent.com/47589910/54984428-d28de680-4fe9-11e9-8926-23fb5165c91a.png)

**Desktop (please complete the following information):**
 - OS: rhel73 x86_64 
 - Browser FF
 - Version Cacti1.2.2

**Comment by cigamit** [comment]
Resolved.  Thanks for reporting.
