### ISSUE TITLE
Support Sorting of Tree or Graph View by Data Source

### ISSUE THREAD

**Issue by maxstech** [Cacti/cacti#2572]
Cacti 1.2.1.
Is it possible to make dynamic sorting of graphs in tree by  traffic utilization.  To graphics were in the top depending on the load.  
This mechanism would be very convenient for quick localization of problems on the network. 
If such decisions at the moment ?
If not, I would like to see it in the future.
Thanks.

**Comment by cigamit** [comment]
This one has been raised before.  It's fairly trivial for systems that enable Data Source Statistics.  I was looking for the old enhancement request, but could not find it.

**Comment by xmacan** [comment]
You can use my plugin https://github.com/xmacan/plugin_topx
Now It is working with CPU utilization, interface traffic, ... You can easy add another DS

**Comment by maxstech** [comment]
thank you, I will definitely try it16.06.2019, 20:46, "Petr Macek" <notifications@github.com>:You can use my plugin https://github.com/xmacan/plugin_topx
Now It is working with CPU utilization, interface traffic, ... You can easy add another DS

**Comment by maxstech** [comment]
how can I find out the hash function for data_template ? For example in cacti 1.2.116.06.2019, 20:46, "Petr Macek" <notifications@github.com>:You can use my plugin https://github.com/xmacan/plugin_topx
Now It is working with CPU utilization, interface traffic, ... You can easy add another DS

**Comment by xmacan** [comment]
There is file HOW_TO_ADD_YOUR_DATA.txt

**Comment by maxstech** [comment]
Ok, thanks.17.06.2019, 15:46, "Petr Macek" <notifications@github.com>:There is file HOW_TO_ADD_YOUR_DATA.txt

**Comment by xmacan** [comment]
Please use https://github.com/xmacan/plugin_topx/issues/ for Plugin TopX issues. Here is Cacti repository :-)

**Comment by xmacan** [comment]
I implemented DSStats to my plugin TopX. You can try
 https://github.com/xmacan/plugin_topx/

**Comment by jdcoats** [comment]
Sorting of graphs by utilization would be a great addition!

**Comment by TheWitness** [comment]
Yea, it's been on my list for too long.  I have to fix all the issues in DSStats first, like being able to cut through my 1.7M data sources in less than a day.

**Comment by TheWitness** [comment]
@jdcoats, @xmacan, and @maxstech, I've created a separate branch for this work.  I'm just starting on it now.

**Comment by TheWitness** [comment]
This is now resolved in the `develop` branch.
