### ISSUE TITLE
Associated graph template for Data Query Disappears

### ISSUE THREAD

**Issue by kurowskydb** [Cacti/cacti#2573]
I have had an associated graph template repeatedly disappear from the SNMP-Interface Statistics data query

Currently have no idea how to reproduce.

I can re-add the template to the query but of course the mapping id increments.
The I need to go and update / replace the old id with the new in the local_graph table.

**Screenshots**
![2019-03-26 10_36_54-Console -_ Graph Management](https://user-images.githubusercontent.com/11399008/55006423-1b2aad00-4fb4-11e9-97f3-5627112c0582.png)

Cacti version 1.2.2

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Version: Version 73.0.3683.86 (Official Build) (64-bit) 

I noticed when re-applying suggested names.  But not sure if it disappears during the re-applying or during the editing of suggested names.

**Comment by kurowskydb** [comment]
Digging some more it seems I didn't have to update the graph_local table (snmp_query_graph_id).
Looks like the snmp_query_graph table is where the issue resides.
I can see the graph templates that I keep re-adding.  The snmp_query_id keeps getting set to '0'.

**Comment by netniV** [comment]
Is this a custom data query?

**Comment by cigamit** [comment]
So, are you saying that you have graphs that were created from an SNMP Query Graph that was removed from the Data Query list?  If that is so, then you need to repair your database, and it's not going to be easy.  

Before you do that, you should re-run the Database upgrade and force a pre 1.x version.  That column should have been added during the upgrade to 1.0.0.  So, if you do the following:

```shell
cd /var/www/html/cacti/cli
php -q upgrade_database.php --frocever=0.8.8a
```

It should return clean and the snmp_query_graph_id should be populated for any graphs that have an snmp_index_id > 0.  If that's not the case, I would repair your original Data Query by re-importing it, and then create the graphs all over again, and then copy the old RRDfile over the new one.

I'm not sure that there is any change to Cacti that is warranted.

**Comment by kurowskydb** [comment]
So this is a little hard to explain.  I'll try my best.  Not a custom query, Just an 'enhanced' graph template I'm associating to the query.

![image](https://user-images.githubusercontent.com/11399008/55075510-897d7700-5069-11e9-9b20-ea0fb9c6c106.png)

I've had it disappear from this list now 3 or 4 times.  While investigating I discovered they were still listed in the snmp_query_graph table (I deleted them since then) with a value of "0" in the 'snmp_query_id' field.

![image](https://user-images.githubusercontent.com/11399008/55076066-dc0b6300-506a-11e9-9008-78ee0db76d05.png)

**Comment by cigamit** [comment]
Well that is unusual.  So, from my perspective, you need to root this out using the two tables: graph_local and data_local.  For both tables, the snmp_query_id must be set properly.  For the graph_local, the snmp_query_graph_id must be set to, in your case 24.  Now, since there was hacking going on, I know that there is one more table that holds the snmp_query_graph_id, for the moment, I just don't remember it.

It goes without saying that we need an update ERD for this database, and it's something that we will do more along the lines of a 1.3+ release where we plan to cut all the fat out of the schema.

For now, start with those two changes, and see if it's still not displaying properly or resetting to 0.  Also, when does the resetting take place?  Is it as a part of a re-index?  Please confirm.  This will help with diagnosing where you need to continue to hack to get this right.  Sorry that you have to hack.

**Comment by kurowskydb** [comment]
I have not been able to reproduce this same issue, but I have run into a couple other problems that appear to be related.  All revolving around the data queries.  There appear to be some linkage issues.
When clicking on the source name for the interface traffic graphs, the associated data templates are empty.  I did a clean install on 1.2.2.  I upgraded to 1.2.3 and problem persists.  Then a clean install on 1.2.3.  no change.

![image](https://user-images.githubusercontent.com/11399008/55329242-20787380-545c-11e9-888f-9810db91ee39.png)

![image](https://user-images.githubusercontent.com/11399008/55329255-24a49100-545c-11e9-86e8-8d054fc9560e.png)

**Comment by kurowskydb** [comment]
I also gone to some graph sources (prior to the clean install)  and the data templates where not empty, but they were not set and had been disabled.  After fixing It and clicking save it would crate the duplicate data query mentioned earlier in the original message.

**Comment by cigamit** [comment]
It looks like you had a custom XML file, or the XML file has disappeared from the resources/snmp_queries directory, or it's not readable by the web site.

**Comment by cigamit** [comment]
@kurowskydb, please close once you've figured things out.

**Comment by kurowskydb** [comment]
Looks like data queries listed under the source column on the Graph management page are missing "&snmp_query_id=" in the link.  "&snmp_query_id=4" in my case.

**Comment by cigamit** [comment]
The reason the column is missing is that the upgrade is removing the column from the XML file, which then subsequently mucks up your system.  Upload your 'good' XML file.  I might just incorporate those changes.  There are others too.

**Comment by kurowskydb** [comment]
This is happening in a fresh install.

**Comment by cigamit** [comment]
I've verified this now.  Fixing shortly.

**Comment by cigamit** [comment]
This issue is resolved now.
