### ISSUE TITLE
Poller warning bad snmp indexes

### ISSUE THREAD

**Issue by 5sirius5** [Cacti/cacti#2577]
After installing 1.2.2 in log appear lot of messages like "POLLER: Poller[Main Poller] WARNING: You have 6 Devices with bad SNMP Indexes. Devices: Device[opti98_7], Device[opti72_33], Device[opti96_4], Device[opti90_6], Device[opti128], Device[opti92_46] totalling 26 Data Sources. Please Either Re-Index, Delete or Disable these Data Sources."

I made a change to the data sources fields Index Type and Value, and some time everything is ok. After some time begins the same, in log appear the same lines and data source fields change back to incorrect values. In previous version there was no this error.

"2019/03/27 06:46:07 - REINDEX WARNING: Sort Field has Changed for Device[opti72_33] and DQ[SNMP - Interface Statistics]. Old Sort:ifDescr, New Sort:ifName. Re-mapping issues may occur!
--
2019/03/27 06:46:07 - PCOMMAND Device[opti72_33] WARNING: Recache Event Detected for Device
2019/03/27 06:44:07 - POLLER: Poller[Main Poller] WARNING: You have 5 Devices with bad SNMP Indexes. Devices: Device[opti98_7], Device[opti96_4], Device[opti90_6], Device[opti128], Device[opti92_46] totalling 25 Data Sources. Please Either Re-Index, Delete or Disable these Data Sources.
2019/03/27 06:39:06 - POLLER: Poller[Main Poller] WARNING: You have 5 Devices with bad SNMP Indexes. Devices: Device[opti98_7], Device[opti96_4], Device[opti90_6], Device[opti128], Device[opti92_46] totalling 25 Data Sources. Please Either Re-Index, Delete or Disable these Data Sources.
2019/03/27 06:34:07 - POLLER: Poller[Main Poller] WARNING: You have 5 Devices with bad SNMP Indexes. Devices: Device[opti98_7], Device[opti96_4], Device[opti90_6], Device[opti128], Device[opti92_46] totalling 25 Data Sources. Please Either Re-Index, Delete or Disable these Data Sources.
2019/03/27 06:29:07 - POLLER: Poller[Main Poller] WARNING: You have 5 Devices with bad SNMP Indexes. Devices: Device[opti98_7], Device[opti96_4], Device[opti90_6], Device[opti128], Device[opti92_46] totalling 25 Data Sources. Please Either Re-Index, Delete or Disable these Data Sources.
2019/03/27 06:24:06 - POLLER: Poller[Main Poller] WARNING: You have 5 Devices with bad SNMP Indexes. Devices: Device[opti98_7], Device[opti96_4], Device[opti90_6], Device[opti128], Device[opti92_46] totalling 25 Data Sources. Please Either Re-Index, Delete or Disable these Data Sources.
2019/03/27 06:19:06 - POLLER: Poller[Main Poller] WARNING: You have 5 Devices with bad SNMP Indexes. Devices: Device[opti98_7], Device[opti96_4], Device[opti90_6], Device[opti128], Device[opti92_46] totalling 25 Data Sources. Please Either Re-Index, Delete or Disable these Data Sources.
2019/03/27 06:14:08 - POLLER: Poller[Main Poller] WARNING: You have 5 Devices with bad SNMP Indexes. Devices: Device[opti98_7], Device[opti96_4], Device[opti90_6], Device[opti128], Device[opti92_46] totalling 25 Data Sources. Please Either Re-Index, Delete or Disable these Data Sources.
2019/03/27 06:09:06 - POLLER: Poller[Main Poller] WARNING: You have 5 Devices with bad SNMP Indexes. Devices: Device[opti98_7], Device[opti96_4], Device[opti90_6], Device[opti128], Device[opti92_46] totalling 25 Data Sources. Please Either Re-Index, Delete or Disable these Data Sources.
2019/03/27 06:04:06 - POLLER: Poller[Main Poller] WARNING: You have 5 Devices with bad SNMP Indexes. Devices: Device[opti98_7], Device[opti96_4], Device[opti90_6], Device[opti128], Device[opti92_46] totalling 25 Data Sources. Please Either Re-Index, Delete or Disable these Data Sources.
2019/03/27 05:59:06 - POLLER: Poller[Main Poller] WARNING: You have 5 Devices with bad SNMP Indexes. Devices: Device[opti98_7], Device[opti96_4], Device[opti90_6], Device[opti128], Device[opti92_46] totalling 25 Data Sources. Please Either Re-Index, Delete or Disable these Data Sources.
2019/03/27 05:54:06 - POLLER: Poller[Main Poller] WARNING: You have 5 Devices with bad SNMP Indexes. Devices: Device[opti98_7], Device[opti96_4], Device[opti90_6], Device[opti128], Device[opti92_46] totalling 25 Data Sources. Please Either Re-Index, Delete or Disable these Data Sources."

**Comment by cigamit** [comment]
There were a number of vendors we discovered that update the ifDescriptions between firmware updates which forced the change to ifName, which is more static.  In the cases where the ifDescriptions could not match the ifDescription of an existing ifName, we reset the snmp_index and disable the graph.  You can find these Data Sources in Cacti 1.2.2 and then do the research to either remove these graphs, or manually associate the ifName of the correct interface.  It's not a bug, it's a feature that exposed something that has been going on for years that we were all silently unaware of.  You can help us here by letting us know your Device Type and sharing some snmpwalks of the ifDescription and ifName for historical reference.

**Comment by 5sirius5** [comment]
Hello again. I didn't make any firmware updates to the switch and it stopped to work, begun to write about data sources re-indexing to the log. I have feeling like this happens randomly. I make correction to data sources and it works some time, but then stop and begin to write the same about re-indexing.

**Comment by 5sirius5** [comment]
Today was no firmware update on another switch and it stopped to draw graphs with broken data sources. I think i will try to downgrade to 1.2.1 or move to zabbix.

**Comment by TheWitness** [comment]
Likely the device had not been reindexed in a long time.  IfDesc was found to be unreliable.  ifName is though.  The way you fix is to set manually in you screen shot to ifName, and the pick the right one.

**Comment by 5sirius5** [comment]
I already made this two weeks ago for this switch, and yesterday it stopped to draw graphs and want to reindex data sources? I don't know what else i can do, every time i need to manually fix IfDesc to IfName and then it stopped to work again. Every day begins from fixing datasources.

**Comment by 5sirius5** [comment]
I made change to the broken data source and graphs begin to draw, but after some time without any firmware updates graphs on the same switch break down again. And i have the latest 1.2.3 version. I just don't understand why absolutely working data sources, which was previously corrected, break down again.

**Comment by cigamit** [comment]
If you ever update interfaces.xml, you need to make sure that the sort field is always ifName and not ifDescr, otherwise, the next time the device re-index, the order will be changed again.  We have found that with many devices the idDescr will change upon firmware updates, which makes it a very bad candidate for interfaces.

The problem is, several people has published templates that update the interfaces.xml file.  This is a pretty nagging issue for us.

**Comment by 5sirius5** [comment]
Today one more switch stopped to draw graphs with the same warnings "Please Either Re-Index, Delete or Disable these Data Sources." and firmware on it was not updated. And also i don't have any file interfaces.xml.

**Comment by cigamit** [comment]
Cacti 1.2.5 has some specific fixes for some very old SNMP Queries.  I would consider updating to it once released.

**Comment by interduo** [comment]
After update to 1.2.5 from 1.2.4.

`2019/07/17 12:45:36 - POLLER: Poller[1] WARNING: You have 65 Devices with bad SNMP Indexes.  Devices: Device[41], Device[72], Device[80], Device[117], Device[121], Device[187], Device[157], Device[151], Device[200], Device[229], Device[234], Device[36], Device[246], Device[51], Device[344], Device[363], Device[365], Device[366], Device[372], Device[384], Device[385], Device[377], Device[390], Device[393], Device[394], Device[415], Device[408], Device[426], Device[456], Device[368], Device[495], Device[505], Device[519], Device[536], Device[586], Device[594], Device[589], Device[597], Device[58], Device[608], Device[612], Device[615], Device[628], Device[654], Device[469], Device[247], Device[675], Device[682], Device[695], Device[706], Device[727], Device[81], Device[752], Device[778], Device[789], Device[726], Device[398], Device[795], Device[829], Device[842], Device[259], Device[110], Device[254], Device[854], Device[857] totalling 348 Data Sources.  Please Either Re-Index, Delete or Disable these Data Sources.`

How to do Re-Index?

**Comment by arekm** [comment]
Related? https://forums.cacti.net/viewtopic.php?f=21&t=59642

**Comment by caleianderson** [comment]
I have this same exact problem. That link is also the same problem and neither of these threads has an answer. I am on version 1.2.6 so going past 1.2.5 did not solve it. And this thread should not have been closed with out an actual solution to the issue.
