### ISSUE TITLE
Missing Data in Graph

### ISSUE THREAD

**Issue by koriks1111** [Cacti/cacti#2579]
Hi niv and team , 

i have update my cacti server machine and cacti version automatically upgrade, now after try logging in. the cacti cannot populate any graph anymore

![image](https://user-images.githubusercontent.com/42999735/55139622-2840cb00-5171-11e9-99ea-d6ae18404a07.png)

my data collector is like this

![image](https://user-images.githubusercontent.com/42999735/55139659-40b0e580-5171-11e9-997d-b008c830324a.png)

please help, thanks in advance

**Comment by netniV** [comment]
That would suggest that the poller isn't running properly  Check your /etc/cron.d/cacti file.

**Comment by koriks1111** [comment]
*/1 * * * *    cacti   /usr/bin/php /usr/share/cacti/poller.php > /dev/null 2>&1


[@localhost cacti]# crontab -l
*/1 * * * *    cacti   /usr/bin/php /usr/share/cacti/poller.php > /dev/null 2>&1

**Comment by koriks1111** [comment]
i usually do the 1 min polling time to have realtime
![image](https://user-images.githubusercontent.com/42999735/55140937-304e3a00-5174-11e9-862f-3160b1300078.png)

**Comment by netniV** [comment]
This would suggest that you have two pollers trying to compete on the same host.  You should only need either /etc/cron.d/cacti or crontab 

The other thing is, where you have /dev/null, change that to a valid file location that user could write to and then check the log file for results.

**Comment by koriks1111** [comment]
how to know if this /etc/cron.d/cacti is running or not? 

i remove my crontab seems still the same. 


sorry for bothering youa anyway

**Comment by koriks1111** [comment]
/etc/cron.d/cacti start
bash: /etc/cron.d/cacti: Permission denied

**Comment by netniV** [comment]
You can't start it, it's a text file used by cron.  You would need to check your cron logs to see whether it had an issue or not.

**Comment by netniV** [comment]
It would be easier just to change the /dev/null to a valid file though as I said earlier.

**Comment by koriks1111** [comment]
i have put like this 
/1 * * * *    cacti   /usr/bin/php /usr/share/cacti/poller.php > /usr/share/cacti/log/cacti_stderr.log  2>&1

but the logs no anything inside. i think it's because the poller is not running

**Comment by koriks1111** [comment]
logs from cron

ar 28 22:22:01 localhost CROND[30578]: (cacti) CMD (  /usr/bin/php /usr/share/cacti/poller.php > /dev/null 2>&1)
Mar 28 22:23:01 localhost CROND[30640]: (cacti) CMD (  /usr/bin/php /usr/share/cacti/poller.php > /dev/null 2>&1)
Mar 28 22:24:01 localhost CROND[30682]: (cacti) CMD (  /usr/bin/php /usr/share/cacti/poller.php > /dev/null 2>&1)
Mar 28 22:25:01 localhost CROND[30725]: (cacti) CMD (  /usr/bin/php /usr/share/cacti/poller.php > /dev/null 2>&1)
Mar 28 22:26:01 localhost CROND[30771]: (cacti) CMD (  /usr/bin/php /usr/share/cacti/poller.php > /dev/null 2>&1)
Mar 28 22:27:01 localhost CROND[30798]: (cacti) CMD (  /usr/bin/php /usr/share/cacti/poller.php > /dev/null 2>&1)
Mar 28 22:28:01 localhost CROND[30863]: (cacti) CMD (  /usr/bin/php /usr/share/cacti/poller.php > /dev/null 2>&1)
Mar 28 22:29:01 localhost CROND[31474]: (cacti) CMD (  /usr/bin/php /usr/share/cacti/poller.php > /dev/null 2>&1)
Mar 28 22:30:01 localhost CROND[32045]: (cacti) CMD (  /usr/bin/php /usr/share/cacti/poller.php > /dev/null 2>&1)
Mar 28 22:31:01 localhost CROND[32093]: (cacti) CMD (  /usr/bin/php /usr/share/cacti/poller.php > /dev/null 2>&1)
Mar 28 22:32:01 localhost CROND[32124]: (cacti) CMD (  /usr/bin/php /usr/share/cacti/poller.php > /dev/null 2>&1)
Mar 28 22:33:01 localhost CROND[32192]: (cacti) CMD (  /usr/bin/php /usr/share/cacti/poller.php > /dev/null 2>&1)
Mar 28 22:34:02 localhost CROND[32236]: (cacti) CMD (  /usr/bin/php /usr/share/cacti/poller.php > /dev/null 2>&1)
Mar 28 22:35:01 localhost CROND[32280]: (cacti) CMD (  /usr/bin/php /usr/share/cacti/poller.php > /dev/null 2>&1)
Mar 28 22:36:01 localhost CROND[32328]: (cacti) CMD (  /usr/bin/php /usr/share/cacti/poller.php > /dev/null 2>&1)

**Comment by netniV** [comment]
Right, the fact that cron says it's still going to /dev/null, suggests that you aren't running this the way you think it is.  I reckon you have a crontab for the cacti user still running.

**Comment by koriks1111** [comment]
it's still the same, is it because my spine is still 1.1.38?

**Comment by koriks1111** [comment]
/usr/local/spine/bin/spine -R -S -V 3
2019/03/29 13:49:43 - SPINE: Poller[1] FATAL: Unable to read configuration file! (Spine init)

**Comment by koriks1111** [comment]
i tried to reinstall the spine now im having this.. :(

![image](https://user-images.githubusercontent.com/42999735/55216215-1de90480-5237-11e9-8939-5c1e59d8ce4e.png)

**Comment by koriks1111** [comment]
if i force to run php -q poller.php --debug --force for couple of time, i can force a graph

![image](https://user-images.githubusercontent.com/42999735/55224378-5bf02380-524b-11e9-8ff7-6290a3071733.png)

sorry the time zone maybe diff with you. thanks in advance hoping to hear a response..

**Comment by netniV** [comment]
Your spine version MUST be the same level as your Cacti core.  There can sometimes be no changes to spine but the version should be kept close.  

Not sure on the realtime error. That probably needs further investigation.

**Comment by koriks1111** [comment]
how about the php version and others? 

my php verion is PHP 5.4.16 (cli) (built: Oct 30 2018 19:30:51)
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies


im trying to provide information as much as i can just to solve this. :(

**Comment by netniV** [comment]
If you are running spine, have you specified the path to the configuration file within settings?

**Comment by netniV** [comment]
And when running spine manually, specify the path to the configuration file using -C

**Comment by koriks1111** [comment]
the path is correct. /usr/local/spine/bin

./spine -C
2019/03/31 14:36:41 - SPINE: Poller[1] ERROR: option -C requires a parameter (Spine init)

**Comment by netniV** [comment]
You need to specify the path to the configuration file

**Comment by cigamit** [comment]
Those errors are realtime errors.  Are they still continuing?  What about general graphing?  What is in your log?  Can you also please see during every polling cycle there are rows accumulating in the poller_output table?  They will only be there for a very short period of time, so you will have to setup a very fast watch on the table.

**Comment by koriks1111** [comment]
im having a hard time debugging it, so i decided to rollback the previous version. thanks for the time btw. i will try to install the new version on my vm and will feedback if i encountered same issue. thanks.
