### ISSUE TITLE
DSStats adding more and more processes until server stops

### ISSUE THREAD

**Issue by JorisFRST** [Cacti/cacti#2580]
**Describe the bug**
Dsstats starts to run more and more php processes, until the server goes 100% cpu, overnight it stops responding.
Cacti 1.2.2

**To Reproduce**
Enable DSStats, wait a few polling cycles

**Expected behavior**
Not much

**Screenshots**

**Comment by JorisFRST** [comment]
Might be related to : #2505

**Comment by JorisFRST** [comment]
Upgraded to 1.2.3 and same issues  Even after disabling and waiting a few poller cycles, the already open php processes don't close.  Had to kill manually.

**Comment by cigamit** [comment]
How often do you run boost updates?  Also, there was a change today, but not sure it'll make a difference.

**Comment by cigamit** [comment]
@JorisFRST, hey we are getting close to release.  Did you try to decrease the boost frequency to something like an hour or so?

**Comment by JorisFRST** [comment]
Hi, set boost to 1 hour now. I'll see how it behaves

**Comment by JorisFRST** [comment]
I think the issue was boost was not enabled anymore (I was troubleshooting the issue with the graphs not updating when viewing them)  After enabling boost again dsstats is behaving.

**Comment by cigamit** [comment]
Okay, I'll keep this open as a feature request though.  Don't want to crash a system for people who have not read the instructions, which might be missing after all as this is OSS :)

**Comment by JorisFRST** [comment]
Yes, entirely my fault, disabled something troubleshooting another thing, and it all went tits up.
Would be a nice feature to not be able to enable dsstats without boost.

**Comment by TheWitness** [comment]
This issue is fixed and will be in 1.2.11.
