### ISSUE TITLE
When user/group permissions are reset, this is not reflected immediately to the end user

### ISSUE THREAD

**Issue by YongBoLiu** [Cacti/cacti#2584]
**Describe the bug**
Change permission, it not effect immediately. you have to re-login to see it works.

**To Reproduce**
1. Go to Console-> user -> permission.
2. Change some permissions and save.
3. It will not effective.
4. You have to logout then login to see it works.

**Expected behavior**
Permission change effect immediately, don't need to re-login.

**Desktop (please complete the following information):**
 - Version [1.2.2]

**Additional context**

It is because the user_perms_valid() always return true. Details is below,

When login,
In first call of user_perms_valid() in session 1. As $_SESSION['sess_user_perms_key'] is NOT set yet. It set the $_SESSION['sess_user_perms_key'] and return true.

In second call of user_perms_valid()  in session 1. As the $valid is set to true, the $_SESSION['sess_user_perms_key'] is set to $valid and return true.

Then the user_perms_valid() always return true.  
```
				if ($key != $_SESSION['sess_user_perms_key']) {
					$valid = false;
				}
```
Because 
# php -r "if('2292476146' != true) echo 'NOT'; else echo 'EQ';"
EQ

This also makes user_perms_valid() always return true When permission changed. Because the  $_SESSION['sess_user_perms_key'] is true seems equals any number.

The root cause i think is, we don't need to set $_SESSION['sess_user_perms_key'] to true when $valid is true. The fix as below,
```
diff -u -N rtm/cacti/lib/auth.php rtm/cacti/lib/auth.php
--- rtm/cacti/lib/auth.php	2019-02-28 10:53:15.000000605 +0800
+++ rtm/cacti/lib/auth.php	2019-03-29 16:16:59.000000570 +0800
@@ -2566,7 +2566,6 @@
 		}
 	} else {
 		$valid = true;
-		$_SESSION['sess_user_perms_key'] = $valid;
 	}
 
 	return $valid;

```
It works well in my env. Please confirm. Thanks.

**Comment by netniV** [comment]
This has now been committed to the development code.
