### ISSUE TITLE
The form_alternate_row_color() is not work well or compatiable with version before (like 0.88)

### ISSUE THREAD

**Issue by YongBoLiu** [Cacti/cacti#2585]
**Describe the bug**
The row color can't be customized. Better compatible with the function before.

**To Reproduce**
1. Go to some plugin pages using the form_alternate_row_color() .
2. Not works well in cacti 1.2.2. The color can't be customized.

**Expected behavior**
The color can be customized. Just as version before , such as cacti 0.88

**Additional context**

In 0.88b,  The color can be customized. Code is below,
```
function form_alternate_row_color($row_color1, $row_color2, $row_value, $row_id = "") {
    if (($row_value % 2) == 1) {
        $current_color = $row_color1;
    }else{
        $current_color = $row_color2;
    }

    if (strlen($row_id)) {
        print "<tr id='$row_id' bgcolor='#$current_color'>\n";
    }else{
        print "<tr bgcolor='#$current_color'>\n";
    }

    return $current_color;
}
```

In 1.2.x,  The color can NOT be customized. Code is below,
```
function form_alternate_row_color($row_color1, $row_color2, $row_value, $row_id = '') {
    if ($row_value % 2 == 1) {
            $class='odd';
            $current_color = $row_color1;
    } else {
        if ($row_color2 == '' || $row_color2 == 'E5E5E5') {
            $class = 'even';
        } else {
            $class = 'even-alternate';
        }
        $current_color = $row_color1;
    }

    if ($row_id != '') {
        print "<tr class='$class selectable tableRow' id='$row_id'>\n";
    } else {
        print "<tr class='$class tableRow'>\n";
    }

    return $current_color;
}
```
So, the $row_color1, $row_color2 is NOT be used in cacti 1.2.x. 

Could you merge the code below, to make it work as before. And the $disabled is considered as in form_alternate_row().
```
diff -u -N rtm/cacti/lib/html_utility.php rtm/cacti/lib/html_utility.php
--- rtm/cacti/lib/html_utility.php	2019-02-28 10:53:15.000000719 +0800
+++ rtm/cacti/lib/html_utility.php	2019-03-29 17:17:22.000000220 +0800
@@ -99,7 +99,7 @@
      to display for this particular row. must be an integer
    @arg $row_id - used to allow js and ajax actions on this object
    @returns - the background color used for this particular row */
-function form_alternate_row_color($row_color1, $row_color2, $row_value, $row_id = '') {
+function form_alternate_row_color($row_color1, $row_color2, $row_value, $row_id = '', $disabled = false) {
 	if ($row_value % 2 == 1) {
 			$class='odd';
 			$current_color = $row_color1;
@@ -112,10 +112,11 @@
 		$current_color = $row_color1;
 	}
 
+	$selectable = ($disabled ? ' selectable': '');
 	if ($row_id != '') {
-		print "<tr class='$class selectable tableRow' id='$row_id'>\n";
+		print "<tr class='tableRow". ($disabled ? '':' selectable') . "' bgcolor='#$current_color' id='$row_id'>\n";
 	} else {
-		print "<tr class='$class tableRow'>\n";
+		print "<tr class='tableRow". ($disabled ? '':' selectable') . "' bgcolor='#$current_color'>\n";
 	}
 
 	return $current_color;
```

Thanks.

**Comment by netniV** [comment]
I believe that was intentional to keep things more uniform look and feel based upon the theme.

**Comment by YongBoLiu** [comment]
But in 0.88x, this function is for customize the color. Now in 1.2.x, this behave is changed. The $current_color is not be used, so what's the use of having the $row_color1, $row_color2 parameters.

**Comment by netniV** [comment]
Historic compatibility to prevent breaking plugins.  @cigamit may have something else to add.

**Comment by YongBoLiu** [comment]
Got it. Thanks.

**Comment by ddb4github** [comment]
BTW,  syslog and thold also have row color customization requirement.  

    syslog plugin create a new function syslog_row_color to implement it.
    thold directly output '<tr>' with specified color

**Comment by TheWitness** [comment]
The goal of the team, going back nearly a decade, was to remove use of all colors and use css/classes instead.  This function was left around to ease migration.
