### ISSUE TITLE
Graph Tree Alphabetic Ordering not working

### ISSUE THREAD

**Issue by jdcoats** [Cacti/cacti#2587]
Go to management/trees and set the tree sorting type to Alphabetic Ordering and It does not change the order correctly.

**Comment by lux4rd0** [comment]
I've seen this similar behavior in the last few dot releases. My tree orders will bounce around based on which Tree I've last been editing. So if I save a tree - that particular tree will go to the top or near the top of the List. Then it'll stay there until I hit the little "alphabetize" icon - which then puts them back in order.

Before:

![Screen Shot 2019-05-21 at 11 25 58 PM](https://user-images.githubusercontent.com/30187533/58147394-dfad0780-7c1f-11e9-9b2b-41644efb7d48.png)

Edit and save the "Storage" tree and this is now the order:

![Screen Shot 2019-05-21 at 11 26 19 PM](https://user-images.githubusercontent.com/30187533/58147402-e9cf0600-7c1f-11e9-991f-41c46513011f.png)

**Comment by cigamit** [comment]
Actually, there is no pure ordering.  If you sort by the 'order' field, you see what the ordering is.  You can then drag and drop the ordering.  If you click the sort buttons, then the tree's a resorted the either ascending or descending.  However, the default sort is manual and has always been there.  Hope that is clear.
