### ISSUE TITLE
Consider 1.2.2 showing on mobile phones like 0.8.8?

### ISSUE THREAD

**Issue by tyit** [Cacti/cacti#2588]
![image](https://user-images.githubusercontent.com/31933126/55270786-72938a80-52de-11e9-9104-fe775237bd04.png)
![image](https://user-images.githubusercontent.com/31933126/55270797-9787fd80-52de-11e9-96e7-bf6d44e5dc39.png)

![image](https://user-images.githubusercontent.com/31933126/55270802-a969a080-52de-11e9-9a73-6a690451ef07.png)
![image](https://user-images.githubusercontent.com/31933126/55270808-b8e8e980-52de-11e9-9df4-c17354c2218c.png)

I want to use a mobile phone to see outside the business trip, 1.2.2 but I can't see the graphics at all. Consider 1.2.2 showing on mobile phones like 0.8.8? 

Thanks in advance

**Comment by cigamit** [comment]
Can you please try one of the other themes?

**Comment by Susanin63** [comment]
Hi!
I have already raised this issue on the [forum ](https://forums.cacti.net/viewtopic.php?f=21&t=58521)
For this reason, you cannot fully use all plugins, sometimes important columns in tables are hidden.
Changing the theme does not help.

And I found a solution!
in /lib/html.php:2278
`<meta content='width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0' name='viewport'`>
I change to
`<meta content='width=device-width, initial-scale=0.4, minimum-scale=0.4, maximum-scale=5.0' name='viewport'>`

or even delete it!

And now all work like old version - with pinch zoom on mobile!

**Comment by tyit** [comment]
@cigamit @Susanin63 

Thank you very much, I tried to operate

**Comment by tyit** [comment]
@Susanin63 

Great, I changed it, it works fine.
