### ISSUE TITLE
Language selection is not working as expected

### ISSUE THREAD

**Issue by whsir** [Cacti/cacti#2590]
Install 1.2.3 version
language change no succeed
no change

**Comment by netniV** [comment]
I have just tested this without issue, please let us know if you have any browser console errors within the brower's developer tools

**Comment by whsir** [comment]
browser version Google Chrome 73.0.3683.86

**Comment by whsir** [comment]
![f1](https://user-images.githubusercontent.com/46343402/55369069-93025580-5527-11e9-9706-e684a8405386.gif)

**Comment by whsir** [comment]
![image](https://user-images.githubusercontent.com/46343402/55369103-b927f580-5527-11e9-8701-4861a7da2e5a.png)
language no change

**Comment by whsir** [comment]
![image](https://user-images.githubusercontent.com/46343402/55369120-d957b480-5527-11e9-8571-94947491db8e.png)
![image](https://user-images.githubusercontent.com/46343402/55369132-e1175900-5527-11e9-852e-6426640674ba.png)

**Comment by netniV** [comment]
OK, so the issue is not that the language isn't changing, but that it keeps defaulting back to english?

**Comment by whsir** [comment]
yes，language defaulting english

**Comment by whsir** [comment]
Change again language 
![image](https://user-images.githubusercontent.com/46343402/55369858-de6a3300-552a-11e9-8552-9ed1632c8bb5.png)

next、next、next...

Until he finished

![image](https://user-images.githubusercontent.com/46343402/55369895-0ce80e00-552b-11e9-900a-1280e2b70242.png)
![image](https://user-images.githubusercontent.com/46343402/55369904-13768580-552b-11e9-8599-bea5d0b98f7e.png)

language defaulting english

**Comment by whsir** [comment]
![image](https://user-images.githubusercontent.com/46343402/55369964-58022100-552b-11e9-81a1-ae85eac1bc0a.png)

Change language，
must
Clear browser cache

**Comment by whsir** [comment]
now
if Settings language english
then
save no change
Clear browser cache，no change

now Chinese

Language switching should be a problem！

**Comment by whsir** [comment]
说了这么多，不知道你是否明白我的想法:smile:

**Comment by netniV** [comment]
OK, we will look into this

**Comment by TheWitness** [comment]
What do you guys thing about storing the last language used in localStorage, that way the login/logout will work as well (at least on the browser you last logged into).
