### ISSUE TITLE
Drill down to some pages may be incorrect due to logic issues

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/cacti#2591]
**To Reproduce**
1) Go to Utilitites -System utilitites page
2) Click SNMP Notification Receivers, drill down to other page
3) Page show under RTM License Services - Managers  -- failed

**Screenshots**
![Screen Shot 2019-03-26 at 4 28 50 PM](https://user-images.githubusercontent.com/47589910/55300716-6f79d500-546b-11e9-96be-528f3f135704.png)
![Screen Shot 2019-03-26 at 4 29 06 PM](https://user-images.githubusercontent.com/47589910/55300717-71439880-546b-11e9-83e8-db6fbeb9ed06.png)

**Desktop (please complete the following information):**
 - OS: rhel73 x64
 - Browser: FF
 - Version :cacti1.2.2

**Comment by netniV** [comment]
This is due to another page having the same filename and the way that the menu structure works.  It also occurred for #2430 but in your case, this is a third party plugin that is messing it up.

**Comment by TheWitness** [comment]
Yingbaiibm, suggest you rename the license managers file to lic_managers.php.  Since this a third party plugin issue, I'll close.

**Comment by yingbaiibm** [comment]
@TheWitness @netniV   it is actually the lic_managers.php we are using now.   When drill down to SNMP notification receivers, it replace our lic_managers.php URL and show mangers.php. We are not using the name managers.php 

The point is when drill down to other link like view_snmpagent_cache, the URL will change to http://IP/cacti/utilities.php**?action=view_snmpagent_cache**

But when drill down to SNMP notification receivers, it goes to http://IP/**cacti/managers.php**.  What I thought it should be also like above http://IP/cacti/utilities.php**?action=xxxx**.  Then this problem will not happen.

**Comment by netniV** [comment]
This sounds like you have a URL problem going to the old address and the old managers.php file is still around?

**Comment by ddb4github** [comment]
Current behavior is:
    1. Access "System Utilities -> SNMP notification receivers"
    2.  cacti/utilities.php auto-forward to cacti/managers.php
    3.  During  ajax loading-page,   auto-fuzzy-match to cacti/plugins/xxx_managers.php, and auto-expend to that menu item.

Force reload browser with cacti/managers.php by key#F5,  non-auto-expand.

**Comment by yingbaiibm** [comment]
@TheWitness @ddb4github  can you open and fix this issue ?
