### ISSUE TITLE
Display graphs from this aggregate can not work

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/cacti#2592]
**To Reproduce**
1) Create an aggregate graph for a graph
2) Go to graphs page, check the aggregate graph
3) Click Display graphs from this aggregate  icon
4) Can not show graph well -- failed

**Screenshots**
![Screen Shot 2019-03-26 at 3 14 17 PM](https://user-images.githubusercontent.com/47589910/55300859-43ab1f00-546c-11e9-8e6b-3e7880df8e95.png)
![Screen Shot 2019-03-26 at 3 14 32 PM](https://user-images.githubusercontent.com/47589910/55300861-4574e280-546c-11e9-918b-c0adf6bdeee6.png)

**Desktop (please complete the following information):**
 - OS: rhel73 x64
 - Browser FF
 - Version cacti1.2.2

**Comment by cigamit** [comment]
Ah, I see the issue now.

**Comment by cigamit** [comment]
Good catch.  Resolved.
