### ISSUE TITLE
Can not migrate aggregate to use a template

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/cacti#2593]
**To Reproduce**
1) Create aggregate template for GRID - Cluster Efficiency
2) Create aggregate graph for GRID - Cluster Efficiency graph not using template
3) Click the aggregate graph, choose migregate aggregate to use a template -- failed.

2019/03/26 14:57:58 - CMDPHP ERROR: A DB Row Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') AND graph_template_id>0' at line 1
2019/03/26 14:57:58 - CMDPHP SQL Backtrace:  (/aggregate_graphs.php[61]:form_actions(), /aggregate_graphs.php[368]:db_fetch_assoc(), /lib/database.php[450]:db_fetch_assoc_prepared(), /lib/database.php[464]:db_execute_prepared())

**Expected behavior**

**Screenshots**
![Screen Shot 2019-03-26 at 2 49 07 PM](https://user-images.githubusercontent.com/47589910/55300936-a6041f80-546c-11e9-816e-ffd3994dbc3c.png)
![Screen Shot 2019-03-26 at 2 48 16 PM](https://user-images.githubusercontent.com/47589910/55300939-a8ff1000-546c-11e9-927c-d075eac9e021.png)
![Screen Shot 2019-03-26 at 2 49 18 PM](https://user-images.githubusercontent.com/47589910/55300941-abfa0080-546c-11e9-8329-ccb6546cfe6b.png)
![Screen Shot 2019-03-26 at 2 48 43 PM](https://user-images.githubusercontent.com/47589910/55300943-af8d8780-546c-11e9-90eb-36a4645a519a.png)

**Desktop (please complete the following information):**
 - OS: rhel73 x64
 - Browser FF
 - Version cacti 1.2.2

**Comment by cigamit** [comment]
Good catch.  Resolved.
