### ISSUE TITLE
Cacti 1.2.3 Change language does not respond . No next step

### ISSUE THREAD

**Issue by tyit** [Cacti/cacti#2597]
![image](https://user-images.githubusercontent.com/31933126/55301699-7e16bb00-5470-11e9-9094-1c6947a2968d.png)

Change language does not respond

![image](https://user-images.githubusercontent.com/31933126/55301674-4dcf1c80-5470-11e9-81de-691a22becbfa.png)

No next step

**Comment by netniV** [comment]
I just tested the changing of languages and it works as expected.  Please give more information on the browser including versions and any console errors.

**Comment by tyit** [comment]
I am upgrading 1.2.3 from 1.2.2
Browser Chrome

**Comment by netniV** [comment]
There seems to be an issue as #2590 seems to have the same issue

**Comment by netniV** [comment]
Duplicate #2590

**Comment by ckaraca** [comment]
Even if you change the language, on the next session cacti returns to the native language of the browser. On the graphs we get an error "Error: invalid color def format" when we see the menu items as Turkish

**Comment by netniV** [comment]
If you are on 1.2.7 and have an issue, it should be opened separately.
