### ISSUE TITLE
[Aggregate] Create aggregate without aggregate graph tempate, rrdtools error 

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/cacti#2598]
**To Reproduce**
1) Go to management - graphs page
2) Choose a graph and  create aggregate graph
3) After save the aggregate graph,  preview tab can not see the graph. unknow RRDtool error.  --failed 
4) If create aggregate graph with aggregate template, then in preview tab, the graph can be show well. 

**Expected behavior**
At preview tab, graph can show well for aggregate graph created without aggregate template.

**Screenshots**
![Screen Shot 2019-04-01 at 3 32 20 PM](https://user-images.githubusercontent.com/47589910/55310612-7ddbe700-5493-11e9-9c93-aa9df0b08779.png)
![Screen Shot 2019-04-01 at 3 32 46 PM](https://user-images.githubusercontent.com/47589910/55310616-7e747d80-5493-11e9-994d-e41185aff7ba.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] rhel73 x64
 - Browser [e.g. chrome, safari] FF
 - Version [e.g. 22] cacti1.2.2

**Comment by cigamit** [comment]
Can you please provide the error, or the debug output from the Preview tab with debug enabled?

**Comment by cigamit** [comment]
@yingbaiibm, second piece that we need is a screen capture of how you went about creating the aggregate.  Nee to know what you included and skipped and the various settings that drove this error.

**Comment by yingbaiibm** [comment]
It's just simple aggregate graph creation, do not need to change anything. 
After click save button, the RRDtools error will exist. 
No error log in cacti.log 
NO error in /var/log/httpd/error_log

cacti 1.2.3 
rhel73 x64 
FF 

![1](https://user-images.githubusercontent.com/47589910/55926963-f0905380-5c45-11e9-9b37-5d797efd38f6.png)
![2](https://user-images.githubusercontent.com/47589910/55926971-f5550780-5c45-11e9-9341-d552a567593c.png)
![3](https://user-images.githubusercontent.com/47589910/55926975-f71ecb00-5c45-11e9-85f0-84a55e7f17a9.png)
![4](https://user-images.githubusercontent.com/47589910/55926978-f9812500-5c45-11e9-90b6-c0197fa44b0b.png)
![5](https://user-images.githubusercontent.com/47589910/55926984-fd14ac00-5c45-11e9-9e4c-168d5e92d202.png)
![6](https://user-images.githubusercontent.com/47589910/55926985-fe45d900-5c45-11e9-9d12-da7a5f31167b.png)

Append detail graph debug info for this graph 
RRDtool Command:
------------------------------------------------
/bin/rrdtool graph - \
--imgformat=PNG \
--start='-86400' \
--end='-300' \
--pango-markup  \
--title='Aggregate - GRID Available Memory' \
--vertical-label='available memory' \
--slope-mode \
--base=1000 \
--height=120 \
--width=500 \
--tabwidth '30' \
--rigid \
--alt-autoscale-max \
--lower-limit='0' \
COMMENT:"From 2019/04/10 10\:41\:40 To 2019/04/11 10\:36\:40\c" \
COMMENT:"  \n" \
--color BACK#F3F3F3 \
--color CANVAS#FDFDFD \
--color SHADEA#CBCBCB \
--color SHADEB#999999 \
--color FONT#000000 \
--color AXIS#2C4D43 \
--color ARROW#2C4D43 \
--color FRAME#2C4D43 \
--border 1 --font TITLE:11:'Arial' \
--font AXIS:8:'Arial' \
--font LEGEND:8:'Courier' \
--font UNIT:8:'Arial' \
--font WATERMARK:6:'Arial' \
--slope-mode \
--watermark 'Generated by Cacti®' \

RRDtool Says:
--------------------------------------------------

**Comment by cigamit** [comment]
This is completely understandable as you skipped all items.  I guess maybe the right thing to do would be to block the save button unless one item was not marked to skip.  Easy enough to force fix.  It's a minor issue though.

**Comment by cigamit** [comment]
Okay, until you click at least one 'total' item, you can no longer save.  That should cover this issue well.
