### ISSUE TITLE
[Aggregate]SQL error when create aggregate graph 

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/cacti#2599]
**To Reproduce**
1. Go to management - Graphs page 
2. Choose a graph and create aggregate graph
3. Totaling set as **print all legend items** 
4. Total type set as **Total all datasource** 
5. Re-set Totaling value as **No tota**l 
Save the aggregate graph and error exist. 
6. Modify exist aggregate graph, Totaling and Total type also can not work well. 

04/01/2019 15:56:06 - CMDPHP ERROR: A DB Exec Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE local_graph_id = '3008' AND graph_type_id IN ('20')' at line 1
04/01/2019 15:56:06 - CMDPHP SQL Backtrace:  (/var/www/html/cacti/graphs.php[80]:form_actions(), /var/www/html/cacti/graphs.php[767]:aggregate_create_update(), /lib/api_aggregate.php[1188]:aggregate_handle_stacked_lines(), /lib/api_aggregate.php[1398]:db_execute_prepared())
04/01/2019 15:56:13 - CMDPHP ERROR: A DB Exec Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE local_graph_id = '3008' AND graph_type_id IN ('20')' at line 1
04/01/2019 15:56:13 - CMDPHP SQL Backtrace:  (/var/www/html/cacti/aggregate_graphs.php[58]:form_save(), /var/www/html/cacti/aggregate_graphs.php[238]:push_out_aggregates(), /lib/api_aggregate.php[946]:aggregate_create_update(), /lib/api_aggregate.php[1188]:aggregate_handle_stacked_lines(), /lib/api_aggregate.php[1398]:db_execute_prepared())

**Expected behavior**
1. When re-set Totaling value as 'no Total', the total type value and prefix for Gprint totals value should be auto changed.  
2. When modify the aggregate graph, if set Totaling as 'no total', should not change Total type and Gprint totals value

**Screenshots**
![Screen Shot 2019-04-01 at 4 07 54 PM](https://user-images.githubusercontent.com/47589910/55312548-63f0d300-5498-11e9-9cf5-2f9e2b07e538.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] rhel73 x64
 - Browser [e.g. chrome, safari] FF 
 - Version [e.g. 22] cacti1.2.2

**Comment by cigamit** [comment]
Good catch.  Resolved.
