### ISSUE TITLE
External link can not be added at Top Console and Bottom Console page 

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/cacti#2602]
**Describe the bug**

**To Reproduce**
1) Go to utilitites - External link page
2) Add an external link, choose top of console page type external link or bottom top of console page type
3) After saving the external link, can not see the newly added link in console page 

**Expected behavior**
newly added external link info should be shown in cacti/index.php  

**Screenshots**
![Screen Shot 2019-04-01 at 5 32 56 PM](https://user-images.githubusercontent.com/47589910/55318011-504b6980-54a4-11e9-90bd-e72a39e46034.png)
![Screen Shot 2019-04-01 at 5 33 22 PM](https://user-images.githubusercontent.com/47589910/55318021-517c9680-54a4-11e9-987c-ed306aab1ef5.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] rhel73 x64
 - Browser [e.g. chrome, safari] FF
 - Version [e.g. 22] cacti1.2.2

**Comment by TheWitness** [comment]
@yingbaiibm, this is not a cacti issue.  It's caused by a third party plugin likely one of the RTM ones.
