### ISSUE TITLE
[data query] SQL error when add a dataquery

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/cacti#2604]
**To Reproduce**
1) Go to Data Collection - Data Query page
2) Add a Data Query, error exist in log 

2019/04/02 14:12:39 - ERROR PHP NOTICE: Undefined variable: previous_input_id in file: /var/www/html/cacti/data_queries.php  on line: 143
2019/04/02 14:12:39 - CMDPHP PHP ERROR NOTICE Backtrace:  (/var/www/html/cacti/data_queries.php[39]:form_save(), /var/www/html/cacti/data_queries.php[143]:CactiErrorHandler())

![Screen Shot 2019-04-02 at 2 14 50 PM](https://user-images.githubusercontent.com/47589910/55380336-7a5b6500-5552-11e9-9c19-465e7ee87591.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] rhel73 x64
 - Browser [e.g. chrome, safari] FF 
 - Version [e.g. 22] cacti1.2.2

**Comment by cigamit** [comment]
Good catch.  Resolved.
