### ISSUE TITLE
Add IPv4 and IPv6 Specific Counters to interfaces.xml

### ISSUE THREAD

**Issue by reubenfarrelly** [Cacti/cacti#261]
I've been running with this patch for a while now - and it has been very useful to help me determine how much IPv4 specific and IPv6 specific traffic I have been seeing coming and going out of my WAN links.  This is known to work with Cisco IOS devices (routers, at least, probably switches too).

This patch just adds IPv4 and IPv6 specific counters as an option to resource/snmp_queries/interfaces.xml.

[interface.xml-addipv4v6.patch.txt](https://github.com/Cacti/cacti/files/747679/interface.xml-addipv4v6.patch.txt)

**Comment by ronytomen** [comment]
You could do a pull request.. :)

**Comment by cigamit** [comment]
Resolved, thanks!
