### ISSUE TITLE
Data Sources troubleshooter generates warning that each() function is deprecated

### ISSUE THREAD

**Issue by gbonny1982** [Cacti/cacti#2610]
When Troubleshooting - Data Sources I see two error messages in the logging:

ERROR PHP DEPRECATED: The each() function is deprecated. This message will be suppressed on further calls in file: /opt/cacti/data_debug.php on line: 171 
CMDPHP PHP ERROR Backtrace: (/data_debug.php[41]:form_actions(), /data_debug.php[171]:each(), CactiErrorHandler()) 

On Ubuntu 18.04 LTS + PHP7.2 with latest patches.

https://www.php.net/manual/en/migration72.deprecated.php
https://www.php.net/manual/en/function.each.php
The function "foreach()" is suggested as a solution.

**Comment by netniV** [comment]
Hmm, I thought we'd removed all of those, this appears to have been introduced afterwards.
