### ISSUE TITLE
Management console page blank in FireFox

### ISSUE THREAD

**Issue by KnoAll** [Cacti/cacti#2611]
**Describe the bug**
After navigating around in the management console (devices, sites, etc) the main frame will periodically go blank with the only way to get the page to display again is a full page refresh. 

**To Reproduce**
1. Go to 'Devices.'
2. Click on 'a host, back to sites, etc.'
3. Main frame will go blank randomly

**Expected behavior**
Hosts, sites, etc should be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/7632685/55512142-2e262880-5617-11e9-9f2c-196f7bf5b458.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: broken in FireFox, seems to work reliably in Chrome and IE.

**Comment by netniV** [comment]
Use the developer tools of your browser to see if there are any console errors.

**Comment by KnoAll** [comment]
Does this help?
![image](https://user-images.githubusercontent.com/7632685/55582839-4f4d4e80-56d5-11e9-99c2-2ef010ca5422.png)

**Comment by netniV** [comment]
Which version of cacti is this? I can find line 14 of Dark's main.js calling keepWindowSize() but the point in layout.js that claims to have an issue is another internal function call so should be more of a call stack.

**Comment by KnoAll** [comment]
It is 1.2.3, but has been happening since 1.1.x, cant recall exactly how far back.

**Comment by netniV** [comment]
Your layout.js seems to be wrong.  The line numbers do not add up.

**Comment by KnoAll** [comment]
I'm seeing this across multiple installs too

**Comment by netniV** [comment]
I'll take a look .. are all the ones with an issue on the dark theme?

**Comment by KnoAll** [comment]
no, dark and modern as in the original screenshot

**Comment by netniV** [comment]
is the stack trace the same on Modern?

**Comment by KnoAll** [comment]
yes, just confirmed

**Comment by netniV** [comment]
Is this install from develop // git, or via a package?

**Comment by KnoAll** [comment]
One of each. Dark is via package, and Modern is from git. It looks as thought he modern is actually on 1.2.4

**Comment by netniV** [comment]
Well, I have just tested both 1.3 and 1.2.4 and neither have generated errors on my mac running Firefox Quantum 65.0.  I will test a PC tomorrow, but this looks like either you have an addon/extension that is mangling the javascript at the moment.

**Comment by KnoAll** [comment]
Interesting. I'll test on my Mac at home tonight....

**Comment by netniV** [comment]
OK, I'll wait on your response 👍

**Comment by KnoAll** [comment]
Could not reproduce on my Mac, but verified it on another windows box. I checked the plugins and it appears that the 'LastPass' extension is causing this. Not sure how or why, but when it is disabled I cannot reproduce.

**Comment by cigamit** [comment]
Can you please change the function only slightly and see if the problem goes away.

Just make the following change:

``code
});

$(window).trigger('resize');
```

to 

```code
}).trigger('resize');
```

Let us know if that fixes the issue.

**Comment by KnoAll** [comment]
I see that string in many places across several files. Which location/s should I change?

**Comment by cigamit** [comment]
Sorry, line 2645 in layout.js.  Sorry, assumed you were able to interpret the stack trace.

**Comment by KnoAll** [comment]
Apologies, bonehead move. I'm an infrastructure guy not a developer!

**Comment by cigamit** [comment]
Funny, I know what you mean.

**Comment by KnoAll** [comment]
Doesn't seem to have resolved

**Comment by cigamit** [comment]
Okay, do this instead, take out the .trigger('resize'); and add a new line below as follows:

```code
window.dispatchEvent(new Event('resize'));
```

**Comment by KnoAll** [comment]
now looks like this...
        })
        window.dispatchEvent(new Event('resize'));
}

with no change in behavior

**Comment by cigamit** [comment]
You need a semicolor after the }).  Also, you need to force a reload.  It's more difficult in Chrome.  In Firefox on Windows, just hit the circle with the arrow button on the address bar.  On Chrome, you have to browse directly to the layout.js file, and then once you can see it, then hit the refresh button.  It's insane.

**Comment by KnoAll** [comment]
ok, updated the ;

after hard refresh (FireFox) still the same

**Comment by cigamit** [comment]
I think we should write this off to an offensive Firefox plugin bug don't you?

**Comment by KnoAll** [comment]
Sadly have to agree. Was not able to reproduce on chrome with the lastpass extension.

**Comment by cigamit** [comment]
Thanks.  You should report this to the author of that plugin.
