### ISSUE TITLE
Issue when i try and update via YUM

### ISSUE THREAD

**Issue by gllewellyn** [Cacti/cacti#2615]
I am running 

Technical Support [Summary]
General Information
Date	Thu, 04 Apr 2019 12:50:30 +0000
Cacti Version	1.2.1
Cacti OS	unix
RSA Fingerprint	80:6a:64:f4:30:b0:ec:ba:1e:62:09:83:00:a2:a6:67
NET-SNMP Version	NET-SNMP version: 5.7.2
RRDtool Version Configured	1.4.0+
RRDtool Version Found	1.4.8
Devices	164
Graphs	30,650
Data Sources	Script/Command: 5
SNMP Query: 30,379
Script Query: 2
Total: 30,386
Poller Information
Interval	300
Type	SPINE 1.2.1 Copyright 2004-2017 by The Cacti Group
Items	Action[0]: 82,152
Action[1]: 9
Total: 82,161
Concurrent Processes	4
Max Threads	15
PHP Servers	5
Script Timeout	25
Max OID	20
Last Run Statistics	Time:42.1600 Method:spine Processes:4 Threads:15 Hosts:160 HostsPerProcess:40 DataSources:82161 RRDsProcessed:27517

And trying to do upgrade via YUM

[root@gcp3451prdsrv01 xxxxx]# yum update
Resolving Dependencies
--> Running transaction check
---> Package cacti.noarch 0:1.2.0-1.el7 will be updated
---> Package cacti.noarch 0:1.2.3-1.el7 will be an update
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package       Arch           Version                Repository            Size
================================================================================
Updating:
 cacti         noarch         1.2.3-1.el7            epel-testing          19 M

Transaction Summary
================================================================================
Upgrade  1 Package

Total download size: 19 M
Is this ok [y/d/N]: y
Downloading packages:
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
cacti-1.2.3-1.el7.noarch.rpm                               |  19 MB   00:01
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Updating   : cacti-1.2.3-1.el7.noarch                                     1/2
Error unpacking rpm package cacti-1.2.3-1.el7.noarch
warning: /etc/cacti/db.php created as /etc/cacti/db.php.rpmnew
error: unpacking of archive failed on file /usr/share/cacti/cache: cpio: rename
  Verifying  : cacti-1.2.3-1.el7.noarch                                     1/2
cacti-1.2.0-1.el7.noarch was supposed to be removed but is not!
  Verifying  : cacti-1.2.0-1.el7.noarch                                     2/2

Failed:
  cacti.noarch 0:1.2.0-1.el7             cacti.noarch 0:1.2.3-1.el7

Complete!

**Comment by netniV** [comment]
I have seen that, you need to make sure you have the package installed to allow deltas with yum.  Also, check your yum history, you'll likely have an earlier package that also failed.  If you look at the details, you will see what caused the failure.

**Comment by netniV** [comment]
@mortenstevens - this is very similar to that issue I emailed you about the other week, won't really know until there is more information on the actual error.

**Comment by mortenstevens** [comment]
@netniV 
This is not a bug.

It's not allowed to store cache data to /usr/share/cacti/cache
When installing cacti RPM packages for Fedora or Fedora-RHEL it creates automatically a symlink from /usr/share/cacti/cache to /var/lib/cacti/cache/

For example on my installation:
ls -l cache
lrwxrwxrwx. 1 root root 20 Feb 25 13:47 cache -> /var/lib/cacti/cache

If users are going to deleting the symlink and storing cache folders/data to /usr/share/cache/cacti we can't do anything.

The upgrade failed, because our RPM package expects a symlink and not a cache directory in /usr/share/cacti/cache

**Comment by netniV** [comment]
Well I guess we'd need to know if @gllewellyn did do that themselves.  If not, something seems to be suddenly causing this issue.  Could it be that Cacti is creating it if the poller is running during the upgrade?

**Comment by cigamit** [comment]
Since this is a packaging issue, I'm going to close.  Thanks for all your support @mortenstevens!
