### ISSUE TITLE
Graphs export

### ISSUE THREAD

**Issue by carboxste** [Cacti/cacti#2617]
**Describe the bug**
Could you add the graphs export support. We need to copy the png images to customers's home dir. In the old version you can set cache dir but with 1.2.2 and 1.2.3 there is only the cache/boost and the images are un readable.

 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by netniV** [comment]
https://github.com/cacti/plugin_gexport/
