### ISSUE TITLE
"Reapply Suggested Names" does not work on "Empty Graph"

### ISSUE THREAD

**Issue by jenhek** [Cacti/cacti#2619]
**Describe the bug**
Looks like "Reapply Suggested Names"  with graphs does not work anymore
at least since Cati 1.2.2

**To Reproduce**

Rediscover a device with new graphs

Console/Management/Graphs, find Device, mark all graphs, scroll down 
and select "Reapply ..." and press "go"

3. It then

shows correctly what to do

and after that I a have again "Empty Graphs"

**Expected behavior**

It should work like in "Data Sources, where all is correct

**Comment by cigamit** [comment]
Any errors in the Cacti log?

**Comment by cigamit** [comment]
No feedback.

**Comment by jenhek** [comment]
Sorry. Was away from work for some weeks. No, I did not see any errors.
