### ISSUE TITLE
Missing "add" button for Data Collectors

### ISSUE THREAD

**Issue by Serazio** [Cacti/cacti#262]
Hi,

it seams the "Add" button inside of the "Data Collectors" view is missing. 

Using "pollers.php?action=edit" inside the url will help shortly. 

replace line 498 from 
html_start_box( __('Data Collectors'), '100%', '', '3', 'center', '');
to
html_start_box( __('Data Collectors'), '100%', '', '3', 'center', 'pollers.php?action=edit');

**Comment by cigamit** [comment]
This is not a bug.  It was done this way by design so that users would be forced to create remote data collectors through the installation process on the remote device.
