### ISSUE TITLE
Erro during update

### ISSUE THREAD

**Issue by arbenatti** [Cacti/cacti#2620]
I'm trying to update my cacti (using centos 7.6 1810 rpm package), but after some errors and using the other bug reports, I don't se what happening anymore, see bellow. What can I do to get my cacti working again?

+++++++++++++++++++++++++++++++

Cacti Server v1.2.2 - Installation Wizard
Error

Your Cacti Server v1.2.2 has been installed/updated with errors
Process Log

2019/04/05 09:17:35 - INSTALL: always: Installation was started at 2019-04-05 12:16:19, completed at 2019-04-05 12:17:35
2019/04/05 09:17:35 - INSTALL: always: WARNING: One or more upgrades failed to install correctly
2019/04/05 09:17:35 - INSTALL: always: Finished UPGRADE Process for v1.2.2
2019/04/05 09:17:18 - INSTALL: always: Upgrading from v1.1.31 (DB 1.1.31) to v1.1.34
2019/04/05 09:17:17 - INSTALL: always: Upgrading from v1.1.28 (DB 1.1.28) to v1.1.31
2019/04/05 09:17:17 - INSTALL: always: Upgrading from v1.1.26 (DB 1.1.26) to v1.1.28
2019/04/05 09:17:17 - INSTALL: always: Upgrading from v1.1.20 (DB 1.1.20) to v1.1.26
2019/04/05 09:17:16 - INSTALL: always: Upgrading from v1.1.17 (DB 1.1.17) to v1.1.20
2019/04/05 09:17:16 - INSTALL: always: Upgrading from v1.1.14 (DB 1.1.14) to v1.1.17
2019/04/05 09:17:16 - INSTALL: always: Upgrading from v1.1.11 (DB 1.1.11) to v1.1.14
2019/04/05 09:17:16 - INSTALL: always: Upgrading from v1.1.8 (DB 1.1.8) to v1.1.11
2019/04/05 09:17:16 - INSTALL: always: Upgrading from v1.1.7 (DB 1.1.7) to v1.1.8
2019/04/05 09:17:16 - INSTALL: always: Upgrading from v1.1.6 (DB 1.1.6) to v1.1.7
2019/04/05 09:17:16 - INSTALL: always: Upgrading from v1.1.4 (DB 1.1.4) to v1.1.6
2019/04/05 09:17:15 - INSTALL: always: Upgrading from v1.1.2 (DB 1.1.2) to v1.1.4
2019/04/05 09:17:14 - INSTALL: always: Upgrading from v1.0.5 (DB 1.0.5) to v1.1.2
2019/04/05 09:17:12 - INSTALL: always: Upgrading from v1.0.4 (DB 1.0.4) to v1.0.5
2019/04/05 09:17:12 - INSTALL: always: Upgrading from v1.0.0 (DB 1.0.0) to v1.0.4
2019/04/05 09:16:41 - INSTALL: always: Upgrading from v0.8.8h (DB 1.2.2 (DB: 0.8.8h)) to v1.0.0
2019/04/05 09:16:41 - INSTALL: always: NOTE: Using temporary file for db cache: /tmp/cdu2QnIA2
2019/04/05 09:16:41 - INSTALL: always: Switched from to /tmp/cdu2QnIA2
2019/04/05 09:16:41 - INSTALL: always: Converting Table #108 'weathermap_settings'
2019/04/05 09:16:40 - INSTALL: always: Converting Table #107 'weathermap_maps'
2019/04/05 09:16:40 - INSTALL: always: Converting Table #106 'weathermap_groups'
2019/04/05 09:16:40 - INSTALL: always: Converting Table #105 'weathermap_data'
2019/04/05 09:16:40 - INSTALL: always: Converting Table #104 'weathermap_auth'
2019/04/05 09:16:40 - INSTALL: always: Converting Table #103 'version'
2019/04/05 09:16:40 - INSTALL: always: Converting Table #102 'user_log'
2019/04/05 09:16:40 - INSTALL: always: Converting Table #101 'user_auth_realm'
2019/04/05 09:16:39 - INSTALL: always: Converting Table #100 'user_auth_perms'
2019/04/05 09:16:39 - INSTALL: always: Converting Table #99 'user_auth'
2019/04/05 09:16:39 - INSTALL: always: Converting Table #98 'thold_template'
2019/04/05 09:16:39 - INSTALL: always: Converting Table #97 'thold_data'
2019/04/05 09:16:39 - INSTALL: always: Converting Table #96 'snmp_query_graph_sv'
2019/04/05 09:16:38 - INSTALL: always: Converting Table #95 'snmp_query_graph_rrd_sv'
2019/04/05 09:16:38 - INSTALL: always: Converting Table #94 'snmp_query_graph_rrd'
2019/04/05 09:16:38 - INSTALL: always: Converting Table #93 'snmp_query_graph'
2019/04/05 09:16:38 - INSTALL: always: Converting Table #92 'snmp_query'
2019/04/05 09:16:37 - INSTALL: always: Converting Table #91 'settings_tree'
2019/04/05 09:16:37 - INSTALL: always: Converting Table #90 'settings_graphs'
2019/04/05 09:16:37 - INSTALL: always: Converting Table #89 'settings'
2019/04/05 09:16:37 - INSTALL: always: Converting Table #88 'rra_cf'
2019/04/05 09:16:37 - INSTALL: always: Converting Table #87 'rra'
2019/04/05 09:16:37 - INSTALL: always: Converting Table #86 'reportit_variables'
2019/04/05 09:16:36 - INSTALL: always: Converting Table #85 'reportit_templates'
2019/04/05 09:16:36 - INSTALL: always: Converting Table #84 'reportit_rvars'
2019/04/05 09:16:36 - INSTALL: always: Converting Table #83 'reportit_reports'
2019/04/05 09:16:36 - INSTALL: always: Converting Table #82 'reportit_recipients'
2019/04/05 09:16:36 - INSTALL: always: Converting Table #81 'reportit_presets'
2019/04/05 09:16:35 - INSTALL: always: Converting Table #80 'reportit_measurands'
2019/04/05 09:16:35 - INSTALL: always: Converting Table #79 'reportit_cache_variables'
2019/04/05 09:16:35 - INSTALL: always: Converting Table #78 'reportit_cache_reports'
2019/04/05 09:16:35 - INSTALL: always: Converting Table #77 'reportit_cache_measurands'
2019/04/05 09:16:35 - INSTALL: always: Converting Table #76 'poller_time'
2019/04/05 09:16:34 - INSTALL: always: Converting Table #75 'poller_reindex'
2019/04/05 09:16:34 - INSTALL: always: Converting Table #74 'poller_output_rt'
2019/04/05 09:16:34 - INSTALL: always: Converting Table #73 'poller_output_boost_processes'
2019/04/05 09:16:34 - INSTALL: always: Converting Table #72 'poller_output_boost'
2019/04/05 09:16:33 - INSTALL: always: Converting Table #71 'poller_output'
2019/04/05 09:16:33 - INSTALL: always: Converting Table #70 'poller_item'
2019/04/05 09:16:33 - INSTALL: always: Converting Table #69 'poller_command'
2019/04/05 09:16:33 - INSTALL: always: Converting Table #68 'poller'
2019/04/05 09:16:32 - INSTALL: always: Converting Table #67 'plugin_wmi_queries'
2019/04/05 09:16:32 - INSTALL: always: Converting Table #66 'plugin_wmi_accounts'
2019/04/05 09:16:32 - INSTALL: always: Converting Table #65 'plugin_update_info'
2019/04/05 09:16:32 - INSTALL: always: Converting Table #64 'plugin_thold_threshold_contact'
2019/04/05 09:16:32 - INSTALL: always: Converting Table #63 'plugin_thold_template_contact'
2019/04/05 09:16:32 - INSTALL: always: Converting Table #62 'plugin_thold_log'
2019/04/05 09:16:31 - INSTALL: always: Converting Table #61 'plugin_thold_host_failed'
2019/04/05 09:16:31 - INSTALL: always: Converting Table #60 'plugin_thold_contacts'
2019/04/05 09:16:31 - INSTALL: always: Converting Table #59 'plugin_routerconfigs_devicetypes'
2019/04/05 09:16:31 - INSTALL: always: Converting Table #58 'plugin_routerconfigs_devices'
2019/04/05 09:16:31 - INSTALL: always: Converting Table #57 'plugin_routerconfigs_backups'
2019/04/05 09:16:31 - INSTALL: always: Converting Table #56 'plugin_routerconfigs_accounts'
2019/04/05 09:16:30 - INSTALL: always: Converting Table #55 'plugin_realms'
2019/04/05 09:16:30 - INSTALL: always: Converting Table #54 'plugin_notification_lists'
2019/04/05 09:16:30 - INSTALL: always: Converting Table #53 'plugin_hooks'
2019/04/05 09:16:30 - INSTALL: always: Converting Table #52 'plugin_flowview_schedules'
2019/04/05 09:16:30 - INSTALL: always: Converting Table #51 'plugin_flowview_queries'
2019/04/05 09:16:29 - INSTALL: always: Converting Table #50 'plugin_flowview_dnscache'
2019/04/05 09:16:29 - INSTALL: always: Converting Table #49 'plugin_flowview_devices'
2019/04/05 09:16:29 - INSTALL: always: Converting Table #48 'plugin_fix64bit'
2019/04/05 09:16:29 - INSTALL: always: Converting Table #47 'plugin_discover_template'
2019/04/05 09:16:28 - INSTALL: always: Converting Table #46 'plugin_discover_hosts'
2019/04/05 09:16:28 - INSTALL: always: Converting Table #44 'plugin_config'
2019/04/05 09:16:28 - INSTALL: always: Converting Table #43 'plugin_aggregate_color_templates'
2019/04/05 09:16:28 - INSTALL: always: Converting Table #42 'plugin_aggregate_color_template_items'
2019/04/05 09:16:28 - INSTALL: always: Converting Table #41 'mac_track_temp_ports'
2019/04/05 09:16:27 - INSTALL: always: Converting Table #40 'mac_track_sites'
2019/04/05 09:16:27 - INSTALL: always: Converting Table #39 'mac_track_scanning_functions'
2019/04/05 09:16:27 - INSTALL: always: Converting Table #38 'mac_track_scan_dates'
2019/04/05 09:16:27 - INSTALL: always: Converting Table #37 'mac_track_processes'
2019/04/05 09:16:27 - INSTALL: always: Converting Table #36 'mac_track_ports'
2019/04/05 09:16:27 - INSTALL: always: Converting Table #35 'mac_track_oui_database'
2019/04/05 09:16:26 - INSTALL: always: Converting Table #34 'mac_track_macwatch'
2019/04/05 09:16:26 - INSTALL: always: Converting Table #33 'mac_track_macauth'
2019/04/05 09:16:26 - INSTALL: always: Converting Table #32 'mac_track_ips'
2019/04/05 09:16:26 - INSTALL: always: Converting Table #31 'mac_track_ip_ranges'
2019/04/05 09:16:26 - INSTALL: always: Converting Table #30 'mac_track_devices'
2019/04/05 09:16:26 - INSTALL: always: Converting Table #29 'mac_track_device_types'
Copyright (C) 2004-2019 The Cacti Group

**Comment by netniV** [comment]
The upgrade process shows no errors above but may have from earlier.  If you are still stuck with it trying to do the upgrade, turn on the install log:

```sql
REPLACE INTO settings VALUES ('log_install','5')
```

run the upgrade again and then email your install-complete.log to developers@cacti.net and I'll take a look.

**Comment by netniV** [comment]
No response and I couldn't find an email related to this.
