### ISSUE TITLE
[1.2.2] Cacti page not working

### ISSUE THREAD

**Issue by USER1696960** [Cacti/cacti#2624]
Hi everyone,

I have a strange problem that I can't find out how to resolve.
Last week we upgrade Cacti to use Syslog plugin. Everything look cool, but the page no.
I can log in but if I want to go to devices or any option, the page not move.

Already check httpd, mariadb, php, logs but nothing looks bad.

Any ideas ?

Best regards and have a amazing week !

PD: Sorry for my awful english :B

**Comment by USER1696960** [comment]
If I go to the highlight button of the image works but no from the menu.

![image](https://user-images.githubusercontent.com/13982683/55752037-72516880-5a1d-11e9-8431-ce0ad796ab1d.png)

**Comment by cigamit** [comment]
Please, for both of you, check your Chrome and Firefox debug consoles.  Look for JavaScript errors and report there here.

**Comment by cigamit** [comment]
No feedback.
