### ISSUE TITLE
Cacti 1.2.2 - CMDPHP ERROR

### ISSUE THREAD

**Issue by cwlam8888** [Cacti/cacti#2625]
**Describe the bug**

Cacti version: 1.2.2

Cacti log found a lot of alarm as like this:
2019/04/09 09:35:01 - CMDPHP SQL Backtrace: (/cmd.php[62]:require_once(), /include/cli_check.php[31]:include(), /include/global.php[402]:include_once(), /include/global_arrays.php[2646]:api_plugin_hook(), /lib/plugins.php[74]:api_plugin_run_plugin_hook(), /lib/plugins.php[177]:syslog_config_arrays(), /plugins/syslog/setup.php[1332]:db_fetch_cell(), /lib/database.php[360]:db_fetch_cell_prepared(), /lib/database.php[376]:db_execute_prepared())
--
2019/04/09 09:35:01 - CMDPHP ERROR: A DB Cell Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1

**Comment by cigamit** [comment]
This looks like a syslog bug.  Can you please open in that issue area?

**Comment by cigamit** [comment]
Closing here.
