### ISSUE TITLE
Spine Poller duplicate entry for key primary, error'1062'

### ISSUE THREAD

**Issue by chenbangkuo** [Cacti/cacti#2628]
Hi, Cacti team 
Recently i've encountered some DB poller time issue loged by Duplicate entry.
after a whole painfuly solution hunting but dosent seems to get me any where.
I'm not so sure but the issue seems to spread through thold function and getting 
some strange current interface traffice. 
Please could kindly point out what i've done wrong.
OS: Ubuntu16.04
Cacti version: 1.1.38
Spine version: 1.1.38
Mysql version: 5.7.22
![2019-04-14_07h20_13](https://user-images.githubusercontent.com/36146687/56086288-7bf82780-5e86-11e9-8f27-34895fe8a063.png)

**Comment by netniV** [comment]
This is due to the maximum on the poller_id column.  Basically, it's trying to auto increment but can't.  It was fixed in 1.2.2 #2317 under commit cd6b789bb05ae3e387da6ce0d991c8e694269d88
