### ISSUE TITLE
Authentication bug on Cacti upgrade

### ISSUE THREAD

**Issue by OUnagiles** [Cacti/cacti#2629]
**Summary**
On RHEL 7.6 we have encountered an authentication bug  upon Cacti package upgrade from version 1.1.38 -> 1.2.2
On navigating to the web installer and attempting to log in with an LDAP account, the authentication page crashes (HTML 500).

**To Reproduce**
1. Upgrade the Cacti package from EPEL from version 1.1.38 -> 1.2.2 using yum package manager.
2. Navigate to the Web Installer in a web browser in order to complete the upgrade
3. Attempt to authenticate with an LDAP account when prompted

**Expected behavior**
The LDAP account is authenticated and the user is redirected to the web installer

**Suspected Cause**
It appears that auth_login.php is invoked with working directory `<CACTI_PATH>/install/ `which causes path resolution in the statement `include_once('./lib/ldap.php');` to fail. 

https://github.com/Cacti/cacti/blob/6ea486a00a56c1e43fac07a3ccb7c56acca17b3c/auth_login.php#L122 

In particular, it looks like the path `'./lib/ldap.php'` is resolved to `'<CACTI_PATH>/install/lib/ldap.php'`, a nonexistent file path.  Temporarily changing the include statement to read `include_once(‘lib/ldap.php’);` allowed us to successfully login and complete the upgrade.

**Desktop:**
 - OS: RHEL 7.6
 - Browser: Firefox
 - Version: 66

**Additional context**
- For reference, <CACTI_PATH> is /usr/share/cacti/ on RHEL from the EPEL RPM package.
- Current EPEL package is at <https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/c/cacti-1.2.2-1.el7.noarch.rpm>
- Logging in with a local account proceeds without issue

**Comment by cigamit** [comment]
Should be resolved now.

**Comment by OUnagiles** [comment]
Okay, looks good. Thanks!
