### ISSUE TITLE
Error upgrading 0.8.8h to 1.0.0

### ISSUE THREAD

**Issue by SoNix21** [Cacti/cacti#263]
When i`m doing the Upgrade from 0.8,8h to 1.0.0, i can't complete the process...
The upgrade fail with this error :

Fatal error: Call to a member function row() on a non-object in C:\Cacti\Apache24\htdocs\Cacti\lib\snmpagent.php on line 507

**Comment by browniebraun** [comment]
Poller tables will be updated now within the SNMPcache. Please provide me your feedback.

**Comment by SoNix21** [comment]
Hummm.. Yep :+1:  Your patch seem to work, but now i get a new error :(

 Fatal error: Call to a member function row() on a non-object in C:\Cacti\Apache24\htdocs\Cacti\lib\snmpagent.php on line 536

**Comment by browniebraun** [comment]
Sorry, but that sounds to me like the SNMPCache has not been filled up for whatever reason.
Can you verify that SNMPagent tables are not empty?

**Comment by SoNix21** [comment]
OKay, there is a screenshot of the "Host" SQL table : 

![select](https://cloud.githubusercontent.com/assets/25518106/22598528/bc7ca994-ea01-11e6-9a59-644d01eaa94e.png)

And there is a Screenshot of the Host_SNMP_Cache : 
![select1](https://cloud.githubusercontent.com/assets/25518106/22598606/0700f768-ea02-11e6-82d4-1fb5020b251b.png)

**Comment by browniebraun** [comment]
Sy, I was looking for table " snmpagent_cache" and "snmpagent_mibs".

**Comment by SoNix21** [comment]
Humm... i really don't know how to help you...

I checked the @Update script@ : 
The Upgrade seem to rename a SQL table : 
```
if (db_table_exists('**plugin_snmpagent_cache**', false)) {
		db_install_rename_table('**plugin_snmpagent_cache**', '**snmpagent_cache**');
	}
```

And if the database is missing, the upgrade script try to create it : 

`db_install_execute("CREATE TABLE IF NOT EXISTS `snmpagent_cache` (
		`oid` varchar(255) NOT NULL,
		`name` varchar(255) NOT NULL,
		`mib` varchar(255) NOT NULL,
		`type` varchar(255) NOT NULL DEFAULT '',
		`otype` varchar(255) NOT NULL DEFAULT '',
		`kind` varchar(255) NOT NULL DEFAULT '',
		`max-access` varchar(255) NOT NULL DEFAULT 'not-accessible',
		`value` varchar(255) NOT NULL DEFAULT '',
		`description` varchar(5000) NOT NULL DEFAULT '',
		PRIMARY KEY (`oid`),
		KEY `name` (`name`),
		KEY `mib` (`mib`))
		ENGINE=$engine
		COMMENT='SNMP MIB CACHE';");`

But... there seem, to be a problem... With the create... So the table is missing... :(

![missing_sql](https://cloud.githubusercontent.com/assets/25518106/22601039/308f5ed6-ea0b-11e6-85b4-e4736d2cf6bb.png)

**Comment by ronytomen** [comment]
Can you search your Cacti log for any errors from the upgrade?

**Comment by SoNix21** [comment]
OKay... there many errors... :(
Maybe because since 0.8.8h MySQL to 1.0.0 i moved to MariaDB ? ( For the Requirement ? )

[cacti.txt](https://github.com/Cacti/cacti/files/751731/cacti.txt)

**Comment by cigamit** [comment]
Your database is either running in UTF8, or it's MySQL 5.0.2-.  If it's the former, take the latest development image, and re-upgrade.  If not, then make sure you upgrade MySQL 5.0 to a more recent version before upgrading.  If the issue was UTF8, then this issue is resolved.  If it's MySQL 5.0, we don't support that MySQL version any longer.
