### ISSUE TITLE
Cacti1.1.26 Chinese garbled

### ISSUE THREAD

**Issue by tyit** [Cacti/cacti#2633]
![WX20190418](https://user-images.githubusercontent.com/31933126/56337773-7fb6e180-61d9-11e9-935b-3d5ee84bfadf.png)

![WX20190418-125430](https://user-images.githubusercontent.com/31933126/56337774-834a6880-61d9-11e9-9aab-18f6a25f90c9.png)

Hi!
Chinese garbled, what should I change? Thank you

**Comment by purplegrape** [comment]
it seems due to miss some fonts
run the following command if you are running centos,hope it's useful for u

yum install dejavu-* cjkuni-* -y

**Comment by netniV** [comment]
Thanks @purplegrape, let us know if that is the issue @tyit

**Comment by tyit** [comment]
@purplegrape @netniV 
Thank you, I have a test.

**Comment by tyit** [comment]
@purplegrape 
@netniV 
@cigamit 

Thanks

yum install dejavu-* cjkuni-* -y 

![image](https://user-images.githubusercontent.com/31933126/57749952-c9c8af80-7712-11e9-883a-a8126c4c06ee.png)
