### ISSUE TITLE
Particle size is five minutes. How to Setting save one year?

### ISSUE THREAD

**Issue by tyit** [Cacti/cacti#2634]
![image](https://user-images.githubusercontent.com/31933126/56338142-73338880-61db-11e9-9a17-b026af53b2a3.png)
Hi!

Particle size is five minutes. How to Setting save one year?

Sorry, my English is not good.

**Comment by cigamit** [comment]
You just need to add particles "row" to each RRD.  It should be strait forward.  However, if you have an established site with lot's of RRDfiles, you need a utility, currently checked into the 1.3 branch to help you update all the RRDfiles.

Since this is a question, I'll close now.
