### ISSUE TITLE
Multiple Database Sync Issues in v1.2.x

### ISSUE THREAD

**Issue by mmccaugh1** [Cacti/cacti#2635]
**Describe the bug**
There are a number of DB Sync issues I have found in v1.2.x, all appear to potentially relate to functionality that has been distributed to the remote pollers, but associated database information is NOT being synced.

**To Reproduce**
1. Make a Change in Cacti (For this test change the cacti log file path)
2. Save
3. Do a Full Sync (Should not be necessary, but fastest way to see this isn't working)
4. Log into Remote Poller and check the cacti.settings table, and note that the cacti log path has NOT changed (And cacti log is still writing to old directory, 1.1.37 in this case)

**Expected behavior**
Any settings that the remote pollers will rely on their local MySQL database for should be replicated out from the master server when changed.

**Screenshots**

**Additional context**
Important note here is that even if you log in to the remote poller directly and browse to the setting in question (The cacti log path is a valid example again), this page pulls the setting from the master node so it appears correct (There is no way to change it directly on the poller without manually editing/inserting the row in MySQL)

So far I have observed this issue on :
cacti.settings
cacti.automation_networks
cacti.automation_snmp
cacti.automation_snmp_items

But I am confident there are more I have not found, and unfortunately I do not have the architectural knowledge of the cacti structure (Current, and roadmapped) to provide an accurate list of what 'should' replicate.

But I wanted to get this on the radar for 1.2.4 potentially as it has broken some functionality..

**Comment by netniV** [comment]
There are tweaks made to the poller sync logic to avoid synchronising paths in various versions of Cacti 1.2, because we are trying to handle different scenarios.  At one point, we were not synchronising the paths because pollers on different architectures place things in different places.  

I can't recall off the top of my head which situation we are currently in and whether we are or not synchronising paths at the moment without looking at the code.

**Comment by mmccaugh1** [comment]
Keep in mind the paths are just one example, there seem to be many issues.

Simple fix here would be to be able to force everything to still rely on the master node SQL Server (Which would I believe fix every issue in the interim), though the permanent fix would be the DBSync.

The main issue is simply that the pollers are performing functions today that pull from their local SQL database, but the rows are not being replicated from the master node so functions that rely on them either do not work at all, or work in unexpected ways (As in the Cacti Logging, it works, but it writes to the wrong place)

If it's possible to force the old behavior then that's a today albeit bandaid fix.

**Comment by netniV** [comment]
The idea was to have the core work both ways.  If online, they would use the latest in the main database with the local used as a backup if it was unavailable.  That way, local polling can still occur if say the link to the main site went down.  That would allow data to be collected and populated for devices behind say a dial up.

It may be useful to have an enhancement that states, "online only" as an option but we don't have that currently.

**Comment by mmccaugh1** [comment]
That sounds great, but the issue is of course the data is not all being pushed out to the remote pollers.. It seems like a full sync should replicate everything (Which it does not). 

The idea of forcing everything to use the master node isn't functionality I see being necessary long term, it is just a bandaid idea until the database sync is corrected.

Is there data on the main node we do NOT want to replicate (and overwrite) to a remote poller? If there isn't then I can potentially fix this sloppy until it's got a proper fix.. But my concern is errantly replicating something out that is unique to each instance thus breaking things spectacularly.

**Comment by cigamit** [comment]
Okay, I've solved this by forcing the connection back to the central database.  It'll be a little slower, but that should not be a big deal for automation.

**Comment by mmccaugh1** [comment]
I will apply and test, however I want to stress the issue does seem to extend beyond automation (Log files as the other example from the settings table). 

I cannot confirm other functionality impacted but I do think the entire sync process could use a once over to confirm what should sync does, and what cannot sync or does not sync pulls from the master node.

**Comment by mmccaugh1** [comment]
Confirming applied fix did correct automation scans.
