### ISSUE TITLE
Aggergate Graphs Total Line

### ISSUE THREAD

**Issue by chathurag** [Cacti/cacti#2636]
When created aggregated graphs with multiple graphs the total line is not on the edge of stacks.

Version 1.2.3
![cacti](https://user-images.githubusercontent.com/35136010/56479601-dcfdac00-64d3-11e9-9b09-94bbb5a7d9d5.PNG)

**Comment by netniV** [comment]
Sorry, I'm not quite sure what you are saying is the issue here.  Maybe @cigamit can interpret 👍

**Comment by cigamit** [comment]
You need to post your Aggregate "Details" tab in it's entirety.

**Comment by chathurag** [comment]
@netniV - The above image shows that black line (which shows total) is not on the edge of last stack (pink)

@cigamit - Please find as below.
![image](https://user-images.githubusercontent.com/35136010/56559296-cf712080-65be-11e9-812a-92c60dd74e1b.png)

**Comment by cigamit** [comment]
Where is that dark pink line coming from.  Can you post the Debug info from the Preview tab?

**Comment by chathurag** [comment]
/bin/rrdtool graph - \
--imgformat=PNG \
--start='-86400' \
--end='-300' \
--pango-markup  \
--title='XXXXX' \
--vertical-label='bits per second' \
--slope-mode \
--base=1000 \
--height=300 \
--width=900 \
--rigid \
--alt-autoscale-max \
--lower-limit='0' \
COMMENT:"From 09/05/2019 14\:30\:23 To 10/05/2019 14\:25\:23\c" \
COMMENT:"  \n" \
--border 1 --font TITLE:10: \
--font AXIS:8: \
--font LEGEND:8: \
--font UNIT:8: \
--font WATERMARK:8: \
--slope-mode \
--watermark 'XXX' \
DEF:a='/var/www/cacti-1.2.3/rra/location2-rtr-001_traffic_in_1341.rrd':'traffic_out':MAX \
DEF:b='/var/www/cacti-1.2.3/rra/location2-rtr-001_traffic_in_1341.rrd':'traffic_out':AVERAGE \
DEF:c='/var/www/cacti-1.2.3/rra/location1-rtr-002_traffic_in_1473.rrd':'traffic_out':MAX \
DEF:d='/var/www/cacti-1.2.3/rra/location1-rtr-002_traffic_in_1473.rrd':'traffic_out':AVERAGE \
DEF:e='/var/www/cacti-1.2.3/rra/location1-rtr-002_traffic_in_1474.rrd':'traffic_out':MAX \
DEF:f='/var/www/cacti-1.2.3/rra/location1-rtr-002_traffic_in_1474.rrd':'traffic_out':AVERAGE \
DEF:g='/var/www/cacti-1.2.3/rra/location1-rtr-002_traffic_in_1475.rrd':'traffic_out':MAX \
DEF:h='/var/www/cacti-1.2.3/rra/location1-rtr-002_traffic_in_1475.rrd':'traffic_out':AVERAGE \
DEF:i='/var/www/cacti-1.2.3/rra/location1-rtr-002_traffic_in_1476.rrd':'traffic_out':MAX \
DEF:j='/var/www/cacti-1.2.3/rra/location1-rtr-002_traffic_in_1476.rrd':'traffic_out':AVERAGE \
DEF:ba='/var/www/cacti-1.2.3/rra/location1-rtr-003_traffic_in_1517.rrd':'traffic_out':MAX \
DEF:bb='/var/www/cacti-1.2.3/rra/location1-rtr-003_traffic_in_1517.rrd':'traffic_out':AVERAGE \
DEF:bc='/var/www/cacti-1.2.3/rra/location1-rtr-003_traffic_in_1518.rrd':'traffic_out':MAX \
DEF:bd='/var/www/cacti-1.2.3/rra/location1-rtr-003_traffic_in_1518.rrd':'traffic_out':AVERAGE \
CDEF:cdefa='a,8,*' \
CDEF:cdeff='c,8,*' \
CDEF:cdefba='e,8,*' \
CDEF:cdefbf='g,8,*' \
CDEF:cdefca='i,8,*' \
CDEF:cdefzzcf='ba,8,*' \
CDEF:cdefda='bc,8,*' \
CDEF:cdefdg='TIME,1557478523,GT,b,b,UN,0,b,IF,IF,TIME,1557478523,GT,d,d,UN,0,d,IF,IF,TIME,1557478523,GT,f,f,UN,0,f,IF,IF,TIME,1557478523,GT,h,h,UN,0,h,IF,IF,TIME,1557478523,GT,j,j,UN,0,j,IF,IF,TIME,1557478523,GT,bb,bb,UN,0,bb,IF,IF,TIME,1557478523,GT,bd,bd,UN,0,bd,IF,IF,+,+,+,+,+,+,8,*' \
CDEF:cdefea='TIME,1557478523,GT,b,b,UN,0,b,IF,IF,TIME,1557478523,GT,d,d,UN,0,d,IF,IF,TIME,1557478523,GT,f,f,UN,0,f,IF,IF,TIME,1557478523,GT,h,h,UN,0,h,IF,IF,TIME,1557478523,GT,j,j,UN,0,j,IF,IF,TIME,1557478523,GT,bb,bb,UN,0,bb,IF,IF,TIME,1557478523,GT,bd,bd,UN,0,bd,IF,IF,+,+,+,+,+,+' \
AREA:cdefa#59E8177F:'location2-rtr-001 GigabitEthernet1/0/0 \:  Outbound'  \
GPRINT:cdefa:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefa:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdefa:MAX:'Maximum\:%8.2lf %s'  \
COMMENT:'Total Out\:  170.52 MB\n'  \
AREA:cdeff#D462FF7F:'location1-rtr-002 Pos2/0/0 \:  Outbound            ':STACK \
GPRINT:cdeff:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdeff:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdeff:MAX:'Maximum\:%8.2lf %s'  \
COMMENT:'Total Out\:    3.14 GB\n'  \
AREA:cdefba#0000FF7F:'location1-rtr-002 GigabitEthernet6/0/1 \:  Outbound':STACK \
GPRINT:cdefba:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefba:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdefba:MAX:'Maximum\:%8.2lf %s'  \
COMMENT:'Total Out\:    2.10 TB\n'  \
AREA:cdefbf#FFFF007F:'location1-rtr-002 GigabitEthernet7/0/2 \:  Outbound':STACK \
GPRINT:cdefbf:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefbf:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdefbf:MAX:'Maximum\:%8.2lf %s'  \
COMMENT:'Total Out\:    6.03 TB\n'  \
AREA:cdefca#FF00007F:'location1-rtr-002 Pos2/0/1 \:  Outbound            ':STACK \
GPRINT:cdefca:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefca:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdefca:MAX:'Maximum\:%8.2lf %s'  \
COMMENT:'Total Out\:    4.55 MB\n'  \
AREA:cdefzzcf#00FFFF7F:'location1-rtr-003 Pos6/0/0 \:  Outbound            ':STACK \
GPRINT:cdefzzcf:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefzzcf:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdefzzcf:MAX:'Maximum\:%8.2lf %s'  \
COMMENT:'Total Out\:  228.72 MB\n'  \
AREA:cdefda#C122677F:'location1-rtr-003 GigabitEthernet5/0/2 \:  Outbound':STACK \
GPRINT:cdefda:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefda:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdefda:MAX:'Maximum\:%8.2lf %s'  \
COMMENT:'Total Out\:   33.25 MB\n'  \
 \
LINE1:cdefdg#0000007F:'Total Upload \:                               '  \
GPRINT:cdefdg:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefdg:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdefdg:MAX:'Maximum\:%8.2lf %s'  \
COMMENT:'Total Out\:    8.14 TB\n'

**Comment by chathurag** [comment]
@cigamit - Any update?

**Comment by cigamit** [comment]
Well, one thing is interesting.  Look at your Graph Template that the Aggregate that it's based off of.  Note this difference?

![AggregateErrorImage](https://user-images.githubusercontent.com/957322/57974451-df8ddd00-797d-11e9-890b-d31368c9c62d.png)

**Comment by cigamit** [comment]
It renders correctly on my system.

**Comment by cigamit** [comment]
Hmm, I just saw something that's interesting.  Give me some more time.  This is the bandwidth graph template.  That means something.

**Comment by cigamit** [comment]
Pretty sure that this is fixed now in 1.2.4.  You might have to resave your aggregate template by switching a value, saving, and then switch it back, or switch something in the standalone aggregate and then back to it's original setting though.
