### ISSUE TITLE
Graphs issues with 1.2 beta 4

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#2637]
Hello Everyone 

Fresh install of 1.2 Beta4

autom8 generates the following errors

2019/04/22  12:29:21 - DBCALL ERROR: SQL Save Failed for Table  'graph_templates_graph'.  SQL:'INSERT INTO graph_templates_graph (`id`,  `local_graph_template_graph_id`, `local_graph_id`, `graph_template_id`,  `title`, `vertical_label`, `image_format_id`, `height`, `width`,  `base_value`, `slope_mode`, `auto_scale`, `auto_scale_opts`,  `auto_scale_log`, `scale_log_units`, `auto_scale_rigid`, `upper_limit`,  `lower_limit`, `unit_value`, `unit_exponent_value`, `unit_length`,  `no_gridfit`, `alt_y_grid`, `right_axis`, `right_axis_label`,  `right_axis_format`, `right_axis_formatter`, `left_axis_formatter`,  `auto_padding`, `dynamic_labels`, `force_rules_legend`, `tab_width`,  `legend_position`, `legend_direction`) VALUES (0, 0, 143, 0, NULL, NULL,  0, 0, 0, 0, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL,  NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL,  NULL, NULL) ON DUPLICATE KEY UPDATE  `local_graph_template_graph_id`=VALUES(`local_graph_template_graph_id`),  `local_graph_id`=VALUES(`local_graph_id`),  `graph_template_id`=VALUES(`graph_template_id`),  `title`=VALUES(`title`), `vertical_label`=VALUES(`vertical_label`),  `image_format_id`=VALUES(`image_format_id`), `height`=VALUES(`height`),  `width`=VALUES(`width`), `base_value`=VALUES(`base_value`),  `slope_mode`=VALUES(`slope_mode`), `auto_scale`=VALUES(`auto_scale`),  `auto_scale_opts`=VALUES(`auto_scale_opts`),  `auto_scale_log`=VALUES(`auto_scale_log`),  `scale_log_units`=VALUES(`scale_log_units`),  `auto_scale_rigid`=VALUES(`auto_scale_rigid`),  `upper_limit`=VALUES(`upper_limit`),  `lower_limit`=VALUES(`lower_limit`), `unit_value`=VALUES(`unit_value`),  `unit_exponent_value`=VALUES(`unit_exponent_value`),  `unit_length`=VALUES(`unit_length`), `no_gridfit`=VALUES(`no_gridfit`),  `alt_y_grid`=VALUES(`alt_y_grid`), `right_axis`=VALUES(`right_axis`),  `right_axis_label`=VALUES(`right_axis_label`),  `right_axis_format`=VALUES(`right_axis_format`),  `right_axis_formatter`=VALUES(`right_axis_formatter`),  `left_axis_formatter`=VALUES(`left_axis_formatter`),  `auto_padding`=VALUES(`auto_padding`),  `dynamic_labels`=VALUES(`dynamic_labels`),  `force_rules_legend`=VALUES(`force_rules_legend`),  `tab_width`=VALUES(`tab_width`),  `legend_position`=VALUES(`legend_position`),  `legend_direction`=VALUES(`legend_direction`)'
--
2019/04/22 12:29:21 - CMDPHP SQL Backtrace:   (/poller_automation.php[345]:discoverDevices(),  /poller_automation.php[668]:automation_update_device(),  /lib/api_automation.php[3768]:automation_execute_data_query(),  /lib/api_automation.php[2144]:create_dq_graphs(),  /lib/api_automation.php[2441]:create_complete_graph_from_template(),  /lib/template.php[1041]:change_graph_template(),  /lib/template.php[713]:sql_save(),  /lib/database.php[1245]:_db_replace(),  /lib/database.php[1175]:db_execute(),  /lib/database.php[188]:db_execute_prepared())
2019/04/22 12:29:21 - CMDPHP ERROR: A DB Exec Failed!, Error: Column 'title' cannot be null
2019/04/22 12:29:21 - CMDPHP PHP ERROR NOTICE Backtrace:   (/poller_automation.php[345]:discoverDevices(),  /poller_automation.php[668]:automation_update_device(),  /lib/api_automation.php[3768]:automation_execute_data_query(),  /lib/api_automation.php[2144]:create_dq_graphs(),  /lib/api_automation.php[2441]:create_complete_graph_from_template(),  /lib/template.php[1041]:change_graph_template(),  /lib/template.php[708]:CactiErrorHandler())

Device is added to graph properly  
template being used is Cisco Router
Device is added to tree properly 
When you click on the device graph lists only shows 5MIN CPU however the graph is not added to the device 

See below

![device](https://user-images.githubusercontent.com/13388748/56512522-9a50c980-64fd-11e9-96c7-4ae7ca00572e.JPG)

![device2](https://user-images.githubusercontent.com/13388748/56512525-9d4bba00-64fd-11e9-9ff7-34ab3032df04.JPG)

I have another cacti instance V1.2.1 installed on the same machine running perfectly just the v1.2 beta4 showing the following issues Graph rules are the same 

If I manually add the graphs to the device they add without error

**Comment by bmfmancini** [comment]
Found this error AUTOM8 ERROR: Device[192.168.1.40] Graph Not Added due to missing data sources.  when adding the graph manually the graph does not show I checked data queries and input methods from my working cacti and the beta and they match

**Comment by bmfmancini** [comment]
Enviroment details 

Cacti Version | 1.2.0
-- | --
Cacti OS | unix
RSA Fingerprint | a6:e5:14:6d:37:b7:e3:36:dc:c4:17:c6:7e:72:4d:15
NET-SNMP Version | NET-SNMP version: 5.7.3
RRDtool Version Configured | 1.4.0+
RRDtool Version Found | 1.5.5
Devices | 6
Graphs | 77
Data Sources | Script/Command: 5SNMP Get: 5SNMP Query: 6Total: 16


PHP Version | 7.2.16-1+ubuntu16.04.1+deb.sury.org+1
-- | --
PHP OS | Linux
PHP uname | Linux dsc-cacti-lab 3.13.0-165-generic #215-Ubuntu SMP Wed Jan 16 11:46:48 UTC 2019 i686
PHP SNMP | Installed
max_execution_time | 30
memory_limit | 128M

MariaDb 10

**Comment by bmfmancini** [comment]
Here is the mysql output for the template

MariaDB [cacti12]> SELECT local_graph_template_graph_id FROM graph_templates_graph;
+-------------------------------+
| local_graph_template_graph_id |
+-------------------------------+
|                             0 |
|                             0 |
|                             0 |
|                             0 |
|                             0 |
|                             0 |
|                             0 |
|                             0 |
|                             0 |
|                             0 |
|                             0 |
|                             0 |
|                             0 |
|                             0 |
|                             0 |
|                             0 |
|                             0 |
|                             0 |
|                             0 |
|                             0 |
|                             0 |
|                             0 |
|                             0 |
|                             0 |
|                             0 |
|                             0 |
|                             0 |
|                             0 |
|                             0 |
|                             0 |
|                             0 |
|                             0 |
|                             0 |
|                            14 |
|                            15 |
|                            16 |
|                            17 |
|                             1 |
|                             1 |
|                             1 |
|                             1 |
|                             2 |
|                             2 |
|                             1 |
|                             2 |
|                             2 |
|                             2 |
|                             2 |
+-------------------------------+
48 rows in set (0.00 sec)



MariaDB [cacti12]> SELECT local_graph_template_graph_id FROM graph_templates_graph WHERE local_graph_id = 14;
Empty set (0.00 sec)

MariaDB [cacti12]> SELECT local_graph_template_graph_id FROM graph_templates_graph WHERE local_graph_id = 15;
Empty set (0.01 sec)

MariaDB [cacti12]> SELECT local_graph_template_graph_id FROM graph_templates_graph WHERE local_graph_id = 1;
+-------------------------------+
| local_graph_template_graph_id |
+-------------------------------+
|                            14 |
+-------------------------------+
1 row in set (0.00 sec)

MariaDB [cacti12]> SELECT local_graph_template_graph_id FROM graph_templates_graph WHERE local_graph_id = 2;
+-------------------------------+
| local_graph_template_graph_id |
+-------------------------------+
|                            15 |
+-------------------------------+

**Comment by cigamit** [comment]
1.2.0 Beta4 is pretty old.  I would stat with 1.2.3 or develop.

**Comment by netniV** [comment]
Agreed.  Not sure why or how you picked up the beta version, you should be on a final release (1.2.3 is latest, 1.2.4 this weekend).

**Comment by bmfmancini** [comment]
Sorry Guys this is my bad
