### ISSUE TITLE
Incorrect display of archived graphs. Bursts on the charts in cacti 1.2.1

### ISSUE THREAD

**Issue by maxstech** [Cacti/cacti#2639]
Hello,
cacti 1.2.1
Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-43-generic x86_64)
PHP 7.0.32-0ubuntu0.16.04.1

On all archived graphs, I see an incomprehensible duplicate traffic band. otherwise it looks like splashes.
On the daily traffic - everything is always good. But it is worth looking at the daily traffic of a month ago - I see these incomprehensible traffic lanes.
At the same time in the legend of this traffic is not.
It is confusing.
An old 0.8.8b displays graphics correctly.
What could be the solution?
See screenshots.
Thank.
![day](https://user-images.githubusercontent.com/47040342/56581883-a3fe2e00-65de-11e9-85aa-598bf8eda177.jpg)
![last month 2](https://user-images.githubusercontent.com/47040342/56581892-a6f91e80-65de-11e9-981d-2a9acfeb9f9e.jpg)
![last month](https://user-images.githubusercontent.com/47040342/56581899-a8c2e200-65de-11e9-81f3-1da108cb8f32.jpg)

![maximum 4 months](https://user-images.githubusercontent.com/47040342/56581911-aceeff80-65de-11e9-87cd-d670c0a9270a.jpg)
![vsplesk 2](https://user-images.githubusercontent.com/47040342/56581913-af515980-65de-11e9-800a-c56c7d73f4be.jpg)
![vsplesk 22 04 2019](https://user-images.githubusercontent.com/47040342/56581915-b0828680-65de-11e9-8f5b-f2bfd662006b.jpg)

**Comment by cigamit** [comment]
There is nothing wrong here.  Cacti, and in fact really RRDtool, aggregates data over time, which reduces the precision of the data.  So, before you go and create a million graphs, you should come up to speed on that fact and then make adjustments before creating your first graph.  Goto www://rrdtool.org for more information on the organization/structure of an RRDfile.

With regard to legends, there are a few new Legend types that will present the max of the max.  The standard legends report the max of the average consolidation function.  If you want to use the GPRINT of the MAX, use the GPRINT:MAX and not GPRINT.  You can view this on the Graph Template Item page.

**Comment by maxstech** [comment]
Thank you for your comments. 
But for me the situation is critical.
The difference between the total cacti and counters cisco
Here is an example of one client: 
![raznica2](https://user-images.githubusercontent.com/47040342/56800172-165f5000-6823-11e9-9868-8e15c15fd0f8.jpg)

incoming traffic: 4 (cacti) - 3.68 (cisco) = 0.32 GB 
for outgoing traffic 172.87 (cacti) -161(cisco) - 11.87 GB. 
It's only for 4 days of work. Is this difference caused by these spikes in the charts ?
It turns out that I am not able to see the actual data from the archive charts. 
You're talking about adjustments, could you stop here for details. What can I do to avoid these spikes.
Why doesn't this happen in cacti Version 0.8.7 g ? 
Maybe I should change the rrdtool version . Now I have - RRDtool 1.7.0
