### ISSUE TITLE
Possible Template Bug ? 

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#2640]
Not sure if this is the proper place to post this I have also made a forum post 

I have the advanced ping template in use and when I attempt to add that to the Cisco router template the graph will not auto-generate  the debug logs doesn't even show an attempt to create the graph 

I know this is a user template but I don't think this is the advanced ping graph template because 
 if you manually create a device and add the graph everything is good 
I have to re-confirm this deleted a device and added it back with the template same deal 

![cisco-template](https://user-images.githubusercontent.com/13388748/56604306-a86f1a80-65cf-11e9-8433-a5b46233d0a7.JPG)

Cacti version 1.2.1

**Comment by netniV** [comment]
Check that the rules you have list the objects you expect to be matched.

**Comment by bmfmancini** [comment]
Sorry I am not sure I follow

**Comment by bmfmancini** [comment]
The issue I am having is that the advanced ping graph doesn't show up when I attach the Cisco template even though the graph is in the list 

If I add the graph manually then the graph shows up

**Comment by netniV** [comment]
Oh, that may be a proper bug.  I think one of our other guys is looking into it.

**Comment by bmfmancini** [comment]
Ok Cool thanks !

**Comment by cigamit** [comment]
Okay, I verified last night that this is a problem.  I'll try to address before the 1.2.4 release.  Time permitting.

**Comment by bmfmancini** [comment]
Thanks!

**Comment by bmfmancini** [comment]
Looks like this has been fixed on 1.2.4 based on my testing

**Comment by cigamit** [comment]
Thanks.  Closing.
