### ISSUE TITLE
Aggregate Graph is being shown more than once, leading to layout/display issues

### ISSUE THREAD

**Issue by DavidLiedke** [Cacti/cacti#2644]
**Describe the bug**
Unable to see Aggregate Graph in Device View

**To Reproduce**
1. Go to Graphs
2. Click on selected device
3. Scroll down to the aggregate graph

**Expected behavior**
If you click on "Graph Details" or "Time Graph View" you can see the graph.

**Screenshots**
1.
![firefox_2019-04-25_07-42-03](https://user-images.githubusercontent.com/25581728/56712169-d10d2680-672d-11e9-8567-a3fb09b41f99.png)
2.
![firefox_2019-04-25_07-42-16](https://user-images.githubusercontent.com/25581728/56712176-d4a0ad80-672d-11e9-9ca0-bffe0e8ff941.png)

**Comment by cigamit** [comment]
@DavidLiedke, is this a Windows box?  If not, provide the debug output (rrdtool graph ...).  If it is, Windows has problems with long strings, or used to years ago.  Not sure if it still persists.

**Comment by DavidLiedke** [comment]
No it is a linux system (openSUSE 15.0). 

I need to correct my error message. The graph is displayed after all. But cacti wants to display it next to the graph again.  This only happens in the Device View.

### Overview:
![firefox_2019-04-26_07-38-46](https://user-images.githubusercontent.com/25581728/56785735-c4083a00-67f6-11e9-90f6-1f5ad5a95598.png)

### Graph 1:
![2019-04-26_07-39-24](https://user-images.githubusercontent.com/25581728/56785768-e1d59f00-67f6-11e9-86d6-6fe3c1e98b7d.png)


![firefox_2019-04-26_07-47-30](https://user-images.githubusercontent.com/25581728/56785993-9ec7fb80-67f7-11e9-903a-2970ee97c5d9.png)
graph.php?action=zoom&local_graph_id=840&rra_id=0&graph_start=1556171100&graph_end=1556257500

![firefox_2019-04-26_07-47-37](https://user-images.githubusercontent.com/25581728/56786015-af787180-67f7-11e9-8bab-921dda5f9692.png)
graph.php?local_graph_id=840

![firefox_2019-04-26_07-47-43](https://user-images.githubusercontent.com/25581728/56786021-b99a7000-67f7-11e9-8e1c-f4e056eb48fc.png)
graph_view.php?page=1&graph_template_id=-1&host_id=-1&filter=&style=selective&action=preview&graph_add=14%2C203%2C815%2C816%2C

### Graph 2:
![2019-04-26_07-39-39](https://user-images.githubusercontent.com/25581728/56785775-e69a5300-67f6-11e9-93e9-5c0f9ae84110.png)

![firefox_2019-04-26_07-47-30](https://user-images.githubusercontent.com/25581728/56785993-9ec7fb80-67f7-11e9-903a-2970ee97c5d9.png)
graph.php?action=zoom&local_graph_id=840&rra_id=0&graph_start=1556171100&graph_end=1556257500

![firefox_2019-04-26_07-47-37](https://user-images.githubusercontent.com/25581728/56786015-af787180-67f7-11e9-8bab-921dda5f9692.png)
graph.php?local_graph_id=840

![firefox_2019-04-26_07-47-43](https://user-images.githubusercontent.com/25581728/56786021-b99a7000-67f7-11e9-8e1c-f4e056eb48fc.png)
graph_view.php?page=1&graph_template_id=-1&host_id=-1&filter=&style=selective&action=preview&graph_add=14%2C203%2C815%2C816%2C

**Comment by kurowskydb** [comment]
What browser are you using?  Also try private / incognito tab to see if extensions are affecting.  Had similar issue of a particular type of graph not showing in chrome.  Disabled some extensions, restarted and the graph appeared...  :/

**Comment by cigamit** [comment]
Need to see the browser console, and the debug output.

**Comment by DavidLiedke** [comment]
Issue exist in all browsers (Microsoft  Edge, Google Chrome and Firefox). 
Microsoft Edge has no extensions. In Firefox & Google Chrome the extensions are disabled for this URL. 

![chrome_2019-04-29_07-51-46](https://user-images.githubusercontent.com/25581728/56878342-dfbc4c00-6a53-11e9-8887-bfa22113c8e0.png)

![chrome_2019-04-29_07-53-00](https://user-images.githubusercontent.com/25581728/56878353-f662a300-6a53-11e9-999d-1b4be7260879.png)

In the debug log i cant find anything. Also there is no entry in the apache error log.

**Comment by netniV** [comment]
So the setTimeout warning is that it is above the 50ms which is chromes default warning limit for execution time of animation based events.  See https://stackoverflow.com/questions/41218507/violation-long-running-javascript-task-took-xx-ms and https://stackoverflow.com/questions/42218699/javascript-chrome-violation-violation-handler-took-83ms-of-runtime/44824402#44824402

So, it's unlikely that they are what is causing your issue.  Since everything appears to be OK with the status result etc, I can only assume that the data coming back isn't a valid image (or has a PHP notification/warning smack in the middle of it corrupting the data).  

When you browse those URLs directly, what do you get?  Can you use wget to download the data and post it as a data (rather than image file)?

**Comment by DavidLiedke** [comment]
If i browse this URLs ( graph_json.php?rra_id=0&local_graph_id=840&graph_start=1556440072&graph_end=1556526472&graph_height=120&graph_width=500 ) directly i get the JSON RAW Data.

![56785735-c4083a00-67f6-11e9-90f6-1f5ad5a95598](https://user-images.githubusercontent.com/25581728/56884685-d4c0e600-6a6a-11e9-8219-c0a507e9a166.png)

The aggregate graph works without any problems. But Cacti wants to show this graph two times. The first time (left) is shown. The second time it is not displayed. I can click the buttons (Graph Details, CSV Export, Time Graph View, Display Graphs from this Aggregate) of both graphs without any problems. 

![2019-04-29_10-44-24](https://user-images.githubusercontent.com/25581728/56885120-f5d60680-6a6b-11e9-9aa9-a7bd77912341.gif)

**Comment by netniV** [comment]
Oh, so my bad.   This is a case of trying to display it more than once...  But, if I now understand the issue right, that will likely cause issues because the div's ID that is used to inject the image already exists so it won't be updating both I imagine.

**Comment by netniV** [comment]
Looking back up, that is the real issue as these are both for graph id 840.

**Comment by DavidLiedke** [comment]
I had only one aggregate graph in my system. And this problem only happends in the "device view".

**Comment by cigamit** [comment]
I think @netniV got it right.  Likely an ID issue.  We will move this fix to 1.2.5.  Patch real soon though.

**Comment by pautiina** [comment]
I also have this bug

**Comment by cigamit** [comment]
This is resolved now.  Moved to 1.2.4 milestone due to the delays.

**Comment by onnieBLT** [comment]
When will the new version be released?

**Comment by DavidLiedke** [comment]
Thx. Problem is fixed.

**Comment by netniV** [comment]
We are just trying to test/tweak the installer and once we are confident in that, it will be released.  I was going to be this weekend, but I think it'll be Saturday now just to give us a bit more time.
