### ISSUE TITLE
The cacti setting 'base_url' may be incorrect for some systems. Correct it when applicable

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#2645]
The default value of "settings->'base_url'" ('http://hostname/') is not valid for report/thold/syslog as list below:
```php
lib/reports.php:                $out = "<a href='" . html_escape(read_config_option('base_url') . '/graph.php?action=view&local_graph_id='.$item['local_graph_id']."&rra_id=0") . "'>" . $out . '</a>';
plugins/thold/thold_functions.php:      $httpurl               = read_config_option('base_url');
plugins/thold/thold_functions.php:                              'file'           => "$httpurl/graph_image.php?local_graph_id=" . $thold_data['local_graph_id'] . '&rra_id=0&view_type=tree',
plugins/thold/thold_functions.php:      $url = $httpurl . '/graph.php?local_graph_id=' . $thold_data['local_graph_id'] . '&rra_id=all';
plugins/thold/thold_functions.php:      $text = str_replace('<URL>', "<a href='" . html_escape("$httpurl/graph.php?local_graph_id=$local_graph_id") . "'>" . __('Link to Graph in Cacti', 'thold') . "</a>", $text);
plugins/syslog/syslog_process.php:                                                              $smsalert = __('Sev:', 'syslog') . $severities[$alert['severity']] . __(', Host:', 'syslog') . $a['host'] . __(', URL:', 'syslog') . read_config_option('base_url') . '/plugins/syslog/syslog.php?tab=current&id=' . $sequence;
plugins/syslog/syslog_process.php:                                              $smsalert = __('Sev:', 'syslog') . $severities[$alert['severity']] . __(', Count:', 'syslog') . sizeof($at) . __(', URL:', 'syslog') . read_config_option('base_url') . '/plugins/syslog/syslog.php?tab=current&id=' . $sequence;
```
It should be "http://hostname/cacti"

**Comment by cigamit** [comment]
Good point.

**Comment by cigamit** [comment]
I'm not sure this is a bug.  The base url should be something like: http[s]://hostname/cacti already.  I'm going to implement a workaround just in case.

**Comment by cigamit** [comment]
This should be better now.

**Comment by ddb4github** [comment]
Currently,  Cacti define two default settings indicate conflict experience:

  * include/global.php:
         global -> $url_path,  setting -> $config['url_path'] ,  Macro->URL_PATH
          Value is '/cacti/
          **Assumption is 'cacti is running under a webapp '/cacti/', not directly under web server root'**
  * include/global_settings.php: 
         read_config_option('base_url'):   
         Value is 'http://' . gethostname()
         **Assumption is  'cacti page can be directly access under server name'**



BTW,  Issue can be workaround by simply modify and save base_url with '/cacti/' under Console-->Settings

**Comment by netniV** [comment]
The latter should also make use of the url_path and in not doing so would be the bug.

**Comment by netniV** [comment]
This has now been corrected along with another bug that I spotted where `$prefix` was being used whilst not being primed.  I also updated the description of base_url to be more clear that it should always include the url_path
