### ISSUE TITLE
graph 5/minute change unsuccessful 

### ISSUE THREAD

**Issue by whsir** [Cacti/cacti#2648]
HI，my version 1.2.2。

Graphics refresh in 5/min。
![1](https://user-images.githubusercontent.com/46343402/56789488-90e49b80-6834-11e9-862a-ce2944ab1ec0.png)

I want to change the graphics refresh time。1/min

![image](https://user-images.githubusercontent.com/46343402/56789352-4105d480-6834-11e9-92fd-3aa34bb648ac.png)

![2](https://user-images.githubusercontent.com/46343402/56789607-de610880-6834-11e9-971e-626593d237de.png)

unsuccessful

**Comment by whsir** [comment]
I've rebuilt the poller cache，
How can I change it。

**Comment by netniV** [comment]
The issue here is more than likely that your RRD files are still having the 5 minute step value.  Check the data source and the data source info/debug options to see.  You can also use the Troubleshooting -> Data Sources tool to fully analyse any source you want.

**Comment by whsir** [comment]
Thank you for your ideas。
Check the data source and the data source info/debug options to see.
`/usr/local/bin/rrdtool create \
/data/www/cacti/rra/demo_load_1min_33.rrd \
--start -900 --step 60  \
DS:load_1min:GAUGE:600:0:500 \
DS:load_5min:GAUGE:600:0:500 \
DS:load_15min:GAUGE:600:0:500 \
RRA:AVERAGE:0.5:1:2900 \
RRA:AVERAGE:0.5:15:1400 \
RRA:AVERAGE:0.5:60:1465 \
RRA:AVERAGE:0.5:240:4380 \
RRA:MIN:0.5:1:2900 \
RRA:MIN:0.5:15:1400 \
RRA:MIN:0.5:60:1465 \
RRA:MIN:0.5:240:4380 \
RRA:MAX:0.5:1:2900 \
RRA:MAX:0.5:15:1400 \
RRA:MAX:0.5:60:1465 \
RRA:MAX:0.5:240:4380 \
RRA:LAST:0.5:1:2900 \
RRA:LAST:0.5:15:1400 \
RRA:LAST:0.5:60:1465 \
RRA:LAST:0.5:240:4380 \`

**Comment by whsir** [comment]
![image](https://user-images.githubusercontent.com/46343402/56857726-a5937180-69a3-11e9-8f80-a92af8ab6766.png)

RRDfile does not match Data Profile

**Comment by whsir** [comment]
![image](https://user-images.githubusercontent.com/46343402/56857752-df647800-69a3-11e9-9891-6668853dec4d.png)
The picture above
I changed the results of the 'Run Check' at the data source 1 minute later

**Comment by whsir** [comment]
change minute
The data source
RRDfile does not match Data Profile

**Comment by whsir** [comment]
Is it because of a bug？

**Comment by whsir** [comment]
Does the existing data source no longer change?
create new  graph，succeed
![image](https://user-images.githubusercontent.com/46343402/56859864-3c235b00-69c3-11e9-8868-2738b4ae9e21.png)

**Comment by cigamit** [comment]
Got Settings -> Poll, and ensure that your Cron Interval and you Poller Interval are correct, then you should rebuild the Poller Cache.  You RRDfile looks right, you just are not sampling often enough.  Which leads on to review either the Poller Interval or the possibility that you have not Rebuilt the Poller Cache.

**Comment by cigamit** [comment]
There is an updated utility in Cacti 1.2.5 that will allow you to change the Step of your RRDfile.  It's a little complicated, the the process is:

1) move the existing file to a new file name, say 123.rrd
2) allow Cacti to recreate the RRDfile using the correct step
3) from the cli directory run 'php -q splice_rrd.php --oldrrd=123.rrd --newrrd=thenewrrd.php --finrrd=thenewrrd.php
4) make sure the permissions are correct, and repeat for all the files that you wish to change
5) dont' forget to remove the 123.rrd once you are done with it
