### ISSUE TITLE
Automation not creating graphs when there are custom items

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#2649]
Hello 

Just did an update on my lab instance to 1.2.4 I am seeing that  in autom8 when you attempt to discover a network it is not working 

No errors seen however the discovery does not run and even when run in debug mode is enabled there are no logs 

If I disable/Enable the network the status responds however it never  shows a running state

**Comment by bmfmancini** [comment]
Performed a fresh install same issue

**Comment by cigamit** [comment]
Resolved now.

**Comment by bmfmancini** [comment]
Thanks a bunch !
