### ISSUE TITLE
[1.2.3] MIB Resolution for Data Queries Missing

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#2658]
I have reported on something similar before, but the closest report I can find about the issue is #408. I recently upgraded from ~1.2.1 to 1.2.3

Here is what two data queries look like before refreshing data sources:
![image](https://user-images.githubusercontent.com/12864741/56923115-ffb93300-6a86-11e9-9fa7-ff4f9d7d4681.png)

And afterwards:
![image](https://user-images.githubusercontent.com/12864741/56923177-20818880-6a87-11e9-939f-284f9b725fcf.png)

The integer value '0' is no longer being resolved to 'normal' likewise the value '7' is not being resolved to 'notFound'.

**Comment by netniV** [comment]
Can you export the template that this data query comes with?  Are you sure that it isn't the device in question which has changed the way it reports it?

**Comment by eschoeller** [comment]
Let me know what I did wrong in this template so I can fix it!!

**Comment by eschoeller** [comment]
[servertech.zip](https://github.com/Cacti/cacti/files/3133763/servertech.zip)

**Comment by cigamit** [comment]
The reason is that it's using the php-snmp module.  There was a new config.php.dist setting in 1.2.4 (current develop) to not use the php-snmp module when performing actions such as walk.  Enabled that and then re-index.  We have to fix the php-snmp module, and to date, we just have not had time to do that for the PHP guys.

**Comment by eschoeller** [comment]
I don't have the php-snmp module available on this system. The installer always complains about it, and I haven't had a chance to get our sysadmin team to include php-snmp yet.

**Comment by netniV** [comment]
Setting the value means nothing in 1.2.3 as its just a variable setting.  All code to handle the process was introduced in a recent commit and will be released as part of 1.2.4
