### ISSUE TITLE
Feature Request: Ignore legend text format in Aggregates

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#2659]
When creating an Aggregate graph the user is given the option to use a Prefix for each GPRINT line to help distinguish it from other graph items. When this option is used, there should be an adjacent option to suppress the default 'Text Format' for the associated graph item. Otherwise this same text is displayed over and over again for each graph item, and it's not entirely useful. This is one thing holding me back from converting many of my legacy Aggregate graphs into the new style.

See this example yielded from the new style Aggregate, where "Temperature" is repeated unnecessarily each time:
![cacti_graph_57916](https://user-images.githubusercontent.com/12864741/56936593-74a36180-6ab5-11e9-9eef-5791754d1c48.png)
Repeating "Temperature" in this manner also expands the legend too far and cuts off the "Max:"

**Comment by eschoeller** [comment]
I find it *very* interesting that when I modify the legend text for a LINE1 object in a graph template, it does NOT propagate into the Aggregate to change the LINE1 text there. The aggregate retains the original text the graph template had when it was created. So, that means this is getting stashed away somewhere, I just can't tell where.

**Comment by eschoeller** [comment]
OK, so I have found these in the graph_templates_item table. I guess a more concerning issue is that these have been hard-coded in, and not entered as |host_description| as I had specified. So, when I change the description of the host, the aggregate text_format is not updating.

**Comment by cigamit** [comment]
There was some optimization done not to push out everything every time you saved a graph.  Some of that optimization was not fully rationalized.  We can address this after 1.2.4.

**Comment by eschoeller** [comment]
So, it looks like the existing legend text is now being removed in 1.2.4. But the text is still hard-coded into the graph_templates_item text_format field, so when the data changes the only way to update all this is to temporarily change the text_format for it to update everything.

**Comment by cigamit** [comment]
Hmm, I have to think about this one.

**Comment by eschoeller** [comment]
Yes, I have confirmed this is working, thank you very much!!

**Comment by cigamit** [comment]
Thanks!
