### ISSUE TITLE
during "Incorrect display of archived graphs. Bursts on the charts in cacti 1.2.1 (#2639)"

### ISSUE THREAD

**Issue by maxstech** [Cacti/cacti#2660]
Thank you for your comments.
But for me the situation is critical.
The difference between the total cacti and counters cisco
Here is an example of one client:
![raznica2](https://user-images.githubusercontent.com/47040342/56968797-7aa84980-6b6c-11e9-8f69-cd184d55ca6d.jpg)
incoming traffic: 4 (cacti) - 3.68 (cisco) = 0.32 GB
for outgoing traffic 172.87 (cacti) -161(cisco) - 11.87 GB.
It's only for 4 days of work. Is this difference caused by these spikes in the charts ?
It turns out that I am not able to see the actual data from the archive charts.
You're talking about adjustments, could you stop here for details. What can I do to avoid these spikes.
Why doesn't this happen in cacti Version 0.8.7 g ?
Maybe I should change the rrdtool version . Now I have - RRDtool 1.7.0

**Comment by cigamit** [comment]
Is Cisco using 1024 vs. 1000 bytes to the KBytes?  Cacti is using KBytes aka 1K == 1000.  Cisco may be using KiB == 1024 bytes to the KiB.  The Cacti numbers look spot on.

**Comment by maxstech** [comment]
Here's the problem. Where do cacti get more than counters ? On my screen is indicated in bytes - they are all the same. Interface Cisco shows: 3952824046 divide that by 1000, you get ~3.95 Gb. Where did cactus for 4 days, took another 500  ? I still want to deal with spikes As they change the total amount of traffic not only on the charts but in fact. 08.05.2019, 06:53, "Jimmy Conner" <notifications@github.com>:Is Cisco using 1024 vs. 1000 bytes to the KBytes?  Cacti is using KBytes aka 1K == 1000.  Cisco may be using KiB == 1024 bytes to the KiB.  The Cacti numbers look spot on.

**Comment by cigamit** [comment]
What spikes are you referring to?  If you are getting spikes, then your maximum values in the RRDfiles may be incorrect.

**Comment by maxstech** [comment]
About which spoke in #2639. How to get rid of these overlays. Maybe there are recommendations.18:55, 11 мая 2019 г., Jimmy Conner <notifications@github.com>:What spikes are you referring to?  If you are getting spikes, then your maximum values in the RRDfiles may be incorrect.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by cigamit** [comment]
Closing as I'm not certain what we can do here.  The behavior is as expected.
