### ISSUE TITLE
Automation - Wrong network/netmask calculation

### ISSUE THREAD

**Issue by lbullian** [Cacti/cacti#2661]
**Describe the bug**
The IP addresses calculated of hosts to be scanned in "Automation->Networks" are wrong when the input is something different from xx.xx.xx.0/xx.

**To Reproduce**
1. Go to 'Automation->Networks'
2. Add new network for example '172.21.66.192/28'
3. Discover Now, with debug mode.
4. See logs. (Scanned: 172.21.66.192 to 172.21.66.205)

**Expected behavior**
Hosts scanned should be 

- HostMin:   172.21.66.193        10101100.00010101.01000010.1100 0001
- HostMax:   172.21.66.206        10101100.00010101.01000010.1100 1110

**Screenshots**
not applicable

**Desktop (please complete the following information):**
 - OS: Linux Debian 9
 - Browser: Any
 - Version: Any

**Additional context**
The problem is not present when the network is something that ends in 0. Like: 172.20.84.0/28

**Comment by cigamit** [comment]
@netniV, should I take this one?

**Comment by cigamit** [comment]
This should be resolved in develop now.  Thanks for pointing out.  Some real old code there.
