### ISSUE TITLE
Instalation Stuck 0%

### ISSUE THREAD

**Issue by optimuscream** [Cacti/cacti#2666]
Hello 

My issue is almost the same as issue "Installation progress stays at 0% #2304". Same problem, I also follow all the guide there no success
I don't want to re-opened closed issue.

I want to upgrade from 1.1.38 to 1.2.x (development) branch pulled from git.

from cacti_dir/cacti.log 

I only can see auth login log:

2019/05/03 10:07:45 - AUTH LOGIN: User 'my_username' Authenticated  --> with admin privileges

No other error.

and from the browser only show :

=====================================================================
Installation In Progress

There is an Installation or Upgrade in progress.

Only Cacti Administrators with Install/Upgrade privilege may login at this time

[Return | Login Again]
=====================================================================

Stuck forever.

```
tail -f /var/log/apache2/error.log

Fri May 03 10:17:13.765600 2019] [mpm_prefork:notice] [pid 22822] AH00163: Apache/2.4.10 (Debian) configured -- resuming normal operations
[Fri May 03 10:17:13.765688 2019] [core:notice] [pid 22822] AH00094: Command line: '/usr/sbin/apache2'
```

No error.

What I have done;

```
SELECT * FROM settings WHERE name = 'log_install' or name = 'log_verbosity';
+---------------+-------+
| name          | value |
+---------------+-------+
| log_install   | 5     |
| log_verbosity | 5     |
+---------------+-------+

```
and also

Running Database Upgrade Script

sudo -u cacti php -q cli/upgrade_database.php --forcever=`cat include/cacti_version`

Updating Cacti Version in Database

update version set cacti = '1.1.38';

```
a2dismod 
Your choices are: access_compat alias auth_basic authn_core authn_file authz_core authz_host authz_user autoindex deflate dir env filter mime mpm_prefork negotiation php5 reqtimeout rewrite setenvif status
Which module(s) do you want to disable (wildcards ok)?
```

_No mod_security enabled._

My server detail:

- Debian 8
- 3.16.0-7-amd64 #1 SMP Debian 3.16.59-1 (2018-10-03) x86_64 GNU/Linux
- apache2                        2.4.10-10+deb8u13
- libmariadbd-dev                10.0.38-0+deb8u1 
- mariadb-server                 10.0.38-0+deb8u1
- php5                           5.6.40+dfsg-0+deb8u1
- php5-mysql                     5.6.30+dfsg-0+deb8u1

How to debug further ?

Thks.

**Comment by netniV** [comment]
> Installation In Progress
>
> There is an Installation or Upgrade in progress.
>
> Only Cacti Administrators with Install/Upgrade privilege may login at this time
>

Well, that's interesting because it would suggest that you have lost the privileges that you need to perform the upgrade.  The code should self correct this if there is no other admins with that privilege.

To check, run this:

```sql
select * from user_auth_realms where realm_id = 26
```

> SELECT * FROM settings WHERE name = 'log_install' or name = 'log_verbosity';

This will cause very verbose logging to be written to install-complete.log and cacti.log.  The install-complete.log would be useful if the problem was the above issue of permissions.

> sudo -u cacti php -q cli/upgrade_database.php --forcever=cat include/cacti_version

ALthough this is missing the single backticks, I can figure you put them there.  However, this would do nothing because that would update the database by forcing the original version to be the same as the current version, ego, no updates required.

Forcever should be the version you are coming from.

**Comment by optimuscream** [comment]
> > Installation In Progress
> > There is an Installation or Upgrade in progress.
> > Only Cacti Administrators with Install/Upgrade privilege may login at this time
> 
> Well, that's interesting because it would suggest that you have lost the privileges that you need to perform the upgrade. The code should self correct this if there is no other admins with that privilege.
> 
> To check, run this:
> 
> ```sql
> select * from user_auth_realms where realm_id = 26
> ```
I've done this command but I'm not aware my username is not in the list. 
> 
> > SELECT * FROM settings WHERE name = 'log_install' or name = 'log_verbosity';
> 
> This will cause very verbose logging to be written to install-complete.log and cacti.log. The install-complete.log would be useful if the problem was the above issue of permissions.
> 
> > sudo -u cacti php -q cli/upgrade_database.php --forcever=cat include/cacti_version

I've have to type manually 
php -q cli/upgrade_database.php --forcever=1.1.38
and suddenly it updating. I forgot what happened before something tell that it already updated
> 
> ALthough this is missing the single backticks, I can figure you put them there. However, this would do nothing because that would update the database by forcing the original version to be the same as the current version, ego, no updates required.
> 
> Forcever should be the version you are coming from.

Install goes through and success.
Please close the ticket.

Thank you.

**Comment by netniV** [comment]
If you had the above problem, the chances are you will have this again on the next upgrade.
