### ISSUE TITLE
Trailing parentheses are removed from the SNMP system description

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#2668]
I've noticed this one for awhile. See the output from SNMP:
```
RFC1213-MIB::sysDescr.0 = STRING: "CRAH-1 (North)"
```
See what comes through in Cacti:
![image](https://user-images.githubusercontent.com/12864741/57189651-356a7b80-6ece-11e9-85bb-c66d3bc433b2.png)

Nothing major.

**Comment by cigamit** [comment]
Well, that was odd.  The snmp string was being trimmed by a regex, going to try to trace why that was added.

**Comment by cigamit** [comment]
Okay, resolved this.  There was a pull request back in 2017 with no explanation.  So, backed off the offending portion.

**Comment by eschoeller** [comment]
That fixed it!

**Comment by eschoeller** [comment]
I think this might have broken something else though (one of my scripts). So I just backed it out. I'll take another closer look at this later.

**Comment by netniV** [comment]
So, the regex was extended to look for the values of "(up" or "(down" and remove them for some reason.  Plus it was also asked to remove the closing bracket if it was on the end of the line.  This was added by @arno-st 11th May 2017 with the comment of 'I also change the REGEXP_SNMP_TRIM to be able to handle correctly the status of an interface who can give up or down status, and now it's not handle correctly'

**Comment by cigamit** [comment]
@eschoeller, the issue we have with the current snmp library functions include one issue around obtaining numeric data vs. text data.

There is no way to say: "Hey, I don't want the walk to return up or down, I want it to return 1 or 0", the same applies with your HRULE issues.  "Hey, I want the numeric value without the suffix, and not the whole string.".

Some of this can be accommodated by a value regex.  But there may be some cases that can not be accommodated by that.

There is also a major compatibility issue with the SNMP class in php-snmp module that needs to be corrected.  So, basically, it's a mess right now.

**Comment by eschoeller** [comment]
Confirmed working in 1.2.4
