### ISSUE TITLE
Cacti server setup wizard

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#2670]
Hey All

I know that on the forms and around the web there are users who run into installation issues where a package is missing or a DB is not created right etc I have created a cacti-server setup wizard that includes all of the packages downloads and installs plugins and tunes maria 

I think this might be a great  tool for new users to use so they can get the server up and running and as long as they run the script they should get a working install

I have also put in logic to download and compile spine properly which is another pain point for some users 

Check it out https://github.com/bmfmancini/cacti-install-wizard.git

**Comment by cigamit** [comment]
That's pretty cool.  If you haven't already, you should post on the forums as well.
