### ISSUE TITLE
Cacti Install on Windows Fails

### ISSUE THREAD

**Issue by dedefri** [Cacti/cacti#2672]
Hello, I have problem install cacti using package from https://www.cacti.net/downloads/packages/Windows/

![cacti](https://user-images.githubusercontent.com/50319643/57265989-3b19ba00-70a4-11e9-8fc6-4f8f245a3956.png)

OS : windows 7x86
browser : Firefox and Chrome

C:\Cacti\php>php -m
[PHP Modules]
bcmath
calendar
com_dotnet
Core
ctype
date
dom
filter
gd
gettext
gmp
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
Phar
readline
Reflection
session
SimpleXML
snmp
sockets
SPL
standard
tokenizer
wddx
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**Comment by dedefri** [comment]
check at "php_errors.txt"

[07-May-2019 09:28:20 Asia/Jakarta] PHP Warning:  Invalid argument supplied for foreach() in C:\Cacti\Apache24\htdocs\cacti\lib\utility.php on line 1427
[07-May-2019 09:28:20 Asia/Jakarta] PHP Warning:  Invalid argument supplied for foreach() in C:\Cacti\Apache24\htdocs\cacti\lib\installer.php on line 1656

**Comment by cigamit** [comment]
This issue turned into something a bit different.  Can you please download the develop version and try again.  It should behave better now.  Report back ASAP.

**Comment by dedefri** [comment]
thank you for your response.
now I'm using ubuntu 18.04.2 LTS and cacti 1.1.38
but why didn't I get latest version cacti 1.2.3 ??

**Comment by cigamit** [comment]
Once Cacti 1.2.4 is released, it may be marked stable in your environment.  However, I think the 1.2 version is currently in unstable.  You might want to check with @paulgevers on this one.  We've had some delays recently.  We hope to have 1.2.4 released soon.

**Comment by paulgevers** [comment]
```
paul@testavoira ~ $ rmadison cacti
cacti      | 0.8.8b+dfsg-8+deb8u6 | oldstable  | source, all
cacti      | 0.8.8h+ds1-10        | stable     | source, all
cacti      | 1.2.2+ds1-2          | testing    | source, all
cacti      | 1.2.2+ds1-2          | unstable   | source, all
```
Ubuntu 18.04 is (of course) more than 1 year old, so that isn't up-to-date.

Debian buster is soon to be released, so the package will remain what it is now in testing, unless security issues appear.

It is my intention to provide newer Cacti versions for Debian via backports and for Ubuntu 19.4 via my ppa as long as that is reasonably possible due to dependencies.

**Comment by netniV** [comment]
Thanks for the breakdown @paulgevers Always useful to know. What will it take to get updated version into stable sometime in the future?

**Comment by paulgevers** [comment]
In Debian stable (and currently in testing because we are frozen) only targeted fixes for serious bugs are allowed. So a newer Cacti version in stable is close to impossible.

**Comment by netniV** [comment]
That makes no sense given that the only version in stable is almost 4 years old now I’ve got myself

**Comment by paulgevers** [comment]
We'll release a new stable soon.

Sorry, that's how Debian works. (And that is why the backports archive exists).

**Comment by netniV** [comment]
Thats OK just seems illogical to me to have such well outdated software considered base.  I guess I just expect the whole testing, unstable, stable process to be more efficient given the updates that are constantly being made available for other software.

Getting back to the issue at hand, we are hoping to have 1.2.4 by the end of the month.

**Comment by tejindersinghmehta1** [comment]
I am facing a similar issue with cacti version 1.2.5 installing on windows 10.

Any help will be highly appreciated. 
![cacti](https://user-images.githubusercontent.com/54613859/63826656-d00b3080-c97d-11e9-96fb-5d4a71a708e5.JPG)

**Comment by netniV** [comment]
Generally speaking it normally means that either the modules are not enabled within the PHP.INI used by the command line or the path to the php.exe  (path_php_binary)  is incorrect in the settings table.

**Comment by alisiddiqui1987** [comment]
netniV can you please guide which one to use from below. I got two php.exe files in Xampp folder

C:\xampp\php\php.exe
C:\xampp\php\windowsXamppPhp\php.exe

since last 4 days i am stuck with this problem and unable to find any solution to this. I am unaware of any of the programming language hence step by step guidance to fix the issue would be appreciated.
![cli](https://user-images.githubusercontent.com/56796839/67241337-e1018b00-f470-11e9-92df-20ac69a9d55d.PNG)

**Comment by netniV** [comment]
You need to run the install/cli_check.php with the single parameter of extensions, recommends and optionals, then post all output here.

**Comment by alisiddiqui1987** [comment]
Thanks netniV for your response. can you please how should I do that. as I said I am not a programmer so step by step guide would be needed.

I am using windows 10 xampp. all the files of cacti are store in htdocs forlder of xampp and some in xampp folder itself.

I tried to run cli_check.php and it says 
#!/usr/bin/php -q
This script is only meant to run at the command line.

when I try to open that file with command as below, nothing shows up and stucks there
c:\xampp\php>php.exe -c "c:\xampp\cacti\install\cli_check.php"

Also I did a test for print_r(get_loaded_extensions()); and attached the output for your reference

please review and suggest what needs to be done.

![cli_check](https://user-images.githubusercontent.com/56796839/67285800-d63d0980-f4f5-11e9-9aa0-633218031d93.PNG)
![cli_check_web](https://user-images.githubusercontent.com/56796839/67285837-ebb23380-f4f5-11e9-93b8-400d4fa53307.PNG)
![module](https://user-images.githubusercontent.com/56796839/67285922-0dabb600-f4f6-11e9-804f-2aac8ec9acc6.PNG)

**Comment by netniV** [comment]
So it would appear that the reason you are getting no modules/requirements listed is because you're PHP.INI is trying to load MySQL extensions and failing for some reason.  You need to fix that so the script can run properly.  You should be using the -q option by the way which suppresses PHP headers normally created for the web side.
