### ISSUE TITLE
[usibility] Can not show all columns which I have choosed and have no hint for user 

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/cacti#2673]
**To Reproduce**
1. Go to Cluster - By Host page 
2. Set the page to show total 23 columns, but the page only show 15 columns 

**Expected behavior**
The new behavior for cacti displaying the column is Screen size adaptation, If the screen is small, can not display all the columns.  but we should add some hint to notice user there will be more columns to show. 

**Screenshots**
![Screen Shot 2019-05-07 at 2 08 53 PM](https://user-images.githubusercontent.com/47589910/57275709-e7be6080-70d1-11e9-919f-5fc1d28151f0.png)

**Desktop (please complete the following information):**
 cacti 1.2.3 
 FF

**Comment by cigamit** [comment]
This is by design and part of responsive design. So, it's not a bug.
