### ISSUE TITLE
When a string is above 80 characters, language translation can fail due to wrapped MSGID's

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#2674]
**Describe the bug**
Content of web is outside browser (and no thereis no scrollbars).
I cannot see whole page content in theme MODERN.

**To Reproduce**
1. Go to 'https://cacti/user_admin.php?action=user_edit&id=19&tab=realms'
2. See whole page

**Expected behavior**
Content of page in the visible place of browser.

**Screenshots**
![content-cacti](https://user-images.githubusercontent.com/17087236/57286820-71f8cb80-70b6-11e9-95bb-973a6d97ab7e.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Browser: Chromium
 - Version: 73.0.3683.103

**Comment by bmfmancini** [comment]
Not seeing the same thing here 
I am using Firefox 66.0.4 (64-bit)

Maybe an issue specific to chromium try firefox  on your end

Thanks!

**Comment by interduo** [comment]
Change language to Polish. This causes problem.

`Project-Id-Version: Report-Msgid-Bugs-To: POT-Creation-Date: 2019-03-10 13:25-0400 PO-Revision-Date: 2019-03-10 13:43-0400 Last-Translator: Language-Team: Language: pl_PL MIME-Version: 1.0 Content-Type: text/plain; charset=UTF-8 Content-Transfer-Encoding: 8bit Plural-Forms: nplurals=3; plural=(n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<12 || n%100>14) ? 1 : 2); X-Generator: Poedit 2.2.1`

**Comment by cigamit** [comment]
Yes, somehow we are attempting to translate and empty string.  We've seen this one time before.

**Comment by cigamit** [comment]
Okay, using the develop version with latest syslog, and the latest polish translation, I can not reproduce this.  So, I suspect it's solved.  Can you please do the same and confirm?

**Comment by interduo** [comment]
Don't want to update to develop version. I am using master branch.
When will 1.2.4 will come up? I will check on that version.

**Comment by cigamit** [comment]
No feedback.  I've checked on version 1.2.4 and can not reproduce.  Someone needs to verify the Polish strings.  Under both User Management and User Group Management, there are several untranslated strings.

You can go to https://translate.cacti.net and sign up for an account.  When using the Translate site, performing translations for not only Cacti, but all of our Plugins is quite simple.  If you wish to be in charge of approving strings for the Polish language, you simply need to reach out to @netniV who can do the assignment.

**Comment by cigamit** [comment]
Here is the link to where you would start with an account to Translate Cacti into Polish:

https://translate.cacti.net/projects/cacti/core/pl-PL/

**Comment by interduo** [comment]
The issue still exists in Polish translation. 
I did some translations but cannot find the missing translations. 

Please reopen this.

**Comment by interduo** [comment]
Look there is no strings from user_edit form in localization files.

I tried to search this by:
`https://translate.cacti.net/search/cacti/core/?checksum=&offset=&q=Realtime+Graphs&search=ftx&source=on&target=on&context=on&location=on&comment=on&type=all&ignored=False&date=&only_user=&exclude_user=&lang=pl-PL
`

**Comment by interduo** [comment]
The whole cacti is mixed up by translation english/polish even if I choose English language in user profile and in main setttings there is many things in polish language.

**Comment by netniV** [comment]
@interduo can you please link the source string that you believe to be wrong?

**Comment by netniV** [comment]
I have found that the string exists in the POT file:
```
locales/po/cacti.pot:6635:msgid "Realtime Graphs"
locales/po/cacti.pot:11796:msgid "How do you wish to view Realtime Graphs?"
```

I also noticed that your search link is using FullText and that appears to fail in finding the string.  If you change that to Substring, it correct finds the above two entries.

**Comment by interduo** [comment]
Well, just look at the first screenshot. In Plugin permission tab - probably the missed the header before "Device Monitoring".

**Comment by interduo** [comment]
![cacti](https://user-images.githubusercontent.com/17087236/61083298-acbb0f00-a42b-11e9-83c6-2f1b552db87d.png)

**Comment by interduo** [comment]
If I change to English there is no debug text.

**Comment by netniV** [comment]
I've found and I am about to commit a change to all the POT/PO files.  The issue seems to be that the MSGID is being wrapped but when it is, the ID goes from being the full string to having a blank first line then the rest that follows.

To correct this issue, we can tell it not to wrap on both the xgettext and msgmerge calls.  Hopefully, this will have no side effects but I am going to try committing this to the develop branch now.

Can you test update to the latest once it is there and then test that?
