### ISSUE TITLE
issue while installing

### ISSUE THREAD

**Issue by scarface10** [Cacti/cacti#2675]
![image](https://user-images.githubusercontent.com/21038504/57291336-f4958100-70de-11e9-8cb2-1cbbbdea13ac.png)
all path are right but it says One or more paths appear to be incorrect, unable to proceed. I can't install

**Comment by cigamit** [comment]
We need to see the instal log.  It'll be in your Cacti log directory.

**Comment by scarface10** [comment]
![image](https://user-images.githubusercontent.com/21038504/57351270-f9ab0c80-7180-11e9-9cd0-e5d06a8e5653.png)

**Comment by scarface10** [comment]
I solved it!!!
Tried using opera browser it works.
Don't know why next button work on google chrome

**Comment by scarface10** [comment]
![Uploading image.png…]()
