### ISSUE TITLE
Skin paper plane not working on iPhone XR

### ISSUE THREAD

**Issue by reboot1983** [Cacti/cacti#2676]
The topmenu (console, graph, etc.) don’t work on my mobile device (iPhone xr) on default browser Safari and Chrome browser in the graphs tab.

De dropdowns do not respond and also the menubuttons do nothing in the graphs tab. Not in landscape or portrait mode.

Also the treemenu does not popup. 
Also the graphs are very small in portrait mode. In landscape it looks fine.

This is Cacti 1.2.3.

![IMG_0074](https://user-images.githubusercontent.com/20405704/57325581-a26a5500-710a-11e9-9f9a-ec2dfc69bcc0.jpg)

**Comment by cigamit** [comment]
Is there any way to look for JavaScript bugs on that page?  What happens when you flip to landscape mode and back again?

**Comment by reboot1983** [comment]
If I flip it to landscape mode, the image are large. But the menu still doesn't work. I don't know how to check for JavaScript issues on the page. Console page does work, but the graphs page does not.

**Comment by cigamit** [comment]
Should be better now.  You should be able to simply update include/layout.js and refresh the browser cache.

**Comment by reboot1983** [comment]
Thanks for the changes.
I can see something has changed, but the issue is not solved yet. The menu on the left side is gone now. Which gives more room for the graphs, but they are still small.
Besides that, the top-menu still doesn't work which makes navigating impossible.

When I go to landscapemode, the graphs are showing largere (exactly like the screenshot above in this issue).

**Comment by cigamit** [comment]
Well, that is odd.

**Comment by cigamit** [comment]
I was able to reproduce and latest layout.js should get it.

**Comment by reboot1983** [comment]
One part has been resolved. 👍 The graphs are large now. In portrait and also in landscape mode.
But, the top menu items are still not working in graphs view. They do work in all other views, but not in Graphs mode.

The 'paper plane' icon is highlighted when I click on it, but the console panel is not viewing. Also the graphs, reports, question mark and the 'person icon' have the same behaviour and bug. These options are all not working when in Graphs view (in landscape and portrait mode).

When I am in console view, the paper plane icon is toggling the left menu (as it should) and all other topmenu items are functioning. The topmenu only does not work in Graphs view. In Graphs view in landscape mode the left tree menu is visible until you collapse it. Then there is no possibility to get it back, because the topmenu also here does not work.

**Comment by reboot1983** [comment]
This has not been resolved. Please read last post.

**Comment by netniV** [comment]
Do you have any javascript errors at that point?

**Comment by reboot1983** [comment]
How can I see that on my iPhone?

**Comment by netniV** [comment]
https://blog.chromium.org/2019/03/debugging-websites-in-chrome-for-ios.html
