### ISSUE TITLE
Users with passwords that do not meet complexity requirements are not redirected to the Change Password page

### ISSUE THREAD

**Issue by rickyowens** [Cacti/cacti#2679]
After setting 'Force Complexity Upon Old Passwords', users who don't meet the new complexity requirements are not redirected to the Change Password page, instead receive a dialog box like below.

![cactlogin](https://user-images.githubusercontent.com/39543507/57411146-d0ea4c00-7240-11e9-9812-a2dd8a625148.PNG)

**Comment by cigamit** [comment]
Yea, that's a problem.

**Comment by cigamit** [comment]
This is resolved now.
