### ISSUE TITLE
Centos 7 installation wizard ends in http 500

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#2681]
Hello All 

I have noticed on a fresh Centos 7 install on 1.2.4 that  I am getting error 500 with the following in the error_log file fot httpd

[Sat May 11 05:32:55.987845 2019] [php7:error] [pid 7384] [client x.x.x.x] PHP Fatal error:  Uncaught Error: Call to undefined function cacti_escapseshellcmd() in /var/www/html/cacti/lib/installer.php:2502\nStack trace:\n#0 /var/www/html/cacti/lib/installer.php(1514): Installer->processStepInstall()\n#1 /var/www/html/cacti/lib/installer.php(179): Installer->processCurrentStep()\n#2 [internal function]: Installer->jsonSerialize()\n#3 /var/www/html/cacti/install/step_json.php(66): json_encode(Object(Installer))\n#4 {main}\n  thrown in /var/www/html/cacti/lib/installer.php on line 2502, referer: http://x.x.x.x/cacti/install/install.php?data={%22Step%22:%229%22,%22Eula%22:true}

However, on 1.2.3 and others, everything is running fine 
the installer does continue however it just hangs showing that the log file cannot be found but it is indeed there 

My install method is here 
https://github.com/bmfmancini/cacti-install-wizard/blob/master/cacti-install-wizard-centos.sh

**Comment by cigamit** [comment]
Thanks, fixed now.
