### ISSUE TITLE
cacti 1.2.4 graph_json.php errors 

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#2682]
Hey Guys 

New  install on 1.2.4 I am seeing the following errors  right away in cacti.log

2019/05/10  15:42:51 - CMDPHP PHP ERROR NOTICE Backtrace:   (/graph_json.php[220]:rrdtool_function_graph(),  /lib/rrd.php[2127]:CactiErrorHandler())
--
2019/05/10 15:42:51 - ERROR PHP NOTICE: Only variables should be  passed by reference in file: /var/www/html/cacti/lib/rrd.php  on line:  2127
2019/05/10 15:42:51 - CMDPHP PHP ERROR NOTICE Backtrace:   (/graph_json.php[220]:rrdtool_function_graph(),  /lib/rrd.php[2127]:CactiErrorHandler())
2019/05/10 15:42:51 - ERROR PHP NOTICE: Only variables should be  passed by reference in file: /var/www/html/cacti/lib/rrd.php  on line:  2127
2019/05/10 15:42:51 - CMDPHP PHP ERROR NOTICE Backtrace:   (/graph_json.php[220]:rrdtool_function_graph(),  /lib/rrd.php[2127]:CactiErrorHandler())
2019/05/10 15:42:51 - ERROR PHP NOTICE: Only variables should be  passed by reference in file: /var/www/html/cacti/lib/rrd.php  on line:  2127
2019/05/10 15:42:51 - CMDPHP PHP ERROR NOTICE Backtrace:   (/graph_json.php[220]:rrdtool_function_graph(),  /lib/rrd.php[2127]:CactiErrorHandler())
2019/05/10 15:42:51 - ERROR PHP NOTICE: Only variables should be  passed by reference in file: /var/www/html/cacti/lib/rrd.php  on line:  2127
2019/05/10 15:42:51 - CMDPHP PHP ERROR NOTICE Backtrace:   (/graph_json.php[220]:rrdtool_function_graph(),  /lib/rrd.php[2127]:CactiErrorHandler())
2019/05/10 15:42:51 - ERROR PHP NOTICE: Only variables should be  passed by reference in file: /var/www/html/cacti/lib/rrd.php  on line:  2127
2019/05/10 15:42:51 - CMDPHP PHP ERROR NOTICE Backtrace:   (/graph_json.php[220]:rrdtool_function_graph(),  /lib/rrd.php[2127]:CactiErrorHandler())
2019/05/10 15:42:51 - ERROR PHP NOTICE: Only variables should be  passed by reference in file: /var/www/html/cacti/lib/rrd.php  on line:  2127
2019/05/10 15:42:50 - CMDPHP PHP ERROR NOTICE Backtrace:   (/graph_json.php[158]:rrdtool_function_graph(),  /lib/rrd.php[2127]:CactiErrorHandler())
2019/05/10 15:42:50 - ERROR PHP NOTICE: Only variables should be  passed by reference in file: /var/www/html/cacti/lib/rrd.php  on line:  2127
2019/05/10 15:42:50 - CMDPHP PHP ERROR NOTICE Backtrace:   (/graph_json.php[158]:rrdtool_function_graph(),  /lib/rrd.php[2127]:CactiErrorHandler())

Here is the specific code 

                                        break;
                                case GRAPH_ITEM_TYPE_HRULE:
                                        /* perform variable substitution; if this does not return a number, rrdtool will FAIL! */
                                        $substitute = strip_alpha(rrd_substitute_host_query_data($graph_variables['value'][$graph_item_id], $graph, $graph_item));

Date | Fri, 10 May 2019 15:56:53 -0400
-- | --
Cacti Version | 1.2.4
Cacti OS | unix
RSA Fingerprint | 5f:c6:e7:c5:42:82:af:57:cb:65:cf:fb:38:d7:67:51
NET-SNMP Version | NET-SNMP version: 5.7.2
RRDtool Version Configured | 1.4.0+
RRDtool Version Found | 1.4.8
Devices | 12
Graphs | 90
Data Sources | Script/Command: 9SNMP Get: 8SNMP Query: 32Script Server: 36Total: 85

**Comment by bmfmancini** [comment]
Issue is on my end

**Comment by fedsan** [comment]
Hi bmfmancini, what was issue that caused the errors?

**Comment by netniV** [comment]
It normally means you've attached to pass a constant (such as a piece of text) to a parameter that expects to be a referenced field to be updated.
