### ISSUE TITLE
Sunrise theme breadcrumb icons set far left 

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#2683]
Hey Everyone 

just noticing 2 issues with the sunrise theme 

1.) The breadcrumb icons are all the way to the right
![image](https://user-images.githubusercontent.com/13388748/57728607-523b4780-7662-11e9-92a7-afee5bf3e81b.png)

2.) You have to hover around the graph for a while before they actually show up 

see below the icons arent shown 

![image](https://user-images.githubusercontent.com/13388748/57728681-7e56c880-7662-11e9-8c7e-cda1b1beb14f.png)

**Comment by bmfmancini** [comment]
Issue number 2 seems that there just needs to be a specific area to hover  over so users know where to place the mouse  

Also, something nice to have would be an option to have the icons always showing

**Comment by netniV** [comment]
The icons are always displayed.  If you only see them in certain circumstances, it will be styling issue that is changed when other attributes come into play

**Comment by bmfmancini** [comment]
Hmm ok on the modern theme the icons are always visible but sunrise you kinda have to guess where to hover for them to display

**Comment by cigamit** [comment]
Looks good from my end.  Check for JavaScript errors in the browsers debug console.

![SunRiseTheme](https://user-images.githubusercontent.com/957322/57973538-deee4a00-796f-11e9-81ef-91721ccdbe60.png)

**Comment by bmfmancini** [comment]
Sure I will check and let you know what i see

**Comment by bmfmancini** [comment]
Not seeing any errors but here is what I am seeing  but here is the issue I am seeing only with themes other than Modern

![sunrise theme issue](https://user-images.githubusercontent.com/13388748/58129729-6b0aa680-7be8-11e9-8435-ecbfcd46bb61.gif)

**Comment by cigamit** [comment]
This is the design behavior.  The icons are hidden until you hover over the area to the right of the graph.

**Comment by bmfmancini** [comment]
Can we have it so the icons always show?

As you can see it's not always easy to get the icons to display you have to
hover around a bit before they show

In the modern the icons always show making it easier to click on them

**Comment by netniV** [comment]
It could possibly be made an option so that it’s not hidden if desired but since the default is currently to hide it so I think that the default should remain. There may be a reason with the UI in the skin mode as to why that decision was made so we will have to review it

**Comment by cigamit** [comment]
We could add a javascript option.  But that would imply that everyones themes should showing and hiding things, which is a big assumption.  I would suggest that you 'cp -rp sunrise mysunrise' and start from there.
