### ISSUE TITLE
Data graphics are not right

### ISSUE THREAD

**Issue by tyit** [Cacti/cacti#2684]
![image](https://user-images.githubusercontent.com/31933126/57767170-55563680-773b-11e9-820a-03ed3613cc99.png)

![image](https://user-images.githubusercontent.com/31933126/57767182-5ab38100-773b-11e9-9c06-2dd4e1237622.png)

![image](https://user-images.githubusercontent.com/31933126/57767196-6010cb80-773b-11e9-9a69-ceb1532df2a4.png)

![image](https://user-images.githubusercontent.com/31933126/57767223-6737d980-773b-11e9-8e8e-e39d1e31dc00.png)

Cacti Version 1.2.3
My English is very bad.
I don't know how to operate, please help me. Thank you very much.

**Comment by netniV** [comment]
I believe that you are seeing two legends one for the line and one for the area in each section.  Check your template with the interface standard ones

**Comment by tyit** [comment]
@netniV 
Thank you very much for checking
