### ISSUE TITLE
Cacti AUTOM8 creates same multiple graphs 

### ISSUE THREAD

**Issue by fisnnik** [Cacti/cacti#2685]
I have cacti 1.2.3, when i create graphs with automate rules, it creates multiple same graph. So for the first time when i run autom8 rule, this happens

Example from log:
Line 33: 15/05/2019 11:06:09 - AUTOM8 NOTE: Graph Added - Device[DeviceUBR10k], Graph[DeviceUBR10k - SNR: Cable6/0/1-upstream5-MIT-NodeM 14, MIT-NodeM 11], DS[DeviceUBR10k - SNR: Cable6/0/1-upstream5-MIT-NodeM 14, MIT-NodeM 11] Graphs[DeviceUBR10k - SNR: Cable6/0/1-upstream5-MIT-NodeM 14, MIT-NodeM 11]
	Line 33: 15/05/2019 11:06:09 - AUTOM8 NOTE: Graph Added - Device[DeviceUBR10k], Graph[DeviceUBR10k - SNR: Cable6/0/1-upstream5-MIT-NodeM 14, MIT-NodeM 11], DS[DeviceUBR10k - SNR: Cable6/0/1-upstream5-MIT-NodeM 14, MIT-NodeM 11] Graphs[DeviceUBR10k - SNR: Cable6/0/1-upstream5-MIT-NodeM 14, MIT-NodeM 11]
	Line 33: 15/05/2019 11:06:09 - AUTOM8 NOTE: Graph Added - Device[DeviceUBR10k], Graph[DeviceUBR10k - SNR: Cable6/0/1-upstream5-MIT-NodeM 14, MIT-NodeM 11], DS[DeviceUBR10k - SNR: Cable6/0/1-upstream5-MIT-NodeM 14, MIT-NodeM 11] Graphs[DeviceUBR10k - SNR: Cable6/0/1-upstream5-MIT-NodeM 14, MIT-NodeM 11]
	Line 34: 15/05/2019 11:06:09 - AUTOM8 NOTE: [PID: 10940] create_graph_node() Graph[DeviceUBR10k - SNR: Cable6/0/1-upstream5-MIT-NodeM 14, MIT-NodeM 11] Tree Item - Added - id: (18574)

I dont know if this a bug or something but i am not able to find a way for this. In version 1.2.0 i didnt have this problem.

The next problem that i am having is when i go to Create -> New Graphs -> Choose the same device, and i click refresh that specific data query then again some graph are recreated again, and after this i am getting wrnings in cacti log:

15/05/2019 14:21:43 - POLLER: Poller[Main Poller] WARNING: You have 1 Devices with bad SNMP Indexes. Devices: Device[DeviceUBR10k] totalling 140 Data Sources. Please Either Re-Index, Delete or Disable these Data Sources.

Graphs that are recreated:

15/05/2019 14:26:43 - AUTOM8 NOTE: Graph Added - Device[DeviceUBR10k], Graph[DeviceUBR10k - SNR: Cable5/0/3-upstream6-MIT-NodeN 15], DS[DeviceUBR10k - SNR: Cable5/0/3-upstream6-MIT-NodeN 15] Graphs[DeviceUBR10k - SNR: Cable5/0/3-upstream6-MIT-NodeN 15] 

15/05/2019 14:27:01 - AUTOM8 NOTE: Graph Added - Device[DeviceUBR10k], Graph[DeviceUBR10k - SNR: Cable5/0/3-upstream6-MIT-NodeN 15], DS[DeviceUBR10k - SNR: Cable5/0/3-upstream6-MIT-NodeN 15] Graphs[DeviceUBR10k - SNR: Cable5/0/3-upstream6-MIT-NodeN 15] 

15/05/2019 14:29:02 - AUTOM8 NOTE: Graph Added - Device[DeviceUBR10k], Graph[DeviceUBR10k - SNR: Cable5/0/3-upstream6-MIT-NodeN 15], DS[DeviceUBR10k - SNR: Cable5/0/3-upstream6-MIT-NodeN 15] Graphs[DeviceUBR10k - SNR: Cable5/0/3-upstream6-MIT-NodeN 15] 

Also this didnt happen on Cacti 1.2.0, i have same automate rules and everything as it was before.

At configuration -> Settings i have disabled Automatic Graph Creation and Automatic Tree Item Creation.

Also i have deleted device and graphs and recreated them, same thing are happening again.

If you need more details i will be happy to assist.

**Comment by cigamit** [comment]
Which version are you running?  We resolved this problem after 1.2.0.

**Comment by cigamit** [comment]
Is this one of the indexes that are bad?

**Comment by cigamit** [comment]
I took a look at the query, and in the end, it did not need to be so complicated.  Try again with the latest lib/api_automation.php

**Comment by fisnnik** [comment]
****

IMPORTANT: I just found out that this is not happening with Data query: SNMP Interface statistics, everything fine here.
Only with some custom data query like this one attached, so maybe this a problem with this data query or smoething.
[cacti_data_query_cisco_-_yact_-_cable_snr.zip](https://github.com/Cacti/cacti/files/3197539/cacti_data_query_cisco_-_yact_-_cable_snr.zip)

***


In version cacti 1.2.3 i have modified file lib/api_automation.php as you request and did tests but there are same problem again.


Then i have upgraded to developing vresion 1.2.4 and same problems are again. Below you can find logs
(FYI i have deleted all graphs and added again)

These are the graphs that are created for the first time, as you can see again there are multiple graphs created. ( i have included only two graphs for sample)
But in log there is no error for bad snmp indexs.



20/05/2019 10:52:35 - AUTOM8 NOTE: [PID: 839] create_graph_node() Graph[UBR7246-Device - SNR: Cable2/0-upstream6-Restelice 3 - Linja e re] Tree Item - Added - id: (18807)
20/05/2019 10:52:15 - AUTOM8 NOTE: Graph Added - Device[UBR7246-Device], Graph[UBR7246-Device - SNR: Cable2/0-upstream6-Restelice 3 - Linja e re], DS[UBR7246-Device - SNR: Cable2/0-upstream6-Restelice 3 - Linja e re] Graphs[UBR7246-Device - SNR: Cable2/0-upstream6-Restelice 3 - Linja e re]
20/05/2019 10:52:15 - AUTOM8 NOTE: [PID: 7816] create_graph_node() Graph[UBR7246-Device - SNR: Cable2/0-upstream6-Restelice 3 - Linja e re] Tree Item - Added - id: (18806)
20/05/2019 10:52:14 - AUTOM8 NOTE: Graph Added - Device[UBR7246-Device], Graph[UBR7246-Device - SNR: Cable2/0-upstream6-Restelice 3 - Linja e re], DS[UBR7246-Device - SNR: Cable2/0-upstream6-Restelice 3 - Linja e re] Graphs[UBR7246-Device - SNR: Cable2/0-upstream6-Restelice 3 - Linja e re]
20/05/2019 10:52:14 - AUTOM8 NOTE: [PID: 7816] create_graph_node() Graph[UBR7246-Device - SNR: Cable2/0-upstream6-Restelice 3 - Linja e re] Tree Item - Added - id: (18805) 



20/05/2019 10:52:04 - AUTOM8 NOTE: Graph Added - Device[UBR7246-Device], Graph[UBR7246-Device - SNR: Cable1/0-upstream4-Restelice 2], DS[UBR7246-Device - SNR: Cable1/0-upstream4-Restelice 2] Graphs[UBR7246-Device - SNR: Cable1/0-upstream4-Restelice 2]
20/05/2019 10:52:04 - AUTOM8 NOTE: [PID: 7816] create_graph_node() Graph[UBR7246-Device - SNR: Cable1/0-upstream4-Restelice 2] Tree Item - Added - id: (18798)
20/05/2019 10:52:03 - AUTOM8 NOTE: Graph Added - Device[UBR7246-Device], Graph[UBR7246-Device - SNR: Cable1/0-upstream4-Restelice 2], DS[UBR7246-Device - SNR: Cable1/0-upstream4-Restelice 2] Graphs[UBR7246-Device - SNR: Cable1/0-upstream4-Restelice 2]
20/05/2019 10:52:02 - AUTOM8 NOTE: [PID: 7816] create_graph_node() Graph[UBR7246-Device - SNR: Cable1/0-upstream4-Restelice 2] Tree Item - Added - id: (18797)
20/05/2019 10:51:58 - AUTOM8 NOTE: Graph Added - Device[UBR7246-Device], Graph[UBR7246-Device - SNR: Cable1/0-upstream4-Restelice 2], DS[UBR7246-Device - SNR: Cable1/0-upstream4-Restelice 2] Graphs[UBR7246-Device - SNR: Cable1/0-upstream4-Restelice 2]
20/05/2019 10:51:58 - AUTOM8 NOTE: [PID: 7816] create_graph_node() Graph[UBR7246-Device - SNR: Cable1/0-upstream4-Restelice 2] Tree Item - Added - id: (18796)
20/05/2019 10:51:57 - AUTOM8 NOTE: Graph Added - Device[UBR7246-Device], Graph[UBR7246-Device - SNR: Cable1/0-upstream4-Restelice 2], DS[UBR7246-Device - SNR: Cable1/0-upstream4-Restelice 2] Graphs[UBR7246-Device - SNR: Cable1/0-upstream4-Restelice 2]
20/05/2019 10:51:56 - AUTOM8 NOTE: [PID: 7816] create_graph_node() Graph[UBR7246-Device - SNR: Cable1/0-upstream4-Restelice 2] Tree Item - Added - id: (18795) 



Now again when i go to  "Create -> New Graphs -> Choose the same device", and i click refresh that specific data query, then again some duplicate graphs are recreated, and after this i am getting wrnings in cacti log:
20/05/2019 11:11:52 - POLLER: Poller[Main Poller] WARNING: You have 1 Devices with bad SNMP Indexes. Devices: Device[UBR7246-Device] totalling 15 Data Sources. Please Either Re-Index, Delete or Disable these Data Sources.


20/05/2019 11:10:49 - AUTOM8 NOTE: Graph Added - Device[UBR7246-Device], Graph[UBR7246-Device - SNR: Cable2/0-upstream6-Restelice 3 - Linja e re], DS[UBR7246-Device - SNR: Cable2/0-upstream6-Restelice 3 - Linja e re] Graphs[UBR7246-Device - SNR: Cable2/0-upstream6-Restelice 3 - Linja e re]
20/05/2019 11:10:49 - AUTOM8 NOTE: [PID: 10500] create_graph_node() Graph[UBR7246-Device - SNR: Cable2/0-upstream6-Restelice 3 - Linja e re] Tree Item - Added - id: (18830)


20/05/2019 11:10:43 - AUTOM8 NOTE: Graph Added - Device[UBR7246-Device], Graph[UBR7246-Device - SNR: Cable1/0-upstream4-Restelice 2], DS[UBR7246-Device - SNR: Cable1/0-upstream4-Restelice 2] Graphs[UBR7246-Device - SNR: Cable1/0-upstream4-Restelice 2]
20/05/2019 11:10:43 - AUTOM8 NOTE: [PID: 10500] create_graph_node() Graph[UBR7246-Device - SNR: Cable1/0-upstream4-Restelice 2] Tree Item - Added - id: (18825)
20/05/2019 11:10:42 - AUTOM8 NOTE: Graph Added - Device[UBR7246-Device], Graph[UBR7246-Device - SNR: Cable1/0-upstream4-Restelice 2], DS[UBR7246-Device - SNR: Cable1/0-upstream4-Restelice 2] Graphs[UBR7246-Device - SNR: Cable1/0-upstream4-Restelice 2]
20/05/2019 11:10:42 - AUTOM8 NOTE: [PID: 10500] create_graph_node() Graph[UBR7246-Device - SNR: Cable1/0-upstream4-Restelice 2] Tree Item - Added - id: (18824)
20/05/2019 11:10:41 - AUTOM8 NOTE: Graph Added - Device[UBR7246-Device], Graph[UBR7246-Device - SNR: Cable1/0-upstream4-Restelice 2], DS[UBR7246-Device - SNR: Cable1/0-upstream4-Restelice 2] Graphs[UBR7246-Device - SNR: Cable1/0-upstream4-Restelice 2]
20/05/2019 11:10:41 - AUTOM8 NOTE: [PID: 10500] create_graph_node() Graph[UBR7246-Device - SNR: Cable1/0-upstream4-Restelice 2] Tree Item - Added - id: (18823)


These are the graphs with bad indexes:

UBR7246-Device - SNR: Cable1/0-upstream0-Restelice 1 - Qendra	20765	1 / 0	5 Minutes	No	Yes	Cisco - YACT - Cable SNR	
UBR7246-Device - SNR: Cable1/0-upstream0-Restelice 1 - Qendra	20782	1 / 0	5 Minutes	No	Yes	Cisco - YACT - Cable SNR	
UBR7246-Device - SNR: Cable1/0-upstream1-Restelice 1 - Qendra	20766	1 / 0	5 Minutes	No	Yes	Cisco - YACT - Cable SNR	
UBR7246-Device - SNR: Cable1/0-upstream1-Restelice 1 - Qendra	20783	1 / 0	5 Minutes	No	Yes	Cisco - YACT - Cable SNR	
UBR7246-Device - SNR: Cable1/0-upstream2-Restelice 1 - Qendra	20767	1 / 0	5 Minutes	No	Yes	Cisco - YACT - Cable SNR	
UBR7246-Device - SNR: Cable1/0-upstream2-Restelice 1 - Qendra	20784	1 / 0	5 Minutes	No	Yes	Cisco - YACT - Cable SNR	
UBR7246-Device - SNR: Cable1/0-upstream3-Restelice 1 - Qendra	20785	1 / 0	5 Minutes	No	Yes	Cisco - YACT - Cable SNR	
UBR7246-Device - SNR: Cable2/0-upstream1-Restelice 2 - Shkolla	20774	1 / 0	5 Minutes	No	Yes	Cisco - YACT - Cable SNR	
UBR7246-Device - SNR: Cable2/0-upstream1-Restelice 2 - Shkolla	20791	1 / 0	5 Minutes	No	Yes	Cisco - YACT - Cable SNR	
UBR7246-Device - SNR: Cable2/0-upstream1-Restelice 2 - Shkolla	20789	1 / 0	5 Minutes	No	Yes	Cisco - YACT - Cable SNR	
UBR7246-Device - SNR: Cable2/0-upstream2-Restelice 2 - Shkolla	20775	1 / 0	5 Minutes	No	Yes	Cisco - YACT - Cable SNR	
UBR7246-Device - SNR: Cable2/0-upstream3-Restelice 2 - Shkolla	20776	1 / 0	5 Minutes	No	Yes	Cisco - YACT - Cable SNR	
UBR7246-Device - SNR: Cable2/0-upstream3-Restelice 2 - Shkolla	20790	1 / 0	5 Minutes	No	Yes	Cisco - YACT - Cable SNR	
UBR7246-Device - SNR: Cable2/0-upstream4-Restelice 3 - Linja e re	20777	1 / 0	5 Minutes	No	Yes	Cisco - YACT - Cable SNR	
UBR7246-Device - SNR: Cable2/0-upstream5-Restelice 3 - Linja e re	20792	1 / 0	5 Minutes	No	Yes	Cisco - YACT - Cable SNR

**Comment by cigamit** [comment]
We need the resource XML as well as the template XML.  Thus far you have only updated the resource XML.

You should also run the following command and send the output to developers at cacti dot net.

`mysqldump cacti host_snmp_cache graph_local > debug_file.sql`

**Comment by fisnnik** [comment]
Hi,

Please find attached requested files, also i have sent by email db dump as requested.

Br,

[template.zip](https://github.com/Cacti/cacti/files/3201385/template.zip)

**Comment by cigamit** [comment]
Thanks for that, but you still have not included the resource XML.  You are only including the Template Exports, which is not what I have asked for.

**Comment by fisnnik** [comment]
Hi,
Please find attached template and resource file.

[new-template-resourcefile.zip](https://github.com/Cacti/cacti/files/3210860/new-template-resourcefile.zip)

**Comment by cigamit** [comment]
Okay, that resource XML file did the trick.  Learned something new about some 'very' old code today.  Update lib/data_query.php, and re-index.  Let me know if things are working as expected now.

**Comment by fisnnik** [comment]
I did update that file and still the same things are happening, also i dowonloaded all developing files of cacti and upgraded them still the same thing.

For the first time i indexed it created some graphs duplicate not all, then second time i indexed it created again same graphs and then i had Bad indexes.

Maybe i need to fix that xml file?

Here is part of log 

23/05/2019 18:56:47 - AUTOM8 NOTE: Graph Added - Device[UBR7246-device], Graph[UBR7246-device - SNR: Cable2/0-upstream0-Restelice 2 - Shkolla], DS[UBR7246-device - SNR: Cable2/0-upstream0-Restelice 2 - Shkolla] Graphs[UBR7246-device - SNR: Cable2/0-upstream0-Restelice 2 - Shkolla]
23/05/2019 18:56:47 - AUTOM8 NOTE: [PID: 2687] create_graph_node() Graph[UBR7246-device - SNR: Cable2/0-upstream0-Restelice 2 - Shkolla] Tree Item - Added - id: (20302)
23/05/2019 18:56:46 - AUTOM8 NOTE: Graph Added - Device[UBR7246-device], Graph[UBR7246-device - SNR: Cable2/0-upstream5-Restelice 3 - Linja e re], DS[UBR7246-device - SNR: Cable2/0-upstream5-Restelice 3 - Linja e re] Graphs[UBR7246-device - SNR: Cable2/0-upstream5-Restelice 3 - Linja e re]
23/05/2019 18:56:46 - AUTOM8 NOTE: [PID: 2687] create_graph_node() Graph[UBR7246-device - SNR: Cable2/0-upstream5-Restelice 3 - Linja e re] Tree Item - Added - id: (20301)
23/05/2019 18:56:45 - AUTOM8 NOTE: Graph Added - Device[UBR7246-device], Graph[UBR7246-device - SNR: Cable2/0-upstream4-Restelice 3 - Linja e re], DS[UBR7246-device - SNR: Cable2/0-upstream4-Restelice 3 - Linja e re] Graphs[UBR7246-device - SNR: Cable2/0-upstream4-Restelice 3 - Linja e re]
23/05/2019 18:56:45 - AUTOM8 NOTE: [PID: 2687] create_graph_node() Graph[UBR7246-device - SNR: Cable2/0-upstream4-Restelice 3 - Linja e re] Tree Item - Added - id: (20300)
23/05/2019 18:56:44 - AUTOM8 NOTE: Graph Added - Device[UBR7246-device], Graph[UBR7246-device - SNR: Cable2/0-upstream3-Restelice 2 - Shkolla], DS[UBR7246-device - SNR: Cable2/0-upstream3-Restelice 2 - Shkolla] Graphs[UBR7246-device - SNR: Cable2/0-upstream3-Restelice 2 - Shkolla]
23/05/2019 18:56:44 - AUTOM8 NOTE: [PID: 2687] create_graph_node() Graph[UBR7246-device - SNR: Cable2/0-upstream3-Restelice 2 - Shkolla] Tree Item - Added - id: (20299)
23/05/2019 18:56:43 - AUTOM8 NOTE: Graph Added - Device[UBR7246-device], Graph[UBR7246-device - SNR: Cable2/0-upstream2-Restelice 2 - Shkolla], DS[UBR7246-device - SNR: Cable2/0-upstream2-Restelice 2 - Shkolla] Graphs[UBR7246-device - SNR: Cable2/0-upstream2-Restelice 2 - Shkolla]
23/05/2019 18:56:43 - AUTOM8 NOTE: [PID: 2687] create_graph_node() Graph[UBR7246-device - SNR: Cable2/0-upstream2-Restelice 2 - Shkolla] Tree Item - Added - id: (20298)
23/05/2019 18:56:42 - POLLER: Poller[Main Poller] WARNING: You have 1 Devices with bad SNMP Indexes. Devices: Device[UBR7246-device] totalling 8 Data Sources. Please Either Re-Index, Delete or Disable these Data Sources.



23/05/2019 18:52:37 - AUTOM8 NOTE: Graph Added - Device[UBR7246-device], Graph[UBR7246-device - SNR: Cable1/0-upstream4-Restelice 2], DS[UBR7246-device - SNR: Cable1/0-upstream4-Restelice 2] Graphs[UBR7246-device - SNR: Cable1/0-upstream4-Restelice 2]
23/05/2019 18:52:37 - AUTOM8 NOTE: [PID: 1748] create_graph_node() Graph[UBR7246-device - SNR: Cable1/0-upstream4-Restelice 2] Tree Item - Added - id: (20281)
23/05/2019 18:52:36 - AUTOM8 NOTE: Graph Added - Device[UBR7246-device], Graph[UBR7246-device - SNR: Cable1/0-upstream4-Restelice 2], DS[UBR7246-device - SNR: Cable1/0-upstream4-Restelice 2] Graphs[UBR7246-device - SNR: Cable1/0-upstream4-Restelice 2]
23/05/2019 18:52:35 - AUTOM8 NOTE: [PID: 1748] create_graph_node() Graph[UBR7246-device - SNR: Cable1/0-upstream4-Restelice 2] Tree Item - Added - id: (20280)
23/05/2019 18:52:33 - AUTOM8 NOTE: Graph Added - Device[UBR7246-device], Graph[UBR7246-device - SNR: Cable1/0-upstream4-Restelice 2], DS[UBR7246-device - SNR: Cable1/0-upstream4-Restelice 2] Graphs[UBR7246-device - SNR: Cable1/0-upstream4-Restelice 2]
23/05/2019 18:52:33 - AUTOM8 NOTE: [PID: 1748] create_graph_node() Graph[UBR7246-device - SNR: Cable1/0-upstream4-Restelice 2] Tree Item - Added - id: (20279)
23/05/2019 18:52:32 - AUTOM8 NOTE: Graph Added - Device[UBR7246-device], Graph[UBR7246-device - SNR: Cable1/0-upstream4-Restelice 2], DS[UBR7246-device - SNR: Cable1/0-upstream4-Restelice 2] Graphs[UBR7246-device - SNR: Cable1/0-upstream4-Restelice 2]

**Comment by cigamit** [comment]
Okay, to get you out of hot water, do the following.  Edit the Resource XML file and add the interface/query row:

```xml
<index_order>docsIfSigQSNRIndex</index_order>
```

Then Re-Index, you should get some messages about the index changing, and from there, goto the Graphs page and see if you still have any 'Orphaned' Data Query Graphs associated with this Data Query.  If not, you 'should' be able to remove that one line again.  But might as well leave it there.

**Comment by fisnnik** [comment]
Yes this did the trick. I left that line there and now it is not creating duplicates and Bad indexes.
Old graphs will be deleted and recreated. But it is good to have a solution.
Thanks a lot. Have a good day.
