### ISSUE TITLE
Can not change from 5 min to 1 min Cron Interval. Will not save.

### ISSUE THREAD

**Issue by gllewellyn** [Cacti/cacti#2686]
Running cacti / spine 1.2.3 can not change from 5min to 1 min Cron Interval. Under Configuration/Poller/Cron Interval. Change from 5 to 1 min and click save and it does not save. After a few mins click on anything and it warns you it have not save.





**Comment by bmfmancini** [comment]
I am not able to replicate this in my LAB 

are you matching the poller time and the crontab to 1 minute?
try a different browser? maybe try incognito mode or something

**Comment by gllewellyn** [comment]
Tried firefox / IE & Google

Just never finishes the save. I can save any other change to the page. Crontab has already been updated to 1 min.
[cid:image001.png@01D50BCD.03AF9EE0]

When I try to move off page I get message below.

[cid:image002.png@01D50BCD.03AF9EE0]

**Comment by bmfmancini** [comment]
Are you selecting 1 Minute poller and 1 Minute cron ?
your images did not come through

**Comment by gllewellyn** [comment]
1 min cron

**Comment by netniV** [comment]
Can you post your images via a web browser rather than email as the context they contain is lost without them.

**Comment by cigamit** [comment]
Note that:
1) If you change the poller interval, that does not change any graphs.
2) If you change the poller interval to a system that is already collecting data, you have to ensure that you rebuild the poller cache afterwards, again, that will not change any graphs.
3) If you want to change the Data Source Profile for a Data Source, you can, but then you have to delete the RRDfiles as we don't make those changes for you.

**Comment by cigamit** [comment]
Can you please continue this discussion on the forums.  We should log a bug to better document the method to change the sampling/data collection frequency.
