### ISSUE TITLE
PHP errors on multiple fresh installs

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#2687]
Hello Everyone 

I am not sure if this is a bug but I am seeing the same PHP errors on multiple fresh installs of 1.2.3 and 1.2.4

I am wondering if there is something missing during my installations 
I see the ss_poller.php file there and all installs seem to be working just fine 

2019/05/15 12:53:04 - PHPSVR WARNING: Function does not exist  INC: 'ss_poller.php' FUNC: 'ss_boost_avg_size' PARMS: ''
--
2019/05/15 12:53:04 - PHPSVR WARNING: Function does not exist  INC: 'ss_poller.php' FUNC: 'ss_boost_timing' PARMS: ''
2019/05/15 12:53:04 - PHPSVR WARNING: Function does not exist  INC: 'ss_poller.php' FUNC: 'ss_boost_table' PARMS: ''
2019/05/15 12:53:04 - PHPSVR WARNING: Function does not exist  INC: 'ss_poller.php' FUNC: 'ss_boost_records' PARMS: ''
2019/05/15 12:53:04 - PHPSVR WARNING: Function does not exist  INC: 'ss_poller.php' FUNC: 'ss_boost_avg_size' PARMS: ''
2019/05/15 12:53:04 - PHPSVR WARNING: Function does not exist  INC: 'ss_poller.php' FUNC: 'ss_thold_time' PARMS: ''
2019/05/15 12:53:04 - PHPSVR WARNING: Function does not exist  INC: 'ss_poller.php' FUNC: 'ss_syslog_stats' PARMS: ''
2019/05/15 12:53:04 - PHPSVR WARNING: Function does not exist  INC: 'ss_poller.php' FUNC: 'ss_syslog_time' PARMS: ''
2019/05/15 12:53:04 - PHPSVR WARNING: Function does not exist  INC: 'ss_poller.php' FUNC: 'ss_syslog_stats' PARMS: ''
2019/05/15 12:53:03 - PHPSVR WARNING: Function does not exist  INC: 'ss_poller.php' FUNC: 'ss_boost_timing' PARMS: ''
2019/05/15 12:53:03 - PHPSVR WARNING: Function does not exist  INC: 'ss_poller.php' FUNC: 'ss_boost_table' PARMS: ''
2019/05/15 12:53:03 - PHPSVR WARNING: Function does not exist  INC: 'ss_poller.php' FUNC: 'ss_boost_records' PARMS: ''
2019/05/15 12:53:03 - PHPSVR WARNING: Function does not exist  INC: 'ss_poller.php' FUNC: 'ss_boost_avg_size' PARMS: ''
2019/05/15 12:53:03 - PHPSVR WARNING: Function does not exist  INC: 'ss_poller.php' FUNC: 'ss_thold_time' PARMS: ''
2019/05/15 12:53:03 - PHPSVR WARNING: Function does not exist  INC: 'ss_poller.php' FUNC: 'ss_syslog_stats' PARMS: ''
2019/05/15 12:53:03 - PHPSVR WARNING: Function does not exist  INC: 'ss_poller.php' FUNC: 'ss_syslog_time' PARMS: ''
2019/05/15 12:53:03 - PHPSVR WARNING: Function does not exist  INC: 'ss_poller.php' FUNC: 'ss_syslog_stats' PARMS: ''

**Comment by netniV** [comment]
I believe this was reported already if you search through the history of issues.

**Comment by bmfmancini** [comment]
OK thanks I will check

**Comment by cigamit** [comment]
This was an issue with our unpublished package plugin.  Can you please update the Cacti_Stats.xml.gz file from the latest develop and then re-run 'import_package.php --filename=...'
