### ISSUE TITLE
Increase length of Graph Item 'value' field to support pango-markup better

### ISSUE THREAD

**Issue by frontierliu** [Cacti/cacti#2688]
In case cacti 1.x support pango-markup text format, it is a good function to make cacti's graph text to have more color and other attributes. 
But when I create a gprint_preset for input a pango-markup format string, eg. "\<span foreground="blue" size="x-large"\>%8.2lf%s\</span\>", the text input box size limit to 40 chars, it is not enough for that pango-markup style string.  I  suggest increase the size limit to 100 chars, for better support pango-markup format string. 100 chars  fit to the database gprint_preset table's field definition, no need to change database table. I found that text input box size limit was define in include/global_form.php, a minor modify shoud be ok.
Just a suggestion, thanks for the  Cacti team's great work and I love it.

**Comment by netniV** [comment]
That does not sound like a massive increase but as it’s per field would lead to a longer maximum command line. Not sure if that is an issue more for Windows than Linux. 

Unless one of the team can see a problem with it, I would suggest making that change in the 1.3 branch so it can be properly tested.

**Comment by TheWitness** [comment]
Turned out to be a simple thing.  The database was already at 255 characters, so the only thing that needed to be changed was the form.

**Comment by netniV** [comment]
The issue was more with the length of the built up command line, not the database field.  By increasing to 255 per field, it can greatly increase the likelihood that the command line can exceed its limits.

**Comment by frontierliu** [comment]
Yes, in a graph that have many datasource items, It is possible exceed the limit of Windows system command line 8191 chars.  I think cacti can make a enchancement : when someone click  "Turn on Graph Debug Mode" , the command line display text also print the command line text total chars count, if  the count exceed 8191 in a windows system, show some warning messages.  That would be helpful.

**Comment by netniV** [comment]
Please create that as an enhancement request, I think it's not a bad plan. 👍

**Comment by TheWitness** [comment]
Yea, makes sense.  The best plan is that if you are using Windows, you need to come to the light side and use a real operating system, on that is designed from the beginning for web hosting.  I do like the idea of logging the command length (for windows users).

**Comment by frontierliu** [comment]
ok, I will create an enchancement request for it.

**Comment by frontierliu** [comment]
Pull request have been created, only update rrd.php in lines 2256, please check it. 
Now when someone  "Turn on Graph Debug Mode", it will display like follow:
![wx_20200404171709](https://user-images.githubusercontent.com/24820773/78451991-482b9880-76bb-11ea-8af7-6fbc65155ebd.png)

If the Cacti OS is Windows and the lengths > 8191，it will display a warning message like follow:
![wx20200404171551](https://user-images.githubusercontent.com/24820773/78452008-6abdb180-76bb-11ea-829c-8a11c7a8e827.png)

It will be helpful to debug some graph display issue about Windows system commandline lengths.
