### ISSUE TITLE
cacti graph not showing

### ISSUE THREAD

**Issue by scarface10** [Cacti/cacti#2690]
![image](https://user-images.githubusercontent.com/21038504/57833152-1f678f80-77d9-11e9-8c10-9415a5200b46.png)
****

**Comment by bmfmancini** [comment]
Hello 

These issues are normally one of the following 

1.) Check your cron entry 
2.) Check the permissions for you RRA folder 
3.)if using spine make sure your spine.conf file is setup properly
4.) Does the device show up ?

**Comment by scarface10** [comment]
Thanks for follow up 
my cron entry and rra permissions are  
![cron](https://user-images.githubusercontent.com/21038504/57902934-6f069380-788b-11e9-9cf7-f9970ffb5f8c.PNG)
![rra permissions](https://user-images.githubusercontent.com/21038504/57902939-74fc7480-788b-11e9-80c3-76847ce08125.PNG)

**Comment by scarface10** [comment]
Does this has something to do with spine ? I found these
![spine](https://user-images.githubusercontent.com/21038504/57904698-a5e0a780-7893-11e9-92f6-4e4d76cc236a.PNG)

**Comment by scarface10** [comment]
Installed my spine
![spine2](https://user-images.githubusercontent.com/21038504/57905340-ee996000-7895-11e9-8268-d899ac11a99d.PNG)

**Comment by scarface10** [comment]
So, i configured spine correctly, changed poller type to spine . It still wont work

**Comment by bmfmancini** [comment]
do you have snmpd  installed on the server ? 
does the localhost device show up ?

**Comment by bmfmancini** [comment]
you could try a reinstall I have a script that would help you make sure nothing is missed 

https://github.com/bmfmancini/cacti-install-wizard

**Comment by netniV** [comment]
Change the /dev/null in your cron entry to a valid log location and then see what output it contains

**Comment by tyit** [comment]
@bmfmancini 
This script is very good 
Can be used in a production environment?

**Comment by bmfmancini** [comment]
Sure it can

Its good for rapid deployment

Just tune what you need specific to your environment

Thanks for the comment!

**Comment by tyit** [comment]
@bmfmancini 
This  is very good
thank you very much

**Comment by cigamit** [comment]
So far, I have not seen any cacti.log output.

**Comment by bmfmancini** [comment]
Check the permissions of cacti.log make sure it's owned by www-data or
Apache depending on your system

**Comment by scarface10** [comment]
I found out following errors on cacti.log
[error.log](https://github.com/Cacti/cacti/files/3194657/error.log)

**Comment by scarface10** [comment]
I found following errors on cacti.log
![error](https://user-images.githubusercontent.com/21038504/57976406-ce38e500-79fe-11e9-9134-506a2e93ea9a.PNG)

**Comment by scarface10** [comment]
so i found the following errors in cacti.log
![a](https://user-images.githubusercontent.com/21038504/57977625-ff73de00-7a1b-11e9-87b7-116d8472c8de.PNG)

**Comment by scarface10** [comment]
here is screenshot of cacti error log

![a](https://user-images.githubusercontent.com/21038504/57977718-2fbc7c00-7a1e-11e9-8887-e44fdb9f444c.PNG)

**Comment by scarface10** [comment]
my poller settings are
![a](https://user-images.githubusercontent.com/21038504/57977740-b96c4980-7a1e-11e9-8e9d-1f8d221da8e4.PNG)

**Comment by scarface10** [comment]
![image](https://user-images.githubusercontent.com/21038504/57977744-dc96f900-7a1e-11e9-9c2d-1492b54d61b8.png)

**Comment by scarface10** [comment]
when i try to create device uptime graph. I still get
![image](https://user-images.githubusercontent.com/21038504/57977756-1ec03a80-7a1f-11e9-92bb-e0436da59177.png)

**Comment by scarface10** [comment]
> do you have snmpd installed on the server ?
> does the localhost device show up ?

yes localhost device show up & snmpd is installed on my server
![image](https://user-images.githubusercontent.com/21038504/57977819-04d32780-7a20-11e9-8a30-faeb09d426b8.png)

**Comment by netniV** [comment]
The /1 is unnecessary on your cron line and maybe be an issue, not sure if it would complain about that.  The asterisk alome means every 1.

**Comment by scarface10** [comment]
> The /1 is unnecessary on your cron line and maybe be an issue, not sure if it would complain about that. The asterisk alome means every 1.

Thanks! Yea got that. But it turns out my localhost graph is empty -nan. What might be the solution?

**Comment by cigamit** [comment]
Okay everyone.  I have a determined that this discussion should continue on the forums.  It's not a Cacti issue, but rather a user training issue, which belong on the forums.

However, with that said, I want to thank @scarface10, as he, through his wanderings with the interface exposed two minor bugs.  Thanks for that!

To put a final statement on where the issue stands now, you should do the following thing:

1) Check the ownership of files in the Cacti directory
2) Run the command `id apache`, if the apache user is found, then do the following:
  a) cd /usr/share/cacti
  b) chown -R --dereference apache:root *
3) Verify the poller.php is running through the cron log

Or simply install from ports and now try to hack it as bad as you have done.
