### ISSUE TITLE
Error when working with cacti

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#2694]
**Describe the bug**
An repetable error when working with cacti.

**To Reproduce**
1. Go to monitor plugin page.
2. Find host 1M59
3. Click on host icon.
4. Get an error (this error is only when we click on this host)

**Expected behavior**
No error.

**Screenshots**
![cacti_blad](https://user-images.githubusercontent.com/17087236/58015988-e0994880-7afc-11e9-8506-4f4b11ac8386.png)

- this is repetable on firefox/chrome, on windows and linux on different users, on different computers.

**Comment by bmfmancini** [comment]
What version of cacti and monitor are you using?

**Comment by interduo** [comment]
Cacti: 1.2.3
Monitor plugin is synchronized with git with master branch.

**Comment by interduo** [comment]
When I click on icon the link is https://cacti/graph_view.php?action=preview&reset=1&host_id=174.

**Comment by interduo** [comment]
But going to this link from other place gets no error so I don't know how to diagnose this.

**Comment by bmfmancini** [comment]
Interesting

OK let me see if I can reproduce it
What does your access.log for Apache look like? Maybe we can see what
action or error is being triggered

**Comment by bmfmancini** [comment]
Oh and this is just on a specific host?

**Comment by interduo** [comment]
```
172.20.2.42 - - [20/May/2019:15:50:37 +0200] "GET /plugins/monitor/monitor.php?action=ajax_status&size=monitor_medium&id=174 HTTP/1.1" 200 3947 "https://cacti/plugins/monitor/monitor.php?action=refresh&refresh=30&grouping=default&tree=-1&site=-1&template=-1&view=default&crit=0&size=monitor_medium&mute=false&rfilter=MU01OQ%3D%3D&status=-1" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/73.0.3683.103 Chrome/73.0.3683.103 Safari/537.36"
172.20.2.42 - - [20/May/2019:15:50:38 +0200] "GET /graph_view.php?action=preview&reset=1&host_id=174 HTTP/1.1" 200 9861 "https://cacti/plugins/monitor/monitor.php?action=refresh&refresh=30&grouping=default&tree=-1&site=-1&template=-1&view=default&crit=0&size=monitor_medium&mute=false&rfilter=MU01OQ%3D%3D&status=-1" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/73.0.3683.103 Chrome/73.0.3683.103 Safari/537.36"
172.20.2.42 - - [20/May/2019:15:50:39 +0200] "GET /graph_json.php?rra_id=0&local_graph_id=2323&graph_start=1558338638&graph_end=1558360238&graph_height=120&graph_width=500 HTTP/1.1" 200 26283 "https://cacti/graph_view.php?action=preview&reset=1&host_id=174" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/73.0.3683.103 Chrome/73.0.3683.103 Safari/537.36"
```

This is a log. The error log is empty.

> Oh and this is just on a specific host?

This is the only host whitch get this error.

**Comment by interduo** [comment]
**Found only in firebug:**
https://cacti/graph_view.php?action=preview&reset=1&host_id=174

`Unchecked runtime.lastError: The message port closed before a response was received.`

**Comment by interduo** [comment]
I don't know is it important thing - I use modern skin.

**Comment by bmfmancini** [comment]
Weird issue especially if it's only one device and the others are working
fine I suspect something went wrong maybe try disable monitoring on the
device and enable it again??

**Comment by interduo** [comment]
I did:
"Disable Monitor Device"
"Enable Monitor Device"

Add added more graphs (in this device I had only ping graph).
The issue still exists.

**Comment by TheWitness** [comment]
Looks to me that the URL is missing the hostname or ip address.

**Comment by interduo** [comment]
I found another device whitch gets an error.
`https://cacti/graph_view.php?action=preview&reset=1&host_id=183`

**Comment by interduo** [comment]
`rfilter=MU1hag%3D%3D`

For me this looks strange. Could It cause errors?

**Comment by interduo** [comment]
Yes that is that.

You need to type in filter something with digit in front and then some letters like:
`1MAJ` or `3M22` or this issue wouldn't happen.

%3D%3D is '=' in URL Encoding so probbably this is it.

**Comment by interduo** [comment]
%3D%3D is '=' in URL Encoding so probbably this is it.

**Comment by bmfmancini** [comment]
Good find!

**Comment by netniV** [comment]
If I remember rightly, the rfilter parameter is both url and base64 encoded.

**Comment by cigamit** [comment]
I've just pushed an update to monitor assuming that this was purely and escaping issue.  Please check it out.

**Comment by interduo** [comment]
It didn't help.

**Comment by cigamit** [comment]
Can you please upload a Screen2Gif of the transaction?

**Comment by interduo** [comment]
Yes, just give ma an email.

**Comment by cigamit** [comment]
developers at cacti dot net.

**Comment by interduo** [comment]
When I am filtering 3 chars `1M3` the error didn't exists. When I am filtering `1M35` or `1m35` the error exists. 

I did the screencast and sent it to mail.

I found an error in frontend (chrome console) error:
`monitor.php?action=change&refresh=60&grouping=tree&tree=-1&site=-1&template=-1&view=default&crit=0&size=monitor_medium&mute=false&rfilter=MW0z&status=-1:292 Uncaught (in promise) DOMException`

The error also appears when You mark at device and select EDIT.
It's only appears from Monitor.php.

**Comment by cigamit** [comment]
This will be fixed shortly.  It should have been in the monitor plugin location.  I'm closing here.  You should see the update in about 5 minutes.

**Comment by interduo** [comment]
What commit is this?
This one https://github.com/Cacti/plugin_monitor/commit/02a6a4662e9202f965825a32e74eeffbe770e66b ?

I did:
```
git fetch origin;
git checkout origin develop;
```

The issue still exists.
