### ISSUE TITLE
Change RRD Name ID to data source name in auto creation poller

### ISSUE THREAD

**Issue by dldiegouru** [Cacti/cacti#2695]
Hi, i want to ask to the forum if somebody could change the names of each rrd file. I dont want do it manualy, i want Cacti create it with different name with the slot/port (data source)
For example i want to do this change to identify the rrd file with the interface.
host-10z_ds_6354.rrd --> chantge to or auto create as host-10z_ds_21_1.rrd

This file is asociated with the data source host-10Z - Traffic - xgei_1/21/1
My main idea is to change in any Cacti configuration to obtain rrd files without id number, and with the position of the port in the poller.

Do you understand me?

This action will help me to colect 130 rrd files in the same device ( OLT Gpon Pon ports and Uplink) and identify each one.

In others ways i tried to search some report where it match data source name with rrd but i cant do it. I didnt find it :(

Thanks a lot for any tips or information.
Best regards.

Diego

**Comment by TheWitness** [comment]
Yea, this is a long shot.  I kind of know where you are going, but it's really a low priority in my opinion.

**Comment by TheWitness** [comment]
We have implemented a new method to allow segregation this way, which I think is more appropriate.  I would suggest a script if you want to do this programmatically.  The new patterns include:

`<path_rra>/host_id/snmp_query_id/local_data_id.rrd`
`<path_rra>/hash_id/host_id/local_data_id.rrd`
`<path_rrd>/hash_id/host_id/snmp_query_id/local_data_id.php`

So, I'm going to mark this one as not planned and close.  Sorry about that, but it's not a total loss.  Like I said, with some knowledge of the database, you can normalize the paths quite quickly.
