### ISSUE TITLE
CMDPHP: Poller[0] ERROR: A DB Exec Failed!, Error:'1062'

### ISSUE THREAD

**Issue by tyit** [Cacti/cacti#2697]
![image](https://user-images.githubusercontent.com/31933126/58084031-b757e580-7bec-11e9-904e-bbc0edca115e.png)

Hello, What caused this?  How to solve this error?

Cacti Version 0.8.8a
OS  Version  CentOS6.x
Apache/2.2.13
PHP 5.3.2
Mysql  5.1.56

**Comment by cigamit** [comment]
We are no longer supporting those versions.  But if you edit the file, and change 'insert into' to 'replace into', that will fix this problem.

**Comment by cigamit** [comment]
In the future, you should ask questions on unsupported versions on the Cacti forums first before coming here.
