### ISSUE TITLE
PHP Notice: MIB_Cache Error after update

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#270]
2017-02-06 08:25:54 - CMDPHP PHP ERROR NOTICE Backtrace: (/poller.php: 710 snmpagent_poller_bottom)(/lib/snmpagent.php: 354 update)(/lib/mib_cache.php: 363 CactiErrorHandler)(/lib/functions.php: 4238 cacti_debug_backtrace)
2017-02-06 08:25:54 - ERROR PHP NOTICE: Undefined index: .1.3.6.1.4.1.23925.2.9.1.6.727 in file: /var/www/html/cacti/lib/mib_cache.php on line: 363

**Comment by pautiina** [comment]
I also have this error:
```
2017-02-06 10:00:19 - ERROR PHP NOTICE: Undefined index: .1.3.6.1.4.1.23925.2.9.1.6.477 in file: /var/www/cacti/lib/mib_cache.php  on line: 363
2017-02-06 10:00:19 - CMDPHP PHP ERROR NOTICE Backtrace: (/poller.php: 710 snmpagent_poller_bottom)(/lib/snmpagent.php: 354 update)(/lib/mib_cache.php: 363 CactiErrorHandler)(/lib/functions.php: 4238 cacti_debug_backtrace)
```

**Comment by browniebraun** [comment]
Update library mib_cache.php (/lib/mib_cache.php) to the latest git version. Order of arguments was unfortunately twisted. 

Regards
-Andi

**Comment by interduo** [comment]
git pull -a 
And It did not found anything.

**Comment by pautiina** [comment]
@browniebraun I have last update
line 363 have:
`                                                $sql[] = '(' . db_qstr($values[$column_params['oid']]) . ', ' . db_qstr($column_params['name']) . ')';`

**Comment by interduo** [comment]
OK 
You need also to rebuild cache.

**Comment by pautiina** [comment]
@interduo  I rebuild "Poller cahce" and "SNMPAgent Cache". I tried twice, but the error persists

**Comment by pautiina** [comment]
I rolled back 4e4a142 commit and error disappeared.

**Comment by interduo** [comment]
After Rebuild Poller Cache the error disapperared in my host.
Maybe You did not wait for next poll ?

**Comment by pautiina** [comment]
@interduo For reliability I TRUNCATE TABLE `snmpagent_cache`  and rebuild cache. Wait a minute 10 - and then write the result.

**Comment by pautiina** [comment]
@interduo Error present. Can you show the structure of your table. I used a clean install Cacti. Maybe if you used the update that is the difference.

**Comment by interduo** [comment]
The Error is present.

**Comment by pautiina** [comment]
If rolled back 4e4a142 commit and error disappeared.

**Comment by interduo** [comment]
I also do:
git reset --soft d87fa4751c21d3c625ee083f300ac16faac41d46

**Comment by interduo** [comment]
Even I git reset the error is present in logs :/

**Comment by SoNix21** [comment]
same thing on my side, i did an @Git download@, updated my webroot, and now i get this error too:

`017-02-06 11:30:08 - CMDPHP PHP ERROR NOTICE Backtrace: (C:\Cacti\Apache24\htdocs\Cacti\poller.php: 598 snmpagent_poller_bottom)(C:\Cacti\Apache24\htdocs\Cacti\lib\snmpagent.php: 354 update)(C:\Cacti\Apache24\htdocs\Cacti\lib\mib_cache.php: 363 CactiErrorHandler)(C:\Cacti\Apache24\htdocs\Cacti\lib\functions.php: 4238 cacti_debug_backtrace)`

-> Here is my SQL Dump ;
CREATE TABLE IF NOT EXISTS `snmpagent_cache` (
		`oid` varchar(255) NOT NULL,
		`name` varchar(255) NOT NULL,
		`mib` varchar(255) NOT NULL,
		`type` varchar(255) NOT NULL DEFAULT '',
		`otype` varchar(255) NOT NULL DEFAULT '',
		`kind` varchar(255) NOT NULL DEFAULT '',
		`max-access` varchar(255) NOT NULL DEFAULT 'not-accessible',
		`value` varchar(255) NOT NULL DEFAULT '',
		`description` varchar(5000) NOT NULL DEFAULT '',
		PRIMARY KEY (`oid`),
		KEY `name` (`name`),
		KEY `mib` (`mib`))settings
		COMMENT='SNMP MIB CACHE';

**Comment by cigamit** [comment]
So, I'm fixing this right now.

**Comment by cigamit** [comment]
This is resolved.  Update your mib_cache.php and then from Utilities Rebuild the SNMP Agent Cache.
