### ISSUE TITLE
[Feature Request] Allow for addition of code snippets after <head>

### ISSUE THREAD

**Issue by lux4rd0** [Cacti/cacti#2700]
**Is your feature request related to a problem? Please describe.**

I use HTML/Javascript snippets to manage end user monitoring performance of this application. It requires manually changing:

```
/include/top_general_header.php
/include/top_graph_header.php
/include/top_header.php
```

each time Cacti is patched or upgraded or I need to change the HTML/Javascript snippet.

**Describe the solution you'd like**

Provide a snippet include file either from the database or another type of framework so files do not need to be edited.

**Describe alternatives you've considered**

Tried using External Links - but need to be placed in the HTML below the `<head>` - not as an iframe/tab link (and not just on the console - but on the graph pages - or every page).

**Additional context**
Really was hoping that the framework for the external pages might work - but it's not a page - it's Javascript that I'm looking to embed.

**Comment by TheWitness** [comment]
You can write a small plugin that uses the page_head hook.  The page_head hook allows you to inject content into the page or every page.
