### ISSUE TITLE
Usability: minor issue:  Graphs-->Preview: 'Graphs' filter value should be multiple of 'Columns'

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#2705]
**Describe the bug**
Generally, 'Graphs' filter value should be multiple of 'Columns' filter value

**To Reproduce**
1. Make sure graph number is more than 4
2. Navigate to Graphs-->Preview
3. Select 'Columns' as '3'
4. Select 'Graphs' as '4'
5. See graph pages equal or greater than 2. But right-bottom area is not filled by graphs. Detail ref screenshot below

**Expected behavior**
Reset 'Graphs' to multiple of 'Columns' when changed

**Screenshots**
![image](https://user-images.githubusercontent.com/17589018/58318549-8f65bd80-7e4a-11e9-942f-61de8af98673.png)

**Comment by TheWitness** [comment]
I don't really think there is any value in this request.  So, I'll close.  You can never predict this as it can change depending on the filter settings.
