### ISSUE TITLE
[Cacti 1.2.1] Realtime graph not working

### ISSUE THREAD

**Issue by criteron** [Cacti/cacti#2706]
When i open the real-time graph popup window, no image is displayed (with Chrome, IE or Edge). 

When i inspect the "img" tag in the HTML source code, there is only the "data:image/png;base64" with no base64 image encoded string.

When i inspect the result of HTTP query to graph_realtime.php?action=countdown there is nothing in the "data" json field.

At first i thought it was the permissions, but "realtime graphs" option is checked for the user and it's group. 

I need help to resolve this issue,

Thanks

**Comment by cigamit** [comment]
You must ensure that the apache account has read-write-execute to the cache directory.

```console
chown -R apache:root /var/www/html/cacti/cache
chmod -R 755 /var/www/html/cacti/cache
```

This path may differ by installation and by user setting.  Depending on the OS version, the owner my be different than apache, for example www-run.

**Comment by criteron** [comment]
I checked the rights of the cache directory and it's sub-directories. The apache user has the RWX permissions on it.

**Comment by netniV** [comment]
Be sure that apache is the user the your OS is using.  You haven't given much information on the setup or versions you have.

**Comment by criteron** [comment]
The Cacti partition was full.
