### ISSUE TITLE
cacti 1.2.3 Associated Data Queries can't display.

### ISSUE THREAD

**Issue by akai1983** [Cacti/cacti#2709]
**Describe the bug**
Some graph like SNMP - Interface Statistics 、SNMP - Get Mounted Partitions can not display on 
Create > New Graphs 

**To Reproduce**
fresh install cacti 1.2.3 and use private window on centos 7
 Create > New Graphs
You can not select SNMP - Interface Statistics

**Screenshots**
![image](https://user-images.githubusercontent.com/51112119/58461019-5470cc00-8161-11e9-9dba-432f8679016b.png)

devices edit page can selected
![image](https://user-images.githubusercontent.com/51112119/58461935-618eba80-8163-11e9-81f9-62ac54ed2156.png)

**Desktop (please complete the following information):**
 - OS: windows 7 x64
 - Browser chrome latest
 - 

**server:**
 - OS: centos 7.4
 - cacti 1.2.3

**Comment by cigamit** [comment]
That is the expected behavior.  You can not add Data Queries from the Graphs New interface.
