### ISSUE TITLE
cacti 1.2.3 SNMP - Interface Statistics Graphs can't display

### ISSUE THREAD

**Issue by akai1983** [Cacti/cacti#2710]
**Describe the bug**
cacti 1.2.3 SNMP - Interface Statistics Graphs can't display

**To Reproduce**
Management > Devices > add > add a device use snmp v2
Device Template -> Generic SNMP Device
SNMP - Interface Statistics  can display. on Cacti 1.2.2 fresh install

BUT
SNMP - Interface Statistics  can NOT display. on Cacti 1.2.3 fresh install

**Screenshots**

![image](https://user-images.githubusercontent.com/51112119/58525734-6012d000-81ff-11e9-8a96-54ee64ff5eec.png)
![image](https://user-images.githubusercontent.com/51112119/58525752-6acd6500-81ff-11e9-9109-ce0ed4d0b96e.png)

![image](https://user-images.githubusercontent.com/51112119/58525784-86387000-81ff-11e9-9fac-ca83349add5c.png)
![image](https://user-images.githubusercontent.com/51112119/58525812-a5370200-81ff-11e9-8b40-7d825035bc17.png)

Desktop (please complete the following information):

OS: windows 7 x64
Browser chrome latest

server:
OS: centos 7.4
cacti 1.2.3  fresh install
cacti 1.2.2 fresh install

**Comment by cigamit** [comment]
Please verify that you have actually created interface graphs.

**Comment by cigamit** [comment]
No response.
