### ISSUE TITLE
Enhance logging capabilities to allow for compressed formats

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/cacti#2711]
1. The current cacti log is generated every day.   In order to avoid cacti log taking a lot of space, better to support cacti log auto compress by user setting.

2. Go to system utilities - Log Administration page, check File drop down list, it can not only show cacti.log, but also show files named begin with cacti.log.xxx that I created, thus the gz file can not display -- Failed. 

![Screen Shot 2019-05-29 at 11 26 13 AM](https://user-images.githubusercontent.com/47589910/58527365-e382f000-8204-11e9-9874-9034c4c068b9.png)

Cacti 1.2.3 
FF
rhel7 x64

**Comment by ddb4github** [comment]
Under cacti/clog.php,  File dropdown list only valid log file name that is endwith '.log'

So, I prefer replace 'cacti/utilities.php?action=view_logfile' implementation with 'cacti/clog.php'

**Comment by netniV** [comment]
I agree that the bug fix should be to make the utilities have the same limitations as the clog.  The enhancement would be the handling of compressed formats.

**Comment by cigamit** [comment]
We should block the *.gz extension for now.

**Comment by TheWitness** [comment]
Once we implement the new logging interface we're going to expect that these logs will be forwarded to a central login server so I don't think there's really reason to do this one. 

Making the executive decision to close.
