### ISSUE TITLE
"ERROR: Problems parsing Multi SNMP OID!" after changed device description

### ISSUE THREAD

**Issue by maxstech** [Cacti/cacti#2715]
cacti 121
Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-43-generic x86_64)
PHP 7.0.32-0ubuntu0.16.04.1

if I change the description in General Device Options, the logs are full of errors:
![error cacti max oid](https://user-images.githubusercontent.com/47040342/58703195-84fa7500-83b0-11e9-9c23-83235e48eb2c.jpg)

initially I get the equipment, the rules of automation. 
But there are situations when device name changes on the switch. 
Then I go and change it manually - General Device Options -- change Description and get these errors. 
This happens with any switch, whose description is changing manually.

**Comment by cigamit** [comment]
Please update to 1.2.4, and then re-index your devices.  After that, see if the error still occurs.

**Comment by maxstech** [comment]
With new equipment there is no problem after the upgrade. I close it, thanks.
