### ISSUE TITLE
[feature request] Add intergration with twillo/SMS gateway 

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#2716]
Hey Everyone 

Something that would be nice to see would be native integration with a SMS gateway service like twillo and thold or cacti 

I current have accomplished this but via and script and thold 

the general idea would be to have another field in the device view that would hold the number to text 

Number : <input type="text" name="SMS Number"> in the device view form 
Twillo Number : <input type="text" name="Twillo from Number">
Services such as twillo can be called using simple curl commands

curl -XPOST https://api.twilio.com/2010-04-01/Accounts/ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/Messages.json \
--data-urlencode "To=+1<SMS Number>" \
--data-urlencode "From=+1<Twillo from Number>" \
--data-urlencode "Body=<THOLD Variables>" \
-u 'ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:your_auth_token'

Right now I have a bash script that accepts a few variables from thold and then sends out the SMS that way  but it would be cool if this was integrated natively 

Thanks as always!

**Comment by netniV** [comment]
This is really a thold request and I believe the decision taken by the main developer of that plugin went for using scripts so that any service could be integrated.

**Comment by bmfmancini** [comment]
Thanks @netniV 

I will post this to te THOLD team 

Thanks !

**Comment by TheWitness** [comment]
After the thold 1.2.4 release, this whole notification topic will be covered.
