### ISSUE TITLE
Question: The newest .mo files were committed into locales/po, correct?

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#2717]
.mo file name:
```list
zh-CN.mo
fr-FR.mo
es-ES.mo
```
impacted Cacti project:
```list
cacti
plugin_audit
plugin_cycle
plugin_flowview
plugin_gexport
plugin_hmib
plugin_mactrack
plugin_maint
plugin_mikrotik
plugin_monitor
plugin_reportit
plugin_syslog
plugin_thold
plugin_webseer
```

**Comment by netniV** [comment]
The translation service appears to be placing these in the wrong folder.  I will have to investigate and see if I can correct this today.

**Comment by netniV** [comment]
I moved the translations for the core prior to the release yesterday but we will continue to monitor it. The plugins still need to be all checked.

**Comment by netniV** [comment]
As of today, all plugins and core should now be saving to the correct locations.  I ran a script today to correct them across all plugins.  As such, when the next release is made these should be correct.
