### ISSUE TITLE
Empty graphs being created automatically but we can't delete them

### ISSUE THREAD

**Issue by stormonts** [Cacti/cacti#2719]
Every time we add a new device to Cacti, graphs are created via automation rules including an "Empty graph" that can't be deleted.  All of our automation rules show matching devices and objects, so we can't tell what specifically is creating these "empty graphs" or why.  When we select them and then either click on Delete or re-apply suggested names, we get the message shown below.  The "Empty graphs" can be seen in the background of the image.

![image](https://user-images.githubusercontent.com/25824323/59035670-c8833200-883b-11e9-953d-a78684f19e47.png)

**Comment by cigamit** [comment]
Need more information, you may have to send a database dump to developers at cacti dot net.

**Comment by cigamit** [comment]
Note also that 1.2.4 has been released.

**Comment by stormonts** [comment]
Problem still exists in 1.2.4.  Whole DB dump is 120 MB; guessing only part of that is needed for analysis.

**Comment by netniV** [comment]
Is that compressed?

**Comment by stormonts** [comment]
No, I'm an idiot and can't read.  Zipped it is 14 meg.  Where should I send it?

**Comment by netniV** [comment]
developers@cacti.net and reference the issue number so we know which issue the email relates to.

**Comment by cigamit** [comment]
@stormonts, did @netniV help you on this one yet?

**Comment by cigamit** [comment]
I've taken a look at this and am about to commit a patch.  I'll need you to manually remove the file in the graph_local table.

**Comment by cigamit** [comment]
Update made, you need to run the following query to remove the bad graphs.

```sql
DELETE gl 
FROM graph_local AS gl 
LEFT JOIN graph_templates_graph AS gtg 
ON gl.id = gtg.local_graph_id 
WHERE gtg.local_graph_id IS NULL;
```

**Comment by ddb4github** [comment]
How about diff below, then we can delete them by WebUI:
```diff
--- graphs.php.orig     2019-06-26 21:47:52.001432337 +0800
+++ graphs.php  2019-06-26 21:48:26.221159679 +0800
@@ -1990,7 +1990,7 @@
        $sql_order = get_order_string();
        $sql_limit = ' LIMIT ' . ($rows*(get_request_var('page')-1)) . ',' . $rows;

-       $graph_list = db_fetch_assoc("SELECT gtg.id, gtg.local_graph_id, gtg.height, gtg.width,
+       $graph_list = db_fetch_assoc("SELECT gtg.id, gl.id AS local_graph_id, gtg.height, gtg.width,
                gtg.title_cache, gt.name, gl.host_id,
                IF(gl.graph_template_id=0, 0, IF(gl.snmp_query_id=0, 2, 1)) AS graph_source
                FROM graph_local AS gl
```

# Before Fixing
![image](https://user-images.githubusercontent.com/17589018/60185937-68414800-985d-11e9-9655-fc0b3731819f.png)

# After Fixing
![image](https://user-images.githubusercontent.com/17589018/60185596-c883ba00-985c-11e9-97d8-55637aaf3a02.png)
