### ISSUE TITLE
After Upgrade - HTTP 302 Error

### ISSUE THREAD

**Issue by DavidLiedke** [Cacti/cacti#272]
After the upgrade from 0.8.8h to 1.0.0 and 1.0.1 i get a HTTP 302 Error in the Browser.

The database upgrade has no errors. 

Apache Access Log:
![kitty_portable_2017-02-06_10-31-43](https://cloud.githubusercontent.com/assets/25581728/22641854/bbd53aca-ec58-11e6-98e9-86b7e313d06a.png)

In the Apache Error Log is no entry.

**Comment by browniebraun** [comment]
HTTP errors will return a status code of 4xx and 5xx. 
Status code 302 indicates a temporary redirect.

Regards
-Andi

**Comment by DavidLiedke** [comment]
I can´t find any mistake in the configuration. 

1. Download and extract cacti-1.0.1 to /cactistable/
2. edit the include/config.php
3. import the cacti.sql (from the tar package).
4. run the installer
5. I can use cacti without any problems

If i use my old database:
3. import my old (0.8.8h) database
4. run the installer (upgrade) without any problems.
5. i get the redirect errors. 

If i delete the content of the database i come back to the installer.

**Comment by cigamit** [comment]
Can you please edit you /etc/php.ini and set the error_log = /tmp/php_errors.txt, then restart apache, and rerun the upgrade.  Also, what authentication method are you using?  Lastly, you can also upgrade from the command line:

1) Stop apache
2) Upgrade the system image (cacti)
3) Change directories to the cli directory
4) Run 'upgrade_database.php',
5) Start Apache,
6) Close your browser, open it goto the Cacti login page, and press F5 to reload all Javascript package
7) Login.

Please let us know your authentication method though.  That will be important to reproduce this case.

**Comment by DavidLiedke** [comment]
Thanks i will do this tomorrow and give you an feedback asap.

I use the WebAuth authentication method.

**Comment by cigamit** [comment]
The problem may have something to do with your auth method, which running the CLI will make more convenient.  Either way, as soon as you get a login prompt, it'll be important to refresh your browser cache using F5 (most browsers) or Ctrl+R (chome)

**Comment by cigamit** [comment]
Also, a user reported today that the cookie_domain can cause issues on upgrade.  Please check that settings in php.ini.

**Comment by DavidLiedke** [comment]
I test it now with the cli and the browser. Both upgrades doesn´t work. 

On the cli:
cli/analyze_database.php --> All tables Successful

I see in the "session" table that cacti start a session for the user.  

**php.ini:**
; The domain for which the cookie is valid.
; http://php.net/session.cookie-domain
session.cookie_domain =

This was the default setting from the operating system.

----
At the moment is my php_errors.txt empty. I am looking for the reason why.

**Comment by cigamit** [comment]
You ran 'analyze_database.php' and not 'upgrade_database.php'.  Try using the correct command.

**Comment by DavidLiedke** [comment]
No I run the correct command. 
At first I run the upgrade_database.php with no errors. After that I run the analyze_database.php to check the database (no errors). 

Sorry for the confusion.

**Comment by cigamit** [comment]
Can you check you config.php and see if $cacti_db_session is set to true, and set to false?

**Comment by DavidLiedke** [comment]
/* save sessions to a database for load balancing */

$cacti_db_session = true;

**Comment by cigamit** [comment]
I'm changing the $cacti_db_session = false as the default.

**Comment by DavidLiedke** [comment]
Now it works :)

$cacti_db_session = false

**Comment by cigamit** [comment]
Thank goodness.  I've changed the default for others as well.  Thanks for hanging in there.
