### ISSUE TITLE
Calls to _db_replace() are not consistent resulting in warnings

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#2722]
**Describe the bug**
1. function `_db_replace` has argv `$has_autoinc`, but never use it
2. function sql_save call `_db_replace` with a valid param `$has_autoinc`, default is '`true`
3. function db_replace call `db_replace` without the 5th argv `$has_autoinc`

**Comment by TheWitness** [comment]
Jing, is this critical?

**Comment by ddb4github** [comment]
> Jing, is this critical?

Just a quick code validating.

Might impact function sql_save, need more testing from Monday

**Comment by netniV** [comment]
The validation is correct.  The has_autoinc parameter is never used but was introduced as part of 47de436a96bc18ed928c5061342bc53b1ce40ca0 which was a backport apparently.

We should correct the function definition and/or make sure the calls are aligned.
