### ISSUE TITLE
Undefined variable message raised by push_out_host() in lib/utility.php

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#2723]
**Describe the bug**
Undefined variable '$template_fields'.

I guess it should be $data_template_fields

For some fix-able(by me) issues, I'll summarize and log another ticket with diff

**Comment by netniV** [comment]
No, I believe the name is correct, the problem is that it isn't properly imitialised at the start as an array before it attempts to populate it after the `!issset()` check
