### ISSUE TITLE
Error processing hex-lines for space delimited hex strings into mac addresses

### ISSUE THREAD

**Issue by PonomarenkoVladimir** [Cacti/cacti#2733]
**Describe the bug**
  Error processing hex-lines (MAC-address)

**To Reproduce**
   Have a Script Query XML File
   The output format of the field “spMeshLinkNodeId”: **hex**
![изображение](https://user-images.githubusercontent.com/26214543/59409463-a10f0500-8df9-11e9-9baf-16956bcd9534.png)
 
**Steps**
1. Select "Management" -> "Devices" -> My Device
2. Select "Associated Data Queries"
3. Select "Verbose Query"
![изображение](https://user-images.githubusercontent.com/26214543/59409688-2a263c00-8dfa-11e9-94ad-02b099712ed8.png)

**Result:** :   no print MAC-address of the equipment (field ”spMeshLinkNodeId”)
![изображение](https://user-images.githubusercontent.com/26214543/59409742-4f1aaf00-8dfa-11e9-9c33-f966c6380811.png)

**Expected behavior**
I fixed the error in the file **./lib/snmp.php** 
**Result:**
![изображение](https://user-images.githubusercontent.com/26214543/59409817-812c1100-8dfa-11e9-8ac3-3b18889d3dad.png)

Because I do not know the logic of the program, the text of the correction is not attached.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Chrome

**Comment by cigamit** [comment]
Please upload your updated lib/snmp.php.  Thanks!!

**Comment by cigamit** [comment]
I have attempted to validate this one using core Cacti 1.2.4/1.2.5 and can not.  Can you please also update to develop or 1.2.4 after you upload your modified lib/snmp.php file?

**Comment by cigamit** [comment]
Oh, I was not able to validate using the ifInterfaces HwAddress walk.  You might also want to upload the output of this command:

```shell
snmpwalk -c yourcommunity -v2c -Ox youhostname theOIDinQuestion
```

Also, what happens when you change type from 'get' to 'walk'?

**Comment by PonomarenkoVladimir** [comment]
My updated lib/snmp.php file for version Cacti 1.2.4:
[snmp.php.tar.gz](https://github.com/Cacti/cacti/files/3318838/snmp.php.tar.gz)
My changes are marked "**********"

Command output:
snmpwalk -c public -v2c -Ox 172.17.2.186 .1.3.6.1.4.1.15319.2.2.1.4.0
iso.3.6.1.4.1.15319.2.2.1.4.0 = Hex-STRING: 00 0A DB 08 9F BF 

**Also, what happens when you change type from 'get' to 'walk'?**
**Result:**
Click to show Data Query output for field 'spMeshLinkNodeId
Executing script query '/usr/bin/php -q /usr/share/cacti-1.2.4/scripts/query_skypilot_link_stats.php '172.17.2.186' '7' '2:161:2000:2:20:public::::::' 'query' 'node_id''Found item [spMeshLinkNodeId=''] index: 0 
 
The result has not changed.

**Comment by cigamit** [comment]
Yea, those changes looked mostly good.  Committing momentarily.  Then I would like you to test it.

**Comment by cigamit** [comment]
Okay, it's uploaded.  Please test.

**Comment by PonomarenkoVladimir** [comment]
Works.
