### ISSUE TITLE
Suggestion Cacti-1.2.4: Displaying non-English label names on graphs.

### ISSUE THREAD

**Issue by PonomarenkoVladimir** [Cacti/cacti#2734]
**Describe the bug**
Non-English labels are not displayed correctly on graphs

**To Reproduce**
Have a Template graphics: labels on Russian language
![изображение](https://user-images.githubusercontent.com/26214543/59410884-51cad380-8dfd-11e9-92ac-cfdff5aa5958.png)
**Result:**    labels are not displayed
![изображение](https://user-images.githubusercontent.com/26214543/59410953-7b83fa80-8dfd-11e9-975f-23ee198bded7.png)

**Suggestion:**
Correct the file **./lib/rrd.php**: line 1167, function **rrdtool_function_graph**
Add a line to display labels in Russian (or other language):
       **setlocale (LC_CTYPE, ‘ru_RU.UTF8’);**
**Result:**
![изображение](https://user-images.githubusercontent.com/26214543/59411253-2399c380-8dfe-11e9-8c89-3def900192e5.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Chrome

**Comment by cigamit** [comment]
Please update include/global_languages.php from the develop branch and verify that this is fixed that way.

**Comment by PonomarenkoVladimir** [comment]
Works. Thank!
