### ISSUE TITLE
Set cache rebuild process indicator for the Cacti UI

### ISSUE THREAD

**Issue by PonomarenkoVladimir** [Cacti/cacti#2738]
**Is your feature request related to a problem? Please describe.**
When I start the process of rebuilding cache poller or SNMPAgent cache, I do not see the process start, which is why I can click the mouse several times. Perhaps this may lead to a repeated launch of the cache rebuilding process.

**Describe the solution you'd like**
I ask you to set an indicator of the cache restructuring process.
![image](https://user-images.githubusercontent.com/26214543/59476674-37dccf80-8e95-11e9-81cb-3392322c8cd7.png)

**Comment by TheWitness** [comment]
Might want to bump this one up.  Putting back in the pipeline.

**Comment by TheWitness** [comment]
@PonomarenkoVladimir, I only did this on the Rebuild Poller Cache option.  How long does the SNMP cache rebuild take for you?  It should be blocking.
