### ISSUE TITLE
the plugin i18n is not work

### ISSUE THREAD

**Issue by zhangjian420** [Cacti/cacti#2739]
**Describe the bug**
I am from China ，I am not very good at English。
version: 1.2.4
file: included/global_languages.php line:134
`if (file_exists($config['base_path'] . '/plugins/' . $plugin . '/locales/LC_MESSAGES/' . $lang2locale[$cacti_locale]['filename'] . '.mo')) {`
modify：
`if (!file_exists($config['base_path'] . '/plugins/' . $plugin . '/locales/LC_MESSAGES/' . $lang2locale[$cacti_locale]['filename'] . '.mo')) {`

**Comment by netniV** [comment]
It should not be changed as it is correct from what I can see. Can you describe more why you believe that it is a problem ?

**Comment by zhangjian420** [comment]
> It should not be changed as it is correct from what I can see. Can you describe more why you believe that it is a problem ?
When I was debugging, I found out 'included/global_languages.php' line 134 and 136 is the same condition。
so I added debug code at line 139，like this:
`
print_r($path2catalogue);
`
Get the following result：
`
/var/www/html/cacti/locales/LC_MESSAGES/zh-CN.mo
/var/www/html/cacti/locales/LC_MESSAGES/zh-CN.mo
/var/www/html/cacti/locales/LC_MESSAGES/zh-CN.mo
`
So I made a change。it works well。
I have installed two plugins，Thold and Monitor。You can try the code above。

My English is very poor, I hope you can understand

**Comment by zhangjian420** [comment]
@netniV 
When I was debugging, I found out 'included/global_languages.php' line 134 and 136 is the same condition。
so I added debug code at line 139，like this:
`print_r($path2catalogue);`
Get the following result：
`/var/www/html/cacti/locales/LC_MESSAGES/zh-CN.mo /var/www/html/cacti/locales/LC_MESSAGES/zh-CN.mo /var/www/html/cacti/locales/LC_MESSAGES/zh-CN.mo`
So I made a change。it works well。
I have installed two plugins，Thold and Monitor。You can try the code above。

My English is very poor, I hope you can understand

**Comment by zhangjian420** [comment]
@netniV I found a new problem again.When something like "[]" appears in the UI interface。
and the i18n methods is not work。
`
__('Graph Management [ All Devices ]')
`
it is not work when you change locales.

**Comment by cigamit** [comment]
I really don't see an issue here other than we currently have a problem with plugins not locating the *.mo files in the correct location.

**Comment by cigamit** [comment]
Going to go ahead and close this as I've performed a code review and see nothing out of the ordinary.
