### ISSUE TITLE
Allow Realtime Graph Popup Mode

### ISSUE THREAD

**Issue by mitcham** [Cacti/cacti#274]
I noticed that since the realtime plugin has been integrated it now displays the graph inline rather than opening another small window, is it possible to add this as an option?

**Comment by cigamit** [comment]
That has been a feature that has been requested before.  I think we can do it.  We thought the new feature to realtime + 20 graphs in a single view would have been more compelling though.  Guess not ;)

**Comment by interduo** [comment]
It would be also very nice to have external link to realtime graph and could include this into some other site without login to cacti.

**Comment by cigamit** [comment]
Interduo, can you log that separately?

**Comment by cigamit** [comment]
Correct

**Comment by hiddenicon** [comment]
@cigamit It'd be nice to have the option for a pop-out for realtime. We sometimes take graphs from different tree folders to pop-out and watch at the same time. When it's inline, we have to create a separate tree folder to put both graphs into to do realtime. Example would be internet connections from two different locations. They are in different tree folders, but want to watch them at the same time in realtime.

**Comment by cigamit** [comment]
This issue will be resolved in Cacti 1.1.37.
