### ISSUE TITLE
http error 500 on weathermaps cacti

### ISSUE THREAD

**Issue by adeprima97** [Cacti/cacti#2740]
Hi all,
I am having a problem about weathermap in Cacti. when I try to add a weathermaps error message suddenly appears "This page isn’t working 10.14.3.48 is currently unable to handle this request.
HTTP ERROR 500 "

http://10.14.3.48/plugins/weathermap/weathermap-cacti-plugin-editor.php?action=nothing&mapname=ICON.conf

log error

Fatal PHP error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 4376 bytes) in /usr/cacti-0.8.8h/plugins/weathermap/lib/WeatherMap.functions.php on line 1938
06/13/2019 03:52:28 PM - WEATHERMAP: Poller [0] WARNING: [Map 87] ICON.conf: Target /usr/cacti-0.8.8h/rra/jabar-bandungutara-r7606-npe-01_traffic_in_150. rrd doesn't exist. Is it a file? [WMRRD06]
06/13/2019 03:52:28 PM - WEATHERMAP: Poller [0] WARNING: [Map 87] ICON.conf: ReadData: LINK node00622_copy1y-node00622_copy1y_copy, target: /usr/cacti-0.8.8h/rra/jabar- bandungutara-r7606-npe-01_traffic_in_150.rrd on config line 1381 of /usr/cacti-0.8.8h/plugins/weathermap/configs/ICON.conf had no valid data, according to WeatherMapDataSource_rrd
06/13/2019 03:52:28 PM - WEATHERMAP: Poller [0] WARNING: [Map 87] ICON.conf: ReadData: LINK node06737_copy_copy_copy-node00622_copy_copy_copy_copy_copy, target: /usr/cacti-0.8.8h/rra/jatim- waru-r7606-npe-01_traffic_in_180.rrd on config line 1540 of /usr/cacti-0.8.8h/plugins/weathermap/configs/ICON.conf had no valid data, according to WeatherMapDataSource_rrd
06/13/2019 03:52:28 PM - WEATHERMAP: Poller [0] WARNING: [Map 87] ICON.conf: NewColourFromPercent: Clipped 113.090348464% to 100% for item node02922-node00622_copy_copy [WMWARN33]
06/13/2019 03:52:28 PM - WEATHERMAP: Poller [0] WARNING: [Map 87] ICON.conf: ReadData: LINK node00q_copy-node02631, target: /usr/cacti-0.8.8h/rra/sbs- bukitsiguntang-r7606-npe-01_traffic_in_130.rrd on config line 2075 of /usr/cacti-0.8.8h/plugins/weathermap/configs/ICON.conf had no valid data, according to WeatherMapDataSource_rrd
06/13/2019 03:52:28 PM - WEATHERMAP: Poller [0] WARNING: [Map 87] ICON.conf: NewColourFromPercent: Clipped 160.07713681846% to 100% for items node05437-node00q_copy [WMWARN33]
06/13/2019 03:52:29 PM - WEATHERMAP: Poller [0] WARNING: [Map 87] ICON.conf: ReadData: LINK node08715-node07941, target: /usr/cacti-0.8.8h/rra/rit- gi_parigi-me3600-upe-01_traffic_in_1106.rrd on config line 2637 of /usr/cacti-0.8.8h/plugins/weathermap/configs/ICON.conf had no valid data, according to WeatherMapDataSource_rrd

how do you deal with this troubleshoot? can anyone help ... please

PHP 5.3.3 (cli) (built: Mar 22 2017 12:27:09)
php weathermap 0.98

**Comment by xmacan** [comment]
Try to edit php.ini file and change memory_limit from 128M to 256M and restart web server.

**Comment by netniV** [comment]
This should really be raised on the Weathermaps repo that Howard Jones maintains since it relates to his plugin.

**Comment by adeprima97** [comment]
Thank you very much. It works hihihi

Pada tanggal Sen, 17 Jun 2019 04.00, Mark Brugnoli-Vinten <
notifications@github.com> menulis:
