### ISSUE TITLE
Resolve a number of QA issues in various files

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#2741]
**Describe the bug**
1.  rrdcleaner.php:344: Undefined variable '$width'.
     Maybe ;100%'
2. managers.php:860: Undefined variable '$manager_id'.
3. lib/poller.php:1354: Undefined variable '$remote_poller_id'.
4. graphs.php:741: Undefined variable '$action'.
5. data_templates.php:153: Undefined variable '$data_template_rrd_id'.
     Maybe "get_filter_request_var('data_template_rrd_id')"
6. data_templates.php:153: Undefined variable '$data_template_id'.
          Maybe "get_filter_request_var('data_template_id')"
7.  data_debug.php:938: Undefined variable '$host'.

****
**To Reproduce**
Review all source code.

**Comment by cigamit** [comment]
Great work @ddb4github
