### ISSUE TITLE
1.2.4 Tree search size not resizable 

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#2745]
Hello Everyone 

I am seeing an issue where if you have a node with a long name the search and tree view justify to the right but you can't resize it 

![image](https://user-images.githubusercontent.com/13388748/59859040-0b6bfc00-934a-11e9-89db-8958aa47f825.png)

It would be nice to be able to resize this view as it can take up a lot of screen space 
seeing this using the Modern theme 

I have tried on Firefox,IE,Chrome  and still see this issue 

Let me know if you need any more info!
Thanks as always !

**Comment by netniV** [comment]
This has been raised before and is open as an enhancement request.

https://github.com/Cacti/cacti/issues/1518
