### ISSUE TITLE
Graphics coming out of the graphical menu are slower than graphics coming out of the tree menu.

### ISSUE THREAD

**Issue by zhangjian420** [Cacti/cacti#2746]
**Describe the bug**
When I create a graphic ，i click follow the path :
**step 1：Management-Graphs-Click the graphic i just created。I found that the graph has no data yet.
step2： i put the graphic in the tree，and click top menu “Graphs”，Data appear，like：
please pay attention to the time of my screenshot **
![1](https://user-images.githubusercontent.com/293321/59862869-270cec00-93b6-11e9-8c5c-d368e684635f.jpg)
**then Back to step1，like：**
![2](https://user-images.githubusercontent.com/293321/59862880-2b390980-93b6-11e9-843f-1fe59aede781.jpg)
**After 1 minute，like：**
![3](https://user-images.githubusercontent.com/293321/59862892-33914480-93b6-11e9-9183-776e7c9c66ab.jpg)
**After 2 minute，like：**
![4](https://user-images.githubusercontent.com/293321/59862962-5facc580-93b6-11e9-8be2-67e515c3aaac.jpg)
**After about 10 minutes, data appears，like：**
![6](https://user-images.githubusercontent.com/293321/59864774-2a09db80-93ba-11e9-9c51-a84249f547d7.jpg)

How can I display them synchronously?

 - Browser Google Chrome
 - Version 1.2.4
 - Poller inteval 1 min
 - crontab */1 * * * * /usr/bin/php /var/www/html/cacti/poller.php > /dev/null 2>&1

**Comment by netniV** [comment]
That is by design as far as I recall.

**Comment by cigamit** [comment]
I'm not even sure what we are looking at here....  If image caching is enabled, it would be by design.
