### ISSUE TITLE
Provide better sorting in Console >Management > Graphs

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#2747]
In the Console->Management->Graphs function currently only the 'Graph Name', 'ID' and 'Size' are sortable. I don't see why the 'Source Type' and 'Source Name' wouldn't be sortable as well. Thanks!

**Comment by cigamit** [comment]
Recording this.  Right now, I don't believe we are joining on these fields, but it would be possible.  Sorting on the ID will be easier than on the text I think.  Some of this has a salability impact.

**Comment by TheWitness** [comment]
This is resolved now.
