### ISSUE TITLE
When the path_php_binary location is invalid, this should be notified during installation when checking modules

### ISSUE THREAD

**Issue by cjwbath** [Cacti/cacti#2748]
I saw an issue similar to #2665 where the installer showed none of the required PHP modules were installed for the CLI. They definitely were, according to _php -m_ and manual execution of _cli_check.php_.

I was trying to install against a database imported from another server and it turns out the error was caused because the PHP binary was now in a different location to that specified by the _path_php_binary_ value in the database's _settings_ table. Because of the way `utility_php_extensions()` shells out then silences errors from `json_decode`, if there was an error running PHP we just get an empty string there. Once all the rest of the extension array processing is then done, it just looks to the GUI like none of the modules is installed for the CLI.

Once I did `UPDATE SETTINGS set value = '/usr/bin/php' WHERE name = 'path_php_binary';` in the DB all was good. I suggest try to check the validity of that configuration setting (presence of the PHP CLI binary) earlier in the install process.

**Comment by cigamit** [comment]
Any thoughts on this on @netniV?

**Comment by netniV** [comment]
Yes, I’m updating the code to check that the returned string is actually non-blank otherwise show a new message to report this possibility of an issue.  It will require manually updating the path unless we can the order of the installation steps and that can’t happen till 1.3
