### ISSUE TITLE
The line in the graph appears ghost

### ISSUE THREAD

**Issue by zhangjian420** [Cacti/cacti#2755]
**To Reproduce**
1. Go to Top Menu Graphs
2. in the Graph Filters panel Choose 'Last Day' or 'Last 2 Days' of Presets ，The display is correct, the screenshot is as follows：
![1](https://user-images.githubusercontent.com/293321/59989355-4f743f00-9671-11e9-8be2-6ed77ee0eb5c.jpg)
3. Choose 'Last 3 Days' of Presets ，Line ghosting， the screenshot is as follows：
![2](https://user-images.githubusercontent.com/293321/59989399-8185a100-9671-11e9-9777-2a0421c9cb25.jpg)
Google Chrome  and  Cacti-1.2.4
Is it my problem? tks

**Comment by cigamit** [comment]
This is a normal artifact.  As the graph ages, you will see those lines begin to separate as the max values start to pull away from the average values.  If you review the Graph Template you will see that there is a line for both the inbound and output graph using the MAX Consolidation Function (CF).
