### ISSUE TITLE
Install: blank page after clicking "next", 1.0.1

### ISSUE THREAD

**Issue by Jerrison777** [Cacti/cacti#276]
Hi there,
just grabbed the latest release and tried to get past the install script.
It´s a new install, no upgrade and I´m using the latest MariaDB release and PHP 5.5.30.
After I imported cacti.sql I´ll hit the first page of the  "Cacti Installation Wizard".
However, checking the box and clicking "next" always results in a blank page
with no content. I tried IE, Chrome, FF and different OSes as well. No "noscript" or the likes was
used
I can "cheat" into the next page by using "index.php?step=2" and so on and the pages
all render fine albeit I´m not sure if all settings are written to the DB. Step 2 shows all in the
green (I adjusted the new DB to fit the requirements).
After step 5 I can hit next and the version field get´s updated from new_install to 1.0.1
but here again: I´ll land on the authentication page, enter the default creds and get a blank
page next.

I enabled php errors but didn´t find anything nor in the apache error or access logs. After the POST message there´s just no more returns from the webserver.

Not really sure what else I can try or if I´m missing something here. Oh, all the files and folders
got "chowned" to my "apache" user and for debugging purposes I 777ed all as well.

Cheers for bringing out this release, very excited to get it up and running soon :)
Jerri

**Comment by cigamit** [comment]
Please edit your /etc/php.ini and set error_log = /tmp/php_errors.txt and then restart Apache, and retry the upgrade and post what you find there.  There is some JavaScript on that page.  Please make sure that you don't have any legacy plugins installed on your system as many of them are incompatible (you can simply tgz them and delete the directories).  You can only restore those plugins after they have been certified to work on Cacti 1.0.  We did this intentionally as users have been including many of the JavaScript modules that are in use in Cacti 1.0, and they would break Cacti more often than not.  So, we make you put some extra working into getting your plugins migrated.

**Comment by Jerrison777** [comment]
Thanks for replieing. As stated above, this is a fresh install and no upgrade so no additional plugins have been used. There are no error log entries in the php_errors-logfile, I checked for that so I suspect some
issues with the java script but just can´t figure out what it is. Debugging mode in the browsers don´t hint at anything going wrong (besides IE ofc which I never use anyway).

**Comment by cigamit** [comment]
Well that's interesting.  Can you post your Technical Support PHP Section.  I'm looking for the $_SERVER variables section.  We need to get rid of that IP_ADDRESS warning.  If you could please also obfuscate the data if it includes anything personally identifiable.  If the $_SERVER variables include domain names, just replace with my.domain.com.

**Comment by Jerrison777** [comment]
Will do as soon as I get cacti installed for once. But the main issue seems to me to be memcached.
I´ll need some time to set up another host with the latest mariaDB then I´ll get to the Technical Support section :)
However, the IP_ADDRESS warning is NOT the cause of the blank page -> this seems to be php session related.

**Comment by cigamit** [comment]
If you are using PHP 7.1 it is not supported yet.  Please confirm.

**Comment by Jerrison777** [comment]
As stated above, Im using PHP 5.5.30 :)

On Feb 8, 2017 12:32 AM, "Jimmy Conner" <notifications@github.com> wrote:

If you are using PHP 7.1 it is not supported yet. Please confirm.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Cacti/cacti/issues/276#issuecomment-278179526>, or mute
the thread

**Comment by cigamit** [comment]
Ope, sorry about that.  Can you edit your config.php and set $cacti_db_session to false if it is set to true?

**Comment by cigamit** [comment]
No feedback.
