### ISSUE TITLE
Table does not exist

### ISSUE THREAD

**Issue by zhangjian420** [Cacti/cacti#2761]
When I create a new graphic，There was a very serious mistake。
![1](https://user-images.githubusercontent.com/293321/60079710-0ef3ee80-9761-11e9-8dc3-bcd9cbcb7835.jpg)

The name of the table that does not exist is called `graph_template`，Should be called `graph_templates` ,I don't know if there are other places like this. 1.2.5

**Comment by cigamit** [comment]
Thanks for testing.  Fixing this shortly.

**Comment by cigamit** [comment]
Resolved.  No changelog.  It's between releases.
