### ISSUE TITLE
Can not create aggregate graph with unknown RRD tools error 

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/cacti#2762]
1) Go to graph page 
2) Choose a graph, for example: Local Linux Machine - Load Average 
3) Click create aggregate graph, then do not change any setting, then click create. 
4) Go to preview tab, error exist. 
![Screen Shot 2019-06-25 at 4 55 48 PM](https://user-images.githubusercontent.com/47589910/60084671-8aa66900-976a-11e9-9b25-6276fc42e552.png)
![Screen Shot 2019-06-25 at 4 56 04 PM](https://user-images.githubusercontent.com/47589910/60084675-8c702c80-976a-11e9-8704-1228a281e418.png)
![Screen Shot 2019-06-25 at 4 56 36 PM](https://user-images.githubusercontent.com/47589910/60084676-8da15980-976a-11e9-94d7-d8fa3ff51b5a.png)

cacti 1.2.4
FF
rhel7 x64

**Comment by cigamit** [comment]
This is a fairly minor issue.

**Comment by cigamit** [comment]
Resolved.  Will not show the preview tab if there are no items selected.
