### ISSUE TITLE
Undefined variable causes notice when migrating aggregate graphs

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/cacti#2763]
log error:
2019/06/25 17:34:24 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[61]:form_actions(), /aggregate_graphs.php[523]:CactiErrorHandler())
2019/06/25 17:34:24 - ERROR PHP NOTICE: Undefined variable: save_html in file: /opt/IBM/cacti/aggregate_graphs.php on line: 523 

![Screen Shot 2019-06-25 at 5 39 59 PM](https://user-images.githubusercontent.com/47589910/60087797-4ae28000-9770-11e9-8553-c2e5fb375a3e.png)

cacti 1.2.4 
FF
rhel7 x64

**Comment by cigamit** [comment]
Resolved.  No changelog.  Minor non-functional issue.
