### ISSUE TITLE
Cascading selection of available graphics

### ISSUE THREAD

**Issue by zhangjian420** [Cacti/cacti#2765]
I added a new feature. When editing the tree, select the available sites and cascade to select available devices and available graphics, select available devices and cascade to select available graphics. Because I have a lot of devices on different sites, searching is not the best option.

The attachment is my modified file, based on version 1.2.4。
[tree.zip](https://github.com/Cacti/cacti/files/3330498/tree.zip)

----------------------------Dividing line-----------------------
I also found another problem, creating a flow graph with the graphic type "In/Out Bits64", but the data in the generated graph is up to 35G. I found that it is due to the "U" for No Maximum of traffic_in and traffic_out in the graphics data source. 

So I modified the "U" for No Maximum of the data source traffic_in and traffic_out to 100G, but the maximum data in the graphics can still only reach 35G, because the rrd file has been generated.

 I deleted the rrd file again. After re-generation, the graphics data exceeded 35G.

So I modified the code. When I created the graph based on the template that does not automatically scale and the --upper-limit is 100G, at the same time I also modified the "U" for No Maximum of the data source traffic_in and traffic_out to 100G, and executed it with exec_shell:
`/usr/local/bin/rrdtool tune /var/www/html/cacti/rra/4/121.rrd --maximum traffic_in:100000000000
/usr/local/bin/rrdtool tune /var/www/html/cacti/rra/4/121.rrd --maximum traffic_out:100000000000`
Because there are a lot of changes, the code is not uploaded.

My English is coming to Google Translate，I hope that the translation is not too bad.

**Comment by netniV** [comment]
You could still provide a pull request for this.  If you clone the repository, you can use `git checkout release/1.2.4` and that would be the 1.2.4 released code, you can then create a branch and copy over your changes, commit them and push them up before creating a pull request.

**Comment by cigamit** [comment]
@zhangjian420, agree with @netniV.  A pull request would be great.  That way you can also have recognition for your contributions.  Let us know right away.  We are planning a release this weekend.

**Comment by cigamit** [comment]
Okay, I've reviewed the code and found it to be acceptable.  There is a downside that if you select multiple nodes, you only match one of them, but I'm okay with that for the moment.
