### ISSUE TITLE
Modifying Aggregate Templates not cascading to Graph

### ISSUE THREAD

**Issue by zhangjian420** [Cacti/cacti#2766]
After the aggregation template is successfully created, modify the Auto Scale in the Scaling Options to false. The modification does not take effect.

It seems that modifying all the Graph Configuration options does not take effect, you can try！

Google Chrome 
1.4.2

**Comment by netniV** [comment]
The version number seems wrong, also do you have any errors appear in your logs when this occurs?

**Comment by cigamit** [comment]
Also, can you explain where the modification is based.  Is it on the source Graphs, or Graph Templates, or the Aggregate Template?  If it's the underlying Graph or Graph Template, that would be the expected behavior.  So, please clarify.

**Comment by zhangjian420** [comment]
@netniV ， @cigamit 
Sorry, the version number is wrong, it should be 1.2.4
The problem comes from the aggregation template. After the aggregation template is successfully created, modifying the parameters of the Graph Configuration in the aggregation template does not work.
The first image is a successful creation of an aggregate template:
![1](https://user-images.githubusercontent.com/293321/60279991-a78e9800-9934-11e9-9036-4c3b2905de45.jpg)

The second image is to modify the parameters of the Graph Configuration in the aggregate template:
![2](https://user-images.githubusercontent.com/293321/60280015-acebe280-9934-11e9-84e5-36232c5a77be.jpg)

**Comment by cigamit** [comment]
Oh, that is interesting.

**Comment by cigamit** [comment]
This issue is  resolved now.  Template should have those items disabled until such time as you flip the toggle.
