### ISSUE TITLE
Plugins should be temporarily disabled if a required plugin is also disabled

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#2767]
As subject.
Once a major plugin is disabled, its data will not be updated. e.g. thold.log
Other plugin will always use a expired/invalid date

---

- Add checks to hooks to see if heirarchy fully enabled
- Add option for plugin to decide if heirachy check should be made
- Add check when manually disabling to see if dependent plugins should be disabled (block disable if a non-disabled dependant found?)

**Comment by netniV** [comment]
This is a good idea that will need testing if it has a production impact by disabling the plugins.  In truth, I think we can't truly disable dependant plugins, but we should check if the heirarchy is disabled at any point...

If we do implement this it will be in the next major release.

**Comment by netniV** [comment]
Part of me does think this is plugin dependant though because, for example, thold becoming disabled doesn't remove the data, merely no longer updates it so monitor would still work it would just be out of date.

**Comment by ddb4github** [comment]
Or call a predefined function(like '<pluginname>_dependency_disaable') or pre-register hook to notify each related plugin "your dependency is disabled, do sth. by your self" 😆

**Comment by netniV** [comment]
Something like that 👍

**Comment by netniV** [comment]
So I added three other thoughts as a list to your original post for ease of reference.

**Comment by cigamit** [comment]
Yea, this has been bugging me too.  But too lazy to open a bug ;)
