### ISSUE TITLE
Aggregate Graphs showing wrong row count

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#2768]
**Describe the bug**
Any new-style aggregate graphs which use a |query_| in the text_format end up being statically defined instead of dynamic. 

**To Reproduce**
Update a data query, and observe that the old value of the |query_| is still present in the aggregate graph, instead of the new queried value. 

**Expected behavior**
When an object in a data query is updated, any references using |query_| should also follow suit.

**Additional context**
I think I mentioned this in one of my other reports, so if we want to handle it there, that would be ok too. Sorry for the double-post in that case.

**Comment by cigamit** [comment]
Hmm, @eschoeller did I mention that last weekend was a long one.  So, the replacements should happen dynamically at render time.  If they are not, then we have another bug.

Do me a favor, cut a new database dump, and then let me know which aggregate graph id it impacts.  I'll take a look over the weekend.

**Comment by eschoeller** [comment]
Sent you a new DB dump. Take a look at new-style aggregate graph ID 67220.

**Comment by cigamit** [comment]
Okay, there were two issues here.  The first was the row count, and the second was the updating of the values.  I think the second has already been fixed in another bug fix.  Just update to develop.  And now the second, row count, is fixed.

**Comment by eschoeller** [comment]
OK. So I tried to update to develop earlier today. And it was super rough. So I backed out. I'm back to applying patches manually, which I generally seem to have more success with. I need to improve my git skills. 
The row count issue is fixed.
I cannot verify the updating values issue, I can't really seem to find which fix would have addressed this. But I can wait for the official 1.2.5
