### ISSUE TITLE
Reapply suggested names does not update with "empty" replacement variables.

### ISSUE THREAD

**Issue by grotnicki** [Cacti/cacti#2769]
**Describe the bug**
Not sure if bug or intended functionality. Reapply suggested names on both graphs and data sources does not update names if query replacement variable field does not exist. Same results are from using both UI and CLI.

**Expected behavior**
Reapply names with placeholders "|query_...| in places where those variables are not avaialble. 

**Screenshots**
First Screen: Current and after "reapplying suggested names"
![image](https://user-images.githubusercontent.com/42233676/60245557-221bd100-98bd-11e9-9d33-88b2ee3d19d2.png)

Second screen: Prompt to continue reapplying name. Note the |query_ifDescr| and |query_ifAlias| placeholders.
![image](https://user-images.githubusercontent.com/42233676/60245655-52636f80-98bd-11e9-8fbe-9123e97ade1a.png)

**Additional context**
While this "bug" seems being functionality working as intended, I've used this mechanic to find and delete graphs from non-operational ports by reapplying names and looking for graphs with |query_ifDescr| in graph names.

**Comment by cigamit** [comment]
First of all, which version of Cacti?  Second, if less than 1.2.4, please first update to develop, and then re-index your device.  We are planning an update this weekend.  So, timing is critical.

**Comment by grotnicki** [comment]
Cacti Version | 1.2.4

**Comment by cigamit** [comment]
Perfect, updating to develop should be pretty safe then.

**Comment by grotnicki** [comment]
Cacti updated to develop device has been reindexed, same results as earlier.

**Comment by cigamit** [comment]
Perform a verbose query, and then post the full contents of the output.  At the top of the debug window, you will see a copy to clipboard.  Use that to copy the data.  Past the results into this ticket.

**Comment by grotnicki** [comment]
[query_v.txt](https://github.com/Cacti/cacti/files/3337958/query_v.txt)

This device have about 100000 items from 10000 interfaces, so the query verbose might not be helpful.

Just to make it clearer those interfaces which do not update their graph name are no longer present on the device, and this is the main reason I don't believe it's a bug. In fact being able to update names of interfaces that are no longer present might've been a bug which was fixed.

**Comment by grotnicki** [comment]
Including logs from CLI for both DS and Graph rename. As you can see for DS it says that the rename is done with |query_...| but in the end the DS name isn't changed at all.

Also here's a gif showing that in the prompt to continue reapplying the names should be changed leaving placeholders where variables should be (if they were present)
![reaplly suggested names](https://user-images.githubusercontent.com/42233676/60327627-ac7f3600-998c-11e9-82ff-06bc40e35150.gif)


Also in graph edit mode, the names are shown with placeholders:
![image](https://user-images.githubusercontent.com/42233676/60327940-77bfae80-998d-11e9-95d8-a455881e1f4e.png)

It seems that for some reason field "title_cache" in table "graph_templates_graph" isn't updated (might be the same in data_template_data with field name_cache)

**Comment by cigamit** [comment]
So, a few things:

1) From the Graphs page, select filter 'orphans' and see if these guys show up.
2) If they don't show up, capture the 'graph id', make a note of the numbers
3) Enter the mysql prompt and look for the graphs.  Here the query:

```sql
SELECT * FROM graph_local WHERE id IN(1,2,3,4);
```

Replacing 1,2,3,4 with the Graph ID's.

4) Note the index numbers in the snmp_index column.  If the snmp_indexes are blank, let me know.  If not, continue to the next step:

5) Run the following query using the snmp_indexes the host_id and the snmp_query_id from the above output.

```sql
SELECT * FROM host_snmp_query WHERE snmp_query_id = X AND host_id = Y AND snmp_index IN(1,2,3,4);
```

Replacing 1,2,3,4 with the snmp_indexes from the graph_local table.

Post your findings.  I suspect what is happening is this.

1) You have a snmp table where the IP addresses move from snmp index to snmp index depending on when people connect.
2) As such you see the graph names change from time to time
3) If there is no matching index, then the graph naming breaks as well
4) Prior to Cacti 1.2.4, these graph names would break.  Moving forward, they will continue to hold the legacy name.

**Comment by grotnicki** [comment]
> From the Graphs page, select filter 'orphans' and see if these guys show up.

Yes they're orphaned. Could've checked this feature earlier.

> Note the index numbers in the snmp_index column. If the snmp_indexes are blank, let me know. If not, continue to the next step:

Just to be sure I've checked those graphs and their snmp_index are empty (which I guess makes them orphaned)

> Prior to Cacti 1.2.4, these graph names would break. Moving forward, they will continue to hold the legacy name.

And this is propably it. And it concludes that what I'm experiencing is that Cacti is working as intended.  It invalidates my approach to identify elements that are no longer present on devices and I'll need to tackle this problem from my side.

This brings me to a question is there an easy way to identify orphaned graphs from CLI?

**Comment by cigamit** [comment]
Here is what I would suggest, if these are like VPN connections, and you have the username, or something that is unique, you can do the following:

1) Make that 'unique' column the primary sort column.  Could be the IP Address, you would add that to the XML file in the:

```xml
<index_order>ifMyUniqueColumn</index_order>
```

Change the re-index type to index count changed, if you have an OID that returns the number of indexes, add that to the 

``xml
<oid_num_indexes>.1.2.3.4....</oid_num_indexes>
```

Then, re-index.  Now, since the XML column ifMyUniqueColumn, will always be unique, and you have a way to detect changes in the number of indexes, Cacti will follow those index changes moving forward every time your re-index.  However, if that re-index takes a long time, you might want to just work half broken.

**Comment by cigamit** [comment]
I'm going to close this, but we can still keep discussing if you have questions.
