### ISSUE TITLE
Add tip support to html_header() and html_header_checkbox()

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#2772]
**Describe the bug**
html_header_sort_checkbox  and html_header_sort support  'tooltip'
html_header_checkbox, html_header do not support

Anyway, I can use html_header_sort_checkbox  and html_header_sort with all column 'nosort' settings.

**Comment by cigamit** [comment]
This is now resolved.

**Comment by ddb4github** [comment]
> This is now resolved.

thank your quick response 🤣
