### ISSUE TITLE
Aggregate graphic legend is displayed incorrectly

### ISSUE THREAD

**Issue by zhangjian420** [Cacti/cacti#2773]
Step1: When creating an aggregated graphic through the graphic list function menu
![1](https://user-images.githubusercontent.com/293321/60281318-5207ba80-9937-11e9-97ea-1cd9888f04b1.jpg)
Step2: Select Aggregate Graph Settings as follows:
![2](https://user-images.githubusercontent.com/293321/60281344-5df37c80-9937-11e9-8a03-de17aba099cb.jpg)
Step3: Select the preview tab, no graph legend is generated:
![3](https://user-images.githubusercontent.com/293321/60281359-677ce480-9937-11e9-82b1-697be69f6b5a.jpg)
Step4: Modify the Prefix for GPRINT Totals value to total, and generate the graph as follows:
![4](https://user-images.githubusercontent.com/293321/60281374-6cda2f00-9937-11e9-9b6b-9b5dd3abcd80.jpg)
![7](https://user-images.githubusercontent.com/293321/60281706-01dd2800-9938-11e9-91d9-76829c038b60.jpg)

Question: If there is a Prefix, the Prefix value should be added before the legend. The generated legend should look like this:
![6](https://user-images.githubusercontent.com/293321/60281551-ad39ad00-9937-11e9-98fe-8dcba3d9229a.jpg)

**Comment by cigamit** [comment]
I'm going to close this.  I would suggest that this is a user error.  You should place hard returns on your Graph Template and then re-order your Graph Template to place the MAX values at the end or in a place that works better for the Template.  So, basically, this is not an issue.
