### ISSUE TITLE
Division by zero in files in negative case

### ISSUE THREAD

**Issue by YongBoLiu** [Cacti/cacti#2776]
**Describe the bug**
 
2019/06/28 09:54:46 - ERROR PHP WARNING in Plugin 'xxx': Division by zero in file: 
html_reports.php

**To Reproduce**

**Expected behavior**

Need check the value before divide read_config_option('poller_interval') as below,

xxx  / read_config_option('poller_interval');

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

[yboliu@oc8636837557 cacti]$ grep -R '\/[[:blank:]]*read_config_option' .
./lib/html_reports.php:		$report['mailtime'] = date(reports_date_time_format(), floor(time() / read_config_option('poller_interval')) * read_config_option('poller_interval'));
./lib/snmpagent.php:		'cactiStatsPollerUtilization'         => round($data[0]/read_config_option('poller_interval', true)*100, 10)

**Comment by YongBoLiu** [comment]
Instead of divide read_config_option('poller_interval')  directly, We'd better to check the value before divide it , something like below to avoid error in negative case.

+	$temp_poller_interval = read_config_option('poller_interval');
+	if ($temp_poller_interval) {
+		$xxx = 3600 / $temp_poller_interval;
+	} else {
+		$xxx = 3600 / 300;
+	}

**Comment by netniV** [comment]
tbh, there is a larger issue in that the value of the setting stable could be anything including text.  However, the poller interval should always be set and positive.

**Comment by cigamit** [comment]
This has been a problem for a while that for some reason, the read_config_option('') will not return the 'default' value if set in the settings array.  The is a read_default_config_option('') that should return the value, but it does not.  The reason is likely that how do you handle the difference between a default that is blank, and a database entry that is not there.

**Comment by cigamit** [comment]
I setup a test case this morning by creating the following script, then dropping the row from the settings table.  In my case, the poller_interval setting was set to 60 in the database, I removed the row, and then ran the following script:

```php
<?php
include('./include/cli_check.php');

$poller_interval = read_config_option('poller_interval');
print 'The poller interval is ' . $poller_interval . PHP_EOL;
exit;
```

The result of running that script with the settings table empty resulted in 300, which is as expected.  I also change the initial include to global.php, and ran from the website with the same result.

So, @YongBoLiu, how were you able to cause this to happen.  We need to know how you were able to make this break?

**Comment by cigamit** [comment]
No feedback.
