### ISSUE TITLE
Archive old versions of Templates when importing new ones

### ISSUE THREAD

**Issue by sam-san91** [Cacti/cacti#278]
Hi,
I have an enhancement request :)
Everytime I import a template from a forum or whatever it will overwrite my existing templates if included.
This is really annoying as I have to check first whether a template will be overwritten and backup those first.
I was thinking of a small checkbox to decide if any existing templates can be overwritten or not. At least a small warning would be really great :-)

**Comment by cigamit** [comment]
When you import into 1.0, you have the option to 'preview'.  Are you asking to simply backup the old before importing the new, or is preview enough?  We should allow a certain amount of 'rollback'.  But that is a project that will take a while.  Please clarify.

**Comment by sam-san91** [comment]
Yes, that would show me what it would do, but it will still overwrite my existing templates.
In some cases I don't want that to happen, so an option would be nice to disable updating/overwriting at all for an import. It could still give me an output that it would like to overwrite something but couldn't because of this option. Sort of a "protect from overwrite/update" checkbox.
I hope that I could express myself correctly. :)

Btw: I really like 1.0, good job!

**Comment by cigamit** [comment]
I could see under 'preview' we could conceivably add check boxes against everything that was to change.  But it might cause more problems.  For now, I'll just mark this as an enhancement request.  Thanks for your feedback and testing.  We will be doing weekly releases for a while until things are totally bug free.  You may see a few of the outstanding planned features dovetailed in from time to time.  This request is not at the top of the list at the moment.

**Comment by reubenfarrelly** [comment]
For the purposes of this being an enhancement request - this would be of interest to me as well.  I also noticed when I imported some templates (and selected to include dependencies) that it made a wide variety of changes to other templates as well that I wasn't expecting.  It's was almost impossible to work out what was changed as part of the import (let alone revert anything).

**Comment by cigamit** [comment]
Yea, the template system is dangerous in my opinion.  You have to be very careful when bringing in a stray from the field.  It could eat your children.

**Comment by smiles1969** [comment]
LMAO Jimmy!

**Comment by ronytomen** [comment]
Sometimes it more like body snatchers and just takes over the template..
