### ISSUE TITLE
Upgrade database script not actually upgrading Cacti

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#2780]
**To Reproduce**
1. Deploy Cacti 1.2.4 on top of any pre-release.
2. Shell exec cli/upgrade_database.php
3. Access Web
4. See error, upgrade wizard instead of index.php

**Comment by cigamit** [comment]
Oh, that is interesting.  It's not supposed to care.  Have to reach out to @netniV.

**Comment by netniV** [comment]
Actually it is.  The upgrade_database.php runs through any database upgrades that may be required, but the web/cli installer does more than just the database.  The last DB upgrade was probably 1.2.3 so would have been the latest database version the upgrade went to.  The cli/web installer would go to the code version.

**Comment by cigamit** [comment]
Oh, that somehow defeats the purpose for the upgrade script.  This was intended originally for package maintainers.  Committing something shortly.  @ddb4github and @netniV please review.

**Comment by netniV** [comment]
We introduced a new script for package maintainers as it also performs our other upgrade steps such as installing templates, packages etc.
