### ISSUE TITLE
A non-numeric value encountered in \lib\plugins.php on line 930

### ISSUE THREAD

**Issue by BSOD2600** [Cacti/cacti#2786]
**Describe the bug**
Following two errors reoccur and login page does not show.
```
[30-Jun-2019 19:45:03 America/Los_Angeles] PHP Warning:  A non-numeric value encountered in C:\Apache24\htdocs\cacti\lib\plugins.php on line 930
[30-Jun-2019 19:45:03 America/Los_Angeles] PHP Warning:  A non-numeric value encountered in C:\Apache24\htdocs\cacti\lib\plugins.php on line 933

```

**To Reproduce**
php-7.2.19-Win32-VC15-x64 - cause this error.
php-7.2.17-Win32-VC15-x64 - no error. login is functional. 
Thus appears to be a bug with the 7.2.19 php release and how it handles the integer addition with the variables in plugins.php.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 2012 R2
 - Browser IE
 - Version 11
- Apache 2.4.39 ( httpd-2.4.39-win64-VC15 )

**Additional context**

**Comment by netniV** [comment]
Do we know if a later release corrects the issue again? Also, is it patch 18 or 19? As I don't see a release for 19 yet.

**Comment by BSOD2600** [comment]
7.2.19 is the latest of that branch posted on https://windows.php.net/download/  released 2019-May-29 
If you'd prefer, could switch to 7.3.6 instead ?

**Comment by netniV** [comment]
Not sure if 7.3 will have its own issues as we haven't done a full 7.3 compatibility test yet.  Weirdly, [PHP Releases](https://www.php.net/releases/index.php) states that 7.2.18 is the latest on the 30th May...

**Comment by BSOD2600** [comment]
Odd indeed.  They've got it listed here: https://www.php.net/ChangeLog-7.php#7.2.19

**Comment by netniV** [comment]
Very strange.  Anyway, we reviewed the code and cannot see how this error could OK.  The field should be an integer already so should never have this issue.

**Comment by BSOD2600** [comment]
This error does not occur with php 7.2.20 and latest 1.2.5 develop branch.

**Comment by netniV** [comment]
So it does sound like an interim bug that they introduced.
