### ISSUE TITLE
Aggregate Preview Tab is missing

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#2787]
The preview tab keeps disappearing and reappearing. 
![image](https://user-images.githubusercontent.com/12864741/60409924-df8b1a80-9b82-11e9-9052-0b06cab4fa46.png)
Probably happened after #2768 but not sure.
After clicking back to the "Details" tab, the Preview re-appears. If you're on the "Items" tab, "Preview" is gone.

**Comment by cigamit** [comment]
Yea, sorry a regression from my fix of another bug.  Resolving shortly.
