### ISSUE TITLE
Boost display error

### ISSUE THREAD

**Issue by jpobeda** [Cacti/cacti#279]
Hi there,

Cacti 1.0.0 upgraded to 1.0.1 from github

Every time I go to Console/ System utilities / View Boost Status I get these errors on cacti.log

> 2017-02-07 13:12:37 - CMDPHP PHP ERROR WARNING Backtrace: (/utilities.php: 87 boost_display_run_status)(/utilities.php: 2124 number_format_i18n)(/include/global_languages.php: 569 number_format)(CactiErrorHandler)(/lib/functions.php: 4233 cacti_debug_backtrace)
> 2017-02-07 13:12:37 - ERROR PHP WARNING: number_format() expects parameter 1 to be double, string given in file: /var/www/html/cacti-develop/include/global_languages.php on line: 569 

If you want me to provide full debug logs, just let me know.

Current Setup

Cacti 1.0.1 from github with latest commits and bugfixes
PHP 5.3.3
Apache 2.2
MariaDB 10.0.29

**Comment by cigamit** [comment]
Resolved.  Thanks for reporting.
