### ISSUE TITLE
The traffic image has a shadow, but the aggregated image does not appear

### ISSUE THREAD

**Issue by zhangjian420** [Cacti/cacti#2790]
I created a traffic aggregation graph and two traffic graphs. When Presets is selected to select Last Day or Last 2 Days, the graphics display is normal.
But with Last 3 Days or above, the aggregated graphics are normal, but the two traffic graphs are shaded.

1、Select Last Day, the graphics are displayed normally
![1](https://user-images.githubusercontent.com/293321/60450288-1e40d380-9c5c-11e9-9b36-72433cd29e4b.jpg)
2、Select "Last 3 days", the traffic aggregation graph is normal, and the two traffic graphs are shaded.
![2](https://user-images.githubusercontent.com/293321/60450359-4cbeae80-9c5c-11e9-951d-060dd48428ee.jpg)
3、The traffic aggregation graph is configured as follows
![3](https://user-images.githubusercontent.com/293321/60450470-81cb0100-9c5c-11e9-82ed-70a0ea1e92cb.jpg)
4、The configuration of the traffic graph template is as follows
![4](https://user-images.githubusercontent.com/293321/60450587-c5256f80-9c5c-11e9-81c4-387f298f2d66.jpg)
I have read the code for a long time, please help me solve this problem, thank you.

**Comment by cigamit** [comment]
Closing again.  Unselect the 'MAX' line and this problem will go away.

**Comment by cigamit** [comment]
Don't open a new bug on this again please.
