### ISSUE TITLE
Large installation - replication issue

### ISSUE THREAD

**Issue by sysres-dev** [Cacti/cacti#2793]
**Describe the bug**
After upgrading from 1.1.38 to 1.2.4 the replication process start to stack up.

**To Reproduce**
I had the problem on my production environment (~30k devices), but I can reproduce it in my lab with a dump from my prod database).
I have 1 master and a few pollers, 2 of those pollers have about 14k devices each, when upgrading to 1.2.4 the first replication starts with the poller process but doesn't end in 5 minutes and then another is started at the next poll cycle.
Each replication process is using a few GB of RAM and after a few stacked up processes, all the RAM is used and the Linux OOM Killer starts to work...

On my lab environment, when I limit the number of devices on the remote poller, the problem disappears as the replication takes less than 5min.

**Expected behavior**
Only one replication at a time so as not to kill the server

**Screenshots**
```
[root@imgsr-t501 ~]# ps faux |grep replicate
root     22910  8.6 10.5 2426720 407828 ?      R    14:56   6:08 /opt/rh/rh-php70/root/bin/php -q /var/www/cacti/cli/poller_replicate.php --poller=2
root     24561 11.4 10.7 2366364 415316 ?      R    15:12   6:17 /opt/rh/rh-php70/root/bin/php -q /var/www/cacti/cli/poller_replicate.php --poller=2
root     24850 11.3 24.0 2594136 934820 ?      R    15:17   5:40 /opt/rh/rh-php70/root/bin/php -q /var/www/cacti/cli/poller_replicate.php --poller=2
root     27529  6.3  3.6 474972 142276 ?       R    16:03   0:16 /opt/rh/rh-php70/root/bin/php -q /var/www/cacti/cli/poller_replicate.php --poller=2
root     27530  5.0  3.6 474972 142276 ?       R    16:03   0:12 /opt/rh/rh-php70/root/bin/php -q /var/www/cacti/cli/poller_replicate.php --poller=2
```

**Additional context**
All my servers use the same softwares :
OS : RHEL 7.5
PHP : 7.0
DB : MariaDB 10.2.8

Cacti Version | 1.2.4
Cacti OS | unix
RSA Fingerprint | 22:9a:ef:ad:d8:de:1d:e7:95:7d:89:98:bd:4f:b9:df
NET-SNMP Version | NET-SNMP version: 5.7.2
RRDtool Version Configured | 1.4.0+
RRDtool Version Found | 1.4.8
Devices | 29079
Graphs | 494155
Data Sources | Script/Command: 20285
SNMP Get: 81036
SNMP Query: 308536
Script Query: 65304
Script Server: 28892
Script Query - Script Server: 35009
Total: 539062

Do not hesitate to ask for further details or tests to run, I will leave the 1.2.4 version on my lab environment.

**Comment by cigamit** [comment]
There is a fairly big fix for replication in 1.2.5.  Develop is pretty much ready to do.  Just waiting on the weekend for formal release.  After 1.2.5, you should only have to replicate once in a while to replicate settings more so that data sources and graphs.

**Comment by cigamit** [comment]
I'm going to mark this as duplicate and close.  Keep an eye out for the 1.2.5 release and update right way.  You might consider a full re-index, afterwards if continue to have issues.  After the re-index, a full sync would not be a bad idea.

**Comment by sysres-dev** [comment]
I tried 1.2.5 on my lab installation and I still have the problem of processes stacking up.

What is the recommended frequency for poller replication ?
I have a script that add devices every night, do think manually starting the replication each night after my script is a good idea ?

By the way, I found a bug when trying to disable the scheduled replication, I will post a pull request shortly.

**Comment by sysres-dev** [comment]
Hi @cigamit , any idea about my question above (poller replication frequency) ?

Thx.

**Comment by TheWitness** [comment]
Jumping in on this thread.  I would update to 1.2.6 first, update replication to either manual, or to once a day, then kill all the replicate tasks that remain.  After that, force a replication.

**Comment by sysres-dev** [comment]
Hi,

Following up on this issue, I tried 1.2.7 a few days ago and I still have the same problem :(

Any ideas ?

Thx.

**Comment by TheWitness** [comment]
1.2.8 should be out this weekend.  As I see it there were more changes in that release to reduce issues.

**Comment by sysres-dev** [comment]
Hi,

I saw that 1.2.8 was released yesterday. I tried it, but same issue...
Any ideas ?

Thx.

**Comment by cigamit** [comment]
What is the replication frequency?

**Comment by cigamit** [comment]
I just made a minor change to cli/poller_replicate.php.  Kill all the running processes, and then install it.

**Comment by sysres-dev** [comment]
Hi, I'm testing that right now, I will keep you posted.

Thank you.

**Comment by sysres-dev** [comment]
Hi,

It seems to be working fine on my lab environment. I will push that to production at the beggining of January.

thanks again.
