### ISSUE TITLE
Graph template not saved on graph edit

### ISSUE THREAD

**Issue by scamp** [Cacti/cacti#2794]
**Cacti version**
1.2.3 via freebsd ports
**PHP version**
7.2.16
**RRDTool version**
1.7.0

**Describe the bug**
The "Graph template" field is not being saved on saving graph settings under graph management.

**To Reproduce**
1. Add a new graph using Graph management
2. Select specific template (Interface bits/s), add data sources.
3. Save the graph.
4. Return to edit graph, notice the template is different from saved (Cisco CPU usage).
5. Clicking "Save" without changing the template breaks the graph.

**Expected behavior**
Graph template, host and data sources correctly saved.

**Comment by scamp** [comment]
Please not, that affected graphs were added manually using "New graph" page using previous versions of Cacti.
Now any of "Interface" graph templates are not present on template list when creating a new graph from scratch. Creating graphs from "Device" page works fine.
I wonder if this could be related.

**Comment by cigamit** [comment]
You will have to provide additional detail like the contents of your log files, and screen shows of the RRDtool debug output from Graph Management both before and after.  There is simply not enough information for us to diagnose from what you have provided.

**Comment by barreljan** [comment]
Same here. Thought it was a browser thing... I was loosing my mind about this. In the earlier version (1.2.2 or 1.2.3) it was working, still with some quirks though.

Cacti version
1.2.4 via Yum epel repo, using Spine 1.2.4
PHP version
7.3.7
RRDTool version
1.4.8
SELinux enabled. No failures in the audit logs

We have some custom graphs and the aggrate function does not satisify our needs. We aggregate it ourself from multiple devices (all plain traffic).

@cigamit; I will be making some of the requested information. For now basically, 
its a graph template with no data sources, but custom inputs. Then, add a new graph via Management, choose the template and no device. Unlock the graph. Choose the neccesary Graph Item Fields. Then, save. As you would expect, all Graph Item Fields are saved, but if you edit the new graph, the Select Graph Template is back to 2 Cisco Memory Usage (or whatever sits on top), and all the inputs at the Graph Item Fields section are one and the same from the same device.

Here some screens. The log is attached also, no specific entry found. Some issues I need to fix but not related.

![capt1](https://user-images.githubusercontent.com/29972043/61777290-f547d480-adfc-11e9-8f7e-58c4e88bddf0.PNG)
![capt1a](https://user-images.githubusercontent.com/29972043/61777291-f547d480-adfc-11e9-8875-36f1889a46fa.PNG)
![capt1b](https://user-images.githubusercontent.com/29972043/61777292-f547d480-adfc-11e9-88b9-14d6a1162625.PNG)
![capt2](https://user-images.githubusercontent.com/29972043/61777293-f547d480-adfc-11e9-8877-dba386ad8f44.PNG)
![capt3](https://user-images.githubusercontent.com/29972043/61777295-f5e06b00-adfc-11e9-8a4e-35d09d0fd5de.PNG)
![capt4](https://user-images.githubusercontent.com/29972043/61777296-f5e06b00-adfc-11e9-9de8-4c5ddebdd1dc.PNG)
![capt5](https://user-images.githubusercontent.com/29972043/61777298-f5e06b00-adfc-11e9-9266-21f198950cce.PNG)
[log.txt](https://github.com/Cacti/cacti/files/3425699/log.txt)

The graph Cacti makes is correct, however it uses the same traffic_in and traffic_out for all the inputs....

@scamp is this the same sort of issue you are experiencing?

**Comment by cigamit** [comment]
If you two can update to 1.2.5 first, that would be appreciated.

**Comment by cigamit** [comment]
Oh, this is interesting.  I see what the bug is now.

**Comment by cigamit** [comment]
Okay, I've made a change, though it won't help for graphs that are broken already.  So, before you apply this fix, make sure your graphs are okay.  After the change, the problem should be resolved, though it's obfuscating some things, which I don't think is a problem.

**Comment by scamp** [comment]
> @scamp is this the same sort of issue you are experiencing?

Yes, that it!
Thanks for detailed description.

**Comment by scamp** [comment]
@cigamit thanks, verified as resolved.
Now I am able to edit graphs and change data sources without resetting graph template.
Also template option has been removed from graph edit page.
