### ISSUE TITLE
Why is the custom time interval 3 days,  the graphics will lose frames

### ISSUE THREAD

**Issue by zhangjian420** [Cacti/cacti#2796]
It is now July 4, 2019, 22:04。
1、Custom interval of 3 days：
The start time is 2019-07-01 22:01 and the end time is 2019-07-03 22:01.Then click on the Refresh button，You will find that the graphics have lost frames.
![1](https://user-images.githubusercontent.com/293321/60672621-6bb18080-9ea8-11e9-9505-e2371a220832.jpg)
2：Custom interval of 2 days：
The start time is 2019-07-02 22:01 and the end time is 2019-07-03 22:01.Then click on the Refresh button，Graphic display is normal。
![2](https://user-images.githubusercontent.com/293321/60672798-e11d5100-9ea8-11e9-99dd-77fcc971cda6.jpg)
3：Custom interval of 4 days：
The start time is 2019-06-30 22:01 and the end time is 2019-07-03 22:01.Then click on the Refresh button，Graphic display is normal。
![3](https://user-images.githubusercontent.com/293321/60673420-3c9c0e80-9eaa-11e9-9d19-3cfd34adb27d.jpg)

Why is the custom time interval 3 days,  the graphics will lose frames？

**Comment by netniV** [comment]
I'm not sure I follow you there.  The custom date range you have set is actually 3 days of data (dates are inclusive).  Jun 30th 10pm-12pm, July 1st, 2nd, 3rd until 10pm (roughly).  The issue is, due to scaling, you aren't seeing Sunday on the left because there simply isn't room.

**Comment by cigamit** [comment]
Please become familiar with RRDtools design.  You must setup Data Source Profiles that define your storage retention settings.  In the future, questions like this are better handled in the forums.  Thanks!
