### ISSUE TITLE
When upgrading from before 1.x, SuperLinks view permissions may not be correct

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#2797]
**Describe the bug**
1. Lost realm of "External Links" during Cacti upgrade from pre-1.0.0
2. Missed to remove obsoleted plugins realms from plugin_realms, including: settings, nectar, superlinks, 

**To Reproduce**
1.  Build Cacti 0.8.8 env with superlinks, settings, nectar plugins enabled
2.  Access Console-->User Management-->admin(edit)
2.  Make sure all permission is selected, and save
2. Upgrade to Cacti 1.2.4 by cli/upgrade_database.php
3. Check User-->Permission(Tab)

**Comment by netniV** [comment]
That is interesting.  I would have though someone else would have reported that by now given the 1.x lifetime.  We will have to double check the upgrade code as I thought this was part of it.

**Comment by netniV** [comment]
for superlinks, the following code should be adjusting the realms as appropriate:

```php
db_install_execute('DELETE FROM superlinks_auth WHERE pageid NOT IN(SELECT id FROM external_links)');
db_install_execute('INSERT INTO user_auth_realm (user_id, realm_id) SELECT userid, pageid+10000 FROM superlinks_auth');
db_install_drop_table('superlinks_auth');
```

This is found in the install/upgrades/1_0_0.php upgrade file.

**Comment by ddb4github** [comment]
above three lines upgrade permission of `superlinks created tab, links, ...`. But not "External Links" that is like "Graphs, Devices"

**Comment by netniV** [comment]
I'm confused because Superlinks became External Links I believe.

**Comment by ddb4github** [comment]
"Superlinks" plugin permission is configured in table plugin_realms.

During upgrade,  1_0_0.php only handle "superlinks internal permission" from table 'superlinks_auth ' about "permission of superlinks created content".

* Before upgrade:
![image](https://user-images.githubusercontent.com/17589018/60694705-9b48a300-9f11-11e9-9712-0b04041d4694.png)

* After upgrade
![image](https://user-images.githubusercontent.com/17589018/60694788-e1056b80-9f11-11e9-8514-cf0230e8d9fd.png)
![image](https://user-images.githubusercontent.com/17589018/60694868-4194a880-9f12-11e9-8de1-f5aa22c47be2.png)

* Whatever before/after upgade, 
```
# mysql cacti -e "select * from plugin_realms where plugin='superlinks'"
+----+------------+---------------------+------------------------------------+
| id | plugin     | file                | display                            |
+----+------------+---------------------+------------------------------------+
| 12 | superlinks | superlinks.php      | Plugin -> SuperLinks: View Pages   |
| 13 | superlinks | superlinks-mgmt.php | Plugin -> SuperLinks: Manage Pages |
+----+------------+---------------------+------------------------------------+
```

**Comment by netniV** [comment]
Was there anything already populated in the external links table ? I notice that the first query is only checking that the external links id does not exist in superlinks, but I suspect it should also have the -1000 on it.

**Comment by netniV** [comment]
Wait, I may be missing that the External Links will have it's own realm anyway.

**Comment by netniV** [comment]
OK, to be clearer on this the security for the links are being transferred, but the manage permission is should be set to realm 24 but is not.  I think we will need to update the 1_0_0.php upgrade file but it is unfortunately that any previous upgrade will have lost this permission.

**Comment by netniV** [comment]
Actually, my bad.  External Links should be available to any user with access to a link.  External Links is the ability to view the tab not the management of it.  So, we will patch this in 1.2.5 to reapply that realm if they have access to a link.

**Comment by netniV** [comment]
I've submitted a change to the 1_0_0.php file that should rectify the upgrade.  If you have already upgraded, it wouldn't be right to run this automatically since you could have adjusted the permissions already and this could have changed them without your knowledge if run in a later upgrade.

If you do need to grant view permissions to the external links tab for all users you can run:

```
REPLACE INTO user_auth_realm (user_id, realm_id) SELECT user_id, 24 AS realm_id FROM user_auth
```
