### ISSUE TITLE
1.2.4 If device becomes SNMP unreachable but is pingable ping graph does not populate

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#2798]
Hello All 

We had a device where the availability check was set to ping or SNMP reachability 
I noticed that the device became unresponsive to SNMP polls due to a config issue however the device was pingable 

As you would expect the SNMP graphs like interface and CPU show no data but I also see that the ping graph ended up showing NAN to fix this I set the availability check to PING only then the graph started populating again 

Not sure if this was an isolated incident I will try to replicate it again in the lab
Also not sure if this is a bug

I will update back once I test this out 

Thanks!

**Comment by bmfmancini** [comment]
I notice that when I update the reachability option this appears in the log 


2019/07/05  09:53:42 - CMDPHP PHP ERROR NOTICE Backtrace:   (/graph_json.php[158]:rrdtool_function_graph(),  /lib/rrd.php[2127]:CactiErrorHandler())
--
2019/07/05 09:53:42 - ERROR PHP NOTICE: Only variables should be  passed by reference in file: /var/www/html/cacti/lib/rrd.php  on line:  2127
2019/07/05 09:53:42 - CMDPHP PHP ERROR NOTICE Backtrace:   (/graph_json.php[158]:rrdtool_function_graph(),  /lib/rrd.php[2127]:CactiErrorHandler())
2019/07/05 09:53:42 - ERROR PHP NOTICE: Only variables should be  passed by reference in file: /var/www/html/cacti/lib/rrd.php  on line:  2127
2019/07/05 09:53:42 - CMDPHP PHP ERROR NOTICE Backtrace:   (/graph_json.php[158]:rrdtool_function_graph(),  /lib/rrd.php[2127]:CactiErrorHandler())
2019/07/05 09:53:42 - ERROR PHP NOTICE: Only variables should be  passed by reference in file: /var/www/html/cacti/lib/rrd.php  on line:  2127
2019/07/05 09:53:42 - CMDPHP PHP ERROR NOTICE Backtrace:   (/graph_json.php[158]:rrdtool_function_graph(),  /lib/rrd.php[2127]:CactiErrorHandler())
2019/07/05 09:53:42 - ERROR PHP NOTICE: Only variables should be  passed by reference in file: /var/www/html/cacti/lib/rrd.php  on line:  2127
2019/07/05 09:53:42 - CMDPHP PHP ERROR NOTICE Backtrace:   (/graph_json.php[158]:rrdtool_function_graph(),  /lib/rrd.php[2127]:CactiErrorHandler())
2019/07/05 09:53:42 - ERROR PHP NOTICE: Only variables should be  passed by reference in file: /var/www/html/cacti/lib/rrd.php  on line:  2127

**Comment by netniV** [comment]
I believe this has already been addressed if you search through the histories/change log

**Comment by bmfmancini** [comment]
I also confirmed that the Ping graph stops generating when the device shows up via ping but down via snmp  I dont understand why that would be  I would expect that the SNMP based graphs would not work but why would the ping stop ?

**Comment by bmfmancini** [comment]
I believe I have fixed this issue using data from 2c25435

                                  Remove &
                                    
function strip_alpha(&$string) {
        /* strip all non numeric data */
        $string = trim(preg_replace('/[^0-9,.+-]/', '', $string));

Just waiting to see if the ping graph starts working again

**Comment by bmfmancini** [comment]
The errors are gone but the graph is still not generating unless I make the reachability option to ping

**Comment by netniV** [comment]
I'm going to suggest waiting for the 1.2.5 release and see if that resolves things for you.

**Comment by bmfmancini** [comment]
ok cool thanks !

**Comment by cigamit** [comment]
Correct, there was a bug, just remove the '&' from the strip_alpha calling parameters.  This has already been resolved as such.  If this does not resolve the issue, but the device into debug mode and review the output from spine or cmd.php for one polling cycle.

**Comment by cigamit** [comment]
Going to close as duplicate.  Please update if you still are having problems.
