### ISSUE TITLE
Under heavy use of Real Time Graphs, SQL errors may start appearing

### ISSUE THREAD

**Issue by jvickya** [Cacti/cacti#2799]
Hi,
My cacti have error log.
How to fix this problem?

![Snap1](https://user-images.githubusercontent.com/51222755/60694898-ffffff80-9f09-11e9-8b01-ce9248675d0f.jpg)

**Comment by bmfmancini** [comment]
Use the analyze_db.php script  to check the db 

Then use repair_db.php script if needed 
 Did this happen after a upgrade ?

**Comment by cigamit** [comment]
This is likely that you have an old table structure for the realtime plugin.  Can you please output the results of the following SQL command:

```sql
SHOW CREATE TABLE poller_output_realtime;
```

If it shows anything other than a varchar(255) for the poller_id field, you should update it by first dropping the table and then applying the create table in install/updates/1_0_0.php.

**Comment by cigamit** [comment]
Oh, wait, I actually see a bug here.  Run this command:

```sql
ALTER TABLE poller_output_realtime DROP PRIMARY KEY, ADD PRIMARY KEY (local_data_id, rrd_name, time, poller_id);
```
