### ISSUE TITLE
Edit Graph - There is nothing to Change (Everything is Disabled)

### ISSUE THREAD

**Issue by SoNix21** [Cacti/cacti#280]
When i try to edit a Graph (change the name/Title), the field is disabled... so there is nothing to change...

![image](https://cloud.githubusercontent.com/assets/25518106/22693739/8a2e2a4e-ed12-11e6-9795-ea69ca220c9b.png)

**Comment by pautiina** [comment]
I think you must klick` *Unlock Graph.`
![9](https://cloud.githubusercontent.com/assets/11805503/22708497/257fef02-ed7f-11e6-8c34-099618773634.png)

**Comment by cigamit** [comment]
Pautiina, is correct and that was to speed the interface if all you want to do is debug the output.  In very large sites who have thousands or hundreds of thousands of graphs per device.  The Graph Edit interface can get quite slow.
