### ISSUE TITLE
Tree Edit - Search Graph with comma

### ISSUE THREAD

**Issue by DavidLiedke** [Cacti/cacti#2800]
**Describe the bug**
I want to add a graph to a tree. The graph has an "comma" in the name. The graph is not found when I enter the comma in the search box.

**To Reproduce**
1. Go to Console --> Management --> Tress
2. Select one tree
2. Click on "Edit Tree"
3. Go to the Available Graph section
4. Search a graph with an comma in the name

**Screenshots**
![2019-07-05_09-02-54](https://user-images.githubusercontent.com/25581728/60704182-fd9aa700-9f03-11e9-9156-acd4201d09f9.gif)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version 67.0.4

**Comment by cigamit** [comment]
Good thing you reported this.  Thanks!
