### ISSUE TITLE
Add Data Source Info Mode to the Data Source Debug analysis page

### ISSUE THREAD

**Issue by zhangjian420** [Cacti/cacti#2801]
I use troubleshooting to check the data source and get the Issues:RRDfile does not match Data Source.
But provide Data Source Repair Recommendations, how to synchronize the data source with rrdfile.
![1](https://user-images.githubusercontent.com/293321/60729252-df20c400-9f74-11e9-876a-b675a3d263ae.jpg)

**Comment by netniV** [comment]
The data source troubleshooter hasn't completed yet according to the above screen so the recommendations won't be generated yet.

**Comment by netniV** [comment]
Also which version of 1.2 are you on?

**Comment by zhangjian420** [comment]
@netniV  @mhoran 

"Waiting on Data Source Check to Complete" has always existed. The image above is the result of the check, but no suggestions for modification. I have modified the graphics template and the data source template, but the rrdfile will not be modified synchronously, so the Issues:RRDfile does not match Data Source appears.

Version 1.2.4.

**Comment by cigamit** [comment]
Right now, the only way to view the recommendations is to goto Data Sources and enabled "Info Mode", then you will see what Cacti thinks is wrong with the RRDfile and the recommended rrdtool command to correct.  Note that some recommendations like the maximum value may be incorrect especially in cases where the interface speed is reported incorrectly by snmpd.

**Comment by zhangjian420** [comment]
@cigamit @netniV 

A few days ago, I created the graph using the "Interface-Traffic" template, and the Data Source Profile in the template was selected for 1 minute. Today I modified Presets>Data Source Profiles> 1 minute collection, and added an item, as shown below:
![1](https://user-images.githubusercontent.com/293321/60758471-a69eea00-a049-11e9-9d85-1d0925e00e13.jpg)。
then I use troubleshooting to check the data source，Get the above Issue。and I have enabled "Info Mode"，The screenshots are as follows:
![3](https://user-images.githubusercontent.com/293321/60758555-c8e53780-a04a-11e9-9c6c-eb95c21da23a.png)

**Comment by cigamit** [comment]
In the current version of Cacti, if you modify a Data Source Profile, you must delete all the RRDfiles.  This is why the Data Source Profile should be 'read only'.  If you can add to a Data Source Profile when Graph's exist, that would be a bug.

**Comment by cigamit** [comment]
![DataSourceProfileReadOnly](https://user-images.githubusercontent.com/957322/60758984-76bcfb80-9fe3-11e9-830a-fe4988a3bf21.PNG)

Note, it says 'Read Only'?

**Comment by cigamit** [comment]
I found the source of this issue.  It's a bug in the Data Template page.

**Comment by cigamit** [comment]
Okay, this one is related to #2807.  You should read it and then note where the problem was.  Thanks for keeping active reporting things.

**Comment by zhangjian420** [comment]
@cigamit  @netniV 
Yes, it is really read-only. I did this: First I switched the Data Source Profile in the data source to a 5-minute collection, then modified Presets>Data Source Profiles> 1 minute collection and added one. Then return to the Data Source Profile in the modified data source for a 1-minute collection.
If you want to do enhancements, you can choose not to modify the data source.
