### ISSUE TITLE
Merged plugins are not always upgraded correctly

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#2805]
**Describe the bug**
Since #906,  original 'realtime' plugin permission was resumed as a standalone  permission "Realtime Graphs".

**To Reproduce**
1. Prepare Cacti 0.8.8h + realtime
2. Select all permission in User(Edit)
3. Deploy Cacti 1.2.5 from develop branch
4. Upgrade by Web Wizard
5. Check user permission
6. "Realtime Graphs" is not checked

**Additional context**
After upgrade to 1.2.5, '108' is original 'realtime' plugin permission. 
```
# mysql cacti -e "select * from user_auth_realm where realm_id > 100"
+----------+---------+
| realm_id | user_id |
+----------+---------+
|      101 |       1 |
|      106 |       1 |
|      107 |       1 |
|      108 |       1 |
|     1043 |       1 |
+----------+---------+
```
Dump from 0.8.8h env before upgrade
```
INSERT INTO `plugin_realms` VALUES (1,'internal','plugins.php','Plugin Management'),
(2,'snmpagent','managers.php','Plugin -> SNMPAgent: Configure SNMP Notification Receivers'),
(3,'aggregate','color_templates.php,color_templates_items.php,aggregate_templates.php,aggregate_graphs.php,aggregate_items.php','Plugin -> Aggregate Administrator'),
(4,'settings','email-test.php','Send Test Email'),
(5,'domains','domains.php','Plugin -> Manage User Domains'),
(6,'ugroup','ugroup.php','Plugin -> Manage User Groups'),
(7,'discovery','discover.php,discover_template.php','View Host Auto-Discovery'),
(8,'realtime','graph_image_rt.php,graph_popup_rt.php,graph_ajax_rt.php','Plugin -> Realtime'),
(9,'nectar','nectar.php','Plugin -> Nectar Reports Admin'),
(10,'nectar','nectar_user.php','Plugin -> Nectar Reports User');
```

**Comment by cigamit** [comment]
Okay, taking a different approach.

**Comment by ddb4github** [comment]
Call upgrade_realms earlier than external_links created
```
2019/07/07 15:09:05 - CMDPHP ERROR: A DB Exec Failed!, Error: Table 'cacti.external_links' doesn't exist
2019/07/07 15:09:05 - CMDPHP SQL Backtrace:  (/install/background.php[52]:Installer::beginInstall(), /lib/installer.php[3200]:Installer->install(), /lib/installer.php[2723]:Installer->upgradeDatabase(), /lib/installer.php[3099]:call_user_func(), upgrade_to_1_0_0(), /install/upgrades/1_0_0.php[484]:upgrade_realms(), /install/upgrades/1_0_0.php[1797]:db_install_execute(), /install/functions.php[119]:db_execute_prepared())
```

**Comment by ddb4github** [comment]
Another error about the first get theme during 0.8.8x to 1.x upgrade
```
2019/07/07 15:05:13 - CMDPHP ERROR: A DB Cell Failed!, Error: Table 'cacti.settings_user' doesn't exist
2019/07/07 15:05:13 - CMDPHP SQL Backtrace:  (/install/install.php[62]:html_common_header(), /lib/html.php[2293]:get_selected_theme(), /lib/functions.php[511]:db_fetch_cell_prepared(), /lib/database.php[378]:db_execute_prepared())
```

**Comment by netniV** [comment]
Thanks for the feedback.  Can be an issue sometimes when trying to retro fit these older things that have passed by for so long.

Any calls to settings_user are normally done with an if exists around them within the installer, but as this is part of the wider get_selected_theme function, I guess that will need it too.

**Comment by cigamit** [comment]
Okay, both those issues resolved.

**Comment by ddb4github** [comment]
Everything workable now (not verify upgrade with data for each plugin, only add a tab by superlinks).

Exception a notice level error handling msg:
![image](https://user-images.githubusercontent.com/17589018/60775489-59f50500-a156-11e9-9df4-71b924f4d864.png)

**Comment by netniV** [comment]
That was likely skipped if the key was already found so a skipped status is OK.

**Comment by ddb4github** [comment]
Extra SQL Error in 1_0_0.php:1775, should be 'realm_id', current 'real_id'
