### ISSUE TITLE
When navigating a tree, the layout may unexpectedly move

### ISSUE THREAD

**Issue by cigamit** [Cacti/cacti#2808]
**Describe the bug**
On the dark them, and in other themes, when showing and hiding the tree, the size of the margin either is restored improperly, or the margin creeps to the left through successive navigations.

**To Reproduce**
1. Goto dark theme
2. Goto tree and start to navigation to different banches
3. Not that the left margin continually increases
4. Goto any theme, and hide the tree navigation
5. Unhide the tree, and notice the graph area has lost it's left padding

**Expected behavior**
When you hide and show the tree, the restoral of the tree should result in previous view.  Navigating the tree should not change the width of the navigation area.

**Comment by netniV** [comment]
Wasn't this raised in an earlier issue too? Or maybe that one has already been closed.

**Comment by cigamit** [comment]
Yea, it was closed.  This was related.  Noted in testing that after you hide and restore the tree, that the graphs to the right were creeping into the Tree area.
