### ISSUE TITLE
Cacti Select all and Mac Safari version 1.0.1

### ISSUE THREAD

**Issue by mattymrm** [Cacti/cacti#281]
only seems to affect Safari on the mac. Any tick box which would normally select all graphs or items underneath to be ticked doesn't work in Safari. Firefox seems to be ok and works as expected.

**Comment by cigamit** [comment]
Select All from what page?  Please be specific.

**Comment by mattymrm** [comment]
<img width="1688" alt="screen shot 2017-02-07 at 23 46 31" src="https://cloud.githubusercontent.com/assets/25553853/22716858/c000562e-ed8f-11e6-89c3-ab91ec62d5c1.png">

anywhere that has a select all box, it doesn't select all.

**Comment by mattymrm** [comment]
<img width="1748" alt="screen shot 2017-02-07 at 23 48 29" src="https://cloud.githubusercontent.com/assets/25553853/22716899/f74b4292-ed8f-11e6-8913-581431a24e5e.png">

same thing in Firefox works as it should.

**Comment by cigamit** [comment]
Turn on Safari's developer debug tools, find the console, and look for JavaScript errors.  Post what you find.

**Comment by mattymrm** [comment]
<img width="1857" alt="screen shot 2017-02-08 at 00 01 41" src="https://cloud.githubusercontent.com/assets/25553853/22717242/d3ec90b0-ed91-11e6-920b-10673e825153.png">

that any good? :)

**Comment by mattymrm** [comment]
<img width="1879" alt="screen shot 2017-02-08 at 00 04 47" src="https://cloud.githubusercontent.com/assets/25553853/22717313/412d31e8-ed92-11e6-9576-00f54c72fd2d.png">

**Comment by cigamit** [comment]
Yup that is perfect.  I'm surprised this did not show up sooner.  Some syntax issues.

**Comment by cigamit** [comment]
Just committed.  Try again.  Remember to reload.

**Comment by mattymrm** [comment]
yup all good now! Nice one. cheers :)

**Comment by mattymrm** [comment]
still broke on the select all for data query part as in the image. Other select all boxes are working fine so far.
![screen shot 2017-02-08 at 15 50 34](https://cloud.githubusercontent.com/assets/25553853/22744888/a4ccd350-ee16-11e6-89d6-1ab039c5da4b.png)

**Comment by mattymrm** [comment]
![screen shot 2017-02-08 at 15 56 21](https://cloud.githubusercontent.com/assets/25553853/22745069/35d118b6-ee17-11e6-8920-f47fde61ac9b.png)
