### ISSUE TITLE
Cacti 1.2.4 doesn't recognize Spine 1.2.4 

### ISSUE THREAD

**Issue by mauagomes** [Cacti/cacti#2812]
**Describe the bug**
I've installed Cacti 1.2.4 with Spine 1.2.4 and the following information is shown:
"SPINE 1.2.3 Copyright 2004-2019 by The Cacti Group (Different version of Cacti and Spine!)"

**To Reproduce**
1. Go to 'Tools' menu on console;
2. Click on 'System Utilities';
3. Click on 'Support';
4. See error at "Poller Information" section, where "Type" field informs Spine 1.2.3 version.

**Expected behavior**
Spine 1.2.4 poller version information is expected.

**Screenshots**
![image](https://user-images.githubusercontent.com/30599854/60837914-d4964280-a19f-11e9-9b7d-62b76bd9d8fa.png)

**Desktop (please complete the following information):**
 - OS: CentOS 7.6.1810
 - Browser: Chrome 75.0.3770.100, Firefox 67.0.4

**Additional context**
I've noticed the following text at line 2, in "configure.ac" Spine1.2.4 installer file:
"AC_INIT(Spine Poller, 1.2.3, http://www.cacti.net/issues.php)"

**Comment by netniV** [comment]
This has already been reported in a previous issue. Please use the search feature to locate it and close this one.
