### ISSUE TITLE
RRDfile Cleaner is not available

### ISSUE THREAD

**Issue by zhangjian420** [Cacti/cacti#2813]
The actual number of data sources in the system is eight, because I have deleted a lot before. However, there are many .rrd files in the cacti/rra directory. Use RRDfile Cleaner to clear the rrd file and find that there are no more rrd files.
![1](https://user-images.githubusercontent.com/293321/60864957-92c8d300-a257-11e9-9891-600a5c726053.jpg)
![2](https://user-images.githubusercontent.com/293321/60864972-9c523b00-a257-11e9-8f38-51f62cbdb0c9.jpg)
![3](https://user-images.githubusercontent.com/293321/60864982-a2481c00-a257-11e9-9c87-2d8bfddf39e3.jpg)

**Comment by cigamit** [comment]
You must rescan, also, please note that you have some permissions that are wrong on those files.

**Comment by cigamit** [comment]
Please take up issues like this on the forums please.
