### ISSUE TITLE
When viewing the utilities page, HTML tags may be seen rather than rendered

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/cacti#2814]
1) Go to ystem utilitites - Technical Support page
2) Check MariaDB Tuning Info, show like below: 
MariaDB Tuning (/etc/my.cnf) - [ <a class="linkOverDark" href="https://dev.mysql.com/doc/refman/5.5/en/server-system-variables.html">Documentation</a> ] Note: Many changes below require a database restart

Looks ugly.  
![Screen Shot 2019-07-09 at 5 09 46 PM](https://user-images.githubusercontent.com/47589910/60875716-088b6980-a26d-11e9-9641-61688ffb75ad.png)

Cacti 1.2.4
FF
rhel7 x86_64

**Comment by netniV** [comment]
Can you provide more information on what your definition of 'ugly' is ?

**Comment by cigamit** [comment]
I see the issue.  Correcting shortly.
