### ISSUE TITLE
Two issues about page navigation under "Logs" tab

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#2816]
**Describe the bug**
1. Browser 'Reload" action always return Page#1  whatever current pageno
2. Minor:  Show empty when "Brower 'Reload' action" after log rotated

**To Reproduce**
1. Issue#1
   1. Go to 'Logs' tab
   2. Click on 'Clear' button
   3. Page navigation to any non-1 page
   4. Check browser addr-bar
   5. Use browser 'Reload' method
   6. See error: page no is reset to '1'
2. Issue#2
   1. Go to 'Logs' tab
   2. Page navigation to a non-1 page, e.g. P10
   3. Waiting for log rotated. e.g. keep browser open for tomorrow working
   4. Browser 'Reloac' action,
   5. See error: page show empty

**Comment by cigamit** [comment]
Resolved.
