### ISSUE TITLE
PDOStatement::execute(): SQLSTATE[HY093]: Invalid parameter number: 

### ISSUE THREAD

**Issue by sododx** [Cacti/cacti#282]
[root@node1-SH-test html]# ./cli/add_tree.php --list-graphs --host-id=1
Known Device Graphs: (id, name, template)
PHP Warning:  PDOStatement::execute(): SQLSTATE[HY093]: Invalid parameter number: no parameters were bound in /usr/share/nginx/cacti/html/lib/database.php on line 344

lib/api_automation_tools.php:497
db_fetch_assoc->db_fetch_assoc_prepared

**Comment by cigamit** [comment]
Resolved, thanks for testing!
