### ISSUE TITLE
Upgrade to 1.2.5 fails on database upgrade: ALTER TABLE poller_output_realtime

### ISSUE THREAD

**Issue by KnoAll** [Cacti/cacti#2824]
**Describe the bug**
Getting a failure upon database upgrade: ALTER TABLE poller_output_realtime DROP PRIMARY KEY, ADD PRIMARY KEY (local_data_id, rrd_name, time, poller_id) when upgrading to v1.2.5

**To Reproduce**
1. Upgrade pre-existing cacti version, tested with 1.2.1 and 1.2.3 with the same results

**Screenshots**
![image](https://user-images.githubusercontent.com/7632685/61254174-6cec7400-a718-11e9-8364-999172842899.png)

**Additional context**
attempted 
`delete from settings where name like 'install_%';`
found here 
https://github.com/Cacti/cacti/issues/2561
with same results

**Comment by netniV** [comment]
What happens if you do the command manually?

**Comment by KnoAll** [comment]
Apologies, which command? The SQL command?

**Comment by netniV** [comment]
Yes, the failed one.  I suspect this is due to the row_format/engine

**Comment by KnoAll** [comment]
ERROR 1071 (42000): Specified key was too long; max key length is 767 bytes

**Comment by netniV** [comment]
Right, that requires the InnoDB to be using Barracuda and ROW_FORMAT=DYNAMIC

**Comment by KnoAll** [comment]
I have both of those set
MariaDB [cacti]> show variables like "%innodb_file%";
+--------------------------+-----------+
| Variable_name            | Value     |
+--------------------------+-----------+
| innodb_file_format       | Barracuda |
| innodb_file_format_check | ON        |
| innodb_file_format_max   | Barracuda |
| innodb_file_per_table    | ON        |
+--------------------------+-----------+

and have even tried manually changing the table to dynamic with the same results when trying to complete the upgrade. any ideas?
alter table poller_output_realtime ROW_FORMAT=DYNAMIC;

**Comment by KnoAll** [comment]
MariaDB [cacti]> SELECT * FROM information_schema.INNODB_SYS_TABLES WHERE name='cacti/poller_output_realtime'\G
*************************** 1. row ***************************
     TABLE_ID: 434728
         NAME: cacti/poller_output_realtime
         FLAG: 33
       N_COLS: 8
        SPACE: 427544
  FILE_FORMAT: Barracuda
   ROW_FORMAT: Dynamic
ZIP_PAGE_SIZE: 0
1 row in set (0.00 sec)

**Comment by interduo** [comment]
Try:
```
SET @@global.innodb_large_prefix = 1;
ALTER TABLE poller_output_realtime DROP PRIMARY KEY;
ALTER TABLE poller_output_realtime ADD PRIMARY KEY (local_data_id, rrd_name, time, poller_id);
```

**Comment by KnoAll** [comment]
That seems to have done it!

**Comment by interduo** [comment]
Probably You need to:
1. edit: 1_2_5.php file
2. run `php cli/upgrade_database.php`
or edit version of db in version table somewhere

**Comment by flying-bigbird** [comment]
Thanks a lot, The problem has correct!





At 2019-07-17 04:56:56, "Interduo" <notifications@github.com> wrote:


Probably You need to:

edit: 1_2_5.php file
run php cli/upgrade_database.php
or edit version of db in version table somewhere

**Comment by netniV** [comment]
This may be an extra check that we need to put in the installer.  However, as there is a workaround, I will close this for now.
