### ISSUE TITLE
"innodb_doublewrite = off" possibly dangerous recommendation

### ISSUE THREAD

**Issue by brenc** [Cacti/cacti#2825]
Just upgraded to 1.2.4 and the installer recommended a bunch of MySQL settings, one of them being `innodb_doublewrite = off` if you're using SSDs. I did some checking and I'm finding is that this setting can be _dangerous_ depending on your filesystem (it can lead to data corruption). [Here](https://dba.stackexchange.com/questions/86636/when-is-it-safe-to-disable-innodb-doublewrite-buffering) is some discussion on the matter. I have removed this setting from our installation.

**Comment by interduo** [comment]
Use ZFS and forget about that.

**Comment by brenc** [comment]
We don't have that option unfortunately.

**Comment by flying-bigbird** [comment]
Thanks a lot.The problem has correct!






At 2019-07-17 03:03:02, "Brendon C." <notifications@github.com> wrote:


We don't have that option unfortunately.

**Comment by interduo** [comment]
> We don't have that option unfortunately.

So the recommendation should be conditional 'If ZFS turn off doublewrite'.

**Comment by cigamit** [comment]
I'm going to have to agree here.  From research in the last few days by both @netniV and I, we can see that there are two cases at least, where this can be safely disabled, ZFS and FusionI/O cases.  Otherwise, you can loose your database if someone pulls the plug or you abruptly loose power.

**Comment by brenc** [comment]
I would even go further and say that many of these settings are probably overkill for most people. I manage a fairly high qps database cluster that uses hardware RAID and SSDs and I don't even set most of these. They're not necessary except under certain circumstances and can cause other side effects. Nothing else explicitly dangerous though like this doubewrite setting.

**Comment by netniV** [comment]
Yeah hardware raid trumps double write in my opinion. This is why the SQL recommendations are just that and not enforced aside from utf8
