### ISSUE TITLE
This value is not displayed on one line

### ISSUE THREAD

**Issue by tyit** [Cacti/cacti#2826]
![image](https://user-images.githubusercontent.com/31933126/61274345-39741d00-a7de-11e9-88c4-6fa8e2d4c365.png)
![image](https://user-images.githubusercontent.com/31933126/61274387-4c86ed00-a7de-11e9-9420-ee0d47ffca3a.png)

Version Cacti 1.2.5

Hi
This value is not displayed on one line

**Comment by cigamit** [comment]
Please move these discussions to the forums.
