### ISSUE TITLE
How can I do this like the picture below? Graphic sum 

### ISSUE THREAD

**Issue by tyit** [Cacti/cacti#2827]
![image](https://user-images.githubusercontent.com/31933126/61275590-dd5ec800-a7e0-11e9-9a7a-67280e1175a3.png)

![image](https://user-images.githubusercontent.com/31933126/61275622-ec457a80-a7e0-11e9-87fc-974bd2b55523.png)

![image](https://user-images.githubusercontent.com/31933126/61275956-a2a95f80-a7e1-11e9-8db3-307be0b4396f.png)

Hi
How can I do this like the picture below? Graphic sum  
Thank you

**Comment by cigamit** [comment]
Please move these discussions to the forums.
