### ISSUE TITLE
Disabled Top/Bottom external links should not be displayed

### ISSUE THREAD

**Issue by YongBoLiu** [Cacti/cacti#2830]
**Describe the bug**
The FRONTTOP/ FRONT external links always show up, even it be disabled.

**To Reproduce**
1. Go to console->utilities->External Links. Add a link with 'Top of console page' style.
2. Then disable it.
3. Navigate to  Clog page,  then navigate back the console page.
4. The external link still show up.

**Expected behavior**
If FRONTTOP/ FRONT external links  disabled, it don't need to be show.

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [firefox]
 - Version []

**Smartphone (please complete the following information):**

**Additional context**
cacti 1.2.4/1.2.5

```
diff -u -N rtm/cacti/index.php rtm/cacti/index.php
--- rtm/cacti/index.php	2019-06-08 13:01:40.000000000 +0800
+++ rtm/cacti/index.php	2019-07-18 16:38:13.000000981 +0800
@@ -30,7 +30,7 @@
 function render_external_links($style = 'FRONT') {
 	global $config;
 
-	$consoles = db_fetch_assoc_prepared('SELECT id, contentfile FROM external_links WHERE style = ?', array($style));
+	$consoles = db_fetch_assoc_prepared('SELECT id, contentfile FROM external_links WHERE enabled = "on" AND style = ?', array($style));
 	if (cacti_sizeof($consoles)) {
 		foreach($consoles as $page) {
 			if (is_realm_allowed($page['id']+10000)) {

**Comment by netniV** [comment]
Could there be times where an admin wants to keep the link but temporarily disable it?  Should there be a separate option to hide on disabled?

**Comment by YongBoLiu** [comment]
Yes, sometimes admin wants to keep the link but temporarily disable it. So, we just need to show it when it is enabled. Or I can't see what does 'disable' action option mean.
