### ISSUE TITLE
Boost performance drops on very large systems

### ISSUE THREAD

**Issue by cigamit** [Cacti/cacti#2834]
**Describe the bug**
Boost performance in Cacti 1.2.x get's poorer the more data sources you have cached in the boost table to the point where it becomes unusable.

**To Reproduce**
1. Enable boost.
2. Cache as many as 25 million boost records
3. Observe the system performance when attempt to flush the boost cache.  It may never complete.

**Expected behavior**
Boost should scale even as the number of records in the boost table increases dramatically.

**Comment by eschoeller** [comment]
That's a monster code update for boost!

**Comment by cigamit** [comment]
Well, sometimes it does not get fixed in the first pass.  Now it's totally fixed here.  https://github.com/Cacti/cacti/issues/2962

Just a side note, there is no 'multiple process' boost right now.  The setting is there, but it has not been merged.  Our bad.
