### ISSUE TITLE
Upgrader to raise error condition when innodb_large_prefix is not set

### ISSUE THREAD

**Issue by PeterUpfold** [Cacti/cacti#2836]
**Is your feature request related to a problem? Please describe.**
When the Cacti database is using **utf8mb4**, but **innodb_large_prefix** is not set, the installer will permit you to begin the upgrade process, even though doing so will cause a database error when an attempt is made to create a large index during an `ALTER TABLE`.

**Describe the solution you'd like**
The upgrader should detect the combination of **utf8mb4** charset tables combined with the lack of **innodb_large_prefix** and raise an error condition to avoid starting an upgrade process that will fail.

**Additional context**

I've just upgraded a Cacti instance from 1.2.4 to 1.2.5.

I ran into an issue during the upgrade process. Specifically, this query was failing:

    ALTER TABLE poller_output_realtime DROP PRIMARY KEY, ADD PRIMARY KEY (local_data_id, rrd_name, time, poller_id)

With the following:

    2019/07/18 21:44:04 - CMDPHP ERROR: A DB Exec Failed!, Error: Specified key was too long; max key length is 767 bytes
    2019/07/18 21:44:04 - CMDPHP SQL Backtrace: (/install/background.php[52]:Installer::beginInstall(), /lib/installer.php[3200]:Installer->install(), /lib/installer.php[2723]:Installer->upgradeDatabase(), /lib/installer.php[3099]:upgrade_to_1_2_5(), /install/upgrades/1_2_5.php[59]:db_install_execute(), /install/functions.php[119]:db_execute_prepared())

The server was configured with **utf8mb4** and the Cacti tables were also already using this charset.

    character-set-server  = utf8mb4
    collation-server      = utf8mb4_unicode_ci

However, my `server.cnf` did not have `innodb_large_prefix` (and prerequisite options) and this was causing the issue where that `ALTER TABLE` would fail, because the long index was not supported.

I was able to resolve it by setting these in the server.cnf:

    innodb_file_format=Barracuda
    innodb_file_per_table=1
    innodb_large_prefix=1

I then rolled back the previous mysqldump database backup, which re-created the tables with file_per_table and in Barracuda format to support the longer index length. A subsequent run of the upgrade process succeeded.

**Comment by netniV** [comment]
This actually relates to #2824 and #2825 where we have had a few discussions on the topic.

**Comment by JDavidRogers** [comment]
I've encountered the same issue in upgrading from 1.2.4 to 1.2.5. What is the recommended resolution?

**Comment by PeterUpfold** [comment]
I'm happy to contribute to this if this is helpful, but I'm unsure of where to start. Would adding something to `utilities_get_mysql_recommendations()` in `lib/utility.php` be correct? Is there a different place for 'blocking' requirements?

**Comment by netniV** [comment]
I think innodb_large_prefix is already in there isn't it?

**Comment by cigamit** [comment]
Okay, just making the update now.  There are four settings that now are at the 'error' level.

```console
innodb_file_per_table = ON
innodb_file_format = Baracudda
innodb_large_prefix = 1
innodb_double_write = ON
```

We also need to change the repair_database.php to convert the row format to DYNAMIC.

**Comment by cigamit** [comment]
Also, checked the 'repair_database.php', and it has a dynamic flag.  The question becomes how should we handle this.  Also, MariaDB 10.3 fails with an error about the innodb_large_prefix, they moved it back to 'deprecated' in 10.4.  So, it's going to have a ripple for folks running 10.3 for a while if we block install/upgrade for users at 10.3.
