### ISSUE TITLE
Non regular expression search filters don't support international characters

### ISSUE THREAD

**Issue by zhangjian420** [Cacti/cacti#2839]
There are three places where an exception occurs during Chinese filtering.
1、
![1](https://user-images.githubusercontent.com/293321/61642486-891d8180-acd3-11e9-9c41-13fba8854bb7.jpg)
2、
![2](https://user-images.githubusercontent.com/293321/61642494-8de23580-acd3-11e9-8134-35d6ef6a831c.jpg)
3、
![3](https://user-images.githubusercontent.com/293321/61642495-8fabf900-acd3-11e9-9739-d153d398a3b5.jpg)

The error picture is as follows：
![4](https://user-images.githubusercontent.com/293321/61642545-a9e5d700-acd3-11e9-8bcf-1e08debd77b9.jpg)

cacti v1.2.4
The system language is set to Chinese and the exception still occurs.

**Comment by cigamit** [comment]
Yea, this is a big issue right now across any page that is other than a regex page.  Going to be a big change as it affects multiple pages, but not a big deal.

**Comment by cigamit** [comment]
This is resolved in the 1.2.1 branch.  You need to test thoroughly and provide feedback.
