### ISSUE TITLE
Total count is wrong after searching for External Link pages

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/cacti#2841]
1) Go to External link page 
2) Add 4 external link
3) Search invalid "abc" and click go, the total count result after search is incorrect 
![Screen Shot 2019-07-23 at 3 05 17 PM](https://user-images.githubusercontent.com/47589910/61690541-2a501a80-ad5c-11e9-8250-cf6de460de92.png)

Cacti 1.2.4 
FF 
rhel7 x64

**Comment by netniV** [comment]
Sounds like the filter is not being applied on the count the same as it is the selection

**Comment by cigamit** [comment]
Good catch.  Thanks for reporting!
