### ISSUE TITLE
Dissociate aggregate graph from parent device[s]

### ISSUE THREAD

**Issue by TerribleTesla** [Cacti/cacti#2842]
Cacti Version 1.2.5

When creating an aggregate graph, the graph is tied to all of the devices that the data originates from.  For example, viewing in Tree View:

Firewalls (Root Container)
- Firewall1 (Device) [10 Graphs]
- Firewall2 (Device) [10 Graphs]
- Firewall3 (Device) [10 Graphs]
- Firewall4 (Device) [10 Graphs]

When I (successfully) create an aggregate graph of total blocked packets from the above 4 devices, the new aggregate graph shows under all 4 of the devices in tree view (New total of 11 graphs under all 4 devices)

Can there be a feature to divorce / disassociate the aggregate graph from the parent devices to prevent them from being displayed in the tree view (When the Device is used as a node in tree view).

I'd like to be able to not have the aggregate graphs under the physical device in the tree view, but rather add in the individual aggregate graphs to another node in tree view.

**Comment by cigamit** [comment]
This was initially resolved as a bug fix with users wanting to see these graphs associated with the devices that were associated with the Aggregates.  I guess we now need a setting.  Therefore, marking as a feature request.

**Comment by TheWitness** [comment]
This has been fixed and will be a part of a user setting in 1.2.11.
