### ISSUE TITLE
Data Template can't be edited when it is in use

### ISSUE THREAD

**Issue by rprofijt** [Cacti/cacti#2845]
**Describe the bug**
After upgrading to 1.2.5 we wanted to change the maximum value in a data template that is being used, on save it gives an "Save Failed due to field input errors" this seems to be because the page thinks the Internal data source name is missing, it is not, but it is greyed out/pre-filled. This does work in 1.1.3.8 and on a data template that is not in use.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Templates -> Data Source
2. Click on a data template that is in use and edit the Maximum Value
3. Click save

**Expected behavior**
The data template gets edited with the new maximum value

**Screenshots**
![cacti125-datatemplate-bug](https://user-images.githubusercontent.com/12047685/61877028-7cc14080-aeee-11e9-8c3a-46a893e0db36.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version:  67.0.4

**Comment by cigamit** [comment]
Oh, darn.  I did not test that.  Let me fix it now.

**Comment by cigamit** [comment]
All fixed up now.

**Comment by eholz1** [comment]
This does not help me. If I have no devices I have no data source templates. If I add a router or switch, then I get datasources and a datatemplate. I want to change the collection to 5 min for the cpu usage.
My default preset is 1 min. the 5_cpu name is greyed out on the form, and will not let me select the option to allow user to change preset on device creation - How can I do this?

**Comment by eholz1** [comment]
oops, better forget above comment - found this:
![image](https://user-images.githubusercontent.com/49035408/62730413-c3299b80-b9d4-11e9-9969-57f856574996.png)

**Comment by netniV** [comment]
Why do you have so many 1 minute collections to?  Do they have different time spans?
