### ISSUE TITLE
Aggregate graphs get clipped due to incorrect date range

### ISSUE THREAD

**Issue by jav4** [Cacti/cacti#2848]
Due to an error in step calculation, some aggregated graphs get a part of them clipped. Fix is very simple (patch included).

[rrd.patch.txt](https://github.com/Cacti/cacti/files/3438126/rrd.patch.txt)

```diff
--- rrd.php.OLD	2019-07-27 13:46:43.387895819 +0200
+++ rrd.php	2019-07-27 13:47:04.100010947 +0200
@@ -2458,7 +2458,7 @@
 			if (cacti_sizeof($data_source_info)) {
 				foreach($data_source_info as $resolution) {
 					if ($graph_start > ($time - ($resolution['step'] * $resolution['steps'] * $resolution['rows']))) {
-						if ($type = 'res') {
+						if ($type == 'res') {
 							return $resolution['step'] * $resolution['steps'];
 						} else {
 							return $resolution['step'];
```

**Comment by netniV** [comment]
You can just paste the difference.  I've updated your post with it so you can edit and see how it's done.

**Comment by cigamit** [comment]
I'm not finding this in the Cacti source.  What version of Cacti are you using?

**Comment by jav4** [comment]
@cigamit I was using 1.2.4, but bug is still in current tree (line 2465 of lib/rrd.php as of today).

**Comment by cigamit** [comment]
Okay, yea brain dead.  Found it.
