### ISSUE TITLE
Graph and Devices Permission not found

### ISSUE THREAD

**Issue by sebas4944** [Cacti/cacti#2849]
Graph and Devices Permission it does not work correctly, just don't filter what you should filter.
the only filter that works correctly is tree permissions.

I am testing in versions 1.2.4 and 1.2.5

Before I had version 0.8.8 installed and everything worked perfect

**Comment by netniV** [comment]
Actually it works perfectly.  This is a user error 👍 

There are tick boxes on each filter which determine help determine what is shown.  I am betting that once you toggle them, you see what you want to see.

**Comment by sebas4944** [comment]
No no, it is not a user error.
I had version 0.8.8 installed and it worked perfect.
When I upgrade to version 1.2.4 it stopped working.

Try deleting users and creating them again, but it still doesn't work.

**Comment by netniV** [comment]
Works perfectly for me.

**Comment by sebas4944** [comment]
![equiposvisiblesListo](https://user-images.githubusercontent.com/53378301/62013508-06307700-b16a-11e9-9e08-a1a459a10fb0.png)
![equipobloqueadoListo](https://user-images.githubusercontent.com/53378301/62013509-06307700-b16a-11e9-9b60-a7c89fd1ad91.png)

**Comment by netniV** [comment]
And on the graph tab does it say something like:
```
Note: System Graph Policy is 'Permissive' meaning the User must have access to at least one of Graph, Device, or Graph Template to gain access to the Graph
```

**Comment by cigamit** [comment]
Cacti permissions were pretty much broken in 0.8.8.  You may have thought they were working, but they were very difficult to work with and basically inconsistent at best.  These issues have been resolved, but some users will experience issues if they are upgrading a system.  Best you read up on the new permissions system, and things will operate better, and it's easier to use as well.
