### ISSUE TITLE
Missing graph template in device drop down

### ISSUE THREAD

**Issue by mattymrm** [Cacti/cacti#285]
ive attached a couple of screen shots. Basically the graph template, data query etc all exist, actually was using it ok for a while adding new devices in version 1.0.1. I then went to add another new device and its missing from the list.

![screen shot 2017-02-08 at 15 29 28](https://cloud.githubusercontent.com/assets/25553853/22743993/d21b3eee-ee13-11e6-87c1-73df6b49911b.png)
![screen shot 2017-02-08 at 15 29 02](https://cloud.githubusercontent.com/assets/25553853/22744009/e3542f36-ee13-11e6-8799-81e63dcb56e9.png)

**Comment by cigamit** [comment]
That should not happen.  The way the drop down works is as follows:

Graph Templates drop down will only include Graph Templates that are NOT associated with a Data Query.  If a Graph Template is associated with a Data Query, it will NOT show up under Graph Templates.  If the device is already assigned to the Graph Template, it will disappear from the drop down list, but that affects the current Device only, and does not bleed into other devices.  So, I'm not quite sure how this is happening.

Additionally, if the Postfix data is gather over SNMP, and the device you have added is SNMP, the SNMP based Graph Templates do not show up.  I looked for a defect in the code tonight, and could not find it.  I'm guessing that the change in behavior may have stumped you.  Give it some thought and let me know what you think.

**Comment by mattymrm** [comment]
hmm somethings not right somewhere for sure, I think it messed up when exported and imported the Advanced Ping v1.3 templates. It was there originally for new devices as I've managed to add it to three of them as you can see in the screen shot. Its not the only template thats vanished, if I add a Cisco Router device I used to see in the drop down 1 Cisco - CPU Usage (still there) and 2 Cisco - Memory Usage (vanished). That postfix Graph Template is just not showing up at all even for existing devices its not in the list of already graphed items even though the graph exists already. Im no programer but I've been using cacti for many years, something that was there is now no longer there. :(

**Comment by mattymrm** [comment]
<img width="1692" alt="screen shot 2017-02-09 at 10 41 54" src="https://cloud.githubusercontent.com/assets/25553853/22779943/9f469b7a-eeb4-11e6-932a-e46573597f5a.png">
<img width="1692" alt="screen shot 2017-02-09 at 10 40 09" src="https://cloud.githubusercontent.com/assets/25553853/22779944/9f62f7f2-eeb4-11e6-9018-d76ca82b8e21.png">

**Comment by mattymrm** [comment]
<img width="1688" alt="screen shot 2017-02-09 at 10 47 14" src="https://cloud.githubusercontent.com/assets/25553853/22780084/4a5b6838-eeb5-11e6-9e2b-5d2b4c296a08.png">
<img width="1689" alt="screen shot 2017-02-09 at 10 46 41" src="https://cloud.githubusercontent.com/assets/25553853/22780085/4aa7f40a-eeb5-11e6-9d32-6418450c688f.png">

**Comment by cigamit** [comment]
There are some complex queries under the covers here.  Will look at it again in the morning.

**Comment by cigamit** [comment]
Marking this one resolved.  If you are still missing dropdowns in the Graph Templates section, it is because you are also using those templates in the Data Queries section.  Can you confirm either?  Just reply to the closed ticket.

**Comment by mattymrm** [comment]
you can see on the screenshots that I'm not using them in the data queries section though?

**Comment by mattymrm** [comment]
![screen shot 2017-02-14 at 12 50 55](https://cloud.githubusercontent.com/assets/25553853/22929633/98ba0da6-f2b4-11e6-90fa-6d8d9589497b.png)
![screen shot 2017-02-14 at 12 51 27](https://cloud.githubusercontent.com/assets/25553853/22929635/9a377844-f2b4-11e6-9bf9-0315d8a58105.png)

**Comment by mattymrm** [comment]
ok so can't add it on the first screen but I can the second when I go to create graphs. I can click save once Postfix Queues is selected. I go back to that list of added graphs and its not there .. oh but wait it is :) -

![screen shot 2017-02-14 at 12 54 49](https://cloud.githubusercontent.com/assets/25553853/22929684/d030f128-f2b4-11e6-8231-574842959534.png)

**Comment by mattymrm** [comment]
![screen shot 2017-02-14 at 12 55 50](https://cloud.githubusercontent.com/assets/25553853/22929785/4cad82b6-f2b5-11e6-93b6-fdbed75a5c68.png)
