### ISSUE TITLE
Update error when ALTER TABLE command runs

### ISSUE THREAD

**Issue by gatesr494** [Cacti/cacti#2850]
When I try to upgade to 1.2.5 I get an error when it tries the command ALTER TABLE poller_output_realtime DROP PRIMARY KEY, ADD PRIMARY KEY (local_data_id, rrd_name, time, poller_id).

I followed what Issue # 2824 stated but when I try that I get an error stating: ERROR 1071 (42000): Specified key was too long; max key length is 3072 bytes.

My innodb settings are as follows:

mysql> show variables like "%innodb_file%";
+--------------------------+-----------+
| Variable_name            | Value     |
+--------------------------+-----------+
| innodb_file_format       | Barracuda |
| innodb_file_format_check | ON        |
| innodb_file_format_max   | Antelope  |
| innodb_file_per_table    | ON        |
+--------------------------+-----------+
4 rows in set (0.00 sec)

Any help to get this fixed is much appreciated.

**Comment by netniV** [comment]
Checkout #2836 which is likely the same issue.  If it is, please close this as a duplicate.

**Comment by cigamit** [comment]
Yea, this is the same issue.  You need to have the default file format be Barracuda, with file per table and large prefix enabled per the recommendations.  Sorry about the issue.
