### ISSUE TITLE
 message not to send to the recipient on cacti

### ISSUE THREAD

**Issue by rifanriansyah** [Cacti/cacti#2851]
Good morning..
I have a problem, the email was not sent to the recipient on cacti but the status was successful
please help

Cacti Version 1.1.38
service sendmail
Ubuntu 18.04 
Thresholds 1.0.6
![333](https://user-images.githubusercontent.com/53414308/62016614-598fdd00-b1dd-11e9-8de2-70d184766b56.jpg)

**Comment by cigamit** [comment]
Check the sendmail logs.  The success is just that it successfully handed the message off to sendmail.  From there it is your servers responsibility, and we have no control over it.  If you need future help, please ask in our forums.  This tracker is for issues with the code.

**Comment by rifanriansyah** [comment]
how to check it out ?

**Comment by cigamit** [comment]
Check /var/log/mail ?  Can't really say, its your server, there are a billion different ways for it to be configured.

**Comment by rifanriansyah** [comment]
this log
![Uploading as.jpg…]()
![ass](https://user-images.githubusercontent.com/53414308/62021929-0bd29f00-b1f4-11e9-8bb0-bfbf0ce21915.jpg)
