### ISSUE TITLE
Add Site Assocation as a default setting when adding devices via discovery

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#2854]
**Is your feature request related to a problem? Please describe.**
When adding devices that are discovered via Automation, you can currently set the device template and availability method, but you can not set which site they are associated to.

**Describe the solution you'd like**
And extra option should be added to allow the site to be predetermined rather than updated after adding the devices.  This also helps when attempting to find the devices later since they would be associated already to the site.

**Additional context**
Cacti version 1.2.5

**Comment by TheWitness** [comment]
This feature is already in the automation networks.  So, there is no change required.
