### ISSUE TITLE
Spine poller timeouts, where cmd.php does not!

### ISSUE THREAD

**Issue by RigacciOrg** [Cacti/cacti#2855]
![cacti-spine-problem-annotated](https://user-images.githubusercontent.com/863803/62055130-4ac81b00-b21b-11e9-819d-66c1a1291cd7.png)

When I activate the Spine poller, my graphs begin to show many gaps. The problem is with one host monitored via SNMP protocol over a congested DSL line. This may be expected, but the very strange thing is that the problem disappears if I select the cmd.php poller.

My Cacti installation is monitoring 5 devices with 82 data sources, the problematic host has 27 data sources active. I tried to raise the SNMP Timeout for that host to 60000 ms (one minute), but the timeout problem persists. If I try some **snmpget** commands from the Cacti host to the remote one, I always receive the answer even during network congestion. The worst case being some SNMP "extend" commands, which sometimes requires 2-3 seconds to complete (I have four of such slow commands).

In the attached **picture** you can see the difference in the resulting graph from Spine to cmd.php. As you can see the cmd.php poller does not have any issue even when the DSL line is congested at 800 kbps upload rate. I attach also a **log snippet**, with the first errors when the Spine poller fails due network congestion.

May be this is a configuration issue, but I think that Spine being - out of the box - worse than cmp.php is an issue, not just a forum topic... My installation is a clean Debian 10 Buster, with Cacti 1.2.2. 

[cacti-spine-problem.log](https://github.com/Cacti/cacti/files/3442658/cacti-spine-problem.log)

**Comment by cigamit** [comment]
This looks like a configuration issue.  Please follow-up on this issue in the forums thanks!!

**Comment by netniV** [comment]
Spine was updated this weekend, you may way to get the latest version as that does improve things with some timeouts
