### ISSUE TITLE
Aggregate issues with very long RRDtool command lines

### ISSUE THREAD

**Issue by randymendes123** [Cacti/cacti#2856]
Hi all,
I have the same issues, someone can help me to redolve this isues
**cacti Version 1.2.5
rrdtool 1.7.1
IOS: UBUNTU 19.0.4**
when add more than 498 INTERFACES   on the aggragate receive RRdtoll error
please help me to solved this problem.
![image](https://user-images.githubusercontent.com/32839066/62063375-a3e77d00-b222-11e9-97c9-02d5a157b46d.png)

[rrdtool_errror.txt](https://github.com/Cacti/cacti/files/3443165/rrdtool_errror.txt)
@neclimdul @mhoran @Xake @rlaager @ablyler @netniV help me

**Comment by randymendes123** [comment]
@cigamit could you help me with this issue ?

**Comment by jav4** [comment]
Command line for rrdtool becomes too long for PHP "popen". Please try this patch:

```diff
--- site/lib/rrd.php    2019-07-25 13:03:47.401160762 +0200
+++ site/lib/rrd.php    2019-07-27 13:51:11.809388002 +0200
@@ -261,10 +261,11 @@
        /* output information to the log file if appropriate */
        cacti_log('CACTI2RRD: ' . read_config_option('path_rrdtool') . " $command_line", $log_to_stdout, $logopt, POLLER_VERBOSITY_DEBUG);
 
+       $debug = '';
        /* if we want to see the error output from rrdtool; make sure to specify this */
        if ($config['cacti_server_os'] != 'win32') {
                if ($output_flag == RRDTOOL_OUTPUT_STDERR && !is_resource($rrdtool_pipe)) {
-                       $command_line .= ' 2>&1';
+                       $debug .= ' 2>&1';
                }
        }
 
@@ -285,9 +286,19 @@
 
                session_write_close();
                if (is_file(read_config_option('path_rrdtool')) && is_executable(read_config_option('path_rrdtool'))) {
-                       $fp = popen(read_config_option('path_rrdtool') . escape_command(" $command_line"), $pipe_mode);
-                       if (!is_resource($fp)) {
-                               unset($fp);
+                       $descriptorspec = array(
+                               0 => array('pipe', 'r'),
+                               1 => array('pipe', 'w')
+                       );
+
+                       $process = proc_open(read_config_option('path_rrdtool') . ' - ' . $debug, $descriptorspec, $pipes);
+
+                       if (!is_resource($process)) {
+                               unset($process);
+                       } else {
+                               fwrite($pipes[0], escape_command($command_line));
+                               fclose($pipes[0]);
+                               $fp = $pipes[1];
                        }
                } else {
                        cacti_log("ERROR: RRDtool executable not found, not executable or error in path '" . read_config_option('path_rrdtool') . "'.  No output written to RRDfile.");
@@ -338,14 +349,16 @@
                                $output .= fgets($fp, 4096);
                        }
 
-                       pclose($fp);
+                       fclose($fp);
+                       proc_close($process);
 
                        return $output;
                        break;
                case RRDTOOL_OUTPUT_STDERR:
                        $output = fgets($fp, 1000000);
 
-                       pclose($fp);
+                       fclose($fp);
+                       proc_close($process);
 
                        if (substr($output, 1, 3) == 'PNG') {
                                return 'OK';
```

**Comment by randymendes123** [comment]
hi @jav4 
wher i can change this _ could you share the path please ?

**Comment by jav4** [comment]
In the root directory of a source tree you just need to execute: patch -p1 <patchfile

If you want to patch an installed version, you need to locate the rrd.php file. In a Debian/Ubuntu installation it'll be at /usr/share/cacti/site/lib

**Comment by randymendes123** [comment]
@jav4  see the path  below 
![image](https://user-images.githubusercontent.com/32839066/62460105-ff60c000-b778-11e9-8c06-8408386e9309.png)

**Comment by jav4** [comment]
@randymendes123 in your case rrd.php should be at /var/www/html/cacti/lib

**Comment by cigamit** [comment]
I'm going to dispute that this is either faster or slower than the existing method.  You need to provide some validation through citations or better examples before we will merge anything.

**Comment by rlaager** [comment]
I don’t know why I was tagged here, but... @cigamit, I don’t see any claim about performance being made here. The tentative claim is that the command line is too long and fails outright for that reason.

**Comment by cigamit** [comment]
Oh, my bad, was not reading closely enough.

**Comment by cigamit** [comment]
Can you create a pull request against the 1.2.x branch then?

**Comment by randymendes123** [comment]
@jav4 
please find in attachment my rrd.php to help me add the code above I can not find  some parameters
[rrd.zip](https://github.com/Cacti/cacti/files/3492758/rrd.zip)

**Comment by jav4** [comment]
Pull request created.

**Comment by cigamit** [comment]
Resolved.

**Comment by randymendes123** [comment]
@cigamit I am lost, was resolved, whatis the solution?

**Comment by netniV** [comment]
This was committed as part of a pull request I believe.
