### ISSUE TITLE
When trying to find the best index to use, a 'must implement Countable' warning appears

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#2857]
Hello everyone 

I noticed that after running a network scan on 1.2.5 I see these errors in the log
I don't see any impacts everything seems to be running fine  but thought id report it to you 

I don't see these errors on my 1.2.4 instance 

2019/07/29  19:51:53 - CMDPHP PHP ERROR WARNING Backtrace:   (/host.php[60]:form_save(), /host.php[227]:api_device_save(),  /lib/api_device.php[779]:api_device_update_host_template(),  /lib/api_device.php[861]:run_data_query(),  /lib/data_query.php[106]:query_snmp_host(),  /lib/data_query.php[727]:get_best_data_query_index_type(),  /lib/data_query.php[2029]:sizeof(), CactiErrorHandler())
--
2019/07/29 19:51:53 - ERROR PHP WARNING: sizeof(): Parameter must be  an array or an object that implements Countable in file:  /var/www/html/cacti/lib/data_query.php  on line: 2029
2019/07/29 19:51:53 - CMDPHP PHP ERROR NOTICE Backtrace:   (/host.php[60]:form_save(), /host.php[227]:api_device_save(),  /lib/api_device.php[779]:api_device_update_host_template(),  /lib/api_device.php[861]:run_data_query(),  /lib/data_query.php[106]:query_snmp_host(),  /lib/data_query.php[727]:get_best_data_query_index_type(),  /lib/data_query.php[2029]:CactiErrorHandler())
2019/07/29 19:51:53 - ERROR PHP NOTICE: Undefined index: fields in  file: /var/www/html/cacti/lib/data_query.php  on line: 2029
2019/07/29 19:51:53 - CMDPHP PHP ERROR WARNING Backtrace:   (/host.php[60]:form_save(), /host.php[227]:api_device_save(),  /lib/api_device.php[779]:api_device_update_host_template(),  /lib/api_device.php[861]:run_data_query(),  /lib/data_query.php[106]:query_snmp_host(),  /lib/data_query.php[727]:get_best_data_query_index_type(),  /lib/data_query.php[2029]:sizeof(), CactiErrorHandler())
2019/07/29 19:51:53 - ERROR PHP WARNING: sizeof(): Parameter must be  an array or an object that implements Countable in file:  /var/www/html/cacti/lib/data_query.php  on line: 2029
2019/07/29 19:51:53 - CMDPHP PHP ERROR NOTICE Backtrace:   (/host.php[60]:form_save(), /host.php[227]:api_device_save(),  /lib/api_device.php[779]:api_device_update_host_template(),  /lib/api_device.php[861]:run_data_query(),  /lib/data_query.php[106]:query_snmp_host(),  /lib/data_query.php[727]:get_best_data_query_index_type(),  /lib/data_query.php[2029]:CactiErrorHandler())
2019/07/29 19:51:53 - ERROR PHP NOTICE: Undefined index: fields in  file: /var/www/html/cacti/lib/data_query.php  on line: 2029

**Comment by netniV** [comment]
This should now be resolved in the 1.2.x branch.
