### ISSUE TITLE
PHP 7.4 Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by jenong2k** [Cacti/cacti#2859]
2019/07/31 10:30:04 - ERROR PHP : Array and string offset access syntax with curly braces is deprecated in file: /projects/cacti/lib/html_utility.php  on line: 69

**Comment by cigamit** [comment]
I've just made a commit to the 1.2.x branch.  Can you please download and test.  Close if everything is resolved.  I did a check of the source code, and this is the ones in this file were all  I could find that we missed.

**Comment by cigamit** [comment]
Oh, that's interesting, what I just committed has some errors.  I need to check a few things.

**Comment by cigamit** [comment]
Okay, recommitted.  Test again.

**Comment by jenong2k** [comment]
Sorry for the delayed response
