### ISSUE TITLE
Graph Template - "Replacements Tags"

### ISSUE THREAD

**Issue by SoNix21** [Cacti/cacti#286]
Hi, for some reason, some "replacement" tag work, and sometimes, won't work... :(

![image](https://cloud.githubusercontent.com/assets/25518106/22797786/9e2b1f2c-eecd-11e6-9ffc-2f701ccd1f72.png)

**Comment by cigamit** [comment]
Can you goto the MySQL command prompt, and perform the following query:

select * from graph_local where id = <your graph_id>

Then, take the snmp_index field and the nun the following query:

select * from host_snmp_cache where snmp_index='your index' and host_id='your host id';

Then tell me if the replacement column exists in the output, or rather paste the results of your test and let me know if the values are correct.

There was a change in the part of the code for optimization, and maybe there was too much.  Just need to be sure.

**Comment by SoNix21** [comment]
Select * from graph_local where id = 117;
![image](https://cloud.githubusercontent.com/assets/25518106/22812468/ef8fd7dc-ef12-11e6-91d3-37d33324d26f.png)

select * from host_snmp_cache where snmp_index='474' and host_id='117';
![image](https://cloud.githubusercontent.com/assets/25518106/22812479/0492840e-ef13-11e6-8a2e-4dd278034114.png)

Seem to be Empty.... :(

**Comment by SoNix21** [comment]
Ok.. wait before investigating... 
I will try to find a real issue..., since the database take some time to update... ( 3  day passed since update..)

![image](https://cloud.githubusercontent.com/assets/25518106/22812891/6d353270-ef15-11e6-9b0a-b6b2f3612dfc.png)

**Comment by cigamit** [comment]
Next step, view the graph from Graph Preview, click the cog, and put the graph into debug mode, take the numbers off the last portion of the RRDfile, and that will be the local_data_id.  Then, from mysql, do the following:

select * from data_local where id='your local_data_id'
select * from host_snmp_query where host_id='your host_id' and snmp_query_id='your snmp_query_id'

Lastly, perform a verbose query and return the contents of the 'sort_field' from the query above, and the index query from the verbose query.

**Comment by cigamit** [comment]
So, did you give up on me?  Should I close this one?

**Comment by SoNix21** [comment]
Sorry, for the long delay...
Can you tell me how many times, the script take to @re-update@ the host_snmp_cache Database?
If i do, an "select * ', the last_update is still 6 febuary... a week passed, and the poller never update the "ifAlias" field...

**Comment by cigamit** [comment]
Run a verbose query, do the dates change then?

**Comment by SoNix21** [comment]
Yep!! i did a "verbose query" and the magic happen :)

`Found item [ifAlias='Uplink Vers .2.230 - 20 Fev 2017'] index: 47 [from value]`

When i get in the SQL database : 

![image](https://cloud.githubusercontent.com/assets/25518106/23126078/1833fc30-f743-11e6-8b9b-b774ae8387da.png)

**Comment by cigamit** [comment]
What is the re-index method?  Many people will re-index the devices every few days either in cron, or during a network discovery.  There is a cli script for this.
