### ISSUE TITLE
When testing remote poller connections during install, undefined variable warning can occur

### ISSUE THREAD

**Issue by vaclav-krauz** [Cacti/cacti#2860]
**Describe the bug**
version 1.2.4
PHP Notice:  Undefined variable: rdatabase_retries in /opt/cacti/install/functions.php on line 94

the variable rdatabase_retries is missing in global list in the function install_test_remote_database_connection()

.

**Comment by netniV** [comment]
Thanks for reporting this, it should be resolved in 1.2.6
