### ISSUE TITLE
Automation does not calculate network information correctly for single hosts

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#2862]
Hey All 

So I was adding some single IP's to automation  and I noticed that even though I specify a /32 which should be 1 IP cacti calculates this wrong

Here is an example

1.1.1.1/32
2.2.2.2/32
3.3.3.3/32
4.4.4.4/32
5.5.5.5/32

![image](https://user-images.githubusercontent.com/13388748/62238601-580f1200-b3a1-11e9-885b-9500add67457.png)

And one more weird thing 
Even if cacti had a predetermined CIDR it falls back to wouldn't it be 5G and not 4 since there are 5 subnets  ?

**Comment by bmfmancini** [comment]
Ok if you separate them by commas it goes to 0

![image](https://user-images.githubusercontent.com/13388748/62239638-4464ab00-b3a3-11e9-95b0-a0e1c7ce8451.png)

Just as a FYI my rationale of using the /32 is that we have a much larger block but are picking which devices to put in cacti I want to feed the single ip's into autom8 to do the graph creation and such

If I put a /30 then it works fine

![image](https://user-images.githubusercontent.com/13388748/62239772-842b9280-b3a3-11e9-9d87-c163c81cc33e.png)

The above where it was showing 4G is actually my bad because I didn't separate the networks by ,
but I did notice that in 1.2.4 you would get this popup

![image](https://user-images.githubusercontent.com/13388748/62239845-ad4c2300-b3a3-11e9-96ee-2511d4f27baa.png)

However I didnt see that popup in 1.2.5

**Comment by bmfmancini** [comment]
In 1.2.5 the action saves fine as below so the validation from 1.2.4 is missing in 1.2.5

![image](https://user-images.githubusercontent.com/13388748/62239938-d66cb380-b3a3-11e9-83e7-feeb98c0114a.png)

**Comment by bmfmancini** [comment]
Here is the successful save from 1.2.5 

so the validation that 1.2.4 has didn't make it to 1.2.5  it appears 

![image](https://user-images.githubusercontent.com/13388748/62240461-0bc5d100-b3a5-11e9-9249-e647a3fb6826.png)

**Comment by cigamit** [comment]
Can't you just include the 4 ip addresses.  The 32bit mask is likely a corner case.  I'll leave this open, but you should just include the 4 ip addresses in the mean time.

**Comment by netniV** [comment]
I'll take a look tonight at the code and review it just to be sure there's nothing strange.

**Comment by bmfmancini** [comment]
Thanks Guys 

@cigamit  yes I tested this morning and the single addresses without the /32 works fine

**Comment by netniV** [comment]
I've done some testing and the code wasn't quite right.  So, I'm testing a new function to provide all network details as one array which the others can use.

**Comment by bmfmancini** [comment]
cool! thanks for checking into this !

**Comment by cigamit** [comment]
@netniV, when were you going to commit your changes?

**Comment by bmfmancini** [comment]
Hey Guys 

Found another both with AUTOM8 and CIDR on 1.2.5
if there is a whitespace after the CIDR cacti will register a huge IP range

I.e 192.168.1.0/24(white space) will show 4G instead of 254

**Comment by netniV** [comment]
I've made a change that should resolve the issues regarding network calculations.  There may be other places that need a change still but I did the immediate functions.

**Comment by bmfmancini** [comment]
Looking good!

/32 shows up as one  and white spaces throws an error !
how about instead of throwing an error for white space when clicking the save action would remove any whitespace in the range ?

**Comment by netniV** [comment]
By default, no fields are automatically trimmed in cacti.

**Comment by bmfmancini** [comment]
gotcha 

ok cool everything looks good in the lab now 

Thanks alot !
