### ISSUE TITLE
After restarting the server, the graph has no data.

### ISSUE THREAD

**Issue by zhangjian420** [Cacti/cacti#2865]
Cacti 1.2.4
When I restart the server, the rrd file is not updated, causing the graph to have no data generation.
![7](https://user-images.githubusercontent.com/293321/62288052-1d36d800-b48e-11e9-88f4-5d146f372f9e.jpg)

# crontab -l
![1](https://user-images.githubusercontent.com/293321/62287598-d4325400-b48c-11e9-8265-18a8c2d824f4.jpg)

I use /usr/bin/php /var/www/html/cacti/poller.php --force to force poller
# /usr/bin/php /var/www/html/cacti/poller.php --force 
![2](https://user-images.githubusercontent.com/293321/62287550-b7961c00-b48c-11e9-91ae-d45311b7b27d.jpg)

# tail -f /var/log/crond
![3](https://user-images.githubusercontent.com/293321/62287706-39864500-b48d-11e9-9c54-91c01f14374c.jpg)

I used the cactiuser user to execute 
# php -q cli/rebuild_poller_cache.php
![4](https://user-images.githubusercontent.com/293321/62287821-8833df00-b48d-11e9-85e6-87abedd12e61.jpg)

And I also clicked the Rebuild Resource Cache button, but there is still no graphics generated.
There is no information about poller in the log.
![6](https://user-images.githubusercontent.com/293321/62288123-4a838600-b48e-11e9-9387-6f7f287ad44b.jpg)

rra file directory permissions as shown below
![8](https://user-images.githubusercontent.com/293321/62288278-98988980-b48e-11e9-9b1d-7443a1b69da0.jpg)

Now I can only solve the problem by re-generating the rra file after deleting all the files in the rra directory.Is there any other solution?

**Comment by cigamit** [comment]
Issues like this do not belong here.  They a belong on the forums.  I'm going to close this.  Please continue the discussion there.
