### ISSUE TITLE
Add poller ID to subject for admin notifications 

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#2866]
Hello Guys !

It would be nice to attach the Poller ID to the subject line when getting an admin notification that something has gone wrong 

Here is an example of a admin notification I got when we turned up a new poller the cron was misconfigured 

From this email I am left guessing where the issue was of course in this case I new a new poller came online so it most likley was that but if  this messge came out of the blue and you had multiple pollers it could be tricky 

{
From: xyz

To: Admin
Subject: Cacti System Warning

WARNING: Cron is out of sync with the Poller Interval! The Poller Interval is '60' seconds, with a maximum of a '60' seconds, but 121 seconds have passed since the last poll!
}

Something like Cacti System Warning Poller id 1 would be cool to have 

Thanks Guys !

**Comment by netniV** [comment]
This seems like a reasonable request.

**Comment by cigamit** [comment]
Resolved.

**Comment by bmfmancini** [comment]
Awesome thanks guys !
