### ISSUE TITLE
Cacti Polling Cycle Exceeded Poller Interval, gaps on graphs

### ISSUE THREAD

**Issue by maxstech** [Cacti/cacti#2868]
cacti 121
Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-43-generic x86_64)
PHP 7.0.32-0ubuntu0.16.04.1

for some time now, at the same time, I started getting gaps in the charts.  In the logs I see that at this moment in time the outcome of the work of pollster and I get what you get. See the screenshot
What can I do to fix this ?

![trubl cacti spikes](https://user-images.githubusercontent.com/47040342/62318420-8295c380-b4a4-11e9-8be5-3a13c4fc656a.jpg)

**Comment by bmfmancini** [comment]
The amount of threads you are using is really high 30 ? that would mean you are using 15 cores 
Is this a new install ?

We should also move this to the forums

**Comment by maxstech** [comment]
I have 4 cores on the virtual machine.  How many processors and threads can I supply ?  4 processors and 8 threads ?

**Comment by maxstech** [comment]
root@cacti:~# lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           4
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz
Stepping:            4
CPU MHz:             2593.906
BogoMIPS:            5187.81
Hypervisor vendor:   VMware
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            19712K
NUMA node0 CPU(s):   0-3
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xsaves arat pku ospke flush_l1d arch_capabilities

**Comment by bmfmancini** [comment]
Then you would set optimally 8 threads  
you can increase a bit passed that but then your surpassing what is actually available
and would tax the CPU and system more 

You can raise the proccess count and keep the threads at 8 which would give the system the chance to keep it running 

to test this theory during the next poll how high does you CPU go ?

**Comment by maxstech** [comment]
I set 4/8:
![cacti trubl 2](https://user-images.githubusercontent.com/47040342/62328282-62253380-b4bb-11e9-8d19-3554665af91f.jpg)

**Comment by maxstech** [comment]
the maximum load that I saw now while the poller was working:
![load cacti](https://user-images.githubusercontent.com/47040342/62328975-41f67400-b4bd-11e9-9b20-1fda0e407132.jpg)

**Comment by maxstech** [comment]
Thanks for your comments. I will observe a day or two, and I will write the result here.

**Comment by bmfmancini** [comment]
No worries 

Are you doing 1 or 5 minute polling?

**Comment by maxstech** [comment]
5 minute, here are my poller settings.  Perhaps here, too, need to adjust ?
![setting poller](https://user-images.githubusercontent.com/47040342/62329780-8edb4a00-b4bf-11e9-8558-cb03f6e280ca.jpg)

**Comment by maxstech** [comment]
I could try loading a poller every minute, but I don't fit in that minute. Now the polling time is a little more than a minute.

**Comment by bmfmancini** [comment]
No no don't set it to 1 you'll get errors looking at your stats

**Comment by maxstech** [comment]
now I already have time on the brink. I can’t understand what this is connected with.
![грань](https://user-images.githubusercontent.com/47040342/62331089-7c630f80-b4c3-11e9-840f-d3321ea351ef.jpg)

**Comment by bmfmancini** [comment]
What's the host machine load like ?
You mentioned this is a vm

**Comment by maxstech** [comment]
I don’t have access right now. Tomorrow I will ask my colleagues what kind of bother in general. Resources have been allocated for me - I use them.

**Comment by maxstech** [comment]
I have not changed anything unfortunately

**Comment by maxstech** [comment]
![trubl cacti  night](https://user-images.githubusercontent.com/47040342/62336181-cf46c200-b4d7-11e9-8833-c6059f816ba0.jpg)
![trubl cacti  night2](https://user-images.githubusercontent.com/47040342/62336190-d8d02a00-b4d7-11e9-8ed8-da7b83ca585d.jpg)

**Comment by maxstech** [comment]
How can I track the cause of these troubles?

**Comment by maxstech** [comment]
I will close this ticket and will deal with the system settings.
