### ISSUE TITLE
Creating Aggregates from Graphs pages not fully functional due to JavaScript issues

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/cacti#2869]
1) Go to Graph page 
2) Choose a graph and create aggregate graph for it. 
3) Total and Total type can not work well -- failed 
4) Can not click save button --failed. 
This makes the aggregate function totally can not work. 
![Screen Shot 2019-08-02 at 1 42 22 PM](https://user-images.githubusercontent.com/47589910/62347204-7a349b80-b52b-11e9-9487-783649559fbe.png)
![Screen Shot 2019-08-02 at 1 42 39 PM](https://user-images.githubusercontent.com/47589910/62347210-7c96f580-b52b-11e9-99fc-6b701170a40b.png)

**Comment by cigamit** [comment]
This is resolved now.
