### ISSUE TITLE
Report when RRA's heartbeat is below the data source profile's interval

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#2871]
**Is your feature request related to a problem? Please describe.**
When an RRA is created, the heartbeat is normally defined as twice that of the data source profile (from what I've seen).  However, if you switch profiles and miss recreating or migrating any of the RRA's, this can lead to gaps in the graph:

```
Turns out it was the minimal_heartbeat setting in the rrd that was the problem.

I've been dealing with odd issues here and there since upgrading from 0.8.8 to 1.2.2. One of them seems to be that my 5 minute polling data profile has a heartbeat setting of 2 minutes (120 seconds) after the upgrade.
```

**Describe the solution you'd like**
There should be a check and warning when the heartbeat is below the minimum cycle of a profile.

**Additional context**
I'm not sure whether this already appears on the Troubleshooting -> Data Sources section.

**Comment by TheWitness** [comment]
@xmacan does your RRDfile check check for this?

**Comment by xmacan** [comment]
no, but I will add it.

**Comment by xmacan** [comment]
@netniV  I have a question: Is it enough to test that hearthbeat is equal or greater than data source profile or heartbeat is equal to 2x data source? I don't know rrd that much. What is correct? Thank you

**Comment by TheWitness** [comment]
It's usually 2x.  I like to make it higher as my spine segfaults from time to time and I have not had a chance to figure it out.

**Comment by TheWitness** [comment]
This is resolved now in @xmacan RRDcheck and in the Data Source Debug.
