### ISSUE TITLE
Cacti support for MySQL 8 and use of grouping table column

### ISSUE THREAD

**Issue by rafaeldtinoco** [Cacti/cacti#2872]
**Describe the bug**

Table "aggregate_graph_templates" variable "grouping" is a keyword in recent
MySQL versions.

**To Reproduce**

Steps to reproduce the behavior: Try to import cacti.sql into a MySQL 8, for example.

**Expected behavior**

Well, unfortunately it isn't cacti's fault that MySQL project created a function named "grouping" in recent versions. Unfortunately, because of that, cacti.sql will have to change the field name. Nevertheless, looking at cacti's code, I could not find a reference to that field, possibly it is being used through positional reference and not name.

**Desktop (please complete the following information):**

- OS: Debian & Ubuntu (We are merging new MySQL 8 version into Ubuntu, and this but came from autopkgtests). Issue has been reported [here](https://salsa.debian.org/cacti-team/cacti/merge_requests/1#note_100059).
- I suggested, through Debian, the following simple [change](https://salsa.debian.org/cacti-team/cacti/merge_requests/1/diffs?commit_id=955d3048cc937b78f55184e8ca2c9925deb2f85f).

**Additional context**

We, the Canonical Server Team, are making sure Cacti is good in Ubuntu Eoan. We need this fix landing in Upstream and Debian in order to reduce Ubuntu delta. Thanks a lot for considering this, or suggesting a better fix for us to consider.

**Comment by rafaeldtinoco** [comment]
ERROR 1064 (42000) at line 1666: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'grouping char(2) NOT NULL default '',
  t_unit_value char(2) default '',
  unit_' at line 38

**Comment by rafaeldtinoco** [comment]
According to:
https://dev.mysql.com/doc/refman/8.0/en/keywords.html

GROUPING (R); added in 8.0.1 (reserved)
GROUPS (R); added in 8.0.2 (reserved)

**Comment by rafaeldtinoco** [comment]
ALRIGHT .. so instead of changing the field name, we could use `` in "grouping" keyword, just as it was used in the beginning of cacti. There is another issue for MySQL 8 as well:

ERROR 1231 (42000) at line 6: Variable 'sql_mode' can't be set to the value of 'NO_AUTO_CREATE_USER'

NO_AUTO_CREATE_USER is the default moe now and the SQL_MODE does not exist anymore. I'll provide patches fixing those 2 issues and suggest it here.

**Comment by rafaeldtinoco** [comment]
I have proposed:

https://github.com/Cacti/cacti/pull/2873/commits/b14b3da3d10a4ddf70b2514a998fa65ebf4ab3bb

To address this issue. 

Thanks for considering it.

**Comment by rafaeldtinoco** [comment]
Just got feedback that I have to address MariaDB versions also. Will re-push with a fix.

**Comment by rafaeldtinoco** [comment]
Alright I have addressed MySQL and MariaDB now. 

[Merge Request](https://github.com/Cacti/cacti/pull/2873/commits/3c7124b82b6745c6f46f5531c0907d6306e3cd0c
)
Thanks!

**Comment by cigamit** [comment]
Yup merged and fixed.  Next time, please update the CHANGELOG file too.  Thanks for sure though!!!
