### ISSUE TITLE
Undefined variable when removing spikes in some cases

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/cacti#2875]
1) Choose a graph, and do kill spike, error exist 

2019/08/05  13:40:11 - CMDPHP PHP ERROR NOTICE Backtrace:   (/spikekill.php[91]:spikekill->remove_spikes(),  /lib/spikekill.php[630]:CactiErrorHandler())

2019/08/05 13:40:11 - ERROR PHP NOTICE: Undefined variable:  new_output in file: /var/www/html/cacti_ml/lib/spikekill.php  on line:  630

![Screen Shot 2019-08-05 at 1 42 47 PM](https://user-images.githubusercontent.com/47589910/62441506-f5de5480-b786-11e9-899c-9b01d11cb8a4.png)

**Comment by netniV** [comment]
Having a brief look at the code, it would seem that you've managed to get to a point where there's been a kill of a spike but yet not output was generated which seems wrong.

A quick fix would be to put and `if(!empty($new_output)) {` just before the writing out of the xml file but that may be just masking an issue.  I'd need to thoroughly review that functions code before making a judgement on that later this week.

**Comment by cigamit** [comment]
Okay, this one was pretty strait forward in the end.  Thanks for reporting.  Just some poor logic.
