### ISSUE TITLE
Process Log

### ISSUE THREAD

**Issue by zeeffort** [Cacti/cacti#2876]
**Describe the bug**
After an upgrade to Cacti Server v1.2.5 I am getting the error "Your Cacti Server v1.2.5 has been installed/updated with errors"
Process Log

--- NO LOG FOUND ---

**Expected behavior**

**Desktop (please complete the following information):**
 - Installation was done on Ubuntu Server 16.04
 - Am using Mozilla Firefox browser
 

![nologfound](https://user-images.githubusercontent.com/53774319/62469619-eb2cbb00-b798-11e9-867a-4135daeea52e.png)

**Comment by bmfmancini** [comment]
check your permissions for /var/www/html or wherever you have your cacti installed 
make sure to have permissions set to www-data:www-data 

cat the /var/www/html/cacti/log/cacti.log file for the errors

**Comment by bmfmancini** [comment]
if you want you can re-install using this script https://github.com/bmfmancini/cacti-install-wizard
which follows the recommended installation method

**Comment by netniV** [comment]
No, that's a bug which has already been corrected in #2832
