### ISSUE TITLE
Problems sending reports

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#2877]
Hello All 

Just came across this error even from the dev branch 

Call to undefined function get_timespan() for html_reports.php

To fix I # line 810 

 #get_timespan($timespan, time(), $current_ts, $first_weekdayid);

Everything seems to be working fine after commenting out the line I think it may have been left in there from a deletion

**Comment by netniV** [comment]
I’m pretty sure there is a standard `get_timespan` function which converts a time integer to text that I wrote for 1.2.

**Comment by bmfmancini** [comment]
let me have a look 

The reporting function works fine so far with that line commented out 
I didnt see a function for it but let me check again

**Comment by netniV** [comment]
There are different functions for slightly different things but the one above should be in lib/time.php.  There is also `get_timeinstate()` which is for obtaining a human readable string of how long a device was in its current state.

**Comment by bmfmancini** [comment]
interesting 

thanks for the info

**Comment by cigamit** [comment]
I have been unable to reproduce.  Can you please post some of the log messages you are receiving?

**Comment by bmfmancini** [comment]
Sure I will comment out and rerun I'll send it sometime tomorrow

**Comment by bmfmancini** [comment]
PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/cacti/lib/reports.php
Reports still generate but you you get this error in the gui 

![image](https://user-images.githubusercontent.com/13388748/62972354-daf08d80-bde1-11e9-9ddc-f02180944bdd.png)

**Comment by bmfmancini** [comment]
Recently upgraded to 1.2.5 now I see this error

PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/cacti/lib/reports.php

![image](https://user-images.githubusercontent.com/13388748/62972445-070c0e80-bde2-11e9-80fa-4eecaab66ce0.png)

**Comment by cigamit** [comment]
Well, that is odd.

**Comment by bmfmancini** [comment]
Yeah really weird at least in 1.2.5 the report generates it's just the error that's pops up

**Comment by cigamit** [comment]
Please update to the latest 1.2.x and try again.
