### ISSUE TITLE
PHP 7.4 Function get_magic_quotes_gpc() is deprecated

### ISSUE THREAD

**Issue by jenong2k** [Cacti/cacti#2878]
2019-08-07 09:43:46 - ERROR PHP : Function get_magic_quotes_gpc() is deprecated in file: /projects/cacti/include/global.php  on line: 384
2019-08-07 09:43:46 - CMDPHP PHP ERROR Backtrace:  (/clog.php[27]:include(), /include/auth.php[28]:require_once(), /include/global.php[384]:CactiErrorHandler())

**Comment by netniV** [comment]
Magic quotes has been gone a while but as we still support PHP 5.4, we now have a problem between support systems that use it and those that don't have (7+).  Currently, using get_magic_quotes() on a 7+ system just returns false.  

IMHO, I can understand why they removed the set's etc, but the get's should just continue on returning false. Not sure how we will tackle this aside from using the PHP version itself to determine if we should call the builtin function.

**Comment by bmfmancini** [comment]
Perhaps somewhere down the line PHP 5x support is dropped after xyz release all together and move on to 7x  7 has been around long enough and there are plenty of working cacti installs to go by to say that 7 is stable enough for this project

**Comment by netniV** [comment]
That's a discussion we keep having internally because unfortunately, plenty of servers still run CentOS 6 or equivalent platforms that aren't running PHP 7 yet.  In fact, I know of servers running CentOS 5 still which surprised me so its not always easy to get people moving forwards 👍

**Comment by cigamit** [comment]
Can not wait to get away from magic quotes.  In the mean time, adding a small patch for those getting this warning.

**Comment by cigamit** [comment]
This issue for the moment is resolved.
