### ISSUE TITLE
Switching from authPriv to authNoPriv produces error when saving

### ISSUE THREAD

**Issue by enbrander** [Cacti/cacti#2879]
**Describe the bug**
Switching from AuthPriv to authNoPriv or noAuthNoPriv on a device produces "The SNMP v3 Privacy Passphrases do not match" error

**To Reproduce**
1. Edit a device that is currently set to AuthPriv for SNMP Security Level
2. Change the SNMP Security Level to authNoPriv or NoAuthNoPriv
3. Re-enter the correct SNMP Password (v3) twice (if authNoPriv)
4. See that it has the Check Mark and "Passphrases match"
5. Click Save
6. See error "The SNMP v3 Privacy Passphrases do not match"

**Expected behavior**
It should save the device settings with the new configuration.

**Screenshots**
Screenshot not added as it didn't seem necessary

**Desktop (please complete the following information):**
 - OS: Win
 - Browser Chrome
 - Version 76

**Smartphone (please complete the following information):**
N/A

**Additional context**
Cacti version 1.2.4
PHP version 5.4.16

**Comment by cigamit** [comment]
I can see why that would be a problem.

**Comment by cigamit** [comment]
Thanks for reporting.  This should be resolved now.

**Comment by enbrander** [comment]
Thanks!!
