### ISSUE TITLE
Main poller users are unable to login to remote pollers

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#2880]
Hey Guys 

I am using 1.2.4 with 2 remote pollers and a main poller 

What I am seeing is that unless I create a user on one of the remote pollers the accounts that already exist on the main poller are not able to login to the remote pollers 

The error you get is username/password incorrect and nothing appears in the log 

I am sure this is not by design  

Everything else works without issue and the main poller is able to reach out to the remote pollers 

I saw that the user auth tables did get replicated  

2019/08/07 16:00:13 - CMDPHP NOTE: Table user_auth Replicated to Remote Poller 4 With 4 Rows Updated
--
2019/08/07 16:00:13 - CMDPHP NOTE: Table version Replicated to Remote Poller 4 With 1 Rows Updated
2019/08/07 16:00:13 - CMDPHP NOTE: Table poller Replicated to Remote Poller 4 With 3 Rows Updated

When I check that table on both remote pollers I see the users I create from the main server 

This is not occurring in Debian/Centos  but this is happening for me in RHEL

I am not sure if this is a bug but it seems like it

**Comment by bmfmancini** [comment]
Well it was a glitch ! ME!! sorry guys RHEL EPEL was not enabled so the vm's got php 5.3 on them upgraded to php 7.2 all is good 

Closing

**Comment by cigamit** [comment]
It may have been a replication issue too.

**Comment by bmfmancini** [comment]
Possibly 

The issue went away and has not come back since the upgrade so I'm leaning more towards that meh who knows 

Thanks as always
