### ISSUE TITLE
Disabling poller replication doesn't work

### ISSUE THREAD

**Issue by sysres-dev** [Cacti/cacti#2883]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by cigamit** [comment]
Okay, we have resolved this in the 1.2.x branch.  Thanks for your pull request unfortunately it was against the wrong branch.  So, instead of merging, which we could not, I just committed the fix.
