### ISSUE TITLE
too many process poller_dsstats.php

### ISSUE THREAD

**Issue by salehhoushangi** [Cacti/cacti#2885]
Hi

I am new in cacti . last week i setup new cacti server in centos7.6 . with  below releas:
cacti-spine-1.2.5-1.el7.x86_64
cacti-1.2.5-1.el7.noarch
also my database server version is "MariaDB-server-10.4.7-1.el7.centos.x86_64".
our last server in cacti 0.8.8h also with same spine version. and MariaDB 5.6 goes well with no problem.
we decided to setup new cacti server to have server as secondary.
I backup from my server with simple sqldump  and restore in new cacti serve database;
my serious problem is to drawing graph with lot of gap among it.and we have different gap for each graph in timeline.
also in my last server everything is good and no more php process exist also have little use of ram .
but in new cacti server we have lot of php  process raising up from poller.php(poller_dsstats) and also consuming more RAM.(id don't know why process don't terminate and still in our server)after a while when memory reach to 40~50 % graph isn't plotted at all. in continue all RAM occupy  by php process.
Also in my cacti.log we have  strange Error and warning and after spend a lot of  time on it i cant find causes of problem. for example :
1-CMDPHP ERROR: A DB Cell Failed!, Error: PDOStatement::execute(): SQLSTATE[HY093]: Invalid parameter number: no parameters were bound
2-08/08/2019 10:29:34 - DSSTATS WARNING: File '/usr/share/cacti/rra/csw02_new_traffic_in_546.rrd' Does not exist
3- when i getting state from MariaDB i see the warning like below:
Aug 08 10:37:07 monitoring mysqld[9451]: 2019-08-08 10:37:07 139478 [Warning] Aborted connection 139478 to db: 'cacti' user: 'cacti' host: 'localhost' (Got an error reading communication packets)
I put some info such as image and config for you to give me a better troubleshooting.
======================================================================
 my sever.cnf :
[mariadb-10.4]
max_heap_table_size = 200000000
max_connections = 5000
#wait_timeout = 28000
interactive_timeout = 28000
query_cache_size = 0
query_cache_type = 0
query_cache_limit = 1M
performance_schema = ON enable PFS
innodb_buffer_pool_size = 332M
innodb_log_file_size = 48M
 ==========================================================================================

**Comment by salehhoushangi** [comment]
also i saw massage in cacti.log
2019/08/09 20:28:23 - SPINE: Poller[1] Device[55] ERROR: Problems parsing Multi                                                                                         SNMP OID! (oid: .1.3.6.1.2.1.2.2.1.11.), Set MAX_OIDS to 1 for this host to isol                                                                                        ate bad OID
2019/08/09 20:27:41 - SPINE: Poller[1] ERROR: Spine Timed Out While Waiting for                                                                                         Threads to End
08/06/2019 17:23:01 - CMDPHP SQL Backtrace:  (/poller.php[787]:poller_replicate_check(), /poller.php[847]:db_fetch_assoc(), /lib/database.php[452]:db_fetch_assoc_prepared(), /lib/database.php[466]:db_execute_prepared())
08/09/2019 20:27:49 - POLLER: Poller[1] Maximum runtime of 58 seconds exceeded.                                                                                         Exiting.

**Comment by salehhoushangi** [comment]
Time:24.0485 Method:spine Processes:6 Threads:20 Hosts:739 HostsPerProcess:124 DataSources:23419 RRDsProcessed:87

**Comment by cigamit** [comment]
This has already been fixed in the 1.2.x branch.  Please use that branch.  lib/dsstats.php and poller_dsstats.php should be pulled.
