### ISSUE TITLE
Ping on Windows machines doesnt work

### ISSUE THREAD

**Issue by FormadorLar** [Cacti/cacti#2886]
**Describe the bug**
Any kind of ping doesnt work on cacti for windows... 

TO SOLVE:
- Install fping ( https://github.com/dexit/fping-windows ) on windows ( copy the exe and add it to the %path% )
- replace the following line in \cacti\lib\ping.php:

   - locate the function ping_icmp()
   - replace the windows part  - locate this : 
              }else if (substr_count(strtolower(PHP_OS), "**winnt**")) {
     with the following code:
     - $result = shell_exec("fping " . $this->host["hostname"] . " -w " . $this->timeout . " -n " . $this->retries);

done!

please implement it on the next release.

Best regards,

FormadorLar

**Comment by cigamit** [comment]
This is a bit of a problem, we have to use something for ping that is provided by the OS vendor.  Can you please create a pull request that properly uses the Windows ping command?

**Comment by cigamit** [comment]
@BSOD2600, it would be nice if you could look at this one.

**Comment by netniV** [comment]
Ping on windows uses ICMP and for that as with Linux, you need to be elevated in order to achieve the access to RAW TCP packets as Windows protects these from being used in most circumstances these days.

The windows ping command can be utilised as it is Microsoft signed.  I will review the ping command used as I am not sure why @FormadorLar believes that this does not work at all.  He also doesn't mention which poller he is using to test that with either.

**Comment by FormadorLar** [comment]
> Ping on windows uses ICMP and for that as with Linux, you need to be elevated in order to achieve the access to RAW TCP packets as Windows protects these from being used in most circumstances these days.
> 
> The windows ping command can be utilised as it is Microsoft signed. I will review the ping command used as I am not sure why @FormadorLar believes that this does not work at all. He also doesn't mention which poller he is using to test that with either.

I'm a bit of a newbie here, but i tested on windows server 2008 r2 with iis7 and php 7,2.13. With this solution, i know it works ok, but if you can provide another solution that works here, i'll appreciate very very much!

**Comment by FormadorLar** [comment]
> The windows ping command can be utilised as it is Microsoft signed. I will review the ping c

Hi, I'm a newbie at this, I'm using cmd.php poller with windows server 2008 r2, IIS7, PHP 7.2.13 and i know this this solution works for me, at least. I know its not the ideal one, but of course if u have another that can work, i will appreciate it very very very much!

**Comment by netniV** [comment]
So I can confirm that the above ping command that we have implemented will work fine.  The only thing that I can see being an issue is if you do not have a timeout or retry value.  If that is blank for say retry, the command would become something like:

```console
chcp 437 && ping -w 1000 -n 10.20.30.40
```

This would be invalid.  Can you confirm that you have a value for both retry and timeout?  You can log this using:

```
cacti_log(('PINGCMD: chcp 437 && ping -w ' . $this->timeout . ' -n ' . $this->retries . ' ' . $this->host['hostname']);
```

You will then be able to filter for PINGCMD in your cacti log to see what is being used.
