### ISSUE TITLE
AUTOM8 does not create graphs on remote pollers 1.2.4

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#2887]
Hey All 

I am running 1.2.4 with remote pollers 
I notice that when you scan a IP block the devices will be added however the graphs are not created you need to go to the chosen remote poller select the devices and  run automation rules then the graphs are created

No errors are generated from the main poller and nothing in the logs at the remote poller indicate a reason why the graphs were not created 

The device template and rules are in both pollers as well

**Comment by cigamit** [comment]
Yea, I think you are right on this one.

**Comment by cigamit** [comment]
This was resolved in Cacti 1.2.5.  So, it's duplicate.

**Comment by bmfmancini** [comment]
Cool thanks

Which comit/bug number was this a duplicate of ?

**Comment by bmfmancini** [comment]
Sorry I should say which comkt was it fixed in ?
