### ISSUE TITLE
Long hostnames cause template filter to go off page

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#2888]
Hey Everyone 

I notice that when you have a long hostname in a tree that the page doesn't format properly
the template filter gets pushed off the page and you cant select anything

![image](https://user-images.githubusercontent.com/13388748/62798976-a1e8ae00-baad-11e9-8482-0a98a18205b3.png)

it seems after 40 or so characters this happens 

if you go to another tree without the long hostname the drop-down still doesn't appear you need to reload the page for it to show-up

Tested this on chrome,firefox

**Comment by bmfmancini** [comment]
same behaviour is seen in 1.2.5 
also with I.E

**Comment by bmfmancini** [comment]
to re-create create a device like so 
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by cigamit** [comment]
Is that with a device with a domain name, or just a device name?  What if we provide an option to strip domains?

**Comment by bmfmancini** [comment]
It's a combination of both

A device that shows the domain it would be cool if there would be an option
to strip the domain

I think it would be good if the tree could be frozen so it won't expand and
crunch out the right side of the window or something like that

**Comment by bmfmancini** [comment]
How about limiting how many characters are displayed in the tree ?

**Comment by netniV** [comment]
This is an issue that I raised a long while ago as it also should be resizable on the tree listing of the graphs.

**Comment by cigamit** [comment]
I think we should move the tree panels to flex layout since we don't care about IE10 any longer.  That'll fix this issue, and then we can simply set an overflow on the tree div.

**Comment by netniV** [comment]
That sounds like a plan, we should implement that feature in 1.3.

**Comment by bmfmancini** [comment]
Hey guys is still slated for 1.3 ?

**Comment by cigamit** [comment]
The only thing I would be willing to do is provide a strip domain setting in 1.2.x.  Above that, we have a number of major filter enhancements that we plan to make longer term that would accommodate wider columns and full filters on mobile devices.  That's all pretty far out right now due to all of our schedulers.

**Comment by bmfmancini** [comment]
The strip domain function would be awesome and in my case eliminate most of
the long names

**Comment by bmfmancini** [comment]
Poller replication is every 8 hours

**Comment by cigamit** [comment]
Long hostnames addressed here: https://github.com/Cacti/cacti/issues/3079

**Comment by cigamit** [comment]
I think this will be fully resolved in 1.2.8.  Due to the use of the new changes in the jquery ui select filter.
