### ISSUE TITLE
Question on upgrade procedure 

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#2889]
Hey guys 

Quick question 

On a multiple poller setup is the best way to upgrade the main poller then the rest or the remote pollers then the main poller ?

**Comment by cigamit** [comment]
Main poller always.  The remote pollers almost entirely self update.

**Comment by bmfmancini** [comment]
How do the remote pollers get the updated files does the main poller rsync
the files over ?

Sorry new to multiple poller upgrade process

**Comment by bmfmancini** [comment]
How do the remote pollers get the new files ?
Do they rsync between the main poller ?

**Comment by cigamit** [comment]
They are transferred through the resource cache.  Every website file is checked against a CRC and when the files change, they are reloaded into the resource cache, which the remote pollers then query and copy those files into their own environment.

**Comment by bmfmancini** [comment]
Awesome thank you so much
