### ISSUE TITLE
Allow external nologin access for Realtime Graphs

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#289]
It would be very useful to allow external nologin access to specific graph.
I would like to include this graph in website.

**Comment by ronytomen** [comment]
You can use the graph export plugin to export to a location for servicing.

**Comment by ronytomen** [comment]
I deleted my comment, as I didn't read the title... 

This could be very dangerous, as in multiple people hitting it causing high load on the system.

Also, not even the load on the server, but the load on the device being polled.  Access consolidation (as in a single stream to the device) would have to be implemented for this to be safe for devices.  And then some sort of consolidated realtime data stream that multiple users could access.

This probably needs to happen anyways... :)

**Comment by netniV** [comment]
The device in question wouldn't need to be polled just to produce the graph would it?  The data to produce the graph should be fairly local (ie, on the server or on the RRD server) even with a remote poller? Or have I misunderstood how that works?

**Comment by interduo** [comment]
If implemented correctly on www site there is no danger as You write. I need to put few graphs as a destination to buttons, so You need to click to see the graph and those graphs are in our CRM hosted only locally. Or it just needs to be limited on frontend www.

**Comment by netniV** [comment]
I think what @ronytomen is getting at is there is a difference between using a graph and a realtime graph.  

A realtime graph would poll the device in question constantly.  This results in a higher load on both the poller, device and network.  If there is no authentication done, that could and most likely would cause issues if many people were accessing the same realtime graph.  

An internal graph uses the standard resources to generate graphs which does not impact on the actual device, though may have some impact on cacti's host system if a long period was selected for time. So, whilst the impact is far less and the monitored device will not be hit, there are still resource implications.

If automatic login is desired, a user could be given a username/password and they could tick the "Keep Me Signed In" option which would then use Authenticate the user by cookie.  That user can be given access to one or more graphs.  When attempting to view a graph directly for the first time, the system will authenticate, but should show the graph in question.

If you needed to have a method to automatically log in to the system, such as from a TV that can't specify a username/password (except maybe in the URL), then you won't be able to make that work without re-writing a lot of the auth code to work off something like IP.

**Comment by netniV** [comment]
Would you definitely want realtime graphing though? Like I said, that puts pressure on the network device, and bypasses the local cached data.  Would you not prefer the normal graph you get on the Graphs tree?

**Comment by interduo** [comment]
I would like to include here a button "Realtime grapht" and after clicking It should popup realtime graph.
So my answer is Yes.

**Comment by netniV** [comment]
Does your CRM allow code to generate that link?  I'm just thinking about the security aspect, and also users who multiple-click on links.  Opening multiple real-time graphs to the same device would really not be advisable so if code could generate a use-once token, that would be better.

It would also mean allowing a "guest" user to view your graphs.  I am thinking a plugin would work better here as it would only provide the functionality to those who really want it, plus allow for the creation of a settings tab etc.

**Comment by interduo** [comment]
In my CRM I can define external device id and on that id I can generate link.
Only users with special privileges (technicans) can access that module.

In nomal work we have CRM and Cacti always opened so I think that if user is unlogged it should be login page.

**Comment by netniV** [comment]
Well, if the user is already logged into Cacti, then it should be just a case of getting the real time link from the side of the graphs.  Have you already tried that?

**Comment by interduo** [comment]
If this is a really big security issue problem then ok - guest access off.

**Comment by cigamit** [comment]
Resolved.  You would enable Realtime for the Guest account and then this will work as expected when calling graph_realtime.php.
