### ISSUE TITLE
unlink(/opt/IBM/cacti/cache/mibcache/mibcache.lock): No such file or directory in file: /opt/IBM/cacti/snmpagent_mibcachechild.php on line: 84

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/cacti#2890]
2019/08/12 14:06:37 - CMDPHP PHP ERROR WARNING Backtrace:  (/snmpagent_mibcachechild.php[84]:CactiErrorHandler())

2019/08/12 14:06:37 - ERROR PHP WARNING:  unlink(/opt/IBM/cacti/cache/mibcache/mibcache.lock): No such file or  directory in file: /opt/IBM/cacti/snmpagent_mibcachechild.php  on line:  84

related code: 
if($mibcache_changed !== NULL || file_exists($path_mibcache) === false ) {

The logic may use lock file instead of path 

Cacti 1.2.4 
FF 
rhel7 x64

**Comment by cigamit** [comment]
@yingbaiibm, looks like you have a packaging issue.  The cache directory, and it's children directories need to be owned by the website user.  There are four standard directories inside the cache directory, they are: mibcache, boost, realtime, and spikekill.
