### ISSUE TITLE
Script server script ss_fping.php generates error when not called by script server

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#2891]
**Describe the bug**
PHP ERROR: Class 'Net_Ping' not found in file: /var/www/html/cacti/scripts/ss_fping.php on line: 21

**To Reproduce**
1. cd /var/www/html/cacti/scripts/
2. exec 'php -q ss_fping.php'
3. Check cacti.log

**Comment by cigamit** [comment]
This should not be a problem when the ss_fping.php is called properly.  But I'll fix this anyway.
