### ISSUE TITLE
Visualize big amount of HFSC queues

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#2892]
**Is your feature request related to a problem? Please describe.**
I would like to visualize traffic from few 8k+ HFSC/HTB Queues.

**Describe the solution you'd like**
Don't know how to do that - so any way would be good. 

I have:
File from router with queue counters. The result of: `tc -s qdisc >> $file` command.

I expect to have:
One graph with two values (download&upload) with the same classid.

Did anybody try that?

**Comment by cigamit** [comment]
Better take that one up on the newly upgraded forums.
