### ISSUE TITLE
Database Information and Recommendations Incorrect when viewed from Remote Data Collectors

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#2894]
Hey Guys 

I see the following on RHEL7,Mariadb and cacti 1.2.5 

Seems like its just not picking up the variables unless I am doing something completely wrong 
not seeing the same issues on Ubuntu though 

MariaDB [(none)]>  show variables LIKE 'tmp_table_size';
+----------------+-----------+
| Variable_name  | Value     |
+----------------+-----------+
| tmp_table_size | 136314880 |
+----------------+-----------+
1 row in set (0.00 sec)

MariaDB [(none)]>  show variables LIKE 'join_buffer_size';
+------------------+----------+
| Variable_name    | Value    |
+------------------+----------+
| join_buffer_size | 33554432 |
+------------------+----------+
1 row in set (0.00 sec)

MariaDB [(none)]>  show variables LIKE 'innodb_large_prefix';
+---------------------+-------+
| Variable_name       | Value |
+---------------------+-------+
| innodb_large_prefix | ON    |
+---------------------+-------+
1 row in set (0.00 sec)

MariaDB [(none)]>  show variables LIKE 'innodb_buffer_pool_size';
+-------------------------+-----------+
| Variable_name           | Value     |
+-------------------------+-----------+
| innodb_buffer_pool_size | 262144000 |
+-------------------------+-----------+
1 row in set (0.00 sec)

Here is what Cacti reports its seeing 

![image](https://user-images.githubusercontent.com/13388748/62898816-67d51180-bd24-11e9-8783-1d80fefa979f.png)

Here is the config from Mariadb my.cnf

innodb_file_format = Barracuda
character_set_client = utf8mb4
max_allowed_packet = 16777777
join_buffer_size = 32M
innodb_file_per_table = ON
innodb_large_prefix = 1
innodb_buffer_pool_size = 250M
innodb_additional_mem_pool_size = 90M
innodb_flush_log_at_trx_commit = 2
max_heap_table_size = 150M
tmp_table_size = 130M
join_buffer_size = 250M
innodb_large_prefix = 1
innodb_buffer_pool_size = 2000M

**Comment by cigamit** [comment]
I have no idea what to make of that.

**Comment by bmfmancini** [comment]
Ok I found out whats going on here 

I have multiple pollers  a couple of the pollers have more memory than others so the recommendations for the poller with more memory is showing a higher recommendation 

when the remote poller is syncing with the main poller which has less memory the settings from the main poller are showing as the current values for the remote poller which is not actually the case in the config on the DB side

Should have a way so that the remote pollers will show their local values and not the main pollers values

**Comment by netniV** [comment]
It is simply a different database connection but I'm not sure if the installer does maintain both or just the one it's supposed to be working on...

**Comment by bmfmancini** [comment]
yeah it looks like the main poller will  show the recommended values bashed on the remote pollers hardware details

**Comment by cigamit** [comment]
Yea, that makes sense.  In the online mode, it's going to do that.  I'm okay labeling this a bug.
