### ISSUE TITLE
Percentile calculation is incorrect on Graphs with multiple Data Sources from different RRDs

### ISSUE THREAD

**Issue by TheBlueMatt** [Cacti/cacti#2895]
I have a nice graph which stacks sources from multiple RRDs (network interface traffic, in this case), and has another RRD that is, roughly, the total of the others (cause its an upstream network interface). Printing the Nth percentile for the total interface via  |95:bits:6:current:2| gives an incorrect result (notably, its different from a similar graph that only shows the one upstream network interface).

This appears to be because this doesn't do what it should: https://github.com/Cacti/cacti/blob/f5205ab7ff714ccb0c180e23d812ff2d5728896f/lib/graph_variables.php#L423.

If that line is changed to 
```
$local_data_array = array_intersect_key($local_data_array, array_flip(array($graph_item['local_data_id'])));
```
it all works fine. I didn't do this as a PR cause it looks like this should mean some of the other types (notably, likely, 'max') are also incorrect so this function probably needs a good clean read.

**Comment by cigamit** [comment]
I'm taking a slightly different approach on this one.

**Comment by cigamit** [comment]
Please test develop ASAP.  We are releasing over the weekend.

**Comment by TheBlueMatt** [comment]
I manually applied the patch from 2925f69326cda4d35cd605f0b245a428e48a70de but it doesnt seem to fix it. Ultimately, the issue is that the other RRDs need to *not* be in the array, instead of appending them to the array, otherwise nth_percentile considers them all in its calculations. The new patch in dev doesn't actually ever remove anything from the array, which is wrong.

**Comment by cigamit** [comment]
Okay, let me take a closer look then.  Can you describe your use case again in a bit more detail?  Appreciate your quick response.

**Comment by TheBlueMatt** [comment]
This is the graph template in question. There are four separate interfaces, three downstream and one upstream being graphed, each has an traffic_in and traffic_out part. Thus, it pulls from 6 separate RRDs.
![Template](https://user-images.githubusercontent.com/649246/64046949-d86d9200-cb5c-11e9-9fac-ea706ee3f873.png)

**Comment by TheBlueMatt** [comment]
Huh? I see no evidence this is closed?

**Comment by cigamit** [comment]
Having things in context helps.  Please check the latest commit.

**Comment by cigamit** [comment]
After committing yesterday, I found that I missed the array format.  So, did another commit this morning.

**Comment by TheBlueMatt** [comment]
Current master works for one half of the graph - because there are two values pulled from each RRD (traffic_in and traffic_out) the resulting array needs to contain both, otherwise it later assumes both were calculated and goes looking for the cached copy (which wasn't, actually, calculated).

**Comment by cigamit** [comment]
Just decided to go with your solution.  It makes sense.
