### ISSUE TITLE
Question about Y-axis units

### ISSUE THREAD

**Issue by yujw668** [Cacti/cacti#2898]
Question about Y-axis units
Automatic carry

For example, after 1000u (subtle), it will display 1m (milliseconds).
 
Now, I have checked that the unit used for monitoring is U subtle. Since it is 1000 microseconds, ![image](https://user-images.githubusercontent.com/54139993/63091016-a3274880-bf8f-11e9-81a8-f7f5979ab181.png)
then it automatically becomes a millisecond m unit. The figure below is what I zoomed in.
![image](https://user-images.githubusercontent.com/54139993/63091039-b803dc00-bf8f-11e9-9fe8-c72e1f7aa333.png)

I modified the following values to not work,
![image](https://user-images.githubusercontent.com/54139993/63174240-21f5b180-c074-11e9-8280-68072e8cfb87.png)

I hope that after 1000u (subtle), it also shows the unit of u, for example, 2000u, 3000u instead of 2m, 3m (milliseconds) of the carry. Which parameter should I adjust?

**Comment by cigamit** [comment]
You should ask this question on the RRDtool user board or on the Cacti forums.  You should consider upgrading.  That looks like Cacti 0.8.7 or 0.8.6.
