### ISSUE TITLE
Aggregate Graphs - query_ifAlias

### ISSUE THREAD

**Issue by smiles1969** [Cacti/cacti#290]
I use the variable |query_ifAlias| as a prefix to the graphs I add to an aggregate. It appears that if the alias contains parens, they are not being escaped properly, or otherwise handled correctly when passed to RRDtool.

![image](https://cloud.githubusercontent.com/assets/17500126/22836268/49df3110-ef81-11e6-9095-1a99fb782ff3.png)

![image](https://cloud.githubusercontent.com/assets/17500126/22836284/59f10790-ef81-11e6-8aef-8603fa247084.png)

Not sure where this is being handled in the code or I would attempt a pull request.

**Comment by smiles1969** [comment]
Another thing I noticed that was odd about this is the Watermark text showing for the first line item.

This does not show when I use |query_ifName| or |query_ifDescr|

**Comment by SoNix21** [comment]
Check my bug : #286

**Comment by smiles1969** [comment]
The more I look at this, it may be the dashes or forward slashes it's having issues with and not the parens.

**Comment by smiles1969** [comment]
Was able to work around this by inserting:

$txt_graph_item = preg_replace('/&/','',$txt_graph_item);

at line 2269 in lib/rrd.php

Don't want to do a pull request on this as I'm not sure what else that could break.

**Comment by pautiina** [comment]
I think that is not problem. When you crete Aggregate Graphs you can use several different resources, and the right to choose which query_ifAliyas not possible

**Comment by smiles1969** [comment]
Escaping (or removing like I did as a workaround) the ampersand was most definitely the problem, and you can use ifAlias in your graph prefixes, as well as any of the other supported |query| strings.

![image](https://cloud.githubusercontent.com/assets/17500126/22847453/8f0087cc-efb2-11e6-86d6-bb0902f5c26f.png)

![image](https://cloud.githubusercontent.com/assets/17500126/22847489/ca61ff08-efb2-11e6-8280-e4f3e3992624.png)

**Comment by cigamit** [comment]
Resolved, thanks for reporting!

**Comment by smiles1969** [comment]
Thanks Cigamit!
