### ISSUE TITLE
Cacti 1.0.0 installer requires PHP LDAP extension, contrary to docs

### ISSUE THREAD

**Issue by mhoran** [Cacti/cacti#291]
The Cacti 1.0.0 [installer](https://github.com/Cacti/cacti/blob/6704d419cf9cbd628b7d62a30637313e3f3e984d/install/index.php#L573) requires the PHP LDAP extension, which is contrary to a note in the docs which states that LDAP is only required when using [LDAP Authentication](https://github.com/Cacti/cacti/blob/190ca292caeeb89d2d04f2f30ce84c2301fa22a1/docs/build/manual.sgml#L207).

This is contrary to previous versions of Cacti, where the PHP LDAP extension was actually optional. I'd prefer not to install the PHP LDAP extension on my server along with all its dependencies if not actually required.

**Comment by cigamit** [comment]
Resolved.
