### ISSUE TITLE
Can not show user menu when in portrait mode on mobile devices

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#2910]
**Describe the bug**
user_menu cannot be displayed in portrait mode on mobile device when current-top-tab is collapsed due to width of device.
In landscape mode,  user_menu can be display by clicking current-top-tab again when current-top-tab is displayed.

**To Reproduce**
1. Assume user menu exist  under  top-tab 'TabU' .
2. Use mobile device, or resize browser width. And ensure 'TabU' are collapsed.
3. Click Graph tab(Tree mode is default)
4. Show graphs by column
5. Click Graph tab again
6. Move main page to right, and show graph tree
7. Click 'down arrow' --> 'TabU'
8. Show a page. 
9. Click 'down arrow' --> 'TabU' again
10. Reload page(see error)

**Expected behavior**
* Expect  Step#9 show user menu like Step#5.
Note:
  * Step#2 and step#4 click 'Console' have same result: show menu
  * If browser or device width is enough to show 'TabU', the 2nd click can also display user menu.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome with DevTool toggle device toolbar 
 - Version 76

**Smartphone (please complete the following information):**
 - Device: Pixel 2 XL
 - OS: Android 10
 - Browser Chrome
 - Version 76

**Comment by cigamit** [comment]
This should be good to go now.
