### ISSUE TITLE
No rrd file created after executed poller (cacti 1.2.5)

### ISSUE THREAD

**Issue by tantantan666** [Cacti/cacti#2911]
When I add graph of interfaces for new added device , I got the error message below , and there isn't any rrd file created:

CMDPHP PHP ERROR WARNING Backtrace: (/graph.php[538]:rrdtool_function_graph(), /lib/rrd.php[1527]:variable_nth_percentile(), /lib/graph_variables.php[432]:nth_percentile(), /lib/graph_variables.php[33]:json_decode(), CactiErrorHandler())
2019/08/23 23:54:10 - ERROR PHP WARNING: json_decode() expects parameter 1 to be string, array given in file: /var/www/html/cacti/lib/graph_variables.php on line: 33
2019/08/23 23:54:10 - CMDPHP PHP ERROR NOTICE Backtrace: (/graph.php[538]:rrdtool_function_graph(), /lib/rrd.php[1527]:variable_nth_percentile(), /lib/graph_variables.php[432]:nth_percentile(), /lib/graph_variables.php[33]:rrdtool_function_stats(), /lib/graph_variables.php[103]:CactiErrorHandler())
2019/08/23 23:54:10 - ERROR PHP NOTICE: Undefined offset: 152 in file: /var/www/html/cacti/lib/graph_variables.php on line: 103
2019/08/23 23:54:10 - CMDPHP PHP ERROR NOTICE Backtrace: (/graph.php[538]:rrdtool_function_graph(), /lib/rrd.php[1527]:variable_nth_percentile(), /lib/graph_variables.php[432]:nth_percentile(), /lib/graph_variables.php[33]:rrdtool_function_stats(), /lib/graph_variables.php[84]:CactiErrorHandler())
2019/08/23 23:54:10 - ERROR PHP NOTICE: Undefined variable: fetch_array in file: /var/www/html/cacti/lib/graph_variables.php on line: 84

Does anyone met this before ?

/bin/rrdtool graph - 
--imgformat=PNG 
--start='-86400' 
--end='-300' 
--pango-markup 
--title='04AC15-WORK-SWITCH - Traffic - F131 ' 
--vertical-label='bits per second' 
--slope-mode 
--base=1000 
--height=200 
--width=700 
--rigid 
--alt-autoscale-max 
--lower-limit='0' 
COMMENT:"From 2019/08/23 00:15:24 To 2019/08/24 00:10:24\c" 
COMMENT:" \n" 
--color BACK#F3F3F3 
--color CANVAS#FDFDFD 
--color SHADEA#CBCBCB 
--color SHADEB#999999 
--color FONT#000000 
--color AXIS#2C4D43 
--color ARROW#2C4D43 
--color FRAME#2C4D43 
--border 1 --font TITLE:11:'Arial' 
--font AXIS:8:'Arial' 
--font LEGEND:8:'Courier' 
--font UNIT:8:'Arial' 
--font WATERMARK:6:'Arial' 
--slope-mode 
--watermark 'Generated by Cacti®' 
DEF:a='/var/www/html/cacti/rra/04ac15-work-switch_traffic_in_152.rrd':'traffic_in':AVERAGE 
DEF:b='/var/www/html/cacti/rra/04ac15-work-switch_traffic_in_152.rrd':'traffic_out':AVERAGE 
CDEF:cdefa='a,8,' 
CDEF:cdeff='b,8,' 
LINE1:cdefa#00CF00FF: 
AREA:cdefa#00CF007F:'Inbound ' 
GPRINT:cdefa:LAST:'Current:%8.2lf %s' 
GPRINT:cdefa:AVERAGE:'Average:%8.2lf %s' 
GPRINT:cdefa:MAX:'Maximum:%8.2lf %s\n' 
LINE1:cdeff#002A97FF: 
AREA:cdeff#002A977F:'Outbound' 
GPRINT:cdeff:LAST:'Current:%8.2lf %s' 
GPRINT:cdeff:AVERAGE:'Average:%8.2lf %s' 
GPRINT:cdeff:MAX:'Maximum:%8.2lf %s\n' 
COMMENT:' \n' 
HRULE:0#FF0000FF:'95th Percentile' 
COMMENT:'(0 mbit in+out)'
RRDtool Says:
ERROR: opening '/var/www/html/cacti/rra/04ac15-work-switch_traffic_in_152.rrd': no such file or directory .

Environment:
 CENTOS 7
 Cacti 1.2.5
 RRDTOOL 1.4.8

**Comment by netniV** [comment]
At first I thought this was releated to #2512 but that was an undefined variable rather than your case of an array being passed instead of a string.

**Comment by cigamit** [comment]
Please update lib/graph_variables.php and see if you can reproduce this error.
