### ISSUE TITLE
Selection "Graph type" not saved and restored after going to page two

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#2913]
**Describe the bug**
UI little bug.

**To Reproduce**
https://cacti/graphs_new.php
1. Change "Select a Graph Type to Create" to IN/OUT Unicast Packets
2. Change page = 2.
3. The selection of type graph type doesn't save&restrore.

**Expected behavior**
After going to page two, selection "Graph type" should be firstly saved and restored after page loaded.

**Comment by cigamit** [comment]
@interduo, this should be resolved now.  However, the saving of the session only happens when you create the first graph for the data query in question.  So, create a graph of a graph type on page 1, then goto page 2, and the setting will be retained.
