### ISSUE TITLE
Automated variable %port_description in graph-names

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#2914]
**Is your feature request related to a problem? Please describe.**
When we modify port configuration for example "change port description". We need to change graph title. This is useless work in my opinion that should be done by polling script not only when adding graphs.

**Describe the solution you'd like**
Simple variable "%port_description" that we could put into graph title.
The variable should be changed to 'ALIAS (IF-MIB)' after every polling cycle.

**Comment by cigamit** [comment]
This should be automatic if you set the suggested name to ifAlias and select verify all fields.  However, it's a lot of overhead to reindex every polling cycle.  Best let AUTOM8 do it for you and deal with the lag.

**Comment by interduo** [comment]
It could be verified for example 1/day or on-demand if it's a very much work to do like You said but we don't want to do this by hand.

> Best let AUTOM8 do it for you and deal with the lag.

You need to write more about it because I don't see the oportunity there.

**Comment by cigamit** [comment]
Here is the process:

1) Setup all of your management networks for discovery
2) In the discovery network definition set to re-index devices (those already in cacti that are found)
3) Save and watch what happens on next discovery.

That's one way to do it.  Otherwise, we need some feature, as you mentioned to periodically re-index devices.  I would make it a device level setting, something like 'Auto Re-index interval as a dropdown.

**Comment by interduo** [comment]
For a manual temporary workaround for this problem I suggest to use:
 https://www.cacti.net/downloads/docs/html/cli_poller_reindex_hosts.html

`php ./cli/poller_reindex_hosts.php --id=51`

**Comment by cigamit** [comment]
Yea that would do it.  If you do this by cron from time to time, this will not impact the poller.

**Comment by interduo** [comment]
No it isn't working finally. Just my firiend catch and change hosts where I was testing.

I tried
`php ./cli/poller_reindex_hosts.php --id=all`
`rebuild_poller_cache.php`

So I have got no idea how to do some mass reindex.

**Comment by cigamit** [comment]
Upload some screen captures.

**Comment by interduo** [comment]
![reindex1](https://user-images.githubusercontent.com/17087236/65589712-c62f1a00-df89-11e9-8dae-09792443dcf6.png)

![reindex2](https://user-images.githubusercontent.com/17087236/65590764-9b45c580-df8b-11e9-8935-342d98c63652.png)

**Comment by cigamit** [comment]
Well, goto the Console > Management > Data Sources and search for orphans.  Then, for those orphans, can you identify the Data Template for them for us?  It might be a poorly written Data Query, like the 'running process' Host MIB template, which should be put down the Cacti memory hole.  It's a bad template.  Let us know if there is a theme with these orphans.

**Comment by interduo** [comment]
I removed orphaned data sources but the count of 83 Devices still exists.

**Comment by interduo** [comment]
For debuging in log there shoud be ID of broken data source when there is need to reindex.

**Comment by RustedKnight** [comment]
fyi, we use |query_ifAlias| in our graph templates as part of the graph title. It auto updates just fine for us every time the device is re-indexed.

For example, we use the following line as the graph title in our bits/sec graph template and it gives us the host name, port identification, and description and updates on each re-index. Of course we have automation set to run on index change.
|host_description| - Traffic - |query_ifDescr| - |query_ifAlias|

**Comment by netniV** [comment]
In that case, I'm going to close this as it's not an actual bug right now.
