### ISSUE TITLE
Your Cacti Server v1.2.5 has been installed/updated with errors

### ISSUE THREAD

**Issue by ketechsupport** [Cacti/cacti#2915]
Hi team,
For the first time I had an issue when updating my Cacti server:

This is the error text:

ALTER TABLE poller_output_realtime DROP PRIMARY KEY, ADD PRIMARY KEY (local_data_id, rrd_name, time, poller_id)

The other two operations went well:

UPDATE graph_local AS gl INNER JOIN graph_templates_item AS gti ON gti.local_graph_id = gl.id INNER JOIN data_template_rrd AS dtr ON gti.task_item_id = dtr.id INNER JOIN data_local AS dl ON dl.id = dtr.local_data_id SET gl.snmp_query_id = dl.snmp_query_id, gl.snmp_index = dl.snmp_index WHERE gl.graph_template_id IN (SELECT graph_template_id FROM snmp_query_graph) AND gl.snmp_query_id = 0 | [Success]
-- | --
  | UPDATE graph_local AS gl INNER JOIN ( SELECT DISTINCT local_graph_id, task_item_id FROM graph_templates_item ) AS gti ON gl.id = gti.local_graph_id INNER JOIN data_template_rrd AS dtr ON gti.task_item_id = dtr.id INNER JOIN data_template_data AS dtd ON dtr.local_data_id = dtd.local_data_id INNER JOIN data_input_fields AS dif ON dif.data_input_id = dtd.data_input_id INNER JOIN data_input_data AS did ON did.data_template_data_id = dtd.id AND did.data_input_field_id = dif.id INNER JOIN snmp_query_graph_rrd AS sqgr ON sqgr.snmp_query_graph_id = did.value SET gl.snmp_query_graph_id = did.value WHERE input_output = 'in' AND type_code = 'output_type' AND gl.graph_template_id IN (SELECT graph_template_id FROM snmp_query_graph) | [Success]

There is not other log available.

Any suggestions?

Thanks,

Jens Brinch

**Comment by netniV** [comment]
You can find the logs in the cacti log.  Unfortunately, there was a bug that meant the installation wizard failed to display the filtered log properly.

**Comment by netniV** [comment]
Oh and the above error was due to https://github.com/Cacti/cacti/issues/2836
