### ISSUE TITLE
Security Scan Report

### ISSUE THREAD

**Issue by andermat8** [Cacti/cacti#2916]
Attaching a security scan.  I did one of these a while back and it seemed to be appreciated.  This is for version 1.1.38 but it will probably apply to the current version as well.  I suggest renaming the attachment from .txt to .html for better format and reading.  Please let me know if this can be addressed in a future release or patch.

Thanks!

[Cacti Security Scan.txt](https://github.com/Cacti/cacti/files/3556835/Cacti.Security.Scan.txt)

**Comment by netniV** [comment]
tbh, we have already fixed a number of things raised by a previous 1.1.38 security report but we will review what you have anyway.  These kinds of reports are always best against the latest version of the software so that we can be sure if we have corrected them or not.

**Comment by TheWitness** [comment]
Took a cursory look as well.  Best rerun this on 1.2.6.

**Comment by bmfmancini** [comment]
Yea most of these have been fixed I run Burpsuite and ZAP and they have come back with nothing on 1.2.4 and 1.2.5

**Comment by cigamit** [comment]
That's what I like to hear.  Hey, you should run against develop when you get a chance.  We are releasing 1.2.6 this weekend!!!

**Comment by bmfmancini** [comment]
Sweet will do!

**Comment by netniV** [comment]
Correction, 1.2.x not develop.  Develop is still 1.2.5 until we merged 1.3 into it this weekend.

**Comment by andermat8** [comment]
I have 1.2.5 in my lab.  I'll get the Security Team to run a scan on it and let you know what we find.

Thanks for the quick response!
