### ISSUE TITLE
cacti 1.2.6 dev security qualsys security report

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#2918]
Looking good guys !

Scan passes easily let me know in the future if you want these scans !
this scan is on the dev branch ahead of this weekends 1.2.6 release !

[Cacti_qualsys_aug29_1.2.6-dev.html.txt](https://github.com/Cacti/cacti/files/3558008/Cacti_qualsys_aug29_1.2.6-dev.html.txt)

Rename the file to .html to read it

**Comment by netniV** [comment]
Dev or 1.2.x? 1.2.x is the release coming this weekend as this weekend 1.3 will be merged into develop.
