### ISSUE TITLE
When refreshing menu, selected items are sometimes lost and submenu items can become hidden

### ISSUE THREAD

**Issue by YongBoLiu** [Cacti/cacti#2919]
**Describe the bug**
Add a  jquery tabs in the cacti console page, change the skin to paper plane or paw, the labels on tabs can not see clear, it's all black as the background colour.

**To Reproduce**
1. Add a   jquery tabs in the cacti console page. The widget tabs from https://jqueryui.com/tabs/
2. Change the skin to paper plane or paw.
3. Check the tabs in the console page.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/12453888/64005036-16a98800-cb42-11e9-815e-7a286efb0dce.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
It seems the paper-plane and paw not compatible with the jquery css below, better to change the color a little.

./include/themes/paper-plane/jquery-ui.css
``
.ui-state-active a:visited {
        color: #212121;
        text-decoration: none;
}

**Comment by YongBoLiu** [comment]
![issue1](https://user-images.githubusercontent.com/12453888/64005736-8e2be700-cb43-11e9-9304-e50294287a6b.png)
re-attach the image of screen shot.

**Comment by YongBoLiu** [comment]
The test code changeset is below, which from [https://jqueryui.com/tabs/](url)

``#diff -u . /pcc/dev/dev14/yboliu/my_git/cacti/cacti/index.php
--- ./index.php	2019-08-30 15:58:30.364925017 +0800
+++ /pcc/dev/dev14/yboliu/my_git/cacti/cacti/index.php	2019-08-30 15:29:10.364501000 +0800
@@ -58,6 +58,23 @@
 
 if (read_config_option('hide_console') != 'on') {
 ?>
+<div id="itabs">
+  <ul>
+    <li><a href="#tabs-1">Nunc tincidunt</a></li>
+    <li><a href="#tabs-2">Proin dolor</a></li>
+    <li><a href="#tabs-3">Aenean lacinia</a></li>
+  </ul>
+  <div id="tabs-1">
+    <p>Proin elit arcu, rutrum commodo, vehicula tempus, commodo a, risus. Curabitur nec arcu. Donec sollicitudin mi sit amet mauris. Nam elementum quam ullamcorper ante. Etiam aliquet massa et lorem. Mauris dapibus lacus auctor risus. Aenean tempor ullamcorper leo. Vivamus sed magna quis ligula eleifend adipiscing. Duis orci. Aliquam sodales tortor vitae ipsum. Aliquam nulla. Duis aliquam molestie erat. Ut et mauris vel pede varius sollicitudin. Sed ut dolor nec orci tincidunt interdum. Phasellus ipsum. Nunc tristique tempus lectus.</p>
+  </div>
+  <div id="tabs-2">
+    <p>Morbi tincidunt, dui sit amet facilisis feugiat, odio metus gravida ante, ut pharetra massa metus id nunc. Duis scelerisque molestie turpis. Sed fringilla, massa eget luctus malesuada, metus eros molestie lectus, ut tempus eros massa ut dolor. Aenean aliquet fringilla sem. Suspendisse sed ligula in ligula suscipit aliquam. Praesent in eros vestibulum mi adipiscing adipiscing. Morbi facilisis. Curabitur ornare consequat nunc. Aenean vel metus. Ut posuere viverra nulla. Aliquam erat volutpat. Pellentesque convallis. Maecenas feugiat, tellus pellentesque pretium posuere, felis lorem euismod felis, eu ornare leo nisi vel felis. Mauris consectetur tortor et purus.</p>
+  </div>
+  <div id="tabs-3">
+    <p>Mauris eleifend est et turpis. Duis id erat. Suspendisse potenti. Aliquam vulputate, pede vel vehicula accumsan, mi neque rutrum erat, eu congue orci lorem eget lorem. Vestibulum non ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce sodales. Quisque eu urna vel enim commodo pellentesque. Praesent eu risus hendrerit ligula tempus pretium. Curabitur lorem enim, pretium nec, feugiat nec, luctus a, lacus.</p>
+    <p>Duis cursus. Maecenas ligula eros, blandit nec, pharetra at, semper at, magna. Nullam ac lacus. Nulla facilisi. Praesent viverra justo vitae neque. Praesent blandit adipiscing velit. Suspendisse potenti. Donec mattis, pede vel pharetra blandit, magna ligula faucibus eros, id euismod lacus dolor eget odio. Nam scelerisque. Donec non libero sed nulla mattis commodo. Ut sagittis. Donec nisi lectus, feugiat porttitor, tempor ac, tempor vitae, pede. Aenean vehicula velit eu tellus interdum rutrum. Maecenas commodo. Pellentesque nec elit. Fusce in lacus. Vivamus a libero vitae lectus hendrerit hendrerit.</p>
+  </div>
+</div>
 <table class='cactiTable'>
 	<tr class='tableRow'>
 		<td class='textAreaNotes top left'>
@@ -103,6 +120,7 @@
 ?>
 <script type='text/javascript'>
 $(function() {
+	$('#itabs').tabs();
 	resizeWindow();
 	$(window).resize(function() {
 		resizeWindow();

**Comment by YongBoLiu** [comment]
How about change the color of '.ui-state-active a:visited',  from #212121 to  #FFFFFF ? This we can see the labels clearly in paper-plane skin.

**Comment by cigamit** [comment]
Please review and see what you think.

**Comment by YongBoLiu** [comment]
The fix works well in my Env. Thank you!
