### ISSUE TITLE
Undefined variable 'result' in lib/data_query.php

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#2922]
**Describe the bug**

```
2019/09/03 13:05:35 - CMDPHP PHP ERROR NOTICE Backtrace: (/poller_commands.php[139]:run_data_query(), /lib/data_query.php[130]:CactiErrorHandler())
--
2019/09/03 13:05:35 - ERROR PHP NOTICE: Undefined variable: result in file: /var/www/html/cacti/lib/data_query.php on line: 130
```

I get this from time to time but I cannot reproduce this by hand.

**Comment by cigamit** [comment]
Are you using the WMI plugin by chance?

**Comment by interduo** [comment]
> Are you using the WMI plugin by chance?

No.

**Comment by cigamit** [comment]
This should be resolved in the 1.2.x branch.  But I'm concerned.  Can you tell me about the Data Query?  Share an export of the entire device template?

**Comment by interduo** [comment]
Thanks for resolving this issue.

> Can you tell me about the Data Query?

Yes, what do You would like to know?

> Share an export of the entire device template?

Yes - how to do the export?

**Comment by cigamit** [comment]
I only need the one in question that was generating this error.  The path that you were going should never have been followed, and that is concerning.  It's for a data query data input method type that does not exist.

That section of the code if reserved for plugins that define their own data input types, and the only plugin that I know of right now  is the WMI plugin.

**Comment by cigamit** [comment]
I'm going to close.  If you want, just dump your databbase and email it to developers@cacti.net
