### ISSUE TITLE
Cacti 1.2.6 Boost messeges in log

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#2923]
Hey Guys 

I notice that in 1.2.6 that suddenly Boost related info is going into the log that advises all of the DS it is updating 

```
2019/09/02  23:44:10 - BOOST NOTE: Updating Local Data Id:'667',  Template:traffic_in:traffic_out, Output: 1567480502:0:146956114  1567480562:0:146961080 1567480622:0:146967237 1567480682:0:146973226  1567480741:0:146978756 1567480802:0:146983781 1567480862:0:146988747  1567480922:0:146993649 1567480982:0:146999175 1567481043:0:147004981  1567481101:0:147010264 1567481161:0:147017292 1567481222:0:147022362  1567481282:0:147027264 1567481342:0:147032413 1567481401:0:147037626  1567481461:0:147043620 1567481522:0:147048981 1567481581:0:147054891  1567481642:0:147059961 1567481702:0:147064863 1567481762:0:147069765  1567481821:0:147074544 1567481882:0:147081276 1567481942:0:147086682  1567482002:0:147092592 1567482062:0:147098037 1567482121:0:147103250  1567482181:0:147108340 1567482242:0:147113365
2019/09/02 23:44:10 - BOOST NOTE: Updating Local Data Id:'666',  Template:traffic_in:traffic_out, Output: 1567480502:23312857:945979993  1567480562:23313619:946008407 1567480622:23314381:946039976  1567480682:23315143:946069304 1567480741:23315905:946100710  1567480802:23316825:946134269 1567480862:23317587:946164041  1567480922:23318349:946195650 1567480982:23319111:946232177  1567481043:23319873:946293252 1567481101:23320635:946321314  1567481161:23321397:946351510 1567481222:23322159:946381429  1567481282:23322921:946411707 1567481342:23323683:946442749  1567481401:23324445:946472162 1567481461:23325207:946502278  1567481522:23325969:946534310 1567481581:23326731:946568783  1567481642:23327493:946631889 1567481702:23328255:946661178  1567481762:23329017:946691477 1567481821:23329779:946721489  1567481882:23330541:946751506 1567481942:23331303:946784586  1567482002:23332065:946814375 1567482062:23332827:946842389  1567482121:23333589:946872149 1567482181:23334351:946907912  1567482242:23335113:946966482
```

I think this is a resurface of https://github.com/Cacti/cacti/issues/1257

Here is my DB info 
```
MariaDB [cacti]> SELECT name,value FROM settings WHERE name in ('boost_rrd_update_enable', 'boost_rrd_update_system_enable');
+--------------------------------+-------+
| name                           | value |
+--------------------------------+-------+
| boost_rrd_update_enable        | on    |
| boost_rrd_update_system_enable | on    |
+--------------------------------+-------+
2 rows in set (0.00 sec)

MariaDB [cacti]> 
```

This is the old DB info 

```
MariaDB [cactiold]> SELECT name,value FROM settings WHERE name in ('boost_rrd_update_enable', 'boost_rrd_update_system_enable');
+--------------------------------+-------+
| name                           | value |
+--------------------------------+-------+
| boost_rrd_update_enable        | on    |
| boost_rrd_update_system_enable | on    |
+--------------------------------+-------+
2 rows in set (0.00 sec)

MariaDB [cactiold]> 
```

but the boost logs were never coming into the main cacti log before aside from boost stats

Here is my logging setup

![image](https://user-images.githubusercontent.com/13388748/64191011-8ae77280-ce45-11e9-956c-145b4f444c09.png)

Boost settings

![image](https://user-images.githubusercontent.com/13388748/64191040-9e92d900-ce45-11e9-9e72-e9dd19eaaa92.png)

**Comment by cigamit** [comment]
You must be running poller_boost.php by hand using the '--debug' flag.  That message will only occur when you either set logging to medium or you launch poller_boost.php using debug.  However, it could also happen if the setting 'path_boost_log', the setting on the bottom is set to something over than blank, which in your case, it's not.  So, I would do the following:

```sql
SELECT value, length(value) FROM settings WHERE name='path_boost_log'
```

Post the output to that command and let's see if there might be a problem there.

**Comment by netniV** [comment]
I am assuming you don't have a device in debug mode at the moment?

**Comment by bmfmancini** [comment]
@netniV  I will double check 
@cigamit  I will run this and get back asap

**Comment by bmfmancini** [comment]
@netniV no device in debug mode that I can see 

@cigamit  here is the DB output

MariaDB [(none)]> use cacti
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [cacti]> SELECT value, length(value) FROM settings WHERE name='path_boost_log';
+-------+---------------+
| value | length(value) |
+-------+---------------+
|       |             0 |
+-------+---------------+
1 row in set (0.00 sec)

MariaDB [cacti]>

**Comment by bmfmancini** [comment]
Ok so weird enough the messages have stopped  weird but ok I will keep an eye out for now

**Comment by netniV** [comment]
I will close this for now then until you can repeat the situation.
