### ISSUE TITLE
Cacti 1.2.6 failed to update graph.

### ISSUE THREAD

**Issue by broxio** [Cacti/cacti#2926]
**Describe the bug**
Navigate to single graph item and try to update description as picture and SAVE button , then cacti show up error 

(/graphs.php[45]:validate_graph_request_vars(), /graphs.php[1818]:validate_store_request_vars(), /lib/html_utility.php[682]:die_html_input_error(), /lib/html_validate.php[64]:cacti_debug_backtrace())
Validation error for variable host_id with a value of xxxxxx . See backtrace below for more details.

**To Reproduce**
 -  Go to 'Console > Management > Devices > Graph List > Pick the graph and try to edit and save"

**Expected behavior**
- Updated description of graph.

**Screenshots**
###figure1 
<img width="1219" alt="Screen Shot 2562-09-05 at 17 26 13" src="https://user-images.githubusercontent.com/195177/64330652-ea8b7c80-d003-11e9-9bb5-b1f78c4f4793.png">

###Figure2
<img width="816" alt="Screen Shot 2562-09-05 at 17 24 24" src="https://user-images.githubusercontent.com/195177/64330703-0000a680-d004-11e9-8254-5eeff943c455.png">

**Desktop (please complete the following information):**
 - OS: macOS (Mojave) / Ubuntu 18.04 LTS
 - Browser Opera
 - Version Opera 62 macOS (Mojave)

**Additional context**
Happen after update from 1.2.4 to 1.2.6 , Cacti is manual install from source on Ubuntu 16.04 LTS

Cacti-info
Date | Thu, 05 Sep 2019 17:30:44 +0800
Cacti Version | 1.2.6
Cacti OS | unix
RSA Fingerprint | f1:b2:0a:ac:1a:2f:9e:97:f9:da:4c:70:1a:bc:15:f4
NET-SNMP Version | NET-SNMP version: 5.7.3
RRDtool Version Configured | 1.6.0+
RRDtool Version Found | 1.6.0
Devices | 805
Graphs | 9934
Data Sources | Script/Command: 10SNMP Get: 1082SNMP Query: 6497Script Query: 66Script Server: 28Script Query - Script Server: 778Total: 8461

**Comment by netniV** [comment]
What was the value of host_id? I am assuming it was not an integer.

**Comment by cigamit** [comment]
Okay, it was ugly, but I have resolved this one.  Please pull the latest graphs.php from branch 1.2.x and give it a shot.

**Comment by broxio** [comment]
I had pull from 1.2.x and it resolved the issue.

**Comment by bmcintosh** [comment]
Hey Guys - I am really new to Cacti - can you share some step-by-step details on how to solve this issue? i am having the same issue. Really appreciate.

**Comment by shakilahmed13** [comment]
Hi could you please provide more details . Having the same problem 

<img width="804" alt="Untitled" src="https://user-images.githubusercontent.com/55801592/65615196-c73c6780-dfda-11e9-8a10-f425765cfd9a.png">

**Comment by cigamit** [comment]
You can wait for 1.2.7 released this weekend, or download the branch 1.2.x right now.  Either way, it'll be fixed real soon.
