### ISSUE TITLE
Some graphs not displaying data for redhat/centos 7 machines

### ISSUE THREAD

**Issue by Givo29** [Cacti/cacti#2928]
**Describe the bug**
I have found that the interface traffic graphs are not displaying the `traffic_out` data for redhat/centos 7 machines.

**Expected Behaviour**
The `traffic_out` data should be graphing on centos7 machines however it is only showing the inbound traffic for these machines.

Steps taken to resolve this along with more information about the issue can be found at #2641

**Comment by cigamit** [comment]
Yea, I just saw your issue.  On your Traffic Out, the minimal heartbeat is set to 120, even though the step is 300 (5 minutes).  Wished I had seen that before.  Sorry about that.  Actually, I'm not certain how that happened actually.

Was this system upgraded from a 0.8.x version?

To fix, you simply have to tune the RRDfiles using:

```console
rrdtool tune filename --heartbeat traffic_out:600
```

Then, goto your database and run the following:

```sql
SELECT rrd_heartbeat, data_source_name, count(*) AS totals FROM data_template_rrd GROUP BY rrd_heartbeat, data_source_name;
```

If you find a bunch with 'traffic_out' that are set to 120, then you should update using the following:

```sql
UPDATE data_template_rrd SET rrd_heartbeat=600 WHERE data_source_name='traffic_out' AND rrd_heartbeat=120;
```

Got it?

**Comment by cigamit** [comment]
Next we have to find out how this happened.  Make sure you tell me if this is a new install or an upgrade.  Also let me know if you've been changing data collection frequencies for some of your data sources.

**Comment by Givo29** [comment]
Thanks, tuning the rrd files worked!  

Regarding your questions:  
- This build of cacti was an upgrade from `0.8.7f` to `1.2.2`.
- Some of the data collection frequencies were played with before the system upgrade happened, we think this was the cause of the issue.

**Comment by cigamit** [comment]
Okay, great.  I'll close then.  Thanks again for your patience.
