### ISSUE TITLE
Blank CDEFs and other objects on clean install of 1.0.2

### ISSUE THREAD

**Issue by reubenfarrelly** [Cacti/cacti#293]
This doesn't seem quite right for a clean install:

<img width="1402" alt="blank-cdefs" src="https://cloud.githubusercontent.com/assets/8552189/22865210/697a0156-f1b3-11e6-8c9d-e89d080849df.png">

Are the first two CDEFs meant to be blank?

There is also a blank Data Query with ID=10, a blank GPRINT and a couple of blank Data Input Methods as well.

At this stage all I had done was a clean install of 1.0.2 from git, run through settings and created some new devices and device trees.  No templates had been created/imported or graphs created at that stage.

**Comment by cigamit** [comment]
Edit include/global_arrays.php and change the $hash_version_code for 1.0.1 to 0027 and re-import.  Was a misstep as a part of the packing process.

**Comment by reubenfarrelly** [comment]
Thanks - confirmed as all fixed in -git.
