### ISSUE TITLE
Upgrade from 1.2.0 Beta 1 to 1.2.5 DB error

### ISSUE THREAD

**Issue by jackouille-ch** [Cacti/cacti#2931]
Centos 7 with PHP 7.3 and MariaDB 10.4
Fresh install from Cacti 1.2.5 with Package was working fine with local host.
Imported Database from Cacti 1.2.0 Beta 1 and got the following:
2019/09/09 22:12:01 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'deleted' in 'where clause'
2019/09/09 22:12:01 - CMDPHP SQL Backtrace:  (/poller.php[370]:db_fetch_assoc_prepared(), /lib/database.php[466]:db_execute_prepared())
2019/09/09 22:12:01 - ERROR PHP WARNING: array_merge(): Expected parameter 2 to be an array, bool given in file: /usr/share/cacti/poller.php  on line: 370
2019/09/09 22:12:01 - CMDPHP PHP ERROR WARNING Backtrace:  (/poller.php[370]:array_merge(), CactiErrorHandler())
2019/09/09 22:12:01 - ERROR PHP WARNING: Invalid argument supplied for foreach() in file: /usr/share/cacti/poller.php  on line: 582
2019/09/09 22:12:01 - CMDPHP PHP ERROR WARNING Backtrace:  (/poller.php[582]:CactiErrorHandler())
2019/09/09 22:12:01 - SYSTEM STATS: Time:0.0155 Method:spine Processes:10 Threads:20 Hosts:-1 HostsPerProcess:-0 DataSources:13866 RRDsProcessed:0
2019/09/09 22:12:01 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'sync_interval' in 'where clause'
2019/09/09 22:12:01 - CMDPHP SQL Backtrace:  (/poller.php[787]:poller_replicate_check(), /poller.php[847]:db_fetch_assoc(), /lib/database.php[452]:db_fetch_assoc_prepared(), /lib/database.php[466]:db_execute_prepared())
2019/09/09 22:12:01 - ERROR PHP WARNING: Invalid argument supplied for foreach() in file: /usr/share/cacti/poller.php  on line: 849
2019/09/09 22:12:01 - CMDPHP PHP ERROR WARNING Backtrace:  (/poller.php[787]:poller_replicate_check(), /poller.php[849]:CactiErrorHandler())
2019/09/09 22:12:01 - SYSTEM THOLD STATS: Time:0.0655 Tholds:0 TotalDevices:68 DownDevices:3 NewDownDevices:0
2019/09/09 22:12:02 - POLLER: Poller[1] WARNING: You have 7 Devices with bad SNMP Indexes.  Devices: Device[1], Device[136], Device[164], Device[168], Device[24], Device[187], Device[186] totalling 20 Data Sources.  Please Either Re-Index, Delete or Disable these Data Sources.
2019/09/09 22:12:02 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'deleted' in 'where clause'
2019/09/09 22:12:02 - CMDPHP SQL Backtrace:  (/poller_maintenance.php[146]:api_device_purge_deleted_devices(), /lib/api_device.php[110]:db_fetch_assoc_prepared(), /lib/database.php[466]:db_execute_prepared())

Performed Classical input:
[root@cacti-dev cli]# php upgrade_database.php --forcever=1.1.38
Upgrading from v1.1.38
[root@cacti-dev cli]#

But still the same, any hints ?

**Comment by cigamit** [comment]
That's quite odd, can you do it in Debug mode and send the output?

**Comment by jackouille-ch** [comment]
My trouble is that I cannot reach GUI anymore, I got timeouts and no entries in httpd/access.log despite the httpd restart that doesn't provide an error:
[root@cacti-dev httpd]# ps -afe | grep http
root      9628     1  0 05:52 ?        00:00:00 /usr/sbin/httpd -DFOREGROUND
apache    9629  9628  0 05:52 ?        00:00:00 /usr/sbin/httpd -DFOREGROUND
apache    9630  9628  0 05:52 ?        00:00:00 /usr/sbin/httpd -DFOREGROUND
apache    9631  9628  0 05:52 ?        00:00:00 /usr/sbin/httpd -DFOREGROUND
apache    9632  9628  0 05:52 ?        00:00:00 /usr/sbin/httpd -DFOREGROUND
apache    9633  9628  0 05:52 ?        00:00:00 /usr/sbin/httpd -DFOREGROUND

**Comment by cigamit** [comment]
Well, you run the update script from the command line.  You should try to stop httpd hard, make sure all the PID's are cleared up, and then re-run the upgrade script from the command line.

**Comment by jackouille-ch** [comment]
Still the same:

[root@cacti-dev httpd]# service httpd stop
Redirecting to /bin/systemctl stop httpd.service
[root@cacti-dev httpd]# ps -afe | grep http
root     23648  2036  0 20:50 pts/0    00:00:00 grep --color=auto http
[root@cacti-dev httpd]# php /usr/share/cacti/cli/upgrade_database.php --forcever=1.1.38
Upgrading from v1.1.38
[root@cacti-dev httpd]# service httpd start
Redirecting to /bin/systemctl start httpd.service
[root@cacti-dev httpd]#

And log entries:
2019/09/10 20:50:01 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'deleted' in 'where clause'
2019/09/10 20:50:01 - CMDPHP SQL Backtrace:  (/poller.php[370]:db_fetch_assoc_prepared(), /lib/database.php[466]:db_execute_prepared())
2019/09/10 20:50:01 - ERROR PHP WARNING: array_merge(): Expected parameter 2 to be an array, bool given in file: /usr/share/cacti/poller.php  on line: 370
2019/09/10 20:50:01 - CMDPHP PHP ERROR WARNING Backtrace:  (/poller.php[370]:array_merge(), CactiErrorHandler())
2019/09/10 20:50:01 - ERROR PHP WARNING: Invalid argument supplied for foreach() in file: /usr/share/cacti/poller.php  on line: 582
2019/09/10 20:50:01 - CMDPHP PHP ERROR WARNING Backtrace:  (/poller.php[582]:CactiErrorHandler())
2019/09/10 20:50:01 - SYSTEM STATS: Time:0.0164 Method:spine Processes:10 Threads:20 Hosts:-1 HostsPerProcess:-0 DataSources:13866 RRDsProcessed:0
2019/09/10 20:50:01 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'sync_interval' in 'where clause'
2019/09/10 20:50:01 - CMDPHP SQL Backtrace:  (/poller.php[787]:poller_replicate_check(), /poller.php[847]:db_fetch_assoc(), /lib/database.php[452]:db_fetch_assoc_prepared(), /lib/database.php[466]:db_execute_p repared())
2019/09/10 20:50:01 - ERROR PHP WARNING: Invalid argument supplied for foreach() in file: /usr/share/cacti/poller.php  on line: 849
2019/09/10 20:50:01 - CMDPHP PHP ERROR WARNING Backtrace:  (/poller.php[787]:poller_replicate_check(), /poller.php[849]:CactiErrorHandler())
2019/09/10 20:50:02 - SYSTEM THOLD STATS: Time:0.0287 Tholds:0 TotalDevices:68 DownDevices:3 NewDownDevices:0
2019/09/10 20:50:02 - POLLER: Poller[1] WARNING: You have 7 Devices with bad SNMP Indexes.  Devices: Device[1], Device[136], Device[164], Device[168], Device[24], Device[187], Device[186] totalling 20 Data Sou rces.  Please Either Re-Index, Delete or Disable these Data Sources.
2019/09/10 20:50:02 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'deleted' in 'where clause'
2019/09/10 20:50:02 - CMDPHP SQL Backtrace:  (/poller_maintenance.php[146]:api_device_purge_deleted_devices(), /lib/api_device.php[110]:db_fetch_assoc_prepared(), /lib/database.php[466]:db_execute_prepared())

Should I run an SQL command?

**Comment by cigamit** [comment]
There is something wrong.  Your output should show quite a bit more than it shows.  The upgrade script is not running.  What is your memory_limit in the php.ini file?  Maybe it's too low.  Edit the php.ini file and set the error_log to /tmp/error_log, the run again.  Review the error log for errors.  You should see a number of upgrade steps and a number of plus signs.  You can use the --debug flag, and then you should see quite a bit more too.

**Comment by jackouille-ch** [comment]
[root@cacti-dev httpd]# grep memory_limit /etc/php.ini
memory_limit = 2048MB

[root@cacti-dev httpd]# cat /tmp/php_errors.log
[11-Sep-2019 06:00:40 CET] PHP Fatal error:  Allowed memory size of 2097152 bytes exhausted (tried to allocate 65536 bytes) in /usr/share/cacti/lib/functions.php on line 3196
[11-Sep-2019 06:01:01 CET] PHP Fatal error:  Allowed memory size of 2097152 bytes exhausted (tried to allocate 12288 bytes) in /usr/share/cacti/lib/functions.php on line 2363

Moved to 8GB
[root@cacti-dev ~]# grep memory_limit /etc/php.ini
memory_limit = 8192MB

[11-Sep-2019 06:09:01 CET] PHP Fatal error:  Allowed memory size of 2097152 bytes exhausted (tried to allocate 12288 bytes) in /usr/share/cacti/lib/functions.php on line 2363
[11-Sep-2019 06:09:25 CET] PHP Fatal error:  Allowed memory size of 2097152 bytes exhausted (tried to allocate 65536 bytes) in /usr/share/cacti/lib/functions.php on line 3196
[11-Sep-2019 06:10:01 CET] PHP Fatal error:  Allowed memory size of 2097152 bytes exhausted (tried to allocate 12288 bytes) in /usr/share/cacti/lib/functions.php on line 2363

It looks like php.ini value is not taken. I checked on running 1.2.0 Beta and I only 512M

**Comment by netniV** [comment]
```
find / -name php.ini
```
Do that and see what other locations exist.  Debian systens, for example, have more than one ini file (cli and web)

**Comment by jackouille-ch** [comment]
That's what I already did but there is only one:
[root@cacti-dev ~]# php -v
PHP 7.3.9 (cli) (built: Aug 27 2019 22:52:39) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.9, Copyright (c) 1998-2018 Zend Technologies
[root@cacti-dev ~]# uname -a
Linux cacti-dev.local 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
[root@cacti-dev ~]# find / -name php.ini
/etc/php.ini
[root@cacti-dev ~]#

So it's CentOS 7 and I either try to reboot server, it doesn't bring a better state.
By the way it's a VM and I perform a snapshot before importing data so I can revert in case of need.
With fresh install, all requirements were met (in green).
My export is big:
[root@cacti-dev ~]# ll /root/cactidump.sql
-rw-r--r-- 1 root root 119586338 Sep  9 20:40 /root/cactidump.sql
[root@cacti-dev ~]#

Here are toher tasks I perform on 1.2.5:
[root@cacti-dev cli]# php ./repair_database.php --force
Repairing All Cacti Database Tables
Repairing Table -> 'aggregate_graph_templates' Successful
Repairing Table -> 'aggregate_graph_templates_graph' Successful
Repairing Table -> 'aggregate_graph_templates_item' Successful
Repairing Table -> 'aggregate_graphs' Successful
<snip>
NOTE: Running some Data Query repair scripts
NOTE: Checking for Invalid Cacti Templates
NOTE: 10 Invalid Data Input Data Rows based upon template mappings removed from Data Templates

[root@cacti-dev cli]# php remove_device.php --description="_DC_Firewall 1" --ip=10.41.1.129 --confirm
PHP Notice:  Undefined variable: debug in /var/lib/cacti/cli/remove_device.php on line 106
      id |                           host |                    description
     111 |                    10.41.1.129 |                 _DC_Firewall 1

Removing devices with ids: 111
Success - removed device-ids: 111



Why do I got errors for 8 devices (I removed one manually with

**Comment by jackouille-ch** [comment]
CLI) and from 1.2.0 Beta 1 no errors reported ?

**Comment by netniV** [comment]
So you shouldn’t be running the repair instead run the upgrade-database instead with the —forcever=1.1.38 but I still feel like it’s using a mixture of sources.

**Comment by jackouille-ch** [comment]
Back to state before import:
Update php.ini with 8192M instead of 512M
Updated logs to DEBUG
stopped httpd
performed import
Started httpd
Try to access GUI -> Timeout

Still not able to use Cacti.

Full logs:
Last login: Thu Sep  5 23:11:01 2019 from office.schell-consult.ch
[root@cacti-dev ~]# nano /etc/php.ini
[root@cacti-dev ~]# service httpd stop
Redirecting to /bin/systemctl stop httpd.service
[root@cacti-dev ~]# mysql -u root -p cacti < /root/cactidump.sql
Enter password:
[root@cacti-dev ~]# php /usr/share/cacti/cli/upgrade_database.php --forcever=1.1.38
Upgrading from v1.1.38
[root@cacti-dev ~]# service httpd start
Redirecting to /bin/systemctl start httpd.service

and cacti error.log:
2019/09/11 21:10:01 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'deleted' in 'where clause'
2019/09/11 21:10:01 - CMDPHP SQL Backtrace:  (/poller.php[370]:db_fetch_assoc_prepared(), /lib/database.php[466]:db_execute_prepared())
2019/09/11 21:10:01 - ERROR PHP WARNING: array_merge(): Expected parameter 2 to be an array, bool given in file: /usr/share/cacti/poller.php  on line: 370
2019/09/11 21:10:01 - CMDPHP PHP ERROR WARNING Backtrace:  (/poller.php[370]:array_merge(), CactiErrorHandler())
2019/09/11 21:10:01 - ERROR PHP WARNING: Invalid argument supplied for foreach() in file: /usr/share/cacti/poller.php  on line: 582
2019/09/11 21:10:01 - CMDPHP PHP ERROR WARNING Backtrace:  (/poller.php[582]:CactiErrorHandler())
2019/09/11 21:10:01 - SYSTEM STATS: Time:0.0110 Method:spine Processes:10 Threads:20 Hosts:-1 HostsPerProcess:-0 DataSources:13902 RRDsProcessed:0
2019/09/11 21:10:01 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'sync_interval' in 'where clause'
2019/09/11 21:10:01 - CMDPHP SQL Backtrace:  (/poller.php[787]:poller_replicate_check(), /poller.php[847]:db_fetch_assoc(), /lib/database.php[452]:db_fetch_assoc_prepared(), /lib/database.php[466]:db_execute_prepared())
2019/09/11 21:10:01 - ERROR PHP WARNING: Invalid argument supplied for foreach() in file: /usr/share/cacti/poller.php  on line: 849
2019/09/11 21:10:01 - CMDPHP PHP ERROR WARNING Backtrace:  (/poller.php[787]:poller_replicate_check(), /poller.php[849]:CactiErrorHandler())
2019/09/11 21:10:01 - SYSTEM THOLD STATS: Time:0.0148 Tholds:0 TotalDevices:69 DownDevices:3 NewDownDevices:0
2019/09/11 21:10:01 - POLLER: Poller[1] WARNING: You have 8 Devices with bad SNMP Indexes.  Devices: Device[1], Device[111], Device[136], Device[164], Device[168], Device[24], Device[187], Device[186] totalling 21 Data Sources.  Please Either Re-Index, Delete or Disable these Data Sources.
2019/09/11 21:10:01 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'deleted' in 'where clause'
2019/09/11 21:10:01 - CMDPHP SQL Backtrace:  (/poller_maintenance.php[146]:api_device_purge_deleted_devices(), /lib/api_device.php[110]:db_fetch_assoc_prepared(), /lib/database.php[466]:db_execute_prepared())

httpd/access_log:
82.146.220.140 - - [11/Sep/2019:21:11:22 +0200] "GET /cacti/ HTTP/1.1" 302 - "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0"

httpd/error.log
[Wed Sep 11 21:07:37.215813 2019] [suexec:notice] [pid 21115] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Wed Sep 11 21:07:37.244096 2019] [lbmethod_heartbeat:notice] [pid 21115] AH02282: No slotmem from mod_heartmonitor
[Wed Sep 11 21:07:37.303528 2019] [mpm_prefork:notice] [pid 21115] AH00163: Apache/2.4.6 (CentOS) PHP/7.3.9 configured -- resuming normal operations
[Wed Sep 11 21:07:37.303556 2019] [core:notice] [pid 21115] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'

But these errors were generated before import

**Comment by netniV** [comment]
This almost sounds like the clI and web are running two different codes. Probably something I could resolve with half hour dedicated support but tricky without access. 

I’m pretty sure deleted got added to that table in the 1_2_0.php upgrade file.

**Comment by jackouille-ch** [comment]
Could you contact me directly by private message ?

**Comment by jackouille-ch** [comment]
info at schell-consult.ch

**Comment by jackouille-ch** [comment]
Thanks netniV, now it works
