### ISSUE TITLE
Poller Output Table not Empty

### ISSUE THREAD

**Issue by andermat8** [Cacti/cacti#2933]
Running Windows with version 1.1.38.  I have been having issues with the poller output table not getting emptied.  It seems to happen once a week for the most part and polling stops functioning.  Running poller_output_empty.php with a server reboot resolves the issue.  I currently have over 17k graphs.  Based on suggestions I have read I adjusted tmp_table_size and max_heap_table_size as well as memory_limit in the php.ini:

tmp_table_size=2G
max_heap_table_size=2G

php.ini
memory_limit = 3G

ysql> select @@max_heap_table_size;
+-----------------------+
| @@max_heap_table_size |
+-----------------------+
|            2147483648 |
+-----------------------+
1 row in set (0.00 sec)

mysql> SELECT table_name, data_length + index_length as size FROM information_schema.TABLES WHERE table_schema = 'cacti'
    ->  and table_name = 'poller_output';
+---------------+----------+
| table_name    | size     |
+---------------+----------+
| poller_output | 47806096 |
+---------------+----------+
1 row in set (0.00 sec)

Just looking for any suggestions regarding resolution for this.  I'm planning on upgrading to 1.2.5 shortly.

**Comment by andermat8** [comment]
Good news.  Thanks.  I'll work toward upgrading.

**Comment by bmfmancini** [comment]
on 1.2.5 I periodically see this issue as well  not sure what it is though

**Comment by cigamit** [comment]
It can happen if the poller run exceeds the poller frequency.  When you see these errors, did the prior run exceed, or get very close to the poller interval?

**Comment by bmfmancini** [comment]
At least in my case I don't get poller overrun errors just periodic poller
output table not empty

I will check what my stats are tomorrow

**Comment by andermat8** [comment]
I did see this yesterday but it is not consistent.  
2019/09/15 12:06:55 - POLLER: Poller[1] WARNING: Scheduled Task is out of sync with the Poller Interval!  The Poller Interval is '300' seconds, with a maximum of a '300' second Scheduled Task, but 413.9 seconds have passed since the last poll!
2019/09/15 12:06:55 - POLLER: Poller[1] WARNING: Poller Output Table not Empty.  Issues: 4243, DS[60440, 420, 60433, 34487, 912, 59385, 60325, 2103, 59171, 57056, 59160, 60403, 46194, 58841, 59223, 60379, 48284, 37010, 59170, 46756], Additional Issues Remain.  Only showing first 20

**Comment by andermat8** [comment]
Just checked the system I upgraded to 1.2.5 and it is also having the poller output table issue so an upgrade won't fix it.

**Comment by bmfmancini** [comment]
Yeah but that indicates your system is not working fast enough to get to
all of the devices

Are you using cmd.php or spine ?

**Comment by andermat8** [comment]
cmd.php, having issues with spine on a Windows server.  The poller runs like a champ for most of the week before it has issues, seems to be at the same time every Sunday right now.

**Comment by andermat8** [comment]
Also, running poller_output_empty.php not working for me in 1.2.5 for some reason.  Command D:\php\php.exe -q D:\inetpub\wwwroot\cacti\cli\poller_output_empty.php works fine in 1.1.38 but not in the updated version. No error given but the table is not emptied.

**Comment by cigamit** [comment]
Can you guys work on this issue in the forums please.  Thanks!
