### ISSUE TITLE
cacti 1.2.6 图形错误

### ISSUE THREAD

**Issue by 315xiaoyao** [Cacti/cacti#2935]
![image](https://user-images.githubusercontent.com/33082140/64756508-cf6bc000-d561-11e9-8916-0487491cb78e.png)

**Comment by bmfmancini** [comment]
huh ?

**Comment by cigamit** [comment]
Please state what the issue is in English.  As far as I know, none of the Cacti Developer can read Chinese, and since its a screen shot, we can't even paste it into a translator.

**Comment by cigamit** [comment]
Update to latest 1.2.x branch until 1.2.7 is released.
