### ISSUE TITLE
Installer will loop when number of tables exceeds PHP's max_input_vars limit

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#2936]
**Describe the bug**
1. Cacti Server v1.2.6 - Installation Wizard keep at step "Table Setup" if some tables are not convert InnoDB, or charset is not 'utf8mb4_general_ci'
2. Check "Select All Rows" will highlight all rows, but single row can not be highlight when click 'checkbox' of at end of each single table_name_row,

**To Reproduce**
1. Install a Cacti 1.2.5- env
2. Convert some tables to MyISAM, some table chartset to  latin1
3. Deploy Cacti 1.2.6, start "installation Wizard"
4. Navigate to step "Table Setup". All table_name_row is selected and highlight.
5.  Click "Select All Rows" to clean all selected status
6.  "Select" any one of table_name  by row-end-checkbox.
7. You will see "selected row" is not highlight
8. Ensure "un-check" all table_name, click "Next"
9.  Installation Wizard keep current page after a cycle checking.

**Expected behavior**
1.  highlight or un-highlight row when click 'checkbox'
2. Continue wizard even non-table selected

**Screenshots**
"Select All Rows"
![image](https://user-images.githubusercontent.com/17589018/64770711-4ca62d80-d580-11e9-9cae-d369aae780fd.png)

"Select Some Rows"
![image](https://user-images.githubusercontent.com/17589018/64770790-6e071980-d580-11e9-9613-03ff37fa6416.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser FireFix
 - Version 70

**Comment by netniV** [comment]
That almost sounds like the csrf is failing since there shouldn’t be a 302 from step_json.php. To debug that I would put a file_put_contents() around either side of the first include in step_json to see.

**Comment by ddb4github** [comment]
BTW,  this time wizard never require  me to login. Wizard is directly started when I access /cacti/

**Comment by netniV** [comment]
Hmm, have you changed your auth settings ? I'm going to recreate your setup by creating a load of tables with the names from the log file and see if I get the same issue.

**Comment by ddb4github** [comment]
Settings:
auth_cache_enabled	on
auth_method	1
graph_auth_method	1
secpass_expireaccount	0
secpass_expirepass	0
secpass_forceold
secpass_history	0
secpass_lockfailed	0
secpass_minlen	8
secpass_reqmixcase	on
secpass_reqnum	on
secpass_reqspec	on
secpass_unlocktime	60

**Comment by cigamit** [comment]
I suspect a keep me logged in session is active and stored during the upgrade process.  If you log out first before starting the upgrade, does anything change?

**Comment by netniV** [comment]
OK, so I managed to recreate this by creating all the disku/lic tables.  I'll keep looking why its occurring but I thought I would let you know that I had found the same issue.

**Comment by netniV** [comment]
I would also agree with @cigamit's theory that if you have already logged in with the 'remember me' setting, the installation wizard will automatically authentication you.

**Comment by netniV** [comment]
Can you try doubling the `max_input_vars` within your php.ini?  that should hopefully resolve the issue for you.  If so, I'll have to write some code to try and detect when this situation is likely to happen and put that into the php recommendations set.

**Comment by netniV** [comment]
![image](https://user-images.githubusercontent.com/9052188/64929032-5e096700-d818-11e9-93fe-9439b405bd84.png)

So, this is what I've produced to display the warning.  Since it's kind of an edge case, I think it will do to place it here rather than within the recommendations.
