### ISSUE TITLE
Under CentOS packages, upgrade_database.php script uses incorrect location for DB upgrade scripts

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#2938]
**Describe the bug**
When using the upgrade_database.php script, a single line may be seen showing that an upgrade of the database from version x.x.x is ,underway.  No further updates are seen and the database version is updated in the database to y.y.y (the updated version).

However, aside from the database version, zero updates are performed.  This may be related to #2780 when a change was made to set the database version at the end of the script regardless of whether an update has been performed. 

It turns out that the reason for this failure to update the database was highlighted in #2931, specifically [this post](https://github.com/cacti/cacti/issues/2931#issuecomment-530873249) where the include locations were diagnosed as being under the cli folder, not the cacti web root.

**Expected behavior**
Use $config['base_path'] rather than a relative include due to packaging method.

**Additional context**
Tagging @mortenstevens here so that he is aware of the situation and will be notified when a forth coming patch is applied to 1.2.7 correcting the situation.  This may also apply to ubuntu (@paulgevers) but that hasn't been tested at this time.

**Comment by mortenstevens** [comment]
@netniV 
Thank you for the report. But I'm not able to reproduce this? I have upgraded some cacti installations (RHEL 8, Fedora 30, Fedora 31) from 1.2.5 to 1.2.6 without any issue.

**Comment by netniV** [comment]
When the upgrade runs. Do you see the individual upgrade versions being reported ? Or just the one line ?

**Comment by netniV** [comment]
This has been corrected in 21f0446b40b716b1fb6c204766d199629caf926a
