### ISSUE TITLE
add_graphs.php not change the title

### ISSUE THREAD

**Issue by cgpcaigv** [Cacti/cacti#2939]
Hello,

Use cacti version 1.1.38.

I am creating graphs from add_graphs.php, the graph is created correctly but does not change the title with the --graph-title option.

I have checked the checkbox title in the template.

I have also used the version of cacti 0.8.7 and in this case if I changed the title with the script.

I have searched this page and on the Internet how to solve it and I have not found any way to do it.

Anyone know what might be happening?
Why does this option work in the old version and not in the new one? Is there any change from one version to another or is it necessary to activate any additional option?

A basic example (this is not the graph I want but it is a test to see that the title does not change): php -q add_graphs.php --host-id=3 --graph-type=ds --graph-template-id=2 --snmp-query-id=1 --snmp-query-type-id=6 --snmp-field=ifName --snmp-value=Gi3 --graph-title="Gi3 interface graph"

Thanks and sorry for my English.

**Comment by cigamit** [comment]
This was fixed in the 1.2.x release series.  Here is the fix: https://github.com/Cacti/cacti/commit/92b112c0723298591f74f4169654db674d2b8e90#diff-ae8635bb7a75eca6b42b5bcc099c1612
