### ISSUE TITLE
cacti_stderr.log more verbose in error

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#2941]
**Describe the bug**
I found:
`snmpwalk: Unknown host (.1.3.6.1.4.1.14988.1.1.1.2.1.3.76.94.12.2.19.25.2)`

But don't know how to find data source whitch is responsible for that.

**Expected behavior**
A host and data source in cacti_stderr.log.

Cacti 1.2.x

**Comment by netniV** [comment]
Unfortunately the stderr log is used by not only us but any sub process that writes to that channel. So it may not be so easy to pin point what is writing it.

**Comment by interduo** [comment]
So It would be good to show the name of the subprocess/script and parameters whitch it was run with.

**Comment by netniV** [comment]
If we control that yes. But we don’t always.

**Comment by cigamit** [comment]
I really don't want to mess with this right now.  I'm not sure what the benefits would be.  So, I'm going to take executive action and close it down.  You will get data in your standard error log, and that will either be something that PHP can not block, there are some cases for that, or script error logging, say a python or bash script, which, if the script is written well, should log either to syslog, or to the Cacti log in the case it's a PHP script.
