### ISSUE TITLE
Log filtering poller

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#2942]
**Is your feature request related to a problem? Please describe.**
I have got a little instance. Every poller the log gets about few tousands lines. There is much logs and then when I would like to find any messages whitch was generated not by poller there is a little problem because cannot filter that. Yes I know that there is a cli and grep but I don't want to give cli access to cacti users.

**Describe the solution you'd like**
Send poller log to it's ownfile (ex. cacti-poller.log).

**Alternative the solution you'd like**
Char "-" in the begining of the line before string works as "don't show log lines whitch does contain string". We could write for example "-SPINE" or "-poller.php".

**Comment by netniV** [comment]
That is already possible as the search is a regular expression:
```
^((?!SPINE).)*$
```

**Comment by interduo** [comment]
Nice. Thanks!
