### ISSUE TITLE
1.2.5 Graphs Randomly Stop generating 

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#2946]
Hey Guys 

So I have noticed that on a system with remote pollers that Randomly graphs will stop generating 
Permissions are fine and you see the RRA displayed but they go to nan 

Doing a Datasource debug will show the following

Data Source returned Bad Results for errors_out Data Source returned Bad Results for discards_in Dat

If you re-create the device it works again 

I have tried re-indexing the device both cli and in the gui no go 
very weird my systems stats are as follows

![image](https://user-images.githubusercontent.com/13388748/65063255-e76d8600-d94b-11e9-89ab-f819b21c6eeb.png)

The Max polling time was a spike from a while ago during an upgrade

**Comment by bmfmancini** [comment]
![image](https://user-images.githubusercontent.com/13388748/65063341-0a983580-d94c-11e9-8aaf-4d4c81e99d82.png)

**Comment by bmfmancini** [comment]
![image](https://user-images.githubusercontent.com/13388748/65063438-403d1e80-d94c-11e9-90bf-51a0f18bfa76.png)

**Comment by bmfmancini** [comment]
Here is the output from the reindex script

 php poller_reindex_hosts.php --id=2232 --debug
WARNING: Do not interrupt this script.  Reindexing can take quite some time
DEBUG: There are '3' data queries to run
DEBUG: Data query number '1' host: '2232' SNMP Query Id: '1' starting
DEBUG: Data query number '1' host: '2232' SNMP Query Id: '1' ending
DEBUG: Data query number '2' host: '2232' SNMP Query Id: '11' starting
DEBUG: Data query number '2' host: '2232' SNMP Query Id: '11' ending
DEBUG: Data query number '3' host: '2232' SNMP Query Id: '12' starting
DEBUG: Data query number '3' host: '2232' SNMP Query Id: '12' ending

**Comment by TheWitness** [comment]
@bmfmancini, you should import the Cacti Stat's package and track the polling time for the remote collectors in order to look for a correlation.

To do this, first import the package, and then create a device, with no availability check of type Cacti Stats.  Then, create any Data Query graphs that makes sense.

I would avoid cmd.php in that scripts do not have never had a good timeout.  It's the nature of popen, whereas spine will time out the scripts.  cmd.php could be enhanced to use proc_open, to include timeouts, but someone needs to create a pull request to do so.  At that time cmd.php can be more scalable.

**Comment by bmfmancini** [comment]
Hey thanks for the suggestion

I am currently using spine on all of the pollers

Are you suggesting to switch back to cmd.php ? I'm worried about the
performance impact

**Comment by cigamit** [comment]
Yea, I would not do that.  But check your script timeout and see if there is an issue.  If you update the Device package there is a poller time device graph.  You should create those graphs and then find the slow devices and do some research as to why it happens.

**Comment by cigamit** [comment]
Another thing you can do is increase the heartbeat of the graphs.  So, you can do this in batch from the command line as the hearbeat can be set via the rrdtool command.  After that, it might be a good thing to update it in the Data Templates.

**Comment by bmfmancini** [comment]
Yea I made some changes yesterday on the SNMP time outs and snmpbulk get as I see some of the devices in the WAN coming back with a SNMP timeout  so lets see how that works

I will report back on if that helped 

As always thanks for your help !

**Comment by bmfmancini** [comment]
Ok I increased the SNMP-Timeout and script time out 
I also increased the SNMP gets as well 

Looks good so far lets see

**Comment by cigamit** [comment]
I would be more concerned if you were to increase timeout especially when a WAN connection goes down.  This is why it's prudent to deploy Remote Data Collectors for devices that need to be reached over a WAN connection.  Increasing in those cases where you are traversing a WAN can be a real problem especially when you have a high frequency data collection interval.
