### ISSUE TITLE
Send Curl request when Device is down 

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#2947]
Hey Everyone 

What would be cool is to be able to send a curl command  or just have a command field like there is in Thold but for when the site is down

Currently, there is only an option to send an email which works great but is less than ideal for ticket system integrations

**Comment by netniV** [comment]
This can already be done using a script in thold I believe.

**Comment by netniV** [comment]
This should only be open in thold

**Comment by bmfmancini** [comment]
OK thanks 

I dont see any option for up/down just for threshold breaches ill keep looking 
Thanks

**Comment by netniV** [comment]
Hmm, not entirely sure on that one actually.  I think monitor handles up/down notices.

**Comment by bmfmancini** [comment]
Actually yes you are right

Monitor is responsible for up down notifications

I'll open this request there
