### ISSUE TITLE
Device Template Names - Minor Issue

### ISSUE THREAD

**Issue by reubenfarrelly** [Cacti/cacti#295]
Currently we have:

Cisco Router
Generic SNMP-enabled Host
Local Linux Machine
ucd/net SNMP Host
Windows Host

The naming of these is not ideal, however I suspect it might be difficult to fix these up especially in an upgrade scenario:

- Cisco Router - this Device Template actually applies and works with Cisco Routers and Switches all running classic Cisco IOS as well as Cisco IOS XE and Cisco NX-OS.  A more correct name for this would be "Cisco IOS/XE/NX-OS"
- ucd/net SNMP Host - the project was renamed as Net-SNMP over 15 years ago.  We should probably update the name here too
- Use of the word 'Windows'.  This probably should be 'Microsoft Windows'

In any case for Cisco and Microsoft there is a case that we should be appending each company's trademarks without the trademark ® symbol.  I am not a lawyer but this is how I interpret the guidelines on the use of those names.

**Comment by cigamit** [comment]
On a clean install, they have been renamed, and are drastically different templates.  On upgrade we left things alone so as not to screw up your environments without your permission.  The copyright point is noted.

In all honesty, we should break up the templates a little more and have Cacti detect which templates are applicable.  In that case, a device could have more than one template that it is associated with.  It's something we will give careful thought to moving forward.  Being that this would be a major change though, it would happen during the next major upgrade which will be a little way off.

**Comment by reubenfarrelly** [comment]
Fair enough.  Yes I agree the upgrade scenario would be.... messy ... and break the principle of 'least surprise'.

The only template I am seeing as different now (with a clean install as of 2 mins ago) is the Net-SNMP one.  The other two look and are named the same as before.

**Comment by cigamit** [comment]
The import_package.php has been improved now to make this stable.  Make sure you select --remove-orphans option unless you want things out of order.
