### ISSUE TITLE
Add/modified legends in Aggregate Graphs in Cacti 1.2.6

### ISSUE THREAD

**Issue by frankfer01** [Cacti/cacti#2951]
Actually, I use the version 0.8.8b of Cacti and I want to move to the 1.2.6 version. I have a new server and the new Cacti is all ready installed, but when I create a aggregate graph, I cant add or edit the legend in the new graph. Why this is not possible. In the previous version you can do it. In the new version aggregates items are not editable. I have a lots of interfaces graphs and I can't migrate to the new cacti because of this. 

Please somebody can help me.

Regards,

**Comment by cigamit** [comment]
In Cacti 1.2.6, you can convert an Aggregate Graph to a normal graph and then modify as you require.  So, there is some good news ahead.

**Comment by frankfer01** [comment]
The point is that I want to see the correct legend in the new aggregate graph. The aggregate item can not be editable in the new version. I add in the graph template a new graph item as COMMENT but in the aggregate it can't be added:

![cacti](https://user-images.githubusercontent.com/55502569/65242452-6681cc00-dabc-11e9-8679-2139641fbc04.jpg)

In the new aggregate graph, I want so see the correct legend of each item(in this case Outbound/Inbound)

**Comment by cigamit** [comment]
So, the comment field includes only the word "Inbound" or outbound?  Do you not see it from the AREA's just before?  Show me the completed aggregate graph as is.

**Comment by frankfer01** [comment]
Yes, the comment field only include "Inbound" and "Outbound". I can see in the AREA Item, the thing is that this part disappear in the aggregate graph:

![cacti1](https://user-images.githubusercontent.com/55502569/65244613-58827a00-dac1-11e9-95b0-072fbb5523a5.JPG)

In in the template graph I deleted the item COMMENT, this is the result:

![cacti2](https://user-images.githubusercontent.com/55502569/65244885-e8282880-dac1-11e9-9248-fff66fd8b572.jpg)

![cacti4](https://user-images.githubusercontent.com/55502569/65244899-ee1e0980-dac1-11e9-81c5-38396d78b086.JPG)

**Comment by cigamit** [comment]
Okay, conceding on this one.  You will have to update to the 1.2.x branch to fix.  We had originally added the force skip as a protection method, but in your case, it's critical.

**Comment by frankfer01** [comment]
Thanks, do you think that will work for the next version(1.2.7)?. When will be available the a new version?

Regards,

**Comment by cigamit** [comment]
~ 2019-09-28.  There is a nasty form bug in 1.2.6.  You should just grab it.

**Comment by frankfer01** [comment]
Thanks a lot for your support. I'll be waiting.

**Comment by frankfer01** [comment]
Hi, today I upgrade Cacti to 1.2.7, but I have the same issue with the aggregate graphs. I can't modify the legends.
