### ISSUE TITLE
In tree view if device is marked down or threshold triggered mark as red

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#2952]
A feature that would be nice to have is a marker for a device that is down in the tree view 
or if thold is enabled and a thold is triggered then mark it as yellow or something 

Another thing to add would be the tree name its self marked with a different colour text or some other flag  if a device in that tree has an issue i,e down

Thanks guys !

**Comment by cigamit** [comment]
Oh, that's cool.

**Comment by cigamit** [comment]
Changed to preserve some resemblance of sanity.

**Comment by bmfmancini** [comment]
Awesome man looking forward to testing this out!
