### ISSUE TITLE
only gmp module not found (cli - no) prevents installation

### ISSUE THREAD

**Issue by pbrena** [Cacti/cacti#2953]
Hi,

Unlike problem #2665 (Required PHP modules) only gmp reports as cli - no thus preventing installation.

![Screen](https://user-images.githubusercontent.com/55524715/65215346-d8cdbe80-da72-11e9-812b-b26bf65eec44.png)

{"ctype":{"cli":true,"web":false},"PDO":{"cli":true,"web":false},"zlib":{"cli":true,"web":false},"xml":{"cli":true,"web":false},"standard":{"cli":true,"web":false},"spl":{"cli":true,"web":false},"sockets":{"cli":true,"web":false},"simplexml":{"cli":true,"web":false},"session":{"cli":true,"web":false},"pdo_mysql":{"cli":true,"web":false},"pcre":{"cli":true,"web":false},"date":{"cli":true,"web":false},"openssl":{"cli":true,"web":false},"mbstring":{"cli":true,"web":false},"ldap":{"cli":true,"web":false},"json":{"cli":true,"web":false},"hash":{"cli":true,"web":false},"gmp":{"cli":true,"web":false},"gd":{"cli":true,"web":false},"filter":{"cli":true,"web":false},"posix":{"cli":true,"web":false}

2019/09/18 20:17:54 - AUTH LOGIN: User 'admin' Authenticated

Wed Sep 18 20:13:32.203909 2019] [mpm_prefork:notice] [pid 3429] AH00163: Apache/2.4.41 (Unix) PHP/7.1.32 configured -- resuming normal operations
[Wed Sep 18 20:13:32.204097 2019] [core:notice] [pid 3429] AH00094: Command line: '/usr/local/opt/httpd/bin/httpd -D FOREGROUND

 - OS: MacOs Mojave
 - safari
 - Homebrew: PHP  7.1.32 (cli) (built: Sep 14 2019 18:22:11) ( NTS )
 - Homebrew: Server version: Apache/2.4.41 (Unix) Server built:   Sep  8 2019 02:57:02
 - mysql-8.0.17

**Comment by cigamit** [comment]
Well, do you have a php.ini or some other variable.  If it's a debian variant, there is generally something like:

/etc/phpX/cli/php.ini
and
/etc/phpX/apache2/php.ini

You should diff those two files and see what is different.  Not run Debian in a while.  So, the module inclusion may be in a conf.d directory or something.

**Comment by netniV** [comment]
The system is MacOS so I'm not totally sure where Homebrew puts the php.ini, but there is likely a separate ini file for cli and apache itself just like debian does (even though macos is actually a bsd variant).  

We use GMP so it is needed.

**Comment by pbrena** [comment]
Thanks for the pointers and fast responce,

I had made this so far:

1) Cleaned up previous test php envitonments and switched to:
 PHP 7.1.23 (cli) (built: Feb 22 2019 22:19:32) ( NTS )
Copyright (c) 1997-2018 The PHP Group

2) I still found 3 different php.ini files and made them all equal:

$ sudo find / -name "php.ini"
/usr/local/etc/php/7.3/php.ini
/usr/local/Cellar/php/7.3.9_1/.bottle/etc/php/7.3/php.ini
/private/etc/php.ini
$
$ diff /usr/local/etc/php/7.3/php.ini /usr/local/Cellar/php/7.3.9_1/.bottle/etc/php/7.3/php.ini
$ diff /usr/local/etc/php/7.3/php.ini /private/etc/php.ini
$ 

Unfortunately still same behavior 

3) gmp seems to be present in phpinfo and ext folder:

![Screen Shot 2019-09-19 at 8 29 51 PM](https://user-images.githubusercontent.com/55524715/65292435-0707d880-db1d-11e9-9faf-13c73a7e106a.png)
![Screen Shot 2019-09-19 at 8 31 56 PM](https://user-images.githubusercontent.com/55524715/65292436-0707d880-db1d-11e9-8541-33104d8ffd27.png)
![Screen Shot 2019-09-19 at 8 34 07 PM](https://user-images.githubusercontent.com/55524715/65292437-0707d880-db1d-11e9-9655-2faf46ffaa9a.png)

4) all dynamic extensions are commented out not only gmp (;extension=gmp) but if I remove the comment i get: 

Warning: PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php/7.3.9_1/include/php/ext/gmp' - dlopen(/usr/local/Cellar/php/7.3.9_1/include/php/ext/gmp, 9): no suitable image found.  Did find:
	/usr/local/Cellar/php/7.3.9_1/include/php/ext/gmp: not a file
	/usr/local/Cellar/php/7.3.9_1/include/php/ext/gmp: stat() failed with errno=22 in Unknown on line 0

So.. What I cant understand is why is gmp the only one not recognised, please advice

**Comment by bmfmancini** [comment]
Have you tried a reload/restart of apache ?

**Comment by pbrena** [comment]
I have, Including reboot, safari-clean history.

Still no change... I m out of clues for further troubleshooting... any idea for further try would be appreciated.

**Comment by netniV** [comment]
```
Warning: PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php/7.3.9_1/include/php/ext/gmp' - dlopen(/usr/local/Cellar/php/7.3.9_1/include/php/ext/gmp, 9): no suitable image found. Did find:
/usr/local/Cellar/php/7.3.9_1/include/php/ext/gmp: not a file
/usr/local/Cellar/php/7.3.9_1/include/php/ext/gmp: stat() failed with errno=22 in Unknown on line 0
```
That is your problem.  Your enabling an extension that apparently isn't installed in one of those other locations.  Find out which location has the gmp extension and then copy it to the others.

**Comment by cigamit** [comment]
I'm going to close this as it sounds like an environment issue.  However, you can continue this discussion while it's closed if you like.  Good luck.

**Comment by pbrena** [comment]
Thx, I get it is an environment issue, and sorry for all this newbie questions...

I still fail to find the missing extension, i find the php for mac documentation scarce and/or outdated.

currently i struggle to identify the php extension names, even the ones it finds, for example: { it finds the pdo_mysql extension and AFAIU its name should have been "pdo_mysql.so" but it is nowhere in the system (see bellow) and of course gmp.so isn't either}

So my question is: What is the name of the files it should find? ... lets say of gmp and pdo_mysql.

-----------------------------------
$ sudo find / -name "pdo_mysql.so"
find: /dev/fd/3: Not a directory
find: /dev/fd/4: Not a directory
$

**Comment by netniV** [comment]
If you would like some support for this, email me netniv@cacti.net but this is a non-standard setup issue so isn't really a forum for issue trackers.
