### ISSUE TITLE
data input methods - it's impossible to add (or change) an input field

### ISSUE THREAD

**Issue by vaclav-krauz** [Cacti/cacti#2954]
version 1.2.6

**Describe the bug**
when you want to add a new input field to a data input method, you can select no field (defined in 'path/script.lol &lt;arg1&gt; &lt;arg2&gt;...., because the select is empty and you get the error message "Sorry, we could not process your last action.
Save Failed due to field input errors (Check red fields)."

**Screenshots**
![Screenshot at 2019-09-19 11-13-48](https://user-images.githubusercontent.com/17041727/65230694-9a65ed00-dace-11e9-8ece-5e027737b618.png)

**Additional context**
I would say, somebody forget 'break' on the line 83 in the file lib/html_utility.php

function inject_form_variables()

you go through the array

        [data_name] => Array (
            [method] => drop_array
            [friendly_name] => Field [|arg1:|]
            [description] => Choose the associated field from the |arg1:| field.
            [value] => |arg3:data_name|
            [array] => |arg2:|
        )

the first applicable check value is 'value', so you replace 

[value] => |arg3:data_name| to [value] => func

but there is your:

// Double check to see if the replacement went as planned

and this is true:

if (!cacti_sizeof($matches)) {

and here is the statement 'break' which should not be there, because the loop
foreach ($check_fields as $field_to_check) { ends and other array keys - values are not replaced

**Comment by cigamit** [comment]
Please update to the 1.2.x branch.  There was an error in the form handling in 1.2.6.  But it looks like you have a bigger issue too.

**Comment by vaclav-krauz** [comment]
I have version 1.2.6 and the same code in the master branch,

 lib/html_utility.php
function inject_form_variables()
`						// Double check to see if the replacement went as planned
						$matches = array();
						preg_match('/\|(arg[123]):([a-zA-Z0-9_]*)\|/', $string, $matches);
						if (!cacti_sizeof($matches)) {
							$form_array[$field_name][$field_to_check] = $string;
							break;
						} elseif (isset($form_array[$field_name]['default'])) {
							$form_array[$field_name][$field_to_check] = $form_array[$field_name]['default'];
						} else {
							$form_array[$field_name][$field_to_check] = '';
						}`
if you delete the line with 'break;' in the 'if (!cacti_sizeof($matches)) {' it works fine

**Comment by cigamit** [comment]
Well, don't look at master, update to the 1.2.x branch.

**Comment by vaclav-krauz** [comment]
I mean this

![Screenshot at 2019-09-19 17-00-59](https://user-images.githubusercontent.com/17041727/65256414-c9e11d80-daff-11e9-80e3-dcc4a8e1fd22.png)

if you click on 'func' (and the break is in code), you can see this (the empty select)

![Screenshot at 2019-09-19 17-01-16](https://user-images.githubusercontent.com/17041727/65256701-3f4cee00-db00-11e9-8d12-723566c2187d.png)

and when you delete the 'break' and click on 'func', you can select what you want

![Screenshot at 2019-09-19 17-01-47](https://user-images.githubusercontent.com/17041727/65256818-76bb9a80-db00-11e9-9228-6da2705307fb.png)

I have downloaded the version 1.2.6
(The latest stable version is 1.2.6, released 09/02/19.) 

(the break is in the master)

![Screenshot at 2019-09-19 17-03-53](https://user-images.githubusercontent.com/17041727/65257287-4a544e00-db01-11e9-9b8a-aee5c500b6ed.png)

![Screenshot at 2019-09-19 17-04-01](https://user-images.githubusercontent.com/17041727/65257413-7374de80-db01-11e9-8d96-d3eb02d3b516.png)

**Comment by cigamit** [comment]
Right, it's fixed already in the 1.2.x branch.  Are you still confused?  Closing, but we can continue the conversation even though it's closed.  However, to be clear, this is resolved already.  Not in develop, but in 1.2.x.
