### ISSUE TITLE
the name of data input method is automatically changed to the name of added outputfiled

### ISSUE THREAD

**Issue by vaclav-krauz** [Cacti/cacti#2955]
**Describe the bug**
version 1.2.6

when you add a new output field to a data input method, its name rewrite the name of the data input method

**To Reproduce**
1. Go to 'data inptut methods'
2. Select one
2. Click on 'add output field'
3. fill the form and click on save
4. Check the name of the edited data input method

**Expected behavior**
The name of the data input method should be still the same

**Screenshots**
![Screenshot at 2019-09-19 12-08-56](https://user-images.githubusercontent.com/17041727/65235240-845c2a80-dad6-11e9-8b39-28751850d113.png)

**Desktop (please complete the following information):**
 - OS: linux
 - Browser Chromium
 - Version 76.0.3809.100

**Comment by cigamit** [comment]
Well, that's a problem.

**Comment by cigamit** [comment]
Hmm, can you do a screen2gif animated gif of how you are able to re-produce this.  I tried on my local system and can not reproduce.

**Comment by cigamit** [comment]
Also, give me the id of the data input method, and the id of the item that you edited.

**Comment by vaclav-krauz** [comment]
I cannot reproduce it again. It works now properly. Strange.

**Comment by cigamit** [comment]
Okay, just going to close.  If it happens again.  Just let us know.
