### ISSUE TITLE
How to degrade from 1.3.0 to 1.2.5

### ISSUE THREAD

**Issue by vishnubraj** [Cacti/cacti#2956]
By mistake i upgraded to 1.3.0 and i having high Mysql CPU utilization, i downloaded the 1.2.5 package and moved to that, but the mysql is still at 1.3.0, I dont see much changes on the install/upgrades/1_3_0.php file, also the 1.2.6 file is missing... 
The mysql CPU is reaching 500 percent and not able to use cacti. Can someone please help me with that?

**Comment by cigamit** [comment]
Just copy the 1.2.x branch files over the existing, and then run this query, the restart everything:

``` sql
UPDATE cacti SET version='1.2.6';
```

**Comment by cigamit** [comment]
Delete that update file too.  Otherwise, it'll keep trying to run that.

**Comment by vishnubraj** [comment]
Thanks @cigamit  it worked

**Comment by cigamit** [comment]
Good to hear.
