### ISSUE TITLE
autocomplete drop-down list sometimes needs double click to open

### ISSUE THREAD

**Issue by kim-fitness** [Cacti/cacti#2958]
**Describe the bug**
In "Graph Management" page, the drop-down list "Device" sometimes need double-click to open.

**To Reproduce**
1. Go to page "Graph Management"
2. Click on 'Device' to open the drop-down list
3. Click any other place on this page, the "Device" drop-down list will be closed.
4. Click on 'Device', the drop-down list does not open. (Reproduced)
5. Click on 'Device' again, the drop-down list is opened.

**Expected behavior**
No matter how operate on this page, the 'Device' drop-down list should be opened with one click.

**Screenshots**
![Screen Shot 2019-09-20 at 1 39 37 PM](https://user-images.githubusercontent.com/47587743/65301988-48939480-dbac-11e9-8aa0-f66ef127e0c1.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.14
 - Browser: Chrome
 - Version: 76.0.3809.132

**Additional context**
This issue is introduced by following code from cacti/include/themes/paw/main.js (for example, any other theme has the same issue)

```
	$('#host').unbind().autocomplete({
		source: pageName+'?action=ajax_hosts',
		autoFocus: true,
		minLength: 0,
		select: function(event,ui) {
			$('#host_id').val(ui.item.id);
			callBack = $('#call_back').val();
			if (callBack != 'undefined') {
				eval(callBack);
			} else if (typeof applyGraphFilter === 'function') {
				applyGraphFilter();
			} else {
				applyFilter();
			}
		}
	}).addClass('ui-state-default ui-selectmenu-text').css('border', 'none').css('background-color', 'transparent');

	$('#host, #host_click').click(function() {
		if (!hostOpen) {
			$('#host').autocomplete('option', 'minLength', 0).autocomplete('search', '');
			hostOpen = true;
		} else {
			$('#host').autocomplete('close');
			hostOpen = false;
		}
	});
```

When click to open the drop-down list, 'hostOpen' becomes 'true'. But when click out-side the drop-down list to close it, 'hostOpen' still be 'true', that makes next time, when you click on the drop-down list, the code go with 'else' to close it, other than open it.

I have fixed this issue by following code, but it is not perfect, by my fix, the drop-down list's behavior has been changed a little.

Before my fix,
Click the drop-down list, it will open, click again, it will close.

After my fix,
Click the drop-down list, it will alway open. User should click out-side the drop-down list to close it.

Here is my fix for your reference
```
    $('#host, #host_click').unbind().autocomplete({
    	source: pageName+'?action=ajax_hosts',
    	autoFocus: true,
    	minLength: 0,
    	select: function(event,ui) {
    		$('#host_id').val(ui.item.id);
    		callBack = $('#call_back').val();
    		if (callBack != 'undefined') {
    			eval(callBack);
    		} else if (typeof applyGraphFilter === 'function') {
    			applyGraphFilter();
    		} else {
    			applyFilter();
    		}
    	},
        close: function( event, ui ) {
            hostOpen = false;
        },
        open: function( event, ui ) {
            hostOpen = true;
        }
    }).addClass('ui-state-default ui-selectmenu-text').css('border', 'none').css('background-color', 'transparent');

    $('#host, #host_click').click(function() {
    	if (!hostOpen) {
            $('#host').autocomplete('option', 'minLength', 0).autocomplete('search', '');
    	} else {
            $('#host').autocomplete('close');
    	}
    });
```

**Comment by cigamit** [comment]
We would prefer it if you could do a pull request for this.  Thanks!

**Comment by cigamit** [comment]
Never mind.  I'm going to pull the logic from the dark theme, which works correctly.

**Comment by ddb4github** [comment]
Still double click after apply new main.js. Sent screen record to developer@cacti.net

**Comment by TheWitness** [comment]
Jing, developer[s]@cacti.net

**Comment by ddb4github** [comment]
> Jing, developer[s]@cacti.net

Ha, just check gmail, addr correct, but "Message too large" :disappointed_relieved:

**Comment by kim-fitness** [comment]
The logic from the dark theme also has the same issue. But it is easy to fix. I'll do a pull request for it

**Comment by cigamit** [comment]
All fixed now.
