### ISSUE TITLE
[1.2.6] Installer foreach() error

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#2960]
I'm doing a clean install of 1.2.6. I've blown away the db and cacti directory several times and I keep encountering this error:
```
Warning: Invalid argument supplied for foreach() in /cacti/cacti-1.2.6-dev/lib/installer.php on line 1679
```
There seems to be something wrong with the PHP detection logic. I'm performing this install on the same system where my production cacti instance runs, so I know the environment is OK. 
Here's a screenshot:
![image](https://user-images.githubusercontent.com/12864741/65380303-a0f29100-dc95-11e9-87ac-192149ce7d5a.png)
I'm trying to fiddle around with the code to see what's not working. I have PHP installed at /usr/local/php/bin/php, and I'm wondering if that's part of the problem.

**Comment by eschoeller** [comment]
Whew, I guess it just helped to hammer out a bug report. Because now I can move on after performing this command:
```
insert into settings(name,value) VALUES ('path_php_binary','/usr/local/php/bin/php');
```

**Comment by netniV** [comment]
I believe the issue is with the text being returned from the cli check as per https://github.com/Cacti/cacti/issues/2903

**Comment by netniV** [comment]
Cool, so it was an issue with the cli check aka the location of php itself.

**Comment by eschoeller** [comment]
Well, was this addressed in #2903 ? I don't think I should have had to do what I did directly in the database ...

**Comment by netniV** [comment]
The location looks odd.  I'm not sure it's in the default list of locations we look for PHP.

**Comment by netniV** [comment]
In fact, I think there's an enhancement request that I have opened for 1.3 to allow us to search the PATH for the location of various executables since people often have them in non-standard locations but do have them set in the path to be able to use them.

**Comment by eschoeller** [comment]
Well, in this case I was not able to proceed with the install without setting path_php_binary first. I haven't done a clean install like this in a while. I've been upgrading, and that setting is already present in my existing db. 
I guess if the installer can't find it automatically it somehow needs to prompt for the location. Even though it's asking for those paths earlier on. 
Perhaps the ordering of the installer needs to change .. setting the paths should happen *first* before the other stuff.

**Comment by netniV** [comment]
Yeah, that was something else that was previously found out but again, rearranging things in the installer like that needs some proper testing time which is what we would do for 1.3.

For now, it's one of those edge cases since most installs like you said already have that setting and if using a packaged version, new installs tend to get it added.  Plus, a lot of system do install a symbolic link to /usr/bin/php which is the default location we use.

**Comment by eschoeller** [comment]
Yeah, I should probably put a symlink in.
