### ISSUE TITLE
Cacti 1.2.6 Sync Device Template fails

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#2961]
I don't usually try to sync device templates, but I gave it a shot, and it yielded this error:
```
Fatal error: Call to undefined function api_data_source_cache_crc_update() in /cacti/cacti-1.2.6-prod/lib/utility.php on line 745
```

**Comment by netniV** [comment]
`api_data_source_cache_crc_update()` is found in api_data_source.php.  In utility.php, it doesn't include that file directly as the source include utility.php normally does.

So, feeding backwards, `repopulate_poller_cache()` and `push_out_host()` are two functions that call the crc_update function.  However, when I ran the following commands, the only results that were printed were for library sources which usually rely on the call to include other libraries.  So, it would be more beneficial to have the full stack trace.

```shell
[cacti]$ find . -name \*.php -exec grep -Hn "push_out_host" {} \; | cut -d':' -f 1 | xargs grep -HLn "api_data_source.php"
./plugins/thold/thold_webapi.php
./plugins/thold/thold_webapi.php
./cli/add_datasource.php
./lib/api_automation.php
./lib/api_automation.php
./lib/api_data_source.php
./lib/utility.php
./lib/utility.php
./lib/template.php
./lib/template.php
./lib/template.php
./lib/api_device.php
./lib/api_device.php
[cacti]]$ find . -name \*.php -exec grep -Hn "repopulate_poller_cache" {} \; | cut -d':' -f 1 | xargs grep -HLn "api_data_source.php"
./lib/installer.php
./lib/utility.php
```
