### ISSUE TITLE
Upgrade from 1.1.38 to 1.2.5 fail

### ISSUE THREAD

**Issue by velbon** [Cacti/cacti#2969]
**Describe the bug**
Upgrade failed and log is showing:
ALTER TABLE poller_output_realtime DROP PRIMARY KEY, ADD PRIMARY KEY (local_data_id, rrd_name, time, poller_id)
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by velbon** [comment]
MariaDB [cacti]> show variables like "%innodb_file%";
+--------------------------+-----------+
| Variable_name            | Value     |
+--------------------------+-----------+
| innodb_file_format       | Barracuda |
| innodb_file_format_check | ON        |
| innodb_file_format_max   | Barracuda |
| innodb_file_per_table    | ON        |
+--------------------------+-----------+

sudo php cli/audit_database.php --report
Checking Table: 'poller_output_realtime'
ERROR Index: 'PRIMARY', is missing from 'poller_output_realtime'
ERROR Index: 'PRIMARY', is missing from 'poller_output_realtime'
ERROR Index: 'PRIMARY', is missing from 'poller_output_realtime'

ERRORS: 3, WARNINGS: 0

Please what is the fix???

**Comment by netniV** [comment]
I believe it's already been reported before as https://github.com/Cacti/cacti/issues/2836, can you confirm and close if true?

**Comment by cigamit** [comment]
You need to set 'innodb_large_prefix=1', restart MySQL/MariaDB, and rerun the upgrade.

**Comment by velbon** [comment]
Dear All,
I tried all your support but it didn't work....so i manipulated the database:
***Created the primary key*****
ALTER TABLE poller_output_realtime ADD CONSTRAINT PRIMARY KEY (local_data_id, rrd_name, time, poller_id);  
***Verify the table and the primary keys***
show index from poller_output_realtime;
*** Run the failed command manually***
ALTER TABLE poller_output_realtime DROP PRIMARY KEY, ADD PRIMARY KEY (local_data_id, rrd_name, time, poller_id);

***Run the php commands again***
sudo php cli/upgrade_database.php
sudo php cli/audit_database.php --report 

*** Warning Error*****
-------------
Checking Table: 'poller_output_realtime'
WARNING Index: 'PRIMARY', does not exist in default Cacti.  Plugin possible

ERRORS: 0, WARNINGS: 1

***Check in the database again****
SHOW INDEX FROM version;
ALTER TABLE version ADD PRIMARY KEY(cacti) USING BTREE
*********************************************************************
Database reboot and upgrade completed

**Comment by cigamit** [comment]
That's likely due to the fact that it was removed before earlier.  So, now that the large_prefix is enabled, you should just be able to :+1: 

``` sql
ALTER TABLE poller_output_realtime ADD PRIMARY KEY (local_data_id, rrd_name, time, poller_id);
```
