### ISSUE TITLE
User menu does not always display properly on mobile devices

### ISSUE THREAD

**Issue by YongBoLiu** [Cacti/cacti#2973]
**Describe the bug**

**To Reproduce**
1. Assume user menu exist under top-tab 'TabU' . Ensure 'TabU' is collapsed. And there are more than one node in the user menu tree. Such as node A (default), and node B.
2. Use mobile device, or resize browser width. 
3. Click 'down arrow' --> 'TabU'.
4. Show the default  (node A) page. OK.
5. Select the other node (node B),  it's show up OK. And 'TabU' tab is collapsed.
6. Click 'down arrow' --> 'TabU' again. The user menu tree flash then hide. And the page go back to the default (node A) page. This is wrong.

**Expected behavior**
The user menu under top-tab 'TabU'， should works well as menu under Console tab.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

Related ticket : https://github.com/Cacti/cacti/issues/2910 
Related with: #2910

**Comment by tyit** [comment]
Yes, it has always been bad, and it is too different from the 0.8.8.x series.

**Comment by cigamit** [comment]
Resolved now.
