### ISSUE TITLE
Relocate Boost debug messages to boost debug log

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#2976]
I'd like to request that these style messages:

```
BOOST NOTE: Updating Local Data Id
```
be shifted from cacti.log to boost.log, as I feel that's a more appropriate location for them. Any objections?

**Comment by cigamit** [comment]
Nope.  Evening.

**Comment by cigamit** [comment]
Done.

**Comment by eschoeller** [comment]
Thanks!
