### ISSUE TITLE
Multi Output Fields are not parsed correctly

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#2979]
Here's another one. As you know I have a Main data collector and 3 'remote' data collectors. I have all of our Linux servers on one of the data collectors. When I ran into boost problems a few days ago I immediately disabled all of them to bring down the load on the system. Now I have attempted to re-enable them. In doing so, the poller run time on the main data collector increases dramatically as more of the linux servers are enabled on the remote data collector. 

After turning on medium level verbosity I'm seeing the main data collector flooded with these messages:
```
2019/09/25 19:55:52 - POLLER: Poller[1] Parsed MULTI output field 'finwait2:0' [map finwait2->finwait2]
2019/09/25 19:55:52 - POLLER: Poller[1] Parsed MULTI output field 'synsent:0' [map synsent->synsent]
2019/09/25 19:55:52 - POLLER: Poller[1] Parsed MULTI output field 'synrecv:0' [map synrecv->synrecv]
2019/09/25 19:55:52 - POLLER: Poller[1] Parsed MULTI output field 'closewait:0' [map closewait->closewait]
2019/09/25 19:55:52 - POLLER: Poller[1] Parsed MULTI output field 'file_sz:2048' [map file_sz->file_sz]
2019/09/25 19:55:52 - POLLER: Poller[1] Parsed MULTI output field 'totsck:621' [map totsck->totsck]
2019/09/25 19:55:52 - POLLER: Poller[1] Parsed MULTI output field 'tcpsck:10' [map tcpsck->tcpsck]
2019/09/25 19:55:52 - POLLER: Poller[1] Parsed MULTI output field 'udpsck:6' [map udpsck->udpsck]
2019/09/25 19:55:52 - POLLER: Poller[1] Parsed MULTI output field 'rawsck:0' [map rawsck->rawsck]
2019/09/25 19:55:52 - POLLER: Poller[1] Parsed MULTI output field 'ip_frag:0' [map ip_frag->ip_frag]
2019/09/25 19:55:52 - POLLER: Poller[1] Parsed MULTI output field 'plist_sz:245' [map plist_sz->plist_sz]
2019/09/25 19:55:52 - POLLER: Poller[1] Parsed MULTI output field 'procs:1.00' [map procs->procs]
2019/09/25 19:55:52 - POLLER: Poller[1] Parsed MULTI output field 'cswchs:137.00' [map cswchs->cswchs]
```
I recognize this output as being related to the data sources associated with our Linux devices, and not with anything the main data collector should be currently polling. 
So I am left wondering why the main data collector is taking on this multi output field parsing from the remote data collector. 

I attempted to move all the Linux servers to a different remote data collector to see if it would resolve the problem. But I'm still seeing all this activity on the main data collector.

**Comment by eschoeller** [comment]
Quick fix! It took me longer to apply the updates than for you to write the code I think.
So, yes the messages have gone away, but I'm still left wondering why the main data collector runtime is still increasing when I enable devices on a remote data collector

**Comment by cigamit** [comment]
It has to wait on all the remotes to finish.

**Comment by eschoeller** [comment]
Oh, that has not been my experience at all. Here take a look:
![cacti_graph_68034](https://user-images.githubusercontent.com/12864741/65655602-03bb9380-dfda-11e9-8ece-ec1c988dfb7a.png)
In this case the two remote pollers, thorn-b and thorn-c were consistently running longer than the main poller was.
I just kicked up the logging verbosity and found what it was doing in those additional 15 seconds, more of the MULTI output field stuff, but I think these are for items that run directly on the main poller

**Comment by cigamit** [comment]
Hmm, I'm going to have to give that some thought.
