### ISSUE TITLE
THOLD not executing command 

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#2981]
Hey Everyone 

I am having an issue with THOLD executing a shell script 
running the script manually works  and the script  is owned by apache the log shows the command was run but I dont see it working at all 

Looking for some help on this one to see if its me or THOLD

**Comment by netniV** [comment]
Make sure you have the full path to the script and that it definitely has execute permissions and SELinux isn't blocking it

**Comment by bmfmancini** [comment]
OK so I have selinux disabled  and I have put the full path to the command
this is in /usr/bin and from the apache user I can run it without putting the full path so its weird unless thold runs the command a bitter different than the shell does

**Comment by bmfmancini** [comment]
This is the command I am trying to run no go 
/usr/bin/curltest <DESCRIPTION> <HOSTNAME> <DSNAME> <CURRENTVALUE> <GRAPH>

here it is run from the commandline 

 /usr/bin/curltest 1 2 3 4 5 6 7
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

**Comment by bmfmancini** [comment]
2019/09/27 09:56:33 - THOLD WARNING: Threshold command execution for   - Errors - Gi0/0 [errors_in]] returned 1, with no output.

**Comment by bmfmancini** [comment]
getenforce
Disabled
-rwxr-xr-x    1 root root      562 Sep 26 17:57 curltest
I have also given apache full permissions to the file but still the same thing

**Comment by bmfmancini** [comment]
bash-4.2$ /usr/bin/curltest
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
uid=48(apache) gid=48(apache) groups=48(apache)

**Comment by cigamit** [comment]
Move this to the thold issues list.  Thanks!
