### ISSUE TITLE
realtime log non ordinary message

### ISSUE THREAD

**Issue by majed17** [Cacti/cacti#2982]
Peace, it happens when opening the realtime graphs and sounds like a buggy message but with no side effects
`2019/09/27 08:44:25 - CMDPHP Input Validation Not Performed for 'graph_nolegend' Backtrace: (/graph_realtime.php[61]:load_current_session_value(), /lib/html_utility.php[864]:get_request_var(), /lib/html_utility.php[344]:html_log_input_error(), /lib/html_validate.php[44]:cacti_debug_backtrace()) 
`
thought you ought to know about this

**Comment by cigamit** [comment]
Okay, this is resolved.  Since it was new in the 1.2.7 branch, we don't need a CHANGELOG.  Thanks for catching this one!

**Comment by majed17** [comment]
welcome

**Comment by majed17** [comment]
moved to 1.2.x (after 1.2.7) now there is: 

```
2019/10/07  08:58:31 - CMDPHP Input Validation Not Performed for 'node' Backtrace:   (/graph_view.php[219]:top_graph_header(),  /lib/functions.php[3247]:include_once(),  /include/top_graph_header.php[28]:draw_navigation_text(),  /lib/functions.php[2484]:get_request_var(),  /lib/html_utility.php[369]:html_log_input_error(),  /lib/html_validate.php[44]:cacti_debug_backtrace())
--
2019/10/07 08:56:10 - CMDPHP Input Validation Not Performed for  'graph_nolegend' Backtrace:   (/graph_realtime.php[61]:load_current_session_value(),  /lib/html_utility.php[889]:get_request_var(),  /lib/html_utility.php[369]:html_log_input_error(),  /lib/html_validate.php[44]:cacti_debug_backtrace())


```

**Comment by netniV** [comment]
that is a variable validation warning suggesting that we are not properly checking that variable before using it...

**Comment by majed17** [comment]
bug or something to configure?

**Comment by netniV** [comment]
Technically a bit of both as you can hide the message, but useful to know, log it as a new issue.
