### ISSUE TITLE
Cacti 1.2.5 & 1.2.6 is failing to graph after some errors

### ISSUE THREAD

**Issue by fisnnik** [Cacti/cacti#2983]
Cacti 1.2.5 & 1.2.6 is failing to graph after errors below, i have to cacti servers 1.2.5 & 1.2.6 running on debian 9, i have tried to upgrade version, this did not fix the problem.
After i reboot server everything goes back to normal, then after some days this happens again
I have enabled debug but nothing shows up there!

What this could be and how to troubleshoot and fix  this?

27/09/2019 07:35:00 - CMDPHP PHP ERROR WARNING Backtrace:   (/poller.php[795]:poller_maintenance(),   /lib/functions.php[4022]:exec_background(), /lib/poller.php[137]:exec(),   CactiErrorHandler())
--
27/09/2019 07:35:00 - ERROR PHP WARNING: exec(): Unable to fork   [/usr/bin/php -q '/var/www/html/poller_maintenance.php' > /dev/null   2>&1 &] in file: /var/www/html/lib/poller.php on line: 137
27/09/2019 07:35:00 - CMDPHP PHP ERROR WARNING Backtrace:   (/poller.php[794]:automation_poller_bottom(),   /lib/api_automation.php[2826]:exec_background(), /lib/poller.php[137]:exec(),   CactiErrorHandler())
27/09/2019 07:35:00 - ERROR PHP WARNING: exec(): Unable to fork   [/usr/bin/php -q '/var/www/html/poller_automation.php' -M > /dev/null   2>&1 &] in file: /var/www/html/lib/poller.php on line: 137
27/09/2019 07:35:00 - CMDPHP PHP ERROR WARNING Backtrace:   (/poller.php[793]:spikekill_poller_bottom(),   /poller.php[959]:exec_background(), /lib/poller.php[137]:exec(),   CactiErrorHandler())
27/09/2019 07:35:00 - ERROR PHP WARNING: exec(): Unable to fork   [/usr/bin/php -q '/var/www/html/poller_spikekill.php' > /dev/null   2>&1 &] in file: /var/www/html/lib/poller.php on line: 137
27/09/2019 07:35:00 - CMDPHP PHP ERROR WARNING Backtrace:   (/poller.php[792]:reports_poller_bottom(),   /lib/reports.php[1468]:exec_background(), /lib/poller.php[137]:exec(),   CactiErrorHandler())
27/09/2019 07:35:00 - ERROR PHP WARNING: exec(): Unable to fork   [/usr/bin/php -q /var/www/html/poller_reports.php > /dev/null 2>&1   &] in file: /var/www/html/lib/poller.php on line: 137

27/09/2019 10:15:00 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php[795]:poller_maintenance(), /lib/functions.php[4041]:exec_background(), /lib/poller.php[137]:exec(), CactiErrorHandler())
--
27/09/2019 10:15:00 - ERROR PHP WARNING: exec(): Unable to fork [/usr/bin/php -q '/var/www/html/poller_maintenance.php' > /dev/null 2>&1 &] in file: /var/www/html/lib/poller.php on line: 137
27/09/2019 10:15:00 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php[794]:automation_poller_bottom(), /lib/api_automation.php[2829]:exec_background(), /lib/poller.php[137]:exec(), CactiErrorHandler())
27/09/2019 10:15:00 - ERROR PHP WARNING: exec(): Unable to fork [/usr/bin/php -q '/var/www/html/poller_automation.php' -M > /dev/null 2>&1 &] in file: /var/www/html/lib/poller.php on line: 137
27/09/2019 10:15:00 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php[793]:spikekill_poller_bottom(), /poller.php[960]:exec_background(), /lib/poller.php[137]:exec(), CactiErrorHandler())
27/09/2019 10:15:00 - ERROR PHP WARNING: exec(): Unable to fork [/usr/bin/php -q '/var/www/html/poller_spikekill.php' > /dev/null 2>&1 &] in file: /var/www/html/lib/poller.php on line: 137
27/09/2019 10:15:00 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php[792]:reports_poller_bottom(), /lib/reports.php[1468]:exec_background(), /lib/poller.php[137]:exec(), CactiErrorHandler())
27/09/2019 10:15:00 - ERROR PHP WARNING: exec(): Unable to fork [/usr/bin/php -q /var/www/html/poller_reports.php > /dev/null 2>&1 &] in file: /var/www/html/lib/poller.php on line: 137

**Comment by cigamit** [comment]
Edit /etc/selinux/config and change enforcing to disabled.  Then reboot.  If you want to work with selinux, you must follow the common way of first placing it in permissive, and then using audit2allow to build a policy file for your Apache site.

**Comment by fisnnik** [comment]
Hi and thank you for your reply, i have checked but i dont have selinux on these servers! Also these servers are for cacti only, nothing else is installed there.

Maybe i can try a fresh install and move db and rrds to new installation?

**Comment by netniV** [comment]
Are you sure that path is correct and the location of your cacti software?  If not, update the settings table to the correct location

**Comment by fisnnik** [comment]
Yes path is correct, as i mentioned earlier mos of the time cacti works perfect, but once a week it fails to write graphs, errors above. After rebooting server everything goes back to normal.

should i try a fresh install and move db and rrds to new installation?

**Comment by cigamit** [comment]
After rebooting.  Sounds strange.

**Comment by cigamit** [comment]
Sounds like an environment problem.  So, I'll go ahead and close this one.
