### ISSUE TITLE
[1.2.6] Unexpected error message in Debian CI script

### ISSUE THREAD

**Issue by paulgevers** [Cacti/cacti#2984]
After I packaged Cacti 1.2.6 for Debian with commit f87ade3ab5 added to fix other errors, I still get an unexpected error in the Cacti log in the CI run.

All tests: https://ci.debian.net/packages/c/cacti/testing/amd64/
Example failure log: https://ci.debian.net/data/autopkgtest/testing/amd64/c/cacti/3018448/log.gz

The cacti log contains:
```
2019/09/23 06:20:26 - CMDPHP ERROR: A DB Row Failed!, Error: Query was empty
2019/09/23 06:20:26 - CMDPHP SQL Backtrace:  (/data_source_profiles.php[96]:profile_edit(), /data_source_profiles.php[559]:draw_edit_form(), /lib/html_form.php[114]:draw_edit_control(), /lib/html_form.php[311]:db_fetch_assoc(), /lib/database.php[452]:db_fetch_assoc_prepared(), /lib/database.php[466]:db_execute_prepared())
```

I don't know if there is any fix already available, in that case just pointing at it would be great.

**Comment by cigamit** [comment]
Thanks @paulgevers, perfect timing for a test.  Correcting.

**Comment by paulgevers** [comment]
@cigamit  worked like a charm. Thanks.
