### ISSUE TITLE
Changing Color Template does not update Aggregate

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#2987]
If you make changes to a color template these changes are not reflected in an existing Aggregate using that template until the color template is switched to something else, saved, then switched back, and saved again. 
It could be an awful amount of effort to find every graph which uses a particular template and then update all of those graphs for every change that is made to a color template. But it's equally also inconvenient to step through numerous Aggregates and switch around the color templates. Sort of defeats the purpose of using a template in the first place.

**Comment by netniV** [comment]
Did you sync the template to the devices/graphs?

**Comment by eschoeller** [comment]
Ah, well, I'm not sure that would have any effect? Yes, I know we can now run a sync on a graph template, but I don't see where that will impact the color template the Aggregate graph is using. The graph templates being referenced by these Aggregates is only using one color, whereas the Aggregate has three data sources, so it needs a color template, otherwise it will just draw three lines of the same color. 
I can do a step-by-step example if that would help better explain it.

**Comment by netniV** [comment]
So effectively, there needs to be a sync color template too?  So that once your changes are done and you are happy with it, you can apply it to all?

**Comment by cigamit** [comment]
There is a function push_out_aggregate() that can be called after each save.  This is a strait forward change.

**Comment by cigamit** [comment]
The only issue is that the drag and drop actions will delay the page update.  So, we might have to add a 'Sync Aggregates' dropdown to make is a smoother experience.

**Comment by cigamit** [comment]
@eschoeller, please test the 'Sync Aggregates' dropdown.

**Comment by eschoeller** [comment]
Thanks:) I think it might be a bit hard to remember to do, but at least it will be there somewhere. It's always good to peruse through that menu ... reminds you of things you *should* be doing, or gives you cool ideas about things you *could* be doing:) 
I'm still back on 1.2.6. I'll get up to 1.2.7, make sure I'm all good there, then snag this update. I'll have to re-create the situation, but it should not be difficult:) 
I'll just need a little bit of time.

**Comment by eschoeller** [comment]
I tested this, and it did not work :(

**Comment by eschoeller** [comment]
Hey, just checking in on this one too ... not sure if you can see my comments on a closed issue? I couldn't get this to work ...
