### ISSUE TITLE
Context menu overlaps when in tree editing mode

### ISSUE THREAD

**Issue by fskale** [Cacti/cacti#2988]
**Describe the bug**
When in tree editing mode, the context menu overlaps and any submenu (edit) is not accessible. 
**To Reproduce**
1. Go to 'Managment->tree'
2. Select a tree
3. Click on 'Edit tree'
4. Right click on 'tree member'

**Expected behavior**
The context menu should be visible and scrollable.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/12457151/65854431-ec273680-e35c-11e9-86a1-4b03a3e010ba.png)

Cacti version 1.2.6 and 1.2.7
**Desktop (please complete the following information):**
 - OS: [Windows, OSX, Linux]
 - Browser [chrome, safari, firefox]
 - Version [77.0.3865.90, 13.0.1 (14608.2.11.1.11), 69.0.1]

**Comment by netniV** [comment]
do you have any browser console errors when this occurs?

**Comment by fskale** [comment]
Hi @netniV,
i don't see any errors in the console.
Perhaps only a mapping problem ? Foreground -> Background (Mouse action).
I can scroll using the keyboard though.

**Comment by cigamit** [comment]
What theme is this, are you also zoomed in?  What is the zoom level?

**Comment by fskale** [comment]
Hi @cigamit,
i'm on no zoom level and the theme is "modern".
See the screenshot for details.
<img width="1498" alt="Bildschirmfoto 2019-09-30 um 19 52 01" src="https://user-images.githubusercontent.com/12457151/65903090-14924d80-e3bc-11e9-82b0-090d02236a77.png">

**Comment by cigamit** [comment]
Ohhh, I see.  How does it look in Englash?

**Comment by cigamit** [comment]
Nope, the context menu is in English, the branches are in a foreign language.  So, it's not that.  I'm also curious that the context menu's are transparent.  Man it looks like your theme is not right, or you have another plugin installed that makes the foreground transparent.

To confirm that, you can bring up the debug console, and look at the CSS section and inspect the dom of the context menu and see where the transparency is coming from.  I'm betting a plugin.

**Comment by fskale** [comment]
We only use the thold plugin on the new version.
I cloned the productive VM, deleted the plugin, removed it from the plugins dir, removed any debris in the database.
No change.
See screenshots. (when right clicked).
I think, it's the css along with the theme. (background-> transparent).
<img width="714" alt="Bildschirmfoto 2019-10-01 um 09 02 16" src="https://user-images.githubusercontent.com/12457151/65941143-9de06900-e42a-11e9-9dcb-333106e7712b.png">
![Bildschirmfoto 2019-10-01 um 09 02 25](https://user-images.githubusercontent.com/12457151/65941157-a2a51d00-e42a-11e9-94a5-b1813ab7efd3.jpg)

**Comment by fskale** [comment]
When changing the theme to classic, the context menu works !
So its a problem with the modern theme.
Will switch back to classic.

**Comment by fskale** [comment]
Found one problem with the classic theme and the login page.
The background is white and you don't see any characters, so i added color=black to the .ui-state-default css entry in the main.css (beginning with line 1973).
<pre>
.ui-state-default {
        background: #FFFFFF !important;
        border: none;
        font-weight: normal;
        padding: 2px;
        color: black;
}
</pre>

**Comment by cigamit** [comment]
Is this an Debian/Ubuntu install?  Did you use Aptitude (apt-get install)?

**Comment by cigamit** [comment]
Also, what you upload it the tree's CSS, and not the menu's.  The process is 1) Open debug menu, 2) Right click to bring up contxt menu, 3) Goto the debug menu and click the pointer all the way top left, 4) Move the mouse back to the context menu and click on it.  

This should put a bounding box around a portion of the context menu.  Then, below, in the debug menu, you will find some HTML displayed, you are looking for a &lt;li&gt; tag inside of a &lt;ul&gt; tag with the class class 'vakata-context', and the CSS will fall to the right.  So, you are almost there.

**Comment by fskale** [comment]
@cigamit,
what browser are you referring ?

**Comment by cigamit** [comment]
Firefox has the best I think.

**Comment by fskale** [comment]
So,
my colleague, a web developer fixed the problem.
He added the z-index and supplied the value 99.
<pre>
.vakata-context,
.vakata-context ul {
  margin: 0;
  padding: 2px;
  position: absolute;
  background: #f5f5f5;
  border: 1px solid #979797;
  box-shadow: 2px 2px 2px #999999;
  z-index: 99;
}
</pre>
I repackaged and rolled out via CI/CD.
works.
You can close the issue, but you should fix that problem as well as the problem for the classic theme. (white font color on white background!)

**Comment by cigamit** [comment]
Did you answer the question on where you installed Cacti from?

**Comment by fskale** [comment]
Download via Url: https://github.com/Cacti/cacti/archive/release/1.2.7.tar.gz
Repackage using our own CI/CD system.
No files will be altered but automatically put in place and rolled out via default config which then will configured using puppet (DB settings)

**Comment by fskale** [comment]
Could it be, that the github source code file changed after it has been published ?
Right now i see, that the MD5sum from the downloaded file changed as well as there were changes on the 29.09.2019 19:57 which weren't included in the file downloaded on monday.
The file 1.2.7.tar.gz i downloaded now directly from github !

md5sum 1.2.7.tar.gz 1.2.7-01-10-2019.tar.gz
149b43167e2ff47392ed7a51fb867880  1.2.7.tar.gz
dee1607baab3d77125b87c9227d79a1e  1.2.7-01-10-2019.tar.gz

This would clear things up as the files are not the same and github's own CI/CD system failed during publishment.
I had some ptoblems weeks ago with my own repo though.
Anyhow, i did a repackage and CI/CD and it works now using the new downloaded source code.
I will close the ticket.
Thanks for your help !
