### ISSUE TITLE
Allow Remote Data Collectors to maintain their own path variables

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#2989]
Hey Guys 

I had a DB crash on a remote poller and I dropped and re-created the db 
I imported cacti.sql and its up and running with the exception that the poller will not run the log shows that the location for spine is invlaid 

2019/09/30 11:43:02 - POLLER: Poller[2] ERROR: The spine path:  is invalid.  Poller can not continue!

![image](https://user-images.githubusercontent.com/13388748/65895167-02db8680-e379-11e9-9f3a-a381d216ce16.png)

Any ideas ?

**Comment by bmfmancini** [comment]
ls /usr/local/spine/bin/
spine

**Comment by bmfmancini** [comment]
weirdly when I run spine manually this is the output

2019/09/30 12:07:53 - SPINE: Poller[1] ERROR: SS[3] Script Server did not start properly return message was: 'U'
2019/09/30 12:07:53 - SPINE: Poller[1] ERROR: SS[4] Script Server did not start properly return message was: 'U'

**Comment by bmfmancini** [comment]
Very weird I went back to the main poller as well and saved the config tried replicating no go 
I also tried to drop the db and re-import still same issue

**Comment by bmfmancini** [comment]
Ok I went as far a reinstalling cacti

it refuses to see the spine directory ... I am at a loss

**Comment by bmfmancini** [comment]
Ok close so it seems any path cacti needs to check it cant see

i.e it cant see /usr/local/spine
its also reporting that the plugin files are missing but they are indeed there 

Permissions are fine  from what i can tell

**Comment by bmfmancini** [comment]
Well here is my issue 

Database changed
MariaDB [cacti]> SELECT name,value FROM settings where name like 'path_%';
+--------------+---------------------+
| name         | value               |
+--------------+---------------------+
| path_webroot | /var/www/html/cacti |


It doesnt make sense I have dropped this db so many times !

**Comment by bmfmancini** [comment]
@cigamit is there a way to manually insert the missing path records ?

**Comment by bmfmancini** [comment]
OK looks like I am back on track here is what I did 

Disabled the poller from the main poller
drop the db
created the db and imported as per usual 
finally got the cacti install page
came up as a new poller in the main poller page 
moved the devices to the poller named new poller 
delete old poller name 

All good

**Comment by cigamit** [comment]
The big thing, and if you want to do a doc pull request on this, it would help.  Here is what 'should' work anyway:

1) ALWAYS disable crontab on the new server
2) Perform a full Remote Data Collector install
3) Right now, it's going to create a new poller_id on the main server, so edit the config.php and change the poller_id back to the original
4) Remove the new ghost remote poller from the main Cacti server
5) Perform a full sync to the restored poller
6) Re-enable crontab.

So, as of 1.2.7, steps 3 & 4 are hacks.  We need a bug report on that.  I mean for the Remote Poller install to detect if a poller already exists for the server in question.

**Comment by bmfmancini** [comment]
It was very weird you would think that the table for settings would have been replicated no matter what as the other settings were fine so I think its something on the settings table

**Comment by cigamit** [comment]
Oh, so when you install, make sure you fill in the correct location for spine.  Changing it afterwards might be harder.  The full sync ignores the '%path%' stuff right now from the settings table.

**Comment by bmfmancini** [comment]
in my case even after a DB drop and re-import it would re-sync where I went wrong was not to disable the poller from the main poller to prevent a db sync

I will work on the Doc soon since I know this is a pain point

**Comment by cigamit** [comment]
Yea, forgot that too.  The remote sync should only be say once a day in my opinion now with the latest Cacti, or when you make some fundamental settings changes, or you were making a lot of changes with the Remote Data Collectors offline.  Most all actions sync dynamically to all Data Collectors now.

**Comment by cigamit** [comment]
Okay, this is resolved now.  All 'path_%' and '%_path' variables on the 'Paths' page from the remote poller are only saved there.  They are not overwritten when you save from the Poller ID 1 now either.

**Comment by cigamit** [comment]
This does not mean that one data collector can be using spine, and the other can use cmd.php.
