### ISSUE TITLE
Empty Data collectors/input methods @ Cacti 1.0.2 fresh install

### ISSUE THREAD

**Issue by jpobeda** [Cacti/cacti#299]
Hi there,

Fresh install:
Apache 2.4 | PHP 5.4 | MariaDB 5.5 | Cacti 1.0.2

Nothing really critical but I found these blanks Data input methods and Data queries.
Where did they come from?

I've just added 2 devices, created a couple of Trees and branches. Haven't done much yet so it's unlikely to be something I did by mistake I would say.

Any thoughts?
![cacti 1 0 2 blank data](https://cloud.githubusercontent.com/assets/13456559/22913059/82319824-f2cd-11e6-948a-a0565072b57f.png)

Can I just get rid of them?

**Comment by cigamit** [comment]
Please restart/upgrade.  There was a significant issue in Cacti 1.0.2.  It was corrected in 1.0.3.
