### ISSUE TITLE
Cacti Statistics Device Template Generates Errors for Graph Export Graph

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#2991]
Hey Guys 

I have been testing 1.2.7 and noticed that on a fresh install I see the following errors 

2019/09/30  19:42:35 - CMDPHP SQL Backtrace:   (/scripts/ss_gexport.php[10]:ss_gexport(),  /scripts/ss_gexport.php[15]:db_fetch_assoc(),  /lib/database.php[452]:db_fetch_assoc_prepared(),  /lib/database.php[466]:db_execute_prepared())
--
2019/09/30 19:42:35 - CMDPHP ERROR: A DB Row Failed!, Error: Table 'cacti.graph_exports' doesn't exist

I have only 1 device on this and just installed in 5 mins ago 
I see that same error in 1.2.5 as well

**Comment by cigamit** [comment]
That table is from the gexport plugin.  Have you not installed it?

**Comment by bmfmancini** [comment]
no this is a fresh install nothing added I can give you access to the server I am testing it on if you want to check something out since its just a VPS I used my install script to do the install

**Comment by cigamit** [comment]
I see the issue, you are plotting the Cacti stats for Graph Exports even though you don't have the plugin installed.  That's a Cacti bug for sure.

**Comment by bmfmancini** [comment]
Yea makes sense  I have no plugins installed at all right now

**Comment by cigamit** [comment]
Resolved.  Just update the script for now.

**Comment by gvoitis** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/42605037/71041867-db53b900-2132-11ea-81df-35df6f5b5685.jpg)


I run this config:

Cacti Version | 1.2.8
RRDtool Version Configured | 1.7.2+
SPINE 1.2.8 Copyright 2004-2019 by The Cacti Group
PHP Version | 7.3.12
10.1.43-MariaDB
