### ISSUE TITLE
Issue with editing data sources

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#2992]
I'm still on 1.2.6, however I don't see any updates to data_sources.php recently. 
I am getting this error:
```
Warning: implode(): Invalid arguments passed in /cacti/cacti-1.2.6-prod/data_sources.php on line 883
```
![image](https://user-images.githubusercontent.com/12864741/65943646-30faae00-e3ed-11e9-8511-759b2e720494.png)

**Comment by eschoeller** [comment]
It's a long-shot, but I think when I executed this query:
```
ALTER TABLE data_input_data ADD INDEX data_template_data_id (data_template_data_id);
```
during issue #2978 this may have broken this.

**Comment by netniV** [comment]
This error is actually because it attempts to find the data templates for the given data source name and then concatenate the ids of the templates together to query against.  As it isn't finding a template, there are no ids and the variable being used was never primed.

This issue exists under 1.2.7 as well because `$dtids` isn't primed.  This does make me wonder if the two queries above are correct or not.

**Comment by cigamit** [comment]
This looks like database corruption to me.  An alter of a table to add an index should not have done that.

**Comment by netniV** [comment]
I would agree that adding an index shouldn't have cause column corruption.  If anything I would have though it would have lost the row itself.  But I guess if the table is corrupted already, it's possible?

**Comment by cigamit** [comment]
@eschoeller, you might want to consider a restore from before this happened.  Check the Cacti.log for any SQL type errors too.  Keep us posted.

**Comment by eschoeller** [comment]
Yeah. I think I'm in trouble here. Seeing a lot of these now too:
```
2019/09/29 10:28:43 - ERROR PHP NOTICE: Undefined variable: initial_time in file: /cacti/cacti-1.2.6-prod/poller_boost.php  on line: 638
2019/09/29 10:28:43 - CMDPHP PHP ERROR NOTICE Backtrace:  (/poller_boost.php[137]:output_rrd_data(), /poller_boost.php[311]:boost_process_local_data_ids(), /poller_boost.php[450]:boo
st_process_output(), /poller_boost.php[638]:CactiErrorHandler())
2019/09/29 10:28:43 - ERROR PHP NOTICE: Undefined variable: outbuf in file: /cacti/cacti-1.2.6-prod/poller_boost.php  on line: 627
2019/09/29 10:28:43 - CMDPHP PHP ERROR NOTICE Backtrace:  (/poller_boost.php[137]:output_rrd_data(), /poller_boost.php[311]:boost_process_local_data_ids(), /poller_boost.php[450]:boo
st_process_output(), /poller_boost.php[627]:CactiErrorHandler())
```
Stepped away from this for a short while and now it's blown up on me somehow. Everything was fine when I left it a few days ago!
Not sure what I can do. I guess I could ask our database team to try and roll back the db. Not sure what I'd lose then.

**Comment by checkmate777** [comment]
Regarding $outbuf: go to that file, line 624: There's typo in the variable name: outbut. You might want trying to change that to outbuf :)

**Comment by netniV** [comment]
I've already fixed that in #3006

**Comment by eschoeller** [comment]
Yeah, I need to upgrade to 1.2.7. I think I'm going to get a lot of my issues sorted out.

**Comment by netniV** [comment]
My fix is for 1.2.8 👍

**Comment by eschoeller** [comment]
Upgraded to 1.2.x current and I'm still getting this error.

**Comment by eschoeller** [comment]
These are new data templates that I have created recently. I'm looking around in data_source.php around line 893 trying to debug this. I have run a few queries by hand I think I have found some oddities.
```
mysql> select GROUP_CONCAT(DISTINCT data_source_name ORDER BY data_source_name) AS data_source_names FROM data_template_rrd WHERE data_template_id =744 GROUP BY data_template_id ORDER BY data_source_names;
+--------------------------------------------------------------------------+
| data_source_names                                                        |
+--------------------------------------------------------------------------+
| ,delta_time,flow,gain,signal,signal_strength,total,velocity,volume_total |
+--------------------------------------------------------------------------+
1 row in set (0.00 sec)
```
I can't figure out where that leading comma is coming from yet. 
Then this query completely fails:
```
mysql> SELECT data_template_id,GROUP_CONCAT(DISTINCT data_source_name ORDER BY data_source_name) AS data_source_names FROM data_template_rrd WHERE local_data_id=0 GROUP BY data_template_id HAVING data_source_names = ",delta_time,flow,gain,signal,signal_strength,total,velocity,volume_total";
Empty set (0.01 sec)

mysql> SELECT data_template_id,GROUP_CONCAT(DISTINCT data_source_name ORDER BY data_source_name) AS data_source_names FROM data_template_rrd WHERE local_data_id=0 GROUP BY data_template_id HAVING data_source_names = "delta_time,flow,gain,signal,signal_strength,total,velocity,volume_total";
Empty set (0.02 sec)
```
Which then triggers the implode error since the query comes back with nothing. 
I also have several data_template_ids with no associated names:
```
mysql> SELECT data_template_id,GROUP_CONCAT(DISTINCT data_source_name ORDER BY data_source_name) AS data_source_names FROM data_template_rrd WHERE local_data_id=0 GROUP BY data_template_id HAVING data_source_names = "";
+------------------+-------------------+
| data_template_id | data_source_names |
+------------------+-------------------+
|              359 |                   |
|              413 |                   |
|              450 |                   |
|              720 |                   |
|              721 |                   |
|              722 |                   |
|              723 |                   |
|              724 |                   |
|              725 |                   |
|              726 |                   |
|              727 |                   |
|              728 |                   |
|              729 |                   |
|              730 |                   |
|              731 |                   |
|              737 |                   |
|              738 |                   |
|              739 |                   |
|              744 |                   |
|              745 |                   |
+------------------+-------------------+
20 rows in set (0.02 sec)
```

**Comment by eschoeller** [comment]
OK, I found some commonalities between all these templates. They are all "generic" data source templates which are used across multiple devices with the OID field templated as custom data input as well as the internal data source name. I've been doing this for many years. Here is an example configuration of one data template:
![image](https://user-images.githubusercontent.com/12864741/66286199-8b808800-e88d-11e9-842a-c2e35fc8e38c.png)
I have poked around at a few data sources using these templates, and they are all exhibiting the implode() error. So I think having the internal data source name set to custom input is causing the problem.

**Comment by netniV** [comment]
Some interesting diagnostics there, we will review and come back to you.

**Comment by cigamit** [comment]
This looks related to the catastrophe that was lib/html_utility.php and the inject_form_variables() function that has undergone several updates since 1.2.5.  I would like you to update lib/html_utility.php and lib/functions.php from the 1.2.x branch.  There may be some database damage though as I had alluded to earlier though.  It's likely repairable though.

**Comment by eschoeller** [comment]
Ok I can take a look in a few hours. Skiing right now :)

Eric.

**Comment by eschoeller** [comment]
I was already on the most current html_utility.php. Just upgraded functions.php. I'm still seeing the issue.

**Comment by eschoeller** [comment]
Any further thoughts on this one?

**Comment by cigamit** [comment]
Database corruption.  Can you send a fresh copy of the database.  I'll see what I can do on Sunday.  If not, next weekend.

**Comment by eschoeller** [comment]
Sorry for the delay. Just sent it. Let me know when you have it so I can remove it.

**Comment by cigamit** [comment]
Just restore from the last good backup.  Going to close this now.

**Comment by cigamit** [comment]
Make sure you get to 1.2.8 ASAP as the prior versions caused this issue.
