### ISSUE TITLE
Create / Edit - Automation Graph Rule -  Graph Type Dropdown empty

### ISSUE THREAD

**Issue by C00kiekiller** [Cacti/cacti#2994]
**Describe the bug**

When editing or creating a graph automation rule the graph type drop-down is empty.

**To Reproduce**
1. Go to 'automation'
2. Click on 'Graph Rules'
3. Click on 'Add' or 'Existing Rule'
4. See error  - Drop-down Graph Type is empty

**Expected behavior**
See the available types - for example  In/Out Bits (64-bit) or In/Out Bytes (64-bit)

**Screenshots**
![2019-10-01 12_32_39-Console -_ Graph Rules -_ (Edit)](https://user-images.githubusercontent.com/16733284/65955521-9fb92500-e448-11e9-8da8-ce44925622cc.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Version 1903 Build 18362.356
 - Browser: chrome, Firefox, Edge
 - Version: always latest

**Server**
- OS: Debian 9.9.0
- Version: Cacti version 1.2.6
- Database: mysql  Ver 15.1 Distrib 10.1.41-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
- Webserver: Apache 2

**Comment by bmfmancini** [comment]
What cacti version are you using ?

**Comment by C00kiekiller** [comment]
>> What cacti version are you using ?

>**Server**
>Version: Cacti version 1.2.6

**Comment by C00kiekiller** [comment]
Bug was fixed in 1.2.7

**Comment by netniV** [comment]
Yay, I do like it when the fix is that we've already fixed it.  👍 

It's also good to see people filling in the bug report info to give a clearer picture of what software versions we are dealing with 🥇
