### ISSUE TITLE
Tree Branch Report only displays single column - not multi column

### ISSUE THREAD

**Issue by daepunt** [Cacti/cacti#2995]
When defining a (Nectar) Report, consisting of a Tree Branch, the graphs of that Branch are displayed in one column only, regardless of the Report Columns setting. I would like to have 2 or 4 columns, but the setting does not seem to do anything. I experimented with Custom HTML, Alignment (or Report and Item) and nothing helps. It does work when adding separate Graphs as single Items to the Report, but the beauty of adding a Tree Branch to a Report is that it's easier to add Graphs and apply Sorting etc. I checked up to Cacti 1.2.6 on debian-testing.

**Comment by cigamit** [comment]
That is quite odd.  I am able to product multiple columns.  Can you show the example item edit and the general tab so we can have context.  Thanks.

**Comment by daepunt** [comment]
Hi @cigamit!

Thanks for your reply. I have attached screenshots of the general report settings, item edit and preview.

Please let me know if you need anything else.

Best regards,

Dae.

![2019-10-03_11-08-21](https://user-images.githubusercontent.com/6223232/66114211-a4a7e100-e5ce-11e9-9d5b-f267de813796.jpg)
![2019-10-03_11-09-27](https://user-images.githubusercontent.com/6223232/66114212-a4a7e100-e5ce-11e9-8a0a-8052823d5ed6.jpg)
![2019-10-03_11-10-38](https://user-images.githubusercontent.com/6223232/66114213-a4a7e100-e5ce-11e9-813c-dc70bfb4ad02.jpg)

**Comment by cigamit** [comment]
How does it look when you send it?  I think what is happening is that you have your user profile setting to 'Expand Devices' which forces each template into a new row.  Please verify.  It's still a bug.  However, this should give you a workaround in the near term anyway.

**Comment by cigamit** [comment]
The reason it's a bug, is we should be giving you that option when you save the Report.

**Comment by daepunt** [comment]
When I send the report, it shows only one column, just like the preview.
I attached my User Settings. Expand Devices is turned off, although the on/off switch is green :-)

![2019-10-03_14-15-14](https://user-images.githubusercontent.com/6223232/66125960-8c44c000-e5e8-11e9-820a-b8872a97a2b4.jpg)

**Comment by cigamit** [comment]
Okay, thanks for that.  Let me see if I can do a workaround to turn off expand devices by default until we can add a column.

**Comment by daepunt** [comment]
Expand Devices is disabled by default, as far as I know.
And I never had it turned on, so it doesn't seem to be related.

**Comment by cigamit** [comment]
Okay, this is the way it has been fixed, if you select 'cascade to all tree branches', you will get the behavior that you are seeing.  If you unselect 'cascade to all tree branches', all the graphs will be in the column arrangement you desire.  You should update lib/html_reports.php and lib/reports.php from the 1.2.x branch.
