### ISSUE TITLE
User Graph Options - Rights value not shown correctly

### ISSUE THREAD

**Issue by C00kiekiller** [Cacti/cacti#2996]
**Describe the bug**
Disable the user rights to see the Tree/List/Preview View under the "graph options" with the slider and save the user. The user has the correct rights in the database but the slider still shows enabled but it should be shown as disabled. The slider show all the time enabled no matter to  the stored database value.

**To Reproduce**
1. Go to 'Console'
2. Go to 'Configuration'
3. Click on 'Users'
4. Go to 'General Tab'
5 Disable under 'Graph Options' the setting 'User Has Rights to Tree View' with the Slider 
6. Click on 'Save'
7. Click on the Operation successful popup 'Ok'
8. See error - The slider was enabled again
9. When going back to 'user overview' and select the same user again the slider is shown as enabled but the right was correctly disabled 

This issue belong to all sliders Tree/List/Preview View under the graph Options no matter which one is disabled.

**Expected behavior**
When the right was disabled the slider should be shown as disabled.

**Screenshots**

- **Before save**
![2019-10-01 14_15_27-Console -_ Users -_ (Edit)](https://user-images.githubusercontent.com/16733284/65961174-4d7f0080-e456-11e9-8e49-8378671d1233.png)
- **After save and open/edit the user again**
![2019-10-01 14_15_50-Console -_ Users -_ (Edit)after](https://user-images.githubusercontent.com/16733284/65961177-51ab1e00-e456-11e9-9eb1-5f346765beb9.png)

**Desktop (please complete the following information):**
- OS: Windows 10 Version 1903 Build 18362.356
- Browser: chrome, Firefox, Edge
- Version: always latest

**Server**
- OS: Debian 9.9.0
- Version: Cacti version 1.2.7
- Database: mysql Ver 15.1 Distrib 10.1.41-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
- Webserver: Apache 2

**Comment by cigamit** [comment]
Just confirming.  That's pretty bad.

**Comment by cigamit** [comment]
Okay, update lib/html_utility.php and this will be resolved.  Looking at a quick release of 1.2.8 as this is fairly serious.
