### ISSUE TITLE
Lot of graph not in Tree

### ISSUE THREAD

**Issue by nicolapiazzi** [Cacti/cacti#2997]
Create a router and put it under a tree, 
If you create Traffic Graph that are not  bits with 95 percentile they are not show in graph tab
![1](https://user-images.githubusercontent.com/54310887/65978156-76fa5500-e473-11e9-82ce-655120254a54.PNG)
![2](https://user-images.githubusercontent.com/54310887/65978210-93968d00-e473-11e9-8755-43213d91b991.PNG)

**Comment by cigamit** [comment]
Do you have permissions to view the Graph?  Go under your user profile, and check the 'Expand Devices'.  Then, go back to the tree and see if the 95th ptile stuff is still there.  Then, check your permissions to view.

**Comment by nicolapiazzi** [comment]
Hi cigamit, incredible, it will be visible after logout/login, i checked permission but no way to know, i created other couple with broarcast, same thing, visible after logout / login, 
If is so is not a big problem.

**Comment by cigamit** [comment]
Okay, closing.

**Comment by nicolapiazzi** [comment]
It works for me now using a CDEF
