### ISSUE TITLE
Blank arguments can lead to extra spaces in script arguments

### ISSUE THREAD

**Issue by vaclav-krauz** [Cacti/cacti#2999]
**Describe the bug**

version 1.2.6

When a device has set snmp version 2, it has empty items of snmp settings for version 3 and when I have data input method (script server) where I use all snmp settings like special type codes [snmp_community]...:

```
ss_gateway_wan_gpns_monitoring.php <func> <ip> <interface> <circuit_size_down> <circuit_size_up> <_community> ...
```

I get this error from poller:

ERROR PHP ERROR: Uncaught ArgumentCountError: Too few arguments to function ss_get_bandwidth(), 8 passed in /opt/mikenopa/cacti/site/script_server.php on line 222 and exactly 14 expected 

when I check it in poller_item, I can see this: 

```
...oring.php 'ss_get_bandwidth' '172.17.0.3' '2' '100000' '100000' 'public'       '2' '161' '500'
```

![Screenshot at 2019-10-02 13-26-11](https://user-images.githubusercontent.com/17041727/66040922-ebd39a80-e518-11e9-9f71-d8571f1e2052.png)

there is a big gap between 'public' and '2' (the yellow lines), so required fields  `<_community>` `<_username>` `<_password>` `<_auth_protocol>` `<_priv_passphrase>` `<_priv_protocol>` `<_context>` `<_version>` are translated like an empty character without quotes

![Screenshot at 2019-10-02 12-53-43](https://user-images.githubusercontent.com/17041727/66040183-20465700-e517-11e9-8f9d-a0d1faa1fdac.png)

**Expected behavior**
cacti should store the full script path without the extra spaces like " ... 'public' '' '' '' '' '' '' '2' ..."

**Comment by vaclav-krauz** [comment]
I would do something like this

1517 function get_full_script_path($local_data_id) {
...
1548         if (cacti_sizeof($data)) {
1549                 foreach ($data as $item) {
1550                         $value = cacti_escapeshellarg($item['value']);
1551                         if ('' === $value) {
1552                             $value = "''";
1553                         }   
1554                         $full_path = str_replace('<' . $item['data_name'] . '>', $value, $full_path);
1555                 }
1556         }


it works now

POLLER: Poller[1] Device[17] DS[116] SERVER: /opt/mikenopa/cacti/site/scripts/ss_gateway_wan_gpns_monitoring.php 'ss_get_bandwidth' '172.17.0.3' '2' '100000' '100000' 'public' '' '' '' '' '' '' '2' '161' '500', output: circuit_size_down:100000 circuit_size_up:100000 in_octets:3712342191 out_octets:1805196573

**Comment by netniV** [comment]
I've updated the title of the issue and fixed up a bit of formatting in your original post (feel free to edit and see how it works).

If a parameter is replaced, it should be replaced with a blank and I believe that it is.  The problem is that the space before or after that argument is not trimmed because we don't know if it should be or not.

To be fair though, I have never really noticed this issue with my own systems but does lead to an interesting thought this may be what's affecting one or two other obscure errors we've seen in the past.

**Comment by netniV** [comment]
Oh and thanks for the technical break down too, that helps 👍

**Comment by cigamit** [comment]
Just modify your Data Input method and enclose the arguments in single quotes:

``` console
php -q <path_cacti>/scripts/somescript.sh '<hostname>' '<some_argument>'
```

That should immediately solve the issue.

**Comment by cigamit** [comment]
I guess we could add that simple check, and just trim the single quotes for people who have already made this change too.  Less tickets for us.

**Comment by cigamit** [comment]
Have to be careful about Windows though.

**Comment by cigamit** [comment]
Good catch.  Bad assumption on my part.  Resolved.
