### ISSUE TITLE
[Cacti-1.2.6] Main Poller status Heartbeat

### ISSUE THREAD

**Issue by jvickya** [Cacti/cacti#3001]
I use cacti 1.2.6 and have problem below
![image](https://user-images.githubusercontent.com/51222755/66107235-f01bb880-e5e9-11e9-8279-73a5f95e4c04.png)

![image](https://user-images.githubusercontent.com/51222755/66107248-f7db5d00-e5e9-11e9-83ff-151c56582926.png)

Cronjob
*/5 * * * * cacti php /var/www/html/cacti/poller.php > /dev/null 2>&1

Log Cronjob
tail -f /var/log/cron
Oct  3 13:55:01 cacti-bk CROND[10169]: (cacti) CMD (php /var/www/html/cacti/poller.php > /dev/null 2>&1)
Oct  3 14:00:01 cacti-bk CROND[10179]: (cacti) CMD (php /var/www/html/cacti/poller.php > /dev/null 2>&1)
Oct  3 14:01:01 cacti-bk CROND[10186]: (root) CMD (run-parts /etc/cron.hourly)
Oct  3 14:01:01 cacti-bk run-parts(/etc/cron.hourly)[10186]: starting 0anacron
Oct  3 14:01:01 cacti-bk run-parts(/etc/cron.hourly)[10195]: finished 0anacron
Oct  3 14:05:01 cacti-bk CROND[10201]: (cacti) CMD (php /var/www/html/cacti/poller.php > /dev/null 2>&1)
Oct  3 14:10:01 cacti-bk CROND[10210]: (cacti) CMD (php /var/www/html/cacti/poller.php > /dev/null 2>&1)
Oct  3 14:15:01 cacti-bk CROND[10220]: (cacti) CMD (php /var/www/html/cacti/poller.php > /dev/null 2>&1)
Oct  3 14:20:01 cacti-bk CROND[10230]: (cacti) CMD (php /var/www/html/cacti/poller.php > /dev/null 2>&1)
Oct  3 14:25:02 cacti-bk CROND[10313]: (cacti) CMD (php /var/www/html/cacti/poller.php > /dev/null 2>&1)

Please support. Many thanks.

**Comment by netniV** [comment]
That issue with the display of arg1 has been reported before and has been corrected already.

**Comment by jvickya** [comment]
How about heartbeat status? How to fix?

**Comment by cigamit** [comment]
Fix it by going to the 1.2.x branch, and downloading lib/html_utility.php.  Sorry for that.

**Comment by cigamit** [comment]
We hope to have a 1.2.8 out shortly.  But we are all busy at the moment.

**Comment by jvickya** [comment]
Hi cigamit,
I loaded lib/html_utility.php but not work
