### ISSUE TITLE
Graphs / List View Upper right button not working v1.2.5

### ISSUE THREAD

**Issue by andermat8** [Cacti/cacti#3002]
When using list view under graphs the button will not work after clicking on one of the links:
![image](https://user-images.githubusercontent.com/29753529/66126363-4c191980-e5b7-11e9-910a-8f4997d1bc02.png)

The button will stay red (or grayed out) so it is not clickable:
![image](https://user-images.githubusercontent.com/29753529/66126499-8edaf180-e5b7-11e9-8ee5-00f0a028e83c.png)

Like most screens, there is no back button option so you have to click on something else and then go back into the list view.  Another workaround is to refresh the browser.  It's more of an annoyance / bug but figured I should let you know as it did not work this way in a previous version (1.1.38).

**Comment by netniV** [comment]
I think this has already been fixed:
https://github.com/Cacti/cacti/issues/2917

**Comment by cigamit** [comment]
Closing.
