### ISSUE TITLE
Cannot add new network discovery range

### ISSUE THREAD

**Issue by nomisunrider** [Cacti/cacti#3003]
**Describe the bug**
I just upgraded to version 1.2.7 and wanted to setup network device discovery.
Tried to add a new network discovery range and received the below error window.

I checked the cacti logs and see these related errors:

```
2019/10/03 14:46:22 - ERROR PHP WARNING: strpos() expects parameter 1 to be string, array given in file: /usr/share/cacti-1.2.7/lib/api_automation.php  on line: 3027
2019/10/03 14:46:22 - CMDPHP PHP ERROR WARNING Backtrace:  (/automation_networks.php[43]:form_save(), /automation_networks.php[70]:api_networks_save(), /automation_networks.php[244]:automation_calculate_total_ips(), /lib/api_automation.php[3124]:automation_get_network_info(), /lib/api_automation.php[3027]:strpos(), CactiErrorHandler())
2019/10/03 14:46:22 - ERROR PHP WARNING: explode() expects parameter 2 to be string, array given in file: /usr/share/cacti-1.2.7/lib/api_automation.php  on line: 3029
2019/10/03 14:46:22 - CMDPHP PHP ERROR WARNING Backtrace:  (/automation_networks.php[43]:form_save(), /automation_networks.php[70]:api_networks_save(), /automation_networks.php[244]:automation_calculate_total_ips(), /lib/api_automation.php[3124]:automation_get_network_info(), /lib/api_automation.php[3029]:explode(), CactiErrorHandler())
```

**To Reproduce**
Try to add a new network discovery range

**Expected behavior**
A new range is added

**Screenshots**
![image](https://user-images.githubusercontent.com/13275125/66160552-fd3ba600-e5ef-11e9-8ca1-a6e5f35dfc5b.png)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by netniV** [comment]
There was a change made to improve the accuracy of the range detection.  However, it would appear this has somehow evaded testing so far. Can you clarify what you had in the boxes when you were saving it? Especially the subnet/range.

**Comment by nomisunrider** [comment]
Anything I tried errors the same way.

10.84.0.0/23
192.168.0.0/24
192.168.0.1

**Comment by netniV** [comment]
What version of PHP are you running btw?

**Comment by netniV** [comment]
Are you entering more than one range? If so, that's not supported as far as I know.

**Comment by nomisunrider** [comment]
I'm only trying one at a time, though the dialogue/directions indicate more than one at a time is supported (see screenshot)

# php --version
PHP 7.3.10 (cli) (built: Sep 24 2019 09:20:18) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.10, Copyright (c) 1998-2018 Zend Technologies


![image](https://user-images.githubusercontent.com/13275125/66233190-5a972c00-e6b0-11e9-893f-15b4666f4560.png)

**Comment by netniV** [comment]
Yeah i was wondering about that as I noticed the textbox seems to indicate that it can hold more than one value, but I'm sure in the installer it is only one so it makes me wonder.  @cigamit or @TheWitness may know better on that score.

As for the values you had, then each worked fine for me.  The only thing that didn't work was when I specified multiple ones.

**Comment by cigamit** [comment]
You can add more than one network in the Subnet range "separated by comma" according to the tip on that form element.

**Comment by netniV** [comment]
I must have missed the comma suggestion.  I'll get it another try.

**Comment by nomisunrider** [comment]
Has anyone else tested it with php 7.3.10?

**Comment by netniV** [comment]
I'm running on 7.2, I'd have to see about switching versions but I doubt that is the issue here

**Comment by nomisunrider** [comment]
Here is an interesting note.  Right underneath the input "Subnet Range" text area is the field:
"Total IP Addresses
Total addressable IP Addresses in this Network Range"

No matter what I enter, this stays at 0.  It looks like it should update "live" with the number of addresses.  Does it do so for you?  It does not for me.

I've also tried in multiple browsers, so it is not a browser dependent.

**Comment by netniV** [comment]
Yes, that updates for me though I think it was only when I was saving.  Are you getting any console errors? I'll try and look into this again tonight.

**Comment by nomisunrider** [comment]
I only get the errors I put in the initial entry of this issue.  Even enabling developer debug mode doesn't show anything...

**Comment by netniV** [comment]
For now, I've relabelled this as unverified as I cannot reproduce it.  I've raised a separate issue for trimming spaces off the IP range since they are not valid characters.

This is logged as *Automation network range with spaces fails validation #3017*

**Comment by nomisunrider** [comment]
Do you have any advice how I can generate some more useful errors to try to figure this out?
No matter what debug levels I set in cacti options, nothing more appears in logs file for this.

**Comment by nomisunrider** [comment]
NM.  You can close this.  
I found that for some reason this file was not updated properly and was from an older version.  I pulled the latest and it now works.  So sorry for the confusion...

automation_networks.php

Thank you

**Comment by cigamit** [comment]
Great, thanks for confirming!
