### ISSUE TITLE
1.2.5 showing db connection errors but everything seems to be working (Remote poller setup)

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3004]
Hey Guys 

This is my situation and I don't know if this is a bug or my setup 

I have 3 pollers and 1200+ devices 

each poller has 8cpu and 8GB of ram 

A few times this month both the remote pollers went into heartbeat mode 

When I look into it there is a huge backup of boost records as if the poller was offline for some time

even though the network is fine  what I notice is that in cacti_stderr.log shows  failed connections back to the main poller  even when  everything is working fine the messages come in 

I am using spine 1.2.5 4 processes 4 threads 

Here is my DB setup on the main and remote server 

# Main 

```
# this is read by the standalone daemon and embedded servers
[server]

# this is only for the mysqld standalone daemon
[mysqld]
#max_allowed_packet=16777216
max_allowed_packet=128M
max_heap_table_size = 2G
tmp_table_size=4GB
join_buffer_size=250M
innodb_file_per_table=on
innodb_file_format=barracuda
innodb_buffer_pool_size=2000M
innodb_additional_mem_pool_size = 90M
innodb_doublewrite = off
innodb_flush_log_at_trx_commit = 2
innodb_flush_method =  O_DIRECT
innodb_large_prefix = 1


character-set-server=utf8mb4
collation-server=utf8mb4_unicode_ci



# this is only for embedded server
[embedded]

# This group is only read by MariaDB-5.5 servers.
# If you use the same .cnf file for MariaDB of different versions,
# use this group for options that older servers don't understand
[mysqld-5.5]

# These two groups are only read by MariaDB servers, not by MySQL.
# If you use the same .cnf file for MySQL and MariaDB,
# you can put MariaDB-only options here
[mariadb]

[mariadb-5.5]
```

# Remote 

```
# These groups are read by MariaDB server.
# Use it for options that only the server (but not clients) should see
#
# See the examples of server my.cnf files in /usr/share/mysql/
#

# this is read by the standalone daemon and embedded servers
[server]

# this is only for the mysqld standalone daemon
[mysqld]


innodb_file_format = Barracuda
character_set_client = utf8mb4
max_allowed_packet = 16777777
join_buffer_size = 32M
innodb_file_per_table = ON
innodb_large_prefix = 1
innodb_buffer_pool_size = 250M
innodb_additional_mem_pool_size = 90M
innodb_flush_log_at_trx_commit = 2


# this is only for embedded server
[embedded]

# This group is only read by MariaDB-5.5 servers.
# If you use the same .cnf file for MariaDB of different versions,
# use this group for options that older servers don't understand
[mysqld-5.5]

# These two groups are only read by MariaDB servers, not by MySQL.
# If you use the same .cnf file for MySQL and MariaDB,
# you can put MariaDB-only options here
[mariadb]

[mariadb-5.5]
```

On the main poller, I have set the max connections to 2k 

The message I get is 
```
MYSQL: Connection Failed: Error:'2003', Message:'Can't connect to MySQL server (Host name)
```

I know I am using mariadb 5.5 which I also know cacti recommended version 10 for a network issue would it be related to this or am I going the wrong way with this?

I plan on doing a update to mariadb 10 anyways  

Any help would be greatly appreciated 

Thanks!

**Comment by bmfmancini** [comment]
Also one more thing to note that the more devices on the poller the more the messages appear could this be a spine-related issue? possibly not handling the db connections properly?

**Comment by bmfmancini** [comment]
mariadb logs are clean on the remote side and local side  no auth errors are shown 
but I would think if its a misconfigured creds issues it would be all or nothing

**Comment by bmfmancini** [comment]
One more thing that I can think of is that both pollers are using the same credentials maybe that might explain the unable to connect randomly ??? I will verify this theory by changing on of the usernames

**Comment by bmfmancini** [comment]
I am still seeing these errors and I can't explain it 

Replication works fine graphs work fine
I connect to the main DB from the remote site using CLI
I'm scratching my head on this one 

Any help with be appreciated !

**Comment by bmfmancini** [comment]
Hey  all 

BTW here is my db stats I recently restarted the DB 

Uptime: 1677  Threads: 162  Questions: 2809219  Slow queries: 0  Opens: 275  Flush tables: 2  Open tables: 170  Queries per second avg: 1675.145

**Comment by bmfmancini** [comment]
Ok ive been monitoring this and still the errors come in slowly like 1 every 30 mins or so in the past 6 hours 470+  aborted connections have been clocked on the main poller DB

Again no errors showing a network issue its for sure not a creds issue because that would be all or nothing 

I have set the timeout on the main DB to be 80 seconds didn't seem to make much of a difference

**Comment by bmfmancini** [comment]
OK 

I went a head a made a  LAB on 1.2.5 using 1 main server and 1 remote poller 
and low and behold even with all default values 1 device on each server the failed aborted  count is rising 

MariaDB [(none)]> show status like '%onn%';
+--------------------------+-------+
| Variable_name            | Value |
+--------------------------+-------+
| Aborted_connects         | 6     |  <<<<
| Connections              | 160   |
| Max_used_connections     | 25    |
| Ssl_client_connects      | 0     |
| Ssl_connect_renegotiates | 0     |
| Ssl_finished_connects    | 0     |
| Threads_connected        | 21    |
+--------------------------+-------+
7 rows in set (0.00 sec)

Server version: 5.5.64-MariaDB MariaDB Server

I will update to Maria 10 on this server and check if the issue clears

**Comment by bmfmancini** [comment]
Here it is with Maria10

Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 64
Server version: 10.1.41-MariaDB MariaDB Server

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.


And its still climbing !!

MariaDB [(none)]> show status like '%onn%';
+-----------------------------------------------+-------+
| Variable_name                                 | Value |
+-----------------------------------------------+-------+
| Aborted_connects                              | 10    | <<<<< Raising by about 1 - 2 errors every 20 mins
| Connection_errors_accept                      | 0     |
| Connection_errors_internal                    | 0     |
| Connection_errors_max_connections             | 0     |
| Connection_errors_peer_address                | 0     |
| Connection_errors_select                      | 0     |
| Connection_errors_tcpwrap                     | 0     |
| Connections                                   | 77    |
| Max_used_connections                          | 20    |
| Performance_schema_session_connect_attrs_lost | 0     |

Poller config 
processes  1 threads 1 
2 devices in total 

Next I will test if this is a 1.2.5 thing

**Comment by bmfmancini** [comment]
upgraded to 1.2.7 so far no errors but I will wait longer and update soon

**Comment by bmfmancini** [comment]
Upgraded to 1.2.7  left idle for 40 minutes 

MariaDB [(none)]> show status like '%onn%';
+-----------------------------------------------+-------+
| Variable_name                                 | Value |
+-----------------------------------------------+-------+
| Aborted_connects                              | 89    |  <<<<<<
| Connection_errors_accept                      | 0     |
| Connection_errors_internal                    | 0     |
| Connection_errors_max_connections             | 0     |
| Connection_errors_peer_address                | 0     |
| Connection_errors_select                      | 0     |
| Connection_errors_tcpwrap                     | 0     |
| Connections                                   | 490   |
| Max_used_connections                          | 14    |
| Performance_schema_session_connect_attrs_lost | 0     |
| Slave_connections                             | 0     |
| Slaves_connected                              | 0     |
| Ssl_client_connects                           | 0     |
| Ssl_connect_renegotiates                      | 0     |
| Ssl_finished_connects                         | 0     |
| Threads_connected                             | 8     |
| wsrep_connected                               | OFF   |
+-----------------------------------------------+-------+
17 rows in set (0.00 sec)

**Comment by bmfmancini** [comment]
Ok so the counter still goes up even though the system is practically empty

+-----------------------------------------------+-------+
| Variable_name                                 | Value |
+-----------------------------------------------+-------+
| Aborted_connects                              | 28    | <<<<
| Connection_errors_accept                      | 0     |
| Connection_errors_internal                    | 0     |
| Connection_errors_max_connections             | 0     |
| Connection_errors_peer_address                | 0     |
| Connection_errors_select                      | 0     |
| Connection_errors_tcpwrap                     | 0     |
| Connections                                   | 11213 |
| Max_used_connections                          | 24    |
| Performance_schema_session_connect_attrs_lost | 0     |
| Slave_connections                             | 0     |
| Slaves_connected                              | 0     |
| Ssl_client_connects                           | 0     |
| Ssl_connect_renegotiates                      | 0     |
| Ssl_finished_connects                         | 0     |
| Threads_connected                             | 16    |
| wsrep_connected                               | OFF   |
+-----------------------------------------------+-------+
17 rows in set (0.01 sec)

MariaDB [(none)]>

**Comment by cigamit** [comment]
Odd, you should 'flush hosts' via cron periodically if this continues to happen.  I'm not sure where this is happening though.

**Comment by cigamit** [comment]
If you are running 1.2.7, better grab the 1.2.x branch instead.

**Comment by bmfmancini** [comment]
@cigamit  yea for now i made the max connection error counter huge and I will put in a cron
I have 1 prod system and 1Lab  both  doing the same thing

Prod is 1.2.5 
Lab 1 is 1.2.7 but also tested with 1.2.5

**Comment by bmfmancini** [comment]
Also I can give you access to the lab if you want to see I think this might be a issue that can lead to instability 

if these errors are happening they can creep up over time and eventually hit the max counter and cause the main pollers db to lock out the remote pollers and cause the local table to fill up

**Comment by cigamit** [comment]
Well, are the log's clean from both the remote data collector and the main collector?  I'm a bit under the weather.  Barely able to do this today.

**Comment by bmfmancini** [comment]
No worries at all @cigamit  take care of your self first 

there are no logs that are jumping out at all just the number of aborted connections rises 
I am thinking this might be a spine issue and not a cacti issue 

I will try to switch to cmd.php on the empty lab server and see if that is a difference

**Comment by bmfmancini** [comment]
Oh sorry there are errors on the remote pollers not the main pollers 
the error simply says cannot connect but at a very slow interval

**Comment by bmfmancini** [comment]
Ok so I upgraded to maria10 on my prod systems  here is the errors from the cacti_stderr.log

MYSQL: Connection Failed: Error:'2003', Message:'Can't connect to MySQL server on '' (4 "Interrupted system call")'
MYSQL: Connection Failed: Error:'2003', Message:'Can't connect to MySQL server on '' (4 "Interrupted system call")'
MYSQL: Connection Failed: Error:'2003', Message:'Can't connect to MySQL server on '' (4 "Interrupted system call")'
MYSQL: Connection Failed: Error:'2003', Message:'Can't connect to MySQL server on '' (4 "Interrupted system call")'
MYSQL: Connection Failed: Error:'2003', Message:'Can't connect to MySQL server on '' (4 "Interrupted system call")'
MYSQL: Connection Failed: Error:'2003', Message:'Can't connect to MySQL server on '' (4 "Interrupted system call")'
MYSQL: Connection Failed: Error:'2003', Message:'Can't connect to MySQL server on '' (4 "Interrupted system call")'

**Comment by bmfmancini** [comment]
Ok I re-complied spine to version 1.2.7 and so far the errors on the poller I did it on have stopped !
original version was 1.2.5

**Comment by bmfmancini** [comment]
A few of the errors have come back but way less than before

**Comment by bmfmancini** [comment]
ok revisiting this since upgrading to 1.2.7 today 

Errors are still present same thing errors are only present on the remote pollers and not the main poller 

Max connections is well under the limit 
Maria logs clear

**Comment by netniV** [comment]
This is likely to be a connection timeout issue.  I can't recall if our DB settings have that available to them, if so what do you have it set to?

**Comment by bmfmancini** [comment]
I don't think there is an option for timeout

Let me check

**Comment by bmfmancini** [comment]
Here are the options for the remote poller DB connection 
no timeout value 

Also Spine does not have a directive for timeout 

![image](https://user-images.githubusercontent.com/13388748/66928385-4c75d380-efff-11e9-9671-8a2eee22d9b7.png)


The closests thing is in the config.php for db retries  but not sure at what interveral it would try a re-connect

#$rdatabase_port     = '3306';
#$rdatabase_retries  = 5;
#$rdatabase_ssl      = false;

**Comment by cigamit** [comment]
Well, are the log's clean from both the remote data collector and the main collector?  I'm a bit under the weather.  Barely able to do this today.

**Comment by cigamit** [comment]
Well, you need to complete those settings and make sure the connection tests out.

**Comment by bmfmancini** [comment]
Thise are filled out I got those from the default config.php 
Today I tried raising the retries no good 

Like I mentioned everything works fine it's just these entries in cactistderr.log show up

**Comment by bmfmancini** [comment]
The username and password from the gui have been removed from the pic but they are setup with the creds for the main db server

**Comment by cigamit** [comment]
I'm going to close this one.  If you are able to track this one down, let us know.  It might be simply that the main poller can not communicate to the remote poller or it could be more involved.  Likely has to do with your other issues too.

**Comment by bmfmancini** [comment]
Ok sounds good

Do you mean the other bug report issues with autom8 ?

The remote pollers for sure can talk to the main poller and vice versa

I'll keep on tracking it and see what I can find

**Comment by cigamit** [comment]
You know that this could simply be caused when the database connections back to the central server break.  That would make sense to me.
