### ISSUE TITLE
Password change on first login not working

### ISSUE THREAD

**Issue by lbsou** [Cacti/cacti#3005]
Hi!

I just installed a brand new cacti on develop branch today.

CentOS Linux release 8.0.1905 (Core)
PHP 7.2.11 (cli) (built: Oct  9 2018 15:09:36) ( NTS )
MariaDB Ver 15.1 Distrib 10.3.11
Chrome 77.0.3865.90

When I login for the first time using the default (admin/admin) It ask to change the password. The problem is that I can't get past this step, it is looping without error message.

The only workaround is if I modify the must_change_password column in user_auth. 

As you can see in the screenshot, the password i'm using qualify as "green checkmark".

![image](https://user-images.githubusercontent.com/30626084/66208581-63bdd400-e683-11e9-881b-846bec6fdb70.png)

Thanks!

**Comment by netniV** [comment]
Are you getting any PHP or MySQL errors in the apache or cacti logs?

**Comment by lbsou** [comment]
Strangely, not able to reproduce, closing it.
