### ISSUE TITLE
1.2.7  installer loops on remote poller after upgrade  (undefined index database.php)

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3007]
Hey Guys 

Noticed this yesterday while upgrading my lab to 1.2.7  when I try to login to the remote poller the installer comes up and just loops 

here is the apache error log

[Sat Oct 05 14:22:50.797780 2019] [php7:notice] [pid 8810] [client :54482] PHP Notice:  Undefined index: 127.0.0.1:3306:cacti in /var/www/html/cacti/lib/database.php on line 208, referer: http:///cacti/install/install.php?data={%22Step%22:%2298%22,%22Eula%22:%221%22}
[Sat Oct 05 14:22:50.797802 2019] [php7:notice] [pid 8810] [client :54482] PHP Notice:  Undefined index: 127.0.0.1:3306:cacti in /var/www/html/cacti/lib/database.php on line 208, referer: http:///cacti/install/install.php?data={%22Step%22:%2298%22,%22Eula%22:%221%22}
[Sat Oct 05 14:22:52.698839 2019] [php7:notice] [pid 8810] [client :54482] PHP Notice:  Undefined index: 127.0.0.1:3306:cacti in /var/www/html/cacti/lib/database.php on line 208, referer: http:///cacti/install/install.php
[Sat Oct 05 14:22:52.698885 2019] [php7:notice] [pid 8810] [client :54482] PHP Notice:  Undefined index: 127.0.0.1:3306:cacti in /var/www/html/cacti/lib/database.php on line 208, referer: http:///cacti/install/install.php
[Sat Oct 05 14:22:52.698893 2019] [php7:notice] [pid 8810] [client :54482] PHP Notice:  Undefined index: 127.0.0.1:3306:cacti in /var/www/html/cacti/lib/database.php on line 208, referer: http:///cacti/install/install.php
[Sat Oct 05 14:22:55.242605 2019] [php7:notice] [pid 8810] [client :54482] PHP Notice:  Undefined index: 127.0.0.1:3306:cacti in /var/www/html/cacti/lib/database.php on line 208, referer: http:///cacti/install/install.php?data={%22Step%22:%2298%22,%22Eula%22:%221%22}
[Sat Oct 05 14:22:55.242662 2019] [php7:notice] [pid 8810] [client :54482] PHP Notice:  Undefined index: 127.0.0.1:3306:cacti in /var/www/html/cacti/lib/database.php on line 208, referer: http:///cacti/install/install.php?data={%22Step%22:%2298%22,%22Eula%22:%221%22}
[Sat Oct 05 14:22:55.242683 2019] [php7:notice] [pid 8810] [client :54482] PHP Notice:  Undefined index: 127.0.0.1:3306:cacti in /var/www/html/cacti/lib/database.php on line 208, referer: http:///cacti/install/install.php?data={%22Step%22:%2298%22,%22Eula%22:%221%22}
[Sat Oct 05 14:22:55.705637 2019] [php7:notice] [pid 8810] [client :54482] PHP Notice:  Undefined index: 127.0.0.1:3306:cacti in /var/www/html/cacti/lib/database.php on line 208, referer: http:///cacti/install/install.php?data={%22Step%22:%2298%22,%22Eula%22:%221%22}
[Sat Oct 05 14:22:55.705682 2019] [php7:notice] [pid 8810] [client :54482] PHP Notice:  Undefined index: 127.0.0.1:3306:cacti in /var/www/html/cacti/lib/database.php on line 208, referer: http:///cacti/install/install.php?data={%22Step%22:%2298%22,%22Eula%22:%221%22}
[Sat Oct 05 14:22:55.705689 2019] [php7:notice] [pid 8810] [client :54482] PHP Notice:  Undefined index: 127.0.0.1:3306:cacti in /var/www/html/cacti/lib/database.php on line 208, referer: http:///cacti/install/install.php?data={%22Step%22:%2298%22,%22Eula%22:%221%22}
[Sat Oct 05 14:22:57.662846 2019] [php7:notice] [pid 8810] [client :54482] PHP Notice:  Undefined index: 127.0.0.1:3306:cacti in /var/www/html/cacti/lib/database.php on line 208, referer: http:///cacti/install/install.php
[Sat Oct 05 14:22:57.662889 2019] [php7:notice] [pid 8810] [client :54482] PHP Notice:  Undefined index: 127.0.0.1:3306:cacti in /var/www/html/cacti/lib/database.php on line 208, referer: http:///cacti/install/install.php
[Sat Oct 05 14:22:57.662897 2019] [php7:notice] [pid 8810] [client :54482] PHP Notice:  Undefined index: 127.0.0.1:3306:cacti in /var/www/html/cacti/lib/database.php on line 208, referer: http:///cacti/install/install.php

**Comment by bmfmancini** [comment]
Found the Bug here 

Cacti does not seem to like very long complex passwords 

My original config  with loops 

$database_type = "mysql";
$database_default = "cacti";
$database_hostname = "127.0.0.1";
$database_username = "cacti";
$database_password = "NG1acj6MEnhFthOMgEyye1FOMEJ98TVO1bRyVAjx/S8=";


No more loops 
$database_type = "mysql";
$database_default = "cacti";
$database_hostname = "127.0.0.1";
$database_username = "cacti";
$database_password = "cacti";

**Comment by cigamit** [comment]
Have to defer to @netniV

**Comment by cigamit** [comment]
He is busy at the moment.  Likely some json encoding error.  Could be solved by base64 encoding the json.

**Comment by netniV** [comment]
Actually, that error means that it isn't finding the database session by the index in the cached sessions variable:

```php
$db_conn = $database_sessions["$database_hostname:$database_port:$database_default"];
```

So, this would suggest that it wasn't able to open the connection.  Now, cacti itself doesn't do anything with the password but use it as far as I am aware, so this suggests that it is more likely that either the password was wrong or its actually MySQL that doesn't like the really complex password.

**Comment by bmfmancini** [comment]
It only occurs for the remote db I had the same password on the local db
works fine when I use that same pwd in the cli it works fine weird

**Comment by bmfmancini** [comment]
Also I would suspect the install would have failed if the password was
wrong this was after the install completed and you click the get started
button

**Comment by netniV** [comment]
Well, you can put the password into a test php file and test the connection with the password, but it isn’t cacti itself balking at the long password.  It may be an issue of the connection has never been opened so it needs opening... but I’m not sure if anything has changed on that front.

**Comment by bmfmancini** [comment]
Ok cool will do

Thanks!

**Comment by cigamit** [comment]
Guys, I'm going to close this one.  Figure it's some odd phenomena related to the password and possibly json data.  So, I'm going to close for now.  If it comes back again, we can spend more time on it.
