### ISSUE TITLE
1.2.7 SSL switch for Remote poller always enables despite disabling from Main poller

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3008]
Hey Guys 

Another bug  with the remote poller setups 
the remote poller works fine so I dont think that SSL is truly enabled 
also I have the SSL options commented out of config,php 

![poller-ssl](https://user-images.githubusercontent.com/13388748/66256540-cb941d80-e75c-11e9-927d-1e90613bd74e.gif)

**Comment by cigamit** [comment]
Please update lib/html_utility.php from the 1.2.x branch.  It'll solve the problem.

**Comment by bmfmancini** [comment]
Hey this is from the 1.2x branch though 
Unless my git messed up and went to the master

**Comment by cigamit** [comment]
This is working on new installs.  Run the audit_database.php cli script and see if you have any missing columns.  I'm going to close this, but keep us posted.
