### ISSUE TITLE
PHP Script Server wrong values

### ISSUE THREAD

**Issue by bmcgoncalves** [Cacti/cacti#3009]
Hi, recently we upgraded CACTI to version 1.2.7 and we are experiencing a strange behavior on php script server data queries.

When we run the script directly in command line the values are ok but in cacti sometimes we have wrong values with a difference of millions. 

We wrote the values to file just before the return value to cacti.  The values are ok.
So, the script it's ok.

This issue happens randomly. We are not able to reproduce this issue with a procedure. Just happens randomly.

The php script server in this cases are getting data from a DB in other host and the data are Ok there.

Something change in script server since version 1.1?

Thanks

**Comment by cigamit** [comment]
Turn on device debug on the device in question.  Also, what does your Cacti log look like during these time periods?  Are you using spine or cmd.php?  If you have some poorly performing script server scripts, and using cmd.php, there is some historically bad behavior that can be expected.  You should also edit your cli's php.ini file and set 'error_log = /tmp/somefile', and check that file for errors as well as the Cacti stderr..log file, if there are some that are non-blank.

**Comment by bmcgoncalves** [comment]
I've done all of your suggestions:
- there's no errors in php error_log
- with debug device ON, i cannot find nothing unsual but i see the **WRONG** value output
- we are using spine and if we run /usr/local/spine/bin/spine -R -S -V 10  -f 77 -l 77 there's no bad values here

**DataQueries**
![image](https://user-images.githubusercontent.com/27480860/66266087-073fed80-e818-11e9-81a4-7edbb9e9ea11.png)

**1 Example**
![image](https://user-images.githubusercontent.com/27480860/66266092-335b6e80-e818-11e9-97dd-8070f0b36e35.png)

**Graph Values**
![image](https://user-images.githubusercontent.com/27480860/66266114-80d7db80-e818-11e9-92ce-74ef85839600.png)
the normal values are 5, 6, 8 etc..

**Graph Template**
![image](https://user-images.githubusercontent.com/27480860/66266158-0c516c80-e819-11e9-91ed-27988e146e86.png)

The SNMP graphs are OK, we are only seeing issues with script server scripts.

**Comment by bmcgoncalves** [comment]
**Values on script:**
2019-10-07 07:56:sbc07a:vport_used:3292:vport_available:38708:vport_total:**42000**

**DEBUG:**
2019/10/07 07:56:22 - SPINE: Poller[Main Poller] PID[41489] Device[sbc07a] HT[1] DS[sbc07a -VPort Utilization] Graphs[sbc07a - VPort Utilization] SS[2] SERVER: /data/gui/cacti/scripts/genband/ss_vports.php ss_vports 'sbc07a' 'get' 'vport_total' '0', output: **0**

In this case the vport_total is always passing to value 0.
![image](https://user-images.githubusercontent.com/27480860/66295803-08d6e780-e8e4-11e9-80a6-ae4d5c7afdb9.png)

**Comment by netniV** [comment]
if you manually run the script:
```
/data/gui/cacti/scripts/genband/ss_vports.php ss_vports 'sbc07a' 'get' 'vport_total' '0', output: 0
```
What is the output it displays?

**Comment by bmcgoncalves** [comment]
$ php /data/gui/cacti/scripts/genband/ss_vports.php 'sbc07a' 'get' 'vport_total' '0'
42000

**Comment by netniV** [comment]
Now that is interesting as I am sure that should have the `vport_total:` prefix

**Comment by bmcgoncalves** [comment]
@netniV we think that is true for input method queries. If that is true for script server it doesn't explain the good results.

**Comment by netniV** [comment]
You may be right, I hven't got my head in DS mode right now, I'd have to see what I get on other scripts.  Can you provide the XML that goes with this query?

**Comment by bmcgoncalves** [comment]
We stopped some new scripts and the problem was gone.
We are trying to find what is the script messing up this queries.

**Comment by TheWitness** [comment]
You should always check the return values from the DB calls and never simply return them.  If you get a blank or null, you have to return either 0 or U.  So, what you are doing is a bad practice.

**Comment by bmcgoncalves** [comment]
Yes, we know that, but returning 0 it's also a bad practice, 0 it's a valid value. Return U is the best option.

That's not the problem in this case, only if the connection with the database is down.

**Comment by bmcgoncalves** [comment]
unable to know what was the problem. maybe one script server was affecting the values of other graphs? this is possible?
closing the issue, it's all ok now.
