### ISSUE TITLE
Table conversion to UTF8 doesn't seem to work

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#3010]
Over the past several upgrades I continually see these notice:

![image](https://user-images.githubusercontent.com/12864741/66281311-02128b00-e878-11e9-9c67-d3c25aa4c841.png)

I allow cacti to convert these tables to UTF8 but it doesn't appear to work. 
Here's the install log:
```
2019/10/06 20:31:10 - INSTALL: always: Installation was started at 2019-10-07 02:31:08, completed at 2019-10-07 02:31:10
2019/10/06 20:31:10 - INSTALL: always: Finished UPGRADE Process for v1.2.7
2019/10/06 20:31:10 - INSTALL: always: Upgrading from v1.2.6 (DB 1.2.7 (DB: 1.2.6)) to v1.2.7
2019/10/06 20:31:10 - INSTALL: always: NOTE: Using temporary file for db cache: /tmp/cdubyYYxt
2019/10/06 20:31:10 - INSTALL: always: Switched from to /tmp/cdubyYYxt
2019/10/06 20:31:10 - INSTALL: always: Converting Table #3 'poller_resource_cache'
2019/10/06 20:31:09 - INSTALL: always: Converting Table #2 'poller_command'
2019/10/06 20:31:09 - INSTALL: always: Converting Table #1 'host_snmp_cache'
2019/10/06 20:31:09 - INSTALL: always: Found 3 tables to convert
2019/10/06 20:31:09 - INSTALL: always: Starting UPGRADE Process for v1.2.7
2019/10/06 20:31:08 - INSTALL: always: Setting PHP Option memory_limit = -1
2019/10/06 20:31:08 - INSTALL: always: Setting PHP Option max_execution_time = 0
2019/10/06 20:31:08 - INSTALL: Checking arguments
2019/10/06 20:31:07 - INSTALL: always: Spawning background process: /usr/local/php/bin/php '/cacti/cacti-1.2.7a-prod/install/background.php' 1570415467.766
```

**Comment by netniV** [comment]
I can give you the command it would run, then you would have to try that manually to see the true problem.

**Comment by eschoeller** [comment]
Yep, send the command and I’ll run it!

Eric.

**Comment by netniV** [comment]
```php
sudo -u <poller or website user> php -q cli/convert_tables.php --table='<table_name>' --utf8 --innodb
```

That will run something like:
```sql
ALTER TABLE `<table_name>` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, ENGINE=Innodb
```

Try using the CLI method first as that is what the code does so it would be useful to know the output its giving.  If that still hasn't converted it, try the sql command as it's likely MySQL is giving an error for some reason...

**Comment by eschoeller** [comment]
Here they are right now:
```
mysql> show table status from cacti where name like '%poller_resource_cache%' or name like '%poller_command%' or name like '%host_snmp_cache%';
+-----------------------+--------+---------+------------+-------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+-------------------+----------+----------------+--------------------------------------------------+
| Name                  | Engine | Version | Row_format | Rows  | Avg_row_length | Data_length | Max_data_length | Index_length | Data_free | Auto_increment | Create_time         | Update_time | Check_time | Collation         | Checksum | Create_options | Comment                                          |
+-----------------------+--------+---------+------------+-------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+-------------------+----------+----------------+--------------------------------------------------+
| host_snmp_cache       | InnoDB |      10 | Compact    | 84434 |            128 |    10862592 |               0 |     25968640 |   6291456 |           NULL | 2017-03-21 21:09:48 | NULL        | NULL       | latin1_swedish_ci |     NULL |                |                                                  |
| poller_command        | InnoDB |      10 | Compact    |     0 |              0 |       16384 |               0 |        16384 |         0 |           NULL | 2017-03-11 20:19:23 | NULL        | NULL       | latin1_swedish_ci |     NULL |                |                                                  |
| poller_resource_cache | InnoDB |      10 | Compact    |  1480 |          46926 |    69451776 |               0 |       180224 |  12582912 |           2088 | 2018-10-20 15:38:43 | NULL        | NULL       | latin1_swedish_ci |     NULL |                | Caches all scripts, resources files, and plugins |
+-----------------------+--------+---------+------------+-------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+-------------------+----------+----------------+--------------------------------------------------+
3 rows in set (0.00 sec)
```
/usr/local/php/bin/php -q /cacti/cacti-prod/cli/convert_tables.php --table='poller_resource_cache' --utf8 --innodb
Converting Database Tables to InnoDB and  utf8 with less than '1000000' Records
Converting Table -> 'poller_resource_cache' Successful
-bash-4.1$ /usr/local/php/bin/php -q /cacti/cacti-prod/cli/convert_tables.php --table='poller_command' --utf8 --innodb
Converting Database Tables to InnoDB and  utf8 with less than '1000000' Records
Converting Table -> 'poller_command' Successful
-bash-4.1$ /usr/local/php/bin/php -q /cacti/cacti-prod/cli/convert_tables.php --table='host_snmp_cache' --utf8 --innodb
Converting Database Tables to InnoDB and  utf8 with less than '1000000' Records
Converting Table -> 'host_snmp_cache' Successful
```
mysql> show table status from cacti where name like '%poller_resource_cache%' or name like '%poller_command%' or name like '%host_snmp_cache%';
+-----------------------+--------+---------+------------+-------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+-------------------+----------+----------------+--------------------------------------------------+
| Name                  | Engine | Version | Row_format | Rows  | Avg_row_length | Data_length | Max_data_length | Index_length | Data_free | Auto_increment | Create_time         | Update_time | Check_time | Collation         | Checksum | Create_options | Comment                                          |
+-----------------------+--------+---------+------------+-------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+-------------------+----------+----------------+--------------------------------------------------+
| host_snmp_cache       | InnoDB |      10 | Compact    | 84434 |            128 |    10862592 |               0 |     25968640 |   6291456 |           NULL | 2017-03-21 21:09:48 | NULL        | NULL       | latin1_swedish_ci |     NULL |                |                                                  |
| poller_command        | InnoDB |      10 | Compact    |     0 |              0 |       16384 |               0 |        16384 |         0 |           NULL | 2017-03-11 20:19:23 | NULL        | NULL       | latin1_swedish_ci |     NULL |                |                                                  |
| poller_resource_cache | InnoDB |      10 | Compact    |  1480 |          46926 |    69451776 |               0 |       180224 |  12582912 |           2088 | 2018-10-20 15:38:43 | NULL        | NULL       | latin1_swedish_ci |     NULL |                | Caches all scripts, resources files, and plugins |
+-----------------------+--------+---------+------------+-------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+-------------------+----------+----------------+--------------------------------------------------+
3 rows in set (0.01 sec)
```
Here is the problem:
```
mysql> alter table 'poller_resource_cache' CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, ENGINE=Innodb;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''poller_resource_cache' CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode' at line 1
```

**Comment by eschoeller** [comment]
mysql> SHOW VARIABLES LIKE "%version%";
+-------------------------+---------------------+
| Variable_name           | Value               |
+-------------------------+---------------------+
| innodb_version          | 5.6.23              |
| protocol_version        | 10                  |
| slave_type_conversions  |                     |
| version                 | 5.6.23-log          |
| version_comment         | Source distribution |
| version_compile_machine | x86_64              |
| version_compile_os      | Linux               |
+-------------------------+---------------------+
7 rows in set (0.00 sec)

**Comment by netniV** [comment]
You used single quotes rather than backticks on the table name

**Comment by eschoeller** [comment]
Whoops! Here you go:
```
mysql> alter table `poller_resource_cache` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, ENGINE=Innodb;
ERROR 1709 (HY000): Index column size too large. The maximum column size is 767 bytes.
```

**Comment by netniV** [comment]
This is the large prefix and row format issue that was raised previously if you search through past issues.  Tweak your MySQL configuration and it should start working.

**Comment by eschoeller** [comment]
OK, here's what our DB team had to say about this:

"There is a mysql config setting 'innodb_large_prefix' that needs to be set to ON in order to create prefixes (indexes > 767 chars).   However, in order to use innodb_large_prefix, the table type needs to be Barracuda, and the row_format needs to be dynamic or compressed.    The current cacti tables are using the older innodb table format (Antelope) with a row_format of Compact.    This needs to be changed before the innodb_large_prefix can be turned on, and the innodb_large_prefix must be turned on before the alter table can work."

This seems like a lot of re-configuration. Do you support all of this? I didn't know I was so far off from where I needed to be ... is the installer checking for any of these requirements?

**Comment by eschoeller** [comment]
This all seems related to #2957 I bet a lot of people are running into this type of problem, especially those of us who have been with this software for many years and have been carrying along databases this entire time.

**Comment by netniV** [comment]
It does seem to affect the older ones, and yes your DB team is correct, the engine needs to become barracuda.  Unfortunately, whilst that was identified in that previous issue, it would appear that convert_tables.php wasn't updated to also force barracuda so I will have to see why it wasn't.

**Comment by cigamit** [comment]
Yea, this last piece is going to cause issue for a while unless we start blocking installation if the default table format is forced to Barracuda.

**Comment by netniV** [comment]
tbh, I don 't see a reason why you would block it from a mysql point of view.  We can have the installer detect it the same way we do with UTF8 and request a conversion.  In fact, for the antelope issue we probably should block it rather than just warn if there are any tables that aren't converted.

**Comment by cigamit** [comment]
That's what I meant.

**Comment by cigamit** [comment]
I've just confirmed that I can not install a fresh install without have innodb_large_prefix set to 1.  So, I'm suggesting we close this one.
