### ISSUE TITLE
Some graph routines are not properly validating incoming variables

### ISSUE THREAD

**Issue by majed17** [Cacti/cacti#3012]
this was one 1.2.7 and still is on the later 1.2.x
```
2019/10/07  08:58:31 - CMDPHP Input Validation Not Performed for 'node' Backtrace:   (/graph_view.php[219]:top_graph_header(),  /lib/functions.php[3247]:include_once(),  /include/top_graph_header.php[28]:draw_navigation_text(),  /lib/functions.php[2484]:get_request_var(),  /lib/html_utility.php[369]:html_log_input_error(),  /lib/html_validate.php[44]:cacti_debug_backtrace())
--
2019/10/07 08:56:10 - CMDPHP Input Validation Not Performed for  'graph_nolegend' Backtrace:   (/graph_realtime.php[61]:load_current_session_value(),  /lib/html_utility.php[889]:get_request_var(),  /lib/html_utility.php[369]:html_log_input_error(),  /lib/html_validate.php[44]:cacti_debug_backtrace())
```

**Comment by netniV** [comment]
I've already made a change for the first mod, going to look at the second shortly, then post both.

**Comment by majed17** [comment]
now realtime doesn't produce graphs...it produces the following error:
2019/10/08 12:44:44 - CMDPHP Validation Error, Variable:graph_nolegend, Value:false Backtrace: (/graph_realtime.php[43]:get_filter_request_var(), /lib/html_utility.php[484]:die_html_input_error(), /lib/html_validate.php[64]:cacti_debug_backtrace())

**Comment by netniV** [comment]
OK, I'll take another look at that.  It's likely that the default is checking for integer values rather than the words "true" or "false".

**Comment by cigamit** [comment]
Correct, graph_nolegend was resolved some time ago.  The fix that was committed assumed integer.  Performing proper validation in commit shortly.

**Comment by majed17** [comment]
now i get :
`2019/10/14 17:27:54 - CMDPHP Input Validation Not Performed for 'node' Backtrace: (/graph_view.php[219]:top_graph_header(), /lib/functions.php[3253]:include_once(), /include/top_graph_header.php[28]:draw_navigation_text(), /lib/functions.php[2484]:get_request_var(), /lib/html_utility.php[369]:html_log_input_error(), /lib/html_validate.php[44]:cacti_debug_backtrace()) `

**Comment by netniV** [comment]
I've reopened this, purely so it doesn't get forgotten as I'm not changing any code tonight.  The changelog will not be adjusted, just more code added for this newer variable.

**Comment by majed17** [comment]
now i get :

`2019/10/16 08:41:42 - CMDPHP Validation Error, Variable:graph_nolegend, Value:false Backtrace: (/graph_realtime.php[43]:get_filter_request_var(), /lib/html_utility.php[484]:die_html_input_error(), /lib/html_validate.php[64]:cacti_debug_backtrace()) `

**Comment by netniV** [comment]
You haven't got the current graph_realtime.php as that line number does not match up.

**Comment by netniV** [comment]
In fact, I'm getting the same with the other message you posted, what version of cacti are you running?

**Comment by majed17** [comment]
with your latest commit, i am getting nothing cranky any more. not to flatter, but my cacti has never had such a clean log. on monday morning, God willing, we'll see if anything new pops up!

**Comment by majed17** [comment]
this is still present:

 `CMDPHP Input Validation Not Performed for 'node' Backtrace: (/graph_view.php[219]:top_graph_header(), /lib/functions.php[3253]:include_once(), /include/top_graph_header.php[28]:draw_navigation_text(), /lib/functions.php[2484]:get_request_var(), /lib/html_utility.php[369]:html_log_input_error(), /lib/html_validate.php[44]:cacti_debug_backtrace())`

**Comment by netniV** [comment]
If you try that, it should now work.

**Comment by majed17** [comment]
the "if" just reveals unthankfulness, and it turns out it just works !

**Comment by netniV** [comment]
Not sure I follow but glad it works.
