### ISSUE TITLE
Sync only plugins with remote_collect:1 to the remote pollers

### ISSUE THREAD

**Issue by thurban** [Cacti/cacti#3014]
In the file` lib/poller.php` for function `update_resource_cache($poller_id = 1)` can we add a feature that it checks wether a plugin should not be transferred/synced with the remote poller ?

i.e my CereusReporting plugin is only required to run on the master server and is of no use on a remote poller.
I would assume the same for other plugins as well.

Maybe just skipping plugins with **remote_collect:0** in the _capabilities_ section of the `INFO `file would do the trick ?

**Comment by netniV** [comment]
Yes there is as we've run into that before 👍 

Good to hear from you though, hope you've been well.
