### ISSUE TITLE
Cacti does not automatically draw graphics

### ISSUE THREAD

**Issue by shtampuh** [Cacti/cacti#3016]
Hi, 
I Use Cacti Version 1.2.6 
When i add network range for Automation cacti create the graphics only on interface who are Ip addrese, i need to automatic create graphuc for ethenet port with traffic.
I use Generic SNMP Device template.
![image](https://user-images.githubusercontent.com/30555436/66634487-dc89d680-ec15-11e9-8c9c-eb2325c1e5af.png)
In Data Query:
![image](https://user-images.githubusercontent.com/30555436/66634579-0a6f1b00-ec16-11e9-91f6-3d270da6fd18.png)

**Comment by cigamit** [comment]
This issue should be taken up on the Cacti forums before coming here.  Is your Cacti log clean?  Are the permissions right on the RRDfiles?

**Comment by cigamit** [comment]
No feedback.
