### ISSUE TITLE
user_language will not take effect if user_language is different with browser locale

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#3019]
**Describe the bug**
user_language is not took effect if user_language  is different with browser locale

**To Reproduce**
0. Ensure browser locale is non-en-US, and change admin-->user_language to en_US
2. Access login page, check button, input-field stakeholder is not en-US
3. Login
4. Check top tab, top tab use 'non-en-US'
5. Check auth_profile.php?action=edit
6. User Language field is "English", but interface language is not English.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/17589018/66659146-7b91eb00-ec75-11e9-9514-259208d36729.png)

**Comment by cigamit** [comment]
Can you please provide fresh pull request with the modified CHANGELOG for this an the other issue?

**Comment by cigamit** [comment]
Never mind, I did it.

**Comment by ddb4github** [comment]
**More default behavior need to be completed: for case below**
1. default `auth_profile.php-->user_language` is from  `settings-->i18n_default_language`
2. default settings-->i18n_default_language is `en_US`
3. login page locale depend on browser interface language, e.g. non-en_US

**Proposal story as**
   -  Keep above `#3` behavior, change `#1` "default `auth_profile.php-->user_language` to browser UI language(locale)`
 - Or  Keep above `#1, #2`, and change `#3` "login page locale always depend on settings-->i18n_default_language"

**Comment by netniV** [comment]
Personally, I believe that the order should be User Settings -> Browser -> System Settings. That way there is a fallback default language if the browsers language isn't supported.
