### ISSUE TITLE
Tree view cuts off at the bottom of page on modern theme

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3021]
Hey Guys 

I alot of tress in the tree view and what I notice is that the trees cut off or are hard to get to when its neat the bottom of the page 

Also if you add a new tree at times you cant see it unless you expand another one to make the scroll bar go down more  I  suggest maybe adding some padding at the bottom to eliminate this issue 

Or a cascading tree view from when you search the other irellevant tress are hidden 

Verified this in Firefox,Chrome,IE

![image](https://user-images.githubusercontent.com/13388748/66674993-6182e900-ec32-11e9-9cb7-c2b94ceabe5e.png)

**Comment by cigamit** [comment]
This issue has been out there for a while.  Would love to see a pull request to get this one fixed.  I suspect this is the modern theme right?

**Comment by bmfmancini** [comment]
Yes and also with sunrise as well
I will try to.play with the css and see what I can do

Thanks !

**Comment by bmfmancini** [comment]
I have not been able to track down this issue I think it's in the jquery area
