### ISSUE TITLE
Last device added is the only graph that shows

### ISSUE THREAD

**Issue by ambtfp** [Cacti/cacti#3022]
After adding a new device to Cacti, the graph of my other device stops working. This will continue to happen if I add a new device, only that graph will update and all others will stop working. I'm running the latest version of Cacti.

Example:
![image](https://user-images.githubusercontent.com/56456029/66685163-b2520c00-ec49-11e9-9ab3-f9e8aad4b4cd.png)
![image](https://user-images.githubusercontent.com/56456029/66685250-ecbba900-ec49-11e9-928b-8d4f6ff29593.png)

**Comment by cigamit** [comment]
You need to provide output from your Cacti log as this is not nearly enough information to debug.  Actually, questions like this should be directed to the forums first.  Have you addressed this in the forums?

**Comment by cigamit** [comment]
If you log is clean, you may simply have a permission issue with your RRDfiles.
