### ISSUE TITLE
Non-Console-Tab continuously reload page instead of show/hide menu

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#3023]
**Describe the bug**
Actually, #2910  and #2919 are not resolved.
BTW, Graphs tab has similar issue:  `Under tree mode , click 'Tree View' will trigger 'Page Reload" but not show/hide tree`

**To Reproduce**
Ref #2910 and #2919 

**Root Cause**
After click a collapsed non-console tab from submenu, and then click another non-default page under current non-console-tab:, current page execute order as:
* setupResponsiveMenuAndTabs-->loadTopTab:  param 'id' is 'tab-xxxx-ellipsis'
   -  go thru all tab, include submenu,  and mark  clicked sub-menu-item with 'selected' class
* showCurrentTab: param 'id is 'tab-xxxx'
   - Remove sub-menu-item by id 'tab-xxxx-ellipsis'

So 'selected' info is lost.
When click current 'non-console-tab' again,  function setupResponsiveMenuAndTabs check fail both for 'selected' and 'same page', 
* Then reload default page instead of show/hide menu

**Additional**
I fixed non-console-tab issue at first.
I'll try graph-sub-menu issue as soon if non-other guys interest it .

**Comment by cigamit** [comment]
Can you please provide fresh pull request with the modified CHANGELOG for this an the other issue?

**Comment by cigamit** [comment]
Never mind, I did it.
