### ISSUE TITLE
Aggregate Graph re-ordering does not work

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#3027]
As referenced in #3013 

The Aggregate Graph is displayed identically regardless of which Reorder Type is selected:
![cacti_graph_67217](https://user-images.githubusercontent.com/12864741/66719316-661edd00-edab-11e9-9181-0709601de199.png)

I would expect the "*_Inlet_D6" sources to be shifted to the top of the legend.

**Comment by cigamit** [comment]
Please dump your db and send along to developers at cacti dot net.

**Comment by eschoeller** [comment]
will do

**Comment by eschoeller** [comment]
Sent. p/w is your first name

**Comment by cigamit** [comment]
@eschoeller, I just checked the code.  The re-ordering only works with Stacked Graphs presently, which is odd.  Let me make it more generic and let's see what happens.

**Comment by cigamit** [comment]
Okay, looking at the code, the options presently don't make any sense.  I'll have to make sense of them.

**Comment by eschoeller** [comment]
Cool thanks for looking into it! Looks like you’re working this weekend .. I might have some time later today or tomorrow, but I’m currently traveling. If you want another db dump from me let me know, I can whip that together

**Comment by cigamit** [comment]
It was a pain.  But I think it's fixed.  Uploading shortly.

**Comment by cigamit** [comment]
Okay, so you have to change lib/api_aggregate.php, lib/aggregate.php, and aggregate_templates.php.  Then, you have to change something on the template and click save, then change it back to what you want.  In your case, it's really the order.

**Comment by eschoeller** [comment]
Applied those updates, I've been playing around with it. I think we might have a regression issue from #2659

**Comment by eschoeller** [comment]
Most notably, see this legend:
![Screen Shot 2019-11-30 at 3 59 06 PM](https://user-images.githubusercontent.com/12864741/69907435-78200380-138a-11ea-8e86-6c6985588d30.png)
I can't get rid of the "Temperature" for each item, and that's what we were working on in #2659 and #2656.
Both sort orders are also putting "10" in front of "6", but I am less worried about that.

**Comment by cigamit** [comment]
Understand about the regression.  We need to add an option for including/excluding the Temperature.  I'll have to make another commit either tonight or tomorrow.

**Comment by cigamit** [comment]
Okay, to apply this, you need to add a new column to both the aggregate_graphs, and aggregate_graph_templates tables.  Look into the install/upgrades/1_2_8.php file for the alter syntax.

Then, from inside the template there is a checkbox below the prefix to allow you to show and hide the original GPRINT title text.

**Comment by cigamit** [comment]
Make sure you provide feedback on the zoom issue too.  I'm pretty sure it'll be fixed now if you take the full update (1.2.x branch).

**Comment by cigamit** [comment]
@eschoeller, Any updates?
