### ISSUE TITLE
Error when creating tree items with "&" in the name in Cacti 1.0.2

### ISSUE THREAD

**Issue by stormonts** [Cacti/cacti#303]
This issue didn't exist in .8.8h, but when I create a new tree item in Cacti 1.0.2 that has a "&" in it, Cacti changes it to "&amp", so "Linux & Windows" becomes "Linux &amp Windows". If I right-click on it and choose edit, I am not allowed to edit it, but it automatically changes again to "Linux &amp amp Windows". Each further attempt to edit it adds another "amp" to the string.

**Comment by smiles1969** [comment]
Must be in the javascript on that page, the form button save stuff looks like it's working correctly, only the right click rename functionality.

**Comment by cigamit** [comment]
Yea, the callbacks need to be escaped.  Going to test.

**Comment by cigamit** [comment]
Well, this is mostly resolved, though when you rename, you will see the special characters.  This second issue appears to be more a jstree issue than a Cacti issue.

**Comment by cigamit** [comment]
Created the following jstree issue https://github.com/vakata/jstree/issues/1709

**Comment by cigamit** [comment]
Resolved, thanks.
