### ISSUE TITLE
AUTOM8 on 1.2.5 not working properly on Remote pollers but fine on Main

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3033]
Hey Guys 

So on 1.2.5 when I run a scan on a remote poller some times the proccess hangs for a long time but no devices end up getting added even though the ping.SNMP hosts show 2/2 for example

If you cancel the proccess and try to rerun autom8 comes back and doesnt even scan the IP's  and now reports there are no devices 

here is the debug output this is only happening on the remote pollers the main poller is fine
I run the discover from the main poller and I have forced a sync as well to make sure everyone has the proper settings

2019/10/15 13:45:58 - AUTOM8 [PID: 1655] Found 0 Threads
2019/10/15 13:45:53 - AUTOM8 [PID: 1655] Found 0 Threads
2019/10/15 13:45:48 - AUTOM8 [PID: 1655] Found 0 Threads
2019/10/15 13:45:48 - AUTOM8 [PID: 1655] Checking for Running Threads
2019/10/15 13:45:43 - AUTOM8 [PID: 1658] Network lb's Thread 1 Finished, 0 IPs **Scanned, 0 IPs** Responded to Ping, 0 Responded to SNMP, 0 Device Added, 0 Graphs Added to Cacti
2019/10/15 13:45:43 - POLLER: Poller[123] DEBUG: About to Spawn a Remote Process [CMD: /bin/php, ARGS: -q /var/www/html/cacti/poller_automation.php --poller=8 --thread=1 --network=43 --force --debug]
2019/10/15 13:45:43 - AUTOM8 [PID: 1655] Launching Thread 1
2019/10/15 13:45:43 - AUTOM8 [PID: 1655] Automation will use 1 Threads
2019/10/15 13:45:43 - AUTOM8 [PID: 1655] A Total of **1 IP Addresses Primed** 

Very Odd behaviour

**Comment by bmfmancini** [comment]
ok now I tried to restart the network scan and it just hangs the autom8 proccess on the remote poller ended yet in automnaton it still shows running ????

I think I need to do a upgrade to 1.2.7 in short order due to all these bugs with 1.2.5

**Comment by bmfmancini** [comment]
Ok upgraded to 1.2.7 and so far its working good weird I will keep and eye and keep on testing

**Comment by netniV** [comment]
I'll close the issue for now, we can reopen it if you identify the problem.

**Comment by bmfmancini** [comment]
What do you make of that log though ??

**Comment by netniV** [comment]
Well, actually, I might sound harsh, but I don't really care for pre-1.2.6's method of calculating network ranges/ips.  I put a big fix in for that and tested it thoroughly so I know it's right now (please no one find a bug lol).

It is possible that you fell into that small percentage that broke the old methods which I think occurred for some of the stranger entries or for single hosts, etc.

**Comment by bmfmancini** [comment]
Oh yea !! lol I remember that fix for 1.2.6 but i thought it was just when you put a CIDR 
in this case it was just the IP in the box and the first run found the device but hung so It never occurred to me to be that bug 

interesting ,,,,

ok ill keep an eye out 

Thanks !

**Comment by bmfmancini** [comment]
but why only the remote poller ???
and looking at the log autom8 did pickup 1 ip and primed it but scanned ip's 

im not sure this is the same bug

**Comment by netniV** [comment]
Do you have the same error since?  If not, I'll stick to my answer ;-)

**Comment by bmfmancini** [comment]
I'll run a couple of more tests and let you know

Thanks!
