### ISSUE TITLE
The Inbound/Outbound Data Source changed after save

### ISSUE THREAD

**Issue by wilson298** [Cacti/cacti#3034]
Hi all, 

I has a problem to create a graph which sum up two device interfaces traffic.

Here was what I did:
Click Graph Management -> Click Add 
Selected Graph Template: Interface - Traffic(bits/sec, 95th Percentile In and Out)
Host: None
Graph Item Fields:
Inbound Data Source : Device A eth1(traffic_in)
Inbound Data Source: Device B eth2(traffic_in)
Outbound Data Source: Device A eth1(traffic_out)
Outbound Data Source: Device B eth2(traffic_out) 

Somehow after save, checked the Inbound/Outbound Data Source were not the same as I configured, it became:
Inbound Data Source : Device B eth2(traffic_in)
Inbound Data Source: Device B eth2(traffic_in)
Outbound Data Source: Device B eth2(traffic_out)
Outbound Data Source: Device B eth2(traffic_out) 

Is someone has any idea how to fix the issue?
Attached is the RRDTool commands and below is the information for reference.
Thanks.

Cacti Version: 0.8.8b
NET-SNMP version: 5.5
RRDTool Version: 1.3.x

![RRDTool Command](https://user-images.githubusercontent.com/56633090/66910702-a26b6b00-f041-11e9-8904-3eb429aeb016.png)

**Comment by cigamit** [comment]
Sorry, we are no longer supporting the 0.8.x series, only the 1.x series.  I'm not even sure where to begin.

**Comment by cigamit** [comment]
I'm pretty sure you can manually edit the Graph and fix them though.  Just do that.  I'll close this one since you can do it there.
