### ISSUE TITLE
Poller Output Table not empty for poller id 1. Issues: 1, DS[12777].

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#3036]
**Describe the bug**
`WARNING: Poller Output Table not empty for poller id 1. Issues: 1, DS[12777]`

**To Reproduce**
1. Go to one specified device id=793.
2. Create Interface Traffic Graphs for ports 9 or 10.
3. Wait for poller.
4. See error every polling cycle.

**Expected behavior**
Clean log.

Cacti branch 1.2.x 
I did update this day before making issue to be sure it exists in newest code.

**Additional information:**
1. I tried to check all issues with "poller output" but not found any solution for that.
2. When I delete those graphs and rebuild poller cache - error dosn't show in next polling cycle.
3. When I disable device the error doesn't appear in log.

MariaDB [cacti]> SELECT * FROM poller_output;
+---------------+------------+---------------------+--------+
| local_data_id | rrd_name   | time                | output |
+---------------+------------+---------------------+--------+
|         12777 | traffic_in | 2019-10-17 17:40:01 | U      |
+---------------+------------+---------------------+--------+

The rrd is created and got permisions like any other rrd file.

**Comment by cigamit** [comment]
Yea, for some reason, the traffic_out is not being generated.  Is this a bad interface? Of is the device timing out and therefore the data is not being returned?  I think that this is a valid warning message, and that you really need to focus on why it's happening.  Then, take this issue up on the forums first as this is a good warning.

**Comment by netniV** [comment]
I know this is an older issue, but I thought I would add my observations to this.  This can occur if the script_server.php or spine crashes for some reason so you should always up your logging and see what is being reported back.

In my case, I could simulate this by merely running two instances of spine at the exact same time causing too many database connections to the mysql server which in turn caused the parent process of the script server to disappear and not properly process all output.
