### ISSUE TITLE
Minor UI issue for aggregate when 'main' div width is less than 1230px

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#3038]
**Describe the bug**
Minor UI issue for aggregate when 'main' div width is less than 1230px
Ref screenshot.

**To Reproduce**
1. Select anyone graph under Console-->Management-->Graphs
2. Select 'Create Aggregate Graph' action,  Go
3. Zoom out browser window width

**Screenshots**
![image](https://user-images.githubusercontent.com/17589018/67090187-0c1f7c80-f1dc-11e9-8450-deee104dc30a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox  60.9 esr
 - Cacti Version 1.2.7

**Comment by cigamit** [comment]
@ddb4github, is it only when creating an aggregate that this happens?  There is form logic to resize the text[box] and textarea form elements, but maybe it's not working on this page.

**Comment by ddb4github** [comment]
Yes, during edit, form is expended to whole main area.
And issue is also disappeared

**Comment by TheWitness** [comment]
This is a bug.
