### ISSUE TITLE
Is host online more frequently

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#304]
It would be good to check if host is up/down more frequent (and send notification if down).

We need to:
- update graphs by 5 min,
- check host online interval 30 seconds.

**Comment by interduo** [comment]
I think that it should be possible to check some host less frequently.
For example 4times/hour.

It should be possible to define.

**Comment by cigamit** [comment]
Hosts are checked as they are polled.  Any checks beyond this would have to be done via plugin, as its usefulness is very limited.  The only other way to simulate this is to add a single graph for each host that polls every 30 seconds and then change your cron / poller interval to 30 seconds.  For alerting, we already have plugins that alert when a host goes down.
