### ISSUE TITLE
AUTOM8 discovery starts   even if you click cancel 

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3040]
Hey Guys 

I noticed that on 1.2.7 and 1.2.6 if you click discover network then click cancel the discovery still runs

**Comment by bmfmancini** [comment]
Below is a capture fresh install 

tested with browsers
Edge
Firefox
Chrome

![AUTOM8 Discover cancel issue](https://user-images.githubusercontent.com/13388748/67211458-ca175600-f3e8-11e9-88fb-dc1b36f00d4d.gif)

**Comment by bmfmancini** [comment]
Hey Guys is there any more info you need on this one ?

**Comment by netniV** [comment]
Sorry, haven't looked into yet myself.  I'm sure if we need anything we'll be straight back to you.

**Comment by bmfmancini** [comment]
So i found that this is also happening for things like enable,disable etc 
if you click cancel it still saves the change
