### ISSUE TITLE
AUTOM8 network scan continues to run infinetly even when cancelled

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3041]
Hey Guys on 1.2.7 

If you click discover and the process is running if you want to cancel it in the middle the network stop scanning you will not see any AUTOM8 processes running but the status still shows running this is different than my other report here https://github.com/Cacti/cacti/issues/3040

**Comment by cigamit** [comment]
It's working perfectly in my setup.  Just tested with a brand new install.  Make sure you have good bidirectional mysql communications.  From the main data collector, goto Console > Data Collection > Data Collectors and edit the remote data collector.  Go down to the Database Settings and click 'Test Connection'.  Please ensure that this works.

**Comment by cigamit** [comment]
Found the issue.  Should be committed shortly.
