### ISSUE TITLE
Cacti PHP Modules and MYSQL Error

### ISSUE THREAD

**Issue by alisiddiqui1987** [Cacti/cacti#3043]
i am getting attached issue while installing Cacti on Windows 10. I am using latest version of Xampp for apache and php and mysql.

i am not familiar with any of the programming language so request to help with step by step guide lines to get it addressed.

Thanks for your time

**Additional context**
![cacti error](https://user-images.githubusercontent.com/56796839/67162468-d4523980-f381-11e9-907d-7204c093ec2e.PNG)
![mariadberror](https://user-images.githubusercontent.com/56796839/67162493-12e7f400-f382-11e9-869e-357772e3e3b1.PNG)
![mysql error](https://user-images.githubusercontent.com/56796839/67162496-17aca800-f382-11e9-9b50-89eb51647a39.PNG)

**Comment by bmfmancini** [comment]
Follow the installation guide
Make sure to populate the mysql timezone tables

Also looks like your Apache is not picking up the cli side of the php
modules try to restart the process

Systemctl restart apache2

For the mysql part  follow this

https://forums.cacti.net/viewtopic.php?t=56848

**Comment by bmfmancini** [comment]
Oh and this assume you are running linux

For windows it's a different set of steps

**Comment by alisiddiqui1987** [comment]
Thanks I need help for windows 10 OS

**Comment by netniV** [comment]
This is a configuration issue, so should be taken up on the forums where there are more users to be able to respond to it.

**Comment by alisiddiqui1987** [comment]
Hi NetniV

I have tried almost all the possible posts of cacti forum and other related stuffs but could not help to get it fixed. hence finally through cacti contact us page I had been directed here.

would appreciate some quick help to get it addressed.

Thanks in advance

**Comment by ddb4github** [comment]
For mysql timezone tables, you can ref: https://dev.mysql.com/downloads/timezones.html

**Comment by netniV** [comment]
https://github.com/Cacti/documentation/blob/develop/Installing-Under-Windows.md
