### ISSUE TITLE
Various issues in Chrome and only Chrome.

### ISSUE THREAD

**Issue by crkinard** [Cacti/cacti#3044]
Cacti v1.2.2
Raspberry Pi
Chrome 77.0.3865.120

Graphs do not show up when viewing a host in tree view. Only way to get ANY graph to show up in chrome is to: Management -> Devices -> Select device -> Graph list -> Right click broken image icon for graph and and say open in another tab.

Most right click menus on top of said broken image graphs do not work. Well, the right click menu shows but no sub items expand and clicking on anything does nothing.

Clicking on the user name in the top right does nothing. No drop down menu so impossible to set account settings or even log out.

Factory defaulting chrome (clearing all cache's and settings as well as unloading all extensions) does not fix the issue.

All works fine in IE.

**Comment by netniV** [comment]
What console errors are you seeing? I suspect slowness is an issue and therefore Chrome is terminating the scripts though the scripts themselves work fine.

**Comment by crkinard** [comment]
I am not sure. There seems to be no delay in loading the page or anything hanging when said page loads.

**Comment by netniV** [comment]
You'll need to use the network tab of the developer tools to investigate and check the console errors.

**Comment by crkinard** [comment]
`Refused to load the image 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAyMAAAFMCAIAAABXjPQ0AAAABmJLR0QA/wD/AP+gvaeTAAAgAElEQVR4nOydeXxMV/vAz10mM9mJ7CETEUuCoEGb2LeiilfR1ku1iGqV0uWt0ir6Q7VV5a2gJSqopVpvLa2t9iKKVEOoLSZ7Insms9/l98eVMWbLPbPfON+Pz8jMnPneZ869Mzl57jnPxS5dugQQCAQCgUAgEI6mtraWBAB06NDB3ZEgEAgEAoFANDV27NiBuzsGBAKBQCAQiCYLGmkhEAgEAoFAOAs00kIgEAgEAoFwFqS7A0AgEAgEAoEQJDU1NUaPNGvWzOgRNNJCIBAIBAKBsIXi4mLuh/z8/Ojo6Pz8/GHDhhm1QSMtBAKBQCAQCFtISEgAAFAUlZ+fHx8fX1BQYNoGjbQQCAQCgUAgbESpVN65c8fb2zs3N9fb29u0ARppIRAIBAKBQNjClStXAABSqTQ+Pr6ws...s0NIQz68agpVAoFi1ahBCSSqU4JAAAMAk1Li5Oe6cdAAAMs7a2trCwqKmpaWhoeP78uaenp52d3cOHD6uqqhobG21sbKhUan9/v52dXW9v7+DgIIfDIf2USqVWV1fLZDIrKysWi0Wn02tra+vr62fOnKmb38nJqa6urrGxkU6n0+l0giBwGBqNRqVS1dXVqVQqoVBIo9HodHp1dbWfn5/ueMja2hrv6P79+zY2Ns7OzpaWlrr7tbe3f/DgQVVVVUtLi6enJ47B1dW1r6/Pzs6OyWQqlUqJRNLS0sJgMAQCAbwRDwAwiUQiody8eVMoFE50JAAAMCoKhUKpVHp7e090IAAA8P/Onj0LN8MBAK+89vb2u3fvcrnciQ4EAACGg/e0AACvPFdXV1dX14mOAgAASMA9LQAAAACA8QIjLQAAAACA8QIjLQAAAACA8QIjLQAAAACA8UIpLi5uamqa6DAAAAAAAP6B/g/+uPGE8MRqogAAAABJRU5ErkJggg==' because it violates the following Content Security Policy directive: "default-src 'self' 'unsafe-inline'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.`

**Comment by netniV** [comment]
As this occurs in the jquery.zoom.js, I'm going to label this one a 3rd party bug for now.  We don't maintain that as far as I am aware altough @cigamit or @TheWitness may correct me on that.  Not sure how we would actually fix that without supplying an upstream patch.

**Comment by cigamit** [comment]
jquery.zoom.js was created by @browniebraun.  So, it's supported.  Have to see what is broken on Chrome.  I did some bug fixing lately for Chrome too.  However, it could be that Chrome, though very fast has thousands of bugs.

**Comment by cigamit** [comment]
Before I invest any time on this, please upgrade to branch 1.2.x.  Then let us know what you find.

**Comment by reubenfarrelly** [comment]
Curiously I am seeing something very similar but I'm not sure if it's the same bug or not.  As of 1.2.x today (28-Nov) I cannot get any graphs to display in Tree View in the Graphs Tab, with Chrome, or in fact Edge.  But with Firefox everything renders just fine.  If I change from Tree View everything works. 

I have however just changed from Modern to Classic Theme and it all immediately started working which leads me to think this could be a theme specific bug.  Can the OP confirm if this is the case as well if it is possible to log in and change it?

Looks a lot like Tree View + Modern theme is broken...

**Comment by netniV** [comment]
If you are on a broken theme, do you see any console javascript errors?

**Comment by reubenfarrelly** [comment]
I'm getting the following output from Edge:

HTML1300: Navigation occurred.
graph_view.php (1,1)

HTML1524: Invalid HTML5 DOCTYPE. Consider using the interoperable form “<!DOCTYPE html>”.
graph_view.php (1,1)

CONSOLE1810304: console.memory is not implemented and will return 0 for all attributes. Please use the memory profiler to monitor memory utilisation.

2HTML1300: Navigation occurred.
graph_view.php (1,1)

CONSOLE1810304: console.memory is not implemented and will return 0 for all attributes. Please use the memory profiler to monitor memory utilisation.

SEC7115: :visited and :link styles can only differ by colour. Some styles were not applied to :visited.
graph_view.php (1,1)

From Firefox:

Error: Can't find profile directory. XULStore.jsm:66:15
Unknown category for SetEventRecordingEnabled: fxmonitor
Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.
LoginManager: searchLogins: `formActionOrigin` or `httpRealm` is recommended LoginManager.jsm:473:13
Key event not available on some keyboard layouts: key=“i” modifiers=“accel,alt,shift” id=“key_browserToolbox” browser.xhtml
LoginManager: searchLogins: `formActionOrigin` or `httpRealm` is recommended LoginManager.jsm:473:13
Use of nsIFile in content process is deprecated. 8 NetUtil.jsm:253:8
NS_ERROR_FAILURE: Failed to open input source 'file:///' DevToolsUtils.js:678
‘src’ attribute of <script> element is not a valid URI: “/include/js/screenfull.js?60a2ad1d452950179fa4d2c5d1b5dee4” {cb095ba0-e6ae-4581-bf43-1f23ebf26450}:1:1
‘src’ attribute of <script> element is not a valid URI: “/include/js/jquery.js?2f0d15c70b7e652d5d61ed4032eb44af” {cb095ba0-e6ae-4581-bf43-1f23ebf26450}:1:1
‘src’ attribute of <script> element is not a valid URI: “/include/js/jquery-ui.js?f1f075fe32aca8216e55c5d00106fba7” {cb095ba0-e6ae-4581-bf43-1f23ebf26450}:1:1
‘src’ attribute of <script> element is not a valid URI: “/include/js/jquery.ui.touch.punch.js?4195aad6f616651c00557e84c6721646” {cb095ba0-e6ae-4581-bf43-1f23ebf26450}:1:1
‘src’ attribute of <script> element is not a valid URI: “/include/js/jquery.cookie.js?0b804d4f90de70b032a9986b22165b75” {cb095ba0-e6ae-4581-bf43-1f23ebf26450}:1:1
‘src’ attribute of <script> element is not a valid URI: “/include/js/js.storage.js?dbcd4e6ad90c47adfa9dd509ceb55eb9” {cb095ba0-e6ae-4581-bf43-1f23ebf26450}:1:1
‘src’ attribute of <script> element is not a valid URI: “/include/js/jstree.js?eeb830a71f511a57f23c2a74f36cbb66” {cb095ba0-e6ae-4581-bf43-1f23ebf26450}:1:1
‘src’ attribute of <script> element is not a valid URI: “/include/js/jquery.hotkeys.js?fbf82bcab286e9fc5cdf863eb067230f” {cb095ba0-e6ae-4581-bf43-1f23ebf26450}:1:1
‘src’ attribute of <script> element is not a valid URI: “/include/js/jquery.tablednd.js?a33b14ebf8ce2abf7911e62cbc19e0c5” {cb095ba0-e6ae-4581-bf43-1f23ebf26450}:1:1
‘src’ attribute of <script> element is not a valid URI: “/include/js/jquery.zoom.js?8914e0bed74b42db3f2bfc840db8e751” {cb095ba0-e6ae-4581-bf43-1f23ebf26450}:1:1
‘src’ attribute of <script> element is not a valid URI: “/include/js/jquery.multiselect.js?4a409cc12d02ac72805c8aa463b4b069” {cb095ba0-e6ae-4581-bf43-1f23ebf26450}:1:1
‘src’ attribute of <script> element is not a valid URI: “/include/js/jquery.multiselect.filter.js?ccf700b33985626742e26c6707028bed” {cb095ba0-e6ae-4581-bf43-1f23ebf26450}:1:1
‘src’ attribute of <script> element is not a valid URI: “/include/js/jquery.timepicker.js?f29132ab24085f909242175ad11cfcbc” {cb095ba0-e6ae-4581-bf43-1f23ebf26450}:1:1
‘src’ attribute of <script> element is not a valid URI: “/include/js/jquery.colorpicker.js?3b7032780b24b9b48050e5d245a36260” {cb095ba0-e6ae-4581-bf43-1f23ebf26450}:1:1
‘src’ attribute of <script> element is not a valid URI: “/include/js/jquery.tablesorter.js?8d331985e11cfc65649a915073cb30ed” {cb095ba0-e6ae-4581-bf43-1f23ebf26450}:1:1
‘src’ attribute of <script> element is not a valid URI: “/include/js/jquery.tablesorter.widgets.js?3cc0d7b3426e1db1e4a099db18b17e3c” {cb095ba0-e6ae-4581-bf43-1f23ebf26450}:1:1
‘src’ attribute of <script> element is not a valid URI: “/include/js/jquery.tablesorter.pager.js?8ca32d30195c98492cd028f582f07c8c” {cb095ba0-e6ae-4581-bf43-1f23ebf26450}:1:1
‘src’ attribute of <script> element is not a valid URI: “/include/js/jquery.metadata.js?bdd7532ce75cce796a5451bd4322d61f” {cb095ba0-e6ae-4581-bf43-1f23ebf26450}:1:1
‘src’ attribute of <script> element is not a valid URI: “/include/js/jquery.sparkline.js?c7638b825bc7deb1cf58c990825d35b2” {cb095ba0-e6ae-4581-bf43-1f23ebf26450}:1:1
‘src’ attribute of <script> element is not a valid URI: “/include/js/Chart.js?ae4cd3db34d0ea7ea1a9596d5d4120e6” {cb095ba0-e6ae-4581-bf43-1f23ebf26450}:1:1
‘src’ attribute of <script> element is not a valid URI: “/include/js/dygraph-combined.js?b5b448f71f8c3eb4a39506299bd81b0c” {cb095ba0-e6ae-4581-bf43-1f23ebf26450}:1:1
‘src’ attribute of <script> element is not a valid URI: “/include/js/d3.js?6db1c8feb22917c88023d14370218d26” {cb095ba0-e6ae-4581-bf43-1f23ebf26450}:1:1
‘src’ attribute of <script> element is not a valid URI: “/include/js/c3.js?4475647e3aea91584750d4726c065ccd” {cb095ba0-e6ae-4581-bf43-1f23ebf26450}:1:1
‘src’ attribute of <script> element is not a valid URI: “/include/layout.js?3838ec1b5a5992d776aae4c3e1eff89c” {cb095ba0-e6ae-4581-bf43-1f23ebf26450}:1:1
‘src’ attribute of <script> element is not a valid URI: “/include/js/pace.js?30fbf6c62d78d3367fa50bd51913200c” {cb095ba0-e6ae-4581-bf43-1f23ebf26450}:1:1
‘src’ attribute of <script> element is not a valid URI: “/include/realtime.js?6dab1b6aabdf85292fa2bc0f03043277” {cb095ba0-e6ae-4581-bf43-1f23ebf26450}:1:1
‘src’ attribute of <script> element is not a valid URI: “/include/themes/modern/main.js?48547b68fcbc990a479736fb2c779075” {cb095ba0-e6ae-4581-bf43-1f23ebf26450}:1:1
‘src’ attribute of <script> element is not a valid URI: “/include/vendor/csrf/csrf-magic.js” {cb095ba0-e6ae-4581-bf43-1f23ebf26450}:1:1
Use of nsIFile in content process is deprecated. NetUtil.jsm:253:8
NS_ERROR_FAILURE: Failed to open input source 'file:///' DevToolsUtils.js:678
Use of nsIFile in content process is deprecated. 11 NetUtil.jsm:253:8
Successfully compiled asm.js code (total compilation time 83ms) demangle.js

**Comment by netniV** [comment]
Just checking, but your cacti is the root website for the URL correct?

**Comment by reubenfarrelly** [comment]
Correct.  https://cacti.reub.net/  (no directory under that) .

**Comment by netniV** [comment]
And you have the $url_path in config.php set to "/" ?

**Comment by reubenfarrelly** [comment]
Yes:

/*
 * Set the $url_path to point to the default URL of your cacti install.
 * For example if your cacti install as at `https://serverip/cacti/` this
 * would be set to `/cacti/`.
 */

$url_path = '/';

/*
 * Default session name - session name must contain alpha characters
 */

$cacti_session_name = 'Cacti';

/*

I'm running from git 1.2.x branch and have been for some time.  So no external patches.

**Comment by netniV** [comment]
Cool, just narrows down any external factors.  The strange part is, I think those element sources do exist.  If you navigate to them, I'm sure you'll find the various JS files.

```console
cacti/include$ ls *.js
layout.js  realtime.js
```

```console
cacti/include$ ls js/*.js
js/c3.js                  js/jquery.metadata.js             js/jquery-ui.js
js/Chart.js               js/jquery.multiselect.filter.js   js/jquery.ui.touch.punch.js
js/d3.js                  js/jquery.multiselect.js          js/jquery.zoom.js
js/dygraph-combined.js    js/jquery.sparkline.js            js/js.storage.js
js/jquery.colorpicker.js  js/jquery.tablednd.js             js/jstree.js
js/jquery.cookie.js       js/jquery.tablesorter.js          js/pace.js
js/jquery.dropdown.js     js/jquery.tablesorter.pager.js    js/screenfull.js
js/jquery.hotkeys.js      js/jquery.tablesorter.widgets.js
js/jquery.js              js/jquery.timepicker.js
```

**Comment by netniV** [comment]
I wonder if this is complaining because the hostname is not part of the src attribute?

**Comment by reubenfarrelly** [comment]
Yes, maybe.  The interesting thing (that you've already suggested) is that yes those files do seem to be there:

thunderstorm /tmp # wget -S https://cacti.reub.net/include/js/Chart.js
--2019-11-30 00:33:33--  https://cacti.reub.net/include/js/Chart.js
Resolving cacti.reub.net... 2403:5800:7100:910::22, 192.168.10.22
Connecting to cacti.reub.net|2403:5800:7100:910::22|:443... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 200 OK
  Date: Fri, 29 Nov 2019 13:33:33 GMT
  Server: Apache
  Upgrade: h2,h2c
  Connection: Upgrade, Keep-Alive
  Last-Modified: Wed, 24 Oct 2018 09:35:49 GMT
  ETag: "62446-578f63622a0f6"
  Accept-Ranges: bytes
  Content-Length: 402502
  Cache-Control: max-age=1
  Expires: Fri, 29 Nov 2019 13:33:34 GMT
  Keep-Alive: timeout=15, max=100
  Content-Type: application/x-javascript
Length: 402502 (393K) [application/x-javascript]
Saving to: ‘Chart.js’

Chart.js            100%[===================>] 393.07K  --.-KB/s    in 0.002s  

2019-11-30 00:33:33 (254 MB/s) - ‘Chart.js’ saved [402502/402502]

thunderstorm /tmp # 

And yes they are all there in the include directory as expected.

**Comment by netniV** [comment]
So this suggests some form of browser issue.  Can you verify which browsers you have a problem with?

**Comment by cigamit** [comment]
It's almost as if the web server is not liking the leading slash.  Very odd.

**Comment by netniV** [comment]
Well, browser actually, that's a browser warning.

**Comment by reubenfarrelly** [comment]
I've got the same problem with both Chrome 78, Egde and IE all on latest Windows.  Only Firefox renders the page correctly.  The others all show the same problem, 

I've also just wiped and re-cloned my cacti repository from github, and still seeing the same problem there too.  The only config change I made was to fix the url_path .  So I'm pretty confident it's not a case of corrupted files.

I also "unpublished" all of the trees I have, the page rendering changes then as I now see the empty list on the left hand side where the tree items would be, but it's empty (as expected).  But it at least renders.  As soon as I publish any trees again the list shrinks to about 5 pixels wide as shown here.

![image](https://user-images.githubusercontent.com/8552189/69894485-7a776300-1374-11ea-8bc0-64fae2174ae8.png)

**Comment by cigamit** [comment]
Anything in the console that looks like an error?  What's the web server?

**Comment by reubenfarrelly** [comment]
Web server is apache:

thunderstorm ~ # apache2 -V
Server version: Apache/2.4.41 (Unix)
Server built:   Nov 17 2019 21:28:54
Server's Module Magic Number: 20120211:88
Server loaded:  APR 1.7.0, APR-UTIL 1.6.1
Compiled using: APR 1.7.0, APR-UTIL 1.6.1
Architecture:   64-bit
Server MPM:     event
  threaded:     yes (fixed thread count)
    forked:     yes (variable process count)
Server compiled with....
 -D APR_HAS_SENDFILE
 -D APR_HAS_MMAP
 -D APR_HAVE_IPV6 (IPv4-mapped addresses enabled)
 -D APR_USE_PROC_PTHREAD_SERIALIZE
 -D APR_USE_PTHREAD_SERIALIZE
 -D SINGLE_LISTEN_UNSERIALIZED_ACCEPT
 -D APR_HAS_OTHER_CHILD
 -D AP_HAVE_RELIABLE_PIPED_LOGS
 -D DYNAMIC_MODULE_LIMIT=256
 -D HTTPD_ROOT="/usr"
 -D SUEXEC_BIN="/usr/bin/suexec"
 -D DEFAULT_PIDLOG="/var/run/httpd.pid"
 -D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
 -D DEFAULT_ERRORLOG="logs/error_log"
 -D AP_TYPES_CONFIG_FILE="/etc/apache2/mime.types"
 -D SERVER_CONFIG_FILE="/etc/apache2/httpd.conf"
thunderstorm ~ # 

There are no obvious errors in the console.  I've also reproduced the same problem with the new Microsoft Edge/Chromium Dev builds.  So the only browser not affected so far is Firefox.

**Comment by reubenfarrelly** [comment]
Ok here's another observation.  If I click on "Tree View" in Chrome or IE or Edge, I get sent to this URL:

https://cacti.reub.net/graph_view.php?action=tree

On all browsers that shows the blank view I am consistently seeing.  If I enter the full URL of a Tree View page (such as https://cacti.reub.net/graph_view.php?action=tree&node=tree_anchor-6&site_id=-1&host_id=-1&host_template_id=-1&hgd=&hyper=true) then the page loads in it's entirely and everything works, including further navigation. 

Is there supposed to be a redirect/refresh of some sort after going to the "https://cacti.reub.net/graph_view.php?action=tree" URL? 

My default user view is Tree View, and the link on the top right of the page to Tree View is to that URL as well.  So that would explain why I'm seeing the problem.

Curiously after erasing all content in Firefox that browser too now shows the issue.

**Comment by cigamit** [comment]
Please goto the browsers debug console and look for errors please.

**Comment by netniV** [comment]
> Is there supposed to be a redirect/refresh of some sort after going to the "[cacti.reub.net/graph_view.php?action=tree](https://cacti.reub.net/graph_view.php?action=tree)" URL?

No, the URL at the top remains the same current.  when you click, the call is intercepted and converted to an AJAX call to pull the data back.

**Comment by reubenfarrelly** [comment]
Hmm ok.  I may need more help gathering the required info for this as the Chrome Developer Tools aren't entirely obvious to use.  Can you please let me know where I would look for the sort of errors you need to see?  Or the Edge equivalent, as Chrome intermittently works (and is working right now but yet Edge is not).
I did paste in some errors above in https://github.com/Cacti/cacti/issues/3044#issuecomment-559618514 though.

**Comment by cigamit** [comment]
I think we will continue to keep this open after the 1.2.8 release.  We can ask all those who have contributed to update us after release.

**Comment by netniV** [comment]
> Can you please let me know where I would look for the sort of errors you need to see? 

The console tab will always show errors that are generated.  You can also view any network related requests/responses by clicking on the network tab before you click a link or refresh a page.  I often find it best to use the clear option before clicking a call that will be made so that I know the tab is just for that call.

**Comment by nuno-silva** [comment]
Did you guys completely ignore the `Content Security Policy` errors (which are preventing images and scripts from loading) in https://github.com/Cacti/cacti/issues/3044#issuecomment-544557728?

@crkinard what web server are you using? Did you set an explicit Content Security Policy directive in your web server?

**Comment by netniV** [comment]
> Did you guys completely ignore the `Content Security Policy` errors (which are preventing images and scripts from loading) in [#3044 (comment)](https://github.com/Cacti/cacti/issues/3044#issuecomment-544557728)?

Bit harsh, but technically not =wrong.  I have never set any CSP so have never come across that before myself.

**Comment by TheWitness** [comment]
Same here.  We could add to the header I guess.

**Comment by nuno-silva** [comment]
Sorry, I didn't mean to be harsh.

Most likely, @crkinard has some CSP set in his webserver. If that's the case, adding CSP headers to Cacti would not solve the issue.

**Comment by netniV** [comment]
As we haven't had a response to the questions in two months, I'm going to close this for now.  If it resurfaces we can reopen it.
