### ISSUE TITLE
When viewing Aggregate Graphs, an error due to undefined referrer may occur

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#3045]
**Describe the bug**
PHP Notice 'Undefined index: aggregate_referer' when directly access aggregate_graphs.php with param like browser history or address bar auto-complete

**To Reproduce**
1. Directly access aggregate_graphs.php like "'cacti/aggregate_graphs.php?action=edit&id=4566&tab=preview&debug=1"
2. Check cacti.log
3. See error

**Detail cacti.log**
``` log
CMDPHP PHP ERROR NOTICE Backtrace:  (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[618]:CactiErrorHandler())
ERROR PHP NOTICE: Undefined index: aggregate_referer in file: /var/www/html/cacti/aggregate_graphs.php  on line: 618
```

**Comment by netniV** [comment]
This should now be fixed, please review 👍
