### ISSUE TITLE
When using Classic theme, Location dropdown does not allow for free text entry

### ISSUE THREAD

**Issue by battery-hue** [Cacti/cacti#3046]
**Describe the bug**
This bug applies /only/ when **Classic** theme is enabled and active. The bug is an inability to type any new text into the "Location" drop down combo menu box

**To Reproduce**
1. Install a fresh copy of Cacti in a sandboxed environment (in this case, version 1.2.7)
2. Verify **Classic** theme is enabled. If not, enable **Classic** theme for logged in user.
3. Navigate to Console -> Create -> New Device
4. Locate "Location" setting under "General Device Options" (3rd setting from top).
5. Any attempt to type location into drop down combo menu box fails; cannot type text into combo menu box.

**Expected behavior**
I expect to be able to type in new locations into the drop down combo menu box as I am able to when any other theme is active. If I select any other theme, I am able to type new locations into this option's drop down combo menu box.

**Screenshots**
<img width="1421" alt="Screen Shot 2019-10-22 at 8 22 56 am" src="https://user-images.githubusercontent.com/56883448/67302125-43747e80-f4a5-11e9-8868-54019de5bef4.png">

**Desktop (please complete the following information):**
 - OS: MacOS 10.15
 - Browse: Safari
 - Version: 13.0.2 (15608.2.30.1.1)

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Additional context**
Don't hesitate asking for any useful additional information.

**Comment by cigamit** [comment]
I just want to toss the Classic theme, but some people just have to have it.

**Comment by cigamit** [comment]
Not sure I want to fix this one.  I'm marking known issue for now.  Have to talk it over with the rest of the team.
