### ISSUE TITLE
When saving settings, ignore remote pollers who have not checked in recently

### ISSUE THREAD

**Issue by thurban** [Cacti/cacti#3047]
When saving settings it seems like changes are immediately propagated/saved to all remote pollers.  This is causing a very long delay before anything can be done again.

Can this be delayed and propagated along the normal sync time ?

This behavior was observed up until Cacti 1.2.7

**Comment by netniV** [comment]
This was introduced to ensure remote poller are using the same ones as soon as possible.

**Comment by thurban** [comment]
Which is a good intent but in my case it causes a waiting time of 2 minutes for each small change due to very remote pollers and offline pollers.

It would be nice to be able to disable this immediate sync and use a "sync settings" from the remote pollers view next to the full sync option ?

**Comment by netniV** [comment]
I think that could be another useful enhancement

**Comment by cigamit** [comment]
This can be fixed with a bulk insert.  Let's do that instead.  It's a minor performance bug.

**Comment by cigamit** [comment]
Looks like it's a bulk insert anyway.  @thurban, how long does a save take on your system?

**Comment by thurban** [comment]
Minutes. It would be ok but as soon as some poller are offline it goes into timeouts which cause the  huge delay

Sent from Nine
________________________________
Von: Jimmy Conner <notifications@github.com>
Gesendet: Samstag, 9. November 2019 18:09
An: Cacti/cacti
Cc: Thomas Urban; Mention
Betreff: Re: [Cacti/cacti] Delay settings changes propagation to remote pollers (#3047) 

Looks like it's a bulk insert anyway. @thurban, how long does a save take on your system?

**Comment by cigamit** [comment]
Well, we could force a sync of the settings table at the next poll, but that will delay as well.  I'll have to give it some thought as to not make things messy.

**Comment by thurban** [comment]
How about skipping pollers that have not reported in for some time and sync them only when they report back ?



Sent from Nine
________________________________
Von: Jimmy Conner <notifications@github.com>
Gesendet: Samstag, 9. November 2019 19:11
An: Cacti/cacti
Cc: Thomas Urban; Mention
Betreff: Re: [Cacti/cacti] Delay settings changes propagation to remote pollers (#3047) 

Well, we could force a sync of the settings table at the next poll, but that will delay as well. I'll have to give it some thought as to not make things messy.

**Comment by cigamit** [comment]
Not a bad idea.  Let's do that first.

**Comment by cigamit** [comment]
Update settings.php and let me know how the performance is now.

**Comment by cigamit** [comment]
Any updates?

**Comment by thurban** [comment]
Sorry, missed the original request.  Will check next week and report back with some numbers.

**Comment by cigamit** [comment]
Thanks.  We are releasing this weekend though.  I'm pretty sure you will like the performance change though.

**Comment by thurban** [comment]
Ok.  Had a quick look at the code change. I'm more then fine with that change.

**Comment by cigamit** [comment]
Okay, I'll close this then.  Thanks Thomas!
