### ISSUE TITLE
Allow different log settings for remote pollers

### ISSUE THREAD

**Issue by thurban** [Cacti/cacti#3048]
Running remote pollers using Raspberry Pis, the logging can be an issue in regards to SD-Card wearing and space. 
Especially when running debug log, remote pollers can fill up easily with log messages.

I would like to be able to set a different logging mode for remote pollers, so I can still leverage high logging mode on the master system while making sure remote pollers don't do unecessary logging.

This has been tested with Cacti 1.2.7

**Comment by netniV** [comment]
That would be a feature request for 1.3 but I think it’s a valid one.
