### ISSUE TITLE
Can't create new graphs of "None Host Type"

### ISSUE THREAD

**Issue by gmuellerfr** [Cacti/cacti#305]
I've just migrated from 0.8.h to 1.0.1.
Beforehand I've been using a lot of graphs from type "None Host" to bring different things into one graph.
Now, when I select the button "New Graphs", I'm presented with a sorted list of the first 30 devices beginning with "a".
When I edit this field, I can search for each device, which is present in my device list, but I can't select "none".
There is a selector in the code of graphs_new.php, which should made this possible, but the logic seems to get a valid host_id and the mask shows every time an existing device.
There is no difference in code between 1.0.1 to 1.0.3.
The decision what to show on page is made between line 451 and line 472 in this piece of code.

**Comment by cigamit** [comment]
It's working for me.  Just clear the field from what you searched for, and then you will see that "None" is selectable.

**Comment by gmuellerfr** [comment]
Sorry, I don't agree. Maybe I haven't made clear what I wan't.
It's not a problem to find graphs, which I previously created with type NONE.
I want to create a new graph of this type and I don't find a way to do so.
There is no button "ADD" in the graph section, where I can search for graphs. (as before 1.0)
There is no way to do so on "New Graphs", because the device you will create graphs for, should exist!

I'm not sure, wether this issue will be reopen, if I give only give a comment...

Kind Regards

**Comment by cigamit** [comment]
Goto Console -> Settings -> General -> Other Settings -> Graph/Data Source Creation Mode, and set to 'Advanced' and you will get your 'Add' button back.

**Comment by gmuellerfr** [comment]
Thanks
