### ISSUE TITLE
Improper validation call prior to plugin call

### ISSUE THREAD

**Issue by majed17** [Cacti/cacti#3050]
using latest 1.2.x
i get: 
 `2019/10/24 16:24:01 - CMDPHP Input Validation Not Performed for 'leaf_id' Backtrace: (/graph_view.php[357]:grow_right_pane_tree(), /lib/html_tree.php[1372]:get_request_var(), /lib/html_utility.php[369]:html_log_input_error(), /lib/html_validate.php[44]:cacti_debug_backtrace()) `

after a device experienced a timeout

**Comment by cigamit** [comment]
Closing.  Confirmed resolved.
