### ISSUE TITLE
CMDPHP Validation Error - thumbnails in Graph View

### ISSUE THREAD

**Issue by reubenfarrelly** [Cacti/cacti#3053]
Seeing this error and a blank screen with the Graphs tab as of 9fbb0621f284ceba8ca2058de2f43f2f9b766165 .  Tracking git branch 1.2x:

25/Oct/2019 21:25:31 - CMDPHP Validation Error, Variable:thumbnails, Value:on Backtrace: (/graph_view.php[221]:top_graph_header(), /lib/functions.php[3253]:include_once(), /include/top_graph_header.php[54]:grow_dhtml_trees(), /lib/html_tree.php[95]:html_validate_tree_vars(), /lib/html_tree.php[812]:validate_store_request_vars(), /lib/html_utility.php[704]:die_html_input_error(), /lib/html_validate.php[64]:cacti_debug_backtrace())

php-7.3.11 on Gentoo Linux x86_64 .

This is only a problem with Tree view.  List and Preview view work fine.

**Comment by cigamit** [comment]
Need more information like for example what we the URL that you used.  I can not presently reproduce this.

**Comment by cigamit** [comment]
@reubenfarrelly, I suspect that this was resolved some time ago by @netniV.

**Comment by cigamit** [comment]
Found the issue.

**Comment by cigamit** [comment]
Confirmed and resolved.  Thanks!
