### ISSUE TITLE
php not interpreted by server 

### ISSUE THREAD

**Issue by gaetan1903** [Cacti/cacti#3054]
**Describe the bug**
when I tried to enter in localhost/cacti, it's return the source code of php 

**Desktop (please complete the following information):**
 - OS:  Arch Linux
 - Browser : Brave Browser

cacti using apache

But my php in other thing , works 
![Capture d’écran de 2019-10-27 01-01-18](https://user-images.githubusercontent.com/43904633/67626564-80e65c80-f855-11e9-9463-6147528d49d4.png)

**Comment by netniV** [comment]
This is an environmental issue and can be easily solved by googling.  It is not a Cacti issue.
