### ISSUE TITLE
AUTOM8 should allow SNMP as a ping method for networks that have devices that dont respond to a ping

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3061]
Hey Guys 

I am on 1.2.7 and I am seeing that AUTOM8 will scan a device that is not pingable but can be reached by SNMP and will not add the device 

2019/10/29 16:13:31 - AUTOM8 [PID: 6019] Network lb's Thread 1 Finished, 1 IPs Scanned, 0 IPs Responded to Ping, 0 Responded to SNMP, 0 Device Added, 0 Graphs Added to Cacti
2019/10/29 16:13:31 - AUTOM8 [PID: 6017] Network Discover is now running for Subnet Range '43' 

However, when you do a snmpwalk  to the device all is well 

I can add the device manually without issue

**Comment by cigamit** [comment]
Okay, re-edit your network and change the ping method to SNMP Get.  Then it will behave this way.  Gets the agents object id.
