### ISSUE TITLE
First time installation keeps asking for password change

### ISSUE THREAD

**Issue by fr500** [Cacti/cacti#3064]
**Describe the bug**
Hello. I just downloaded the latest master to test (79f29cd)
I unzipped, edited configuration files, created the database and browsed to cacti

I was prompted to enter password (admin/admin) then to change password and that's were the issue occurs. I get two checkmarks (I assume this is password complexity requirements) and change it, but I get redirected back to the same screen

**Expected behavior**
It should change and ask me to login again

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Firefox, Chrome

**Comment by netniV** [comment]
Do you see any errors in your log files? Is the database updated with a change of password?

**Comment by bmfmancini** [comment]
Hey Guys 

I had a bug report on my cacti install script for this exact issue but it seems to be related to 1.3.0
https://github.com/bmfmancini/cacti-install-wizard/issues/15
Some of the users left the logs they found there but nothing specific

**Comment by netniV** [comment]
Please be aware that develop is the cutting and it must have been develop not master you have downloaded based off the hash you've supplied.  Master would be the latest from the 1.2.x branch that has been released (at least it should be!).  For the latest 1.2.x development, use the 1.2.x branch.

I could really use your log files to see why you were having the error.

**Comment by netniV** [comment]
I think I identified the reason for this with develop.  The missing columns have been added to the cacti.sql script.  If you have done a fresh install, you can download the latest cacti.sql from develop and import that to a fresh database.  Alternatively, you can run the database upgrade cli program forcing the original version to 1.2.7 and it will add the new fields in.

**Comment by netniV** [comment]
This was fixed with https://github.com/Cacti/cacti/commit/feb639824ad460be0359c4e2afe5cc48dbe3632e
