### ISSUE TITLE
Need to add secure flag to cookie when HTTPS is enabled

### ISSUE THREAD

**Issue by kim-fitness** [Cacti/cacti#3066]
**Describe the bug**
The Set-Cookie does not contains secure flag, which is considered as CWE of "Sensitive Cookie in HTTPS Session Without 'Secure' Attribute", reference link as below,
http://cwe.mitre.org/data/definitions/614.html

**To Reproduce**
1. Go to 'login' page
2. Click on 'Keep me signed in' and then do login
3. See the Set-Cookie in http response header of calling index.php by HTTP POST
4. There is no secure flag.

**Expected behavior**
Need secure flag for Set-Cookie.
The attached picture shows the correct behavior after I fixed this issue.

**Screenshots**
![Screen Shot 2019-11-04 at 4 27 47 PM](https://user-images.githubusercontent.com/47587743/68107588-4bf69b80-ff20-11e9-924a-9e01b59159d4.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by cigamit** [comment]
Closing.  Thanks for your contribution.
