### ISSUE TITLE
Input Validation Not Performed for id Backtrace: user_admin.php

### ISSUE THREAD

**Issue by battery-hue** [Cacti/cacti#3068]
**Describe the bug**
I have enabled 'Log Input Validation Issues'. When i save any of my user's settings (in Console -> Configuration -> Users -> User Settings), this message is logged:

`01.Nov.2019 08:30:58 - CMDPHP Input Validation Not Performed for 'id' Backtrace: (/user_admin.php[46]:form_save(), /user_admin.php[612]:get_request_var(), /lib/html_utility.php[346]:html_log_input_error(), /lib/html_validate.php[44]:cacti_debug_backtrace())`

**To Reproduce**
1. Enable Log Input Validation Issues
2.Nativate to Console -> Configuration -> Users -> [select any user] -> User Settings
3. Make any change to user's settings
4. Check logs

**Expected behavior**
To be able to make change to user settings without failing input validation

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Safari
 - Version: 13.0.2

**Smartphone (please complete the following information):**
N/A

**Additional context**
I have noticed, on occasion, that my log file has a few "Input Validation Not Performed for 'id' Backtrace: " errors messages. As of this report, I am only able to verify error is triggered when making changes to user settings. I have not yet be able to identify why/when the other errors are triggered.

**Comment by netniV** [comment]
A few have been fixed in the dev version so if you have the dev version they may be resolved

**Comment by cigamit** [comment]
Just did a double check, and though although this issue is not there any longer, there were a few cases where there is no pre-validation.  This is not a problem due to us using prepared statements, but to keep the log clean, I have corrected them anyway.  Commit coming shortly.
