### ISSUE TITLE
Cacti 0.8.7g doesn't work with ltb-project/cacti-plugins

### ISSUE THREAD

**Issue by wangtel** [Cacti/cacti#3069]
ltb-project is a cacti plugin for LDAP monior,but it can't draw graph in cacti 0.8.7g.
In cacti 0.8.7‘s cacti.log，the line of perl script is “ SCRIPT: perl /var/www/html/scripts/openldap_operations.pl -h x.x.x.x -p 389 -D username -W password -t 3 -v 3, output: 0 ”.However, in realtime graph it works well.

It's all OK in cacti 1.2.7,but we can't mirgrate from 0.8.7g to 1.2.7.

**Comment by netniV** [comment]
The likelihood is that it’s either permissions or wrong script type bu5 that’s just guesswork. Unfortunately we don’t support 0.8.x anymore other than to migrate forwards
