### ISSUE TITLE
Pathname to rra is dereferenced in database, problems with symlinks

### ISSUE THREAD

**Issue by ibatten** [Cacti/cacti#3071]
I have the mutable data for cacti in /var, and I have a symlink to the cacti installation itself.

So:

igb@offsite9:/usr/share/cacti$ ls -ltr
total 12
drwxrwxr-x 17 cacti cacti 4096 Sep  9 10:11 cacti-1.2.6
drwxrwxr-x 16 cacti cacti 4096 Nov  4 17:06 cacti-1.2.7
lrwxrwxrwx  1 root  root    11 Nov  4 17:07 site -> cacti-1.2.7
igb@offsite9:/usr/share/cacti$

and

igb@offsite9:/usr/share/cacti/cacti-1.2.7$ ls -ld rra
lrwxrwxrwx 1 cacti cacti 18 Nov  4 17:06 rra -> /var/lib/cacti/rra
igb@offsite9:/usr/share/cacti/cacti-1.2.7$ 

Yesterday, I deleted 1.2.[1-5], as I no longer need them, and a bunch of graphs stopped working.

It turns out that (EDIT TO CORRECT) the symlink to the release is dereferenced before it is inserted into the poller_items table, at the time of update.

`MariaDB [cacti]> select substr(rrd_path,1, 30) as head, count(distinct(local_data_id)) from poller_item where rrd_path like '%cacti-%' group by head;
+--------------------------------+--------------------------------+
| head                           | count(distinct(local_data_id)) |
+--------------------------------+--------------------------------+
| /usr/share/cacti/cacti-1.2.5/r |                             93 |
| /usr/share/cacti/cacti-1.2.6/r |                             46 |
+--------------------------------+--------------------------------+
2 rows in set (0.000 sec)

MariaDB [cacti]> 
`

If I then make a trivial change to one device, 1.2.7 appears:

`MariaDB [cacti]> select substr(rrd_path,1, 30) as head, count(distinct(local_data_id)) from poller_item where rrd_path like '%cacti-%' group by head;
+--------------------------------+--------------------------------+
| head                           | count(distinct(local_data_id)) |
+--------------------------------+--------------------------------+
| /usr/share/cacti/cacti-1.2.5/r |                             93 |
| /usr/share/cacti/cacti-1.2.6/r |                             35 |
| /usr/share/cacti/cacti-1.2.7/r |                             11 |
+--------------------------------+--------------------------------+
3 rows in set (0.002 sec)

MariaDB [cacti]> 
`

This behaviour is surprising.  And new in 1.2.something - I have operated with rra as a symlink since 0.8.7.  I suspect it's new since 1.2.5, because unless I have edited every device since then (and I don't think I have), all such paths are either 1.2.5 or 1.2.6 (or now 1.2.7).

My temporary workaround is to re-create cacti-1.2.5 just to contain a link to rra, and then I will edit each device in order to alter the path (or, if I am feeling brave, update poller_item behind cacti's back with a bit of SQL, but I never like doing that).  However, it seems an odd feature: is there a reason for it?

**Comment by netniV** [comment]
It was introduced to prevent bugs with remote poller where the symlink didn’t exist amongst other things. This is by design and not a bug.
