### ISSUE TITLE
ss_net_snmp_disk_bytes.php and ss_net_snmp_disk_io.php do not report mmcblk data.

### ISSUE THREAD

**Issue by jkrinke** [Cacti/cacti#3074]
**Describe the bug**

ss_net_snmp_disk_bytes.php and ss_net_snmp_disk_io.php do not report mmcblk data as found on Raspberry Pis. The data reported from snmp is filtered so that only 'sd[a-z]' devices are considered.

**To Reproduce**
Add Combined SCSI ... graphs for a Raspberry.

Fixes to both files are attached so that mmcblk[0-9] devices are considered.

[patch.txt](https://github.com/Cacti/cacti/files/3819868/patch.txt)

**Comment by netniV** [comment]
So, I can't vouch for the rPI output but the patch itself looks ok.  Are you able to do that as a pull request with a changelog entry so we can commit it?

**Comment by cigamit** [comment]
Pull request would be perfect.  We will have to update the Net-SNMP Device Package for sure.

**Comment by jkrinke** [comment]
I have created a pull request #3097 for it.

**Comment by cigamit** [comment]
Can you move that to the 1.2.x branch?  Otherwise, it won't make the 1.2.8 release.

**Comment by jkrinke** [comment]
This has now been merged to the 1.3.x branch. If wanted, I can also create it for the 1.2.x branch.

**Comment by netniV** [comment]
I think we should test this out rather than push to the 1.2.x at this late stage.  I don't believe it will be an issue, but always worth letting people have a chance to break things 👍
