### ISSUE TITLE
Allow disabling remote poller resource cache replication to support upgrade testing

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3077]
Hey guys 

So I am thinking that if you have a large install with multiple pollers and you are upgrading you might not want upgrade all of the pollers at once in case something comes up I.e a bug or something 

Upgrade a single poller everything will update the files as well which could be bad if something goes sideways 

I vision something like a way to mark that poller so that it doesn't replicate the files via resource cache   from the rest of the pollers then if all goes well you can upgrade the others 

I know this may be a challenge due to db changes and other things but I think if there is a way to do it that would be good and make cacti more flexible during updates 

I hope this .makes sense

**Comment by cigamit** [comment]
Yea, I think it's a good thing.  I think it might be critical enough to pull ahead to 1.2.8.  I'm just a bit overwhelmed at the moment.  Though a number of issues were resolved today.

**Comment by cigamit** [comment]
I have decided to pull this ahead as it provides significant assistance during upgrades.

**Comment by cigamit** [comment]
Console > Settings > Poller > Disable Resource Cache Replication

**Comment by bmfmancini** [comment]
Wow dude that's awesome 
Thanks alot
