### ISSUE TITLE
File not found warnings when viewing graph debug from remote data collector

### ISSUE THREAD

**Issue by cigamit** [Cacti/cacti#3078]
**Describe the bug**
When viewing a graph in debug mode enabled on remote data collectors, instead of seeing an 'Ok' or some warning as to why the RRDtool did not render, you get a 'File not found' warning as if the syntax is not leveraging the remote_agent.php file.

**To Reproduce**
1. Login to a Remote Data Collector in 'online' mode.
2. Goto Console > Management > Graphs and Edit a Graph
3. Enable Graph Debug

**Expected behavior**
You should get rendering data from the Remote Agent.

**Comment by cigamit** [comment]
For now, we will simply skip the check.

**Comment by bmfmancini** [comment]
Confirmed working fix 1.2.8 off the 1.2.x branch
