### ISSUE TITLE
Allow for domain names to be stripped from long device descriptions

### ISSUE THREAD

**Issue by cigamit** [Cacti/cacti#3079]
**Describe the bug**
When viewing some graph and management pages, the filters get very wide and with long device hostname or device descriptions this can cause the filter to be hidden too quickly.

**Expected behavior**
There should be a way to shorten the hostname so that the filters do not get hidden so easy.

**Comment by cigamit** [comment]
Resolved.

**Comment by bmfmancini** [comment]
Tested and this works great!

Good work again @cigamit !
