### ISSUE TITLE
AUTOM8 1.2.7 off 1.2.x branch  Device showiung in unkown state

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3082]
Hey Guys 

So I am testing the new additions from this weekend I noticed the following issue

So far what I am seeing is that AUTOM8 does complete the scan adds the device into the cacti but it shows the device in unkown status even after the next poll

If you go to the remote poller and click on the device avaliability checks are all good'

![image](https://user-images.githubusercontent.com/13388748/68554091-0dffe880-03f4-11ea-990d-7468f24a24a1.png)

![image](https://user-images.githubusercontent.com/13388748/68554108-296af380-03f4-11ea-8b1e-cd4e6380830f.png)

From the Main poller when clicking on the device 

![image](https://user-images.githubusercontent.com/13388748/68554126-4e5f6680-03f4-11ea-83dd-f2d40370e54c.png)

Log output after forcing a sync

2019/11/10 19:51:57 - WEBUI NOTE: All selected Remote Data Collectors in [2] synchronized correctly by user admin
--
2019/11/10 19:51:57 - CMDPHP NOTE: Table data_input_data Not Replicated to Remote Poller 2 Due to No Rows Found
2019/11/10 19:51:57 - CMDPHP NOTE: Table graph_templates_item Not Replicated to Remote Poller 2 Due to No Rows Found
2019/11/10 19:51:57 - CMDPHP NOTE: Table data_template_rrd Not Replicated to Remote Poller 2 Due to No Rows Found
2019/11/10 19:51:57 - CMDPHP NOTE: Table data_template_data Not Replicated to Remote Poller 2 Due to No Rows Found
2019/11/10 19:51:57 - CMDPHP NOTE: Table graph_local Replicated to Remote Poller 2 With 3 Rows Updated
2019/11/10 19:51:57 - CMDPHP NOTE: Table data_local Not Replicated to Remote Poller 2 Due to No Rows Found
2019/11/10 19:51:57 - CMDPHP NOTE: Table poller_reindex Replicated to Remote Poller 2 With 1 Rows Updated
2019/11/10 19:51:57 - CMDPHP NOTE: Table host_snmp_cache Replicated to Remote Poller 2 With 281 Rows Updated
2019/11/10 19:51:57 - CMDPHP NOTE: Table host Replicated to Remote Poller 2 With 1 Rows Updated
2019/11/10 19:51:57 - CMDPHP NOTE: Table poller_item Not Replicated to Remote Poller 2 Due to No Rows Found
2019/11/10 19:51:57 - CMDPHP NOTE: Table poller_command Not Replicated to Remote Poller 2 Due to No Rows Found
2019/11/10 19:51:57 - CMDPHP NOTE: Table host_snmp_query Replicated to Remote Poller 2 With 1 Rows Updated
2019/11/10 19:51:57 - CMDPHP NOTE: Table user_domains_ldap Not Replicated to Remote Poller 2 Due to No Rows Found
2019/11/10 19:51:57 - CMDPHP NOTE: Table user_domains Not Replicated to Remote Poller 2 Due to No Rows Found
2019/11/10 19:51:57 - CMDPHP NOTE: Table user_auth_realm Replicated to Remote Poller 2 With 28 Rows Updated
2019/11/10 19:51:57 - CMDPHP NOTE: Table user_auth_group_realm Not Replicated to Remote Poller 2 Due to No Rows Found
2019/11/10 19:51:57 - CMDPHP NOTE: Table user_auth_group_perms Not Replicated to Remote Poller 2 Due to No Rows Found
2019/11/10 19:51:57 - CMDPHP NOTE: Table user_auth_group_members Not Replicated to Remote Poller 2 Due to No Rows Found
2019/11/10 19:51:57 - CMDPHP NOTE: Table user_auth_group Not Replicated to Remote Poller 2 Due to No Rows Found
2019/11/10 19:51:57 - CMDPHP NOTE: Table user_auth Replicated to Remote Poller 2 With 2 Rows Updated
2019/11/10 19:51:57 - CMDPHP NOTE: Table version Replicated to Remote Poller 2 With 1 Rows Updated
2019/11/10 19:51:57 - CMDPHP NOTE: Table poller Replicated to Remote Poller 2 With 2 Rows Updated
2019/11/10 19:51:57 - CMDPHP NOTE: Table data_input_fields Replicated to Remote Poller 2 With 98 Rows Updated
2019/11/10 19:51:57 - CMDPHP NOTE: Table snmp_query Replicated to Remote Poller 2 With 9 Rows Updated
2019/11/10 19:51:57 - CMDPHP NOTE: Table host_template_snmp_query Replicated to Remote Poller 2 With 14 Rows Updated
2019/11/10 19:51:57 - CMDPHP NOTE: Table host_template_graph Replicated to Remote Poller 2 With 48 Rows Updated
2019/11/10 19:51:57 - CMDPHP NOTE: Table host_template Replicated to Remote Poller 2 With 6 Rows Updated
2019/11/10 19:51:57 - CMDPHP NOTE: Table data_input Replicated to Remote Poller 2 With 31 Rows Updated

**Comment by bmfmancini** [comment]
Oh btw  here is the availability checks 

![image](https://user-images.githubusercontent.com/13388748/68554192-e5c4b980-03f4-11ea-86e7-f8f960f2796d.png)

**Comment by cigamit** [comment]
This is quite odd.  This is a new install right?

**Comment by cigamit** [comment]
If it's a new install, please upload your install logs.

**Comment by bmfmancini** [comment]
This is a upgrade from 1.2
5 in my lab to 1.2.7

**Comment by bmfmancini** [comment]
Here is the install log from the upgrade

[root@localhost log]# cat install-complete.log 
[2019-11-09 21:45:51] [          global always  ] Spawning background process: /bin/php '/var/www/html/cacti/install/background.php' 1573353951.834
[2019-11-09 21:45:52] [          global always  ] Setting PHP Option max_execution_time = 0
[2019-11-09 21:45:52] [          global always  ] Setting PHP Option memory_limit = -1
[2019-11-09 21:45:52] [          global always  ] Starting UPGRADE Process for v1.2.7
[2019-11-09 21:45:52] [          global always  ] No tables where found or selected for conversion
[2019-11-09 21:45:52] [          global always  ] Switched from  to /tmp/cdu5tjH52
[2019-11-09 21:45:52] [          global always  ] NOTE: Using temporary file for db cache: /tmp/cdu5tjH52
[2019-11-09 21:45:52] [          global always  ] Upgrading from v1.2.5 (DB 1.2.7 (DB: 1.2.5)) to v1.2.7
[2019-11-09 21:45:52] [          global always  ] Finished UPGRADE Process for v1.2.7
[2019-11-09 21:45:52] [          global always  ] Installation was started at 2019-11-10 02:45:52, completed at 2019-11-10 02:45:52
[root@localhost log]# 
[root@localhost log]# cat install-general.log 
[2019-11-09 21:45:51] [ always  ] Spawning background process: /bin/php '/var/www/html/cacti/install/background.php' 1573353951.834
[2019-11-09 21:45:52] [ always  ] Setting PHP Option max_execution_time = 0
[2019-11-09 21:45:52] [ always  ] Setting PHP Option memory_limit = -1
[2019-11-09 21:45:52] [ always  ] Starting UPGRADE Process for v1.2.7
[2019-11-09 21:45:52] [ always  ] No tables where found or selected for conversion
[2019-11-09 21:45:52] [ always  ] Switched from  to /tmp/cdu5tjH52
[2019-11-09 21:45:52] [ always  ] NOTE: Using temporary file for db cache: /tmp/cdu5tjH52
[2019-11-09 21:45:52] [ always  ] Upgrading from v1.2.5 (DB 1.2.7 (DB: 1.2.5)) to v1.2.7
[2019-11-09 21:45:52] [ always  ] Finished UPGRADE Process for v1.2.7

**Comment by cigamit** [comment]
There is definately something wrong with the database.  Same issue as @eschoeller

**Comment by cigamit** [comment]
Per the other thread, send along the device template.

**Comment by bmfmancini** [comment]
Hey @cigamit  you did get my dbexport via email correct ?

**Comment by bmfmancini** [comment]
Hey guys was this resolved ? Just wondering ahead of the 1.2.8 release

**Comment by cigamit** [comment]
Pretty sure this was due to all the form issues.  It has likely corrupted quite a few installs.  If you simply upgrade using the 1.2.x branch are you still getting things messed up?  The reason that it stays at Unknown is that there are no data sources attached to the graphs.  I'll do a fresh install shortly.

**Comment by cigamit** [comment]
With a strait install, I can not reproduce.
