### ISSUE TITLE
1.2.7 from 1.2,x branch Undefined index: local_data_id   /template.php 

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3083]
Hey Guys

I found the following errors on 1.2.7 from the 1.2.x branch 

2019/11/10  20:28:08 - CMDPHP PHP ERROR NOTICE Backtrace:   (/graphs_new.php[41]:form_save(),  /graphs_new.php[149]:html_graph_new_graphs(),  /lib/html_graph.php[447]:host_new_graphs_save(),  /graphs_new.php[243]:create_save_graph(),  /lib/template.php[1643]:CactiErrorHandler())
--
2019/11/10 20:28:08 - ERROR PHP NOTICE: Undefined index:  local_data_id in file: /var/www/html/cacti/lib/template.php  on line:  1643
2019/11/10 20:28:08 - CMDPHP PHP ERROR NOTICE Backtrace:   (/graphs_new.php[41]:form_save(),  /graphs_new.php[149]:html_graph_new_graphs(),  /lib/html_graph.php[447]:host_new_graphs_save(),  /graphs_new.php[243]:create_save_graph(),  /lib/template.php[1643]:CactiErrorHandler())
2019/11/10 20:28:08 - ERROR PHP NOTICE: Undefined index:  local_data_id in file: /var/www/html/cacti/lib/template.php  on line:  1643
2019/11/10 20:28:08 - CMDPHP PHP ERROR NOTICE Backtrace:   (/graphs_new.php[41]:form_save(),  /graphs_new.php[149]:html_graph_new_graphs(),  /lib/html_graph.php[447]:host_new_graphs_save(),  /graphs_new.php[243]:create_save_graph(),  /lib/template.php[1643]:CactiErrorHandler())
2019/11/10 20:28:08 - ERROR PHP NOTICE: Undefined index:  local_data_id in file: /var/www/html/cacti/lib/template.php  on line:  1643
2019/11/10 20:28:08 - CMDPHP PHP ERROR NOTICE Backtrace:   (/graphs_new.php[41]:form_save(),  /graphs_new.php[149]:html_graph_new_graphs(),  /lib/html_graph.php[447]:host_new_graphs_save(),  /graphs_new.php[243]:create_save_graph(),  /lib/template.php[1643]:CactiErrorHandler())
2019/11/10 20:28:08 - ERROR PHP NOTICE: Undefined index:  local_data_id in file: /var/www/html/cacti/lib/template.php  on line:  1643
2019/11/10 20:28:08 - CMDPHP PHP ERROR NOTICE Backtrace:   (/graphs_new.php[41]:form_save(),  /graphs_new.php[149]:html_graph_new_graphs(),  /lib/html_graph.php[447]:host_new_graphs_save(),  /graphs_new.php[243]:create_save_graph(),  /lib/template.php[1643]:CactiErrorHandler())
2019/11/10 20:28:08 - ERROR PHP NOTICE: Undefined index:  local_data_id in file: /var/www/html/cacti/lib/template.php  on line:  1643
2019/11/10 20:28:08 - CMDPHP PHP ERROR NOTICE Backtrace:   (/graphs_new.php[41]:form_save(),  /graphs_new.php[149]:html_graph_new_graphs(),  /lib/html_graph.php[447]:host_new_graphs_save(),  /graphs_new.php[243]:create_save_graph(),  /lib/template.php[1643]:CactiErrorHandler())
2019/11/10 20:28:08 - ERROR PHP NOTICE: Undefined index:  local_data_id in file: /var/www/html/cacti/lib/template.php  on line:  1643

This occours when adding graphs to a cisco device

**Comment by cigamit** [comment]
Can you turn on data source debug and then do the same thing.  Post all the output from the log.

**Comment by bmfmancini** [comment]
Ok funny thing here all of the new devices are showing 0 data sources 

![image](https://user-images.githubusercontent.com/13388748/68556081-c763bb80-03fe-11ea-8c3a-948726c38dbb.png)

**Comment by cigamit** [comment]
What device template are these?  You may need to export it and send it and any resource files that it uses along.

**Comment by bmfmancini** [comment]
Just the default cacti templates

Cisco router and the other one is set to none with a ping graph

**Comment by cigamit** [comment]
Yea, export that and send it my way.  Pretty important.  Suspect it's damaged.  You might want to send database dump to developers at cacti dot net too.  Need to see how bad it is.  This was likely caused by all the form bugs that we introduced in 1.2.6 and 1.2.7.

**Comment by bmfmancini** [comment]
Ok cool sending it your way

**Comment by bmfmancini** [comment]
sent let me know if you need anything else 
I can also try a fresh install if that helps

**Comment by cigamit** [comment]
Try re-importing the templates from a pre-1.2.5 system if you have it.  Otherwise, re-import that package from the install directory.  Then, try a fresh discovery.

**Comment by bmfmancini** [comment]
Ok cool I'll give that a try

**Comment by bmfmancini** [comment]
I am not able to import the templates the error I get is cacti version does not exist

**Comment by bmfmancini** [comment]
![image](https://user-images.githubusercontent.com/13388748/68725648-0a539980-058d-11ea-9071-9cc40c3ea3b2.png)

**Comment by bmfmancini** [comment]
And the template I tried is here 
https://docs.cacti.net/template:package:cisco_router

**Comment by bmfmancini** [comment]
Ironically the cli template seems to think everything is ok 

[root@localhost cli]# php repair_templates.php --execute
NOTE: Repairing All Duplicated Templates
NOTE: Repairing Data Templates
NOTE: No Damaged Data Templates Found
NOTE: Repairing Graph Templates
NOTE: No Damaged Graph Templates Found
[root@localhost cli]#

**Comment by bmfmancini** [comment]
Ok I dropped the DB's and re-created working fine so yea something definetly broke during the upgrade proccess

**Comment by bmfmancini** [comment]
I pulled the 1.2.x branch again all good 

Now this was a upgrade from 1.2.5 not sure if a upgrade from 1.2.6 would also do this

**Comment by TheWitness** [comment]
This whole thing was due to a bug between 1.2.5 -> 1.2.7.  It's corrected in the 1.2.x branch and should be better again after 1.2.8.  Note to others, and a reminder to myself, some old code should never be touched.
