### ISSUE TITLE
It is possible to have the same IP address for the remote and main pollers causing synchronization issues

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3085]
Hey Guys 

I just came across a scenario we might want to check for
On my remote poller lab I mistakenly entered the main poller Ip as the remote DB ip on the remote poller 

This led to devices going bye bye when syncing the pollers see below 

![vanish devices](https://user-images.githubusercontent.com/13388748/68555676-de091300-03fc-11ea-84a9-cdab19afd720.gif)

My Lab is setup as following 

192.168.1.227 is the main poller
192.168.1.228 is the remote 

below I had entered 192.168.1.227 as the remote DB and as you can see above this caused the device to disappear this could be very bad in production 

![image](https://user-images.githubusercontent.com/13388748/68555689-f0834c80-03fc-11ea-9a99-0996f8bdcee0.png)

**Comment by cigamit** [comment]
Oh, good catch.  That makes the other issue kind of less daunting.

**Comment by cigamit** [comment]
Okay, this is fixed now.  Thanks for reporting!
