### ISSUE TITLE
Cacti 1.2.7 - Graph zooming error

### ISSUE THREAD

**Issue by DavidLiedke** [Cacti/cacti#3088]
**To Reproduce**
1. Click on "Time Graph View" of one graph
2. Then click "Graph Details, Zooming, Debugging Utilities"
3. Zoom in the graph

**Screenshots**
1. 
![2019-11-11_08-34-17](https://user-images.githubusercontent.com/25581728/68569908-9f587480-045f-11ea-8393-f2ca6ccfa245.gif)

2. 
![2019-11-11_08-43-15](https://user-images.githubusercontent.com/25581728/68569916-a3849200-045f-11ea-99fb-325ceb780e4f.gif)

3. 
![Unbenannt](https://user-images.githubusercontent.com/25581728/68569931-ac756380-045f-11ea-9414-54df5e6affd1.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 70.0.1

**Comment by cigamit** [comment]
Please try with branches 1.2.x.

**Comment by netniV** [comment]
David is normally pretty current, I haven't had time to test this out myself on Firefox.

**Comment by cigamit** [comment]
@netniV, I am unable to reproduce this on 1.2.x.

**Comment by netniV** [comment]
Could this be related to the #3112?

**Comment by cigamit** [comment]
Maybe, @DavidLiedke, please see if it's reproducible now.  Thanks!

**Comment by cigamit** [comment]
It's likely related to #3029 too.
