### ISSUE TITLE
Show "Save successful" notification permanently

### ISSUE THREAD

**Issue by Weppel** [Cacti/cacti#309]
When doing large amounts of quickly repeated Cacti update/modifications in the GUI the notification bar at the top after an action has finished is very annoying because it disappears after X amount of seconds.

The result of this is that it's possible (and has happened to me countless times) that right when I want to click something the entire screen moves up a bit because of the disappearing notification bar. 

My suggestion would be to either remove this disappearing function entirely or make it optional on a per-user basis.

**Comment by cigamit** [comment]
Agree.

**Comment by camerabob** [comment]
Perhaps pop up (toast like) from the bottom of the screen. Similar to the device reachable stats when saving a device. It scrolls the entire screen down a bit after the entire screen loads with the results. +1

**Comment by cigamit** [comment]
I was thinking of the same thing, to place some note at the bottom of the screen.  My schedule has not permitted me any quality time with the code lately.  A pull request would be appreciated.

**Comment by cigamit** [comment]
I've resolved it.  If you can come up with something better.  Please create a pull request and we will evaluated it.
