### ISSUE TITLE
No OID number in log messages

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#3090]
`2019/11/11 23:35:11 - SPINE: Poller[Main Poller] Device[HOSTNAMEDELETED] ERROR: Problems parsing Multi SNMP OID! (oid: ), Set MAX_OIDS to 1 for this host to isolate bad OID`

**There is:**
"(oid: )" in log message. 

**Should be:**
(oid: oid.number1, oid.number2, oid.number3) or no "(oid:) in error message.

**Comment by cigamit** [comment]
Well that is odd.  Please open in the spine issue tracker.
