### ISSUE TITLE
SNMP Information on device host - add firmware version

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#3091]
**Describe the solution you'd like**
Please add `Firmware version` or `Software Version` whitch is avaiable by SNMP in `host.php?action=edit` in header information. The information could be also available in host.php in hosts list in last column. 

**Additional context**
This is major informartion about device. It could be used in many ways. Creating the sorting of newly created column could be also helpful to find all the devices with older (mostly buggy) firmwares.

**Comment by netniV** [comment]
There is no guarantee that a device offers that information as far as I was aware but if others think it would be worth it that could be a future enhancement.

**Comment by TheWitness** [comment]
I would suggest something like a rule that can pull that information from an OID on a device template specific setting.  I think I did this in the MacTrack plugin before being swept away from the Networking vertical by Platform Computing over a decade ago.  No reason it could not be in a device template in a modern Cacti.  Having a serial number column might not be bad.  Many network switches though have multiple modules, each with their own serial numbers.  So, this might get a bit more complicated.

**Comment by bmfmancini** [comment]
This would be awesome to have a Colum to collect something like serial number and it would be up to the user to put in the oid of the serial they wanted ie chassis serial etc would be helpful for inventory purposes

**Comment by cigamit** [comment]
This sounds like something that the hmib plugin could do, but it would be highly dependent on device type.

**Comment by xmacan** [comment]
I have tried it before, I will prepare small example with few OS types and serial numbers

**Comment by xmacan** [comment]
I have prepared small plugin. For now plugin supports only few vendors mikrotik/synology/3com/h3c, ... and only few informations.
It does not depend on device/template. It obtains information from snmp by IANA organization numbers
https://github.com/xmacan/plugin_snver

**Comment by TheWitness** [comment]
I was working on the Synology NAS Device Package, and it might be beneficial to add this attribute to the Device Template.  Just keeping that in the pipeline.  Could use the `|host_blah|` variables to display that information on a Graph for example too.

**Comment by TheWitness** [comment]
This is been achieved using the new evidence plug in so I think we can close this and Mark it as completed.
