### ISSUE TITLE
New Remote Poller Error

### ISSUE THREAD

**Issue by whsir** [Cacti/cacti#3093]
create New Remote Poller

cacti version 1.2.2 succeed
cacti version 1.2.3、1.2.4、1.2.5、1.2.6、1.2.7 All error

![image](https://user-images.githubusercontent.com/46343402/68740643-8352ff80-0626-11ea-8292-086e4100ce38.png)

**Comment by whsir** [comment]
OS：Centos7.6
LEMP：php5.6.40、mysql5.7.28
nginx、php，no error log
Chrome78，clear cache

**Comment by whsir** [comment]
Cacti version = 1.2.2 No problem
Cacti version > 1.2.2  Error: 200 OK

**Comment by whsir** [comment]
![image](https://user-images.githubusercontent.com/46343402/68741540-db8b0100-0628-11ea-8f3b-7b37567f7cd1.png)

**Comment by netniV** [comment]
Unfortunately, none of this is helpful apart from your have a problem with the test connection during the installer.  The reasons being:

- You've specified multiple versions which conflict with the images, please be clear what version you are using and have a problem with.  You should also state were you sourced this from.

- The post data is missing as you only have the access log rather than the full request and response.

The likelihood is that if you check your PHP/Apache/Cacti logs, you'll find an error or warning being generated and that is interfering with the json output since the warning would break it.

**Comment by whsir** [comment]
I tested multiple versions.
> 1.2.2 version Same mistake

**Comment by whsir** [comment]
download
https://codeload.github.com/Cacti/cacti/tar.gz/release/1.2.3
https://codeload.github.com/Cacti/cacti/tar.gz/release/1.2.4
https://codeload.github.com/Cacti/cacti/tar.gz/release/1.2.5
https://codeload.github.com/Cacti/cacti/tar.gz/release/1.2.6
https://codeload.github.com/Cacti/cacti/tar.gz/release/1.2.7

**Comment by whsir** [comment]
Sorry, I can't see any warnings or error logs

**Comment by whsir** [comment]
php-fpm.conf
![image](https://user-images.githubusercontent.com/46343402/68742700-cd8aaf80-062b-11ea-83e3-9ed8c471a347.png)
![image](https://user-images.githubusercontent.com/46343402/68742729-d8454480-062b-11ea-891a-244314db13ed.png)

**Comment by whsir** [comment]
![image](https://user-images.githubusercontent.com/46343402/68742797-0165d500-062c-11ea-9636-8dd7d564fb1f.png)

**Comment by bmfmancini** [comment]
Try cleaning your cookies and cache if you haven't already tried that

**Comment by whsir** [comment]
@bmfmancini The cache has been cleaned,

**Comment by whsir** [comment]
init OS
Respectively installed New Remote Poller.
Only version 1.2.2 No problem.
< 1.2.2 No test
> 1.2.2 test error As shown in figure ,Error content identical

**Comment by whsir** [comment]
![image](https://user-images.githubusercontent.com/46343402/68743583-c1075680-062d-11ea-8c74-63c67bea3751.png)

**Comment by whsir** [comment]
Nginx open debug log：
![image](https://user-images.githubusercontent.com/46343402/68748541-96ba9680-0637-11ea-9722-b2a18a18e1b5.png)

php open debug log：
![image](https://user-images.githubusercontent.com/46343402/68748597-a3d78580-0637-11ea-8ccf-6e62db115ac5.png)

**Comment by netniV** [comment]
> The post data is missing as you only have the access log rather than the full request and response.
I'll reiterate this as all of the comments in between haven't really changed anything.  Need to see the response back to the browser and preferably the request being sent including the data.

**Comment by whsir** [comment]
![image](https://user-images.githubusercontent.com/46343402/68817290-3cafe480-06bc-11ea-9c4e-fce68967be01.png)

**Comment by whsir** [comment]
Everything seems normal, but the browser doesn't jump

**Comment by whsir** [comment]
firefox
![image](https://user-images.githubusercontent.com/46343402/68818734-dda09e80-06c0-11ea-9409-30012391ef54.png)

**Comment by netniV** [comment]
As I suspected the JSON is being malformatted, can you provide the raw output rather than the parsed output?

**Comment by whsir** [comment]
sudo -u www php /data/www/cacti/install/cli_check.php extensions
`{"sockets":{"cli":true,"web":false},"simplexml":{"cli":true,"web":false},"session":{"cli":true,"web":false},"pdo_mysql":{"cli":true,"web":false},"spl":{"cli":true,"web":false},"standard":{"cli":true,"web":false},"posix":{"cli":true,"web":false},"zlib":{"cli":true,"web":false},"xml":{"cli":true,"web":false},"PDO":{"cli":true,"web":false},"pcre":{"cli":true,"web":false},"gmp":{"cli":true,"web":false},"gd":{"cli":true,"web":false},"filter":{"cli":true,"web":false},"date":{"cli":true,"web":false},"hash":{"cli":true,"web":false},"json":{"cli":true,"web":false},"openssl":{"cli":true,"web":false},"mbstring":{"cli":true,"web":false},"ldap":{"cli":true,"web":false},"ctype":{"cli":true,"web":false}}`

**Comment by whsir** [comment]
I think it has to do with this parameter

![image](https://user-images.githubusercontent.com/46343402/68912175-53c10600-0792-11ea-925f-6b49b1d32c97.png)

**Comment by whsir** [comment]
I added this parameter in 1.2.7
`$config['poller_id'] == 1 &&`
![image](https://user-images.githubusercontent.com/46343402/68912323-d0ec7b00-0792-11ea-8ce3-db41a9a46b17.png)

**Comment by netniV** [comment]
That parameter merely checks that you are running an upgrade on your main server rather than remote poller.  It has nothing to do with the JSON that is being returned.  We need the JSON that the browser is seeing rather than the command line output.

**Comment by whsir** [comment]
Sorry, I don't understand

**Comment by netniV** [comment]
Your browser, for some reason, tried to interpret the JSON which it didn't like.  We need the unformatted version from your browser.

**Comment by whsir** [comment]
`{
"Mode": "2",
"Step": "3",
"Errors": {
"Paths": {
"path_rrdtool": "File not found",
"path_snmpwalk": "File not found",
"path_snmpget": "File not found",
"path_snmpbulkwalk": "File not found",
"path_snmpgetnext": "File not found",
"path_snmptrap": "File not found"
}
},
"Eula": "1",
"Prev": {
"Text": "Previous",
"Step": 2,
"Enabled": true,
"Visible": true
},
"Next": {
"Text": "Next",
"Step": 4,
"Enabled": false,
"Visible": true
},
"Test": {
"Text": "Test Connection",
"Step": -4,
"Enabled": true,
"Visible": true
},
"Theme": "modern",
"StepData": {
"Sections": {
"connection_local": 1,
"connection_remote": 1,
"error_file": false,
"error_poller": false,
"poller_vars": 0,
"poller_steps": 1
}
},
"Html": "<h2 class='cactiInstallSectionTitle'>Installation Type</h2><h3 class='cactiInstallSectionTitle'>Please select the type of installation</h3><div class=\"installSubSection\"><p class='cactiInstallSection cactiInstallSectionNormal'>Installation options:</p><p class='cactiInstallSection cactiInstallSectionNormal'><ul><li><b><i>New Primary Server</i></b> - Choose this for the Primary site.</li><li><b><i>New Remote Poller</i></b> - Remote Pollers are used to access networks that are not readily accessible to the Primary site.</li></ul></p><p class='cactiInstallSection cactiInstallSectionNormal'><select id=\"install_type\" name=\"install_type\"><option value=\"1\">New Primary Server</option><option value=\"2\" selected>New Remote Poller</option></select></p><p class='cactiInstallSection cactiInstallSectionNormal'>The following information has been determined from Cacti's configuration file. If it is not correct, please edit \"include/config.php\" before continuing.</p></div><h3 class='cactiInstallSectionTitle' id='connection_local'>Local Database Connection Information</h3><div class=\"installSubSection\"><p class='cactiInstallSection cactiInstallSectionCode'>Database: <b>cacti</b><br>Database User: <b>cacti</b><br>Database Hostname: <b>localhost</b><br>Port: <b>3306</b><br>Server Operating System Type: <b>unix</b><br></p></div><h3 class='cactiInstallSectionTitle' id='connection_remote'>Central Database Connection Information</h3><div class=\"installSubSection\"><p class='cactiInstallSection cactiInstallSectionCode'>Database: <b>cacti</b><br>Database User: <b>cacti</b><br>Database Hostname: <b>192.168.1.140</b><br>Port: <b>3306</b><br>Server Operating System Type: <b>unix</b><br></p></div><h3 class='cactiInstallSectionTitle' id='error_file'>Configuration Readonly!</h3><div class=\"installSubSection\"><p class='cactiInstallSection cactiInstallSectionNormal'><span class=\"textError\"><strong>ERROR:</strong> Your config.php file must be writable by the web server during install in order to configure the Remote poller.  Once installation is complete, you must set this file to Read Only to prevent possible security issues.</span></p></div><h3 class='cactiInstallSectionTitle' id='error_poller'>Configuration of Poller</h3><div class=\"installSubSection\"><p class='cactiInstallSection cactiInstallSectionNormal' id='config_remote'><span class=\"textError\"><strong>ERROR:</strong> Your Remote Cacti Poller information has not been included in your config.php file.  Please review the config.php.dist, and set the variables: <i>$rdatabase_default, $rdatabase_username</i>, etc.  These variables must be set and point back to your Primary Cacti database server.  Correct this and try again.</span></p></div><h3 class='cactiInstallSectionTitle' id='poller_vars'>Remote Poller Variables</h3><div class=\"installSubSection\"><p class='cactiInstallSection cactiInstallSectionNormal'>The variables that must be set in the config.php file include the following:</p><p class='cactiInstallSection cactiInstallSectionCode'>$rdatabase_type     = 'mysql';<br>$rdatabase_default  = 'cacti';<br>$rdatabase_hostname = 'cacti.example.com'; // Central Cacti server.<br>$rdatabase_username = 'cactiuser';<br>$rdatabase_password = 'cactiuser';<br>$rdatabase_port     = '3306';<br>$rdatabase_ssl      = false;<br></p><p class='cactiInstallSection cactiInstallSectionNormal' id='config_remote_poller'>The Installer automatically assigns a $poller_id and adds it to the config.php file.</p><p class='cactiInstallSection cactiInstallSectionNormal' id='config_remote_var'>Once the variables are all set in the config.php file, you must also grant the $rdatabase_username access to the main Cacti database server.  Follow the same procedure you would with any other Cacti install.  You may then press the 'Test Connection' button.  If the test is successful you will be able to proceed and complete the install.</p></div><h3 class='cactiInstallSectionTitle' id='poller_steps'>Additional Steps After Installation</h3><div class=\"installSubSection\"><p class='cactiInstallSection cactiInstallSectionNormal' id='config_remote_db'>It is essential that the Central Cacti server can communicate via MySQL to each remote Cacti database server.  Once the install is complete, you must edit the Remote Data Collector and ensure the settings are correct.  You can verify using the 'Test Connection' when editing the Remote Data Collector.</p></div>"
}`

**Comment by whsir** [comment]
{
	data[step]:-4,
	__csrf_magic:sid:f4220c01d91e62b85d8429b302f601f21279e8d1,1573807290
}

**Comment by netniV** [comment]
Is that -4 for the step? A negative number usually means special function ... let me check that, but you received no response ? So that's weird as you should always get something.

**Comment by netniV** [comment]
OK, yeah so that's right, -4 is the function defined as STEP_TEST_REMOTE.  Now there's a small piece of JavaScript that tests the connection by passing that value which `step_json.php` then interprets:

```php
if (isset($initialData['step']) && $initialData['step'] == Installer::STEP_TEST_REMOTE) {
        $json = install_test_remote_database_connection();
        $json_debug = $json;
```

Now, `install_test_remote_database_connection` always returns that json value if it receives it:

```php
        if (is_object($connection)) {
                db_close($connection);
                print json_encode(array('status' => 'true'));
        } else {
                print json_encode(array('status' => 'false'));
        }
```

The only bug I have spotted when viewing this is that the json_debug option only takes effect for the normal steps not the test connection one.  I would also have coded that bit slightly differently and have the installer class handle it but it's more speed efficient this way.

**Comment by netniV** [comment]
So, if you get to that step within the installer, set `log_install` in the `Settings` table to 5, then hit test connection.  After the dialog 200 appears, remove that setting from the table.

You should now have an install-json.log in the logs folder and that should have the values being sent in/out.

**Comment by whsir** [comment]
set log_install in the Settings table to 5 ?
Sorry, I don't understand

**Comment by netniV** [comment]
> set log_install in the Settings table to 5 ?
Within MySQL add an entry to the settings table.

**Comment by whsir** [comment]
Please tell me which entry? Please tell me which table? 
Thanks!

**Comment by netniV** [comment]
I already have twice.

**Comment by whsir** [comment]
本来国际上沟通就不流畅，就不能说的详细下吗？1、2、3、。。。
算了，我放弃了，反正也是“佛系”解决问题
谢谢

**Comment by netniV** [comment]
OK, fair enough. Still believe this to be a localised issue with your setup.

**Comment by whsir** [comment]
@netniV 
I think I suddenly understand what you mean!
Edit "settings" table
add
name：log_install
value：5
cat cacti/log/install-json.log
[2019-11-20 10:52:03] [ debug   ] Using supplied data
[2019-11-20 10:52:03] [ notice  ] Start: {"step":"-4"}

**Comment by whsir** [comment]
![image](https://user-images.githubusercontent.com/46343402/69205801-f6f48f80-0b85-11ea-9fe7-86545da9dbd1.png)

**Comment by netniV** [comment]
You can remove the setting and the other install-*.log files now.  When you visit https://<cacti>/install/step_json.php?step=-4 you have the same output ?

**Comment by whsir** [comment]
1、del sql "settings"
2、rm -f cacti/log/*
3、curl URL
http://192.168.1.162/cacti//install/step_json.php?step=-4

{"status":"500","statusText":"\u672a\u767b\u5f55","responseText":"\u60a8\u5fc5\u987b\u5148\u767b\u5f55\u624d\u80fd\u8bbf\u95ee\u8be5\u533a\u57df\u7684Cacti."}

**Comment by whsir** [comment]
![image](https://user-images.githubusercontent.com/46343402/69219853-b78e6900-0bae-11ea-981b-41b9d0d8fc87.png)

**Comment by whsir** [comment]
It looks the same

**Comment by whsir** [comment]
It looks the same

**Comment by netniV** [comment]
That last curl is for mode 2, step 3, not -4

**Comment by whsir** [comment]
nginx→apache
test succeed

Can you verify nginx？I think the problem might be nginx！

**Comment by netniV** [comment]
Shouldn't be as we run nginx on our internal cacti server and that installation went OK.  So to be clear, the test connection is successfully, it's when you go to the next step you have an issue?

**Comment by whsir** [comment]
I was successful with apache！But use Nginx Still failed！
Same way, but different environment, I don't know why nginx faild！

**Comment by whsir** [comment]
init centos7
yum install epel-release
yum install nginx php php-mysql php-fpm mariadb-server mariadb php-gd ......
edit php mysql nginx 
edit cacti/include/config.php
curl URL
Test Connection
![image](https://user-images.githubusercontent.com/46343402/69320229-b9722e00-0c7b-11ea-85e8-b76a757e8468.png)

**Comment by whsir** [comment]
<iframe width="560" height="315" src="https://www.youtube.com/embed/0gSjScpfZ64" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

**Comment by whsir** [comment]
yum install epel-release
yum install nginx wget
vim /etc/nginx/conf.d/default.conf
server {
    listen       80;
    server_name  192.168.1.139;

    root   /usr/share/nginx/html;
    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ =404;
    }
    error_page 404 /404.html;
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass unix:/var/run/php-fpm/php-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
systemctl start nginx

yum install rrdtool net-snmp php php-mysql php-fpm
yum install php-gd php-ldap php-mbstring php-posix
vim /etc/php-fpm.d/www.conf
listen.owner = nobody
listen.group = nobody
user = nginx
group = nginx
listen = /var/run/php-fpm/php-fpm.sock
vim /etc/php.ini
date.timezone = Asia/Shanghai
systemctl start php-fpm


yum install mariadb-server mariadb
systemctl start mariadb
echo -e "\nn\ny\ny\ny\ny" | mysql_secure_installation
mysql -uroot -p
mysql> set password = password('whsir');
mysql> CREATE DATABASE cacti DEFAULT CHARACTER SET utf8;
mysql> GRANT ALL ON cacti.* TO cacti@localhost IDENTIFIED BY 'blog.whsir.com';
mysql> GRANT SELECT ON mysql.time_zone_name TO cacti@localhost IDENTIFIED BY 'blog.whsir.com';
mysql> ALTER DATABASE cacti CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
mysql> flush privileges;
mysql> quit
mysql_tzinfo_to_sql /usr/share/zoneinfo/ | mysql -uroot -pwhsir mysql


cd /usr/share/nginx/html
wget https://github.com/Cacti/cacti/archive/release/1.2.7.tar.gz
mysql -uroot -pwhsir cacti < cacti/cacti.sql

touch /usr/share/nginx/html/cacti/log/cacti.log
chmod 777 /usr/share/nginx/html/cacti/log/cacti.log
chmod 777 /usr/share/nginx/html/cacti/include/config.php
cp config.php.dist config.php
vim config.php

**Comment by whsir** [comment]
I want you to verify that!
Thaks

**Comment by whsir** [comment]
![image](https://user-images.githubusercontent.com/46343402/69328812-e417b300-0c8a-11ea-845b-9af2c70fe8dc.png)

**Comment by netniV** [comment]
Thank you for the extra information.  Unfortunately, it's going to be a few days before I have spare time to put a VM together to test all this.  One thing you left off was the OS version you are running?

**Comment by whsir** [comment]
new Centos7.6
It's mentioned in my recorded video！
Thank you for taking the time to test！

**Comment by cigamit** [comment]
Have you tested branch 1.2.x?

**Comment by cigamit** [comment]
We will test prior to release.

**Comment by whsir** [comment]
@cigamit 
I tested 1.2.x with the same problem.
![image](https://user-images.githubusercontent.com/46343402/69686448-ca4af580-10fa-11ea-9656-a543f3674b4b.png)
Be sure to test with the LEMP environment！
LAMP testing no problem！
https://github.com/Cacti/cacti/issues/3093#issuecomment-557014396
https://github.com/Cacti/cacti/issues/3093#issuecomment-557014929

**Comment by cigamit** [comment]
I think this will be resolved post 1.2.8.  The main data collector now performs a full sync at the time of upgrade.  So, you simply need to ensure that your remote data collectors are up at the time of upgrading.

**Comment by whsir** [comment]
@cigamit 
![image](https://user-images.githubusercontent.com/46343402/70607684-de820d00-1c39-11ea-8647-8c1e3d2cb2e2.png)

**Comment by whsir** [comment]
@netniV I verified again and the problem was not solved

**Comment by TheWitness** [comment]
Is this a Cacti problem or an environment problem.  I've been installing Data Collectors without issue on CentOS7.

**Comment by TheWitness** [comment]
@whsir, After the release of 1.2.11, please retest this.  I still think it's an environment issue though.

**Comment by whsir** [comment]
@TheWitness 
Please try with LEMP environment！！！
There is no problem using LAMP！！！
