### ISSUE TITLE
The vertical_label unit kilobytes is wrong on graph template 'Linux - Memory Usage' 

### ISSUE THREAD

**Issue by YongBoLiu** [Cacti/cacti#3099]
**Describe the bug**
The vertical_label unit kilobytes is wrong on graph template 'Linux - Memory Usage' . It should be Bytes.
When my Linux cacti server has 23G memory free.  The graph shows 23G, which is OK. But the vertical lable show kilobytes. It's wrong, should be Bytes.

**To Reproduce**
1. Go to Console->graphs.
2. Click on the Local Linux Machine - Memory Usage graph.
3. Check the vertical lable on the graph.

**Expected behavior**
Change the kilobytes to Bytes.

**Screenshots**

**Desktop (please complete the following information):**
Linux

**Smartphone (please complete the following information):**

**Additional context**

The script (#perl cacti/scripts/linux_memory.pl) returns value in KB, and the graph item use 'Multiply by 1024'. So, the value result in Bytes.

The file  Local_Linux_Machine.xml seems be encoded, after gzip the cacti/install/templates/Local_Linux_Machine.xml.gz.

**Comment by YongBoLiu** [comment]
![unit_wrong](https://user-images.githubusercontent.com/12453888/69221064-59af5080-0bb1-11ea-8221-fe5d0e285691.jpg)

**Comment by netniV** [comment]
So, one of two things is wrong then, either the label should become bytes or the values should have been divided by 1024 but are not... Not sure if @cigamit changed that in the last year or not without searching which I can't do right now.

**Comment by YongBoLiu** [comment]
@netniV I prefer to change the label to bytes, because this makes the value more straightforward. Otherwise, we may get the value, 3G as shown 3M of KB. Thanks.

**Comment by netniV** [comment]
Yeah I can agree with that.

**Comment by cigamit** [comment]
This is resolved now with the updated Local Linux Machine package.

**Comment by netniV** [comment]
One thing is that we may need to make the installer allow re-installation of packages

**Comment by cigamit** [comment]
We really need a 'Package' option on the Import/Export page as well, one that can install packages from a local file system, or directly download and install them from GitHub.  But instead of making a new option, we just allow them to specify package or template on the import export picks.
