### ISSUE TITLE
Can't delete datasource - Bug

### ISSUE THREAD

**Issue by mikygee** [Cacti/cacti#3100]
Version: 1.2.7

Helllo,

It's impossible to delete a datasource.
Management > Datasource
Select the datasource
Select Delete
=> The selected datasource gets unchecked and all datasources get greyed.

The Disable function works whereas the Delete doesn't.

Regards

**Comment by rtripon** [comment]
Hello,
I know for sure that you cant delete datasources that are in use. Maybe you have graphs that are using those datasources and untill graphs exists, you cant delete them.

**Comment by mikygee** [comment]
Hello,
Thank you for your answer but in Cacti before 1.0 that was not the behavior.
It was asking if I wanted to delete the graphs as well.
Do the test on your cacti, this behavior is not normal: select a datasource, choose delete and then it's unselected.
Regards

**Comment by netniV** [comment]
There is a column that states if a datasource can be removed, and if it cannot, no matter how many times you select it, it will be deselected. @rtripon is correct in what he is saying.

**Comment by TheWitness** [comment]
This generally means that the data source is in use, and therefore it can not be deleted until the graph that uses it has been deleted.
