### ISSUE TITLE
Poller.php polling... too fast?!

### ISSUE THREAD

**Issue by lbsou** [Cacti/cacti#3101]
Hi!

This morning, I posted a spine issue, but since then, I realised it was probably more a poller.php bug.

https://github.com/Cacti/spine/issues/123

Hi!

**Describe the bug**

Just installed a brand new cacti. I added all my devices (1400+) and it is now polling.

It is configured to poll every 10seconds with poller.php called every minute by crontab.

/etc/cron.d/cacti
*/1 * * * * root php /usr/share/cacti-1.2.7/poller.php > /dev/null 2>&1

![image](https://user-images.githubusercontent.com/30626084/69425501-02b49300-0cf9-11ea-8459-f92644a96fb0.png)

The problem is that instead of the 10seconds intervals, it happen in 8 seconds and sleep at the end of the 6 polling sequence. (see screenshot)

**To Reproduce**
Configure same parameter as I did I suppose...

**Expected behavior**
As you can see in my other screenshot of my current production server, the interval are 10seconds.

**Screenshots**

![image](https://user-images.githubusercontent.com/30626084/69425193-7ace8900-0cf8-11ea-9953-1aa97ff40d16.png)

For comparison, here is the CPU stats from my other server 0.8.8g

![image](https://user-images.githubusercontent.com/30626084/69425598-3e4f5d00-0cf9-11ea-8f54-6f46be6ccfe8.png)

**Server (please complete the following information):**
Cacti 1.2.7 
Spine 1.2.7
RedHat 8.1
PHP 7.3.12

**Compiling (please complete the following information):**

 - compiler: gcc 8.3.1-4.5
 - autoconf: 2.69-27
 - glibc: 2.28-72
 - source: https://www.cacti.net/downloads/cacti-1.2.7.tar.gz

**Comment by bmfmancini** [comment]
Sounds like something on RHEL more than on spine  since cron would be the mechanisim that would initiate spine 

try this create  a small script that echos the time to a text file and have it run at the same time restart the crond service to be sure it syncs up and compare if the echo and spine behave the same

**Comment by lbsou** [comment]
/var/log/cron show that poller.php is launch by crontab exactly every minutes.

**Comment by TheWitness** [comment]
Man, 10 seconds with 1400 devices.  Must be a big box.  I would suggest that this is a small issue in poller.php.

**Comment by TheWitness** [comment]
Hmm, seems a counter issue inside of poller.php.  It should record the start time, and the end time, take the difference between that and the start of the next poll, and then sleep for that amount of time.

**Comment by lbsou** [comment]
Ok, that's what I tought.

FYI, running on a 20 x XeonE7-4850 v4 @ 2.10GHz
@+!

**Comment by TheWitness** [comment]
Yea, that's a beast.

**Comment by cigamit** [comment]
Update your poller.php from branch 1.2.x and report back.

**Comment by lbsou** [comment]
Yep, back to normal!
