### ISSUE TITLE
spine bad performance

### ISSUE THREAD

**Issue by Justmfree** [Cacti/cacti#3102]
i have spine 1 minute polling and i think i have performance issue...
my average system stat is :

11/24/2019 08:12:46 PM - SYSTEM STATS: Time:44.5115 Method:spine Processes:10 Threads:15 Hosts:415 HostsPerProcess:42 DataSources:73694 RRDsProcessed:37945
11/24/2019 08:12:30 PM - WEATHERMAP: Poller[0] STATS: Weathermap 0.98 run complete - Sun, 24 Nov 19 20:12:30 +0400: 13 maps were run in 29 seconds with 37 warnings.
11/24/2019 08:11:48 PM - SYSTEM STATS: Time:45.6564 Method:spine Processes:10 Threads:15 Hosts:415 HostsPerProcess:42 DataSources:73694 RRDsProcessed:37945
11/24/2019 08:11:29 PM - WEATHERMAP: Poller[0] STATS: Weathermap 0.98 run complete - Sun, 24 Nov 19 20:11:29 +0400: 13 maps were run in 27 seconds with 34 warnings.
11/24/2019 08:10:46 PM - SYSTEM STATS: Time:44.5574 Method:spine Processes:10 Threads:15 Hosts:415 HostsPerProcess:42 DataSources:73695 RRDsProcessed:37946
11/24/2019 08:10:27 PM - WEATHERMAP: Poller[0] STATS: Weathermap 0.98 run complete - Sun, 24 Nov 19 20:10:27 +0400: 13 maps were run in 25 seconds with 36 warnings.
11/24/2019 08:09:46 PM - SYSTEM STATS: Time:44.7725 Method:spine Processes:10 Threads:15 Hosts:415 HostsPerProcess:42 DataSources:73695 RRDsProcessed:37946
11/24/2019 08:09:35 PM - WEATHERMAP: Poller[0] STATS: Weathermap 0.98 run complete - Sun, 24 Nov 19 20:09:35 +0400: 13 maps were run in 34 seconds with 36 warnings.

but sometimes is :

11/24/2019 11:37:01 AM - SYSTEM STATS: Time:58.8380 Method:spine Processes:10 Threads:15 Hosts:415 HostsPerProcess:42 DataSources:73694 RRDsProcessed:37945

Accordingly after such time result ,there are errors in log:
11/24/2019 11:22:11 AM - PHPSVR: Poller[0] ERROR: Input Expected, Script Server Terminating
11/24/2019 11:22:11 AM - SPINE: Poller[0] FATAL: Connection Failed, Error:'2002', Message:'Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (11)' (Spine thread)

there are my spine settings:

Maximum Concurrent Poller Processes : 10
Maximum Threads per Process : 15
Number of PHP Script Servers : 2
Script and Script Server Timeout Value : 500
The Maximum SNMP OID's Per SNMP Get Request: 15
VM machine: 
25GB RAM
SSD  
20 CPUs core xeon.
system stat time was about 30-40 sec but yesterday this time grew up without reason...
so, is there something to check or change to fix this issue ?
i tried to change poller settings but without any success...

**Comment by lbsou** [comment]
Can you check in Cacti, in the "devices" menu, the columns "Poll time/Current/Average" and see if there is any big number there?

**Comment by Justmfree** [comment]
yes of course 
top:
Average (ms)**

69.24
67.3
67.02
66.27
65.83
64.96
64.35
62.28
60.52

Top:
Current (ms)**

1682.21
174.74
97.13
95.67
92.84
87.27
83.42
73.68
71.84
67.63
67.23
64.27
60.72

**Comment by lbsou** [comment]
How many concurrent session configured on mysql?

/etc/my.cnf

max_connections = ?

**Comment by Justmfree** [comment]
'max_connections';
+-----------------+-------+
| Variable_name   | Value |
+-----------------+-------+
| max_connections | 800   |
+-----------------+-------+


'max_used_connections';
+----------------------+-------+
| Variable_name        | Value |
+----------------------+-------+
| Max_used_connections | 366   |
+----------------------+-------+

**Comment by TheWitness** [comment]
This is likely due to two things: 

1) too many concurrent processes, 
2) lack of using boost.

Issue 2) is more than likely the big issue.  This should have been addressed on the forums as this is not a issue with the tool.

A few easy ways to check if boost is required is to:

1) Run "du -hs <path_cacti>/rra", if the number is larger than the amount of free disk cache (via top), you must run boost.
2) If the total amount of memory on the system is less than the output of the command above.
3) Output of "cat /proc/cpuinfo | grep processor | wc -l" is less than 4 x processes x threads.  So, in your case, you have 10 * 15, so you would need more than ~38 from the command above on the server to keep up.  Remember that the database needs threads too.  So, 4x is pretty aggressive.

**Comment by Justmfree** [comment]
thanks i will check it tomorrow...

**Comment by Justmfree** [comment]
i checked now please see outputs:

1) 4.4G    rra/
2) top result: see pic..
3) cat /proc/cpuinfo | grep processor | wc -l result : 22
so do i need to change poller settings ? 
![top](https://user-images.githubusercontent.com/13820959/69653961-6ccc8f80-108d-11ea-9ea3-78359165ef18.jpg)

**Comment by TheWitness** [comment]
Just use boost.  That will get you out of trouble for now.  You should also consider reducing your innodb_buffer_pool_size to something like 8G in /etc/my.cnf.d/server.cnf since you seem to only be using about 3.5GB of MariaDB memory.  Also, reduce the number of innodb_buffer_pool_instances to something like 8, no more.  A MariaDB restart is required to change both those settings.

If in the future, you start running plugins that hold a lot of data, you should re-review these settings to see if they still make sense.

**Comment by Justmfree** [comment]
my cacti database Engine is MYISAM :) so what do you have suggestions To respond  these challenges ?

**Comment by netniV** [comment]
You should be using Barracuda and InnoDB for best performance as far as I am aware.

**Comment by TheWitness** [comment]
Right, goto Utilities > System Utilities > Technical Support and check the Database recommendations.  Make the changes, and then run the cli script:

```command
php -q convert_tables.php  --innodb --utf8
```

That'll move things to InnoDB, which is our current recommendation which includes Barracuda, large_prefix, etc.

**Comment by TheWitness** [comment]
Boost is a no brainer though, you should not fear it other than to ensure that the RRDfiles are owned by the web server, and cron runs as the web server account as well.

**Comment by Justmfree** [comment]
Server is Under the spotlight now there is no error at this moment system stat time is about 44 second.
without error later if issues comes again i will check again. thanks

**Comment by cigamit** [comment]
The difference between OSS, and Operations is always a bitch.  A simple change to change engines, when faced with the scrutiny of Operations Management, though a simple change, brings huge exposure.

My recommendation, change control first with a backup before hand, or the ability to roll back the changes.  Be well, and Happy T'Giving!
