### ISSUE TITLE
Cacti 1.2.6 and custom script problem

### ISSUE THREAD

**Issue by GeneralFox** [Cacti/cacti#3103]
In cacti 1.2.6 running under CentOS 7.7.1908 I was not able to pass a variable to a custom script.
I have configured the path/to/scrip <argument_to_pass> in the Input String of Data Input Methods, saved but then under the "Input Fields" the dropbox Field [|arg1:|] is void and I was not able to save the input fields.

I've also tried to build another Data Input Source but with the same results.

**Comment by cigamit** [comment]
This is a bug in 1.2.7.  Download the branch 1.2.x version, and it should be resolved if you edit and save the Data Input Method.
