### ISSUE TITLE
Request variable delete_type not validated in host.php resulting in warnings

### ISSUE THREAD

**Issue by majed17** [Cacti/cacti#3105]
on 1.2.x (not the latest), got an error while deleting a host with all data sources:
`CMDPHP Input Validation Not Performed for 'delete_type' Backtrace: (/host.php[70]:form_actions(), /host.php[294]:get_request_var(), /lib/html_utility.php[369]:html_log_input_error(), /lib/html_validate.php[44]:cacti_debug_backtrace()) `

although it actually delete succesfully

**Comment by cigamit** [comment]
Okay, got it.  There is a setting in Cacti to warn if we use any request variable that has not been validated/inspected, and you enabled that setting and are now helping keep Cacti safe :)

**Comment by majed17** [comment]
and what is it exactly that i enabled :)? i am unsure that i am away from defaults almost everywhere..

**Comment by netniV** [comment]
It is the option to verify that parameters are being properly vetted. Having that on is not a bad thing 👍

**Comment by cigamit** [comment]
We might want to create a 'developer' tab or something as this is literally a developer option.  Fortunately, it defaults to off.  Maybe we create a small project for the next release.
