### ISSUE TITLE
PHP Warning:  md5_file(....clude/themes/cacti/jquery.multiselect.filter.css) - No such file or directory

### ISSUE THREAD

**Issue by xmacan** [Cacti/cacti#3106]
Version 1.3.0 - Dev 8516c0c8, update from 1.2.7.

After update I have scheme "Cacti". Errors is in log after a lot of actions - change theme, click  New graph, ...

[Wed Nov 27 15:48:33.817911 2019] [php7:warn] [pid 58247] [client 192.168.222.52:58086] PHP Warning:  md5_file(/usr/local/share/cacti_develop/lib/../include/themes/cacti/jquery.multiselect.filter.css): failed to open stream: No such file or directory in /usr/local/share/cacti_develop/lib/functions.php on line 5338, referer: https://cactidevelop.kostax.cz/index.php?newtheme=1
[Wed Nov 27 15:48:37.130117 2019] [php7:warn] [pid 58247] [client 192.168.222.52:58086] PHP Warning:  md5_file(/usr/local/share/cacti_develop/lib/../include/themes/cacti/jquery.multiselect.filter.css): failed to open stream: No such file or directory in /usr/local/share/cacti_develop/lib/functions.php on line 5338, referer: https://cactidevelop.kostax.cz/settings.php
[Wed Nov 27 15:48:39.398231 2019] [php7:warn] [pid 58247] [client 192.168.222.52:58086] PHP Warning:  md5_file(/usr/local/share/cacti_develop/lib/../include/themes/cacti/jquery.multiselect.filter.css): failed to open stream: No such file or directory in /usr/local/share/cacti_develop/lib/functions.php on line 5338, referer: https://cactidevelop.kostax.cz/user_admin.php

**Comment by netniV** [comment]
I've pushed an update to develop to fix this issue.  Please note that DEVELOP is for the 1.3.x series that we are about to start working on enhancements for.  The current 1.2.x series is on the 1.2.x branch.

**Comment by xmacan** [comment]
I know. I wanted prepare my plugins for new themes which are in 1.3

**Comment by netniV** [comment]
OK, just some people missed that announcement so I tend to repeat it just to make sure they are aware.  Glad you're testing it out though 👍

**Comment by cigamit** [comment]
Yea, all good from my perspective. 👍

**Comment by netniV** [comment]
Fixed in https://github.com/Cacti/cacti/commit/42d43af5e1e29cab5c2a0b8bbd87d610d28adc92
