### ISSUE TITLE
nosync=true still syncs files to a remote poller

### ISSUE THREAD

**Issue by thurban** [Cacti/cacti#3110]
Setting **nosync=true** in the INFO file for plugins still syncs files to the remote poller.

i.e. the weathermap output directory and files within are being transferred to the remote poller everytime new/updated files are being generated.

**Expected behavior**
None of the files of the plugin (i.e. not even the plugin directory) should be synced to the remote poller

**Additional context**
Tested with Cacti 1.2.7 and Cacti 1.x compatible weathermap

**Comment by cigamit** [comment]
The correct syntax is:

```shell
nosync=relativepath1,releativepath2,...
```

**Comment by thurban** [comment]
Thanks.  Is there a documentation for these parameters ?

**Comment by netniV** [comment]
Probably not, are you offering ? ;-)

**Comment by cigamit** [comment]
lol, wish we all had more time.

**Comment by bmfmancini** [comment]
Sure! 

I just need to better understand it a bit but I am willing to document it 

Hey BTW  would it be ok if we moved the documentation to something other than Github its super annoying to deal with all of the formatting requirements for the Markdown I have a lot of documentation id like to share but dealing with the formatting really slows it all down 

I would be willing to donate hosting something like a wikimedia site and run with that side of things

**Comment by netniV** [comment]
We use GitHub markdown because we then convert from that format.  It also ensures we can apply rules to the formatting so there are no plans to move from it currently.

The rules can be annoying but if you do enough of them, it's a five minute job normally to fix up the mistakes 👍

**Comment by cigamit** [comment]
Markdown pad is available to help with the deficiencies of Markdown.  I agree.  It's super annoying, especially for those of use that have used real document word processors.  It's where we are at the moment though.

I just updated the plugin documentation.  Not sure it passes all the rules though.  Hehe.

**Comment by cigamit** [comment]
Going to close this now.

**Comment by thurban** [comment]
Argh..  found it here anyhow:  https://github.com/Cacti/documentation/blob/develop/Plugin-Development.md

Maybe I should read the docs before opening an issue ... ;-)
