### ISSUE TITLE
storage graphs for usb devices change devices on reboot

### ISSUE THREAD

**Issue by jkrinke** [Cacti/cacti#3114]
**Describe the bug**
If storage graphs are created for usb devices, they may change to allocated device on reboot as the allocated /dev device can change.  The result is that the graphs are different before and after reboot.

This can be fixed by using a different sorting.  A user 'gandalf' reported this and fixed it in his own template 'disk_usage' <https://docs.cacti.net/usertemplate:data:host_mib:disk_usage>.

The same fix can be applied to host_disk.xml to fix the issue (PR coming).

I have not looked at net-snmp_disk.xml which is also affected by the same problem.

The coming fix for host_disk.xml only works for newly created graphs, i.e. current graphs need to be removed and re-created. 

**To Reproduce**
1. Create storage graphs for multiple usb devices.
2. Reboot and force a change in the enumeration, e.g. by removing one usb device.
3. Graphs of usb devices change their allocated device.

**Expected behavior**
Storage graphs should keep their mapped device.

**Comment by cigamit** [comment]
Cut a pull request off the 1.2.x branch so we can see the diff.  Do this right away.  We are releasing this weekend.
