### ISSUE TITLE
When upgrading from a pre-1.x release, offer to add an automation network

### ISSUE THREAD

**Issue by cigamit** [Cacti/cacti#3122]
**Describe the bug**
Presently, when upgrading from an 0.8.x release, you do not get offered the ability to add an automation network.  This hides a key feature in Cacti 1.x that users should have the ability to take advantage of.

**To Reproduce**
1. Upgrade a 0.8.x instance
2. Note that you don't get the ability to add an automation network

**Expected behavior**
You should have the ability to add an automation network during upgrade.

**Comment by netniV** [comment]
I'm pretty sure that an automation network is created as part of 1.2.x.  Therefore, I think we should close this?
