### ISSUE TITLE
After automatic logout, logout repeats periodically

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#3129]
**Describe the bug**
unnecessary repeat auto-logout again and again

**To Reproduce**
1. Clean cookie and session
2. Access http://localhost/cacti/, `do not login`
3. keep a while, page will be forward to logout.php
4. what more time, you will found more logout.php request from browser DevTool or httpd access_log

**apache2/access_log: grep php**
 * 192.168.1.100 - - [04/Dec/2019:11:24:47 +0800] "GET /cacti/ HTTP/1.1
192.168.1.100 - - [04/Dec/2019:11:30:35 +0800] "GET /cacti/logout.php?action=timeout HTTP/1.1
192.168.1.100 - - [04/Dec/2019:11:36:23 +0800] "GET /cacti/logout.php?action=timeout HTTP/1.1
192.168.1.100 - - [04/Dec/2019:11:42:13 +0800] "GET /cacti/logout.php?action=timeout HTTP/1.1
192.168.1.100 - - [04/Dec/2019:11:48:01 +0800] "GET /cacti/logout.php?action=timeout HTTP/1.1
192.168.1.100 - - [04/Dec/2019:11:53:47 +0800] "GET /cacti/logout.php?action=timeout HTTP/1.1
192.168.1.100 - - [04/Dec/2019:11:59:36 +0800] "GET /cacti/logout.php?action=timeout HTTP/1.1
192.168.1.100 - - [04/Dec/2019:12:05:23 +0800] "GET /cacti/logout.php?action=timeout HTTP/1.1
192.168.1.100 - - [04/Dec/2019:12:11:11 +0800] "GET /cacti/logout.php?action=timeout HTTP/1.1
192.168.1.100 - - [04/Dec/2019:12:16:59 +0800] "GET /cacti/logout.php?action=timeout HTTP/1.1

**Comment by cigamit** [comment]
Resolved.  Thanks!
