### ISSUE TITLE
Cacti 1.0.3, new install, device state not changing to down, though time in state does change

### ISSUE THREAD

**Issue by camerabob** [Cacti/cacti#313]
I installed the Monitor plugin and set my APC UPS device to trigger an alert when down. I then pulled the Ethernet from the APC and nothing happened. After the five minute poll time lapsed, I saw no change on the Monitor screen. I then went to the device window to check settings and saw there that the device was still showing the green 'up' indicator though the 'in state' time had now changed to reflect it being down for the past five minutes. I am assuming here that Monitor gets its state from the device settings window. Not a Cacti pro, but I am really good at installing it...

My environment:
Date 			Mon, 20 Feb 2017 12:29:28 -0500
Cacti Version 		1.0.3
Cacti OS 			unix
RSA Fingerprint 	c5:d8:9b:84:32:1f:e0:da:64:33:28:55:d6:ab:46:a3
NET-SNMP Version 	NET-SNMP version: 5.7.2
RRDtool Version 	RRDTool 1.4.x
Devices 			12
Graphs 			81
Data Sources 		Script/Command: 6
				SNMP Get: 71
				SNMP Query: 21
				Script Server: 2
				Total: 100

**Comment by cigamit** [comment]
In order for Cacti to provide a device status when using cmd..php, you have to graph at least one thing, like the network interface, voltage, power, etc.  Otherwise, Cacti just see's it as a device to ignore.  When using spine, it may be more interesting.  Please implement spine, and let us know if you still experience an issue.  Otherwise, feel free to close.

**Comment by camerabob** [comment]
I have been monitoring. I was at the time as well.

![apc ups](https://cloud.githubusercontent.com/assets/25908052/23210852/5b2a3e7e-f8cd-11e6-91d2-8f0e3b45252d.png)

**Comment by cigamit** [comment]
Did you check the 'monitor' checkbox when setting up the device?  Also, the monitor plugin has some interesting interactions depending on your settings there.  So, this might just be operator error.  Glad you are good at installing it.  I think that this is likely just a fluke.  Let us know what your availability setting was set to.  In fact, attache a screen shot of the availability method, and ping method.  Thanks!

**Comment by camerabob** [comment]
Here you go. Nothing changed since the issue was reported.

![upssettings](https://cloud.githubusercontent.com/assets/25908052/23306858/43baef70-fa73-11e6-92b1-e2c6f4c415b1.png)

**Comment by cigamit** [comment]
You should put the device into debug mode and pull the plug again.  The Cacti log will include the ICMP ping log and the SNMP ping log results.

**Comment by camerabob** [comment]
I have no idea what has changed, I haven't done a damned thing and now Monitor is working as it is supposed to. I am closing this.
