### ISSUE TITLE
Regular user able to see and manage Reporting tab

### ISSUE THREAD

**Issue by nbhatti** [Cacti/cacti#3130]
Running 1.3.0 - Dev on  4-12-2019 git commit. Added a new user and made all default policies and templates to deny. New user is part of just 1 non-admin group. User is only allowed to see their own graphs.

When user logs in they are able to see Reporting tab with all administrative options enabled displaying Reports [Administrator Level] [ 1.3.0 - Dev ] as well. This regular user is also able to enable/disable/delete any reports. While in the list of devices he's only able to see their own devices, but if a report is made by administrator this user is able to see the device names of everything added to the report.

Looks like some permission issue in reporting module needs a fix.

Thanks.

**Comment by cigamit** [comment]
That is expected.  They will only be able to see their own reports though, where the admin level allows the admin to take over ownership of existing reports and of course manage/delete them.

So, there is really no action to take.  If you don't want people to be creating their own reports, you simply take away their 'Reports Creation' permission.

**Comment by nbhatti** [comment]
Correct this is expected but not happening. The user do not have any Report Creation permission but yet they are still able to create reports. If a report is made by admin, they are still able to view it.  The only permission for the users set are View, Update Profile and Realtime graphs.  Also took the ownership of the report but the user is still able to view. Anyway I can enable debug logs etc to see what's going on to help out?

**Comment by netniV** [comment]
Based on what you are saying I will reopen this for now whilst we test this out but this may be something that we can only see with your data.  So please bare with us if we can't seem to identify the root cause, as we may need to ask for a dump of your data.

**Comment by cigamit** [comment]
I have confirmed that this feature works perfectly in 1.2.8.  Your user may be a member of a user group that has the access, and Cacti's permissions are additive.  So, ensure that if the user is a member of a group that you remove that user groups permission to view/edit Reports.
