### ISSUE TITLE
Button to reindex bad indexes 

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3131]
Hey Guys 

One feature that would be awsome to have is a way to re-index devices with reported bad indexes 

we have outputs in the log that show something like this 

 WARNING: You have 145 Devices with bad SNMP Indexes.  Devices: Device[1210], Device[1215]

But it would be so useful if these 145 devices could be re-indexed to help solve the problem 
the only other way I know to re-index them would be either one by one or all of the devices
I am sure you could also do some cli magic with the poller_reindex script as well but it would be cool to be able to do it via the gui

**Comment by cigamit** [comment]
Yea, this should go on the System Utilities page.  You are using the 1.2.x branch right?  There is a force re-index for all hosts, but that will rerun for all devices.  You should really troubleshoot why those bad indexes happened.  Could be a crap data query (like Linux processes), or you simply have ifNames that are going away.  The seconds not likely unless you are removing or replacing cards with differing port counts in your switches.

**Comment by bmfmancini** [comment]
yea the devices with the bad indexs are a small portion of the total devices they are older ciscos some on older IOS as well so I am sure its all sorts of issues

**Comment by TheWitness** [comment]
With the new re-indexing in 1.2, this could be pretty fast.  But the screen would likely hang for a while unless it's done in background, which means you need a status page too, like boost.

**Comment by TheWitness** [comment]
This was actually resolved some time ago.  I'll mark resolved for 1.2.23 though.
