### ISSUE TITLE
CMDPHP PHP ERROR NOTICE

### ISSUE THREAD

**Issue by FormadorLar** [Cacti/cacti#3134]
Hi, my thold plugin cannot send emails (sadly, i have to verify from time to time if everything is working allright), i suspect it might have to do with this error appearing in the log:

> 2019/12/10 16:47:17 - CMDPHP PHP ERROR NOTICE Backtrace: (C:\inetpub\wwwroot\cacti\plugins\thold\thold.php[135]:thold_edit(), C:\inetpub\wwwroot\cacti\plugins\thold\thold.php[1975]:draw_edit_form(), C:\inetpub\wwwroot\cacti\lib\html_form.php[55]:CactiErrorHandler())
> --
> 2019/12/10 16:47:17 - ERROR PHP NOTICE: Undefined index: value in file: C:\inetpub\wwwroot\cacti\lib\html_form.php on line: 55

These two always appear at same time repeatedly - might a trigger action from thold has to do with it... Currently i've got one. 

I'm not a programmer or know php language that much i can correct the error, but i would appreciate very much if u could help.

If anything more is needed, please tell.

**Screenshots**
![image](https://user-images.githubusercontent.com/39267022/70553914-fabb7680-1b73-11ea-83b1-58acb1a97270.png)

Not always the "threshold modify" appears below the error, but in this example, it did.

**Desktop**
 - OS: Windows Server 2008 R2 + IIS7 + PHP 7.2.13
 - Browser: Chrome
 - Version of CACTI: latest 1.2.8

**Comment by cigamit** [comment]
What version of thold?  This would appear to be a thold issue.

**Comment by cigamit** [comment]
Please open this bug in thold issue tracker.  Thanks!
