### ISSUE TITLE
Plugin adoption to core - Weathermap

### ISSUE THREAD

**Issue by RustedKnight** [Cacti/cacti#3137]
With the development of the weathermap plug-in no longer being done by Howie would it be possible for the Cacti development team to take this in and make it part of the core much like the team did with things like Autom8 and Realtime?

**Comment by netniV** [comment]
That is unlikely to happen as Howie is still continuing to support the core product.  We are, or rather, I am planning to handle the Cacti GUI portion but that is waiting on a separation to be done by him of GUI and Core.  @thurban did get a version working with some changes so if he were to publish that, others could use it for the time being.

**Comment by thurban** [comment]
I've uploaded the current working version here:
https://www.urban-software.com/wp-content/uploads/Cacti1x/weathermap_098a_cacti1.x.zip
