### ISSUE TITLE
After Update 1.2.7. to 1.2.8 Graph History is empty

### ISSUE THREAD

**Issue by C00kiekiller** [Cacti/cacti#3138]
**Describe the bug**
History in graphs are not shown but rrd files are present

**To Reproduce**
1. Follow these steps [https://www.cacti.net/downloads/docs/html/upgrade.html](https://www.cacti.net/downloads/docs/html/upgrade.html)
2. After Update Login and click on 'Graphs'
3. select any device you want

**Expected behavior**
To see the history of my graphs

**Screenshots**
![Image of Issue](https://i.ibb.co/wNDD3SC/grafik.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser: Firefox, Chomre latest

**Additional context**
And yes I've copied my rrd files from the old installation folder to the new one.
Update from 1.2.6 to 1.2.7. was successful with graph history.
And i wait 1 hour but no history data was shown in the graphs only new data.

**Comment by cigamit** [comment]
You made some mistake.  Likely you either moved or removed your RRDfiles.  You should look for them, they will be in the "rra" directory.

**Comment by cigamit** [comment]
Look at the old 'rra' directory.
