### ISSUE TITLE
Cacti 1.0.3, new install Syslog plugin not accepting data [pulled]

### ISSUE THREAD

**Issue by camerabob** [Cacti/cacti#314]
After installing the Syslog plugin, I set my router and firewall to point data at Cacti. Nothing is showing up in the log area. I also ran a packet trace from the firewall to check and traffic was directed to Cacti from the firewall as well as the router. I ran 'netstat -pln and there is no indication of any device listening on UDP 514. The firewall confirmed this in the trace with 'Cannot PING device at xx.xx.xxx.xxx' Is there some hidden setting in the Syslog area to set things up? I hit the syslog tab in settings as well as the top syslog tab. Enabled, disabled, re-enabled. Nothing. Firewalld is stopped and disabled, and selinux is also stopped and disabled. ICMP pings work fine, just nothing from UDP 514.

My environment:
Date
-Mon, 20 Feb 2017 12:29:28 -0500

Cacti Version
-1.0.3

Cacti OS
-unix

RSA Fingerprint
-c5:d8:9b:84:32:1f:e0:da:64:33:28:55:d6:ab:46:a3

NET-SNMP Version
-NET-SNMP version: 5.7.2

RRDtool Version
-RRDTool 1.4.x

Devices
-12

Graphs
-81

Data Sources
-Script/Command: 6
-SNMP Get: 71
-SNMP Query: 21
-Script Server: 2
-Total: 100

**Comment by SoNix21** [comment]
humm... Cacti is not a SYSLog Server... 
You need to have your own syslog server, and forward the message to a database or a log file...
And Cacti will get access to the database/log...

**Comment by camerabob** [comment]
I currently have a Cacti 0.8.8b server running with the syslog plugin and have four YEARS worth of data sitting in it. Unless they changed the way the syslog plugin works, I believe you are incorrect. Or maybe the other install is a fluke? Highly unlikely. See below.

http://www.camerabob.com/graphics/cacti-0.8.8b.png

**Comment by itsjoke** [comment]
You need to have your own syslog server, and forward the message to a database or a log file...

**Comment by camerabob** [comment]
I'm pulling this because more than one person has told me that I'm inaccurate, so I will go back and do some research.

Thanks all.

**Comment by pautiina** [comment]
New syslog plugin have new format on syslog server.
I use Rsyslog and have this template:
```
$template cacti_syslog,"INSERT INTO syslog_incoming(facility_id, priority_id, program, date, time, host, message) \
values (%syslogfacility%, %syslogpriority%, '%programname%', '%timereported:::date-mysql%', '%timereported:::date-mysql%', '%HOSTNAME%', TRIM('%msg%'))", SQL
```
```
--------------------- start /etc/rsyslog.d/cacti.conf ---------------------

$ModLoad imudp
$UDPServerRun 514
$ModLoad ommysql

$template cacti_syslog,"INSERT INTO syslog_incoming(facility_id, priority_id, program, date, time, host, message) \ 
values (%syslogfacility%, %syslogpriority%, '%programname%', '%timereported:::date-mysql%', '%timereported:::date-mysql%', '%HOSTNAME%', TRIM('%msg%'))", SQL

*.* >localhost,my_database,my_user,my_password;cacti_syslog

--------------------- end /etc/rsyslog.d/cacti.conf ---------------------
```
