### ISSUE TITLE
After Update 1.2.7 to 1.2.8 Tree Mode blank

### ISSUE THREAD

**Issue by C00kiekiller** [Cacti/cacti#3140]
**Describe the bug**
The Tree Mode in the graph tab is complete empty.

**To Reproduce**
1. Update to 1.2.8 with the procedure [https://www.cacti.net/downloads/docs/html/upgrade.html](https://www.cacti.net/downloads/docs/html/upgrade.html)
2. Login into Cacti and select the Graph Tab
3. Optional select Tree View
4. See error blank site

**Expected behavior**
The see the trees and graphs

**Screenshots**
![Image of Issue](https://i.ibb.co/4scPD1F/grafik.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox, Chrome
 - Version latest

**Additional context**
- Cleard Browser Cache without success 
- Tried Brower Private Mode
- List View and Preview Mode are ok

**Comment by netniV** [comment]
Can you open the browser's developer tools and see if you have any console errors?

**Comment by C00kiekiller** [comment]
A mate installed yesterday an ad blocker. After disabling this the Tree View Mode works flawless.
