### ISSUE TITLE
No tree show

### ISSUE THREAD

**Issue by nicolapiazzi** [Cacti/cacti#3143]
![1](https://user-images.githubusercontent.com/54310887/70696236-93acd780-1cc3-11ea-913d-c80fc7feba23.PNG)
![2](https://user-images.githubusercontent.com/54310887/70696241-96a7c800-1cc3-11ea-9206-2c5cf2dbbcf4.PNG)

Fresh installed 1.2.8  on Centos8 PHP 7.4 MariaDB 10.4
Created graphs are not shown under tree, all tre are white also if enabled and also if not default tree

**Comment by nicolapiazzi** [comment]
I reverted a snapshot OS and made a fresh install of 1.2.7 and no problem with graph tree, i reverted another time and reinstalled 1.2.8 and no tree show.
Problem seems to be 1.2.8
If i disable Publish of default tree and go to Graphs > Tree i see a Search tab, if i enable Publish page is White, but i see a line in the left screen i suppose something hidden under this
![3](https://user-images.githubusercontent.com/54310887/70699490-85fa5080-1cc9-11ea-9faa-c2d6214afad5.PNG)

**Comment by netniV** [comment]
I believe this was a duplicate and I presume that's why you've closed it too.

**Comment by nicolapiazzi** [comment]
Yes, it was the same of "Chrome sets graphs tree navigation view to width 0px"
