### ISSUE TITLE
Unable to create aggregate graphs on new installations

### ISSUE THREAD

**Issue by brucereg** [Cacti/cacti#3146]
**Describe the bug**
This update added the gprint_format column to the aggregate_graphs and aggregate_graph_templates tables. The update include a patch to install/upgrades/1_2_8.php to perform an ALTER table to add the new column, unfortunately, the base cacti.sql file was not updated which causes new installations to fail when trying to create an aggregate template.
Also, the install/upgrades/1_2_8.php patch is trying to alter table aggregate_graph when it should be aggregate_graphs.

**To Reproduce**
Install a new 1.2.8 installation and try to create an aggregate template.

**Comment by netniV** [comment]
> Update for "Resolve a regression around #3027" is broken.

That would seem to be an issue.  Thanks for reporting it.

**Comment by brucereg** [comment]
On Dec 16, 2019, at 1:05 PM, Mark Brugnoli-Vinten <notifications@github.com> wrote:
> 
> Hmm, I just looked at the 1_2_8.php and it is definitely trying to do the right table:

Sorry, my eyes must be going. Yes, it looks correct. Must have misread it at one point. So only cacti.sql needs to be updated.

**Comment by netniV** [comment]
Yes, it looks like cacti.sql does not have the correct layout for those tables.  I will add a patch for that which @mortenstevens and @paulgevers will likely want to implement.

**Comment by netniV** [comment]
I believe that this should now be resolved, though @TheWitness and @cigamit should probably review the changes to the audit_schema.sql to make sure nothing majorly appears wrong.
