### ISSUE TITLE
When using Time Graph View, Zooming can cause errors

### ISSUE THREAD

**Issue by frontierliu** [Cacti/cacti#3150]
Cacti Version:1.2.8, Browser Version: Chrome 79.0.3945.79 (64bit)

when I zoom graphs in "time graph view"，it get an js error ,only return 6-months time range graphs, and can not zoom any more .
the js error is :
Uncaught TypeError: Cannot read property 'split' of undefined
    at getTimestampFromDate (layout.js?3838ec1b5a5992d776aae4c3e1eff89c:151)
    at HTMLAnchorElement.<anonymous> (layout.js?3838ec1b5a5992d776aae4c3e1eff89c:3411)
    at Function.each (jquery.js?2f0d15c70b7e652d5d61ed4032eb44af:354)
    at jQuery.fn.init.each (jquery.js?2f0d15c70b7e652d5d61ed4032eb44af:189)
    at initializeGraphs (layout.js?3838ec1b5a5992d776aae4c3e1eff89c:3407)
    at zoomAction_zoom_in (jquery.zoom.js?8914e0bed74b42db3f2bfc840db8e751:732)
    at HTMLDivElement.<anonymous> (jquery.zoom.js?8914e0bed74b42db3f2bfc840db8e751:460)
    at HTMLDivElement.dispatch (jquery.js?2f0d15c70b7e652d5d61ed4032eb44af:5183)
    at HTMLDivElement.elemData.handle (jquery.js?2f0d15c70b7e652d5d61ed4032eb44af:4991)
getTimestampFromDate @ layout.js?3838ec1b5a5992d776aae4c3e1eff89c:151
(anonymous) @ layout.js?3838ec1b5a5992d776aae4c3e1eff89c:3411
each @ jquery.js?2f0d15c70b7e652d5d61ed4032eb44af:354
each @ jquery.js?2f0d15c70b7e652d5d61ed4032eb44af:189
initializeGraphs @ layout.js?3838ec1b5a5992d776aae4c3e1eff89c:3407
zoomAction_zoom_in @ jquery.zoom.js?8914e0bed74b42db3f2bfc840db8e751:732
(anonymous) @ jquery.zoom.js?8914e0bed74b42db3f2bfc840db8e751:460
dispatch @ jquery.js?2f0d15c70b7e652d5d61ed4032eb44af:5183
elemData.handle @ jquery.js?2f0d15c70b7e652d5d61ed4032eb44af:4991

I tracked it and found it is a bug in /cacti/include/js/jsquery.zoom.js. But I have not located accurately yet.
Resolved temporary:  copy the 1.2.7's jsuqery.zoom.js override the 1.2.8's jquery.zoom.js ,and it works fine.

**Comment by netniV** [comment]
So, this is an issue where the date1 or date2 field isn't being found, and as a result, trying to get a date from it is impossible.  As there's no error checking in getTimestampFromdate, it bombs out.

I have added some checking to the routine and if undefined returns false.  However, I have not yet traced the cause or solution for the root issue.

**Comment by frontierliu** [comment]
Yes, html element date1 and date2 wh undefined when zooming graph. 
It is affect the "time graph view" page's zooming, But the export of CSV's is ok, so i think there is a bug inside jquery.zoom.js.

**Comment by netniV** [comment]
Well, exporting to CSV from the zoomed graph is a function of the jquery.zoom.js script.  So it should be applying to both parts.  Interesting that it is only one of them.

**Comment by netniV** [comment]
OK, so I am using chrome on a freshly installed Cacti 1.2.8+dev running under Chrome Version 79.0.3945.88 on a MacBook Pro.  I can zoom in and out without issue until I go to Time Graph View.  The reason for this being that the date1/date2 do not apply to the Time Graph View as they are only on the normal view.  

Should zooming be applicable on the time graph?

**Comment by netniV** [comment]
Whilst I have resolved the error, I believe that zooming should not be allowed when on Time Graph View as it defeats the purpose of that view.  Just waiting for feedback from @rony, @cigamit and @TheWitness on that one.

**Comment by frontierliu** [comment]
In cacti 1.2.5 and previous version, It works fine . I think it is a good and fast way to zoom a graph in a specific period.  Suggest to keep it.

**Comment by netniV** [comment]
That would mean that each graph on that view should have its own set of date fields.  Selecting a range on one currently affects all of them.

**Comment by frontierliu** [comment]
I have applied the newest bug fixed, the js error have gone, but the time view graph zoom still not work properly,  only return 6 months time-range graph.
Finally I find the bug was in  cacti 1.2.8's cacti/include/js/jquery.zoom.js，the function call of initializeGraphs():
line 732:                                            initializeGraphs(); 
line 842:                                            initializeGraphs();
the function definition is in cacti/include/layout.js.

In cacti 1.2.7 and previous version,  the above function call are initializeGraph(),  lack of 's',
the function definition is in cacti/graph.php, not in  layout.js.
The function inititalizeGraph() works ok in “time view graph", for it does not use gettimeofstamp().
So, I think it is a bug about wrong  function call. Remove the 's'  in that 2 lines and resolved.

**Comment by cigamit** [comment]
Oh, that would be a problem.  Thanks for catching that.

**Comment by cigamit** [comment]
Okay, it's resolved.  Thanks for you debugging efforts.
