### ISSUE TITLE
Moving items in aggregate graphs

### ISSUE THREAD

**Issue by Izmenoff** [Cacti/cacti#3152]
I have a big aggregate graphs and I need to moving items up or down. How it possible to change position the items in aggregate graphs?
Thanks!
![Clipboard01](https://user-images.githubusercontent.com/17400240/71156319-d5ec9080-2250-11ea-9653-41bd0761ef26.jpg)

**Comment by cigamit** [comment]
Likely the best thing you can do is to convert the aggregate to a standard Graph and then re-order.  Not though that in Cacti 1.2.8, when you say to re-order by Graph, the graphs will actually be sorted by Graph name as you might be looking to do.

**Comment by Izmenoff** [comment]
Thanks a lot!
