### ISSUE TITLE
Сhange of values don't work in Cacti Settings (Poller)

### ISSUE THREAD

**Issue by Izmenoff** [Cacti/cacti#3154]
Cacti 1.2.8
Values **Default Threads per Proces or Default Data Collector Processes** don't work  in Cacti Settings (Poller).
Сhanges working only in Data Collectors - Main Poller - Collection Settings (Processes, Threads)

**Comment by netniV** [comment]
Correct.  The first is merely the default for a new poller.  All poller settings are configured against the poller.

**Comment by Izmenoff** [comment]
tnx, clear
