### ISSUE TITLE
Aggregate Reorder Type & color template

### ISSUE THREAD

**Issue by Izmenoff** [Cacti/cacti#3155]
If I use Reorder Type (Graph, Data Source) color template does not fit to graph
![image](https://user-images.githubusercontent.com/17400240/71399554-09566300-2635-11ea-938e-00bb7b3f0f16.png)
![image](https://user-images.githubusercontent.com/17400240/71399564-15dabb80-2635-11ea-99ce-0f0a1b023690.png)
If Reorder Type (No reordering) - all's ok
![image](https://user-images.githubusercontent.com/17400240/71399665-74a03500-2635-11ea-98de-f6161f427f7f.png)

**Comment by cigamit** [comment]
Yea, darn.  I did not think of that when I did the Re-order fix.  Good catch!!!

**Comment by Izmenoff** [comment]
Thanks for quick response and solving the problem

**Comment by cigamit** [comment]
Please update lib/api_aggregate.php from the 1.2.x branch, then change the Reorder, save, and then back to the desired Reorder and save again.  Let me know if they are proper now.

**Comment by cigamit** [comment]
It's not fixed.  Does not cover the Data Source, Graph reordering.

**Comment by cigamit** [comment]
Okay, should be okay now.

**Comment by Izmenoff** [comment]
Thanks! I'm just waiting for 1.2.9
