### ISSUE TITLE
SQL Save on table 'aggregate_graphs': Column 'gprint_format' does not exist, unable to save!

### ISSUE THREAD

**Issue by krisxzd** [Cacti/cacti#3156]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by cigamit** [comment]
Yea, there was an issue in the clean install of Cacti 1.2.8.  Just goto the cli directory and run this command:

```console
php -q upgrade_database.php --forcever=1.2.7
```

That'll fix the issue near term.  Total fix for new installs will be to install from 1.2.9.

**Comment by krisxzd** [comment]
Thank you very much for solving the problem.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jimmy Conner"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月24日(星期二) 晚上11:28
收件人:&nbsp;"Cacti/cacti"<cacti@noreply.github.com&gt;;
抄送:&nbsp;"快乐的忧愁"<32113816@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Cacti/cacti] SQL Save on table 'aggregate_graphs': Column 'gprint_format' does not exist, unable to save! (#3156)




Yea, there was an issue in the clean install of Cacti 1.2.8.  Just goto the cli directory and run this command:
 php -q upgrade_database.php --forcever=1.2.7
 
That'll fix the issue near term.  Total fix for new installs will be to install from 1.2.9.

**Comment by rtripon** [comment]
Hello,
I have a kinda similar situation on a cacti 1.3.0(develop) when I try to add an aggregate graph template
![aggregate error](https://user-images.githubusercontent.com/28921178/73393086-c0549700-42e3-11ea-8f2d-3b2db6b980ee.jpg)
. I tried repairing the database, no luck :

[root@wg cli]# php -q upgrade_database.php --forcever=1.3.0
ERROR: Your Cacti is already up to date
  - from: v1.3.0
      to: v1.3.0 - Dev bb619ef @ 2019-12-27 13:49

**Comment by netniV** [comment]
We need to merge 1.2.9 when it is released into 1.3.0.  However, once that is done, you should use --forcever=1.2.7 rather than 1.3.0 just so that it runs through the required upgrades again.
