### ISSUE TITLE
Back button not working in all cases in 1.2.8

### ISSUE THREAD

**Issue by Susanin63** [Cacti/cacti#3157]
I'm having and issue where the browser back button does not return to the previous page in certain instances.
Clear 1.2.8 install. Admin profile - choose Classic theme. After that click on main menu Console - Management  and after that menu "Devices","Sites","Trees". Then click Back button on browser. Link adress will change, but browser don't update data.

Another theme work fine.
Tested on FF and Chrome last version. 
In layout.js 2485 don't fired.

**Additional context**
```
	$('#filter, #rfilter').keydown(function(event) {
		if (event.keyCode == 8 && $(this).val() == '') {
			handlePopState();
		}
	});
```
not fired in any themes.

**Comment by cigamit** [comment]
Well, that code is to prevent the backspace from triggering a back action when your cursor is inside the filter and you backspace to the beginning.  So, that's not the place.  Going to trace this one.

**Comment by cigamit** [comment]
Well, that's odd.  The jQuery function was not triggering on Classic for some unknown reason.

**Comment by Susanin63** [comment]
Now it works better, but not perfect.
Tested on Classic and Modern theme. Open cacti and open link: Managment -> Devices, Sites, Trees and the remaining 8 links in turn. After that press Back button one time. 
Adress will be:
...../plugins/thold/notify_lists.php?nostate=true
press Back button one more time:
...../plugins/thold/notify_lists.php - but we have the same content
press Back button one more time:
...../aggregate_graphs.php?nostate=true - this work correct
press Back button one more time:
and we have blank page!
 
tested on normal and private mode on Chrome 79.0.3945.88 (x64)
