### ISSUE TITLE
Classic theme show only 3 tabs on mobile device. Don't show Console menu

### ISSUE THREAD

**Issue by Susanin63** [Cacti/cacti#3158]
On classic theme on  mobile device don't work pinch zoom. Because of this, only 3 tabs are visible and the main menu is hidden after half a second. Video is attached.

Xiaomi MiMIX 2S   5.99" and  2160x1080
![cacti](https://user-images.githubusercontent.com/28290503/71467861-8b818b80-27dd-11ea-8830-c3d14e1931af.gif)

**Comment by Susanin63** [comment]
And old version (0.8.8f) on that device looks like this:
![cacti_old _](https://user-images.githubusercontent.com/28290503/71469731-81fb2200-27e3-11ea-8916-7dbbf2b937c2.gif)

**Comment by netniV** [comment]
I think there should be a tab with three dots in it for the drop down part, but I can't recall if that applies to classic.

**Comment by TheWitness** [comment]
Presently, it does not.  I checked the code.  I'm not sure how much work it is to fix though. Maybe we just don't hide under that theme.

**Comment by netniV** [comment]
I think given this is a "Classic" theme, that's probably the easiest answer.

**Comment by Susanin63** [comment]
or change one line a little:
lib\html.php:2296
`<meta content='width=device-width, initial-scale=0.5, minimum-scale=0.2, maximum-scale=2.0' name='viewport'>`

to make the pinch-zoom work again

**Comment by TheWitness** [comment]
Maybe that's better for the classic theme.  For the others, they handle the tab hiding and showing just fine.

**Comment by TheWitness** [comment]
Test the latest lib/html.php.

**Comment by Susanin63** [comment]
Now it is work!
