### ISSUE TITLE
PHP Memory is not correctly identified when value is not in megabytes

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#3159]
**Describe the bug**
Installation Wizard can not identify PHP-->memory_limit when unit is not 'M'

**To Reproduce**
1. Prepare Cacti 1.2.7 or earlier env
2. Edit /etc/php.ini, set `memory_limit = 2G`
3. Restart httpd service
4. Web access Cacti  and Click Next
5. See error

**Expected behavior**

**Screenshots**
set memory_limit to 2G in php.ini
![image](https://user-images.githubusercontent.com/17589018/71519769-d55c9580-28f3-11ea-944f-c29325920b4e.png)

set memory_limit to 2048M in php.ini
![image](https://user-images.githubusercontent.com/17589018/71519627-56675d00-28f3-11ea-8a7d-cf02941bff1d.png)

**Comment by netniV** [comment]
Good catch.  I'll see if I can fix this one up.
