### ISSUE TITLE
Graph Realtime issue

### ISSUE THREAD

**Issue by sysres-dev** [Cacti/cacti#3160]
**Describe the bug**
Realtime does not produces graph based on SNMP  Data Query(ex: <path_cacti>/resource/script_server/host_disk.xml). This issue disappears when the device is moved to another data collector. When the device is moved back to a previously used data collecter, the issue come back.
Others graphs are not affect by this issue (ex: graphs based on NSCP request).
Graphs based on scheduled polling are correctly displayed.

**To Reproduce**
- On Data collector A:
Click on the realtime icon for a graph.
Wait for a few seconds and no image is displayed.
The rrd and the png files are not created on the master

-	Move the device to Data collector B
Click on the realtime icon for a graph.
Wait for a few seconds and the graph is displayed.
The rrd and the png files are created on the master (<path_cacti>/cache/realtime/)

-	Move back to Data collector A
Remove rrd and png files in cache directory (<path_cacti>/cache/realtime/).
Click on the realtime icon for a graph.
Wait for a few seconds and the graph is displayed with no data.
The rrd and the png files are present on the master (<path_cacti>/cache/realtime/) but they are empty.

**Expected behavior**
The graphs are displayed in realtime.

**Screenshots**
![Screenshot1](https://user-images.githubusercontent.com/45565495/71587266-52b71e80-2b1d-11ea-9225-bde3236c224a.jpg)

![Screenshot2](https://user-images.githubusercontent.com/45565495/71587271-564aa580-2b1d-11ea-8873-139fcd40e3ee.jpg)

![Screenshot3](https://user-images.githubusercontent.com/45565495/71587279-59de2c80-2b1d-11ea-981b-c534362a9646.jpg)

**Server**
- Master/ Data collector A / Data collector B
o	Red Hat Enterprise Linux Server release 7.5 (Maipo)
o	kernel 3.10.0-862
o	Cacti 1.1.38:
RRDtool Version RRDtool 1.4.x
Devices	34531
Graphs	581607
Data Sources	Script/Command: 24829
SNMP Get: 90446
SNMP Query: 391151
Script Query: 70787
Script Server: 34112
Script Query - Script Server: 41320
Total: 652645

**Compiling (please complete the following information)**
•	compiler: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
•	autoconf: autoconf (GNU Autoconf) 2.69
•	glibc: glibc-2.17-260
•	source: release 1.1.38

**Additional context**
Result of http request from master to data collectors:
- Data collector A:
o	Request:
GET /cacti//remote_agent.php?action=polldata&host_id=65516&local_data_ids%5B0%5D=1069831&poller_id=8o55hbs1a2kahsb0udpet3svq2

o	Response:
Server: Apache
X-Powered-By: PHP/7.0.27
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 1000
Access-Control-Allow-Headers: X-Requested-With, Content-Type, Origin, Authorization, Accept, Client-Security-Token, Accept-Encoding
Access-Control-Allow-Methods: POST, GET, OPTIONS, DELETE, PUT
Connection: close
Content-Type: text/html; charset=UTF-8
[{"value":"274864078848","rrd_name":"hdd_total","local_data_id":"1069831"},{"value":"266101194752","rrd_name":"hdd_used","local_data_id":"1069831"}]

- Data collector B:
o	Request:
GET /cacti//remote_agent.php?action=polldata&host_id=65516&local_data_ids%5B0%5D=1069831&poller_id=8o55hbs1a2kahsb0udpet3svq2
o	Response:

Server: Apache/2.4.6 (Red Hat Enterprise Linux) mod_fcgid/2.3.9
X-Powered-By: PHP/7.0.27
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 1000
Access-Control-Allow-Headers: X-Requested-With, Content-Type, Origin, Authorization, Accept, Client-Security-Token, Accept-Encoding
Access-Control-Allow-Methods: POST, GET, OPTIONS, DELETE, PUT
Connection: close
Content-Type: text/html; charset=UTF-8
[{"value":"274864078848","rrd_name":"hdd_total","local_data_id":"1069831"},{"value":"266464591872","rrd_name":"hdd_used","local_data_id":"1069831"}]

**Comment by bmfmancini** [comment]
you know what I did see something like this  on one of my devices on a remote poller and moving it to the main poller did yield the same result 

but in my case I re-added the device and have not had an issue since 
is it only the disk data query you are having an issue with ?

**Comment by cigamit** [comment]
I've been trying to avoid this one, since I actually have to think.  I might get to it tomorrow.

**Comment by sysres-dev** [comment]
In response to bmfmancini, I also have this issue with:
Host - MIB -Processees (Data input method: SNMP Data).
Ping - Advanced ping (Data input method: Ping - Advanced ping [<path_cacti>/scripts/ss_fping.php ss_fping]).
CPU utilization (Script Server Data 	Host MIB - CPU Usage).

I can reproduce the behaviour when I move the device to another data collector.

**Comment by cigamit** [comment]
Are you using the HMIB plugin for any of this?

**Comment by cigamit** [comment]
Also, from the remote data collector system, monitor the apache error and access logs and let us know what is showing up there when you are trying to view realtime.  That'll be important.  Lastly, in the php.ini file set the error_log = /tmp/php_errors.log, and then watch in both the /tmp directory as well as the systemd processes /tmp file, it's usually /tmp/systemd*http*/tmp for example.  Let us know if things are stacking up there too.

**Comment by netniV** [comment]
When using /tmp, be aware that some systems actually map that for system services to be under another folder such as `/tmp/systemd-apache-1234/tmp` so you should probably use find to locate the logs if you can't see them immediately.

**Comment by sysres-dev** [comment]
I am sorry for the delay of my answer.

We don't use the HMIB plugin.

I have searched the php logs error and I didn't see any error related to the realtime.
I only find some errors not present on the data collectors where the realtime is working:

Here an example:

[24-Feb-2020 14:27:04 Europe/Paris] PHP Parse error:  syntax error, unexpected 'pid' (T_STRING), expecting ',' or ')' in /tmp/ccp0OUdbV on line 153
[24-Feb-2020 14:32:04 Europe/Paris] PHP Parse error:  syntax error, unexpected 'pid' (T_STRING), expecting ',' or ')' in /tmp/ccpEJ9u1V on line 153

**Comment by netniV** [comment]
That would suggest that there is a problem with one or more of the files that is being sent over to the remote poller.

Can you run the following on your main collector?
```
cd <path to cacti>
find . -name \*.php -exec php -l {} \;
```

**Comment by sysres-dev** [comment]
On the main collector I have these errors with the command:
`find . -name \*.php -exec /opt/rh/rh-php70/root/bin/php -l {} \; | grep -v "No syntax errors detected in"`

The result is:

```
PHP Parse error:  syntax error, unexpected 'pid' (T_STRING), expecting ',' or ')' in ./script_server.php on line 153
Errors parsing ./script_server.php
PHP Fatal error:  Cannot declare class SNMP, because the name is already in use in ./include/phpsnmp/classSNMP.php on line 36
Errors parsing ./include/phpsnmp/classSNMP.php
PHP Fatal error:  Cannot declare class SNMP, because the name is already in use in ./include/vendor/phpsnmp/classSNMP.php on line 36
Errors parsing ./include/vendor/phpsnmp/classSNMP.php
```

The context arroung the line 153 returning the error for script_server.php:

```
150                 if (substr($input_string,0,4) == 'quit') {
151                         fputs(STDOUT, 'PHP Script Server Shutdown request received, exiting\n');
152                         fflush(STDOUT);
153                         cacti_log('DEBUG: PHP Script Server Shutdown request received, exiting. 'pid: ' . $pid', false, 'PHPSVR', POLLER_VERBOSITY_DEBUG);
154                         db_close();
155                         exit(0);
```


The context arroung the line 153 returning the error for classSNMP.php:
```
 32 if (!defined('SNMP_STRING_OUTPUT_HEX')) {
 33         define('SNMP_STRING_OUTPUT_HEX', 3);
 34 }
 35
 36 class SNMP {
 37         const ERRNO_NOERROR = 0;
 38         const ERRNO_GENERIC = 1;
 39         const ERRNO_TIMEOUT = 2;
 40         const ERRNO_ERROR_IN_REPLY = 3;
 41         const ERRNO_OID_NOT_INCREASING = 4;
```

**Comment by netniV** [comment]
Ok I can see the SNMP problem, we moved the external libraries to the vendor folder. It looks SNMP is also still in the root folder. They should not both be in use though.

**Comment by netniV** [comment]
For script server, download the latest version from GitHub because yours does seem flawed, plus I fixed a few things that will be coming out in 1.2.10 this weekend.
