### ISSUE TITLE
Not able add devices in CACTI 1.2.8.

### ISSUE THREAD

**Issue by amarnath-jena** [Cacti/cacti#3162]
When i am adding a host or network device in cacti . It doesnt get add and also doesnt show any error. Kindly help me tp resolve it.
![cacti](https://user-images.githubusercontent.com/54077804/71655333-38b74f00-2d5c-11ea-955b-78b228b5ee22.png)

**Comment by netniV** [comment]
Please give more information.

**Comment by amarnath-jena** [comment]
its working now. I dont know exactly what was the issue.
i have a issue with the import template section it doesnt import templates. I have to manually import it.
Mikrotik multicore cpu graph avg not working. even though i import the tenplate manually.
![Screenshot from 2020-01-02 19-35-36](https://user-images.githubusercontent.com/54077804/71670788-17c01f80-2d97-11ea-8546-80b116f8bcb7.png)
