### ISSUE TITLE
Broken graph issue

### ISSUE THREAD

**Issue by sirjana** [Cacti/cacti#3164]
I am getting Cacti log error as:
1/03/2020 12:18:39 PM - CMDPHP: Poller[0] WARNING: SNMP Get Timeout for Host

POLLER: Poller[0] WARNING: Poller Output Table not Empty. Issues Found: 274636, Data Sources: traffic_in(DS[24]), traffic_out(DS[24]),

Due to this all graph seems broken and I tried on different server and working fine. I have increased The Maximum SNMP OID's Per SNMP Get Request and snmp timeout but it's still not working. Any idea? please help**Describe the bug**

**Comment by TheWitness** [comment]
Set the error_log in php to /tmp/php_errors.log and the watch it.  Your poller may be running over it's poller frequency.  Using boost normally solves these issues.  This is more like a support)training issue.  So, I'm going to close this.
