### ISSUE TITLE
Array and string offset access syntax with curly braces is deprecated in php 7.4

### ISSUE THREAD

**Issue by jostreff** [Cacti/cacti#3169]
**Describe the bug**
Array and string offset access syntax with curly braces is deprecated in php 7.4.

**To Reproduce**
1. install php 7.4

**Comment by jostreff** [comment]
Deprecated: Array and string offset access syntax with curly braces is deprecated in /usr/local/share/cacti/lib/functions.php on line 1964

Deprecated: Array and string offset access syntax with curly braces is deprecated in /usr/local/share/cacti/lib/functions.php on line 2452

Deprecated: Array and string offset access syntax with curly braces is deprecated in /usr/local/share/cacti/lib/functions.php on line 2477

Deprecated: Array and string offset access syntax with curly braces is deprecated in /usr/local/share/cacti/lib/functions.php on line 2479

Deprecated: Array and string offset access syntax with curly braces is deprecated in /usr/local/share/cacti/lib/functions.php on line 5198

Warning: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /usr/local/share/cacti/include/global.php on line 376

Warning: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /usr/local/share/cacti/include/global.php on line 378

Warning: Cannot modify header information - headers already sent by (output started at /usr/local/share/cacti/lib/functions.php:1964) in /usr/local/share/cacti/include/global.php on line 382

Warning: Cannot modify header information - headers already sent by (output started at /usr/local/share/cacti/lib/functions.php:1964) in /usr/local/share/cacti/include/global.php on line 383

Warning: Cannot modify header information - headers already sent by (output started at /usr/local/share/cacti/lib/functions.php:1964) in /usr/local/share/cacti/include/global.php on line 384

Warning: Cannot modify header information - headers already sent by (output started at /usr/local/share/cacti/lib/functions.php:1964) in /usr/local/share/cacti/include/global.php on line 385

Warning: Cannot modify header information - headers already sent by (output started at /usr/local/share/cacti/lib/functions.php:1964) in /usr/local/share/cacti/include/global.php on line 386

Warning: Cannot modify header information - headers already sent by (output started at /usr/local/share/cacti/lib/functions.php:1964) in /usr/local/share/cacti/include/global.php on line 387

Warning: Cannot modify header information - headers already sent by (output started at /usr/local/share/cacti/lib/functions.php:1964) in /usr/local/share/cacti/include/global.php on line 389

Warning: session_name(): Cannot change session name when headers already sent in /usr/local/share/cacti/include/global.php on line 395

Warning: session_start(): Cannot start session when headers already sent in /usr/local/share/cacti/include/global.php on line 396
User Login

**Comment by jostreff** [comment]
Deprecated: Array and string offset access syntax with curly braces is deprecated in /usr/local/share/cacti/lib/import.php on line 231

**Comment by netniV** [comment]
I'm going to mark this as an enhancement for 1.3.  1.2.x will work fine under 7.3 and one or two of the above errors (such as unable to set the session name) will actually vanish under 1.3 if the warnings before it disappear.

**Comment by netniV** [comment]
I believe that this has been rectified as part of some recent fixes.  If not, please let us know and we can reopen it.
