### ISSUE TITLE
Mouse-wheel scrolling on left-side navigation menu frame causes scrolling on main frame

### ISSUE THREAD

**Issue by CapitalF** [Cacti/cacti#317]
Mouse-wheel scrolling on the left-side navigation menu frame will cause scrolling to occur on the main window frame. This is undesired behavior.

Cacti 1.0.3 on Linux. Browser used is Chromium on Linux.

**Comment by cigamit** [comment]
Yea, this is an artifact that is hard to control.  I suggest you start working on that theme.  We are looking forward to it.  There is always the Classic theme that at least is a little closer to what you may be used to.
