### ISSUE TITLE
Reorder Type in Aggregate Graph not working

### ISSUE THREAD

**Issue by hp619** [Cacti/cacti#3171]
Today we upgraded from Cacti 1.2.7 to 1.2.8 and noticed, that newly created aggregate graphs do not seem to follow the reorder type setting anymore. No matter what option is chosen, the graph item order stays the same and thus the graph always renders identical.

Existing graphs created on 1.2.7 are still displayed correctly, as long as they are not modified. There's also no difference if the graph is created directly or from a template.

On 1.2.7 we used the following settings:
![ag-settings](https://user-images.githubusercontent.com/59609312/71909246-ea48ec80-316f-11ea-9670-7d0e42b3a995.png)

which resulted in the following (desired) graph:
![ag](https://user-images.githubusercontent.com/59609312/71910299-ecac4600-3171-11ea-94c8-0672a29936a2.png)

On 1.2.8 the same settings result in the following graph:
![ag-broken](https://user-images.githubusercontent.com/59609312/71910392-1d8c7b00-3172-11ea-92ad-d4a05cc2d156.png)

Since there were other issues regarding aggregate graph ordering lately, we already tried to replace /lib/api_aggregate.php from the 1.2.x branch to see if there's any difference, without any success.

**Comment by cigamit** [comment]
Can you change it to Graph, Data Source and save again, then preview, upload the preview.  Followed by another save back to Data Source, Graph?  Next, show an upload of don't reorder.  Then, update lib/api_aggregate.php from the 1.2 branch, and rinse and repeat.

**Comment by cigamit** [comment]
Maybe the latest lib/api_aggregate.php fixes this.

**Comment by hp619** [comment]
Ok here we go...
Set to Graph, Data Source:
![agg_gr_ds](https://user-images.githubusercontent.com/59609312/72053487-6e61b800-32c7-11ea-9a99-7bcb33e51a88.png)

Set to Data Source, Graph:
![agg_ds_gr](https://user-images.githubusercontent.com/59609312/72053523-83d6e200-32c7-11ea-80d7-2be87595abdc.png)

And with no reordering:
![agg_no_reorder](https://user-images.githubusercontent.com/59609312/72053561-92bd9480-32c7-11ea-9309-3f351102fed4.png)

Then replaced lib/api_aggregate from [here](https://github.com/Cacti/cacti/blob/1.2.x/lib/api_aggregate.php) and again...
Set to Graph, Data Source:
![agg_gr_ds2](https://user-images.githubusercontent.com/59609312/72054358-1f1c8700-32c9-11ea-834a-5992deb77970.png)

Set to Data Source, Graph:
![agg_ds_gr2](https://user-images.githubusercontent.com/59609312/72054380-26dc2b80-32c9-11ea-930d-0d831bd2da63.png)

And again with no reordering:
![agg_no_reorder2](https://user-images.githubusercontent.com/59609312/72054396-3196c080-32c9-11ea-908f-162c80657f80.png)

To my eye all graphs look identical and I didn't just upload the same screenshot six times ;)

**Comment by hp619** [comment]
I compared the database entries of two aggregate graphs. ID 7 is still rendering correctly while ID 23 is the graph shown above.

```
+----+-----------------------+----------------------+----------------+-----------------------------------+-------------------+-----------------+---------------+------------+-------+------------+--------------+------------+---------------------+---------+
| id | aggregate_template_id | template_propogation | local_graph_id | title_format                      | graph_template_id | gprint_prefix   | gprint_format | graph_type | total | total_type | total_prefix | order_type | created             | user_id |
+----+-----------------------+----------------------+----------------+-----------------------------------+-------------------+-----------------+---------------+------------+-------+------------+--------------+------------+---------------------+---------+
|  7 |                     0 |                      |            136 | Aggregate (Archive)               |                68 | |query_ifAlias| |               |         50 |     2 |          1 | Total        |          2 | 2019-12-19 10:38:57 |       4 |
| 23 |                     0 |                      |            153 | Aggregate Test                    |                68 | |query_ifAlias| |               |          8 |     2 |          1 | Total        |          2 | 2020-01-09 10:37:17 |       4 |
+----+-----------------------+----------------------+----------------+-----------------------------------+-------------------+-----------------+---------------+------------+-------+------------+--------------+------------+---------------------+---------+
```

**Comment by cigamit** [comment]
Well, this is quite odd.  Can I ask for one more thing, can you paste a screen shot of the Aggregate Edit General tab?  I need to see how that looks.  Thanks for your patience.  I've been busy this week and only able to get to these things off hours.

**Comment by hp619** [comment]
No worries, thanks for your time.

Edit view part 1:
![edit-view-1](https://user-images.githubusercontent.com/59609312/72325793-2ae3c100-36ae-11ea-971f-8a95c2a43596.png)
Edit view part 2:
![edit-view-2](https://user-images.githubusercontent.com/59609312/72325813-36cf8300-36ae-11ea-8e65-f12d69e3b169.png)

**Comment by cigamit** [comment]
Okay, I think I know what is going on now.  Going to make a commit shortly.

**Comment by cigamit** [comment]
Okay, try again.  Remember change to Graph, Data Source, save, back to Data Source, Graph, and then save again.

**Comment by hp619** [comment]
Ok, I can see a difference now but not yet the desired result.

I pulled the latest lib/api_aggregate.php again and these are the graphs

No reorder:
![agg_no_reorder](https://user-images.githubusercontent.com/59609312/72504540-4978c200-383e-11ea-9e84-1d3ee3cf1072.png)

Data Source, Graph:
![agg_ds_gr](https://user-images.githubusercontent.com/59609312/72504587-5f868280-383e-11ea-8693-9c9163718278.png)

And Graph, Data Source:
![agg_gr_ds](https://user-images.githubusercontent.com/59609312/72504606-6c0adb00-383e-11ea-999d-fc096568557a.png)

I also have to mention that normally I'm using the setting **Keep Type and STACK** instead of **Convert to AREA/STACK Graph** like it's shown in the previous settings screenshot. But right now there's no visible difference between these two settings.

**Comment by cigamit** [comment]
Okay, you have to update include/global_constants.php, include/global_arrays.php, and lib/api_aggregate.php.  There is a new order type called 'Base Graph Order', use that sort order, and save.  Should be back to normal.

**Comment by hp619** [comment]
Yes, can confirm it's working. Thanks a lot :)

---

Btw, I found one or two other bugs while messing around with aggregate graphs.
- When an aggregate graph is created, the setting **Include Prefix Text** is not followed. Afterwards in the edit screen it works as expected.
- When creating an aggregate graph from a template, the resulting graph legend is slightly broken and the setting **Include Prefix Text** is not followed.
- When an aggregate graph is converted to a normal one, you can't edit it or it will be broken.


If you'd like I can create additional issues for them.

**Comment by netniV** [comment]
Yes please so they can be properly tracked and not lost with other comments
