### ISSUE TITLE
when I upgrade 1.2.7 to 1.2.8 found error

### ISSUE THREAD

**Issue by angelsu00** [Cacti/cacti#3172]
mysql version 5.6.46

CMDPHP SQL Backtrace: (/plugins/monitor/poller_monitor.php[87]:monitor_uptime_checker(), /plugins/monitor/poller_monitor.php[185]:db_execute(), /lib/database.php[191]:db_execute_prepared())
CMDPHP ERROR: A DB Exec Failed!, Error: You can't specify target table 'plugin_monitor_uptime' for update in FROM clause

**Comment by netniV** [comment]
That Is not a cacti core issue. That is a monitor plugin issue and should be opened there.
