### ISSUE TITLE
Fresh cacti installed but got some issue with php kindly help to solve

### ISSUE THREAD

**Issue by amarnath-jena** [Cacti/cacti#3173]
cacti-1.2.8
apache-2
php-7.2
ubuntu 18.04
below screenshot for error
![cacti issue](https://user-images.githubusercontent.com/54077804/71982438-762f4700-324a-11ea-9b22-2c626f7edabe.png)

**Comment by bmfmancini** [comment]
Looks like your PHP is not properly installed

Make sure you have libapache2-mod-php7.2 of not do a apt-install for it
then restart apache

**Comment by netniV** [comment]
I’m on my phone right now so the s screenshot isn’t expanding for me but it does look like your web server isn’t interpreting the PHP so that would suggest it does not have the php engine enabled even if it is installed.

**Comment by amarnath-jena** [comment]
sudo a2enmod php7.2
systemctl restart apache2

This command worked for me.
Thanks for help team.

**Comment by bmfmancini** [comment]
Cool!
Glad it worked  out

**Comment by netniV** [comment]
Yeah good should Sean

**Comment by netniV** [comment]
*shout

**Comment by bmfmancini** [comment]
this is a good candidate for a document under the troubleshooting section

**Comment by cigamit** [comment]
Agree.

**Comment by netniV** [comment]
I have now added a small FAQ relating to this.
https://github.com/Cacti/documentation/commit/765235b9dc74342887a9876d13a03c310b027bd0#diff-3dcbd9e0f16162e0704f17707513c711
