### ISSUE TITLE
Spine-Error with "Wrong-Type" SNMP-Answer

### ISSUE THREAD

**Issue by thomasbuesser** [Cacti/cacti#3175]
If you have a SNMP-Device that gives you a "WRONG Type" Answer for a SNMP-Query. Spine removes trailing characters from the answer. 

**To Reproduce**
1. do SNMP-Query on Host: (Answer should look like that):
IF-MIB::ifHCInOctets.167862272 = Wrong Type (should be Counter64): Hex-STRING: 00 00 00 02 41 CF B4 DC 

2. debug answer in snmp.c from spine ~line 700
3. debug answer after 
snprintf(snmp_oids[i].result, RESULTS_BUFFER, "%s", trim(strip_alpha(temp_result)));
4. compare values in temp_result <-> snmp_oids[i].result

Server-OS is FreeBSD 12.1-RELEASE-p1
Cacti / Spine-Release 1.2.7

**Comment by bmfmancini** [comment]
I think this should be moved to the Spine repo

**Comment by thomasbuesser** [comment]
you are right... done!
