### ISSUE TITLE
Graph generation fails when switching Data Source Profile？

### ISSUE THREAD

**Issue by zhangjian420** [Cacti/cacti#3179]
Ver 1.2.8
Poller-type:SPINE
Poller Interval:Every Minute
And add crontab for 1 minute 。
![1](https://user-images.githubusercontent.com/293321/72216762-59538600-3560-11ea-862a-59e3924ed207.jpg)
I have created a graphic of Traffic In / Out. And the Data Source Profile in the data source defaults to 1 minute
![2](https://user-images.githubusercontent.com/293321/72216800-b94a2c80-3560-11ea-8a1d-20bfe34d2738.jpg)
Now I want to change it to 5 minutes, so I changed the Data Source Profile to 5 minutes。The modified graphic is not generated, so I traced the code and found the data_source_profile_id in the data_template_data table is changed to 1, but the rrd_step is still 60 seconds.
![3](https://user-images.githubusercontent.com/293321/72216969-121ac480-3563-11ea-8682-61df1428e719.jpg)

After I turned on the data source debugging mode, the results are as follows:
![4](https://user-images.githubusercontent.com/293321/72216867-c1569c00-3561-11ea-9ecd-d7f955dc9562.jpg)

I still used the `rrdtool info 192_168_1_211_traffic_in_66.rrd | grep step` command to check the graphics information, and found that the step was still 60 seconds
![5](https://user-images.githubusercontent.com/293321/72216894-0a0e5500-3562-11ea-847d-eef32637d602.jpg)

Then use the command `rrdtool tune 192_168_1_211_traffic_in_66.rrd --step 300` to manually change the step to 300 seconds without success.
![6](https://user-images.githubusercontent.com/293321/72216953-d1bb4680-3562-11ea-9e13-69adfbc3ab71.jpg)

**Comment by netniV** [comment]
If you change the profile, you must remove and recreate the graph.  This is because you can't easily change the step within an RRD once it is created.

**Comment by TheWitness** [comment]
You might want to try the splice command in the cli directory, but I have not ever tested it with decreased granularity.

**Comment by cigamit** [comment]
I think it should work.  Right now though, we don't officially support changing an existing RRDfile to a different profile on the fly.  I'm surprised you were able to do it.  Let us know the exact steps please.

The work-around for now is to use the rrd_splice.php CLI script.  You first though need to create the new RRDfile with the correct granularity.  You can do this by simply moving the old file out of the way, and after 5 minutes, cacti will re-create the RRDfile (if you have boost running, you may have to view the graph if you are in a hurry).

Then, having the old and new RRDfiles available, run the following:

```console
php -q splice_rrd.php --oldrrd=old_file.rrd --newrrd=new_file.rrd --finrrd=somenewfile.rrd
```

If it completes error free, you can simply copy that file back over the new_file.rrd.  Make sure you keep your permissions proper, and make sure, if you have PHP, that it's 5.4+ and the SQLite PHP extension is installed.

**Comment by cigamit** [comment]
In Cacti 1.3, we may allow things like this from the CLI, but since it's very CPU intensive, it's not something you want to do in batch from the UI.
