### ISSUE TITLE
When configuration file is unreadable, Cacti shows database connection errors if non defaults are needed

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#3181]
**Describe the bug**
When the include/config.php is unreadable, Cacti reports a database connection error if non defaults are needed.

**To Reproduce**
1. Create Cacti Database/User as something other than 'cactiuser' on localhost
2. Set permissions on config.php to be unreadable
3. Launch cacti website or cli program

**Expected behavior**
Cacti should report that the configuration file is unreadable as other settings may also be unset as a result.

**Comment by cigamit** [comment]
@netniV, isn't this one fixed already?

**Comment by netniV** [comment]
I believe that it was. I thought it was in the  CHANGELOG already but I’d have to look

**Comment by netniV** [comment]
When i looked on my phone it didn't show the commit but it is above.
