### ISSUE TITLE
Cacti 1.2.8 - Installer returns false positive results for binary location of spine as well as spine config file

### ISSUE THREAD

**Issue by browniebraun** [Cacti/cacti#3185]
File detection for Spine binary under default path (/usr/local/spine/bin/spine) returns a green flag although it has been installed under a different location. 
Similar result for detection of configuration file for Spine: Marked green while input field stays empty.

Due to the fact that Spine is optional it should only be green if no path for the binary itself has been provided.

**Comment by browniebraun** [comment]
Mark,
I know, but we flag a missing path for Spine red under settings, so it is some kind of logical break from my point of view. 
And if a path is given to the installer it should be checked and verified in that case.

**Comment by netniV** [comment]
I did have it handling that way once upon a time then it was changed by @cigamit as he felt it broke something else.  I'm being vague as I don't really recall why.
