### ISSUE TITLE
Feature: rra path should be configurable

### ISSUE THREAD

**Issue by mikygee** [Cacti/cacti#3187]
Hello,

The rra_path should be configurable in include/config.php and/or in GUI
I use the path /data/rra (which is on a different disk than where cacti lives)

To reach this goal I have to modify $config['rra_path'] = '/data/rra'; in include/global.php

So the expected behavior is to have $config['rra_path'] = 'rra'; in include/config.php by default

Thanks

**Comment by TheWitness** [comment]
Seems reasonable.

**Comment by netniV** [comment]
No, I was thinking that as I read it.  Of all the configurable paths, this is not one of them.
