### ISSUE TITLE
1-Minute polling should be supported and enabled by default

### ISSUE THREAD

**Issue by CapitalF** [Cacti/cacti#319]
Feature request.

1-minute collection is not supported by default because the "Presets -> Data Profiles -> System Default" Data Source Profile does not include an appropriate RRA, and the Polling Interval default is set for 5 minutes.

The year is 2017. I first started using 1-minute polling over a decade ago. WTF.

**Comment by browniebraun** [comment]
It depends on what you're monitoring - not everything has changed in 2017 :)
Btw, I use to have a 5 minute granularity for 100 days and 30 minute granularity for 400 days. That's not in presets, too. Or using your words: WTF.

**Comment by cigamit** [comment]
I tend to agree with Mr. F.  Capital F.  It was actually missed in the initial release.  Either way, it's an enhancement.  So, the real question is what does the 'F' stand for?

**Comment by cigamit** [comment]
Resolved by adding 30 second High Collection Rate example in cacti.sql.
