### ISSUE TITLE
Themes not working in cacti 1.2.8

### ISSUE THREAD

**Issue by armend-i** [Cacti/cacti#3190]
After upgrading Cacti from version 1.2.5 to 1.2.8, Cacti tree view shows empty, everything else looks ok, while upgrading no error has been encountered, devices and tree are available and when in preview mode they are visible with all the data on it, when enetering technical support within cacti it shows that paths are ok, in error log there is no error, and when trying to change theme, it does not change no matter what, only when logging out it changes the login theme but nothing more, has anyone else experienced something similar?

Thanks for any help!

Found the issue, I just had to change the theme on my profile and not i general settings, now everything looks as it should, if anyone experiences the same issue this is the solution!

**Comment by danfiscus** [comment]
I'm glad someone posted this, I was wondering about this too! Still, the general settings page should be able to change the theme, since it has an option for that, no? I could be wrong but this does seem like it counts as a bug

**Comment by netniV** [comment]
No this is not a bug but by design. The general settings is the default. Once a user has logged in, they have all their own settings copied from the defaults and these are found on the user profile menu option which is separate to settings. 

This may change in the future but for now works as described.

**Comment by armend-i** [comment]
I agree netniV, except that after the installation this should not have affected any user profile, I'm not saying that this is a huge issue, just that, if after upgrade, others are not able to view the tree graphs, they should log in and change user profile theme, and it could happen that at first it doesn't work, yet try 2 times, clear browser cache and that should do it.
P.S: I'm not complaining only noticing and letting others know.

Have a good one ;)

**Comment by TheWitness** [comment]
The tree issue will be fixed in 1.2.29.  I've been thinking that things like domain, and preferred user themes should be saved in local storage in addition to the database so that the login screen matches your desired profile.

**Comment by majed17** [comment]
just now, i upgraded to 1.3.0-dev (it didn't ask to got through the upgrade proceedure like 1.2.10 does)
i tried upgrading because we changed the theme to cacti in a user's profile, and now the cacti theme is everywhere and can not be changed even in general settings also.
