### ISSUE TITLE
Add ability to change options in AUTOM8 networks

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3192]
Hey Guys 

one option that would be nice to have is the ability to make changes to all of the networks in AUTOM8 at once 

i.e if you want to change the notification email or thread count you should be able to select all of the networks then have the option to change network settings 

Things that I can think of are 

- Change Notification email
- Change Reachability options i.e SNMP instead of ICMP
- Modify all of the switche options like re-run data queries  etc

Thank guys !

**Comment by cigamit** [comment]
Yea, that's a good idea.
