### ISSUE TITLE
Starting with MySQL 5.7 some sql_mode variables are required for some plugins

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#3193]
**Describe the bug**
Starting with MySQL 5.7 you must a set a new sql_mode to set a date of '0000-00-00'.  This needs to be a part of the base API.  The variables is ALLOW_INVALID_DATES.

**Expected behavior**
Any plugin that used a default date of '0000-00-00' will be impacted without this change.

**Comment by netniV** [comment]
That is a quick fix for now which gets over the hurdle.  I would rather see valid dates or null imho in the date since no other system will cope with that date.
