### ISSUE TITLE
cacti 1.2.8 meets Safari Version 13.0.5 (15608.5.6) in MacOS Catalina 10.15.3 Public Beta 2

### ISSUE THREAD

**Issue by ibatten** [Cacti/cacti#3195]
Updated to 10.15.3 Public Beta 2 from 10.15.3 Public Beta 1.

Graphs no longer display, giving error shown in attachment (they were fine with 10.15.3 public beta 1)
<img width="326" alt="Screenshot 2020-01-16 at 21 22 40" src="https://user-images.githubusercontent.com/7934081/72564013-c3449600-38a6-11ea-8990-e6b9500a5da3.png">
.   Independent of Content-Security-Policy.

I have "Disable Local File Restrictions" selected.  

My guess would be that something has changed in the Safari security model (everything still works in Chrome) but this will be a problem for cacti if Safari/cacti are still fighting when 10.15.3 ships.

Edit to add: I can make the graphs display again by selecting "Disable Cross-Origin Restrictions".

**Comment by TheWitness** [comment]
Pull lib/html.php from the 1.2.x branch and see if that resolves the issues.

**Comment by cigamit** [comment]
Yea, agree with the new meta tags, you should have better luck.

**Comment by netniV** [comment]
I have a mac running public betas, so I'll try this out myself over the weekend.

**Comment by TheWitness** [comment]
My guess is that Safari is applying a default content-security-policy now if the site does not already have it's own defined.

**Comment by ibatten** [comment]
No, with the suggested version installed (and checked: I looked at the source in the browser to confirm that the meta CSP was being delivered) the same situation arises: you need to tick the Developer "Disable Cross-Site Protections" option to get graphs to render.

**Comment by ibatten** [comment]
The Content-Security-Policy needs "blob:" as well as "data:".   With that change, the 1.2.x branch version fixes the original bug.  Around line 2304:

        <meta http-equiv="Content-Security-Policy" content="default-src *; img-src 'self' data: blob:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline';">

As an additional problem, using the 1.2.x branch html.php (either as pulled, or with my above change) breaks the "drag out a region, zoom" functionality, both in the latest Safari bits and latest Chrome bits.  I have a student working on Content-Security-Policy I shall ask on Monday if I can't fix it myself :-)

**Comment by TheWitness** [comment]
Thanks for that.   There are a few additional updates you have to make to remove the use of evals().  Those include all the theme main.js and the jquery.zoom.js file.  Once those are in and re-loaded into the browsers memory, zoom will start working again.

**Comment by ibatten** [comment]
Thanks for the feedback.  My enthusiasm for living on the edge is only occasional, so as zoom works with the unsafe-eval CSP I have put in there, I will wait for the 1.2.9 release which will presumably bundle up all the required changes.  Thanks for all your work!

**Comment by TheWitness** [comment]
No problem.  We should have it out by the end of the month.

**Comment by ibatten** [comment]
OK, bad news...this morning the problem is back.  My bad, I think: I tested by turning the "Disable Cross Site Protection" checkmark on and off, but I guess that there might be something sticky about it: with a fresh copy of Safari, the problems (both the failure to render graphs, and then once I have turned the Disable option on the failure to zoom) are both back.

It's madness for Apple to ship something which changes browser semantics this severely midway through the beta cycle of a dot release, but there you go...

**Comment by TheWitness** [comment]
Test out the latest include/global.php.  I've basically replicated the whole thing for every page including callbacks.

**Comment by ibatten** [comment]
The 1.2.x branch global.h doesn't seem to help.

I suspect we aren't the only people seeing this issue, for example: https://github.com/eXist-db/dashboard/issues/122

It's possible it's a Safari bug.  I can't see how rejecting a data: image is correct behaviour when there is an explicit image-src data: entry in the Content-Security-Policy.

**Comment by ibatten** [comment]
Yes, I believe that the problem happens with 19D62e, aka Public Beta 2, but not with 19D49f, aka PB1.   I ran 19D49f for some weeks with no (cacti) issues.

I suspect it's Safari Version 13.0.5 (15608.5.6) that is the issue, but as I don't have a machine running 19D49f to hand I can't check they bumped the version number on Safari.  I rather hope they did, given the scale of this change.

**Comment by netniV** [comment]
My safari version is Version 13.0.5 (15608.5.5) so yes, it looks like they bumped it up a minor build.  Strange that a tiny revision is giving a big issue.

**Comment by ibatten** [comment]
Rendering appears to be fixed in 19D75a, Public Beta 3, with Safari 15608.5.11.  Time zoom still does not work, but I will need to pick through exactly what bits I am running to see what causes that.

**Comment by cigamit** [comment]
Yea, you need to update the include/js/jquery.zoom.js file.  There were some eval() in the code that have been removed.  I'm going to close this one now.  Thanks for keeping us in the loop!
