### ISSUE TITLE
Steps to install cacti in cpanel account

### ISSUE THREAD

**Issue by rajkumargkn** [Cacti/cacti#3198]
Hi there,

Trying to install cacti under the Cpanel account.  when we access the cacti link we get following error.

Gateway Timeout
The gateway did not receive a timely response from the upstream server or application.

Additionally, a 504 Gateway Timeout error was encountered while trying to use an ErrorDocument to handle the request.

Is there any steps to install cacti under Cpanel server

Regards

**Comment by netniV** [comment]
How did you add it in the first place?

**Comment by rajkumargkn** [comment]
Hello Netniv, 

Thank you for your response.
 
Just downloaded cacti 1.2.8 and uploaded in to cpanel  user directory and tried to access the url via browser to continue the installation.... 

After changing the password just loads for few minutes and getting the error... 
Awaiting for your reply.... 

Regards.

**Comment by cigamit** [comment]
I'd like to see some screen shots of what you are experiencing and what you expect to see.

**Comment by rajkumargkn** [comment]
Hello there, 

Here is the screenshot for the error.

http://puu.sh/F1wcq/e39e8fd78c.png
http://puu.sh/F1was/8ca21a737c.png
http://puu.sh/F1wdm/e7bd717409.png


Thanks.

**Comment by TheWitness** [comment]
Seems to me you have to get behind the covers on this one.  Review the apache error log for example, if it's empty, turn on php logging by editing the php.ini file and un-commenting and changing the error_log=/tmp/php_errors.log.

**Comment by rajkumargkn** [comment]
Hello There,

Thank you for your guidance, 

I manage to resolve the issue, now I am stuck in the Cpanel PHP modules.  Please refer to the screen capture and do let us know how to load Cpanel PHP modules.

http://puu.sh/F2klS/b316bf31b2.png
http://puu.sh/F2kms/518a5ac451.png

Thanks in advance

**Comment by netniV** [comment]
There’s two reasons for that. One is that you have two versions of PHP that are running, one for the web and one for CLI stuff with their own ini files that both require the modules. 

The other is that you are pointing at a binary that isn’t actually PHP. as of 1.2.9 we now set the default location in more ways including an environment var of PHP_BINDIR and that will be the default location set by the installer. 

If you override that, the setting path_php_binary will be used from the database.

**Comment by cigamit** [comment]
Going to close this one.  Seems more of a local configuration issue that should be resolved in the forums.
