### ISSUE TITLE
Cacti boost not graphing - php errors

### ISSUE THREAD

**Issue by eholz1** [Cacti/cacti#3199]
I have enabled boost for a cacti-1.2.8 installation.
300 devices - prior to enabling boost - all was well, clean cacti.log and getting data in graphs.
Boost failing PHP call in poller_boost.php

**To Reproduce**
1.Enable boost in the cacti GUI
2. Let it run for a while - approx 10 to 15 minutes
3. Get this error repeatedly - like 20mb in a boost.log file
2020/01/17 09:40:33 - ERROR PHP WARNING: unlink(modern_lgi_26_rrai_0_tsi_1_height_240_width_850.png): Permission denied in file: /opt/rh/httpd24/root/var/www/cacti-1.2.8/poller_boost.php on line: 728  
2020/01/17 09:40:33 - CMDPHP PHP ERROR WARNING Backtrace: (/poller_boost.php[176]:purge_cached_png_files(), /poller_boost.php[728]:unlink(), CactiErrorHandler())  
2020/01/17 09:40:33 - ERROR PHP WARNING: unlink(modern_lgi_150_rrai_0_tsi_2_height_240_width_850.png): Permission denied in file: /opt/rh/httpd24/root/var/www/cacti-1.2.8/poller_boost.php on line: 728  
2020/01/17 09:40:33 - CMDPHP PHP ERROR WARNING Backtrace: (/poller_boost.php[176]:purge_cached_png_files(), /poller_boost.php[728]:unlink(), CactiErrorHandler())  
2020/01/17 09:40:33 - ERROR PHP WARNING: unlink(modern_lgi_25_rrai_0_tsi_1_height_240_width_850.png): Permission denied in file: /opt/rh/httpd24/root/var/www/cacti-1.2.8/poller_boost.php on line: 728  

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bmfmancini** [comment]
Looks like some sort of permissions issue what user are you running cacti
with ?

**Comment by eholz1** [comment]
Hello cigamit,

Correct - I carefully reviewed the required permissions, still not quite sure which user (cacti and/or apache) need the rights - be allowed both users to write, and that fixed the issue. The error message was not quite clear to me as where to look.

Thanks for the suggestion - it allowed me to recheck permissions and directories.

ewholz
