### ISSUE TITLE
Users can not change their own password

### ISSUE THREAD

**Issue by CapitalF** [Cacti/cacti#320]
Apparently the Admin user can not change his own password? Either disable password changing for the admin user or add some kind of notice, or this is a bug.

Cacti 1.0.3 on Linux. Browser used is Chromium on Linux.

**Comment by pautiina** [comment]
I do not know why you can not change the password, but my Cacti version 1.0.3 is changing. For admin account and for other users is work.

**Comment by CapitalF** [comment]
I just reproduced this again. It's definitely a problem for me.

This is a newly installed installation (started with 1.0.2, now on 1.0.3).

Log into the Cacti site with the "admin" account.

Click on the "Login in as admin" drop-down menu in the upper-right corner of the screen (Modern theme).

Select "Change Password" (auth_changepassword.php).

The following error is given, even with valid input:

"Your current password is not correct. Please try again."

Also interesting is that the "Change Password" item on the drop-down menu is missing on my other non-admin account. If I manually load that auth_changepassword.php page on another non-admin user, I am logged out immediately without the Change Password page loading.

Auth method is local/built-in. No weird configurations.

**Comment by jpobeda** [comment]
I upgraded from 1.0.2 to 1.0.3 and it works fine for me.

**Comment by pautiina** [comment]
@CapitalF Try click on user settings:
![15](https://cloud.githubusercontent.com/assets/11805503/23204237/6f908456-f8ee-11e6-919c-be92235bcc47.png)

**Comment by CapitalF** [comment]
Confirmed that the regular user account did not have the "Change Password" button active, so that explains why this user could not change their own password. After testing, this seems to be the default for new accounts, which is very questionable. Actively preventing users from managing their own passwords seems security ignorant. A workaround is that you can create a User Template, which is a nice feature.

Now that I can test the Change Password page on the regular user, I find that it too is unable to change it's password with the same error as mentioned above, so the problem is not only limited to the Admin user like originally assumed.

Right now I suspect that having changed some of the "Local Account Complexity Requirements" may have caused this, but I am uncertain and don't have time to test further right now.

While we are here, there is a problem with mouse hovering over the question mark on the auth_changepassword.php page: "Must be at least characters in length". The number variable is not being expanded.

**Comment by CapitalF** [comment]
Title has been updated acordingly

**Comment by cigamit** [comment]
Changed the default to 'on' or checked.  Thanks for pointing this out.  Closing.
