### ISSUE TITLE
Reopen 3195: Content-Security-Policy issues

### ISSUE THREAD

**Issue by ibatten** [Cacti/cacti#3202]
OK, bad news...this morning the problem is back. My bad, I think: I tested by turning the "Disable Cross Site Protection" checkmark on and off, but I guess that there might be something sticky about it: with a fresh copy of Safari, the problems (both the failure to render graphs, and then once I have turned the Disable option on the failure to zoom) are both back.

It's madness for Apple to ship something which changes browser semantics this severely midway through the beta cycle of a dot release, but there you go...

C-S-P shipped in the graph page is as follows:

meta http-equiv="Content-Security-Policy" content="default-src *; img-src 'self' data: blob:; style-src 'self' 'unsafe-inline' 'unsafe-eval'; script-src 'self' 'unsafe-inline' 'unsafe-eval';"

There is no C-S-P being added by the webserver.

Console and main display attached.
<img width="1256" alt="Screenshot 2020-01-19 at 13 01 13" src="https://user-images.githubusercontent.com/7934081/72681469-dbd9c980-3abb-11ea-81e5-1ea18a25ae19.png">
<img width="1433" alt="Screenshot 2020-01-19 at 13 01 27" src="https://user-images.githubusercontent.com/7934081/72681471-dc726000-3abb-11ea-9081-f5acc7e06e26.png">

**Comment by TheWitness** [comment]
We may have to add it to every header.  You might want to open a bug with Apple too.

**Comment by netniV** [comment]
We should close this and keep the other one open until we are sure it’s resolved.

**Comment by TheWitness** [comment]
Agreeing.
