### ISSUE TITLE
Converted aggregate graph cannot be edited

### ISSUE THREAD

**Issue by hp619** [Cacti/cacti#3206]
A converted aggregate graph cannot be edited via the web UI. As soon as the edit form is submitted, the graph breaks.

1. Convert existing aggregate graph to normal graph
2. Visit edit view of converted graph
3. Hit the save button
4. Graph preview and edit view is different

Part of edit view and graph before:
![agg_fine](https://user-images.githubusercontent.com/59609312/72745488-29cff980-3bb0-11ea-8ea5-1614d1c398dc.png)

Edit view and graph after hitting save:
![agg_broken](https://user-images.githubusercontent.com/59609312/72745163-6b13d980-3baf-11ea-9ddc-9cd4a6d19c9f.png)

This issue occurs on v1.2.8 (also observed in 1.2.7, can't say for previous versions)

**Comment by TheWitness** [comment]
The graph will disappear from the Aggregate interface, you must search for Device 'None' from Graph Management.

**Comment by TheWitness** [comment]
Can you update to 1.2.9 and see if you can repeat this?

**Comment by TheWitness** [comment]
Oh, I just reproduced.

**Comment by TheWitness** [comment]
This should be fixed now.  Just update graphs.php from the 1.2.x branch.

**Comment by hp619** [comment]
Can confirm it's working fine now. Very nice, thanks!
