### ISSUE TITLE
Error in Percona MYSQL monitoring data collection/graph

### ISSUE THREAD

**Issue by KnoAll** [Cacti/cacti#3208]
**Describe the bug**
I"m seeing an interesting issue with the Percona MYSQL monitoring. I've gotten this to work on older versions of Cacti (1.2.1 and 1.2.3) and it continues to work on 1.2.8 when the template is already installed on an earlier version that is then upgraded (1.2.3 > 1.2.8 for example) When I install the template on 1.2.8 for the first time I do not get data.  In doing a device debug I can see a difference in the how the data is being gathered.

Working in 1.2.3:
2020/01/21 08:12:03 - SPINE: Poller[Main Poller] PID[796] Device[Percona] HT[1] DS[Percona - MySQL Threads] Graphs[Percona - MySQL Threads] SCRIPT: /bin/php -q /var/www/html/cacti/scripts/ss_get_mysql_stats.php --host 'localhost' --items it,iu,iv,iw,iy --user --pass --port --server-id , output: it:0 iu:30 iv:34453 iw:1 iy:0

Not working in 1.2.8:
2020/01/21 07:32:09 - SPINE: Poller[Main Poller] PID[10431] Device[Percona] HT[1] DS[Percona - MySQL Threads] Graphs[Percona - MySQL Threads] SCRIPT: /usr/bin/php -q /var/www/html/cacti/scripts/ss_get_mysql_stats.php --host 'localhost' --items it,iu,iv,iw,iy --user '' --pass '' --port '' --server-id '', output: it:-1 iu:-1 iv:-1 iw:-1 iy:-1

It appears that in the non-working situation it is passing '' as part of the query whereas it does not do this on the working instance.
--user '' --pass '' --port '' --server-id ''

**To Reproduce**
1. Install Percona MYSQL on earlier version of Cacti (1.2.1 and 1.2.3 tested) 
2. Setup new device and add Percona graphs
3. After successful data graphed, upgrade to 1.2.8, still getting good data.

A. Install Percona MYSQL on 1.2.8
B. Setup new device and add Percona graphs
C. No data gathered and graphs blank.

**Expected behavior**
Should be able to install Percona directly into v1.2.8 and get data and graphs?

**Screenshots**
![image](https://user-images.githubusercontent.com/7632685/72834923-a3aec400-3c3e-11ea-864b-b1968e5e159b.png)

**Desktop (please complete the following information):**
 - OS: CentOS7 and Raspbian Buster
 - Browser: Chrome, Firefox

**Additional context**
Have tried several variations to troubleshoot. different PHP versions 7.1, 7.4, different levels of CentOS7, 7.3, 7.4.
Have tried upgrading v1.2.8 to v1.3.0.-1 as well with similar results.

**Comment by TheWitness** [comment]
Check edit your Data Sources and verify that the database user and passwords are filled in.  Since the arguments are being escaped now, they are showing up empty in the script.  So, the script may just need some updates to compensate for that.

**Comment by TheWitness** [comment]
Upload the script here.

**Comment by KnoAll** [comment]
I have tried updating the data source template to include those values with no luck.
![image](https://user-images.githubusercontent.com/7632685/72947187-1e0e3f80-3d36-11ea-948d-9ea62d5804c6.png)

2020/01/22 16:41:03 - SPINE: Poller[Main Poller] PID[5202] Device[Percona] HT[1] DS[Percona - MySQL Transaction Handler] Graphs[Percona - MySQL Transaction Handler] SCRIPT: /bin/php -q /var/www/html/cacti/scripts/ss_get_mysql_stats.php --host 'localhost' --items mm,mw,mx,my --user '' --pass '' --port '' --server-id '', output: mm:-1 mw:-1 mx:-1 my:-1


[ss_get_mysql_stats.txt](https://github.com/Cacti/cacti/files/4100766/ss_get_mysql_stats.txt)

**Comment by TheWitness** [comment]
Do you have the old version still online anywhere?  If so, look at the poller cache and see if the user and password were missing from that version.  Also, post the data input method edit screen.  It seems that the ss_mysql_stats.php has some defaults, and then the parameters passed override those defaults.  In your case, since they are not escaped, they are overriding with blanks.  So, the connection is breaking.

**Comment by TheWitness** [comment]
It's odd though that you have those values there.  Can you 'resave' the Device and then look at the poller cache to see if the records have the right values after that save?

**Comment by KnoAll** [comment]
I do have the working older version of Cacti still online.  It is a VM that i use for testing these types of things. 

Here is the corresponding poller cache from the working system.

Script: /bin/php -q /var/www/html/cacti/scripts/ss_get_mysql_stats.php --host 'localhost' --items mm,mw,mx,my --user --pass --port --server-id
--

I tried doing the save the device with the same results...

Script: /bin/php -q /var/www/html/cacti/scripts/ss_get_mysql_stats.php --host 'localhost' --items mm,mw,mx,my --user '' --pass '' --port '' --server-id ''
--

**Comment by TheWitness** [comment]
Quick fix is to change line 234 to this:

```code
 if ($value != '') $options[$param] = $value;
```

But you should export the device template ant post it here including dependencies so we can review it for errors since between those single quotes there should be values.

**Comment by KnoAll** [comment]
[mysql-template.txt](https://github.com/Cacti/cacti/files/4101209/mysql-template.txt)

**Comment by KnoAll** [comment]
> 
> 
> Quick fix is to change line 234 to this:
> 
> ```
>  if ($value != '') $options[$param] = $value;
> ```
> 
> But you should export the device template ant post it here including dependencies so we can review it for errors since between those single quotes there should be values.

Apologies, in which file should i change line 234?

**Comment by KnoAll** [comment]
Apologies again, found what you meant in the script. Made your suggested quick fix and now pulling stats as indicated.

**Comment by netniV** [comment]
This is something I found previously with the Percona scripts, unfortunately they decided that they aren't supporting them anymore if I remember rightly.

**Comment by netniV** [comment]
Yup, I was right, I tried to patch that a long time ago!
https://github.com/percona/percona-monitoring-plugins/pull/98/files

**Comment by KnoAll** [comment]
Thanks for the help on this. It is working as expected now. 

I did find another (admittedly edge case) issue with remote polling. I have rPi remote pollers but my main poller is centos. The template calls for <php_path_binary> which breaks between the main and remote pollers as the path is different. /bin/php vs /usr/bin/php. Edited the template to just stipulate php and all is well.

**Comment by netniV** [comment]
The path variables should really always be local to the poller in question.

**Comment by KnoAll** [comment]
I would have thought but that is not what I was seeing in the logs/cache
