### ISSUE TITLE
Modernize Tree View graph sizes

### ISSUE THREAD

**Issue by CapitalF** [Cacti/cacti#321]
Feature request.

The current default graph width seems to be 600, but the minimum page width in "Tree View" requires a window width that would support at least a graph width of 750. This is somewhat dependent upon font widths on the "Graph Filters" area, but I suspect the default graph width should be increased to at least 700, and maybe 750. This eliminates wasted whitespace. The situation is even worse for those who use small font sizes; a default graph size of 900 or 1000 might be appropriate. Maybe there are some reasons to keep the graph width smaller, but I don't know what they are.

I would suggest there is a need to modernize the default size of graphs.

**Comment by camerabob** [comment]
In version 1.0.x: Go to Settings > General (tab) > Other Defaults (area)
See below areas:

Graph Template Height
The default Graph Width to be used for all new Graph Templates.
Graph Template Width
The default Graph Width to be used for all new Graph Templates.

**Comment by cigamit** [comment]
There is also an option under Console -> Templates -> Graph.  To resize all Graph Templates, which will also resize all graphs.  I was thinking it might be a good idea to autosize the width of graphs as we do in thumbnails.  That is also possible with the updated framework.  If you would like that, please open an enhancement request with that subject.  Thanks!
