### ISSUE TITLE
Allow Automation Rules to place newly discovered devices on an already-existing subtree

### ISSUE THREAD

**Issue by danfiscus** [Cacti/cacti#3211]
**Is your feature request related to a problem? Please describe.**
I have a large number of automated network scans with plenty of automation rules that apply the correct templates and graphs, but I have not found a way to use a rule to place items on a subtree automatically. Automation Tree Rules doesn't seem robust enough to do what I would like.

**Describe the solution you'd like**
I would like to be able to create a single rule that looks for a specified string and places the item on a tree with a matching string. For example, let's say I want all devices with an SNMP description ending in "ell.net.domain.edu", ".ell", or "ell.NEW.net.domain.edu" to automatically place themselves on a subtree titled "ELL - VLAN". Now, all I need is a system to do that automatically with any three-letter combination, so instead of "ell.net..." going to "ELL VLAN", the same rule would also take care of "mct.net" on a subtree called "MCT VLAN" and so on.

**Describe alternatives you've considered**
Currently, I have an automation tree rule for each subtree VLAN that is supposed to add matching devices to that VLAN's subtree. But we have hundreds of VLANs in use and I would really prefer not to create hundreds of individual tree rules. Not to mention, I can't seem to figure out how to get the rules I do have to work, I'm new to Cacti so perhaps I am missing something but this solution hasn't worked for me yet.

**Additional context**
We have a few hundred VLANs in use, device descriptions contain a three-letter abbreviation that corresponds to the building the device is in, and I have a subtree for each building with a name that starts with the same abbreviation

**Comment by bmfmancini** [comment]
YES!!! This would be awsome

**Comment by bmfmancini** [comment]
Actually, wait ... Have you considered making a tree for the devices you want to group together then make a tree rule that matches that description to attach to the tree ? 

That is what I do to group similar devices together what would be nice is a more intuitive way for cacti to detect one hostname is similar to

**Comment by bmfmancini** [comment]
The only other way I could think of is that cacti groups similar devices together unsupervised ?

**Comment by netniV** [comment]
OK so it sounds like you are asking for regex style replacement on the rules, but I doubt it would involve changing the case as I don't know many regex that support that.

**Comment by cigamit** [comment]
This almost sounds like a bug.

**Comment by cigamit** [comment]
If @gan-dalf would just stop wood working for a year or two and come back to Cacti, this would be solved already.  Long live @gan-dalf!

**Comment by danfiscus** [comment]
@bmfmancini Okay I'm back in the office now, I have some time to test your idea out. You're recommending (at least as a temporary solution) to use a separate tree for each VLAN/building and use automation rules to set those automatically, is that correct?

**Comment by TheWitness** [comment]
The rules already support regular expression matching and replacement, simply not case, and as far as I'm concernted, will add Graphs and Devices to existing Trees and Branches.  So, closing this one.
