### ISSUE TITLE
Remote Data Collector install/upgrade should fail if Remote Data Collector is a newer release

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#3214]
**Describe the bug**
If you attempt to upgrade or install a remote data collector, and that remote data collector is a more recent version of cacti, it should be blocked.

**To Reproduce**
1. Install main Cacti collector at version 1.2.8
2. Attempt to install a remote data collector at version 1.2.9
3. Bad things start to happen including installer failures

**Expected behavior**
Newer remote data collector installs should be blocked.

**Comment by cigamit** [comment]
Yea, I see how that could be bad.

**Comment by netniV** [comment]
The problem we have here is whether the main connection is online or not.  IF the connection is not online, do we block installation completely?

**Comment by cigamit** [comment]
This makes sense.  Right now anyway, we have to be able to connect to the main data collector to complete the install.  In 1.3, it would be fine if we allowed remote data collectors to self register.  That way, you could spin up docker images and have the auto-register.  For this release anyway, let's block.

**Comment by netniV** [comment]
This is still work in progress

**Comment by TheWitness** [comment]
This is fixed in the develop Branch now so I'm going to go ahead and close this.
