### ISSUE TITLE
cacti installation got stopped at 41% with below issue;

### ISSUE THREAD

**Issue by praveenyeragani** [Cacti/cacti#3219]
below is the status of installation...

Cacti Server v1.2.8 - Installation Wizard
Installing Cacti Server v1.2.8
Your Cacti Server is now installing

Refresh in	 	ProgressLast updated: 05:48:45
 	
41 %
2020/01/27 05:48:45 - INSTALL: always: About to import Package #1 'Cacti_Stats.xml.gz'.
2020/01/27 05:48:45 - INSTALL: always: Found 6 templates to install
2020/01/27 05:48:45 - INSTALL: always: No tables where found or selected for conversion
2020/01/27 05:48:45 - INSTALL: always: Starting INSTALL Process for v1.2.8
2020/01/27 05:48:36 - INSTALL: always: Setting PHP Option memory_limit = -1
2020/01/27 05:48:36 - INSTALL: always: Setting PHP Option max_execution_time = 0
2020/01/27 05:48:36 - INSTALL: Checking arguments
2020/01/27 05:48:35 - INSTALL: always: Spawning background process: C:/cacti/php/php.exe "C:/cacti/Apache24/htdocs/cacti/install/background.php" 1580132915.5599
2020/01/27 05:23:33 - INSTALL: always: About to import Package #1 'Cacti_Stats.xml.gz'.
2020/01/27 05:23:32 - INSTALL: always: Found 6 templates to install
2020/01/27 05:23:32 - INSTALL: always: No tables where found or selected for conversion
2020/01/27 05:23:31 - INSTALL: always: Starting INSTALL Process for v1.2.8
2020/01/27 05:23:24 - INSTALL: always: Setting PHP Option memory_limit = -1
2020/01/27 05:23:24 - INSTALL: always: Setting PHP Option max_execution_time = 0
2020/01/27 05:23:24 - INSTALL: Checking arguments
2020/01/27 05:23:23 - INSTALL: always: Spawning background process: C:/cacti/php/php.exe "C:/cacti/Apache24/htdocs/cacti/install/background.php" 1580131403.7383
2020/01/27 04:58:22 - INSTALL: always: About to import Package #1 'Cacti_Stats.xml.gz'.
2020/01/27 04:58:22 - INSTALL: always: Found 6 templates to install
2020/01/27 04:58:21 - INSTALL: always: No tables where found or selected for conversion
2020/01/27 04:58:21 - INSTALL: always: Starting INSTALL Process for v1.2.8
2020/01/27 04:58:14 - INSTALL: always: Setting PHP Option memory_limit = -1
2020/01/27 04:58:14 - INSTALL: always: Setting PHP Option max_execution_time = 0
2020/01/27 04:58:14 - INSTALL: Checking arguments
2020/01/27 04:58:13 - INSTALL: always: Spawning background process: C:/cacti/php/php.exe "C:/cacti/Apache24/htdocs/cacti/install/background.php" 1580129893.0832
2020/01/27 04:33:12 - INSTALL: always: About to import Package #1 'Cacti_Stats.xml.gz'.
2020/01/27 04:33:11 - INSTALL: always: Found 6 templates to install
2020/01/27 04:33:11 - INSTALL: always: No tables where found or selected for conversion
2020/01/27 04:33:11 - INSTALL: always: Starting INSTALL Process for v1.2.8
2020/01/27 04:33:05 - INSTALL: always: Setting PHP Option memory_limit = -1
2020/01/27 04:33:05 - INSTALL: always: Setting PHP Option max_execution_time = 0
2020/01/27 04:33:05 - INSTALL: Checking arguments
2020/01/27 04:33:04 - INSTALL: always: Spawning background process: C:/cacti/php/php.exe "C:/cacti/Apache24/htdocs/cacti/install/background.php" 1580128384.3651

Copyright (C) 2004-2020 The Cacti Group

**Comment by netniV** [comment]
This suggests that you are having an error with installing the stats template for some reason, more than likely environment issue that with the package itself.  Can you check your cacti error log and the php/apache error logs to see if anything is shown?

**Comment by praveenyeragani** [comment]
below is cacti log file details

2020/01/27 19:27:32 - INSTALL: always: Spawning background process: C:/cacti/php/php.exe "C:/cacti/Apache24/htdocs/cacti/install/background.php" 1580182052.7909
2020/01/27 19:27:41 - INSTALL: Checking arguments
2020/01/27 19:27:41 - INSTALL: always: Setting PHP Option max_execution_time = 0
2020/01/27 19:27:41 - INSTALL: always: Setting PHP Option memory_limit = -1
2020/01/27 19:27:50 - INSTALL: always: Starting INSTALL Process for v1.2.8
2020/01/27 19:27:51 - INSTALL: always: No tables where found or selected for conversion
2020/01/27 19:27:51 - INSTALL: always: Found 6 templates to install
2020/01/27 19:27:51 - INSTALL: always: About to import Package #1 'Cacti_Stats.xml.gz'.
2020/01/27 19:27:52 - IMPORT NOTE: Got Package Signature
2020/01/27 19:27:52 - IMPORT NOTE: File is Signed Correctly
2020/01/27 19:27:52 - IMPORT Loading Plugin Information from package
2020/01/27 19:27:52 - IMPORT Verifying each files signature
2020/01/27 19:27:52 - IMPORT NOTE: File OK: scripts/ss_poller.php
2020/01/27 19:27:52 - IMPORT NOTE: File OK: scripts/ss_poller.php
2020/01/27 19:27:52 - IMPORT NOTE: File OK: scripts/ss_poller.php
2020/01/27 19:27:52 - IMPORT NOTE: File OK: scripts/ss_poller.php
2020/01/27 19:27:52 - IMPORT NOTE: File OK: scripts/ss_poller.php
2020/01/27 19:27:52 - IMPORT NOTE: File OK: scripts/cacti_user_stats.php
2020/01/27 19:27:52 - IMPORT NOTE: File OK: scripts/ss_poller.php
2020/01/27 19:27:52 - IMPORT NOTE: File OK: scripts/ss_poller.php
2020/01/27 19:27:52 - IMPORT NOTE: File OK: scripts/ss_poller.php
2020/01/27 19:27:52 - IMPORT NOTE: File OK: scripts/ss_poller.php
2020/01/27 19:27:52 - IMPORT NOTE: File OK: scripts/ss_poller.php
2020/01/27 19:27:52 - IMPORT NOTE: File OK: scripts/ss_poller.php
2020/01/27 19:27:52 - IMPORT NOTE: File OK: scripts/ss_poller.php
2020/01/27 19:27:52 - IMPORT NOTE: File OK: scripts/ss_poller.php
2020/01/27 19:27:52 - IMPORT NOTE: File OK: scripts/ss_poller.php
2020/01/27 19:27:52 - IMPORT NOTE: File OK: resource/script_server/cpoller.xml
2020/01/27 19:27:52 - IMPORT NOTE: File OK: resource/script_server/webseer.xml
2020/01/27 19:27:52 - IMPORT NOTE: File OK: resource/script_server/gexport.xml
2020/01/27 19:27:52 - IMPORT NOTE: File OK: scripts/ss_cpoller.php
2020/01/27 19:27:52 - IMPORT NOTE: File OK: scripts/ss_webseer.php
2020/01/27 19:27:52 - IMPORT NOTE: File OK: scripts/ss_gexport.php
2020/01/27 19:27:52 - IMPORT NOTE: File OK: Cacti_Stats.xml
2020/01/27 19:27:52 - IMPORT Writing Files
2020/01/27 19:27:52 - IMPORT Writing file: C:/cacti/Apache24/htdocs/cacti/scripts/ss_poller.php
2020/01/27 19:27:52 - IMPORT Write Status file: C:/cacti/Apache24/htdocs/cacti/scripts/ss_poller.php, with Status written
2020/01/27 19:27:52 - IMPORT Writing file: C:/cacti/Apache24/htdocs/cacti/scripts/ss_poller.php
2020/01/27 19:27:52 - IMPORT Write Status file: C:/cacti/Apache24/htdocs/cacti/scripts/ss_poller.php, with Status written
2020/01/27 19:27:52 - IMPORT Writing file: C:/cacti/Apache24/htdocs/cacti/scripts/ss_poller.php
2020/01/27 19:27:52 - IMPORT Write Status file: C:/cacti/Apache24/htdocs/cacti/scripts/ss_poller.php, with Status written
2020/01/27 19:27:52 - IMPORT Writing file: C:/cacti/Apache24/htdocs/cacti/scripts/ss_poller.php
2020/01/27 19:27:52 - IMPORT Write Status file: C:/cacti/Apache24/htdocs/cacti/scripts/ss_poller.php, with Status written
2020/01/27 19:27:52 - IMPORT Writing file: C:/cacti/Apache24/htdocs/cacti/scripts/ss_poller.php
2020/01/27 19:27:52 - IMPORT Write Status file: C:/cacti/Apache24/htdocs/cacti/scripts/ss_poller.php, with Status written
2020/01/27 19:27:52 - IMPORT Writing file: C:/cacti/Apache24/htdocs/cacti/scripts/cacti_user_stats.php
2020/01/27 19:27:52 - IMPORT Write Status file: C:/cacti/Apache24/htdocs/cacti/scripts/cacti_user_stats.php, with Status written
2020/01/27 19:27:52 - IMPORT Writing file: C:/cacti/Apache24/htdocs/cacti/scripts/ss_poller.php
2020/01/27 19:27:52 - IMPORT Write Status file: C:/cacti/Apache24/htdocs/cacti/scripts/ss_poller.php, with Status written
2020/01/27 19:27:52 - IMPORT Writing file: C:/cacti/Apache24/htdocs/cacti/scripts/ss_poller.php
2020/01/27 19:27:52 - IMPORT Write Status file: C:/cacti/Apache24/htdocs/cacti/scripts/ss_poller.php, with Status written
2020/01/27 19:27:52 - IMPORT Writing file: C:/cacti/Apache24/htdocs/cacti/scripts/ss_poller.php
2020/01/27 19:27:53 - IMPORT Write Status file: C:/cacti/Apache24/htdocs/cacti/scripts/ss_poller.php, with Status written
2020/01/27 19:27:53 - IMPORT Writing file: C:/cacti/Apache24/htdocs/cacti/scripts/ss_poller.php
2020/01/27 19:27:53 - IMPORT Write Status file: C:/cacti/Apache24/htdocs/cacti/scripts/ss_poller.php, with Status written
2020/01/27 19:27:53 - IMPORT Writing file: C:/cacti/Apache24/htdocs/cacti/scripts/ss_poller.php
2020/01/27 19:27:53 - IMPORT Write Status file: C:/cacti/Apache24/htdocs/cacti/scripts/ss_poller.php, with Status written
2020/01/27 19:27:53 - IMPORT Writing file: C:/cacti/Apache24/htdocs/cacti/scripts/ss_poller.php
2020/01/27 19:27:53 - IMPORT Write Status file: C:/cacti/Apache24/htdocs/cacti/scripts/ss_poller.php, with Status written
2020/01/27 19:27:53 - IMPORT Writing file: C:/cacti/Apache24/htdocs/cacti/scripts/ss_poller.php
2020/01/27 19:27:53 - IMPORT Write Status file: C:/cacti/Apache24/htdocs/cacti/scripts/ss_poller.php, with Status written
2020/01/27 19:27:53 - IMPORT Writing file: C:/cacti/Apache24/htdocs/cacti/scripts/ss_poller.php
2020/01/27 19:27:53 - IMPORT Write Status file: C:/cacti/Apache24/htdocs/cacti/scripts/ss_poller.php, with Status written
2020/01/27 19:27:53 - IMPORT Writing file: C:/cacti/Apache24/htdocs/cacti/scripts/ss_poller.php
2020/01/27 19:27:53 - IMPORT Write Status file: C:/cacti/Apache24/htdocs/cacti/scripts/ss_poller.php, with Status written
2020/01/27 19:27:53 - IMPORT Writing file: C:/cacti/Apache24/htdocs/cacti/resource/script_server/cpoller.xml
2020/01/27 19:27:53 - IMPORT Write Status file: C:/cacti/Apache24/htdocs/cacti/resource/script_server/cpoller.xml, with Status written
2020/01/27 19:27:53 - IMPORT Writing file: C:/cacti/Apache24/htdocs/cacti/resource/script_server/webseer.xml
2020/01/27 19:27:53 - IMPORT Write Status file: C:/cacti/Apache24/htdocs/cacti/resource/script_server/webseer.xml, with Status written
2020/01/27 19:27:53 - IMPORT Writing file: C:/cacti/Apache24/htdocs/cacti/resource/script_server/gexport.xml
2020/01/27 19:27:53 - IMPORT Write Status file: C:/cacti/Apache24/htdocs/cacti/resource/script_server/gexport.xml, with Status written
2020/01/27 19:27:53 - IMPORT Writing file: C:/cacti/Apache24/htdocs/cacti/scripts/ss_cpoller.php
2020/01/27 19:27:53 - IMPORT Write Status file: C:/cacti/Apache24/htdocs/cacti/scripts/ss_cpoller.php, with Status written
2020/01/27 19:27:53 - IMPORT Writing file: C:/cacti/Apache24/htdocs/cacti/scripts/ss_webseer.php
2020/01/27 19:27:53 - IMPORT Write Status file: C:/cacti/Apache24/htdocs/cacti/scripts/ss_webseer.php, with Status written
2020/01/27 19:27:53 - IMPORT Writing file: C:/cacti/Apache24/htdocs/cacti/scripts/ss_gexport.php
2020/01/27 19:27:53 - IMPORT Write Status file: C:/cacti/Apache24/htdocs/cacti/scripts/ss_gexport.php, with Status written
2020/01/27 19:27:53 - IMPORT Importing XML Data for Cacti_Stats.xml

**Comment by praveenyeragani** [comment]
below is apache error log:
[Mon Jan 27 19:08:14.832199 2020] [mpm_winnt:notice] [pid 1888:tid 580] AH00422: Parent: Received shutdown signal -- Shutting down the server.
[Mon Jan 27 19:08:17.656217 2020] [mpm_winnt:notice] [pid 1372:tid 496] AH00364: Child: All worker threads have exited.
[Mon Jan 27 19:08:18.437795 2020] [mpm_winnt:notice] [pid 1888:tid 580] AH00430: Parent: Child process 1372 exited successfully.
[Mon Jan 27 19:09:17.050682 2020] [mpm_winnt:notice] [pid 1880:tid 676] AH00455: Apache/2.4.41 (Win64) configured -- resuming normal operations
[Mon Jan 27 19:09:17.050682 2020] [mpm_winnt:notice] [pid 1880:tid 676] AH00456: Apache Lounge VS16 Server built: Aug  9 2019 16:46:32
[Mon Jan 27 19:09:17.050682 2020] [core:notice] [pid 1880:tid 676] AH00094: Command line: 'C:\\cacti\\Apache24\\bin\\httpd.exe -d C:/cacti/Apache24'
[Mon Jan 27 19:09:17.066305 2020] [mpm_winnt:notice] [pid 1880:tid 676] AH00418: Parent: Created child process 2192
[Mon Jan 27 19:09:17.847600 2020] [mpm_winnt:notice] [pid 2192:tid 556] AH00354: Child: Starting 64 worker threads.
'-q' is not recognized as an internal or external command,
operable program or batch file.
'-v' is not recognized as an internal or external command,
operable program or batch file.
'-q' is not recognized as an internal or external command,
operable program or batch file.
'-v' is not recognized as an internal or external command,
operable program or batch file.
'-q' is not recognized as an internal or external command,
operable program or batch file.
'-v' is not recognized as an internal or external command,
operable program or batch file.
'-q' is not recognized as an internal or external command,
operable program or batch file.
'-q' is not recognized as an internal or external command,
operable program or batch file.
'-v' is not recognized as an internal or external command,
operable program or batch file.
'-v' is not recognized as an internal or external command,
operable program or batch file.
'-v' is not recognized as an internal or external command,
operable program or batch file.
'-v' is not recognized as an internal or external command,
operable program or batch file.
'-v' is not recognized as an internal or external command,
operable program or batch file.

**Comment by netniV** [comment]
Hmm, that means you have a strange PHP version being picked up.  If you look at the mysql database, what does path_php_binary point at in the settings table?

**Comment by praveenyeragani** [comment]
'path_php_binary'-'C:/cacti/php/php.exe'

**Comment by praveenyeragani** [comment]
how to resolve please help me

**Comment by netniV** [comment]
Does php.exe exist there?

**Comment by praveenyeragani** [comment]
it exists

**Comment by praveenyeragani** [comment]
is there any correct procedure to install,if yes i will do it once again

**Comment by praveenyeragani** [comment]
i installed using Cacti-1.2.8.exe

**Comment by praveenyeragani** [comment]
is there any update, using Cacti-1.2.8.exe for installation i got the above issue, installation stopped at 41% with above mentioned issue

**Comment by netniV** [comment]
If you run php.exe with the -v or -q options, does it work correctly?

**Comment by shamim3000** [comment]
This issue has been solved in this link:
https://github.com/Cacti/cacti/issues/3313

Summary: You can restart the installation process a little more simply using MySQL:                   delete from settings where name like 'install_%';

![image](https://user-images.githubusercontent.com/19424236/76545722-76e79200-64b4-11ea-9c3b-19cb86ea16a9.png)


Unchecking this one solve the installation problem

**Comment by naoualelj** [comment]
Hello guys! Im Having the same problem here, any help?

**Comment by TheWitness** [comment]
@naoualelj, the best thing to do is to pull the 1.2.x branch, and just install from that:

```cmd
git pull -b 1.2.x https://github.com/Cacti/cacti.git /somewhere/where/you/want/it
/bin/cp -frp /somewhere/where/you/want/it/* /var/www/html/cacti
chown -R apache:apache /var/www/html/cacti
```

Change the two paths to match what you want, and you Cacti path.  If you are using a distribution, just grab the Cacti_Stats.xml.gz from the git clone, and copy it into the |path_cacti|/install/templates directory.

**Comment by TheWitness** [comment]
If this is a Windows platform issues, I left that business about oh, about 14 years ago.  Using Linux exclusively.  See if you can translate.

**Comment by naoualelj** [comment]
Hello, thanks for replying! Haha no im using fedora linux right now as a virtual machine!

**Comment by naoualelj** [comment]
It s okaaay now! Thanks
