### ISSUE TITLE
Some activities DoS the entire Cacti site

### ISSUE THREAD

**Issue by CapitalF** [Cacti/cacti#322]
If Cacti is currently creating new graphs for a host and the process is extremely slow (remote host with 60ms latency), the entire Cacti website fails to respond to other client requests.

It would seem that Cacti is a single-user application.

Cacti 1.0.3 on Linux. Browser used is Chromium on Linux.

**Comment by browniebraun** [comment]
The way you described this /issue/ is not correct. Cacti is not a single-user application. The browser is waiting for the result of that request initiated by you. This also affects additional browser tabs and windows which are not absolutely independent and sharing the session. Use two different browsers and you will notice the difference. Or open Cacti in two tabs, logout in the first one and after that click on a link in the second. Theoretically, changing this would be possible, but would also require to use input queues at the backend and other locking mechanism.

Regards
-Andi

**Comment by cigamit** [comment]
We intentionally share the session between browser tabs.  If you do not like this behavior, you may freely create a pull request, or use separate browsers.  Glad that you found the Authentication Cookies which makes this issue somewhat mute.  Therefore, I'm going to go ahead and close.
