### ISSUE TITLE
Cacti Post upgrade (1.2.2->1.2.8) failure: dB upgrade fail (1.2.3 -> 1.2.5)

### ISSUE THREAD

**Issue by gundalba** [Cacti/cacti#3222]
O/S: CentOS 7 on VMWare
3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Error Log===========================

Error

Your Cacti Server v1.2.8 has been installed/updated with errors
Database Upgrade - Version 1.2.3
Database Upgrade - Version 1.2.5

The following table lists the status of each upgrade performed on the database
	UPDATE graph_local AS gl INNER JOIN graph_templates_item AS gti ON gti.local_graph_id = gl.id INNER JOIN data_template_rrd AS dtr ON gti.task_item_id = dtr.id INNER JOIN data_local AS dl ON dl.id = dtr.local_data_id SET gl.snmp_query_id = dl.snmp_query_id, gl.snmp_index = dl.snmp_index WHERE gl.graph_template_id IN (SELECT graph_template_id FROM snmp_query_graph) AND gl.snmp_query_id = 0	[Success]
	UPDATE graph_local AS gl INNER JOIN ( SELECT DISTINCT local_graph_id, task_item_id FROM graph_templates_item ) AS gti ON gl.id = gti.local_graph_id INNER JOIN data_template_rrd AS dtr ON gti.task_item_id = dtr.id INNER JOIN data_template_data AS dtd ON dtr.local_data_id = dtd.local_data_id INNER JOIN data_input_fields AS dif ON dif.data_input_id = dtd.data_input_id INNER JOIN data_input_data AS did ON did.data_template_data_id = dtd.id AND did.data_input_field_id = dif.id INNER JOIN snmp_query_graph_rrd AS sqgr ON sqgr.snmp_query_graph_id = did.value SET gl.snmp_query_graph_id = did.value WHERE input_output = 'in' AND type_code = 'output_type' AND gl.graph_template_id IN (SELECT graph_template_id FROM snmp_query_graph)	[Success]
	**_ALTER TABLE poller_output_realtime DROP PRIMARY KEY, ADD PRIMARY KEY (local_data_id, rrd_name, time, poller_id)	[Fail]_**
Process Log

2020/01/28 15:26:12 - INSTALL: always: Installation was started at 2020-01-28 23:25:44, completed at 2020-01-28 23:26:12
2020/01/28 15:26:12 - INSTALL: info: Progress: 100
2020/01/28 15:26:12 - INSTALL: always: WARNING: One or more upgrades failed to install correctly
2020/01/28 15:26:12 - INSTALL: info: Progress: 85
2020/01/28 15:26:12 - INSTALL: info: Progress: 80
2020/01/28 15:26:12 - INSTALL: always: Finished UPGRADE Process for v1.2.8
2020/01/28 15:26:12 - INSTALL: always: Repairing Automation Rules
2020/01/28 15:26:11 - INSTALL: always: Upgrading from v1.2.3 (DB 1.2.3) to v1.2.5
2020/01/28 15:26:11 - INSTALL: always: Upgrading from v1.2.2 (DB 1.2.8 (DB: 1.2.2)) to v1.2.3
2020/01/28 15:26:11 - INSTALL: always: NOTE: Using temporary file for db cache: /tmp/cduRzMAiM
2020/01/28 15:26:11 - INSTALL: always: Switched from to /tmp/cduRzMAiM
2020/01/28 15:26:11 - INSTALL: info: Progress: 60
2020/01/28 15:26:11 - INSTALL: always: Converting Table #142 'wmi_wql_queries'
2020/01/28 15:26:11 - INSTALL: always: Converting Table #141 'wmi_user_accounts'
2020/01/28 15:26:11 - INSTALL: always: Converting Table #140 'version'
2020/01/28 15:26:11 - INSTALL: always: Converting Table #139 'vdef_items'
2020/01/28 15:26:11 - INSTALL: always: Converting Table #138 'vdef'
2020/01/28 15:26:10 - INSTALL: always: Converting Table #137 'user_log'
2020/01/28 15:26:10 - INSTALL: always: Converting Table #136 'user_domains_ldap'
2020/01/28 15:26:10 - INSTALL: always: Converting Table #135 'user_domains'
2020/01/28 15:26:10 - INSTALL: always: Converting Table #134 'user_auth_realm'
2020/01/28 15:26:10 - INSTALL: always: Converting Table #133 'user_auth_perms'
2020/01/28 15:26:10 - INSTALL: always: Converting Table #132 'user_auth_group_realm'
2020/01/28 15:26:10 - INSTALL: always: Converting Table #131 'user_auth_group_perms'
2020/01/28 15:26:10 - INSTALL: always: Converting Table #130 'user_auth_group_members'
2020/01/28 15:26:09 - INSTALL: always: Converting Table #129 'user_auth_group'
2020/01/28 15:26:09 - INSTALL: always: Converting Table #128 'user_auth_cache'
2020/01/28 15:26:09 - INSTALL: always: Converting Table #127 'user_auth'
2020/01/28 15:26:09 - INSTALL: always: Converting Table #126 'syslog_statistics'
2020/01/28 15:26:09 - INSTALL: always: Converting Table #125 'syslog_reports'
2020/01/28 15:26:06 - INSTALL: always: Converting Table #124 'syslog_removed'
2020/01/28 15:26:06 - INSTALL: always: Converting Table #123 'syslog_remove'
2020/01/28 15:26:06 - INSTALL: always: Converting Table #122 'syslog_programs'
2020/01/28 15:26:06 - INSTALL: always: Converting Table #121 'syslog_priorities'
2020/01/28 15:26:06 - INSTALL: always: Converting Table #120 'syslog_logs'
2020/01/28 15:26:06 - INSTALL: always: Converting Table #119 'syslog_incoming'
2020/01/28 15:26:05 - INSTALL: always: Converting Table #118 'syslog_hosts'
2020/01/28 15:26:05 - INSTALL: always: Converting Table #117 'syslog_host_facilities'
2020/01/28 15:26:05 - INSTALL: always: Converting Table #116 'syslog_facilities'
2020/01/28 15:26:05 - INSTALL: always: Converting Table #115 'syslog_alert'
2020/01/28 15:26:04 - INSTALL: always: Converting Table #114 'syslog'
2020/01/28 15:26:04 - INSTALL: always: Converting Table #113 'snmpagent_notifications_log'
2020/01/28 15:26:04 - INSTALL: always: Converting Table #112 'snmpagent_mibs'
2020/01/28 15:26:04 - INSTALL: always: Converting Table #111 'snmpagent_managers_notifications'
2020/01/28 15:26:04 - INSTALL: always: Converting Table #110 'snmpagent_managers'
2020/01/28 15:26:04 - INSTALL: always: Converting Table #109 'snmpagent_cache_textual_conventions'
2020/01/28 15:26:04 - INSTALL: always: Converting Table #108 'snmpagent_cache_notifications'
2020/01/28 15:26:04 - INSTALL: always: Converting Table #107 'snmpagent_cache'
2020/01/28 15:26:03 - INSTALL: always: Converting Table #106 'snmp_query_graph_sv'
2020/01/28 15:26:03 - INSTALL: always: Converting Table #105 'snmp_query_graph_rrd_sv'
2020/01/28 15:26:03 - INSTALL: always: Converting Table #104 'snmp_query_graph_rrd'
2020/01/28 15:26:03 - INSTALL: always: Converting Table #103 'snmp_query_graph'
2020/01/28 15:26:03 - INSTALL: always: Converting Table #102 'snmp_query'
2020/01/28 15:26:03 - INSTALL: always: Converting Table #101 'sites'
2020/01/28 15:26:03 - INSTALL: always: Converting Table #100 'settings_user_group'
2020/01/28 15:26:03 - INSTALL: always: Converting Table #99 'settings_user'
2020/01/28 15:26:02 - INSTALL: always: Converting Table #98 'settings_tree'
2020/01/28 15:26:02 - INSTALL: always: Converting Table #97 'settings'
2020/01/28 15:26:02 - INSTALL: always: Converting Table #96 'sessions'
2020/01/28 15:26:02 - INSTALL: always: Converting Table #95 'reports_items'
2020/01/28 15:26:02 - INSTALL: always: Converting Table #94 'reports'
2020/01/28 15:26:02 - INSTALL: always: Converting Table #93 'poller_time'
2020/01/28 15:26:02 - INSTALL: always: Converting Table #92 'poller_resource_cache'
2020/01/28 15:26:01 - INSTALL: always: Converting Table #91 'poller_reindex'
2020/01/28 15:26:01 - INSTALL: always: Converting Table #90 'poller_output_realtime'
2020/01/28 15:26:01 - INSTALL: always: Converting Table #89 'poller_output_boost_processes'
2020/01/28 15:26:01 - INSTALL: always: Converting Table #88 'poller_output_boost'
2020/01/28 15:26:01 - INSTALL: always: Converting Table #87 'poller_output'
2020/01/28 15:26:00 - INSTALL: always: Converting Table #86 'poller_item'
2020/01/28 15:26:00 - INSTALL: always: Converting Table #85 'poller_data_template_field_mappings'
2020/01/28 15:26:00 - INSTALL: always: Converting Table #84 'poller_command'
2020/01/28 15:26:00 - INSTALL: always: Converting Table #83 'poller'
2020/01/28 15:26:00 - INSTALL: always: Converting Table #82 'plugin_routerconfigs_devicetypes'
2020/01/28 15:25:59 - INSTALL: always: Converting Table #81 'plugin_routerconfigs_devices'
2020/01/28 15:25:59 - INSTALL: always: Converting Table #80 'plugin_routerconfigs_backups'
2020/01/28 15:25:59 - INSTALL: always: Converting Table #79 'plugin_routerconfigs_accounts'
2020/01/28 15:25:59 - INSTALL: always: Converting Table #78 'plugin_realms'
2020/01/28 15:25:59 - INSTALL: always: Converting Table #77 'plugin_hooks'
2020/01/28 15:25:59 - INSTALL: always: Converting Table #76 'plugin_hmib_types'
2020/01/28 15:25:59 - INSTALL: always: Converting Table #75 'plugin_hmib_processes'
2020/01/28 15:25:59 - INSTALL: always: Converting Table #74 'plugin_hmib_hrSystemTypes'
2020/01/28 15:25:58 - INSTALL: always: Converting Table #73 'plugin_hmib_hrSystem'
2020/01/28 15:25:58 - INSTALL: always: Converting Table #72 'plugin_hmib_hrSWRun_last_seen'
2020/01/28 15:25:58 - INSTALL: always: Converting Table #71 'plugin_hmib_hrSWRun_ignore'
2020/01/28 15:25:58 - INSTALL: always: Converting Table #70 'plugin_hmib_hrSWRun'
2020/01/28 15:25:58 - INSTALL: always: Converting Table #69 'plugin_hmib_hrSWInstalled'
2020/01/28 15:25:58 - INSTALL: always: Converting Table #68 'plugin_hmib_hrStorage'
2020/01/28 15:25:58 - INSTALL: always: Converting Table #67 'plugin_hmib_hrProcessor'
2020/01/28 15:25:58 - INSTALL: always: Converting Table #66 'plugin_hmib_hrDevices'
2020/01/28 15:25:57 - INSTALL: always: Converting Table #65 'plugin_db_changes'
2020/01/28 15:25:57 - INSTALL: always: Converting Table #64 'plugin_config'
2020/01/28 15:25:57 - INSTALL: always: Converting Table #63 'host_wmi_query'
2020/01/28 15:25:57 - INSTALL: always: Converting Table #62 'host_wmi_accounts'
2020/01/28 15:25:57 - INSTALL: always: Converting Table #61 'host_template_wmi_query'
2020/01/28 15:25:57 - INSTALL: always: Converting Table #60 'host_template_snmp_query'
2020/01/28 15:25:57 - INSTALL: always: Converting Table #59 'host_template_graph'
2020/01/28 15:25:57 - INSTALL: always: Converting Table #58 'host_template'
2020/01/28 15:25:57 - INSTALL: always: Converting Table #57 'host_snmp_query'
2020/01/28 15:25:55 - INSTALL: always: Converting Table #56 'host_snmp_cache'
2020/01/28 15:25:55 - INSTALL: always: Converting Table #55 'host_graph'

**Comment by netniV** [comment]
I believe that you are hitting this issue:
https://github.com/Cacti/cacti/issues/3060

If that is not the case, please reopen this one.
