### ISSUE TITLE
Add '--all' option to remove_graphs.php and issue an error if command would result in all graphs being removed and --all not specified

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3224]
Hey Guys 

This may be or bug or by design  but if you run 
php remove_graphs.php --graph-regex=   --list
you will  get a list of all of the devices in  your install  
Is there supposed to be an error displayed if the regex is null?

This is going to work great for me because I am in the middle of changing our data profile so I need to delete all of my graphs but I could see this being a danger if someone were to issue the force option and forget to add a regex value .....maybe...possibly ??

Here is the output from my test 

[root@li1303-178 cli]# php remove_graphs.php --graph-regex= --list
There are 4 Graphs to Remove.  Use the --force option to remove these Graphs.
ID      GraphName
17      Local Linux Machine - Processes
18      Local Linux Machine - Load Average
19      Local Linux Machine - Logged in Users
20      Local Linux Machine - Memory Usage

[root@li1303-178 cli]# php remove_graphs.php --graph-regex= --force
There are 4 Graphs to Remove.  Data Sources will be removed is possible.
[root@li1303-178 cli]#

**Comment by bmfmancini** [comment]
Oh BTW if it is a bug could we add keep it as a feature say something like 
php remove_graphs.php --all
with a confirmation that your about to do something bad(Potentially)
I know that its not something you would do every day but it would come in handy if you need to

**Comment by netniV** [comment]
That would work currently because the regex is considered not to have been set, rather than being set to something that will never match.  If you had used ' ' after the =, that would have only listed those with a space.

Should that be considered a bug, I think so.  If you are setting the regex, you should have a regex.

**Comment by bmfmancini** [comment]
ok cool 
can we add the --all flag ??

**Comment by cigamit** [comment]
Why don't you just change the profile, and repopulate the poller cache, move the RRDfiles to a backup location, wait for the new RRDfiles to be created, and then use the rrd_splice.php tool to stitch the old and the new together?

**Comment by bmfmancini** [comment]
I would but there are 35k graphs and tha kfulky we are ok for a reset!
Time saved!

**Comment by bmfmancini** [comment]
Oh and my goal is to change the averaging and the retention  not the poll
time so the full rra would need to be recreated just curious I guess the
rra split wouldn't do so well in that case?

**Comment by cigamit** [comment]
If you are doing something like adding rows to rra's, the splicer will still work.  Just make a backup copy of the file before you add rows, and then splice the old into the new.  You will see no gaps in the data for areas of rows that were added.

The splicing can be time consuming, so it's best to do it in parallel with as many threads as possible.
