### ISSUE TITLE
Unable to Import Templates in Cacti 1.2.9+

### ISSUE THREAD

**Issue by ank0l0g** [Cacti/cacti#3225]
Good afternoon.
Installed from scratch version 1.2.8
Trying to import templates that work in 1.2.4
Templates are not imported.
I see errors in the logs
2020/01/30 11:32:26 - 4 Import Error: Failed to insert into data_input_data table
2020/01/30 11:32:26 - CMDPHP Import Error: Import found an invalid dependency hash of: 51bde3d899e12bde28ad979166985584. Please open bug on GitHub.
2020/01/30 11:32:26 - 4 Import Error: Failed to insert into data_input_data table
2020/01/30 11:32:26 - CMDPHP Import Error: Import found an invalid dependency hash of: 51bde3d899e12bde28ad979166985584. Please open bug on GitHub.
2020/01/30 11:32:26 - 4 Import Error: Failed to insert into data_input_data table
2020/01/30 11:32:26 - 4 Import Error: Failed to insert into data_input_data table
2020/01/30 11:32:26 - 4 Import Error: Failed to insert into data_input_data table
2020/01/30 11:32:26 - CMDPHP Import Error: Import found an invalid dependency hash of: 51bde3d899e12bde28ad979166985584. Please open bug on GitHub.
2020/01/30 11:32:26 - 4 Import Error: Failed to insert into data_input_data table
2020/01/30 11:32:26 - 4 Import Error: Failed to insert into data_input_data table
2020/01/30 11:32:26 - CMDPHP Import Error: Import found an invalid dependency hash of: 51bde3d899e12bde28ad979166985584. Please open bug on GitHub.
2020/01/30 11:32:26 - 4 Import Error: Failed to insert into data_input_data table
2020/01/30 11:32:26 - 4 Import Error: Failed to insert into data_input_data table
2020/01/30 11:32:26 - CMDPHP Import Error: Import found an invalid dependency hash of: 51bde3d899e12bde28ad979166985584. Please open bug on GitHub.
2020/01/30 11:32:26 - 4 Import Error: Failed to insert into data_input_data table

**Comment by netniV** [comment]
Can you provide details of the template and if possible the files you are trying to use?

**Comment by cigamit** [comment]
Also, upload the damaged template here and let us know where you received it from.

**Comment by ank0l0g** [comment]
http://achlab.ru/ach/2016/09/20/cacti-template-for-nmc-ups-ippon/
[cacti_host_template_ups_ippon_nmc.zip](https://github.com/Cacti/cacti/files/4137718/cacti_host_template_ups_ippon_nmc.zip)

**Comment by cigamit** [comment]
How we missed this, I'll never know.  Resolved.  Improved the logging just a little for in the future.

**Comment by cigamit** [comment]
Okay, I did fix one issue, but there appears to be another.  Tracking that now.

**Comment by cigamit** [comment]
So, I see the problem here.  It's another example of a very old template, one where the end user modified the 'Get SNMP Data' Data Input Method before it was made 'hidden' or 'system'.  Let me see if I can find a creative way to address this without having to 'fix' the broken template.

**Comment by cigamit** [comment]
So, this will work now in 1.2.9 release.

**Comment by ank0l0g** [comment]
Updated to 1.3.0
The problematic template has been loaded.
But there was a problem with other templates.
https://docs.cacti.net/usertemplate:host:ups:apc
or
https://docs.cacti.net/usertemplate:data:apc:apcupsd

There are no errors in the logs.
