### ISSUE TITLE
CPU usage seems high

### ISSUE THREAD

**Issue by sirjana** [Cacti/cacti#3227]
On cacti server cpu load is 100% and while verifying with top command rrdtool is causing the issue.How can we fix this and what can cause large cpu usage by rrdtool???
I'm using rrdtool utility version as RRDtool 1.4x, maximum thread per process on setting -->poller is 20 and cacti version is 0.8.6a.

**Comment by cigamit** [comment]
Well, Cacti 0.8.6a is pretty old.  You could try boost and the plugin architecture, but I would say just go with 1.2.29 once it's released.  Since we don't support this release any longer, I'm going to close this.  You should carry on this conversation on the Forums.
