### ISSUE TITLE
Security issue on login page, the password send on clear text on the query

### ISSUE THREAD

**Issue by arno-st** [Cacti/cacti#3229]
How is it possible that the password is send in clear text in the login query ?
I know an https can partially resolve this issue, but still if you decode the https (via revers proxy) the password will still be a clear text

body of the query:
__csrf_magic=sid%3A855748ee77503b073ab016d44a0072fb26322c1f%2C1580733223&action=login&login_username=<in clear>&login_password=<in clear>%2Ba&realm=2

**Comment by netniV** [comment]
That should not be a get request but a post.  Something has changed that.

**Comment by TheWitness** [comment]
Pretty sure that is a post.  Can you turn on your browsers debug panel, and then goto the network panel, and make the log persist.  Then, logoff, clear the network panel, and then log back on again.  You first entry on the network panel should be index.php, with the indication that it was a POST.  The fact that it included the "csrf_magic" token also tells me that.

**Comment by arno-st** [comment]
No no, it is a POST, but still, I don't think as security point of view that the password should be in clear.

**Comment by cigamit** [comment]
Yes, this is the way that HTML forms work.  If you want it end to end encrypted, you have to use HTTPS.  HTML standard doesn't have a method for fully encrypting the data before sending.  Even "enctype" is just changing the encoding, its still plain text over the wire.  There are other methods of using JavaScript to encrypt the data first, but they have their own issues (the Javascript doing the encryption is plain text and is also visible via a reverse-proxy).

**Comment by netniV** [comment]
You're only way to do an encryption before posting is to either hash the password client side or encrypt it with a one time code so it can only be decrypted once by the server.

**Comment by cigamit** [comment]
The problem with just doing an encode is that the only person that comes out feeling more comfortable is the person who see's that even though the post is encrypted via https, they can still look at the post from the browsers debug panel and it's not encoded.

We could share a salt with the client on the login page and encode dynamically, but that could also be intercepted and used to hack some foolish enough to use http over https.  I'm not sure there is any real value in that right now though with all the other things pending.

**Comment by arno-st** [comment]
Ok, I close the case

**Comment by netniV** [comment]
> We could share a salt with the client on the login page and encode dynamically, but that could also be intercepted and used to hack some foolish enough to use http over https. I'm not sure there is any real value in that right now though with all the other things pending.

Well, if we used a time-based hash, that could provide an effectively OTP hash that is valid on for the few minutes that the login was being attempted.  Tie the salt to the PHP session ID and a 5 minute period, it adds a fair bit of security to the login, but it is a bit of work.

To be honest, you are betting using 1.3's TOTP password functionality to prevent people logging in without your 2FA code.
