### ISSUE TITLE
Some Selection Boxes don't work properly

### ISSUE THREAD

**Issue by CapitalF** [Cacti/cacti#323]
Some selection drop-down boxes don't work properly. They are often slow to open, or don't open when clicked on. Pressing Esc or clicking outside of the selection box fails to close the selection box, as is expected. A good example of this is the "Device" Selection box on graphs_new.php. It seems like this problem is caused by the fact that this box is some kind of Frankenstein-monster text input+drop-down box that does an SQL query when clicked on. Another example is on the graph_view.php page, 4th drop-down menu from the right on the "Graph Filters" "Presets" line, between the To-date and the Refresh button.

Cacti 1.0.3 on Linux. Browser used is Chromium on Linux.

**Comment by cigamit** [comment]
That Frankenstein monster was a serious pain to write.  Wish that jQueryUI would make it a supported method.  If you feel so motivated, we would love to accept a pull request to make it work better.  Other than that, I don't seen anything to change here.  jQueryUI is quirky at times, and we hope that they make things more stable in the future.  As it is, the upgrade to 1.12 is going to be a lot of work.

Either way, we appreciate your somewhat morbid approach to editorializing your issue reports.  Thanks for being specific in this case.

Once you have finalized enhancing the device dropdown, just open a pull request with your changes and we will review.  Thanks!
