### ISSUE TITLE
When editing HRULE and VRULE items,  color selector was not presented

### ISSUE THREAD

**Issue by frontierliu** [Cacti/cacti#3232]
Version: Cacti 1.2.8, 1.2.9

When I edit graph template's item of HRULE or VRULE , I can change its color in item_edit  page  as below:
![QQ图片20200205104857](https://user-images.githubusercontent.com/24820773/73809791-40f92300-480f-11ea-8201-6bcf225058a3.png)

But When I edit graph's item of HRULE or VRULE, the color selector dispears in item_edit page, and I think it is unreasonable, as below:
![QQ截图20200205104700](https://user-images.githubusercontent.com/24820773/73809983-ec09dc80-480f-11ea-814c-31dbd86abb70.png)

HRULE and VRULE edit page should keep color option selector and other options in graph, as graph_template do.

how to resolv:
in graphs_items.php 
line 601:        $('#row_color_id').hide();   change to :      $('#row_color_id').show();   
line 613:        $('#row_text_format').hide();    change to :     $('#row_text_format').show();
line 618:        $('#row_color_id').hide();   change to :        $('#row_color_id').show();
line 630:        $('#row_text_format').hide();   change to:    $('#row_text_format').show();

**Comment by cigamit** [comment]
Oh, this is interesting.

**Comment by cigamit** [comment]
Thanks for catching this.
