### ISSUE TITLE
ERROR: A DB Cell Failed!, Error: Table 'cacti.poller_output_boost_arch

### ISSUE THREAD

**Issue by Izmenoff** [Cacti/cacti#3235]
centos7
MariaDB 10.2.31
cacti 1.2.8

Time to time appears this error in log. All works, but what it means?

![image](https://user-images.githubusercontent.com/17400240/73820763-8152a400-4803-11ea-8731-05d87a51f5c7.png)

**Comment by cigamit** [comment]
This is a transient error and can be ignored.  It happens when a user is trying to view a graph when boost runs, and by the time it goes to generate the graph, the table has been dropped.  Should be easy to bypass that warning.

**Comment by cigamit** [comment]
This is fixed, but if you want to take the fix, you also have to update poller_boost.php from the 1.2.x branch.  Otherwise wait for 1.2.29.

**Comment by Izmenoff** [comment]
Thanks for fast response and fix the problem!
