### ISSUE TITLE
Cacti 1.3.0 not import templates

### ISSUE THREAD

**Issue by ank0l0g** [Cacti/cacti#3236]
Updated to 1.3.0
The problematic template has been loaded.
But there was a problem with other templates.
https://docs.cacti.net/usertemplate:host:ups:apc
or
https://docs.cacti.net/usertemplate:data:apc:apcupsd

There are no errors in the logs.

**Comment by netniV** [comment]
This is likely related to the existing bug in 1.2.x which we recently patched. Those patches haven’t made their way to 1.3 yet.

**Comment by ank0l0g** [comment]
Suggest to wait?

**Comment by netniV** [comment]
Yes, we have been leaving things o tick over this week and hopefully release 1.2.9 at the weekend.  once that is done, the changes will be merged.  Going forward, we are going to have to duplicate the work to ensure that it is patched on both sides once the code starts differing vastly.

**Comment by cigamit** [comment]
Yea, after release, we will push the changes back into develop.  Small team.

**Comment by netniV** [comment]
Latest changes where pushed to develop.
