### ISSUE TITLE
Aggregate Template Graph Template JavaScript Error

### ISSUE THREAD

**Issue by CapitalF** [Cacti/cacti#324]
In the "Aggregate Template" (aggregate_templates.php), setting the "Source Graph Template" results in the dropdown box not closing after selection. I've seen this elsewhere on some drop-down selectors.

Cacti 1.0.3 on Linux. Browser used is Chromium on Linux.

**Comment by cigamit** [comment]
Please attach a screen shot.

**Comment by CapitalF** [comment]
Attached

![untitled](https://cloud.githubusercontent.com/assets/13446991/23243299/25996654-f93b-11e6-8aed-5fda5e37984a.png)

This screen shows after I have selected an item on the drop-down. Expected behavior is for the menu to close.

**Comment by cigamit** [comment]
Resolved.  Next time, please be more specific when logging issues.  It will save having to rehash things which just delays the fixes.  Thanks for testing!
