### ISSUE TITLE
upgrade from cacti 0.8f to cacti 1.2.4

### ISSUE THREAD

**Issue by rabbit24** [Cacti/cacti#3241]
2020/02/06 13:31:18 - INSTALL: always: Installation was started at 2020-02-06 12:26:10, completed at 2020-02-06 13:31:18
2020/02/06 13:31:18 - INSTALL: always: WARNING: One or more upgrades failed to install correctly
2020/02/06 13:31:17 - INSTALL: always: Finished UPGRADE Process for v1.2.4
2020/02/06 13:31:17 - INSTALL: always: Installation was started at 2020-02-06 11:58:56, completed at 2020-02-06 13:31:17
2020/02/06 13:31:17 - INSTALL: always: WARNING: One or more upgrades failed to install correctly
2020/02/06 13:31:16 - INSTALL: always: Finished UPGRADE Process for v1.2.4
2020/02/06 13:09:04 - INSTALL: always: Installation was started at 2020-02-06 11:33:32, completed at 2020-02-06 13:09:04
2020/02/06 13:09:03 - INSTALL: always: WARNING: One or more upgrades failed to install correctly
2020/02/06 13:09:01 - INSTALL: always: Finished UPGRADE Process for v1.2.4
2020/02/06 12:55:06 - INSTALL: always: Upgrading from v0.8.8f (DB 1.2.4 (DB: 0.8.8f)) to v1.0.0
2020/02/06 12:55:05 - INSTALL: always: NOTE: Using temporary file for db cache: /tmp/cducPmVvD
2020/02/06 12:55:05 - INSTALL: always: Switched from /tmp/cdu70M5pD to /tmp/cducPmVvD 

this the error i am getting. i have 4 days on this. i have reboot the pc and did not work. please help
thanks 
Marco

**Comment by rabbit24** [comment]
sorry it is 0.8.8f. if it was done already. is there any anther way of doing it. plaese share. this first time i am doing it.
thanks for the feed back
Marco

**Comment by netniV** [comment]
You should probably move to 1.2.8/1.2.9 if you can.  The 1.2.4 was six months ago and there have been plenty of bug fixes since.  Are you in a position to be able to do that?
