### ISSUE TITLE
Cacti v1.2.8: Tree Mode is blank

### ISSUE THREAD

**Issue by rcuares** [Cacti/cacti#3242]
**Describe the bug**
The Tree Mode is blank under the Graphs tab.

**To Reproduce**
1. Install Cacti v1.2.8 (fresh install).
2. Login to Cacti.
3. Add monitored devices. In my case, an Ubuntu VM and Cisco router.
4. Click on Graphs tab (by default, it is set to Tree View)
5. The Tree Mode page is blank.

![image](https://user-images.githubusercontent.com/40181093/73973845-13c38680-496f-11ea-8ca3-dcb4804ae9c5.png)

**Expected behavior**
I should be able to see my devices under Tree Mode. Sample screenshot provided for my other install of Cacti running on version 1.2.4.

![image](https://user-images.githubusercontent.com/40181093/73974165-99473680-496f-11ea-83eb-0de61bf43900.png)

**Desktop:**
 - OS: Ubuntu 18.04.3 LTS and Windows 10
 - Browser and version: 
Firefox 72.0.2 (64-bit) on both Ubuntu and Windows 
Chrome 79.0.3945.130 (64-bit) on Ubuntu

**Additional context**
I tried the following but did not resolved the issue.
- changed the themes 
- used different browsers
- used different OS
- cleared web cache
- verified that the Default Tree is published

![image](https://user-images.githubusercontent.com/40181093/73975016-322a8180-4971-11ea-82af-6685b5a8bc0e.png)

- toggled to List Mode and Preview Mode are working fine.

**Comment by netniV** [comment]
Are you seeing any errors on your browser's developer console?

**Comment by TheWitness** [comment]
This is fixed in the 1.2.x branch.

**Comment by rcuares** [comment]
@netniV not seeing any errors when I enabled debug on the browser (i used Firefox).

@TheWitness Could you please advise the bug id # that makes this post duplicate? Thanks.

**Comment by cigamit** [comment]
https://github.com/Cacti/cacti/issues/3142
