### ISSUE TITLE
Interface Graphs Maxed at 14M

### ISSUE THREAD

**Issue by djeronimo** [Cacti/cacti#3243]
My interface graphs max out at 14M, but in realtime they show the proper bandwidth.

![Interface_Max](https://user-images.githubusercontent.com/5642437/74086799-69be2a00-4a54-11ea-9e60-1c5e739a5373.jpg)

**Comment by bmfmancini** [comment]
Are you using 64bit counters?

**Comment by djeronimo** [comment]
I am

**Comment by bmfmancini** [comment]
Interesting

What version of cacti?
What type of device?

Can you send the graph debug output
Also may want to do a data source debug to see what the poller gets as a
value

Also is this cmd.php or spine?

**Comment by cigamit** [comment]
Check the Maximum values for the counters in the RRDfiles.  If this is an upgraded Cacti for sure, you might have a low max value which will drive an error.  The Data Source Debug interface checks for such things too.

**Comment by cigamit** [comment]
Theres a second note on this one.  There are cases, especially with older SNMP agents, where things like bonded interfaces report the correct ifHighSpeed, or an ifSpeed that are too low.  In those Cases, Cacti really can not properly set a Max value in the RRDfile.  But also, Cacti has little expectation to be able to find all agent bugs.  So, you can use rrdtool tune command to fix such things.

**Comment by djeronimo** [comment]
This particular graph is off a Cisco ASA firewall, but I am experiencing the same with my switches which are HPE Procurve 5406zl.

Here is the debug from the ASA interface.

RRDtool Command:
/usr/bin/rrdtool graph - \
--imgformat=PNG \
--start='-86400' \
--end='-300' \
--pango-markup  \
--title='ciscoasa.dentistry.utoronto.ca - Traffic - External Interface' \
--vertical-label='bytes per second' \
--slope-mode \
--base=1000 \
--height=200 \
--width=700 \
--rigid \
--alt-autoscale-max \
--lower-limit='0' \
COMMENT:"From 07/02/2020 19\:05\:25 To 08/02/2020 19\:00\:25\c" \
COMMENT:"  \n" \
--color BACK#F3F3F3 \
--color CANVAS#FDFDFD \
--color SHADEA#CBCBCB \
--color SHADEB#999999 \
--color GRID#C4C4C4 \
--color MGRID#1A1C1C \
--color FONT#000000 \
--color AXIS#2C4D43 \
--color ARROW#2C4D43 \
--color FRAME#2C4D43 \
--border 1 --font TITLE:11:'Arial' \
--font AXIS:8:'Arial' \
--font LEGEND:8:'Courier' \
--font UNIT:8:'Arial' \
--font WATERMARK:6:'Arial' \
--slope-mode \
--watermark 'Generated by Cacti®' \
DEF:a='/var/www/html/cacti/rra/ciscoasa_dentistry_utoronto_ca_traffic_in_13.rrd':'traffic_in':AVERAGE \
DEF:b='/var/www/html/cacti/rra/ciscoasa_dentistry_utoronto_ca_traffic_in_13.rrd':'traffic_in':MAX \
DEF:c='/var/www/html/cacti/rra/ciscoasa_dentistry_utoronto_ca_traffic_in_13.rrd':'traffic_out':AVERAGE \
DEF:d='/var/www/html/cacti/rra/ciscoasa_dentistry_utoronto_ca_traffic_in_13.rrd':'traffic_out':MAX \
AREA:a#00CF00FF:'Inbound '  \
LINE1:b#00CF00FF:  \
GPRINT:b:LAST:'Current\:%8.2lf%s'  \
GPRINT:b:AVERAGE:'Average\:%8.2lf%s'  \
GPRINT:b:MAX:'Maximum\:%8.2lf%s\n'  \
LINE1:c#002A97FF:'Outbound'  \
GPRINT:c:LAST:'Current\:%8.2lf%s'  \
LINE1:d#002A97FF:  \
GPRINT:d:AVERAGE:'Average\:%8.2lf%s'  \
GPRINT:d:MAX:'Maximum\:%8.2lf%s' 
RRDtool Says:
OK

**Comment by djeronimo** [comment]
> Theres a second note on this one. There are cases, especially with older SNMP agents, where things like bonded interfaces report the correct ifHighSpeed, or an ifSpeed that are too low. In those Cases, Cacti really can not properly set a Max value in the RRDfile. But also, Cacti has little expectation to be able to find all agent bugs. So, you can use rrdtool tune command to fix such things.

**Comment by djeronimo** [comment]
sorry didn't mean to close it off

**Comment by TheWitness** [comment]
Post an "rrdtool info filename"

**Comment by djeronimo** [comment]
filename = "/var/www/html/cacti/rra/ciscoasa_dentistry_utoronto_ca_traffic_in_13.rrd"
rrd_version = "0003"
step = 300
last_update = 1581217506
header_size = 5216
ds[traffic_in].index = 0
ds[traffic_in].type = "COUNTER"
ds[traffic_in].minimal_heartbeat = 600
ds[traffic_in].min = 0.0000000000e+00
ds[traffic_in].max = 1.0000000000e+09
ds[traffic_in].last_ds = "3905181446"
ds[traffic_in].value = 8.4569189298e+05
ds[traffic_in].unknown_sec = 0
ds[traffic_out].index = 1
ds[traffic_out].type = "COUNTER"
ds[traffic_out].minimal_heartbeat = 600
ds[traffic_out].min = 0.0000000000e+00
ds[traffic_out].max = 1.0000000000e+09
ds[traffic_out].last_ds = "224857357"
ds[traffic_out].value = 1.0946863144e+06
ds[traffic_out].unknown_sec = 0
rra[0].cf = "AVERAGE"
rra[0].rows = 600
rra[0].cur_row = 343
rra[0].pdp_per_row = 1
rra[0].xff = 5.0000000000e-01
rra[0].cdp_prep[0].value = NaN
rra[0].cdp_prep[0].unknown_datapoints = 0
rra[0].cdp_prep[1].value = NaN
rra[0].cdp_prep[1].unknown_datapoints = 0
rra[1].cf = "AVERAGE"
rra[1].rows = 700
rra[1].cur_row = 41
rra[1].pdp_per_row = 6
rra[1].xff = 5.0000000000e-01
rra[1].cdp_prep[0].value = 1.3954561455e+05
rra[1].cdp_prep[0].unknown_datapoints = 0
rra[1].cdp_prep[1].value = 1.8074099248e+05
rra[1].cdp_prep[1].unknown_datapoints = 0
rra[2].cf = "AVERAGE"
rra[2].rows = 775
rra[2].cur_row = 661
rra[2].pdp_per_row = 24
rra[2].xff = 5.0000000000e-01
rra[2].cdp_prep[0].value = 1.2897348494e+06
rra[2].cdp_prep[0].unknown_datapoints = 0
rra[2].cdp_prep[1].value = 8.4650949714e+06
rra[2].cdp_prep[1].unknown_datapoints = 0
rra[3].cf = "AVERAGE"
rra[3].rows = 797
rra[3].cur_row = 645
rra[3].pdp_per_row = 288
rra[3].xff = 5.0000000000e-01
rra[3].cdp_prep[0].value = 5.2201003236e+06
rra[3].cdp_prep[0].unknown_datapoints = 0
rra[3].cdp_prep[1].value = 3.3620321034e+07
rra[3].cdp_prep[1].unknown_datapoints = 0
rra[4].cf = "MIN"
rra[4].rows = 600
rra[4].cur_row = 546
rra[4].pdp_per_row = 1
rra[4].xff = 5.0000000000e-01
rra[4].cdp_prep[0].value = NaN
rra[4].cdp_prep[0].unknown_datapoints = 0
rra[4].cdp_prep[1].value = NaN
rra[4].cdp_prep[1].unknown_datapoints = 0
rra[5].cf = "MIN"
rra[5].rows = 700
rra[5].cur_row = 306
rra[5].pdp_per_row = 6
rra[5].xff = 5.0000000000e-01
rra[5].cdp_prep[0].value = 1.3954561455e+05
rra[5].cdp_prep[0].unknown_datapoints = 0
rra[5].cdp_prep[1].value = 1.8074099248e+05
rra[5].cdp_prep[1].unknown_datapoints = 0
rra[6].cf = "MIN"
rra[6].rows = 775
rra[6].cur_row = 205
rra[6].pdp_per_row = 24
rra[6].xff = 5.0000000000e-01
rra[6].cdp_prep[0].value = 7.9578305427e+04
rra[6].cdp_prep[0].unknown_datapoints = 0
rra[6].cdp_prep[1].value = 7.3424725397e+04
rra[6].cdp_prep[1].unknown_datapoints = 0
rra[7].cf = "MIN"
rra[7].rows = 797
rra[7].cur_row = 125
rra[7].pdp_per_row = 288
rra[7].xff = 5.0000000000e-01
rra[7].cdp_prep[0].value = 7.9578305427e+04
rra[7].cdp_prep[0].unknown_datapoints = 0
rra[7].cdp_prep[1].value = 7.3424725397e+04
rra[7].cdp_prep[1].unknown_datapoints = 0
rra[8].cf = "MAX"
rra[8].rows = 600
rra[8].cur_row = 151
rra[8].pdp_per_row = 1
rra[8].xff = 5.0000000000e-01
rra[8].cdp_prep[0].value = NaN
rra[8].cdp_prep[0].unknown_datapoints = 0
rra[8].cdp_prep[1].value = NaN
rra[8].cdp_prep[1].unknown_datapoints = 0
rra[9].cf = "MAX"
rra[9].rows = 700
rra[9].cur_row = 88
rra[9].pdp_per_row = 6
rra[9].xff = 5.0000000000e-01
rra[9].cdp_prep[0].value = 1.3954561455e+05
rra[9].cdp_prep[0].unknown_datapoints = 0
rra[9].cdp_prep[1].value = 1.8074099248e+05
rra[9].cdp_prep[1].unknown_datapoints = 0
rra[10].cf = "MAX"
rra[10].rows = 775
rra[10].cur_row = 326
rra[10].pdp_per_row = 24
rra[10].xff = 5.0000000000e-01
rra[10].cdp_prep[0].value = 2.0663827348e+05
rra[10].cdp_prep[0].unknown_datapoints = 0
rra[10].cdp_prep[1].value = 6.5089176410e+06
rra[10].cdp_prep[1].unknown_datapoints = 0
rra[11].cf = "MAX"
rra[11].rows = 797
rra[11].cur_row = 732
rra[11].pdp_per_row = 288
rra[11].xff = 5.0000000000e-01
rra[11].cdp_prep[0].value = 5.5644935271e+05
rra[11].cdp_prep[0].unknown_datapoints = 0
rra[11].cdp_prep[1].value = 7.7621265436e+06
rra[11].cdp_prep[1].unknown_datapoints = 0
rra[12].cf = "LAST"
rra[12].rows = 600
rra[12].cur_row = 375
rra[12].pdp_per_row = 1
rra[12].xff = 5.0000000000e-01
rra[12].cdp_prep[0].value = NaN
rra[12].cdp_prep[0].unknown_datapoints = 0
rra[12].cdp_prep[1].value = NaN
rra[12].cdp_prep[1].unknown_datapoints = 0
rra[13].cf = "LAST"
rra[13].rows = 700
rra[13].cur_row = 104
rra[13].pdp_per_row = 6
rra[13].xff = 5.0000000000e-01
rra[13].cdp_prep[0].value = 1.3954561455e+05
rra[13].cdp_prep[0].unknown_datapoints = 0
rra[13].cdp_prep[1].value = 1.8074099248e+05
rra[13].cdp_prep[1].unknown_datapoints = 0
rra[14].cf = "LAST"
rra[14].rows = 775
rra[14].cur_row = 371
rra[14].pdp_per_row = 24
rra[14].xff = 5.0000000000e-01
rra[14].cdp_prep[0].value = 1.3954561455e+05
rra[14].cdp_prep[0].unknown_datapoints = 0
rra[14].cdp_prep[1].value = 1.8074099248e+05
rra[14].cdp_prep[1].unknown_datapoints = 0
rra[15].cf = "LAST"
rra[15].rows = 797
rra[15].cur_row = 138
rra[15].pdp_per_row = 288
rra[15].xff = 5.0000000000e-01
rra[15].cdp_prep[0].value = 1.3954561455e+05
rra[15].cdp_prep[0].unknown_datapoints = 0
rra[15].cdp_prep[1].value = 1.8074099248e+05
rra[15].cdp_prep[1].unknown_datapoints = 0

**Comment by TheWitness** [comment]
That info output looks like the max value for a 1GE port.  So, to me, you are polling a 32bit OID and not the 64bit.  So, you should review the poller cache and review the SNMP OID's being polled and then do an snmpget against that OID.  I bet's it comes back a Counter or Counter32.

**Comment by djeronimo** [comment]
The interface is 1GE and the graphs are set to 64-bit, but what I will do is blow away the graphs I've created and re-do them.

![Annotation 2020-02-09 112150](https://user-images.githubusercontent.com/5642437/74105740-6b5c2080-4b2e-11ea-9f51-41e37e2807a9.jpg)

**Comment by TheWitness** [comment]
Do what I asked...

**Comment by djeronimo** [comment]
Seems to be working now.  I deleted all the graphs and data.


![image](https://user-images.githubusercontent.com/5642437/74111025-4fbd3e00-4b5f-11ea-8c87-1e16b8fec754.png)

**Comment by TheWitness** [comment]
You can splice the old rrdfile into the new one too.  You should also compare the rrdtool info from the old RRDfile and the new one to see what is different.

**Comment by TheWitness** [comment]
```console
cd cli
php -q splice_rrd.php --oldrrd=oldfile --newrrd=newfile --finfile=outputfile
```

You need to be at PHP 5.4+ and have SQLite php module installed.
