### ISSUE TITLE
Generic SNMP OID Data Source Maximum doesn't apply to negative values

### ISSUE THREAD

**Issue by TheBlueMatt** [Cacti/cacti#3244]
I have an SNMP data source (a signal strength meter) that is always negative (in dBm), and occasionally 0 to indicate no connection. I'd like to drop all the 0 values, so set the "Maximum Value" field to -5, however 0 still regularly still gets recorded as the current value.

**Comment by netniV** [comment]
Have you checked your datasource against the RRA?

**Comment by TheBlueMatt** [comment]
Hmm, not actually sure what that means? The RAA contains 0 values, and the data source in cacti has a "Maximum Value" of -5.

**Comment by TheWitness** [comment]
post the rrdtool info output.

**Comment by TheBlueMatt** [comment]
The following is the rrdtool info output, though note that the Maximum of -5 has been set for some months but not at initial creation.

```
filename = "/var/lib/cacti/rra/litebeam_as397444_net_snmp_oid_199.rrd"
rrd_version = "0003"
step = 60
last_update = 1582775043
header_size = 3704
ds[snmp_oid].index = 0
ds[snmp_oid].type = "GAUGE"
ds[snmp_oid].minimal_heartbeat = 600
ds[snmp_oid].min = -1.0000000000e+02
ds[snmp_oid].max = NaN
ds[snmp_oid].last_ds = "-56"
ds[snmp_oid].value = -1.6800000000e+02
ds[snmp_oid].unknown_sec = 0
rra[0].cf = "AVERAGE"
rra[0].rows = 2900
rra[0].cur_row = 796
rra[0].pdp_per_row = 1
rra[0].xff = 5.0000000000e-01
rra[0].cdp_prep[0].value = NaN
rra[0].cdp_prep[0].unknown_datapoints = 0
rra[1].cf = "AVERAGE"
rra[1].rows = 1400
rra[1].cur_row = 1088
rra[1].pdp_per_row = 15
rra[1].xff = 5.0000000000e-01
rra[1].cdp_prep[0].value = -7.8396666667e+02
rra[1].cdp_prep[0].unknown_datapoints = 0
rra[2].cf = "AVERAGE"
rra[2].rows = 1465
rra[2].cur_row = 740
rra[2].pdp_per_row = 60
rra[2].xff = 5.0000000000e-01
rra[2].cdp_prep[0].value = -2.4691000000e+03
rra[2].cdp_prep[0].unknown_datapoints = 0
rra[3].cf = "AVERAGE"
rra[3].rows = 4380
rra[3].cur_row = 2708
rra[3].pdp_per_row = 240
rra[3].xff = 5.0000000000e-01
rra[3].cdp_prep[0].value = -1.2537100000e+04
rra[3].cdp_prep[0].unknown_datapoints = 0
rra[4].cf = "MIN"
rra[4].rows = 2900
rra[4].cur_row = 63
rra[4].pdp_per_row = 1
rra[4].xff = 5.0000000000e-01
rra[4].cdp_prep[0].value = NaN
rra[4].cdp_prep[0].unknown_datapoints = 0
rra[5].cf = "MIN"
rra[5].rows = 1400
rra[5].cur_row = 163
rra[5].pdp_per_row = 15
rra[5].xff = 5.0000000000e-01
rra[5].cdp_prep[0].value = -5.6933333333e+01
rra[5].cdp_prep[0].unknown_datapoints = 0
rra[6].cf = "MIN"
rra[6].rows = 1465
rra[6].cur_row = 104
rra[6].pdp_per_row = 60
rra[6].xff = 5.0000000000e-01
rra[6].cdp_prep[0].value = -5.7966666667e+01
rra[6].cdp_prep[0].unknown_datapoints = 0
rra[7].cf = "MIN"
rra[7].rows = 4380
rra[7].cur_row = 2005
rra[7].pdp_per_row = 240
rra[7].xff = 5.0000000000e-01
rra[7].cdp_prep[0].value = -5.8000000000e+01
rra[7].cdp_prep[0].unknown_datapoints = 0
rra[8].cf = "MAX"
rra[8].rows = 2900
rra[8].cur_row = 1120
rra[8].pdp_per_row = 1
rra[8].xff = 5.0000000000e-01
rra[8].cdp_prep[0].value = NaN
rra[8].cdp_prep[0].unknown_datapoints = 0
rra[9].cf = "MAX"
rra[9].rows = 1400
rra[9].cur_row = 1059
rra[9].pdp_per_row = 15
rra[9].xff = 5.0000000000e-01
rra[9].cdp_prep[0].value = -5.5100000000e+01
rra[9].cdp_prep[0].unknown_datapoints = 0
rra[10].cf = "MAX"
rra[10].rows = 1465
rra[10].cur_row = 1264
rra[10].pdp_per_row = 60
rra[10].xff = 5.0000000000e-01
rra[10].cdp_prep[0].value = -5.5000000000e+01
rra[10].cdp_prep[0].unknown_datapoints = 0
rra[11].cf = "MAX"
rra[11].rows = 4380
rra[11].cur_row = 3614
rra[11].pdp_per_row = 240
rra[11].xff = 5.0000000000e-01
rra[11].cdp_prep[0].value = -5.5000000000e+01
rra[11].cdp_prep[0].unknown_datapoints = 0
rra[12].cf = "LAST"
rra[12].rows = 2900
rra[12].cur_row = 708
rra[12].pdp_per_row = 1
rra[12].xff = 5.0000000000e-01
rra[12].cdp_prep[0].value = NaN
rra[12].cdp_prep[0].unknown_datapoints = 0
rra[13].cf = "LAST"
rra[13].rows = 1400
rra[13].cur_row = 804
rra[13].pdp_per_row = 15
rra[13].xff = 5.0000000000e-01
rra[13].cdp_prep[0].value = -5.6000000000e+01
rra[13].cdp_prep[0].unknown_datapoints = 0
rra[14].cf = "LAST"
rra[14].rows = 1465
rra[14].cur_row = 775
rra[14].pdp_per_row = 60
rra[14].xff = 5.0000000000e-01
rra[14].cdp_prep[0].value = -5.6000000000e+01
rra[14].cdp_prep[0].unknown_datapoints = 0
rra[15].cf = "LAST"
rra[15].rows = 4380
rra[15].cur_row = 724
rra[15].pdp_per_row = 240
rra[15].xff = 5.0000000000e-01
rra[15].cdp_prep[0].value = -5.6000000000e+01
rra[15].cdp_prep[0].unknown_datapoints = 0
```

**Comment by TheWitness** [comment]
I think this is really more of a question and not a bug.  If you plan on modifying the RRDfile min and maxes you should set the min and max values to be updateable for the Generic OID and then set them when you create the graph.

However, if would be better if you simply create a Data Template and Graph Template for this specific object type where the value will always be right the first time.  That is my recommendation.

**Comment by TheBlueMatt** [comment]
Hmm. Maybe the UI is assuming a certain level of knowledge of how things work underneath that I don't have, but I'd expect if I update the maximum in the UI after creating a datasource it would update the maximum. It appears that isn't correct?

I don't fully understand your response, so could you suggest a more precise action as a workaround, and then maybe retag this as a suggested improvement that updates work as the UI implies they should?

**Comment by TheWitness** [comment]
That's not the way it works.  By default, in Cacti anyway, once you set the maximum and minimum values in Cacti, it does not 'automatically' change the values. If you wish to always create an RRDfile where you can specify the minimum and maximum values, you have to first edit it's Data Template, then you change the toggle next to the min and max values, then save.  After that, you will be prompted for what the min and max values should be.  Review the image below.

![MinMaxValues](https://user-images.githubusercontent.com/1439914/76692723-a02d2d00-6630-11ea-87da-089a97acbbe7.png)

**Comment by TheBlueMatt** [comment]
Right, I edited the data template (though there are no such switches on that page?), but that's it. The UI doesn't generally expose much of the concept of the underlying RRDs being generated, hence why I'm left pretty confused. Maybe it makes sense to just convert this to a "UX is confusing, need more docs on the RRD and how to change the min/max values for already existing things"?

**Comment by TheBlueMatt** [comment]
Any update on this? There are no checkboxes 
![image](https://user-images.githubusercontent.com/649246/82107845-39a0ba00-971a-11ea-8c91-bfd25b207568.png)

**Comment by netniV** [comment]
Are you editing the template or the graph ?

**Comment by TheBlueMatt** [comment]
The data source.

**Comment by netniV** [comment]
You need to edit the template, then synchronise the changes.
