### ISSUE TITLE
Unix timestamps after Sep 13 2020 are rejected as graph start/end arguments

### ISSUE THREAD

**Issue by nuno-silva** [Cacti/cacti#3245]
**Describe the bug**

The `graph_start` and `graph_end` request variables in `graph_image.php` only accept values less than `1600000000`, which is `Sun Sep 13 12:26:40 2020` in UTC (just 7 months from now!).

Note: at least `graph_json.php`, `graph_xport.php` and `remote_agent.php` are also affected.

**To Reproduce**
Steps to reproduce the behaviour:
1. Obtain the ID of any graph.
2. Open `http://host.example.com/cacti/graph_image.php?local_graph_id=123&graph_end=1600000000&disable_cache=true`.
3. Bug: graph will not display the desired timespan and will instead ignore the `graph_end` variable.
4. Repeat step 2 using `1599999999` if you wanna see it working, or just look at my screenshots.

**Expected behavior**
The example URL should display a timespan ranging from `<today>` until Sep 13 2020.

**Screenshots**
  * `graph_image.php` using `graph_end=1599999999`

![1599999999](https://user-images.githubusercontent.com/6935057/74104686-082eb600-4b4f-11ea-8489-b347676e4e35.png)

  * `graph_image.php` using `graph_end=1600000000`

![1600000000](https://user-images.githubusercontent.com/6935057/74104687-095fe300-4b4f-11ea-8004-192d316fb531.png)

**Desktop:**
N/A

**Smartphone:**
N/A

**Additional context**
Relevant lines of code:

https://github.com/Cacti/cacti/blob/bb619ef6695e5faa4f52b03d07519522702793e4/graph_image.php#L82-L90

My suggestion is to compare these timestamps with something like `now + 1 year` instead of an hard-coded one. I don't mind preparing a pull request to fix this after further discussion about a solution.

**Comment by netniV** [comment]
Should now be resolved, thanks!

**Comment by nuno-silva** [comment]
Thank you for the fix, but you just moved the problem 16 years into the future :stuck_out_tongue:

**Comment by netniV** [comment]
I did, well spotted 👍 

If you're still using this version of the software then, I'd worry 😱

**Comment by nuno-silva** [comment]
Well, I'd worry, too, but my point is that someone will have to deal with this again in the future before the 16 years, no matter the version :stuck_out_tongue:

**Comment by netniV** [comment]
It does, but by then we will hopefully be all on 64-bit so we can then go above the 32-bit barrier :)

**Comment by paulgevers** [comment]
@netniV I guess this issue is present in (much) older versions of Cacti. Do you happen to know when it was introduced? I probably need to fix Cacti in the stable and oldstable releases as well as let the Ubuntu people know about it.

**Comment by TheWitness** [comment]
This setting goes back to at least 0.8.7.  So, anything after that has this clipping boundary to future times.
