### ISSUE TITLE
When upgrading with remote collectors, sync status does not always return properly

### ISSUE THREAD

**Issue by reubenfarrelly** [Cacti/cacti#3246]
I've just upgraded from 1.2.8 to 1.2.9 via CLI, and seeing the following warnings logged:

10/Feb/2020 13:48:46 - INSTALL-CLI: always: Installation has now completed, you may launch the web console
10/Feb/2020 13:48:46 - INSTALL-CLI: always: Finished installation...
10/Feb/2020 13:48:46 - INSTALL: always: Installation was started at 2020-02-10 02:48:42, completed at 2020-02-10 02:48:46
10/Feb/2020 13:48:46 - INSTALL: always: No Remote Data Collectors found for full syncronization
10/Feb/2020 13:48:46 - CMDPHP PHP ERROR WARNING Backtrace: (/cli/install_cacti.php[209]:Installer::beginInstall(), /lib/installer.php[3307]:Installer->install(), /lib/installer.php[2843]:Installer::fullSyncDataCollectors(), /lib/installer.php[3369]:CactiErrorHandler())
10/Feb/2020 13:48:46 - ERROR PHP WARNING: sizeof(): Parameter must be an array or an object that implements Countable in file: /var/www/cacti.reub.net/htdocs/lib/installer.php on line: 3369
10/Feb/2020 13:48:46 - INSTALL: always: Finished UPGRADE Process for v1.2.9
10/Feb/2020 13:48:46 - CMDPHP PHP ERROR Backtrace: (/cli/install_cacti.php[209]:Installer::beginInstall(), /lib/installer.php[3307]:Installer->install(), /lib/installer.php[2825]:Installer->upgradeDatabase(), /lib/installer.php[3238]:cacti_version_compare(), /lib/functions.php[5017]:version_to_decimal(), /lib/functions.php[5086]:hexdec(), CactiErrorHandler())
10/Feb/2020 13:48:46 - ERROR PHP DEPRECATED: Invalid characters passed for attempted conversion, these have been ignored in file: /var/www/cacti.reub.net/htdocs/lib/functions.php on line: 5086
10/Feb/2020 13:48:46 - INSTALL: always: NOTE: Using temporary file for db cache: /tmp/cdugi6zHs
10/Feb/2020 13:48:46 - INSTALL: always: Switched from to /tmp/cdugi6zHs
10/Feb/2020 13:48:46 - INSTALL: always: No tables where found or selected for conversion
10/Feb/2020 13:48:46 - INSTALL: always: Starting UPGRADE Process for v1.2.9
10/Feb/2020 13:48:42 - INSTALL: always: Setting PHP Option memory_limit = -1
10/Feb/2020 13:48:42 - INSTALL: always: Setting PHP Option max_execution_time = 0
10/Feb/2020 13:48:42 - INSTALL-CLI: always: Starting installation...
10/Feb/2020 13:48:42 - INSTALL-CLI: always: Installer prepared for UPGRADE action

Line 5086 of functions.php looks like:

        }

        return hexdec($newver) * 1000 + $int;
}

It appears that the upgrade has gone through succesfully but the warning and deprecation error probably should be fixed.

This is with Gentoo Linux, Apache with php-7.4.2 .

[I was using the CLI to upgrade as the web installer was getting stuck due to ""aborted due to no eula acceptance" even though I was never presented the EULA to accept, but that's presumably a separate and unrelated issue].

**Comment by netniV** [comment]
EULA is the very first screen on an install or upgrade. Strange you never saw it.

**Comment by netniV** [comment]
OK, so the problem here is with the `fullSyncDataCollectors()` not returned a valid status object with the success and failed elements (which should both be arrays).  Also, the use of sizeof vs cacti_sizeof (which handles some nuances that PHP introduced were it no longer likes certain types being passed to sizeof).

**Comment by netniV** [comment]
I believe that this should now be resolved.  I don't know if you are able to replicate and test again.

**Comment by reubenfarrelly** [comment]
If it's a problem still when 1.3.0 is released then I'll open another bug then referencing this one.
