### ISSUE TITLE
mo files does not update "PO-Revision-Date" attribute

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#3247]
In mo file, the attribute "PO-Revision-Date" is only one timestamp in metainfo.
i18n utility also read this attribute for some checking.

I prefer to update PO-Revision-Date in po files before or during building mo files

**Comment by TheWitness** [comment]
@ddb4github,

@netniV continues to ignore these.  He is planning a release next weekend.  Maybe we can include them for the latest release.

**Comment by netniV** [comment]
It's something that should be sone manually by the scripts as they are generated.  The translate software also appears to do that too.

**Comment by ddb4github** [comment]
> It's something that should be sone automatically by the scripts as they are generated. The translate software also appears to do that too.

In .po file, `POT-Creation-Date` is always updated now. Maybe by scripts or other translate utility.
But .mo only use `PO-Revision-Date`

**Comment by ddb4github** [comment]
In latest .mo files,  `PO-Revision-Date: 2019-07-11 17:10+0000`
In latest .po files, `POT-Creation-Date: 2020-03-22 12:15-0400`

**Comment by TheWitness** [comment]
@ddb4github , this is due to our translate site not being tied into the 1.2.x branch.  I working on updating the "#fuzzy" translations now through PO Edit.  They will be in before I turn in for the night, at least most of them.

There was a lot done this weekend.  I'll hook up with you in the morning.

**Comment by TheWitness** [comment]
All the latest *.po files have been updated to the latest release.  The MO files released should match the GitHub po files.

**Comment by netniV** [comment]
Not sure if this will stay resolved since most translation comes via the WebLate software.

**Comment by TheWitness** [comment]
The msgmerg program, until very recently, did not have an option to update the revision date.  I think weblate does.
