### ISSUE TITLE
Error on upgrade to 1.2.9

### ISSUE THREAD

**Issue by patoberli** [Cacti/cacti#3248]
**Describe the bug**
Run the upgrade, but the db upgrade failed.
Error message:
	ALTER TABLE host_snmp_cache MODIFY COLUMN snmp_index VARCHAR(255) NOT NULL default ""	[Fail]

I'm still using Antelope database, if that has any influence (is there a way to switch it to Barracuda?).

Log:
2020/02/10 09:48:26 - INSTALL: always: Installation was started at 2020-02-10 08:47:29, completed at 2020-02-10 08:48:26
2020/02/10 09:48:26 - INSTALL: always: WARNING: One or more upgrades failed to install correctly
2020/02/10 09:48:26 - INSTALL: always: Finished UPGRADE Process for v1.2.9
2020/02/10 09:48:22 - INSTALL: always: Upgrading from v1.2.7 (DB 1.2.9 (DB: 1.2.7)) to v1.2.8
2020/02/10 09:48:22 - INSTALL: always: NOTE: Using temporary file for db cache: /tmp/cdu0mGiTJ
2020/02/10 09:48:22 - INSTALL: always: Switched from to /tmp/cdu0mGiTJ
2020/02/10 09:48:22 - INSTALL: always: Converting Table #130 'version'
2020/02/10 09:48:22 - INSTALL: always: Converting Table #129 'vdef_items'
2020/02/10 09:48:22 - INSTALL: always: Converting Table #128 'aggregate_graph_templates'
2020/02/10 09:48:21 - INSTALL: always: Converting Table #127 'aggregate_graph_templates_item'
2020/02/10 09:48:21 - INSTALL: always: Converting Table #126 'aggregate_graphs'
2020/02/10 09:48:21 - INSTALL: always: Converting Table #125 'aggregate_graphs_graph_item'
2020/02/10 09:48:21 - INSTALL: always: Converting Table #124 'aggregate_graphs_items'
2020/02/10 09:48:21 - INSTALL: always: Converting Table #123 'aggregate_graph_templates_graph'
2020/02/10 09:48:20 - INSTALL: always: Converting Table #122 'automation_devices'
2020/02/10 09:48:20 - INSTALL: always: Converting Table #121 'automation_graph_rule_items'
2020/02/10 09:48:20 - INSTALL: always: Converting Table #120 'automation_graph_rules'
2020/02/10 09:48:20 - INSTALL: always: Converting Table #119 'automation_ips'
2020/02/10 09:48:20 - INSTALL: always: Converting Table #118 'automation_match_rule_items'
2020/02/10 09:48:20 - INSTALL: always: Converting Table #117 'automation_networks'
2020/02/10 09:48:20 - INSTALL: always: Converting Table #116 'automation_processes'
2020/02/10 09:48:20 - INSTALL: always: Converting Table #115 'automation_snmp'
2020/02/10 09:48:20 - INSTALL: always: Converting Table #114 'automation_snmp_items'
2020/02/10 09:48:19 - INSTALL: always: Converting Table #113 'automation_templates'
2020/02/10 09:48:19 - INSTALL: always: Converting Table #112 'automation_tree_rule_items'
2020/02/10 09:48:19 - INSTALL: always: Converting Table #111 'cdef'
2020/02/10 09:48:19 - INSTALL: always: Converting Table #110 'automation_tree_rules'
2020/02/10 09:48:18 - INSTALL: always: Converting Table #109 'color_template_items'
2020/02/10 09:48:18 - INSTALL: always: Converting Table #108 'cdef_items'
2020/02/10 09:48:18 - INSTALL: always: Converting Table #107 'color_templates'
2020/02/10 09:48:18 - INSTALL: always: Converting Table #106 'data_debug'
2020/02/10 09:48:18 - INSTALL: always: Converting Table #105 'user_log'
2020/02/10 09:48:18 - INSTALL: always: Converting Table #104 'colors'
2020/02/10 09:48:17 - INSTALL: always: Converting Table #103 'data_input_data'
2020/02/10 09:48:16 - INSTALL: always: Converting Table #102 'data_input'
2020/02/10 09:48:16 - INSTALL: always: Converting Table #101 'data_input_fields'
2020/02/10 09:48:16 - INSTALL: always: Converting Table #100 'data_local'
2020/02/10 09:48:16 - INSTALL: always: Converting Table #99 'data_source_profiles'
2020/02/10 09:48:15 - INSTALL: always: Converting Table #98 'data_source_profiles_cf'
2020/02/10 09:48:15 - INSTALL: always: Converting Table #97 'data_source_profiles_rra'
2020/02/10 09:48:15 - INSTALL: always: Converting Table #96 'data_source_purge_action'
2020/02/10 09:48:15 - INSTALL: always: Converting Table #95 'data_source_stats_daily'
2020/02/10 09:48:14 - INSTALL: always: Converting Table #94 'data_source_purge_temp'
2020/02/10 09:48:14 - INSTALL: always: Converting Table #93 'data_source_stats_hourly'
2020/02/10 09:48:14 - INSTALL: always: Converting Table #92 'data_source_stats_hourly_cache'
2020/02/10 09:48:13 - INSTALL: always: Converting Table #91 'data_source_stats_monthly'
2020/02/10 09:48:13 - INSTALL: always: Converting Table #90 'data_source_stats_hourly_last'
2020/02/10 09:48:12 - INSTALL: always: Converting Table #89 'data_source_stats_weekly'
2020/02/10 09:48:11 - INSTALL: always: Converting Table #88 'data_template_data'
2020/02/10 09:48:11 - INSTALL: always: Converting Table #87 'data_template'
2020/02/10 09:47:53 - INSTALL: always: Converting Table #86 'data_source_stats_yearly'
2020/02/10 09:47:52 - INSTALL: always: Converting Table #85 'data_template_rrd'
2020/02/10 09:47:52 - INSTALL: always: Converting Table #84 'external_links'
2020/02/10 09:47:52 - INSTALL: always: Converting Table #83 'graph_template_input'
2020/02/10 09:47:51 - INSTALL: always: Converting Table #82 'graph_local'
2020/02/10 09:47:50 - INSTALL: always: Converting Table #81 'graph_template_input_defs'
2020/02/10 09:47:50 - INSTALL: always: Converting Table #80 'graph_templates'
2020/02/10 09:47:50 - INSTALL: always: Converting Table #79 'graph_templates_gprint'
2020/02/10 09:47:49 - INSTALL: always: Converting Table #78 'graph_templates_graph'
2020/02/10 09:47:48 - INSTALL: always: Converting Table #77 'graph_templates_item'
2020/02/10 09:47:48 - INSTALL: always: Converting Table #76 'host_graph'
2020/02/10 09:47:48 - INSTALL: always: Converting Table #75 'host'
2020/02/10 09:47:48 - INSTALL: always: Converting Table #74 'graph_tree_items'
2020/02/10 09:47:48 - INSTALL: always: Converting Table #73 'graph_tree'
2020/02/10 09:47:48 - INSTALL: always: Converting Table #72 'host_snmp_query'
2020/02/10 09:47:45 - INSTALL: always: Converting Table #71 'host_snmp_cache'
2020/02/10 09:47:45 - INSTALL: always: Converting Table #70 'host_template'
2020/02/10 09:47:45 - INSTALL: always: Converting Table #69 'host_template_graph'
2020/02/10 09:47:45 - INSTALL: always: Converting Table #68 'host_template_snmp_query'
2020/02/10 09:47:44 - INSTALL: always: Converting Table #67 'mac_track_aggregated_ports'
2020/02/10 09:47:44 - INSTALL: always: Converting Table #66 'mac_track_approved_macs'
2020/02/10 09:47:44 - INSTALL: always: Converting Table #65 'mac_track_devices'
2020/02/10 09:47:44 - INSTALL: always: Converting Table #64 'mac_track_device_types'
2020/02/10 09:47:43 - INSTALL: always: Converting Table #63 'mac_track_interfaces'
2020/02/10 09:47:43 - INSTALL: always: Converting Table #62 'mac_track_interface_graphs'
2020/02/10 09:47:43 - INSTALL: always: Converting Table #61 'mac_track_dot1x'
2020/02/10 09:47:42 - INSTALL: always: Converting Table #60 'mac_track_ips'
2020/02/10 09:47:42 - INSTALL: always: Converting Table #59 'mac_track_ip_ranges'
2020/02/10 09:47:41 - INSTALL: always: Converting Table #58 'mac_track_macwatch'
2020/02/10 09:47:41 - INSTALL: always: Converting Table #57 'mac_track_ports'
2020/02/10 09:47:41 - INSTALL: always: Converting Table #56 'mac_track_macauth'
2020/02/10 09:47:40 - INSTALL: always: Converting Table #55 'mac_track_oui_database'
2020/02/10 09:47:40 - INSTALL: always: Converting Table #54 'mac_track_processes'
2020/02/10 09:47:39 - INSTALL: always: Converting Table #53 'mac_track_scanning_functions'
2020/02/10 09:47:39 - INSTALL: always: Converting Table #52 'mac_track_scan_dates'
2020/02/10 09:47:39 - INSTALL: always: Converting Table #51 'mac_track_sites'
2020/02/10 09:47:39 - INSTALL: always: Converting Table #50 'mac_track_snmp_items'
2020/02/10 09:47:39 - INSTALL: always: Converting Table #49 'mac_track_snmp'
2020/02/10 09:47:39 - INSTALL: always: Converting Table #48 'mac_track_temp_ports'
2020/02/10 09:47:39 - INSTALL: always: Converting Table #47 'plugin_config'
2020/02/10 09:47:38 - INSTALL: always: Converting Table #46 'mac_track_vlans'
2020/02/10 09:47:38 - INSTALL: always: Converting Table #45 'plugin_db_changes'
2020/02/10 09:47:38 - INSTALL: always: Converting Table #44 'plugin_realms'
2020/02/10 09:47:38 - INSTALL: always: Converting Table #43 'plugin_hooks'
2020/02/10 09:47:38 - INSTALL: always: Converting Table #42 'poller_command'
2020/02/10 09:47:38 - INSTALL: always: Converting Table #41 'poller'
2020/02/10 09:47:38 - INSTALL: always: Converting Table #40 'poller_data_template_field_mappings'
2020/02/10 09:47:36 - INSTALL: always: Converting Table #39 'poller_item'
2020/02/10 09:47:36 - INSTALL: always: Converting Table #38 'poller_output'
2020/02/10 09:47:36 - INSTALL: always: Converting Table #37 'poller_output_boost'

**To Reproduce**
Old version was 1.2.7, run the upgrade as usual. Failed with the DB Upgrade.

**Desktop (please complete the following information):**
 - OS: Debian 9.11

**Comment by patoberli** [comment]
Little update. Just tried from the CLI, here I get an error message:
/var/www/cli]# php upgrade_database.php 
Upgrading from v1.2.7
Upgrading from v1.2.7 (DB 1.2.7) to v1.2.8
+x+++
################################
[Fail]       -   DB Exec Failed!, Error 1071: Specified key was too long; max key length is 767 bytes
+------------------------------+
ALTER TABLE host_snmp_cache MODIFY COLUMN snmp_index VARCHAR(255) NOT NULL default ""

**Comment by bmfmancini** [comment]
Make sure you have large_prefix=1 in my
Cnf that error usually means you don't

**Comment by patoberli** [comment]
That is correct, that was the error. Please see my edited second post.

**Comment by bmfmancini** [comment]
Yea sorry I saw it after I sent that
If you want to update the dB version you can run the dB update script
Running Database Upgrade Script

sudo -u cacti php -q cli/upgrade_database.php --forcever=`cat
include/cacti_version`

<https://github.com/Cacti/cacti/blob/develop/README.md#updating-cacti-version-in-database>Updating
Cacti Version in Database

update version set cacti = '1.1.38';

**Comment by patoberli** [comment]
I already run that script, to fix my initial error (after modifying my my.cnf).
The only remaining questions I have are (clarified them):
Two things, first the upgrade let me continue although I had those two options not set, should that be blocked?
Secondly, is there a way on how to migrate the database from Antelope to Barracuda?

**Comment by netniV** [comment]
https://dev.mysql.com/doc/refman/5.6/en/innodb-file-format-enabling.html

The first point is that it should now block that, we will have to investigate.
