### ISSUE TITLE
Cacti 1.2.9: New graph doesn't appear in the tree

### ISSUE THREAD

**Issue by Izmenoff** [Cacti/cacti#3249]
Created new device, created graphs for it, device placed to the tree.
If create additional graph for it device, it doesn't appear in the tree. Device will be contain only old graphs.

**Comment by netniV** [comment]
Can you provide any evidence of this? Or steps to replicate?

**Comment by Izmenoff** [comment]
1. create a new device with some graphs (for example let it be 3 graphs)
2. place the divice in a tree, you can see your 3 gpraphs
3. go to management-dvice and add aditional graphs to the deivce.
4. new graphs don't appear, you can see only 3 graphs, which you created at first

**Comment by netniV** [comment]
OK, I'll give it a test.  Just be clear, which graph templates did you use?

**Comment by Izmenoff** [comment]
Net-SNMP

**Comment by mrjackson** [comment]
I also have this issue on 1.2.12 (and have seen it before on older versions).
Even deleting the device from the tree and re-adding it still doesn't show the new graphs (custom), but it works fine on my dev system that I exported them from.
