### ISSUE TITLE
Add configurable auto-logout and page-reload options.

### ISSUE THREAD

**Issue by CapitalF** [Cacti/cacti#325]
Feature request.

Please add configurable auto-logout and page-refresh options. I seem to remember previous versions of Cacti having better behavior.

Cacti 1.0.3 on Linux. Browser used is Chromium on Linux.

**Comment by cigamit** [comment]
This is reasonable.  We had the exact debate, and the decision was to use the gc_maxlifetime as the timeout.  We will revisit though.

**Comment by CapitalF** [comment]
Thanks. Also, in case you don't read my comment on #326, enabling Authentication Cookies gives me a much better user experience. Suggest enabling by default since it seems to be currently disabled by default.

**Comment by cigamit** [comment]
Enabling Authentication Cookies by default now.  So, closing.  Thanks.
