### ISSUE TITLE
Upgrade 1.2.9 csrf-secret.php issue

### ISSUE THREAD

**Issue by KnoAll** [Cacti/cacti#3251]
Getting an error on upgrade complaining of permissions issue on crsf-secret.php. Upon investigating that file is not present in the referenced location. 

![image](https://user-images.githubusercontent.com/7632685/74176157-0109b580-4bec-11ea-9ae9-4b9ff574230d.png)

-rw-rw-r--  1 cacti cacti  7088 Feb  9 17:14 csrf-magic.js
-rw-rw-r--  1 cacti cacti 14786 Feb  9 17:14 csrf-magic.php
-rw-rw-r--  1 cacti cacti    40 Feb  9 17:14 index.php
-rw-rw-r--  1 cacti cacti  1300 Feb  9 17:14 LICENSE
-rw-rw-r--  1 cacti cacti  2636 Feb  9 17:14 NEWS
-rw-rw-r--  1 cacti cacti  6382 Feb  9 17:14 README

Upgrading from 1.2.8 on Raspbian Buster

**Comment by KnoAll** [comment]
Apologies. Discovered this was an error where apache needed access to this location. updated permissions and file was automatically generated.

**Comment by netniV** [comment]
Apache should only have access to that file one time, once the secret is generated, it should not be modifiable by the website.
