### ISSUE TITLE
Upgrade to 1.2.9 fails in dark theme

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#3252]
I started to upgrade from 1.2.7 to 1.2.9. I kept getting a blank screen. Somehow, I knew it was a theme problem. But I had a lot of difficulty trying to change the theme, I got stuck in a bad loop. In the end, the best fix was this:

```
mysql> select * from settings where name like '%theme%';
+----------------+--------+
| name           | value  |
+----------------+--------+
| install_theme  | dark   |
| selected_theme | modern |
+----------------+--------+
2 rows in set (0.00 sec)

mysql> update settings set value='modern' where name='install_theme';
Query OK, 1 row affected (0.00 sec)
Rows matched: 1  Changed: 1  Warnings: 0
```

That got me through it. 

Here's what the installer looked like:
![blank_install](https://user-images.githubusercontent.com/12864741/74206564-2ffa4880-4c39-11ea-83be-4ce7384f81bd.png)

I tried the refresh button in the corner numerous times ... no dice!

**Comment by netniV** [comment]
Unfortunately, I have not been able to reproduce this.  If you can provide any more details or steps to reproduce then I can take another look.
