### ISSUE TITLE
Installer shows script owner rather than running user for suggested chown command

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#3254]
The permissions commands suggestion box is awfully useful.

But the user:group is never accurate on my system. I run the webserver as user 'apache'. I imagine others do as well. The installer always suggests to 'chown -R root:root ...'. Would it be relatively easy to determine the correct user:group of the running webserver through an environment variable and then reflect that in the permissions suggestion?

No worries if it's too much hassle or too error prone. It's just something I've been thinking of for awhile.

**Comment by netniV** [comment]
I think someone has done something with that, because on my system, it showed the owner of the folder rather than website user.  I had planned to investigate that, but now I will definitely have to because theirs an open issue ;-)

**Comment by netniV** [comment]
Someone had been tampering, so i've tampered again and improved on my original stuff to use the posix functions if they are available for speedier use.
