### ISSUE TITLE
Upgrade to 1.2.9 - No Remote Data Collectors Found

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#3255]
Here is a log snippet from my 1.2.7 -> 1.2.9 upgrade:

```
2020/02/10 18:58:11 - INSTALL: always: Spawning background process: /usr/local/php/bin/php '/cacti/cacti-1.2.9-prod/install/background.php' 1581386291.6681
2020/02/10 18:58:12 - INSTALL: Checking arguments
2020/02/10 18:58:12 - INSTALL: always: Setting PHP Option max_execution_time = 0
2020/02/10 18:58:12 - INSTALL: always: Setting PHP Option memory_limit = -1
2020/02/10 18:58:12 - INSTALL: always: Starting UPGRADE Process for v1.2.9
2020/02/10 18:58:12 - INSTALL: always: Found 3 tables to convert
2020/02/10 18:58:12 - INSTALL: always: Converting Table #1 'host_snmp_cache'
2020/02/10 18:58:29 - INSTALL: always: Converting Table #2 'poller_command'
2020/02/10 18:58:29 - INSTALL: always: Converting Table #3 'poller_resource_cache'
2020/02/10 18:58:34 - INSTALL: always: Switched from  to /tmp/cduVqWbdA
2020/02/10 18:58:34 - INSTALL: always: NOTE: Using temporary file for db cache: /tmp/cduVqWbdA
2020/02/10 18:58:34 - INSTALL: always: Upgrading from v1.2.7 (DB 1.2.9 (DB: 1.2.7)) to v1.2.8
2020/02/10 18:58:58 - INSTALL: always: Finished UPGRADE Process for v1.2.9
2020/02/10 18:59:00 - INSTALL: always: No Remote Data Collectors found for full syncronization
2020/02/10 18:59:00 - INSTALL: always: Installation was started at 2020-02-11 01:58:12, completed at 2020-02-11 01:59:00
```

Note this entry:
```
2020/02/10 18:59:00 - INSTALL: always: No Remote Data Collectors found for full syncronization
```

I actually have 4 remote data collectors ... so I'm not sure why they weren't found? I can do my own sync, but I think we had an intention to automate this on an upgrade, which may not be working.

**Comment by bmfmancini** [comment]
was it successful after you did a manual sync ?

**Comment by eschoeller** [comment]
Oh yes, it’s all working just fine now. I think eventually they sync’d themselves, just as they normally do, but it does not appear to have occurred during the actual upgrade process

**Comment by netniV** [comment]
I think that message merely means that it couldn't find any needing a full sync.  Probably because you already had 1.2.9 across to them via the background polling replication before you finished the install.

**Comment by netniV** [comment]
This may have been resolved as part of some recent installer changes that are upcoming in [v1.2.10](https://github.com/Cacti/cacti/milestone/14)

**Comment by TheWitness** [comment]
I just did a code review, and the code is sound.  This message will appear if:

1) You don't have any remote data collectors, 
2) Your remote data collectors are disabled.
