### ISSUE TITLE
Erratic Zooming Behavior

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#3256]
I'm on 1.2.9 now, and I'm still seeing erratic behavior with zooming. Here is a snippet of the behavior. You'll see some graphs update, some don't. I can't specifically isolate the why/when yet. I thought this was strictly related to the Dark Theme, but I found it present in the Modern theme too. 

![modern_zooming](https://user-images.githubusercontent.com/12864741/74209794-828e3180-4c46-11ea-8581-4d0596b18f5f.gif)

![dark_zooming](https://user-images.githubusercontent.com/12864741/74209622-d2202d80-4c45-11ea-9593-c324c1c07de5.gif)

I'm playing around with where the mouse is positioned after I perform the zoom. Maybe that has something to do with it. I'm also wondering if it has something to do with when you select a preset, and then perform a zoom.

**Comment by netniV** [comment]
Using chrome with the latest 1.2.9, I'm not seeing that zooming issue.

**Comment by TheWitness** [comment]
We need to see the debug > network panel output.

**Comment by eschoeller** [comment]
Hey, sorry I dropped off the face of the planet. I'm on 1.2.11 now. I'm still having zooming problems.

How exactly should I capture the network panel output?

**Comment by eschoeller** [comment]
OK, I saved it as a .har file. In this case I'm looking at a page with 17 graphs. 10 of them zoomed correctly. The others didn't. When I initiated the zoom I selected the middle of a graph and pulled it clear across to the right, past the graph image, and released the mouse. The graph I was trying to zoom did not update. 

[cacti_har.zip](https://github.com/Cacti/cacti/files/4526651/cacti_har.zip)

**Comment by TheWitness** [comment]
@eschoeller, I've added a few checks so that when you are viewing inline, all graphs have to be rendered before another stack of graph render requests are tossed into the system.  So, in a case where you set the refresh to be every second, and it takes one of those graphs 5 to render, the rest will wait until that slow one renders.  Update just the realtime.js.

**Comment by TheWitness** [comment]
Oh god.  That fix was for realtime.  Need to go take my medication.  That'd be beer or wine.
