### ISSUE TITLE
Your Cacti Server v1.2.4 has been installed/updated with errors - Pls Help

### ISSUE THREAD

**Issue by cjolly3053** [Cacti/cacti#3258]
I know I know all that will be said BUT I have a production server STUCK on 1.0.2 (beta) and have been trying for months to somehow either get the data out or upgrade the sql database.

This is as close as I have got with a fresh install from apt-get cacti which is showing version 1.2.4?

I have tried repairing the database and upgrading via CLI and it appears to upgrade as the version in the sql table is 1.2.4

Can somebody help this troubled admin get his Cacti upgraded with yelling at me too much about backups and beta and all that stuff. I feel this is probably something simple somewhere.

My 1.0.2 version is actually running and still collecting data but just worry if something happens I will be worse off.

Please help.

**Comment by bmfmancini** [comment]
hmm ok let's check a couple of things 

1.) what error are you getting when trying to update? (cacti.log)
maybe try to update to 1.0.2 release then upgrade from there?
2.) what does your my.cnf look like ? do you have the updated recommendations/requirements
the bigger ones is larg_prefix = 1 is big one

**Comment by cjolly3053** [comment]
Yes on #2 went with the larger reqs

#1 the log only has one entry and it’s an admin login line
I see other logs in here and a cacti.log thats zipped? GZ?

This is a VM so I can repeat this a number of times very easily return back to a good starting point.

--------------------------------
Chris Jolly
cjolly3053@gmail.com

**Comment by bmfmancini** [comment]
ok when you try going through the upgrade proccess what do you see ?

**Comment by cjolly3053** [comment]
So this is odd… Saying trying to update to 1.2.4 but I downloaded 1.0.2 and moved the cacti directory and dropped the old cacti database.

Let me check the sqldump cause it should NOT being saying that…

Version in the table says 1.2.0??? Would that be right for 1.0.2 beta?

--------------------------------
Chris Jolly
cjolly3053@gmail.com

**Comment by cjolly3053** [comment]
Trying as is I got this…



--------------------------------
Chris Jolly
cjolly3053@gmail.com

**Comment by bmfmancini** [comment]
I don't think the right

Maybe use the db script to force the version to 1.0.2 because if the
installer sees 1.2.0 I bet you won't get the dB updates that have been made
between 1.0.2 and 1.2.0 which I'm sure would be part of why the Install is
failing

**Comment by cjolly3053** [comment]
Interesting…. OK now I do feel stupid…. It’s NOT that old a beta…

Says 1.2.0 Beta… was getting my 2 and 0 backwards sorry…

So website says 1.2.0 - Beta 1

--------------------------------
Chris Jolly
cjolly3053@gmail.com

**Comment by bmfmancini** [comment]
ah ok 

so when you perfrom the update to 1.2.4 where does the installer take a dump ?

**Comment by cjolly3053** [comment]
So get all the pages and checks and get to the upgrade page with the 2 status bars

Then it goes to the page I sent:

But odd thing is I downloaded on accident 1.0.2 cacti and it thought it was higher version?

Lets rollback this VM and try again…lol Sorry about the confusion. Got a little backwards with my numbers :(

--------------------------------
Chris Jolly
cjolly3053@gmail.com

**Comment by cjolly3053** [comment]
So you suggest trying 1.2.0 right to upgrade to first?

--------------------------------
Chris Jolly
cjolly3053@gmail.com

**Comment by bmfmancini** [comment]
lets try moving out of the beta version first so 1.2.0 release if that goes well then try 1.2.4 or even 1.2.8 latest release

**Comment by cjolly3053** [comment]
So is there something somewhere that might have caused the page to think 1.2.4? Maybe cached????

I moved the whole cacti directory and used the DB from the beta.

--------------------------------
Chris Jolly
cjolly3053@gmail.com

**Comment by cjolly3053** [comment]
Ok so interestingly enough there was no upgrade since it went from 1.2.0 > 1.2.0

Tried running the upgrade_database.php but would not do it since it was beta 1.2.0

Everything comes up but no devices listed and no graphs. RRA’s are there and permissions appear correct.

--------------------------------
Chris Jolly
cjolly3053@gmail.com

**Comment by cjolly3053** [comment]
So I read about this somewhere else but I did a forcever=1.1.38 and it looks like we updated to 1.2.0

Checking some graphs but now I have all my devices and graphs so just want to check some real quick and we will try another step.

Can I go from 1.2.0 > whatever or do I need to step?

--------------------------------
Chris Jolly
cjolly3053@gmail.com

**Comment by netniV** [comment]
You really should be off 1.2.0 beta.  In fact, I would get to 1.2.9 as soon as you can since there's been hundreds of bug fixes since then.

**Comment by bmfmancini** [comment]
@cjolly3053  you should be able to update right up to 1.2.9 now although for me I am waiting until the release code because right now I see alot of open issues with 1.2.9 but that's my preference

**Comment by netniV** [comment]
This is really a kind of post that should be on the forums where more people can help.  For now, I'm going to close this. If you are still having issues, create a post there and people can assist.
