### ISSUE TITLE
Auto-logout/inactivity and auto-page-refresh irrational behavior

### ISSUE THREAD

**Issue by CapitalF** [Cacti/cacti#326]
If you have multiple pages open to your cacti installation and are automatically logged out after a period of inactivity, log in again on one of the window/pages, and then refresh the other window, it logs you out again. This is because Cacti actually puts your browser on a "logout" URL (logout.php?action=timeout), and reloading the URL causes you to log out again.

Additionally, random inappropriate logouts of Cacti happen if I have multiple tabs open and leave one of them idle. The user will be logged out for inactivity even though he may be actively using other tabs.

All-in-all, the page refresh and session timeout behavior of Cacti 1.0 is foobar.

Cacti 1.0.3 on Linux. Browser used is Chromium on Linux.

**Comment by cigamit** [comment]
If you enable Authentication cookies, you won't have this problem.  Otherwise, you should increase your gc_maxlifetime to some larger value and restart apache.

**Comment by CapitalF** [comment]
Thanks for your reply. I was testing Authentication Cookies today and agree that it fixes this issue.

However, Authentication Cookies seems to be disabled by default. Enabling it by default might be a better idea. It certain gives a better user experience for me.
