### ISSUE TITLE
When a device is added, populate the created date/time

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3260]
Hey Guys 

one thing that would be awesome to have is a column in the DB that shows when a device was added by autom8 or other means 

this will allow for device exports to import the device names to systems like ServiceNow to build Configuration Items 

instead of having to export all of the host's tables each time to look for new additions you would be able to leverage that column's data 

We have used the poll count to check if a device is new but that's not the best way since it could be reset if a device is removed and re-added 

It doesn't have to be displayed in the GUI persay it could just be a data point to be extracted if needed 

Thanks !

**Comment by TheWitness** [comment]
So, you are asking for a 'created_date' column?  Can it be hidden or should it be visible?

**Comment by bmfmancini** [comment]
For my purpose it can be hidden just Information on the dB side for device
list export

It might also be valuable to be visible as well

**Comment by TheWitness** [comment]
In the near term, you can do the following:

```sql
ALTER TABLE host ADD COLUMN create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP();
```
