### ISSUE TITLE
Refresh will randomly jump

### ISSUE THREAD

**Issue by tyit** [Cacti/cacti#3263]
**Describe the bug**
Refresh will randomly jump bug ？
![image](https://user-images.githubusercontent.com/31933126/74605800-53743600-5106-11ea-8dfd-ebe9288b98c7.png)

**Desktop (please complete the following information):**
 - OS: [ OSX ]
 - Browser [chrome]
 - Cacti Version 1.2.9

**Additional context**

![image](https://user-images.githubusercontent.com/31933126/74605777-0db76d80-5106-11ea-8126-664228e4a1a8.png)

 Refresh will randomly jump correct

**Comment by cigamit** [comment]
What version of RRD Tool?  The spacing is completely handled by it, we don't have any control over it.

**Comment by tyit** [comment]
![image](https://user-images.githubusercontent.com/31933126/74626010-42b8d400-5189-11ea-8f66-b5dc3b334006.png)
![image](https://user-images.githubusercontent.com/31933126/74626110-a216e400-5189-11ea-897d-27b728357617.png)
![image](https://user-images.githubusercontent.com/31933126/74626232-05087b00-518a-11ea-8868-c9180e6111d4.png)

RRDtool 1.4.8
Nginx Version: Nginx/1.16.x
PHP 5.4.x (cli)
PHP 5.4.x (fpm-fcgi)
mysql 5.6.x
rrdtool version problem? Thank you so much. cacti getting better and better

**Comment by tyit** [comment]
![image](https://user-images.githubusercontent.com/31933126/74708953-e9b87100-5258-11ea-9d3e-d7ea17966735.png)
RRDtool 1.6.0 
I changed the version of rrdtool and the problem still exists

**Comment by netniV** [comment]
I believe that there is already an issue open about this and it comes down to the parameters being slightly different on occasion.

**Comment by TheWitness** [comment]
Are these the same exact graphs, or different graphs with the same local_graph_id?  That'll make a big difference in understanding what is going on.

**Comment by tyit** [comment]
@TheWitness 

Hi  Are these the same exact graphs.

**Comment by netniV** [comment]
> @TheWitness
> 
> Hi Are these the same exact graphs.

Not sure you actually answered there ;-)

**Comment by TheWitness** [comment]
@tyit, first you Test 2 graph is using a proportional font.  Can you change it back to a fixed width font.  Second, what image format are you using?  Also, when you get these rendering errors, can you please show the graph creation output too.  We really don't have enough information to go on right now as your test cases seem to be from different systems or with settings that are different.

**Comment by TheWitness** [comment]
Also, when you have this issue, take the local data id off of the RRDfile name and do the following:

```sql
SELECT sequence, count(*) AS number
FROM graph_templates_item
WHERE local_graph_id = XXX
GROUP BY local_graph_id
ORDER BY sequence
```

**Comment by TheWitness** [comment]
Had to edit that a few times.

**Comment by tyit** [comment]
![image](https://user-images.githubusercontent.com/31933126/75132778-34336500-5713-11ea-9e5d-7600f5062f69.png)
![image](https://user-images.githubusercontent.com/31933126/75132793-46ad9e80-5713-11ea-9c7f-a8f6d8ae1aaf.png)

@netniV @TheWitness 

Sorry, I do n’t speak English well, I can only mark it with a graph. I debugged the graph today and found this GPRINT: cdefbe: MAX: 'Maximum \:% 8.2lf% s \ n' \ Random jump

**Comment by netniV** [comment]
Run the above query in MYSQL using the id from the graph

**Comment by netniV** [comment]
Wait, there’s no where statement on that query @thewitness

**Comment by TheWitness** [comment]
There is something wrong with that template.  You should goto Console > Template > Graph.  Then, select the Template in question, and from the dropdown choose 'Sync Graph Template', and then post again.  It looks like you have been importing various versions of the template as there are several lines.  But that does not really make sense.  So, before you do that, you should dump your database:

```cmd
mysqldump cacti > file.sql
```

And email it to developers at cacti dot net.  The sync should fix this, be we need to understand how it happened in the first place.  Was this a new install, do you remember what version you were at when you first installed?

**Comment by tyit** [comment]
I upgraded from Cacti 1.2.7 to Cacti 1.2.9 
I know nothing about the code
I do n’t know the email address of the developer, can you tell me?
thank you very much

**Comment by netniV** [comment]
developers@cacti.net

Don't worry, we don't expect you to know about the code, just to run some database queries if we need them.  Some people are able to help with code, so we may ask sometimes, but don't be afraid to say that you can't do it.

It does look like your sequence for the comment and the gprint will possibly have the same number, thus the order which they appear can be dependant on how mysql feels at the time.  If we have a dump of your database, this can help us diagnose it best.

**Comment by tyit** [comment]
Thank you very much
I have dumped cacti sql and sent it to mailbox

**Comment by TheWitness** [comment]
I just made a fix to lib/template.php and lib/import.php that fix the "sync template" issue.  It'll be part of the 1.2.11 release.  If your template layout is wrong, then it won't really fix anything when you sync templates.  So, that's critical.  You may have to re-import a good version of the template from another system and use the 'Remove Oprhans' option to fix the template due to some 'GPRINT' containment logic that breaks here in the Graph Template editing through.  That is only if you find that you have that problem.
