### ISSUE TITLE
 Void space

### ISSUE THREAD

**Issue by tyit** [Cacti/cacti#3265]
![image](https://user-images.githubusercontent.com/31933126/74609349-48300300-5124-11ea-91b8-921a94498f01.png)

Cacti 1.2.9  Void space

**Comment by cigamit** [comment]
What version of RRD Tool? The spacing is completely handled by it, we don't have any control over it.

**Comment by tyit** [comment]
RRDtool 1.4.8
nginx version: nginx/1.16.0
PHP 5.4.16 (cli) 
PHP 5.4.16 (fpm-fcgi)
mysql 5.6

**Comment by tyit** [comment]
Replaced with rrdtool 1.6.0, the problem is solved,Thank you very much
