### ISSUE TITLE
cacti 1.3.0-dev

### ISSUE THREAD

**Issue by majed17** [Cacti/cacti#3267]
**Describe the bug**
 size automatically changes from 70% to 100% 

**To Reproduce**
1) change a real time graph to size 70%
2) restart
3) it starts as 70% but then i noticed that one changes to 100% 
    and so all change to 100%

**Expected behavior**
in 1.2.8 restart keeps the before restart settings

**Desktop (please complete the following information):**
Gentoo
firefox (haven't tested on others)
73 64 bit

**Additional context**
i browsed to configuration, visual, and scrolled down expecting to see a setting ... and it is absent in all tried cacti versions

**Comment by netniV** [comment]
I've just merged 1.2.9 into develop, that's probably our last big merge as we look to try and make a start on the development stuff in 1.3.  See if those changes have made a difference.
