### ISSUE TITLE
Graphic input Chinese search error

### ISSUE THREAD

**Issue by tyit** [Cacti/cacti#3269]
![image](https://user-images.githubusercontent.com/31933126/74710754-59c8f600-525d-11ea-8680-8b30b40b319f.png)

Hi 
Graphic input Chinese search error

**Comment by netniV** [comment]
Do you see any errors in your cacti or apache logs when that occurs?

**Comment by tyit** [comment]
![image](https://user-images.githubusercontent.com/31933126/75089454-e6442300-5593-11ea-86fa-29b6563fb930.png)

![image](https://user-images.githubusercontent.com/31933126/75089462-fe1ba700-5593-11ea-8044-88c891cedcd1.png)

When I type Chinese test return string
cacti  or nginx  no  logs  errors

**Comment by TheWitness** [comment]
Please update lib/html_utility.php, then try again.  Let us know the error message you receive.

**Comment by TheWitness** [comment]
This should be fixed now.

**Comment by tyit** [comment]
![image](https://user-images.githubusercontent.com/31933126/75097103-a99f1880-55e1-11ea-9dcf-90fd7763ba5a.png)

![image](https://user-images.githubusercontent.com/31933126/75097134-3b0e8a80-55e2-11ea-92d8-f88bf1f243a3.png)

![image](https://user-images.githubusercontent.com/31933126/75097115-e66b0f80-55e1-11ea-828c-bfd19b02f947.png)

![image](https://user-images.githubusercontent.com/31933126/75097141-511c4b00-55e2-11ea-972d-10c334594576.png)

Hi  Updated the file lib/html_utility.php ,Problem still exists
