### ISSUE TITLE
Maximum execution time in vendor lib

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#3270]
**Describe the bug**
`[Wed Feb 19 10:39:28.736441 2020] [:error] [pid 17836] [client 172.20.2.42:55510] PHP Fatal error:  Maximum execution time of 60 seconds exceeded in /var/www/html/cacti/include/vendor/gettext/src/Extractors/Mo.php on line 98`

**To Reproduce**
1. Just run https://cacti.

**Expected behavior**
Maybe we should use composer to get the latest libs from vendors?

**Desktop (please complete the following information):**
 - OS: Debian Buster latest update

**Comment by netniV** [comment]
What version of cacti are you using? We ditched phpgettext in favour of motranslator a few versions back.

**Comment by interduo** [comment]
The problem exists in php7.0 after update to php7.3 the problem disappeared.

**Comment by interduo** [comment]
Sorry for no information about version. We use Cacti, updated few minutes ago ... branch 1.2.x.

**Comment by netniV** [comment]
I do apologise, we added MoTranslator as an option, it was Oscarotero we defaulted to, though we do include phpgettext for backward compatibility too. Try setting l10n_language_handler in either config.php or the settings table to the number of one of the following:

```php
define('CACTI_LANGUAGE_HANDLER_NONE', 0);
define('CACTI_LANGUAGE_HANDLER_PHPGETTEXT', 1);
define('CACTI_LANGUAGE_HANDLER_OSCAROTERO', 2);
define('CACTI_LANGUAGE_HANDLER_MOTRANSLATOR', 3);
```

At the moment, your value is effectively zero, which means that it will run through the following code, most likely picking OSCAROTERO:

```php
if (empty($l10n_handler)) {
        l10n_debug('Handler: not specified in config, autodetection is now in progress');
        if (file_exists($config['include_path'] . '/vendor/gettext/src/Translator.php')) {
                $l10n_handler = CACTI_LANGUAGE_HANDLER_OSCAROTERO;
        } elseif (file_exists($config['include_path'] . '/vendor/phpgettext/streams.php')) {
                $l10n_handler = CACTI_LANGUAGE_HANDLER_PHPGETTEXT;
        } elseif (file_exists($config['include_path'] . '/vendor/motanslator/src/Translator.php')) {
                $l10n_handler = CACTI_LANGUAGE_HANDLER_MOTRANSLATOR;
        }
}
```

**Comment by interduo** [comment]
I don't know if the issue still exists after updating to php7.3. I cannot reproduce it now.
If You think that there is a that possibility then please make a commit to 1.2.x branch with that code.

**Comment by netniV** [comment]
No this is the code that exists not a proposed change. I was suggesting you force it to a different translator. It is how package maintainers can do it.

**Comment by interduo** [comment]
Thanks for explanations. So the installer need to be changed and should update my config? Right?

**Comment by netniV** [comment]
No installer change just update your config if you want to force a different translation module.

**Comment by interduo** [comment]
On php7.3 both translation engines works as expected.

@netniV You didn't answer my proposition about using composer in Cacti.

Do You know adventages of using composer?

**Comment by netniV** [comment]
Composer is merely to bring in library dependencies as far as I am aware. Not sure how that would resolve the above but if you have a suggest then let me know.

**Comment by interduo** [comment]
It's very easy to juggle with dependencies libraries versions with composer and diagnose problems with dependencies. There is no use to duplicate code of other repositories where we could just use composer.

I strongly recommend to use composer or other dependecies manager in Cacti.
For example now we need to update PHPMailer 6.0.x in Cacti (the newest one is 6.1.4). In 6.0.x there are few problems with SMTP connecting in big workloaded envirnoment. If have composer - the only thing we need to do is `composer update` but now - we need to manually download and replace libs.

**Comment by cigamit** [comment]
Since this is php7.0, which we know was pretty buggy, I'd say we just close this one out.

**Comment by interduo** [comment]
ok - nice.
