### ISSUE TITLE
1.2.9 SQL errors when re-adding a deleted device 

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3273]
Hey everyone 

I think something is very broken with Autom8 on 1.2.9 

Case 

I am testing 1.2.9 to deploy in prod 

I have 400 Devices added via AUTOM8  the first run worked just fine 
I deleted the devices and did a re-discover to test that the bug from 1.2.7 where devices would stick around after being deleted is fixed ( I will edit with the github number)

When you do a re-scan to re-add the devices this error comes up 

2020/02/20 16:15:07 - CMDPHP SQL Backtrace: (/poller_automation.php[354]:discoverDevices(), /poller_automation.php[666]:automation_add_device(), /lib/api_automation.php[2871]:api_device_save(), /lib/api_device.php[727]:sql_save(), /lib/database.php[1415]:_db_replace(), /lib/database.php[1345]:db_execute(), /lib/database.php[210]:db_execute_prepared()) 

Along with the SQL insert command 
DBCALL ERROR: SQL Save Failed for Table 'host'. SQL:'INSERT INTO host  
2020/02/20 16:15:07 - CMDPHP ERROR: A DB Exec Failed!, Error: Column 'monitor' cannot be null 

Then the PHP script server goes nuts and crashes

2020/02/20 16:20:03 - SPINE: Poller[Main Poller] PID[26357] ERROR: SS[0] PHP Script Server communications lost. Restarting PHP Script Server
2020/02/20 16:20:03 - SPINE: Poller[Main Poller] PID[26342] ERROR: SS[0] PHP Script Server communications lost. Restarting PHP Script Server
2020/02/20 16:20:03 - SPINE: Poller[Main Poller] PID[26357] ERROR: SS[0] PHP Script Server communications lost. Restarting PHP Script Server
2020/02/20 16:20:03 - SPINE: Poller[Main Poller] PID[26357] ERROR: SS[0] PHP Script Server communications lost. Restarting PHP Script Server
2020/02/20 16:20:03 - SPINE: Poller[Main Poller] PID[26342] ERROR: SS[0] PHP Script Server communications lost. Restarting PHP Script Server
2020/02/20 16:20:03 - SPINE: Poller[Main Poller] PID[26328] ERROR: SS[0] PHP Script Server communications lost. Restarting PHP Script Server
2020/02/20 16:20:03 - SPINE: Poller[Main Poller] PID[26311] ERROR: SS[0] PHP Script Server communications lost. Restarting PHP Script Server
2020/02/20 16:20:03 - SPINE: Poller[Main Poller] PID[26357] ERROR: SS[0] PHP Script Server communications lost. Restarting PHP Script Server 

Followed by cacti log showing that the DB has gone away but thats not true you can still access it via the mysql shell and no issues show up  

ironically some devices did re-add without issues ???

Spine then takes a dump and starts exiting  

Here are the system details 

PHP 7.2.27 (cli) (built: Jan 22 2020 09:31:55) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.3.9, Copyright (c) 2002-2019, by ionCube Ltd.

Date 	Thu, 20 Feb 2020 16:23:50 -0500
Cacti Version 	1.2.9
Cacti OS 	unix
RSA Fingerprint 	
NET-SNMP Version 	NET-SNMP version: 5.7.2
RRDtool Version Configured 	1.4.0+
RRDtool Version Found 	1.4.8
Devices 	24
Graphs 	168
Data Sources 	SNMP Get: 2
SNMP Query: 146
Script Server: 4
Total: 152

**Comment by bmfmancini** [comment]
OK so here is some more digging 

Is seems the connections are not being closed  instead they are just taking up more and more connections ?


| 7628 | cacti | localhost           | cacti | Sleep   |  478 |       | NULL             |    0.000 |
| 7667 | cacti | localhost           | cacti | Sleep   |  478 |       | NULL             |    0.000 |
| 7681 | cacti | localhost           | cacti | Sleep   |  478 |       | NULL             |    0.000 |
| 7703 | cacti | localhost           | cacti | Sleep   |  478 |       | NULL             |    0.000 |
| 7718 | cacti | localhost           | cacti | Sleep   |  478 |       | NULL             |    0.000 |
| 7732 | cacti | localhost           | cacti | Sleep   |  478 |       | NULL             |    0.000 |
| 7735 | cacti | localhost           | cacti | Sleep   |   95 |       | NULL             |    0.000 |
| 7736 | cacti | localhost           | cacti | Sleep   |    8 |       | NULL             |    0.000 |
| 7737 | cacti | localhost           | cacti | Sleep   |  249 |       | NULL             |    0.000 |
| 7922 | cacti | localhost           | cacti | Sleep   |  418 |       | NULL             |    0.000 |
| 7961 | cacti | localhost           | cacti | Sleep   |  417 |       | NULL             |    0.000 |
| 7962 | cacti | localhost           | cacti | Sleep   |  417 |       | NULL             |    0.000 |
| 7963 | cacti | localhost           | cacti | Sleep   |  417 |       | NULL             |    0.000 |
| 7964 | cacti | localhost           | cacti | Sleep   |  417 |       | NULL             |    0.000 |
| 7965 | cacti | localhost           | cacti | Sleep   |  232 |       | NULL             |    0.000 |
| 7966 | cacti | localhost           | cacti | Sleep   |  223 |       | NULL             |    0.000 |
| 8480 | cacti | localhost           | cacti | Sleep   |   39 |       | NULL             |    0.000 |
| 9380 | cacti | localhost           | cacti | Sleep   |   68 |       | NULL             |    0.000 |
| 9381 | cacti | localhost           | cacti | Sleep   |   61 |       | NULL             |    0.000 |

| 9399 | cacti | localhost           | cacti | Sleep   |    4 |       | NULL             |    0.000 |
| 9555 | root  | localhost           | NULL  | Query   |    3 | init  | SHOW PROCESSLIST |    0.000 |
+------+-------+--------------

MariaDB [(none)]> show status like '%onn%';
+-----------------------------------------------+-------+
| Variable_name                                 | Value |
+-----------------------------------------------+-------+
| Aborted_connects                              | 2446  |
| Connection_errors_accept                      | 0     |
| Connection_errors_internal                    | 0     |
| Connection_errors_max_connections             | 297   |
| Connection_errors_peer_address                | 0     |
| Connection_errors_select                      | 0     |
| Connection_errors_tcpwrap                     | 0     |
| Connections                                   | 9809  |
| Max_used_connections                          | 801   |
| Performance_schema_session_connect_attrs_lost | 0     |
| Slave_connections                             | 0     |
| Slaves_connected                              | 0     |
| Ssl_client_connects                           | 0     |
| Ssl_connect_renegotiates                      | 0     |
| Ssl_finished_connects                         | 0     |
| Threads_connected                             | 800   |
| wsrep_connected                               | OFF

**Comment by bmfmancini** [comment]
OK stoped maria restarted to clear the connections 
Ran AUTOM8 to scan 3 networks on 2 pollers Main and remote 

Network 1 is a /24 20 Threads Main Poller
Network 2 is a /24 20 threads Main Poller
Nework 3 is a /24 50 threads remote poller

MariaDB [(none)]> show status like '%onn%';
+-----------------------------------------------+-------+
| Variable_name                                 | Value |
+-----------------------------------------------+-------+
| Aborted_connects                              | 1     |
| Connection_errors_accept                      | 0     |
| Connection_errors_internal                    | 0     |
| Connection_errors_max_connections             | 0     |
| Connection_errors_peer_address                | 0     |
| Connection_errors_select                      | 0     |
| Connection_errors_tcpwrap                     | 0     |
| Connections                                   | 2068  |
| Max_used_connections                          | 322   |
| Performance_schema_session_connect_attrs_lost | 0     |
| Slave_connections                             | 0     |
| Slaves_connected                              | 0     |
| Ssl_client_connects                           | 0     |
| Ssl_connect_renegotiates                      | 0     |
| Ssl_finished_connects                         | 0     |
| Threads_connected                             | 250   |
| wsrep_connected                               | OFF   |
+-----------------------------------------------+-------+

Again proccessess seem to just stay asleep 

| 2802 | cacti | 127.0.0.1:44742     | cacti | Sleep   |   51 |       | NULL             |    0.000 |
| 2805 | cacti | 127.0.0.1:44748     | cacti | Sleep   |   51 |       | NULL             |    0.000 |
| 2808 | cacti | 127.0.0.1:44754     | cacti | Sleep   |   51 |       | NULL             |    0.000 |
| 2821 | cacti | localhost           | cacti | Sleep   |   51 |       | NULL             |    0.000 |
| 2824 | cacti | 127.0.0.1:44782     | cacti | Sleep   |   51 |       | NULL             |    0.000 |
| 2825 | cacti | localhost           | cacti | Sleep   |   51 |       | NULL             |    0.000 |
| 2828 | cacti | 127.0.0.1:44788     | cacti | Sleep   |   50 |       | NULL             |    0.000 |
| 2832 | cacti | 127.0.0.1:44796     | cacti | Sleep   |   51 |       | NULL             |    0.000 |
| 2848 | cacti | localhost           | cacti | Sleep   |   51 |       | NULL             |    0.000 |
| 2853 | cacti | 127.0.0.1:44834     | cacti | Sleep   |   50 |       | NULL             |    0.000 |
| 2854 | cacti | localhost           | cacti | Sleep   |   51 |       | NULL             |    0.000 |
| 2875 | cacti | localhost           | cacti | Sleep   |   51 |       | NULL             |    0.000 |
| 2879 | cacti | 127.0.0.1:44882     | cacti | Sleep   |   50 |       | NULL             |    0.000 |
| 2904 | cacti | localhost           | cacti | Sleep   |   51 |       | NULL             |    0.000 |
| 3374 | root  | localhost           | NULL  | Query   |    0 | init  | SHOW PROCESSLIST |    0.000 |
+------+-------+---------------------+-------+---------+------+-------+------------------+----------+
316 rows in set (0.00 sec)

**Comment by bmfmancini** [comment]
Ok 

I Ran the exact same test but this time I switch to CMD.php as the poller instead of spine 

MariaDB [(none)]> show status like '%onn%';
+-----------------------------------------------+-------+
| Variable_name                                 | Value |
+-----------------------------------------------+-------+
| Aborted_connects                              | 0     |
| Connection_errors_accept                      | 0     |
| Connection_errors_internal                    | 0     |
| Connection_errors_max_connections             | 0     |
| Connection_errors_peer_address                | 0     |
| Connection_errors_select                      | 0     |
| Connection_errors_tcpwrap                     | 0     |
| Connections                                   | 1065  |
| Max_used_connections                          | 154   |
| Performance_schema_session_connect_attrs_lost | 0     |
| Slave_connections                             | 0     |
| Slaves_connected                              | 0     |
| Ssl_client_connects                           | 0     |
| Ssl_connect_renegotiates                      | 0     |
| Ssl_finished_connects                         | 0     |
| Threads_connected                             | 58    |
| wsrep_connected                               | OFF   |
+-----------------------------------------------+-------+


The sleeping processes went down to 56 and dropping quickly 
No SQL related errors while importing 400 devices 

I think this may be something spine related ??

**Comment by bmfmancini** [comment]
Ok so I restored from a DB backup and deleted and re-added devices no issues 
It seems like whatever happened corrupted the DB so weird 

Any ideas?  trying to figure out what may have happened in case this is a stability issue that's going to arise in prod on a heavier system

**Comment by netniV** [comment]
The monitor table comes from a plugin.  If you have created a test system using the database from a live one, but do not include all the plugins, the parameters can end up missing as they aren't being populated by the system hooks that would normally do it.

**Comment by netniV** [comment]
I've reviewed this again this morning and i believe that you've corrupted the setup rather than it being a bug with existing code so I'm going to go and close this one.  If that changes we can reopen it.

**Comment by bmfmancini** [comment]
Hey Guys 

I think there is something real going on here 

Complete new setup now nothing from previous build 
I noticed that this happens all over again if there is 0 devices and you re-add them then the Monitor table cannot be null error shows up 

02/24/2020 13:57:15 - CMDPHP SQL Backtrace: (/poller_automation.php[354]:discoverDevices(), /poller_automation.php[666]:automation_add_device(), /lib/api_automation.php[2871]:api_device_save(), /lib/api_device.php[727]:sql_save(), /lib/database.php[1415]:_db_replace(), /lib/database.php[1345]:db_execute(), /lib/database.php[210]:db_execute_prepared())
02/24/2020 13:57:15 - CMDPHP ERROR: A DB Exec Failed!, Error: Column 'monitor' cannot be null 

Steps to reproduce

1.) Deleted all of your devices 
2.) try manually create a device 

02/24/2020 13:57:15 - CMDPHP SQL Backtrace: (/poller_automation.php[354]:discoverDevices(), /poller_automation.php[666]:automation_add_device(), /lib/api_automation.php[2871]:api_device_save(), /lib/api_device.php[727]:sql_save(), /lib/database.php[1415]:_db_replace(), /lib/database.php[1345]:db_execute(), /lib/database.php[210]:db_execute_prepared())
02/24/2020 13:57:15 - CMDPHP ERROR: A DB Exec Failed!, Error: Column 'monitor' cannot be null 


My next test will be the same procedure but without the Monitor plugin installed

**Comment by bmfmancini** [comment]
Ok so I re-tested 

This time I uninstalled the monitor plugin no issues came up 
It seems this issue is with  the monitor plugin and not cacti core

I will open an issue on the Monitor plugin page
