### ISSUE TITLE
When editing a tree, multiple device drag/drop does not work

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#3274]
**Describe the bug**
When you are editing a tree, selecting multiple available devices and dragging them to a tree node only adds one of the devices randomly.  This affects 1.2.9

**Expected behavior**
All devices added should be represented in the tree.

**Comment by netniV** [comment]
Trying to replicate this with a test system and I have been unable to so far.

**Comment by TheWitness** [comment]
This seems to be related to a change in jsTree bahavior.  I'm fixing it now.
