### ISSUE TITLE
When spine aborts, script server can be left wanting or generating unnecessary logs

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#3276]
**Describe the bug**
Depending on the version of Cacti you are running, if spine has an issue, such as too many open database connections, script server can suddenly lose it's parent and thus has no ability to receive input.

As such, this can cause lots of log entries for "Input Expected", though with later versions script server will also stop.

**To Reproduce**
Run spine using `spine &` repeatedly at the command line and watch the database connections fail, and then script server fail.

**Expected behavior**
Script server should silently close when the parent process has also been closed.

**Comment by bmfmancini** [comment]
hey Mark could the issue I reported be related to this 

My issue https://github.com/Cacti/cacti/issues/3273

**Comment by netniV** [comment]
No, that is a different issue.  Mine was caused by flooding mysql so there were no further connections available.  That in turn causes spine threads to die and means that script server has no parent process to respond to.
