### ISSUE TITLE
When boost does not find an initial time, numeric errors can be raised

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3277]
cacti 1.2.9 

Seeing errors coming from Boost which I found is causing Boost to miss RRD updates 

2020/02/21 11:00:09 - BOOST WARNING: RRD Update Warning '' for Local Data ID '4993'
2020/02/21 11:00:09 - CMDPHP PHP ERROR WARNING Backtrace: (/poller_boost.php[137]:output_rrd_data(), /poller_boost.php[312]:boost_process_local_data_ids(), /poller_boost.php[608]:boost_process_output(), /poller_boost.php[641]:boost_rrdtool_function_update(), /lib/boost.php[1194]:boost_rrdtool_function_create(), /lib/boost.php[1070]:CactiErrorHandler())
2020/02/21 11:00:09 - ERROR PHP WARNING: A non-numeric value encountered in file: /var/www/html/cacti/lib/boost.php on line: 1070
2020/02/21 11:00:09 - BOOST WARNING: RRD Update Warning '' for Local Data ID '4992'
2020/02/21 11:00:09 - CMDPHP PHP ERROR WARNING Backtrace: (/poller_boost.php[137]:output_rrd_data(), /poller_boost.php[312]:boost_process_local_data_ids(), /poller_boost.php[452]:boost_process_output(), /poller_boost.php[641]:boost_rrdtool_function_update(), /lib/boost.php[1194]:boost_rrdtool_function_create(), /lib/boost.php[1070]:CactiErrorHandler())
2020/02/21 11:00:09 - ERROR PHP WARNING: A non-numeric value encountered in file: /var/www/html/cacti/lib/boost.php on line: 1070

**Comment by bmfmancini** [comment]
here is line 1070

 /* back off the initial time to allow updates */
        $initial_time -= 300;

**Comment by netniV** [comment]
That is the correct line.  The reason is that initial time is actually initialised to  '' rather than 0.
