### ISSUE TITLE
cacti 1.2.9 NULL  Host entries via AUTOM8

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3278]
Hello Everyone 

Continuing to test 1.2.9 and found that after deleting devices completely and readding the autom8 process works fine aside from one time where everything went bonkers 

below you see devices that are Null across the board except for poll time and uptime 

![image](https://user-images.githubusercontent.com/13388748/75059492-11067c80-54ab-11ea-824d-0452d7e60e73.png)

Here is the output from the dbside

MariaDB [cacti]> select id,description,hostname  from host where id = "809";
+-----+-------------+----------+
| id  | description | hostname |
+-----+-------------+----------+
| 809 |             | NULL     |
+-----+-------------+----------+

selecting them and deleting via gui  cleared them

**Comment by cigamit** [comment]
Do you have more than one Data Collector?  Are these devices associated with the remote, or the local?  I was unable to reproduce using the main data collector.  Just need some more details.

**Comment by bmfmancini** [comment]
Hey @cigamit  

These devices were on a remote poller in my lab I only have the one remote poller

**Comment by bmfmancini** [comment]
OK it happend again 

This time these are the steps I did 

1.) Deleted all Devices 
2.) confirmed in both the gui and DB there were no devices 
3.) ran autom8 on remote poller

5 devices came in with no description or hostname but reported as UP with the other stats 
DB again displayed Null for the description 

Deleted the blank devices re-ran got 5 new devices  this time with the descriptions and the hostname

**Comment by netniV** [comment]
So, to be clear, the steps to reproduce are:

1. Install a new main poller
2. Install a new remote poller
3. Run automate using the remote poller
4. Monitor the database

**Comment by cigamit** [comment]
This was fixed pretty sure in the 1.2.10 release.

**Comment by TheWitness** [comment]
@bmfmancini, can you try to reproduce this with the latest 1.2.x branch?  If not, can you close.  Thanks

**Comment by bmfmancini** [comment]
So far I havent seen it again although the only time I did see it was mass importing devices which I have not had the oppourtunity to do 

Lets close for now and if it comes up again ill let you know !
