### ISSUE TITLE
Enhance Cacti to report possible number of connections may exceed configured

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#3279]
**Describe the bug**
Within MySQL you have to configure the maximum number of connections allowed.  There is a default value that is used if you do not (may be dependant on the MySQL version).  However, if you have a busy system with lots of users, plus lots of polling, you may find that on occasions you are busting the limits of connections without realising it.

This can occur even more when there are many threads querying devices that are not responding near the ned of a polling cycle or if a user happens to just hit refresh a lot.

**Expected behavior**
Cacti should be able to automatically calculate a rough estimate of how many connections are used and whether it is exceeding the configured value.  This can be reported when the admin saves a poller configuration or views the MySQL recommendations section within utilities or during the upgrade processes.

For new installs, those figures would not be available to Cacti so would need to assumed ok.

**Comment by cigamit** [comment]
Good idea.  This ones been generating forum posts for years.  As a rule of thumb, I use the following:

target number of Concurrent Users * 6 connections (most browsers allow 6 graphs to be rendered in parallel per tab)
plus
number of data collectors * concurrent processes * (number of threads + script servers + 1)

The number of concurrent users should be either detected, which involves counting settions that are active (either from the database or /var/lib/php/session direcotry), or setting a setting in Cacti as the 'baseline'.

**Comment by netniV** [comment]
Currently the cacti user stats does that as part of its process. So we could reuse the rrd data should it be available.

**Comment by TheWitness** [comment]
This was added to the Technical Support page a few releases ago.  So, I'm going to mark this closed/resolved.
