### ISSUE TITLE
Cacti Stats - User Logins - Incorrect count of invalid users

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#3287]
**Describe the bug**
The graph constantly reports all invalid logins before the polling time.  In my case, the invalid login occurred a year ago, not within the polling interval.

**To Reproduce**
1. Attempt to login incorrectly
2. Wait an hour or two
3. Visit the Cacti Stats - User Login graph
4. See invalid logins stays at the same level

**Expected behavior**
The invalid login attempts should be graphed as per the valid ones.

**Comment by netniV** [comment]
I patched my version by changing the invalid query to match the valid one:
```php
$user_logins_invalid = db_fetch_cell("SELECT COUNT(*) AS user_logins
        FROM user_log
        WHERE UNIX_TIMESTAMP(`time`) BETWEEN UNIX_TIMESTAMP() - $active_interval AND UNIX_TIMSTAMP()
        AND user_id = 0
        AND `result` IN (0, 3)");
```

Need to find out how we package those so we can get this fix pushed with the next update.

**Comment by netniV** [comment]
This can be manually tested by running the following query:
```sql
insert into user_log values ('admin',1,'2019-01-01 01:01:01',0,'1.2.3.4');
```

**Comment by netniV** [comment]
This can be manually tested by running cacti_user_stats.php before and after running the following query:
```sql
insert into user_log values ('admin',1,'2019-01-01 01:01:01',0,'1.2.3.4');
```

Before:
```console
$ sudo -u www-data php -q cacti_user_stats.php
valid:0 invalid:1 active:U sleeping:U garbage:U uactive:U usleeping:U
```

After:
```console
mysql> insert into user_log values ('admin',1,'2019-01-01 01:01:01',0,'1.2.3.4');
Query OK, 1 row affected (0.00 sec)

mysql> quit
$ sudo -u www-data php -q cacti_user_stats.php
valid:0 invalid:2 active:U sleeping:U garbage:U uactive:U usleeping:U
```

That last invalid:2 should be :0 as both failed login records are for a year ago.

**Comment by cigamit** [comment]
Going to patch this, in github, but we need to also repackage the stats package too.

**Comment by cigamit** [comment]
Step 1 of 2 done.

**Comment by cigamit** [comment]
Package updated.
