### ISSUE TITLE
Customize the favicon

### ISSUE THREAD

**Issue by earendilfr** [Cacti/cacti#329]
Currently, we can not tune easily the favicon for CACTI site.
Could we change the directory of the favicon to use the theme directory?

You can found a patch to allow it in attachment.
[0001-Add-hability-to-customize-the-favicon-for-the-site.txt](https://github.com/Cacti/cacti/files/789933/0001-Add-hability-to-customize-the-favicon-for-the-site.txt)

**Comment by cigamit** [comment]
Resolved.  Please test and if all is well, please close.  Thanks!

**Comment by earendilfr** [comment]
Just one remark : perhaps you should remove the `type='image/gif'` in the second icon line.
Because i'm not sure that everybody use gif format for their favicon

**Comment by pautiina** [comment]
If a file with the extension ICO Type must be: `type='image/x-icon'`
In this case, should be: `type='image/x-icon'`

Comment from [https://en.wikipedia.org/wiki/Favicon](url):

![18](https://cloud.githubusercontent.com/assets/11805503/23265965/15968e8a-f9ef-11e6-862f-ddd5a24beced.png)

**Comment by cigamit** [comment]
All set now.
