### ISSUE TITLE
Minor: table refresh by re-order when resize table column 

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#3295]
**Describe the bug**
Table refresh by re-order when resize table column and mouse-up in left-column header

**To Reproduce**
1. Go to Console->Devices(Any list page)
2. Move mouse between two columns, until cursor become `e-resize`
3. Press and drag mouse from right to left until mouse on top of left column header cell.
4. Release mouse
5. See page refresh(ajax mode), and new page order by previous left column. 

Note: If release mouse out of left column header cell, page will be not refresh-ed

**Expected behavior**
Current behavior is similar to clicking on the left column。
Expected behavior should be keep non-refresh no matter where release mouse

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser FireFox 68.5.0 esr, Chrome 80.0.3987.116

**Comment by cigamit** [comment]
I was trying to resolve this one, and it's not easy.  I would like to see if you can do a pull request @ddb4github.
