### ISSUE TITLE
Upgrade from 1.2.5 to 1.2.9 not completing / memory exhaustion

### ISSUE THREAD

**Issue by blowrancebenton** [Cacti/cacti#3296]
**Describe the bug**
- I completed the upgrade instructions posted here (for 1.2.5 to 1.2.9): https://www.cacti.net/downloads/docs/html/upgrade.html
  - All of the upgrade checks verified ok.
  - When I proceeded to allow the web interface to complete the upgrade it shows a progress bar indicating "Your Cacti Server is now installing" but it never completes it remains at 0% with "--- NO LOG FOUND ---" below it.
- I checked  /path/to/cacti/log/install-general.log and it shows it spawned background process /usr/bin/php '/usr/share/cacti/install/background.php'
  - If I launch this process from the console of the Cacti Server it produces the following error:
_**PHP Fatal error:  Allowed memory size of 2097152 bytes exhausted (tried to allocate 20480 bytes) in /usr/share/cacti/lib/functions.php on line 3127**_

**To Reproduce**
I'm not exactly certain the variables required to reproduce, I simply upgraded Cacti from 1.2.5 to 1.2.9 (replaced the Cacti Files, logged in and confirmed the requirements were met then instructed it to begin the upgrade).  The OS is Ubuntu 18.04.1.

**Expected behavior**
The upgrade process should have completed or listed errors. It only shows the progress bar at 0% and underneath that it shows "--- NO LOG FOUND ---. There is a green progress bar progressing from right to left over yellow in the left most portion of the overall progress bar just beneth the words "Refresh in".
I tried rebooting the server and launching the upgrade again as well but experienced the same result.

**Desktop (please complete the following information):**
Server is Ubuntu 18.04.1.
Desktop where I logged in to launch the upgrade is Windows 10 1909. I tried in Internet Explorer 11.657.18362.0 and Firefox 72.0.2 (64bit).

**Comment by netniV** [comment]
when I saw this last night on my phone, I suspected that this may be an installer problem, but actually you have your CLI memory limit set to 2 MB?  That is way too small.  In fact, it shouldn't have got past the recommendations page with a memory limit that small so I will have to do a test on that.  

But we should probably add a check to the background installer to make sure about the memory limit before it attempts to do anything and flag it as a problem if so without attempting an update.

**Comment by blowrancebenton** [comment]
> you have your CLI memory limit set to 2 MB

My php cli memory limit is set to 5GB so I'm not sure why it would only be allowing 2MB to be used:
```
cat /etc/php/7.2/cli/php.ini | grep memory_limit
memory_limit = 5120MB
```

**Comment by blowrancebenton** [comment]
Your reply did help me find that I had the cli php.ini memory_limit set to 5120**MB** instead of 5120M so I suppose it defaulted to 2 MB instead.  I adjusted this in the cli/php.ini file, restarted apache2 and the installation proceeded as usual.

**Comment by netniV** [comment]
Good to know, I'll close this once I apply a patch to report and fail if the memory limit is below a certain value.  However, still confused how you got past the recommendations page so I'll have to test that too.

**Comment by TheWitness** [comment]
Fixed.
