### ISSUE TITLE
Cacti should warn users who use php-snmp and SNMPv3 to uninstall php-snmp

### ISSUE THREAD

**Issue by Uedogit** [Cacti/cacti#3299]
**Describe the bug**
If i use Cacti to monitor Brocade FC Switches with so called virtual fabrics i have to use this command

`snmpwalk -v 3 -u userX -l authnoPriv -a MD5 -A passwordX -n VF:100 ipxxx .1.... oid`

- on cli it works --> i get a value

I created a data sourcee with the right OID 
In the device section i use a new device where i insert for example VF:100

But the cacti poller show me U and no valid value.
With no context i get an integer value --> the correct value, but i need the context

there is an error message:

> ERROR PHP WARNING: SNMP::get(): Fatal error: Bad context specified in file: /var/www/html/cacti/lib/snmp.php on line 479

**And:**
In production i use version 1.1.28 --> it works since many updates. If i want to update, i have the same problem.

Could    :    be the problem?

**Desktop (please complete the following information):**
 - OS: RHEL
 - Browser chrome 
 - Cacti Version 1.2.9 plain install

**Comment by netniV** [comment]
Can you be clear. Are you using 1.1.28 or 1.2.8?

**Comment by Uedogit** [comment]
1.1.28 --> true

**Comment by netniV** [comment]
And that is the version you are having the problem with, or 1.2.9 is?

**Comment by Uedogit** [comment]
My problem is with the new Version 1.2.9!

> https://github.com/Cacti/cacti/blob/develop/lib/snmp.php

`function cacti_snmp_session_get($session, $oid, $strip_alpha = false)`

Because I couldn't make an update to a new Version!
Then i test a new installation (1.2.9) and i see the snmp problem!

**Comment by TheWitness** [comment]
Can you let us know if php-snmp is installed?

**Comment by Uedogit** [comment]
Yes! Version 5.4.16

**Comment by cigamit** [comment]
You have to remove php-snmp to use SNMPv3 in Cacti.  Can you remove the module and see if it works again.

**Comment by netniV** [comment]
Maybe we should throw up a warning or disable v3 if using php-snmp?

**Comment by TheWitness** [comment]
Makes sense to me.

**Comment by Uedogit** [comment]
I removed php-snmp and it works! Thanks! 👍 

I think a warning is necessary, cause of:

Cacti requires MySQL, PHP, RRDTool, **net-snmp**, and a webserver that supports PHP such as Apache or IIS.

**Comment by TheWitness** [comment]
Warning added.
