### ISSUE TITLE
Import templates to non default Data Profile 

### ISSUE THREAD

**Issue by gamineiro** [Cacti/cacti#330]
Even if you select another data profile, the import is done with id 1 (System Default)

**Comment by cigamit** [comment]
Hmm, that would be a legit bug.

**Comment by CapitalF** [comment]
Meetoo, reproduced here.

Sample workarounds to fix directly in the DB:

# Update only templates
update data_template_data set data_source_profile_id=2 where local_data_id=0;

# Update templates and real DSs
update data_template_data set data_source_profile_id=2;

Assumes the ID of the DS Profile you want to use is 2.

**Comment by cigamit** [comment]
This has been resolved now.  If you are running the development version, you will have to run database_upgrade.php, otherwise this issue will be resolved with Cacti 1.0.5.

**Comment by gamineiro** [comment]
Thanks. Best regards.
