### ISSUE TITLE
Allow Basic Auth Accounts to be Mapped by CSV File

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#3304]
**Is your feature request related to a problem? Please describe.**
When using basic authentication, cacti will currently look for an @ sign, and if it finds it, it will use the information before the @ sign as the login account.  But some customers do not use that account as the local account name.  Provide a setting, that if the customer provides a static CSV file, that Cacti will search that CSV file for the basic account to use for login.

**Describe the solution you'd like**
The CSV file would look like the following:
thewitness, ladams
ronytoman, troman
...

So, if the user thewitness@cacti.net logs in using Basic authentication, the account 'ladams' would be used for login.

**Comment by netniV** [comment]
Would it not be better to have external auth lonks as a table within Cacti so that we can properly link LDAP and Basic alike ?
