### ISSUE TITLE
No Local "admin" when ldap configured. 

### ISSUE THREAD

**Issue by fxrsliberty** [Cacti/cacti#3305]
**Describe the bug**
I Recently upgraded from 088h to 1.2.9 
The previous install had no LDAP configuration
After adding an LDAP configuration, I can log in with LDAP credentials but not the local admin. when I look at the local admin account, it is disabled. 
when I re-enable it , I can login with the local admin account but not with LDAP accounts. Yes, I am choosing the "local" button for the local admin and the LDAP for my credentials on the log in page. 
This appears to be similar to https://github.com/Cacti/cacti/issues/446
possibly the same issue but it isn't addressed in the "upgrade" routine. 
Thank you for a wonderful tool!

**Comment by netniV** [comment]
You need to use the User Domains rather than plain LDAP.  Using the User Domains you can also use local login as well as LDAP.  In 1.3, we will be retiring the basic LDAP and moving its configuration to the User Domains as a new entry if set.

**Comment by ddb4github** [comment]
@fxrsliberty did you configure local admin as 'User Template'? I found 'User Template' user will be disabled after save settings.
If configure other one.  'local admin' work well

**Comment by netniV** [comment]
Template user was disabled automatically as part of a bug fix a long time ago that I suggested.  This was because a template user could actively be used to sign in with, which is bad given most people would never change the password associated with that template.
