### ISSUE TITLE
Can't change Poller Type from cmd.php to spine

### ISSUE THREAD

**Issue by Jh0nHerrera** [Cacti/cacti#3307]
Hi team,
I recently installed cacti and when i try to change the poller type to spine i click in the save button but nothing happen. and i get the error message Unsaved Changes Detected when switch to other tab
OS: CentOS 7.7.1908
CACTI: 1.2.9
MARIADB: 10.4.12
PHP: 7.0.33
APACHE: 2.4.6-90

UPDATE 1 NOTE:
For you information i test with a old version (1.1.28,1.1.38) and i can change Poller Type and save it without any problem.

UPDATE 2 NOTE:
For you information i test with a old version (1.2.0,1.2.8,1.2.7,1.2.6,1.2.5) same problem as 1.2.9

**Comment by TheWitness** [comment]
For the 1.2.x version, you need to get the 1.2.x spine source and recompile.  The spine 1.1.x source is not compatible.  You can test spine this way:

```cmd
./spine -R -V 3 -S
```

If it's working, it'll dump quite a bit of data to stdout.  If it's not working, you will have a clue as to why.

**Comment by Jh0nHerrera** [comment]
I am sorry, it is false positive, i can't save as specified initially because i am setting poller interval to 5 minutes and the cron interval to 1 minute.
After change this values to the same of each other, now i can save the configuration without any problem, thanks team for you help.
Regards, Jhon from Colombia.
