### ISSUE TITLE
During installation Cacti 1.2.10 converting table is infinitive

### ISSUE THREAD

**Issue by martinlegionowo** [Cacti/cacti#3308]
Hello,

during installation Cacti 1.2.10 109 tables are have to be converted to UTF8
and after checked all the converting table looks like it works infinitive at 41%.
Sometimes it refreshes and changing the Progress Last Update.

**Expected behavior**
Converting and finishing the installation.

**Screenshots**

![cacti_1_2_10_converting_table_infinitive](https://user-images.githubusercontent.com/61698203/75685773-686ece80-5c9b-11ea-9eda-d0718b68c565.jpg)

**Desktop (please complete the following information):**
 - OS: CentOS 7.8 - 3.10.0-1062.12.1.el7.x86_64
 - Browser: Firefox 
 - Version: 73.0.1 64bit

Who can me help ?
Maybe someone has the same problem ?

Thanks and regards,
Marcin

**Comment by netniV** [comment]
You have it wrong, the installation is actually at the stage of importing a template, the conversion of tables completed (version is always the last since it's the last alphabetically).

Check your error logs and see if anything was recorded for it.

**Comment by martinlegionowo** [comment]
Ok, but it still the same - 41% percent - look the same problem in the issue no #3313. Probably the same problem, What we can do now ?
To be honest - which error logs you mentioned ? From which location ?
Regards,
Marcin

**Comment by martinlegionowo** [comment]
Ok, but it still the same - 41% percent - look the same problem in the
issue no #3313 <https://github.com/Cacti/cacti/issues/3313>. Probably the
same problem, What we can do now ?
To be honest - which error logs you mentioned ? From which location ?

Regards,
Marcin






wt., 3 mar 2020 o 01:51 Mark Brugnoli-Vinten <notifications@github.com>
napisał(a):

**Comment by ndilooc** [comment]
i follow instruction from this link https://www.itzgeek.com/how-tos/linux/ubuntu-how-tos/how-to-install-cacti-on-ubuntu-18-04-lts-bionic-beaver.html 
i tried to install in debian, but ended up the same, instalation stopped at 41% and keep looping

**Comment by martinlegionowo** [comment]
Hello,

exactly, it was 1.2.7 version, I think it is a bug connected with
installation, I am waiting for answer,
but if you will find the solution please let me know.

regards,
Marcin





wt., 3 mar 2020 o 14:48 ndilooc <notifications@github.com> napisał(a):

**Comment by Jh0nHerrera** [comment]
I team yes same here, stuck in 41% i think that it is a problem when try to export the defaul templates, when i issue the command sudo systemctl status httpd i see this:
![image](https://user-images.githubusercontent.com/61655570/75804104-7e3ccc00-5d4d-11ea-8e15-17cfba79315c.png)

**Comment by martinlegionowo** [comment]
> 
> 
> Hi team yes same here, stuck in 41% i think that it is a problem when try to install the default templates, when i issue the command sudo systemctl status httpd i see this:
> ![image](https://user-images.githubusercontent.com/61655570/75804104-7e3ccc00-5d4d-11ea-8e15-17cfba79315c.png)
> 
> UPDATE 1 NOTE:
> If you don't select any template to install the installation is succeed

But how the break it ?
Which the name of the process ?

**Comment by Jh0nHerrera** [comment]
UPDATE 2 NOTE:
If you uncheck Cisco Template, the installation is succeed

**Comment by Jh0nHerrera** [comment]
1- delete symbolic link and cacti directory
2- delete cacti db from mariadb or mysql
3- extract again cacti latest version and create symbolic link
4- create again cacti db from mariadb or mysql
5- import database structure to cacti db
6- modify config.php to reflect username and passwor for cacti db
7- start again the installation process from Web Browser.

**Comment by Jh0nHerrera** [comment]
UPDATE 3 NOTE:
I finally found the problem, this issue occurred if you check the latest option, please check the image with the red circle
![image](https://user-images.githubusercontent.com/61655570/75810024-bf39de00-5d57-11ea-92c4-fedcff6a0d84.png)

**Comment by ndilooc** [comment]
Thank you, appreciate your helps, it resolve the issue

**Comment by netniV** [comment]
This seems to be a duplicated in issue 3313

**Comment by martinlegionowo** [comment]
Thank you for your help !

**Comment by cigamit** [comment]
Okay, this is resolved now with the merge of @netniV's fetch branch back into 1.2.x branch.  It'll be a part of the 1.2.11 release.
