### ISSUE TITLE
Graph template title variables

### ISSUE THREAD

**Issue by jotate-git** [Cacti/cacti#3309]
Apologies if this topic has been covered...

If i recall correctly, setting a graph template title variables was pretty straight forward.  Just edit the graph template, and modify the "title".  this would allow for the insertion of variables, ect.

However, something has change in recent versions (i can pinpoint exactly, as i havent had to adda new device in some time).  for example, at least with Cacti 1.2.9, the graph template for "Interface - Traffic (bits/sec)", illustrates the default title as "|host_description| - Traffic".  Changing this to "|host_description| - Traffic - |query_ifName| - |query_ifAlias|" seems to have no affect on newly added interface graphs. 

All new interface graphs, have their title populated with "|host_description| - Traffic - |query_ifName|".  Since this differs from what is default in the graph template, i assume template titles are configured elsewhere?

any help on how/where to set graph template titles is appreciated.

Thanks!

**Comment by netniV** [comment]
I think it depends on what values are actually available at the time of graph creation.  Template titles are defined against the template with an order of priority.

**Comment by jotate-git** [comment]
> 
> 
> I think it depends on what values are actually available at the time of graph creation. Template titles are defined against the template with an order of priority.

understood.  I tested a bit with new graphs, and i verified the graph template "title" string.  The behavior i am seeing is, the graph title string for a newly created graph, does not reflect the graph title setting in the template.  it defaults to:

 "|host_description| - Traffic - |query_ifName|"   <--Interface graph as an example

..regardless of what the graph template is set to.

**Comment by netniV** [comment]
I'm currently looking into the suggested names functionality for a client and trying to wrap my head around the interface traffic one speciically because he doesn't get his ifName appearing.

**Comment by jotate-git** [comment]
> 
> 
> I'm currently looking into the suggested names functionality for a client and trying to wrap my head around the interface traffic one speciically because he doesn't get his ifName appearing.

cool beans.  I am going to try to figure out, where in the DB newly created interface graphs gets the "tile" string from.  Ill post any results.

Thanks again for your help!

**Comment by netniV** [comment]
Graph's that are templated, should come from Graph Template Data as far as I recall.  One of these days we will do a visual chart explaining the DB... probably when I'm old and gray.

**Comment by jotate-git** [comment]
> 
> 
> Graph's that are templated, should come from Graph Template Data as far as I recall. One of these days we will do a visual chart explaining the DB... probably when I'm old and gray.

i wonder if an existing device, that is using and existing template, like "Cisco Router", contains old interface template info, and any "new" interface graphs, pull stale graph template info?!?

**Comment by netniV** [comment]
I was wondering that myself.  I have a client whose data template information didn't look right, but I haven't had time to complete that investigation.

**Comment by cigamit** [comment]
So, with regard to Data Queries, the Suggested values work from sequence 1 to the last sequence and search for uniqueness and not necessarily the first match.  So, I guess we could re-visit this approach, but we need more information as to the problem.

**Comment by jotate-git** [comment]
> 
> 
> I was wondering that myself. I have a client whose data template information didn't look right, but I haven't had time to complete that investigation.

i searched around a bit in a Cacti DB dump.  I was searching for "|host_description| - Traffic - |query_ifName|", as this seems to be the default string applied to Traffic graph titles.

Under the table, "snmp_query_graph_rrd_sv", i found the string "|host_description| - Traffic - |query_ifName|", under a few different values.  I am just not sure what each 'id" refers to.  

Is it possible, this table is where some newly created graphs are getting their graph title string from?

**Comment by netniV** [comment]
snmp_query_graph_rrd_sv is where the data source suggest titles for a graph come from.  I noticed on a client's DB that some traffic interface graphs seem to be missing these SV's for some reason.  I haven't had a chance to investigate why yet.

**Comment by TheWitness** [comment]
Likely removed by accident.  There may be room to improve that, but let's open a specific feature for that.  For now, I'll close.
