### ISSUE TITLE
Cacti 1.0.3 new install - graph permissions for users not working as designed

### ISSUE THREAD

**Issue by camerabob** [Cacti/cacti#331]
I have set the permissions to restrictive. I still manually have to revoke access to the device, the graph and the template to restrict people from seeing the graphs. Also when I build a restrictive template and apply it to a vanilla user, nothing happens. When applied to a restricted user, all graphs open up again. I cannot successfully use the group memberships at all at this time.

I'm not sure if this is by design as well, but if the default action is changed from 'Allow' to 'Deny', all of the permissions reverse.

My environment:
Date
-Mon, 20 Feb 2017 12:29:28 -0500

Cacti Version
-1.0.3

Cacti OS
-unix

RSA Fingerprint
-c5:d8:9b:84:32:1f:e0:da:64:33:28:55:d6:ab:46:a3

NET-SNMP Version
-NET-SNMP version: 5.7.2

RRDtool Version
-RRDTool 1.4.x

Devices
-12

Graphs
-81

Data Sources
-Script/Command: 6
-SNMP Get: 71
-SNMP Query: 21
-Script Server: 2
-Total: 100

**Comment by cigamit** [comment]
You have to provide more information.  Screen shots would be helpful.

**Comment by cigamit** [comment]
In the modern Cacti, you should consider using user groups, and placing the permissions there.  Once you get used to this security system, it should not be too difficult.  The Cacti 0.8.x permission system was horribly broken.  If you got it to work, you were lucky.  As a part of the redesign, that old permission system was validated with all combinations and it was a total fail.  This one is consistent and works as advertised, though it will take some getting used to.

**Comment by camerabob** [comment]
I didn't have a chance to update before you closed it. Still not working. I will get my documentation together over the weekend and open another post. 

Excuse any misspellings. I'm still getting used to this iGadget!

**Comment by cigamit** [comment]
Works for me.
