### ISSUE TITLE
Minor：Console menu does not auto-expand for graph item editor page

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#3312]
**Describe the bug**
Console menu does not auto-expand and selected for graph item editor page

**To Reproduce**
1. Access Console-->Templates-->Graph
2. Click any one graph template name
3. Click any one graph template item
4. Reload page by Browser(F5)
4. All Console menus are collapsed

**Expected behavior**
Expand "Templates" and mark "Graph" as selected

**Screenshots**
![image](https://user-images.githubusercontent.com/17589018/75742920-23ee3c00-5d4a-11ea-9641-595aff8e562d.png)

**Comment by cigamit** [comment]
This one is a very legacy pain in the arse.  The Cacti permission system is file based, and this one has no navigation.  Let me see what we can do.

**Comment by cigamit** [comment]
Resolved now.
