### ISSUE TITLE
Script Server has invalid debug code left in

### ISSUE THREAD

**Issue by rprofijt** [Cacti/cacti#3314]
**Describe the bug**
In Cacti 1.2.10 we get this in the cacti.log:

2020/03/03 14:01:15 - CMDPHP PHP ERROR WARNING Backtrace:  (/script_server.php[183]:unlink(), CactiErrorHandler())
2020/03/03 14:01:15 - ERROR PHP WARNING:  unlink(/usr/share/cacti/site/log/script_server_7224.out): No such file  or directory in file: /opt/cacti/cacti-prod/script_server.php  on line:  183

The script_server.php has a hardcoded path to /usr/share/cacti, we have Cacti running in another location.

**To Reproduce**

Run Cacti in a custom directory (/opt)

**Expected behavior**

Use the path Cacti is running in

**Comment by netniV** [comment]
Ouch, that sounds like a line of my debugging version got into the live source.

**Comment by netniV** [comment]
This has now been resolved.
