### ISSUE TITLE
Graph not showing any data cacti 1.2.10

### ISSUE THREAD

**Issue by ndilooc** [Cacti/cacti#3316]
after creating device and new graph, cacti graph not showing any data,
![cacti2](https://user-images.githubusercontent.com/61731447/75837501-9ff28d80-5df7-11ea-9815-163a57b650f2.PNG)

cacti log 
![cacti3](https://user-images.githubusercontent.com/61731447/75837537-b6004e00-5df7-11ea-95f2-3a8807a4894c.PNG)

please help,

**Comment by bmfmancini** [comment]
Start with a debug on the data source
Try reindexing the device as well

Is it only this device having issues?

**Comment by ndilooc** [comment]
![cacti4](https://user-images.githubusercontent.com/61731447/75839144-a33b4880-5dfa-11ea-8432-8fd8fde8e3d6.PNG)

all the device not showing any graph,

**Comment by netniV** [comment]
See issue #3314 as I suspect you may have that problem.  Download the latest version of script_server.php or apply the patch from that commit and that should resolve it.

**Comment by cigamit** [comment]
Give us an update ASAP.  Thanks!!

**Comment by martinlegionowo** [comment]
Dear support,

I have the same problem. May you tell me from which place I can upload the script_server.php or patch and how I can apply it. I am quite new user of Cacti. Big thanks !

**Comment by netniV** [comment]
See issue 3314.

**Comment by martinlegionowo** [comment]
Hello,

this I know. I ask how we can upgrade the PHP script - only
override current ?
How we can apply fix - and from where we can download it ?
I overrided the script_server.php - I still have a problem with graphs with
the logs:
2020/03/13 14:10:01 - POLLER: Poller[Main Poller
<http://192.168.1.36/cacti/pollers.php?action=edit&id=1>] WARNING: Invalid
Response(s), Errors[4] Device[Cisco ASA Dach
<http://192.168.1.36/cacti/host.php?action=edit&id=9>] Thread[1] DS[Cisco
ASA Dach - 5 Minute CPU
<http://192.168.1.36/cacti/data_sources.php?action=ds_edit&id=148>, Cisco
ASA Dach - CPU - Idle
<http://192.168.1.36/cacti/data_sources.php?action=ds_edit&id=149>, Cisco
ASA Dach - CPU - System
<http://192.168.1.36/cacti/data_sources.php?action=ds_edit&id=150>, Cisco
ASA Dach - CPU - User
<http://192.168.1.36/cacti/data_sources.php?action=ds_edit&id=151>]
Graphs[Cisco
ASA Dach - CPU Usage, Cisco ASA Dach - CPU Utilization
<http://192.168.1.36/cacti/graph_view.php?page=1&style=selective&action=preview&graph_add=106%2C107>]

2020/03/13 14:10:01 - POLLER: Poller[Main Poller
<http://192.168.1.36/cacti/pollers.php?action=edit&id=1>] WARNING: Invalid
Response(s), Errors[5] Device[Sophos XG UTM
<http://192.168.1.36/cacti/host.php?action=edit&id=7>] Thread[1] DS[Sophos
XG UTM - Traffic - Port1
<http://192.168.1.36/cacti/data_sources.php?action=ds_edit&id=142>, Sophos
XG UTM - Traffic - Port2
<http://192.168.1.36/cacti/data_sources.php?action=ds_edit&id=143>, Sophos
XG UTM - Traffic - PortE1
<http://192.168.1.36/cacti/data_sources.php?action=ds_edit&id=144>, Sophos
XG UTM - Traffic - lag1
<http://192.168.1.36/cacti/data_sources.php?action=ds_edit&id=145>, Sophos
XG UTM - Traffic - lag1.2
<http://192.168.1.36/cacti/data_sources.php?action=ds_edit&id=146>]
Graphs[Sophos
XG UTM - Traffic - Port1/5, Sophos XG UTM - Traffic - Port2/6, Sophos XG
UTM - Traffic - PortE1/10, Sophos XG UTM - Traffic - lag1/24, Sophos XG UTM
- Traffic - lag1.2/25
<http://192.168.1.36/cacti/graph_view.php?page=1&style=selective&action=preview&graph_add=100%2C101%2C102%2C103%2C104>
]

RRDtool Command:

/usr/bin/rrdtool graph - \
--imgformat=PNG \
--start='-86400' \
--end='-300' \
--pango-markup  \
--title='Sophos XG UTM - Traffic - lag1.2/25' \
--vertical-label='bits per second' \
--slope-mode \
--base=1000 \
--height=200 \
--width=700 \
--rigid \
--alt-autoscale-max \
--lower-limit='0' \
COMMENT:"From 2020/03/12 14\:36\:07 To 2020/03/13 14\:31\:07\c" \
COMMENT:"  \n" \
--border 1 --slope-mode \
--watermark 'Generated by Cacti®' \
DEF:a='/var/www/html/cacti-1.2.10/rra/sophos_xg_utm_traffic_in_146.rrd':'traffic_in':MAX
\
DEF:b='/var/www/html/cacti-1.2.10/rra/sophos_xg_utm_traffic_in_146.rrd':'traffic_in':AVERAGE
\
DEF:c='/var/www/html/cacti-1.2.10/rra/sophos_xg_utm_traffic_in_146.rrd':'traffic_out':MAX
\
DEF:d='/var/www/html/cacti-1.2.10/rra/sophos_xg_utm_traffic_in_146.rrd':'traffic_out':AVERAGE
\
CDEF:cdefa='a,8,*' \
CDEF:cdefb='b,8,*' \
CDEF:cdeff='c,8,*' \
CDEF:cdefg='d,8,*' \
LINE1:cdefa#00CF00FF:  \
AREA:cdefb#00CF007F:'Inbound '  \
GPRINT:cdefb:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefb:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdefb:MAX:'Maximum\:%8.2lf %s\n'  \
LINE1:cdeff#002A97FF:  \
AREA:cdefg#002A977F:'Outbound'  \
GPRINT:cdefg:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefg:AVERAGE:'Average\:%8.2lf %s'  \

GPRINT:cdefg:MAX:'Maximum\:%8.2lf %s\n'

Regards,
Marcin





pt., 13 mar 2020 o 11:12 Mark Brugnoli-Vinten <notifications@github.com>
napisał(a):
