### ISSUE TITLE
Need Cacti SNMP PHP Libraries Source Code

### ISSUE THREAD

**Issue by alisiddiqui1987** [Cacti/cacti#3318]
Hi Team,

Can you please help us providing the source code for SNMP libraries in cacti whose source code is not there.

Thanks & Best Regards,
Ali Ahmed Siddiqui

**Comment by netniV** [comment]
We do not have sources to the SNMP libraries.  We use either PHP-SNMP or NetSNMP libraries.

**Comment by alisiddiqui1987** [comment]
Thank netniV. do you have any code related to PHP-SNMP or NetSNMP libraries.

if you have can you please share the same with me please

its critical for my project

**Comment by netniV** [comment]
Not sure what you are actually after, as I already stated, we don't maintain those libraries.

**Comment by alisiddiqui1987** [comment]
any suggestion from where I could get them?

**Comment by TheWitness** [comment]
You can download the php-snmp source code from the php.net developers website.  They used to use SVN, but I think they might be on GitHub now.  Yup was right.  The link is here:

https://github.com/php/php-src
