### ISSUE TITLE
Unable to Import Mikrotik Device Template

### ISSUE THREAD

**Issue by Jh0nHerrera** [Cacti/cacti#3320]
Hi team,
I am trying to import a device template of mikrotik, but i execute the commando from cli but nothing happen as you can see in the image below
![image](https://user-images.githubusercontent.com/61655570/75892772-dfbd7300-5dff-11ea-90f6-24d753cdd73c.png)

My system is:
CentOS 7
PHP 7.4
MariaDB 10.4
Apache 2.4
Cacti 1.2.10

Note: i delete netsnmp_device template and try to import it and i get the same.

**Comment by cigamit** [comment]
Wrong command.  That is a package.  You should try:

```cmd
php -q import_package.php --filename=/path/to/the/gz/file  --preview
```

**Comment by Jh0nHerrera** [comment]
Thanks for you help, now working, but this package can't be imported from GUI ? i ask this because when i try to import from the GUI i get hash error.

**Comment by TheWitness** [comment]
There is no package import from the GUI.
