### ISSUE TITLE
Set Default Graph Policy for User is not Working  - Cacti 1.2.10

### ISSUE THREAD

**Issue by Jh0nHerrera** [Cacti/cacti#3324]
Hello Team,
When i try to set Default Graph Policy to Deny for a user nothing happen and no change to Deny, this happen with any user. Only this works if i set to User Group, but for individual user is not working.
Note: in other tabs works, such as Device perms, Tree perms, etc.

OS: CentOS 7.X
PHP 7.4
APACHE 2.4
MariaDB 10.4
Cacti 1.2.10

**Comment by netniV** [comment]
You can actually see why graphs are being allowed by hovering over the effective policy text.

**Comment by Jh0nHerrera** [comment]
Hi thanks for your help, now is working, looks like cache of the web browser.
