### ISSUE TITLE
1.2.8 to 1.2.10 no more LDAP

### ISSUE THREAD

**Issue by hiddenicon** [Cacti/cacti#3328]
**Describe the bug**
We've upgraded two instances of cacti from 1.2.8 to 1.2.10. After that, all LDAP auth stopped working which was previously working. We are using the multiple AD domains/User Domains for auth. All local accounts work fine.

**Vesion:**
Cacti 1.2.10 on RHEL 7.x

**Additional context**
We tried different browsers and clearing browser cache. 
As you hit the login button, it fails right away with "Invalid User Name/Password Please Retype".
Doing a packet capture on the cacti server, we do not see any packets going toward the LDAP configured IP so it appears it's not even trying LDAP.

**Comment by netniV** [comment]
If you raise your debugging levels, see what LDAP messages are recorded.

**Comment by hiddenicon** [comment]
Ok so when on debug, I was seeing a lot of LDAP DN searches failing. User DN not found, etc. I tested all of the variation of settings for LDAP and found that only Specific Searching with its proper config works for me now. I had it previously set to anonymous searching and that was working on 1.2.8. I know there are LDAP changes moving forward about using User Domains only. Not sure if there was a change that would affect this.

The only issue I see now is that LDAP CN Settings for Full Name and eMail are not working. I'm going against Active Directory and no matter what field I put into there, the full name and email do not get filled in.

**Comment by cigamit** [comment]
Can you post some of the LDAP debug information related to the Full Name and Email issues?  On the other issue, your LDAP administrator may have blocked anonymous browsing as it's a security issue and likely a GPDR issue.

**Comment by hiddenicon** [comment]
We have anonymous searching enabled still, it is working on another cacti VM I have running on a lower 1.2.x version. Along with the upgrade from 1.2.8 to 1.2.10, we also did a RHEL OS update as well. Does Cacti use PHP LDAP or another module to do the LDAP Auth? I can check to see if that was updated and any changes there.

Here is the debug when adding a user upon first login. The full_name of "LDAP_DEFAULT" is the local user created to be used as the template. We've tried many LDAP attributes including displayname, sAMAccountName, mail, iPhone, etc to get anything from LDAP into there but nothing happens.

2020/03/09 10:52:48 - AUTH LDAP_SEARCH: Authentication Success, DN: CN=<USER>
2020/03/09 10:52:48 - AUTH LOGIN: LDAP User '<USER>' Authenticated from Domain '<DOMAIN>'
2020/03/09 10:52:48 - AUTH WARN: User '<USER>' does not exist, copying template user

2020/03/09 10:52:48 - DBCALL DEVEL: SQL Save on table 'user_auth': 'a:25:{s:2:"id";i:0;s:8:"username";s:6:"<USER>";s:8:"password";i:9211282;s:5:"realm";s:4:"1001";s:9:"full_name";s:12:"LDAP_DEFAULT";s:13:"email_address";s:0:"";s:20:"must_change_password";s:0:"";s:15:"password_change";s:0:"";s:9:"show_tree";s:2:"on";s:9:"show_list";s:2:"on";s:12:"show_preview";s:2:"on";s:14:"graph_settings";s:2:"on";s:10:"login_opts";s:1:"1";s:13:"policy_graphs";s:1:"1";s:12:"policy_trees";s:1:"1";s:12:"policy_hosts";s:1:"1";s:22:"policy_graph_templates";s:1:"1";s:7:"enabled";s:2:"on";s:10:"lastchange";s:2:"-1";s:9:"lastlogin";s:2:"-1";s:16:"password_history";s:0:"";s:6:"locked";s:0:"";s:15:"failed_attempts";s:1:"0";s:8:"lastfail";s:1:"0";s:11:"reset_perms";s:10:"2073242544";}'
2020/03/09 10:52:48 - AUTH LOGIN: User '<USER>' Authenticated

Template local user:
![image](https://user-images.githubusercontent.com/10273594/76229501-b2563800-61f8-11ea-87d1-d17dc9a7d0bc.png)

**Comment by netniV** [comment]
That is very strange.  And you don't have any errors showing in the cacti.log or php/apache error logs? Is the username blank or have you blanked it?

**Comment by hiddenicon** [comment]
Yes I blanked out our domain and username. That was the only entry in the cacti.log when I did the AUTH. I didn't check php/apache logs. The template user for LDAP users is in that screenshot. It's name is configured as LDAP_DEFAULT, and that's what is being used to create the new user from LDAP. It appears it's not using those LDAP CN settings. 

One thing, since I had this LDAP issue after going to 1.2.10, I was testing all of the settings and landed on the User Domain. We were originally setup for normal LDAP with anonymous searching.

Is cacti using PHP LDAP? Or what module?

**Comment by netniV** [comment]
In 1.3, I had planned to phase out the single LDAP usage because it makes no real sense duplicating a lot of settings and work.  Unfortunately, don't have a lot of LDAP configurations to test against to know what the issue might actually be.

**Comment by hiddenicon** [comment]
Since this is resolved for me using user domains with specific searching, I can close this issue and open new ones pertaining to the specifics (ie. CN Settings not coming over).

**Comment by hume-github** [comment]
Since #3379 was marked as being the duplicate of this bug, I'll make this comment here so that people searching for the error maybe find it.

I'm going to echo that I'm also seeing odd LDAP login problems, in an upgrade from 1.1.26 to 1.2.10.  If you load the main login page and try to log in directly, it will fail, and you'll even see "AUTH LOGIN: LDAP Login Failed" in the cacti.log.

However, if you first change the Realm from LDAP to Local back to LDAP, it will work.

After turning on debugging, the following cacti.log lines are generated:

> AUTH DEBUG: User 'hume' attempting to login with realm , using method 3

... for a no-special-steps login, and the following line for a swap-trick login:

> AUTH DEBUG: User 'hume' attempting to login with realm 2, using method 3

I'll be upgrading to 1.2.11 as soon as possible and hopefully it will cure the issue.

**Comment by netniV** [comment]
We would be grateful if you could confirm that resolves your issue.  I think we would like to streamline the login process again in 1.3 because it's historic code that's been built upon but it's in a few places.

**Comment by netniV** [comment]
Oh and I would wait for 1.2.12 this weekend as we have had quite a few more fixes that are coming especially around auth, cookie domains and package installation.

**Comment by hiddenicon** [comment]
1.2.11 appears to have fixed any LDAP auth issues I've been having. I haven't pulled the latest dev on here to try though. 

Do you follow a certain release schedule?

**Comment by netniV** [comment]
We try to release on the weekend around the end of the month but sometimes it creeps into the week after. This weekend will be release weekend.
