### ISSUE TITLE
Add new tool to rebuild the graph and data source title_cache

### ISSUE THREAD

**Issue by CapitalF** [Cacti/cacti#333]
I often need to make mass changes to data in Cacti, and the web user interface often doesn't give me the tools I need to do that effectively, so I turn to accessing the SQL DB directly, either in the mysql command line or bash scripts.

I recently needed to change the titles of graphs and data sources en-mass, but I ran into trouble when it came to rebuilding the title_cache field for both.

I need to rebuild the title caches, but there doesn't seem to be an easy way to do that right now.

The poller_graphs_reapply_names.php and poller_data_sources_reapply_names.php commands in the cli tools dir almost do what I want, but both apply suggested names before doing so.

As a workaround, I simply copy both files are rename them, and then comment-out the "api_reapply_suggested_graph_title" line.

cp -ap poller_graphs_reapply_names.php update_graph_title_cache.php
cp -ap poller_data_sources_reapply_names.php update_data_source_title_cache.php

Could you please add an argument to these commands to skip processing of the api_reapply_suggested_graph_title function?

**Comment by cigamit** [comment]
Closings this.  There are already two scripts in the CLI directory that are responsible for this.
