### ISSUE TITLE
Remove files graph_items.php and graph_templates_items.php

### ISSUE THREAD

**Issue by cigamit** [Cacti/cacti#3332]
**Is your feature request related to a problem? Please describe.**
These files, being that their function has been separated from the base file in Cacti cause navigation issues on the Cacti menu.  They should be removed, and their functionality moved to the interior of their parent files.  This also affects color_templates_items.php which cloned the prior two files.

**Describe the solution you'd like**
Sub functionality should be held in the main file and not separated in another file.

**Describe alternatives you've considered**
Hacking the various menu functions for navigation to work the way we would have it.

**Comment by netniV** [comment]
Could we change the files to be .inc's and then include them within the main source?

**Comment by TheWitness** [comment]
I'd say just dump the old files.  There are a few others as well.

**Comment by TheWitness** [comment]
Good one for taking on.

**Comment by TheWitness** [comment]
This one is resolved now.  Need to combined Aggregate and Color Templates as well.
