### ISSUE TITLE
Allow sequential network scans via AUTOM8

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3333]
Hey  Guys 

one feature that would be great to have for autom8 is the ability to schedule network scans but instead of network by network you can have all networks scan but sequentially to prevent tons of proccessess happening all at once 

Example you have 5 networks 
schedule the scan for Midnight on Monday 
when network 1 is done network 2 starts 

There should be some sort of check in case one of the network scans get hung the others start say after 20 mins regardless of the state of the first scan 

Right now I stagnate my scans by time and even day but it would be awsome not to have to keep track of the scheduled scans and just tell cacti start at X time and whenever your done your done

thanks guys !!

**Comment by netniV** [comment]
There are two ways to implement this:

- Network A has an option to run another Network set to Network B
  or
- Network B has a dependancy on Network A

The problem we have is that with the first, you can end up circling around if you don't check the chain fully.  With the second, you could run multiple scans from a single one, and onwards, resulting in large scale run by mistake.
