### ISSUE TITLE
Can't change polling time

### ISSUE THREAD

**Issue by Izmenoff** [Cacti/cacti#3337]
cacti 1.2.10
mariaDB
spine 1min

All graphs use the same template - (Interface - Traffic) with Data profile 1 minute. It works fine except several graphs which respound time 5min.

I tried to change graph template, data profile time resp from 1min to 5min (System Default) and return back. No results. 
But if delete rrd files of problem grpaphs, it works ok.

It is not a big problem to delete rrd, but I'll lost statistics.

![image](https://user-images.githubusercontent.com/17400240/76308416-cb83e500-62db-11ea-88b6-d54f31c6343d.png)

![image](https://user-images.githubusercontent.com/17400240/76308436-db032e00-62db-11ea-994c-ba2cfc20ea43.png)

![image](https://user-images.githubusercontent.com/17400240/76308496-f8d09300-62db-11ea-9572-c522033daf7f.png)

**Comment by netniV** [comment]
That is expected.  The RRD files have a value built into them which details the time expected between value updates.  If you increase from 1 minute to 5 minutes, you effectively exceed the heartbeat so RRDtool believes that you've got missing data.

Check out the data source for your graph and the examine the debug info on that page.

**Comment by TheWitness** [comment]
There is a new CLI called splice_rrd.php that will allow you to change the 'step' (polling interval). Of two RRDfiles.  It's a CLI only.  There is no bulk changes from the Web Interface though as it's a pretty CPU intensive command.

**Comment by Izmenoff** [comment]
which command I should run from cli ? php splice_rrd.php my.rrd  ?

**Comment by Izmenoff** [comment]
Data Source Debug
/bin/rrdtool create \
/var/www/html/cacti/rra/mi_asbr1_traffic_in_33460.rrd \
--start -900 --step 60  \
DS:traffic_in:COUNTER:120:0:20000000000 \
DS:traffic_out:COUNTER:600:0:20000000000 \
RRA:AVERAGE:0.5:1:1450 \
RRA:AVERAGE:0.5:5:580 \
RRA:AVERAGE:0.5:15:1346 \
RRA:AVERAGE:0.5:60:1440 \
RRA:AVERAGE:0.5:1440:730 \
RRA:MIN:0.5:1:1450 \
RRA:MIN:0.5:5:580 \
RRA:MIN:0.5:15:1346 \
RRA:MIN:0.5:60:1440 \
RRA:MIN:0.5:1440:730 \
RRA:MAX:0.5:1:1450 \
RRA:MAX:0.5:5:580 \
RRA:MAX:0.5:15:1346 \
RRA:MAX:0.5:60:1440 \
RRA:MAX:0.5:1440:730 \
RRA:LAST:0.5:1:1450 \
RRA:LAST:0.5:5:580 \
RRA:LAST:0.5:15:1346 \
RRA:LAST:0.5:60:1440 \
RRA:LAST:0.5:1440:730 \

**Comment by TheWitness** [comment]
Move the 1 minute RRD out of the way, let cacti create the 5 minute RRD, then follow the instructions when you run 'splice_rrd.php --help'.

**Comment by Izmenoff** [comment]
**TheWitness**, Thanks a lot! It works
