### ISSUE TITLE
Script server logfile error

### ISSUE THREAD

**Issue by KnoAll** [Cacti/cacti#3338]
**Describe the bug**
I'm getting errors in the cacti.log about script_server.php...

2020/03/10 10:44:04 - CMDPHP PHP ERROR WARNING Backtrace: (/script_server.php[183]:unlink(), CactiErrorHandler())
--
2020/03/10 10:44:04 - ERROR PHP WARNING: unlink(/usr/share/cacti/site/log/script_server_49508.out): No such file or directory in file: /var/www/html/cacti/script_server.php on line: 183
2020/03/10 10:44:04 - CMDPHP PHP ERROR WARNING Backtrace: (/script_server.php[183]:unlink(), CactiErrorHandler())
2020/03/10 10:44:04 - ERROR PHP WARNING: unlink(/usr/share/cacti/site/log/script_server_49502.out): No such file or directory in file: /var/www/html/cacti/script_server.php on line: 183

I'm on a centos system with cacti installed in /var/www/html so the /usr/share/cacti is not a valid path.

I've checked line 183 and it is:
unlink($log_file);
which is set on line 137 to
$log_file = '/usr/share/cacti/site/log/script_server_' . getmypid() . '.out';

appears to be statically set and not pulled from the paths settings.

**Comment by netniV** [comment]
This has been reported already and corrected.

**Comment by netniV** [comment]
This is the duplicate reference: https://github.com/Cacti/cacti/issues/3314
