### ISSUE TITLE
[Question/Advice] Perfomance Impact of SNMPV3 vs V2 cacti 1.2.7

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3339]
Hey Guys 

So I have an instance with 11k devices which will grow soon to 18k devices 
currently 90% of the devices are on SNMPV2 but the devices will be moving to SNMPV3 
we have been slowly making the changes and I notice there is a small performance impact per device 

Now I know SNMPV3 will have an overhead due to encryption especially if you are using authpriv mode
I am just wondering if the impact I am seeing is that overhead or something else 

for example I have a poller with 6k device that was polling at 46seconds average after converting 200 devices to V3 its now averaging around 50 seconds 
I raised the process count on the poller to bring it down closer to my liking

**Comment by netniV** [comment]
Any encryption adds overhead and depending on the power and capacity of your box, this usually starts in milliseconds.  Of course even 10 milliseconds x 6000 devices is still 6 seconds extra.  For 20 seconds, that becomes 12 seconds extra, etc.

**Comment by TheWitness** [comment]
Spine is using sessions.  So not too bad.  However make sure your servers are core rich, as it'll take more cpu.

**Comment by TheWitness** [comment]
Use either a P8/P9 or Rome/Epyc system with lot's of threads and then it should not matter.  The P9 boxes are perfect for a big Cacti system.
