### ISSUE TITLE
primary key on poller output boost table not efficient/not being used correctly

### ISSUE THREAD

**Issue by rprofijt** [Cacti/cacti#334]
We found that on large systems (+- 240.000 data sources) it takes ages for the boost poller to get data from MySQL. (and creating a large backlog) After investigating MySQL was doing a lot of "creating sort index".

The boost_poller_output table is created with this primary key:

PRIMARY KEY USING BTREE (`local_data_id`,`rrd_name`,`time`)

But the select queries are being done like this:

SELECT local_data_id, UNIX_TIMESTAMP(time) AS timestamp, rrd_name, output FROM poller_output_boost_arch_1487853923 FORCE INDEX (PRIMARY) ORDER BY local_data_id ASC, rrd_name ASC , time ASC  LIMIT 100000;

We fixed the issue by changing the primary key to this order:

ALTER TABLE poller_output_boost DROP PRIMARY KEY, ADD PRIMARY KEY  (`local_data_id`, time, rrd_name) USING BTREE;

**Comment by cigamit** [comment]
Resolved.  Thanks for catching and reporting this!
