### ISSUE TITLE
PHP Error when loading broken/empty 95th percentile graphs

### ISSUE THREAD

**Issue by rprofijt** [Cacti/cacti#3340]
**Describe the bug**
After upgrading to 1.2.10 (from 1.1.38) we get these errors in the cacti log:

2020/03/11 11:28:24 - CMDPHP PHP ERROR NOTICE Backtrace: (/graph_json.php[159]:rrdtool_function_graph(), /lib/rrd.php[1586]:variable_nth_percentile(), /lib/graph_variables.php[449]:nth_percentile(), /lib/graph_variables.php[33]:rrdtool_function_stats(), /lib/graph_variables.php[140]:nth_percentile_fetch_statistics(), /lib/graph_variables.php[153]:CactiErrorHandler())
2020/03/11 11:28:24 - ERROR PHP NOTICE: Undefined index: values in file: /opt/cacti/cacti-prod/lib/graph_variables.php on line: 153 

**To Reproduce**

Open/render a graph with 95th percentile and nan values.

**Expected behavior**
Render the empty broken graph without PHP errors

**Comment by TheWitness** [comment]
Update the graph_variables.php from the 1.2.x branch and let us know if this is fixed.

**Comment by rprofijt** [comment]
Fixed, thanks!

**Comment by a-vasilishin** [comment]
I have the same problem. Cacti 1.2.10 download via copy/paste  graph_variables.php from the 1.2.x branch.
