### ISSUE TITLE
PHP Error when loading Cacti login page

### ISSUE THREAD

**Issue by rprofijt** [Cacti/cacti#3341]
**Describe the bug**
When loading Cacti from Firefox/Edge/Chrome in Windows we get this error in the Cacti log:

2020/03/11 11:13:08 - CMDPHP PHP ERROR WARNING Backtrace: (/index.php[25]:include(), /include/auth.php[28]:require_once(), /include/global.php[478]:include_once(), /include/global_languages.php[230]:load_gettext_oscarotero(), /include/global_languages.php[278]:Gettext\Translations::__callStatic(), /include/vendor/gettext/src/Translations.php[153]:call_user_func_array(), Gettext\Translations->__call(), /include/vendor/gettext/src/Translations.php[174]:call_user_func(), Gettext\Extractors\Extractor::fromFile(), /include/vendor/gettext/src/Extractors/Extractor.php[18]:Gettext\Extractors\Mo::fromString(), /include/vendor/gettext/src/Extractors/Mo.php[44]:Gettext\Extractors\Mo::readIntArray(), /include/vendor/gettext/src/Extractors/Mo.php[126]:unpack(), CactiErrorHandler())
2020/03/11 11:13:08 - ERROR PHP : unpack(): Type V: not enough input, need 4, have 0 in file: /opt/cacti/cacti-prod/include/vendor/gettext/src/Extractors/Mo.php on line: 126 

We don't see the error on a Linux desktop with Firefox. Might be a language thing? The Windows desktop has been set to Dutch, Linux desktop is English.

**Comment by netniV** [comment]
That is a third party library for parsing MO/PO files.  You can change which interpreter is used.  I will also have to see if there is an update to that library as that may resolve things.

**Comment by TheWitness** [comment]
What language was this?  Where did you get the MO file from?

**Comment by TheWitness** [comment]
Please update the Mo.php from the 1.2.x branch and let us know if the issue is resolved.

**Comment by rprofijt** [comment]
Dutch, still getting the error on the latest pull

**Comment by rprofijt** [comment]
Error: 

2020/03/13 13:51:01 - CMDPHP PHP ERROR WARNING Backtrace:   (/index.php[25]:include(), /include/auth.php[28]:require_once(),  /include/global.php[482]:include_once(),  /include/global_languages.php[230]:load_gettext_oscarotero(),  /include/global_languages.php[278]:Gettext\Translations::__callStatic(),   /include/vendor/gettext/src/Translations.php[153]:call_user_func_array(),  Gettext\Translations->__call(),  /include/vendor/gettext/src/Translations.php[174]:call_user_func(),  Gettext\Extractors\Extractor::fromFile(),  /include/vendor/gettext/src/Extractors/Extractor.php[18]:Gettext\Extractors\Mo::fromString(),   /include/vendor/gettext/src/Extractors/Mo.php[44]:Gettext\Extractors\Mo::readIntArray(),  /include/vendor/gettext/src/Extractors/Mo.php[130]:unpack(),  CactiErrorHandler())
--
2020/03/13 13:51:01 - ERROR PHP : unpack(): Type V: not enough  input, need 4, have 0 in file:  /opt/cacti/cacti-prod/include/vendor/gettext/src/Extractors/Mo.php  on  line: 130

**Comment by TheWitness** [comment]
Okay, just updated again.  Update and let us know.

**Comment by rprofijt** [comment]
Sadly no:

2020/03/13  15:51:49 - CMDPHP PHP ERROR WARNING Backtrace:   (/index.php[25]:include(), /include/auth.php[28]:require_once(),  /include/global.php[482]:include_once(),  /include/global_languages.php[230]:load_gettext_oscarotero(),  /include/global_languages.php[278]:Gettext\Translations::__callStatic(),   /include/vendor/gettext/src/Translations.php[153]:call_user_func_array(),  Gettext\Translations->__call(),  /include/vendor/gettext/src/Translations.php[174]:call_user_func(),  Gettext\Extractors\Extractor::fromFile(),  /include/vendor/gettext/src/Extractors/Extractor.php[18]:Gettext\Extractors\Mo::fromString(),   /include/vendor/gettext/src/Extractors/Mo.php[44]:Gettext\Extractors\Mo::readIntArray(),  /include/vendor/gettext/src/Extractors/Mo.php[133]:unpack(),  CactiErrorHandler())

2020/03/13 15:51:49 - ERROR PHP : unpack(): Type V: not enough  input, need 4, have 0 in file:  /opt/cacti/cacti-prod/include/vendor/gettext/src/Extractors/Mo.php  on  line: 133

**Comment by TheWitness** [comment]
Okay, updated again.  Once this is isolated, have to figure out the correct way to compensate.

**Comment by netniV** [comment]
Have we checked for an updated version of the component since it is a third party    one ?

**Comment by rprofijt** [comment]
Error is gone, thanks.

**Comment by netniV** [comment]
Whilst the error is gone within our source vendor files, because this fix has not been patched on the original vendor sources, it is likely to be reintroduced by any systems relying on packages, such as CentOS, ubuntu, debian, etc. all of which are quite popular.

**Comment by TheWitness** [comment]
We should upstream it then.
