### ISSUE TITLE
CSRF at Admin Email

### ISSUE THREAD

**Issue by Baheraimarjun** [Cacti/cacti#3342]
**Describe the bug**
A malformed GET request at http://192.168.56.106/cacti/auth_profile.php?action=edit can lead to admin email change.

Affected URI
http://192.168.56.106/cacti/auth_profile.php?action=edit

**To Reproduce**
1. Go to 'http://192.168.56.106/cacti/auth_profile.php?action=edit'
2. Turn on a proxy interceptor, I used Burp.
3. Change the email and save the request.
4. Change the email in the saved request and send the URL to a logged in admin.
5. Admin email will be changed

Malformed Request:
http://192.168.56.106/cacti/auth_profile.php?tab=general&action=update_data&name=email_address&value=attacker@abc.com

**Expected behavior**
Such actions should not be requested with GET method and anti-CSRF tokens should be used.

 - OS: Ubuntu
 - Browser: Firefox
 - Version: Cacti Version 1.2.8

**Comment by TheWitness** [comment]
This should be blocked.

**Comment by TheWitness** [comment]
This should be fixed now.
