### ISSUE TITLE
Cacti 1.2.8 -> 1.2.10 failed after php updated 7.2 - 7.3

### ISSUE THREAD

**Issue by Izmenoff** [Cacti/cacti#3344]
Ater php uptated 7.2 to 7.3 problem with cacti update 
Installation is hanging on this screen
![image](https://user-images.githubusercontent.com/17400240/76492235-c8563980-6440-11ea-90ba-f823dab08f18.png)
12-Mar-2020 09:03:41 - ERROR PHP ERROR: Maximum execution time of 50 seconds exceeded in file: /var/www/html/cacti/lib/import.php on line: 279
12-Mar-2020 09:03:41 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
12-Mar-2020 09:03:42 - IMPORT NOTE: Got Package Signature
12-Mar-2020 09:03:42 - IMPORT NOTE: File is Signed Correctly
12-Mar-2020 09:03:42 - IMPORT Loading Plugin Information from package
12-Mar-2020 09:03:42 - ERROR PHP ERROR: Uncaught Error: Call to undefined function simplexml_load_string() in /var/www/html/cacti/lib/import.php:308 Stack trace: #0 /var/www/html/cacti/cli/import_package.php(99): import_package('//var/www/html/...', '', false, false, true) #1 {main} thrown in file: /var/www/html/cacti/lib/import.php on line: 308
12-Mar-2020 09:03:42 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
12-Mar-2020 09:03:42 - IMPORT NOTE: Got Package Signature
12-Mar-2020 09:03:42 - IMPORT NOTE: File is Signed Correctly
12-Mar-2020 09:03:42 - IMPORT Loading Plugin Information from package
12-Mar-2020 09:03:42 - ERROR PHP ERROR: Uncaught Error: Call to undefined function simplexml_load_string() in /var/www/html/cacti/lib/import.php:308 Stack trace: #0 /var/www/html/cacti/cli/import_package.php(99): import_package('//var/www/html/...', '', false, false, true) #1 {main} thrown in file: /var/www/html/cacti/lib/import.php on line: 308
12-Mar-2020 09:03:42 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
12-Mar-2020 09:03:42 - IMPORT NOTE: Got Package Signature
12-Mar-2020 09:03:42 - IMPORT NOTE: File is Signed Correctly
12-Mar-2020 09:03:42 - IMPORT Loading Plugin Information from package
12-Mar-2020 09:03:42 - ERROR PHP ERROR: Uncaught Error: Call to undefined function simplexml_load_string() in /var/www/html/cacti/lib/import.php:308 Stack trace: #0 /var/www/html/cacti/cli/import_package.php(99): import_package('//var/www/html/...', '', false, false, true) #1 {main} thrown in file: /var/www/html/cacti/lib/import.php on line: 308
12-Mar-2020 09:03:42 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
2020-03-12 09:03:42 - SPINE: Poller[1] PID[3248] Device[100] Hostname[10.166.1.5] ERROR: HOST EVENT: Device is DOWN Message: Device did not respond to SNMP, UDP: Device is Alive
12-Mar-2020 09:03:42 - IMPORT NOTE: Got Package Signature
12-Mar-2020 09:03:42 - IMPORT NOTE: File is Signed Correctly
12-Mar-2020 09:03:42 - IMPORT Loading Plugin Information from package
12-Mar-2020 09:03:42 - ERROR PHP ERROR: Uncaught Error: Call to undefined function simplexml_load_string() in /var/www/html/cacti/lib/import.php:308 Stack trace: #0 /var/www/html/cacti/cli/import_package.php(99): import_package('//var/www/html/...', '', false, false, true) #1 {main} thrown in file: /var/www/html/cacti/lib/import.php on line: 308
12-Mar-2020 09:03:42 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
12-Mar-2020 09:03:42 - IMPORT NOTE: Got Package Signature
12-Mar-2020 09:03:42 - IMPORT NOTE: File is Signed Correctly
12-Mar-2020 09:03:42 - IMPORT Loading Plugin Information from package
12-Mar-2020 09:03:42 - ERROR PHP ERROR: Uncaught Error: Call to undefined function simplexml_load_string() in /var/www/html/cacti/lib/import.php:308 Stack trace: #0 /var/www/html/cacti/cli/import_package.php(99): import_package('//var/www/html/...', '', false, false, true) #1 {main} thrown in file: /var/www/html/cacti/lib/import.php on line: 308
12-Mar-2020 09:03:42 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
![image](https://user-images.githubusercontent.com/17400240/76492608-b45f0780-6441-11ea-9e5c-0e4dd0662c57.png)

**Comment by Izmenoff** [comment]
!!!after update php to 7.3 you have to install additional components (php-snmp php-gmp php-simplexml php-xml)

**Comment by netniV** [comment]
Unfortunately upgrading PHP on some systems doesn’t update the installed modules or custom settings.
