### ISSUE TITLE
Broken rewrite of octet strings

### ISSUE THREAD

**Issue by browniebraun** [Cacti/cacti#3346]
I have just found a tiny, but really nasty bug in /lib/data_query.php, line 1119.
There is a space in the pattern (at **'}) {2**') that breaks the recognition of octet strings like e.g. '5.103.101.48.47.49'

`if (preg_match('/^\d{1,3}(\.\d{1,3}) {2,}$/', $parse_value)) {`

**Comment by TheWitness** [comment]
Fixed @browniebraun
