### ISSUE TITLE
multi cut and poller  some time take 9s and some time 298s

### ISSUE THREAD

**Issue by Lashinkof** [Cacti/cacti#3347]
after migration from 0.8.8h to 1.2.10 I facing  multi cut and poller  some time take 9s and some time 298s , same issue with boost.
![31](https://user-images.githubusercontent.com/62134083/76698135-4c622880-66b0-11ea-8a17-40d905d95a0e.PNG)

**Comment by TheWitness** [comment]
What is 'multi-cut'?  Are you using spine?

**Comment by Lashinkof** [comment]
yes I'm useing spine and tried boost nad same issue 
![git 1](https://user-images.githubusercontent.com/62134083/76728695-842ca700-6768-11ea-9757-af27c422e989.png)
![git 2](https://user-images.githubusercontent.com/62134083/76728701-85f66a80-6768-11ea-8b37-5ad44205e6d5.png)

**Comment by TheWitness** [comment]
298 is a symptom of a segfault or some other issue like running out of MySQL connections.  What is showing in your cacti.log?  You might want to setup your cron so that it can generate a core file.  You may have to google that.

**Comment by TheWitness** [comment]
Any update?

**Comment by Lashinkof** [comment]
I can't find any sql issue  tomorrow I will upload log file

**Comment by TheWitness** [comment]
No feedback.
