### ISSUE TITLE
Variable max_input_vars is read only.  Attempting to change it adds no value

### ISSUE THREAD

**Issue by YongBoLiu** [Cacti/cacti#3349]
**Describe the bug**

When select more than 1000 hosts in one cation, get the errors as below, in error_log of httpd.

[Wed Mar 11 02:51:33.188573 2020] [:error] [pid 3272] [client 9.197.250.110:55005] PHP Warning:  Unknown: Input variables exceeded 1000. To increase the limit change max_input_vars in php.ini. in Unknown on line 0, referer: http://9.21.55.81/cacti/...

**To Reproduce**
1. select 1000+ hosts in some plugins,
2. take the action to open/close the devices.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
The max_input_vars can't be set in user's code. Because it's changeable is PHP_INI_PERDIR.
So, we have to change php.ini if we support open/close 1000 hosts in one action.
 
#find . -name "*php"|xargs grep ini_set.*max_input_vars

./cacti/include/global.php:ini_set('max_input_vars', '5000');
./cacti/include/global.php:    ini_set('max_input_vars', '5000');
 
Ref: 
https://stackoverflow.com/questions/9973555/setting-max-input-vars-php-ini-directive-using-ini-set
 
https://www.php.net/manual/en/info.configuration.php

**Comment by YongBoLiu** [comment]
Although it's not effect any feature in cacti native, we should remove these settings.

**Comment by TheWitness** [comment]
Fixed.
