### ISSUE TITLE
Gettext - French Translation error

### ISSUE THREAD

**Issue by SoNix21** [Cacti/cacti#335]
On the "login" page, there is 2 typos... i think the gettext of french translation need \ before the '

So... "Nom d'utilisateur" and "S'Inscrire" is cropped.

![image](https://cloud.githubusercontent.com/assets/25518106/23276576/cd300f7e-f9d8-11e6-9e52-2da4496cbf5f.png)

**Comment by browniebraun** [comment]
Many thanks for your feedback.
All current translation files are completely outdated at the moment. Unfortunately I'm not proficient in French, but it would be awesome if you or someone else would volunteer for that part. I'm currently working on the German catalog while jpobeda is making real progress with a Spanish version.

Regards
-Andi

**Comment by browniebraun** [comment]
Ok, this is a real bug - need to clarify some coding standards first.
