### ISSUE TITLE
Upgrade from 1.2.7 to 1.2.9 Spine binary not found only on remote pollers

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3351]
Hey Guys 

I recently upgraded from 1.2.7 to 1.2.9 

Upgrade went fine I upgraded spine to 1.2.9 thats where the remote pollers come back with an errors that spine cannot be found but the file is indeed there 

Any help is appreciated 

Thanks!

**Comment by bmfmancini** [comment]
![image](https://user-images.githubusercontent.com/13388748/76773440-d675c400-6778-11ea-927d-b18bb8fc8bc6.png)

![image](https://user-images.githubusercontent.com/13388748/76773602-1fc61380-6779-11ea-8269-98697e163f92.png)

total 388
-rwsr-sr-x 1 root root 397064 Mar 16 11:16 spine

**Comment by bmfmancini** [comment]
Well that was interesting on the remote pollers and only on the remote pollers I had to make the folder permissions 755 so apache could access it 
I seem to remember reporting this type of issue before

**Comment by TheWitness** [comment]
Weird, I confirmed everything was working, but for some reason spine was not working as expected.  Still trying to figure out what is wrong.  So, is this resolved for you then?

**Comment by bmfmancini** [comment]
Yes resolved on my end  but maybe something to look into?

**Comment by TheWitness** [comment]
I'll log it separately.  I have to first figure out why it's behaving oddly.  Some mix of profile and poller interval I think.
