### ISSUE TITLE
1.2.9 tree view search bar not visible

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3357]
Hey Guys 

I am pretty sure this is a duplicate issue but I am not able to find it 
On 1.2.9 the search bar on tree view goes missing but if you right-click on the textbox and select the inspect element the textbox becomes visible ??

![image](https://user-images.githubusercontent.com/13388748/76873925-ce835600-6844-11ea-9fdc-fb7c4ffb0277.png)

after selecting inspect element

![image](https://user-images.githubusercontent.com/13388748/76873988-e2c75300-6844-11ea-9e5b-2285ad509fc4.png)

Here is the code I see 
```
<input type="text" class="ui-state-default ui-corner-all" id="searcher" style="padding: 2px; font-size: 12px; width: 218.641px;" size="35">
```

**Comment by TheWitness** [comment]
I fixed this over the weekend.  lib/html_tree.php.

**Comment by bmfmancini** [comment]
That did it!

Thanks a lot!
