### ISSUE TITLE
New release tag for 1.2.11

### ISSUE THREAD

**Issue by ncopa** [Cacti/cacti#3358]
**Is your feature request related to a problem? Please describe.**

The latest release, 1.2.10 fails to install (#3313) it is fixed in git but it would be very helpful for downstream packagers to have a working release. 

**Describe the solution you'd like**

Create a 1.2.11 tag that successfully installs, so we can fix our alpine [stable branch](https://gitlab.alpinelinux.org/alpine/aports/commit/d257bf86303c111c0a6407903b162c596fb405de)

**Describe alternatives you've considered**
Another option is to backport the exact patches. An attempt was done but [failed](https://gitlab.alpinelinux.org/alpine/aports/issues/11312#note_74737). So a list of the exact patches to be backported would be a helpful alternative.

**Additional context**
related downstream issues (note that those are for edge branch, not stable):
https://gitlab.alpinelinux.org/alpine/aports/issues/11287
https://gitlab.alpinelinux.org/alpine/aports/issues/11312

**Comment by vegnuli** [comment]
hi! thanks for this request @ncopa .. i also added that i suspect that if stats template are not available in cacti, we could not install property any dependant plugin like this : https://github.com/Cacti/plugin_mikrotik/issues/41

**Comment by mckaygerhard** [comment]
pleeease! a good release! ¬_¬u

**Comment by TheWitness** [comment]
Please check the milestone schedule.  We will release the next release on or about 3/31.  Until then, if you are a package maintainer and concerned about the Cacti Stats device package, just cherry pick it and include in your distributions.

The MikroTik problem is a web server configuration issue, but we'll fix it to work around that configuration issue.

**Comment by netniV** [comment]
I thought I'd missed something here with a tag... Then I thought I was a time traveller, but now I realise that you're just ahead of schedule :)

**Comment by ncopa** [comment]
>  if you are a package maintainer and concerned about the Cacti Stats device package, just cherry pick it and include in your distributions.

Exactly what commit(s) is it?

**Comment by netniV** [comment]
Check out the source, then do a `git log <file>` on any file you want history for, it’ll tell you. You can also see it on the github website.

**Comment by ncopa** [comment]
> Check out the source, then do a `git log <file>` on any file you want history for, it’ll tell you. You can also see it on the github website.

Sorry. Maybe i'm stupid. I just package cacti for alpine. I have no idea exactly what file "Cacti Stats device package" is nor what the exact problem in 1.2.10 is. All I know is that someone claims that 1.2.10 is broken, and we pushed it to alpine stable branch due to various security issues. So I thought I'd ask the upstream devs who knows the code and the problem better than me.

 `git log --grep stats` gives me various commits but nothing that clearly stats "this fixes the stats package install problem introduced in 1.2.10".

@mckaygerhard maybe you can help me find the exact commit that fixes your problem? Otherwise we'll just wait for the 1.2.11 release and let cacti be broken for a while.

PS. `git log` is not as useful as you may think. For example this commit does not really tell me anything useful at all, without also reading what Issue #NNN is about:
```
    Fixing Issue #NNN
    
    * Turns out it was disabled by design.
    * Confirmed it works.
    * Additionally added the automation tables to the full sync.
    * Also, remove orphans is enabled by default now.

```
The only way to get anything useful out from the git history is by use the github web interface.

**Comment by netniV** [comment]
There are six packages in install/templates

**Comment by ncopa** [comment]
> There are six packages in install/templates

Thank you very much! The only commit in `install/templates` since `release/1.2.10` tag is 793d3520f8094ed225c39678d3df5ff23973dee9, so I'll cherry-pick that. I'm sorry that I was not able  to find that out by myself from the commit message "Fixing a few issues" and had to ask.

**Comment by ncopa** [comment]
The 793d3520f8094ed225c39678d3df5ff23973dee9 fails to apply cleanly and also needs c640cc1b86004294bce6dea426ebe558c5e4e32a.

However, those packages seems to be binaries:
```
File install/templates/Cacti_Stats.xml.gz: git binary diffs are not supported.
```

So I have to wait for the 1.2.11 release anyway.

Thanks for quick responses and thanks for continue maintaining opensource in spite of ungrateful and demanding users! It is appreciated even if it is seldom expressed.

**Comment by TheWitness** [comment]
```cmd
cd /var/www/html/cacti/cli
php -q install_package.php --filename=/path/to/tgz
```

**Comment by netniV** [comment]
You can download the binaries directly from the code tab of the GitHub repo. The current version is the fixed version.

**Comment by mckaygerhard** [comment]
i disagree.. @ncopa  .. we have many workload and the comits on github are not very explanatory and it is difficult for packers to work with such a mess.. of course cacti developers do it in a standard way.. but every linux distribution tries to put its files in order.. i don't see a description policy in the cacti commits comments respect the files and previous commits

also @TheWitness  the command `cd /var/www/html/cacti/cli
php -q install_package.php --filename=/path/to/gz` never ends, there's many hardcoded ini values in the "install_package.php" that cause to fails! as someone posted in https://github.com/Cacti/cacti/issues/3313#issuecomment-601508135

i downloaded most newer ones and seems same result as vegnuli posted!

**Comment by TheWitness** [comment]
We are just moving fast right now and we all have our day jobs too.  So before you release an update to your respective distribution, make sure you test things out.  We are not perfect, and having constructive criticism is better than ranting.  We will get the next release out soon enough.  The previous timeout issue has been resolved.  Thanks for that additional note.

**Comment by mckaygerhard** [comment]
added relevant commit;: https://github.com/Cacti/cacti/commit/75580b386e38d919e06d4062147c4d1e208770dd thanks fo a commit that at leas said the problem.. i'll wait the next release ! thanks.. and thanks @vegnuli too.. we also have diferences but i always test the releases.. 

> (no need to delete comments.. in any case mails always arrived and that are forever)
