### ISSUE TITLE
Timeout and logout issue for guest

### ISSUE THREAD

**Issue by arno-st** [Cacti/cacti#3360]
I have a monitoring station that use the guest account to view the thold page (or any other page)
But after some timeoute user are logged out, so how can I setup cacti to allow user to have unlimited page view.

Ensure under Console > Configuration > Settings > Authentication that this account is the selected guest account

Then go the graph_view.php, or another one, and just wait.
Timeout will occur and will log you out!

**Comment by TheWitness** [comment]
Fixed.  Pull the include/global_session.php from the 1.2.x branch.

**Comment by TheWitness** [comment]
There was one more change on this one.  All set now.
