### ISSUE TITLE
Cacti 1.2.9 Some devices on remote poller show Device[6978] not found. Please perform Full Sync!

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3361]
Hello Everyone

I  found that on 1.2.9 I added a new device to a remote poller today manually 
I saved the device and cacti showed the SNMP info all great 

the device status went to unknown which is normal I did a sync on the pollers and then it showed up status 

Now go back to the device and make a slight change to the name
Device[6978] not found. Please perform Full Sync!

Then another resync of the pollers needed to fix that 
Went to another device that had been there for a while if you just click save again cacti will come back showing device not found perform a full sync

Its something new for me as I am not used to this behavior is this by design?
Right now I have set my pollers to resync after 8 hours like this you would need shorter sync times to make sure new devices are available for graphing 

Thanks !

**Comment by TheWitness** [comment]
I think this is all fixed up in the 1.2.x branch.

**Comment by bmfmancini** [comment]
Ah man

Do you know which commit or file by chance I just upgraded from 1.2.7 to
1.2.9 don't wanna do another Maintenace window lol

**Comment by TheWitness** [comment]
I'll have to check.  For sure @cigamit would know.

**Comment by TheWitness** [comment]
Release coming later today.  Closing this.  Upgrade will do a full sync afterwards.  So, if this issue persists, open another ticket.
