### ISSUE TITLE
Aborted connection 99 to db: 'unconnected' user: 'unauthenticated' host: 'localhost' 

### ISSUE THREAD

**Issue by jackouille-ch** [Cacti/cacti#3362]
Hi,

I am running Cacti 1.2.10 on CentOS 7, PHP 7.3.16 and MariaDB 10.4.12

Isaw in /var/log/messages that this files is very big and each minute I receive the following log entries (looks like they are generated till at least Cacti 1.2.9):
Mar 8 03:41:01 cacti3 systemd: Created slice User Slice of root.
Mar 8 03:41:01 cacti3 systemd: Started Session 28399 of user root.
Mar 8 03:41:02 cacti3 mysqld: 2020-03-08 3:41:02 9975184 [Warning] Aborted connection 9975184 to db: 'unconnected' user: 'unauthen
ticated' host: 'localhost' (This connection closed normally without authentication)
Mar 8 03:41:03 cacti3 mysqld: 2020-03-08 3:41:03 9975217 [Warning] Aborted connection 9975217 to db: 'unconnected' user: 'unauthen
ticated' host: 'localhost' (This connection closed normally without authentication)
Mar 8 03:41:03 cacti3 mysqld: 2020-03-08 3:41:03 9975242 [Warning] Aborted connection 9975242 to db: 'unconnected' user: 'unauthen
ticated' host: 'localhost' (This connection closed normally without authentication)
Mar 8 03:41:03 cacti3 mysqld: 2020-03-08 3:41:03 9975245 [Warning] Aborted connection 9975245 to db: 'unconnected' user: 'unauthen
ticated' host: 'localhost' (This connection closed normally without authentication)
Mar 8 03:41:03 cacti3 mysqld: 2020-03-08 3:41:03 9975259 [Warning] Aborted connection 9975259 to db: 'unconnected' user: 'unauthen
ticated' host: 'localhost' (This connection closed normally without authentication)
Mar 8 03:41:03 cacti3 mysqld: 2020-03-08 3:41:03 9975280 [Warning] Aborted connection 9975280 to db: 'unconnected' user: 'unauthen
ticated' host: 'localhost' (This connection closed normally without authentication)
Mar 8 03:41:03 cacti3 mysqld: 2020-03-08 3:41:03 9975293 [Warning] Aborted connection 9975293 to db: 'unconnected' user: 'unauthen
ticated' host: 'localhost' (This connection closed normally without authentication)
Mar 8 03:41:03 cacti3 mysqld: 2020-03-08 3:41:03 9975296 [Warning] Aborted connection 9975296 to db: 'unconnected' user: 'unauthen
ticated' host: 'localhost' (This connection closed normally without authentication)
Mar 8 03:41:03 cacti3 mysqld: 2020-03-08 3:41:03 9975303 [Warning] Aborted connection 9975303 to db: 'unconnected' user: 'unauthen
ticated' host: 'localhost' (This connection closed normally without authentication)
Mar 8 03:41:03 cacti3 mysqld: 2020-03-08 3:41:03 9975307 [Warning] Aborted connection 9975307 to db: 'unconnected' user: 'unauthen
ticated' host: 'localhost' (This connection closed normally without authentication)
Mar 8 03:41:03 cacti3 mysqld: 2020-03-08 3:41:03 9975312 [Warning] Aborted connection 9975312 to db: 'unconnected' user: 'unauthen
ticated' host: 'localhost' (This connection closed normally without authentication)
Mar 8 03:41:03 cacti3 mysqld: 2020-03-08 3:41:03 9975324 [Warning] Aborted connection 9975324 to db: 'unconnected' user: 'unauthen
ticated' host: 'localhost' (This connection closed normally without authentication)
Mar 8 03:41:03 cacti3 mysqld: 2020-03-08 3:41:03 9975339 [Warning] Aborted connection 9975339 to db: 'unconnected' user: 'unauthen
ticated' host: 'localhost' (This connection closed normally without authentication)
Mar 8 03:41:03 cacti3 mysqld: 2020-03-08 3:41:03 9975363 [Warning] Aborted connection 9975363 to db: 'unconnected' user: 'unauthen
ticated' host: 'localhost' (This connection closed normally without authentication)
Mar 8 03:41:03 cacti3 mysqld: 2020-03-08 3:41:03 9975365 [Warning] Aborted connection 9975365 to db: 'unconnected' user: 'unauthen
ticated' host: 'localhost' (This connection closed normally without authentication)
Mar 8 03:41:03 cacti3 mysqld: 2020-03-08 3:41:03 9975372 [Warning] Aborted connection 9975372 to db: 'unconnected' user: 'unauthen
ticated' host: 'localhost' (This connection closed normally without authentication)
Mar 8 03:41:03 cacti3 mysqld: 2020-03-08 3:41:03 9975378 [Warning] Aborted connection 9975378 to db: 'unconnected' user: 'unauthen
ticated' host: 'localhost' (This connection closed normally without authentication)
Mar 8 03:41:03 cacti3 mysqld: 2020-03-08 3:41:03 9975379 [Warning] Aborted connection 9975379 to db: 'unconnected' user: 'unauthen
ticated' host: 'localhost' (This connection closed normally without authentication)
Mar 8 03:41:03 cacti3 mysqld: 2020-03-08 3:41:03 9975392 [Warning] Aborted connection 9975392 to db: 'unconnected' user: 'unauthen
ticated' host: 'localhost' (This connection closed normally without authentication)
Mar 8 03:41:03 cacti3 mysqld: 2020-03-08 3:41:03 9975400 [Warning] Aborted connection 9975400 to db: 'unconnected' user: 'unauthen
ticated' host: 'localhost' (This connection closed normally without authentication)
Mar 8 03:41:03 cacti3 mysqld: 2020-03-08 3:41:03 9975402 [Warning] Aborted connection 9975402 to db: 'unconnected' user: 'unauthen
ticated' host: 'localhost' (This connection closed normally without authentication)
Mar 8 03:41:03 cacti3 mysqld: 2020-03-08 3:41:03 9975403 [Warning] Aborted connection 9975403 to db: 'unconnected' user: 'unauthen
ticated' host: 'localhost' (This connection closed normally without authentication)
Mar 8 03:41:03 cacti3 mysqld: 2020-03-08 3:41:03 9975405 [Warning] Aborted connection 9975405 to db: 'unconnected' user: 'unauthen
ticated' host: 'localhost' (This connection closed normally without authentication)
Mar 8 03:41:03 cacti3 mysqld: 2020-03-08 3:41:03 9975413 [Warning] Aborted connection 9975413 to db: 'unconnected' user: 'unauthen
ticated' host: 'localhost' (This connection closed normally without authentication)
Mar 8 03:41:03 cacti3 mysqld: 2020-03-08 3:41:03 9975425 [Warning] Aborted connection 9975425 to db: 'unconnected' user: 'unauthen
ticated' host: 'localhost' (This connection closed normally without authentication)
Mar 8 03:41:03 cacti3 mysqld: 2020-03-08 3:41:03 9975428 [Warning] Aborted connection 9975428 to db: 'unconnected' user: 'unauthen
ticated' host: 'localhost' (This connection closed normally without authentication)
Mar 8 03:41:03 cacti3 mysqld: 2020-03-08 3:41:03 9975435 [Warning] Aborted connection 9975435 to db: 'unconnected' user: 'unauthen
ticated' host: 'localhost' (This connection closed normally without authentication)
Mar 8 03:41:03 cacti3 mysqld: 2020-03-08 3:41:03 9975446 [Warning] Aborted connection 9975446 to db: 'unconnected' user: 'unauthen
ticated' host: 'localhost' (This connection closed normally without authentication)
Mar 8 03:41:03 cacti3 mysqld: 2020-03-08 3:41:03 9975456 [Warning] Aborted connection 9975456 to db: 'unconnected' user: 'unauthen
ticated' host: 'localhost' (This connection closed normally without authentication)
Mar 8 03:41:03 cacti3 mysqld: 2020-03-08 3:41:03 9975463 [Warning] Aborted connection 9975463 to db: 'unconnected' user: 'unauthen
ticated' host: 'localhost' (This connection closed normally without authentication)
Mar 8 03:41:03 cacti3 mysqld: 2020-03-08 3:41:03 9975468 [Warning] Aborted connection 9975468 to db: 'unconnected' user: 'unauthen
ticated' host: 'localhost' (This connection closed normally without authentication)
Mar 8 03:41:03 cacti3 mysqld: 2020-03-08 3:41:03 9975488 [Warning] Aborted connection 9975488 to db: 'unconnected' user: 'unauthen
ticated' host: 'localhost' (This connection closed normally without authentication)
Mar 8 03:41:03 cacti3 mysqld: 2020-03-08 3:41:03 9975492 [Warning] Aborted connection 9975492 to db: 'unconnected' user: 'unauthen
ticated' host: 'localhost' (This connection closed normally without authentication)
Mar 8 03:41:04 cacti3 mysqld: 2020-03-08 3:41:04 9975502 [Warning] Aborted connection 9975502 to db: 'unconnected' user: 'unauthen
ticated' host: 'localhost' (This connection closed normally without authentication)
Mar 8 03:41:22 cacti3 systemd: Removed slice User Slice of root.

Any idea on how to avoid this kind of entries ?

**Comment by TheWitness** [comment]
Well, this is not a Cacti issue per se.  It's more of an authentication issue between Cacti and your database.  You should seek that out.  You should also check your Apache error_log for problems like syntax errors that are causing the connections to not close as expected.

You should be asking yourself what changed lately too.  Did you do a "yum upgrade"?  Are you using a non-standard PHP?  Did you recently update a plugin?

**Comment by jackouille-ch** [comment]
All updates, including Cacti are performed with YUM, so PHP version is either dowloaded as a package.
This server is dedicated to Cacti and no plugins were updated recently.
Checked on Apache logs and nothing relevant found in error_log nor access.
The strange this is that these errors only came during polling time, so each minute

**Comment by TheWitness** [comment]
Maybe your cacti user does not have access to the mysql.time_zone_name table?  Might be a problem from the package maintainers perspective.  Open a bug over at epel.

**Comment by jackouille-ch** [comment]
I try several enhancements within my.cnf and either a mysql_upgrade -u root -p
but still facing the same issue.
It only appears during Cacti polling.
I perform a search within files but no success, will continue my investigations
Regarding opening a bug at epel, do you have the URL to be used (I'm not so familiar with that kind of reports)?

**Comment by TheWitness** [comment]
Nope.

**Comment by TheWitness** [comment]
We will be upgrading today.  After upgrading Cacti and spine, if this issue persists, we will attempt to reproduce it using a matching environment.

**Comment by TheWitness** [comment]
No feedback
