### ISSUE TITLE
Changing data source index type from ifname to ifalias

### ISSUE THREAD

**Issue by csk06** [Cacti/cacti#3369]
Is it possible to change data source index types for all data sources ? I need to change it from ifname to ifalias.

I need it, because we are frequently replacing devices, so in that replacement ifalias remain same (as configuration we are using same description) but since its different device, ports are not remaining same. 

If there is a method for me to change it can you enlighten me ? 

Thanks

**Comment by TheWitness** [comment]
Just add it to the beginning of the XML sort field and reindex.  But note, if all ports don't have an ifAiias, and its not unique, you may not be happy.
