### ISSUE TITLE
The device OID value is missing.

### ISSUE THREAD

**Issue by ZhiXianZheng** [Cacti/cacti#3370]
This is the error picture.
Device normal in Cacti 0.8.8h use. 

![1](https://user-images.githubusercontent.com/6488212/77292793-f169aa80-6d1b-11ea-9fd3-74cbdd62b632.png)
![4](https://user-images.githubusercontent.com/6488212/77293063-8b315780-6d1c-11ea-9a06-73f11249ebd4.png)

Run snmpwalk commands in the cacti server.
![2](https://user-images.githubusercontent.com/6488212/77292890-270e9380-6d1c-11ea-8ea8-8e1b01f24393.png)
![3](https://user-images.githubusercontent.com/6488212/77292901-2d9d0b00-6d1c-11ea-94e3-30534e96ee35.png)

**Comment by TheWitness** [comment]
I think you don't have enough information here.  Looks like either there is an issue with SNMP in Cacti or something else.  I'm guessing SELInux.

**Comment by zhengzx0127** [comment]
> SELINUX=disabled

**Comment by TheWitness** [comment]
I would normally say, check the apache error log, but I know you are not running that.

**Comment by TheWitness** [comment]
After upgrading to the 1.2.11 release, report back using a new ticket if this issue persists.
