### ISSUE TITLE
Poller Recovery is slow poller_recovery.php

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3376]
Hey Guys 

I was testing a failure scenario in the  Main poller was taken down for a while 
came back restored the main poller the remote poller of course was in heartbeat status

it showed that is had 5M offline records  the log showed poller_output_table full 
but it appears the recovery script was not being initiated by cacti in the background even though the main database was restored 

I manually ran the poller_recovery.php script and it has been running for almost 1 hour seems to be running pretty slow my lab only has 130 devices on it so I could imaging if this was in a production system with tons of devices that it would take a huge amount of time 

I am not sure if this is typically slow as I have not had to run this manually before 

Thanks!

**Comment by TheWitness** [comment]
I just looked at the code.  I have to talk to Jimmy about his drinking habit.  Just kidding.  I've fixed it up.  Have an upload in a bit.

**Comment by TheWitness** [comment]
Not sure you want to test this, but it'll be way faster now.

**Comment by TheWitness** [comment]
My systems was able to do ~2000 in about 1.7 seconds.  So, 5M should take no more than a minute.

**Comment by bmfmancini** [comment]
wow that is an improvement  I tested the old script vs the new similar failure scenario and notice a big performance boost 

Thanks !

**Comment by TheWitness** [comment]
Okay, close if happy.
