### ISSUE TITLE
Weird LDAP Auth issue after upgrade from 1.1.37 to 1.2.10

### ISSUE THREAD

**Issue by jpobeda** [Cacti/cacti#3379]
I recently upgraded Cacti from 1.1.37 to 1.2.10 and it all went well.

```
CentOS7
PHP 5.4.16
MariaDB 5.5.64
Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_fcgid/2.3.9 PHP/5.4.16
```
```
LDAP Support	enabled
RCS Version	$Id$
Total Links	0/unlimited
API Version	3001
Vendor Name	OpenLDAP
Vendor Version	20444
SASL Support	Enabled

ldap.max_links	Unlimited	Unlimited
```
At some point Today, I tried to log in and was getting invalid user or password.
I turned DEBUG level to DEVEL and nothing really showed up on the logs other than

```
27/Mar/2020 11:07:28 - AUTH LOGIN: LDAP Login Failed for user 'MyUSER' from IP Address 'X.X.X.X'.
27/Mar/2020 11:07:08 - AUTH LOGIN: LDAP Login Failed for user 'MyUSER' from IP Address 'X.X.X.X'.
27/Mar/2020 11:05:15 - AUTH LOGIN: LDAP Login Failed for user 'MyUSER' from IP Address 'X.X.X.X'.
27/Mar/2020 10:54:37 - AUTH LOGIN: LDAP Login Failed for user 'MyUSER' from IP Address 'X.X.X.X'.
27/Mar/2020 10:53:40 - AUTH LOGIN: LDAP Login Failed for user 'MyUSER' from IP Address 'X.X.X.X'.
27/Mar/2020 10:53:02 - AUTH LOGIN: LDAP Login Failed for user 'MyUSER' from IP Address 'X.X.X.X'.
27/Mar/2020 10:52:11 - AUTH LOGIN: LDAP Login Failed for user 'AnotherUSER' from IP Address 'X.X.X.X'.
27/Mar/2020 10:52:00 - AUTH LOGIN: LDAP Login Failed for user 'AnotherUSER' from IP Address 'X.X.X.X'.
27/Mar/2020 10:50:20 - AUTH LOGIN: LDAP Login Failed for user 'AnotherUSER' from IP Address 'X.X.X.X'.
27/Mar/2020 10:49:24 - AUTH LOGIN: LDAP Login Failed for user 'AnotherUSER' from IP Address 'X.X.X.X'.
```
I couldn't find relevant errors or warning on cacti, httpd, php logs.

This is where the weirdness comes in

On the login screen, I changed REALM to local, clicked login (which of course failed), then I changed it back to LDAP and it worked. And so far, 3 other accounts have been able to reproduce it. That's when I realised it was a browser side thing.

I think it's some sort of cookie problem? When attempting from an 'incognito' browser session it works right away.

While I was trying to login I had a tcpdump capture running on the box and there were not a single attempt to connect to LDAP servers on port 389/636. Only when I did the trick above I was able to see traffic to LDAP Servers.

Is this something likely to happen after every upgrade?

I have a few more users to reproduce this if you'd like to investigate it.

**Comment by TheWitness** [comment]
Test again on the 1.2.x branch.  In all likelihood, it'll be tagged for release tomorrow.  It would be nice to know this is fixed there before tagging.  Just to let you know, this report already came in and there was a fix for it.

**Comment by jpobeda** [comment]
@TheWitness , cool, good to know. I did search for existing issues and only found https://github.com/Cacti/cacti/issues/3328.

Can you point me to the commit on the 1.2.x branch?

**Comment by TheWitness** [comment]
It was this, but there may have been a light change afterwards https://github.com/Cacti/cacti/pull/3322/files

**Comment by netniV** [comment]
I believe that this may be related to #3576
