### ISSUE TITLE
data_sources.php bug in template

### ISSUE THREAD

**Issue by a-vasilishin** [Cacti/cacti#3381]
After update from 1.2.8 to 1.2.10 I have a such bug:
![изображение](https://user-images.githubusercontent.com/3845145/77766398-44a76a00-7048-11ea-89fc-7565db2b102c.png)

**Comment by TheWitness** [comment]
What plugins do you have running?  I can not repeat this on a normal install.

**Comment by a-vasilishin** [comment]
![изображение](https://user-images.githubusercontent.com/3845145/77802837-6a526480-7084-11ea-8f5d-2ccdd8ce3d85.png)

**Comment by a-vasilishin** [comment]
I copied readable text from "view source"
 K M%d Attempts%d Column%d Days%d GBytes%d Hours%d Lines%d Megabytes%d Minute%d Minutes%d Months%d Weeks%d Years%d minutes%s %s%s GBytes%s Hours%s Minutes(Custom)(Edit)1 Attempt1 Column1 Day1 GByte1 Hour1 Megabyte1 Minute1 Year10,000 Data Source Items100,000 Data Source Items15,000 Data Source Items16x2 Hours2,000 Data Source Items200,000 Data Source Items25,000 Data Source Items2x4 Hours400,000 Data Source Items4x5,000 Data Source Items50,000 Data Source Items (Default)6 Hours8x<a href="%s">Create devices</a> for network<a href="%s">Create graphs</a> for your new devices<a href="%s">View</a> your new graphsA short textual representation of a month, three lettersAprA short textual representation of a month, three lettersAugA short textual representation of a month, three lettersDecA short textual representation of a month, three lettersFebA short textual representation of a month, three lettersJanA short textual representation of a month, three lettersJulA short textual representation of a month, three lettersJunA short textual representation of a month, three lettersMarA short textual representation of a month, three lettersMayA short textual representation of a month, three lettersNovA short textual representation of a month, three lettersOctA short textual representation of a month, three lettersSepA textual representation of a day, three lettersFriA textual representation of a day, three lettersMonA textual representation of a day, three lettersSatA textual representation of a day, three lettersSunA textual representation of a day, three lettersThuA textual representation of a day, three lettersTueA textual representation of a day, three lettersWedA very special thanks to %sTobi Oetiker%s, the creator of %sRRDtool%s and the very popular %sMRTG%s.ALLOWAbout CactiAccount OptionsActionActionsActiveAddAdd DeviceAdd Graph TemplateAdd to GroupAdditional OptionsAddress1Address2AdvancedAggregateAlignAlignmentAllAll ItemsAll TypesAllowAlphabeticAlternate NameAlways OffAlways OnAnyAppliedApply FilterAprilArabicArchiveAre You Sure?AttemptsAugustAuthenticationAuthorAutoAuto Language DetectionAutomationAvailabilityAverageAverage (ms)Base TimeBeginBottom -&gt; UpBranchesBulgarianButton: delete all table entriesPurgeButton: reset filter settingsClearButton: use filter settingsGoBypassedCSV ExportCache DirectoryCacti DevelopersCacti OSCacti System UtilitiesCacti VersionCacti is designed to be a complete graphing solution based on the RRDtool's framework. Its goal is to make a network administrator's job easier by taking care of all the necessary details necessary to create meaningful graphs.Cacti is licensed under the GNU GPL:CancelCenterChange Graph TemplateChange PasswordChange ProfileCheckChinese (China)Choose an actionCityClassicClearClear FiltersClear LogClear StatisticsClipboardCloseCollationCollection SettingsColorColor NameColorsColumnsCommentCommentsCommon OptionsCommunityCommunity:CompleteConcurrent ProcessesConfigurationConfiguration SettingsConfirm new passwordConsoleConsolidation FunctionContactContact:ContextContinueConvert to Graph TemplateCopyCountryCreateCurrentCurrent (ms)Current ValueCurrent passwordCustomCustom DataCutDailyDarkDataData CollectionData CollectorsData Input MethodData Input MethodsData SourceData Source TypeData SourcesDatabaseDateDay(s)Days of WeekDebugDebuggingDecemberDefaultDefault FontDefault OptionsDefault TreeDefault View ModeDeletableDeleteDelete AllDelete CheckDelete Graph Template(s)Delete Graph(s)DeletedDenyDescriptionDestination Branch:DetailedDetailsDeviceDevice NameDevice StatusDevice Template:Device TemplatesDevice:DevicesDisableDisable PluginDisabledDiscover NowDisplayDisplay OrderDocumentationDomainsDon't ShowDownDowngradeDownloadDuplicateDuplicate Graph Template(s)DurationDutchERRORERROR:EastEditEdit DeviceEdit PageEdit ProfileEmailEmail AddressEmail FrequencyEnableEnable PluginEnabledEncryptionEnd DateEngineEnglishEnter keywordEntriesEquationErrorError:ErrorsEspecially anyone who has taken the time to create an issue report, or otherwise help fix a Cacti related problems. Also to anyone who has contributed to supporting Cacti.EventsEveryEvery %d MinutesEvery DayEvery HourEvery MinuteEvery Other DayEvery WeekEvery dayExportExport ResultsExport TemplatesExport to a fileExternalExternal IDExternal LinkExternal LinksFailFailedFebruaryFieldField NameField OrderField TypeField ValueFileFile FoundFile not foundFilterFirstFont SizeFormatFoundFrenchFrequencyFridayFriendly NameFromFrom Email AddressFrom NameFull NameFull Name:FunctionGeneralGeneral InformationGeneral SettingsGermanGet HelpGet StartedGoGrant AccessGraphGraph ConfigurationGraph HeightGraph Items [edit: %s]Graph Items [new]Graph ManagementGraph SettingsGraph TemplateGraph TemplatesGraph TitleGraph TypeGraph WidthGraphsGreekGrid OptionsGroup DescriptionGroup NameGroupsGuest UserHeaderHeader TypeHeartbeatHebrewHex ValueHideHide Item DetailsHindiHomepageHorizontal RuleHostHost:HostnameHostname:Hour(s)IDIPIP AddressIdIdleImage FormatImportImport ResultsImport TemplateImport TemplatesImport/ExportIndexInheritInlineInput FieldInput TypeInstallInstall PluginInstalledIntervalInvalidInvalid User Name/Password Please RetypeIssueIssuesItalianItemItem ColorItem DetailsItemsJanuaryJapaneseJulyJuneJustifiedKeep Graph TypesKeep me signed inKindKoreanLanguageLanguage SupportLastLast %d DaysLast %d HoursLast %d MonthsLast %d WeeksLast %d YearsLast CheckLast DayLast EditedLast Half HourLast HourLast LoginLast ModifiedLast MonthLast RunLast SyncLast UpdateLast WeekLast YearLatitudeLeafLeftLicenseLightLinksList ModeList ViewLocalLocationLocation:LockedLog EntriesLog RetentionLog SettingsLogged in asLoggingLoginLogin NameLogin OptionsLogoutLogsLongitudeMD5Mail ServicesManagementManualMarchMatching GraphsMaxMax:MayMemberMembersMembershipMethodMinMin:Minimum LengthMinute(s)ModeModernMondayMonoMonthlyMove DownMove UpMultipleN/ANameNaturalNetworkNetwork NameNetworksNeverNewNew DeviceNew GraphsNew GroupNew ProfileNew ReportNew SiteNew WindowNew passwordNewest FirstNextNext RunNoNo %s FoundNo Devices FoundNo Graphs FoundNo Items FoundNo Pages FoundNo Reports FoundNo UserNo Users FoundNo associated graph templates.No file selectedNo issues foundNoneNone SelectedNormalNormal UserNorthNot ApplicableNot FoundNot InstalledNot Logged InNot SelectedNote, we could not process all your actions.  Details are below.NotesNotificationNotification EmailNotification From NameNotification SettingsNotificationsNovemberNumericOSObjectsOctoberOfflineOkOldest FirstOnce a DayOnlineOpen in new tabOperationOperation successfulOperatorOptionalOrderOtherOther SettingsOwnerPHP InfoPHP InformationPHP Mail() FunctionPHP Module InformationPHP OSPHP VersionPagePage RefreshPart of AggregatePassedPasswordPassword successfully changed.PastePathsPatternPausePerformancePermission DeniedPermissionsPingPlace Graph(s) on TreePlace on a Tree (%s)Please confirmPlease press 'Return' to continue.Please see the official %sCacti website%s for information, support, and updates.Plugin ManagementPlugin NamePluginsPolishPoll TimePollerPoller IntervalPollersPortPortuguesePortuguese (Brazil)Postal/Zip CodePrefixPresetsPreviewPreview ModePreviousPrevious DayPrevious MonthPrevious WeekPrevious YearProfileProfile NameProfilesProgressPublishPublishedPurgeQuickRead OnlyReapply Suggested NamesReason:ReceiverReceiversRecommendedRecommended ValueRecordsRecoveryReferralsRefreshRemove from GroupRenameReportReport AddReport DeleteReport EditReport IntervalReport TitleReport a bugReport:ReportingReportsRequiredRequiresRescanResetReset fields to defaultsReset filtersResize Selected Graph Template(s)Restrict AccessResultResultsRetriesReturnRevoke AccessRightRowsRule NameRunningRussianSMTPSMTP HostnameSMTP PasswordSMTP PortSMTP SecuritySMTP TimeoutSMTP UsernameSNMPSNMP Password (v3)SNMP Username (v3)SNMP VersionSNMP Version:SSLSaturdaySaveScheduleSchedule TypeScriptScript ServerScript:ScriptsSearchSearch BaseSearch FilterSearch PatternSecondSecuritySelect AllSelect File(s)Select TemplateSelect a FileSelectedSend NowSend ReportSend a Test EmailSending Message...SendmailSendmail OptionsSendmail PathSeptemberSequenceServerServersSessionSet DefaultSet/Refresh FiltersSettingsSeverityShowShow AllShow Graph TitleShow Item DetailsSimpleSiteSite InformationSite NameSite:SitesSizeSkipSome Actions failedSource NameSource TypeSouthSpanishSpecial UsersSpikesStandard DeviationStart DateStartedStateStatisticsStatsStatusStepStepsStopStyleSubjectSuccessSuccess!Suggested ValueSummarySundaySunriseSupportSwedishSystemSystem UtilitiesTLSTable SettingsTablesTake OwnershipTechnical SupportTemplateTemplate NameTemplate SetupTemplate TitleTemplatesTest ConnectionTest EmailTextText FormatThanksThe color to use for the legend.The encryption method to use for the Email.The label vertically printed to the left of the graph.The users of CactiThemeTheme SettingsThirdThis MonthThis WeekThis YearThis is the Email address that the Email will appear from.This is the actual name that the Email will appear from.This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.ThreadsThumbnail HeightThumbnail WidthThumbnailsThursdayTimeTimeoutTimestampTitleTitle Font SizeTitle FormatToTop -&gt; DownTotalTotal: %sTreeTree ViewTreesTroubleshootingTuesdayTurkishTurn Off Graph Debug ModeTurn On Graph Debug ModeTypeUnavailableUninstallUninstall PluginUnknownUnknown FieldUnlimitedUpUpdateUpdate ProfileUpgradeUptimeUserUser CommunityUser GroupsUser LanguageUser LevelUser LoginUser ManagementUser NameUser PermissionsUser SettingsUser:UsernameUsername already exists.Username:UsersUtilitiesValidation ErrorValueVariableVersionVersion %sVertical LabelVietnameseViewView LogView PageVisualWARNING:WarningWarningsWednesdayWeek(s)WeeklyWestWhich mail service to use in order to send mailWindowWord WrapWritableXML PathYOU DO NOT HAVE RIGHTS FOR TREE VIEWYear(s)YesYou are now logged into <a href="%s"><b>Cacti</b></a>. You can follow these basic steps to get started.ZoomZoom InZoom Out[None][edit: %s][fail][new][success]begins withcentercontainsdaysdefaultdoes not begin withdoes not containdoes not end withdropdown actionArchivedropdown actionDeletedropdown actionPublisheMailends withfilter resetClearfilter: resetClearfilter: useGoguesthoursis emptyis greater thanis less thanis not emptyis not equal toleftmatchesminutesnamenoneordering of tree itemsinheritordering of tree itemsmanualordering of tree itemsnumericrename %s to %srightrule_nameProject-Id-Version: Cacti Russian Language File
Report-Msgid-Bugs-To: developers@cacti.net
POT-Creation-Date: 2020-02-02 11:17-0500
PO-Revision-Date: 2019-03-10 13:47-0400
Last-Translator: Patrick Rademaker
Language-Team: KPbIC <cacti>
Language: ru
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
Plural-Forms: nplurals=3; plural=(n%10==1 &amp;&amp; n%100!=11 ? 0 : n%10&gt;=2 &amp;&amp; n%10&lt;=4 &amp;&amp; (n%100&lt;10 || n%100&gt;=20) ? 1 : 2);
X-Generator: Poedit 2.2.1
 K М%d попыток%d Колонка%d Дня(ей)%d Гбайт%d Часа(ов)%d Линий%d Мегабайт%d Минута%d Минут%d Месяца%d Недели%d Года%d минут%s %s%s Гбайт%s Часов %s Минут(Özel)(Редактировать)1 Попытка1 колонка1 День1 Гбайт1 Час1 Мегабайт1 минута1 Год10,000 Элементов источников данных100,000 Элементов источников данных15,000 Элементов источников данных16x2 Часа2,000 Элементов источников данных200,000 Элементов источников данных25,000 Элементов источников данных2x4 Часа400,000 Элементов источников данных4x5,000 Элементов источников данных50,000 Элементов источников данных6 Часов8x<a href="%s">Создайте устройства</a> для сети<a href="%s">Создайте график</a> для вашего нового устройства<a href="%s">Посмотрите</a> ваши новые графикиАпрАвгДекФевЯнвИюлИюнМарМайНояОктСенПтПнСбВсЧтВтСрОтдельная благодарность %sTobi Oetiker%s, создателю %sRRDtool%s и очень популярной библиотеки %sMRTG%s.РазрешитьО CactiАккаунт ОпцииДействиеДействияАктивныйДобавитьДобавить устройствоДобавить Шаблон ГрафикаДобавить в группуДополнительные опцииАдрес1Адрес2ДополнительноСовокупныйВыравниваниеВыравниваниеВсеВсе элементыВсе типыРазрешитьВ алфавитном порядкеДругое ИмяВсегда ВыклВсегда ВклЛюбойПримененоПрименить фильтрАпрельАрабскийАрхивВы уверены?ПопытокАвгустАутентификацияАвторАвтоАвтоматическое Определение ЯзыкаАвтоматизацияДоступностьСреднеСрейдний (мс)Базовое времяНачалоНиз -&gt; ВерхФилиалБолгарскийУдалитьОчиститьПерейтиБез обработкиCSV экспортДиректория кэшаРазработчики CactiОСУтилиты CactiВерсия CactiCacti - это полнофункциональное графическое решение на основе RRDtool Его цель - упростить работу администратора сети, забота о всех необходимых деталях, И графикиCacti лицензирован под GNU GPL:ОтменаЦентрИзменение Шаблона ГрафикаИзменить парольИзменить профильПроверитьКитайский (Китай)Выберите действиеГородКлассическийОчиститьОчистить фильтрыОчистить журналОчистить СтатистикуБуфер обменаЗакрытьСравнениеПараметры коллекцийЦветНазвание ЦветаЦветаКолонкиКомментарийКомментарииОбщие ПараметрыСообществоСообщество:ГотовоКоличество Конкурирующих процессовКонфигурацияНастройкиПодтвердите новый парольКонсольФункция КонсолидацииКонтактКонтактная информация:КонтекстПродолжитьПреобразовать в Шаблон ГрафикаКопироватьСтранаСоздатьТекущийТекущий (мс)Текущее значениеТекущий парольПользовательскийПользовательские данныеВырезатьЕжедневноТемныйДанныеКоллекции ДанныхСистемы &amp;Сбора ДанныхМетод Ввода ДанныхМетод Ввода ДанныхИсточник ДанныхТип данных источникаИсточники ДанныхБаза ДанныхДатаДень(дней)Дни неделиОтладкаОтладкаДекабрьСтандартноШрифт по умолчаниюНастройки по умолчаниюДерево по умолчаниюРежим просмотра по умолчаниюУдаляемыйУдалитьУдалить всеУбрать проверкуУдалить шаблоны графиковУдалить график(и)УдаленоОтклонитьОписаниеВетка назначенияДетализированныйДеталиУстройствоИмя устройстваСтатус устройстваШаблон Устройства:Шаблон УстройстваУстройство:УстройстваВыключитьОтключить плагинВыключенОткрыть сейчасПоказатьСортировать поДокументацияДоменыНе показыватьВнизПонижениеСкачатьДублироватьПродублировать шаблоны графиковПродолжительностьГолландскийОШИБКАОШИБКА:ВостокРедактироватьРедактировать устройствоРедактировать страницуРедактировать профильEmailАдрес электронной почтыЧастота EmailВключитьВключить плагинВключеноШифрованиеДата окончанияДвигательАнглийскийВведите ключевое словоЗаписиУравнениеОшибкаОшибка:ОшибкиОсобенно тем, кто нашел время, чтобы создать отчет о проблеме, или как-то иначе помог исправить проблемы, связанные с Кактусом. Также всем, кто внес вклад в поддержку Кактуса.СобытияКаждыйКаждые %d МинутыКаждый деньКаждый часКаждую минутуЧерез деньКаждую неделюКаждый деньЭкспортЭкспортировать результатыЭкспорт ШаблоновЭкспорт в файлВнешнийВнешний IDВнешняя ссылкаВнешние ссылкиНеудачаОшибкаФевральПолеИмя поляПорядок поляТип поляЗначение поляФайлФайл НайденФайл не найденФильтрПервыйРазмер шрифтаФорматНайденоФранцузскийЧастотаПятницаДружественное имяОтEmail адрес отправителяОт когоПолное ИмяПолное имя:ФункцияОбщиеОсновная ИнформацияОсновые НастройкиНемецкийПолучить помощьНачатьВыполнитьПредоставить доступГрафикНастройки графикаВысота графикаГрафики [редактировать %s]Графики [новый]Управление графикамиСвойства графиковШаблон ГрафикаШаблоны ГрафиковНазвание ГрафикаТип диаграммыШирина графикаГрафикиГреческийПараметры сеткиОписание группыИмя группыГруппыГостьЗаголовокТип заголовкаПульсацияИвритШестнадцатеричное значениеСкрытьСкрыть подробностиХиндиГлавная страницаГоризонтальная линияХостХостинг:Имя хостаИмя хоста : Час(ов)ИДIPIP адресIdНеактивноФормат ИзображенияИмпортИмпорт РезультатовИмпорт шаблонаИмпорт ШаблоновИмпорт/ЭкспортИндексУнаследоватьВ очередиПоле ВводаТип вводаУстановитьУстановить плагинУстановленноИнтервалНедействительныйНе верный логин или пароль, попробуйте ещё разВопросВопросыИтальянскийПунктЦвет элементаДетали элементаЭлементыЯнварь日本語ИюльИюньОправданоСохранять типы графиковОставаться в сетиВидКорейскийЯзыкПоддерфиваемые ЯзыкиПоследнийПоследние %d Дня(ей)Последние %d ЧасовПоследние %d Месяца(ев)Последние %d Недели(ь)Последние %d ГодаПоследняя проверкаПоследние ДеньПоследнее изменениеПоследние 30 МинутПоследний ЧасПоследний ВходПоследнее изменениеПоследний МесяцПоследнее обновлениеПоследняя синхронизацияПоследнее обновлениеПоследняя НеделяПоследний ГодШиротаЛистЛевоЛицензионное соглашениеСветлыйСсылкиРежим спискаСписокЛокальныйМестоположениеМестоположение:ЗаблокированоЗаписи в журналеХранение журналаНастройка РегистрацииВошел какРегистрацияВходЛогинОпции авторизацииВыходЖурналыДолготаMD5Почтовые службыУправлениеВручнуюМартСопоставление графиковМаксМакс:МайУчастникУчастникиЧленствоМетодМинМин:Минимальная длинаМинут(а)РежимСовременныйПонедельникМоноЕжемесячноПереместить внизДвижение вверхМножественныйН/ДИмяНатуральныйСетьИмя сетиСетиНикогдаНовыйНовое устройствоНовый графикНовая группаНовый профильНовая ЖалобаНовый сайтНовое окноНовый парольНовые СначалаСледующаяСледующий запускНет%s не найденоУстройства не найденыГрафики не найденыНичего не найденоСтраницы не найденыОтчёты не найденыНет пользователяПользователей не найденоНет ассоциированых шаблонов графиковФайл не выбранВыпуски не найденыНетНичего не выбраноНормальныйОбычный пользовательСеверНепригодныйНе найденоНе УстановленноНе авторизованНе выбраноОбратите внимание: мы не смогли обработать все ваши действия. Подробности ниже.ЗаметкиУведомлениеУведомление по электронной почтеУведомление пользователя от имениНастройки уведомленийУведомленияНоябрьЧисловойОСОбъектыОктябрьНе в сетиОкСначала старыеРаз в суткиВ сетиОткрыть в новой вкладкеОперацияОперация выполнена успешноОператорНеобязательныйЗаказДругоеДругие настройкиВладелецИнформация по PHPИнформация PHPPHP Mail() ФункцияИнформация о модуле PHPОС PHPВерсия PHPСтраницаОбновить страницуЧасть совокупностиПройденоПарольПароль успешно изменен.ВставитьПутьШаблонПаузаПроизводительностьДоступ запрещёнРазрешенияПингПоместить график(и) на деревоПоместить в дерево (%s)Пожалуйста, подтвердитеПожалуйста нажмите 'Вернуть' для продолженияПожалуйста посетите оффициальный сайт %sCacti website%s, там вы найдёте необходимую информацию, поддержку, и оповещения об обновленияхУправление ПлагинамиНазвание системной вставкиПлагиныПольскийВремя ОпросаРегистраторЧастота ОпросаРегистраторыПортПортугальскийПортугальский (Бразилия)ИндексПрефиксПредустановкиПредпросмотрРежим предварительного просмотраПредыдущаяПредыдущий ДеньПредыдущий МесяцПредыдущая НеделяПредыдущий ГодПрофильИмя профиляПрофилиПрогрессОпубликоватьОпубликованоУдалитьQuick(Быстро)Только чтениеПрименить Предлагаемые ИменаПричина:ПолучательПолучателиРекомендуемыеРекомендуемое значениеЗаписиВосстанавливаетсяРефералыОбновитьУдалить из группыПереименоватьОтчетДобавить отчётУдалить отчётИзменить отчётИнтервал отчетаНазвание отчетаСообщить об ошибкеОтчёт:ОтчётыОтчетыОбязательноЗависимостиПовторное сканированиеСбросСбросить поля по умолчаниюСбросить фильтрыИзменить размер выбранных шаблоновОграничение доступаРезультатРезультатыПопыткиВернутьОтозвать доступПравоСтрокИмя правилаВ процессеРусскийSMTPSMTP HostnameSMTP ПарольSMTP портSMTP БезопасностьSMTP таймаутSMTP Имя пользователяSNMPSNMP Пароль (v3)SNMP Имя Пользователя (v3)Версия SNMPВерсия SNMP:SSLСуббота Сохранить РасписаниеТип РасписанияСкриптСервер СкриптовСкрипт:СкриптыНайтиБаза поискаФильтр поискаОбразецСекундаБезопасностьВыбрать ВсеВыберите Файл(ы)Выбрать шаблонВыбрать файлВыбраноОтправить сейчасОтправить отчётОтправить тестовое письмоОтправка сообщения...SendmailSendmail ОпцииSendmail ПутьСентябрь*Sequence* (секвенция)СерверСерверыСессияУстановить по умолчаниюУстановить/Обновить фильтрыНастройкиВажностьПоказатьПоказать всеПоказать название графикаПоказать подробностиПростойУзелДанные УзлаИмя УзлаУзел:УзлыРазмерПропуститьНе удалось выполнить некоторые действияИмя источникаТип источникаЮгИспанскийСпециальный пользовательЗубцыСтандартное отклонениеДата началаЗапущеноОбластьСтатистикаСтатистикаСтатусШагШагиСтопСтильТемаВыполненноУспешно!Рекомендуемое значениеРезюмеВоскресеньеВосходПоддержкаШведскийСистемаСистемные УтилитыTLSНастройки таблицыТаблицыСтать владельцемТехническая ПоддержкаШаблонИмя ШаблонаНастройка ШаблонаНазвание шаблонаШаблоныТест подключенияТестовый emailТекстФормат ТекстаБлагодарностиЦвет используемый для легендыМетод шифрования для EmailВертикальная метка пишется слева от графикаПользователи CactiТемаНастройки темыТретийЭтот месяцНа этой неделеВ этом годуЭто адрес электронной почты, который будет отображаться в письме.Это фактическое имя, которое будет отображаться в сообщении электронной почты.Эта программа распространяется в надежде, что она будет полезна, но БЕЗ КАКИХ-ЛИБО ГАРАНТИЙ; Даже без подразумеваемых гарантий КОММЕРЧЕСКОЙ ЦЕННОСТИ или ПРИГОДНОСТИ ДЛЯ ОПРЕДЕЛЕННОЙ ЦЕЛИ. Для получения дополнительной информации см. GNU General Public License.Это приложение является свободным программным обеспечением; Вы можете распространять его и/или изменять в соответствии с условиями GNU General Public License, опубликованной Free Software Foundation; Либо 2ой версии лицензии (по вашему выбору), любой более поздней версии.ТемыВысота миниатюрыШирина миниатюрМиниатюрыЧетвергВремяПаузаОтметкаНазваниеРазмер шрифта заголовкаФормат заголовкаДоВерх -&gt; НизВсегоВсего: %sДеревоВ виде дереваДеревьяУстранение ошибокВторникТурецкийОтключить режим отладки для графиковВключить режим отладки для графиковТипНедоступноУдалитьУдалить плагинНеизвестноНеизвестное ПолеНеограниченноВверхОбновитьОбновить профильОбновитьАптаймПользовательСообщество пользователейГруппы пользователейЯзык пользователяУровень пользователяАутентификацияУправление ПользователямиИмя ПользователяПользовательские разрешенияНастройкиПользователь:Имя ПользователяИмя пользователя уже существует.Имя Пользователя:ПользователиУтилитыОшибка проверкиЗначениеПеременнаяВерсияВерсия %sВертикальная МеткаВьетнамскийВидПосмотреть логПросмотр страницыВизуальноВНИМАНИЕ:ПредупреждениеПредупрежденияСредаНедельЕженедельноЗападКакую почтовую службу использовать для отправки почтыОкноПеренос СтрокЗаписиПуть к XMLУ ВАС НЕДОСТАТОЧНО ПРАВ ДЛЯ ПРОСМОТРА ДЕРЕВАГод (лет)ДаВы вошли в <a href="%s"><b>Cacti</b></a>. Вы можете проделать эти простые шаги для начала.УвеличитьПриблизитьУменьшить[Нет][редакция: %s[ошибка][новый][выполненно]начинается спо центрусодержитднейпо умолчаниюне начинается сне содержитне заканчивается наАрхивУдалитьОпубликоватьEmailзаканчивается наОчиститьОчиститьПерейтигостьчасовпустоебольше, чемменьше, чемне пустоене равнослевасовпадаетминутимянетунаследоватьвручнуючисловойпереименовать %s в %sсправаrule_name					</cacti></p�����up�����zp��></g��></td>
					<td>

**Comment by a-vasilishin** [comment]
I just installed gettext  and run script ./locales/build_gettext.sh. Now I have russian interface and no bugs :)

**Comment by TheWitness** [comment]
Hopefully the quality is good.  If not, update the Russian po file and submit as a pull request
