### ISSUE TITLE
cacti 1.2.2 - php running into memory limits because poller_push_reindex_data_to_poller() tries to process too many DB entries

### ISSUE THREAD

**Issue by bernisys** [Cacti/cacti#3383]
We ran into a situation where a poller accumulated a huge amount of entries (~38 million data points in the end) in poller_output / poller_output_boost. Recovery started, but could not be completed, because as i found out the function "poller_push_reindex_data_to_main" was apparently trying to load a huge chunk of data from the poller's local DB, which lead to a crash in that function due to a memory shortage, it could not allocate as much as 7 bytes, according to the error-text.

PHP mem settings is currently 1GB, but i tried also with values up to 3GB without success.

After naively commenting out that function in the recovery script, at least the collected data was synced properly again and the pollers got out of the "Heartbeat" state.

IMHO it would be better to sync the reindex data back in smaller chunks, like looping thru the devices, or looping thru the table, procesing a limited number of rows for each step.

if needed, i can send you a dump of all DBs and you can try to reproduce the situation - should be doable by just calling the recovery script on a remote poller with a high amount of data in the snmp cache table. The recovery script will most likely exit with an "out of mem" error.

Our systems are all running on RHEL 7.4 - 7.6, using the rather old php 5.4.16 that comes with the distribution.

Please contact me if you need any further information!

**Comment by TheWitness** [comment]
Please pull the poller_recovery.php from the 1.2.x branch.  There has been a major update there.  Report back.

**Comment by TheWitness** [comment]
You might also want to pull lob/boost.php and poller_boost.php from 1.2.x too.

**Comment by TheWitness** [comment]
You might want to simply upgrade as there have been some functional improvements and new functions in lib/poller.php.

**Comment by bernisys** [comment]
First of all, thanks for the hint and the quick reply! Do you think this will work with an older MySQL version? I saw that a newer version is now explicitly requested while upgrading cacti, so currently we cannot go higher than Cacti 1.2.4 at the moment...

Our current version is mysql  Ver 15.1 Distrib 5.5.60-MariaDB (comes with RHEL ... yes i know, we should update, but we're stuck at the moment with a vendor package...)

**Comment by TheWitness** [comment]
MariaDB 5.5 is fine.  It's a bit old, but I run Cacti on MariaDB 5.5 just fine.  You simply get better performance on MariaDB 10.x.  This is especially true if you are using Flash or SSD's.

**Comment by bernisys** [comment]
Ok, thanks, then i will try .. there is just one thing, when we were trying to upgrade, in the step from 1.2.4 to 1.2.5 the DB update script uses this command:
MariaDB [cacti]> ALTER TABLE poller_output_realtime DROP PRIMARY KEY, ADD PRIMARY KEY (local_data_id, rrd_name, time, poller_id);
which produces:
ERROR 1709 (HY000): Index column size too large. The maximum column size is 767 bytes.
because it is using UTF-8 tables and the resulting hashed string sizes grow too large - this is as far as i understood (was reading some bugreports) hardcoded in Mariadb and is resolved in a later version only.

But i think in our environment it is quite unlikely that we use anything else than standard latin1 characters, so maybe it is safe to convert the content and continue on non-utf8.

Any suggestions from your side? (i know it's getting a bit off-.topic from the original bug-report now...)

**Comment by netniV** [comment]
The issue of the index too large has been resolved on a number of trackers here, so if you search through you'll find the required changes to both the mysql configuration and the tables.
