### ISSUE TITLE
How many output fields you can have in Cacti 1.2.10?

### ISSUE THREAD

**Issue by frankfer01** [Cacti/cacti#3384]
Hi, 
I'm using an script that return about 65 output fields. When I create a graph using some of this outputs, I only get data from the first 41.  Form 41-60(output fields, created in Data Imput Methods) return NaN. The question is, there are limitations quantities of output fields that can be use in the 1.2.10 version?. Actually works well in the version 0.8.8b. of cacti 

This is the output of script:

perl /home/cacti/Nodes/Huawei/Scripts/MSC_CPU 'STGO_vMSC01_CPU' 
WCCU_1031:9 WCCU_1030:9 WCCU_1029:10 WCCU_1028:10 WCCU_1027:9 WCCU_1026:9 WCCU_1025:10 WCCU_1024:10 WCCU_1023:9 WCCU_1022:8 WCCU_1021:10 WCCU_1020:10 WCCU_1019:9 WCCU_1018:9 WCCU_1017:9 WCCU_1016:9 WCCU_1015:9 WCCU_1014:9 WCCU_1013:10 WCCU_1012:9 WCCU_1011:9 WCCU_1010:9 WCCU_1009:9 WCCU_1008:9 WCCU_1007:9 WCCU_1006:10 WCCU_1005:8 WCCU_1004:10 WCCU_1003:9 WCCU_1002:9 WCCU_1001:10 WCCU_1000:9 WBSG_415:10 WBSG_414:14 WBSG_413:10 WBSG_412:10 WBSG_411:9 WBSG_410:14 WBSG_409:9 WBSG_408:10 WBSG_407:9 WBSG_406:9 WBSG_405:10 WBSG_404:11 WBSG_403:11 WBSG_402:11 WBSG_401:9 WBSG_400:10 WVDB_211:13 WVDB_210:12 WVDB_209:13 WVDB_208:13 WVDB_207:12 WVDB_206:12 WVDB_205:13 WVDB_204:13 WVDB_203:12 WVDB_202:12 WVDB_201:13 WVDB_200:13 WCDB_101:6 WCDB_100:7 WIFM_3:6 WIFM_2:9 WIFM_1:10

I can graphs the outputs from WCCU_1031 to WBSG_406 and got the correct data, but from  WBSG_405, I got NaN.

![image](https://user-images.githubusercontent.com/55502569/77795416-4115e200-704c-11ea-9e9c-3c15b5db2956.png)

Using cacti 0.8.8b works well:

![image](https://user-images.githubusercontent.com/55502569/77795550-81756000-704c-11ea-88f2-082ad5e36499.png)

**Comment by TheWitness** [comment]
What's the string length on that.  The output columns on the poller_output and poller_output_boost are limited to 512 bytes.  You may need to widen them.  So, not a bug.

**Comment by frankfer01** [comment]
I changed and now it's working. 

Thanks so much.

**Comment by TheWitness** [comment]
No problem
