### ISSUE TITLE
https://docs.cacti.net registration & password reset failing

### ISSUE THREAD

**Issue by milegrin** [Cacti/cacti#3389]
**Describe the bug**
Warning: preg_replace(): The /e modifier is no longer supported, use preg_replace_callback instead in /var/data/www/docs.cacti.net/inc/mail.php on line 255
Repeated error displayed

**To Reproduce**
1. Goto https://docs.cacti.net/start?do=register or https://docs.cacti.net/start?do=resendpwd
2. Trying to register gives a memory error.  Numerous attempts will result in blank registration email
   Trying to retireve unknown password gives the error :
3)   Warning: preg_replace(): The /e modifier is no longer supported, use preg_replace_callback instead in /var/data/www/docs.cacti.net/inc/mail.php on line 255

**Expected behavior**
1) Registration email received with new password instead of blank email.
2) New password email received - nothing received.

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - Browser Firefox & Chrome
 - Version N/A Wiki site

**Comment by TheWitness** [comment]
@cigamit, can you fix this one?

**Comment by netniV** [comment]
We do not accept registrations on that site at this time.
