### ISSUE TITLE
Cacti 1.0.3 - thumbnail view/mode is not working

### ISSUE THREAD

**Issue by ndhami23** [Cacti/cacti#339]
Hi Everyone,

I am facing some issue with thumbnail view/mode in Cacti 1.0.3. Every time I logged out and login in again, I am not getting my saved thumbnails view instead it goes to default non thumbnail view. Any idea how can i fix this?

**Comment by cigamit** [comment]
This issue has already been resolved, update your lib/html_tree.php from the development branch.

**Comment by ndhami23** [comment]
Thanks a lot @cigamit.. It's working now!
