### ISSUE TITLE
Incorrect breadcrumb bar if current tab is not "Graphs"

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#3390]
**Describe the bug**
Incorrect navigation bar if current tab is not "Graphs", including "Console"

**To Reproduce**
1. Switch theme to show "navigation bar(bread crumb)", e.g. Dark, Modern
2. Click "Graphs" tab 
3. Click any tree node to show some graphs
4. Click other "Non-Graphs" tab, e.g. "Console"
5. Check "navigation bar" , see error.

**Expected behavior**
Navigation bar should keep consistent with current web page.

**Screenshots**
![image](https://user-images.githubusercontent.com/17589018/78041543-6899e100-73a3-11ea-82d5-92a6794f18f1.png)

**Comment by TheWitness** [comment]
That is some sort of recent regression I think.

**Comment by TheWitness** [comment]
Should be resolved.  Please test and provide feedback.

**Comment by ddb4github** [comment]
Test pass
