### ISSUE TITLE
Customize filters and host list in Console->Devices page

### ISSUE THREAD

**Issue by YongBoLiu** [Cacti/cacti#3392]
**Is your feature request related to a problem? Please describe.**
We need add a special filter on Console->Device page, such as cluster to filter the hosts. I have to change the host.php code. And when the cacti upgrade, the filters missing. 

**Describe the solution you'd like**
Add some hooks to show the customize filters from plugins, and add hook to some customer columns in the host list.

The hooks may be as below,
api_plugin_hook('device_filter_start');
api_plugin_hook_function('device_display_text', $display_text);
api_plugin_hook_function('device_table_start', $hosts);

**Describe alternatives you've considered**

**Additional context**

**Comment by TheWitness** [comment]
@YongBoLiu, please create a pull request.  Thanks.

**Comment by netniV** [comment]
Any request for new hooks should be considered an enhancement applied to 1.3.

**Comment by YongBoLiu** [comment]
I created a PR #3396 for 1.2.x , please help to review it. Thanks. It works well for my plugin.
