### ISSUE TITLE
1.2.9 Remote pollers sync too often ignoring setting

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3393]
Hey everyone 

On 1.2.9 I have 1 main poller and 2 remote I had set the poller sync  interveral to be 8 hours but it seems to be stuck at the default 2 hours 

2020/04/01 14:50:23 - POLLER: Poller[Main Poller] STATS: Poller ID 8 fully Replicated
2020/04/01 14:49:18 - POLLER: Poller[Main Poller] STATS: Poller ID 7 fully Replicated
2020/04/01 12:50:00 - POLLER: Poller[Main Poller] STATS: Poller ID 8 fully Replicated
2020/04/01 12:49:01 - POLLER: Poller[Main Poller] STATS: Poller ID 7 fully Replicated
2020/04/01 10:50:01 - POLLER: Poller[Main Poller] STATS: Poller ID 8 fully Replicated
2020/04/01 10:49:05 - POLLER: Poller[Main Poller] STATS: Poller ID 7 fully Replicated
2020/04/01 08:50:03 - POLLER: Poller[Main Poller] STATS: Poller ID 8 fully Replicated
2020/04/01 08:49:04 - POLLER: Poller[Main Poller] STATS: Poller ID 7 fully Replicated
2020/04/01 06:50:01 - POLLER: Poller[Main Poller] STATS: Poller ID 8 fully Replicated
2020/04/01 06:49:07 - POLLER: Poller[Main Poller] STATS: Poller ID 7 fully Replicated
2020/04/01 04:48:58 - POLLER: Poller[Main Poller] STATS: Poller ID 8 fully Replicated
2020/04/01 04:48:04 - POLLER: Poller[Main Poller] STATS: Poller ID 7 fully Replicated
2020/04/01 02:49:01 - POLLER: Poller[Main Poller] STATS: Poller ID 8 fully Replicated
2020/04/01 02:47:11 - POLLER: Poller[Main Poller] STATS: Poller ID 7 fully Replicated
2020/04/01 00:48:58 - POLLER: Poller[Main Poller] STATS: Poller ID 8 fully Replicated
2020/04/01 00:47:06 - POLLER: Poller[Main Poller] STATS: Poller ID 7 fully Replicated 

I just changed it to 16 hours to see if there is a difference

Side question do we really need a sync interval anymore since alot of these updates lately push to the remotes just fine 

Thanks guys !

**Comment by bmfmancini** [comment]
I have disabled the function for now just to save my poor main server getting pounded every 2 hours with sync's 

Thanks guys !

**Comment by bmfmancini** [comment]
Ok looks like even though it's disabled its still replicating !!!

**Comment by TheWitness** [comment]
Mainly no, just for the auth pieces these days are when a data collector has been down for a bit.

**Comment by TheWitness** [comment]
More thing solved in 1.2.11.

**Comment by bmfmancini** [comment]
cool!

Was this polling sync fixed in 1.2.11 is there a comit I can cherry pick ?

**Comment by bmfmancini** [comment]
Hey Guys any thoughts on this one ?
Is there something I can do in the meantime to disable the sync ?

**Comment by bmfmancini** [comment]
ok I am using the /lib/poller.php from the 1.2.x branch that fixed the automation issue where the remote pollers did not create graphs 

From what I can tell the issue started after that I believe the issue is with the /lib/poller.php since nothing has changed on settings.php which include /lib/poller.php

possibly this commit 
https://github.com/Cacti/cacti/commit/cee5f34478785a614928e8bb1ffbcf76072e44d8
there were some changes made to the replicate function by @TheWitness  maybe something went belly up ??

**Comment by bmfmancini** [comment]
I reverted the original /lib/poller.php from the release zip and the same effect happened 
I know this did not happen in 1.2.7

**Comment by bmfmancini** [comment]
I checked on my 1.2.7 lab for this behaviour and its fine so something changed since then that has the pollers sync at the default 2 hours and the settings page setting is ignored

**Comment by TheWitness** [comment]
It's these lines from poller_replicate_check in poller.php.

![image](https://user-images.githubusercontent.com/1439914/78383498-7e2b2880-75a6-11ea-85f8-a90a9c26b4ff.png)

**Comment by bmfmancini** [comment]
is that fixed on the 1.2.x branch can I just copy that ?

**Comment by bmfmancini** [comment]
@TheWitness  did you mean these lines need to be removed or the variable is the issue ?

**Comment by TheWitness** [comment]
If you don't want to even think about, it, just comment them stop the exec_background from happening.  Otherwise, just make sure the sync_interval != 0 is there.  0 means 'disabled'.

**Comment by TheWitness** [comment]
Going to mark this one as resolved since it's already fixed in the 1.2.x branch.

**Comment by bmfmancini** [comment]
ouch ok ill find the differences 

thanks !

**Comment by bmfmancini** [comment]
Here is that same block of code from the 1.2.x branch poller.php

       $pollers = db_fetch_assoc("SELECT id
                FROM poller
                WHERE id > 1
                AND dbhost NOT IN ('localhost', '127.0.0.1', '')
                AND disabled = ''
                AND sync_interval != 0
                AND (last_sync = '0000-00-00 00:00:00' OR requires_sync = 'on'
                OR (UNIX_TIMESTAMP()-UNIX_TIMESTAMP(last_sync) >= IFNULL(sync_interval, $sync_interval)))");



Which looks identical to the poller.php in the 1.2.9 zip 
I also did a diff between 1.2.x to 1.2.9
are you sure this is fixed in 1.2.x ?

**Comment by bmfmancini** [comment]
![image](https://user-images.githubusercontent.com/13388748/78454779-32d94e80-7668-11ea-8dc9-c9d537284337.png)

**Comment by TheWitness** [comment]
Yup, check your pollers table and see that everything is set to zed:

```sql
SELECT id, sync_interval FROM poller;
```

**Comment by TheWitness** [comment]
This is what I get on my 'wee' system.

![image](https://user-images.githubusercontent.com/1439914/78456505-16421400-7672-11ea-8e92-5b4f2af08af6.png)

**Comment by TheWitness** [comment]
That's 1 and 2 since I missed the Data Collector id.

**Comment by bmfmancini** [comment]
Yep I see the 7200 

however, when I select something like 8 hours that interval does not change should it not change based on the setting selected ?  just for my understanding

i.e I selected 8 hours polling interval but still have 7200 in the db

**Comment by TheWitness** [comment]
Cherry picks at night, coders delight, cherry pickers in the morn, coders be warned.  Pollers.php

**Comment by bmfmancini** [comment]
I deleted that comment because I wanted to update my lab from 1.2.10 to 1.2.x branch 
I am seeing the same thing 


Date | Sat, 04 Apr 2020 12:20:00 -0500
-- | --
Cacti Version | 1.2.11
Cacti OS | unix
RSA Fingerprint | e3:de:f8:a8:ea:28:c7:04:69:d1:85:17:1c:ea:e5:02
NET-SNMP Version | NET-SNMP version: 5.7.3
RRDtool Version Configured | 1.5.0+
RRDtool Version Found | 1.5.5



MariaDB [cacti]> select sync_interval from poller;
+---------------+
| sync_interval |
+---------------+
|          7200 |
|          7200 |
+---------------+
2 rows in set (0.00 sec)

MariaDB [cacti]>
