### ISSUE TITLE
Consultation on the cacti database

### ISSUE THREAD

**Issue by hramose** [Cacti/cacti#3394]
Is there a way to make a query by sql that lists all the configured graphs and know if they are graphing?

Is there a way to make a query by sql that lists all the configured graphs and know if they are graphing?

**Comment by hramose** [comment]
is there a way to make a query in sql that shows me the consumption averages in a time range? for configured devices or graphics

**Comment by cigamit** [comment]
This is not an issue.  We have a support forum for these types of questions.
http://forums.cacti.net
