### ISSUE TITLE
Call to non-existent function poller_push_reindex_data_to_poller() in lib/data_query.php, line 385

### ISSUE THREAD

**Issue by jenhek** [Cacti/cacti#3397]
**Describe the bug**

Typo???

**To Reproduce**

find cacti -exec fgrep -l poller_push_reindex_data_to_poller {} \;

**Expected behavior**

No error message in cacti.log

**Screenshots**

N/A

**Desktop (please complete the following information):**

irrelevant

**Smartphone (please complete the following information):**

irrelevant

**Additional context**

line 385 in cacti/data_query.php contains a typo,
my guess is that the call to the nowhere existent
function 

     poller_push_reindex_data_to_poller()

should read

    poller_push_reindex_data_to_main()

Doing this on my system helps ;-)

Sorry for not supplying a patch :-(

No test procedures?

**Comment by TheWitness** [comment]
The function was renamed.  You are cherry picking, but not the whole bunch.

**Comment by jenhek** [comment]
This way or the other. Thx that it's fixed.

I prefer strawberries.

**Comment by netniV** [comment]
That's why i dislike cherry picking outside of patch management.  It's useful for releasing dev work to test, but production stuff should be all or nothing, imho. 👍

**Comment by jenhek** [comment]
I was told to do so. Nothing else.

**Comment by bmfmancini** [comment]
I'm always on the fence there with each new release can come a bunch of new
issues with upgrade and stuff so I can cherry pick just the fix I need
until I can test out the new stable version I Think that's better overall

Since cacti has many release keeping on top of testing each new build can
take some time my opinion anyways

As always thanks for everything!

**Comment by TheWitness** [comment]
I prefer wine, which either cherries over strawberries.  I prefer reds in general, but especially when black cherries or dark chocolate are involved.  With strawberries, you have to drink white.  We need to get 1.2.11 out the door.
