### ISSUE TITLE
Aberrant Behavior Detection in Time Series for Network Monitoring

### ISSUE THREAD

**Issue by balainit** [Cacti/cacti#3398]
rrdtool implements the Holt-Winters Time Series Forecasting Algorithm for this purpose.

It lets you define additional lines on your graph for expected value and expected value +- X standard deviations. It then lets you do comparisons of the actual value with these calculated expected values and take action based on the result

This lets you do something like "Alert if the actual value is > 2SD away from the expected value" which can alert for 'traffic too high' at 3am on sunday for the same traffic level that generates a 'traffic too low' at 9am on monday.

It 'learns' the patterns. As I understand it, after ~10 cycles of the pattern it will be pretty close to accurate. so after a couple weeks you can rely on it's daily pattern, after a couple months it will notice weekends with great accuracy, etc.

some useful links for this

the original usenix paper and slides
http://usenix.org/legacy/publications/library/proceedings/lisa2000/full_papers/brutlag/brutlag_html/index.html
http://www.hpl.hp.com/news/events/csc/2005/jake_slides.pdf

info in it's implementation in rrdtool (also under GPLv2 so code can be copied directly)

http://cricket.sourceforge.net/aberrant/rrd_hw.htm
https://oss.oetiker.ch/rrdtool/doc/rrdcreate.en.html

**Comment by TheWitness** [comment]
We have known about this for several years, it just makes a very complicated app all the more complicated, so we have been avoiding implementing.  I guess there will come a point where we do implement it.

**Comment by TheWitness** [comment]
Closing the holt winters issues for now.  We will reopen once we get the overall issue list reduced.
