### ISSUE TITLE
cacti 1.2.10 upgrade stuck at 2% on fedora 31

### ISSUE THREAD

**Issue by majed17** [Cacti/cacti#3401]
Today, i downloaded the 1.2.x and replaced the installer.php and earlier i had replaced the cacti_Stats.xml.gz and all similar scripts in its folder..but still the upgrade will not budge above 2%

Refresh in |   | ProgressLast updated: 14:53:52
-- | -- | --
  |   | 2 %

`020/04/04 14:15:14 - SYSTEM STATS: Time:13.2481 Method:spine Processes:1 Threads:1 Hosts:35 HostsPerProcess:35 DataSources:5517 RRDsProcessed:2233
2020/04/04 14:20:13 - SPINE: Poller[1] PID[11675] Device[1] DEBUG Falling back to UDP Ping Due to SetUID Issues
2020/04/04 14:20:14 - SYSTEM STATS: Time:12.1893 Method:spine Processes:1 Threads:1 Hosts:35 HostsPerProcess:35 DataSources:5517 RRDsProcessed:2233
2020/04/04 14:25:14 - SPINE: Poller[1] PID[11800] Device[1] DEBUG Falling back to UDP Ping Due to SetUID Issues
2020/04/04 14:25:15 - SYSTEM STATS: Time:13.1982 Method:spine Processes:1 Threads:1 Hosts:35 HostsPerProcess:35 DataSources:5517 RRDsProcessed:2233
2020/04/04 14:30:13 - SPINE: Poller[1] PID[12078] Device[1] DEBUG Falling back to UDP Ping Due to SetUID Issues
2020/04/04 14:30:14 - SYSTEM STATS: Time:12.1982 Method:spine Processes:1 Threads:1 Hosts:35 HostsPerProcess:35 DataSources:5517 RRDsProcessed:2233
2020/04/04 14:35:13 - SPINE: Poller[1] PID[12185] Device[1] DEBUG Falling back to UDP Ping Due to SetUID Issues
2020/04/04 14:35:15 - SYSTEM STATS: Time:13.2332 Method:spine Processes:1 Threads:1 Hosts:35 HostsPerProcess:35 DataSources:5517 RRDsProcessed:2233
2020/04/04 14:40:13 - SPINE: Poller[1] PID[12454] Device[1] DEBUG Falling back to UDP Ping Due to SetUID Issues
2020/04/04 14:40:13 - SYSTEM STATS: Time:12.1646 Method:spine Processes:1 Threads:1 Hosts:35 HostsPerProcess:35 DataSources:5517 RRDsProcessed:2233
2020/04/04 14:45:14 - SPINE: Poller[1] PID[12708] Device[1] DEBUG Falling back to UDP Ping Due to SetUID Issues
2020/04/04 14:45:14 - SYSTEM STATS: Time:12.2898 Method:spine Processes:1 Threads:1 Hosts:35 HostsPerProcess:35 DataSources:5517 RRDsProcessed:2233
2020/04/04 14:50:14 - SPINE: Poller[1] PID[12835] Device[1] DEBUG Falling back to UDP Ping Due to SetUID Issues
2020/04/04 14:50:15 - SYSTEM STATS: Time:13.1692 Method:spine Processes:1 Threads:1 Hosts:35 HostsPerProcess:35 DataSources:5517 RRDsProcessed:2233
2020/04/04 14:53:51 - INSTALL: always: Spawning background process: /bin/php '/usr/share/cacti/install/background.php' 1586001231.8456
2020/04/04 14:53:52 - INSTALL: Checking arguments
2020/04/04 14:53:52 - INSTALL: always: Setting PHP Option max_execution_time = 0
2020/04/04 14:53:52 - INSTALL: always: Setting PHP Option memory_limit = -1
2020/04/04 14:53:52 - INSTALL: always: Starting UPGRADE Process for v1.2.10
2020/04/04 14:55:14 - SPINE: Poller[1] PID[13111] Device[1] DEBUG Falling back to UDP Ping Due to SetUID Issues
2020/04/04 14:55:15 - SYSTEM STATS: Time:13.3745 Method:spine Processes:1 Threads:1 Hosts:35 HostsPerProcess:35 DataSources:5517 RRDsProcessed:2233
`

now running 
sudo -u apache /bin/php '/usr/share/cacti/install/background.php' 1585896763.8316
no more produces an error.. but as the subjects states, the problem remains

**Comment by netniV** [comment]
Can you do the following:

1. Close any browser windows
2. Ensure no background.php process is running
3. Delete install settings from your database 
   ```sql
   DELETE FROM Settings where name like 'install_%'
   ```
4. Turn on full install logging
   ```sql
   REPLACE INTO Settings values ('log_install','5')
   ```
5. Start the upgrade process again.
6. Email the logs/install_complete.log to developers@cacti.net

I'm not sure the process you went through for overwriting your current install with the GitHub version, but you also need to make sure all permissions etc, are correct.

**Comment by majed17** [comment]
all the permissions are passed:
USE cacti;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [cacti]> delete from settings where name like 'install_%';
Query OK, 21 rows affected (0.003 sec)

MariaDB [cacti]> REPLACE INTO Settings values ('log_install','5');
ERROR 1146 (42S02): Table 'cacti.Settings' doesn't exist

**Comment by netniV** [comment]
Lowercase S on settings

**Comment by majed17** [comment]
well that is not my fault...done ..

**Comment by netniV** [comment]
I know that was my bad because of autocorrect and I hadn’t noticed.

**Comment by majed17** [comment]
well, at least, you did not say "excuse me" which is more enlightening :)

**Comment by sd3m0n** [comment]
Thank you. Mine too stuck at 42% (Ubuntu Server 18.04.4). The solutoin from post https://github.com/Cacti/cacti/issues/3401#issuecomment-609022683 helped.

**Comment by KnoAll** [comment]
Similarly for me, doing the process above helped me get past this issue. not sure if you still want it, but I have sent the log on to you as requested.

**Comment by TheWitness** [comment]
Can you guys reconfirm on 1.2.11.  Please note bug #3436 before you get all tied in a knot though.

**Comment by KnoAll** [comment]
I am still seeing this on 1.2.11. Your workaround for authentication appears to work.

**Comment by KnoAll** [comment]
I have just done this upgrade again, and did your suggested db changes first, and got the stuck upgrade at 42% again on 'importing packages'
![image](https://user-images.githubusercontent.com/7632685/78928165-fdac7200-7a54-11ea-96fa-1c6dd28371f2.png)
I have sent the install-complete.log to the developers email.

**Comment by KnoAll** [comment]
Confirming, deselecting all Templates for import seems to allow the upgrade to complete.

**Comment by netniV** [comment]
OK, we switched to using integrated packaging import for better reporting and control rather than calling the CLI which has proven to be problematic at times.  However, something clearly isn't right with it or we have corrupt packages again.

Looking at the commit history for the packages folder, nothing has changed since we last did it, so it must be at the code level and possibly a timing issue in some way.

Please bear with us as we try to replicate and fix it.

**Comment by netniV** [comment]
I believe that this was resolved as part of another issue tracker.  Please update us if this is not the case.
