### ISSUE TITLE
About Structured RRA Path

### ISSUE THREAD

**Issue by ixinshang** [Cacti/cacti#3415]
**Describe the bug**
when selected Structured RRA Path, add a new device,something error.
like:
CMDPHP ERROR: Unable to set directory permissions for '/var/www/html/cacti/rra/3'
CMDPHP PHP ERROR WARNING Backtrace: (/host.php[60]:form_save(), /host.php[252]:api_device_save(), /lib/api_device.php[801]:chown(), CactiErrorHandler())
ERROR PHP WARNING: chown(): Operation not permitted in file: /var/www/html/cacti/lib/api_device.php on line: 801

when didn't select Structured RRA Path,it's correct.

OS: CentOS Linux release 7.7.1908 (Core)
rrdtool：1.4.8
cacti:1.2.10
mariadb:10.4.12

user:
groups cactiuser
cactiuser : apache

groups apache
apache : apache

i found something about it ,eg.https://github.com/Cacti/cacti/issues/376  and https://github.com/KnoAll/cacti-template/issues/74.   
but,no effects. 

Could you give me some advices,thanks.

**Comment by netniV** [comment]
This is because when setting the structured path, makes the directory and attempts to keep the permissions as desired.  We should really suppress the warning you see there with our own and record what we failed to be able to do.

**Comment by ixinshang** [comment]
> This is because when setting the structured path, makes the directory and attempts to keep the permissions as desired. We should really suppress the warning you see there with our own and record what we failed to be able to do.

thanks.  
And Does it affect the use?

**Comment by netniV** [comment]
Shouldn't do, depends on whether your poller runs as a different user to your website.  If that is the case, you may find that removing older directories via the GUI would fail but since we never remove RRA's without explicit request, you shouldn't notice anything unless you are doing things at the cli level.

**Comment by ixinshang** [comment]
> Shouldn't do, depends on whether your poller runs as a different user to your website. If that is the case, you may find that removing older directories via the GUI would fail but since we never remove RRA's without explicit request, you shouldn't notice anything unless you are doing things at the cli level.

Could you give me some advises or links to avoid this.  thanks.

**Comment by ixinshang** [comment]
thanks everyone.
