### ISSUE TITLE
Auto Nan replace

### ISSUE THREAD

**Issue by a-vasilishin** [Cacti/cacti#3416]
I am using cacti for monitoring many heavy loaded (by network)  servers that located in many data-centres. Almost all of them have 100% network load. Is it possible to make some retries when request timeout or auto Nan replace with last khown good?
![изображение](https://user-images.githubusercontent.com/3845145/78546013-6ef5e600-7805-11ea-98e7-abd9c3a0f4fe.png)

**Comment by netniV** [comment]
Depending on the heartbeat period of your RRA, RRDtool will assume good data until that has been exceeded.  Once exceed NaN will become the default value it uses.

**Comment by a-vasilishin** [comment]
If I understand correctly, Spine makes only one request per period. If the packet with answer was dropped somewhere in Internet, we get NaN

**Comment by netniV** [comment]
Correct, and we supply that to RRDTool which in turn 'fills' the gaps once it receives good data.

**Comment by TheWitness** [comment]
Just increase your default heartbeat.  You should be able to do that using the RRDtool command.

**Comment by a-vasilishin** [comment]
> Just increase your default heartbeat. You should be able to do that using the RRDtool command.
Howto do that?

**Comment by TheWitness** [comment]
rrdtool tune [options]

man rrdtune

**Comment by a-vasilishin** [comment]
Sorry, that I opened it again. There was such heartbeat
ds[nginx_handled].minimal_heartbeat = 600
ds[nginx_requests].minimal_heartbeat = 600
ds[nginx_accepts].minimal_heartbeat = 600
I increased it to 900 by command
for rrd in `ls /usr/share/cacti/site/rra/*/*.rrd`; do  rrdtool tune $rrd --heartbeat nginx_accepts:900 ; done
What value is good?

**Comment by a-vasilishin** [comment]
Increase that value to 1200. No changes are noted.
![изображение](https://user-images.githubusercontent.com/3845145/78973170-0154fd00-7b18-11ea-8c8f-858f91d37b1e.png)
Is there possibility to make a spike kill by cron?

**Comment by TheWitness** [comment]
Do an rrdtool dump and let's see what's there.

**Comment by a-vasilishin** [comment]
There are many NaN's :)  [nginx-socket.txt](https://github.com/Cacti/cacti/files/4463240/nginx-socket.txt)
