### ISSUE TITLE
Technical Support should offer estimated maximum runtime of polled items

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#3417]
# Feature Request

## Is your feature request related to a problem? Please describe

When viewing the technical support page, an estimate on the total time to poll all items should be displayed.  If this is near or exceeds the polling time, a warning should be presented to allow administrators to realise that they may well over run.

## Describe alternatives you've considered

This warning could ben verified once a day/week and present into the cacti log as a warning.

## Additional context

This idea came about because sometimes, the combination of retries and timeouts can cause poller overruns thus not all items are successfully polled properly.

**Comment by bmfmancini** [comment]
Awsome Idea!

Would there be a way to include some stats in that window/part of the page 
i.e amount of retries/timeouts in 24 hours ?

**Comment by xmacan** [comment]
I have similar thing in Intropage plugin. I will do it

**Comment by netniV** [comment]
@xmacan awesome, if you would create it as a pull request against develop as would be a 1.3 thing if merged.
