### ISSUE TITLE
Infinite loop in poller_automation.php if auto net discovery is "almost turned on" 

### ISSUE THREAD

**Issue by tgkay** [Cacti/cacti#342]
If a foolish user (me in this case) sets a schedule type of monthly but then fails to set days, dates etc. you end up with poller automation in an infinite loop:

The call to background_exec() in the cacti/poller_automation.php in the net_discovery process proceeds and the switch statement in api_automation_is_time_to_start() gets a discovery type of 4 with a $net['next_start'] == '0000-00-00 00:00:00'  but $days as an empty array thus the while(TRUE) loop break is never matched.

It's obviously user error but that should be flagged in the interface or die gracefully. Hopefully the above is clear, I'm posting this as I /need/ to get my cacti instance up and each poll creating a spinning PHP process has led to there being some work to do. Happy to provide more info later in the week if required.

Thanks for the otherwise excellent software!

Tim

**Comment by cigamit** [comment]
Yousa, going to fix that one.  Won't make the 1.0.4 release, but right after.

**Comment by cigamit** [comment]
Resolved on the front side.  For new networks, they will be disabled in cases where the date ranges have been defined incorrectly.
