### ISSUE TITLE
The aggregation graph only displays a single 95th percentile (聚合图形只显示一条95线)

### ISSUE THREAD

**Issue by teesa-git** [Cacti/cacti#3425]
I modified the original 95 graphic template to display two 95 lines on a single graphic, one in the incoming direction and the other in the out direction.

(我修改了原始的95图形模版，在单个图形上面能正常显示两条95线，一个是进方向的，另一个是出方向的)
![33](https://user-images.githubusercontent.com/52067473/78655797-130c8980-78f9-11ea-89ca-ddaaa0b8a28d.jpg)

![44](https://user-images.githubusercontent.com/52067473/78655359-7ba73680-78f8-11ea-907e-cd8d6af3a364.jpg)

But when I added the aggregated graph, the result only showed a single 95th percentile. There is only one 95th percentile data when the graphic is debugged.
(但是在我添加聚合图形的时候，结果只显示一条95线。图形debug 时也只有一个95线的数据)

![11](https://user-images.githubusercontent.com/52067473/78655416-8eba0680-78f8-11ea-98b3-20ae19b6da85.jpg)

![22](https://user-images.githubusercontent.com/52067473/78655488-a85b4e00-78f8-11ea-8534-36f8c654c094.jpg)
![55](https://user-images.githubusercontent.com/52067473/78656040-654daa80-78f9-11ea-9881-1bd25cc9a3b5.jpg)

This works normally on 0.8.8a
(我在0.8.8a上面是能正常显示的。)

![07175458](https://user-images.githubusercontent.com/52067473/78656186-9b8b2a00-78f9-11ea-846b-97155f9d3a37.jpg)

What should I do?
(请问该怎么解决？)

---
Edited by netniV, translated by Google and interpreted by netniV

**Comment by netniV** [comment]
I'd love to help, unfortunately English is the primary language here on GitHub.  I'll see if Google can help me out 👍

**Comment by netniV** [comment]
OK, so I've made some translations and interpretations which I hope are correct.  Unfortunately, I now know that I will have little to offer on this as I don't fully have a grasp on how the 95th percentile stuff actually works yet.  I think this is one for either @cigamit or @TheWitness

**Comment by teesa-git** [comment]
@netniV thanks, my problem is why the aggregate graph only show one 95th line ?

**Comment by TheWitness** [comment]
What version of Aggregate were you using in Cacti 0.8.x?  Thanks!

**Comment by TheWitness** [comment]
Also, not that starting in Cacti 1.2.9, pretty sure thats the release, you can convert an Aggregate Graph to a standard graph, where you can add as many 95th ptile COMMENTS as you like.  But note, that this is a one time switch.

**Comment by teesa-git** [comment]
> What version of Aggregate were you using in Cacti 0.8.x?  Thanks!

0.8.8b

**Comment by teesa-git** [comment]
> Also, not that starting in Cacti 1.2.9, pretty sure thats the release, you can convert an Aggregate Graph to a standard graph, where you can add as many 95th ptile COMMENTS as you like.  But note, that this is a one time switch.

I don’t know enough about the one time switch. And the release of 1.2.9 can do that?or include that feature?

**Comment by TheWitness** [comment]
I asked for your aggregate release not cacti release.

**Comment by teesa-git** [comment]
> I asked for your aggregate release not cacti release.

the version of aggregate  is 0.75 , cacti version is 0.8.8b.

**Comment by TheWitness** [comment]
Okay, since you are on that release, just upgrade to 1.2.11, and from the Aggregate Screen, just convert to a normal graph and you will be just about back to where you were before.

**Comment by teesa-git** [comment]
OK , i have one more question. now i use the 1.2.10 , when i add the custom graph ,there only show the logical ports, doesn't show the physical ports.

**Comment by TheWitness** [comment]
Ask that question on the forums.
