### ISSUE TITLE
Better check of max_connections for mysql

### ISSUE THREAD

**Issue by jenhek** [Cacti/cacti#3426]
On some platforms it is not sufficient to check in the configuration file for
the mysqld (/etc/my.cnf) is "max_connections" is sufficient.

There might be other configuration files of the OS that limits this value.
In my case I had to modify /etc/security/limits.conf and 
/usr/lib/systemd/system/mariadb.service before the change in /etc/my.cnf 
actually was acknoledged by mysqld. (CentOS7)

One more reliable way would be testing like this:

      mysql -e"show variables like '%max_connecti%'"

**Comment by netniV** [comment]
This is what our MySQL recommendations does for most SQL configuration variables.  We do not assume to have access to the raw configuration files.
