### ISSUE TITLE
AUTOM8 Backtrace Errors due to SNMP class not muting snmpv3 auth errors

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3429]
Hey Guys 

I noticed after running device discovery the following errors come up 
I don't see any specific issues with AUTOM8 adding the device

Thought I would report it to get your take if this is a dummy alert or something else 

2020/04/06 10:36:53 - CMDPHP PHP ERROR WARNING Backtrace: (/poller_automation.php[358]:discoverDevices(), /poller_automation.php[569]:automation_valid_snmp_device(), /lib/api_automation.php[3265]:cacti_snmp_session_get(), /lib/snmp.php[479]:SNMP->get(), CactiErrorHandler())
2020/04/06 10:36:51 - CMDPHP PHP ERROR WARNING Backtrace: (/poller_automation.php[358]:discoverDevices(), /poller_automation.php[569]:automation_valid_snmp_device(), /lib/api_automation.php[3265]:cacti_snmp_session_get(), /lib/snmp.php[479]:SNMP->get(), CactiErrorHandler())
2020/04/06 10:36:51 - CMDPHP PHP ERROR WARNING Backtrace: (/poller_automation.php[358]:discoverDevices(), /poller_automation.php[569]:automation_valid_snmp_device(), /lib/api_automation.php[3265]:cacti_snmp_session_get(), /lib/snmp.php[479]:SNMP->get(), CactiErrorHandler())
2020/04/06 10:36:50 - CMDPHP PHP ERROR WARNING Backtrace: (/poller_automation.php[358]:discoverDevices(), /poller_automation.php[569]:automation_valid_snmp_device(), /lib/api_automation.php[3265]:cacti_snmp_session_get(), /lib/snmp.php[479]:SNMP->get(), CactiErrorHandler())
2020/04/06 10:36:50 - CMDPHP PHP ERROR WARNING Backtrace: (/poller_automation.php[358]:discoverDevices(), /poller_automation.php[569]:automation_valid_snmp_device(), /lib/api_automation.php[3265]:cacti_snmp_session_get(), /lib/snmp.php[479]:SNMP->get(), CactiErrorHandler())
2020/04/06 10:36:50 - CMDPHP PHP ERROR WARNING Backtrace: (/poller_automation.php[358]:discoverDevices(), /poller_automation.php[569]:automation_valid_snmp_device(), /lib/api_automation.php[3265]:cacti_snmp_session_get(), /lib/snmp.php[479]:SNMP->get(), CactiErrorHandler())
2020/04/06 10:36:50 - CMDPHP PHP ERROR WARNING Backtrace: (/poller_automation.php[358]:discoverDevices(), /poller_automation.php[569]:automation_valid_snmp_device(), /lib/api_automation.php[3265]:cacti_snmp_session_get(), /lib/snmp.php[479]:SNMP->get(), CactiErrorHandler())
2020/04/06 10:36:49 - CMDPHP PHP ERROR WARNING Backtrace: (/poller_automation.php[358]:discoverDevices(), /poller_automation.php[569]:automation_valid_snmp_device(), /lib/api_automation.php[3265]:cacti_snmp_session_get(), /lib/snmp.php[479]:SNMP->get(), CactiErrorHandler())
2020/04/06 10:36:49 - CMDPHP PHP ERROR WARNING Backtrace: (/poller_automation.php[358]:discoverDevices(), /poller_automation.php[569]:automation_valid_snmp_device(), /lib/api_automation.php[3265]:cacti_snmp_session_get(), /lib/snmp.php[479]:SNMP->get(), CactiErrorHandler())
2020/04/06 10:36:49 - CMDPHP PHP ERROR WARNING Backtrace: (/poller_automation.php[358]:discoverDevices(), /poller_automation.php[569]:automation_valid_snmp_device(), /lib/api_automation.php[3265]:cacti_snmp_session_get(), /lib/snmp.php[479]:SNMP->get(), CactiErrorHandler())
2020/04/06 10:36:48 - CMDPHP PHP ERROR WARNING Backtrace: (/poller_automation.php[358]:discoverDevices(), /poller_automation.php[569]:automation_valid_snmp_device(), /lib/api_automation.php[3265]:cacti_snmp_session_get(), /lib/snmp.php[479]:SNMP->get(), CactiErrorHandler())
2020/04/06 10:36:48 - CMDPHP PHP ERROR WARNING Backtrace: (/poller_automation.php[358]:discoverDevices(), /poller_automation.php[569]:automation_valid_snmp_device(), /lib/api_automation.php[3265]:cacti_snmp_session_get(), /lib/snmp.php[479]:SNMP->get(), CactiErrorHandler())

**Comment by TheWitness** [comment]
Can you show more of the error.  There should also be a WARNING.

**Comment by bmfmancini** [comment]
Sure 

Here you go 

2020/04/06 10:37:14 - CMDPHP PHP ERROR WARNING Backtrace: (/poller_automation.php[358]:discoverDevices(), /poller_automation.php[569]:automation_valid_snmp_device(), /lib/api_automation.php[3265]:cacti_snmp_session_get(), /lib/snmp.php[479]:SNMP->get(), CactiErrorHandler())
2020/04/06 10:37:14 - ERROR PHP WARNING: SNMP::get(): Fatal error: Unknown user name in file: /var/www/html/cacti/lib/snmp.php on line: 479
2020/04/06 10:37:14 - CMDPHP PHP ERROR WARNING Backtrace: (/poller_automation.php[358]:discoverDevices(), /poller_automation.php[569]:automation_valid_snmp_device(), /lib/api_automation.php[3265]:cacti_snmp_session_get(), /lib/snmp.php[479]:SNMP->get(), CactiErrorHandler())
2020/04/06 10:37:14 - ERROR PHP WARNING: SNMP::get(): Fatal error: Unknown user name in file: /var/www/html/cacti/lib/snmp.php on line: 479
2020/04/06 10:37:14 - AUTOM8 NOTE: Graph Added - Device[1481], Graph[13695], DS[Missing Datasource 12314], Rule[Interface Errors]
2020/04/06 10:37:13 - AUTOM8 NOTE: Graph Added - Device[1481], Graph[13694], DS[Missing Datasource 12313], Rule[Interface Errors]
2020/04/06 10:37:13 - AUTOM8 NOTE: Graph Added - Device[1481], Graph[13693], DS[Missing Datasource 12312], Rule[Interface Errors]
2020/04/06 10:37:13 - CMDPHP PHP ERROR WARNING Backtrace: (/poller_automation.php[358]:discoverDevices(), /poller_automation.php[569]:automation_valid_snmp_device(), /lib/api_automation.php[3265]:cacti_snmp_session_get(), /lib/snmp.php[479]:SNMP->get(), CactiErrorHandler())
2020/04/06 10:37:13 - ERROR PHP WARNING: SNMP::get(): Fatal error: Unknown user name in file: /var/www/html/cacti/lib/snmp.php on line: 479
2020/04/06 10:37:13 - AUTOM8 NOTE: Graph Added - Device[1481], Graph[13692], DS[Missing Datasource 12311], Rule[Interface Errors]

**Comment by bmfmancini** [comment]
The missing DS is fine I did delete that device later on

**Comment by TheWitness** [comment]
Okay, we just need to mask off those error messages.  They are normal.  Just clogging the log.

**Comment by TheWitness** [comment]
So, test again with the latest lib/snmp.php in the 1.2.x branch.
