### ISSUE TITLE
Device Discovery cannot handle dots in device name (1.0.4)

### ISSUE THREAD

**Issue by Xake** [Cacti/cacti#343]
The network I am monitoring has a couple of switches that are named things like "acc-10.9.1.128"
However, when I run Discover on this network, the devices are added and graphs are created correctly under the name "acc-10". Shich menas that I am currently has ten devices named "acc-10".
Please look into if this i fixable.

**Comment by cigamit** [comment]
This one is kind of interesting, we are assuming a domain name when we find something like this.  We should be able to provide logic.

**Comment by cigamit** [comment]
Resolved, thanks!

**Comment by Xake** [comment]
Still not fixed.
#749 created with proved fix
