### ISSUE TITLE
Graph not show 

### ISSUE THREAD

**Issue by pisith168** [Cacti/cacti#3431]
![image](https://user-images.githubusercontent.com/63323646/78729234-29076200-796c-11ea-9c7f-66e978cc6e8c.png)
Dear sir 
please help after the installed cacti graph shows normal but when I open again not show. thanks

**Comment by bmfmancini** [comment]
What version of cacti?
What is the state of the device is it showing up?
Are you using snmp on that device?
Enable device debug and see what output shows up in the log

**Comment by pisith168** [comment]
Cacti version 1.2.10
the device working normally 
yes use snmp

**Comment by TheWitness** [comment]
Update to 1.2.11, then check the permissions of the 'rra' folder to ensure that your cron user and your apache user can write into it and the file.  Lastly review the Cacti log for periodic "SYSTEM STATS:" messages that align with your data collection frequency desired.

**Comment by pisith168** [comment]
![image](https://user-images.githubusercontent.com/63323646/78740573-befdb580-7989-11ea-901f-6ed0f15383ae.png)
rra write already and can run real-time but not record data

**Comment by pisith168** [comment]
![image](https://user-images.githubusercontent.com/63323646/78741053-ed2fc500-798a-11ea-87d1-ddb26ad823b2.png)
Real-time can show but not record graph

**Comment by TheWitness** [comment]
What's in your Cacti.log?  Dos you see SYSTEM STATS: in green every poller interval.  If not, you need to figure out why cron is not triggering data collection.

**Comment by pisith168** [comment]
![image](https://user-images.githubusercontent.com/63323646/78860510-fab97d80-7a64-11ea-9380-8e97b47bb5bb.png)
this log bro please check

**Comment by TheWitness** [comment]
Read at the bottom of the image you uploaded, read it twice, or even 3 time bro.  Your cron stopped.

**Comment by pisith168** [comment]
so how to start cron bro please

**Comment by bmfmancini** [comment]
First check crond daemon stays

Systemctl status crond

Next make sure you setup cron to run at the proper time

Crontab - l under the user your running cacti under or check under cron.d
for the user cron file and make sure it setup to fire ever minute or 5
whatever your polling is

Next you can monitor the crond log to make sure its firing properly

**Comment by TheWitness** [comment]
This is all covered in the install documentation, so closing this now.
