### ISSUE TITLE
Cacti 1.2.10 stuck on 2%

### ISSUE THREAD

**Issue by ank0l0g** [Cacti/cacti#3433]
Hello.

Install cacti 1.2.10 centos7.
The second day hangs at around 2%.
PHP Option in file php.ini memory_limit = 512M
![Install_stuck](https://user-images.githubusercontent.com/60463210/78748250-98854d80-797c-11ea-8595-1ca27e2de685.JPG)

**Comment by TheWitness** [comment]
Can you please try again on 1.2.11, but please review bug #3436 and plan accordingly before you begin.

**Comment by ank0l0g** [comment]
Install from repository CentOS 7. There is only 1.2.10

**Comment by ank0l0g** [comment]
My file
[intsall-comlete.log](https://github.com/Cacti/cacti/files/4454923/intsall-comlete.log)

**Comment by TheWitness** [comment]
One more time.  Install 1.2.12 from cacti.net.  please be careful of issue #3436.
