### ISSUE TITLE
can't change password on cacti 1.3.0-dev

### ISSUE THREAD

**Issue by majed17** [Cacti/cacti#3437]
password only changes from the console menu

if i try changing by clicking from the right corner, it just displays the same password window again.

i tried this on the mention version which is actually a copy from 1.2.9

Os: gentoo

php version: 7.4.4

**Comment by TheWitness** [comment]
@majed17, check #3436, and then after you have confirmed that is not the case, please upload diagnostic information.  We are not quite ready to start the 1.3 bandwagon hard as all the Dev's are insanely busy right now on our day jobs.  So, you will have to be patient.

**Comment by majed17** [comment]
downgraded to 1.2.11 and it is working... if you desire, comment when you will be free on 1.3 so i try it ..

**Comment by netniV** [comment]
I've gone ahead and reopened this so we don't forget it.  If you can give me the exact steps you took, I'll try it at the weekend.

**Comment by majed17** [comment]
get yourself a 1.2.7 or 8 then upgrade to 1.3-dev..there is no upgrading windows and just after log in try to change the password from the up right corner with php 7.4.4..and it ....try ..

**Comment by netniV** [comment]
7.4.4 is quite high. I’m only on 7.2 on Ubuntu

**Comment by majed17** [comment]
what's better in gentoo is not just this, but the absence of politically correct UBUNTU "trolls"

**Comment by TheWitness** [comment]
Oh, finally... someone who understands me. :)

**Comment by netniV** [comment]
I'm not sure whether to take that as a direct swipe or not ;-)

Will see if I can make time for this over the weekend though.

**Comment by majed17** [comment]
too bad my topic got deleted from ubuntu forums

**Comment by netniV** [comment]
Hi Majed, I didn't have a problem with my dev password changing. When I set the force password change on during a recent update to copy_user.php, it required me to login and change my password.

Can you confirm if you still have an issue?

**Comment by majed17** [comment]
so to do it right this time...download from the develop branch?
and
sudo -u cacti php -q cli/upgrade_database.php --forcever=`cat include/cacti_version`

Updating Cacti Version in Database

update version set cacti = '1.2.12';

?

**Comment by netniV** [comment]
There was an issue where the upgrade functions didn’t exist properly. Let me test an upgrade and confirm to you but generally 

I’m pretty sure that if you force upgrade to the cacti version stored in that file, you won’t actually do anything since it  considers your DB to already be at the current level

**Comment by xmacan** [comment]
I have same problem like like @majed17. FreeBSD 12.1 with PHP 7.4

**Comment by netniV** [comment]
Now that is strange, as I'm sure mine changed...but thanks for the fix!
