### ISSUE TITLE
Add custom graph doesn't display the physical port 

### ISSUE THREAD

**Issue by teesa-git** [Cacti/cacti#3439]
my device is H3C 12508 .
The problem is that when I add a custom graphic, the physical port is not displayed.
![22](https://user-images.githubusercontent.com/52067473/78816761-c01ff880-7a04-11ea-8f16-fa7ce288fc02.jpg)
![33](https://user-images.githubusercontent.com/52067473/78817045-260c8000-7a05-11ea-877d-8c909439b1cd.jpg)
![44](https://user-images.githubusercontent.com/52067473/78817049-29077080-7a05-11ea-8cde-62f06aa33cca.jpg)
![111](https://user-images.githubusercontent.com/52067473/78816785-c615d980-7a04-11ea-8d4a-e822b60626f3.jpg)

**Comment by TheWitness** [comment]
Are you sure you understand what you are doing?  Can I suggest that you please take this up on the forums.  I'm asking kind of hard.  There are some good people to help you there.
