### ISSUE TITLE
Cannot update from Cacti 1.0.3 to 1.0.5 on FreeBSD

### ISSUE THREAD

**Issue by pautiina** [Cacti/cacti#344]
Apache logs have error:
`[Mon Feb 27 09:47:08.672910 2017] [:error] [pid 19674] [client 2001:67c:13b8:7::175:61803] PHP Notice:  Undefined variable: memInfo in /var/www/cacti/lib/utility.php on line 1044, referer: https://noc.isp.kh.ua/cacti/install/`
I use FreeBSD and we dont have:
`/proc/meminfo` or `/usr/bin/free`
I think this is not the main problem, but the error is present.
I looked MySQL process and see the following:
![22](https://cloud.githubusercontent.com/assets/11805503/23353989/d1f5a95e-fcd7-11e6-9981-045ef53e30a1.png)
No update is completed.
![21](https://cloud.githubusercontent.com/assets/11805503/23354001/de51e0be-fcd7-11e6-93a0-89c412fcfa9f.png)

**Comment by pautiina** [comment]
To resolve this I restart mysql-server and TRUNCATe table poller_output_boost. After this I can finish update and Cacti log show me error this meminfo again:
```
2017-02-27 10:41:33 - ERROR PHP NOTICE: Undefined variable: memInfo in file: /var/www/cacti/lib/utility.php  on line: 1044
2017-02-27 10:41:33 - CMDPHP PHP ERROR NOTICE Backtrace: (/install/index.php: 664 utilities_get_mysql_recommendations)(/lib/utility.php: 596 utilities_get_system_memory)(/lib/utility.php: 1044 CactiErrorHandler)(/lib/functions.php: 4264 cacti_debug_backtrace)
```

**Comment by ronytomen** [comment]
This is a support issue, not a code issue.  Please use the [forums](http://forums.cacti.net) on the future for such issues.

**Comment by cigamit** [comment]
Resolved.  Thanks for reporting!
