### ISSUE TITLE
My cacti can't send email notification 

### ISSUE THREAD

**Issue by pisith168** [Cacti/cacti#3440]
![image](https://user-images.githubusercontent.com/63323646/78839339-dccf2700-7a2a-11ea-8a86-8f522fef1c63.png)
Dear everyone 
I already set setting for cacti notification but can't send email

**Comment by bmfmancini** [comment]
For Gmail I believe your username name is your full email address

Also if you have two factor auth enabled you need to Generate an app
specific password

Another thing I believe you need to enable SMTP on your Gmail account

**Comment by pisith168** [comment]
this Gmail I test with other cacti can send normal bro and I already enable SMTP

**Comment by TheWitness** [comment]
My recommendation is you follow the phpmailer troubleshooting guide.  PHP Mailer is used by the entire internet.  If it were broken, all hell would break loose.
