### ISSUE TITLE
Cacti 1.2.11 do not Import Template

### ISSUE THREAD

**Issue by ank0l0g** [Cacti/cacti#3441]
Hi.

Cacti 1.2.11 do not Import Template
https://docs.cacti.net/usertemplate:graph:advanced_ping_alt
There are no errors in the logs. There is no other import information either.
![import-1](https://user-images.githubusercontent.com/60463210/78873446-f341a680-7a5b-11ea-81ed-0ab8c1ea52f4.JPG)
![import-2](https://user-images.githubusercontent.com/60463210/78873449-f50b6a00-7a5b-11ea-9876-006c2f6f8bed.JPG)
No matter how much import is done, it is always the same.

**Comment by TheWitness** [comment]
The default is preview.  To import you must flip the toggle switch first.
