### ISSUE TITLE
can't login after downgrading from 1.3.0-dev to 1.2.11 [solved]

### ISSUE THREAD

**Issue by majed17** [Cacti/cacti#3444]
This is on Gentoo.. the downgrade process went succesfully. i then logged out and tried to login back, but i can't... i tried reseting the admin password from mysql and the restarting mysql but nothing..
it doesn't say username or paswword incorrect, just show the opening page again.

**Comment by gbonny1982** [comment]
related to #3436 see solution overthere.

**Comment by majed17** [comment]
thanks!
