### ISSUE TITLE
Fatal PHP Error Translations.php when trying to open cacti login page

### ISSUE THREAD

**Issue by Frewx** [Cacti/cacti#3445]
# Describe the bug

When loading cacti from Chrome/Firefox/Edge on Windows we get http 500 and this log from error logs;

PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'ArrayObject::__construct() expects parameter 3 to be a class name derived from Iterator, 'ArrayIterator' given' in /usr/share/cacti/include/vendor/gettext/src/Translations.php:138\nStack trace:\n#0 /usr/share/cacti/include/vendor/gettext/src/Translations.php(138): ArrayObject->__construct(Array, 0, 'ArrayIterator')\n#1 /usr/share/cacti/include/vendor/gettext/src/Translations.php(153): Gettext\\Translations->__construct()\n#2 /usr/share/cacti/include/global_languages.php(278): Gettext\\Translations::__callStatic('fromMoFile', Array)\n#3 /usr/share/cacti/include/global_languages.php(278): Gettext\\Translations::fromMoFile('/usr/share/cact...')\n#4 /usr/share/cacti/include/global_languages.php(230): load_gettext_oscarotero('cacti')\n#5 /usr/share/cacti/include/global.php(478): include_once('/usr/share/cact...')\n#6 /usr/share/cacti/include/auth.php(28): require_once('/usr/share/cact...')\n#7 /usr/share/cacti/index.php(25): include('/usr/share/cact...')\n#8 {main}\n   in /usr/share/cacti/include/vendor/gettext/src/Translations.php on line 138

## Expected behavior

Opening the cacti web page without any error.

## Desktop (please complete the following information)

- OS: Windows , Linux

- Browser: On Windows: Chrome , Firefox,Edge. On Linux: Chrome

- Version: 1.2.10

## Additional context

Cacti server is built on CentOS 7.
When connecting from Opera/Firefox on Linux we get no problem. The language on Linux is English. But on Windows the language is Turkish.
We didn't have any problems a month ago or so.

**Comment by TheWitness** [comment]
Please update to 1.2.11 noting this important post 1.2.11 bug #3436.    I believe this was addressed already.
