### ISSUE TITLE
Cacti Stats template doesnt work on remote pollers 

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3448]
Hey Guys 

I have noticed that the cacti stats graphs don't work on remote pollers 
even if you create a device pointing to the remote poller all the graphs i.e poller run time will be the values of the Main poller 

If you create a device with 127.0.0.1 and associate it to the remote poller all of the graphs get 0 value

not sure when this started I am sure this used to work before 

I've tried this on 
1.2.9 and 1.2.11

Thanks

**Comment by bmfmancini** [comment]
as far as I can tell this is also happening on 1.2.11 as well

**Comment by netniV** [comment]
Do you mean .12?

**Comment by bmfmancini** [comment]
Yes sorry

**Comment by TheWitness** [comment]
Yea, it's not fixed.

**Comment by TheWitness** [comment]
Just removing the unverified as I'm pretty sure it's not designed to work on remote data collectors.

**Comment by bmfmancini** [comment]
Bump to keep this active

**Comment by TheWitness** [comment]
I'm really busy @ the moment Sean.

**Comment by bmfmancini** [comment]
No worries Larry

I wrote a small script to monitor the polling times on the remote servers
to fit what I wanted to monitor

Just wanted to make sure this didn't expire out

Hope you are well

**Comment by TheWitness** [comment]
Sorry guys, I've been taking some time off.  Now I'm pretty busy, working on the weekends too. No time left for cacti at the moment.

**Comment by bmfmancini** [comment]
commenting so this doesnt get marked as expired

**Comment by anarkia1976** [comment]
Hi, i have the same problem. Do you have time to verify the problem?

**Comment by netniV** [comment]
umm not sure that was for me @anarkia1976 as I haven't been involved in the stats template aside from asking if bmf had the wrong version number at the time.

**Comment by anarkia1976** [comment]
Hi Guys @TheWitness and @netniV, how do you monitor cacti server stats in your environments?
thanks a lot as always.

**Comment by TheWitness** [comment]
We know it broken.  Time, there is never enough of it.

**Comment by bmfmancini** [comment]
Hey guys!

I found something here its not that the data query doesn't work its just the graph the cacti stats template makes !

If you on a remote poller delete the Main poller Runtime graph you can go back and create the graph but select the poller ID
and on top of that the graph is much more detailed !

I will show the outputs on a test system
