### ISSUE TITLE
Items are overlapping in directory permission checks in installation wizard

### ISSUE THREAD

**Issue by nuno-silva** [Cacti/cacti#3449]
# Describe the bug

In the Directory permission checks step of the installation wizard, the directory paths column is too small to display most paths, resulting in them appearing under the actual "check result" and being unreadable. Perhaps it's just a CSS bug.

## To Reproduce

Steps to reproduce the behaviour:

1. Install fresh cacti 1.2.11

2. Complete the installation wizard until you reach the "directory permission checks" step

3. See issue

## Expected behavior

Path column should have space for bigger paths.

## Screenshots

![2020-04-07_cacti_1 2 11_fresh_install](https://user-images.githubusercontent.com/6935057/78925696-c27d6380-7a93-11ea-8e86-b79772545997.png)

## Desktop

- OS: Gentoo Linux

- Browser: Chromium

- Version: 80.0.3987.149 (Developer Build) (64-bit)

**Comment by netniV** [comment]
There seems to be a few Gentoo issues.  Are you running the Gentoo with a desktop and chrome on there?  The CSS styling seems to have failed, you theme looks like the modern one is that correct?

**Comment by nuno-silva** [comment]
I'm running Chromium on a Gentoo Linux Desktop. Cacti was installed on a Gentoo Linux server. I think I used the Classic theme. I don't think the distribution is relevant, but I can re-test on Ubuntu if you prefer. Is there a quick way I can access the installer page without installing a new instance?

**Comment by netniV** [comment]
OK, so that gives me something to look at.  Oh, and which web server are you using?  Just trying to get all the variables together so I can give a reason chance of replicating the test.

**Comment by nuno-silva** [comment]
I'm using `nginx` with `php-fpm` and `mariadb`.

I've just reproduced the bug on an Ubuntu VM running:
- Ubuntu 18.04.4 LTS (Bionic Beaver)
- fresh install of cacti v1.2.11
- classic theme
- `Chromium 80.0.3987.163 Built on Ubuntu , running on Ubuntu 18.04`
- `nginx version: nginx/1.14.0 (Ubuntu)`
- php-fpm `7.2.24-0ubuntu0.18.04.4`
- `MariaDB 10.1.44-MariaDB-0ubuntu0.18.04.1 Ubuntu 18.04`

Here's a screenshot (chromium):
![image](https://user-images.githubusercontent.com/6935057/79669429-4b428080-81b3-11ea-8d34-5546bebc9305.png)

And a copy of the rendered page (as saved by Chromium): [Cacti Server v1.2.11 - Maintenance.zip](https://github.com/Cacti/cacti/files/4497487/Cacti.Server.v1.2.11.-.Maintenance.zip)

On firefox, it's rendered a little different (classic theme on `Mozilla Firefox 75.0`):
![image](https://user-images.githubusercontent.com/6935057/79669661-eab44300-81b4-11ea-8535-f7f0340db76f.png)

Modern theme is OK (chromuim):
![image](https://user-images.githubusercontent.com/6935057/79669601-914c1400-81b4-11ea-96b2-ad39431052e4.png)
