### ISSUE TITLE
Unable to create new graphs - SNMP - Generic OID Template - In/Out Bits

### ISSUE THREAD

**Issue by luizmello043** [Cacti/cacti#345]
Support Team,

I am unable to create new graphs for In/Out Bits (Host already defined).
Process is standard: Enter the Host and create new graph for the desired interface.

When I go to Management --> Data Sources, select the created Data Source for the graph I just created, and turn debug on nothing is displayed in the debug section.

For the graphs already created I can see the graphs but when entering management --> data source with debug enabled in the Data Source Debug I can see the RRD File Information but in the RRDtool Tune Info I see RRA x missing from Cacti Definition.

It was working fine in my previous version 0.8.8g and when I migrated to 1.0.3/1.0.4 it stopped working.

RRDTool is 1.3.x

Thx

**Comment by cigamit** [comment]
You need to be more specific.  Please show Graph Debug output and the RRDTool info output.

**Comment by cigamit** [comment]
This has been resolved by Issue #337.  If you would like to repair your graph, please import the attached template and you will be back in business.

[cacti_graph_template_snmp_-_generic_oid_template.xml.txt](https://github.com/Cacti/cacti/files/852018/cacti_graph_template_snmp_-_generic_oid_template.xml.txt)

**Comment by hasnaouikhouloud** [comment]
please help me i have problem . the graphs was empty when I turn on data source info mode .
i get this:
RRA '0' missing in Cacti definition
RRA '1' missing in Cacti definition
RRA '2' missing in Cacti definition
RRA '3' missing in Cacti definition
RRA '4' missing in Cacti definition
RRA '5' missing in Cacti definition
RRA '6' missing in Cacti definition
RRA '7' missing in Cacti definition
RRA '8' missing in Cacti definition
RRA '9' missing in Cacti definition
RRA '10' missing in Cacti definition
RRA '11' missing in Cacti definition
RRA '12' missing in Cacti definition
RRA '13' missing in Cacti definition
RRA '14' missing in Cacti definition
RRA '15' missing in Cacti definition

**Comment by netniV** [comment]
@hasnaouikhouloud If you need assistance, please create a new issue and give full examples of what you are seeing and what you expect to be seeing, rather than commenting on old issues.  If you feel it is related, you can use the # followed by the number of the issue above (345) to link your new issue back to an old one.
