### ISSUE TITLE
about cookies

### ISSUE THREAD

**Issue by ixinshang** [Cacti/cacti#3451]
hi,everone.
i installed cacti 1.2.11 with mariadb on centos7.1.
when i installing it, i delete "$cacti_cookie_domain" from config.php. it's well.
now, i changed a new domain. when i use correct user and password, i can't login. 
no errors from logs. 
please help me , i want to change a new domain. thanks.

**Comment by netniV** [comment]
And you have definitely commented out or removed the cookie domain from config.php?

**Comment by TheWitness** [comment]
Well, outside of it not being commented out, there is no bug here.  If you Web Server domain does not match your $cacti_cookie_domain, you won't be able to login.

**Comment by ixinshang** [comment]
> And you have definitely commented out or removed the cookie domain from config.php?

yes,like this.

/*
 * Default Cookie domain - The cookie domain to be used for Cacti
 */

/* 
 * $cacti_cookie_domain = 'cacti.net';
 */

/*
 * Save sessions to a database for load balancing
 */

i rebooted server and change another browser to try, i can't login. no error logs.

**Comment by TheWitness** [comment]
Please take this one to the forums for resolution at this point.
