### ISSUE TITLE
about Reporting

### ISSUE THREAD

**Issue by ixinshang** [Cacti/cacti#3453]
i am sorry for my questions.
hi,everone.
i installed cacti 1.2.11 with mariadb on centos7.1(PHP 5.4.16 (cli) (built: Nov  1 2019 16:04:20)).

Cacti Settings (Mail/Reporting/DNS),i set my email account to test. i can send email normal.  i can receive email. 
in Reporting, i made a report. i tried a test to send a report. 
it's successful. but i don't recevie eamils. 
in logs,there are some errors.

CMDPHP MAILER ERROR Backtrace: (/reports_admin.php[58]:reports_form_actions(), /lib/html_reports.php[245]:reports_send(), /lib/html_reports.php[388]:generate_report(), /lib/reports.php[481]:mailer(), /lib/functions.php[3546]:record_mailer_error(), /lib/functions.php[3733]:cacti_debug_backtrace())
CMDPHP MAILER ERROR:

thanks.

**Comment by TheWitness** [comment]
Duplciate of this https://github.com/Cacti/cacti/issues/3454
