### ISSUE TITLE
Graph right axis scale can be negative.

### ISSUE THREAD

**Issue by F-i-f** [Cacti/cacti#3457]
# Describe the bug

In the Cacti 1.211 _Graph_ and _Graph Templates_ pages, the right axis scale is not allowed to be negative.  However rrdtool handles negative scales (in effect flipping the right axis).

## To Reproduce

1. Log in into Cacti.
2. Navigate to the _Console_
3. In the left menu bar, scroll down to _Management_ > _Graphs_
4. Edit any existing graph or create a new one.
5. Scroll down to _Axis Options_.
6. In the _Right Axis_ text field, enter `-1:0`.
7. Click _Save_.

## Expected behavior

The graph should be saved, but instead Cacti refuses to save the graph and issues the error: ` Save Failed due to field input errors (Check red fields).`.

## Desktop (please complete the following information)

- OS: Linux
- Browser: Firefox

## Additional context

The same issue exists for _Graph Template_.

**Comment by TheWitness** [comment]
@F-i-f, that's for your contribution.  I'm going to mark this one resolved.  You can close once you have verified that everything is as you would expect it to be.

**Comment by F-i-f** [comment]
All looks good.  Thank for your responsiveness and work on Cacti.
