### ISSUE TITLE
new remote poller installation fails during connection test, with fix; 1.2.11

### ISSUE THREAD

**Issue by ibatten** [Cacti/cacti#3459]
1.2.11

The connection test for a fresh remote poller fails with 200 parseerror.

The problem appears to be (based on strace-ing the php-fpm process) that the "Content-Length" header in the HTTP response is 0, although the content is a valid {"status":"true"}.

I am not, by any stretch of the imagination, a PHP programmer, but based on blind intuition and a certain amount of other messing around I fixed it by replacing "print json_encode..." with "return json_encode..." in install_test_local_database_connection and install_test_remote_database_connection in install/functions.php.

I also had problems with the final install hanging (running for half an hour, apparently doing nothing other than SELECT ing the install progress variables from the database).  I just deleted all the install_% variables from the database and it appeared then to work.

**Comment by TheWitness** [comment]
Yea, the loop thing has been breaking a lot of upgrades.  To date, we have been unable to reproduce other than there was a bogus package that screwed up some install/upgrades.

**Comment by scline** [comment]
@ibatten manual change also fixed this issue on my install (using centos8 docker container). The issue was also present in 1.2.8 if that helps anything.

**Comment by TheWitness** [comment]
Can someone do a pull request on this one to the 1.2.x branch?
