### ISSUE TITLE
Incorrect default cli php memory_limit

### ISSUE THREAD

**Issue by rprofijt** [Cacti/cacti#3462]
The default cli memory limit of php in Debian/Ubuntu is -1, in include/cli_check.php however, the limit is overwritten (to 500MB) which causes our cli scripts (poller_reindex) to fail.

**Comment by TheWitness** [comment]
Unlimited makes sense to me.  The reindex can take a lot of memory.

**Comment by TheWitness** [comment]
@rprofijt, thanks for reporting.  I've opened the flood gates.  I think it'll be fine though.  Not many systems have less than a dozen or so GB these days.
