### ISSUE TITLE
vdef DB  error -  Unknown column 'graphs' in 'having clause'

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/cacti#3463]
## To Reproduce

1. Go to Present-VDEFs page

2. Check 'has graph' option and then check log, error exist 

2020/04/15  16:41:27 - CMDPHP SQL Backtrace:  (/vdef.php[87]:vdef(),  /vdef.php[874]:get_vdef_records(), /vdef.php[801]:db_fetch_cell(),  /lib/database.php[383]:db_fetch_cell_prepared(),  /lib/database.php[399]:db_execute_prepared())
--
2020/04/15 16:41:27 - CMDPHP ERROR: A DB Cell Failed!, Error: Unknown column 'graphs' in 'having clause'

rhel7 x64
cacti 1.2.11
FF 75

**Comment by TheWitness** [comment]
Good catch @yingbaiibm!

**Comment by TheWitness** [comment]
Thanks @yingbaiibm for all your efforts!
