### ISSUE TITLE
graph not showing in cacti

### ISSUE THREAD

**Issue by kaisarkhan1981** [Cacti/cacti#3464]
Real time graph shows but 5 minutes average graph is not showing. What should be the possible cause? I don't see any error when I ran puller.

**Comment by TheWitness** [comment]
Please take this issue to the forums.  This is a common issue where you have:

1) Not enabled cron
2) Your cron user does not have permission to run
3) Your cron user does not have access to the $CACTI_TOP/rra directory that it requires.

I'm guessing 1) or 2).
