### ISSUE TITLE
Cannot Create New Automation Graph Rules in 1.2.11

### ISSUE THREAD

**Issue by jdcoats** [Cacti/cacti#3468]
Cannot Create New Automation Graph Rules in 1.2.11

1. Go to Automation

2. Click on Graph Rules

3. Click the + sign to create a new rule.

4. Give rule a name and select a data query

5. Note the data query changes back to the 1st query in the list.

I tried both IE and Chrome.

**Comment by bmfmancini** [comment]
I can replicate this as well

work around for now is save the new rule even though it goes back to the first data query 
then change the query to the one you want and click save again

**Comment by jdcoats** [comment]
correct, i copied an existing rule :)

**Comment by bmfmancini** [comment]
this is also an issue on 1.2.9 so its been there for a while

**Comment by TheWitness** [comment]
Would you believe I tired of killing bugs?  Which reminds me to remind Sean about his avatar ;)  Many of us are taking breaks at the moment.  I working hard on a side project.  It's a great plugin that I can not share.  But it's awesome in any event.  If you guys figure things out.  Pull requests are always appreciated.

**Comment by bmfmancini** [comment]
whats wrong with my avatar lol 
ok ill do some digging and see what I can find 

Thanks @TheWitness

**Comment by TheWitness** [comment]
No need to change, well, maybe make it a bit larger.  Love your videos!

**Comment by TheWitness** [comment]
Increase the audio recording level though.... ;)

**Comment by TheWitness** [comment]
Fixed now.
