### ISSUE TITLE
Wrong IP address saved when Cacti is after a VIP or a reverse proxy

### ISSUE THREAD

**Issue by earendilfr** [Cacti/cacti#347]
Currently, Cacti save the IP address of the user that connect to the WebUI.
But, If the Web server is hosted beyond a VIP or a reverse proxy with a NAT configuration, you register the wrong IP address.

I propose this patch to save the X-Forward IP address if it's present in the Web header.

[0001-Allow-to-register-real-IP-of-the-user-beyond-with-th.txt](https://github.com/Cacti/cacti/files/805135/0001-Allow-to-register-real-IP-of-the-user-beyond-with-th.txt)

**Comment by ronytomen** [comment]
Care to do a pull request?

**Comment by cigamit** [comment]
Resolved, in aforementioned pull request.
