### ISSUE TITLE
The SSL option to set the SSL_CA should be optional for Client Connections

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#3474]
# Describe the bug
When an administrator set's up MySQL or MariaDB SSL connectivity, the option to require the Certificate Authority file is optional.  However, in Cacti's SSL database layer its presently mandatory.

## To Reproduce

1. Setup mysql to use openssl security and to make it mandatory but not require a CA file.

2. Specify only the cert and key options for the client connection.

3. Attempt to connect to Cacti

## Expected behavior

Cacti should allow just the key and the cert options when logging in.

**Comment by TheWitness** [comment]
Confirmed that spine does not have this issue.

**Comment by netniV** [comment]
> Confirmed that spine does not have this issue.

Interesting, did I get that right then 👍 Does SSL work OK with spine?

**Comment by TheWitness** [comment]
Should, I'm reticent to test though.
