### ISSUE TITLE
scrollbar missing in device selection

### ISSUE THREAD

**Issue by rprofijt** [Cacti/cacti#348]
In all themes except for classic the scrollbar in the dropdown menu for device selection is missing, so you only have the first 30 devices. This appears to be broken in the graph management but also list/preview modes.

We're on 1.0.4 now but I think I first noticed this in 1.0.3.

**Comment by dsclassen** [comment]
I've noticed this too.

**Comment by cigamit** [comment]
This is not a bug.  If you double click in the device drop down, you will notice that it is 'Autocomplete' enabled.  You can start typing in a device name and the drop down menu will adjust to your selection.  You may think this is unnecessary, except when you have 40k devices, then you will adore this feature.
