### ISSUE TITLE
Device gone

### ISSUE THREAD

**Issue by rcsmota** [Cacti/cacti#3481]
I'm running a Cacti 1.2.11 on a Debian Machine. (new Installation)
One of my devices just disappeared from my list. I can see the graphics in the tree but in the list of devices (Console -> Management -> Devices)  it does not appear.

If enter on another device and put your ID on browser I can enter on configuration  

![imagem](https://user-images.githubusercontent.com/31240306/79748180-e7c86800-8304-11ea-9df7-b30e2c29225b.png)
change only de ID number of 2 to 3 for example. 

Thanks

**Comment by TheWitness** [comment]
This is known issue and resolved already.  Download the host.php from the 1.2.x branch and apply it to your install.  1.2.12 will be released soon.
