### ISSUE TITLE
date time format in Clog is not compatiable with old cacti, and default format is not the same 

### ISSUE THREAD

**Issue by YongBoLiu** [Cacti/cacti#3483]
# Describe the bug

In old cacti (version < 1.0), such as 0.8.6, the data time format in cacti log is m/d/Y h:i:s AM/PM, but after cacti 1.0, the data time format is Y/m/d H:i:s, and if CACTI_DATE_TIME_FORMAT is not defined, the format is Y-m-d H:i:s. 

## To Reproduce

1. Install cacti 0.8.6, Go to CLog page, check in the date time format of logs.

2. Upgrade to cacti 1.2.0, Go to CLog page, check in the date time format of logs.

3. The date time format of log is not in the same.

## Expected behavior

a, After upgrade, the  date time format of log should the same as before. 
b, The default format should be the same, no matter whether CACTI_DATE_TIME_FORMAT  defined or not. 

## Desktop (please complete the following information)

RHEL

## Smartphone (please complete the following information)

Firefox 68

**Comment by cigamit** [comment]
I would imagine a good many things changed since 0.8.6 was released 15 years ago.  You should expect that when you upgrade something so old.

As for the other issue when the variable is not set, we will have to look into it.

**Comment by ddb4github** [comment]
> I would imagine a good many things changed since 0.8.6 was released 15 years ago. You should expect that when you upgrade something so old.
> 
> As for the other issue when the variable is not set, we will have to look into it.

Actually,  the default cacti.log data format history more like table below:

Version| Data Format | Retied
--- | :--- | :--- 
0.8.6 | m/d/Y h:i:s A | 0.8.8h
1.0.0 | Y-m-d H:i:s | 1.1.7
1.1.8 | Y/m/d H:i:s |

**Comment by netniV** [comment]
That would be my doing I suspect to bring the time stamp to be something more universal rather than just American format.

**Comment by netniV** [comment]
Not sure about the slashes though, I use hyphens normally

**Comment by TheWitness** [comment]
I think the 1.0.0 version should be the default.

**Comment by TheWitness** [comment]
Not sure when it broke though.

**Comment by ddb4github** [comment]
Update date format history table as above

**Comment by TheWitness** [comment]
The third column explains.

**Comment by netniV** [comment]
This was originally added as part of https://github.com/cacti/cacti/issues/459
