### ISSUE TITLE
[Security] 1.2.11 shows snmpv3 password is not obfuscated   in device defaults screen

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3484]
Hello 

I noticed that in the device default page the priv passphrase does not  block out the password

![image](https://user-images.githubusercontent.com/13388748/79892172-1e1ee980-83d0-11ea-99fd-b8f195f55c46.png)

Even after you save the form the password is not obfuscated

**Comment by TheWitness** [comment]
Yea, that was by design.  I've wondering if we do need to obfuscate it.

**Comment by TheWitness** [comment]
Maybe only show it when you first create it, then don't show it on subsequent edits...

**Comment by bmfmancini** [comment]
Yea I think it should be uniform maybe show the credentials in clear until you hit submit 
This will make security teams happy
