### ISSUE TITLE
Installation progress log not visible in installation wizard as of latest 1.2.x (0c76515b0)

### ISSUE THREAD

**Issue by nuno-silva** [Cacti/cacti#3490]
Installation wizard completes without displaying any Process Log.
Instead it shows a `--- NO LOG FOUND ---` message.

## To Reproduce

Steps to reproduce the behaviour:

1. Checkout a fresh copy of branch `1.2.x` (as of commit 0c76515b0)

2. Setup database, nginx, php

3. Navigate to the cacti web UI and complete the installation wizard until you reach the last step

4. Confirm and begin installation

5. See that installation completes without any progress log and shows `--- NO LOG FOUND ---`.

I reproduced this issue twice using 0c76515b0 and also tested that it is working as expected using `releases/1.2.11`.

## Expected behaviour

Installation progress log should be displayed in the installation wizard.

## Screenshots

 - End of installation wizard as of 1.2.x 0c76515b0:
![image](https://user-images.githubusercontent.com/6935057/80047081-5b849380-8504-11ea-9bad-27820b21777f.png)

- End of installation wizard as of releases/1.2.11:
![image](https://user-images.githubusercontent.com/6935057/80047129-80790680-8504-11ea-8907-ca8450d19f69.png)

## Desktop

- OS: Gentoo Linux
- Browser: Chromium
  - Version: 80.0.3987.149 (Developer Build) (64-bit)

### Server info
- Gentoo Linux
- nginx version nginx/1.16.1
- PHP 7.2.29
- MariaDB: version 10.2.29-MariaDB
- the setup was exactly the same in both cases

### step_json.php responses

Responses for `POST /cacti/install/step_json.php` (last request):

- 1.2.x 0c76515b0 gives this:
```
{"Mode":null,"Step":"98","Errors":[],"Eula":"1","Prev":{"Text":"Previous","Step":0,"Enabled":false,"Visible":false},"Next":{"Text":"Get Started","Step":-1,"Enabled":true,"Visible":true},"Test":{"Text":"Test Connection","Step":-4,"Enabled":true,"Visible":false},"Theme":"classic","StepData":{"Sections":[]},"Html":"<h2 class='cactiInstallSectionTitle'>Complete<\/h2><p class='cactiInstallSection cactiInstallSectionNormal'>Your Cacti Server v1.2.11 has been installed\/updated.  You may now start using the software.<\/p><\/div><h3 class='cactiInstallSectionTitle'>Process Log<\/h3><div class=\"installSubSection\"><p class='cactiInstallSection cactiInstallSectionCode'>--- NO LOG FOUND ---<\/p>"}
```

- releases/1.2.11 gives:
```
{"Mode":null,"Step":"98","Errors":[],"Eula":"1","Prev":{"Text":"Previous","Step":0,"Enabled":false,"Visible":false},"Next":{"Text":"Get Started","Step":-1,"Enabled":true,"Visible":true},"Test":{"Text":"Test Connection","Step":-4,"Enabled":true,"Visible":false},"Theme":"classic","StepData":{"Sections":[]},"Html":"<h2 class='cactiInstallSectionTitle'>Complete<\/h2><p class='cactiInstallSection cactiInstallSectionNormal'>Your Cacti Server v1.2.11 has been installed\/updated.  You may now start using the software.<\/p><\/div><h3 class='cactiInstallSectionTitle'>Process Log<\/h3><div class=\"installSubSection\"><p class='cactiInstallSection cactiInstallSectionCode'>2020\/04\/23 01:40:23 - INSTALL: always: Installation was started at 2020-04-23 00:37:56, completed at 2020-04-23 00:40:23\n<br\/>2020\/04\/23 01:40:22 - INSTALL: always: Finished INSTALL Process for v1.2.11\n<br\/>2020\/04\/23 01:40:22 - INSTALL: always: Generating RSA Key Pair\n<br\/>2020\/04\/23 01:40:10 - INSTALL: always: Repopulating SNMP Agent cache\n<br\/>2020\/04\/23 01:40:09 - INSTALL: always: Repopulating poller cache\n<br\/>2020\/04\/23 01:40:09 - INSTALL: always: Adding Device to Default Tree\n<br\/>2020\/04\/23 01:40:08 - INSTALL: always: Creating Graphs for Default Device\n<br\/>2020\/04\/23 01:39:56 - INSTALL: always: Device Template for First Cacti Device is 4\n<br\/>2020\/04\/23 01:39:56 - INSTALL: always: Updating automation network (1), mode \"on\" => \"\", subnet \"192.168.1.0\/24\" => 192.168.1.0\/24\"\n<br\/>2020\/04\/23 01:39:55 - INSTALL: always: Mapping Automation Template for Device Template 'Cisco Router'\n<br\/>2020\/04\/23 01:39:55 - INSTALL: always: Mapping Automation Template for Device Template 'Windows Device'\n<br\/>2020\/04\/23 01:39:55 - INSTALL: always: Mapping Automation Template for Device Template 'Net-SNMP Device'\n<br\/>2020\/04\/23 01:39:55 - INSTALL: always: Repairing Automation Rules\n<br\/>2020\/04\/23 01:39:55 - INSTALL: always: Import of Package #6 'Windows_Device.xml.gz' under Profile '3' succeeded\n<br\/>2020\/04\/23 01:39:53 - INSTALL: always: About to import Package #6 'Windows_Device.xml.gz'.\n<br\/>2020\/04\/23 01:39:53 - INSTALL: always: Import of Package #5 'NetSNMP_Device.xml.gz' under Profile '3' succeeded\n<br\/>2020\/04\/23 01:39:20 - INSTALL: always: About to import Package #5 'NetSNMP_Device.xml.gz'.\n<br\/>2020\/04\/23 01:39:20 - INSTALL: always: Import of Package #4 'Local_Linux_Machine.xml.gz' under Profile '3' succeeded\n<br\/>2020\/04\/23 01:39:12 - INSTALL: always: About to import Package #4 'Local_Linux_Machine.xml.gz'.\n<br\/>2020\/04\/23 01:39:12 - INSTALL: always: Import of Package #3 'Generic_SNMP_Device.xml.gz' under Profile '3' succeeded\n<br\/>2020\/04\/23 01:39:08 - INSTALL: always: About to import Package #3 'Generic_SNMP_Device.xml.gz'.\n<br\/>2020\/04\/23 01:39:08 - INSTALL: always: Import of Package #2 'Cisco_Router.xml.gz' under Profile '3' succeeded\n<br\/>2020\/04\/23 01:38:43 - INSTALL: always: About to import Package #2 'Cisco_Router.xml.gz'.\n<br\/>2020\/04\/23 01:38:42 - INSTALL: always: Import of Package #1 'Cacti_Stats.xml.gz' under Profile '3' succeeded\n<br\/>2020\/04\/23 01:37:57 - INSTALL: always: About to import Package #1 'Cacti_Stats.xml.gz'.\n<br\/>2020\/04\/23 01:37:57 - INSTALL: always: Found 6 templates to install\n<br\/>2020\/04\/23 01:37:57 - INSTALL: always: No tables where found or selected for conversion\n<br\/>2020\/04\/23 01:37:56 - INSTALL: always: Starting INSTALL Process for v1.2.11\n<br\/>2020\/04\/23 01:37:56 - INSTALL: always: Setting PHP Option memory_limit = -1\n<br\/>2020\/04\/23 01:37:56 - INSTALL: always: Setting PHP Option max_execution_time = 0\n<br\/>2020\/04\/23 01:37:56 - INSTALL: Checking arguments\n<br\/>04\/23\/2020 01:37:56 - INSTALL: always: Spawning background process: \/usr\/bin\/php '\/var\/www\/cacti-nuno\/htdocs\/cacti\/install\/background.php' 1587602276.1234\n<br\/><\/p>"}
```

- in both cases the following installation logs are created and populated (and end up with exactly the same *number of* bytes):
```
log/install-automation.log
log/install-complete.log
log/install-general.log
log/install-sync.log
```

**Comment by nuno-silva** [comment]
Well, this is awkward: I was not able to reproduce this a third/fourth/fifth time -- this time using 46874b56af, just 2 commits ahead of 0c76515.

Won't close for now. Could this be a non-deterministic issue?

**Comment by nuno-silva** [comment]
Indeed, in the test database (from a dump of the second install):
```
('path_boost_log',''),
('path_cactilog','/var/www/localhost/htdocs/cacti/log/cacti.log'),
('path_stderrlog','/var/www/cacti-nuno/htdocs/cacti/log/cacti_stderr.log'),
```

I don't think I changed these values during the install. Is it possible the default was computed wrongly or is it more likely I somehow changed them without noticing?

**Comment by netniV** [comment]
If you use the same database from two different locations, a lot of our code will now utilise REALPATH which means that we know the precise location of what we are updating.  If you then switch to using a test site but the live database, things may not work as expected.  Always try to keep a separate database for each install location.  Generally, symlinks will be resolved these days, but there may be an issue there somewhere.

**Comment by nuno-silva** [comment]
Thanks for your reply.

The first and second "test" installs (and all others I mentioned, except the production install, which I didn't touch) were fresh installs with a clean database. However, since I was not able to reproduce this anymore, it's more likely that I perhaps changed the log path accidentally and don't remember. I do remember touching the "spine config path" field in the wizard, which is right above the "cacti log path" field.

The production database happens to be called "cacti", which is the default. However, the password is different from the default, so I don't think the test install(s) was able to access it even if I somehow were to forget to change the default config in the test install(s).

I wasn't using symlinks either.

If there's no other explanation, and if no one else reports anything related, I think this can be closed.

**Comment by netniV** [comment]
OK, thanks for the feedback.  If you do find a way to reproduce it though, let me know as I am always keen to have a clean installer 👍 We have just had a rough time with the last few patches trying to correct issues and introducing more as a result despite our testing.

**Comment by netniV** [comment]
One other thought, if this happens around your log rotation time, it could also happen as it uses the cacti.log (don't know if I mentioned that already).

**Comment by vKnmnn** [comment]
I have noticed my log isn't visible in the installer. I always thought it is because i keep my log in a non-default location and put a symlink from `/usr/share/cacti/site/log -> /logs`

**Comment by nuno-silva** [comment]
@vKnmnn what are the owner/permissions on `/logs`? Is the PHP user (e.g. `www-data`, `nobody`, ..., depending on your distro) able to create files in that folder? Is it the same user that runs the poller?

**Comment by vKnmnn** [comment]
the permissions on /logs are `drwxr-xr-x   7 www-data adm        4096 Apr 27 10:34 logs`
www-data. adm is the administration group that should be able to see the logs too. spine also runs as www-data.
