### ISSUE TITLE
percent sign(%) is doubled in graph item of AREA type with text

### ISSUE THREAD

**Issue by YongBoLiu** [Cacti/cacti#3496]
# Describe the bug

Edit a graph template, add a graph item, choose the Graph Item Type with 'AREA', Input text such as 'aaa %' in the text format, then save.
Check the graphs base on the graph template, the text in the graph shows 'aaa %%'.

## To Reproduce

1. Go to console->templates->graph.  edit: Linux - Memory Usage graph template.

2.  Add a graph item, choose the Graph Item Type with 'AREA', Input text such as 'aaa %' in the text format, then save.

3. Go to console->management->graphs. Check the graphs base on the template.

4. See the text is 'aaa %%'.

## Expected behavior

The percent sign(%) should the same as input, not be doubled.

## Desktop (please complete the following information)

Linux REHL7

## Smartphone (please complete the following information)

Firefox68

**Comment by netniV** [comment]
I have made a comment on the PR but I will repeat it here.  I believe that this is incorrect.  We corrected the use of being able to use % in the comments/legends and this regresses that.  In reality, the template which has the problem should be updated.
