### ISSUE TITLE
When viewing Graphs, can not switch between list, preview and tree submodes

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#3502]
Tiny issue here. I'm on 1.2.11.

Select list view.
Select some graphs.
Click view.
You are now taken to the graph preview ... but the list view tab is still selected. So you can't go back to it. You need to select the preview tab, then select the list view tab, to get back to the list. After an auto refresh however, the preview tab is appropriately selected, and you can return to list view normally. 

I'm using the dark theme.

**Comment by TheWitness** [comment]
Thanks for pointing this out @eschoeller.

**Comment by eschoeller** [comment]
Anytime:)
