### ISSUE TITLE
Upgrade from 1.2.10 to 1.2.11 stuck at 41% under CentOS 7

### ISSUE THREAD

**Issue by jackouille-ch** [Cacti/cacti#3503]
I perform a yum upgrade and here is my upgrade status:
===================================================================================================================
 Package                    Arch                Version                              Repository               Size
===================================================================================================================
Updating:
 cacti                      noarch              1.2.11-1.el7                         epel                     20 M
 cacti-spine                x86_64              1.2.11-1.el7                         epel                     73 k
 php-PsrLog                 noarch              1.1.3-1.el7                          epel                     14 k
 php-pear                   noarch              1:1.10.12-1.el7.remi                 remi-php73              362 k
 php-phpseclib              noarch              2.0.27-1.el7                         epel                    217 k

All packages were installed correctly, Cacti asked to upgrade, all previous steps were fine and I'm now stuck here:
![image](https://user-images.githubusercontent.com/35721406/80275008-d7d2ce80-86de-11ea-9939-79b1cf151e50.png)

But if I check on another tab, it works fine:
![image](https://user-images.githubusercontent.com/35721406/80275036-005ac880-86df-11ea-9a31-0cc3d47528fd.png)

What should I do to achieve the install process ?

**Comment by jackouille-ch** [comment]
After 30 minutes I disconnect from admin, login in again and it is now working.
I also restart install and got the following messages:
![image](https://user-images.githubusercontent.com/35721406/80275570-714faf80-86e2-11ea-9d46-73269be3b92a.png)

**Comment by TheWitness** [comment]
Yea, check your templates if you choose to import the updated packages.  If you made any customization's, they will be lost.
