### ISSUE TITLE
After successfully logging in, a user can become automatically logged out again

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#3506]
# Describe the bug
"Login as Regular User" always forward to "Automatic Logout....timeout"

## To Reproduce
1. Configure "Guest User" under Console-->Settings-->Authentication
2. Logout
3. Directly access cacti/graph_view.php with login action
4. Click `Login as Regular User` like ScreenShot#1
5. After a while, browser show as ScreenShot#2

## Expected behavior
Show login page with username password input fields

## Screenshots
![image](https://user-images.githubusercontent.com/17589018/80303152-fa4d1080-87e0-11ea-85b2-a70119970c9a.png)
![image](https://user-images.githubusercontent.com/17589018/80303162-01741e80-87e1-11ea-905a-d75fb36b2884.png)

## Desktop (please complete the following information)
- OS: Windows 10 1909
- Browser Chrome
- Version 81

**Comment by TheWitness** [comment]
The whole login/logout logic needs to be redone IMHO.  It's brutally complex and should not be.

**Comment by netniV** [comment]
Agree.  We should simplify it into API calls in 1.3
