### ISSUE TITLE
special charactes in SNMPv3 Passwords

### ISSUE THREAD

**Issue by righter83** [Cacti/cacti#351]
Hi

I'm using Cacti 1.0.4 and have the problem, that I have SNMPv3 devices with special characters (!) in the password and privacy phrase. If i escape it on the shell it is workin fine. In Cacti it is not workin.

Is there a solution to escape the password in the GUI?

**Comment by righter83** [comment]
Hmm in the mysql DB are the passwords correct but in the Frontend I got this errer:

Warning: SNMP::get(): Fatal error: Timeout in /var/www/cacti.righter.ch/html/lib/snmp.php on line 497
SNMP error

**Comment by cigamit** [comment]
Please submit the output of the following:

php --version
php -m

Thanks!

**Comment by righter83** [comment]
Sure:
```

PHP 7.0.16-1~dotdeb+8.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.16-1~dotdeb+8.1, Copyright (c) 1999-2017, by Zend Technologies

[PHP Modules]
apcu
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
snmp
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

```

**Comment by cigamit** [comment]
Okay, thanks for the input.  This would then be in the SNMP module.  If you remove php-snmp, does the problem still occur?

**Comment by righter83** [comment]
No First error disappears then but there ist still the SNMP error but no other information
`SNMP error`

**Comment by cigamit** [comment]
I've just updated the snmp module.  You can add php-snmp back, and try again.  You may have to instrument the code.  There is a function called cacti_snmp_session() that is of key importance and the call to setSecurity() you should cacti_log() the settings from the database and verify that they are accurate.

**Comment by righter83** [comment]
Hi I've just fetched the new lib/snmp.php and reinstalled php-snmp and got now 2 errors:

```
2017-03-05 16:56:33 - ERROR PHP WARNING: SNMP::get(): Fatal error: Timeout in file: /var/www/cacti.righter.ch/html/lib/snmp.php  on line: 504
2017-03-05 16:56:33 - CMDPHP PHP ERROR WARNING Backtrace: (/host.php: 111 api_device_ping_device)(/lib/api_device.php: 364 cacti_snmp_session_get)(/lib/snmp.php: 504 get)(CactiErrorHandler)(/lib/functions.php: 4259 cacti_debug_backtrace)
2017-03-05 16:56:34 - ERROR PHP WARNING: SNMP::get(): Fatal error: Timeout in file: /var/www/cacti.righter.ch/html/lib/snmp.php  on line: 509
2017-03-05 16:56:34 - CMDPHP PHP ERROR WARNING Backtrace: (/host.php: 111 api_device_ping_device)(/lib/api_device.php: 364 cacti_snmp_session_get)(/lib/snmp.php: 509 get)(CactiErrorHandler)(/lib/functions.php: 4259 cacti_debug_backtrace)
```

**Comment by righter83** [comment]
Ooooh wait now it's workin....
sorry my colleague has reconfigured something on the router on friday.
so your patch is workin! thanks for your awesome fast patch!!

**Comment by cigamit** [comment]
Okay, that error was due to some bad code.  I have done another update to remove that duplicated code.  Thanks for testing!
