### ISSUE TITLE
Missing SNMPv3 auth data on script server Input Fields when importing/updating a device/graph template

### ISSUE THREAD

**Issue by nuno-silva** [Cacti/cacti#3516]
# Describe the bug

After importing/updating a device/graph template, the script server for the graph's input method runs with wrong/missing Input Fields. See Debugging info below for more details.

I have had this issue in two different installs (1.2.11 and 1.2.x) and was able to reproduce it in a fresh install.

Even though I only tried debugging this with an SNMPv3, it affected all graphs of this type, including SNMPv2/v3, in the 1.2.11 install (in this case, it was a template update on an old/production cacti install).

## To Reproduce

Steps to reproduce the behaviour:

1. Install cacti
   1. Extract cacti from source (I used 1.2.x at 6fa429c3124)
   2. Edit include/config.php with DB settings
   3. Create DB:
   ```
   create database if not exists cacti_nuno2;
   GRANT ALL ON cacti_nuno2.* to cactiuser2@'localhost' IDENTIFIED BY 'cactiuser2';
   grant select on mysql.time_zone_name to  cactiuser2@'localhost' IDENTIFIED BY 'cactiuser2';
   flush privileges;
   ```
   4. Populate DB:
   ```
   mysql -p -v cacti_nuno2 < /var/www/cacti-nuno2/htdocs/cacti/cacti.sql
   ```
   5. Configure webserver
   6. Point your browser to cacti
   7. Complete the install: probably not relevant, but these were my steps: change password, Classic theme, English, Accept GPL, Begin, Checks ok, Next, New Primary Server, Next, All folders are writable (including `/var/www/cacti-nuno2/htdocs/cacti/log/`), Next, Bin locations are OK (including `/var/www/cacti-nuno2/htdocs/cacti/log/cacti.log`), Next, I have read this statement, Next, 1 Minute Collection, Every Minute, uncheck "Scan Mode", Next, all templates are selected, Next, Collation/Tables OK, Next, Confirm Installation, Install, logs appear in wizard (`04/28/2020 11:39:58 - INSTALL: always: Spawning background process: /usr/bin/php '/var/www/cacti-nuno2/htdocs/cacti/install/background.php' 1588070397.967`,...), Wait..., Get Started
   8. Activate poller cron: `* *  * * *  nobody  php -q /var/www/cacti-nuno2/htdocs/cacti/poller.php >/dev/null`
2. Let the poller run for a couple of cycles
3. Add an SNMPv3 device using template "Net-SNMP Device", fill in the description, hostname=myhost.example.com, select SNMPv3, authPriv, user=cacti, auth proto=SHA, password=AAAAA, Privacy Protocol=AES, Passphrase=BBBBB; everything else is the default; Create.
    - device is created with 11 graphs
4. Add the device to the root of the default tree
5. Let the poller run for a few cycles and confirm graphs are working
6. Download a new graph template, such as https://github.com/netniV/cacti-netsnmp-memory (I used https://github.com/netniV/cacti-netsnmp-memory/commit/f00431317331ee3bb03a961b1050baca311f4716)
7. Follow the Installation instructions in the https://github.com/netniV/cacti-netsnmp-memory/blob/f00431317331ee3bb03a961b1050baca311f4716/README.md#installation (including importing the template and adding it to the SNMPv3 device)
8. After adding the "Host Memory - ucd/net - Memory Usage" template to the device, the graph is created automatically
9. Let the poller run for a few cycles and confirm the new graph is populated with all zeroes and no real data
10. Devices -> (select the device) -> Enable Device Debug
11. Wait for the poller to run and check the log
12. Look for the a line containing "ss_netsnmp_memory" and verify that the script server was run with too few arguments:

```
2020-04-28 12:07:04 - POLLER: Poller[Main Poller] Device[myhost] DS[myhost - Memory Usage] Graphs[myhost - Memory Usage] SERVER: /var/www/cacti-nuno2/htdocs/cacti/scripts/ss_netsnmp_memory.php ss_netsnmp_memory 'myhost.example.com' '3' 'public' '161' '500' 'cacti' 'AAAAA' , output: totalReal:0 availReal:0 totalSwap:0 availSwap:0 memBuffer:0 memCached:0 usedReal:0 usedSwap:0
```

The data input method is:
```
<path_cacti>/scripts/ss_netsnmp_memory.php ss_netsnmp_memory <hostname> <snmp_ver> <snmp_community> <snmp_port> <snmp_timeout> <snmp3_username> <snmp3_password> <snmp3_authprot> <snmp3_privpass> <snmp3_privprot> <snmp3_context>
```
so `<snmp3_authprot> <snmp3_privpass> <snmp3_privprot> <snmp3_context>` are missing.

## Expected behaviour

The script server should run `ss_netsnmp_memory` with all the input fields properly populated.

I don't think this is a problem with the template. All the input fields seem fine and are used by other input methods.

## Desktop

- OS: Gentoo Linux
- Browser: Chromium
  - Version: 81.0.4044.122 (Developer Build) (64-bit)

### Server info
- Gentoo Linux
- nginx version nginx/1.16.1
- PHP 7.2.29
- MariaDB: version 10.2.29-MariaDB
- Cacti 1.2.x at 6fa429c3124
- https://github.com/netniV/cacti-netsnmp-memory/commit/f00431317331ee3bb03a961b1050baca311f4716

### Debugging info

I spent a couple days trying to debug this. It wasn't fun.

Here are a few notes I took:

> call stack (in reverse order):
> 
>  - ss_netsnmp_memory
>  - script_server.php `call_user_func_array`
>  - cmd.php `case POLLER_ACTION_SCRIPT_PHP`
>  - `$item['arg1']` which comes from table `poller_item`
>  - lib/utility.php `update_poller_cache` `DATA_INPUT_TYPE_PHP_SCRIPT_SERVER` calls `api_poller_cache_item_add` to populate `poller_item` via `poller_update_poller_cache_from_buffer`
>    - lib/functions.php `get_full_script_path` fetches `FROM data_input_fields LEFT JOIN data_input_data`, and `data_input_data` is incomplete
>
>
>  - cli/rebuild_poller_cache.php also calls `poller_update_poller_cache_from_buffer`: after recreating the graph (or saving the DS in the UI, I'm not sure which one triggered this), the fields already appear in the JOIN but are empty

My conclusion is that when the `get_full_script_path` functions performs `data_input_fields LEFT JOIN data_input_data`, `data_input_data.data_template_data_id` is `NULL` for the affected data input fields:
https://github.com/Cacti/cacti/blob/6fa429c3124/lib/functions.php#L1573-L1582

This means the affected rows are in the `data_input_fields` table but have no value in the `data_input_data` table.

Doing the `LEFT JOIN` myself, I can see this:

```
MariaDB [cacti_nuno2]> SELECT data_input_data.data_template_data_id,data_input_fields.data_name,
 data_input_data.value, data_input_data.t_value,data_input_fields.input_output
 FROM data_input_fields LEFT JOIN data_input_data
 ON (data_input_fields.id = data_input_data.data_input_field_id) 
 WHERE data_input_fields.data_input_id  =  32  and data_input_fields.input_output='in'
 order by  data_input_data.data_template_data_id ;
+-----------------------+----------------+--------------------+---------+--------------+
| data_template_data_id | data_name      | value              | t_value | input_output |
+-----------------------+----------------+--------------------+---------+--------------+
|                  NULL | snmp3_authprot | NULL               | NULL    | in           |
|                  NULL | snmp3_privpass | NULL               | NULL    | in           |
|                  NULL | snmp3_context  | NULL               | NULL    | in           |
|                  NULL | snmp3_privprot | NULL               | NULL    | in           |
|                    85 | snmp_ver       |                    |         | in           |
|                    85 | snmp_timeout   |                    |         | in           |
|                    85 | snmp_port      |                    |         | in           |
|                    85 | hostname       |                    |         | in           |
|                    85 | snmp_community |                    |         | in           |
|                    85 | snmp3_password |                    |         | in           |
|                    85 | snmp3_username |                    |         | in           |
|                    86 | snmp_ver       | 3                  | NULL    | in           |
|                    86 | snmp_timeout   | 500                | NULL    | in           |
|                    86 | snmp_port      | 161                | NULL    | in           |
|                    86 | hostname       | myhost.example.com | NULL    | in           |
|                    86 | snmp_community | public             | NULL    | in           |
|                    86 | snmp3_password | AAAAA              | NULL    | in           |
|                    86 | snmp3_username | cacti              | NULL    | in           |
+-----------------------+----------------+--------------------+---------+--------------+
18 rows in set (0.00 sec)
```

-  `data_input_data`:

```
MariaDB [cacti_nuno2]> select * from data_input_data where data_template_data_id in (85,86);
+---------------------+-----------------------+---------+--------------------+
| data_input_field_id | data_template_data_id | t_value | value              |
+---------------------+-----------------------+---------+--------------------+
|                 101 |                    85 |         |                    |
|                 102 |                    85 |         |                    |
|                 103 |                    85 |         |                    |
|                 106 |                    85 |         |                    |
|                 107 |                    85 |         |                    |
|                 108 |                    85 |         |                    |
|                 114 |                    85 |         |                    |
|                 101 |                    86 | NULL    | 3                  |
|                 102 |                    86 | NULL    | 500                |
|                 103 |                    86 | NULL    | 161                |
|                 106 |                    86 | NULL    | myhost.example.com |
|                 107 |                    86 | NULL    | public             |
|                 108 |                    86 | NULL    | AAAAA              |
|                 114 |                    86 | NULL    | cacti              |
+---------------------+-----------------------+---------+--------------------+
```

- `data_input_fields`:

```
MariaDB [cacti_nuno2]> select id,data_input_id,data_name from data_input_fields where data_input_id=32;
+-----+---------------+----------------+
| id  | data_input_id | data_name      |
+-----+---------------+----------------+
|  99 |            32 | snmp3_authprot |
| 100 |            32 | totalReal      |
| 101 |            32 | snmp_ver       |
| 102 |            32 | snmp_timeout   |
| 103 |            32 | snmp_port      |
| 104 |            32 | memCached      |
| 105 |            32 | availReal      |
| 106 |            32 | hostname       |
| 107 |            32 | snmp_community |
| 108 |            32 | snmp3_password |
| 109 |            32 | availSwap      |
| 110 |            32 | usedReal       |
| 111 |            32 | memBuffer      |
| 112 |            32 | usedSwap       |
| 113 |            32 | totalSwap      |
| 114 |            32 | snmp3_username |
| 115 |            32 | snmp3_privpass |
| 116 |            32 | snmp3_context  |
| 117 |            32 | snmp3_privprot |
+-----+---------------+----------------+
19 rows in set (0.00 sec)
```

### Workaround

While I was not able to trace the source of the issue, I found that just by going to `http://cacti-nuno2/cacti/data_templates.php?action=template_edit&id=62` and saving the `ucd/net - Memory Usage` Data Source template **without changing anything** fixes the DB and **makes the graph start working**:

```
MariaDB [cacti_nuno2]> SELECT data_input_data.data_template_data_id,data_input_fields.data_name, data_input_data.value, data_input_data.t_value,data_input_fields.input_output
 FROM data_input_fields LEFT JOIN data_input_data
 ON (data_input_fields.id = data_input_data.data_input_field_id) 
 WHERE data_input_fields.data_input_id  =  32 
 and data_input_fields.input_output='in' order by  data_input_data.data_template_data_id ;
+-----------------------+----------------+--------------------+---------+--------------+
| data_template_data_id | data_name      | value              | t_value | input_output |
+-----------------------+----------------+--------------------+---------+--------------+
|                    85 | snmp3_authprot |                    |         | in           |
|                    85 | snmp_ver       |                    |         | in           |
|                    85 | snmp_timeout   |                    |         | in           |
|                    85 | snmp_port      |                    |         | in           |
|                    85 | hostname       |                    |         | in           |
|                    85 | snmp_community |                    |         | in           |
|                    85 | snmp3_password |                    |         | in           |
|                    85 | snmp3_username |                    |         | in           |
|                    85 | snmp3_privpass |                    |         | in           |
|                    85 | snmp3_context  |                    |         | in           |
|                    85 | snmp3_privprot |                    |         | in           |
|                    86 | snmp3_authprot | SHA                | NULL    | in           |
|                    86 | snmp_ver       | 3                  | NULL    | in           |
|                    86 | snmp_timeout   | 500                | NULL    | in           |
|                    86 | snmp_port      | 161                | NULL    | in           |
|                    86 | hostname       | myhost.example.com | NULL    | in           |
|                    86 | snmp_community | public             | NULL    | in           |
|                    86 | snmp3_password | AAAAA              | NULL    | in           |
|                    86 | snmp3_username | cacti              | NULL    | in           |
|                    86 | snmp3_privpass | BBBBB              | NULL    | in           |
|                    86 | snmp3_context  |                    | NULL    | in           |
|                    86 | snmp3_privprot | AES128             | NULL    | in           |
+-----------------------+----------------+--------------------+---------+--------------+

```

```
2020-04-28 12:55:04 - POLLER: Poller[Main Poller] Device[myhost] DS[myhost - Memory Usage] Graphs[myhost - Memory Usage] SERVER: /var/www/cacti-nuno2/htdocs/cacti/scripts/ss_netsnmp_memory.php ss_netsnmp_memory 'myhost.example.com' '3' 'public' '161' '500' 'cacti' 'AAAAA' 'SHA' 'BBBBB' 'AES128' '', output: totalReal:98957272 availReal:88825212 totalSwap:10485756 availSwap:10485756 memBuffer:1312108 memCached:6534892 usedReal:17979060 usedSwap:0
```

I hope this helps.

**Comment by TheWitness** [comment]
We need to get a move on packaging.

**Comment by netniV** [comment]
I will follow your stpes and then do a database comparison upon save to see if I can spot what difference that would make.

**Comment by nuno-silva** [comment]
Thank you!

Here's a diff for mine, maybe it helps: [diff.diff.gz](https://github.com/Cacti/cacti/files/4553472/diff.diff.gz). It's the DB that I used in the bug report, so the IDs will match with the examples in the report. Also, the poller was running for a few hours after, but I did not change anything else.

**Comment by netniV** [comment]
This is still with me.

**Comment by netniV** [comment]
So I was expecting to have to do a lot of long tedious bug deep dive diagnosis on this which is why I had not had enough time allocated to look into it yet.  However, as I searched through the code, I realised that the following are NOT valid substitute fields and are no where in our code:

- snmp3_authprot
- snmp3_privpass
- snmp3_privprot
- snmp3_context

So, these are either input fields specified on templates or invalid host substitution codes.  If you edit the data input method for the template, you will likely find that it has a 'Special Type Code' on the data input method's fields.  Hovering over the question mark will give you a list of all the valid type codes.

To verify the list of valid host fields that can be substituted see the first few lines of code in `include/global_form.php` which performs an API call to ensure that any plugin added fields are added to valid host fields.  Ignoring plugins the default valid names are: 

- hostname
- host_id
- location
- snmp_community
- snmp_username
- snmp_password
- snmp_auth_protocol
- snmp_priv_passphrase
- snmp_priv_protocol
- snmp_context
- snmp_engine_id
- snmp_version
- snmp_port
- snmp_timeout
- external_id

Any invalid codes are simply removed without error.  I do wonder if we should start reporting unsubstituted fields in 1.3 though to help highlight this issue.  It also raises awareness of another issue where we are trying to get away from having plugins modify core tables, though that's one for the future.  

So, ultimately, the only bug here is with the template itself.

**Comment by netniV** [comment]
In fact, I found this [bug fix](https://github.com/netniV/cacti-netsnmp-memory/issues/4) from the current maintainer of that template so it looks like I was correct 👍
