### ISSUE TITLE
Sometimes, poller_reports.php fall in function reports_interval_start with CPU UT 100%, and never return.

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#3517]
# Describe the bug
Sometimes,  poller_reports.php fall in function `reports_interval_start` with CPU UT 100%, and never return.

## To Reproduce
Not sure now because mysql  also crashed due to no disk space because poller_reports.php generated huge log(1TB)
I'll try to reproduce at later.
## Additional context

part of  cacti.log:
 * _2020/04/28 10:35:41 - CMDPHP PHP ERROR NOTICE Backtrace:  (/poller_reports.php[143]:generate_report(), /lib/reports.php[497]:reports_interval_start(), /lib/reports.php[240]:reports_interval_start(), /lib/reports.php[240]:reports_interval_start(), /lib/reports.php[240]:reports_interval_start(), /lib/reports.php[240]:reports_interval_start(), /lib/reports.php[240]:reports_interval_start(), /lib/reports.php[240]:reports_interval_start(), /lib/reports.php[240]:reports_interval_start(), /lib/reports.php[240]:reports_interval_start(), /lib/reports.php[240]:reports_interval_start(), /lib/reports.php[240]:reports_interval_start(), /lib/reports.php[240]:reports_interval_start(), /lib/reports.php[240]:reports_interval_start(), /lib/reports.php[240]:reports_interval_start(), /lib/reports.php[240]:reports_interval_start(), /lib/reports.php[240]:reports_interval_start(), /lib/reports.php[240]:reports_interval_start(), /lib/reports.php[240]:reports_interval_start(), /lib/reports.php[240]:_

**Comment by TheWitness** [comment]
Ouch, keep us posted.  There is interlocking in 1.2.12 to minimize race conditions, but disk full can be problematic.

**Comment by TheWitness** [comment]
That looks like it's generated from a GUI client as the main IF block is checking for the presence of the $_REQUEST variable which should not be present in the CLI.

**Comment by TheWitness** [comment]
Wow, just saw the recursion loop from an interval that is invalid.

**Comment by TheWitness** [comment]
Fixed.
