### ISSUE TITLE
[1.2.11 ]Devices under Management menu don't show up

### ISSUE THREAD

**Issue by jpobeda** [Cacti/cacti#3519]
Today I upgraded from 1.2.10 to 1.2.11.

The upgrade got stuck at 42% but apparently it finished "ok"

Now my problem is, when I go to Console>Management and click on devices I only get three out of 138.

If I go to Graphs tab and browse the tree I can see them all (I guess) and with their respective graphs.

If I search for something under Management/devices
The URL it constructs is:
```
https://cacti.domain.com/cacti/host.php?host_status=-1&host_template_id=-1&site_id=-1&criticality=-1&poller_id=-1&rows=-1&filter=somedevice&page=undefined&
```

I'm a bit confused about this 'page'. See picture below.
![image](https://user-images.githubusercontent.com/13456559/80551903-1f2bc880-8a19-11ea-86c0-8a19d627863b.png)

I haven't seen this problem before so I got not a single clue on where to start looking at.

What sort of details do you guys need? I couldn't find any error on cacti.log except for this one which based on the timestamp was at the time I was performing the upgrade. 

`29/Apr/2020 08:29:37 - CMDPHP ERROR: A DB Exec Failed!, Error: Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. You have to change some columns to TEXT or BLOBs`

```
Currently running CentOS 7
Cacti 1.2.11
Spine 1.2.11
Apache 2.4.6 + PHP 5.4.6
MariaDB 5.5
```

**Comment by TheWitness** [comment]
The db_execute error is due to the fact that you made a large backup file in the Cacti path that Cacti is choking on.  The location issue is due to a bug that will be fixed once @netniV get's 1.2.12 released this weekend.  I think you just need to update host.php from the 1.2.x branch.
