### ISSUE TITLE
Can no longer login

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#3526]
I had three Cacti instances running ... one was at 1.2.9 the other ones at older versions (perhaps down to 1.1.x) I upgraded all three a few days ago and had no issues. Now, I cannot login to any of them. I've increased logging to DEVEL, but I get nothing back in the log. Entering valid/invalid login information drops me right back to the login screen with no indication of the problem. I tried changing the admin password - no luck.

**Comment by cigamit** [comment]
Did you comment out "$cacti_cookie_domain" in the config.php?

**Comment by eschoeller** [comment]
I never had a $cacti_cookie_domain in config.php
I just copied over my old config. 
A couple of my browsers could still interact with Cacti. But they started to degrade in their ability to function. I'm actually diagnosing a potentially serious problem with some batteries so I quickly downgraded back to 1.2.9 and I can login again. Hopefully the DB doesn't get too screwed up by that.
I left the other two instances at 1.2.11. I don't need to login to those, so I can still tinker around and try to fix them

**Comment by eschoeller** [comment]
OK, on an entirely different machine, with a very fresh install of debian 10, I got this after the first login:

![image](https://user-images.githubusercontent.com/12864741/80781088-55a73780-8b2e-11ea-9812-f6612dcd5af2.png)

Then I go to login again, and it works. I don't understand that. I also noticed that I do not have a:
$path_csrf_secret = '/usr/share/cacti/resource/csrf-secret.php';
in my config but it looks like that's generally commented out anyway.

**Comment by eschoeller** [comment]
haha. I just got that same message on the 1.2.9 instance I just downgraded too. What the heck. So, on all three of these instances i have this set:
```
$cacti_session_name = 'Cacti';
```
I have done this for years and I think it's triggered small little quirks here and there, but nothing this serious. maybe now I really do need to have these set differently.

**Comment by eschoeller** [comment]
Newer machine browser:
```
Chromium	80.0.3987.162 (Developer Build) built on Debian 10.3, running on Debian 10.3 (64-bit)
Revision	f2c5dd6138153bb0658091205bd1a1717f16081a-refs/branch-heads/3987@{#1034}
OS	Linux
JavaScript	V8 8.0.426.29
Flash	(Disabled)
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36
Command Line	/usr/lib/chromium/chromium --show-component-extension-options --enable-gpu-rasterization --no-default-browser-check --disable-pings --media-router=0 --enable-remote-extensions --load-extension --flag-switches-begin --flag-switches-end --disable-webrtc-apm-in-audio-service --file-url-path-alias=/gen=/usr/lib/chromium/gen
Executable Path	/usr/lib/chromium/chromium
Profile Path	/home/eric/.config/chromium/Default
```

**Comment by eschoeller** [comment]
I get the CSRF timeout message now on the older browser
```
Chromium	75.0.3770.90 (Official Build) Built on Ubuntu , running on Ubuntu 18.10 (64-bit)
Revision	a6dcaf7e3ec6f70a194cc25e8149475c6590e025-refs/branch-heads/3770@{#1003}
OS	Linux
JavaScript	V8 7.5.288.23
Flash	(Disabled)
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/75.0.3770.90 Chrome/75.0.3770.90 Safari/537.36
Command Line	/usr/lib/chromium-browser/chromium-browser --enable-pinch --flag-switches-begin --flag-switches-end
Executable Path	/usr/lib/chromium-browser/chromium-browser
Profile Path	/home/eric/.config/chromium/Default
```

**Comment by eschoeller** [comment]
I have a include/vendor/csrf/csrf-secret.php file, it's owned by the webserver user, but it's empty.

**Comment by netniV** [comment]
There was a bug in earlier versions where the CSRF secret was being forced to be created but not properly.  It only really needs to be created to add a custom key for CSRF-based tokens.  Most people do not need it from what I have seen.

**Comment by TheWitness** [comment]
If you make that directory writable for just a moment, and refresh your Cacti page, the new file, properly populated will appear like magic.

**Comment by eschoeller** [comment]
I'm getting these CSRF messages just about all the time now. I think it has something to do with the fact that I use the same browser to login to multiple different instances of Cacti that run on the same webserver.

**Comment by netniV** [comment]
I run multiple instances without CSRF issues.

**Comment by eschoeller** [comment]
I think I finally got a csrf-secret file. Maybe that will fix this

**Comment by eschoeller** [comment]
Still having problems after installing a csrf-secret file, and now I have another user who is having the endless login loop problem too. He's looking deep into the PHP sessions and cookies. He was able to break his way back in with creating a new cookie and inserting it into his browser, or something.

**Comment by TheWitness** [comment]
Eric, I'm going to remove a same site cookie hack that was supposed to work for pre php7.3 later this morning.  I've recently read that it will or is already broken in some browsers.

**Comment by eschoeller** [comment]
OK cool, I'll be happy to update and keep testing.

**Comment by TheWitness** [comment]
Okay, update include/global.php from the 1.2.x branch.  I'm thinking this will cure a bunch of ills.
