### ISSUE TITLE
Why is Cacti showing an empty graph???

### ISSUE THREAD

**Issue by hasnaouikhouloud** [Cacti/cacti#3528]
# i have created a graph in Cacti, It is showing device up, It is creating rrd file. (RRDTool says OK). -) Showing the graph, but it's empty.
and when I turn on data source info mode of graphes I get :
-value NAN  
and cacti log show:
05/02/2020 14:09:54 - DBCALL ERROR: SQL Assoc Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'rows FROM data_source_profiles AS dsp INNER JOIN data_source_profiles_cf AS ds' at line 1
05/02/2020 14:09:54 - DBCALL ERROR: SQL Assoc Failed!, Error:1064, SQL:'SELECT dspc.consolidation_function_id AS cf, dsp.x_files_factor AS xff, dspr.steps AS steps, dspr.rows AS rows FROM data_source_profiles AS dsp INNER JOIN data_source_profiles_cf AS dspc ON dsp.id=dspc.data_source_profile_id INNER JOIN data_source_profiles_rra AS dspr ON dsp.id=dspr.data_source_profile_id WHERE dsp.id = ? ORDER BY dspc.consolidation_function_id, dspr.steps'
05/02/2020 14:09:54 - CMDPHP PHP ERROR WARNING Backtrace: (/data_sources.php: 77 ds_edit)(/data_sources.php: 1062 rrdtool_function_info)(/lib/rrd.php: 2395 sizeof)(CactiErrorHandler)(/lib/functions.php: 4585 cacti_debug_backtrace)
05/02/2020 14:09:54 - ERROR PHP WARNING: sizeof(): Parameter must be an array or an object that implements Countable in file: /usr/share/cacti/site/lib/rrd.php on line: 2395 

Tuchnical support:
Cacti Version 	1.1.38
PHP Version 	7.2.24
ubuntu          18.04.4
 MariaDB       10.4.12

**Comment by TheWitness** [comment]
The only way this will be fixed is by updating to 1.2.12.  It's fixed there.
