### ISSUE TITLE
Broadcast & Multicast Packet counter missing in 1.0.4 interface.xml

### ISSUE THREAD

**Issue by jenhek** [Cacti/cacti#353]
Hi,

it was in 0.8.8.h AFAIR. Would be nice to have it back again:

213a214,241
>  		<ifInMulticastPkts>
>  			<name>Multicast Packets In</name>
>  			<method>walk</method>
>  			<source>value</source>
>  			<direction>output</direction>
>  			<oid>.1.3.6.1.2.1.31.1.1.1.2</oid>
>  		</ifInMulticastPkts>
>  		<ifOutMulticastPkts>
>  			<name>Multicast Packets Out</name>
>  			<method>walk</method>
>  			<source>value</source>
>  			<direction>output</direction>
>  			<oid>.1.3.6.1.2.1.31.1.1.1.4</oid>
>  		</ifOutMulticastPkts>
>  		<ifInBroadcastPkts>
>  			<name>Broadcast Packets In</name>
>  			<method>walk</method>
>  			<source>value</source>
>  			<direction>output</direction>
>  			<oid>.1.3.6.1.2.1.31.1.1.1.3</oid>
>  		</ifInBroadcastPkts>
>  		<ifOutBroadcastPkts>
>  			<name>Broadcast Packets Out</name>
>  			<method>walk</method>
>  			<source>value</source>
>  			<direction>output</direction>
>  			<oid>.1.3.6.1.2.1.31.1.1.1.5</oid>
>  		</ifOutBroadcastPkts>

Best regards, Jens

**Comment by ronytomen** [comment]
This got removed?

**Comment by jenhek** [comment]
On 28.02.2017 22:39, Tony Roman wrote:
> This got removed?
> 

To me it looked like (or are there tomatoes on my eyes?)

See attached email.

**Comment by CapitalF** [comment]
I confirm. The templates and everything for Multicast packets are just gone.

**Comment by jenhek** [comment]
Am 02.03.2017 um 03:29 schrieb CapitalF:
> I confirm. The templates and everything for Multicast packets are just gone.


As well as the "BroadCast Packets":

	ifInBroadcastPkts
	ifOutBroadcastPkts

Note that "non unicast packet" MIBS are deprecated:

	ifInNUcastPkts
	ifOutNUcastPkts

Some devices still support it, the more modern
(eg. Cisco Catalyst 4500) don't.


-- 
Dipl.-Phys. Jens Hektor, Networks
IT Center, RWTH Aachen University
Room 2.04, Wendlingweg 10, 52074 Aachen (Germany)
Phone: +49 241 80 29206 - Fax: +49 241 80 22100
http://www.itc.rwth-aachen.de - hektor@itc.rwth-aachen.de

**Comment by cigamit** [comment]
Well, this is half resolved.  Bringing back the actual templates is a bit more difficult.

**Comment by cigamit** [comment]
Resolved, thanks for reporting!  You will have to re-import packages to add the new templates using the cli script import_package.php to do so.
