### ISSUE TITLE
Start date for RRDfile is different between RRDfile in a Cacti install

### ISSUE THREAD

**Issue by ixinshang** [Cacti/cacti#3533]
Cacti 1.2.10
Centos 7.2 
Mysql:mysql  Ver 15.1 Distrib 10.4.12-MariaDB
rrdtool:RRDtool 1.7.2
i exported Previous month datas. i saw the "start time",it's wrong. it's start at 2020/4/1 0:10:00.  

![Snipaste_2020-05-04_11-43-01](https://user-images.githubusercontent.com/10056396/80934833-8b814000-8dfc-11ea-8ba6-3e4cf1250707.png)
![Snipaste_2020-05-04_11-42-21](https://user-images.githubusercontent.com/10056396/80934834-8de39a00-8dfc-11ea-9e38-8738084740f8.png)

it's a bug or new change?
can you help me to reslove it. thanks.

**Comment by netniV** [comment]
I'm slightly confused because your filters suggest at 00:00 not 00:10, was that a typo?

**Comment by ixinshang** [comment]
> I'm slightly confused because your filters suggest at 00:00 not 00:10, was that a typo?

i select from "Previous month",it means the start date is 00:00, the first point should start at 00:05,
but it's first point started at 00:10,and not 00:05.

the end point is errors too.

**Comment by TheWitness** [comment]
The real issue here is that the dates are set when you first insert into the RRDfile.  So, for example, you could get a daily RRA that has a timestamp that is not midnight, but say 2:00am or 4:00am, etc.

The way we do this is that at create time always initilize the first date:

```
rrdtool create some_rrd.rrd  --start 0 ...
```

The important part is "--start 0".  Right now, that is not being done.  Easy fix.

**Comment by TheWitness** [comment]
There is not much we can do about files that have already been created.  You might consider using the splice_rrd.php function in the cli directory, but it'll take a long time to complete.

**Comment by ixinshang** [comment]
> There is not much we can do about files that have already been created. You might consider using the splice_rrd.php function in the cli directory, but it'll take a long time to complete.

thanks your replies.  all cacti has same problems?

**Comment by TheWitness** [comment]
As far as I can tell.  Looks like it was introduced post Cacti 1.x.  Before it was never being set.  I have a patch ready.  Just waiting on the call to see where it should go.

**Comment by TheWitness** [comment]
This has been fixed.  If you are on 1.2.12, you can pull the files directly from the 1.2.x branch.

**Comment by ixinshang** [comment]
> This has been fixed. If you are on 1.2.12, you can pull the files directly from the 1.2.x branch.

thanks,i will have a try to test it .   thanks.

**Comment by ixinshang** [comment]
> This has been fixed. If you are on 1.2.12, you can pull the files directly from the 1.2.x branch.

it's ok.  thanks all person.  @netniV  @TheWitness

**Comment by ixinshang** [comment]
i install a new cacti(1.2.12) on an old server( it' installed cacti.1.2.10), i exported Previous month datas. 
the start time is 2020/4/1  0:10:00. 
The new 1.2.x branch need to have a new installed rrdtool?  @TheWitness

**Comment by netniV** [comment]
The fix above will be in the next release it is not in .12

If you want that fix you need to apply it either manually or download the latest sources from the 1.2.X branch

**Comment by ixinshang** [comment]
thanks all.
i hope to the next veriosn to fix those problems.
