### ISSUE TITLE
Username on Login page is not visible in Classic Theme

### ISSUE THREAD

**Issue by RBuryak** [Cacti/cacti#3535]
# Describe the bug

When I type a Username for login to Cacti I don't see typed symbols in Classic Theme.
I think a symbol's color is equal to background color

## To Reproduce

1. Switch to Classic Theme

2. Logout

3. Try to login

## Desktop (please complete the following information)
- OS: Debian 10

- Browser
Chrome, IE, FireFox, Opera

- CACTI Version 1.2.2

**Comment by netniV** [comment]
Could you update to 1.2.12 and see if this is still an issue?

**Comment by TheWitness** [comment]
I've checked on 1.2.12 and it's fine.

![image](https://user-images.githubusercontent.com/1439914/81026160-2a328e80-8e47-11ea-8df4-0beb6faf2e24.png)
