### ISSUE TITLE
Responsive Navigation Menu Show/Hide Broken in 1.2.12

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#3536]
# Describe the bug

When you are viewing Cacti on a small screen such as a mobile phone, Cacti should hide the navigation menu on load, and then when on page, clicking again on the menu should open/close the menu.  This is broken in 1.2.12.

## To Reproduce

1. Go to the Console

2. Click Console again and navigation menu should hide

3. Notice that each click will activate the Console again and not hide the menu.

## Expected behavior

Cacti should behave as it did in 1.2.11.

**Comment by netniV** [comment]
This is working OK under Modern on develop but strangely not on 1.2.x
