### ISSUE TITLE
Place on tree dashes / ordering

### ISSUE THREAD

**Issue by sam-san91** [Cacti/cacti#354]
In the current version if you want to place a host on a tree the dashes are just increasing with every subtree.
e.g.
-ROOT
--Sub1
---Sub1-1
----Sub1-2
-----Sub2
Whereas it should be like:
-ROOT
--Sub1
---Sub-1-1
---Sub-1-2
--Sub2

I think I found a workaround, not sure yet if it breaks anything else. I edited the function grow_dropdown_tree in lib/html_tree.php
[fix.txt](https://github.com/Cacti/cacti/files/807399/fix.txt)

**Comment by ronytomen** [comment]
How about submitting a pull request?

**Comment by cigamit** [comment]
Thanks for reporting.  Closing.
