### ISSUE TITLE
Can't login with Server's hostname

### ISSUE THREAD

**Issue by DY-1990** [Cacti/cacti#3540]
# Describe the bug

can't login with hostname after upgrade from 1.2.5 to 1.2.11.

## To Reproduce

1. Go to browser.

2. type in cacti server's url in address bar.

3. Entering username, password in login page.

## Expected behavior

fix login error. 

## Screenshots

![cacti1](https://user-images.githubusercontent.com/63394625/81137404-493d3780-8f91-11ea-8632-cfd2f7b78ca3.PNG)

## Desktop (please complete the following information)

- OS: centos 7

- Browser chrome

- Version 1.2.11

**Comment by cigamit** [comment]
Already fixed, please upgrade to 1.2.12, or comment out the cookie domain in your config.php.

**Comment by DY-1990** [comment]
sorry, my fail. I mean I upgrade from 1.2.5 to 1.2.12. please see my screen shot.

**Comment by netniV** [comment]
Please check if you have the cookie domain set in your config.php and that if you do it matches the domain your website is on.  Also, please check the error logs and cacti logs for any issues.

**Comment by DY-1990** [comment]
Please find my config.php below.
![cacti2](https://user-images.githubusercontent.com/63394625/81145620-33d40780-8fa9-11ea-82e0-115ef7fd6d5d.PNG)

**Comment by netniV** [comment]
That does not match your website url on the screenshot above.

**Comment by DY-1990** [comment]
sorry, should I type full url in config file?

**Comment by netniV** [comment]
I believe so

**Comment by netniV** [comment]
As in the full host name. Not all the https etc

**Comment by DY-1990** [comment]
I change the value for cookie domain in config.php, but still stuck in login page. Even worse, using IP is also stuck in login page. 
![cacti3](https://user-images.githubusercontent.com/63394625/81243721-35520e00-9043-11ea-8f86-3f3210eb7ce2.PNG)
![cacti4](https://user-images.githubusercontent.com/63394625/81243725-38e59500-9043-11ea-960b-6f12c7f66f06.PNG)

**Comment by DY-1990** [comment]
hostname is working now, but IP address still not. nothing modified.

**Comment by netniV** [comment]
IP will not work if the domain is set.

**Comment by DY-1990** [comment]
hostname not works again, nothing changed. I think where is still something wrong.

**Comment by DY-1990** [comment]
The situation is like this below. It's stucking after click login. 
<img width="749" alt="cacti4" src="https://user-images.githubusercontent.com/63394625/81364480-4e78be80-9118-11ea-9059-69eb630ef1be.PNG">

**Comment by TheWitness** [comment]
Make sure you close all your browsers before using the cookie domain.  Then, once you attempt a login, we need you to goto the browsers debug window, then goto the network tab, go to the the transaction that is posting the user id and password, click on that transaction, goto the Cookie sub-tab and find the Cacti session cookie.  Make a screen shot of all it's attributes and attach to this ticket.

**Comment by DY-1990** [comment]
I'm not sure if that is what you want. Please find it below. 
![cacti1](https://user-images.githubusercontent.com/63394625/81460373-8f83d800-91d7-11ea-94ff-b2557e9c530d.PNG)

**Comment by DY-1990** [comment]
I think I find the root cause, but still have something wrong. I will feedback the solution if it's totally solved.

**Comment by DY-1990** [comment]
finally, it works woth IE without any problem, but Chrome still can't be login.

**Comment by TheWitness** [comment]
What's your PHP version?

**Comment by TheWitness** [comment]
So, same site cookies are not officially supported until PHP 7.3.  There was a workaround published for versions prior to PHP 7.3, but I'm not certain it will work.

**Comment by DY-1990** [comment]
My PHP information shows below.
 PHP 5.4.16 (cli) (built: Apr 12 2018 19:02:01) 
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies
what is your metioned workaround. can you tell me what do to.

**Comment by TheWitness** [comment]
I'm going to suspect that.  If you can edit the following file: include/global.php, and comment out line 429.  After that, see if you have any issues logging in.

Once you get to version 7.3, this will be fully supported.

**Comment by TheWitness** [comment]
You can also change that line to the following.  Let us know if this fixes it in Chrome:

```
header('Set-Cookie: cross-site-cookie=bar; Path=' . $config['url_path'] . '; SameSite=Strict;' . (isset($_SERVER['HTTPS']) && $_SERVER['H    TTPS'] != 'off' ? ' Secure':''));
```

**Comment by DY-1990** [comment]
Hello TheWitness, thanks for help. I have tried both methods that you provide, neither of them works. I found that it's only works with chrome when I doubled login(I mean click login in login page then refresh the page and login again).

**Comment by DY-1990** [comment]
This is my include/global.php, please also check.
![cacti](https://user-images.githubusercontent.com/63394625/81632928-0ae6c300-943e-11ea-9b01-2c4ced449aa9.PNG)

**Comment by TheWitness** [comment]
The SameSite was removed from the 1.2.x branch for versions less than 7.3.  So, I'm going to close this.  Update include/global.php from the 1.2.x branch.
