### ISSUE TITLE
Need to save \n\r into the DB

### ISSUE THREAD

**Issue by arno-st** [Cacti/cacti#3541]
Hello,
In one of my plugin I need to save a text (as text or blob) into the DB with \r\n
But the function db_execute call db_strip_control_chars who then call clean_up_lines, so all my \n\r are removed
And I can't find a cacti function who let my save a text as it is.

Any clue how to do that without rewriting a function ?

**Comment by netniV** [comment]
You could try either url or html encoding ti? I didn’t think db_execute itself called clean_up_lines except when displaying the error message. Will have to check later.

**Comment by arno-st** [comment]
Well db_execute call db_execute_prepared, then it call db_strip_control_chars who call clean_up_lines

Ok I will try to escape the code

**Comment by TheWitness** [comment]
There is no way that db_execute() executes clean_up_lines().  We store binary data all the time using db_execute().

**Comment by arno-st** [comment]
Sorry, cacti 1.2.12
line 240 (inside db_execute_prepared) 	$sql = db_strip_control_chars($sql);
Then line 1476 inside (db_strip_control_chars) trim(clean_up_lines($sql)
And clean_up_lines inside functions.php line 1702 : 	return preg_replace('/\s*[\r\n]+\s*/',' ', $string);

But maybe the regex is suppose to do the filtering differently, like at start and end of the $sql

I'm not inventing it!!

**Comment by TheWitness** [comment]
Mark, that's a problem if it's in fact not for logging.

**Comment by netniV** [comment]
There was a reason it was introduced, we will need to look at the commit that added it and review.  I didn't think you were making it up @arno-st but we are surprised ourselves that it is used on the SQL that goes into the DB so we must have had a reason.

**Comment by TheWitness** [comment]
Yea, blowing my mind actually.  If you use prepared statements, it would not be a problem, but using the legacy call is bad mojo.

**Comment by netniV** [comment]
@arno-st it would see a work around for now, use `db_execute_prepared` ?

**Comment by arno-st** [comment]
How can I use db_execute_prepared, it's the one called from db_Execute, so that dosen't change anything:
function db_execute($sql, $log = true, $db_conn = false) {
	return db_execute_prepared($sql, array(), $log, $db_conn);
}

**Comment by netniV** [comment]
Say you have the query of:

```php
$comment = "This is 
my multiline
comment";
$id = 1023

db_execute('update host set comment = "$comment" where id = $id');
```

We now know that this would actually execute more like:

```php
db_execute('update host set comment = "This is my multiline comment" where id = 1023);
```

With db_execute_prepared, you query changes and prevents SQL injection attempts by becoming:

```php
$comment
db_execute_prepared('update host set comment = ? where id = ?', array($comment, $id));
```

The SQL statement passed to MySQL would be exactly as written and it's MySQL that converts the parameters we pass, thus goes not go through the db_strip_control_chars.  Does this help?

**Comment by arno-st** [comment]
I see, but how can you do it with values ?
so here is my query:
   $ret = db_execute("INSERT INTO plugin_ciscotools_backup(host_id,version,diff,datechange) VALUES('".
    $deviceid. "', '".
    $version. "', '".
    $data. "', '".
    date("Ymd")."')");

**Comment by netniV** [comment]
Just the same way, all values become question marks.

**Comment by arno-st** [comment]
Perfect, that fit my needs
thanks

**Comment by netniV** [comment]
For now, I'm going to close this issue.  Glad you are sorted 👍
