### ISSUE TITLE
Downgrading from 1.3.0-dev to 1.2.1

### ISSUE THREAD

**Issue by dzogrim** [Cacti/cacti#3542]
Hi!
I found we have a cacti running on version 1.3.0.
We are experiencing some bugs that are annoying … is there by any chance a downgrade path to current stable 1.2.1?
How should I **safely proceed to downgrade** if possible, please?

Or maybe should we wait if another version of 1.3.0 is pending release in next few weeks?

Thanks in advance!

**Comment by netniV** [comment]
What bugs are you facing?

**Comment by dzogrim** [comment]
I'm collecting more information from main users and add comment ASAP…

**Comment by netniV** [comment]
For reference, Develop is generally speaking cutting edge and may break.  We could probably do a weekly build into a 1.3.x branch but that's not something we've considered yet.

**Comment by dzogrim** [comment]
Yeah, I know, I didn't install or recommend using the dev version ; anyway the situation is like that. For example, it is impossible to add _traffic_ datasource (N/A) while is it both displaying _traffic_ and _Watt_
![screenshot-3](https://user-images.githubusercontent.com/4758578/81260130-b0aec200-9039-11ea-9ac2-48d9d618d2fb.png)
![screenshot-2](https://user-images.githubusercontent.com/4758578/81260133-b1475880-9039-11ea-8f2f-9d898efa1c99.png)

And title changes are also impossible from time to time.
![screenshot-4](https://user-images.githubusercontent.com/4758578/81260203-d20fae00-9039-11ea-82d4-06b48a6c88c7.png)

That's why I'm looking for to **downgrade to the current stable version**.
Is that possible?
Meanwhile, I'll try to deploy a 1.2.1 version and import database.

Thanks anyway

**Comment by netniV** [comment]
Those issues may still exist on Stable tbh.  That functionality shouldn't be much difference.  Develop has had mostly cosmetic changes under the hood at the moment and my thoughts are that whilst the ajax changes could be affecting this, it shouldn't be so I would be curious.

If you are going to downgrade, at the moment there isn't much difference database wise, just checkout the 1_3_0.php upgrade file.  Revert those fields that are changed back to the 1.2.12 versions and remove those that are new.  Unfortunately, that's a manual process as we don't recommend downgrading, but do know some admins need to do it occasionally.

If you do still have these issues as problems, please open separate issues for each of them.

**Comment by dzogrim** [comment]
Alright! thanks a lot for your inputs…
