### ISSUE TITLE
CSV Export output readability issues using UTF8 characters

### ISSUE THREAD

**Issue by ixinshang** [Cacti/cacti#3543]
hi, i installed 1.2.12 on centos7 with mysql  Ver 15.1 Distrib 10.4.12-MariaDB and rrdtool 1.7.2.

1:
i saw 1.2.12 have resolve the problem "issue#3427: When exporting to a CSV with unicode characters, contents can become garbled".  i read https://github.com/Cacti/cacti/issues/3427. 
so i exported a data. it's wrong.
first, i use Chinese as my "User Language", my graph title name is "联通 - Polling Time". i exported data.
![image](https://user-images.githubusercontent.com/10056396/81281578-9ce07b80-908c-11ea-82c2-d386f3a2c1b4.png)

then, i use English  as my "User Language",  i exported data too.
![image](https://user-images.githubusercontent.com/10056396/81281381-5a1ea380-908c-11ea-96a3-04a2c318677f.png)
it's a new bug or others?

2: 
i found the "Interface - Traffic Data Template",  in "Maximum Value" can use |query_ifSpeed|, i want to use |query_ifHighSpeed| ,it's wrong. it's a new feature?

thanks all to creat cacti.

**Comment by netniV** [comment]
You should open the second as a separate issue

**Comment by ixinshang** [comment]
> You should open the second as a separate issue

i'm sorry.  i will create a new issue.

**Comment by TheWitness** [comment]
Can you please edit:

graph_xport.php, line 211 and change:

```
print mb_convert_encoding($output, 'UTF-16LE', 'UTF-8');
```

to

```
print $output;
```

And let us know how the output looks?

**Comment by ixinshang** [comment]
@TheWitness 
I'm very sorry to be late answering.  
i install 1.2.10.    but  i will have a test later  on 1.2.12.

**Comment by TheWitness** [comment]
No problem.  Thanks.

**Comment by ixinshang** [comment]
@TheWitness 
RRDtool 1.4.8 
mysql  Ver 15.1 Distrib 10.4.12-MariaDB, for Linux (x86_64) using readline 5.1
CentOS Linux release 7.7.1908 (Core)
Cacti 1.2.12
 Apache/2.4.6 (CentOS)
i use this config to try a test. it's great. all word are right. like this.
![image](https://user-images.githubusercontent.com/10056396/83939541-607d7800-a810-11ea-98d7-4a5a79436ff7.png)
thanks all people to help resovle this problem.  
Thanks to all.
in the end.  I'm very sorry to be late answering.
