### ISSUE TITLE
Installer instability 1.2.11 -> 1.2.12

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#3552]
I got kicked out of the installer three times performing an upgrade. Each time I had to re-login, and at one point I got that pesky CSRF failure again. This is what the screen looked like:

![image](https://user-images.githubusercontent.com/12864741/81633081-121fb980-93c9-11ea-90e6-5b8de0533517.png)

The Next button and the reload button in the corner all failed to work. So I used the browser reload and that's when I got kicked out. Each time I would get redirected back to the same spot in the install, which was good. The last time I just got logged in, so I assumed the upgrade was done.

I'm still on an older version of Chrome, so I need to upgrade my workstations and get to more recent versions. Maybe a lot of my browser related issues will go away when this happens, but I figure I'd report the behavior. I didn't have this problem upgrading to 1.2.11 on any of the three instances I did the upgrade on. I've also cleared out my cache recently and had no other browser windows running at the time.

**Comment by netniV** [comment]
I have used lots of browser/server combinations without issue, so I think this is a local one to yourself.  Generally speaking, it would mean a javascript failing so it would be a good idea to check the browser's console window for any errors? Also, you should see if there are any apache/ngix/php errors recorded as you refresh the page.

**Comment by eschoeller** [comment]
I'll try an upgrade of another instance and inspect the apache logs and browser console while I do it. Hopefully on Wednesday, or perhaps later today.

**Comment by netniV** [comment]
Any feedback?

**Comment by eschoeller** [comment]
I am so sorry, not yet. My life has gotten turned upside down with this whole thing. One of our buildings got broken into again a couple days ago ... I'm dealing with stuff waaaay outside my job description now! Probably the earliest I'll have a chance to try another upgrade is next Tuesday.

**Comment by TheWitness** [comment]
Sorry to hear that.  Be well.

**Comment by netniV** [comment]
Haven't heard from you since, hope all is well? An update would be good before stalebot get's his hands on this thread. 👍

**Comment by eschoeller** [comment]
Haha yeah sorry. They opened up skiing again and today is the last day. Had some other stuff going on too. I’ll try to circle back as soon as I can. Thanks for your patience!

Eric.

**Comment by TheWitness** [comment]
Saw some snow just the other day, in JUNE!!!
