### ISSUE TITLE
undefined error when directly visit a none-exist graph

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/cacti#3553]
Directly access some none-exist graph page, eg: http://ipxxxxx/cacti/aggregate_graphs.php?action=edit&id=4566&tab=preview&debug=1

page says access deny, but log has error

2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[987]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 987
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[986]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: legend_direction in file: /opt/IBM/cacti/aggregate_graphs.php on line: 986
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[987]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 987
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[986]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: legend_position in file: /opt/IBM/cacti/aggregate_graphs.php on line: 986
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[987]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 987
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[986]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: tab_width in file: /opt/IBM/cacti/aggregate_graphs.php on line: 986
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[987]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 987
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[986]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: force_rules_legend in file: /opt/IBM/cacti/aggregate_graphs.php on line: 986
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[987]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 987
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[986]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: dynamic_labels in file: /opt/IBM/cacti/aggregate_graphs.php on line: 986
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[987]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 987
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[986]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: auto_padding in file: /opt/IBM/cacti/aggregate_graphs.php on line: 986
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[987]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 987
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[986]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: left_axis_formatter in file: /opt/IBM/cacti/aggregate_graphs.php on line: 986
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[987]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 987
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[986]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: right_axis_formatter in file: /opt/IBM/cacti/aggregate_graphs.php on line: 986
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[987]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 987
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[986]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: right_axis_format in file: /opt/IBM/cacti/aggregate_graphs.php on line: 986
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[987]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 987
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[986]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: right_axis_label in file: /opt/IBM/cacti/aggregate_graphs.php on line: 986
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[987]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 987
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[986]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: right_axis in file: /opt/IBM/cacti/aggregate_graphs.php on line: 986
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[987]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 987
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[986]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: alt_y_grid in file: /opt/IBM/cacti/aggregate_graphs.php on line: 986
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[987]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 987
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[986]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: no_gridfit in file: /opt/IBM/cacti/aggregate_graphs.php on line: 986
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[987]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 987
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[986]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: unit_length in file: /opt/IBM/cacti/aggregate_graphs.php on line: 986
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[987]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 987
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[986]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: unit_exponent_value in file: /opt/IBM/cacti/aggregate_graphs.php on line: 986
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[987]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 987
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[986]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: unit_value in file: /opt/IBM/cacti/aggregate_graphs.php on line: 986
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[987]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 987
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[986]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: lower_limit in file: /opt/IBM/cacti/aggregate_graphs.php on line: 986
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[987]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 987
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[986]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: upper_limit in file: /opt/IBM/cacti/aggregate_graphs.php on line: 986
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[987]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 987
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[986]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: auto_scale_rigid in file: /opt/IBM/cacti/aggregate_graphs.php on line: 986
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[987]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 987
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[986]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: scale_log_units in file: /opt/IBM/cacti/aggregate_graphs.php on line: 986
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[987]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 987
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[986]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: auto_scale_log in file: /opt/IBM/cacti/aggregate_graphs.php on line: 986
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[987]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 987
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[986]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: auto_scale_opts in file: /opt/IBM/cacti/aggregate_graphs.php on line: 986
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[987]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 987
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[986]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: auto_scale in file: /opt/IBM/cacti/aggregate_graphs.php on line: 986
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[987]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 987
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[986]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: slope_mode in file: /opt/IBM/cacti/aggregate_graphs.php on line: 986
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[987]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 987
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[986]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: base_value in file: /opt/IBM/cacti/aggregate_graphs.php on line: 986
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[987]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 987
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[986]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: width in file: /opt/IBM/cacti/aggregate_graphs.php on line: 986
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[987]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 987
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[986]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: height in file: /opt/IBM/cacti/aggregate_graphs.php on line: 986
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[987]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 987
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[986]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: image_format_id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 986
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[987]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 987
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[986]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: vertical_label in file: /opt/IBM/cacti/aggregate_graphs.php on line: 986
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[968]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: local_graph_template_graph_id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 968
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[967]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 967
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[798]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: graph_template_id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 798
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[645]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: aggregate_template_id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 645
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[638]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: local_graph_id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 638
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[637]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: title_format in file: /opt/IBM/cacti/aggregate_graphs.php on line: 637
2020/05/11 03:09:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[635]:CactiErrorHandler())
2020/05/11 03:09:13 - ERROR PHP NOTICE: Undefined index: local_graph_id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 635
2020/05/11 03:09:11 - CMDPHP SQL Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[773]:aggregate_items(), /aggregate_graphs.php[1185]:db_fetch_assoc(), /lib/database.php[476]:db_fetch_assoc_prepared(), /lib/database.php[490]:db_execute_prepared())
2020/05/11 03:09:11 - CMDPHP ERROR: A DB Row Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') AS agi ON gtg.local_graph_id=agi.local_graph_id WHERE (agi.local_graph_id IS N' at line 1
2020/05/11 03:09:11 - CMDPHP SQL Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[773]:aggregate_items(), /aggregate_graphs.php[1168]:db_fetch_cell(), /lib/database.php[386]:db_fetch_cell_prepared(), /lib/database.php[402]:db_execute_prepared())
2020/05/11 03:09:11 - CMDPHP ERROR: A DB Cell Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') AS agi ON gtg.local_graph_id=agi.local_graph_id WHERE (agi.local_graph_id IS N' at line 1
2020/05/11 03:09:11 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[645]:CactiErrorHandler())
2020/05/11 03:09:11 - ERROR PHP NOTICE: Undefined index: aggregate_template_id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 645
2020/05/11 03:09:11 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[638]:CactiErrorHandler())
2020/05/11 03:09:11 - ERROR PHP NOTICE: Undefined index: local_graph_id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 638
2020/05/11 03:09:11 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[637]:CactiErrorHandler())
2020/05/11 03:09:11 - ERROR PHP NOTICE: Undefined index: title_format in file: /opt/IBM/cacti/aggregate_graphs.php on line: 637
2020/05/11 03:09:11 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[635]:CactiErrorHandler())
2020/05/11 03:09:11 - ERROR PHP NOTICE: Undefined index: local_graph_id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 635
2020/05/11 03:09:09 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[645]:CactiErrorHandler())
2020/05/11 03:09:09 - ERROR PHP NOTICE: Undefined index: aggregate_template_id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 645
2020/05/11 03:09:09 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[638]:CactiErrorHandler())
2020/05/11 03:09:09 - ERROR PHP NOTICE: Undefined index: local_graph_id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 638
2020/05/11 03:09:09 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[637]:CactiErrorHandler())
2020/05/11 03:09:09 - ERROR PHP NOTICE: Undefined index: title_format in file: /opt/IBM/cacti/aggregate_graphs.php on line: 637
2020/05/11 03:09:09 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[635]:CactiErrorHandler())
2020/05/11 03:09:09 - ERROR PHP NOTICE: Undefined index: local_graph_id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 635
2020/05/11 03:08:03 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[645]:CactiErrorHandler())
2020/05/11 03:08:03 - ERROR PHP NOTICE: Undefined index: aggregate_template_id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 645
2020/05/11 03:08:03 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[638]:CactiErrorHandler())
2020/05/11 03:08:03 - ERROR PHP NOTICE: Undefined index: local_graph_id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 638
2020/05/11 03:08:03 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[637]:CactiErrorHandler())
2020/05/11 03:08:03 - ERROR PHP NOTICE: Undefined index: title_format in file: /opt/IBM/cacti/aggregate_graphs.php on line: 637
2020/05/11 03:08:03 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[635]:CactiErrorHandler())
2020/05/11 03:08:03 - ERROR PHP NOTICE: Undefined index: local_graph_id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 635
2020/05/11 03:05:04 - SYSTEM DISKU STATS: Time:0.2440 Groups:82 Users:551

## Screenshots
![Screen Shot 2020-05-12 at 11 32 06 AM](https://user-images.githubusercontent.com/47589910/81635672-54d2a780-9444-11ea-994c-a740d2bfeb33.png)

## Desktop (please complete the following information)
cacti 1.2.10
FF 76
rhel8 x64

**Comment by TheWitness** [comment]
Great job @yingbaiibm.

**Comment by yingbaiibm** [comment]
Still has problem with the fix. 
Steps:
1. visit a none-exist agg graph
2. Click details button then check log, error exist 
2020/05/15 12:06:29 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[1003]:CactiErrorHandler())
2020/05/15 12:06:29 - ERROR PHP NOTICE: Undefined index: image_format_id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 1003
2020/05/15 12:06:29 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[1004]:CactiErrorHandler())
2020/05/15 12:06:29 - ERROR PHP NOTICE: Undefined index: id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 1004
2020/05/15 12:06:29 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[1003]:CactiErrorHandler())
2020/05/15 12:06:29 - ERROR PHP NOTICE: Undefined index: vertical_label in file: /opt/IBM/cacti/aggregate_graphs.php on line: 1003
2020/05/15 12:06:29 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[985]:CactiErrorHandler())
2020/05/15 12:06:29 - ERROR PHP NOTICE: Undefined index: local_graph_template_graph_id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 985
2020/05/15 12:06:29 - CMDPHP PHP ERROR NOTICE Backtrace: (/aggregate_graphs.php[66]:graph_edit(), /aggregate_graphs.php[984]:CactiErrorHandler())
2020/05/15 12:06:29 - ERROR PHP NOTICE: Undefined index: id in file: /opt/IBM/cacti/aggregate_graphs.php on line: 984

**Comment by yingbaiibm** [comment]
<img width="1270" alt="Screen Shot 2020-05-15 at 12 04 52 PM" src="https://user-images.githubusercontent.com/47589910/82010593-20115b00-96a5-11ea-9d41-3f62a7ab221d.png">

**Comment by yingbaiibm** [comment]
@TheWitness  Still has problem after the fix, please have a look.

**Comment by TheWitness** [comment]
Should be resolved now.
