### ISSUE TITLE
when it reaches 2020-09-13 20:26:40，the graph view will be broken

### ISSUE THREAD

**Issue by JiangzhouXing** [Cacti/cacti#3554]
# Describe the bug

when i set the graph fileters time from 2020-09-11 12:55 to 2020-09-14 12:55，the graph was broken.

## To Reproduce

1. Go to 'Graph'

2. Click Any Device

3. set the graph filters time after  2020-09-13 20:26:40

## Screenshots
![image](https://user-images.githubusercontent.com/65210974/81640474-31fac000-9451-11ea-8139-154c393a8238.png)

## Server Enviroment

- OS: CentOS7
- Cacti Version: 0.8.8h
## Desktop
-OS: Windows10
-Browser: Google Chrome 81.0.4044.138

## Additional context

I am not a program engineer，but i find the reason，maybe is not the true reason，but i hope it can helps you.
in cacti/graph_xport.php 
line 56:
if (!empty($_GET["graph_start"]) && is_numeric($_GET["graph_start"]) && $_GET["graph_start"] < 1600000000)
and cacti/graph_image.php
line 63:
if (!empty($_GET["graph_start"]) && $_GET["graph_start"] < 1600000000)

 I think is the '1600000000' cause the problem.

according to the code，seems all version have this problem.

**Comment by JiangzhouXing** [comment]
i saw it has been solved in newest veresion， but old version Still used frequently，can you update the code in all version ?

**Comment by netniV** [comment]
Unfortunately not. you would have to do that manually.

**Comment by TheWitness** [comment]
Correct.  That version is no longer maintained.  It's been fixed in upstream several releases ago.
