### ISSUE TITLE
Limit user to a single session

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3557]
Hey Guys 

One useful option to have would be to limit a user to a single session this eliminates users opening cacti in multiple browsers consuming resources 

If a user is already logged in the other session should terminate and a new session starts 

Thanks !

**Comment by netniV** [comment]
I think @TheWitness knows how to detect if a user has multiple tabs open, but generally most people want that as we  made Ctrl-Click work again on the 1.3 branch specifically for that reason.

**Comment by TheWitness** [comment]
I'm going to close this one for now.  I'm not really excited about doing it anyway.
