### ISSUE TITLE
Monitor view issue on multiple items/trees

### ISSUE THREAD

**Issue by w1sht0l1v3** [Cacti/cacti#356]
Two issues with displaying.
1.First would be with multiple items in one category inside a root.Notice in the picture that the switch category has 23 items....last 2 items are on a next row that is under the other categories.
2.I have two trees there..notice in the picture that All Trees is selected to show but the second tree(2.Francizati) is displayed as the first one(1.Cacti Monitorizare) and the first one is completely missing from view.Also this makes the categories get mixed...one of the category named 3.Server should be in the second tree.

Here is a schema on how i suppose it should work:
Tree1
-cat1-cat2-cat3-
cat4-cat5
Tree2
-cat1-cat2-cat3

![cacti](https://cloud.githubusercontent.com/assets/1199041/23461006/a9d6a5c6-fe90-11e6-909e-902333e1d9be.jpg)

Some categories are emtpy..so them not being displayed is normal i guess...like my second tree has 3 categories but only one is populated with items.

**Comment by cigamit** [comment]
Please open this bug in the Monitor plugin issue area.  Thanks.
