### ISSUE TITLE
Cacti Graph Automation Rule changes existing graphs

### ISSUE THREAD

**Issue by eholz1** [Cacti/cacti#3562]
Hello All,
I tried to use cacti automation to add 64bit counter (In/Out Bits) to UP interfaces
on a device (later a range of devices).

I set up a network discovery for the the network in question - but NOT adding device to cacti.
I then copied the stock 64 bytes rule and made it 64 counter In/Out Bits.

I then applied the automation rule to the device - it adds some graphs (64bit counters In/Out bits) but only to the sub interfaces:
i.e Gi0/1.301 this interface is up. I need it to add a graph for Gi0/1 not the sub-interface. It would be ok if the rule added
64Bit counter to both Gi0/1 and Gi0/1.301.

Pattern matching by adding a 4th item to the rule for ifName does not work.

The I discovered what i think is very strange. When I apply the graph rule to a device, it may (or may not) add a 64bit In/Out bits graph, but it changes all existing In/Out graphs to use 64bit counters, but does not change the graph type or template!

Is this the intended mode of operation? I also notice that if a device is discovered thru automation, it adds appropriate graphs.

Help - will post this on Git Hub as well.

Thanks,
eholz1

Graph rule may or may not add graph, but change existing graphs

## Create or use an existing graph rule and apply it to an existing device

1. Go to Management > devices > select a device 
2. Select "Apply Automation Rule" to device

## Expected behavior

I expected the rule to add 64counters (In/Out bits) graphs to all UP interfaces on device. It does not. It may add a 64bit counter graph or not, but it changes existing graphs (based on SNMP interface statistics) to use 64 bit counters

## Desktop (please complete the following information)

- OS: Red Hat 7 RHEL

- Browser [IE, Firefox]

## Additional context

Is this expected behaviour? I have run a network discovery, re-run queries, but not add devices to cacti. What to change existing devices.

**Comment by eholz1** [comment]
The above "bug" is not a bug - it is an interpretation error on the part of the user.
Please delete this post.

**Comment by netniV** [comment]
👍
