### ISSUE TITLE
Current orphan handling disrupts graphing transient indexes

### ISSUE THREAD

**Issue by adamsla** [Cacti/cacti#3563]
# Describe the bug

If you have transient indexes in your system, the impact on re-indexing can disrupt graphing and generate excessive log messages, and becomes a burden to keep up with.

## To Reproduce

1. Create a Data Query where indexes periodically leave the system, like a wireless router

2. Re-index and note a entries leave the system, the graphs stop working and warnings are generated periodically

## Expected behavior

Cacti should mark them as orphans so that they are traceable, but should not bother the admin with excessive logging.

**Comment by TheWitness** [comment]
I've done this in such a way as we don't need to update the cacti.sql.  We should update the base sql though.  Leave that here for discussion @netniV.

**Comment by ddb4github** [comment]
create_complete_graph_from_template also call update_data_source_data_query_cache with column 'orphan'

**Comment by TheWitness** [comment]
I don't think the API actually requires the orphan column.  Should have not included it in the select.

**Comment by ddb4github** [comment]
> I don't think the API actually requires the orphan column. Should have not included it in the select.

1.  function `update_data_source_data_query_cache` operate dl.orphan:
```php
<?php
...
lib/data_query.php:1654: function update_data_source_data_query_cache($local_data_id, $host_id = '', $data_query_id = '', $previous_index = '') {
...
lib/data_query.php:1691:     if ($data_query_id != 0 && $current_index != '' && $current_index != $previous_index) {
        /* set the index to the new index */
        db_execute_prepared('UPDATE data_local
            SET snmp_query_id = ?,
            snmp_index = ?,
            orphan = 0
            WHERE id = ?',
            array($data_query_id, $current_index, $local_data_id));

        /* update data source title cache */
```
2. function `create_complete_graph_from_template` call `update_data_source_data_query_cache` 
```php
<?php
....
lib/template.php:1005: function create_complete_graph_from_template($graph_template_id, $host_id, $snmp_query_array, &$suggested_vals) {
....
lib/template.php:1230:                    /* now that we have put data into the 'data_input_data' table, update the snmp cache for ds's */
                    update_data_source_data_query_cache($cache_array['local_data_id'][$data_template['id']]);
```
3. `create_complete_graph_from_template` is called by many files.

So I prefer to add `add_orphan_support` at begin of `create_complete_graph_from_template` function like `run_data_query`.

**Comment by TheWitness** [comment]
Okay, I've made that change.
