### ISSUE TITLE
[CACTI 1.2.12] Cacti Server + Cacti Poller

### ISSUE THREAD

**Issue by anarkia1976** [Cacti/cacti#3565]
we have configured a "server + poller" infrastructure with the latest release including the patches in the "1.2.x" branch. unfortunately on the poller server we do not see applied as poller "plugs" after configuring it on the primary server.

1. Go to Primary server --> Configuration --> settings --> poller --> spine

2. Go to Poller server --> Configuration --> settings --> poller --> is always equal to cmd

Primary server:
![image](https://user-images.githubusercontent.com/1744639/82344059-de114d80-99f3-11ea-836c-61beadc78144.png)

Poller Server:
![image](https://user-images.githubusercontent.com/1744639/82344091-eb2e3c80-99f3-11ea-970c-098af4782b64.png)

**Comment by bmfmancini** [comment]
Check under settings and paths is your spine binary detected?

**Comment by TheWitness** [comment]
Correct, it the spine path is not readable by the web server, or does not exist, spine will not show up.

**Comment by anarkia1976** [comment]
Poller type in the "poller server" is correctly set to spine from the gui point of view:
![image](https://user-images.githubusercontent.com/1744639/82418563-6daf0e80-9a7d-11ea-9060-85f4b3f87a0e.png)

Paths and Permissions are ok:
![image](https://user-images.githubusercontent.com/1744639/82418655-8d463700-9a7d-11ea-8f96-91fa8dd0244b.png)

How can i check into the sql database?

thanks a lot
stefano

**Comment by anarkia1976** [comment]
Hi Guys, sorry the problem was on my side, i have forgot to add permissions for frontend server into poller sql database. Thanks a lot for support.
