### ISSUE TITLE
Uncaught Error: Call to undefined function duplicate_mactrack

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#3566]
# Describe the bug
Uncaught Error: Call to undefined function duplicate_mactrack

## To Reproduce
1. Go to 'Console-->Automation-->SNMP Options'
2. Select any one of 'SNMP Option Set;
3. Select  'Duplicate' action
4. Click 'Go'
5. Click 'Continue'
6. No response, check 'Logs'
7. See error
```
2020/05/21 08:10:58 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
2020/05/21 08:10:58 - ERROR PHP ERROR: Uncaught Error: Call to  undefined function duplicate_mactrack() in  /var/www/html/cacti/automation_snmp.php:188 Stack trace: #0  /var/www/html/cacti/automation_snmp.php(47):  form_automation_snmp_actions() #1 {main} thrown in file:  /var/www/html/cacti/automation_snmp.php on line: 188
```

**Comment by netniV** [comment]
This is actually a completely missing function so may have been named differently.  

```console
 grep duplicate_mactrack * -R
automation_snmp.php:					duplicate_mactrack($selected_items[$i], get_nfilter_request_var('name_format'));
plugins/mactrack/mactrack_snmp.php:					duplicate_mactrack($selected_items[$i], get_nfilter_request_var('name_format'));
```

When I tried to narrow down on it, the only thing I saw was:

```console
plugins/mactrack$ grep duplicate * -R | grep function | grep duplicate
mactrack_device_types.php:function api_mactrack_duplicate_device_type($device_type_id, $dup_id, $device_type_title) {
```
So I think I'll have to defer to either @cigamit or @thewitness on this one.

**Comment by netniV** [comment]
Just for completeness, I did run through all the tags assigned so far and none of these releases have that function.

**Comment by TheWitness** [comment]
MackTrack.  That's a surprise.  I think it made it way in when snmp options were peeled away from MacTrack.

**Comment by TheWitness** [comment]
Some should fix this in MacTrack too.  It's fixed in Cacti for sure now.
