### ISSUE TITLE
If Recovery Mode runs longer than a polling interval a second is spawned

### ISSUE THREAD

**Issue by Carlimeunier** [Cacti/cacti#357]
In my env, I have 1 Main cacti Server and 1 Remote Data Collector.  The RDC has ~20k datasources.

After lost connection with the main for about ~ 3 days, RDC stored data in his local DB. When it reconnected to the main, it started the recovery process. But it has to many data to recovery, so it's take a while and launchs every 5 minute time polling the recovery script  : 
`cacti   44412   0.6  2.1 248252 86764  -  S     1:05PM     0:01.45 /usr/local/bin/php -q /data/www/cacti/poller_recovery.php
cacti   44515   0.5  1.4 217532 57608  -  S     1:10PM     0:00.17 /usr/local/bin/php -q /data/www/cacti/poller_recovery.php
cacti   44397   0.0  1.9 248252 81140  -  I     1:00PM     0:01.95 /usr/local/bin/php -q /data/www/cacti/poller_recovery.php
 /data/www/cacti/poller_recovery.php`

The recovery process works but it takes too much resources 

Thanks!

**Comment by cigamit** [comment]
Hmm.  It should only launch one poller_recovery process.  That is definitely a bug.

**Comment by cigamit** [comment]
Resolved.  It will run as fast as humanly possible, and a second will not be spawned, which would cause issues.
