### ISSUE TITLE
Undefined function 'aggregate_detect_linex_graph_type'

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#3570]
# Describe the bug
Undefined function `aggregate_detect_linex_graph_type` in unused function `aggregate_convert_to_stack`

**Comment by TheWitness** [comment]
What the heck.

**Comment by netniV** [comment]
```php
$_pure_linex_graph = aggregate_detect_linex_graph_type($_old_graph_id);
```

Which is in the function `aggregate_convert_to_stack` in lib/aggregate.php.  It is only called if the graph no is 0, so I guess that depends on when that function is called with a zero.

However, as @ddb4github has commented, that parent function doesn't appear to be used if you search for it either.

**Comment by ddb4github** [comment]
`aggregate_convert_to_stack` is used until `aggregate` plugin v0.74.
Since v0.75, that line is commented

**Comment by netniV** [comment]
Now that's going back a long time!  Sounds like we just take the function out for now.  Would you concur?

**Comment by TheWitness** [comment]
Yea, there are two functions not even used, and this one that is missing.  Whacking them.
