### ISSUE TITLE
Missing prompts during automation's device creation leads to blank data

### ISSUE THREAD

**Issue by mrjackson** [Cacti/cacti#3572]
# Describe the bug
In 1.2.12 when adding a new Device with Automatic Graph Creation enabled, any graph with a data source that has an override enabled for custom data in the datasource is created with blank data instead of prompting as it did in previous versions (1.2.2)

## To Reproduce
1. Enable Automatic Graph Creation. (default)
2. Add a new device with a template that has an override allowed in a datasource
![image](https://user-images.githubusercontent.com/573075/82741046-580b4480-9d1c-11ea-8309-b6c70cc53e44.png)
3. Page to enter custom data (url) does not show, checking datasource after has a blank field.
Same results on a fresh install on Debian 10.3 and upgrade from 1.2.2 to 1.2.12 on Slackware 14.2

## Expected behavior
After adding a new device, a page should be displayed to enter custom data overrides.
Page shows as expected if graphs are created manually after the device is added.
![image](https://user-images.githubusercontent.com/573075/82741040-42961a80-9d1c-11ea-828c-6d2c617687e0.png)

## Desktop
- OS: Windows Server 2012R2
- Browser Chrome
- Version 81

**Comment by TheWitness** [comment]
Yea, this is a known issue with automation.  If you are wanting to override the defaults, you should disable automatic non-Data Query automation.

**Comment by TheWitness** [comment]
I'm going to mark this as a feature request as such.
