### ISSUE TITLE
Hosts are being incorrectly filtered when first displaying with filter set to all

### ISSUE THREAD

**Issue by DavidLiedke** [Cacti/cacti#3577]
# Describe the bug

Not all devices are displayed by default in the device list.

## To Reproduce

Go to the device list.
Then I must search for the device or i have to click on "Go".

## Screenshots

![xrV7H4ZvJT](https://user-images.githubusercontent.com/25581728/82868572-274e2980-9f2d-11ea-9566-70d1d21c5b78.gif)

**Comment by simonpunk** [comment]
Same to me, cacti 1.2.12, ubuntu server 20.04

**Comment by netniV** [comment]
There was a bug in the previous version of Cacti where the device filtering did not include a check for blanks vs nulls.  That was corrected though, https://github.com/Cacti/cacti/issues/3424 in 1.2.12 so I'm surprised you are showing the same issue.  Can you double check the values of the location column against your hidden device?

**Comment by DavidLiedke** [comment]
![TeamViewer_RRqHLkFYN4](https://user-images.githubusercontent.com/25581728/83107331-5f38a680-a0be-11ea-99d4-77c57710876f.png)

The device with ID 4 is not shown by default.

**Comment by netniV** [comment]
Could you email me a dump of your database to verify what’s going on ? There must be a difference somehow.

**Comment by DavidLiedke** [comment]
can you send me your mail address ?

**Comment by netniV** [comment]
Developers@cacti.net

**Comment by DavidLiedke** [comment]
You have an email ;-)

**Comment by netniV** [comment]
Thanks, sorry been a busy few days  The issue appears to be that three of your devices have a location of None.  Those are being filtered by the default filter, yet the drop down suggests it is usually 'All' which shouldn't filter them.

**Comment by netniV** [comment]
This should now be resolved.
