### ISSUE TITLE
Scheduled Automatic Re-indexing of Devices

### ISSUE THREAD

**Issue by troyfreytag** [Cacti/cacti#3578]
# Feature Request

## Is your feature request related to a problem? Please describe

Automatic re-indexing of devices using the index-count re-index method on data queries does not work for us, and we rarely reboot devices. The issue with the index-count method is that most of our devices do not handle the interface index count OID correctly and report a different value than the actual number of interfaces returned by the SNMP - Interface Statistics data query.

## Describe the solution you'd like

We would like a method of scheduling a re-index of a device, that can be per device or tied to a device template, based on timing and not an event. For example, we would like to have devices that the interface index count changes frequently re-index once a day while other devices would automatically re-index once a week.

## Describe alternatives you've considered

An alternate solution we tried for the data query index-count method was removing the index count OID from the interfaces.xml file and letting Cacti count the number of returned rows instead. This worked for some devices, but caused more problems on others. A large number of devices return additional info (Ex. Interface Descriptions or IP Addresses) that are not necessarily tied to an ifIndex. Each piece of additional info is given its own row and adds to the row count. 

From what I gathered by testing, without the interface count OID in the XML file, the index-count method compares only the number of rows returned when polling the IfIndex OID tree to the total number of rows returned when processing the data query, which includes the extra rows added by additional info. As a result, our devices still re-index every poling cycle.

For now, we periodically go through our devices and re-index them manually.

**Comment by netniV** [comment]
Seems reasonable. First step, would be introducing the ability to set a global schedule, then introduce template/device level option overrides.

**Comment by netniV** [comment]
One thing that a recent comment has highlighted is that this could end up generating lots of new data sources and graphs if automatic creation is enabled with automation.

**Comment by vbarahona** [comment]
> One thing that a recent comment has highlighted is that this could end up generating lots of new data sources and graphs if automatic creation is enabled with automation.

True. Actually in my environment that will be the desired behavior as we decide which interface graph using ifDesc. So if there is a change in ifDesc we have to reindex manually. It will be very appreciated including a timing policy for reindexing.

**Comment by TheWitness** [comment]
This is resolved.  Review the commit and provide comments.  Basically midnight or so on select frequencies and days.
