### ISSUE TITLE
It is strange that many graphs show as 'Empty Graph'

### ISSUE THREAD

**Issue by YongBoLiu** [Cacti/cacti#3579]
# Describe the bug

The graph title can be set as 'Reg  |query_region| - Project |query_project| - |query_feature| - xxx', if user only set query_project and query_feature, not set query_region. 
The graph title show as 'Empty Graph'. It is weird to users.  

Users prefer to 'Reg  |query_region| - Project project1 - feature1- xxx' than 'Empty Graph'. And sometimes users may set the |query_region|  after graph created.

## To Reproduce  
1. Add a graph template , set the title as 'Reg  |query_region| - Project |query_project| - |query_feature| - xxx'.

2. Add a data query, associate the graph template to the data query.

3. User set the query_project and query_feature, but not set query_region. 

4. After graphs created, all the graphs base on the 'Reg  |query_region| - Project |query_project| - |query_feature| - xxx', show as 'Empty Graph'.

## Smartphone (please complete the following information)

firefox 60.5

**Comment by YongBoLiu** [comment]
The condition is added two years ago, but the graph title is different from data source title, it is more chance to be set  by users.
So, I think the condition should be removed as below.

diff -u -N rtm/cacti/lib/variables.php rtm/cacti/lib/variables.php
--- rtm/cacti/lib/variables.php	2020-04-20 10:54:42.000000000 +0800
+++ rtm/cacti/lib/variables.php	2020-05-28 15:45:28.000000942 +0800
@@ -180,12 +180,10 @@
 function update_graph_title_cache($local_graph_id) {
 	$graph_title = get_graph_title($local_graph_id);
 
-	if (strstr($graph_title, '|query_') === false && strstr($graph_title, '|host_') === false) {
 		db_execute_prepared('UPDATE graph_templates_graph
 			SET title_cache = ?
 			WHERE local_graph_id = ?',
 			array($graph_title, $local_graph_id));
-	}
 }
 
 /* null_out_substitutions - takes a string and cleans out any host variables that do not have values

**Comment by netniV** [comment]
It looks good, but does mean that there would potentially be more updates to the DB.  However, since most graphs use on of those, I would agree it seems to make sense.

**Comment by TheWitness** [comment]
I had to make a change to this as it has missed a key reason for the original change.  So, please change the updated lib/variables.php.

**Comment by netniV** [comment]
You are checking if old title is blank, what it is false (no row) or considered null? Can that happen? Haven’t checked it fully against the schema as on my mobile

**Comment by TheWitness** [comment]
Default is not null or blank..

**Comment by netniV** [comment]
OK, so as long as schema is correct, my worry should never occur 👍
