### ISSUE TITLE
Realtime graph javascript error in Chrome

### ISSUE THREAD

**Issue by ahouston** [Cacti/cacti#3580]
# jQuery + Chrome race condition

When starting a realtime graph in Chrome, the following javascript error occurs, and the graph isn't rendered:

```
Uncaught ReferenceError: imageOptionsChanged is not defined
    at HTMLDocument.<anonymous> (graph_realtime.php?top=0&left=0&local_graph_id=14317:227)
    at mightThrow (jquery.js?11c05eb286ed576526bf4543760785b9:3557)
    at process (jquery.js?11c05eb286ed576526bf4543760785b9:3625)
```
I had a look at the code and it appears that the jQuery document ready $(function() {}) in graph_realtime.php is executing before the realtime.js file is loaded, so the imageOptionsChanged() function isn't defined at this point.

I tried this in Firefox and it seemed to work OK there, so likely something specific to browsers based on the Chromium V8 engine.

The simple fix is to change the graph_realtime.php ready function to use the ```$(window).on('load',function{})``` binding like so:

```
$(window).on('load', function() {
	imageOptionsChanged('init');
	myCountdown = setTimeout(function() {
	     countdown_update();
	}, 1000);
});
```
I've tested in Chrome and Firefox and it seems to work fine with the change.

## To Reproduce

1. Chrome Version 81.0.4044.138 (Official Build) (64-bit)
2. From the graph view, click on the realtime icon

## Desktop (please complete the following information)

- OS: Windows 10
- Browser: Chrome Version 81.0.4044.138 (Official Build) (64-bit)

**Comment by netniV** [comment]
There is actually an issue open for this but the race condition makes sense. We really need to ensure the realtime.js is loaded before we initialise then.

**Comment by ahouston** [comment]
Sorry, I don't know how I missed the open issue, I did a cursory search before I raised this but couldn't see anything open for realtime...

The "fix" I put in seems to be working OK, but it may need to be tested against multiple browsers before passing muster.

**Comment by netniV** [comment]
To be fair, the previous one was closed prematurely, and I'd not reopened it yet despite seeing the evidence presented as I hadn't had a chance to diagnose it myself.

**Comment by hiddenicon** [comment]
Yes I had #3538. Just tested this code change for the onload and I'm working again as well. Tested on a few browsers and PCs we initially had issues with, all good now.

**Comment by netniV** [comment]
Thanks for the help and support on this one.
