### ISSUE TITLE
E-Mail alert doesn't work after upgrade to 1.2.12

### ISSUE THREAD

**Issue by DY-1990** [Cacti/cacti#3591]
# Describe the bug

As my title said, I can't received any alert emails even thold has been triggered. I found this in log file "2020/06/02 16:51:08 - THOLD ERROR: Sending Email Failed. Error was Bad email address format. Invalid from email address Cacti@localhost". Email address should be fine after checking.

BTW, I unmarked "Default Cookie domain - The cookie domain to be used for Cacti" to solve a login problem, hope it's no associated with this case.

**Comment by DY-1990** [comment]
additional, I can receive test email through "Send a Test Email" options.

**Comment by netniV** [comment]
No it is unrelated.  Have you updated THOLD since you updated Cacti?

**Comment by TheWitness** [comment]
You need to set a valid from email in the latest phpmailer.  You will find that under the thold settings.

**Comment by DY-1990** [comment]
> No it is unrelated. Have you updated THOLD since you updated Cacti?

thanks netniV, The problem has been solved after upgrade thold to 1.4.
