### ISSUE TITLE
When importing template, resources aren't checked properly 

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#3596]
# Describe the bug

When importing a template, the data query resource is not verified to exist whilst importing.

## To Reproduce

Import a template that relies on a resource file without uploading to the resources folder. No warnings/errors are presented during verification or import.

## Expected behavior

Validation error should appear.

## Screenshots

![image](https://user-images.githubusercontent.com/9052188/83974240-e0284700-a8e3-11ea-9773-1e1854fff29b.png)

**Comment by TheWitness** [comment]
Okay, this is cursory but addresses the issue at hand.
