### ISSUE TITLE
cacti.db import: ERROR 1071 (42000) at line 2560: Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by CapitalF** [Cacti/cacti#360]
This might have already been fixed in 1.0.4, not sure. Sorry if that's the case.

http://forums.cacti.net/viewtopic.php?f=2&t=56827

This guy said he was on Arch. I'm on Debian Unstable here and get the same thing.

Mariadb default config:

character-set-server  = utf8mb4
collation-server      = utf8mb4_general_ci

Probably just need to update the DB template.

**Comment by CapitalF** [comment]
Also note that on the install page/wizard, the "Recommended MySQL System Variable Settings" are utf8mb4_unicode_ci and utf8mb4, which doesn't work. That cacti.db template needs to get fixed.

**Comment by CapitalF** [comment]
Specifically, this is caused by two lines improperly containing character set and collate declarations during the creation of VDEF related tables:

```
-->egrep -i utf cacti.sql
  name varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL default '',
  value varchar(150) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL default '',
```

**Comment by cigamit** [comment]
Resolved thanks!

**Comment by CapitalF** [comment]
I was wrong about this, or at least provided incomplete information. My apologies.

It's true that those two lines needed to go anyway, but they were not the full source of the problem.

The problem is that the "utf8" character set is 3-byte and is not true "UTF8". The true UTF8 character set is utf8mb4, which is 4-bytes in size. All modern MySQL/MariaDB installations use utf8mb4 by default and changing this setting at the global level is probably not appropriate.

Because of the character byte size difference, index keys are no longer fitting in the innodb limit of 767 bytes. All of those indexes/keys that no longer fit are going to need to get reconsidered.

Until the database can be properly migrated to 4-byte UTF8, databases will need to be created with: "create database cacti DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;"

In addition to new databases being created correctly, there will probably need to be some kind of migration script to handle this.

**Comment by cigamit** [comment]
Resolved.
