### ISSUE TITLE
Zoom looses focus in preview graph display mode when graph title is turned on

### ISSUE THREAD

**Issue by hoswfh** [Cacti/cacti#3602]
After installing CACTI version 1.2.11,  the zoom in is not working at all. The zoom looses focus while crossing chart border. This happen when I turn on the graph title display. If the graph title is turned off, the zoom in is working fine. I find that if the graph title is long, the zoom will loose focus. However, if the title is within the graph border, it is working fine. Please advise how to resolve this issue. I have another CACTI server with version 0.8.8g and does not have this zoom in issue on the same graph display. In addition, left click to zoom in is also not working when in preview display mode.
Thank you.

**Comment by netniV** [comment]
I'm sure we changed the zoom process slightly in 1.2.12 because we found that the ability to drag/drop a graph was affected by zoom overlaying the graph too much.  Would you be able to test under 1.2.12 for the same issue?

**Comment by TheWitness** [comment]
Correct, the plugin author @browniebraun made a slight improvement recently for this issue.  You need to update the include/js/jquery.zoom.js from the 1.2.x branch and then refresh your page (F5 on Windows).

However, please note that there are also some important jQuery fixes that should be having your considering the 1.2.12 release.

**Comment by hoswfh** [comment]
Thanks for the advice. I had upgraded to cacti version 1.2.12 and still facing the same problem. 
Any more advice on how to solve this zoom in problem. I attached the graph image for your reference. Thank you.
<img width="1514" alt="zoom issue" src="https://user-images.githubusercontent.com/64879630/87382957-d1ac0a00-c5ca-11ea-97b5-04fbb951e808.PNG">
