### ISSUE TITLE
No Devices Found after updating from v1.2.9 to v1.2.11

### ISSUE THREAD

**Issue by karljohns0n** [Cacti/cacti#3604]
# Describe the bug

No Devices Found after updating from v1.2.9 to v1.2.11.

## To Reproduce

Browse http://cacti/host.php, it will show No Devices Found

## Expected behavior

List all 3 current devices

## Screenshots

![Screen Shot 2020-06-11 at 12 19 20](https://user-images.githubusercontent.com/13647791/84412858-d7828a00-abdd-11ea-80fc-7ec329a60c5d.png)

## Additional context

Everything is still working fine. I can see the devices in the database. Polling still working. No errors in cacti.log.

**Comment by bmfmancini** [comment]
I think this was a known issue back in 1.2.11 your location is being
filtered will null check the dropdown box

**Comment by bmfmancini** [comment]
Oh and I know the Classic theme also had some other bug try also switching to the Modern theme

**Comment by karljohns0n** [comment]
It was indeed the location being null per default. Thanks @bmfmancini
