### ISSUE TITLE
1.2.12 about 95th

### ISSUE THREAD

**Issue by 2019032** [Cacti/cacti#3606]
It's Zero.

**Comment by anarkia1976** [comment]
@2019032 Please send a full bug report with all infos, search into bugs the problem is already addressed.

**Comment by TheWitness** [comment]
This problem is already addressed.  It's duplicate.

**Comment by TheWitness** [comment]
It's formally fixed in 1.2.13 once released.  Otherwise, please search for the fix.

**Comment by 2019032** [comment]
Thx.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"TheWitness"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月13日(星期六) 晚上6:40
收件人:&nbsp;"Cacti/cacti"<cacti@noreply.github.com&gt;;
抄送:&nbsp;"2019032"<2019032@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Cacti/cacti] 1.2.12 about 95th (#3606)





 
Closed #3606.
