### ISSUE TITLE
Can't access log after been kicked out by timeout

### ISSUE THREAD

**Issue by arno-st** [Cacti/cacti#3607]
I have a strange issue.
When I'm kicked out of cacti by the timeout session, and my graph are display as guest.
I click as 'Login as regular user' and go to the authentication process as usual, I can't access the log file anymore.
I can't click to the tab Log, and if i access to the clog.php I have this error:
FATAL: YOU DO NOT HAVE ACCESS TO THIS AREA OF CACTI
But If I go to 'uttilites' -> 'System Utilities' -> 'log administration' I able to see my log.

But every other access are ok (based on my user right who is equivalent to admin)

And no error message on the log

It's on Cacti 1.2.12

**Comment by TheWitness** [comment]
Okay, I've confirmed and corrected this.  Update include/auth.php from the 1.2.x branch, and re-test.  If it works, please close.

**Comment by arno-st** [comment]
Oups something missing between 1.2.12 and the current develop release:

15/06/2020  09:00:03 - CMDPHP PHP ERROR WARNING Backtrace:   (/clog.php[27]:include(), /include/auth.php[28]:require_once(),  /include/global.php[505]:include_once(), /lib/auth.php[29]:include(),  /lib/auth.php[29]:CactiErrorHandler())
--
15/06/2020 09:00:03 - ERROR PHP : include(): Failed opening  '/usr/share/cacti/lib/../include/vendor/GoogleAuthenticator/RuntimeException.php'  for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in  file: /usr/share/cacti/lib/auth.php  on line: 29
15/06/2020 09:00:03 - CMDPHP PHP ERROR WARNING Backtrace:   (/clog.php[27]:include(), /include/auth.php[28]:require_once(),  /include/global.php[505]:include_once(), /lib/auth.php[29]:include(),  /lib/auth.php[29]:CactiErrorHandler())
15/06/2020 09:00:03 - ERROR PHP :  include(/usr/share/cacti/lib/../include/vendor/GoogleAuthenticator/RuntimeException.php):  failed to open stream: No such file or directory in file:  /usr/share/cacti/lib/auth.php  on line: 29
15/06/2020 09:00:03 - CMDPHP PHP ERROR WARNING Backtrace:   (/clog.php[27]:include(), /include/auth.php[28]:require_once(),  /include/global.php[505]:include_once(), /lib/auth.php[28]:include(),  /lib/auth.php[28]:CactiErrorHandler())
15/06/2020 09:00:03 - ERROR PHP : include(): Failed opening  '/usr/share/cacti/lib/../include/vendor/GoogleAuthenticator/GoogleQrUrl.php'  for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in  file: /usr/share/cacti/lib/auth.php  on line: 28

**Comment by TheWitness** [comment]
Looks like you pulled the file from the develop branch and not the 1.2.x branch.

**Comment by arno-st** [comment]
Yes, that's why I delete the messages.
i download the right one, and I'm testing it
I will let you know

**Comment by TheWitness** [comment]
Okay, cool.  I was able to confirm with my test environment, though sometimes I get it wrong.  So, just give an update and close if it's all good.

**Comment by arno-st** [comment]
Ok, I'm not kicked out anymore !
