### ISSUE TITLE
Using data input field in graph title

### ISSUE THREAD

**Issue by frankfer01** [Cacti/cacti#3608]
I trying to create a graph using a input field in the grah title, but is not working.
I created of this way:

![image](https://user-images.githubusercontent.com/55502569/84523710-2c420580-acaf-11ea-89b5-9be3580118de.png)
The operation is succeeded:
![image](https://user-images.githubusercontent.com/55502569/84523785-4e3b8800-acaf-11ea-8a57-23823a9771b7.png)

But when you look for the graph, did not work:
![image](https://user-images.githubusercontent.com/55502569/84523909-7f1bbd00-acaf-11ea-8884-395f4a1c2cdc.png)

![image](https://user-images.githubusercontent.com/55502569/84523971-90fd6000-acaf-11ea-808f-867de648f575.png)

I'm using Cacti version 1.2.10

Thanks in advance.

**Comment by frankfer01** [comment]
Hi, If I enter in Management-> Graph and click in the graph, then click in the unlock graph and save without change anything, it work!!!!, the graph change the name to the value of input field. So strange...

**Comment by TheWitness** [comment]
Thanks for reporting this.  Keep it queued for a bit as you have a workaround.

**Comment by TheWitness** [comment]
Still a bug.  Hating this blanking stalebot.

**Comment by TheWitness** [comment]
Outdated.  Bah, humbug.
