### ISSUE TITLE
Document MySQL TimeZone Setup Steps

### ISSUE THREAD

**Issue by CapitalF** [Cacti/cacti#361]
During a new installation (Linux), the following error message will appear:

ERROR: Your Cacti database login account does not have access to the MySQL TimeZone database. Please provide the Cacti database account "select" access to the "time_zone_name" table in the "mysql" database, and populate MySQL's TimeZone information before proceeding.

Discussed on the forum here:
http://forums.cacti.net/viewtopic.php?f=2&t=56815

This needs to be on the installation documentation.

Suggested fix goes something like this (please test/verify):

root-bash> mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root -p mysql

mysql> use mysql;
mysql> GRANT SELECT ON mysql.time_zone_name TO cactiuser@localhost;
mysql> flush privileges;

**Comment by browniebraun** [comment]
Agreed - this needs to be documented. Especially due to the fact that the steps for e.g. Windows or HP-UX are different.

**Comment by pautiina** [comment]
Please change Title. 
This problem has also been described #242

**Comment by macheretj** [comment]
Suggested Solution from CapitalF applied successfully.

**Comment by dtrinidad** [comment]
I have tried the solution but once I introduce the command "mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root -p mysql" it just ends.

Sample Output:

[root@cacti2 ~]# 
[root@cacti2 ~]# mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root -p mysql
Enter password: 
[root@cacti2 ~]#

**Comment by pautiina** [comment]
@dtrinidad 
Try this solution:

> On FreeBSD:
> 
> cd /usr/local/share/mysql 
> mysql -u root mysql < mysql_test_data_timezone.sql 
> Other UNIX:
> 
> cd /usr/share/mysql 
> mysql -u root mysql < mysql_test_data_timezone.sql 
> If you have mysql root passrword:
> mysql -u root -p mysql < mysql_test_data_timezone.sql
> 
> And you must add access cacti databes user for databases mysql or only for table:
> mysql.time_zone_name

You must have file  **mysql_test_data_timezone.sql** on your share directory OS. This file copy when you install `mysql-server`

**Comment by dtrinidad** [comment]
@pautiina 

Thanks for your guidance, thanks to it I've been able to fullfill my task. 

here is how I did this:

- First let me comment that I have a CentOS Installation.

- now the process:

[root@cacti2 mysql]#  mysql -u root -p mysql                                    
Enter password:                                                                 
Reading table information for completion of table and column names              
You can turn off this feature to get a quicker startup with -A                  
                                                                                
Welcome to the MariaDB monitor.  Commands end with ; or \g.                     
Your MariaDB connection id is 16                                                
Server version: 10.1.26-MariaDB MariaDB Server                                  
                                                                                
Copyright (c) 2000, 2017, Oracle, MariaDB Corporation Ab and others.            
                                                                                
Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.  
                                                                                
MariaDB [mysql]> GRANT SELECT ON mysql.time_zone_name TO cacti@localhost;       
Query OK, 0 rows affected (0.00 sec)                                            
                                                                                
MariaDB [mysql]> flush privileges;                                              
Query OK, 0 rows affected (0.00 sec)                                            
                                                                                
MariaDB [mysql]> exit                                                           
Bye                                                                             
[root@cacti2 mysql]#                                                            



thanks.

**Comment by cigamit** [comment]
This issue has been resolved in the documentation GitHub repo.
