### ISSUE TITLE
Unable to view Cacti ChangeLog from GUI

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#3611]
# Describe the bug

There is no way to view the Cacti ChangeLog from the GUI

## Expected behavior

There should be a location to access the Cacti ChangeLog from the GUI

## Additional context

This issue is closely related to #3590 but will not go as far.

**Comment by netniV** [comment]
I've changed this from a bug to a feature, because it's not really a bug that you can't do it.
