### ISSUE TITLE
upgrading from 0.8.8h to 1.2.12 causes multiple database upgrade errors

### ISSUE THREAD

**Issue by smarteyesi** [Cacti/cacti#3612]
# Describe the bug

## To Reproduce

Original cacti.sql was using MyISAM tables instead of InnoDB

Running cli/upgrade_database.php as part of package update...
Upgrading from v1.1.2
Upgrading from v1.1.2 (DB 1.1.2) to v1.1.4
--------xx---------------
################################
[Fail]       -   DB Exec Failed!, Error 1071: Specified key was too long; max key length is 1000 bytes
+------------------------------+
ALTER TABLE `snmpagent_cache` ADD INDEX mib_name(mib,name)
################################

################################
[Fail]       -   DB Exec Failed!, Error 1071: Specified key was too long; max key length is 1000 bytes
+------------------------------+
ALTER TABLE `snmpagent_cache` ADD INDEX mib_name(mib,name)

**SOLUTION: CHANGE tables to MyISAM to INNODB and enable innodb_large_index**

Upgrading from v1.1.3
Upgrading from v1.1.3 (DB 1.1.3) to v1.1.4
--------++---------------Upgrading from v1.1.4 (DB 1.1.4) to v1.1.6
++++++++++++++++++++++++++-+++++Upgrading from v1.1.6 (DB 1.1.6) to v1.1.7
+Upgrading from v1.1.7 (DB 1.1.7) to v1.1.8
+Upgrading from v1.1.8 (DB 1.1.8) to v1.1.11
+++Upgrading from v1.1.11 (DB 1.1.11) to v1.1.14
+Upgrading from v1.1.14 (DB 1.1.14) to v1.1.17
+++++++++++++++++++++++++++Upgrading from v1.1.17 (DB 1.1.17) to v1.1.20
++-+++-++++-+++Upgrading from v1.1.20 (DB 1.1.20) to v1.1.26
++++++++-Upgrading from v1.1.26 (DB 1.1.26) to v1.1.28
++++++-++Upgrading from v1.1.28 (DB 1.1.28) to v1.1.31
++++++++Upgrading from v1.1.31 (DB 1.1.31) to v1.1.34
x-++-++++++++++++++++++++-+-+++++++++-+++-+++++++++++++++++++-++-++
################################
[Fail]       -   DB Exec Failed!, Error 1054: Unknown column 'snmp_readstring' in 'automation_snmp_items'
+------------------------------+
ALTER TABLE `automation_snmp_items` CHANGE COLUMN `snmp_readstring` `snmp_community` varchar(50) NOT NULL DEFAULT ""

That table doesnt exist...

**Comment by netniV** [comment]
Your issue is that you need to set the MySQL innodb recommendations that was displayed on one of the first pages of the upgrade wizard. This includes the large prefix and some of the others. There are previous issues on here about that.

**Comment by smarteyesi** [comment]
The upgrade wizard did not run and threw an 500 error message when trying
to continu.

CLI upgrade_database was used instead to try to resolve the issue of very
old upgrade path to recent

Op zo 14 jun. 2020 om 20:12 schreef Mark Brugnoli-Vinten <
notifications@github.com>:

**Comment by TheWitness** [comment]
You need to reread the comment from @netniV.  Upgrading requires you to do some research and prepare your database for the upgrade.  If the documentation is not clear on this, that is the real bug.
