### ISSUE TITLE
Tree management limited to 20 devices and graphs

### ISSUE THREAD

**Issue by jayaich** [Cacti/cacti#3613]
# Describe the bug

On the tree management page the 'Device Description' and 'Graph Name' columns both seem to be limited to 20 rows. We have more than 20 of both of these.
This is using Cacti 2.1.12.

## To Reproduce

1. Go to 'Console => Management'

2. Click on 'Trees' and select a tree to view/modify.

## Expected behavior

Both the device and graphs columns should be populated with all the devices and graphs.
Scroll bars should appear when the list is long.

## Desktop (please complete the following information)

- OS: CentOS 7

- Browser Firefox

- Version 77.0.1

## Additional context

I took a look at the 'tree.php' file. The '20' limits seem clear in the file. I removed them, and the device/graph columns then showed all the relevant items and scroll bars. Not sure that this is the correct fix though, so just submitted as a suggestion. Attached is a unified diff file of the changes (only 2 lines).

[tree.php-diff.txt](https://github.com/Cacti/cacti/files/4780117/tree.php-diff.txt)

**Comment by cigamit** [comment]
This is not a bug, as it is by design.  It may work for removing it for your scenario, but when you have 10000 servers, it doesn't work so well.  If you click on "Available Devices" or "Available Graphs" it should show a search box to allow you to filter to exactly what you are looking for.

The only change I would recommend to this, is instead changing the 20 limit to a definable setting (but still set a maximum allowed on it).

**Comment by TheWitness** [comment]
The limit is configurable too. Console > Configuration > Settings > Visual > Autocomplete Rows.

**Comment by jayaich** [comment]
Thanks for the replies.
We already have the autocomplete rows set to 30, but it is still not listing all our devices (24 of them).

I would agree that a configurable limit would be the best way to go. If the 'autocomplete' setting is supposed to do that, then, as said, it doesn't seem to be working for managing trees.

**Comment by TheWitness** [comment]
Sounds like a bug then.

**Comment by netniV** [comment]
Are you able to provide screenshots? If they are sensitive in nature, please email them to developers@cacti.net

A picture can say a thousand words so I imagine several will be a novel in this case ;-)

**Comment by jayaich** [comment]
Screenshot attached of the trees management page we see. We have 24 devices, and 238 graphs, but as can be seen all we get are 20 of each and no scroll bars. (Searching is possible as a solution, but I think providing a list would be preferred by the users (ours anyway!))
![Screenshot_20200615_174016](https://user-images.githubusercontent.com/6230023/84684261-53f3d080-af30-11ea-965e-db6185420a60.png)
.

**Comment by cigamit** [comment]
@TheWitness Ya, I didn't think the autocomplete rows applied here (and it doesn't appear to) as mine is set to 10, and I have 20 in my listing also (and it appears to be hard coded to 20).  We will want to fix this.

**Comment by TheWitness** [comment]
Okay, you just have to update tree.php from the 1.2.x branch.

**Comment by jayaich** [comment]
Thanks for that. The new tree.php seems to work fine.
I'll close this issue.
