### ISSUE TITLE
UI Frontend little bug, menu tabs covering title bar 

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#3614]
# Describe the bug
![ui-cacti](https://user-images.githubusercontent.com/17087236/84664524-f3a86300-af1e-11ea-9a8f-f2bfec15c6d4.png)

## Expected behavior
The tabs are not covering panel title when windows is small.

Browser: Chromium/Ubuntu

**Comment by netniV** [comment]
What cacti version and theme?

**Comment by interduo** [comment]
branch: 1.2.x
theme: modern

**Comment by TheWitness** [comment]
Okay, this is fixed in the 1.2.x branch.

**Comment by interduo** [comment]
Are issues closed when next numbered version is released?

**Comment by netniV** [comment]
If there is nothing outstanding

**Comment by interduo** [comment]
Thanks for resolving btw ;)
