### ISSUE TITLE
Poller keeps using old IP address for a device

### ISSUE THREAD

**Issue by PE1NUT** [Cacti/cacti#3615]
Recently one of our switches got assigned a new IP address. In Cacti, I changed this in the device definition page (new IP address in the 'hostname' field). After saving it, it correctly shows the SNMP uptime, hostname, location and contact, confirming that cacti can connect to it.

All seemed well, but it turns out that the graphs for this device are no longer being updated. After enabling debugging for the device, I find this in the log file:

"2020-06-16 12:26:11 - POLLER: Poller[Main Poller] Device[switch1] STATUS: Device '10.0.0.1' is Down." 

Note that 10.0.0.1 is the OLD address for the device, not the new address that was configured through the interface. The word 'switch1' is a hyperlink which leads to the correct page for the device in question, and shows the updated IP address in the 'hostname' field.

Things I've tried to remedy this:
* Saving the device page, changing the IP address to something else and back
* Rebuilding the poller cache
* Rebooting the cacti server

None of these helped, and the poller continues to try and connect to the device on its old IP address.
Note that the IP address/hostname are not in use for any other device.

## To Reproduce

I don't seem to be able to reproduce this behaviour - if I change (in Cacti) the IP address for another device to a non-existing IP, it seems that the poller picks this right up without issues. However, for this one device, I can't get the poller to use the new IP address.

## Expected behavior

Upon changing the device information, poller should pick up the new hostname/IP address, or log a clear error why it cannot.

## Cacti Server:

- Debian 10
- Version 1.2.10 (from Debian package)

## Desktop:

- Ubuntu 20.20
- Firefox 77.0.1

**Comment by PE1NUT** [comment]
Update: resolved it by running a MySQL command: 'update poller_item set hostname = 'x.x.x.x' where host_id = 5;

**Comment by TheWitness** [comment]
You say it's working for some devices and not others.  Well, that does not make much sense.  Might be your templates and not as much a Cacti issue.

**Comment by PE1NUT** [comment]
Thanks for the reply. As I found a (brute force) workaround and am not able to reproduce this with other hosts, I don't think much progress can be made. Closing the ticket.

**Comment by netniV** [comment]
The other thing to check is if it using a host name are there any dns issues such as multiple entries or in the system hosts file.
