### ISSUE TITLE
Cacti 1.2.12 | Moved database dir | Cacti can't acess mysql through default port 3306 from localhost or poller

### ISSUE THREAD

**Issue by zuka1337** [Cacti/cacti#3617]
**WORK: The only way I can localy acess is to specify the locaction dir of the database in DATABASE_PORT ex:**

$database_type     = 'mysql';
$database_default  = 'database';
$database_hostname = 'localhost';
$database_username = 'cacti';
$database_password = 'password';
**$database_port     = 'common/mysql/mysql.sock**et';
$database_retries  = 5;
$database_ssl      = false;
$database_ssl_key  = '';
$database_ssl_cert = '';
$database_ssl_ca   = '';

**DOES NOT WORK: Cacti is trying to connect the database but it can't reach like this:**

$database_type     = 'mysql';
$database_default  = 'database';
$database_hostname = 'localhost';
$database_username = 'cacti';
$database_password = 'password';
**$database_port     = '3306';**
$database_retries  = 5;
$database_ssl      = false;
$database_ssl_key  = '';
$database_ssl_cert = '';
$database_ssl_ca   = '';

**NOT WORKING: Remote Poller**

$rdatabase_type     = 'mysql';
$rdatabase_default  = 'database_main';
$rdatabase_hostname = 'remote_host';
$rdatabase_username = 'cacti';
$rdatabase_password = 'password';
$rdatabase_port     = '3306'
$rdatabase_retries  = 5;
$rdatabase_ssl      = false;

**How I moved the database:**

**First check the default dir:**

MariaDB [(none)]> select @@datadir;

Output
```
+-----------------+
| @@datadir       |
+-----------------+
| /var/lib/mysql/ |
+-----------------+
1 row in set (0.00 sec
```

**Stoped process:**

`sudo systemctl stop mysqld
`

**Rsynk the default database dir to the new location**

`sudo rsync -av /var/lib/mysql /common/`

**Rename old mysql**

`sudo mv /var/lib/mysql /var/lib/mysql.bak
`

**Edit my.conf fie:**
```

    sudo vi /etc/my.cnf
    [mysqld]
    . . .
    datadir=/common/mysql
    socket=/common/mysql/mysql.sock
    . . .

```

**start mysql:**

`sudo systemctl start mysqld`

**New location datadir;**

```
MariaDB [(none)]> select @@datadir;
+----------------+
| @@datadir      |
+----------------+
| /common/mysql/ |
+----------------+
1 row in set (0.000 sec
MariaDB [(none)]> SHOW VARIABLES WHERE Variable_name = 'port'
    -> ;
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| port          | 3306  |
+---------------+-------+
1 row in set (0.001 sec)
```

**Comment by zuka1337** [comment]
Config Error: Solved with:

my.conf
[client-server]
port=3306

**Comment by TheWitness** [comment]
yea, I really don't see a Cacti problem here.  If you "want" to use the socket, you have to put the socket file path in the $database_hostname, not the port too.
