### ISSUE TITLE
Page broken after save any settings  1.3.0 - Dev f27e609ca

### ISSUE THREAD

**Issue by xmacan** [Cacti/cacti#3618]
# Describe the bug
Fresh 1.3.0 devel with fresh db (mysql -p cacti_develop < cacti.sql)
Go to settings->tab path, general (maybe more) and click save
Result is:
![Screenshot_2020-06-16 Console - Cacti Settings](https://user-images.githubusercontent.com/26485719/84823828-45381700-b01f-11ea-9f07-3aebdd1f1966.png)

Browser firefox

**Comment by netniV** [comment]
And that was from Console > Settings ?

**Comment by TheWitness** [comment]
Once you hit 'save'.  The callback handler is not parsing out the head and navigation and only leaving main.  Same for Graph Pagination, actually any pagination.

**Comment by TheWitness** [comment]
Yea, just looking at the code, we need to come up with a loadUrl() function for post data as the responses were all relying on the header=false to remove evertying except 'main'.  We have $.post() riddled through the code in many places.

**Comment by TheWitness** [comment]
The pagination bug is going to be focused in one file only lib/html.php.  Just need it to call loadUrl() with the right id for returning the content to.  Will have to strip the headers and navigation as well.

**Comment by netniV** [comment]
There is code in global that detects if the call is Ajax based and removes the headers/nav. Sounds like that isn’t being applied on post or that the pages in question aren’t using the detected value. 

We knew there might be a few of these as we transitioned under 1.3 to allow back and forth to start working properly with relying on variables. 

I’ll did consider a `loadUtl`  that handled posts but wasn’t convinced at the time as many seemed to operate slightly different.

**Comment by TheWitness** [comment]
Well, that's the rub, everything is a callback, but on some pages we want to remove the header, and on some pages, we need it to populate the page title and breadcrumbs.

**Comment by netniV** [comment]
I will take a look at these examples and see the best way forward.

**Comment by netniV** [comment]
OK, this should now be resolved most with c0358397858df72bda49c4ff23fa815100804e60 (with the tiniest QA I've ever made in 57b468211ee7ed0be1475364ab730b1da6d20ed3)
