### ISSUE TITLE
Extremely slow new graph/DS creation in Cacti 1.0.3

### ISSUE THREAD

**Issue by CapitalF** [Cacti/cacti#362]
Reopening improperly closed issue: https://github.com/Cacti/cacti/issues/338

I have updated my issue below after further testing.

I am having a problem where new graph and DS creation in a new Cacti 1.0.3 installation is taking an extremely long time. Something is very wrong, but I'm not sure where the problem is yet.

I should note that I get a general impression that writing to the DB is slow, but I don't notice significant problems elsewhere. Creating new graphs may just be the most DB-write-intensive example that stands out.

I did a bunch of benchmarks on this hardware to make sure that it wasn't slow disk or something else going on and all of those tests showed positive results. I also ran some seperate mysql DB tests and they showed good results too, so I don't think this is isolated to the mariadb install/config.

On average, new graphs (3-5 DS per) are taking 6-8 seconds to be created. This is an estimate based on eight different tests creating various graphs on some 48 port switches. Creating approximately 120 graphs with 240 DS ( about two per graph) took 13 minutes and 48 seconds on average. These tests were repeated many times and resulted in very reliable results in regards of how long it took to finish. I was able to come back to my stopwatch and see the page finish roughly when I expected it to.

The tests above were conducted on an Intel Haswell PC from 2013/2014. i5-4570 CPU 3.20GHz. The disks/storage are three 2TB desktop-type drives in a RAID5. The storage is pretty fast, but it's not like SSD-fast. This is not a VM -- main testing installation is on hardware, but I used VMs on this hardware to further test.

I set up a nearly-identical VM on the same hardware mentioned above but used the Debian Cacti 0.8.8h+ds1-8 package with identical Device Templates and it took less than two seconds to create the same 120 graphs from the same host mentioned above.

I created a second VM on this hardware to verify my results on Cacti 1.0.3 and had the same slowness problems. This install was as fresh as I could make it. The only thing I imported was the device template so that I could reproduce the graphs and DS. All other Cacti, php, and mariadb configuration was as default as possible.

Then I tested on a second set of faster hardware. Intel Skylake i7; SSD storage, etc. This is a very fast high-end system. All tests were done on VMs, but this system isn't very heavily loaded and I have exclusive control over what is running (it's my desktop).

On this faster hardware, the 0.8.8h installation takes 1 second or less to create the 120 graphs.

On a 1.0.3 installation it took 2 minutes 52 seconds to make the 120 graphs. I did a bunch of other graph creation tests and estimated that the average graph was taking 1.9 seconds to create. It's a lot faster, but it's still really slow in comparison to 0.8.8h.

It's possible that some configuration I've made is related, but I'm not certain what it would be. I've made my tests systems as basic as I could.

Can I get someone with some slower HDD disks to test out graph creation times on 1.0.x to reproduce or deny my findings?

**Comment by CapitalF** [comment]
I've replicated this now on a third system. Cacti 1.0 is just extremely slow compared to Cacti 0.8.8h. There is something very wrong.

**Comment by cigamit** [comment]
Please create using the two method, and upload results:
1) put cacti in developer debug mode and create a graph or two, upload cacti log for that transaction
2) put cacti into 'Classic' theme and several graphs at once.  Was there any measurable difference in timing
3) create graphs while using Chrome's Timeline function to profile the transactions to see where the delay occurs.  Export the profile output and upload here.

**Comment by cigamit** [comment]
No feedback.
