### ISSUE TITLE
PHP Recommendation (web)  date.timezone issue

### ISSUE THREAD

**Issue by dongmush** [Cacti/cacti#3623]
![image](https://user-images.githubusercontent.com/67049695/84881199-1e7ded00-b0c0-11ea-82fa-19deb2861ee2.png)

I having this issue while i just follow the step by step to setup the cacti server in Centos 7:
https://www.itzgeek.com/how-tos/linux/centos-how-tos/monitor-network-using-cacti-with-centos-7-rhel-7.html

anyone can help on this.Many Thanks~

**Comment by netniV** [comment]
It basically means that you haven’t set it in your PHP ini file for the web
