### ISSUE TITLE
Cacti Website: All versions show the same release notes

### ISSUE THREAD

**Issue by PE1NUT** [Cacti/cacti#3633]
The main webpage at cacti.net shows the latest releases, and a link to the release notes for each version in the 'Latest News' section. However, clicking on such a link always leads to the changelog of the latest version, despite the URL indicating that it should show the one pertaining to that release.

## To Reproduce

Go to https://cacti.net/ and click on the changelog for a release.

https://www.cacti.net/release_notes.php?version=1.2.11

https://www.cacti.net/release_notes.php?version=1.2.10

The above URLs all end up showing the release notes for 1.2.12.

## Expected behavior

Show the release notes that go with the version in question.

## Desktop (please complete the following information)

- OS: Ubuntu 20.20LTS

- Browser: Firefox 77.0.1

**Comment by netniV** [comment]
Thanks for reporting this.  It should now be working again.
