### ISSUE TITLE
[Feature Request] Add date and timestamp to cacti_stderr.log

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3634]
Hey Guys 

It would be nice to have a date and time stamp in the cacti_stderr.log file 

Thanks !

**Comment by TheWitness** [comment]
Since we don't really control what goes in there, we could just write a timestamp at the beginning of a poller run.

**Comment by netniV** [comment]
The standard error can contain errors from outside of cacti by processes which are run by cacti.  As we only trap standard error in a rare number of cases, there is always a possibility of having rogue messages appear to stderr.  One way to ensure a timestamp on that would be using `tee` or `ts` before it to add the timestamp to each line.

As such, whilst we appreciate the suggestion, I think our efforts are better focused elsewhere.
