### ISSUE TITLE
cacti V1.2.12 Backtrace errors running AUTOM8

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3635]
Hey Everyone 

I can across these errors today running Apply automation rules on a single device 
The graphs were created as far as I can see 

![image](https://user-images.githubusercontent.com/13388748/85414786-8c03a080-b53a-11ea-9ba9-1a8b870065ab.png)

**Comment by bmfmancini** [comment]
Here is the full error 

2020/06/23 09:58:36 - CMDPHP PHP ERROR NOTICE Backtrace: (/remote_agent.php[72]:run_remote_data_query(), /remote_agent.php[439]:run_data_query(), /lib/data_query.php[398]:automation_execute_data_query(), /lib/api_automation.php[2200]:create_dq_graphs(), /lib/api_automation.php[2512]:create_complete_graph_from_template(), /lib/template.php[1341]:api_plugin_hook_function(), /lib/plugins.php[114]:api_plugin_run_plugin_hook_function(), /lib/plugins.php[218]:thold_create_graph_thold(), /plugins/thold/setup.php[1432]:autocreate(), /plugins/thold/thold_functions.php[5220]:thold_raise_message(), /plugins/thold/thold_functions.php[4929]:raise_message(), /lib/functions.php[720]:cacti_session_start(), /lib/functions.php[5541]:CactiErrorHandler())

2020/06/23 09:58:36 - ERROR PHP NOTICE: Undefined index: cacti_session_name in file: /var/www/html/cacti/lib/functions.php on line: 5541

2020/06/23 09:58:35 - CMDPHP PHP ERROR WARNING Backtrace: (/remote_agent.php[72]:run_remote_data_query(), /remote_agent.php[439]:run_data_query(), /lib/data_query.php[398]:automation_execute_data_query(), /lib/api_automation.php[2200]:create_dq_graphs(), /lib/api_automation.php[2512]:create_complete_graph_from_template(), /lib/template.php[1341]:api_plugin_hook_function(), /lib/plugins.php[114]:api_plugin_run_plugin_hook_function(), /lib/plugins.php[218]:thold_create_graph_thold(), /plugins/thold/setup.php[1432]:autocreate(), /plugins/thold/thold_functions.php[5222]:thold_raise_message(), /plugins/thold/thold_functions.php[4929]:raise_message(), /lib/functions.php[720]:cacti_session_start(), /lib/functions.php[5543]:session_start(), CactiErrorHandler())

2020/06/23 09:58:35 - ERROR PHP WARNING: session_start() expects parameter 1 to be array, null given in file: /var/www/html/cacti/lib/functions.php on line: 5543

2020/06/23 09:58:35 - CMDPHP PHP ERROR NOTICE Backtrace: (/remote_agent.php[72]:run_remote_data_query(), /remote_agent.php[439]:run_data_query(), /lib/data_query.php[398]:automation_execute_data_query(), /lib/api_automation.php[2200]:create_dq_graphs(), /lib/api_automation.php[2512]:create_complete_graph_from_template(), /lib/template.php[1341]:api_plugin_hook_function(), /lib/plugins.php[114]:api_plugin_run_plugin_hook_function(), /lib/plugins.php[218]:thold_create_graph_thold(), /plugins/thold/setup.php[1432]:autocreate(), /plugins/thold/thold_functions.php[5222]:thold_raise_message(), /plugins/thold/thold_functions.php[4929]:raise_message(), /lib/functions.php[720]:cacti_session_start(), /lib/functions.php[5543]:CactiErrorHandler())

2020/06/23 09:58:35 - ERROR PHP NOTICE: Undefined index: cookie_options in file: /var/www/html/cacti/lib/functions.php on line: 5543

2020/06/23 09:58:35 - CMDPHP PHP ERROR WARNING Backtrace: (/remote_agent.php[72]:run_remote_data_query(), /remote_agent.php[439]:run_data_query(), /lib/data_query.php[398]:automation_execute_data_query(), /lib/api_automation.php[2200]:create_dq_graphs(), /lib/api_automation.php[2512]:create_complete_graph_from_template(), /lib/template.php[1341]:api_plugin_hook_function(), /lib/plugins.php[114]:api_plugin_run_plugin_hook_function(), /lib/plugins.php[218]:thold_create_graph_thold(), /plugins/thold/setup.php[1432]:autocreate(), /plugins/thold/thold_functions.php[5222]:thold_raise_message(), /plugins/thold/thold_functions.php[4929]:raise_message(), /lib/functions.php[720]:cacti_session_start(), /lib/functions.php[5541]:session_name(), CactiErrorHandler())

2020/06/23 09:58:35 - ERROR PHP WARNING: session_name(): session.name cannot be a numeric or empty '' in file: /var/www/html/cacti/lib/functions.php on line: 5541

2020/06/23 09:58:35 - CMDPHP PHP ERROR NOTICE Backtrace: (/remote_agent.php[72]:run_remote_data_query(), /remote_agent.php[439]:run_data_query(), /lib/data_query.php[398]:automation_execute_data_query(), /lib/api_automation.php[2200]:create_dq_graphs(), /lib/api_automation.php[2512]:create_complete_graph_from_template(), /lib/template.php[1341]:api_plugin_hook_function(), /lib/plugins.php[114]:api_plugin_run_plugin_hook_function(), /lib/plugins.php[218]:thold_create_graph_thold(), /plugins/thold/setup.php[1432]:autocreate(), /plugins/thold/thold_functions.php[5222]:thold_raise_message(), /plugins/thold/thold_functions.php[4929]:raise_message(), /lib/functions.php[720]:cacti_session_start(), /lib/functions.php[5541]:CactiErrorHandler())

2020/06/23 09:58:35 - ERROR PHP NOTICE: Undefined index: cacti_session_name in file: /var/www/html/cacti/lib/functions.php on line: 5541

2020/06/23 09:58:35 - CMDPHP PHP ERROR WARNING Backtrace: (/remote_agent.php[72]:run_remote_data_query(), /remote_agent.php[439]:run_data_query(), /lib/data_query.php[398]:automation_execute_data_query(), /lib/api_automation.php[2200]:create_dq_graphs(), /lib/api_automation.php[2512]:create_complete_graph_from_template(), /lib/template.php[1341]:api_plugin_hook_function(), /lib/plugins.php[114]:api_plugin_run_plugin_hook_function(), /lib/plugins.php[218]:thold_create_graph_thold(), /plugins/thold/setup.php[1432]:autocreate(), /plugins/thold/thold_functions.php[5222]:thold_raise_message(), /plugins/thold/thold_functions.php[4929]:raise_message(), /lib/functions.php[720]:cacti_session_start(), /lib/functions.php[5543]:session_start(), CactiErrorHandler())

2020/06/23 09:58:35 - ERROR PHP WARNING: session_start() expects parameter 1 to be array, null given in file: /var/www/html/cacti/lib/functions.php on line: 5543

2020/06/23 09:58:35 - CMDPHP PHP ERROR NOTICE Backtrace: (/remote_agent.php[72]:run_remote_data_query(), /remote_agent.php[439]:run_data_query(), /lib/data_query.php[398]:automation_execute_data_query(), /lib/api_automation.php[2200]:create_dq_graphs(), /lib/api_automation.php[2512]:create_complete_graph_from_template(), /lib/template.php[1341]:api_plugin_hook_function(), /lib/plugins.php[114]:api_plugin_run_plugin_hook_function(), /lib/plugins.php[218]:thold_create_graph_thold(), /plugins/thold/setup.php[1432]:autocreate(), /plugins/thold/thold_functions.php[5222]:thold_raise_message(), /plugins/thold/thold_functions.php[4929]:raise_message(), /lib/functions.php[720]:cacti_session_start(), /lib/functions.php[5543]:CactiErrorHandler())

2020/06/23 09:58:35 - ERROR PHP NOTICE: Undefined index: cookie_options in file: /var/www/html/cacti/lib/functions.php on line: 5543

2020/06/23 09:58:35 - CMDPHP PHP ERROR WARNING Backtrace: (/remote_agent.php[72]:run_remote_data_query(), /remote_agent.php[439]:run_data_query(), /lib/data_query.php[398]:automation_execute_data_query(), /lib/api_automation.php[2200]:create_dq_graphs(), /lib/api_automation.php[2512]:create_complete_graph_from_template(), /lib/template.php[1341]:api_plugin_hook_function(), /lib/plugins.php[114]:api_plugin_run_plugin_hook_function(), /lib/plugins.php[218]:thold_create_graph_thold(), /plugins/thold/setup.php[1432]:autocreate(), /plugins/thold/thold_functions.php[5222]:thold_raise_message(), /plugins/thold/thold_functions.php[4929]:raise_message(), /lib/functions.php[720]:cacti_session_start(), /lib/functions.php[5541]:session_name(), CactiErrorHandler())

2020/06/23 09:58:35 - ERROR PHP WARNING: session_name(): session.name cannot be a numeric or empty '' in file: /var/www/html/cacti/lib/functions.php on line: 5541

2020/06/23 09:58:35 - CMDPHP PHP ERROR NOTICE Backtrace: (/remote_agent.php[72]:run_remote_data_query(), /remote_agent.php[439]:run_data_query(), /lib/data_query.php[398]:automation_execute_data_query(), /lib/api_automation.php[2200]:create_dq_graphs(), /lib/api_automation.php[2512]:create_complete_graph_from_template(), /lib/template.php[1341]:api_plugin_hook_function(), /lib/plugins.php[114]:api_plugin_run_plugin_hook_function(), /lib/plugins.php[218]:thold_create_graph_thold(), /plugins/thold/setup.php[1432]:autocreate(), /plugins/thold/thold_functions.php[5222]:thold_raise_message(), /plugins/thold/thold_functions.php[4929]:raise_message(), /lib/functions.php[720]:cacti_session_start(), /lib/functions.php[5541]:CactiErrorHandler())

2020/06/23 09:58:35 - ERROR PHP NOTICE: Undefined index: cacti_session_name in file: /var/www/html/cacti/lib/functions.php on line: 5541

**Comment by TheWitness** [comment]
@bmfmancini, if you can update lib/api_device.php and include/global.php and test again.  The remote_agent.php was being denied a session due to a setting in global.php, which caused this error.

**Comment by bmfmancini** [comment]
Hey Larry so far this is looking good in the Lab no errors popping up  however my lab only has a few devices so not a large scale 
would this only come up under a certain condition on my lab v1.2.12 before the update was applied I ran autom8 no backtrace errors came up 

However I still went ahead and applied the new commits just to make sure nothing else broke 

I will apply this to our production system  soon which is where I saw the original issue 

Thanks !

**Comment by bmfmancini** [comment]
This looks good as well! 

Thanks
