### ISSUE TITLE
Spikekill method variable is misinterpreted when calculating overall statistics

### ISSUE THREAD

**Issue by riversdev0** [Cacti/cacti#3636]
# Describe the bug

The Spikekill script accepts a few input parameters when it's run, one of which is the "method".  This is either `stddev`, `variance`, `float`, or `fill`.  At the beginning of the script, these four values are assigned the numbers 1 through 4, respectively.  During the `calculateOverallStatistics` function, the values of 1 and 2 are misinterpreted such that a value of 1 indicates variance, and 2 indicates stddev.

## To Reproduce

This behavior occurs every time the spikekill script is run.

## Expected behavior

If the variables are interpreted correctly, this will result in the DryRun table containing accurate data.

## Screenshots

n/a

## Desktop (please complete the following information)

n/a

## Smartphone (please complete the following information)

n/a

## Additional context

n/a

**Comment by riversdev0** [comment]
I've spent a handful of hours over the last week trying to understand how this script is supposed to work because it has not been producing anything helpful for me.  I've come to see that there are a couple logic problems contained within, and several things that perhaps could be errors, but I'm not sure.

This leads me to three questions:

1) I fully understand what a "stddev kill" and a "variance kill" is, but could someone please help me understand what a "window kill" is, what a "float kill" is, and what a "fill kill" is?  From the code, I can read what these do, but I'm just not understanding what they are for.

2) Currently, the logic of the script is to count the number of kills before then performing the kills.  I'd like to re-tool the script so that it performs the kills while counting them, and simply omits writing to disk when `DryRun` is `true`.  Would the maintainers be in favor of me doing this?

3) The 13 lines following `/* check for outlier territory */` are confusing to me.  Can someone tell me if this is intended behavior, or if that part is mixed up, also?

**Comment by TheWitness** [comment]
I believe that:

1) window kill replaces all data in the time window with the starting data, 
2) flow kill will fill gaps in the time window with the last known good data.

If the data is 0, there should be an option to float to the last zero, but can not remember.  If the data is NAN, the float should update it.

2) I'm good with that.  Using something like SQLite for this would really speed things up.  Look at the script splice_rrd.php for a good example.  Might make the process go much faster too.

3) I have no problem with you owning it.  Go for it.

4) Outliers are number that are outside/above of the say 95th percentile.  If you are calculating something live an average or variance, you might want to skip those numbers as they will skew the expected variance.

Sorry, a lot of statistics, and when I wrote this thing way back when, my brain moved faster than the keyboard.  Not the same problem these days, but there is never enough time.

**Comment by riversdev0** [comment]
A few questions:
1) I'd like to change the functionality of the StdDev and Variance methods to be time-bound like the Range and Fill methods are. Is this an acceptable change to make?
2) When I'm finished, what code branch should this be merged into? Can you briefly help me understand the difference between 1.2.x, 1.3, and develop?
3) The script's behavior will be changing slightly. Are there some release notes that should mention these changes?
4) Is there documentation for SpikeKill?  If not, and if I were to write some, where would it belong?

**Comment by TheWitness** [comment]
Create a pull request against 1.2.x, and we'll evaluate.  We delayed the release again, but try to have it in before the weekend if you would like it to go out soon.

**Comment by TheWitness** [comment]
As far as doco is concerned, we have a repo for that, and if there is something special for the release notes, type up a paragraph and send to developers at cacti dot net.  @netniV, will give it a once over.

**Comment by netniV** [comment]
1.3.0-dev is an old branch. It was merged if I develop. However due to the way git works, people still have local branches with it in as we can’t force that removal from the local ones. 

Personally, I would prefer such a big change to go against 1.3.0 so there’s time to test it and make sure things are right as to me it’s more akin to a new feature since the idea is to link it to the range. 

TheWitness would say it’s a  bug fix and want to make people happy by getting it out a.s.a.p. coz he has a big heart :)

My gut says, no to the 1.2.13 release. Maybe .14 depending on what’s involved and how the tests go. If there are any compelling arguments either way then I’m open for discussion

**Comment by TheWitness** [comment]
Yea, and there is that open bug about the multiple RRDfile case that needs attention too.  So, take a shot at it, then like Mark said, well think about it and if nothing else, it'll be in the pipeline for long term merging.
