### ISSUE TITLE
SQL backtraces after DB restart cacti V1.2.12

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3637]
Hey Everyone

I did a simple restart of mysql to add a error log path cacti came back up all is well in terms of the DB connection between cacti and mariadb  gui works even graphs poll new data but the log gets smashed with these errors 

2020/06/23 12:19:46 - CMDPHP SQL Backtrace: (/poller.php[816]:api_plugin_hook(), /lib/plugins.php[74]:api_plugin_run_plugin_hook(), /lib/plugins.php[177]:thold_poller_bottom(), /plugins/thold/includes/polling.php[45]:thold_check_all_thresholds(), /plugins/thold/includes/polling.php[473]:thold_check_threshold(), /plugins/thold/thold_functions.php[2580]:thold_check_baseline(), /plugins/thold/thold_functions.php[4255]:thold_get_ref_value(), /plugins/thold/thold_functions.php[4180]:rrdtool_function_fetch(), /lib/rrd.php[899]:boost_fetch_cache_check(), /lib/boost.php[272]:boost_process_poller_output(), /lib/boost.php[626]:db_fetch_cell(), /lib/database.php[386]:db_fetch_cell_prepared(), /lib/database.php[402]:db_execute_prepared())
2020/06/23 12:19:46 - CMDPHP SQL Backtrace: (/poller.php[816]:api_plugin_hook(), /lib/plugins.php[74]:api_plugin_run_plugin_hook(), /lib/plugins.php[177]:thold_poller_bottom(), /plugins/thold/includes/polling.php[45]:thold_check_all_thresholds(), /plugins/thold/includes/polling.php[473]:thold_check_threshold(), /plugins/thold/thold_functions.php[2580]:thold_check_baseline(), /plugins/thold/thold_functions.php[4255]:thold_get_ref_value(), /plugins/thold/thold_functions.php[4180]:rrdtool_function_fetch(), /lib/rrd.php[899]:boost_fetch_cache_check(), /lib/boost.php[272]:boost_process_poller_output(), /lib/boost.php[626]:db_fetch_cell(), /lib/database.php[386]:db_fetch_cell_prepared(), /lib/database.php[402]:db_execute_prepared())
2020/06/23 12:19:46 - CMDPHP SQL Backtrace: (/poller.php[816]:api_plugin_hook(), /lib/plugins.php[74]:api_plugin_run_plugin_hook(), /lib/plugins.php[177]:thold_poller_bottom(), /plugins/thold/includes/polling.php[45]:thold_check_all_thresholds(), /plugins/thold/includes/polling.php[473]:thold_check_threshold(), /plugins/thold/thold_functions.php[2580]:thold_check_baseline(), /plugins/thold/thold_functions.php[4255]:thold_get_ref_value(), /plugins/thold/thold_functions.php[4180]:rrdtool_function_fetch(), /lib/rrd.php[899]:boost_fetch_cache_check(), /lib/boost.php[272]:boost_process_poller_output(), /lib/boost.php[626]:db_fetch_cell(), /lib/database.php[386]:db_fetch_cell_prepared(), /lib/database.php[402]:db_execute_prepared())

I figured it had something to do with THOLD I disabled the plugin but no differnce 
I do notice boost is running right now so I will see if it has something to do with boost

**Comment by bmfmancini** [comment]
Boost finished running same errors are coming in and they come in fast too

**Comment by bmfmancini** [comment]
Ok so must have been some stubborn PHP proccess I did a reboot errors are gone 
I caught this in my PHP error log 

[23-Jun-2020 12:15:50 America/Toronto] PHP Warning:  Use of undefined constant ST_TRIGGERA - assumed 'ST_TRIGGERA' (this will throw an Error in a future version of PHP) in /var/www/html/cacti/plugins/thold/thold_functions.php on line 2773
[23-Jun-2020 12:15:52 America/Toronto] PHP Warning:  Use of undefined constant ST_TRIGGERA - assumed 'ST_TRIGGERA' (this will throw an Error in a future version of PHP) in /var/www/html/cacti/plugins/thold/thold_functions.php on line 2773
[23-Jun-2020 12:23:51 America/Toronto] PHP Warning:  Use of undefined constant ST_TRIGGERA - assumed 'ST_TRIGGERA' (this will throw an Error in a future version of PHP) in /var/www/html/cacti/plugins/thold/thold_functions.php on line 2773
[23-Jun-2020 12:31:01 America/Toronto] PHP Notice:  Undefined variable: method in /var/www/html/cacti/poller.php on line 796
[23-Jun-2020 12:31:01 America/Toronto] PHP Notice:  Undefined variable: hosts_per_process in /var/www/html/cacti/poller.php on line 797


But other than that nothing aparent

**Comment by TheWitness** [comment]
You've got some gremlins in your system Sean.  Is the remote agent bug reproducible?

**Comment by TheWitness** [comment]
Some of these issues can not be avoided upon restart, Cacti will generate an error at the moment.  At some point we might be able to issue a certain number of retries depending on the error.  Right now, there are only a few cases where that happens.

The Cacti log should also include the MySQL error, I'm sure it's either a 2006 or a 2013.  Let us know which one.

**Comment by TheWitness** [comment]
@bmfmancini, bump!

**Comment by bmfmancini** [comment]
Hey

Sorry been caught up at work

I'll dig up the logs from that day and see if I can find it thanks !

**Comment by bmfmancini** [comment]
Hey @TheWitness  it was 2013

**Comment by TheWitness** [comment]
I'm going to let this one die.  Basically, I saw the same issue today, the Thold plugin had been disabled, and therefore, you were not getting the constant defined as it should have been.  Need to find out what disabled thold.
