### ISSUE TITLE
 Some cacti graphs are not showing new data

### ISSUE THREAD

**Issue by hughesr67** [Cacti/cacti#3638]
Since I added some more sensors to my cacti some graphs are not showing new data.
I can sees these errors in the cacti log:

SPINE Poller(0) The NIFTY POPEN timed out

I am using a php script to poll some devices. This has been working fine.
After adding some more sensors to be monitored so the number of sensors is up to 49, some of the graphs have stopped displaying data.
I am wondering if this is some timeout issue I am having as the php snmp query takes a few seconds to run.
This seems to happen when the number of sensors goes above 40.

cacti version is 0.8.8h running on a CentOS 7.8 VM with 4 CPU 4 GB Ram
php - 5.4.16
mysql - 5.4.16
rrdtool - 1.4.8-9
net-snmp - 5.7.2-48

**Comment by TheWitness** [comment]
What is the script timeout set to?  If it's low, you might want to increase.  However, if your script takes too long, it might be better to perform the data collection asynchronously and cache it for sampling.

**Comment by TheWitness** [comment]
I think you should continue this discussion on the forums.  As such, I'll close this one.
