### ISSUE TITLE
Duplicate Entry error  when updating device V1.2.12

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3639]
Hey All,

So we have been moving some devices to SNMP  V3 what I notice is that if you update the creds on an exisiting device the error log shows the below

2020/06/25 14:35:31 - CMDPHP ERROR: A DB Exec Failed!, Error: Duplicate entry '7-3-8789' for key 'PRIMARY'
2020/06/25 14:35:00 - CMDPHP ERROR: A DB Exec Failed!, Error: Duplicate entry '7-3-8789' for key 'PRIMARY'

2020/06/25 14:45:20 - CMDPHP SQL Backtrace: (/host.php[60]:form_save(), /host.php[253]:api_device_save(), /lib/api_device.php[730]:api_device_purge_from_remote(), /lib/api_device.php[103]:db_execute_prepared())
2020/06/25 14:35:31 - CMDPHP SQL Backtrace: (/host.php[60]:form_save(), /host.php[253]:api_device_save(), /lib/api_device.php[730]:api_device_purge_from_remote(), /lib/api_device.php[103]:db_execute_prepared())
2020/06/25 14:35:00 - CMDPHP SQL Backtrace: (/host.php[60]:form_save(), /host.php[253]:api_device_save(), /lib/api_device.php[730]:api_device_purge_from_remote(), /lib/api_device.php[103]:db_execute_prepared())
2020/06/25 13:15:14 - CMDPHP SQL Backtrace: (/host.php[60]:form_save(), /host.php[253]:api_device_save(), /lib/api_device.php[730]:api_device_purge_from_remote(), /lib/api_device.php[103]:db_execute_prepared())
2020/06/25 13:15:06 - CMDPHP SQL Backtrace: (/host.php[60]:form_save(), /host.php[253]:api_device_save(), /lib/api_device.php[730]:api_device_purge_from_remote(), /lib/api_device.php[103]:db_execute_prepared())

It looks like a dummy error since the device updates just fine and everything works 
but I thought I would bring it up

**Comment by bmfmancini** [comment]
One additional Error I found 

2020/06/25 15:31:12 - ERROR PHP WARNING: A non-numeric value encountered in file: /var/www/html/cacti/lib/api_device.php on line: 1071

**Comment by bmfmancini** [comment]
OK did more digging also see the same errors when you do a poller sync only after you make a device change 
so I am certain its something to do with the save routine trying to append data in duplicate and only the change actually goes through 

2020/06/25 16:20:46 - CMDPHP ERROR: A DB Exec Failed!, Error: Duplicate entry '7-3-9886' for key 'PRIMARY'
2020/06/25 16:20:46 - CMDPHP ERROR: A DB Exec Failed!, Error: Duplicate entry '7-3-8725' for key 'PRIMARY'
2020/06/25 16:20:46 - CMDPHP ERROR: A DB Exec Failed!, Error: Duplicate entry '7-3-7934' for key 'PRIMARY'
2020/06/25 16:20:46 - CMDPHP ERROR: A DB Exec Failed!, Error: Duplicate entry '7-3-7463' for key 'PRIMARY'
2020/06/25 16:20:46 - CMDPHP ERROR: A DB Exec Failed!, Error: Duplicate entry '7-3-6461' for key 'PRIMARY'
2020/06/25 16:20:46 - CMDPHP ERROR: A DB Exec Failed!, Error: Duplicate entry '7-3-4056' for key 'PRIMARY'
2020/06/25 16:20:46 - CMDPHP ERROR: A DB Exec Failed!, Error: Duplicate entry '7-3-2928' for key 'PRIMARY'
2020/06/25 16:20:46 - CMDPHP ERROR: A DB Exec Failed!, Error: Duplicate entry '7-3-2721' for key 'PRIMARY'

**Comment by TheWitness** [comment]
This should be resolved now.  Thanks for all the testing.

**Comment by bmfmancini** [comment]
Thank @TheWitness  I will try these fixes and get back to you !

**Comment by bmfmancini** [comment]
Ok tried the fixes on My lab and prod boxes all working good !

**Comment by TheWitness** [comment]
Cool.
