### ISSUE TITLE
Graph Edit

### ISSUE THREAD

**Issue by smiles1969** [Cacti/cacti#364]
I'm using dark theme, when I click on the up or down arrows to reorder graph items, it loses the theme and goes to white background.

Console->Management->Graphs->Edit Graph
graphs.php?action=graph_edit

**Comment by CapitalF** [comment]
I have been using the dark theme on Chrome for Windows and Chromium for Linux extensively over the last two weeks and have not seen anything like this. What browser are you using? The devs are going to want more info to try to reproduce this. I can't reproduce it.

**Comment by smiles1969** [comment]
Appears to be browser independant.

Also appears to be only on graphs created with no graph template.

So to recreate, you would have to build a new graph with no template, and then try to reorder items.

The screen that is displayed after reordering the item has no theme and shows "Graph Template Selection" at the top of the page.

**Comment by smiles1969** [comment]
Also of note, unless you have Settings->General->Other Settings->Graph/Data Source Creation Method set to Advanced, you wont be able to reproduce this either.

**Comment by CapitalF** [comment]
Good info. Creating graphs without an associated Graph Template is not something I have ever tried. That's probably the key factor to your bug. Hopefully a dev will look into this for you.

**Comment by cigamit** [comment]
Resolved, thanks for testing!
