### ISSUE TITLE
cacti V1.2.12  Duplicate poller error after poller misconfigured

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3640]
Hey Guys 

In my lab I had to rebuild my remote poller VM  and I change the Local IP of the server
when I went to go update the IP in the remote collectors tab you get the following error

![image](https://user-images.githubusercontent.com/13388748/85928814-e7f16080-b87d-11ea-93d1-c6ba44f34a68.png)

Here is the funny thing even when I put a poller name I know never existed you get the same error

![image](https://user-images.githubusercontent.com/13388748/85928836-1e2ee000-b87e-11ea-819a-b814771b2827.png)

Now the remote database is pointing to 192.168.1.50 it should be pointed to 192.168.2.50 if I change the poller hostname it same just fine so long as I keep the 192.168.1.50 IP address in 

I also deleted the poller and re-ran the setup on the remote poller is goes fine but it comes up again with this old IP info

**Comment by bmfmancini** [comment]
sorry correction the remote database hostname is not stuck on the IP rather its stuck on the remote pollers hostname in my case cacti2

In the mean time I put a localhosts entry to point to the proper Ip and voila working now

**Comment by TheWitness** [comment]
Goto poller.php and just before line 381 do the following:

```php
cacti_log("SELECT id FROM poller WHERE id != $poller_id AND ($sql_where1 $sql_where2)");
```

Post the hostname and dbhosts that you are trying to set and that output.

**Comment by bmfmancini** [comment]
Ok so I added the above like so 

        if ($poller_id == '1') {
                $polling_hosts = array_merge(
                        array(0 => array('id' => '0')),
                        cacti_log("SELECT id FROM poller WHERE id != $poller_id AND ($sql_where1 $sql_where2)");
                        db_fetch_assoc_prepared('SELECT ' . SQL_NO_CACHE . ' id
                                FROM host
                                WHERE poller_id = ?
                                AND disabled=""
                                AND deleted=""
                                ORDER BY id',



This is what I am trying to save 

![image](https://user-images.githubusercontent.com/13388748/85934760-a7add480-b8b5-11ea-86bc-f94c1680cc1f.png)


This is the error that results 

![image](https://user-images.githubusercontent.com/13388748/85934767-c9a75700-b8b5-11ea-9440-dff0c5757f4e.png)



Nothing shows up in cacti.log


Here is the output from the db 

MariaDB [cacti]> select id,name,hostname,dbhost  from poller ;
+----+-------------+----------+--------+
| id | name        | hostname | dbhost |
+----+-------------+----------+--------+
|  1 | Main Poller | cact1    | cact1  |
|  3 | Remote      | cact2    | cact2  |
+----+-------------+----------+--------+
2 rows in set (0.00 sec)

MariaDB [cacti]>

**Comment by TheWitness** [comment]
Oh, geeze, pollers.php and not poller.php.

**Comment by TheWitness** [comment]
You better remove what you added to poller.php, you broke your poller.

**Comment by bmfmancini** [comment]
LOL i was about to come back and say I relized that and I since have moved it to the proper spot thank god for labs

**Comment by bmfmancini** [comment]
Here is the updated Pollers.php

    cacti_log("SELECT id FROM poller WHERE id != $poller_id AND ($sql_where1 $sql_where2)");
        $duplicate = db_fetch_cell_prepared("SELECT id
                FROM poller
                WHERE id != ?
                AND ($sql_where1 $sql_where2)",


I am re running the testing now

**Comment by bmfmancini** [comment]
Here is the output from cacti.log

2020/06/27 19:48:08 - CMDPHP SELECT id FROM poller WHERE id != 3 AND  (dbhost IN ('192.168.2.50')  OR  ((dbhost = 'cact1' OR dbhost LIKE  'cact1.%' OR dbhost = 'cact1')))
--
2020/06/27 19:48:08 - CMDPHP SELECT id FROM poller WHERE id != 3 AND  (hostname IN ('192.168.2.50')  OR  ((hostname = 'cact2' OR hostname  LIKE 'cact2.%' OR hostname = 'cact2')))

**Comment by TheWitness** [comment]
And I seeing double?  cact1 or cact2?

**Comment by bmfmancini** [comment]
Cact1 is the main poller cacti2 is the remote poller

**Comment by TheWitness** [comment]
Run both those queries, let me know what they both come back with.

**Comment by bmfmancini** [comment]
Larry....I think I need some more sleep lol 

The issue is I was putting the MAIN poller IP into the remote db field it should be the REMOTE poller!
and to add insult to injury when I added that local host entry well I put the IP of the remote poller!!

No issue here except the one between the chair and keyboard 

Sorry to waste your time

**Comment by TheWitness** [comment]
Lol.  Glad I'm not the only one.  Good chuckle.
