### ISSUE TITLE
Maximum OIDs Per Get Request - field empty

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#3643]
# Describe the bug
```
2020/06/29 13:20:57 - CMDPHP PHP ERROR WARNING Backtrace: (/host.php[137]:api_device_ping_device(), /lib/api_device.php[1045]:cacti_snmp_session(), /lib/snmp.php[86]:CactiErrorHandler())
--
2020/06/29 13:20:57 - ERROR PHP WARNING: cacti_snmp_session(): max_oids should be positive integer or NULL, got 0 in file: /var/www/html/cacti/lib/snmp.php on line: 86
```

## To Reproduce
1. Edit any Device.
2. Delete value from: "Maximum OIDs Per Get Request" - leave field empty
3. Submit form.

## Expected behavior
No error :)

**Comment by TheWitness** [comment]
You don't mention a Cacti version @interduo.  Code looks good.  Somehow the host in question has a max_oids of 0, which should not be possible.  You should look to how you added this device and trace how the max_oids became 0.  My guess is that you are doing this external to Cacti.

**Comment by interduo** [comment]
Sorry.
Branch: 1.2.x
Updated few days ago.

**Comment by interduo** [comment]
> My guess is that you are doing this external to Cacti.

No. I use only gui.

**Comment by TheWitness** [comment]
```sql
SELECT COUNT(*) FROM host WHERE max_oids = 0;
```

**Comment by netniV** [comment]
```
select max_oids, count(*) from host group by max_oids;
+----------+----------+
| max_oids | count(*) |
+----------+----------+
|       10 |        3 |
+----------+----------+
1 row in set (0.00 sec)
```
Try that query, so we can see the split of the setting.

**Comment by interduo** [comment]
Thanks for the query. I changed all fields to 16.

As I see - You could set Maximum OIDs Per Get Request = 0 if You put 0 or leave empty field.
Is this value normal? 


And after that in:
https://cacti/host.php?action=edit&id=749&nostate=true ... as many times as I open this form

```
2020/06/30 09:48:43 - CMDPHP PHP ERROR WARNING Backtrace: (/host.php[137]:api_device_ping_device(), /lib/api_device.php[1045]:cacti_snmp_session(), /lib/snmp.php[86]:CactiErrorHandler())
--
2020/06/30 09:48:43 - ERROR PHP WARNING: cacti_snmp_session(): max_oids should be positive integer or NULL, got 0 in file: /var/www/html/cacti/lib/snmp.php on line: 86
2020/06/30 09:48:43 - CMDPHP Updating 9 Data Source
2020/06/30 09:48:25 - CMDPHP PHP ERROR WARNING Backtrace: (/host.php[137]:api_device_ping_device(), /lib/api_device.php[1045]:cacti_snmp_session(), /lib/snmp.php[86]:CactiErrorHandler())
2020/06/30 09:48:25 - ERROR PHP WARNING: cacti_snmp_session(): max_oids should be positive integer or NULL, got 0 in file: /var/www/html/cacti/lib/snmp.php on line: 86


```

**Comment by interduo** [comment]
in mysql SHOW CREATE TABLE host shows 
`max_oids` int(12) unsigned DEFAULT 10,

There is ``max_oids` int(12) unsigned DEFAULT 10,`
So I think that empty field should be 10 not 0.

**Comment by netniV** [comment]
what do you have for the setting 'max_get_size' ?
```sql
select * from settings where name = 'max_get_size';
```

**Comment by interduo** [comment]
MariaDB [cacti]> select * from settings where name = 'max_get_size';
+--------------+-------+
| name         | value |
+--------------+-------+
| max_get_size | 16    |
+--------------+-------+
1 row in set (0.001 sec)

**Comment by TheWitness** [comment]
Fixed.
