### ISSUE TITLE
Graph preview not rendering due to datetimepicker error

### ISSUE THREAD

**Issue by ahouston** [Cacti/cacti#3644]
# Describe the bug

When loading graph preview page with a URL like https://host/graph_view.php?action=preview&reset=1&host_id=721, the following javascript error occurs:

```
Uncaught TypeError: $(...).datetimepicker is not a function
    at initPage (graph_view.php?action=preview&reset=1&host_id=721:511)
    at HTMLDocument.<anonymous> (graph_view.php?action=preview&reset=1&host_id=721:535)
    at mightThrow (jquery.js?11c05eb286ed576526bf4543760785b9:3557)
    at process (jquery.js?11c05eb286ed576526bf4543760785b9:3625)
```
The resulting page doesn't get to the actual RRD rendering;

![image](https://user-images.githubusercontent.com/1083694/85998599-4c8df600-ba0b-11ea-902e-93a349aa9b3d.png)

Some Googling on the subject seems to indicate that this has to do with the order of the script being loaded, so I tried moving the ```/include/js/jquery.timepicker.js?f29132ab24085f909242175ad11cfcbc``` entry around in lib/html.php but it doesn't seems to help.

I've put in a workaround on my side in lib/html_graph.php to import the javascript file with a Promise, and then execute initPage() which seems to work fine:
```
		$(function() {
			import("/include/js/jquery.timepicker.js?f29132ab24085f909242175ad11cfcbc").
			then(function(){
				$.when(initPage())
				.pipe(function() {
					initializeGraphs();
				});
			//})
		});
```

I don't have much experience with the jquery.timepicker.js library, maybe a simple move of the script src will resolve this?

## To Reproduce

1. Go to graph_view.php?action=preview&reset=1&host_id=1

2. Observe graphs not rendered

Note that using any of the filter actions like "Go" or unticking "Thumbails" will render the graphs properly, presumably because the timepicker is correctly loaded by the time the AJAX request fires.

## Expected behavior

Graphs should render and datetimepicker should work on the #date1 and #date2 fields.

## Screenshots

![image](https://user-images.githubusercontent.com/1083694/85999392-4fd5b180-ba0c-11ea-86c9-4655e31fd25e.png)

## Desktop (please complete the following information)

- OS: Windows 10

- Browser: Chrome

- Version: Version 83.0.4103.116 (Official Build) (64-bit)

**Comment by TheWitness** [comment]
This has been resolved and will be included in the 1.2.13 release this coming weekend.  If you want the fix before then, pull the 1.2.x branch.
