### ISSUE TITLE
add_datasource.php should print the created ID

### ISSUE THREAD

**Issue by rlaager** [Cacti/cacti#3647]
# Feature Request

In a local script, we are calling e.g. `/usr/share/cacti/cli/add_datasource.php --host-id=261 --data-template-id=90`. It does not print out the ID of the DS created. We need the ID for further steps.

## Describe the solution you'd like

I would like it to print `$local_data_id` in some form.

## Describe alternatives you've considered

We have considered doing all the work of `add_datasource.php` in our script. That would be a lot of duplicated effort.

**Comment by TheWitness** [comment]
Thanks!
