### ISSUE TITLE
ss_host_disk.php and ss_host_cpu.php  Reindex Method Shifts Values returned to cmd.php

### ISSUE THREAD

**Issue by FrodoTheRingWearer** [Cacti/cacti#365]
This issue occurs because when using the reindex method's the aforementioned scripts PRINT the values instead of RETURNing them. See http://forums.cacti.net/viewtopic.php?f=21&t=56999 for more details. Both scripts contain print statements and they should be replaced with return statements.

**Comment by pautiina** [comment]
I look  script ss_host_disk.php  and read your message on forum, and I think that line 67,73,82 must replace print to return.

**Comment by FrodoTheRingWearer** [comment]
Yes.

Also in ss_host_cpu.php lines 65,70, 79, 82, 95, 97, and 103 must change print to return.

**Comment by cigamit** [comment]
FrodoTheRingWearer, not true.

**Comment by FrodoTheRingWearer** [comment]
Which part are you disagreeing with?

**Comment by cigamit** [comment]
"lines 65, 70, 79, ...".

The only parts that must include 'return' are those that are actually used by the script server.  This includes only 'get' and 'num_indexes'.  The others are used by the re-index section which calls the script directly and not through the script server, so they must be printed.

It's confusing at first, but correct.  This num_indexes stuff was back-ported from and earlier and never released version of cacti that was therefore never thoroughly tested

**Comment by cigamit** [comment]
Resolved, thanks for reporting.
