### ISSUE TITLE
Editing any item on an Aggregate Graph that has been converted to a normal graph breaks entire graph

### ISSUE THREAD

**Issue by iskandarbasman** [Cacti/cacti#3651]
# Describe the bug

Converted Aggregate graph to a normal graph because I want to edit it  to be more like the Aggregate graph in cacti 8.8.
Trying to edit almost any graph item breaks it.

## To Reproduce

1. Edit Graph.

2. Click on Item 28.

3. Change the colour.

4. Save and Graphs break.

## Expected behavior

Should allow me to edit the graph without breaking it.

## Screenshots

**Before**
![image](https://user-images.githubusercontent.com/67727557/86322278-45662280-bc6d-11ea-9564-7e5a0f87ff1f.png)

**After**
![image](https://user-images.githubusercontent.com/67727557/86322331-5b73e300-bc6d-11ea-8c20-df96caa5b47e.png)

**Raw Debug Before**
`
RRDtool Command:
/usr/bin/rrdtool graph - \
--imgformat=PNG \
--start='-86400' \
--end='-300' \
--pango-markup  \
--title='Aggregate - AS4657 STARHUB' \
--vertical-label='bits per second' \
--slope-mode \
--base=1000 \
--height=200 \
--width=700 \
--rigid \
--alt-autoscale-max \
--lower-limit='0' \
COMMENT:"From 2020-07-01 13\:52\:20 To 2020-07-02 13\:47\:20\c" \
COMMENT:"  \n" \
--border 1 --slope-mode \
--watermark 'Generated by Cacti®' \
DEF:a='/usr/share/cacti/rra/nkipnac000br001_traffic_in_199.rrd':'traffic_in':MAX \
DEF:b='/usr/share/cacti/rra/nkipnac000br001_traffic_in_199.rrd':'traffic_in':AVERAGE \
DEF:c='/usr/share/cacti/rra/nkipnac000br001_traffic_in_199.rrd':'traffic_out':MAX \
DEF:d='/usr/share/cacti/rra/nkipnac000br001_traffic_in_199.rrd':'traffic_out':AVERAGE \
DEF:e='/usr/share/cacti/rra/nkipo1c000br001_traffic_in_170.rrd':'traffic_in':MAX \
DEF:f='/usr/share/cacti/rra/nkipo1c000br001_traffic_in_170.rrd':'traffic_in':AVERAGE \
DEF:g='/usr/share/cacti/rra/nkipo1c000br001_traffic_in_170.rrd':'traffic_out':MAX \
DEF:h='/usr/share/cacti/rra/nkipo1c000br001_traffic_in_170.rrd':'traffic_out':AVERAGE \
CDEF:cdefa='a,8,*' \
CDEF:cdefb='b,8,*' \
CDEF:cdeff='c,8,*' \
CDEF:cdefg='d,8,*' \
CDEF:cdefba='e,8,*' \
CDEF:cdefbb='f,8,*' \
CDEF:cdefbf='g,8,*' \
CDEF:cdefbg='h,8,*' \
CDEF:cdefcb='TIME,1593668840,GT,b,b,UN,0,b,IF,IF,TIME,1593668840,GT,f,f,UN,0,f,IF,IF,+,8,*' \
CDEF:cdefcg='TIME,1593668840,GT,d,d,UN,0,d,IF,IF,TIME,1593668840,GT,h,h,UN,0,h,IF,IF,+,8,*' \
LINE0.01:cdefa#00CF00FF:'NKIPNAC000BR001':STACK \
LINE0.01:cdefb#00CF007F:'NKIPNAC000BR001':STACK \
GPRINT:cdefb:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefb:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdefb:MAX:'Maximum\:%8.2lf %s\n'  \
LINE0.01:cdeff#002A97FF:'NKIPNAC000BR001':STACK \
LINE0.01:cdefg#002A977F:'NKIPNAC000BR001':STACK \
GPRINT:cdefg:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefg:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdefg:MAX:'Maximum\:%8.2lf %s\n'  \
LINE0.01:cdefba#00CF00FF:'NKIPO1C000BR001':STACK \
LINE0.01:cdefbb#00CF007F:'NKIPO1C000BR001':STACK \
GPRINT:cdefbb:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefbb:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdefbb:MAX:'Maximum\:%8.2lf %s\n'  \
LINE0.01:cdefbf#002A97FF:'NKIPO1C000BR001':STACK \
LINE0.01:cdefbg#002A977F:'NKIPO1C000BR001':STACK \
GPRINT:cdefbg:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefbg:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdefbg:MAX:'Maximum\:%8.2lf %s\n'  \
COMMENT:' \n'  \
LINE0.01:cdefcb#00CF00FF::STACK \
LINE1:cdefcb#00CF007F:'Total          '  \
GPRINT:cdefcb:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefcb:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdefcb:MAX:'Maximum\:%8.2lf %s\n'  \
LINE0.01:cdefcg#002A97FF::STACK \
LINE1:cdefcg#002A977F:'Total          '  \
GPRINT:cdefcg:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefcg:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdefcg:MAX:'Maximum\:%8.2lf %s\n' 
RRDtool Command lengths = 2771 charaters.
RRDtool Says:
OK

`
**Raw Debug After**

`
RRDtool Command:
/usr/bin/rrdtool graph - \
--imgformat=PNG \
--start='-86400' \
--end='-300' \
--pango-markup  \
--title='Aggregate - AS4657 STARHUB' \
--vertical-label='bits per second' \
--slope-mode \
--base=1000 \
--height=200 \
--width=700 \
--rigid \
--alt-autoscale-max \
--lower-limit='0' \
COMMENT:"From 2020-07-01 13\:53\:19 To 2020-07-02 13\:48\:19\c" \
COMMENT:"  \n" \
--border 1 --slope-mode \
--watermark 'Generated by Cacti®' \
DEF:a='/usr/share/cacti/rra/nkipnac000br001_traffic_in_199.rrd':'traffic_in':MAX \
DEF:b='/usr/share/cacti/rra/nkipnac000br001_traffic_in_199.rrd':'traffic_in':AVERAGE \
DEF:c='/usr/share/cacti/rra/nkipnac000br001_traffic_in_199.rrd':'traffic_out':MAX \
DEF:d='/usr/share/cacti/rra/nkipnac000br001_traffic_in_199.rrd':'traffic_out':AVERAGE \
DEF:e='/usr/share/cacti/rra/nkipo1c000br001_traffic_in_170.rrd':'traffic_in':MAX \
DEF:f='/usr/share/cacti/rra/nkipo1c000br001_traffic_in_170.rrd':'traffic_in':AVERAGE \
DEF:g='/usr/share/cacti/rra/nkipo1c000br001_traffic_in_170.rrd':'traffic_out':MAX \
DEF:h='/usr/share/cacti/rra/nkipo1c000br001_traffic_in_170.rrd':'traffic_out':AVERAGE \
CDEF:cdefa='a,8,*' \
CDEF:cdefb='b,8,*' \
CDEF:cdeff='c,8,*' \
CDEF:cdefg='d,8,*' \
CDEF:cdefba='e,8,*' \
CDEF:cdefbb='f,8,*' \
CDEF:cdefbf='g,8,*' \
CDEF:cdefbg='h,8,*' \
CDEF:cdefcb='TIME,1593668899,GT,b,b,UN,0,b,IF,IF,TIME,1593668899,GT,f,f,UN,0,f,IF,IF,+,8,*' \
CDEF:cdefcg='TIME,1593668899,GT,d,d,UN,0,d,IF,IF,TIME,1593668899,GT,h,h,UN,0,h,IF,IF,+,8,*' \
LINE0.01:cdefa#00CF00FF:'NKIPNAC000BR001':STACK \
LINE0.01:cdefb#00CF007F:'NKIPNAC000BR001':STACK \
GPRINT:cdefb:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefb:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdefb:MAX:'Maximum\:%8.2lf %s\n'  \
LINE0.01:cdeff#002A97FF:'NKIPNAC000BR001':STACK \
LINE0.01:cdefg#002A977F:'NKIPNAC000BR001':STACK \
GPRINT:cdefg:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefg:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdefg:MAX:'Maximum\:%8.2lf %s\n'  \
LINE0.01:cdefba#00CF00FF:'NKIPO1C000BR001':STACK \
LINE0.01:cdefbb#00CF007F:'NKIPO1C000BR001':STACK \
GPRINT:cdefbb:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefbb:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdefbb:MAX:'Maximum\:%8.2lf %s\n'  \
LINE0.01:cdefbf#002A97FF:'NKIPO1C000BR001':STACK \
LINE0.01:cdefbg#002A977F:'NKIPO1C000BR001':STACK \
GPRINT:cdefbg:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefbg:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdefbg:MAX:'Maximum\:%8.2lf %s\n'  \
COMMENT:' \n'  \
LINE0.01:cdefcb#00CF00FF::STACK \
LINE1:cdefcb#00CF007F:'Total          '  \
GPRINT:cdefcb:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefcb:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdefcb:MAX:'Maximum\:%8.2lf %s\n'  \
LINE0.01:cdefcg#002A97FF::STACK \
LINE3:#002A977F:'Total          '  \
GPRINT:cdefcg:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefcg:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdefcg:MAX:'Maximum\:%8.2lf %s\n' 
RRDtool Command lengths = 2765 charaters.
RRDtool Says:
ERROR: parameter '#002A977F' does not represent a number in line LINE3:#002A977F:Total          
`

## Desktop (please complete the following information)

Win10

Firefox 77.0.1 (64-bit)

**Comment by TheWitness** [comment]
Pretty sure this is resolved in the 1.2.x branch.  Please install it, and then report back.  Here is how I upgrade.

```cmd
#!/bin/sh
cd /var/www/html
rm -rf cacti-develop
git clone -b 1.2.x https://github.com/Cacti/cacti.git cacti-develop
/bin/cp -rpf cacti-develop/* cacti
chown -R apache:apache cacti
```

**Comment by iskandarbasman** [comment]
> 
> 
> Pretty sure this is resolved in the 1.2.x branch. Please install it, and then report back. Here is how I upgrade but check against your system for correct users/groups etc.
> 
> ```batchfile
> #!/bin/sh
> cd /var/www/html
> rm -rf cacti-develop
> git clone -b 1.2.x https://github.com/Cacti/cacti.git cacti-develop
> /bin/cp -rpf cacti-develop/* cacti
> chown -R apache:apache cacti
> ```

I have problems installing GIT on this particular VM. (not the admin and don't have the right Redhat repos enabled on the satellite i believe.)

This is pretty much a new install of Cacti 1.2.12.

The original Cacti 1.2.12 was install using yum on this Redhat7 vm.
"https://www.itzgeek.com/how-tos/linux/centos-how-tos/monitor-network-using-cacti-with-centos-7-rhel-7.html"

So I decide to do the traditional TAR upgrade by downloading the TAR ball for cacti 1.2.12 on the cacti website.

Even editing the colour breaks it.
Is it possible that old code got into the current distribution if this issue was already fixed ?

![image](https://user-images.githubusercontent.com/67727557/86425850-cd553680-bd18-11ea-9a57-0d373c05f748.png)

**Comment by iskandarbasman** [comment]
Okay just to update. 
Did a fresh install of Cacti v1.2.12 from the tar ball.

For this case I only hit the bug when editing the line type of Item 29.

![image](https://user-images.githubusercontent.com/67727557/86511310-6a53c480-be2a-11ea-9a5e-db15dc1ebdc1.png)

**Comment by iskandarbasman** [comment]
> 
> 
> Pretty sure this is resolved in the 1.2.x branch. Please install it, and then report back. Here is how I upgrade but check against your system for correct users/groups etc.
> 
> ```batchfile
> #!/bin/sh
> cd /var/www/html
> rm -rf cacti-develop
> git clone -b 1.2.x https://github.com/Cacti/cacti.git cacti-develop
> /bin/cp -rpf cacti-develop/* cacti
> chown -R apache:apache cacti
> ```

Okay... Did the GIT update on my VM cacti.
Edit the colour of the last line Item break the graph.

![image](https://user-images.githubusercontent.com/67727557/86511504-82c4de80-be2c-11ea-85c6-010fe9c30b35.png)

**Comment by TheWitness** [comment]
Please see what happens when using The Modern or Dark themes.  Also, can you help format the RRDtool debug output so we can read it a bit better?  The first paste looked much easier to read that the second.

**Comment by TheWitness** [comment]
Lastly, when you edit the Graph Item, what is the CDEF set to?  It should be something like "Total Add Data Sources'.  If not, what was it before you converted the Aggregate to a Graph?

**Comment by TheWitness** [comment]
I think I tracked this down.
