### ISSUE TITLE
Cacti V1.2.12 Boost running too often 

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3656]
Hey Guys 

Another Boost behavior I notice in 1.2.12 is that boost shows to be running too often 

2020/07/02 12:09:42 - SYSTEM BOOST STATS: Time:1.0000 RRDUpdates:0
2020/07/02 11:48:43 - SYSTEM BOOST STATS: Time:420.2600 RRDUpdates:3993445
2020/07/02 11:42:44 - SYSTEM BOOST STATS: Time:1.0000 RRDUpdates:0
2020/07/02 11:22:42 - SYSTEM BOOST STATS: Time:419.0400 RRDUpdates:3992143

I've replicated this on 2 separate systems 

Here are my boost settings for the above system

![image](https://user-images.githubusercontent.com/13388748/86399495-59158700-bc75-11ea-9812-0e0eaa97d337.png)
****

Boost stats

Last Start Time:	2020-07-02 14:42:41
Last Run Duration:	6 minutes59 seconds (12.00 percent of update frequency)
RRD Updates:	4276352
Peak Poller Memory:	61.48 MBytes
Detailed Runtime Timers:	RRDUpdates:4276352 TotalTime:420 get_records:4.78 results_cycle:402.34 rrd_filename_and_template:12.59 rrd_lastupdate:368.34 rrdupdate:13.8 delete:8.5
Max Poller Memory Allowed:	1024 MBytes

**Comment by bmfmancini** [comment]
Here is a similar result from another system

2020-07-03 09:20:03 - SYSTEM BOOST STATS: Time:0.5700 RRDUpdates:123
2020-07-03 09:19:03 - SYSTEM BOOST STATS: Time:0.5300 RRDUpdates:81
2020-07-03 09:18:04 - SYSTEM BOOST STATS: Time:0.6300 RRDUpdates:152
2020-07-03 09:17:03 - SYSTEM BOOST STATS: Time:0.4900 RRDUpdates:91

**Comment by TheWitness** [comment]
That is quite odd.  Did you have a time-zone change in your database?  Cause otherwise, this should not happen.

**Comment by bmfmancini** [comment]
No timezone changes on the DB side and I see this on a couple of systems big or small

**Comment by TheWitness** [comment]
Very odd, for each of those systems, you should dump the settings table and send via email along with the cacti.log.

**Comment by bmfmancini** [comment]
Sorry back to this 

I caught this today 

Last Start Time:	2020-07-22 13:36:26
Last Run Duration:	1 seconds (0.00 percent of update frequency)
RRD Updates:	0
Peak Poller Memory:	63.01 MBytes
Detailed Runtime Timers:	RRDUpdates:3699543 TotalTime:503 get_records:4.09 results_cycle:487.31 rrd_filename_and_template:15.57 rrd_lastupdate:445.17 rrdupdate:18.27 delete:7.68
Max Poller Memory Allowed:	1024 MBytes

So weird 

Do you want the full settings table or is just the settings from the gui fine ?

**Comment by netniV** [comment]
1 second? You have a beast of a machine there 👍

**Comment by TheWitness** [comment]
I did a little re-write of the timing logic to make it a bit easier for the next guy to read through.
