### ISSUE TITLE
Contacting device spinning icon  ( 1.3.0-devel)

### ISSUE THREAD

**Issue by rtripon** [Cacti/cacti#3664]
After last pull ( 1.3.0-devel) I'm unable to contact any device via snmp. No errors, poller is working, graphs are populated.

# Describe the bug

Contacting device with the updating/spinning icon that never completes. It never resolves the SNMP sysinfo now, just says Contacting Device indefinitely. SPINE continues to poll fine, graphs are populating, and I can snmpwalk all devices just fine.

Date | Tue, 07 Jul 2020 08:15:39 +0300
-- | --
Cacti Version | 1.3.0
Cacti OS | unix
NET-SNMP Version | NET-SNMP version: 5.7.2
RRDtool Version Configured | 1.7.0+
RRDtool Version Found | 1.7.0

## To Reproduce

Any device in management.

## Screenshots
![contacting device spinning icon](https://user-images.githubusercontent.com/28921178/86716326-c2a4e500-c029-11ea-9659-6cc8d2f1bbd2.jpg)

## Desktop (please complete the following information)

- Windows 10

- Chrome, Firefox.

**Comment by netniV** [comment]
there was an issue, though I thought I'd fixed this with another push in the last day or so. Turns out I hadn't committed, but I have now.  Do another pull and it should start working again.

**Comment by rtripon** [comment]
Fixed, confirm.
