### ISSUE TITLE
When Input Field is in error, message reports field will be highlighted which is incorrect

### ISSUE THREAD

**Issue by DavidLiedke** [Cacti/cacti#3668]
# Describe the bug

Cacti Version 1.2.12

Error Message: Save Failed due to field input errors (Check red fields).

The error message says that the field is marked red. But the field: "Input Field" is not marked red.

## To Reproduce

1. Go to Data Collection --> Data Input Method

2. Select one Input Method

3. Add one Input Field

4. Dont select a field and click "Create"

## Screenshots

![ABiEBovc7S](https://user-images.githubusercontent.com/25581728/86895032-30254400-c104-11ea-9628-39d521aadcfc.gif)

## Desktop (please complete the following information)

- OS: [e.g. iOS] Win 10

- Browser [e.g. chrome, safari] Firefox

- Version [e.g. 22] 78.0.1

**Comment by TheWitness** [comment]
David, took a slightly different approach here.  But this issue should not happen again.
