### ISSUE TITLE
Spikekill CLI misinterprets the default method when when method is not specified in arguments

### ISSUE THREAD

**Issue by riversdev0** [Cacti/cacti#3670]
# Describe the bug

When the Spikekill CLI is run and the user does not specify a `method` parameter in the CLI arguments, the default method is taken from the Cacti settings.  In Settings of the Cacti GUI, 'Standard Deviation' is stored in the database as a `spikekill_method`=`1`, and 'Variance' is stored as a `spikekill_method`=`2`.  However, when the Spikekill CLI is run, it interprets a database value of `1` to be 'Variance' and a value of `2` to be 'Standard Deviation', which is backwards.

## To Reproduce

This bug will occur every time the Spikekill CLI is run and the `method` parameter is omitted from the arguments.

## Expected behavior

The Spikekill CLI should interpret the `method` value retrieved from the database so as to carry the same meaning as it does in the Cacti settings.

## Screenshots

n/a

## Desktop (please complete the following information)

n/a

## Smartphone (please complete the following information)

n/a

## Additional context

None

**Comment by riversdev0** [comment]
I have fixed this issue in my personal repository, but because my understanding of GIT is still shallow, I didn't make new branches the way I should have.  Therefore, I will wait to submit a pull request for this issue until after my previous pull request gets merged.

**Comment by netniV** [comment]
I have now merged your changes that were already present.

**Comment by riversdev0** [comment]
Wasn't this Issue Tracker supposed to get closed when the PR got merged yesterday?  I'm new to GIT, so maybe I didn't link something right.

**Comment by netniV** [comment]
No, it doesn't automatically close until it goes into the develop branch.  So, I tend to close them during release for 1.2.x 👍
