### ISSUE TITLE
cacti v1.2.12 undefined index graphs stopped until poller sync

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3672]
Hey Everyone

Today I had graphs suddenly stop working saw these errors in the log
after doing a poller sync graphs started working again

2020/07/08 16:59:28 - CMDPHP PHP ERROR NOTICE Backtrace: (/graph_json.php[159]:rrdtool_function_graph(), /lib/rrd.php[1594]:variable_bandwidth_summation(), /lib/graph_variables.php[644]:CactiErrorHandler())
2020/07/08 16:59:28 - ERROR PHP NOTICE: Undefined index: traffic_out in file: /var/www/html/cacti/lib/graph_variables.php on line: 644
2020/07/08 16:59:28 - CMDPHP PHP ERROR NOTICE Backtrace: (/graph_json.php[159]:rrdtool_function_graph(), /lib/rrd.php[1594]:variable_bandwidth_summation(), /lib/graph_variables.php[644]:CactiErrorHandler())
2020/07/08 16:59:28 - ERROR PHP NOTICE: Undefined index: traffic_out in file: /var/www/html/cacti/lib/graph_variables.php on line: 644
2020/07/08 16:59:28 - CMDPHP PHP ERROR NOTICE Backtrace: (/graph_json.php[159]:rrdtool_function_graph(), /lib/rrd.php[1594]:variable_bandwidth_summation(), /lib/graph_variables.php[644]:CactiErrorHandler())
2020/07/08 16:59:28 - ERROR PHP NOTICE: Undefined index: traffic_in in file: /var/www/html/cacti/lib/graph_variables.php on line: 644
2020/07/08 16:59:28 - CMDPHP PHP ERROR NOTICE Backtrace: (/graph_json.php[159]:rrdtool_function_graph(), /lib/rrd.php[1594]:variable_bandwidth_summation(), /lib/graph_variables.php[644]:CactiErrorHandler())
2020/07/08 16:59:28 - ERROR PHP NOTICE: Undefined index: traffic_in in file: /var/www/html/cacti/lib/graph_variables.php on line: 644
2020/07/08 16:59:28 - CMDPHP PHP ERROR NOTICE Backtrace: (/graph_json.php[159]:rrdtool_function_graph(), /lib/rrd.php[1594]:variable_bandwidth_summation(), /lib/graph_variables.php[644]:CactiErrorHandler())
2020/07/08 16:59:28 - ERROR PHP NOTICE: Undefined index: traffic_out in file: /var/www/html/cacti/lib/graph_variables.php on line: 644
2020/07/08 16:59:28 - CMDPHP PHP ERROR NOTICE Backtrace: (/graph_json.php[159]:rrdtool_function_graph(), /lib/rrd.php[1594]:variable_bandwidth_summation(), /lib/graph_variables.php[644]:CactiErrorHandler())
2020/07/08 16:59:28 - ERROR PHP NOTICE: Undefined index: traffic_out in file: /var/www/html/cacti/lib/graph_variables.php on line: 644
2020/07/08 16:59:28 - CMDPHP PHP ERROR NOTICE Backtrace: (/graph_json.php[159]:rrdtool_function_graph(), /lib/rrd.php[1594]:variable_bandwidth_summation(), /lib/graph_variables.php[644]:CactiErrorHandler())
2020/07/08 16:59:28 - ERROR PHP NOTICE: Undefined index: traffic_in in file: /var/www/html/cacti/lib/graph_variables.php on line: 644

**Comment by bmfmancini** [comment]
Here is the surrounding code

                        break;
                case 'total':
                        foreach ($graph_items as $graph_element) {
                                if (!empty($graph_element['data_template_rrd_id']) &&
                                        !empty($graph_element['local_data_id']) &&
                                        is_graphable_item($graph_item_types[$graph_element['graph_type_id']])) {
                                        $summation += $summation_cache[$graph_element['local_data_id']][$graph_element['data_source_name']];
                                }
                        }

                        break;
        }

**Comment by bmfmancini** [comment]
OK further digging 

There were a few points where the poller time on the Main poller exceed due to a network issue
the response from the devices was very slow  

It appears that the Boost table went into a backlog I normally have it set to 4M max rows but Boost did not quick in while the main poller was timing out  and that grew to close to 20M records 

Boost finally kicked in when the network stabilized and ran without error 
I can see that right after that large Boost run that graphs stopped working until I did a poller re-sync which fixed it 

What's more strange is that this didn't impact all of the graphs some continued to work just fine 
During the time the graphs stopped  poller was running just fine 

I dont see any boost related errors in the log

**Comment by TheWitness** [comment]
I must be looking at another graph_variables than you, cause line 644 area looks like this:

![image](https://user-images.githubusercontent.com/1439914/87235497-71d71880-c3aa-11ea-985b-44dfbb21856a.png)

**Comment by bmfmancini** [comment]
Hmmm

Maybe I did look at another file unless I look up the wrong lines

**Comment by TheWitness** [comment]
On vacation.

**Comment by TheWitness** [comment]
I'm going to close this one.  I'm pretty sure this has something to do with new graphs, but it should only happen, if it happens at all, until the rrdfile is created.
