### ISSUE TITLE
Spikekill does not receive correct `avgnan` value when launching from GUI

### ISSUE THREAD

**Issue by riversdev0** [Cacti/cacti#3673]
# Describe the bug

When launching Spikekill from the Cacti GUI, the incorrect value for `avgnan` (which is Replacement Method) is passed to the hook script if you choose either GapFill or Float.  Choosing StdDev or Variance does not experience the issue.

## To Reproduce

1. Go to Cacti's Graph tab.

2. Identify a graph upon which to run Spikekill.  Click the Spikekill icon next to the graph to open the menu.  Hover on Settings.  Hover on Replacement Method.  Chose Average.

3. Click the Spikekill icon next to the graph again.  Click 'Gap Fill Range'.

4. Observe in the `log/cacti.log` file the messgage indicating `avgnan` is `last`:
```2020/07/08 18:21:18 - SPIKEKILL CactiUser:admin, File:eag-wan-rt02_traffic_in_72.rrd, Method:GapFill, OutStart:1594164011, OutEnd:1594250411, AvgNan:last```

5. Observe via a packet capture tool the HTTP request indicating that `avgnan` is `last`:
![image](https://user-images.githubusercontent.com/7363202/86981356-f24c0e00-c14b-11ea-8bb4-600c3db3a439.png)

## Expected behavior

If the Replacement Method is set to 'Average', Spikekill should not be launched with 'Last Known Good', but rather with 'Average'.

## Screenshots

Wireshark says the replacement is 'last'
![image](https://user-images.githubusercontent.com/7363202/86981727-0b08f380-c14d-11ea-9539-97e5e55af0ee.png)

The GUI says the replacement is 'average'
![image](https://user-images.githubusercontent.com/7363202/86981848-5ae7ba80-c14d-11ea-8e61-852d6abf70b5.png)

## Desktop (please complete the following information)

n/a

## Smartphone (please complete the following information)

n/a

## Additional context

None

**Comment by netniV** [comment]
seems logical to me, you're doing some good work on spikekill 👍 

Will you be submitting a PR for this, or should I go ahead and fix it tomorrow?

**Comment by riversdev0** [comment]
This one, actually, I have not found the cause for yet.  I feel like it's in a Javascript somewhere, but I haven't spent enough time looking yet.  If you know where the problem is, either go ahead and fix it, or tell me where to find it.  Otherwise, I can search for it and fix it once I've located it.  The proper solution should be to drop the parameter from the query string, because the script will pull the user's setting from the database, thus it is not even needed in the HTTP query.

**Comment by TheWitness** [comment]
Everything is in layout.js.  My thoughts here are that we should not even be passing in the parameter.  When we do that, the spikekill.php should be getting the default from the database.  So, we just have to remove "method=blah" from layout.js selectively.

**Comment by TheWitness** [comment]
Here is a quick grep, you can see it's hardcoded.

![image](https://user-images.githubusercontent.com/1439914/87247465-003ab100-c422-11ea-90a8-12ae723372f7.png)

**Comment by TheWitness** [comment]
lol, it's 'avgnan'.  But again, hardcoded.  That's a bug.  Let me do dig in this morning.  I'll have to be a pull request.

**Comment by TheWitness** [comment]
Okay, got a good pull request now.  Give it a look over.  Some other things were wrong too, which @netniV will see strait away.  This change will always pull the last stored value from the user settings, which was not happening before.  So, if you changed something from the GUI and then expected it to just work, it would not.  That's besides the fact that avgnan was always hardcoded.

**Comment by riversdev0** [comment]
Awesome, thank you!
