### ISSUE TITLE
Relocate the delete button for collectors to the edit page

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3677]
Hey Guys 

I think the delete option in the dropdown in data collection should be moved somewhere else 

in the same dropdown where you have sync pollers right above disable is delete
I think it would be better to maybe remove that from the dropdown and put it elsewhere or some other alternative 
I know cacti would  pop up with the confirmation message maybe for the delete option  the user should be forced the enter the name of the poller ? that way you dont just click ok and then bye bye poller 

Thanks !

**Comment by netniV** [comment]
![image](https://user-images.githubusercontent.com/9052188/87222815-23585880-c36f-11ea-872f-c451325fb4aa.png)

![image](https://user-images.githubusercontent.com/9052188/87222825-38cd8280-c36f-11ea-97b6-d8bca1e63eae.png)

This has now been applied to the 1.3 branch.  Definitely a safer course of action.
