### ISSUE TITLE
More or Equal incorrect highlighting max_heap_table_size and tmp_table_size

### ISSUE THREAD

**Issue by coozoo** [Cacti/cacti#3678]
# Describe the bug

Incorrect highlighting of  max_heap_table_size and tmp_table_size when actually they met criteria of equality they highlighted with orange color in Recommended MySQL System Variable Settings.

## To Reproduce

1. set mariadb-server.cnf values for max_heap_table_size and tmp_table_size equal to recomended (in 1.2.12 it's 311M)

```
max_heap_table_size = 311M
tmp_table_size = 311M
```

2. setup or upgrade cacti actually you need to see window with recommended settings

## Expected behavior

There is two ways to fix(I suppose 1st is better to follow style of other values):
1. Values shouldn't be highlighted. 
2. Or condition should be changed from more/equal (>=) to more (>)

## Screenshots

![image](https://user-images.githubusercontent.com/25594311/87196369-a7c0c200-c302-11ea-8cde-42cf93dc24e1.png)

## Desktop (please complete the following information)

- OS: Fedora 31

- Browser Chromium

- Version 31

## Additional context

It's actually very old bug. Just decided to open it now :)

**Comment by netniV** [comment]
More than likely, it's a rounding issue.  At least that is my gut feeling because the values are converted back and forth between bytes, kilobytes etc.

**Comment by TheWitness** [comment]
My thoughts exactly.

**Comment by TheWitness** [comment]
We should use the ceil function on the recommendations instead of the round functions in lib/utilities.php.

**Comment by TheWitness** [comment]
@coozoo, do you have a setup that can reproduce?

**Comment by coozoo** [comment]
@TheWitness nope, but suppose I can make some for that :)
