### ISSUE TITLE
When in 'Time Graph View' mode, Zoom features do not work correctly

### ISSUE THREAD

**Issue by iskandarbasman** [Cacti/cacti#3682]
# Feature Request

In the previous versions of we were able to perform a mouse of zoom in 'Time Graph View' mode (Where you see Daily, Weekly, Monthly, Yearly Graph for a selected object.)
This a convenient feature but it was removed for some reason.

You can only perform mouse over zoom in the Tree mode or Preview mode where the Graph Filter menu is available. 

![image](https://user-images.githubusercontent.com/67727557/87247205-e9797600-c484-11ea-901a-bd76b6f27179.png)

**Comment by netniV** [comment]
It looks like you've used the 'feature request' template for a bug ... this should have been using the Bug/Issue template 👍  

Thanks for the report though!
