### ISSUE TITLE
http://cacit-url/cacti/install/install.php?data={"Step":"97","Eula":"1"}  - Not installing in RDS Mysql

### ISSUE THREAD

**Issue by myvelcn** [Cacti/cacti#3687]
# Describe the bug

I am using RDS mysql for this cacti installation and i am not able to succesfully install it and it throws error.

http://cacit-url/cacti/install/install.php?data={"Step":"97","Eula":"1"}.

V:1.2.12
MYSQL -5.7 AWS RDS

```

Connecting the remote database using the below config.

$rdatabase_type     = 'mysql';
$rdatabase_default  = 'cacti';
$rdatabase_hostname = '<rds-database-aws>';
$rdatabase_username = 'cacti';
$rdatabase_password = '<password>';
$rdatabase_port     = '3306';
$rdatabase_retries  = 5;
$rdatabase_ssl      = false;
$rdatabase_ssl_key  = '';
$rdatabase_ssl_cert = '';
$rdatabase_ssl_ca   = '';


While trying installation it gives the errir ELUA=1 Step-97 and it hangs for longer time.

```

Refresh in |   | ProgressLast updated: 04:09:44
-- | -- | --
  |   | 0 %

07/13/2020 04:09:44 - INSTALL: always: Install aborted due to no EULA acceptance
07/13/2020 04:09:44 - INSTALL: Checking arguments
07/13/2020 04:09:44 - INSTALL: always: Spawning background process: /usr/bin/php '/usr/share/cacti/install/background.php' 1594631384.0472
````

**Comment by TheWitness** [comment]
You should open the browsers debug console and check for JavaScript errors.  Also, note, that when installing a remote data collector, all variables prefixed with $r* point to the central core database, and all variables not prefixed with $r* are for the local database.

You should test your connection before you start, and not that the central account will need access to the remote data collectors database as well.  So, it's a bidirectional communication path.

**Comment by netniV** [comment]
Check that your PHP path is actually correct on that instance, if it isn't the background process will fail.

**Comment by myvelcn** [comment]
@TheWitness I have configured remote poller setting only and the test connection was susccessfull.

$rdatabase_type     = 'mysql';
$rdatabase_default  = 'cacti';
$rdatabase_hostname = '<rds-database-aws>';
$rdatabase_username = 'cacti';
$rdatabase_password = '<password>';
$rdatabase_port     = '3306';
$rdatabase_retries  = 5;
$rdatabase_ssl      = false;
$rdatabase_ssl_key  = '';
$rdatabase_ssl_cert = '';
$rdatabase_ssl_ca   = '';


@netniV   php path is configured properly. I just want to know cacti will be installed in RDS mysql.

**Comment by TheWitness** [comment]
@myvelcn how about from the remote poller to the main server?

**Comment by myvelcn** [comment]
```
07/13/2020 04:09:44 - INSTALL: always: Install aborted due to no EULA acceptance
07/13/2020 04:09:44 - INSTALL: Checking arguments
07/13/2020 04:09:44 - INSTALL: always: Spawning background process: /usr/bin/php '/usr/share/cacti/install/background.php' 1594631384.0472

**Comment by myvelcn** [comment]
I am closing this issue. i have added both local and remote poller entries. Now it is working fine.

**Comment by myvelcn** [comment]
Issue fixed , added both local and remote poller details in include/config.php
