### ISSUE TITLE
v1.2.2 Create Graph Errors - Debian Repo

### ISSUE THREAD

**Issue by rotor-head** [Cacti/cacti#3689]
# Describe the bug

cacti.log output:
2020/07/13 - ERROR PHP ERROR: Uncaught Error: Call to undefined function api_tree_branch_exists() in /usr/share/cacti/site/lib/api_automation.php:2683 Stack trace: #0 /usr/share/cacti/site/lib/api_automation.php(2648): create_header_node('Traffic', Array, Array, '0') #1 /usr/share/cacti/site/lib/api_automation.php(2624): create_multi_header_node('Fixed String', Array, Array, '0') #2 /usr/share/cacti/site/lib/api_automation.php(2374): create_all_header_nodes('55', Array) #3 /usr/share/cacti/site/lib/api_automation.php(2131): automation_execute_graph_create_tree('55') #4 /usr/share/cacti/site/lib/template.php(1319): automation_hook_graph_create_tree(Array) #5 /usr/share/cacti/site/lib/template.php(1619): create_complete_graph_from_template('12', 6, Array, NULL) #6 /usr/share/cacti/site/graphs_new.php(220): create_save_graph(6, 'sg', 2, Array, Array) #7 /usr/share/cacti/site/lib/html_graph.php(447): host_new_graphs_save(6) #8 /usr/share/cacti/site/graphs_new.php(126): html_graph_new_graphs('graphs_new.php', 6, 2, Array) #9 /usr/share/cacti/s in file: /usr/share/cacti/site/lib/api_automation.php on line: 2683
2020/07/13 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())

## To Reproduce

1. Create new switch device, Click Save

2. Click on '*Create Graphs for this Device'

3. Click to check the 'Select All' tick box 

4. Click 'Create' button

## Expected behavior

Expected the web interface to load the next page for selection of colors and tilting the header info. It simply stays on the page and stalls with no user feedback describing there was an issue.

**Comment by netniV** [comment]
Have you searched through old issues, especially the CHANGELOG for everything fixed since 1.2.2 which is over a year old?

**Comment by rotor-head** [comment]
ooff. yes. I was looking at it when you responded. No maintainers for Debian? 

Drop kick this ticket.

**Comment by netniV** [comment]
@paulgevers maintains a cacti repo with a later version which is compatible with Debian but only if your version isn't too far behind due to its dependancies.

**Comment by paulgevers** [comment]
@rotor-head: you're on buster/Debian 10? Maybe it's time I put the latest Cacti version in the official backports archive. Would that help?

**Comment by rotor-head** [comment]
> @rotor-head: you're on buster/Debian 10? Maybe it's time I put the latest Cacti version in the official backports archive. Would that help?

Yes, buster ... It certainly would help @paulgevers. Thank you.

**Comment by paulgevers** [comment]
@rotor-head cacti just got accepted in the official buster-backports archive. Soon, you'll be able to install it from there.

**Comment by netniV** [comment]
@paulgevers thank you for your efforts on this 👍

**Comment by TheWitness** [comment]
Fantastic @paulgevers !!!
