### ISSUE TITLE
Cacti 1.0.3 - bits/sec with total bandwidth - missing CDEF on MAX lines

### ISSUE THREAD

**Issue by andytech77** [Cacti/cacti#369]
In Cacti 1.0.3, the "Interface - Traffic (bits/sec, Total Bandwidth)" template is missing the "Turn Bytes to Bits" CDEF function on the two LINE1 items for MAX traffic_in/traffic_out  (Items 1 and 7).

This causes the lines for these to be drawn at one-eighth of the correct value.

**Comment by cigamit** [comment]
Resolved.  Will only impact new installs.  Old installs should re-import the package.
