### ISSUE TITLE
Allow use of ifDescr  variable  in Tree rules 

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3696]
Hey Guys 

One thing that would be useful is being able to use the following Variable in the tree automation

ifDescr

My scenario is this 

Each of our devices connects to another router example
Site device A connects to Area router A
and  of the uplink port  of the site device  mentions the area router its connected to 

So If the option was there to select the ifdescr variable in the tree rules 
I can create a tree per Area router to bunch up the devices per area/router

it may be a corner case but I think a lot of people may find this useful even if its just that one variable

Thanks !

**Comment by bmfmancini** [comment]
Any thoughts on this guy's ?

**Comment by TheWitness** [comment]
ifDescr should already be there.

**Comment by bmfmancini** [comment]
its there for graph rules but not tree rules under object selection criteria 
unless I am completely missing it

**Comment by bmfmancini** [comment]
The weird thing to me anyways is that both tree_rules and graph_rules have the same includes 
yet show different variables in the dropdown

**Comment by bmfmancini** [comment]
Hey Guys I checked also on v1.2.15  this option is not there as well 
the option is there unde graph creation criteria but not for tree creation

**Comment by TheWitness** [comment]
Closing this one.

![image](https://github.com/user-attachments/assets/6d8b3c16-d3e5-46c7-aeca-9442378467ad)
