### ISSUE TITLE
No graphs data

### ISSUE THREAD

**Issue by d-mihaylenko** [Cacti/cacti#3697]
Hi, all graphs data has stopped coming. But online, all the graphs show.

Version cacti 1.2.11/1.2.12/1.2.13

<img width="1258" alt="Screenshot 2020-07-15 at 10 18 15" src="https://user-images.githubusercontent.com/17220673/87516595-5445cf80-c686-11ea-940c-76d1979e7c76.png">
<img width="1260" alt="Screenshot 2020-07-15 at 10 18 26" src="https://user-images.githubusercontent.com/17220673/87516602-56a82980-c686-11ea-87f9-622dfdb1ac5e.png">

I dont see any problems in logs

<img width="1440" alt="Screenshot 2020-07-15 at 10 35 55" src="https://user-images.githubusercontent.com/17220673/87517228-3fb60700-c687-11ea-8cda-3589edf709e5.png">

And /usr/bin/php7.3 /var/www/cacti/poller.php works without any problems

**Comment by d-mihaylenko** [comment]
rrdtool works fine too but data graphs are empty

<img width="1288" alt="Screenshot 2020-07-15 at 11 03 25" src="https://user-images.githubusercontent.com/17220673/87519921-f10a6c00-c68a-11ea-8605-e5405228d387.png">

**Comment by bmfmancini** [comment]
So you have 3 systems doing this at the same time

You mention 3 versions so I'm confused

Check your logs for poller overuns
Are you using spine ? If so run it in read-only mode

./spine -r -v 5

Check your rra permissions they should match the cacti user

**Comment by d-mihaylenko** [comment]
I meant that I tried to upgrade to 3 different versions and got the same effect on everyone, I also updated the spine to the last.

Logs poller added attachment
[poller_log.txt](https://github.com/Cacti/cacti/files/4925292/poller_log.txt)

I also checked the rights to the folder with rra and did not notice any problems, it is also visible that the files appear in it even now
<img width="446" alt="Screenshot 2020-07-15 at 15 55 54" src="https://user-images.githubusercontent.com/17220673/87547791-473fd500-c6b4-11ea-837a-eb7a2713def3.png">


I can’t start spine in read mode, help with this
<img width="798" alt="Screenshot 2020-07-15 at 16 01 13" src="https://user-images.githubusercontent.com/17220673/87547937-7c4c2780-c6b4-11ea-9f23-ec789f3c4da2.png">

**Comment by bmfmancini** [comment]
Sorry I think it's -R

**Comment by d-mihaylenko** [comment]
Thanks for help. There was a problem with the wrong poller timer, that was set once a minute in cacti and in the crontab this was every 5 minutes.
