### ISSUE TITLE
"Net-SNMP - Load Average" default Graph Template is malformed

### ISSUE THREAD

**Issue by CapitalF** [Cacti/cacti#370]
The Net-SNMP - Load Average graph template, which comes default with Cacti 1.0.x, is malformed. The Graph Items are all in random order.

**Comment by cigamit** [comment]
Please re-sequence your graphs.  It's an option under Graph Templates.  Before you do that, you should select the following:

select sequence from graph_templates_item where graph_template_id=? and local_graph_id = 0 order by sequence;

And it will show the correct order.
