### ISSUE TITLE
No Graph for GPON interface OLT

### ISSUE THREAD

**Issue by cacti-user** [Cacti/cacti#3701]
# Describe the bug

I have migrated cacti 0.8.8b to 1.2.13 and now the GPON traffic graphs are not showing anything. The values shows 'nan'

- OS: Redhat 7
- Cacti version 1.2.13
- Browser Firefox and Chrome

## To Reproduce
1. Create a new graph for GPON interface
2. Run real-time graph or wait for poller to complete polling
3. Graph Empty
![image](https://user-images.githubusercontent.com/68411536/87746647-2e1a5e00-c845-11ea-8c82-4b7ddd37b197.png)

## Expected behavior
The graph should plot traffic in/out values

## Screenshots
**Cacti version 0.8.8b** shows this graph for the same GPON interface
![image](https://user-images.githubusercontent.com/68411536/87746721-6752ce00-c845-11ea-8498-ad91d1fe99de.png)

## Additional context
In Data Source Troubleshooter, I can see the rrd is getting updated but the graph is failing to plot. Getting error "Data Source returned Bad Results for GPON_traffic_out Data Source returned Bad Results for GPON_traffic_in"

![image](https://user-images.githubusercontent.com/68411536/87746905-dcbe9e80-c845-11ea-85f6-05d4d6c5c93f.png)

Also looking at logs the SNMP output is 'U'

2020/07/17 15:05:03 - POLLER: Poller[Main Poller] Device[Host] DS[Host – GPON 0/18/0 – XGS-Combo-Auto] Graphs[Host – GPON 0/18/0 – XGS-Combo-Auto] SNMP: v3: IP Address, dsname: GPON_traffic_out, oid: .1.3.6.1.2.1.31.1.1.1.10.4194451456, **output: U**
2020/07/17 15:05:03 - POLLER: Poller[Main Poller] Device[Host] DS[Host – GPON 0/18/0 – XGS-Combo-Auto] Graphs[Host – GPON 0/18/0 – XGS-Combo-Auto] SNMP: v3: IP Address, dsname: GPON_traffic_in, oid: .1.3.6.1.2.1.31.1.1.1.6.4194451456, **output: U**

Tried Snmpget and getting this result
**ifHCInOctets.4194451456: Unknown Object Identifier (Index out of range: 4194451456 (ifIndex))**

But when running snmpget with option '-Ir' I get expected results
**IF-MIB::ifHCInOctets.4194451456 = Counter64: 8360398254462**

**Comment by cacti-user** [comment]
I was using cmd.php initially then tried to use spine, it made no difference. Sadly after switching to spine poller, in addition to GPON graphs, all my graphs are now empty. Switching back to PHP poller didn't help either. Realtime graphs still work fine. Checked the permissions of apache to rrd files  and they are still the same as they were initially

**Comment by cacti-user** [comment]
My bad, seems to be working fine with spine now. Config error

**Comment by cacti-user** [comment]
Apologies, have to re-open this. Spine has been creating some issue with gaps in graphs for random devices so had to revert back to cmd.php

**Comment by cacti-user** [comment]
This is the output from logs cmd.php VS Spine. However, due to spine causing random gaps in graphs, I have to use cmd.php

Spine
![image](https://user-images.githubusercontent.com/68411536/90324592-c9c5f800-dfc4-11ea-8278-e50aac92b0f1.png)

cmd.php
![Uploading image.png…]()

**Comment by netniV** [comment]
So instead of using spine which operates, you are falling back to cmd which doesn't?

**Comment by cacti-user** [comment]
Only reason I am falling back to php is that it does not have gaps on random device's standard ethernet ports, which are more critical then GPON at this stage for me. I would have liked to keep using spine too, but in daily reports we were seeing gaps in graphs. Which is a separate issue and I probably should open a separate ticket for, where spine was randomly failing to poll some OIDs or the whole device in a polling cycle

**Comment by TheWitness** [comment]
You might want to increase the timeouts on things.  if there is a timeout, on either a snmp get or a ping, spine will ignore the device.

**Comment by cacti-user** [comment]
I thought that might be the case, so tried with 10sec SNMP timeout, which was really high. But that didn't work either, unfortunately.

**Comment by TheWitness** [comment]
Well, with Spine, you have to be very careful with the Database max_connections as spine can use them up very fast.  It's something that we've put a warning on.  When using cmd.php, are you using the php-snmp modle (aka ```php -m```) or net-snmp, you don't have php-snmp installed.

Some snmp features are presently not supported with php-snmp installed.  So, if that is the case, you might want to uninstall php-snmp and try again.

**Comment by TheWitness** [comment]
I'm going to close this one.  If you have issues, continue to test using net-snmp cli.  If the indexes are changing, then you should consider changing the re-index method, if it's a remote poller that is experiencing the issues, that'll be fixed in 1.2.15.  Another thing to do if it's periodic and somewhat random, consider reducing the MAX OID's.
