### ISSUE TITLE
Graph Tree search problem

### ISSUE THREAD

**Issue by gleamx** [Cacti/cacti#3703]
# Describe the bug

First of all, sorry for my bad english!
When i do a search of graph from Graph Tree, the results only highlights, but keep showing all my devices and i think is tedious, to scroll down until find the device

## To Reproduce

After running the upgrade from 0.8.8a to 1.2.12

1. Login
2. Click on Graphs tab
3. Do a Search

## Expected behavior

I would expect that the results, only show what i'm really searching for.

## Screenshots

![imagen](https://user-images.githubusercontent.com/3728370/87822000-c06b3380-c83e-11ea-9f49-b70aafd3b7c6.png)

![imagen](https://user-images.githubusercontent.com/3728370/87822267-2bb50580-c83f-11ea-89f1-329cc7edc0ef.png)

## Desktop (please complete the following information)

None

## Smartphone (please complete the following information)

None

## Additional context

As i do work as web developer, i figured out, that was missing the class jstree-hidden in the default (style.css) of all themes. I recommend to put this lines in all of them:

Suggest: On line 70

.jstree-hidden,
.jstree-node.jstree-hidden {
  display: none;
}

Example path: /var/www/html/cacti/include/themes/modern/default/style.css

**Comment by TheWitness** [comment]
Pull request?
