### ISSUE TITLE
Reporting - Cascade to Branches function not working (Graphs in reporting shows only in 1 column)

### ISSUE THREAD

**Issue by cacti-user** [Cacti/cacti#3704]
# Describe the bug

In reporting when Type Tree and Graph Tree Branch is selected and if you want to turn on 'Cascade to Branches', it does not work. Preview only shows a single column. Even though I have selected 'Graph columns >3'

## To Reproduce

1. Create a Report

2. Add a Report Item

3. Select 'Type'>Tree, Graph Tree and Graph Tree Branch

4. Turn Cascade to Branches On

5. Graph Columns in report 'Details' are set to 2 or above

## Expected behavior

In the Reporting preview, you should see all graphs Cascaded to Branch.

## Screenshots
Turned Cascade to Branches On
![image](https://user-images.githubusercontent.com/68411536/87844827-6d17e480-c915-11ea-9cf1-06b71efd4d49.png)

Preview still shows single column
![image](https://user-images.githubusercontent.com/68411536/87844902-eb748680-c915-11ea-8b4f-68ce38ed2bac.png)

## Desktop (please complete the following information)

- Redhat 7

- Browser Firefox and Chrome

- Cacti version 1.2.13

## Additional context

In the older version (0.8.8b) I was using when Cascade to Branches was ticked, the graphs would render to the branch and shows in the correct column numbers selected.
![image](https://user-images.githubusercontent.com/68411536/87844987-df3cf900-c916-11ea-83b4-15bf254e954a.png)

![image](https://user-images.githubusercontent.com/68411536/87845011-2d51fc80-c917-11ea-83d4-80808661687d.png)

**Comment by TheWitness** [comment]
Okay, fixed now.

**Comment by TheWitness** [comment]
Reopening for comment.
