### ISSUE TITLE
PHP Notice when running cli script analyze_database.php

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#3707]
```
cacti:/var/www/html/cacti/cli# php ./analyze_database.php 
PHP Notice:  Constant CACTI_LANGUAGE_HANDLER_NONE already defined in /var/www/html/cacti/include/global_constants.php on line 462
PHP Notice:  Constant CACTI_LANGUAGE_HANDLER_PHPGETTEXT already defined in /var/www/html/cacti/include/global_constants.php on line 463
PHP Notice:  Constant CACTI_LANGUAGE_HANDLER_OSCAROTERO already defined in /var/www/html/cacti/include/global_constants.php on line 464
PHP Notice:  Constant CACTI_LANGUAGE_HANDLER_MOTRANSLATOR already defined in /var/www/html/cacti/include/global_constants.php on line 465
```

locales:
cacti:/var/www/html/cacti/cli# locale
```
LANG=pl_PL.UTF-8
LANGUAGE=pl_PL.UTF-8
LC_CTYPE="pl_PL.UTF-8"
LC_NUMERIC="pl_PL.UTF-8"
LC_TIME="pl_PL.UTF-8"
LC_COLLATE="pl_PL.UTF-8"
LC_MONETARY="pl_PL.UTF-8"
LC_MESSAGES="pl_PL.UTF-8"
LC_PAPER="pl_PL.UTF-8"
LC_NAME="pl_PL.UTF-8"
LC_ADDRESS="pl_PL.UTF-8"
LC_TELEPHONE="pl_PL.UTF-8"
LC_MEASUREMENT="pl_PL.UTF-8"
LC_IDENTIFICATION="pl_PL.UTF-8"
LC_ALL=pl_PL.UTF-8
```

branch: 1.2.x updated 5 mins ago

**Comment by netniV** [comment]
This would suggest that the GLOBAL_CONSTANTS.PHP file is being included more than once for some reason.

**Comment by bmfmancini** [comment]
Which version of cacti are you running ?

not seeing the same behavior here 

root@cact1:/var/www/html/cacti/cli# php analyze_database.php 
Analyzing All Cacti Database Tables
Analyzing Table -> 'aggregate_graph_templates' Successful
Analyzing Table -> 'aggregate_graph_templates_graph' Successful
Analyzing Table -> 'aggregate_graph_templates_item' Successful
Analyzing Table -> 'aggregate_graphs' Successful
Analyzing Table -> 'aggregate_graphs_graph_item' Successful
Analyzing Table -> 'aggregate_graphs_items' Successful
Analyzing Table -> 'automation_devices' Successful
Analyzing Table -> 'automation_graph_rule_items' Successful
Analyzing Table -> 'automation_graph_rules' Successful
Analyzing Table -> 'automation_ips' Successful
Analyzing Table -> 'automation_match_rule_items' Successful

**Comment by interduo** [comment]
Debian 10, branch: 1.2.x

**Comment by netniV** [comment]
Something strange there as `CACTI_LANGUAGE_HANDLER_NONE` is only defined in global_constants.php so you should have more than just the language constants causing you a problem.  The only other thing I can think of is that somehow, you are using something that is including global_languages.php BEFORE global_constants.php

**Comment by netniV** [comment]
I have verified that within our own sources, this should never happen.

```console
cacti$ ~/sp global_languages.php
Searching for global_languages.php
./include/global.php:497:include_once($config['include_path'] . '/global_languages.php');
```
```console
cacti$ ~/sp global_constants.php
Searching for global_constants.php
./lib/html_utility.php:898:   @arg $status - the status type of the device as defined in global_constants.php
./include/global.php:259:include_once($config['include_path'] . '/global_constants.php');
```
```console
cacti$ ~/sp CACTI_LANGUAGE_HANDLER_NONE
Searching for CACTI_LANGUAGE_HANDLER_NONE
./include/global_languages.php:207:		$l10n_handler = CACTI_LANGUAGE_HANDLER_NONE;
./include/global_languages.php:214:if (CACTI_LANGUAGE_HANDLER != CACTI_LANGUAGE_HANDLER_NONE) {
./include/global_languages.php:386:	define('CACTI_LANGUAGE_HANDLER', CACTI_LANGUAGE_HANDLER_NONE);
./include/global_constants.php:462:define('CACTI_LANGUAGE_HANDLER_NONE', 0);
```

Constants are always included before languages.  `sp` is a special alias I have for searching only PHP files (helpfully ignores any logs or RRD's etc).

**Comment by TheWitness** [comment]
I guess the comment here is was this installed via ports or installed via source or was it a mix?  If a mix of ports and source, I could see how something like this might happen. @paulgevers might know how that would happen.  Also, I think mainline 'develop' should be the 1.3.x branch now.  So, the 1.3.0 branch should be retired at some point.

**Comment by netniV** [comment]
errr, not sure you got that quite right ;-)

**Comment by paulgevers** [comment]
The paths mentioned above are **not** from the Debian package. Is (or was) it ever installed?

**Comment by interduo** [comment]
Cacti is from git not from Debian package.

**Comment by netniV** [comment]
Yeah sorry @paulgevers, in the first post it showed a CentOS/RedHat style of installation so I hadn't brought you in on the discussions.  If you have Cacti from git, can you do a git status and git log to see what the last commit you had is and if anything is out of step?

**Comment by interduo** [comment]
My last commit is:
```
Author: netniV <netniv@hotmail.com>
Date:   Sun Aug 2 22:24:44 2020 +0000

    Update for release 1.2.14
```

git status is empty...

**Comment by TheWitness** [comment]
@paulgevers, I should have noted that on the first post ```/var/www/html/cacti``` is not Debian.  Glad you are watching though.

**Comment by netniV** [comment]
```console
cli$ md5sum analyze_database.php
76b902c9bd980499bee56af3a3c16f79  analyze_database.php
```
Do you get the same checksum?

**Comment by netniV** [comment]
Also, what plugins do you have enabled?  Not sure any should kick in from the above program but you never know...

**Comment by interduo** [comment]
> @paulgevers, I should have noted that on the first post `/var/www/html/cacti` is not Debian. Glad you are watching though.

Joking? 
Configuration of httpd and www paths is not implicating the OS installed....

**Comment by netniV** [comment]
I was meaning from a package point of view.  If you were using the OS-packages, CentOS/RedHat place them into /var/www/html/cacti (or at least used to), if you are using Paul's ubuntu/debian packages, these go into /usr/share/cacti (if I remember rightly as it's been a while but I know it's not the CentOS directory).  So, that is why I didn't rope in Paul (for Ubuntu/Debian) or Morten (for CentOS/RedHat).

You then already said you did this via Git, so it involved neither of them again 👍 

None of that really answers my question though :-)

> - Do you get the same checksum?
>
> - what plugins do you have enabled?

**Comment by interduo** [comment]
> Do you get the same checksum?
Checksum of what?

I said `git diff origin/master` was clean.

> what plugins do you have enabled?

Monitor, maint, thold.

**Comment by netniV** [comment]
And I still asked for a checksum to be sure.

**Comment by interduo** [comment]
If You mean checksum of files downloaded by git are as expected.

**Comment by cigamit** [comment]
This doesn't happen on my install either.  Just curious, do you have any plugins installed?

**Comment by interduo** [comment]
I said it earlier - I've got installed and enabled: Monitor, maint, thold.

@cigamit what settings in php.ini Do You have?

```
cat /etc/php/7.3/cli/php.ini | grep error_reporting | grep =
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
```

**Comment by cigamit** [comment]
Sorry, I missed where you stated the plugins.  I have all 3 of those installed also.
PHP 7.2.24 running on Centos 8 (and I tested my Centos 7 with PHP 5.4.16)
error_reporting = E_ALL

I am running the devel branch instead of the 1.2.X, but they are pretty close currently.

**Comment by interduo** [comment]
I've got the problem with all cli scripts not only analyze_database.php

```
# php md5sum.php
PHP Notice:  Constant CACTI_LANGUAGE_HANDLER_NONE already defined in /var/www/html/cacti/include/global_constants.php on line 462
PHP Notice:  Constant CACTI_LANGUAGE_HANDLER_PHPGETTEXT already defined in /var/www/html/cacti/include/global_constants.php on line 463
PHP Notice:  Constant CACTI_LANGUAGE_HANDLER_OSCAROTERO already defined in /var/www/html/cacti/include/global_constants.php on line 464
PHP Notice:  Constant CACTI_LANGUAGE_HANDLER_MOTRANSLATOR already defined in /var/www/html/cacti/include/global_constants.php on line 465
ERROR: MD5 file '/var/www/html/cacti/.md5sum' is missing, cannot verify
```

```
# php about.php 
PHP Notice:  Constant CACTI_LANGUAGE_HANDLER_NONE already defined in /var/www/html/cacti/include/global_constants.php on line 462
PHP Notice:  Constant CACTI_LANGUAGE_HANDLER_PHPGETTEXT already defined in /var/www/html/cacti/include/global_constants.php on line 463
PHP Notice:  Constant CACTI_LANGUAGE_HANDLER_OSCAROTERO already defined in /var/www/html/cacti/include/global_constants.php on line 464
PHP Notice:  Constant CACTI_LANGUAGE_HANDLER_MOTRANSLATOR already defined in /var/www/html/cacti/include/global_constants.php on line 465
PHP Notice:  Undefined index: REQUEST_URI in /var/www/html/cacti/include/global_session.php on line 107
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta content='width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=5' name='viewport'>
[cut]
```


```
# php about.php 
PHP Notice:  Constant CACTI_LANGUAGE_HANDLER_NONE already defined in /var/www/html/cacti/include/global_constants.php on line 462
PHP Notice:  Constant CACTI_LANGUAGE_HANDLER_PHPGETTEXT already defined in /var/www/html/cacti/include/global_constants.php on line 463
PHP Notice:  Constant CACTI_LANGUAGE_HANDLER_OSCAROTERO already defined in /var/www/html/cacti/include/global_constants.php on line 464
PHP Notice:  Constant CACTI_LANGUAGE_HANDLER_MOTRANSLATOR already defined in /var/www/html/cacti/include/global_constants.php on line 465
PHP Notice:  Undefined index: REQUEST_URI in /var/www/html/cacti/include/global_session.php on line 107
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
[cut]
```

my locales are:
```
# locale
LANG=pl_PL.UTF-8
LANGUAGE=pl_PL.UTF-8
LC_CTYPE="pl_PL.UTF-8"
LC_NUMERIC="pl_PL.UTF-8"
LC_TIME="pl_PL.UTF-8"
LC_COLLATE="pl_PL.UTF-8"
LC_MONETARY="pl_PL.UTF-8"
LC_MESSAGES="pl_PL.UTF-8"
LC_PAPER="pl_PL.UTF-8"
LC_NAME="pl_PL.UTF-8"
LC_ADDRESS="pl_PL.UTF-8"
LC_TELEPHONE="pl_PL.UTF-8"
LC_MEASUREMENT="pl_PL.UTF-8"
LC_IDENTIFICATION="pl_PL.UTF-8"
LC_ALL=pl_PL.UTF-8
```

**Comment by interduo** [comment]
Ok I've found it. It was workaround for error from year ago: https://github.com/Cacti/cacti/issues/3270#issuecomment-588196057.

Deleted the constants from config.php and it's working like expected now.

**Comment by netniV** [comment]
My next step was going to have you add a `cacti_debug_backtrace()` to the top of the file in order to find out where the inclusions where coming from.  Shows how a little tinkering a long time ago can raise its head years later... though I am surprised you haven't had that with any of the other installs/upgrades?

Thankfully, you found it yourself though I wouldn't have guessed that file in a million years.  This is why using a json file for configuration is better than an executable one.  Maybe something for a later development.
