### ISSUE TITLE
cacti.db import: ERROR 1071 (42000) at line 2560: Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by CapitalF** [Cacti/cacti#371]
This is a re-open of: https://github.com/Cacti/cacti/issues/360

Sorry about that. I provided incomplete information.

The problem is that the "utf8" character set is 3-byte and is not true "UTF8". The true UTF8 character set is utf8mb4, which is 4-bytes in size. All modern MySQL/MariaDB installations use utf8mb4 by default and changing this setting at the global level is probably not appropriate.

Because of the character byte size difference, index keys are no longer fitting in the innodb limit of 767 bytes. All of those indexes/keys that no longer fit are going to need to get reconsidered.

Until the database can be properly migrated to 4-byte UTF8, databases will need to be created with: "create database cacti DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;"

In addition to new databases being created correctly, there will probably need to be some kind of migration script to handle this.

**Comment by cigamit** [comment]
I'll be testing this later this morning.  We kept the indexes under 191 to keep everything under the 767 boundary.  It was working for me some time ago.  We may have to set a new recommendation for the wider index length in MySQL and MariaDB.

**Comment by cigamit** [comment]
Closing this one and re-opening the other.  You can simply comment on the old ticket.  No need to open a new one.
