### ISSUE TITLE
WARNING: Poller Output Table not empty for poller id 1. Issues: 1

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#3712]
# Describe the bug

I get mails with content (not every pool but every 4-5th pool):
WARNING: Poller Output Table not empty for poller id 1. Issues: 1, DS[10453].
...
WARNING: Poller Output Table not empty for poller id 1. Issues: 1, DS[10461].
...
WARNING: Poller Output Table not empty for poller id 1. Issues: 1, DS[10453].
...
WARNING: Poller Output Table not empty for poller id 1. Issues: 1, DS[10461].
...
WARNING: Poller Output Table not empty for poller id 1. Issues: 1, DS[10453].
...
WARNING: Poller Output Table not empty for poller id 1. Issues: 1, DS[10453].
...
WARNING: Poller Output Table not empty for poller id 1. Issues: 1, DS[10453].
...
WARNING: Poller Output Table not empty for poller id 1. Issues: 1, DS[10453].

and then I go to DB terminal and run: `SELECT * FROM poller_output;` and it's always empty.

## Expected behavior
More diagnostic info in email.

How to deal with that? I checked whole internet.

Branch: 1.2.x, 
Spine: SPINE 1.2.12

**Comment by bmfmancini** [comment]
Do you have a device timing out ?
Maybe when you checked the table at that time it was a good poll cycle 
I have those errors as well but on devices that constantly time out

**Comment by interduo** [comment]
No.

**Comment by netniV** [comment]
Basically, poller_output left overs are normally due to overruns.  Check whether you have any overruns being reported.

**Comment by TheWitness** [comment]
The poller will purge the value at the start of each new polling cycle.  This is generally an issue with a template that requires two or more output values and some number less than that are being returned by the scripts.

**Comment by TheWitness** [comment]
Since there has been no discussion on this, I'm going to close.

**Comment by interduo** [comment]
Well if there is situation when the poller table is not empty - please do debug output in raport not only that the poller table is not empty because the poller table is cleaned on new poller run.
