### ISSUE TITLE
When sorting data debug checks by user, no results are shown and errors recorded

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/cacti#3713]
## To Reproduce

1. Go to 'Troubleshooting - Data Sources page'

2. Sort by User in this page, no item display --failed

3. Check log, error exist 
2020/07/22 14:55:45 - CMDPHP SQL Backtrace: (/data_debug.php[137]:debug_wizard(), /data_debug.php[507]:db_fetch_assoc(), /lib/database.php[476]:db_fetch_assoc_prepared(), /lib/database.php[490]:db_execute_prepared())
2020/07/22 14:55:45 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'username' in 'order clause' 

## Screenshots

![Screen Shot 2020-07-22 at 4 59 57 PM](https://user-images.githubusercontent.com/47589910/88157834-d7929280-cc3d-11ea-9d42-53c307e83c38.png)

## Desktop (please complete the following information)

- OS: rhel7.7 x64

- Browser FF

- Version  cacti 1.2.13

**Comment by netniV** [comment]
This would suggest that column needs a nosort as it's a calculated or included column that is possibly being renamed so has the wrong value for the name.  Have you supplied a fix or are we to do this one?

**Comment by yingbaiibm** [comment]
@netniV  please fix this.
