### ISSUE TITLE
Newly added devices are missing from the list. [Management > Devices]

### ISSUE THREAD

**Issue by abhisheksahnii** [Cacti/cacti#3714]
# Describe the bug

After upgrading cacti from 1.1.38 to 1.2.12 it has been observed that after creating new devices I can be able to see the graphs but I could be able to find the device in the devices list, 

**Admin Portal > Management > Devices.**

Similar to this one - https://github.com/Cacti/cacti/issues/3481

I have already updated the host.php from the latest available branch but the issue is still there.

**Workaround -** 

After digging a bit into DB, comparing the problematic (missing) devices with the visible one. I found,

Devices with "Location" = "NULL" are visible and Devices with "Location" = "None" are not visible. 

so I changed the flag to NULL for the missing devices which made them to visible in the list.

## Expected behavior

Newly added devices must be visible in the list.

## Additional context

Please let me know if I have missed something. It seems like, while upgrading I might have missed something.

**Comment by abhisheksahnii** [comment]
Noticed one more issue, I am not able to filter devices on behalf of their location. Whenever I select the location the box turns to blank.  
/cacti/host.php   
Console > Devices. 

ssl_error logs, 

While page loads,

PHP Notice:  Undefined index: created in /var/www/html/cacti/host.php on line 1764

**Comment by bmfmancini** [comment]
Hey there this was fixed in the 1.2x branch grab host.php from there
