### ISSUE TITLE
Cannot Sync Graph Template

### ISSUE THREAD

**Issue by Harry-Om** [Cacti/cacti#3717]
# Describe the bug
Modify the Graph Template "Interface Errors/Discards" first, add  ~ |query_ifName| ~ |query_ifAlias| to the Title. 

## To Reproduce

Console Graph Templates
Graph
Edit "Interface - Errors/Discards", Title edit, add ~ |query_ifName| ~ |query_ifAlias|, save.
Select "Interface - Errors/Discards".
Action - Sync Graphs

2020/07/23 06:26:46 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
--
2020/07/23 06:26:46 - ERROR PHP ERROR: Call to undefined function  api_data_source_cache_crc_update() in file:  /usr/share/cacti/lib/utility.php on line: 745

## Expected behavior
Change to the devices is not applied. If i goto Graph from Any device, change is not applied.

## Desktop (please complete the following information)

VMWare Cluster
CentOS Linux release 7.8.2003 (Core)
mariadb-server.x86_64  1:5.5.65-1.el7  

Firefox, Chrome
Same Problem

## Smartphone (please complete the following information)

Firefox, Chrome
Same Problem

## Additional context
Tried to execute "php repair_graphs.php --execute --data-template-id=31 --graph-template-id=37"

**Comment by bmfmancini** [comment]
What version of cacti are you running?
Tested here on 1.2.11 and 1.2.12 not seeing this issue

**Comment by Harry-Om** [comment]
I tried a fresh install, Centos, MariaDB. Insert One Cisco Switch. Then edit Graph Template "Interface - Errors/Discards", insert in the Title  |query_ifName| ~ |query_ifAlias|, save. 
Select, sync Graphs, go. Error Log is the same message and no graph is changed.

Error Log:
2020-07-29 05:58:56 - ERROR PHP ERROR: Call to undefined function api_data_source_cache_crc_update() in file: /usr/share/cacti/lib/utility.php on line: 745
2020-07-29 05:58:56 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())

Installed Packages
cacti.noarch                                                                         1.2.12-1.el7      
cacti-spine.x86_64                                                                   1.2.12-1.el7      
mariadb.x86_64                                                                           1:5.5.65-1.el7
mariadb-devel.x86_64                                                                     1:5.5.65-1.el7
mariadb-libs.x86_64                                                                      1:5.5.65-1.el7
mariadb-server.x86_64                                                                    1:5.5.65-1.el7
CentOS Linux release 7.8.2003 (Core)

**Comment by netniV** [comment]
Fresh install from what source?  Was it 1.2.13 ?

**Comment by Harry-Om** [comment]
I tried a fresh install, Centos, MariaDB. Insert One Cisco Switch. Then edit Graph Template "Interface - Errors/Discards", insert in the Title  |query_ifName| ~ |query_ifAlias|, save. 
Select, sync Graphs, go. Error Log is the same message and no graph is changed.

Error Log:
2020-07-29 05:58:56 - ERROR PHP ERROR: Call to undefined function api_data_source_cache_crc_update() in file: /usr/share/cacti/lib/utility.php on line: 745
2020-07-29 05:58:56 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())

Installed Packages
cacti.noarch                                                                         1.2.12-1.el7      
cacti-spine.x86_64                                                                   1.2.12-1.el7      
mariadb.x86_64                                                                           1:5.5.65-1.el7
mariadb-devel.x86_64                                                                     1:5.5.65-1.el7
mariadb-libs.x86_64                                                                      1:5.5.65-1.el7
mariadb-server.x86_64                                                                    1:5.5.65-1.el7
CentOS Linux release 7.8.2003 (Core)


> 
> 
> What version of cacti are you running?
> Tested here on 1.2.11 and 1.2.12 not seeing this issue

Tested on 1.2.12 with Centos.

**Comment by netniV** [comment]
I think this has already been resolved in #3646.  If you can, try upgrading to 1.2.14.

**Comment by Harry-Om** [comment]
> 
> 
> I think this has already been resolved in #3646. If you can, try upgrading to 1.2.14.

I tried a fresh install of 1.2.14, same issue, with same errors in log...

**Comment by Harry-Om** [comment]
> 
> 
> > I think this has already been resolved in #3646. If you can, try upgrading to 1.2.14.
> 
> I tried a fresh install of 1.2.14, same issue, with same errors in log...

After Sync Graph, this log was created.

2020/09/02 10:58:55 - ERROR PHP ERROR: Call to undefined function api_data_source_cache_crc_update() in file: /usr/share/cacti/lib/utility.php on line: 745
2020/09/02 10:58:55 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
2020/09/02 10:59:31 - ERROR PHP ERROR: Call to undefined function api_data_source_cache_crc_update() in file: /usr/share/cacti/lib/utility.php on line: 745
2020/09/02 10:59:31 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())

**Comment by TheWitness** [comment]
This was resolved last week.
