### ISSUE TITLE
Improve usability/appearance of dark theme scroll bars

### ISSUE THREAD

**Issue by CapitalF** [Cacti/cacti#372]
See attached picture

![cacti_dark_scrollbars_chrome](https://cloud.githubusercontent.com/assets/13446991/23583767/de39864a-010a-11e7-99b2-eeab16054f35.png)

First off, let me thank the Cacti team for the new themes. They look pretty good, and I'm very fond of the new dark theme.

However, as pictured, the dark theme scroll bar sizes need a review.

The vertical scroll bar is too thin and is difficult to click on with the mouse cursor. Please increase it's width.

The horizontal bar is functional, but seems a tad bit too fat. Suggest reducing it slightly.

Thanks

**Comment by cigamit** [comment]
You can submit a pull request on this one.  That's the route I suggest.
