### ISSUE TITLE
Device gone (again)

### ISSUE THREAD

**Issue by rcsmota** [Cacti/cacti#3721]
# Describe the bug

On "console -> Devices" not show all my Devices. I opened an issue previously ( https://github.com/Cacti/cacti/issues/3481) which was solved with the help of @TheWitness   but now with the update to 1.2.13 it happened again.

I can see the graphics in the tree but in the list of devices (Console -> Management -> Devices) it does not appear.

If enter on another device and put your ID on browser I can enter on configuration

![imagem](https://user-images.githubusercontent.com/31240306/88374624-ee49fe00-cd91-11ea-99c3-077b813f0920.png)

change only de ID number of 2 to 3 for example.

Should I do the same as last time?

Thanks

**Comment by bmfmancini** [comment]
Try pulling host.php from the 1.2.x branch I dont think the fix was in the source zip for 1.2.13 so you may have overwrote the fix
pull it and do a diff to make sure

**Comment by rcsmota** [comment]
Hi @bmfmancini . With the host.php of 1.2.x branch resolved the problem.

Thank you.
