### ISSUE TITLE
External Links - switch between tabs

### ISSUE THREAD

**Issue by rcsmota** [Cacti/cacti#3722]
I'm running a Cacti 1.2.13 on a Debian Machine.

I have some external link on tabs, when I am in one of the cacti tabs and open an external link tab it opens without problems, but if it is already in an external link tab it does not open another one, it stays in the same place and I don't see error logs anywhere .
To go to another tab of an external link I have to open a tab of a cacti link, graphics for example, and then go to another external tab.

Thanks

**Comment by netniV** [comment]
Do you have the target set as _blank or _new ?  This is off the top of my head without looking into the externa links code.  If they are a named link, it will try to reuse it

**Comment by TheWitness** [comment]
Fixed this.  Thanks for reporting.
