### ISSUE TITLE
The ability to right-click and save graphs has been removed, please re-add it

### ISSUE THREAD

**Issue by CapitalF** [Cacti/cacti#373]
In Cacti 0.8.8h, it was possible to right-click on a graph in Tree View and save the graph as an image file.

However, in Cacti 1.0.x, this is no longer possible because the JS function which captures context menu activity has been expanded from only the grid-view area to the entire graph image area. The result is that an end-user can not right-click and save graphs because the zoom mode context menu replaces the standard browser context menu.

I would suggest simply restoring the previous behavior since that's what users are accustomed to and provides the functionality of both features.

**Comment by cigamit** [comment]
I agree, and browniebraun has self assigned.  It will not make it into 1.0.5, but soon thereafter I hope.

**Comment by browniebraun** [comment]
I've added a new option to download the graph image directly out of Zoom's right click menu in hope that this hits your expectations.
Regards
-Andi

**Comment by CapitalF** [comment]
Personally, your fix will meet my needs, so thanks!. However, I'm concerned that it's not the "right thing to do". Depending on your browser, that right-click context menu might let you do any of a number of things:

Copy the image URL/location
Open the image/object in a new window and/or tab
Save the image locally
Do any other number of things that some plugin might let you do

All of these things are now not possible.

More importantly, what's the justification for expanding the context menu area to the entire image rather than just than using the graph area like it was before? I suppose it's non-intuitive that you can right-click in different places and get different results.

These are just thoughts. Totally up to you guys on what to do.
