### ISSUE TITLE
Graphs created for all interfaces | Reload Query | Cacti 1.2.13

### ISSUE THREAD

**Issue by ndhami23** [Cacti/cacti#3731]
Dear Team,

When I hit a reload query under SNMP - Interface Statistics item it automatically creates a graph for all the associated interfaces for the device instead of reloading interface related parameters/indexes. Please suggest.

**Comment by bmfmancini** [comment]
check your autom8 rules do you have the rule to create graphs for all interfaces ?
if you reload the query I belive the autom8 rules also run as well when it finds something new

**Comment by ndhami23** [comment]
Yes, automatic graph rule was enabled, and the problem was resolved after disabling it. Thanks!
