### ISSUE TITLE
Can't graph over 100/110 Mbps | Cacti 1.2.13

### ISSUE THREAD

**Issue by ndhami23** [Cacti/cacti#3732]
Hi Team,

I am not able to plot over 100/100 Mbps when using a 32 bit counter in cacti 1.2.13 while there's no issue with older releases like 0.8.8b or 1.0.3 that I am using till 1Gbps. Any ideas, please?

**Comment by riversdev0** [comment]
Two ideas for you:
1. Is it possible that when the data query was built, that the data source template has a maximum value that is too small?  To check this, go to Management > Data Sources and click on the Data Source that you are having problems with.  What is the value filled in for 'Maximum Value'?
2. If you are using 32-bit counters and the interface is constantly running over about 700-800 Mbps, the 32-bit counter will be overflowing more than 1 time each minute.  RRDtool is able to handle an overflow with no problems, except that the counter rolled over twice, not once.  Therefore, the RRD will calculate a value that is too small, and it will look like the link is always running a lot slower than reality.

**Comment by cigamit** [comment]
This is a limitation of 32 counters.  Use 64 bit counters instead.

**Comment by ndhami23** [comment]
> Two ideas for you:
> 
> 1. Is it possible that when the data query was built, that the data source template has a maximum value that is too small?  To check this, go to Management > Data Sources and click on the Data Source that you are having problems with.  What is the value filled in for 'Maximum Value'?
> 2. If you are using 32-bit counters and the interface is constantly running over about 700-800 Mbps, the 32-bit counter will be overflowing more than 1 time each minute.  RRDtool is able to handle an overflow with no problems, except that the counter rolled over twice, not once.  Therefore, the RRD will calculate a value that is too small, and it will look like the link is always running a lot slower than reality.

Hi riversdev0,
- data query is built with a 1000000000 and I don't suppose that's an issue. With 64 bit-counters I am not getting such problems but I am wondering now why Cacti is still using 32-bit counters and what's purpose/benefits of using it instead of 64-bit counters.

**Comment by riversdev0** [comment]
These counters are not inside Cacti, they are inside the network device.  When you created the graphs, you told Cacti to read the 32-bit counters inside the device.  Many years ago, when devices were slower, the counters only needed to be 32-bits.  As networks got faster, there was a need to make the counters go up higher, so now there are 64-bit counters, also.   The 32-bit counters are still around for backward-compatibility.  Thus, when you switch to use 64-bit counters, you are just telling Cacti to pull a different SNMP OID on the network device.

**Comment by ndhami23** [comment]
> These counters are not inside Cacti, they are inside the network device. When you created the graphs, you told Cacti to read the 32-bit counters inside the device. Many years ago, when devices were slower, the counters only needed to be 32-bits. As networks got faster, there was a need to make the counters go up higher, so now there are 64-bit counters, also. The 32-bit counters are still around for backward-compatibility. Thus, when you switch to use 64-bit counters, you are just telling Cacti to pull a different SNMP OID on the network device.

Hi riversdev0,
Thanks a lot for making it clear! 👍
