### ISSUE TITLE
Aggregate graphs issue | 2 Aggregate graphs created one under aggregate tree and another under device tree | Cacti v1.2.13

### ISSUE THREAD

**Issue by ndhami23** [Cacti/cacti#3736]
Hi Team,

In Cacti v1.2.13 if I am creating aggregate graphs it automatically creates two aggregate graphs one under the aggregate tree and another under a device itself. Not sure whether this is a desired feature or purpose of it or maybe I am hitting a bug. If this is an expected behavior can I turn it off to stop creating an aggregate inside the device tree? and is there any way to put a threshold in an aggregate graph? Kindly suggest.

**Comment by netniV** [comment]
I would say this is by design if you have placed the device on the tree as well as have the automation rules set to automatically add new graphs.
