### ISSUE TITLE
Dark Theme graph tool buttons are hidden by default

### ISSUE THREAD

**Issue by CapitalF** [Cacti/cacti#374]
In Tree View mode, as well as some other graph viewing modes, there are buttons on the upper right corner exterior of each graph. These buttons offer features such as Graph Zooming, debugging,CVS export, Time Graph View, and Real Time graphing.

However, in the dark theme, these buttons are hidden by default and require a mouse-over in the general area to enable them.

Please remove this mouse-over behavior and show these buttons, just like the other themes do. Hiding UI elements doesn't serve a functional purpose which helps the user.

Alternately, please apply this mouse-over behavior to all themes so that they are uniform in functionality.

**Comment by cigamit** [comment]
The easiest way to fix this is to:

cp -rp dark mydark

And then edit away mydark.  If you like, you can create a pull request to merge it.  Though, please keep in mind that when we goto jQueryUI 1.12 things will break.  We have to move there, but it's turning out to be a pretty big project.
