### ISSUE TITLE
Will mURLin pluguin be adapted to version 1.2.x? 

### ISSUE THREAD

**Issue by Alexisclv** [Cacti/cacti#3742]
If someone want to work on this plugin adaptation ?

**Comment by cigamit** [comment]
mURLin is a 3rd Party plugin, you would have to ask the author if he plans to convert it.  Webseer has URL monitoring also and has been adapted to 1.2.X, you may give it a try and see if it will work for you.
https://github.com/Cacti/plugin_webseer

**Comment by netniV** [comment]
I have a port of mURLin on my repos but I don't actually use it myself as I use Webseer
