### ISSUE TITLE
Description field allows more characters entered than is stored

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#3743]
# Describe the bug

If you modify a device, such as Localhost, and give it a seriously long description by repeated pasting ' extremely' to fill the maximum length, then change the last two to be ' long description', the long description part will not be saved.

## Expected behavior

All the description should be saved by ensuring that length of database meets length of field

**Comment by TheWitness** [comment]
This problem is actually larger than you may think.  We should have a project in the 1.3.x timeline that audit's the forms for the column descriptions, or we should deprecate "max_length" and just set it to the database column size.  Easier said than done I imagine.
