### ISSUE TITLE
ldap.php cannot be loaded while installer is running.

### ISSUE THREAD

**Issue by browniebraun** [Cacti/cacti#3747]
Only happening while the installer is running, because in this case the current working directory is /install/.
Introduced by the changing the path from 

`include_once(__DIR__ . '/lib/ldap.php');`

to 

```
/* include ldap support */
include_once('./lib/ldap.php');
```

**Comment by netniV** [comment]
This is one of four things I sent myself to fix last night but I didn't get to it. Saved me opening the issue.

**Comment by netniV** [comment]
Also it looks like @cigamit also patched this yesterday so funny that there are three of us on the same page.

**Comment by browniebraun** [comment]
*lol* -  I'm back from vacay ;)

**Comment by TheWitness** [comment]
Is this all resolved then?

**Comment by eschoeller** [comment]
I also got hit by this bug on an upgrade to 1.2.14. Glad it was already worked out:)
