### ISSUE TITLE
Unable to remove discovered device

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#3748]
# Feature Request

## Is your feature request related to a problem? Please describe

When working with many automation networks, you may want to remove a site or selection of devices from the discovered device list, especially when you know that they will not show up again in the future.

## Describe the solution you'd like

Ability to remove discovered devices by using the standard Cacti table selection processes.

**Comment by TheWitness** [comment]
I'm surprised it's not there already.

**Comment by TheWitness** [comment]
I'm labeling this as a design bug.
