### ISSUE TITLE
Drag and Drop of Devices and Graph Items  in Tree Management

### ISSUE THREAD

**Issue by thurban** [Cacti/cacti#375]
In Cacti 1.0.4 it is possible to drag&drop devices from the "Available Devices" to the "Available Devices"  box.  The same is true with the "Availabe Graphs" items.  See the attached Video for an example.

Server:
Cacti 1.0.4
Centos 7

Client:
Chrome Version 56.0.2924.87
Windows 10 64 bit

[DragAndDrop_Issues.zip](https://github.com/Cacti/cacti/files/819451/DragAndDrop_Issues.zip)

Dropping items to these two lists shouldn't be possible as they are the source for the Tree.

**Comment by cigamit** [comment]
Hmm.  That was blocked at one point.  Will have to review and see what changed.

**Comment by cigamit** [comment]
Resolved, thanks for reporting!
