### ISSUE TITLE
Missing database fields on develop branch

### ISSUE THREAD

**Issue by rtripon** [Cacti/cacti#3752]
Hello,
I have a brand new install of Cacti 1.3.0 [ 1.3.0 - Dev d951897 @ 2020-08-10 06:02 ] and I seem to have tons of errors in logs, like the ones bellow. 
2020/08/12 13:25:14 - CMDPHP PHP ERROR NOTICE Backtrace:  (/host.php[157]:host(), /host.php[1764]:CactiErrorHandler())
--
2020/08/12 13:25:14 - ERROR PHP NOTICE: Undefined index: created in file: /var/www/html/cacti/host.php  on line: 1764

Also some error from automation plugin :+1: 

2020/08/12 13:30:33 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
--
2020/08/12 13:30:33 - ERROR PHP ERROR: Uncaught Error: Call to  undefined function debug() in  /var/www/html/cacti/lib/api_automation.php:3707 Stack trace: #0  /var/www/html/cacti/lib/api_automation.php(3518):  calculateNextStart(Array, 1597228233) #1  /var/www/html/cacti/poller_automation.php(222):  api_automation_is_time_to_start('3') #2 {main} thrown in file:  /var/www/html/cacti/lib/api_automation.php on line: 3707

Except the logs, all seems to work properly, graphs are populated.

**Comment by netniV** [comment]
Try running the upgrade_database.php script with `--forcever-1.2.14` as this should create the missing fields.  We probably need to sync the database with the cacti.sql script so that installs from github are clean.

**Comment by rtripon** [comment]
Thanks, that seems to get rid of the error. Any hints for the api_automation errors?.

**Comment by netniV** [comment]
I'll take a look tomorrow as not sure what that would be.

**Comment by rtripon** [comment]
Hello,
I'm posting here since its kinda related : 
After I did the upgrade to 1.2.14 I've noticed some weird behaviour : The server is getting high cpu(from mysqld) and everytime I try to delete graphs for a device it hangs(while the CPU is increasing its load) and web server isnt accesible anymore. 
![504 gateway timeout](https://user-images.githubusercontent.com/28921178/92134444-34bf5d80-ee12-11ea-8b05-07ce0bebd643.jpg)
![504 timeout](https://user-images.githubusercontent.com/28921178/92134451-36892100-ee12-11ea-9ab5-21cbc403f736.jpg)

After a reboot, everything is back to normal(cpu load is 0.xx, while during the graph delete its getting to 5-6.
Also some errors in httpd log :

[Wed Sep 02 09:38:06.063143 2020] [proxy_fcgi:error] [pid 50447:tid 140133777012480] (70007)The timeout specified has expired: [client 192.168.1.1:51138] AH01075: Error dispatching request to :5080: (polling), referer: http://192.168.1.254:5080/index.php
[Wed Sep 02 13:48:05.159084 2020] [proxy_fcgi:error] [pid 50446:tid 140134338832128] (70007)The timeout specified has expired: [client 192.168.1.1:49321] AH01075: Error dispatching request to :5080: (polling), referer: http://192.168.1.254:5080/graphs.php?
[Wed Sep 02 13:50:09.211255 2020] [proxy_fcgi:error] [pid 50445:tid 140134229989120] (70007)The timeout specified has expired: [client 192.168.1.1:49352] AH01075: Error dispatching request to :5080: (polling), referer: http://192.168.1.254:5080/graphs.php?
[Wed Sep 02 13:50:38.658701 2020] [proxy_fcgi:error] [pid 50445:tid 140134196418304] (70007)The timeout specified has expired: [client 192.168.1.1:49370] AH01075: Error dispatching request to :5080: (polling), referer: http://192.168.1.254:5080/graph_view.php?action=tree&node=tbranch-68&host_id=26&site_id=-1&host_template_id=-1&hgd=&hyper=true
[Wed Sep 02 13:52:02.245097 2020] [proxy_fcgi:error] [pid 50445:tid 140134506817280] (70007)The timeout specified has expired: [client 192.168.1.1:49388] AH01075: Error dispatching request to :5080: (polling), referer: http://192.168.1.254:5080/graph_view.php?action=tree&node=tbranch-68&host_id=26&site_id=-1&host_template_id=-1&hgd=&hyper=true
[Thu Sep 03 17:56:34.675084 2020] [proxy_fcgi:error] [pid 50446:tid 140134372402944] (70007)The timeout specified has expired: [client 192.168.1.1:50546] AH01075: Error dispatching request to :5080: (polling), referer: http://192.168.1.254:5080/graphs.php?
[Thu Sep 03 17:56:45.748525 2020] [proxy_fcgi:error] [pid 50447:tid 140133944768256] (70007)The timeout specified has expired: [client 192.168.1.1:50570] AH01075: Error dispatching request to :5080: (polling), referer: http://192.168.1.254:5080/clog.php
[Thu Sep 03 17:57:37.179130 2020] [proxy_fcgi:error] [pid 50446:tid 140133927982848] (70007)The timeout specified has expired: [client 192.168.1.1:50546] AH01075: Error dispatching request to :5080: (polling), referer: http://192.168.1.254:5080/clog.php


PS : I did a php repair_database also. Didnt help.

**Comment by rtripon** [comment]
More databases errors/warning : 


2020-09-04  7:13:30 272 [Warning] Aborted connection 272 to db: 'cacti' user: 'cacti' host: 'localhost' (Got timeout reading communication packets)
2020-09-04  7:14:31 274 [Warning] Aborted connection 274 to db: 'cacti' user: 'cacti' host: 'localhost' (Got timeout reading communication packets)
2020-09-04  7:15:32 277 [Warning] Aborted connection 277 to db: 'cacti' user: 'cacti' host: 'localhost' (Got timeout reading communication packets)
2020-09-04  7:16:33 278 [Warning] Aborted connection 278 to db: 'cacti' user: 'cacti' host: 'localhost' (Got timeout reading communication packets)
2020-09-04  7:17:34 273 [Warning] Aborted connection 273 to db: 'cacti' user: 'cacti' host: 'localhost' (Got timeout reading communication packets)
2020-09-04  7:18:36 276 [Warning] Aborted connection 276 to db: 'cacti' user: 'cacti' host: 'localhost' (Got timeout reading communication packets)
2020-09-04  7:19:37 269 [Warning] Aborted connection 269 to db: 'cacti' user: 'cacti' host: 'localhost' (Got timeout reading communication packets)
2020-09-04  7:20:38 531 [Warning] Aborted connection 531 to db: 'cacti' user: 'cacti' host: 'localhost' (Got timeout reading communication packets)
2020-09-04  7:21:39 275 [Warning] Aborted connection 275 to db: 'cacti' user: 'cacti' host: 'localhost' (Got timeout reading communication packets)
2020-09-04  7:22:40 530 [Warning] Aborted connection 530 to db: 'cacti' user: 'cacti' host: 'localhost' (Got timeout reading communication packets)
