### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by mikygee** [Cacti/cacti#3753]
Version: 1.2.14

Hello,

I do a fresh install and I see this message
`2020/08/13 09:43:11 [error] 57141#0: *116 FastCGI sent in stderr: "PHP message: PHP Warning:  Invalid argument supplied for foreach() in /htdocs/cacti-1.2.14/lib/installer.php on line 1791" while reading response header from upstream, client: 192.168.99.202, server: _, request: "POST /install/step_json.php HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm.cacti.sock:", host: "MyIP:8080", referrer: "http://MyIP:8080/install/install.php?data={%22Step%22:%222%22,%22Eula%22:true}"`

I saw a message stating it was fixed in 1.2.3 but I have it on 1.2.14

I'm stuck at page 2 because I have warnings saying php modules cli - No

I open this issue for the error message

**Comment by netniV** [comment]
Check your path_php_bin setting is correct. I need to modify the 1.3 installer to ask for the file paths first so we can handle things properly.

**Comment by mikygee** [comment]
Hello Mark,
Yes I think it's correct
> select * from settings where name='path_php_binary';
+-----------------+----------+
| name            | value    |
+-----------------+----------+
| path_php_binary | /bin/php |
+-----------------+----------+
1 row in set (0.000 sec)

$ /bin/php -v
PHP 7.3.17 (cli) (built: Aug  1 2020 11:59:21) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.17, Copyright (c) 1998-2018 Zend Technologies

So the problem lives somewhere else.

Please also check the rights for the php binary. The http user should be able to execute it.

**Comment by netniV** [comment]
What OS is this?

**Comment by mikygee** [comment]
The OS is Openbsd + Nginx and Chrooted
But cacti is already installed on a different machine with the same version and it works.
Which tests are done by the installer ?

**Comment by netniV** [comment]
It requests a list of enabled modules from PHP runtime and returns that back via json to the webserver.  This is suggesting there's something different setup between the two machines then

**Comment by mikygee** [comment]
Is it this invoked command ?
`php -q /cacti/install/cli_check.php`

**Comment by netniV** [comment]
Yes, and you can call it with a single argument of either 

- extensions
- recommends
- optionals

**Comment by mikygee** [comment]
Thank you Mark.

All three display the same output
```
FATAL: Connection to Cacti database failed. Please ensure:
  - the PHP MySQL module is installed and enabled.
  - the database is running.
  - the credentials in config.php are valid.
```

Do you know where in the code, a script is trying to connect to mysql ?
My credentials are valid (used mysql -u xxx -p command), the modules are enabled (not sure if it's mysqli or pdo_mysql but both are enabled) and the database is running. The socket path is correct.

**Comment by netniV** [comment]
Hmm, did you get any warnings in the error log or php logs?  Something strange is happening with your system.  Maybe you can add a `cacti_log()` with to record the output of the php call made within utilities.

**Comment by mikygee** [comment]
Please explain me where I should add this instruction ?
In cli_check.php, at the begining of the script ?

**Comment by netniV** [comment]
No, in the utility.php that calls it.  Verify that the output coming back is clean json.

**Comment by mikygee** [comment]
Hello,
Where exactly in utility.php should I add cacti_log();
In the begining ?

**Comment by TheWitness** [comment]
Anything going on with this one @netniV or @mikygee ?

**Comment by netniV** [comment]
Sorry, I missed the reply, I'll have to make a diff file for the utility.php from the 1.2.14 release (though I don't think the 1.2.15 one has changed)

**Comment by netniV** [comment]
```diff
diff --git a/lib/utility.php b/lib/utility.php
index b7d460b42..65c353e11 100644
--- a/lib/utility.php
+++ b/lib/utility.php
@@ -1429,6 +1429,8 @@ function utility_php_recommends() {
        utility_php_verify_recommends($ext['web'], 'web');
        utility_php_set_recommends_text($ext);

+       cacti_log("UTILITY RECOMMENDS: $json");
+
        return $ext;
 }
```

**Comment by TheWitness** [comment]
I've done a quick fix to handle at least the error.  However, the underlying issue remains.  So, can you guys open another ticket with the root cause of the path issue?
