### ISSUE TITLE
"Error: Save Failed" in Cacti Version 0.8.8f.

### ISSUE THREAD

**Issue by cutehameed** [Cacti/cacti#3757]
Hi, i am getting "Error: Save Failed" in Cacti Version 0.8.8f while adding new devices.  I had previously added devices previously and after installing some plugins i am getting this error. I have tried disable/delete all plugins but still getting this error.

**Comment by netniV** [comment]
We do not support that version of Cacti and haven't for a few years.  You may ask on our community forum https://forums.cacit.net and other 0.8.8 users may help out.  There can be a number of reasons you are getting the failure:

- bad plugin
- missing table fields
- extra table fields

You will have to do some self diagnostics unfortunately.
