### ISSUE TITLE
Cacti V1.2.12 Devices showing blank after deleteing and Poller sync

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3760]
Hey Guys!

I had reported this issue before but couldn't reproduce  

![image](https://user-images.githubusercontent.com/13388748/90554191-80f87580-e163-11ea-8cf5-76bc2ba84c22.png)

I found the steps to reproduce

1.) Delete a device 
2.) Re-sync pollers 
3.) Device graphs,DS and other entries seem to be gone expect you see the exact amount devices you deleted but you will see a blank entry 

if you select the empty entries again and delete they will be gone

**Comment by TheWitness** [comment]
Dont' think it's related.

**Comment by TheWitness** [comment]
This is as seen from the central server right?

**Comment by TheWitness** [comment]
Does it show up before you sync too?

**Comment by bmfmancini** [comment]
This is seen as the main server correct
The entries don't show up before to sync

**Comment by TheWitness** [comment]
If you don't do a sync, does the problem correct itself after an hour?  Can you test that case?

**Comment by bmfmancini** [comment]
The issues is not present unless you do a sync

So do you want me to do the sync as allow one hour for the entries to
disappear ?

**Comment by TheWitness** [comment]
Delete something, wait an hour, and then sync.

**Comment by TheWitness** [comment]
I'm going to make a small change to the replicate function here shortly.  So, after I make the change, you should not have to wait.

**Comment by TheWitness** [comment]
Okay, commit is in the 1.2.x branch now.

**Comment by TheWitness** [comment]
I'm closing due to lack of feedback on this one Sean.
