### ISSUE TITLE
Cacti V1.2.12   backtraces when deleting devices 

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3761]
Hey Guys 

Saw this error pop up when deleting devices 
```
2020/08/18 04:43:26 - CMDPHP PHP ERROR NOTICE Backtrace: (/poller_commands.php[144]:run_data_query(), /lib/data_query.php[394]:data_query_remove_disabled_items(), /lib/data_query.php[438]:CactiErrorHandler())
2020/08/18 04:43:26 - ERROR PHP NOTICE: Array to string conversion in file: /var/www/html/cacti/lib/data_query.php on line: 438
```

Not sure if this is related to 
https://github.com/Cacti/cacti/issues/3760  or https://github.com/Cacti/plugin_monitor/issues/132

**Comment by TheWitness** [comment]
I'm back for a day anyway.  Very busy.  Just doing a bug run.  Thanks @bmfmancini for reporting!
