### ISSUE TITLE
cacti 1.2.13 tree view problem

### ISSUE THREAD

**Issue by samohsin** [Cacti/cacti#3762]
# Describe the bug
I need help on cacti ver 1.2.13. I have several graphs in a tree. When i select tree mode & click on a specific tree, there are about 15 graphs in that one. I can view all the graphs in a preview mode. When the mouse cursor is on any graph, & i click on a particular graph it just zooms the graphs rather than opening the graph which was so in cacti 0.8.8b. I have to click on time view graph on the right side of each graph to view. I do not want this. I want the time view graph to be activated when i click the graph in the tree.what is the solution to this issue.

**Comment by TheWitness** [comment]
This behavior has changed.  You can use the icon on the right with the horizontal bars, or right click and select 'View Graph'.

**Comment by TheWitness** [comment]
We have had reports of this from time to time, but the resolution is settled.
