### ISSUE TITLE
Suggested values on Data Queries with multiple data templates gives error

### ISSUE THREAD

**Issue by georgetasioulis** [Cacti/cacti#3764]
On a Data Query with more than one pair (in/out) of data sources, for example when monitoring traffic and unicast packets in a single graph, adding suggested values for the second set of data sources throws an error:

> Suggested Value was not entered. Please enter a suggested value and try again.

## To Reproduce

On a data query with at least two data templates (ie traffic and unicast packets) add a field name and suggested value for the second data template.

## Expected behavior

Being able to add suggested values for the second data template

## Screenshots

![GIF1](https://p195.p4.n0.cdn.getcloudapp.com/items/o0u86AyO/Screen%20Recording%202020-08-20%20at%2002.27.27%20AM.gif)

## Desktop

- OS: MacOS Catalina
- Browser: Chrome
- Version: 84.0.4147.125

## Cacti 
- Version: 1.2.13

**Comment by TheWitness** [comment]
Oh, that's interesting.  I've never really tried that before.  Wondering if you can really create graph's that way.  Have you confirmed that it otherwise workse?

**Comment by TheWitness** [comment]
Just looked at the code.  Taking a look at it.

**Comment by TheWitness** [comment]
Old nasty code.  Glad it's fixed.

**Comment by TheWitness** [comment]
Okay, this is fixed in the 1.2.x branch.
