### ISSUE TITLE
Installation - Required PHP modules

### ISSUE THREAD

**Issue by hnlgdxsj** [Cacti/cacti#3765]
Hi,
I have a problem with php check during installation process.
my environment is centos8 , nginx is nginx/1.18.0, php is PHP 7.4.9 (cli) . cacti version is 
1.2.14. the php-fpm -m is reports correctly:
[root@localhost ~]# php-fpm -m
[PHP Modules]
bcmath
cgi-fcgi
Core
ctype
curl
date
dom
fileinfo
filter
gd
gettext
gmp
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
standard
sysvsem
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
xsl
zlib

[Zend Modules]

But the installtion shows me "cli - no" for all php modules.
![image](https://user-images.githubusercontent.com/33644309/90703538-a353d580-e2c0-11ea-8410-e116ea2b091a.png)

I can't find where's the problem, I'm not a PHP expert, is there any missing configuration?

Thanks

**Comment by bmfmancini** [comment]
A couple of basic checks

1.) Try to restart ngix 
```
nginx -s reload 
```

Or 
```
systemctl restart ngix
```

else it seems to be your php-fpm setup on ngix check this out for more help to setup properly 
https://www.linode.com/docs/web-servers/nginx/serve-php-php-fpm-and-nginx/

**Comment by hnlgdxsj** [comment]
I also installed zabbix server on this centos8, it works ok. so i think the LNMP(centos8, nginx, php-fpm, mysql) environment works ok.

**Comment by cigamit** [comment]
Installing such a bleeding edge release of PHP is always bound to cause issues (7.4.9 was released 06 Aug 2020).  
I would try this

> dnf install mlocate
> updatedb
> locate php.ini

Some installs of PHP have separate INI files for PHP-FPM vs PHP-CLI.

**Comment by hnlgdxsj** [comment]
> Installing such a bleeding edge release of PHP is always bound to cause issues (7.4.9 was released 06 Aug 2020).
> I would try this
> 
> > dnf install mlocate
> > updatedb
> > locate php.ini
> 
> Some installs of PHP have separate INI files for PHP-FPM vs PHP-CLI.

thank you. it reports blow:
[root@localhost ~]# locate php.ini
/usr/local/php/etc/php.ini
/usr/local/src/php-7.4.9/php.ini-development
/usr/local/src/php-7.4.9/php.ini-production

**Comment by hnlgdxsj** [comment]
hi all,
i have soved this problem using this:

mysql>use cacti;

insert into settings
(name, value) 
values
("path_php_binary", "/usr/local/php/bin/php")

restart mysqld and nginx , now it is  ok
![image](https://user-images.githubusercontent.com/33644309/90736503-67406500-e300-11ea-9b39-e4e1cdb50490.png)

**Comment by TheWitness** [comment]
We have another feature request to either hard code or use what's in the path.  So, I think we can close this one.
