### ISSUE TITLE
Bulk  Export / Import Templates from Front-end

### ISSUE THREAD

**Issue by zuka1337** [Cacti/cacti#3766]
# Feature Request

Is possible to bulk export Devices templates, Graphs Templates, Datas Templates and Data Querys all at once?
Is possible to bulk  import Devices templates, Graphs Templates, Datas Templates and Data Querys all at once

## Is your feature request related to a problem? Please describe

I have thousands of Templates and do it one by one is painless..
Also if I export the tables in to the mysql it becomes very slow..

## Describe the solution you'd like

Export/Import full Devices templates or any other templates.

## Describe alternatives you've considered

A clear and concise description of any alternative solutions or features you've
considered.

**Comment by TheWitness** [comment]
This will be released as a part of out packaging plugin post the 1.2.23 release.  It will be offered as a plugin.
