### ISSUE TITLE
Fields not translated when using other language than english

### ISSUE THREAD

**Issue by mikygee** [Cacti/cacti#3774]
Version: 1.2.14

In Configuration > Paramètres
Many fields do not appear translated: Language Support, Auto Language Detection...

![C1](https://user-images.githubusercontent.com/2222550/91506482-7449ef00-e8d2-11ea-858e-6989bc3dfb59.PNG)

But are translated in fr-FR.po

#: include/global_settings.php:374
#, fuzzy
msgid "Auto Language Detection"
msgstr "D\xc3\xa9tection automatique de la langue"

**Comment by TheWitness** [comment]
The way it works is you verify the string as a French man/woman, and if you are good with it.  Remove the "#, fuzzy", then recompile the po file into a pot file using the ./build_gettext.sh.

Once your translation is complete, open a pull request with the changes.
