### ISSUE TITLE
Search field strange behavior when hitting enter in 1.2.14

### ISSUE THREAD

**Issue by barreljan** [Cacti/cacti#3775]
# Describe the bug

When you log in to Cacti, and go in the three mode and click on any device, then search a specific string it all works fine. If you open the console, hit for instance the Management and Graphs button, return to the Graphs (top tab) and do a search in the same host, again with the same in the search field and hitting 'enter' you end up with the page from console. If you click on the Go button this behavior is not observed.

## To Reproduce

1. Go to tab Graphs

2. Click on a host in the tree

3. Enter a string in the search field en hit 'enter' (do not click on go)

4. Go to tab Console

5. Click on Management and then Graphs (or any item, e.g. System Utilities and the View User Log)

6. Go to tab Graphs

7. Enter a string in the seach field and hit 'enter' (do not click on go)

8. Page of the last visited item under tab Console shows up

## Expected behavior

When hitting enter, just as clicking on the Go button, a list of graphs matching the search string.

- OS: Windows 10

- Browser: Edge Chromium, FireFox, IE11

- Cacti Version: 1.2.14
- Server running Centos7 (latest updates). Apache 2.4, PHP 7.4.9

Workaround for now:
Log out, log back in, search again. Any time you click on something within the Console tab, you end up with this. Unless you hit the Go button of course.

**Comment by TheWitness** [comment]
Thanks for logging this.  This has been an annoyance for some time.  Makes sense to make a light modification.

**Comment by TheWitness** [comment]
Interesting.  Have not tested in a while, and I'm getting this too.  Seems my database default collation is not right.

![image](https://user-images.githubusercontent.com/1439914/91662611-8635b880-eab1-11ea-8ec9-0df614592d41.png)

**Comment by TheWitness** [comment]
Testing after this:

```sql
alter database cacti collate utf8mb4_unicode_ci character set utf8mb4;
```
