### ISSUE TITLE
Export DataQuery show PHP Error: ERROR PHP NOTICE: Undefined index: fname

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#3778]
# Describe the bug
Export DataQuery show PHP Error: ERROR PHP NOTICE: Undefined index: fname in file: /var/www/html/cacti/lib/export.php on line: 346 
CMDPHP PHP ERROR NOTICE Backtrace: (/templates_export.php[33]:form_save(), /templates_export.php[58]:get_item_xml(), /lib/export.php[1102]:data_input_method_to_xml(), /lib/export.php[346]:CactiErrorHandler()) 

## To Reproduce

1. Go to Console->Import/Export-->Export Templates

2. Select "What would you like to export?"-->Data Query

3. Select "Device Template to Export"--> Any Data Query

4. Enable "Include Dependencies"

5. Select "Output Format" --> "Save File Locally"

6. Click "Export"

7. Check "Logs" tab

8. See Error

**Comment by TheWitness** [comment]
Nice catch @ddb4github.  That's for the QA.
