### ISSUE TITLE
CMDPHP PHP ERROR Backtrace: (/poller.php[696]:process_poller_output()

### ISSUE THREAD

**Issue by d-mihaylenko** [Cacti/cacti#3779]
Go to logs on version 1.2.14
<img width="1440" alt="Screenshot 2020-08-31 at 18 51 54" src="https://user-images.githubusercontent.com/17220673/91741560-90dd7400-ebbd-11ea-9556-7ee6bdcf619b.png">

My version PHP 7.4.9-1+0~20200807.24+debian9~1.gbp7962cd

**Comment by bmfmancini** [comment]
I believe this should go on the THOLD tracker 
What version of thold do you have on your install?

**Comment by d-mihaylenko** [comment]
THOLD is 1.3.2

**Comment by bmfmancini** [comment]
Update to 1.2.4 which has a bunch of fixes

**Comment by d-mihaylenko** [comment]
Thanks, its help
