### ISSUE TITLE
Cacti V1.2.12 remove_device.php removes multiple devices with similar name 

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3782]
Hey Guys 

I came across the following issue 

When using the remove_device.php CLI script if you remove a device by name in my case test the script comes back with multiple results and goes on the delete the results see below

php remove_device.php --description=test
PHP Notice:  Undefined variable: debug in /var/www/html/cacti/cli/remove_device.php on line 106
      id |                           host |                    description
     276 |                     IP |                           test
     277 |                     IP |                         test10

Removing devices with ids: 276, 277
Success - removed device-ids: 276, 277

Now test and test10 did have the same IP but I wouldn't think that would be a factor since we are doing a check based on the description 

I also got the following backtrace in the log 

2020-09-01 14:54:27 - CMDPHP PHP ERROR NOTICE Backtrace: (/cli/remove_device.php[106]:CactiErrorHandler())
2020-09-01 14:54:27 - ERROR PHP NOTICE: Undefined variable: debug in file: /var/www/html/cacti/cli/remove_device.php on line: 106

I am going to test this on 1.2.14 but based on the commit history on this script I believe it will be the same result

**Comment by bmfmancini** [comment]
ok so in 1.2.14 bit of a different issue 

I have these 3 devices 

![image](https://user-images.githubusercontent.com/13388748/91895215-dd2fbf00-ec64-11ea-82d7-7539c27dbfe5.png)


When I run the cli script 

By description 

root@cact1:/var/www/html/cacti/cli# php remove_device.php --description=test1
PHP Notice:  Undefined variable: debug in /var/www/html/cacti/cli/remove_device.php on line 106
ERROR: Unable to find host in the database matching desciption (test1)
root@cact1:/var/www/html/cacti/cli#


By ip 

root@cact1:/var/www/html/cacti/cli# php remove_device.php --ip=1.1.1.1
PHP Notice:  Undefined variable: debug in /var/www/html/cacti/cli/remove_device.php on line 118
      id |                           host |                    description
      23 |                        1.1.1.1 |                         test10

Please use --confirm to remove these devices
root@cact1:/var/www/html/cacti/cli#


MariaDB [cacti]> select description,hostname,id  from host where description LIKE 'test%';
+-------------+----------+----+
| description | hostname | id |
+-------------+----------+----+
| test1       | 1.1.1.1  | 21 |
| test2       | 1.1.1.1  | 22 |
| test10      | 1.1.1.1  | 23 |
+-------------+----------+----+
3 rows in set (0.01 sec)

3 rows in set (0.00 sec)

MariaDB [cacti]>

**Comment by bmfmancini** [comment]
Same error occurred as well

2020/09/01 15:08:09 - CMDPHP PHP ERROR NOTICE Backtrace:  (/cli/remove_device.php[118]:CactiErrorHandler())
2020/09/01 15:08:09 - ERROR PHP NOTICE: Undefined variable: debug in  file: /var/www/html/cacti/cli/remove_device.php  on line: 118

**Comment by bmfmancini** [comment]
No change between 1.2.12 release and 1.2.14

root@cact1:~/cacti-release-1.2.12/cli# diff remove_device.php /var/www/html/cacti/cli/remove_device.php
root@cact1:~/cacti-release-1.2.12/cli#
root@cact1:~/cacti-release-1.2.12/cli# md5sum remove_device.php
73183f208dbdcd65d957560c15c49da0  remove_device.php
root@cact1:~/cacti-release-1.2.12/cli# md5sum /var/www/html/cacti/cli/remove_device.php
73183f208dbdcd65d957560c15c49da0  /var/www/html/cacti/cli/remove_device.php
root@cact1:~/cacti-release-1.2.12/cli#

root@cact1:~/cacti-release-1.2.12/cli# cat /var/www/html/cacti/include/cacti_version
1.2.14
root@cact1:~/cacti-release-1.2.12/cli#

**Comment by bmfmancini** [comment]
Here is the relevant code 

```
/* process host description */
        if ($description > '') {
                if ($debug) {
                        print "Searching hosts by description...\n";
                }

```

**Comment by bmfmancini** [comment]
Need to change 

```
if (cacti_sizeof($parms)) {
        /* setup defaults */
        $description   = '';
        $ip            = '';
        $host_id       = '';
        $quietMode     = false;
        $confirm       = false;
        $quiet         = false;
```

to 

```
if (cacti_sizeof($parms)) {
        /* setup defaults */
        $description   = '';
        $ip            = '';
        $host_id       = '';
        $debug         = false;
        $quietMode     = false;
        $confirm       = false;
        $quiet         = false;
```

that fixes the error but not the device search

**Comment by bmfmancini** [comment]
OK found the issue 

If you have a device that is set to template none this script fails 

See below 
test 2 and test 10 are set to host_template_id 0 which is none
test 1 has now been set to cisco router 

MariaDB [cacti]> select hostname,description,host_template_id from host where description  LIKE 'test%';
+----------+-------------+------------------+
| hostname | description | host_template_id |
+----------+-------------+------------------+
| 1.1.1.1  | test1       |                1 |
| 1.1.1.1  | test2       |                0 |
| 1.1.1.1  | test10      |                0 |
+----------+-------------+------------------+
3 rows in set (0.00 sec)

MariaDB [cacti]>

See result now 

root@cact1:/var/www/html/cacti/cli# php remove_device.php --description=test
      id |                           host |                    description
      21 |                        1.1.1.1 |                          test1

Please use --confirm to remove these devices

After changing all of the devices to have a template 

MariaDB [cacti]> select hostname,description,host_template_id from host where description  LIKE 'test%';
+----------+-------------+------------------+
| hostname | description | host_template_id |
+----------+-------------+------------------+
| 1.1.1.1  | test1       |                1 |
| 1.1.1.1  | test2       |                1 |
| 1.1.1.1  | test10      |                1 |
+----------+-------------+------------------+
3 rows in set (0.00 sec)

MariaDB [cacti]>


root@cact1:/var/www/html/cacti/cli# php remove_device.php --description=test
      id |                           host |                    description
      21 |                        1.1.1.1 |                          test1
      23 |                        1.1.1.1 |                         test10
      22 |                        1.1.1.1 |                          test2

Please use --confirm to remove these devices
root@cact1:/var/www/html/cacti/cli#

**Comment by bmfmancini** [comment]
no it appears that the script is performing alike search instead of a equals to search which in my mind should not be the way because you are entering a specific hostname so cacti should be looking for that specific hostname

**Comment by TheWitness** [comment]
I closed the pull request.  You opened it on the develop branch and should have on the 1.2.x branch.

**Comment by netniV** [comment]
I've applied the debug fix.
