### ISSUE TITLE
Add SHA256 and AES256 for snmp polling

### ISSUE THREAD

**Issue by mikygee** [Cacti/cacti#3787]
Hello,
At the moment only SHA128 and AES128 are supported.
Many devices now support AES256 and SHA256, they should be also used.
Regards

Additional informations
http://www.net-snmp.org/wiki/index.php/Strong_Authentication_or_Encryption

**Comment by netniV** [comment]
Unfortunately, this is one where as much as we really want this ourselves, we are reliant on the libraries out there and I don't believe that NetSNMP fully support it last I heard.  @cigamit or @TheWitness may correct me on that as they follow them a lot better than I do.

**Comment by bmfmancini** [comment]
@netniV 

Actually I think as of 5.8 it does 

Question: Authentication

Does it support anything stronger than SHA1?
Answer

Yes. Net-SNMP 5.8 and later support all the authentication protocols defined in [RFC7860|https://tools.ietf.org/html/rfc7860], w hich are:

    SHA-192
    SHA-256
    SHA-284
    SHA-512

Question: Encryption

Does Net-SNMP support AES192 or AES256?
Answer

The short answer is Yes, starting with release 5.8 AES193 and AES256 are an optional configure option.

There are two separate parts to the long answer: 

source:http://www.net-snmp.org/wiki/index.php/Strong_Authentication_or_Encryption

**Comment by TheWitness** [comment]
Yea, it's supported in the SNMP library for now.  We were holding off on this till 1.3.  Been really busy though.  It's a small project, but involves both Cacti and Spine.

**Comment by TheWitness** [comment]
Interesting that there is a full php implementation of SNMP that covers this, which is pretty cool.

https://github.com/Cacti/cacti/issues/3818
