### ISSUE TITLE
Error Upgrading Cacti from Pre 1.x from Recent MariaDB version

### ISSUE THREAD

**Issue by SaleSmart** [Cacti/cacti#3790]
Hi,
I installed Cacti 1.2.10 on Ubuntu 20.0.4., and imported old Cacti (0.8f) database dump. Upgrade failed, there is an error only one line:
UPDATE cdef SET system=1 WHERE name LIKE '\_%'         Fail
What can I do to solve this issue?
Thanks in advance!

**Comment by TheWitness** [comment]
What version of MariaDB?

**Comment by TheWitness** [comment]
Okay, update the one modified file and try again.  I'm pretty sure that "system" is now a reserved word in a modern MariDB/MySQL

**Comment by TheWitness** [comment]
Yea, confirmed it was handled in other places.  That fix should do you right.
