### ISSUE TITLE
The default display is incomplete this month?

### ISSUE THREAD

**Issue by balainit** [Cacti/cacti#3795]
Hi, everybody

Recently found that the default display data for this month is incomplete

 Did not make any adjustments, this happened suddenly in the last month

Does anyone know what the problem is ?

 Cacti  version  0.8.8.x

 OS     version  CentOS 7.x
 

### Full display of this month's data graph

![QQ截图20200911091314](https://user-images.githubusercontent.com/31933126/92836515-13accd00-f40f-11ea-97bd-ae3c9c8072f3.png)

### Incomplete data graph for this month

![QQ截图20200908101347](https://user-images.githubusercontent.com/31933126/92426269-1794e100-f1bc-11ea-9e71-e18b7c7941ed.png)

**Comment by netniV** [comment]
You are likely hitting the 32-bit barrier and there isn't much you can do about it unless you upgrade to a new OS and the latest version of cacti.

**Comment by balainit** [comment]
@netniV 
Thanks for receiving your reply, my OS is 64-bit 
   
64-bit capture used by cacti

I’ve been doing well before, but this problem happened recently, I don’t know what to do? Can you help me? 
thank you very much

**Comment by netniV** [comment]
Your OS might be 64-bit, but I doubt your PHP/Cacti versions are given the age of them.

**Comment by balainit** [comment]
@netniV
 
Php Version  5.4.x

Cacti Version  0.8.8h

It’s been used this way all the time, this problem suddenly appeared

**Comment by netniV** [comment]
Like I said it's a 32 bit problem.

**Comment by balainit** [comment]
@netniV 
All versions are 64-bit, and they have always been good before. This problem suddenly appears, shouldn't it be a version problem? Can I only upgrade to the latest version?

**Comment by cigamit** [comment]
The 0.8.8 branch is deprecated and unsupported.  If you need help with it, you will need to ask in the forums.  The issue tracker is for issues with the current code base.

**Comment by netniV** [comment]
@balainit if they are 64-bit versions, there is a change that has been applied by many 0.8.x users in the last week on another issue tracker here.  As @cigamit said, we don't support that version so the fix has pretty much been to take what I did originally in 1.2.x for this and work out where to apply it to their local versions.  

We won't be directly supplying or supporting the fix.

**Comment by balainit** [comment]
@cigamit @netniV 

Thank you very much, reference #3798  has been resolved
