### ISSUE TITLE
in Real Time graphing the Thumbnails is a nu-sense 

### ISSUE THREAD

**Issue by majed17** [Cacti/cacti#3796]
Peace, there must be an option to whether the Thumbnails option would appear in the first place, because below 60%, the browser doesn't shrink the window anymore

**Comment by netniV** [comment]
Can you provide a visual example of what you mean?

**Comment by majed17** [comment]
just open a real time graph with a browser configured to reopen saved sites, and select 50%, and reboot

**Comment by TheWitness** [comment]
@majed17, hopefully, providing what @netniV asked for it not too difficult for you.

**Comment by majed17** [comment]
![After-Restart-Redacted](https://user-images.githubusercontent.com/35138065/93062300-72777e00-f67d-11ea-9223-d37c06b491f1.png)
![original-redacted](https://user-images.githubusercontent.com/35138065/93062338-7c997c80-f67d-11ea-9da0-3a736a83ae23.jpg)

**Comment by majed17** [comment]
![original-redacted](https://user-images.githubusercontent.com/35138065/93062520-b5d1ec80-f67d-11ea-869e-a9897a2b94a1.jpg)
![After-Restart-Redacted](https://user-images.githubusercontent.com/35138065/93062533-b9657380-f67d-11ea-97e6-1d79bedd2baf.png)

**Comment by TheWitness** [comment]
I was testing this in 1.2.15 and in that version, every change you make to the popout is immediately saved into your profile, so long as you have profile access.

**Comment by majed17** [comment]
if yes, then i will be more than thankful... i.e. expect a monetary..... prize! ;)

**Comment by TheWitness** [comment]
This is working as advertising.  So, I'm going to close.

**Comment by majed17** [comment]
sorry man, yesterday i upgraded, and early in the morning nothing new started...

**Comment by majed17** [comment]
in1.2.16, the same

**Comment by majed17** [comment]
worth mentioning, it works as you stated on a windows machine..but with linux i am suffering...

**Comment by majed17** [comment]
it seems to be related to firefox on linux.. seems like a mozilla forum topic..

**Comment by TheWitness** [comment]
Well, since it's a JavaScript change to include/realtime.js, you have to either clear your cache, or somehow force the new realtime.js to load.  Its a big pain in the you know what.  We've tried to defeat the aggressive caching that the browsers have been doing more and more over the years, but they continue to make it difficult to 'refresh' things.

So, download the realtime.js from the 1.2.x branch, then you can browse to it http://yoursite/cacti/include/realtime.js, then once it's loaded, hit F5 (refresh) and that should force a cache reload.  After that realtime should never pass a null size variable again.

**Comment by majed17** [comment]
well there is that i rarely clear the cache on version upgrades, but this time, just for you, i did..and downloaded the js file and placed it in the include directory on the server and pointed to the webpage you mentioned, but it just displays the code of the file. i did file a bug with firefox anyway..or any more hints?

**Comment by TheWitness** [comment]
Let me try it on Linux.  What FF version?

**Comment by TheWitness** [comment]
I just pushed a new graph_realtime.php and realtime.js into Github 1.2.x branch.  Test with that.  If that does not fix it, I give up.

**Comment by majed17** [comment]
firefox 84, cacti 1.2.16 with dark theme..the day is almost over, i'll test later, God willing...

**Comment by majed17** [comment]
tried to exit firefox before replacing the files..the windows closed but a firefox, what's it called, tab in the task bar remained, and the other tabs hanged. only pressing the start menu works to log out and back in..anyway after replacing the the 2 files (graph_realtime.php) & (realtime.js) ... and nothing new..i was thinking if it is .js..then it has to do something with java..might it be caused by my 32-bit java verison installed manually on linux (for asdm to wok)?
