### ISSUE TITLE
Time presets

### ISSUE THREAD

**Issue by Izmenoff** [Cacti/cacti#3797]
Cacti 1.2.8
Centos7
PHP 7.3.22
MariaDB 10.2.33

Time presets doesn't work for (last 2 hour, last hour, last half hour), 4 hour and more works fine

![image](https://user-images.githubusercontent.com/17400240/93021449-372c6f00-f5eb-11ea-9484-7e89e8287e8f.png)

**Comment by TheWitness** [comment]
Anything in the log?

**Comment by Izmenoff** [comment]
nothing

**Comment by TheWitness** [comment]
So, bring up the browsers debug window, and goto the network tab, then, change the timespan selector and graph the 'graph_json.php' request variables and pass them along.  I would like to see what was passed to 'graph_view.php' too.  Screen shot's will help, I would like to see what was passed to the backend.

**Comment by Izmenoff** [comment]
![image](https://user-images.githubusercontent.com/17400240/93023538-5c73aa00-f5f8-11ea-8741-3b67968831f3.png)
![image](https://user-images.githubusercontent.com/17400240/93023561-81681d00-f5f8-11ea-8fe5-ab675ff7996d.png)

**Comment by TheWitness** [comment]
You need to goto the "headers" and then post the values for the Request Variables.

**Comment by budiroots** [comment]
same problem here... :(

**Comment by Izmenoff** [comment]
![image](https://user-images.githubusercontent.com/17400240/93046125-bb213e00-f661-11ea-928a-9883e08fc21e.png)
![image](https://user-images.githubusercontent.com/17400240/93046207-e9068280-f661-11ea-959e-a57c19d663d7.png)

**Comment by Izmenoff** [comment]
![image](https://user-images.githubusercontent.com/17400240/93046335-3551c280-f662-11ea-93e6-06e4beb183fc.png)
![image](https://user-images.githubusercontent.com/17400240/93046371-4ac6ec80-f662-11ea-98d9-ba6bee09fc86.png)

**Comment by toobadsosad** [comment]
same here cannot use preset lower than LAST DAY... weirdly this also happen to my other cacti installation suddenly 0.8.8h, 1.1.16, and 2.1.16... 

is there any external resource that may impact this??

**Comment by Izmenoff** [comment]
Guys, I solved the problem to install new cacti & spine 1.2.14

**Comment by toobadsosad** [comment]
Hmm.. quick fix for older cacti at lease working in my 1.2.6..
(but i do not know what this "dirty fix" will create regression bug)
will still looking forward for official suggestion.

in graph_image.php and graph_json.php change the 1600000000 to 2600000000

```
$graph_data_array = array();

/* override: graph start time (unix time) */
if (!isempty_request_var('graph_start') && get_request_var('graph_start') < 2600000000) {
        $graph_data_array['graph_start'] = get_request_var('graph_start');
}

/* override: graph end time (unix time) */
if (!isempty_request_var('graph_end') && get_request_var('graph_end') < 2600000000) {
        $graph_data_array['graph_end'] = get_request_var('graph_end');
}
```

**Comment by toobadsosad** [comment]
> Hmm.. quick fix for older cacti at lease working in my 1.2.6..
> (but i do not know what this "dirty fix" will create regression bug)
> will still looking forward for official suggestion.
> 
> in graph_image.php and graph_json.php change the 1600000000 to 2600000000
> 
> ```
> 
> /* override: graph start time (unix time) */
> if (!isempty_request_var('graph_start') && get_request_var('graph_start') < 2600000000) {
>         $graph_data_array['graph_start'] = get_request_var('graph_start');
> }
> 
> /* override: graph end time (unix time) */
> if (!isempty_request_var('graph_end') && get_request_var('graph_end') < 2600000000) {
>         $graph_data_array['graph_end'] = get_request_var('graph_end');
> }
> ```

in latest cacti version, those 1600000000 value already replaced with FILTER_VALIDATE_MAX_DATE_AS_INT

**Comment by hero1c** [comment]
@toobadsosad fix worked for me. I don't know why but it did. I backed up the old json file in case things got messy.

Awaiting officail fix.

**Comment by toobadsosad** [comment]
> @toobadsosad fix worked for me. I don't know why but it did. I backed up the old json file in case things got messy.
> 
> Awaiting officail fix.

same here.. i backed up the original file.. and wait for official.. or at least confirmation that this fix is ok

**Comment by younity-ENG** [comment]
@toobadsosad Thanks,

fix work for me as well!!

**Comment by TheWitness** [comment]
Glad you all found it.  Thought we had fixed that some time ago, but I guess not.

**Comment by TheWitness** [comment]
Official fix is to upgrade to 1.2.10+, preferably 1.2.14.

**Comment by twkfaisal** [comment]
great... I've changed this value from 1600000000 to 2600000000 and it works.

**Comment by Talria** [comment]
Hmm. I've changed both php files from 1600000000 to 2600000000 and restarted the server, and still doesn't allow me to zoom into the graph, or see any graph in the past 4 hours. :( Anything else I can try??

![image](https://user-images.githubusercontent.com/71720855/93909780-27d5b180-fcce-11ea-83e8-ac69cc0b07c1.png)
![image](https://user-images.githubusercontent.com/71720855/93909904-53589c00-fcce-11ea-8bdb-e599c9b1938d.png)

**Comment by netniV** [comment]
You will probably be better asking for assistance on the forums for outdated versions of Cacti as other community users may have a solution for you when they experienced the issue.

We no longer support 0.8.8 or below and haven't for some time.
