### ISSUE TITLE
Graph history only for 1 one day

### ISSUE THREAD

**Issue by maxstech** [Cacti/cacti#3799]
Cacti 1.2.1
Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-43-generic x86_64)
PHP 7.0.32-0ubuntu0.16.04.1

The graph history was displayed only for 1 day. Even if I try to view the chart for a few hours, I only get the daily chart.
The problem started recently, the system worked for about 1.5 years.
How can I fix this ?

![day](https://user-images.githubusercontent.com/47040342/93077319-4cf46f80-f691-11ea-8e72-fe6b00b6b6b0.jpg)

![time graph view same grame](https://user-images.githubusercontent.com/47040342/93077328-51b92380-f691-11ea-8980-f2780ba2bc85.jpg)

**Comment by tonykiboi** [comment]
same for me
Case #3800

**Comment by maxstech** [comment]
https://github.com/Cacti/cacti/issues/3798#issuecomment-691898797

> Hmm.. quick fix for older cacti at lease working in my 1.2.6..
> (but i do not know what this "dirty fix" will create regression bug)
> will still looking forward for official suggestion.
> 
> in **graph_image.php** and **graph_json.php** change the 1600000000 to 2600000000
> 
> ```
> 
> /* override: graph start time (unix time) */
> if (!isempty_request_var('graph_start') && get_request_var('graph_start') < 2600000000) {
>         $graph_data_array['graph_start'] = get_request_var('graph_start');
> }
> 
> /* override: graph end time (unix time) */
> if (!isempty_request_var('graph_end') && get_request_var('graph_end') < 2600000000) {
>         $graph_data_array['graph_end'] = get_request_var('graph_end');
> }
> ```

I followed this solution, it helped me. I will wait for an official answer.

**Comment by TheWitness** [comment]
Correct, you need to upgrade to at least 1.2.10 to resolve this issue, you can optionally edit the following files and search for "16000" and remove the lines that lock in the date range:

graph_view.php
graph_json.php
graph_xport.php
