### ISSUE TITLE
Cacti ignores a non-standard SNMP port

### ISSUE THREAD

**Issue by FrodoTheRingWearer** [Cacti/cacti#380]
So I have a device that is running SNMP on port 3401. Anyway, so I created the device and set the port correctly, but it continually times out.

Inside of MySQL I ran:

select * from poller_item where host_id=31; (31 being the host that I just created).

Anyway, the first item listed shows the SNMP port as 161. I can confirm that Cacti is polling this device on port 161 instead of port 3401 (Packet capture shows that). This single item breaks all the graphs for this device as all of them poll on SNMP on port 161 instead of 3401. If I change the port in MySQL, it seems to fix this issue.

I've found this issue in 1.0.4 and it is reproducible .

**Comment by cigamit** [comment]
I can not reproduce this.  Please describe how you created this device and why the GUI would not work?

**Comment by FrodoTheRingWearer** [comment]
So I'm trying to pull in statistics from Squid (See http://wiki.squid-cache.org/Features/Snmp ). So I create a new device and point it to the server in question and change the SNMP port to 3401. I add the graph templates that I've attached below. Anyway, at this point I'll get errors from Cacti that the host timed out (SNMP walk works fine from the command-line though). Then if I do the above (select * from poller_item where host_id=30;), I can see that the item with the lowest local_data_id is using port 161 instead of 3401 (See the picture attached to this).

The issues are:
1) The first graph item create should not be polling on port 161
2) Just because the first graph item is polling on port 161 doesn't mean the rest should. It seems that Cacti only looks at the first item for this host and then assumes the rest of the graph items use SNMP on that same port.

I'm running:
Windows 7 Pro x64 SP1
PHP 7.1.2
MariaDB 10.1
Apache 2.4.25

Thanks!

![cacti_issue](https://cloud.githubusercontent.com/assets/26150256/23642575/3f5f08e8-02c1-11e7-8639-b53e2ed4f7dc.jpg)
[Squid.zip](https://github.com/Cacti/cacti/files/823416/Squid.zip)

**Comment by cigamit** [comment]
What Graph Template is this?  It's not standard, and the issue is likely there.  Go into the Data Template and see if it's hard coding a bad snmp_port for it.  One you fix that, you may need to re-save the host, though when modifying the Data Template, it may update the poller cache automatically.

**Comment by FrodoTheRingWearer** [comment]
The SNMP port isn't hard coded in the data template.

**Comment by cigamit** [comment]
After a cursory inspection of one of the templates, it would appear that these template have duplicated some 'system' data input methods that should not have been done.  I won't be able to give this a closer look until the weekend as my time during daylight hours is limited.  In the mean time, simply update the port number in the poller_items periodically.  This fix may take a little time.

**Comment by FrodoTheRingWearer** [comment]
I did some digging. If I run the following query:

`select dif.type_code, did.value
	FROM data_input_fields AS dif
	LEFT JOIN data_input_data AS did
	ON dif.id=did.data_input_field_id
	WHERE (type_code LIKE "snmp_%" OR type_code IN("hostname","host_id"))
	AND did.data_template_data_id =294
	AND did.value !="";
`

FYI: 294 is the "data_template_data_id" pulled from a previous query. I think this identifies information specific to this data source.

Anyway, I get the following output:
`+----------------+---------------------------+
| type_code      | value                     |
+----------------+---------------------------+
| hostname       | 10.1.1.142                |
| snmp_community | public                    |
| snmp_oid       | .1.3.6.1.4.1.3495.1.3.1.7 |
| snmp_version   | 2                         |
+----------------+---------------------------+`

It looks as if this may be an issue with the template as it never wrote an SNMP port to the database. However, there is still the bug of Cacti polling every data source for this host on port 161.

**Comment by FrodoTheRingWearer** [comment]
So after reviewing the cmd.php it looks as if it was written in such a way that you cannot have a single host that uses the same version of SNMP on a different port. This is because when cmd.php connect to the host it creates a session. It uses the host_id and the SNMP version number to identify this session. So in my case above, it creates the first session with port 161, then tries to reuse it with the next polling items that are supposed to be using port 3401.

To fix this, we'd need to change all instances (Lines 93,94,99,100,484,485,532,533,637,638) of the text:

$sessions[$host_id . '_' . $item['snmp_version'] to:

$sessions[$host_id . '_' . $item['snmp_version'] . '_' . $item['snmp_port']

I'm still looking into the issue mentioned in the post just before this, but that code is a lot more complex.

**Comment by FrodoTheRingWearer** [comment]
I definitely think this is an issue with the Cache Objects template. It looks like it never pulls in the SNMP Port field from the template because the SNMP Port is not listed under the "items" for the Squid - Cache Object data source.

I think it would make more sense if Cacti would default to the SNMP port that is used for the Device rather than the default SNMP port. I would understand if you didn't classify this specific issue as a bug.

**Comment by cigamit** [comment]
Can you please goto Data Input Methods and search for SNMP.  From there, put a screen shot of the Data Input Methods here.

Thanks!

**Comment by cigamit** [comment]
This is resolved now.  The ping method should be None for squid.  The SNMP Getnext did not work as expected since the Agent is looking for a System MIB which does not exist for Squid.  They should have wrote this as an SNMP Agent extension instead of it's own MIB.
