### ISSUE TITLE
ALL Graphs only display daily Average

### ISSUE THREAD

**Issue by tonykiboi** [Cacti/cacti#3800]
CENTOS7
CACTI Version 1.2.2

All graphs display the daily average even for weekly, monthly and yearly 

![2020-09-14_13-48-16](https://user-images.githubusercontent.com/71262343/93077584-af4d7000-f691-11ea-959f-359c4407e054.jpg)

**Comment by tonykiboi** [comment]
Data Source Profile screenshot

![image](https://user-images.githubusercontent.com/71262343/93078747-b2e1f680-f693-11ea-98b1-193146d5e9e0.png)

**Comment by zfon** [comment]
Hi,

we have the same issue on two different Cacti 1.2.2, no configuration changes as far as I know. Its happening since the 11th; We have other two Cacti 0.8.8h that seem to work fine.

Thanks and kind regards

**Comment by TheWitness** [comment]
You need to upgrade to at least 1.2.10 to resolve this issue, you can optionally edit the following files and search for "16000" and remove the lines that lock in the date range:

graph_view.php
graph_json.php
graph_xport.php

**Comment by zfon** [comment]
Upgraded to 1.2.14 via Buster backports, seems to fix the issue.
I had to logout and log in again, was having the followinh php error:

`+15/09/2020 08:37:50 - CMDPHP Validation Error, Variable:thumbnails, Value:on Backtrace:  (/graph_view.php[221]:top_graph_header(), /lib/functions.php[3287]:include_once(), /include/top_graph_header.php[55]:grow_dhtml_trees(), /lib/htm
l_tree.php[95]:html_validate_tree_vars(), /lib/html_tree.php[855]:validate_store_request_vars(), /lib/html_utility.php[702]:die_html_input_error(), /lib/html_validate.php[64]:cacti_debug_backtrace())`

Login out solved it.

**Comment by TheWitness** [comment]
Ah, you must have somehow send that through a post due to some JavaScript error.  Good to know.  Can you report that as a separate issue though?

**Comment by zfon** [comment]
I can't reproduce it anymore, now it works perfectly. I just wanted to document it, thanks.
Sometimes after an upgrade the tree tab doesn't work for some users, login out and/or deleting cookies solve it.

**Comment by TheWitness** [comment]
Cool.  Thanks!
