### ISSUE TITLE
Cacti. Hourly graph filters not working while day filter working fine

### ISSUE THREAD

**Issue by SohaibAs1** [Cacti/cacti#3804]
I am using cacti Ezi 0.8 
From last 2 days hourly graph filter not working and showing whole day graph while filter applied for last 2 hrs.

**Comment by cigamit** [comment]
Unsupported Cacti version, but this probably applies.
https://github.com/Cacti/cacti/issues/3797

**Comment by SohaibAs1** [comment]
Thanks for urgent response and support. Can you please suggest the stable version of cacti to update. Currently Issue fixed on temporary basis by following given thread.

**Comment by cigamit** [comment]
CactiEZ was based on Centos 6, which is also unsupported, so you are going to want to build out a new system with up to date software on it.

**Comment by SohaibAs1** [comment]
ok thanks

**Comment by TheWitness** [comment]
There is a known issue right now with the 3 following files, if you are using the old stuff (prior to 1.2.10).

graph_image.php
graph_xport.php
graph_json.php

The solution can be found in some closed GitHub tickets.  Look for that, but Jimmy is right, we are not really supporting the real old stuff.

**Comment by cominderace** [comment]
Faced the same issue today. Only Last 1 day range is displayed. Other filters have no effect.
Had not such issue a month ago. Version was the same: 1.2.7. So it is not too old from my point of view.

**Comment by cominderace** [comment]
Upgrade to Version 1.2.15 has fixed the issue.
