### ISSUE TITLE
1.2.14 Installation Wizard Loop

### ISSUE THREAD

**Issue by tonykiboi** [Cacti/cacti#3806]
Upgrade from 1.2.3 to 1.2.14

The upgrade starts and gets to 3% then loops back to the beging of the installation wizard

![image](https://user-images.githubusercontent.com/71262343/93197222-0f0c4f80-f754-11ea-8726-d5bac4d6eb8e.png)

![image](https://user-images.githubusercontent.com/71262343/93197714-a40f4880-f754-11ea-8017-bfb5f910f388.png)

**Comment by TheWitness** [comment]
Is this a large or small installation?  What is the max_execution_time variable set to in /etc/php.ini?

**Comment by TheWitness** [comment]
As a workaround, you can run the upgrade_database.php script in the cli directory.

**Comment by tonykiboi** [comment]
Database issues
innodb_io_capacity	200	>=	5000
innodb_io_capacity_max	2000 >=	10000
once I set this correctly, it worked

**Comment by netniV** [comment]
> As a workaround, you can run the upgrade_database.php script in the cli directory.

That should be a last resort, there is a command line installer that operates the same as the web based one which should really be used to obtain the same install experience.
