### ISSUE TITLE
HOST-RESOURCES-MIB::hrStorageUsed and Size "No Such Instance currently exists at this OID'"

### ISSUE THREAD

**Issue by edewillians10** [Cacti/cacti#3807]
I am with a clean Cacti default installation running and several servers are showing up these messages regarding the OID for disk Size and Used. 

Any idea how I can solve these warnings?

![image](https://user-images.githubusercontent.com/38332419/93255251-7e7f4080-f74e-11ea-8669-c981ee02a0a1.png)

**Comment by cigamit** [comment]
Have you attempted to do an SNMP Walk against the device to see if they return data?  Also you don't state Cacti version, what platform you are running from, and what type of device you are connecting to.

**Comment by edewillians10** [comment]
Sorry for the lack of information...

Cacti Version 1.2.14 server running on RHEL 7.8 
Client servers Centos7 and RHEL7.8 consuming Device Template "Net-SNMP Device" with default Graphs and Data Queries

Yes, I have tried to call the client hosts using snmpwalk :

> # snmpwalk -v 2c -c community 172.xxx.xxx.xxx 1.3.6.1.2.1.25.2.3.1.5.66
HOST-RESOURCES-MIB::hrStorageSize.66 = No Such Instance currently exists at this OID
> # snmpwalk -v 2c -c community  172.xxx.xxx.xxx1.3.6.1.2.1.25.2.3.1.6.66
HOST-RESOURCES-MIB::hrStorageUsed.66 = No Such Instance currently exists at this OID

>

**Comment by cigamit** [comment]
Ya, looks like either a misconfigured snmp on those servers.  I have both Centos7/8 and Rhel 7/8 working just fine.

You could try adding this to the /etc/snmp/snmpd.conf
`view    systemview    included   .1`

**Comment by edewillians10** [comment]
Thanks for the quickly answer I will try this

**Comment by edewillians10** [comment]
Hi @cigamit it worked smoothly ...  like a charm 

Thank you for your assistance ...

**Comment by TheWitness** [comment]
The problem is you are using and old and crappy data query to track system process cpu and memory.  That data query is a bad one, which is why I wrote the hmib plugin.  Use that plugin if you want to track that information.

**Comment by TheWitness** [comment]
Looking back, now after > 1 cup of coffee on this bright morning, and you can ignore my comments ;)  Unless of course you want to monitor such things...

**Comment by edewillians10** [comment]
I really appreciate that @TheWitness ... I have worked with HMIB before and I will do that, it makes total sense... thanks for the feedback !!!
