### ISSUE TITLE
Allow Users to Specify Alternate Sources for Content-Security Policy

### ISSUE THREAD

**Issue by arno-st** [Cacti/cacti#3808]
# Describe the bug
Using a call to an external javascript, can't be executed due to configuration of contend-security to tigth

## To Reproduce

I'm using a Mapping plugin who do a call on the following url:
https://unpkg.com/leaflet@1.6.0/dist/leaflet.css
https://unpkg.com/leaflet@1.6.0/dist/leaflet.js

it's openstreet map componnents, and it give the following error:

Content Security Policy: The page settings prevented a resource from loading at https://unpkg.com/leaflet@1.6.0/dist/leaflet.css ("style-src").
Content Security Policy: The page settings prevented a resource from loading at https://unpkg.com/leaflet@1.6.0/dist/leaflet.js ("script-src").

it's on Cacti 1.2.14 but it's like that since the dev team added contewnt-security.
And i try on Firefox and IE.

I try the Console > Configuration > Setting > General
Called: Allow Unsafe JavaScript eval() calls
Set that to Yes.

but that dosen't change anything.

And I have no clue ho to solve that and what to change to apply on the current content-security settings

**Comment by cigamit** [comment]
Not a Cacti bug, but a bug within how the plugin works I believe.

Also duplicate of https://github.com/Cacti/plugin_gpsmap/issues/12

**Comment by arno-st** [comment]
Not a duplicate exactly, it's not the same plugin.

But I would love to have some input, to find the bug on this (my) plugin !!
Here is the part of the code that is not working s I expect him:
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"
  integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
  crossorigin=""/>
<script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"
  integrity="sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew=="
  crossorigin=""></script>


and you can find the whole code here:
https://github.com/arno-st/map

It was working fine before the security-contend, and I know I'm way far from THE developer in PHP and web app, but willing to learn!

So any input you can give me is welcome

**Comment by TheWitness** [comment]
We've got a but like this in the main Cacti issue tracker as well.  I'm going to add another setting to loosen the security restrictions.  Might have it done tonight.  We'll see.

**Comment by TheWitness** [comment]
Looking through the spec's again, we may have to allow one to many origin's outside of 'self'.  Basically make it a configuration option.

**Comment by TheWitness** [comment]
Hopefully, this is self explanatory. 
![image](https://user-images.githubusercontent.com/1439914/93402714-82e15180-f853-11ea-9620-49a353bcbaf8.png)

**Comment by arno-st** [comment]
Almost good
You just need to add $alternate to img-src and it's ok

**Comment by arno-st** [comment]
Almost good
You just need to add $alternate to img-src and it's ok

**Comment by arno-st** [comment]
Almost good
You just need to add $alternate to img-src and it's ok

**Comment by TheWitness** [comment]
Okay, test again.

**Comment by arno-st** [comment]
Yup perfect thanks for your prompt action

**Comment by squad1534** [comment]
I'm facing this same issue in Debian Buster will this fix make it into buster-backports?

**Comment by TheWitness** [comment]
You need to direct this to @paulgevers.

**Comment by paulgevers** [comment]
@squad1534 yes it will, once there is a new cacti release, I packaged it for unstable, the package migrates to testing (and somebody pings me ;) )

**Comment by TheWitness** [comment]
@paulgevers, we have been delaying the 1.2.15 for a bit now picking up a few additional bugs here and there.  There are a number of users and companies testing the 1.2.x branch.  I think we are pretty close right now.  When @netniV thinks we are ready, we will pull the trigger.

**Comment by netniV** [comment]
I am thinking next weekend would be good. Most things seem to have calmed down again.

**Comment by bmfmancini** [comment]
That works for me!

**Comment by squad1534** [comment]
Sounds great, thanks Devs!
