### ISSUE TITLE
The maximum value of the graph and the table do not match

### ISSUE THREAD

**Issue by zhangjian420** [Cacti/cacti#3812]
I found a problem. After exporting the table data through the csv button next to the graph, and then sorting the table data, the maximum value is inconsistent with that shown in the graph.
1、The value shown in the graph
![1](https://user-images.githubusercontent.com/293321/93715028-3a9a9a00-fb99-11ea-9f76-2f1e820e508d.png)
2、Sorted table data
![2](https://user-images.githubusercontent.com/293321/93715037-49814c80-fb99-11ea-9c84-3e701304f617.png)

**Comment by zhangjian420** [comment]
@netniV @cigamit Can you help me solve this problem?

**Comment by TheWitness** [comment]
I would ask if you could please do some investigation and see if you can determine the issue.  It could be a difference between 1024 and 1000.

**Comment by netniV** [comment]
I would suggest that it is because of the difference between the two methods of reporting byte size.  1 MB can sometimes be reported as 1,0000,000 instead of 1,048,576.  When used in calculations it should really be the latter used.

**Comment by TheWitness** [comment]
No feedback.
