### ISSUE TITLE
Issues with Cacti login when session_autostart is configured in php.ini

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#3815]
I had previously upgraded from 1.2.9 to 1.2.11. Then I backed out. Now I've upgraded to 1.2.14. I'm getting a lot of these errors now:

```
2020-09-21 23:03:40 - ERROR PHP : A session had already been started - ignoring session_start() in file: /cacti/cacti-1.2.14-prod/lib/functions.php  on line: 5546
2020-09-21 23:03:40 - CMDPHP PHP ERROR NOTICE Backtrace:  (/graph_json.php[32]:include(), /include/auth.php[28]:require_once(), /include/global.php[439]:cacti_session_start(), /lib/functions.php[5546]:session_start(), CactiErrorHandler()
```

My php.ini :
```
date.timezone = America/Denver

; For Cacti spikekill
;memory_limit = 1024M      ; Maximum amount of memory a script may consume
memory_limit = 2048M      ; Maximum amount of memory a script may consume
max_execution_time = 90

; eric angry about files in /tmp
session.save_path = "/var/tmp/php_session_data"
;
; hide php version in http headers
expose_php = False

; 20190921 - schoelle - added to fix login problems for Cacti new install. 
; strange how this was missing for years and didn't really have problems?
[session]
session.auto_start=On
```
Cheers,

**Comment by netniV** [comment]
I don't know who recommended the session autostart in the PHP.INI but that is your problem.  I never use that and it's not something we recommend.

**Comment by eschoeller** [comment]
I disabled the session autostart and the messages went away. So, that's good:) Maybe a check for that setting in the installer would be worthwhile. Dunno if it's worth the hassle though. I don't think it's on by default.

**Comment by TheWitness** [comment]
Fixed it.

**Comment by netniV** [comment]
Having autostart could conflict with the cookie options though, is that anything worth reporting on ?

**Comment by TheWitness** [comment]
Correct, and good point.  We should open a feature request to block it.
