### ISSUE TITLE
Graph "append" time-out gap

### ISSUE THREAD

**Issue by zuka1337** [Cacti/cacti#3817]
# Describe the bug
An image or two is worth a thousand words:

![image](https://user-images.githubusercontent.com/57998098/93856177-868c3280-fcb0-11ea-8634-0e6681e2cabe.png)
![image](https://user-images.githubusercontent.com/57998098/93857056-e800d100-fcb1-11ea-854a-829ad1f1bf5a.png)

When i have a device timeout or for whatever reason the graph stops, I've come accross with this "bug" wich can lead to a mislead that the "graph is normal and nothing is wrong with the device that is being graphed".

## To Reproduce

The graph must have any "gap" with no info, then:
        Simple re-index the device or disable and enable.

## Expected behavior

This:

![image](https://user-images.githubusercontent.com/57998098/93856671-45e0e900-fcb1-11ea-86c5-6fd7a9c603eb.png)
![image](https://user-images.githubusercontent.com/57998098/93857101-f8b14700-fcb1-11ea-8b6c-b0b29dcb1e22.png)

Tested: Version 1.2.14 and Version 1.2.7.

**Comment by netniV** [comment]
You would need to check what your datasource settings are for missing/bad data.  And long that can occur before the "timeout" is stored as such.  Otherwise, RRDtool will try and 'fill' the gap with what it knew/knows.

There is also separate functionality called SpikeKill that can fill data depending on what's occurring.  Can you post more information about your data source?  

I'm also slightly confused between the pictures because if you are saying that a drop in traffic where a value is returned but really low isn't treated as a timeout, then you would be correct as we would have no way to know that it isn't a valid value.

**Comment by zuka1337** [comment]
- Well for simplicity I've removed the middle graph,  as you can see above, those are duplicated graph, and the graphs stoped (for whatever reason may be, not relevat).

> There is also separate functionality called SpikeKill that can fill data depending on what's occurring. Can you post more information about your data source?

Yes, for that is Disabled, never worked for me.

Is this config you need?

![image](https://user-images.githubusercontent.com/57998098/93979486-4d69c600-fd75-11ea-99e0-ab59e0ff0e84.png)


> I'm also slightly confused between the pictures because if you are saying that a drop in traffic where a value is returned but really low isn't treated as a timeout, then you would be correct as we would have no way to know that it isn't a valid value.

Ok, may not be an device timeout, the correct way of saying is a "Drop in traffic", butt sometimes it seems that rrdtool is replacing NaN values for Last known values .

Another example (This on I don't have the "gap" version but data was missing since yesterday noon, I was fixing the graph now and boom.. the last value was **1201.7163** and then folowing was **NaN** I'm sure, but now look what happend :

![image](https://user-images.githubusercontent.com/57998098/93981467-ef8aad80-fd77-11ea-9457-080d413613cf.png)
![image](https://user-images.githubusercontent.com/57998098/93981772-498b7300-fd78-11ea-8a33-7be996d3531f.png)

This happend just bu re-indexing the device.

Tell me if you need any additional info.

**Comment by TheWitness** [comment]
This is a feature not a bug.  You need to set your heartbeat that aligns with your gap criteria.  In the 1 minute sampling, the default heartbeat is set to 10 minutes, which is arguably long.  But it's a configuration option.
