### ISSUE TITLE
new user always change password failed due to password_hash when using php5.5+ 

### ISSUE THREAD

**Issue by OtisLin** [Cacti/cacti#382]
New php function password_hash @php5.5+ generate different password hash every time with same password. This will cause current user password never match. We should use password_verify instead of password_hash to verify password like below:
if (! password_verify( get_nfilter_request_var('current_password') , $user['password'] )) {
    # code for current password no match
}

please check line 106 @ auth_changepassword.php

**Comment by OtisLin** [comment]
Pull request #383 
It works @ php5.6 on my machine

**Comment by cigamit** [comment]
Thanks for the pull request.  Resolved.
