### ISSUE TITLE
Removal of several items that require a confirmation have inconsistent bahavior

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/cacti#3820]
## To Reproduce

1. Go to Present - Data Profiles page

2. Click a data profile

3. Click 'x' to remove a Data Source Profile RRAs for the data profile

4. Click continue, page has no response, js error exist 

## Expected behavior
After click 'x', and click continue, the data source profile RRAs can be removed well. 

## Desktop (please complete the following information)

- OS: rhel7 x64

- Browser FF 80

- Version Cacti 1.2.15 

![Screen Shot 2020-09-23 at 2 09 09 PM](https://user-images.githubusercontent.com/47589910/93974441-63dd4500-fda8-11ea-963b-73a47c9eba1d.png)
![Screen Shot 2020-09-23 at 2 09 58 PM](https://user-images.githubusercontent.com/47589910/93974489-735c8e00-fda8-11ea-9245-a01c329d9224.png)

**Comment by TheWitness** [comment]
This will affect a few more pages as well @yingbaiibm.  I'll have to track down over the weekend.

**Comment by TheWitness** [comment]
I tracked the issue to the cdialog being appended to the 'body' instead of '#main'.  So, they were not disposed on a page refresh.  Moved the dialog to the main div, which will ensure that they are cleared with the remainder of the content from other pages.
