### ISSUE TITLE
The refresh circle still exist after export color done 

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/cacti#3821]
## To Reproduce

1. Go to Present - Colors page 

2. Click Export button 

3. After export done, the refresh circle still running and can not disappear. 

## Expected behavior

After export done, the refresh circle should disappear

## Desktop (please complete the following information)

- OS: rhel7 x64 

- Browser  FF 80 

- Version  Cacti 1.2.x latest code 

![Screen Shot 2020-09-23 at 3 06 12 PM](https://user-images.githubusercontent.com/47589910/93979199-9a6a8e00-fdaf-11ea-93cd-b11c1873c090.png)

**Comment by TheWitness** [comment]
Resolved.

**Comment by yingbaiibm** [comment]
Need also fix the export function for **automation_devices.php, graph_xport.php, host.php, templates_export.php**
