### ISSUE TITLE
Zoom in graphs and graphs filter not working.

### ISSUE THREAD

**Issue by frankfer01** [Cacti/cacti#3830]
# Describe the bug

In graphs filter, if you select, for example last 6 or 4 or 2 hours, it show last day.  If you select last week , it show the last day
![image](https://user-images.githubusercontent.com/55502569/94486344-498ed700-01ad-11eb-9cca-4a250b3b1c9e.png)

But, if you select a month, works well
![image](https://user-images.githubusercontent.com/55502569/94486410-62978800-01ad-11eb-9feb-36f1b3301562.png)

The zoom also not working, you can mark the zoom area, but the graphs it's the same(las 24 hours):

![image](https://user-images.githubusercontent.com/55502569/94486565-9c688e80-01ad-11eb-9177-6b1fdfe5497b.png)

I test it in Google Chrome, Firefox and IExplorer. Two weeks ago was working. No changes made  in Cacti.

Cacti vesion: 0.8.8b

Note: I know is an unsupported version, but  for the moment, we can't upgraded. Just give me some ideas to solve. I suspect of one windows update.

Regards,

**Comment by cigamit** [comment]
Already resolved via #3797
You just need to apply the fixes from that patch.
