### ISSUE TITLE
Minor errors in sep 8 of upgrade web page

### ISSUE THREAD

**Issue by ericorain** [Cacti/cacti#3831]
# Describe the bug

Nothing critical. A little error of typing ("T**a**mplate" instead of "Template") and another one is the button name ("Finish" instead of "Next") appear in step 8 of the upgrade process of Cacti 1.2.14.

## To Reproduce

Upgrade Cacti from 1.2.13 to 1.2.14

## Screenshots

![step8](https://user-images.githubusercontent.com/50406518/94563196-a0a4b280-0266-11eb-98db-7373e6e201c9.png)

**Comment by TheWitness** [comment]
Appreciate that!
