### ISSUE TITLE
Exclude IP addresses in Automation Networks

### ISSUE THREAD

**Issue by EmilAndersson-SE** [Cacti/cacti#3832]
# Feature Request

## Is your feature request related to a problem? Please describe

In my case gateway (firewall) responds to SNMP for every network i add to automation network-list. A bit annoying because i have this device from a "proper" management address already. Some High avaibility setups have a common VRRP address. 

## Describe the solution you'd like

Would love to see a way to exclude single IP-adress, range or smaller network (/xx)

## Describe alternatives you've considered

None, the discovered network-list getting bigger for unwanted devices

**Comment by TheWitness** [comment]
It should not add the device a second time if the snmp_sysName is identical.  So, ...

1) Are you on 1.2.14?
2) If so, are you experiencing a double add?

**Comment by EmilAndersson-SE** [comment]
Wops, forgot that: we are running Cacti 1.2.10

**Comment by TheWitness** [comment]
Review the CHANGELOG.  Seems we caught this a while ago.

**Comment by EmilAndersson-SE** [comment]
If you mean **_-issue#2818: Automation can sometimes incorrectly add duplicate devices with the same sysname_** i think igot something else:

This is from discovered networks:
![image](https://user-images.githubusercontent.com/56084138/94687761-fc397380-032c-11eb-9f4e-fd7da692c55c.png)

This is my previous added device:
![image](https://user-images.githubusercontent.com/56084138/94687912-2be87b80-032d-11eb-8d47-0641f409dde7.png)

My wish here, is to exclude, in this case 172.19.3.1 because its the gateway so it never shows up in the discovered list to keep it as short as possible with accurate Automation Network settings.  :) Is this crazy?

**Comment by TheWitness** [comment]
Easy enough.

**Comment by TheWitness** [comment]
We need help from devs BTW.  Too much to do, not enough resources.

**Comment by EmilAndersson-SE** [comment]
Don't hurry, i'm not leaving Cacti. Ever. I guess

**Comment by TheWitness** [comment]
This is resolved, but I did not support subnet ranges in the solution, just IP addresses.
