### ISSUE TITLE
Dry-run Automation Device Rule

### ISSUE THREAD

**Issue by EmilAndersson-SE** [Cacti/cacti#3833]
# Feature Request

## Is your feature request related to a problem? Please describe

It's a bit of a lottery to configure Device Rules. You have to figure out what to match for, configure and run discover on the network. Wait to discover is done and then check some logs and see what happend. If you are lucky you are done, otherwise repeat. 

## Describe the solution you'd like

Same lovely way to activate "Show Matching Devices" in the Graph Rules-section, this is awesome!

## Describe alternatives you've considered

None, i bet this would be appreciated, a timesaver and safer way when dry-run and adjust rules.

**Comment by TheWitness** [comment]
Yea, that's not a bad idea.  Add the devices to the Automation Devices page, but not to Cacti.

**Comment by TheWitness** [comment]
Right now, you can emulate that by simply flipping this switch.

![image](https://user-images.githubusercontent.com/1439914/94626403-086bf500-0289-11eb-911f-6d968c76e038.png)

**Comment by EmilAndersson-SE** [comment]
Something like this?

![image](https://user-images.githubusercontent.com/56084138/94681633-1589f200-0324-11eb-8b33-591d0006070f.png)

**Comment by TheWitness** [comment]
Yea, I get that.  Great idea.
