### ISSUE TITLE
[Bug] Discovered Devices seachfilter is limited 1.2.10

### ISSUE THREAD

**Issue by EmilAndersson-SE** [Cacti/cacti#3834]
# Describe the bug

Searchfilter in Automation => Discovered Devices only affect IP-field. 

## To Reproduce

1. Go to Automation => Discovered Devices

2. Search for something in Device name, SNMP-name, Location, Contact or Description 

3. The list of results is empty

## Expected behavior

The list should return filtered based on my search

## Desktop (please complete the following information)

- OS: Windows 10 2004

- Browser Microsoft Edge Version 85.0.564.63 (Officiell version) (64 bitar)

## Additional context

All other searchfields in Cacti works great.

Cacti 1.2.10 running on Ubuntu 20.04
Apache 2.4.41
PHP 7.4.3
MySQL-server 8.0.21

**Comment by TheWitness** [comment]
This is resolved in 1.2.14.  So, duplicate and resolved.
