### ISSUE TITLE
Cacti Graph Template for traffic Uses on each interface showing bandwidth uses as well other fixed service uses like ( 1. YouTube 2.Facebook 3. Google ) in a single graph

### ISSUE THREAD

**Issue by smwadek** [Cacti/cacti#3838]
Dear Concern

Please help me regarding this solution, we need to provide graph for uses of traffic for Internet Uses as well other services  like ( 1. YouTube 2.Facebook 3. Google ) in a single graph on Each Interface of the device. 

Is it possible? If any idea it will be great.

**Comment by bmfmancini** [comment]
You are looking for something more like netflow for something like that

Traffic graphs via snmp typically give you the usage on the port in terms
of throughout

For what you are looking for check out the flow view plugin

**Comment by TheWitness** [comment]
Correct.  Closing this.
