### ISSUE TITLE
Cacti log Mysql error 2013

### ISSUE THREAD

**Issue by misterbux** [Cacti/cacti#3839]
Hi everyone,

I'm having error on my cacti log and didn't find the solution yet, herewith attached the error. I'm using cacti 1.12.2 and running on windows server 2016. Seeking your advise to solve this issue. Thank you.

![cacti1-12-2logerror](https://user-images.githubusercontent.com/42340110/94756315-c5fe0180-03c9-11eb-9edc-0f2ff18f8dfe.png)

**Comment by TheWitness** [comment]
Increase your max_connections.  If you increase to say 1000, and after restart reports something less, google what MySQL reports.  You may have to modify your systemd units file.

**Comment by TheWitness** [comment]
Edit your data collector and change your thread count.

**Comment by TheWitness** [comment]
Lastly, what's your poller interval?

**Comment by TheWitness** [comment]
No feedback.
