### ISSUE TITLE
[Cacti 1.2.13] Cannot create 95th in and out independence

### ISSUE THREAD

**Issue by huybacnguyen** [Cacti/cacti#3841]
Hi.
I'm going to upgrade Cacti 0.8 to Cacti 1.2.13
But, in Cacti 1.2.13, i cannot see 95th in and out, only see 95.
What is difference in it. and how to make 95 th in and out on Cacti 1.2.13
![95th](https://user-images.githubusercontent.com/71247861/94903994-d2b35000-04c4-11eb-9b41-37037341061c.png)

**Comment by TheWitness** [comment]
Someone modified the interface data query on your old system to add those templates.  They will be there after upgrade, but don't install packages when you are given the option.  It'll break things.

**Comment by huybacnguyen** [comment]
Thank, and what is the 95th, in+out. (in Cacti 1.2.13)
is it: Total IN+Out, then caculate 95th of this total
Or: it's 95th of IN or OUT (according to the max value)

**Comment by TheWitness** [comment]
Good question, there are several aggregation functions, in the Cacti 1.2.13 case, the equation is:

```
|95:bits:6:max:2|
```

* 95 => 95th Percentile
* bits => self explanatory
* 6 => power, this one takes some explaining, but not here
* max => The function to call
* 2 => The number of digits to round the data to

The important variable is "max", which is the max of all the data sources using the AVG consolation function.  You have other options though:

* max => The max value of any data source not the sum (the default case) using the AVG consolidation function
* current => The current value of a data source (somewhat ambiguous if you have multiple data sources, but works for single data source graphs)

* total => The sum of the data sources using the AVG consolidation function
* total_peak => The sum of the data sources using the MAX consolidation function
* aggregate_sum => The sum of all the data sources over the time range using either AVG or MAX consolidation functions

* all_max_current => The max of all the data sources using the AVG consolidation function
* all_max_peak  => The max of all the data sources using the MAX consolidation function
* aggregate_peak => The max of all the data sources using the MAX consolidation function
* aggregate_max => Same as aggregate_peak (alias)

* aggregate => The sum of the data sources using the AVG consolidation function
* aggregate_current => The same as aggregate (alias)

I think I have them right.

**Comment by TheWitness** [comment]
I hope this helps.  Going to close now, but feel free to comment.  If you think the Documentation needs updating, please create a pull request.  That would be very helpful.

**Comment by TheWitness** [comment]
Now, if you would like to create a separate in + separate out nth percentile line, that would be feature request.  A good one I might add.
