### ISSUE TITLE
[Question] Export Graph name and id per host  - Query

### ISSUE THREAD

**Issue by zuka1337** [Cacti/cacti#3842]
For migration purpose I need to query and compare old.rrd and new.rrd to merge with an .py script

How can I query the DB to get something like graph name and id per host as the image bellow:

Hostname - graph   |   id 

![Sem Título](https://user-images.githubusercontent.com/57998098/94922664-86f7ab00-04b2-11eb-81f2-67e2ea35d153.png)

Db dump/import is not an option.

**Comment by TheWitness** [comment]
Did you look at rrd_merge php?

**Comment by TheWitness** [comment]
Oh, you know, there is more.  Take a look at the merge cli, but I need to post something else. Not today though.

**Comment by zuka1337** [comment]
Well, I din't know about the php splice ! Nice one! Thanks :D

**Comment by TheWitness** [comment]
Yea, it's "splice_rrd.php", my bad.  Glad you found it.

**Comment by TheWitness** [comment]
Make sure you have php5.4+ to get the SQLite support right though.  Don't know many that would be running that old of a PHP though.

**Comment by zuka1337** [comment]
Hey @TheWitness sorry for re-open this one,
It is possible to get name and id per host as the image above with a single query?
