### ISSUE TITLE
[Bug] 1.2.14 Automation Device Rule not working

### ISSUE THREAD

**Issue by EmilAndersson-SE** [Cacti/cacti#3843]
# Describe the bug

Automation Device Rule not adding new devices. 

## To Reproduce

Setup network to scan, make sure SNMP-match and checkbox Automatically Add to Cacti is checked. Go for discover and wait until done. Check Cacti-log, see printscreen:

![image](https://user-images.githubusercontent.com/56084138/94927301-5d468000-04c2-11eb-847a-3a6810311e9e.png)

I have run with debugging (awesome feature!) on automation-files and verified the query-syntax and its correct, but it may not be compatible with MySQL-server 8.x+

## Expected behavior

New devices maches Device Rules should be added to Cacti.

## Workaround

I got this semi-auto, to run my Network-scans and go to Discovered Devices, check all new and apply correct templates.

## Additional context

Cacti installed with **apt-get install cacti cacti-spine** on fresch Ubuntu 2004 LTS (i guess this is the problem).

- Apache 2.4.41
- PHP 7.4.3
- MySQL-server 8.0.21 (my main guess something happend here)

Verified on Cacti 1.2.10, 1.2.12 and 1.2.14.

**Comment by TheWitness** [comment]
What's does your match rule look like, paste the test.

**Comment by EmilAndersson-SE** [comment]
**Device rule**
![image](https://user-images.githubusercontent.com/56084138/95048497-39648380-06e8-11eb-9d34-f7858b12ee87.png)

**Debugging CLOG**
![image](https://user-images.githubusercontent.com/56084138/95048438-2356c300-06e8-11eb-80e4-579388efea59.png)

`2020-10-05 08:49:17 - DBCALL ERROR: A DB Row Failed!, Error: 3685, SQL: 'SELECT at.*,ht.name FROM automation_templates AS at INNER JOIN host_template AS ht ON ht.id=at.host_template WHERE ('HP J9774A 2530-8G-PoEP Switch, revision YA.16.10.0009, ROM YA.15.20 (/ws/swbuildm/rel_ajanta_qaoff/code/build/lakes(swbuildm_rel_ajanta_qaoff_rel_ajanta)) (Formerly ProCurve)' RLIKE sysDescr OR 'HP J9774A 2530-8G-PoEP Switch, revision YA.16.10.0009, ROM YA.15.20 (/ws/swbuildm/rel_ajanta_qaoff/code/build/lakes(swbuildm_rel_ajanta_qaoff_rel_ajanta)) (Formerly ProCurve)' LIKE CONCAT("%", sysDescr, "%")) AND ('.1.3.6.1.4.1.11.2.3.7.11.138' RLIKE sysOid OR '.1.3.6.1.4.1.11.2.3.7.11.138' LIKE CONCAT("%", sysOid, "%")) AND ('sw-baldg11EMIAND11-25308GP' RLIKE sysName OR 'sw-baldg11EMIAND11-25308GP' LIKE CONCAT("%", sysName, "%")) ORDER BY sequence LIMIT 1'`

**Comment by TheWitness** [comment]
What version of MariaDB/MySQL?  That SQL gives me no error on MariaDB 10.5.

**Comment by netniV** [comment]
Can you run the SQL command within MySQL itself to see what the actual error is.

**Comment by EmilAndersson-SE** [comment]
MySQL Server version: 8.0.21-0ubuntu0.20.04.4 (Ubuntu).

`mysql> SELECT at.*,ht.name FROM automation_templates AS at INNER JOIN host_template AS ht ON ht.id=at.host_template WHERE ('HP J9774A 2530-8G-PoEP Switch, revision YA.16.10.0009, ROM YA.15.20 (/ws/swbuildm/rel_ajanta_qaoff/code/build/lakes(swbuildm_rel_ajanta_qaoff_rel_ajanta)) (Formerly ProCurve)' RLIKE sysDescr OR 'HP J9774A 2530-8G-PoEP Switch, revision YA.16.10.0009, ROM YA.15.20 (/ws/swbuildm/rel_ajanta_qaoff/code/build/lakes(swbuildm_rel_ajanta_qaoff_rel_ajanta)) (Formerly ProCurve)' LIKE CONCAT("%", sysDescr, "%")) AND ('.1.3.6.1.4.1.11.2.3.7.11.138' RLIKE sysOid OR '.1.3.6.1.4.1.11.2.3.7.11.138' LIKE CONCAT("%", sysOid, "%")) AND ('sw-baldg11EMIAND11-25308GP' RLIKE sysName OR 'sw-baldg11EMIAND11-25308GP' LIKE CONCAT("%", sysName, "%")) ORDER BY sequence LIMIT 1;
--------------
SELECT at.*,ht.name FROM automation_templates AS at INNER JOIN host_template AS ht ON ht.id=at.host_template WHERE ('HP J9774A 2530-8G-PoEP Switch, revision YA.16.10.0009, ROM YA.15.20 (/ws/swbuildm/rel_ajanta_qaoff/code/build/lakes(swbuildm_rel_ajanta_qaoff_rel_ajanta)) (Formerly ProCurve)' RLIKE sysDescr OR 'HP J9774A 2530-8G-PoEP Switch, revision YA.16.10.0009, ROM YA.15.20 (/ws/swbuildm/rel_ajanta_qaoff/code/build/lakes(swbuildm_rel_ajanta_qaoff_rel_ajanta)) (Formerly ProCurve)' LIKE CONCAT("%", sysDescr, "%")) AND ('.1.3.6.1.4.1.11.2.3.7.11.138' RLIKE sysOid OR '.1.3.6.1.4.1.11.2.3.7.11.138' LIKE CONCAT("%", sysOid, "%")) AND ('sw-baldg11EMIAND11-25308GP' RLIKE sysName OR 'sw-baldg11EMIAND11-25308GP' LIKE CONCAT("%", sysName, "%")) ORDER BY sequence LIMIT 1
--------------

ERROR 3685 (HY000): Illegal argument to a regular expression.
mysql> `

**Comment by EmilAndersson-SE** [comment]
Now i am very confused. Does the Device rules work with a regular string, as i have used here and been following from other instructions and the default rules? Or is there a need to use regular expressions to match for this to work?

**Comment by netniV** [comment]
It mixes both in.  So that if people enter a string that isn't an expression it still works.  But because you have things that break an expression in there, not just pure text, it breaks the expression handling.

**Comment by EmilAndersson-SE** [comment]
You have to help me out here as I can't see where its broken while debugging. I have tried both just Procurve as a string and (Procurve) as regex-match 

![image](https://user-images.githubusercontent.com/56084138/95958773-e5e9e800-0e01-11eb-97eb-22aca3b3a403.png)

![image](https://user-images.githubusercontent.com/56084138/95958841-031eb680-0e02-11eb-81c8-5e461609d571.png)

`2020-10-14 09:33:24 - DBCALL ERROR: A DB Row Failed!, Error: 3685, SQL: 'SELECT at.*,ht.name FROM automation_templates AS at INNER JOIN host_template AS ht ON ht.id=at.host_template WHERE ('HP J9774A 2530-8G-PoEP Switch, revision YA.16.10.0009, ROM YA.15.20 (/ws/swbuildm/rel_ajanta_qaoff/code/build/lakes(swbuildm_rel_ajanta_qaoff_rel_ajanta)) (Formerly ProCurve)' RLIKE sysDescr OR 'HP J9774A 2530-8G-PoEP Switch, revision YA.16.10.0009, ROM YA.15.20 (/ws/swbuildm/rel_ajanta_qaoff/code/build/lakes(swbuildm_rel_ajanta_qaoff_rel_ajanta)) (Formerly ProCurve)' LIKE CONCAT("%", sysDescr, "%")) AND ('.1.3.6.1.4.1.11.2.3.7.11.138' RLIKE sysOid OR '.1.3.6.1.4.1.11.2.3.7.11.138' LIKE CONCAT("%", sysOid, "%")) AND ('sw-baldg11EMIAND11-25308GP' RLIKE sysName OR 'sw-baldg11EMIAND11-25308GP' LIKE CONCAT("%", sysName, "%")) ORDER BY sequence LIMIT 1'`

**Comment by netniV** [comment]
You will need to remove the backets.

**Comment by TheWitness** [comment]
I wonder if there is a preg_quote MariaDB function.  Not sure.

**Comment by TheWitness** [comment]
Looking through this, MySQL/MariaDB have changed much recently.  I suspect this is database version dependent.  I really don't want to install MySQL 8.x at the moment.  Can you test with a recent MariaDB?

**Comment by TheWitness** [comment]
What if you make the REGEX string '(Procurve)' with the quotes?

**Comment by EmilAndersson-SE** [comment]
This is this singelquotes and regex like this: '(Procurve)'
![image](https://user-images.githubusercontent.com/56084138/96415740-49ec2200-11ef-11eb-9f04-4c14aca80383.png)

This is just a simple string like this Procurve
![image](https://user-images.githubusercontent.com/56084138/96416121-e0b8de80-11ef-11eb-90f0-52201cf2e103.png)

I must be blind, where is the string to match in SQL-query?

I'm up to install a new VM with new MariaDB, hope to have some results later this day.

**Comment by EmilAndersson-SE** [comment]
OK here we go with MariaDB-server 10.3.22, it does the work done. The query to match devices is a simple string **Procurve** .
Now i'm running MariaDB on a separate server, i dont know how optimal this is for running Cacti but i would say its integrated with the application and like it on the same machine. I guess its up to you guys to decide if MySQL-server 8.x is supported in future :)

![image](https://user-images.githubusercontent.com/56084138/96423162-380f7c80-11f9-11eb-989f-76a47cfced31.png)

**Comment by TheWitness** [comment]
It's likely a bug in MySQL.  They recently changed the regex engine.  That likely has something to do with it.  Why don't you open a bug report with them, and claim it works on MariaDB?  In my case, 10.5.6.

**Comment by EmilAndersson-SE** [comment]
I feel like all-time worst Cacti-user right now. MariaDB solved automation problem. But now poller hits maximum runtime every run and graphs are empty. Resources on the database-server is almost at sleep. To try another install, i did a fresh install with Cacti 1.2.14 on the same database-machine running MariaDB 10.3.22 but its the same even there, i think i need some vacation for a year or two this is driving me nuts.

![image](https://user-images.githubusercontent.com/56084138/96457654-550b7600-1220-11eb-8f52-1041d6e20933.png)

**Comment by TheWitness** [comment]
Well, you should check your database for errors.  I nyour case, it's showing "DataSources:0", which means your poller_item table is either corrupt or empty.  Check that.  Check your MariaDB log for errors.  Looks also like your are running the "develop" version of Cacti, which is NOT recommended right now.  Back off to the 1.2.x branch.

**Comment by EmilAndersson-SE** [comment]
You are correct about there is nothing for to poll - because its a complete empty fresh Cacti installation of 1.2.1.4. I'm sorry i didn't know 1.2.14 was a developer version. I think i have to re-think a few steps about our migration from the old 0.8.8.

**Comment by netniV** [comment]
1.2.14 is not a developer version.  Development version is 1.3.x

**Comment by TheWitness** [comment]
MySQL made huge changes, and they are new to many.  Until we get someone to write doco for it, we will simply ignore. 

Someone has gotten it working as there were many MySQL 8 patches though.

**Comment by EmilAndersson-SE** [comment]
MySQL 8 and Cacti 1.2.x fully working? Sounds like some customization to me. Anyway, i'm very happy right now.
