### ISSUE TITLE
Cacti 1.2.14 Real-Time Graphs not working

### ISSUE THREAD

**Issue by andermat8** [Cacti/cacti#3847]
# Describe the bug

Running Cacti on Windows Server 2012.  Using Chrome or Edge getting same results where you select to view graph in real-time and it will just keeping clocking with no graph.  If you toggle a time settings or thumbnails it will cause a refresh and you can see graph data but you have to keep doing this to produce a refresh to view new graph data.   

![image](https://user-images.githubusercontent.com/29753529/95267156-99e7e380-0802-11eb-998a-aa5513b352d7.png)

toggle thumbnail and will get a graph:
![image](https://user-images.githubusercontent.com/29753529/95267257-cf8ccc80-0802-11eb-908f-8ee66401a638.png)

toggle again and get data:
![image](https://user-images.githubusercontent.com/29753529/95267333-07940f80-0803-11eb-83cc-af90bb79c738.png)

**Comment by EmilAndersson-SE** [comment]
I can confirm this bug too using 1.2.14, something is broken with auto-refresh in the popup with Chrome-based browser

**Comment by TheWitness** [comment]
Open the browsers debug window as a separate window and look for Javascript errors.  I've tested on the 1.2.x branch and I can not presently reproduce.

**Comment by EmilAndersson-SE** [comment]
Realtime is working as expected on 1.2.12. I've the same problem with auto-refresh as andermat8 in 1.2.14. My first hit on this was an earlier install and i wrote this: https://forums.cacti.net/viewtopic.php?f=21&t=61251

**Comment by netniV** [comment]
Are we sure that it hasn't been because of 
https://github.com/Cacti/cacti/issues/3786

**Comment by andermat8** [comment]
Sorry, I've been traveling so responding late.  With Chrome or Edge getting error Failed to load resource: the server responded with a status of 404.  IE works fine but since it is being replaced by Edge not too many folks use it anymore. 

![image](https://user-images.githubusercontent.com/29753529/95656914-5c73a680-0adf-11eb-8d4c-90f7eb7a1304.png)

**Comment by TheWitness** [comment]
That's a web server issue.  Anything else?

**Comment by andermat8** [comment]
Nothing I can see.  I tried it in incognito mode but same results.  Can you think of anything else to check?  Does it work for you in Chrome and if so what version?

**Comment by TheWitness** [comment]
Latest available on Windows 10.

**Comment by EmilAndersson-SE** [comment]
I can confirm it working in Google Chrome Version 86.0.4240.75 (Officiell version) (64 bitar). But the problem seems to be isolated to Microsoft Edge (Chromium-based) Version 86.0.622.38 (Officiell version) (64 bitar). Same here as andermat8, Microsoft Edge is becoming a more acceptable default webbrowser on many places

**Comment by oijkn** [comment]
Hello,

I also encounter a realtime problem with version 1.12.14 when using the `scripts/ss_net_snmp_disk_io.php` (Data Input Methods -> Script Server) file.
The poller retrieve the data correctly but during the realtime I only have values at 0.
I tried with two different browsers (FireFox & Chrome) without success and no errors in the console or else.

![image](https://user-images.githubusercontent.com/18188407/95919822-8e6e5c80-0dae-11eb-8c72-fd34b42644d3.png)
![image](https://user-images.githubusercontent.com/18188407/95920016-eefd9980-0dae-11eb-99fa-a1297b31e046.png)

**Comment by netniV** [comment]
This does appear to be an Edge problem.

**Comment by EmilAndersson-SE** [comment]
> This does appear to be an Edge problem.

But it works good on 1.2.10, have some work been done on Realtime from then?

**Comment by oijkn** [comment]
Well I think I've found where the problem is. If we look at this part of the code https://github.com/Cacti/cacti/blob/87078bb65f1afe95da053e13f8403a1403d5c77b/scripts/ss_net_snmp_disk_io.php#L31 we see that Cacti wants to write in `/tmp/cacti/...` whether it's with the user `cacti` or `www`.

Unfortunately in realtime mode the user `www` doesn't have the rights to write to this directory.

So the workaround is :
```
	if ($environ != 'realtime') {
		$tmpdir = $tmpdir . '/cacti/net-snmp-devio';
		$tmpfile = $host_id . '_io';
	} else {
		$tmpdir = $tmpdir . '/cacti-rt/net-snmp-devio';  // Change this path for realtime
		$tmpfile = $host_id . '_' . $poller_id . '_io_rt';
	}
```

Now I have the realtime that works perfectly :)

**Comment by andermat8** [comment]
Just to reiterate, I'm having this issue with Chrome (v86.0.4240.75) and Edge.  Internet Explorer works fine.  I'll test the workaround above and see if it works.

**Comment by andermat8** [comment]
After updating ss_net_snmp_disk_io.php I get the following results:

Running Chrome or Edge under C:\Windows\Temp cacti-rt will not get created.  
Running IE under C:\Windows\Temp cacti-rt will get created.

It does not appear to be a rights issue but something has changed since upgrading that is impacting Chrome based browsers.

**Comment by TheWitness** [comment]
I will be making an update to the two script momentarily, to separate the RT directory from the poller directory.

**Comment by TheWitness** [comment]
> 
> 
> Sorry, I've been traveling so responding late. With Chrome or Edge getting error Failed to load resource: the server responded with a status of 404. IE works fine but since it is being replaced by Edge not too many folks use it anymore.
> 
> ![image](https://user-images.githubusercontent.com/29753529/95656914-5c73a680-0adf-11eb-8d4c-90f7eb7a1304.png)

This issue is related to the web server configuration, not so much a Cacti issue.

**Comment by TheWitness** [comment]
So, not sure it's a browser or web server.  After searching, there is syntax in the various files that uses CSS variables to locate the font files.  There are two file type suffixes, there are:

*.less
*.scss

Both locate the fa-solid-900.woff2 differently.  My guess a quick google search will find your way to the solution.  It's definitely not related to Cacti, but more about FontAwesome and various browser/server support.  If you find the fix, open a separate ticket.

**Comment by TheWitness** [comment]
Look here for the server side change.

https://www.drupal.org/project/fontawesome/issues/2422431

**Comment by oijkn** [comment]
@TheWitness What is the link between FontAwesome and the access rights to the realtime directory created with the user cacti ?

**Comment by TheWitness** [comment]
None, but I put the rt directory in there as some people use a different user for the web server and the poller, which could lead to the conflict.  The FontAwesome issue is not new and we have provided instructions in the past as how to resolve it.

**Comment by andermat8** [comment]
I was able to correct the failed to load resource error but real-time graphs still only work for IE.  Not sure how this is a server side issue since the only changes made was to upgrade cacti.  I'm able to duplicate this error on 2 other servers.
