### ISSUE TITLE
You can't place an aggregate on a subtree in 1.0.4

### ISSUE THREAD

**Issue by gmuellerfr** [Cacti/cacti#385]
I want to place a graph on a tree.
I select the graph and choose "Place on Tree".
If the tree has subtrees, I can choose the subtree and click continue.

If it is a "normal" graph, it works. I will find the graph in the correct subtree.
If it is a "aggregate", the graph will always placed on the main tree you have selected
![aggregate_cacti](https://cloud.githubusercontent.com/assets/25848039/23663845/1b7ef404-0354-11e7-9851-f6f32b8ab283.png)

.

Kind Regards 

Guenter

BTW: The counter of the number of graphs in the section "Management -> Aggregate" counts all graphs with "Device = None", too, but doesn't show them. So you will be faced with "Next" Buttons, which lead to empty pages.

**Comment by cigamit** [comment]
Resolved, thanks for reporting!
