### ISSUE TITLE
Trees management screen not reporting correct number of trees

### ISSUE THREAD

**Issue by netadmin101** [Cacti/cacti#3850]
# Describe the bug

In the Tree management page, the header/footer where it shows "All # of Trees" does not show the correct count.  

## To Reproduce

1. Go to the console tab, click the Trees link under the Management section.
2. The dark blue header and footer is showing a count that doesn't match up with how many trees are in the list.

## Expected behavior

I would expect to see a count of the number of trees in the list on this screen.

## Screenshot
This screenshot is from a fresh install of cacti 1.2.14.  The first thing I did was went to the trees screen and added a new tree

![image](https://user-images.githubusercontent.com/11315980/95484541-979a9c00-095e-11eb-96ce-738adf02aa0d.png)

## Desktop (please complete the following information)

- OS: Windows 10
- Browser: Chrome/Firefox/IE

## Additional context

In the file trees.php on line 1984, the following query appears to generate that number based off of the graph_tree_items table and a distinct count of how many trees are actively being used.

        $total_rows = db_fetch_cell("SELECT COUNT(DISTINCT(ti.graph_tree_id))
                FROM graph_tree AS t
                LEFT JOIN graph_tree_items AS ti
                ON t.id=ti.graph_tree_id
                $sql_where");

Would it be better to count how many trees are defined?
SELECT COUNT(DISTINCT(id)) from graph_tree;

**Comment by TheWitness** [comment]
Good catch!

**Comment by netadmin101** [comment]
Thanks!  Looks good now.
