### ISSUE TITLE
[Bug] Can't save users when plugin Intropage is activate 1.2.14

### ISSUE THREAD

**Issue by EmilAndersson-SE** [Cacti/cacti#3855]
# Describe the bug

Can't modify users and save. The changes is lost and a new user is added with **User Name 0** and **Full Name 0** and complain to duplicate user_auth.id

Cacti 1.2.14 running on Ubuntu 20.04 LTS
PHP 7.4.3
MySQL-server 8.0.21

## To Reproduce

1. Make sure plugin Intropage is activated.

2. Select a user, make changes (not necessary) and hit save

3. Changes are not saved and you got a new unwanted user added

4. See error in Cacti-log

## Expected behavior

Changes should be saved to the selected user. Simple

## Workaround

Disable plugin Intropage and it works just fine to modify users.

## Screenshots

After saving admin-user, it says success:
![image](https://user-images.githubusercontent.com/56084138/95825854-caafa780-0d31-11eb-9633-f78cf2169b83.png)

This "account" is added everytime you save a user.
![image](https://user-images.githubusercontent.com/56084138/95825982-f3d03800-0d31-11eb-9d74-d28b2cfbfdde.png)

From Cacti-log during save on user
![image](https://user-images.githubusercontent.com/56084138/95826150-2ed26b80-0d32-11eb-97a0-fc7d63293618.png)

You can't remove the user 0 from gui, have to delete from the database manually.
![image](https://user-images.githubusercontent.com/56084138/95827490-182d1400-0d34-11eb-80a0-189c7c8199c6.png)

## Desktop (please complete the following information)

- OS: Windows 10 2004

- Browser Microsoft Edge  Version 86.0.622.38 (Officiell version) (64 bitar) and Google Chrome Version 86.0.4240.75 (Officiell version) (64 bitar)

**Comment by bmfmancini** [comment]
This was fixed it was an issue with the plugin download the latest version
and you will be good to go

**Comment by netniV** [comment]
I've closed this for now since it's a third party issue and should really be open on their repo.
