### ISSUE TITLE
Tree sequence wrongly increments

### ISSUE THREAD

**Issue by netadmin101** [Cacti/cacti#3858]
# Describe the bug

When saving changes to a tree, the tree sequence in the list of trees is always moved to the bottom of the list.  This happens when clicking the "Edit Tree" button and then the "Save" button, and it happens regardless of whether edits are actually made or not.  The tree sequence is always set to one above the current maximum.  The sequence is then incremented on any subsequent clicks of the save button.

## To Reproduce

1. Go to the trees section under management.

2. Create enough trees so that you have more than one.  Issue is best seen with 3 or more trees.

3. Take note of values in the mysql database, graph_tree field, specifically the sequence fields

4. Click on a tree name, not the last one in the list.  

5. Click the "Edit Tree" button.

6.  Click the "Save" button.

7.  Observe new values in the mysql database.  The tree you just edited has a new sequence that is one higher than the previous max

8.  Click save again.  The sequence increments again.

## Expected behavior

I would expect the sequence to remain the same as it was before the edits are made.  I.E, a tree at the top of the list shouldn't move to the bottom just because an edit was made.

## Screenshots

Original contents of mysql table
![image](https://user-images.githubusercontent.com/11315980/95934125-1ef07100-0d9e-11eb-9af1-4a5795acce6b.png)

Here I clicked save on the Default tree and the sequence was changed from 1 to 4.
![image](https://user-images.githubusercontent.com/11315980/95934174-392a4f00-0d9e-11eb-821f-a5b455f0d40e.png)

One more screenshot: I clicked save a second time, the sequence then changed to 5.
![image](https://user-images.githubusercontent.com/11315980/95934202-4cd5b580-0d9e-11eb-830d-b9183ce95121.png)

## Desktop (please complete the following information)

- OS: Windows 10
- Browser Chrome/Firefox/IE

## Additional context

 - Cacti Version 1.2.14
 - Issue is present on a fresh install
 - We recently updated from 1.2.1 to 1.2.14 and I don't recall it happening in 1.2.1.  

 In trees.php on line 507, the following if statement appears to always be true.  I wish I could provide a suggested fix, but for the life of me I can't find where $save['sequence'] is set.  (Or where it should be set if it's not being defined already)

                if (empty($save['sequence'])) {
                        $save['sequence'] = tree_get_max_sequence() + 1;
                }

**Comment by TheWitness** [comment]
Good catch.  This is a bug.

**Comment by TheWitness** [comment]
You will have to resort your trees before the changes will take affect for this fix.

**Comment by netadmin101** [comment]
Thanks!  I resorted and the sequences are working now as I'd expect them to.

**Comment by TheWitness** [comment]
@netadmin101, thanks for your help!
