### ISSUE TITLE
Cacti shows wrong title under some conditions

### ISSUE THREAD

**Issue by gmuellerfr** [Cacti/cacti#386]
Hello,
As you can see in the picture, the graph doesn't show the title it should configured with rrdtools.
I've seen this behaviour on 1.0.1, today I migrated to 1.0.4, but nothing changed.

This graph has created with "Device=NONE".
In 0.8.8a the title of this graph was shown. In other similar graphs the correct title is shown.

Kind Regards
Guenter

One Remark: At the end of the Debug output, I'm missing the word "ok", what RRDTool should Say. Maybe this will help.

![wrong_title](https://cloud.githubusercontent.com/assets/25848039/23664650/6d0f4538-0356-11e7-8c72-b3b817bf401b.png)

**Comment by cigamit** [comment]
Well, that is very odd that the title is the same as the right axis label and the rrdtool command seems to ignore what you have to the --title.  Can you please take the debug command, run it, but redirect the output to a file and then view that file using an image viewer and see if the issue still exists?

If the image is as displayed, then remove the "<->" characters from the title and try again.  Let me know what you find.  This may, in the end, be an RRDtool issue.

**Comment by gmuellerfr** [comment]
You are right, when I remove the "<>" characters from the title, the title will be correct displayed!
And rrdtool says: OK

The previous version of rrdtool command accepted those characters or those characters should be escaped.
 
When I run the command outside of cacti, I get the following warnings:
(process:29680): Pango-WARNING **: pango_layout_set_markup_with_accel: Error on line 1 char 11: Invalid UTF-8 encoded text in name - not valid '\xb0C'

(process:29680): Pango-WARNING **: pango_layout_set_markup_with_accel: Error on line 1 char 11: Invalid UTF-8 encoded text in name - not valid '\xb0C'

(process:29680): Pango-WARNING **: pango_layout_set_markup_with_accel: Error on line 1 char 11: Invalid UTF-8 encoded text in name - not valid '\xb0C'

(process:29680): Pango-WARNING **: pango_layout_set_markup_with_accel: Error on line 1 char 11: Invalid UTF-8 encoded text in name - not valid '\xb0C'

(process:29680): Pango-WARNING **: pango_layout_set_markup_with_accel: Error on line 1 char 26: '-' is not a valid name

(process:29680): Pango-WARNING **: pango_layout_set_markup_with_accel: Error on line 1 char 11: Invalid UTF-8 encoded text in name - not valid '\xb0C'

(process:29680): Pango-WARNING **: pango_layout_set_markup_with_accel: Error on line 1 char 11: Invalid UTF-8 encoded text in name - not valid '\xb0C'

**Comment by cigamit** [comment]
Okay, it looks like pango accepts htmlspecialchars.  So, we might be able to solve this.  Need to work on a revised lib/rrd.php.

**Comment by cigamit** [comment]
Please test again using the latest lib/rrd.php.  Should be better now.

**Comment by cigamit** [comment]
No feedback.
