### ISSUE TITLE
Console > Settings >Auth > Guest User drop-down list should not list current log on user

### ISSUE THREAD

**Issue by kim-fitness** [Cacti/cacti#3862]
# Describe the bug

After set the Console->Setting->Auth->Guest User as the current log on user, the user will be automatically logged out, and cannot log in anymore, until manually delete the record which name='guest_user' from table 'settings'.

**Comment by kim-fitness** [comment]
If there is only one account in the system(says, the 'admin'), and be set as the guest user, then there is no account can be logged on to the system anymore.

**Comment by netniV** [comment]
That does seem like a bug.  I know that I request changes a long time back for users who are guest or template users not to be allowed to be loggeed into directly, never uncovered this one.

**Comment by TheWitness** [comment]
This is a simple one liner on the drop down I think.

**Comment by TheWitness** [comment]
Is a bit less trivial than I though.

**Comment by TheWitness** [comment]
I've done a fix here.  I suspect there can be some consequences here if for some reason the user has already set the guest or template accounts as the same as the login or admin_user.  Though, I'm not sure if there is reason enough to do anything more than this.
