### ISSUE TITLE
Cacti shows status UP, but port is actualy DOWN.

### ISSUE THREAD

**Issue by TomSoftly** [Cacti/cacti#3863]
Can anybody help me how to fix it?

**Comment by zuka1337** [comment]
If you re-index de device it updates the port status.

Console->Management->Device->Select Device->Re-index-Device

**Comment by TomSoftly** [comment]
> I assume you're talking about data query ports status, not device status.

Yes, i'm talking about ports status, but can't find re-index device, sorry.

**Comment by TomSoftly** [comment]
I'll find! Thank you very much for help!

**Comment by zuka1337** [comment]
![image](https://user-images.githubusercontent.com/57998098/96157219-eec5e100-0f09-11eb-9769-784ae9e574d7.png)

Here you go.

**Comment by bmfmancini** [comment]
You can also re run the data query click the green refresh button next to
the data query
