### ISSUE TITLE
RRDfile Cleaner error with v1.12.14

### ISSUE THREAD

**Issue by oijkn** [Cacti/cacti#3872]
# Describe the bug

Using the utilities `RRDfile Cleaner` function from the GUI does not  remove automatically the RRD files.

## To Reproduce

1. Go to 'Utilities->System Utilities->RRDfile Cleaner'

2. Click on 'Rescan->Delete All'

## Expected behavior

This function is supposed to delete the RRD files not used by the graphs but the deletion is not done correctly.

## Screenshots

![image](https://user-images.githubusercontent.com/18188407/96505287-332ce600-1256-11eb-9b8c-444de28fe2dd.png)

## Desktop (please complete the following information)

- OS: FreeBSD - 12.1-RELEASE-p6

- Browser: FireFox (v81)

- Cacti: v1.12.14

Thank you for your support.

BR

**Comment by TheWitness** [comment]
Pretty sure that this is fixed in the 1.2.x branch already.  Update your poller_maintenance.php from the 1.2.x branch and test.

**Comment by oijkn** [comment]
I've updated the poller_maintenance.php from the 1.2.X branch and now the error is in another line.
After checking in my server, the RRD files are not deleted immediately when I click on delete button (maybe this is done during the polling cycle).

![image](https://user-images.githubusercontent.com/18188407/96506935-bd764980-1258-11eb-9408-f76676abae29.png)

**Comment by TheWitness** [comment]
Okay, cool.  The files are staged for removal, and removed during the next poller cycle by default.

**Comment by TheWitness** [comment]
Well, you are not on the 1.2.x branch but something else.  So, slow down a little.  You can do this from your shell (assuming /var/www/html):

```
cd /var/www/html
git clone -b 1.2.x https://github.com/Cacti/cacti.git some_directory
cp -p some_directory/poller_maintenance.php /var/www/html/cacti
```

**Comment by oijkn** [comment]
Indeed you were right, by doing the manipulation directly from the shell I don't see any more error message in the logs, well done thank you !
