### ISSUE TITLE
Poller Last Sync N/A

### ISSUE THREAD

**Issue by zuka1337** [Cacti/cacti#3873]
# Describe the bug

Poller Last Sync is not updating status..
I've tested with:
 
-   Poller Sync Interval set to 2h 
-    Manual Sync

## To Reproduce

Select poller of your choice than chose Full Sync.
Result:
![image](https://user-images.githubusercontent.com/57998098/96565583-77eb6800-12bc-11eb-9a85-4019865cf5d3.png)

## Expected behavior

![image](https://user-images.githubusercontent.com/57998098/96565494-54c0b880-12bc-11eb-883c-6529c3b5185e.png)

The only log avalibale:

```
2020-10-20 10:06:20 - WEBUI NOTE: All selected Remote Data Collectors in [] synchronized correctly by user admin
2020-10-20 09:41:07 - WEBUI NOTE: All selected Remote Data Collectors in [] synchronized correctly by user admin

```

Cacti Version: 1.2.14

**Comment by TheWitness** [comment]
This is not a bug.  The main poller does not sync with itself.

**Comment by zuka1337** [comment]
Thank you !
