### ISSUE TITLE
The SHIFT functionnality in graphs does not accept negative values

### ISSUE THREAD

**Issue by DebugBill** [Cacti/cacti#3874]
When using the "shift data" option for a graph item, negative values if entered are ignored. Still they are valid in RDDTOOL and work fine.

In order to fix this bug I only replaced in 4 places in lib/rrd.php 
if ($graph_item['shift'] == CHECKED && $graph_item['value'] > 0)
with
if ($graph_item['shift'] == CHECKED && abs($graph_item['value']) > 0)

Fixed file is attached, renamed to rrd.php.txt

[rrd.php.txt](https://github.com/Cacti/cacti/files/5408516/rrd.php.txt)

**Comment by TheWitness** [comment]
How about a pull request off the 1.2.x branch?

**Comment by DebugBill** [comment]
Well, I am not a developper nor a regular contributor so I thought it would be easier that way.... The fixed file is attached to this report. I'm happy to have anybody cot/paste it to its own directory and claim the job is his own. :-)
