### ISSUE TITLE
PHP Parse error:  after update to 1.3.0

### ISSUE THREAD

**Issue by Tehrasha** [Cacti/cacti#3882]
Attempting to update Cacti from 1.1.28 to 1.3.0 to fix the Timestamp bug
After following upgrade instructions, made sure all file permissions match the working install.

Result is 500 Internal Server Error

apache2/error.log contains
PHP Parse error:  syntax error, unexpected ':', expecting '{' in /var/www/cacti/lib/functions.php on line 32

lib/functions.php ... starting Line 32
```
function title_trim(string $text, int $max_length): string {
        if (strlen($text) > $max_length) {
                return mb_substr($text, 0, $max_length) . '...';
        }

        return $text;
}
```

OS is Ubuntu server 14.04.5 LTS
PHP is v5.5.9-1ubuntu4.29

**Comment by TheWitness** [comment]
@Tehrasha, the 1.3 branch requires PHP7.2+.  So, upgrade your PHP, and you should be fine.  Otherwise, stick with the 1.2.x branch which will maintain PHP5.4++ compatibility.
