### ISSUE TITLE
Need help, WARNING: Poller Output Table not Empty

### ISSUE THREAD

**Issue by Harry-Om** [Cacti/cacti#3886]
2020/10/27 09:40:01 - POLLER: Poller[1] WARNING: Poller Output Table not Empty.  Issues: 79, DS[56443, 56445, 56439, 56438, 56439, 64243, 57867, 62087, 39245, 56444, 49782, 56441, 56442, 39252, 29143, 39245, 29144, 39250, 29142, 39244], Additional Issues Remain.  Only showing first 20

OS=Centos7
Cacti=1.2.14

**Comment by bmfmancini** [comment]
Please move this to the forums this is likley due to your poller timing out or a network side issue where devices are timing out
