### ISSUE TITLE
Translation issue | Englisch > German | 

### ISSUE THREAD

**Issue by C00kiekiller** [Cacti/cacti#3889]
Hi there,

the german translation has an mistake.

Version 1.2.14

"**Console**" > "**Sites**" > "**New Site**"

**Issue:**
Englisch > German
State > Zustand

**Expected:**
State > Bundesland

Best regards, 
C00kie

**Comment by TheWitness** [comment]
Are you interested with helping on translating?  We have a site setup that allows you to do so.

**Comment by C00kiekiller** [comment]
> Are you interested with helping on translating? We have a site setup that allows you to do so.

Yeah, sure, why not. :-)

**Comment by TheWitness** [comment]
@netniV or @cigamit, can you get @C00kiekiller setup on https://translate.cacti.net for the German Translation?

**Comment by C00kiekiller** [comment]
Hi,

I can't register an account on https://translate.cacti.net/.
The confirmation mail is missing.

After filling out the contact form to report an issue with the registration I receive the following error.

Internal Server Error
Server Error
The server had serious problems serving your request. Trained monkeys are en-route fixing the issue.


Best regards,
C00kie

**Comment by TheWitness** [comment]
Okay, interesting.  Let's see what @netniV and @cigamit say.

**Comment by TheWitness** [comment]
@cigamit fixed the issue.  Try registering again.

**Comment by C00kiekiller** [comment]
@cigamit @TheWitness Registration done at https://translate.cacti.net/.

Username: C00kiekiller

**Comment by TheWitness** [comment]
Cool, tool around the interface.  The first thing it'll have you do is select the languages that you want to work with.  The Cacti Translation is called "core".  I believe there is a translation section for the 1.2.x branch, as well as the develop branch.  When you find a string, you can see how it was translated in other places where it was used, "plugins" for example, and when you save an updated string, you can confirm that the translation was accurate.  When you do that, the system will automatically push your updates into our GitHub repository.  So, no pull requests required.  Just translate as you go, and the Cacti core, and all the plugin strings you confirm will go strait into GitHub.

**Comment by C00kiekiller** [comment]
Hi,

i've already tried it but it was not allowed to edit or save anyting.
Insufficient privileges for saving translantions & adding suggestions.

Screenshot: 
https://ibb.co/hgFZB3w

**Comment by TheWitness** [comment]
Yea, there are some permissions problems.  I've reached out to @cigamit to see if he can get it fixed.

**Comment by TheWitness** [comment]
@cigamit fixed it.  Knock yourself out.  Looking forward to seeing progress and thnaks!

**Comment by C00kiekiller** [comment]
@TheWitness @cigamit 
Hi,

I've logged out cleared chache and deleted all cookies but still no rights to save or change any translations.

**Comment by TheWitness** [comment]
Yea, there is a permission error on the system.  That is blocking the flow.  @cigamit will look at it again this morning.  Review this video for the translations process.  When you believe a string is accurately translated, uncheck the "Needs editing" checkbox and save.  At that point, the translation will appear when you change your default language.  As mentioned before, you can also see what other plugins have the same string and edit those on the fly, or to use the values that that may already be correct.

In the video below, I demonstrated unchecking the value and saving.  So, that much is working.  @cigamit will get the backend right.

![YourTranslations](https://user-images.githubusercontent.com/1439914/97705770-fd280700-1a8a-11eb-94f0-9939691fb599.gif)

**Comment by TheWitness** [comment]
That was all done using a user with your exact permissions.

**Comment by TheWitness** [comment]
Looks like you are cooking with gas now (aka working), and thanks again.
