### ISSUE TITLE
Single sorting of IP column is not working correctly on the Automation-> Discovered Devices page

### ISSUE THREAD

**Issue by JamesTilt** [Cacti/cacti#3891]
# IP sorting on a single column is not displaying properly

When sorting a single column on the Automation->Discovered Devices page the IP addresses do not sort properly.

- 192.168.2.10
- 192.168.2.100
- 192.168.2.22

Should be sorting

- 192.168.2.10
- 192.168.2.22
- 192.168.2.100

It works with multisort and also if the IP was the last sort left on the page and returning to the page the sort works properly.

## To Reproduce

1. Go to Automation link and then choose discovered devices

2. Click on IP field 

4. See sorting is incorrect for IP addresses

## Expected behavior

See above for expected IP sorting

## Notes

I have already started the pull request process.

**Comment by TheWitness** [comment]
Just like all the others, just add the one line showing this pull request as the id with the pull requests description.
