### ISSUE TITLE
Cacti v1.2.14: Realtime graph pop up counter bug.

### ISSUE THREAD

**Issue by iskandarbasman** [Cacti/cacti#3892]
# Describe the bug

Cacti v1.2.14: Realtime graph pop up counter does not count down on modern browsers. eg. Firefox, Chrome, Microsoft Edge (Chromium), Opera.

## To Reproduce

1. Go to 'Any graph.'

2. Click on 'Time Graph View'
![image](https://user-images.githubusercontent.com/67727557/97542276-6f540980-1a01-11eb-855f-002679018af1.png)

3. At graph_view.php. Click on 'Real time graph icon'
![image](https://user-images.githubusercontent.com/67727557/97542440-b0e4b480-1a01-11eb-9c90-84f8571f4ec5.png)

4. Real time graph pop up appears. Counter is stuck and does not count down.
![image](https://user-images.githubusercontent.com/67727557/97542560-eb4e5180-1a01-11eb-9254-fa8972eddfa5.png)

## Expected behavior

Counter should count down and refresh after hitting 0 seconds.

## Screenshots

Screenshots above.

## Additional context

The bug seems to happen on all modern browsers as mentioned before.
**Interesting the counter count down still works for Classic Internet Explorer.**

This Cacti was upgraded from v1.1.38 to v1.2.14.
Verify that other Cacti that have fresh install with v1.2.13 does not have this bug.

Also found that for Firefox if take the URL for the POP eg. "cacti/cacti/graph_realtime.php?top=0&left=0&local_graph_id=59"
And paste it on a new window, the counter works and it refresh.
This method does not work with Microsoft Edge Chromium or Opera.

**Comment by EmilAndersson-SE** [comment]
This is the same as we was hitting here https://github.com/Cacti/cacti/issues/3847

**Comment by iskandarbasman** [comment]
> 
> 
> This is the same as we was hitting here #3847

So apparently this issue also happens on a Ubuntu server. Common point is Cacti v1.2.14.

**Comment by TheWitness** [comment]
Letting @paulgevers know this.  It's about a Web Server configuration item that error message.

**Comment by jdcoats** [comment]
works fine for me

**Comment by TheWitness** [comment]
Yea, it's a web server config issue, or an chrome add-on or Cacti plugin throwing a JavaScript error.  I've confirmed it's working fine.

**Comment by iskandarbasman** [comment]
@TheWitness  can we reopen this issue ? I just did an upgrade for one my cactis to from v1.2.13 v1.2.15 and the same problem happens for real time graph. 
I verified that this problem was not happening for v1.2.13.
No change in the server side config. Standard Centos 7 installation.

**Comment by TheWitness** [comment]
Open the separate window, and then press F12 to open the debug window, the go-to setting and put it in a separate window.  The once the real-time debug window is open, click on it's console table.  Once there go back to the real-time window and hit F5.  Look in the console for JavaScript errors, post them here.

**Comment by iskandarbasman** [comment]
@TheWitness 
A bit hard to get it since it tends to happen on the initial click.
Reloading the window seems get the script to start most of the time.
This is for Cacti v1.2.14.

For cacti v1.2.1.15 reloading the window seems to resolve the issue.

![image](https://user-images.githubusercontent.com/67727557/97967368-1668e480-1df8-11eb-9f77-b9421349b8f0.png)

**Comment by EmilAndersson-SE** [comment]
I can't see there is a server-problem either. It works on 1.2.10, after upgrade to 1.2.14 its not autorefreshing in the popup. And then downgrade to 1.2.10 it works as expected. On the same server and without changes on Apache, PHP or MariaDB at all.

**Comment by netniV** [comment]
You seem to be getting a lot of errors there but the most fundemental, to me, is that it states you are using cross-site and that suggest you are not using the url/domain that Cacti thinks you should be running.  Additioanlly, there seem to be dropped declarations which seem wrong, can you get more detail on those?

**Comment by iskandarbasman** [comment]
This is error output I managed to get on a different Cacti v1.2.15 install.
Get this errors on the initial click.
F5 gets the pop up to refresh properly.

> 
> 08:33:39.393 This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. graph_realtime.php
> 08:33:51.341 Error in parsing value for ‘background’.  Declaration dropped. graph_realtime.php:1:96
> Elements matching selector: .jqstooltip
> NodeList []
> ​
> length: 0
> ​
> <prototype>: NodeListPrototype { item: item(), keys: keys(), values: values(), … }
> 08:33:51.341 Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped. graph_realtime.php:1:150
> Elements matching selector: .jqstooltip
> NodeList []
> 08:33:51.398 Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. jquery.zoom.css:10:9
> Elements matching selector: #zoom-box
> NodeList []
> 08:33:51.398 Unknown property ‘-moz-opacity’.  Declaration dropped. jquery.zoom.css:11:15
> 08:33:51.398 Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. jquery.zoom.css:33:9
> 08:33:51.399 Unknown property ‘-moz-opacity’.  Declaration dropped. jquery.zoom.css:34:15
> 08:33:51.399 Unknown property ‘-moz-box-shadow’.  Declaration dropped. jquery.zoom.css:44:18
> 08:33:51.399 Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. jquery.zoom.css:54:9
> 08:33:51.399 Unknown property ‘-moz-opacity’.  Declaration dropped. jquery.zoom.css:55:15
> 08:33:51.399 Unknown property ‘-moz-box-shadow’.  Declaration dropped. jquery.zoom.css:65:18
> 08:33:51.400 Expected ‘none’, URL, or filter function but found ‘Alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. jquery-ui.css:52:9
> 08:33:51.400 Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. jquery-ui.css:680:10
> Elements matching selector: .ui-progressbar .ui-progressbar-overlay
> NodeList []
> ​
> length: 0
> ​
> <prototype>: NodeListPrototype { item: item(), keys: keys(), values: values(), … }
> 08:33:51.400 Expected ‘none’, URL, or filter function but found ‘Alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. jquery-ui.css:1044:9
> 08:33:51.400 Expected ‘none’, URL, or filter function but found ‘Alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. jquery-ui.css:1051:9
> 08:33:51.400 Expected ‘none’, URL, or filter function but found ‘Alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. jquery-ui.css:1055:9
> 08:33:51.401 Expected ‘none’, URL, or filter function but found ‘Alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. jquery-ui.css:1307:10
> 08:33:51.402 Unknown property ‘-moz-box-shadow’.  Declaration dropped. style.css:119:19
> 08:33:51.402 Unknown property ‘-moz-text-shadow’.  Declaration dropped. style.css:147:20
> 08:33:51.402 Unknown property ‘-moz-border-radius’.  Declaration dropped. style.css:150:22
> 08:33:51.402 Unknown property ‘-moz-box-shadow’.  Declaration dropped. style.css:157:19
> 08:33:51.402 Unknown property ‘-moz-box-shadow’.  Declaration dropped. style.css:172:19
> 08:33:51.402 Unknown property ‘-moz-text-shadow’.  Declaration dropped. style.css:187:20
> 08:33:51.402 Unknown property ‘-moz-box-shadow’.  Declaration dropped. style.css:190:19
> 08:33:51.402 Unknown property ‘-moz-border-radius’.  Declaration dropped. style.css:193:22
> 08:33:51.402 Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped. style.css:389:11
> 08:33:51.404 Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. jquery.colorpicker.css:233:14
> 08:33:51.404 Unknown property ‘-moz-box-shadow’.  Declaration dropped. c3.css:112:19
> 08:33:51.408 Error in parsing value for ‘box-shadow’.  Declaration dropped. pace.css:30:47
> 08:33:51.408 Unrecognized at-rule or error parsing at-rule ‘@-o-keyframes’. pace.css:66:14
> 08:33:51.408 Unrecognized at-rule or error parsing at-rule ‘@-ms-keyframes’. pace.css:70:15
> 08:33:51.409 Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. all.css:11:27
> 08:33:51.415 Error in parsing value for ‘align-self’.  Declaration dropped. main.css:309:14
> 08:33:51.415 Error in parsing value for ‘border-color’.  Declaration dropped. main.css:1676:25
> 08:33:51.415 Unknown property ‘zoom’.  Declaration dropped. main.css:1752:7
> 08:36:56.716 Navigated to https://cacti.sptel.com/cacti/graph_realtime.php?top=0&left=0&local_graph_id=213
> 08:36:56.718 GEThttps://cacti.sptel.com/cacti/graph_realtime.php?top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 129ms]
> 
> 08:36:56.829 This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. graph_realtime.php
> 08:36:56.838 GEThttps://cacti.sptel.com/cacti/include/js/jquery.js?23c7c5d2d1317508e807a6c7f777d6ed
> [HTTP/1.1 304 Not Modified 10ms]
> 
> 08:36:56.838 GEThttps://cacti.sptel.com/cacti/include/js/screenfull.js?60a2ad1d452950179fa4d2c5d1b5dee4
> [HTTP/1.1 304 Not Modified 0ms]
> 
> 08:36:56.848 GEThttps://cacti.sptel.com/cacti/include/js/jquery.ui.touch.punch.js?4195aad6f616651c00557e84c6721646
> [HTTP/1.1 304 Not Modified 49ms]
> 
> 08:36:56.848 GEThttps://cacti.sptel.com/cacti/include/js/jquery-ui.js?f1f075fe32aca8216e55c5d00106fba7
> [HTTP/1.1 304 Not Modified 44ms]
> 
> 08:36:56.858 GEThttps://cacti.sptel.com/cacti/include/js/jquery.cookie.js?0b804d4f90de70b032a9986b22165b75
> [HTTP/1.1 304 Not Modified 10ms]
> 
> 08:36:56.865 GEThttps://cacti.sptel.com/cacti/include/js/js.storage.js?32df3a56e44d570b7e3177d71e892214
> [HTTP/1.1 304 Not Modified 49ms]
> 
> 08:36:56.868 GEThttps://cacti.sptel.com/cacti/include/js/jstree.js?5860ff24b1d515787567add634c909db
> [HTTP/1.1 304 Not Modified 15ms]
> 
> 08:36:56.870 GEThttps://cacti.sptel.com/cacti/include/js/jquery.hotkeys.js?fbf82bcab286e9fc5cdf863eb067230f
> [HTTP/1.1 304 Not Modified 59ms]
> 
> 08:36:56.871 GEThttps://cacti.sptel.com/cacti/include/js/jquery.tablednd.js?a33b14ebf8ce2abf7911e62cbc19e0c5
> [HTTP/1.1 304 Not Modified 13ms]
> 
> 08:36:56.877 GEThttps://cacti.sptel.com/cacti/include/js/jquery.zoom.js?8959c773f870ad8daf1b225bfadaa0d2
> [HTTP/1.1 304 Not Modified 11ms]
> 
> 08:36:56.880 GEThttps://cacti.sptel.com/cacti/include/js/jquery.multiselect.js?4a409cc12d02ac72805c8aa463b4b069
> [HTTP/1.1 304 Not Modified 10ms]
> 
> 08:36:56.885 GEThttps://cacti.sptel.com/cacti/include/js/jquery.multiselect.filter.js?ccf700b33985626742e26c6707028bed
> [HTTP/1.1 304 Not Modified 48ms]
> 
> 08:36:56.888 GEThttps://cacti.sptel.com/cacti/include/js/jquery.timepicker.js?f29132ab24085f909242175ad11cfcbc
> [HTTP/1.1 304 Not Modified 5ms]
> 
> 08:36:56.889 GEThttps://cacti.sptel.com/cacti/include/js/jquery.colorpicker.js?3b7032780b24b9b48050e5d245a36260
> [HTTP/1.1 304 Not Modified 5ms]
> 
> 08:36:56.891 GEThttps://cacti.sptel.com/cacti/include/js/jquery.tablesorter.js?8d331985e11cfc65649a915073cb30ed
> [HTTP/1.1 304 Not Modified 5ms]
> 
> 08:36:56.893 GEThttps://cacti.sptel.com/cacti/include/js/jquery.tablesorter.widgets.js?3cc0d7b3426e1db1e4a099db18b17e3c
> [HTTP/1.1 304 Not Modified 5ms]
> 
> 08:36:56.899 GEThttps://cacti.sptel.com/cacti/include/js/jquery.tablesorter.pager.js?8ca32d30195c98492cd028f582f07c8c
> [HTTP/1.1 304 Not Modified 5ms]
> 
> 08:36:56.901 GEThttps://cacti.sptel.com/cacti/include/js/jquery.sparkline.js?c7638b825bc7deb1cf58c990825d35b2
> [HTTP/1.1 304 Not Modified 8ms]
> 
> 08:36:56.902 GEThttps://cacti.sptel.com/cacti/include/js/Chart.js?ae4cd3db34d0ea7ea1a9596d5d4120e6
> [HTTP/1.1 304 Not Modified 7ms]
> 
> 08:36:56.905 GEThttps://cacti.sptel.com/cacti/include/js/dygraph-combined.js?b5b448f71f8c3eb4a39506299bd81b0c
> [HTTP/1.1 304 Not Modified 7ms]
> 
> 08:36:56.907 GEThttps://cacti.sptel.com/cacti/include/js/d3.js?6db1c8feb22917c88023d14370218d26
> [HTTP/1.1 304 Not Modified 7ms]
> 
> 08:36:56.908 GEThttps://cacti.sptel.com/cacti/include/js/c3.js?4475647e3aea91584750d4726c065ccd
> [HTTP/1.1 304 Not Modified 7ms]
> 
> 08:36:56.935 GEThttps://cacti.sptel.com/cacti/include/layout.js?2d9642b1d467930313656a0f31d5a654
> [HTTP/1.1 304 Not Modified 6ms]
> 
> 08:36:56.938 GEThttps://cacti.sptel.com/cacti/include/js/pace.js?30fbf6c62d78d3367fa50bd51913200c
> [HTTP/1.1 304 Not Modified 5ms]
> 
> 08:36:56.939 GEThttps://cacti.sptel.com/cacti/include/realtime.js?067cb141f44c0c8fd518f60c7e37809a
> [HTTP/1.1 304 Not Modified 6ms]
> 
> 08:36:56.946 GEThttps://cacti.sptel.com/cacti/include/themes/classic/main.js?3f53c496f650f4b49bd37d85fe97771d
> [HTTP/1.1 304 Not Modified 6ms]
> 
> 08:36:56.947 GEThttps://cacti.sptel.com/cacti/include/vendor/csrf/csrf-magic.js
> [HTTP/1.1 304 Not Modified 6ms]
> 
> 08:36:57.057 Error in parsing value for ‘background’.  Declaration dropped. graph_realtime.php:1:96
> 08:36:57.057 Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped. graph_realtime.php:1:150
> 08:36:57.116 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=init&top=0&left=0&local_graph_id=213&graph_start=-60&ds_step=1&count=0&size=100&graph_nolegend=false
> [HTTP/1.1 200 OK 368ms]
> 
> 08:36:57.215 GEThttps://cacti.sptel.com/cacti/include/themes/classic/images/cacti_logo.gif
> [HTTP/1.1 200 OK 0ms]
> 
> 08:36:57.217 GEThttps://cacti.sptel.com/cacti/include/themes/classic/images/favicon.ico
> [HTTP/1.1 200 OK 0ms]
> 
> 08:36:58.056 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 363ms]
> 
> 08:37:00.061 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 373ms]
> 
> 08:37:02.068 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 460ms]
> 
> 08:37:04.118 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 360ms]
> 
> 08:37:06.128 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 350ms]
> 
> 08:37:08.158 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 411ms]
> 
> 08:37:10.179 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 349ms]
> 
> 08:37:12.209 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 380ms]
> 
> 08:37:14.249 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 350ms]
> 
> 08:37:16.278 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 350ms]
> 
> 08:37:18.313 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 355ms]
> 
> 08:37:20.348 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 371ms]
> 
> 08:37:22.378 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 370ms]
> 
> 08:37:24.399 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 359ms]
> 
> 08:37:26.431 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 357ms]
> 
> 08:37:28.469 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 359ms]
> 
> 08:37:30.499 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 379ms]
> 
> 08:37:32.519 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 379ms]
> 
> 08:37:34.558 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 370ms]
> 
> 08:37:36.559 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 349ms]
> 
> 08:37:38.581 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 357ms]
> 
> 08:37:40.619 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 369ms]
> 
> 08:37:42.639 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 370ms]
> 
> 08:37:44.679 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 369ms]
> 
> 08:37:46.718 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 360ms]
> 
> 08:37:48.758 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 361ms]
> 
> 08:37:50.799 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 360ms]
> 
> 08:37:52.838 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 371ms]
> 
> 08:37:54.869 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 380ms]
> 
> 08:37:56.908 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 370ms]
> 
> 08:37:58.950 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 348ms]
> 
> 08:38:00.989 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 379ms]
> 
> 08:38:03.018 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 390ms]
> 
> 08:38:05.049 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 379ms]
> 
> 08:38:07.089 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 369ms]
> 
> 08:38:09.119 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 369ms]
> 
> 08:38:11.148 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 392ms]
> 
> 08:38:13.178 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 370ms]
> 
> 08:38:15.219 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 379ms]
> 
> 08:38:17.238 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 350ms]
> 
> 08:38:19.278 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 370ms]
> 
> 08:38:21.308 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 353ms]
> 
> 08:38:23.339 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 359ms]
> 
> 08:38:25.379 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 591ms]
> 
> 08:38:27.409 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 380ms]
> 
> 08:38:29.428 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 360ms]
> 
> 08:38:31.458 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 380ms]
> 
> 08:38:33.479 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 360ms]
> 
> 08:38:35.518 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 360ms]
> 
> 08:38:37.553 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 366ms]
> 
> 08:38:39.579 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 360ms]
> 
> 08:38:41.613 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 366ms]
> 
> 08:38:43.648 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 360ms]
> 
> 08:38:45.679 XHRGEThttps://cacti.sptel.com/cacti/graph_realtime.php?action=countdown&top=0&left=0&local_graph_id=213
> [HTTP/1.1 200 OK 349ms]
> 
>

**Comment by jdcoats** [comment]
If you add cacti url cacti.sptel.com to trusted sites and allow allow cross site scripting does it work?

**Comment by jdcoats** [comment]
another thing to try that would prove a server side issue is to link the cacti/include dir to the http root dir
 so the include dir exists in the www root dir.
```
# /var/www/htdocs # ls -al
total 61675
drwxr-xr-x 14 root   root       1112 Nov  2 10:00 .
drwxr-xr-x  8 root   root        200 Nov  2 09:54 ..
drwxr-xr-x 18 apache apache     3648 Oct 20 18:33 cacti
lrwxrwxrwx  1 root   root         39 Apr 14  2014 include -> /var/www/htdocs/cacti/include
```

**Comment by netniV** [comment]
The CSS warnings are because of the use of the `zoom:` attribute, which is prevalant, not just in our own things but in third parties too:

```css
include/themes/dark/main.css:	zoom: 1;
include/themes/classic/main.css:	zoom: 1;
include/js/d3.js:    zoom: function(key, transform) {
include/js/c3.js:      zoom_onzoom: function zoom_onzoom() {},
include/js/jquery-ui.js:				zoom: 1,
plugins/npc/js/ext/resources/css/core.css:    zoom: 1;
plugins/npc/js/ext/resources/css/core.css:    zoom: 1;
plugins/npc/js/ext/resources/css/core.css:    zoom: 1;
plugins/npc/js/ext/resources/css/core.css:    zoom: 1;
plugins/npc/js/ext/resources/css/core.css:    zoom: 1;
plugins/npc/js/ext/resources/css/core.css:    zoom: 1;
plugins/npc/js/ext/resources/css/menu.css:	zoom: 1;
```

So, whilst two of our themes actively use the zoom attribute, third party styles use it quote a lot too.  I'm guessing they all need to be updated but that's out of our hands especially on debian-based systems where the package maintainers actively remove included packages in place of pre-built ones.

That shouldn't, however, stop your timers from working.

**Comment by iskandarbasman** [comment]
@jdcoats 
Not sure my the bug keep happening consistently today.
Going to try a different laptop after this.

I tried adding the following in firefox but it still persists.
Add the sym link for include as well. (What is this for ?)
My cacti directory currently is not in www root.

![image](https://user-images.githubusercontent.com/67727557/98061227-5d052000-1e86-11eb-836d-7d4935d924c7.png)
![image](https://user-images.githubusercontent.com/67727557/98061284-78702b00-1e86-11eb-914e-37cf889d6bbd.png)



> drwxrwxr-x    17 spteladmin spteladmin     4096 Nov  2 11:26 cacti
> lrwxrwxrwx     1 root       root             24 Nov  4 10:04 include -> /usr/share/cacti/include

> total 4
> drwxr-xr-x. 2 root root 38 Nov  4 10:22 .
> drwxr-xr-x. 4 root root 33 Jun 26 20:55 ..
> lrwxrwxrwx  1 root root 24 Nov  4 10:22 include -> /usr/share/cacti/include
> -rw-r--r--  1 root root  5 Nov  4 10:17 test.html

**Comment by iskandarbasman** [comment]
I am not too sure but I suspect this bug tends to happen when you have two different cacti loaded on your browser.
On another laptop it initially loaded correctly on click consistently.
But after I logged into another cacti on the same browser. It started to become inconsistent again.

**Comment by TheWitness** [comment]
Well, that is new information.

**Comment by iskandarbasman** [comment]
@TheWitness @EmilAndersson-SE 
Send you the credentials to my test cacti v1.2.15 i just brought up.
Hard to pin point what causes this issue. 
It just happens.

Let me know if anyone else wants access.
