### ISSUE TITLE
1.2.14 - cannot view any tree other than default tree

### ISSUE THREAD

**Issue by fatbob45** [Cacti/cacti#3893]
fresh install of 1.2.14 on centOS 8 (rebuilding as opposed to upgrading from 0.8.8). stupid 1st problem. created and published a tree (with graphs inside - just in case). but clicking on graphs only shows 'Default tree'. i am admin with full rights everywhere
must apologise for opening a ticket for this issue and the solution will undoubtedly be incompetance but i've been playing with this for 2 hours and no way to display.
thx,
al

**Comment by zuka1337** [comment]
hello @fatbob45, if you click on preview are you able to search for the graphs?

**Comment by zuka1337** [comment]
Maybe is related to this #3849

**Comment by fatbob45** [comment]
slightly weird but figured out that i can only publish when editing the tree. nothing else works. thanks fo rthe reply.
