### ISSUE TITLE
Import template in 1.2.14 is broken

### ISSUE THREAD

**Issue by xmacan** [Cacti/cacti#3894]
Export template from 1.2.14 and try to import to other 1.2.14 via GUI, got error **XML parse error.** 
In cli:
[root@cacti /usr/local/share/cacti/cli]# php -q import_template.php --filename=/home/pm/cacti_host_template_nas_device_synology_qnap_nas4free.xml               
Read 223347 bytes of XML data

In cli it is without error but template isn't imported.

**Comment by TheWitness** [comment]
Yea, update the lib/import.php from the 1.2.x branch.  This issue is resolved now.  Verify and then if clear, close.

**Comment by xmacan** [comment]
Thank you, working
