### ISSUE TITLE
Upgrade 0.8.8 to 1.2.14 - SQL Syntax Error

### ISSUE THREAD

**Issue by krytosvirus** [Cacti/cacti#3895]
# Describe the bug
After doing OS upgrades (php5 to php7.4, mysql to version 8, many other related system packages) I get an error on the final bits of the upgrade of Cacti in the web based upgrade process. The pertinent cacti.log info

- 2020-10-30 12:56:05 - INSTALL: always: Switched from  to /tmp/cdungOIeQ
- 2020-10-30 12:56:05 - INSTALL: always: NOTE: Using temporary file for db cache: /tmp/cdungOIeQ
- 2020-10-30 12:56:05 - INSTALL: always: Upgrading from v0.8.8c (DB 1.2.14 (DB: 0.8.8c)) to v1.0.0
- 2020-10-30 12:56:07 - CMDPHP ERROR: A DB Exec Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'system=1 WHERE name LIKE '\_%'' at line 1
- 2020-10-30 12:56:07 - CMDPHP SQL Backtrace:  (/install/background.php[54]:Installer::beginInstall(), /lib/installer.php[3387]:Installer->install(), /lib/installer.php[2892]:Installer->upgradeDatabase(), /lib/installer.php[3286]:upgrade_to_1_0_0(), /install/upgrades/1_0_0.php[1540]:db_install_execute(), /install/functions.php[136]:db_execute_prepared())
- 2020-10-30 12:56:12 - INSTALL: always: Finished UPGRADE Process for v1.2.14
- 2020-10-30 12:56:12 - INSTALL: always: WARNING: One or more upgrades failed to install correctly
- 2020-10-30 12:56:12 - INSTALL: always: Installation was started at 2020-10-30 17:55:59, completed at 2020-10-30 17:56:12

This is related some changes in MySQL 8 making certain words reserved keywords, in this case "system" being one of them.

This was my fix

```
--- upgrades/1_0_0.php.bak      2020-10-30 14:36:02.421667690 -0500
+++ upgrades/1_0_0.php  2020-10-30 14:32:07.562672119 -0500
@@ -1537,7 +1537,7 @@
 
        // Update Aggregate CDEFs to become system level
        db_install_add_column('cdef', array('name' => 'system', 'type' => 'mediumint(8) unsigned', 'NULL' => false, 'default' => '0', 'after' => 'hash'));
-       db_install_execute("UPDATE cdef SET system=1 WHERE name LIKE '\_%'");
+       db_install_execute("UPDATE cdef SET cdef.system=1 WHERE name LIKE '\_%'");
 
        // Add some important missing indexes
        db_install_add_key('data_local', 'INDEX', 'data_template_id', array('data_template_id'));

```

**Comment by TheWitness** [comment]
This has already been resolved in the upcoming 1.2.15 release.
