### ISSUE TITLE
Upgrade from 0.8 to 1.2.2 hangs at 60%

### ISSUE THREAD

**Issue by huaraz** [Cacti/cacti#3896]
I have upgraded my raspberry Pi to buster and as part of it cacti was upgraded to 1.2.2. I followed the wizard but it hangs at 60%.  is this a known bug ? 

Installing Cacti Server v1.2.2
Your Cacti Server is now installing

Refresh in	 	ProgressLast updated: 13:10:04
 	
60 %
2020/11/01 13:10:02 - INSTALL: always: Upgrading from v0.8.8b (DB 1.2.2 (DB: 0.8.8b)) to v1.0.0
2020/11/01 13:10:02 - INSTALL: always: NOTE: Using temporary file for db cache: /tmp/cduCUucMF
2020/11/01 13:10:02 - INSTALL: always: Switched from /tmp/cdujPC6u8 to /tmp/cduCUucMF
2020/11/01 13:10:02 - INSTALL: always: Converting Table #101 'version'
2020/11/01 13:10:02 - INSTALL: always: Converting Table #100 'user_log'
2020/11/01 13:10:02 - INSTALL: always: Converting Table #99 'user_domains_ldap'
2020/11/01 13:10:01 - INSTALL: always: Converting Table #98 'user_domains'
2020/11/01 13:10:01 - INSTALL: always: Converting Table #97 'user_auth_realm'
2020/11/01 13:10:01 - INSTALL: always: Converting Table #96 'user_auth_perms'
2020/11/01 13:10:01 - INSTALL: always: Converting Table #95 'user_auth_group_realm'
2020/11/01 13:10:01 - INSTALL: always: Converting Table #94 'user_auth_group_perms'
2020/11/01 13:10:01 - INSTALL: always: Converting Table #93 'user_auth_group_members'
2020/11/01 13:10:01 - INSTALL: always: Converting Table #92 'user_auth_group'
2020/11/01 13:10:01 - INSTALL: always: Converting Table #91 'user_auth_cache'
2020/11/01 13:10:00 - INSTALL: always: Converting Table #90 'user_auth'
2020/11/01 13:10:00 - INSTALL: always: Converting Table #89 'snmpagent_notifications_log'
2020/11/01 13:10:00 - INSTALL: always: Converting Table #88 'snmpagent_mibs'
2020/11/01 13:10:00 - INSTALL: always: Converting Table #87 'snmpagent_managers_notifications'
2020/11/01 13:10:00 - INSTALL: always: Converting Table #86 'snmpagent_managers'
2020/11/01 13:10:00 - INSTALL: always: Converting Table #85 'snmpagent_cache_textual_conventions'
2020/11/01 13:10:00 - INSTALL: always: Converting Table #84 'snmpagent_cache_notifications'
2020/11/01 13:10:00 - INSTALL: always: Converting Table #83 'snmpagent_cache'
2020/11/01 13:10:00 - INSTALL: always: Converting Table #82 'snmp_query_graph_sv'
2020/11/01 13:09:59 - INSTALL: always: Converting Table #81 'snmp_query_graph_rrd_sv'
2020/11/01 13:09:59 - INSTALL: always: Converting Table #80 'snmp_query_graph_rrd'
2020/11/01 13:09:59 - INSTALL: always: Converting Table #79 'snmp_query_graph'
2020/11/01 13:09:59 - INSTALL: always: Converting Table #78 'snmp_query'
2020/11/01 13:09:59 - INSTALL: always: Converting Table #77 'settings_user_group'
2020/11/01 13:09:59 - INSTALL: always: Converting Table #76 'settings_user'
2020/11/01 13:09:59 - INSTALL: always: Converting Table #75 'settings_tree'
2020/11/01 13:09:59 - INSTALL: always: Converting Table #74 'settings'
2020/11/01 13:09:59 - INSTALL: always: Converting Table #73 'rra_cf'
2020/11/01 13:09:58 - INSTALL: always: Converting Table #72 'rra'
2020/11/01 13:09:58 - INSTALL: always: Converting Table #71 'reports_items'
2020/11/01 13:09:58 - INSTALL: always: Converting Table #70 'reports'
2020/11/01 13:09:58 - INSTALL: always: Converting Table #69 'poller_time'
2020/11/01 13:09:58 - INSTALL: always: Converting Table #68 'poller_reindex'
2020/11/01 13:09:58 - INSTALL: always: Converting Table #67 'poller_output_realtime'
2020/11/01 13:09:58 - INSTALL: always: Converting Table #66 'poller_output_boost_processes'
2020/11/01 13:09:58 - INSTALL: always: Converting Table #65 'poller_output_boost'
2020/11/01 13:09:58 - INSTALL: always: Converting Table #64 'poller_output'
2020/11/01 13:09:58 - INSTALL: always: Converting Table #63 'poller_item'
2020/11/01 13:09:57 - INSTALL: always: Converting Table #62 'poller_command'
2020/11/01 13:09:57 - INSTALL: always: Converting Table #61 'poller'
2020/11/01 13:09:57 - INSTALL: always: Converting Table #60 'plugin_realms'
2020/11/01 13:09:57 - INSTALL: always: Converting Table #59 'plugin_hooks'
2020/11/01 13:09:57 - INSTALL: always: Converting Table #58 'plugin_db_changes'
2020/11/01 13:09:57 - INSTALL: always: Converting Table #57 'plugin_config'
2020/11/01 13:09:57 - INSTALL: always: Converting Table #56 'host_template_snmp_query'
2020/11/01 13:09:57 - INSTALL: always: Converting Table #55 'host_template_graph'
2020/11/01 13:09:57 - INSTALL: always: Converting Table #54 'host_template'
2020/11/01 13:09:56 - INSTALL: always: Converting Table #53 'host_snmp_query'
2020/11/01 13:09:56 - INSTALL: always: Converting Table #52 'host_snmp_cache'
2020/11/01 13:09:56 - INSTALL: always: Converting Table #51 'host_graph'
2020/11/01 13:09:56 - INSTALL: always: Converting Table #50 'host'
2020/11/01 13:09:56 - INSTALL: always: Converting Table #49 'graph_tree_items'
2020/11/01 13:09:56 - INSTALL: always: Converting Table #48 'graph_tree'
2020/11/01 13:09:56 - INSTALL: always: Converting Table #47 'graph_templates_item'
2020/11/01 13:09:56 - INSTALL: always: Converting Table #46 'graph_templates_graph'
2020/11/01 13:09:56 - INSTALL: always: Converting Table #45 'graph_templates_gprint'
2020/11/01 13:09:55 - INSTALL: always: Converting Table #44 'graph_templates'
2020/11/01 13:09:55 - INSTALL: always: Converting Table #43 'graph_template_input_defs'
2020/11/01 13:09:55 - INSTALL: always: Converting Table #42 'graph_template_input'
2020/11/01 13:09:55 - INSTALL: always: Converting Table #41 'graph_local'
2020/11/01 13:09:55 - INSTALL: always: Converting Table #40 'data_template_rrd'
2020/11/01 13:09:55 - INSTALL: always: Converting Table #39 'data_template_data_rra'
2020/11/01 13:09:55 - INSTALL: always: Converting Table #38 'data_template_data'
2020/11/01 13:09:55 - INSTALL: always: Converting Table #37 'data_template'
2020/11/01 13:09:55 - INSTALL: always: Converting Table #36 'data_source_stats_yearly'
2020/11/01 13:09:54 - INSTALL: always: Converting Table #35 'data_source_stats_weekly'
2020/11/01 13:09:54 - INSTALL: always: Converting Table #34 'data_source_stats_monthly'
2020/11/01 13:09:54 - INSTALL: always: Converting Table #33 'data_source_stats_hourly_last'
2020/11/01 13:09:54 - INSTALL: always: Converting Table #32 'data_source_stats_hourly_cache'
2020/11/01 13:09:54 - INSTALL: always: Converting Table #31 'data_source_stats_hourly'
2020/11/01 13:09:54 - INSTALL: always: Converting Table #30 'data_source_stats_daily'
2020/11/01 13:09:54 - INSTALL: always: Converting Table #29 'data_source_purge_temp'
2020/11/01 13:09:54 - INSTALL: always: Converting Table #28 'data_source_purge_action'
2020/11/01 13:09:54 - INSTALL: always: Converting Table #27 'data_local'
2020/11/01 13:09:54 - INSTALL: always: Converting Table #26 'data_input_fields'
2020/11/01 13:09:53 - INSTALL: always: Converting Table #25 'data_input_data'
2020/11/01 13:09:53 - INSTALL: always: Converting Table #24 'data_input'
2020/11/01 13:09:53 - INSTALL: always: Converting Table #23 'colors'
2020/11/01 13:09:53 - INSTALL: always: Converting Table #22 'color_templates'
2020/11/01 13:09:53 - INSTALL: always: Converting Table #21 'color_template_items'
2020/11/01 13:09:53 - INSTALL: always: Converting Table #20 'cdef_items'
2020/11/01 13:09:53 - INSTALL: always: Converting Table #19 'cdef'
2020/11/01 13:09:53 - INSTALL: always: Converting Table #18 'automation_tree_rules'
2020/11/01 13:09:52 - INSTALL: always: Converting Table #17 'automation_tree_rule_items'
2020/11/01 13:09:52 - INSTALL: always: Converting Table #16 'automation_templates'
2020/11/01 13:09:52 - INSTALL: always: Converting Table #15 'automation_snmp_items'
2020/11/01 13:09:52 - INSTALL: always: Converting Table #14 'automation_snmp'
2020/11/01 13:09:52 - INSTALL: always: Converting Table #13 'automation_processes'
2020/11/01 13:09:52 - INSTALL: always: Converting Table #12 'automation_networks'
2020/11/01 13:09:52 - INSTALL: always: Converting Table #11 'automation_match_rule_items'
2020/11/01 13:09:52 - INSTALL: always: Converting Table #10 'automation_ips'
2020/11/01 13:09:52 - INSTALL: always: Converting Table #9 'automation_graph_rules'
2020/11/01 13:09:52 - INSTALL: always: Converting Table #8 'automation_graph_rule_items'
2020/11/01 13:09:51 - INSTALL: always: Converting Table #7 'automation_devices'
2020/11/01 13:09:51 - INSTALL: always: Converting Table #6 'aggregate_graphs_items'
2020/11/01 13:09:51 - INSTALL: always: Converting Table #5 'aggregate_graphs_graph_item'

The cacti.log says:

2020/11/01 13:10:02 - CMDPHP ERROR: A DB Cell Failed!, Error: Unknown column 'dbhost' in 'field list'
2020/11/01 13:10:02 - CMDPHP SQL Backtrace:  (/poller.php[147]:db_fetch_cell_prepared(), /lib/database.php[376]:db_execute_prepared())
2020/11/01 13:10:02 - CMDPHP ERROR: A DB Exec Failed!, Error: Unknown column 'dbhost' in 'field list'
2020/11/01 13:10:02 - CMDPHP SQL Backtrace:  (/poller.php[158]:db_execute_prepared())
2020/11/01 13:10:02 - CMDPHP ERROR: A DB Cell Failed!, Error: Unknown column 'disabled' in 'field list'
2020/11/01 13:10:02 - CMDPHP SQL Backtrace:  (/poller.php[172]:poller_enabled_check(), /poller.php[859]:db_fetch_cell_prepared(), /lib/database.php[376]:db_execute_prepared())
2020/11/01 13:10:02 - CMDPHP ERROR: A DB Cell Failed!, Error: Unknown column 'disabled' in 'where clause'
2020/11/01 13:10:02 - CMDPHP SQL Backtrace:  (/poller.php[187]:update_resource_cache(), /lib/poller.php[588]:db_fetch_cell(), /lib/database.php[360]:db_fetch_cell_prepared(), /lib/database.php[376]:db_execute_prepared())
2020/11/01 13:10:02 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'poller_id' in 'where clause'
2020/11/01 13:10:02 - CMDPHP SQL Backtrace:  (/poller.php[370]:db_fetch_assoc_prepared(), /lib/database.php[464]:db_execute_prepared())
2020/11/01 13:10:02 - ERROR PHP WARNING: array_merge(): Expected parameter 2 to be an array, bool given in file: /usr/share/cacti/site/poller.php  on line: 370
2020/11/01 13:10:02 - CMDPHP PHP ERROR WARNING Backtrace:  (/poller.php[370]:array_merge(), CactiErrorHandler())
2020/11/01 13:10:02 - CMDPHP ERROR: A DB Exec Failed!, Error: Unknown column 'snmp' in 'field list'
2020/11/01 13:10:02 - CMDPHP SQL Backtrace:  (/poller.php[406]:db_execute_prepared())
2020/11/01 13:10:02 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'h.poller_id' in 'where clause'
2020/11/01 13:10:02 - CMDPHP SQL Backtrace:  (/poller.php[477]:db_fetch_assoc_prepared(), /lib/database.php[464]:db_execute_prepared())
2020/11/01 13:10:02 - INSTALL: always: Converting Table #99 'user_domains_ldap'
2020/11/01 13:10:02 - ERROR PHP WARNING: Invalid argument supplied for foreach() in file: /usr/share/cacti/site/poller.php  on line: 582
2020/11/01 13:10:02 - CMDPHP PHP ERROR WARNING Backtrace:  (/poller.php[582]:CactiErrorHandler())
2020/11/01 13:10:02 - CMDPHP ERROR: A DB Row Failed!, Error: Table 'cacti.poller_data_template_field_mappings' doesn't exist
2020/11/01 13:10:02 - CMDPHP SQL Backtrace:  (/poller.php[661]:process_poller_output(), /lib/poller.php[409]:db_fetch_assoc_prepared(), /lib/database.php[464]:db_execute_prepared())
2020/11/01 13:10:02 - SYSTEM STATS: Time:0.0283 Method:cmd.php Processes:1 Threads:N/A Hosts:-1 HostsPerProcess:-1 DataSources:0 RRDsProcessed:0
2020/11/01 13:10:02 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'dbhost' in 'where clause'
2020/11/01 13:10:02 - CMDPHP SQL Backtrace:  (/poller.php[787]:poller_replicate_check(), /poller.php[847]:db_fetch_assoc(), /lib/database.php[450]:db_fetch_assoc_prepared(), /lib/database.php[464]:db_execute_prepared())
2020/11/01 13:10:02 - ERROR PHP WARNING: Invalid argument supplied for foreach() in file: /usr/share/cacti/site/poller.php  on line: 849
2020/11/01 13:10:02 - CMDPHP PHP ERROR WARNING Backtrace:  (/poller.php[787]:poller_replicate_check(), /poller.php[849]:CactiErrorHandler())
2020/11/01 13:10:02 - INSTALL: always: Converting Table #100 'user_log'
2020/11/01 13:10:02 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'snmp_engine_id' in 'field list'
2020/11/01 13:10:02 - CMDPHP SQL Backtrace:  (/poller.php[788]:snmpagent_poller_bottom(), /lib/snmpagent.php[420]:db_fetch_assoc(), /lib/database.php[450]:db_fetch_assoc_prepared(), /lib/database.php[464]:db_execute_prepared())
2020/11/01 13:10:02 - CMDPHP ERROR: A DB Row Failed!, Error: Table 'cacti.data_debug' doesn't exist
2020/11/01 13:10:02 - CMDPHP SQL Backtrace:  (/poller.php[791]:dsdebug_poller_bottom(), /lib/dsdebug.php[146]:db_fetch_assoc(), /lib/database.php[450]:db_fetch_assoc_prepared(), /lib/database.php[464]:db_execute_prepared())
2020/11/01 13:10:02 - INSTALL: always: Converting Table #101 'version'
2020/11/01 13:10:02 - INSTALL: always: Switched from /tmp/cdujPC6u8 to /tmp/cduCUucMF
2020/11/01 13:10:02 - INSTALL: always: NOTE: Using temporary file for db cache: /tmp/cduCUucMF
2020/11/01 13:10:02 - INSTALL: always: Upgrading from v0.8.8b (DB 1.2.2 (DB: 0.8.8b)) to v1.0.0
2020/11/01 13:10:03 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'poller_id' in 'field list'
2020/11/01 13:10:03 - CMDPHP SQL Backtrace:  (/poller_maintenance.php[146]:api_device_purge_deleted_devices(), /lib/api_device.php[110]:db_fetch_assoc_prepared(), /lib/database.php[464]:db_execute_prepared())

Markus

**Comment by bmfmancini** [comment]
1.2.2 is a pretty old release now
What are the logs showing tail the cacti.log file see where it's hanging

**Comment by huaraz** [comment]
1.2.2. was the buster packaged version. I added the cacti.log details.

2020/11/01 16:05:02 - CMDPHP SQL Backtrace:  (/poller.php[788]:snmpagent_poller_bottom(), /lib/snmpagent.php[420]:db_fetch_assoc(), /lib/database.php[450]:db_fetch_assoc_prepared(), /lib/database.php[464]:db_execute_prepared())
2020/11/01 16:05:02 - CMDPHP ERROR: A DB Row Failed!, Error: Table 'cacti.data_debug' doesn't exist
2020/11/01 16:05:02 - CMDPHP SQL Backtrace:  (/poller.php[791]:dsdebug_poller_bottom(), /lib/dsdebug.php[146]:db_fetch_assoc(), /lib/database.php[450]:db_fetch_assoc_prepared(), /lib/database.php[464]:db_execute_prepared())
2020/11/01 16:05:02 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'poller_id' in 'field list'
2020/11/01 16:05:02 - CMDPHP SQL Backtrace:  (/poller_maintenance.php[146]:api_device_purge_deleted_devices(), /lib/api_device.php[110]:db_fetch_assoc_prepared(), /lib/database.php[464]:db_execute_prepared())

Seems to be all about unknown columns

2020/11/01 16:05:02 - CMDPHP ERROR: A DB Cell Failed!, Error: Unknown column 'dbhost' in 'field list'
2020/11/01 16:05:02 - CMDPHP ERROR: A DB Exec Failed!, Error: Unknown column 'dbhost' in 'field list'
2020/11/01 16:05:02 - CMDPHP ERROR: A DB Cell Failed!, Error: Unknown column 'disabled' in 'field list'
2020/11/01 16:05:02 - CMDPHP ERROR: A DB Cell Failed!, Error: Unknown column 'disabled' in 'where clause'
2020/11/01 16:05:02 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'poller_id' in 'where clause'
2020/11/01 16:05:02 - CMDPHP ERROR: A DB Exec Failed!, Error: Unknown column 'snmp' in 'field list'
2020/11/01 16:05:02 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'h.poller_id' in 'where clause'
2020/11/01 16:05:02 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'dbhost' in 'where clause'
2020/11/01 16:05:02 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'snmp_engine_id' in 'field list'
2020/11/01 16:05:02 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'poller_id' in 'field list'

BTW Is this the best place to discuss or in the forum ? 

Markus

**Comment by bmfmancini** [comment]
I would move this to the forums

I hope you also made a database backup before the upgrade

**Comment by netniV** [comment]
Yeah, you need a later version which you can get from the backports repo that @paulgevers provides.  Not entirely sure if that would work for buster, but i think it should.

**Comment by paulgevers** [comment]
backups are made automatically in the Debian packaging (actually, it's dbconfig-common that does that)

backports instructions: https://backports.debian.org/

**Comment by paulgevers** [comment]
That said, if the buster package is buggy, a bug report in the Rasbian bug tracker would be good (not sure how that works, but if it's a pure copy from Debian, a bug report in Debian would be appropriate too).

**Comment by huaraz** [comment]
I think I found the issue during apt upgrade process a dependency was not resolved i.e. php-phpseclib was missing which stopped the database upgrade.

Thank you
Markus
