### ISSUE TITLE
Cacti 1.3.0 - php broken after last pull (expecting variable (T_VARIABLE)

### ISSUE THREAD

**Issue by rtripon** [Cacti/cacti#3897]
Hello,
I'm using cacti devel 1.3.0, and after last git pull from today, I cant access the website. It looks like php is broken : 

[Mon Nov 02 21:45:42.644354 2020] [:error] [pid 2859] [client 192.168.1.10:50040] PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in /var/www/html/cacti/lib/functions.php on line 1745. 
Any hints? Could it work by copying function.php from another server? I have one with same version.

**Comment by netniV** [comment]
What version of PHP are you running ?

**Comment by rtripon** [comment]
Hello Mark,

PHP 7.0.32 (cli) (built: Sep 13 2018 16:50:42) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.3.9, Copyright (c) 2002-2019, by ionCube Ltd.
    with Zend OPcache v7.0.32, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans

**Comment by netniV** [comment]
The minimum for develop is 7.2. There were various notices about that requirement coming in over the past few months. 

You will need to update your instance to that level due to numerous technologies that we are starting to utilise and third party requirements.

**Comment by rtripon** [comment]
Thank you, all solved with php 7.3.

**Comment by rtripon** [comment]
Actually, after upgrade to php 7.3 I had to upgrade chartdirector to 7.3, but now I got tons of errors.


2020/11/02 20:26:25 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
--
2020/11/02 20:26:25 - ERROR PHP ERROR: Uncaught Error: Call to  undefined function mb_strlen() in /var/www/html/cacti/lib/rrd.php:1641  Stack trace: #0 /var/www/html/cacti/graph_json.php(159):  rrdtool_function_graph(815, '0', Array, '', Array, '1') #1 {main} thrown  in file: /var/www/html/cacti/lib/rrd.php on line: 1641
2020/11/02 20:26:25 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
2020/11/02 20:26:25 - ERROR PHP ERROR: Uncaught Error: Call to  undefined function mb_strlen() in /var/www/html/cacti/lib/rrd.php:1641  Stack trace: #0 /var/www/html/cacti/graph_json.php(159):  rrdtool_function_graph(813, '0', Array, '', Array, '1') #1 {main} thrown  in file: /var/www/html/cacti/lib/rrd.php on line: 1641
2020/11/02 20:26:24 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
2020/11/02 20:26:24 - ERROR PHP ERROR: Uncaught Error: Call to  undefined function mb_strlen() in /var/www/html/cacti/lib/rrd.php:1641  Stack trace: #0 /var/www/html/cacti/graph_json.php(159):  rrdtool_function_graph(814, '0', Array, '', Array, '1') #1 {main} thrown  in file: /var/www/html/cacti/lib/rrd.php on line: 1641
2020/11/02 20:26:24 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
2020/11/02 20:26:24 - ERROR PHP ERROR: Uncaught Error: Call to  undefined function mb_strlen() in /var/www/html/cacti/lib/rrd.php:1641  Stack trace: #0 /var/www/html/cacti/graph_json.php(159):  rrdtool_function_graph(811, '0', Array, '', Array, '1') #1 {main} thrown  in file: /var/www/html/cacti/lib/rrd.php on line: 1641
2020/11/02 20:26:24 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
2020/11/02 20:26:24 - ERROR PHP ERROR: Uncaught Error: Call to  undefined function mb_strlen() in /var/www/html/cacti/lib/rrd.php:1641  Stack trace: #0 /var/www/html/cacti/graph_json.php(159):  rrdtool_function_graph(812, '0', Array, '', Array, '1') #1 {main} thrown  in file: /var/www/html/cacti/lib/rrd.php on line: 1641
2020/11/02 20:26:24 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
2020/11/02 20:26:24 - ERROR PHP ERROR: Uncaught Error: Call to  undefined function mb_strlen() in /var/www/html/cacti/lib/rrd.php:1641  Stack trace: #0 /var/www/html/cacti/graph_json.php(159):  rrdtool_function_graph(4859, '0', Array, '', Array, '1') #1 {main}  thrown in file: /var/www/html/cacti/lib/rrd.php on line: 1641
2020/11/02 20:26:24 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
2020/11/02 20:26:24 - ERROR PHP ERROR: Uncaught Error: Call to  undefined function mb_strlen() in /var/www/html/cacti/lib/rrd.php:1641  Stack trace: #0 /var/www/html/cacti/graph_json.php(159):  rrdtool_function_graph(4860, '0', Array, '', Array, '1') #1 {main}  thrown in file: /var/www/html/cacti/lib/rrd.php on line: 1641
2020/11/02 20:26:24 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
2020/11/02 20:26:24 - ERROR PHP ERROR: Uncaught Error: Call to  undefined function mb_strlen() in /var/www/html/cacti/lib/rrd.php:1641  Stack trace: #0 /var/www/html/cacti/graph_json.php(159):  rrdtool_function_graph(808, '0', Array, '', Array, '1') #1 {main} thrown  in file: /var/www/html/cacti/lib/rrd.php on line: 1641
2020/11/02 20:26:23 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
2020/11/02 20:26:23 - ERROR PHP ERROR: Uncaught Error: Call to  undefined function mb_strlen() in /var/www/html/cacti/lib/rrd.php:1641  Stack trace: #0 /var/www/html/cacti/graph_json.php(159):  rrdtool_function_graph(810, '0', Array, '', Array, '1') #1 {main} thrown  in file: /var/www/html/cacti/lib/rrd.php on line: 1641
2020/11/02 20:26:23 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
2020/11/02 20:26:23 - ERROR PHP ERROR: Uncaught Error: Call to  undefined function mb_strlen() in /var/www/html/cacti/lib/rrd.php:1641  Stack trace: #0 /var/www/html/cacti/graph_json.php(159):  rrdtool_function_graph(809, '0', Array, '', Array, '1') #1 {main} thrown  in file: /var/www/html/cacti/lib/rrd.php on line: 1641
2020/11/02 20:26:23 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
2020/11/02 20:26:23 - ERROR PHP ERROR: Uncaught Error: Call to  undefined function mb_strlen() in /var/www/html/cacti/lib/rrd.php:1641  Stack trace: #0 /var/www/html/cacti/graph_json.php(159):  rrdtool_function_graph(806, '0', Array, '', Array, '1') #1 {main} thrown  in file: /var/www/html/cacti/lib/rrd.php on line: 1641
2020/11/02 20:25:45 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
2020/11/02 20:25:45 - ERROR PHP ERROR: Uncaught Error: Call to  undefined function mb_strlen() in /var/www/html/cacti/lib/rrd.php:1641  Stack trace: #0 /var/www/html/cacti/graph_json.php(159):  rrdtool_function_graph(5094, '0', Array, '', Array, '1') #1 {main}  thrown in file: /var/www/html/cacti/lib/rrd.php on line: 1641
2020/11/02 20:25:24 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
2020/11/02 20:25:24 - ERROR PHP ERROR: Uncaught TypeError: Argument 9  passed to mailer() must be of the type array, string given, called in  /var/www/html/cacti/plugins/thold/thold_functions.php on line 5406 and  defined in /var/www/html/cacti/lib/functions.php:3447 Stack trace: #0  /var/www/html/cacti/plugins/thold/thold_functions.php(5406):  mailer(Array, 'razvan.tripon@g...', '', '', '', 'Device Error: S...',  'System Error : ...', 'System Error : ...', '', Array, true) #1  /var/www/html/cacti/plugins/thold/includes/polling.php(793):  thold_mail('razvan.tripon@g...', 'cacti@cacti.3de...', 'Device Error:  S...', 'System Error : ...', '') #2  /var/www/html/cacti/plugins/thold/includes/polling.php(46):  thold_update_host_status() #3 /var/www/html/cacti/lib/plugins.php(181):  thold_poller_bottom(Array) #4 /var/www/html/cacti/lib/plugins.php(75):  api_plugin_run_plugin_hook('poller_bottom', 'thold',  'thold_poller_bo...', Array) #5 /var/www/html/cacti/poller.php(826):  api_plugin_hook('poller_bottom') #6 {main} thrown in file:  /var/www/html/cacti/lib/functions.php on line: 3447
2020/11/02 20:25:24 - THOLD WARNING: Device[SENZOR VLADI] Hostname[217.156.98.2] is down!
2020/11/02 20:25:23 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
2020/11/02 20:25:23 - ERROR PHP ERROR: Uncaught Error: Call to  undefined function xml_parser_create() in  /var/www/html/cacti/lib/xml.php:29 Stack trace: #0  /var/www/html/cacti/lib/data_query.php(585):  xml2array('<interface>\n\t<n...') #1  /var/www/html/cacti/lib/data_query.php(95): get_data_query_array('1') #2  /var/www/html/cacti/poller_commands.php(144): run_data_query('101',  '1') #3 {main} thrown in file: /var/www/html/cacti/lib/xml.php on line:  29
2020/11/02 20:25:23 - PCOMMAND Device[iMG.ORANGE-VDF-BTRL-ATRIUM] WARNING: Recache Event Detected for Device
2020/11/02 20:25:23 - CMDPHP SQL Backtrace:   (/poller.php[686]:poller_run_stats(), /poller.php[1033]:db_execute(),  /lib/database.php[213]:db_execute_prepared())
2020/11/02 20:25:23 - CMDPHP ERROR: A DB Exec Failed!, Error: Table 'cacti.poller_time_stats' doesn't exist
2020/11/02 20:25:23 - CMDPHP SQL Backtrace:  (/poller.php[686]:poller_run_stats(), /poller.php[1030]:db_execute_prepared())
2020/11/02 20:25:23 - CMDPHP ERROR: A DB Exec Failed!, Error: Table 'cacti.poller_time_stats' doesn't exist
2020/11/02 20:25:23 - SYSTEM STATS: Time:21.5290 Method:spine  Processes:1 Threads:10 Hosts:222 HostsPerProcess:222 DataSources:5079  RRDsProcessed:0
2020/11/02 22:25:10 - SPINE: Poller[Main Poller] PID[12667] Device[TEMPERATURI VLADI] Hostname[217.156.98.2] ERROR: HOST EVENT: Device is DOWN Message: Device did not respond to SNMP, ICMP: Ping timed out
2020/11/02 22:25:10 - SPINE: Poller[Main Poller] PID[12667] Device[TEST VLADI] Hostname[217.156.98.2] ERROR: HOST EVENT: Device is DOWN Message: Device did not respond to SNMP, ICMP: Ping timed out
2020/11/02 22:25:08 - SPINE: Poller[Main Poller] PID[12667] Device[SENZOR VLADI] Hostname[217.156.98.2] ERROR: HOST EVENT: Device is DOWN Message: Device did not respond to SNMP, ICMP: Ping timed out
2020/11/02 20:20:28 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
2020/11/02 20:20:28 - ERROR PHP CORE_WARNING: PHP Startup: Unable to  load dynamic library 'phpchartdir700.dll' (tried:  /usr/lib64/php/modules/phpchartdir700.dll  (/usr/lib64/php/modules/phpchartdir700.dll: undefined symbol:  _array_init), /usr/lib64/php/modules/phpchartdir700.dll.so  (/usr/lib64/php/modules/phpchartdir700.dll.so: cannot open shared object  file: No such file or directory)) in file: Unknown on line: 0

**Comment by rtripon** [comment]
Umm...i think some php modules are still missing.

**Comment by netniV** [comment]
Yeah it sounds like your upgrade has not enabled the same module that were enabled before

**Comment by TheWitness** [comment]
If it centos, I had to enable php-fpm and make several changes.  The SCL stuff is messy too.

**Comment by rtripon** [comment]
Centos 7 it is, I've managed to upgrade to php 7.4 and install the missing modules(all I think), web is working as well as graphs.
I still have some errors with thold :

2020/11/03 11:10:26 - CMDPHP SQL Backtrace: (/poller.php[681]:process_poller_output(), /lib/poller.php[544]:api_plugin_hook_function(), /lib/plugins.php[117]:api_plugin_run_plugin_hook_function(), /lib/plugins.php[225]:thold_poller_output(), /plugins/thold/includes/polling.php[375]:db_fetch_assoc(), /lib/database.php[476]:db_fetch_assoc_prepared(), /lib/database.php[490]:db_execute_prepared())
2020/11/03 11:10:26 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'td.upper_ds' in 'field list'
2020/11/03 11:10:25 - CMDPHP SQL Backtrace: (/poller.php[697]:process_poller_output(), /lib/poller.php[544]:api_plugin_hook_function(), /lib/plugins.php[117]:api_plugin_run_plugin_hook_function(), /lib/plugins.php[225]:thold_poller_output(), /plugins/thold/includes/polling.php[375]:db_fetch_assoc(), /lib/database.php[476]:db_fetch_assoc_prepared(), /lib/database.php[490]:db_execute_prepared()) 

2020/11/03 11:10:26 - CMDPHP SQL Backtrace: (/poller.php[681]:process_poller_output(), /lib/poller.php[544]:api_plugin_hook_function(), /lib/plugins.php[117]:api_plugin_run_plugin_hook_function(), /lib/plugins.php[225]:thold_poller_output(), /plugins/thold/includes/polling.php[375]:db_fetch_assoc(), /lib/database.php[476]:db_fetch_assoc_prepared(), /lib/database.php[490]:db_execute_prepared())
2020/11/03 11:10:26 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'td.upper_ds' in 'field list'

Also,  I'm getting and error when trying to modify any host

**Comment by netniV** [comment]
That appears to be a problem with THold running under develop cacti, not a core issue per sae as far as I can see.

**Comment by rtripon** [comment]
Seems that this upgrade broken everything, I had to reinstall server, staying away from devel versions atm.

**Comment by netniV** [comment]
We are in the process of breaking to fix things 👍  We appreicate beta testers, but it's not always ideal.
