### ISSUE TITLE
new device can't show history graphs , but can show real time graphs 

### ISSUE THREAD

**Issue by yunbytes** [Cacti/cacti#3899]
RRD file also can create
version. 1.2.14

**Comment by bmfmancini** [comment]
Is this a single device or all of them ?
Check the permissions of the rra folder make sure the user matches the
cacti user

**Comment by netniV** [comment]
This generally means that the folder permissions for your cacti instance are not the same between CLI and Apache users.  Use Data Source diagnostics under the Troubleshooting section and see if anything shows up as being wrong.

**Comment by yunbytes** [comment]
> 通常，這意味著CLI和Apache用戶之間對cacti實例的文件夾權限不同。使用“故障排除”部分下的“數據源”診斷，查看是否有任何錯誤。
yes, it's right. thank you.
