### ISSUE TITLE
1.2.15 Installation Wizard Loop

### ISSUE THREAD

**Issue by pan781023** [Cacti/cacti#3900]
Upgrade from 1.2.14 to 1.2.15

The upgrade starts and gets "getting start" then loops back to the beging of the installation wizard in this page 

how can i do ? 

![2020-11-04_171151](https://user-images.githubusercontent.com/12995861/98094460-4da4c780-1ec4-11eb-8399-e165d887ed82.png)

**Comment by netniV** [comment]
You will need to increase the installer logging levels and then best thing would be to email those logs to developer@cacti.net so we can review what's happening. I think there's an error occurring and for some reason that's resetting your step when it shouldn't.

**Comment by TheWitness** [comment]
Waiting on feedback.

**Comment by TheWitness** [comment]
Closing due to lack of feedback.
