### ISSUE TITLE
Cacti shows traffic spike when reset counter occurs

### ISSUE THREAD

**Issue by jcdaniel14** [Cacti/cacti#3901]
Hi, I have around ~1000 devices running on Cacti, mostly cisco, I've noticed the data source template uses ifSpeed to determine the maximum value the poller is going to save to the rrd files but since we tune the interface speed to influence routing decisions this was giving us truncated graphs like this.

![image](https://user-images.githubusercontent.com/13785650/98129671-6773e980-1e87-11eb-88fe-7cc287b08908.png)

We considered a good idea to set the _**maximum value to 'U'**_ (both in template and with rrdtool tune) to solve this issue but then we got into a different problem, several graphs showed traffic spikes reaching petabits of traffic and in every scenario syslog shows device/line card reboots at that same timestamp, which leads me to believe a reset counter is influencing these traffic spikes.

![image](https://user-images.githubusercontent.com/13785650/98130336-25977300-1e88-11eb-85c0-a9a2a82237d7.png)

I've read in the forums that Cacti is aware of a clear counter and will calculate the correct value, but I think maybe the 'U' maximum value is preventing this from happening.

Any insights into this would be very appreciated!

## Additional context

I have Cacti Version 1.2.14 and also I've tried to apply spikekill with different parameters but I think I'm not really understanding how to make it work because it won't detect any spikes.
![spike](https://user-images.githubusercontent.com/13785650/98131448-44e2d000-1e89-11eb-84a1-7825a77827b9.png)

**Comment by TheWitness** [comment]
Are you using spine or cmd.php?

**Comment by jcdaniel14** [comment]
Yea I use spine 1.2.14 since we have too many devices to poll

**Comment by TheWitness** [comment]
With spine there is a feature to place unknown data into the RRDfile for one polling cycle when uptime goes backward.  This was a technique used to prevent spikes in the graphs.  Tobi may have accepted a pull request to 'undo' this some years ago.

The best way to use spike kill is by using variance I think an not standard deviation, though from your perspective, standard deviation seems to identify them.  You may have to increase the number of kills, a separate command line option.

**Comment by TheWitness** [comment]
For the hacking that you are doing with ifHighSpeed, you should incorporate an 'rrdtune' into your process, otherwise, this will continue.

**Comment by jcdaniel14** [comment]
Yea I also used rrdtune to change it to U, at the moment I'm trying to set the value to a very high bandwidth instead of U, both in template and using rrdtune, by the end of month I'll run a script to generate a traffic report and we'll see if it gets corrected.

**Comment by TheWitness** [comment]
Cool.  I'll close it for now.
