### ISSUE TITLE
Cacti does not pass hostname/IP to the script

### ISSUE THREAD

**Issue by 0byt3** [Cacti/cacti#3902]
# Describe the bug

I created a bash script that SSHs into a client and acquires wireless signal information. I added this as a script input method, then used that for a data source template, then used that in a graph template. After I created the graph, no IP Address or hostname is passed to the script when it is used.

## To Reproduce

Create the following script /usr/share/cacti/site/scripts/linux_wifi_levels.bash:
`#!/usr/bin/bash

sshUser="cacti"
sshHost="$1"
output=$(ssh "$sshUser@$sshHost" "cat /proc/net/wireless" | awk 'NR==3 {print "level:"$4,"noise:"$5}' | sed -r 's/(\.|-)//g')
echo -n "$output"`

Create "cacti" user on the target machine with a home directory and create the .ssh directory in the home directory.

Generate SSH keys for the www-data user on the cacti server, then add them to the authorizied_keys file on the target computer.
`sudo -H -u www-data -s bash -c "ssh-keygen"`
`scp /var/www/.ssh/id_rsa.pub cacti@10.100.2.30:/home/cacti/cacti.cacti.pub`
`ssh cacti@10.100.2.30 "cat /home/cacti/cacti.cacti.pub >> /home/cacti/.ssh/authorized_keys`
`ssh cacti@10.100.2.30 "rm -f /home/cacti/cacti.cacti.pub`
!! I just put these commands in by memory, so there may have made some syntax errors, however you get the idea. I tested SSHing into cacti@10.100.2.30 in the context of the www-data user and public key authentication works.

I add the script as an Input Method, create a Data Source Template using the Input Method and create a Graph Template using the Data Source.

I create a graph using the Graph Template. No data makes it onto the graph. I see the following message in the log:
> Poller[1] Device[1] DS[6] CMD: bash /usr/share/cacti/site/scripts/linux_wifi_levels.bash , output: U

## Expected behavior

Cacti receives the data and puts it in the graph.

## Screenshots
![image](https://user-images.githubusercontent.com/15963261/98198737-85206d80-1ede-11eb-873e-5b69e17af351.png)
![image](https://user-images.githubusercontent.com/15963261/98198748-8ce01200-1ede-11eb-9d54-6e05c96d8a33.png)
![image](https://user-images.githubusercontent.com/15963261/98198759-936e8980-1ede-11eb-8960-00592d5616df.png)

If I run the script manually it works fine:
sudo -H -u www-data -s bash -c "bash /usr/share/cacti/site/scripts/linux_wifi_levels.bash 10.100.2.30"
output:
> level:51 noise:256

I understand that the most likely reason this doesn't work is that I configured it incorrectly, however I cannot seem to piece together what the documentation is explaining and turn it into a working Data Source. I tried using the built-in "Unix - Ping Host" as a guide and have everything setup properly so far as I can tell, but it is not working.

**Comment by netniV** [comment]
Can you paste a screenshot of your input method and script parameters within Cacti?

**Comment by TheWitness** [comment]
When in the data input method, click on the hostname field and ensure that the special host code is not blank.  I think one of the special host codes might be 'hostname'.  Post that screenshot.

**Comment by 0byt3** [comment]
Here is the screenshot:
![image](https://user-images.githubusercontent.com/15963261/98320670-3a632c00-1f98-11eb-8558-0e33f8b2fef9.png)

After you pointed me to that location, I clued into what you wanted me to check. I typed "hostname" into the Special Type Code text box and now it works.

Thank you for your assistance.
