### ISSUE TITLE
Enhance automation to allow someone to view all recently discovered devices

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3904]
Hey Guys 

I was thinking what would be a great feature would be to have the ability to add new devices in a temp tree
there is the option in automation to select a device by the amount of polls  we add a remove a bunch of devices in the installs I manage and it would be nice to have the new devices in a tree as they could be recent installs or turnups

Then after the poll count goes passed a certain amount then the devices get removed from the tree

**Comment by EmilAndersson-SE** [comment]
We work a bit the same i guess. Before production and then in production. What about adding all newly discovered devices to this tree by automation rule? Shouldn't that make us happy?

**Comment by TheWitness** [comment]
So, reading between the lines, you would like to see a list of the devices added to Cacti by Automation so that you can purge some of them.  Is that the story?  So, instead of a Tree, the concept would be some way to track that activity and reject some additions?

**Comment by bmfmancini** [comment]
Yes something along those lines but also those devices should move from the 'newly discovered section' to being a regular device type after a certain amount of time i.e 1 week

**Comment by bmfmancini** [comment]
> 
> 
> We work a bit the same i guess. Before production and then in production. What about adding all newly discovered devices to this tree by automation rule? Shouldn't that make us happy?

Yes right now you could add the new device via the poll count field in automation but a mechanism to move them into a regular device would be great as well

One thing I was also thinking would be if you add a device via automation this is not fully in prod yet you may want those devices not to generate alarms until

**Comment by bmfmancini** [comment]
oops

**Comment by EmilAndersson-SE** [comment]
> > We work a bit the same i guess. Before production and then in production. What about adding all newly discovered devices to this tree by automation rule? Shouldn't that make us happy?
> 
> Yes right now you could add the new device via the poll count field in automation but a mechanism to move them into a regular device would be great as well
> 
> One thing I was also thinking would be if you add a device via automation this is not fully in prod yet you may want those devices not to generate alarms until

I agree and monitor is a bit annoying on theese devices if you are working with them on and off.
