### ISSUE TITLE
The cli script install_cacti.php does not exit with not zero exit code when error occur

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#3907]
# Describe the bug

When errors occur in the install_cacti.php script, the script should exit with a non-zero exit code, which it does not.

## To Reproduce

1. Go to /var/www/html/cacti/cli

2. uninstall a critical php module such as ldap

3. Run the installer to install cacti.  Not that there are errors

4. Run "echo $?" and note that the scripted exited with a zero error code

## Expected behavior

CLI script should exit with non-zero exit codes when they fail.

**Comment by netniV** [comment]
No commit was assigned this tracker?
