### ISSUE TITLE
cannot open -lssl

### ISSUE THREAD

**Issue by macadmin-sps** [Cacti/cacti#391]
I am currently trying to update my cacti server (Running Fedora 24) from 0.8.8h to 1.0.4.  I've gotten everything working until I get to configure the spine.   When I run ./configure I get the following output. 

checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gawk... (cached) gawk
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/tmp/cacti-spine-1.0.4':
configure: error: C compiler cannot create executables
See `config.log' for more details

So I check the config.log file and I see the following..

configure:3429: $? = 0
configure:3418: gcc -v >&5
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/6.3.1/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,objc,$
Thread model: posix
gcc version 6.3.1 20161221 (Red Hat 6.3.1-1) (GCC)
configure:3429: $? = 0
configure:3449: checking whether the C compiler works
**configure:3471: gcc   -lpthread -lssl -lm  conftest.c  >&5
/usr/bin/ld: cannot find -lssl**
collect2: error: ld returned 1 exit status
configure:3475: $? = 1
configure:3513: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "Spine Poller"
| #define PACKAGE_TARNAME "spine-poller"
| #define PACKAGE_VERSION "1.0.4"
| #define PACKAGE_STRING "Spine Poller 1.0.4"
| #define PACKAGE_BUGREPORT "http://www.cacti.net/bugs.php"
| #define PACKAGE_URL ""
| #define PACKAGE "spine-poller"
| #define VERSION "1.0.4"
| /* end confdefs.h.  */
|
| int
| main ()
| {
|
|   ;
|   return 0;

I'm stuck at this point and I'm open to suggestions.

**Comment by FrodoTheRingWearer** [comment]
The -l option on GCC tells it to include the library. Does Fedora have an SSL library installed? I'm guessing this isn't working because it can't find that.

**Comment by macadmin-sps** [comment]
I'm relatively new to the Linux world, so I'm not sure.

**Comment by FrodoTheRingWearer** [comment]
I've never used Fedora. I'd imagine they have a package manager of some sort. That would be your best bet to getting the SSL libraries properly installed.

**Comment by dsclassen** [comment]
yum -y install openssl-devel

**Comment by cigamit** [comment]
This is an issue for the forums.  Please look there before opening a ticket.
