### ISSUE TITLE
Banners are not showing up

### ISSUE THREAD

**Issue by RazvanZeces** [Cacti/cacti#3910]
Hello,

I just installed the plugin, configured to export the graphs via FTP, graphs are beeing uploaded to the FTP server but they are not showing up (images) when accessing the FTP server.

Any ideeas why? 
![cacti](https://user-images.githubusercontent.com/56639628/98468915-468ff900-21e5-11eb-9535-1a6123d6b8cf.png)
![cacti2](https://user-images.githubusercontent.com/56639628/98468933-5a3b5f80-21e5-11eb-98bf-1b403f9333a4.png)

**Comment by RazvanZeces** [comment]
@TheWitness should I redownload the plugin and try again?

**Comment by TheWitness** [comment]
No, lib/functions.php from the Cacti 1.2.x branch.

**Comment by RazvanZeces** [comment]
@TheWitness I just downloaded the latest branch for Cacti 1.2.2 from official website, and it seems like not been updated.

Is this ok? 
![functions](https://user-images.githubusercontent.com/56639628/98472231-6aaa0500-21fa-11eb-9e5f-0b21beb620da.png)

**Comment by TheWitness** [comment]
No.  If you are not on Cacti 1.2.15, you need to upgrade fist.  Then you have to get it from GitHub.  What website?

**Comment by RazvanZeces** [comment]
Shoot, sorry, this is my bad, I was running on 1.2.2 and I got this on my mind. I forgot that I upgraded from 1.2.2 to 1.2.15.

Can you give a direct URL from where to download?

**Comment by TheWitness** [comment]
https://github.com/Cacti/cacti/tree/1.2.x/lib

**Comment by RazvanZeces** [comment]
Ok, I downloaded the file and replaced it with the one that was on the server.

It's the same issue, they don't display.

I even re-run manually the export.

**Comment by RazvanZeces** [comment]
Also, errors still appears in the Log section.

![err](https://user-images.githubusercontent.com/56639628/98474104-eeb1bc00-21fd-11eb-9f2e-28ffdbe8b811.png)

**Comment by TheWitness** [comment]
Okay, create another bug under gexport.
