### ISSUE TITLE
Cacti 1.2.x missing php modules (ioncube/chardirector)

### ISSUE THREAD

**Issue by rtripon** [Cacti/cacti#3911]
Hello,
I have a brand new install oh Cacti 1.2.15 on Centos 8 with php 7.4 and I cant make the cacti web server load the ioncube module, nor chartdirector(need them for Cereus reporting plugin).
Bellow are the output for php -m and php -v, in cli the modules are loaded, but on web cacti wont see those.

php -v
PHP 7.4.12 (cli) (built: Oct 27 2020 15:01:52) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.4.4, Copyright (c) 2002-2020, by ionCube Ltd.
    with Zend OPcache v7.4.12, Copyright (c), by Zend Technologies

[root@localhost php.d]# php -m
[PHP Modules]
bcmath
bz2
calendar
ChartDirector PHP API
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
intl
ionCube Loader
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
snmp
sockets
sodium
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
the ionCube PHP Loader + ionCube24

So far so good, but when I check with phpinfo or looking under cacti utilities->sistem utilities->PHP Info, those modules are missing. No errors in any logs, modules are loaded from /etc/php.d/

[root@localhost php.d]# cat 10-ioncube.ini
; Enable ionCube extension
zend_extension="/usr/lib64/php/modules/ioncube_loader_lin_7.4.so"

[root@localhost php.d]# cat 10-chartdirector.ini
#extension=phpchartdir740.dll
extension="/usr/lib64/php/modules/phpchartdir740.dll".

Dont know where to look other than this, any hints?.

**Comment by TheWitness** [comment]
This is likely not a cacti issue.  Please contact Mr. Urban. Hey @thurban, I think this might be you.

Larry

**Comment by rtripon** [comment]
Hello Larry,
I get that those modules are required for Mr. Urban's cereus plugin, but I should be able to see them loaded with phpinfo()?. Or?.

**Comment by thurban** [comment]
You need to restart the apache Webserver to load these modules.
Please send further issues to support@urban-software.com

**Comment by rtripon** [comment]
I did restart webserver, tried to change ini file from 01 to 10 to 50, no luck. I'll write an email then to support@urban-software.com.

**Comment by TheWitness** [comment]
@rtripon, you should.  @thurban will fix you up.
