### ISSUE TITLE
Difficult upgrade to 1.2.15

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#3914]
I just upgraded from 1.2.14 to 1.2.15. It did not go smoothly. As you know, I have a multi-poller setup. After the upgrade, none of the pollers were working. They still had all their hosts associated with them, but during each polling cycle they had "DataSources:0 RRDsProcessed:0" in the SYSTEM STATS message, with a very short runtime. I tried updating the poller cache, and forcing full syncs. No joy. What finally ended up working was moving all the devices off the remote poller to the main poller, and then back. Now the remote pollers started processing the data sources. 

I performed the upgrade in mostly the same manner that I usually do. The main difference was that once the web GUI installer was finished, I re-enabled all the pollers (main and remote). Usually, I only re-enable the main poller for a couple cycles, stop it, update the poller cache, run the main poller again a few cycles, then re-enable the remote pollers. In theory I feel that I should not have to be this careful, and I should be able to update the poller cache while everything is running. 

Next upgrade cycle I'll go back to my previous overly-careful procedure. 

Oh, I should also note: While you're doing a bulk "Change Device Settings" across a lot of devices to change their poller, something is blocking and prohibiting Cacti from rendering/displaying any graphs. That's been a problem for a long time, but it was very apparent while I was having to do all this work.

**Comment by eschoeller** [comment]
You can close this if you want to. I opened #3916 instead.

But, this inability to render/display graphs during a bulk settings change is still a thing.

**Comment by TheWitness** [comment]
Yea, this is a duplicate.
