### ISSUE TITLE
Bulk Enabling Devices takes forever

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#3915]
I'm in the process of fixing some other problems, and notice that disabling 50 devices at once is quick, but enabling 50+ devices takes forever. Sometimes I hit the php maximum runtime. Hopefully this isn't necessary and it could be sped up or could be run in parallel or in the background.

**Comment by zuka1337** [comment]
If you want to disable all devices you can use the query below:
`update host SET disabled = 'on';`

**Comment by netniV** [comment]
The reason that it is not as quick is probably due to syncing with remote pollers to ensure that data is up to date when enabling them.  Simply bypassing that process using the above query may lead to other issues I would suspect but @TheWitness will know better than me.
