### ISSUE TITLE
API Tree Warning Errors when pen testing Cacti in api_tree_rename_node()

### ISSUE THREAD

**Issue by ZhiXianZheng** [Cacti/cacti#3917]
An error occurred while renaming the tree directory name.

version 1.2.10

2020/11/12 15:23:33 - CMDPHP PHP ERROR NOTICE Backtrace: (/tree.php[147]:api_tree_rename_node(), /lib/api_tree.php[548]:CactiErrorHandler())
2020/11/12 15:23:33 - ERROR PHP NOTICE: Undefined offset: 1 in file: /var/www/html/lib/api_tree.php on line: 548
2020/11/12 15:23:33 - CMDPHP PHP ERROR NOTICE Backtrace: (/tree.php[147]:api_tree_rename_node(), /lib/api_tree.php[548]:CactiErrorHandler())
2020/11/12 15:23:33 - ERROR PHP NOTICE: Undefined offset: 1 in file: /var/www/html/lib/api_tree.php on line: 548
2020/11/12 15:23:33 - CMDPHP PHP ERROR NOTICE Backtrace: (/tree.php[147]:api_tree_rename_node(), /lib/api_tree.php[548]:CactiErrorHandler())
2020/11/12 15:23:33 - ERROR PHP NOTICE: Undefined offset: 1 in file: /var/www/html/lib/api_tree.php on line: 548
2020/11/12 15:23:33 - CMDPHP PHP ERROR NOTICE Backtrace: (/tree.php[147]:api_tree_rename_node(), /lib/api_tree.php[548]:CactiErrorHandler())
2020/11/12 15:23:33 - ERROR PHP NOTICE: Undefined offset: 1 in file: /var/www/html/lib/api_tree.php on line: 548

**Comment by netniV** [comment]
Things have moved on since 1.2.10, can you update and see if the problem persists?

**Comment by TheWitness** [comment]
This might be caused through pen testing @netniV.  Maybe that's what going on here.
