### ISSUE TITLE
CSV Export with Summation Rows

### ISSUE THREAD

**Issue by fnasib** [Cacti/cacti#3920]
Hello,

The below is essentially a copy and paste (for the most part) from the cacti forum.

I have scoured the forums and I have only seen fragments that would seem to address my issues but nothing conclusive. I'll consolidate the issue and see if this is something that can be addressed.

This is the Interface Traffic configuration for a new Cacti 1.2.14 deployment, it graphs appropriately and presents bandwidth summation data. This is the same configuration running on version 0.8.7g. Where the issue starts is when the export to CSV via the web console (GUI) is selected. Only the graphed "input" data is exported but it does not export the "Summation Total In:" or "Summation Total Out:" data.

I by no means am a SQL DBA nor a PHP developer but from the limited understanding these do not appear to be the cause. In version 0.8.7g and earlier this functions works without issue. The Summation data is always generated in the CSV export file as rows 9 and 10.

The only variations that can be identified is that the graph_xport.php file has changed significantly over the years along with the cacti.sql file. Having said this, we suspect that this is configuration related and not PHP or SQL related, since software has developed and become more secure over the years. Hence the assumption is the graph template could be incorrectly configured, since it was modeled off Cacti 0.8.7g.

The interface traffic bit/sec bandwidth graph template/data query has not worked either.

If any further data/information is required please do let me know. Or of this has been answered in a different area then please do direct me accordingly.

I have linked the images to the cacti forums because I am getting errors in uploading PNG files. 

[https://forums.cacti.net/viewtopic.php?f=21&t=61190&p=284216&hilit=csv+export+summation#p284216](url)

**Comment by TheWitness** [comment]
Okay, looking at this, I'm thinking 'bug'.

**Comment by TheWitness** [comment]
Okay, this is fixed now.  Thanks for reporting.

**Comment by TheWitness** [comment]
This was crazy.  The code had been removed sometime in 2016.  Dude, like 4 years ago.  Going to close.  It's working fine in my instance.  I changed the output format slightly, so if you have a robot going after the data, it'll have to be updated.

**Comment by fnasib** [comment]
@TheWitness Many thanks for the find and correction!!
