### ISSUE TITLE
 ICMP device status does not change

### ISSUE THREAD

**Issue by freetime27** [Cacti/cacti#3921]
Dear,

I was adding teams only to monitor ICMP, I added several successfully, but then a problem arose. New devices are left in an unknown state. Given this, I was duplicating computers that already had working and after these if they raised a UP state, I modified them with the IP and name of a new one.
So I drove for a couple of hours, but now I can't do this anymore.
I use cacti 1.2.8, I already restarted maria db and apache but it remains the same. wait more than 3 hours and do not change state. when I enter the device it shows me that the ping is fine.
In the cactus log I don't see any errors referring to this. just an error with 2 datasource that are from something else.
I hope your help.

additionally, I comment that I try to see records in the probe of these devices and I do not see them. I think the glitch causes these new devices to not be added to the probe.

![cacti1](https://user-images.githubusercontent.com/28991255/99403242-00aff080-28c9-11eb-958c-a52d2f0fbd4b.png)
![cacti2](https://user-images.githubusercontent.com/28991255/99403248-01e11d80-28c9-11eb-9a69-27cff90ae9cd.png)
![cacti3](https://user-images.githubusercontent.com/28991255/99403250-0279b400-28c9-11eb-8e2a-8438984521aa.png)

**Comment by TheWitness** [comment]
spine poller or cmd.php.  If spine, you need to remember to 

```cmd
chown root:root spine
chmod +s spine
```

**Comment by freetime27** [comment]
Dear, I am using cmd.php.
I tried to install spine but the whole application breaks like this. I just restored the VM to main state without spine installation ...


also try to update cacti to version 1.2.15 but it asks me to update maria db from 5.5 to 5.6 minimum. I did the update but the database was broken.

**Comment by TheWitness** [comment]
Please handle this on forums.

**Comment by freetime27** [comment]
En el foro nadie responde.... ya lo publique.
