### ISSUE TITLE
Username and password on the login page is not visible in Classic theme

### ISSUE THREAD

**Issue by RadekHvizdos** [Cacti/cacti#3926]
# Describe the bug

When I type a username and password for login to Cacti I don't see typed characters in Classic theme. On some browser/OS combinations the placeholder text for Username and Password is also not visible.

I think a character's color is equal to background color.

This is a similar bug to https://github.com/Cacti/cacti/issues/3535

## To Reproduce

1. Switch to Classic Theme

2. Logout

3. Try to login

## Expected behavior

I should be able to see the placeholder text and what I am typing into the input fields.

## Screenshots

![cacti_login](https://user-images.githubusercontent.com/10856567/99708268-eb3fef80-2a9d-11eb-815f-c72ec0065232.png)

## Desktop (please complete the following information)

- OS: Windows 10

- Browser: Brave, Firefox, Internet Explorer (yuk!)

- Version: latest

## Smartphone (please complete the following information)

- OS: Android 10

- Browser: Brave, Firefox

- Version: latest

## Additional context

I can fix the issue by editing the theme file and adding "color: black" here:

```
# cat /usr/share/cacti/site/include/themes/classic/main.css.fix
.ui-state-default {
        background: #FFFFFF !important;
        border: none;
        font-weight: normal;
        padding: 2px;
        color: black;
}
```

But this is probably not the correct solution.

**Comment by TheWitness** [comment]
Thanks for pointing this out.  Classic is like a burr in my saddle, but so many people love that tombstone theme.

**Comment by xmacan** [comment]
@TheWitness What is wrong on classic theme? I prefere Paw, classic and maybe modern. The others are confusing and ugly (for me). I switch to paw because classic has few bugs. I thought about new Classic+ or fix Classic

**Comment by TheWitness** [comment]
@xmacan, after 18 years.... Nothing is technically wrong with it, but after all that time looking at the same canvas, It'll drive you insane.  Too late for me :)

**Comment by TheWitness** [comment]
Close enough I hope.

![image](https://user-images.githubusercontent.com/1439914/99810911-6ba03800-2b12-11eb-9b95-b3a25c92de85.png)

**Comment by TheWitness** [comment]
Hmm, I copied and pasted and it turned green.  Let me check that color.

**Comment by TheWitness** [comment]
Okay, I think it should look better now.  Though I like your button color, going to defer due to "Classic".  You can fix by "cp -rp classic mytheme".

**Comment by RadekHvizdos** [comment]
Neither changes take any effect in my setup, the input fields do not show the hints or characters I type :(

**Comment by TheWitness** [comment]
Yea, the browsers are being a pain these days.  You have to force a refresh of the CSS even after we hacked and hacked to try to out think them.  After your cache is cleared, it'll look like as below (FF).

![image](https://user-images.githubusercontent.com/1439914/99812034-f46ba380-2b13-11eb-9935-2b3dada89ae0.png)

**Comment by RadekHvizdos** [comment]
I have tested the following scenarios:

Brave and Edge show the hints (not the login credentials), but Internet Explorer and Firefox show neither. I have cleared the browser caches multiple times.

Tested on Android and Windows 10.

**Comment by TheWitness** [comment]
This is IE11 and the current Classic on 1.2.16.

![image](https://user-images.githubusercontent.com/1439914/99862780-07f52980-2b69-11eb-86aa-8b4eede07990.png)

**Comment by RadekHvizdos** [comment]
This is so strange. I have tested this:

PC1 W10, AMD GPU:

![pc1](https://user-images.githubusercontent.com/10856567/99876579-ed1dc600-2bf7-11eb-8523-f328cf26353d.png)

PC2 W10 Intel GPU:

![pc2](https://user-images.githubusercontent.com/10856567/99876584-f5760100-2bf7-11eb-9131-8e5e5c97effc.png)


I have no idea why it works for you and not for me :(

**Comment by RadekHvizdos** [comment]
I should probably also mention that I have another Cacti installation (same version) which exhibits the same behavior. The installations were done on different dates, upgraded to latest version provided by Debian.

**Comment by TheWitness** [comment]
Oh, lol, the input text.  Let me test that too.

**Comment by TheWitness** [comment]
Latest firefox, but not the color of the button, you have some other CSS interfering with the classic theme.  I think if you trace that, you will find your issue.  I'll go ahead and close now, and thanks for pointing out original the issue.

![image](https://user-images.githubusercontent.com/1439914/99880957-c0ac7e80-2be4-11eb-96cd-11273b6a3498.png)
