### ISSUE TITLE
Device failure count setting not respected 

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3940]
Hello Guys 

I just found an issue where when you set a fail count for a specific device that setting is not being respected
the device instead waits for the global fail count to trigger a down event

I have set the device to fail at 1 poll cycle at 1-minute polling 
yet the device wait for 10 minutes which is the setting I have in the device defaults

My test best is 1.2.12 but I am seeing the same thing in 1.2.15

**Comment by TheWitness** [comment]
That's not the same thing.  The fail count is the number of times it's failed since you last reset the counters.  So, you are misunderstanding the purpose of that column.
