### ISSUE TITLE
1.2.15 upgrade to 1.3.0-1 500 Internal Server Error

### ISSUE THREAD

**Issue by KnoAll** [Cacti/cacti#3941]
Getting 500 Internal Server Error upon upgrade. This happens only after clicking the 'Confirm Upgrade' checkbox and the Upgrade button.
I've checked the PHP version is 7.3.x, XML appears to be enabled.

Reboots etc do not seem to make any difference.

**Comment by TheWitness** [comment]
Don't upgrade to that release, it's unstable.

**Comment by KnoAll** [comment]
Is there something more stable that I should try?

**Comment by TheWitness** [comment]
1.2.x branch.
