### ISSUE TITLE
Graph CSV export NaN with wrong date range if browser timezone is different with web server

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#3945]
# Describe the bug
Graph CSV export all data as NaA with wrong date range if browser timezone is different with web server

## To Reproduce
1. Configure web server timezone as EST(-05:00), Browser side timezone is CST(+08:00)
2. Create a new graph, ensure its valid data timerange is less than 13 hours
2. Access Graphs-->Preview
3. Select "Last 4 Hours"
4. Compare params in href of "csv export", and timespans 
 `layout.js -->getTimestampFromDate() convert  timespan date1/date2 to timestamp with browser local timezone`
5. Click "csv export" icon, and check csv file
 ```
"Start Date","2020-11-23 10:37:00"
"End Date","2020-11-23 14:37:00"
.......
"2020-11-23 15:04:00","NaN","NaN"
```

## Screenshots
![image](https://user-images.githubusercontent.com/17589018/100071490-151a5d00-2e76-11eb-9e31-7edf44c7fd33.png)

## Additional context
Maybe,  global_session.php can output web server timezone info as JS variables

**Comment by TheWitness** [comment]
Have you considered a pull request for this @ddb4github?

**Comment by TheWitness** [comment]
Resolved @ddb4github.  Please verify.

**Comment by TheWitness** [comment]
@ddb4github, based upon your comments, I have reworked this changes a little to ensure that all timestamps in the web site align with the browser as well.  Please validate and provide feedback.  This does not change the CLI's.
