### ISSUE TITLE
Spine 1.2.15 - Spine Encountered An Unhandled Exception Signal Number: '6' [11, Resource temporarily unavailable] (Spine thread)

### ISSUE THREAD

**Issue by hariesfn** [Cacti/cacti#3948]
Hi,

I've encountered spine issue in version 1.2.15 with message: "Spine Encountered An Unhandled Exception Signal Number: '6' [11, Resource temporarily unavailable] (Spine thread)"

Spine is used in below environment:
- Cacti 1.2.14
- mysqld  Ver 10.1.47-MariaDB-0ubuntu0.18.04.1
- PHP 7.2.24-0ubuntu0.18.04.7
- Ubuntu 18.04.4 LTS, 8GB of RAM, 4  CPU
- Cacti data collector proccess : 4
- Cacti threads per process : 4
- Number of PHP Script Servers : 4
- Mysql max_connections : 4000
- Cacti Stat: SYSTEM STATS: Time:37.6965 Method:spine Processes:12 Threads:5 Hosts:14 HostsPerProcess:2 DataSources:33924 RRDsProcessed:0

I've tried to search but didn't find that kind of error. Have tried to reinstall the spine but that error still appeared.
Spine Encountered An Unhandled Exception Signal Number: '6' [11, Resource temporarily unavailable] (Spine thread)
I am also curious what number 6 and 11 means, does it have any meaning.

[gdb-result.txt](https://github.com/Cacti/cacti/files/5595862/gdb-result.txt)

**Comment by TheWitness** [comment]
I would say that you should reduce your concurrent processes to like 2, and threads to like 10 at your scale, even 1 process would be sufficient.  This issue belongs in the spine issue tracker.

**Comment by TheWitness** [comment]
Closing this as this is more of a question.  Hopefully the utility page updates make this easier for you.  Basically, each Device takes from one to many threads, depending on Device Threads setting at the Device level.  If you are only polling a few items per host, you should never pick more than 1.  Customers that use Device Threads, generally have 10k+ graphs per device.  So, it takes longer to collect all the data.
