### ISSUE TITLE
Log page should not be empty if no log info exists

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/cacti#3949]
1) Go to Utilities - system utilities 
2) Click Log Administration 
3) Choose File as cacti_stderr.log, page becomes blank --failed, even cacti_stderr.log is empty, the cacti page should not be blank  

Cacti 1.2.15 
FF 83 
rhel7 x64

**Comment by yingbaiibm** [comment]
![Screen Shot 2020-11-25 at 2 28 05 PM](https://user-images.githubusercontent.com/47589910/100191108-8e738780-2f2a-11eb-97d7-90f2151aeafb.png)
![Screen Shot 2020-11-25 at 2 28 19 PM](https://user-images.githubusercontent.com/47589910/100191122-93383b80-2f2a-11eb-8b5f-6a00f469f99a.png)

**Comment by TheWitness** [comment]
@yingbaiibm, I'm not seeing this in a stock environment.  Could this be related to @ddb4github recent pull request?

**Comment by yingbaiibm** [comment]
@TheWitness Check with ddb4github, no relationship with his recent pull request.   **The cacti_stderr.log must be empty,** then the issue can be reproduced.

**Comment by yingbaiibm** [comment]
@TheWitness  check with ddb4github, It's that the cacti can not display Poller Standard Error Log info that set at configuration - settings - path - Poller Standard Error Log  path  when checking Log Administrator page 

![Screen Shot 2020-11-26 at 3 53 44 PM](https://user-images.githubusercontent.com/47589910/100322860-d2848c00-2fff-11eb-815a-5f076d0a7119.png)

**Comment by TheWitness** [comment]
@yingbaiibm, I've been unable to reproduce on my side.  Have @ddb4github put in a pull request once he figures it out

**Comment by TheWitness** [comment]
@yingbaiibm, can you please check for a javascript error on that page when you switch files.  Again, I'm unable to reproduce.
