### ISSUE TITLE
1.2.14 Boost enabled and poller_output_boost_arch_* tables constantly increasing

### ISSUE THREAD

**Issue by g1augusto** [Cacti/cacti#3952]
# Describe the bug

Our CACTI version was upgraded from 1.1.38 straight to 1.2.14 and this is where I started to see the following problem:

Console->Utilities->Boost Status->Boot storage Statistics->Current Boost Table(s) Size: above 2.8 GB!!!

Now opening the main poller database I notice that **poller_output_boost** is usually around few tens of megabytes and I have a constant creation of **poller_output_boost_arch_** tables that seems to me are importing data from the previous poller_output_boost run and that one grew up to 2.8 GB (and counting)

This behavior was not seen in version 1.1.38

Yesterday there were 318 of such **poller_output_boost_arch_** tables, now I just checked that these are 501!

I can see also that the writing on disk of the boost process takes time (5 minutes...) and my server is a _**physical**_ server with dedicated SSD so it makes no sense all of this

Also the boost proces is configured to run every 30 minutes as it does but in the **poller_output_boost_arch_** tables (usually only the last one has data in it, others are at 0) has data queries from 2 hours before...

ADD: 
Apparently it creates them at each poll cycle (5 minutes...) and after the underscore there is the epoch number of the creation time...

![image](https://user-images.githubusercontent.com/26431888/100223675-19995100-2f1c-11eb-9dd0-c85c5f64277e.png)

**Comment by TheWitness** [comment]
Did you also update spine?

**Comment by TheWitness** [comment]
This is not a very large count BTW, I have customers that'll have 20+ million rows in there.  However, if you are using MariaDB 10.1+, you should consider moving this table to InnoDB.  Save your memory.

```alter table poller_output_boost engine=InnoDB;```

**Comment by g1augusto** [comment]
Hi, thanks for replying

I didn't mean the 518 is not the rows in the table but the number of **poller_output_boost_arch_xxx** tables.

I haven't seen anything like this behavior in version 1.1.38, is this normal behavior now ?

PS: In the screenshot I deleted the old tables since these were unused

**Comment by g1augusto** [comment]
> Did you also update spine?

Yes spine was updated afterwards I realized this was happening, now spine is 1.2.15 and cacti 1.2.14

**Comment by TheWitness** [comment]
Those arch tables disappear after boost is done.

**Comment by g1augusto** [comment]
> Those arch tables disappear after boost is done.

Thanks for your answers and apologies for replying late.

I realized that the update that was pushed before was not comprehensive of spine update so I did that part, at some point I had to reboot the main poller and when back online the archive tables were gone and everything is working normally*

* = normally up to a point :) because one of my remote pollers for which I had no problem before, now is in **heartbeat** state and the funny thing is that it shows the following problems (that other 3 pollers does not):

1. heartbeat state in Console->Data Collection->Data Collectors menu
2. When I launch a Connection Test on the poller entry it says "Connection Successful" as to indicate that DB to DB connection should be fine
3. If I run realtime graph on devices polled by that remote poller it works
4. I get no data send to the main poller apparently as it has all NaN data for all data sources from that poller

Now all versions are aligned to CACTI 1.2.14 and spine 1.2.15 and no other pollers has problems

**Comment by TheWitness** [comment]
Grab the latest 1.2.x branch and then re-sync and the 'heartbeat' issue will be resolved.

**Comment by g1augusto** [comment]
I did as you suggested, thanks.

Upgrade was smooth but the single poller in question instead of getting the update from the main poller like the others is proposing me the update wizard to _downgrade_ apparently from 1.2.15 to 1.2.14 (it even warns me if I go on 3 screens in the wizard :) )

My last entry here to not flame this topic, do you have a suggestion how to restore this poller or should I say adieu to it ?

**Comment by TheWitness** [comment]
If thats your plan, and don't want the messages, just keep the "cacti_version" file whatever you want it to be.

The whole downgrade thing is unfinished business.

**Comment by g1augusto** [comment]
Well, I would like it to upgrade as the others, just I don't know why is asking to downgrade to the old version it was supposed to be from the new version it apparently got installed.

Probably is some unfinished upgrade from when I was on version 1.2.14 and somehow it triggered now? How do I fix it? 
drastically removing the full folder and then passing it again ?

**Comment by TheWitness** [comment]
The cacti_version file is in the /var/www/html/cacti/include directory.
