### ISSUE TITLE
snmpagent_poller_exiting warning in v 1.2.14

### ISSUE THREAD

**Issue by ataullahsaleem** [Cacti/cacti#3954]
Hello cacti Forum !
i am facing mentioned errors suddenly and when device goes down .i attached snapshot please help me 
![2020-11-26_11-07](https://user-images.githubusercontent.com/70479567/100314395-59be0980-2fd8-11eb-9d78-3a2fcbb66c42.png)
WARNING: There are 1 processes detected as overrunning a polling cycle for poller id 1, please investigate.
WARNING: Poller Output Table not empty for poller id 1. Issues: 10, DS[214, 214, 353, 209, 161, 209, 353, 203, 619, 203].

thanks you cacti group.

**Comment by TheWitness** [comment]
I'm assuming php74?  If you can update that file from the 1.2.x branch and report back, that would be good.

**Comment by ataullahsaleem** [comment]
Thanks you Cacti Form for the Quick respond to me 
i have using PHP version !
**PHP 7.4.12 (cli) (built: Oct 31 2020 17:04:25) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.12, Copyright (c), by Zend Technologie**s
i have using 1.2.14 updates all files .

**Comment by TheWitness** [comment]
Update to the 1.2.x branch right away.  It's stable.  Report back.

**Comment by ataullahsaleem** [comment]
please share me link where i can download all update data 
thanks you once again

**Comment by TheWitness** [comment]
https://github.com/Cacti/cacti/

1) Click on code, 
2) Select 1.2.x branch, 
3) Then download.  

Alternately, from Linux

```sh
git clone -b 1.2.x https://github.com/Cacti/cacti.git /someplace
/bin/cp -rp /someplace/* /var/www/html/cacti
chown -R apache:apache /var/www/html/cacti
```

**Comment by ataullahsaleem** [comment]
thanks you very much for the kind supporting 
    On Thursday, November 26, 2020, 06:09:49 PM GMT+5, TheWitness <notifications@github.com> wrote:  
 
 


https://github.com/Cacti/cacti/
   
   - Click on code,
   - Select 1.2.x branch,
   - Then download.

Alternately, from Linux
git clone -b 1.2.x https://github.com/Cacti/cacti.git /someplace
/bin/cp -rp /someplace/* /var/www/html/cacti
chown -R apache:apache /var/www/html/cacti

**Comment by ataullahsaleem** [comment]
thanks you very much for the kind supporting 
have a nice day !

**Comment by TheWitness** [comment]
Assuming this is corrected now.  This had been hidden, and with the advent of PHP7.4, it was just recently exposed in automated testing.

**Comment by ataullahsaleem** [comment]
dear sir sorry to disturb you !
i have a question to you ,i replace all files one by one or only one second i have using Ubuntu ,i can perform this task by using CLI ?
    On Thursday, November 26, 2020, 06:26:44 PM GMT+5, ataullah saleem <ataullah.saleem@yahoo.com> wrote:  
 
  thanks you very much for the kind supporting 
    On Thursday, November 26, 2020, 06:09:49 PM GMT+5, TheWitness <notifications@github.com> wrote:  
 
 


https://github.com/Cacti/cacti/
   
   - Click on code,
   - Select 1.2.x branch,
   - Then download.

Alternately, from Linux
git clone -b 1.2.x https://github.com/Cacti/cacti.git /someplace
/bin/cp -rp /someplace/* /var/www/html/cacti
chown -R apache:apache /var/www/html/cacti

**Comment by ataullahsaleem** [comment]
once i updated the file what you had said 
the following errors occurs 
![image](https://user-images.githubusercontent.com/70479567/100451771-c836c080-30d9-11eb-937b-e91b14b18a96.png)

**Comment by ataullahsaleem** [comment]
![image](https://user-images.githubusercontent.com/70479567/100453183-5a3fc880-30dc-11eb-88f9-9298b7a241ba.png)

**Comment by TheWitness** [comment]
You have made some mistake.  Check your work.  The all.css file is in the 1.2.x branch.
