### ISSUE TITLE
Wrong language displayed / Config / User & Groups

### ISSUE THREAD

**Issue by C00kiekiller** [Cacti/cacti#3955]
# Describe the bug

Wrong Translation  **chinese traditional** instead of **german**

## To Reproduce

1. Go to 'Configuration'

2. Click on 'Users or Users Group'

3. 'change language to german in profile and retun to Configuration / User & Users Group'

4. See error > Wrong Translation  **chinese traditional** instead of **german**
## Expected behavior

German translation for Allow "ERLAUBEN"

## Screenshots

![2020-11-26 09_39_42-cacti](https://user-images.githubusercontent.com/16733284/100327432-933c4800-2fcb-11eb-9828-105b33f3917c.png)

## Desktop (please complete the following information)

- OS: Windows 10 

- Browser Chrome, Edge, Firefox

- Version latest each browser

## Additional context

Update from 1.2.14 to 1.2.15

Englisch translation works fine

**Comment by TheWitness** [comment]
Can you modify the German po file through a pull request?  We've been having issues with the translate site and need to upgrade it, but it's complicated and not php.  I normally eat celery, but I guess it's used for software development too.

**Comment by TheWitness** [comment]
@C00kiekiller, I'm going to keep this one open for a bit.  We are working on getting our Translate site back up and operational, and at that time, we will sweep the translation files and do one big commit.

But will need help like yours to verify the strings are all translated well on that site.

**Comment by TheWitness** [comment]
@C00kiekiller,

We've relaunched the https://translate.cacti.net.  Go there, reset your password, and then simply fix these errors there.  You changes will be committed to the various Cacti repos within 24 hours of the change.

Larry
