### ISSUE TITLE
Change in the way data query are handled on create new graph on 1.2.15

### ISSUE THREAD

**Issue by arno-st** [Cacti/cacti#3958]
# Describe the bug
I create a new template for a profile monitoring on a F5, htis configuration is working on a cacti 1.2.14 production server, but not on the test server on 1.2.15

## To Reproduce
Having an F5 for the test ?
Otherwise i don't know .

## Expected behavior
When I add the data query into the host, and do a debug, it find all 29 index and data source.
but when I go to create a graph, it tell me their is 29 entry, but none are displayed

Every thing is on this forum message:
https://forums.cacti.net/viewtopic.php?f=12&t=61410

**Comment by TheWitness** [comment]
Can you post the XML file.  Also, post the differences between the verbose output between versions.  I don't recall anything changing here, but that may just be old brain cells falling out.  Looking at the changelog, nothing jumps out at me.

**Comment by arno-st** [comment]
Well sudently it works !! I have no clue why, but after a few trial and error, without changing anything the browser give me the value I requested!!
And since then all is working!!,
So just close it for now, since I will no longer be able to provide usefull input
