### ISSUE TITLE
The 10 seconds polling is only valid for past data in one day on 1.2.15

### ISSUE THREAD

**Issue by terrellgf** [Cacti/cacti#3964]
# Describe the bug

I created a Data Source Profile with the following configuration on 1.2.15 ：
Polling Interval：Every 10 Seconds
Data Retention: 7 Days
When I check the data of the most recent day, the time interval of data recording is 10 seconds.
When I check the data of the last 2 days, the time interval of data recording is not 10 seconds but 20 seconds.
For the last 3 days of data, the time interval is 30 seconds.
For the last 4 days of data, the time interval is 40 seconds.
For the last week of data, the time interval is 60 seconds.
According to my Data Source Profile configuration, doesn't cacti save a data every 10 seconds for 7 days?

## To Reproduce

Always

## Expected behavior

Save a data every 10 seconds for 7 days

## Screenshots

![image](https://user-images.githubusercontent.com/54665471/100569950-82147380-330a-11eb-84c0-f86330c712b6.png)
![image](https://user-images.githubusercontent.com/54665471/100570005-9ce6e800-330a-11eb-8c1a-be000a23278c.png)
![image](https://user-images.githubusercontent.com/54665471/100570069-b720c600-330a-11eb-848d-86ca3db5979b.png)
![image](https://user-images.githubusercontent.com/54665471/100570135-d881b200-330a-11eb-81a6-5bcd802769a7.png)
![image](https://user-images.githubusercontent.com/54665471/100570157-efc09f80-330a-11eb-8cd9-fceffad56702.png)
![image](https://user-images.githubusercontent.com/54665471/100570175-036c0600-330b-11eb-8ffb-0a5000b2f204.png)
![image](https://user-images.githubusercontent.com/54665471/100570212-28607900-330b-11eb-89a5-1d285f6ad8a4.png)
![image](https://user-images.githubusercontent.com/54665471/100570235-3f06d000-330b-11eb-8618-4e3712735254.png)
![image](https://user-images.githubusercontent.com/54665471/100570273-5e9df880-330b-11eb-8626-5bad5558a103.png)
![image](https://user-images.githubusercontent.com/54665471/100570301-737a8c00-330b-11eb-8fe0-a37ca66d6aa5.png)

**Comment by TheWitness** [comment]
You may be running up against a maxrows setting.  Search for the rows setting in lib/red.php and increase it and let us know if changing that fixes this.

**Comment by terrellgf** [comment]
> You may be running up against a maxrows setting. Search for the rows setting in lib/rrd.php and increase it and let us know if changing that fixes this.

I changed maxrows from 10000 to 100000 in rdd.php, and then I directly checked the result in the cacti graphics. It met my expectations, but there is a small problem:
Presets          Polling Interva
Last day         10s (is ok)
Last 2 days     10s (is ok)
Last 3 days     10s (is ok)
Last 4 days     10s (is ok)
Last 6 days 23 hours 59 min 10s (is ok)
Last Week      60s (Should be 10 seconds)
I guess the maximum value is less than 60480 rows (it does not contain 60480 rows).
I am not sure whether it is a bug.
![image](https://user-images.githubusercontent.com/54665471/100733142-b1a9a580-3408-11eb-96be-55385c3117e5.png)
![image](https://user-images.githubusercontent.com/54665471/100733713-8e332a80-3409-11eb-885b-dc5bd3ff59a6.png)

**Comment by TheWitness** [comment]
Try doing a fetch from the command line.

```sh
rrdtool fetch file.rrd [options]
```

**Comment by terrellgf** [comment]
> Try doing a fetch from the command line.
> 
> ```shell
> rrdtool fetch file.rrd [options]
> ```
 /usr/bin/rrdtool fetch /opt/cacti/rra/hadoop-docker1_traffic_in_1099.rrd LAST
[hadoop-docker1_traffic_in_1099.rrd.log](https://github.com/Cacti/cacti/files/5622484/hadoop-docker1_traffic_in_1099.rrd.log)

**Comment by TheWitness** [comment]
So, if you simply remove the -rows option, are you getting all the data?

**Comment by terrellgf** [comment]
> So, if you simply remove the -rows option, are you getting all the data?

# /usr/bin/rrdtool fetch /opt/cacti/rra/hadoop-docker1_traffic_in_1099.rrd
ERROR: Usage: rrdtool fetch <file> <CF> [options]

**Comment by TheWitness** [comment]
Well, keep dinking with it until you get a good answer.  Keep us posted.

**Comment by TheWitness** [comment]
Any updates?  Ball in your court.

**Comment by TheWitness** [comment]
No feedback.

**Comment by terrellgf** [comment]
> No feedback.

I don’t know what else can I do?

**Comment by TheWitness** [comment]
Well, once you get fetch figured out, you can let us know what you had to change.  Maybe open a pull request to propose changes.

**Comment by TheWitness** [comment]
If you can get fetch to return 10k rows, then cacti can too.

**Comment by terrellgf** [comment]
> If you can get fetch to return 10k rows, then cacti can too.

I seem to have found the answer.

For example, under the premise that I triggered the query of the last week's data at a certain time between 12/9/2020 16:30:00 to 16:30:09, the query result shows that the time of the first data is 12/ 2/2020 16:30:10, and the time of the last piece of data 12/9/2020 16:30:00, a total of 60480 rows of data. 
So as long as my query time is later than 12/9/2020 16:30:09 (such as 16:30:11), then the time of my last data will not be 16:30:00, but 16:30:10 ( Polling every ten seconds). That is, the data totals 60481 rows, which exceeds the pre-defined 60480 rows, so the data archive is an interval of 1 minute.

I suggest you make the data query time accurate to the second level. So that this problem can be solved. Because the polling time has reached the level of every 10 seconds. So in my opinion, the query time is accurate to the second level is matched and reasonable.

**Comment by TheWitness** [comment]
Can you please articulate your proposed changes through a pull request?  It's not that difficult once you get the hang of it.

**Comment by terrellgf** [comment]
> Can you please articulate your proposed changes through a pull request? It's not that difficult once you get the hang of it.

Now I don’t have much energy to learn and fix bugs about date query accuracy, but I can pull requests for the maximum row parameter

**Comment by TheWitness** [comment]
That would be great.
