### ISSUE TITLE
Unable to change pages between External Links

### ISSUE THREAD

**Issue by zuka1337** [Cacti/cacti#3967]
Hello Guys,

## The issue:
As the title says I'm unable to change between external link pages:

![external_p](https://user-images.githubusercontent.com/57998098/100632405-b137de80-3324-11eb-9bb7-7d909b691a2f.gif)

Also, if you delete all links, should the mysql id autoincrement row go back to 1?

```
 SELECT max(id) FROM external_links;
+---------+
| max(id) |
+---------+
|       6 |
+---------+
```

No errors on the Console.
No plugins.
Cacti Version 1.2.14

**Comment by cigamit** [comment]
Have you tried a different theme?
And no, auto increment will not go back to 1, thats not how auto increment in mysql databases works.

**Comment by zuka1337** [comment]
Only the classic works, for the other ones I have the same issue..

**Comment by TheWitness** [comment]
Update to 1.2.16.

**Comment by zuka1337** [comment]
There's a fix without full upgrade?
Kind need to test before updating..

**Comment by TheWitness** [comment]
It works on that version, yes.  Was reported a while ago.

**Comment by zuka1337** [comment]
Thank you
