### ISSUE TITLE
SNMPv3 Password Length Limit

### ISSUE THREAD

**Issue by Ratief** [Cacti/cacti#3969]
Cacti Version: 1.1.38
OS: Ubuntu 18.04.4 LTS

I am switching to SNMPv3 and it took me almost 2 hours to discover that Cacti is *silently* limiting the SNMPv3 password length to 50 characters (via HTML maxlength). I have been using a longer password for my Nagios installation so I know that SNMPv3 supports longer passwords. Is where a reason why Cacti is limiting this password? The SNMP community string is limited to 100 characters.

I believe that the default varchar length is 255 and as far as I have researched there is no reason to limit a varchar to less as you will not gain any performance benefits in doing so.

If the above is correct it would be nice if the SNMPv3 password could be increased to 255 characters. The SNMPv3 privacy password should also be increased from 200 to 255 as well (I have no idea why they have different lengths).

**Comment by TheWitness** [comment]
It's likely that no one has reported it.  Most people us shorter password and passphrases, so this hasn't come up in nearly 18 years.  I suspect you are not the first, but the first to report it. It's a trivial fix in any event.

**Comment by TheWitness** [comment]
So, upon further review, it may be easy to change the forms, but the table widths are 50 characters for password, and 200 for passphrase.  Can you make accommodations for that?  If not, we would gladly accept a pull request to fix this.

**Comment by TheWitness** [comment]
I have fixed the issue by which you could type more characters than are supported.  However, if you want more characters, you will need to submit a pull request for.  Thanks for reporting this!
