### ISSUE TITLE
Cacti 1.2.16 upgrade: cannot proceed past default automation step

### ISSUE THREAD

**Issue by KnoAll** [Cacti/cacti#3972]
In the upgrade process I am not able to proceed past the page with Default Automation settings. Changing any of the settings does not make any difference. I'm upgrading from 1.2.15

CentOS 7
Chrome and Firefox

**Comment by TheWitness** [comment]
Run the upgrade from the cli but before you do that, upload your install logs.

**Comment by KnoAll** [comment]
Was not able to reproduce this until now...
[install-complete.log](https://github.com/Cacti/cacti/files/5667730/install-complete.log)
[install-general.log](https://github.com/Cacti/cacti/files/5667731/install-general.log)
[install-sync.log](https://github.com/Cacti/cacti/files/5667732/install-sync.log)

**Comment by TheWitness** [comment]
We likely need a screen2gif of the process, with the debug console open to see any JS errors.

**Comment by netniV** [comment]
Yes, the install logs are not really showing anyway.  You may need to increase their logging level but also provide a screen grab of the process and any javascript console errors.  You would be better sending them to us by email since those will likely have more confidential information in them.

**Comment by TheWitness** [comment]
No feedback.
