### ISSUE TITLE
Problems parsing Multi SNMP OID! (oid: )

### ISSUE THREAD

**Issue by ataullahsaleem** [Cacti/cacti#3973]
hello cacti Forum
i have set Generic SNMP host template for Some device in v 1.2.15 and have set SNMP OID values 1 for all Generic SNMP devices 
please help me [
![Screenshot from 2020-12-02 11-49-56](https://user-images.githubusercontent.com/70479567/100838871-101c6580-3495-11eb-921e-8249d53b013b.png)

**Comment by xmacan** [comment]
Github issues are for reporting errors or feature requests. Similar things (installation, configuration, operational problems, ..) belongs to forums.cacti.net
https://forums.cacti.net/viewtopic.php?t=59475

Try to reindex your device

**Comment by ataullahsaleem** [comment]
> Github issues are for reporting errors or feature requests. Similar things (installation, configuration, operational problems, ..) belongs to forums.cacti.net
> https://forums.cacti.net/viewtopic.php?t=59475
> 
> Try to reindex your device

how to reindex device please help ?

**Comment by ataullahsaleem** [comment]
> > Github issues are for reporting errors or feature requests. Similar things (installation, configuration, operational problems, ..) belongs to forums.cacti.net
> > https://forums.cacti.net/viewtopic.php?t=59475
> > Try to reindex your device
> 
> how to reindex device please help ?

ok i got the page to re-index the device

**Comment by ataullahsaleem** [comment]
> Github issues are for reporting errors or feature requests. Similar things (installation, configuration, operational problems, ..) belongs to forums.cacti.net
> https://forums.cacti.net/viewtopic.php?t=59475
> 
> Try to reindex your device

just re-indexed the affected devices , errors remain the same

**Comment by TheWitness** [comment]
I would replace that command with a script that check for the empty output and returns 0 when it encounters that.  This is not really a Cacti issue, but an implementation issue.  So, i'll go ahead and close, but you may continue to comment.

**Comment by TheWitness** [comment]
Oh wait, I see there are multiple issues in your output.  Problem happens when you post multiple issues in one ticket.  Let me re-open for a moment.

**Comment by TheWitness** [comment]
1) Edit the Data Template, post an image of the Data Template
2) Edit the Data Source, post an image of the Data Source

**Comment by ataullahsaleem** [comment]
i edited data source of affected graph and found there is no SNMP OID values,i disable the affected data source and everything's working normal 
thanks for the supporting 

    On Wednesday, December 2, 2020, 5:44:09 PM GMT+5, TheWitness <notifications@github.com> wrote:  
 
 

   
   - Edit the Data Template, post an image of the Data Template
   - Edit the Data Source, post an image of the Data Source
