### ISSUE TITLE
CPU 100% and PHP warnings

### ISSUE THREAD

**Issue by MikeSierraRO** [Cacti/cacti#3974]
# Describe the bug

I just logged into the server that's hosting Cacti, and I saw that the CPU's at 99.9% and I checked the logs, please see attached.

## Screenshots
![cactierr](https://user-images.githubusercontent.com/56639628/100916782-e5ef9580-34de-11eb-84ab-ef73e58ff15c.png)

I checked the Automation section, if there were another devices added automaticaly by Cacti, but there's not.

**Comment by bmfmancini** [comment]
Wow your ips are funky they are all invalid

I think there was a fix to this recently where someone had a similar issue

**Comment by MikeSierraRO** [comment]
Yes, that was also me. Then the issue was caused by the Automation devices, now there's no automation device and Automation it's disabled to avoid this kind of sittuation.

Checked the Devices tab too, only known devices are located there.

**Comment by TheWitness** [comment]
You have an error in you subnet definition.  Update to 1.2.16 and re-save the definition.

**Comment by TheWitness** [comment]
This is duplicate from another logged and resolved in 1.2.16.

**Comment by TheWitness** [comment]
So, in Automation Networks you have no networks defined?  Have you updated to 1.2.16?

There is nothing in cacti that would scan an invalid range.  Maybe someone wrote a plugin for you that leverages the Cacti API?
