### ISSUE TITLE
Cron is out of sync with the Poller Interval

### ISSUE THREAD

**Issue by ataullahsaleem** [Cacti/cacti#3975]
**POLLER: Poller[Main Poller] WARNING: Cron is out of sync with the Poller Interval! The Poller Interval is '60' seconds, with a maximum of a '60' second Cron, but 120.5 seconds have passed since the last poll!**

i have data collector setting Processes:2/thread 15: PHP scripts 5 and poller interval time is 1 minutes,suddenly i got mentioned error

**Comment by netniV** [comment]
The error is because between the time two instances of polling was run, 120 seconds and you have it defined as being for 60s.  Check your cron logs to see why there was an extended period before being run if your schedule is set for 60s.

**Comment by TheWitness** [comment]
You could have been mucking with the files too and had a syntax error that kept Cacti from running properly.

**Comment by ataullahsaleem** [comment]
![image](https://user-images.githubusercontent.com/70479567/101165362-5a9a0f80-3658-11eb-865f-e3ab9c549c12.png)

and cron tab for cacti poller 
*/1 * * * * www-data php /var/www/html/poller.php > /dev/null 2>&1

**Comment by TheWitness** [comment]
In 1.2.16 there is a cactid.php systemd service.  The unit file and instructions are in the service directory, why don't you try that instead.

**Comment by TheWitness** [comment]
Also, disable snmpagent if you don't plan on using it.
