### ISSUE TITLE
CMDPHP Input Validation Not Performed for Tree

### ISSUE THREAD

**Issue by zuka1337** [Cacti/cacti#3978]
Hello Guys,

#### Graph_tree page is blank:

![image](https://user-images.githubusercontent.com/57998098/101044272-1125c380-3577-11eb-9884-98de52affbb1.png)

Updated to 1.2.16 today, and I have this issue:

`2020-12-03 14:39:42 - CMDPHP Input Validation Not Performed for 'host_id' Backtrace: (/tree.php[114]:display_graphs(), /tree.php[1791]:get_request_var(), /lib/html_utility.php[394]:html_log_input_error(), /lib/html_validate.php[44]:cacti_debug_backtrace())`

For new trees or older ones, the same happend.

**Comment by zuka1337** [comment]
Very strange, seems to work on Mircosoft Edge..

**Comment by zuka1337** [comment]
I'm Closing, since it may be an Browser problem thing.

**Comment by TheWitness** [comment]
It's a bug.
