### ISSUE TITLE
Cacti 1.2.15 login Issue Username and Password Incorrect

### ISSUE THREAD

**Issue by Babat28119** [Cacti/cacti#3979]
Dear Support,

Kindly be informed that i am currently on cacti 1.2.15 but user account created find it difficult to login. they keep getting Wrong Username and Password despite having the valid credentials. i have tried clearing browser history use different browser but still the same issue

Await your swift response.

![login issue1](https://user-images.githubusercontent.com/69158129/101045896-eb9db780-3580-11eb-9b36-b88269808683.JPG)
![login issue](https://user-images.githubusercontent.com/69158129/101045903-eccee480-3580-11eb-829b-befeb690ba46.JPG)

**Comment by TheWitness** [comment]
These issues should be taken up on the forums.  You likely have permission problem in your PHP session directory, or the /var volume is full.
