### ISSUE TITLE
[Cacti 1.0.4] When creating a new tree, the Publish checkbox is not honored

### ISSUE THREAD

**Issue by thurban** [Cacti/cacti#398]
When creating a new tree item in 1.0.4 (Console->Tree->Add), the Publish checkbox is not honored. When hitting the create box the new tree is being added as not published.   

Editing the newly created tree and enabling the publish checkbox does work and sets the "Published" field to yes.

Server:
Cacti 1.0.4
Centos 7

Client:
Chrome Version 56.0.2924.87
Windows 10 64 bit

**Comment by cigamit** [comment]
Resolved through the removal of the checkbox at initial create time.  Thanks for reporting!
