### ISSUE TITLE
Short read while reading rrd->stat_head error in cacti 

### ISSUE THREAD

**Issue by jagadeesanmuthuvel** [Cacti/cacti#3983]
Hi,
I am facing the below error in cacti graph

"Short read while reading rrd->stat_head error in cacti "

I am running cacti in XAMP in windows server

Could anyone help to fix this issue?

![image](https://user-images.githubusercontent.com/40339983/101194877-9e0a7300-3684-11eb-842d-da877b6e3199.png)

**Comment by cigamit** [comment]
Not a Cacti bug.  Please ask in the forums instead.  Also you didn't state Cacti version number, RRDTool Version, and whether you have the proper versions selected in Cacti.   For Windows a lot of people have seen this error when using newer versions of RRDTool.

**Comment by TheWitness** [comment]
It's either an rrdfile corruption or bug.  If it's not impacting other graphs from the same template, the it's a damaged rrdfile, and your only hope is to delete it or restore it from before it was corrupted.
