### ISSUE TITLE
Graph-name Sorting

### ISSUE THREAD

**Issue by hariesfn** [Cacti/cacti#3987]
Hi,

I am using Cacti 0.8.8h
Is it possible to use sorting in a tree by its graph name. I have tried to use alphabetical ordering, numeric ordering, and natural ordering, but it seems ordering only take effect on the tree name only, not on the graph name also.

Is it correct ?

![image](https://user-images.githubusercontent.com/12947828/101282028-244dc300-3805-11eb-9960-caf18dcc5f14.png)

**Comment by TheWitness** [comment]
Right click on the branch.

**Comment by hariesfn** [comment]
Sorry, please explain more about right click that you mention.

**Comment by TheWitness** [comment]
My bad, we do not support 0.8.x any longer.  In the 1.2 branches, you simply right click on the branch and set the sort order.  You can also set the sort order on the 0.8.x at the very top branch from manual to the sort type you want, and then for the children, you can set it to inherit, but it's been so long don't even know how the page looks.
