### ISSUE TITLE
Cacti plot graph data one day back

### ISSUE THREAD

**Issue by mosharaflink** [Cacti/cacti#3989]
Hi
Recently I have install cacti version 1.2.15. All things are going well but having an interesting issue. The graph plotting/showing on the graph is 1 day back. I have added a screenshot for your reference to review. 

What is the issue and how can we resolve it. 

--

![image](https://user-images.githubusercontent.com/32505239/101310616-995ae000-3879-11eb-85b8-10b8792faff1.png)

**Comment by bmfmancini** [comment]
Is your php timezone correct ?

**Comment by mosharaflink** [comment]
@bmfmancini I got the issue; there were two timezones that were active and for what the output is strange. Now after correcting the timezone graph now shows normal. Thank you for quick response. 


![image](https://user-images.githubusercontent.com/32505239/101311799-6c5bfc80-387c-11eb-9c53-4c25b7dca4d3.png)
