### ISSUE TITLE
Utilities- System Utilities - technich support-php info is not a row, should not use form_alternate_row()

### ISSUE THREAD

**Issue by YongBoLiu** [Cacti/cacti#3990]
# Describe the bug

A theme has a feature, mouse over event added for all table rows even the rows are not select-able.
As the php info has many rows in one form_alternate_row() call, the page looks ugly when mouse over it.
form_alternate_row() in here is misleading to other themes to deal with odd, even, tableRow class.

## To Reproduce

1. Add a new theme like spectrum for highlight-able even the rows are not select-able.

2. Go to Utilities- System Utilities - technich support-php info page.

3. The page looks ugly when mouse over it.

## Expected behavior

We should not use form_alternate_row() for one row with many rows' content.

**Comment by TheWitness** [comment]
@YongBoLiu, close once you have it committed and the CHANGELOG is properly updated.
