### ISSUE TITLE
Cacti device rule

### ISSUE THREAD

**Issue by cactiuser1** [Cacti/cacti#3992]
Hello everyone. Somebody tell me why only one device rule template works for me?  I noticed that it only works if it is at the top of the list.  when I start any network with a range of addresses, it automatically assigns only one template, which is at the top of the device rule list.  If i swap templates and then another one works.  If i remove the automatic addition of devices and look at the list of discovered devices,i  see  in the os section there is only one template from top of the list.  in generally only one template works which is at the top of the device rules list. Please help me. Sorry for my English. Thanks

**Comment by cactiuser1** [comment]
Somebody help me please

**Comment by TheWitness** [comment]
This is a question for the forums and not here.  Take it up there please.
