### ISSUE TITLE
Question: How to debug graphs that do not update anymore?

### ISSUE THREAD

**Issue by tersmitten** [Cacti/cacti#3995]
After an upgrade from `0.8.8b` to `1.2.16` some of my graphs do not update anymore. 

![graph_image](https://user-images.githubusercontent.com/3392962/101358769-9b359b00-389b-11eb-893c-d9e20e1f0c9f.png)
 
I know there have been (some) issues with the Percona Monitoring Plugins for Cacti and I already [fixed some of them](https://github.com/tersmitten/percona-monitoring-plugins/pull/2/files) / use suggested fixes, but still no luck. I don't mind debugging / fixing this even further, but I'm a bit out of options.

The data gathering script seems to work:

```sh
# su - www-data -s /bin/bash -c 'env -i php /var/lib/ansible/cacti-server/checkouts/cacti/scripts/ss_get_mysql_stats.php --host example.com --user cacti --pass secret --server-id --items ju,jv,jw,jx,jy,jz,kg,kh,ki,kj,kk --nocache';
ju:3626511 jv:3784 jw:2688314 jx:281823 jy:62 jz:0 kg:0 kh:0 ki:5989 kj:3 kk:0
```

But still no points in the graph(s). All the graphs that use `ss_get_by_ssh.php` do work, but the MySQL ones (`ss_get_mysql_stats.php`) do not.

Do you have any suggestion?

Thanks in advance

**Comment by TheWitness** [comment]
Check the poller cache for the entries.  If they are not there, repopulate it.

**Comment by tersmitten** [comment]
It seems to be there:

```
Script: /usr/bin/php -q /var/lib/ansible/cacti-server/checkouts/cacti/scripts/ss_get_mysql_stats.php --host 'example.com' --items ip,iq,ir,iu,ix,iz --user '' --pass '' --port '' --server-id ''
--
RRD: /var/lib/ansible/cacti-server/checkouts/cacti/rra/example_com_threads_connected_1137.rrd
```

**Comment by tersmitten** [comment]
I ran the exact command above and found out that the mysql credentials that I supplied in my config file were the wrong ones.

![image](https://media.giphy.com/media/XeLcgh8gT8o0F5SQ8i/giphy.gif)

**Comment by tersmitten** [comment]
Thanks for helping out
