### ISSUE TITLE
[CACTI 1.2.16] latest develop branch - No tools link after graphs

### ISSUE THREAD

**Issue by anarkia1976** [Cacti/cacti#3998]
After the latest upgrades there are no longer any buttons / links next to the device graphics:

![image](https://user-images.githubusercontent.com/1744639/101647838-7ecf6500-3a39-11eb-8a09-1a1ad2fba533.png)

This instead is an example in previous releases in previous releases:
![image](https://user-images.githubusercontent.com/1744639/101647683-4e87c680-3a39-11eb-869a-8719d29bda6b.png)

The problem is also present when changing browser or theme.

thanks a lot.

**Comment by zuka1337** [comment]
Hello,

Check this:

![image](https://user-images.githubusercontent.com/57998098/101655193-3ca62380-3a39-11eb-9de6-3884548985e6.png)

**Comment by anarkia1976** [comment]
![Uploading image.png…]()

**Comment by zuka1337** [comment]
Uncheck this --> Hide Graph Drilldowns

**Comment by anarkia1976** [comment]
@zuka1337 wow, thanks a lot. fixed.

**Comment by anarkia1976** [comment]
Thanks for support.

**Comment by TheWitness** [comment]
Hmm, that's what I do to 'check all' means grant and not revoke.  We may have to 'undo' that at some point.

**Comment by netniV** [comment]
This issue was raised as potentially a problem by the changes made in a pull request recently.  We should review as soon as possible.
