### ISSUE TITLE
Poller Recovery is not predictable

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#4002]
# Describe the bug

Due to logic in global.php, there are cases where if a remote data collector goes offline, it may not recover as expected, even though it's fully recovered.

## Expected behavior

Cacti Remote Data Collectors should report the correct status at all times.

**Comment by netniV** [comment]
Do you have the circumstances ?

**Comment by TheWitness** [comment]
It was me doing bad things developing support for Galera.  Closing.

**Comment by TheWitness** [comment]
It's a good think I was testing before committing.  Deleted all my devices working with remote data collectors.

**Comment by TheWitness** [comment]
Reopening.  Remember why I opened in the first place.  You will see the diff shortly.
