### ISSUE TITLE
Support splitting read and write ports for Cacti high availability database setups

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#4003]
# Feature Request

## Is your feature request related to a problem? Please describe

Yes.  Currently, Cacti has the ability to share login sessions across load balancers.  So that, for example, you can have multiple Web Servers fronting Cacti at one time.  However, it has no way to separate READ and WRITE traffic to support technologies like MariaDB Galera, or MySQL Clustering.  

One method to achieve this would be to configure your load balancer, for example HA Proxy, Citrix NetScaler, or MariaDB MaxScale, to forward READ traffic to one set of nodes, and WRITE traffic to a primary writer.

When MariaDB or MySQL are setup in Clusters, the generally require that WRITE traffic is set to a primary or master node.  Though theoretically, for example, in a MariaDB Galera, you can technically have a multi-master setup, writing to random nodes can lead to race conditions and decreased performance.

## Describe the solution you'd like

Allow Operations like db_fetch_*() which are 'Row' and 'Cell' type functions to be redirected to set of READER nodes allowing the load balancer to determine the node to respond to these queries, and other 'Exec' type calls such as sql_save(), db_execute(), db_execute_prepared() to go to a WRITE node.  This would be done by the proxy advertising READ activities type activities on a separate port from WRITE activities, and the setting up differing rules based upon the port that the traffic arrives at.

* In the case of WRITE type queries, all traffic will goto the 'primary' node that is available in the cluster, with no real load balancing
* In the case of READ type queries, traffic can be load balanced using a number of techniques such as lead connections, lowest load, etc.

## Describe alternatives you've considered

I've considered various SQL Query FILTERING techniques at the load balancer to redirect traffic.  The problem with this, is that for cases like the Cacti data collectors, there are times when we just want to use the WRITE node for all activity, like in the case of SPINE this will yield real good performance, while allowing the Script Server to use the READ nodes.  

One of the reasons for this, it that many people use memory tables for some of the output for performance reasons.  Since MEMORY tables are not supported using Technologies like MariaDB Galera, simply FILTERING of SQL Queries, is insufficient.

## Additional context

This should be real cool.

**Comment by netniV** [comment]
Hnm, features should be dev ;-)
