### ISSUE TITLE
Allow Cacti administrators to choose either persistent or non-persistent connections for their web server

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#4004]
# Feature Request

## Is your feature request related to a problem? Please describe

Some user complain that they receive aborted connections on their Database servers when using Cacti.  This is due to Cacti using only persistent connections.  Persistent connections speed the performance of web servers when using in memory php engines, as those php engines will cache the connections and reuse them for multiple user sessions.  However, with technologies like php-fpm, the use of persistent connections does not add significant value to the user.

## Describe the solution you'd like

Simply allow the Cacti administrator to choose the type of connection to use when using Cacti.

## Additional context

Stupid simple enhancement.

**Comment by netniV** [comment]
Hmm, features should be dev ;-)

**Comment by ethansisk1** [comment]
Hi, I've never contributed to an open source project before but I'd like to get started. Is Cacti a good project to contribute to/is this a good issue to start with?

**Comment by TheWitness** [comment]
Can you send your resume to developers at cacti dot net?  I can think of several ice breakers.  Let's see you creds first.

**Comment by ethansisk1** [comment]
I sent my resume that way. I don't have much experience, just looking for a place to build my skillset

**Comment by TheWitness** [comment]
Yup, I got a BEE from North Avenue Trade School myself back in 88'..

**Comment by ethansisk1** [comment]
Nice, I just finished there this month. Now I'm meandering around looking for jobs and trying to keep my programming skills up

**Comment by TheWitness** [comment]
How are your php skills?

**Comment by ethansisk1** [comment]
I don't have any experience with php, but I can pick up languages quickly. I'm also used to combing through code bases to see how they work.

**Comment by TheWitness** [comment]
Okay, I'll give it some thought.  Find you a couple of projects as early as tomorrow I'll be in touch.

**Comment by netniV** [comment]
I am assuming that with 1.2.17 being out that this wasn't a part of the release and needs updating (to dev) ?
