### ISSUE TITLE
Validation Error for Size when viewing Realtime Graphs

### ISSUE THREAD

**Issue by zuka1337** [Cacti/cacti#4005]
# Describe the bug

Do you know what is this about guys?

`CMDPHP Validation Error, Variable:size, Value:null Backtrace: (/graph_realtime.php[39]:get_filter_request_var(), /lib/html_utility.php[508]:die_html_input_error(), /lib/html_validate.php[64]:cacti_debug_backtrace())`

## To Reproduce

1. Create the Graph 

2. Click on Real Graph

3. Show thumbnails

## Screenshots

![image](https://user-images.githubusercontent.com/57998098/102096245-65089600-3e1c-11eb-88a2-81856dc2d7ab.png)

Cacti Version: 1.2.16

**Comment by netniV** [comment]
Could you provide the URL (from the first slash) ? It would help understand what exact parameters are being set.

**Comment by zuka1337** [comment]
Here you have: /cacti/graph_realtime.php?top=0&left=0&local_graph_id=7

```
(/graph_realtime.php[39]:get_filter_request_var(), /lib/html_utility.php[508]:die_html_input_error(), /lib/html_validate.php[64]:cacti_debug_backtrace())
Validation error for variable size with a value of null. See backtrace below for more details.
```

Note:  I'm only able to reproduce if real time graph is running onpage and the popup at the same time.

**Comment by TheWitness** [comment]
Thanks for reporting.  I can not reproduce, but I put a fail-safe in the tool.
