### ISSUE TITLE
Side Icons missing 1.2.16

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#4007]
Hey Everyone,

I just noticed that on 1.2.16 fresh install that the side icons ( Realtime,timeview etc) are not showing up
no console errors I have tried in chrome and firefox

![image](https://user-images.githubusercontent.com/13388748/102246010-406bf700-3ecc-11eb-9823-e6875a69cbe1.png)

**Comment by bmfmancini** [comment]
I tried multiple themes as well same result

**Comment by bmfmancini** [comment]
Ah found the following errors in the console

```
layout.js?25eb770f3a84476d0224556cf2664d01:3648 Uncaught TypeError: $(...).zoom is not a function

**Comment by zuka1337** [comment]
Hello @bmfmancini take a look here #3998
This was a feature in the last version

**Comment by bmfmancini** [comment]
Thanks ! 
yes I was just about to post I fixed it

**Comment by netniV** [comment]
If it isn't actually fixed on a default install of 1.2.17 (current 1.2.x dev), then we need to ensure that it is addressed, can you confirm either way?

**Comment by bmfmancini** [comment]
What happens was I created a new user with all permissions  I didn't notice
that new permission I don't think it was on by default

**Comment by TheWitness** [comment]
Yea, needs to be switched from a revoke to a grant.
