### ISSUE TITLE
Bad Results for hdd_total and hdd_used Cacti 1.2.7

### ISSUE THREAD

**Issue by zuka1337** [Cacti/cacti#4011]
# Describe the bug

Sorry for opening this one here, but can't find nothing related on the forums.

I have the SNMP - Get Mounted Partitions working fine for a couple of devices, 2 days ago I've add 3 new devices and I can't get it to work.

I get results for hrStorageDescr and hrStorageIndex etc.. ( Geting the values is not an issue )
Updating the rrds is the issue.

Also with real time I have nothing.

On troubleshooting all seams to be ok but I have this error:
`Data Source returned Bad Results for hdd_total Data Source returned Bad Results for hdd_used`

Data Source:
**hdd_used:**
Minimum = 0
Maximum = U

**hdd_total:**
Minimum = 0
Maximum = U

rrdtoon info:
```
filename = "/xxx/cacti/rra/xxx/xxx.rrd" 
rrd_version = "0003"
step = 300
last_update = 1608215886
header_size = 2912
ds[hdd_used].index = 0
ds[hdd_used].type = "GAUGE"
ds[hdd_used].minimal_heartbeat = 600
ds[hdd_used].min = 0.0000000000e+00
ds[hdd_used].max = NaN
ds[hdd_used].last_ds = "U"
ds[hdd_used].value = NaN
ds[hdd_used].unknown_sec = 186
ds[hdd_total].index = 1
ds[hdd_total].type = "GAUGE"
ds[hdd_total].minimal_heartbeat = 600
ds[hdd_total].min = 0.0000000000e+00
ds[hdd_total].max = NaN
ds[hdd_total].last_ds = "U"
ds[hdd_total].value = NaN
ds[hdd_total].unknown_sec = 186
rra[0].cf = "AVERAGE"
rra[0].rows = 600
rra[0].cur_row = 490
rra[0].pdp_per_row = 1
rra[0].xff = 5.0000000000e-01
rra[0].cdp_prep[0].value = NaN
rra[0].cdp_prep[0].unknown_datapoints = 0
rra[0].cdp_prep[1].value = NaN
rra[0].cdp_prep[1].unknown_datapoints = 0
rra[1].cf = "AVERAGE"
rra[1].rows = 700
rra[1].cur_row = 240
rra[1].pdp_per_row = 6
rra[1].xff = 5.0000000000e-01
rra[1].cdp_prep[0].value = 0.0000000000e+00
rra[1].cdp_prep[0].unknown_datapoints = 1
rra[1].cdp_prep[1].value = 0.0000000000e+00
rra[1].cdp_prep[1].unknown_datapoints = 1
rra[2].cf = "AVERAGE"
rra[2].rows = 775
rra[2].cur_row = 316
rra[2].pdp_per_row = 24
rra[2].xff = 5.0000000000e-01
rra[2].cdp_prep[0].value = 0.0000000000e+00
rra[2].cdp_prep[0].unknown_datapoints = 7
rra[2].cdp_prep[1].value = 0.0000000000e+00
rra[2].cdp_prep[1].unknown_datapoints = 7
rra[3].cf = "AVERAGE"
rra[3].rows = 797
rra[3].cur_row = 654
rra[3].pdp_per_row = 288
rra[3].xff = 5.0000000000e-01
rra[3].cdp_prep[0].value = NaN
rra[3].cdp_prep[0].unknown_datapoints = 175
rra[3].cdp_prep[1].value = NaN
rra[3].cdp_prep[1].unknown_datapoints = 175
rra[4].cf = "MAX"
rra[4].rows = 600
rra[4].cur_row = 516
rra[4].pdp_per_row = 1
rra[4].xff = 5.0000000000e-01
rra[4].cdp_prep[0].value = NaN
rra[4].cdp_prep[0].unknown_datapoints = 0
rra[4].cdp_prep[1].value = NaN
rra[4].cdp_prep[1].unknown_datapoints = 0
rra[5].cf = "MAX"
rra[5].rows = 700
rra[5].cur_row = 295
rra[5].pdp_per_row = 6
rra[5].xff = 5.0000000000e-01
rra[5].cdp_prep[0].value = -inf
rra[5].cdp_prep[0].unknown_datapoints = 1
rra[5].cdp_prep[1].value = -inf
rra[5].cdp_prep[1].unknown_datapoints = 1
rra[6].cf = "MAX"
rra[6].rows = 775
rra[6].cur_row = 483
rra[6].pdp_per_row = 24
rra[6].xff = 5.0000000000e-01
rra[6].cdp_prep[0].value = -inf
rra[6].cdp_prep[0].unknown_datapoints = 7
rra[6].cdp_prep[1].value = -inf
rra[6].cdp_prep[1].unknown_datapoints = 7
rra[7].cf = "MAX"
rra[7].rows = 797
rra[7].cur_row = 97
rra[7].pdp_per_row = 288
rra[7].xff = 5.0000000000e-01
rra[7].cdp_prep[0].value = NaN
rra[7].cdp_prep[0].unknown_datapoints = 175
rra[7].cdp_prep[1].value = NaN
rra[7].cdp_prep[1].unknown_datapoints = 175
```
Dubug Mode:
```
RRDtool Command:
/usr/bin/rrdtool graph - \
--imgformat=PNG \
--start='-86400' \
--end='-300' \
--pango-markup  \
--title='xxx-dev - Used Space - /' \
--vertical-label='bytes' \
--slope-mode \
--base=1024 \
--height=120 \
--width=500 \
--tabwidth '30' \
--rigid \
--alt-autoscale-max \
--lower-limit='0' \
COMMENT:"From 2020/12/16 14\:56\:26 To 2020/12/17 14\:51\:26\c" \
COMMENT:"  \n" \
--color BACK#F3F3F3 \
--color CANVAS#FDFDFD \
--color SHADEA#CBCBCB \
--color SHADEB#999999 \
--color FONT#000000 \
--color AXIS#2C4D43 \
--color ARROW#2C4D43 \
--color FRAME#2C4D43 \
--border 1 --font TITLE:11:'Arial' \
--font AXIS:8:'Arial' \
--font LEGEND:8:'Courier' \
--font UNIT:8:'Arial' \
--font WATERMARK:6:'Arial' \
--slope-mode \
--watermark 'Generated by Cacti®' \
DEF:a='/xxx/cacti/rra/xxx/xxx.rrd':'hdd_total':MAX \
DEF:b='/xxx/cacti/rra/xxx/xxx.rrd':'hdd_used':MAX \
AREA:a#002A97FF:'Total'  \
GPRINT:a:LAST:'Current\:%8.2lf %s'  \
GPRINT:a:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:a:MAX:'Maximum\:%8.2lf %s\n'  \
AREA:b#F51D30FF:'Used '  \
GPRINT:b:LAST:'Current\:%8.2lf %s'  \
GPRINT:b:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:b:MAX:'Maximum\:%8.2lf %s\n' 
RRDtool Says:
OK
```
WEBLOG:

`WEBLOG CACTI2RRD: /usr/bin/rrdtool graphv - --imgformat=PNG --start='1608132093' --end='1608218493' --pango-markup --title='CETPMGIP006-dev - Used Space - /' --vertical-label='bytes' --slope-mode --base=1024 --height=120 --width=500 --tabwidth '30' --rigid --alt-autoscale-max --lower-limit='0' COMMENT:"From 2020/12/16 15\:21\:33 To 2020/12/17 15\:21\:33\c" COMMENT:" \n" --color BACK#F3F3F3 --color CANVAS#FDFDFD --color SHADEA#CBCBCB --color SHADEB#999999 --color FONT#000000 --color AXIS#2C4D43 --color ARROW#2C4D43 --color FRAME#2C4D43 --border 1 --font TITLE:11:'Arial' --font AXIS:8:'Arial' --font LEGEND:8:'Courier' --font UNIT:8:'Arial' --font WATERMARK:6:'Arial' --slope-mode --watermark 'Generated by Cacti®' DEF:a='/xxx/cacti/rra/xxx/xxx.rrd' DS[xxx-dev - Used Space - /] Graphs[xxx-dev - Used Space - /]:'hdd_total':MAX DEF:b='/xxx/cacti/rra/xxx/xxx.rrd' DS[xxx-dev - Used Space - /] Graphs[xxx-dev - Used Space - /]:'hdd_used':MAX AREA:a#002A97FF:'Total' GPRINT:a:LAST:'Current\:%8.2lf %s' GPRINT:a:AVERAGE:'Average\:%8.2lf %s' GPRINT:a:MAX:'Maximum\:%8.2lf %s\n' AREA:b#F51D30FF:'Used ' GPRINT:b:LAST:'Current\:%8.2lf %s' GPRINT:b:AVERAGE:'Average\:%8.2lf %s' GPRINT:b:MAX:'Maximum\:%8.2lf %s\n'`

This error is on my Prod environment with cacti 1.2.7

**Note**: SNMP is configured nicely, snmpwalk or verbose query works and I have all data that is supost to get.

I've teste on Lab with 1.2.16 and it works like a charm.
For now upgrading is not an option.

Can you guys clear my mind and open my eyes for this issue?

**Comment by TheWitness** [comment]
You more than likely have a collection issue as the RRDtool output is correctly.  You should verify what is in the poller cache.  Then, goto the Cacti documentation and search for debugging using the script server.  In any event, since this is more support related, I would respectfully ask you to work this out on the forums first.  Thanks!

**Comment by zuka1337** [comment]
@TheWitness Thank you, I wish to get help from the forum, but registration seems to be a tiny complicated.
I've tried with all my emails..
Never receave an confirmation for any email.

![image](https://user-images.githubusercontent.com/57998098/102627615-584bb100-4140-11eb-879e-e9d1bd381dbd.png)

**Comment by TheWitness** [comment]
What IP address are you registering from?  We ban a number of IP address ranges due to quite a bit of spam activity from those IP's.  I don't see you in a banned user account status though.

**Comment by netniV** [comment]
@zuka1337 Nothing appears wrong with the username, but can you try the registration again, and if it fails please email developers@cacti.net with your username, email and current IP so we can fully check against any potential bans that might have unfortunately covered you too?  Most of the bans we do are purely automated bots and spammers.

If you aren't sure how to get your current online IP, try https://ifconfig.me/all.json -- you can remove the all.json but that just gives some json info you can copy / paste with ease.

**Comment by zuka1337** [comment]
Already send the email guys, thank you !

**Comment by zuka1337** [comment]
@TheWitness @netniV

**Comment by cigamit** [comment]
You can try registering on the forums again, we were blocking all new hotmail registrations, as spam bots were hammering us with those a while back.  I have removed the block, as they seemed to have stopped.

**Comment by zuka1337** [comment]
The AC was created but fails to send confirmation email..

have tryied a couple times and I don't receave any confirmation email key.
Even with the option "Resend activation email".

**Comment by netniV** [comment]
Is that using the same email address?  If so, can you confirm when you resend and we can check the mail server.
