### ISSUE TITLE
Remote Poller - reset avg/max polling time

### ISSUE THREAD

**Issue by KnoAll** [Cacti/cacti#4013]
# It would be great to have the ability to clear/reset the avg/max polling time statistics for remote data collectors.

## Is your feature request related to a problem? 
No

## Describe the solution you'd like. 
In 'Choose an action' dropdown, ability to say Clear Statistics similar to in the Devices page.

**Comment by TheWitness** [comment]
Yea, I had the same issue and said the same thing.

**Comment by TheWitness** [comment]
This was such a minor enhancement, and worthy of immediate resolution, that I went ahead and committed it.
