### ISSUE TITLE
Two aggregate graphs created including one inside device root - Cacti v1.2.16

### ISSUE THREAD

**Issue by Ashoury** [Cacti/cacti#4014]
Hello Everyone,

In Cacti v1.2.16 if I am creating aggregate graphs of 4 devices I will getting 5 aggregates graph, one under the aggregate graph tab , and another inside device each device  which is a bit annoying. I am not sure whether this is the desired feature or I am creating an aggregate graph in the wrong way. Please suggest how can I fix the issue.

**Comment by TheWitness** [comment]
There is a user setting to either include the aggregate graph inside of the device or not.  See below.

![image](https://user-images.githubusercontent.com/1439914/102691938-24bf6400-41de-11eb-9949-a2bfa9300d9a.png)

I hope that helps.  It's a per user setting, but you can control at the template or user group level.

**Comment by Ashoury** [comment]
Thank you so very much, it was exactly what I was looking 
It works 😀
