### ISSUE TITLE
The report cannot be sent at the specified time set by nectar after the cacti version is upgraded to 1.2.16

### ISSUE THREAD

**Issue by yuqi33** [Cacti/cacti#4016]
I recently upgraded the version to the latest 1.2.16, and found that I could not receive the daily email report set by nectar. However, it can be sent by manually clicking the send report on the nectar page. It should be a new version bug.

# Describe the bug

**Comment by bmfmancini** [comment]
unable to replicate here make sure your report is enabled and the next run time and date are correct

**Comment by yuqi33** [comment]
Checking the log has always reported errors. I don't know if it is related to the automatic report sent by the nectar plugin.

POLLER: Poller[1] ERROR: Process being killed due to timeout! (reports, master, 0, 4817)

![image](https://user-images.githubusercontent.com/35123605/103186552-f0455980-48fb-11eb-8899-5eca88ea7813.png)

![image](https://user-images.githubusercontent.com/35123605/103186615-37cbe580-48fc-11eb-8668-e1afaa8a2d5b.png)

**Comment by bmfmancini** [comment]
Thats weird   spine or cmd.php ?

**Comment by yuqi33** [comment]
Is spine  
Because the report contains a lot of aggregated pictures, and the sending time exceeds 1 minute, it feels that poller terminates the process of sending the report every time it polls.,, the process of manually clicking to send the report will not be terminated by poller, so it can be sent normally.

**Comment by yuqi33** [comment]
Please tell me how I need to set poller rules to prevent the report sending process from being killed. Thanks!

**Comment by bmfmancini** [comment]
Check this setting

**Comment by bmfmancini** [comment]
![Screenshot_20201227-222211_Chrome.jpg](https://user-images.githubusercontent.com/13388748/103187523-95c3e300-4892-11eb-91d8-9cbe312bb43a.jpg)

**Comment by yuqi33** [comment]
This is the current setting, the timeout value is 5 minutes, but poller polling will perform a kill operation every minute.
![image](https://user-images.githubusercontent.com/35123605/103187743-a57a1080-4900-11eb-9c2b-f72eeb5fbaba.png)

**Comment by yuqi33** [comment]
I tried to change the timeoute to 20 minutes and let nectar automatically send my report, but the sending process was terminated by poller.
![image](https://user-images.githubusercontent.com/35123605/103188030-bd9e5f80-4901-11eb-8195-9753a80cae71.png)
![image](https://user-images.githubusercontent.com/35123605/103188014-a8c1cc00-4901-11eb-994c-3177c7e55951.png)

**Comment by yuqi33** [comment]
I tried to manually click to send the report again, and it took 2 minutes and 40 seconds from the start of the delivery report to the receipt of the report in my mailbox, which did not exceed the 5 minute limit.

**Comment by bmfmancini** [comment]
Thats weird though I wouldn't expect the poller to kill out the report
process when it jad it own timeout setting

Maybe a bug ?

**Comment by yuqi33** [comment]
So is there any other way to solve this problem? Or we need to wait for the next version to fix this bug.

I tried to use wget to simulate manually clicking the send report button, and then use the system's crontab to trigger the sending report, but the cookie could not be called, and the feedback could not verify the cookie.This method is feasible in version 0.88.
wget --load-cookies=cookies.txt "http://127.0.0.1/cacti/reports_admin.php?action=send&id=1"

Or is it possible to use php to execute the report sending script locally combined with crontab to send the specified report regularly, ask for advice...
/usr/bin/php /var/www/cacti/reports_admin.php

**Comment by TheWitness** [comment]
First off 10 processes and 20 threads is a bit excessive.  Lower that number significantly.  Then, I suggest you review your maillog or set poller_reports.php to debug, then let's see what's going on.

**Comment by TheWitness** [comment]
You can also run this from the command line and find out what it going wrong:

```sh
php -q poller_reports.php --force
```

**Comment by yuqi33** [comment]
First of all, thank you for your suggestion. Use php -q /var/www/html/cacti/poller_reports.php --force to send all the reports in the nectar list normally. It takes 192 seconds, but if you execute it regularly, an error will be reported and cannot be sent normally. , In addition, can the specified report be sent when the background command is executed?


![image](https://user-images.githubusercontent.com/35123605/103252142-7625db00-49b6-11eb-932b-0c3bd72fdc88.png)
![image](https://user-images.githubusercontent.com/35123605/103252116-57bfdf80-49b6-11eb-9354-3d8db5bad8ae.png)
![image](https://user-images.githubusercontent.com/35123605/103252264-0106d580-49b7-11eb-8f49-8a32dba47bbf.png)

> You can also run this from the command line and find out what it going wrong:
> 
> ```shell
> php -q poller_reports.php --force
> ```

**Comment by TheWitness** [comment]
Hmm, it's the reports master.  If you continue to increase the timeout to an hour, do they all run?

**Comment by TheWitness** [comment]
Double checked.  The timeout is for the master.  If you don't give it enough time, it will be unable to send all the reports.  So, I'm going to close this one.
