### ISSUE TITLE
Threads and Processes values not migrated to Poller Cacti 1.2.16

### ISSUE THREAD

**Issue by Ashoury** [Cacti/cacti#4017]
I have problem with Cacti 1.2.16 I setup new server, added 250 devices  This is Dell R640 server VM Machine and I add 8 CPU and 16G memory for cacti. My Settings page is :

<img width="1293" alt="Screen Shot 2020-12-22 at 11 40 12 PM" src="https://user-images.githubusercontent.com/20817768/102960173-62a6db80-44af-11eb-9527-a94cfc878fe4.png">

but in my log is different

<img width="1421" alt="Screen Shot 2020-12-22 at 7 39 50 PM" src="https://user-images.githubusercontent.com/20817768/102960275-997cf180-44af-11eb-8039-0d2973e39ecb.png">

so I change the number of process by editing Main poller but I am just able to change the Processes value and there is no section for Threads per Process
<img width="600" alt="Screen Shot 2020-12-22 at 11 45 19 PM" src="https://user-images.githubusercontent.com/20817768/102960393-dea12380-44af-11eb-970a-88d65fc2c62a.png">
 
so now I can see in log that the number of processors increased 
<img width="852" alt="Screen Shot 2020-12-22 at 11 48 57 PM" src="https://user-images.githubusercontent.com/20817768/102960632-57a07b00-44b0-11eb-9820-376e7e631173.png">

but I am not able to change Threads per Process.
How can I do increase Threads per Process now I am checking 122 host and the rest of hosts are disabled but I need to enable them and it will add about 3000 graph more so I am wondering if the main poller can handle it.

is there any way to increase Threads per Process?

also after this change sometimes main poller status change to Idle , is anyone know why ?

**Comment by TheWitness** [comment]
All settings are performed at the data collector level and threads are only available in spine.
