### ISSUE TITLE
Data Query [SNMP - Interface Statistics] 

### ISSUE THREAD

**Issue by mail3dexter** [Cacti/cacti#402]
I recently found that one of my graph was not getting plotted since last 2 months. The reason I found was snmp ifindex mismatch. The device ifindex and the snmp ifindex on cacti were not matching.  

To solve it, I pressed the green O button in the right to refresh the SNMP indexes on cacti.

I wanted to know if cacti or any of its plugin can periodically refresh snmp indexes so that this kind of issue doesn't happen in future.

I know that snmp indexes doesn't change (until device reboots in some case) but some reason it got changed and I dont want it to happen again in future and want to automate it to resolve problem automatically.

FYI, I am using cacti 0.8.8g with spine poller and will upgrade soon to the latest one.

Thanks,
Mayur

**Comment by cigamit** [comment]
Cacti 0.8.8g will no longer be supported.  We suggest that you schedule a cronjob of the following:

php -q /path/to/cacti/cli/poller_reindex_hosts.php --id=all --qid=all

Do this periodically.
