### ISSUE TITLE
Change Device Threads, Revert read_config_option() (#4008, #3555)

### ISSUE THREAD

**Issue by kim-fitness** [Cacti/cacti#4021]
Additional fixes to #4008 and fix #3555. Both fixes should be put into 1.2.x branch

**Comment by TheWitness** [comment]
Commit is here.

https://github.com/Cacti/cacti/commit/5d24cfee9b638b2c1ec2d404929809a8688bb805#diff-64fc045898c96c86bd7e2ffbb496f91238a16e813a5af12395c3afe24878079f
