### ISSUE TITLE
Cacti 1.2.16 SNMP Interface traffic shows opposite direction

### ISSUE THREAD

**Issue by tceydeliler** [Cacti/cacti#4029]
I use cacti 1.2.16 /from github) and 0.8.8b
I monitor same interface of same device with same Interface by using graphic template. But 1.2.16 shows inbound and outbound values as opposite. 

1. Create device
2. Select Innterface
3. Create Graph (Bits/sec)
4. Wait graph creates
5. See error: Inbound and outbound traffic are oposite.

I wait that as my 0.8.8b graph, Inbound and outbound shows correct values
![1](https://user-images.githubusercontent.com/10337838/103507637-b1ba1c80-4e70-11eb-9712-fd3cb2889151.png)
![2](https://user-images.githubusercontent.com/10337838/103507652-b8e12a80-4e70-11eb-804d-bb7d3a9464e7.png)
As you see first graph's Inbound traffic is shown as outbound of second graphic.

**Comment by TheWitness** [comment]
You should try to figure out which on is wrong.  Both templates seem to be non-stock.  So, who knows.

**Comment by TheWitness** [comment]
Second one looks closer to stock.

**Comment by TheWitness** [comment]
Best place to look is the poller cache.  Check you OID's for each source.

**Comment by tceydeliler** [comment]
Seems both versions have same OIDs.
![1](https://user-images.githubusercontent.com/10337838/103534116-50f60880-4e9f-11eb-8659-8c7cc9e7e15c.png)
![2](https://user-images.githubusercontent.com/10337838/103534119-53586280-4e9f-11eb-86a7-2aabbcd178da.png)
I have no problem about values. problem is New version read inbound values as outbound, outbound values as inbound in graph.
here is default graphs for bits/sec : As you see out bound bigger than inbound
![3](https://user-images.githubusercontent.com/10337838/103534880-cca48500-4ea0-11eb-856f-d7d4f40abe27.png)
But, actually  inbound should be bigger than outbound
![4](https://user-images.githubusercontent.com/10337838/103534939-e47c0900-4ea0-11eb-8921-648e621abe15.png)

**Comment by TheWitness** [comment]
You did not read my question properly.  Please reread it.

**Comment by tceydeliler** [comment]
I reread. If i am not  mistaken "stock" is default code. Right?
Cacti 1.2.16 Interface bits/sec graphic is created from cacti default templates.
![3](https://user-images.githubusercontent.com/10337838/103534880-cca48500-4ea0-11eb-856f-d7d4f40abe27.png).
And this graph show inbound as outbound, ad inbound as outbound.
I check again and again templates:
![query](https://user-images.githubusercontent.com/10337838/103617439-4e4af000-4f3f-11eb-996e-2779a397b7cb.png)
![source](https://user-images.githubusercontent.com/10337838/103617445-5145e080-4f3f-11eb-850e-75e7d71cd3d8.png)
![graph](https://user-images.githubusercontent.com/10337838/103617449-530fa400-4f3f-11eb-963e-1668c620f73c.png)

**Comment by tceydeliler** [comment]
I check with PRTG and it is ok

**Comment by TheWitness** [comment]
Follow these directions to find out which is wrong.  Let us know what you find.  From the evidence below, it might be your 0.8.x system.  There was a bug there.

Looks right to me:

![image](https://user-images.githubusercontent.com/1439914/103688977-aa723c00-4f60-11eb-9da9-9e015ce96466.png)

```sh
rrdtool info /var/www/html/cacti/rra/113/1896.rrd | more
filename = "/var/www/html/cacti/rra/113/1896.rrd"
rrd_version = "0003"
step = 30
last_update = 1609874010
header_size = 5216
ds[traffic_in].index = 0
ds[traffic_in].type = "COUNTER"
ds[traffic_in].minimal_heartbeat = 60
ds[traffic_in].min = 0.0000000000e+00
ds[traffic_in].max = 1.0000000000e+09
ds[traffic_in].last_ds = "655170041"
ds[traffic_in].value = 0.0000000000e+00
ds[traffic_in].unknown_sec = 0
ds[traffic_out].index = 1
ds[traffic_out].type = "COUNTER"
ds[traffic_out].minimal_heartbeat = 60
ds[traffic_out].min = 0.0000000000e+00
ds[traffic_out].max = 1.0000000000e+09
ds[traffic_out].last_ds = "769521883"
ds[traffic_out].value = 0.0000000000e+00
ds[traffic_out].unknown_sec = 0

[root@vmhost3 cacti]# snmpget -c public -v2c vhost01 .1.3.6.1.2.1.31.1.1.1.6.2 .1.3.6.1.2.1.31.1.1.1.10.2
IF-MIB::ifHCInOctets.2 = Counter64: 655277614
IF-MIB::ifHCOutOctets.2 = Counter64: 769663790
```

So, you should do the same thing.  I'm using the Stock Template.
