### ISSUE TITLE
Why my Cacti Graph Total in and Total out MB/s is reduce. 

### ISSUE THREAD

**Issue by dongmush** [Cacti/cacti#4032]
I have I problem while collect MB/s 

this is last 4 hours reading, the total in/out bytes is normal.
![image](https://user-images.githubusercontent.com/67049695/103601794-61f95500-4f45-11eb-9903-854e5d38778f.png)

while last 12 hours, still acceptable because no traffic on midnight. at lease the number is increase.
![image](https://user-images.githubusercontent.com/67049695/103601838-7dfcf680-4f45-11eb-92e0-97661e7882bf.png)

for last 1 days, the figure is reduce. How do I fixed this.
![image](https://user-images.githubusercontent.com/67049695/103601859-89502200-4f45-11eb-84d2-436a96695a15.png)

**Comment by TheWitness** [comment]
Please start with this issue on the Cacti forums.  Thanks!
