### ISSUE TITLE
SMTP errors 

### ISSUE THREAD

**Issue by ataullahsaleem** [Cacti/cacti#4034]
hello Sir
suddenly i got mentioned errors and do not have received alerts email generated by the cacti 

**SMTP Error: data not accepted.SMTP server error: DATA command failed Detail: Daily user sending quota exceeded. b7sm89178563wrv.47 - gsmtp SMTP code: 550 Additional SMTP info: 5.4.5 | SMTP Error: data not accepted.SMTP server error: DATA command failed Detail: Daily user sending quota exceeded. b7sm89178563wrv.47 - gsmtp SMTP code: 550 Additional SMTP info: 5.4.5
-- | --
SMTP Error: data not accepted.SMTP server error: DATA command failed Detail: Daily user sending quota exceeded. b7sm89178563wrv.47 - gsmtp SMTP code: 550 Additional SMTP info: 5.4.5**

**Comment by xmacan** [comment]
Reason = **Daily user sending quota exceeded** 
You are using gmail servers and it seems that there is limit per user/IP. Better is use own smtp server.

**Comment by ataullahsaleem** [comment]
![image](https://user-images.githubusercontent.com/70479567/103635691-b3680b00-4f6a-11eb-828d-2d035db67464.png)
fix it after increased Memory Limit for Data Source Statistics Data Collector in data tab 
thanks you cacti @xmacan

**Comment by ataullahsaleem** [comment]
> Reason = **Daily user sending quota exceeded**
> You are using gmail servers and it seems that there is limit per user/IP. Better is use own smtp server.

thanks @xmacan

**Comment by xmacan** [comment]
Increased Memory Limit for Data Source Statistics Data Collector is different thing. It has nothing to do with sending quota exceeded error. You are sending a lot of emails via gmail servers and gmail limits the number of emails from your IP.

Please move this to forum. It isn't cacti issue.

**Comment by ataullahsaleem** [comment]
Alright Sir 
    On Tuesday, January 5, 2021, 03:55:26 PM GMT+5, Petr Macek <notifications@github.com> wrote:  
 
 


Increased Memory Limit for Data Source Statistics Data Collector is different thing. It has nothing to do with sending quota exceeded error. You are sending a lot of emails via gmail servers and gmail limits the number of emails from your IP.

Please move this to forum. It isn't cacti issue.

**Comment by TheWitness** [comment]
Data Source Statistics needs some love, but it's a bit down the list right now.

**Comment by TheWitness** [comment]
Looks right to me:

![image](https://user-images.githubusercontent.com/1439914/103688977-aa723c00-4f60-11eb-9da9-9e015ce96466.png)

```sh
rrdtool info /var/www/html/cacti/rra/113/1896.rrd | more
filename = "/var/www/html/cacti/rra/113/1896.rrd"
rrd_version = "0003"
step = 30
last_update = 1609874010
header_size = 5216
ds[traffic_in].index = 0
ds[traffic_in].type = "COUNTER"
ds[traffic_in].minimal_heartbeat = 60
ds[traffic_in].min = 0.0000000000e+00
ds[traffic_in].max = 1.0000000000e+09
ds[traffic_in].last_ds = "655170041"
ds[traffic_in].value = 0.0000000000e+00
ds[traffic_in].unknown_sec = 0
ds[traffic_out].index = 1
ds[traffic_out].type = "COUNTER"
ds[traffic_out].minimal_heartbeat = 60
ds[traffic_out].min = 0.0000000000e+00
ds[traffic_out].max = 1.0000000000e+09
ds[traffic_out].last_ds = "769521883"
ds[traffic_out].value = 0.0000000000e+00
ds[traffic_out].unknown_sec = 0

[root@vmhost3 cacti]# snmpget -c public -v2c vhost01 .1.3.6.1.2.1.31.1.1.1.6.2 .1.3.6.1.2.1.31.1.1.1.10.2
IF-MIB::ifHCInOctets.2 = Counter64: 655277614
IF-MIB::ifHCOutOctets.2 = Counter64: 769663790
```

So, you should do the same thing.  I'm using the Stock Template.

**Comment by TheWitness** [comment]
@xmacan @bmfmancini , maybe this should go into the troubleshooting section of the Doco?

**Comment by TheWitness** [comment]
lol, posted this to the wrong place :)
