### ISSUE TITLE
unable to upgrade to cacti 1.1.6 from 1.1.4

### ISSUE THREAD

**Issue by chrcoluk** [Cacti/cacti#4039]
# Describe the bug

Error code 500 is presented in a little window in the webui during the upgrade process.

This is present in the web server error log.

AH01071: Got error 'PHP message: PHP Fatal error:  Cannot redeclare clog_admin() (previously declared in /usr/local/share/cacti/lib/functions.php:4118) in /usr/local/share/cacti/plugins/clog/setup.php on line 202\n'

## To Reproduce

1 - upgrade cacti web files.
2 - access cacti as admin user and run web installer process to upgrade.

Freebsd 12

**Comment by chrcoluk** [comment]
Removed legacy clog plugin files to fix, the plugin was deactivated however due to been legacy.

**Comment by TheWitness** [comment]
That's going to be tough to fix.

**Comment by TheWitness** [comment]
Thanks for reporting though.

**Comment by TheWitness** [comment]
Are you certain of your versions.  Those are quite old.

**Comment by TheWitness** [comment]
No feedback, plus old version.

**Comment by chrcoluk** [comment]
Sorry it was 1.**2**.4 to 1.**2**.6
