### ISSUE TITLE
Cacti gives success even when test mail fails.

### ISSUE THREAD

**Issue by Xake** [Cacti/cacti#404]
According to settings when sending a test-mail:
#####
Checking Configuration...
Method: SMTP
Ping Results: Success
Creating Message Text...

This is a test message generated from Cacti. This message was sent to test the configuration of your Mail Settings.

Your email settings are currently set as follows

Method: SMTP
Device: < withheld >
Port: 25
Authentication: false
Ping Results: Success

Sending Message...

Success!
#####
According to log:
2017-03-10 15:46:23 - MAILER Mail Failed to '< withheld >', Subject: 'Cacti Test Message'

Why it cannot send is due to phpmailer issue 1003, however cacti should tell me when the tests fails.

**Comment by cigamit** [comment]
The default timeout was increased to 10 seconds and the error should display.  Please open a separate issue when Issue 1003 in phpmailer is resolved.
