### ISSUE TITLE
When searching tree or list views, the URL does not update after changes

### ISSUE THREAD

**Issue by GralfR** [Cacti/cacti#4045]
# Feature Request
be able to have a direct url link to a search-result/filter inside graph view/tree view.

## Is your feature request related to a problem? Please describe
I updated from cacti 0.8.8 to 1.2.15. In 0.8.8  inside graph view using the filter/search on a device shown inside the tree-view I got all the graphs of the device shown, which the search-engine found. This is working on 1.2.15, too. But on 0.8.8 I saw the URL changing and including the search-string. So, inside my browser I was able to bookmark or copy that URL and e.g. send/show my search-result to a colleague and talk about it later. 
In 1.2.15 this does not work anymore, because the filter/search-string seams to be stored inside the session, not inside the URL anymore.
After a lot of googling I read about a security-issue with the filter-parameter, which seams to be the reason, why this feature has been removed.

## Describe the solution you'd like
Because we are using cacti on an internal network without connection to the internet, we do not have to worry a lot about security/hacking. If it is easy to just re-enable that URL-filter-parameter (maybe by user-settings including a warning) this would be okay for us.

## Describe alternatives you've considered
If this is not possible, we need something like a "permanent link" to a filtered graph view, which should be able to guess by an external script. We would like to be able to get to a view of all the graphs of port 20 e.g. of a switch by just one URL link from a cacti-external site (inside the same network, not from outsite from the internet). But that URL should be that clear, that it only differs by the search-string from e.g. all graphs for port 24 of the same switch, because otherwise it would be hard to recode hundreds of links for hundreds of ports on a lot of switches, you know?

I've also searched the web for a plugin, which could do the job of creating a permanet link for my search-result, but didn't find a lot of plugins concerning links or filters. None of them would do the job, or did I miss something?

###
Thanks

**Comment by netniV** [comment]
I think your summary is correct.  There is currently no way to get the search as part of the address bar url.

**Comment by TheWitness** [comment]
It's really a regression.  I've been noticing myself.

**Comment by TheWitness** [comment]
This should be resolved now.
