### ISSUE TITLE
Missing slash in absolute path to cli/convert_tables.php shown during upgrade

### ISSUE THREAD

**Issue by luismrsilva** [Cacti/cacti#4050]
# Describe the bug
During a Cacti upgrade, in the Table Setup part of the Wizard, a `/` is missing in the absolute path to `cli/convert_tables.php`.

The absolute path is `/home/user/cacti-1.2.16/cli/convert_tables.php`, but it is shown as `/home/user/cacti-1.2.16cli/convert_tables.php`. See the screenshot below.

## Screenshots
![Screenshot from 2021-01-11 23-48-46](https://user-images.githubusercontent.com/6828187/104252042-fe9d8480-5468-11eb-9207-892d5b4e5f1b.png)

## Additional context
Experienced while doing an upgrade from `1.2.8` to `1.2.16`.

**Comment by TheWitness** [comment]
Resolved.  Thanks for reporting.
