### ISSUE TITLE
Most devices missed in devices filter list

### ISSUE THREAD

**Issue by glaubway** [Cacti/cacti#4054]
# Describe the bug

Hi, we found next issues on 1.2.15 version cacti, and after upgrading to 1.2.16 it still there.

We have more then 150 devices, but when we trying to filter our graphs by devices we can choose only small part of them.  

Our environment:
Debian 10
PHP 5.4 (but with 7.4 we have same issue)
MariaDB server 10.3
Cacti 1.2.16
Spine 1.2.16

## To Reproduce
1) Open(or):
Console -> Management -> Data Sources 
Console -> Management -> Graphs
Graphs -> List Mode
Graphs -> Preview Mode

2) Try to filtering by devices

## Screenshots

Not full list of added devices:
![image](https://user-images.githubusercontent.com/16296930/104471347-a8d4f380-55b2-11eb-85b8-d0f9081f420e.png)

MariaDB [cacti]> select count(id) from host;
+-----------+
| count(id) |
+-----------+
|       177 |
+-----------+
1 row in set (0.001 sec)

## Additional context

If you need more information about issue I will send it.

**Comment by cigamit** [comment]
Those boxes are now autocomplete search boxes (some people had 10k devices, which caused a full list to break things). It will only show a few but you can type at the top and it will autocomplete on the names.  You can change the setting on how many to show by default in Settings > Visual > Autocomplete Rows.

**Comment by netniV** [comment]
Agree.  This is a duplicate of age old issue trackers but strangely still comes to haunt us now and then.  I wonder if there is anything we can do to help raise awareness of this....

**Comment by TheWitness** [comment]
Either use Select2 or take it's approach for the dropdowns.  Select2 makes it obvious it's an autocomplete.
