### ISSUE TITLE
HRULE Text Format special characters

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#406]
Special characters (tested with a colon) are not properly escaped in the RRDTool command, resulting in an error (I believe). 

Prior versions of Cacti would use:
HRULE:54#FF3932FF:'Poller Runtime Timeout\:   54  '
Version 1.0.4:
HRULE:54#FF3932FF:"Poller Runtime Timeout:   54  "

Which results in this error:
ERROR: I don't understand '  54  ' in command: 'HRULE:54#FF3932FF:Poller Runtime Timeout:   54  '.

I removed the offending colon from the Text Format field in the graph template and was able to resolve the error. I also tried escaping it on the command line (as was done in previous versions) and this worked too. Sorry I don't have a patch, but I might try to work on one. You can probably find the code to modify faster than I can ;)

**Comment by cigamit** [comment]
Resolved.  Thanks for reporting.

**Comment by eschoeller** [comment]
Thank YOU for the quick fix!
