### ISSUE TITLE
Boost - Number of Boost Processes without function

### ISSUE THREAD

**Issue by browniebraun** [Cacti/cacti#4066]
# Describe the bug

Cacti offers the option to configure concurrent boost update processes, but there is no functionality behind this option.

## Screenshots

![image](https://user-images.githubusercontent.com/5182348/105321347-a03e7780-5bc7-11eb-81a4-42b95d7f4064.png)

**Comment by netniV** [comment]
I believe this is one that is already known to @TheWitness

**Comment by browniebraun** [comment]
yep, but I wanted to give him a reminder. ;)

**Comment by TheWitness** [comment]
I know, I know.  Never enough time in a day.
