### ISSUE TITLE
All graphs in a page have same size regardless of the actual size for each one

### ISSUE THREAD

**Issue by jav4** [Cacti/cacti#4068]
# Describe the bug

All  graphs shown on a single pase will have the same size even if each specific graph (or template) have a different size configured.

## To Reproduce

1. Create two different graphs of different sizes belonging to the same host

2. Display that host's graphs

3. Both of them will have the same size

## Expected behavior

Each graph should be displayed at its configured size

**Comment by bmfmancini** [comment]
What version of cacti ?

**Comment by jav4** [comment]
I've seen it in 1.2.15 and 1.2.16, but looks like the bug is still present in the develop branch. See pull request #4061.

**Comment by TheWitness** [comment]
Develop will be updated maybe even this weekend.  Been having issues with git desktop that I think I have a workaround for now.
