### ISSUE TITLE
"The RRD file does not exist" message is misleading

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#407]
When there is an RRDTool error (but the actual RRD file exists) Cacti 1.0.4 displays a message stating the RRD file does not exist. Surely there is a way to differentiate between an RRDTool error and a missing file! But I do realize this is an improvement over previous versions (which would display nothing) and now we are even able to see the RRDTool error within Cacti (also very much appreciated!)

**Comment by cigamit** [comment]
Yea, this is true.  We should create the image using GD.  It does not work well with the various themes either.

**Comment by cigamit** [comment]
Resolved,  Thanks for reporting.
