### ISSUE TITLE
Graph Variable summation fails in some cases when the RRDfile lacks the Data Source

### ISSUE THREAD

**Issue by Izmenoff** [Cacti/cacti#4070]
cacti 1.2.14
PHP Version | 7.3.22
RRDtool Version Found | 1.7.1
Centos7

How to fix it?

21-Jan-2021 12:53:33 - CMDPHP PHP ERROR NOTICE Backtrace: (/graph_json.php[159]:rrdtool_function_graph(), /lib/rrd.php[1591]:variable_bandwidth_summation(), /lib/graph_variables.php[653]:CactiErrorHandler())
21-Jan-2021 12:53:33 - ERROR PHP NOTICE: Undefined index: traffic_in in file: /var/www/html/cacti/lib/graph_variables.php on line: 653

**Comment by bmfmancini** [comment]
What version of cacti ?
How did this error show up? I.e what did you click

**Comment by TheWitness** [comment]
Was the RRDfile already created when you received this error message?  That 'might' lead to this issue.  If it's not repeatable, I'm kind of okay for the moment.

**Comment by Izmenoff** [comment]
It appears in log every poller cycle. I have a lot of users who can create new graphs and I can't say when the problem started.
![image](https://user-images.githubusercontent.com/17400240/105454873-adc13380-5c93-11eb-92db-f631e247e184.png)

**Comment by TheWitness** [comment]
Can you please update to the 1.2.x branch and let us know if this problem persists.  I recall us fixing some issues around this in the last few releases.

**Comment by TheWitness** [comment]
Never mind, I think I've found it.  Maybe an aggregate graph built from a bogus graph.  We might want to log something anyway.  For now, I'm going to mask the error.

**Comment by TheWitness** [comment]
Test using the lib/graph_variables.php from the 1.2.x branch and report back.
