### ISSUE TITLE
Realtime ignores output format

### ISSUE THREAD

**Issue by browniebraun** [Cacti/cacti#4074]
# Describe the bug

Realtime always returns PNG images and does not take the output format provided by the related graph templates into account.
When you are primarily using SVG, you will directly notice the washed-out, bad output.

![image](https://user-images.githubusercontent.com/5182348/105422707-82632800-5c44-11eb-9a53-4ed1bb4098db.png)

![image](https://user-images.githubusercontent.com/5182348/105422851-bcccc500-5c44-11eb-8aaf-80a678a2e4b3.png)

**Comment by TheWitness** [comment]
Went ahead and fixed it.

**Comment by browniebraun** [comment]
Fix is not complete
