### ISSUE TITLE
If user has no permissions assigned and tries to login a redirect loop occours

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#4077]

**Comment by bmfmancini** [comment]
https://user-images.githubusercontent.com/13388748/105434875-55098080-5c2a-11eb-860b-4f8274190648.mp4

**Comment by bmfmancini** [comment]
![no permissions bug](https://user-images.githubusercontent.com/13388748/105435306-1fb16280-5c2b-11eb-8ba0-9856dbf44bd9.gif)

**Comment by bmfmancini** [comment]
Bit more info 

the issue happens on Firefox and Chrome
If the user has any permission at all there is no issue
Cookies have to be clear from the browser to be able to login to cacti again

Request header

{
	"Request headers (405 B)": {
		"headers": [
			{
				"name": "Accept",
				"value": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
			},
			{
				"name": "Accept-Encoding",
				"value": "gzip, deflate"
			},
			{
				"name": "Accept-Language",
				"value": "en-CA,en-US;q=0.7,en;q=0.3"
			},
			{
				"name": "Connection",
				"value": "keep-alive"
			},
			{
				"name": "Cookie",
				"value": "Cacti=sv0jkjqc43r4eg1mn3a8c5fdq2"
			},
			{
				"name": "Host",
				"value": "192.168.1.22"
			},
			{
				"name": "Upgrade-Insecure-Requests",
				"value": "1"
			},
			{
				"name": "User-Agent",
				"value": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
			}
		]
	}
}

**Comment by TheWitness** [comment]
Those sneaky corner cases.  Need to know the exact settings.  Screen capture would be great.

**Comment by TheWitness** [comment]
Never mind.  Animation was better.

**Comment by TheWitness** [comment]
Please test with the latest auth_login.php and report back.

**Comment by bmfmancini** [comment]
Will do

**Comment by bmfmancini** [comment]
tested and working fine!
