### ISSUE TITLE
audit_database.php compatibility enhance for current_timestamp() and CURRENT_TIMESTAMP

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/cacti#4079]
When running audit_database.php under mariadb 10.3.17 found below error 
![current_timestamp](https://user-images.githubusercontent.com/47589910/105438774-99366880-5c9e-11eb-9ed2-70e90570c1b3.gif)

Reproduce steps: 
1. Prepare two env, mariadb 5.5 and mariadb 10.3.17 with both collation_server = **utf8mb4_unicode_ci** set in my.cnf 
2. create a table in cacti DB  
[root@lsf1x200 ~]# mysql cacti -e "desc disku_groups;"
+-----------+------------------+------+-----+---------------------+-------------------------------+
| Field     | Type             | Null | Key | Default             | Extra                         |
+-----------+------------------+------+-----+---------------------+-------------------------------+
| domain    | varchar(20)      | NO   | PRI |                     |                               |
| name      | varchar(64)      | NO   | PRI |                     |                               |
| groupid   | int(10) unsigned | NO   | PRI | 0                   |                               |
| firstSeen | timestamp        | NO   |     | 0000-00-00 00:00:00 |                               |
| lastSeen  | timestamp        | NO   |     | **current_timestamp() | on update current_timestamp() |**
+-----------+------------------+------+-----+---------------------+-------------------------------+
3. Check audit_schema.sql
INSERT INTO `table_columns` VALUES (**'disku_groups',5,'lastSeen','timestamp','NO','','CURRENT_TIMESTAMP','on update CURRENT_TIMESTAMP'**);
4. Run audit_database.php under mariadb 5.5 env, no error exist 
5. Run audit_database.php under mariadb 10 env, error exist as show in screenshot. 
6. Run mysql cacti -e "show table status" to check table collection value, on mariadb 5.5, collection value for this table is utf8mb4_unicode_ci, but on mariadb 10, collection value for this table is utf8mb4_general_ci. 
7. The audit_database.php does not deal with utf8mb4_general_ci to cause this error

**Comment by TheWitness** [comment]
I'm still confused.

**Comment by yingbaiibm** [comment]
OK, close this workaround fix.  Need fix for compatibility support for current_timestamp() and CURRENT_TIMESTAMP 

Detail describe: 
On mariadb 5.5 For: `lastUpdated` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
After creating table it automatically become `lastUpdated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

For mariadb 10.3, it keep same before and after creating table.

The audit_schema.sql is generated based on Maraidb 5.5, so on Mariadb 10, it will have above screenshot error. 

audit_database.php should support this capatibility. It should treat as same for current_timestamp() and CURRENT_TIMESTAMP

**Comment by TheWitness** [comment]
Yea, this is a small corner case.  I think it's easy to fix frankly.

**Comment by yingbaiibm** [comment]
Still failed with the fix
