### ISSUE TITLE
Suppress SNMP Units suffix from cacti_snmp_get() output

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#408]
This one should sound familiar ... I reported it back in 2014. I never upgraded after I reported it, but saw that it had been fixed in version 0.8.8c by cigamit. For reference it was #0002434

After finally upgrading to 1.0.4 today I got bit by this again. I am sure this is a relatively unique situation since I am including MIBs globally like so:

$ cat /etc/snmp/snmp.local.conf:
mibs +CPQHLTH-MIB
mibs +MIB-Dell-10892
mibs +SPAGENT-MIB
mibs +Sentry3-MIB
mibs +NETBOTZ410-MIB
mibAllowUnderline 1

So whenever an SNMP command is run it may display some UNIT derived from the included MIBs, which most people probably only do forcefully by using the '+m ALL' or such on the command line. Either way, I was losing some large amount of data so I did a quick fix, similar to what I did last time:

$ diff snmp.php.20170311 snmp.php
190c190
<                       ' -O fntev ' . $snmp_auth . 
---
>                       ' -O fntevU ' . $snmp_auth . 
314c314
<                       ' -O fntev ' . $snmp_auth . 
---
>                       ' -O fntevU ' . $snmp_auth . 
432c432
<                       ' -O fntev ' . $snmp_auth . 
---
>                       ' -O fntevU ' . $snmp_auth .

(I'm not sure all three were necessary, but as I said, I was in a hurry:)
I'm not sure if this will end up having some unintended affects downstream somewhere else. 

And for completeness, here is a copy of my entire submission from 3 years ago:

The following issue has been RESOLVED. 
====================================================================== 
http://bugs.cacti.net/view.php?id=2434 
====================================================================== 
Reported By:                eschoeller
Assigned To:                cigamit
====================================================================== 
Project:                    Cacti
Issue ID:                   2434
Category:                   Devices/SNMP/Scripts
Reproducibility:            always
Severity:                   minor
Priority:                   normal
Status:                     resolved
Resolution:                 fixed
Fixed in Version:           0.8.8c
====================================================================== 
Date Submitted:             2014-04-05 19:20 EDT
Last Modified:              2014-06-28 02:44 EDT
====================================================================== 
Summary:                    Suppress SNMP UNITS Suffix from cacti_snmp_get()
output
Description: 
I recently updated an SNMP MIB file which now included UNIT suffixes for
objects returned via snmpwalk/get commands. We globally include this MIB
file into SNMP commands through the use of /etc/snmp.local.conf and the
mibs +XXXX option, eg:

$ cat /etc/snmp/snmp.local.conf:

mibs +CPQHLTH-MIB
mibs +MIB-Dell-10892
mibs +SPAGENT-MIB
mibs +Sentry3-MIB
mibs +NETBOTZ410-MIB
mibAllowUnderline 1

Now when a certain query script is run, the following output is returned:

$ php -q  query_servertech_infeed_3ph.php 192.168.100.100 public 2 161
1500 10 \"\" \"\" \"\" \"\" \"\" \"\" get infeedPower3 2
675 Watts

Clearly Cacti can't handle "675 Watts" correctly. I was hoping that the
format_snmp_string() function would address this, but it does not. Adding
the "U" option to the output options to net-snmp fixes the problem
gracefully. 

from "man snmpcmd"
-OU    Do not print the UNITS suffix at the end of the value.

I can't think of any scenarios where Cacti would want the UNITS, so it was
logical to make this change globally by modifying cacti_snmp_get() in the
following manner:

lib/snmp.php
120c120
<                      
exec(cacti_escapeshellcmd(read_config_option("path_snmpget")) . " -O
fntevU " . $snmp_auth . " -v $version -t $timeout -r $retries " .
cacti_escapeshellarg($hostname) . ":$port " . cacti_escapeshellarg($oid),
$snmp_value);
---                                                                       
     
>                      
exec(cacti_escapeshellcmd(read_config_option("path_snmpget")) . " -O fntev
" . $snmp_auth . " -v $version -t $timeout -r $retries " .
cacti_escapeshellarg($hostname) . ":$port " . cacti_escapeshellarg($oid),
$snmp_value);

(basically output options are now " -O fntevU " instead of " -O fntev ")

Let me know what you think about this fix. Our SNMP version:
NET-SNMP version: 5.5

Thanks.
====================================================================== 

---------------------------------------------------------------------- 
 (0006605) cigamit (developer) - 2014-06-28 02:44
 http://bugs.cacti.net/view.php?id=2434#c6605 
---------------------------------------------------------------------- 
Thanks for reporting.  I have corrected this in SVN. 

Issue History 
Date Modified    Username       Field                    Change               
====================================================================== 
2014-04-05 19:20 eschoeller     New Issue                                    
2014-04-07 14:44 paulgevers     Tag Attached: patch                          
2014-06-28 02:32 cigamit        Status                   new => assigned     
2014-06-28 02:32 cigamit        Assigned To               => cigamit         
2014-06-28 02:44 cigamit        Note Added: 0006605                          
2014-06-28 02:44 cigamit        Status                   assigned => resolved
2014-06-28 02:44 cigamit        Fixed in Version          => 0.8.8c          
2014-06-28 02:44 cigamit        Resolution               open => fixed       
======================================================================

**Comment by eschoeller** [comment]
sorry the formatting is terrible on that one!

**Comment by cigamit** [comment]
This is resolved for cacti_snmp_get(), cacti_snmp_walk(), but still in place for cacti_snmp_get_raw().

**Comment by eschoeller** [comment]
Confirmed that my issue is still resolved with cacti_snmp_get_raw left unchanged, many thanks!
