### ISSUE TITLE
cactid Service Fails to Start on Ubuntu

### ISSUE THREAD

**Issue by JeffHochberg** [Cacti/cacti#4084]
# Describe the bug

Upgraded from 1.2.15 to 1.2.16 and migrated from running poller.php via cron to using new cactid.service

Starting cactid via systemctl fails on Ubuntu due to lack of /etc/sysconfig/cactid

Jan 22 13:49:44 ubuntu-server systemd[1]: cactid.service: Failed to load environment files: No such file or directory
Jan 22 13:49:44 ubuntu-server systemd[1]: cactid.service: Failed to run 'start' task: No such file or directory
Jan 22 13:49:44 ubuntu-server systemd[1]: cactid.service: Failed with result 'resources'.

## To Reproduce

1. View contents of /var/www/html/cacti/service/README.md

2. Copy the cactid.service file to /usr/lib/systemd/system

3. Edit /usr/lib/systemd/system/cactid.service

4. Update User, Group, and ExecStart accordingly (www-data, www-data, /var/www/html/cacti/cactid.php respectively)

5. README.md recommends the creation of /etc/sysconfig/cactid but /etc/sysconfig/ does not exist in Ubuntu/Debian systems 

6. Edit **/usr/lib/systemd/system/cactid.service

7. Remove EnvironmentFile=/etc/sysconfig/cactid (line 9) and save file

8. Run systemctl daemon-reload

9. Check status with systemctl status cactid.service

10. Service is active!

This is the output from journalctl -xe after the first attempt:

-- The unit cactid.service has entered the 'failed' state with result 'resources'.
Jan 22 13:49:38 ubuntu-server systemd[1]: Failed to start Cacti Daemon Main Poller Service.
-- Subject: A start job for unit cactid.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- A start job for unit cactid.service has finished with a failure.
-- 
-- The job identifier is 21562 and the job result is failed.
Jan 22 13:49:44 ubuntu-server systemd[1]: cactid.service: Scheduled restart job, restart counter is at 3.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Automatic restarting of the unit cactid.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
Jan 22 13:49:44 ubuntu-server systemd[1]: Stopped Cacti Daemon Main Poller Service.
-- Subject: A stop job for unit cactid.service has finished
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- A stop job for unit cactid.service has finished.
-- 
-- The job identifier is 21631 and the job result is done.
Jan 22 13:49:44 ubuntu-server systemd[1]: cactid.service: Failed to load environment files: No such file or directory
Jan 22 13:49:44 ubuntu-server systemd[1]: cactid.service: Failed to run 'start' task: No such file or directory
Jan 22 13:49:44 ubuntu-server systemd[1]: cactid.service: Failed with result 'resources'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The unit cactid.service has entered the 'failed' state with result 'resources'.
Jan 22 13:49:44 ubuntu-server systemd[1]: Failed to start Cacti Daemon Main Poller Service.
-- Subject: A start job for unit cactid.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- A start job for unit cactid.service has finished with a failure.
-- 
-- The job identifier is 21631 and the job result is failed.

**Comment by TheWitness** [comment]
The documentation specifically states that you need to create that file.

**Comment by TheWitness** [comment]
So, this isn't really a bug.

**Comment by TheWitness** [comment]
Reading further, can you create a pull request and update the README.md in the service directory?

**Comment by bmfmancini** [comment]
@TheWitness  I updated the doco with Ubuntu/Debian based instructions 
PR https://github.com/Cacti/cacti/pull/4087

**Comment by TheWitness** [comment]
Okay, this is fixed now.  Thanks for reporting.
