### ISSUE TITLE
Cacti v1.2.15 upgrade wizard stuck at max_input_vars setting

### ISSUE THREAD

**Issue by ibmmarkham** [Cacti/cacti#4085]
# Describe the bug

We were upgrading IBM RTM and we had unfinished installation. We logged into Webpage, however Cacti v1.2.15 wizard is stuck at this page complaining about max_input_vars.
Your have more tables than your PHP configuration will allow us to display/convert. Please modify max_input_vars setting in php.ini to a value above 1565.

Upgrade couldn't move forward after modified the max_input_vars setting in php.ini , even after restarting apache service.

**Comment by ibmmarkham** [comment]
<img width="769" alt="Screen Shot 2021-01-22 at 16 31 54" src="https://user-images.githubusercontent.com/31447023/105550413-5e005d80-5ccf-11eb-9030-ac1c3b3a60d8.png">

**Comment by TheWitness** [comment]
I suggest IBM support @ibmmarkham.  Open a S1 ticket.

**Comment by TheWitness** [comment]
My suspicion is that the upgrade silently failed.

**Comment by TheWitness** [comment]
IBM has been committing patches recently.

**Comment by TheWitness** [comment]
I guess the right thing to do here is to store all the table names in a large single variable.

**Comment by netniV** [comment]
I am sure there is a single variable length limit too so that would also be a problem.  I am pleased though that the warning actually works as expected 👍 

The simple fix is to update the php file to allow more variables.

**Comment by TheWitness** [comment]
Yea, I would agree.  This is more of a documentation issue.  Maybe we put something in technical support?

**Comment by ibmmarkham** [comment]
I don't have the environment anymore - the problem is that increasing this setting in php.ini didn't help. We increased it to 2000, still the same error message.

**Comment by TheWitness** [comment]
There are actually two variables.  If running Nginx or rhel8 you have to restart php-frm.
