### ISSUE TITLE
CMDPHP Errors during upgrade

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#409]
I had dozens of these during the various upgrades I did today. Our main production site was the worst, but as I recall the other smaller instances had many more (equal) repairs. After the upgrade I immediately needed to rebuild the entire poller cache, the old path_cacti was still stuck everywhere. Not sure if that's related to these or not, but I can tell you anything using an external perl or php command was referencing the wrong path which seems "data_input_method" related! 

2017-03-11 20:21:26 - CMDPHP ERROR: A DB Exec Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE data_input_field_id = 646          AND data_template_data_id = 55614' at line 1
2017-03-11 20:21:26 - CMDPHP SQL Backtrace: (/install/index.php: 417 upgrade_to_1_0_0)(/install/0_8_8h_to_1_0_0.php: 1751 repair_system_data_input_methods)(/lib/functions.php: 4482 db_execute)(/lib/database.php: 113 db_execute_prepared)(/lib/database.php: 178 cacti_debug_backtrace)
2017-03-11 20:21:26 - CMDPHP UPGRADE NOTE: Repairing 1 Damaged data_input_fields
2017-03-11 20:21:27 - CMDPHP UPGRADE NOTE: Found 30137 Damaged data_input_fields

**Comment by cigamit** [comment]
I need more of the error log.

**Comment by cigamit** [comment]
Also, it's likely that your databases are damaged on this one.

**Comment by eschoeller** [comment]
[upgrade.log.gz](https://github.com/Cacti/cacti/files/836619/upgrade.log.gz)

Here is everything from the upgrade that was in cacti.log. Let me know what else you might need, or what I need to check in my database that could be damaged. Thanks!

**Comment by cigamit** [comment]
Thanks will check shortly.

**Comment by cigamit** [comment]
I have resolved the source of the error.  We attempted to repair the 4 system data input methods that someone had 'hacked' at some point in time to add a duplicated snmp_port column.  We removed the 'bad' one during the upgrade to 1.0.  Unfortunately, in your case, you must have detected and repaired this on your own at some point, but you removed the wrong snmp port :) entry.  There are a few fixes for this, you will have to re-import your templates to restore the bogus hash for the snmp_port, or re-upgrade from 0.8.x with 1.0.5 once it's released.  Should be today.

If would be a good thing for you to change the hash for your snmp_port though to the correct one's.  

For 'Get SNMP Data', it is: 'fc64b99742ec417cc424dbf8c7692d36'
For 'Get SNMP Data (Indexed)' it is 'c1f36ee60c3dc98945556d57f26e475b'.

So, you would run the following query:

select id, hash, data_input_id, data_name from data_input_fields WHERE data_name='snmp_port' and hash!='';

And you will see what the current hashes for those two fields are.

Is this making any sense?

**Comment by cigamit** [comment]
You can double check my hashes by reviewing the cacti.sql that is a part of the 1.0.x install.

**Comment by eschoeller** [comment]
lol yikes that sounds like a cluster:) Should have waited a day to upgrade our production instance, but oh well I only have this weekend to get this all done!
Is this what you would expect to see given my situation?
+-----+----------------------------------+---------------+-----------+
| id  | hash                             | data_input_id | data_name |
+-----+----------------------------------+---------------+-----------+
|  39 | c1f36ee60c3dc98945556d57f26e475b |             2 | snmp_port |
|  40 | fc64b99742ec417cc424dbf8c7692d36 |             1 | snmp_port |
| 137 | 8a9a7d85d5f3b977ae20f4825ef09f5e |            32 | snmp_port |
| 184 | 2fdee8024d2df4a3d5b2a53ef80f09cb |            35 | snmp_port |
| 204 | 78b61d7fe46501e4f4414b7405abf012 |            36 | snmp_port |
| 213 | a55ce085ae453aacfcf5a7c120f7f6bd |            37 | snmp_port |
| 220 | d08db2363c535dcd84a7c822cad3e000 |            38 | snmp_port |
| 227 | 528926c5e3cba5e24e10399c11dbe1b4 |            39 | snmp_port |
| 234 | 9e7c33aa8308a46b0ef4420931fb1807 |            40 | snmp_port |
| 241 | 33d14d049b00d62137316fa28ea28c7c |            41 | snmp_port |
| 254 | 88bc1941eaf8fa9e580a27ec6a9bcdb7 |            42 | snmp_port |
| 267 | 8cb1b1b6238cda3d3c93a7777b99bc30 |            43 | snmp_port |
| 274 | d9ca1e10ce6098712f47538cc02b72fa |            44 | snmp_port |
| 281 | 8e6273b9c4ad82090e832e07cc03bf8a |            45 | snmp_port |
| 288 | 61fab814d39f8d617d3dfdba9f6a35cb |            46 | snmp_port |
| 301 | 9a1f368e12cd5a909f9252984adfd3cc |            47 | snmp_port |
| 312 | 7d258455cb07f62eb9b23ac62970a94c |            48 | snmp_port |
| 319 | b94c2b1fb1b010b7b23a4cf5dc984794 |            49 | snmp_port |
| 328 | f9098539be4dc02a3e3c7015033e9109 |            50 | snmp_port |
| 334 | b2a9cc1ef80c51a03ec90362a1d5ebd4 |            51 | snmp_port |
| 351 | 3f9b66ba3b71bb5a8affabab3a4ea4fb |            52 | snmp_port |
| 360 | 6c5ec9f80157ca3e7ca40ba8b8f2c62b |            53 | snmp_port |
| 367 | 8577720c1975a735f6610b4e61d61f96 |            54 | snmp_port |
| 374 | 7bddfea8f11342d2758af8caec267d84 |            55 | snmp_port |
| 437 | 8352ee2f6f579c271ffdfb1199b37373 |            58 | snmp_port |
| 728 | 59f8c73e37492fed3d760b88a1825b26 |           104 | snmp_port |
+-----+----------------------------------+---------------+-----------+
26 rows in set (0.00 sec)

**Comment by cigamit** [comment]
Oh crap!.  So run this:

SELECT data_input.name FROM data_input WHERE id IN(SELECT data_input_id FROM data_input_fields WHERE hash!='' AND data_name='snmp_port');

**Comment by eschoeller** [comment]
hehehe ... here you go!

+----------------------------------------------------+
| name                                               |
+----------------------------------------------------+
| Get SNMP Data                                      |
| Get SNMP Data (Indexed)                            |
| Server Technology CDU - System Total Power         |
| SNMP - Get ServerTech (1x2) CDU Loads (Amps)       |
| SNMP - Get ServerTech (1x2) CDU Powers (Watts)     |
| SNMP - Get ServerTech (2x3) 3ph CDU Loads (Amps)   |
| SNMP - Get ServerTech (2x3) 3ph CDU Powers (Watts) |
| SNMP - Get SUN T5120 Core Temperatures             |
| SNMP - Get SUN T5120 Fan Speeds                    |
| SNMP - Get SUN T5120 Memory Temperatures           |
| SNMP - Get SUN T5120 Power Supply Input Amps       |
| SNMP - Get SUN T5120 Power Supply Input Watts      |
| SNMP - Get SUN x4150 Fan Speeds                    |
| SNMP - Get SUN x4150 Motherboard Temperatures      |
| SNMP - Get SUN x4150 Power Supply Fan Speeds       |
| SNMP - Get SUN x4150 Power Supply Input Amps       |
| SNMP - Get SUN x4150 Power Supply Input Power      |
| SNMP - Get SUN x4150 Power Supply Temperatures     |
| SNMP - Get SUN x4150 System Ambient Temperature    |
| SNMP - Get SUN x4250 Fan Speeds                    |
| SNMP - Get SUN x4250 Motherboard Temperatures      |
| SNMP - Get SUN x4250 Power Supply Input Amps       |
| SNMP - Get SUN x4250 Power Supply Input Power      |
| SNMP - Get SUN x4250 System Ambient Temperature    |
| SNMP - Get TCP Connection Status                   |
| System Activity Reporter                           |
+----------------------------------------------------+
26 rows in set (0.01 sec)

Those are some OLD templates I'm still carrying around. We have about 6 SUN machines left and once those get kicked out the door, so do these templates.

**Comment by cigamit** [comment]
Okay.  These other guys are not a big deal.  Let me insure that there are no issues in the repair script around this discovery.

**Comment by cigamit** [comment]
Just one question, was that query performed before or after the upgrade?

**Comment by eschoeller** [comment]
That was after the upgrade to 1.0.4

**Comment by cigamit** [comment]
Yea, would like to see that same query before the upgrade.

**Comment by cigamit** [comment]
If you still have this issue, could you please take an old 0.8.8x database dump and send to jimmy@sqmail.org?

**Comment by eschoeller** [comment]
I pulled the latest from git today and upgraded the instance I had so much trouble with last weekend. It went just fine. Here was all that existed in the log:
2017-03-18 14:16:01 - CMDPHP UPGRADE NOTE: Repairing 4 Damaged data_input_fields
2017-03-18 14:16:01 - CMDPHP UPGRADE NOTE: Found 1041 Damaged data_input_fields
2017-03-18 14:16:04 - CMDPHP UPGRADE NOTE: Found 1041 Damaged data_input_fields
2017-03-18 14:16:20 - CMDPHP UPGRADE NOTE: Found 285 Damaged data_input_fields
2017-03-18 14:16:23 - CMDPHP WARNING: Could not find Cacti default matching hash for unknown system hash "35637c344d84d8aa3a4dc50e4a120b3f" for 1.  No repair performed.
2017-03-18 14:16:23 - CMDPHP UPGRADE NOTE: Repairing 1 Damaged data_input_fields
2017-03-18 14:16:23 - CMDPHP UPGRADE NOTE: Found 2194 Damaged data_input_fields

I could probably mail you a DB, but it may contain some super-secret stuff in it. I'll have to look at it.

**Comment by cigamit** [comment]
Even though the upgrade seems to be working right now, I'm going to keep this open for a bit.  Since on on this now, I'll take a deeper dive into the code by creating one of your data input method by hand.  You could also export some of the Solaris templates and attaching them here.

**Comment by cigamit** [comment]
I think I figured it out ;)

**Comment by cigamit** [comment]
It's a creepy thing in Cacti.  You should never have to create a 'SNMP Get' or 'SNMP Walk' data input method.  So, whomever created those templates recreated all that work.  Now I will be able to pin down the logic issue.

**Comment by cigamit** [comment]
You know, looking at the code, you are safe now.  I'll just go ahead and close this.
