### ISSUE TITLE
Cacti Version 1.2.15 || Want to monitor TCP ports (like ssh, telnet etc) || having error in tcp.xml file 

### ISSUE THREAD

**Issue by Rafid2211** [Cacti/cacti#4093]
I want to monitor the TCP ports on cacti of remote hosts. I download a tcp template and when I import the tcp.xml file which is the zip of template, got following error:

![image](https://user-images.githubusercontent.com/77919800/105628396-689d2d00-5e5e-11eb-87ee-56a4f1a85df5.png)

![image](https://user-images.githubusercontent.com/77919800/105628403-7783df80-5e5e-11eb-8040-e1f56d964f0d.png)

following is the TCP template zip file:

[TCP Port Template.zip](https://github.com/Cacti/cacti/files/5862058/TCP.Port.Template.zip)

can anyone help me?

**Comment by cigamit** [comment]
Please ask on http://forums.cacti.net  The Issue tracker is for actual issues with Cacti, not support.

**Comment by TheWitness** [comment]
Just update to 1.2.16 or the 1.2.x branch and I believe this problem will be solved.

**Comment by Rafid2211** [comment]
I updated cacti to 1.2.16 but still having the same error when importing the tcp.xml file

**Comment by xmacan** [comment]
You cannot import tcp.xml. You have to copy this file to <cacti_install_dir>/resource/script_server.  The content of scripts directory to the <cacti_install_dir>/scripts. Import only cacti_data*.xml

**Comment by Rafid2211** [comment]
I have copy xml file in folder, it worked.

But in data query shows 0 items, 0 rows

**Comment by xmacan** [comment]
Please try http://forums.cacti.net
