### ISSUE TITLE
Cacti broken graph

### ISSUE THREAD

**Issue by mosharaflink** [Cacti/cacti#4094]
# Cacti version 1.2.15 suddenly all graph shows broken

![Cacti 1 2 15 graph broken](https://user-images.githubusercontent.com/32505239/105640870-bfc8ef00-5eaa-11eb-9c68-83ed855c9b35.png)

**Comment by TheWitness** [comment]
Take this one up on the forums.  Then, if you continue to have problems, you can come back here once you have established it's a bug.
