### ISSUE TITLE
Wrong Chinese translation for "Leaf"

### ISSUE THREAD

**Issue by SaintAiolos** [Cacti/cacti#4096]
# Describe the bug

Hi,guys
I've seen your translations for "Leaf"  is "剩下" in "/locales/po/zh-CN.po" .
in Chinese, "Leaf" should be called "叶子".

Thanks a lot.

---------------------------
cacti version: 1.2.16
---------------------------

**Comment by TheWitness** [comment]
Go-to https://translate.cacti.net, sign up and fix it.  Thanks.
