### ISSUE TITLE
Code Problem in Translations.php

### ISSUE THREAD

**Issue by hellishglare** [Cacti/cacti#4097]
When a browser's language setting is set to Turkish, Cacti pages can not be displayed due to PHP fatal error in Translations.php

## To Reproduce

1. Browser's language setting should be set to Turkish

2. Go to Cacti login page

3. See error

Detailed HTTP Server (Apache) Log:
PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'ArrayObject::__construct() expects parameter 3 to be a class name derived from Iterator, 'ArrayIterator' given' in /usr/share/cacti/include/vendor/gettext/src/Translations.php:138\nStack trace:\n#0 /usr/share/cacti/include/vendor/gettext/src/Translations.php(138): ArrayObject->__construct(Array, 0, 'ArrayIterator')\n#1 /usr/share/cacti/include/vendor/gettext/src/Translations.php(153): Gettext\\Translations->__construct()\n#2 /usr/share/cacti/include/global_languages.php(278): Gettext\\Translations::__callStatic('fromMoFile', Array)\n#3 /usr/share/cacti/include/global_languages.php(278): Gettext\\Translations::fromMoFile('/usr/share/cact...')\n#4 /usr/share/cacti/include/global_languages.php(230): load_gettext_oscarotero('cacti')\n#5 /usr/share/cacti/include/global.php(498): include_once('/usr/share/cact...')\n#6 /usr/share/cacti/include/auth.php(28): require_once('/usr/share/cact...')\n#7 /usr/share/cacti/index.php(25): include('/usr/share/cact...')\n#8 {main}\n   in /usr/share/cacti/include/vendor/gettext/src/Translations.php on line 138

I moved around this problem by changing the "parent::__construct" line in the function __construct() as follows:

- parent::__construct($input, $flags, $iterator_class);
+ parent::__construct($input, $flags);

**Comment by TheWitness** [comment]
I think you have a system setup problem.  When you run ```php -m```, do you show the gettext module?  If not, install php-gettext.  This is what I get.

![image](https://user-images.githubusercontent.com/1439914/105924116-a3909380-600b-11eb-98ee-7935e0e2112e.png)

**Comment by TheWitness** [comment]
Also, what PHP version?

**Comment by hellishglare** [comment]
This happened to me on two different servers. Below you may find detailed information about these servers:

Server #1
CentOS Linux release 7.9.2009 (Core)
Kernel: 3.10.0-1160.11.1.el7.x86_64
PHP Version => 5.4.16
GetText Support => enabled (php-php-gettext-1.0.12-1.el7.noarch)
Cacti Version: 1.2.15

Server #2
CentOS Linux release 7.8.2003 (Core)
Kernel: 3.10.0-1127.18.2.el7.x86_64
PHP Version => 5.4.16
GetText Support => enabled (php-php-gettext-1.0.12-1.el7.noarch)
Cacti Version: 1.2.15

As far as I understand from the error log, $iterator_class = 'ArrayIterator' is passed to the function __construct() in Translations.php but PHP expects this parameter to be a class name derived from Iterator. After I changed the last line in this function to "parent::__construct($input, $flags);" the error went away. I know that this is not a solution but a temporary workaround.

**Comment by TheWitness** [comment]
Can you create a pull request off the 1.2.x branch?

**Comment by TheWitness** [comment]
Where is the php -m output I asked for?

**Comment by hellishglare** [comment]
Server #1
php -m
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
imap
intl
json
ldap
libxml
mbstring
mhash
mysql
mysqli
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
snmp
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
zip
zlib

[Zend Modules]



Server #2
php -m
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
imap
intl
json
ldap
libxml
mbstring
mhash
mysql
mysqli
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
snmp
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
zip
zlib

[Zend Modules]

**Comment by browniebraun** [comment]
PHP Version => 5.4.16 ?

This version is completely end of everything. You should upgrade your environment to PHP 7.3 at a minimum.

**Comment by hellishglare** [comment]
Thanks for the upgrade advice.

**Comment by TheWitness** [comment]
That's RHEL7, but the Remi Repos make PHP7.x painless on RHEL.
