### ISSUE TITLE
Graphs and Data Sources page almost unusable on very large systems

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#4098]
# Describe the bug

On systems is ~1.7 million Graphs and associated Data Sources, both the Graph and the Data Sources page are slow at best, and unusable at worst.  This is due to an indexing issue in Cacti and a JOIN issue as well in the Graphs display.

## To Reproduce

Have a real big Cacti

## Expected behavior

Good performance above 1M Graphs and Data Sources.

**Comment by eschoeller** [comment]
I'm looking forward to seeing if there's some performance gains on my system from this change!

**Comment by TheWitness** [comment]
There are a number of recent changes that totally change the user experience.

**Comment by eschoeller** [comment]
I'm excited:)
