### ISSUE TITLE
Realtime Graph not loading 

### ISSUE THREAD

**Issue by sdiwakar123** [Cacti/cacti#4102]
Hi I am using Cacti version 1.2.14 with Centos 7 Operation System. I am facing issue related to Cacti Realtime graph . When I click on view realtime graph it doen't load any graph data. 

![image](https://user-images.githubusercontent.com/76724933/105991687-1fe9ac00-60ca-11eb-9a99-ef52a2d7c320.png)

**Comment by sdiwakar123** [comment]
my cacti log data.


2021/01/27 18:05:04 - WEATHERMAP WARNING: {"memory":{"_limit_":"-1","start":"21.8M","config-read":"22.8M","settings-set":"22.8M","data-read":"22.8M","post-render":"24.7M","end":"24.7M"},"times":{"start":1611750904.3657241,"config-read":1611750904.3712571,"settings-set":1611750904.3719311,"data-read":1611750904.5490041,"post-render":1611750904.8590939,"end":1611750904.862262},"stats":{"total_targets":27,"duration":0.49653792381286621,"warnings":0}}
--
2021/01/27 18:05:04 - WEATHERMAP Wrote map to /usr/share/cacti/plugins/weathermap/output/c000f3c96139ce7a156b.png and /usr/share/cacti/plugins/weathermap/output/c000f3c96139ce7a156b.thumb.png
2021/01/27 18:05:04 - POLLER: Poller[Main Poller] WARNING: Invalid Response(s), Errors[1] Device[6720_THEUR] Thread[1] DS[6720_THEUR - 5 Minute CPU] Graphs[6720_THEUR - CPU Usage]
2021/01/27 18:05:04 - POLLER: Poller[Main Poller] WARNING: Invalid Response(s), Errors[1] Device[6720_NIXI] Thread[1] DS[6720_NIXI - 5 Minute CPU] Graphs[6720_NIXI - CPU Usage]
2021/01/27 18:05:04 - POLLER: Poller[Main Poller] WARNING: Invalid Response(s), Errors[1] Device[6720_WAKAD_NEW] Thread[1] DS[6720_WAKAD_NEW - 5 Minute CPU] Graphs[6720_WAKAD_NEW - CPU Usage]
2021/01/27 18:05:04 - POLLER: Poller[Main Poller] WARNING: Invalid Response(s), Errors[1] Device[6730_MIRCHOLI] Thread[1] DS[6730_MIRCHOLI -] Graphs[6730_MIRCHOLI -]
2021/01/27 18:05:04 - WEATHERMAP About to write image file. If this is the last message in your log, increase memory_limit in php.ini () [WMPOLL01] : memory_get_usage() says 22.8MBytes used. Limit is -1
2021/01/27 18:05:04 - WEATHERMAP WARNING: ReadData: [LINK NM-CHANDIVALI-MCPL-1], target: /usr/share/cacti/rra/ciena_mcpl-1_traffic_in_743.rrd had no valid data, according to RRDTool [WMWARN70]
2021/01/27 18:05:04 - POLLER: Poller[Main Poller] WARNING: Invalid Response(s), Errors[1] Device[6730_CTRLS] Thread[1] DS[6730_CTRLS -] Graphs[6730_CTRLS -]
2021/01/27 18:05:04 - POLLER: Poller[Main Poller] WARNING: Invalid Response(s), Errors[1] Device[MBKC_NEXSUS] Thread[1] DS[MBKC_NEXSUS - 5 Minute CPU] Graphs[MBKC_NEXSUS - CPU Usage]
2021/01/27 18:05:04 - POLLER: Poller[Main Poller] WARNING: Invalid Response(s), Errors[1] Device[6730_NEW_PANVEL] Thread[1] DS[6730_NEW_PANVEL -] Graphs[6730_NEW_PANVEL -]
2021/01/27 18:05:04 - WEATHERMAP Map: /usr/share/cacti/plugins/weathermap/configs/nld_l3.conf -> /usr/share/cacti/plugins/weathermap/output/c000f3c96139ce7a156b.html & /usr/share/cacti/plugins/weathermap/output/c000f3c96139ce7a156b.png
2021/01/27 18:05:04 - WEATHERMAP WARNING: {"memory":{"_limit_":"-1","start":"19.6M","config-read":"20.4M","settings-set":"20.4M","data-read":"20.4M","post-render":"21.8M","end":"21.8M"},"times":{"start":1611750903.937443,"config-read":1611750903.9418731,"settings-set":1611750903.942426,"data-read":1611750904.0579259,"post-render":1611750904.3622761,"end":1611750904.3649371},"stats":{"total_targets":17,"duration":0.42749404907226562,"warnings":0}}
2021/01/27 18:05:04 - WEATHERMAP Wrote map to /usr/share/cacti/plugins/weathermap/output/efa06dba1c9aafdd74bd.png and /usr/share/cacti/plugins/weathermap/output/efa06dba1c9aafdd74bd.thumb.png
2021/01/27 18:05:04 - POLLER: Poller[Main Poller] WARNING: Invalid Response(s), Errors[2] Device[6720-ILL] Thread[1] DS[6720-ILL - 5 Minute CPU, 6720-ILL - Traffic - \|query_ifIP\| - \|query_ifName\|] Graphs[6720-ILL - CPU Usage, ILL1000110_200Mb_NCDEX]
2021/01/27 18:05:04 - POLLER: Poller[Main Poller] WARNING: Invalid Response(s), Errors[1] Device[6730_PADGHE] Thread[1] DS[6730_PADGHE -] Graphs[6730_PADGHE -]
2021/01/27 18:05:04 - POLLER: Poller[Main Poller] WARNING: Invalid Response(s), Errors[1] Device[POWAI_CORE_10G] Thread[1] DS[POWAI_CORE_10G - 5 Minute CPU] Graphs[POWAI_CORE_10G - CPU Usage]
2021/01/27 18:05:04 - WEATHERMAP About to write image file. If this is the last message in your log, increase memory_limit in php.ini () [WMPOLL01] : memory_get_usage() says 20.4MBytes used. Limit is -1
2021/01/27 18:05:04 - POLLER: Poller[Main Poller] WARNING: Invalid Response(s), Errors[1] Device[PDNSSL1] Thread[1] DS[PDNSSL1 -] Graphs[PDNSSL1 -]

**Comment by bmfmancini** [comment]
That issue was fixed a while ago
You can either update to 1.2.16 or update the real-time files

**Comment by bmfmancini** [comment]
The fix is here
https://github.com/Cacti/cacti/issues/3898

**Comment by sdiwakar123** [comment]
@bmfmancini i update cacti via yum only and i have checked that version 1.2.15 is available currently via yum.

**Comment by bmfmancini** [comment]
Interesting

OK then pull the real-time.js from that commit make a backup of the current one and try that

**Comment by TheWitness** [comment]
This issue is resolved and duplicate.

**Comment by sdiwakar123** [comment]
strange thing is that i am able to view realtime graph in Mozilla but not in chrome.

**Comment by sdiwakar123** [comment]
> Interesting
> 
> OK then pull the real-time.js from that commit make a backup of the current one and try that

tried it but no luck

**Comment by TheWitness** [comment]
What chromium release?

**Comment by sdiwakar123** [comment]
it's latest Version 87.0.4280.141 (Official Build) (64-bit)

**Comment by TheWitness** [comment]
Okay, I'm running `89.0.4389.40 (Official Build) beta (64-bit)` and I am not experiencing this problem.  Looks like a Chromium issue.

**Comment by TheWitness** [comment]
Going to mark as a third party bug and close.
