### ISSUE TITLE
Cacti realtime graph problem cacti 1.2.16

### ISSUE THREAD

**Issue by hariesfn** [Cacti/cacti#4106]
# Describe the bug

Realtime graph is not showing on a group of graphs but normal on other group of graphs. Both graph group refers to different template.

Everything looks normal if not using realtime graph.

## Debug of realtime graph that has problem
[realtime-problem.txt](https://github.com/Cacti/cacti/files/5891557/realtime-problem.txt)

## Debug of realtime graph that looks ok
[realtime-ok.txt](https://github.com/Cacti/cacti/files/5891561/realtime-ok.txt)

Cacti version : 1.2.16

**Comment by TheWitness** [comment]
You need to install the 1.2.x branch, clear your browser cache try again and report back.  If you do continue to have problems we will need console JavaScript debug info.

**Comment by hariesfn** [comment]
Hello,

It's already 1.2.16 version. 
Do I need to reinstall it ? Or can I just replace or edit some files to solve this problem ? 

Since this Cacti already used in production. Your help is much appreciated.

**Comment by TheWitness** [comment]
Download and install the 1.2.x branch.  You did not provide the browser debug console output as was requested BTW.

**Comment by hariesfn** [comment]
This is the browser debug console of Cacti:

![image](https://user-images.githubusercontent.com/12947828/106413413-94329f80-647c-11eb-85c9-2d4855d7116c.png)

**Comment by TheWitness** [comment]
That is the network tab, not the console tab, but you are quickly becoming and expert ;)

**Comment by hariesfn** [comment]
Sorry,

Do you mean this  ?

![image](https://user-images.githubusercontent.com/12947828/106544773-b5f25c00-653a-11eb-826e-07fe35c51911.png)

**Comment by TheWitness** [comment]
Okay, so it's sending data over the wire.  So, go-to the network tab, and select one of the get requests, and go-to the response tab.  Do you see an image?

**Comment by hariesfn** [comment]
Please check:

![image](https://user-images.githubusercontent.com/12947828/106546593-264eac80-653e-11eb-8838-707af03bc776.png)

**Comment by TheWitness** [comment]
Looks good.  The graphs should be rendering.

**Comment by hariesfn** [comment]
Yes, it looks good on normal graph
![image](https://user-images.githubusercontent.com/12947828/106559363-dc72c000-6557-11eb-9aef-5b7addbfea26.png)

But when I check on real-time graph:

![image](https://user-images.githubusercontent.com/12947828/106560841-43917400-655a-11eb-8270-669cff3e1b36.png)

**Comment by TheWitness** [comment]
How does that template collect data?

**Comment by hariesfn** [comment]
That template is collecting data through snmp. And this kind of template works on Cacti 0.8.8's realtime, also.

I just import that template to my current Cacti 1.2.16.

Does my answer too general/simple ? Sorry

**Comment by TheWitness** [comment]
Can you run and `rrdtool info` on the realtime rrdfiles and see if they are getting data?  You can also put the `cmd_realtime.php` or `poller_realtime.php` into debug mode from `Console > Configuration > Settings > General` and actually see the RRDtool commands from the Cacti log.
