### ISSUE TITLE
No CLI commands support the "--list-rras" command in 1.0.4

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#411]
I have a back-end reporting script that used the 'cli/add_tree.php --list-rras --quiet' command in previous versions to keep track of RRAs and automatically generate an e-mail report for any changes made in the system. The '--list-rras' directive has been removed from add_tree.php and no other CLI commands support it. 

I can live without having it (the fear of anyone adding RRAs or making changes to existing ones has since passed) but I'd mark this one as a 'nice to have' feature.

**Comment by cigamit** [comment]
The option --list-rras was removed as we don't support the concept of RRA's now.  We have replaced RRA's with Data Source Profiles.  Data Source Profiles live with the Data Template and don't change from Data Source to Data Source per se.  The Data Source Profiles, once they are in use by Data Sources, become READ ONLY.  So, those issues with the earlier Cacti's should be gone now.

**Comment by eschoeller** [comment]
OK, that's fantastic news actually:) Can't wait to learn more about data source profiles!
