### ISSUE TITLE
Backtrace errors generated by graph_variables.php through unsetting not set variables

### ISSUE THREAD

**Issue by jsmalisa** [Cacti/cacti#4110]
Hi

I am getting this error below. Can someone assist me as I am not well versed with PHP. 

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

ERROR PHP NOTICE: Trying to access array offset on value of type null in file: /opt/cacti/lib/graph_variables.php  on line: 153
--

![image](https://user-images.githubusercontent.com/53674811/106413669-65292780-6496-11eb-99ac-ddd457ee6e37.png)

**Comment by bmfmancini** [comment]
What version of cacti?
How often is it happening?
When does it happen?

**Comment by jsmalisa** [comment]
I ran an upgrade on Ubuntu this morning and it stopped graphing. I believe
it could be related to PHP.

Advise what I should do.


Kind regards
John

**Comment by TheWitness** [comment]
Update lib/variables.php from the 1.2.x branch and report back.

**Comment by jsmalisa** [comment]
Advise how it's done as I am not familiar with it

**Comment by bmfmancini** [comment]
In Github go to the 1.2.x branch
Select the file click raw and you can wget the file to the server

Or you can git clone - b 1.2.x the cacti repo and copy over the file to
your cacti Dir

**Comment by jsmalisa** [comment]
Ok. Will do that and advise you

**Comment by jsmalisa** [comment]
Trying to WGET the variables.php but the connection is timing out.


+++++++++++++++++++++++++++++++++++++++++++++++++++
jmalisa@cactisvr02:~$ wget https://raw.githubusercontent.com/Cacti/cacti/1.2.x/lib/variables.php
--2021-02-02 13:14:11--  https://raw.githubusercontent.com/Cacti/cacti/1.2.x/lib/variables.php
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.28.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.28.133|:443...
failed: Connection timed out.
Retrying.

--2021-02-02 13:16:23--  (try: 2)  https://raw.githubusercontent.com/Cacti/cacti/1.2.x/lib/variables.php
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.28.133|:443... failed: Connection timed out.
Retrying.

--2021-02-02 13:18:35--  (try: 3)  https://raw.githubusercontent.com/Cacti/cacti/1.2.x/lib/variables.php
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.28.133|:443... failed: Connection timed out.
Retrying.
--2021-02-02 14:04:47--  (try: 4)  https://github.com/Cacti/cacti/blob/1.2.x/lib/variables.php
Connecting to github.com (github.com)|13.236.229.21|:443... ^C
jmalisa@cactisvr02:/opt/cacti/lib$ pwd
/opt/cacti/lib
+++++++++++++++++++++++

**Comment by TheWitness** [comment]
```git clone -b 1.2.x https://github.com/cacti/cacti.git some_directory```

**Comment by jsmalisa** [comment]
My Cacti files are in opt/cacti

![image](https://user-images.githubusercontent.com/53674811/106553338-f666cf80-6564-11eb-9740-09f511ab25a6.png)

Do I git clone to that directory?

Kind regards
John

**Comment by jsmalisa** [comment]
Could not GIT CLONE as well

++++++++++++++++++
jmalisa@cactisvr02:/opt/cacti$ sudo git clone -b 1.2.x https://github.com/cacti/cacti.git some_directory
[sudo] password for jmalisa:
Sorry, try again.
[sudo] password for jmalisa:
Cloning into 'some_directory'...
fatal: unable to access 'https://github.com/cacti/cacti.git/': Failed to connect to github.com port 443: Connection timed out
jmalisa@cactisvr02:/opt/cacti$
+++++++++++++++++++++

**Comment by TheWitness** [comment]
Looks like you have to setup a proxy.  Better just got github.com with your browser and learn to use the UI.

**Comment by jsmalisa** [comment]
Thanks, I'll check it out.

**Comment by jsmalisa** [comment]
updated lib/variables.php from the 1.2.x branch and still the same.

![image](https://user-images.githubusercontent.com/53674811/106688175-54ed8580-6619-11eb-829f-9c12ea2f609c.png)

**Comment by bmfmancini** [comment]
What version of PHP are you using?

**Comment by jsmalisa** [comment]
jmalisa@cactisvr02:/opt/cacti/lib$ php -v
PHP 8.0.1 (cli) (built: Jan 13 2021 08:21:37) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.1, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.1, Copyright (c), by Zend Technologies
jmalisa@cactisvr02:/opt/cacti/lib$

**Comment by bmfmancini** [comment]
That's your problem I think

Downgrade to 7.3 try it again

**Comment by jsmalisa** [comment]
I will try and advice

**Comment by jsmalisa** [comment]
I have downgraded to 7.4.14 and it is working now.

jmalisa@cactisvr02:~$ php -v
PHP 7.4.14 (cli) (built: Jan 13 2021 08:04:06) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.14, Copyright (c), by Zend Technologies

**Comment by TheWitness** [comment]
Going to re-open this one.  Want to confirm a few things before we close it.

**Comment by jsmalisa** [comment]
No worries 👍

**Comment by TheWitness** [comment]
Resolved now.

**Comment by bmfmancini** [comment]
@TheWitness  is this an issue just for PHP 8?

**Comment by TheWitness** [comment]
No, it's a corner case with either RRDfiles that have not been generated, or RRDfiles that do not have the MAX consolidation function in their Data Source profile.

**Comment by jsmalisa** [comment]
Why do I keep getting this every now and then.

![image](https://user-images.githubusercontent.com/53674811/107315903-502a4500-6ae3-11eb-9a85-44f412263943.png)

**Comment by bmfmancini** [comment]
Apply the fix that was pushed to the 1.2.x branch looks like the issue was with graph_variables.php

**Comment by TheWitness** [comment]
Since you are not on a supported configuration, I would suggest, since you are not a developer, to either 1) Get on a supported configuration, 2) Disable the snmpagent under Console > Configuration > Settings > Poller.

**Comment by jsmalisa** [comment]
Ok, I'll do that.

**Comment by jsmalisa** [comment]
[image: image.png]
