### ISSUE TITLE
Some graph and RRD file not update cacti 1.2.16

### ISSUE THREAD

**Issue by dargombesmarmoci** [Cacti/cacti#4111]
I installed cacti 1.2.16 on Ubuntu 20.04.  It is OK for some weeks.  Suddenly some graph and rrd file not update.
But some graph and rrd file is updated normally

![image](https://user-images.githubusercontent.com/33474566/106538664-2dba8980-652f-11eb-99cc-2347f50a5d18.png)

here some log message
![image](https://user-images.githubusercontent.com/33474566/106538730-4460e080-652f-11eb-93d3-8d8db88a65eb.png)

Any help ?

**Comment by TheWitness** [comment]
This does not look like a cacti problem, but an environment problem.  Those files are not related to cacti.  Maybe you have a script timing out cactus data collector.

**Comment by TheWitness** [comment]
Move this issue to the forums thou as it not related to cacti.
