### ISSUE TITLE
Cacti 1.2.14 Access Denied, user account disabled

### ISSUE THREAD

**Issue by Ali-arman** [Cacti/cacti#4112]
#  Cacti admin  user account disabled. Could you please help how to enable.

  Below is the error message: 
## Action failed
Sorry, we could not process your last action.
Access Denied, user account disabled

 Thanks.

**Comment by zuka1337** [comment]
This may help you: [59243](https://forums.cacti.net/viewtopic.php?f=7&t=59243)

**Comment by TheWitness** [comment]
Belongs on forums which are searchable with Google or duckduckgo.
