### ISSUE TITLE
Cacti 1.2.16 and PHP8

### ISSUE THREAD

**Issue by jayray-git** [Cacti/cacti#4114]
# Describe the bug

Will not work after upgrade to php8

## To Reproduce

upgrade to php8 on working system

Below I ran from shell "php index.php" and got the output below. Then ran spine and received similar output.

`
PHP Fatal error:  Uncaught ValueError: Unknown format specifier " " in /srv/http/cacti/include/global_languages.php:459
Stack trace:
#0 /srv/http/cacti/include/global_languages.php(459): sprintf()
#1 /srv/http/cacti/include/global_arrays.php(672): __()
#2 /srv/http/cacti/include/global.php(503): include_once('...')
#3 /srv/http/cacti/include/auth.php(28): require_once('...')
#4 /srv/http/cacti/index.php(25): include('...')
#5 {main}
  thrown in /srv/http/cacti/include/global_languages.php on line 459
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function CactiErrorHandler(), 4 passed and exactly 5 expected in /srv/http/cacti/lib/functions.php:4541
Stack trace:
#0 /srv/http/cacti/lib/functions.php(4624): CactiErrorHandler()
#1 [internal function]: CactiShutdownHandler()
#2 {main}
  thrown in /srv/http/cacti/lib/functions.php on line 4541
`
`
`
SPINE: Using spine config file [../etc/spine.conf]
WARNING: DB_PreG is no longer supported
SPINE: Version 1.2.14 starting
PHP Fatal error:  Uncaught ValueError: Unknown format specifier " " in /srv/http/cacti/include/global_languages.php:459
Stack trace:
#0 /srv/http/cacti/include/global_languages.php(459): sprintf()
#1 /srv/http/cacti/include/global_arrays.php(672): __()
#2 /srv/http/cacti/include/global.php(503): include_once('...')
#3 /srv/http/cacti/include/cli_check.php(45): include('...')
#4 /srv/http/cacti/script_server.php(25): require('...')
#5 {main}
  thrown in /srv/http/cacti/include/global_languages.php on line 459
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function CactiErrorHandler(), 4 passed and exactly 5 expected in /srv/http/cacti/lib/functions.php:4541
Stack trace:
#0 /srv/http/cacti/lib/functions.php(4624): CactiErrorHandler()
#1 [internal function]: CactiShutdownHandler()
#2 {main}
  thrown in /srv/http/cacti/lib/functions.php on line 4541
  
Top
1 post • Page 1 of 1
``

**Comment by TheWitness** [comment]
Pretty sure this is fixed in the 1.2.x branch.  Test there please, and report back.

**Comment by jayray-git** [comment]
upgrade from 1.2.16 to 1.2.18?

**Comment by jayray-git** [comment]
Resolved with upgrade to 1.2.16.. I may have been running a bit older version than I thought.
