### ISSUE TITLE
Mail addresses 1st level domain too restrictive (2 to 4 chars)

### ISSUE THREAD

**Issue by luskin72** [Cacti/cacti#4115]
I've modified site/lib/functions.php as follows

```
                // LK - 10.07.2019 - PHP 7.3 Bug Fix for buggy preg_match regex interpreter
                //      and was supposed that 1st level domain shoud be 2 to 4 chars only !!! NO GOOD for .local or .pizza :-)
                //      so, extended to range 2-10
                //$sPattern = '/([\w\s\'\"\+]+[\s]+)?(<)?(([\w\-.\+]+)@((?:[\w\-]+\.)+)([a-zA-Z]{2,4}))?(>)?/';
                $sPattern = '/([\w\s\'\"\+]+[\s]+)?(<)?(([\w\-\.\+]+)@((?:[\w\-]+\.)+)([a-zA-Z]{2,10}))?(>)?/';
                preg_match($sPattern, $email, $aMatch);
```

**Comment by netniV** [comment]
Given the newer formats of domains, this is actually needed, for example, cloud.market which is another example of a valid domain would fail to be validated against the original pattern.  Are you going to submit this as a pull request against the 1.2.x branch?  If so, please also include an entry in the CHANGELOG

**Comment by luskin72** [comment]
eheh I would... but I'm not skilled with git/github and wouldn't create damages... I'm not sure of what I'm doing with pull-reqs, branches an so on... and also, i'm using rel 1.2.2 (standard with debian 10) and don't know if this issue has already been fixed in later versions (just now i'm realizing that 1.2.17 is the last stable). so I only can hope that debian will update cacti package asap...

**Comment by TheWitness** [comment]
I'll fix this up this morning.  Meditating before the US Superbowl.  Not watching it per-se, but drinking through it for sure.

**Comment by TheWitness** [comment]
It looks like we relaxed this in subsequent releases.  We don't have the domain restriction on the current Cacti version 1.2.16+.  So, I'm going to close this and mark as duplicate.

**Comment by TheWitness** [comment]
It's for @paulgevers to decide.  We may get the 1.2.17 out in a few weeks.  Everyone is quite busy.

**Comment by paulgevers** [comment]
@luskin72 There's [Debian Backports](https://backports.debian.org/), which contains the latest cacti version. Does that work for you?

If not, and you think this bug should be fixed in Debian stable, then please file an appropriate bug in the [Debian bug tracking system](https://bugs.debian.org) clearly explaining why it's important enough to update stable for it.

**Comment by luskin72** [comment]
Really dont know... I'll have to try... maybe backports will work ok...
I'll open an issue on deb tracking.
Thnx a lot!
