### ISSUE TITLE
Cacti 1.2.16 - Get memory usage by every 10 second but graph data all are same and without change 

### ISSUE THREAD

**Issue by AndyLeung2021** [Cacti/cacti#4118]
I had configured 10 second data profile, then link it with data source template and graph template, and poller interval is default 5 mins, everything is ok, but finally I got the graph result that showed the data by every 10 secs in 5 mins are same and without any changes, did I misconfigure something?

![image](https://user-images.githubusercontent.com/77342455/107156788-502f2580-69bb-11eb-9181-7558a4c1c202.png)

![image](https://user-images.githubusercontent.com/77342455/107156758-342b8400-69bb-11eb-9ca2-de711aacb18d.png)

**Comment by TheWitness** [comment]
Well, it looks like its working, maybe the data collector script is getting garbage.  What are you using to collect the data?  I don't think this is a Cacti bug actually.

**Comment by TheWitness** [comment]
If it Data Collection is 10 seconds, that's what your poller interval MUST be too.  Switch that over.  After you have done that, you need to 'repopulate' your poller cache to distribute the data collection if you are mixing 10 second data collection with other things.

**Comment by TheWitness** [comment]
So, this is more of a training issue that a bug.  Do those two things and then you can report back here, though I'll be closing the ticket.  We can always reopen it later.
