### ISSUE TITLE
Cacti 1.2.2 - AUTH LOGIN: Template user id '' does not exist.

### ISSUE THREAD

**Issue by darius1706** [Cacti/cacti#4120]
# Describe the bug
Clean installation on Debian (from apt), version 1.2.2., Ldap AUTH.
When I create User Domain based on Ldap, and then I create user based on this domain, after login I got:

2021/02/09 18:03:13 - AUTH LOGIN: Template user id '' does not exist.
--
2021/02/09  18:03:13 - CMDPHP PHP ERROR NOTICE Backtrace:  (/index.php[25]:include(), /include/auth.php[167]:require_once(),  /auth_login.php[170]:domains_login_process(),  /auth_login.php[553]:CactiErrorHandler())
2021/02/09  18:03:13 - ERROR PHP NOTICE: Undefined variable: template_id in file:  /usr/share/cacti/site/auth_login.php on line: 553
2021/02/09  18:03:13 - CMDPHP PHP ERROR NOTICE Backtrace:  (/index.php[25]:include(), /include/auth.php[167]:require_once(),  /auth_login.php[170]:domains_login_process(),  /auth_login.php[552]:CactiErrorHandler())
2021/02/09  18:03:13 - ERROR PHP NOTICE: Undefined variable: template_id in file:  /usr/share/cacti/site/auth_login.php on line: 552
2021/02/09 18:03:13 - AUTH WARN: User 'xxxx' does not exist, copying template user
2021/02/09 18:03:13 - AUTH LOGIN: LDAP User 'xxxx' Authenticated from Domain 'Administrator'
2021/02/09 18:03:13 - AUTH LDAP: Binding with "uid=xxx,OU=SBSUsers,OU=Users,OU=MyBusiness,DC=mail,DC=xxx,DC=cz"
2021/02/09 18:03:13 - AUTH LDAP: Setting protocol version to 2
2021/02/09 18:03:13 - AUTH LDAP: Connect using ldap://xxx:389
2021/02/09  18:03:13 - AUTH LDAP_SEARCH: (/index.php[25]:include(),  /include/auth.php[167]:require_once(),  /auth_login.php[170]:domains_login_process(),  /auth_login.php[450]:domains_ldap_search_dn(),  /auth_login.php[647]:Ldap->Search(),  /lib/ldap.php[662]:LdapError::GetErrorDetails(),  /lib/ldap.php[325]:cacti_debug_backtrace())
2021/02/09  18:03:13 - AUTH LDAP_SEARCH: Authentication Success, DN:  uid=xxxx,OU=SBSUsers,OU=Users,OU=MyBusiness,DC=mail,DC=xxx,DC=cz
2021/02/09 18:03:12 - AUTH LDAP: Search using ldap://xxxx:389

**Comment by bmfmancini** [comment]
1.2.2 is pretty old
I know that in 1.2.14/15 there was a LDAP fix I would suggest updating to
1.2.16 from the 1.2.x repo

**Comment by darius1706** [comment]
It helps, thank you very much.
