### ISSUE TITLE
At the end of install, cacti produces an HTTP 500

### ISSUE THREAD

**Issue by dlynes** [Cacti/cacti#4125]
There is an error on line 4119 of cacti/lib/functions.php:

$logcontents = tail_file($config['base_path'] . '/log/cacti.log', 100, -1, ' INSTALL:' , $page_nr, $total_rows);

It should have the ", $total_rows" removed from the end.  The tail_file function uses a default of 0 for total_rows, and total_rows is not defined in getInstallLog() in functions.php.  That is why the HTTP 500 is produced.

**Comment by TheWitness** [comment]
What version of Cacti is this?  What version of PHP is this?

**Comment by TheWitness** [comment]
Okay, I've confirmed.  I'm guessing php74 or php8x.

**Comment by dlynes** [comment]
Php 7.3, latest version pulled from git.
________________________________

**Comment by dlynes** [comment]
Now that I’m at the office, I’ve got the specifics:

Php 7.3.19 and Cacti 1.3.0-Dev (git)

**Comment by dlynes** [comment]
Just an FYI, that parameter of ', 500' wasn't in the git code I grabbed.  It was ', $total_rows', but $total_rows wasn't defined.

**Comment by TheWitness** [comment]
Need to merge 1.2.x with develop.  Was not able to do it due to a GitHub desktop bug.  Have to see if it's fixed now.
