### ISSUE TITLE
Real-time graphics showing data, but normal graphics remain empty

### ISSUE THREAD

**Issue by globaluty** [Cacti/cacti#4128]
Hi, team.

Debian 9, freshly installed Cacti 1.2.16

Added one Ubuntu and one Debian Linux servers via SNMP v2. Tried adding the servers using different templates (Generic SNMP device, Local linux machine, NET SNMP device), nothing changes.

The problem is that normal graphics do not show any data. Check screenshot below:

![image](https://user-images.githubusercontent.com/79117847/107998721-6443da00-6fee-11eb-9ea7-115f8c2ee2d1.png)

How the realtime graphics look like after clicking on realtime button for each graphic:

![image](https://user-images.githubusercontent.com/79117847/107998952-e46a3f80-6fee-11eb-8623-5746382f7730.png)

How logs tab looks like:

![image](https://user-images.githubusercontent.com/79117847/107999184-7ffbb000-6fef-11eb-80cf-b5983002629e.png)

Maybe it is not a bug but a config issue and I would appreciate your help.

**Comment by bmfmancini** [comment]
Check your rra folder permissions they should match the same user the
poller is running as

Reach out to me if. You need help

**Comment by globaluty** [comment]
Thanks for the reply.

poller is executed by cron job:
* * * * * /usr/bin/php /var/www/html/cacti/poller.php >/dev/null 2>&1

/var/log/syslog
Feb 16 03:58:01 cacti CRON[4612]: (root) CMD (/usr/bin/php /var/www/html/cacti/poller.php >/dev/null 2>&1)
Feb 16 03:59:01 cacti CRON[4994]: (root) CMD (/usr/bin/php /var/www/html/cacti/poller.php >/dev/null 2>&1)
Feb 16 04:00:01 cacti CRON[5674]: (root) CMD (/usr/bin/php /var/www/html/cacti/poller.php >/dev/null 2>&1)
Feb 16 04:01:01 cacti CRON[6724]: (root) CMD (/usr/bin/php /var/www/html/cacti/poller.php >/dev/null 2>&1)

I changed ownership of /var/www/html/cacti/rra to root with 777 permissions on all sub-files.
drwxrwxrwx 2 root     root      12288 Feb 16 10:27 rra

After this change, added servers from yesterday showed the graphs. 

Now I tried to add new linux servers with same settings. Unfortunately the graphs for them remain still empty even after 1,5 hours. Again - realtime graphs are working.

Interesting, I stopped temporarily cron job for the poller, it did not run for 20 minutes, but the graphs for first two servers still showing info for period when poller did not work.

Maybe I am still missing something. Thank you.

**Comment by globaluty** [comment]
Without any changes since my last reply here, now I can see that graphics have drown something on new servers (after ~6 hours they were created).

Now I can see also gap in all graphisc for a period of time. No explanation about that also. See screenshots:

![image](https://user-images.githubusercontent.com/79117847/108092210-23e36b00-7085-11eb-8bdb-9ecfad3e5274.png)

Following image is from last added server:

![image](https://user-images.githubusercontent.com/79117847/108092285-3a89c200-7085-11eb-922f-432f025fd0b4.png)

At the same time poller looks good:
![image](https://user-images.githubusercontent.com/79117847/108092368-53927300-7085-11eb-9ab5-0e5a759744d1.png)
![image](https://user-images.githubusercontent.com/79117847/108092397-5db47180-7085-11eb-9d22-859aa5359201.png)

I really don't have any clue why both things happen. For me it looks like totally broken.

No changes, no downtimes, nothing was done since my last reply. (7 hours ago)

I would be happy of your assistance.

**Comment by TheWitness** [comment]
Not to be rude, but could you take this one to the forums guys.  Thanks.
