### ISSUE TITLE
Cacti 1.2.16 - RRD cannot be updated after switching from SPINE to cmd.php

### ISSUE THREAD

**Issue by iskandarbasman** [Cacti/cacti#4129]
# Describe the bug

Troubleshooting another issue polling timeout on cacti.
Tried to see if cmd.php poller could resolve the issue.
Cacti graphs stop updating, switch back to SPINE poller does not help.

## To Reproduce

Not sure if the problem can be reproduced.
Not going to experiment on my production can for now.

Only way to resolve the problem is to replace the RRD files with an old backup.

Need comments on how to troubleshoot further on how to troubleshoot the broken RRD files.

**Comment by bmfmancini** [comment]
Run spine manually let's test the config

. /spine -R - V 5

What's the output

**Comment by iskandarbasman** [comment]
Emailed you the output.
But I don't se much difference.

**Comment by anarkia1976** [comment]
What version of spine do you used? latest 1.2.x branch?

**Comment by iskandarbasman** [comment]
Spine 1.2.16 as well.

> 
> 
> What version of spine do you used? latest 1.2.x branch?

**Comment by TheWitness** [comment]
cmd.php does not have the same level of parallelism as spine.

**Comment by iskandarbasman** [comment]
But the issue I am seeing, it seems like all the RRD files got corrupted by switch.
How can we determine why the RRDs are not updating ?

Can we check the RRD files itself ?

> 
> 
> cmd.php does not have the same level of parallelism as spine.

**Comment by anarkia1976** [comment]
Update to the latest branch related to "spine & cacti", re-check rrd population please, it seem fixed from my point of view.

**Comment by TheWitness** [comment]
spine and cmd.php don't have anything to do with RRDfiles, and won't corrupt them.  Likely your spine was misconfigured.

**Comment by TheWitness** [comment]
Let's take this one to the forums please.  I know we are behind on the 1.2.17 release, but I'm still kind of in the middle of verifying some finer points on a pretty big install.
