### ISSUE TITLE
php 8.0 and mib_cache.php & vs && error

### ISSUE THREAD

**Issue by Kveri** [Cacti/cacti#4133]
# Describe the bug

After upgrading to php 8.0 and upgrading cacti to 1.2.16 I get this error when running spine:

2021/02/17 21:14:53 - SYSTEM STATS: Time:24.5813 Method:spine Processes:1 Threads:40 Hosts:xyz HostsPerProcess:xyz DataSources:xyz RRDsProcessed:xyz
PHP Fatal error:  Uncaught TypeError: Unsupported operand types: array & bool in /var/www/default/cacti/lib/mib_cache.php:344

Checking line 344 in lib/mib_cache.php gives this:
if ($columns & cacti_sizeof($columns)>0) {

do we really want to BINARY AND $columns and cacti_sizeof($columns)>0 ??

Shouldn't it be && actually (logical AND operator)?

I modified it to && an it works without an error.

This needs to be fixed in delete and update functions in mib_cache.php file.

Looks like that this check silently works before php 8.0 and always gives such a result that the system works.

## To Reproduce

Run the poller.
## Expected behavior

That it ends without and error.

**Comment by Kveri** [comment]
Added pull request #4134

**Comment by TheWitness** [comment]
This has been resolved in this commit https://github.com/Cacti/cacti/commit/f0d3d28f9f5a72eb4e9146a4e4a8640fc4e52efb.  I'll close this one, but keep the pull open.  We have a big merge upcoming for develop just as soon as we can confirm GitHub Desktop is fixed.
