### ISSUE TITLE
[CACTI 1.2.X] Latest - PHP7.4 - Ubuntu 20.04 - PHP Web Datacollector Timezone selection problem

### ISSUE THREAD

**Issue by anarkia1976** [Cacti/cacti#4139]
# Describe the bug

Unfortunately on a new clean server installation I do not have the possibility to select the "Europe / Rome" timezone for the datacollector. 

## To Reproduce

Ubuntu 20.04.
PHP 7.4.3.
Cacti clean install.

When i select "timezone" only these options are present:
![image](https://user-images.githubusercontent.com/1744639/108504321-faf5ec80-72b5-11eb-8d0a-c30d2a5f32fb.png)

PHP Settings:
vim /etc/php/7.4/apache2/php.ini
vim /etc/php/7.4/cli/php.ini

date.timezone = Europe/Rome
memory_limit = 1G
max_execution_time = 60

System Time and date:
timedatectl
               Local time: Fri 2021-02-19 13:29:16 CET
           Universal time: Fri 2021-02-19 12:29:16 UTC
                 RTC time: Fri 2021-02-19 12:29:16
                Time zone: Europe/Rome (CET, +0100)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no

Do you have any suggestions?

Thanks a lot

**Comment by netniV** [comment]
Timezone's are pulled from MySQL so as long as you have setup the timezones info correctly and granted users access to it, these should be properly populated.

**Comment by netniV** [comment]
```sql
SELECT Name AS id, Name AS name FROM mysql.time_zone_name ORDER BY name
```

**Comment by anarkia1976** [comment]
you were absolutely right, I had completely skipped this step: 

MariaDB [(none)]> SELECT Name AS id, Name AS name FROM mysql.time_zone_name ORDER BY name;
+--------------------+--------------------+
| id                 | name               |
+--------------------+--------------------+
| Europe/Moscow      | Europe/Moscow      |
| Japan              | Japan              |
| leap/Europe/Moscow | leap/Europe/Moscow |
| MET                | MET                |
| Universal          | Universal          |
| UTC                | UTC                |
+--------------------+--------------------+
6 rows in set (0.000 sec)

I have applied this:
mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root -p mysql

now it's ok, thanks a lot as always.
