### ISSUE TITLE
Install Wizard - check for typical Spine locations

### ISSUE THREAD

**Issue by BSOD2600** [Cacti/cacti#414]
The latest 1.0.5 install wizard does not give an option to specify the path to Spine on the critical paths page.   It should check for the common Linux and Windows path(s). What a user completes the wizard and visits Settings -> Paths -> Spine it shows "enter a valid path"

**Comment by cigamit** [comment]
Provide where you think spine would be placed?

**Comment by cigamit** [comment]
Verifying

**Comment by cigamit** [comment]
From your perspective which is the 'default' location for spine?

**Comment by cigamit** [comment]
Resolved, thanks!
