### ISSUE TITLE
Adding custom OID graph to host wont show up in the hosts graphs.

### ISSUE THREAD

**Issue by snoozer** [Cacti/cacti#4140]
I have added a host and created graphs.  few hours later I have added custom OID graphs which are there and working when I look at them in Device -> Graphs List -> Graph in question. The graph works. In the Graph tab in the host the graphs don't show.

To reproduce create a host and add graphs. At a later stage add Custom OID graphs.

I expected the same behaviour I have seen with older versions of Cacti where all graphs would show up in the host with all the other graphs for that host.

Device: R-Pi 4, Cacti installed via apt install. Verion 1.2.2

Browser: Firefox and Chrome on Windows 10

**Comment by TheWitness** [comment]
Upgrade Cacti.

**Comment by TheWitness** [comment]
You have to move them there.  But please get off that old version.
