### ISSUE TITLE
Deleting Devices Results in an HTTP 500 Error

### ISSUE THREAD

**Issue by dlynes** [Cacti/cacti#4142]
# Describe the bug

In 1.3.0-Dev on PHP 7.3, if you try deleting a couple of devices (in my case, all devices), you'll get a 500 Internal Server Error.

The resultant trace is:

AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to sanitize_unserialize_selected_items() must be of the type array, string given, called in /home/taftforwardmon/public_html/cacti/host.php on line 315 and defined in /home/taftforwardmon/public_html/cacti/lib/functions.php:3684\nStack trace:\n#0 **/home/taftforwardmon/public_html/cacti/host.php(315): sanitize_unserialize_selected_items('a:2:{i:0;s:1:"2...')\n#1** /home/taftforwardmon/public_html/cacti/host.php(70): form_actions()\n#2 {main}\n  thrown in /home/taftforwardmon/public_html/cacti/lib/functions.php on line 3684', referer: https://taftforwardmon.hammersoftware.ca/cacti/host.php?

As you can see from the line I bolded, the value being passed to sanitize_unserialize_selected_items() from line 315 of host.php is not actually an array.  It is serialized, but it's not an array.  Part of the data structure is an array, however.

## To Reproduce/

1. Expand the Management menu
2. Click on the Devices menu item
3. Select the check all checkbox next to the word 'Created' in the data list header
4. Choose the action 'Delete' from the drop down box
5. Click 'Go'
6. Select the radio button 'Delete all associated Graph(s) and Data Source(s).'
7. Click 'Continue'
8. You'll get an action failure:
      Sorry, we could not process your last action.
      Error:	500 Internal Server Error
      Reason:	The response to the last action was unexpected.
9. And you will also get the stack trace I pasted above in your apache error log.

## Expected behavior

Expected devices to get deleted.

## Desktop (please complete the following information)

- Windows 10 20H2

- Chrome 88.0.4324.150

- 1.3.0-dev

## Additional context

Multiple HTTP 500's in this version.  Will detail more today as I come across them.

**Comment by netniV** [comment]
I need to test if this is still an issue on dev.  There were some changes and some backed out changes.

**Comment by moutzl** [comment]
probably same issue, also trying to delete ANY number of devices  ends the same error in log

2021/05/01 20:57:53 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
2021/05/01 20:57:53 - ERROR PHP ERROR: Uncaught TypeError: Argument 1 passed to sanitize_unserialize_selected_items() must be of the type array, string given, called in /opt/mikenopa/cacti/site/host.php on line 294 and defined in /opt/mikenopa/cacti/site/lib/functions.php:3193 Stack trace: #0 /opt/mikenopa/cacti/site/host.php(294): sanitize_unserialize_selected_items('a:1:{i:0;s:2:"1...') #1 /opt/mikenopa/cacti/site/host.php(70): form_actions() #2 {main} thrown in file: /opt/mikenopa/cacti/site/lib/functions.php on line: 3193

**Comment by TheWitness** [comment]
@netniV, were you planning on fixing this?

**Comment by netniV** [comment]
This was a development issue and I think has actually been corrected already.  It shouldn't be a problem in 1.2.x since we don't use typing there.  Let me see if I can find the commit, since I fixed it when I had the issue without noticing this one.

**Comment by netniV** [comment]
Well, it seems my memory is bad because I did comment on this issue but forgot about it.  However, I did fix it as part of #3740 in commit 408a1aa78.
