### ISSUE TITLE
ifAlias missing from Cisco Nexus when using snmpv3

### ISSUE THREAD

**Issue by andermat8** [Cacti/cacti#4145]
Running Cacti 1.2.16 with PHP 7.0.24 in Windows Server 2012.  We are trying to migrate devices over to use snmpv3.  I'm only aware of this issue with Nexus but I'll need to test and verify.  We normally see ifAlias as a column when creating a graph but once we switch to v3 this column disappears.  Workaround is to setup with snmpv2, index, and then switch to v3 but this is just a band aid.  Nexus is using AES 256.  

You can reproduce by setting up a device with snmpv2 and go to create a graph and you should see the column Alias (IF-MIB) which provides the interface details.  Switch to snmpv3 and the column should disappear.  This also will impact graphs that use the ifAlias information.

**Comment by andermat8** [comment]
Seeing same issue with Cisco ISRs

**Comment by TheWitness** [comment]
So, if the ifAlias in the resource XML file?  If so, I'm not sure if this is a Cacti issue.  You should try and walk the ifAlias and see if it actually returns something.  Let us know.

**Comment by andermat8** [comment]
Yes, I can successfully walk the Ifalias from a command line.

**Comment by andermat8** [comment]
From what I can see this is only an issue when using AES.  I did a spot check of the 390 devices using snmpv3 and any using MD5 display the Alias (IF-MIB) but when using AES the column disappears.

**Comment by TheWitness** [comment]
Show output from verbose query.  Make sure that when testing you use bulkwalk.

**Comment by andermat8** [comment]
Sorry for the late response.  Work has been a bit busy as of late.  I realized that I'm doing my snmpwalk with version 5.7.3 but my instance on the server is using version 5.5.  I can't walk any device with AES using 5.5 so perhaps this is the issue?  Can Cacti 1.2.16 use net-snmp version 5.7.3?

**Comment by andermat8** [comment]
I found bits for 5.7.3 for Windows and added it to my lab instance running 1.2.14 and after re-indexing a device the Alias (IF-MIB) is now visible using snmpv3 with SHA/AES.  Going to test some more but that looks like the issue just not sure if I broke anything else by updating net-snmp.  Cacti is packaged with net-snmp 5.5, correct?  If so, can this get updated to use 5.7.3 or 5.8 in future builds?

**Comment by andermat8** [comment]
Cacti with snmp 5.5
![image](https://user-images.githubusercontent.com/29753529/110494566-bba30a80-80c1-11eb-8c07-bc55356bd7d8.png)


Cacti with snmp 5.7.3
![image](https://user-images.githubusercontent.com/29753529/110494631-c8bff980-80c1-11eb-8348-7b1256a7b636.png)

Also, with snmp 5.5 I only find 248 items and with 5.7.3 I find 347 items for the same device.

**Comment by TheWitness** [comment]
So, can we conclude that this issue is a 3rd party issue or a timeout issue?

**Comment by andermat8** [comment]
From what I see the issue is with using net-snmp 5.5.  Will Cacti get packaged in the future with an updated version of net-snmp or can I update it myself?  Is Cacti compatible with net-snmp 5.7.3 or 5.8?

**Comment by TheWitness** [comment]
Well, the Cacti Windows packing is done by a third party.  He takes tips.

**Comment by andermat8** [comment]
LOL!  Okay, I understand but can you tell me if Cacti compatible with net-snmp 5.7.3 or 5.8?  You can install Cacti on Windows without the package.

**Comment by TheWitness** [comment]
Yea, for the most part.  Things like AES256 and AES512 are not supported presently, but there are Enhancement request in for such things, but the whole command set is rock solid.

**Comment by andermat8** [comment]
Okay, cool.  We are using AES128 at present so should be good.  Seems to be running fine in the lab with 5.7.3 but I'll do more testing.  Thanks for your help.
