### ISSUE TITLE
Input function buttons invisible or missing

### ISSUE THREAD

**Issue by WirthmU** [Cacti/cacti#4146]
Using cacti V1.2.16 on Linux/Ubuntu.
For some time now the function buttons in the Console>Templates menu have disappeared (i.e. move up, move down, delete, add etc). Some of the functions still there by hovering but invisible and others have completely disappeared.
I have checked the forum without any success.

It happens with both Firefox and Chrome as browsers.

![image](https://user-images.githubusercontent.com/27740335/109123886-9a016500-774a-11eb-9c65-692c7e5377b3.png)

**Comment by TheWitness** [comment]
If you installed from apt-get, you should first submit a bug to the Debian bug tracker.  Adding @paulgevers as a head's up.

**Comment by WirthmU** [comment]
@paulgevers

Unfortunately Ubuntu is not supported by the Debian bug tracker - I am a bit lost.

**Comment by paulgevers** [comment]
@WirthmU I fear I'm seeing what's expected on my Debian bullseye system.

![image](https://user-images.githubusercontent.com/3652166/109708149-5324cc80-7b9b-11eb-8555-4496d7d5cb98.png)

**Comment by netniV** [comment]
Can you check your console tab of the developer tools and see if there are any errors.

**Comment by WirthmU** [comment]
I would not know where to find the developer tools in the console tab?

**Comment by TheWitness** [comment]
On a PC, in any browser, hit F12.  Then, you will get a new tabbed section, generally below the browser window.  One of those sections is the 'Console'.  What I suggest you have is a very long line somewhere, and the content is rolling off the screen.  Can you see if all your templates are this way or just some?  Also, check the Cacti log for warnings.
