### ISSUE TITLE
Upgrade to Cacti 1.0.5

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#415]
There is an error after upgrade for *all* the hosts.

POLLER: Poller[1] WARNING: Unable to open session for System Mib collection for Device[516] HOSTNAME

**Comment by interduo** [comment]
I tried to recache: POLLER: Poller[1] ASSERT: 'U<86285000' failed. Recaching host '127.0.0.1', data query #1 

Tried also to rebuild SNMP cache.

Also did not help.

**Comment by cigamit** [comment]
Yea, sorry, did not test with cmd.php.  Updating shortly.

**Comment by cigamit** [comment]
Should be resolved.  Update cmd.php

**Comment by interduo** [comment]
How to delete/make an averge data in a GAP in all of the graphs?

**Comment by interduo** [comment]
2017-03-13 12:00:13 - POLLER: Poller[1] WARNING: Unable to open session for System Mib collection for Device

**Comment by interduo** [comment]
What I have to do to resolve this?

**Comment by cigamit** [comment]
Did you update the cmd.php with the latest from the development branch?  There is a removespikes.php in the cli directory.  Please test on a few graphs.  If you don't have a lot of graphs, you can correct from the GUI using the SpikeKiller graph icon.

**Comment by cigamit** [comment]
Okay, update functions.php.  Found another fly in the ointment.

**Comment by interduo** [comment]
Now it's good.

Is it possible to run removespikes.php for **all the rrd's** for a specified gap only?

**Comment by cigamit** [comment]
You will have to cycle through the templates one at a time.  There is no 'bulk' option presently other than by template.  You should create a pull request that changes that.

**Comment by cigamit** [comment]
The gap fill option is what you should be using.
