### ISSUE TITLE
Stray graphs and cluttered legend in aggregate diagrams

### ISSUE THREAD

**Issue by bernisys** [Cacti/cacti#4153]
# Describe the bug

I have a graph template for CPU load, which has two lines plotted, coming from the same data source, but with two consolidation functions: one "average" and one "max". I use this for CPU load plots, to see also the peaks, which would have otherwise been averaged out in the long-term diagrams.

I have created an aggregate from that a graph template to have the overview about a few hosts (in fact our remote pollers) in one glance.

While the data i need is in there and i can roughly see what is going on, the diagram looks rather cluttered.
  - additional lines (actually disabled in the template), each one drawn only with the first color from the assigned color-template
  - legend contains cluttered descriptions with the hostname from the additional lines included
  - the activated legend items are prefixed with only the 1st color from the template
  - the additional legend items from the unwanted graphs use the correct colors
  - the additional items are prefixed to the following legend-rows,a s they are added after the CR/LF but don't contain CR/LF themselves

This was happening in cacti 1.2.2 and persisted after upgrading to 1.2.14 - haven't tested 1.2.16 yet, but would assume the same result.

## To Reproduce

I'm not sure if this is at all a reproducible behavior, because it affects not every aggregate, but only specific ones.
Maybe it depends on the original graph having several graph-objects from the same data source.

So here is my assumption what to do:
 1. create a graph template with two graphs coming from the same data source:
   - first one with consolidation "average" selected
   - then a legend with cur/avg/max of this first graph item
   - then a second graph item from same data source with "max" consolidation
   - finally a "hrule" item (just to make sure you reproduced my complete setup)
 2. create an aggregate template with only the "average" (first) line active
   - assign a color-template to the active one
   - activate also the legend items
   - deactivate the second graph item
 3. create a new aggregate from this template, adding a few hosts
 4. observe the plot and the legend

## Expected behavior

Only the selected lines should be plotted.
Legend should be intact and not show additional items.

## Screenshots

![cacti - aggr load pollers](https://user-images.githubusercontent.com/32120318/109642970-e6d2aa80-7b53-11eb-8dcd-be0a61794110.png)

**Comment by TheWitness** [comment]
I think you need to test this on a more recent version.  If you choose 'skip' on the Template, the Graph Items should be skipped.  Now there was a small bug that you maybe encountering where a change to a Aggregate may be missed.  Gave it a lot of thought, but sometimes, when I think, there is actually no one at the Inn.  So, there maybe a bug somewhere.

**Comment by TheWitness** [comment]
Tested this on 1.2.17 and I can not reproduce the issue.  So, good news for you...

**Comment by bernisys** [comment]
Okay, we'll see if it persisits, once '17 is out :) - i can reopen the bug if needed.
Maybe there are relics from earlier bugs, but i had recreated the complete aggregate tempalte in 1.2.14 and it was still present.
Also checked the graph template and saw nothing unusual in there as well.
let's see. I'm confident. :)
