### ISSUE TITLE
PHP version recommendation for last cacti version

### ISSUE THREAD

**Issue by ghramos** [Cacti/cacti#4154]
Hi,

Can anyone tell me how the best PHP version is?

I'm installing Cacti 1.2.16.

Best regards,

Guilherme

**Comment by netniV** [comment]
You should be using a supported version of PHP, but the minimum is 5.4.

**Comment by browniebraun** [comment]
From a safety standpoint I would recommend the latest releases of 7.3 or 7.4. 
I have already PHP8 running, but not in production.

**Comment by xmacan** [comment]
I can recommend 7.4. I have 7.4 maybe one year with cacti 1.2.x without any problems

**Comment by ghramos** [comment]
I have installed Cacti with PHP 7.0 because **Spine** doesn't work with the version above.

**Comment by xmacan** [comment]
PHP 7.0 isn't supported:
https://www.php.net/supported-versions.php

which OS distribution?  Which spine version? 

I guess that spine is PHP independent

**Comment by TheWitness** [comment]
@xmacan, you are correct.

**Comment by ghramos** [comment]
I'm using Debian 9.13 and Spine 1.1.38.

I have installed Spine with PHP 7.4, but Cacti has reported some errors in some scripts.

So, i have tried to use with PHP 7.0 and the errors disappears.

I will upgrade Debian to see what happens.

**Comment by ghramos** [comment]
I have upgraded Debian to version 10.8 and PHP has upgraded to version 7.3 too.

Cacti still working and Spine too.

I will monitoring and then upgrade Spine to the last version to see what happens.

I'm taking snapshots of the VM before doing this changes.
