### ISSUE TITLE
Remote Pollers - Recovery process tracking

### ISSUE THREAD

**Issue by browniebraun** [Cacti/cacti#4155]
# Describe the bug
Unfortunately, it can really happen that multiple recovery processes will be triggered for whatever reason (auto + manual).
I just had the situation where the master poller broke and after its fix, remote pollers were having up to 3 recovery processes running in parallel. This should be avoided as the recovery processes are blocking themselves and will bring the local DB instance to its limits.

Recovery processes should be tracked.

**Comment by TheWitness** [comment]
This issue was resolved here https://github.com/Cacti/cacti/commit/ba4e34beda52873298f1b1f1488b7b64491c50be
