### ISSUE TITLE
Allow admin emails to utilise CLOG-style ID to name/link replacements

### ISSUE THREAD

**Issue by xmacan** [Cacti/cacti#4157]
Sometimes I get email with warning: 
**Poller Output Table not empty for poller id 1. Issues: 1, DS[15860].**
and I have to find which Device and value has problem.

It would be better add more information:
Poller Output Table not empty for poller id 1. Issues: 5, 
DS[15860] - data source name 
DS[1380] - data source name 

I guess that will be small code change. Does it make sense to you? I can prepare PR.

**Comment by TheWitness** [comment]
If you access that from the Log tab, Cacti will replace DS[xxx] with a hyperlink to the Data Source.  Or, are you trying to do debuggin in a script?

**Comment by xmacan** [comment]
no, I mean in the email.

**Comment by netniV** [comment]
Hmm, so yeah would be good if the admin email utilised the same string replacement techniques.  Maybe we should move the clog_regex_xxx functions to be more generic in 1.3 @TheWitness ?

**Comment by TheWitness** [comment]
@netniV, I guess one should be able to deliver their own array options to overlay the known ones.  Sure.
