### ISSUE TITLE
Tree rule automatically adding graphs to correct location and also wrong location

### ISSUE THREAD

**Issue by stormonts** [Cacti/cacti#4159]
We are running Cacti 1.2.16.  We have a tree rule (shown below) that is supposed to add graphs to a specific part of the tree (which is working) but the graphs are also being added to a totally different tree level.

![rule](https://user-images.githubusercontent.com/25824323/110252634-541b7c80-7f54-11eb-8ced-4911bc4979e5.png)

In the image below, the graphs are being correctly placed in the section marked in red, but they are also being placed at the tree level highlighted by the green arrow. We don't have any rules setup to put graphs in that location.

![tree](https://user-images.githubusercontent.com/25824323/110252645-6990a680-7f54-11eb-9659-a2fb4585c96c.png)

I verified that none of our tree rules point to the tree where the graphs are being incorrectly created (SE...) at the "Hook into tree" or "At Subtree" setting.

**Comment by TheWitness** [comment]
Do you have any other Tree Rules?  I did a cursory look at the code, and nothing jumped out at me.  There have been some bugs logged where the users want the Automation to stop at the first matched Tree Rule vs. running through all the rules.

**Comment by stormonts** [comment]
Yes, there are other rules, but not that specify the location on the tree where the graphs are being added.

Steve

**Comment by TheWitness** [comment]
Deferring this to post 1.2.17.

**Comment by TheWitness** [comment]
This is related now to #412.  @stormonts, We are doing a major redesign in 1.3 for Automation.  I'm going to close this now.  But moving forward, you can associated Graph and Tree rules to a Device Rule, and have exit conditions and sequences for Tree Rules, which I think matches your original requirements.  If not, please open a new ticket and let's discuss.
