### ISSUE TITLE
Reapply suggested name  feature in graph management not working 

### ISSUE THREAD

**Issue by gj00354347** [Cacti/cacti#4165]
Dear Developers,

we have created a template for disk utilisation and while creating the template we left the vendor name in graph title . But later we wanted to remove the vendor name from title of the graphs which shows disk utilisation.

so we changed the graph template and in graph template we modified the graph title and removed vendor name from there. And then we went to graph management (Management -->Graphs ) and selected the particular template (used template filter) and then from drop down menu I chose reapply suggested name . But unfortunately it did not work .

I enabled debug from cacti GUI (log level was debug) and then I also changed the level to developer one . But could not get any thing concrete .
Here is log for you in case if it helps you 
2021-03-12 14:24:16 - WEBUI Obtaining 'Graph Template' cache
2021-03-12 14:24:16 - WEBUI Detected need for forced template cache refresh:
2021-03-12 14:24:16 - WEBUI Killing Session Cache due to device or template change
2021-03-12 14:24:26 - WEBUI Store InitRows:-1, Hash:1597d7f033a83a19f5b1a2356ce08ea0
2021-03-12 14:24:48 - WEBUI Obtaining 'Graph Template' cache
2021-03-12 14:24:48 - WEBUI Detected need for forced template cache refresh:
2021-03-12 14:24:48 - WEBUI Killing Session Cache due to device or template change
2021-03-12 14:24:58 - WEBUI Store InitRows:-1, Hash:1597d7f033a83a19f5b1a2356ce08ea0
2021-03-12 14:25:33 - WEBUI Obtaining 'Graph Template' cache
2021-03-12 14:25:33 - WEBUI Detected need for forced template cache refresh:
2021-03-12 14:25:33 - WEBUI Killing Session Cache due to device or template change
2021-03-12 14:25:33 - WEBUI Store InitRows:-1, Hash:1597d7f033a83a19f5b1a2356ce08ea0

then I thought of using cli feature to do the renaming I used it but no change happened here as well.
no change for disk utilisation
DEBUG: Graph Name 'hostdescription - vendorname - Disk Utilization (MB)' starting
DEBUG: Graph Rename Done for Graph 'hostdescription - vendorname - Disk Utilization (MB)'

actually the vendorname should have gone after reapplying suggested name but it is still there .

steps to produce 
make a template for disk utilisation , leave the vendor name there and then modify graph title in graph template and then try to REAPPLY SUGGESTED NAME feature from drop down menu of graph management after filtering the appropriate graph template .

cacti version - 1.2.14
os - RHEL 7.8 Maipo
php PHP 5.4.16
mysql   Distrib 5.5.65-MariaDB,

Let me know if anything else is required as many times we change the template name and want to update the old graph name and it remains same and then we have to go for creating new graphs and then merging rrd which becomes a pain.

Best Regards,
Gopal

**Comment by netniV** [comment]
Did you also sync your template ?

**Comment by gj00354347** [comment]
Hi 

what do you mean by sync your template ?? Generally we create a new template , add it to a host template and then , in device management page we filter the devices by host template and then apply "SYNC HOST TEMPLATE".

but here we have updated the graph template , like updated title and then went to graph management page , chose the graph template filter and then did "REAPPLY THE SUGGESTED NAME" .

can you please explain it a little bit .

Best Regards,
Gopal

**Comment by TheWitness** [comment]
No change will happen if the specific Data Query index has been deleted.  When this happens, Cacti can not change the name as the content of the Graph would can not be fully resolved.  So, the graph in question may be an orphan.  You can tell this once you get to Cacti 1.2.17 by clicking on the 'orphans' checkbox when viewing graphs.  It may even work now, but it's slower.  If you only have a few thousand graphs, it should perform pretty well though.

I've texted re-apply otherwise, and it's working fine.  So, I'm going to close this, and I would suggest you continue the conversation on the forums.

**Comment by gj00354347** [comment]
Hi Witness,

actually it’s not a graph template based on data query instead it is based on data template which makes use of GET SNMP DATA and single OID so there is no data query .

So is there any way out I can rename such graphs which are based on single oid and makes use of GET SNMP DATA .in my case it is for disk usage , which is fetched by Single OID.

Best Regards,
Gopal
