### ISSUE TITLE
Unable to upgrade from Cacti 1.1.38 to cacti 1.2.16 platform

### ISSUE THREAD

**Issue by ikorzha** [Cacti/cacti#4168]
Cacti team, for the last 2 years I am struggling to move off 1.1.38 cacti to cacti 1.2.x platform.
Unfortunately every upgrade ends in failure and I am forced to restore from backup, due to 1st spine poller run deleting all devices, graphs and thold alarms..
My environment as following:
CentOS 7.5, + 5 distributed pollers in different regions.
Cacti 1.1.38 with boost & 1 minute polling, plus weathermap, thold, monitor plugins.

My upgrade steps are as following:
1. remove poller from cron job before upgrade start.
2. copy cacti 1.2.16 to replace exiting cacti 1.1.38 files on master server only.
3. perform upgrade_database.php from cli (or gui makes no difference)
4. compile spine 1.2.16 put it in usr folder.
5. In cacti settings update path for to new spine1.2.16.
6. temporarily for the first runs disable plugins: thold, monitor, weathermap.
(until this step all devices and thold alarms are still present in cacti database an gui)
7. Put back poller to cron job.
___________________________________________________________________

After these steps within a few poller runs I have empty thold_data table, empty host and data_local tables.

I beg you for help. Thank you in advance!

**Comment by bmfmancini** [comment]
Can you post the results from the install log located in cactidir/log

What version of mariadb/MySQL

**Comment by TheWitness** [comment]
The question is "did you follow the updated recommended MySQL/MariaDB settings and restart before upgrading"?  That one bites a lot of people.

**Comment by TheWitness** [comment]
Secondly, per @bmfmancini, not nearly enough information to make any assessment.

**Comment by bmfmancini** [comment]
Yes good point!

**Comment by ikorzha** [comment]
Guys I highly appreciate expedited response.
I did follow recommended settings for DB. in initial upgrade screen all my "pre-upgrades" validations are green. Below is a DB information.
I also did restart DB prior to installation when all compliant settings were in..

[install-sync.log](https://github.com/Cacti/cacti/files/6136888/install-sync.log)
[install-complete.log](https://github.com/Cacti/cacti/files/6136889/install-complete.log)
[install-general.log](https://github.com/Cacti/cacti/files/6136890/install-general.log)
![DB info](https://user-images.githubusercontent.com/11211789/111072908-fdadc100-84b2-11eb-9fbd-22739e72cfbf.PNG)

**Comment by bmfmancini** [comment]
Did you apply these changes to all of the remote pollers?

**Comment by ikorzha** [comment]
I didn't apply any changes to remote pollers, only to master. My expectation (may be incorrect one) that they will sync in from master.

What are the steps for remote poller update:
Is it:
1. Copy 1.2.16 to replace my current 1.1.38
2. Compile spine to 1.2.16
Is there a documented steps somewhere for an upgrade you can point me to?

**Comment by bmfmancini** [comment]
The files will replicate but the database settings will not

The biggest one is large_prefix = 1 is set

**Comment by ikorzha** [comment]
Thank you for guidance I will make another attempt tonight and report back:
Here is what I will do different on pollers after I stop the cron job on master prior to upgrade:
1 Copy 1.2.16 to replace my current 1.1.38 in all pollers.
2. Update my my.cnf on each of the pollers with same settings as on master.
3. add "innodb-large-prefix=ON" on all servers master and pollers my.cnf
4. update compiled version of spine on all pollers.
5. start poller cron job on master and observe result.

Anything did I miss?

**Comment by bmfmancini** [comment]
Its a bit more that just that one variable what I would do Is copy all of
the dB setting recommendations to each server

Try this for each server and then tweak after

[mysqld]

# required for multiple language support
character-set-server = utf8mb4
collation-server = utf8mb4_unicode_ci

# Memory tunables - Cacti provides recommendations at upgrade time
max_heap_table_size = XXX
max_allowed_packet = 500M
tmp_table_size = XXX
join_buffer_size = XXX
sort_buffer_size = XXX

# important for compatibility
sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER

# innodb settings - Cacti provides recommendations at upgrade time
innodb_buffer_pool_instances = XXX
innodb_flush_log_at_trx_commit = 2
innodb_buffer_pool_size = XXX
innodb_sort_buffer_size = XXX
innodb_doublewrite = ON

# required
innodb_file_per_table = ON
innodb_file_format = Barracuda
innodb_large_prefix = 1

# not all version support
innodb_flush_log_at_timeout = 3

# for SSD's/NVMe
innodb_read_io_threads = 32
innodb_write_io_threads = 16
innodb_io_capacity = 10000
innodb_io_capacity_max = 20000
innodb_flush_method = O_DIRECT

**Comment by ikorzha** [comment]
Guys I just made an another attempt and it is failing too as out of 559 devices I only have 140 left and 30% have corrupted description.
Here is what happen. I have disabled the cron and pollers prior to upgrade. and updated my.cnf on all pollers
After upgrade I have first enabled 1 of the pollers and it was successful, it started populating data on master and that poller.
Than I sync and than enable another poller, that is when I got full "hosts" corruption and deletion, that poller report status heartbeat....
The other 2 pollers report "Unable to establish MySQL connection with Remote Data Collector." eventhough on 1.1.38 they were fully working. The only change is upgrade to 1.2.16

Looking for suggestions as I reached an impasse point.

![image](https://user-images.githubusercontent.com/11211789/111091375-1f399780-8509-11eb-8d94-0138c6de42fb.png)
in Master log:
![image](https://user-images.githubusercontent.com/11211789/111091523-9111e100-8509-11eb-81bd-75427e567f24.png)

**Comment by bmfmancini** [comment]
Very odd...
What version of mysql/mariadb are you using again?

Also what PHP version are you using?

**Comment by bmfmancini** [comment]
Also I'd like to. Work with you in this reach out to me on my email from
Github maybe we can do a google hangouts or something

**Comment by ikorzha** [comment]
I highly appreciate your offer. I would love to work with you on this issue as I have a large installation with multi pollers..
If you willing and have availability now, I can send you a microsoft teams meeting invite that has ability for audio, screen sharing and remote control to examine the issue

![image](https://user-images.githubusercontent.com/11211789/111092153-a6880a80-850b-11eb-9309-e486ab33aa90.png)

**Comment by ikorzha** [comment]
Sent you a teams meeting invite and waiting for you there. if you willing to join now, if not we can schedule it at a time that is convenient to you.

**Comment by bmfmancini** [comment]
Oh I see your problem
Update your PHP version I've seen this type of behaviour with older
versions of PHP and remote pollers on new versions of cacti alot of
functionality was built into the newer versions of cacti

**Comment by netniV** [comment]
Is this now resolved then?  I am going to close this as it's not a code issue, it's a configuration issue which should be directed to the forums for help.

**Comment by ikorzha** [comment]
Thank you guys for all your help. Sean was a tremendous help in identifying root cause..
