### ISSUE TITLE
Disable / minimize left Menu

### ISSUE THREAD

**Issue by DavidLiedke** [Cacti/cacti#417]
I had one user for a status monitor. This user has only access to one tree without any subtree. 

For this monitor i would nice if i can disable or minimize the left menu. 
I need a view like this:
![chrome_2017-03-13_14-53-19](https://cloud.githubusercontent.com/assets/25581728/23857295/1a6820ba-07fd-11e7-9f8f-ef204c119f3c.png)

Maybe as user setting or as a option in the url. 

For example:
/cacti/graph_view.php?action=tree&node=tbranch-241&hgd=&hyper=true`&menu=false`

or

![chrome_2017-03-13_14-57-36](https://cloud.githubusercontent.com/assets/25581728/23857538/f5b77878-07fd-11e7-9374-04a749415fff.png)

**Comment by cigamit** [comment]
Responsive trees are on our enhancement list.  Additionally responsive forms and other elements.  We are waiting at the moment on Bootstrap 4.0.

**Comment by cigamit** [comment]
Please review the responsive design in 1.1.3.  Should be sufficient.  Just click on the Graph icon a second time, and the tree will be hidden automatically.  Also, it hides automatically on smaller screens such as a mobile phone or tablet.

**Comment by DavidLiedke** [comment]
Yes this is good. It is possible to get this feature in the future as an option ?

**Comment by cigamit** [comment]
David,  Take a stab at a pull request.  Before it's merged, we can do a code review just to make sure you are following are coding standards.
