### ISSUE TITLE
Mouse Hover - New Graph Information

### ISSUE THREAD

**Issue by zuka1337** [Cacti/cacti#4170]
# Feature Request

## Is your feature request related to a problem? Please describe

Somethimes I have a Big Alias/Description  or any other property, and I have to create all graphs to find the one I realy need.

![image](https://user-images.githubusercontent.com/57998098/111155171-00c8b000-858c-11eb-962e-21daf509163b.png)

## Describe the solution you'd like

When Hovering the "property/Item" I would like to see the full text

## Describe alternatives you've considered

Show graph Info before creating ?

## Additional context

Something like this:

![hover](https://user-images.githubusercontent.com/57998098/111155927-0377d500-858d-11eb-8e46-086c5434572d.gif)

**Comment by netniV** [comment]
I'm slightly confused by this one because each table item, even if partially truncated, there is a tooltip displayed to show the full item value.  If you are instead asking for the ID column to show more status information like the monitor plugin does, can you be specific about what sections you feel would benefit from this and what information exactly should be shown.

**Comment by zuka1337** [comment]
Sorry, it is quite simple.
I would like to see the full content of the column, which could be hovering or in place.

In the example below "Alias(IF-MID)" I have 3 dots (C...), incomplete element.
Is there any way of expanding that column and I'd miss it?
Inspecting the span element I can see the full text/element of that column 

eg:
![span](https://user-images.githubusercontent.com/57998098/111499461-e2ed7d80-873a-11eb-8b7f-908f4647655c.png)


This happends for all columns, in this case does not apply to the others, the elements size are quite small.

**Comment by TheWitness** [comment]
Title Trim is clipping the ifAliases.

**Comment by TheWitness** [comment]
Okay, fixed.

**Comment by zuka1337** [comment]
Thank you !!!

**Comment by zuka1337** [comment]
Thats what I'm talking about!!
Thank you, Thank you !!

![hover_fixed](https://user-images.githubusercontent.com/57998098/111779987-b5c1dc00-88ae-11eb-92a0-d61491a77130.gif)
