### ISSUE TITLE
Cacti1.2.16 After a new user is created, the setting does not take effect when only one or more drawings are authorized to be accessed.

### ISSUE THREAD

**Issue by josun-33** [Cacti/cacti#4171]
# Describe the bug
Cacti1.2.16 After a new user is created, the setting does not take effect when only one or more drawings are authorized to be accessed.

## To Reproduce
When a new user' test' is created, and then only one or more drawings are authorized to be accessed, the setting does not take effect. How to solve it?

1.Open' Configuration' and click' Users' to create user' test'

2.Click ’graph perms’ to assign graph permissions to "‘test'", and click ‘Grant Access' to save without any prompt, and the authorized Graph Perms not take effect.

3.Log in with the new' test' and find that you can see all the added graphics, including aggregated graphics.

## Screenshots
![cacti](https://user-images.githubusercontent.com/80661333/111258989-f7842580-8615-11eb-9a23-9c57197d0d2c.png)

## Desktop (please complete the following information)
CentOS Linux release 7.4.1708 (Core)，PHP 7.1.33 (cli)，mysql5.7.30，nginx 1.18.0，rrdtool1.7.2，cacti1.2.16

Chrome 89.0.4389.90(64bit) ,firefox86.0.1 (64bit)

**Comment by TheWitness** [comment]
Though I'm not sure I completely understand what you are asking, cacti graph permissions are confusing to the beginner.  Read the documentation that is currently only I github about user graph permissions.  Then take raise this question on the forums first.

**Comment by josun-33** [comment]
Hi，Can you understand Chinese(是否能看懂中文).

**Comment by xmacan** [comment]
Your screenshot shows that you have default graph policy "Allow". You don't need do grant access because user has access to all graphs. 

You need to switch  default policy to deny and then you can grant access to one or more graphs. 

Then try to uncheck "Show all"

**Comment by josun-33** [comment]
Thank you，It has been solved. Only when' Graph Perms',' Device Perms' and' Template Perms' are set to' Reject' can they take effect.



 
From: Petr Macek
Date: 2021-03-17 15:22
To: Cacti/cacti
CC: josun-33; Author
Subject: Re: [Cacti/cacti] Cacti1.2.16 After a new user is created, the setting does not take effect when only one or more drawings are authorized to be accessed. (#4171)
Your screenshot shows that you have default graph policy "Allow". You don't need do grant access because user has access to all graphs.
You need to switch default policy to deny and then you can grant access to one or more graphs.
Then try to uncheck "Show all"
