### ISSUE TITLE
LDAP / Multiple AD - no template user

### ISSUE THREAD

**Issue by choefing** [Cacti/cacti#418]
Hi,

after the last changes for multiple LDAP / AD Domains https://github.com/Cacti/cacti/commit/2478b34219ec0eb713cc0929d34fea5937e0f876 it is not possible anymore to use a certain users (copy of guest) as a template. The user "guest" is neither tied to "local" nor any newly created domain. Once you copy the guest user,  you are forced to select the domain which makes it unusable as a template user.
Even just opening and saving the guest assigns the the "local" which renders it unusable as template user as well.

Thanks for all the effort.

**Comment by cigamit** [comment]
Resolved.  Thanks for reporting right away.

**Comment by choefing** [comment]
After git pull i just tried to copy the "guest" user and I still have no chance to select "NO" realm, as Realm comes preselected with "Local".
Nevertheless tried to use the newly created user as template user for "Multiple AD / LDAP" but it doesnt show up.

![grafik](https://cloud.githubusercontent.com/assets/26385419/23902317/0355181e-08c1-11e7-9926-e4db4e57783e.png)

![grafik](https://cloud.githubusercontent.com/assets/26385419/23902433/621e1198-08c1-11e7-8621-bdbd019f68e5.png)

Also doesnt work for single LDAP settings.
![grafik](https://cloud.githubusercontent.com/assets/26385419/23902452/751a3290-08c1-11e7-994b-3bd716739eb5.png)

**Comment by cigamit** [comment]
Fixed now.
