### ISSUE TITLE
When using 'basic' authentication, there should be no logoff link as it's not possible

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#4180]
# Describe the bug

When using SSO methods in Cacti with Basic Authentication, Cacti has not way to invalidate the session as it's controlled by the SSO provider, so there should not be a logoff link on the Cacti pages.

## Expected behavior

Less confusion user interface.

**Comment by netniV** [comment]
Actually, you can make Basic Auth sign out using a bit of javascript.  You clear the auth cache and that should do it.

```js
<script type="text/javascript">
function logout() {
    var xmlhttp;
    if (window.XMLHttpRequest) {
        xmlhttp = new XMLHttpRequest();

        xmlhttp.open("GET", '/ERROR/401', true, "logout", "logout");
        xmlhttp.send("");
        xmlhttp.onreadystatechange = function() {
            if (xmlhttp.readyState == 4) {window.location.href='/';}
        }
    } else if (window.ActiveXObject) { // code for IE
      xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");

      // IE clear HTTP Authentication
      document.execCommand("ClearAuthenticationCache");
      window.location.href='/where/to/redirect';
    }

    return false;
}
</script>
```

**Comment by TheWitness** [comment]
When using siteminder, your only choice is to have the siteminder logoff URL and redirect the client to that location. At that point I suspect that the client would be again redirected to the corporate signing page.
