### ISSUE TITLE
Cacti signal handling is not following best practices in PHP 7

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#4185]
# Describe the bug

Cacti signal handling has defined ticks = 1 for several years.  However, as of PHP7.1, there is a new best practice to use a new function, and Cacti is not following that best practice.

## Expected behavior

Cacti should follow best practices.

**Comment by netniV** [comment]
The function can be present but unusable if it is in the following list:

https://stackoverflow.com/questions/52791039/pcntl-async-signals-has-been-disabled-for-security-reasons-ubuntu-16-lara

```php
disable_functions = pcntl_alarm,pcntl_fork,pcntl_waitpid........
```
