### ISSUE TITLE
Navigating from Graph to Data Source combersome

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#4187]
# Describe the bug

When you are editing a Graph and wish to navigate to the Data Source(s), or editing Data Sources and wish to navigate to the Cacti Graph or Graphs it is very cumbersome.

## Expected behavior

Make Cacti easier to use.

**Comment by TheWitness** [comment]
This resolution provides a partial fix to https://github.com/Cacti/cacti/issues/4172

**Comment by bernisys** [comment]
That one is very helpful indeed, thanks for adding this! :)
