### ISSUE TITLE
There is no data in the graph of the 5-minute collection interval

### ISSUE THREAD

**Issue by zhangjian420** [Cacti/cacti#4191]
Centos7.4
Cacti 1.2.4
Crontab 1min  */1 * * * * apache sh /home/apache/run_poller.sh >> /home/apache/run_poller.out

 I have created 2800 graphs to collect the flow of the device. The data collection interval includes 5 minutes and 1 minute intervals. There are about 2600 5-minute interval graphs, and the others are 1-minute interval graphs。

If the graph created on the interface of a device is 5 minutes, the graph sometimes has no data. But after deleting the created 5-minute graph and re-creating the 1-minute interval graph, the data will appear at this time。And no errors appear in the logs window。

![1](https://user-images.githubusercontent.com/293321/112027149-e1281d80-8b71-11eb-9251-6a56c5b930bd.jpg)

Both graphs were collected in 5 minutes. And the interfaces of the device are all available。The first graph is collected correctly, and the second graph has no data。If I change the second graph to 1 minute acquisition, the data will be collected correctly。After collecting for a period of time, there may be no data in the first graph。
   
What is the cause of this?

**Comment by TheWitness** [comment]
Please take this one up on the forums.  This area is not for support requests but for bugs that have been first vetted on the forums.
