### ISSUE TITLE
filter_value() function does not work as expected when search includes # character

### ISSUE THREAD

**Issue by ikorzha** [Cacti/cacti#4195]
Cacti->Management->Devices search return blank description, ID & hostname if device name contain # character .

Using the Cacti version 1.2.17 (patched), with an updated monitor plugin 2.5 (development branch).
Broswer Crome incognito mode for testing.
This is a an extension to original bug #4192 that TheWitness has successfully patched yesterday..

Please see an updated behavior below:
![cacti-search-bug](https://user-images.githubusercontent.com/11211789/112225049-94d8ee00-8c02-11eb-9a74-a5b204ac73b7.gif)

**Comment by TheWitness** [comment]
The # character had a special use in the preg_match.  All fixed up now.

**Comment by ikorzha** [comment]
My apologies, I have tested a patched lib/functions.php and still getting an identical behavior to reported, is there a way you can test it yourself for validation?
![image](https://user-images.githubusercontent.com/11211789/112235544-41bc6680-8c15-11eb-8384-05d27460a0f8.png)

**Comment by TheWitness** [comment]
Works here:

![image](https://user-images.githubusercontent.com/1439914/112235694-89db8900-8c15-11eb-9085-6a46aaef92c0.png)

**Comment by ikorzha** [comment]
maybe because I pulled lib/functions.php into my 1.2.16 I do not to try to upgrade to development version.
If it works for you close it at this point..
