### ISSUE TITLE
Problem with graphs in details section

### ISSUE THREAD

**Issue by pionar** [Cacti/cacti#4196]
Hello,
I moved from 0.8 to the newest stable 1.2.16 version. All works good but in details in graphs I see this:

<img width="1231" alt="cacti" src="https://user-images.githubusercontent.com/1613006/112320879-bc39c480-8caf-11eb-9ae3-234eb3f7eb8f.png">

I've noticed that graphs with very short time period(one cycle of pooler) works. Also I've noticed when I use presets no matter 2,3 hours or days,weeks then it shows me always 1 day in date.

How to fix it? it is bug?

**Comment by bmfmancini** [comment]
Is the time on your server correct?
Is the rrdtool version matching what's installed vs what's in settings?

What is are you using?

**Comment by bmfmancini** [comment]
Check this from. The forums
https://forums.cacti.net/viewtopic.php?t=37786

**Comment by pionar** [comment]
Time is correct, RRDtool in debian system 1.7.2 , RRDtool Version in Cacti configuration "1.7.2+" .
Problem is only when I go into details graph. In all another tabs I see graphs correct.

**Comment by pionar** [comment]
I don't know it's related but from time to time I see in logs:

`
2021/03/24 14:36:22 - CMDPHP PHP ERROR NOTICE Backtrace:  (/graph.php[367]:CactiErrorHandler())
--
2021/03/24 14:36:22 - ERROR PHP NOTICE: Undefined index: id in file: /opt/cacti/graph.php  on line: 367
2021/03/24 14:36:22 - CMDPHP PHP ERROR NOTICE Backtrace:  (/graph.php[315]:CactiErrorHandler())
2021/03/24 14:36:22 - ERROR PHP NOTICE: Undefined index: steps in file: /opt/cacti/graph.php  on line: 315
2021/03/24 14:36:22 - CMDPHP PHP ERROR NOTICE Backtrace:  (/graph.php[300]:CactiErrorHandler())
2021/03/24 14:36:22 - ERROR PHP NOTICE: Undefined index: rows in file: /opt/cacti/graph.php  on line: 300
2021/03/24 14:36:22 - CMDPHP PHP ERROR NOTICE Backtrace:  (/graph.php[300]:CactiErrorHandler())
2021/03/24 14:36:22 - ERROR PHP NOTICE: Undefined index: step in file: /opt/cacti/graph.php  on line: 300
2021/03/24 14:36:22 - CMDPHP PHP ERROR NOTICE Backtrace:  (/graph.php[300]:CactiErrorHandler())
2021/03/24 14:36:22 - ERROR PHP NOTICE: Undefined index: steps in file: /opt/cacti/graph.php  on line: 300
2021/03/24 14:36:22 - CMDPHP PHP ERROR NOTICE Backtrace:  (/graph.php[298]:CactiErrorHandler())
2021/03/24 14:36:22 - ERROR PHP NOTICE: Trying to access array  offset on value of type null in file: /opt/cacti/graph.php  on line: 298
2021/03/24 14:36:22 - CMDPHP PHP ERROR NOTICE Backtrace:  (/graph.php[298]:CactiErrorHandler())
2021/03/24 14:36:22 - ERROR PHP NOTICE: Undefined offset: 0 in file: /opt/cacti/graph.php  on line: 298
`

**Comment by bmfmancini** [comment]
Interesting try pulling down the latest graph.php from Github on the 1.2.x
branch

**Comment by zuka1337** [comment]
Take a look here : [3797](https://github.com/Cacti/cacti/issues/3797)

**Comment by TheWitness** [comment]
@pionar, Any updates?

**Comment by pionar** [comment]
@zuka1337  related [3797](https://github.com/Cacti/cacti/issues/3797) I have cacti version 1.2.16 and there is no number but variable "FILTER_VALIDATE_MAX_DATE_AS_INT" . In my case I have problem only with graph when I go into details and date range is more then one cycle of pooler.
@bmfmancini I downloaded the newest graph.php from repo and errors with Undefined index still appearing

**Comment by bmfmancini** [comment]
What version of PHP are you using?

**Comment by pionar** [comment]
PHP 7.4.3

**Comment by pionar** [comment]
Interesting fact is that in graph details data section shows me everytime 1 day period. It doesn't concert period what I set one step before go into details(Presets).

**Comment by bmfmancini** [comment]
This is my view 

![image](https://user-images.githubusercontent.com/13388748/112512409-b7d1e200-8d69-11eb-89aa-dd0ff45fd80b.png)




PHP Version | 7.3.19-1~deb10u1
-- | --
PHP OS | Linux
PHP uname | Linux cacti-1 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64

**Comment by pionar** [comment]
How graphs in "Time graph view" are generated? Why I have blank page ?

<img width="1220" alt="graphs" src="https://user-images.githubusercontent.com/1613006/112600616-b9ef7b80-8e11-11eb-9ca3-d6e79d499448.png">

**Comment by zuka1337** [comment]
Do you have any console errors?
Does this happen in different browsers?

**Comment by pionar** [comment]
Yes, Does this happen in different browsers with cleared browser cache(checked chrome and firefox).
What do you mean console errors? All errors what I noticed I past in this topic.

**Comment by zuka1337** [comment]
This

![error](https://user-images.githubusercontent.com/57998098/112621881-2f634800-8e22-11eb-879e-4bdea061d0c8.gif)

**Comment by pionar** [comment]
No errors,

In network tab I see:
 `graph.php?local_graph_id=137&header=false`

**Comment by TheWitness** [comment]
Please take this discussion to the forums.  If by your discussion there, you discover something tangible, open a new bug citing specifically the error.
