### ISSUE TITLE
SQL Save on table 'host': Column 'thold_send_email' does not exist, unable to save!

### ISSUE THREAD

**Issue by ikorzha** [Cacti/cacti#4200]
Cacti team I have hit an interesting serious bug after new poller is built and joins the master server.
Steps: (Performed on Cacti 1.2.16)
1. Build a new polller CenOS or Ubuntu (makes no difference), import default cacti.sql and give permissions in DB to master and poller to cacti DB...
2. Poller shows up in Cacti Master poller, proper host name and name assigned. 
3. Full poller replication is performed.
4.  A single host is assigned to poller.
5. Host does get successfully transitioned to new Cacti poller but, graphs on master never updates and host status always shows unknown,
6. Eventually when cacti master attempt replication msgs on log below start popping up every minute (that is on poller).
Master also complaints during replication to new poller that table cacti.host doesnt exist.
7. 
![image](https://user-images.githubusercontent.com/11211789/112722666-4321b380-8ee1-11eb-9ae0-c42da46fd3b8.png)
8. Any attempt to move a host for polling now to a new poller results in:
![image](https://user-images.githubusercontent.com/11211789/112722762-b4616680-8ee1-11eb-8259-5ba316fbe44d.png)

Feels like thold (my version is latest 1.5.3) is causing it, but I am not in position to uninstall and reinstall since I have 31K thold configured.

I have 2 new pollers 1 on CentOS the other is on Ubuntu both newly built and rebuilt and every time identical results.
I feel like replicating a working Cacti DB from 1 of the working pollers to solve this issue.. But wanted to see if development team feels there is more to it...

**Comment by bmfmancini** [comment]
Is this happening on a device assigned to a remote poller?

If it is sync that poller with the main poller I've seen this before and
that worked in my case

**Comment by ikorzha** [comment]
Yes it is happing to a device assigned to a newly built poller. Reassigning the device to a "working poller" and issue disappears.
SYNC to a main poller has been tried and doesn't resolve the problem..
In fact even though there is a host assigned to it, poller log shows NO host, just datasource...

2021/03/27 14:52:08 - SYSTEM STATS: Time:0.7086 Method:spine Processes:2 Threads:4 Hosts:0 HostsPerProcess:0 DataSources:1 RRDsProcessed:0
![image](https://user-images.githubusercontent.com/11211789/112724661-d3b0c180-8eea-11eb-9611-5ee640760c05.png)

**Comment by TheWitness** [comment]
You need to do a Full Sync after the new poller is created.  The new pollers do not know about things like the thold columns.

**Comment by ikorzha** [comment]
The Witness, that is true, Full SYNC was performed as soon as poller comes online first time... However even after full sync and when new host assigned to poller after full sync, it polls but doesn't report back results to master. Host status always stays unknown on master and graph never gets created. An than may be an hour later or I suspect when master does 2 hourly sync up , host table gets deleted from new poller.
That is behavior I been observing on multiple tries.
If you believe there is no bug issue in cacti, my only option is to take a copy of working DB from working poller, and drop it on non working new poller and observe if that fixes the issue.

**Comment by ikorzha** [comment]
Closing issue as problem kinda fixed via uploading empty host table from a working poller.
