### ISSUE TITLE
On full sync Master server erases poller table on remote poller

### ISSUE THREAD

**Issue by ikorzha** [Cacti/cacti#4201]
Cacti team weird problem: Cacti 1.2.16, Mysql 5.7 newly deployed remote poller upon Full SYNC, master server erases poller table on remote poller.
In master server log:
CMDPHP ERROR: A DB Exec Failed!, Error: Incorrect datetime value: '0000-00-00 00:00:00' for column 'last_sync' at row 1
CMDPHP ERROR: A DB Exec Failed!, Error: Incorrect datetime value: '0000-00-00 00:00:00' for column 'status_fail_date' at row 1
Once it happens poller stops polling any devices assigned to it.
Example below is transition after full sync, it retains data sources but device count is 0, however in "data collectors" devices assigned still show as 1 :

2021/03/27 22:48:07 - SYSTEM STATS: Time:0.4901 Method:spine Processes:10 Threads:15 Hosts:0 HostsPerProcess:0 DataSources:7 RRDsProcessed:0
--
2021/03/27 22:47:17 - SYSTEM STATS: Time:8.8234 Method:spine Processes:10 Threads:15 Hosts:1 HostsPerProcess:1 DataSources:7 RRDsProcessed:0

I spent countless hours troubleshooting, even copied DB from a working poller with 0 hosts. Table gets cleaned on first SYNC.

Please provide your input how this problem can be solved as I exhausted all of the possibilities.
Errors during poller full SYNC: 

![image](https://user-images.githubusercontent.com/11211789/112741248-135ec400-8f52-11eb-873d-97beb0400ca9.png)

**Comment by TheWitness** [comment]
What is the SQL_MODE setting on remote poller?

**Comment by ikorzha** [comment]
TheWitness, I can't thank you enough for your help. It took you literally 3 words to fix a problem I been strangling for a few days now with new pollers. Of course it was set to traditional.
And of course I didn't have: sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER  in the my.cnf file.
Let it be a lesson for others.
I feel embarrassed at the end, thank you!

**Comment by TheWitness** [comment]
Well, if you have a backup of the my.cnf, I'd like to see the SQL_MODE before you made the change.

**Comment by ikorzha** [comment]
Here is the answer for you. Before I made a change no sql_mode was defined at all in my.cnf.
However before I made a change to my.cnf I ran a query on SQL mode on non working poller.
Results are below.

mysql> SELECT @@sql_mode;
+-------------------------------------------------------------------------------------------------------------------------------------------+
| @@sql_mode                                                                                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------+
| ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+-------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql>
