### ISSUE TITLE
Editing State=Down device - mark online when editing device when responding by all required probes

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#4202]
# Feature Request
A little improvement - when we are editing device that was marked by last pool as "down" ... and now the device is responding with all the required probes (for example with SNMP & Ping) - please mark the device up and not wait for next pool.

## Is your feature request related to a problem? Please describe
Sometime we have to do some unexpected maintance/repairing - after that we would like to mark device up as soon as possible - because we don't want to engage many people with this alert.

**Comment by interduo** [comment]
Sorry, I've got no resources to do that now :(

**Comment by TheWitness** [comment]
This has been resolved in the develop branch.
