### ISSUE TITLE
Tabs are missing on the RHS of the graph

### ISSUE THREAD

**Issue by jsmalisa** [Cacti/cacti#4203]
Can someone kindly assist me on this?

Did I miss something?

![image](https://user-images.githubusercontent.com/53674811/112806088-bf6eef00-90b9-11eb-9e7f-132bc8945639.png)

**Comment by xmacan** [comment]
https://forums.cacti.net/viewtopic.php?p=285599#p285599

**Comment by jsmalisa** [comment]
Petr,

Thanks so much. You are the best!

Appreciate your help.

[image: image.png]

**Comment by netniV** [comment]
This was a feature introduce and then it had had its functionality inverted because it was hiding them by default. There is a GitHub issue tracker for it if you search.

**Comment by jsmalisa** [comment]
Thanks, I'll check it out.
