### ISSUE TITLE
Configured report's time changes when a report was delayed

### ISSUE THREAD

**Issue by bernisys** [Cacti/cacti#4206]
# Describe the bug

Not sure if this is a bug or more a feature request. But we've seen this several times in the past:
When cacti fails to generate a report at its specific time, it will be generated later, but also the time is adapted.
This should not happen, as some reports might be expected at specific predefined times, but we see that from time to time, when cacti had a hicc-up and generates the report after its specified time.

It is good that it sends out delayed reports, no question here, but the times should be kept intact.

## To Reproduce

1. create a daily report to be sent within specific time of the day (for simulation, choose a time in near future)
2. stop cacti for a while (simulating a temporary outage, that crosses the defined report time)
3. restart cacti processing, wait for the delayed report to be generated
4. check the report time again & compare with previous setting

## Expected behavior

Report time should stay as previously configured.

**Comment by TheWitness** [comment]
Okay, I audited this function and I'm pretty sure I found the issue.  The function itself was trying, in a bad way to normalize the mailtime, when it should just increase it as applicable.  Please test wit h the latest lib/reports.php.

**Comment by TheWitness** [comment]
Confirmed working as expected now in my testing.

**Comment by bernisys** [comment]
Hmm i think you annotated the wrong issue when fixing it ... 
/lib/reports.php has a closed bug #4205 but this bug is #4206
in the changelog you correctly listed 4206

easter stress i assume :)

**Comment by TheWitness** [comment]
Working too late or too early.  Also, I think I need glasses.

**Comment by bernisys** [comment]
Get a glass of your favorite then - cheers!
