### ISSUE TITLE
add possibility to reset polling time statistics for pollers and devices

### ISSUE THREAD

**Issue by bernisys** [Cacti/cacti#4207]
# Feature Request

## Is your feature request related to a problem? Please describe

We had improved several SNMP parameters or the run time of some poller scripts that were used for a lot of metrics. This decreased the polling time a lot, but this was never reflected in the time statistics, so they stay always at the maximum time, even if that time is obsolete after the performance improvement.

## Describe the solution you'd like

A possibility to reset all min/avg/max stats for all pollers and devices globally.
Maybe also for an individual poller and for all devices attached to it.

if possible, values should be reset to:  min=0, avg=current, max=current
if not possible: 0/0/0 is fine too, as it will be populated within the next polling cycle anyway, and there's no hurry actually

## Describe alternatives you've considered

Clearing the metrics in the DB works, but my expectations are that this would be possible in the GUI.

**Comment by bmfmancini** [comment]
@bernisys this is available in 1.2.17
