### ISSUE TITLE
Replace c3.js with billboard.js

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#4210]
# Feature Request

## Is your feature request related to a problem? Please describe

Due to c3 falling so far behind on merging activities, we will drop c3.js and put in it's place billboard.js which is an active fork of c3.  This will be a part of the Cacti 1.2.17 release.

**Comment by TheWitness** [comment]
@paulgevers, @mortenstevens, @DavidLiedke FYI on this.  We are ready to release, just wanting to inform you of this change which will impact packaging to a certain extent.  We made this change due to several issues we were seeing with c3.js in the freshly minted Intropage plugin using the c3 library.

**Comment by jdcoats** [comment]
@TheWitness is this related?
```
2021/04/05 20:23:34 - ERROR PHP WARNING: md5_file(/var/www/localhost/htdocs/cacti/lib/../include/themes/TMH/billboard.css): failed to open stream: No such file or directory in file: /var/www/localhost/htdocs/cacti/lib/functions.php  on line: 5637
```

**Comment by TheWitness** [comment]
Yea, copy that file from one of the other themes.
