### ISSUE TITLE
wrong placed apostroph in inc/html.php for Content-Policy-Security

### ISSUE THREAD

**Issue by thomasbuesser** [Cacti/cacti#4211]
Hi Cacti-Folks

i found a missplaced apostrophe in the file lib/html.php for the Content-Policy-Security Option

`
        <meta http-equiv="Content-Security-Policy" content="default-src *; img-src 'self' <?php print $alternates;?> data: blob:; style-src 'self' 'unsafe-inlin
e' <?php print $alternates;?>; script-src 'self' <?php print $script_policy;?> 'unsafe-inline' **-->'<--** <?php print $alternates;?>; worker-src 'self'"> 
`

if this apostroph is there, Content-Security Alternate Sources are ignored (tested with version 1.2.16)

BRs
 Thomas

**Comment by cigamit** [comment]
Seems to already be resolved in 1.2.X branch

**Comment by thomasbuesser** [comment]
in which version (1.2.16 seems to be the last stable release)?

**Comment by thomasbuesser** [comment]
can be closed
