### ISSUE TITLE
new cacti - 95th percentline values wrong

### ISSUE THREAD

**Issue by DmitriyFreez** [Cacti/cacti#4212]
Good day. We have old version which use at production.
Cacti version 0.8.8h
CentOS Linux release 7.9.2009 (Core). PHP 5.6.40. Apache/2.4.6. mysql Ver 15.1 Distrib 5.5.68-MariaDB

Graph Template :
![old-1](https://user-images.githubusercontent.com/82030718/113698359-10479e80-96dd-11eb-9a13-147f245d5bc2.jpg)

created graph and datasource according to this template
![old-1-1](https://user-images.githubusercontent.com/82030718/113698564-438a2d80-96dd-11eb-8053-ed4a57f5450f.jpg)
![old-1-2](https://user-images.githubusercontent.com/82030718/113698571-4422c400-96dd-11eb-8bdd-39237ceeb9e9.jpg)

finaly correct graph, with adequate, similar to be right values:
![old-2](https://user-images.githubusercontent.com/82030718/113698628-500e8600-96dd-11eb-9bb7-915b786941f9.jpg)

---------------------
Now we have installed new version.
Cacti Version 1.2.16
Debian 10.8. PHP 5.6.40-41+0~20210213.47+debian10~1.gbp6fd845 / nginx 1.14.2 . mysql Ver 15.1 Distrib 10.3.27-MariaDB

![new-1](https://user-images.githubusercontent.com/82030718/113698730-6b799100-96dd-11eb-8cf0-a31c1c2ee4e0.jpg)

![new-1-1](https://user-images.githubusercontent.com/82030718/113698734-6caabe00-96dd-11eb-8a47-1237b7ec0eb5.jpg)

![new-1-2](https://user-images.githubusercontent.com/82030718/113698738-6d435480-96dd-11eb-9068-373ddd073aeb.jpg)

![new-2](https://user-images.githubusercontent.com/82030718/113698823-86e49c00-96dd-11eb-9210-3a38a2705dba.jpg)

As you can see we have same template and identical initial data to calculete 95th percentline, but the values we got at new cacti is wrong.
With any other intrface-graph-data source, the same situation with 95th values.
Please let me know if you need additional data on this issue.

**Comment by TheWitness** [comment]
Switch from max to current in the variables and the numbers will match.  There was a change in behavior where max uses the max of the MAX consolidation function instead of the max of the AVERAGE consolidation function.

**Comment by DmitriyFreez** [comment]
thanks for your advice, it helped

**Comment by gaoyan-cn** [comment]
> thanks for your advice, it helped

Has it been solved? What configurations have been modified?

**Comment by TheWitness** [comment]
There is  really no issue.  There was a behavior change.  In the past, max would pull the max value from the average consolidation function and now max will pull the max from the max consolidation function.  If you want the old values switch from `max` to `current`.
