### ISSUE TITLE
1.2.17 - latest - "Support Authentication Cookies" didn't work

### ISSUE THREAD

**Issue by anarkia1976** [Cacti/cacti#4214]
Hi @TheWitness ,

unfortunately "Support Authentication Cookies " since it was introduced new feature "Auto Log Out Time" would not seem to work.

The user is logged out after 15/20 minutes of inactivity.

Thanks a lot.

**Comment by TheWitness** [comment]
Thanks for reporting.

**Comment by TheWitness** [comment]
Okay, fixed now.
