### ISSUE TITLE
LDAP authentication issues (related to realm selection)

### ISSUE THREAD

**Issue by Yannis100** [Cacti/cacti#422]
After upgrading to 1.0.5, i'm unable to connect with LDAP

![image](https://cloud.githubusercontent.com/assets/3008631/23895621/aaeb536a-08a6-11e7-963d-a7b8155f2006.png)
![image](https://cloud.githubusercontent.com/assets/3008631/23895627/b2bb2e3a-08a6-11e7-8ee7-51c397bff91c.png)

I tried the 3 invisible options (which changed the field realm to 1, 3, 2 in user_auth table) without success

**Comment by Yannis100** [comment]
And same error as #421 when accessing user settings page

**Comment by choefing** [comment]
AFAIK this issue is fixed with latest pull from git but still not working as its intended.
#418 is already closed. Please see my comment at 
https://github.com/Cacti/cacti/issues/418
as well, as its related (and unfortunately not fixed)

Thanks.

**Comment by cigamit** [comment]
This is resolved.  We will be releasing 1.0.6 tonight.

**Comment by Yannis100** [comment]
Thanks, I've upgrade to 1.0.6
The form field is now ok, unfortunately, even after changing user realm to LDAP, I'm unable to login with my AD account
![image](https://cloud.githubusercontent.com/assets/3008631/23940308/ae1a3362-0964-11e7-9631-9fdf6e6adabe.png)

**Comment by cigamit** [comment]
Disappointing.  Though I'm in a pickle at the moment with ldap.  I'll have another commit shortly.

**Comment by cigamit** [comment]
Okay, fix is committed.

**Comment by cigamit** [comment]
Reported by another user this is fixed now.
