### ISSUE TITLE
Issue with lenght of poller output.

### ISSUE THREAD

**Issue by lotke** [Cacti/cacti#4238]
In old cacti releases output field in poller_output table was text, now it is varchar(512).
Because of that you will get weird issues, like realtime graphs work and some normal graphs do not.

I guess we should raise that output varchar(512) to varchar(2048) which is default result buffer size in spine ?
It should probably be raised in table poller_output_boost ?

**Comment by TheWitness** [comment]
There is a debug setting you can enable to assess your poller output length.  Just turn it on and modify your table widths as required and then run it off again.  In general we advise against having scripts with a wide length due to database size requirement when using memory tables.
