### ISSUE TITLE
Autom8 does not discover devices w/o resolveable hostname

### ISSUE THREAD

**Issue by choefing** [Cacti/cacti#424]
When specifing a network including devices w/o resolvable hostname they don't get discovered properly.

In the list of discovered devices it only shows "SNMP DOWN - Status up". All devices will show up as e.g. 11.22.33.44.in-addr.arpa and it seems they don't get snmp queried if no DNS is available.
Checked with a ip --> name match in /etc/hosts will immediately show the proper values retrieved by snmp and "SNMP UP - STATUS UP". So it seems the checks autom8 does is related to some kind of a name resolve.

w/o resolvable name - 0 Responded to SNMP
`2017-03-13 14:12:53 - AUTOM8 Network CMMN Thread 3 Finished, 1 IPs Scanned, 1 IPs Responded to Ping, 0 Responded to SNMP, 0 Device Added, 0 Graphs Added to Cacti `
`2017-03-13 14:12:53 - CMDPHP PHP ERROR WARNING Backtrace: (/poller_automation.php: 318 discoverDevices)(/poller_automation.php: 467 automation_valid_snmp_device)(/lib/api_automation.php: 3051 cacti_snmp_session)(/lib/snmp.php: 52 __construct)(CactiErrorHandler)(/lib/functions.php: 4260 cacti_debug_backtrace)`
`2017-03-13 14:12:53 - ERROR PHP WARNING: SNMP::__construct(): php_network_getaddresses: getaddrinfo failed: No address associated with hostname in file: /var/www/html/cacti/lib/snmp.php on line: 52 `

w/ resovleable name (in /etc/host) - 1 IPs Responded to Ping
` 2017-03-13 14:18:09 - AUTOM8 Network CMMN Thread 1 Finished, 1 IPs Scanned, 1 IPs Responded to Ping, 1 Responded to SNMP, 0 Device Added, 0 Graphs Added to Cacti `

Nevertheless, whenever I set the snmp community to a single correct value (in SNMP Options Set" and add the discovered devices, it will automatically set the hostname to the hostname retrieved via SNMP which is quite what we want.

If I add another snmp community for another kind of device / another network, then when adding the device will always get the last snmp community string in the list.
So devices with "community1" will fail to be added properly with name, while devices with "community2" would be added correctly using snmp retrieved host name.

**Comment by cigamit** [comment]
Should be resolved now.  Please test.  If we release 1.0.7 before you can confirm, and it's not fully working.  Please open a fresh ticket.

**Comment by choefing** [comment]
Tested with 1.1.0 confirmed resolved.
Thanks a lot.
