### ISSUE TITLE
Permission "Hide Graph Drilldowns" functions inverse of all other permissions. 

### ISSUE THREAD

**Issue by sep76** [Cacti/cacti#4240]
When you enable all permissions for a user. you actually hide all drill-down icons on graphs. 

## To Reproduce

1. Go to Configurations - > users -> permissions tab

2. Click on the checkbot to enable all persmissions and save

3. Go to any graph on the tree

4. See drilldown icons missing. 

## Expected behavior

All permissions, should give most features. that one option function inverse of the other is counter intuitive. 
Perhaps change it  to "Show Graph Drilldowns" and make it function as an activation.

## Screenshots
![image](https://user-images.githubusercontent.com/20247522/115624200-95949b00-a2fa-11eb-9ceb-2a7bba8b99da.png)

**Comment by TheWitness** [comment]
This is already resolved in the upcoming 1.2.17 release.
