### ISSUE TITLE
Tag 1.2.17?

### ISSUE THREAD

**Issue by tersmitten** [Cacti/cacti#4242]
# Feature Request

I'm not sure if something is blocking it, but would you be so kind to tag a new `1.2.x` release?

Thanks in advance

**Comment by TheWitness** [comment]
I think @netniV will be doing it either this or next weekend.

**Comment by netniV** [comment]
That would be next weekends job. Some prep work to do this week for it.

**Comment by netniV** [comment]
This is now released.
