### ISSUE TITLE
question of permission

### ISSUE THREAD

**Issue by tyf0628** [Cacti/cacti#4244]
how to set this permission for user ？only admin have this permission？
![image](https://user-images.githubusercontent.com/24688746/116066404-9e9ab900-a6ba-11eb-8402-ce2278e39b51.png)
![image](https://user-images.githubusercontent.com/24688746/116066456-abb7a800-a6ba-11eb-96c1-d96494a99545.png)

**Comment by cigamit** [comment]
Console > Configuration > Users > Click username > Permissions > Show Graph Action Icons
![image](https://user-images.githubusercontent.com/957322/116089854-e0027880-a668-11eb-8fa3-24bf90e89f7c.png)

**Comment by xmacan** [comment]
@cigamit - question  "only admin have this permission?" isn't that simple. These icons can contain "eye icon" for intropage favourite graphs and more. Is it more about security or design/space saving? it would be better for me move this to user profile settings.

**Comment by tyf0628** [comment]
but I can not find this option in  Version 1.2.16
![aa](https://user-images.githubusercontent.com/24688746/116109025-049d3580-a6e7-11eb-974c-c531cfb3a396.jpg)
![bb](https://user-images.githubusercontent.com/24688746/116109045-07982600-a6e7-11eb-88f3-0be20d0f0d2e.jpg)

**Comment by zuka1337** [comment]
Hide Graph Drilldowns.

@cigamit what theme are you using? It looks very clean and modern

**Comment by xmacan** [comment]
@zuka1337 it is modern theme. In your screenshot it is Hide graph Drilldowns. It was renamed in 1.2.17

**Comment by browniebraun** [comment]
I believe he meant the dark Midwinter theme introduced in 1.2.17.

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by netniV** [comment]
The option was renamed and inverted to keep in line with all other settings (see the CHANGELOG for more info)
