### ISSUE TITLE
Change the order of the device_remove hook

### ISSUE THREAD

**Issue by arno-st** [Cacti/cacti#4245]
When you delete a device, the device is actually removed and then the call is made to other hook who respond to device_remove registration.

It will be more usefuel to call the hook, before the device is actually removed, so the plugin can use other value than just the ID to do some action.

And beside the call with ID is useless since it point to nohting than can be significant.

**Comment by TheWitness** [comment]
I thought this was already fixed.

**Comment by TheWitness** [comment]
Yea, this is already fixed in the 1.2.x branch.  Don't remember specifically when it was fixed.
