### ISSUE TITLE
After updating cacti from 1.2.16 to 1.2.17 buttons next to the graph disappeared

### ISSUE THREAD

**Issue by Lejooohn** [Cacti/cacti#4248]
# Describe the bug

After updating cacti from 1.2.16 to 1.2.17 buttons next to the graphs disappeared (like the button to show real time graph)

## To Reproduce

Upgrade 1.2.16 to 1.2.17

## Expected behavior

I have to be able to see and use the buttons next to the graph to see a real time graph for example. See the graph below : 

![68747470733a2f2f692e6962622e636f2f774e44443353432f67726166696b2e706e67](https://user-images.githubusercontent.com/47657060/117114886-ab8b6c80-ad8c-11eb-98b3-f261fc5b0543.png)

## Screenshots with the issue

![Screenshot_1](https://user-images.githubusercontent.com/47657060/117114635-66ffd100-ad8c-11eb-8f6d-8e85127e02e4.jpg)

## Desktop (please complete the following information)

- OS:  Windows 10

- Browser : Tested on Firefox and Google Chrome

- Version : 88.0 and 90.0.4430.93 

Other technical information : 

Cacti run on CentOS  7.9.2009 up to date with httpd 5.4.6-97 and php 7.2.20

Cacti Version | 1.2.17
RRDtool Version Configured | 1.7.2+
RRDtool Version Found | 1.7.2
Type | SPINE 1.2.17  Copyright 2004-2021 by The Cacti Group

Thanks for you help ! :D

**Comment by bernisys** [comment]
Just upgraded to 1.2.17 in test environment and we can confirm the same behavior here .
No interaction icons shown on the right side of the graphs in the graph previews page.

**Comment by bmfmancini** [comment]
Noticed the same thing
Fixed it check permissions you will see show graph icons is not checked

**Comment by Lejooohn** [comment]
Hello @bmfmancini 

Sorry but i dont find any "permissions" to correct this issue.

Can you explain a bit more how to resolv it?

Regards

**Comment by xmacan** [comment]
https://forums.cacti.net/viewtopic.php?f=2&t=61607

**Comment by Lejooohn** [comment]
> https://forums.cacti.net/viewtopic.php?f=2&t=61607

Oh great ! Thanks you @xmacan 👍

**Comment by bernisys** [comment]
Thanks a lot, that really did the trick. Thanks @bmfmancini and @xmacan for the explanations!

Easy to fix, but harder to realize in the first place, specifically when you just setup your permissions once and keep them like that. ;)

Maybe this should be part of the upgrade routine, if there are any new permissions, they should be listed and asked for a default value? Or if the previous behavior was to actually show a specific part, this should be enabled by default ...

**Comment by netniV** [comment]
This is unfortunately due to a third party pull request that inverted the normal flow of permissions.  I thought that we had put something in place to flip this as part of the upgrade, but that appears to have been missed during our tests so I do apologise for that.

Fortunately, the fix isn't hard once you know what you are looking for, and in a way helps you realise there is this new option :)

I'm going to close the issue tracker for now since it has been resolved.
