### ISSUE TITLE
Support crypto Donations

### ISSUE THREAD

**Issue by zuka1337** [Cacti/cacti#4253]
Hello guys,

Can you add cryptos ways of donating for the project?
Main ones, BTC, ETH

I have some fractions of ETH and I would like to donate :D

**Comment by netniV** [comment]
I'm going to change this from an enhancement to a question.  

The answer to the question is that currently we don't have a method to accept those currencies directly. However, I have raised it internally within the group so it may become possible at some point in the future though we have no plans or guidelines on if or when that will be.
