### ISSUE TITLE
When poller first runs, time since last run produces an error

### ISSUE THREAD

**Issue by jmrcpn** [Cacti/cacti#4254]
# Describe the bug

poller.php line 328
Variable poller_seconds_sincerun is set incorrectly to 'never' and  "round" function
complain about it,
php report  then report poller  "crash"
Caution, this show-up using php-8.0.5

Problem locally fixed with fix
poller_seconds_sincerun = '0';

## To Reproduce

Problem show up only on a brand new installation
(poller_lastrun not set)
## Expected behavior

Graph display updated with "fresh" data.

**Comment by netniV** [comment]
I would recommend you update your code to use the above patch.  The reason for text string is to make it clear that there was no previous runtime available.  Thanks for report it.

**Comment by jmrcpn** [comment]
1) I perfectly understood "never" was intended to mark ' no previous runtime available'
2) round function is complaining/crashing about it (when no previous runtime available)
3) this part of cacti code is 6 year old and never got trouble about it, but now with php-8 "round" fonction is
complaining
4) I am using 1.2.16, poller.php code is still the same within 1.2.17
5) Sorry, But whereis the "above patch", what am I missing here?
