### ISSUE TITLE
[1.2.17] the right icons next to the graphs are missing after update

### ISSUE THREAD

**Issue by DavidLiedke** [Cacti/cacti#4255]
# Describe the bug

After the update from version 1.2.15 to 1.2.17 the right icons next to the graphs are missing.

Tested with classic and modern theme.

Maybe #4179 ?

## Screenshots

![TeamViewer_Pv4QVDvxXJ](https://user-images.githubusercontent.com/25581728/117637409-0f91a480-b182-11eb-82bb-ff60d1327909.png)

## Desktop (please complete the following information)

- OS: Windows 10

- Browser Firefox

- Version 88

**Comment by zuka1337** [comment]
Enable the icons on settings

**Comment by DavidLiedke** [comment]
Thanks @zuka1337 & @xmacan
