### ISSUE TITLE
Bug to display information in the chart 

### ISSUE THREAD

**Issue by DFlexy** [Cacti/cacti#4262]
Hello good morning I have a bug that I have done everything and I did not find the solution
CACTI VERSION: Version 1.2.12
Remembering that I changed the file graph_variables.php for the version 17 file to fix a bug

Edited Graph Template to present 95% in and out
it's working well in the graphics however when i create an AGGREGATE using the same template some information is missing

Template here
![image](https://user-images.githubusercontent.com/50220928/118271569-d6b24200-b497-11eb-9c91-12d146382af8.png)

Aggregate Template here
![image](https://user-images.githubusercontent.com/50220928/118271798-242eaf00-b498-11eb-83f4-093ae0b74084.png)

Normal grafic here (OK)
![image](https://user-images.githubusercontent.com/50220928/118272226-adde7c80-b498-11eb-8fd0-f86c8c249050.png)

BUG here with AGREGATE (BUG)
![image](https://user-images.githubusercontent.com/50220928/118272182-9acbac80-b498-11eb-87ad-120e01b770df.png)

**Comment by netniV** [comment]
Have you checked the RRDTool debug info against the graph to see if those lines are being placed onto the graph but maybe overwritten?

**Comment by DFlexy** [comment]
> Have you checked the RRDTool debug info against the graph to see if those lines are being placed onto the graph but maybe overwritten?

LINE1:cdefcdg#00CF00FF:'Total         '  \
AREA:cdefcdg#00CF007F:'Total Inbound '  \
GPRINT:cdefcdg:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefcdg:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdefcdg:MAX:'Maximum\:%8.2lf %s\n'  \
LINE1:cdefceb#002A97FF:'Total         '  \
AREA:cdefceb#002A977F:'Total Outbound'  \
GPRINT:cdefceb:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefceb:AVERAGE:'Average\:%8.2lf %s\n'  \
COMMENT:' \n'  \
HRULE:799528891809.5#000000FF:'95th Percentile Inbound -> ' \
COMMENT:'(799528.89 mbit)\n' 
RRDtool Command lengths = 37901 charaters.
RRDtool Says:
OK

**Comment by netniV** [comment]
So it looks like it's not even a graph item at this point.  It may be related to another bug with aggregates that I saw related #4264 / #4265

**Comment by DFlexy** [comment]
Good afternoon;
I executed the change of the 2 lines according to the document but the problem still persists

https://github.com/Cacti/cacti/commit/c5b8e5838e1ee23ea15ded8e5e838a76145a8065
