### ISSUE TITLE
Graphs with multiple data sources can no longer display percenticles

### ISSUE THREAD

**Issue by KrisShannon** [Cacti/cacti#4263]
# Describe the bug

The fix for #3340 (621091f7a6bdcf73fc4248d7d16d14c7e655fd5f) added an early return when encountering a NaN data source.

This has stopped percentiles working on graphs with multiple data sources.

## To Reproduce

1. Create two data sources,  one with data and the other with NaN's
2. Create a graph using `aggregate_current` percentiles (e.g.`|95:bits:0:aggregate_current:2|`) across the two data sources.
3. View the graph
4. Percentiles are shown as 0

## Expected behavior

Percentile calculation should ignore the NaN data source(s) and be based on any remaining sources with data.

## Additional context

I've locally removed the [early return](https://github.com/Cacti/cacti/blob/release/1.2.17/lib/graph_variables.php#L185-L186) from `nth_percentile_fetch_statistics` and the graphs appear to be working correctly:
```diff
--- lib/graph_variables.php
+++ lib/graph_variables.php
@@ -182,8 +182,6 @@ function nth_percentile_fetch_statistics($percentile, &$local_data_ids, &$fetch_array, $cf) {
 							$asum_array[$ds_name][$timestamp]  = $data;
 						}
 					}
-				} else {
-					return false;
 				}
 			}
 		}
```

**Comment by TheWitness** [comment]
Thanks for your contribution on this.

**Comment by DFlexy** [comment]
Guys sorry for reply here more i try fix and dont work need help

**Comment by TheWitness** [comment]
Sorry, was on sabbatical.
