### ISSUE TITLE
Aggregate current percentile's on multiple data source names not working

### ISSUE THREAD

**Issue by KrisShannon** [Cacti/cacti#4264]
# Describe the bug

When including `aggregate_current` percentiles for multiple data source names (e.g. `traffic_in` and `traffic_out`) the caching is causing both percentiles to be rendered as whichever data source name is calculated first.

## To Reproduce

Steps to reproduce the behaviour:

1. Create a graph showing percentiles for two data source names across two separate data sources
2. The value rendered for both percentiles is the value calculated first on the graph

## Expected behaviour

The percentiles should be calculated independently of each other

## Additional context

This is happening because the [caching in `variable_nth_percentile` in `$vstats`](https://github.com/Cacti/cacti/blob/release/1.2.17/lib/graph_variables.php#L458-L461) is too aggressive.

When the type is `aggregate_current` the [cache key](https://github.com/Cacti/cacti/blob/release/1.2.17/lib/graph_variables.php#L573) needs to also reference the data source name.

**Comment by netniV** [comment]
Hi @KrisShannon, I noticed you have a PR open too, is this for this issue or have you a separate one for this?

**Comment by KrisShannon** [comment]
@netniV, No that PR is only for #4263 

I've made a local hack for this where I've updated the `$vstats` indexing in `variable_nth_percentile` to also include the data source name but I'm not happy enough about the way I've done it to make a pull request.
