### ISSUE TITLE
Cacti throws dns_get_record() errors in pollers.php under select circumstances

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#4272]
# Describe the bug

If you are using a hostname and not a Fully Qualified Domain Name for one of your Cacti data collections, when you save the data collection the dns_get_record() exception is thrown.

## To Reproduce

See the note above.

## Expected behavior

Cacti should not throw these errors.

**Comment by netniV** [comment]
We should see if we use the function elsewhere and update as appropriate

**Comment by TheWitness** [comment]
I remember the settings plugin has a DNS resolver, but if memory serves me right, it's using RAW socket communication, which likely won't work with secure DNS.  We should convert that function/library.

**Comment by TheWitness** [comment]
@cigamit Should comment.
