### ISSUE TITLE
Mysql 1.0.5 upgrade script error

### ISSUE THREAD

**Issue by stivnnik** [Cacti/cacti#428]
Hello,

There is an mysql error during database upgrade to 1.0.5. The following query fails:

db_install_execute('ALTER TABLE poller_reindex DROP PRIMARY KEY, ADD PRIMARY KEY (host_id, data_query_id)');

Originally the primary key contained host_id, data_query_id and arg1.
There are duplicate pairs of host_id and data_query_id.

Kind regards,
Stefan Nikolov

**Comment by cigamit** [comment]
This is due to an old error where the re-index data was not removed.  There should only be one re-index method per data query per device.  So, you will have to hand correct this.

**Comment by tleesentons** [comment]
I'm getting the same error when I try to upgrade from cacti-0.8.8c to cacti-1.1.15.
I see the duplicate entry for host_id and data_query_id but uniq assert_value and arg1.
How can I fix this manually?
When I enter the query manually I get duplicate error.
ALTER TABLE poller_reindex DROP PRIMARY KEY, ADD PRIMARY KEY (host_id, data_query_id);
ERROR 1062 (23000): Duplicate entry '4-1' for key 'PRIMARY'
Please help.
Thanks,
Tom

**Comment by cigamit** [comment]
Run this first, not that for host_id=4 you have two entries with data_query_id=1:

`select host_id, data_query_id from poller_reindex where host_id=4;`

Then run the following:

`delete from poller_reindex where host_id=4 and data_query_id=1 limit X;`

Where X is the number of rows returned by the select minus 1.  Then, rerun the ALTER statement.  If it errors, rinse and repeat.
