### ISSUE TITLE
ERROR: short read while reading header rrd->stat_head

### ISSUE THREAD

**Issue by andermat8** [Cacti/cacti#4280]
# Describe the bug

Noticed after updating to RRD 1.7.2, PHP 7.4.16, Net-SNMP 5.7.3 on Cacti 1.2.16 that some graphs will produce this error: ERROR: short read while reading header rrd->stat_head.  

## To Reproduce

Running Cacti 2.16 on Windows Server 2012 with RRD 1.7.2, PHP 7.4.16, Net-SNMP 5.7.3.  Existing graphs are fine but when create new ones they will sometimes produce the error.  I have deleted existing graphs and recreated and can get this error as well.  Real-time for errored graphs will work.  

## Expected behavior

Graphing of interface or other components.  

## Screenshots

![image](https://user-images.githubusercontent.com/29753529/119365250-c1020100-bc7d-11eb-86c4-c01398a9611c.png)

## Desktop (please complete the following information)

windows server 2012
cacti 2.16
Chrome 

I'm seeing this issues on 3 different systems that I have been testing on.

**Comment by andermat8** [comment]
Revert back to 1.4.5 seems to work but I have to delete and recreate the graphs affected.

**Comment by bmfmancini** [comment]
Did you make sure to select rrdtool 1.7.+ in the cacti settings after the
upgrade?

**Comment by andermat8** [comment]
Yes, set to 1.7.2:
![image](https://user-images.githubusercontent.com/29753529/119397985-e9512600-bca4-11eb-939e-217af02d83a1.png)

**Comment by andermat8** [comment]
I opened up an issue with RRDTOOL in tandem https://github.com/oetiker/rrdtool-1.x/issues/1115#issuecomment-847916431

Since the RRD file is zero bytes, this is what is causing the error.  Not sure why when creating a graph it is creating a zero byte RRD file from time to time.

**Comment by netniV** [comment]
I wonder if anything is opening the file for write but then has no data to write or if the `touch` util is being used as that creates empty files.

**Comment by andermat8** [comment]
This happens on creation of the graph so perhaps something is failing in the initial build of the RRD file?

**Comment by TheWitness** [comment]
This often happens if the server runs out of file space while writing the RRDfile.  One way to determine that is to simply execute the command:

```
rrdtool dump filename
```

If the file is completely undamaged, it should be able to complete properly.  I've seen this many times over the years when file systems fill up especially, other common issues would be disk corruption, or possibly a power outage while the file was in the process of being created/written to.

**Comment by andermat8** [comment]
Hi TheWitness, 

Space doesn't appear to be an issue.  I have plenty of space on the server(s) and reverting back to 1.4.5 resolve the error.

**Comment by netniV** [comment]
What version did you go to?  Have you raised the issue with Tobi at all?

**Comment by andermat8** [comment]
Hi Mark,

The versions are mentioned in this issue..  I upgraded to 1.7.2 of RRDTool and reverted back to 1.4.5.  There is a link to my issue logged with Tobi as well.

Regards,

Matt

**Comment by TheWitness** [comment]
@andermat8, did you run the dump command?  This is NOT a Cacti issue.
