### ISSUE TITLE
missing buttons at graph preview mode

### ISSUE THREAD

**Issue by luizfandrade** [Cacti/cacti#4281]
# Describe the bug

after upgrating from 1.2.14 to 1.2.17 Graph Preview Mode dont show buttons any more

## To Reproduce

upgrade cacti to 1.2.17

## Screenshots
![image](https://user-images.githubusercontent.com/67167666/119393573-83b26900-bca7-11eb-9545-f494f3c01e15.png)

## Server

- OS:  Amazon Linux 2
Linux noc 5.10.29-27.128.amzn2.x86_64 #1 SMP Mon Apr 26 21:32:46 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- PHP 7.4 
php-7.4.15-1.amzn2.x86_64
- MariaDB 10.5
mariadb-server-10.5.9-1.amzn2.0.1.x86_64

## Desktop (please complete the following information)

- Windows10
- Browser 
- Chrome Version 90.0.4430.212 (Official Build) (64-bit)
- FireFox 88.0.1 (64-bit)
- Edge Version 90.0.818.66 (Official build) (64-bit)

**Comment by xmacan** [comment]
https://github.com/Cacti/cacti/issues/4248
