### ISSUE TITLE
thold plugin not sending devices status (Up,Dow) to syslog file

### ISSUE THREAD

**Issue by onyy2000** [Cacti/cacti#4286]
I have issue with Thold plugin version 1.5.2 and my cacti version = 1.2.16
I configured the plugin to send events to syslog file, I can receive service events successfully such as (interface status or hightraffic thold etc), but I can't receive any device status.
Note: I can receive device status by mail notification only but it not forwarded to syslog message file.
The settings as following (configuration => settings => thold => Syslog Enabled => Level Debug => kernel.

I don't know if this is bug in thold version or there is something missed in my configuration.
thanks

**Comment by cigamit** [comment]
Not a bug, device status emails were moved to the Monitor plugin.  It doesn't do syslog.

**Comment by onyy2000** [comment]
Thanks for your feedback and support
