### ISSUE TITLE
Large Number of Realtime Graphs Caused Browser Lockup

### ISSUE THREAD

**Issue by majed17** [Cacti/cacti#4287]
tried to exit firefox before replacing the files..the windows closed but a firefox, what's it called, tab in the task bar remained, and the other tabs hanged. only pressing the start menu works to log out and back in..anyway after replacing the the 2 files (graph_realtime.php) & (realtime.js) ... and nothing new..i was thinking if it is .js..then it has to do something with java..might it be caused by my 32-bit java verison installed manually on linux (for asdm to wok)?

_Originally posted by @majed17 in https://github.com/Cacti/cacti/issues/3796#issuecomment-749986670_

now in Version 1.2.17
and after updating to firefox 89
my firefox is like hammering the brake pedal when switching tabs..
this happens when i open too many cacti real time pop ups,.around 41 ones..
i have firefox consuming: 
1006.87 MB		/usr/lib/firefox/firefox
5171.22 MB		/usr/lib/firefox/firefox
in ram
that's way too much, is it a firefox bug or something oyu can tune?

**Comment by netniV** [comment]
err not really sure what to do with this... was it created by mistake?

**Comment by majed17** [comment]
what makes you think it is a mistake? can't open 40 popups in linux?

**Comment by netniV** [comment]
Purely because the title is about a gazillion characters long??  Also, we have no control over how Firefox does its thing.

If you could rework the initial post to better summarise your issue, I might have chance at understanding what I can assist you with ;-)

**Comment by majed17** [comment]
can't take the blame for that! the previous issue was closed unsolved and all this produced was by clicking referencing the last comment there

**Comment by TheWitness** [comment]
There could be a JavaScript Memory Leak, but that is also a lot of panels to have opened.

**Comment by majed17** [comment]
anything to be done by you or mypart? or simply wait for mozilla to reply and fix?

**Comment by majed17** [comment]
with 24 popups open, it still hammers on the brake, i opened the rest of the 18 popups in opera, and in it there is no such problem, but opera stinks very much as it does not reopen the popups on next login

**Comment by majed17** [comment]
i tried the secondary cacti, and today after booting the graphs opened with different sizes, perhaps this is why the smaller ones are opening in the standard big size
![cacti-bug2](https://user-images.githubusercontent.com/35138065/122511821-87b87900-d010-11eb-907d-fe4c3448ee6f.png)

**Comment by TheWitness** [comment]
Well, there is a memory leak somewhere.  If you can see if it's on your server or your browser, that would be good.  Thinking it's the browser.  I'll look for some memory leaks, but having your help would be awesome as covid lifestyle is kicking all of our arses.

**Comment by TheWitness** [comment]
I've corrected two small memory leaks.  Can you update and try again?

**Comment by majed17** [comment]
hmm, got nothing better to do on a friday night than to verify this, and so indeed, even now on a slower computer, i opened ~40 popups, 40 firefox windows in total with main one with many tabs, and now firefox is consuming less than 2GB of ram although cpu usage is a bit high, ~40% just firefox, and switching between tabs is no more slow, and since here is a slightly different linux os, i restarted the pc to see if the windows open at 40% as they do on the original first poping up, but no, the popup is a bit bigger with black space to the right and the left of the realtime graph. but at least thank you and God willing and if i will be still alive, i'll reward your time spent on me since now i'm a financially short

**Comment by TheWitness** [comment]
Well, this is mostly a browser thing.  I us FF latest on Windows.  I'll try to open 40 tabs and look for leaks, but I suspect it's the browser.

**Comment by TheWitness** [comment]
need that 80 inch monitor...

**Comment by TheWitness** [comment]
Found the big memory leak.  The performance is not exceptional, but the memory lead is solved.  The real issue is that each of the windows have their own set of timers that a triggering every so many milliseconds.  So, it get worse for every new window.  Memory problem solved though.

![image](https://user-images.githubusercontent.com/1439914/123497634-a2848200-d5fc-11eb-93ae-15bb96ae38b4.png)

That's a lot of open windows.  I'll look into if there is a way to reduce the level of triggering in the browsers.  But my guess is that each browser does their own setTimeout trigger intervals.

![image](https://user-images.githubusercontent.com/1439914/123497684-e5def080-d5fc-11eb-9499-e0ee962b94c3.png)

**Comment by TheWitness** [comment]
I let it run before the fix and the memory was out of sight.  Now completely stable.

**Comment by majed17** [comment]
now with 43 windows, and after ~half an hour, firefox is using ~6% cpu and memory ~10%, again i'm very grateful

**Comment by TheWitness** [comment]
Cool.  Glad to have fixed it.

**Comment by majed17** [comment]
Now, being at work for the second day since the fix, can't say it's really fixed, sure memory consumption is lower, but it started at 6% then steadily grew to 9% and now after more than 30mins from booting, it's almost 11%, the problem is that at home it was 10% with twice less total memory than here  at work. at home there was no braking, but here, to scroll one time, it takes ~4 sec to respond, cpu usage of firefox here is < 7% also here are a lot more cpu's

**Comment by majed17** [comment]
worth noting, firefox reached about 14% memory usage after nearly 3 hours of running, then suddenly when i hit the apply button on a java related program, all the windows had their menu bar disappear, and firefox usage dropped to ~4% and i had to loggout so as to be able to switch between windows again

**Comment by netniV** [comment]
Unfortunately, we would have no control over that one.  The menu bar disappearing sounds like an internal lockup to the point where it's not processing the WM_xxx messages, unless you mean it was simply hidden.

**Comment by majed17** [comment]
well the bug is not solved yet, so would be nice to reopen itt up again..as much as i hate spying google products, i tried google-chrome. i closed 14 of 43 popups in firefox and reopened them in the spy browser and firefox still uses ~9% memory while chrome is less than 1%, would you agree?

**Comment by netniV** [comment]
Potentially, but then different browsers use and optimize objects in different ways.  I'll leave that one to @TheWitness to decide as he's been fixing it.

**Comment by TheWitness** [comment]
If you think cacti has a lot of bugs, goto Firefoxes bug tracker make my cheeks pucker.  The big memory leak is closed, the reality is thou, that with that many windows open, each with their won timers, the whole experience is going to be a shit show.

It would be better to build a tree with the graphs you want to monitor, and then do them all online.  It should behave much better.  

In summary, there is no more to do here.  Glad we caught the memory leak though.

**Comment by majed17** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1716496
