### ISSUE TITLE
When creating new graphs, indexed graphs show less tables than possible 

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#4290]
# Describe the bug

When you click on create new graphs, tables such as the interface table, are designed to automatically hide columns when there are too many.  However, in some instances, a full screen view will show only 2 columns, yet resizing and maximizing the window shows them all.

## To Reproduce

1. Create a data query with only a few columns
2. Create a data and graph template for data query
3. Associate data query to a device
4. Click create new graphs
5. Even though all columns can be displayed, only some are present
6. Resize window and then maximise again to see all columns.

## Expected behavior

Resize should not be required to show all available columns.  If there are plenty of columns, all are present.

**Comment by TheWitness** [comment]
There is a new feature in 1.2.17+ that handles that.  Please view the attached screen2gif.

![TableColumnsIssue](https://user-images.githubusercontent.com/1439914/123479193-8cf86380-d5ce-11eb-930c-f23060d555f5.gif)

**Comment by netniV** [comment]
Actually, that's wrong, I fixed it.  You are showing only one table there.  You have to have a small table and a large table combined.  One with say 5 columns and one with more.  Not sure why this wasn't tagged in the commit.
