### ISSUE TITLE
When creating data query associations, automatically select matching datasource

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#4291]
# Feature Request

## Is your feature request related to a problem? Please describe

When creating an association between a data query and templates, having a large amount of sources can be troublesome for both the number of sources and the finding the matching source in the sources combo boxes. 

## Describe the solution you'd like

When loading the page, automatically select a matching data source if it exists and no previous data source was picked.

**Comment by TheWitness** [comment]
That makes sense for 1.2.18 too.

**Comment by netniV** [comment]
It would, but it's a feature request, not a bug.  We'll never get moving on features for 1.3 unless we only fix bugs on 1.2.x ;-)
