### ISSUE TITLE
 Cacti Ver 1.2.17 Poller REPLICATE FATAL: Unable to write to directories 

### ISSUE THREAD

**Issue by zythmo** [Cacti/cacti#4303]
I am using Cacti ver 1.2.17 with OS Red Hat Enterprise Linux 8.4 (Ootpa) on 2 machines,
one set as main and other as a poller. I am receiving the below errors on the poller when i view the log 

REPLICATE FATAL: Unable to write to the plugins path '/usr/share/cacti/plugins'
REPLICATE FATAL: Unable to write to the mibs path '/usr/share/cacti/mibs'
REPLICATE FATAL: Unable to write to the images path '/usr/share/cacti/images'
REPLICATE FATAL: Unable to write to the formats path '/usr/share/cacti/formats'
REPLICATE FATAL: Unable to write to the install path '/usr/share/cacti/install'
REPLICATE FATAL: Unable to write to the include path '/usr/share/cacti/include'
REPLICATE FATAL: Unable to write to the lib path '/usr/share/cacti/lib'
REPLICATE FATAL: Unable to write to the base path '/usr/share/cacti'

**Comment by bmfmancini** [comment]
Check your permissions ensure the plugin directory  on the master poller is
the webserver user

**Comment by netniV** [comment]
This isn't the master, this will be the secondaries.  Also check if SELinux is enabled, and if so make sure it works.

**Comment by zythmo** [comment]
Setting directory permissions on the main poller server fixed the problem

**Comment by netniV** [comment]
Interesting, not sure why the main poller needs write permission to itself.  It's normally the source of replication but then I don't run a multi-poller setup myself.  Thanks for clearing it up though.

**Comment by zythmo** [comment]
Not sure why the backend poller asked for such permissions from the main server, but when the owner was unified on all servers that fixed the problem
