### ISSUE TITLE
Automation Networks - Subnet Range for wildcard is too many

### ISSUE THREAD

**Issue by gadzet21** [Cacti/cacti#4304]
# Describe the bug

If it is used wildcard for an IP address, e.g. 172.18. *. 10 - too many IP addresses on this octet are substituted for wildcard. Instead of 0 to 255, it is 65.534

## Screenshots

![image](https://user-images.githubusercontent.com/33205464/122017001-dde3ad00-cdc1-11eb-8a00-9404f5915ce7.png)

## Desktop (please complete the following information)

- Version  - 1.2.17

## Logs

--
2021/06/15 10:08:24 - AUTOM8 [PID: 5488] WARNING: IP address '172.18.37009.10' is not a valid IP address.
2021/06/15 10:08:24 - AUTOM8 [PID: 5488] WARNING: IP address '172.18.37008.10' is not a valid IP address.
2021/06/15 10:08:24 - AUTOM8 [PID: 5488] WARNING: IP address '172.18.37007.10' is not a valid IP address.
2021/06/15 10:08:24 - AUTOM8 [PID: 5488] WARNING: IP address '172.18.37006.10' is not a valid IP address.
2021/06/15 10:08:24 - AUTOM8 [PID: 5488] WARNING: IP address '172.18.37005.10' is not a valid IP address.
2021/06/15 10:08:23 - AUTOM8 [PID: 5488] WARNING: IP address '172.18.37004.10' is not a valid IP address.
2021/06/15 10:08:23 - AUTOM8 [PID: 5488] WARNING: IP address '172.18.37003.10' is not a valid IP address.
2021/06/15 10:08:23 - AUTOM8 [PID: 5488] WARNING: IP address '172.18.37002.10' is not a valid IP address.
--

**Comment by netniV** [comment]
That would be correct because 37000 is WAY beyond a subnet range max of 255

**Comment by gadzet21** [comment]
Will this issue be repaired in the near future? Because in previous version (1.2.5) it worked correct.

**Comment by netniV** [comment]
Not in the near future.

**Comment by gadzet21** [comment]
Is there any other way to enter the address range, e.g. 172.18.0-255.10?

**Comment by netniV** [comment]
I can only think of manually entering all of them

**Comment by TheWitness** [comment]
I thought we had deprecated the astrix support in lieu of sidr notation.

**Comment by TheWitness** [comment]
But I guess not, cause I'm using it ;)

**Comment by netniV** [comment]
I was under that impression too and I think we did so a long while back so as this has only just cropped up, not really seeing it as a top priority to reimplement/fix.

**Comment by TheWitness** [comment]
Old habits are hard to break.  @gadzet21, can you use CIDR notation for this.  If that works, we would appreciate it if you could close the ticket.

**Comment by TheWitness** [comment]
I'm marking no plans, I hesitate to block scanning from working as the wildcard still works in the last octet.
