### ISSUE TITLE
When creating new graphs, duplicate input for host_id is present

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#4310]
# Describe the bug

When creating new graphs using graphs_new.php, there is an input for host_id included as part of the filter bar at the top of the page, and then again at the bottom of the page as a hidden element.  This means that there are two controls on the page with the same unique ID.

**Comment by TheWitness** [comment]
There was a reason for that, I just don't remember what it was.

**Comment by TheWitness** [comment]
Pulling this off the 1.2.19 list as it's minor.  Performed and audit for SQL injection protection but not wanted to fix this at this time.

**Comment by netniV** [comment]
I am thinking that we should mark filter fields with a filter_ prefix in all cases.

**Comment by TheWitness** [comment]
One of the things I was working on was a filter API.  That's been two years ago now.  Need to bring that back to life.  So many things to do, so little time.  Today's been a good day.
