### ISSUE TITLE
Graph Pop-Up Options Missing

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#4313]
The little tool-tip icons on the right side of the graphs are no longer popping up. I'm on version 1.2.17 using Firefox 68 and Chrome 75.0.3770.90. I realize these are older versions. I'll try with some other more modern browsers at another time.

**Comment by netniV** [comment]
If you search, you'll find this has been answered already a few times 👍

**Comment by eschoeller** [comment]
Sorry, ok. I did look through issues dating back to May, but I guess I didn't look hard enough.

**Comment by rtripon** [comment]
Hello, sorry for posting here, I'm having the same problem, can someone point me where's the fix? I tried searching, but clearly I'm missing something.

**Comment by eschoeller** [comment]
There’s a new option in user permissions that needs to be enabled in order for them to work. The default was to leave it unchekced for all users I guess … 

Eric.

**Comment by rtripon** [comment]
Got it, thank you.

**Comment by netniV** [comment]
https://github.com/Cacti/cacti/issues?q=is%3Aissue+sort%3Aupdated-desc+graph+icons+is%3Aclosed

Sorry if that was tricky to find, I just expected it to show up easily enough as there's quite a few since April :)
