### ISSUE TITLE
Allow the Cacti administrator to perform bulk gap filling and floating in parallel

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#4317]
# Feature Request

## Is your feature request related to a problem? Please describe

Cacti provides the removespikes.php binary, but it's almost impossible for very large sites to run this in batch as it would run for a very long time.  Need a way to improve the speed and reliability.

## Describe the solution you'd like

Use parallel threads similar to other tools in the Cacti family.

**Comment by netniV** [comment]
This is a feature so should be on 1.3

**Comment by TheWitness** [comment]
Just saw your comment.  Was in autopilot.  Back to work now.  This one was causing me major blockage @ ~50k to be exact.
