### ISSUE TITLE
data_sources.php improperly shows devices that contain a period (dot) in their name.

### ISSUE THREAD

**Issue by godsyn** [Cacti/cacti#4318]
![image](https://user-images.githubusercontent.com/508678/123167294-5b539100-d444-11eb-9d18-384213a316cc.png)

When viewing data sources, any host that contains a period in their description will be cut off in the dropdown for device.

example hostname:
`example.test`

only shows:
`example`

Cacti version : `1.2.17`

**Comment by TheWitness** [comment]
Yea, we are striping domains to make the UI a bit easier to work with.  Is that a domain, or just magic numeric value you are adding to the hostname?

**Comment by godsyn** [comment]
It is the last two octets of the ip address.

Example
10.0.0.1/22

We would use: hostname (0.223) to signify the ip.

Suggested fix, only truncate if a known suffix. Eh: org, com, net, etc

**Comment by TheWitness** [comment]
Or an option to disable that entirely.

**Comment by godsyn** [comment]
That would be lovely.

**Comment by netniV** [comment]
A simple IP check would prevent your issues before trimming, but an option sounds like a reasonable fix to complement it.

**Comment by TheWitness** [comment]
Okay, this feature has been there fore a while.  Goto Console > Configuration > Settings > Visual and disable `Strip Domains`.  That will resolve this issue for you.  I thought it was there, but getting old and been very grey for a while.

**Comment by godsyn** [comment]
/cacti/data_sources.php
doesn't respect the setting and strips the domain regardless.

**Comment by TheWitness** [comment]
Updated image?  Logout and back in again.

**Comment by godsyn** [comment]
Relogged, cleared cache, etc.
Issue resolved.
