### ISSUE TITLE
SpikeKill menu is wonky

### ISSUE THREAD

**Issue by ekgermann** [Cacti/cacti#432]
Two videos attached. 

Updated from 1.0.5 to 1.0.6.  

The SpikeKill menu items won't appear in Chrome (57.0.2987.98 (64-bit)) at all.

The SpikeKill menu items appear in FF, but are "white on almost white" so difficult to see.

Zipped to get them to attach

[SpikeKill menu wonky in Firefox.zip](https://github.com/Cacti/cacti/files/844359/SpikeKill.menu.wonky.in.Firefox.zip)
[SpikeKill not showing in Chrome.zip](https://github.com/Cacti/cacti/files/844360/SpikeKill.not.showing.in.Chrome.zip)

Also, when image caching is enabled with Boost, killing spikes manually doesn't cause a refresh of the graph like it used to.  Drilling in to the graphs like (today, week, month, etc) shows the correct graphs but refresh doesn't seem to work.

EKG

**Comment by browniebraun** [comment]
This seems to be related to the PAW theme. I will check that tomorrow evening once I will have arrived at home again.

Regards
-Andi

**Comment by cigamit** [comment]
Resolved for Paw Theme.
