### ISSUE TITLE
ERROR PHP NOTICE: Undefined variable: function in file: /var/www/html/cacti/lib/functions.php on line: 1713

### ISSUE THREAD

**Issue by shkmuradhssn** [Cacti/cacti#4323]
# Describe the bug

While trying to populate the Uptime for cisco switch getting the error " **Graph Not created for Device - Uptime due to Bad Data**"

## To Reproduce

Add network device with Device Template " **Cisco Router/ Generic SNMP Device**".
Create the Graph of " **Device Uptime**"

## Expected behavior

Graph Should get generate with device uptime.

## Screenshots

Added

## Desktop (please complete the following information)

- OS: Ubuntu 20.04.2 LTS

- Browser Chromium

- Cacti Version: Version 1.2.17

- Chromium Version: Version 91.0.4472.114 
![Cacti Error1](https://user-images.githubusercontent.com/86398685/123541537-2d2cc480-d756-11eb-8c95-d96cc8bf1b3e.JPG)
![Cacti Error2_log](https://user-images.githubusercontent.com/86398685/123541538-2e5df180-d756-11eb-8aa5-e3a8a02f1c5a.JPG)
[Functions_Php.txt](https://github.com/Cacti/cacti/files/6721432/Functions_Php.txt)

**Comment by netniV** [comment]
This has probably already been fixed in c41476476 as there was a check for a function from the previous version of that code which i noticed was wrong before I saw this issue.

**Comment by shkmuradhssn** [comment]
Thanks, after updating the fucntions.php file, able to populate the graph
