### ISSUE TITLE
Graph for Virtual interface inside trunk Port

### ISSUE THREAD

**Issue by koriks1111** [Cacti/cacti#4327]
Hi everyone, 

i have SSG device and i have multiple sub interface in 1 physical interface. possible to see each traffic on those virtual interface?

as i can see only the total traffic on Trunk Port.

im using  Interface Traffic (bit/sec) template

thanks in advance

**Comment by netniV** [comment]
Some manufacturers do not provide sub interface stats.  You will need to get the MIB's for your device, then find the appropriate OID if one exists.  Once you have that, query the device to see if you can see the appropriate stats.

There may be ACL's to configure to allow viewing of the actual data.

**Comment by TheWitness** [comment]
Going to close this one.  Please take it up on the Forums once you have done the research on this topic.
