### ISSUE TITLE
Data Query paths use XML tag

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#4328]
# Describe the bug

To specify the root path for cacti, data queries use `<path_cacti>` as part of the xml filename.  However, when exported, this makes any XML document invalid as it does not have a closing tag.  Either the value should be updated to be `<path_cacti />` or changed to match other replacement fields such as `|path_cacti|`

## To Reproduce
```console
$ xmllint --format template.xml
template.xml:5: parser error : Opening and ending tag mismatch: path_cacti line 5 and xml_path
<xml_path><path_cacti>/plugins/mURLin/xml/mURLin.xml</xml_path>
                                                               ^
template.xml:148: parser error : Opening and ending tag mismatch: xml_path line 5 and hash_040102e404254402722ff686605143fb5a2f93
</hash_040102e404254402722ff686605143fb5a2f93>
                                              ^
template.xml:1372: parser error : Opening and ending tag mismatch: hash_040102e404254402722ff686605143fb5a2f93 line 5 and cacti
</cacti>
        ^
template.xml:1372: parser error : EndTag: '</' not found
</cacti>
```

**Comment by TheWitness** [comment]
Moving to enhancement to prevent the evil `outdated` bot from making us uncomfortable.

**Comment by TheWitness** [comment]
@netniV, just update the template XML to change `<path_cacti>` to `&lt;path_cacti&gt;` it looks like that's simply a **REAL OLD** template from before we started escaping the `<path_cacti>`
