### ISSUE TITLE
same local_data_id in poller_output_boost have different name and results in loss of data

### ISSUE THREAD

**Issue by gj00354347** [Cacti/cacti#4329]
# Describe the bug

Dear Developers,

I observed gaps in few graphs that is loss of data for some interfaces for error /discard . I enabled the device debug and found that to the corresponding interfaces we are having data but in graphs there is no data .
on checking the poller_ouput_boost , I see for same local_data_id , I have error in/out and discard in/out for a time stamp and in next poll for the same local_data_id , i have no name for data source and a strange output which is resulting in gaps in the graph .

here is sample output from poller_output_boost 

 local_data_id | rrd_name     | time                | output
+---------------+--------------+---------------------+-------------------------------------------------------------------------------------------------------
|        575242 | errors_in    | 2021-06-29 12:21:49 | 0
|        575242 | errors_out   | 2021-06-29 12:21:49 | 0
|        575242 | discards_in  | 2021-06-29 12:21:49 | 0
|        575242 | discards_out | 2021-06-29 12:21:49 | 0
|        575243 | errors_in    | 2021-06-29 12:21:49 | 243106
|        575243 | errors_out   | 2021-06-29 12:21:49 | 0
|        575243 | discards_in  | 2021-06-29 12:21:49 | 188467
|        575243 | discards_out | 2021-06-29 12:21:49 | 0
|        575242 |              | 2021-06-29 12:17:08 | Innodbbufferpoolpagesdata:30705 Innodbbufferpoolpagesfree:230408 Innodbbufferpoolpagestotal:262143 Inn
|        575243 |              | 2021-06-29 12:17:07 | Innodbbufferpoolpagesdata:220961 Innodbbufferpoolpagesfree:39782 Innodbbufferpoolpagestotal:262143 Inn
|        575242 | errors_in    | 2021-06-29 12:16:47 | 0
|        575242 | errors_out   | 2021-06-29 12:16:47 | 0
|        575242 | discards_in  | 2021-06-29 12:16:47 | 0
|        575242 | discards_out | 2021-06-29 12:16:47 | 0
|        575243 | errors_in    | 2021-06-29 12:16:47 | 243106
|        575243 | errors_out   | 2021-06-29 12:16:47 | 0
|        575243 | discards_in  | 2021-06-29 12:16:47 | 188467
|        575243 | discards_out | 2021-06-29 12:16:47 | 0
|        575242 |              | 2021-06-29 12:12:08 | Innodbbufferpoolpagesdata:30705 Innodbbufferpoolpagesfree:230408 Innodbbufferpoolpagestotal:262143 Inn
|        575243 |              | 2021-06-29 12:12:07 | Innodbbufferpoolpagesdata:220961 Innodbbufferpoolpagesfree:39782 Innodbbufferpoolpagestotal:262143 Inn
|        575242 | errors_in    | 2021-06-29 12:11:48 | 0
|        575242 | errors_out   | 2021-06-29 12:11:48 | 0
|        575242 | discards_in  | 2021-06-29 12:11:48 | 0
|        575242 | discards_out | 2021-06-29 12:11:48 | 0
|        575243 | errors_in    | 2021-06-29 12:11:48 | 243106
|        575243 | errors_out   | 2021-06-29 12:11:48 | 0
|        575243 | discards_in  | 2021-06-29 12:11:48 | 188467
|        575243 | discards_out | 2021-06-29 12:11:48 | 0
|        575242 |              | 2021-06-29 12:07:13 | Innodbbufferpoolpagesdata:30705 Innodbbufferpoolpagesfree:230408 Innodbbufferpoolpagestotal:262143 Inn
|        575243 |              | 2021-06-29 12:07:07 | Innodbbufferpoolpagesdata:220961 Innodbbufferpoolpagesfree:39782 Innodbbufferpoolpagestotal:262143 Inn

I do not know why it is like this may be because this particular data source is corrupted or what ?? or may be a Bug ??

## To Reproduce

cannot tell like what exactly to do to reproduce this error .

## Screenshots

![image](https://user-images.githubusercontent.com/27295357/123784373-abfd3b00-d8d7-11eb-9c7f-169ce2c22380.png)

cacti 1.2.17
spine 1.2.17
OS Red Hat Enterprise Linux Server release 7.8 (Maipo)
mysql mysql  Ver 15.1 Distrib 5.5.65-MariaDB,
rrdtool RRDtool 1.4.8

Best Regards,
Gopal

**Comment by netniV** [comment]
So the local data id should be enough to get to the unique RRD in question and with the given field name be able to update the correct source.  So, whilst that appears to be an error, I'm not sure it's a cause but others may have better experience on that than me.

**Comment by TheWitness** [comment]
Update rrdtool to 1.7.2, and make sure after, you update the GUI setting as well and this issue will resolve itself.
