### ISSUE TITLE
Usergroup "member enabled" & LDAP auth - user not enabled

### ISSUE THREAD

**Issue by choefing** [Cacti/cacti#433]
Not quite sure if it works as intended or if it is really a small issue:

When I go for LDAP auth, creating a user as template (thanks for the fix) and put this user into a usergroup where I specify settings for ALL group members, I am able to set the "enabled" flag for all group users.
Unfortunately this flag seems to be not processed:

- Template User --> enabled unchecked
- Template user is member of "group"
- "group" has "enabled" checked

You can not log in as the user properly authenticated via LDAP is "not enabled".
For now it can be "fixed" by enabling the user template and set it to "locked".

![grafik](https://cloud.githubusercontent.com/assets/26385419/23951183/bb0eec56-098d-11e7-8a3b-4c3b4e3fb642.png)
![grafik](https://cloud.githubusercontent.com/assets/26385419/23951237/d8742162-098d-11e7-9ad3-7426f4f1d554.png)
![grafik](https://cloud.githubusercontent.com/assets/26385419/23951303/ffc100d2-098d-11e7-85cb-36e7857cc47a.png)

Thanks for all the effort guys.

**Comment by cigamit** [comment]
Enabled only applies to the group.  If a user is disabled, they should not be able to log in regardless of access.  Does that makes sense, or am I off in the woods?  Yes, and template users must be enabled, which seems to be a bad thing.

**Comment by choefing** [comment]
Before I respond to that, we need another fix.
Since the last changes I can perfectly login utilizing different template users, groups and domains using LDAP, but the LOCAL admin account is not able to login anymore. I get an "LDAP search error" and as I dont know how to enable debug from server console the only thing the log produces is
`2017-03-16 13:55:52 - AUTH LOGIN: LDAP Error:`

You want me to open another bug report for that ? 

![grafik](https://cloud.githubusercontent.com/assets/26385419/23999443/b74d2ad0-0a58-11e7-9c9d-c31a4b35c386.png)



Seems we just did interpret the things different.
Of course it makes sense that USER settings overrule GROUP settings, so if the template user is "disabled" it should not matter what the group setting says. I agree.
The template user can not login anyways when you set it to "enabled" and "locked" but maybe this can be changed with low priority later to have no need to enable the template user.

**Comment by cigamit** [comment]
You need to change the realm of the admin from LDAP to Local.  You likely changed it by accident.  I'm thinking we should block users from changing the Admin's realm.  So, I'll keep this open for the moment.

**Comment by cigamit** [comment]
On second thought, I'm just going to close this.
