### ISSUE TITLE
Automation attempts to call undefined debug function

### ISSUE THREAD

**Issue by daedalus** [Cacti/cacti#4330]
`2021-06-29` 20:16:07 - CMDPHP PHP ERROR Backtrace: `(CactiShutdownHandler())`

`2021-06-29` 20:16:07 - ERROR PHP ERROR: Uncaught Error: Call to undefined function debug() in /usr/share/cacti/lib/api_automation.php:3853 Stack trace: #0 /usr/share/cacti/lib/api_automation.php(3664): calculateNextStart(Array, 1625008567) #1 /usr/share/cacti/poller_automation.php(230): api_automation_is_time_to_start('3') #2 {main} thrown in file: /usr/share/cacti/lib/api_automation.php on line: 3853`

**Comment by netniV** [comment]
That error seems to have been introduced a year ago as part of #3594 in commit 975aa05fc.  I have just pushed a change to update the name to be `automation_debug`
