### ISSUE TITLE
Zero Date defaults are causing column change failures

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#4331]
# Describe the bug

Later versions of MySQL are disallowed zero dates as a valid date value (correctly).  Cacti should be made to adhere to this by using null values instead.  

The db_xxx functions which actively add, change or remove columns or tables should also be made to check for the existence of such fields and provide an error if they exist since the database change will NOT have been applied.

Where multiple columns exist with zero dates, ALL must be corrected in a single ALTER statement.

This same issue also applies to plugins.

**Comment by TheWitness** [comment]
Zero date are sometime in 1970, like January 01, 1970 @ 00:00:00 depending on your timezone.  It's a valid data, just awkward for people who think that '0' must have been around the time Jesus was born in Nazareth.  Changing this requirement breaks a lot of things in plugins not just in Cacti.  I would place this at a very low priority.

**Comment by netniV** [comment]
I disagree, I would place it a lot higher because it breaks table modifications which in turns breaks systems.

**Comment by TheWitness** [comment]
Cute specific examples please.

**Comment by netniV** [comment]
Upgrades performed by plugins fail because a table has a zero date column and therefore will not have any new or modified columns (other tables without them will be altered without issue).  Whilst fine under prior versions of MySQL, these will start to fail as systems are updated because it's no longer a default valid option.  

phpMyAdmin has exactly the same issue trying to clone a table with one too because it can't recreate the table.

We also should remove them to be more consistent with other systems when exporting data.  I am not aware of any other system allowing all zeros as a valid date (though there may be some).

**Comment by TheWitness** [comment]
Still not specific enough.  As long as the server is using our recommended setting (my.cnf), there is really no issue.

**Comment by netniV** [comment]
Your reply was also not specific enough to state why we should recommend bad settings and values.

**Comment by TheWitness** [comment]
If the client, in your case is forcing a client setting that is incompatible, well, that's not our problem.

**Comment by TheWitness** [comment]
I'm not saying we don't do this project, but there are 200+ features ahead of it.

**Comment by netniV** [comment]
So you feel it is OK to use an non-valid date as a crux ?

**Comment by netniV** [comment]
Please give a valid reason to use a zero date?

**Comment by TheWitness** [comment]
it was a vilid date until Oracle took over.

**Comment by netniV** [comment]
Only for MySQL, not for any other system.

**Comment by TheWitness** [comment]
Granted, but who cares really.  What we have for now works fine.

**Comment by netniV** [comment]
But it doesn't.  People are finding things broken and inconsistent which is the point.

**Comment by TheWitness** [comment]
Try to set a time of 1965-01-01 in MySQL.  Is that a valid timestamp?  Just curious...
