### ISSUE TITLE
syslog and weathermap plugins auto to disable

### ISSUE THREAD

**Issue by ztkink** [Cacti/cacti#4334]
My cacti will auto to disable plugins, i don't know what‘s wrong.

**Comment by cigamit** [comment]
This tracker is for Cacti bugs.  Post your issues with the plugins on the forums.  And please be specific and tell us your Cacti version, plugin versions, php versions, etc... and post the errors from the Cacti log (Cacti tells you exactly why it disabled it).  Without specifics, no one is going to be able to help you.

**Comment by ztkink** [comment]
> This tracker is for Cacti bugs. Post your issues with the plugins on the forums. And please be specific and tell us your Cacti version, plugin versions, php versions, etc... and post the errors from the Cacti log (Cacti tells you exactly why it disabled it). Without specifics, no one is going to be able to help you.

!!!oh , i know ,thank you!
