### ISSUE TITLE
Cacti new install error : 500 Internal Server Error

### ISSUE THREAD

**Issue by rtripon** [Cacti/cacti#4336]
Hello,
I'm trying to install a new server with cacti and I'm stuck at this error. Everything works ok, untill I hit "Confirm Installation".
![500 internal error](https://user-images.githubusercontent.com/28921178/124638442-a1bcdd00-de93-11eb-80ee-b84bedadf33e.jpg)

I'm using the develop brach.

Using Linux centos7 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

PHP 7.4.21 (cli) (built: Jun 29 2021 15:17:15) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
RRDtool 1.7.2  Copyright by Tobias Oetiker <tobi@oetiker.ch>
mariadb 10.5

From httpd logs, I have this:

```
[Tue Jul 06 18:43:46.553369 2021] [php7:error] [pid 28235] [client 172.19.80.27:61889] PHP Fatal error:  Uncaught TypeError: Argument 6 passed to tail_file() must be of the type int, null given, called in 
/var/www/html/cacti/lib/installer.php on line 3421 and defined in 
/var/www/html/cacti/lib/functions.php:1042\nStack trace:\n#0 
/var/www/html/cacti/lib/installer.php(3421): tail_file()\n#1 
/var/www/html/cacti/lib/installer.php(2835): Installer::getInstallLog()\n#2 
/var/www/html/cacti/lib/installer.php(1635): Installer->processStepComplete()\n#3 
/var/www/html/cacti/lib/installer.php(184): Installer->processCurrentStep()\n#4 
[internal function]: Installer->jsonSerialize()\n#5 
/var/www/html/cacti/install/step_json.php(66): json_encode()\n#6 
{main}\n  thrown in /var/www/html/cacti/lib/functions.php on line 1042, referer: http://192.168.96.122/install/install.php?data={%22Step%22:%2210%22,%22Eula%22:true}
```

Tried to search on git, but couldnt find something related to my problem, maybe I'm missing some php module?.

[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
intl
json
ldap
libxml
mbstring
mcrypt
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
snmp
sockets
sodium
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
zip
zlib

[Zend Modules]

**Comment by netniV** [comment]
Hi @rtripon, this is a typing error due to the fact that we have started to put typing information onto our functions.  As a result, there can be some issues that arise on the develop branch as a result.  I'll take a look at this one

**Comment by netniV** [comment]
So I've pushed a small change.  Do you want to see if that works for you?

**Comment by rtripon** [comment]
Hello,
Seems ok now. Thank you.
