### ISSUE TITLE
Advanced ping not wring graph after the migration

### ISSUE THREAD

**Issue by annmaria1** [Cacti/cacti#4337]
HI team,

Im getting below error on cacti 1.2.18 and advanced ping is not plotting the graph too. It has happened after the migration from 0.8.8. How to resolved it.

ERROR PHP ERROR: Uncaught Error: Class 'Net_Ping' not found in  /var/lib/cacti/scripts/ss_fping.php:24 Stack trace: #0  /usr/share/cacti/script_server.php(260): ss_fping('2.2.2.2,  '20', 'ICMP') #1 {main} thrown in file:  /var/lib/cacti/scripts/ss_fping.php on line: 24
--
2021-07-07 02:05:04 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())

Please help

Thanks
JInju

**Comment by bmfmancini** [comment]
which OS are you using ?

**Comment by annmaria1** [comment]
Redhat 7. It has happened after the migration. So I reverted back.
