### ISSUE TITLE
password_verify in php<5.5

### ISSUE THREAD

**Issue by nitzan-tz** [Cacti/cacti#434]
The change in the following commit 
"Use password_verify instead of password_hash @ php5.5+" 
break support for php 5.4 and bellow as password_verify  is only from php5.5
Centos 7.2 still use older php so it break native support in this distribution 

https://github.com/Cacti/cacti/commit/390f0f90452151f9a3437333754d58d54f37f1c5 

Thanks

Nitzan

**Comment by cigamit** [comment]
Got it.  Please test the latest auth_changepassword.php and provide feedback.

**Comment by nitzan-tz** [comment]
Hi,

I already upgrade to php 5.6 from a third party repository so I cant test for now

Thanks

Nitzan

**Comment by cigamit** [comment]
Well that sucks.  However, I think it was nailed in the last change.  The code as it was actually would never have worked in a version of PHP less that 5.5.
