### ISSUE TITLE
Viewing Boost Status page generates SQL Backtrace lines in log file.

### ISSUE THREAD

**Issue by Cramin** [Cacti/cacti#4340]
# Describe the bug

Like in title, when i open Boost status page new blue line appears in log.
Cacti 1.2.17 + Spine 1.2.17 Nginx 1.14.2 PHP 7.3.27 MariaDB 10.3.29 Debian 10.10
## To Reproduce

1. Go to 'Utilities -> System Utilities '

2. Click on 'View Boost Status.'

3. Click on 'Logs' at top of the page

4. See error: CMDPHP SQL Backtrace: (/utilities.php[89]:boost_display_run_status(), /utilities.php[2227]:db_fetch_cell(), /lib/database.php[411]:db_fetch_cell_prepared(), /lib/database.php[427]:db_execute_prepared())

## Desktop (please complete the following information)

- OS: Windows

- Browser Opera

- Version 77
![boost](https://user-images.githubusercontent.com/26957092/124907151-1bfe7600-dfe8-11eb-8290-8c46dd3f3906.png)

**Comment by netniV** [comment]
Hi @Cramin 

I can see the line in question but I would like to see the error that is appearing with the backtrace.  If you can filter by a time when those occur, there should be an error as well.  Your filter in the screenshot is masking that.

**Comment by netniV** [comment]
Closed due to no feedback.
