### ISSUE TITLE
Tree Graph shows same highlighting as graph edit screen

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#4342]
# Describe the bug

When moving over items on the Tree Graph, rows are highlighted in the same fashion as the graph editing screen.

## Expected behavior

Whilst this is useful in graph editing, it should not appear on the Tree views.

**Comment by eschoeller** [comment]
Yup I just noticed this a little while ago and it's awfully annoying.

**Comment by netniV** [comment]
It has been fixed, apply the above changes to correct it.

**Comment by TheWitness** [comment]
Was there a CHANGELOG for this one?

**Comment by netniV** [comment]
Yes, it was mistakenly applied to master.
