### ISSUE TITLE
[1.2.16] - Grpint Max value is wrong when displaying last day info

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#4345]
Hey Guys,

Today we noticed that when you select some graphs the Maximum value is off and seems averaged out even though 

Here is the Last day graph you see a spike to 250 Mbps  yet the max show 180

![image](https://user-images.githubusercontent.com/13388748/125119503-2e97ae80-e0bf-11eb-8409-273e54985dc1.png)

If you zoom into the spike you see these values

![image](https://user-images.githubusercontent.com/13388748/125119650-6a327880-e0bf-11eb-97d9-8258f1c8d350.png)

Which tells me that the RRD doesn't have the values averaged out since its able to pull the proper value 

Raw Data  when zoomed in

![image](https://user-images.githubusercontent.com/13388748/125119911-bc739980-e0bf-11eb-80d1-b5daeffb2433.png)

Raw data from last day

![image](https://user-images.githubusercontent.com/13388748/125120290-402d8600-e0c0-11eb-9cdc-2585700084c9.png)

The data lines up shows 283Mbps for both the zoomed in and non zoomed in graphs yet the Max value shows differently
I haven't noticed this before is this by design or an issue ?

If it helps I can post the raw CSV data

We are using the default interface traffic template here is the template 

![image](https://user-images.githubusercontent.com/13388748/125121595-2725d480-e0c2-11eb-8dcd-9e63edc2af3e.png)

**Comment by bmfmancini** [comment]
Closing this seems to be a RRDtool specific thing not Cacti

**Comment by netniV** [comment]
There is a difference between GPRINT:AVG MAX and GPRINT:MAX MAX... I wonder if that's what you are hitting but as you didn't close the issue, I will now.  If it needs reopening, just reply.
