### ISSUE TITLE
Icons next to graphs are missing - example spike kill GUI

### ISSUE THREAD

**Issue by dsimka** [Cacti/cacti#4346]
After upgrade from 2.1.16 to 2.1.18 was trying to use spike kill on graph , but no icon is shown

**Comment by netniV** [comment]
Please search through past issues and the current CHANGELOG, this issue has already been raised a number of times.

**Comment by dsimka** [comment]
ok, searched from google and found https://github.com/Cacti/cacti/issues/4240
solved
