### ISSUE TITLE
Dead link on navigation tab.

### ISSUE THREAD

**Issue by wonderzone** [Cacti/cacti#435]
Sorry, I'm not good at English...

When using theme "paw" and displaying the screen of the some plug-in, relative path "graph_view.php" is resolved "/cacti/plugins/someplugin/graph.php" and got "404".

![subtree](https://cloud.githubusercontent.com/assets/26381365/23987579/9c189bea-0a6d-11e7-8c2b-2ec28fa6d7c1.png)

[/include/themes/paw/main.js]
110: +'\<li>\<a href="graph_view.php?action=tree">Tree View\</a>\</li>'
111: +'\<li>\<a href="graph_view.php?action=list">List View\</a>\</li>'
112: +'\<li>\<a href="graph_view.php?action=preview">Preview View\</a>\</li>'

Best Regards.

**Comment by cigamit** [comment]
Resolved, thanks.
