### ISSUE TITLE
When using 'Web Basic' authentication, better to popup a message to suggest user close the window, or even, when user consent, close the browser window to make the Apache Basic Authentication logs out

### ISSUE THREAD

**Issue by kim-fitness** [Cacti/cacti#4351]
# Feature Request
When using 'Web Basic' authentication, 
If user click 'logout', it is better to popup a message to suggest user close the window, or even, when user consent, close the browser window to make the Apache Basic Authentication logs out

## Is your feature request related to a problem? Please describe
When using 'Web Basic' authentication, user cannot log out unless close the browser window or clean the browser history

## Describe the solution you'd like

When using 'Web Basic' authentication, If user clicks 'logout', Cacti can pops up a message to suggest user close the browser windows or clear browser history to make the Apache Basic Authentication logs out.
Or even, when user consent, Cacti can close the browser window automatically.

**Comment by netniV** [comment]
I believe that there is a method to force apache to logout the user, but it's not guaranteed.  The logout button is removed by default from Web Auth mode if I recall.

**Comment by kim-fitness** [comment]
> I believe that there is a method to force apache to logout the user, but it's not guaranteed. The logout button is removed by default from Web Auth mode if I recall.

Hi Mark,
Thanks for the feedback, I think if Cacti can pop up a message to suggest user close the window, it will has a much better user experience especially for those who are green hand on Apache Basic Authentication.

**Comment by TheWitness** [comment]
I tend to agree.  The variation in SSO modules wrapped around Web Basic make this very hard to overcome.

**Comment by TheWitness** [comment]
FYI guys, with Basic Authentication, there is no logout button.  This change was made a few released ago.  I think it's more important to detect a token revocation by the SSO provider and redirect to obtain a fresh token.  I've opened a bug on that topic, and will therefore close this one since there is no logout button when using Basic Authentication.
