### ISSUE TITLE
php error when duplicate a report 

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/cacti#4353]
1) create a report 
2) duplicate it, check log error exist 

2021/07/20 01:43:32 - CMDPHP PHP ERROR NOTICE Backtrace: (/reports_admin.php[89]:reports_edit(), /lib/html_reports.php[1284]:reports_interval_start(), /lib/reports.php[190]:CactiErrorHandler())
2021/07/20 01:43:32 - ERROR PHP NOTICE: Undefined offset: 0 in file: /opt/IBM/cacti/lib/reports.php on line: 190
2021/07/20 01:43:30 - CMDPHP PHP ERROR NOTICE Backtrace: (/reports_admin.php[89]:reports_edit(), /lib/html_reports.php[1300]:reports_generate_html(), /lib/reports.php[704]:CactiErrorHandler())
2021/07/20 01:43:30 - ERROR PHP NOTICE: Undefined offset: 0 in file: /opt/IBM/cacti/lib/reports.php on line: 704
2021/07/20 01:43:14 - CMDPHP PHP ERROR NOTICE Backtrace: (/reports_admin.php[94]:reports(), /lib/html_reports.php[1643]:CactiErrorHandler())
2021/07/20 01:43:14 - ERROR PHP NOTICE: Undefined offset: 0 in file: /opt/IBM/cacti/lib/html_reports.php on line: 1643
2021/07/20 01:43:05 - CMDPHP PHP ERROR NOTICE Backtrace: (/reports_admin.php[94]:reports(), /lib/html_reports.php[1643]:CactiErrorHandler())
2021/07/20 01:43:05 - ERROR PHP NOTICE: Undefined offset: 0 in file: /opt/IBM/cacti/lib/html_reports.php on line: 1643
2021/07/20 01:43:05 - CMDPHP PHP ERROR WARNING Backtrace: (/reports_admin.php[58]:reports_form_actions(), /lib/html_reports.php[221]:duplicate_reports(), /lib/reports.php[44]:CactiErrorHandler())
2021/07/20 01:43:05 - ERROR PHP WARNING: Invalid argument supplied for foreach() in file: /opt/IBM/cacti/lib/reports.php on line: 44

Test env: 
Cacti 1.2.15
FF 89
rhel7 x64

**Comment by xmacan** [comment]
Tested on 1.2.18, found another warn and error:
2021-07-21 21:06:54 - ERROR PHP WARNING: Invalid argument supplied for foreach() in file: /usr/local/share/cacti_develop/lib/reports.php  on line: 46
2021-07-21 21:06:54 - CMDPHP PHP ERROR WARNING Backtrace:  (/reports_admin.php[58]:reports_form_actions(), /lib/html_reports.php[221]:duplicate_reports(), /lib/reports.php[46]:CactiErrorHandler())
2021-07-21 21:06:54 - ERROR PHP NOTICE: Undefined offset: 0 in file: /usr/local/share/cacti_develop/lib/html_reports.php  on line: 1643
2021-07-21 21:06:54 - CMDPHP PHP ERROR NOTICE Backtrace:  (/reports_admin.php[94]:reports(), /lib/html_reports.php[1643]:CactiErrorHandler())

I will look at it.

**Comment by ddb4github** [comment]
How about move `$fields_reports_edit` from `cacti/lib/reports.php` to `cacti/include/global_arrays.php`?

**Comment by xmacan** [comment]
I made small fix #4355

**Comment by netniV** [comment]
@yingbaiibm any feed back on if this is now resolved?
