### ISSUE TITLE
XSS issue with special char: grave and curly brace

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#4356]
# Describe the bug
* cacti/data_templates.php:
  Name column does not escape grave(`) char. 
Example:
   ```
   Cacti Stats - Export Duration	onmouseover=`alert(188)`
   ```
  Ref: https://davidmurdoch.com/2017/09/02/the-grave-accent-and-xss/
* graph_templates.php?action=template_edit&id=123
  Graph Item Inputs-->Name column,  cruly braces(})
Example:
   ```
   a onmouseover=55+{toString:alert}//
   ```

## To Reproduce
Hardly reproduce under Firefox/Chrome

**Comment by netniV** [comment]
Does this affect any other areas?

**Comment by ddb4github** [comment]
* data_templates.php issue is about function `filter_value`
 * graph_templates.php issue is about function `html_escape`
 * current `filter_value` does not use `html_escape`

**Comment by TheWitness** [comment]
@ddb4github, didn't I propose and didn't we implement a str_replace() on the graves character?

**Comment by TheWitness** [comment]
This is already in the 1.2.x branch.  Is it nor right?

![image](https://user-images.githubusercontent.com/1439914/133531401-e138d77b-b911-4ea2-9363-a85d72c9b918.png)

**Comment by netniV** [comment]
If you look more closely though, I think he's saying that the filter_value calls we have don't use html_escape so if any of the filter_values are reused in display, they would allow XSS.

**Comment by netniV** [comment]
I was unable to reproduce this myself, so I have basically applied the same code in filter_value as was present in html_escape.  This will make the filters align better as well so it should be a win win scenario.

**Comment by TheWitness** [comment]
That's cause we fixed it already ;)

**Comment by TheWitness** [comment]
Here is the commit that fixed the graves issue.

https://github.com/Cacti/cacti/commit/8b42b6563464f9d736eb648e345ca4830d7f3e92

Going to close this as duplicate.

**Comment by netniV** [comment]
This isn't a duplicate.  It's applying the fix to the filter_value() function.

**Comment by TheWitness** [comment]
Yea, I noted that.

**Comment by netniV** [comment]
Confused as you said it was a duplicate.
