### ISSUE TITLE
Gap on graph

### ISSUE THREAD

**Issue by georgej77** [Cacti/cacti#4357]
Hi Team,

All the graphs on my cacti server show a gap along with a map. My cacti and spine version is 1.2.18. I have attached here the poller setting and poller information along with it.

I tried to adjust the value of data collector process (8, 10, 12 etc) and thread process (8,10, 15,20,30 etc). But the result was the same. Can you please help me to provide a correct solution for resolving it.

![image](https://user-images.githubusercontent.com/41739394/126626704-65194365-e447-446a-a29f-b8d6a107ece3.png)

![image](https://user-images.githubusercontent.com/41739394/126627622-5d5575ad-1abf-4da8-aaa9-c39c6a51ee7b.png)

![image](https://user-images.githubusercontent.com/41739394/126627745-07179ee9-a728-49c8-83eb-6a5f6e4e0bec.png)

Cacti Version	1.2.18
Cacti OS	unix
NET-SNMP Version	NET-SNMP version: 5.7.2
RRDtool Version Configured	1.4.0+
RRDtool Version Found	1.4.8
Devices	134
Graphs	430
Data Sources	Script/Command: 25
SNMP Get: 48
SNMP Query: 292
Script Server: 78
Total: 443

**Comment by bmfmancini** [comment]
In your cacti logs are you seeing any poller overruns?

Also increase your max connection in your my.cnf to 300

Is this one one device or many?

**Comment by annmaria1** [comment]
Yes. I saw the below message from log. 
2021-07-22 00:09:20 - POLLER: Poller[1] PID[65692] WARNING: There are 1 processes detected as overrunning a polling cycle, please investigate.

Right now I'm using cmd.php. But 80% of graphs are ok. But others are not plotting the map. Please find the below image.

![image](https://user-images.githubusercontent.com/41739394/126670670-20a2528f-e2e4-4c15-9d75-c0fc440864c9.png)

I have already increased the max connection value. Please find the configuration below.

 grep "^[^#;]" /etc/my.cnf.d/server.cnf
[server]
[mysqld]
sql_mode = NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER
collation-server = utf8mb4_unicode_ci
character-set-server=utf8mb4
max_heap_table_size = 132M
tmp_table_size = 64M
join_buffer_size = 128M
innodb_file_format = Barracuda
innodb_large_prefix = 1
innodb_flush_log_at_timeout = 3
innodb_buffer_pool_size = 1GB
innodb_buffer_pool_instances = 10
innodb_read_io_threads = 32
innodb_write_io_threads = 16
innodb_io_capacity = 5000
innodb_io_capacity_max = 10000
**max_connections=500**
[galera]
[embedded]
[mariadb]
[mariadb-10.4]

I saw the attached error log too.
[cacti_stderr.log](https://github.com/Cacti/cacti/files/6863747/cacti_stderr.log)

**Comment by bmfmancini** [comment]
is the ping_latency.pl your own script ?

when running spine you can run ./spine -R -V 5 and you will see the output of spine 
it will help you narrow down where the slowdown is

If the poller is over running then its either your network having an issue or not enough threads/processes 
if you want you can reach out to me and I can help you troubleshoot I dont think this is a cacti issue though

**Comment by annmaria1** [comment]
is the ping_latency.pl your own script ? Ans. I have copied it from old server as I saw the file missing on new server. 

What time are you free for troubleshoot it?

**Comment by annmaria1** [comment]
Hi support Team,
As mentioned in the ticket, when I used spine, getting gap on graph. Some time all the graphs will be in grey. So now I changed it to cmd.php. Currently 99% is ok. one or two graphs are not plotting the map. When I removed the device and recreated the graph again, it will work. At that time the other will stop creating the map.
I have increased the CPU to 8 and memory is 4 GB.
I can see the below warning log. In which area should I fine tune it. please advice.
CMDPHP WARNING: cmd.php poller has run over its polling interval and therefore is ending

**Comment by bmfmancini** [comment]
Hey @georgej77  

We can hop on a chat if you still need help

**Comment by georgej77** [comment]
Yes I need help.

**Comment by bmfmancini** [comment]
Send me an email we can set something up

**Comment by georgej77** [comment]
Can you provide me with your email address?

**Comment by netniV** [comment]
@georgej77 it may be worth trying to grab the 1.2.17 version of spine.  There are some issues with the 1.2.18 release which we need to work on.

**Comment by georgej77** [comment]
I couldn't find the repository of cacti and spine 1.2.17 on the cacti
portal. Can you share with me the URL for it?
Is yum package available? I have noticed earlier that yum is available only
for 1.2.15.

Thank you for your response.

**Comment by netniV** [comment]
https://files.cacti.net/spine/cacti-spine-1.2.17.tar.gz

**Comment by georgej77** [comment]
Thanks. Let me try it.

**Comment by georgej77** [comment]
Thanks. Issue has been resolved now.
