### ISSUE TITLE
[Cacti 1.0.4] restricted user does not see graphs in tree view

### ISSUE THREAD

**Issue by jenhek** [Cacti/cacti#436]
First: the authorization schemes are in Cacti 1 much better than before - big thank you!

I can now restrict a user so that he sees only "his" devices in  the tree view.

However [BUG]: if he clicks on one of those device (in tree view) no graphs appear.

In "list view" he can access all the graphs, bit this is off course a little bit cumbersome for navigation

**Comment by cigamit** [comment]
Hmm.  Will have to reproduce.  Can you provide screen shows of the all the tabs for the user so we know the exact setup.  Would need Graph Perms, Device Perms, Template Perms and Tree Perms.

Thanks!

**Comment by jenhek** [comment]
Am 17.03.2017 um 02:00 schrieb Jimmy Conner:
> Hmm.  Will have to reproduce.  Can you provide screen shows of the all the tabs for the user so we know the exact setup.  Would need Graph Perms, Device Perms, Template Perms and Tree Perms.

Alright.

Note, that in the example user is also member
of a user group with some strange settings in
group-tree-perms to make the user see exactly
everything what he should see in tree.

It looks inverted to what I would assume
it should look like

As note: listview looks o.k.


-- 
Dipl.-Phys. Jens Hektor, Networks
IT Center, RWTH Aachen University
Room 2.04, Wendlingweg 10, 52074 Aachen (Germany)
Phone: +49 241 80 29206 - Fax: +49 241 80 22100
http://www.itc.rwth-aachen.de - hektor@itc.rwth-aachen.de

**Comment by cigamit** [comment]
Still waiting on those screen shots.  I'll give you a few more days to upload them before I close this ticket.

**Comment by jenhek** [comment]
On 17.03.2017 23:26, Jimmy Conner wrote:
> Still waiting on those screen shots.  I'll give you a few more days to upload them before I close this ticket.
> 

Sorry, I did hit reply-all so the github received (and scrubbed) them.

Here they go!

Best regards, Jens

**Comment by cigamit** [comment]
Please attach them here.  Thanks.

**Comment by cigamit** [comment]
BTW 'Reply All' does not.  You drag the images into the comment window, and press the 'Comment' button.

**Comment by cigamit** [comment]
Closing for lack of response.

**Comment by jenhek** [comment]
Heyhey, not so fast, at least it's weekend ...


![Uploading group-template-perms.png…]()
![Uploading group-graph-perms.png…]()
![Uploading group-device-perms.png…]()
![Uploading user-treeview.png…]()
![Uploading user-tree-perms.png…]()
![Uploading user-template-perms.png…]()
![Uploading user-listview.png…]()
![Uploading user-graph-perms.png…]()
![Uploading user-device-perms.png…]()

**Comment by jenhek** [comment]
![group-tree-perms](https://cloud.githubusercontent.com/assets/3381029/24078866/931ba2cc-0c79-11e7-8d81-cf71943276a6.png)
![group-template-perms](https://cloud.githubusercontent.com/assets/3381029/24078868/93437f68-0c79-11e7-8d51-e1b0d0ad67b3.png)
![group-graph-perms](https://cloud.githubusercontent.com/assets/3381029/24078869/93444574-0c79-11e7-9ea7-a31ffcb4692e.png)
![group-device-perms](https://cloud.githubusercontent.com/assets/3381029/24078870/9344bdf6-0c79-11e7-9e0c-c4270426ad53.png)
![user-treeview](https://cloud.githubusercontent.com/assets/3381029/24078872/93480f24-0c79-11e7-831e-6f12a5d4b493.png)
![user-tree-perms](https://cloud.githubusercontent.com/assets/3381029/24078871/9347d342-0c79-11e7-97fa-a81cf4d173b4.png)
![user-template-perms](https://cloud.githubusercontent.com/assets/3381029/24078867/933249be-0c79-11e7-8540-6568b0d09f8b.png)
![user-listview](https://cloud.githubusercontent.com/assets/3381029/24078873/93485b8c-0c79-11e7-9d32-74823972a92f.png)
![user-graph-perms](https://cloud.githubusercontent.com/assets/3381029/24078874/935a8654-0c79-11e7-9f32-d0cc3a275c15.png)
![user-device-perms](https://cloud.githubusercontent.com/assets/3381029/24078875/935b29ec-0c79-11e7-8448-9b88fcc63cc8.png)

**Comment by jenhek** [comment]
On 19.03.2017 05:20, Jimmy Conner wrote:
> Closed #436.
> 

Files are now attached through the webinterface.

**Comment by cigamit** [comment]
Sorry to push, we are on a deadline and trying to get as much low hanging fruit out of the way before the release, and most everything happens on the weekends.

It appears from the images above that you granted tree permissions at the group level and the graph permissions at the user level.  It also appears you are running in 'permissive mode'.  Please confirm.

**Comment by jenhek** [comment]
Yes.



Von meinem Samsung Galaxy Smartphone gesendet.


-------- Ursprüngliche Nachricht --------
Von: Jimmy Conner <notifications@github.com>
Datum: 19.03.17 13:19 (GMT+01:00)
An: Cacti/cacti <cacti@noreply.github.com>
Cc: "Hektor, Jens" <hektor@itc.rwth-aachen.de>, Author <author@noreply.github.com>
Betreff: Re: [Cacti/cacti] [Cacti 1.0.4] restricted user does not see graphs in tree view (#436)


Sorry to push, we are on a deadline and trying to get as much low hanging fruit out of the way before the release, and most everything happens on the weekends.

It appears from the images above that you granted tree permissions at the group level and the graph permissions at the user level. It also appears you are running in 'permissive mode'. Please confirm.

-

**Comment by cigamit** [comment]
Resolved in GitHub now.  Thanks for taking the time to provide reproducible details.
