### ISSUE TITLE
Some broken link on home page

### ISSUE THREAD

**Issue by elwesingollo** [Cacti/cacti#4360]
# Describe the bug

on the page https://www.cacti.net/info/downloads there are some broken link.

## To Reproduce

The link are:

Cacti

1.2.18, released Jul 05, 2021.

Linux **Windows**
https://files.cacti.net/cacti/windows/cacti-1.2.18.zip

and
Old Versions and Patches

Old versions and patches can be found in the **downloads directory.**
https://www.cacti.net/downloads/old

See error
 404 not found

**Comment by netniV** [comment]
Unfortunately, that's down to when our resident windows builder has some free time to recompile it.  @browniebraun might not even realise that we released 1.2.18.  You should be able to find .17 there.

**Comment by TheWitness** [comment]
It's just the zip file.  The `/old` link is broken.  Use to link to lot's of old downloads.

**Comment by TheWitness** [comment]
Okay, all fixed up now.  Thanks for reporting.
