### ISSUE TITLE
config.php is unreadable on RockyLinux 8.4

### ISSUE THREAD

**Issue by reeyon** [Cacti/cacti#4365]
Fresh install cacti on RockyLinux 8.4.

# Problem
When open URL http://localhost/cacti/, it shows ```Configuration file include/config.php is present, but unreadable.```

Seeking for solution. Thank you.

**Comment by reeyon** [comment]
Problem resolved.

**Comment by netniV** [comment]
This is usually a permissions problem on the server where the user running the hosting process is unable to read the config file.  Either change ownership or change permissions to allow that user read ability.
