### ISSUE TITLE
Cacti Version 0.8.8b RRDTOOL Dump the RRDTOOL RESTORE in Cacti Version 1.2.18

### ISSUE THREAD

**Issue by malkahtani** [Cacti/cacti#4366]
# Describe the bug
I am trying to migrate  Cacti Version 0.8.8b installed on CentOS 6 on ProLiant BL460c Gen9
Processor Type:	Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz using ESXi 6.5 and later (VM version 13)

To the new Cacti Release 1.2.18 on Ubuntu Linux 20.04 (64-bit) on VMware ESXi, 6.7.0, 15160138 Model:	ProLiant BL460c Gen9 Processor Type:	Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz ESXi 6.0 and later (VM version 11)

I run the script to dump RRD files to XML on  Cacti Version 0.8.8b
for rrd in `find . -type f -name "*.rrd"`
                do
                        xml=`echo $rrd | sed 's/.rrd//g'`
                        rrdtool dump $rrd > $xml.xml
                        
                done
Then I run the script to restore the RRD files from XML on Cacti Release 1.2.18
for xml in `find . -type f -name "*.xml"`
        do
                rrd=`echo $xml | sed 's/.xml//g'`
                rrdtool restore $xml $rrd.rrd
                
        done

I got these errors when restore due to bad XML dump while in Cacti Version 0.8.8b I did not get any errors during the dump. Is there any work around the eliminate these errors when I restore the files from XML?

ERROR: line 13763: expected a value but found a <v> element
/var/www/html/cacti/rra/worood_traffic_in_24064.xml:13763: parser error : Comment not terminated
                         <row><v> 9.3600000000e+00 </v><v> 9.3675555556e+00 </v></r
                                                                               ^
/var/www/html/cacti/rra/worood_traffic_in_24068.xml:13910: parser error : Opening and ending tag mismatch: row line 13910 and r
 AST / 1621123200 --> <row><v> 9.3600000000e+00 </v><v> 9.3675555556e+00 </v></r

ERROR: line 11719: parse_tag_rra: Unknown tag: row
/var/www/html/cacti/rra/wxs201-dmmqzz-a01_traffic_in_31830.xml:11833: parser error : Extra content at the end of the document
                         <row><v>
                                                                              ^
ERROR: line 11833: expected a value but found a <v> element
/var/www/html/cacti/rra/wxs201-dmmskn-001_5min_cpu_28271.xml:11719: parser error : Comment not terminated
                         <row><v> NaN </v
                                                                                      ^
ERROR: line 11606: expected a value but found a <v> element
/var/www/html/cacti/rra/wxs201-jedzhr-002_cisco_procmem_2438.xml:11775: parser error : Comment not terminated
                         <row><v> 4.1379758382e+
                                                                                             ^
ERROR: line 11795: parse_tag_rra: Unknown tag: row
/var/www/html/cacti/rra/wxs201-krjsul-a01_5min_cpu_32598.xml:11668: parser error : Comment not terminated
                         <row><v> NaN </v><v> NaN </v></row
                                                                               ^
ERROR: line 11770: parse_tag_rra: Unknown tag: row
/var/www/html/cacti/rra/wxs201-ruhkfs-001_5min_cpu_2458.xml:11719: parser error : Comment not terminated
                         <row><v> NaN </v><v> NaN </v></row
                                                                               ^
ERROR: line 11818: parse_tag_rra: Unknown tag: row
/var/www/html/cacti/rra/wxs201-ruhrwb-001_cisco_procmem_29077.xml:11719: parser error : Comment not terminated
                         <row><v>
                                                                              ^
ERROR: line 11550: expected a value but found a <v> element
/var/www/html/cacti/rra/_kacst_5th_cn_5min_cpu_37861.xml:11784: parser error : Comment not terminated
                        <!-- 2020-01-14 03:00:00 A
                                                  ^
ERROR: line 11784: parse_tag_rra: Unknown tag: row
/var/www/html/cacti/rra/_kacst_5th_cn_procmem_37862.xml:11719: parser error : Comment not terminated
                        <!-- 202
                                ^
ERROR: line 11719: parse_tag_rra: Unknown tag: row
/var/www/html/cacti/rra/adina_pop_traffic_in_19471.xml:1: parser error : Extra content at the end of the document

^
ERROR: error reading/parsing XML: Extra content at the end of the document

After these ERRORS, when I try to browse the new Cacti "Cacti Version 1.2.18" in my browser I get this error which was not there!

cat: /var/www/html/log/cacti.log: No such file or directory

**Comment by malkahtani** [comment]
[cacti-errors.txt](https://github.com/Cacti/cacti/files/6982666/cacti-errors.txt)
in text file readable errors

**Comment by netniV** [comment]
Unfortunately, we don't actively provide support for RRDtool itself.  That is Tobias' code, so if there is a problem between his export and import, it's worth checking over on the RRDtool's github page at https://github.com/oetiker/rrdtool-1.x

**Comment by TheWitness** [comment]
This is definitely an RRDtool issue.  I'm just wondering why you exported from the earlier version of RRDtool?  Was it due to an architecture change like ARM to PPC64 or an Endian change from Big to Little?  If either of those cases are not valid, there would be ZERO reason to export the RRDfiles.  I think we should close this one.  You can continue to comment though.
