### ISSUE TITLE
[Cacti 1.0.4] User Management - General - Authentication Realm - Dropdown

### ISSUE THREAD

**Issue by jenhek** [Cacti/cacti#437]
There are no texts in the dropdowm menu for

User Management - General - Authentication Realm

**Comment by cigamit** [comment]
This is resolved in 1.0.6.  If using ldap, you will have to add one more unreleased file from the development branch.  Please review the changelog.

**Comment by jenhek** [comment]
Am 16.03.2017 um 14:06 schrieb Jimmy Conner:
> This is resolved in 1.0.6.  If using ldap, you will have to add one more unreleased file from the development branch.  Please review the changelog.
> 

ACK. Done. Works.

-- 
Dipl.-Phys. Jens Hektor, Networks
IT Center, RWTH Aachen University
Room 2.04, Wendlingweg 10, 52074 Aachen (Germany)
Phone: +49 241 80 29206 - Fax: +49 241 80 22100
http://www.itc.rwth-aachen.de - hektor@itc.rwth-aachen.de
