### ISSUE TITLE
cacti Poller not running , no graph appears

### ISSUE THREAD

**Issue by youyou14** [Cacti/cacti#4371]
Hi,

i am new to use cacti
i have just installed cacti on ubuntu server 20.04 LTS
cacti : v 1.2.18
spine : 1.2.18

i have no graph on my cacti , 
![image](https://user-images.githubusercontent.com/18118455/130085019-d8e4e88f-b546-445d-a283-5e76d831d980.png)

the sudo ls -l /var/www/html/cacti/ give this result : 

 ubuntu@ubuntu:~$ sudo ls -l /var/www/html/cacti/
[sudo] password for ubuntu:
total 2764
-rwxr-xr-x 1 www-data www-data 237017 Jul  4 21:29 CHANGELOG
-rwxr-xr-x 1 www-data www-data  15171 Jul  4 21:29 LICENSE
-rwxr-xr-x 1 www-data www-data  11317 Jul  4 21:29 README.md
-rwxr-xr-x 1 www-data www-data   4341 Jul  4 21:29 about.php
-rwxr-xr-x 1 www-data www-data  62971 Jul  4 21:29 aggregate_graphs.php
-rwxr-xr-x 1 www-data www-data  18515 Jul  4 21:29 aggregate_items.php
-rwxr-xr-x 1 www-data www-data  25705 Jul  4 21:29 aggregate_templates.php
-rwxr-xr-x 1 www-data www-data  14674 Jul  4 21:29 auth_changepassword.php
-rwxr-xr-x 1 www-data www-data  30295 Jul  4 21:29 auth_login.php
-rwxr-xr-x 1 www-data www-data  18903 Jul  4 21:29 auth_profile.php
-rwxr-xr-x 1 www-data www-data  24203 Jul  4 21:29 automation_devices.php
-rwxr-xr-x 1 www-data www-data  36742 Jul  4 21:29 automation_graph_rules.php
-rwxr-xr-x 1 www-data www-data  42897 Jul  4 21:29 automation_networks.php
-rwxr-xr-x 1 www-data www-data  31517 Jul  4 21:29 automation_snmp.php
-rwxr-xr-x 1 www-data www-data  18771 Jul  4 21:29 automation_templates.php
-rwxr-xr-x 1 www-data www-data  38723 Jul  4 21:29 automation_tree_rules.php
-rwxr-xr-x 1 www-data www-data   2959 Jul  4 21:29 boost_rrdupdate.php
drwxr-xr-x 6 www-data www-data   4096 Jul  4 21:29 cache
-rw-r--r-- 1 www-data www-data 112204 Jul  5 01:28 cacti-spine-1.2.18.tar.gz
-rwxr-xr-x 1 www-data www-data 125565 Jul  4 21:29 cacti.sql
-rwxr-xr-x 1 www-data www-data   7302 Jul  4 21:29 cactid.php
-rwxr-xr-x 1 www-data www-data  29268 Jul  4 21:29 cdef.php
drwxr-xr-x 2 www-data www-data   4096 Jul  4 21:29 cli
-rwxr-xr-x 1 www-data www-data   1934 Jul  4 21:29 clog.php
-rwxr-xr-x 1 www-data www-data   1940 Jul  4 21:29 clog_user.php
-rwxr-xr-x 1 www-data www-data  30872 Jul  4 21:29 cmd.php
-rwxr-xr-x 1 www-data www-data   8843 Jul  4 21:29 cmd_realtime.php
-rwxr-xr-x 1 www-data www-data  24290 Jul  4 21:29 color.php
-rwxr-xr-x 1 www-data www-data  24859 Jul  4 21:29 color_templates.php
-rwxr-xr-x 1 www-data www-data  13259 Jul  4 21:29 color_templates_items.php
-rwxr-xr-x 1 www-data www-data  34390 Jul  4 21:29 data_debug.php
-rwxr-xr-x 1 www-data www-data  35478 Jul  4 21:29 data_input.php
-rwxr-xr-x 1 www-data www-data  49787 Jul  4 21:29 data_queries.php
-rwxr-xr-x 1 www-data www-data  36236 Jul  4 21:29 data_source_profiles.php
-rwxr-xr-x 1 www-data www-data  67127 Jul  4 21:29 data_sources.php
-rwxr-xr-x 1 www-data www-data  44122 Jul  4 21:29 data_templates.php
drwxr-xr-x 3 www-data www-data   4096 Jul  4 21:30 docs
drwxr-xr-x 2 www-data www-data   4096 Jul  4 21:29 formats
-rwxr-xr-x 1 www-data www-data  14317 Jul  4 21:29 gprint_presets.php
-rwxr-xr-x 1 www-data www-data  21985 Jul  4 21:29 graph.php
-rwxr-xr-x 1 www-data www-data   5764 Jul  4 21:29 graph_image.php
-rwxr-xr-x 1 www-data www-data   9136 Jul  4 21:29 graph_json.php
-rwxr-xr-x 1 www-data www-data  17544 Jul  4 21:29 graph_realtime.php
-rwxr-xr-x 1 www-data www-data  38698 Jul  4 21:29 graph_templates.php
-rwxr-xr-x 1 www-data www-data   9524 Jul  4 21:29 graph_templates_inputs.php
-rwxr-xr-x 1 www-data www-data  26042 Jul  4 21:29 graph_templates_items.php
-rwxr-xr-x 1 www-data www-data  31964 Jul  4 21:29 graph_view.php
-rwxr-xr-x 1 www-data www-data  12267 Jul  4 21:29 graph_xport.php
-rwxr-xr-x 1 www-data www-data  88384 Jul  4 21:29 graphs.php
-rwxr-xr-x 1 www-data www-data  26907 Jul  4 21:29 graphs_items.php
-rwxr-xr-x 1 www-data www-data  32811 Jul  4 21:29 graphs_new.php
-rwxr-xr-x 1 www-data www-data  65137 Jul  4 21:29 host.php
-rwxr-xr-x 1 www-data www-data  30239 Jul  4 21:29 host_templates.php
drwxr-xr-x 2 www-data www-data   4096 Jul  4 21:29 images
drwxr-xr-x 8 www-data www-data   4096 Aug 19 12:32 include
-rwxr-xr-x 1 www-data www-data   5721 Jul  4 21:29 index.php
drwxr-xr-x 4 www-data www-data   4096 Jul  4 21:29 install
drwxr-xr-x 2 www-data www-data   4096 Jul  4 21:29 lib
-rwxr-xr-x 1 www-data www-data   3495 Jul  4 21:29 link.php
-rwxr-xr-x 1 www-data www-data  21883 Jul  4 21:29 links.php
drwxr-xr-x 4 www-data www-data   4096 Jul  4 21:29 locales
drwxr-xr-x 2 www-data www-data   4096 Aug 19 12:42 log
-rwxr-xr-x 1 www-data www-data   4666 Jul  4 21:29 logout.php
-rwxr-xr-x 1 www-data www-data  38080 Jul  4 21:29 managers.php
drwxr-xr-x 2 www-data www-data   4096 Jul  4 21:29 mibs
-rwxr-xr-x 1 www-data www-data   3411 Jul  4 21:29 permission_denied.php
drwxr-xr-x 8 www-data www-data   4096 Aug 19 12:36 plugins
-rwxr-xr-x 1 www-data www-data  24647 Jul  4 21:29 plugins.php
-rwxr-xr-x 1 www-data www-data  33750 Jul  4 21:29 poller.php
-rwxr-xr-x 1 www-data www-data  38479 Jul  4 21:29 poller_automation.php
-rwxr-xr-x 1 www-data www-data  35597 Jul  4 21:29 poller_boost.php
-rwxr-xr-x 1 www-data www-data   7095 Jul  4 21:29 poller_commands.php
-rwxr-xr-x 1 www-data www-data   8340 Jul  4 21:29 poller_dsstats.php
-rwxr-xr-x 1 www-data www-data  20172 Jul  4 21:29 poller_maintenance.php
-rwxr-xr-x 1 www-data www-data   9882 Jul  4 21:29 poller_realtime.php
-rwxr-xr-x 1 www-data www-data   8830 Jul  4 21:29 poller_recovery.php
-rwxr-xr-x 1 www-data www-data   5720 Jul  4 21:29 poller_reports.php
-rwxr-xr-x 1 www-data www-data   8381 Jul  4 21:29 poller_spikekill.php
-rwxr-xr-x 1 www-data www-data  38522 Jul  4 21:29 pollers.php
-rwxr-xr-x 1 www-data www-data  14552 Jul  4 21:29 remote_agent.php
-rwxr-xr-x 1 www-data www-data   3345 Jul  4 21:29 reports_admin.php
-rwxr-xr-x 1 www-data www-data   3246 Jul  4 21:29 reports_user.php
drwxr-xr-x 5 www-data www-data   4096 Jul  4 21:29 resource
drwxr-xr-x 2 www-data www-data   4096 Jul  4 21:29 rra
-rwxr-xr-x 1 www-data www-data  20178 Jul  4 21:29 rrdcleaner.php
-rwxr-xr-x 1 www-data www-data  11950 Jul  4 21:29 script_server.php
drwxr-xr-x 2 www-data www-data   4096 Aug 19 12:42 scripts
drwxr-xr-x 2 www-data www-data   4096 Jul  4 21:29 service
-rwxr-xr-x 1 www-data www-data  40948 Jul  4 21:29 settings.php
-rwxr-xr-x 1 www-data www-data  20567 Jul  4 21:29 sites.php
-rwxr-xr-x 1 www-data www-data   2414 Jul  4 21:29 snmpagent_mibcache.php
-rwxr-xr-x 1 www-data www-data   3688 Jul  4 21:29 snmpagent_mibcachechild.php
-rwxr-xr-x 1 www-data www-data   5510 Jul  4 21:29 snmpagent_persist.php
-rwxr-xr-x 1 www-data www-data   3969 Jul  4 21:29 spikekill.php
drwxrwxr-x 7 www-data www-data   4096 Aug 19 12:38 spine
-rwxr-xr-x 1 www-data www-data   6597 Jul  4 21:29 templates_export.php
-rwxr-xr-x 1 www-data www-data   6072 Jul  4 21:29 templates_import.php
-rwxr-xr-x 1 www-data www-data  64921 Jul  4 21:29 tree.php
-rwxr-xr-x 1 www-data www-data 103532 Jul  4 21:29 user_admin.php
-rwxr-xr-x 1 www-data www-data  29656 Jul  4 21:29 user_domains.php
-rwxr-xr-x 1 www-data www-data  87764 Jul  4 21:29 user_group_admin.php
-rwxr-xr-x 1 www-data www-data  99996 Jul  4 21:29 utilities.php
-rwxr-xr-x 1 www-data www-data  28883 Jul  4 21:29 vdef.php

my Cron  entry:

*/5 * * * * apache php /var/www/html/cacti/poller.php &>/dev/null

 my troubleshooting : 
.
![image](https://user-images.githubusercontent.com/18118455/130084634-d7192cb0-3b7d-4404-bf93-82d360481503.png)

i don't know how resolve this probleme, 
thanks for help me

**Comment by youyou14** [comment]
i had use this commande : 
`/usr/local/spine/bin$ ./spine -R -V 3 -S`

the result is : 
![image](https://user-images.githubusercontent.com/18118455/130086311-f7b65d91-ea26-4869-9016-fb30d5b945c9.png)

**Comment by youyou14** [comment]
i had use this commande : 
`mysql -ucacti -ppassword cacti`

the result is : 
![image](https://user-images.githubusercontent.com/18118455/130086678-376cebeb-7275-4827-b806-7c32472ce7eb.png)

**Comment by youyou14** [comment]
i had use this commande : 
` netstat -tlnp`

the result is : 
![image](https://user-images.githubusercontent.com/18118455/130087052-84ddc9d4-5578-4f4e-8582-2525998e6cd1.png)

**Comment by youyou14** [comment]
i had use this commande : 
`sudo  ls -al /var/www/html/cacti/rra/`

the result is : 
![image](https://user-images.githubusercontent.com/18118455/130087431-83302a01-71f1-4c69-89ee-54ff17c03a74.png)

**Comment by bmfmancini** [comment]
What does your cron entry look like?

**Comment by cigamit** [comment]
This is a misconfiguration issue, not a Cacti issue.  This tracker is for Cacti bugs.  Please continue this support discussion on the Cacti Forums  @ https://forums.cacti.net

Just from a quick look, the Cacti Troubleshooter says your webserver is using the "www-data" user, but your cron is for the "apache" user.
