### ISSUE TITLE
weathermap plugin error cacti

### ISSUE THREAD

**Issue by youyou14** [Cacti/cacti#4372]
hi, 

i am new with cacti, i had install also weathermap plugin, but i don't understand this error : 
![image](https://user-images.githubusercontent.com/18118455/130220689-ed366965-54ed-4b49-aa81-e7d097d3fc0a.png)

can any one help me please ?

**Comment by cigamit** [comment]
This is not a support forum, especially for a plugin (they have their own repos).  I see you already also posted this on the forums albeit in the wrong section, so closing this.
