### ISSUE TITLE
95th Percentile graph is reporting combined values that are unreasonably high

### ISSUE THREAD

**Issue by martinbogo** [Cacti/cacti#4374]
# Describe the bug

Cacti version : 1.2.18 - Github
OS : Debian Buster ( latest patch level and update ) 

## To Reproduce

I upgraded my Cacti installation from 1.2.2 ( Buster ) to the latest version in github ( 1.2.18 )
Databases were migrated
Graph templates were not touched ( screen shot of graph templates below ) 
Template is using 64 bit counters, and graph template seems correct.

## Expected behavior

The value for 95th percentile in+out should be much lower than the value shown. RRDTOOL graph syntax and data attached in screenshots.

Could possibly be a regression in graph_variables.php on the old issue #114?

## Screenshots

![Screen Shot 2021-08-22 at 3 27 28 PM](https://user-images.githubusercontent.com/251177/130369143-f8dda033-d595-4aea-80cf-20eaad5cec62.png)

![Screen Shot 2021-08-22 at 3 30 28 PM](https://user-images.githubusercontent.com/251177/130369208-f42c89d6-bc1b-426d-8726-67e7a9079cc8.png)

![Screen Shot 2021-08-22 at 3 31 40 PM](https://user-images.githubusercontent.com/251177/130369236-523bd13d-02d6-4002-bba9-e417c674d21f.png)

![Screen Shot 2021-08-22 at 3 32 01 PM](https://user-images.githubusercontent.com/251177/130369246-7a1c7572-b1b1-4505-880f-3853773f93d4.png)

![Screen Shot 2021-08-22 at 3 38 44 PM](https://user-images.githubusercontent.com/251177/130369395-51cf6e82-f463-4936-9691-8c23051e62cc.png)

![Screen Shot 2021-08-22 at 3 39 04 PM](https://user-images.githubusercontent.com/251177/130369397-adac0cbf-5030-4058-a24a-2ebad2caae0e.png)

**Comment by martinbogo** [comment]
Any guidance as to what might be causing this, or what other debug information may be useful to track this down, would be appreciated.

**Comment by netniV** [comment]
when it comes to 95th percentile stuff, @TheWitness is currently the expert.

**Comment by TheWitness** [comment]
I think we need to instrument the percentile function.  Let me post and updated file so you can do the instrumentation.

**Comment by TheWitness** [comment]
Edit `lib/graph_variables.php` and add the following to ~ line 35.

```php
cacti_log(json_encode($stats));
```

Post the output from that in formatted json (add some line breaks and whitespace to make it readable).

**Comment by TheWitness** [comment]
You should get something like the following:

```json
{"avg":{"traffic_in":26372.902966000001,"traffic_out":89751.810603999998,"nth_percentile_maximum":89772.993082000001,"nth_percentile_sum":111439.11666699999,"nth_percentile_aggregate_total":89751.810603999998,"stats_traffic_in":{"p95n":26372.902966000001,"p90n":22509.196415999999,"p75n":20697.608888999999,"p50n":19453.515197000001,"p25n":18305.990788999999,"average":20082.722665447003,"sum":18375691.238884009,"elements":915,"variance":15915959319.701799,"stddev":4170.6703369822208},"stats_traffic_out":{"p95n":89751.810603999998,"p90n":86727.271338999999,"p75n":24933.752221999999,"p50n":20532.351111,"p25n":18473.051111000001,"average":33764.696019419629,"sum":30894696.85776896,"elements":915,"variance":825952228205.229,"stddev":30044.633977224399},"stats_nth_percentile_maximum":{"p95n":89772.993082000001,"p90n":86749.497961000001,"p75n":25768.537778000002,"p50n":20861.588853000001,"p25n":19241.078679999999,"average":34389.723005031643,"sum":31466596.549603954,"elements":915,"variance":817699771130.62622,"stddev":29894.162508010308},"stats_nth_percentile_sum":{"p95n":111439.11666699999,"p90n":106914.171112,"p75n":47117.211110999997,"p50n":40118.126667000004,"p25n":37185.311111000003,"average":53847.41868486665,"sum":49270388.096652985,"elements":915,"variance":899556728059.00696,"stddev":31354.778059624557}},"peak":{"traffic_in":26372.902966000001,"traffic_out":89751.810603999998,"nth_percentile_maximum":89772.993082000001,"nth_percentile_sum":111439.11666699999,"nth_percentile_aggregate_total":89751.810603999998,"stats_traffic_in":{"p95n":26372.902966000001,"p90n":22509.196415999999,"p75n":20697.608888999999,"p50n":19453.515197000001,"p25n":18305.990788999999,"average":20082.722665447003,"sum":18375691.238884009,"elements":915,"variance":15915959319.701799,"stddev":4170.6703369822208},"stats_traffic_out":{"p95n":89751.810603999998,"p90n":86727.271338999999,"p75n":24933.752221999999,"p50n":20532.351111,"p25n":18473.051111000001,"average":33764.696019419629,"sum":30894696.85776896,"elements":915,"variance":825952228205.229,"stddev":30044.633977224399},"stats_nth_percentile_maximum":{"p95n":89772.993082000001,"p90n":86749.497961000001,"p75n":25768.537778000002,"p50n":20861.588853000001,"p25n":19241.078679999999,"average":34389.723005031643,"sum":31466596.549603954,"elements":915,"variance":817699771130.62622,"stddev":29894.162508010308},"stats_nth_percentile_sum":{"p95n":111439.11666699999,"p90n":106914.171112,"p75n":47117.211110999997,"p50n":40118.126667000004,"p25n":37185.311111000003,"average":53847.41868486665,"sum":49270388.096652985,"elements":915,"variance":899556728059.00696,"stddev":31354.778059624557}}} ```

**Comment by TheWitness** [comment]
Once you have posted that, let's compare the numbers to what is on the graph.

**Comment by TheWitness** [comment]
If the numbers for `avg` look correct, change text in both the COMMENT and GPRINT from `max` to `current`.

**Comment by TheWitness** [comment]
`in + out` actually implies adding both numbers and using the greatest don't you think?  I don't think `max` even does that.

**Comment by martinbogo** [comment]
Hi @TheWitness

Will do when I get into work on Monday.

-M

**Comment by TheWitness** [comment]
It's almost Tuesday @martinbogo

**Comment by TheWitness** [comment]
It's Thursday @martinbogo ;)

**Comment by TheWitness** [comment]
@martinbogo, back in your court Martin!

**Comment by TheWitness** [comment]
There has been no feedback in a while on this, so I just closed.
