### ISSUE TITLE
SNMP Agent may not find a cache item

### ISSUE THREAD

**Issue by Plinio16** [Cacti/cacti#4382]
I am presenting an issue with Cacti/Spine, it is showing gaps between graphs. The error as the Log shows:

[quote]2021-08-28 21:15:00 - CMDPHP PHP ERROR NOTICE Backtrace: (/poller.php[705]:snmpagent_poller_exiting(), /lib/snmpagent.php[303]:CactiErrorHandler())
2021-08-28 21:15:00 - ERROR PHP NOTICE: Trying to access array offset on value of type bool in file: /opt/cacti/lib/snmpagent.php on line: 303
2021-08-28 21:15:00 - CMDPHP PHP ERROR NOTICE Backtrace: (/poller.php[705]:snmpagent_poller_exiting(), /lib/snmpagent.php[302]:CactiErrorHandler())
2021-08-28 21:15:00 - ERROR PHP NOTICE: Trying to access array offset on value of type bool in file: /opt/cacti/lib/snmpagent.php on line: 302[/quote]

Local Machine
[url=https://postimg.cc/mcRJmY3V][img]https://i.postimg.cc/mcRJmY3V/cacti.png[/img][/url]

A CIsco Device
[url=https://postimg.cc/Z9cg2WVm][img]https://i.postimg.cc/Z9cg2WVm/cacti1.png[/img][/url]

Server Details:

Date	Sat, 28 Aug 2021 21:21:18 -0500
Cacti Version	1.2.16
Cacti OS	unix
RSA Fingerprint	ad:68:21:6f:8f:06:f0:6e:e3:7c:26:58:1e:03:91:b8
NET-SNMP Version	NET-SNMP version: 5.8
RRDtool Version Configured	1.7.2+
RRDtool Version Found	1.7.2
Devices	584
Graphs	2,217
Data Sources	SNMP Get: 591
SNMP Query: 1,047
Script/Command: 1,167
Total: 2,805

Interval	300
Type	SPINE 1.2.16 Copyright 2004-2020 by The Cacti Group
Items	Action[0]: 2,685
Action[1]: 1,167
Total: 3,852
Concurrent Processes	Name: Main Poller, Procs: 1
Max Threads	Name: Main Poller, Threads: 1
PHP Servers	1
Minimum Connections:	Current: 5000, Min Required: 102
Assumes 100 spare connections for Web page users and other various connections.
The minimum required can vary greatly if there is heavy user Graph viewing activity.
Each browser tab can use upto 10 connections depending on the browser.
Script Timeout	25
Max OID	10
Last Run Statistics	Time:298.5048 Method:spine Processes:1 Threads:1 Hosts:584 HostsPerProcess:584 DataSources:3852 RRDsProcessed:2307

**Comment by bmfmancini** [comment]
What PHP version are you using ?

**Comment by Plinio16** [comment]
![image](https://user-images.githubusercontent.com/46384343/131265310-4662dad9-c7ba-415b-bdf0-321b028f58b5.png)

**Comment by bmfmancini** [comment]
And is this happening every poll cycle?
Check your logs for any poller time exceeding messege

**Comment by netniV** [comment]
I've pushed a change to correct the error but the reason is that the poller is overrunning I believe.

**Comment by TheWitness** [comment]
This would appear to be a correct change.

**Comment by TheWitness** [comment]
@Plinio16, please pull a fresh copy of `lib/snmpagent.php` from the 1.2.x branch and report back on your findings.
