### ISSUE TITLE
Test mail is not send

### ISSUE THREAD

**Issue by adfire** [Cacti/cacti#439]
When sending test mail I get an error:

Sending Message...

SMTP Error: The following recipients failed: <mail_address>: : Sender address rejected: Domain not found

and in log there is an error: postifx (smtp server address) connection refused.

The same happens reagrdless of what smtp service (or account) is selected.

Cacti ver. 1.0.4, 1.0.5 and 1.0.6.

**Comment by cigamit** [comment]
This is not a Cacti issue.  Read the error 'Domain not found'.  That is not something that Cacti is generating.
