### ISSUE TITLE
The plugin API should detect when plugins are not behaving properly with return variables required for chaining

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#4390]
# Describe the bug

The Cacti plugin API is dependent on plugin authors returning certain structures to be used by other plugin authors.  These structures should ALWAYS be returned.  Otherwise errors can be thrown by plugins that assume that they are set.

In the event this happens, Cacti should make every effort to detect this and warn the user who can then either correct this issue, or report it to the plugin maintainer.

## Expected behavior

Cacti should do a better job of detecting cases where plugin authors are not using good form when authoring plugins.

## Screenshots

Below is an example of the new error that will be logged in the case of a chaining event when there is greater than one plugin using the hook function.

![image](https://user-images.githubusercontent.com/1439914/132244505-1f8939f5-9add-4f2b-b433-298750fc8642.png)

**Comment by TheWitness** [comment]
The WARNINGS above are just an example.  Since this plugin was the only plugin calling the hook, it will not generate a warning even though it is using bad form.

**Comment by jdcoats** [comment]
So after updating, I noticed that the monitor plugin no longer showed the monitor tab. I disabled monitor and re-enabled and got your warnings. So syslog, monitor and weathermap need some love.
```
2021/09/06 16:24:18 - CMDPHP WARNING: Plugin hook 'syslog_top_graph_refresh' from Plugin 'syslog' must return the calling array or variable, and it is not doing so. Please report this to the Plugin author.
2021/09/06 16:24:18 - CMDPHP WARNING: Plugin hook 'weathermap_top_graph_refresh' from Plugin 'weathermap' must return the calling array or variable, and it is not doing so. Please report this to the Plugin author.
2021/09/06 16:24:18 - CMDPHP WARNING: Plugin hook 'monitor_top_graph_refresh' from Plugin 'monitor' must return the calling array or variable, and it is not doing so. Please report this to the Plugin author.
2021/09/06 16:24:16 - CMDPHP WARNING: Plugin hook 'syslog_top_graph_refresh' from Plugin 'syslog' must return the calling array or variable, and it is not doing so. Please report this to the Plugin author.
2021/09/06 16:24:16 - CMDPHP WARNING: Plugin hook 'weathermap_top_graph_refresh' from Plugin 'weathermap' must return the calling array or variable, and it is not doing so. Please report this to the Plugin author.
2021/09/06 16:24:14 - CMDPHP WARNING: Plugin hook 'syslog_top_graph_refresh' from Plugin 'syslog' must return the calling array or variable, and it is not doing so. Please report this to the Plugin author.
2021/09/06 16:24:14 - CMDPHP WARNING: Plugin hook 'weathermap_top_graph_refresh' from Plugin 'weathermap' must return the calling array or variable, and it is not doing so. Please report this to the Plugin author.
2021/09/06 16:24:14 - CMDPHP WARNING: Plugin hook 'monitor_top_graph_refresh' from Plugin 'monitor' must return the calling array or variable, and it is not doing so. Please report this to the Plugin author.
2021/09/06 16:24:06 - CMDPHP WARNING: Plugin hook 'syslog_top_graph_refresh' from Plugin 'syslog' must return the calling array or variable, and it is not doing so. Please report this to the Plugin author.
2021/09/06 16:24:06 - CMDPHP WARNING: Plugin hook 'weathermap_top_graph_refresh' from Plugin 'weathermap' must return the calling array or variable, and it is not doing so. Please report this to the Plugin author.
2021/09/06 16:24:06 - CMDPHP WARNING: Plugin hook 'monitor_top_graph_refresh' from Plugin 'monitor' must return the calling array or variable, and it is not doing so. Please report this to the Plugin author.
2021/09/06 16:23:25 - CMDPHP WARNING: Plugin hook 'syslog_top_graph_refresh' from Plugin 'syslog' must return the calling array or variable, and it is not doing so. Please report this to the Plugin author.
2021/09/06 16:23:25 - CMDPHP WARNING: Plugin hook 'weathermap_top_graph_refresh' from Plugin 'weathermap' must return the calling array or variable, and it is not doing so. Please report this to the Plugin author.
2021/09/06 16:23:25 - CMDPHP WARNING: Plugin hook 'monitor_top_graph_refresh' from Plugin 'monitor' must return the calling array or variable, and it is not doing so. Please report this to the Plugin author.
```

**Comment by TheWitness** [comment]
Okay.  Let me dig in to these.

**Comment by netniV** [comment]
Part of the functionality of the api was that a plugin can effectively cancel a hook by returning false.  As such, I do not think we should be reporting this warnings except at a debug level or maybe high at a push.  It's been useful to have it log always here as we have had immediate feedback from @jdcoats (tanks for that!) but we should current the logging level for release.

**Comment by TheWitness** [comment]
@jdcoats, can you post the contents of this function `weathermap_top_graph_refresh`?

**Comment by TheWitness** [comment]
In the case of the top_graph_refresh, an array is sent in, but an integer is sent back.  So, the test case would be `null` only I think.

**Comment by jdcoats** [comment]
```
    function weathermap_top_graph_refresh( $refresh )
    {
        if ( basename( $_SERVER[ "PHP_SELF" ] ) != "weathermap-cacti-plugin.php" )
            return $refresh;

        // if we're cycling maps, then we want to handle reloads ourselves, thanks
        if ( isset( $_REQUEST[ "action" ] ) && $_REQUEST[ "action" ] == 'viewmapcycle' ) {
            return ( 86400 );
        }
        return ( $refresh );
    }
```

**Comment by TheWitness** [comment]
It's bad logic in the `lib/plugins.php` commit something later tonight.  Keep an eye out.

**Comment by TheWitness** [comment]
Should be all set now.

**Comment by jdcoats** [comment]
updated and warnings are gone, will continue on testing.

**Comment by netniV** [comment]
Commit 63e1998 is still wrong.  As I commented on there, there are scenario's where the changing of the return value type between array and string is expected and desired.

**Comment by netniV** [comment]
Why has this been closed without addressing the above?

**Comment by TheWitness** [comment]
Re-read my comment.  We need to log a new issue.  This one is closed for the reasons I stated above.

**Comment by netniV** [comment]
You haven't stated any reason above, just that it's all set.  I'm going to assume that the $result only kicks in if there are more than one listeners for a given hook?  But if that's the case, that would be better as the outer IF statement since it's less complex and not as likely to be true unless you have a lot of plugins that all use the same hook.

**Comment by TheWitness** [comment]
Yea, it was in the commit comment.  Sorry about that.

**Comment by netniV** [comment]
That's OK, just trying to make sure we are both following things correctly and not missing something.  My understanding of the hooks logic there has changed each time I read it but I think I have it now.  It will be curious to see who exactly does see the warning.
