### ISSUE TITLE
95th percentile values are wrong

### ISSUE THREAD

**Issue by LukeB42** [Cacti/cacti#4394]
We're having the exact same issue as issue [#4212](https://github.com/Cacti/cacti/issues/4212) but the fix outlined in that thread isn't working.

Can this be fixed for the next release, please?

**Comment by TheWitness** [comment]
See my notes in the other ticket.  There was a behavior change.  Change the value in the from `max` to `current`, and I'm pretty sure you will get the values you are looking for.
