### ISSUE TITLE
Two tables 'poller_output_boost_processes' and 'poller_output_realtime' are missing

### ISSUE THREAD

**Issue by kim-fitness** [Cacti/cacti#4396]
# Describe the bug

In cacti log, it reports that poller_output_boost_processes, poller_output_realtime are missing on the database server

## To Reproduce

Cannot reproduce

## Additional context
We can make en enhancement in the poller.php to check those two tables' existence (`poller_output_boost_processes` and `poller_output_realtime`). Just like what we have done for table `poller_output_boost` as following
```
// catch the unlikely event that the poller_output_boost is missing
if (!db_table_exists('poller_output_boost')) {
	db_execute('CREATE TABLE poller_output_boost LIKE poller_output');
	db_execute('ALTER TABLE poller_output_boost ENGINE=InnoDB');
}
```

**Comment by bmfmancini** [comment]
I haven't seen this before

What version are you on?
Was it a fresh install or upgrade

I like the idea though

**Comment by kim-fitness** [comment]
>I haven't seen this before

>What version are you on?
>Was it a fresh install or upgrade

>I like the idea though
Hi @bmfmancini ,
It's a fresh installed 1.2.17.

Let me make a PR then.

**Comment by TheWitness** [comment]
@kim-fitness, I have not reviewed yet.  Thanks for the contribution.

**Comment by TheWitness** [comment]
I have merged this one.  Thanks!

**Comment by miquelmartos** [comment]
Hello,
This commit breaks the syntax of php.
Double quote must be used to set the default values. 

```
php /opt/cacti/poller.php
PHP Parse error:  syntax error, unexpected '',' (T_CONSTANT_ENCAPSED_STRING), expecting ',' or ')' in /opt/cacti/poller.php on line 217
```
```diff --git a/poller.php b/poller.php
index 341f28d88..61aa1a892 100755
--- a/poller.php
+++ b/poller.php
@@ -212,11 +212,11 @@ if (!db_table_exists('poller_output_boost_processes')) {
 // catch the unlikely event that the poller_output_realtime is missing
 if (!db_table_exists('poller_output_realtime')) {
        db_execute('CREATE TABLE poller_output_realtime (
-               local_data_id mediumint(8) unsigned NOT NULL default '0',
-               rrd_name varchar(19) NOT NULL default '',
-               `time` timestamp NOT NULL default '0000-00-00 00:00:00',
+               local_data_id mediumint(8) unsigned NOT NULL default "0",
+               rrd_name varchar(19) NOT NULL default "",
+               `time` timestamp NOT NULL default "0000-00-00 00:00:00",
                output text NOT NULL,
-               poller_id varchar(256) NOT NULL default '1',
+               poller_id varchar(256) NOT NULL default "1",
                PRIMARY KEY (local_data_id, rrd_name, time, poller_id),
                KEY poller_id (poller_id(191)),
                KEY `time` (`time`))
```

**Comment by TheWitness** [comment]
Thanks and upon further review, there are additional issues.

**Comment by TheWitness** [comment]
Please review the latest commit and comment.  Our Travis commit check has been down for a while and that allowed a few of these issues to creep in.  There was another syntax error corrected just last week that slipped through the cracks.
