### ISSUE TITLE
Windows Download 404

### ISSUE THREAD

**Issue by EanNewton** [Cacti/cacti#4401]
The link to your download for the Windows installer from the https://www.cacti.net/info/downloads page 404's 

https://files.cacti.net/cacti/windows/cacti-1.2.18.zip

**Comment by TheWitness** [comment]
Duplicate of #4360

**Comment by TheWitness** [comment]
Should be fixed now.

**Comment by EanNewton** [comment]
Confirmed to be working, thank you!
