### ISSUE TITLE
Cacti having issues detecting client timezones

### ISSUE THREAD

**Issue by alcatron** [Cacti/cacti#4403]
Im running Cacti 1.2.17 and Centos 8, if I enable SSL on apache, the RRD graphs are -30minutes behind, however if i just go in via plain HTTP, the graphs show the correct time.

I have 2 systems with the issue - Apache/2.4.37 (centos) with Centos 8, and Redhat Enterprise 8.4 with Apache/2.4.37

On regular http graph time shows correct when i zoom in the last 2 hours or so, on the https when i zoom in the time is off by 30mins

I had a PHP developer look at everything and everything in PHP turned out to the fine as well as SQL.
The actual problem is in cacti and cookie timezone calculation

I commented out the following lines below, and once this was taken out the RRD axis graphs showed the correct time and were not offset by minus 30minutes.

/usr/share/cacti/include/global.php - Line 550

```
/* Commented out due to graph time issues
        if (isset($_COOKIE['CactiTimeZone'])) {
                $minutes = $_COOKIE['CactiTimeZone'];
                $hours   = $minutes / 60;

                putenv('TZ=GMT' . ($hours > 0 ? '-':'+') . abs($hours));
                ini_set('date.timezone', 'Etc/GMT' . ($hours > 0 ? '-':'+') . abs($hours));
        }
*/
```

**Comment by TheWitness** [comment]
What is your pollers time zone?  You have to edit the data collector to see the value.

**Comment by alcatron** [comment]
poller timezone is set same as php, and is showing correct, no issues seen with poller timezone.

**Comment by TheWitness** [comment]
The way that this works is that your relative time, based upon your PC is passed back to the server and used as an offset.  So what is in that cookie?  Can you print it out into the cacti log?

**Comment by TheWitness** [comment]
Off by 30 minutes.  Yea, show us the output.

**Comment by alcatron** [comment]
Only The RRD graphs Axis is affected by -30mins when zooming in, all other time is fine, even the time that is stamped below the graph is fine, and only occurs for HTTPS request.

This is what the developer told me is happening:

For https request as example what the browser is interpreting:
_Cookie:
CactiTimeZone=330; Cacti=cqsf7748usoerjllkhr1lib7do; CactiDateTime=Wed Sep 15 2021 22:11:11 GMT+0530 (India Standard Time)_

For http request :
_Cookie:
Cacti=or8is0j5b48kbuoj5vg7gfp42u_

_Cookie 'secure' only set with https and not with http so that was the issue
So cookie. ie set by http can't be accessible by https or vice-versa_

HTTPS cookie secure was re-calculating the timezone, when HTTP was not

_This is part of the code thats causing the issue for some reason, and hashed it out.
ini_set('date.timezone', 'Etc/GMT' . ($hours > 0 ? '-':'+') . abs($hours));_

Happy to ask further clarity what is going on, but thats what i was advised.

**Comment by bmfmancini** [comment]
I can't seem to recreate this 

Can you post a sample or what your graph looks like?

**Comment by TheWitness** [comment]
He's likely in a timeline where the offset is a half hour from Zulu.

**Comment by TheWitness** [comment]
There are only a few places in the world this is true, one of course is IST.  I was hoping to be able to detect the clients timezone, but we may have to ask it instead, which is a pain.  I'm going to do a small patch in the mean time.

**Comment by TheWitness** [comment]
Okay, handling IST and the others better now.  I don't like it, but it's better than nothing.

**Comment by alcatron** [comment]
The PHP developer based in india, however i am also based in AEST timezone Australia, which is offset by 30mins, i think something with -30mins was having an issue

**Comment by TheWitness** [comment]
Yea, you have to pull lib/functions.php and include/global.php from the 1.2.x branch, and you should be all set.

**Comment by alcatron** [comment]
alright, out of interest, what kind of change did you have to make in the code?

**Comment by netniV** [comment]
You can see the changes above by looking at the differences of the commits.
