### ISSUE TITLE
Can't find out the associated graph template when add data queries

### ISSUE THREAD

**Issue by manhvu1997** [Cacti/cacti#4406]
# Describe the bug
Hello,
I followed the documentation on the cacti website to install cacti 1.2.16. However I have an issue, I can't found out the associated graph template when add data queries  

## To Reproduce

1. I added a new data input method:
https://imgur.com/a/CMgSCum
2. I added a new data source template
https://imgur.com/a/nirOJrM
3. Then, I added a new graph template and it's name is "Juniper Drop Queue"
https://imgur.com/a/Jzc7gYh
4. However, when I added data queries, I can't found the the template has just been added in previous step
https://imgur.com/a/ck4Ynmb
## Expected behavior

I hope you can help me to fix that bug soon

## Hardware

- OS: Centos7

- Mariadb:10.6.4

- Httpd: 2.4.6
- PHP: 7.4.23
- rrdtool: 1.4.8
- NetSNMP: 5.7.2
Thanks and waiting for your reply soon

**Comment by netniV** [comment]
I had a similar issue.  If you note the graph template ID, can you try the following query for me?
```sql
select * from snmp_query_graph where graph_template_id = <graph_template_id>
```

Since you have a data input method, that's not based on SNMP OID's, I think it shouldn't be in that table.

**Comment by TheWitness** [comment]
The reason that it is not shown is that your Data Input Method is not a Data Query based one.  So, it's a rookie error.  No worries.  What you should always remember.  A script can query multiple items in one sweep with output as follows:

`name1:value1 name2:value2 ...`

But, this is not true for a Data Query.  Data Queries, if you use a script, will always grab the items one at a time using the `get` action.  So, much different than a classic script or script server based data input methods, which do not apply to Data Queries.

So, not a biggie.  You will figure it out in time.
