### ISSUE TITLE
Misspelling in SNMP Authentication

### ISSUE THREAD

**Issue by camerabob** [Cacti/cacti#4407]
See "Authenticaion"

![mispelling](https://user-images.githubusercontent.com/25908052/134521757-006d146c-aee3-4f55-8a05-cad1f98956d7.png)

**Comment by netniV** [comment]
So I did a search and the only place in the php files that I found this was in the 0_8_7.php.  If you look through your sources, can you find any more locations?

**Comment by netniV** [comment]
If you try the SQL above then it should correct it.

**Comment by TheWitness** [comment]
Just confirming that we don't have to update the Device Templates for this change to stick as those SNMP Input methods are immutable during import.
