### ISSUE TITLE
Translation 

### ISSUE THREAD

**Issue by aydinmu** [Cacti/cacti#441]
Hi,

How can we add new language to cacti ? 

İf you say how i make it i can translate english to other language?

Best regards.

**Comment by browniebraun** [comment]
For different languages we are using the GNU/Gettext format.
Under "cacti/locales/po/" you will find the portable object template called "cacti.pot". This file will be updated by us whenever GUI text has been added or modified. You can use one of the different free editors being available ( for example I'm using PoEdit) to read in our .pot file and to generate a custom human readable file like "german_germany.po" as well as a binary (.mo) that will both include your translations.
Last step would be a pull request to add your files to the Cacti branch.

Regards
-Andi

**Comment by cigamit** [comment]
Please refer to the following Link.  If using Windows I suggest you provide $20 to the author for the advanced features.  It's a fair price.

https://github.com/Cacti/cacti/wiki/How-to-Create-a-Translation

Thanks!

**Comment by aydinmu** [comment]
thank you all . i can try to finish as soon as possible.

**Comment by browniebraun** [comment]
We have to thank you for volunteering!

Regards
-Andi
