### ISSUE TITLE
Remote Pollers - Support execution of custom functions at poller bottom

### ISSUE THREAD

**Issue by browniebraun** [Cacti/cacti#4417]
# Feature Request

Hook 'poller_finishing' could probably used for that approach too, but I'm wondering why we are not supporting a hook to perform individual plugin tasks at the bottom of a remote poller run.

The current code of poller.php does not take this case into account - If I'm not totally wrong. From my point of view a remote poller is not just stupid collector. It should be workhorse.

```
`/* start post data processing */
if ($poller_id == 1) {
	multiple_poller_boost_check();
	poller_replicate_check();
	snmpagent_poller_bottom();
	boost_poller_bottom();
	dsstats_poller_bottom();
	dsdebug_poller_bottom();
	reports_poller_bottom();
	spikekill_poller_bottom();
	automation_poller_bottom();
	poller_maintenance();
	api_plugin_hook('poller_bottom');
	bad_index_check($mibs);
} else {
	// flush the boost table if in recovery mode
	if ($poller_id > 1 && $config['connection'] == 'recovery') {
		cacti_log('NOTE: Remote Data Collection to force processing of boost records.', true, 'POLLER');
		poller_recovery_flush_boost($poller_id);
	}
	automation_poller_bottom();
	poller_maintenance();
}
`
```

**Comment by bmfmancini** [comment]
Hahaha!! It too me a second this made. My morning

**Comment by browniebraun** [comment]
lol. Already done. Damn! I'm old and gray. 😉

**Comment by TheWitness** [comment]
I'm half past dead.  @bmfmancini did we kind of already get this one with the changes for syslog?

**Comment by netniV** [comment]
Currently poller.php has two hooks for `poller_bottom` but doesn't pass data to suggest which place it's calling from (in the loop or out of it).

**Comment by TheWitness** [comment]
Okay, new hook in `poller_maintenance.php` called `poller_remote_maint` and only run on Remote Data Collectors.  Documentation site updated as well.
