### ISSUE TITLE
Plugin Install Issue Version 1.0.6 

### ISSUE THREAD

**Issue by jagmeetbhinder** [Cacti/cacti#442]
I am sorry if this is not the right place to report an issue for general users. I tried all the forums and I don't see any solution. I have installed cacti 1.0.6 and I am trying to install plugins monitor and getting below error. I am experiencing same issues with other plugins as well.

Validation error for variable id, with value of "plugin_monitor". See backtrace below for more details.
(/plugins.php: 51 get_filter_request_var)(/lib/html_utility.php: 430 die_html_input_error)(/lib/html_validate.php: 60 cacti_debug_backtrace)

Here are my environment details:
NET-SNMP Version 	NET-SNMP version: 5.5 
Spine                        SPINE 1.0.6 
PHP Version 	         5.3.3
MySQl                        5.6
Cacti Install                 '/'
OS                              Centos 6.X

Again, I am sorry if this is not the right place to post an issue for general users. Just let me know and I will withdraw the issue.

**Comment by cigamit** [comment]
Rename the directory to 'monitor'.  If you read the readme it tells you to do this.
