### ISSUE TITLE
data remains in poller_output table even if it's flushed to rrd files

### ISSUE THREAD

**Issue by gj00354347** [Cacti/cacti#4422]
Hi Team ,

we are on cacti 1.2.18 and we see a strange behaviour of cacti . Like for some of the data sources we have in poller_output we see those data have been flushed to rrd files but still they are there in poller_table .
on seeing the graphs for the impacted data source we see they are well populated which proves that data is already flushed .Lets say for a local_data_id 284832 we have data from 28 sept 2021 till 14 oct 2021 . but the graph is also populated for the same period .

---------------+-------------+---------------------+--------------+
| local_data_id | rrd_name    | time                | output       |
+---------------+-------------+---------------------+--------------+
|        284832 | traffic_out | 2021-09-28 13:46:53 | 271765179574 |
|        284832 | traffic_in  | 2021-09-28 13:46:53 | 38562284240  |
|        284832 | traffic_in  | 2021-09-28 13:51:52 | 38562321567  |
|        284832 | traffic_out | 2021-09-28 13:51:52 | 271765253715 |
|        284832 | traffic_out | 2021-09-28 13:56:51 | 271765327439 |
|        284832 | traffic_in  | 2021-09-28 13:56:51 | 38562358875  |
|        284832 | traffic_in  | 2021-09-28 14:01:51 | 38562396204  |
|        284832 | traffic_out | 2021-09-28 14:01:51 | 271765401261 |
|        284832 | traffic_in  | 2021-09-28 14:06:51 | 38562433761  |
|        284832 | traffic_out | 2021-09-28 14:06:51 | 271765475666 |
|        284832 | traffic_out | 2021-09-28 14:11:53 | 271765549779 |
|        284832 | traffic_in  | 2021-09-28 14:11:53 | 38562471255  |
|        284832 | traffic_in  | 2021-09-28 14:16:51 | 38562508567  |
|        284832 | traffic_out | 2021-09-28 14:16:51 | 271765623704 |
|        284832 | traffic_out | 2021-09-28 14:21:53 | 271765697929 |
|        284832 | traffic_in  | 2021-09-28 14:21:53 | 38562545896  |
|        284832 | traffic_out | 2021-09-28 14:26:52 | 271765772147 |
|        284832 | traffic_in  | 2021-09-28 14:26:52 | 38562583207  |
|        284832 | traffic_in  | 2021-09-28 14:31:53 | 38562620534  |
|        284832 | traffic_out | 2021-09-28 14:31:53 | 271765846126 |
|        284832 | traffic_out | 2021-09-28 14:36:52 | 271765920093 |
|        284832 | traffic_in  | 2021-09-28 14:36:52 | 38562657840  |
|        284832 | traffic_out | 2021-09-28 14:41:54 | 271765994446 |
|        284832 | traffic_in  | 2021-09-28 14:41:54 | 38562695228  |
|        284832 | traffic_out | 2021-09-28 14:46:52 | 271766068396 |
|        284832 | traffic_in  | 2021-09-28 14:46:52 | 38562732555  |
|        284832 | traffic_out | 2021-09-28 14:51:52 | 271766142601 |
|        284832 | traffic_in  | 2021-09-28 14:51:52 | 38562769865  |
|        284832 | traffic_out | 2021-09-28 14:56:53 | 271766216546 |
|        284832 | traffic_in  | 2021-09-28 14:56:53 | 38562807192  |
|        284832 | traffic_out | 2021-09-28 15:01:51 | 271766290339 |
|        284832 | traffic_in  | 2021-09-28 15:01:51 | 38562844501  |
|        284832 | traffic_in  | 2021-09-28 15:06:53 | 38562882069  |
| local_data_id | rrd_name    | time                | output       |
+---------------+-------------+---------------------+--------------+
|        284832 | traffic_out | 2021-10-14 14:56:53 | 272107446806 |
|        284832 | traffic_in  | 2021-10-14 14:56:53 | 38734938828  |
|        284832 | traffic_out | 2021-10-14 14:51:52 | 272107372592 |
|        284832 | traffic_in  | 2021-10-14 14:51:52 | 38734901516  |
|        284832 | traffic_in  | 2021-10-14 14:46:53 | 38734864283  |
|        284832 | traffic_out | 2021-10-14 14:46:53 | 272107298803 |
|        284832 | traffic_in  | 2021-10-14 14:41:53 | 38734826840  |
|        284832 | traffic_out | 2021-10-14 14:41:53 | 272107224682 |
|        284832 | traffic_in  | 2021-10-14 14:36:51 | 38734789605  |
|        284832 | traffic_out | 2021-10-14 14:36:51 | 272107150264 |
|        284832 | traffic_in  | 2021-10-14 14:31:53 | 38734752291  |
|        284832 | traffic_out | 2021-10-14 14:31:53 | 272107076696 |
|        284832 | traffic_in  | 2021-10-14 14:26:53 | 38734714929  |
|        284832 | traffic_out | 2021-10-14 14:26:53 | 272107002452 |
|        284832 | traffic_in  | 2021-10-14 14:21:54 | 38734677616  |
|        284832 | traffic_out | 2021-10-14 14:21:54 | 272106928437 |
|        284832 | traffic_out | 2021-10-14 14:16:52 | 272106854466 |
|        284832 | traffic_in  | 2021-10-14 14:16:52 | 38734640385  |
|        284832 | traffic_out | 2021-10-14 14:11:52 | 272106780230 |
|        284832 | traffic_in  | 2021-10-14 14:11:52 | 38734603075  |
|        284832 | traffic_out | 2021-10-14 14:06:53 | 272106706400 |
|        284832 | traffic_in  | 2021-10-14 14:06:53 | 38734565558  |
|        284832 | traffic_in  | 2021-10-14 14:01:53 | 38734528008  |
|        284832 | traffic_out | 2021-10-14 14:01:53 | 272106632058 |
|        284832 | traffic_in  | 2021-10-14 13:56:53 | 38734490779  |
|        284832 | traffic_out | 2021-10-14 13:56:53 | 272106558031 |
|        284832 | traffic_out | 2021-10-14 13:51:53 | 272106483910 |
|        284832 | traffic_in  | 2021-10-14 13:51:53 | 38734453406  |
|        284832 | traffic_out | 2021-10-14 13:46:53 | 272106409951 |
|        284832 | traffic_in  | 2021-10-14 13:46:53 | 38734416114  |
|        284832 | traffic_in  | 2021-10-14 13:41:54 | 38734378809  |
|        284832 | traffic_out | 2021-10-14 13:41:54 | 272106336221 |

MariaDB [cacti]> select name_cache from data_template_data where local_data_id=284832;
+---------------------------------+
| name_cache                      |
+---------------------------------+
| xxxxxxxxxxxxx - Traffic - Gi1/0/2 |
+---------------------------------+
![Capture](https://user-images.githubusercontent.com/27295357/137324057-09adad35-fe16-461d-b199-3d3f2596201f.JPG)

1 row in set (0.00 sec)

**Comment by TheWitness** [comment]
I'm going to mark this resolved as I've not experienced this in more than 24 hours since applying the change.  Pretty sure we are good.  Change was here: https://github.com/Cacti/cacti/commit/090ce94e0a767313c1f15514d80c2064850d51cf
