### ISSUE TITLE
about remote_agent.php permission

### ISSUE THREAD

**Issue by horizonlin** [Cacti/cacti#443]
Main poller remote another poller  remote_agent.php,  It failed  when  main poller  server  using  source NAT  with one IP  and  using  IP pool to visit  internet.   Maybe , add  a white list  at  datacollectors setting for verifying

**Comment by cigamit** [comment]
Good point.  Let me enhance the remote agent to obtain the IP of the originator when it's detected that it was traversed over a NAT.  We have already made this enhancement for user logging.

**Comment by cigamit** [comment]
Resolved.  Thanks!
