### ISSUE TITLE
maximum value of data source is inconsistent for many interfaces or graphs although all created using same data template 

### ISSUE THREAD

**Issue by gj00354347** [Cacti/cacti#4432]
# Describe the bug

Hi Team ,

we are on 1.2 18 cacti and we were trying to create interface traffic for our switches and after creation of graph we see that graphs were not being plotted .
so on checking the logs we found Invalid response for those data sources where the graph was not being plotted .On checking the data source we found that Data source maximum was 1G although this interface traffic graph is using Data template "interface Traffic " which has got data source maximum=100G .

and even this value of ds maxm =1G is not consistent somewhere I see 10G for the same device.

it can happen in one case . lets say when we are using data template =1G and we created some graphs then we revised data source=100G in same data template and then we created some graphs of the same device so those graphs created earlier and the one created later will have different data source .

but in this case it is not so , as I can differentiate between these 2 cases using local_graph_id which I see they are consecutive in this case .so they have been recently created still having different data source for different interfaces /graphs which is strange .and we did not modify the data source maxm manually .

![Capture](https://user-images.githubusercontent.com/27295357/137872233-8b839d9b-a4c6-4f5a-bcf1-eac2d7115881.JPG)

see the data template which have been used to create tis graph , it has data source max=100G 

![image](https://user-images.githubusercontent.com/27295357/137872705-c246faec-443d-455c-875b-97c2ffa697a9.png)

and see the data source maxm of a different interface of same device 

![image](https://user-images.githubusercontent.com/27295357/137873110-6d3ae644-359b-4317-bb91-74d927a530b5.png)

so there is no consistency in data source maxm of graphs being created although they all have been derived from same data template .

cacti 1.2.18 
rrdtool 1.7.2

**Comment by TheWitness** [comment]
This is not a bug.  There is a setting that tells Cacti what to use is the ifSpeed and ifHighSpeed are both 0.  Set it appropriately.

![image](https://user-images.githubusercontent.com/1439914/137999547-401de4bc-fc04-408e-b550-07c008d5cb58.png)
