### ISSUE TITLE
Unable to Save Graph Settings

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#4435]
# Describe the bug

When going to the Graphs page, there is a save button, but it does not work.

## To Reproduce

1. Go to top tab Graphs and any type

2. Modify the filter to what you want

3. Press the save button

4. Logout and back in again

5. Go to the same page and note that the save settings were not carried forward to the next login.

## Expected behavior

Cacti should have less bugs.

**Comment by kim-fitness** [comment]
Hi @TheWitness ,
Please check my comment on https://github.com/Cacti/cacti/commit/3370803f9e719d2f2972545b5ab660ba53cb86ed#r59139842

**Comment by TheWitness** [comment]
Yea, I noticed it was not working.  If you can open a pull request, @netniV can merge it.
