### ISSUE TITLE
yum update from 0.8.8h to 1.0.4 fails

### ISSUE THREAD

**Issue by jlykke** [Cacti/cacti#444]
Error: Package: cacti-1.0.4-1.el7.noarch (epel)
           Requires: mariadb
           Available: 1:mariadb-5.5.52-1.el7.x86_64 (base)
               mariadb = 1:5.5.52-1.el7
 You could try using --skip-broken to work around the problem
** Found 1 pre-existing rpmdb problem(s), 'yum check' output follows:
check-mk-raw-1.2.8p11-el7-36.x86_64 has missing requires of mariadb-server

we run mysql 5.6 on centos 7, no want or need to install mariadb 
don't want to do a tarball install either

Can the dependencies be fixed?

**Comment by pautiina** [comment]
It's not problem Cacti. Check your repository.

**Comment by jlykke** [comment]
What is the best repo to use?

We are using the epel for centos 7 and receiving the error :(

**Comment by cigamit** [comment]
This is a very good question for the repo maintainers editor.  It's likely you can skip 'some' but not all checks.  I would suggest that the repo maintainer allow both options.
