### ISSUE TITLE
Poller Output Table not Empty

### ISSUE THREAD

**Issue by andermat8** [Cacti/cacti#4447]
# Describe the bug

Running version 1.2.16 in Windows Server 2012 (16GB memory, 16(2) CPU).  I keep having issues with the poller output table no emptying.  I run poller_output_empty.php but that does not always fix the issue.  I adjusted the php.ini to memory_limit = 6G and that doesn't improve anything.  Processing over 24k RRDs with 2,117 hosts.  The only fix seems to be rebooting the server.  

Looing for any suggestions to help fix this issue.  Are there other adjustments in the php.ini or my.ini files that would help?

**Comment by TheWitness** [comment]
Yea, 1.2.28 baaaddd

**Comment by netniV** [comment]
You are looking into your crystal ball too much.

**Comment by TheWitness** [comment]
I'm all thumbs.

**Comment by TheWitness** [comment]
If you can't get things to run on Windows, switch to Linux.  CentOS8 works fine, though it's an EOL at the end of this year.  There is also Rocky Linux (new RHEL variant on the block), or you can go with Debian, which has had a Cacti package for years.  Either way, 100 processes, is bad unless you server has 30+ cores.  If you have a script that runs more than 1-2 seconds, I would run that asynchronously from the Cacti poller.

**Comment by TheWitness** [comment]
Also, if you are not using boost with that many RRDfiles, you should implement boost.  Do that first.  However, I'm going to close this as it's more like a support request, and we've done that already.

**Comment by andermat8** [comment]
Thanks for your help.  I'll look into boost.  Sadly, windows is my only option at the moment.
