### ISSUE TITLE
Multiple errors in CMDPHP

### ISSUE THREAD

**Issue by fulljackz** [Cacti/cacti#4448]
# Describe the bug

Log output multiple error  on poller

```
2021/10/28  11:55:15 - CMDPHP PHP ERROR WARNING Backtrace:   (/cmd.php[326]:ping_and_reindex_check(), /cmd.php[736]:exec_poll_php(),  /lib/poller.php[80]:fgets(), CactiErrorHandler())
--
2021/10/28 11:55:15 - ERROR PHP WARNING: fgets() expects parameter 1  to be resource, null given in file: /opt/cacti/lib/poller.php  on line:  80
2021/10/28 11:55:15 - CMDPHP PHP ERROR WARNING Backtrace:   (/cmd.php[326]:ping_and_reindex_check(), /cmd.php[736]:exec_poll_php(),  /lib/poller.php[78]:fflush(), CactiErrorHandler())
2021/10/28 11:55:15 - ERROR PHP WARNING: fflush() expects parameter 1  to be resource, null given in file: /opt/cacti/lib/poller.php  on line:  78
2021/10/28 11:55:15 - CMDPHP PHP ERROR WARNING Backtrace:   (/cmd.php[326]:ping_and_reindex_check(), /cmd.php[736]:exec_poll_php(),  /lib/poller.php[77]:fwrite(), CactiErrorHandler())
2021/10/28 11:55:15 - ERROR PHP WARNING: fwrite() expects parameter 1  to be resource, null given in file: /opt/cacti/lib/poller.php  on line:  77
2021/10/28 11:55:15 - CMDPHP PHP ERROR NOTICE Backtrace:   (/cmd.php[326]:ping_and_reindex_check(),  /cmd.php[736]:CactiErrorHandler())
2021/10/28 11:55:15 - ERROR PHP NOTICE: Undefined variable: pipes in file: /opt/cacti/cmd.php  on line: 736
```
I'm currently running cacti 1.2.18 with php5.6, same behavior with php7.4
I checked this issue : https://github.com/cacti/cacti/issues/4312 I also have the same code on my server but it produces errors.

Regards,

**Comment by TheWitness** [comment]
So, is your memory_limit in php.ini file correct for scripts?  How to view that depends on the operating system you are running.  But this error seems environmental as that error will only happen is the script server crashes, maybe from a buggy script?  If that was the case, you would see issues with so and so script.  So, with that said, I'm just going to close this one as a support request.  If you find that there is a Cacti provided script that is crashing the script server, open a separate ticket with the backtrace, or post on the forums if it's a third party template causing the crashes.
