### ISSUE TITLE
Forced change of password does not work v1.0.6.

### ISSUE THREAD

**Issue by solevi** [Cacti/cacti#445]
Hello,

Forcing users to change password on next login results with "HTTP error 500" _after_ entering new password.

http://localhost/auth_changepassword.php

This page isn’t working

localhost is currently unable to handle this request.
HTTP ERROR 500

Debug of page shows:
2017-03-17 15:39:06 - ERROR PHP ERROR: Call to undefined function password_verify() in file: /opt/cacti-1.0.6/auth_changepassword.php on line: 113

**Comment by cigamit** [comment]
Please update auth_changepassword.php from the development branch.  This issue is resolved and will be patched in 1.0.7.

**Comment by solevi** [comment]
Thank you very much, It is working now!
