### ISSUE TITLE
Remote pollers may not get settings when system-wide polling is turn off

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#4451]
To reproduce

go to settings then poller switch off data collection 
if the remote poller goes into heartbeat you will not be able to re-enable polling via gui

Looking deeper the remote DB will not be updated with  poller_enabled 'on'

```
MariaDB [cacti]> select * from settings  where name like '%poller_enabled%'\G ;
*************************** 1. row ***************************
 name: poller_enabled
value:
1 row in set (0.00 sec)
```
Work around is to manually update this value in db
```
UPDATE settings SET value='on' WHERE name='poller_enabled';
```

**Comment by netniV** [comment]
I think the problem here is that if you try to save system wide settings and the last time the remote poller checked in was more than 2 intervals ago, settings are not replicated to that poller.

However, there is no error to tell you of this.

**Comment by netniV** [comment]
There seems to be a bug when checking if a poller is enabled, it doesn't update its status on the main poller if system wide status is off.  Thus, once off, and more than two polling cycles have passed, its considered stale.
