### ISSUE TITLE
MIB Cache column check causes poller crash under PHP 8.x

### ISSUE THREAD

**Issue by reubenfarrelly** [Cacti/cacti#4458]
Upon upgrading from php-7.4 to php-8.0.12 I am now seeing the following backtrace printed on each poller run:

06/Nov/2021 21:20:28 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
06/Nov/2021 21:20:28 - ERROR PHP ERROR: Uncaught TypeError: Unsupported operand types: array & bool in /var/www/cacti/htdocs/lib/mib_cache.php:359 Stack trace: #0 /var/www/cacti/htdocs/lib/snmpagent.php(471): MibCache->update() #1 /var/www/cacti/htdocs/poller.php(822): snmpagent_poller_bottom() #2 {main} thrown in file: /var/www/cacti/htdocs/lib/mib_cache.php on line: 359
06/Nov/2021 21:20:28 - SYSTEM STATS: Time:26.2622 Method:cmd.php Processes:1 Threads:1 Hosts:26 HostsPerProcess:26 DataSources:418 RRDsProcessed:249

This is with git - following the 1.2.x branch and fully up to date as of now on a Gentoo Linux amd64 system.

**Comment by netniV** [comment]
@reubenfarrelly if you aren't using the SNMP Agent facilities, you can disable this in the system settings.  We will take a look at the error and try to identify the issue.
