### ISSUE TITLE
Threshold don't achieve and not send mail alerting 

### ISSUE THREAD

**Issue by MElsaed** [Cacti/cacti#4463]
# Describe the bug

Dear ;

Kindly i need support for configuration the threshold in Cacti . i configured it but not sent email and not achieve the threshold 

Regards ;

## Desktop (please complete the following information)

- OS: [e.g. iOS] Laptop-Windows 10

- Browser [e.g. chrome, safari] [chroom]

## Smartphone (please complete the following information)

- OS: [e.g. iOS8.1] Centos 8

<img width="372" alt="Graph" src="https://user-images.githubusercontent.com/88613073/141685103-a2cfe801-ff3e-4b58-a7d2-c4126b49cbfa.PNG">
<img width="957" alt="Log" src="https://user-images.githubusercontent.com/88613073/141685104-1ecc5d76-314f-44f9-89cc-d0165a94b861.PNG">
<img width="854" alt="Threshold " src="https://user-images.githubusercontent.com/88613073/141685106-9fce626e-d504-4aa1-b9e5-84e6f1cab9da.PNG">

**Comment by netniV** [comment]
Issues relating to the plug-in should be raised on the plug-in repo.

**Comment by MElsaed** [comment]
How to solve this issue
