### ISSUE TITLE
Poller sanity checking

### ISSUE THREAD

**Issue by ARC1450** [Cacti/cacti#4465]
I recently had the joy of accidentally having a bunch of iSCSI LUNs fall off a VM machine, basically causing me to need to reboot most of my networked machines. 

However, for some reason when Cacti rebooted the VM decided that a 12,000 second jump in time was perfectly acceptable. After manually correcting the skew, I noticed my Cacti poller hadn't ran for about an hour. Investigating further on the CLI, when I ran

```
php poller.php -d
```

This little gem popped up in my log. 

```
2021/11/16 01:10:30 - POLLER: Poller[Main Poller]  PID[3302] NOTE: Cron is configured to run too often!  The Poller  Interval is '60' seconds, with a minimum Cron period of '60' seconds,  but only -12,270.3 seconds have passed since the poller last ran.
--
2021/11/16 01:10:30 - POLLER: Poller[Main Poller] PID[3302] NOTE: Poller Int: '60', Cron Int: '300', Time Since Last: '-12270.27', Max Runtime '298', Poller Runs: '5'
```

While I realize this is an extreme case, probably even a corner case, it's something that might be worth doing a sanity check over. Maybe fire off an email to the admin and put an error in the log file about a time jump into the future, if this was supposed to happen run "php poller.php --force" from the command line to rectify this problem.

Normally I'd chalk this up to I'm an idiot. Unfortunately, I've noticed when some VMs get rebooted, they just go absolutely bonkers on the time front and may skew severely before a time daemon (either NTP or VM tools, for example) yanks them back into control. If a poller process happens and the time jumps, though, you could run into some very oddball behavior.

**Comment by netniV** [comment]
I supposed we could absolute the difference of time, but in truth, I think having protection against such a time skew is better in case weird things happen.  For one, it is identifiable in the logs as you rightly point out and I don't believe that the poller should just be absoluting (removing the minus sign) when comparing as that could cause too many polling events. That in itself could lead to other issues.

**Comment by ARC1450** [comment]
Another thing I should mention is that the graphs will be empty until the correct time has passed the negative time. In my case, the poller was actually collecting info but graphs were blank for about 3 hours.

**Comment by netniV** [comment]
That is because we do have reply protection on the datasources I believe.  That stops repeat and wasted updates to the RRD files.  Having this issue though, will at least be searchable for other users who may have the same problem on those rare occasions.

**Comment by ARC1450** [comment]
Is there any way to override that protection and/or remove the false "future" info from the RRDs?

**Comment by netniV** [comment]
I'll be honest, not sure there is without manually using RRDtool to do that.  I think there is a splicer tool in the cli, but I wouldn't know of the top of my head how to use that to remove the future data (as by the time you get there, the system time would likely have caught up already).

**Comment by TheWitness** [comment]
The rrd_splice.php tool might be a good start.  It will load all the rows into a SQLite database and then you can modify records prior to writing back out to the RRDfile.  If you are a coder, you should be able to adapt it to do what you want it to.

**Comment by TheWitness** [comment]
Going to close.  I myself have been having problems with chronyd too.  With VM's it's really important to sync their clock with the hosts at boot time.  With VMWare it used to be optional.
