### ISSUE TITLE
QSFP interface TX/RX power snmp query.

### ISSUE THREAD

**Issue by jocaplanaltonet** [Cacti/cacti#4466]
snmpwalk -v 2c -c Admin123  10.200.10.1 .1.3.6.1.4.1.2011.5.25.31.1.1.3.1.32
iso.3.6.1.4.1.2011.5.25.31.1.1.3.1.32.67403854 = ""
iso.3.6.1.4.1.2011.5.25.31.1.1.3.1.32.67469390 = STRING: "-909.04"
iso.3.6.1.4.1.2011.5.25.31.1.1.3.1.32.67469454 = STRING: "-429.11"
iso.3.6.1.4.1.2011.5.25.31.1.1.3.1.32.67469518 = ""
iso.3.6.1.4.1.2011.5.25.31.1.1.3.1.32.67469582 = ""
iso.3.6.1.4.1.2011.5.25.31.1.1.3.1.32.67469646 = STRING: "-252.90"
iso.3.6.1.4.1.2011.5.25.31.1.1.3.1.32.67469710 = ""
iso.3.6.1.4.1.2011.5.25.31.1.1.3.1.32.67469774 = ""
iso.3.6.1.4.1.2011.5.25.31.1.1.3.1.32.67469838 = ""
iso.3.6.1.4.1.2011.5.25.31.1.1.3.1.32.67469902 = STRING: "-123.09"
iso.3.6.1.4.1.2011.5.25.31.1.1.3.1.32.67469966 = STRING: "-540.91"
iso.3.6.1.4.1.2011.5.25.31.1.1.3.1.32.67470030 = STRING: "-70.38"
iso.3.6.1.4.1.2011.5.25.31.1.1.3.1.32.67470094 = ""
iso.3.6.1.4.1.2011.5.25.31.1.1.3.1.32.67470158 = ""
iso.3.6.1.4.1.2011.5.25.31.1.1.3.1.32.67470222 = ""
iso.3.6.1.4.1.2011.5.25.31.1.1.3.1.32.67470286 = ""
iso.3.6.1.4.1.2011.5.25.31.1.1.3.1.32.67470350 = ""
iso.3.6.1.4.1.2011.5.25.31.1.1.3.1.32.67470414 = ""
iso.3.6.1.4.1.2011.5.25.31.1.1.3.1.32.67470478 = ""
iso.3.6.1.4.1.2011.5.25.31.1.1.3.1.32.67470542 = ""
iso.3.6.1.4.1.2011.5.25.31.1.1.3.1.32.67470606 = ""
iso.3.6.1.4.1.2011.5.25.31.1.1.3.1.32.67470670 = ""
iso.3.6.1.4.1.2011.5.25.31.1.1.3.1.32.67470734 = ""
iso.3.6.1.4.1.2011.5.25.31.1.1.3.1.32.67470798 = ""
iso.3.6.1.4.1.2011.5.25.31.1.1.3.1.32.67470862 = ""
**iso.3.6.1.4.1.2011.5.25.31.1.1.3.1.32.67502158 = STRING: "-4000.00,-4000.00,-4000.00,-4000.00"**
iso.3.6.1.4.1.2011.5.25.31.1.1.3.1.32.67502222 = ""
iso.3.6.1.4.1.2011.5.25.31.1.1.3.1.32.67502286 = STRING: "-174.31,-142.67,-159.71,-138.05"
iso.3.6.1.4.1.2011.5.25.31.1.1.3.1.32.67502350 = STRING: "-153.42,-209.64,-190.17,-172.82"
iso.3.6.1.4.1.2011.5.25.31.1.1.3.1.32.67502414 = ""
iso.3.6.1.4.1.2011.5.25.31.1.1.3.1.32.67502478 = ""

**Comment by netniV** [comment]
Please following the recommended format for creating issues to provide proper information:

```markdown
# Describe the bug

A clear and concise description of what the bug is.

## To Reproduce

Steps to reproduce the behavior:

1. Go to '...'

2. Click on '....'

3. Scroll down to '....'

4. See error

## Expected behavior

A clear and concise description of what you expected to happen.

## Screenshots

If applicable, add screenshots to help explain your problem.

## Desktop (please complete the following information)

- OS: [e.g. iOS]

- Browser [e.g. chrome, safari]

- Version [e.g. 22]

## Smartphone (please complete the following information)

- Device: [e.g. iPhone6]

- OS: [e.g. iOS8.1]

- Browser [e.g. stock browser, safari]

- Version [e.g. 22]

## Additional context

Add any other context about the problem here.
```

**Comment by jocaplanaltonet** [comment]
wrong session, you can close.
