### ISSUE TITLE
Creating another graph for host from a graph template already used duplicates the graph with same data source

### ISSUE THREAD

**Issue by FrodoTheRingWearer** [Cacti/cacti#447]
So I have a graph/data template that I use to log latency and jitter between the Cacti server and a remote host

 Anyway, when I got to create graphs for the host, I select the graph (In this case it is "Network - Ping and Jitter") and click create:

![image](https://cloud.githubusercontent.com/assets/26150256/24059726/20363152-0b1e-11e7-8f00-f3d4615f7fc3.png)

Next it asks me which host that I'd like to ping. I change the header for the graph so that I can distinguigh it from the others. In this I've left the default of "google.com".

![image](https://cloud.githubusercontent.com/assets/26150256/24059755/41c5bc02-0b1e-11e7-8156-b13d4a56d512.png)

And then I end up with two graphs using the same data source.

![image](https://cloud.githubusercontent.com/assets/26150256/24059841/8c71d0a6-0b1e-11e7-8314-02dc33702f0c.png)

This worked fine in .8.8H. I've tried it with a number of my graphs. Maybe this is an issue with my template? I've attached it here if you would like to see.

[ping_latency.zip](https://github.com/Cacti/cacti/files/851589/ping_latency.zip)

**Comment by FrodoTheRingWearer** [comment]
Additionally when I create the graphs, I get the following errors in the Cacti log file:

> 2017-03-17 15:05:24 - CMDPHP PHP ERROR NOTICE Backtrace: (E:\Cacti\graphs_new.php: 37 form_save)(E:\Cacti\graphs_new.php: 106 host_new_graphs)(E:\Cacti\graphs_new.php: 363 draw_nontemplated_fields_graph_item)(E:\Cacti\lib\html_form_template.php: 175 CactiErrorHandler)(E:\Cacti\lib\functions.php: 4265 cacti_debug_backtrace)
2017-03-17 15:05:24 - ERROR PHP NOTICE: Undefined index: text_format in file: E:\Cacti\lib\html_form_template.php on line: 175

> 2017-03-17 15:05:24 - CMDPHP PHP ERROR NOTICE Backtrace: (E:\Cacti\graphs_new.php: 37 form_save)(E:\Cacti\graphs_new.php: 106 host_new_graphs)(E:\Cacti\graphs_new.php: 363 draw_nontemplated_fields_graph_item)(E:\Cacti\lib\html_form_template.php: 175 CactiErrorHandler)(E:\Cacti\lib\functions.php: 4265 cacti_debug_backtrace)
2017-03-17 15:05:24 - ERROR PHP NOTICE: Undefined index: color_id in file: E:\Cacti\lib\html_form_template.php on line: 175

**Comment by cigamit** [comment]
I really don't like this method of creating graphs.  It makes the schema hard to work with as evidenced by this bug.  It's on the list with a few others who are experiencing corner cases when using templating in interesting ways, as you are doing, which is not bad, or not using templating at all, which I would have hoped was dead.

**Comment by cigamit** [comment]
Resolved in GitHub.  Test away and confirm.

**Comment by cigamit** [comment]
I'm going to go ahead and close this.  I have confirmed on my side.  You will have to remove one of the two and start again.

**Comment by adfire** [comment]
I have exactly the same problem with generic oid template. With the proper template (thank you!) graphs for this template are being generated. But all of them uses the same template.
What do you mean that it is resolved in GitHub ? Should I download some files and replace it in my installation ?

**Comment by cigamit** [comment]
Look at the links directly above your's.  It references this commit: https://github.com/Cacti/cacti/commit/257349648ab3dbeafa4f39ae4fc5915ab2001207, that is where you can find the changed files, or you can simply wait for 1.0.7.
