### ISSUE TITLE
i18n Language Debug Checks can cause basedir warnings for /share/

### ISSUE THREAD

**Issue by chrcoluk** [Cacti/cacti#4474]
Some kind of path detection breaks after upgrading from PHP from 7.3 to 7.4, 7.3 is EOL 6 Dec 2021.

To reproduce enable open basedir restrictions on PHP do not include /share/ path, then should see details appear in CLOG of error, I didnt need to enable any debug logging options in the cacti settings.

Error as below.

` CMDPHP PHP ERROR WARNING Backtrace: (/graph_json.php[32]:include(), /include/auth.php[28]:require_once(), /include/global.php[510]:include_once(), /include/global_languages.php[76]:l10n_debug(), /include/global_languages.php[763]:is_dir(), CactiErrorHandler())
22/Nov/2021 02:02:36 - ERROR PHP : is_dir(): open_basedir restriction in effect. File(/share/) is not within the allowed path(s):`

Cacti 1.2.17
PHP 7.4.26
FreeBSD 12.2
Apache 2.4.x

No idea what functionality this is related to as observations are cacti is otherwise working normally.  It would be nice if these error warnings could be hidden

**Comment by netniV** [comment]
Apparently, you have basedir set within a php.ini and that prevents Cacti from examing system directories in an attempt to find php.  You can update the php path directly within the settings table.

**Comment by chrcoluk** [comment]
Thats not the issue, PHP is set corretly in the settings table and I have allowed access to the php folders in basedir, its the same base dir configuration I was runnng on PHP 7,.3, except I modified paths for newer PHP.

It suddenly is starting to check for a non existent /share/ folder every time I load most url's.  This is something new that started occurring on PHP 7.4.

I can flip backwards and forwards between the different PHP versions easily as I am using directadmin, and its a very clear issue, hidden for those who dont use basedir security.

**Comment by netniV** [comment]
OK, so this is not new, it's part of the i18n debug logging and has existed there for two years.  It basically checks for both /share/ and /tmp/ as directories.

Strange that you are only seeing this as a problem under PHP 7.4, since if you have been using the same basedir limitations, you would have expected to see it under earlier versions unless this has now been promoted to a warning/error where previously it was ignored.

**Comment by TheWitness** [comment]
Try testing with the latest 1.2.x branch and report back.
