### ISSUE TITLE
Remote pollers do not force connection when online

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#4477]
Hey Guys,

When running automation on 1.2.19 I see that when you select a remote poller 
the scan does not fire but if you select the main poller it works

![automation_issue](https://user-images.githubusercontent.com/13388748/143496390-f0c6fb48-2855-42ee-be08-7245d7d8a325.gif)

**Comment by bmfmancini** [comment]
Trying to run poller_automation.php yields the following

```
php poller_automation.php --poller=2 --network=1 --debug
2021-11-25 15:34:51 - AUTOM8 [PID: 14306] WARNING: The Network ID: 1 is disabled.  You must use the 'force' option to force it's execution.
php poller_automation.php --poller=2 --network=2 --debug
2021-11-25 15:34:57 - AUTOM8 [PID: 14312] WARNING: The Network ID: 2 is disabled.  You must use the 'force' option to force it's execution.
php poller_automation.php --poller=2 --network=3 --debug
2021-11-25 15:35:00 - AUTOM8 [PID: 14315] WARNING: The Network ID: 3 is disabled.  You must use the 'force' option to force it's execution.
php poller_automation.php --poller=2 --network=4 --debug
2021-11-25 15:35:03 - AUTOM8 [PID: 14333] Network Discover is now running for Subnet Range '4'
```

**Comment by bmfmancini** [comment]
Reverting to automation_network.php from 1.2.17 resolved my issue

**Comment by bmfmancini** [comment]
Reverting back to poller_automation.php fixes my issue not many changes that I see

**Comment by bmfmancini** [comment]
Issue is with this block here

```
if ($config['poller_id'] > 1) {
	if ($config['connection'] == 'online') {
		db_force_remote_cnn();
	} else {
		cacti_log('WARNING: Main Cacti database offline or in recovery.  Can not run automation', false, 'AUTOM8');
		admin_email(__('Cacti System Warning'), __('WARNING: Main Cacti database offline or in recovery'));
	}

	exit(1);
}
```

I removed exit(1) and the issue is resolved for the original file however this is not a good fix
Will need to debug this

**Comment by netniV** [comment]
The exit looks like it should be in the warning section

**Comment by bmfmancini** [comment]
Yea I moved it  thought I had it fixed but I just built a new lab to retest
and it's broken again... Maybe I messed something up with the new build
I'll debug more
