### ISSUE TITLE
The error related to permission denied on cacti 1.2.19 and ubuntu 20.04

### ISSUE THREAD

**Issue by manhvu1997** [Cacti/cacti#4478]
# Describe the bug

I installed cacti 1.2.19 on ubuntu 20.04 and faced 2 bugs:
 1.  "ERROR PHP WARNING: fopen(/var/www/html/cacti/include/vendor/csrf/csrf-secret.php): Failed to open stream: Permission denied in file: /var/www/html/cacti/include/vendor/csrf/csrf-magic.php on line: 490"
 2. Time is wrong compared to reality

## To Reproduce

1. I installed cacti following these steps: https://computingforgeeks.com/install-and-configure-cacti-on-ubuntu/
In the link above, author used php 7.4.3, but in my installation I used php 8.0.13
2. When I setup completely, I see the log file  below
3. This is my permission of cacti folder
(https://user-images.githubusercontent.com/58839875/143515521-2ecb01c5-afdb-434a-b961-f9a7754e29da.png)

## Screenshots

**1. Issues permission denied:**
2021-11-26 15:38:39 - ERROR PHP WARNING: fopen(/var/www/html/cacti/include/vendor/csrf/csrf-secret.php): Failed to open stream: Permission denied in file: /var/www/html/cacti/include/vendor/csrf/csrf-magic.php on line: 490
**2. Wrong time**
This is current time in my ubuntu
(https://user-images.githubusercontent.com/58839875/143514610-27df6b14-cc34-489f-8af3-dacdcd26fb81.png)
This is timedate in logfile:
(https://user-images.githubusercontent.com/58839875/143515375-7b96f28e-2b81-471a-87c6-fab9f24ac10c.png)

 

## Desktop (please complete the following information)

- OS: ubuntu 20.04

- PHP version 8.0.13

- Mariadb 10.3.31
- Cacti: 1.2.19

**Comment by TheWitness** [comment]
You browser needs access to that directory upon install. Did you install from aptitude or from source?  I'd from source, you need to change directories to the cacti base directory and run

```sh
chown -R apache:apache *
```

Since this is Ubuntu, it may be `www-run` or `www-data`.  Use common sense.

**Comment by manhvu1997** [comment]
Hi Witness
Thanks for your reply
I set the permission with user www-data and group www-data for rra and script. With the csrf folder, I set the permission to cacti user and cacti group. However, I also faced the same problem I described above. Can you help me to fix this ? 
This is my permission of csrf folder:
![A932AB67-7DEF-4B2E-963A-74F2B551227E](https://user-images.githubusercontent.com/58839875/143688725-cccf3d96-801f-4a1f-b2dc-97d328182f34.jpeg)

**Comment by TheWitness** [comment]
```sh
cd /var/www/html/cacti
find . -type d -exec chmod 755 {} \;
```

**Comment by netniV** [comment]
Whilst that will set most of the directories to executable, what it doesn't do,  is make the vendor/csrf folder writable to www-data.  Without that, it can't create the csrf-secret.php automatically and you must do it yourself.  Once it has been created, you can make the directory readonly.

**Comment by manhvu1997** [comment]
Thanks for your support netniV
I set the owner and group of csrf folder to www-data:www-data and It's worked perfect
