### ISSUE TITLE
plugins are invisible

### ISSUE THREAD

**Issue by dsclassen** [Cacti/cacti#448]
I have 8 plugins available, but none show up on the /cacti/plugins.php page.

![cacti_no_plugins](https://cloud.githubusercontent.com/assets/8882563/24066469/2304db06-0b30-11e7-9638-c13315bf4308.png)

on commit 88cea36

**Comment by cigamit** [comment]
The one page I forgot to test :)  Solving momentarily.

**Comment by cigamit** [comment]
Resolved.  Please pull latest.

**Comment by dsclassen** [comment]
all fixed. Thanks.

**Comment by cigamit** [comment]
Just did another push.  Only minor.  Test away.  If using 'Dark', you can shift and add more sort columns.  The modern, classic and paw themes still need a new class called 'secondarySort' in order to highlight the secondary sorts though.
