### ISSUE TITLE
Cacti 1.2.17 can't show UI after installed

### ISSUE THREAD

**Issue by manhvu1997** [Cacti/cacti#4484]
# Describe the bug

Dear Sir/Madam
I have installed cacti 1.2.17 on centos 7.9. However, after I installed complete, I face an error like photo above. It's can't show the UI of cacti and show the tree of source code folder. Can you help me to fix this ?

## To Reproduce

1. I install cacti 1.2.17 on centos 7.9

2. My permission of cacti like the photo below
![ảnh](https://user-images.githubusercontent.com/58839875/143797767-fc1c2306-31ab-4da0-9c83-c6582b56239e.png)

3. When I access to the web of cacti, It can't show the UI of cacti and show the tree of source code folder like the picture below
![ảnh](https://user-images.githubusercontent.com/58839875/143797819-f07e5aea-cb8f-477a-9ad7-c9a3a7f92529.png)

## Desktop (please complete the following information)

- OS: Centos7.9

- Browser: Firefox
- Version: cacti 1.2.17
- PHP 7.4.6

**Comment by bmfmancini** [comment]
You seem not to have php installed properly

Run this command

yum install -y rrdtool mariadb-server net-snmp-utils snmpd php php-mysql
php-snmp php-xml php-mbstring php-json php-gd php-gmp php-zip php-ldap
php-mc php-posix


You may also need to do the following

Systemctl restart httpd
Systemctl restart php-fpm

Also in include/config.php check that your base path is correct

**Comment by netniV** [comment]
You also have a badly configured website if you allow directory browsing by default.  You should have that disabled by default.

**Comment by manhvu1997** [comment]
I solved my problem. My php version is installed on my centos, which is conflicted with my php-fpm. So I think it course the UI couldn’t shown.
I uninstalled completely php and installed them in the same version. Finally it’s worked perfect
Thanks all for your support!
