### ISSUE TITLE
realtime graphing stopped after os upgrade

### ISSUE THREAD

**Issue by majed17** [Cacti/cacti#4485]
php upgraded to version 8
cacti version 1.2.9
log displays:
```


CMDPHP PHP ERROR WARNING Backtrace:   (/cmd_realtime.php[201]:cacti_snmp_session_get(),  /lib/snmp.php[492]:SNMP->get(), CactiErrorHandler())
--
ERROR PHP WARNING: SNMP::get(): Fatal error:  USM generic error in file: /usr/share/cacti/lib/snmp.php  on line: 492
```

**Comment by TheWitness** [comment]
This is a PHP issue.  Please report it to the PHP guys.  I suggest you back out your upgrade to a more stable version of PHP.

**Comment by majed17** [comment]
what about this:


```
2021/12/03  04:31:22 - CMDPHP PHP ERROR WARNING Backtrace:   (/graphs_new.php[42]:form_save(),  /graphs_new.php[150]:html_graph_new_graphs(),  /lib/html_graph.php[442]:html_graph_custom_data(),  /lib/html_graph.php[573]:draw_nontemplated_fields_graph_item(),  /lib/html_form_template.php[254]:draw_edit_form(),  /lib/html_form.php[114]:draw_edit_control(),  /lib/html_form.php[330]:CactiErrorHandler())
--
2021/12/03 04:31:22 - ERROR PHP WARNING: Undefined array key "value"  in file: /var/www/localhost/htdocs/cacti/lib/html_form.php  on line:  330
```

that is when we changed a source

**Comment by TheWitness** [comment]
@majed17, What plugins do you have installed?  It's some GUI what includes a Color.  Were you creating a new Graph Item?

**Comment by TheWitness** [comment]
I, recommend that you update to the 1.2.x branch or wait for 1.2.20 to be released.  1.2.9 is quite old now.  I can not reproduce that problem in 1.2.20 (aka 1.2.x branch for now).

**Comment by majed17** [comment]
sorry that's a typo, the version is 1.2.19, i have no external plugins installed other the built in ones..i was changing a number in the oid
