### ISSUE TITLE
FATAL: Connection to Cacti database failed. Please ensure

### ISSUE THREAD

**Issue by sez76** [Cacti/cacti#4486]
# Describe the bug

FATAL: Connection to Cacti database failed. Please ensure:

the PHP MySQL module is installed and enabled.
the database is running.
the credentials in config.php are valid.

Version:
Linux Ubuntu 20.04
PHP7.4
Apache/2.4.41
mysql  Ver 8.0.27-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))

Action:
`select * from settings where name like '%php%';
+-----------------+-----------------+
| name            | value           |
+-----------------+-----------------+
| path_php_binary | /usr/bin/php |
+-----------------+-----------------+
1 row in set (0.00 sec)

mysql> update settings set value='/usr/bin/php7.4' where name='path_php_binary' ;
Query OK, 1 row affected (0.03 sec)
Rows matched: 1  Changed: 1  Warnings: 0

mysql> select * from settings where name like '%php%';
+-----------------+-----------------+
| name            | value           |
+-----------------+-----------------+
| path_php_binary | /usr/bin/php7.4 |
+-----------------+-----------------+
1 row in set (0.00 sec)`

**Comment by netniV** [comment]
this is a MySQL authentication issue, not a Cacti issue.  As long as all the details in config.php are set properly, you should have no issues.  Check your MySQL logs to see why you may have issues with connectivity.
