### ISSUE TITLE
[1.2.19] Missing right panel on the graphs

### ISSUE THREAD

**Issue by xefil** [Cacti/cacti#4489]
# Describe the bug

After updating to 1.2.19 (rpm) I'm missing the right panel on the graphs to show, i.e., the Time Graph view:

![image](https://user-images.githubusercontent.com/17131053/144420062-87bd8974-51de-4d9a-a60f-b79cb57875b1.png)

## To Reproduce

Go to Graph view.

## Expected behavior

I expect to see the above menu.

## Screenshots

see above

## Desktop (please complete the following information)

- OS: Win10

- Browser Chrome

- Version 96

## Smartphone (please complete the following information)

Not Applicable

## Additional context

---

**Comment by xefil** [comment]
Ok, found by myself!

![image](https://user-images.githubusercontent.com/17131053/144420623-bb6e3271-edc6-4470-8e17-c26f5491f9c7.png)

I'ts now a permission!

**Comment by TheWitness** [comment]
Yea, we went back and forth on that.  The way it was originally setup, you had to check it to deny permission, which is confusing since all other checks grant access.

**Comment by xefil** [comment]
Thanks @TheWitness  ;-)
