### ISSUE TITLE
exec_poll_php / $pipes not 'cleaned' when previous command produces error.

### ISSUE THREAD

**Issue by viulian** [Cacti/cacti#449]
I am running cacti 1.0.6 on Fedora 25 (after updating the OS, and then manually updating cacti to 1.0.6) to hopefully get the problem fixed.

I noticed that `ss_host_disk` was showing 'shifted' values, meaning that for the TOTAL of the disk space I was getting a really small number (like 27.8) and for the next query (used disk space), the server_script was returning the TOTAL value (32gb).

After a lot of debugging, I was able to pinpoint the problem to the `$pipes` not being cleaned properly (?) if this is a possible explanation. In `exec_poll_php` I activated non blocking mode for the pipes in an attempt to try to clean the output and to see where the 'fake' 27.8 value was coming from.

What was happening was that just after the script_server was sent the `/usr/share/cacti/scripts/ss_host_disk.php ss_host_disk 192.168.0.109 2 1:161:500:1:10:public:::::: get total '31'` command, the value read with fget was "27.8" instead of 32gb that I was expected.

Trying to clean the pipes before sending the "get total" command, I observed that the pipe contained a different value (instead of my expected one): `FATAL: No sensor data was returned from SNMP`

I realized that this is related to a previous script that was ran (that was also producing errors in cacti log - lm_sensor, but a different text: `2017-03-18 19:52:01 - CMDPHP WARNING: SNMP Error:'snmpget(): Error in packet at 'LM-SENSORS-MIB::lmFanSensorsIndex.15': (noSuchName) There is no such variable name in this MIB.', Device:'127.0.0.1', OID:'.1.3.6.1.4.1.2021.13.16.3.1.1.15'`. (this is due to the motherboard upgrade but I focused on the disk aspect first)

Trying to explain in reverse what I suspect is happening:

1) lm_sensors script produces an error in cacti_log (about lmFanSensorsIndex.15 missing) but continues to output more values on the stdout, some temperatures (I suspect 27.8 is a temperature, not a Fan sensor value).
2) `ss_host_disk` starts, calls `exec_poll_php` which creates new set of `$pipes` and sends the "get total '31'" command to get the total disk space, then reads from the stdout of the server_script.
3) however, it finds the an old "27.8" value (or the FATAL: No sensor ....) so it decides to return that (a new fget on the stdout pipe would return the 31194656768 value that I was expecting)

I have disabled lm_sensors graphs and sources until I fix them, and the disk measurements returned to correct values.

The bug here is that an error in a script ran by the script_server can influence (in cascade) the values of other scripts scripts that are executed after it.

**Comment by cigamit** [comment]
lib/poller.php has just been updated.  Please test and provide feedback.

**Comment by viulian** [comment]
Amazing speed - it looks correct!

My feedback will take 1-2 days, I will have to recreate the failing lm_sensors scripts / graphs - but to speed things up I hope I can recover the configuration from backup.

**Comment by cigamit** [comment]
Please, we are hoping to do a new release this weekend.

**Comment by cigamit** [comment]
Any update?

**Comment by viulian** [comment]
I am sorry :( only had a bit of time today to try to recover the graphs (for fan / temps) and it didn't go smoothly. However, the 'flush' you added looks it was needed, so I will close it for now, and will comment later when I can test it.

Thank you!

**Comment by cigamit** [comment]
Okay, works for me.
