### ISSUE TITLE
Rebuild poller cache problem after change snmp version via DB query

### ISSUE THREAD

**Issue by xmacan** [Cacti/cacti#4491]
Change snmp version via db query. Poller still uses old snmp setting. 
Re-save device, rebuild poller cache from GUI or CLI doesn't help. Only edit device->repopulate poller cache works.

Cacti 1.2.19

**Comment by netniV** [comment]
If you are changing the snmp version via an SQL query, you may not be changing all the required fields.  That is unsupported and there are API's to do that through code which also incorporate the appropriate hooks for core/other plugins.

**Comment by xmacan** [comment]
@TheWitness  advised cli/push_out_hosts.php. It works well.

**Comment by TheWitness** [comment]
I'm wondering what is broken in the current script.  I think that what the current script does is shortcut the re-population of the data_input_data table with your host fields, and therefore it does not fix that, where the push_out_host() pushes all host information back to the data_input_data table.  Have to add this to my "fix Cacti's database project" wish list.
