### ISSUE TITLE
How to align time

### ISSUE THREAD

**Issue by aliuzzz** [Cacti/cacti#4493]
![time](https://user-images.githubusercontent.com/43594093/144779994-ff822aa3-8e05-4a94-8da1-097f44492ec9.png)

The abscissa time is different from the real time，i try to modify php.ini datatimezone，but it only modify the realtime

**Comment by netniV** [comment]
Depending on your system, there can be multiple php.ini files that set the date/time zone.

**Comment by aliuzzz** [comment]
> Depending on your system, there can be multiple php.ini files that set the date/time zone.
![ttime](https://user-images.githubusercontent.com/43594093/144957576-1f097452-8cde-4bda-9d58-f07c251422c3.png)

i set data/time zone "PRC" or "Asia/Shanghai", but it doesn't change. my cacti is cacti1.2.5
The same problem occurs on my other machine cacti0.8.8f. i try to modify php.ini and it takes effect
centos6.10

**Comment by TheWitness** [comment]
Make sure it's a legal timezone and don't forget to restart apache.

**Comment by netniV** [comment]
Or php-fpm if you are using that service.

**Comment by aliuzzz** [comment]
i even reboot my server...
data.timezone only change time
![QQ截图20211208113830](https://user-images.githubusercontent.com/43594093/145144183-1ad3ece0-a0ce-4d2f-b557-99144efc9d9d.png)
i can't change the Time on the abscissa axis by data.timezone.... i check phpinfo and the path to the php.ini is correct
Is this problem related to the data format of the database?

**Comment by xmacan** [comment]
Someone had a similar problem, please try
https://forums.cacti.net/viewtopic.php?f=2&t=61377

**Comment by aliuzzz** [comment]
> Someone had a similar problem, please try https://forums.cacti.net/viewtopic.php?f=2&t=61377

wow!it's a good idea.Let me try

**Comment by TheWitness** [comment]
Going to close this one.
