### ISSUE TITLE
New Local Account Disabled if not logged into

### ISSUE THREAD

**Issue by aoijlattimore** [Cacti/cacti#4494]
# Describe the bug

After creating a new local account, if no one logs into this account within 15-30 minutes the account becomes disabled. 
This only happens for new accounts and doesn't appear to affect any other account types. I was wondering if this was expected behavior or if this is some type of bug. I didn't find any "timeout" settings for this type of behavior but I'm also not wholly convinced that it isn't a security feature.

## To Reproduce

1. Go to 'Configuration>Users>Add User'

2. Click on 'Enabled'

3. Under Account Options, click on 'Must Change Password at Next Login'

4. Click 'Create'

5. Wait between 15-30 minutes (have not been able to nail down exact time)

6. Attempt to login to New Local Account 

## Expected behavior

The expectation is that we would be prompted with an Update Password splash screen. Instead we receive an error that the User/Password are incorrect. When logged into an Admin account to look at the New Account, it is no longer 'Enabled' 

## Desktop (please complete the following information)

- OS: Windows 10

- Browser: Edge, Chrome

- Version: Edge Version 96.0.1054.43 , Chrome version Version 96.0.4664.45

## Additional context

Cacti v 1.2.10
[Forum Post](https://forums.cacti.net/viewtopic.php?f=21&t=61935#p286895) (No Responses)

**Comment by netniV** [comment]
Do you have the options set that automatically block accounts when the wrong password is used?

**Comment by aoijlattimore** [comment]
Yes, it is set to 5 attempts. 
For added context, new accounts become disabled even if no one has attempted to log in as well (after 15-30 min).

**Comment by TheWitness** [comment]
I might have run into this.  I'll have some time over the weekend to do a code review.

**Comment by TheWitness** [comment]
I've created a "watch" for this.  I enabled all the features.  Let's see what happens @cigamit wrote most of this.  Maybe there is a corner case bug.  Will find out.  See if your screen looks like mine:

`watch "mysql -e 'select * from user_auth where id = ?\G' cacti"`

The output should look as follows:

![image](https://user-images.githubusercontent.com/1439914/145626664-1b65c1da-21df-44db-a8a1-4976ca121c11.png)

**Comment by TheWitness** [comment]
If this holds true, then in about 15-30 minutes the `locked` should be set.

**Comment by TheWitness** [comment]
It's been over 30 minutes and no lockout yet.  Do this test and let us know what you come up with.

**Comment by aoijlattimore** [comment]
I was planning on doing this today however CLI access is unavailable at the moment. will need to bring the server down to resolve. Will attempt to run the watch this week.

**Comment by aoijlattimore** [comment]
Unfortunately i didn't get any output after running the watch and creating a test account.

**Comment by TheWitness** [comment]
So, my guess is that someone tried to hack in.

**Comment by aoijlattimore** [comment]
ah so someone is trying to brute force into accounts. how ominous. I still have the test account up to see if becomes locked. I'll check in in about 5-10 minutes. If it's still up I'll just go ahead and close out

**Comment by aoijlattimore** [comment]
Well the test account is still active. I'll have to agree with your assessment. Thank you for looking into this

**Comment by TheWitness** [comment]
Yea, best practice is to always either disable the "admin" account or rename.  Same applies to "guest".  This user names are too common and used as general attack vectors. This is also true of forensic tools used by CISSP's.
