### ISSUE TITLE
DSSTATS will get invalid data for some devices after reboot requiring purging of stats

### ISSUE THREAD

**Issue by jdcoats** [Cacti/cacti#4495]
I have been finding that from time to time dsstats will get invalid data and have to be purged. I have finally found a way to reproduce this issue on demand. Its not always this device or data type but here is an example of what happens when I reboot this Linux server. 

![image](https://user-images.githubusercontent.com/42470924/145235021-f51f12f1-5ba9-4358-ac30-e4ace5bc1e25.png)
```
2021/12/08 10:25:14 - CMDPHP intropage-hr Backtrace: (/plugins/intropage/intropage.php[39]:process_page_request_variables(), /plugins/intropage/include/functions.php[87]:intropage_detail_panel(), /plugins/intropage/include/functions.php[594]:busiest_traffic_detail(), /plugins/intropage/panellib/busiest.php[1143]:human_readable(), /plugins/intropage/include/functions.php[1579]:cacti_debug_backtrace())
--
2021/12/08 10:25:14 - CMDPHP INTROPAGE WARNING: Bytes = [4.919131751469E+18], Factor = [1024], i = [6] d = [1152921504606846976]
```
![image](https://user-images.githubusercontent.com/42470924/145235287-8df087b2-f6fe-4b5a-8153-5a840326abc5.png)

**Comment by TheWitness** [comment]
Just finishing this up today on my day off.

**Comment by TheWitness** [comment]
@jdcoats, you need to update lib/dsstats.php, poller_dsstats.php and include/global_settings.php.  After that see if you can reproduce again.  Make sure the device has been up for a while and has a lot of traffic.

This change will implement RRDtool like clipping for COUNTERS and DERIVE type objects.  If the resulting value is above the rrd_maximum value, it'll return NULL for the delta.  A small gap will appear in the data, but that's fine.  Maybe I can improve that.  Not today.

It also addresses #4500, which will allow DSStats to finish sooner.  Warning, the PHP processes take a lot of CPU.

**Comment by jdcoats** [comment]
Thanks! No longer able to reproduce on demand.

**Comment by TheWitness** [comment]
Cool.  Ignore my other comment.  The new parallel setting should speed things up too.

**Comment by TheWitness** [comment]
Here is without boot.

![image](https://user-images.githubusercontent.com/1439914/145624073-f5a5a2c7-d692-43d2-8c47-0dd1d5ec274d.png)

Here is with boost.

![image](https://user-images.githubusercontent.com/1439914/145624227-1559cf01-5805-4f0a-af75-46e790a00fb1.png)

**Comment by jdcoats** [comment]
![image](https://user-images.githubusercontent.com/42470924/145629834-c2b1eeed-a9c7-465c-becb-8471a48aed15.png)

**Comment by TheWitness** [comment]
Cool.  You should try like 4 processes and see if it's better.

**Comment by jdcoats** [comment]
Before:
![image](https://user-images.githubusercontent.com/42470924/145639737-3dbcbe36-279a-47e9-b6ae-3031639bd86c.png)


After:
![image](https://user-images.githubusercontent.com/42470924/145639609-ef4f280a-5e17-4a9e-b97d-2e01cd9da80e.png)

**Comment by jdcoats** [comment]
8 processes is about as good as i can get

![image](https://user-images.githubusercontent.com/42470924/145656184-fc79f920-e47a-4df8-8166-92c590dbb761.png)

**Comment by TheWitness** [comment]
I'm going to do a code review tomorrow to see if there is a way to squeeze a few more seconds out.  Stay tuned.  Glad the problem is fixed though.

**Comment by jdcoats** [comment]
perfect
