### ISSUE TITLE
Remote Poller Heartbeat notification

### ISSUE THREAD

**Issue by KnoAll** [Cacti/cacti#4499]
# Feature Request
It would be great to get a notification when a Remote Poller has not completed a poll or heartbeat connection
## Is your feature request related to a problem? Please describe
NO
A clear and concise description of what the problem is. Ex. 
I'm always frustrating when a Remote Poller has lost connection but there are no notifications and any devices run through that remote poller could be in an unknown state during that time.

## Describe the solution you'd like
An email to X when a poller has not checked in in X time

**Comment by bmfmancini** [comment]
I did a pr for this and it should be available in the 1.2.x branch under
pollers.php

**Comment by KnoAll** [comment]
Thanks, I only go on the main releases so I look forward to .20!

**Comment by TheWitness** [comment]
Me too.  Make for a good XMas break.
