### ISSUE TITLE
Boost log level, visibility and rotation?

### ISSUE THREAD

**Issue by KnoAll** [Cacti/cacti#4501]
I'm running boost on v1.2.19 and have seen that boost is logging to the cacti.log with debug entries. I do not see anywhere to control the log level of Boost to drop the debug entries? My system log is set to Low so it seems odd. Is there any way to adjust this to reduce verbosity?

Also, I see in /var/www/html/cacti/log/ that there is a boost.log file that also contains those debug entries, but this file does not get rotated like the cacti.log file, nor is it visible in the web UI like cacti.log or cacti_stderr.log so it is a massive file that has been running since I upgraded to .19. Should I setup logrotate to manage these or is there a native cacti/preferred method?

Also there is a minor spelling error in the log entries, 'it took 2 PASSED to complete' should likely say passes?

<html><body>

2021/12/10 11:03:34 - BOOST CHILD DEBUG: Processing Complete for Boost Process 4.  It took 2 passed to complete.
--
2021/12/10 11:03:34 - BOOST CHILD DEBUG: Processing Complete for Boost Process 2.  It took 2 passed to complete.
2021/12/10 11:03:34 - BOOST CHILD DEBUG: Processing Complete for Boost Process 5.  It took 2 passed to complete.
2021/12/10 11:03:20 - BOOST CHILD DEBUG: Processing 1 of 1 for Boost Process 5
2021/12/10 11:03:20 - BOOST CHILD DEBUG: Processing 1 of 1 for Boost Process 4
2021/12/10 11:03:20 - BOOST CHILD DEBUG: Processes:4, TotalRows:17915
2021/12/10 11:03:20 - BOOST CHILD DEBUG: Processing RRRtool Output for Boost Process 4
2021/12/10 11:03:20 - BOOST CHILD DEBUG: Processes:5, TotalRows:34898
2021/12/10 11:03:20 - BOOST CHILD DEBUG: Processing RRRtool Output for Boost Process 5
2021/12/10 11:03:20 - BOOST CHILD DEBUG: Processing 1 of 1 for Boost Process 3
2021/12/10 11:03:20 - BOOST CHILD DEBUG: Processing 1 of 1 for Boost Process 2
2021/12/10 11:03:20 - BOOST CHILD DEBUG: Processes:2, TotalRows:13221
2021/12/10 11:03:20 - BOOST CHILD DEBUG: Processes:3, TotalRows:13710
2021/12/10 11:03:20 - BOOST CHILD DEBUG: Processing RRRtool Output for Boost Process 2
2021/12/10 11:03:20 - BOOST CHILD DEBUG: Processing RRRtool Output for Boost Process 3
2021/12/10 11:03:20 - BOOST CHILD DEBUG: Processing 1 of 1 for Boost Process 1
2021/12/10 11:03:20 - BOOST CHILD DEBUG: Processes:1, TotalRows:23306
2021/12/10 11:03:20 - BOOST CHILD DEBUG: Processing RRRtool Output for Boost Process 1
2021/12/10 11:03:20 - POLLER: Poller[Main Poller] PID[3395] DEBUG: About to Spawn a Remote Process [CMD: /bin/php, ARGS: /var/www/html/cacti/poller_boost.php --child=5 --debug]
2021/12/10 11:03:20 - POLLER: Poller[Main Poller] PID[3395] DEBUG: About to Spawn a Remote Process [CMD: /bin/php, ARGS: /var/www/html/cacti/poller_boost.php --child=4 --debug]
2021/12/10 11:03:20 - POLLER: Poller[Main Poller] PID[3395] DEBUG: About to Spawn a Remote Process [CMD: /bin/php, ARGS: /var/www/html/cacti/poller_boost.php --child=3 --debug]
2021/12/10 11:03:20 - POLLER: Poller[Main Poller] PID[3395] DEBUG: About to Spawn a Remote Process [CMD: /bin/php, ARGS: /var/www/html/cacti/poller_boost.php --child=2 --debug]
2021/12/10 11:03:20 - POLLER: Poller[Main Poller] PID[3395] DEBUG: About to Spawn a Remote Process [CMD: /bin/php, ARGS: /var/www/html/cacti/poller_boost.php --child=1 --debug]

</body>
</html>

**Comment by TheWitness** [comment]
Under `Console > Configuration > Settings > Performance` I think you have the Boost debug log.  I would suggest that you for sure turn it off if you don't use it or have a reason to.  Good enhancement request none-the-less.

**Comment by KnoAll** [comment]
Understood. if it is logging to the main cacti.log then that is OK with me. Thanks

**Comment by TheWitness** [comment]
Got it.  Likely in the mean time, put the boost debug log, if you feel it's important into the log directory, or something like `/var/log/cacti/` and setup a `/etc/logrotate.d/` entry for it.  This is not high on anyones list either.  Not mine for sure.  Pull requests are always welcome of course.
