### ISSUE TITLE
Time issues still seem to exist in 1.2.19

### ISSUE THREAD

**Issue by alcatron** [Cacti/cacti#4502]
Hi, i previously logged a case having timezone issues in -30mins offsets in 1.2.17 based in IST or ACST timezones, i just did an upgrade to cacti 1.2.19 and now im seeing these errors. Anyone able to tell me how to fix this?

`

13-12-2021 17:18:42 - CMDPHP PHP ERROR NOTICE Backtrace: (/clog.php[27]:include(), /include/auth.php[28]:require_once(), /include/global.php[553]:cacti_time_zone_set(), /lib/functions.php[6588]:timezone_name_from_abbr(), CactiErrorHandler())
--
13-12-2021 17:18:42 - ERROR PHP NOTICE: A non well formed numeric value encountered in file: /usr/share/cacti/lib/functions.php on line: 6588
13-12-2021 17:18:40 - CMDPHP PHP ERROR NOTICE Backtrace: (/index.php[25]:include(), /include/auth.php[28]:require_once(), /include/global.php[553]:cacti_time_zone_set(), /lib/functions.php[6588]:timezone_name_from_abbr(), CactiErrorHandler())
13-12-2021 17:18:40 - ERROR PHP NOTICE: A non well formed numeric value encountered in file: /usr/share/cacti/lib/functions.php on line: 6588

`
`

13-12-2021 17:18:40 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/weathermap/weathermap-cacti-plugin.php[6]:include_once(), /include/auth.php[28]:require_once(), /include/global.php[553]:cacti_time_zone_set(), /lib/functions.php[6588]:timezone_name_from_abbr(), CactiErrorHandler())
--
13-12-2021 17:18:40 - ERROR PHP NOTICE: A non well formed numeric value encountered in file: /usr/share/cacti/lib/functions.php on line: 6588
13-12-2021 17:18:36 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/weathermap/weathermap-cacti-plugin.php[6]:include_once(), /include/auth.php[28]:require_once(), /include/global.php[553]:cacti_time_zone_set(), /lib/functions.php[6588]:timezone_name_from_abbr(), CactiErrorHandler())
13-12-2021 17:18:36 - ERROR PHP NOTICE: A non well formed numeric value encountered in file: /usr/share/cacti/lib/functions.php on line: 6588
13-12-2021 17:17:51 - CMDPHP PHP ERROR NOTICE Backtrace: (/clog.php[27]:include(), /include/auth.php[28]:require_once(), /include/global.php[553]:cacti_time_zone_set(), /lib/functions.php[6588]:timezone_name_from_abbr(), CactiErrorHandler())
13-12-2021 17:17:51 - ERROR PHP NOTICE: A non well formed numeric value encountered in file: /usr/share/cacti/lib/functions.php on line: 6588
13-12-2021 17:16:51 - CMDPHP PHP ERROR NOTICE Backtrace: (/clog.php[27]:include(), /include/auth.php[28]:require_once(), /include/global.php[553]:cacti_time_zone_set(), /lib/functions.php[6588]:timezone_name_from_abbr(), CactiErrorHandler())
13-12-2021 17:16:51 - ERROR PHP NOTICE: A non well formed numeric value encountered in file: /usr/share/cacti/lib/functions.php on line: 6588
13-12-2021 17:15:50 - CMDPHP PHP ERROR NOTICE Backtrace: (/clog.php[27]:include(), /include/auth.php[28]:require_once(), /include/global.php[553]:cacti_time_zone_set(), /lib/functions.php[6588]:timezone_name_from_abbr(), CactiErrorHandler())
13-12-2021 17:15:50 - ERROR PHP NOTICE: A non well formed numeric value encountered in file: /usr/share/cacti/lib/functions.php on line: 6588

`

**Comment by TheWitness** [comment]
Please test the lib/functions.php from the 1.2.x branch.

**Comment by alcatron** [comment]
i renamed functions.php to functions.php.old, and put in the newer one from the branch, now the cacti main login page doesnt even work, its just a blank page..

**Comment by xmacan** [comment]
check file permissions

**Comment by alcatron** [comment]
its like for like permissions..

**Comment by TheWitness** [comment]
You should review the cacti.log for errors.

**Comment by TheWitness** [comment]
What's your client timezone?

**Comment by alcatron** [comment]
Ok will check cacti.log, client is ACST

 

From: TheWitness ***@***.***>
Reply to: Cacti/cacti ***@***.***>
Date: Wednesday, 15 December 2021 at 11:27
To: Cacti/cacti ***@***.***>
Cc: alcatron ***@***.***>, Author ***@***.***>
Subject: Re: [Cacti/cacti] Time issues still seem to exist in 1.2.19 (Issue #4502)

 

What's your client timezone?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by alcatron** [comment]
hi, i checked cacti.log , there is nothing in the logs related to the access. The main page is just blank when functions.php is replaced with the newer one, nothing is logged in the file, even the poller stopps working.

To double check, i even re-downloaded the files from cacti site and replaced it again, still the same white page, and poller stops working. I rename it back to the old functions.php file, and things work fine, except various errors show in the log file related to the time etc

**Comment by alcatron** [comment]
I checked apache httpd access logs and this shows up

[16/Dec/2021:20:49:27 +1030] "GET /cacti/index.php HTTP/1.1" 500 -
[16/Dec/2021:20:49:29 +1030] "GET /cacti/index.php HTTP/1.1" 500 -
[16/Dec/2021:20:49:30 +1030] "GET /cacti/index.php HTTP/1.1" 500 -
[16/Dec/2021:20:49:35 +1030] "GET /cacti/index.php HTTP/1.1" 500 -
[16/Dec/2021:20:49:35 +1030] "GET /cacti/index.php HTTP/1.1" 500 -
[16/Dec/2021:20:49:36 +1030] "GET /cacti/index.php HTTP/1.1" 500 -
[16/Dec/2021:20:58:46 +1030] "GET /cacti/index.php HTTP/1.1" 500 -

Its an error 500 after changing the functions.php file

**Comment by netniV** [comment]
You need to refer to the apache error log file then.

**Comment by alcatron** [comment]
apache error log file shows nothing, only the access log with an error of 500 to the cacti website, change back the older functions.php file, and it works fine

**Comment by cigamit** [comment]
I would enable display_errors in your php.ini so that you can see what the error is when you get a 500 status.  Its happening before our error handler loads, so we can't catch it.

**Comment by TheWitness** [comment]
Can you pull lib/functions.pho from the 1.2.x branch and test using it?  Your in one of those weird timezones, but there are some fresh changes there.

**Comment by alcatron** [comment]
Thats what ive been saying in this thread i just pulled the latest 1.2 branch with thay file and it doesnt work, it breaks cacti completely the new functions.php file.

Going to enable php.ini to display errors, as apache access log is error 500 as soon as the newer functions.php is added.

**Comment by netniV** [comment]
there is an apache log and an error log, the errors for 500 go into a separate file.

**Comment by alcatron** [comment]
ok found the error when i enabled display errors , as per cigamit recommendation

Parse error: syntax error, unexpected ':', expecting variable (T_VARIABLE) in /usr/share/cacti/lib/functions.php on line 3841

**Comment by TheWitness** [comment]
You grabbed `develop` and not the `1.2.x` branch.  Try pulling it from the correct repo.

**Comment by alcatron** [comment]
apologies, i realized that now, i got the right one now, i can load the website, in the cacti log i see this now
Error 6604, vs previous it was 6588

 
22-12-2021 13:57:54 - CMDPHP PHP ERROR NOTICE Backtrace: (/clog.php[27]:include(), /include/auth.php[28]:require_once(), /include/global.php[553]:cacti_time_zone_set(), /lib/functions.php[6604]:timezone_name_from_abbr(), CactiErrorHandler())
--
22-12-2021 13:57:54 - ERROR PHP NOTICE: A non well formed numeric value encountered in file: /usr/share/cacti/lib/functions.php on line: 6604
22-12-2021 13:57:54 - CMDPHP PHP ERROR NOTICE Backtrace: (/graph_json.php[32]:include(), /include/auth.php[28]:require_once(), /include/global.php[553]:cacti_time_zone_set(), /lib/functions.php[6604]:timezone_name_from_abbr(), CactiErrorHandler())
22-12-2021 13:57:54 - ERROR PHP NOTICE: A non well formed numeric value encountered in file: /usr/share/cacti/lib/functions.php on line: 6604
22-12-2021 14:00:06 - ERROR PHP NOTICE: A non well formed numeric value encountered in file: /usr/share/cacti/lib/functions.php on line: 6604

**Comment by TheWitness** [comment]
Okay, let me dig in.

**Comment by TheWitness** [comment]
What version of PHP are you using?

**Comment by TheWitness** [comment]
Grab the latest lib/functions.php.  I see my mistake.

**Comment by alcatron** [comment]
thanks TheWitness i can confirm it is fixed now and errors have gone
