### ISSUE TITLE
There is no data in the image in 1.2.19

### ISSUE THREAD

**Issue by underdog-Fu** [Cacti/cacti#4507]
Hello
I upgraded the version to 1.2.19
When I draw the switch port traffic, I can draw an rrd file , but unable to display traffic，like this
![image](https://user-images.githubusercontent.com/46416973/146319023-2c747fe7-df72-419d-b8d6-64a8f2219a78.png)

When I fallback version to 1.2.18,It's working normally, like this
![image](https://user-images.githubusercontent.com/46416973/146319232-fe3e2865-534d-4769-8748-7f3602854a45.png)

I wonder if this is a new version of the bug , and how to solve this problem
Best wishes

**Comment by bmfmancini** [comment]
Usually related to file permissions

**Comment by underdog-Fu** [comment]
Thank you for your reply, but the permissions of the files on both sides are the same

**Comment by TheWitness** [comment]
Are there poller cache entries for the Graph?  Is the poller running?  What does the Cacti log look like?

**Comment by underdog-Fu** [comment]
I think poller cache entries for the graph, and the state of poller is idle/running
At the beginning, I executed 'rrdtool fetch xxx.rrd AVERAGE' in the /rra file, returns 'nan'
After waiting for 4 hours, the graph automatically draws the data,
May I ask what may cause the failure

**Comment by TheWitness** [comment]
Well, you can get `NaN` if the value exceeds the max value in the RRDfile.  Run spine in at `-V 3` mode and make sure you get entries for the graphs in question.  Also, the `rrdtool info` has a `last_ds`, that should provide a number.  If it's above the MAX value in the RRDfile, you will never see data.

**Comment by TheWitness** [comment]
![image](https://user-images.githubusercontent.com/1439914/147006451-253f63b1-aeb9-4d20-ba99-e1b223fa3fee.png)

**Comment by underdog-Fu** [comment]
Thank you for your reply
But I checked RRD info and found that last_ DS ='u ', as shown below
![image](https://user-images.githubusercontent.com/46416973/147176996-46706d4b-ea30-4615-9c5b-d1d1be1c73c5.png)

**Comment by netniV** [comment]
A `U` generally means undefined or unknown, so no data was populated.

**Comment by underdog-Fu** [comment]
I think I found the cause of the problem
My previous version of spine was 1.1.12, and cacti I upgraded to 1.2.19, resulting in version mismatch
I upgraded the spine to the latest cacti-spine-1.2.19, all cacti images can be drawn normally
Thank you very much for your reply and best wishes
