### ISSUE TITLE
CLI add_device.php won't add duplicate IPs to the database

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#451]
$ /usr/local/php/bin/php -q add_device.php --description=test3 --ip=127.0.0.1
ERROR: This IP already exists in the database (127.0.0.1) device-id: (189)

I can create separate instances of a device using the same IP in the GUI, not sure why the CLI wouldn't allow this.

**Comment by cigamit** [comment]
Use the --proxy boolean option.  That will fix you up.
