### ISSUE TITLE
a few poller_item entries in main poller not synced to same table on remote poller

### ISSUE THREAD

**Issue by gj00354347** [Cacti/cacti#4510]
# Describe the bug

a week ago 3 interface graphs of a device  stopped populating in our cacti 1.2.18 which has a multi poller environment  , it were virtual interface ones  and the device was being polled from one of the remote pollers.
so my first guess was like for virtual interface we have set the max data source to 1G and I though that it might have exceeded that so Increased that to 100G using rrdtool tune command .

after doing that I enabled the device debug to see like what's being polled and what's being retrieved and what I found that nothing was in the logs for any KPI of that particular device.(grep -i 'device\[hostid\]' cacti.log) Although rest KPI are being polled and even being populated . Since it is a remote poller , so I was checking logs on remote pollers as it happens the device logs are stored on the poller from where it is being polled . In fact I checked on main poller as well to find nothing .

**so 1st question : Despite enabling the device debug why cant I see the logs .although on remote poller in table settings i see selective device debug is on for the device mentioned here and so in main poller settings table.**

**and why all of a sudden these 3  entries got removed from poller_item of remote poller and never got in sync with main poller .** Although when i create the new graphs the items of poller_item table gets replicated to remote poller but not in case of poller_item . Although I do accept that I have set poller sync to manual and its not automatic but I think that has no role to play here as as when new graphs are created , same is pushed from main to remote pollers. And even for this particular device we have all in sync in poller_item like out of 50 , 47 are in sync except these 3 items .

so what made them disappear from remote poller causing this gap in graphs.

on main poller we see entries

MariaDB [cacti]> select host_id, rrd_path from poller_item where rrd_path='<cacti-home>/rra/321/575385.rrd';
+---------+----------------------------------------+
| host_id | rrd_path                               |
+---------+----------------------------------------+
|     321 | <cacti-home>/rra/321/575385.rrd |
|     321 | <cacti-home>/rra/321/575385.rrd |
+---------+----------------------------------------+
2 rows in set (0.73 sec)

MariaDB [cacti]> select host_id, rrd_path from poller_item where rrd_path='<cacti-home>/rra/321/575386.rrd';
+---------+----------------------------------------+
| host_id | rrd_path                               |
+---------+----------------------------------------+
|     321 | <cacti-home>/rra/321/575386.rrd |
|     321 | <cacti-home>/rra/321/575386.rrd |
+---------+----------------------------------------+
2 rows in set (0.85 sec)

MariaDB [cacti]> select host_id, rrd_path from poller_item where rrd_path='<cacti-home>/rra/321/575387.rrd';
+---------+----------------------------------------+
| host_id | rrd_path                               |
+---------+----------------------------------------+
|     321 | <cacti-home>/rra/321/575387.rrd |
|     321 | <cacti-home>/rra/321/575387.rrd |
+---------+----------------------------------------+

but on remote poller these are missing

MariaDB [cacti]>  select host_id, rrd_path from poller_item where rrd_path='<cacti-home>/rra/321/575385.rrd';
Empty set (0.27 sec)

MariaDB [cacti]>  select host_id, rrd_path from poller_item where rrd_path='<cacti-home>/321/575385.rrd';
Empty set (0.26 sec)

MariaDB [cacti]>  select host_id, rrd_path from poller_item where rrd_path='<cacti-home>/rra/321/575386.rrd';
Empty set (0.26 sec)

MariaDB [cacti]>  select host_id, rrd_path from poller_item where rrd_path='<cacti-home>/rra/321/575387.rrd';
Empty set (0.26 sec)

## To Reproduce

I do not know like what exactly cause this although the explanation that poller sync is set to manual does not give the proper reasons.

## Desktop (please complete the following information)

cacti 1.2.18 
on remote as well as on main poller RHEL 7.8 Maipo
mysql on remote as well as main poller  Distrib 5.5.65-MariaDB
spine on main 1.2.19
spine on remote 1.2.17

**Comment by gj00354347** [comment]
yes Gentlemen ,

one update , as a last resort I did a manual sync of remote pollers with the main poller and 3 lost entries of poller_item of remote poller got populated and graphs started populating again .

but again the same question what made those 3 entries disappear from poller_item of remote poller.

**Comment by TheWitness** [comment]
My guess is that when they were reindexed, the interfaces became orphans.  The way the orphan design worked is that orphans get removed from the poller items table till the index either reappears or the data source is removed.  My guess is that there is still some cases with remote data collection where there are gaps in design.  A full sync was the right move.  I'm on vacation for a while now.  Hopefully I can make some time for Cacti.

**Comment by TheWitness** [comment]
@gj00354347, If this happens again, there is an "orphan" column in the data_local table.  In the case where the re-index does not find the index, the value is cleared from data_local's "snmp_index" column, and the "orphan" column will be set to 1.  The memory of the actual index is kept in the data_input_data table, so that if a subsequent re-index returns the primary key, it will properly be re-associated with the snmp_index in the data_local table and the poller item table will get re-filled and the object should start getting queried again.

So, the next time this happens, before you sync everything you can take a deeper dive into the behavior.

**Comment by TheWitness** [comment]
Sorry @gj00354347, been busy on the day job and trying to resolve things in front of me.

**Comment by TheWitness** [comment]
@gj00354347, we did fixup a few things on the 1.2.20 front.  So, I suspect that this will be resolved on the next release.  In the mean time, performing periodic full sync's will help.  I will see if I can link the fix here and then close this as duplicate.

**Comment by TheWitness** [comment]
Here are a few of them:

https://github.com/Cacti/cacti/issues/4491

https://github.com/Cacti/cacti/issues/4480

https://github.com/Cacti/cacti/issues/4508

Hopefully the release will get out there soon enough.

**Comment by netniV** [comment]
That is still waiting on code being stable first :)
