### ISSUE TITLE
SQL Backtrace fail

### ISSUE THREAD

**Issue by manhvu1997** [Cacti/cacti#4513]
# Describe the bug

I install cacti 1.2.19 on ubuntu 20.04. After everything is installed, I have some errors related to poller.php

## To Reproduce

1. Install cacti 1.2.19

2. Install weathermap 0.98a

3. Go to Clog tab and the error appeared

## Screenshots

This is my error:
![ảnh](https://user-images.githubusercontent.com/58839875/147212543-c6cc312f-f430-449d-a1ea-8963e7fd73f6.png)

## Desktop (please complete the following information)

- OS: Ubuntu 20.04

- Browser: Firefox

- Cacti: 1.2.19
- PHP: 8.0.13
- Mariadb: 10.05

**Comment by TheWitness** [comment]
Need the full backtrace too.

**Comment by TheWitness** [comment]
Grab the latest `lib/poller.php` from the 1.2.x branch.  Then close this ticket when it starts working again.

**Comment by TheWitness** [comment]
@manhvu1997, Still waiting on feedback.

**Comment by TheWitness** [comment]
@manhvu1997, I'm just going to close.  Update your lib/poller.php and poller.php from the 1.2.x branch and this problem should be resolved.
