### ISSUE TITLE
Cacti automation and polling not working in remote pollers

### ISSUE THREAD

**Issue by kasimanikandan** [Cacti/cacti#4514]
# Describe the bug
I have installed cacti v1.2.19 with multi poller setup 1 main poller and 3 remote poller and noticed an issues with all the remote poller.
remote pollers status always showing running even for 1 device polling with 102 Data sources but cacti logs says Maximum runtime of 298 seconds exceeded. Exiting. but when i run spine manually from remote poller severs its completed in less then 1 second and no errors. could you please advise the root cause of this issue.

Note: If i add devices to main poller its working fine, means main poller working as expected and graphs are getting platted.

OS: Redhat 7 (Linux)
Cacti Version : 1.2.19
Spine Version : 1.2.19
PHP Version : 7.3
MariaDB Version : 10.32

Polling interval: Every 1 mins 

Remote poller log:
2021-12-25 18:45:00 - POLLER: Poller[Remote Poller 1] PID[125051] Maximum runtime of 298 seconds exceeded. Exiting.
2021-12-25 18:41:00 - SYSTEM STATS: Time:0.1111 Method:spine Processes:1 Threads:1 Hosts:1 HostsPerProcess:1 DataSources:102 RRDsProcessed:0
2021-12-25 18:41:00 - SYSTEM WARNING: Primary Admin account notifications disabled! Unable to send administrative Email.
2021-12-25 18:41:00 - POLLER: Poller[Remote Poller 1] PID[124669] Maximum runtime of 298 seconds exceeded. Exiting.
2021-12-25 18:40:00 - SYSTEM STATS: Time:0.1098 Method:spine Processes:1 Threads:1 Hosts:1 HostsPerProcess:1 DataSources:102 RRDsProcessed:0
2021-12-25 18:40:00 - SYSTEM WARNING: Primary Admin account notifications disabled! Unable to send administrative Email.
2021-12-25 18:40:00 - POLLER: Poller[Remote Poller 1] PID[124669] Maximum runtime of 298 seconds exceeded. Exiting.
2021-12-25 18:40:00 - SYSTEM WARNING: Primary Admin account notifications disabled! Unable to send administrative Email.
2021-12-25 18:40:00 - SYSTEM STATS: Time:298.4057 Method:spine Processes:1 Threads:1 Hosts:1 HostsPerProcess:1 DataSources:102 RRDsProcessed:0
2021-12-25 18:40:00 - SYSTEM WARNING: Primary Admin account notifications disabled! Unable to send administrative Email.
2021-12-25 18:40:00 - POLLER: Poller[Remote Poller 1] PID[124669] Maximum runtime of 298 seconds exceeded. Exiting.
2021-12-25 18:38:00 - SYSTEM STATS: Time:0.1105 Method:spine Processes:1 Threads:1 Hosts:1 HostsPerProcess:1 DataSources:102 RRDsProcessed:0

Spine Debug Log:
./spine -R -S -V 5
SPINE: Using spine config file [../etc/spine.conf]
Total[0.0060] DEBUG: The path_php_server variable is /usr/share/cacti/script_server.php
Total[0.0060] DEBUG: The path_cactilog variable is /usr/share/cacti/log/cacti.log
Total[0.0060] DEBUG: The log_destination variable is 4 (STDOUT)
Total[0.0063] DEBUG: The path_php variable is /opt/rh/rh-php73/root/usr/bin/php
Total[0.0065] DEBUG: The availability_method variable is 2
Total[0.0066] DEBUG: The ping_recovery_count variable is 3
Total[0.0068] DEBUG: The ping_failure_count variable is 2
Total[0.0069] DEBUG: The ping_method variable is 2
Total[0.0071] DEBUG: The ping_retries variable is 1
Total[0.0073] DEBUG: The ping_timeout variable is 400
Total[0.0074] DEBUG: The snmp_retries variable is 3
Total[0.0076] DEBUG: The log_perror variable is 1
Total[0.0077] DEBUG: The log_pwarn variable is 0
Total[0.0079] DEBUG: The boost_redirect variable is 1
Total[0.0081] DEBUG: The boost_rrd_update_enable variable is 1
Total[0.0083] DEBUG: The log_pstats variable is 0
Total[0.0084] DEBUG: The threads variable is 1
Total[0.0086] DEBUG: The polling interval is 60 seconds
Total[0.0088] DEBUG: The number of concurrent processes is 1
Total[0.0089] DEBUG: The script timeout is 25
Total[0.0091] DEBUG: The selective_device_debug variable is 5,4
Total[0.0093] DEBUG: The spine_log_level variable is 0
Total[0.0094] DEBUG: The number of php script servers to run is 1
Total[0.0096] DEBUG: The number of active data source profiles is 1
Total[0.0098] DEBUG: StartDevice='-1', EndDevice='-1', TotalPHPScripts='0'
Total[0.0098] DEBUG: The PHP Script Server is Not Required
Total[0.0099] DEBUG: The Maximum SNMP OID Get Size is 10
Total[0.0100] DEBUG: Selective Debug Devices 5,4
Total[0.0103] DEBUG: Total Connections made 1
Total[0.0103] DEBUG: Creating Local Connection Pool of 1 threads.
Total[0.0103] DEBUG: Creating Local Connection 0.
Total[0.0106] DEBUG: Total Connections made 2
Total[0.0106] DEBUG: Version 1.2.19 starting
Total[0.0106] DEBUG: MySQL is Thread Safe!
Total[0.0106] DEBUG: Spine running as 0 UID, 0 EUID
Total[0.0107] DEBUG: Spine is running as root.
Total[0.0107] DEBUG: Spine has got ICMP
Total[0.0107] DEBUG: Initializing Net-SNMP API
Total[0.0107] DEBUG: Issues with SNMP Header Version information, assuming old version of Net-SNMP.
Total[0.0120] DEBUG: Initializing PHP Script Server(s)
Total[0.0132] Spine will support multithread device polling.
Total[0.0135] DEBUG: Initial Value of Available Threads is 1 (0 outstanding)
Total[0.0138] DEBUG: Valid Thread to be Created (140307546380032)
Total[0.0138] DEBUG: Available Threads is 0 (1 outstanding)
Total[0.0138] WARNING: Device[0] polling sleeping while waiting for 1 Threads to End
Total[0.0139] DEBUG: Device[0] HT[1] In Poller, About to Start Polling
Total[0.0140] DEBUG: Traversing Local Connection Pool for free connection.
Total[0.0140] DEBUG: Checking Local Pool ID 0.
Total[0.0140] DEBUG: Allocating Local Pool ID 0.
Total[0.0146] Device[0] HT[1] Total Time: 0.00071 Seconds
Total[0.0149] DEBUG: Freeing Local Pool ID 0
Total[0.0149] DEBUG: Device[0] HT[1] DEBUG: HOST COMPLETE: About to Exit Device Polling Thread Function
Total[0.5140] The final count of Threads is 0
Total[0.5140] INFO: Thread complete for Device[0] and 0 to 0 sources
Total[0.5140] DEBUG: Closing Local Connection Pool ID 0
Total[0.5141] DEBUG: Thread Cleanup Complete
Total[0.5141] DEBUG: PHP Script Server Pipes Closed
Total[0.5141] DEBUG: Allocated Variable Memory Freed
Total[0.5142] DEBUG: MYSQL Free & Close Completed
Total[0.5144] DEBUG: Net-SNMP Close Completed
Total[0.5144] Time: 0.5143 s, Threads: 1, Devices: 1

Thanks in advance,

Regard,
Mani

**Comment by bmfmancini** [comment]
Both of these bugs have been corrected in the 1.2.x branch

**Comment by kasimanikandan** [comment]
Thanks @bmfmancini for reply.

could you please advise what could be the probable root cause of pollers getting exited after x seconds ? and poller status always showing running.. no error is log either.

Thanks,
Mani

**Comment by bmfmancini** [comment]
Yea there was a bug in poller.pho file that was corrected in the 1.2.x
branch

I believe you will need to pull down both poller. PHP and lib/poller.php

**Comment by kasimanikandan** [comment]
Thanks @bmfmancini.. i got it... will try it out with 1.2.x 

Cheers,
Mani

**Comment by TheWitness** [comment]
Marking this resolved and duplicate.
