### ISSUE TITLE
Poller Output Table not empty for poller id 1

### ISSUE THREAD

**Issue by hvspa** [Cacti/cacti#4515]
hi,

After recent upgrade from v1.2.15 to 1.2.19 (yum upgrade cacti -y) i started to receive warning emails like below:

`WARNING: Poller Output Table not Empty.  Issues: 4, DS[1505, 2702, 2702, 1505]`

this is what i see in database:
`MariaDB [cacti]> select now(); select * from poller_output;
+---------------------+
| now()               |
+---------------------+
| 2021-12-25 23:41:03 |
+---------------------+
1 row in set (0.000 sec)

+---------------+-------------+---------------------+----------------+
| local_data_id | rrd_name    | time                | output         |
+---------------+-------------+---------------------+----------------+
|          1505 | traffic_in  | 2021-12-25 23:30:22 | 0              |
|          2702 | traffic_out | 2021-12-25 23:35:21 | 81243707482547 |
|          1505 | traffic_in  | 2021-12-25 23:35:21 | 0              |
|          1505 | traffic_out | 2021-12-25 23:40:37 | 0              |
|          2702 | traffic_out | 2021-12-25 23:40:24 | 81243709835415 |
|          2702 | traffic_in  | 2021-12-25 23:35:10 | 8229093740365  |
|          1505 | traffic_out | 2021-12-25 23:35:35 | 0              |
|          1505 | traffic_in  | 2021-12-25 23:40:24 | 0              |
|          2702 | traffic_in  | 2021-12-25 23:40:11 | 8229095876187  |
|          2702 | traffic_in  | 2021-12-25 23:30:10 | 8229091613318  |
|          1505 | traffic_out | 2021-12-25 23:30:36 | 0              |
|          2702 | traffic_out | 2021-12-25 23:30:22 | 81243705127770 |
+---------------+-------------+---------------------+----------------+
12 rows in set (0.000 sec)

MariaDB [cacti]>`

then i tried to upgrade to version 1.2.20 manually from git. but the issue is still there, always getting non empty output table

the problem is that graphs for mentioned DS are not any more plotting. initially these DS were different, i tried to remove them, then rebuild the indexes, but what happens is that after that another one is breaking and  stops plotting right after i re-index the device and new DS starting to report on the poller table

Not sure what is wrong with it. any ideas on how to tackle this?

in version 1.2.15 i was not getting such things and all the graphs were ok. the last one which stopped to plot after removing previous "broken" and re-indexing:

![image](https://user-images.githubusercontent.com/27876987/147392571-47bd4440-71ed-49d1-b204-511ac6e5da5c.png)

- OS: win 10

- Browser Firefox

- Version 95

Q: how to fix the non-empty poller table ina way that the graphs will not suffer?

thanks

**Comment by TheWitness** [comment]
Grab the latest lib/poller.php and poller.php from GitHub 1.2.x branch.  This issue is duplicate and resolved.

**Comment by hvspa** [comment]
> Grab the latest lib/poller.php and poller.php from GitHub 1.2.x branch. This issue is duplicate and resolved.

thanks very much for response. i have copied both poller.php files from branch you mentioned, but the warnings are still there. 


MariaDB [cacti]> select now(); select * from poller_output;
+---------------------+
| now()               |
+---------------------+
| 2021-12-29 20:57:46 |
+---------------------+
1 row in set (0.000 sec)

+---------------+-------------+---------------------+----------------+
| local_data_id | rrd_name    | time                | output         |
+---------------+-------------+---------------------+----------------+
|          1507 | traffic_in  | 2021-12-29 20:50:23 | 0              |
|          1507 | traffic_in  | 2021-12-29 20:55:22 | 0              |
|          1507 | traffic_in  | 2021-12-29 20:45:23 | 0              |
|          2702 | traffic_out | 2021-12-29 20:50:23 | 81246488297434 |
|          2702 | traffic_out | 2021-12-29 20:55:22 | 81246490634863 |
|          2702 | traffic_out | 2021-12-29 20:45:23 | 81246485957357 |
|          1507 | traffic_out | 2021-12-29 20:45:36 | 0              |
|          1507 | traffic_out | 2021-12-29 20:55:36 | 0              |
|          1507 | traffic_out | 2021-12-29 20:50:36 | 0              |
|          2702 | traffic_in  | 2021-12-29 20:45:11 | 8231834593590  |
|          2702 | traffic_in  | 2021-12-29 20:50:10 | 8231836713207  |
|          2702 | traffic_in  | 2021-12-29 20:55:10 | 8231838840462  |
+---------------+-------------+---------------------+----------------+
12 rows in set (0.001 sec)

MariaDB [cacti]> 

any other files needs to be updated?

**Comment by TheWitness** [comment]
Are you running the latest spine?

**Comment by hvspa** [comment]
i guess i am not running spine. how can i check that?

**Comment by TheWitness** [comment]
Looks like you pulled from the `develop` branch and not the `1.2.x` branch.  Please pull again.

**Comment by hvspa** [comment]
> Looks like you pulled from the `develop` branch and not the `1.2.x` branch. Please pull again.

hi and happy new year!!! 

on dec 23rd i have copied from 1.2.x, command i used was: `git clone **-b 1.2.x** https://github.com/cacti/cacti.git cacti.new`

then i moved existing cacti folder to cacti 1.9:

`drwxr-xr-x   10 root   root   4.0K Dec 23 00:13 cacti.19
drwxr-xr-x   21 apache apache 4.0K Dec 29 21:08 cacti`

and moved `cacti.new` to `cacti`

then i copied the `rra` files into new cacti folder:

`yes | cp -pR /usr/share/cacti.19/rra/ /usr/share/cacti/`

that fixed few issues, but the issue with non-empty table was still there. there was a warning in the logs regarding the db exec failure, i fixed it by manually adding the column in the table:

`MariaDB [cacti]> ALTER TABLE host ADD COLUMN snmp_sysUpTimeInstanceAlt bigint(20) unsigned default '0' NOT NULL AFTER snmp_sysUpTimeInstance ;
Query OK, 0 rows affected (0.023 sec)
Records: 0  Duplicates: 0  Warnings: 0`

however, the non-empty table is still there:( do you have any other ideas what can cause this?

thanks in advance,

**Comment by TheWitness** [comment]
I would not use the procedure that you did.  If you are interested in a backup, I would do something like the following.

1) Symlink the rra folder to a separate location.
2) Use the following for the upgrade process.

```sh
# Switch to Web Root
cd /var/www/html
# Backup the setup
tar -zcf cacti.$$.tgz cacti
# Grab the new Cacti
git clone -b 1.2.x https://github.com/cacti/cacti.git cacti.new
# Force Copy the new over the old
/bin/cp -rpf cacti.new/* cacti
# Make sure everything is owned by the web server
chown -R apache:apache cacti
```

Also, switch to spine and see if it happens again.  If it does, turn on Device Debug for any devices that are not emptying out of the poller_output table and see if you are getting any errors.

**Comment by hvspa** [comment]
> I would not use the procedure that you did. If you are interested in a backup, I would do something like the following.
> 
> 1. Symlink the rra folder to a separate location.
> 2. Use the following for the upgrade process.
> 
> ```shell
> # Switch to Web Root
> cd /var/www/html
> # Backup the setup
> tar -zcf cacti.$$.tgz cacti
> # Grab the new Cacti
> git clone -b 1.2.x https://github.com/cacti/cacti.git cacti.new
> # Force Copy the new over the old
> /bin/cp -rpf cacti.new/* cacti
> # Make sure everything is owned by the web server
> chown -R apache:apache cacti
> ```
> 
> Also, switch to spine and see if it happens again. If it does, turn on Device Debug for any devices that are not emptying out of the poller_output table and see if you are getting any errors.

thank you very much. 
i have installed the spine, and now the poller table is empty. and the polling is happening in 27 seconds instead of previous 45.
do you know why could have cmd.php not emptying the table and spine is emptying? 
also, i know it is not related to this issue, but do you know what to do with these warnings?

`2022/01/09 02:20:29 - POLLER: Poller[1] PID[10174] WARNING: You have 5 Devices with bad SNMP Indexes.  Devices: Device[4], Device[10], Device[17], Device[20], Device[21] totalling 29 Data Sources.  Please Either Re-Index, Delete or Disable these Data Sources.`

after re-indexing i am seeing these in the logs:

`2022/01/09 02:12:31 - DSTRACE Running Re-Index for Device[10], DQ[4]
2022/01/09 02:12:35 - DSTRACE Available Sort Fields for Re-Index for Device[10], DQ[4] are [ifName:ifDescr:ifHwAddr:ifIndex]
2022/01/09 02:12:35 - DSTRACE Field Name 'ifIndex' is an SNMP index and suitable Re-Index for Device[10], DQ[4]
2022/01/09 02:12:35 - DSTRACE Field Name 'ifOperStatus' found not suitable during Re-Index for Device[10], DQ[4]
2022/01/09 02:12:35 - DSTRACE Field Name 'ifAdminStatus' found not suitable during Re-Index for Device[10], DQ[4]
2022/01/09 02:12:35 - DSTRACE Field Name 'ifDescr' found suitable during Re-Index for Device[10], DQ[4]
2022/01/09 02:12:35 - DSTRACE Field Name 'ifName' found suitable during Re-Index for Device[10], DQ[4]
2022/01/09 02:12:35 - DSTRACE Field Name 'ifAlias' found not suitable during Re-Index for Device[10], DQ[4]
2022/01/09 02:12:35 - DSTRACE Field Name 'ifType' found not suitable during Re-Index for Device[10], DQ[4]
2022/01/09 02:12:35 - DSTRACE Field Name 'ifSpeed' found not suitable during Re-Index for Device[10], DQ[4]
2022/01/09 02:12:35 - DSTRACE Field Name 'ifHighSpeed' found not suitable during Re-Index for Device[10], DQ[4]
2022/01/09 02:12:35 - DSTRACE Field Name 'ifHwAddr' found not suitable.  Non-unique and nonunique not specified during Re-Index for Device[10], DQ[4]
2022/01/09 02:12:35 - DSTRACE Field Name 'ifIP' found not suitable during Re-Index for Device[10], DQ[4]
2022/01/09 02:12:35 - DSTRACE Field Name 'ifIPv6' found not suitable during Re-Index for Device[10], DQ[4]`
