### ISSUE TITLE
PHP Backtrace Warning with -git 1.2.x Branch on Hourly DSSTATS

### ISSUE THREAD

**Issue by reubenfarrelly** [Cacti/cacti#4517]
Every hour or so I am seeing a backtrace logged:

26/Dec/2021 15:35:28 - SYSTEM DSSTATS STATS: Type:HOURLY, Time:0.01
26/Dec/2021 15:35:28 - SYSTEM STATS: Time:26.2516 Method:cmd.php Processes:1 Threads:1 Hosts:26 HostsPerProcess:26 DataSources:418 RRDsProcessed:249
26/Dec/2021 15:30:31 - SYSTEM DSSTATS STATS: Type:DAILY, Time:2.01 Threads:1 RRDfiles: DSSes: RRDUser:0.00 RRDSystem:0.00 RRDReal:0.00
26/Dec/2021 15:30:31 - CMDPHP PHP ERROR WARNING Backtrace: (/poller_dsstats.php[145]:dsstats_master_handler(), /poller_dsstats.php[262]:CactiErrorHandler())
26/Dec/2021 15:30:31 - ERROR PHP WARNING: Undefined variable $type in file: /var/www/cacti/htdocs/poller_dsstats.php on line: 262
26/Dec/2021 15:30:28 - CMDPHP PHP ERROR WARNING Backtrace: (/poller_dsstats.php[145]:dsstats_master_handler(), /poller_dsstats.php[259]:CactiErrorHandler())
26/Dec/2021 15:30:28 - ERROR PHP WARNING: Undefined variable $type in file: /var/www/cacti/htdocs/poller_dsstats.php on line: 259
26/Dec/2021 15:30:28 - SYSTEM DSSTATS STATS: Type:HOURLY, Time:0.01
26/Dec/2021 15:30:28 - SYSTEM STATS: Time:26.2487 Method:cmd.php Processes:1 Threads:1 Hosts:26 HostsPerProcess:26 DataSources:418 RRDsProcessed:249
26/Dec/2021 15:25:29 - SYSTEM DSSTATS STATS: Type:HOURLY, Time:0.01
26/Dec/2021 15:25:28 - SYSTEM STATS: Time:26.2555 Method:cmd.php Processes:1 Threads:1 Hosts:26 HostsPerProcess:26 DataSources:418 RRDsProcessed:249
26/Dec/2021 15:20:29 - SYSTEM DSSTATS STATS: Type:HOURLY, Time:0.01
26/Dec/2021 15:20:28 - SYSTEM STATS: Time:26.2584 Method:cmd.php Processes:1 Threads:1 Hosts:26 HostsPerProcess:26 DataSources:418 RRDsProcessed:249
26/Dec/2021 15:15:29 - SYSTEM DSSTATS STATS: Type:HOURLY, Time:0.02
26/Dec/2021 15:15:28 - SYSTEM STATS: Time:26.2511 Method:cmd.php Processes:1 Threads:1 Hosts:26 HostsPerProcess:26 DataSources:418 RRDsProcessed:249
26/Dec/2021 15:10:28 - SYSTEM DSSTATS STATS: Type:HOURLY, Time:0.02
26/Dec/2021 15:10:28 - SYSTEM STATS: Time:26.2518 Method:cmd.php Processes:1 Threads:1 Hosts:26 HostsPerProcess:26 DataSources:418 RRDsProcessed:249
26/Dec/2021 15:05:29 - SYSTEM DSSTATS STATS: Type:HOURLY, Time:0.02
26/Dec/2021 15:05:28 - SYSTEM STATS: Time:26.2564 Method:cmd.php Processes:1 Threads:1 Hosts:26 HostsPerProcess:26 DataSources:418 RRDsProcessed:249
26/Dec/2021 15:00:28 - SYSTEM DSSTATS STATS: Type:HOURLY, Time:0.02
26/Dec/2021 15:00:28 - SYSTEM STATS: Time:26.2625 Method:cmd.php Processes:1 Threads:1 Hosts:26 HostsPerProcess:26 DataSources:418 RRDsProcessed:249
26/Dec/2021 14:55:30 - SYSTEM DSSTATS STATS: Type:HOURLY, Time:0.02
26/Dec/2021 14:55:29 - SYSTEM STATS: Time:27.2532 Method:cmd.php Processes:1 Threads:1 Hosts:26 HostsPerProcess:26 DataSources:418 RRDsProcessed:249
26/Dec/2021 14:50:29 - SYSTEM DSSTATS STATS: Type:HOURLY, Time:0.02
26/Dec/2021 14:50:28 - SYSTEM STATS: Time:26.2577 Method:cmd.php Processes:1 Threads:1 Hosts:26 HostsPerProcess:26 DataSources:418 RRDsProcessed:249
26/Dec/2021 14:45:28 - SYSTEM DSSTATS STATS: Type:HOURLY, Time:0.02
26/Dec/2021 14:45:28 - SYSTEM STATS: Time:26.2521 Method:cmd.php Processes:1 Threads:1 Hosts:26 HostsPerProcess:26 DataSources:418 RRDsProcessed:249
26/Dec/2021 14:40:29 - SYSTEM DSSTATS STATS: Type:HOURLY, Time:0.01
26/Dec/2021 14:40:28 - SYSTEM STATS: Time:26.2525 Method:cmd.php Processes:1 Threads:1 Hosts:26 HostsPerProcess:26 DataSources:418 RRDsProcessed:249
26/Dec/2021 14:35:29 - SYSTEM DSSTATS STATS: Type:HOURLY, Time:0.02
26/Dec/2021 14:35:29 - SYSTEM STATS: Time:27.2568 Method:cmd.php Processes:1 Threads:1 Hosts:26 HostsPerProcess:26 DataSources:418 RRDsProcessed:249
26/Dec/2021 14:30:30 - SYSTEM DSSTATS STATS: Type:HOURLY, Time:0.02
26/Dec/2021 14:30:29 - SYSTEM STATS: Time:27.2510 Method:cmd.php Processes:1 Threads:1 Hosts:26 HostsPerProcess:26 DataSources:418 RRDsProcessed:249
26/Dec/2021 14:25:32 - SYSTEM DSSTATS STATS: Type:DAILY, Time:2.01 Threads:1 RRDfiles: DSSes: RRDUser:0.00 RRDSystem:0.00 RRDReal:0.00
26/Dec/2021 14:25:32 - CMDPHP PHP ERROR WARNING Backtrace: (/poller_dsstats.php[145]:dsstats_master_handler(), /poller_dsstats.php[262]:CactiErrorHandler())
26/Dec/2021 14:25:32 - ERROR PHP WARNING: Undefined variable $type in file: /var/www/cacti/htdocs/poller_dsstats.php on line: 262
26/Dec/2021 14:25:30 - CMDPHP PHP ERROR WARNING Backtrace: (/poller_dsstats.php[145]:dsstats_master_handler(), /poller_dsstats.php[259]:CactiErrorHandler())
26/Dec/2021 14:25:30 - ERROR PHP WARNING: Undefined variable $type in file: /var/www/cacti/htdocs/poller_dsstats.php on line: 259
26/Dec/2021 14:25:30 - SYSTEM DSSTATS STATS: Type:HOURLY, Time:0.02
26/Dec/2021 14:25:29 - SYSTEM STATS: Time:27.2633 Method:cmd.php Processes:1 Threads:1 Hosts:26 HostsPerProcess:26 DataSources:418 RRDsProcessed:249

I'm guessing this is related to something that does DSSTATS every hour or so.  This is an up-to-date pull from the 1.2.x git branch.

This is with php-8.1.0 on Gentoo Linux x86_64 .

**Comment by reubenfarrelly** [comment]
This is with the 1.2.x branch as of commit 11e0efc564513f0004fdd0706e82ef38d0795939 (HEAD -> 1.2.x, origin/1.2.x, info) and still present.

**Comment by TheWitness** [comment]
Thanks for reporting.  Get to it this weekend.

**Comment by TheWitness** [comment]
This should be resolved now, just pull the latest poller_dsstats.php and give it a test drive.  There is no changelog due to the bug appearing in unreleased code.
