### ISSUE TITLE
Tracebacks and errors when remote host poll fails

### ISSUE THREAD

**Issue by reubenfarrelly** [Cacti/cacti#4519]
The following backtrace and errors are seen when a host poll fails.  In this case to trigger this I shut down net-snmpd on the remote system - and on the next poll run the errors are showing.  The host itself is still up but the SNMP check times out because snmpd is not running.

This is a Gentoo x86_64 with php-8.1.1 and cacti with git 1.2.x branch (fully up to date).  If the remote check succeeds these errors are not seen.

31/Dec/2021 12:07:22 - POLLER: Poller[Main Poller] PID[353] WARNING: Invalid Response, Device[HOST - tornado] DS[HOST - tornado - CPU Usage - System] Graphs[HOST - tornado - CPU Usage] OID:.1.3.6.1.4.1.2021.11.52.0, output: U
31/Dec/2021 12:07:12 - POLLER: Poller[Main Poller] PID[353] WARNING: Invalid Response, Device[HOST - tornado] DS[HOST - tornado - CPU Usage - Nice] Graphs[HOST - tornado - CPU Usage] OID:.1.3.6.1.4.1.2021.11.51.0, output: U
31/Dec/2021 12:07:02 - CMDPHP SQL Backtrace: (/cmd.php[349]:ping_and_reindex_check(), /cmd.php[859]:db_execute_prepared())
31/Dec/2021 12:07:02 - CMDPHP ERROR: A DB Exec Failed!, Error: Column 'poller_id' cannot be null
31/Dec/2021 12:07:02 - CMDPHP PHP ERROR WARNING Backtrace: (/cmd.php[349]:ping_and_reindex_check(), /cmd.php[862]:CactiErrorHandler())
31/Dec/2021 12:07:02 - ERROR PHP WARNING: Undefined variable $poller_id in file: /var/www/cacti/htdocs/cmd.php on line: 862
31/Dec/2021 12:07:02 - POLLER: Poller[Main Poller] PID[353] Device[HOST - tornado] DQ[ucd/net - Get Monitored Partitions] RECACHE ASSERT FAILED '8869900<
31/Dec/2021 12:06:42 - CMDPHP SQL Backtrace: (/cmd.php[349]:ping_and_reindex_check(), /cmd.php[859]:db_execute_prepared())
31/Dec/2021 12:06:42 - CMDPHP ERROR: A DB Exec Failed!, Error: Column 'poller_id' cannot be null
31/Dec/2021 12:06:42 - CMDPHP PHP ERROR WARNING Backtrace: (/cmd.php[349]:ping_and_reindex_check(), /cmd.php[862]:CactiErrorHandler())
31/Dec/2021 12:06:42 - ERROR PHP WARNING: Undefined variable $poller_id in file: /var/www/cacti/htdocs/cmd.php on line: 862
31/Dec/2021 12:06:42 - POLLER: Poller[Main Poller] PID[353] Device[HOST - tornado] DQ[SNMP - Interface Statistics] RECACHE ASSERT FAILED '8869900<
31/Dec/2021 12:03:24 - AUTH LOGIN: User 'reuben' Authenticated via Authentication Cookie

**Comment by TheWitness** [comment]
Confirming.  Thanks for testing @reubenfarrelly!

**Comment by netniV** [comment]
this needs a better title.
