### ISSUE TITLE
Graph list view - device drop-down limited to 30 devices in new themes

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#452]
When using the modern, dark or paw theme and the Graph List view tab, the device drop-down menu is limited to only 30 devices and does not have a scroll bar to find any other devices past this limit. The classic theme scrolls OK.

**Comment by cigamit** [comment]
This is not a bug but a feature for large sites.  If activate the dropdown, you will find that you can select and type into the form.  It's only showing first 30, but if you start typing 'abc', the list will dynamically change.  Classic is like the Smithsonian.  We are keeping it around for old people.

**Comment by eschoeller** [comment]
Can you check on this again? I don't think it's doing what you described:( I see a search box in the "All Graphs & Templates" drop-down, but no matter what I type or do in the device drop-down I can't select my "zzztest" device!

**Comment by cigamit** [comment]
Is it working for other devices?  In other words when you start typing, is the device list changing?

**Comment by cigamit** [comment]
You need to bring up your browser debug console and see if you are getting Javascript errors.  If so, take a screen shot and share them here.

**Comment by eschoeller** [comment]
No, typing in the device drop-down isn't doing anything

**Comment by cigamit** [comment]
Are you able to highlight "Any" and type over it? Again, check the Browser's Debug Console for javascript errors.  If none of the above, then make a video and upload it.

**Comment by eschoeller** [comment]
OH, ok if I delete the word "Any" I can type in text here and it changes the contents in the drop-down. I was trying to type in the drop-down list itself, not in the top box area. So I now see how it's working but I just don't know if there's a way to make it any more straightforward. But you do see that in some sites where there's a search box and you need to delete the pre-populated "Search Here..." text and enter in your actual query.

**Comment by cigamit** [comment]
Well, let's make that a separate ticket.  You will get used to it in the mean time.
