### ISSUE TITLE
Incomplete Listbox entries on menu data sources

### ISSUE THREAD

**Issue by GitHub2022** [Cacti/cacti#4523]
Cacti Version 1.2.20

Got to management ->data sources and click on any data source name. 
The device list box shows the current device but the list itself doesnt contain all of the devices.
So you can not change the device for your needs in case you need it.

**Comment by TheWitness** [comment]
This is pretty normal.  What are you trying to do?  Some of this stuff really belongs on the Forums.

**Comment by netniV** [comment]
The list is dynamically generated based on maximum number of entries and the entered search text.  This behaviour has been around for a number of years now (yet it does still get rasied as a problem from time to time).

**Comment by GitHub2022** [comment]
But the search was on default „empty“. But it still generates only some devices. Is there a maximum number of listbox entries?

**Comment by netniV** [comment]
Yes check the settings, probably visual tab
