### ISSUE TITLE
When using CMD for polling, pipes are not properly referenced for PHP scripts

### ISSUE THREAD

**Issue by camerabob** [Cacti/cacti#4525]
# Describe the bug

In the cacti_stderr.log, the below appears:

<html>
<body>

--
PHP Warning: fgets() expects parameter 1 to be resource, null given in /usr/share/cacti/lib/poller.php on line 80
PHP Warning: fflush() expects parameter 1 to be resource, null given in /usr/share/cacti/lib/poller.php on line 78
PHP Warning: fwrite() expects parameter 1 to be resource, null given in /usr/share/cacti/lib/poller.php on line 77
PHP Notice: Undefined variable: pipes in /usr/share/cacti/cmd.php on line 786

</body>
</html>

## To Reproduce

Happens every polling cycle

## Expected behavior

No errors n logs as before upgrade from 1.2.16, CentoOS 7

## Desktop (please complete the following information)

- OS: Windows 7
- Browser: Opera

**Comment by TheWitness** [comment]
The pipes should be defined.  My guess is that RRDtool is failing to initialize.

**Comment by TheWitness** [comment]
@camerabob, can you respond?

**Comment by TheWitness** [comment]
No response.
