### ISSUE TITLE
Reporting not sending email - Rocky Linux - 1.2.19-1.el8

### ISSUE THREAD

**Issue by juesor** [Cacti/cacti#4526]
I created a daily report if I click "Send Report" it works.  PHP Mailer delivers a message.

When it comes time for the report to send tomorrow the Next Run date does not update and nothing is displayed in cacti.log regarding sending a message.

![image](https://user-images.githubusercontent.com/14931420/149172266-924bf319-06a9-4613-b2d3-90db97a6eb56.png)

I set this report up at 8:30 AM on 2022.01.12 for a later date and it seems like it never ran.

**Comment by netniV** [comment]
Are you sure it's been scheduled and that the plugin is not only installed but enabled?

**Comment by juesor** [comment]
![image](https://user-images.githubusercontent.com/14931420/149345210-10f4bec7-ed10-4766-85ca-2c884a330014.png)
 
From my first image, it says enabled as the job is enabled

Above is a full screenshot of the report you can see it is enabled and the interval is set to "day(s) 1".

As for plugin's isn't Reporting built-in? I didn't build this server so my history with cacti is this upgrade and this problem.

**Comment by TheWitness** [comment]
If you setup the report and press the Send Report now button.  Is the Email delivered?

**Comment by juesor** [comment]
Yes.  But daily every morning at 08:45:00 nothing happens.

**Comment by TheWitness** [comment]
It's the `poller_reports.php` file.  If you can trace the issue, that would be good.  There are command line options.  Just use the --help command line argument.

**Comment by juesor** [comment]
[root@cacti-nops /]# ./usr/share/cacti/poller_reports.php
PHP Notice:  Undefined variable: reports_interval in /usr/share/cacti/lib/html_reports.php on line 150
PHP Notice:  Undefined variable: attach_types in /usr/share/cacti/lib/html_reports.php on line 220
2022/01/19 11:16:21 - SYSTEM REPORTS STATS: Time:6.0787 Reports:2


Manually running the poller_reports.php threw 2 errors but ultimately completed the reports and the message i was looking for was delivered.

What controls when to execute the poller? 

--debug didn't output any new information to look at.

**Comment by juesor** [comment]
'intrvl' => array(
                'friendly_name' => __('Report Interval'),
                'description' => __('Defines a Report Frequency relative to the given Mailtime above.') . '<br>' .
                        __('e.g. \'Week(s)\' represents a weekly Reporting Interval.'),
                'default' => REPORTS_SCHED_INTVL_DAY,
                'method' => 'drop_array',
                'array' => $reports_interval,
                'value' => '|arg1:intrvl|'
                ),


Is there something with line 150 on html_reports.php checking latest to make sure mine matches whats here.

**Comment by netniV** [comment]
That variable defines the frequency but you also have a count and offset and the time the report was last emailed.  You can see any scheduled events using the events tab I believe.

**Comment by juesor** [comment]
I noticed that it was throwing an error that no email address assigned to admin user.

I put my email address in there.

And I set the scheduled report to send every 5 minutes after 9:00 and now every 5 minutes I'm getting this.

WARNING: Poller Output Table not empty for poller id 1. Issues: 86, DS[1766, 1766, 1766, 1766, 2846, 2846, 2846, 2846, 4526, 4526, 4526, 4526, 5041, 5041, 5041, 5041, 5916, 5916, 5916, 5916], Additional Issues Remain. Only showing first 20.

What is this referring to and i'm guessing this is what is preventing reports from sending?

**Comment by juesor** [comment]
I logged in with mysql workbench and it threw an error at me that my db 

created with mariadb now running please use mysql_upgrade to fix this error

So I ran mysql_upgrade and 

Now at 9:35, I got a report with my graph.

**Comment by juesor** [comment]
I spoke too soon.

The report ran twice on a schedule and then hasn't run since. 

I'm getting Cacti System Warning emails but not my BW report graph

/var/log/cacti/cacti.log isn't throwing anything. So I'm backtracking to figure out why it ran earlier but not since.

**Comment by juesor** [comment]
Still, nothing pointing to why this is not working.

Does anyone have any more ideas of things to look at in cacti?

**Comment by TheWitness** [comment]
My eyes are pointed elsewhere at the moment.  You can put `poller_reports.php` into debug mode from the `Console > Settings > General` tab.  Why don't you do that around the time the report is supposed to be sent and see what shows up in the Cacti log.  BTW, there have been multiple changes in the 1.2.x branch, but to apply those, you have to eat the whole elephant.

**Comment by TheWitness** [comment]
I can tell from your warning about reports_interval and attach_types being undefined that you Cacti version is not fully upgraded somewhere.  Those are global variables, and when you include lib/html_reports.php they should exist in that form object.  So, something is wrong with your overall setup.

The way I would upgrade rocky would be as follows, assuming you installed from source from the Get Go.  Simple enough:

```sh
cd /var/www/html/
git clone -b 1.2.x https://github.com/cacti/cacti.git cacti-new
/bin/cp -rpf cacti-new/* cacti
chown -R apache:apache cacti
```

Then refresh your browser.  Do those commands as root.

**Comment by juesor** [comment]
Thanks for the responses I'll look at debug and keep working through it.

**Comment by TheWitness** [comment]
I didn't originally write the reporting UI.  But I've been disliking it lately enough to spend some time on it.

**Comment by TheWitness** [comment]
Going to be much better in 1.2.20 under the context of being able to scale properly, which it does not in the 1.2.19-- versions.

**Comment by TheWitness** [comment]
Just made another update today.  Not sure it will make a difference though.  On my system, it's attempting to send, but hitting a size limit on the SMTP server side.  Can't make those reports too big.

**Comment by juesor** [comment]
Sorry, it's been a while since I responded.

Tearing down all reports and rebuilding after the 1.21.2022 message and now reports are sent out daily with no problems.

It was deleting all old reports and cleaning it up are rebuilding from scratch that fixed it for me.

No idea what was sitting around not letting the reports daily trigger.

**Comment by TheWitness** [comment]
Cool.
