### ISSUE TITLE
custom script can not get data

### ISSUE THREAD

**Issue by blazec88** [Cacti/cacti#4527]
Hey,  I create custom data input method as follow:
![image](https://user-images.githubusercontent.com/83337541/149274252-6a02f7db-b960-4d6f-aea2-a364a2604a71.png)

And input fields is :
![image](https://user-images.githubusercontent.com/83337541/149274312-397cd6d5-475b-438d-b99a-8368a5c9987c.png)

Data source template is:
![image](https://user-images.githubusercontent.com/83337541/149274477-76d8fe03-f002-4ada-9e08-d9e7e5db784c.png)

Graph template is:
![image](https://user-images.githubusercontent.com/83337541/149274686-46ed6d66-a1ae-4b7c-9906-0a5dc1b1b001.png)
![image](https://user-images.githubusercontent.com/83337541/149274704-c4305950-673a-415b-8171-38930b96ab63.png)

When I'm going to add this graph into device, it can not return any data, and log is warning as follow:
> 2022/01/13 14:05:05 - SPINE: Poller[185] PID[487419] PT[139684270016256] WARNING: Invalid Response, Device[2114] HT[1] DS[21945] SCRIPT: /var/www/html/scripts/ss_cpu_avg.php ss_cpu_avg '' '' '' '' '' '' '' '' '' '' '', output:

**environment**
cacti: 1.2.20
spine:1.2.20

Is anywhere I set the wrong parameter?

**Comment by TheWitness** [comment]
I would suggest that you simplify things and only use the replacement variable `<hostid>`, then in your script, you can connect to the cacti database and pull all the SNMP settings from the `host` table vs pulling it all through the script.  Use the example below, which you can get from the MikroTik plugin.

![image](https://user-images.githubusercontent.com/1439914/149815043-738ec458-8e36-40e5-b95b-7db28e9d884c.png)

**Comment by TheWitness** [comment]
No feedback.
