### ISSUE TITLE
Default Setting "Device Threads" is ignored in device creation form

### ISSUE THREAD

**Issue by Vulcan1171** [Cacti/cacti#4528]
# Describe the bug

When manually creating a new device in the '_Device [new]_' form, the option '_Number of Collection Threads_' will always start set to '_1 Thread (default)_' regardless of setting in '_Configuration->Settings->Device Defaults->Device Threads_'.

Is this the expected behaviour?

## To Reproduce

1. Go to 'Configuration->Settings->Device Defaults'

2. Modify value of 'Device Threads' from 1 to another value and save

3. Go to 'Management->Devices->+ (new)' or 'Create->New Device'

4. The option 'Number of Collection Threads' is still set to '1 Thread (default)'

## Expected behavior

When the form for the creation of a new device is presented to the user, the option 'Number of Collection Threads' should be preset to the value selected in "Configuration->Settings->Device Defaults->Device Threads"

## Additional context

Verified on Cacti version 1.2.19

![2022-01-14_16h38_15](https://user-images.githubusercontent.com/97747775/149542622-e1d690b6-08b6-4e8d-b969-c03d393f305a.png)
![2022-01-14_16h38_25](https://user-images.githubusercontent.com/97747775/149542681-83ecc4f0-1fb4-442b-9edd-cb484058a811.png)

**Comment by TheWitness** [comment]
Confirming.

**Comment by TheWitness** [comment]
This is fixed no in the 1.2.x branch.  Thanks for reporting!
