### ISSUE TITLE
Graph Rules, Device Selection Criteria, error in your SQL syntax

### ISSUE THREAD

**Issue by mitay2** [Cacti/cacti#453]
Example(we find DC2, DC12...? but no DC1):
Item1: description contains DC
Item2: description does not match with DC1

log:
DBCALL ERROR: SQL Assoc Failed!, Error: You have an error in your SQL syntax;

**Comment by cigamit** [comment]
Can you move the logging level to Developer Debug and then show the same error, but it will include the SQL.

**Comment by cigamit** [comment]
It's got to be operator error.  Here are two 'working' examples.

![devicematch1](https://cloud.githubusercontent.com/assets/957322/24084791/0f998310-0cbf-11e7-9745-14a035bbcdd9.png)
![devicematch2](https://cloud.githubusercontent.com/assets/957322/24084792/12744bf6-0cbf-11e7-9477-776cdd4011f6.png)
