### ISSUE TITLE
Cacti's Reporting Interface is NOT Usable on Large Systems

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#4530]
# Describe the bug

Due to the lack of select's that do not leverage callbacks to limit the list size, the Reporting GUI performance degrades steadily as you add more Devices and Graphs to the Cacti system.

## To Reproduce

1. Have a System with 40k hosts and more than a million graphs

2. Attempt to create a report

3. Interface is almost unusable

## Expected behavior

Cacti should be performing callbacks for things like: Trees, Sub-Trees, Devices, and Graphs.

**Comment by TheWitness** [comment]
@bmfmancini, this is ready for testing.  Just force run the upgrade from 1.2.19 to 1.2.20 again to pick up the table changes.

**Comment by bmfmancini** [comment]
Testing shows good! no errors and UI is much much faster !
