### ISSUE TITLE
Graphs incorrectly drawing after router upgrade

### ISSUE THREAD

**Issue by chrisch80** [Cacti/cacti#4532]
Hello,

we are currently upgrading our Cisco routers to a new eXR version.

And after the upgrade we are facing interface graphs are stop drawing or wrong values are present.

What I can see so far is that the snmp-index changed during the upgrade (or reboot):

[user@cacti ~]$ more router1_preupgrade.txt |grep Bundle-Ether10
IF-MIB::ifDescr.1313 = STRING: Bundle-Ether10
IF-MIB::ifDescr.1315 = STRING: Bundle-Ether10.100

[user@cacti ~]$ more router1_postupgrade.txt |grep Bundle-Ether10
IF-MIB::ifDescr.29 = STRING: Bundle-Ether10
IF-MIB::ifDescr.123 = STRING: Bundle-Ether10.100

Which is anyway strange because we are using "snmp-server ifindex persist" in the configration.

However, we have different performance management tools and all of them don't have any issues after the router upgrades.
Even with Cacti 0.8.7e we don't have any issues after the router upgrades.
But with Cacti 1.2.17 we have this issue.

E.g. in case of Bundle-Ether10 ist stops drawing:
![grafik](https://user-images.githubusercontent.com/24794879/150532795-86a33e22-6e15-4bb5-894e-d4d1501245f7.png)

If we do a "Re-Index Device" on that router, Cacti 1.2.17 adds a lot of additional graphs (with IN/OUT bytes (64-bit)) which we never added manually. We generally don't use IN/OUT bytes counters (we only use IN/OUT bit and errors for interfaces).

I have no idea if this could be a bug or wrong configuration.
I have tested something but nothing helped.

Thx

**Comment by TheWitness** [comment]
This is likely due to an index change on the router side.  You should force a re-index and see if the error goes away.  As this is more of a support issue and not a bug, I'm going to mark as a question and then close.  Feel free to continue to comment though.

With your switches and routers, when you add a line card, or with certain Routers add an interface, Cacti needs to be re-indexed.  Sometimes, if the switch/router is in a bad spot when this re-indexing fails, it won't properly re-index.  If the interface "ifName" for the interface in question changes, you will have to hand edit the data source to set the correct interface for the traffic.

**Comment by TheWitness** [comment]
Another thing, we switched from ifDescr to ifName as the default "sort" field a long time ago.  You should check your `interfaces.xml` file to see if you have an old or new sort field.  Using ifDescr was deemed dangerous as that when you upgrade switches and routers firmware, they often time change the ifDescr which will cause your problem.

If you are using a recent version of Cacti, it should detect the change and look for the correct ifName and make the switch automatically at re-index time.

**Comment by chrisch80** [comment]
Hello,

thank you for your feedback.

Cacti 0.8.7e doesn't have the issue
Cacti 1.2.17 (fresh install last year) has the issue

Cacti 0.8.7e interface.xml:
	<index_order>ifDescr:ifName:ifHwAddr:ifIndex</index_order>

Cacti 1.2.17 interface.xml:
	<index_order>ifName:ifDescr:ifHwAddr:ifIndex</index_order>


As already mentioned in the first thread, when I do a re-index I have afterwards more graphs as before.
E.g. I did this some minutes ago on 1 device:
Before I had 10 Graphs (1xCPU, 1xPollingTime, 1xUptime, 7xTraffic 64bit/s).
Now I have 127 Graphs (1xCPU, 1xPollingTime, 1xUptime, 7xTraffic 64bit/s, 117x Traffic 64byte/s)
That means a re-index added 117 addional graph which I don't want.
However, the 7xTraffic 64bit/s are working correct afert the re-index.

Is there some reason:
1. Why the re-index is not done automaticaly?
2. Why are additional graphs (Traffic 64bit byte/s) created? Can I somehow prevent it?


In the devices settings I have:
Bulk Walk Maximum Repititions: Auto Detect on Re-Index
1) SNMP - Interface Statistics: Re-Index Method: Uptime

Therefore I would expect directly after the router upgrade (which includes a reboot, means uptime changes) a automatic Re-Index of the interfaces.
I have devices which were upgraded in Dec 2021 and still not automatically re-indexed.

Seems to be similar to [#3578](https://github.com/Cacti/cacti/issues/3578).

Thx

**Comment by TheWitness** [comment]
Just force reindex them.  There is a cli tool for that.

**Comment by TheWitness** [comment]
You might want to consider updating as soon as 1.2.20 is released too.
