### ISSUE TITLE
Restructuring RRDfile paths takes too long on large systems and will stop polling for potentially several hours

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#4533]
# Describe the bug

On large systems with over 1M RRDfiles, it's very difficult to restructure paths and keep polling operational at the same time.  The current CLI script first disables polling, then restructures the paths one at a time which is arguably too slow.  Additionally, if you have 20k+ hosts, you still end up with a directory of over 20k files, which though not as bad, is still excessive.

## To Reproduce

1. Create a system with 1.7M RRDfiles and over 20k hosts

2. Allow all RRDfiles to be created in the RRA directory

3. Attempt to "structure the RRDfile paths"

## Expected behavior

Cacti should be able to execute this process with no downtime.

**Comment by browniebraun** [comment]
This was the first script for Cacti I originally wrote in 2006. Times are changing...

**Comment by browniebraun** [comment]
or was in 2005? I don't know. 🙄🤔😅

**Comment by TheWitness** [comment]
Where's my cane 😂

**Comment by TheWitness** [comment]
I've bumped this one to 1.2.22 as it's material for me right now.
