### ISSUE TITLE
The poller_output_boost_arch tables are not deleted

### ISSUE THREAD

**Issue by cub-uanic** [Cacti/cacti#4535]
I'm using Cacti 1.2.17 from Docker hub smcline06/cacti, all settings are on their defaults (except added new devices and graphs).
I see ~14500 tables with the name poller_output_boost_arch_NNNNNN, and this makes DB slow, just due to the big directory size.
All of them are zero rows, but they aren't deleted automatically, so I had to delete them manually.
How this could be fixed?

As I'm not sure which project is responsible for this - I'm creating a bug in both, please see:
https://github.com/scline/docker-cacti/issues/98

**Comment by bmfmancini** [comment]
This was fixed

Move to the latest 1.2.x branch

**Comment by TheWitness** [comment]
Yea, fixed a while ago.
