### ISSUE TITLE
Broken handling of plugin dependencies in 1.2.19

### ISSUE THREAD

**Issue by browniebraun** [Cacti/cacti#4539]
# Describe the bug

This issue has been noticed in 1.2.19. Unfortunately there was no time to verify if 1.2.20 is affected, too.

## To Reproduce

- Create two plugins A and B.
- Define within the manifest of B: "requires A"
- Ensure that A is NOT installed.
- Click on the install button for plugin B.

Following output will be returned instead of an error message that A has not been installed yet:

![image](https://user-images.githubusercontent.com/5182348/151813675-1e234f9e-259e-4019-a888-5e9ecdd1277f.png)

**Comment by TheWitness** [comment]
Should be fixed now.

**Comment by TheWitness** [comment]
@browniebraun do you have an update?

**Comment by browniebraun** [comment]
Sorry, I haven't received any kind of notification.
But yes, you fixed it.

**Comment by TheWitness** [comment]
Cool.  Found a few more too.
