### ISSUE TITLE
Some Email systems reject sending email if emails are duplicated in a send request.  Cacti should deduplicate them

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#4543]
# Describe the bug

We recently got into a mailer issue the other day where we had the same Email in a Notification list, and the same Email in a `notification_extra` using an upper case email.  When calling the mailer with this condition, the upstream mail services rejected the Email since it had duplicated Email addresses.

`EMAIL@domain.com,email@domain.com`

That example was rejected upstream.

## Expected behavior

Cacti should per-process the Email list, convert the Emails to lower case, and de-duplicate them prior to sending to the upstream mail service.

**Comment by netniV** [comment]
Technically, we can't de-dupe that situation.  Both are valid independent email addresses according to the RFC.

**Comment by TheWitness** [comment]
Ouch.  Okay, maybe we issue a warning then?  I was able to cleanup the issue (In thold), and I plan on disabling legacy notifications.

```
strtolower($mail) == strtolower($other_email)
```

**Comment by netniV** [comment]
Taken from https://stackoverflow.com/a/9808332/697159

> From [RFC 5321, section 2.3.11](https://www.rfc-editor.org/rfc/rfc5321#section-2.3.11):
>
> > The standard mailbox naming convention is defined to be 
> > "local-part@domain"; contemporary usage permits a much broader set of 
> > applications than simple "user names".  Consequently, and due to a 
> > long history of problems when intermediate hosts have attempted to 
> > optimize transport by modifying them, the local-part MUST be 
> > interpreted and assigned semantics only by the host specified in the 
> > domain part of the address.

> So yes, the part before the "@" could be case-sensitive, since it is entirely under the control of the host system.  In practice though, no widely used mail systems distinguish different addresses based on case.

> The part after the @ sign however is the domain and according to [RFC 1035](https://www.rfc-editor.org/rfc/rfc1035), section 3.1, 

> > "Name servers and resolvers must compare [domains] in a case-insensitive manner"

> In short, you are safe to treat email addresses as case-insensitive.

**Comment by netniV** [comment]
Maybe we ignore the RFC on that one since most systems do these days.  But we need to make sure it's documented.

**Comment by TheWitness** [comment]
I think we should.  It's a minor thing.  Looking at the code `parse_email_details()`, could de-duplicate there, just have to be careful.  Maybe make the strlower($email) the index of the array.

**Comment by netniV** [comment]
I would personally just use reset($details) to get the first item.  Saves messing around getting the keys to get the first element.

**Comment by netniV** [comment]
Also, I would only set the element once, but report duplicates if there is a difference in the values?  For example, if you have the same email but different names....

**Comment by TheWitness** [comment]
Interesting.  Let me think about it.

**Comment by TheWitness** [comment]
Okay, used reset, but not detecting the duplicate name for now.  We can put that into the backlog.
