### ISSUE TITLE
Invalid path for Boost logging stops Boost update process without notification

### ISSUE THREAD

**Issue by browniebraun** [Cacti/cacti#4549]
# Describe the bug

Affected version 1.2.19

While Moving and updating an existing Cacti lab instance to a new directory, I have missed to update the existing path entry for the Boost update log. This morning I found 30M records in the poller_output_boost table, but no hint in the Cacti log for any Boost update statistics nor an Boost error message. The old directory was no longer existing and that is the root cause of this seldom issue.

Please note: This is not the same as having an existing valid directory path where the destination log file is not existing as this file will then be created automatically.

## To Reproduce

- Change you boost log path to something not existing like  /www/foo/bar/boost.log
- Reduce the number of maximum boost records to something lower (e.g. 1000) than your number of monitored data sources to trigger an update process with the next poller run.

## Expected behavior

- At least an error message in the Cacti log would be expected, saying that the Boost log is not existing and that it cannot be created.
- Writing poller_ouput_boost data down to the RRDs although the logging issue exists.

**Comment by TheWitness** [comment]
Pulling this one ahead.
