### ISSUE TITLE
PHP DEPRECATED errors in 8.1

### ISSUE THREAD

**Issue by densenator** [Cacti/cacti#4551]
# Describe the bug

I installed advanced ping and trying to edited it because my ping is more is 500. It's normal for me.
I see only dev, not see avg and other.
And i get some errors now:

<html>
<body>

12.02.2022 11:17:39 - CMDPHP PHP ERROR Backtrace: (/graphs.php[116]:graph_edit(), /graphs.php[1675]:rrdtool_function_graph(), /lib/rrd.php[1906]:str_replace(), CactiErrorHandler())
--
12.02.2022 11:17:39 - ERROR PHP DEPRECATED: str_replace(): Passing null to parameter #2 ($replace) of type array\|string is deprecated in file: /var/www/html/lib/rrd.php on line: 1906
12.02.2022 11:15:01 - CMDPHP WARNING: cmd.php poller has run over its polling interval and therefore is ending
12.02.2022 11:15:00 - SYSTEM WARNING: Primary Admin account notifications disabled! Unable to send administrative Email.
12.02.2022 11:15:00 - POLLER: Poller[Main Poller] PID[3620] WARNING: There are 1 processes detected as overrunning a polling cycle, please investigate
12.02.2022 11:14:59 - SYSTEM STATS: Time:298.5947 Method:cmd.php Processes:1 Threads:1 Hosts:15 HostsPerProcess:15 DataSources:90 RRDsProcessed:64
12.02.2022 11:14:59 - SYSTEM WARNING: Primary Admin account notifications disabled! Unable to send administrative Email.
12.02.2022 11:14:59 - POLLER: Poller[Main Poller] PID[3006] Maximum runtime of 298 seconds exceeded. Exiting.
12.02.2022 11:10:02 - PHPSVR Maximum runtime of 300 seconds exceeded for the Script Server. Exiting.

</body>
</html>

in server i run
root@cacti:/var/www/html/scripts# php -q ss_fping.php my-server.com 20 ICMP
min:603.6110 avg:615.5208 max:629.1850 dev:5.7867 loss:0.0000

## Screenshots
![image](https://user-images.githubusercontent.com/18443709/153706023-65be04c9-6ded-4601-8696-b26e82d02539.png)

![image](https://user-images.githubusercontent.com/18443709/153706124-d0a2c39e-f1ee-4c40-8e63-7c791de6041b.png)

![image](https://user-images.githubusercontent.com/18443709/153706134-44672039-34c5-484b-beaa-2dd69108f41f.png)

![image](https://user-images.githubusercontent.com/18443709/153706152-2cbb22a6-ba3b-49ee-9800-b0aafb1c1586.png)

## Desktop (please complete the following information)

- OS:  debian 11.2
- PHP 8.1.2
-  Apache/2.4.52
-  10.5.12-MariaDB
- cacti 1.2.20

chrome
98.0.4758.82

**Comment by densenator** [comment]
also deprecated in import
<html>
<body>


12.02.2022 14:03:39 - CMDPHP PHP ERROR Backtrace: (/templates_import.php[43]:form_save(), /templates_import.php[97]:import_xml_data(), /lib/import.php[190]:xml_to_data_input_method(), /lib/import.php[1796]:CactiErrorHandler())
--
12.02.2022 14:03:39 - ERROR PHP DEPRECATED: Automatic conversion of false to array is deprecated in file: /var/www/html/lib/import.php on line: 1796
12.02.2022 14:03:39 - CMDPHP PHP ERROR Backtrace: (/templates_import.php[43]:form_save(), /templates_import.php[97]:import_xml_data(), /lib/import.php[197]:xml_to_gprint_preset(), /lib/import.php[1227]:CactiErrorHandler())
12.02.2022 14:03:39 - ERROR PHP DEPRECATED: Automatic conversion of false to array is deprecated in file: /var/www/html/lib/import.php on line: 1227
12.02.2022 14:03:39 - CMDPHP PHP ERROR Backtrace: (/templates_import.php[43]:form_save(), /templates_import.php[97]:import_xml_data(), /lib/import.php[197]:xml_to_gprint_preset(), /lib/import.php[1227]:CactiErrorHandler())
12.02.2022 14:03:39 - ERROR PHP DEPRECATED: Automatic conversion of false to array is deprecated in file: /var/www/html/lib/import.php on line: 1227
12.02.2022 14:03:39 - CMDPHP PHP ERROR Backtrace: (/templates_import.php[43]:form_save(), /templates_import.php[97]:import_xml_data(), /lib/import.php[197]:xml_to_gprint_preset(), /lib/import.php[1227]:CactiErrorHandler())
12.02.2022 14:03:39 - ERROR PHP DEPRECATED: Automatic conversion of false to array is deprecated in file: /var/www/html/lib/import.php on line: 1227
12.02.2022 14:03:39 - CMDPHP PHP ERROR Backtrace: (/templates_import.php[43]:form_save(), /templates_import.php[97]:import_xml_data(), /lib/import.php[200]:xml_to_cdef(), /lib/import.php[1519]:CactiErrorHandler())
12.02.2022 14:03:39 - ERROR PHP DEPRECATED: Automatic conversion of false to array is deprecated in file: /var/www/html/lib/import.php on line: 1519


</body>
</html>

**Comment by densenator** [comment]
1.2.20

**Comment by densenator** [comment]
Nothing changed now.
<html>
<body>


13.02.2022 15:25:11 - CMDPHP PHP ERROR Backtrace: (/templates_import.php[48]:import(), /templates_import.php[127]:import_display_results(), /lib/import.php[2180]:html_escape(), /lib/html.php[1069]:str_replace(), CactiErrorHandler())
--
13.02.2022 15:25:11 - ERROR PHP DEPRECATED: str_replace(): Passing null to parameter #3 ($subject) of type array\|string is deprecated in file: /var/www/html/lib/html.php on line: 1069
13.02.2022 15:25:11 - CMDPHP PHP ERROR WARNING Backtrace: (/templates_import.php[48]:import(), /templates_import.php[127]:import_display_results(), /lib/import.php[2180]:CactiErrorHandler())
13.02.2022 15:25:11 - ERROR PHP WARNING: Undefined array key "title" in file: /var/www/html/lib/import.php on line: 2180
13.02.2022 15:25:11 - CMDPHP PHP ERROR WARNING Backtrace: (/templates_import.php[48]:import(), /templates_import.php[127]:import_display_results(), /lib/import.php[2174]:CactiErrorHandler())
13.02.2022 15:25:11 - ERROR PHP WARNING: Undefined array key "type" in file: /var/www/html/lib/import.php on line: 2174
13.02.2022 15:25:11 - CMDPHP PHP ERROR WARNING Backtrace: (/templates_import.php[48]:import(), /templates_import.php[127]:import_display_results(), /lib/import.php[2172]:CactiErrorHandler())
13.02.2022 15:25:11 - ERROR PHP WARNING: Undefined array key "type" in file: /var/www/html/lib/import.php on line: 2172


</body>
</html>

**Comment by TheWitness** [comment]
Okay, some progress.

**Comment by TheWitness** [comment]
Was it Advanced Ping 2.2 or 1.3?  Also, just made another update.

**Comment by densenator** [comment]
v1.3, and i'm trying to import 2.2 and cacti sayes "nothing changes"
![image](https://user-images.githubusercontent.com/18443709/153759462-08fcce87-eadf-46fb-9d8b-da0b25fa94e8.png)

**Comment by TheWitness** [comment]
I'm just trying to use the Remi repos to try and squeeze php81 on my CentOS7.1 box.

**Comment by TheWitness** [comment]
Any more import errors though?

**Comment by TheWitness** [comment]
Enabling 8.1.2 made a mess out of my log.  Going to be fixing things for a while.  Just did thold, syslog is coming.

**Comment by densenator** [comment]
After last update cacti i don't see errors in my log.
But advanced ping also don't show values more then 500 for me.
And any other errors:
<html>
<body>


13.02.2022 17:40:06 - CMDPHP PHP ERROR NOTICE Backtrace: (/cmd.php[437]:fwrite(), CactiErrorHandler())
--
13.02.2022 17:40:06 - ERROR PHP NOTICE: fwrite(): Write of 6 bytes failed with errno=32 Broken pipe in file: /var/www/html/cmd.php on line: 437
13.02.2022 17:40:06 - PHPSVR Maximum runtime of 300 seconds exceeded for the Script Server. Exiting.
13.02.2022 17:40:06 - CMDPHP WARNING: cmd.php poller has run over its polling interval and therefore is ending
13.02.2022 17:40:00 - SYSTEM WARNING: Primary Admin account notifications disabled! Unable to send administrative Email.
13.02.2022 17:40:00 - POLLER: Poller[Main Poller] PID[192834] WARNING: There are 1 processes detected as overrunning a polling cycle, please investigate


</body>
</html>

**Comment by TheWitness** [comment]
Well, I have not used it in years, though I did import this morning and made some psr changes to ss_fping.  What ping method are you using?

**Comment by TheWitness** [comment]
Using cmd.php is no good by the way...  It lacks some better timing control that is in spine.

**Comment by TheWitness** [comment]
This last one is expected when the poller times out.  So, let's let that last one stand.  In spine, we will kill the script after the script timeout.

**Comment by TheWitness** [comment]
We could attempt to mask the error message.  Let me just try that once.  Just did a minor commit.  There are better "different" ways to do this, trying the shortcut first.

**Comment by TheWitness** [comment]
If you get any more, just open a new ticket.
