### ISSUE TITLE
Cannot add graph Unix ping latency in 1.2.19

### ISSUE THREAD

**Issue by xmacan** [Cacti/cacti#4553]
Someone has this problem in forums.cacti.net. I have tested it and I confirm the problem.
Graph creating stuck on Graph items, button create does not trigger any action:
![unix_ping](https://user-images.githubusercontent.com/26485719/154061217-bac8f755-7ca2-4607-914f-19c79b8a20e5.png)

Firefox 97
cacti 1.2.19

**Comment by TheWitness** [comment]
@xmacan,

There have been a ton of updates for 1.2.20 on this topic.  It's stable, but not yet released. This 1.2.20 update is especially important update for larger systems that will suffer dramatically from this performance bug.

**Comment by TheWitness** [comment]
Can you please test on that version?

**Comment by TheWitness** [comment]
I just tested on 1.2.20, and it worked fine.  I had seen this a few months ago.  So, duplicate and resolved.

**Comment by xmacan** [comment]
Yes, in 1.2.20 works fine

**Comment by TheWitness** [comment]
Glad you confirmed it too.  We are winding down to release.  Just doing some testing right now on PHP8.1.
