### ISSUE TITLE
Undefined index in graph debug mode

### ISSUE THREAD

**Issue by browniebraun** [Cacti/cacti#4557]
# Describe the bug

Only occurs if you are using a non-typical RRA profil. In my case only archive LAST will be created and used within the graph template.

Graph debug returns more than 20 times "Undefined offset: 1 ...." .

## Solution

Simple to fix as the issue occurs in /lib/functions.php -- function generate_graph_best_cf:

 
![image](https://user-images.githubusercontent.com/5182348/154470194-2dd0c185-3b51-41d9-9bd2-e3d281b63f85.png)

Due to the reason that $avail_cf_functions hasn't been touched before line 2707 

`$best_cf = current($avail_cf_functions);`

would be appropriate to return the first element.

## Screenshots
![image](https://user-images.githubusercontent.com/5182348/154469117-cd78c56e-996c-47f8-8010-af75963a7b3a.png)

- Version
Cacti 1.2.19 and above

**Comment by TheWitness** [comment]
Can you commit this?
