### ISSUE TITLE
Fix #4134 seems to not have been applied completely on 1.2.19

### ISSUE THREAD

**Issue by zuzzurro** [Cacti/cacti#4558]
On my fedora 35, running cacti 1.2.19 I get lots of errors in the log such as:

`2022/02/17 13:00:08 - ERROR PHP ERROR: Uncaught TypeError: Unsupported operand types: array & bool in /usr/share/cacti/lib/mib_cache.php:359 Stack trace: #0 /usr/share/cacti/lib/snmpagent.php(471): MibCache->update(Array) #1 /usr/share/cacti/poller.php(822): snmpagent_poller_bottom() #2 {main} thrown in file: /usr/share/cacti/lib/mib_cache.php on line: 359 `

Looking at line 359 it seems to me that there's still a boolean vs logical "and" error:

```
                        $columns = $this->cache__tables_columns[$this->active_mib][$this->active_table];
===>                    if ($columns & cacti_sizeof($columns)>0) {
                                $sql = array();
```

I replaced manually the & with && in my copy and the errors seem to have gone away.

**Comment by TheWitness** [comment]
Can you update to the 1.2.x branch and see if the issue persists?

**Comment by zuzzurro** [comment]
I prefer not to mess with the Fedora config and I strictly use the provided packages, so I would say no. But I looked at the 1.2.x branch and I see that my issue had already been reported and fixed (by completely removing the first component of the expression, "$columns & " . So I don't see why it should not work for me when I will receive 1.2.20.
I'm a bit puzzled about why in this particular case the fix is slightly different from the others but of course I know nothing of the Cacti internals.
I think this issue can be closed and I will make sure to recheck later after an upgrade.

**Comment by TheWitness** [comment]
We are in a testing phase.  The epel maintainer is watching.  Once we hit release, he'll follow suite.
