### ISSUE TITLE
cmd.php SNMP polling issue back in 1.1.0?

### ISSUE THREAD

**Issue by ekgermann** [Cacti/cacti#456]
Updated to 1.1.0 this morning.  Looks like the bug with polling is back

![image](https://cloud.githubusercontent.com/assets/9213892/24108012/b85b4fee-0d62-11e7-869f-1aab904a5bf6.png)

![image](https://cloud.githubusercontent.com/assets/9213892/24108069/ebd9ca08-0d62-11e7-947e-15054708f0de.png)

**Comment by ekgermann** [comment]
Appears clearing the poller cache may have fixed this.  I will close if it remains stable for a period of time

**Comment by cigamit** [comment]
Yea, I'm not seeing this on a new install.  But I did find some problems, but not related to this.
