### ISSUE TITLE
poller runtime errors with spine

### ISSUE THREAD

**Issue by densenator** [Cacti/cacti#4560]
# Describe the bug

19.02.2022 10:20:00 - POLLER: Poller[Main Poller] PID[8341] WARNING: There are 1 processes detected as overrunning a polling cycle, please investigate
19.02.2022 10:19:59 - POLLER: Poller[Main Poller] PID[7830] Maximum runtime of 298 seconds exceeded. Exiting.

## Desktop (please complete the following information)

- OS:  Debian 11.2
- PHP 8.1.2
- Apache/2.4.41
- Mariadb 10.3.32
- cacti 2.20

Chrome
Chrome  98.0.4758.102

**Comment by TheWitness** [comment]
Verify spine can actually run

```sh
./spine -R -V 3 -S
```

**Comment by densenator** [comment]
It is show any information.
And i turned off this errors with uncheck and check again "Enable Real-time Graphing"
sorry for this issue, it's mine
