### ISSUE TITLE
Advanced Ping issue

### ISSUE THREAD

**Issue by densenator** [Cacti/cacti#4561]
# Describe the bug

Advanced ping not showing pings more then 500

## To Reproduce

1. Install advanced ping 

2. Use it with very far devices

3. Not show ping more then 500

in server i run
root@cacti:/var/www/html/scripts# php -q ss_fping.php my-server.com 20 ICMP
min:603.6110 avg:615.5208 max:629.1850 dev:5.7867 loss:0.0000

## Screenshots
![image](https://user-images.githubusercontent.com/18443709/154804550-5d903667-99f1-4b0e-9717-2390bcdb193e.png)
![image](https://user-images.githubusercontent.com/18443709/154804564-5f44ebc8-6bc6-451a-aef6-bcb5b6cbe66f.png)
![image](https://user-images.githubusercontent.com/18443709/154804616-edd3ac82-d250-4ea1-8cf0-2389592a1cfb.png)
![image](https://user-images.githubusercontent.com/18443709/154804622-ff11e4fd-7d89-4ca1-a923-ff841cc65df3.png)

## Desktop (please complete the following information)

- OS: debian 11.2
- Apache/2.4.52
- PHP 8.1.2 
-  Cacti 1.2.20
-  10.5.12-MariaDB

Chrome
98.0.4758.102

**Comment by TheWitness** [comment]
I'm not sure what you are talking about here.

**Comment by densenator** [comment]
![image](https://user-images.githubusercontent.com/18443709/154805490-a59454d2-ab73-4cb2-a1d5-5e27da4e8808.png)

**Comment by TheWitness** [comment]
Edit the data template and make the Max U.  Then delete the rrdfiles or simply use the rrdtune to remove the max limit and make it U.

**Comment by TheWitness** [comment]
I've fixed this in a Graph Template package that will be available starting in 1.2.20.
