### ISSUE TITLE
Migration cacti from one server to another with CMDPHP PHP ERROR NOTICE Backtrace and not graphing

### ISSUE THREAD

**Issue by MegaAndrey** [Cacti/cacti#4566]
So I have installed new cacti (1.2.19, centos 7, php v7.1.33 and php v5.6 with fpm, rrdtool 1.7.1, poller spine). Copied old rrd files to new server with plugins. Cacti shows old data on graphs, but not recording new (nan) and data source troubleshooting not working too (endless loading). Also I observe this error in log:

2022-02-23 08:54:52 - CMDPHP PHP ERROR NOTICE Backtrace: (/graph_json.php[32]:include(), /include/auth.php[28]:require_once(), /include/global.php[553]:cacti_time_zone_set(), /lib/functions.php[6588]:timezone_name_from_abbr(), CactiErrorHandler())
2022-02-23 08:54:52 - ERROR PHP NOTICE: A non well formed numeric value encountered in file: /usr/share/cacti/lib/functions.php on line: 6588

Debug of graphs:
RRDtool Command:
/usr/bin/rrdtool graph - \
--imgformat=PNG \
--start='-86400' \
--end='-300' \
--pango-markup  \
--title='jet-colossus-1001864 - Traffic - Fa0/1' \
--vertical-label='bits per second' \
--slope-mode \
--base=1000 \
--height=150 \
--width=600 \
--tabwidth '30' \
--rigid \
--alt-autoscale-max \
--lower-limit='0' \
COMMENT:"From 2022-02-22 10\:31\:25 To 2022-02-23 10\:26\:25\c" \
COMMENT:"  \n" \
--color BACK#F3F3F3 \
--color CANVAS#FDFDFD \
--color SHADEA#CBCBCB \
--color SHADEB#999999 \
--color FONT#000000 \
--color AXIS#2C4D43 \
--color ARROW#2C4D43 \
--color FRAME#2C4D43 \
--border 1 --font TITLE:11:'Arial' \
--font AXIS:8:'Arial' \
--font LEGEND:8:'Courier' \
--font UNIT:8:'Arial' \
--font WATERMARK:6:'Arial' \
--slope-mode \
--watermark 'Generated by Cacti®' \
DEF:a='/usr/share/cacti/rra/jet-colossus-1001864_traffic_in_23338.rrd':'traffic_in':AVERAGE \
DEF:b='/usr/share/cacti/rra/jet-colossus-1001864_traffic_in_23338.rrd':'traffic_out':AVERAGE \
CDEF:cdefa='a,8,*' \
CDEF:cdefe='b,8,*' \
AREA:cdefa#00CF00FF:'Inbound '  \
GPRINT:cdefa:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefa:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdefa:MAX:'Maximum\:%8.2lf %s\n'  \
LINE1:cdefe#002A97FF:'Outbound'  \
GPRINT:cdefe:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefe:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdefe:MAX:'Maximum\:%8.2lf %s' 
RRDtool Command lengths = 1286 charaters.
RRDtool Says:
OK

Data Source Debug:
/usr/bin/rrdtool create \
/usr/share/cacti/rra/jet-colossus-1001864_traffic_in_23338.rrd \
--start 0 --step 300  \
DS:traffic_in:COUNTER:600:0:100000000 \
DS:traffic_out:COUNTER:600:0:100000000 \
RRA:AVERAGE:0.5:1:600 \
RRA:AVERAGE:0.5:6:700 \
RRA:AVERAGE:0.5:24:775 \
RRA:AVERAGE:0.5:288:797 \
RRA:MAX:0.5:1:600 \
RRA:MAX:0.5:6:700 \
RRA:MAX:0.5:24:775 \
RRA:MAX:0.5:288:797 \

**Comment by TheWitness** [comment]
This is more of a support request.  So long as the paths for all the binaries and the web site have not changed, and you have all the required binaries, the system should take right off.  You should review your Cacti log for any issues and check file permissions.  Can you continue this discussion on the forums?  Thanks!

**Comment by TheWitness** [comment]
At this point, it might be better to simply pulls the 1.2.x branch to clear that warning.
