### ISSUE TITLE
LDAP issue seems to still exist for me in 1.1.0

### ISSUE THREAD

**Issue by stormonts** [Cacti/cacti#457]
We had been running 1.0.5, LDAP was working fine, and then it broke when we upgraded to 1.0.6 giving a "Invalid User Name/Password Please Retype" error at login.  After upgrading to 1.1.0 things got even weirder.

When I try and login, I get a message that says "Error: Access Denied, user account disabled."
![access denied](https://cloud.githubusercontent.com/assets/25824323/24111975/875c4aae-0d6e-11e7-9fc9-0b162675a3d7.png)

I then log into Cacti as the local admin, go to Users, and see that a new user has been created with my same username. 
![users](https://cloud.githubusercontent.com/assets/25824323/24111991/91b79710-0d6e-11e7-9f32-f690672234a9.png)

 If I attempt to enable that second account and change it to LDAP, I get a message saying that the "username is already in use".  I then deleted the first account that I created and was then able to enable the one that appeared to be created as part of the login process.  However, then when I try to login, I get the same "Access Denied" message and another new account gets created in users:
![another new account](https://cloud.githubusercontent.com/assets/25824323/24112012/9a0b56fe-0d6e-11e7-82f8-37d99a6930ce.png)

Nothing seems to be failing when looking at the user logs:
![logs](https://cloud.githubusercontent.com/assets/25824323/24112075/c92a5462-0d6e-11e7-9248-eddd1dde2ee1.png)

**Comment by cigamit** [comment]
I can't say I'm happy about this.  Looks like 1.1.1 is to be on it's way.  This is not a little issue.  Sorry about that.

**Comment by cigamit** [comment]
Okay, fixed.  Sorry about that.  We had received confirmation that things were working from users, when in fact they were not.

**Comment by Yannis100** [comment]
Great thanks, I was on the way to report this issue too :)

**Comment by mbile** [comment]
How did you fix the issue? i am having the same problem here.

**Comment by netniV** [comment]
With which version?
