### ISSUE TITLE
Dashboard in Cacti

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#458]
The best feature to provide is Cacti dashboard on welcome page with:
- devices status divided in groups (ex. sites, importance) 
- openstreetmap with device positions and connections between devices
- thold summary with categories, Device Status Warnings and Notifications
- thold recent events
- max 5 main (most important) graphs
- last error from CLOG
- some statistics

If You got  >500 devices the monitor page is not as usefull as expected.
All others Monitoring system have got something like that.

The best I found (most useful) was in Observium. In zabbix there is also a good dashboard.
This enhancement would significantly change cacti perception and make usability better.

**Comment by cigamit** [comment]
There is a dashboard plugin in the wild already, and I think the author has updated it to 1.x.x format.  We are thinking about this subject as well.

**Comment by jenhek** [comment]
Just my 2¢: the "intropage" plugin is a pretty good dashboard

**Comment by interduo** [comment]
Is it working with last cacti-git version?

**Comment by jenhek** [comment]
Am 07.04.2017 um 15:47 schrieb Interduo:
> Is it working with last cacti-git version?
> 

Yes.

-- 
Dipl.-Phys. Jens Hektor, Networks
IT Center, RWTH Aachen University
Room 2.04, Wendlingweg 10, 52074 Aachen (Germany)
Phone: +49 241 80 29206 - Fax: +49 241 80 22100
http://www.itc.rwth-aachen.de - hektor@itc.rwth-aachen.de

**Comment by interduo** [comment]
Khmm it's pretty but it need's more information like I said in 1st post.

**Comment by cigamit** [comment]
We are looking for a more of a Grafana type approach with concepts like multiple dashboards, grid movement and to include various text and chart object types.  We want it to be pluggable and flexible.

This would not be a replacement for the Graph Trees, but rather a separate view into the data.

**Comment by xmacan** [comment]
Hi, I'm author of Intropage plugin (https://github.com/xmacan/plugin_intropage). It works with Cacti 1.0.5+ (I need chart.js v. 2). 
Two weeks ago I released version where is everything what I need (movable panels, 24 hours extrems, ...) ... but your requests "thold recent events" is good idea. 
I'm thinking about multiple Dashboard pages, second for your "5 important graphs".  

I will add this in few days. If you have another wish, please create new issue.

**Comment by netniV** [comment]
I will have to give your dashboard a go. I’ll let you know what I find :)

**Comment by jhonnyx82** [comment]
Hi Everyone,

Is there any plan for a dashboard then?

If none at the moment can you list somewhere what options we have, it would be useful for us.

Thanks in advance (long time no see :) )

**Comment by netniV** [comment]
@jhonnyx82 See above, the intropage is the currently common method :)

**Comment by jhonnyx82** [comment]
Thanks!

In case you wish to add to the core I think it wouldn't be such a bad idea!

**Comment by cigamit** [comment]
I'm looking to borrow another page from Grafana, but you guys keep throwing new bugs and features at me.  Can't keep up.

**Comment by cigamit** [comment]
Oh, and Intropage is pretty nice.

**Comment by subarusyd** [comment]
Hi

Pretty nice plugin. Just curious , is it possible to custom size the graphs we manually added to the Intro page dashboard?

Thanks

**Comment by netniV** [comment]
You need to open a request on the intropage repo https://github.com/xmacan/plugin_intropage

**Comment by netniV** [comment]
Since @cigamit has many other things on right now, I'm going to close this.  Once an integrated dashboard is written, I'm sure there'll be a new issue raised about it.
