### ISSUE TITLE
Due to inneficient checking of string values for replacement patterns, viewing graphs generates excessive database queries

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#4586]
testing the latest commits I am seeing huge degradation in performance of the preview mode

cycling through the changes I see the issue starts between

5d1b8e6 and 0971281

Rolling back to 18dc527  fixes the issue for me

**Comment by bmfmancini** [comment]
I have checked both local and LDAP accounts same issue seen 
Tree view and all other parts of the gui are fine except preview mode

**Comment by TheWitness** [comment]
This was resolved here, though it had nothing to do with any of those changes.  This is a big catch actually and will increase performance for many users.  Good catch.

https://github.com/Cacti/cacti/commit/1ebbfa4af2b103f46bdd51dcd4c3aa3214ee8acf

**Comment by TheWitness** [comment]
This was resolved in a one-on-one with @bmfmancini tonight.  It was some faulting `$sql_limit` syntax that was a) wrong, b) used in too many places.
