### ISSUE TITLE
Add variable time to report mail subject

### ISSUE THREAD

**Issue by coozoo** [Cacti/cacti#459]
Hi,
For me it's good to have possibility to add date of report to subject. So on my side I'm doing it in such way. By defining in subject keyword |date_time| and applying such patch, if you find it useful you can include it into source.
Patch attached (for version 1.0.4 but looks like it will work on latest version).
[functions.php.txt](https://github.com/Cacti/cacti/files/857721/functions.php.txt)

**Comment by cigamit** [comment]
Resolved, but a bit differently.  The date format is now a global setting, and users are still able to maintain their own setting for graphs, but this can now be extended to other areas of the GUI.
