### ISSUE TITLE
Missing IO Wait data source for graph Net-SNMP - CPU Utilization

### ISSUE THREAD

**Issue by hpaluch-pil** [Cacti/cacti#4592]
# Describe the bug

On fresh install with `NetSNMP_Device.xml.gz` package (using DEB package `cacti` under Debian) the
graph Template `Net-SNMP - CPU Utilization` reports error:

```
No Source: IO Wait:
```

## To Reproduce

1. Ensure that you have installed `NetSNMP_Device.xml.gz` package

2. Go to Templates -> Graph -> `Net-SNMP - CPU Utilization`

```
Item # 13	No Source: IO Wait:	AREA:STACK	AVERAGE	50%		00004D		
Item # 14	No Source: Current:	GPRINT	LAST					
Item # 15	No Source: Average:	GPRINT	AVERAGE					
Item # 16	No Source: Maximum:<HR>
```

And really there are only these related Data Source Templates found:
```
Net-SNMP - CPU - System
Net-SNMP - CPU - User
Net-SNMP - CPU - Idle
```

There is no `IO Wait` related DS  under Templates -> Data Sources

I have decoded base64 data from last  `<file>` element  of  `install/templates/NetSNMP_Device.xml`:
```
<file>
           <name>NetSNMP_Device.xml</name>
....
```
And really IO Wait DS is missing.

## Expected behavior

Data source `Net-SNMP - CPU - IOWait` should be added to
base64 content of `<name>NetSNMP_Device.xml</name>` in file
 `install/templates/NetSNMP_Device.xml`. 

## Screenshots

![no-iowait-ds-error](https://user-images.githubusercontent.com/30519713/156335797-4a6134e9-b0a2-4a40-91a8-df5771cdc095.png)

## Additional context

Tested this debian package:
```bash
$ dpkg -l cacti

Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-================================================
ii  cacti          1.2.16+ds1-2 all          web interface for graphing of monitoring systems
```
and its source package.

Unfortunately I don't know how is `install/templates/NetSNMP_Device.xml` created so I'm unable to provide fix so far.

**Comment by hpaluch-pil** [comment]
Now I see possible rationale - the Net-SNMP has no normalized (over minute) counter for Wait, only Raw counter. So maybe that is the reason for DS omission?

**Comment by TheWitness** [comment]
This is actually correct.  When this template was developed I/I wait source was not available.  It's the difference between everything else and 100%.  So there is no Data Source.  Just a cdef.

**Comment by hpaluch-pil** [comment]
What is noteworthy that on real Graph the "synthetic"  IO Wait is shown anyway. It seems to be automatically computed as sum up to 100%. When I turn Debug on, I see:
```
...
DEF:a='/usr/share/cacti/site/rra/localhost_sscpusystem_13.rrd':'ssCpuSystem':AVERAGE \
DEF:b='/usr/share/cacti/site/rra/localhost_sscpuuser_14.rrd':'ssCpuUser':AVERAGE \
DEF:c='/usr/share/cacti/site/rra/localhost_sscpuidle_12.rrd':'ssCpuIdle':AVERAGE \
CDEF:cdefbc='100,TIME,1646223989,GT,a,a,UN,0,a,IF,IF,TIME,1646223989,GT,b,b,UN,0,b,IF,IF,TIME,1646223989,GT,c,c,UN,0,c,IF,IF,+,+,-' \
...
AREA:cdefbc#00004D7F:'IO Wait\:':STACK \
GPRINT:cdefbc:LAST:'Current\:%8.1lf %%'  \
GPRINT:cdefbc:AVERAGE:'Average\:%8.1lf %%'  \
GPRINT:cdefbc:MAX:'Maximum\:%8.1lf %%\n' 
```

So I'm closing this issue.
