### ISSUE TITLE
Plugin tab does not stay visible when main poller is offline 

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#4598]
When you have a plugin that resides on multiple pollers the tab will disappear even if you you have offline_view = 1 and Remote_manage = 1 configured in the INFO file if the main poller goes offline 

In this case I have a modified version of the syslog plugin to run on multiple pollers and the only thing I can't get working is this

**Comment by TheWitness** [comment]
Try 'offline_mgmt:1'

**Comment by bmfmancini** [comment]
No go

I've tried this config as well but still no tab on remotes when primary is
down

***@***.*** syslog]# cat INFO
[info]
name = syslog
version = 3.2
longname = Syslog Monitoring
author = The Cacti Group
email =
homepage = http://www.cacti.net
compat = 1.2.10
capabilities = online_view:1, online_mgmt:1, offline_view:1,
 offline_mgmt:1, remote_collect:1, remote_manage:1, remote_v
iew:1
nosync = *.php,*.css,images,locales,template
***@***.*** syslog]#

**Comment by TheWitness** [comment]
Test the latest update.

**Comment by bmfmancini** [comment]
Same result

**Comment by TheWitness** [comment]
Should be resolved.  You will have to perform a Full Sync after updating.

**Comment by seanmancini** [comment]
Works like a charm !
