### ISSUE TITLE
Multiple DS's  created for a device when multiple graphs are created using a single DS template containing multiple DS items.

### ISSUE THREAD

**Issue by sbotnickusgs** [Cacti/cacti#4600]
Issue:
When creating a new device using custom DS, Graph and Device templates for a device with multiple graphs using a single script Data Input Method with multiple output fields, a DS is created for each graph. This happens when creating multiple graphs the first time for a device or adding graphs later.  I have run into this with multiple custom devices and when creating multiple graphs for the first time, it may or may not create a data source for each graph. When adding a graph to the device, it has consistently created new data sources for each graph when the data are already being acquired by an existing data source for the device.

## To Reproduce

Create new device with template.
Add graphs to device

## Expected behavior

I expect only one data source to be created for a device to supply all graphs for that device that use data from the one source.
With the included device template, creating a device and  creating all 5 graphs simultaneously usually results it creating 5 data sources. 

## Additional context

  I am currently running  Cacti 1.2.19 on CentOS7 and 8, but it happened with previous versions of Cacti, also.

Including the device template with dependencies.

[cacti_host_template_gill_met_simple.xml.zip](https://github.com/Cacti/cacti/files/8202146/cacti_host_template_gill_met_simple.xml.zip)

I believe https://github.com/Cacti/cacti/issues/3523 describes the same issue but it looks like it never went anywhere.

I don't believe it is user error, but I, the user, could be in error.

**Comment by TheWitness** [comment]
I can confirm that this is working perfectly in the 1.2.x branch or the 1.2.20 release.  If you enable `Data Source Trace` from `Console > Configuration > Settings > General` and then go to create the second Graph using the Data Source, you will find a series of log messages like the following.

![image](https://user-images.githubusercontent.com/1439914/157777642-da3c5336-f8aa-40fd-8337-ee47e4978c7a.png)

So, this issue is resolved.
