### ISSUE TITLE
Totaling 95 percentile on Aggregate value is null

### ISSUE THREAD

**Issue by anixT** [Cacti/cacti#4601]
If I aggregate two interface , aggregate graph gets plotted but the totaling value of 95 percentile is zero
![image](https://user-images.githubusercontent.com/44528428/157382293-5804450c-8466-4bfa-af07-de9313bc1f53.png)

**Comment by TheWitness** [comment]
You did not state your version...

**Comment by anixT** [comment]
I am using cacti 0.8.8h with aggregate-v1.10.tgz .
Please help

**Comment by TheWitness** [comment]
We are no longer supporting that release.  I would suggest you give 1.2.20 a try once it's released.  Be sure that you review the minimum requirements.  If you are at a bad PHP level, try using the REMI repos for PHP as he's can take you all the way to PHP8, though I suggest you stay at PHP7.4 for now.
