### ISSUE TITLE
Undefined function call get_guest_account in global_languages  - Installation of 1.2.20 failing

### ISSUE THREAD

**Issue by browniebraun** [Cacti/cacti#4602]
# Describe the bug

Fresh installation of 1.2.x as remote poller will fail with error message:

Fatal error: Uncaught Error: Call to undefined function get_guest_account() ....

## To Reproduce

To reproduce that error it is required to clear browser cache first.
When you call the new system instance for the first time to start the installation wizard the browser returns following message:

`Fatal error: Uncaught Error: Call to undefined function get_guest_account() in /proj/cacti/www/cacti/include/global_languages.php:700 Stack trace: #0 /proj/cacti/www/cacti/include/global_languages.php(64): read_user_i18n_setting('user_language') #1 /proj/cacti/www/cacti/include/global.php(513): include_once('/proj/cacti/www...') #2 /proj/cacti/www/cacti/include/auth.php(27): require_once('/proj/cacti/www...') #3 /proj/cacti/www/cacti/index.php(25): include('/proj/cacti/www...') #4 {main} thrown in /proj/cacti/www/cacti/include/global_languages.php on line 700`

## Reason
Function get_guest_account() will be defined in /lib/auth.php, but within global.php at line 512 global_languages will be loaded before the library becomes available:

```
define('CACTI_DATE_TIME_FORMAT', date_time_format());

include_once($config['include_path'] . '/global_languages.php');
include_once($config['library_path'] . '/auth.php');
```

**Comment by TheWitness** [comment]
Resolved this by moving the two functions to lib/functions.php.  Since this is a bug that happened between releases, I'm not including a ChangeLog.
