### ISSUE TITLE
[CACTI LATEST] 1.2.x branch - midwinter theme

### ISSUE THREAD

**Issue by anarkia1976** [Cacti/cacti#4605]
# Describe the bug

Possible problem related to impossibility to insert text and filter into the search box when we have selected the chart/tree view.
![image](https://user-images.githubusercontent.com/1744639/157817159-a01c13a0-db17-437c-9695-b72c8b7e2eab.png)

## To Reproduce

Go to Dashboard --> Charts --> Tree View.

Thanks a lot
stefano

**Comment by TheWitness** [comment]
Thanks for continuing to test @anarkia1976

**Comment by TheWitness** [comment]
Andi, I pushed a commit that I think might work better.  Let me know what you think...

**Comment by TheWitness** [comment]
Well, that is an entirely different issue.  Please log it separately.  @browniebraun is working on it.  He can add this to the plate too.

**Comment by TheWitness** [comment]
It is a new issue, and I can confirm...

![image](https://user-images.githubusercontent.com/1439914/158188627-242e2245-b749-4f3e-9e57-e93bf8d5cfe0.png)

vs.

![image](https://user-images.githubusercontent.com/1439914/158188768-2e130390-3608-4436-8a9b-4cf83c0e8d97.png)

**Comment by TheWitness** [comment]
@browniebraun, do you want a separate ticket, or are you okay working with these as one?

**Comment by browniebraun** [comment]
Leave it as one ticket.

**Comment by TheWitness** [comment]
Closing this one as it's stale.
