### ISSUE TITLE
Create user or user groups show error in log

### ISSUE THREAD

**Issue by densenator** [Cacti/cacti#4606]
# Describe the bug

<html>
<body>

11.Mar.2022 16:23:23 - CMDPHP PHP ERROR NOTICE Backtrace: (/user_admin.php[55]:user_edit(), /user_admin.php[1900]:CactiErrorHandler())
--
11.Mar.2022 16:23:23 - ERROR PHP NOTICE: Trying to access array offset on value of type null in file: /var/www/html/cacti/user_admin.php on line: 1900
11.Mar.2022 16:23:23 - CMDPHP PHP ERROR NOTICE Backtrace: (/user_admin.php[55]:user_edit(), /user_admin.php[1900]:CactiErrorHandler())
11.Mar.2022 16:23:23 - ERROR PHP NOTICE: Undefined variable: user in file: /var/www/html/cacti/user_admin.php on line: 1900

</body>
</html>

## To Reproduce

1. Go to 'users'

2. Copy user

3. See error

## Desktop (please complete the following information)

- OS: debian 11
- cacti 1.2.20
- PHP 7.4.28
- 10.5.12-MariaDB
- Apache/2.4.52

chrome
99.0.4844.51

**Comment by TheWitness** [comment]
Thanks for testing.  Please apply the latest update and let me know if everything is back to normal.

**Comment by TheWitness** [comment]
Resolved, but no changelog on this one as it was created between releases.
