### ISSUE TITLE
Plugin disabled automatically on cacti release 1.2.19

### ISSUE THREAD

**Issue by bentech4u** [Cacti/cacti#4619]
HI 

i have installed plugin and it was working perfectly. But every day it is disabling automatically 

Cacti Version | 1.2.19
-- | --
Cacti OS | unix
NET-SNMP Version | NET-SNMP version: 5.8
RRDtool Version Configured | 1.7.0+
RRDtool Version Found | 1.7.0

**Comment by TheWitness** [comment]
What was the release of PHP that you are using?

**Comment by bentech4u** [comment]
PHP 7.2.24

**Comment by TheWitness** [comment]
This issue is now duplicate.  Closing this one.
