### ISSUE TITLE
LDAP authorization issue: group membership check broken for 'Group Member Type' = 'Username'

### ISSUE THREAD

**Issue by paddydoyle** [Cacti/cacti#462]
Hi,

We're using cacti on Scientific Linux 6 (old, I know!), and got caught recently with an LDAP authorization bug when RHEL6 upgraded from 0.8.8h to 1.0.4.

The issue occurs with these LDAP settings:

- Require Group Membership: on
- Group Member Type: Username

In the apache error logs, we see:

`PHP Warning:  ldap_get_dn() expects parameter 2 to be resource, boolean given in /usr/share/cacti/lib/ldap.php on line 267`

After some digging, it seems that commit c5a5e02 flipped the logic between 'Group Member Type: Username' and 'Group Member Type: Distinguished Name', and the expanded DN search code was added to the Username branch (it got rid of Username completely).

I'll submit a fairly small pull request which fixes it.

Thanks,
Paddy

**Comment by cigamit** [comment]
Please test the commit that was just done.  Trying to meet in the middle and improve the log handling at the same time.  If it works, we can simply close the pull request.

**Comment by paddydoyle** [comment]
Hi Jimmy,

Yup, d13f1f8 fixes it for me as well.

Thanks for the speedy response and fix!

Paddy

**Comment by cigamit** [comment]
Thanks for testing too.  Every bug makes Cacti better.
