### ISSUE TITLE
Error Unknown column 'snmp_sysUpTimeInstanceAlt' in 'field list'

### ISSUE THREAD

**Issue by nani81** [Cacti/cacti#4624]
# Describe the bug

Hi, I have upgraded my cacti from 1.1.38 to 1.2.19. (On a linux server (RedHat)
When I look at the log I find several failures continuously:
"2022/03/15 16:12:35 - CMDPHP SQL Backtrace: (/cmd.php[349]:ping_and_reindex_check(), /cmd.php[721]:update_system_mibs(), /cmd.php[576]:db_execute_prepared())"
"2022/03/15 16:12:35 - CMDPHP ERROR: A DB Exec Failed!, Error: Unknown column 'snmp_sysUpTimeInstanceAlt' in 'field list'"

And I can't manage to solve it.
Can you help me, thanks

![cacti](https://user-images.githubusercontent.com/51642177/158410907-d9de088c-cbfc-43f6-a137-9363a2b83d90.png)

**Comment by TheWitness** [comment]
I think that's it.

**Comment by nani81** [comment]
Hello, I understand that it is "upgrade_database.php"
I have executed it and nothing, it keeps giving the same error:

[root@server /var/www/cacti]# sudo -u cactiuser php -q cli/upgrade_database.php --forcever=1.1.38
Upgrading from v1.1.38
Upgrade from v1.1.38 (DB 1.2.19) to v1.2.0
++++++++++++++-++++++++++++++++++++++++++++Update from v1.2.0 (DB 1.2.19) to v1.2.1
++Upgrade of v1.2.1 (DB 1.2.19) to v1.2.2
++Upgrade from v1.2.2 (DB 1.2.19) to v1.2.3
++++++Upgrade of v1.2.3 (DB 1.2.19) to v1.2.5
+++Upgrade from v1.2.5 (DB 1.2.19) to v1.2.7
-Upgrading from v1.2.7 (DB 1.2.19) to v1.2.8
+++++Upgrade from v1.2.8 (DB 1.2.19) to v1.2.11
+Upgrade from v1.2.11 (DB 1.2.19) to v1.2.14
+Upgrading from v1.2.14 (DB 1.2.19) to v1.2.15
+Upgrade from v1.2.15 (DB 1.2.19) to v1.2.17
++++Upgrade from v1.2.17 (DB 1.2.19) to v1.2.19

I have seen that in the file "cmd.php" there is the entry "snmp_sysUpTimeInstanceAlt" but in the database in the table "host" there is not.

Is this normal?
Thanks

**Comment by bmfmancini** [comment]
These are all the snmp tables I have in my DB on a working system

```
MariaDB [cacti]> show tables like '%snmp%';
+-------------------------------------+
| Tables_in_cacti (%snmp%)            |
+-------------------------------------+
| automation_snmp                     |
| automation_snmp_items               |
| host_snmp_cache                     |
| host_snmp_query                     |
| host_template_snmp_query            |
| snmp_query                          |
| snmp_query_graph                    |
| snmp_query_graph_rrd                |
| snmp_query_graph_rrd_sv             |
| snmp_query_graph_sv                 |
| snmpagent_cache                     |
| snmpagent_cache_notifications       |
| snmpagent_cache_textual_conventions |
| snmpagent_managers                  |
| snmpagent_managers_notifications    |
| snmpagent_mibs                      |
| snmpagent_notifications_log         |
+-------------------------------------+
17 rows in set (0.000 sec)
```

Try running analyze_db.php

**Comment by TheWitness** [comment]
Good catch @nani81, I've made a fix.  Easy enough to just replace your `cmd.php`.
