### ISSUE TITLE
no side menu in the graphs

### ISSUE THREAD

**Issue by nani81** [Cacti/cacti#4625]
Good,
since I have upgraded from 1.1.38 to 1.2.19 I don't see the side menu of the graphs to be able to, see their properties, see the real time pricing, graph times, .....

Thanks
![ahora_antes](https://user-images.githubusercontent.com/51642177/158440750-8766c11c-24ec-4d19-905f-67551d356d7e.png)

**Comment by browniebraun** [comment]
This is not a bug. You have to update your user permissions to enable the graph action items:

![2021-12-14 10 23 29 localhost 8366ebb9fba0](https://user-images.githubusercontent.com/5182348/158442467-691f0aef-4ff6-40fd-ad97-e30980e2bcfc.jpg)

**Comment by nani81** [comment]
Thank you very much, and I am sorry to have created an issue for this.
I have already activated it

**Comment by browniebraun** [comment]
I forgot that multiple times while installing a new release,  so don't worry. 😀
