### ISSUE TITLE
Input Field Checking is not enforced upon creation of Data Source

### ISSUE THREAD

**Issue by riversdev0** [Cacti/cacti#4632]
# Describe the bug

If you have a custom field attached to a Data Input Method, that field will only be validated for acceptable data upon being edited, not upon creation.

## To Reproduce

1. Create a Data Input Method with a custom Input Field
![image](https://user-images.githubusercontent.com/7363202/158818103-8932682f-d9d2-4911-a4fb-271d6f399922.png)

2. Set a Regular Expression Match on the Input Field
![image](https://user-images.githubusercontent.com/7363202/158818187-8b12bcff-3c70-41fb-b67f-2fbbba792832.png)

3. Create a Data Source Template that allows the user to modify the value of Input Field
![image](https://user-images.githubusercontent.com/7363202/158818288-1de15a76-4299-40de-ac49-240d98321f71.png)

4. Create a Graph Template referencing that Data Source Template
5. Add a graph using that template to a device.  Set the Custom Data to something outside the range of the validation pattern.
![image](https://user-images.githubusercontent.com/7363202/158888552-aa614156-f482-4978-b080-e8590ae00c92.png)

6. Edit the brand new Data Source and observe that the value is out of range.
![image](https://user-images.githubusercontent.com/7363202/158818613-745375d0-4ca1-4b49-8830-ae1c26ba76e1.png)

7. Save the Data Source with no changes.  Observe that the validation fails.
![image](https://user-images.githubusercontent.com/7363202/158818640-14eb7877-4999-4520-97e0-3f49b532e29d.png)

## Expected behavior

I would expect the Input Field Checking validation pattern to be enforced upon creation of the Data Source, just as it is during the modification of the Data Source.

## Version info

- Cacti 1.2.19

## Additional context

I'm willing to help fix this, but some others probably know from memory where the relevant code is located.

**Comment by TheWitness** [comment]
Never used that feature, though I can see why it's handy.

**Comment by TheWitness** [comment]
So, question, I'm assuming you are manually creating the data source rather than doing so using the template engine.  Is this a correct assumption?

**Comment by riversdev0** [comment]
The way I'm creating the graph is by navigating to the Device, and clicking "*Create Graphs for this Device" and picking the Graph Template from the drop down.  This method was used to produce the screenshots above.

I do have a point of confusion, however, about how the process described in the sentence above is different than picking the Graph Template directly from the Device page, without first clicking "*Create Graphs for this Device".  Here's a screenshot of what I'm referring to, "directly on the Device page".
![image](https://user-images.githubusercontent.com/7363202/158822105-ae2a1ee2-14d2-4fad-ad42-e1e888737f83.png)

My confusion is that if I add the graph directly from the Device page, Cacti "remembers" the graph being there, as illustrated in this screenshot:
![image](https://user-images.githubusercontent.com/7363202/158822993-c74163de-af51-4ac5-a60b-f8a99ee8c1fa.png)

Yet, if I create the graph from the "*Create Graphs for this Device" page, cacti doesn't display any evidence that the device has the graph (except it is does appear on the "Graphs" page and it does fully work, there is just no evidence on the Device page).

**Comment by TheWitness** [comment]
The process is somewhat confusing, but glad you clarified.

**Comment by TheWitness** [comment]
You will have to force load your pages `include/layout.js`, but after which, you should be able to test this.

**Comment by TheWitness** [comment]
@riversdev0, just checking in to see if you are satisfied with the fix...

**Comment by TheWitness** [comment]
You need to force reload the new layout.  Browsers like chrome make it hard without clearing your cache.

**Comment by riversdev0** [comment]
Ok, I tried it in a Private browser window and I was able to see the error message, and was able to correct the value, and the new graph was created.  I think the change worked as expected!  Thank you!
