### ISSUE TITLE
SNMPAGENT WARNING: No notification receivers configured for event:

### ISSUE THREAD

**Issue by nani81** [Cacti/cacti#4638]
Good morning, I have updated my cacti to version 2.1.19 and since the update, I get the following warning
"SNMPAGENT WARNING: No notification receivers configured for event: cactiNotifyDeviceFailedPoll (CACTI-MIB), severity: medium"

I have read that I have to have "SNMP Agent" support enabled. Well, I have it enabled, but I still get the warnings.
I attach screenshots.
Thanks
![warning](https://user-images.githubusercontent.com/51642177/159242079-1bc336a7-e5cf-448b-b6e2-1e83a52b339e.png)
![snmp_agent](https://user-images.githubusercontent.com/51642177/159242096-e214a14b-bf51-4eeb-a9c0-e1082e7264d8.png)

**Comment by browniebraun** [comment]
This is not a bug. This message means that the SNMPagent normally would like to inform an external SNMP trap receiver about an event that has just discovered (host down). Trap receivers can be configured under  Utilities->System Utilities.
If not needed you could also disable the SNMP agent under Configuration->Settings->Poller.

Regards
-Andi
