### ISSUE TITLE
Yearly graphs for newly created data sources don't seem to be updating

### ISSUE THREAD

**Issue by ekgermann** [Cacti/cacti#464]
Upgraded from the 0.8x series to 1.x series and not sure which of the releases it showed up in, but newly created devices don't seem to update their Yearly graphs for network interfaces.  Seems to work OK for other host related parameters on ucd/snmp, but not Yearly network.  Network definition is bps (95th percentile)

Devices/graphs created before seem to update OK.

![image](https://cloud.githubusercontent.com/assets/9213892/24175679/e3d628ea-0e6d-11e7-9ed5-cbdb762a386f.png)

![image](https://cloud.githubusercontent.com/assets/9213892/24175703/fe5202ca-0e6d-11e7-926e-c6742098f0d2.png)

**Comment by cigamit** [comment]
What is in the cacti log?  Are there entries in the poller cache.  I'm a little concerned that this may not be a bug.  Also, edit the data source and verify that the index is correct.

**Comment by ekgermann** [comment]
Log, poller cache and DS.

It updates all graphs with the DS except the yearly eth0 graph (the other 3 are fine for eth0).  Running rrdtool 1.6.0 built from source.  What triggers update of yearly graph?


cacti.log-20170321:2017-03-20 18:10:37 - POLLER: Poller[1] Device[266] DS[4043] SNMP: v2: <REDACTED>, dsname: traffic_out, oid: .1.3.6.1.2.1.31.1.1.1.10.6, output: 9440999
cacti.log-20170322:2017-03-21 05:25:32 - WEBUI WARNING: Removed '775' Spikes from <REDACTED>, Method:'2'

![image](https://cloud.githubusercontent.com/assets/9213892/24177231/7dd84834-0e77-11e7-9a2d-ece959a60814.png)

![image](https://cloud.githubusercontent.com/assets/9213892/24177354/39d33e04-0e78-11e7-9e0a-8852e5fbc1f5.png)

**Comment by cigamit** [comment]
It looks like the spike killer is killing you.  I would disable that for a moment and let's see what happens.

**Comment by ekgermann** [comment]
Will do and let it run for a few days.

The perplexing question is, why are pre-1.x updating if that is it?  We shall see.

**Comment by ekgermann** [comment]
Spikekill does indeed appear to be the issue.  Disabling allows data to show up in the yearly graph.

**Comment by cigamit** [comment]
Goto Console->Settings->Spikes and post a screen shot of your current settings.

**Comment by ekgermann** [comment]
![image](https://cloud.githubusercontent.com/assets/9213892/24201321/bb74867e-0edd-11e7-99cc-906a19f0df1d.png)


![image](https://cloud.githubusercontent.com/assets/9213892/24201374/db7dea28-0edd-11e7-855d-d0d473b15840.png)

**Comment by cigamit** [comment]
Please perform an 'rrdtool dump' of the RRDfile and upload it.  This is rrdtool 1.6.  Something might have changed.

**Comment by ekgermann** [comment]
Attached.

[4099.xml.gz](https://github.com/Cacti/cacti/files/863458/4099.xml.gz)

**Comment by cigamit** [comment]
I did not find anything interesting in the RRDfile.  My suspicion is that standard deviation is a bad idea for traffic graphs especially.  Try manually running dry run's on the graph from the GUI and see what comes back.  Take screen shots of the dryrun at different variance and standard deviation levels.

**Comment by cigamit** [comment]
Found the bug.  Resolving.  Also changing defaults.  The limit on the number of spike's killed was not respected in some cases.
