### ISSUE TITLE
REAPPLY SUGGESTED NAME DOES NOT WORK IN 1.2.18 CACTI

### ISSUE THREAD

**Issue by gj00354347** [Cacti/cacti#4640]
# Describe the bug

Dear Developers ,

I have come across an issue where a few graphs are suffixed with wrong tag and I want to correct them with right name . It's for error discard graph for interface called eth-s1p1 and eth-s1p2 .

so whenever I try to to apply the new naming convention through Reapply suggested name feature , cacti 1.2.18 fails to find the value of variable |query_ifName|  although the interface for which I am doing this has got |query_ifName| in cacti .PFB snapshot for eth-s1p1 and eth-s1p2

generally what happens that |query_ifName| or some other variable is evaluated before you click on CONTINUE BUTTON .but here it does not happen , and in case , even if I ignore this evaluation , it does not happen even after we click on CONTINUE BUTTON.

![image](https://user-images.githubusercontent.com/27295357/159300406-68150d0a-e003-4275-81f4-a6bc271b9aac.png)
![image](https://user-images.githubusercontent.com/27295357/159301294-f40f9dca-bc9f-4f4c-9cb0-f0423a853a18.png)

## To Reproduce

don't know because cacti sometimes works without any issue and reapply suggested name works fine but sometimes I face this anomalous behaviour.

**Comment by TheWitness** [comment]
@gj00354347, we are aware of this issue and there is a repair script in the install/updates/1.2.20.php file that will fix things, or should anyway.  We are hoping to get 1.2.20 released this weekend.  You should update at your earliest convenience.  In the mean time, the repair steps are documented in that upgrade script.  You should consider running them manually if upgrading will present more issues.

**Comment by TheWitness** [comment]
Note though, if the interface has been removed, the rename should not change the titles.

**Comment by gj00354347** [comment]
so @TheWitness Larry , we will have to run this php script after installation of 1.2.20 , like /path-to-cacti/install/updates/1.2.20.php  or after successful  installation of 1.2.20  we have to do "REAAPLY SUGGESTED NAME" and that will fix the issue ??

**Comment by TheWitness** [comment]
It should.  Basically the upgrade script will run itself upon upgrade.  You won't have to run anything.  It will fix any broken associations it encounters, after which if the re-apply is still not working, we may require a database dump.
