### ISSUE TITLE
Cacti 1.2.19, Active directory authentication issue

### ISSUE THREAD

**Issue by bentech4u** [Cacti/cacti#4644]
HI

i have cacti installation 1.2.19 with below LDAp settings which is not working.

![image](https://user-images.githubusercontent.com/4426408/159669264-5db28e91-abaf-46a6-83fa-9259df49de1e.png)

I have another installation of Old cacti 0.8.8g with same LDAP settings working.

![image](https://user-images.githubusercontent.com/4426408/159669647-fdb0fb36-0f5c-4e19-bbb6-0ef1548b7480.png)

---------------------------------------- Logs ---------------------------------------------
2022-03-23 12:06:35 - AUTH LDAP: Insufficient Access to Server (corp.example.kw)
2022-03-23 12:06:35 - AUTH LOGIN: LDAP Error: Insufficient Access to Server (corp.example.kw)
2022-03-23 12:06:35 - AUTH LOGIN: LDAP Login Failed for user 'ntg022' from IP Address '10.15.14.117'.

**Comment by seanmancini** [comment]
Insufficient Access to Server indicates your LDAP user doesn't have the proper group access 
on your 0.8 system you don't have require membership checked but on your new system you do this tells ldap that the user must be part of the member group to authenticate

**Comment by TheWitness** [comment]
@seanmancini there is hope after all ;)

**Comment by bmfmancini** [comment]
@TheWitness  theres always hope :)

**Comment by bentech4u** [comment]
HI,

i have updated group like below and from AD side the user which i am trying to login is part of that group

![image](https://user-images.githubusercontent.com/4426408/159876967-42ba23ed-a81b-4f2a-bf53-d7684076f3b8.png)

![image](https://user-images.githubusercontent.com/4426408/159877324-c1305391-820d-4d45-ab6f-5c03debf592f.png)


2022-03-24 11:41:50 - AUTH LDAP: Insufficient Access to Server (corp.example.kw)
2022-03-24 11:41:50 - AUTH LOGIN: LDAP Error: Insufficient Access to Server (corp.example.kw)
2022-03-24 11:41:50 - AUTH LOGIN: LDAP Login Failed for user 'ntg022' from IP Address '10.15.14.122'.

**Comment by bentech4u** [comment]
Issue has been solved, Thanks for support

**Comment by nani81** [comment]
Good, how did you solve the problem I can't solve it.
thanks

**Comment by nani81** [comment]
> Issue has been solved, Thanks for support

Good, how did you solve the problem I can't solve it.
thanks
