### ISSUE TITLE
Script_server.php not able to receive STDIN arguments

### ISSUE THREAD

**Issue by mihirprad** [Cacti/cacti#4647]
# Describe the bug

Hi there, 
I am having an issue when trying to create a graph using a script in cacti. It seems that the "script_server.php" isnt receiving any of the command line inputs provided by the data input method.

## To Reproduce

1. create a data input method using script server. 

2. Create a graph using this data input method

## Expected behavior
![image](https://user-images.githubusercontent.com/84665785/159821140-de27196b-07aa-4ce8-8e55-f17c0cea89d6.png)

In line 156 of script_server.php , the script tries to read the stdin inputs but it looks like it is returning an empty string. This is causing cacti to terminate the script early.

![image](https://user-images.githubusercontent.com/84665785/159821339-de9256b3-0973-4aa7-8f2a-d4e0752dcaef.png)

I added a log to show what cacti was scanning in and this was the result: an empty string
![image](https://user-images.githubusercontent.com/84665785/159821404-0c7d3181-3ba8-4ff3-a2d2-f868596bdc5a.png)

however, when i try this on another instance of cacti it seems to be working properly (black box has confidential data)
![image](https://user-images.githubusercontent.com/84665785/159821509-8cba4961-0566-4593-972f-1c4d2d725679.png)

Finally this is the data input method it self:
![image](https://user-images.githubusercontent.com/84665785/159821588-9e4874db-e41b-4b20-8426-cfc2aab0c282.png)

Note: the data input method was imported from the working version of cacti so im not sure why it is not working since everything is identical. Both cactis are version 1.2.18

## Desktop (please complete the following information)

- OS:  RHEL 7

- Chrome

**Comment by TheWitness** [comment]
How long is your input string?  Per your other ticket, did you post the poller cache?

**Comment by TheWitness** [comment]
```sql
SELECT max(length(arg1)) FROM poller_item;
```

**Comment by TheWitness** [comment]
No feedback.
