### ISSUE TITLE
[1.2.20] - Advanced ping template has port default override enabled by default

### ISSUE THREAD

**Issue by seanmancini** [Cacti/cacti#4649]
When trying to add the advanced ping graph template to a host via automation errors will occur with the following

```
Graph not added due to no default value for overridable field.
```

the default graph template looks like this 

![image](https://user-images.githubusercontent.com/69045419/160466574-8d30e5f2-e04b-43b5-9bfe-9cba69704211.png)

Turning off the port default override fixes the issue 
by default the template will use ICMP anyway so this should be off by default unless the admin wants to use TCP/UDP ping by default

**Comment by bmfmancini** [comment]
PR https://github.com/Cacti/cacti/pull/4650

**Comment by TheWitness** [comment]
This is actually a bug with some protections that were put into the code for 1.2.20.  Good thing you caught it.  Have to fix this before 1.2.20 release.

**Comment by TheWitness** [comment]
@xmacan, It's likely one of the recent packages that include that Template.  We should ensure that Advanced Ping is not integrated into any Device Packages.

**Comment by TheWitness** [comment]
Maybe we need to translate the null to an empty string.  Let me approach it that way.

**Comment by TheWitness** [comment]
It might have been me too ;)

**Comment by TheWitness** [comment]
Okay, I've refixed it in both the 1.2.x branch and develop now.
