### ISSUE TITLE
Less than sign inside items and labels of graph make them broken

### ISSUE THREAD

**Issue by coozoo** [Cacti/cacti#465]
Hi sorry for that very small bug :)
If set less than sign (<) for label and item it will make them broken.
**Greater than sign works fine(>).**
In label and item it behaves in little bit different way if replace with escape sequences please see below.

1. **Example for an old version 0.8.8** - _correct result_
![lessthan0 8 8](https://cloud.githubusercontent.com/assets/25594311/24205313/b27e20a2-0f23-11e7-8e85-aba070e1ecc5.png)

In graph debug it's converted to this:
`--vertical-label="test(down if <1)" \
GPRINT:a:MIN:"MIN(<1)\:%8.2lf %s"  \`

_So pay attention to double quotes inside command._

2. **Current result version 1.0.4** - _incorrect result_
![lessthan1 0 4](https://cloud.githubusercontent.com/assets/25594311/24205412/069258e8-0f24-11e7-8831-cb5768fc8d52.png)

In graph debug it's converted to this:
`--vertical-label='Sitecore State (down if <1)' \
GPRINT:a:MIN:'DOWN(<1)\:%8.2lf %s'  \`

_Pay attention that in new version it's single quoted._

3. **Current result version 1.0.4 escape sequence** - _incorrect result_
![lessthanescapesequences1 0 4](https://cloud.githubusercontent.com/assets/25594311/24205568/67d7a6da-0f24-11e7-9d86-22cbea41825e.png)

In graph debug it's converted to this:
`--vertical-label='Sitecore State (down if &lt;1)' \
GPRINT:a:MIN:'DOWN(lt;1)\:%8.2lf %s'  \`

_You can see that escaped works fine for label, but inside item ampersand sign is missed that's why workaround doesn't work here._

Thank you

**Comment by cigamit** [comment]
Well, we have been trying to simplify the lib/rrd.php code.  We escapted the title, but not the axis or the legends.  So, I'm not surprised.  Thanks for reporting.  Should not take to long to find the proper approach to resolving this.

**Comment by cigamit** [comment]
Please test with the latest lib/rrd.php and provide feedback.  Thanks for reporting.

**Comment by coozoo** [comment]
Hi thanks, I've tested it little bit
**Less than fixed** 
but another side effect appeared
Line breaks (Insert Hard Return checkbox `<HR>`) for items are not correctly working there is n (suppose it's somehow related to replacing backslash in \n) at the end of each string
![linebrakebroken](https://cloud.githubusercontent.com/assets/25594311/24242071/5af22aee-0fbf-11e7-8b12-aeca316eb794.png)

And you can see that there is case that sometimes linebreaks works but still n at the end
![linebrakebroken2](https://cloud.githubusercontent.com/assets/25594311/24242266/ee2ba90c-0fbf-11e7-9852-8816c6c1ece8.png)

In both cases rrd command, on webpage from debug, looks identically:
`GPRINT:cdeffa:LAST:'CUR\:%8.2lf %s'\n  \`
So i'm not sure what the reason of this.
thank you

**Comment by coozoo** [comment]
Great work, thanks now it works fine :)

![correctmultilinelessthan](https://cloud.githubusercontent.com/assets/25594311/24261866/108ebd18-1001-11e7-9ca8-d69d49e77b76.png)
