### ISSUE TITLE
After repopulating graph, navigation to check cumbersome

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#4652]
# Describe the bug

When you use the 'Repopulate Poller Cache' option whilst editing a device, this is useful for individual device updates.  However, to then verify the outcome of this, you have to navigate through several screens and filters to see the desired results.  This should be easily navigatable for debugging purposes.

## Expected behavior

A simple link to show just that device's poller cache

**Comment by TheWitness** [comment]
Sub-tabs are the way to go.  Maybe bring them back in 1.2.21.  We implemented in 0.8.9, but never released it.
