### ISSUE TITLE
PHP ERROR NOTICE Backtrace

### ISSUE THREAD

**Issue by densenator** [Cacti/cacti#4657]
# Describe the bug

<html>
<body>

31.Mar.2022 15:00:07 - CMDPHP PHP ERROR NOTICE Backtrace: (/script_server.php[189]:fputs(), CactiErrorHandler())
--
31.Mar.2022 15:00:07 - ERROR PHP NOTICE: fputs(): write of 53 bytes failed with errno=32 Broken pipe in file: /var/www/html/cacti/script_server.php on line: 189
31.Mar.2022 15:00:07 - CMDPHP PHP ERROR NOTICE Backtrace: (/script_server.php[154]:fgets(), CactiErrorHandler())
31.Mar.2022 15:00:07 - ERROR PHP NOTICE: fgets(): read of 8192 bytes failed with errno=9 Bad file descriptor in file: /var/www/html/cacti/script_server.php on line: 154
31.Mar.2022 15:00:07 - CMDPHP PHP ERROR NOTICE Backtrace: (/script_server.php[154]:fgets(), CactiErrorHandler())
31.Mar.2022 15:00:07 - ERROR PHP NOTICE: fgets(): read of 8192 bytes failed with errno=9 Bad file descriptor in file: /var/www/html/cacti/script_server.php on line: 154
31.Mar.2022 15:00:07 - CMDPHP PHP ERROR NOTICE Backtrace: (/script_server.php[154]:fgets(), CactiErrorHandler())

</body>
</html>

## To Reproduce

Maybe use some utilites

Cacti 1.2.20

**Comment by TheWitness** [comment]
The poller is timing out.  How many script servers?  Have you performed a manual debug run to trace slow script server calls for timeouts?

**Comment by TheWitness** [comment]
If you run the following from the command prompt, that would be good.

`./spine -R -V 5 -S`

I'd like to see the front end of the run.  It'll look as follows:

```sh
[root@vmhost3 bin]# ./spine -R -V 5 -S
SPINE: Using spine config file [../etc/spine.conf]
Total[0.0060] DEBUG: The path_php_server variable is /var/www/html/cacti/script_server.php
Total[0.0060] DEBUG: The path_cactilog variable is /var/www/html/cacti/log/cacti.log
Total[0.0060] DEBUG: The version variable is 10.5.15-MariaDB
Total[0.0060] DEBUG: The log_destination variable is 4 (STDOUT)
Total[0.0062] DEBUG: The path_php variable is /bin/php
Total[0.0063] DEBUG: The availability_method variable is 2
Total[0.0064] DEBUG: The ping_recovery_count variable is 3
Total[0.0065] DEBUG: The ping_failure_count variable is 2
Total[0.0066] DEBUG: The ping_method variable is 2
Total[0.0067] DEBUG: The ping_retries variable is 1
Total[0.0069] DEBUG: The ping_timeout variable is 400
Total[0.0070] DEBUG: The snmp_retries variable is 0
Total[0.0071] DEBUG: The log_perror variable is 1
Total[0.0072] DEBUG: The log_pwarn variable is 1
Total[0.0073] DEBUG: The boost_redirect variable is 1
Total[0.0075] DEBUG: The boost_rrd_update_enable variable is 1
Total[0.0076] DEBUG: The log_pstats variable is 1
Total[0.0077] DEBUG: The threads variable is 4
Total[0.0078] DEBUG: The polling interval is 30 seconds
Total[0.0079] DEBUG: The number of concurrent processes is 1
Total[0.0080] DEBUG: The script timeout is 40
Total[0.0082] DEBUG: The selective_device_debug variable is
Total[0.0083] DEBUG: The spine_log_level variable is 0
Total[0.0084] DEBUG: The number of php script servers to run is 4
Total[0.0085] DEBUG: The number of active data source profiles is 1
Total[0.0086] DEBUG: The number of snmp ports on the system is 1
Total[0.0088] DEBUG: StartDevice='-1', EndDevice='-1', TotalPHPScripts='1'
Total[0.0088] DEBUG: The PHP Script Server is Required
Total[0.0089] DEBUG: The Maximum SNMP OID Get Size is 20
Total[0.0091] DEBUG: Total Connections made 1
Total[0.0092] DEBUG: Creating Local Connection Pool of 4 threads.
Total[0.0092] DEBUG: Creating Local Connection 0.
Total[0.0093] DEBUG: Total Connections made 2
Total[0.0093] DEBUG: Creating Local Connection 1.
Total[0.0095] DEBUG: Total Connections made 3
Total[0.0095] DEBUG: Creating Local Connection 2.
Total[0.0097] DEBUG: Total Connections made 4
Total[0.0097] DEBUG: Creating Local Connection 3.
Total[0.0099] DEBUG: Total Connections made 5
Total[0.0099] DEBUG: Version 1.2.20 starting
Total[0.0099] DEBUG: MySQL is Thread Safe!
Total[0.0099] DEBUG: Spine running as 0 UID, 0 EUID
Total[0.0099] DEBUG: Spine is running as root.
Total[0.0099] DEBUG: Spine has got ICMP
Total[0.0099] DEBUG: Initializing Net-SNMP API
Total[0.0100] DEBUG: Issues with SNMP Header Version information, assuming old version of Net-SNMP.
Total[0.0108] DEBUG: Initializing PHP Script Server(s)
Total[0.0109] DEBUG: SS[0] PHP Script Server Routine Starting
Total[0.0109] DEBUG: SS[0] PHP Script Server About to FORK Child Process
Total[0.0110] DEBUG: SS[0] PHP Script Server Child FORK Success
Total[0.1191] DEBUG: SS[0] Confirmed PHP Script Server running using readfd[11], writefd[10]
Total[0.1191] DEBUG: SS[1] PHP Script Server Routine Starting
Total[0.1191] DEBUG: SS[1] PHP Script Server About to FORK Child Process
Total[0.1229] DEBUG: SS[1] PHP Script Server Child FORK Success
Total[0.2210] DEBUG: SS[1] Confirmed PHP Script Server running using readfd[13], writefd[12]
Total[0.2211] DEBUG: SS[2] PHP Script Server Routine Starting
Total[0.2211] DEBUG: SS[2] PHP Script Server About to FORK Child Process
Total[0.2250] DEBUG: SS[2] PHP Script Server Child FORK Success
Total[0.3051] DEBUG: SS[2] Confirmed PHP Script Server running using readfd[15], writefd[14]
Total[0.3051] DEBUG: SS[3] PHP Script Server Routine Starting
Total[0.3051] DEBUG: SS[3] PHP Script Server About to FORK Child Process
Total[0.3053] DEBUG: SS[3] PHP Script Server Child FORK Success
Total[0.3808] DEBUG: SS[3] Confirmed PHP Script Server running using readfd[17], writefd[16]
Total[0.3816] Spine will support multithread device polling.
Total[0.3819] DEBUG: Initial Value of Available Threads is 4 (0 outstanding)
Total[0.3821] DEBUG: Valid Thread to be Created (140652607149824)
Total[0.3821] DEBUG: Available Threads is 3 (1 outstanding)
Total[0.3822] DEBUG: Device[0] HT[1] In Poller, About to Start Polling
Total[0.3823] DEBUG: Traversing Local Connection Pool for free connection.
Total[0.3823] DEBUG: Checking Local Pool ID 0.
Total[0.3823] DEBUG: Allocating Local Pool ID 0.
Total[0.3824] DEBUG: Valid Thread to be Created (140652528531200)
```

**Comment by densenator** [comment]
root@cacti:/usr/local/spine/bin# ./spine -R -V 5 -S
SPINE: Using spine config file [../etc/spine.conf]
Total[0.0042] DEBUG: The path_php_server variable is /var/www/html/cacti/script_server.php
Total[0.0043] DEBUG: The path_cactilog variable is /var/www/html/cacti/log/cacti.log
Total[0.0043] DEBUG: The version variable is 10.5.15-MariaDB-0+deb11u1
Total[0.0043] DEBUG: The log_destination variable is 4 (STDOUT)
Total[0.0044] DEBUG: The path_php variable is /usr/bin/php
Total[0.0046] DEBUG: The availability_method variable is 2
Total[0.0048] DEBUG: The ping_recovery_count variable is 3
Total[0.0049] DEBUG: The ping_failure_count variable is 2
Total[0.0051] DEBUG: The ping_method variable is 2
Total[0.0052] DEBUG: The ping_retries variable is 1
Total[0.0054] DEBUG: The ping_timeout variable is 3000
Total[0.0056] DEBUG: The snmp_retries variable is 3
Total[0.0058] DEBUG: The log_perror variable is 1
Total[0.0059] DEBUG: The log_pwarn variable is 0
Total[0.0061] DEBUG: The boost_redirect variable is 0
Total[0.0062] DEBUG: The boost_rrd_update_enable variable is 0
Total[0.0064] DEBUG: The log_pstats variable is 0
Total[0.0066] DEBUG: The threads variable is 1
Total[0.0068] DEBUG: The polling interval is 300 seconds
Total[0.0070] DEBUG: The number of concurrent processes is 3
Total[0.0071] DEBUG: The script timeout is 25
Total[0.0073] DEBUG: The selective_device_debug variable is
Total[0.0074] DEBUG: The spine_log_level variable is 0
Total[0.0076] DEBUG: The number of php script servers to run is 1
Total[0.0078] DEBUG: The number of active data source profiles is 1
Total[0.0079] DEBUG: The number of snmp ports on the system is 1
Total[0.0082] DEBUG: StartDevice='-1', EndDevice='-1', TotalPHPScripts='1'
Total[0.0082] DEBUG: The PHP Script Server is Required
Total[0.0083] DEBUG: The Maximum SNMP OID Get Size is 10
Total[0.0089] DEBUG: Total Connections made 1
Total[0.0089] DEBUG: Creating Local Connection Pool of 1 threads.
Total[0.0089] DEBUG: Creating Local Connection 0.
Total[0.0094] DEBUG: Total Connections made 2
Total[0.0095] DEBUG: Version 1.2.20 starting
Total[0.0095] DEBUG: MySQL is Thread Safe!
Total[0.0095] DEBUG: Spine running as 0 UID, 0 EUID
Total[0.0095] DEBUG: Spine is running as root.
Total[0.0095] DEBUG: Spine has got ICMP
Total[0.0095] DEBUG: Initializing Net-SNMP API
Total[0.0096] DEBUG: Issues with SNMP Header Version information, assuming old version of Net-SNMP.
Total[0.0102] DEBUG: Initializing PHP Script Server(s)
Total[0.0102] DEBUG: SS[0] PHP Script Server Routine Starting
Total[0.0102] DEBUG: SS[0] PHP Script Server About to FORK Child Process
Total[0.0105] DEBUG: SS[0] PHP Script Server Child FORK Success
Total[0.0934] DEBUG: SS[0] Confirmed PHP Script Server running using readfd[8], writefd[7]
Total[0.0950] Spine will support multithread device polling.
Total[0.0956] DEBUG: Initial Value of Available Threads is 1 (0 outstanding)
Total[0.0960] DEBUG: Valid Thread to be Created (140167488276224)
Total[0.0960] DEBUG: Available Threads is 0 (1 outstanding)
Total[0.0962] DEBUG: Device[0] HT[1] In Poller, About to Start Polling
Total[0.0964] DEBUG: Traversing Local Connection Pool for free connection.
Total[0.0964] DEBUG: Checking Local Pool ID 0.
Total[0.0965] DEBUG: Allocating Local Pool ID 0.
Total[0.0971] Device[0] HT[1] Total Time: 0.00086 Seconds
Total[0.0973] DEBUG: Freeing Local Pool ID 0
Total[0.0974] DEBUG: Device[0] HT[1] DEBUG: HOST COMPLETE: About to Exit Device Polling Thread Function
Total[0.1965] DEBUG: Valid Thread to be Created (140167488276224)
Total[0.1966] DEBUG: Available Threads is 0 (1 outstanding)
Total[0.1967] DEBUG: Device[4] HT[1] In Poller, About to Start Polling
Total[0.1967] DEBUG: Traversing Local Connection Pool for free connection.
Total[0.1969] DEBUG: Checking Local Pool ID 0.
Total[0.1969] DEBUG: Allocating Local Pool ID 0.
Total[0.1975] get_namebyhost(192.168.109.185) - Allocating name_t
Total[0.1976] get_namebyhost(192.168.109.185) - No delimiter, assume full hostname
Total[0.1978] Device[4] INFO: SNMP Device '192.168.109.185:161' has a timeout of 3000000 (3000), with 3 retries
Total[0.1979] Device[4] DEBUG: Entering SNMP Ping
Total[1.3281] Device[4] SNMP Result: Device responded to SNMP
Total[1.3281] Device[4] Checking for System Information Update
Total[1.3281] Device[4] Updating Full System Information Table
Total[2.9474] ERROR: Failed to get oid '.1.3.6.1.6.3.10.2.1.3.0' for Device[4] with Response[2]
Total[5.1155] DEBUG: Device[4] HT[1] RECACHE: Processing 1 items in the auto reindex cache for '192.168.109.185'
Total[5.6556] ERROR: Failed to get oid '.1.3.6.1.6.3.10.2.1.3.0' for Device[4] with Response[2]
Total[5.6556] Device[4] HT[1] DQ[4] Extended Uptime Result: , Is Numeric: 0
Total[6.1915] Device[4] HT[1] DQ[4] RECACHE OID: .1.3.6.1.2.1.1.3.0, (assert: 3305800 < output: 3308850)
Total[6.1924] Device[4] HT[1] NOTE: There are '6' Polling Items for this Device
Total[6.1924] Device[4] INFO: SNMP Device '192.168.109.185:161' has a timeout of 3000000 (3000), with 3 retries
Total[17.3994] Device[4] HT[1] DS[20] TT[11206.89] SS[0] SERVER: /var/www/html/cacti/scripts/ss_fping.php ss_fping '192.168.109.185' '20' 'ICMP' '', output: min:534.5860 avg:556.5240 max:657.7990 dev:28.4339 loss:0.0000
Total[17.9441] Device[4] HT[1] DS[17] TT[544.65] SNMP: v2: 192.168.109.185, dsname: uhp_d1_sn, oid: 1.3.6.1.4.1.8000.22.2.1.0, value: 98
Total[17.9442] Device[4] HT[1] DS[18] TT[544.71] SNMP: v2: 192.168.109.185, dsname: uhp_temp, oid: iso.3.6.1.4.1.8000.22.8.1.0, value: 46
Total[17.9442] Device[4] HT[1] DS[19] TT[544.72] SNMP: v2: 192.168.109.185, dsname: uhp_remote_state, oid: iso.3.6.1.4.1.8000.22.5.4.9.0, value: 3
Total[17.9442] Device[4] HT[1] DS[21] TT[544.73] SNMP: v2: 192.168.109.185, dsname: traffic_in, oid: .1.3.6.1.2.1.2.2.1.10.1, value: 40359533
Total[17.9442] Device[4] HT[1] DS[21] TT[544.74] SNMP: v2: 192.168.109.185, dsname: traffic_out, oid: .1.3.6.1.2.1.2.2.1.16.1, value: 852188254
Total[17.9442] DEBUG: Setting up writes to local database
Total[17.9443] Device[4] HT[1] Total Time: 18 Seconds
Total[17.9462] DEBUG: Freeing Local Pool ID 0
Total[17.9462] DEBUG: Device[4] HT[1] DEBUG: HOST COMPLETE: About to Exit Device Polling Thread Function
Total[18.0209] DEBUG: Valid Thread to be Created (140167488276224)
Total[18.0209] DEBUG: Available Threads is 0 (1 outstanding)
Total[18.0209] DEBUG: Device[5] HT[1] In Poller, About to Start Polling
Total[18.0210] DEBUG: Traversing Local Connection Pool for free connection.
Total[18.0210] DEBUG: Checking Local Pool ID 0.
Total[18.0210] DEBUG: Allocating Local Pool ID 0.
Total[18.0215] get_namebyhost(192.168.109.197) - Allocating name_t
Total[18.0215] get_namebyhost(192.168.109.197) - No delimiter, assume full hostname
Total[18.0216] Device[5] INFO: SNMP Device '192.168.109.197:161' has a timeout of 3000000 (3000), with 3 retries
Total[18.0216] Device[5] DEBUG: Entering SNMP Ping
Total[20.4574] Device[5] SNMP Result: Device responded to SNMP
Total[20.4574] Device[5] Checking for System Information Update
Total[20.4574] Device[5] Updating Full System Information Table
Total[30.2892] ERROR: Failed to get oid '.1.3.6.1.6.3.10.2.1.3.0' for Device[5] with Response[2]
Total[44.9783] DEBUG: Device[5] HT[1] RECACHE: Processing 1 items in the auto reindex cache for '192.168.109.197'
Total[50.3145] ERROR: Failed to get oid '.1.3.6.1.6.3.10.2.1.3.0' for Device[5] with Response[2]
Total[50.3145] Device[5] HT[1] DQ[4] Extended Uptime Result: , Is Numeric: 0
Total[54.9835] Device[5] HT[1] DQ[4] RECACHE OID: .1.3.6.1.2.1.1.3.0, (assert: 15102420 < output: 15113000)
Total[54.9842] Device[5] HT[1] NOTE: There are '6' Polling Items for this Device
Total[54.9842] Device[5] INFO: SNMP Device '192.168.109.197:161' has a timeout of 3000000 (3000), with 3 retries
Total[80.0094] WARNING: SS[0] The PHP Script Server did not respond in time and will therefore be restarted
Total[80.0094] DEBUG: SS[0] Script Server Shutdown Started
Total[80.0596] DEBUG: SS[0] PHP Script Server Routine Starting
Total[80.0597] DEBUG: SS[0] PHP Script Server About to FORK Child Process
Total[80.0600] DEBUG: SS[0] PHP Script Server Child FORK Success
Total[80.1415] DEBUG: SS[0] Confirmed PHP Script Server running using readfd[10], writefd[8]
Total[80.1416] Device[5] HT[1] DS[25] TT[25157.27] SS[0] SERVER: /var/www/html/cacti/scripts/ss_fping.php ss_fping '192.168.109.197' '20' 'ICMP' '', output: U
Total[81.4459] Device[5] HT[1] DS[22] TT[1304.32] SNMP: v2: 192.168.109.197, dsname: uhp_d1_sn, oid: 1.3.6.1.4.1.8000.22.2.1.0, value: 147
Total[81.4460] Device[5] HT[1] DS[23] TT[1304.37] SNMP: v2: 192.168.109.197, dsname: uhp_temp, oid: iso.3.6.1.4.1.8000.22.8.1.0, value: 33
Total[81.4460] Device[5] HT[1] DS[24] TT[1304.38] SNMP: v2: 192.168.109.197, dsname: uhp_remote_state, oid: iso.3.6.1.4.1.8000.22.5.4.9.0, value: 3
Total[81.4460] Device[5] HT[1] DS[26] TT[1304.39] SNMP: v2: 192.168.109.197, dsname: traffic_in, oid: .1.3.6.1.2.1.2.2.1.10.1, value: 2249915738
Total[81.4460] Device[5] HT[1] DS[26] TT[1304.40] SNMP: v2: 192.168.109.197, dsname: traffic_out, oid: .1.3.6.1.2.1.2.2.1.16.1, value: 2142568185
Total[81.4461] DEBUG: Setting up writes to local database
Total[81.4461] Device[5] HT[1] Total Time: 63 Seconds
Total[81.4477] DEBUG: Freeing Local Pool ID 0
Total[81.4477] DEBUG: Device[5] HT[1] DEBUG: HOST COMPLETE: About to Exit Device Polling Thread Function
Total[81.4980] DEBUG: Valid Thread to be Created (140167488276224)
Total[81.4980] DEBUG: Available Threads is 0 (1 outstanding)
Total[81.4981] DEBUG: Device[17] HT[1] In Poller, About to Start Polling
Total[81.4982] DEBUG: Traversing Local Connection Pool for free connection.
Total[81.4982] DEBUG: Checking Local Pool ID 0.
Total[81.4983] DEBUG: Allocating Local Pool ID 0.
Total[81.4990] get_namebyhost(192.168.109.155) - Allocating name_t
Total[81.4990] get_namebyhost(192.168.109.155) - No delimiter, assume full hostname
Total[81.4991] Device[17] INFO: SNMP Device '192.168.109.155:161' has a timeout of 3000000 (3000), with 3 retries
Total[81.4992] Device[17] DEBUG: Entering SNMP Ping
Total[82.0333] Device[17] SNMP Result: Device responded to SNMP
Total[82.0334] Device[17] Checking for System Information Update
Total[82.0334] Device[17] Updating Full System Information Table
Total[83.6725] ERROR: Failed to get oid '.1.3.6.1.6.3.10.2.1.3.0' for Device[17] with Response[2]
Total[85.8162] DEBUG: Device[17] HT[1] RECACHE: Processing 1 items in the auto reindex cache for '192.168.109.155'
Total[86.3560] ERROR: Failed to get oid '.1.3.6.1.6.3.10.2.1.3.0' for Device[17] with Response[2]
Total[86.3560] Device[17] HT[1] DQ[4] Extended Uptime Result: , Is Numeric: 0
Total[86.8889] Device[17] HT[1] DQ[4] RECACHE OID: .1.3.6.1.2.1.1.3.0, (assert: 11428170 < output: 11437480)
Total[86.8896] Device[17] HT[1] NOTE: There are '6' Polling Items for this Device
Total[86.8896] Device[17] INFO: SNMP Device '192.168.109.155:161' has a timeout of 3000000 (3000), with 3 retries
^CFATAL: Spine Interrupted by Console Operator
Total[87.7691] Device[17] HT[1] DS[106] TT[879.37] SS[0] SERVER: /var/www/html/cacti/scripts/ss_fping.php ss_fping '192.168.109.155' '20' 'ICMP' '', output: U
Total[88.3018] Device[17] HT[1] DS[103] TT[532.70] SNMP: v2: 192.168.109.155, dsname: uhp_d1_sn, oid: 1.3.6.1.4.1.8000.22.2.1.0, value: 98
Total[88.3019] Device[17] HT[1] DS[104] TT[532.74] SNMP: v2: 192.168.109.155, dsname: uhp_temp, oid: iso.3.6.1.4.1.8000.22.8.1.0, value: 54
Total[88.3019] Device[17] HT[1] DS[105] TT[532.76] SNMP: v2: 192.168.109.155, dsname: uhp_remote_state, oid: iso.3.6.1.4.1.8000.22.5.4.9.0, value: 3
Total[88.3019] Device[17] HT[1] DS[107] TT[532.76] SNMP: v2: 192.168.109.155, dsname: traffic_in, oid: .1.3.6.1.2.1.2.2.1.10.1, value: 2760430026
Total[88.3019] Device[17] HT[1] DS[107] TT[532.77] SNMP: v2: 192.168.109.155, dsname: traffic_out, oid: .1.3.6.1.2.1.2.2.1.16.1, value: 37201700
Total[88.3020] DEBUG: Setting up writes to local database
Total[88.3020] Device[17] HT[1] Total Time: 6.8 Seconds
Total[88.3036] DEBUG: Freeing Local Pool ID 0
Total[88.3036] DEBUG: Device[17] HT[1] DEBUG: HOST COMPLETE: About to Exit Device Polling Thread Function
Total[88.3690] DEBUG: Valid Thread to be Created (140167488276224)
Total[88.3691] DEBUG: Available Threads is 0 (1 outstanding)
Total[88.3691] DEBUG: Device[23] HT[1] In Poller, About to Start Polling
Total[88.3691] DEBUG: Traversing Local Connection Pool for free connection.
Total[88.3692] DEBUG: Checking Local Pool ID 0.
Total[88.3692] DEBUG: Allocating Local Pool ID 0.
Total[88.3696] get_namebyhost(192.168.109.224) - Allocating name_t
Total[88.3697] get_namebyhost(192.168.109.224) - No delimiter, assume full hostname
Total[88.3697] Device[23] INFO: SNMP Device '192.168.109.224:161' has a timeout of 3000000 (3000), with 3 retries
Total[88.3698] Device[23] DEBUG: Entering SNMP Ping
Total[88.9089] Device[23] SNMP Result: Device responded to SNMP
Total[88.9089] Device[23] Checking for System Information Update
Total[88.9090] Device[23] Updating Full System Information Table
Total[90.6713] ERROR: Failed to get oid '.1.3.6.1.6.3.10.2.1.3.0' for Device[23] with Response[2]
^C

**Comment by TheWitness** [comment]
You should research this:

```
Total[80.1416] Device[5] HT[1] DS[25] TT[25157.27] SS[0] SERVER: /var/www/html/cacti/scripts/ss_fping.php ss_fping '192.168.109.197' '20' 'ICMP' '', output: U
```

Two things with it:

1) The response is 'U', which means it was unable to get data. 
2) It's timing out after 25 seconds.

The second bit is that you have not configured more than one thread.  Best to do that, and more than one script server.  Threads are under `Console > Data Collection > Data Collector > Edit`, Script servers under `Console > Configuration > Settings > Poller`.  I am concerned the ss_fping.php is not working.  You should run ss_fping.php by hand and see what is wrong.  What OS is this?  Do you have ping installed?

**Comment by TheWitness** [comment]
In order for the ss_fping to work, you may have to reduce the pings to something like 5 or 10 from 20.  Here is how you test it.

```bash
[root@vmhost3 cacti]# php -q script_server.php
PHP Script Server has Started - Parent is cmd
/var/www/html/cacti/scripts/ss_fping.php ss_fping '192.168.11.195' '20' 'ICMP' ''
min:0.3410 avg:0.4350 max:0.4880 dev:0.0363 loss:0.0000
```

**Comment by TheWitness** [comment]
I'm closing this, but we can always continue the conversation.
