### ISSUE TITLE
Huge amount of queries

### ISSUE THREAD

**Issue by reboot1983** [Cacti/cacti#467]
Running cacti 1.1.0 on my Raspberry Pi 3b:

When activating the MySQL general_log setting in the my.cnf and requesting the following url:
http://192.168.1.3/cacti/graph_view.php?action=get_node&tree_id=0&id=%23

This is an ajax request for requesting the main tree node in de graphs tab of cacti. 

I get a huge amount of queries listed in the log. A lot of the queries are the same and are requesting the same variables in de settings table. Also there are queries querying primary keys with value 0 (zero).

I've attached the mysql.txt (see section 85 for all the queries executed for requesting this URL).
[mysql.txt](https://github.com/Cacti/cacti/files/862735/mysql.txt)

Maybe it's possible to cache requested settings in a class (or collect all settings from the table in a static class and ask the class for the value of the specific setting). This should generate a lot less traffic with the MySQL server.

**Comment by cigamit** [comment]
This is mainly calls to the settings table, which is odd.  We already are supposed to cache those entries.  I'll take a look and see what's up.

**Comment by cigamit** [comment]
Just out of curiosity, are you doing those calls as the guest account, or some other account?

**Comment by cigamit** [comment]
Pull the latest lib/functions.php and let us know how it was reduced.

**Comment by reboot1983** [comment]
I was calling as user_id = 1 (admin); I will pull lib/functions.php and check if it has been solved.

**Comment by reboot1983** [comment]
Maybe... just not yet ok.
I just clicked the clog tab and this resulted in a http500 error. 

From the cacti.log:
```
2017-03-23 15:32:14 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4303 cacti_debug_backtrace)
2017-03-23 15:32:14 - ERROR PHP ERROR: Call to undefined function set_page_refresh() in file: /var/www/html/cacti/lib/clog_webapi.php on line: 110
```

**Comment by cigamit** [comment]
Okay, closing this.  Moving on.  Looking forward to that pull request.  The lib/auth.php is a beast.  Please be careful.
