### ISSUE TITLE
New templates are not installed during the update

### ISSUE THREAD

**Issue by xmacan** [Cacti/cacti#4682]
I don't know if the existing templates have been updated. But the new ones are not being installed.

No warning nor error in log.

**Comment by TheWitness** [comment]
@netniV, can you work on this one?

**Comment by netniV** [comment]
@xmacan do you have a detailed install-complete.log that shows this?

**Comment by netniV** [comment]
Also, can you run a query for:
```sql
SELECT * FROM settings WHERE name like 'install_template_%';
```

**Comment by xmacan** [comment]
root@localhost [cacti]> select * from settings where name like 'install_template_%';
Empty set (0.001 sec)

**Comment by netniV** [comment]
See, that would mirror what your log says "Nothing was selected".

**Comment by xmacan** [comment]
I tried update two installations and I selected at least one template on each installation.

**Comment by netniV** [comment]
OK, I will have to test that out then.

**Comment by TheWitness** [comment]
Okay, I have resolved this, but I'm going to open a new ticket as the user should have options that we have on the Package Install page when it comes to upgrades.
