### ISSUE TITLE
Cacti Packages corrupted with release of Cacti 1.2.20

### ISSUE THREAD

**Issue by sbbbv** [Cacti/cacti#4685]
Fresh install Debian 11.3 and Cacti Release 1.2.20.
Everything installed from Debian packages except Cacti.

PHP 7.4.28
MariaDB 10.5.15

Templates are not installed correctly with errors in the logs like:
"2022-04-08 13:41:58 - CMDPHP Import Error: Import found an invalid dependency hash of :24146b2a8b037c29d8c5d7f1f06a6ce9. Please open bug on GitHub.
2022-04-08 13:41:58 - 4 Import Error: inserting into snmp_query_graph_rrd"
![Clipboard02](https://user-images.githubusercontent.com/103254279/162422536-b9679431-b7ce-466c-98a6-368f34e6ac53.jpg)
![Clipboard04](https://user-images.githubusercontent.com/103254279/162422560-53285a25-23c1-4fb1-b8f8-1d79b980869c.jpg)
[cacti.log](https://github.com/Cacti/cacti/files/8451212/cacti.log)
[install-complete.log](https://github.com/Cacti/cacti/files/8451213/install-complete.log)
[install-general.log](https://github.com/Cacti/cacti/files/8451214/install-general.log)

**Comment by TheWitness** [comment]
This is a bit of a nasty bug.  Looking into it now.

**Comment by paulgevers** [comment]
I think I'm seeing the result of this too in my attempt to package 1.2.20. For me, the package fails to install because during install ir run
```
        su --shell /bin/sh www-data -c "/usr/share/cacti/cli/import_package.php \
            --filename=/usr/share/cacti/site/install/templates/Local_Linux_Machine.xml.gz" > /dev/null
```
which fails with
```
PHP Fatal error:  Uncaught TypeError: array_search(): Argument #2 ($haystack) must be of type array, string given in /usr/share/cacti/site/lib/import.php:2217
Stack trace:
#0 /usr/share/cacti/site/lib/import.php(2217): array_search()
#1 /usr/share/cacti/cli/import_package.php(144): import_display_results()
#2 {main}
  thrown in /usr/share/cacti/site/lib/import.php on line 2217
```

**Comment by netniV** [comment]
That has been patched already as of today.  See https://github.com/Cacti/cacti/pull/4695

**Comment by sbbbv** [comment]
> That has been patched already as of today. See #4695

I just downloaded the latest Cacti-1.2.x. Same thing as in the first post

"2022-04-12 09:38:12 - CMDPHP Import Error: Import found an invalid dependency hash of :24146b2a8b037c29d8c5d7f1f06a6ce9. Please open bug on GitHub."

**Comment by TheWitness** [comment]
Yea, the other fix does not address the corruption.  I created a pull request to fix, but need to redo it since the repo was not properly rebased prior to commit.  Should be done later today.

**Comment by TheWitness** [comment]
This has been resolved now.  I would simply pull a fresh version of the 1.2.x branch and hit the reset button.

**Comment by TheWitness** [comment]
We are going to rework the packages one more time this weekend.
