### ISSUE TITLE
Package Import generates errors when you try to import directory or non-file

### ISSUE THREAD

**Issue by densenator** [Cacti/cacti#4689]
# Describe the bug
<html>
<body>

09.Apr.2022 12:06:59 - IMPORT FATAL: Unable to read Cacti Package compress.zlib:///var/www/html/cacti/plugins/mikrotik/templates/
--
09.Apr.2022 12:06:59 - CMDPHP PHP ERROR NOTICE Backtrace: (/cli/import_package.php[133]:fread(), CactiErrorHandler())
09.Apr.2022 12:06:59 - ERROR PHP NOTICE: fread(): read of 8192 bytes failed with errno=21 Is a directory in file: /var/www/html/cacti/cli/import_package.php on line: 133

</body>
</html>
## To Reproduce

1. Use cli script for import template
2. Choose wrong file
3. See error

**Comment by TheWitness** [comment]
This should be fixed pretty soon.  Just waiting on a code review.

**Comment by TheWitness** [comment]
Pull down a fresh copy of `import_package.php` and see if you can break it now.

**Comment by densenator** [comment]
resolved
