### ISSUE TITLE
Feature Request: Change re-index method of Data Query

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#469]
I would like to be able to change the re-index method of an existing data query without removing it and re-adding it. In reality I need to do this across about 100 devices and 500 data queries so a "bulk" function would be very useful.

**Comment by eschoeller** [comment]
Additionally ... if multiple data queries on the same device are using the same "Uptime goes backward" re-index method ... why not poll sysUpTimeInstance just once for the device instead of once for each data query?

**Comment by cigamit** [comment]
Good point on the second point.  I'm trying to figure out a way to do this without making the interface look too wonky.  At the moment, simply thinking.  It's simple, and complicated at the same time.

**Comment by eschoeller** [comment]
I know exactly what you mean!

**Comment by cigamit** [comment]
I gave this quite a bit of thought over copious amounts of alcohol tonight.  I have an idea.  Sit tight.

**Comment by cigamit** [comment]
Resolved, thanks.  Looks pretty good.
