### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by densenator** [Cacti/cacti#4697]
# Describe the bug

If i tried to use wrong password, i don't see error of this in login page.

If i logged succefully, i always see in log file:

AUTH LOGIN FAILED: Domains LDAP Login Failed for user 'user' from IP Address 'my.ip'.
And then 
AUTH LOGIN: User 'user' authenticated

Why it's always trying to use LDAP?, my Authentication Method is Bultin. And for user too.

**Comment by bmfmancini** [comment]
Is this happening on all logins ?
I'm not seeing this on my end

**Comment by densenator** [comment]
Yes, I'm creating new user, and view the same.
How do i get more logs?
<html>
<body>


12.Apr.2022 15:43:57 - AUTH LOGIN: User 'user2' authenticated
--
12.Apr.2022 15:43:45 - AUTH LOGIN FAILED: Domains LDAP Login Failed for user 'user2' from IP Address 'ip'.
12.Apr.2022 15:43:37 - AUTH LOGIN FAILED: Domains LDAP Login Failed for user 'user2' from IP Address 'ip'.
12.Apr.2022 15:43:37 - AUTH LOGIN FAILED: No password provided for user user2
![image](https://user-images.githubusercontent.com/18443709/162965755-d293c9e8-cd07-4204-830d-eb9d83d1704e.png)
![image](https://user-images.githubusercontent.com/18443709/162965851-07bb09fe-98c8-4115-bf99-a22ce54839fd.png)


</body>
</html>

**Comment by TheWitness** [comment]
Enable the LDAP log on the Authentication page.  Let us know what you find.

**Comment by TheWitness** [comment]
This may also be solved with the latest 1.2.x as of a few minutes ago.  Update `auth_login.php` and `lib/auth.php` and let us know.

**Comment by densenator** [comment]
solved
