### ISSUE TITLE
Create new device error

### ISSUE THREAD

**Issue by densenator** [Cacti/cacti#4698]
# Describe the bug
After creating new device i always get error
"Remote Poller 0 is Down, you will need to perform a FullSync once it up again."

I don't have remote pollers. How fix that?
![Screenshot_1](https://user-images.githubusercontent.com/18443709/162938073-86ce4b12-0a66-4022-811e-1b3baa04836f.png)
![Screenshot_2](https://user-images.githubusercontent.com/18443709/162938099-f279530b-6fa1-49c2-aec8-45703bf7700f.png)
![Screenshot_3](https://user-images.githubusercontent.com/18443709/162938110-365dc846-3670-4ddb-ab8f-0a6ce00cb1e9.png)
![Screenshot_4](https://user-images.githubusercontent.com/18443709/162938118-0e1f9c27-8f49-4396-b63e-a9f0f22558ef.png)

**Comment by bmfmancini** [comment]
Yea I'm seeing the same thing ..weird I hadn't seen this in testing

**Comment by TheWitness** [comment]
Yea, I just saw it too, and was like WTF.

**Comment by TheWitness** [comment]
Thanks for reporting.  Last minute changes never go well.

**Comment by TheWitness** [comment]
Resolved here.
https://github.com/Cacti/cacti/pull/4702
