### ISSUE TITLE
Cacti can't get value from python scripts

### ISSUE THREAD

**Issue by manhvu1997** [Cacti/cacti#4706]
# Describe the bug

I installed cacti 1.2.20 on ubuntu 20.04 and wrote some python scripts to get data from network device. When I check log file of cacti, the result of script is "Empty result[]..". However, when I directly ran python script on server, the result of script is ok.
**Log on cacti:**
![ảnh](https://user-images.githubusercontent.com/58839875/163094876-1a0aea8d-3959-44f3-8c85-3d3ca039f432.png)
ERROR: Empty result [172.27.16.68]: 'python3 /var/www/html/cacti/scripts/check_ftel_ivoice_cc_ram.py 'FPTHCM123' '172.27.16.68'' 

Run directly on server:
![ảnh](https://user-images.githubusercontent.com/58839875/163095006-5bdcf7b8-1777-43f9-9b8c-e145ce8522e7.png)

Can you help me to fix the error that cacti response empty result when run the python scripts ?
## To Reproduce

I tried to permissioned the scripts folder to www.data:www.data and chmod +x for them, but the result was still Empty...

**Comment by netniV** [comment]
Have you run the verbose query when editing the device?

**Comment by TheWitness** [comment]
You should try to run as the apache/www-run account and see if that makes a difference.

**Comment by TheWitness** [comment]
Also, is this `spine` of `cmd.php`?

**Comment by TheWitness** [comment]
With spine, you **may** have to provide the full path to python3.

**Comment by manhvu1997** [comment]
Thank for your reply
I found the problem and fixed that. The result of python was empty because the library python not apply for all user, I uninstall library and reinstall in all user, so the result is same when I run directly command on server

**Comment by manhvu1997** [comment]
Close the issue!!!
