### ISSUE TITLE
SQL Save on table 'graph_templates_item': Column 'data_template_id' does not exist

### ISSUE THREAD

**Issue by sbbbv** [Cacti/cacti#4707]
Fresh install Debian 11.3 and Cacti 1.2.x branch downloaded 30 min ago.
Everything installed from Debian packages except Cacti.

PHP 7.4.28
MariaDB 10.5.15

Duplicating graph template broked with message like "SQL Save on table 'graph_templates_item': Column 'data_template_id' does not exist, unable to save!" error.

![Clipboard02](https://user-images.githubusercontent.com/103254279/163117126-886cc996-a1b3-4806-ba4c-cdf68d25029d.jpg)
![Clipboard04](https://user-images.githubusercontent.com/103254279/163117141-2bfdcc45-8e60-4aa7-a3f6-e6cda7cbe23e.jpg)
![Clipboard05](https://user-images.githubusercontent.com/103254279/163117150-76ae746a-fbf3-4de3-abe8-0c55492cd889.jpg)

**Comment by TheWitness** [comment]
This is resolved now.  Just grab 1.2.x.
