### ISSUE TITLE
ERROR PHP NOTICE: Undefined offset: 1 in file: cacti/lib/dsstats.php  on line: 259

### ISSUE THREAD

**Issue by amrit3327** [Cacti/cacti#471]
Permissions are fine...cron for poller is running and spine is running data is also there in tables...but what else i need to chek...

**Comment by cigamit** [comment]
So, you have your RRDfiles updating now.  Please confirm.

**Comment by amrit3327** [comment]
No cigamit..i am getting this error ..

**Comment by amrit3327** [comment]
can i increase the time from 209 sec for poller i think rrd step is at the last in poller.php or it is in loop for every data source process..because it always show 0 rrd processed after each poller run ..

**Comment by amrit3327** [comment]
[poller.txt](https://github.com/Cacti/cacti/files/866758/poller.txt)

Attached are the poller logs

**Comment by cigamit** [comment]
You need to do something about your error handling.  Lot's of issues.  Looks like you are running boost.  Are you seeing boost clearing out the tables?  Were you running boost server before, as it's not available any more.  Please advise.  Also, I think this belongs on the forums.  You can get better help there I think.

**Comment by cigamit** [comment]
It's really unclear how that error can happen.  Can you please place the following into the code at that line:

if (!isset($parts[1])) cacti_log("info $rrdfile");

Then, from the log, take the output of the "rrdtool info $rrdfile" and post it here.

**Comment by amrit3327** [comment]
2017-03-24 12:40:22 - CMDPHP PHP ERROR NOTICE Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4304 CactiErrorHandler)(/lib/functions.php: 4265 cacti_debug_backtrace)
2017-03-24 12:40:22 - ERROR PHP NOTICE: Undefined variable: rrdfile in file: /u/cacti/lib/functions.php on line: 4304

After adding this is what i am getting ..

**Comment by amrit3327** [comment]
i have one more concern is rrd,php used in poller,php as i dont see poller,php using rrd.php in my case....which may be reason for rrd not updating  as well

**Comment by cigamit** [comment]
Well, you need to learn a little more about PHP if you expect help here.  Until you know what you are doing, it's going to be hard to identify a bug if any.

**Comment by amrit3327** [comment]
yes i am stranger to php but as we are using cacti so can u help me to figure put whyy rrd is not updating whcih as a system admin is hurting us from last3 weeks..which may lead to cacti decommission which actually i dont want ...i am trying my best in spite i am not a programmer..

**Comment by cigamit** [comment]
Well, since you are unable to perform the simplest task in PHP, I recommend you execute your backoff plan and return to the previous version of cacti.  First, you need to restore the original website files, then restore from your database backup.  The rrdfiles should start updating all by themselves after that.  If you have not properly planned your upgrade, don't have these files, then, it's not the fault of anyone here.  A lack of planning on your part does not constitute and emergency on ours.  I wish you luck.
