### ISSUE TITLE
Double dublicate Data Queries when duplicate Graph Templates

### ISSUE THREAD

**Issue by sbbbv** [Cacti/cacti#4715]
Fresh install Debian 11.3 and Cacti 1.2.x branch downloaded 30 min ago.
Everything installed from Debian packages except Cacti.

PHP 7.4.28
MariaDB 10.5.15

Double dublicate Data Queries with wrong name and content inside when duplicate Graph Templates.

Just duplicate "Interface - Traffic (bits/sec, BW)" with untoched default name "<template_title> (1)" and go to "Data Queries -> SNMP - Interface Statistics" .

![Clipboard02](https://user-images.githubusercontent.com/103254279/163315485-e24bc5bf-f3b7-4220-84c5-5dc54bd281ed.jpg)
![Clipboard02](https://user-images.githubusercontent.com/103254279/163337411-c77937fb-e78f-4a28-9e88-c3ec1f7164f3.jpg)

1. Double "Interface - Traffic (bits/sec, BW) (1)" after duplicate Graph Templates.
2. Double "[In/Out Bits (64-bit)" and "TECLinkStatus (1)" as default name and  after install.
I think its mistake.

![Clipboard05](https://user-images.githubusercontent.com/103254279/163314416-6797eea0-3212-47ad-bf3f-1ca89656c926.jpg)

First.

![Clipboard07](https://user-images.githubusercontent.com/103254279/163314430-e2406dae-6a0e-4ed9-a451-8be1a8a5eec9.jpg)

And second.

**Comment by TheWitness** [comment]
Tell me how you got to this point?  What I mean is the history of the system, when installed, etc.

**Comment by sbbbv** [comment]
It's a new installation Debian from iso and Cacti from 1.2.x branch downloaded in the morning 14Apr.
1. Unzip new arch to web. Set permisssons.
2. "Drop database cacti", "create database cacti" and etc on mariadb. "Mysql cacti < cacti.sql" from new arch.
3.  Install Cacti from web interface with all template. 
4.  Immediately after installation go to Graph Templates and duplicate template named "Interface - Traffic (bits/sec, BW)"
5.  Go to "Data Queries - SNMP Interface Statistics"
6. You can see the result in the screenshots above.

**Comment by TheWitness** [comment]
Okay thanks!  Adding @bmfmancini as he is doing the cleanup.  We will push new packages likely in the next day or so.  It advisable to the reset button afterwards and reinstall from scratch.

**Comment by TheWitness** [comment]
@sbbbv, we are working on it.  We've already published the new Packages, but they were messed up too.  So, we've introduced some things to cleanup much of the mess.  Update in a day or so after I finish testing.

**Comment by TheWitness** [comment]
In the mean time, you may delete the duplicated Data Query Graphs.  The rest will cleanup after we've testing things out.  Delete the ones with the higher ID is your best bet.

**Comment by TheWitness** [comment]
Related to #4682.  Closing as Duplicated.
