### ISSUE TITLE
check_cli_version.sh fails on files with Windows line endings (CRLF)

### ISSUE THREAD

**Issue by paulgevers** [Cacti/cacti#4717]
# Describe the bug

Running `tests/tools/check_cli_version.sh` on Cacti 1.2.20 fails on `cli/remove_broken_graphs.php` because contrary to nearly all other files in the `cli` directory, those files have Windows line endings. I suggest converting all files to LF line endings, but otherwise the check should be made robust.

## Expected behavior

Running `check_cli_version.sh` should pass

## Additional context

It's not the only file, but the other one fails for a missing header, but that was fixed yesterday.

**Comment by netniV** [comment]
Hi Paul,

I'm going to close this pull request as I'm already working on CI stuff that actually has an update to this routine. 

I'll be committing over the bank holiday weekend. 

Mark
