### ISSUE TITLE
Schema change suggestion

### ISSUE THREAD

**Issue by reboot1983** [Cacti/cacti#472]
While I was investigating some slowness on my Raspberry Pi, I noticed the huge amount of queries needed for Cacti (reported in #467). While investigating some of these queries I came up with some schema changes for the Cacti database. These changes solve some temporary tables and table scans which mainly speed up some tree queries.

```
ALTER TABLE `graph_templates_item` DROP KEY `local_graph_id`, ADD KEY `local_graph_id_sequence` (`local_graph_id`,`sequence`);
ALTER TABLE `graph_tree_items` DROP KEY `parent`, ADD KEY `parent_position` (`parent`,`position`);
```

**Comment by cigamit** [comment]
Resolved, thanks!
