### ISSUE TITLE
CMDPHP ERROR: A DB Row Failed  after update cacti 1.2.14 -> 1.2.20

### ISSUE THREAD

**Issue by ISekan** [Cacti/cacti#4727]
Centos7
MariaDB 10.2.33
PHP 7.3.22

Cacti works fine after update but file with CMDPHP ERROR errors grows up to 1G per day

19-Apr-2022 08:17:08 - CMDPHP ERROR: A DB Exec Failed!, Error: PDOStatement::execute(): send of 89 bytes failed with errno=32 Broken pipe
19-Apr-2022 08:17:08 - CMDPHP ERROR: A DB Row Failed!, Error: MySQL server has gone away
19-Apr-2022 08:17:08 - CMDPHP ERROR: A DB Row Failed!, Error: MySQL server has gone away
19-Apr-2022 08:17:08 - CMDPHP ERROR: A DB Row Failed!, Error: MySQL server has gone away
19-Apr-2022 08:17:08 - CMDPHP ERROR: A DB Row Failed!, Error: MySQL server has gone away

**Comment by netniV** [comment]
Sounds like a problem with MySQL rather than Cacti. I would check your MySQL logs

**Comment by ISekan** [comment]
attached
[log.zip](https://github.com/Cacti/cacti/files/8510846/log.zip)

**Comment by TheWitness** [comment]
It's likely you are eclipsing the max_connections;

```sql
SHOW GLOBAL VARIABLES LIKE 'max_connections';
SHOW GLOBAL STATUS LIKE 'max_used_connections';
```

**Comment by TheWitness** [comment]
Spine 1.2.x will allocate and entire pool of threads on boot time, which is different than before.  So, if you have madlad thread and process settings, you are going to run your database clear out of connections.

**Comment by ISekan** [comment]
It was:
| max_connections | 120   |
| Max_used_connections | 74    |

Chanded to
| max_connections | 200   |
| Max_used_connections | 45    |

But, still
20-Apr-2022 09:11:52 - CMDPHP ERROR: A DB Exec Failed!, Error: PDOStatement::execute(): send of 89 bytes failed with errno=32 Broken pipe
20-Apr-2022 09:11:52 - CMDPHP ERROR: A DB Row Failed!, Error: MySQL server has gone away
20-Apr-2022 09:11:52 - CMDPHP ERROR: A DB Row Failed!, Error: MySQL server has gone away
20-Apr-2022 09:11:52 - CMDPHP ERROR: A DB Row Failed!, Error: MySQL server has gone away
20-Apr-2022 09:11:52 - CMDPHP ERROR: A DB Row Failed!, Error: MySQL server has gone away
20-Apr-2022 09:11:52 - CMDPHP ERROR: A DB Row Failed!, Error: MySQL server has gone away
20-Apr-2022 09:11:52 - CMDPHP ERROR: A DB Row Failed!, Error: MySQL server has gone away

**Comment by TheWitness** [comment]
You may need to review your mariadb log file, check for a full file system.  This is likely not a Cacti issue.

**Comment by netniV** [comment]
When reviewing your MySQL/MariaDB logs, be sure to look at the older ones too because often they will recycle them on startup so your current one is just for the active service.  To see why it went away, you'd have to look at the previous log.

**Comment by ISekan** [comment]
Tried to drop and create a new DB cacti. No changes. Fresh logs after reboot server:
[logs.zip](https://github.com/Cacti/cacti/files/8523598/logs.zip)

**Comment by netniV** [comment]
Your version of spine should be the same as the version of cacti you are running.

**Comment by ISekan** [comment]
the same problem on cacti 1.2.21

31-May-2022 04:27:50 - POLLER: Poller[1] PID[98455] WARNING: There are 2 Data Sources not returning all data leaving rows in the poller output table.  Details to follow.
31-May-2022 04:27:50 - POLLER: Poller[1] PID[98455] WARNING: Data Template 'Interface - Traffic' is impacted by lack of complete information
31-May-2022 04:27:50 - SYSTEM STATS: Time:48.8446 Method:spine Processes:1 Threads:13 Hosts:398 HostsPerProcess:398 DataSources:40100 RRDsProcessed:0
31-May-2022 04:28:18 - SYSTEM BOOST STATS: Time:86.73 ProcessNumber:2 RRDUpdates:439216
31-May-2022 04:28:28 - SYSTEM BOOST STATS: Time:96.80 ProcessNumber:1 RRDUpdates:425454
31-May-2022 04:28:29 - SYSTEM BOOST STATS: Time:98.22 RRDUpdates:864670
31-May-2022 04:28:53 - CMDPHP ERROR: A DB Exec Failed!, Error: PDOStatement::execute(): send of 89 bytes failed with errno=32 Broken pipe
31-May-2022 04:28:53 - CMDPHP ERROR: A DB Row Failed!, Error: MySQL server has gone away
31-May-2022 04:28:53 - CMDPHP ERROR: A DB Row Failed!, Error: MySQL server has gone away
31-May-2022 04:28:53 - CMDPHP ERROR: A DB Row Failed!, Error: MySQL server has gone away
31-May-2022 04:28:53 - CMDPHP ERROR: A DB Row Failed!, Error: MySQL server has gone away
31-May-2022 04:28:53 - CMDPHP ERROR: A DB Row Failed!, Error: MySQL server has gone away
31-May-2022 04:28:53 - CMDPHP ERROR: A DB Row Failed!, Error: MySQL server has gone away
31-May-2022 04:28:53 - CMDPHP ERROR: A DB Row Failed!, Error: MySQL server has gone away
31-May-2022 04:28:53 - CMDPHP ERROR: A DB Row Failed!, Error: MySQL server has gone away
