### ISSUE TITLE
Cacti Template and Package Installs need a way to deal with conflicting Suggested Name Values/Patterns

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#4729]
# Describe the bug

Due to corrupted packages, new installs, and possibly upgrades can have their templates corrupted with invalid data.  A way to clean up this issue needs to be created.

## Remediation Plan

Add a new option to replace suggested values in the Cacti install with revised patterns in the Templates.

**Comment by netniV** [comment]
c99d9365a is the commit for this.

**Comment by TheWitness** [comment]
The has been resolved through a new parameter to replace all suggested values.  This parameter, now available through the CLI will allow people negatively impacted by the 1.2.20 Package errors to resolve them.
