### ISSUE TITLE
SQL_CALC_FOUND_ROWS instead of two queries

### ISSUE THREAD

**Issue by reboot1983** [Cacti/cacti#473]
While examining the queries of #467, I found several queries executed multiple times. First for the result and the second time for the number of results. This can also be determined by using mysql_fetch_row(), mysqli_fetch_row() or PDO's equivalent. But since there are basic functions implemented in the Cacti code to fetch DB results I might suggest the usage of SQL_CALC_FOUND_ROWS in the primary query and SELECT FOUND_ROWS() in the second query to fetch the number of results. This way MySQL executes the query once. The follow-up query is: 'SELECT FOUND_ROWS()' and will result only one cell with the number of results in it. I think this might be easy to implement and more efficient. 

1. If you search for 'as rower' in Lib/auth.php (6 results, 1 might be unable to be changed)
2. If you search for 'SELECT DISTINCT id' in Lib/auth.php (2 results)
  -- also; both queries can we rewritten to be a bit lighter:
```
Example query:
SELECT SQL_CALC_FOUND_ROWS h1.*   
FROM host AS h1   
INNER JOIN (    
	SELECT DISTINCT h.id
	FROM host AS h     
	LEFT JOIN graph_local AS gl      ON h.id=gl.host_id      
	LEFT JOIN graph_templates_graph AS gtg      ON gl.id=gtg.local_graph_id      
	LEFT JOIN graph_templates AS gt      ON gt.id=gl.graph_template_id      
	LEFT JOIN host_template AS ht     ON h.host_template_id=ht.id     
	LEFT JOIN user_auth_perms AS uap0 ON (gl.id=uap0.item_id AND uap0.type=1 AND uap0.user_id=1) 
	LEFT JOIN user_auth_perms AS uap1 ON (gl.host_id=uap1.item_id AND uap1.type=3 AND uap1.user_id=1) 
	LEFT JOIN user_auth_perms AS uap2 ON (gl.graph_template_id=uap2.item_id AND uap2.type=4 AND uap2.user_id=1)      
	WHERE h.id = 9 #also please notice the original query that the IN() will always contain the value 0 (zero)
	AND (uap0.user_id IS NULL OR uap1.user_id IS NULL OR uap2.user_id IS NULL)   
) AS rs2   ON rs2.id=h1.id
ORDER BY description;

SELECT FOUND_ROWS();
```

**Comment by cigamit** [comment]
I'll setup the table changes for 1.1.1, but if you could do a pull requests out of lib/auth.php, that would be great.

**Comment by cigamit** [comment]
Thanks for the pull request.  I made a comment there that we will need to rationalize this with some testing based upon this article: https://www.percona.com/blog/2007/08/28/to-sql_calc_found_rows-or-not-to-sql_calc_found_rows/.  If this is dated information and you can cite where improvements were made fundamentally to the algorithm, then I will merge right away, but if we can find evidence, someone will need to benchmark the differences using some real and sizable data.  Is that something you can do?

**Comment by reboot1983** [comment]
I've investigated this and the only changes for sql_calc_found_rows since MySQL 5.4 are bugfixes. 
I've not found any information in the release notes about optimisations or algorithm changes handling sql_calc_found_rows.

I guess benchmarking the differences is our only option.

**Comment by cigamit** [comment]
Okay, let's see if anyone can help with that.

**Comment by eschoeller** [comment]
The DB on our Cacti machine is the weakest link in terms of overall performance right now. I'm very interested in any improvements that can be made to ease up on the DB. If you provide me with a patch I can watch a few metrics we currently trend to see if there are any improvements. Namely CPU, memory, context switches, sockets and of course poller runtime. Our DB team may also be collecting stats on DB performance specifically but sadly this has fallen outside my purview as time has passed here (probably leading to these performance problems in the first place!)

**Comment by cigamit** [comment]
Decribe you setup, # cacti server, cores, memory, disk, and how many devices, graphs and users..

**Comment by eschoeller** [comment]
1 cacti server. 1 minute polling (on production instance). No boost. Running spine. 32 processes. balance process load. 16 threads per process. 445 hosts, 50,790 data sources, 15,550 RRDs, 56,240 snmp items, 9,510 scripts, 426 script servers. 64 threads, 32 cores, 4 physical CPUs. 372GB memory. RRDs are on PCIe enterprise SSDs (linux software raid 1). Database is on regular 15k SAS drives in a RAID 5 (was on the SSD as well at one point). 
5 minute load average during normal operation is 85. System is responsive via command line, but god awfully slow in the Cacti GUI. Borderline unusable by anyone but me (I'm patient).

**Comment by reboot1983** [comment]
When your cacti server is 'idle', (I mean only polling, no GUI operations), what's the 5-min load?
How long does your poller run?

Gui:
What takes the most time to load? 
- Opening a tree? 
- Getting the graphs on screen?

What the average loading time of one graph? (In chrome/IE; hit F12 (developer panel opens), select the network tab and check for the loading times of the graph requests).

**Comment by cigamit** [comment]
eschoeller,

Your spine process count is way too high, you are crushing the mysql server with connections.  This will cause the data collector to stall for several seconds.  MySQL does not handle opening the poller item for several hundred threads concurrently be it InnoDB or Memory storage engine.  Take your process count down to something like 4.  You should find that your number should not change that much.  If you have devices with a large number of items, you can parallelize by increasing the 'Device Threads' at the individual device level.  But what you have done is not even close to a best practice.

I know some Cacti installs with over 20k devices and they only use 4 processes and 15 threads.  If you have slow running scripts, you may want to collect that data asynchronously and pre-cache it in the database.

**Comment by eschoeller** [comment]
Here is the load average over the last day
![image](https://cloud.githubusercontent.com/assets/12864741/24737067/439e5a7c-1a49-11e7-9168-2ea87f2057bc.png)
Not much GUI operation. Like I said, at this point I'm the only one who can put up with it. I have a dashboard running on a screen in my office constantly refreshing 15 graphs every minute but that's about all the extra overhead there is. The rest is polling. The production instance poller runs at just about 42 seconds. Another instance runs about 15 seconds. The start time of that poller is delayed 30 seconds in cron, so they don't both start at the same time. Don't ask why there are two. There are three other smaller instances running but they are extremely minimal (dev, test, then a 10 second poller watching just the trending machine itself). 

Loading some graphs shows a maximum of 18.97 seconds for graph_view.php in just a few tests I've done. 

@cigamit Just reading your comment. Yes, I am aware that the settings page specifically states running more processes with spine is bad. It's been years since those settings were made, and each time I've strayed away to decrease processes and increase threads it's had a negative impact on the poller runtime and I timeout. Sure wish I had 5 minutes to run and not 1 minute. But a lot has changed over the years (yes, device threads in particular) so I'll make an aggressive change as you suggest and see what happens.

**Comment by cigamit** [comment]
Closing as the SQL_CALC_FOUND_ROWS adds no benefit when using InnoDB tables.  We will work on making the pollers more scalable by moving all the data collection input to the remote pollers.  Won't do that for a release or two though.  This will free up the central hosts and poller_items tables and help eschoeller out with his problem.
