### ISSUE TITLE
Spine not processing RRDs

### ISSUE THREAD

**Issue by danielnavcom** [Cacti/cacti#4733]
Spine Poller running at 1 minute. RRDs are not all processed from time to time (randomly).

Usually there are 2153 RRDs which should be processed:

20.04.2022 12:42:10 - SYSTEM STATS: Time:9.8483 Method:spine Processes:1 Threads:15 Hosts:12 HostsPerProcess:12 DataSources:5006 RRDsProcessed:2153 

Here:

20.04.2022 12:36:04 - SYSTEM STATS: Time:2.7954 Method:spine Processes:1 Threads:15 Hosts:12 HostsPerProcess:12 DataSources:5006 RRDsProcessed:1966 

When this happens there are random graphs with white interruptions.

There are no mysql errors, no cacti stderr errors, no other errors in logs - all green.

Also, I do not understand from where is the poller showing: DataSources:5006 because when I list them ALL at Management > Data Sources there are:  2166.

SPINE 1.2.20  Copyright 2004-2021 by The Cacti Group
Cacti 1.2.20

Is this a bug or am I missing something?

Running on debian 11 bullseye
php 7.4 fpm with nginx
mariadb 10.5

All are setup/configured correctly, no limits are reached, as stated above, no errors/warning are thrown.

**Comment by TheWitness** [comment]
spine does not process rrd's.

**Comment by TheWitness** [comment]
You likely have a profile that is not exactly the same as the poller interval.  Say, your poller interval is 1 minutes, and your cron interval is set to 5 minutes, and you have some data sources that are updating at a 5 minute interval and some with 1 minutes.  In this case, the number of RRDfiles processed by `poller.php` will rarely be the same.  It's really not a bug.

The way you can test this is by going to the poller item table and running this query:

```sql
SELECT rrd_step, COUNT(*) AS items FROM poller_item GROUP BY rrd_step;
```

If you have multiple collection frequencies, you will get back more than one row.

**Comment by danielnavcom** [comment]
From the logs, thats what I thought, that spine triggers the processing of data sources and rrds.
If it doesn't ok, but why are all RRDs not being processed sometimes?

There is only 1 main poller which runs once a minute.
We use only ﻿one profile - 1 minute.
All data sources have poller interval 1 minute.

Practically there is no poller/data source/template in our database setup for 5 minutes.

MariaDB [cacti]> SELECT rrd_step, COUNT(*) AS items FROM poller_item GROUP BY rrd_step;
+----------+-------+
| rrd_step | items |
+----------+-------+
|       60 |  5006 |
+----------+-------+
1 row in set (0.007 sec)

What are those 5006 items? And why are those named DataSources:5006 in the logs if the data sources number lower/different?

**Comment by TheWitness** [comment]
Yea, those are the data sources.  So, the number of RRDfiles processed should be consistent.  I will disable boost on my system.  In the mean time, turn on boost on your system to mask the issue.  More to follow.

**Comment by TheWitness** [comment]
Rat's, have to setup a second system.  When you have multiple pollers, you 'must' run boost.

**Comment by danielnavcom** [comment]
We come from a very old version of cacti, like 0.8... we recently updated from 1.2.19 to 1.2.20 without any issue, but I think we have no boost available on our installation.

Utilities > System utilities > View Boost Status
We have: https://imgur.com/a/jyWCOrb

But the logs show the following only when we access View Boost Status link from system utilities:

20.04.2022 15:24:05 - CMDPHP SQL Backtrace:   (/utilities.php[84]:boost_display_run_status(),  /utilities.php[2222]:db_fetch_cell(),  /lib/database.php[462]:db_fetch_cell_prepared(),  /lib/database.php[484]:db_execute_prepared())
--
20.04.2022 15:24:05 - CMDPHP ERROR: A DB Cell Failed!, Error: Table 'cacti.poller_output_boost_local_data_ids' doesn't exist

How does that work? :)

**Comment by danielnavcom** [comment]
I forgot to mention that this is happening rarely, like once/twice a day at a random hour/minute.

Nothing else is running on the machine, like other crons and stuff.. already checked to see if it somehow matches any other operation or something but.. no luck.

**Comment by TheWitness** [comment]
That table should exist.  You might want to check for it.

```sql
CREATE TABLE `poller_output_boost_local_data_ids` (
  `local_data_id` int(10) unsigned NOT NULL DEFAULT 0,
  `process_handler` int(10) unsigned DEFAULT 0,
  PRIMARY KEY (`local_data_id`),
  KEY `process_handler` (`process_handler`)
) ENGINE=MEMORY;
```

**Comment by danielnavcom** [comment]
Created the table, tho I have no clue from where to enable the booster, theres nothing about it at settings, I believe, as previously said, this is because we're having the installation since many years ago - though the upgrade does not fail at all, works like a charm, it doesn't complain on missing any tables/data.

I believe we still miss something regarding the boost.


Now, it is the first time since we upgraded to 1.2.20 when I see the following in logs: (and again not all RRDs are being processed)


`

21.04.2022 08:08:04 - SYSTEM DSSTATS STATS: Time:0.12 Type:HOURLY
--
21.04.2022 08:08:04 - SYSTEM THOLD STATS: Time:0.1148 Tholds:8 TotalDevices:12 DownDevices:0 NewDownDevices:0
21.04.2022 08:08:04 - SYSTEM STATS: Time:2.8660 Method:spine  Processes:1 Threads:15 Hosts:12 HostsPerProcess:12 DataSources:5006  RRDsProcessed:2153
21.04.2022 08:07:04 - SYSTEM DSSTATS STATS: Time:0.12 Type:HOURLY
21.04.2022 08:07:04 - SYSTEM THOLD STATS: Time:0.1018 Tholds:8 TotalDevices:12 DownDevices:0 NewDownDevices:0
21.04.2022 08:07:04 - SYSTEM STATS: Time:2.8908 Method:spine  Processes:1 Threads:15 Hosts:12 HostsPerProcess:12 DataSources:5006  RRDsProcessed:2024
21.04.2022 08:07:03 - POLLER: Poller[Main Poller] PID[509014] WARNING: Data Template 'Interface - Traffic' is impacted by lack of complete information
21.04.2022 08:07:03 - POLLER: Poller[Main Poller]  PID[509014] WARNING: There are 1 Data Sources not returning all data  leaving rows in the poller output table.  Details to follow.
21.04.2022 08:06:07 - SYSTEM DSSTATS STATS: Time:0.12 Type:HOURLY
21.04.2022 08:06:07 - SYSTEM THOLD STATS: Time:0.1096 Tholds:8 TotalDevices:12 DownDevices:0 NewDownDevices:0
21.04.2022 08:06:07 - SYSTEM STATS: Time:5.9108 Method:spine  Processes:1 Threads:15 Hosts:12 HostsPerProcess:12 DataSources:5006  RRDsProcessed:2153

21.04.2022 08:08:04 - SYSTEM DSSTATS STATS: Time:0.12 Type:HOURLY
21.04.2022 08:08:04 - SYSTEM THOLD STATS: Time:0.1148 Tholds:8 TotalDevices:12 DownDevices:0 NewDownDevices:0
21.04.2022 08:08:04 - SYSTEM STATS: Time:2.8660 Method:spine Processes:1 Threads:15 Hosts:12 HostsPerProcess:12 DataSources:5006 RRDsProcessed:2153
21.04.2022 08:07:04 - SYSTEM DSSTATS STATS: Time:0.12 Type:HOURLY
21.04.2022 08:07:04 - SYSTEM THOLD STATS: Time:0.1018 Tholds:8 TotalDevices:12 DownDevices:0 NewDownDevices:0
21.04.2022 08:07:04 - SYSTEM STATS: Time:2.8908 Method:spine Processes:1 Threads:15 Hosts:12 HostsPerProcess:12 DataSources:5006 RRDsProcessed:2024
21.04.2022 08:07:03 - POLLER: Poller[[Main Poller](http://cacti.nav.ro/pollers.php?action=edit&id=1)] PID[509014] WARNING: Data Template 'Interface - Traffic' is impacted by lack of complete information
21.04.2022 08:07:03 - POLLER: Poller[[Main Poller](http://cacti.nav.ro/pollers.php?action=edit&id=1)] PID[509014] WARNING: There are 1 Data Sources not returning all data leaving rows in the poller output table. Details to follow.
21.04.2022 08:06:07 - SYSTEM DSSTATS STATS: Time:0.12 Type:HOURLY
21.04.2022 08:06:07 - SYSTEM THOLD STATS: Time:0.1096 Tholds:8 TotalDevices:12 DownDevices:0 NewDownDevices:0
21.04.2022 08:06:07 - SYSTEM STATS: Time:5.9108 Method:spine Processes:1 Threads:15 Hosts:12 HostsPerProcess:12 DataSources:5006 RRDsProcessed:2153`

**Comment by danielnavcom** [comment]
Ok managed to have boost configured and running from Cacti Settings (Performance)

Will see how it acts.

**Comment by TheWitness** [comment]
Is this a new install with Cacti 1.2.20 or an upgrade?  If a new install, I suggest you restart with the latest 1.2.x branch.  We had a misstep on the 1.2.20 release with corrupted packages.  We are still working on fixing them.  What's in the 1.2.x branch at least will work, it's just not structured the way we want it yet.

**Comment by danielnavcom** [comment]
I upgraded from 1.2.19 to 1.2.20, it is not a fresh install of 1.2.20.

And to 1.2.19 we have reached from an old 0.8 install and then 1.1.x > 1.2.x ... and so on :)

I have managed to configure boost, it is running fine

We upgraded to 1.2.20 on 15 April this month.

**Comment by danielnavcom** [comment]
Update

Boost running fine, I have debug enabled, logs are all green, no warning, nothing weird happens.. Graphs have random interruptions several times in a day now.. on random devices, random graph types.

This was not happening before the upgrade.

We have only 12 cisco hosts, we have 1 spine process with 15 threads, devices are setup with snmp v3

Do you recommend anything special on devices configuration? Like how many Maximum OIDs Per Get Request, snmp timeout, collection threads?

**Comment by TheWitness** [comment]
For your current size, it's all a matter of how frequently you want to query,  basically with those settings, everything is done in parallel.  I know customers using spine with 5 process and 30 threads per process polling over 40k hosts.  So, you are good right where you are at.  Years ago I did a write-up on the forums that might be in the Cacti documentation now.  It's safe to say that spine scales pretty well.  Usually things go bad when you loose a wan Link to a large site, which can be overcome using remote data collectors which are fault tolerant.  But if you are all LAN based or your WAN is good, you are just fine.

**Comment by TheWitness** [comment]
There was a change in cmd.php to insert all host records in bulk identically to spine as a potential workaround to this and there was a changelog for that.  So, just marking this solved and closed.

**Comment by danielnavcom** [comment]
Hey,

Thanks for getting back to this issue.

So, afterall I should wait for 1.2.21 to upgrade if this is marked as fixed.

Now, I re-open it just to make sure nothing else is wrong. After several days/weeks now since I use booster, blank/white interruptions in random graphs still show daily (waiting to update once new version will be released).

Though I see this in the logs:

```
03.05.2022 08:51:07 - CMDPHP SQL Backtrace:   (/graph_image.php[133]:rrdtool_function_graph(),  /lib/rrd.php[1257]:boost_graph_cache_check(),  /lib/boost.php[360]:boost_process_poller_output(),  /lib/boost.php[906]:db_execute_prepared())
--
03.05.2022 08:51:07 - CMDPHP ERROR: A DB Exec Failed!, Error: Table  'cacti.poller_output_boost_arch_1651557063' doesn't exist
```

**Comment by TheWitness** [comment]
What cacti release are you at?

**Comment by danielnavcom** [comment]
Spine / Cacti 1.2.20

**Comment by TheWitness** [comment]
This error can be ignored, but it is a bug.  Glad you brought it up.  Logging it in a minute just to verify

```
20.04.2022 15:24:05 - CMDPHP SQL Backtrace: (/utilities.php[84]:boost_display_run_status(), /utilities.php[2222]:db_fetch_cell(), /lib/database.php[462]:db_fetch_cell_prepared(), /lib/database.php[484]:db_execute_prepared())
20.04.2022 15:24:05 - CMDPHP ERROR: A DB Cell Failed!, Error: Table 'cacti.poller_output_boost_local_data_ids' doesn't exist```
