### ISSUE TITLE
1.2.20 help---change my Data Source Profile  5 Minute Collection ---error

### ISSUE THREAD

**Issue by wangguowang** [Cacti/cacti#4735]
![image](https://user-images.githubusercontent.com/17695129/164355196-a7f435c2-8ba3-4a0e-a501-8acd9ad90472.png)
when change my Data Source Profile  5 Minute Collection  above, i must store 5 miniutes data for excel export.
but i find error :
![image](https://user-images.githubusercontent.com/17695129/164355460-fb8d76d7-1cc2-429b-85e3-a226da56c37e.png)

please help ,thanks!

**Comment by netniV** [comment]
If this is a new data source, remove the offending RDD. If it's an existing one and you have changed the polling cycle there is a cli script that can help migrate the data by filling in missing data points.

**Comment by wangguowang** [comment]
it's new data source ,i have removed the rdd file and rebuilded, but error again

**Comment by TheWitness** [comment]
@wangguowang, I think your "steps" definition is wrong.  This results in a bogus layout.  You steps should be a multiple of the previous RRA.  So, it might be the code.  I'll have to test.

**Comment by TheWitness** [comment]
If you look at the attached image, the steps should always be different between RRA's.  See below.

![image](https://user-images.githubusercontent.com/1439914/166061583-c4cadb79-edb7-4875-b1c6-04bad70daa9b.png)

So, this is a bug in Cacti, but you should be able to fix it internally and then start over.

**Comment by TheWitness** [comment]
Once my pull request is merged, this issue should be resolved.  However, you will need to modify your Data Source Profile RRA's as I explained.

**Comment by TheWitness** [comment]
The 1.2.21 release will make it harder to make these types of mistakes.  Marking resolved and closing now.
