### ISSUE TITLE
Some PHP options value incorrect in Installation Wizard -->Step 2

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#4736]
# Describe the bug
Some PHP options value incorrect in Installation Wizard -->Step 2, See:
* `date.timezone` in `Recommendations (web)`
* `max_execution_time` in `Recommendations (cli)`

## Screenshots
![image](https://user-images.githubusercontent.com/17589018/164392486-cd36e1d2-3273-463c-9692-72a205211927.png)

## OS
* RHEL 8.5 for x86_64
* PHP 7.4.19

**Comment by TheWitness** [comment]
Agreed the max_execution_time for CLI should be 0 for sure.

**Comment by TheWitness** [comment]
I'm surprised that the Database Timezone comes back that way.

**Comment by netniV** [comment]
I totally disagree with max execution time of 0 for cli scripts as that can result in a never ending looping script eating resources. 

There should certainly be a couple that do but most scripts should fall under a reason time limit

**Comment by ddb4github** [comment]
> @ddb4github, on the timezone side, the cacti_set. The file `lib/functions.php` has the following:
> 
> ```
> $zone = timezone_name_from_abbr('', $gmt_offset);
> ```
> 
> Maybe that function can be leveraged?

root cause of `date.timezone in Recommendations (web)` should be code before this line:
![image](https://user-images.githubusercontent.com/17589018/164582204-fa0b3951-97e1-4cf2-912a-f8e8c2df6d3b.png)

**Comment by ddb4github** [comment]
BTW, found lots of `ini_set` calling, I think, Installation Wizard should ignore all these modification by `IN_CACTI_INSTALL`. 
```php
include/cli_check.php:38:       ini_set('memory_limit', $default_limit);
include/cli_check.php:42:       ini_set('max_execution_time', $default_time);
include/global.php:398: ini_set('post_max_size', '8M');
include/global.php:401: ini_set('session.cookie_httponly', true);
include/global.php:402: ini_set('session.cookie_path', $config['url_path']);
include/global.php:403: ini_set('session.use_strict_mode', true);
include/global.php:412:         ini_set('session.cookie_domain', $cacti_cookie_domain);
include/global.php:418:         ini_set('session.cookie_samesite', 'Strict');
include/global.php:423:         ini_set('session.cookie_secure', true);
include/vendor/phpmailer/src/PHPMailer.php:1809:            ini_set('sendmail_from', $this->Sender);
include/vendor/phpmailer/src/PHPMailer.php:1822:            ini_set('sendmail_from', $old_from);
include/vendor/phpseclib/Crypt/Random.php:145:            ini_set('session.use_cookies', 0);
include/vendor/phpseclib/Crypt/Random.php:169:                ini_set('session.use_cookies', $old_use_cookies);
include/vendor/phpsnmp/mib_parser.php:61:               ini_set('memory_limit', '-1');
lib/import.php:262:             ini_set('max_execution_time', '50');
lib/import.php:263:             ini_set('memory_limit', '-1');
lib/html_utility.php:878:       ini_set('track_errors', 1);
lib/html_utility.php:881:               ini_set('track_errors', $track_errors);
lib/html_utility.php:889:       ini_set('track_errors', $track_errors);
lib/boost.php:1237:     ini_set('memory_limit', read_config_option('boost_poller_mem_limit') . 'M');
lib/dsstats.php:981:    ini_set('memory_limit', read_config_option('dsstats_poller_mem_limit') . 'M');
lib/functions.php:6982:         ini_set('date.timezone', $_SESSION['sess_browser_php_tz']);
lib/functions.php:6995:         ini_set('date.timezone', $_SESSION['sess_php_tz']);
lib/functions.php:7022:         ini_set('date.timezone', 'Etc/GMT' . ($hours > 0 ? '-':'+') . abs($hours));
lib/functions.php:7086:                 ini_set('date.timezone', $zone);
```

Even ignore installer self modification to show actual `system configuration`
```php
lib/installer.php:3379:               Installer::setPhpOption('max_execution_time', 0);
lib/installer.php:3380:               Installer::setPhpOption('memory_limit', -1);
lib/installer.php:3434:       public static function setPhpOption($option_name, $option_value) {
lib/installer.php:3438:                 ini_set($option_name, $option_value);
```

**Comment by TheWitness** [comment]
The timezone part of this should be better now.

**Comment by ddb4github** [comment]
> I totally disagree with max execution time of 0 for cli scripts as that can result in a never ending looping script eating resources.
> 
> There should certainly be a couple that do but most scripts should fall under a reason time limit

Just check php.ini and `php -i`,  PHP team said:
 * The default setting is 30. When running PHP from the [command line](https://www.php.net/manual/en/features.commandline.php) the default setting is 0.
 * In my Env
   * **php.ini**
    ```ini
    php.d/05-cacti.ini:2:memory_limit = 400M
    php.d/05-cacti.ini:3:max_execution_time = 60
    php.ini:386:; http://php.net/max-execution-time
    php.ini:387:; Note: This directive is hardcoded to 0 for the CLI SAPI
    php.ini:388:; max_execution_time = 30
    ```
    * **php -i**
    ```
   max_execution_time => 0 => 0
   memory_limit => 400M => 400M
   "Olson" Timezone Database Version => 0.system
   Timezone Database => internal
   Default timezone => America/Los_Angeles
   date.timezone => America/Los_Angeles => America/Los_Angeles
   ```

**Comment by ddb4github** [comment]
So close this ticket for date.timezone

**Comment by netniV** [comment]
Thanks for the lesson learnt on the execution time @ddb4github.  So it would seem that setting execution time has no effect at the CLI level, only when run through the web, etc.
