### ISSUE TITLE
Cacti 1.2.18 not collecting data for traffic over 80 Giga bits per sec limit

### ISSUE THREAD

**Issue by kasimanikandan** [Cacti/cacti#4739]
# Describe the bug

I'm using Cacti 1.1.28 not collecting data for traffic over  80 Giga bits per sec limit, rrd files showing NaN if the interface traffic goes beyond 80 giga bites per second

Data Template:
Inbound Traffic
![image](https://user-images.githubusercontent.com/85684729/164956313-28a52afc-02f7-46e1-a35c-6b6e50e2604e.png)

Outbound Traffic:
![image](https://user-images.githubusercontent.com/85684729/164956340-bc2ae235-f64f-49c0-9234-11b4bf97934e.png)

Interface traffic Graph:
![image](https://user-images.githubusercontent.com/85684729/164956455-09fa70c4-6284-451e-9e57-ec0d93a6c729.png)

- OS: Linux

- Browser : Chrome

- Version : 1.2.17

Could you please advise how we can handle this issue ?

Thanks In advance.

Regards,
Mani

**Comment by TheWitness** [comment]
You might want to look for a max value on either the Graph Template, or a bad max value in the RRDfile.  This is likely not a Cacti bug but a setup problem.  For the Data Source, you should run Data Debug, but don't forget to review the AutoScaling and Max values on the Graph Template too.

**Comment by kasimanikandan** [comment]
Thanks @TheWitness  for quick reply.

Please find below for graph template settings for interface graphs.
![image](https://user-images.githubusercontent.com/85684729/165106288-f7b90c43-2693-4241-ab2d-7f0d12d98fb5.png)

could you please advise anything wrong with this settings ?

Thanks,
Mani

**Comment by TheWitness** [comment]
Where is your Data Debug information?

**Comment by kasimanikandan** [comment]
Hi @TheWitness ,

rrdinfo returning max values as below where its exactly dropping when its reaches that limit.

rrdinfo:
![image](https://user-images.githubusercontent.com/85684729/165193785-1faae423-868b-4e41-801c-b7d0abff9b25.png)

Date Template:
![image](https://user-images.githubusercontent.com/85684729/165194087-a1700ea7-7182-4aed-b1cb-7afa472fba15.png)


but as per the templates max limit was set to U (maximum limit is unlimited). could you please advise when we update the template setting it wont applied to already existing data source ?

is there any solution to handle this scenario if we have huge data sources 

Thanks,
Mani

**Comment by TheWitness** [comment]
Where is the Data Debug information though?  This is the third time I've asked that question.

**Comment by kasimanikandan** [comment]
Sorry.. Please find below for data debug informations 

data debug information:
![image](https://user-images.githubusercontent.com/85684729/165231160-7e3569b2-64bb-48ec-b00a-fec2c663013c.png)


Data Source:
![image](https://user-images.githubusercontent.com/85684729/165229220-2c83af11-bdc8-41a9-b351-17b67489632a.png)

Data source troubleshoot:
![image](https://user-images.githubusercontent.com/85684729/165230600-f2279543-d573-4c40-8d33-e98b7bb1ee68.png)

Please let me know if you need any additional details.

Thanks,
Mani

**Comment by TheWitness** [comment]
Go to the Graphs New page, bring up the Interfaces Data Query and report what the ifHighSpeed is for the interface.

**Comment by kasimanikandan** [comment]
Please find below for HighSpeed details for this interface.

![image](https://user-images.githubusercontent.com/85684729/165304522-3e9098c6-d5a7-4edf-be63-fb7037d9e0d3.png)

Thanks,
Mani

**Comment by bmfmancini** [comment]
Im not seeing it but are you using 64bit counters?

go to management >> graphs and check that your graph source name looks like this 

![image](https://user-images.githubusercontent.com/13388748/165312682-78e066cf-52fa-4fc3-aa9f-bc5530eca6ea.png)

if your not using 64bit that could be what this is

**Comment by kasimanikandan** [comment]
@bmfmancini , i have checked data query, its 64 bit counter.

@TheWitness ,
I have updated the rrd files max limit as U (unlimited) earlier it was 1.000xe^10... but still its showing NaN when its reached above this limit. Do we need to delete the data source & graph and recreate to get this changes effective ?

Also, i have noticed when i delete the device from management tab, there was an option (check) to delete data source & graph can also be deleted. but when chose that option (delete both data source & graph) rra files are not getting deleted on the server. could you please advise about this behaviour ? 

Thanks,
Mani

**Comment by TheWitness** [comment]
There is a Cacti option to AutoPurge RRDfiles.  It's off by default.  That will happen when the poller runs.  Setting the max values to 'U' should stop the clipping though.  So, not sure what you are doing wrong.  If you remove the Data Source, the invalid Max will still happen.  BTW, when you change the Max, it does not go back in time and correct the wrong measurements, it's only for future measurements.

Focus on getting your hardware vendor to fix their agent as that is the real issue.  You might want to write a script to 'fix' the max value for those ifHighSpeeds that you know are wrong.

**Comment by kasimanikandan** [comment]
Thanks @TheWitness  for the details.

Apologies for asking too many questions.

I have one more query, for example if we change the max limit values i.e traffic_in max values was 10000000 at the time of data source creation and later this value is updated to U or some other values from Cacti UI, will it update both cacti db table (data_template_rrd) as well as rrd files ? or it only update cacti db table (data_template_rrd) and rrd files we have to update manually via rrdtool tune command ?

As per my understanding based on this specific issue any changes in the template (via Cacti UI) only updating the cacti tables and rrd files were intact which required manual updates.. please correct me if my observation is wrong.

Also if we update the rrd file via rrdtool tune command for this example updating max traffic values to U and do we need to delete the graph or data source (rra file) or both to get the changes effective on the graph ?
I tried to update one of the interface data source (rrd file) and kept the graph as is but still its dropped the data when its reached previously limit values (80 Gbps). so its bit confusing whether we have to delete only the graph and add it again or we have delete both graph & datasource (rrd) or Nothing required ? 


Thanks,
Mani

**Comment by kasimanikandan** [comment]
Thanks a lot @TheWitness  @netniV  @bmfmancini for your time and helping me to fix this issue. Updating the rrd files max limit fixed this issue.
