### ISSUE TITLE
Graph is not populating at all since upgrade to 1.0.x

### ISSUE THREAD

**Issue by zetoo1412** [Cacti/cacti#474]
My technical supports :
Cacti 1.0.5
Spine 1.0.3
RRDTool 1.4.5 VC10
Net-SNMP 5.5.0-2
MySQL 5.7.16
PHP 7.0.16
IIS 8.5
Window Server 2012

RRDTool Command:
c:/rrdtool/rrdtool.exe graph - \
--imgformat=PNG \
--start="-180000" \
--end="-300" \
--pango-markup \
--title="Cacti Host Test - CPU Utilization" \
--vertical-label="percent" \
--slope-mode \
--base=1000 \
--height=150 \
--width=600 \
--alt-autoscale-max \
--lower-limit="0" \
--color BACK#F3F3F3 \
--color CANVAS#FDFDFD \
--color SHADEA#CBCBCB \
--color SHADEB#999999 \
--color FONT#000000 \
--color AXIS#2C4D43 \
--color ARROW#2C4D43 \
--color FRAME#2C4D43 \
--border 1 --font TITLE:11:"Ariel" \
--font AXIS:8:"Ariel" \
--font LEGEND:8:"Courier" \
--font UNIT:8:"Ariel" \
--font WATERMARK:6:"Ariel" \
--slope-mode \
--watermark "Copyright (C) 2004-2017 The Cacti Group" \
DEF:a="C\:/inetpub/wwwroot/cacti/rra/cacti_host_test_sscpusystem_47.rrd":"ssCpuSystem":AVERAGE \
DEF:b="C\:/inetpub/wwwroot/cacti/rra/cacti_host_test_sscpuuser_48.rrd":"ssCpuUser":AVERAGE \
DEF:c="C\:/inetpub/wwwroot/cacti/rra/cacti_host_test_sscpuidle_46.rrd":"ssCpuIdle":AVERAGE \
CDEF:cdefbc="100,TIME,1489994873,GT,a,a,UN,0,a,IF,IF,TIME,1489994873,GT,b,b,UN,0,b,IF,IF,TIME,1489994873,GT,c,c,UN,0,c,IF,IF,+,+,-" \
AREA:a#F51D307F:"System\: " \
GPRINT:a:LAST:"Current\:%8.1lf %%" \
GPRINT:a:AVERAGE:"Average\:%8.1lf %%" \
GPRINT:a:MAX:"Maximum\:%8.1lf %%\n" \
AREA:b#74C3667F:"User\: ":STACK \
GPRINT:b:LAST:"Current\:%8.1lf %%" \
GPRINT:b:AVERAGE:"Average\:%8.1lf %%" \
GPRINT:b:MAX:"Maximum\:%8.1lf %%\n" \
AREA:c#3D3C3A7F:"Idle\: ":STACK \
GPRINT:c:LAST:"Current\:%8.1lf %%" \
GPRINT:c:AVERAGE:"Average\:%8.1lf %%" \
GPRINT:c:MAX:"Maximum\:%8.1lf %%\n" \
AREA:cdefbc#00004D7F:"IO Wait\:":STACK \
GPRINT:cdefbc:LAST:"Current\:%8.1lf %%" \
GPRINT:cdefbc:AVERAGE:"Average\:%8.1lf %%" \
GPRINT:cdefbc:MAX:"Maximum\:%8.1lf %%\n"

RRDTool Says:
OK

This only happen when I tried to create graph from default template. All of them seems like did not updating.

**Comment by cigamit** [comment]
If using RRDtool 1.2.x please upgrade to RRDtool 1.3.x+.

**Comment by cigamit** [comment]
On approximately line 2051, you will see something like:

$output = rrdtool_execute("$graph ...

issue the following statement just before that call:

cacti_log("$graph ...);

Take the log output and then attempt to run this from the command line.  Let us know what the output/error is.

**Comment by zetoo1412** [comment]
@cigamit sorry, could you direct me since I am still a newbie here. Which one I need to open to find those line 2501 ? 
I could not find those in clog.

**Comment by cigamit** [comment]
Please continue to read the code and study on php.net.  The idea here is to log the rrdtool_execute() statement to the log so that you may test it at the command line.  I can not help you other than that.  You have to in a sense, help yourself.

**Comment by cigamit** [comment]
Please update to 1.1.1, and re-populate your poller cache.  Run the poller one time by hand.  I suspect this issue belongs on the forums first since you don't have enough experience to discuss this in detail.  So, for now, I'm closing.

**Comment by zetoo1412** [comment]
@cigamit thanks a lot for replying. I will try to upgrade to 1.1.1 soon.

**Comment by zetoo1412** [comment]
already upgrade to 1.1.2 and re-populate but nothing happens.

All I do is upgrade from 0.8.8f to 1.0.x then to 1.x.x (using installer from BSOD2600 which I think thats not the issue)
