### ISSUE TITLE
Ping only device Down

### ISSUE THREAD

**Issue by dschultzca** [Cacti/cacti#4742]
If I set a device to be monitored with Ping only, its status becomes Down even though the device is reponding.
Cacti 1.2.14 on Windows

**Device Setup**

![image](https://user-images.githubusercontent.com/1688870/165585664-3ada51d4-fb0d-4906-93a7-7aee601e5569.png)

**Device Status**

![image](https://user-images.githubusercontent.com/1688870/165585874-7ca66bf0-2a9b-494c-b5df-94fd4d13cee4.png)

**Debug Log**

![image](https://user-images.githubusercontent.com/1688870/165586209-4615368c-a252-488d-8d0a-be50569b6035.png)

What am I missing?
Thanks

**Comment by xmacan** [comment]
chmod +s /path/to/spine

**Comment by dschultzca** [comment]
How does that help on Windows?

**Comment by xmacan** [comment]
ups... sorry. I overlooked that it is on windows. It is typical linux spine problem

**Comment by TheWitness** [comment]
Install the full Cygwin if you have not already and make sure you change the permission on spine

```sh
cd /usr/local/spine/bin/
chmod +s spine
```

Should behave like any other Linux variant.

**Comment by dschultzca** [comment]
I have no Cygwin installation.   I used the Cacti installer for Windows https://forums.cacti.net/viewtopic.php?t=14946  
Are you saying I need to switch to a Cygwin compiled version of spine?

**Comment by TheWitness** [comment]
The guy who does the packaging does that for you.  If you install cygwin, it's a simple thing, you can change the permissions.

**Comment by TheWitness** [comment]
Yea, right now spine is ICMP ping is not supported.  It's been open for a while under spine.  We would be glad to receive a contribution.  I would use SNMP if it's available.  If not, try TCP ping.  It will essentially attempt to connect ot a well known port like AD, and if it can, then it will assume the host is up.  Just pick a good port, even if it's a bad port, I think TCP ping will detect that (on Linux for sure), and proceed.  The only issue might be on Windows.  So, just pick a port that you know is always open.

**Comment by TheWitness** [comment]
Marking related to https://github.com/Cacti/spine/issues/127 and closing.  Continue to comment if you like.

**Comment by dschultzca** [comment]
BTW, trying to use TCP as a dection method still fails as the check for the IPv6 address marks the host down with no attempt to try to connect to the port.  Same message as ping only.  
`PING Result: PING: Device is Unknown or is IPV6. Please use the SNMP ping options only.`

**Comment by TheWitness** [comment]
That might be true re setuid.  Patches are always welcome.
