### ISSUE TITLE
fontawesome error

### ISSUE THREAD

**Issue by densenator** [Cacti/cacti#4743]
# Describe the bug
27.Apr.2022 22:13:22 - CMDPHP PHP ERROR NOTICE Backtrace: (/graph_view.php[139]:get_matching_nodes(), /graph_view.php[129]:CactiErrorHandler())
27.Apr.2022 22:13:22 - ERROR PHP NOTICE: Undefined variable: fa in file: /var/www/html/cacti/graph_view.php on line: 129
27.Apr.2022 22:13:15 - CMDPHP PHP ERROR NOTICE Backtrace: (/graph_view.php[139]:get_matching_nodes(), /graph_view.php[129]:CactiErrorHandler())
27.Apr.2022 22:13:15 - ERROR PHP NOTICE: Undefined variable: fa in file: /var/www/html/cacti/graph_view.php on line: 129
27.Apr.2022 22:13:13 - CMDPHP PHP ERROR NOTICE Backtrace: (/graph_view.php[139]:get_matching_nodes(), /graph_view.php[129]:CactiErrorHandler())
27.Apr.2022 22:13:13 - ERROR PHP NOTICE: Undefined variable: fa in file: /var/www/html/cacti/graph_view.php on line: 129
27.Apr.2022 22:13:12 - CMDPHP PHP ERROR NOTICE Backtrace: (/graph_view.php[139]:get_matching_nodes(), /graph_view.php[129]:CactiErrorHandler())
27.Apr.2022 22:13:12 - ERROR PHP NOTICE: Undefined variable: fa in file: /var/www/html/cacti/graph_view.php on line: 129
27.Apr.2022 22:13:12 - CMDPHP PHP ERROR NOTICE Backtrace: (/graph_view.php[139]:get_matching_nodes(), /graph_view.php[129]:CactiErrorHandler())
27.Apr.2022 22:13:12 - ERROR PHP NOTICE: Undefined variable: fa in file: /var/www/html/cacti/graph_view.php on line: 129
27.Apr.2022 22:13:10 - CMDPHP PHP ERROR NOTICE Backtrace: (/graph_view.php[139]:get_matching_nodes(), /graph_view.php[129]:CactiErrorHandler())
27.Apr.2022 22:13:10 - ERROR PHP NOTICE: Undefined variable: fa in file: /var/www/html/cacti/graph_view.php on line: 129
27.Apr.2022 22:13:08 - CMDPHP PHP ERROR NOTICE Backtrace: (/graph_view.php[139]:get_matching_nodes(), /graph_view.php[129]:CactiErrorHandler())
27.Apr.2022 22:13:08 - ERROR PHP NOTICE: Undefined variable: fa in file: /var/www/html/cacti/graph_view.php on line: 129
27.Apr.2022 22:13:05 - CMDPHP PHP ERROR NOTICE Backtrace: (/graph_view.php[139]:get_matching_nodes(), /graph_view.php[129]:CactiErrorHandler())
27.Apr.2022 22:13:05 - ERROR PHP NOTICE: Undefined variable: fa in file: /var/www/html/cacti/graph_view.php on line: 129
27.Apr.2022 22:13:04 - CMDPHP PHP ERROR NOTICE Backtrace: (/graph_view.php[139]:get_matching_nodes(), /graph_view.php[129]:CactiErrorHandler())
27.Apr.2022 22:13:04 - ERROR PHP NOTICE: Undefined variable: fa in file: /var/www/html/cacti/graph_view.php on line: 129

**Comment by TheWitness** [comment]
I have a pull request pending that should resolve this.

**Comment by TheWitness** [comment]
Thanks for testing!

**Comment by TheWitness** [comment]
This is resolved now.  Thanks for your bug submission.
