### ISSUE TITLE
Has Aggregate been having issues?

### ISSUE THREAD

**Issue by blackboar** [Cacti/cacti#4745]
Aggregate has many imperfections

1. The template cannot be edited
It seems that only Source Graph Template can be inherited and cannot be changed anymore:

![image](https://user-images.githubusercontent.com/9621926/165708466-cf796653-8090-4b33-a0f2-ffa6c408a9c4.png)

2. The graphic content cannot be displayed normally
Cannot display IN or OUT and which source data

![image](https://user-images.githubusercontent.com/9621926/165708567-8ab9d3cc-c35a-4a73-8855-3c66ba84f278.png)

**Comment by blackboar** [comment]
1.X has been having issues with aggregation, today I installed a brand new set of 1.2.20 test results

**Comment by TheWitness** [comment]
Working fine for me.  I think you need to be more specific what specifically can you not change?

**Comment by blackboar** [comment]
@TheWitness

**Comment by blackboar** [comment]
1. Whether it is a template or a graphic aggregation, I hope it can change the configuration of the Item;
2, and hope to display the data source name and in or out normally

**Comment by TheWitness** [comment]
To do that well, you should pick the data source ordering, but keep in mind, unless you are summing all the data sources and showing only a line and a single area fill, the graphs get real ugly.  I generally separate In and out into two separate aggregates if I want to view all the interfaces separately.  I was thinking you could make one positive and the other negative, but that would be a feature request.  So, basically add an invert checkbox for lines and area fills.  If that works for you, I would request you open a separate feature request.

**Comment by TheWitness** [comment]
Oh, click the Checkbox "Include Prefix Text" and see if that help lol 🥇

**Comment by TheWitness** [comment]
No feedback.
