### ISSUE TITLE
After Updating to Cacti 1.2.20 unable to view timeline of Graph

### ISSUE THREAD

**Issue by sdiwakar123** [Cacti/cacti#4755]
After Updating to Cacti 1.2.20 unable to view timeline of Graph,
Unable to view 1 min, 1hour, Daily, Weekly Graph timeline view.
Please help.

**Comment by netniV** [comment]
This isn't an enhancement.  In fact, I'm going to guess this is a duplicated bug report for the user options that were incorrectly turned off during one of the earlier upgrade versions.  Edit your user and you'll see the option is off.

**Comment by sdiwakar123** [comment]
Thanks how can i change this settings for all users by default?

**Comment by TheWitness** [comment]
Create a user group that has the permission and put them all in that group.  Otherwise, there is a simple insert statement you can run from the command line to do it. 

It goes something like this:

```sql
INSERT IGNORE INTO user_auth_realms (user_id, realm_id) 
SELECT user_id, blah AS realm_id
FROM user_auth:
```

Where `blah` is the realm.

**Comment by sdiwakar123** [comment]
> Edit your user and you'll see the option is off.

Could you please tell me what option is disabled in user profile, actully in earliear version we were able to see option like (timeline, realtime graph and RRD tool option) but after upgrade those options are not showing.
![image](https://user-images.githubusercontent.com/76724933/166648724-66edd4b9-6e78-4ce1-bbf6-5ac489980551.png)

**Comment by TheWitness** [comment]
It's a user permission not a profile setting you have to do that by editing the user as I explained previously.

**Comment by sdiwakar123** [comment]
> It's a user permission not a profile setting you have to do that by editing the user as I explained previously.

Could you please share snapshot of that particular settings.

**Comment by TheWitness** [comment]
![image](https://user-images.githubusercontent.com/1439914/166803639-66543a35-616f-44ea-a916-e0ffd4158621.png)

**Comment by netniV** [comment]
As this is a confirmed duplicate, I'm going to close it now.

**Comment by sdiwakar123** [comment]
Thanks
