### ISSUE TITLE
Local Login Failed when Multiple LDAP/AD Domain Authentication Selected 

### ISSUE THREAD

**Issue by huangchao-shanghai** [Cacti/cacti#4763]
# Describe the bug
cacti version 1.2.20
Selected Multiple LDAP/AD Domain Authentication 
AD auth is OK
Local login failed

## To Reproduce

1. Go to 'Configuration -> Settings -> Authentication '

2. Click on 'Authentication Method:'

3. Scroll down to 'Multiple LDAP/AD Domain Authentication'

User Login page 
select Realm: Local
Enter the admin user name and password and click login
unable to login back to login page

## Expected behavior

Normal login

## Screenshots
![image](https://user-images.githubusercontent.com/3233883/166924919-09ad199f-267c-44b6-b564-6934e38459a3.png)
![image](https://user-images.githubusercontent.com/3233883/166925097-556337ac-d423-433c-b51a-c9a93dcbdc0c.png)
![image](https://user-images.githubusercontent.com/3233883/166925192-f0184ff0-f9ac-4590-a531-5d319e2d97a0.png)

## Desktop (please complete the following information)

- OS: [windows 2019]

- Browser [chrome, edge]

- Version [100.0.1185.50]

**Comment by TheWitness** [comment]
I have a pending pull request that will resolve this.
