### ISSUE TITLE
Unable to login to Cacti Web Access and no error message

### ISSUE THREAD

**Issue by donsan-git** [Cacti/cacti#4765]
Dear Friends,
I have a Cacti 1.2.19 running on Centos 7.9 server in production. As it is giving hardware issues, we planned to install another server and migrate.
Installed Cacti 1.2.20 on another server.
Migrated the database (cacti.sql) and .rrd files to new server.
After migration is complete, unable to login to the new server through web (http://New_Serer_IP_Address/cacti) as admin with old server's admin account's password (as guided).
It doesn't give any error, and stays at the same login page. And, it takes any password and same behavior except for blank password. For blank password, it says "Access Denied: No password provided by User"
Please let me know how do I fix this.
Please let me know if you would need any further information / details

Thanks in advance

Regards'
Sanjeeva

**Comment by bmfmancini** [comment]
Have you tried private mode or incognito?

**Comment by donsan-git** [comment]
Yes. I tried now. And it is the same. It doesn’t login and stays at login page only!

 

One observation is that,

The URL being tried is http://Server_IP_address/cacti/ . However, it is going to http://Server_IP_Address/cacti/install/install.php 

 

Thanking you,

 

Regards’

Sanjeeva

**Comment by TheWitness** [comment]
Update to the 1.2.x branch.  That'll be 1.2.21 shortly.

**Comment by TheWitness** [comment]
Note, that there is a pull request pending for 1.2.x, depending on your situation, you may need to update auth_login.php from that pull.

**Comment by donsan-git** [comment]
Ok. Thanks for the suggestion. I shall check about the pull request!

**Comment by donsan-git** [comment]
I have tried now with the change suggested in auth_login.php. But, no luck! Problem is still the same,

**Comment by TheWitness** [comment]
What is the php version of the new server?  I'm thinking this might be something different than the bug I just fixed.  Also, what authentication method are you using?

**Comment by TheWitness** [comment]
Try this too...

```sql
REPLACE INTO settings (name, value) VALUES ('secpass_forceold', '');
```

**Comment by TheWitness** [comment]
The issue you have is that you went backward on PHP.  Not a good move.  That old PHP version does not recognize you passwords.  In PHP7++ the passwords are encrypted with a differing algorithm that is not supported in PHP5.4.  I suggest you grab PHP from the REMI repos.  It's what I use on CentOS7 to get a more recent PHP.  PHP7.4.x is a good release.

**Comment by donsan-git** [comment]
Yes. Upgrading PHP to 7.4.x from Remi resolved the issue and the system is back!
Thanks a lot! 

Regards'
Sanjeeva

**Comment by netniV** [comment]
Maybe we should have an issue open to create an installer check and report if the PHP version has been downgraded (it can only be a warning since that may be necessary).

**Comment by TheWitness** [comment]
Not a bad idea.

**Comment by donsan-git** [comment]
Shall I reopen the case / ticket?

**Comment by netniV** [comment]
Be cleaner in a feature request.
