### ISSUE TITLE
Poller error when update the cacti and realtime button disappear

### ISSUE THREAD

**Issue by David-yanp** [Cacti/cacti#4767]
Hello,

Yesterday, I updated the syslog which is the cacti's plugin to try to fix the alert command issue. But I have some other errors on the `cacti.log` . So, I updated the cacti to 1.2.20 and updated the Spine to the latest, when I finish it. the `cacti.log` shows the error: `POLLER: Poller[[Main Poller](https://new.noc.wang/pollers.php?action=edit&id=1)] PID[19537] ERROR: Process being killed due to timeout! (commands, master, 1, 17814)`, in the meantime, I found the graphs didn't show the real-time button on each graph.

I don't know how to debug these issues, someone can help me?
Any idea will be appreciated.
## Screenshots

![image](https://user-images.githubusercontent.com/11266502/167751707-fcf82bce-3a63-4b63-bb50-6cf7ba4533fa.png)

**Comment by bmfmancini** [comment]
For the real-time button issue that can be fixed in the user permissions

Make sure the user has the show graph action icons permission set to on

**Comment by David-yanp** [comment]
Hi,

Thank you for replying to me.

The real-time button issues have been resolved, I think it would be better to have it enabled by default for admins.
And another one, I downgrade the cacti to 1.2.17 and upgrade with incognito mode again, the Poller error wasn't shown again.
It seems wired.
