### ISSUE TITLE
Cacti - 1.2.20 Windows version - No graph displayed

### ISSUE THREAD

**Issue by phipou** [Cacti/cacti#4773]
# Describe the bug

Unable to see graph drawn.  Blank page with icon on top left corner

## To Reproduce

Fresh install of Cacti 1.2.20 on Windows Server. Add new device with template - 'Generic Snmp device' or 'Cacti Stats" or 'net-snmp device"  - I am not able to see graph.

## Screenshots
![image](https://user-images.githubusercontent.com/104107518/168162872-5b5fd316-7396-498c-af60-644c854ee374.png)

## Desktop (please complete the following information)

- OS: Windows Server 2019 standard

- Browser - Chrome

- Version - 101.0.4951.54

**Comment by TheWitness** [comment]
You will have to provide more information like what's in your Cacti.log

**Comment by phipou** [comment]
Hi,
[Cacti.zip](https://github.com/Cacti/cacti/files/8710313/Cacti.zip)

Here are the log files.

**Comment by TheWitness** [comment]
I suggest you start over using either the 1.2.x branch or 1.2.21 as soon as it's out.

**Comment by phipou** [comment]
Thank you

**Comment by TheWitness** [comment]
I'll close this for now.  We can re-open if the issue persists.  Cacti 1.2.21 was released last night.

**Comment by bonj1987** [comment]
I just built  a 2019 windows server, downloaded the recent windows installer. im having the same problem. in addition, when i look at the cycle plugin, i see the proper graphs.. but in the "graphs" tab, white boxes. i know im pulling data, but the graphs tab isnt working properly.

**Comment by bonj1987** [comment]
to update.. my blank graphs look to only be the localhost as other devices are showing.. ill update later when i get more info.

**Comment by TheWitness** [comment]
This is a known issue with Windows RRDtool versions.  They don't support SVG.  So, you simply need to goto the Graph Templates page and change to SVG.  You can do it in one step.

**Comment by bonj1987** [comment]
mine is already set to PNG 

![PNG](https://user-images.githubusercontent.com/115038949/194072331-02bc02f4-4229-4c9a-a437-0207388a9aa3.PNG)

**Comment by TheWitness** [comment]
Go to the Graph Templates page and check each template. That's image is just a preset for new templates.
