### ISSUE TITLE
In "Installation Wizard" can not reflection date.timezone

### ISSUE THREAD

**Issue by YoheiZuho** [Cacti/cacti#4775]
# Describe the bug

In "Installation Wizard" can not reflection date.timezone
![image](https://user-images.githubusercontent.com/26687568/168420437-fdc272a6-bf65-447e-866f-1ea1a2f5850b.png)
date.timezone data entered in php.ini is not reflected. Changes in other items are reflected.

## Screenshots
![image](https://user-images.githubusercontent.com/26687568/168420437-fdc272a6-bf65-447e-866f-1ea1a2f5850b.png)
![image](https://user-images.githubusercontent.com/26687568/168420527-fce1a44b-36a6-44ff-8102-a3e38162380d.png)
The time zone data in php.ini is not reflected in the installation wizard.

## Server

- OS: Ubuntu 20.04 LTS
- PHP version : 7.4.29
- Browser : chrome
- CactiVersion : v1.2.21 [dbfab60](https://github.com/Cacti/cacti/commit/dbfab60fd3c735a69964204941726f0f09a528e7)

**Comment by YoheiZuho** [comment]
This bug did not occur in release/1.2.20.

**Comment by TheWitness** [comment]
Avoid develop is thats what you are using.

**Comment by TheWitness** [comment]
Remember to restart apache after making that setting change.  Post your images in English if possible.

**Comment by YoheiZuho** [comment]
I have restarted the web server but the problem has not been resolved.

**Comment by netniV** [comment]
Make sure you are editing the correct php.ini file as you may have multiple copies.

**Comment by YoheiZuho** [comment]
There is no possibility of copying, since the items other than timezone are indeed reflected.

**Comment by YoheiZuho** [comment]
This is not likely to be the case, as other versions reflect this and are correctly recognized.

**Comment by YoheiZuho** [comment]
Please forgive the unnatural English due to the use of machine translation.

**Comment by TheWitness** [comment]
Did you pull latest 1.2.21?  There was a similar, issue a few commits back.

**Comment by YoheiZuho** [comment]
Yes. The branch is 1.2.x and the commit hash is dbfab60fd3c735a69964204941726f0f09a528e7.

**Comment by TheWitness** [comment]
Did you pull latest 1.2.21?  There was a similar, issue a few commits back. Hmm, pretty close.  What is you timezone?

**Comment by YoheiZuho** [comment]
Asia/Tokyo

**Comment by TheWitness** [comment]
Did you update both php.ini files?  Ubuntu has two of them.  Afterwards you have to restart apache and pho-fpo is using that.

**Comment by YoheiZuho** [comment]
I had rewritten php.ini in cli and fpm. Of the two, the cli checks item correctly recognizes the timezone. Also, I forgot to mention that I am using Nginx and php7.4-fpm. phpinfo() confirms that the timezone is set correctly.

**Comment by YoheiZuho** [comment]
Hmmm. Uninstalled and reinstalled again, problem solved...
![image](https://user-images.githubusercontent.com/26687568/168479139-a8cacb99-6433-4062-9018-a425e9badc07.png)

**Comment by YoheiZuho** [comment]
I think it was a problem in our environment, I will close the issue.

**Comment by kto2038** [comment]
The same issue occured on my AlmaLinux 8.6 server with cacti-1.2.21-1.el8.noarch package in EPEL.

When I overwrote `/usr/share/cacti/include/layout.js` with `cacti-release-1.2.20/include/layout.js`, deleted all of Cacti cookies, and reloaded the page, this issue is resolved.

CactiTimeZone cookie seems to be related to this issue.
