### ISSUE TITLE
Datasources and graph names are not updated using CLI php scripts.

### ISSUE THREAD

**Issue by danielnavcom** [Cacti/cacti#4777]
# Describe the bug

Datasources and graph names are not updated.

## To Reproduce

cacti/cli
php poller_graphs_reapply_names.php --host-id=all
php poller_data_sources_reapply_names.php --host-id=all

it runs but does nothing.

## Expected behavior

Update data sources and graph names.

Cacti Version 1.2.20

Using: php fpm 7.4

**Comment by danielnavcom** [comment]
If thats so we will be waiting for the next release and close this.

**Comment by TheWitness** [comment]
Was released last night.

**Comment by danielnavcom** [comment]
Upgraded cati and spine to 1.2.21

CLI scripts still do not update the names of data sources and graphs.

Note: I have not updated the templates during upgrade.

**Comment by KnoAll** [comment]
I'm having a similar experience, does not update from web OR cli

**Comment by TheWitness** [comment]
Make sure that they are not orphans.  Anything in the Log?  Edit the Data Query and the Suggest Names.  Are they empty?  If they are, you may need to re-import the Data Queries, or device Templates.

**Comment by danielnavcom** [comment]
They are not empty and are not orphaned and nothing in the logs.

**Comment by TheWitness** [comment]
Daniel, you will have to dump your database and send my way to dig deeper.  Send to: thewitness at cacti dot net.

**Comment by KnoAll** [comment]
Same for me. Suggest Names not empty, none are orphaned, nothing in the logs.

**Comment by TheWitness** [comment]
Send along you database dump.

**Comment by danielnavcom** [comment]
Ok - go to each device - re-index the devices then run the cli scripts - works for me, updates DS and graph names fine.

So this should be marked as resolved.
