### ISSUE TITLE
Add devices sysName and sysLocation name as a Device description 

### ISSUE THREAD

**Issue by kasimanikandan** [Cacti/cacti#4778]
Hi, 

is there any way to customise device description ? i think by default Device SysName is taken as device description. 

we would like to keep device description as combination of sysname-location when devices added via auto discovery 

Example:
SysName: ROUTER001
Location: 1ABC-00-QW-001

Expected: SysName-sub(Location,0,3)
Device Description : ROUTER001-1ABC

Cacti Version : 1.2.18
Spine : 1.2.19
Mariadb : 10.3

Thanks,
Mani

**Comment by TheWitness** [comment]
Sounds like a feature request.
