### ISSUE TITLE
Cacti - 1.2.19 Windows version - Multiple Error in Log

### ISSUE THREAD

**Issue by phipou** [Cacti/cacti#4780]
# Describe the bug

A new Cacti install on Windows server. After Cacti install, there are multiples error in log file. I am unable to figure out what the error mean. Added device also contribute to error log.

## To Reproduce

After fresh install of Cacti

## Expected behavior

Unable to determine if error causes Cacti functioning properly.

## Screenshots
![Cacti Screenshoot](https://user-images.githubusercontent.com/104107518/169165560-54fcaed7-142b-4b14-a646-044c156b46a8.PNG)

Log file attached
[log.zip](https://github.com/Cacti/cacti/files/8721260/log.zip)

## Desktop (please complete the following information)

- Windows Server 2019

- Chrome

- 101.0.4951.67

**Comment by TheWitness** [comment]
Please test 1.2.21 which was released last night.

**Comment by TheWitness** [comment]
If you continue to have problems, we can re-open this.
