### ISSUE TITLE
Cacti - 1.2.21 Windows version - Graph not display. Showing icon on top left corner.

### ISSUE THREAD

**Issue by phipou** [Cacti/cacti#4783]
# Describe the bug

I am unable to see graph drawn. 

## To Reproduce

1. Fresh install of Cacti 1.2.21

2. Add device

3. Add device to default tree

4. Click on Graph tab

## Expected behavior
Unable to see graph drawn. No error message.

## Screenshots

Screen shot of graph
![1-2-21-nograph](https://user-images.githubusercontent.com/104107518/169339729-46d5c3a9-8aea-42d9-8ffb-7e71cd80af63.PNG)

Log file attached

[log.zip](https://github.com/Cacti/cacti/files/8731939/log.zip)

## Desktop (please complete the following information)

- Windows Server 2019

- Chrome

- Version 101.0.4951.67

Add any other context about the problem here
Encounter this issue first on Cacti version 1.2.20. I was suggested to user version 1.2.x
Install Cacti 1.2.19 - encountered lots of error in log file. Graph is working ok. I was suggested to install 1.2.21
Cacti1.2.21 has same issue with 1.2.20 where the graph is not displaying.

**Comment by TheWitness** [comment]
Cacti.log please.

**Comment by phipou** [comment]
Cacti.log included in initial post
[log.zip](https://github.com/Cacti/cacti/files/8734055/log.zip)
.

**Comment by TheWitness** [comment]
Switch the templates from SVG to PNG and see if they render.  Also, you can debug by going to `Console > Management > Graphs` and Editing a Graph and turning on Debug mode to see the Error.  Post that error.

**Comment by TheWitness** [comment]
Okay, then this is an RRDtool error.  Better think about Linux.  Better development platform IMHO, more scalable technology stack too.  Your call.  Thanks for reporting though.

**Comment by TheWitness** [comment]
Going to close this one, and then open a feature request to switch Windoz to PNG rendering, or remove SVG rendering, but we first need to know what is broken on Windoz.

**Comment by phipou** [comment]
Thank you
