### ISSUE TITLE
Remote poller error when adding new device, but we don't have remote pollers.

### ISSUE THREAD

**Issue by Juppers** [Cacti/cacti#4784]
Upgraded from 1.2.18 to 1.2.20 this morning and now get the below errors when adding a new device. The device does appear to add successfully. There are no and never have been remote pollers in this install. 

Popup window contains:
Some Actions failed
Note, we could not process all your actions. Details are below.
Remote Poller 0 is Down, you will need to perform a FullSync once it is up again
Save Successful.

Log shows:
05/19/2022 11:14:14 - CMDPHP PHP ERROR NOTICE Backtrace: (/host.php[62]:form_save(), /host.php[272]:api_device_save(), /lib/api_device.php[980]:api_device_update_host_template(), /lib/api_device.php[1077]:CactiErrorHandler())
05/19/2022 11:14:14 - ERROR PHP NOTICE: Undefined variable: device_id in file: /var/www/html/wan/lib/api_device.php on line: 1077

Any idea what could be causing it to not find the newly created device id when saving the new device, and how the remote poller error is being displayed when all instances of that message I can find are constrained by a if ($poller_id > 1) { conditional?

**Comment by andersonreloaded** [comment]
Having similar issue when upgraded from 1.1.38 to 1.2.20.

**Comment by bmfmancini** [comment]
This was corrected later after the 1.2.20 release

Upgrade to 1.2.21 with the latest code and you should be good

**Comment by TheWitness** [comment]
This issue should not be present in 1.2.21.  Please double check that you actually have the right install.  Something has to be wrong.

**Comment by Juppers** [comment]
The issue is corrected in 1.2.21.
