### ISSUE TITLE
Windows install does not support SVG rendering

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#4786]
# Describe the bug

We had a recent report that on Windows, SVG rendering does not work.  The installer should switch the Graph Template image format to PNG if the install is windows.

## Expected behavior

Graphs that work out of the box.

**Comment by stefanbrudny** [comment]
Does number of user on Windows still really justifies keeping the Windows platform supported?

**Comment by TheWitness** [comment]
A lot of students play with cacti still today in universities, and they don't all use a Mac.  I would never use it for production, but I used to back in 2004-2006.

**Comment by TheWitness** [comment]
Going to make this a build issue.  Currently the folks at rrdtool.org are now providing full Windoz binaries for RRDtool.  This fact has been raised with @BSOD2600.

**Comment by TheWitness** [comment]
I've handled this in the installer with this errant commit: https://github.com/Cacti/cacti/commit/116c60599a00ea39818caf48bf43b23f3438cb2b
