### ISSUE TITLE
Ubuntu Server 20.04 - Installation stops at Critical Binary Locations and Versions - See screenshot

### ISSUE THREAD

**Issue by stefanp2021** [Cacti/cacti#4787]
# Describe the bug

I'm trying to install Cacti v1.2.21 

## To Reproduce

Run through Installation

![2022-05-30 10_30_21-Window](https://user-images.githubusercontent.com/82162559/170952610-f69dde5d-25c0-4bd3-a2e6-4296e80c9f48.png)

I can't fix the errors, when I correct the paths, the check still fails.

All the programs have been installed.

## Screenshots

See below - 
## Desktop (please complete the following information)

- OS: Windows 10

- Browser: Microsoft Edge

- Version: 101.0.1210.53

**Comment by netniV** [comment]
Check your log files, see whether they give you any indication as to the failure.  Ubuntu/Debian are generally handled by the package consistently, are you doing a manual install? Do you definitely have the files present?

**Comment by TheWitness** [comment]
No feedback.
