### ISSUE TITLE
Some PHP errors after upgrade from 1.2.19 to 1.2.21

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#4788]
I use Cacti on Debian Buster with MariaDB with Spine pooler.
After upgrade there are many errors every pool.

```
2022/05/30 14:01:19 - CMDPHP SQL Backtrace: (/poller.php[671]:process_poller_output(), /lib/poller.php[584]:api_plugin_hook_function(), /lib/plugins.php[149]:api_plugin_run_plugin_hook_function(), /lib/plugins.php[266]:thold_poller_output(), /plugins/thold/includes/polling.php[263]:db_execute(), /lib/database.php[272]:db_execute_prepared())
--
2022/05/30 14:01:19 - CMDPHP ERROR: A DB Exec Failed!, Error: Duplicate entry '853-0' for key 'PRIMARY'
2022/05/30 14:01:19 - CMDPHP SQL Backtrace: (/poller.php[671]:process_poller_output(), /lib/poller.php[584]:api_plugin_hook_function(), /lib/plugins.php[149]:api_plugin_run_plugin_hook_function(), /lib/plugins.php[266]:thold_poller_output(), /plugins/thold/includes/polling.php[263]:db_execute(), /lib/database.php[272]:db_execute_prepared())
2022/05/30 14:01:19 - CMDPHP ERROR: A DB Exec Failed!, Error: Duplicate entry '526-0' for key 'PRIMARY'
```

and more of them:

```
2022/05/30 15:15:03 - CMDPHP SQL Backtrace: (/poller_boost.php[222]:boost_output_rrd_data(), /poller_boost.php[602]:boost_process_local_data_ids(), /poller_boost.php[775]:boost_get_rrd_filename_and_template(), /lib/boost.php[1008]:db_fetch_assoc_prepared(), /lib/database.php[613]:db_execute_prepared())
--
2022/05/30 15:15:03 - CMDPHP ERROR: A DB Row Failed!, Error: Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '='
2022/05/30 15:15:03 - CMDPHP SQL Backtrace: (/poller_boost.php[222]:boost_output_rrd_data(), /poller_boost.php[602]:boost_process_local_data_ids(), /poller_boost.php[775]:boost_get_rrd_filename_and_template(), /lib/boost.php[1008]:db_fetch_assoc_prepared(), /lib/database.php[613]:db_execute_prepared())
2022/05/30 15:15:03 - CMDPHP ERROR: A DB Row Failed!, Error: Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '='
2022/05/30 15:15:03 - CMDPHP SQL Backtrace: (/poller_boost.php[222]:boost_output_rrd_data(), /poller_boost.php[602]:boost_process_local_data_ids(), /poller_boost.php[775]:boost_get_rrd_filename_and_template(), /lib/boost.php[1008]:db_fetch_assoc_prepared(), /lib/database.php[613]:db_execute_prepared())
2022/05/30 15:15:03 - CMDPHP ERROR: A DB Row Failed!, Error: Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '='
2022/05/30 15:15:03 - CMDPHP SQL Backtrace: (/poller_boost.php[222]:boost_output_rrd_data(), /poller_boost.php[602]:boost_process_local_data_ids(), /poller_boost.php[775]:boost_get_rrd_filename_and_template(), /lib/boost.php[1008]:db_fetch_assoc_prepared(), /lib/database.php[613]:db_execute_prepared())
2022/05/30 15:15:03 - CMDPHP ERROR: A DB Row Failed!, Error: Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '='
2022/05/30 15:15:03 - CMDPHP SQL Backtrace: (/poller_boost.php[222]:boost_output_rrd_data(), /poller_boost.php[602]:boost_process_local_data_ids(), /poller_boost.php[775]:boost_get_rrd_filename_and_template(), /lib/boost.php[1008]:db_fetch_assoc_prepared(), /lib/database.php[613]:db_execute_prepared())
2022/05/30 15:15:03 - CMDPHP ERROR: A DB Row Failed!, Error: Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '='
2022/05/30 15:15:03 - CMDPHP SQL Backtrace: (/poller_boost.php[222]:boost_output_rrd_data(), /poller_boost.php[602]:boost_process_local_data_ids(), /poller_boost.php[775]:boost_get_rrd_filename_and_template(), /lib/boost.php[1008]:db_fetch_assoc_prepared(), /lib/database.php[613]:db_execute_prepared())
2022/05/30 15:15:03 - CMDPHP ERROR: A DB Row Failed!, Error: Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '='
2022/05/30 15:15:03 - CMDPHP SQL Backtrace: (/poller_boost.php[222]:boost_output_rrd_data(), /poller_boost.php[602]:boost_process_local_data_ids(), /poller_boost.php[775]:boost_get_rrd_filename_and_template(), /lib/boost.php[1008]:db_fetch_assoc_prepared(), /lib/database.php[613]:db_execute_prepared())
2022/05/30 15:15:03 - CMDPHP ERROR: A DB Row Failed!, Error: Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '='
```

last error is:
`BOOST ERROR: Failed to retrieve archive table name`

If there are duplicates we could create UNIQUE constraints.
**cli/audit_database.php show no errors**

What to do remove those errors?

**Comment by interduo** [comment]
I found similar issue in github cycle_plugin repository:
https://github.com/Cacti/plugin_cycle/issues/18#issuecomment-610196475
https://github.com/Cacti/plugin_cycle/issues/18#issuecomment-610448360
Thanks @TheWitness ;-)

The third error disappeared when I change the switch state in Performance Tab and then plug it on after next cycle.

Last thing that graphs stopped updating and no errors about that in clog.

I see some tables in DB:
| poller_output                          |
| poller_output_boost                    |
| poller_output_boost_1552465803         |
| poller_output_boost_1552466102         |
| poller_output_boost_1552466402         |
| poller_output_boost_1552466703         |
| poller_output_boost_1552467002         |
| poller_output_boost_1552467302         |
| poller_output_boost_1552467603         |
| poller_output_boost_1552467909         |
| poller_output_boost_1552468203         |
| poller_output_boost_1552468502         |
| poller_output_boost_1552468803         |
| poller_output_boost_1552469102         |
| poller_output_boost_1552469403         |
| poller_output_boost_1552469702         |
| poller_output_boost_1552470002         |
| poller_output_boost_1552470303         |
| poller_output_boost_1552470603         |
| poller_output_boost_1556367303         |
| poller_output_boost_1556367602         |
| poller_output_boost_arch_1653918301    |
| poller_output_boost_arch_1653918601    |
| poller_output_boost_arch_1653918903    |
| poller_output_boost_arch_1653919202    |
| poller_output_boost_local_data_ids     |
| poller_output_boost_processes 

How to manualy run rra updates?

**Comment by interduo** [comment]
@jdcoats How did You clean boosts cache (https://github.com/Cacti/cacti/issues/4391#issuecomment-913839671)?

**Comment by interduo** [comment]
I've cleaned those tables and recreated them from cacti.sql file - now graphs are updating.

For people reading this with the same problem there is a good sql query to do this fast:
```
SELECT concat('DROP TABLE IF EXISTS `', table_name, '`;')
FROM information_schema.tables
WHERE table_schema = 'cacti' ORDER BY table_name;
```
then You can copy+paste to console tables from poller_output and then recreate it from `doc/cacti.sql`.

I don't upgrade Cacti often but that upgrade didn't worked like a charm - it was cumulation of 5 different problems.

To be better we should:
- `audit_database.php` and `convert_tables.php` should also check collation for tables separatly not only for whole db,
- installer should check installed spine version if its installed,
- there should be an option to empty boost cache and recreate tables from UI (in utilities.php) or this should be done when turning off boosts switch in performance tab,
- repair "view_boost_status" code (it is always saying "Running" event that stops unexpectedly and we don't see it in processlist from command line)
- remove PHP Notice,

**Comment by TheWitness** [comment]
You need to increase you Max Heap Table Size in MariaDB if you plan on keeping that table MEMORY.  MEMORY is by far the most efficient for this table, but you have to manage the size.  If you can not do that, then stick with InnoDB, but that will impact performance.
