### ISSUE TITLE
include/global_session.php issue

### ISSUE THREAD

**Issue by wonderzone** [Cacti/cacti#479]
Sorry, I am not good at English and php......

Probrems occur when using reverse-proxy to set a path different from the backend.

For example...

```
server {
    listen x.x.x.x;
    :
    location /another {
        proxy_pass http://backend/cacti;
    }
}
```

Because `$_SERVER['REQUEST_URI']` is set to path of backend, `requestURI` is set to '/cacti/some/path'.
I think '/another/some/path' should be set to `requestURI`.

I fixed it **temporary** with following......
```diff
--- global_session.php.orig     2017-03-25 18:29:14.285000000 +0900
+++ global_session.php  2017-03-25 18:51:30.916000000 +0900
@@ -25,6 +25,7 @@
 global $config, $refresh;

 $script = basename($_SERVER['SCRIPT_NAME']);
+$wonderzone = preg_replace("|^/[^/]+/|", $config['url_path'], $_SERVER['REQUEST_URI']);
 if ($script == 'graph_view.php' || $script == 'graph.php') {
        if (isset($_SESSION['custom']) && $_SESSION['custom'] == true) {
                $refreshIsLogout = 'true';
@@ -87,5 +88,5 @@ if (isset($_SESSION['refresh'])) {
        var refreshMSeconds=<?php print $myrefresh['seconds']*1000;?>;
        var urlPath='<?php print $config['url_path'];?>';
        var previousPage='';
-       var requestURI='<?php print $_SERVER['REQUEST_URI'];?>';
+       var requestURI='<?php print $wonderzone;?>';
 </script>
```

Best Regards!

**Comment by wonderzone** [comment]
Hmm......I'm really sorry, I may not have explained well.

Simply, it may be better to set 'Alias /another /path/to/real/cacti/dir' on the backend config.

I did trial and error several times, but I could not think of a way to set "/another/some/path" correctly and completely for "requestURI". And browser requests for '/cacti/some/path' to reverse proxy, and got 404.

**Comment by wonderzone** [comment]
......And I'm sorry to misspelling 'problems'.

**Comment by cigamit** [comment]
My thoughts are this:

1) We have $config['url_path'], since you can't simply use that, we can.
2) Set a special config.php variable $rewrite_path = '/my/rewrite/path';
3) From inside where ever it's needed: $path = str_replace($config['url_path'], $config['rewrite_path'], $somepath);

What do you think?  Of course, if $config['url_path'] = '/', which happens, doing that change would not work.

**Comment by wonderzone** [comment]
Please let me explain as properly as possible.

First, my reverse proxy server is set to receive `http://reverseproxy/another`,and it is set to pass to `http://backend/cacti`. And `$config['url_path']` is set to `/another/`.

I accessed to `http://reverseproxy/another` with firefox browser, and logged in to cacti.

I got at cacti console screen, but URI on firefox location bar changed to `http://reverseproxy/cacti/` in a second.

Even clicked 'Graphs' tab on top navigation, firefox location bar changed to `http://reverseproxy/cacti/graph_view.php`.

I thought that why is path not 'another' but 'cacti', and where is 'cacti' come from, and I selected 'View source' menu on Firefox.

```
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

omg...

Next, I captured network packets, and found the following.

```
<script type='text/javascript'>
var theme='paw';
var refreshIsLogout=false;
var refreshPage='/cacti/graph_view.php?header=false';
var refreshMSeconds=300000;
var urlPath='/another/';
var previousPage='';
var requestURI='/cacti/graph_view.php';
</script>
```

I thought that where is this scripts come from. And I reached 'global_session.php'...Here at last, it leads to my first post.

It would be good just to replace `/cacti/` to `$config['url_path']` in the `$_SERVER['REQUEST_URI']`, but this is only for my environment.

`/cacti/` may be `/some/path/cacti`, Or may be `/`. I thought ways that can be solved smoothly and tried, and I sticked to it too much.

Right now, I think that the way to solve this problem smoothly is to decide only one simple rule "When using a reverse proxy, use the same path for reverse proxy, Cacti server, and `$config['url_path']` ".

Finally, I'm sorry for made a noise, but I'd like to close once this issue if no problems. May I close it by myself?
And I'm sorry if I have a rude expression. Please complaints to google translate......

**Comment by cigamit** [comment]
Gladly closing.  Happy to have the conversation.

**Comment by wonderzone** [comment]
Thanks for response! I'll do my best little by little!
