### ISSUE TITLE
Nectar Aggregate 95th emailed report broken

### ISSUE THREAD

**Issue by iskandarbasman** [Cacti/cacti#4791]
Refer to #3733 & #3702

This is old reported bug for Nectar emailed reported two year ago.
Is there any road map to the fix ?

**Comment by TheWitness** [comment]
Can you show me an image of the Graph before Emailing and the RRDtool create syntax, and then an image of what shows up?

**Comment by iskandarbasman** [comment]
Hi @TheWitness below was you previously mentioned in #3702 
![image](https://user-images.githubusercontent.com/67727557/173264554-02eff4f6-4e93-45ac-8092-d54e57ac861f.png)

**Issue still exists in cacti v1.2.21**
Below is the side by side comparison of the Nectar report preview and what I received in email.
Bug shows the 95th value in the emailed report duplicating the values above it.

"RRDtool create syntax" <- How and where should I do this.

![image](https://user-images.githubusercontent.com/67727557/173264846-28eecc81-0e44-4733-9fc5-8b6af3b5f9ca.png)

**Nectar report configuration**
![image](https://user-images.githubusercontent.com/67727557/173265308-3fbb6bec-042c-4ed1-82aa-8ae671ed8218.png)

![image](https://user-images.githubusercontent.com/67727557/173266104-d8ffa163-a3ae-45ce-ae55-936130679d13.png)

**Comment by netniV** [comment]
The bug there appears to be simply that the total isn't being cleared if all the values were zero so it's picking up the previous one?

**Comment by TheWitness** [comment]
@netniv, I think you may be right, @ronytomen had introduced a cache several years ago, and maybe the index on aggregates is gummed up.

The last number might simply be due to another sample towards the end increasing the nth ptile a smidge.

**Comment by iskandarbasman** [comment]
> Here is a test that I would like you to peform. In your setup edit the file `lib/graph_variables.php` and search for the word `static`. For each instance, comment out the `static` lines. Then, save the file and re-run your test. Let us know what comes back.

Wow.. I am seeing very positive results after commenting out the 3 instances of `static $vstats = array();` from `lib/graph_variables.php` 

It seems we have a fix for this issue.
No more bugged duplicated 95th percentile values in the nectar emailed report. (I will monitor further on my daily runs.)

Any side effect for commenting out those lines ?

**Comment by TheWitness** [comment]
Not on any well behaved modern system.

**Comment by TheWitness** [comment]
I've marked this resolved.  Grab the latest and keep testing.

**Comment by netniV** [comment]
My only concern is about it slowing the reporting down further since the same data is no longer cached.  But at least we have sorted the problem out.

**Comment by TheWitness** [comment]
It won't be a material slowdown as reports can only be so large.  Nor to the UI.
