### ISSUE TITLE
Cacti 1.2.18 - Boost Process Stats 

### ISSUE THREAD

**Issue by kasimanikandan** [Cacti/cacti#4794]
Hi Team,

Could you please help me to understand boost process statistics. We have cacti multi poller setup with one main collector and 3 remote collectors and approx. 1.5 Million data points (SNMP Gets) with every 5 mins polling. i have noticed boost is taking larger time to update rrd files ~ 21 mins.

Please find below boost settings.
![image](https://user-images.githubusercontent.com/85684729/171771788-44b6b16f-d635-4b9b-aa7a-dfcb84036539.png)

Boost performance stats.
![image](https://user-images.githubusercontent.com/85684729/171772115-53059f04-a8bc-47d8-ab03-e3a327b9d69f.png)

Could you please advise how we can improve this boost performance further ? 

Cacti 1.2.18
Spine 1.2.19
MariaDB 10.3

Thanks,
Mani

**Comment by bmfmancini** [comment]
You have set a huge amount of processes which I bet is also putting some
pressure on your dB

Also check your Io since that would be a bunch of writes to the rrd's

**Comment by kasimanikandan** [comment]
Thanks @bmfmancini for quick response.

i tired earlier with 5 process and its took ~ 25mins to update rrd's and later changed to 20 process which reduced ~ 4 to mins.  Could you please advise is there any optimal settings for better performance. 

Note: We have enough system resource to handle this work load and with current settings approx ~ 50 % of system resource  (CPU & memory) utilised. 

Thanks,
Mani

**Comment by TheWitness** [comment]
In our production we use 10 processes and update about 18m record updates every 45 minutes or so.  It takes about 1200 seconds as well.  That's on SSD's using GFS2 with three way replication for resiliency, so it's a little slow.  

On a single system FusionIO setup or similar, the times can drop significantly, but you will need lots of cores for that as with FusionIO, you can get 100% core bound with the rrdtool updates.  It's amazing tech.

On the settings side, increasing the maximum string length is material.  On Linux, a 16k byte string length is fine.  Not sure what yours is set to. 

Larry

**Comment by kasimanikandan** [comment]
if we increase the boost update frequency from 30 min to 1 or 2 hour then it will cause upto 2 hours delay in graphs update right ? please correct me if i'm wrong. unfortunately we cannot tolerate upto 2 hours delay. 

Thanks,
Mani

**Comment by bmfmancini** [comment]
It will only delay graphs not being viewed
In between boost cycles if you view a graph it will be updated at that time

Others will be updated during the boost update

**Comment by TheWitness** [comment]
@bmfmancini is correct.  So, long as the web server has the right permissions, this is not service impacting.

**Comment by kasimanikandan** [comment]
Thanks @bmfmancini  and @TheWitness .

We are using Redhat 7 (vmware) with Flash drive storage with 3.5 TB capacity.

i have changed RRD update frequency to 1 hour and kept other settings as below.

Boost Process : 10
Max Record: 20M
max string length 16k

what would the impact if we set max string length to max number for example 50k etc... will it reduce the rrd update time.

![image](https://user-images.githubusercontent.com/85684729/172779005-d99189a8-7d10-4829-ad79-525cf736eca3.png)

Could you please advise what is the actual meaning for main boost statistics and child process stats?
RRDUpdates:16438677 
TotalTime:1355.39 
get_records:9 
results_cycle:1332 
rrd_filename_and_template:17 
rrd_lastupdate:1292 
rrdupdate:3 
delete:2 


Thanks,
Mani

**Comment by TheWitness** [comment]
Report back your RRDtool version and the setting in cacti.  If you upgrade it or change the setting, report back the new numbers.

**Comment by kasimanikandan** [comment]
Thanks @TheWitness ... i'm using RRDTool version 1.7. could you please advise what kind of settings we need update in cacti ? 
Current settings as below:
![image](https://user-images.githubusercontent.com/85684729/172973906-e96de4c1-c7dd-4ec0-8442-a0f5b37cb188.png)

Thanks,
Mani

**Comment by TheWitness** [comment]
Report back your RRDtool version and the setting in cacti.  If you upgrade it or change the setting, report back the new numbers. Okay just checking.  Have to double check that we skip the last update check.  Maybe we aren't.  Hmm...

**Comment by TheWitness** [comment]
Well, I'm looking at the 1.2.21 code, and it's properly skipping.  There was a significant design change in the 1.2.15 - 1.2.21 versions.  I would have to see about 1.2.18.  I would suggest you upgrade as we had a number of quality issues between 1.2.15 and 1.2.21.  Right now 1.2.21 is pretty solid.  Just a few snafu's that are easy to cherry pick at this point in time.

**Comment by TheWitness** [comment]
Just checked the 1.2.18 boost had the performance updates.  However, I don't get your output.  The lastupdate time should be zero.  Your's should be slightly higher than zero, but no 1200 seconds.  My example below is showing small because I just had flushed it a few minutes before.  But I'm certain the lastupdate time was a close to zero as you can get.

![image](https://user-images.githubusercontent.com/1439914/173157650-648d9d3a-99db-4e16-94ea-13d8caf8052e.png)

**Comment by TheWitness** [comment]
There may have been a display bug though.  Instead of me digging in, I'm just simply going to suggest you upgrade.

**Comment by TheWitness** [comment]
I'm going to close this, but you can still comment and discuss things.

**Comment by kasimanikandan** [comment]
Thanks @TheWitness .. could you please share the details of last_update check ? what last_update check is doing ?
is there any detailed design or process flow document for boost process ?

Thanks,
Mani

**Comment by TheWitness** [comment]
The last update check used to be performed to prevent boost update failures.  It had to check the last update time for each RRDfile and then only include samples after that date.  Then, in RRDtool 1.5+, an RRDtool option was added to simply skip any updates that came in in the past, which allowed us to reduce the number of turns on the file system to perform an update.  So, all that is left in that function is the nano seconds it takes to perform the evaluation for each data source now.  Should be very close to zero.
