### ISSUE TITLE
Cacti 1.0.x: RRDTool Says: ERROR: I don't understand ...

### ISSUE THREAD

**Issue by ndhami23** [Cacti/cacti#480]
In  a graph tree i can see that graph is plotting but when i click a gear button i am getting RRDTool ERROR. Can you please suggest a hint to fix it.

``
![image](https://cloud.githubusercontent.com/assets/13357925/24322160/13740624-1186-11e7-945c-60c6c982ddb6.png)

![image](https://cloud.githubusercontent.com/assets/13357925/24322163/20e592e6-1186-11e7-954b-edb9bfd4b741.png)

**Comment by cigamit** [comment]
What Cacti version?

**Comment by ndhami23** [comment]
1.0.3

**Comment by cigamit** [comment]
It's a problem with the colon in the hrule for the graph template.  There are a few solutions.  Easiest is to upgrade to 1.1.0, and then apply the lib/rrd.php from the GitHub development branch, or wait till sometime tomorrow, when we release 1.1.1.

**Comment by ndhami23** [comment]
thx cigamit (y)... I will wait for newer release!
