### ISSUE TITLE
Search in tree view unusable on sizeable installations

### ISSUE THREAD

**Issue by rb83** [Cacti/cacti#4806]
While trying to use the web search field (tree view) on one of our smaller cacti installations, we get consistent timeouts.
This is an installation with ~6k devices and ~52k graphs.

So far, we've traced the issue back to [the SQL query beginning on line 54 in graph_view.php](https://github.com/Cacti/cacti/blob/1235955857d7c4242a19f8b552586b069dc9012a/graph_view.php#L54). Executing this query manually through mysql demonstrates that it would take ages to complete (didn't wait for completion).

`audit_database.php` doesn't show any complaints.

## To Reproduce

1. Go to tree view on a sizeable installation
2. Hit 'Search' with a trivial string

## Additional context

- Cacti: 1.2.21
- OS: RHEL7
- DB: MariaDB 5.5

**Comment by rb83** [comment]
Running the SQL query with some patience shows a metric ton of duplicated rows. The query is missing a DISTINCT at the very least, and needs some closer inspection. The multiple joins are a bit smelly, and right now it looks like joining by `site_id` lets everything explode. `site_id` in this context a bit of a headscratcher anyway, since it essentially short-circuits the query to return the whole of `graph_tree_items`, even when limiting the query to a single node.

**Comment by rb83** [comment]
Also,
```sql
LEFT JOIN graph_templates_graph AS gtg
ON gtg.local_graph_id=gti.local_graph_id AND gtg.local_graph_id>0
```

is useless to my understanding, and can simply be written as

```sql
WHERE gti.local_graph_id>0
```
to the same effect, retaining the JOIN, but possibly giving the query planner the chance to omit the join to begin with (but that would need some more confirmation)

**Comment by rb83** [comment]
We've simplified the query as follows:
```sql
SELECT gti.parent, gti.graph_tree_id
FROM graph_tree_items AS gti
LEFT JOIN host AS h
ON h.id=gti.host_id
LEFT JOIN graph_templates_graph AS gtg
ON gtg.local_graph_id=gti.local_graph_id AND gtg.local_graph_id > 0
WHERE 
  gtg.title_cache LIKE ?
OR h.description LIKE ?
OR h.hostname LIKE ?
OR gti.title LIKE ?
```
In essence, the doubled join with `host` on `site_id` was removed. The reasoning behind this join is unclear, and to my current understanding of the DB schema this would return all graph_tree_items that have the same site_id as the host (or  host description, et cetera...) matching in the where clause. Which would return a cartesian product from hell, or at least have the query planner deal with it.

For us, this restores functionality, and searches through the web interfaces are now super fast again.

Not sure if this breaks functionality in other places, but if it's good, I'd prepare a quick PR later on.

**Comment by TheWitness** [comment]
Communicate you changes through a pull request please. I can comment there.

**Comment by rb83** [comment]
> Communicate you changes through a pull request please. I can comment there.

Done as requested

**Comment by TheWitness** [comment]
I've made a slight change to your pull request.  If you would please test it and report back, I would appreciate it.
