### ISSUE TITLE
Pre-Installation Checks Php Recommendations (Web) date.timezonne issue

### ISSUE THREAD

**Issue by BaptisteVlt** [Cacti/cacti#4807]
I just finish to install cacti on Centos 7. I just arrive on the cacti web page to finish the installation. 
There I see that I've a lot of "warning" and "error" message, I'm doing my best to fix all of them to have the cleanest cacti installation possible. 
But there is one error that I can't fix : 
Indeed for the php recommendations (web), date.timezone : error : A valid timezone ... 
![image](https://user-images.githubusercontent.com/45470774/172367179-5e738fc5-469b-440e-ab69-432c036e160b.png)
I've only one php.ini file : etc/php.ini and I don't have this error for php recommendations (cli).
Thank you in advance for your help !

**Comment by netniV** [comment]
You will likely have another one specifically for apache.  Check your configuration files for PHPINIDir as this can alter where the ini file will be read from.
