### ISSUE TITLE
The ping result in device page is always timeout (v1.1.0)

### ISSUE THREAD

**Issue by skyjou** [Cacti/cacti#481]
I upgrade my cacti to 1.1.0 recently, and I find the device which detection method is "TCP Ping" always show time out result at the top of device page.

But the detection result of spine is good.

I try to replace the lib/ping.php with old version (0.8.8c), and it works normally.

**Comment by cigamit** [comment]
Interesting.  Can you investigate further and see if you can find the issue and then submit a pull request?

**Comment by cigamit** [comment]
It's working for me, so you have a lot of work ahead of you.  You may end up having to run an strace to determine the root cause.

**Comment by smiles1969** [comment]
I'm getting the same. Contacting device with the updating icon that never completes. My production box was on 1.0.6, and working fine. Upgraded to 1.1.0 and it's also broke now. It never resolves the SNMP sysinfo now, just says Contacting Device indefinitely. SPINE continues to poll fine, graphs are populating, and I can snmpwalk all devices just fine.

**Comment by skyjou** [comment]
I install cacti 1.1.0 in a new Ubuntu 16.04 to make sure if there is any problem in my production environment that ping.php not work normally. And I see the same problem, both of TCP and UDP ping status are always time out. I compare two versions of ping.php, and I modify the following line in new version:

470                 $w = $f = array();
471                 $r = array($this->socket);

-->

470                 $f = array();
471                 $r = $w = array($this->socket);

It's working now. Is this the root cause?

**Comment by cigamit** [comment]
Well that is very odd.  Will review.

**Comment by cigamit** [comment]
This should not be the case.  What OS type and PHP version are you using.  We don't need to set the write socket as we are only reading from the socked.  So, we need more information as this must be some bug in PHP.

**Comment by browniebraun** [comment]
Both, TCP and UDP, are working fine on my test server running Ubuntu 16.04 and Cacti 1.1.0

**Comment by skyjou** [comment]
My production environment is Ubuntu 12.04, and PHP version is 7.1.3.

**Comment by cigamit** [comment]
So, just to confirm how did you install PHP 7.1.3 and is authentication/login working on that release?

**Comment by skyjou** [comment]
I install it from ppa:ondrej/php. Authentication and login are working fine.

**Comment by cigamit** [comment]
This sounds like a PHP issue as the write descriptor can and should be null when performing a select against a read operation.  Is there anything in your Cacti log when you revert to the 1.1.1 version?

**Comment by skyjou** [comment]
I upgrade Cacti to 1.1.1, and I do not see suspicious log in cacti.log.

**Comment by cigamit** [comment]
But the error still remains right?

**Comment by skyjou** [comment]
Yes, it's always timeout.

**Comment by browniebraun** [comment]
Ok, I have PHP 7.0.15 running on my box.

**Comment by cigamit** [comment]
I suspect this is a PHP 7.1.3 issue.  There were some recent socket/stream changes.  My guess is that they blew this up.  Can you install an earlier version of PHP, on that is not so bleeding edge?

Some possible candidates.

7.1.0
Core:
    Fixed bug #72857 (stream_socket_recvfrom read access violation).
    Implemented #51879 stream context socket option tcp_nodelay (Joe)
Streams:
    Fixed bug #73586 (php_user_filter::$stream is not set to the stream the filter is working on).
    Fixed bug #72853 (stream_set_blocking doesn't work).
    Fixed bug #72743 (Out-of-bound read in php_stream_filter_create).
    Implemented FR #27814 (Multiple small packets send for HTTP request).
    Fixed bug #72764 (ftps:// opendir wrapper data channel encryption fails with IIS FTP 7.5, 8.5).
    Fixed bug #72810 (Missing SKIP_ONLINE_TESTS checks).
    Fixed bug #41021 (Problems with the ftps wrapper).
    Fixed bug #54431 (opendir() does not work with ftps:// wrapper).
    Fixed bug #72667 (opendir() with ftp:// attempts to open data stream for non-existent directories).
    Fixed bug #72771 (ftps:// wrapper is vulnerable to protocol downgrade attack).
    Fixed bug #72534 (stream_socket_get_name crashes).
    Fixed bug #72439 (Stream socket with remote address leads to a segmentation fault).

And under the category 'streams', very closely related to sockets a whole rash of changes in 7.1.

7.1.3
    Fixed bug #73496 (Invalid memory access in zend_inline_hash_func).
    Fixed bug #74090 (stream_get_contents maxlength>-1 returns empty string).

It may be a blocking issue too.  But a write FD should not have to be set when you fwrite() and then wait on a read FD.

**Comment by skyjou** [comment]
It seems like TCP ping is working on telnet service (port 23). But it always reports timeout result on http service (port 80, 443).

**Comment by cigamit** [comment]
Okay, this must be a web configuration issue and not a Cacti issue.  I know a user, I think it was smiles1969 posted a bug report on how to configure apache to allow such connections.  We should likely make a Wiki article out of it.  I'm going to close. However, please review Issue #185.  If you feel like creating a Wiki article out of it we would glad to have you contribute.

**Comment by skyjou** [comment]
I don't enable selinux on my server or laptop, I do not find error message in php_errors.log, too.

The testing result of nc is correct.

root@cacti:~# su - www-data -c "nc -zv 172.31.252.2 80"
Connection to 172.31.252.2 80 port [tcp/http] succeeded!

The target device is a FortiAP.

Is that possible to get same result from ping.php? How can I modify my server config?

**Comment by interduo** [comment]
I can confirm this problem in Debian 10 Buster.

I did:
```
<?php
print 'ping test start';
$result = shell_exec('/bin/ping -c3 172.20.2.42 2>&1');
print "<pre>$result</pre>";
print 'ping test end';
?>
```

I get:
```
ping test start
ping: socket: Operation not permitted
ping test end
```

**Comment by TheWitness** [comment]
https://serverfault.com/questions/372975/ping-sendmsg-operation-not-permitted-error-after-installing-iptables-on-arch-g#372979

**Comment by TheWitness** [comment]
Also this.  This is not a cacti bug. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=832999
