### ISSUE TITLE
When importing, make it possible to only import certain components

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#4820]
# Feature Request

## Is your feature request related to a problem? Please describe

It is not possible to selectively import Cacti Template components

## Describe the solution you'd like

Provide the ability for a plugin author to be able to selectively import certain components from a package.  This might include Graph Templates, Data Queries, Data Sources, etc.

## Describe alternatives you've considered

N/A

## Additional context

Required for the public release of the Packaging Plugin

**Comment by TheWitness** [comment]
Going to keep this open until I can fully test out the plugin.  In theory this is enough.

**Comment by netniV** [comment]
My only concern would be someone not realising what they are doing and wondering why a template breaks because of a partial import, but I can see the benefits too.

**Comment by TheWitness** [comment]
Once I complete the package plugin, you will be able to see how this will work.  You are right though, there might be some unintended consequences, but not for the trained eye.  Anyway, more to follow.

**Comment by TheWitness** [comment]
Taking off resolved until QA is complete
