### ISSUE TITLE
Automation Section - adding not visible

### ISSUE THREAD

**Issue by jkw117** [Cacti/cacti#4821]
I am running the latest version 1.2.21 Under the automation section the icons for adding networks, graph rules, tree rules (basically the whole section)  are not visible.  But they are their if I hover over them they display the description, and I can use them.  This was a fresh install, and I copied data over from an old install.  So it's possible I messed something up, but I didn't use this section in the past, and I don't know how I could've messed it up.

**Comment by TheWitness** [comment]
No, it's a setting to compress the page.  If you want to see old style, you can display them onder `Console > Configuration > Settings > General > Other Settings > Show Form/Setting Help Inline`.
