### ISSUE TITLE
Graph zoom not working on 1.2.21

### ISSUE THREAD

**Issue by netadmin101** [Cacti/cacti#4824]
# Describe the bug

Mouse-over zoom in tree mode view does not appear to be working correctly in version 1.2.21.  I just upgraded from 1.2.18 and it was working fine there.

## To Reproduce

1. Go to the Graphs tab

2. Click on a host or tree

3. Hover over a graph and then click and drag to attempt to zoom

4. The mouse does not change to the zoom style plus sign.  When I try to click and drag, it tries to drag the whole graph as if I were trying to save the image to a folder.

## Expected behavior

I expect for the mouse to change from a pointer to a zoom control and highlight a timeframe to look at.

## Screenshots

Screenshot of dragging while on the graph
![image](https://user-images.githubusercontent.com/11315980/173833084-9255a65e-8fba-4cc9-83f1-d84ea78485a4.png)

## Desktop (please complete the following information)

- OS: Windows 10

- Browser: Tested in Chrome, Firefox, Edge

- Version: 1.2.21

## Smartphone (please complete the following information)

n/a

**Comment by TheWitness** [comment]
You need to edit your user and enable graph actions drill down permission. This is not a bug.

**Comment by netadmin101** [comment]
Ok... That's odd.  So then is it a bug that this permission got changed during an upgrade?  It's not like I went and took away permissions for all my users.  I've confirmed that adding the "Show Graph Action Icons" permission restores the zoom features.

**Comment by TheWitness** [comment]
Yea, was a bit of a mess.  All permissions are permissive and we created one the was restrictive, which broke the rules. Easy fix for anyone though.

**Comment by netadmin101** [comment]
Sounds good, thanks for the info.
