### ISSUE TITLE
installer could have links to docs.cacti.net

### ISSUE THREAD

**Issue by xmacan** [Cacti/cacti#4827]
If forum is very often query about mysql poplate timezone, ...
There could be link (or more links) to official documentation 
https://docs.cacti.net/Install-Under-CentOS_LAMP.md

**Comment by TheWitness** [comment]
Good idea!

**Comment by netniV** [comment]
This should use a client side check to see if the remote site is available.  If so, go there, otherwise, use the local if it's available (which can be determined server side).
