### ISSUE TITLE
Cactid lacks a default for $database_ssl

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#4831]
# Describe the bug

If a user forget's to set $database_ssl = true|false, Cactid throws an error

## Expected behavior

Less bugs

**Comment by cutehameed** [comment]
how to set $database_ssl = true|false ?

**Comment by TheWitness** [comment]
In your `config.php`

**Comment by cutehameed** [comment]
@TheWitness Apologies! As i am newbie on linux. Kindly tell me complete file path so that i can edit via vim editor.

**Comment by TheWitness** [comment]
In a normal install it's `/var/www/html/cacti/include/config.php`, for Debian, it might be something like `/usr/share/site/cacti/include/config.php` or it could even be in `/etc/cacti`.

**Comment by cutehameed** [comment]
Still not working.... Still getting below error


CMDPHP PHP ERROR NOTICE Backtrace: (/cactid.php[150]:db_check_reconnect(), /cactid.php[268]:CactiErrorHandler())
ERROR PHP NOTICE: Undefined variable: database_retries in file: /var/www/html/cacti/cactid.php on line: 268

**Comment by cutehameed** [comment]
@TheWitness Sorry unable to understand. Should i change config.php.dist?

**Comment by cutehameed** [comment]
@TheWitness is it possible to install old version of cacti in ubuntu 20?

**Comment by cutehameed** [comment]
@TheWitness I will appericiate and request you to take me on board via anydesk and help me to get rid of the issue.

**Comment by TheWitness** [comment]
Read the documentation on how to install Cacti.  It's not that complicated.

**Comment by cutehameed** [comment]
ok. thanks alot for support. issue stands resolved.
