### ISSUE TITLE
csv export

### ISSUE THREAD

**Issue by dreamhighhd** [Cacti/cacti#4839]
There is no "CSV export" function in the cacti icon, and the original data cannot be exported.

version:1.2.21
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/40293011/174760734-f43d8557-6740-43eb-8722-868f72849c06.png">
version:0.8.7
![image](https://user-images.githubusercontent.com/40293011/174761077-54d45195-af92-4b41-a1b3-d36b2d10e7fa.png)

**Comment by netniV** [comment]
This is actually a duplicate bug report and was caused by a third-party PR that made the permission become inverted.  Something we have had to live with for the past year or people reporting it.  

Check out the user permissions and you'll find it's not enabled to show the icons.

**Comment by dreamhighhd** [comment]
I've found it thank you

**Comment by TheWitness** [comment]
Just for anyone else asking.  We get this one a lot.
![image](https://user-images.githubusercontent.com/1439914/174932491-ba3b8228-9f68-4e5d-8d1a-7f0d9804fef0.png)

**Comment by TheWitness** [comment]
`Show Graph Action Icons`
