### ISSUE TITLE
Web Basic authentication not creating template user

### ISSUE THREAD

**Issue by robwdwd** [Cacti/cacti#4840]
# Describe the bug

Currently on cacti 1.2.21 and this seems to have broken web basic authentication. When a user authenticates with web basic the template user is not used to copy the user because the auth method is being reset and cacti us treating it as a local user. This does not affect users logging in with an existing account.

## To Reproduce

This happens every time a new user logs in without an existing account, that must be copied from the template user.

## Expected behavior

User is created on first login from template user.

## Additional context

I tracked the issue down to this bit of code in auth_login.php. $frv_realm is set here, but I am presuming since web basic auth won't have a form this will use the default 0.

```php
$frv_realm     = get_nfilter_request_var('realm', 0); // The dropdown value for realm
```

It then hits this bit of code which resets $auth_method to local because $auth_method = 2 and $frv_realm = 0

```php
if (get_nfilter_request_var('action') == 'login' || $auth_method == 2) {
  if ($auth_method >= 2 && $frv_realm <= 1) {
    // User picked 'local' from dropdown;
    $auth_method = 1;
  } else {
    $auth_method = read_config_option('auth_method');
  }
```

Looking into lib/auth.php and auth_get_username() if I set the realm here to 2 it fixes the issue.

```php
  if ($auth_method == 2) {
    $username = get_basic_auth_username();

    /* Get the Web Basic Auth username and set action so we login right away */
    set_request_var('action', 'login');
    set_request_var('realm', 2);

  } elseif (get_nfilter_request_var('action') == 'login') {
    $username = get_nfilter_request_var('login_username');
  } else {
    $username = '';
```

**Comment by TheWitness** [comment]
@robwdwd first thanks for reporting.  Is it just the first login problem and picking the template user to copy?

Before you make a pull request, pull the latest 1.2.x.  There have already been some bugs reported.

**Comment by TheWitness** [comment]
https://github.com/Cacti/cacti/commit/ea067041c0644ad2e7ea6e4f757a1c6bdd934fe1

**Comment by TheWitness** [comment]
I'm thinking that this is wrong.  Should be `$auth_method > 2`

```php
if (get_nfilter_request_var('action') == 'login' || $auth_method == 2) {
  if ($auth_method >= 2 && $frv_realm <= 1) {
    // User picked 'local' from dropdown;
    $auth_method = 1;
  } else {
    $auth_method = read_config_option('auth_method');
  }
```

**Comment by TheWitness** [comment]
Try that out and report back.

**Comment by robwdwd** [comment]
That works! :)
