### ISSUE TITLE
Can't create graph on cacti 1.2.20

### ISSUE THREAD

**Issue by manhvu1997** [Cacti/cacti#4842]
Hi everyone
I installed cacti 1.2.20 on ubuntu. When I created the graph, the rrdtool say: "failed to open data file, poller may not have run yet". So, I check the log file and faced the error like image below:
![image](https://user-images.githubusercontent.com/58839875/175003823-80a62fc2-4cf6-4dca-8518-46d63cb29998.png)
![image](https://user-images.githubusercontent.com/58839875/175003863-724c33ad-04a3-4062-938a-5df6f997b341.png)
Can you help me to fix that ?

**Comment by manhvu1997** [comment]
Sorry for the late reply netniV
I checked the connection, and resources of my database server, and all are normal. I tried to increase the timeout of the read and write action in my database configuration, but it still fails. Can you help me to suggest how can I solve it ?
set @@global.net_write_timeout = 3600;
Query OK, 0 rows affected (0.00 sec)
set @@global.net_read_timeout = 3600; 
Query OK, 0 rows affected (0.00 sec)

**Comment by manhvu1997** [comment]
The log fail:
![image](https://user-images.githubusercontent.com/58839875/175854964-6ef45c53-36f0-42bf-93c9-cf0cd780d888.png)

**Comment by netniV** [comment]
That is your cacti log, not your MySQL one.

**Comment by manhvu1997** [comment]
Thank you all for your support
I found the solution, my MariaDB cluster is gone away because the number of requests to them is so much. So my solution is to increase the thread of connecting to my MariaDB cluster

**Comment by TheWitness** [comment]
Were you using Galera or Replication?

**Comment by manhvu1997** [comment]
I'm using the Galera cluster, Can you suggest for me which one has the better performance?

**Comment by TheWitness** [comment]
Galera is good so long as it's main function is for Cacti.  You should consider async parallel replication with a reasonable number of threads though.  There are other tunables as well.  Using NVMe and big interfaces speeds things up.  But again, if it's only cacti, you might even work fine with defaults.
