### ISSUE TITLE
During install screen tells me 

### ISSUE THREAD

**Issue by goosej13** [Cacti/cacti#4843]
# Describe the bug
During the upgrade after all issues are completed with the install it gets to the progress page and just keeps telling me that the EULA was not accepted 

https://v21cacpl01/cacti/install/install.php?data={%22Step%22:%2210%22,%22Eula%22:true}

## To Reproduce

Following this install guide AS well as using yum install cacti (both methods produce the same result)

https://files.cacti.net/docs/html/unix_configure_cacti.html

I then login to cacti using local admin account to complete the install

First page - Asks for Theme/Language and Accept GPL

I can easily change theme and click accept on GPL but Language shows blank at first and when I select any language it just shows up blank. ( I thought this was weird it would never show the language name ) 

I click begin upgrade -- Go through all the fixes it recommends turn everything that is orange or red into a good condition. 

Get to the step 10 where there is a checkbox to begin upgrade. Click it.. 

Then it goes to a page where it just keeps refreshing telling me that I didn't accept EULA and never gets past 0 percent of the install

I have done the upgrade again (prob 10 times now after restoring my snapshot) and same result after making sure I clicked that Accept GPL on first page

I have a dev server with the exact same settings and it worked successfully.. The only difference is that the DEV server doesn't have all the graphs/sources/ discovered and running. 

RHEL 7.9
PHP 5.4.16

**Comment by TheWitness** [comment]
Are there any errors in your cacti.log?

**Comment by goosej13** [comment]
![image](https://user-images.githubusercontent.com/108091612/175390601-d043b791-cdc5-4027-b338-466384906c16.png)


tail -n 100 cacti/cacti.log
2022/06/23 16:10:43 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:10:43 - CMDPHP SQL Backtrace:  (/install/step_json.php[65]:Installer->__construct(), /lib/installer.php[174]:Installer->setDefaults(), /lib/installer.php[345]:Installer->setTemplates(), /lib/installer.php[1159]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:10:43 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:10:43 - CMDPHP SQL Backtrace:  (/install/step_json.php[65]:Installer->__construct(), /lib/installer.php[174]:Installer->setDefaults(), /lib/installer.php[345]:Installer->setTemplates(), /lib/installer.php[1159]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:10:43 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:10:43 - CMDPHP SQL Backtrace:  (/install/step_json.php[65]:Installer->__construct(), /lib/installer.php[174]:Installer->setDefaults(), /lib/installer.php[345]:Installer->setTemplates(), /lib/installer.php[1159]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:10:43 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:10:43 - CMDPHP SQL Backtrace:  (/install/step_json.php[65]:Installer->__construct(), /lib/installer.php[174]:Installer->setDefaults(), /lib/installer.php[345]:Installer->setTemplates(), /lib/installer.php[1159]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:10:43 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:10:43 - CMDPHP SQL Backtrace:  (/install/step_json.php[65]:Installer->__construct(), /lib/installer.php[174]:Installer->setDefaults(), /lib/installer.php[345]:Installer->setTemplates(), /lib/installer.php[1159]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:10:43 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:10:43 - CMDPHP SQL Backtrace:  (/install/step_json.php[65]:Installer->__construct(), /lib/installer.php[174]:Installer->setDefaults(), /lib/installer.php[345]:Installer->setTemplates(), /lib/installer.php[1159]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:10:43 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:10:43 - CMDPHP SQL Backtrace:  (/install/step_json.php[65]:Installer->__construct(), /lib/installer.php[174]:Installer->setDefaults(), /lib/installer.php[345]:Installer->setTemplates(), /lib/installer.php[1159]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:10:43 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:10:43 - CMDPHP SQL Backtrace:  (/install/step_json.php[65]:Installer->__construct(), /lib/installer.php[174]:Installer->setDefaults(), /lib/installer.php[345]:Installer->setTemplates(), /lib/installer.php[1159]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:10:43 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:10:43 - CMDPHP SQL Backtrace:  (/install/step_json.php[65]:Installer->__construct(), /lib/installer.php[174]:Installer->setDefaults(), /lib/installer.php[345]:Installer->setTemplates(), /lib/installer.php[1176]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:10:43 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:10:43 - CMDPHP SQL Backtrace:  (/install/step_json.php[65]:Installer->__construct(), /lib/installer.php[174]:Installer->setDefaults(), /lib/installer.php[346]:Installer->setProfile(), /lib/installer.php[831]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:10:43 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:10:43 - CMDPHP SQL Backtrace:  (/install/step_json.php[65]:Installer->__construct(), /lib/installer.php[174]:Installer->setDefaults(), /lib/installer.php[347]:Installer->setAutomationMode(), /lib/installer.php[867]:Installer->setTrueFalse(), /lib/installer.php[380]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:10:43 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:10:43 - CMDPHP SQL Backtrace:  (/install/step_json.php[65]:Installer->__construct(), /lib/installer.php[174]:Installer->setDefaults(), /lib/installer.php[349]:Installer->setAutomationRange(), /lib/installer.php[958]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:10:43 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:10:43 - CMDPHP SQL Backtrace:  (/install/step_json.php[65]:Installer->__construct(), /lib/installer.php[174]:Installer->setDefaults(), /lib/installer.php[350]:Installer->setRRDVersion(), /lib/installer.php[666]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:10:43 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:10:43 - CMDPHP SQL Backtrace:  (/install/step_json.php[65]:Installer->__construct(), /lib/installer.php[174]:Installer->setDefaults(), /lib/installer.php[350]:Installer->setRRDVersion(), /lib/installer.php[667]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:10:43 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:10:43 - CMDPHP SQL Backtrace:  (/install/step_json.php[65]:Installer->__construct(), /lib/installer.php[174]:Installer->setDefaults(), /lib/installer.php[352]:Installer->setMode(), /lib/installer.php[1321]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:10:43 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:10:43 - CMDPHP SQL Backtrace:  (/install/step_json.php[65]:Installer->__construct(), /lib/installer.php[174]:Installer->setDefaults(), /lib/installer.php[356]:Installer->processParameters(), /lib/installer.php[237]:Installer->setStep(), /lib/installer.php[1378]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:10:43 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:10:43 - CMDPHP SQL Backtrace:  (/install/step_json.php[65]:Installer->__construct(), /lib/installer.php[174]:Installer->setDefaults(), /lib/installer.php[356]:Installer->processParameters(), /lib/installer.php[237]:Installer->setStep(), /lib/installer.php[1380]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:10:43 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:10:43 - CMDPHP SQL Backtrace:  (/install/step_json.php[65]:Installer->__construct(), /lib/installer.php[174]:Installer->setDefaults(), /lib/installer.php[356]:Installer->processParameters(), /lib/installer.php[237]:Installer->setStep(), /lib/installer.php[1381]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:10:43 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:10:43 - CMDPHP SQL Backtrace:  (/install/step_json.php[65]:Installer->__construct(), /lib/installer.php[174]:Installer->setDefaults(), /lib/installer.php[356]:Installer->processParameters(), /lib/installer.php[247]:Installer->setEula(), /lib/installer.php[604]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:10:43 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:10:43 - CMDPHP SQL Backtrace:  (/install/step_json.php[66]:json_encode(), Installer->jsonSerialize(), /lib/installer.php[184]:Installer->processCurrentStep(), /lib/installer.php[1624]:Installer->processStepInstall(), /lib/installer.php[2647]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:10:43 - INSTALL: always: Spawning background process: /bin/php '/usr/share/cacti/install/background.php' 1656015043.3676
2022/06/23 16:10:43 - INSTALL: Checking arguments
2022/06/23 16:10:43 - INSTALL: always: Install aborted due to no EULA acceptance
2022/06/23 16:12:41 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:12:41 - CMDPHP SQL Backtrace:  (/install/step_json.php[65]:Installer->__construct(), /lib/installer.php[151]:Installer->setStep(), /lib/installer.php[1378]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:12:41 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:12:41 - CMDPHP SQL Backtrace:  (/install/step_json.php[65]:Installer->__construct(), /lib/installer.php[151]:Installer->setStep(), /lib/installer.php[1380]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:12:41 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:12:41 - CMDPHP SQL Backtrace:  (/install/step_json.php[65]:Installer->__construct(), /lib/installer.php[151]:Installer->setStep(), /lib/installer.php[1381]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:12:41 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:12:41 - CMDPHP SQL Backtrace:  (/install/step_json.php[65]:Installer->__construct(), /lib/installer.php[166]:Installer->setLanguage(), /lib/installer.php[580]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:12:41 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:12:41 - CMDPHP SQL Backtrace:  (/install/step_json.php[65]:Installer->__construct(), /lib/installer.php[167]:Installer->setTheme(), /lib/installer.php[702]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:12:41 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:12:41 - CMDPHP SQL Backtrace:  (/install/step_json.php[65]:Installer->__construct(), /lib/installer.php[167]:Installer->setTheme(), /lib/installer.php[703]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:12:41 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:12:41 - CMDPHP SQL Backtrace:  (/install/step_json.php[65]:Installer->__construct(), /lib/installer.php[174]:Installer->setDefaults(), /lib/installer.php[345]:Installer->setTemplates(), /lib/installer.php[1159]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:12:41 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:12:41 - CMDPHP SQL Backtrace:  (/install/step_json.php[65]:Installer->__construct(), /lib/installer.php[174]:Installer->setDefaults(), /lib/installer.php[345]:Installer->setTemplates(), /lib/installer.php[1159]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:12:41 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:12:41 - CMDPHP SQL Backtrace:  (/install/step_json.php[65]:Installer->__construct(), /lib/installer.php[174]:Installer->setDefaults(), /lib/installer.php[345]:Installer->setTemplates(), /lib/installer.php[1159]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:12:41 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:12:41 - CMDPHP SQL Backtrace:  (/install/step_json.php[65]:Installer->__construct(), /lib/installer.php[174]:Installer->setDefaults(), /lib/installer.php[345]:Installer->setTemplates(), /lib/installer.php[1159]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:12:41 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:12:41 - CMDPHP SQL Backtrace:  (/install/step_json.php[65]:Installer->__construct(), /lib/installer.php[174]:Installer->setDefaults(), /lib/installer.php[345]:Installer->setTemplates(), /lib/installer.php[1159]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:12:41 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:12:41 - CMDPHP SQL Backtrace:  (/install/step_json.php[65]:Installer->__construct(), /lib/installer.php[174]:Installer->setDefaults(), /lib/installer.php[345]:Installer->setTemplates(), /lib/installer.php[1159]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:12:41 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:12:41 - CMDPHP SQL Backtrace:  (/install/step_json.php[65]:Installer->__construct(), /lib/installer.php[174]:Installer->setDefaults(), /lib/installer.php[345]:Installer->setTemplates(), /lib/installer.php[1159]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:12:41 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:12:41 - CMDPHP SQL Backtrace:  (/install/step_json.php[65]:Installer->__construct(), /lib/installer.php[174]:Installer->setDefaults(), /lib/installer.php[345]:Installer->setTemplates(), /lib/installer.php[1159]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:12:41 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:12:41 - CMDPHP SQL Backtrace:  (/install/step_json.php[65]:Installer->__construct(), /lib/installer.php[174]:Installer->setDefaults(), /lib/installer.php[345]:Installer->setTemplates(), /lib/installer.php[1159]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:12:41 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:12:41 - CMDPHP SQL Backtrace:  (/install/step_json.php[65]:Installer->__construct(), /lib/installer.php[174]:Installer->setDefaults(), /lib/installer.php[345]:Installer->setTemplates(), /lib/installer.php[1176]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:12:41 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:12:41 - CMDPHP SQL Backtrace:  (/install/step_json.php[65]:Installer->__construct(), /lib/installer.php[174]:Installer->setDefaults(), /lib/installer.php[346]:Installer->setProfile(), /lib/installer.php[831]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:12:41 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:12:41 - CMDPHP SQL Backtrace:  (/install/step_json.php[65]:Installer->__construct(), /lib/installer.php[174]:Installer->setDefaults(), /lib/installer.php[347]:Installer->setAutomationMode(), /lib/installer.php[867]:Installer->setTrueFalse(), /lib/installer.php[380]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:12:41 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:12:41 - CMDPHP SQL Backtrace:  (/install/step_json.php[65]:Installer->__construct(), /lib/installer.php[174]:Installer->setDefaults(), /lib/installer.php[349]:Installer->setAutomationRange(), /lib/installer.php[958]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:12:41 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:12:41 - CMDPHP SQL Backtrace:  (/install/step_json.php[65]:Installer->__construct(), /lib/installer.php[174]:Installer->setDefaults(), /lib/installer.php[350]:Installer->setRRDVersion(), /lib/installer.php[666]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:12:41 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:12:41 - CMDPHP SQL Backtrace:  (/install/step_json.php[65]:Installer->__construct(), /lib/installer.php[174]:Installer->setDefaults(), /lib/installer.php[350]:Installer->setRRDVersion(), /lib/installer.php[667]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:12:41 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:12:41 - CMDPHP SQL Backtrace:  (/install/step_json.php[65]:Installer->__construct(), /lib/installer.php[174]:Installer->setDefaults(), /lib/installer.php[352]:Installer->setMode(), /lib/installer.php[1321]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:12:41 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:12:41 - CMDPHP SQL Backtrace:  (/install/step_json.php[65]:Installer->__construct(), /lib/installer.php[174]:Installer->setDefaults(), /lib/installer.php[356]:Installer->processParameters(), /lib/installer.php[237]:Installer->setStep(), /lib/installer.php[1378]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:12:41 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:12:41 - CMDPHP SQL Backtrace:  (/install/step_json.php[65]:Installer->__construct(), /lib/installer.php[174]:Installer->setDefaults(), /lib/installer.php[356]:Installer->processParameters(), /lib/installer.php[237]:Installer->setStep(), /lib/installer.php[1380]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:12:41 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:12:41 - CMDPHP SQL Backtrace:  (/install/step_json.php[65]:Installer->__construct(), /lib/installer.php[174]:Installer->setDefaults(), /lib/installer.php[356]:Installer->processParameters(), /lib/installer.php[237]:Installer->setStep(), /lib/installer.php[1381]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:12:41 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:12:41 - CMDPHP SQL Backtrace:  (/install/step_json.php[65]:Installer->__construct(), /lib/installer.php[174]:Installer->setDefaults(), /lib/installer.php[356]:Installer->processParameters(), /lib/installer.php[247]:Installer->setEula(), /lib/installer.php[604]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:12:41 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'settings' is full
2022/06/23 16:12:41 - CMDPHP SQL Backtrace:  (/install/step_json.php[66]:json_encode(), Installer->jsonSerialize(), /lib/installer.php[184]:Installer->processCurrentStep(), /lib/installer.php[1624]:Installer->processStepInstall(), /lib/installer.php[2647]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
2022/06/23 16:12:41 - INSTALL: always: Spawning background process: /bin/php '/usr/share/cacti/install/background.php' 1656015161.6061
2022/06/23 16:12:41 - INSTALL: Checking arguments
2022/06/23 16:12:41 - INSTALL: always: Install aborted due to no EULA acceptance

**Comment by goosej13** [comment]
this solved all my problems

MariaDB [cacti]>   ALTER TABLE `settings`  ROW_FORMAT=DYNAMIC;

**Comment by goosej13** [comment]
solved

**Comment by TheWitness** [comment]
Super weird.  Never seen that. Been doing MySQL for a long time.

**Comment by goosej13** [comment]
> Glad you figured it out though.

Thank you.. it was your suggestion to look at the logs again.. I first looked and there was so much crap in the logs I gave up... Then I just grepped for "error" to find that one log line about the settings... Quick google search on how to look at table settings.. Compared it with my dev server.. then boom.. edited it.
