### ISSUE TITLE
Can't view some informations in graph

### ISSUE THREAD

**Issue by manhvu1997** [Cacti/cacti#4848]
# Describe the bug

I install cacti 1.2.20 on ubuntu. When I create the graph, the graph was like the picture below:
![image](https://user-images.githubusercontent.com/58839875/176347955-60888ad0-ab58-4f49-8752-233ec3dbe204.png)
However, I want to see more information like the picture below:
![image](https://user-images.githubusercontent.com/58839875/176347738-3572e82d-4739-45a8-ba5e-5f963746ae58.png)
Can you help me how to config cacti to see that information?

**Comment by manhvu1997** [comment]
Hope you can answer me
I really need that

**Comment by TheWitness** [comment]
This would appear to be a forum related issue.  So, take this to the forums.
