### ISSUE TITLE
Tree Search Does Not Properly Search All Trees

### ISSUE THREAD

**Issue by browniebraun** [Cacti/cacti#4849]
# Describe the bug

We are using a global, script generated tree with following schema:

World
   -> region
        -> country
             -> state
                  -> city
                       -> site 
                            -> Cacti Device Type
                                -> Device

First off, the search will find matching objects. It doesn't matter if it is part of the device, site or city name, BUT
all elements belonging to a matching items will not be available in most cases.

Example:

You search for "Dear" and Cacti builds following tree:
->World
    -> North America
         -> US
              -> Michigan
                  -> Dearborn

Leaf sites and assigned device types and devices are not part of the result. Matching City name "Dearborn" is not clickable and does not allow to load underlying elements with another call.

**Comment by browniebraun** [comment]
v.1.2.22

**Comment by TheWitness** [comment]
@browniebraun did this work before?  Any Javascript errors?

**Comment by TheWitness** [comment]
I'm seeing a similar issue.

**Comment by TheWitness** [comment]
You might want to upload an animation screen2gif @browniebraun

**Comment by browniebraun** [comment]
@TheWitness
Hi Larry,
Sorry for my late response. I have just found some time to review the updated SQL query and did a few test runs. From my point of view it has to be changed as shown below:

```
                $matching = db_fetch_assoc_prepared("SELECT gti.parent, gti.graph_tree_id
                        FROM graph_tree_items AS gti
                        LEFT JOIN host AS h
                        ON h.id = gti.host_id
                        LEFT JOIN graph_templates_graph AS gtg
                        ON gtg.local_graph_id = gti.local_graph_id
                        LEFT JOIN sites AS s
                        ON s.id = gti.site_id
                        WHERE (gtg.local_graph_id > 0 AND gtg.title_cache LIKE ?)
                        OR (h.description LIKE ? AND gti.host_id > 0)
                        OR (h.hostname LIKE ? AND gti.host_id > 0)
                        OR (gti.title LIKE ?)
                        OR (s.name LIKE ? AND gti.site_id > 0)
                        GROUP BY gti.parent, gti.graph_tree_id",
                        array($filter, $filter, $filter, $filter, $filter));

```
Your query did not work for me, but maybe I'm generating the tree with over 5000 items not correctly in my script.
I'm setting the site_id in table graph_tee_items, too.
Building a concatenated LEFT JOIN of sites and host table will exclude all sites automatically where hosts not matching and not deliver the correct results.

In my case instead of h.site_id, gti.site_id should be used for the JOIN statement with sites and a GROUP BY afterwards to get rid of the duplicates.

This is working faultlessly for my environment.

Regards
-Andi

**Comment by browniebraun** [comment]
Addendum: 
- Matching Sites are clickable, but cannot be opened like folder to show assigned host types and hosts belonging to that sites.
- A search pattern should have a minimum of 3 characters before being triggered or the trigger delay in JS has to be increased. On huge environments you are faced with timeouts if a search has been fired forcing Cacti to search for a singe character everywhere. This happens if you are too slow in pressing the delete button like I'm. ;)

**Comment by TheWitness** [comment]
Commit it then.  But make sure the other route works too.

**Comment by TheWitness** [comment]
> Addendum: 
> - Matching Sites are clickable, but cannot be opened like folders to show assigned host types and hosts belonging to a site.
> - A search pattern should have a minimum of 3 characters before being triggered or the trigger delay in JS has to be increased. On huge environments you are faced with timeouts if a search has been fired forcing Cacti to search for a singe character everywhere. This happens if you are too slow in pressing the delete button like I'm. ;)
> 
> 

This is likely due to the site oriented tree logic.  Commit you changes and then I can have a look or keep working through it.
