### ISSUE TITLE
Device Edit - Contacting Device

### ISSUE THREAD

**Issue by smiles1969** [Cacti/cacti#485]
Contacting device with the updating/spinning icon that never completes. My production box was on 1.0.6, and working fine. Upgraded to 1.1.0 and it's also broke now. It never resolves the SNMP sysinfo now, just says Contacting Device indefinitely. SPINE continues to poll fine, graphs are populating, and I can snmpwalk all devices just fine. 

Looks to me like the changes that were part of 201bc6e commit, probably with the javascript.

**Comment by smiles1969** [comment]
This is working fine in IE. 

NOT working in chrome, even after refresh and clear cache.

**Comment by smiles1969** [comment]
I get this in the console:

Uncaught ReferenceError: hostInfoHeight is not defined
    at HTMLDocument.<anonymous> (host.php?action=edit&id=2:812)
    at mightThrow (jquery.js:3508)
    at process (jquery.js:3576)

**Comment by smiles1969** [comment]
I've replaced the check for hostInfoHeight with this and it's working for me now:

if (typeof hostInfoHeight != "undefined") {

I haven't done enough javascript to know if this is a good fix so I didn't attempt a pull request.

**Comment by cigamit** [comment]
Resolved, thanks!
