### ISSUE TITLE
Cacti/Spine non working after upgrading from Version 1.1.38 to 1.2.18

### ISSUE THREAD

**Issue by elwesingollo** [Cacti/cacti#4854]
After upgrading an existing cacti installation from v 1.1.38 to 1.2.18 i cannot make spine working correcly.
It reach always the max polling time of 299 seconds. no rrd is upgraded and no evident errors is displayed in the logs.

this is the configuration:
**General Information:**
<html><body>

Date | Fri, 01 Jul 2022 12:13:40 +0200
-- | --
Cacti Version | 1.2.18
Cacti OS | unix
RSA Fingerprint | f4:48:66:ba:58:3a:63:35:c7:da:fd:e3:75:6a:0d:25
NET-SNMP Version | NET-SNMP version: 5.5
RRDtool Version Configured | 1.4.0+
RRDtool Version Found | 1.4.8
Devices | 604
Graphs | 5,009
Data Sources | Script/Command: 4,102SNMP Get: 6,963SNMP Query: 735Script Query: 1Script Server: 129Script Server Query: 969Total: 12,899

</body>
</html>

**Poller Information:**

<html><body>

Interval | 300
-- | --
Type | SPINE 1.2.18  Copyright 2004-2021 by The Cacti Group
Items | Action[0]: 7,894Action[1]: 4,102Action[2]: 1,280Total: 13,276
Concurrent Processes | Name: Main Poller, Procs: 4
Max Threads | Name: Main Poller, Threads: 45
PHP Servers | 4
Minimum Connections: | Current: 2000, Min Required: 296Assumes 100 spare connections for Web page users and other various connections.The minimum required can vary greatly if there is heavy user Graph viewing activity.Each browser tab can use upto 10 connections depending on the browser.
Script Timeout | 15
Max OID | 40
Last Run Statistics | Time:298.7941 Method:spine Processes:4 Threads:45 Hosts:597 HostsPerProcess:150 DataSources:13276 RRDsProcessed:0

</body>
</html>

**System memory:**

<html><body>

MemTotal | 3.74 G
-- | --
MemFree | 1.30 G
Buffers | 336.36 M
Cached | 1.13 G
Active | 1.14 G
Inactive | 1.14 G
SwapTotal | 1.95 G
SwapFree | 1.80 G

</body>
</html>

**PHP Informations:**

<html><body>

PHP Version | 5.5.5
-- | --
PHP OS | Linux
PHP uname | Linux xxxxxxxxxxxxxx 2.6.32-358.el6.i686 #1 SMP Tue Jan 29 11:48:01 EST 2013 i686
PHP SNMP | Not Installed
max_execution_time | 60
memory_limit | 800M

</body>
</html>

I've rebuild the Poller Cache many times, i've stopped/start the poller and the single datasources but it didn't produce any good
The only issue i see in the logs are these WARNING
<html><body>

2022/06/27 16:00:02 - SPINE: Poller[1] PID[1612] WARNING: Unknown error while resolving host ` (Name or service not known)
2022/06/27 15:55:02 - SPINE: Poller[1] PID[1082] WARNING: Unknown error while resolving host p (Name or service not known)
2022/06/27  15:50:03 - SPINE: Poller[1] PID[542] WARNING: Unknown error while  resolving host Xi:m/%d %H:%M:%S -  (Name or service not known)
2022/06/27 15:45:02 - SPINE: Poller[1] PID[32321] WARNING: Unknown error while resolving host P (Name or service not known)

</body>
</html>
But all the hosts are correctly present in the database.
<html><body>

27/06/2022 16:05:02 - PHPSVR WARNING: Parent (2317) of Script Server (2367) has been lost, forcing exit
27/06/2022 16:05:02 - PHPSVR WARNING: Parent (2317) of Script Server (2386) has been lost, forcing exit
27/06/2022 16:05:02 - PHPSVR WARNING: Parent (2317) of Script Server (2457) has been lost, forcing exit
27/06/2022 16:05:02 - PHPSVR WARNING: Parent (2317) of Script Server (2510) has been lost, forcing exit
27/06/2022 16:05:02 - PHPSVR WARNING: Input Expected, parent process 2317 should have sent non-blank line
27/06/2022 16:05:02 - PHPSVR WARNING: Input Expected, parent process 2317 should have sent non-blank line
27/06/2022 16:05:02 - PHPSVR WARNING: Input Expected, parent process 2317 should have sent non-blank line
27/06/2022 16:05:02 - PHPSVR WARNING: Input Expected, parent process 2317 should have sent non-blank line

</body>
</html>

this warnings are the most concerning, but i cant see how i can resolve them

Can you please give me an hint to wat to do?

**Comment by TheWitness** [comment]
Use the 1.2.x branch.  We just recently did some QA.  It's much better and will be part of 1.2.22 release.

**Comment by TheWitness** [comment]
No feedback.

**Comment by elwesingollo** [comment]
Sorry,
I 'was on holiday.
i've used the master version now, and it works well.
