### ISSUE TITLE
Wrong ping values in Cacti graph issue.

### ISSUE THREAD

**Issue by cutehameed** [Cacti/cacti#4858]
Hi folks,
I am using Cacti as monitoring server and it is working pretty well. But i am facing wrong ping (output) value issue in cacti on only a few graphs. Kindly help me in this regards with thanks.

**Comment by TheWitness** [comment]
Take this up on the forums.  Thanks.

**Comment by cutehameed** [comment]
@TheWitness What is the appropriate forum to discuss it?

**Comment by TheWitness** [comment]
forums.cacti.net
