### ISSUE TITLE
View query_ifName in created graph for this host interface

### ISSUE THREAD

**Issue by manhvu1997** [Cacti/cacti#4862]
Hi All
I install Cacti 1.2.20 on Ubuntu. When I add a new device and click Created Graph for this device, the graphnew interface appears. After that, I change the Graph type box to "SNMP - Interface statistics" and I see the new UI like the picture below:
![image](https://user-images.githubusercontent.com/58839875/178707372-915472f9-b281-41d2-8983-8048bbdc8b70.png)

In this version, I can't view the ifName row in the "Create graph for this device" interface. However, I used to use the old Cacti version is 0.8.8d, it has the ifName row when I created new graph like the picture below. It makes it easier for me to distinguish when creating graphs.

![image](https://user-images.githubusercontent.com/58839875/178707043-462b4bd5-dde2-4be2-a1c9-72719310c640.png)
So, Can you help me to view ifName row in the new version Cacti 1.2.20?

**Comment by manhvu1997** [comment]
Any one can help me ?

**Comment by manhvu1997** [comment]
I check log file of my cacti, and the log said:
![image](https://user-images.githubusercontent.com/58839875/178866736-0e498e03-a473-4e90-9c92-08378127b5fc.png)
However, when I execute the command snmpwalk in the cacti server, the result is different:
![image](https://user-images.githubusercontent.com/58839875/178866920-08691c24-c5cf-4f44-9dcb-9330efde5e4f.png)

**Comment by TheWitness** [comment]
The question does not make any sense.

**Comment by manhvu1997** [comment]
After a long time of researching, I found a solution. I add 1 field to the oid .1.3.6.1.2.1.31.1.1.1.1 in the file /var/www/html/cacti/resource/snmp_queries/interface.xml like this:

> <ifName>
>                <name>Name (IF-MIB)</name>
>                <method>walk</method>
>                <source>value</source>
>                <direction>input</direction>
`                  <output_format>ascii</output_format>`
>                <oid>.1.3.6.1.2.1.31.1.1.1.1</oid>
> </ifName>

I did that because the output of snmpwalk command is a string value, so when you add ASCII output, Cacti will detect value ifname in the UI
