### ISSUE TITLE
Non device based Data Sources not being polled

### ISSUE THREAD

**Issue by holm-informatik** [Cacti/cacti#4863]
# Describe the bug

Somewhere between 1.2.16 and 1.2.20, non device based data sources (Device: None) stopped being polled (no data collected and does not show up in the poller cache). It worked in 1.2.16 and older, it does not seem to work after upgrading to 1.2.20 (and 1.2.21).

Rebuilding the poller cache (tested web and cli) does not help.

Cacti is running on Debian 11, php 7.4

**Comment by TheWitness** [comment]
Hmm, do they exist in the poller cache?  Can you confirm?

**Comment by holm-informatik** [comment]
No, they do not.

**Comment by TheWitness** [comment]
I have to setup a reproduce environment.

**Comment by TheWitness** [comment]
Run this.  I just set one up and it worked perfectly:

```sql
SELECT * FROM data_local WHERE host_id = 0;
```

**Comment by TheWitness** [comment]
Also the following;

```sql
SELECT COUNT(*) FROM poller_item WHERE host_id = 0;
```

**Comment by TheWitness** [comment]
Is that them though?  They are in the poller cache.

**Comment by holm-informatik** [comment]
Yes, it's them.

It would seem so but they are not present when looking in Console > Utilities > View Poller Cache and I get no data UNLESS I assign the Data Source to a device (so I assume that there is no problem with the data source itself).

**Comment by TheWitness** [comment]
Run this and show me the output:

```bash
./spine -R -V 5 -S -f 0 -l 0
```

Maybe it's spine.

**Comment by holm-informatik** [comment]
No, I'm not using spine...

**Comment by TheWitness** [comment]
cmd.php is similar

[code]
php -q cmd.php --debug --first=0 --last=0 --poller=1
[/code]

**Comment by holm-informatik** [comment]
```
cacti$ php -q cmd.php --debug --first=0 --last=0 --poller=1
Total[0.0093] NOTE: There are no items in your poller for this polling cycle!
cacti$ 
```

**Comment by TheWitness** [comment]
Okay, reproduced.  Update your cmd.php from the 1.2.x branch.  Thanks for sticking in there.
