### ISSUE TITLE
CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())

### ISSUE THREAD

**Issue by v0vas** [Cacti/cacti#4864]
Hi mates!

When open Graph tab, see this message

`Fatal error: Uncaught Error: Call to undefined function proc_open() in /usr/local/share/cacti/lib/rrd.php:313 Stack trace: #0 /usr/local/share/cacti/lib/rrd.php(261): __rrd_execute() #1 /usr/local/share/cacti/lib/functions.php(3039): rrdtool_execute() #2 /usr/local/share/cacti/lib/functions.php(2998): get_rrd_cfs() #3 /usr/local/share/cacti/lib/rrd.php(1462): generate_graph_best_cf() #4 /usr/local/share/cacti/graph_json.php(159): rrdtool_function_graph() #5 {main} thrown in /usr/local/share/cacti/lib/rrd.php on line 313`

Also in Cacti log

`17.07.2022 15:03:11 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
17.07.2022 15:03:11 - ERROR PHP ERROR: Uncaught Error: Call to undefined function proc_open() in /usr/local/share/cacti/lib/rrd.php:313 Stack trace: #0 /usr/local/share/cacti/lib/rrd.php(261): __rrd_execute() #1 /usr/local/share/cacti/lib/functions.php(3039): rrdtool_execute() #2 /usr/local/share/cacti/lib/functions.php(2998): get_rrd_cfs() #3 /usr/local/share/cacti/lib/rrd.php(1462): generate_graph_best_cf() #4 /usr/local/share/cacti/graph_json.php(159): rrdtool_function_graph() #5 {main} thrown in file: /usr/local/share/cacti/lib/rrd.php on line: 313
17.07.2022 15:03:11 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
17.07.2022 15:03:11 - ERROR PHP ERROR: Uncaught Error: Call to undefined function proc_open() in /usr/local/share/cacti/lib/rrd.php:313 Stack trace: #0 /usr/local/share/cacti/lib/rrd.php(261): __rrd_execute() #1 /usr/local/share/cacti/lib/functions.php(3039): rrdtool_execute() #2 /usr/local/share/cacti/lib/functions.php(2998): get_rrd_cfs() #3 /usr/local/share/cacti/lib/rrd.php(1462): generate_graph_best_cf() #4 /usr/local/share/cacti/graph_json.php(159): rrdtool_function_graph() #5 {main} thrown in file: /usr/local/share/cacti/lib/rrd.php on line: 313
17.07.2022 15:03:11 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())`

- OS: FreeBSD 13.1
- PHP 8.2
- Browser chrome
- Version 1.2.21

**Comment by TheWitness** [comment]
This is not a bug, you are missing a require PHP module.  Go to php.net to get information on installing, or install the required package from your os providers package management system.

**Comment by v0vas** [comment]
What exactly module are missing? 
`php -m
[PHP Modules]
bz2
Core
ctype
date
dom
filter
gd
gettext
gmp
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
Reflection
session
SimpleXML
snmp
sockets
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache`

**Comment by TheWitness** [comment]
Process Control.  It's named differently depending on your os.

**Comment by v0vas** [comment]
Installed php-pcntl extension https://www.php.net/manual/en/book.pcntl.php. An error still remain.

**Comment by v0vas** [comment]
Solved. There was custom security settings in php.ini.

**Comment by TheWitness** [comment]
Yea, the php-process does not make some security people happy.  However, it's super important.
