### ISSUE TITLE
XML Pre-processing during Graph Creation throws error when Resource XML file inproperly formatted

### ISSUE THREAD

**Issue by BaptisteVlt** [Cacti/cacti#4865]
Hello,

I run my cacti server on Centos 7.
Recently I tried to create a new graph and I got errors after that in my logs : 

--
2022/07/18 10:25:38 - ERROR PHP WARNING: Illegal string offset 'direction' in file: /var/www/html/cacti/graphs_new.php on line: 826
2022/07/18 10:25:38 - CMDPHP PHP ERROR WARNING Backtrace: (/graphs_new.php[68]:graphs(), /graphs_new.php[670]:CactiErrorHandler())
2022/07/18 10:25:38 - ERROR PHP WARNING: Illegal string offset 'direction' in file: /var/www/html/cacti/graphs_new.php on line: 670

![image](https://user-images.githubusercontent.com/45470774/179475002-a3e7e5d8-7639-4636-befe-15e415afe0d9.png)
I compare the file graphs_new.php that I've to other ones and it looks like everything is normal.
Just cause I'm curious I ran 'systemctl status cactid' on my server and I got the error : 
"Failed to start Cacti Daemon Main Poller Service"
I guess there is a link between this 2 problems.
Cacti version : 1.2.21.

**Comment by TheWitness** [comment]
What data query were you using?  Can you upload the Resources XML file here for us to review.

**Comment by BaptisteVlt** [comment]
I'm using data query that I found on the forum. This is data query for iDirect :
At this moment I was trying to use down snr graph. 
[data_query.zip](https://github.com/Cacti/cacti/files/9138601/data_query.zip)

**Comment by TheWitness** [comment]
The XML files have some illegal characters in them.  Notice in the attached image the following

![image](https://user-images.githubusercontent.com/1439914/179761976-1140349a-d473-49dc-9042-2a72a417bdfc.png)

Get rid of those illegal characters and I think the problem will be solved.  I will put in a patch to mask the error, but my guess is that we should be handling this better.  In any event, it's a Resource XML file issue.  Occurs in all of them.

![image](https://user-images.githubusercontent.com/1439914/179761885-e1f39a9c-0da8-4eba-8180-21f4b8289104.png)

**Comment by TheWitness** [comment]
Test the update before you fix the XML files.

**Comment by BaptisteVlt** [comment]
Thank you very much. I'm sorry that I didn't notice that before ..
