### ISSUE TITLE
Using ${var} in strings is deprecated, use {$var} instead in file

### ISSUE THREAD

**Issue by v0vas** [Cacti/cacti#4866]
Hi mates!
Cacti 1.2.21
PHP - 8.2

I have error messages in logs:

> 19.07.2022 09:59:02 - CMDPHP PHP ERROR Backtrace: (/poller_maintenance.php[26]:require(), /include/cli_check.php[45]:include(), /include/global.php[520]:include_once(), /include/global.php[520]:CactiErrorHandler())
> --
> 19.07.2022 09:59:02 - ERROR PHP DEPRECATED: Using ${var} in strings is deprecated, use {$var} instead in file: /usr/local/share/cacti/lib/html_form.php on line: 355
> 19.07.2022 09:59:02 - CMDPHP PHP ERROR Backtrace: (/poller_maintenance.php[26]:require(), /include/cli_check.php[45]:include(), /include/global.php[520]:include_once(), /include/global.php[520]:CactiErrorHandler())
> 19.07.2022 09:59:02 - ERROR PHP DEPRECATED: Using ${var} in strings is deprecated, use {$var} instead in file: /usr/local/share/cacti/lib/html_form.php on line: 353
> 19.07.2022 09:59:02 - CMDPHP PHP ERROR Backtrace: (/poller_spikekill.php[26]:require(), /include/cli_check.php[45]:include(), /include/global.php[520]:include_once(), /include/global.php[520]:CactiErrorHandler())
> 19.07.2022 09:59:02 - ERROR PHP DEPRECATED: Using ${var} in strings is deprecated, use {$var} instead in file: /usr/local/share/cacti/lib/html_form.php on line: 355
> 19.07.2022 09:59:02 - CMDPHP PHP ERROR Backtrace: (/poller_spikekill.php[26]:require(), /include/cli_check.php[45]:include(), /include/global.php[520]:include_once(), /include/global.php[520]:CactiErrorHandler())
> 19.07.2022 09:59:02 - ERROR PHP DEPRECATED: Using ${var} in strings is deprecated, use {$var} instead in file: /usr/local/share/cacti/lib/html_form.php on line: 353
> 19.07.2022 09:59:02 - CMDPHP PHP ERROR Backtrace: (/poller_automation.php[34]:require(), /include/cli_check.php[45]:include(), /include/global.php[520]:include_once(), /include/global.php[520]:CactiErrorHandler())
> 19.07.2022 09:59:02 - ERROR PHP DEPRECATED: Using ${var} in strings is deprecated, use {$var} instead in file: /usr/local/share/cacti/lib/html_form.php on line: 355
> 19.07.2022 09:59:02 - CMDPHP PHP ERROR Backtrace: (/poller_automation.php[34]:require(), /include/cli_check.php[45]:include(), /include/global.php[520]:include_once(), /include/global.php[520]:CactiErrorHandler())
> 19.07.2022 09:59:02 - ERROR PHP DEPRECATED: Using ${var} in strings is deprecated, use {$var} instead in file: /usr/local/share/cacti/lib/html_form.php on line: 353
> 19.07.2022 09:59:02 - CMDPHP PHP ERROR Backtrace: (/poller_dsstats.php[34]:require(), /include/cli_check.php[45]:include(), /include/global.php[520]:include_once(), /include/global.php[520]:CactiErrorHandler())
> 19.07.2022 09:59:02 - ERROR PHP DEPRECATED: Using ${var} in strings is deprecated, use {$var} instead in file: /usr/local/share/cacti/lib/html_form.php on line: 355
> 19.07.2022 09:59:02 - CMDPHP PHP ERROR Backtrace: (/poller_dsstats.php[34]:require(), /include/cli_check.php[45]:include(), /include/global.php[520]:include_once(), /include/global.php[520]:CactiErrorHandler())
> 19.07.2022 09:59:02 - ERROR PHP DEPRECATED: Using ${var} in strings is deprecated, use {$var} instead in file: /usr/local/share/cacti/lib/html_form.php on line: 353
> 19.07.2022 09:59:02 - CMDPHP PHP ERROR Backtrace: (/poller_reports.php[34]:require(), /include/cli_check.php[45]:include(), /include/global.php[520]:include_once(), /include/global.php[520]:CactiErrorHandler())
> 19.07.2022 09:59:02 - ERROR PHP DEPRECATED: Using ${var} in strings is deprecated, use {$var} instead in file: /usr/local/share/cacti/lib/html_form.php on line: 355
> 19.07.2022 09:59:02 - CMDPHP PHP ERROR Backtrace: (/poller_reports.php[34]:require(), /include/cli_check.php[45]:include(), /include/global.php[520]:include_once(), /include/global.php[520]:CactiErrorHandler())
> 19.07.2022 09:59:02 - ERROR PHP DEPRECATED: Using ${var} in strings is deprecated, use {$var} instead in file: /usr/local/share/cacti/lib/html_form.php on line: 353
> 19.07.2022 09:59:01 - CMDPHP PHP ERROR Backtrace: (/cmd.php[365]:ping_and_reindex_check(), /cmd.php[742]:update_system_mibs(), /cmd.php[580]:open_snmp_session(), /cmd.php[543]:cacti_snmp_session(), /lib/snmp.php[87]:CactiErrorHandler())
> 19.07.2022 09:59:01 - ERROR PHP DEPRECATED: Creation of dynamic property phpsnmp\SNMP::$bulk_walk_size is deprecated in file: /usr/local/share/cacti/lib/snmp.php on line: 87
> 19.07.2022 09:59:00 - CMDPHP PHP ERROR Backtrace: (/cmd.php[365]:ping_and_reindex_check(), /cmd.php[722]:Net_Ping->__construct(), /lib/ping.php[43]:CactiErrorHandler())
> 19.07.2022 09:59:00 - ERROR PHP DEPRECATED: Creation of dynamic property Net_Ping::$port is deprecated in file: /usr/local/share/cacti/lib/ping.php on line: 43
> 19.07.2022 09:59:00 - CMDPHP PHP ERROR Backtrace: (/script_server.php[33]:require(), /include/cli_check.php[45]:include(), /include/global.php[520]:include_once(), /include/global.php[520]:CactiErrorHandler())
> 19.07.2022 09:59:00 - ERROR PHP DEPRECATED: Using ${var} in strings is deprecated, use {$var} instead in file: /usr/local/share/cacti/lib/html_form.php on line: 355
> 19.07.2022 09:59:00 - CMDPHP PHP ERROR Backtrace: (/script_server.php[33]:require(), /include/cli_check.php[45]:include(), /include/global.php[520]:include_once(), /include/global.php[520]:CactiErrorHandler())
> 19.07.2022 09:59:00 - ERROR PHP DEPRECATED: Using ${var} in strings is deprecated, use {$var} instead in file: /usr/local/share/cacti/lib/html_form.php on line: 353

**Comment by TheWitness** [comment]
I've made the changes to mask those Deprecation warnings.  Keep testing.  I know that there are a few plugins impacted, but that's secondary.
