### ISSUE TITLE
In Graph Management, filtering for "Device: None" shows all graphs

### ISSUE THREAD

**Issue by holm-informatik** [Cacti/cacti#4867]
# Describe the bug

in Cacti 1.2.21 (and 1.2.20, not sure about earlier versions), when filering "Device: None" in Graph Management, all graphs are shown.

Debian 11, Php 7.4

## To Reproduce

- Go to Graph Management - Graphs
- Select: Device None
- All graphs are shown

## Expected behavior

Only "Non Device Graphs" should be shown

**Comment by TheWitness** [comment]
Okay, fixed in the 1.2.x branch.  Please test.
