### ISSUE TITLE
Add support for Business Hours 

### ISSUE THREAD

**Issue by thurban** [Cacti/cacti#4874]
# Feature Request

## Is your feature request related to a problem? Please describe
Displaying Business Hours on the graph helps identifying issues during these and ignore known spikes out of office hours.

## Describe the solution you'd like
Include business hours to be displayed as an AREA within the charts

## Describe alternatives you've considered
There are non

## Additional context
See attached early alpha for showing business hours, realized as a plugin
![BusinesHours_demo_plugin_1](https://user-images.githubusercontent.com/17292964/180615767-48c4e0b3-31c4-49ac-ab60-d6f32751209d.png)
![BusinesHours_demo_plugin_2](https://user-images.githubusercontent.com/17292964/180615768-59403004-552e-44e9-a952-d47d1b5a2c16.png)

**Comment by netniV** [comment]
Is this something you are working on @thurban ?  Or just something you'd like us to add?

**Comment by thurban** [comment]
Hi. Im working on it. Got some basic version already working.  

I probably add some basic functionality for future versions and a plugin for complete version 1.x compatibility.

**Comment by netniV** [comment]
Sounds good, I have places I can test it out if you need.

**Comment by TheWitness** [comment]
Yea, glad to have you on board Thomas.  I would like to assign this ticket to you.  What do you think @netniV?

**Comment by thurban** [comment]
I'm going to review the code and may change it. Although it is working, it will create quite large rrdtool command line, so going to optimize that.

Maybe some special generic cdefs like from this post will make it essier:
https://forums.cacti.net/viewtopic.php?t=30839

**Comment by thurban** [comment]
I added a limit to display the business hours for a maximum number of days. Otherwise the rrdtool command line size may be getting too large (i.e. for year graphs)
