### ISSUE TITLE
Unwanted Graphs (In/Out Bytes) after re-index

### ISSUE THREAD

**Issue by chrisch80** [Cacti/cacti#4875]
Hello,

always when I do a reindex of devices I get additional graphs with "In/Out Bytes (64-bit)" from all interfaces of the reindexed device (it doen't matter which device type Cisco, Juniper, ...).
Since I don't need this graphs (I only work with bit/s 64-bit and sometimes errors for interfaces) I need to delete it after the reindex manually.
Currently I am running the last version 1.2.21, but I have seen this already in 1.2.16 (before I was on a 0.8.x version).
It occurs when I do the reindex in the WebGUI as well when I use poller_reindex_hosts.php in CLI.

Is this a bug or work as desigend?
Is there as workaround a possibility to delete all "In/Out Bytes (64-bit)" graphs via CLI?

Thank You & best regards,
Chris

**Comment by bmfmancini** [comment]
Do you have an automation rule by chance?

Check if you have a rule in automation - graph rules and see if one is
there to create the graph

**Comment by chrisch80** [comment]
thx, this was the case and my issue is solved
