### ISSUE TITLE
CMDPHP WARNING: cmd.php poller has run over its polling interval and therefore is ending

### ISSUE THREAD

**Issue by nani81** [Cacti/cacti#4876]
Good morning,
I have been getting the following error for some time now:
"2022-07-26 08:51:03 - CMDPHP WARNING: cmd.php poller has run over its polling interval and therefore is ending."
And the poller stops working.
Causing the server to crash in such a way that the CPU, RAM and SWAP status is raised.

- Version cacti: v2.1.19
- OS version: Red Hat 

Thank you very much
![cacti2](https://user-images.githubusercontent.com/51642177/180944138-f75dc1cd-11e4-4a06-8f28-475925b9b161.png)
![cacti3](https://user-images.githubusercontent.com/51642177/180944213-3f9ea40f-c83d-4a82-931f-1bf9ed5583e6.png)
![Cacti](https://user-images.githubusercontent.com/51642177/180944517-6c3bfdc4-2e0d-4d93-a551-6bb4c42999c8.png)

**Comment by TheWitness** [comment]
Use spine, it's the only thing I would ever use for production environments.

**Comment by TheWitness** [comment]
I would also use the cactid systemd service.  If you are using Windows, move to either RHEL or Debian or one of their varients.

**Comment by TheWitness** [comment]
So, basically, this is not a bug.  The cmd.php data collector can be made massively parallel, but it still lacks the level of parallelism and performance of the spine data collector.

**Comment by nani81** [comment]
Thanks you, I will change the poll to spine.
