### ISSUE TITLE
Data Query Script returns duplicate value after upgrade to 1.2.21

### ISSUE THREAD

**Issue by Atze2022** [Cacti/cacti#4877]
v1.2.21
Self Data Queries [Net-SNMP-Ext - Radius - sqlippool]

CLI Output from script = 6400
Output in Graph = 64006400

LOG-File
....web/cacti/scripts/ss_radius_sqlippool.php ss_radius_sqlippool '80.x.x.x:2:public:::::::161:500' 'get' 'size' 'DaPool', output: 64006400

Is there a known bug ?
With v1.2.10 this data query works fine ....

Thanks,
Niels

**Comment by thurban** [comment]
Hi, is that data query also coming with a XML file ? If yes, how does that look like ?  Where can this script be found ?

**Comment by Atze2022** [comment]
Hi, 
yes that data query coming with XML Input

Get Script Server Data (Indexed) - runs this XML File

/script_server/radius_sqlippool.xml
-> then the following PHP Script 

Any Idea's how i can find where the output becoming duplicated ?

Thanks
Niels



<query>
        <name>Radius - Get IP-Pool utilization</name>
        <description>Queries radippool table through NET-SNMP-Exntension script</description>
        <script_path>|path_cacti|/scripts/ss_radius_sqlippool.php</script_path>
        <script_function>ss_radius_sqlippool</script_function>
        <script_server>php</script_server>
  <arg_prepend>|host_hostname|:|host_snmp_version|:|host_snmp_community|:|host_snmp_username|:|host_snmp_password|:|host_snmp_auth_protocol|:|host_snmp_priv_passphrase|:|host_snmp_priv_protocol|:|host_snmp_context|:|host_snmp_port|:|host_
snmp_timeout|</arg_prepend>

        <arg_index>index</arg_index>
        <arg_query>query</arg_query>
        <arg_get>get</arg_get>
        <output_delimeter>:</output_delimeter>
        <index_order>poolName</index_order>
        <index_order_type>string</index_order_type>
        <index_title_format>|chosen_order_field|</index_title_format>
        <fields>
                <poolName>
                        <name>Pool name</name>
                        <direction>input</direction>
                        <query_name>name</query_name>
                </poolName>
                <poolSize>
                        <name>Total pool size</name>
                        <direction>output</direction>
                        <query_name>size</query_name>
                </poolSize>
                <poolUsed>
                        <name>IP addresses in use</name>
                        <direction>output</direction>
                        <query_name>used</query_name>
                </poolUsed>

                <poolUser>
                        <name>Number of distinct users</name>
                        <direction>output</direction>
                        <query_name>user</query_name>
                </poolUser>
        </fields>
</query>





#
# ss_radius_sqlippool.php
#
#
# load the Cacti configuration settings if they aren't already present
#
if (isset($config) == FALSE) {

        if (file_exists(dirname(__FILE__) . "/../include/config.php")) {
                include_once(dirname(__FILE__) . "/../include/config.php");
        }

        if (file_exists(dirname(__FILE__) . "/../include/global.php")) {
                include_once(dirname(__FILE__) . "/../include/global.php");
        }

        if (isset($config) == FALSE) {
                echo ("FATAL: Unable to load Cacti configuration files \n");
                return;
        }
}

#
# load the Cacti SNMP libraries if they aren't already present
#
if (defined('SNMP_METHOD_PHP') == FALSE) {

        if (file_exists(dirname(__FILE__) . "/../lib/snmp.php")) {
                include_once(dirname(__FILE__) . "/../lib/snmp.php");
        }

        if (defined('SNMP_METHOD_PHP') == FALSE) {
                echo ("FATAL: Unable to load SNMP libraries \n");
                return;
        }
}

#
# call the main function manually if executed outside the Cacti script server
#
if (isset($GLOBALS['called_by_script_server']) == FALSE) {

        array_shift($_SERVER["argv"]);
        print call_user_func_array("ss_radius_sqlippool", $_SERVER["argv"]);
}

#
# main function
#
function ss_radius_sqlippool(
        $protocol_bundle="",
        $cacti_request="",
        $data_request="",
        $data_request_key="")
{

        #
        # 1st function argument contains the protocol-specific bundle
        #
        # use '===' matching for strpos in case colon is 1st character
        #
        if ((trim($protocol_bundle) == "") || (strpos($protocol_bundle, ":") === FALSE)) {

                echo ("FATAL: No SNMP parameter bundle provided\n");
                ss_radius_sqlippool_syntax();
                return;
        }

        $protocol_array = explode(":", $protocol_bundle);

        if (count($protocol_array) < 11) {

                echo ("FATAL: Not enough elements in SNMP parameter bundle\n");
                ss_radius_sqlippool_syntax();
                return;
        }

        if (count($protocol_array) > 11) {

                echo ("FATAL: Too many elements in SNMP parameter bundle\n");
                ss_radius_sqlippool_syntax();
                return;
        }

        #
        # 1st bundle element is $snmp_hostname
        #
        $snmp_hostname = trim($protocol_array[0]);

        if ($snmp_hostname == "") {
                echo ("FATAL: Hostname not specified in SNMP parameter bundle\n");
                ss_radius_sqlippool_syntax();
                return;
        }

        #
        # 2nd bundle element is $snmp_version
        #
        $snmp_version = trim($protocol_array[1]);

        if ($snmp_version == "") {
                echo ("FATAL: SNMP version not specified in SNMP parameter bundle\n");
                ss_radius_sqlippool_syntax();
                return;
        }

        if (($snmp_version != 1) and ($snmp_version != 2) and ($snmp_version != 3)) {

                echo ("FATAL: \"$snmp_version\" is not a valid SNMP version\n");
                ss_radius_sqlippool_syntax();
                return;
        }

        #
        # 3rd bundle element is $snmp_community
        #
        $snmp_community = trim($protocol_array[2]);

        if (($snmp_version != 3) and ($snmp_community == "")) {

                echo ("FATAL: SNMP v$snmp_version community not specified in SNMP parameter bundle\n");
                ss_radius_sqlippool_syntax();
                return;
        }

        #
        # 4th bundle element is $snmp_v3_username
        #
        $snmp_v3_username = trim($protocol_array[3]);

        #
        # 5th bundle element is $snmp_v3_password
        #
        $snmp_v3_password = trim($protocol_array[4]);

        #
        # 6th bundle element is $snmp_v3_authproto
        #
        $snmp_v3_authproto = trim($protocol_array[5]);

        #
        # 7th bundle element is $snmp_v3_privpass
        #
        $snmp_v3_privpass = trim($protocol_array[6]);

        #
        # 8th bundle element is $snmp_v3_privproto
        #
        $snmp_v3_privproto = trim($protocol_array[7]);

        #
        # 9th bundle element is $snmp_v3_context
        #
        $snmp_v3_context = trim($protocol_array[8]);

        #
        # 10th bundle element is $snmp_port
        #
        $snmp_port = trim($protocol_array[9]);

        if ($snmp_port == "") {

                #
                # if the value was omitted use the default port number
                #
                $snmp_port = 161;
        }

        if (is_numeric($snmp_port) == FALSE) {

                echo ("FATAL: Non-numeric SNMP port \"$snmp_port\" specified in SNMP parameter bundle\n");
                ss_radius_sqlippool_syntax();
                return;
        }

        #
        # 11th bundle element is $snmp_timeout
        #
        $snmp_timeout = trim($protocol_array[10]);

        if ($snmp_timeout == "") {

                #
                # if the value was omitted use the global default timeout
                #
                $snmp_timeout = read_config_option("snmp_timeout");
        }

        if (is_numeric($snmp_timeout) == FALSE) {

                echo ("FATAL: Non-numeric SNMP timeout \"$snmp_timeout\" specified in SNMP parameter bundle\n");
                ss_radius_sqlippool_syntax();
                return;
        }

        #
        # these aren't parameters, but go ahead and out $snmp_retries and $snmp_maxoids
        # from the global settings
        #
        $snmp_retries = read_config_option("snmp_retries");
        $snmp_maxoids = read_config_option("max_get_size");

        #
        # 2nd function argument is $cacti_request
        #
        $cacti_request = strtolower(trim($cacti_request));

        if ($cacti_request == "") {

                echo ("FATAL: No Cacti request provided\n");
                ss_radius_sqlippool_syntax();
                return;
        }

        if (($cacti_request != "index") &&
                ($cacti_request != "query") &&
                ($cacti_request != "get")) {

                echo ("FATAL: \"$cacti_request\" is not a valid Cacti request\n");
                ss_radius_sqlippool_syntax();
                return;
        }

        #
        # remaining function arguments are $data_request and $data_request_key
        #
        if (($cacti_request == "query") || ($cacti_request == "get")) {

                $data_request = strtolower(trim($data_request));

                if ($data_request == "") {

                        echo ("FATAL: No data requested for Cacti \"$cacti_request\" request\n");
                        ss_radius_sqlippool_syntax();
                        return;
                }

                if (($data_request != "name") &&
                        ($data_request != "size") &&
                        ($data_request != "used") &&
                        ($data_request != "user")) {

                        echo ("FATAL: \"$data_request\" is not a valid data request\n");
                        ss_radius_sqlippool_syntax();
                        return;
                }

                #
                # get the index variable
                #
                if ($cacti_request == "get") {

                        $data_request_key = strtolower(trim($data_request_key));

                        if ($data_request_key == "") {

                                echo ("FATAL: No index value provided for \"$data_request\" data request\n");
                                ss_radius_sqlippool_syntax();
                                return;
                        }
                }

                #
                # clear out spurious command-line parameters on query requests
                #
                else {
                        $data_request_key = "";
                }
        }

        #
        # build the snmp_arguments array for future use
        #
        # note that the array structure varies according to the version of Cacti in use
        #
        if (isset($GLOBALS['config']['cacti_version']) == FALSE) {

                echo ("FATAL: Unable to determine Cacti version\n");
                return;
        }

        elseif (substr($GLOBALS['config']['cacti_version'],0,5) == "0.8.6") {

                $snmp_arguments = array(
                        $snmp_hostname,
                        $snmp_community,
                        "",
                        $snmp_version,
                        $snmp_v3_username,
                        $snmp_v3_password,
                        $snmp_port,
                        $snmp_timeout);

                #
                # Cacti 0.8.6 SNMP timeout used milliseconds, while PHP uses Net-SNMP foormat, which
                # is typically microseconds. Normalize by multiplying the timeout value by 1000.
                #
                $snmp_timeout = ($snmp_timeout * 1000);
        }

        elseif (substr($GLOBALS['config']['cacti_version'],0,5) >= "0.8.7") {

                $snmp_arguments = array(
                        $snmp_hostname,
                        $snmp_community,
                        "",
                        $snmp_version,
                        $snmp_v3_username,
                        $snmp_v3_password,
                        $snmp_v3_authproto,
                        $snmp_v3_privpass,
                        $snmp_v3_privproto,
                        $snmp_v3_context,
                        $snmp_port,
                        $snmp_timeout,
                        $snmp_retries,
                        $snmp_maxoids);
        }

        else {
                echo ("FATAL: \"" . $GLOBALS['config']['cacti_version'] .
                        "\" is not a supported Cacti version\n");
                return;
        }

        #
        # set the snmp_arguments array to 
        # NET-SNMP-EXTEND-MIB::nsExtendOutLine.\"radius-sqlippool\" OID
        #
        $snmp_arguments[2] = ".1.3.6.1.4.1.8072.1.3.2.4.1.2.16.114.97.100.105.117.115.45.115.113.108.105.112.112.111.111.108";

        #
        # walk the tree and capture the resulting array of CPUs
        #
        $snmp_array = call_user_func_array("cacti_snmp_walk", $snmp_arguments);

        #
        # verify that the response contains expected data structures
        #
        if ((isset($snmp_array) == FALSE) ||
                (count($snmp_array) == 0) ||
                (array_key_exists('oid', $snmp_array[0]) == FALSE) || 
                (array_key_exists('value', $snmp_array[0]) == FALSE) ||
                (substr($snmp_array[0]['value'],0,16) == "No Such Instance") ||
                (trim($snmp_array[0]['value']) == "")) {

                echo ("FATAL: No CPU data was returned from SNMP\n");
                return;
        }

        #
        # Expected output format: <pool_name>:<size>:<used>:<users>
        #
        $pools = array();
        foreach ($snmp_array as $snmp_response) {
                $pool_data = explode(':', $snmp_response['value']);
                $pool['name'] = $pool_data[0];
                $pool['size'] = $pool_data[1];
                $pool['used'] = $pool_data[2];
                $pool['user'] = $pool_data[3];

                $pools[strtolower($pool['name'])] = $pool;
        }

        #
        # verify that the pool exists and has data
        #
        if ((isset($pools) == FALSE) || (count($pools) == 0)) {

                echo ("FATAL: No Pools were returned from SNMP\n");
                return;
        }

        #
        # return output data according to $cacti_request
        #
        switch ($cacti_request) {
                case "index":
                        foreach ($pools as $p) {
                                echo ($p['name'] . "\n");
                        }
                        break;

                #
                # if the user queried for all entries in a column, return that column
                #
                case "query":
                        foreach ($pools as $p) {
                                echo ($p['name'] . ":" . $p[$data_request] . "\n");
                        }
                        break;

                #
                # if the user requested the value for a specific entry, give them just that data
                #
                case "get":
                        if (array_key_exists($data_request_key, $pools)) {
                                echo ($pools[$data_request_key][$data_request]);
                                if (isset($GLOBALS['called_by_script_server']) == TRUE) {
                                        return $pools[$data_request_key][$data_request];
                                }
                        } else {
                                echo ("FATAL: No such pool '".$data_request_key."'\n");
                        }
                        break;
        }
}

#
# display the syntax
#
function ss_radius_sqlippool_syntax() {

        echo ("Syntax: ss_radius_sqlippool.php <hostname>:<snmp_version>:[<snmp_community>]:\ \n" .
        "      [<snmp3_username>]:[<snmp3_password>]:[<snmp3_auth_protocol>]:[<snmp3_priv_password>]:\ \n" .
        "      [<snmp3_priv_protocol>]:[<snmp3_context>]:[<snmp_port>]:[<snmp_timeout>] \ \n" .
        "      (index|query <fieldname>|get <fieldname> <pool-name>)\n");
}

?>

**Comment by thurban** [comment]
based on the code, i would say that this part isn't correct):
```
            case "get":
                    if (array_key_exists($data_request_key, $pools)) {
                            echo ($pools[$data_request_key][$data_request]);
                            if (isset($GLOBALS['called_by_script_server']) == TRUE) {
                                    return $pools[$data_request_key][$data_request];
                            }
                    } else {
                            echo ("FATAL: No such pool '".$data_request_key."'\n");
                    }
                    break;
```

From a logic point, shouldn't it be this:
```
            case "get":
                    if (array_key_exists($data_request_key, $pools)) {
                            if (isset($GLOBALS['called_by_script_server']) == TRUE) {
                                    return $pools[$data_request_key][$data_request];
                            } else {
                                echo ($pools[$data_request_key][$data_request]);
                            }
                    } else {
                            echo ("FATAL: No such pool '".$data_request_key."'\n");
                    }
                    break;
```

**Comment by Atze2022** [comment]
Thats it, now it's ok !

Great Job, thank you so much for you support.

BR
Niels
