### ISSUE TITLE
Cacti 1.2.18 - Data query Automation Not working for Newly added interfaces

### ISSUE THREAD

**Issue by anubhamangal** [Cacti/cacti#4879]
We have cacti v1.2.18 and we are facing an issue with automation. The device is not capturing new interfaces when an interface is added to the device. Though the device "status" and Admin status are actually up still cacti is not capturing it when any new interface is being added.

Versions we are using are 
Cacti Version : 1.2.18
MariaDB Version: 10.32

![Cacti Status issue](https://user-images.githubusercontent.com/99225699/181164090-4968b014-df41-4aaa-be50-384047ab8690.png)

The current data query is set as attached screenshot: -
![index](https://user-images.githubusercontent.com/99225699/181163407-73683180-b778-4b7f-bf80-5fa6b7d35cb3.png)

Could you please help with the resolution?

Thanks in advance,

Regards,
Anubha

**Comment by TheWitness** [comment]
Please upgrade to 1.2.x branch, or 1.2.21.  Then, ask again.

**Comment by TheWitness** [comment]
You also need to 're-index' the device from time to time.  Either through automation or through a cron job for now.  There is a feature to do this automatically that is in the backlog.
