### ISSUE TITLE
Invalid data records remaining in poller_output cache

### ISSUE THREAD

**Issue by browniebraun** [Cacti/cacti#4885]
# Describe the bug
This record is only for 1.2.16 and has not been verified for newer releases.
During the migration of Cisco devices to become Cisco cEdges by an OS upgrade following situation occurs:
SNMP table and indexes are completely changing. Some indexes may exist afterwards, some not.
In this case the poller_output table starts to fill up with invalid records. Those will not be dropped during the execution of Boost and remain in poller_output till the amount of records is so high that the DB server(s) dramatically slows down and polling cycles starts to overrun.  

## To Reproduce

Those records can be counted / identified with following query for example:

SELECT local_data_id, count(*) as records FROM poller_output WHERE output = 'U' GROUP BY local_data_id ORDER by records;

## Solution
From my point of view all records older than the current BOOST update interval should be removed automatically during the execution of BOOST. Although invalid data sources have to be removed to get rid of that unwanted behavior, it would be a workaround to keep the system stable. Additionally I think that it is not worth keeping those records for longer than 2 hours as U is NAN, the default if you have no data to store.

**Comment by TheWitness** [comment]
My guess is that your sort index is ifDescr.  This is why we changed it to ifName a while ago.  Old XML files are still using ifDescr though.

**Comment by TheWitness** [comment]
This issue has already been addressed in Cacti 1.2.21.  So, this is duplicate.  The entire BOOST process was redesigned between 1.2.16 and 1.2.21.  It can now easily process 400M records in the boost table, as it deletes nothing from it and simply drops the table after all 'good' Data Sources have been processed.
