### ISSUE TITLE
in cacti 1.2.22 real time counter gets stuck and does not count down

### ISSUE THREAD

**Issue by majed17** [Cacti/cacti#4893]
sometimes in the browsers i use for cacti, Firefox and chrome, the real time graph counter does not count down and the graph remains black. today all the chrome real time graphs were stuck. exiting the browser many times and reopening after a while solves the issue. except a random graph of thos open stays stuck.
log says:

```
2022/08/18  09:34:54 - CMDPHP PHP ERROR WARNING Backtrace:   (/graphs_new.php[42]:form_save(),  /graphs_new.php[172]:host_new_graphs_save(),  /graphs_new.php[274]:create_save_graph(),  /lib/template.php[2128]:push_out_host(),  /lib/utility.php[794]:update_poller_cache(),  /lib/utility.php[304]:api_poller_cache_item_add(),  /lib/api_poller.php[97]:get_data_source_path(),  /lib/functions.php[2634]:generate_data_source_path(),  /lib/functions.php[2965]:CactiErrorHandler())
--
2022/08/18 09:34:54 - ERROR PHP WARNING: Undefined array key "id" in  file: /var/www/localhost/htdocs/cacti/lib/functions.php  on line: 2965


```

**Comment by TheWitness** [comment]
Finally a new bug.  Whew, I thought that would never happen, or hoping maybe 😉.  Anyway, I'll have a look later today.

**Comment by majed17** [comment]
the error mentioned might be related to creating a cpu graph, so if anything else is needed, just let me know

**Comment by majed17** [comment]
works

**Comment by majed17** [comment]
Today, 9 out of the 52 graphs opened with non decrementing timer in the real time graphs in different browsers.
