### ISSUE TITLE
Process being killed due to timeout! after update to 1.2.22

### ISSUE THREAD

**Issue by densenator** [Cacti/cacti#4894]
<html>
<body>

18.Aug.2022 16:21:07 - POLLER: Poller[Main Poller] PID[318744] ERROR: Process being killed due to timeout! (commands, master, 1, Process 316345, Time 1660828273, Timeout 300, Timestamp 1660828867)
--
18.Aug.2022 16:21:07 - SYSTEM STATS: Time:66.5553 Method:spine Processes:4 Threads:20 Hosts:79 HostsPerProcess:20 DataSources:468 RRDsProcessed:351
2022.08.18 16:20:38 - SPINE: Poller[Main Poller] PID[317644] PT[140615148893952] WARNING: SS[3] The PHP Script Server did not respond in time and will therefore be restarted

In Debug mode:

18.Aug.2022 16:31:26 - POLLER: Poller[Main Poller] PID[321152] ERROR: Process being killed due to timeout! (commands, master, 1, Process 319938, Time 1660829172, Timeout 300, Timestamp 1660829486)
--
18.Aug.2022 16:31:26 - POLLER: Poller[Main Poller] PID[321156] NOTE: Registering process! (spikekill, master, 0, 321156)
18.Aug.2022 16:31:26 - POLLER: Poller[Main Poller] PID[321154] NOTE: Registering process! (reports, master, 0, 321154)
18.Aug.2022 16:31:26 - POLLER: Poller[Main Poller] PID[320041] DEBUG: About to Spawn a Remote Process [CMD: /usr/bin/php, ARGS: -q /var/www/html/cacti/plugins/mikrotik/poller_mikrotik.php -M]
18.Aug.2022 16:31:26 - POLLER: Poller[Main Poller] PID[320041] DEBUG: About to Spawn a Remote Process [CMD: /usr/bin/php, ARGS: -q '/var/www/html/cacti/poller_maintenance.php']
18.Aug.2022 16:31:26 - POLLER: Poller[Main Poller] PID[320041] DEBUG: About to Spawn a Remote Process [CMD: /usr/bin/php, ARGS: -q '/var/www/html/cacti/poller_automation.php' -M]
18.Aug.2022 16:31:26 - POLLER: Poller[Main Poller] PID[320041] DEBUG: About to Spawn a Remote Process [CMD: /usr/bin/php, ARGS: -q '/var/www/html/cacti/poller_spikekill.php']
18.Aug.2022 16:31:26 - POLLER: Poller[Main Poller] PID[320041] DEBUG: About to Spawn a Remote Process [CMD: /usr/bin/php, ARGS: -q /var/www/html/cacti/poller_reports.php]
18.Aug.2022 16:31:26 - POLLER: Poller[Main Poller] PID[320041] DEBUG: About to Spawn a Remote Process [CMD: /usr/bin/php, ARGS: -q '/var/www/html/cacti/poller_commands.php' --poller=1]
18.Aug.2022 16:31:26 - SYSTEM STATS: Time:85.6246 Method:spine Processes:4 Threads:20 Hosts:79 HostsPerProcess:20 DataSources:468 RRDsProcessed:351
18.Aug.2022 16:31:26 - POLLER: Poller[Main Poller] PID[320041] Processing Poller Output with 1 maximum items to be processed
2022.08.18 16:31:25 - SPINE: Poller[Main Poller] PID[320059] PT[139908439282048] Time: 84.6782 s, Threads: 20, Devices: 20
2022.08.18 16:31:25 - SPINE: Poller[Main Poller] PID[320059] PT[139908439282048] DEBUG: Net-SNMP Close Completed
2022.08.18 16:31:25 - SPINE: Poller[Main Poller] PID[320059] PT[139908439282048] DEBUG: MYSQL Free & Close Completed
2022.08.18 16:31:25 - SPINE: Poller[Main Poller] PID[320059] PT[139908439282048] DEBUG: Allocated Variable Memory Freed
2022.08.18 16:31:25 - SPINE: Poller[Main Poller] PID[320059] PT[139908439282048] DEBUG: PHP Script Server Pipes Closed
2022.08.18 16:31:25 - SPINE: Poller[Main Poller] PID[320059] PT[139908439282048] DEBUG: SS[3] Script Server Shutdown Started
2022.08.18 16:31:25 - SPINE: Poller[Main Poller] PID[320059] PT[139908439282048] DEBUG: SS[2] Script Server Shutdown Started
2022.08.18 16:31:25 - SPINE: Poller[Main Poller] PID[320059] PT[139908439282048] DEBUG: SS[1] Script Server Shutdown Started
2022.08.18 16:31:25 - SPINE: Poller[Main Poller] PID[320059] PT[139908439282048] DEBUG: SS[0] Script Server Shutdown Started
2022.08.18 16:31:25 - SPINE: Poller[Main Poller] PID[320059] PT[139908439282048] DEBUG: Thread Cleanup Complete
2022.08.18 16:31:25 - SPINE: Poller[Main Poller] PID[320059] PT[139908439282048] DEBUG: Closing Local Connection Pool ID 19
2022.08.18 16:31:25 - SPINE: Poller[Main Poller] PID[320059] PT[139908439282048] DEBUG: Closing Local Connection Pool ID 18
2022.08.18 16:31:25 - SPINE: Poller[Main Poller] PID[320059] PT[139908439282048] DEBUG: Closing Local Connection Pool ID 17
2022.08.18 16:31:25 - SPINE: Poller[Main Poller] PID[320059] PT[139908439282048] DEBUG: Closing Local Connection Pool ID 16
2022.08.18 16:31:25 - SPINE: Poller[Main Poller] PID[320059] PT[139908439282048] DEBUG: Closing Local Connection Pool ID 15
2022.08.18 16:31:25 - SPINE: Poller[Main Poller] PID[320059] PT[139908439282048] DEBUG: Closing Local Connection Pool ID 14
2022.08.18 16:31:25 - SPINE: Poller[Main Poller] PID[320059] PT[139908439282048] DEBUG: Closing Local Connection Pool ID 13
2022.08.18 16:31:25 - SPINE: Poller[Main Poller] PID[320059] PT[139908439282048] DEBUG: Closing Local Connection Pool ID 12
2022.08.18 16:31:25 - SPINE: Poller[Main Poller] PID[320059] PT[139908439282048] DEBUG: Closing Local Connection Pool ID 11
2022.08.18 16:31:25 - SPINE: Poller[Main Poller] PID[320059] PT[139908439282048] DEBUG: Closing Local Connection Pool ID 10
2022.08.18 16:31:25 - SPINE: Poller[Main Poller] PID[320059] PT[139908439282048] DEBUG: Closing Local Connection Pool ID 9
2022.08.18 16:31:25 - SPINE: Poller[Main Poller] PID[320059] PT[139908439282048] DEBUG: Closing Local Connection Pool ID 8
2022.08.18 16:31:25 - SPINE: Poller[Main Poller] PID[320059] PT[139908439282048] DEBUG: Closing Local Connection Pool ID 7
2022.08.18 16:31:25 - SPINE: Poller[Main Poller] PID[320059] PT[139908439282048] DEBUG: Closing Local Connection Pool ID 6
2022.08.18 16:31:25 - SPINE: Poller[Main Poller] PID[320059] PT[139908439282048] DEBUG: Closing Local Connection Pool ID 5
2022.08.18 16:31:25 - SPINE: Poller[Main Poller] PID[320059] PT[139908439282048] DEBUG: Closing Local Connection Pool ID 4
2022.08.18 16:31:25 - SPINE: Poller[Main Poller] PID[320059] PT[139908439282048] DEBUG: Closing Local Connection Pool ID 3
2022.08.18 16:31:25 - SPINE: Poller[Main Poller] PID[320059] PT[139908439282048] DEBUG: Closing Local Connection Pool ID 2
2022.08.18 16:31:25 - SPINE: Poller[Main Poller] PID[320059] PT[139908439282048] DEBUG: Closing Local Connection Pool ID 1
2022.08.18 16:31:25 - SPINE: Poller[Main Poller] PID[320059] PT[139908439282048] DEBUG: Closing Local Connection Pool ID 0

</body>
</html>

**Comment by TheWitness** [comment]
This is fixed just today.  If running 1.2.22, just download a fresh `include/global_settings.php` and `poller_commands.php` from the 1.2.x branch.

Also, you can increase the timeout from `Console > Configuration > Settings > Poller`.

**Comment by densenator** [comment]
Don't help for my case.
I downloaded fresh both files and  increase the timeout.
Now I see:
ERROR: Process being killed due to timeout! (commands, master, 1, Process 527640, Time 1660884369, Timeout 600, Timestamp 1660884972)
And some graphs view:
![image](https://user-images.githubusercontent.com/18443709/185557672-64b9e1a8-507e-43eb-8db4-ed3829c983ab.png)

I decrease timeot again and now My settings:
![image](https://user-images.githubusercontent.com/18443709/185558903-61dd84c4-8566-425a-86b4-5a8413ae8ab6.png)

![image](https://user-images.githubusercontent.com/18443709/185559448-4da20741-0a8a-45a6-bd01-c2133845a91c.png)
![image](https://user-images.githubusercontent.com/18443709/185559554-c266e030-6ba8-4438-a45c-da232c7dd3dc.png)

**Comment by densenator** [comment]
I set to 10 concurrent processes and problem is gone.
But i see small drops here

**Comment by TheWitness** [comment]
You might need to increase `max_connections` in MySQL. Due to all this parallel stuff going on, you might need to buffer the number of connections a bit more (like in this case 10 more).  Technical support gives some estimates.

**Comment by TheWitness** [comment]
Resolved in #4892 and #4890
