### ISSUE TITLE
Pass poller status to script_server to avoid connecting to the main database when offline or in recovery

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#4899]
Currently, the script server is set up to accept just one option ( Spine)

It would be good to pass the Poller status to script server to adjust timeouts 
currently, since only spine is passed the script server is not aware if the remote poller is in an offline state
so the script server attempts to connect to the primary poller which slows down the scripts server causing timeouts

**Comment by TheWitness** [comment]
There will also be a corresponding spine change for this.
