### ISSUE TITLE
Host MIB - Hard Drive Space

### ISSUE THREAD

**Issue by SourceDoctor** [Cacti/cacti#490]
Sometimes Disc Capacity and remaining free Space are assigned to wrong Mount Points. Especially on Connections with high latency. For Example Cacti says one of my remote Server has a Swap Drive with a Capacity of 6TB, but this is the Capacity of the local Storage Mountpoint. The Swap Drive has a Capacity of 8GB.

**Comment by cigamit** [comment]
This is a duplicate of issue #454.  It's not an easy fix due to the complexity of the code, but working on it.
