### ISSUE TITLE
Auto logout issue after upgrade to 1.2.22

### ISSUE THREAD

**Issue by ldjvc** [Cacti/cacti#4908]
# Describe the bug

After upgrading from 1.2.18 to 1.2.22 the login screen will only display for a second and then the user is redirected to an "Automatic Logout" page which states that the user has been logged out due to a session timeout. The redirect stops the user being able to enter login credentials.

## To Reproduce

1. Go to the root URL of the installed Cacti

2. The user login screen is shown asking for username and password but a spinner is running at the top of the page and a second or so later the user is redirected to the Automatic Logout page. Clicking on the offered "Login Again" link takes the user back to the login credential entry page but again the spinner is running and a second or so later the user is redirected to the Automatic Logout page. Hitting esc a few times as soon as the login credential entry dialog shows stops the redirect from happening (kills the js I guess) and normal login can occur. Clearing cookies/restarting browser does not change this behavior. I have observed the same issue with version 1.2.20 and 1.2.21. 

## Expected behavior

Login screen should be displayed and not automatically redirect to a logout page.

## Screenshots

![image](https://user-images.githubusercontent.com/8614536/186598600-d5410c00-6579-4ffd-90f9-eab2edc9973d.png)

There is a mismatch in the above regarding Spine but this is just a DEV instance to test the upgrade process. The poller is not running.

## Desktop (please complete the following information)

- OS: RHEL 8.6

- Browser: FireFox

- Version: 102.0.1esr (64-bit)

## Additional context

PHP is running in FastCGI mode (php-fpm).

**Comment by TheWitness** [comment]
We had a change in our session storing for persistent logins between these releases.  The problem should go away on it's own, or you can force everyone to login again by running the following command:

```sql
TRUNCATE TABLE user_auth_cache;
```

**Comment by TheWitness** [comment]
I don't think we will be making any code changes around this, let me know that the issue is resolved once you truncate the table.

**Comment by TheWitness** [comment]
Okay, better to enable "remember me" support in Cacti which will keep you logged in from a specific browser for upto 90 days of inactivity.
