### ISSUE TITLE
Data Source Receiving Data but still na values on graph

### ISSUE THREAD

**Issue by BaptisteVlt** [Cacti/cacti#4910]
Hello everyone,
I've connected Cacti with iDirect in order to poll some RX and TX graphs.
RX-Snr graph is working well.
But for TX and RX trafic I've a problem.
For some reasons I've a lot of nan values :
![Capture](https://user-images.githubusercontent.com/45470774/186727841-4cda4e5d-b647-43ef-a251-61c4de83d9a5.PNG)

When I go to console - Troubleshooting - Data source and I run a check for RX Trafic for example :
![Capture1](https://user-images.githubusercontent.com/45470774/186727875-4fef777d-36a3-4991-8d55-bfae0daad966.PNG)

The data source can find the data so why I can't see them on the graph ?
Even if I think the data are too high, I first want to see them on the graph.
Then I'll deal with high values problem ...
Do you guys have any idea about this problem ?
Best regards,

**Comment by TheWitness** [comment]
See if the script actually returns the data that you are looking for.  If not, or that data is out of range (aka max value in Data Template), then you will continue to receive NaN values.

**Comment by TheWitness** [comment]
No feedback.
