### ISSUE TITLE
Datetime of boost performance is failed

### ISSUE THREAD

**Issue by manhvu1997** [Cacti/cacti#4911]
I installed Cacti 1.2.20 and enabled Boost performance, but the DateTime in boost performance is not matched with my system DateTime. How can I resolve it?
My Datetime boost performance
![image](https://user-images.githubusercontent.com/58839875/186820169-e40688d6-76c1-40df-8591-1b799d72672b.png)
My system Datetime
![image](https://user-images.githubusercontent.com/58839875/186820559-e4ae74a1-9d77-48fe-b7a7-044d226c65dc.png)

**Comment by TheWitness** [comment]
Update to 1.2.22.  There has been quite a bit of movement around boost since 1.2.19.
