### ISSUE TITLE
spine 1.2.22 compilation gives error ssl error

### ISSUE THREAD

**Issue by gj00354347** [Cacti/cacti#4912]
# Describe the bug

Dear Developers ,

we are on 1.2.21 and we learnt that cacti Group has released 1.2.22 cacti & Spine . So we started with downloading spine and compiling it in our Test Environment but got stuck at make command and found the below error .

gcc -DHAVE_CONFIG_H -I. -I./config     -I/usr/include/net-snmp -I/usr/include/net-snmp/.. -I/usr/include/mysql -g -O2 -MT sql.o -MD -MP -MF .deps/sql.Tpo -c -o sql.o sql.c
sql.c: In function âdb_connectâ:
sql.c:353:6: error: âssl_keyâ undeclared (first use in this function)
  if (ssl_key != NULL) {
      ^
sql.c:353:6: note: each undeclared identifier is reported only once for each function it appears in
sql.c:357:6: error: âssl_caâ undeclared (first use in this function)
  if (ssl_ca != NULL) {
      ^
sql.c:361:6: error: âssl_certâ undeclared (first use in this function)
  if (ssl_cert != NULL) {
      ^
make: *** [sql.o] Error 1

## To Reproduce

Download spine and try to install .

1. tar -xzvf cacti-spine.tar.gz
2. cd cacti-spine-1.2.22
3. ./bootstrap
4.  ./configure --prefix=/<path-to-cacti>/spine/1.2.22/ --enable-lcap
5. make 

and after make you have the above mentioned error on your shell .

7. Click on '....'

8. Scroll down to '....'

9. See error

## Desktop (please complete the following information)

kernel version 3.10.0-1160.49.1.el7.x86_64
Red Hat Enterprise Linux Server release 7.9 (Maipo)
mysql  Ver 15.1 Distrib 5.5.68-MariaDB
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
PHP 5.4.16 (cli) (built: Oct 29 2019 09:56:22)

**Comment by netniV** [comment]
This should be opened in the spine repo, not core.

**Comment by bernisys** [comment]
-> https://github.com/Cacti/spine/issues/279
