### ISSUE TITLE
cacti 1.2.18- Not plotting any graph & spike kill issue

### ISSUE THREAD

**Issue by anubhamangal** [Cacti/cacti#4913]
We are not able to get any graphs and data collection for any of the devices. Our spike kill configuration was changed to 6hrs from 12hrs and added a few templates post which we experienced this issue.

In Addition, receiving multiple  errors mentioning:

-Polling timeout
![image](https://user-images.githubusercontent.com/99225699/187154201-a3991878-646d-4e2f-b2e8-c4f6ecf8accc.png)

-Connection Broken in Function db
![image](https://user-images.githubusercontent.com/99225699/187154335-062908f8-7cae-4ee6-b9b5-efb6cd39531e.png)

could you please provide a resolution for the above errors? 

Thanks & Regards,
Anubha Mangal

**Comment by TheWitness** [comment]
You are running out of MySQL connections.  Increase your max_connections and restart MariaDB/MySQL.  Ensure that your process count is very low at first.  I monitor > 40k devices with 4 processes and 20 threads each.  If you have < 1000 devices, one process is generally enough.

**Comment by TheWitness** [comment]
You should also update to 1.2.22.  It's a solid release the builds on the prior release that all had some significant issues that were experienced with one section of the code or another and with some newer PHP versions.

**Comment by anubhamangal** [comment]
Hi,
For cacti 1.2.18, let's say if we have 4k devices what could be the max_connections set in approx and the threads too? Please advice

**Comment by TheWitness** [comment]
I would say for something like that, 2 processes and 20 threads.  Make sure the server has the SMT cores to support at leave 40 threads.  In other Say, 40 or so VCPU's if virtual and 20 cores in SMT mode for a physical machine.
