### ISSUE TITLE
[1.2.22] Zooming In/Out issue in preview mode

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#4914]
# Describe the bug
No abbility to zoom graph by clicking mouse on it.

## To Reproduce
URL: `graph_view.php?action=preview&reset=1&host_id=981`
I move mouse on graph the coursor don't change.
I try to click right mouse button - browser open context menu instead of Cacti Menu with options.

This issue occurs when user has no "Show Graph Action Icons" option enabled.

OS: Ubuntu
Browser: Chromium 104.0.5112.101
Cacti branch: 1.2.x

**Comment by TheWitness** [comment]
There is a new permission in the General section for User Permissions.  Enable it.

**Comment by interduo** [comment]
Ok so this is by design. Thanks for the information.

**Comment by TheWitness** [comment]
Correct.  It's caused some confusion, but people are figuring it out.
