### ISSUE TITLE
1.2.22 - ERROR PHP NOTICE: Undefined index: id in file: /usr/share/cacti/lib/functions.php on line: 2965

### ISSUE THREAD

**Issue by stultitiophobia** [Cacti/cacti#4915]
# Describe the bug

After the update to 1.2.22 when creating new graphs I get the error in the logs:

2022/09/01 07:56:24 - CMDPHP PHP ERROR NOTICE Backtrace: (/graphs_new.php[42]:form_save(), /graphs_new.php[164]:html_graph_new_graphs(), /lib/html_graph.php[465]:host_new_graphs_save(), /graphs_new.php[274]:create_save_graph(), /lib/template.php[2128]:push_out_host(), /lib/utility.php[794]:update_poller_cache(), /lib/utility.php[304]:api_poller_cache_item_add(), /lib/api_poller.php[97]:get_data_source_path(), /lib/functions.php[2634]:generate_data_source_path(), /lib/functions.php[2965]:CactiErrorHandler())

2022/09/01 07:56:24 - ERROR PHP NOTICE: Undefined index: id in file: /usr/share/cacti/lib/functions.php on line: 2965

## To Reproduce

Create new Diagrams 

## Expected behavior

No error message should been the logs

## Desktop (please complete the following information)

Ubuntu 20.04.5 LTS

**Comment by TheWitness** [comment]
Looks like whoever packaged Cacti for you missed an update in lib/functions.php.  Pull the one from the 1.2.x branch and you will be back in good shape.

**Comment by TheWitness** [comment]
That same line in the 1.2.x branch, in other words the 1.2.22 release is correct.
