### ISSUE TITLE
Cacti 1.2.20 can't mapping graph template after created in data queries

### ISSUE THREAD

**Issue by manhvu1997** [Cacti/cacti#4916]
Hi everyone
I install Cacti 1.2.20 on Ubuntu 20.04. My PHP version is 7.4
I created some graph templates like the picture below
![image](https://user-images.githubusercontent.com/58839875/188423231-489db368-4d3e-4f3c-905d-cd664f45e12e.png)
However, when I navigated to data queries, I added new data queries and after that, I associated some graph templates to it. I faced a problem is all the graph templates I created above not mounting to the dropdown list in the picture below. Can you help me to fix that issue?
![image](https://user-images.githubusercontent.com/58839875/188423775-ad646334-f798-46ba-8572-d7e94a97b0ce.png)

**Comment by TheWitness** [comment]
That's due to the fact that you already have the template in use.  You have to enable multiple templates.  However, the 'right' way to create a Graph is NOT what you are doing.  You should create Graphs from the Create menu pick and not what you are doing.
