### ISSUE TITLE
Graph template "duplicate" action does not working - 500 Internal Server Error

### ISSUE THREAD

**Issue by maximt** [Cacti/cacti#4923]
Trying to duplicate Graph Template in Templates menu but got 500 Internal Server Error.
Its seems that the problem in type casting for php > 5 versions.

To fix:

File 'lib/api_graph.php', function 'api_duplicate_graph', line 478

replace from:
`$save['hash'] = get_hash_data_query('', 'data_query_graph');`
to:
`$save['hash']              = get_hash_data_query(0, 'data_query_graph');`

**Comment by TheWitness** [comment]
Thanks fixed.
