### ISSUE TITLE
AD configuration problems, Cacti 1.2.19

### ISSUE THREAD

**Issue by nani81** [Cacti/cacti#4924]
Good morning, 
I am configuring the AD for authentication access to cacti.
If I configure unrestricted access, it works perfectly.
But if I add a membership to restrict access depending on which OU you belong to, it doesn't work.
I attach images.
PS: I have seen issue #4644 but the user does not post the resolution of the issue.
Can you help me? thanks 
![Con restriccion](https://user-images.githubusercontent.com/51642177/189309561-336926fa-8a48-4665-ba8f-f6fa8d5ea79f.png)
![Sin restriccion](https://user-images.githubusercontent.com/51642177/189309573-5e2742db-3af9-48be-b7e7-e3112800fddd.png)
![Error_log](https://user-images.githubusercontent.com/51642177/189310082-2cbb6f02-901f-485b-b9c9-16ae4b699e3f.png)
![Error_cacti](https://user-images.githubusercontent.com/51642177/189310099-695ca3ba-5348-4949-9226-3a93be5909d1.png)

**Comment by TheWitness** [comment]
I would suggest you review the code.  You could also use the `User Domains` feature to have some equivalent functionality.

**Comment by nani81** [comment]
> I would suggest you review the code. You could also use the `User Domains` feature to have some equivalent functionality.

I don't understand what you mean, sorry.

**Comment by TheWitness** [comment]
There is a request to automatically assign users to groups based upon their AD membership.  That feature enhancement has not gone anywhere due to other issues ahead of it in the pipeline.  Until then, you will have to seek the answers in the forums or the Cacti documentation as I have stated.

**Comment by nani81** [comment]
> Hay una solicitud para asignar automáticamente usuarios a grupos en función de su pertenencia a AD. Esa mejora de características no se ha ido a ninguna parte debido a otros problemas que se avecinan. Hasta entonces, tendrás que buscar las respuestas en los foros o en la documentación de Cacti como he dicho.

OK, thank you very much for your help
Best regards

**Comment by nani81** [comment]
> No worries. I think this must be a documentation issue. The process works perfectly especially when using Open LDAP. Can you look through the Cacti forums and the Cacti documentation for the procedure. Many users are using it, and no complaints from them in quite some time.

One question, can the DN have blanks? 
For example
CN=83 - group,ou=2 - group,dc=domain,dc=com

**Comment by TheWitness** [comment]
It's at least 128 characters.  You should continue this conversation on the forums.  Okay?
