### ISSUE TITLE
error php:  Implicit conversion from float

### ISSUE THREAD

**Issue by crequill** [Cacti/cacti#4928]
Every 5 minutes (cacti-poller), I get php errors in cacti.log:
2022/09/22 10:25:00 - ERROR PHP : Implicit conversion from float 5.5 to int loses precision in file: /usr/share/webapps/cacti/include/global_languages.php  on line: 507
2022/09/22 10:25:00 - ERROR PHP : Implicit conversion from float 5.5 to int loses precision in file: /usr/share/webapps/cacti/include/global_languages.php  on line: 516

The problem in code is isset($i18n[$args[1]]) . It can be avoid with isset($i18n[intval($args[1])]) but I am not sure it’s a good correction.

Just wait cacti-poller to have these php errors.
OS: Arch Linux
PHP: 8.1.10
Version: 1.2.22

**Comment by TheWitness** [comment]
How did you update?  This issue was solved some time ago.  Just wondering if you are really at a full 1.2.22.  suggest you apply the 1.2.x branch.

**Comment by crequill** [comment]
My global_languages.php from my installation is the same as global_languages.php on release 1.2.22 on github. Where is the problem?

**Comment by TheWitness** [comment]
Can you provide the full backtrace?  It'll show what page you were viewing.  We did have an issue previously, you global arrays line 732 should look like the following:

```php
330    => __('%0.1f Minutes', 5.5),
```

**Comment by crequill** [comment]
For information, 330    => __('%0.1f Minutes', 5.5) for 1.2.22 is line 731 of gjobal_arrays.php (see [github.com](https://github.com/Cacti/cacti/blob/release/1.2.22/include/global_arrays.php)).

Please find attached a log with backtrace.

[backtrace.log](https://github.com/Cacti/cacti/files/9646384/backtrace.log)

**Comment by TheWitness** [comment]
Yea, you need to quote that line.  I'm not sure how that happened.  Just change `5.5` to `'5.5'` problem solved.

**Comment by TheWitness** [comment]
But wait, there must be some other issue.  I need to assign @browniebraun as I'm running 1.2.23 on 8.1.11 and can not reproduce this.  What PHP version?

**Comment by TheWitness** [comment]
@browniebraun, can you look into this.  I'm at my wits end.  It happens when editing a Data Source profile and exercising the Heartbeat dropdown.

**Comment by crequill** [comment]
> But wait, there must be some other issue. I need to assign @browniebraun as I'm running 1.2.23 on 8.1.11 and can not reproduce this. What PHP version?

PHP version is 8.1.10-1

**Comment by crequill** [comment]
> @browniebraun, can you look into this. I'm at my wits end. It happens when editing a Data Source profile and exercising the Heartbeat dropdown.

I have this error each time cacti-poller is running.

**Comment by crequill** [comment]
> Yea, you need to quote that line. I'm not sure how that happened. Just change `5.5` to `'5.5'` problem solved.

Thanks. This avoid "implicit conversion from float" errors in cacti.log.

**Comment by browniebraun** [comment]
Issue will occur once user has chosen a different GUI language under user settings. 1.2.23 is affected, too.

**Comment by browniebraun** [comment]
fixed (see: https://github.com/Cacti/cacti/commit/eb2c0e5dd937c9f9771550a43233d90f8f32c0f7 )
