### ISSUE TITLE
Cacti PHP - Recommendations (web) date.timezone,>=,Error,A valid timezone that matches MySQL and the system

### ISSUE THREAD

**Issue by kuniyil** [Cacti/cacti#4929]
Cn you please somebody help me resolve Cacti PHP - Recommendations (web) date.timezone,>=,Error,A valid timezone that matches MySQL and the system issue, I have installed cacti v1.2.21 and my os is centos 7.5, I have updated time [zone](url) in php.ini file already then also facing the same issue, screenshot attached, Please help me

![cacti v1 2 21 timezon php we error](https://user-images.githubusercontent.com/30433937/191893153-c6e24ff0-4c3c-4ce1-aa41-44cd91eb0b80.PNG)

**Comment by TheWitness** [comment]
You basically need to set your `date.timezone` in your `php.ini` files, and then restart Apache.
