### ISSUE TITLE
Net-SNMP - Device I/O template Maximum Value is zero

### ISSUE THREAD

**Issue by Helmut1972** [Cacti/cacti#4935]
Hi,

fresh install of 1.2.22. Data Template "Net-SNMP - Device I/O" maximum value is 0 for Bytes_Read, Bytes_Written, Device_Reads and Device_Written resulting in empty graphs:

![image](https://user-images.githubusercontent.com/35489776/192358877-6543c88d-4515-4a4c-8e8c-b5bcc4be0b46.png)
![image](https://user-images.githubusercontent.com/35489776/192358567-efa8ea1b-4c8b-4782-973f-a9f7f0570e56.png)
![image](https://user-images.githubusercontent.com/35489776/192358604-a4f88430-42d0-49ca-99cf-de43eef73895.png)

After manually overriding the maximum values with "U" graphs work as expected:

![image](https://user-images.githubusercontent.com/35489776/192358970-f65a15ec-9ab2-49ea-b217-67c797d5b3ef.png)
![image](https://user-images.githubusercontent.com/35489776/192359043-ba52e4ae-82e0-4449-956f-163ea0408d07.png)
![image](https://user-images.githubusercontent.com/35489776/192359149-342f5e31-345c-4cd0-b443-6727e51574dd.png)

**Comment by TheWitness** [comment]
Yea, thanks for that.  I'll be updating the Device Packages before the 1.2.23 release.  Feel free to fix things up in the mean time.

**Comment by TheWitness** [comment]
This is now incorporated into the latest packages that will be released with 1.2.23.  Thanks for the feedback.
