### ISSUE TITLE
[1.2.22] Automated Graph Rules not working for SNMP Queried Indexes 

### ISSUE THREAD

**Issue by salt-is-good** [Cacti/cacti#4937]
# Describe the bug

We recently upgraded to Cacti-1.2.22 from an old 0.8.8a version.  We noticed that the automated graph rules are not working for snmp query indexed items.  The automated graph rules are returning no objects for SNMP Query indexes.  The automated device graph rules are working but not for the ones that require snmp queries with indexes such as interfaces.   

## To Reproduce

1. Go to 'Automation->Graph Rules'

2. Click on 'Show Matching Objects'

Once we do that we do not see the expected results for matching objects for snmp queried interfaces.  We have removed all of the Graph Creation Criteria and still do not see the expected interfaces showing.     

We have put the application in DEVEL debug mode and captured the query that it is running behind the scenes and do see the items in the database but they do not return back to automation_graph_rules.php page from the api_automation page.  

See attached file for output from DB and from the cacti.log file.

## Expected behavior

We would expect all of those objects to render in the automation_graph_rules.php page but it is only showing one interface as well as the graphs would be automatically created by the rules on device creation within the application

## Screenshots

![image](https://user-images.githubusercontent.com/114668976/193037220-22cfa23f-9fc2-4c96-b007-63e00e56b43d.png)

## Desktop (please complete the following information)

- OS: Windows 10

- Browser: Chrome

- Version: Version 105.0.5195.127 (Official Build) (64-bit)

## Additional context

[cacti-1.2.22-snmp-graph-rules-issue.txt](https://github.com/Cacti/cacti/files/9674874/cacti-1.2.22-snmp-graph-rules-issue.txt)

**Comment by TheWitness** [comment]
I don't see any graph creation criteria.  You need to add that.

**Comment by salt-is-good** [comment]
Even when i add a simple one like this still don't see the expected results:

![image](https://user-images.githubusercontent.com/114668976/193041420-32fb111d-a063-4d14-8509-3666753f4161.png)

**Comment by TheWitness** [comment]
Make sure graph automation is enabled and the rerun the rules for the device.  Setting is in Setting > General.

**Comment by TheWitness** [comment]
From device management select the device and then select rerun automation.  See if it's created then.

**Comment by salt-is-good** [comment]
So it will automatically create the graphs with this in the criteria for Graph Creation Criteria.  

![image](https://user-images.githubusercontent.com/114668976/193097950-eff4e5a3-a6d3-42fe-8d7c-b465ff59d1a3.png)

But will not will a simple AND statement that should match

![image](https://user-images.githubusercontent.com/114668976/193100113-0ac23031-ec08-4e8b-a328-35e8c09fbefd.png)

**Comment by bmfmancini** [comment]
The logged error can be fixed by pulling the latest lib/functions.php

I have not noticed a changed in automation rules let me try and re-create
what your seeing

**Comment by TheWitness** [comment]
Any updates @salt-is-good ?

**Comment by salt-is-good** [comment]
Have a workaround in place with the graph rules to make them work by using the ifType number (6|18|30|94|107|37|32|23|108) in the rules such as a regular expression match.  I used to the same regular expression match but just used the translation of the ifType name for the number such as this: 
 ^(adsl|atm|atmIma|ds1|ds3|frameRelay|frf16MfrBundle|ppp|pppMultilinkBundle|ethernetCsmacd)

It still is not rendering correctly to show matching objects in the automation_graph_rules.php page, but it is actually building the graphs using the modified ruleset even though it is not showing any matches on the page when testing the rule.   Here is a sample:

![image](https://user-images.githubusercontent.com/114668976/194061047-d971ea86-052b-47ae-b9e1-c70f33852714.png)

**Comment by TheWitness** [comment]
It sounds like we are not storing the text value and that the numeric value needs to be converted to the text value and that is likely not happening.  I guess we need to confirm that.  Up/Down is tricky as we do some string conversions there.

**Comment by TheWitness** [comment]
One this you can do is run this query, and let me know what comes back for you:

```sql
SELECT * FROM host_snmp_cache
WHERE host_id = host_in_question
AND field_name="ifOperStatus";
```

Comes back like this for me.  Odd, it's right...

```sh
+---------+---------------+--------------+-------------+------------+-------------------------+---------+---------------------+
| host_id | snmp_query_id | field_name   | field_value | snmp_index | oid                     | present | last_updated        |
+---------+---------------+--------------+-------------+------------+-------------------------+---------+---------------------+
|      13 |             4 | ifOperStatus | Up          | 1          | .1.3.6.1.2.1.2.2.1.8.1  |       1 | 2022-10-05 01:32:52 |
|      13 |             4 | ifOperStatus | Down        | 2          | .1.3.6.1.2.1.2.2.1.8.2  |       1 | 2022-10-05 01:32:52 |
|      13 |             4 | ifOperStatus | Up          | 3          | .1.3.6.1.2.1.2.2.1.8.3  |       1 | 2022-10-05 01:32:52 |
|      13 |             4 | ifOperStatus | Down        | 4          | .1.3.6.1.2.1.2.2.1.8.4  |       1 | 2022-10-05 01:32:52 |
|      13 |             4 | ifOperStatus | Down        | 5          | .1.3.6.1.2.1.2.2.1.8.5  |       1 | 2022-10-05 01:32:52 |
|      13 |             4 | ifOperStatus | Down        | 6          | .1.3.6.1.2.1.2.2.1.8.6  |       1 | 2022-10-05 01:32:52 |
```

**Comment by salt-is-good** [comment]
@TheWitness, any updates on this one?  As you can see there should have been several interfaces to show up in the matching objects in the automation_graph_rules.php filter.

**Comment by TheWitness** [comment]
I'd like to defer the Diagnosis to @bmfmancini as he uses this feature regularly.  Once he provides feedback, I can take action.

**Comment by bmfmancini** [comment]
@TheWitness  By looking at this I am thinking that this is related to https://github.com/Cacti/cacti/issues/4712
In that case the device takes a bit longer than most to respond to SNMP so autom8 looks for oper status that is not fully populated yet my guess is because the data query is still running 

If you run apply automation rules a few mins later the rules will run fine

@salt-is-good  what device is this ?

**Comment by TheWitness** [comment]
Not too sure about that, would have to do a code review.

**Comment by salt-is-good** [comment]
The sample device I provided is Cisco ISR 4321.  It does not have that many interfaces on it.

Yes.  The apply automation rules seem to run fine and builds the graphs using the graph rules.  There is no way to test the graph rules since the automation_graph_rules.php pages does not show the matching objects correctly.

**Comment by bmfmancini** [comment]
Then yes this is what I have seen but only on devices with slow snmp agents
either devices with alot of interfaces or older devices with slow snmp
agents

It's also more noticible in my testing on v3 than v2

**Comment by salt-is-good** [comment]
This device is very responsive to the snmp request and returns OID request data very quickly.   Also note, it responds and displays correctly in our previous version of cacti which was 0.8.8a (i know - very old) but it was working then.

**Comment by TheWitness** [comment]
I'll have to allocate time, but it's going to take a few weeks, going on vacation shortly.

**Comment by TheWitness** [comment]
@salt-is-good, one last thing to try.  You say that 0.8.8a is working good.  Great, then set the max bulk walk size from 'Auto' to 10 and see if it speeds up.  Even make it 20.  See below.

![image](https://user-images.githubusercontent.com/1439914/208320444-3dc37ba4-b039-4c50-832c-1e6908804824.png)

**Comment by TheWitness** [comment]
You should NOT install PHP-snmp BTW.  If it's installed and you uninstall, make sure you restart httpd and php-fpm if you are using it.

**Comment by TheWitness** [comment]
Also, if it's the whole 'AutoM8' process that is running long, you can disable Data Source verification on the Graph Templates for Interface Graphs.  That will slow down the Graph Creation if your Devices are out on the edge.

![image](https://user-images.githubusercontent.com/1439914/208320597-e76230af-5575-41e3-ae18-837bada8dda0.png)
