### ISSUE TITLE
Toolbar disappeared after update 1.2.14-1.2.22

### ISSUE THREAD

**Issue by ISekan** [Cacti/cacti#4939]
CentoOS
Cacti 1.2.14 -> 1.2.22
Where is turn on the panel?
![image](https://user-images.githubusercontent.com/17400240/193580164-11c52e5f-9050-4fd5-9a81-62ae6f2ef28a.png)
![image](https://user-images.githubusercontent.com/17400240/193580233-eb19a355-5e6a-420b-a8c2-9e3fe283a506.png)

**Comment by xmacan** [comment]
https://github.com/Cacti/cacti/issues/4240

**Comment by ISekan** [comment]
> #4240

Thanks a lot!
In cacti 1.2.22 it is sounds like
![image](https://user-images.githubusercontent.com/17400240/193618182-90ad5213-206d-4afe-98cf-e4ab8dd8f48e.png)
