### ISSUE TITLE
Cacti 1.2.18 - DB restart issue

### ISSUE THREAD

**Issue by anubhamangal** [Cacti/cacti#4949]
Hi,

I'm using Cacti 1.2.18 and facing an issue whenever restarting the Main server Database. 

After restarting the Main Poller database it stops collecting data which results in data loss.

Please find below the system specifications
Cacti 1.2.18
Spine 1.2.19
MariaDB 10.3.
OS: Linux
Browser: Chrome

Could you please advise how we can handle this issue?

Thanks In advance.

Regards,
Anubha Mangal

**Comment by bmfmancini** [comment]
Make sure the time is correct in the. Local machine

Are you restarting the dB mid poll. Or disabling polling first?

Do. You have boost enabled?

**Comment by anubhamangal** [comment]
Hi,
Yes, boost is enabled and DB restart was **NOT** done in the middle of the polling as per timestamps.

But I haven't disabled any pollers as it was unplanned system reboot/ patching. Also noted that the pollers and boost were not automatically running after restart

Please guide 

Thanks 
Anubha Mangal

**Comment by bmfmancini** [comment]
Boost will only run when either the max entries has been reached or the
update timer has been reached

If your using the cactid daemon make sure its started

Are you seeing any errors in log?

**Comment by anubhamangal** [comment]
We have 3K+ devices and polling happens every 5 min and the boost threshold is set to 8 million or 30 min time gap.
But we noticed that Boost did not start automatically when it crossed 8 million or the next start time as well.

We are looking for any recommendations which we can implement to avoid this issue from occurring in the future.

Thanks
Anubha Mangal

**Comment by thurban** [comment]
Can you check on which tables are "MEMORY" tables ? You can view this by going to Utilities -> System Utilities -> Technical Support then click on the "Database" tab.

MEMORY tables get cleared when you do a database/mysql restart

**Comment by TheWitness** [comment]
My advice is simple, get to 1.2.22 ASAP.  Lots of problems post 1.2.16 are fixed there, especially around boost. 

There are a few more coming in 1.2.23 to.  They are less impactful, but good updates.

**Comment by TheWitness** [comment]
Also, poller_output_boost should be InnoDB theses days.  The local data ids table can and should be memory.

**Comment by TheWitness** [comment]
Speaking specifically if 1.2.22 of course.

**Comment by TheWitness** [comment]
Going to close this as it's more of a support question.
