### ISSUE TITLE
device template ruijie ?

### ISSUE THREAD

**Issue by hendranata** [Cacti/cacti#4950]
Dear cacti,
i am looking device template for ruijie switch device.. anyone have that?
thanks

**Comment by bmfmancini** [comment]
You can check the forums under the templates and scripts section
But you may need to create one your self for this

Usually the snmp interfaces query will give you traffic for most devices

**Comment by hendranata** [comment]
yes they working for physical port..
but cant draw vlan..

**Comment by bmfmancini** [comment]
Yea so you would need to make a query to collect the vlan details

**Comment by hendranata** [comment]
how to make a query? 
u mean do we need to get the device template for ruijie?

**Comment by bmfmancini** [comment]
All you need to know is in this doc

https://docs.cacti.net/How-To-Data-Queries.md

**Comment by hendranata** [comment]
does anyone know how to draw vlan layer3 in ruijie switch under cacti?
MIB: 1.3.6.1.2.1.2.2.1.16
seems not working..any other idea?

**Comment by TheWitness** [comment]
Once you have created your Device Template. If you would like to share it, we can review, but let's continue this discussion on the forums.
