### ISSUE TITLE
.RRD file backup

### ISSUE THREAD

**Issue by Nitin797** [Cacti/cacti#4952]
Hi Team,

We are currently experiencing data loss over weekend in our Cacti application when we take an image level backup on Weekend and upon investigating found the **.rrd**files were causing the issue. Could someone suggest if we can exclude. **.rrd** files from backup list and would this cause any issue to our system like any historic data loss or something like that.
Please advise.

Cacti 1.2.18
Spine 1.2.19
MariaDB 10.3.
OS: Linux
Browser: Chrome

Regards,
Nitin

**Comment by bmfmancini** [comment]
So your doing a vm backup?
There will be a polling timeout due to the Io freeze but should not be an
extensive loss of data

You could do a client based backup and copy the rrd files without any
issues there  you want a backup of your sql dB and the rra files as they
are the most important files

**Comment by bmfmancini** [comment]
Not required to do a image backup a file backup will work too

**Comment by Nitin797** [comment]
Ok, thanks will try this way and update the status.

Regards,
Nitin Kumar

**Comment by TheWitness** [comment]
VM image snapshots will cause a data loss.  The is especially true as your system gets into the thousands of devices.  So, at all costs it should be avoided.  Instead use either NFS (a good one), or use RSYNC to NFS to backup the RRDfiles.  Under no circumstances should you allow VM snaps, period, full stop.

I've written a good backup plugin, but unfortunately is not publically available.
