### ISSUE TITLE
Add Device Template Classes to match the Classes in Upcoming release of the Package Plugin

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#4957]
# Feature Request

## Is your feature request related to a problem? Please describe

Add Classes to Device Templates to match those defined in the unreleased Package Plugin.

## Describe the solution you'd like

These have been needed for several years, but not implemented.

## Describe alternatives you've considered

Prefixing Templates with names.  Not nice.

**Comment by TheWitness** [comment]
Have proposed the following device classes.  Awaiting feedback before finalizing/closing.

```php
$device_classes = array(
	'application'  => __('Application Related'),
	'cacti'        => __('Cacti Related'),
	'database'     => __('Database Related'),
	'facilities'   => __('Facilities Related'),
	'general'      => __('Generic Device'),
	'hpc'          => __('HPC/Grid Computing'),
	'hypervisor'   => __('Hypervisor Related'),
	'license'      => __('Licensing Related'),
	'linux'        => __('Linux Related'),
	'loadbalancer' => __('Load Balancer'),
	'switch'       => __('Network Switch'),
	'router'       => __('Network Router'),
	'firewall'     => __('Network Firewall'),
	'storage'      => __('Storage Related'),
	'telephony'    => __('Telco Related'),
	'webserver'    => __('Web Server Related'),
	'windows'      => __('Windows Related'),
	'ups'          => __('UPS Related'),
	''             => __('Unassigned')
);
```

**Comment by bmfmancini** [comment]
Media converter  ( Fiber optic related or telco related )

**Comment by TheWitness** [comment]
What do you prefer, removing `Telco Related` and adding a number of others?  You are the expert...

**Comment by bmfmancini** [comment]
Yeah remove the telco in my opinion all of these devices can be put under that category

**Comment by TheWitness** [comment]
Okay, provided an updated list.  That would be great.  No rush.

**Comment by TheWitness** [comment]
Completing the circular reference here:

https://github.com/Cacti/cacti/issues/3421

**Comment by xmacan** [comment]
Wifi (ap, controller)

**Comment by xmacan** [comment]
Something like management (ILO, IPMI, iDrac, ...)

**Comment by xmacan** [comment]
Please add wireless

**Comment by TheWitness** [comment]
@xmacan, Wireless as in what?  Review the Example I provided @bmfmancini .

```php
device_classes = array(
    'wireless' => __('Daffy Duck, Fred Flintstone, etc.')
);
```
??

**Comment by TheWitness** [comment]
Okay, added both.
