### ISSUE TITLE
Where is install_package.php CLI script?

### ISSUE THREAD

**Issue by austinbutler** [Cacti/cacti#496]
During install it says, "If you choose not to install the packages, there is an 'install_package.php' cli script that can be used from the command line after the install is complete." I can't find that file anywhere on the filesystem or here in Github, except in documentation.

I am using Cacti from EPEL, version 1.0.4.

**Comment by cigamit** [comment]
It is in the cli directory.  However, until just recently there were issues.  I recommend that you move to 1.1.1 before you start using it.  Also, you should always --remove-orphans to prevent having a template that has issues with earlier versions of the template.  Having a test system is always important.

**Comment by cigamit** [comment]
You can continue to comment.  However, I will close this.

**Comment by austinbutler** [comment]
Should it be here? https://github.com/Cacti/cacti/tree/develop/cli
