### ISSUE TITLE
Add ESXi Device Template to Base Cacti Install

### ISSUE THREAD

**Issue by jdcoats** [Cacti/cacti#4961]
```
2022/10/17 15:40:06 - CMDPHP PHP ERROR WARNING Backtrace: (/script_server.php[264]:ss_esxi_vhosts(), /scripts/ss_esxi_vhosts.php[42]:CactiErrorHandler())
2022/10/17 15:40:06 - ERROR PHP WARNING: Use of undefined constant value - assumed 'value' (this will throw an Error in a future version of PHP) in file: /var/www/localhost/htdocs/cacti/scripts/ss_esxi_vhosts.php on line: 42
2022/10/17 15:40:06 - CMDPHP PHP ERROR WARNING Backtrace: (/script_server.php[264]:ss_esxi_vhosts(), /scripts/ss_esxi_vhosts.php[40]:CactiErrorHandler())
2022/10/17 15:40:06 - ERROR PHP WARNING: Use of undefined constant value - assumed 'value' (this will throw an Error in a future version of PHP) in file: /var/www/localhost/htdocs/cacti/scripts/ss_esxi_vhosts.php on line: 40
```

**Comment by jdcoats** [comment]
[ss_ups_basicstatus.php.log](https://github.com/Cacti/cacti/files/9803970/ss_ups_basicstatus.php.log)

**Comment by jdcoats** [comment]
[ss_esxi_vhosts.php.log](https://github.com/Cacti/cacti/files/9803988/ss_esxi_vhosts.php.log)

**Comment by TheWitness** [comment]
Can you attach the template resource files and scripts here?

**Comment by TheWitness** [comment]
[ss_esxi_vhosts.tar.gz](https://github.com/Cacti/cacti/files/9805603/ss_esxi_vhosts.tar.gz)

This 'might' work.

**Comment by TheWitness** [comment]
Send everything anyway.

**Comment by xmacan** [comment]
@jdcoats  - It is my (very old, maybe my first) template. If you find another problem, please let me know in the forum

**Comment by jdcoats** [comment]
[VMWare-ESXi.zip](https://github.com/Cacti/cacti/files/9810154/VMWare-ESXi.zip)

**Comment by TheWitness** [comment]
Can you upload the scripts and resource files too?

**Comment by jdcoats** [comment]
[esxi_cpu.txt](https://github.com/Cacti/cacti/files/10012900/esxi_cpu.txt)
[esxi_hw.txt](https://github.com/Cacti/cacti/files/10012901/esxi_hw.txt)

**Comment by TheWitness** [comment]
Thanks.  Just working on packaging it.  Talking to @xmacan too.  The package will break a few things without a cleanup of the Data Input method's as I'm switching from all the snmp information being passed to just passing the device id.

**Comment by TheWitness** [comment]
Closing this one.  Will add feature request to put the ESXi Template into Base.

**Comment by xmacan** [comment]
@TheWitness - thank you. Crossing this thing off my TODO list ;-)
