### ISSUE TITLE
Will the calculation rules of 95nth_percentile involve php and rrdtool versions?

### ISSUE THREAD

**Issue by htyypt** [Cacti/cacti#4963]
I have three sets of CACTI:
1. 0.8.8a+php5.3.3+rrdtool1.4.9
2. 0.8.8h+php5.6.40+rrdtool1.4.8
3. 1.2.20+php7.2+rrdtool1.7.2

For example, the 5-minute data in September should be 12 * 24 * 30=8640 pieces of data, and 8640*0.05 is 432, which should be calculated from the 433rd piece of data.

But they are handled separately as follows:
1. Some are 432, some are 433, I can't find their running rules
2. Always 433 (correct)
3. It is always 432 (the number is limited and the statistics are not accurate)

I looked at the graph_variables.php code for 0.8.8a and 0.8.8h, they are all the same, don't know why this is the result.

**Comment by htyypt** [comment]
Also, there is an error in the data time exported by 1.2.20:

Also, there is an error in the data time exported by 1.2.20:
2022-09 month data, according to the old version is 2022-09-01 0:05 - 2022-10-01 0:00, 1.2.20 is 2022-09-01 0:10 - 2022-10-01 0:05

![image](https://user-images.githubusercontent.com/81215528/196661023-03d830fb-4b63-4e7e-8833-5b047f084379.png)

**Comment by TheWitness** [comment]
There is a rounding function on the element number, you are suggesting we use a `ceil()` instead of a `floor()` function then?  One sample off?

**Comment by TheWitness** [comment]
This is the bit of code from `lib/graph_variables.php` line # 300 (approximately).  Do me a favor and change from `floor()` to `ceil()` and see if that makes the difference up.  Let us know.

![image](https://user-images.githubusercontent.com/1439914/196945784-1bd29e87-2fc8-4c2d-a8fc-90a853c66e47.png)

**Comment by htyypt** [comment]
TheWitness, there is one more question for you.

1.2.20（rrdtool 1.7.2） There is an error in the export time:
The 2022-09 month data shows 2022-09-01 0:05 - 2022-10-01 0:00, but it is actually 2022-09-01 0:10 - 2022-10-01 0:05.

But when I changed rrdtool to version 1.48, the problem disappeared, how can I go about it.

![image](https://user-images.githubusercontent.com/81215528/196955788-bd0de813-f7ea-450c-af6a-98eb0ea6916c.png)
![image](https://user-images.githubusercontent.com/81215528/196955871-89156fd5-adb9-4dbc-bcfb-3e41141c56f2.png)

**Comment by TheWitness** [comment]
Is your browsers time zone different than the servers?  This is a regression when we introduced that feature.  @thurban is working on a way to disable that until we get the feature more unified across not only Core Cacti, but the plugin architecture.  This should be resolved before too long.  Issue is here:

https://github.com/Cacti/cacti/issues/4926

**Comment by htyypt** [comment]
My browser is in the same timezone as the server and it doesn't seem to be the same problem.

**Comment by TheWitness** [comment]
Okay, but one issue per ticket.  Can you do the pull request?

**Comment by htyypt** [comment]
Regarding the first question, I have already submitted. I don't know if it is correct, please take a look.

**Comment by htyypt** [comment]
Sorry, please help to change it this time, I will learn.

**Comment by TheWitness** [comment]
No problem, it's queued up, but I'm heading out for vacation for next week or so.  Get it done when I get back.  In the mean time maybe @xmacan can pull it together.  I'll be monitoring from my phone.

**Comment by TheWitness** [comment]
Resolved.
