### ISSUE TITLE
[CACTI 1.2.23 - Latest Source] Tree search not hiding non-matching tree objects

### ISSUE THREAD

**Issue by anarkia1976** [Cacti/cacti#4964]
Hi Guys,

i'm using modern theme and the problem is related to: 

filter the devices in the search box in the tree view show all devices.

1. Go to Tab - Graphs.
2. Click into box - Search.
3. Search a specific Device or Devices with the same Description.

The problem seems to be present with all themes. 

Thanks a lot for support.

**Comment by TheWitness** [comment]
Really not enough information.  Check your browsers debug console windows for JavaScript issues.  It's working fine on my test systems.

**Comment by anarkia1976** [comment]
The problem is the behavior of the filter.
While in the previous version when you did a search it showed only the results present in the various trees, now it shows all the devices present, highlighting the one searched for.
This is a problem as we have several folders one for each model and for each being the same customer can have a device inside.
Is there any setting to make in order to disable the expansion in the search for customers not included in the search?

You can see it in the example "step4" for the DHL search, it highlights the customer but still shows all the others.

A thousand thanks.
![step1-added-new-device](https://user-images.githubusercontent.com/1744639/196870999-c0934504-d742-43d6-aa1d-98235445d5e3.jpg)

![step2-added-new-device-to-tree-server](https://user-images.githubusercontent.com/1744639/196871027-7df52edd-0876-4255-b338-2d31e53356fb.jpg)

![step3-filter-with-new-devices-after-upgrade-is-OK](https://user-images.githubusercontent.com/1744639/196871036-87cbc513-bacb-4ede-8635-6f410e1f7a17.jpg)

![step4-filter-is-working-but-all-devices-are-displayed](https://user-images.githubusercontent.com/1744639/196871043-360e2051-cb9b-4006-9427-ec25f273a954.jpg)

**Comment by TheWitness** [comment]
Yea, @browniebraun was working on it.  We are chatting this morning.  He'll see about getting it fixed up before the 1.2.23 release.  Just keep an eye on this ticket.

**Comment by browniebraun** [comment]
Not sure if this should really be called a bug, but it is true that the search will not hide non-matching trees, branches and leafs.
From my point of view this could be added to become a filter setting in a later release, but for now I will switch it back to "normal".

Additionally the filter will not be removed if the search pattern has been cleared again character by character.
