### ISSUE TITLE
When viewing the Device page, ensure that the Device Template filter only includes Devices Types in use

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#4966]
# Describe the Enhancement

There are so many Device Templates these days, but many we don't use.  Only show the ones in use when filtering from the main Devices page.

**Comment by netniV** [comment]
Before...
![image](https://user-images.githubusercontent.com/9052188/198997852-a4a7a397-9962-4b2f-948e-5dd996fc0909.png)

After...
![image](https://user-images.githubusercontent.com/9052188/198997887-fd49026b-5472-44b0-ba89-c7bcb383fd52.png)
