### ISSUE TITLE
How to create aggregate traffic in 1.0.x release? The second graph was form earlier release 0.8.8b and it was easy.

### ISSUE THREAD

**Issue by ndhami23** [Cacti/cacti#497]
![image](https://cloud.githubusercontent.com/assets/13357925/24447966/69c9061e-1492-11e7-9036-eb16bac89a1b.png)
![image](https://cloud.githubusercontent.com/assets/13357925/24447980/7369d946-1492-11e7-887e-1fae891b4eb4.png)
![image](https://cloud.githubusercontent.com/assets/13357925/24447988/7d0bb49c-1492-11e7-96ac-6a66cf18cb75.png)
![image](https://cloud.githubusercontent.com/assets/13357925/24447993/7fe4ac82-1492-11e7-9903-dd52f15846a6.png)

**Comment by cigamit** [comment]
Follow this video.  You can modify the parameters to get the view you had before, you just have to tinker with the template.

https://www.youtube.com/watch?v=yAp9rGeu-hw

**Comment by ndhami23** [comment]
I suppose there is a bug in aggregate plugin in 1.0.3 release. When i use "total similar data sources" option it shows rrd file does not exist problem but when "total all data source" option is selected in total type option field i am getting the graph but not in the way i want. 

![image](https://cloud.githubusercontent.com/assets/13357925/24557974/50575140-1659-11e7-9430-b29fbdb56341.png)
![image](https://cloud.githubusercontent.com/assets/13357925/24557977/54beb6ce-1659-11e7-8a60-d36e539c7369.png)
![image](https://cloud.githubusercontent.com/assets/13357925/24557984/586920d4-1659-11e7-8b08-2ff5991ae358.png)
![image](https://cloud.githubusercontent.com/assets/13357925/24557990/5d9adc5a-1659-11e7-8de1-2c7ef49f14c8.png)
