### ISSUE TITLE
innodb_buffer_pool_size changed in server configuration to some GB but in Cacti UI it shows additional 4GB

### ISSUE THREAD

**Issue by Nitin797** [Cacti/cacti#4970]
Hi Team,

we have updated our innodb_buffer_pool_size to some GB and restarted our DB post that when we went onto UI and see there is a difference with what we configured. It shows additional GB on UI.

Could you please let us know if that is the common behavior or what could be done.

Cacti 1.2.18
Spine 1.2.19
MariaDB 10.3.
OS: Linux
Browser: Chrome

Regards,
Nitin Kumar

**Comment by TheWitness** [comment]
Well, you have to show images and text. Could be the difference between GiB and GB.

**Comment by TheWitness** [comment]
This changes for the most part in 1.2.23.  just made the edit the other day.

**Comment by TheWitness** [comment]
If not, just show us the differences.

**Comment by Nitin797** [comment]
The value on server.cnf - 20480M
In UI - 24576M
The difference is 4096M.

**Comment by TheWitness** [comment]
We pull the data directly from MariaDB.  So, you should restart MariaDB.  Is it the primary poller or remote?

**Comment by TheWitness** [comment]
No feedback on this one.
