### ISSUE TITLE
No Graph - Version 1.2.22

### ISSUE THREAD

**Issue by Internet2022** [Cacti/cacti#4972]
![image](https://user-images.githubusercontent.com/116327795/197451358-be992f2c-6355-48c4-b9f6-97f5846a3c1a.png)
![image](https://user-images.githubusercontent.com/116327795/197451390-3ea067ec-9513-4e9c-bce2-1841622bcf0b.png)

**Comment by Internet2022** [comment]
![image](https://user-images.githubusercontent.com/116327795/197451933-bb7bedd8-7462-4494-aa58-47a7304073cd.png)

**Comment by bmfmancini** [comment]
I see you are using windows based on the path 
Change the graph format from the default SVG to PNG

go to settings > general

![image](https://user-images.githubusercontent.com/13388748/198460912-e9b71262-b575-46c5-89f5-0dae9d8cb3c5.png)

**Comment by Internet2022** [comment]
But i have other error
![image](https://user-images.githubusercontent.com/116327795/198908226-ef064faf-0532-4c41-9b82-3ef061a68aeb.png)

**Comment by netniV** [comment]
That would suggest the file path is invalid to the fputs clal.

**Comment by TheWitness** [comment]
Yea, basically the script server is failing.  You should test it this way:

```bash
php -q script_server.php
quit
```

Look for errors.

**Comment by TheWitness** [comment]
No feedback.
