### ISSUE TITLE
can not run poller_maintenance.php

### ISSUE THREAD

**Issue by crequill** [Cacti/cacti#4975]
Hello,

I activate log rotation in cacti but nothing occurs. So I search and find that poller_maintenance.php was not running. I can run this command from the command line but when it’s launched by cacti it doesn˚t work.

The launch is on line 149 of lib/poller.php (line 137 in your [code](https://github.com/Cacti/cacti/blob/develop/lib/poller.php))
exec($filename . ' ' . $args . ' > /dev/null 2>&1 &');

If I redirect it to a file, there is no ouput or error.

To run poller_maintenance, I wrap the command with parentheses:
exec('(' . $filename . ' ' . $args . ' > /dev/null) 2>&1 &');

arch linux
php 8.1.11
apache 2.4.54-2 
cacti 1.2.22

**Comment by bmfmancini** [comment]
Hmm this runs successful for me 

[root@cacti-main cacti]# php poller_maintenance.php --debug
Checking for Purge Actions
Checking for Account / Password expiration
[root@cacti-main cacti]# 

I see your using PHP 8.1.x I am running 7.3 wonder if thats the diff

**Comment by crequill** [comment]
As said previously running poller_maintenance.php from command line works well but not when done by poller.php.

**Comment by netniV** [comment]
The added brackets actually negate error output redirection I think. I think you are only redirecting errors that come from standard output of the inner command?  Since that would never contain errors it would do nothing ?

**Comment by crequill** [comment]
When I redirect to file and see nothing, bracket was not added and I just replace /dev/null with a file so 2>&1 remains in place.

**Comment by TheWitness** [comment]
You should add some `cacti_log()` statements inside of the poller to trace where the poller is breaking.

**Comment by crequill** [comment]
I already do it with error_log. php launch exec command and nothing after.

**Comment by TheWitness** [comment]
Can you revert to the original file and test again?  Also, the `exec_background()` function should be used for performing background execution.  It's included in `lib/poller.php`.

**Comment by crequill** [comment]
Yes l’exec call is in exec_background() function in lib/poller.php. I revert to the original file and add 2 error_log calls:
 error_log("Before\n",3,'/tmp/a');
 exec($filename . ' ' . $args . ' > /dev/null 2>&1 &');
 error_log("After\n",3,'/tmp/a');

And I add an error_log at the beginning in poller_maintenance.php:
error_log("In poller_maintenance\n",3,'/tmp/a');

In /tm/a, I get:
Before
After
Before
After
(…)

poller_maintenance.php is not running: exec in background is not running. If I delete & at the end of command, poller_maintenance.php is running. To call it in background, I have to add brackets.

**Comment by TheWitness** [comment]
That means there is some syntax issue with poller_maintenance.php.  You should run the following as the apache account:

```bash
php -q -d display_errors=On poller_maintenance.php
```

**Comment by TheWitness** [comment]
If you are getting these messages, then poller_maintenance.php is working.  It by itself does not insert a log entry.

![image](https://user-images.githubusercontent.com/1439914/201547858-07978039-263d-4a6d-b4ff-367784a3f4d8.png)

**Comment by TheWitness** [comment]
I've added maintenance stats for 1.2.23.  You should see them there.
