### ISSUE TITLE
[CACTI 1.2.23 - Latest Source] Tree Mode - Timestamp for Graphs didn't work - Gradient Option

### ISSUE THREAD

**Issue by anarkia1976** [Cacti/cacti#4976]
If you select "Tree Mode Graphs" and modify the custom presets to filter a specific period of date and time, the same does not work correctly.

![image](https://user-images.githubusercontent.com/1744639/197493483-b3dc7651-236b-49dc-9e84-4497d615336f.png)

The problem only occurs if you select the gradient in the options.

![image](https://user-images.githubusercontent.com/1744639/197493643-2989f47d-fe34-4caa-9d30-7b08aab4d7d1.png)

thanks a lot.

**Comment by bmfmancini** [comment]
I can confirm I am seeing the same behaviour in 1.2.22 and 1.2.23 even with the gradient option on
Whats very strange is that this does not seem to happen with the Admin user but it does happen with a regular user

![image](https://user-images.githubusercontent.com/13388748/197874347-6644964c-d64f-425b-ac7b-baeebfda7382.png)

I am seeing that the raw data in that time is the correct data

![image](https://user-images.githubusercontent.com/13388748/197874868-56dad660-0c42-4bf4-b432-28cbd87c5c32.png)

I have confirmed date and time is correct on both PHP and DB as well as poller timezone settings 

<html><body>


Date | Tue, 25 Oct 2022 16:27:18 -0400
-- | --
Cacti Version | 1.2.23
Cacti OS | unix
RSA Fingerprint | 9a:71:17:a2:e9:73:a6:3a:40:b2:d6:c9:59:85:a6:f6
NET-SNMP Version | NET-SNMP version: 5.7.2
RRDtool Version Configured | 1.8.0+
RRDtool Version Found | 1.8.0


</body>
</html>

DB time


MariaDB [(none)]> select NOW();
+---------------------+
| NOW()               |
+---------------------+
| 2022-10-25 16:28:24 |
+---------------------+
1 row in set (0.001 sec)

MariaDB [cacti]> select timezone from poller;
+-----------------+
| timezone        |
+-----------------+
| America/Toronto |
| America/Toronto |
| America/Toronto |
| America/Toronto |
+-----------------+
4 rows in set (0.001 sec)

Server time is also correct 

[root@cacti-main ~]# date
Tue Oct 25 16:29:04 EDT 2022

**Comment by bmfmancini** [comment]
The request header is in GMT despite the client being set to EST 
the time matches both the EST timezone  listed in the gprint from and to 
and matches the time stamps on the graph its like one of the timestamps are not being converted properly ?

![image](https://user-images.githubusercontent.com/13388748/197877006-7dc7b7eb-2616-4b03-b56f-dd993bee20ac.png)

**Comment by bmfmancini** [comment]
```

GET /cacti/graph_json.php?rra_id=0&local_graph_id=651&graph_start=1666643400&graph_end=1666729800&graph_height=200&graph_width=700 HTTP/1.1
Host: 192.168.1.22
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:106.0) Gecko/20100101 Firefox/106.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: en-CA,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate
X-Requested-With: XMLHttpRequest
Connection: keep-alive
Referer: http://192.168.1.22/cacti/graph_view.php?action=tree&node=tbranch-117&host_id=178&site_id=-1&host_template_id=-1&hgd=&hyper=true
Cookie: Cacti=v5roaas1029h41g1g3uiskuu8p; CactiDateTime=Tue Oct 25 2022 16:25:10 GMT-0400 (Eastern Daylight Saving Time); CactiTimeZone=-240


HTTP/1.1 200 OK
Date: Tue, 25 Oct 2022 20:31:04 GMT
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.3.33
X-Powered-By: PHP/7.3.33
Last-Modified: Tue, 25 Oct 2022 20:31:04 GMT
X-Frame-Options: SAMEORIGIN
Content-Security-Policy: default-src *; img-src 'self'  data: blob:; style-src 'self' 'unsafe-inline' ; script-src 'self'  'unsafe-inline' ; frame-ancestors 'self'; worker-src 'self' ;
P3P: CP="CAO PSA OUR"
Cache-Control: max-age=15
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Pragma: no-cache
Content-Length: 169759
Keep-Alive: timeout=5, max=99
Connection: Keep-Alive
Content-Type: application/json
```

**Comment by thurban** [comment]
@anarkia1976 can you specify in more detail what the issue is ?

From the graph/screenshot I can see that your custom from/to date/time is actually matchine the "From/To" text in the graph as well as the graph range.   The Graph starts at 20-10-2022 11:18 and ends at 24-10-2022 11:18. 

Can you clarify or provide an example how it should look like when working ?

**Comment by bmfmancini** [comment]
Removed my comments before as this seems to be something differnt

**Comment by anarkia1976** [comment]
> @anarkia1976 can you specify in more detail what the issue is ?
> 
> From the graph/screenshot I can see that your custom from/to date/time is actually matchine the "From/To" text in the graph as well as the graph range. The Graph starts at 20-10-2022 11:18 and ends at 24-10-2022 11:18.
> 
> Can you clarify or provide an example how it should look like when working ?

if you enable the console / settings function relating to the gradient in the graphs, the selection of a date range does not correspond to the graph shown.

disabling the function everything works correctly.

**Comment by thurban** [comment]
I understand that,, but can you provide an example of a graph where I can see this ? The graph you provided doesn't show this issue.

**Comment by thurban** [comment]
But that is exactly what is being shown ?   How does it look when you disable the gradient ?

**Comment by anarkia1976** [comment]
> But that is exactly what is being shown ? How does it look when you disable the gradient ?

All working as axpected.

**Comment by thurban** [comment]
Please provide a screenshot of this "all working as expected" using the same stat/end time.

**Comment by anarkia1976** [comment]
> Please provide a screenshot of this "all working as expected" using the same stat/end time.

Unfortunately I have seen that the problem is random, sometimes it works, other times it doesn't. It is not always present.
To reproduce it, it is necessary to insist on selecting the custom on different charts.

**Comment by thurban** [comment]
I assume you have boost enabled ?

**Comment by anarkia1976** [comment]
> I assume you have boost enabled ?

yes.

**Comment by thurban** [comment]
If the graph with the wrong time is showing UTC time, then it is indeed the same issue as bmfmancini has #4978

**Comment by anarkia1976** [comment]
> If the graph with the wrong time is showing UTC time, then it is indeed the same issue as bmfmancini has #4978

yes it's the same. closing this.
