### ISSUE TITLE
[CACTI 1.2.23 - Latest Source] Cacti Login page - can't change and create custom theme

### ISSUE THREAD

**Issue by anarkia1976** [Cacti/cacti#4977]
I noticed a theme issue.
It is impossible to create a custom theme that also reflects the LOGIN page.
The home page where user / password is entered always refers to the "modern" theme.
Could you tell me if I'm wrong in customization or there is some parameter to configure.

Example - theme is SET TO DARK - LOGIN PAGE:
always reflect - modern theme - include/theme/modern
![image](https://user-images.githubusercontent.com/1744639/197563318-23274328-2113-4076-ad5f-bc36a00b513f.png)

Example - theme is SET TO DARK - CACTI GUI:
alway reflect - dark theme - include/theme/dark
![image](https://user-images.githubusercontent.com/1744639/197563493-7012d563-1ef2-4664-a60e-3ece7a1683bf.png)

thanks a lot for support.

**Comment by anarkia1976** [comment]
> The theme used for the login screen will be set globally under Console->Configuration.

Thanks a lot, unfortunately I didn't know this thing, it works now.

**Comment by browniebraun** [comment]
You are welcome 🙂
