### ISSUE TITLE
Recommended value of sort_buffer_size is a negative

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#4981]
# Describe the bug
Recommended value of sort_buffer_size will be show as a a negative when "Maximum possible memory usage"(var `$totalMemorySans` in lib/utility.php) is larger then physical memory, 

## Screenshots
![image](https://user-images.githubusercontent.com/17589018/198966279-9e81d9d1-2a5e-4522-90b6-70c2cd6a7ee2.png)

## Possible Solution
Have not actual idea now, just log it

**Comment by netniV** [comment]
I believe that if you read what is written in red, the reason for this is that your combined memory usage is too much.  Therefore, not a bug.

**Comment by TheWitness** [comment]
Correct, pointing out this part.

**When performing joins, if they are below this size, they will be kept in memory and never written to a temporary file. As this is a per connection memory allocation, care must be taken not to increase it too high. The sum of the join_buffer_size + sort_buffer_size + read_buffer_size + read_rnd_buffer_size + thread_stack + binlog_cache_size + Core MySQL/MariaDB memory should be below 80%. If the recommendation is negative, you must decrease this and or the sort_buffer_size until the recommendation fits within the allowable memory.**

**Comment by ddb4github** [comment]
Just one cent about usability, How about:
* Make `join_buffer_size` line is red and disable next installation?
* Or change negative value to a red N/A or other something
* Or append few word in right long description to explain "negative recommended is a bad configuration".

**Comment by TheWitness** [comment]
I vote for just the red text.  Jing, can you draft a pull request?
