### ISSUE TITLE
Cacti install selects incorrect PHP binary location

### ISSUE THREAD

**Issue by ww849025879** [Cacti/cacti#4983]
- The PHP binary location is not valid and must be [updated.
![Uploading CCC.png…]()

**Comment by TheWitness** [comment]
You need to ensure that the path of the web server for PHP is properly set to what you want it to be, then it'll match.  I don't think this is a Cacti issue.  By the way, your "Uploading CCC.png" is not an image.  I'll close, but you can upload an image if you have not already solved your problem yet.

Also, next time, create your ticket in English.  Thanks!
