### ISSUE TITLE
Spelling mistake "Access Denied, please contact you Cacti Administrator."

### ISSUE THREAD

**Issue by Coool** [Cacti/cacti#4986]
# Spelling mistake
https://github.com/Cacti/cacti/blob/52dfc61e763d3d2dc94ee998046d6dd9ea17d457/locales/po/cacti.pot#L973

I'm not English expert, but "Access Denied, please contact your Cacti Administrator." sounds better?

**Comment by TheWitness** [comment]
That's an old commit.  Can you catch up in both 1.2.x?
