### ISSUE TITLE
Graphs are automatically created but not added to tree 1.1.1 (Apply automation rules works though)

### ISSUE THREAD

**Issue by stormonts** [Cacti/cacti#499]
I have graph rules which are executing correctly and creating graphs, but the tree items aren't being created.  However, if I select a number of graphs and then click the "Apply Automation Rules" option, the graph trees are automatically created and the graphs are added to the tree.

Below is my Tree rule and the associated Cacti log entries from when a system is first detected and the tree creation is automatically attempted. 

We are running Cacti 1.1.1 and MySQL 5.7.17. Wasn't sure if this is a bug or something on my end.
![tree-rule](https://cloud.githubusercontent.com/assets/25824323/24463287/5c0be6e0-1474-11e7-89fc-7aa5a678a22a.png)
![log](https://cloud.githubusercontent.com/assets/25824323/24463293/5dc8048c-1474-11e7-858d-6184240514f5.png)

**Comment by cigamit** [comment]
Resolved the SQL error.  Please update and test.
