### ISSUE TITLE
[CACTI - 1.2.23 - Latest Source] Utilities - External Link 

### ISSUE THREAD

**Issue by anarkia1976** [Cacti/cacti#4990]
Hi Guys,

When you create an external links to a web page with a user that has the correct permissions, for example USER1, the latter is able to correctly view the site as a TOP TAB and recall it.

USER1
![image](https://user-images.githubusercontent.com/1744639/200263159-97858b8a-5b48-4c29-aaae-8087a30c4377.png)

![image](https://user-images.githubusercontent.com/1744639/200262793-78c47fd5-c592-4dd0-bcdb-9c87a5218897.png)

If you create a second user, for example USER2 with the same permissons, the same will correctly display the URL in the external links but will not be able to recall it due to a permissions problem.

USER2
![image](https://user-images.githubusercontent.com/1744639/200262972-78d5ae6b-d3a4-4a62-9993-665e2e00277e.png)

```
2022-11-07 09:17:04 - CMDPHP PHP ERROR NOTICE Backtrace: (/links.php[37]:form_actions(), /links.php[186]:CactiErrorHandler())
2022-11-07 09:17:04 - ERROR PHP NOTICE: Trying to access array offset on value of type null in file: /var/www/html/cacti/links.php on line: 186
2022-11-07 09:16:05 - CMDPHP PHP ERROR NOTICE Backtrace: (/links.php[37]:form_actions(), /links.php[186]:CactiErrorHandler())
2022-11-07 09:16:05 - ERROR PHP NOTICE: Trying to access array offset on value of type null in file: /var/www/html/cacti/links.php on line: 186 
```

I don't know if the behavior is correct or if the external links must be personal and not viewable by other users.

Thanks a lot.

**Comment by TheWitness** [comment]
What PHP version?

**Comment by anarkia1976** [comment]
> What PHP version?

php -v
PHP 7.4.3 (cli) (built: Aug 17 2022 13:29:56) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

**Comment by anarkia1976** [comment]
I have seen that when an external link is created by a specific user, in order to make it seen by others, you have to change the settings of the individual user.
I do not know if it is correct, the problem is that when you have many users you should go hand in hand to give the permissions one by one.

![image](https://user-images.githubusercontent.com/1744639/200342700-46f717b1-f207-45ba-b6a8-912932f24ee0.png)

**Comment by TheWitness** [comment]
Thanks for reporting that backtrace.  That was a bug and I'll use this ticket to correct it.  On the other issue, it seems quite odd.  First, you have to grant the user access to the links, and then you have to give them access to the specific link.  Maybe you did one and not the other.

**Comment by TheWitness** [comment]
Did you use the 'Copy User' dropdown to make the new user?  If so, and it did not set the Links realms, that is another bug.
