### ISSUE TITLE
Graph Name in Graph Management shows the same name multiple times.

### ISSUE THREAD

**Issue by Coporton** [Cacti/cacti#4996]
# Describe the bug
I don't know why but I checked several times. The result is still the same. Graph Name in Graph Management shows the same name multiple times.

## To Reproduce

1. Go to 'Console'
2. Click on 'Management'
3. Click on 'Graphs'
4. See the Graph Name

## Expected behavior

It's showing the same name multiple times with the same URL.

## Screenshots
![Cacti Error](https://user-images.githubusercontent.com/89565607/200818491-44e903e2-f17f-4aca-a059-e99e569cc59a.png)

## Desktop (please complete the following information)

chrome
1.2.23

**Comment by TheWitness** [comment]
Appreciate you reporting this one.

**Comment by TheWitness** [comment]
Please run this query and let me know if you get duplicates:

```sql
SELECT gtg.id, gl.id AS local_graph_id,
        gtg.height, gtg.width, gtg.title_cache, gt.name, gl.host_id,
        IF(gl.graph_template_id = 0, 0, IF(gl.snmp_query_id = 0, 2, 1)) AS graph_source,
        IF(gl.snmp_query_id > 0, sqg.name, gt.name) AS source_name
        FROM graph_local AS gl
        INNER JOIN graph_templates_graph AS gtg
        ON gl.id=gtg.local_graph_id
        LEFT JOIN graph_templates AS gt
        ON gl.graph_template_id=gt.id
        LEFT JOIN aggregate_graphs AS ag
        ON ag.local_graph_id=gl.id
        LEFT JOIN host AS h
        ON h.id=gl.host_id
        LEFT JOIN sites AS s
        ON h.site_id=s.id
       ORDER BY gl.id
       LIMIT 20 ;
```

**Comment by TheWitness** [comment]
Lastly, on line 2222 of `graphs.php`, take the query for the variable `$graph_list` and put it inside of a `cacti_log()` function call.  After that, render the page once, and then goto the cacti.log and post what the query you find there.  Just to be clear:

```php
$graph_list = db_fetch_assoc("blah");

cacti_log("blah");
```

**Comment by Coporton** [comment]
Thanks, @TheWitness. I ran the query and got zero duplicates but I don't understand your second instruction. Actually, I'm not that smart... :(

**Comment by TheWitness** [comment]
Well for me this is philanthropic work. so if you want free support you're going to have to meet me halfway.  I'll patiently await you to provide the response I requested.

**Comment by Coporton** [comment]
I understand the situation, my friend. Anyways, After doing some research, I may able to understand what you wanted to say. The query works. Now I can see the single result on GUI, however only 20 rows according to the statement. 

In the cacti log, I found no error. Please have a look. 
![1](https://user-images.githubusercontent.com/89565607/200870389-f92af9fa-9832-4675-a461-9c36389c625b.png)

**Comment by bmfmancini** [comment]
Do you have any plugins installed ?

**Comment by bmfmancini** [comment]
Also run /cacti/cli/audit_database --report

**Comment by Coporton** [comment]
Hi, @bmfmancini, no I don't have any installed plugins. Actually, I am just trying to follow the instruction that @TheWitness told me to do.

**Comment by bmfmancini** [comment]
Hmm I am not able to replicate on 1.2.23 


![image](https://user-images.githubusercontent.com/13388748/200876533-0a8237c7-a04c-4df9-92b3-7b8cf65de468.png)

**Comment by bmfmancini** [comment]
@Coporton  run audit_database --report and check for any errors/warnings

**Comment by TheWitness** [comment]
Copy Paste the text of that log message.  Here. Then I'll have a follow-up query for you to run.

**Comment by Coporton** [comment]
@TheWitness, here is the log message report

2022-11-09 21:00:27 - CMDPHP SELECT gtg.id, gl.id AS local_graph_id, gtg.height, gtg.width, gtg.title_cache, gt.name, gl.host_id, IF(gl.graph_template_id = 0, 0, IF(gl.snmp_query_id = 0, 2, 1)) AS graph_source FROM graph_local AS gl INNER JOIN graph_templates_graph AS gtg ON gl.id=gtg.local_graph_id LEFT JOIN graph_templates AS gt ON gl.graph_template_id=gt.id LEFT JOIN aggregate_graphs AS ag ON ag.local_graph_id=gl.id LEFT JOIN host AS h ON h.id=gl.host_id LEFT JOIN sites AS s ON h.site_id=s.id ORDER BY gl.id LIMIT 20;

**Comment by Coporton** [comment]
@TheWitness Forgive me, if I input wrong. I have added, As you told me, 

.......
After 2222 line...

`	$graph_list = db_fetch_assoc("SELECT gtg.id, gl.id AS local_graph_id,
        gtg.height, gtg.width, gtg.title_cache, gt.name, gl.host_id,
        IF(gl.graph_template_id = 0, 0, IF(gl.snmp_query_id = 0, 2, 1)) AS graph_source
        FROM graph_local AS gl
        INNER JOIN graph_templates_graph AS gtg
        ON gl.id=gtg.local_graph_id
        LEFT JOIN graph_templates AS gt
        ON gl.graph_template_id=gt.id
        LEFT JOIN aggregate_graphs AS ag
        ON ag.local_graph_id=gl.id
        LEFT JOIN host AS h
        ON h.id=gl.host_id
        LEFT JOIN sites AS s
        ON h.site_id=s.id
       ORDER BY gl.id
       LIMIT 20 ;");
	   
cacti_log("	$graph_list = db_fetch_assoc("SELECT gtg.id, gl.id AS local_graph_id,
        gtg.height, gtg.width, gtg.title_cache, gt.name, gl.host_id,
        IF(gl.graph_template_id = 0, 0, IF(gl.snmp_query_id = 0, 2, 1)) AS graph_source
        FROM graph_local AS gl
        INNER JOIN graph_templates_graph AS gtg
        ON gl.id=gtg.local_graph_id
        LEFT JOIN graph_templates AS gt
        ON gl.graph_template_id=gt.id
        LEFT JOIN aggregate_graphs AS ag
        ON ag.local_graph_id=gl.id
        LEFT JOIN host AS h
        ON h.id=gl.host_id
        LEFT JOIN sites AS s
        ON h.site_id=s.id
       ORDER BY gl.id
       LIMIT 20 ;");");`

..........
And I got the same output in the cacti log.

**Comment by TheWitness** [comment]
Still wrong.  You might want to restore that file.  Let's take another approach

1) do you have any plugins installed.  If so, what are they?
2) is this a new install or an upgrade?  If an upgrade, what was the original version at it's inception?

**Comment by Coporton** [comment]
I have already restore the original file. it's showing same name in multiple times like before.

01. No, I didn't install any extra plugins.
02. This is new install. Version 1.2.23

I followed the GitHub install instructions

**Comment by TheWitness** [comment]
What interface graphs did you create for each of these interfaces?

**Comment by Coporton** [comment]
I'm using Interface - Traffic (bits/sec) template for all the graph name created.

**Comment by Coporton** [comment]
Hi @TheWitness, I just replaced the `$graph_list` statement with your given statement from line no. 2200 in cacti/graphs.php, which works as I wanted. Now data retrieve single entries as it should.

> 
	$graph_list = db_fetch_assoc("SELECT gtg.id, gl.id AS local_graph_id,
		gtg.height, gtg.width, gtg.title_cache, gt.name, gl.host_id,
		IF(gl.graph_template_id = 0, 0, IF(gl.snmp_query_id = 0, 2, 1)) AS graph_source,
		IF(gl.snmp_query_id > 0, sqg.name, gt.name) AS source_name
		FROM graph_local AS gl
		INNER JOIN graph_templates_graph AS gtg
		ON gl.id=gtg.local_graph_id
		LEFT JOIN graph_templates AS gt
		ON gl.graph_template_id=gt.id
		LEFT JOIN aggregate_graphs AS ag
		ON ag.local_graph_id=gl.id
		LEFT JOIN host AS h
		ON h.id=gl.host_id
		LEFT JOIN sites AS s
		ON h.site_id=s.id
		LEFT JOIN snmp_query_graph AS sqg
		ON gl.snmp_query_id = sqg.snmp_query_id
		AND gl.graph_template_id = sqg.graph_template_id
		$orphan_join
		$sql_where
		$sql_order
		$sql_limit");

Thank you so much, everyone. Thanks for your valuable support & I appreciate it.

**Comment by TheWitness** [comment]
Just reproduced it 👍

**Comment by TheWitness** [comment]
Okay, this looks like a regression with regards to a few Graph Templates that were recently packaged.  I have to research the source package.  I'll get you a Delete Statement shortly.

**Comment by TheWitness** [comment]
Is this an upgrade?  Did you by chance import the CISCO ASA Template?

**Comment by TheWitness** [comment]
This is partially resolved.  We have to determine what do to in these cases though.

**Comment by TheWitness** [comment]
This is resolved now.
