### ISSUE TITLE
upgrade to `898b31c01` results in missing DB table 'cacti.user_auth_row_cache'

### ISSUE THREAD

**Issue by dsclassen** [Cacti/cacti#4997]
# Describe the bug

I recently updated our cacti installation and the graph view is broken and the log files are inundated with these errors:

```
022-11-09 09:18:26 - CMDPHP ERROR: A DB Exec Failed!, Error: Table 'cacti.user_auth_row_cache' doesn't exist
```

Is there some way to "refresh" the DB?

**Comment by TheWitness** [comment]
Scott, set your version back to 1.2.22 in the version table to force an upgrade.  It'll add the table.

**Comment by dsclassen** [comment]
All fixed. Thanks.

**Comment by TheWitness** [comment]
Scott, the most recent changes are designed to speed up page rendering.  Getting the row counters is a very expensive query especially on real large systems like the one at my office.  Let us know if you run into issues with it.
