### ISSUE TITLE
Failed to load snmp protocol from nms

### ISSUE THREAD

**Issue by Seokanghogithub** [Cacti/cacti#4998]
# Describe the bug

## To Reproduce

Hello.
I am the user who is using the nms you developed.
There is no problem elsewhere, but only one instrument cannot load information from nms normally.
Required information such as LAN and WAN was not loaded.
I need your help. Please check.
Thank you.

## Expected behavior

![image](https://user-images.githubusercontent.com/117891410/201231329-1fbe1bc0-1d0a-47f7-9ff1-a767f97df57b.png)

Interface information for the device.
You must register this information.
Upload using the snmp protocol.
However, it was not uploaded successfully.

## Screenshots
![image](https://user-images.githubusercontent.com/117891410/201015862-46610585-8a3d-4165-b739-5b80e656bec6.png)

## Desktop (please complete the following information)

- windows

- chrome

- Version 1.2.21 | (c) 2004-2022 - The Cacti Group

**Comment by TheWitness** [comment]
Your description does not provide enough information.  Please elaborate more.

**Comment by Seokanghogithub** [comment]
> 귀하의 설명은 충분한 정보를 제공하지 않습니다. 더 자세히 설명해주세요.
I added a little more explanation.
Can I check the problem with this?

**Comment by TheWitness** [comment]
So, are you saying you are missing interface graphs?  If so, you must create them by hand, or use an automation rule for that.  Please follow the documentation for creating graphs.

**Comment by TheWitness** [comment]
Closing as this would appear to be a support request.  You can continue to ask questions, but please look into the documentation on creating graphs and Cacti automation.

**Comment by Seokanghogithub** [comment]
Automation rules were used, but graphs were missing.
Is there a way to insert interface graphics manually?
If so, could you link the documents related to it?

**Comment by TheWitness** [comment]
Before you go there.  If you are using 1.2.23, the Device Packages were damaged from a Data Query perspective.  If sync your 1.2.23 install, then re-import the net-snmp device package, the issue will be fixed.

As far as how to do it, follow the documentation.

**Comment by Seokanghogithub** [comment]
![image](https://user-images.githubusercontent.com/117891410/201557759-2c354c10-8123-414f-972c-8162a4491bcc.png)

I was able to confirm 1.2.22.
But I don't know where the 1.2.23 version is.

**Comment by TheWitness** [comment]
You have to download the 1.2.x branch from GitHub.com.

**Comment by Seokanghogithub** [comment]
If you are installing 1.2.23 version
Is it correct that the problem I requested has been solved?
Is there any data that this problem has been resolved in a place like a release note?

**Comment by Seokanghogithub** [comment]
> You have to download the 1.2.x branch from GitHub.com.

If you are installing 1.2.23 version
Is it correct that the problem I requested has been solved?
Is there any data that this problem has been resolved in a place like a release note?

I have an additional question
Everywhere else, all interface information is displayed normally.
Why did this happen in one place?
If the code was a problem, shouldn't the information everywhere else be wrong?

**Comment by Seokanghogithub** [comment]
> Before you go there. If you are using 1.2.23, the Device Packages were damaged from a Data Query perspective. If sync your 1.2.23 install, then re-import the net-snmp device package, the issue will be fixed.
> 
> As far as how to do it, follow the documentation.

Isn't this solution impossible because the version we are using is 1.2.21 version?

**Comment by TheWitness** [comment]
Well, 1.2.23 will allow this to be easily fixed.  To be released next month.  If you grab the 1.2.x release, you can get the fixes early with some risk.

**Comment by Seokanghogithub** [comment]
> Well, 1.2.23 will allow this to be easily fixed. To be released next month. If you grab the 1.2.x branch, you can get the fixes early with some risk.

Thank you for your reply.

I will wait until the 1.2.23 version comes out next month.
If these symptoms appear again after the update, I will contact you again.

**Comment by TheWitness** [comment]
Cool
