### ISSUE TITLE
Bug: Error 404 on cacti website

### ISSUE THREAD

**Issue by mikygee** [Cacti/cacti#5008]
Hello,

The link on cacti website old versions and patches leads to a page 404
![image](https://user-images.githubusercontent.com/2222550/202043356-90529e6f-ca75-4cfa-a742-d438be30b94e.png)

On page https://files.cacti.net/old it's a 404

Regards

**Comment by TheWitness** [comment]
This one's been out there for a while.  Our website administrator is too busy to fix it.  So, I hacked in a fix.
