### ISSUE TITLE
Can't display graphs with new chrome version 57.0.2987.98

### ISSUE THREAD

**Issue by gmuellerfr** [Cacti/cacti#501]
Hello,

I was two weeks on vacation. Yesterday I've started my workstation running linux and updated chrome to the newest version

Version 57.0.2987.98 (64-bit)

Now I can't display the graphs because of the following error displayed after starting cacti:

Validation error for variable tree_id, with value of "11?newtheme=1". See backtrace below for more details.
(/graph_view.php: 177 get_filter_request_var)(/lib/html_utility.php: 430 die_html_input_error)(/lib/html_validate.php: 60 cacti_debug_backtrace)

The pages have been displayed correct before with version 56.0.2924.76 (64-bit) of chrome. 
Pages will be displayed correct with firefox  version 52.0.1 (64-bit).
I'm still on cacti version 1.0.4.

Who is to blame?

Kind regards
Guenter

**Comment by cigamit** [comment]
Please upgrade to 1.1.1.  Also, please insure that you are using RRDtool 1.3+
