### ISSUE TITLE
Unable to edit any report items as site_id is not a column

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#5014]
# Describe the bug

Try to edit or create a report item and it will state that site_id is not a valid column. 

## To Reproduce

1. Click Reporting
2. Edit or Create a report
3. Click Items
4. Edit or Create an item
5. Click Save on the Item
6. See error message

**Comment by netniV** [comment]
This appears to have been broken with commit 26e2dbacf298265ce9e517f6f1f008ec46167b5d

**Comment by TheWitness** [comment]
Everything looked correct to me, when you re-ran the upgrade, did it work?

**Comment by netniV** [comment]
It took two attempts but that did make it work.  Curious if other users are missing that field.

**Comment by TheWitness** [comment]
I'm wondering if the prior step is failing somehow.  Should be caught and logged. Lots of testing coming up.

**Comment by anarkia1976** [comment]
> It took two attempts but that did make it work. Curious if other users are missing that field.

Hi guys, tested. No problem so far. Latest cacti 1.2.x branch.
