### ISSUE TITLE
1.3.0 - HoltWinter Prediction feature in Cacti

### ISSUE THREAD

**Issue by gj00354347** [Cacti/cacti#5022]
# Feature Request

## Is your feature request related to a problem? Please describe

Hi Developers ,

we are taking care of our Data center and the folks who owns the switches , routers , Load balancers , Firewalls they want to have a HoltWinter kind of prediction in cacti so that during Christmas and other festivals or let's say during any gala event like Olympics or some other event they want to predict the traffic using HoltWinter Prediction .

so is it possible to have this kind of feature in cacti so that we can predict the traffic in peak times , weekend or gala events and accordingly we do the capacity planning so that end consumer's experience is not impacted.

I am on 1.2.18 but planning to upgrade it to 1.2.22 very soon.

Looking forward to hear the good news ); from you folks .

Best Regards,
Gopal

## Describe alternatives you've considered

A clear and concise description of any alternative solutions or features you've
considered.

**Comment by TheWitness** [comment]
There is an article out there that shows how to do it without HoltWinters.  I don't think it's a horribly big thing to do.  However, we would need someone to contribute an example of how it would be used.

**Comment by gj00354347** [comment]
> Honestly, I wouldn't even know where to start. I gues the first step would be look up HoltWinter. Then figure out how that applies to RRD files.

Any Idea any wild
Guess Vinten by when can we expect this in cacti ??

**Comment by gj00354347** [comment]
> There is an article out there that shows how to do it without HoltWinters. I don't think it's a horribly big thing to do. However, we would need someone to contribute an example of how it would be used.

Can you please help
Me
With url ??

**Comment by TheWitness** [comment]
@gj00354347,

I posted this to give you some reading while we address the HoltWinters gap.  I'm pretty sure we have the PREDICT function published now in the more recent 1.2.x releases.  You can see here:

![image](https://user-images.githubusercontent.com/1439914/204349037-b76925fa-d60e-4f7f-a1f6-8a09b42feb54.png)

https://forums.cacti.net/viewtopic.php?t=62394

Larry

**Comment by TheWitness** [comment]
Here is another article where HoltWinters is actually explained:

https://www.usenix.org/legacy/events/lisa2000/full_papers/brutlag/brutlag_html/index.html

There are a few examples there too.

**Comment by TheWitness** [comment]
We are going to close this one.  We achieved much of what we hoped for, but the holt winters requires a large architecture change.  We can revisit at a later date.
