### ISSUE TITLE
restrict area used by the tree in tree mode

### ISSUE THREAD

**Issue by gmuellerfr** [Cacti/cacti#503]
Hello,

I have a enhancement request.

It would be nice to have the possibility to restrict the amount of pixels used by the tree itself.
If you go deeper and deeper into the tree hierarchy graphs become smaller and smaller as the tree area will be dynamically extended.

Kind regards
Guenter

**Comment by DavidLiedke** [comment]
I have suggested something similar
https://github.com/Cacti/cacti/issues/417

**Comment by cigamit** [comment]
I'm not too thrilled about shrinking the icons.  What about widening the viewport.  First we would add a widget to hide the remainder of the form up top, then we could simply grow the landing zone as you added tree elements.

**Comment by gmuellerfr** [comment]
I'm not sure wether we talk about the same. I need to shrink the shown text beside the tree icons because the whole area consumes so much place. The shown names depend on the choosen templates (which should be meaningful for me).
![large_tree_area](https://cloud.githubusercontent.com/assets/25848039/24553712/5725e64a-162b-11e7-8579-a462339e31bc.png)
In version 0.8 there was a scroll slider at the bottom of the tree.

There is another case l want to reduce the shown areas. 
It's similar to the wish of David. I want to show only a monitor of the most interesting graphs on one screen. I've selected thumbnails for 12 graphs in 3 Columns. In this scenario both the tree and the filter section are not necessary to be shown.
Maybe a simple button to hide the tree and to hide the filter area would be sufficient. It would be nice if this behaviour can be selected in the profile. So you can open a browser, log in and have the interesting graphs shown on a informational screen at the wall of the corridor.
Thank you for listening.
Guenter

**Comment by cigamit** [comment]
For the graph tree I was hoping on making it more responsive.

**Comment by cigamit** [comment]
The tree menu is now responsive.  You can hide the tree by simply clicking on the graphs icon a second time.
