### ISSUE TITLE
RRD Proxy Server not supported by CLI script "structure_rra_paths.php"

### ISSUE THREAD

**Issue by browniebraun** [Cacti/cacti#5034]
# Describe the bug

Once a RRD proxy has been set up and you would like to migrate existing RRDs the execution of 
"structure_rra_paths.php" will fail.

## To Reproduce

New system, default installation. Poller running, auto discovery enabled. RRD proxy configured and running in full debug mode.
Go to CLI and execute structure_rra_paths.php.

browniebraun@browniebraun-Lenovo-ideapad-530S-14IKB:/var/www/html/cacti/cli$ php structure_rra_paths.php --proceed
NOTE: Found:5 Data Sources.  Beginning Process

Warning: chgrp(): Operation not permitted in /var/www/html/cacti/cli/structure_rra_paths.php on line 379
FATAL: Could not Set Permissions for Directory '/var/www/html/cacti/rra/1/1/0'

Proxy shows no connection being established during script run.

Ubuntu 22.04.1 LTS

**Comment by TheWitness** [comment]
Maybe for these structured path change, we skip the permission change on the file movement.  @browniebraun, is this even required for the proxy?  For me, I have to add both the hash + gt or dq as there are just so many graphs/devices.  Some data queries with 70k graphs.  So, even that's a lot for a single directory.

**Comment by browniebraun** [comment]
From my point of view it is not required, because the proxy owns it and a direct access from somewhere else like web is not supported.

**Comment by TheWitness** [comment]
Okay, let me take it then.

**Comment by TheWitness** [comment]
Should be resolved now.

**Comment by browniebraun** [comment]
Mmmh, I only meant that the change of ownership is not necessary and not that the support should be skipped.  For the proxy it doesn't matter if Cacti wants to have one, two or more sub-directories or just a single one. I'm using it with structured paths in production ( /device_id/local_data_id). Let take a closer look at it this week, once I have time.

BTW: Why does the script say that BOOST has to be enabled to support structured paths?

**Comment by TheWitness** [comment]
You know, I can not remember, but I think it's the data source lock.
