### ISSUE TITLE
1.3.0 - QA - Selecting Table Options and Posting does full page refresh

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#5038]
# Describe the bug

Using the 1.3.0 branch, the "Go" Table actions dropdown callbacks are using a full page refresh instead of rendering through a callback.

## To Reproduce

1. Select a few devices to delete

2. From the Actions Dropdown select "Delete"

3. Press "Go"

4. Note that the browser does a full page refresh to bring up the confirmation screen.

## Expected behavior

All these callbacks are supposed to be through ajax.

**Comment by netniV** [comment]
This was an intermediate bug fixed in commit 49ab4aeb3
