### ISSUE TITLE
Custom themes may cause errors if they do not contain all required CSS/JS files

### ISSUE THREAD

**Issue by jdcoats** [Cacti/cacti#5041]
What is it that changed and what do i need to do?
```
2022/12/05 12:49:46 - CMDPHP PHP ERROR WARNING Backtrace: (/host.php[174]:top_header(), /lib/functions.php[4595]:include_once(), /include/top_header.php[34]:html_common_header(), /lib/html.php[2567]:get_md5_include_css(), /lib/functions.php[6555]:get_md5_hash(), /lib/functions.php[6529]:md5_file(), CactiErrorHandler())
--
2022/12/05 12:49:46 - ERROR PHP WARNING: md5_file(/var/www/localhost/htdocs/cacti/lib/../include/themes/TMH/Diff.css): failed to open stream: No such file or directory in file: /var/www/localhost/htdocs/cacti/lib/functions.php on line: 6529
```

**Comment by TheWitness** [comment]
@jdcoats, just copy the Diff.css from the closest theme. We are not 100% ready for release, tree editing will be updated later today, and packages will be republishedbtonight maybe too, but test away.

**Comment by jdcoats** [comment]
10/4

**Comment by netniV** [comment]
@TheWitness I was going to close this as a third party bug, but in reality, I think we will need to have a default `Diff.css` to fall back upon since others may have custom themes that do not have this yet.  Maybe log a warning when falling back?

**Comment by TheWitness** [comment]
I would agree for any of these mandatory files.

**Comment by TheWitness** [comment]
Suggesting that maybe we use the modern theme mandatory files if they're missing.

**Comment by TheWitness** [comment]
We would like to likely want to debounce the error message so that it does not appear too often.

**Comment by TheWitness** [comment]
Okay, I've added a debounce message and an Admin Email for these file missing issues.

**Comment by TheWitness** [comment]
Okay, this is resolved now.
