### ISSUE TITLE
1.3.0 - QA When viewing a remote poller page sql check redirects to another page

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#5043]
In 1.3 when testing mysql connectivity of a remote poller you are re-directed to another page with the result

![remote_poller_db](https://user-images.githubusercontent.com/13388748/205723221-370fe069-3886-4061-ba7b-ce26e4f1c71a.gif)

The usual behaviour is a simple text under the button that pops up saying successful or fail

**Comment by netniV** [comment]
this should be corrected in f5042fa62

**Comment by bmfmancini** [comment]
confirmed corrected !
