### ISSUE TITLE
Log rotation does not work

### ISSUE THREAD

**Issue by vengenus** [Cacti/cacti#505]
Cacti version 1.1.1
If a different path to the log file is defined in the settings and log rotation is enabled, an error appears.
![logrotate](https://cloud.githubusercontent.com/assets/26815929/24547987/d1620554-1623-11e7-9176-99b4ab24c233.jpg)

patch: 
[poller_maintenance.txt](https://github.com/Cacti/cacti/files/885384/poller_maintenance.txt)

**Comment by cigamit** [comment]
Can you please do this as a pull request?

**Comment by cigamit** [comment]
Resolved
