### ISSUE TITLE
1.3.0 - QA  in RRD Cleaner when clicking rescan GUI breaks

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#5051]
In the rrd cleaner click rescan and the GUI will break 

![rrd_cleaner](https://user-images.githubusercontent.com/13388748/205762789-518081bb-cbbc-456d-aba1-eb2b99c24537.gif)

**Comment by netniV** [comment]
This was fixed in 1be873cc4 but it has the wrong issue number.
