### ISSUE TITLE
1.2.23 - PHP8.1 when adding a device rule in automation deprecated messages occour

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#5057]
add a entry in automation >> Device rules 
you will see the below messages

```
2022-12-05  19:33:42 - CMDPHP PHP ERROR Backtrace:   (/automation_templates.php[38]:form_save(),  /automation_templates.php[202]:CactiErrorHandler())
2022-12-05 19:33:42 - ERROR PHP DEPRECATED: Constant  FILTER_SANITIZE_STRING is deprecated in file:  /var/www/html/cacti/automation_templates.php  on line: 202
```

**Comment by netniV** [comment]
The definitions of these filters is depreciated in 8.1 I believe.  This means that we need to consider an alternative, possibly our own implementation that does the same thing.

FILTER_SANITIZE_STRING

> Strip tags and HTML-encode double and single quotes, optionally strip or encode special characters. Encoding quotes can be disabled by setting FILTER_FLAG_NO_ENCODE_QUOTES. (Deprecated as of PHP 8.1.0, use htmlspecialchars() instead.)

FILTER_SANITIZE_STRIPPED

> Alias of "string" filter. (Deprecated as of PHP 8.1.0, use htmlspecialchars() instead.)

Alternatively, we just don't filter the string input.  But I'm sure @TheWitness would prefer the first option.

**Comment by TheWitness** [comment]
This should be resolved now.

**Comment by netniV** [comment]
I know there's a 1.3.x QA issue around FILTER_xxx so there's probably more.

**Comment by TheWitness** [comment]
This is the one, I relabeled it as it impacts 1.2.23.  So, I think we are good now.
