### ISSUE TITLE
Undefined index: cactiStatsDeviceFailedPolls in file: lib/snmpagent.php  on line: 296

### ISSUE THREAD

**Issue by gpant** [Cacti/cacti#506]
After upggrading from 0.8.8g I have the following issue on every poll

ERROR PHP NOTICE: Undefined index: cactiStatsDeviceFailedPolls in file: lib/snmpagent.php
 on line: 296
CMDPHP PHP ERROR NOTICE Backtrace: (/poller.php: 710 snmpagent_poller_bottom)(lib/snmpagent.php: 296 CactiErrorHandler)(/lib/functions.php: 4310 cacti_debug_backtrace)

**Comment by browniebraun** [comment]
Go to the console menu and click under utilities on "rebuild snmpagent cache".

Regards
-Andi

**Comment by gpant** [comment]
Already tried that without any change in the issue.
I re-did a fresh install of cacti and still get that issue, any idea how to debug it further? Its not affecting any rra's as far as I can tell just want to clear the issue from the logs.

**Comment by cigamit** [comment]
Please grab the latest lib/snmpagent.php from the development branch.  Also, please after updating, rebuild the snmpagent cache and let us know that there are records there.  I will close this, but please still provide us an update.

**Comment by gpant** [comment]
Issue is fixed using the snmpagent.php in git.
Thanks
