### ISSUE TITLE
1.3.0 - QA device debug does run

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#5063]
when enabling device debug you should get logs on each poller run for that device 
However, this does not trigger

![image](https://user-images.githubusercontent.com/13388748/206036272-09e1ea7b-da23-473c-8102-ff0b3b34201c.png)

![image](https://user-images.githubusercontent.com/13388748/206036621-2a0ecc26-1a24-40ce-99e8-b64a0267cfcd.png)

**Comment by netniV** [comment]
I found that this works as intended.  I did some clean up on the code but that aside, everything was good.  Make sure the device in question actually has something to be polled.
