### ISSUE TITLE
1.3.0 - QA clicking graph propertise  appears to load graph view instead

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#5064]
![image](https://user-images.githubusercontent.com/13388748/206037230-32a33e0c-0d7e-4b3a-91ef-27ba5ec0e2e6.png)

**Comment by netniV** [comment]
Part way through fixing this but not happy yet with the outcome.  Will have to revisit tomorrow

**Comment by bmfmancini** [comment]
@netniV  looks like its fixed do you still need to commit anything ?

**Comment by netniV** [comment]
No, once I've assigned it to you, I've done my bit.

**Comment by bmfmancini** [comment]
Confirmed fixed
