### ISSUE TITLE
1.2.23 - Cacti does not escape the watermark leading to broken graphs

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#5066]
# Describe the bug

Out a single quoted in your watermark and watch your graphs break.

## Expected behavior

A safer less disruptful Cacti.

**Comment by bmfmancini** [comment]
Also see this on 1.3.x

![image](https://user-images.githubusercontent.com/13388748/206222386-2d5d47ca-1053-4de0-9cb5-4ddc782500dd.png)

![image](https://user-images.githubusercontent.com/13388748/206222541-5843bb62-8546-40f1-b269-7a9c06e0b564.png)

**Comment by TheWitness** [comment]
Okay, this is resolved now.
