### ISSUE TITLE
Spikeill feature is not working as expected

### ISSUE THREAD

**Issue by Nitin797** [Cacti/cacti#5067]
Hi Team,

We have enabled around 10 graph templates in Spike kill feature but could still see there are spikes in the graph which is not getting removed automatically as it should be. The removal schedule is set to 6hours which doesn't work either. The details are in below. Could you please assist on the same to resolve this issue.

Cacti 1.2.18
Spine 1.2.19
MariaDB 10.3.
OS: Linux
Browser: Chrome

`Regards,
Nitin Kumar

**Comment by TheWitness** [comment]
There have been some spike kill enhancements since 1.2.18.  But you need to show before, after and dryeun output here.  In other words, we need more information.  Screen shots and that dryeun data is important.

**Comment by Nitin797** [comment]
![image](https://user-images.githubusercontent.com/110081629/206633590-e42603ad-4d9e-4933-bf0c-82e971d53e70.png)

**Comment by Nitin797** [comment]
![image](https://user-images.githubusercontent.com/110081629/206633725-e115d9b7-901a-4e69-8768-0dfd62436f37.png)

This snip is today's data

**Comment by Nitin797** [comment]
> ![image](https://user-images.githubusercontent.com/110081629/206633725-e115d9b7-901a-4e69-8768-0dfd62436f37.png)
> 
> This snip is today's data

This graph shows displayed is for traffic-discards

**Comment by TheWitness** [comment]
How much is 2.5L?

**Comment by Nitin797** [comment]
It is 2,50,000 graphs of traffic discards.

**Comment by TheWitness** [comment]
So, 250k.  Likely does not scale well.  Needs to be parallel. That would be a feature request on the 1.3 roadmap.

**Comment by Nitin797** [comment]
Could you please let us know if there should be any spike kill settings to be changed as per the attached snip?

**Comment by TheWitness** [comment]
Well, that's a trial and error thing on your part.  We don't make the recommendations, but if you know enough about statistics, you will find your way through the right settings.  I suggest you deploy a "test box" and do your training there though.  Once you know what works and how it works, then move onto making the changes on your production box.

**Comment by TheWitness** [comment]
Let's have you continue this discussion on the Forums.
