### ISSUE TITLE
1.3.0 - QA Unable to provide secondary confirmation when creating graphs

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#5075]
# Describe the bug

When you go to create Data Query graphs where there exists a secondary confirmation, the `Create` button does not work and therefore you can not create Data Query type graphs.

## To Reproduce

1. Create a Net-SNMP based Device
2. Select the SNMP Mounted partition objects to create graphs for
3. Press the Create Button
4. Note that nothing happens.

## Expected behavior

Cacti 1.3.x should be have similarly to Cacti 1.2.x.

**Comment by netniV** [comment]
I believe that this has already been addressed in issue #5080
