### ISSUE TITLE
1.3.0 - QA Attempting to Change Theme Results in JavaScript Errors

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#5076]
Describe the bug

When you attempt to edit your profile and change the Theme, instead of changing the theme, JavaScript errors occur on the page.

![image](https://user-images.githubusercontent.com/1439914/206921068-b34f43ed-3089-4582-9a2f-470c473001ab.png)

## To Reproduce

1. Edit Profile

2. Bring up browser debug window

3. Attempt to Change Theme

## Expected behavior

Theme should change as normal.

**Comment by netniV** [comment]
toggleFields is part of layout.js, you have refresh / cache issues.

**Comment by TheWitness** [comment]
Yea, just did that.  Still waking up ;)
