### ISSUE TITLE
Make user log ask for confirmation on purge

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#5083]
When trying to purge the user log the log is not purging 

![user_log_purge](https://user-images.githubusercontent.com/13388748/207140500-4d41fd83-632a-413c-9a84-56857ec8ebc7.gif)

**Comment by bmfmancini** [comment]
Also  the user_log table has entries that are not shown 

```
MariaDB [cacti]> select * from user_log
    -> ;
+----------+---------+---------------------+--------+---------------+
| username | user_id | time                | result | ip            |
+----------+---------+---------------------+--------+---------------+
| admin    |       0 | 2022-12-03 23:22:38 |      3 | 192.168.3.243 |
| admin    |       1 | 2022-12-03 23:22:29 |      1 | 192.168.3.243 |
| admin    |       1 | 2022-12-03 23:55:40 |      1 | 192.168.3.243 |
| admin    |       1 | 2022-12-04 00:04:40 |      1 | 192.168.3.243 |
| admin    |       1 | 2022-12-04 00:05:55 |      1 | 192.168.3.243 |
| admin    |       1 | 2022-12-04 14:32:46 |      1 | 192.168.3.243 |
| admin    |       1 | 2022-12-04 19:34:24 |      1 | 192.168.3.221 |
| admin    |       1 | 2022-12-05 14:02:41 |      1 | 192.168.3.151 |
| admin    |       1 | 2022-12-05 18:35:35 |      1 | 192.168.3.151 |
| admin    |       1 | 2022-12-05 18:36:12 |      1 | 192.168.3.151 |
| admin    |       1 | 2022-12-05 18:36:38 |      1 | 192.168.3.151 |
```

**Comment by bmfmancini** [comment]
One more strange thing on this one 

I truncated user_log 

MariaDB [cacti]> select * from user_log;
Empty set (0.003 sec)

yet

![image](https://user-images.githubusercontent.com/13388748/207141327-f30995ee-a5c3-47f5-97c5-5e6c3034c207.png)

is still showing

**Comment by netniV** [comment]
This should behave the same as the system log:
![image](https://user-images.githubusercontent.com/9052188/207154998-6dfa8ddb-3c74-488b-ae68-3bcf1e40fb8d.png)

**Comment by netniV** [comment]
So, my instance cleared the data, and left two entries behind.  However, that didn't ask to confirm before doing so.  We should add a confirmation.

**Comment by netniV** [comment]
Just for future reference, the entries left behind are always the latest valid Token and Web login results.  This is by design.  Also, made the User Log more accessible to new admins who may not even realise it exists!
