### ISSUE TITLE
After Update 1.2.20 to 1.2.22 CMDPHP ERROR: A DB Cell Failed 

### ISSUE THREAD

**Issue by C00kiekiller** [Cacti/cacti#5084]
# Describe the bug

Error in SQL Syntax  CMDPHP after Upgrade from 1.2.20 to 1.2.22

`13-12-2022 08:50:49 - CMDPHP ERROR: A DB Cell Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '? WHERE graph_tree.enabled = "on" ORDER BY graph_tree.id LIMIT 1' at line 1
`
## To Reproduce

1. Click on  'Tab Graphs'

4. See error in Log

## Expected behavior

No Error Message

## Screenshots
![image](https://user-images.githubusercontent.com/16733284/207257983-2fe4cc9c-80bd-4a69-ac40-4207d762cfe1.png)

## Desktop (please complete the following information)

- OS: [Windows 10]

- Browser [Chrome, Firefox, Edge]

- Version [latest versions]

- Server OS: Ubuntu 20.04.5 LTS \n \l
- Server DB: mariadb  Ver 15.1 Distrib 10.6.11-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
- PHP: PHP 7.4.3 (cli) (built: Nov  2 2022 09:53:44) ( NTS )
- Webserver: Server version: Apache/2.4.41 (Ubuntu)

**Comment by netniV** [comment]
There should be a corresponding backtrace that goes with this.  Can you provide it, please?

**Comment by C00kiekiller** [comment]
`14-12-2022 15:37:37 - CMDPHP SQL Backtrace: (/graph_view.php[242]:top_graph_header(), /lib/functions.php[4559]:include_once(), /include/top_graph_header.php[55]:grow_dhtml_trees(), /lib/html_tree.php[125]:db_fetch_cell(), /lib/database.php[462]:db_fetch_cell_prepared(), /lib/database.php[484]:db_execute_prepared())`

**Comment by TheWitness** [comment]
Please update `lib/html_tree.php` from the 1.2.x branch and report back.

**Comment by C00kiekiller** [comment]
The problem is solved after updating the file`lib/html_tree.php` . The error no longer occurs. Thanks

**Comment by C00kiekiller** [comment]
Reopen:

- 'Tree View' is broken (blank page) - 'List View' and 'Preview' Still working'
- Screenshot is attached
- No error in cacti  log or apache2 log

Console Output from my Browser after click on a element/branch/device in 'Tree Mode':

```
URL from a element in the Tree:
https://cacti.foo.bar/cacti/graph_view.php?action=tree&node=tbranch-19&host_id=9&site_id=-1&host_template_id=-1&hgd=

graph_view.php 

Uncaught ReferenceError: loadUrl is not defined
    at HTMLDivElement.<anonymous> (<anonymous>:143:7)
    at HTMLDivElement.dispatch (jquery.js?23c7c5d2d1317508e807a6c7f777d6ed:5429:27)
    at elemData.handle (jquery.js?23c7c5d2d1317508e807a6c7f777d6ed:5233:28)
    at Object.trigger (jquery.js?23c7c5d2d1317508e807a6c7f777d6ed:8715:12)
    at jQuery.fn.init.triggerHandler (jquery.js?23c7c5d2d1317508e807a6c7f777d6ed:8799:24)
    at $.jstree.plugins.search.trigger (jstree.js?5d3a3b5f68b0163175e5630a5e8a3a66:960:17)
    at $.jstree.plugins.search.select_node (jstree.js?5d3a3b5f68b0163175e5630a5e8a3a66:3288:10)
    at $.jstree.plugins.search.activate_node (jstree.js?5d3a3b5f68b0163175e5630a5e8a3a66:3155:11)
    at $.jstree.plugins.search.<anonymous> (jstree.js?5d3a3b5f68b0163175e5630a5e8a3a66:777:12)
    at HTMLDivElement.dispatch (jquery.js?23c7c5d2d1317508e807a6c7f777d6ed:5429:27)

```
![image](https://user-images.githubusercontent.com/16733284/208067373-66b60268-da2d-4bab-8bc1-6d2e6805b4f8.png)

**Comment by C00kiekiller** [comment]
**Update**: The fix ```lib/html_tree.php``` is working but the page needs aprox 4 minutes and 50 seconds to load the graph frame.

**Comment by TheWitness** [comment]
You took the change from `develop` and not `1.2.x` branches.

**Comment by TheWitness** [comment]
@C00kiekiller, I'm going to go ahead and close.  Once you get this pulled down from the `1.2.x` branch instead of the `develop` branch, you will be fine.
