### ISSUE TITLE
Cacti core frequently redirect to graph_view.php for page that call html_graph_area() function

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#5085]
# Describe the bug
After 13734026 (#4948)
Cacti core frequently redirect to graph_view.php for pages that call html_graph_area.

## To Reproduce
1. Install and enable any plugin that have some page calling function `html_graph_area`. For example hmib
2. Access a page that use `html_graph_area` function. For example: `plugins/hmib/hmib.php?action=graphs`
3. Click `Shift Time Backward/Forward` before graph loading success.
4.  `layout.js: initializeGraphs()` will be call again, and `$.ajaxQ.abortAll()` is called by `initializeGraphs()`
5. Previous `initializeGraphs()-->XHR request will be aborted, and execute into `fail()` branch
6. Page will be forward to `cacti/graph_view.php`

## Expected behavior
Keep current page, non-forward

**Comment by TheWitness** [comment]
@ddb4github, I'm seeing this as well.  It may have something to do with a failing graph render.  Have you had any luck tracing it?  What the failing response code is?  Maybe preserve the network tab, and look for the failed response code.

**Comment by TheWitness** [comment]
This is resolved now.  Moving the fix to the develop branch shortly.

**Comment by TheWitness** [comment]
Confirmed that this is working now as expected.
