### ISSUE TITLE
When numeric regex validation fails, not backtrace message is logged in the Cacti log

### ISSUE THREAD

**Issue by chrcoluk** [Cacti/cacti#5089]
# Describe the bug

Popup box which says this when going in and out of device settings, also happens on some other screens.
```

Sorry, we could not process your last action.

Save Failed due to field input errors (Check red fields).
```

Log says the following.

`4/Dec/2022 20:53:02 - CMDPHP Form Validation Failed: Variable 'id' with Value '66' Failed REGEX '0' `

## To Reproduce

Do as above, whilst using PHP 8.0 or newer.

## Expected behavior

No errors.

## Desktop (please complete the following information)

Windows, Firefox (latest stable)

## Additional context

Switching back to PHP 7.4, its error free, note PHP 7.4 is EOL.

**Comment by chrcoluk** [comment]
To add, there is no red fields.

**Comment by netniV** [comment]
This is not a php 8 issue.  The issue is that the regex validation failed to pass on the input.

**Comment by chrcoluk** [comment]
Nope, I tried to set devel logging, and enable anything that would increase verbosity, but that was it.

**Comment by TheWitness** [comment]
Do you have any plugins installed?  If so, please name them.

**Comment by TheWitness** [comment]
Okay, I this is interesting.  Basically you have an invalid REGEX in one of your Data Input Methods.  If you run the following Query:

```sql
SELECT dtd.data_input_id, dl.host_id, dif.id, dif.input_output, dif.data_name, 
dif.regexp_match, dif.allow_nulls, dif.type_code
FROM data_template_data AS dtd
LEFT JOIN data_input_fields AS dif
ON dif.data_input_id = dtd.data_input_id
LEFT JOIN data_local AS dl
ON dtd.local_data_id = dl.id
WHERE dif.input_output='in' and regexp_match != '';
```

You will find a Data Input Method that specifies a Regex, and the value of the Regex is 0, which is not a valid regular expression.

Here is a Screen Shot of that inside of Cacti.

![image](https://user-images.githubusercontent.com/1439914/207749742-b792a74f-3a50-481f-aa07-3880f7a01e84.png)

If you run that Query, it'll give you a Data Input ID, then Edit that ID and clear the Regex Match.  I'm going to see about handing this error during save though, but as a separate issue.

**Comment by TheWitness** [comment]
Okay, after more testing '0' is a valid Regex value, but it also means that there is something wrong with you Data Input Method such that no data is being provided.  Let me know what comes back from the query.  This is likely happening at Graph Creation Time.

**Comment by TheWitness** [comment]
@chrcoluk, any Feedback?

**Comment by TheWitness** [comment]
You will notice that the regex is 0, which means the exact value allowed is only 0, which is bad.  So, the Data Input Method needs to be altered and the Regex cleared from the input field.  So, this is really not a bug.  It's a developer issue who is writing the Data Input Method.

**Comment by chrcoluk** [comment]
Hi I wasnt here for two days, I can run this query and give you the result, if you are still interested.

I wasnt actually trying to create a graph though, I was just going into the devices page and back out of it, without changing/saving anything.

Also ideally the logs should point this to me, as the warning/error was very vague?

I will get back to you on the query.

**Comment by chrcoluk** [comment]
I get an empty result, not even a 0, just nothing.

**Comment by chrcoluk** [comment]
If I browse the data input methods, the majority will make the box popup and log an entry in the log, again no trace, also never anything highted red.  PHP 7.6 no popups, no log entries.

**Comment by TheWitness** [comment]
What plugins do you have installed?  If you do, mention their versions.

**Comment by TheWitness** [comment]
Yes, there is a way to turn it off, but before we do, let's find out where it's happening.

**Comment by chrcoluk** [comment]
Ok list of plugins as presented in the GUI

Monitor Active 2.5
Fix64bit Installed 0.4
Ipsubnet Installed .4f
Thold Active 1.5.2

**Comment by TheWitness** [comment]
Okay, it's one of them.  Can't you tgz and upload Fix64 and Ipsubnet?

**Comment by TheWitness** [comment]
To stop the message go to *Settings > General* and disable *Log Input Validation Issues*

**Comment by TheWitness** [comment]
It's really a developer mode to catch bad behavior, which it did perfectly, well maybe a little less than perfectly.

**Comment by TheWitness** [comment]
I've made an update to lib/functions.php that will be a part of Cacti 1.2.23 that will give you a better clue as to where the bug is when in Log Validation Issues mode.

**Comment by chrcoluk** [comment]
Ok I will do the upload, and remove those 2, also when I toggled the option, it stopped the log but didnt remove the popup, could you please also make the option remove the popup?

**Comment by chrcoluk** [comment]
[fix64bit.tgz](https://github.com/Cacti/cacti/files/10254714/fix64bit.tgz)
[ipsubnet.tgz](https://github.com/Cacti/cacti/files/10254715/ipsubnet.tgz)
