### ISSUE TITLE
Invalid cacti modification template title

### ISSUE THREAD

**Issue by dreamhighhd** [Cacti/cacti#5091]
![image](https://user-images.githubusercontent.com/40293011/207764395-ce41eca8-9c11-4dfd-996e-6fbe1ba92a47.png)

Modify the template title to "| host_description | - | query_ifName | - | query_ifAlias |"
![image](https://user-images.githubusercontent.com/40293011/207764713-90832a4d-13e7-44d3-90d1-8abd279c4220.png)
The host template is "Generic SNMP Device"
![image](https://user-images.githubusercontent.com/40293011/207765122-92462360-6763-49d8-b5c6-39b8f9b48b0e.png)
![image](https://user-images.githubusercontent.com/40293011/207765311-8504f1c0-c5e6-4039-88f3-6647a2333682.png)

The production title is not in the format I want
![image](https://user-images.githubusercontent.com/40293011/207765606-2729720a-c311-4af5-ad13-60d23326ae74.png)

**Comment by dreamhighhd** [comment]
![image](https://user-images.githubusercontent.com/40293011/207766180-d5da6780-7a3e-491c-9ff7-ec05be123856.png)



You guys can help me to see why I adjusted the title format of the template. When I created the graphic, the title format was still not what I wanted

**Comment by netniV** [comment]
Did you push the template back to the devices?

**Comment by TheWitness** [comment]
Try Reapply Suggested name.

**Comment by TheWitness** [comment]
This is a retraining issue.  When you edit the data query, there are suggested name patterns, cacti goes in order finding the best name.  If you reorder the suggested ames, and the Reapply Suggested Names, you will have your solution.

On another subject, can you help on the Chinese Cacti translation?

**Comment by TheWitness** [comment]
But a bunch left to do ;)

**Comment by dreamhighhd** [comment]
I saw the titles related to sorting on the Internet, but I think they are all old versions of cacti. It seems that there is no relevant content in my version.

**Comment by dreamhighhd** [comment]
> But a bunch left to do ;)



> I was thinking before that a good chunk of Chinese was translated already looking at that screen shot.

Is it translated into English？

**Comment by dreamhighhd** [comment]
<img width="1673" alt="image" src="https://user-images.githubusercontent.com/40293011/207999987-43f8b586-540d-4ac2-a80e-7898a2255742.png">

When I use the "Reuse the recommended name", the alias is changed. When the "description" is not configured for some switch ports, there is no "query_ifAlias".
<img width="1672" alt="image" src="https://user-images.githubusercontent.com/40293011/208000018-421f7fb9-9522-4524-9e60-19b433c1ea72.png">

**Comment by dreamhighhd** [comment]
When "query_ifAlias" does not exist or other variable names do not exist, it is invalid when I use "Reuse Suggested Names" to adjust the names

**Comment by dreamhighhd** [comment]
When "query_ifAlias" does not exist or other variable names do not exist, it is invalid when I use "Reuse Suggested Names" to adjust the names

**Comment by TheWitness** [comment]
> > But a bunch left to do ;)
> 
> > I was thinking before that a good chunk of Chinese was translated already looking at that screen shot.
> 
> Is it translated into English？

English is the default.  Translate the stuff that is missing to Chinese.

**Comment by TheWitness** [comment]
@dreamhighhd, goto https://docs.cacti.net and read up on how to Create a Data Query.  From that part of the manual, you will come to discover how Graph Naming works in Cacti.

As this is more of a support issue, I'm going to close.
