### ISSUE TITLE
installer.php - php-snmp module

### ISSUE THREAD

**Issue by xmacan** [Cacti/cacti#5092]
Update or install cacti on system without  php-snmp module. I got red message Installed No - Both. Previously used php-snmp or netsnmp. Today it is possible to have both installed (falls back to NetSNMP).
The message "No - Both" is confusing.

![Screenshot 2022-12-15 at 20-41-24 Cacti Server v1 2 23 - Maintenance](https://user-images.githubusercontent.com/26485719/207952936-89810f4c-4711-4809-b008-7c9e50e30ea3.png)

1.2.x branch

**Comment by netniV** [comment]
The error `No - Both` refer to no CLI and no Web module enabled for that particular item.  Also, with the section your issue is showing, that is also optional so it won't prevent you from carrying forward.
