### ISSUE TITLE
1.3.0 - QA - Unable to upgrade from 1.2.23 to 1.3.0 due to SQL Errors

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#5100]
# Describe the bug

When attempting to upgrade from 1.2.23 to 1.3.0 (develop) I'm getting SQL errors and get popped back to the install screen after I proceed to execute the upgrade.  Backtrace error below.

![image](https://user-images.githubusercontent.com/1439914/208256040-6981dfb9-09ad-4bf0-ae17-49de4941af11.png)

## To Reproduce

1. Start at 1.2.23

2. Attempt to upgrade to 1.3.0

3. Review the cacti.log for the above error.

## Expected behavior

Upgrade should work error free.

**Comment by TheWitness** [comment]
It seems the goal of this is to:

1. Inform the user they are on develop
2. Which develop version they are running
3. To re-run the upgrade if they happen to git clone a newer version, in which case the .git directory will exist and the timestamp can be found from there, or by running the git command from the server.

**Comment by netniV** [comment]
The version issues should now have been resolved.  Please advise if this is still an issue
