### ISSUE TITLE
Warnings executing function dsstats_get_and_store_ds_avgpeak_values() during boost processing

### ISSUE THREAD

**Issue by sosrobert** [Cacti/cacti#5111]
I wish you a nice day! We hit a bug or something. Within Cacti, the maintenance time of the statistics of the data sources is set to 11:50pm, and at this time the maintenance issues an error. Until now, it was set to midnight, so we changed it, but it didn't solve the problem. 
Thanks for your supporting.

`2022-12-19 23:50:10 - ERROR PHP WARNING: A non-numeric value encountered in file: /var/www/html/cacti/lib/dsstats.php  on line: 186`
`2022-12-19 23:50:10 - CMDPHP PHP ERROR WARNING Backtrace:  (/poller_dsstats.php[177]:dsstats_get_and_store_ds_avgpeak_values(), /lib/dsstats.php[186]:CactiErrorHandler())`
`2022-12-19 23:50:10 - ERROR PHP WARNING: A non-numeric value encountered in file: /var/www/html/cacti/lib/dsstats.php  on line: 187`
`2022-12-19 23:50:10 - CMDPHP PHP ERROR WARNING Backtrace:  (/poller_dsstats.php[177]:dsstats_get_and_store_ds_avgpeak_values(), /lib/dsstats.php[187]:CactiErrorHandler())`
`2022-12-19 23:50:10 - ERROR PHP WARNING: A non-numeric value encountered in file: /var/www/html/cacti/lib/dsstats.php  on line: 188`
`2022-12-19 23:50:10 - CMDPHP PHP ERROR WARNING Backtrace:  (/poller_dsstats.php[177]:dsstats_get_and_store_ds_avgpeak_values(), /lib/dsstats.php[188]:CactiErrorHandler())`

## Desktop

- OS: Ubuntu 22.04.1 LTS

- Browser: Mozilla Firefox

- Version: Cacti 1.2.22

**Comment by TheWitness** [comment]
Okay, I can see how the warnings were generated.  Was this on a new install?

**Comment by TheWitness** [comment]
Okay, this is all fixed now.  Thanks for reporting.
