### ISSUE TITLE
1.3.0 - QA php error when changing theme in user profile

### ISSUE THREAD

**Issue by xmacan** [Cacti/cacti#5114]
Fatal error: Uncaught Error: Undefined constant "sess_simple_perms" in /usr/local/share/cacti_develop/lib/auth.php:1028 Stack trace: #0 /usr/local/share/cacti_develop/include/global_arrays.php(1658): is_realm_allowed(21) #1 /usr/local/share/cacti_develop/include/global.php(576): include_once('/usr/local/shar...') #2 /usr/local/share/cacti_develop/include/auth.php(27): require_once('/usr/local/shar...') #3 /usr/local/share/cacti_develop/user_admin.php(25): include('/usr/local/shar...') #4 {main} thrown in /usr/local/share/cacti_develop/lib/auth.php on line 1028

Actual develop branch

**Comment by netniV** [comment]
This was fixed by @browniebraun two day sago in ca5fac57b. 

Thanks @browniebraun
