### ISSUE TITLE
QA - 1.3.0 - Empty entry is shown in Authentication Method drop-down on settings

### ISSUE THREAD

**Issue by thurban** [Cacti/cacti#5116]
# Describe the bug

An Empty entry is shown in Authentication Method drop-down on settings on Cacti 1.3

## To Reproduce

1. Go to Settings

2. Click on 'Authentication'

3. Select the drop down for "Authentication Method"

## Expected behavior

No Empty entry appearing

## Screenshots

![Cacti_Settings_AuthMethod_emptyentry](https://user-images.githubusercontent.com/17292964/209410281-1096e2c4-79ec-4108-9e5b-832f2468be99.png)

## Desktop (please complete the following information)

n/a

## Smartphone (please complete the following information)

n/a

**Comment by thurban** [comment]
The issue is caused by setting the $auth_methods[AUTH_METHOD_LDAP] to null:

 ![Issue_EmptyEntry](https://user-images.githubusercontent.com/17292964/209410341-a8c9e06c-cd1f-40ab-886a-8c56a71a8387.png)

I suggest to remove this entry

**Comment by netniV** [comment]
I honestly wondered how long it would go unnoticed. Then it was long enough I forgot about it (->20mins)

**Comment by netniV** [comment]
This is because AUTH_METHOD_LDAP has been shifted to the DOMAINS since they all pretty much use the same parameters. 

Unfortunately, before committing I hadn't spotted that our drop-down function doesn't care if you have a text value or not, that option gets displayed. 

Something to fix
