### ISSUE TITLE
1.2.23 - QA Web-based Install is blocked due to pcntl not being compiled into php-fpm

### ISSUE THREAD

**Issue by thurban** [Cacti/cacti#5117]
# Describe the bug

The web-based install stops when checking the PHP required modules as pcntl is marked as being required for CLI and WEB.
In RockyLinux 8, REMI PHP 8.0 PHP-FPM is not compiled with pcntl support and hence reports it as not being installed.

The CLI based installation completes without any issues.

## To Reproduce

Install a 1.2.22 Cacti version on RockyLinux 8 using the following guide:
https://www.urban-software.com/cacti-howtos/cacti/install-cacti-on-rockylinux-8/

Then upgrade to Cacti 1.2.23 and start the web-based installer. 

Proceed to the PHP/Database required settings/modules

## Expected behavior

The pcntl should show up as installed for CLI and ignore if it is not installed for WEB

Installation ( "Next" button not being disabled ) should proceed 

## Screenshots

![grafik](https://user-images.githubusercontent.com/17292964/210139008-05e73162-222c-4e36-9ca8-94a5151db16a.png)
![grafik](https://user-images.githubusercontent.com/17292964/210139012-fdeffdea-78d0-4531-a3b5-2eaed42e378f.png)

## Additional context

RockyLinux 8, PHP 8.0 , Cacti 1.2.22 -> Cacti 1.2.23 upgrade, PHP-FPM

**Comment by thurban** [comment]
The same issues seems to happen on a Ubuntu with PHP 7.3

**Comment by bmfmancini** [comment]
Yea same thing on debian 10 php 7.3 


```
 root@master1:~# php -m
 [PHP Modules]
 calendar
 Core
 ctype
 date
 dom
 exif
 fileinfo
 filter
 ftp
 gd
 gettext
 gmp
 hash
 iconv
 intl
 json
 ldap
 libxml
 mbstring
 mysqli
 mysqlnd
 openssl
 pcntl
 pcre
 PDO
 pdo_mysql
 Phar
 posix
 readline
 Reflection
 session
 shmop
 SimpleXML
 snmp
 sockets
 sodium
 SPL
 standard
 sysvmsg
 sysvsem
 sysvshm
 tokenizer
 wddx
 xml
 xmlreader
 xmlwriter
 xsl
 Zend OPcache
 zip
 zlib
 
 [Zend Modules]
 Zend OPcache
```

Forced install via cli system utilities >> php shows pcntl is present

**Comment by TheWitness** [comment]
Okay, this is resolved now.  Please test again.  Heading out for appointments now.
