### ISSUE TITLE
1.0.1 login process fails

### ISSUE THREAD

**Issue by chrcoluk** [Cacti/cacti#512]
I upgraded from 0.88h to 1.0.1 and now cannot login

I read the FAQ which I suspect is out of date to reset the password and still cannot login.

Are the passwords still md5 hash?

**Comment by chrcoluk** [comment]
actually seems the password is been accepted but just the login page is reloading.

Nothing in php and http error logs.

**Comment by browniebraun** [comment]
This sounds like an old bug that has already been solved.
Please upgrade to v1.1.2 first. Your version (1.0.1) is pretty old.

Regards
-Andi

**Comment by chrcoluk** [comment]
I updated to the latest in the FreeBSD ports tree so I will have to bug the maintainer.

However I found the cause, it was related to the new mysql session storage, if I disable it then I can login.

IS the bug related to the mysql session storage?

**Comment by cigamit** [comment]
In the 1.0 and 1.0.1 release session storage was enabled by default which would never work on an upgrade since the session table did not exist.  So, it was disabled in subsequent releases.  Session storage in the database works fine but you can not have it enabled when upgrading from pre-1.0.
