### ISSUE TITLE
Undefined index: external_id errors when rebuilding poller cache

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#513]
Just upgraded to 1.1.2. I launched a "Rebuild Poller Cache" under Console->Utilities and got numerous errors in cacti.log:

`2017-04-02 21:41:59 - ERROR PHP NOTICE: Undefined index: external_id in file: /cacti/cacti-1.1.2-prod/lib/variables.php  on line: 206`
`2017-04-02 21:41:59 - CMDPHP PHP ERROR NOTICE Backtrace: (/utilities.php: 39 repopulate_poller_cache)(/lib/utility.php: 43 update_poller_cache)(/lib/utility.php: 339 get_script_query_path)(/lib/data_query.php: 1321 substitute_host_data)(/lib/variables.php: 206 CactiErrorHandler)(/lib/functions.php: 4295 cacti_debug_backtrace)`

**Comment by eschoeller** [comment]
Ack, this is actually worse than just a few thousand errors in the cacti.log:

![screenshot_20170402_220729](https://cloud.githubusercontent.com/assets/12864741/24595136/dccba96c-17f0-11e7-8f79-b6beb794e412.png)

**Comment by tertius1** [comment]
You either missed the database schema update from cacti 1.0.4 to 1.05, or you didn't clean your browser cookies after the update.

found in install/1_0_4_to_1_0_5.php:

        /* add external id column */
        if (!db_column_exists('host', 'external_id')) {
                db_install_execute('ALTER TABLE host ADD COLUMN external_id VARCHAR(40) DEFAULT NULL AFTER notes');
                db_install_execute('ALTER TABLE host ADD INDEX external_id (external_id)');
        }

In case you didn't miss the schema update and your host table does actually contain the new external_id column, clean all cacti cookies, because that column is also cached in $_SESSION. Logout/login should probably suffice.

**Comment by eschoeller** [comment]
OK I was missing the external_id column, it's now added. Now I am getting this error with that same graph:

![screenshot_2017-04-03_08-46-42](https://cloud.githubusercontent.com/assets/12864741/24614999/3aabbb86-184a-11e7-8d18-5d2847326827.png)

**Comment by cigamit** [comment]
Have you been able to determine the problem here?

**Comment by eschoeller** [comment]
Yeah man ... we've been here before. The colon in the COMMENT appears to be blowing everything up now

**Comment by eschoeller** [comment]
Sorry, the colon in the HRULE

**Comment by eschoeller** [comment]
Yep, this works:
HRULE:54#FF3932FF:'Poller Runtime Timeout'
This does not:
HRULE:54#FF3932FF:'Poller Runtime Timeout: 54'

I think that special character in the text field for the HRULE needs to be escaped with a \

This works from the command line:
HRULE:54#FF3932FF:'Poller Runtime Timeout\: 54'

**Comment by cigamit** [comment]
Resolved.
