### ISSUE TITLE
1.2.23 - When the MySQL/MariaDB setting `join_buffer_size` is not set, SQL errors appear when attempting to upgrade Cacti

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#5138]
# Describe the bug

The default `join_buffer_size` setting in MySQL/MariaDB will cause bigint overflows when added to other settings.  The generates an overflow error in MySQL/MariaDB

## To Reproduce

1. Have an install that does not have join_buffer_size set

2. Attempt to install/upgrade

3. Review the Cacti log

## Expected behavior

Cacti should compensate for this instead of throwing and error.

**Comment by netniV** [comment]
You added a commit that tagged this issue yet marked it as unreproducible. Which was it ?

**Comment by TheWitness** [comment]
Yea, my eyes are going, it was #5317 and not this tick.
