### ISSUE TITLE
cacti spine 1.1.2 make problem

### ISSUE THREAD

**Issue by aminli** [Cacti/cacti#514]
OS : freebsd v11
net-snmpd v5.7.3

Problem during make command:
_# make
cc -DHAVE_CONFIG_H -I. -I./config      -I/usr/local/include/mysql -g -O2 -MT sql.o -MD -MP -MF .deps/sql.Tpo -c -o sql.o sql.c
In file included from sql.c:34:
./common.h:134:10: fatal error: 'net-snmp/net-snmp-config.h' file not found
#include <net-snmp/net-snmp-config.h>
         ^
1 error generated.
*** Error code 1

Stop.
make: stopped in /usr/home/amin/cacti-spine-1.1.2_

**Comment by pautiina** [comment]
On freebsd use this string:
`./configure  'CC=gcc49' '--prefix=/usr/local/' '--exec-prefix=/usr/local/'`

**Comment by cigamit** [comment]
Also, what is the output of the configure script?  Who about when you ran bootstrap.  Seems like some paths are buggered up.

**Comment by cigamit** [comment]
Hmm.  Well Pautiina, as you know, I'm not patient.  So, I'll close after 3 days and no response.

**Comment by pautiina** [comment]
The problem is that the standard `clang` compiler uses the FreeBSD source code and librery, and spine requires the libraries of the installed `net-snmp` package. To solve this and similar problems it is necessary to install the GCC compiler. It correctly uses include libraries.

**Comment by cigamit** [comment]
aminli,

Once you have this resolved, if you would please create a pull request with updated documentation for FreeBSD that would be great.  Just append it to the current readme.

**Comment by aminli** [comment]
Thanks for all,
I run this command after installing GCC6 
./configure 'CC=gcc6' '--prefix=/usr/local/' '--exec-prefix=/usr/local/'
it is installed without any error.
