### ISSUE TITLE
1.2.23 - Cacti PHP 8.2 SNMP Errors with php-snmp Installed

### ISSUE THREAD

**Issue by reubenfarrelly** [Cacti/cacti#5140]
Some early stage testing of php-8.2.0 (release version) with cacti 1.2.x (up to date as of now) is showing poller errors:

06/Jan/2023 00:40:28 - CMDPHP PHP ERROR Backtrace: (/cmd.php[377]:ping_and_reindex_check(), /cmd.php[754]:update_system_mibs(), /cmd.php[592]:open_snmp_session(), /cmd.php[555]:cacti_snmp_session(), /lib/snmp.php[87]:CactiErrorHandler())
06/Jan/2023 00:40:28 - ERROR PHP DEPRECATED: Creation of dynamic property phpsnmp\SNMP::$bulk_walk_size is deprecated in file: /var/www/cacti/htdocs/lib/snmp.php on line: 87
06/Jan/2023 00:40:28 - CMDPHP PHP ERROR Backtrace: (/cmd.php[377]:ping_and_reindex_check(), /cmd.php[754]:update_system_mibs(), /cmd.php[592]:open_snmp_session(), /cmd.php[555]:cacti_snmp_session(), /lib/snmp.php[87]:CactiErrorHandler())
06/Jan/2023 00:40:28 - ERROR PHP DEPRECATED: Creation of dynamic property phpsnmp\SNMP::$bulk_walk_size is deprecated in file: /var/www/cacti/htdocs/lib/snmp.php on line: 87
06/Jan/2023 00:40:27 - CMDPHP PHP ERROR Backtrace: (/cmd.php[377]:ping_and_reindex_check(), /cmd.php[754]:update_system_mibs(), /cmd.php[592]:open_snmp_session(), /cmd.php[555]:cacti_snmp_session(), /lib/snmp.php[87]:CactiErrorHandler())
06/Jan/2023 00:40:27 - ERROR PHP DEPRECATED: Creation of dynamic property phpsnmp\SNMP::$bulk_walk_size is deprecated in file: /var/www/cacti/htdocs/lib/snmp.php on line: 87

This is on Gentoo x86_64 and was built with net-snmp-5.9.3 .

**Comment by TheWitness** [comment]
Thanks for tmeunning the tests @reubenfarrelly

**Comment by TheWitness** [comment]
I've not used php-snmp in so long, totally slipped my mind testing this one.

**Comment by TheWitness** [comment]
@reubenfarrelly, I don't know why this is triggering with 1.2.23/1.2.x branch.  If you look at the phpsnmp/classSNMP.php file, you should see the following:

![image](https://user-images.githubusercontent.com/1439914/211067842-d50112b0-9220-4426-9693-1f17ed7d911f.png)

Line 49.  It's a public variable.  So, this message should not have fired.  Make sure you've got the right file okay?

**Comment by TheWitness** [comment]
Okay, I'm confirming the same behavior.  But for the life of my I don't know why.  We have defined the $bulk_walk_size to be a public property.  So, this error should not be being thrown.  Testing on 8.2.1.

**Comment by TheWitness** [comment]
Okay, I have this working now.  Still mind boggling the behavior of this single variable.
