### ISSUE TITLE
dsstats_poller_bottom() error

### ISSUE THREAD

**Issue by sosrobert** [Cacti/cacti#5141]
# Describe the bug

Have a nice day! We had the following problem. It did this by randomly because it had no problem with the Cacti path until now. Thank you very much!

`2023-01-06 11:10:06 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())`
`2023-01-06 11:10:06 - ERROR PHP ERROR: Uncaught Error: Undefined constant "CACTI_PATH_LIBRARY" in /var/www/html/cacti/lib/dsstats.php:1011 Stack trace: #0 /var/www/html/cacti/poller.php(821): dsstats_poller_bottom() #1 {main} thrown in file: /var/www/html/cacti/lib/dsstats.php on line: 1011`

## Desktop

OS: Ubuntu 22.04.1 LTS

Browser: Mozilla Firefox

Version: Cacti 1.2.22

**Comment by TheWitness** [comment]
You some how or another got DEVELOP code running on top of 1.2.x code.  That constant should not be in use in 1.2.22.  So, if you were patching your 1.2.22, I suggest you instead upgrade to 1.2.23.
