### ISSUE TITLE
1.2.23 - Correct issues with permission model including display of authorization UI elements and warnings

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#5142]
When you change permissions models from the previous of:

* Permissive
* Restrictive

To anything else, including:

* Device Based
* Graph Template Based

Cacti should warn the users that with a permission system change, there can be unexpected consequences, and that before making this change, they should understand that access to Graphs will change.

It should be noted, that the Graph Permission will continue to override any Template Restriction.  So, for the documentation we should be clear that if you want the `Graph Template` and `Device` Permission Models to be the final solution, `Graph` permissions should be `Deny` by default.

Lastly, when the Permission Model is `Device` we should not show the `Graph Templates` permission tab in Users and User Groups,  In addition, if the Permission Model is set to `Graph Template`, we should not be showing the `Device` permissions tab.

**Comment by netniV** [comment]
Lastly twice ?

**Comment by TheWitness** [comment]
Thank God for the Edit button :)
