### ISSUE TITLE
1.2.23 - When a Device has zero Graphs or Data Sources, it does not display the correct value

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#5143]
# Describe the bug

When a device has not Graphs or Data Sources, the page should show 0 Graphs and Data Sources.  See below.

![image](https://user-images.githubusercontent.com/1439914/211095857-0d3fef43-7758-4cf0-938a-373baaa5115b.png)

## To Reproduce

Simply create a device an note the values here.

## Expected behavior

Cacti should show 0.

**Comment by netniV** [comment]
I'm not sure that's incorrect, It shows no items by inference of null.  But I guess we could default to 0.
