### ISSUE TITLE
1.3.0 - QA Device SNMP and Ping Option visibility logic incorrect

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#5146]
# Describe the bug

When SNMP and Ping settings are set to `None` options for those settings should be completely hidden and they are not.

## Expected behavior

Cacti Device Context form visibility settings should work as expected.

## Screenshots

![image](https://user-images.githubusercontent.com/1439914/211154784-ea462e06-d7b5-400d-a033-e3b2c92be5d7.png)

**Comment by netniV** [comment]
This is underway but having a strange selectmenu issue so not committed yet.
