### ISSUE TITLE
The Import Package cli script displays the wrong 'info' parameter

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#5150]
# Describe the bug

When using the import_package.php script, the help says that there is an option called `--only-info` but that option does not exist.  The correct name is `--info-only` but both of these could be shortened to `--info` which is a more common parameter name usage.

## To Reproduce

```
php -q import_package.php --help
php -q import_package.php --only-info [file]
```
## Expected behaviour

```
php -q import_package.php --info [file]
```

**Comment by TheWitness** [comment]
Porting done.
