### ISSUE TITLE
1.2.23 - Login mask didn't show the correct cacti version

### ISSUE THREAD

**Issue by anarkia1976** [Cacti/cacti#5152]
Hi Guys,

as per attached screen login mask didn't show the correct cacti version:
![image](https://user-images.githubusercontent.com/1744639/211485180-d6124b8e-5a31-4281-8020-9b1938309610.png)

thanks a lot.

**Comment by TheWitness** [comment]
Can you grab the latest 1.2.x.  There was a series of changes recently.

**Comment by TheWitness** [comment]
Confirming.  No changelog on this one as it's a regression.  I'm surprised this ever worked.  Update auth_login.php and this will be resolved.  @anarkia1976, thanks for reporting!
