### ISSUE TITLE
Separate inbound and outbound graph data

### ISSUE THREAD

**Issue by gpahlevanzadeh** [Cacti/cacti#5153]
I define a device and connected to a SNMP and get data  and generate graph fine. Now I want to generate two graph 1. in bandwith 2. out bandwith.
How can I seperate them?

**Comment by bmfmancini** [comment]
Hello @gpahlevanzadeh  to do this you will have to make separate graph templates 
check out this page from our documentation section 

https://github.com/Cacti/documentation/blob/develop/Graph-Templates.md

if you have more questions please checkout our forums
https://forums.cacti.net !
