### ISSUE TITLE
Description and/or hostname Automation Device Rules

### ISSUE THREAD

**Issue by Fabrice35** [Cacti/cacti#5156]
Hi,

I have some Lightweight Access Points that only answer a ping, but if I create a Automation Device Rules for them, my switches will also match this rule ...

Could it be possible to add an Automation Template on the description and/or hostname in the Automation Device Rules ?

Thank you.
BB

**Comment by Fabrice35** [comment]
I understand, but I can't do that because my AP have no "intelligence". They are managed by a controller, they are so-called Lightweight Access Points that only respond to ping (no snmp).

**Comment by bmfmancini** [comment]
you would still be able to do this but it wouldn't be fully automated

1.) Create a template called ping
2.) scan the subnet with the AP's with the avability method being ICMP
3.) IP's that respond will be put into the discovered devices section
4.) select the devices add select the ping template 

this saves you from manually adding one by one

**Comment by Fabrice35** [comment]
Thank you for your answer.

Sorry, but sysName is "SNMP Name":
```
 automation_devices.php:
       'sysName' => array('display' => __('SNMP Name'), 'align' => 'left', 'sort' => 'ASC'),
```
As sysDescr is snmp_sysDescr ...

But my Lightweight Access Points are without snmp.
That's why it should be possible to match the description and/or hostname.

Thanks

**Comment by TheWitness** [comment]
Look at recent commits around #412.  I'm way down the rabbit hole, but now taking a few days break.

**Comment by Fabrice35** [comment]
Can you reopen this unresolved issue ?

**Comment by Fabrice35** [comment]
Hi,

I would like to filter on the "hostname" and/or "description" of a non-SNMP device (not on SNMP sys******* tables).
Can you add this feature?

I'd rather not try to change the code, I'll make mush :-S 

BB

**Comment by Fabrice35** [comment]
Hello,

Can anyone confirm the feasibility?

Thank you 

BB

**Comment by Fabrice35** [comment]
This is great news.
Thank you very much.
I'll just wait for v1.3...

BB
