### ISSUE TITLE
Complete Username is not shown in the logs

### ISSUE THREAD

**Issue by Nitin797** [Cacti/cacti#5157]
Cacti 1.2.18
Spine 1.2.19
MariaDB 10.3.
OS: Linux
Browser: Chrome

Hi Team,

We noticed that when we try to login to the GUI with our username and password (LDAP) the cacti logs show the user who logged in but when we close and re-open the session in the logs it shows only the first character of the user.

Do we need to change anything in the auth.php to take the full name of the user who logs in everytime.

![image](https://user-images.githubusercontent.com/110081629/212040078-9d77469a-b1f9-463d-865a-194ad1c0ceff.png)

**Comment by netniV** [comment]
That username is passed in from line 105 of auth_login.php, which in turn gets it from `auth_get_username()`.  It is possible, that the sanitize_search_string is affecting that, but if so, that should be happening every time.  Are you using the remember me option?

**Comment by Nitin797** [comment]
Yes, using remember me option

**Comment by TheWitness** [comment]
You should consider upgrading your GUI to 1.2.23.  Do NOT import the Packages though.

**Comment by Nitin797** [comment]
Sure, Thank you.

**Comment by TheWitness** [comment]
I'm pretty sure this is working in 1.2.23.  So, I'm going to close for now.
