### ISSUE TITLE
Fix issue to allow interface status without having to change later

### ISSUE THREAD

**Issue by arno-st** [Cacti/cacti#516]
Since many people use Interface status I suggest that you fix it on the Cacti source.
The change are the following:
under lib/snmp.php:
define("REGEXP_SNMP_TRIM", "/(hex|counter(32|64)|gauge|gauge(32|64)|float|ipaddress|string|integer):|(up|down)(|)$/i");

under resource/snmp_queries/interface.xml
under
VALUE/REGEXP:[a-zA-Z]{1,}\(([1-]{1})+\)$ output

And create a graph and data template based on the attached file
[cacti_graph_template_interface_-_status.xml.txt](https://github.com/Cacti/cacti/files/890299/cacti_graph_template_interface_-_status.xml.txt)

**Comment by cigamit** [comment]
There is a separate bug open on this already...
