### ISSUE TITLE
Switching language in the settings only becomes active after removal of session cookie

### ISSUE THREAD

**Issue by paulgevers** [Cacti/cacti#5161]
# Describe the bug

While debugging issue #5160 I noticed that if I switch the language in the settings.php page, they do not become active. I can active the language by clearing my session cookie.

## To Reproduce

1. Go to '/cacti/settings.php'

2. Change the value under  'language' and set 'Auto Language Detection' to `Disabled`

3. Hit the `Save` button

4. See the pop-up window appearing in the original language.

## Expected behavior

Selected language becomes active immediately

## Desktop (please complete the following information)

- OS: Linux on Debian `bookworm`

- Browser: Firefox

- Version: 102.6.0esr

**Comment by TheWitness** [comment]
@paulgevers, please test with the latest settings.php in the 1.2.x branch.

**Comment by paulgevers** [comment]
@TheWitness I was finally able to check it. I'm sorry to say but with only commit 446c1d6, it doesn't seem to work for me.

**Comment by TheWitness** [comment]
Paul, could you provide a screen2gif of the UI action?

**Comment by paulgevers** [comment]
[vokoscreenNG-2023-01-19_21-04-35.webm](https://user-images.githubusercontent.com/3652166/213548431-7c2d030e-2dee-4feb-bcc5-428dcf81d98b.webm)

**Comment by TheWitness** [comment]
Okay, I addressed a different issue, but same process.  On it.
