### ISSUE TITLE
1.3.0 - DSSTATS - Add Additional Data Source Statics to Cacti

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#5163]
# Feature Request

## Is your feature request related to a problem? Please describe

Calculating Peak and Average is fine, but there are so many other relevant statistics that should be calculated.  Add an option to have them.

## Describe the solution you'd like

Percentiles, Variance, Standard Deviation.  Something that might go into a whisker chart for example.

## Additional context

Awesome data for dashboarding.

**Comment by netniV** [comment]
Statics huh ? ;-)

**Comment by TheWitness** [comment]
This Enhancement will do a few things.

1) Provide additional statistics
2) Will do this in parallel as do the others
3) Will leverage the RRDtool socket to improve performance as much as possible
4) Still toying with the idea of doing daily/weekly/monthly/yearly snapshots of the various tables and implementing retention periods.
5) Possible pruning of these new partition tables as devices and metrics come and go, and we don't really keep those statistics their parent relationships anyway once they are removed.
