### ISSUE TITLE
When adding a new device, location is not being saved

### ISSUE THREAD

**Issue by zeleniy** [Cacti/cacti#5174]
<img width="1280" alt="Screen Shot 2023-01-17 at 1 59 38 PM" src="https://user-images.githubusercontent.com/2780617/212868530-87b05a7e-fdea-4bf3-a490-61eb83055eea.png">

**Comment by TheWitness** [comment]
What version?

**Comment by zeleniy** [comment]
Version 1.2.23

**Comment by TheWitness** [comment]
Are there any locations defined in the database?  Location is a dynamic callback from the following:

```sql
SELECT DISTINCT location FROM host;
```

This JS error only happens when you have no locations in returned from that SQL query.  As soon as you setup your first location, the JS error disappears.

**Comment by TheWitness** [comment]
Okay, fixed it.

**Comment by netniV** [comment]
I posted a question on the commit as I saw that first.  I think the value should be not internationalized for consistency between users.

**Comment by TheWitness** [comment]
Oh, good point, but I'm not sure it saves that to the file.  Will check tomorrow.

**Comment by netniV** [comment]
It's part of the edit fields so it will.

**Comment by TheWitness** [comment]
I've got the solution.  Take care in the AM.

**Comment by netniV** [comment]
Looks good to me.  Just waiting on confirmation from @zeleniy

**Comment by TheWitness** [comment]
Cool
