### ISSUE TITLE
PHP 8.2 rendering first graph only on a page full of graphs.

### ISSUE THREAD

**Issue by hemiawd** [Cacti/cacti#5175]
# Describe the bug

PHP 8.2 rendering first graph only on page of graphs.

## To Reproduce

1. Go to 'Graphs'

2. Click on 'a switch full of graphs'

4. See error box pops up in FireFox - 500 Internal Server Error, The response to the last action was unexpected

PHP Error Log displays - 
[17-Jan-2023 11:43:29 America/New_York] PHP Fatal error:  Uncaught TypeError: Unsupported operand types: string + int in C:\inetpub\wwwroot\lib\rrd.php:984
Stack trace:
#0 C:\inetpub\wwwroot\lib\graph_variables.php(333): rrdtool_function_fetch()
#1 C:\inetpub\wwwroot\lib\graph_variables.php(607): bandwidth_summation()
#2 C:\inetpub\wwwroot\lib\rrd.php(1658): variable_bandwidth_summation()
#3 C:\inetpub\wwwroot\graph_json.php(159): rrdtool_function_graph()
#4 {main}
  thrown in C:\inetpub\wwwroot\lib\rrd.php on line 984

## Expected behavior

All Graphs should display.

## Screenshots

easily reproduced

## Desktop (please complete the following information)

- OS: Win10

- Browser Firefox

- Version 102.6.0esr

## Smartphone (please complete the following information)

- Device: N/A - not tested

## Additional context

Error is server side, not browser - IIS8.5 PHP NTS 8.2.1 x64

rrd.php - line 984

as it appears: 
$fetch_array['values'][$index][$timestamp] = $number + 0;

corrected:
$fetch_array['values'][$index][$timestamp] = (int)$number + 0;

Solution in line with error description, PHP 8.2 
PHP Fatal error:  Uncaught TypeError: Unsupported operand types: **string + int** in C:\inetpub\wwwroot\lib\rrd.php:984

**Comment by TheWitness** [comment]
Which code branch develop or 1.2.x?

**Comment by netniV** [comment]
1.2.x doesn't officially support 8.2. 1.3.x will

**Comment by TheWitness** [comment]
Yea, I think it's safe to push this to 1.3.x.  better stick with PHP8.1 for now.

**Comment by TheWitness** [comment]
I would like to get more information though. If you know the specific graph it's cashing on, I would like to send you and instrumented binary.  Will that work.  Just one file.

**Comment by TheWitness** [comment]
Please edit `lib/rrd.php` and add the three lines as below and then post your cacti.log after the error occurs.

![image](https://user-images.githubusercontent.com/1439914/213325176-c57703b1-e79a-4ef6-9151-39354682f9cb.png)

**Comment by TheWitness** [comment]
@hemiawd, waiting for your feedback.  Please respond.

**Comment by TheWitness** [comment]
@hemiawd Still waiting on you buddy.

**Comment by TheWitness** [comment]
No feedback.

**Comment by TheWitness** [comment]
By the way @hemiawd, typing to (int) is not appropriate as that number can also be a float.  So, you solution is NOT correct.

**Comment by TheWitness** [comment]
I did a change to at least mask this issue for now.
