### ISSUE TITLE
Weathemaps not visible for a user who is already part of user group

### ISSUE THREAD

**Issue by Nitin797** [Cacti/cacti#5179]
Hi Team,

Hope you could help me understand on my below query.
A **user** is already part of a **user group** who has the Weathermaps view enabled but it doesn't reflect the same when a user logs in with their user account the weathermaps aren't visible and when we go the user account permissions and enable the weathermaps view and same is working.

Cacti 1.2.18
Spine 1.2.19
MariaDB 10.3.
OS: Linux
Browser: Chrome

**Comment by netniV** [comment]
You will need to provide more details such as what permission mode you are using and details of the settings you've applied.

**Comment by Nitin797** [comment]
![image](https://user-images.githubusercontent.com/110081629/213404622-b64661d9-e272-4006-b919-201086277641.png)
The above settings are enabled for the user group (example: XYZ) account and the same settings is disabled on user (example:ABC) account where the user (ABC) is already part of user group (XYZ) which has the attached snip settings enabled.

When the user(ABC) accesses the GUI the weathermaps view is not visible for him.

**Comment by Nitin797** [comment]
Note: The other feature settings are working fine except for Weathermaps.

**Comment by TheWitness** [comment]
Is this the Weathermaps version proved by the cacti group or from Howard Jones repo?

**Comment by TheWitness** [comment]
I have confirmed in Weathermap Beta1 from The Cacti Group that this issue can not be reproduced.
