### ISSUE TITLE
1.2.24 - QA: Fatal exception when processing proxy headers

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#5186]
# Describe the bug

When processing Proxy Headers, you can receive the following in your php_error log.

```sh
[root@vmhost3 tmp]# cat php_errors.log
[22-Jan-2023 10:26:10 America/Detroit] PHP Fatal error:  Uncaught TypeError: array_intersect(): Argument #2 must be of type array, null given in /var/www/html/cacti/lib/functions.php:6772
Stack trace:
#0 /var/www/html/cacti/lib/functions.php(6772): array_intersect()
#1 /var/www/html/cacti/include/session.php(95): get_client_addr()
#2 [internal function]: cacti_db_session_write()
#3 [internal function]: session_write_close()
#4 {main}
  thrown in /var/www/html/cacti/lib/functions.php on line 6772
```

This is due to the second argument being null on certain occasions

## Expected behavior

Bug Free Cacti

**Comment by TheWitness** [comment]
This appears to be the ReportIt function calling register realm repeatedly from within it's config arrays function.  That's a recipe for disaster.  We need to find a way to block that kind of behavior.

**Comment by TheWitness** [comment]
Porting complete.

**Comment by netniV** [comment]
$allowed_proxy_headers comes from the global_arrays.php if I remember rightly, so there should not be a case where this is not set.
