### ISSUE TITLE
1.2.23 - Device Template Filter broken

### ISSUE THREAD

**Issue by browniebraun** [Cacti/cacti#5188]
# Describe the bug

Device Templates will no longer be filtered by a search pattern. Instead of returning matching records only, all table records will be displayed and matching records only highlighted.  This is a misbehavior.

**Comment by TheWitness** [comment]
Please be more specific.  It's working fine in my environment.  What part of the search filter is not working?  Do you have any plugins that are over-riding the default host page like potentially the monitor plugin?

**Comment by browniebraun** [comment]
Maybe it has already been fixed in 1.2.x. Let me add a screenshot. I have the same behavior in dev and prod.

![image](https://user-images.githubusercontent.com/5182348/214305255-1d3e2d51-35b3-4e42-8ff3-266ca87e1767.png)

**Comment by browniebraun** [comment]
Ok, the error is here in host_template.php and occurs whenever the class is set to 'unassigned' or 'all'. In this case $sql_where will be overwritten.

![image](https://user-images.githubusercontent.com/5182348/214308058-a851b6c5-c108-46c5-b1b4-dfe5adc1429f.png)

**Comment by TheWitness** [comment]
Oh crap, Device Templates.  Dah!  Wake up @TheWitness
