### ISSUE TITLE
It is not possible to remove the Reporting tab in 1.1.0

### ISSUE THREAD

**Issue by gmuellerfr** [Cacti/cacti#519]
Hello,

I've just recognized, that it is not possible to remove the reporting tab in a user profile, even if you have no rights to access reporting. If you have no rights for console access, the console tab disappears. Maybe you should invent a check mark for reporting access.

Kind regards
Guenter

**Comment by gmuellerfr** [comment]
Hello,

while experimenting with the user permissions, I've recognized that this behaviour applies to the Cacti Log tab as well.

Kind regards
Guenter

![cacti_user_permissions](https://cloud.githubusercontent.com/assets/25848039/24661695/5ee2ada2-1953-11e7-973c-dc487b0af59e.png)

**Comment by cigamit** [comment]
Resolved.  Thanks for reporting.
