### ISSUE TITLE
realtime is broken in Edge since the change from issue 4871

### ISSUE THREAD

**Issue by arjanoosting** [Cacti/cacti#5192]
# Describe the bug

The realtime graph in Edge doesn't load ad the console gives an _Uncaught ReferenceError: imageOptionsChanged is not defined_ error. When searching for this error a came across issue [3538](https://github.com/Cacti/cacti/issues/3538) but that one was closed in 2020. 
When looking at the actual code, i saw the change of 3538 was reverted in issue [4871](https://github.com/Cacti/cacti/issues/4871)
I have reverted the change from 4871 and then the realtime graph loads again in Edge.

## To Reproduce

1. Open Cacti in Edge (I have version 109.0.1518.52) 

2. Go to Graphs 

3. Open a Graph in 'Time Graph View'

4. Click on 'Click to view just this Graph in Real-time' 

5. The resulting pop-up will display the selection bar, but no graph is loaded.

## Expected behavior

I expected an graph to be loaded an refreshed at the selected timespan.

## Screenshots

Will add them later if necessary

## Desktop (please complete the following information)

- OS: Windows

- Browser Edge

- Version 109.0.1518.52

**Comment by TheWitness** [comment]
Sorry, I can not reproduce this on 1.2.23+.  I've tested both inline and new window and they are both working perfectly.  Look for JavaScript errors.  Could be you need to purge your browser cache.

**Comment by TheWitness** [comment]
We found the issue in another ticket and it's fixed.
