### ISSUE TITLE
php snmp vs snmp tool set

### ISSUE THREAD

**Issue by jdcoats** [Cacti/cacti#5193]
In previous versions and advice from Cacti dev's ive been advised to not use php snmp and use snmp tool set.
When testing 1.2.24 during the upgrade I could not upgrade without re-installing php snmp. Which is it. With or without snmp php module support built in?

**Comment by jdcoats** [comment]
So currently you cannot install 1.2.24 and use snmpv3?

PHP SNMP	Installed. Note: If you are planning on using SNMPv3, you must remove php-snmp and use the Net-SNMP toolset.

**Comment by jdcoats** [comment]
also the system utilities/techsupport pages do not expand to the full data, you cannot see the full my.cnf or php module data on the tabs.

**Comment by TheWitness** [comment]
You should not have been forced to update to php-snmp.  It's specifically optional.  Are you sure you were forced?

**Comment by jdcoats** [comment]
positive. It was orange thumbs down warning for php module and would not give me the next button.

**Comment by TheWitness** [comment]
Okay, that's a new bug.  Let me verify.

**Comment by TheWitness** [comment]
Must have been something else.  I'm able to bypass, even with the MySQL/MariaDB stuff which we kind of make optional for some things.

![UpgradeTo1224_php_snmp](https://user-images.githubusercontent.com/1439914/214860534-e21bac11-7802-4d67-8ce5-ceec853bbcc0.gif)

**Comment by jdcoats** [comment]
Interesting, mine looked like that with no both but instead of the orange warning triangle it was a thumbs down and the next was not allowed. I know its not required so after i got through the upgrade I just rebuilt php without snmp again.

**Comment by jdcoats** [comment]
only difference i notice is I was going from 1.2.23 to 1.2.24

**Comment by jdcoats** [comment]
I just reverted my version in the database and ran through again and cannot reproduce. Who knows, maybe its related to me following code so closely behind your changes that I was in a odd state that caused it.

**Comment by TheWitness** [comment]
Appreciate you doing the QA.  Seriously.
