### ISSUE TITLE
CSRF directory needs to be writeable for creating the csrf-secret.php file

### ISSUE THREAD

**Issue by thurban** [Cacti/cacti#5194]
# Describe the bug

During the installation the installer tells you to make the CSRF path read-only after the installation finished.  It does not tell where it is or provide an example for how to set the write permissions.
The installation completes regardless of the setting but it causes a lot of permission error logging in the cacti log.

Also the csrf-secret.php file can be access directly, exposing the secret to the web. It should be hidden and not returning the plain secret.

## To Reproduce

Install a fresh Cacti

## Expected behavior

Either show example commands or move the csfr-secret.php somewhere where it can be written/created.

## Screenshots

![grafik](https://user-images.githubusercontent.com/17292964/214830510-3c8ccc11-e3cb-47a0-b3cb-2d15194debb5.png)
![grafik](https://user-images.githubusercontent.com/17292964/214831001-5ba3f268-986b-4322-8542-38cb1b63c1f7.png)

**Comment by TheWitness** [comment]
@netniV, assigned this to you.  I think at least in the example we should show the vendor directory, without much explanation as a directory that only requires write for install.  This is a one line change.  We can do something glorious (aka different) in 1.3.

**Comment by TheWitness** [comment]
Changing the assignment here since we have a little more time before release.
