### ISSUE TITLE
Remote Poller Upgrade | It does not load localhost info from config.php

### ISSUE THREAD

**Issue by zuka1337** [Cacti/cacti#5213]
Hello,

Long time no see ;)

I'm having an issue with a remote poller upgrade:
Setup:

- BD
- MAIN
- Poller01
- Poller02
- Poller03

```
$database_type     = 'mysql';
$database_default  = 'cacti3';
$database_hostname = 'localhost';
$database_username = 'cacti';
$database_password = 'PASS';
$database_port     = '3306';
$database_retries  = 5;
$database_ssl      = false;
$database_ssl_key  = '';
$database_ssl_cert = '';
$database_ssl_ca   = '';
$database_persist  = false;

/**
 * When the cacti server is a remote poller, then these entries point to
 * the main cacti server. Otherwise, these variables have no use and
 * must remain commented out.
 */

$rdatabase_type     = 'mysql';
$rdatabase_default  = 'cacti';
$rdatabase_hostname = 'CETPCACT001';
$rdatabase_username = 'cacti';
$rdatabase_password = 'PASS';
$rdatabase_port     = '3306';
$rdatabase_retries  = 5;
$rdatabase_ssl      = false;
$rdatabase_ssl_key  = '';
$rdatabase_ssl_cert = '';
$rdatabase_ssl_ca   = '';
```
Centos7
Upgrade from 1.2.7 -> 1.2.23

![image](https://user-images.githubusercontent.com/57998098/215921942-891cc6af-0309-4868-93d4-82a2599a4114.png)

Can you point me out what am I missing ?

**Comment by TheWitness** [comment]
Do you have file replication enabled?  If not, enable it, and then do a full sync.

**Comment by TheWitness** [comment]
Then, it'll auto-upgrade

**Comment by zuka1337** [comment]
Very smooth !thanks, now all upgraded :D

Can you tell-me about this issue:

CMDPHP ERROR: A DB Exec Failed!, Error: Unknown or incorrect time zone: 'Europe/Lisbon':

![image](https://user-images.githubusercontent.com/57998098/215930022-d6393568-ed3f-4706-82bc-0855bf7be00e.png)


Tell-me if you need-me to open a new issue for it.

**Comment by TheWitness** [comment]
Well that's weird.  Yea, you better log it.  Maybe a PHP issue.  Not sure.
