### ISSUE TITLE
CMDPHP - Unknown or incorrect time zone: 'Europe/Lisbon'

### ISSUE THREAD

**Issue by zuka1337** [Cacti/cacti#5218]
# Describe the bug

Cacti log trace Incorrect Time Zone.

## To Reproduce

Since upgrade this case show up:

![image](https://user-images.githubusercontent.com/57998098/216086628-03ce8285-f622-4424-ac28-c717e41be144.png)

> CMDPHP` SQL Backtrace (/resource/scripts/nokia/query_nokia_dhcp_ipoe.php[11]:include(),/include/global.php[385]:db_execute_prepared()) -----> Is this part of the backtrace ?

> CMDPHP ERROR: A DB Exec Failed!, Error: Unknown or incorrect time zone: 'Europe/Lisbon'

## Expected behavior

Select Poller TimeZone should do it ?

## Screenshots

![image](https://user-images.githubusercontent.com/57998098/216085947-83762ef4-25bc-4f0a-ab04-c729d6546ed2.png)

**Comment by zuka1337** [comment]
Points to here:
```
378 if ($config['poller_id'] > 1) {
379         $timezone = db_fetch_cell_prepared('SELECT timezone
380                 FROM poller
381                 WHERE id = ?',
382                 array($config['poller_id']));
383
384         if ($timezone != '') {
385                 db_execute_prepared('SET time_zone = ?', array($timezone));
386         }
387 }
```

**Comment by netniV** [comment]
This suggests that the timezone being selected is not a valid timezone in the MySQL timezone database.  Have you loaded the MySQL timezone info?

**Comment by netniV** [comment]
Additionally, that line of code has not changed in 4 years 👍

**Comment by bernisys** [comment]
I'd say the same .. try to initialize the timezone DB:

`mysql_tzinfo_to_sql /usr/share/zoneinfo/ | mysql -u root -p mysql`

**Comment by TheWitness** [comment]
Spot on:

```sh
MariaDB [mysql]> select * from time_zone_name where name like 'Europe/L%';
+-------------------+--------------+
| Name              | Time_zone_id |
+-------------------+--------------+
| Europe/Lisbon     |          449 |
| Europe/Ljubljana  |          450 |
| Europe/London     |          451 |
| Europe/Luxembourg |          452 |
+-------------------+--------------+
4 rows in set (0.001 sec)
```

**Comment by bernisys** [comment]
BTW wouldn't it be a good idea to place a hint into a log?
At least something like "DB table time_zone_name is not populated or not accessible. Please check the Cacti setup manual to resolve this issue."

I think it helps new users a lot to get to know better all the things that need to be configured. Can be frustrating if you do this for the 1st or 2nd time only.

**Comment by TheWitness** [comment]
Yea, makes sense.

**Comment by TheWitness** [comment]
I re-opened this, and then gave it some though.  I suspect it's better to catch this at install time.  Must be for a remote data collection.  @zuka1337 can you confirm?

**Comment by zuka1337** [comment]
@TheWitness it is only on remote pollers, and @netniV was right for some reason I dont have the timezone on the BD.
But I didn't know before cause it wasnst logged..

```
MariaDB [mysql]> select * from time_zone_name ;
+--------------------+--------------+
| Name               | Time_zone_id |
+--------------------+--------------+
| MET                |            1 |
| UTC                |            2 |
| Universal          |            2 |
| Europe/Moscow      |            3 |
| leap/Europe/Moscow |            4 |
| Japan              |            5 |
+--------------------+--------------+
6 rows in set (0.045 sec)

```

I will fix it today

**Comment by TheWitness** [comment]
You may have adjusted the time zone of your poller which would cause this.

**Comment by zuka1337** [comment]
Done !
```
MariaDB [mysql]> select * from time_zone_name where name like 'Europe/L%';
+-------------------+--------------+
| Name              | Time_zone_id |
+-------------------+--------------+
| Europe/Lisbon     |          448 |
| Europe/Ljubljana  |          449 |
| Europe/London     |          450 |
| Europe/Luxembourg |          451 |
+-------------------+--------------+
4 rows in set (0.001 sec)

MariaDB [mysql]>
```
I have no more errors

**Comment by TheWitness** [comment]
Cool.

**Comment by netniV** [comment]
@TheWitness maybe we could put something in the MySQL info section to show when the timezone isn't in the DB for 1.3 ?

**Comment by TheWitness** [comment]
Yea, that's a good bit for technical support.  We could actually do a timezones check on full sync too.  Have to debounce the error if we do something during polling.
