### ISSUE TITLE
ERROR: A DB Row Failed | 'last_updated' in 'where clause'`

### ISSUE THREAD

**Issue by zuka1337** [Cacti/cacti#5219]
# Describe the bug

Poller Log:

## 

![image](https://user-images.githubusercontent.com/57998098/216089001-533552ca-0380-4871-ab8f-151e7080a80a.png)

`2023/02/01 15:31:13 - CMDPHP SQL Backtrace(/poller_commands.php[228]:run_data_query(),/lib/data_query.php[396]:poller_push_reindex_data_to_poller(),/lib/poller.php[1929]:db_fetch_assoc_prepared(), /lib/database.php[697]:db_execute_prepared())`
`2023/02/01 15:31:13 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'last_updated' in 'where clause'`

**Ps:** Sorry for the issue spam, tell-me if is easy to open in other way

**Comment by netniV** [comment]
This is a duplicate of #5191
