### ISSUE TITLE
Cannot be created based on Aggregate Templates

### ISSUE THREAD

**Issue by htyypt** [Cacti/cacti#5230]
Version 1.2.23

![image](https://user-images.githubusercontent.com/81215528/217209793-240cf902-83f3-48b0-8626-3934d39d4cb0.png)
![image](https://user-images.githubusercontent.com/81215528/217210390-0b58dc23-d173-48d5-a921-9270cb31651e.png)

Why only 2?

**Comment by TheWitness** [comment]
Did you figure out why?

**Comment by htyypt** [comment]
Only graphs created based on the same template can discover aggregated templates. Is it designed like this or is it a bug? @TheWitness

**Comment by TheWitness** [comment]
Yes, that is by design.  You can always build an aggregate by hand.  It's a bit less fun, but I know several who do it that way.

**Comment by TheWitness** [comment]
You just enable the "Advanced" mode Graph Creation in `Console > Configuration > Settings > General`

**Comment by htyypt** [comment]
thanks
