### ISSUE TITLE
When editing a Device show in state/uptime as a date in the header

### ISSUE THREAD

**Issue by xmacan** [Cacti/cacti#5231]
Device list contains duration In states and Uptime. Sometimes could be useful to have information about "since when" instead of duration.

Two possibilities - switch between duration/since when on device list or something like in screenshot.
![Screenshot 2023-02-08 at 19-59-47 Console Devices (Edit)](https://user-images.githubusercontent.com/26485719/217627408-4ab861d4-71ed-4ab3-a61b-95317fe25ee8.png)

**Comment by bmfmancini** [comment]
This could be good but the only issue is that the user would need to have console access to view it
