### ISSUE TITLE
Cannot separate in/out 95th percentile line on Aggregation

### ISSUE THREAD

**Issue by seyma-n** [Cacti/cacti#5233]
Hello,

I am having Cacti version 1.2.15 running. After a while of trying to figure out without luck, I am here looking for help from the community.

I have multiple 95th-percentile graphs. When I aggregate them together, I face 2 problems:
1. The aggregate graph does not show 95th percentile for outbound.
2. The value of 95th percentile is in Mbps instead of Gbps.
Any advice/suggestion to fix these 2 issues, please?

![image](https://user-images.githubusercontent.com/97157189/217993899-2e4fb520-7e04-41e2-b2f3-8793613ee693.png)

Regards,

**Comment by TheWitness** [comment]
Post your Graph Template.  I'm specifically looking for the 95th percentile comment line.

**Comment by TheWitness** [comment]
I'm going to recommend you go to the support forums for this solution as it's mainly a training issue.

**Comment by seyma-n** [comment]
Hello @TheWitness , apologize for the late response as I was away from PC for a few days. I would like to check if you can help and look into this so that I can share the Graph Template. Or do you think I should post the issue to the support forums still?

Regards,

**Comment by seyma-n** [comment]
Here is the 95th percentile comment line. Really appreciate if you could help to look into this and advise some suggestions.
![image](https://user-images.githubusercontent.com/97157189/219996046-bc3cba97-5a25-43f1-83d2-27a8c8af1271.png)

Regards,

**Comment by TheWitness** [comment]
https://docs.cacti.net/Variables.md

**Comment by seyma-n** [comment]
Hello @TheWitness , thanks for sharing the docs, I will have a look at that and make some changes to my template.

Regards,

**Comment by seyma-n** [comment]
Just to provide an update, I can change the return value from Mbps to Gbps now by using "COMMENT: |95:bits:9:aggregate:3| Gbps". 
Now I am still finding a way to produce the Aggregation for 95th Percentile Outbound.
