### ISSUE TITLE
Device not getting added using add_device.php from CLI

### ISSUE THREAD

**Issue by phil-1666** [Cacti/cacti#5234]
# Describe the bug

Device not getting added using add_device.php from CLI

## To Reproduce
php add_device.php --description=test2023-02-10 --ip=10.10.10.12
Adding test2023-02-10 (10.10.10.12) as "Generic SNMP-enabled Host" using SNMP v0 with community ""
Success - new device-id: (0)

Can not find device searching under devices in GUI

## Expected behavior

Should be able to find device.

## Desktop (please complete the following information)

- OS: [e.g. iOS] opensuse

- Browser [e.g. chrome, safari] firefox

- Version [e.g. 22] 109.0.1

## Additional context

Cacti logs show:
2023/02/10 14:26:16 - CMDPHP ERROR: A DB Exec Failed!, Error: Column 'monitor' cannot be null
2023/02/10 14:26:16 - CMDPHP SQL Backtrace:  (/cli/add_device.php[452]:api_device_save(), /lib/api_device.php[749]:sql_save(), /lib/database.php[1472]:_db_replace(), /lib/database.php[1402]:db_execute(), /lib/database.php[238]:db_execute_prepared())

I do have the thold and monitor plugins installed and activated.

To me, this sounds similar to issue #3111.

**Comment by phil-1666** [comment]
I just tried it on an older install we have, 1.2.16, on a SLES server. This install has the thold and monitor plugins installed but both are disabled.

Version of our current Cacti is 1.2.18.

**Comment by bmfmancini** [comment]
Disable the monitor plugin see if that works first

If it does then we can narrow it down

**Comment by TheWitness** [comment]
The monitor plugin does make some changes.  I'm going to close this one, and maybe look to see if there is something in Monitor that needs attention.

**Comment by phil-1666** [comment]
Thanks - temporarily disabling monitor seems to be a pretty good work around.
