### ISSUE TITLE
cacti version 1.1.38 ，The switch template is abnormal, and only the port outbound traffic can be obtained

### ISSUE THREAD

**Issue by dreamhighhd** [Cacti/cacti#5235]
cacti version: 1.1.38

systeminfo: centos7.9

weathermap version: 0.98a

apache version: 2.4.6

mariadb version: 10.2.44

php version: 5.4.16

net-snmp version: 5.7.2

Device template name: ucd/net SNMP Host

Graph target name: "Interface - Traffic (bits/sec, 95th Percentile)" "Interface - Traffic (bits/sec)"

Data source name: "Interface - Traffic"

Data query name: "SNMP - Interface Statistics"

Premise description:

Because the newly installed cacti wants to use the "weathermap" plug-in, the latest "weathermap" can only support "cacti 1. x" in github, so the version of cacti was downgraded from "1.2x" to "1.1.38" at that time. The "cacti 1.1.38" version used is downloaded from the official website of cacti, "Weathermap" is downloaded for the official project of github. After the deployment of cacti software, it is found that there is no "device template", "graphics template", "data source", and "data query" on the web Wait, and then try to export the corresponding template from the previous 1.2. x, and find that the target contains unsupported items, which fails. After that, it was found that there was no obvious error in exporting and re-importing from the template in cacti 0.8.7. After all service switches are added to the system, it is found that the flow graph monitoring of all switch ports can only collect "outbound", and the flow graph of "inbound" cannot be displayed. At the same time, the interface often reports errors during the use of weathermap.

Problem 1: Switch port traffic monitoring can only obtain "outbound", but not "inbound"
![image](https://user-images.githubusercontent.com/40293011/218418571-a3044e4c-6798-4336-985c-dcc3f8283713.png)

Question 2: Can you provide the relevant template of cacti1.1.38
![image](https://user-images.githubusercontent.com/40293011/218418966-6b939bf7-c31d-4b45-925b-0612e784e37e.png)
![image](https://user-images.githubusercontent.com/40293011/218419080-7c348012-903b-489f-8b0d-20e6387b1dfd.png)
![image](https://user-images.githubusercontent.com/40293011/218419207-17032efe-5db4-425e-bbfb-beb2b28188aa.png)
![image](https://user-images.githubusercontent.com/40293011/218419325-b89e0b0d-bb56-4f9c-8786-f90a23f67c23.png)

Problem 3: weathermap often displays the following error and requests solutions.

(/plugins/weathermap/weathermap-cacti-plugin.php: 271 top_graph_header)(/lib/functions.php: 3573 include)(/include/top_graph_header.php: 81 draw_navigation_text)(/lib/functions.php: 2797 get_filter_request_var)(/lib/html_utility.php: 443 die_html_input_error)(/lib/html_validate.php: 64 cacti_debug_backtrace)

Validation error for variable action with a value of list view See backtrace below for more details.

**Comment by dreamhighhd** [comment]
"Question 3" weathermap is normal as shown below
![image](https://user-images.githubusercontent.com/40293011/218420342-7c34a0c7-f9ea-4b6e-aa64-5e4e6d0d491b.png)

The figure of "Problem 3" weathermap exception is as follows
![image](https://user-images.githubusercontent.com/40293011/218420453-5e19d62d-ccb0-4c83-95de-19616e2f5bac.png)

**Comment by dreamhighhd** [comment]
logs-info:
![image](https://user-images.githubusercontent.com/40293011/218422330-151ebd09-ea06-4070-9a5f-4cdcb1adb413.png)

**Comment by TheWitness** [comment]
Okay, I'm going to close this, but I will give you three suggestions.

1) Upgrade to 1.2.24 as soon as it's available
2) Once you are upgraded, also upgrade to the latest WeatherMaps here on the Cacti GitHub repo.
3) When you open bugs in the future, open one bug for each issue and ensure that you are logging in the correct repositories issue list.  The backtraces in the Cacti log should give it away.
