### ISSUE TITLE
SNMP-Options - Bulk Walk Maximum Repetitions ignored

### ISSUE THREAD

**Issue by thomasbuesser** [Cacti/cacti#5239]
# Describe the bug

If you change the value for Bulk Walk Maximum Repetitions on the SNMP-Options Page the value is not written to the DB

## To Reproduce

1. Go to '/cacti/automation_snmp.php?action=item_edit&item_id=4&id=1'

2. Change 'Bulk Walk Maximum Repetitions' from Auto to '1 Repetition'

3. Save

4. Reopen Item

## Expected behavior

1 Repetition should be saved

**Comment by TheWitness** [comment]
You did not state your Cacti version.

**Comment by thomasbuesser** [comment]
sorry, Version 1.2.23 - fresh installed on freebsd

**Comment by TheWitness** [comment]
Okay, thanks for the confirmation.

**Comment by TheWitness** [comment]
Can you update to the 1.2.x branch and see if the problem persists?  I believe this was recently addressed.  I was able to save to 1 and then check back.  Going to let it simmer a few polling cycles and re-indexes and see if it changes back to auto though.  Yea, it's working as expected on the 1.2.x branch.  Sorry for the inconvenience, and thanks for reporting.

**Comment by TheWitness** [comment]
Duplicate bug is here: https://github.com/Cacti/cacti/issues/5145

**Comment by thomasbuesser** [comment]
i will... give me a few days for testing

**Comment by thomasbuesser** [comment]
tried it: no success

the form-field bulk_walk_size is not processed in automation_snmp.php --> isset_request_var('save_component_automation_snmp_item')

**Comment by TheWitness** [comment]
Oh geeze I completely missed that it was for automation. Let me look into that.

**Comment by TheWitness** [comment]
Okay, I've done the fix now.  Thanks for continuing to pester me ;)
