### ISSUE TITLE
Reporting Issue

### ISSUE THREAD

**Issue by komathodivijay** [Cacti/cacti#524]
I have installed in cacti Version 1.1.2 in centos 7. I have create the scheduled report and add the device in Graph Tree Branch. Pls let us know the Graph Name Regular Expression to select all graphs to include from the tree.

As of now i have select "Graph" in graph type and select the device with required graph. This method will be difficult if you want to add more than 10 Devices.

Moreover i want to send the alerts to system admin, if host is down. pls let us know the steps.
.

**Comment by cigamit** [comment]
The first I would simply use an asterix or a period as the regex.  The second, you should install thold and monitor plugins.  They provide that capability.

**Comment by komathodivijay** [comment]
I have tried both expression  "*" and "regex" in Graph Name Regular Expression. But graph is not populated in Preview tab

**Comment by komathodivijay** [comment]
As mentioned above i have installed monitor plugin But in the plugin Management it shows as incompatible.
![plugin](https://cloud.githubusercontent.com/assets/26949629/24737822/4e7ecca4-1aaf-11e7-9ab2-91cd4e949fef.JPG)

**Comment by komathodivijay** [comment]
I have installed both plugin. Pls let us know the status of reporting.
 I have tried both expression "*" and "regex." in Graph Name Regular Expression. But graph is not populated in Preview tab

**Comment by cigamit** [comment]
The asterisk (*) is not going to be correct.  Though the period works perfectly.  So, your regex would be simply '.'.

**Comment by cigamit** [comment]
Must be an old monitor plugin.

**Comment by komathodivijay** [comment]
I have give period '.' in the expression filed. But graph is not showing in preview tab.
![report item](https://cloud.githubusercontent.com/assets/26949629/24847303/b36a8348-1ddd-11e7-972a-ce54fa398714.JPG)
![preview](https://cloud.githubusercontent.com/assets/26949629/24847312/b9f34ed4-1ddd-11e7-89a5-c11cc380d21e.JPG)

**Comment by komathodivijay** [comment]
I have give period '.' in the expression filed. But graph is not showing in preview tab.

**Comment by cigamit** [comment]
I see the problem now, a Device Tree branch type was never validated.  I'll reopen this now.

**Comment by cigamit** [comment]
Resolved now, thanks for sticking with it!
