### ISSUE TITLE
Not escaping LAST GPRINT in Cacti 1.1.2

### ISSUE THREAD

**Issue by jsarmento** [Cacti/cacti#525]
While using Cacti 1.1.2 I was getting some error in some graphs:
```
ERROR: Unused arguments "%8.2lf%s" in...
GPRINT:b:LAST:Current:%8.2lf%s
```

After some debugging and looking around, while using the rrdtool debug it seemed weird that there was no escape for LAST GPRINT while AVERAGE and MAX were escaped.

E.g.
```
GPRINT:de:LAST:Current\:%8.2lf%s  \
GPRINT:dd:AVERAGE:'Average\:%8.2lf%s'  \
GPRINT:df:MAX:'Maximum\:%8.2lf%s\n' 
```

Solution:
Change lib/rrd.php

Original line 1873:
`$txt_graph_items .= 'GPRINT:' . $data_source_name . ':LAST:' . ($graph_variables['text_format'][$graph_item_id] . $graph_item['gprint_text'] . $hardreturn[$graph_item_id]) . ' ';
`
Corrected line 1873:
`$txt_graph_items .= 'GPRINT:' . $data_source_name . ':LAST:' . cacti_escapeshellarg($graph_variables['text_format'][$graph_item_id] . $graph_item['gprint_text'] . $hardreturn[$graph_item_id]) . ' ';
`

**Comment by cigamit** [comment]
Resolved, thanks for catching.
