### ISSUE TITLE
incorrect collation validation message during installation

### ISSUE THREAD

**Issue by peter9370** [Cacti/cacti#5250]
# Describe the bug

I'm trying to install cacti on a devuan chimaera system (== debian bullseye without systemd).  The mysql is percona 5.6.37-82.2
Cacti version (installed from the devuan/debian repository) is 1.2.16+ds1-2+deb11u1

During the install procedure, a warning message appears saying:

"Your database default collation does NOT appear to be full UTF8 compliant"

- even though in the mysql system,  collation_database=utf8mb4_unicode_ci and character_set_database=utf8mb4

I looked at /usr/share/cacti/site/lib/installer.php, and found that the function isValidCollation (line 1410 in my copy), appears to be looking for variables starting "charset_".  But in the version of mysql which I'm using, the global variables giving the character set values begin with "character_set_". 

I tried changing 'charset_'  to 'character_set_' on lines 1410 and 1411 and refreshing the install page. This time, there was no warning message. I then backed out the changes - warning message came back.

Apologies if I'm missing something.  If not, I'm happy to include instructions for replicating this.

**Comment by TheWitness** [comment]
I suggest you update.  This issue was fixed some releases ago.  Thanks for reporting none-the-less.
