### ISSUE TITLE
ss_gexport: ExportDuration:0 TotalGraphsExported:0

### ISSUE THREAD

**Issue by WirthmU** [Cacti/cacti#5256]
# Describe the bug

The ss_gexport script always gives zero values for ExportDuration and TotalGraphsExported.

And also the ss_poller.php script is missing ss_gexport (it still is ss_export).

Most propably this is associated with the warning:
`PHPSVR WARNING: Function does not exist INC: 'ss_poller.php' FUNC: 'ss_gexport' PARMS: `

Cacti version 1.2.24

**Comment by netniV** [comment]
ss_gexport is a completely different script from ss_poller.  ss_export is correctly named.

**Comment by netniV** [comment]
On the export duration and number of graphs, make sure you are actually running the gexport at all.  Any gexport issues should be reported against its own repo.

**Comment by TheWitness** [comment]
I've been talking to the user.  He made some local template changes that were not correct.

**Comment by WirthmU** [comment]
And yes gexport is running perfectly fine:

![image](https://user-images.githubusercontent.com/27740335/226369353-2bb6ee34-d204-4df8-82ba-3f1554361b45.png)

**Comment by TheWitness** [comment]
@WirthmU, it was changed to a Data Query some time ago when we allowed more than one export per Cacti setup.  See the image below.  Stop using the old script.  You should be able to copy old RRDfile over the new.

![image](https://user-images.githubusercontent.com/1439914/228971767-ae6f9861-e280-4f35-ae36-21b4dfd8bf29.png)

**Comment by TheWitness** [comment]
![image](https://user-images.githubusercontent.com/1439914/228971963-1222a2a8-e999-4c12-9550-45e4daeffb57.png)

**Comment by WirthmU** [comment]
It worked - thank you for your support.

**Comment by TheWitness** [comment]
No, I don't think so.  Nice thing to add. You should give it a try.
