### ISSUE TITLE
 "Packets out of order. Expected 1 received 0." in version 1.2.24

### ISSUE THREAD

**Issue by PonomarenkoVladimir** [Cacti/cacti#5260]
# Describe the bug

On the browser screen, on any page, a message appears:
Warning: Packets out of order. Expected 1 received 0. Packet size=145 in /usr/share/cacti-1.2.24/lib/database.php on line 107

## To Reproduce

1. Open Logs page
   The error appears after a while.
   The occurrence of the error depends on the size of the database. It may not be in some cases.
   The error appears on other pages as well.

2. See Screenshot and Apache log file error.log

## Desktop (please complete the following information)

- OS: Windosws 10

- Browser: Firefox, Chrome

- Version:  Cacti-1.2.24

## Additional context

Cacti ver.1.2.24
Server Ubuntu 20.04.5 LTS
MySQL ver. 8.0.32
PHP ver. 7.4.3-4
NET-SNMP ver.5.8

![Cacti-1 2 24-Error](https://user-images.githubusercontent.com/26214543/223090792-454f6f9d-3a2e-4848-8ad2-9ce3823e8fb1.png)
[error.log](https://github.com/Cacti/cacti/files/10897373/error.log)

**Comment by TheWitness** [comment]
Do you have SELinux enabled and enforcing?  What ping method is being used?  This is a some issue in the PHP binary likely more than Cacti.
