### ISSUE TITLE
[1.2.24] Install Wizard should use backslashes in paths for Windows

### ISSUE THREAD

**Issue by BSOD2600** [Cacti/cacti#5265]
# Describe the bug
IIS returns generic 500 error for the Technical Support page, when forward slashes are used for the spine path.  Updating the paths to use proper backslashes, solves this issue. 

The installation wizard on Windows, uses forward slashes for the various detected paths.  While typically not an issue, it should used backslashes to conform to expected Windows nomenclature.   Possibly just an edge case with Spine (cygwin related?), as the path slash issue does not affect net-snmp or rrdtool binaries.

Server 2016 and 2019.
PHP 8.1.16 with IIS and FastCGI. 
MySQL 8.0.32

## To Reproduce
Clicking on Technical Support ( utilities.php?action=view_tech ), results in a generic 500 error from IIS.

Updating the spine path from c:/spine/spine.exe to c:\spine\spine.exe, solves the issue and no more 500 errors.

## Screenshots
Enabled IIS failure logging:
![image](https://user-images.githubusercontent.com/5741811/224143675-40669e48-ca74-4fe1-935f-c5ea98a0ff9a.png)

**Comment by netniV** [comment]
Not convinced on this one. I have no issues using forward slashes within php 8.1.16. The only time it is an issue is if you are passing a path to a third party command or cmd.exe itself.

**Comment by TheWitness** [comment]
I think we need to test this one on a Windows server.  I don't have any of those...

**Comment by TheWitness** [comment]
Closing this one.  Suspect a regression in PHP.  @BSOD2600 can you report this upstream?

**Comment by netniV** [comment]
We do have a windows server to test against for the installer. I think we should revisit it whilst we are investigating the installer improvements.

**Comment by TheWitness** [comment]
@netniV, have you got this under control?

**Comment by TheWitness** [comment]
I'm going to close this one.
