### ISSUE TITLE
SPINE: Poller - SNMP timeout detected [500 ms], ignoring host

### ISSUE THREAD

**Issue by CamZie** [Cacti/cacti#5268]
Hello,

We have recently upgraded our Cacti installation to version `1.2.2` and after that we had issues with our graphs not updating or not being available.

System/Software version:

- OS: Debian 10
- cacti: 1.2.2+ds1-2+deb10u5
- cacti-spine: 1.2.2-1
- PHP version: 7.3

The poller runs via crontab every 5 minutes:
```
*/5 * * * * www-data php /usr/share/cacti/site/poller.php 2>&1 >/dev/null
```

Multilple SNMP timeout detected in the log file:
```
2023/03/13 15:41:11 - SPINE: Poller[1] Device[359] HT[1] DS[7493] WARNING: SNMP timeout detected [500 ms], ignoring host '***REMOVED***'
2023/03/13 15:41:11 - SPINE: Poller[1] Device[300] HT[1] DS[6385] WARNING: SNMP timeout detected [500 ms], ignoring host '***REMOVED***'
2023/03/13 15:41:11 - SPINE: Poller[1] Device[331] HT[1] DS[7033] WARNING: SNMP timeout detected [500 ms], ignoring host '***REMOVED***'
```

We are using the data source template` ucd/net `. Most of the graphs are showing no value = `NaN`.

Does anyone have an idea? Thanks in advance.

**Comment by TheWitness** [comment]
This is really for the forums.  Take the topic up there.
