### ISSUE TITLE
Graph print wrong Gprint value

### ISSUE THREAD

**Issue by pautiina** [Cacti/cacti#527]
![cacti_85 1](https://cloud.githubusercontent.com/assets/11805503/24768476/55c0c650-1b0b-11e7-889b-1b8ae7e7a0c1.png)
![37](https://cloud.githubusercontent.com/assets/11805503/24768529/83c5b1e6-1b0b-11e7-8d34-9d6b7cc80757.png)
Graph Data
```
"Title:","LOCALHOST - Traffic - ix0/1"
"Vertical Label:","bits per second"
"Start Date:","2017-03-30 22:15:00"
"End Date:","2017-03-30 22:30:00"
"Step:","900"
"Total Rows:","1"
"Graph ID:","85"
"Host ID:","1"
""
"Date","col10-cdefa","Inbound","col12-cdeff","Outbound"
"2017-03-30 22:30:00","8.5999170788e+08","6.1562716980e+08","2.0804311243e+08","5.0456973116e+07"

```

**Comment by cigamit** [comment]
This is a behavioral issue with the current LEGEND type.  If you simply change the Graph Item from GPRINT to GPRINTMAX, and choose the MAXIMUM consolidation function, you will get the correct value.  I hope that is clear.

**Comment by mhoran** [comment]
@cigamit is there any way this could be updated in the default graph templates? I finally stumbled across this issue after scratching my head all night trying to figure out the discrepancy.

I'd regenerated a bunch of graphs from a very, very old Cacti install, and discovered the new max lines, which uncovered the mismatched GPRINT for Maximum on most of my graphs.

(On a side note, I couldn't figure out where the defaults are stored to make sure I hadn't misconfigured something myself. Any pointers so I can make sure everything is good would be appreciated.)
