### ISSUE TITLE
Host parameter missing Fault message after trying to add a host

### ISSUE THREAD

**Issue by PG34414** [Cacti/cacti#5270]
Hi,

while trying to add a new system I've got a fault that system cannot be stored by pressing the save button. Since this moment I get every minute this fault multiple times in protocol:

....
<html><body>

2023-03-14 16:53:02 - CMDPHP ERROR: ApacheStats08 - Host parameter missing, can not continue
--
2023-03-14 16:53:02 - CMDPHP ERROR: ApacheStats08 - Host parameter missing, can not continue
2023-03-14 16:53:02 - CMDPHP ERROR: ApacheStats08 - Host parameter missing, can not continue

</body>
</html>
....

Using Cacti 1.2.24 with Plugins Monitor 2.5; Intropage 4.0.2; Thold 1.5.2. 

Adding systems the days before doesn't make any problems. Now I cannot add systems anymore. Any idea?

**Comment by netniV** [comment]
This suggests that the host parameter has not been passed to the command.  Check the poller output view and see what command is being issued against that host for the ss_apache_stats.php script

**Comment by PG34414** [comment]
Where to find the poller output view? This is not the view of cacti.log in protocols?



> This suggests that the host parameter has not been passed to the command.  Check the poller output view and see what command is being issued against that host for the ss_apache_stats.php script
> 
>

**Comment by PG34414** [comment]
There I have this messages 

![image](https://user-images.githubusercontent.com/127875192/225234253-b1a9b2fd-19f7-4947-8dc7-6b8ee4201432.jpeg)

Do I need to delete these data sources because they are empty / wrong?

**Comment by TheWitness** [comment]
How did you create the Graphs?  It looks like they are not associated with any host.  You need to point them at a host.  This is really not a Cacti issue.

**Comment by TheWitness** [comment]
I'm going to close this, but feel free to comment additionally.

**Comment by PG34414** [comment]
But this is my problem:

In management in go to system and there the + symbol to add new system. 
I fill in everything and when I press save at to lower right end of the page there comes up a message that the system cannot be stored. 

The system is not shown in the systems list but the log does make these faults because it seems that the graphs are added without adding the host. 

I cannot add new systems anymore just in the moment I activate the Monitor plugin I have found out. I think there is a problem. 

How to solve? And how to get rid of this faults in the log? 



> How did you create the Graphs?  It looks like they are not associated with any host.  You need to point them at a host.  This is really not a Cacti issue.

**Comment by TheWitness** [comment]
Make a screen2gif of how you did it.

**Comment by PG34414** [comment]
Here I add new system. Entering description, IP address and so on. 

![image](https://user-images.githubusercontent.com/127875192/226583664-f6733a8c-3a9e-4575-82e6-e70272d28fdc.png)

At end of page I click Erzeugen to save to system. 

![image](https://user-images.githubusercontent.com/127875192/226583757-8510c681-e4c6-4a79-a3ff-d85d78142189.png)

Then I get this fault

![image](https://user-images.githubusercontent.com/127875192/226583811-377fce57-72fc-4a7d-a0c8-ae476cffc382.png)

After this in protocol I get these fault 

![image](https://user-images.githubusercontent.com/127875192/226583880-85876594-c2ff-4ad2-81e0-8f8e14cb639a.jpeg)

This aminos happens when Monitor plug-in is installed.

**Comment by TheWitness** [comment]
```sql
ALTER TABLE host MODIFY COLUMN monitor NOT NULL default 'on';
```

This should be the default.  You might want to check before you run that command.

```sql
SHOW CREATE TABLE host;
```

**Comment by TheWitness** [comment]
Is the monitor plugin installed BTW?
