### ISSUE TITLE
Cacti 1.2.24 Issue unable to create Graph

### ISSUE THREAD

**Issue by Rikii16** [Cacti/cacti#5271]
Hello Team,

We upgraded Cacti from 1.2.9 to 1.2.24 but we have an issue when we are creating a new graph, this is the logs from Deveops console and clog.
When we try to create a graph does'nt create aynthing

Do you have any idea to fix this?

## Screenshots

![cacti error](https://user-images.githubusercontent.com/113200412/225087005-1f7508dc-2329-498f-ab16-b31557743a5f.PNG)

CLOG
CMDPHP PHP ERROR WARNING Backtrace: (/graphs_new.php[42]:form_save(), /graphs_new.php[164]:html_graph_new_graphs(), /lib/html_graph.php[465]:host_new_graphs_save(), /graphs_new.php[269]:CactiErrorHandler())

- OS: Centos 7

- BrowserChrome, Edge

- Version 22

PHP version 5.4.16php-devel

Best,

**Comment by netniV** [comment]
You've given the backtrace but not the message, normally we have the opposite problem 👍

**Comment by TheWitness** [comment]
No feedback.
