### ISSUE TITLE
How soon can I update version 1.3.0?

### ISSUE THREAD

**Issue by aliuzzz** [Cacti/cacti#5274]
I want to upgrade my current version 1.2.4 directly to the future version 1.3

**Comment by TheWitness** [comment]
Well, there are a number of issues and it's not fully QA'd right now.  If you go to that release, expect some issues.  But mostly it works.  We will let the community know when it's ready for Alpha testing.  We had a good run in December when we all had a week to contribute.  We are all back to our day jobs now.

We still have a few 1.2.25 bugs to backport, then it'll be off to 1.3.0.

**Comment by aliuzzz** [comment]
Okay, I see. Cheer up for you and look forward to 1.3.0
