### ISSUE TITLE
And yes gexport is running perfectly fine:

### ISSUE THREAD

**Issue by WirthmU** [Cacti/cacti#5284]
And yes gexport is running perfectly fine:

![image](https://user-images.githubusercontent.com/27740335/226369353-2bb6ee34-d204-4df8-82ba-3f1554361b45.png)

_Originally posted by @WirthmU in https://github.com/Cacti/cacti/issues/5256#issuecomment-1476328481_

**Comment by WirthmU** [comment]
Is there a solution to this?

**Comment by TheWitness** [comment]
I updated the other ticket.  Let me know if that works.

**Comment by WirthmU** [comment]
Its working - thank you!

**Comment by TheWitness** [comment]
Cool great!
