### ISSUE TITLE
Gradient Support hides low data graph

### ISSUE THREAD

**Issue by ISekan** [Cacti/cacti#5285]
cacti 1.2.24
The graph with less data is hidden by "Enable Gradient Support"
![image](https://user-images.githubusercontent.com/17400240/228797216-be5b7ddd-ca0e-4c2a-973d-84c3e85770fd.png)
![image](https://user-images.githubusercontent.com/17400240/228797470-5c4c18c1-a0ea-475b-8d1f-60a9b8f406d5.png)

**Comment by TheWitness** [comment]
This is a known issue.  @thurban has initiated a conversation with Tobi Oetiker to see if there are any other options.  The Gradient support introduced into Cacti has this limitation.  It's a known issue, and our solution may be to have a per graph/template setting to enable disable this until we can get better support in RRDtool itself.

So, again, this is a known issue and a duplicate ticket.  Look to this ticket for further updates.

https://github.com/Cacti/cacti/issues/5212

**Comment by ISekan** [comment]
I see, thnx TheWitness
