### ISSUE TITLE
Can Cacti be deployed through Docker？

### ISSUE THREAD

**Issue by aliuzzz** [Cacti/cacti#5288]
Or an official version of docker-compose.yml is released, and now there are unofficial docker images, but they cannot be updated with official updates

**Comment by thurban** [comment]
Did you check out this docker ( or forks) https://github.com/scline/docker-cacti

It includes an upgrade feature. ( https://github.com/scline/docker-cacti#updating-cacti )

Other then that, there's no official docker image available.

**Comment by TheWitness** [comment]
Going to close this as it's more of a question.

**Comment by TheWitness** [comment]
Thomas, I imagine if you want to start hosting a container that is officially supported by us, you should open a separate feature enhancement.
