### ISSUE TITLE
Is being graphed  also can  be selected

### ISSUE THREAD

**Issue by horizonlin** [Cacti/cacti#529]
Is being graphed  also can  be selected  ,ver 1.1.2

![Uploading 20170407102804.png…]()

**Comment by horizonlin** [comment]
![20170407102804](https://cloud.githubusercontent.com/assets/26472990/24783232/975d2c9e-1b7d-11e7-99ba-58108dba71b1.gif)

**Comment by cigamit** [comment]
Resolved, thanks.
