### ISSUE TITLE
When importing packages, SQL errors may be generated

### ISSUE THREAD

**Issue by jdcoats** [Cacti/cacti#5291]
```
2023/04/04 14:59:08 - CMDPHP SQL Backtrace: (/package_import.php[41]:form_save(), /package_import.php[188]:import_package(), /lib/import.php[587]:import_xml_data(), /lib/import.php[235]:xml_to_data_template(), /lib/import.php[1179]:db_execute_prepared())
2023/04/04 14:59:08 - CMDPHP ERROR: A DB Exec Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'data_template_rrd AS dtr ON gti.task_item_id = dtr.id INNER JOIN data_input_f...' at line 1
```

**Comment by jdcoats** [comment]
Yes, saw the same thing running the upgrade to 1.2.25 yesterday also. Should have mentioned that today

**Comment by jdcoats** [comment]
I will update to develop if you have time to follow through with me to stabilization :)

**Comment by TheWitness** [comment]
Not yet Dan.  There is some heavy lifting yet to do. If you want to do a dev setup, that fine.

**Comment by jdcoats** [comment]
Thought so, it would be some work here also as every device has an ACL allowing snmp query so everything would have to be touched to allow that and 2x query’s every minute would be excessive also

**Comment by TheWitness** [comment]
This is resolved now.

**Comment by TheWitness** [comment]
Fixed here.
