### ISSUE TITLE
phpinfo() and get data of cacti

### ISSUE THREAD

**Issue by gpahlevanzadeh** [Cacti/cacti#5297]
I think it's very needed to debug or get data a Tab beside Log Tab, it generate all of configuration data for users and developers.

**Comment by TheWitness** [comment]
Understood.  Some of the PHP info is present, but other bits have been stripped out for various reasons.

**Comment by netniV** [comment]
If you need phpinfo(), write a quick PHP page to output that and then browse to it.  

```
<?php
phpinfo()
```

Job done.  The info inside Cacti is more for technical reference and we do not need everything nor would want certain information out there either.
