### ISSUE TITLE
Error when try use VDEF in any graph template item.

### ISSUE THREAD

**Issue by ObGoN** [Cacti/cacti#530]
Cacti version 1.1.2, used VDEF - Total: Current Data Source in GPRINT.

2017-04-07 13:41:45 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4333 cacti_debug_backtrace)
2017-04-07 13:41:45 - ERROR PHP ERROR: Call to undefined function get_vdef() in file: /var/www/cacti/lib/rrd.php on line: 1350

**Comment by cigamit** [comment]
Resolved, thanks for reporting.

**Comment by ObGoN** [comment]
Fixed, but now new error (RRDtool 1.5.5):

RRDTool Command:

/usr/bin/rrdtool graph - \
--imgformat=PNG \
--start='-180000' \
--end='-300' \
--pango-markup  \
--title='SBC-1 - Realm REGISTRAR - Sessions' \
--slope-mode \
--base=1000 \
--height=150 \
--width=600 \
--alt-autoscale-max \
--lower-limit='0' \
--border 1 --slope-mode \
DEF:a='/var/www/cacti_test/rra/sbc-1_asi_35.rrd':'ASI':MAX \
DEF:b='/var/www/cacti_test/rra/sbc-1_asi_35.rrd':'NAI':AVERAGE \
DEF:c='/var/www/cacti_test/rra/sbc-1_asi_35.rrd':'ASI':AVERAGE \
DEF:d='/var/www/cacti_test/rra/sbc-1_asi_35.rrd':'ASO':MAX \
DEF:e='/var/www/cacti_test/rra/sbc-1_asi_35.rrd':'NAO':AVERAGE \
DEF:f='/var/www/cacti_test/rra/sbc-1_asi_35.rrd':'ASO':AVERAGE \
DEF:g='/var/www/cacti_test/rra/sbc-1_asi_35.rrd':'Status':AVERAGE \
VDEF:vdefba='e,TOTAL' \
CDEF:cdefbd='g,1,LE,1,0,IF,g,5,GE,1,0,IF,+' \
CDEF:cdefbe='g,4,EQ,1,0,IF' \
LINE1:a#00CF00FF:''  \
AREA:b#FF0000FF:'':STACK \
AREA:c#00CF007F:'Inbound '  \
GPRINT:c:LAST:'Current\:%8.0lf'  \
GPRINT:b:AVERAGE:'Drop\:%8.0lf'  \
GPRINT:c:MAX:'Maximum\:%8.0lf\n'  \
LINE1:d#002A97FF:''  \
AREA:e#FF0000FF:'':STACK \
AREA:f#002A977F:'Outbound'  \
GPRINT:f:LAST:'Current\:%8.0lf'  \
GPRINT:vdefba:AVERAGE:'Drop\:%8.0lf'  \
GPRINT:f:MAX:'Maximum\:%8.0lf\n'  \
TEXTALIGN:center \
TICK:cdefbd#FF00007F:1.0:'  Out Of Service' \
TICK:cdefbe#FFFF007F:1.0:'  Constraint\n'

RRDTool Says:

ERROR: Unused Arguments "Drop:%8.0lf" in command : GPRINT:vdefba:AVERAGE:Drop\:%8.0lf

**Comment by cigamit** [comment]
Looks like in RRDtool 1.5 he dropped the consolidation function, which makes sense.

**Comment by cigamit** [comment]
Just updated lib/rrd.php.  Try again.

**Comment by ObGoN** [comment]
Now works.
