### ISSUE TITLE
[1.3 QA] Function get_daysfromtime() truncates result through invalid use of (int) cast

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#5301]
# Describe the bug

When applying string typing to lib/functions.php the return value of get_daysfromtime() was improperly cast as an (int) when it's a string.

**Comment by netniV** [comment]
This fix is wrong, for typing purposes we should be returning a number, not a string (trim)

**Comment by TheWitness** [comment]
Review the function, it prints a string.  For example "10d:6h:22m:12s".

**Comment by netniV** [comment]
Oh my bad then.  This is what I get for quickly glancing.
