### ISSUE TITLE
problems with the button action

### ISSUE THREAD

**Issue by nani81** [Cacti/cacti#5306]
I have several problems since I upgraded from cacti 1.2.19 to 1.2.24.
When I want to create a new chart it does nothing.
When I want to delete a chart it doesn't do anything either.
When I want to disable a data source it doesn't do anything either.
These examples that I pass.
I add videos so you can see that the application says it does what I ask it to do, but in the end it doesn't do it.
Best regards

https://user-images.githubusercontent.com/51642177/232698660-7a2d40a4-2413-49d7-a819-4e9288a0800a.mp4
https://user-images.githubusercontent.com/51642177/232698720-176e058f-6fdb-4932-b8e4-d63f8f749521.mp4
https://user-images.githubusercontent.com/51642177/232698771-b670dfdd-ead7-4a05-b341-e45c59923201.mp4

**Comment by TheWitness** [comment]
Can you bring up the browsers debug window, go to it's console and look for JS errors?

What browser and version are you using?  BTW, IE is no longer supported, any version.

**Comment by TheWitness** [comment]
Also, show if there are errors in your cacti log.

**Comment by TheWitness** [comment]
You can do one of two things:

1) upgrade PHP to 7.4
2) grab the latest 1.2.x branch.

REMI repos are an excellent source of PHP.

**Comment by nani81** [comment]
Good afternoon,

the release I installed is the one on the cacti/github website v1.2.24

From what you tell me about this, is it better to download what is as v1.2.x than to download the full release package, which is supposed to be the stable one as it is the one published as such on the application's website?

Then one of the problems is that the source code on the web is not correct.

[(https://github.com/Cacti/cacti/releases/tag/release%2F1.2.24)]

What version is v1.2.x ? a development version ? can you explain a bit more, please ? I would not like to have applications where it is still under development.

Thanks

**Comment by TheWitness** [comment]
git clone -b 1.2.x https://github.com/cacti/cacti.git

That's 1.2.25 which addresses the issue.  I would prefer you upgrade PHP.  What RHEL version are you running?

**Comment by nani81** [comment]
Good morning,
the php version I have is: php.x86_64 5.4.16-48.el7
About the cacti version, is version v1.2.25 a stable version? or is it still under development?
Thanks

**Comment by TheWitness** [comment]
You should seriously consider upgrading to 8.2+.  The 1.2.x branch is now considered long term support.  Aka No new features. 

Using the REMI repos is the easiest way to be on an old RHEL platform and still run modern PHP.
