### ISSUE TITLE
Weathermaps not seen in lower environment

### ISSUE THREAD

**Issue by aryaaneesh5** [Cacti/cacti#5307]
In our lower environment(1.2.18),We have primary servers and secondary servers.

For the Primary servers, main poller and 1 remote poller is running and 2 remote pollers are in heart beat. We have weathermap plugin installed here. but weathermaps are not seen. We see the below error in logs. Weathermap related logs are not there.

2023-04-22 20:10:23 - CMDPHP PHP ERROR NOTICE Backtrace: (/cli/poller_replicate.php[110]:replicate_out(), /lib/poller.php[1296]:poller_connect_to_remote(), /lib/poller.php[1261]:CactiErrorHandler())

2023-04-22 20:10:23 - ERROR PHP NOTICE: Undefined index: dbretries in file: /opt/cacti/lib/poller.php on line: 1261

For secondary servers, main poller and 3 remote pollers are running. weather maps are not seen. Logs are not showing any errors.

 Weather map plugin status is mentioned as error in plugins tab.

version - 0.98a

Could you please suggest us how can enable weathermap  in secondary/primary.

**Comment by TheWitness** [comment]
We did a fairly significant update to WeatherMap for Cacti 1.2.23 and above.  If I were you, I would make the first focus getting to Cacti 1.2.24.  Then install our version of WeatherMap.  Talked note to closely follow the README.md as we will attempt to move images from their current locations.

The easiest way to upgrade these days from my perspective is to upgrade the primary server and then let it do a full sync to the remotes.  I often use the upgrade_datsbase.php script to update the database.

It sounds like your poller table is missing a column too.  You can use the --forcever from any prior version.

So, for example, this should work for you:

```sh
php -q upgrade_database.php --forcever=1.1.38
```

**Comment by TheWitness** [comment]
Remi repos can be found here if your PHP version is below 7.4.

https://rpms.remirepo.net/
