### ISSUE TITLE
Unable to obtain data source

### ISSUE THREAD

**Issue by aliuzzz** [Cacti/cacti#5308]
cacti 1.2.24
centos7.9
when i input /usr/bin/php /var/www/html/cacti/poller.php --force
it only return 2023-04-23 09:06:08 - SYSTEM STATS: Time:1.2208 Method:spine Processes:1 Threads:1 Hosts:3 HostsPerProcess:3 DataSources:0 RRDsProcessed:0
but i can get snmp data，and i use spine

**Comment by bmfmancini** [comment]
In console >>utilities >> system utilities
Click on view poller cache this will show what the poller is polling

**Comment by TheWitness** [comment]
What version of PHP?  If 5.x, then upgrade to 8.2 using the REMI PHP repos here: https://rpms.remirepo.net/
