### ISSUE TITLE
[1.3 QA] Cacti Log Periodically Getting Errors associated with tailing log file

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#5309]
# Describe the bug

Periodically Cacti is getting the following errors.  This did not occur in prior versions.

![image](https://user-images.githubusercontent.com/1439914/233847004-1f100172-91b8-4b70-bbaf-6b81a05abb6c.png)

## Expected behavior

Less Errors

**Comment by TheWitness** [comment]
@netniV, can you please review the commit?

**Comment by netniV** [comment]
The code is wrong. It's going to skip lines and read the next st the same time as incrementing display line number

**Comment by TheWitness** [comment]
I'm not sure how it threw that error though.  Must be timing related.
