### ISSUE TITLE
Bugs in graph template item - TICK

### ISSUE THREAD

**Issue by ObGoN** [Cacti/cacti#531]
1. Get RRDTool pharse error when use TICK in graph template because can't define fraction (field "Value" not visible). Fix for graph_templates_items.php:
case '30': // TICK
$('#row_consolidation_function_id').**hide**();
$('#row_value').**show**();
2. Wrong "data source", "cf type" and "alpha" fields in Graph Template Items table for TICK and TEXTALIGN items.
Item:
![default](https://cloud.githubusercontent.com/assets/25996128/24791950/ea5f22b0-1b9d-11e7-8048-9d7e33a29249.png)
Table (items 13 - 15 fields wrong):
![default](https://cloud.githubusercontent.com/assets/25996128/24792320/51d3899e-1b9f-11e7-9933-33b8b455d6f8.png)
Move item 11 down:
![default](https://cloud.githubusercontent.com/assets/25996128/24792433/c1374384-1b9f-11e7-8281-76add670feb1.png)
3. Incorrect formatting TICK "Text Format" field in render (need 2 space before text - RRDTool?):
![default](https://cloud.githubusercontent.com/assets/25996128/24792617/9932b8a4-1ba0-11e7-861b-51ae2bcf368f.png)

**Comment by cigamit** [comment]
Thanks for catching.  Please test the commit that was just performed and report back.

**Comment by ObGoN** [comment]
It seems that everything functions as expected:
![default](https://cloud.githubusercontent.com/assets/25996128/24844553/4ef6640a-1dcd-11e7-9328-d8c3cbdb0420.png)

**Comment by cigamit** [comment]
Great thanks for confirming.
