### ISSUE TITLE
Console > Management > Graphs Not change named of graphs

### ISSUE THREAD

**Issue by sebas4944v2** [Cacti/cacti#5310]
I have version 1.2.24 installed, from the debian repositories. I've had it installed for years, I update it as the debian repositories update.

I recently realized that if I go to Console > Management > Graphs and select a graph, the option to rename it does not appear. This is a bug in version 1.2.24 ??, I tried with different users just in case and with different Themes, but with all the same.
Let me clarify, everything works perfectly, but it won't let me change the name of the graphics...

![Captura de pantalla de 2023-04-22 20-38-08](https://user-images.githubusercontent.com/131607216/233851234-155a662b-1a4f-4b00-be47-de2e3a728d93.png)

**Comment by TheWitness** [comment]
Please confirm your PHP version?

**Comment by sebas4944v2** [comment]
php -v
PHP 8.2.4 (cli) (built: Mar 16 2023 14:24:40) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.4, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.4, Copyright (c), by Zend Technologies

**Comment by sebas4944v2** [comment]
Dear, I tell you that apart from using php8.2 I also tried the php7.4
version, but the problem continues...

Reading a forum I found that this problem has been dragging on since cacti
version 1.23...

In cacti version 1.22 this worked fine.

In fact I have a server running cacti 1.22 and everything is perfect!

**Comment by TheWitness** [comment]
Edit the Graph Template associated with the Graph, check the Checkbox to the left of the Graph Title.  Then, the graph name can be edited.  However, something is strange with your Graph.  You appear to have only two datasources, but it shows as 4.  Can you tell me how you made this graph?

**Comment by sebas4944v2** [comment]
Dear, first of all thank you for your help.
That graphic is the last one he created, and it was made with only 4 colors.
Now reviewing the associated Graph Template, I see that everything is
weird. I actually fixed the title as you indicated, that must have been
changed in some update!....
Now I am going to fix it by hand with the 4 colors! only 2 colors!
[image: image.png]

**Comment by TheWitness** [comment]
Glad you are getting things fixed up.
