### ISSUE TITLE
Allow for searching in settings/menu

### ISSUE THREAD

**Issue by xmacan** [Cacti/cacti#5316]
I like search in settings like Firefox or chrome. One search field which searching in all settings. Our settings are growing, it could be useful. 

Maybe extend it - add search box under main menu and searching more than setting, for example users, graphs, ...

**Comment by netniV** [comment]
I like this idea.

**Comment by TheWitness** [comment]
I guess we could do this with a callback and a filter to hide non-matching tabs/rows in a settings javascript function controlled by an array of tabs/settings to hide.

**Comment by TheWitness** [comment]
Maybe it's better to have a callback that shows matching tabs, settings.  Might be an easier way to handle it.

1) Perform, callback
2) Hide everything
3) Unhide matching columns/tabs.

**Comment by TheWitness** [comment]
![image](https://github.com/Cacti/cacti/assets/1439914/a660bc44-e5a1-434a-a97f-b3188022b958)

**Comment by netniV** [comment]
You would want to keep the previous header for an item though to ensure the header of it was present.  Also, we have to be careful of those options which are co-dependant.

**Comment by TheWitness** [comment]
@xmacan, give the latest 1.2.x branch a spin.  Let me know if that works well.

**Comment by TheWitness** [comment]
Visually, this is how it looks.

![SearchingFromSettings](https://github.com/Cacti/cacti/assets/1439914/303341c7-0ef3-4303-ad2e-6c5f0a2240d5)

**Comment by xmacan** [comment]
> @xmacan, give the latest 1.2.x branch a spin. Let me know if that works well.

Cannot test, @netniV reverted it. 

It is new feature, it could be in 1.3.0 not in 1.2.x

**Comment by netniV** [comment]
Correct.  @TheWitness still needs to reapply https://github.com/Cacti/cacti/commit/d4a1eeaff6857067387300b4515b5ef1006e4320

**Comment by jdcoats** [comment]
why revert this? looks exciting :)

**Comment by xmacan** [comment]
We decided that version 1.2.x will be something like LTS (long time support). There will we only fix issues but not add newfeatures. New things wil be only in 1.3.x

**Comment by TheWitness** [comment]
This is an accident, but I have it 're-fixed' now.
