### ISSUE TITLE
SECURITY: Multiple minor stored XSS vulnerabilities in Cacti 1.2.24

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#5318]
# Describe the bug

Though Cacti has automatic XSS protection mechanism's, security researchers have found a number of XSS vulnerabilities that should be corrected.  Thanks to @VissaMoutafis at GitHub

## Expected behavior

No security issues regardless of XSS protections.

**Comment by paulgevers** [comment]
@TheWitness thanks for maintaining cacti and keeping it safe. For Debian I'm helping the security team to prepare fixes for our stable and old stable release (based on cacti versions 1.2.24 and 1.2.16), but I'm having a hard time matching commits between 1.2.24 and 1.2.25 that fix security issues and those that fix other issues. I'm wondering (maybe just for the future, but now would be awesome too), if you could cross reference commits in the security advisories. That would ease the work of distribution maintainers a lot.

**Comment by TheWitness** [comment]
My apologies Paul, let me put together a care package for you on the security side.  Will take a bit, but I'll try to prioritize.

**Comment by paulgevers** [comment]
@TheWitness if you're meaning to create new versions of cacti on your side, that's not exactly what I'm asking and I also think that doesn't scale for you. Distributions have to do their own work. I'm "just" asking to help us (all distribution) to identify the relevant security commits (at least those with a CVE/security advice) in each cacti release. More is too much to ask in my opinion, unless you want to go for a route of longer term support cacti releases (which again, I'm not asking).

**Comment by TheWitness** [comment]
That was the plan.  However I had a hardware failure in my lab.  So, I wrote off the weekend and spent time with the boss (wife).

**Comment by netniV** [comment]
@paulgevers I think in the future, we will try to make use of the private branch tracking features of individual advisories so it's more easily associated when merged.  The XSS side did have a number that were cross advisories which should really have been merged into a single advisory in hindsight, but the report had created them separately for each instance it occurred.

Previously, before GitHub's security advisories started taking off (which people seem to be using now), it was just tracked as a standard issue like this one.  Going forward, I would imagine most will be handled via advisories (even if we have to create those advisories ourselves).

**Comment by paulgevers** [comment]
> @paulgevers I think in the future, we will try to make use of the private branch tracking features of individual advisories so it's more easily associated when merged.

I think that would cover what I'm asking for indeed.
