### ISSUE TITLE
Missing main menu on some views

### ISSUE THREAD

**Issue by reboot1983** [Cacti/cacti#532]
When I open the Cacti (1.1.2) settings (/cacti/settings.php) on my Macbook Pro with MacOS 10.12.4 - Chrome 57.0.2987.133 (64-bit)) I get an odd layout. Same thing happens on Windows 10 with the exact same browser. The menu is missing. It's not an cache thing, cleared that one out already. 

Also; for as far as I'm able to check, this seems to be the only browser with the issue. 
Same laptop with Safari is ok, iPad with default Safari is ok, Windows 10 with IE11 is ok too.

When I change tabs (path, device default, etc.) the menu appears again, but when I return back to general tab, the menu is gone again. 

Also: If I change something and hit save the message 'Save successful.' won't go away.
Also: This 'missing main menu issue' also occures for de data_input_methods (/cacti/data_input.php)

I am unable to create a fix for this.

![schermafbeelding 2017-04-07 om 10 41 04](https://cloud.githubusercontent.com/assets/20405704/24792947/539d01f2-1b80-11e7-8bcf-e749cf4dfbbb.png)
![schermafbeelding 2017-04-07 om 11 34 24](https://cloud.githubusercontent.com/assets/20405704/24794560/5f99f7a2-1b86-11e7-9ffe-853e27d40630.png)
![schermafbeelding 2017-04-07 om 11 34 50](https://cloud.githubusercontent.com/assets/20405704/24794559/5f9989b6-1b86-11e7-8028-274ea553c1e1.png)

**Comment by cigamit** [comment]
This likely has to do with the content width.  Edit include/themes/classic/main.js and change line 11, to be something like:

contentWidth = totalWidth - treeWidth - 25;  (instead of 23, then reload, clear cache, etc.

**Comment by reboot1983** [comment]
No matter what I change here, Nothing changes.
Tried to do some debugging and found out the following (see screenshot (1st & 2nd image), right lower corner; height not filled in; 145x0). If I change the 0 (zero) to something > 0, the menu appears. The container just has 0 height. If I inspect the container (3rd image); it has a height of 5px (only the padding: 5px).

![image](https://cloud.githubusercontent.com/assets/20405704/24826192/5c4cbf4e-1c30-11e7-887c-46ba48f92400.png)

![image](https://cloud.githubusercontent.com/assets/20405704/24826198/798fea36-1c30-11e7-915f-62d76bb678b4.png)

![image](https://cloud.githubusercontent.com/assets/20405704/24826258/ca9809c6-1c31-11e7-9528-c8a329b24ef4.png)

**Comment by nitzan-tz** [comment]
To add to this issue 
In chrome it always stayed in the classic theme no meter which one I am selecting 
In Firefox it works ok

Nitzan

**Comment by reboot1983** [comment]
Did you try logout and login again?
Settings will be saved, but only applied when you re-login. This bug should be fixed in cacti 1.1.3

**Comment by cigamit** [comment]
The windows scroll height does not seem to be reliable across browsers.  Resolved for now.
