### ISSUE TITLE
Add Device types directly to the tree

### ISSUE THREAD

**Issue by browniebraun** [Cacti/cacti#5327]
# Feature Request

## Provide the option to add device types (based on device templates) directly to the tree.

From my point of view it would also be nice to have the option to create a branch like shown below.
This is pretty similar to adding sites to a branch, which are already offering device types on their next layer. My idea is to have the same for a global scope, means everything Cacti monitors.

```

|__ Device Types
      |__ cEdges
      |       |__ abcrt001
      |       |__ abcrt002
      |       |__ ....
      |__ vEdges
      |__ Cisco Routers (IOS)
      |__ F5
```

....

**Comment by netniV** [comment]
How would you imagine that works? It includes all device types or just those that didn't make it into the others?  If you have a lot of devices on the system, that could lead to an unresponsive tree.

**Comment by TheWitness** [comment]
Likely not very well

**Comment by netniV** [comment]
In that case, going to close this one for now.  If you can think of a better way long term, we can revisit it.

**Comment by TheWitness** [comment]
Better to do the same thing either for a site, a tag or filter.
