### ISSUE TITLE
Search through Data Query fields when searching for Graphs in Tree

### ISSUE THREAD

**Issue by gpahlevanzadeh** [Cacti/cacti#5328]
It's very nice if when I create tree, I can search in data source along with graph name.

**Comment by netniV** [comment]
Please provide more description as to how you want this search to work.

**Comment by gpahlevanzadeh** [comment]
Suppose I don't want a graph name, But I know vlan number, or section of data source. I need to search in section of data source or vlan number.

**Comment by TheWitness** [comment]
So, basically, you have that in the data source name but not the graph name.

**Comment by TheWitness** [comment]
I did one better.  See the attached.  Committing shortly.

![image](https://github.com/user-attachments/assets/6dfca27d-0461-4225-83fa-bf64fad019b1)
