### ISSUE TITLE
Cacti polls the wrong host - database is inconsistant and a poller cache rebuild does not help

### ISSUE THREAD

**Issue by eriksejr** [Cacti/cacti#5332]
First off let me say I would have posted this on the forum first but I cannot log in nor create a new account because emails sent from the forum are not arriving. I have tried two different email addresses (one hotmail, one gmail) and I could not get a password reset email on the hotmail nor an activation email on the gmail, so I am posting this here.

# Describe the bug

The hostname of an existing device is changed in the GUI but cacti continues to poll the previous hostname. Rebuilding the poller cache for this host ID does not resolve the problem.

The problem is most visible if you query the database if queried directly. Note that I have changed the hostnames here for privacy reasons. A packet capture on the server will show cacti querying the wrong host for a number of data sources:

```
cactiuser@localhost [cacti]> select hostname from host where id=1046;
+-------------------------------+
| hostname                      |
+-------------------------------+
| device01a.host.com |
+-------------------------------+
1 row in set (0.001 sec)
```

```
cactiuser@localhost [cacti]> select hostname, host_id from poller_item where host_id=1046;
+-------------------------------+---------+
| hostname                      | host_id |
+-------------------------------+---------+
| device01b.host.com |    1046 |
| device01b.host.com |    1046 |
| device01b.host.com |    1046 |
| device01b.host.com |    1046 |
| device01b.host.com |    1046 |
| device01b.host.com |    1046 |
| device01b.host.com |    1046 |
| device01b.host.com |    1046 |
| device01b.host.com |    1046 |
| device01b.host.com |    1046 |
| device01b.host.com |    1046 |
| device01b.host.com |    1046 |
| device01b.host.com |    1046 |
| device01b.host.com |    1046 |
+-------------------------------+---------+
14 rows in set (0.001 sec)
```

Try to rebuild poller cache:

```
root@cacti:/usr/local/share/cacti # cli/rebuild_poller_cache.php --host-id=1046
WARNING: Do not interrupt this script.  Rebuilding the Poller Cache can take quite some time
...........
```

Check again:

```
cactiuser@localhost [cacti]> select hostname, host_id from poller_item where host_id=1046;
+-------------------------------+---------+
| hostname                      | host_id |
+-------------------------------+---------+
| device01b.host.com |    1046 |
| device01b.host.com |    1046 |
| device01b.host.com |    1046 |
| device01b.host.com |    1046 |
| device01b.host.com |    1046 |
| device01b.host.com |    1046 |
| device01b.host.com |    1046 |
| device01b.host.com |    1046 |
| device01b.host.com |    1046 |
| device01b.host.com |    1046 |
| device01b.host.com |    1046 |
| device01b.host.com |    1046 |
| device01b.host.com |    1046 |
| device01b.host.com |    1046 |
+-------------------------------+---------+
14 rows in set (0.001 sec)
```

## To Reproduce

I am unsure this is consistently reproducible for other devices but at the moment I can change the hostname of this device in the GUI or hosts table in the database to whatever I please and cacti continues to poll the old device name no matter what I do.

## Expected behavior

I would expect the poller to poll the device shown in the GUI and the hostname present in the hosts table in the database.

## Software involved and versions

Desktop is windows 11, using Firefox 113. Server is FreeBSD 13.1 and DB is MariaDB 10.5.15. Cacti Version is 1.2.24

## Additional context

This device is a redundant pair of devices named "device01a" and "device01b". At times a switch from "A" to "B" or back can happen and cacti does not easily support such redundancy. To handle this a cron job is occasionally run between poller intervals to determine which device is active. If the active device has changed the script run by cron will update the host in the database with the correct device and trigger a poller cache rebuild for this device ONLY. As this is unique to this device it's possible this has somehow triggered this bug.

While I can easily update the poller_item table manually to fix the database I have no idea why this happened and I was wondering if someone can provide some insight? Perhaps the script that does the database update needs to take some additional steps to ensure database consistency.

Thanks

**Comment by eriksejr** [comment]
I'm thinking that in the GUI there's some kind of broken regex or comparison which can under certain circumstances not properly update the hostname. Lets say the hostname is in the format:

abcd-cdef-device01a.host.com

if I change this in the gui to "abcd-cdef-device01b.host.com" and check the data_input_data table in the database for the appropriate data_template_data_id's the value remains unchanged at "abcd-cdef-device01a.host.com"

If I retry this test, but I make a more extreme change in the GUI like changing the hostname to "bob.host.com", the values in the data_input_data table are now updated correctly (they now read bob.host.com). If I then change the hostname to the desired value of "abcd-cdef-device01b.host.com" the fields are again updated correctly.

So there's some code somewhere when you save a device that seems to check if that field has changed, and if it has update it. That code seems buggy and it appears that some changes are not caught as changes. I am still working to find it.

**Comment by bmfmancini** [comment]
That is some strange behaviour 
we did have a bug like that in 1.2.20  I belive but that was fixed 

Is this device on a remote poller or is it a single poller ?

**Comment by bmfmancini** [comment]
There is the change device cli script that you can leverage to do that
which will allow you to change the details and the script will ensure the
dB is consistent

**Comment by eriksejr** [comment]
Fantastic! I'll use that and avoid this whole mess!

**Comment by TheWitness** [comment]
This actually looks like a bug.  @eriksejr, this happens when you save the host from the GUI and change the hostname or the description?

**Comment by TheWitness** [comment]
I'll do some testing, if it's not reproducible, I'll close.
