### ISSUE TITLE
MariaDB clusters will no longer support exclusive locks

### ISSUE THREAD

**Issue by iceking2nd** [Cacti/cacti#5333]
2023/05/19 22:20:39 - CMDPHP ERROR: A DB Cell Failed!, Error: This version of MariaDB doesn't yet support 'GET_LOCK in cluster (WSREP_ON=ON)'
2023/05/19 22:20:39 - CMDPHP SQL Backtrace:  (/graph_json.php[159]:rrdtool_function_graph(), /lib/rrd.php[1307]:boost_graph_cache_check(), /lib/boost.php[387]:boost_process_poller_output(), /lib/boost.php[697]:db_fetch_cell(), /lib/database.php[546]:db_fetch_cell_prepared(), /lib/database.php[568]:db_execute_prepared())

MariaDB version: 10.6.13
Cacti version: 1.2.24

**Comment by TheWitness** [comment]
Yea, I'm aware.  It's really Galera.  There really may not be a need these days.  But I think there is another way.

**Comment by TheWitness** [comment]
As an interim, if you are at >= RRDtool 1.5 and set in the GUI that way, you can remove [GET|SET]_LOCK from the code. Just comment out for now.

**Comment by TheWitness** [comment]
This should be resolved now.

**Comment by TheWitness** [comment]
Looks like MariaDB has reverted the change for now.

![image](https://github.com/Cacti/cacti/assets/1439914/2016690a-1c1f-4d61-b29d-444e3e7c84d4)

and

![image](https://github.com/Cacti/cacti/assets/1439914/46d9963a-14c4-493f-8161-777953da5386)
