### ISSUE TITLE
Error when creating a new chart

### ISSUE THREAD

**Issue by nani81** [Cacti/cacti#5334]
Good morning, I have cacti version v1.2.24 on a redhat 8.6 with php 8.

When I click on create a new chart for a device I get the following screen and I can't continue.
![crear nueva gráfico](https://github.com/Cacti/cacti/assets/51642177/36d0c9f3-ede9-4cdb-99d3-6e288a320dbb)

In the log I get the following message:
![Error gráfica](https://github.com/Cacti/cacti/assets/51642177/b501f1d6-f957-42fb-a34f-3cf2190e5f16)
![warning](https://github.com/Cacti/cacti/assets/51642177/2a363fe6-fa3b-4183-a6e0-44bfe7a4923b)

Thanks

**Comment by TheWitness** [comment]
Did you install from source?

**Comment by nani81** [comment]
yes, of course

**Comment by netniV** [comment]
That error is in the 1.3.x not 1.2.24 as stated above which may be causing some confusion.  However, that constant is defined in global_path.php and should be present.

**Comment by netniV** [comment]
Just for a sanity check:
```
$ grep CACTI_PATH * -R
tests/tools/check_install_code.php:define('CACTI_PATH', str_replace('/tests/tools', '', dirname(__FILE__)));
tests/tools/check_install_code.php:$config = array('base_path' => CACTI_PATH);
tests/tools/check_install_code.php:$install_upgrades_dir = CACTI_PATH . '/install/upgrades';
```
The only mention of CACTI_PATH at all in 1.2.x is in one of the tool scripts so would never apply to what you are seeing.

**Comment by nani81** [comment]
That's right, that file: "graphs_new.php" is from the developer version.
I put it because the version that comes in release v1.2.24 gave me the following error when I wanted to create new graphs for my F5 balancer.
So I tried to test with the development version.
But I keep getting the same errors.
In the end I had to change this file to the one in release v.2.19 with this one it doesn't give me any error and I can create graphs without any problem.
![Error crear grafica F5 - cacti](https://github.com/Cacti/cacti/assets/51642177/79e1dd6a-4b41-4a68-b060-096c62df0577)
![error f5 - cacti](https://github.com/Cacti/cacti/assets/51642177/b31879b7-bd97-49bf-b0ee-fa656274359e)
![Error graphs_new](https://github.com/Cacti/cacti/assets/51642177/ee78ec3d-177e-4631-83a7-9fb4c3198f02)

**Comment by TheWitness** [comment]
That is not a Cacti 1.2.24 version of graphs_new.php still.  I would re-install using something like:

```sh
cd /var/www/html
git clone -b 1.2.x https://github.com/cacti/cacti.git cacti
chown -R apache:apache cacti
```

That's the way you would do it with RHEL anyway.
