### ISSUE TITLE
Fridh GT - systemstats - CPU usage - Linegraph all value = -nan

### ISSUE THREAD

**Issue by PloEric** [Cacti/cacti#5340]
# Describe the bug
when I create a new graph Fridh GT - systemstats - CPU usage - Linegraph all value keep at -nan.
The new graph create a file .rrd on the first polling after the creation, but after at the other polling, it's not modified.

## To Reproduce

1. Go to create a new graph

2. Click on Fridh - ucd/net - SystemStats - CPU Usage Linegraph

3. Scroll down to create

there's no error, the file *.rrd is created, but it's not modified by the polling
## Expected behavior
all the value are : -nan
For the graph new graph Fridh GT - systemstats - I/O - Linegraph, it's OK
For the old graph (create a long time ago on other client) Fridh GT - systemstats - CPU usage - Linegraph, it's OK
## Desktop (please complete the following information)

- OS: [e.g. iOS] debian11

- Browser [e.g. chrome, safari] firefox on ubuntu

- Version [e.g. 22] 1.2.24

**Comment by TheWitness** [comment]
Enable detailed logging on `Console > Configuration > Settings > General` tab, and then you will find there error.  It's likely the device does not support the OID or that you have some issue with SNMP.  This is really not a bug.
