### ISSUE TITLE
Improve detection of downed Devices

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#5356]
# Describe the bug

Availability checks are not quite consistent between Core and Spine.  Make sure that they are.

**Comment by netniV** [comment]
This relates to spine issue https://github.com/Cacti/spine/issues/304 and follows on from https://github.com/Cacti/spine/issues/238

**Comment by netniV** [comment]
This was already ported, the label is pointless.

**Comment by TheWitness** [comment]
Spine issue @netniV

**Comment by netniV** [comment]
Yes I already ported the spine changes I'm sure.
