### ISSUE TITLE
Disabling device in device management overview page doesn't change anything in 1.1.0

### ISSUE THREAD

**Issue by gmuellerfr** [Cacti/cacti#536]
Hello,

if I check mark a device in the device management page and choose as action "Disable" nothing happens.  All I get is an empty page which is not updated. If I click again on devices I see that the status didn't change. I have to go into the device menu and check mark "disable". Then the status is reported as "disabled" in the overview menu.

The same appears, when I try to enable a device. I guess that this doesn't depend on the action, I have requested.

Kind regards
Guenter

**Comment by cigamit** [comment]
Please update to 1.1.2.  This issue can not be reproduced there.

**Comment by gmuellerfr** [comment]
I've verified.
This behaviour has disappeared in version 1.1.2

Thanx for listening
