### ISSUE TITLE
[1.2.25] Boost will not enable

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#5374]
Enabling boost in settings does not show any errors however viewing boost stats shows boost is still disabled 
DB has boost set to ON

MariaDB [cacti]> select * from settings  where name like '%boost%';
+-----------------------------------------+----------------------------------+
| name                                    | value                            |
+-----------------------------------------+----------------------------------+
| boost_last_run_time                     | 1686587106                       |
| boost_max_output_length                 | 1686587827:0                     |
| boost_next_run_time                     | 1686590706                       |
| boost_parallel                          | 1                                |
| boost_png_cache_directory               | /var/www/html/cacti/cache/boost/ |
| boost_png_cache_enable                  |                                  |
| boost_poller_mem_limit                  | 1024                             |
| boost_redirect                          |                                  |
| boost_rrd_update_enable                 | on                               |
| boost_rrd_update_interval               | 60                               |
| boost_rrd_update_max_records            | 1000000                          |
| boost_rrd_update_max_records_per_select | 50000                            |
| boost_rrd_update_max_runtime            | 1200                             |
| boost_rrd_update_string_length          | 2000                             |
| boost_rrd_update_system_enable          | on                               |
| path_boost_log                          |                                  |
+-----------------------------------------+----------------------------------+
16 rows in set (0.003 sec)

![image](https://github.com/Cacti/cacti/assets/13388748/e0371537-453a-4d5f-b577-b43287bdea8d)

**Comment by netniV** [comment]
That suggests that the code isn't working out when the next runtime is supposed to be.
