### ISSUE TITLE
When reload page in browser with graphs created scroll window always return to top

### ISSUE THREAD

**Issue by AntonBelogolovskiy** [Cacti/cacti#5378]
Cacti v. 1.2.25. When reload page in browser with graphs created scroll window always return to top

Scroll window position not saved and with reload page on press `F5` is return to top of window.

Cacti v. 1.2.25 installed on Debian 11 server:

# cat /etc/debian_version
11.7

php -v

# php -v
PHP 7.4.33 (cli) (built: Feb 22 2023 20:07:47) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.33, Copyright (c), by Zend Technologies

# apache2 -v
Server version: Apache/2.4.56 (Debian)
Server built:   2023-04-02T03:06:01

## Desktop (please complete the following information)

- OS: Windows 11 (with latest updates)

- Browser : Firefox, Chrome (latest versions)

**Comment by netniV** [comment]
I believe that is by design. Are you expecting something different or am I thinking of a different process ?

**Comment by TheWitness** [comment]
Push the go or refresh buttons instead.

**Comment by TheWitness** [comment]
Yea, it can.

**Comment by AntonBelogolovskiy** [comment]
> Yea, it can.

can you help me with this?

**Comment by netniV** [comment]
It's a low priority feature for me.  We could make it an option for 1.3, but right now it's not even on the road map.

**Comment by TheWitness** [comment]
Not for 1.2.25, but I'll give it some thought for 1.3.0.

**Comment by TheWitness** [comment]
This is resolved no in the develop branch.
