### ISSUE TITLE
Unable to rename tree folder

### ISSUE THREAD

**Issue by reboot1983** [Cacti/cacti#538]
I'm unable to rename a folder in a tree. If I click the rename option (see image), the "treeitems view" will reload and that's it. Nothing else happens.

![image](https://cloud.githubusercontent.com/assets/20405704/24826303/c92c79f4-1c32-11e7-8ceb-7ad618d712f1.png)

**Comment by cigamit** [comment]
Can you please check the JavaScript console for errors when attempting to do so.  Also, please note your browser and version.  See if you can reproduce this on other browsers.  Lastly, note your Cacti version.  I'm assuming you are working off the development branch.

**Comment by cigamit** [comment]
Okay, I've reproduced.  Maybe it happened when we updated jstree a while ago.

**Comment by cigamit** [comment]
Seems that there must be hover event from another jquery call triggering that is forcing the rename to complete since if you position the tree so that the context menu have the rename right over the branch, you can rename.  Now, to find the callback...

**Comment by cigamit** [comment]
Found it!

**Comment by cigamit** [comment]
Resolved, thanks!
