### ISSUE TITLE
Cacti errors with php 8.0+ browsing devices (and more)

### ISSUE THREAD

**Issue by chrcoluk** [Cacti/cacti#5380]
This was already reported but looks like the previous issue got deleted, I put a lot of effort in typing that out and providing what information I can so apologies if I dont do it again.

I was advised this simply isnt a bug and was more or less a wont fix, but there was an improvement made in the validation checking.

Having now updated to cacti 1.2.23 (which has this validation change).  I tried again using php 8.0/8.1/8.2, of course the issue is still here as wasnt fixed, but there seems to be a bit more logging now.

The steps to hit this bug, is I go to manage devices, and the list loads, select a device.  Then I get a warning from cacti with the following message 

"Sorry, we could not process your last action.

Save Failed due to field input errors (Check red fields)."

There is no red fields.

If I then enable "Log Input Validation Issues" This appears in the cacti log.

```
17/Jun/2023 23:10:15 - CMDPHP REGEX FAILURE Backtrace: (/host.php[25]:include(), /include/auth.php[27]:require_once(), /include/global.php[533]:include_once(), /include/global_form.php[2362]:api_plugin_hook(), /lib/plugins.php[83]:api_plugin_run_plugin_hook(), /lib/plugins.php[225]:monitor_config_form(), /plugins/monitor/setup.php[730]:form_input_validate(), /lib/functions.php[851]:cacti_debug_backtrace())
17/Jun/2023 23:10:15 - CMDPHP Form Validation Failed: Variable 'id' with Value '67' Failed REGEX '0'
17/Jun/2023 23:10:15 - CMDPHP REGEX FAILURE Backtrace: (/host.php[25]:include(), /include/auth.php[27]:require_once(), /include/global.php[533]:include_once(), /include/global_form.php[2362]:api_plugin_hook(), /lib/plugins.php[83]:api_plugin_run_plugin_hook(), /lib/plugins.php[225]:monitor_config_form(), /plugins/monitor/setup.php[730]:form_input_validate(), /lib/functions.php[851]:cacti_debug_backtrace())
17/Jun/2023 23:10:15 - CMDPHP Form Validation Failed: Variable 'id' with Value '67' Failed REGEX '0' 
```

If I use cacti again with php 7.4, the warnings stop and is no errors logged.  On the previous report it was never explained why this only happens on 8.0 and newer.

**Comment by chrcoluk** [comment]
It looks like the monitor plugin is possibly the culprit (I am fairly sure this wasnt logged last time and we was guessing).

**Comment by chrcoluk** [comment]
Confirmed dev version of the monitor plugin fixes this problem, I see that plugin is authored by cacti dev's so I suggest making a new release for it. Will close this report.  Thanks for improving the logging.

**Comment by TheWitness** [comment]
@chrcoluk, okay.  Glad you located it.  To the point on plugin releases.  Totally agree.  We need more help on the team to keep up.  I've written so many over the years, I can not keep up any longer.
