### ISSUE TITLE
Cacti does not show graph

### ISSUE THREAD

**Issue by amirrezawh** [Cacti/cacti#5388]
Hello everyone
I've installed cacti but the graph does not show and the "RRDtool Says: Ok" shows when debug mode is enable for debugging the graph.
I have no idea and there is no error in logs.
cacti version: 1.2.25 

EDIT: Real time graph works fine.

**Comment by bmfmancini** [comment]
We need more info but this looks like something for the forums

What version of cacti?
What OS?

**Comment by amirrezawh** [comment]
Sorry about that,
I'm using Debian 11 and cacti 1.2.25

**Comment by bmfmancini** [comment]
Can you post a screenshot or what your seeing this is Lilley a config issue

**Comment by amirrezawh** [comment]
This is graphs before running real time:
![cacti1](https://github.com/Cacti/cacti/assets/24862892/b37a7049-f77a-415d-8dfc-cd61af8a35f4)
This is graphs after real time:
![cacti2](https://github.com/Cacti/cacti/assets/24862892/e7a5d090-871c-4cac-84ee-82c0eefc2d32)

**Comment by bmfmancini** [comment]
Things to check

Ensure your cron is running
Check the log poller stats
Check permissions of the rrd folder

Please check the forums or the docs repo

**Comment by netniV** [comment]
This will be a permissions issue between the user that runs the poller and the user being used to serve the web pages.

**Comment by netniV** [comment]
Or your poller is not scheduled to run at all

**Comment by amirrezawh** [comment]
I'm running my poller with:
`* * * * * php /var/www/html/cacti/poller.php >> /var/www/html/cacti/poller-error.log 2>&1`
and I just set it with `crontab -u www-data -e` which is for apache.

**Comment by TheWitness** [comment]
And you actually have SNMP access to the device.  I generally guess on permissions:

```sh
chown -R apache:apache /var/www/html/cacti
```

But on Debian/Ubuntu is's www-data I think.

**Comment by TheWitness** [comment]
I'm closing, but you can continue the conversation here or on the forums.
