### ISSUE TITLE
When a new account is created or admin has reset password send password to user

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#5389]
As the title says 

when a new local user is created the admin will have to send the password to the user either verbally or through another way
As with other systems when a password is reset there is a function to send the new password or a link to the account where they will be forced to reset their password and continue to login

**Comment by netniV** [comment]
Sounds like a reasonable feature for 1.3.x

**Comment by TheWitness** [comment]
I'm going to close this one @xmacan is still working on the, but we don't send passwords via email ever
