### ISSUE TITLE
<cacti_path> not applied in poller_items and snmpagent_mibs

### ISSUE THREAD

**Issue by reboot1983** [Cacti/cacti#539]
I'm not sure, but shouldn't `rrd_path` and `arg` contain <cacti_path> instead of /var/www/html/cacti/ ?
Same thing for: `snmpagent_mibs` column `file`

![image](https://cloud.githubusercontent.com/assets/20405704/24826353/8cb473a8-1c34-11e7-91c1-452de77febd7.png)

![image](https://cloud.githubusercontent.com/assets/20405704/24826405/c6913948-1c35-11e7-85ec-2ca0db025409.png)

**Comment by cigamit** [comment]
No, everything is normalized in the poller_x tables to reduce the query load.  We are looking to create a graph rendering cache as well to reduce the query load when rendering graphs on very large systems.  That cache would include all rendering 'rrdtool graph' syntax except --start and --end, and any theme related canvas manipulation, watermark, and appearance of the 'to - from' date ranges.  Should speed things up quite a bit.
