### ISSUE TITLE
Issues with damaged data queries after upgrade from 1.2.11 to 1.2.21

### ISSUE THREAD

**Issue by datutu58888** [Cacti/cacti#5391]
The issue of unsuccessful creation of 95 billing for creating a multi port template

This issue does not exist in version 1.2.11

When creating a graphic based on the multi port 95 billing template, a prompt appears with version 1.2.21

I created the template myself, and there were no issues creating and using it in version 1.2.11

Here are the prompts and screenshots

When I choose to create a multi port 95 template, I am prompted with an error in the index type, index value, and output type ID. In version 1.2.11, if these values are not entered, the creation can still be successful
![20230629180924](https://github.com/Cacti/cacti/assets/138114577/1d943ea6-7cb7-428a-b5b3-2d3fb979486d)

**Comment by TheWitness** [comment]
Upgrade to 1.2.24.  Between 1.2.16 and 1.2.23 there were Data Query regressions introduced.  They are repaired to the extent possible in the upgrade script.

**Comment by TheWitness** [comment]
As mentioned, the upgrade script will fix these to the best of it's ability.  If that does not work, please restore your database from the last good backup, and then upgrade to 1.2.24.
