### ISSUE TITLE
When importing a Template, errors may be recorded

### ISSUE THREAD

**Issue by xmacan** [Cacti/cacti#5392]
Actual 1.2.25
Import templates causes blank screen, log:
2023/06/30 15:15:07 - CMDPHP IMPORT NOTE: Repairing 1 Damaged data_input_fields
2023/06/30 15:15:07 - CMDPHP WARNING: Could not find Cacti default matching hash for unknown system hash "35637c344d84d8aa3a4dc50e4a120b3f" for 1.  No repair performed.
2023/06/30 15:15:18 - CMDPHP IMPORT NOTE: Repairing 2 Damaged data_input_fields
2023/06/30 15:15:18 - CMDPHP WARNING: Could not find Cacti default matching hash for unknown system hash "35637c344d84d8aa3a4dc50e4a120b3f" for 1.  No repair performed.
2023/06/30 15:15:24 - IMPORT parse_xml_hash ERROR wrong hash format for hash: 45
2023/06/30 15:15:24 - ERROR PHP ERROR: Uncaught Error: Unsupported operand types in /usr/local/share/cacti/lib/import.php:252 Stack trace: #0 /usr/local/share/cacti/templates_import.php(117): import_xml_data('<cacti>\t\n\t<hash...', false, 2, false, false, Array) #1 /usr/local/share/cacti/templates_import.php(43): form_save() #2 {main} thrown in file: /usr/local/share/cacti/lib/import.php on line: 252
2023/06/30 15:15:24 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())

I know, it is very old xml.

**Comment by TheWitness** [comment]
@xmacan , can you please upload the XML?

**Comment by xmacan** [comment]
[cacti_graph_template_aruba_-_user_stats.xml.gz](https://github.com/Cacti/cacti/files/11925718/cacti_graph_template_aruba_-_user_stats.xml.gz)

**Comment by TheWitness** [comment]
Okay, nice error generated now.
