### ISSUE TITLE
User log is not updated or supplemented [Cacti Version 1.2.24]

### ISSUE THREAD

**Issue by leonardo0014** [Cacti/cacti#5394]
# Describe the bug

User log is not written or updated when a known user logs in. If he logs in for the first time, it will still be written, but not after that. I use the WEB Basic variant without a mapping table. Each new authenticated user is created using the "Template User" as a template.
Oh yes, there is no logout link in the menu

## To Reproduce

1. Open Cacti and log in with a new User
2. Close Browser and Wait about 2 Minutes (It will then be more visible in the result)
3. Open Cacti and log in with the same User before
4. Check User Log. There is only one entry from the first login

## Expected behavior

Current entries about each user and their login

## Screenshots

n/a

## Desktop

- OS: Windows
- Browser: Chrome or Firefox
- Version: the current stable version

## Additional context

Cacti Version 1.2.4 Running with httpd, php-fpm and a MariaDB 10.6.12
The error occurs with an update installation of version 1.2.20 and also with a fresh installation of 1.2.24
I also checked the audit log of the SQL database and it doesn't even try to write anything to the user_log or I don't see any access.

**Comment by TheWitness** [comment]
I'll check this today.

**Comment by TheWitness** [comment]
Is this basic authentication?  If so, until you close all your browser sessions, the session 'preserved' by the browser, say firefox, and stays persistent.  Until the basic user get's prompted for a user and password again, it is considered the same login session.

Bottom line, close all browsers open and not just close the tab.

**Comment by TheWitness** [comment]
A colleague of mine, wanted me to add a logout for basic auth, which actually makes little sense other than to clear your session actually.  It's something I'll consider doing after the 1.2.25 release in the 1.3/develop branch.

**Comment by TheWitness** [comment]
Going to close this, but I'll still be watching of course.

**Comment by TheWitness** [comment]
Yea, the redirect function in auth_login.php is where the magic happens.  That function does the user log and then opens that page, or redirects to it.

You can insert cacti_log() statements in the file to help you trace this.

**Comment by TheWitness** [comment]
The function is auth_login_redirect(), and it can be found in `lib/auth.php`
