### ISSUE TITLE
Out of memory in graph_view.php

### ISSUE THREAD

**Issue by drees** [Cacti/cacti#5395]
The graphs pageis failing to load. From the web client it seems to show up in a few different ways, from 500 to 503 http error codes to others. In the logs, this shows up every time:

```
[02-Jul-2023 20:12:31 UTC] PHP Fatal error:  Out of memory (allocated 2097152) (tried to allocate 67201425304 bytes) in /usr/share/cacti/lib/html_tree.php on line 740
[02-Jul-2023 20:12:31 UTC] PHP Stack trace:
[02-Jul-2023 20:12:31 UTC] PHP   1. {main}() /usr/share/cacti/graph_view.php:0
[02-Jul-2023 20:12:31 UTC] PHP   2. html_validate_tree_vars() /usr/share/cacti/graph_view.php:308
```

You can see that cacti is trying to allocate 60+ GB of memory. The system is configured to allow up to 1G of memory, but also tried temporarily allowing up to 64G but it still generated errors.

Browser: Chrome

Host system: Rocky 8.8
Cacti:
```
$ rpm -q cacti
cacti-1.2.23-1.el8.noarch
```
PHP:
```
$ rpm -q php
php-7.4.33-1.module+el8.8.0+1150+ac720675.x86_64
$ php -v
PHP 7.4.33 (cli) (built: Oct 31 2022 10:36:05) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.33, Copyright (c), by Zend Technologies
    with Xdebug v2.9.5, Copyright (c) 2002-2020, by Derick Rethans
```

**Comment by TheWitness** [comment]
Try the 1.2.x branch instead...

**Comment by TheWitness** [comment]
Also test the 8.0 version of PHP using the dnf PHP8 stream.

**Comment by drees** [comment]
Hmm, so updating to php-8.0 seems to resolve the issue. Though I really need php-7.4 for the moment on this server.

**Comment by xmacan** [comment]
1.2.x works with php 7.4 well. You need to  update cacti to actual 1.2.x branch. This is basically the unreleased version 1.2.25.
Howto update is described here https://docs.cacti.net/Upgrading-Cacti.md

**Comment by drees** [comment]
Thanks, so you're confirming that the 1.2.x has a fix for this, so I'll have to install from source and uninstall the rpm from the epel repo?

**Comment by TheWitness** [comment]
I normally install from source, but many are not comfortable with the pre-reqs though.

**Comment by TheWitness** [comment]
Going to close this as a non-issue.
