### ISSUE TITLE
PHP 8.2 Deprecated Error - $session->value_output_format = $value_output_format;

### ISSUE THREAD

**Issue by reubenfarrelly** [Cacti/cacti#5399]
I've just done a test-run of php-8.2.8 to see how things work with Cacti and immediately found a problem:

08/Jul/2023 10:41:10 - CMDPHP PHP ERROR Backtrace: (/cli/poller_reindex_hosts.php[165]:run_data_query(), /lib/data_query.php[106]:query_snmp_host(), /lib/data_query.php[863]:cacti_snmp_session_walk(), /lib/snmp.php[445]:CactiErrorHandler())
08/Jul/2023 10:41:10 - ERROR PHP DEPRECATED: Creation of dynamic property phpsnmp\SNMP::$value_output_format is deprecated in file: /var/www/cacti/htdocs/lib/snmp.php on line: 445

This error is not printed with php-8.1 so it looks like a new change that is required for 8.2.

The error is printed dozens of times on a poll cycle so it is very noisy.

This is with the latest cacti 1.2.x git pull from github and on a Gentoo x86_64 box.

**Comment by TheWitness** [comment]
Is php-snmp installed or not?

**Comment by reubenfarrelly** [comment]
Yes:

<html>
<body>


PHP Version | 8.1.21
-- | --
PHP OS | Linux
PHP uname | Linux thunderstorm 6.4.2-gentoo #1 SMP PREEMPT_DYNAMIC Thu Jul 6 10:47:02 AEST 2023 x86_64
PHP SNMP | Installed. Note: If you are planning on using SNMPv3, you must remove php-snmp and use the Net-SNMP toolset.
max_execution_time | 30
memory_limit | 128M


</body>
</html>

**Comment by TheWitness** [comment]
It looks like I may have missed a commit back a while ago.

**Comment by TheWitness** [comment]
Should be all set now.
