### ISSUE TITLE
PHP ERROR: Uncaught Error: Call to undefined function imagettftext()

### ISSUE THREAD

**Issue by dsclassen** [Cacti/cacti#540]
Seeing this uncaught error in my cacti.log

```
2017-04-08 10:59:09 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4274 cacti_debug_backtrace)
thrown in file: /cacti/lib/rrd.php on line: 3253
#1 {main}
#0 /cacti/graph_image.php(151): rrdtool_create_error_image('file or directo...')
Stack trace:
2017-04-08 10:59:09 - ERROR PHP ERROR: Uncaught Error: Call to undefined function imagettftext() in /cacti/lib/rrd.php:3253

```

**Comment by cigamit** [comment]
Looks like the required module gd is not installed http://php.net/manual/en/function.imagettftext.php

**Comment by dsclassen** [comment]
GD is installed. Or at least the cacti Console-->Utilities-->Technical Support indicates that it is.

```
GD Support	enabled
GD Version	bundled (2.1.0 compatible)
GIF Read Support	enabled
GIF Create Support	enabled
PNG Support	enabled
libPNG Version	1.5.13
WBMP Support	enabled
XBM Support	enabled
Directive	Local Value	Master Value
gd.jpeg_ignore_warning	0	0
```

**Comment by cigamit** [comment]
Here is the issue.  Did you roll PHP yourself?  If not, you should let the package maintainer know to build in FreeType.  Keep us posted, though I'm keeping this closed for the moment.

http://stackoverflow.com/questions/7290958/php-fatal-error-call-to-undefined-function-imagettftext
