### ISSUE TITLE
The issue of unsuccessful creation of 95 billing for creating a multi port template

### ISSUE THREAD

**Issue by datutu58888** [Cacti/cacti#5400]
The issue of unsuccessful creation of 95 billing for creating a multi port template

This issue does not exist in version 1.2.11

When creating a graphic based on the multi port 95 billing template, a prompt appears with version 1.2.21

I created the template myself, and there were no issues creating and using it in version 1.2.11

Here are the prompts and screenshots

When I choose to create a multi port 95 template, I am prompted with an error in the index type, index value, and output type ID. In version 1.2.11, if these values are not entered, the creation can still be successful
![249744126-1d943ea6-7cb7-428a-b5b3-2d3fb979486d](https://github.com/Cacti/cacti/assets/138114577/35f08759-1102-4356-848f-eec4afa885ab)

These are the contents of the template, there is no problem creating graphics in version 1.2.11
![QQ图片20230701152200](https://github.com/Cacti/cacti/assets/138114577/2c971127-e53a-40d5-8803-7a8d1931d9e2)

According to the official response I received from Cacti on GitHub, I have already upgraded to version 1.2.24, but the above issues still persist, and there is a new prompt!
![QQ图片20230710170703](https://github.com/Cacti/cacti/assets/138114577/5582b170-d469-46ce-ba3f-3d518fd582cc)
![QQ图片20230710170725](https://github.com/Cacti/cacti/assets/138114577/6fd5d01e-ffbd-44a2-a6b3-210077c952be)

**Comment by TheWitness** [comment]
You need to upgrade to PHP7.4++.  You are still using PHP5.4 which has been end of life for several years.  RedHat only updated to PHP7.4 in RHEL8 with an option to go to PHP8.0 via streams.  We may have coded a workaround into Cacti 1.2.25 though.  If you update to the 1.2.x branch.  I believe this issue will be resolved.

**Comment by datutu58888** [comment]
I have tested cacti versions 1.2.11, 1.2.15, and 1.2.19, and none of them had this issue. However, when I tested version 1.2.20, this problem was triggered and it has persisted from version 1.2.20 to 1.2.24

**Comment by datutu58888** [comment]
> You need to upgrade to PHP7.4++. You are still using PHP5.4 which has been end of life for several years. RedHat only updated to PHP7.4 in RHEL8 with an option to go to PHP8.0 via streams. We may have coded a workaround into Cacti 1.2.25 though. If you update to the 1.2.x branch. I believe this issue will be resolved.

I have tested cacti versions 1.2.11, 1.2.15, and 1.2.19, and none of them had this issue. However, when I tested version 1.2.20, this problem was triggered and it has persisted from version 1.2.20 to 1.2.24.

**Comment by TheWitness** [comment]
Correct. I'm not surprised it's not worse.

**Comment by datutu58888** [comment]
The worse problem occurred. In the testing of version 1.2.19, it was found that it no longer requires me to input the index type, index value, and output type ID.

I successfully created a graph using my custom template and selected the ports I wanted to aggregate. However, the RRD files were not generated automatically. I have attached a screenshot showing this issue, and I have enabled graph debugging.

If this problem exists, it means that version 1.2.11 should also have this problem. I have a template that aggregates 40 ports into one graph, and at that time, the RRD files were not created automatically either. I manually ran a script in the operating system to create the RRD files, but I didn't pay attention to this issue and missed the opportunity.

If it is required to input the index type, index value, and output type ID in versions 1.2.20 to 1.2.24, how should I input them? Is there a reference specification available? I feel like these three values should be generated by the system automatically, as manual input might cause confusion, right?
![QQ图片20230717231748](https://github.com/Cacti/cacti/assets/138114577/9bf2795a-8e68-4e7a-b1ab-b6ae807aa121)
![QQ图片20230717231817](https://github.com/Cacti/cacti/assets/138114577/13d6088a-8af4-4397-b82e-798a91088766)
![QQ图片20230717231846](https://github.com/Cacti/cacti/assets/138114577/7854cbb8-8099-4711-b5df-b0a08281d1b7)

**Comment by datutu58888** [comment]
The following is a screenshot of my custom template. I hope you can understand it. It simply merges eight existing graphs into one and displays the 95th billing line, otherwise I would have to check each of the eight graphs individually.
Thank you very much!
![QQ图片20230717234756](https://github.com/Cacti/cacti/assets/138114577/18e8e085-aeb2-43a5-bff5-e279437093e4)
![QQ图片20230717234813](https://github.com/Cacti/cacti/assets/138114577/837c9eb7-1e11-4c60-9581-03f7e5552af5)
![QQ图片20230717234837](https://github.com/Cacti/cacti/assets/138114577/c009aa02-fee3-4085-8ff7-c0d0be0b8ef4)
![QQ图片20230717234903](https://github.com/Cacti/cacti/assets/138114577/10ce4b2a-8cdb-4617-a56c-e858b97a8bca)

**Comment by datutu58888** [comment]
This is the XML file for the 8-port template. I hope it will be helpful to you.
[cacti_graph_template_8-95.zip](https://github.com/Cacti/cacti/files/12071517/cacti_graph_template_8-95.zip)

**Comment by datutu58888** [comment]
cacti 1.2.19
php 7.4
centos 7.9

Notice:  Undefined offset: 24 in /home/cacti/lib/graph_variables.php on line 175

Notice:  Trying to access array offset on value of type null in /home/cacti/lib/graph_variables.php on line 175


Notice:  Undefined offset: 24 in /home/cacti/lib/graph_variables.php on line 175


Notice:  Trying to access array offset on value of type null in /home/cacti/lib/graph_variables.php on line 175

**Comment by datutu58888** [comment]
Just tested 1.2.25 and still prompted that the index type, index value, and output id must enter values
After practice, I have become proficient in switching and upgrading between different versions of Cacti, and have repeatedly deleted databases to completely switch between them
^_^ #

**Comment by datutu58888** [comment]
> 正确的。我很惊讶情况并没有更糟。

Are you saying that this problem really exists? How long will it take to fix it? Thank you very much!
I translated English using a translator, and the expression may not be very clear. Please understand!

**Comment by TheWitness** [comment]
What cacti release are you at?

**Comment by TheWitness** [comment]
You have to go to php7.4++.  Can you do that?

**Comment by TheWitness** [comment]
Or grab lib/functions.php from the 1.2.x branch.

**Comment by datutu58888** [comment]
> You have to go to php7.4++. Can you do that?

I can switch between PHP 5.6, 7.4, and 8.0 freely

**Comment by datutu58888** [comment]
> 或者从 1.2.x 分支获取 lib/functions.php。

I am currently using CentOS 7.9 with PHP 7.4 and Cacti 1.2.19. In versions prior to this, I was able to import my own graph templates, but they are not functioning correctly as they fail to automatically create RRD files. Starting from version 1.2.20, I can import the templates, but I am unable to create them as it prompts me to input values such as index type. If I update your files, do I need to upgrade Cacti to 1.2.24? When I directly updated your functions.php on version 1.2.19, I encountered the error message "Parse error: syntax error, unexpected '|', expecting '{' in /home/cacti/lib/functions.php on line 680".

**Comment by TheWitness** [comment]
Yea, with that old of a Cacti, you can not simply update the `lib/functions.php` and the one you pulled appears to be from the `develop` branch which requires php8.0+.  So, you have to be more careful as the `develop` branch is radically different than the `1.2.x` branch.  I suggest you at a minimum, since you are on PHP7.4 already, to upgrade to 1.2.24 today.

**Comment by datutu58888** [comment]
> Yea, with that old of a Cacti, you can not simply update the `lib/functions.php` and the one you pulled appears to be from the `develop` branch which requires php8.0+. So, you have to be more careful as the `develop` branch is radically different than the `1.2.x` branch. I suggest you at a minimum, since you are on PHP7.4 already, to upgrade to 1.2.24 today.


 deleted the cacti directory and extracted the new 1.2.24 version into the cacti directory. Following your guidance, I downloaded the latest lib/functions.php file and replaced the functions.php file in the 1.2.24 directory. However, when I accessed the website, I received an error message: "Parse error: syntax error, unexpected '|', expecting '{' in /home/cacti/lib/functions.php on line 680". At this moment, my PHP version is 7.4 and I am using Nginx 1.20.2.

**Comment by datutu58888** [comment]
> Yea, with that old of a Cacti, you can not simply update the `lib/functions.php` and the one you pulled appears to be from the `develop` branch which requires php8.0+. So, you have to be more careful as the `develop` branch is radically different than the `1.2.x` branch. I suggest you at a minimum, since you are on PHP7.4 already, to upgrade to 1.2.24 today.

I decided to download the latest 1.2.25 code because you mentioned that replacing the file resulted in an error. Therefore, I completely deleted the cacti directory and extracted the 1.2.25 files again. I also upgraded the 1.2.19 database to 1.2.25. However, when I tried to create an aggregate graph using my custom template, I still received the same prompt asking for those three values. My template is only intended for aggregation and does not involve index values.
![QQ图片20230726201658](https://github.com/Cacti/cacti/assets/138114577/d61f2132-a0eb-4a05-91bf-b47f3fde19cb)
![QQ图片20230726201727](https://github.com/Cacti/cacti/assets/138114577/35099d78-663a-4800-9a15-0e77e9c53afc)

**Comment by TheWitness** [comment]
Uh oh.  Check into this tomorrow.

**Comment by TheWitness** [comment]
You downloaded develops lib/functions.php and not the 1.2.x branches. 

`git clone -b 1.2.x https://github.com/cacti/cacti.git`

**Comment by datutu58888** [comment]
> You downloaded develops lib/functions.php and not the 1.2.x branches.
> 
> `git clone -b 1.2.x https://github.com/cacti/cacti.git`

I obtained my version 1.2.25 by directly downloading the file from the link provided in the screenshot below. This should be the updated complete package that you have released, right?
![QQ图片20230727143920](https://github.com/Cacti/cacti/assets/138114577/d3f239be-c1e4-472b-8df8-4646304585a0)

I downloaded my lib/functions.php file by clicking on the location indicated in the screenshot below. I believe this is also your latest file, correct?

![QQ图片20230727144002](https://github.com/Cacti/cacti/assets/138114577/3066fdd6-f98a-48c4-afc9-5288e418edab)

**Comment by datutu58888** [comment]
After downloading lib/functions.php based on version 1.2.25, I copied and pasted its content into the functions.php file under my cacti 1.2.25 installation. However, I encountered an error that says "Parse error: syntax error, unexpected '|', expecting '{' in /home/cacti/lib/functions.php on line 680." Currently, my PHP version is 7.4. Do I need to upgrade to PHP 8.0?

**Comment by datutu58888** [comment]
php 8.24  

new /lib/functions.php copy 1.2.25/lib/functions.php

Fatal error: Uncaught Error: Undefined constant "OPTIONS_WEB" in /home/cacti/lib/functions.php:686 Stack trace: #0 /home/cacti/lib/functions.php(1336): read_config_option() #1 /home/cacti/include/global.php(385): cacti_log_file() #2 /home/cacti/include/auth.php(27): require_once('...') #3 /home/cacti/index.php(25): include('...') #4 {main} thrown in /home/cacti/lib/functions.php on line 686

**Comment by TheWitness** [comment]
You are still downloading the wrong version.  Look for the word "develop" on that page. Click on the word, it's a drop-down.  Change it to 1.2.x.  Once you do that, you will be downloading the right version.

**Comment by datutu58888** [comment]
> You are still downloading the wrong version. Look for the word "develop" on that page. Click on the word, it's a drop-down. Change it to 1.2.x. Once you do that, you will be downloading the right version.

this ok ?
I updated the functions.php in this link. The error message is gone, but when I create a template graphic, it still asks me for three values. Do you need to download the zip package from this link and redeploy?
![EV75OLN3LP9% IZQZS( CX7](https://github.com/Cacti/cacti/assets/138114577/48659bc7-3c82-4f55-83b0-1bf922c72ba5)

**Comment by TheWitness** [comment]
Edit and re-save the template and you should be fixed.  The template had those settings uncheck which was an error.  We can keep this bug open though as the import function should handle that repair.

**Comment by TheWitness** [comment]
Glad you hung in there though.

**Comment by datutu58888** [comment]
I have many port aggregation templates, have you tried the one I uploaded? Find my custom template in template ---&gt; graphic template ------, edit it, and save it without any modification, does that mean?



---Original---
From: ***@***.***&gt;
Date: Thu, Jul 27, 2023 22:43 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Cacti/cacti] The issue of unsuccessful creation of 95 billingfor creating a multi port template (Issue #5400)




 
Glad you hung in there though.

**Comment by datutu58888** [comment]
> Edit and re-save the template and you should be fixed. The template had those settings uncheck which was an error. We can keep this bug open though as the import function should handle that repair.

Following your instructions, I clicked on "Edit" for my custom template without making any changes, and then saved it. However, when I tried to create a graph using the template again, I still received a prompt asking for three index values.

**Comment by TheWitness** [comment]
Apply this patch, and then re-import the Template.

https://github.com/Cacti/cacti/issues/5426

**Comment by TheWitness** [comment]
When you edit the Data Template, the Custom Data should look like this:

![image](https://github.com/Cacti/cacti/assets/1439914/886e5abb-1eca-463d-9172-960dae348445)

**Comment by TheWitness** [comment]
Please upload a TGZ of your Template so that we investigate further.

**Comment by datutu58888** [comment]
> 当您编辑数据模板时，自定义数据应如下所示：
> 
> ![图像](https://user-images.githubusercontent.com/1439914/256676448-886e5abb-1eca-463d-9172-960dae348445.png)

I have updated the files in the screenshots below, but when I try to import the template again, it still prompts for three index values.

![QQ图片20230728120216](https://github.com/Cacti/cacti/assets/138114577/fc022322-dbea-44c0-ba1c-afc499645ffa)
![QQ图片20230728120119](https://github.com/Cacti/cacti/assets/138114577/7781ad3d-3d24-4ae9-909a-ffd366d9382d)

At the same time, I also updated the code in /lib/import.php. However, when I was in the editing mode of the template, I didn't see the screen you mentioned where I could choose to disable the three index values.

**Comment by datutu58888** [comment]
> 请上传您模板的 TGZ，以便我们进一步调查。

[cacti_graph_template_8-95.zip](https://github.com/Cacti/cacti/files/12190070/cacti_graph_template_8-95.zip)

**Comment by datutu58888** [comment]
> When you edit the Data Template, the Custom Data should look like this:
> 
> ![image](https://user-images.githubusercontent.com/1439914/256676448-886e5abb-1eca-463d-9172-960dae348445.png)

You asked about here? If it's re
![QQ图片20230728122929](https://github.com/Cacti/cacti/assets/138114577/3b627c38-d0d5-4082-8138-199d19d7dd6c)
ferring to this part, it matches the screenshot you provided.

**Comment by TheWitness** [comment]
Okay, I'm reading through everything now in a bit more detail.  I was not paying close attention to detail before and made some general assumptions.  

So, here is the problem, you were trying to mix templating with non templating and then hacking in the bits to take it the last mile.

Though this is very creative, you should have not done that as it sets you up for what just happened.

The supported way of doing this would have been to create all the single graphs and then used something like aggregate to create the graph, and then, if you did not what aggregate produced, you could convert it to a non-templated graph and then make all the changes.

So, there is not much we can do here, oh and you only sent me the graph template, but not the data template or data query components.  Did you ask to include dependencies?

Why don't you send the entire Device Template along.  I'm curious how you did this.

**Comment by datutu58888** [comment]
> Okay, I'm reading through everything now in a bit more detail. I was not paying close attention to detail before and made some general assumptions.
> 
> So, here is the problem, you were trying to mix templating with non templating and then hacking in the bits to take it the last mile.
> 
> Though this is very creative, you should have not done that as it sets you up for what just happened.
> 
> The supported way of doing this would have been to create all the single graphs and then used something like aggregate to create the graph, and then, if you did not what aggregate produced, you could convert it to a non-templated graph and then make all the changes.
> 
> So, there is not much we can do here, oh and you only sent me the graph template, but not the data template or data query components. Did you ask to include dependencies?
> 
> Why don't you send the entire Device Template along. I'm curious how you did this.

I have been using these templates since the early versions of Cacti 0.x. It's possible that the earlier versions didn't have the aggregation feature. My template version 1.2.11 can still be used, but there are difficulties with automatically creating RRD files, so manual intervention is required. It doesn't actually rely on anything specific; it just calls the "Interface - Traffic" data source under the template. We have been using this method for 10 years, and many people in China also use it. We are accustomed to using this method to aggregate multiple graphs into one and retrieve the 95th percentile value. Are you saying that aggregation can achieve all the functionalities of my template?

**Comment by datutu58888** [comment]
> Okay, I'm reading through everything now in a bit more detail. I was not paying close attention to detail before and made some general assumptions.
> 
> So, here is the problem, you were trying to mix templating with non templating and then hacking in the bits to take it the last mile.
> 
> Though this is very creative, you should have not done that as it sets you up for what just happened.
> 
> The supported way of doing this would have been to create all the single graphs and then used something like aggregate to create the graph, and then, if you did not what aggregate produced, you could convert it to a non-templated graph and then make all the changes.
> 
> So, there is not much we can do here, oh and you only sent me the graph template, but not the data template or data query components. Did you ask to include dependencies?
> 
> Why don't you send the entire Device Template along. I'm curious how you did this.

Strictly speaking, the template I sent you looks more like a drawing tool. It utilizes "Interface - Traffic in/out" to create a list of many individual graphs, and once I add the desired ports, it generates a single graph. Can the aggregation feature you mentioned fulfill the functionalities of my template?

**Comment by datutu58888** [comment]
> Okay, I'm reading through everything now in a bit more detail. I was not paying close attention to detail before and made some general assumptions.
> 
> So, here is the problem, you were trying to mix templating with non templating and then hacking in the bits to take it the last mile.
> 
> Though this is very creative, you should have not done that as it sets you up for what just happened.
> 
> The supported way of doing this would have been to create all the single graphs and then used something like aggregate to create the graph, and then, if you did not what aggregate produced, you could convert it to a non-templated graph and then make all the changes.
> 
> So, there is not much we can do here, oh and you only sent me the graph template, but not the data template or data query components. Did you ask to include dependencies?
> 
> Why don't you send the entire Device Template along. I'm curious how you did this.

My device template and graph template are both default in Cacti 1.2.24. I only need a few components because I have performed a fresh minimal installation, and most of the templates have been removed as per my requirements. What do I need to do next? Thank you very much for your assistance in tracking this issue ove
![QQ图片20230728150129](https://github.com/Cacti/cacti/assets/138114577/13e30575-71ad-47d8-808f-654f4e9fe149)
r the past few days!
![QQ图片20230728150552](https://github.com/Cacti/cacti/assets/138114577/719debf9-acb9-47d9-8c78-f44e03b70094)

**Comment by TheWitness** [comment]
Tru just entering data, or better yet, chang the data input method to something non-indexed.  The downside is that it will create a data source in both cases.  Maybe create a fake Data Input method that echos 0 and use it.  Using SNMP Data Index's requires something in this three fields moving forward.

**Comment by TheWitness** [comment]
Just checked on my phone "none" is a valid option! [Screenshot_20230728-072912.png](https://github.com/Cacti/cacti/assets/1439914/b36076bf-846a-43c4-af0f-a2bee381d6cd)

**Comment by TheWitness** [comment]
Just checked on my phone "none" is a valid option! [Screenshot_20230728-072912.png](https://github.com/Cacti/cacti/assets/1439914/b36076bf-846a-43c4-af0f-a2bee381d6cd)

You may have to alter your process a bit to pull it off.  Maybe duplicate the template, then change the method, and then switch template for your existing graphs.  Better create a test system for this.

**Comment by TheWitness** [comment]
I'm going to close this one again.  After long thought, you should pick the data input method as 'None' moving forward.  Then you can continue to script the rest.

**Comment by datutu58888** [comment]
> 您可能需要稍微改变您的流程才能实现这一目标。也许复制模板，然后更改方法，然后切换现有图表的模板。最好为此创建一个测试系统。



> You may have to alter your process a bit to pull it off. Maybe duplicate the template, then change the method, and then switch template for your existing graphs. Better create a test system for this.

Thank you very much! I will follow your instructions and proceed with the testing.

**Comment by datutu58888** [comment]
> I'm going to close this one again. After long thought, you should pick the data input method as 'None' moving forward. Then you can continue to script the rest.

This is a consolidated graph with 6 ports. How can I make sure that only the 'Outbound', 'Inbound', and the '95 Red Line' are shown on the graph? The additional lines make the visualization look strange, as
![QQ图片20230803151157](https://github.com/Cacti/cacti/assets/138114577/b3cd3245-f206-4221-bea5-d38276317d97)
 my actual traffic is not 250G

**Comment by TheWitness** [comment]
It's a separate issue.  Don't mix issues.
