### ISSUE TITLE
cacti 1.2.24 logs errors

### ISSUE THREAD

**Issue by abderrazak-meksi** [Cacti/cacti#5404]
### I'm experiencing redundant errors in the cacti logs. Any ideas on how to fix them?

![image](https://github.com/Cacti/cacti/assets/18287470/eae064ad-3ad0-48f3-bcb5-8b57120fc8cd)

**Comment by TheWitness** [comment]
Your script server is crashing.  Check the stderr log or enable the PHP error_log.

**Comment by abderrazak-meksi** [comment]
cacti_stderr.log is empty
after enabling PHP error_log remains empty too.

it's a fresh installation of the last version without errors during it. my system is ubuntu 22.04 and php version is 8.1

**Comment by TheWitness** [comment]
You may have to test each of your PHP script server scripts.  Can you try to get access to 1.2.25?  You might want to reach out to @paulgevers and get details on how to get early access through aptitude.  We are delaying release for Windows if you can believe that.

**Comment by paulgevers** [comment]
@abderrazak-meksi, before I get involved :) how did you install cacti on your Ubuntu 22.04? The default on 22.04 should be something older than 1.2.24, hinting that you didn't use the Ubuntu package.

**Comment by TheWitness** [comment]
Run this command:

```bash
cd /usr/share/cacti/site/scripts
for file in `ls -1 *.php`;do php -l {} \;
```

Look for the error.

**Comment by paulgevers** [comment]
> Run this command:
> 
> ```shell
> cd /usr/share/cacti/site/scripts
> for file in `ls -1 *.php`;do php -l {} \;
> ```
> 
> Look for the error.

I assume this needs to be done somewhere under `/opt/cacti` which seems to be where the reporter installed cacti (judging from the error log).

**Comment by TheWitness** [comment]
Thanks Paul.

**Comment by TheWitness** [comment]
So, if you turn logging to high, you might be able to glean where or what script is failing.  Do that and then upload your poller cache with the script server items selected only.

**Comment by netniV** [comment]
If I remember rightly, @paulgevers , ubuntu/debian doesn't install to /opt by default, that's more a redhat thing?

**Comment by paulgevers** [comment]
@netniV `/opt` in Debian (and all derivatives) is the domain of the system administrator. Packages in Debian are not allowed to install there. Hence, I concluded that the OP didn't install a Debian package, but installed cacti manually.

**Comment by netniV** [comment]
Yeah, that's what I guessed too having read that.  Thanks for clarifying your side.

**Comment by TheWitness** [comment]
Okay, closing this one now.
