### ISSUE TITLE
Edit a tree - unpublished after save (similar to #5159)

### ISSUE THREAD

**Issue by xmacan** [Cacti/cacti#5405]
On 1.2.25 

Management -> trees -> choose any (published) tree -> Edit tree -> click save. Result is unpublished tree

**Comment by TheWitness** [comment]
Let me check.

**Comment by TheWitness** [comment]
If found this a 1.2.24 issue.  I was working with an x-customer yesterday, and we only had to pull the latest 1.2.x branch.  Can you check?

**Comment by TheWitness** [comment]
Yea, just tested and it's fine.  There was some 1.3.x code in the 1.2.24 release apparently, or it was somewhere between releases.

**Comment by xmacan** [comment]
Tested, with actual 1.2.x branch it is ok
