### ISSUE TITLE
QA: Package import doesn't save device class

### ISSUE THREAD

**Issue by xmacan** [Cacti/cacti#5408]
Package has correct class  <class>linux</class>.
After import Device template has Unassigned device class always

**Comment by TheWitness** [comment]
I coded a fix.  Just need to test.

**Comment by TheWitness** [comment]
@xmacan, you should be all set now.

**Comment by xmacan** [comment]
Tested, ok, thank you

**Comment by TheWitness** [comment]
Great.  Put that minor enhancement into 1.2.25 today if you have time.
