### ISSUE TITLE
Classic template missing horizontal scroll in Graph view

### ISSUE THREAD

**Issue by reboot1983** [Cacti/cacti#541]
In Cacti 1.1.2 I cannot view the whole graph (treeview mode) on my mobile device (iPhone 7, Safari default browser) in the classic template. 

On the modern template I get a horizontal scrollbar which allowes me to scroll and see te right side of the graph and the icons. On the classic template I have no scrollbar and cannot see the whole graph and the icons.

![img_1367](https://cloud.githubusercontent.com/assets/20405704/24832833/2044c1b6-1cb9-11e7-935f-c9ed958f0488.PNG)
![img_1368](https://cloud.githubusercontent.com/assets/20405704/24832834/20638a38-1cb9-11e7-96da-42d7a1607b55.PNG)

**Comment by reboot1983** [comment]
Both templates are tested and viewed in portrait mode

**Comment by cigamit** [comment]
This one will have to wait till we do more of a responsive navigation.  Won't make 1.1.3 for sure.

**Comment by cigamit** [comment]
It should be a little better.  Was a pretty large change.  New behavior, if your screen is < 780 pixels, the menu and tree will be hidden automatically.  You can show it again by click on the Graph or Console menu pick.  Also, the filterTable will have elements automatically hidden as the display is resized.  The actual tables themselves, there is a design, but it will take more work.
