### ISSUE TITLE
Cacti themes are not working in chrome 1.1.2 

### ISSUE THREAD

**Issue by nitzan-tz** [Cacti/cacti#542]
Hi,

After upgrading to 1.1.2 I saw that only the Classic theme is working no matter which one I am selecting 
In Firefox it works fine 
I also tried it with the fix in #532 but it didnt help 

I am running Windows 10 with chrome 57.0.2987.133 (64-bit)

Thanks

Nitzan

**Comment by cigamit** [comment]
Open your browsers console and look for JavaScript errors.  I suspect this is a third party plugin causing this issue.  Please post your results.

**Comment by nitzan-tz** [comment]
![image](https://cloud.githubusercontent.com/assets/7695109/24837891/bf2b6c84-1d46-11e7-8820-3f86c789af5e.png)

As you can see there is no error in the console and I have disabled all chrome extensions and run it in incognito mode

**Comment by cigamit** [comment]
I'm not sure incognito is a good way to test.  I would have to say that there must be something wrong with your setup.

**Comment by cigamit** [comment]
Until you can get me some good details on this, I'm going to close.  1.1.3 will be out in a few days.  I have tried to reproduce this to no avail.  Maybe your user_settings table is corrupt?  Run a repair on your table.

**Comment by nitzan-tz** [comment]
Hi,

I understand the issue
I didn't notice the theme setting is also per user (In Firefox I test with different user )

Maybe its a good idea to add indication if the setting is per user or  global 

Thanks
Nitzan
