### ISSUE TITLE
Does cacti support mariaDB 11.0.2? 

### ISSUE THREAD

**Issue by aliuzzz** [Cacti/cacti#5424]
In this version of the database, the "innodb_flush_method" field has been removed, which affects the installation of cacti
![image](https://github.com/Cacti/cacti/assets/43594093/ef85e136-a7f4-4042-bc96-a85c5d507676)

**Comment by TheWitness** [comment]
Thanks for the tip @aliuzzz !

**Comment by aliuzzz** [comment]
That's OK.
Meanwhile, I would like to know if the stable version of 1.2.25 will be released in August？

**Comment by TheWitness** [comment]
For sure.

**Comment by netniV** [comment]
We keep getting ready to release, and then someone finds something that means we need to postpone slightly.  I had hoped to have it released this weekend, but we are going to be making changes this week so that is likely to be postponed again.  Ultimately, the end of August is the latest I'm trying to aim for.

**Comment by aliuzzz** [comment]
Approaching September

**Comment by TheWitness** [comment]
I'll do some testing tonight.  I suspect that there will not be issues outside of initial setup though.  We shall see.

**Comment by TheWitness** [comment]
Worked perfectly.  Had to make a slight change to the 1.2.25 installer as the `innodb_version` variable was deprecated and removed from the settings.

**Comment by TheWitness** [comment]
BTW

```bash
[root@vmhost6 ~]# mysql --version
mysql: Deprecated program name. It will be removed in a future release, use '/usr/bin/mariadb' instead
mysql from 11.1.2-MariaDB, client 15.2 for Linux (x86_64) using  EditLine wrapper
```

**Comment by TheWitness** [comment]
Likely we should update the documentation to simplify things more though.  This is all I had to add to the `server.cnf` file

```shell
[mariadb]
max_heap_table_size=500M
character_set_client=utf8mb4
character_set_server=utf8mb4
collation_server=utf8mb4_unicode_ci
innodb_buffer_pool_size=8G
innodb_doublewrite=OFF
tmp_table_size=500M
```

**Comment by netniV** [comment]
We may need to update the install to search for `mariadb` now as well as `mysql` with a documented preference.

**Comment by TheWitness** [comment]
In MariaDB 11.x, they are starting to deprecate mysql* for mariadb-* now too.  So, it'll be a while before they fork completely.  I'm riding MariaDB 11.0.2-1 right now on one of my test boxes with the configuration above.  Funny thing, even though they deprecated `innodb_flush_method`, it stoll reports O_DIRECT even though I did not set it.  So, Cacti is not generating any warnings on the Technical Support page.

![image](https://github.com/Cacti/cacti/assets/1439914/881b9378-ca4d-4b8f-a302-350c3087f714)
