### ISSUE TITLE
[1.3 QA] Automation Device Rules has no column sorting available.

### ISSUE THREAD

**Issue by jdcoats** [Cacti/cacti#5433]
Automation Device Rules has no column sorting available.

**Comment by TheWitness** [comment]
Yup.  I'm like 85% through the 1.3 version.  Seems like I can not find the time to finish anything.

**Comment by TheWitness** [comment]
It's fixed in 1.3.  If you have Drag & Drop Enabled, you will not see the move Icons.

**Comment by TheWitness** [comment]
I did some confirmation and removed the inline styling here: a9c91486147a4c0109cc6326c46a88ba8f335b7f and here: 04b3289b0515c5e5b58cc610afb1a8c4bc44995a
