### ISSUE TITLE
Change Graph Template

### ISSUE THREAD

**Issue by optimuscream** [Cacti/cacti#5437]
Hello

I don't know if has been asked before , resolved or not. Or it is by design.

I have graph that I want to change its graph template to another graph template.

Cacti version 0.8.8x  has ability to change the graph template directly in the individual graph.

![graphtemplatecactiold](https://github.com/Cacti/cacti/assets/14342926/68e5fde5-2e42-40d5-8c17-f3008b421eef)

How to change the graph template in cacti version 1.2.x or latest cacti.  Don't have the old option in the newest cacti version.

![Screenshot 2023-08-08 at 08-52-52 Console Graph Management (Edit)](https://github.com/Cacti/cacti/assets/14342926/a6a47f52-37aa-41c4-bf1b-754a67169708)

Thanks and regards

**Comment by TheWitness** [comment]
You first have to set the Graph Template in the Filter Drop-down to your Template.  It can not be 'All'.  Once you do that the option from 0.8.x will re-appear.

**Comment by TheWitness** [comment]
After that, only compatible templates will show up.

**Comment by TheWitness** [comment]
So, to be clear:  Management > Graphs > Filter on Template > Select the Graph "highlight", from the Go menu pick Change Template, then Press "Go"

**Comment by optimuscream** [comment]
ok I found it . It takes few steps but work.  Could I also make request to change it to the old ways ?

Thanks anyway.

**Comment by TheWitness** [comment]
You can log a feature request.  Would happen in 1.3.x though.
