### ISSUE TITLE
Allow Log Rotation to be other than Daily

### ISSUE THREAD

**Issue by reboot1983** [Cacti/cacti#544]
Although my rotation settings are set to 28 days, de logs are rotated every night by CMDPHP.

`2017-04-09 00:00:30 - CMDPHP Cacti Log Rotation - Created Log cacti.log-20170409`

```
:/var/www/html/cacti/log $ ls -lha
total 96K
drwxrwxr-x  2 www-data www-data 4.0K Apr  9 00:00 .
drwxrwxr-x 17 pi       pi       4.0K Apr  2 21:36 ..
-rw-rw-r--  1 www-data www-data  19K Apr  9 10:45 cacti.log
-rw-rw-r--  1 www-data www-data  14K Apr  8 00:00 cacti.log-20170408
-rw-rw-r--  1 www-data www-data  43K Apr  9 00:00 cacti.log-20170409
-rw-rw-r--  1 www-data www-data  170 Apr  2 21:36 .htaccess
```

![schermafbeelding 2017-04-09 om 10 49 21](https://cloud.githubusercontent.com/assets/20405704/24836063/6f786ee6-1d12-11e7-940a-15651c132181.png)

**Comment by cigamit** [comment]
The setting is retention, not rotation interval, though I agree that rotation should be configurable to nightly, weekly, monthly, etc.

**Comment by ronytomen** [comment]
This is a pretty easy change, poke at it and make a pull request!  

While it is easy, it's a distraction from working on other issues and enhancements.  Work around would be to use logrotate and not use built in log rotation.

This can move up in priority if people care to comment that they want this feature.

**Comment by cigamit** [comment]
Resolved.  New settings: Daily, Weekly, and Monthly.
