### ISSUE TITLE
search doesn't show all items after selecting item in cacti 1.1.2 with firefox 52.0.1

### ISSUE THREAD

**Issue by gmuellerfr** [Cacti/cacti#545]
Hello,

I've searched in the device list for an item. Three found devices are displayed.
![search_cacti_before_select](https://cloud.githubusercontent.com/assets/25848039/24848704/4712b5fe-1dc8-11e7-8d07-87cecd52cdfd.png)
Now I select one of the devices. From now on no device will be displayed in the list although the header line suggests 3 found devices. This list remembers this state even if I select other menu items 
![search_cacti_after_select](https://cloud.githubusercontent.com/assets/25848039/24848726/68db94a8-1dc8-11e7-87f9-87b0d17cfbc7.png)
until I clear the search field with Ctrl+Shift+X which will display the whole list.

Kind Regards
Guenter

**Comment by cigamit** [comment]
Can you define 'select'.  Does that mean edit and save?

**Comment by gmuellerfr** [comment]
Yes, 'select' meant clicking on one of the show items under "Device Description".
I'm sorry for not writing more clearly.
Guenter

**Comment by cigamit** [comment]
I'm running 52.0.2 and I can not reproduce.  Are there any errors in the Cacti log when this happens?  You may want to put host.php into Developer Debug mode so we can see the failing SQL if you are able to reproduce this at will.

I'll keep this ticket open for a few days to give you a chance of figuring out what the bad SQL looks like and post it here.

**Comment by gmuellerfr** [comment]
Hello,
I've logged off and logged on again and the behaviour disappeared. Maybe something went wrong in the browser cache.
Thank you for listening.
Guenter
