### ISSUE TITLE
Unable to convert database to latin1 instead of utf8 if desired

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#5450]
# Describe the bug

There is presently no way to mass convert tables to latin1 if you are space constrained and don't use international characters.

## To Reproduce

1. Go to cli folder

2. Run ./convert_tables.php --help

3. There is no latin1 option

## Expected behavior

Cacti should provide the ability to move between utf8mb4 and latin1

**Comment by netniV** [comment]
It should be noted, this will make the installer request table conversion each time until utf8 is restored.

**Comment by TheWitness** [comment]
Yea, maybe we should have set the character set for the whole tables and verify against that.

**Comment by netniV** [comment]
No I believe the default of UTF8's is correct for modern dbs

**Comment by TheWitness** [comment]
We will have to address as a feature in 1.3.
