### ISSUE TITLE
Unable to Generate RRD Files for Some Graphs on the Same Device. How to Proceed?

### ISSUE THREAD

**Issue by htyypt** [Cacti/cacti#5456]
Details: 

Device: Same device Some graphs' RRD files are generated, while others are not. How should this be addressed?

Versions: 

Cacti 1.2.24 
SPINE 1.2.24 
RRDtool 1.8.0

Situation: 

Multiple graphs of the same template on the same device. After creating the graphs, some of them randomly fail to generate RRD files.

Known Information:

1.The number of graphs matches the number of data sources.

2.The number of data sources in the Poller cache matches.

3.DEBUG mode logs are mostly normal. Data sources are displayed correctly. RRDsProcessed count is incorrect for some (mismatch with expected RRDs and actual directory content).

4.After clearing all RRD files from the directory and completing the polling again, the RRD files are recreated. This indicates that it's not a permission-related issue. The quantity remains the same (the ones that failed previously are still not created).

Question: How can I proceed to confirm the issue further?

**Comment by TheWitness** [comment]
Please try the lastest 1.2.x branch.
