### ISSUE TITLE
Current develop branch layout issues

### ISSUE THREAD

**Issue by reboot1983** [Cacti/cacti#546]
At the current develop branch there are some layout issues. This is a screenshot of a device edit. As you can see, the notes textarea has a blue/gray tableheader laying under the textarea.

Also: at the Associated Graph Templates and Associated Data Queries sections, de columnheaders are not visible due to the columnheaderbackground being white instead of blue/gray.

![image](https://cloud.githubusercontent.com/assets/20405704/24856486/300e7f4c-1de5-11e7-8c90-ff75d2b7f5bd.png)

p.s. had a hard time creating perfect round circles and a square box with my mouse :p :p

**Comment by cigamit** [comment]
Ahh, one of those is a Chrome rendering bug (from top to bottom, first one).  And when I went to their bug tracking site to review a few months ago, there were so many rendering bugs that I just gave up.  The second I may have introduced this weekend.  I'll have to check it out.

**Comment by cigamit** [comment]
I used to hate IE, now my disdain is increasing with yet again, another buggy browser.
