### ISSUE TITLE
When viewing data sources, an undefined variable error may be seen

### ISSUE THREAD

**Issue by xmacan** [Cacti/cacti#5464]
Actual 1.2.x branch

When I was apparently working incorrectly with data profiles, part of my data source now reports:
File RRA '0' has same CF/steps (AVERAGE, 1) as '1'
File RRA '1' has same CF/steps (AVERAGE, 1) as '0'
File RRA '5' has same CF/steps (MAX, 1) as '6'
File RRA '6' has same CF/steps (MAX, 1) as '5'
File RRA '6' has same CF/steps (MAX, 1) as '5'

There is few php warning too:
Warning: Undefined variable $i in /usr/local/share/cacti/lib/rrd.php on line 3034
Warning: Undefined variable $i in /usr/local/share/cacti/lib/rrd.php on line 3034
Warning: Undefined variable $i in /usr/local/share/cacti/lib/rrd.php on line 3034
Warning: Undefined variable $i in /usr/local/share/cacti/lib/rrd.php on line 3034

**Comment by TheWitness** [comment]
Okay, this is fixed now.
