### ISSUE TITLE
Automation Rules detecting down interface when rule set to only show interfaces that are up.

### ISSUE THREAD

**Issue by ck-australia** [Cacti/cacti#5465]
# Describe the bug

When creating an automation to detect interface on Cisco devices whereby the OperStatus and AdminStatus are both up its detecting interfaces that are also in a down down state.

## Expected behavior

Only interfaces that are in an Up/Up state to be matched as part of the rule. 

## Screenshots

If appli
![Screenshot 2023-08-17 092426](https://github.com/Cacti/cacti/assets/77236712/0bc1d7ab-f19f-4a09-bfbc-8a8ad035f713)
cable, add screenshots to help explain your problem.

## Desktop
![Screenshot 2023-08-14 132626](https://github.com/Cacti/cacti/assets/77236712/74fb45fb-67fb-45cf-be00-837caff8187a)
 (please complete the following information)

- OS: RedHat Enterprise

- Browser Chrome

**Comment by TheWitness** [comment]
Good catch.  What did the final GUI look like to make this work? I won't say it is or not a bug (yet :) )

**Comment by TheWitness** [comment]
I've been messing with this tonight, and have a nice Enhancement to merge after the 1.2.25 release.  Basically, you can click on an Icon and get this popup to help with diagnosing what you are doing wrong.  So, you were right.  In the end, it's not a bug, but that does not make it easy to diagnose.  This change will help.

![image](https://github.com/Cacti/cacti/assets/1439914/b64fe98b-84ad-48b6-aa24-26255ea4263d)

**Comment by TheWitness** [comment]
@netniV, so that you can see it.

**Comment by TheWitness** [comment]
The leading `AND` or `OR` and the `)` or `(` need to be on their own lines.

**Comment by TheWitness** [comment]
![image](https://github.com/Cacti/cacti/assets/1439914/ad651f45-a3cf-45e1-a42a-29211decba85)

**Comment by arno-st** [comment]
I like the idea of the button to troubleshoot the rule.
I'm not sure you have to have the ( )  on a separate line.
I have this rule and it works very well:

![Cacti autom8](https://github.com/Cacti/cacti/assets/25684899/4c724324-fa5e-4ea5-b78e-8d758515ddb6)

**Comment by TheWitness** [comment]
Okay, I think we are settled then.  @ck-australia.  It's not pretty, but are you getting it?
