### ISSUE TITLE
[1.3 QA] After Upgrade to 1.3 Realm show 'Unavailable' for Legit Realms

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#5470]
# Describe the bug

After upgrading to 1.3 from 1.2.x, looking at the User Auth page, we see the following:

![image](https://github.com/Cacti/cacti/assets/1439914/f2aee72c-3a22-4697-8ee8-a2818af9f219)

These were legal domains in the 1.2.x version.

## Expected behavior

The true Domain name as defined in Cacti should be shown.

**Comment by TheWitness** [comment]
@netniV, can we add the confirmed flag to the outdated/stale watching?  If it's marked confirmed, then don't mark outdated.

**Comment by netniV** [comment]
That would leave most issues open. The whole point of outdated is to prompt for a response or action so it's not forgotten.

**Comment by TheWitness** [comment]
I only have so many hours in a day @netniV.  So, things will linger.

**Comment by netniV** [comment]
Don't disagree on that one. It's like that annoying calendar reminder. You'll keep dismissing it.

**Comment by TheWitness** [comment]
Fixed.
