### ISSUE TITLE
[1.3 QA] When saving settings in the `develop` version of Cacti, the response to the save is not handled properly

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#5471]
# Describe the bug

When you save the settings page, the response is not handled properly in Ajax.

![image](https://github.com/Cacti/cacti/assets/1439914/9eb11219-2039-4ae3-a097-f2d6a9833636)

## Expected behavior

The page and the response should be handled in Ajax via a callback.

**Comment by netniV** [comment]
I swore I already fixed that very recently.  Did someone break it again?

**Comment by netniV** [comment]
This was the commit: e5c973d22

**Comment by TheWitness** [comment]
Sorry, I was running a 'streams' branch.  Thanks!

**Comment by TheWitness** [comment]
I updated and the UI component now has a progress bar, but does not go away when it hits the right end of the page.
