### ISSUE TITLE
Preview Mode | Preset's Clear button Issue

### ISSUE THREAD

**Issue by kimarenchi** [Cacti/cacti#5474]
# Describe the bug

Pressing Preset clear button on preview mode does not reset the graph to the default times span.

## To Reproduce

1. Go to Preview Mode

2. Zoom the graph or change the Preset timespan.

3. Press the Preset Clear button to reset the graph to the default timespan

4. Graph does not reset to the default timespan

## Expected behavior

Pressing Preset Clear button should reset the graph to the default timespan which is working fine with Version 0.8.8h

## Screenshots

<img width="531" alt="Preview Mode2" src="https://github.com/Cacti/cacti/assets/101618968/71840a43-c11e-4379-abb2-23fcd02d19ec">

## Desktop (please complete the following information)

- OS: Windows 11

- Browser: Brave and Chrome 
- Version [Version 1.57.53 Chromium: 116.0.5845.114 (Official Build) (64-bit)](https://brave.com/latest/)
- Version 116.0.5845.140 (Official Build) (64-bit)

**Comment by TheWitness** [comment]
What Cacti version?

**Comment by TheWitness** [comment]
I've been unable to reproduce this either on the 1.3.0 develop version and the 1.2.25 version.
