### ISSUE TITLE
CSV result missed timestamps by 5 minutes

### ISSUE THREAD

**Issue by accidentalyadmin** [Cacti/cacti#5479]
# Describe the bug

Export to CSV may or will result in missed timestamps by 5 minutes both at the start and end time.

## To Reproduce

1. Go to 'Graphs' tab and select the graph that you need to export to CSV.

2. Select precisely the start time and end time, eg. 08:00 AM start time and 18:00 PM end time.

3. Click 'export to CSV' button on the right side of the graph, download and save the CSV file.

4. Open the CSV file.

## Expected behavior

Notice at the 'Start date' column will say "yyyy-mm-dd 08:05:00" and the 'End date' column will say "yyyy-mm-dd 18:05:00".

## Screenshots
![IMG-20230905-WA0003](https://github.com/Cacti/cacti/assets/144127012/c84acb5d-1c23-4ac5-80cf-255795e9833f)

- Cacti version 1.2.25 and 1.2.24 (tested)
- Environment : RHEL 7, PHP 7.3, MariaDB 10, rrdtool 1.4
- Client : Edge, Firefox, Opera

**Comment by TheWitness** [comment]
This likely has something to do with RRDtool.

**Comment by TheWitness** [comment]
Confirmed. it's totally messed up.  Have to find out how this is happening.  Session related for sure.

**Comment by TheWitness** [comment]
@accidentalyadmin, I'm just getting back to this one.  We need to do some diagnostics.  Is this always repeatable, or only from time to time?  Can you bring up the browser debug window, and go to the Network tab.  From there, select the Download link and capture the URL that is sent back to Cacti.  Post that here.

**Comment by TheWitness** [comment]
This has been fixed by @xmacan .  Can you please test @accidentalyadmin?
