### ISSUE TITLE
Incomplete certificate chain on https://files.cacti.net/

### ISSUE THREAD

**Issue by andreasstieger** [Cacti/cacti#5480]
# Describe the bug

Incomplete certificate chain on https://files.cacti.net/

## To Reproduce

https://www.ssllabs.com/ssltest/analyze.html?d=files.cacti.net

>  This server's certificate chain is incomplete. Grade capped to B. 

Also...

````
wget https://files.cacti.net/spin
e/cacti-spine-1.2.25.tar.gz
--2023-09-06 07:46:46--  https://files.cacti.net/spine/cacti-spine-1.2.25.tar.gz
Resolving files.cacti.net (files.cacti.net)... 23.166.80.12
Connecting to files.cacti.net (files.cacti.net)|23.166.80.12|:443... connected.
ERROR: cannot verify files.cacti.net's certificate, issued by ‘CN=R3,O=Let's Encrypt,C=US’:
  Unable to locally verify the issuer's authority.
To connect to files.cacti.net insecurely, use `--no-check-certificate'.
````

## Expected behavior

Full certificate chain provided. Note that some browsers cache, or even preload, intermediate certificates. So if it works in the browser does not mean it is fixed.

**Comment by netniV** [comment]
The certificate chain is provided automatically by LetsEcnrypt.  I do not believe there is anything we do about that.  Normally when SSL is being reported as incorrect, the root certificates may not have updated on the system in question.

**Comment by andreasstieger** [comment]
Actually I think you are mistaken. You chain `*.cacti.net` --> R3 --> ISRG Root X1. You need to provide the R3 intermediate. You can compare with a correctly configured server.

````
echo | openssl s_client -connect www.cacti.net:443 -showcerts
echo | openssl s_client -connect valid-isrgrootx1.letsencrypt.org:443 -showcerts
````

You seem to be using nginx. Maybe this helps https://community.letsencrypt.org/t/including-intermediate-certificates-from-letsencrypt-in-nginx-ssl-setup/142796

**Comment by cigamit** [comment]
This should be resolved now

**Comment by andreasstieger** [comment]
confirmed, thanks

**Comment by netniV** [comment]
@andreasstieger Thanks for reporting and keeping us honest.  Much appreciated.
