### ISSUE TITLE
Force ipv4 in Device Tab

### ISSUE THREAD

**Issue by Its-egner** [Cacti/cacti#5484]
If ipv6 is configured in Host System of Cacti. Cacti try to use also IPv6 to discover devices when new ones are added. Here it would be great to choose if ipv4 or ipv6 should be used.

Workaround here is disable IPv6 in Host System.

See: http://forums.cacti.net/viewtopic.php?p=292835#p292835

Greetings

**Comment by TheWitness** [comment]
Can you please screen capture the errors and post here.

**Comment by Its-egner** [comment]
So there is no error, this is a feature request. I already deactivated ipv6 in host configuration. Now it uses ipv4 only.

Greetings

**Comment by TheWitness** [comment]
Yea, well you need to be more specific.  Sorry.

**Comment by Its-egner** [comment]
Ah well. When in host ipv6 is enabled. Cacti will try connect to AAA record of a domain. For example docker02.its-egner.de.

In this case it would be great to have an option in device preferences to select either it uses ipv4 with the A record or ipv6 what is currently the default on dual stack host configiration.

I have the problem that ipv4 is correct ip in dns but ipv6 is wrong because of dyndns.

Hope that explain what i mean.

⁣Freundliche Grüße
Ronny Egner​

**Comment by TheWitness** [comment]
In what part of the interface though?  When performing what specific action?

**Comment by Its-egner** [comment]
Management -> Devices -> specific device page

⁣Freundliche Grüße
Ronny Egner​

**Comment by TheWitness** [comment]
Show the errors from the Cacti log please.

**Comment by netniV** [comment]
Cacti relies on the TCP stack of the system.  If the TCP stack is configured to utilise IPv4 as a priority over IPv6 that would also resolve the issue but allow you to have both v4 and v6 enabled at the same time.  This is a standard sysadmin problem and applies to any of the software on your system.  Most software will not offer a way to prioritise one over the other, they just rely on the system being configured as the admin intends it.

**Comment by Its-egner** [comment]
Well then is it possible to configure tcp stack to prioritise tcp v4

⁣Freundliche Grüße
Ronny Egner​

**Comment by netniV** [comment]
On a debian-based system, take a look at /etc/gai.conf and /etc/resolv.conf as I believe these may assist you.  But I would do a google search for your specific system/version.
