### ISSUE TITLE
How to extract numeric data from STRING SNMP query results

### ISSUE THREAD

**Issue by iulian-v** [Cacti/cacti#5486]
I'm trying to graph some temperatures for a device that reports them by SNMP as something like STRING: "23 C / 73 F".  VALUE/REGEXP doesn't work for XML fields of type "output" and I noticed that Cacti (I'm using version 1.2.25) seems to simply extract all digits from the string to form the numeric value, so the RRD gets updated with 2373.

Asking for a configurable way to parse SNMP STRING results (like "use all digits" or "use the first, or second, or nth group of digits) may be a bit much, but could someone please point me to the exact location of the code where this conversion is made?  Maybe I'll succeed in changing it to suit my needs (scripting is also an option, but SNMP looks more elegant)...

Thank you.

**Comment by TheWitness** [comment]
Sadly, we've not written the value output regex.  Best was to do this is through writing a simple data input method that calls the snnp_get_raw() cacti function and then post processes the data.  

If you have a number of devices of this type or a very large install, it might be safer to write it using the script server.

You can find several good examples scripts to use as a starter in the default install.

@netniV was thinking of taking up the value output regex, but likely only for 1.3+.

**Comment by iulian-v** [comment]
I'll definitely try script queries, but I'd also like to study the code that takes "23 C / 73 F" and produces 2373 before updating the RRD - could you please point me to the relevant file(s) / func(s) ?  Thank you.

**Comment by TheWitness** [comment]
If cacti is storing those digits, then you don't need to write a script, you may be able to apply a cdef to say shift the bits of the numeric value so that either centigrade or fahrenheit is returned.  I would still do it with a script though.

**Comment by TheWitness** [comment]
There is a fairly strait forward script server script:

https://github.com/Cacti/cacti/blob/1.2.x/scripts/ss_net_snmp_disk_io.php

**Comment by iulian-v** [comment]
I may have been able to work around my problem by writing a new CDEF to separate the Celsius value from the concatenation:  37C being the last C with a two-digit F, I'm dividing the SNMP value by 100 or 1000 depending on how it compares to 3799.

![image](https://github.com/Cacti/cacti/assets/144784285/d5033ea3-d50f-4fa1-aa19-d4d8da8cba57)

**Comment by TheWitness** [comment]
Going to close this then.  Good on you.
