### ISSUE TITLE
ESXi Template - Recache Assertion Failed Each Time Poller Runs

### ISSUE THREAD

**Issue by reubenfarrelly** [Cacti/cacti#5488]
I have 3 ESXi hosts, all are running:   System: VMware ESXi 8.0.1 build-22088125 VMware, Inc. x86_64  Polling them via SNMP is successful for the small number of graphs I have set up for them.

However each time these three hosts are polled, a recache assertion is logged like this:

14/Sep/2023 22:35:37 - RECACHE STATS: Poller:1 RecacheTime:6.5047 DevicesRecached:3
14/Sep/2023 22:35:32 - PCOMMAND Device[HOST - vmware-3.reub.net] NOTE: Recache Event Detected for Device
14/Sep/2023 22:35:32 - PCOMMAND Device[HOST - vmware-1.reub.net] NOTE: Recache Event Detected for Device
14/Sep/2023 22:35:31 - PCOMMAND Device[HOST - vmware-2.reub.net] NOTE: Recache Event Detected for Device
14/Sep/2023 22:35:31 - SYSTEM MAINT STATS: Time:0.00
14/Sep/2023 22:35:31 - SYSTEM DSSTATS STATS: Time:0.01 Type:HOURLY
14/Sep/2023 22:35:31 - SYSTEM STATS: Time:29.2771 Method:cmd.php Processes:1 Threads:1 Hosts:29 HostsPerProcess:29 DataSources:518 RRDsProcessed:297
14/Sep/2023 22:35:29 - POLLER: Poller[Main Poller] PID[8022] Device[HOST - vmware-3.reub.net] HT[1] DQ[ESXi - CPU] RECACHE ASSERT FAILED '9=
14/Sep/2023 22:35:27 - POLLER: Poller[Main Poller] PID[8022] Device[HOST - vmware-1.reub.net] HT[1] DQ[ESXi - CPU] RECACHE ASSERT FAILED '9=
14/Sep/2023 22:35:25 - POLLER: Poller[Main Poller] PID[8022] Device[HOST - vmware-2.reub.net] HT[1] DQ[ESXi - CPU] RECACHE ASSERT FAILED '9=

This is with the latest cacti 1.2.x git up to date as of now (fa7a29947e621d9a85eee4ae241cb80d054d2f18).  I am using cmd.php and php-8.2.10 on Gentoo x86_64.

I have attempted to rebuild the poller cache but this did not make any difference.

**Comment by TheWitness** [comment]
What is the Reindex method for these Data Queries?

**Comment by reubenfarrelly** [comment]
Re-index method is set to 'Verify All'.

I've captured some debugging for one of these device IDs which might help pinpoint the problem:

23/Sep/2023 22:55:28 - POLLER: Poller[Main Poller] PID[22888] Device[HOST - vmware-3.reub.net] DQ[ESXi - Hardware] RECACHE OID: 1.3.6.1.2.1.25.3.2.1.1.16, (assert:16 = output:16)
23/Sep/2023 22:55:28 - POLLER: Poller[Main Poller] PID[22888] Device[HOST - vmware-3.reub.net] DQ[ESXi - Hardware] RECACHE OID: 1.3.6.1.2.1.25.3.2.1.1.15, (assert:15 = output:15)
23/Sep/2023 22:55:28 - POLLER: Poller[Main Poller] PID[22888] Device[HOST - vmware-3.reub.net] DQ[ESXi - Hardware] RECACHE OID: 1.3.6.1.2.1.25.3.2.1.1.14, (assert:14 = output:14)
23/Sep/2023 22:55:28 - POLLER: Poller[Main Poller] PID[22888] Device[HOST - vmware-3.reub.net] DQ[ESXi - Hardware] RECACHE OID: 1.3.6.1.2.1.25.3.2.1.1.12, (assert:12 = output:12)
23/Sep/2023 22:55:28 - POLLER: Poller[Main Poller] PID[22888] Device[HOST - vmware-3.reub.net] DQ[ESXi - Hardware] RECACHE OID: 1.3.6.1.2.1.25.3.2.1.1.11, (assert:11 = output:11)
23/Sep/2023 22:55:28 - POLLER: Poller[Main Poller] PID[22888] Device[HOST - vmware-3.reub.net] DQ[ESXi - Hardware] RECACHE OID: 1.3.6.1.2.1.25.3.2.1.1.10, (assert:10 = output:10)
23/Sep/2023 22:55:28 - POLLER: Poller[Main Poller] PID[22888] Device[HOST - vmware-3.reub.net] DQ[ESXi - Hardware] RECACHE OID: 1.3.6.1.2.1.25.3.2.1.1.1, (assert:1 = output:1)
23/Sep/2023 22:55:28 - POLLER: Poller[Main Poller] PID[22888] Device[HOST - vmware-3.reub.net] HT[1] DQ[ESXi - CPU] RECACHE ASSERT FAILED '9=
23/Sep/2023 22:55:28 - POLLER: Poller[Main Poller] PID[22888] Device[HOST - vmware-3.reub.net] DQ[ESXi - CPU] RECACHE OID: 1.3.6.1.2.1.25.3.3.1, (assert:9 = output:)
23/Sep/2023 22:55:28 - POLLER: Poller[Main Poller] PID[22888] Device[HOST - vmware-3.reub.net] DQ[SNMP - Interface Statistics] RECACHE OID: .1.3.6.1.2.1.31.1.1.1.1.5, (assert:vmk0 = output:vmk0)
23/Sep/2023 22:55:28 - POLLER: Poller[Main Poller] PID[22888] Device[HOST - vmware-3.reub.net] DQ[SNMP - Interface Statistics] RECACHE OID: .1.3.6.1.2.1.31.1.1.1.1.4, (assert:vSwitch0 = output:vSwitch0)
23/Sep/2023 22:55:28 - POLLER: Poller[Main Poller] PID[22888] Device[HOST - vmware-3.reub.net] DQ[SNMP - Interface Statistics] RECACHE OID: .1.3.6.1.2.1.31.1.1.1.1.3, (assert:DvsPortset-0 = output:DvsPortset-0)
23/Sep/2023 22:55:28 - POLLER: Poller[Main Poller] PID[22888] Device[HOST - vmware-3.reub.net] DQ[SNMP - Interface Statistics] RECACHE OID: .1.3.6.1.2.1.31.1.1.1.1.2, (assert:vmnic1 = output:vmnic1)
23/Sep/2023 22:55:28 - POLLER: Poller[Main Poller] PID[22888] Device[HOST - vmware-3.reub.net] DQ[SNMP - Interface Statistics] RECACHE OID: .1.3.6.1.2.1.31.1.1.1.1.1, (assert:vmnic0 = output:vmnic0)
23/Sep/2023 22:55:28 - POLLER: Poller[Main Poller] PID[22888] Device[HOST - vmware-3.reub.net] RECACHE: Processing 22 items in the auto reindex cache for 'vmware-3.reub.net'.
23/Sep/2023 22:55:28 - POLLER: Poller[Main Poller] PID[22888] Device[HOST - vmware-3.reub.net] STATUS: Device 'vmware-3.reub.net' is UP.

And the SNMP polling responses:

thunderstorm ~ # snmpwalk -v 2c -c snmpaccess vmware-3 1.3.6.1.2.1.25.3.3.1
HOST-RESOURCES-MIB::hrProcessorLoad.1 = INTEGER: 10
HOST-RESOURCES-MIB::hrProcessorLoad.2 = INTEGER: 20
HOST-RESOURCES-MIB::hrProcessorLoad.3 = INTEGER: 9
HOST-RESOURCES-MIB::hrProcessorLoad.4 = INTEGER: 0
HOST-RESOURCES-MIB::hrProcessorLoad.5 = INTEGER: 6
HOST-RESOURCES-MIB::hrProcessorLoad.6 = INTEGER: 9
HOST-RESOURCES-MIB::hrProcessorLoad.7 = INTEGER: 0
HOST-RESOURCES-MIB::hrProcessorLoad.8 = INTEGER: 25
HOST-RESOURCES-MIB::hrProcessorLoad.9 = INTEGER: 3
HOST-RESOURCES-MIB::hrProcessorLoad.10 = INTEGER: 8
HOST-RESOURCES-MIB::hrProcessorLoad.11 = INTEGER: 6
HOST-RESOURCES-MIB::hrProcessorLoad.12 = INTEGER: 5
thunderstorm ~ # snmpwalk -v 2c -On -c snmpaccess vmware-3 1.3.6.1.2.1.25.3.3.1
.1.3.6.1.2.1.25.3.3.1.2.1 = INTEGER: 5
.1.3.6.1.2.1.25.3.3.1.2.2 = INTEGER: 20
.1.3.6.1.2.1.25.3.3.1.2.3 = INTEGER: 9
.1.3.6.1.2.1.25.3.3.1.2.4 = INTEGER: 0
.1.3.6.1.2.1.25.3.3.1.2.5 = INTEGER: 6
.1.3.6.1.2.1.25.3.3.1.2.6 = INTEGER: 9
.1.3.6.1.2.1.25.3.3.1.2.7 = INTEGER: 0
.1.3.6.1.2.1.25.3.3.1.2.8 = INTEGER: 25
.1.3.6.1.2.1.25.3.3.1.2.9 = INTEGER: 3
.1.3.6.1.2.1.25.3.3.1.2.10 = INTEGER: 8
.1.3.6.1.2.1.25.3.3.1.2.11 = INTEGER: 1
.1.3.6.1.2.1.25.3.3.1.2.12 = INTEGER: 5
thunderstorm ~ #

**Comment by TheWitness** [comment]
For this query, I would use OID Reindex Method of NONE unless it's a VM and you plan to add/remove cores.  Arguably, the logging could be better.  Looks like a SNMP timeout I'm thinking though.

**Comment by TheWitness** [comment]
For things like Switches/Routers where you continually make changes, relabel ports, etc. and whose `COUNTERS` reset from time to time, I would use uptime, as Cacti will attempt to remove the spikes, but for Data Queries where the data is mostly static, and the measures are `GUAGE` like CPU UT, I would go with None or Uptime just to be consistent.

**Comment by TheWitness** [comment]
For enterprise Cacti deployments, `Verify All` can never scale. I would think anyway.

**Comment by reubenfarrelly** [comment]
I've changed the Reindex method to none and that seems to have cleared up the error.  Is there a way to default (when new) the re-index type to None for specific data queries?  I don't think I've ever specifically set that setting so it would make sense to be able to have it pick a reasonable default that does not result in asserts being printed when it is first added.

**Comment by TheWitness** [comment]
@reubenfarrelly, let's close this one, and then open a feature request to be able to set the re-index method at the Device Template level.  I think that change is overdue.  There is a system default, but better in the Device Template.
