### ISSUE TITLE
Preserve option is not properly honoured when removing devices at command line

### ISSUE THREAD

**Issue by nomisunrider** [Cacti/cacti#5489]
As the subject says, the "preserve" option is not accounted for in the logic of cli\remove_graphs.php startng at line 108.
This results in "ERROR: Invalid Argument: (preserve)" and datasources are deleted.

**Comment by TheWitness** [comment]
What Cacti release is this?

**Comment by nomisunrider** [comment]
Not sure it matters, but I'm using 1.2.24.

I checked the branches and don't see any logic to handle the "preserve" option
Here is 1.2.x:
https://raw.githubusercontent.com/Cacti/cacti/1.2.x/cli/remove_graphs.php

**Comment by TheWitness** [comment]
Yea, got it now.  Not enough coffee this morning.

**Comment by TheWitness** [comment]
Check out the latest updates.

**Comment by nomisunrider** [comment]
That looks correct, thanks

**Comment by TheWitness** [comment]
Cool.  Thanks for the help.
