### ISSUE TITLE
PHP Warning:  Undefined array key "method" /  "oid_index" / "source"

### ISSUE THREAD

**Issue by infinitynet2011** [Cacti/cacti#5491]
Hello!

Cacti Version | 1.2.24
Devices	16
Graphs	1,023
--
OS AlmaLinux 9.2 
PHP 8.0.27

[root@cacti cli]# crontab -l
10 */1 * * * /usr/bin/php /var/www/html/cacti/cli/poller_reindex_hosts.php -id=all
15 */1 * * * /usr/bin/php /var/www/html/cacti/cli/poller_graphs_reapply_names.php -id=all

.[root@cacti cli]# /usr/bin/php /var/www/html/cacti/cli/poller_reindex_hosts.php --id=all
WARNING: Do not interrupt this script.  Reindexing can take quite some time
.......................PHP Warning:  Undefined array key "oid_index" in /var/www/html/cacti/lib/data_query.php on line 822
PHP Warning:  Undefined array key "oid_index" in /var/www/html/cacti/lib/data_query.php on line 822
PHP Warning:  Undefined array key "oid_index" in /var/www/html/cacti/lib/data_query.php on line 822
PHP Warning:  Undefined array key "oid_index" in /var/www/html/cacti/lib/data_query.php on line 822
PHP Warning:  Undefined array key "oid_index" in /var/www/html/cacti/lib/data_query.php on line 822
PHP Warning:  Undefined array key "oid_index" in /var/www/html/cacti/lib/data_query.php on line 822
PHP Warning:  Undefined array key "oid_index" in /var/www/html/cacti/lib/data_query.php on line 822
PHP Warning:  Undefined array key "oid_index" in /var/www/html/cacti/lib/data_query.php on line 822
PHP Warning:  Undefined array key "oid_index" in /var/www/html/cacti/lib/data_query.php on line 822
PHP Warning:  Undefined array key "oid_index" in /var/www/html/cacti/lib/data_query.php on line 822
PHP Warning:  Undefined array key "oid_index" in /var/www/html/cacti/lib/data_query.php on line 878
PHP Warning:  Undefined array key "source" in /var/www/html/cacti/lib/data_query.php on line 944
PHP Warning:  Undefined array key "method" in /var/www/html/cacti/lib/data_query.php on line 944
PHP Warning:  Undefined array key "source" in /var/www/html/cacti/lib/data_query.php on line 952
PHP Warning:  Undefined array key "method" in /var/www/html/cacti/lib/data_query.php on line 958
PHP Warning:  Undefined array key "method" in /var/www/html/cacti/lib/data_query.php on line 1159
PHP Warning:  Undefined array key "source" in /var/www/html/cacti/lib/data_query.php on line 944
PHP Warning:  Undefined array key "method" in /var/www/html/cacti/lib/data_query.php on line 944
PHP Warning:  Undefined array key "source" in /var/www/html/cacti/lib/data_query.php on line 952
PHP Warning:  Undefined array key "method" in /var/www/html/cacti/lib/data_query.php on line 958
PHP Warning:  Undefined array key "method" in /var/www/html/cacti/lib/data_query.php on line 1159
PHP Warning:  Undefined array key "source" in /var/www/html/cacti/lib/data_query.php on line 944
PHP Warning:  Undefined array key "method" in /var/www/html/cacti/lib/data_query.php on line 944
PHP Warning:  Undefined array key "source" in /var/www/html/cacti/lib/data_query.php on line 952
PHP Warning:  Undefined array key "method" in /var/www/html/cacti/lib/data_query.php on line 958
PHP Warning:  Undefined array key "method" in /var/www/html/cacti/lib/data_query.php on line 1159
PHP Warning:  Undefined array key "source" in /var/www/html/cacti/lib/data_query.php on line 944
PHP Warning:  Undefined array key "method" in /var/www/html/cacti/lib/data_query.php on line 944
PHP Warning:  Undefined array key "source" in /var/www/html/cacti/lib/data_query.php on line 952
PHP Warning:  Undefined array key "method" in /var/www/html/cacti/lib/data_query.php on line 958
PHP Warning:  Undefined array key "method" in /var/www/html/cacti/lib/data_query.php on line 1159
PHP Warning:  Undefined array key "source" in /var/www/html/cacti/lib/data_query.php on line 944
PHP Warning:  Undefined array key "source" in /var/www/html/cacti/lib/data_query.php on line 952
PHP Warning:  Undefined array key "method" in /var/www/html/cacti/lib/data_query.php on line 958
PHP Warning:  Undefined array key "method" in /var/www/html/cacti/lib/data_query.php on line 1159
PHP Warning:  Undefined array key "source" in /var/www/html/cacti/lib/data_query.php on line 944
PHP Warning:  Undefined array key "source" in /var/www/html/cacti/lib/data_query.php on line 952
PHP Warning:  Undefined array key "method" in /var/www/html/cacti/lib/data_query.php on line 958
PHP Warning:  Undefined array key "method" in /var/www/html/cacti/lib/data_query.php on line 1159
..................[root@cacti cli]# 

I can fix this?

Thanks,
Gabe

**Comment by infinitynet2011** [comment]
Hello,

I just changed the PHP Version. to 8.3.0RC2
But I have the same output.


Thanks,
Gabe

**Comment by infinitynet2011** [comment]
Hello,

With the new PHP version, I have this.

2023-09-20 13:28:15 - CMDPHP PHP ERROR Backtrace: (/graphs.php[123]:graph_management(), /graphs.php[2265]:html_header_sort_checkbox(), /lib/html.php[936]:CactiErrorHandler())
2023-09-20 13:28:15 - ERROR PHP DEPRECATED: Increment on non-alphanumeric string is deprecated in file: /var/www/html/cacti/lib/html.php on line: 936

Thanks,
Gabe

**Comment by TheWitness** [comment]
What Cacti release is this?

**Comment by infinitynet2011** [comment]
Hello 

Cacti Version	1.2.24

**Comment by TheWitness** [comment]
Can you upgrade to 1.2.25 and retry. Also verify that the XML file actually exists.

**Comment by TheWitness** [comment]
Although also that second issue looks like a separate issue can you open that one separately please?

**Comment by infinitynet2011** [comment]
Hello,

About **cron** errors, at that time, I was using cmd instead spine. Now that I changed to spine I don't see those errors anymore.

[root@cacti scripts]# /usr/bin/php /var/www/html/cacti/cli/poller_reindex_hosts.php --id=all
WARNING: Do not interrupt this script.  Reindexing can take quite some time..

[root@cacti scripts]/usr/bin/php /var/www/html/cacti/cli/poller_graphs_reapply_names.php -id=allll
WARNING: Do not interrupt this script.  Interrupting during rename can cause issues
.............................................................................................................................................


I will open a separate issue for "CMDPHP PHP ERROR Backtrace:*"


Thanks,
Gabe
