### ISSUE TITLE
[1.3 QA]  trees bug

### ISSUE THREAD

**Issue by asd0109** [Cacti/cacti#5499]
![image](https://github.com/Cacti/cacti/assets/37428027/9a32994a-7df6-4386-8493-8039a64dcabf)

i have a tree

![image](https://github.com/Cacti/cacti/assets/37428027/451c62eb-2f86-4d7b-a448-2b390a29c830)

but in graphs is empty .

![image](https://github.com/Cacti/cacti/assets/37428027/fe7cd1b1-dd8c-4159-8f94-db13ba7d2931)

you can see pic  in preview mode.

**Comment by jab60** [comment]
From screen shot 1 the tree is not published. Been there hope it helps.

**Comment by TheWitness** [comment]
Yea, you were on the preview page.  Do a full refresh and look at the right tabs.  I'll be on the preview tab.  The glyphs for the Modern and Dark themes were missing until earlier today.
