### ISSUE TITLE
Creat Graph devices TAB

### ISSUE THREAD

**Issue by cciethor** [Cacti/cacti#550]
Hi , i have 100+ devices already added to CACTI 1.1.2  , whenever i need to create graph , the device drop down menu doesn't show all the devices it shows almost 25 and i have to type the device name in the box in order to select it , same thing for viewing the graphs for the devices ?

**Comment by dsclassen** [comment]
This is an intended feature. Imagine if you had 10,000+ devices!! You would be scrolling for hours.

**Comment by cciethor** [comment]
there should be a way at least to sort or chose what to show in this drop menu .

**Comment by dsclassen** [comment]
The dropdown menu should update dynamically as you type in the first few letters of the device.
How would you propose configuring it differently? It looks to be alphabetical at the moment. At least for my setup.

**Comment by cigamit** [comment]
For 10k devices, I would hope you are using Autom8.  Right now the search is '%blah%'.  If you want, it's a simple change to make it 'blah%'.  What do you think?
