### ISSUE TITLE
[1.3 QA] Install last step error

### ISSUE THREAD

**Issue by asd0109** [Cacti/cacti#5500]
![2023-09-25 09 12 55](https://github.com/Cacti/cacti/assets/37428027/1744a5c6-9251-449f-9972-b86d250a6002)

![2023-09-25 09 13 07](https://github.com/Cacti/cacti/assets/37428027/69abe152-9393-435f-a842-0f0316c3a314)

when you finish install click "next" you will go to license page.

**Comment by bmfmancini** [comment]
Hey there

Can you post the full setup log?
Also what version of PHP are you using? 


Thanks!

**Comment by asd0109** [comment]
install is successful no error print , i use ubuntu server 22.04.3 + php 8.1 + mysql 8.0

i send  video to your email

**Comment by TheWitness** [comment]
Been spending evenings with the wife.  I'll get back to Cacti soon.

**Comment by asd0109** [comment]
Life is very important. We aren't in a hurry .

Thank you  efforts for cacti

**Comment by TheWitness** [comment]
Happens to me too...

**Comment by TheWitness** [comment]
Okay, finally had some time to spend on this.  It's not elegant, but it's solved for now.
