### ISSUE TITLE
Allow the renaming of guest and template accounts

### ISSUE THREAD

**Issue by infinitynet2011** [Cacti/cacti#5503]
Hello,

If I want to change the username (admin level), it works but the message is a bit confusing..

![Screenshot_41](https://github.com/Cacti/cacti/assets/42605037/734f11ec-1e61-45b5-a63c-4a605af1f55b)

Setup:
Cacti Version	1.2.25
PHP Version	8.3.0RC2
SQL       11.1.2-MariaDB

Thanks,

**Comment by TheWitness** [comment]
You have to set the admin user in setting to something other than admin.  Easy to simply copy the user and the disable the admin account.

**Comment by TheWitness** [comment]
I did a double check, and as a result and based upon the current design, we can change the behavior.

**Comment by TheWitness** [comment]
Okay, I decided to reverse my previous decision.  Should be resolved in the 1.2.x branch.
