### ISSUE TITLE
Cacti throws errors with most SNMPv3 Auth/Priv protocols -- "Unknown authentication protocol 'SHA256' in file: /var/www/html/cacti/lib/snmp.php on line: 110"

### ISSUE THREAD

**Issue by rst-ack** [Cacti/cacti#5504]
# Describe the bug

In version 1.2.23 and 1.2.25 (these are the only two versions I have tested, and encountered this problem with) on RHEL 8.7, creating an SNMPv3 device using any authentication protocol above SHA (i.e. SHA-224, SHA-256, SHA-392, SHA-512) and/or any privacy protocol above AES-128 (i.e. AES-192, AES-256) results in a "System SNMP error". Inspecting the logs reveals that Cacti is throwing an `Unknown authentication protocol` or `Unknown security protocol` error (respectively). Debug logs offer no additional information or steps to resolve.

## To Reproduce

PHP version: 7.2.24
DB version: MariaDB 10.3.35
SNMP version: 5.8

Steps to reproduce the behavior (for authentication protocol issue):

1. Install Cacti 1.2.23 or 1.2.25 on RHEL 8.7, according to the [official Cacti install guide](https://files.cacti.net/docs/html/unix_configure_cacti.html)
2. Progress through the initial setup wizard
3. Create a new device using the following parameters:
    1. SNMP Version: Version 3
    2. SNMP Security Level: authPriv
    3. SNMP Auth Protocol (v3): anything above SHA (i.e. SHA-224, SHA-256, SHA-392, SHA-512)
    4. SNMP Privacy Protocol (v3): DES or AES-128
5. Click Create
6. The error `System SNMP error` is displayed in the SNMP Information pane at the top of the page
7. Inspecting `cacti.log` shows the following error:

```
ERROR PHP WARNING: SNMP::setSecurity(): Unknown authentication protocol 'SHA256' in file: /var/www/html/cacti/lib/snmp.php  on line: 110
CMDPHP PHP ERROR WARNING Backtrace:  (/host.php[141]:api_device_ping_device(), /lib/api_device.php[1534]:cacti_snmp_session(), /lib/snmp.php[110]:SNMP->setSecurity(), CactiErrorHandler())
```

Steps to reproduce the behavior (for security protocol issue):

1. Install Cacti 1.2.23 or 1.2.25 on RHEL 8.7, according to the [official Cacti install guide](https://files.cacti.net/docs/html/unix_configure_cacti.html)
2. Progress through the initial setup wizard
3. Create a new device using the following parameters:
    1. SNMP Version: Version 3
    2. SNMP Security Level: authPriv
    3. SNMP Auth Protocol (v3): MD5 or SHA
    4. SNMP Privacy Protocol (v3): anything above AES-128 (i.e. AES-192, AES-256)
5. Click Create
6. The error `System SNMP error` is displayed in the SNMP Information pane at the top of the page
7. Inspecting `cacti.log` shows the following error:

```
ERROR PHP WARNING: SNMP::setSecurity(): Unknown security protocol 'AES192' in file: /var/www/html/cacti/lib/snmp.php  on line: 110
CMDPHP PHP ERROR WARNING Backtrace:  (/host.php[141]:api_device_ping_device(), /lib/api_device.php[1534]:cacti_snmp_session(), /lib/snmp.php[110]:SNMP->setSecurity(), CactiErrorHandler())
```

## Expected behavior

SNMP connections should succeed using any authentication/privacy protocol offered to the user.

## Screenshots

N/A

## Desktop (please complete the following information)

- OS: Windows 10, Windows Server 2019

- Browser: Firefox, Edge, Chrome

- Version: Latest

**Comment by TheWitness** [comment]
Uninstall php-snmp and then restart Apache. This is a known issue.  PHP is a little behind.

**Comment by rst-ack** [comment]
I haven't had time to properly test, but initially upon removing the php-snmp package and then restarting both httpd and php-fpm, it appears that the issue persisted. I'll do more testing and report back.

Out of curiosity, where is this issue documented? I didn't come across any mention of this in my research into the issue.

**Comment by TheWitness** [comment]
Right during the install.  If you are planning on using Advanced Encryption or SNMPv3, we recommend you disable PHP-SNMP.  You also should be at **Net-SNMP 5.8+**.

**Comment by TheWitness** [comment]
Also note that whomever built the Net-SNMP 5.8 which it appears you are at, may not have enabled the compiler flags to do the advanced features.  You an use the Net-SNMP man pages to see if that is the case.  So, see if things are built properly, run `man snmpcmd` and search for `-a authProtocol`.  You should see something like below:

![image](https://github.com/Cacti/cacti/assets/1439914/7a5f5aa1-f501-498b-8ca9-b3c8ed757b4b)

Although, I'm also looking at Net-SNMP 5.9.1 on my Rocky9 box, and I'm also not seeing the options from that command.  I should grumble now....

**Comment by TheWitness** [comment]
Seems like this has been reported to the net-snmp people.  You may have to use AES128 for a while.

https://github.com/net-snmp/net-snmp/issues/524
