### ISSUE TITLE
After deleting last item on page 2 from any list the Previous button is missing on nav bar

### ISSUE THREAD

**Issue by jab60** [Cacti/cacti#5506]
# Describe the bug

This bug applies to any list which uses the `html_nav_bar` function.
Edge case as it only applies when the list length changes from needing 2 pages to 1 page.
When the last list item on page 2 is deleted the page view stays on page 2 but the Previous button in the nav bar is not displayed so its tricky to get back to page 1. 

Workaround
Clicking clear on the filter bar resets the form back to page 1.

## To Reproduce

1. This was simplest to reproduce on the Color Template form but applies to any list.
2. In Settings set the list length to its min value of 10 (so you don't have to enter lots of items on the form)
3. Add new color items until you have 11 items in the list (This should display as 2 pages)
4. Go to page 2 of the list
5. Delete the item displayed so the list is now just 10 items long
6. The form header bar will update to "All 10 color templates" and the page remains on page 2 so there is nothing displayed.
7. The navigation bar has not displayed the Previous button so you can not scroll back to page 1.
8. To get back to page 1 select Clear on the filter button

## Expected behavior

The page should be forced back to page 1 (Difficult to implement?). 
OR 
Display the Previous button on the nav bar (this is similar to what happens on 3 or more pages when all items on the page are deleted)

## Screenshots

Shows page 2 with the 11th template item
![image](https://github.com/Cacti/cacti/assets/108667514/e4acaaff-9ed6-4ad4-b309-6cd437884bfc)

Now delete this item from list
![image](https://github.com/Cacti/cacti/assets/108667514/f57f660f-74cc-494c-b0eb-3ba326fa4741)

![image](https://github.com/Cacti/cacti/assets/108667514/df221286-d128-4626-989a-e50c0267180d)

## Desktop (please complete the following information)

- Server Ubuntu 22.04 - Desktop W10 
- Browser chrome Version 117.0.5938.92 (Official Build) (64-bit)
- cacti Version 1.2.25

## Smartphone (please complete the following information)

- not tested

## Additional context

Possible code fix
In file lib/html.php line 583 - to 587
replace
```
			$nav = "<div class='navBarNavigation'>
				<div class='navBarNavigationNone'>
					" . __('All %d %s', $total_rows, $object) . "
				</div>
			</div>\n";
```
with
```
                        $nav = "<div class='navBarNavigation'>
                                <div class='navBarNavigationPrevious'>
                                        " . (($current_page > 1) ? "<a href='#' onClick='goto$page_var(" . ($current_page-1) . ");return false;'><i class='fa fa-angle-double-left previous'></i>" . __('Previous'). '</a>':'') . "
                                </div>
                                <div class='navBarNavigationNone'>
                                        " . __('All %d %s', $total_rows, $object) . "
                                </div>
                                </div>\n";
```

**Comment by TheWitness** [comment]
Can you create a pull request against the 1.2.x branch.  Make sure you update the `CHANGELOG` too.

**Comment by TheWitness** [comment]
Hmm, I think this should be done a little differently.

**Comment by jab60** [comment]
I'm just tinkering whilst trying to build a plugin. Good learning curve for the PHP stuff, but finding these little issues. 
I'm happy for you to fix in whatever way you feel best suits the overall project and coding style.

**Comment by TheWitness** [comment]
You are more than welcomed and encouraged actually to contribute.  If you would like to become a volunteer for the broader team, send your bio to thewitness@cacti.net.

**Comment by TheWitness** [comment]
The fix as committed should work.
