### ISSUE TITLE
mysql folder growing big

### ISSUE THREAD

**Issue by majed17** [Cacti/cacti#5507]
in cacti 1.2.25, i migrated to another server, and now there are growing files in the mysql directory growing beyond 1GB, like cacti-bin.000009.
i made the mysql configuration before migrating as such:
```

collation-server 				= utf8mb4_unicode_ci
character-set-server			= utf8mb4
max_heap_table_size				= 64M
tmp_table_size					= 64M
innodb_file_format				= Barracuda
innodb_file_per_table			= ON
query_cache_type 				= 1
join_buffer_size				= 2M
sort_buffer_size				= 2M
innodb_buffer_pool_size 		= 1G
innodb_buffer_pool_instances	= 10
innodb_doublewrite				= OFF
innodb_flush_method				= O_DIRECT
innodb_flush_log_at_timeout		= 3
innodb_read_io_threads			= 32
innodb_write_io_threads			= 16
innodb_io_capacity				= 6000
innodb_io_capacity_max			= 11000
innodb_large_prefix				= 1
log-basename					= cacti

[mariadb]

query_cache_size			= 1288M
query_cache_type 			= 1
thread_cache_size			= 4

slow_query_log				= 1

general_log					= 0

#long_query_time			= 1

slow_query_log_file			= 	/var/log/mysql/log-slow-queries.log

log-error					= 	/var/log/mysql/mysqld.err

general_log_file			=	/var/log/mysql/mariadb.log

wait_timeout				= 200

#skip-name-resolve			= 1

max_connections				= 150

```
how to get rid of these growing cacti mysql files?

**Comment by TheWitness** [comment]
@majed17, those are binary logs.  You have to options, disable binary logging (only needed really from my perspective if you are replicating Cacti to another server), or set a binary log retention in your **server.cnf**.  You can get the documentation on mariadb.org or mysql.com.  Depending on what database you are using.

**Comment by TheWitness** [comment]
Closed this as it's a support issue...  To disable binary logging in the past, you would comment out `server_id=x` in the `server.cnf`.  I forget the variable to only keep so many hours of the binary log, but 20 minutes googling or duckducking should get you the answer.

**Comment by majed17** [comment]
thanks
