### ISSUE TITLE
[1.3 QA] Columns not resizing smaller on the Discovered Devices page right side gets truncated

### ISSUE THREAD

**Issue by jab60** [Cacti/cacti#5508]
# Describe the bug

From development version
In Chrome & Edge browser (Firefox is ok I guess the default font is slightly smaller)
The list of discovered devices is wider than my 1920X1080 monitor and cuts off the right hand cols instead of sizing the cols smaller. I can increase the browser width over 2 monitors to see the right hand cols. The cols can be increased in size and automatically resize themselves as the browser is made wider.
Its as if there is a fixed floor width for the cols and that is > 1920 pixels.
I notice 2 new cols have been added to this page after 1.2.25

## To Reproduce

1. Go to Automation>>Discovered Devices
2. Maximize the browser window and the last right hand cols are truncated.
3. If you have multiple monitors then resize the browser over 2 monitors width and the cols are visible.
4. After you get to this width then making the browser wider does resize the cols with the window

## Expected behavior

The cols should autosize to a smaller width with the main browser window

## Screenshots

Chrome Browser maximized on 1 monitor at 1920X1080 resolution. Right hand side is truncated.
![image](https://github.com/Cacti/cacti/assets/108667514/fbf6bb70-c313-47d6-a85a-797f3d5427d3)

Chrome Browser sized across 2 monitors to show all cols.
![image](https://github.com/Cacti/cacti/assets/108667514/a2e15206-40c6-465f-8e63-aa2832986a86)

Firefox browser - not maximized but this is smallest it will go before chopping off right hand cols
![image](https://github.com/Cacti/cacti/assets/108667514/0096bddc-1c90-4fef-8a09-bc10149bf782)

## Desktop (please complete the following information)

- OS: W10 22H2
- ubuntu 22.04
- cacti develop version 1.3.0 (28/9/2023)

- Browser 
- Chrome Version 117.0.5938.132 (Official Build) (64-bit)
- Firefox 118.0.1 (64-bit)

## Smartphone (please complete the following information)

- Not tested

**Comment by TheWitness** [comment]
Are you certain of the setting to constrain the width of the page?  It's one the two icons below.

This first one means keep the size and hide columns that don't fit.

![image](https://github.com/Cacti/cacti/assets/1439914/f31a9a0c-66eb-4c39-a7ed-69dd99dfa9f4)

The second one is to allow the screen to scroll horizontally.

![image](https://github.com/Cacti/cacti/assets/1439914/e91a8354-e6e5-4e91-991d-0b8c9c832ed2)

Please confirm the setting.

**Comment by jab60** [comment]
Something odd, as I cant replicate with current development version even from a clean installation.  (By the way I like the full version showing in the header bar now!)
Discovery Filters [ 1.3.0 - Dev 98195e64 @ 2023-10-01 19:21 ]

I don't recollect seeing a horizontal scroll bar in screen shot 1 and I didnt capture that part of the browser.
On first screen You cant see the constraints icon but on the second screen shot its in the hide cols mode (thats the default) so that's what it would have been in screen 1 as I didnt change it.

Even so from screenshot 1 the selection box right hand col should always be visible (It is in current version).

Close but Ill watch out in case I can repeat.

**Comment by TheWitness** [comment]
Okay, it works for me.  I'm not totally happy with some of the column bits for sure either.
