### ISSUE TITLE
[1.3 QA] Missing path separator in logged warning message about flags package

### ISSUE THREAD

**Issue by jab60** [Cacti/cacti#5509]
# Describe the bug

Warning message in cacti log - Appears to be reported once only not sure how to re-trigger it.

WEBUI WARNING: Key Cacti Include File "flag-icon.css" missing. Please locate and replace this file as we checked in "/var/www/html/cactiinclude/vendor/flag-icon-css/css/"

Note the missing path separator in cactiinclude which should be cacti/include

## To Reproduce

1. Install a new version of cacti 1.3.0
2. View log

## Expected behavior

This message should not be in the log

## Screenshots

Log message
![image](https://github.com/Cacti/cacti/assets/108667514/325a054c-e04b-49ab-bd99-29c426f9850e)

## Desktop (please complete the following information)

- OS: W10 22H2
- Chrome Version 117.0.5938.132 (Official Build) (64-bit)
- Ubuntu 22.04
- cacti develop 1.3.0

## Smartphone (please complete the following information)

- Not tested

## Additional context

This path dosent exist in a new 1.3.0 installation because the flags package has been moved and renamed. It would probably exist in an upgrade and the user could potentially then have the package twice. 

Message reported from **lib/functions.php** in `function get_theme_paths`

Both paths are referenced in **lib/html.php** under global styles in `function html_common_header`. This may just be for convenience whilst this version is developed.

```
        /* Global styles */
        print get_md5_include_css('include/fa/css/all.css');
        print get_md5_include_css('include/fa/css/fontawesome.css');
        print get_md5_include_css('include/vendor/flag-icon-css/css/flag-icon.css');   //Old path doesnt exist in new 1.3.0 install and reported missing in log
        print get_md5_include_css('include/vendor/flag-icons/css/flag-icons.css');      //New path
        print get_md5_include_css('include/themes/' . $selectedTheme .'/main.css');

```

**Comment by TheWitness** [comment]
Should be resolved now.
