### ISSUE TITLE
Tree View no longer shows interface graphs...

### ISSUE THREAD

**Issue by holbor** [Cacti/cacti#551]
At some point recently, I did a "git pull" into my environment, a database upgrade occurred, and now the tree view no longer shows any graphs except an advanced ping.  The devices have many interface graphs, and if I go to list view, they are all there, but I cannot seem to get them to show in the tree view.  Not a permissions thing.  I'm figuring it's a filter thing, but the filter is set to "All Graphs & Templates".

/rh

**Comment by reboot1983** [comment]
What branch did you pull? Are there any entries in the CLOG?
Did you refresh your browser window? (clear cache, etc.)
Do you have a printscreen of what you see?

**Comment by holbor** [comment]
root@cacti-1:/var/www/html/cacti# git branch -av
* develop                95e100f Calculating new width from adding hidden
widths
  remotes/origin/HEAD    -> origin/develop
  remotes/origin/develop 95e100f Calculating new width from adding hidden
widths
  remotes/origin/master  42c5844 Merge branch 'develop' for 1.1.1 release

Nothing in CLOG that I would not expect, no glaring errors, just down hosts
and misc snmp errors.

Yes, different browsers, different systems.




​
​

**Comment by cigamit** [comment]
This looks less of a tool issue and more like a support issue for the forms unless reboot you want to dig in?  I'm kind of busy at the moment.

**Comment by reboot1983** [comment]
@Holbor; what's the os, browser and version you're using?

**Comment by holbor** [comment]
Kubuntu 16.04 Desktop and Chrome/Firefox, and Windows 8 with Chrome.
Server is ubuntu 16.04 with latest updates as of a week or so ago.

/rh

**Comment by cigamit** [comment]
This sounds more of a Graph Permissions issue.  I will close until the author of the bug can provide better information.

**Comment by holbor** [comment]
Let me know what you would like to see?  I've got permissions on all the
graphs, and can see them fine in the list view.. they just don't show up in
the tree view.  Not sure on the process for editing the tree view now, but
the devices were all generally added via the old discovery plugin before
updating the version.  Also not sure if it matters, but in permissions, I
don't see a list of trees..

Console ->Users ->(Edit)

[image: Inline image 1]
But they show up in Console  - > Graph Trees

[image: Inline image 2]
/rh
