### ISSUE TITLE
[1.3 QA] Search icon repeats each time after clicking on a list columns constraints mode icon

### ISSUE THREAD

**Issue by jab60** [Cacti/cacti#5516]
# Describe the bug

The magnifying glass icon next to the search box repeats just to the right every time you click on the column constraints icon.
Click the search Clear button to reset view
Its also affecting a collapsed search bar as you get 1 extra export icon for each extra search icon.

## To Reproduce

Steps to reproduce the behaviour:

1. Go to 'Management>>Devices' (Seems to apply to any screen with the search bar present)
2. Click on the column constraints icon
3. See another magnifying glass icon added next to the search bar
4. Click clear to reset view

## Expected behaviour

Should only see 1 magnifying glass icon and 1 download icon

## Screenshots

The initial view is correct with just the 1 magnifying glass icon
![image](https://github.com/Cacti/cacti/assets/108667514/085ca979-10ea-4bcb-a560-8f4f6ca7f61a)

Click the column constraints icon and a second search icon appears
![image](https://github.com/Cacti/cacti/assets/108667514/b5b6d00b-8a5e-4b34-8b6e-68aab1540ab9)

Keep clicking constraints icon for more....
![image](https://github.com/Cacti/cacti/assets/108667514/b9d9e863-673c-4a04-952d-1b33a3a95c16)

Here there are 5 extra search icons
When the search bar is collapsed there are 5 extra export icons
![image](https://github.com/Cacti/cacti/assets/108667514/18348be7-58ca-4701-9165-e85eed9579eb)

## Desktop (please complete the following information)

- W10 22H2
- Chrome Version 117.0.5938.132 (Official Build) (64-bit)
- FireFox 118.0.1 (64-bit
- Ubuntu 22.04
- cacti 1.3.0 development

## Smartphone (please complete the following information)

- not tested

**Comment by TheWitness** [comment]
Do you have an plugins installed?  If not, force refresh your static content, or try to reproduce from a privacy window.

**Comment by jab60** [comment]
No plugins installed, this is a clean new install of develop branch
Repeatable in Incognito and Private browsers with both Chrome and FF
Cleared browser cached data still repeatable
Ctrl-F5 in chrome still repeatable

**Comment by TheWitness** [comment]
Are you pressing the go button, or just hitting enter in the search field?

**Comment by TheWitness** [comment]
@jab60, now that I'm actively back on develop, things will break from time to time. I'm working on two milestone projects one for scalability and the other around automation.  I will be fixing bugs as I see them.

**Comment by TheWitness** [comment]
Also, @jab60, are you installing from source?  I can not reproduce this on any browser so far.  Any JavaScript errors or warnings?  Can you do a screen2gif of the interaction (animated Gif) and post it?  Do two captures, one with the console open, and the other with the network open.  Do one test by striking ENTER, and another test by hitting the Go button.

This seams like an old issue, but again, I can not reproduce it.

**Comment by jab60** [comment]
Not the Go/Enter buttons
Im just repeatedly clicking the colum constraints button 
![image](https://github.com/Cacti/cacti/assets/108667514/7431f281-29cf-4c89-9c3a-5645fbdbc645)
then
![image](https://github.com/Cacti/cacti/assets/108667514/9586431a-187f-428c-8bae-96298becb4a4)

Video as suggested (Neat little tool ive not come across that before)
![Show multiple magnifiers](https://github.com/Cacti/cacti/assets/108667514/1444f318-869b-4635-b5dc-ad9fc821b618)

Im downloading source with git console. Just updated to 
![image](https://github.com/Cacti/cacti/assets/108667514/4372dbcf-9a37-4db3-9a44-43d074274e89)
and issue still present.

No messages in log file from tests yesterday

With latest version I get below
But I suspect that is something else you are working on unrelated.
<html>
<body>


2023-10-02 17:55:01 - CMDPHP ERROR: A DB Exec Failed!, Error: Unknown column 'data_sources' in 'field list'
--
2023-10-02 17:55:01 - SQL Backtrace: (/poller_maintenance.php[127]:update_graphs_data_source_templates_totals(), /poller_maintenance.php[165]:update_data_source_totals(), /lib/utility.php[2153]:db_execute_prepared())


</body>
</html>

**Comment by TheWitness** [comment]
This is fixed now.  You will have to clear the cache.
