### ISSUE TITLE
[1.3 QA] Cacti does not recognize the 'about' page as a console page, so its not possible to open the menu

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#5518]
# Describe the bug

Typically, people can see the 'about' page when they are on the console tab and can therefore open/close the console menu when on that page, but in the latest develop, you can not do that for some reason.

## To Reproduce

1. Login using the Modern Theme

2. Go to the Console

3. Click on the Cacti below the menu

4. Now try to click on the Console top tab, note that it will not open the console.

## Expected behavior

When on the about page, if you have access to the Console, the menu should be able to appear.  And it should not 'auto' close.

**Comment by netniV** [comment]
This seems to be resolved without a commit?

**Comment by TheWitness** [comment]
Agreed, and it's not fixed.  The console still closes and there is no way to bring it back.

**Comment by TheWitness** [comment]
Fixed here: https://github.com/Cacti/cacti/issues/5581
