### ISSUE TITLE
[1.3 QA] Tree list blank when switching from list view to tree view on Graphs display

### ISSUE THREAD

**Issue by jab60** [Cacti/cacti#5519]
# Describe the bug

The left pane tree list is not redrawn when switching from list view to tree view mode.
The tree is published.
The tree is redrawn after clicking the tree view button a second time
Ive done a Screen2gif capture to demonstrate
This is a default update to current build (but was also happening in previous dev build I just hadnt nailed it)

## To Reproduce

1. Go to 'Graphs'
2. Click on 'List view mode'
3. Click on Tree view mode <<The tree list is not drawn left panel is blank
4. Click on Tree view mode again << The tree is now displayed

## Expected behavior

The tree panel should not be left blank

## Screenshots

![Treelistmissing](https://github.com/Cacti/cacti/assets/108667514/efe10918-7e13-4dfa-a4d4-315d6bd3a485)

## Desktop (please complete the following information)

- W10 22H2
- Chrome Version 117.0.5938.132 (Official Build) (64-bit)
- FF 118.0.1
- Ubuntu 22.04
- cacti [ 1.3.0 - Dev a4d06bf1 @ 2023-10-03 17:36 ]

## Smartphone (please complete the following information)

- Not tested

## Additional context

Same effect changing from Preview mode to tree view mode
This is a default installation only has the local Linux machine as a monitored device

I got as far as following the code to include/layout.js and the call to function resizeTreePanel
It seems to fail with a timeout whilst being called if also resizing the graphs.

**Comment by TheWitness** [comment]
Any JavaScript errors?

**Comment by TheWitness** [comment]
This is resolved.  Use a cache cleaning tool to reload the `layout.js`.

**Comment by TheWitness** [comment]
I'm still having issues with this.  Have to find a way to simplify the logic.

**Comment by TheWitness** [comment]
Pretty sure it's the way I want it for now.

**Comment by jab60** [comment]
Sorry it dosent seem to have fixed for me in latest update [ 1.3.0 - Dev d5615333 @ 2023-10-05 18:20 ]
Ive definitely reloaded layout.js (included patched code in video)
Repeatable in incognito browser and private FF browser as well

![Treelistmissing(2)](https://github.com/Cacti/cacti/assets/108667514/9105a677-f023-459b-a4ac-a9be63b7a62f)

There are also a couple of not very helpful  .js errors showing at bottom of developer mode view if thats any use.
[Violation] Forced reflow while executing JavaScript took 31ms

Ill run again from a clean install later.

**Comment by netniV** [comment]
The violations occur because Chrome has a really low threshold for how long a handler should take.  This is  designed to make it so designers can see to it that a UI remains responsive but has no real baring on the functionality.
