### ISSUE TITLE
Graph selection - Cosmetic Bug

### ISSUE THREAD

**Issue by amprantino** [Cacti/cacti#552]
I am using Cacti 1.1.2. How to reproduce the bug:

When selecting graphs from a listing, yellow/grey selections are not functiong properly.
Select a device, then top right box (select all graphs) .
Now uncheck a checkbox. Line does not update (still yellow).

Best Regards
![capture](https://cloud.githubusercontent.com/assets/1978223/24896943/c48f5afa-1e9f-11e7-9855-45e89de1e5f5.JPG)

**Comment by cigamit** [comment]
That's odd, is this a data query or a graph template?

**Comment by amprantino** [comment]
None.
The screenshot is from the graphs list, under the Devices.

**Comment by cigamit** [comment]
confirmed.

**Comment by cigamit** [comment]
Resolved.  Thanks for reporting.

**Comment by amprantino** [comment]
Thank you
Waiting the new version to test
