### ISSUE TITLE
[1.3 QA] Probably missing global $config;

### ISSUE THREAD

**Issue by jkbzh** [Cacti/cacti#5521]
This function is accessing config in line 458, but it's undefined. You probably forgot to add a global $config.

Secondary issue, maybe you want to add an isset() before accessing its value.

https://github.com/Cacti/cacti/blob/a642e61ad75c9de83754309eb3a3e40391acf550/lib/rrd.php#L448

https://github.com/Cacti/cacti/blob/a642e61ad75c9de83754309eb3a3e40391acf550/lib/rrd.php#L458

**Comment by TheWitness** [comment]
Yikes.  Good catch.

**Comment by TheWitness** [comment]
Fixed here.

https://github.com/Cacti/cacti/commit/9a7c85bd8d552f5d4cc1fd63f08f7a8398ad9674

**Comment by netniV** [comment]
Has made me wonder if this should also be a CONSTANT

**Comment by TheWitness** [comment]
I was thinking the same thing, but I was in bug hunt mode and not optimize mode.

**Comment by TheWitness** [comment]
The default is `PHP_OS`

**Comment by netniV** [comment]
On another project, I have this as a constant called IS_WINDOWS, thought we had it too, but clearly I had not done that as part of my CONSTANT rework.
