### ISSUE TITLE
1.2.25 import_package give a general error 500

### ISSUE THREAD

**Issue by arno-st** [Cacti/cacti#5524]
When I try to import a package (I have no clue what it is yet)
I have an error 500

Go to management -> import/export -> Import packages

and in the log I have this:
`09/10/2023 13:33:17 - CMDPHP WARNING: Page:package_import.php Generated a Fatal Error:500--
09/10/2023 13:33:17 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
09/10/2023 13:33:17 - ERROR PHP COMPILE_ERROR: Cannot declare class  Diff, because the name is already in use in file:  /usr/share/cacti/include/vendor/phpdiff/Diff.php on line: 46
`

It's on Cacti 1.2.25, php 7.4.33

**Comment by TheWitness** [comment]
Did you install from source or a Debian package?  What other plugins are you using?

**Comment by arno-st** [comment]
Damn, that was the good question to ask!

Yes I have class Diff inside one of my plugin!
So I'm gona change the name to solve this issue.

As for the question no I install it from a from the repo

**Comment by TheWitness** [comment]
Thanks guy.
