### ISSUE TITLE
Reindex fail ? | CMDPHP ERROR: A DB Row Failed!

### ISSUE THREAD

**Issue by jhonatanrmagalhaes** [Cacti/cacti#5525]
# Describe the bug

Cant't see updated "status" or "alias" or "name" when creating a new graph, even reindexing device or reload device.

uplinks are shown as "Down" on cacti, but is actualy UP on device and snmp.

![image](https://github.com/Cacti/cacti/assets/91952246/a5b9b08e-5d58-4421-83d3-bceccc0d24f4)
IF-MIB::ifOperStatus.118161480 = INTEGER: up(1)

## To Reproduce

Disable/enable Device
Reindex Device
Verbose/Reload Query

> 2023/10/10 14:43:31 - CMDPHP SQL Backtrace:  (/remote_agent.php[72]:run_remote_data_query(), /remote_agent.php[439]:run_data_query(), /lib/data_query.php[396]:poller_push_reindex_data_to_poller(), /lib/poller.php[1905]:db_fetch_assoc_prepared(), /lib/database.php[697]:db_execute_prepared())
2023/10/10 14:43:31 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'last_updated' in 'where clause'
2023/10/10 14:43:31 - CMDPHP SQL Backtrace:  (/remote_agent.php[72]:run_remote_data_query(), /remote_agent.php[439]:run_data_query(), /lib/data_query.php[396]:poller_push_reindex_data_to_poller(), /lib/poller.php[1912]:db_fetch_assoc_prepared(), /lib/database.php[697]:db_execute_prepared())
2023/10/10 14:44:02 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'last_updated' in 'where clause'
2023/10/10 14:44:02 - CMDPHP SQL Backtrace:  (/remote_agent.php[72]:run_remote_data_query(), /remote_agent.php[439]:run_data_query(), /lib/data_query.php[396]:poller_push_reindex_data_to_poller(), /lib/poller.php[1929]:db_fetch_assoc_prepared(), /lib/database.php[697]:db_execute_prepared())
2023/10/10 14:44:11 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'last_updated' in 'where clause'
2023/10/10 14:44:11 - CMDPHP SQL Backtrace:  (/remote_agent.php[72]:run_remote_data_query(), /remote_agent.php[439]:run_data_query(), /lib/data_query.php[396]:poller_push_reindex_data_to_poller(), /lib/poller.php[1905]:db_fetch_assoc_prepared(), /lib/database.php[697]:db_execute_prepared())
2023/10/10 14:44:12 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'last_updated' in 'where clause'
2023/10/10 14:44:12 - CMDPHP SQL Backtrace:  (/remote_agent.php[72]:run_remote_data_query(), /remote_agent.php[439]:run_data_query(), /lib/data_query.php[396]:poller_push_reindex_data_to_poller(), /lib/poller.php[1912]:db_fetch_assoc_prepared(), /lib/database.php[697]:db_execute_prepared())
2023/10/10 14:44:33 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'last_updated' in 'where clause'
2023/10/10 14:44:33 - CMDPHP SQL Backtrace:  (/remote_agent.php[72]:run_remote_data_query(), /remote_agent.php[439]:run_data_query(), /lib/data_query.php[396]:poller_push_reindex_data_to_poller(), /lib/poller.php[1929]:db_fetch_assoc_prepared(), /lib/database.php[697]:db_execute_prepared())

Also some of this show up:

> 2023/10/10 14:58:14 - SPINE: Poller[3] PID[70401] PT[140380527912704] ERROR: Device[2760]: Failed to obtain a script execution lock within 30 seconds

I have 3 pollers, this is happening in only one of them.

Cacti: Version 1.2.23
Spine: 1.2.20
Mysql: 10.4.8-MariaDB
OS: Centos 7

**Comment by jhonatanrmagalhaes** [comment]
Alternative to fix this issue:
1 - Change device to diferent poller
2 - Reindex, reload query

**Comment by TheWitness** [comment]
Upgrade to 1.2.25.  There have been a number of update to Data Queries in the last several point releases.  Report back afterwards.

**Comment by TheWitness** [comment]
Also, run the audit_database.php script to confirm that your setup is 100% correct.
