### ISSUE TITLE
When upgrading, missing data source profile can cause errors to be logged

### ISSUE THREAD

**Issue by nem8** [Cacti/cacti#5527]
# Describe the bug

Upgrade from 0.8.8 to 1.2.25 (latest) fails on db upgrade somewhere between 0.8.8 to 1.0.5 due to missing data source profile id.

## To Reproduce

Upgrade from 0.8.8 to >1.0.0 and observe /var/www/html/cacti/log/cacti.log for error messages like:
`CMDPHP ERROR: A DB Exec Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE data_source_profile_id = 0' at line 1`

## Expected behavior

Expect database upgrade to complete without errors.

## Desktop (please complete the following information)

- OS: Ubuntu 22.04.3 LTS

- Browser: Firefox

- Version 118.0.1

## Additional context

We have an old cacti 0.8.8 install that we are migrating to a new server. I have set up a new server and installed all required packages. I did an mysqldump of old database and imported to new.
Installation wizard fails on updating database from 1.0.4 to 1.0.5 and after looking at the files in `/var/www/html/cacti/install/upgrades` i can see that in 1_0_0.php the table is created and in 1_0_5.php installer attempts to fetch the id from data_source_profiles but it fails and returns an empty string as the table is empty.
When grepping for data_source_profiles in all the upgrade php scripts, only the following is found:
```
1_0_0.php:	db_install_execute("CREATE TABLE IF NOT EXISTS `data_source_profiles` (
1_0_0.php:	db_install_execute("CREATE TABLE IF NOT EXISTS `data_source_profiles_cf` (
1_0_0.php:	db_install_execute("CREATE TABLE IF NOT EXISTS `data_source_profiles_rra` (
1_0_0.php:				$id = sql_save($save, 'data_source_profiles');
1_0_0.php:					db_install_execute("INSERT INTO data_source_profiles_rra
1_0_0.php:					db_install_execute("REPLACE INTO data_source_profiles_cf
1_0_5.php:	$profile_id_results = db_install_fetch_cell('SELECT id FROM data_source_profiles ORDER BY `default` DESC LIMIT 1');
```
I am not able to really understand why data_source_profiles is empty, but apparently this is a bug considering there is no fallback in 1_0_5.php in case it is..

Please advice if there is anything i can do manually to solve this.

To be noted, i also emptied host_snmp_cache as it failed on duplicate primary keys. I figured i would rerun the poller once upgrade is finished. I dont think this is relevant to the issue at hand.

**Comment by bmfmancini** [comment]
Wow that's quite the upgrade!!
Try running audit_database.php in the. Cli folder with the - - report flag
it will check the dB against the current schema and report back
There is an option to repair which will add/remove tables or columns as
needed

I would take a complete backup first though

**Comment by nem8** [comment]
Yeah its a big leap. Its a long forgotten server, set up by someone who probably left the company years ago..
As mentioned i dumped the db and im working on this upgrade on a new server so it doesnt matter if i have to nuke the db and start over a few more times, we wont lose any data.

When i run `php -f audit_database.php -- report` it results in:
`WARNING: Cacti must be upgraded first.  Use the --upgrade option to perform that upgrade`
I can see from the code that it expects the installed cacti version to match the one from the version table, however the version table is stuck at 1.0.4 as the upgrade stalled there.
```
mysql -e "use cacti; select cacti from version"
+-------+
| cacti |
+-------+
| 1.0.4 |
+-------+
```
I _could_ bypass this check but from first glance it looks like it will do changes to the database even with the report argument (?)

**Comment by TheWitness** [comment]
Go to the readme and ensure you have all the requisite params, then restart MariaDB, and the run the CLI script `upgrade_databse.php --forcever=0.8.8`

**Comment by nem8** [comment]
Hey,

Yeah i restarted the upgrade process by dropping the database and re-importing the 0.8.8 one.
The result is the same as before tho:

```
 sudo -u www-data php -q cli/upgrade_database.php
NOTE: Repairing Tables for Local Database
Upgrading from v0.8.8h
Upgrading from v0.8.8h (DB 0.8.8h) to v1.0.0
++++++++++++++++++++++++++++++++++++-++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-++++++++++++++++++++++++++++++++++++++-++++-++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++----++-++++++++++++++++++++++++++++--+++-++++-+++++++++++++++++-+-+-+-++++++-++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-Upgrading from v1.0.0 (DB 1.0.0) to v1.0.4
-Upgrading from v1.0.4 (DB 1.0.4) to v1.0.5
x+++++x+++++++++

***removed 1 error for snmp cache as i resolve this by emptying the table as mentioned in previous post***

################################
[Fail]       -   DB Exec Failed!, Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE data_source_profile_id = 0' at line 1
+------------------------------+
UPDATE data_template_data SET data_source_profile_id =  WHERE data_source_profile_id = 0
################################

```
Running it with or without forcever='0.8.8' yields the same result. My original post outlines my findings in the upgrade php scripts, and logically these are used regardless of where the upgrade is triggered from (wizard or cli) so result is the same. data_source_profile_id doesnt exist.

If someone knows what this is maybe i can set it manually, or correct an error in the script?

There is an identical case about this from 2020 where it supposedly was fixed..
https://github.com/Cacti/cacti/issues/3319

I cant seem to find the corresponding code change tho, so i dont know what was changed in that patch..

**Comment by nem8** [comment]
I looked at the git history for the upgrade script and there hasn't been any other changes done to it besides the one in 2020.
```
$profile_id_results = db_install_fetch_cell('SELECT id FROM data_source_profiles ORDER BY `default` DESC LIMIT 1');
$profile_id         = $profile_id_results['data'];
db_install_execute('UPDATE data_template_data SET data_source_profile_id = ' . $profile_id . ' WHERE data_source_profile_id = 0');
```
`data_source_profiles` is empty so it returns an empty string (or nothing).
I checked `data_source_data` and this has `no data_source_profile_id`'s other than 0:
```
mysql -e 'SELECT COUNT(data_source_profile_id) FROM cacti.data_template_data WHERE data_source_profile_id <> 0;'
+-------------------------------+
| COUNT(data_source_profile_id) |
+-------------------------------+
|                             0 |
+-------------------------------+

```

**Comment by TheWitness** [comment]
You did not follow my advice.

**Comment by TheWitness** [comment]
What is your MariaDB/MySQL version?  I was referring to this...

```sh
[mysqld]

# required for multiple language support
character-set-server = utf8mb4
collation-server = utf8mb4_unicode_ci

# Memory tunables - Cacti provides recommendations at upgrade time
max_heap_table_size = XXX
max_allowed_packet = 500M
tmp_table_size = XXX
join_buffer_size = XXX
sort_buffer_size = XXX

# important for compatibility
sql_mode=NO_ENGINE_SUBSTITUTION

# innodb settings - Cacti provides recommendations at upgrade time
innodb_buffer_pool_instances = XXX
innodb_flush_log_at_trx_commit = 2
innodb_buffer_pool_size = XXX
innodb_sort_buffer_size = XXX
innodb_doublewrite = ON

# required
innodb_file_per_table = ON
innodb_file_format = Barracuda
innodb_large_prefix = 1

# not all version support
innodb_flush_log_at_timeout = 3

# for SSD's/NVMe
innodb_read_io_threads = 32
innodb_write_io_threads = 16
innodb_io_capacity = 10000
innodb_io_capacity_max = 20000
innodb_flush_method = O_DIRECT
```

**Comment by nem8** [comment]
> You did not follow my advice.

I did, I just didn't type it out.
I went through README.MD and I verified all mariadb settings, added a few recommendations that I didn't already have and changed one that the upgrade complained about.
I can verify mariadb version when I'm at the server again, it's the one from Ubuntu repos whichever that is. Do you suspect this is a mariadb issue?

**Comment by TheWitness** [comment]
If you can send a dump of the database to `thewitness@cacti.net` I'll take a look at it.  Your call.

**Comment by netniV** [comment]
I feel we should deprecate upgrade_database in favor of the cli installer.  However, in this case, your search revealed that there are two parts that should have inserted data for profiles in your 1.0.5 update:

```
1_0_0.php:				$id = sql_save($save, 'data_source_profiles');
1_0_0.php:					db_install_execute("INSERT INTO data_source_profiles_rra
```

If you can see why these didn't occur, had any errors during your upgrade, and/or any exclusions in the outer IF statements that may have resulted in them being skipped, that would aid in understanding how to fix them.  I'm not looking at the code itself right now so this is purely from reading this issue.

**Comment by TheWitness** [comment]
Still waiting on that dump @nem8

**Comment by nem8** [comment]
Hello,
Sorry for the delay in responding. I havent had time to continue working on the issue quite yet.
Im not able to upload a dump of the database due to company policy, else i would. 
I will spend more time troubleshooting the code to see if i can get closer to pinpointing why it fails. PHP isnt a language i know very well, but it seems to be readable enough. Just need to look up the odd thing here and there..

I will have more time later this week to work on this issue and ill update here with my findings, or lack thereof..

Thanks

**Comment by TheWitness** [comment]
Is it a classic install or was it bundled with a vendor tool? Upload a screen shot of the RRA's page.

**Comment by nem8** [comment]
AFAIK its a classic install, aka its either installed from tarball or distro repo.
Its been years tho, there is no documentation for the server.
Mysql version is 5.1.7.3 for the old server, mariadb version is 10.6.12 on the new.

RRAs:
![CDViewer_niTOrwdVKJ](https://github.com/Cacti/cacti/assets/495296/3e2813ed-79ed-4df3-9eb7-457e1ed2f4c0)

**Comment by TheWitness** [comment]
Are you using the one minute RRA?

**Comment by nem8** [comment]
I dont know. Is there a way to tell if its in use?

**Comment by TheWitness** [comment]
How frequently does your poller run?  Also, for a single RRDfile, run the command below.  Post the data:

`rrdtool info $filename`

**Comment by platipusica** [comment]
Hi Team, 

I concur, there is an issue as well with 0.8.7d

This is upgrade to 1.2.25:

```
sudo -u apache php -q cli/upgrade_database.php
NOTE: Repairing Tables for Local Database
Upgrading from v0.8.7d
Upgrading from v0.8.7d (DB 0.8.7d) to v0.8.7h
++++++++++++Upgrading from v0.8.7h (DB 0.8.7h) to v0.8.8
+-++++++++++++Upgrading from v0.8.8 (DB 0.8.8) to v1.0.0
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++--x-+++++--++++++++++++++++++++-++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
################################
[Fail]       -   DB Exec Failed!, Error 1060: Duplicate column name 'id'
+------------------------------+
ALTER TABLE automation_devices ADD COLUMN id BIGINT unsigned auto_increment FIRST, ADD COLUMN network_id INT unsigned NOT NULL default '0' AFTER id, ADD COLUMN snmp_port int(10) unsigned NOT NULL DEFAULT '161' AFTER snmp_version, ADD COLUMN snmp_engine_id varchar(30) DEFAULT '' AFTER snmp_context, DROP PRIMARY KEY, ADD PRIMARY KEY(id), ADD UNIQUE INDEX ip(ip); ADD INDEX network_id(network_id), COMMENT='Table of Discovered Devices'
################################
```

MariaDB:
```
Server version: 10.3.35-MariaDB MariaDB Server
```
OS:
```
cat /etc/redhat-release
Red Hat Enterprise Linux release 8.8 (Ootpa)
```

Yes, I realize this is a big jump, however, the upgrade worked well with v1.2.23 from EPEL. Something changed big time since upgrade now is looping indefinitely with this in the install log:

```
[2023-10-25 10:19:36] [          global always  ] WARNING: One or more upgrades failed to install correctly
[2023-10-25 10:19:36] [          global always  ] Installation was started at 2023-10-25 02:19:10, completed at 2023-10-25 02:19:36
```

Upgrade to 1.2.23 worked well from 0.8.7d:
```
[2023-07-25 13:17:41] [          global always  ] Spawning background process: /usr/bin/php '/usr/share/cacti/install/background.php' 1690262261.1
678
[2023-07-25 13:17:41] [          global always  ] Setting PHP Option max_execution_time = 0
[2023-07-25 13:17:41] [          global always  ] Setting PHP Option memory_limit = -1
[2023-07-25 13:17:41] [          global always  ] Starting UPGRADE Process for v1.2.23
[2023-07-25 13:17:41] [          global always  ] Found 71 tables to convert
.
.
[2023-07-25 13:19:58] [          global always  ] Installation was started at 2023-07-25 05:17:41, completed at 2023-07-25 05:19:58
```

Upgrade to 1.2.25 from 0.8.7d:
```
[2023-10-25 10:00:37] [          global always  ] Spawning background process: /usr/bin/php '/usr/share/cacti/install/background.php' 1698199237.3
634
[2023-10-25 10:00:37] [          global always  ] Setting PHP Option max_execution_time = 0
[2023-10-25 10:00:37] [          global always  ] Setting PHP Option memory_limit = -1
[2023-10-25 10:00:37] [          global always  ] Starting UPGRADE Process for v1.2.25
.
.
[2023-10-25 10:01:05] [          global always  ] Finished UPGRADE Process for v1.2.25
[2023-10-25 10:01:05] [          global always  ] WARNING: One or more upgrades failed to install correctly
[2023-10-25 10:01:05] [          global always  ] Installation was started at 2023-10-25 02:00:37, completed at 2023-10-25 02:01:05
```

**Comment by platipusica** [comment]
> How frequently does your poller run? Also, for a single RRDfile, run the command below. Post the data:
> 
> `rrdtool info $filename`

Current v1.2.25:

```
rdtool info heads16vm_cpu_utilisation_17911.rrd
filename = "heads16vm_cpu_utilisation_17911.rrd"
rrd_version = "0003"
step = 300
last_update = 1698198905
header_size = 2456
ds[cpu_utilisation].index = 0
ds[cpu_utilisation].type = "GAUGE"
ds[cpu_utilisation].minimal_heartbeat = 600
ds[cpu_utilisation].min = 0.0000000000e+00
ds[cpu_utilisation].max = 1.0000000000e+18
ds[cpu_utilisation].last_ds = "67"
ds[cpu_utilisation].value = 3.3500000000e+02
ds[cpu_utilisation].unknown_sec = 0
rra[0].cf = "AVERAGE"
rra[0].rows = 500
rra[0].cur_row = 209
rra[0].pdp_per_row = 1
rra[0].xff = 5.0000000000e-01
rra[0].cdp_prep[0].value = NaN
rra[0].cdp_prep[0].unknown_datapoints = 0
rra[1].cf = "AVERAGE"
rra[1].rows = 600
rra[1].cur_row = 481
rra[1].pdp_per_row = 1
rra[1].xff = 5.0000000000e-01
rra[1].cdp_prep[0].value = NaN
rra[1].cdp_prep[0].unknown_datapoints = 0
rra[2].cf = "AVERAGE"
rra[2].rows = 700
rra[2].cur_row = 11
rra[2].pdp_per_row = 6
rra[2].xff = 5.0000000000e-01
rra[2].cdp_prep[0].value = 2.0696000000e+02
rra[2].cdp_prep[0].unknown_datapoints = 0
rra[3].cf = "AVERAGE"
rra[3].rows = 775
rra[3].cur_row = 476
rra[3].pdp_per_row = 24
rra[3].xff = 5.0000000000e-01
rra[3].cdp_prep[0].value = 1.1902800000e+03
rra[3].cdp_prep[0].unknown_datapoints = 0
rra[4].cf = "AVERAGE"
rra[4].rows = 797
rra[4].cur_row = 309
rra[4].pdp_per_row = 288
rra[4].xff = 5.0000000000e-01
rra[4].cdp_prep[0].value = 1.1902800000e+03
rra[4].cdp_prep[0].unknown_datapoints = 0
rra[5].cf = "MAX"
rra[5].rows = 500
rra[5].cur_row = 148
rra[5].pdp_per_row = 1
rra[5].xff = 5.0000000000e-01
rra[5].cdp_prep[0].value = NaN
rra[5].cdp_prep[0].unknown_datapoints = 0
rra[6].cf = "MAX"
rra[6].rows = 600
rra[6].cur_row = 400
rra[6].pdp_per_row = 1
rra[6].xff = 5.0000000000e-01
rra[6].cdp_prep[0].value = NaN
rra[6].cdp_prep[0].unknown_datapoints = 0
rra[7].cf = "MAX"
rra[7].rows = 700
rra[7].cur_row = 568
rra[7].pdp_per_row = 6
rra[7].xff = 5.0000000000e-01
rra[7].cdp_prep[0].value = 7.4620000000e+01
rra[7].cdp_prep[0].unknown_datapoints = 0
rra[8].cf = "MAX"
rra[8].rows = 775
rra[8].cur_row = 705
rra[8].pdp_per_row = 24
rra[8].xff = 5.0000000000e-01
rra[8].cdp_prep[0].value = 9.5240000000e+01
rra[8].cdp_prep[0].unknown_datapoints = 0
rra[9].cf = "MAX"
rra[9].rows = 797
rra[9].cur_row = 657
rra[9].pdp_per_row = 288
rra[9].xff = 5.0000000000e-01
rra[9].cdp_prep[0].value = 9.5240000000e+01
rra[9].cdp_prep[0].unknown_datapoints = 0
```

What I mean by looping is after install finishes, the next visit to cacti starts installer again.
For me, the poller does not run atm.
```
After upgrade to 1.2.25:

mysql -e "use cacti; select cacti from version" -p
Enter password: 
+--------+
| cacti  |
+--------+
| 0.8.8h |
+--------+
```

**Comment by TheWitness** [comment]
Yea, that's what I was afraid of.  The old RRA definitions left people wanting to move to 1 minute polling setting up a defective RRDfile stack since they did not really know what they were doing which in turn led to a bunch of graphs that only updated for months instead of years, and real trouble for us.

I guess what I could do in the 1.2.x code is to detect this and force a profile set on the user.  The challenge there is it would likely be wrong or maybe wrong anyway.

However, after your upgrade, the right thing to do would be to move all the old RRDfiles into a backup directory and let the new ones be created, once they are created, then use the `splice_rrd.php` cli script to bring your old data into the new RRDfiles.  Otherwise, you will just persist the mess.  This is something that normally I would have done in a consulting engagement, but my options there this day (besides the availability of my time) make my options there that limited.

How are your scripting skills?  This is actually not that difficult to pull off, but if you scripting skills are shite, there could be some issues and I can not handhold.  How many RRDfiles do you have?  Let me know.

```sh
cd /var/www/html/cacti/rra
find . -print | wc -l
```

**Comment by TheWitness** [comment]
@platipusica, the issue you saw was that the system you upgraded the second time included the autom8 plugin.  Those errors would not have otherwise occurred.  When the autom8 plugin was merged, we only use one version of the plugin as the baseline.  I guess the version you were using had already addressed the lack of a primary key.  I suspect someone familiar with the database schema could hack around this don't you think?

**Comment by TheWitness** [comment]
@nem8, I found the bug.  It's real.  Pushing a fix to the 1.2.x branch in a few minutes.

**Comment by TheWitness** [comment]
Fixed now.  Just update the file 1_0_5.php from the 1.2.x branch and force the upgrade again.  Let us know if there are more issues.  The automation issue from @platipusica, he/she should be able to resolve independently.

**Comment by nem8** [comment]
@TheWitness nice! Sorry I've been radio silence this week. I got swamped in another project and life.. I will get back to this next week and I'll try the new upgrade file.

**Comment by TheWitness** [comment]
Going to mark it closed.  1.2.26 should be out before too long.  Some pretty big customers are using it without issue right now.
