### ISSUE TITLE
[1.3 QA] Add automation network generated undefined variable error in log

### ISSUE THREAD

**Issue by jab60** [Cacti/cacti#5528]
# Describe the bug

Error is raised only when adding a new network not when editing an existing network

## To Reproduce

1. Go to 'Automation>>Networks'
2. Click on '+' to add a new network (Dont need to define it)
3. Now view the cacti log and see message 
ERROR PHP WARNING: Undefined variable $network in file: /var/www/html/cacti/automation_networks.php on line: 1266

## Expected behavior

No error

## Screenshots

Error log message
![image](https://github.com/Cacti/cacti/assets/108667514/b3256df9-9b29-40bb-bf49-98e2baa0ba26)

## Desktop (please complete the following information)

- W10 22H2
- Chrome
- Ubuntu 22.04
- cacti 1.3.0 development build [ 1.3.0 - Dev de9aa0c2 @ 2023-10-11 17:09 ]

## Smartphone (please complete the following information)

- N/A

**Comment by TheWitness** [comment]
Thanks @jab60.  Sort of back at it this weekend.  Today anyway.
