### ISSUE TITLE
[1.3 QA] Tooltip hints not popping up on any form

### ISSUE THREAD

**Issue by jab60** [Cacti/cacti#5529]
# Describe the bug

When clicking or hovering over the ? icon for input field help and on any form the hint text does not pop up

## To Reproduce

1. Go to any form with user enterable fields
2. Hover over the tool hint ? icon
3. The hint is not displayed

## Expected behavior

The field tool tip hint should be displayed

## Screenshots

![image](https://github.com/Cacti/cacti/assets/108667514/c62f0033-5dc5-4a7a-b214-1f06de3d8525)

## Desktop (please complete the following information)

- W10 22H2
- Chrome and Firefox
- Ubuntu 22.04
- cacti 1.3.0 develop

## Smartphone (please complete the following information)

- N/A
## Additional context

In the browser developer console it indicates an issue in layout.js with the HtmlSanitizer object not defined

**Comment by TheWitness** [comment]
I might have missed a commit.  Any JavaScript errors?

**Comment by TheWitness** [comment]
Hehe, never mind.  That would be a yes!

**Comment by TheWitness** [comment]
Fixed.
