### ISSUE TITLE
Aggregated graph does not belong to host

### ISSUE THREAD

**Issue by amprantino** [Cacti/cacti#553]
When I create an aggregate host, it doesn't belong to any host.
So, if I create a leaf having all graphs belonging to a host, the aggregated graph is not included.
In addition, I cannot add it manually inside the same leaf

Please check the image:

![capture](https://cloud.githubusercontent.com/assets/1978223/24907216/f3ae0736-1ec3-11e7-83b3-dcf55c27bf42.JPG)

cacti version 1.1.2

**Comment by cigamit** [comment]
This is an enhancement.

**Comment by cigamit** [comment]
This is resolved now, but only for Tree's and Reports.  Not for preview mode.
