### ISSUE TITLE
[1.3 QA] Error php depreciated parameter to file_exists on initial run

### ISSUE THREAD

**Issue by jab60** [Cacti/cacti#5530]
# Describe the bug

From a clean new install get PHP error in log
ERROR PHP DEPRECATED: file_exists(): Passing null to parameter #1 ($filename) of type string is deprecated in file: /var/www/html/cacti/lib/poller.php on line: 132

## To Reproduce

Perform a clean new installation
View log to see errors

## Screenshots
![image](https://github.com/Cacti/cacti/assets/108667514/b96cbe68-b24e-4b34-8f96-bdef20ca9885)

## Desktop (please complete the following information)

- W10 22H2
- Ubuntu 22.04
- cacti 1.3.0 develop
- PHP 8.1.2-1ubuntu2.14
- Chrome
- 
## Smartphone (please complete the following information)

- N/A

**Comment by jab60** [comment]
Maybe also a logic issue in file_exists_2gb as in strict PHP mode this returns true when $filename==null
I copied the code functions out to a quick test file (run on ubuntu)

```
<?php
#declare(strict_types=1);

$config['cacti_server_os'] = 'lnux';

#$fname = "cacti.sql";  //pass in both modes
#$fname = "toast";      //no action in both modes

$fname = null;          //in strict_type mode this raises an exception
                        //Not strict mode then file_exists_2gb returns true

print("parameter='" . $fname . "'\n");
exec_background($fname);

function file_exists_2gb($filename) {
        global $config;

        $rval = 0;

        if ($config['cacti_server_os'] != 'win32') {
                system("test -f $filename", $rval);

                return ($rval == 0);
        } else {
                return 0;
        }
}

function exec_background($filename) {

        if (file_exists($filename)) {
                print(__FUNCTION__ . " :file_exists is true\n");
        } elseif (file_exists_2gb($filename)) {
                print(__FUNCTION__ . " :file_exists_2gb is true\n");
        }
}

```
-----------------------------------------------------
At the bash shell
# when the file does exist
test -f "cacti.sql" && echo "true" || echo "false"
true

# when the file does not exist
test -f "toast" && echo "true" || echo "false"
false

# with an empty file name
test -f "" && echo "true" || echo "false"
false

# with a null file name
test -f  && echo "true" || echo "false"
true

**Comment by TheWitness** [comment]
This is a timing issue.  You re-installed and you started cactid before the php binary path was set.  However, I made two corrections to attempt to mask the issue.

**Comment by TheWitness** [comment]
That `file_exists_2g()` function should be deprecated and removed.  It's likely not been relevant for over 18 years.

**Comment by TheWitness** [comment]
This is wrong too...

`$config['cacti_server_os'] = 'lnux';`

**Comment by netniV** [comment]
```
 return ($rval == 0);
```
This is also wrong, because you can get `false` or `null` back which would also equate to 0.

**Comment by TheWitness** [comment]
For 1.3, we should just remove this function.
