### ISSUE TITLE
rewrite_index works in debug query but poller shows incorrect OID

### ISSUE THREAD

**Issue by tomkivlin** [Cacti/cacti#5535]
# Describe the bug

I've created an SNMP Query XML file, as follows:

```xml
<outlet>
        <name>Get PDU Outlets</name>
        <description>Queries a PDU for a list of Outlets</description>
        <oid_index>.1.3.6.1.4.1.13742.6.3.5.3.1.2.1</oid_index>
        <oid_num_indexes>.1.3.6.1.4.1.13742.6.3.2.2.1.4.1</oid_num_indexes>
        <index_order>outletIndex</index_order>
        <index_order_type>numeric</index_order_type>

        <fields>
                <outletIndex>
                        <name>Index</name>
                        <method>walk</method>
                        <source>value</source>
                        <direction>input</direction>
                        <oid>.1.3.6.1.4.1.13742.6.3.5.3.1.2.1</oid>
                </outletIndex>
                <outletLabel>
                        <name>Label</name>
                        <method>walk</method>
                        <source>value</source>
                        <direction>input</direction>
                        <oid>.1.3.6.1.4.1.13742.6.3.5.3.1.3.1</oid>
                </outletLabel>
                <outletPower>
                        <name>ActivePower</name>
                        <method>get</method>
                        <source>value</source>
                        <direction>input-output</direction>
                        <rewrite_index>|query_outletIndex|</rewrite_index>
                        <oid>.1.3.6.1.4.1.13742.6.5.4.3.1.4.1</oid>
                        <oid_suffix>5</oid_suffix>
                </outletPower>
        </fields>
</outlet>
```

The data query debug on the device seems to work fine, and as expected:

> Total: 0.260000, Delta: 0.000000, Located input field 'outletPower' [get]
> --
> Executing  SNMP get for 24 oids (.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.1.5,  .1.3.6.1.4.1.13742.6.5.4.3.1.4.1.2.5,  .1.3.6.1.4.1.13742.6.5.4.3.1.4.1.3.5,  .1.3.6.1.4.1.13742.6.5.4.3.1.4.1.4.5,  .1.3.6.1.4.1.13742.6.5.4.3.1.4.1.5.5,  .1.3.6.1.4.1.13742.6.5.4.3.1.4.1.6.5,  .1.3.6.1.4.1.13742.6.5.4.3.1.4.1.7.5,  .1.3.6.1.4.1.13742.6.5.4.3.1.4.1.8.5,  .1.3.6.1.4.1.13742.6.5.4.3.1.4.1.9.5,  .1.3.6.1.4.1.13742.6.5.4.3.1.4.1.10.5,  .1.3.6.1.4.1.13742.6.5.4.3.1.4.1.11.5,  .1.3.6.1.4.1.13742.6.5.4.3.1.4.1.12.5,  .1.3.6.1.4.1.13742.6.5.4.3.1.4.1.13.5,  .1.3.6.1.4.1.13742.6.5.4.3.1.4.1.14.5,  .1.3.6.1.4.1.13742.6.5.4.3.1.4.1.15.5,  .1.3.6.1.4.1.13742.6.5.4.3.1.4.1.16.5,  .1.3.6.1.4.1.13742.6.5.4.3.1.4.1.17.5,  .1.3.6.1.4.1.13742.6.5.4.3.1.4.1.18.5,  .1.3.6.1.4.1.13742.6.5.4.3.1.4.1.19.5,  .1.3.6.1.4.1.13742.6.5.4.3.1.4.1.20.5,  .1.3.6.1.4.1.13742.6.5.4.3.1.4.1.21.5,  .1.3.6.1.4.1.13742.6.5.4.3.1.4.1.22.5,  .1.3.6.1.4.1.13742.6.5.4.3.1.4.1.23.5,  .1.3.6.1.4.1.13742.6.5.4.3.1.4.1.24.5)
> Found result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.1.5' [value='105']
> Found result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.2.5' [value='182']
> Found result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.3.5' [value='157']
> Found result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.4.5' [value='340']
> Found result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.5.5' [value='101']
> Found result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.6.5' [value='0']
> Found result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.7.5' [value='90']
> Found result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.8.5' [value='354']
> Found result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.9.5' [value='343']
> Found result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.10.5' [value='121']
> Found result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.11.5' [value='111']
> Found result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.12.5' [value='0']
> Found result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.13.5' [value='262']
> Found result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.14.5' [value='225']
> Found result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.15.5' [value='205']
> Found result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.16.5' [value='217']
> Found result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.17.5' [value='161']
> Found result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.18.5' [value='0']
> Found result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.19.5' [value='13']
> Found result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.20.5' [value='105']
> Found result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.21.5' [value='136']
> Found result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.22.5' [value='4']
> Found result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.23.5' [value='48']
> Found result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.24.5' [value='0']
> Setting result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.1.5' [key='0', value='105']
> Setting result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.2.5' [key='1', value='182']
> Setting result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.3.5' [key='2', value='157']
> Setting result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.4.5' [key='3', value='340']
> Setting result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.5.5' [key='4', value='101']
> Setting result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.6.5' [key='5', value='0']
> Setting result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.7.5' [key='6', value='90']
> Setting result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.8.5' [key='7', value='354']
> Setting result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.9.5' [key='8', value='343']
> Setting result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.10.5' [key='9', value='121']
> Setting result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.11.5' [key='10', value='111']
> Setting result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.12.5' [key='11', value='0']
> Setting result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.13.5' [key='12', value='262']
> Setting result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.14.5' [key='13', value='225']
> Setting result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.15.5' [key='14', value='205']
> Setting result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.16.5' [key='15', value='217']
> Setting result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.17.5' [key='16', value='161']
> Setting result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.18.5' [key='17', value='0']
> Setting result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.19.5' [key='18', value='13']
> Setting result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.20.5' [key='19', value='105']
> Setting result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.21.5' [key='20', value='136']
> Setting result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.22.5' [key='21', value='4']
> Setting result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.23.5' [key='22', value='48']
> Setting result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.24.5' [key='23', value='0']
> Got SNMP get result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.1.5' [value='105'] (index: 1)
> Got SNMP get result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.2.5' [value='182'] (index: 2)
> Got SNMP get result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.3.5' [value='157'] (index: 3)
> Got SNMP get result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.4.5' [value='340'] (index: 4)
> Got SNMP get result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.5.5' [value='101'] (index: 5)
> Got SNMP get result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.6.5' [value='0'] (index: 6)
> Got SNMP get result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.7.5' [value='90'] (index: 7)
> Got SNMP get result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.8.5' [value='354'] (index: 8)
> Got SNMP get result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.9.5' [value='343'] (index: 9)
> Got SNMP get result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.10.5' [value='121'] (index: 10)
> Got SNMP get result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.11.5' [value='111'] (index: 11)
> Got SNMP get result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.12.5' [value='0'] (index: 12)
> Got SNMP get result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.13.5' [value='262'] (index: 13)
> Got SNMP get result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.14.5' [value='225'] (index: 14)
> Got SNMP get result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.15.5' [value='205'] (index: 15)
> Got SNMP get result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.16.5' [value='217'] (index: 16)
> Got SNMP get result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.17.5' [value='161'] (index: 17)
> Got SNMP get result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.18.5' [value='0'] (index: 18)
> Got SNMP get result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.19.5' [value='13'] (index: 19)
> Got SNMP get result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.20.5' [value='105'] (index: 20)
> Got SNMP get result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.21.5' [value='136'] (index: 21)
> Got SNMP get result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.22.5' [value='4'] (index: 22)
> Got SNMP get result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.23.5' [value='48'] (index: 23)
> Got SNMP get result for data @ '.1.3.6.1.4.1.13742.6.5.4.3.1.4.1.24.5' [value='0'] (index: 24)
> Total: 0.340000, Delta: 0.080000, Checking for Sort Field change.  No changes detected.
> Total: 0.340000, Delta: 0.000000, Update Data Query Sort Cache complete
> Total: 0.340000, Delta: 0.000000, Found 1 Local Data ID's to Verify
> Total: 0.340000, Delta: 0.000000, Verification of 1 Local Data ID's Complete
> Total: 0.340000, Delta: 0.000000, Index Association with Local Data complete
> Total: 0.350000, Delta: 0.010000, No Index Changes Detected, Skipping Re-Index and Poller Cache Re-population
> Total: 0.350000, Delta: 0.000000, Automation Executing for Data Query complete
> Total: 0.350000, Delta: 0.000000, Plugin hooks complete

But, in the cacti.log I see the following:

`2023-10-17 14:55:00 - POLLER: Poller[1] PID[2884] Device[2] DS[79] TT[0.96] SNMP: v2: 192.168.243.146, dsname: active_power, oid: .1.3.6.1.4.1.13742.6.5.4.3.1.4.1.1..5, output: U`

And the graph shows no output and NaN for MIN/MAX/AVERAGE (the graph debug has no issues/errors).

## To Reproduce

1. Add above XML to `resource/snmp_queries/pdu.xml`
2. Create Data Query pointing at above file, using "Get SNMP Data (Indexed" method
3. Associate this Data Query to the device and run a verbose query (to get the first output)

## Expected behavior

I expect the poller to behave in the same way as the SNMP query debug output, with a value per index.

## Screenshots

n/a

## Desktop (please complete the following information)

n/a

## Smartphone (please complete the following information)

n/a

## Additional context

I'm running Cacti v1.2.25 on Ubuntu 20.04.4.

**Comment by tomkivlin** [comment]
Update:

I recreated everything (Data Query, Data Source, Templates, etc.) and now it works.  I don't know if therefore this isn't a bug, or at least not what I posted about.  I wonder if there is something I wasn't aware with when updating the XML query files and maybe the poller wasn't using the same query as the debug.

**Comment by TheWitness** [comment]
Okay, good to know.
