### ISSUE TITLE
[CACTI 1.2.25] latest source - htmlsanitizer.js is missing

### ISSUE THREAD

**Issue by anarkia1976** [Cacti/cacti#5536]
Hi @TheWitness,

i have this error after latest 1.2.25 source merge:

WARNING: Key Cacti Include File /var/www/html/cacti/include/js/HtmlSanitizer.js missing. Please locate and replace this file.

thanks a lot. stefano.

**Comment by TheWitness** [comment]
For now, just edit lib/html.pho and remove that line.  Will fix that after I get back from to the office. @netniV FYI.

**Comment by TheWitness** [comment]
I've removed it here for now.  It's coming back when the security incident is closed.  Will be a part of the 1.2.26 release.

https://github.com/Cacti/cacti/commit/234a4c672db5c0f7707f4ebbcefb1ce433882daf
