### ISSUE TITLE
Cacti device status broken when the device does not have a graph. Cannot create graph for down device.

### ISSUE THREAD

**Issue by jdcoats** [Cacti/cacti#5537]
I have a hundreds of ping only devices. I noticed today that some were down but cacti never said they were down. The status still says up. In troubleshooting, I created 2 new ping only devices one that is up and one that is down. Both devices stay in an Unknown state in Cacti, never brings them to up or down status. I created a ping graph for the up device and then Cacti shows it up. I try to create a graph for the down device but cannot due to invalid data. I should be able to add a device and it show up/down regardless of having a graph for the device or not. Down device detection should stilI work if devices do not have graphs. I should be able to create a ping graph for a device whether it is up or not.

**Comment by jdcoats** [comment]
If it is helpful, It appears this broke mid August. I don't have any Timeclocks Down/Up since 8/14 . They are all stuck in an Up state.  When i run rebuild_poller_cache.php it completes in less than a minute where normal was 10mintes or so. In cacti log I see
```
2023/10/20 11:32:02 - PUSHOUT Child Started Process 5 with 361 hosts, from: 1444
2023/10/20 11:32:02 - PUSHOUT Child Started Process 3 with 361 hosts, from: 722
2023/10/20 11:32:02 - PUSHOUT Child Started Process 4 with 361 hosts, from: 1083
2023/10/20 11:32:02 - PUSHOUT Child Started Process 1 with 361 hosts, from: 0
2023/10/20 11:32:02 - PUSHOUT Child Started Process 2 with 361 hosts, from: 361
2023/10/20 11:32:02 - PUSHOUT WARNING: Deprecated script push_out_hosts.php. Please use rebuild_poller_cache.php.
2023/10/20 11:32:02 - PUSHOUT WARNING: Deprecated script push_out_hosts.php. Please use rebuild_poller_cache.php.
2023/10/20 11:32:02 - PUSHOUT WARNING: Deprecated script push_out_hosts.php. Please use rebuild_poller_cache.php.
2023/10/20 11:32:02 - PUSHOUT WARNING: Deprecated script push_out_hosts.php. Please use rebuild_poller_cache.php.
2023/10/20 11:32:02 - PUSHOUT WARNING: Deprecated script push_out_hosts.php. Please use rebuild_poller_cache.php.
```

**Comment by TheWitness** [comment]
Yea, that warning should not be there @jdcoats .  It's the preferred way IMNSHO.

**Comment by jdcoats** [comment]
Yeah, this seems to be a serious bug. But current state is both cacti and mactrack are broken.

**Comment by TheWitness** [comment]
We did make a logic change a few releases ago to 'optimize' things.  I guess they must have been sub-optimal.

**Comment by TheWitness** [comment]
Can you describe the event in question @jdcoats?

**Comment by jdcoats** [comment]
I thought my description in the report was clear. What more do you need? I worked around the issue by 1st creating a single ping graph for all ping only devices that were up. Then the 5 devices that were down I changed to an ip that answered a ping then created a ping graph then switched the ip back to the real down ip and they went to down state

**Comment by jdcoats** [comment]
Short answer is ping device without graph does not go down in cacti and can’t create ping graph for a device that is down

**Comment by TheWitness** [comment]
That's been a spine thing for years @jdcoats.  That would be a spine bug.

**Comment by TheWitness** [comment]
Oh, and second bit is there is a new Graph Template testing option to "Test Source".  Uncheck that in the Graph Template.

**Comment by TheWitness** [comment]
Here is the setting...

![image](https://github.com/Cacti/cacti/assets/1439914/75b22544-f2e7-4c98-883d-4c9320f6214c)

**Comment by jdcoats** [comment]
okay, this just started with some changes in August. I've always had these devices without graphs (no need to add disk IO creating graphs for them) but now it is required for them to show up/down in Cacti.

**Comment by TheWitness** [comment]
Did you switch from cmd.php to spine?  cmd.php has always pinged even if there were no data sources.

**Comment by jdcoats** [comment]
Always spine

**Comment by TheWitness** [comment]
What was the last version of spine that you were working with, before August?

**Comment by jdcoats** [comment]
~/cacti/1.2.x/spine # ls -alh
total 151K
drwxr-xr-x 4 root root  152 Oct 20 10:24 .
drwxr-xr-x 4 root root   96 Oct 20  2020 ..
-rw-r--r-- 1 root root 146K Oct 20 10:24 1.2.x.zip
drwxr-xr-x 8 root root 1.8K Oct 20 10:25 spine-1.2.x
drwxr-xr-x 8 root root 1.8K Aug 25 08:16 spine-1.2.x.previous

I'm not sure that the aug25 build was good, I think august 25 may be the build that broke it. I could confirm that i guess. I dont have whatever build date was before that.

**Comment by jdcoats** [comment]
Can you reproduce this? add ping device that is down (any ip)... Does Cacti show it down or just stay in unknown state? Then any existing device that is up (without a graph) change the IP to an IP that is down, does it stay up in Cacti? Then when you create a unix ping graph does it work as expected?

**Comment by TheWitness** [comment]
```sh
./spine --version
```

**Comment by jdcoats** [comment]
SPINE 1.2.25  Copyright 2004-2023 by The Cacti Group
but like i showed above its from 1.2.x Oct 20

**Comment by jdcoats** [comment]
Thanks, it appears things are working as expected now. I can't move this to spine but I assume you can.

**Comment by xmacan** [comment]
Tested, works fine, closing
