### ISSUE TITLE
How to remove the number after the port name above the traffic graph？

### ISSUE THREAD

**Issue by aliuzzz** [Cacti/cacti#5539]
![image](https://github.com/Cacti/cacti/assets/43594093/302de849-960f-4044-8ecc-c1bb30fd01b9)

This is my graph name
Actually, these two ports should be GigabitEthernet0/0/17 and GigabitEthernet0/0/18，I don't know how the suffixes ”18“ and ”22“ come from, how can they not be displayed

**Comment by xmacan** [comment]
Try to Console - > graphs -> select your graphs and Reappy Suggested Names

**Comment by cigamit** [comment]
This isn't a bug.  Please ask support questions on the forums.  https://forums.cacti.net

**Comment by TheWitness** [comment]
Correct.  The Data Query picks the best name for the Graph base upon a set of matching patterns.
