### ISSUE TITLE
Missing scrollbar

### ISSUE THREAD

**Issue by amprantino** [Cacti/cacti#554]
A scrollbar is missing ....

![capture](https://cloud.githubusercontent.com/assets/1978223/24908841/657a1188-1eca-11e7-95f4-8b7d8a32b359.JPG)

Probably this applies to all lists

cacti version 1.1.2

**Comment by cigamit** [comment]
![scrollbars](https://cloud.githubusercontent.com/assets/957322/24935484/0718f082-1ee8-11e7-848a-839a8fb1ab67.PNG)

Not an issue.

**Comment by amprantino** [comment]
Can this be a problem of the default theme?
