### ISSUE TITLE
What are the common causes of this situation

### ISSUE THREAD

**Issue by aliuzzz** [Cacti/cacti#5547]
A few days ago, I added a device and was able to obtain monitoring data. Today, I added a few plugins, deleted them, and added an additional machine, which made it impossible to display the image.
I did not modify any other configurations, and there were no errors in the logs
![image](https://github.com/Cacti/cacti/assets/43594093/d7daf7d0-a2ab-4f9c-a897-ddd91b80fc30)

**Comment by TheWitness** [comment]
What's your language and OS?

**Comment by aliuzzz** [comment]
Centos 8 ,chinese,
I try to enter graphics debug mode，it says
![image](https://github.com/Cacti/cacti/assets/43594093/10094fa0-c768-4b27-8efb-c61fe9dc47bd)
Is it a problem with rrdtool?My rrdtool version is 1.7.2
I switched the graphic formats svg and png, and re-adding them did not return to normal.
It looks like it can't create the graph, but my folder permissions are all there because the previously added device keeps showing the image

**Comment by TheWitness** [comment]
Is your poller running?

**Comment by TheWitness** [comment]
No feedback.
