### ISSUE TITLE
DSSTATS SQL insert into data_source_stats_hourly_cache has an error

### ISSUE THREAD

**Issue by kaf3773** [Cacti/cacti#555]
I am testing Cacti-1.1.2 using MariaDB 10.1.21 with Spine-1.1.2 and finding 

Minor syntax error in SQL for DSSTATS insert which i believe is causing poller threads to hang hence spinning a lot more poller_dsstats.php instances.

`CMDPHP SQL Backtrace: (/poller.php: 537 process_poller_output)(/lib/poller.php: 491 dsstats_poller_output)(/lib/dsstats.php: 696 db_execute)(/lib/database.php: 113 db_execute_prepared)(/lib/database.php: 178 cacti_debug_backtrace)

CMDPHP ERROR: A DB Exec Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '), (21400, 'cpu_system', '2017-04-11 15:36:32', ), (21401, 'cpu_user', '2017-04-' at line 1

DBCALL ERROR: A DB Exec Failed!, Error:1064, SQL:"INSERT INTO data_source_stats_hourly_cache (local_data_id, rrd_name, time, `value`) VALUES (21399, 'cpu_idle', '2017-04-11 15:36:32', ), (21400, 'cpu_system', '2017-04-11 15:36:32', ), (21401, 'cpu_user', '2017-04-11 15:36:32', ), (21408, 'n_calls', '2017-04-11 15:36:32', 1382), (21408, 'n_mem', '2017-04-11 15:36:32', 2677984), (21657, 'n_calls', '2017-04-11 15:36:32', 1371) ON DUPLICATE KEY UPDATE `value`=VALUES(`value`)'`

I am also getting these for a different table

`CMDPHP SQL Backtrace: (/poller.php: 537 process_poller_output)(/lib/poller.php: 491 dsstats_poller_output)(/lib/dsstats.php: 700 db_execute)(/lib/database.php: 113 db_execute_prepared)(/lib/database.php: 178 cacti_debug_backtrace)

CMDPHP ERROR: A DB Exec Failed!, Error: Column 'value' cannot be null

DBCALL ERROR: A DB Exec Failed!, Error:1048, SQL:"INSERT INTO data_source_stats_hourly_last (local_data_id, rrd_name, `value`, calculated) VALUES (30642, '', NULL, NULL) ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `calculated`=VALUES(`calculated`)'

CMDPHP SQL Backtrace: (/poller.php: 537 process_poller_output)(/lib/poller.php: 491 dsstats_poller_output)(/lib/dsstats.php: 696 db_execute)(/lib/database.php: 113 db_execute_prepared)(/lib/database.php: 178 cacti_debug_backtrace)

CMDPHP ERROR: A DB Exec Failed!, Error: Column 'value' cannot be null

DBCALL ERROR: A DB Exec Failed!, Error:1048, SQL:"INSERT INTO data_source_stats_hourly_cache (local_data_id, rrd_name, time, `value`) VALUES (30642, '', '2017-04-11 15:36:38', NULL) ON DUPLICATE KEY UPDATE `value`=VALUES(`value`)'`

I think the above is causing  poller_dsstats.php to not complete and hang and then starting another instance

`cacti     5242     1 28 11:05 ?        01:29:19 /usr/bin/php -q /var/www/html/prod_cacti/poller_dsstats.php
cacti     7258     1 21 11:55 ?        00:56:49 /usr/bin/php -q /var/www/html/prod_cacti/poller_dsstats.php
cacti     9831     1 24 11:25 ?        01:11:02 /usr/bin/php -q /var/www/html/prod_cacti/poller_dsstats.php
cacti    10047     1 22 11:40 ?        01:02:41 /usr/bin/php -q /var/www/html/prod_cacti/poller_dsstats.php
cacti    11137     1 18 14:45 ?        00:17:03 /usr/bin/php -q /var/www/html/prod_cacti/poller_dsstats.php
cacti    14608     1 27 11:10 ?        01:24:25 /usr/bin/php -q /var/www/html/prod_cacti/poller_dsstats.php
cacti    18042     1 21 12:01 ?        00:55:18 /usr/bin/php -q /var/www/html/prod_cacti/poller_dsstats.php
cacti    19577     1 22 11:45 ?        01:00:31 /usr/bin/php -q /var/www/html/prod_cacti/poller_dsstats.php
cacti    21451     1 26 11:15 ?        01:19:49 /usr/bin/php -q /var/www/html/prod_cacti/poller_dsstats.php
cacti    21826     1 23 11:30 ?        01:07:45 /usr/bin/php -q /var/www/html/prod_cacti/poller_dsstats.php
cacti    27102     1 18 14:31 ?        00:19:56 /usr/bin/php -q /var/www/html/prod_cacti/poller_dsstats.php
cacti    27890     1 29 11:00 ?        01:33:50 /usr/bin/php -q /var/www/html/prod_cacti/poller_dsstats.php
cacti    28341     1 21 12:06 ?        00:53:42 /usr/bin/php -q /var/www/html/prod_cacti/poller_dsstats.php
cacti    28890     1 20 13:21 ?        00:35:37 /usr/bin/php -q /var/www/html/prod_cacti/poller_dsstats.php
cacti    30080     1 22 11:50 ?        00:58:41 /usr/bin/php -q /var/www/html/prod_cacti/poller_dsstats.php
cacti    31554     1 23 11:35 ?        01:05:12 /usr/bin/php -q /var/www/html/prod_cacti/poller_dsstats.php
cacti    32212     1 21 12:10 ?        00:52:21 /usr/bin/php -q /var/www/html/prod_cacti/poller_dsstats.php`

Fix for this will be very much appreciated as i use dsstats plugin heavily.

Thanks

**Comment by cigamit** [comment]
This error is only a symptom of a larger problem and that is that the local_data_id's in the example above are not returning data.  You should resolve that before you get burned by bad data.  I have resolved the source of the SQL errors otherwise.
