### ISSUE TITLE
Cacti 1.2.25 and Mikrotik device template does not find mt interfaces

### ISSUE THREAD

**Issue by PAOK1926** [Cacti/cacti#5550]
when i add a mikrotik router, using Mikrotik device template, with Cacti 1.2.25 it does not find any mt interfaces.
this was not happening with older versions of cacti..

![Screenshot 2023-11-02 at 8 57 59 PM](https://github.com/Cacti/cacti/assets/31358094/805abcf3-d5c2-449e-aeb1-2075537c3d72)
![Screenshot 2023-11-02 at 8 58 32 PM](https://github.com/Cacti/cacti/assets/31358094/a9014a5f-aa2a-43fa-a0ee-70b40427dfbe)

**Comment by TheWitness** [comment]
Make sure you first install the MikroTik plugin and enable monitoring.

**Comment by PAOK1926** [comment]
i noticed that when i add the device as Mikrotik router, interfaces are not added..
but when i add it as net snmp device, are added.

**Comment by TheWitness** [comment]
Yea, you can go that route as well.  But if you wish to use the MicroTik template, it's best served when using the plugin.

**Comment by PAOK1926** [comment]
i made a clean installation of cacti, i think it installs something for mikrotik.
then, after your advice, i installed the plugin..
most of the graphs are empty (i tried it on a HEX s router), besides there are no interface stats..
