### ISSUE TITLE
CMDPHP ERROR: A DB Row Failed!, Error: Column 'graphs' in field list is ambiguous 

### ISSUE THREAD

**Issue by yudentaa521** [Cacti/cacti#5553]
# Describe the bug

![image](https://github.com/Cacti/cacti/assets/67460486/af80f31c-74ef-42b3-b1fa-3db70d5294b8)

When i access host.php, device not found. In my logs:

![image](https://github.com/Cacti/cacti/assets/67460486/836c748c-3230-46da-a784-e91a5e6e51ef)
CMDPHP ERROR: A DB Row Failed!, Error: Column 'graphs' in field list is ambiguous 

Can you help me, Sir?

**Comment by TheWitness** [comment]
What Cacti version?

**Comment by TheWitness** [comment]
It sounds like you have a 1.3 database and a 1.2.x install which would cause this error.

**Comment by TheWitness** [comment]
This has been resolved now.  Just pull a fresh copy of the 1.2.x branch.

**Comment by TheWitness** [comment]
Fixed here: https://github.com/Cacti/cacti/pull/5564

**Comment by yudentaa521** [comment]
Thank you very much
