### ISSUE TITLE
Support using <> lessthan/greater than characters in device description

### ISSUE THREAD

**Issue by dallenk** [Cacti/cacti#5558]
# Describe the bug
using Cacti 1.3

If using <> in a device description, the characters display as escape characters in dropdown menus

## To Reproduce

1. edit a device description

2. include a less than or greater than symbol  "< or >, <>"

3. go to "Management/Graphs" 

4. display dropdown menu, if the device is "selected" it displays correctly, other devices show the escape characters for lt/gt

## Expected behavior

Display lt/gt symbols in the device names while unselected in a dropdown menu.

## Screenshots

![image](https://github.com/Cacti/cacti/assets/2725066/49932694-480f-4cd2-8c4f-7e15864ed433)

**Comment by TheWitness** [comment]
Yea, we currently don't support this due to all the potential XSS and injection possibilities.  So, I'm going to mark "will not fix" for now.  Sorry about that.  It might always change, but not before the 1.3 release.

**Comment by TheWitness** [comment]
Feel free to continue to comment.

**Comment by dallenk** [comment]
Fair enough, can we move this to feature suggestion/enhancement instead of a bug?

**Comment by TheWitness** [comment]
Yea, I think so.

**Comment by netniV** [comment]
Personally, I think we should just not support this.  Primarily because it imitates HTML tags.

**Comment by TheWitness** [comment]
There is a way to achieve that by performing a re-write of the `html_escape()` function using the library that our security researchers are recommending.  But it's likely going to have to be in the `develop` branch due to the dependency to support the old RHEL7 stuff in 1.2.x Cacti version.

**Comment by TheWitness** [comment]
I was looking into this, and it looks like our server side sensitization switches the encoding, and when I use the client side sensitization, that normally allows certain characters, it's also converting them.  It's the joy's of using a browser and having to implement security.

**Comment by TheWitness** [comment]
I don't think that there is a good secure solution here for those characters.  So, I'm going to close this one.

**Comment by dallenk** [comment]
no problem, was just an idea but security is way more important to me.
