### ISSUE TITLE
CLI script "change_device.php" doesn't allow for passwords containing "=" characters

### ISSUE THREAD

**Issue by bernisys** [Cacti/cacti#5560]
# Describe the bug

If you run the CLI script and pass a password-string that contains an equal "=" character in the 8th or smaller position, it will fail in the parameter-check in lib/api_device.php at the password length check inside api_device_save(), because the input parameter is truncated by the "explode" function call in the parameter preparsing at the top of the change_device script.

## To Reproduce

1. Run this example on the shell:
php change_device.php --id=1 --version=3 --username='snmptest' --password='abc=123=def=456' --authproto='SHA' --privpass='something_long_and_secret' --privproto='AES128'

2. See error

## Expected behavior

passwords containing "=" chars should be handled properly.

## Additional context

Fix:  See my pull request https://github.com/Cacti/cacti/pull/5559

**Comment by TheWitness** [comment]
Confirmed an resolved in your pull request.
