### ISSUE TITLE
Unable to change a device's community at command line

### ISSUE THREAD

**Issue by apapierz** [Cacti/cacti#5565]
# Describe the bug

Unable to change device community via change_device.php CLI script

## To Reproduce

1. Run  php -q ./cli/change_device.php --id=deviceid --ip=ipaddress --community'new_community'

2. Scripts executes correctly but snmp community stays unchanged

## Sollution

Wrong name of array element in change_device.php line 89:

			$overrides['community'] = trim($value);

Changing name to snmp_community fixes the issue.

**Comment by xmacan** [comment]
Thank you for reporting
