### ISSUE TITLE
Problems with device reindexing. Unknown format specifier "," in the file global_languages.php on line 632

### ISSUE THREAD

**Issue by Vladyslav78956785786576** [Cacti/cacti#5569]
Problems with device reindexing.

http://10.10.10.10/host.php?action=reindex&host_id=1

` Fatal error: Uncaught ValueError: Unknown format specifier "," in /www/web01/data/www/domain.com/include/global_languages.php:632 Stack trace: #0 /www/web01/data/www/domain.com/include/global_languages.php(632): sprintf() #1 /www/web01/data/www/domain.com/host.php(203): __() #2 /www/web01/data/www/domain.com/host.php(66): host_reindex() #3 {main} thrown in /www/web01/data/www/domain.com/include/global_languages.php on line 632`

# uname -Kv
`FreeBSD 13.2-STABLE 74614fa93 SUPPORT-13-2-0 1302507`

# php -v
```
PHP 8.2.11 (cli) (built: Oct  6 2023 16:35:10) (ZTS)
Copyright (c) The PHP Group
Zend Engine v4.2.11, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.11, Copyright (c), by Zend Technologies
```
# php -m
```
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
enchant
exif
FFI
fileinfo
filter
gd
gettext
gmp
hash
iconv
imagick
imap
intl
json
ldap
libxml
mbstring
memcache
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
pspell
random
Reflection
session
shmop
SimpleXML
snmp
soap
sockets
sodium
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

```

# Cacti version - 1.2.25
# Cacti spine version - 1.2.25 

## To Reproduce

1. Go to the "hosts" section
2. Select any host. For example, select 1.
3. Run *[Re-Index Device](http://10.10.10.10/host.php?action=reindex&host_id=1)

## Desktop 

- OS: Windows 10

- Browser Firefox

- Version 119.0.1

**Comment by TheWitness** [comment]
What language are you using?

**Comment by Vladyslav78956785786576** [comment]
> What language are you using?

Russian

**Comment by TheWitness** [comment]
Okay cool.  It may take me a few days.  Busy week.

**Comment by TheWitness** [comment]
The issue was whomever originally translated the string.  If you are so inclined, signup at the site below and fix more translations.  In the case, the translator did not know what they were doing and switched at format character `%0.2f` to `%0,2f` which is not a valid format character.  I made the fix as the Translate site admin.

https://translate.cacti.net/translate/cacti/core-v1-2-x/ru/?offset=1&q=Device+Reindex&sort_by=-priority%2Cposition&checksum=

**Comment by TheWitness** [comment]
You will have to pull a fresh copy of the ru_RU.po and ru_RU.mo files.

**Comment by TheWitness** [comment]
There is quite a bit of Russian to translate yet.

**Comment by TheWitness** [comment]
For example "The Operation was successful.  Details are below."

![image](https://github.com/Cacti/cacti/assets/1439914/5c0cc15c-492e-464b-85d7-f7293cd62f45)

**Comment by Vladyslav78956785786576** [comment]
> The issue was whomever originally translated the string. If you are so inclined, signup at the site below and fix more translations. In the case, the translator did not know what they were doing and switched at format character `%0.2f` to `%0,2f` which is not a valid format character. I made the fix as the Translate site admin.
> 
> https://translate.cacti.net/translate/cacti/core-v1-2-x/ru/?offset=1&q=Device+Reindex&sort_by=-priority%2Cposition&checksum=

Translation is another method of delivering all sorts of vulnerabilities...

P.S. Once again, can you generate a Russian translation and push it into the repository?

**Comment by TheWitness** [comment]
What are you asking for?

**Comment by Vladyslav78956785786576** [comment]
> What are you asking for?

Update translation files for Russian language.
As I see it, this is done semi-manually.

**Comment by TheWitness** [comment]
If you update in the translate site, those updates will on a cron basis, be pushed back to GitHub automatically.  So, you simply can assume that https://translate.cacti.net is the source of truth, though from time to time, if we do change the wording for a specific translation, you may have to go back and redo it.  There will be a bunch of that going on in the `develop` branch with some of the changes that I'm currently making.  But if you do those changes to the `1.2.x` branch things get pushed back and make it into subsequent releases.
