### ISSUE TITLE
AKCP template does not see all devices.

### ISSUE THREAD

**Issue by itman0806** [Cacti/cacti#5571]
# Describe the bug

When using the AKPC template some SensorProbe devices are not recognized.

Working device refers to the device working with the Cacti AKCP template, Non-working refers to a device that does not work with the Cacti AKCP template.

When running verbose command on the non-working temperature sensors I get the following message.

Data Query Debug Information 
Total: 0.000000, Delta: 0.000000, Found data query XML file at '/var/www/html/cacti/resource/script_queries/query-akcp-temperature.xml'
Total: 0.000000, Delta: 0.000000, Running Data Query [5].
Total: 0.000000, Delta: 0.000000, Found Type = '6' [Script Server Query].
Total: 0.000000, Delta: 0.000000, XML file parsed ok.
Total: 0.000000, Delta: 0.000000, <arg_num_indexes> missing in XML file, 'Index Count Changed' emulated by counting arg_index entries
Total: 0.070000, Delta: 0.070000, ERROR: Data Query returned no indexes.

## To Reproduce

Adding the device or running a verbose query..

From my own trouble shooting I have found the following:

The non working device has different OID and not in the MIB. The PHP file query_akcp_temperature.php looks for the OID .1.3.6.1.4.1.3854.1.1.8.0 to look for securityProbe devices. However since this OID does not exist no value is returned. This was confirmed running the OID against a working device, then a non-working device using mib browser.

Working device .1.3.6.1.4.1.3854.1.1.8.0 returns the spProductName.0 sensorProbe2 v2.0
Non working returns no such name.
Older non-working device returns no such name.

Using the managment MIB OID .1.3.6.1.2.1.1.1.0 sysDescr

working device returns - (Name/OID: sysDescr.0; Value (OctetString):) sensorProbe2 v2.0 SP2468 090514
non-working device returns - (Name/OID: sysDescr.0; Value (OctetString):) SP2 F7 1.0.5676 Jan 10 2022 04:11:27
older non - working device - (Name/OID: sysDescr.0; Value (OctetString):) sensorProbe2A VLCT263 July 18 2003

Running a walk on the newer Non working device none of the OID's match the MIB file.

Name/OID: .1.3.6.1.4.1.3854.3.2.1.8.0; Value (OctetString): SP2 F7 1.0.5676 Jan 10 2022 04:11:2
I have uploaded a walk of the file removing any personal information.

[NewrAKCPwalk.txt](https://github.com/Cacti/cacti/files/13356084/NewrAKCPwalk.txt)

I hope this is enough information, I will be glad to provide more information if you need it.

Thanks

Paul

**Comment by TheWitness** [comment]
Paul, can you provide a walk with snmpwalk instead?  We don't have access to any of these devices, but I'm sure that through collaboration it can be achieved.

The two walks that are important are first with the vendor mib loaded, and the second walk using -On option to return numeric OIDs.
