### ISSUE TITLE
When viewing a graph, option to edit template may lead to incorrect URL

### ISSUE THREAD

**Issue by Vladyslav78956785786576** [Cacti/cacti#5573]
Incorrect URL for editing graph_templates. Perhaps typo.
```

<br>
<a class="iconLink" role="link" title="Edit Graph Template" href="//graph_templates.php?action=template_edit&amp;id=401"><img src="/images/template_edit.png"></a><br><a class="iconLink" href="/plugins/thold/thold.php?action=add&amp;usetemplate=1&amp;local_graph_id=4223" title="Создать порог"><i class="tholdEdit fas fa-wrench"></i></a><br><a class="iconLink" onclick="addQuickTree(4223, 0)" title="Add this graph to QuickTree" href="#"><i class="deviceUp fas fa-plus-circle"></i></a><br>					</td>				</tr>

```

Cacti version - 1.2.25

## To Reproduce

1. Go to 'Graph tree'

2. Select any graphic.

3. Click link "Edit Graph Template"

## Screenshots
![изображение](https://github.com/Cacti/cacti/assets/145745713/d04dba45-5242-44e5-a65c-7cc26c35e3e4)

## Additional context

```
-- href="//graph_templates.php?action=template_edit&amp;id=401 ...
++ href="/graph_templates.php?action=template_edit&amp;id=401 ...
```

**Comment by TheWitness** [comment]
What is your url_path in config.php?  I think it may be wrong.

**Comment by TheWitness** [comment]
It's normally $url_path = '/cacti/'.  My guess is that yours is simply '/'.

**Comment by Vladyslav78956785786576** [comment]
> It's normally $url_path = '/cacti'. My guess is that yours is simply '/'.

yes.
`$url_path = '/';`

**Comment by TheWitness** [comment]
Change it to an empty string.  What happens then?

**Comment by Vladyslav78956785786576** [comment]
> Change it to an empty string. What happens then?

I did an additional Ctrl + F5 and everything worked!

**Comment by TheWitness** [comment]
Which page, and did you change the url_path?  Does it work with the standard `$url_path='/cacti/';`?

**Comment by Vladyslav78956785786576** [comment]
> Which page, and did you change the url_path? Does it work with the standard `$url_path='/cacti/';`?

My web server is configured to use the full URI - http://10.10.10.10/

**Comment by TheWitness** [comment]
So, `$config['url_path']` should be the empty string '';

**Comment by cigamit** [comment]
Actually, this a a bug, and url_path should not be an empty string.
There is an extra slash on
https://github.com/Cacti/cacti/blob/develop/graph.php#L171
if url_path is set to /cacti/
then the url ends up as /cacti//graph_templates.php?action=template_edit&id=1

Also looks like line
https://github.com/Cacti/cacti/blob/develop/graph.php#L444
has the issue also

**Comment by cigamit** [comment]
Only other 2 I found where at
https://github.com/Cacti/cacti/blob/develop/help.php#L89
https://github.com/Cacti/cacti/blob/develop/lib/data_query.php#L76

**Comment by TheWitness** [comment]
Closing.  Thanks @cigamit !

**Comment by netniV** [comment]
Was the CHANGELOG updated for this issue?

**Comment by TheWitness** [comment]
No.

**Comment by TheWitness** [comment]
It is there now.
