### ISSUE TITLE
not really a bug - depreciated warning thousands of times. MYSQL_OPT_RECONNECT

### ISSUE THREAD

**Issue by dallenk** [Cacti/cacti#5579]
# Describe the bug

the cacti_stderr.log file contains many thousands of entries of:
MYSQL_OPT_RECONNECT is deprecated and will be removed in a future version.

**Comment by TheWitness** [comment]
Grab the 1.2.x spine.  It's way ahead of develop. This issue should be solved.

**Comment by TheWitness** [comment]
However, are you using MySQL 8.1.x.  Could be we need to update Cacti too. Oracle not making me too happy.

**Comment by dallenk** [comment]
OK, i'll revert to 1.2.x for spine,
lol at Oracle.  they don't make me happy either, I'm using 10.6.12-MariaDB-0ubuntu0.22.04.1

**Comment by dallenk** [comment]
changed to spine 1.2.25, warning remains.

**Comment by TheWitness** [comment]
Can you check your libmysqlclient.* version and see if it aligns with MySQL 8?  MySQL deprecated that option, but MariaDB did not.  As such, if the client library is recent and based on the latest MySQL build, we are going to have to figure something out there.

**Comment by TheWitness** [comment]
If you need help figuring things out.  It's likely in the versioning of the `so` files.

**Comment by TheWitness** [comment]
Interesting point of view on this one:

https://bugs.mysql.com/bug.php?id=112089

**Comment by TheWitness** [comment]
We will keep this open until such time as Oracle steps up.

**Comment by TheWitness** [comment]
Asked the question here: https://bugs.php.net/bug.php?id=58863&thanks=3

**Comment by dallenk** [comment]
> Can you check your libmysqlclient.* version and see if it aligns with MySQL 8? MySQL deprecated that option, but MariaDB did not. As such, if the client library is recent and based on the latest MySQL build, we are going to have to figure something out there.

here you go, i guess that means we are stuck with it until Oracle fixes something?  
apt list -a libmysqlclient*
Listing... Done
libmysqlclient-dev/jammy-updates,jammy-security,now 8.0.35-0ubuntu0.22.04.1 amd64 [installed,automatic]
libmysqlclient-dev/jammy 8.0.28-0ubuntu4 amd64

libmysqlclient21/jammy-updates,jammy-security,now 8.0.35-0ubuntu0.22.04.1 amd64 [installed,automatic]
libmysqlclient21/jammy 8.0.28-0ubuntu4 amd64

**Comment by TheWitness** [comment]
See if there is a `libmariadbclient` package.  If nothing else, MariaDB provides a client.  If neither are available, maybe there is a compat package to replace the standard.

I'm using Rocky[8-9] and don't have these issues.  Last thing is maybe use the REMI PHP packages.  He's a bit more responsive.

**Comment by TheWitness** [comment]
More tips...

https://stackoverflow.com/questions/51110986/libmariadbclient-dev-install-error-depends-libmariadbclient18#51111074

**Comment by dallenk** [comment]
adding to my.cnf seems to clear the errors in the log, but no idea is there is an impact on the rest of the system (so far seems ok.. I think)
 

[client]
reconnect=false

**Comment by TheWitness** [comment]
That should be posted on the forums as I'm sure it'll be everywhere for quite a while.

**Comment by TheWitness** [comment]
Going to close this one.  People will still be able to find the solution from Google.com.
