### ISSUE TITLE
Function `array_rekey()` fails on a null value in PHP 8.2 causing Cacti errors

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#5584]
# Describe the bug

Cacti has a habit of using `array_rekey()` blindly outside of the `db_fetch_assoc()` function.  If the Query fails and the result is something other than an empty array, PHP 8.2 will generate a Fatal error.

## Expected behavior

Maybe Cacti should write a wrapper to handle this situation.  Something like `cacti_array_rekey()` might be prudent.

**Comment by netniV** [comment]
Closed as completed without commits?

**Comment by TheWitness** [comment]
Well, I figured that it was just going to take too much time, and there were other things to do.  I guess I should have closed it and marked it **won't fix** or **no plans**
