### ISSUE TITLE
Secondary LDAP server not evaluated when the first one has failed

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#5590]
When you have multiple LDAP servers configured in the auth settings the expected behaviour is that cacti will evaluate the LDAP servers from left to right 

with the below failure the secondary server is not evaluated

```
2023-11-21 11:36:17 - AUTH LOGIN FAILED: LDAP Login Failed for user 'user' from IP Address ''.
2023-11-21 11:36:17 - AUTH LOGIN FAILED: LDAP Error: Protocol Error, Unable to bind, LDAP result: (Can't contact LDAP server) on Server (ldap hostname)
2023-11-21 11:36:17 - AUTH LDAP: Protocol Error, Unable to bind, LDAP result: (Can't contact LDAP server) on Server (ldap hostsname)
``

However in ling/ldap I see the following error conditions are checked and it does not include this error 

```
			/* unable to bind */
			$ldap_error = ldap_errno($ldap_conn);
			if ($ldap_error == 0x02) {
				/* protocol error */
				$output = LdapError::GetErrorDetails(LdapError::ProtocolErrorGeneral, $ldap_conn, $this->host);
			} elseif ($ldap_error == 0x31) {
				/* invalid credentials */
				$output = LdapError::GetErrorDetails(LdapError::Failure, $ldap_conn, $this->host);
			} elseif ($ldap_error == 0x32) {
				/* insufficient access */
				$output = LdapError::GetErrorDetails(LdapError::InsufficientAccess, $ldap_conn, $this->host);
			} elseif ($ldap_error == 0x51) {
				/* unable to connect to server */
				$output = LdapError::GetErrorDetails(LdapError::ConnectionUnavailable, $ldap_conn, $this->host);
			} elseif ($ldap_error == 0x55) {
				/* timeout */
				$output = LdapError::GetErrorDetails(LdapError::ConnectionTimeout, $ldap_conn, $this->host);
			} else {
				/* general bind error */
				$output = LdapError::GetErrorDetails(LdapError::ProtocolErrorBind, $ldap_conn, $this->host);
			}
		}

```

**Comment by TheWitness** [comment]
How did you get an empty IP address?

**Comment by bmfmancini** [comment]
I redacted it it was populated correctly though

**Comment by TheWitness** [comment]
Okay

**Comment by TheWitness** [comment]
This code block, you should log an error like this

```php
		} else {
			/* general bind error */
cacti_log("LDAP Bind failed error was $ldap_error");
			$output = LdapError::GetErrorDetails(LdapError::ProtocolErrorBind, $ldap_conn, $this->host);
		}
```

**Comment by TheWitness** [comment]
give it a whirl again @bmfmancini.

**Comment by bmfmancini** [comment]
Tested good!
