### ISSUE TITLE
[1.3 QA] Graph item presets and saved views seem to be ignored.

### ISSUE THREAD

**Issue by dallenk** [Cacti/cacti#5591]
# Describe the bug

Preset Graphs items in the user profile, or using the "save" button seems to be ignored.

## To Reproduce

1. Go to 'Console/Configuration/Users/<username>/User Settings'
2. Change Preview Graphs Per Page to anything other than 10
3. Go to 'Console/Configuration/Users/<username>/General'
4. Enable 'Maintain Custom Graph and User Settings'

logout,
log back in - View device with more than 10 graphs and only 10 are displayed in tree mode

Go to graph_view.php?action=preview
Select 100 and save.
logout, log back in and return to the preview page.. the saved profile is not used.

![image](https://github.com/Cacti/cacti/assets/2725066/85dd320b-65f1-4476-84b2-7fac2d5b519d)

![image](https://github.com/Cacti/cacti/assets/2725066/094ea265-04da-4c69-a09f-375f99509982)

![image](https://github.com/Cacti/cacti/assets/2725066/eb01316b-dd1d-4826-ae3d-54c06fb09afd)

Have I simply missed a configuration option somewhere?

**Comment by TheWitness** [comment]
Well, this may be a real issue and likely in 1.2.x too.  However, we won't be fixing it there.  I'll log it as a non QA bug for now and dig in later.

If you can not save custom settings, it should take the default.  If you enable custom settings, it should take either the default or the last thing you saved before it was disabled, or the cached value from the session.

The question becomes, do we wipe the custom settings when an Admin takes away your right to save them.  I'm pretty sure that's what we have to do.  What do you think?

**Comment by dallenk** [comment]
well, I guess it depends on what priority you want the custom settings to be, admin is first of course, then is it groups then users?   

If a user is a member of a group, and the option to save custom settings is disabled in the group, but enabled for the user, who wins?  and the other way around?

My thought would be default settings are always inherited, group settings override defaults, but user settings override groups so some group members of a group have a little more flexibility .   but if the admin removes those rights, then defaults always inherit?

**Comment by TheWitness** [comment]
Right now, it's strictly a permissive system and there is no precedence.  If the user gets it, then user wins by it's nature.  I guess that could change.  I know that at one point, a user had asked that it be more restrictive and that the admin should be able to define the order.  My guess is that they wanted some groups to go last if you were a member.  I know many customers who will remove all local permissions and leave it entirely to the group.  But right now, there is no way to do that en-mass other than with database calls.

**Comment by TheWitness** [comment]
Moved to an enhancement to keep it from closing.

**Comment by TheWitness** [comment]
This should be fixed in 1.3 now.

**Comment by TheWitness** [comment]
@sgvfr, once you have confirmed, simply close this ticket.

**Comment by dallenk** [comment]
looks good now, thanks!

**Comment by TheWitness** [comment]
Cool thanks.  I closed the darn thing before you confirmed.  Glad you got back when you did.
