### ISSUE TITLE
[1.3 QA] New bug introduced with latest commit - no options displayed for "change device settings"

### ISSUE THREAD

**Issue by dallenk** [Cacti/cacti#5598]
# Describe the bug

since the latest commits (not sure which one)  no options or selections are presented when selecting multiple devices and selecting "Change device Settings" from the dropdown.

only a Continue button, which returns to the device list.
![image](https://github.com/Cacti/cacti/assets/2725066/ce58515c-3b11-4c1b-bae4-76a242121ff6)

**Comment by TheWitness** [comment]
It seems working for me.  Can you retest?

**Comment by TheWitness** [comment]
Are you sure you have the latest `lib/html_form.php`?

**Comment by dallenk** [comment]
just pulled the latest again, i can try a hard reset.. will check and compare now.


64dad6625 (HEAD -> develop, origin/develop, origin/HEAD) Merge remote-tracking branch 'origin/develop' into develop

diff is identical from my local to git source

**Comment by dallenk** [comment]
sudo -u www-data git reset --hard a622b6cb0
HEAD is now at a622b6cb0 add template for Aruba OSCX 6x00 switch (#5596)

works here.

fails here:
sudo -u www-data git reset --hard 7357fa0af
HEAD is now at 7357fa0af QA: Convert host.php to confirmation api

**Comment by TheWitness** [comment]
Stupid me.  I still had a browser tab opened to 1.2.26.  Fixing shortly.

**Comment by dallenk** [comment]
yup, that did it.
