### ISSUE TITLE
Does Cacti have an API that can be called, for example, to use Python to retrieve traffic graphs for devices in Cacti?

### ISSUE THREAD

**Issue by jackfish0405** [Cacti/cacti#5599]
I would like to read data from Cacti using Python. Are there any relevant APIs that I can use for this purpose?

**Comment by TheWitness** [comment]
The best one I know is either graph_xport.php or graph_json.php.

However you need to know the local_graph_id first.

**Comment by jackfish0405** [comment]
thank you for your support.
