### ISSUE TITLE
Missing action duplicate in Management->Graphs (cacti 1.1.2)

### ISSUE THREAD

**Issue by gmuellerfr** [Cacti/cacti#560]
Hello,
I have many graphs with special consolidation functions summing traffic of ports of switches or comparing different devices.
![fw-traffic-port-based](https://cloud.githubusercontent.com/assets/25848039/24957863/8889bbd8-1f8d-11e7-8213-7270dddbbf4b.png)
![cpu-utilization](https://cloud.githubusercontent.com/assets/25848039/24957902/b8fc2be8-1f8d-11e7-8180-ee9e458d9027.png)

 In Version 0.8 I've created a customized graph for one device. Then I've duplicated the graph and changed host, ports or whatever.
Now I have to build up each graph from the scratch, because the duplicate action is missing.
Please readd this action. I've missed it today.
Kind Regards
Guenter

BTW, I remember an action called convert into template, which seems to have disappeared, too.

**Comment by cigamit** [comment]
Are these non-templated graphs?  Please let me know.  We removed it due to the fact that it does not make sense to duplicate a templated graph.  But the two options removed, do make sense for a non-templated graph.  No worries though.  Easy to restore that feature.

**Comment by gmuellerfr** [comment]
Yes, you remember, that I missed the ability to generate graphs with no source and no template. You told me that I have to enable this expert feature. Now I can't duplicate my own creations. Maybe you enable those actions only for expert mode.
Thank you for listening
Guenter

**Comment by cigamit** [comment]
Resolved.  Thanks.

**Comment by gmuellerfr** [comment]
Hello,

thank you for reimplementing this feature.
But trying to duplicate a graph gives following error-message:

Fatal error: Call to undefined function duplicate_graph() in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 531

:-(

Thank you for listening.
Guenter

**Comment by cigamit** [comment]
I swear that I tested this.  The QA department must have been out to lunch that day.  That would be you BTW.  Thanks for using Cacti.

**Comment by Tehrasha** [comment]
Is this feature alternately removed, restored, and removed again?
I am running 1.1.28 and see no 'duplicate' option under Management->Graphs
In fact I find no way to create a custom graph without a template.
