### ISSUE TITLE
When adding a device, using the bulk walk option can make version information appear

### ISSUE THREAD

**Issue by psycholand** [Cacti/cacti#5602]
The case statement for "--bulk_walk" in cli/add_device.php is missing a "break".

**Comment by TheWitness** [comment]
What cacti version?

**Comment by psycholand** [comment]
It was missing when the code for issue #4105 was committed (commit: afcb13b) on March 21, 2021.  So from version 1.2.17 up to the current 1.2.25.

**Comment by TheWitness** [comment]
Okay, this is fixed now.  Thanks for reporting.
