### ISSUE TITLE
The IN /OUT MAX values ​​in the Aggregate Graphs image are inconsistent with those in the CSV

### ISSUE THREAD

**Issue by jackfish0405** [Cacti/cacti#5606]
The IN /OUT MAX values ​​in the Aggregate Graph image are inconsistent with those in the CSV
Not all Aggregate Graphs have this problem, only some do, and no obvious pattern is found. The testing time frame is the previous month. Production environment cacti version 1.2.22

Aggregate Graph image 
IN MAX is 16.51G  OUT MAX is 7.78G
![image](https://github.com/Cacti/cacti/assets/53333879/4639a854-a714-4567-809b-f1797136d780)

Export CSV data using descending order,
IN MAX is 16.16G  OUT MAX is 6.86G
![image](https://github.com/Cacti/cacti/assets/53333879/75b45026-f033-44a9-b9d3-a90d44a4b763)

**Comment by TheWitness** [comment]
Check the latest once 1.2.26 is released and report back then.

**Comment by jackfish0405** [comment]
OK I'll find time to build a 1.2.26 and import the production environment data to test it.

**Comment by TheWitness** [comment]
Start at the forums on this one.  Thanks!
