### ISSUE TITLE
Question: System Stats Time almost doubled after update from 1.2.25 to 1.2.26. Is this expected?

### ISSUE THREAD

**Issue by j66h** [Cacti/cacti#5608]
Hi,
I've updated from 1.2.25 as of 07/21/2023 to 1.2.26 of today (12/06/2023). After this statistic times in log are almost doubled.
I've updated cacti and spine at the same timestamps.

Running on Debian 12, MariaDB 10.11.4. PHP 8.2.7. RRDTool 1.7.2. Despite cacti and spine everything installed from Debian repository.
CPU% increased a little but is below 15%, Load Average decreased:
![image](https://github.com/Cacti/cacti/assets/54892435/10ce2cea-3df7-460a-a0b5-e59a7cdeea54)

Just before the update:
![image](https://github.com/Cacti/cacti/assets/54892435/7c5db6a0-0313-4fd2-8791-9a68a0e95f49)

Right after the update:
![image](https://github.com/Cacti/cacti/assets/54892435/2fd5f03c-a467-44f8-b1f7-edb5489ee81b)

After some hours:
![image](https://github.com/Cacti/cacti/assets/54892435/0603953d-63fb-48cb-912d-6737e821cdd3)

So it looks like boost is back to the same times as before. Maybe some database/file caches had to be filled. But SYSTEM STATS stay at 80 seconds.

Is this expected for the new release or am I running into a problem?

Thanks a lot, best Regards, Joerg

**Comment by TheWitness** [comment]
Update spine.  There was an issue reported tonight.  It's fixed in the 1.2.x branch of spine now.
