### ISSUE TITLE
Hex-STRING prefix issue of snmp.php

### ISSUE THREAD

**Issue by skyjou** [Cacti/cacti#561]
The value with "Hex-STRING:" prefix seems like not work correct in "snmp.php".

After replacing manipulation in line 770, the original string prefix "Hex-STRING: " should be "Hex-".

It may need to remove the remain part "Hex-" from string, because there is no more Hex-"STRING:" in the string?

Another suspicious problem is line 863. The last variable in this line should be "$part", right?

I do not know if these are correct. Here is my diff:

`@@ -834,11 +834,11 @@`
`         }`
` `
`         $string = $output;`
`-    }elseif (preg_match('/(hex-string:)/i', $string)) {`
`+    }elseif (preg_match('/hex-/i', $string)) {`
`         $output = '';`
` `
`         /* strip off the 'Hex-STRING:' */`
`-        $string = preg_replace('/hex-string: ?/i', '', $string);`
`+        $string = preg_replace('/hex- ?/i', '', $string);`
` `
`         /* normalize some forms */`
`         $string = str_replace(' ', ':', $string);`
`@@ -860,7 +860,7 @@`
` `
`                 $output .= chr(hexdec($part));`
`             } else {`
`-                $output .= ($output != '' ? ':':'') . $output;`
`+                $output .= ($output != '' ? ':' : '') . $part;`
`             }`
`         }`

**Comment by cigamit** [comment]
Can you please convert this to a pull request?

**Comment by cigamit** [comment]
Once this is converted to a pull request, we can merge it.
