### ISSUE TITLE
[1.2.23] Different size of graphs in preview 

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#5610]
# Describe the bug
The graphs visual size differes in graph_view.

## To Reproduce
1. Go to (https://cacti/graph_view.php?action=preview&reset=1&host_id=878)
2. Scroll down & see error

## Expected behavior
Same size of graphs.

## Screenshots
![image](https://github.com/Cacti/cacti/assets/17087236/5a009394-73b1-4315-ad07-53704cd107a2)

## Desktop (please complete the following information)

- OS: Windows 7
- Browser Chrome

**Comment by TheWitness** [comment]
Adjust your Graph Templates if you want them all the same size.  This is not a bug.

**Comment by interduo** [comment]
OK, thanks for info! :)
