### ISSUE TITLE
False alerts and no new data on device graphs after some counters limit

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#5611]
# Describe the bug
I got two Cisco Nexus with almost 500days uptime.
(with Cisco NX-OS(tm) nxos.7.0.3.I6.2.bin, Software (nxos), Version 7.0(3)I6(2), RELEASE)

Few days ago some counters gets full and:
1. New data from that time did not appear on all this two devices graphs.
2. We get mail with 'Cacti Device Reboot Notification' for two devices.

## Expected behavior
Draw again data on graphs.
Make an exception for this counters limit and dont send reboot alerts, 

## Screenshots
![image](https://github.com/Cacti/cacti/assets/17087236/7c9ac074-497c-4b60-b220-e30edbec0953)
![image](https://github.com/Cacti/cacti/assets/17087236/8e22b679-7405-4fde-ab46-115befdc6c37)

For all the graphs I get in logs:
```
2023/12/09 12:50:22 - SPINE: Poller[Main Poller] PID[2385099] WARNING: Invalid Response, Device[CENTR-AGM-nexus-agg] HT[1] DS[CENTR-AGM-nexus-agg - Non-Unicast Packets - |query_ifName|] Graphs[CENTR-AGM-nexus-agg - Non-Unicast Packets - Ethernet1/50/4] SNMP: v2: 172.20.1.253, dsname: nonunicast_out, oid: .1.3.6.1.2.1.2.2.1.18.436432896, value: No Such Instance currently exists at this OID
2023/12/09 12:50:22 - SPINE: Poller[Main Poller] PID[2385099] WARNING: Invalid Response, Device[CENTR-AGM-nexus-agg] HT[1] DS[CENTR-AGM-nexus-agg - Non-Unicast Packets - |query_ifName|] Graphs[CENTR-AGM-nexus-agg - Non-Unicast Packets - Ethernet1/50/4] SNMP: v2: 172.20.1.253, dsname: nonunicast_in, oid: .1.3.6.1.2.1.2.2.1.12.436432896, value: No Such Instance currently exists at this OID
2023/12/09 12:50:22 - SPINE: Poller[Main Poller] PID[2385099] WARNING: Invalid Response, Device[CENTR-AGM-nexus-agg] HT[1] DS[CENTR-AGM-nexus-agg - Non-Unicast Packets - |query_ifName|] Graphs[CENTR-AGM-nexus-agg - Non-Unicast Packets - Ethernet1/50/3] SNMP: v2: 172.20.1.253, dsname: nonunicast_out, oid: .1.3.6.1.2.1.2.2.1.18.436428800, value: No Such Instance currently exists at this OID
2023/12/09 12:50:22 - SPINE: Poller[Main Poller] PID[2385099] WARNING: Invalid Response, Device[CENTR-AGM-nexus-agg] HT[1] DS[CENTR-AGM-nexus-agg - Non-Unicast Packets - |query_ifName|] Graphs[CENTR-AGM-nexus-agg - Non-Unicast Packets - Ethernet1/50/3] SNMP: v2: 172.20.1.253, dsname: nonunicast_in, oid: .1.3.6.1.2.1.2.2.1.12.436428800, value: No Such Instance currently exists at this OID
2023/12/09 12:50:22 - SPINE: Poller[Main Poller] PID[2385099] WARNING: Invalid Response, Device[CENTR-AGM-nexus-agg] HT[1] DS[CENTR-AGM-nexus-agg - Non-Unicast Packets - |query_ifName|] Graphs[CENTR-AGM-nexus-agg - Non-Unicast Packets - Ethernet1/50/2] SNMP: v2: 172.20.1.253, dsname: nonunicast_out, oid: .1.3.6.1.2.1.2.2.1.18.436424704, value: No Such Instance currently exists at this OID
2023/12/09 12:50:22 - SPINE: Poller[Main Poller] PID[2385099] WARNING: Invalid Response, Device[CENTR-AGM-nexus-agg] HT[1] DS[CENTR-AGM-nexus-agg - Non-Unicast Packets - |query_ifName|] Graphs[CENTR-AGM-nexus-agg - Non-Unicast Packets - Ethernet1/50/2] SNMP: v2: 172.20.1.253, dsname: nonunicast_in, oid: .1.3.6.1.2.1.2.2.1.12.436424704, value: No Such Instance currently exists at this OID
2023/12/09 12:50:22 - SPINE: Poller[Main Poller] PID[2385099] WARNING: Invalid Response, Device[CENTR-AGM-nexus-agg] HT[1] DS[CENTR-AGM-nexus-agg - Non-Unicast Packets - |query_ifName|] Graphs[CENTR-AGM-nexus-agg - Non-Unicast Packets - Ethernet1/50/1] SNMP: v2: 172.20.1.253, dsname: nonunicast_out, oid: .1.3.6.1.2.1.2.2.1.18.436420608, value: No Such Instance currently exists at this OID
2023/12/09 12:50:22 - SPINE: Poller[Main Poller] PID[2385099] WARNING: Invalid Response, Device[CENTR-AGM-nexus-agg] HT[1] DS[CENTR-AGM-nexus-agg - Non-Unicast Packets - |query_ifName|] Graphs[CENTR-AGM-nexus-agg - Non-Unicast Packets - Ethernet1/50/1] SNMP: v2: 172.20.1.253, dsname: nonunicast_in, oid: .1.3.6.1.2.1.2.2.1.12.436420608, value: No Such Instance currently exists at this OID
```

**Comment by interduo** [comment]
@TheWitness Its `int(10)` value in DB limit  probbably this field: https://github.com/Cacti/cacti/blob/develop/cacti.sql#L333. I suggest changing it all data tables to int(16).

**Comment by TheWitness** [comment]
That column has nothing to do with your issue.

**Comment by TheWitness** [comment]
This issue belongs on the forums.  Thanks.

**Comment by interduo** [comment]
> That column has nothing to do with your issue.

Ok, but for sure it's somewhere else `int(10)` in other place - because the time when issue occurs was the limit of int(10) field.

> This issue belongs on the forums. Thanks.

What does it mean for future? Could You give me link to this issue in forum?

What can I do with that thing? Is this normal situation?

**Comment by interduo** [comment]
@TheWitness there are two problems with that:

1. Flase alerting:
Device reboot exactly after 497.1 days is extremely unlikely. So, as a workaround you could compare 2 latest uptime values.
If uptime has decreased AND it was less than (497.1 - small value, depends on how often you poll device) days before decrease, then a reboot took place. Otherwise no reboot, just counter overflow.

Do You think is it possible to code that excepion in alerting function? 
(You could save somebodys life (myocardial infarction) or just bring less silver hairs on the top of dome).

2. No data in graphs

I don't know why there is no new data. What to do with that? (device reboot is not possible)

**Comment by TheWitness** [comment]
Support is on the forums, not here.  Once you've confirmed on the forums that there is a bug, and are given directions as such, then open a ticket.
