### ISSUE TITLE
The downloaded CSV table differs by 5 minutes from the selected time

### ISSUE THREAD

**Issue by aliuzzz** [Cacti/cacti#5615]
I set the time range to start from 16:40, and i  download a CSV table,
in cacti0.8.8，it starts from 16:45,
in cacti1.2.25, it starts from 16:50, is this a bug in version 1.2.25？
![1](https://github.com/Cacti/cacti/assets/43594093/3fca65fc-449c-422e-b133-495a7ab5da70)
![2](https://github.com/Cacti/cacti/assets/43594093/76102f93-8022-4166-afe8-21c947f8923f)

**Comment by xmacan** [comment]
It was fixed - https://github.com/Cacti/cacti/issues/5479

Please update to 1.2.x branch
