### ISSUE TITLE
The IN /OUT MAX values ​​in the Aggregate Graphs image are inconsistent with those in the CSV

### ISSUE THREAD

**Issue by jackfish0405** [Cacti/cacti#5617]
#5606 Association
The IN /OUT MAX values ​​in the Aggregate Graph image are inconsistent with those in the CSV
Not all Aggregate Graphs have this problem, only some do. The testing time frame is the previous month. 
Production environment cacti version 1.2.22.
Currently importing rra data into cacti latest version 1.2.26, but the problem still exist.

In Graph image MAX IN is 12.1G
![image](https://github.com/Cacti/cacti/assets/53333879/b0d3a11d-0f3b-4d3a-a3c8-46e083f79dd5)

Total IN-MAX on CSV in descending order the maximum is 6.74G
![image](https://github.com/Cacti/cacti/assets/53333879/c54c0d29-f210-4815-9709-a75e1ffe0cfa)

**Comment by jackfish0405** [comment]
After analysis, it was found that the problem of inconsistency between the peak value of the aggregate graph and the CSV data often occurs in the following situations: when traffic switching occurs between multiple interfaces of the aggregate graph.

For example, the aggregation graph in the figure below consists of two interfaces. Between 18:11-19:11, the OUT direction traffic is switched from interface A to interface B.
![image](https://github.com/Cacti/cacti/assets/53333879/e7e7f40a-18c9-4b24-923d-68c7a6452337)

The aggregate graph for the previous month shows that the traffic at this point in time is cumulative.
![image](https://github.com/Cacti/cacti/assets/53333879/09a56d9b-f4e2-4a81-ba16-6138a49b700d)

Selecting the time range for the day's aggregate graph reveals that there are two cumulative peaks before and after the traffic switch.
![image](https://github.com/Cacti/cacti/assets/53333879/5c38ae5d-0c97-4763-a2eb-c5f10e6a1009)

Then further select the time range to two hours before the traffic switch, and the peak value of the aggregate graph is displayed normally again.
![image](https://github.com/Cacti/cacti/assets/53333879/aeb259de-9f84-4a3a-bfbe-a375f211ceb0)

It is also normal to view CSV data with a time range of last month at 18:11-19:11, with cumulative peaks appearing every month.

This problem only occurs with aggregated graph displays when the time range spans a long time range.

**Comment by jackfish0405** [comment]
My image template uses MAX for drawing. I analyzed that the problem may be that each port performs data compression first during drawing, and a MAX value is taken within the time range of one pixel.

In this way, when the port traffic is switched, it may happen that both ports take the MAX value in the same pixel time range. When these two sets of port data are combined for drawing, the MAX value superposition occurs.

Is it possible to merge the data of multiple ports into a set of data first, and then draw the aggregated graph?
This is just my guess.

**Comment by TheWitness** [comment]
Which Cacti version @jackfish0405 ?

**Comment by jackfish0405** [comment]
Is the latest version 1.2.26

**Comment by TheWitness** [comment]
On this one, you need to be very careful of what Consolidation Function the GPRINT is using.  If the Graph line/area is using AVG and the GPRINT is using MAX, they are two different numbers.  That's what is going on here.
