### ISSUE TITLE
[1.2.26] Undefined index:  in /var/www/html/cacti/lib/installer.php on line 1144

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#5618]
# Describe the bug

Upgrade Cacti from 1.2.25 to 1.2.26.by Web Console.
Wizard hang between "inport template" and "convert table" steps

# Code Fragment
* in /var/www/html/cacti/lib/installer.php on line 1144:
  ```php
  foreach ($this->defaultAutomation as $item) {
    if ($item[''] == $param_default_template) {
      $default_template = $param_default_template;
      break;
    }
  }
  ```

# Comments:
* From source code, `$param_default_template` should be a host-template-id
  ```php
  #line 1119
				  if (!empty($host_template_id)) {
					  if ($host_template_id != $default_template) {
						  log_install_always('templates', 'getDefaultTemplate(): Changing Device Template to \'' . $item['name'] . '\'');
  
						  set_config_option('default_template', $host_template_id);
					  }
  #line 1151
		  if (empty($default_template)) {
			  $default_template = $this->getDefaultTemplate();
		  }
  
		  set_config_option('default_template', $default_template);
  ```
* But in line 197, `$this->defaultAutomation` does not include any index about `host-template-id`

So, I'm not sure what's original coder design intend. and can not provide any valuable diff.

**Comment by TheWitness** [comment]
Jing if you would like to propose a pull request I would be more than welcome to merge.
