### ISSUE TITLE
 Using Cacti to monitor switch port traffic, inaccurate port traffic

### ISSUE THREAD

**Issue by WangDaMiaoAAA** [Cacti/cacti#5620]
Using Cacti to monitor the 10G port traffic of the switch, it was found that the peak speed exceeded 10G,Cacti version1.2.25

<img width="398" alt="feead010fd32f3b7c418a111fe9667c" src="https://github.com/Cacti/cacti/assets/154414132/54a25af6-7ddb-4066-8185-29a5d79fde48">

**Comment by WangDaMiaoAAA** [comment]
I feel that the delay in obtaining data from SNMP caused the traffic data from the previous minute to be overlaid with the traffic data from the next minute
<img width="405" alt="b327b601bd5ae5e473a71ee6a5b3b90" src="https://github.com/Cacti/cacti/assets/154414132/2db7fc48-757c-4467-a083-19168afa0df4">

**Comment by TheWitness** [comment]
This is less about Cacti and more about your switch/router.  For the interface in question, what is the ifHighSpeed?  Cacti set's the max value in the RRDfile based upon the response here.  If the interface is something like a VLAN or aggregate interface that does not provide an accurate ifHighSpeed, Cacti has a default value.  If there are going to be multiple Defaults, you will have to tune the RRDfiles directly using the `rrdtool tune filename -a traffic_in:blah -a traffic_out:blah` command.
