### ISSUE TITLE
Update Cacti with current MariaDB features

### ISSUE THREAD

**Issue by HQuest** [Cacti/cacti#5621]
While deploying or tuning Cacti, one of the checks is against MariaDB existence of InnoDB (have_innodb). However this value was removed since [MariaDB v10.0](https://mariadb.com/kb/en/innodb-system-variables/#have_innodb). The recommendation is to use alternate ways of querying (show engines;), but I'm uncertain if InnoDB can be disabled at all.

**Comment by TheWitness** [comment]
This has been fixed in the pending 1.2.26 release already.  Thanks for the issue log though.
