### ISSUE TITLE
Improve PHP 8.3 support

### ISSUE THREAD

**Issue by HQuest** [Cacti/cacti#5622]
ERROR PHP ERROR: Could not set timer: Invalid argument (22) in file: cacti-1.2.25/graph_templates.php on line: 34

Offending line:
ini_set('max_execution_time', '-1');
Changing value to 0 allows unlimited execution time and resolves the error.

ERROR PHP DEPRECATED: Increment on non-alphanumeric string is deprecated in file: cacti-1.2.25/lib/html.php on line: 936
Offending line:
$page++;
Changing to "$page = (int)$page + 1;" looks less developer-y but resolves the deprecation.

Both can be experienced when going Console > Templates > Graph.

**Comment by TheWitness** [comment]
Hmm.  Nice catch PHP ;)  We will fix this post 1.2.26.

**Comment by TheWitness** [comment]
This is fixed now.  Thanks for taking the time to report.
