### ISSUE TITLE
Incomplete information displayed in the drop-down list under non classic themes

### ISSUE THREAD

**Issue by linqianye** [Cacti/cacti#5627]
# Describe the bug

When using modern themes, the 'Device' options in the Filter can only display 30 items. The number 30 seems to come from global settings.
After testing, it was found that only classic themes are displayed in full.

## To Reproduce

1. Change the theme to a non classic theme.

2. Go to Console > Management > Graphs/Date Soures > Filter > Device

3. Click on the dropdown list and drag to the end

4. Only 30 items, not all

5. When I go to Console > Configuration > Settings > Visual

6. change the value of Autocomplete Rows under Table Settings from 30 to 50

7.  Repeat steps 2-4, there are 50 items here

## Expected behavior

Under the classic theme, all devices are displayed in the dropdown list. And in fact, we expect it to be the same under the other theme.

## Cacti Version
Version 1.2.25

**Comment by TheWitness** [comment]
This is normal behavior.  There is a visual setting that allows you to control the number of tows.
