### ISSUE TITLE
When changing password, returning to previous page does not always work

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#5629]
# Describe the bug

“Change Passwrod” page cannot return to the refer url by just clicking the "Return" button once

## To Reproduce

1. Access any Cacti page

2. Access `auth_changepassword.php` by input URL or User->Menu

3. Input something, and make sure the password changed fails 

4. Click  "Return"

5. Click  "Return" again

## Expected behavior

Expect to return previous refer page in the 4th step, but do not. 
But return in the fifth step。

**Comment by TheWitness** [comment]
@ddb4github, please test the latest updates.
