### ISSUE TITLE
I have encountered an issue in different versions where "Poller Output Table not Empty" appears, and RRD files are not created.

### ISSUE THREAD

**Issue by htyypt** [Cacti/cacti#5632]
The system specifications are as follows:

Operating System: CentOS Linux release 7.9.2009
PHP: 8.1.13
MySQL: 8.0
Cacti: 1.2.26
Spine: 1.2.26
Symptoms:

1、For instance, when creating 50 graphs for an SNMP host, a random subset of graphs does not generate RRD files. No solution seems to work, and the only effective method is to delete and re-add these graphs.
![image](https://github.com/Cacti/cacti/assets/81215528/fd810845-2773-4dbd-8a7e-4008baccf990)

2、The logs report the issue "Poller Output Table not Empty," affecting the update of data for certain graphs. The associated hosts do not experience timeout issues, and Spine processes and threads have been increased, ruling out performance problems.
![image](https://github.com/Cacti/cacti/assets/81215528/369ede94-37e6-479e-a8ce-9b90824648de)

I have consulted forums and all available issues but am uncertain how to proceed. Your assistance is appreciated.

**Comment by TheWitness** [comment]
Put the device into debug mode and look for bad or missing data coming back.  You might want to be careful with setting maxoids too high as well.

**Comment by htyypt** [comment]
> Put the device into debug mode and look for bad or missing data coming back. You might want to be careful with setting maxoids too high as well.

How do I set it to debug mode?
Is it in Cacti Settings? Fill in the host name or IP

**Comment by TheWitness** [comment]
What version of Cacti is this?  When you edit the device, there are several links in the upper right hand corner.  Read them out loud.

**Comment by TheWitness** [comment]
Better to run `spine -R -V 3 -S -H host_id` and see if the Data Sources are even being polled.

**Comment by TheWitness** [comment]
No feedback.
