### ISSUE TITLE
Cacti 1.2.25 tree mode is blank

### ISSUE THREAD

**Issue by smithmich** [Cacti/cacti#5634]
After upgrade to 1.2.25 In the Graphs tab Tree mode is blank but list mode shows the graphs.
Running on Redhat 7
Any help would be appreciated

**Comment by smithmich** [comment]
It works in Edge but not Chrome though

**Comment by smithmich** [comment]
Never mind. I leared my cache and it works. Sorry

**Comment by smithmich** [comment]
I'm an idiot.

**Comment by TheWitness** [comment]
Well, I feel less alone today then 😁
