### ISSUE TITLE
CSV table time interval problem

### ISSUE THREAD

**Issue by aliuzzz** [Cacti/cacti#5635]
In the default time of day, I download the CSV table, and the time interval in the table is 5 minutes, which is correct. But if I customize and modify other times, the time interval in the table is 30 minutes?
Like this pictures:
![image](https://github.com/Cacti/cacti/assets/43594093/30228cd9-932b-4085-a3e8-0363e8ed96d6)
![image](https://github.com/Cacti/cacti/assets/43594093/2d0bd330-387a-49b9-9535-c61f370eecdb)

**Comment by TheWitness** [comment]
What Cacti version?  I believe this was fixed already in 1.2.26.

**Comment by TheWitness** [comment]
No feedback.
