### ISSUE TITLE
Template created on 0.8.x no more working on 1.2.25

### ISSUE THREAD

**Issue by jackouille-ch** [Cacti/cacti#5642]
Hi,

I build a new server, imported all template and data and I tried to create a new graph that I define but it's no more working.
My graph is an aggregation of 2 interface traffic (I saw the embedded ones but I can't customize them as I want, sorry).
I attached it: [cacti_graph_template_two_feeds_2024.zip](https://github.com/Cacti/cacti/files/13908596/cacti_graph_template_two_feeds_2024.zip)

The template works for old graphs but I can't create new ones based on it, always prompted for Custom Data [Template: Interface - Traffic] but don't know what to fill or how to remove it.
Here is my current output:
![twoFeeds2024](https://github.com/Cacti/cacti/assets/35721406/a3a8a03d-bbf3-485b-8ccf-9000ae0db20e)

Running Cacti 1.2.25 on CentOS 9, PHP 8.3 (waiting for version 1.2.26 to be packaged for CentOS).

How can I correct this ? Or is there a way to duplicate the existing graph so that I will be able  to change Data Source after ?

Thanks

**Comment by bmfmancini** [comment]
Can you share any errors your seeing in the log
Or enable debug on the device

**Comment by jackouille-ch** [comment]
There is no errors within logs (while in Debug) because graph is not created.
I only got the following message: Save Failed due to field input errors (Check red fields).
But no red fields, here is the output:
![twoFeeds2024-1](https://github.com/Cacti/cacti/assets/35721406/32323a4f-1806-425e-aee4-789087934687)

**Comment by jackouille-ch** [comment]
Added some more logs and here the result:
<html><body>

2024-01-13 10:31:01 - CMDPHP Form Validation Failed: Variable 'c_0_184_41_14' does not allow nulls and variable is null
2024-01-13 10:31:01 - CMDPHP Form Validation Failed: Variable 'c_0_184_41_13' does not allow nulls and variable is null
2024-01-13 10:31:01 - CMDPHP Form Validation Failed: Variable 'c_0_184_41_12' does not allow nulls and variable is null

</body>
</html>

**Comment by xmacan** [comment]
1.2.26 fix few things in aggregated graphs:
https://github.com/Cacti/cacti/issues/5555

**Comment by jackouille-ch** [comment]
Waiting for the 1.2.26 package to be available on CentOS...
I either hope it will correct a PHP issue with deprecated function.

**Comment by TheWitness** [comment]
@jackouille-ch, I'm going to go ahead and close this.  Once you get yourself to 1.2.26 or setup a test environment for 1.2.x and you can again reproduce, feel free to chime back in.
