### ISSUE TITLE
Error on data source template about Maximum value as |query_ifSpeed|

### ISSUE THREAD

**Issue by arno-st** [Cacti/cacti#5647]
Hello,
I try to define for interface traffic, the maximum based on the speed of the interface.
So far I have |query_ifSpeed| but get this error once in a while:
```
CMDPHP ERROR: Suggested value column error. Column rrd_maximum for Data Template ID 206 is not a compatible field name for tables data_template_data and data_template_rrd. Please correct this suggested value mapping 
```

It's on a Port-channel:
```
AUTOM8 NOTE: Graph Added - Device[sre-b30-130], Graph[sre-b30-130 Po30 - Traffic - Po30 VSS domain 30 --- ], DS[sre-b30-130 Po30 - Traffic - Po30 VSS domain 30 ---] Graphs[sre-b30-130 Po30 - Traffic - Po30 VSS domain 30 --- ], Rule[Traffic Port-channel] 
```

or a regular interface:
```
10/01/2024 11:01:49 - AUTOM8 NOTE: Graph Added - Device[se-pdb-3001], Graph[se-pdb-3001 Gi1/0/25 - Traffic - SRE-B30-130 / WS-C4500X-32 / Te1/1/3 ], DS[se-pdb-3001 Gi1/0/25 - Traffic - SRE-B30-130 / WS-C4500X-32 / Te1/1/3] Graphs[se-pdb-3001 Gi1/0/25 - Traffic - SRE-B30-130 / WS-C4500X-32 / Te1/1/3 ], Rule[Traffic uplink Port] 
```

Here is the Data template 206:
![2024-01-10 13_41_18-Clipboard](https://github.com/Cacti/cacti/assets/25684899/069e4fab-7e05-4078-a375-0e93d4c41791)

So I try to change the maximum value with |query_ifHighSpeed|
but then I got this error message:
```
Sorry, we could not process your last action.

Save Failed due to field input errors (Check red fields).
```
And no field is in red, but since I change only one it has to be the maximum value.

How can I fix this, or is it normal ?

Cacti 1.2.26, latest dev

**Comment by TheWitness** [comment]
From a logic perspective, this can not happen unless you lost the database connection.  Make sure your max_connections is high.  You can check if it's high enough using these two MySQL/MariaDB commands:

```db
SHOW GLOBAL VARIABLES LIKE 'max_connections';
SHOW GLOBAL STATUS LIKE 'max_used_connections';
```

You can see below:

![image](https://github.com/Cacti/cacti/assets/1439914/033595bb-7ac2-4935-b3df-6c39a450fb8e)
