### ISSUE TITLE
SPINE: Poller[Main Poller] PID[p id] PT[pt number] Device[Device Name] Hostname[IP Address] ERROR: HOST EVENT: Device is DOWN Message: ICMP: Ping timed out

### ISSUE THREAD

**Issue by MSS970** [Cacti/cacti#5656]
**Describe the bug**
Spine Poller reports devices as down however, the devices are found UP by attempting to check the status of the devices in CACTI (click on management -> devices -> click on any device, the Ping Results is successful.

**CACTI log shows:**

SPINE: Poller[Main Poller] PID[p id] PT[pt number] Device[Device Name] Hostname[IP Address] ERROR: HOST EVENT: Device is DOWN Message: ICMP: Ping timed out.

**To Reproduce**

1. Install CACTI Dev (1.3)
2. Install Spine Dev (1.3)
3. Login to CACTI
4. Click on Logs
5. See error

**Expected behavior**
It is expected to see no errors from spine poller.

Server (please complete the following information):

- OS: [Windows 2019]
- Version [e.g. 2019]
- CACT version 1.3
- Spine version 1.3

![SPING1 3-error](https://github.com/Cacti/cacti/assets/124117691/55381366-5488-49be-8024-d36387a37a9d)

**Comment by TheWitness** [comment]
Is spine marked setuid?  In other words, is the file owned by root and "chmod +s spine"?  I suspect that's the error.

**Comment by MSS970** [comment]
Hi,
I use Windows OS, not sure if the chmod applies here.

**Comment by MSS970** [comment]
As I use Windows,  there is no root.

**Comment by TheWitness** [comment]
This is likely a restriction in Windows.  Look up giving a user permission to open **RAW SOCKETS** and grant that access to the Windows account.

**Comment by TheWitness** [comment]
Are you using spine or cmd.php?

**Comment by MSS970** [comment]
I use spine and fping on Windows

**Comment by MSS970** [comment]
I have checked the permissions on Windows:

- SYSTEM account has full permissions
- Administrators group has full permission
- Users group has read and execute

**Comment by TheWitness** [comment]
Here you go

https://learn.microsoft.com/en-us/windows/win32/winsock/tcp-ip-raw-sockets-2
