### ISSUE TITLE
Consolidation Functions must be available in COMMENT for nth percentile and bandwidth summations comment types

### ISSUE THREAD

**Issue by aliuzzz** [Cacti/cacti#5657]
![image](https://github.com/Cacti/cacti/assets/43594093/fcda7758-e6b8-4aac-909b-66e6d2ed69e1)
![image](https://github.com/Cacti/cacti/assets/43594093/3d97e74b-8690-4584-84b1-00a643368a88)
Can we change average to max？

**Comment by TheWitness** [comment]
This is controlled by the HRULE rules vs. the consolidation function though I see the point when coming from 0.8.x.

**Comment by aliuzzz** [comment]
So, you means that it cannot be modified to MAX, but it will not affect the normal data results.The results are the same as the 0.8.x

**Comment by aliuzzz** [comment]
So, you means that it cannot be modified to MAX, but it will not affect the normal data results.The results are the same as the 0.8.x.
This is important to me and I hope to receive confirmation

**Comment by TheWitness** [comment]
There is a custom aggregation method for max of max.  Here are the available aggregations group by those that are identical.  There are duplicates.

* current - Current from AVG
* max - Max from MAX
* total, all_max_current - Total from AVG
* total_peak, all_max_peak - Total from MAX
* aggregate, aggregate_sum - Total from AVG
* aggregate_peak, aggregate_max, aggregate_sum_peak - Total from MAX
* aggregate_current - Total from AVG
* aggregate_current_max - Total from MAX

Let me know if any of these get you to where you want to go?

**Comment by aliuzzz** [comment]
aggregate_peak, aggregate_max, aggregate_sum_peak - Total from MAX

**Comment by aliuzzz** [comment]
Also, do different aggregation methods affect the results of the csv table? I created an aggregation graph that aggregates several graphs using the "Interface - Traffic (bits/sec, 95th) " template. But the total column always matches the inbound traffic, while the 95 percentile on the graph will display normally according to the difference between inbound and outbound

![dd43a778639105d876f70e86733ba685](https://github.com/Cacti/cacti/assets/43594093/0dd3f44f-a36c-495c-8199-778dd74e9436)
![0b30b4a46ae03594be5e42c6c958fc2d](https://github.com/Cacti/cacti/assets/43594093/09ac263a-92c2-4a21-a005-7e0cfc64ac8b)

**Comment by maojianyou** [comment]
> There is a custom aggregation method for max of max. Here are the available aggregations group by those that are identical. There are duplicates.
> 
> * current - Current from AVG
> * max - Max from MAX
> * total, all_max_current - Total from AVG
> * total_peak, all_max_peak - Total from MAX
> * aggregate, aggregate_sum - Total from AVG
> * aggregate_peak, aggregate_max, aggregate_sum_peak - Total from MAX
> * aggregate_current - Total from AVG
> * aggregate_current_max - Total from MAX
> 
> Let me know if any of these get you to where you want to go?

php7.3
nginx1.20
mysql8.0
rrdtool1.8.0

I have a switch with two interfaces, eth-trunk20 and eth-trunk44, and I'm using a separate 95th percentile template. However, the default template is set to "max," which includes the parameters HRULE: |95:bits:0:max:2| and COMMENT: |95:bits:9:max:2| G<HR>.

Now, I'm trying to create an aggregate graph by adding eth-trunk20 and eth-trunk44 to it. However, I noticed that the items in the aggregate graph cannot be modified, and both eth-trunk20 and eth-trunk44 carry the same parameters, which are HRULE: |95:bits:0:max:2| and COMMENT: |95:bits:9:max:2| G<HR>.

The issue I'm encountering is that the graph is summing the in and out values to calculate the 95th percentile, which is resulting in inaccurate data.
![02ecaabc2fb41ff548636420e0560ca](https://github.com/user-attachments/assets/b9667d3d-83a7-4842-89e7-59377131143f)

This approach essentially sums the inbound and outbound traffic at the same time point before calculating the maximum value, which is not what I want. Instead, I need to sum the outbound traffic separately and the inbound traffic separately, and then calculate the maximum value for each at the same time point.

To achieve this, I thought of changing max to aggregate_max, resulting in HRULE: |95:bits:0:aggregate_max:2| and COMMENT: |95:bits:9:aggregate_max:2| G<HR>. For the individual interfaces, eth-trunk20 and eth-trunk44, the data collection works fine, but when aggregating eth-trunk20 and eth-trunk44, the 95th percentile graph shows abnormal values.
aggregating config
![image](https://github.com/user-attachments/assets/55629271-b176-4102-a766-13b5fb7fa7f7)

bug 
![image](https://github.com/user-attachments/assets/b59d86af-31ee-4a1e-a98e-715d49f93ae3)
