### ISSUE TITLE
How to monitor multiple remote sites with single Cacti

### ISSUE THREAD

**Issue by enrikio** [Cacti/cacti#5659]
Did any of you successfully implement Cacti on one site, for it to monitor multiple sites/networks (Company monitoring multiple customers networks with single Cacti)? I have a few questions:

• What can be done when some remote sites eventually have same network segment?
• What is the safest way to talk with remote clients (Lack of SNMP v3 on Windows is also a big security question here)? I suppose site to site vpn and with specific ports open?
• Are there any agent versions, which can be installed on remote clients to talk with cacti?
• Your other experience regarding this topic please.

**Comment by cigamit** [comment]
You already asked this question twice on the forums.  The issue tracker is for tracking issues with the software, its not a consumer forum.
