### ISSUE TITLE
"Toggle Threshold VRULES On" is broken

### ISSUE THREAD

**Issue by dsclassen** [Cacti/cacti#566]
Attempting to toggle vrules on results in the following errors:

![vrule_error](https://cloud.githubusercontent.com/assets/8882563/25014748/d886b7ee-202d-11e7-8bb2-c5eb00ce35b0.png)

Which appears to be complaining about this snippit of code:

```
	$(function() {
		navHeight    = $('.cactiTreeNavigationArea').height();
		windowHeight = $(window).height();
		navOffset    = $('.cactiTreeNavigationArea').offset();
		if (navHeight + navOffset.top < windowHeight) {
			$('.cactiTreeNavigationArea').height(windowHeight - navOffset.top);
		}
	});
```

**Comment by cigamit** [comment]
I'm confused, is this a thold issue?

**Comment by cigamit** [comment]
Thold issue.  Please open there.
