### ISSUE TITLE
Create New Graph from WEB (RRD permissions)

### ISSUE THREAD

**Issue by bmcgoncalves** [Cacti/cacti#567]
Hi,

When a graph is created from the "new graphs" option in Cacti then the RRD is created in filesystem with permissions only for the owner.

ls -lrt /path/rra/35/145865.rrd
-rw-r--r-- 1 apache apache 235288 Apr 14 08:02 /path/rra/35/145865.rrd

The pooler in crontab is running in another user so i think the rrd cannot be updated. I have holes in the graphs,
I cannot explain the holes but when i changed the rrd permissions to 777 the lines in graphs started do appear.
I found this issue because in real time is working fine and in the normal pooling is not working well.

**Comment by cigamit** [comment]
That is how Linux works.  To work around it, you can setgid the rra directory.
https://en.wikipedia.org/wiki/Setuid
