### ISSUE TITLE
Bug in module api_automation.php - function strtotime() 

### ISSUE THREAD

**Issue by mabps** [Cacti/cacti#5685]
# Describe the bug
I have installed Cacti from the standard Debian repository, on a clean system, during the installation process has been installed all the necessary dependencies himself. 
After installing and running it, i have some errors in the Cacti logs.

<html>
<body>

2024-02-28 15:15:33 - CMDPHP PHP ERROR WARNING Backtrace: (/poller_automation.php[231]:api_automation_is_time_to_start(), /lib/api_automation.php[3637]:strtotime(), CactiErrorHandler())
--
2024-02-28 15:15:33 - ERROR PHP WARNING: strtotime(): Epoch doesn't fit in a PHP integer in file: /usr/share/cacti/site/lib/api_automation.php on line: 3637

</body>
</html>

## To Reproduce

1. Go to http://localhost/cacti/clog.php

2. See error

## Screenshots

![image](https://github.com/Cacti/cacti/assets/95409148/0e926c9b-9340-486a-8f0a-bef614aaa5d6)

## Desktop (please complete the following information)

- Debian 12/5 
- PHP 8.2.7 (cli) (built: Jun  9 2023 19:37:27) (NTS)

- Package: cacti
Version: 1.2.24+ds1-1+deb12u1
Priority: optional
Section: web
Maintainer: Cacti Maintainer <pkg-cacti-maint@lists.alioth.debian.org>
Installed-Size: 48.1 MB
Depends: dbconfig-common, dbconfig-mysql | dbconfig-no-thanks, fonts-dejavu-core, fonts-dejavu-extra, fonts-fork-awesome, javascript-common, libapache2-mod-php | php, libjs-chart.js, node-d3, libjs-jquery, libjs-jquery-cookie, libjs-jquery-hotkeys, libjs-jquery-metadata, libjs-jquery-tablesorter, libjs-jquery-timepicker, libjs-jquery-ui, libjs-jquery-ui-touch-punch, libphp-phpmailer (>= 6.1.5~), node-ua-parser-js, php-cli, php-gd, php-json, php-gmp, php-ldap, php-mbstring, php-mysql, php-phpmyadmin-motranslator, php-phpseclib, php-snmp, php-twig, php-xml, rrdtool, snmp, ucf, debconf (>= 0.5) | debconf-2.0, libjs-jquery-colorpicker (>= 1.2.20), libjs-jquery-jstree (>= 3.3.12+dfsg1), libjs-jquery-ui-theme-smoothness (>= 1.12.1+dfsg), libjs-jquery-ui-theme-south-street (>= 1.12.1+dfsg), libjs-jquery-ui-theme-ui-darkness (>= 1.12.1+dfsg), perl:any
Recommends: apache2 | lighttpd | nginx | httpd, default-mysql-server | virtual-mysql-server, inetutils-ping | iputils-ping, logrotate
Suggests: cacti-spine, moreutils, snmpd
Homepage: https://www.cacti.net/
Tag: admin::monitoring, implemented-in::php, interface::web, role::program,
 use::monitor, works-with::db
Download-Size: 28.2 MB
APT-Manual-Installed: yes
APT-Sources: http://deb.debian.org/debian bookworm/main i386 Packages
Description: web interface for graphing of monitoring systems

**Comment by mabps** [comment]
This error occurs only on the x86 platform version on which I installed the Cacti
I think this was my mistake - choosing the x86 platform is not correct, the error does not occur on Debian x64.
I consider the ticket closed.

**Comment by mabps** [comment]
closed

**Comment by TheWitness** [comment]
Oh wait, you are in a funky timezone right GMT +5.5?  Please confirm?

**Comment by mabps** [comment]
> Oh wait, you are in a funky timezone right GMT +5.5? Please confirm?

Hi, no - my timezone = +3 (Moscow) 
  - system time is +3h = 15:00 
  - but Cacti logs write +0 = 12:00 
  where it's can be fixed i'm not find still

**Comment by TheWitness** [comment]
That should work.  Can you upgrade to 1.2.26?

**Comment by mabps** [comment]
> That should work. Can you upgrade to 1.2.26?

unfortunately, I can't check now - I reinstalled the system to the x64 version and the problem resolved.

**Comment by TheWitness** [comment]
Okay.  We'll leave it as is then.
