### ISSUE TITLE
About search box and base64！

### ISSUE THREAD

**Issue by aliuzzz** [Cacti/cacti#5686]
I enter English in the search box, everything works fine, but when I enter Chinese, the search text will appear encrypted to base64 format, and then search again.For example

![image](https://github.com/Cacti/cacti/assets/43594093/e624ba64-b5ca-4326-aa68-6fbd8e672dc8)

https://github.com/Cacti/cacti/assets/43594093/f29a35a7-83db-4093-ba73-d2ee4fde2939

**Comment by aliuzzz** [comment]
PHP 8.0.30
MariaDB-10.5.22
Apache/2.4.37
net-snmp 5.8
if i update php version or mariadb version，can solve this problem？

**Comment by TheWitness** [comment]
Did it start working?
