### ISSUE TITLE
In Cacti 1.2.26, after aggregation, only the 95th percentile values are calculated for the outbound direction

### ISSUE THREAD

**Issue by datutu58888** [Cacti/cacti#5689]
In Cacti 1.2.26, after aggregation, only the 95th percentile values are calculated for the outbound direction, and there are no statistics calculated for the inbound direction.

There is no such issue in version 1.2.24.
I haven't made any special settings in either version, and they are basically in their default state. Furthermore, I have compared the parameters with version 1.2.24 and found no differences.
![QQ图片20240313164554](https://github.com/Cacti/cacti/assets/138114577/69df57e3-ab98-48d1-8a65-009d4e1f5bb4)
![QQ图片20240313164912](https://github.com/Cacti/cacti/assets/138114577/62a310c8-047d-44aa-ac0a-1bec0031862d)

The Cacti system is a completely new installation.
Centos 7.9
PHP 7.4
mysql 5.7
RRdtool 1.48
NET-SNMP version: 5.7.2

Thanks in advance for your reply.

In Cacti 1.2.24, it functions normally; even if there is no outbound traffic, it can still calculate the 95th percentile value for inbound traffic.

![QQ图片20240313165133](https://github.com/Cacti/cacti/assets/138114577/91865744-8c7a-46ce-8394-be5d0242100f)

cacti 1.2.26 only calculates the 95th percentile for outbound traffic, not for inbound traffic. Is this a functional change or a bug? In version 1.2.24, it would calculate the higher of the two for the 95th percentile. Thank you.

**Comment by datutu58888** [comment]
I have been posting a question on a forum, but no one has replied to me. Actually, if there is anyone else using Cacti 1.2.26 and not experiencing the same issue as me, where the 95th percentile value is normal, then I can test it myself and prove that the problem lies in my installation process. I am concerned that my installation process is causing unnecessary trouble for the developers. My installation process is identical to that of version 1.2.24, and I am using the same dependency platform, which I am already very familiar with. Thank you!

**Comment by aliuzzz** [comment]
It is correct in version<1.2.25.
In version 1.2.26, # 12 may need to be adjusted for inbound and outbound.
Also, I think version 1.2.25 is more user-friendly, but the exported CSV table is incorrect

**Comment by aliuzzz** [comment]
@datutu58888 hope we can discuss together

**Comment by datutu58888** [comment]
> It is correct in version<1.2.25. In version 1.2.26, # 12 may need to be adjusted for inbound and outbound. Also, I think version 1.2.25 is more user-friendly, but the exported CSV table is incorrect

Thank you for your reply. So, in version 1.2.25, the aggregated template automatically calculates the 95th percentile values based on the direction of the traffic flow, right? For version 1.2.26, I also suspect there have been functional adjustments. I believe my installation is correct. When you mentioned issues with the CSV export data in 1.2.25, are you referring to discrepancies between the exported maximum values and the ones displayed in the graphs?

**Comment by datutu58888** [comment]
If the developers have made functional choices in version 1.2.26 of Cacti for the 95th percentile values in the inbound and outbound directions, I suppose I may need to revert back to version 1.2.25. The developers are unlikely to accept my request to revert the changes. I suspect that the developers may have considered issues raised by other users and made adjustments regarding the problem of multiple 95th percentiles only displaying as a single 95th percentile in the aggregated template graphs. It's also possible that we might need to create our own interface templates to include the 95th percentile for the inbound direction and then create aggregated templates based on these interface templates. However, it's strange that my 1.2.26 aggregated template does not calculate the 95th percentile for the inbound direction, but when I check each individual interface separately, the 95th percentile is normal and it does calculate the 95th percentile.

**Comment by datutu58888** [comment]
> @datutu58888 hope we can discuss together
The reason why I am reluctant to revert to version 1.2.25 is that version 1.2.26 has fixed more vulnerabilities.

**Comment by aliuzzz** [comment]
@datutu58888  What is your email or other contact information and would like to get in touch

**Comment by datutu58888** [comment]
> @datutu58888 What is your email or other contact information and would like to get in touch

info@zj-idc.com 

or telegram ?

**Comment by TheWitness** [comment]
Sorry guys, I've been taking a bit of a sabbatical after some family illnesses.  No, not me, but you know.  I think the problem here is in the code.  For aggregate, if memory serves me right, I only permitted one Aggregate HRULE per graph.  So, that's obviously flawed here would you not say?

**Comment by datutu58888** [comment]
> Sorry guys, I've been taking a bit of a sabbatical after some family illnesses. No, not me, but you know. I think the problem here is in the code. For aggregate, if memory serves me right, I only permitted one Aggregate HRULE per graph. So, that's obviously flawed here would you not say?

I did notice that you haven't logged in here in March. I hope your family members recover soon!

Are you suggesting that my problem is caused by a PHP bug? I am using a translation system to communicate with you, and sometimes the translation may not be very accurate.

**Comment by datutu58888** [comment]
> Sorry guys, I've been taking a bit of a sabbatical after some family illnesses. No, not me, but you know. I think the problem here is in the code. For aggregate, if memory serves me right, I only permitted one Aggregate HRULE per graph. So, that's obviously flawed here would you not say?

If this problem is caused by a PHP code error, approximately how long will it take to fix?

If only calculating the 95th percentile value for a specific direction is considered as an improvement, how should I implement the functionality of aggregating the 95th percentile values in a template?

**Comment by datutu58888** [comment]
If this problem is caused by a PHP code error, how long will it take to fix it?

If only counting the 95 value in the outgoing direction is a functional improvement, then how should I implement the 95 value function in the incoming direction of the aggregation template?

**Comment by TheWitness** [comment]
Post your base graph Template Items screen, and the Aggregate Template, not the bottom portion, but the top portion including the summation rules.  It's pretty important.  It has to be a case that I have not considered in the creation/migration of the Aggregate plugin into core Cacti.  Since the first several releases did not support the nth percentile stuff, I'm not surprised.

**Comment by TheWitness** [comment]
When your in-laws or any family member becomes frail and pass away, it disrupts family life as it once was.  It's the way life was intended to go.  So, it is what it is.  As I like to say "we are next".  Not for a while I hope.

**Comment by datutu58888** [comment]
> When your in-laws or any family member becomes frail and pass away, it disrupts family life as it once was. It's the way life was intended to go. So, it is what it is. As I like to say "we are next". Not for a while I hope.

![Screenshot_20240316_231114_com android chrome](https://github.com/Cacti/cacti/assets/138114577/4832117d-9709-4dd1-aeac-67c87c612c64)
![Uploading Screenshot_20240316_231123_com.android.chrome.jpg…]()

**Comment by datutu58888** [comment]
![Uploading Screenshot_20240316_231123_com.android.chrome.jpg…]()

**Comment by datutu58888** [comment]
> Post your base graph Template Items screen, and the Aggregate Template, not the bottom portion, but the top portion including the summation rules. It's pretty important. It has to be a case that I have not considered in the creation/migration of the Aggregate plugin into core Cacti. Since the first several releases did not support the nth percentile stuff, I'm not surprised.

![Screenshot_20240316_231114_com android chrome](https://github.com/Cacti/cacti/assets/138114577/fa4a4c6f-14cd-46c8-9708-74efcad9d744)
![Screenshot_20240316_231123_com android chrome](https://github.com/Cacti/cacti/assets/138114577/da6960c4-3bac-4ca5-b57c-d7f405847d80)

**Comment by datutu58888** [comment]
The graphics you sent, are they what you wanted? I am ready to cooperate and assist you at any time! Thank you.

> 发布您的基本图表模板项目屏幕和聚合模板，不是底部部分，而是包括求和规则的顶部部分。这非常重要。这一定是我在将 Aggregate 插件创建/迁移到核心 Cacti 时没有考虑到的情况。由于前几个版本不支持第 n 个百分位的内容，因此我并不感到惊讶。



> Post your base graph Template Items screen, and the Aggregate Template, not the bottom portion, but the top portion including the summation rules. It's pretty important. It has to be a case that I have not considered in the creation/migration of the Aggregate plugin into core Cacti. Since the first several releases did not support the nth percentile stuff, I'm not surprised.

The graphics you sent, are they what you wanted? I am ready to cooperate and assist you at any time! Thank you.

**Comment by datutu58888** [comment]
> Post your base graph Template Items screen, and the Aggregate Template, not the bottom portion, but the top portion including the summation rules. It's pretty important. It has to be a case that I have not considered in the creation/migration of the Aggregate plugin into core Cacti. Since the first several releases did not support the nth percentile stuff, I'm not surprised.

The graphics you sent, are they what you wanted? I am ready to cooperate and assist you at any time! Thank you.

**Comment by TheWitness** [comment]
Okay, I've made an update, but I also see a functional gap.  Let's say you want to track inbound and outbound separately.  Please test and provide feedback.

**Comment by datutu58888** [comment]
> Okay, I've made an update, but I also see a functional gap. Let's say you want to track inbound and outbound separately. Please test and provide feedback.

I copied the code you provided for the update into my Cacti, then followed your instructions to edit my aggregation template, and it worked after saving
![Uploading IMG_20240317_022330.jpg…]()

**Comment by datutu58888** [comment]
> Okay, I've made an update, but I also see a functional gap. Let's say you want to track inbound and outbound separately. Please test and provide feedback.

I copied the code you provided for the update into my Cacti, then followed your instructions to edit my aggregation template, and it worked after saving
![IMG_20240317_022330](https://github.com/Cacti/cacti/assets/138114577/e76c9b96-be20-43f0-b51e-7669a048684f)

**Comment by datutu58888** [comment]
> Okay, I've made an update, but I also see a functional gap. Let's say you want to track inbound and outbound separately. Please test and provide feedback.

I found an issue: I used your updated code to fix the aggregation for two ports and ten ports, but the red line for the 95th percentile on the graphs for the 40-port aggregation has disappeared.
![IMG_20240317_022459](https://github.com/Cacti/cacti/assets/138114577/020763f9-66c2-4c4c-be8c-5145efbdb8e1)

Of course, this issue may not be caused by your code. Perhaps I need to rebuild the aggregation graphs?

**Comment by TheWitness** [comment]
I think you need to add a fixed maximum greater than the current.  The problem here is that it's "sum", so, you should stack the In/Out and then it should be large enough to show the red line that's currently greater than the graph maximum.

**Comment by TheWitness** [comment]
Your source Graph Template may be need some Re-Sync'ing too.  Those line breaks are off.  I'm going to mark this resolved.

**Comment by datutu58888** [comment]
> Your source Graph Template may be need some Re-Sync'ing too. Those line breaks are off. I'm going to mark this resolved.

Are there any issues with the 95th percentile values of these two graphs? 
Have you modified the PHP code for the aggregation template's 95th percentile to include both inbound and outbound traffic? In previous versions, it would automatically choose the direction with higher traffic to calculate the 95th percentile.
![E8K)`%ABUZIZX2({3T1QYQR](https://github.com/Cacti/cacti/assets/138114577/8e52ee35-385d-42f1-bb20-8d089ab152d4)
![F0CPW$C$R1IT4~B 2){AQ8L](https://github.com/Cacti/cacti/assets/138114577/326e2a34-5ef2-4ffc-a1f0-c965b823a2b8)

**Comment by datutu58888** [comment]
> Your source Graph Template may be need some Re-Sync'ing too. Those line breaks are off. I'm going to mark this resolved.

I have a bad feeling that maybe both of us made a mistake. The 95th percentile calculation method in 1.2.26 seems to be correct, but I found that the method used in versions prior to 1.2.5 was incorrect. This is because when I looked at the graph template from 1.2.24, the configuration is the same as in 1.2.26, but the 95th percentile values are calculated higher. Perhaps not having any adjustments to the 95th percentile calculation method after 1.2.26 is the right approach?

this is cacti 1.2.24
The following three graphs are in the default state of Cacti 1.2.24. I suspect that this error exists in previous versions as well. The configuration does not specify statistical inbound direction for the 95th percentile. Of course, I may be mistaken.
![Screenshot_20240317_030204](https://github.com/Cacti/cacti/assets/138114577/901d0550-1fb4-437a-8a0e-d18aa35e5d15)
![Screenshot_20240317_030256](https://github.com/Cacti/cacti/assets/138114577/4f6eea44-b24b-4096-b0d0-27a69809508c)
![Screenshot_20240317_030330](https://github.com/Cacti/cacti/assets/138114577/6847e49f-cb50-4a64-bb21-cd42b7bf892a)

**Comment by aliuzzz** [comment]
> 我有一种不好的预感。也许我们俩都犯了一个错误。1.2.26 中的第 95 个计数方法是正确的。默认配置不应在传入方向上计算第 95 个。我发现 1.2.6 之前版本中的第 95 个方法可能不正确？我查看了之前的 1.2.24 图形模板。配置与 1.2.26 相同，但值 95 会自动选择流量较大的方向进行统计和展示（虽然这是一件好事）。在 1.2.26 之后，就没有方向了。也许第 95 次是对的？我认为 1.2.24 的默认配置不应显示传入方向 95th。

Yes, ≤ 1.2.25 version, it will automatically display a larger one, 1.2.26 need to manually adjust the in or out direction at first. I don't know if this is a bug or a normal adjustment for developers, I didn't see this in the version update information.I hope @TheWitness  bro can explain

**Comment by TheWitness** [comment]
We really need to get comments from users.  Something like a user survey.  Ptiles were never originally supported in aggregate.  I reluctantly added them a few releases ago without much thought.

We've got ~ weeks to figure it out.

**Comment by datutu58888** [comment]
> We really need to get comments from users. Something like a user survey. Ptiles were never originally supported in aggregate. I reluctantly added them a few releases ago without much thought.
> 
> We've got ~ weeks to figure it out.

In China, the ISP billing method adopts a value of 95. The value is only billed for the upstream of the user equipment, that is, the in direction of the monitored switch and the user interface. Downstream is not billed, and some countries and regions will charge it. The sum of in+out is 95th, and the billing value of 95 of the communication operator is the out direction of the device.

**Comment by datutu58888** [comment]
At the ISP billing level, it is best to charge according to the higher price. Regardless of out or in, whichever is higher will be calculated.

**Comment by datutu58888** [comment]
> We really need to get comments from users. Something like a user survey. Ptiles were never originally supported in aggregate. I reluctantly added them a few releases ago without much thought.
> 
> We've got ~ weeks to figure it out.
Hi TheWitness, can you change the way the aggregation template of cacti 1.2.26 counts 95 values ​​back to the previous version，automatic selection of 95 values ​​in a higher direction for display? The in+out method is not suitable for us! I like version 1.2.26 very much. It fixes many problems and I don’t want to go back to the previous version.
 Thank you very much!
