### ISSUE TITLE
Add a device "enabled/disabled" indicator next to the graphs

### ISSUE THREAD

**Issue by bernisys** [Cacti/cacti#5692]
# Feature Request

## Is your feature request related to a problem? Please describe

We have a policy for decommissioning of devices, which states that the graphs should be visible for a certain amount of time after a device was removed, so that people could compare the past time graphs in case a new devices where the capabilities were migrated to is having problems.

But the disabled devices also always rise questions by some people, as we're flagging the NaN areas in a nice yellow background color, so that you can detect on a glance if a graph is still functional. (This should be the default for the existing templates btw .. i can open another request for that. We do that using a RPN, if one data row is "U" then we plot a partly transparent yellow area across the graph with infinite height)

## Describe the solution you'd like

It would be nice to see an icon next to the graph, which clearly shows, if the device is enabled or disabled. A light-bulb icon showing either yellow or grey depending on the state of the device would be quite nice. If there is not enough space, maybe the background of the plot could show a configurable alternate color, or the table cell in which the graph is displayed in the overview page could be greyed out a bit.

## Describe alternatives you've considered

Not showing the disabled devices is not an option, because people still need to see those graphs.

**Comment by TheWitness** [comment]
Not a bad feature requests @bernisys!  Hey @browniebraun, with your work on MidWinter, what do you think is the best approach?  Background color, or a glyph to the right or something else?

**Comment by TheWitness** [comment]
From the team meeting, we will add the 'data-disable=true|false' to the table around the graph for now.

**Comment by TheWitness** [comment]
@bernisys, This was logged as experimental in the commit.  If you would like it for the other themes, feel free to create a pull request.

**Comment by TheWitness** [comment]
![image](https://github.com/Cacti/cacti/assets/1439914/fdb1b3bf-2e4e-4c30-94dc-46c3a9ed2956)

**Comment by bernisys** [comment]
Looks good for me, thanks :)  and we use the standard skin, so we're completely okay.
