### ISSUE TITLE
cacti 1.2.26 regarding template naming issues! After creating a new template, the name of the created graphic template has not changed!

### ISSUE THREAD

**Issue by datutu58888** [Cacti/cacti#5699]
In order to solve the problem that the cacti 1.2.26 aggregation template only counts out 95th and not in 95th, I copied the graphics template interface-Traffic (bit/sec, 95th) to a new template and renamed it, but when creating it for the device interface, Two duplicate templates appeared, and the names were the ones I just copied and created, not the names I renamed!
Is this something I didn't set up? Or is it a bug?

![IMG_20240319_215204](https://github.com/Cacti/cacti/assets/138114577/e0566794-eb89-4e14-a71a-91f33a8e3551)
![IMG_20240319_215233](https://github.com/Cacti/cacti/assets/138114577/28cb0940-a6fb-4232-9225-b9780037bfc7)

**Comment by datutu58888** [comment]
Thank you so much! Looking forward to your reply!

**Comment by OliverZyu** [comment]
![image](https://github.com/Cacti/cacti/assets/44251601/cbe0b631-b810-44cf-8c37-e07162a93f67)
So do i.

**Comment by datutu58888** [comment]
> ![image](https://private-user-images.githubusercontent.com/44251601/314224743-cbe0b631-b810-44cf-8c37-e07162a93f67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4ODM5NzIsIm5iZiI6MTcxMDg4MzY3MiwicGF0aCI6Ii80NDI1MTYwMS8zMTQyMjQ3NDMtY2JlMGI2MzEtYjgxMC00NGNmLThjMzctZTA3MTYyYTkzZjY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDIxMjc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwNGExYjY4ZTllOTBmZWM3YzMzZGU3MTZlODJkN2Q5OWI3ZjE0Zjg3MmJkMWM3NmYyMDhiNzA2NjhhODIzYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bZZwtPsHM-W7IU7o9juvPxqd_cjrFGbey8QWNt1i1wc) So do i.

We all gave the templates the same name. I copied the new one directly before naming it, so my problem is worse than yours, and renaming it is useless! It can only be the name automatically generated after copying! Ha ha

**Comment by datutu58888** [comment]
> ![image](https://private-user-images.githubusercontent.com/44251601/314224743-cbe0b631-b810-44cf-8c37-e07162a93f67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4ODQxNTAsIm5iZiI6MTcxMDg4Mzg1MCwicGF0aCI6Ii80NDI1MTYwMS8zMTQyMjQ3NDMtY2JlMGI2MzEtYjgxMC00NGNmLThjMzctZTA3MTYyYTkzZjY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDIxMzA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5N2MyYTRmZDU3ZDlmNGM3YTVlYzE0NDA0ZWViMGIxOGI1NzAzNmFkNjcyNTUwNjEzNWE3M2VhNmRkNGIwODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-jGg9D23inxL_Qs_UuKIUHFhzjg5Iq5yJIl0hYVySCQ) So do i.

I created the new interface graph template because CACTI 1.2.26 changed the default aggregation template to the 95th way for incoming and outgoing traffic, and the 1.2.26 default aggregation template removed the 95th statistics for incoming traffic, although the developers in the code Fixed this problem and turned it into the 95th sum of the incoming and outgoing directions, which is not what I want. I am more afraid that the developers will definitely do this in version 1.2.27. I am worried that my suggestion will cause more trouble, so I restored the code of 1.2.26 and created a new graphic template to statistically display the 95th of inbound and outbound traffic. That was enough to achieve my purpose.

**Comment by OliverZyu** [comment]
> > ![image](https://private-user-images.githubusercontent.com/44251601/314224743-cbe0b631-b810-44cf-8c37-e07162a93f67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4ODM5NzIsIm5iZiI6MTcxMDg4MzY3MiwicGF0aCI6Ii80NDI1MTYwMS8zMTQyMjQ3NDMtY2JlMGI2MzEtYjgxMC00NGNmLThjMzctZTA3MTYyYTkzZjY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDIxMjc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwNGExYjY4ZTllOTBmZWM3YzMzZGU3MTZlODJkN2Q5OWI3ZjE0Zjg3MmJkMWM3NmYyMDhiNzA2NjhhODIzYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bZZwtPsHM-W7IU7o9juvPxqd_cjrFGbey8QWNt1i1wc) So do i.
> 
> We all gave the templates the same name. I copied the new one directly before naming it, so my problem is worse than yours, and renaming it is useless! It can only be the name automatically generated after copying! Ha ha

Yes, because that's what I'm trying to achieve.😂

**Comment by OliverZyu** [comment]
> > ![image](https://private-user-images.githubusercontent.com/44251601/314224743-cbe0b631-b810-44cf-8c37-e07162a93f67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4ODQxNTAsIm5iZiI6MTcxMDg4Mzg1MCwicGF0aCI6Ii80NDI1MTYwMS8zMTQyMjQ3NDMtY2JlMGI2MzEtYjgxMC00NGNmLThjMzctZTA3MTYyYTkzZjY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDIxMzA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5N2MyYTRmZDU3ZDlmNGM3YTVlYzE0NDA0ZWViMGIxOGI1NzAzNmFkNjcyNTUwNjEzNWE3M2VhNmRkNGIwODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-jGg9D23inxL_Qs_UuKIUHFhzjg5Iq5yJIl0hYVySCQ) So do i.
> 
> I created the new interface graph template because CACTI 1.2.26 changed the default aggregation template to the 95th way for incoming and outgoing traffic, and the 1.2.26 default aggregation template removed the 95th statistics for incoming traffic, although the developers in the code Fixed this problem and turned it into the 95th sum of the incoming and outgoing directions, which is not what I want. I am more afraid that the developers will definitely do this in version 1.2.27. I am worried that my suggestion will cause more trouble, so I restored the code of 1.2.26 and created a new graphic template to statistically display the 95th of inbound and outbound traffic. That was enough to achieve my purpose.

In fact, I'm experiencing the same problem as the issue#5689 you created because of version 1.2.26. Before updating lib/api_aggregate.php, the 95th line only existed as outbound even if the inbound value was greater than the outbound. but after updating the code, the 95th line of the 2-port aggregate graph disappeared and the 95th Percentile value below the graph was summing in+out. line disappeared and the 95th Percentile value below the graph summed in+out. so i am also looking for a solution and also creating in&out 95th is not an ideal solution, that's why i will create the graphs template with the same name as yours!

**Comment by datutu58888** [comment]
I saw some feedback here that cacti graphics cannot display multiple 95ths. The developer may have changed the calculation method of the aggregation template for this reason.

**Comment by datutu58888** [comment]
Our problem is very embarrassing. Cacti is global. In some areas, the value of 95 is billed by the sum of inbound and outbound. Here, I charge a high value. Maybe there is a conflict with other functions that makes it impossible to use a high value! If it continues to waver, it will prevent a group of people from upgrading the version in the future, and upgrading will require changing a lot of settings.

**Comment by datutu58888** [comment]
Our problem is quite awkward. Cacti is global, and in some regions, the 95th percentile value is calculated by summing inbound and outbound traffic, while here it is calculated based on the higher value.

**Comment by datutu58888** [comment]
![Screenshot_20240320_133527](https://github.com/Cacti/cacti/assets/138114577/0fb7f545-476b-4c06-8f64-366353efad92)
The picture shows the effect of changing the template. The first traffic graph shows the values ​​of inbound and outbound 95 respectively. The third traffic graph is the original 1.2.26 state, with only the value of outbound 95.

**Comment by datutu58888** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/44251601/314224743-cbe0b631-b810-44cf-8c37-e07162a93f67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4ODM5NzIsIm5iZiI6MTcxMDg4MzY3MiwicGF0aCI6Ii80NDI1MTYwMS8zMTQyMjQ3NDMtY2JlMGI2MzEtYjgxMC00NGNmLThjMzctZTA3MTYyYTkzZjY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDIxMjc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwNGExYjY4ZTllOTBmZWM3YzMzZGU3MTZlODJkN2Q5OWI3ZjE0Zjg3MmJkMWM3NmYyMDhiNzA2NjhhODIzYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bZZwtPsHM-W7IU7o9juvPxqd_cjrFGbey8QWNt1i1wc) So do i.
> > 
> > 
> > We all gave the templates the same name. I copied the new one directly before naming it, so my problem is worse than yours, and renaming it is useless! It can only be the name automatically generated after copying! Ha ha
> 
> Yes, because that's what I'm trying to achieve.😂

There are certain flaws in my method. It is difficult to identify small customers. I suggest you change it back to dealing with 95th on high principles.

**Comment by datutu58888** [comment]
To address the issue of Cacti 1.2.26 only calculating outbound but not inbound for the 95th percentile values, I added items 14 and 15 to the graph template and selected them in the Inbound Data Source. I found that the aggregated graph can display outbound and inbound values properly, but the Interface - Traffic graph for individual interfaces still shows combined inbound and outbound values. This might be due to the way the original template handles statistics. If that's the case, I recommend modifying the aggregation template code to follow separate statistical principles.
![1](https://github.com/Cacti/cacti/assets/138114577/2fbbb593-9f19-4dc3-b153-9309a0d8df42)

The 95th percentile values for outbound and inbound are displayed correctly in the aggregated graph
![2](https://github.com/Cacti/cacti/assets/138114577/78b1c672-4dc5-49c2-b4dc-45beaad61727)

On the original template, the individual interface is not displaying correctly again. The inbound and outbound values are the same...
![3](https://github.com/Cacti/cacti/assets/138114577/64699550-dde1-493d-9d2e-56f626d78b91)

I suggest that the statistical method of 95th should be restored to the state before version 1.2.25. According to the inbound and outbound of the graph, the 95th should be displayed in a higher direction

**Comment by TheWitness** [comment]
So, what is the request here? I'm confused.

**Comment by TheWitness** [comment]
Okay, I get it now.  Yea, the fact that it's labeled "in + out" makes it very confusing.  I'll have to think about this one.

**Comment by datutu58888** [comment]
> Okay, I get it now. Yea, the fact that it's labeled "in + out" makes it very confusing. I'll have to think about this one.

You misunderstood what I meant. The first post of the main body reflected a bug in the code, that is, there was no way to change the name of the graphic template I created! Thanks

The translator is not very accurate!

**Comment by datutu58888** [comment]
> So, what is the request here? I'm confused.

When I created a new template and created a monitoring chart on the device, I found two more templates when I selected the template, and changing the name of the template did not take effect! This is what the theme wants to express!

**Comment by TheWitness** [comment]
You need to edit the underlying Data Query which is where the title in the Graphs new interface comes from.  So, it's a minor training issue.

**Comment by TheWitness** [comment]
Also, I get you, which is why I was confused too. There appeared to be multiple issues in this ticket.

**Comment by datutu58888** [comment]
> Also, I get you, which is why I was confused too. There appeared to be multiple issues in this ticket.
There are indeed multiple problems. The bottom one is that the 1.2.26 aggregation template has an error in the parameter definition of the Max 95 value. I changed it to the agg parameter and it worked fine. The original MAX parameter can be counted as inbound. To obtain the value of 95, the AI ​​must first be changed to the agg parameter.

**Comment by TheWitness** [comment]
I'm going to close this one.  If there is still an issue, please open a separate request.
