### ISSUE TITLE
Preview Mode: No graphs after page refresh

### ISSUE THREAD

**Issue by bmcgoncalves** [Cacti/cacti#570]
In preview mode if i have a filter to show some graphs and wait until the refresh, then no graphs appears.
The count of the graphs are ok, but the graphs are not showing up.
To get the graphs appering again i need to change the filter in the number of graphs to show.

**Comment by cigamit** [comment]
I tried to reproduce this and could not.  You have to give 'very' specific instructions.  Basically, we need a repeatable case starting with a login, then to the graphs tab, and then what filters, etc.  We need exact steps.

**Comment by bmcgoncalves** [comment]
Hi, i also tried to reproduce the problem and now i dont have the issue. 
I will update the ticket when its possible to reproduce the issue, maybe a combination of filters.
I'm not the only one experiencing this issue in our cacti (1.1.2)

**Comment by bmcgoncalves** [comment]
I can't reproduce this anymore. You can close this issue.
