### ISSUE TITLE
Regarding the small problem of the aggregation template, the Maxinum item is wrapped separately!

### ISSUE THREAD

**Issue by datutu58888** [Cacti/cacti#5700]
Regarding the small problem of the aggregation template, the Maxinum item is wrapped separately!

cacti 1.2.24
cacti 1.2.25
cacti 1.2.26

![Screenshot_20240319_221340](https://github.com/Cacti/cacti/assets/138114577/b7608ba8-ccc0-4664-92f6-089eece2168e)
![Screenshot_20240319_221222](https://github.com/Cacti/cacti/assets/138114577/0425c34e-29b9-4541-a1fd-bd14a9111f97)
![Screenshot_20240319_221738](https://github.com/Cacti/cacti/assets/138114577/bf43ec2b-495a-475f-a503-6c16e6683c1d)

**Comment by OliverZyu** [comment]
I have the same configuration and environment as you, but mine is fine, maybe it's a web adaptive issue, the difference is that I'm using a pc browser.
![image](https://github.com/Cacti/cacti/assets/44251601/9c954d3b-6670-44b5-9430-b8e5275ee204)

**Comment by datutu58888** [comment]
> I have the same configuration and environment as you, but mine is fine, maybe it's a web adaptive issue, the difference is that I'm using a pc browser. ![image](https://private-user-images.githubusercontent.com/44251601/314227096-9c954d3b-6670-44b5-9430-b8e5275ee204.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4ODM4MjMsIm5iZiI6MTcxMDg4MzUyMywicGF0aCI6Ii80NDI1MTYwMS8zMTQyMjcwOTYtOWM5NTRkM2ItNjY3MC00NGI1LTk0MzAtYjhlNTI3NWVlMjA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDIxMjUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1ZWU5YTQwMTk2YWJjYTQ4MzI3ZWIzM2RmNzQ0OTQ0YTlkNjVjM2MyYTU4YzkzZmUwZTIwNTkzYjQyMjg1YTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W9H1PBSFgd3dzXHoUFCFrYjZ-R5y5kkE6LRu0NXm3S8)

When I use the Chrome browser on my computer, the line breaks automatically!

**Comment by TheWitness** [comment]
Re-Sync the Graph Template and then re-save the Aggregate Template.

**Comment by datutu58888** [comment]
> Re-Sync the Graph Template and then re-save the Aggregate Template.

I don't quite understand the first thing you mean. How are synchronization templates synchronized? I know that saving an aggregation means saving the aggregation once without making any changes. Thanks

**Comment by xiongminping** [comment]
![image](https://github.com/Cacti/cacti/assets/113511764/1e0be434-43d4-41ff-80df-4f765f255e4c)
你的这个95th in和out分开的图形模板里面具体配置项能截图看下不

**Comment by datutu58888** [comment]
> ![image](https://private-user-images.githubusercontent.com/113511764/315242495-1e0be434-43d4-41ff-80df-4f765f255e4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMjc5NTYsIm5iZiI6MTcxMTAyNzY1NiwicGF0aCI6Ii8xMTM1MTE3NjQvMzE1MjQyNDk1LTFlMGJlNDM0LTQzZDQtNDFmZi04MGRmLTRmNzY1ZjI1NWU0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMVQxMzI3MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNWY3OTMzNWM3NDczMjUxNWIxNjBhODBjYTkwNTZjODJmODVkYjQ1NWRjMDA2ZDdkZjU2NDNmZmY0MmNlOGQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SS0WV0ry4o6WFexHLFjMwgMZ2qvXsqgUeAGgiF1khEE) 你的这个95th in和out分开的图形模板里面具体配置项能截图看下不

截图里就是具体配置了.唯一区别就是inbound

**Comment by xiongminping** [comment]
这是我的，不知道为什么和你的模板一样，但是不能出图


758254946
***@***.***









&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Cacti/cacti"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月21日(星期四) 晚上9:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Cacti/cacti] Regarding the small problem of the aggregation template, the Maxinum item is wrapped separately! (Issue #5700)





  
 你的这个95th in和out分开的图形模板里面具体配置项能截图看下不
  
截图里就是具体配置了.唯一区别就是inbound

**Comment by datutu58888** [comment]
> 这是我的，不知道为什么和你的模板一样，但是不能出图 758254946 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Cacti/cacti" ***@***.***&gt;; 发送时间:&nbsp;2024年3月21日(星期四) 晚上9:28 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Cacti/cacti] Regarding the small problem of the aggregation template, the Maxinum item is wrapped separately! (Issue #5700) 你的这个95th in和out分开的图形模板里面具体配置项能截图看下不 截图里就是具体配置了.唯一区别就是inbound — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

你的目的是什么?

**Comment by TheWitness** [comment]
![image](https://github.com/Cacti/cacti/assets/1439914/9c083690-08c0-4638-9509-17edf12ffe56)

**Comment by TheWitness** [comment]
Once you sync, make sure you re-save your Aggregates for Non-Templated Aggregates or Aggregate Templates for Templated Aggregates.
