### ISSUE TITLE
Single Device Graph showing different data on 2 Cacti Servers

### ISSUE THREAD

**Issue by sdiwakar123** [Cacti/cacti#5709]
Hi We have 2 Cacti Servers were we have added a device on both Servers.
We have observed that Graph data showing different data on both Cacti Servers. We have recently upgraded 1 Cacti Server to version 1.2.25 and other Cacti Server version is 1.2.14.

![image](https://github.com/Cacti/cacti/assets/76724933/6d615b55-61ec-49d8-a5c8-d9d4e3ef618f)
Cacti version:1.2.25

![image](https://github.com/Cacti/cacti/assets/76724933/0a5e9367-07e6-4451-8b1c-8cee5caf4ca0)
Cacti version 1.2.14

Kindly help us to find the root cause.

Thanks

**Comment by TheWitness** [comment]
You need to ensure that you are creating 64 bit graphs, and that the RRDfile max values are correct for the ifHighSpeed for the device is correct.  Often times, this problem comes from an ifHighSpeed that reports incorrect information.

Use the `rrdtool info $filename` on both files and check the max values on the two RRA's.

**Comment by sdiwakar123** [comment]
Hi both Graph are 64 bit only. only the difference is Cacti version.
If you want i can provide you rrd info of both graph.

**Comment by TheWitness** [comment]
What happened when you ran rrdtool info on the two files?  I suspect in the data source you had differences.

![image](https://github.com/Cacti/cacti/assets/1439914/dacd3e97-8c4b-450e-88c7-d164f91bfd95)

**Comment by sdiwakar123** [comment]
![image](https://github.com/Cacti/cacti/assets/76724933/56b8ce7b-6c27-4207-992e-d98a49dc5192)

![image](https://github.com/Cacti/cacti/assets/76724933/de97e47b-2636-4773-8fb7-ac952732171f)

Please see both Graph rrd info report

**Comment by TheWitness** [comment]
Is that the correct max value for the data source?  Is the number up top the bad RRDtool info?  It looks more like a 32 bit OID.  Check the poller cache and make sure the OID's are the same for both systems.

**Comment by sdiwakar123** [comment]
![image](https://github.com/Cacti/cacti/assets/76724933/6e641d3d-729b-495a-ae96-5f028bf3586b)

![image](https://github.com/Cacti/cacti/assets/76724933/b436aaf8-1745-46ea-9958-fe248029ca45)
 Yes you are right the OID is different on both Systems. 
is that could be the reason??

**Comment by xmacan** [comment]
Here it is described 
https://www.cisco.com/c/en/us/support/docs/ip/simple-network-management-protocol-snmp/26007-faq-snmpcounter.html

Maybe you started on your older server with snmp v1 which doesn't support 64bit counters. So 32 bit counters (.1.3.6.1.2.1.2.2.1.10 ) are used. .1.3.6.1.2.1.31.1.1.1  - it is 64 bit counters

**Comment by sdiwakar123** [comment]
I have checked SNMP Version it is showing V2 on both Systems. Any solutions regarding this issue ?

**Comment by xmacan** [comment]
Create new graphs 64bit

**Comment by sdiwakar123** [comment]
Hi  I have created new graph but it is not plotting data in graph. showing NAN in rrdinfo.
but in realtime data is showing.
I have given the permission to the rrd file but no luck. what could be the reason ?

**Comment by TheWitness** [comment]
Run spine at verbosity 3 on the device.  Post the output highlighting thou output for that data source or data sources.

`./spine -V 3 -R -S -H host_id`

Better this be taken up in the forums too.  Bad karma here.
