### ISSUE TITLE
Extend user and usergroup options

### ISSUE THREAD

**Issue by jhonnyx82** [Cacti/cacti#571]
I was looking at limiting user and usergroups to access realtime feature (as my understanding is that it is quite CPU demanding and also potentially dangerous for the polled devices if used by a certain number of users)

So I would like to ask an enhancement for serveral options for user and usergroups like:

realtime access restriction (and other graph features)
page reload timeout

...more to follow as it will come to mind.

Thanks!

**Comment by netniV** [comment]
@jhonnyx82 - I believe that these features actually exist already (realtime access has it's own realm for authentication).  If you think there was something more to this, let me know.  Otherwise, we can close this I think.

**Comment by jhonnyx82** [comment]
Please close this item, it’s an old request
