### ISSUE TITLE
apostrophe characters hard coded on all graphs for the 1st item description/name

### ISSUE THREAD

**Issue by dallenk** [Cacti/cacti#5711]
I just noticed ever graph seems to have additional characters hard coded into every template, which leads me to think it's something in the graph generation scripts and not the templates at all.  

only the 1st item appears this way wrapped in apostrophes
 
![image](https://github.com/Cacti/cacti/assets/2725066/826f0abf-108d-4e72-957e-55889fe1bd44)
![image](https://github.com/Cacti/cacti/assets/2725066/e0ee5dd9-9061-44fd-aada-2990e80d3ac2)
![image](https://github.com/Cacti/cacti/assets/2725066/da39de18-9b3b-48dc-a908-118f8cbd786e)

I took a look through templates, but it's not there.. it doesn't break anything except for my OCD needing things to line up neatly lol

**Comment by xmacan** [comment]
ok, it is 1.3 issue only.

**Comment by xmacan** [comment]
Not all templates are damaged, only with area element
