### ISSUE TITLE
SNMP - Generic OID Template lost its - Multiple Instances flag

### ISSUE THREAD

**Issue by xmacan** [Cacti/cacti#5714]
For several devices I need create host specific generic oid graphs. I can create only one, because  is graph_net.php is SQL query with condition:
``$available_graph_templates = db_fetch_assoc_prepared('SELECT gt.id, gt.name
FROM graph_templates AS gt
LEFT JOIN snmp_query_graph AS sqg
ON sqg.graph_template_id = gt.id
WHERE sqg.name IS NULL
**AND gt.id NOT IN (SELECT graph_template_id FROM host_graph WHERE host_id = ?)**
AND gt.multiple = ""
UNION
SELECT id, name
FROM graph_templates AS gt
WHERE multiple = "on"
ORDER BY name',
array(get_request_var('host_id'))
);

I understand it's a protection against creating identical charts. For generic OID should be exception here.
Tested on actual 1.2.26 and actual 1.2.x branch

**Comment by TheWitness** [comment]
Note the following in the Graph Template @xmacan.  Somehow when we packaged last, we cleared this setting.  Not going to Repackage for 1.2.27.  We just need to track for 1.3.

**Comment by TheWitness** [comment]
Resolved here: bf5fd49102b1675bca8644fb3d5f80fd21eca18e
