### ISSUE TITLE
CactiEZ

### ISSUE THREAD

**Issue by Pepan123** [Cacti/cacti#5715]
CactiEZ 1.2.26 new installation Import template not works
Can you help me please?
Thanks
![image](https://github.com/Cacti/cacti/assets/166505890/d4288a86-7e19-40ff-ab42-61cfc80f4119)

**Comment by TheWitness** [comment]
Can you open your Debug Console in your browser, and try the import again?  I suspect a JavaScript error.  You may have to clear your browser cache for the site in question.

**Comment by Pepan123** [comment]
Hi 
Many thannks for your support, but this error was befor import. This is first click on import template.
Soo let it bee. I will install new server stable version. Not EZ
Thanks

**Comment by TheWitness** [comment]
Okay, but if its repeatable, weigh in again.  This looks more like a post on a page from a submit button.  It's entirely possible, just under what cases.
