### ISSUE TITLE
bug with CLI add_device.php - merging passed CLI parameters with non-enabled 'SNMP Defaults'

### ISSUE THREAD

**Issue by richud** [Cacti/cacti#5718]
Currently have SNMP Defaults set to 'Not in Use'. [Previously was SNMPv3 with AuthPriv]
v1.2.25 in RL9

If I add a device with the CLI (using authnopriv), it tries to use the old settings from the 'Device Defaults > SNMP Defaults' 
sudo php -q add_device.php --description=xxxxxxxxxx --ip=zzzzzzzzzzzzzzz --template=5 --avail=snmp --version=3 --username=uuuuuuuuuuuuu --password=pppppppppppp --authproto=SHA

xxxxxxxxxx (zzzzzzzzzzzzzzz) as "Cisco Router" using SNMP v3 with community "public"
snmpwalk: Unsupported security level
snmpbulkwalk: Unsupported security level
snmpbulkwalk: Unsupported security level
snmpbulkwalk: Unsupported security level
snmpbulkwalk: Unsupported security level
snmpget: Unsupported security level
snmpwalk: Unsupported security level
snmpbulkwalk: Unsupported security level
snmpwalk: Unsupported security level
snmpbulkwalk: Unsupported security level
snmpget: Unsupported security level
Success - new device-id: (764)

If I add like this, specifically setting an empty priv pass/proto it then adds ok - but still populates the GUI with the priv protocol and password with whatever used to be the 'Device Defaults > SNMP Defaults'.

sudo php -q add_device.php --description=xxxxxxxxxxxx --ip=zzzzzzzzzzzzzzz --template=5 --avail=snmp --version=3 --username=uuuuuuuuuuuuuuuu --password=pppppppppppppp --authproto=SHA --privpass='' --privproto=''

Adding xxxxxxxxxxxx (zzzzzzzzzzzzzzz) as "Cisco Router" using SNMP v3 with community "public"
Success - new device-id: (766)

i.e. add & then go to the GUI, it showing device detail output at the top (working) BUT also incorrectly showing a populated  priv protocol and password that it isn't using (from the old defaults). If you then hit save it breaks it, as it starts using these incorrect settings it pulled from the old defaults. Bit strange.

**Comment by TheWitness** [comment]
Can you verify that your version of net-snmp supports sha by running a walk from the command line?  Also, we've made some changes in the 1.2.x branch that will soon be 1.2.27.  You might want to update to the 1.2.x branch once you have verified that you have a recent version of net-snmp.

**Comment by TheWitness** [comment]
No feedback.
