### ISSUE TITLE
New Remote Poller install fails because directory permissions

### ISSUE THREAD

**Issue by eduardomozart** [Cacti/cacti#5719]
# Describe the bug

I created some suggestions about the Cacti Windows Installer about the permissions: https://forums.cacti.net/viewtopic.php?t=62804

The latest version (1.2.26) seems to have some issues that I already reported there.

When installing Cacti 1.2.26 using Windows Installer, the check permissions stage (after successfully) setting up Remote Poller connection, the directory permission check seems to fail but it isn't reported on Cacti UI, the Next button simply doesn't work, but the JSON response seems to return the error, it only isn't being printed on UI.

This error doens't seems to be related to Remote Poller itself but folder permission assignment during Cacti Windows Installer and Cacti Permission JSON parse return response from server, but those errors aren't thrown when installing Cacti without Remote Poller option.

## To Reproduce

1. Go to Cacti browser install.

2. Click on 'Next' on 'Directory Permission Checks'.

3. See error

## Expected behavior

The Cacti installation progresses or the permission error being thrown on screen.

## Screenshots

![image](https://github.com/Cacti/cacti/assets/2974895/731061cf-e4b5-4dcd-8b1f-6a9e9c89f8c8)

```
{"Mode":"2","Step":4,"Errors":{"Permission":{"snmp_queries:C:\/inetpub\/wwwroot\/cacti\/resource\/snmp_queries":"Path was not writable","script_server:C:\/inetpub\/wwwroot\/cacti\/resource\/script_server":"Path was not writable","script_queries:C:\/inetpub\/wwwroot\/cacti\/resource\/script_queries":"Path was not writable","scripts:C:\/inetpub\/wwwroot\/cacti\/scripts":"Path was not writable","csrf:C:\/inetpub\/wwwroot\/cacti\/include\/vendor\/csrf\/csrf-secret.php":"Path was not writable"}},"Eula":true,"Prev":{"Text":"Previous","Step":3,"Enabled":true,"Visible":true},"Next":{"Text":"Next","Step":5,"Enabled":true,"Visible":true},"Test":{"Text":"Test Connection","Step":-4,"Enabled":true,"Visible":false},"Theme":"modern","StepData":{"Sections":{"writable_always":3,"host_access":3}},"Html":"<h2 class='cactiInstallSectionTitle'>Directory Permission Checks<\/h2><p class='cactiInstallSection cactiInstallSectionNormal'>Please ensure the directory permissions below are correct before proceeding.  During the install, these directories need to be owned by the Web Server user.  These permission changes are required to allow the Installer to install Device Template packages which include XML and script files that will be placed in these directories.  If you choose not to install the packages, there is an 'install_package.php' cli script that can be used from the command line after the install is complete.<\/p><p class='cactiInstallSection cactiInstallSectionNormal'>These directories will be required to stay read writable after the install so that the Cacti remote synchronization process can update them as the Main Cacti Web Site changes<\/p><p class='cactiInstallSection cactiInstallSectionNote'><span class=\"cactiInstallSectionNoteTitle\">NOTE:<\/span><span class='cactiInstallSectionNoteBody'>For remote pollers, it is critical that the paths that you will be updating frequently, including the plugins, scripts, and resources paths have read\/write access as the data collector will have to update these paths from the main web server content.<\/span><\/p><\/div><h3 class='cactiInstallSectionTitle' id='host_access'>Potential permission issues<\/h3><div class=\"installSubSection\"><p class='cactiInstallSection cactiInstallSectionNormal'><font color=\"#008000\">All folders are writable<\/font><\/p><\/div><\/div><h3 class='cactiInstallSectionTitle' id='writable_always'>Required Writable after Install Complete<\/h3><div class=\"installSubSection\"><div class='formRow odd'><div class='formColumnLeft'><div class='formFieldName'>C:\\Windows\\TEMP\/<\/div><\/div><div class='formColumnRight'><div class='formData' width='100%'><i class=\"fa fa-thumbs-up\"><\/i> <font color=\"#008000\">Writable<\/font><\/div><\/div><\/div><div class='formRow even'><div class='formColumnLeft'><div class='formFieldName'>C:\/inetpub\/wwwroot\/cacti\/log\/<\/div><\/div><div class='formColumnRight'><div class='formData' width='100%'><i class=\"fa fa-thumbs-up\"><\/i> <font color=\"#008000\">Writable<\/font><\/div><\/div><\/div><div class='formRow odd'><div class='formColumnLeft'><div class='formFieldName'>C:\/inetpub\/wwwroot\/cacti\/cache\/boost\/<\/div><\/div><div class='formColumnRight'><div class='formData' width='100%'><i class=\"fa fa-thumbs-up\"><\/i> <font color=\"#008000\">Writable<\/font><\/div><\/div><\/div><div class='formRow even'><div class='formColumnLeft'><div class='formFieldName'>C:\/inetpub\/wwwroot\/cacti\/cache\/mibcache\/<\/div><\/div><div class='formColumnRight'><div class='formData' width='100%'><i class=\"fa fa-thumbs-up\"><\/i> <font color=\"#008000\">Writable<\/font><\/div><\/div><\/div><div class='formRow odd'><div class='formColumnLeft'><div class='formFieldName'>C:\/inetpub\/wwwroot\/cacti\/cache\/realtime\/<\/div><\/div><div class='formColumnRight'><div class='formData' width='100%'><i class=\"fa fa-thumbs-up\"><\/i> <font color=\"#008000\">Writable<\/font><\/div><\/div><\/div><div class='formRow even'><div class='formColumnLeft'><div class='formFieldName'>C:\/inetpub\/wwwroot\/cacti\/cache\/spikekill\/<\/div><\/div><div class='formColumnRight'><div class='formData' width='100%'><i class=\"fa fa-thumbs-up\"><\/i> <font color=\"#008000\">Writable<\/font><\/div><\/div><\/div><\/div>"}
```

## Desktop (please complete the following information)

- OS: Windows Server 2012

- Browser Chrome

- Version 109

## Additional context

I needed to run the following commands to fix it:

```
icacls "C:\inetpub\wwwroot\cacti\resource\snmp_queries" /grant "IUSR:(OI)(CI)(RX,W)"
icacls "C:\inetpub\wwwroot\cacti\resource\script_server" /grant "IUSR:(OI)(CI)(RX,W)"
icacls "C:\inetpub\wwwroot\cacti\resource\script_queries" /grant "IUSR:(OI)(CI)(RX,W)"
icacls "C:\inetpub\wwwroot\cacti\scripts" /grant "IUSR:(OI)(CI)(RX,W)"
copy /b NUL "C:\inetpub\wwwroot\cacti\include\vendor\csrf\csrf-secret.php"
icacls "C:\inetpub\wwwroot\cacti\include\vendor\csrf\csrf-secret.php" /grant "IUSR:(RX,W)"
```

The file "C:\inetpub\wwwroot\cacti\include\vendor\csrf\csrf-secret.php" doesn't seems to exist so I needed to create it for permissions to be applied on it.

After applying them, the installer continued as expected, but then fails during the installation progress bar, it stops reporting progress and after reloading the page the error is thrown, even if during Cacti Windows Installer, IIS was selected during install:

```
System log file is not available for writing, please enable write access Log: C:/Apache24/htdocs/cacti/log/cacti.log 
```

NOTE: Permission issues does not occurs when installing Cacti Windows Installer using Apache option.

**Comment by TheWitness** [comment]
If you want to help with the installer, that would be good.  We could use some additional help.  I've only tested the install on Apache as I don't use IIS.  So, I'm not surprised you found issues.

**Comment by TheWitness** [comment]
@netniV, can you take this one?

**Comment by eduardomozart** [comment]
> If you want to help with the installer, that would be good. We could use some additional help. I've only tested the install on Apache as I don't use IIS. So, I'm not surprised you found issues.

It would be great, but I was unable to found the Cacti Windows Installer formula/source code to contribute on it. Is it available somewhere?

**Comment by eduardomozart** [comment]
Please notice that this issue affects not only the Windows Installer, but the Cacti itself. The JSON is returning an error, but that isn't being handled by the Cacti Installer UI.

**Comment by TheWitness** [comment]
Understood.  If you are interested, send your VC to developers at cacti dot net.  We uses the NSIS installer for Windows.

**Comment by TheWitness** [comment]
The NSIS installer uses this logic.

![image](https://github.com/Cacti/cacti/assets/1439914/184dedf7-f1ef-4258-9ab6-9511ded14cd2)

**Comment by eduardomozart** [comment]
I'll send a mail. It would be great if this formula could be hosted on GitHub so we can contribute to the installer. It seems that there's missing folders to apply permissions on IIS. This issue doesn't seems to happen on Apache because the installer applies a "AllowAll" permission to the Apache user to the htdocs directory, which doesn't happen on IIS.

**Comment by TheWitness** [comment]
We keep the packaging repo private.  So, we would have to add you to the team.  Send your CV and we will go from there.  I'll be building the Cacti 1.2.27.exe installer today sometime.

**Comment by TheWitness** [comment]
@eduardomozart, I have updated the windows install documentation on GitHub to add your notes.  You should review the changes.  Feel free to open a pull request.

**Comment by eduardomozart** [comment]
I've added a PR to add missing paths to documentation. Not sure how much time it takes to reflect on https://docs.cacti.net/Installing-Under-Windows.md

**Comment by TheWitness** [comment]
Thanks!
