### ISSUE TITLE
"Local Database Connection" shows Remote Poller info instead of local ones

### ISSUE THREAD

**Issue by eduardomozart** [Cacti/cacti#5721]
# Describe the bug

When setting up a Remote Poller after a failed install (#5719), instead of showing the local MySQL connection parameters, it shows the Remoter Poller one instead when reinstalling a existing Cacti Remote Poller instance.

Here's my ``config.php`` file contents:

```
...

/**
 * Make sure these values reflect your actual database/host/user/password
 */

$database_type     = 'mysql';
$database_default  = 'cacti';
$database_hostname = 'localhost';
$database_username = "cactiuser";
$database_password = "your_password";
$database_port     = '3306';
$database_retries  = 5;
$database_ssl      = false;
$database_ssl_key  = '';
$database_ssl_cert = '';
$database_ssl_ca   = '';
$database_persist  = false;

/**
 * When the cacti server is a remote poller, then these entries point to
 * the main cacti server. Otherwise, these variables have no use and
 * must remain commented out.
 */

$rdatabase_type     = 'mysql';
$rdatabase_default  = 'cacti';
$rdatabase_hostname = '168.XXX.X.XXX';
$rdatabase_username = 'cactiuser_XXX';
$rdatabase_password = 'your_password';
$rdatabase_port     = '3306';
$rdatabase_retries  = 5;
$rdatabase_ssl      = false;
$rdatabase_ssl_key  = '';
$rdatabase_ssl_cert = '';
$rdatabase_ssl_ca   = '';

...
```

## To Reproduce

1. Go to Cacti Web Installer.

2. Click on 'New Remote Poller'.

4. See issue

## Expected behavior

It should shows the Local and Remote Poller settings as expected.

## Screenshots

<img width="1029" alt="image" src="https://github.com/Cacti/cacti/assets/2974895/b15a072b-bb18-4db0-be91-c6b623d652bd">

## Desktop (please complete the following information)

- OS: Windows Server 2012

- Browser Chrome

- Version 109

## Additional context

None.

**Comment by TheWitness** [comment]
The $database_blah is from the perspective of the poller in question.  In all remote poller cases the $rdatabase_blah will always point to the main database.

Here is my example for my remote poller.  You can see that $database_hostname is usually "localhost" be it remote or main.  If you have a very big system, your Database may be on another server.  Cacti is fully horizontally scalable that way.

```php
/*
 * Make sure these values reflect your actual database/host/user/password
 */

$database_type     = 'mysql';
$database_default  = 'cacti';
$database_hostname = 'localhost';
$database_username = 'cactiuser';
$database_password = 'cactiuser';
$database_port     = '3306';
$database_rport    = '3306';
$database_retries  = 1;
$database_ssl      = false;
$database_ssl_key  = '';
$database_ssl_cert = '';
$database_ssl_ca   = '';
$database_persist  = false;

/*
 * When the cacti server is a remote poller, then these entries point to
 * the main cacti server. Otherwise, these variables have no use and
 * must remain commented out.
 */

$rdatabase_type     = 'mysql';
$rdatabase_default  = 'cacti';
$rdatabase_hostname = 'vmhost3';
$rdatabase_username = 'cactiuser';
$rdatabase_password = 'cactiuser';
$rdatabase_port     = '3306';
$rdatabase_retries  = 1;
$rdatabase_ssl      = false;
$rdatabase_ssl_key  = '';
$rdatabase_ssl_cert = '';
$rdatabase_ssl_ca   = '';
$rdatabase_persist  = false;

/*
 * The poller_id of this system.  set to `1` for the main cacti web server.
 * Otherwise, you this value should be the poller_id for the remote poller.
 */

$poller_id = 20;
```

**Comment by eduardomozart** [comment]
I see. If it's the intended behavior, I'll close this "issue".

**Comment by TheWitness** [comment]
Yea, it is.  When I wrote this, I used the `$r*`.  I should have used something like `$m*` instead to refer to `main` vs. `remote`.  History is finished, it'll stay that way for the near term.
