### ISSUE TITLE
Remote Poller shouldn't override it's binaries and log paths with Main Poller settings

### ISSUE THREAD

**Issue by eduardomozart** [Cacti/cacti#5722]
# Describe the bug

After setting up a new Remote Poller instance, even it running on IIS and my Main Poller running on Apache, the setup fails during the installation progress bar, it stops reporting progress and after reloading the page the error is thrown, even if during Cacti Windows Installer, IIS was selected during Remote Poller install:

```
System log file is not available for writing, please enable write access Log: C:/Apache24/htdocs/cacti/log/cacti.log 
```

After applying the permission to the file on Remote Poller and attempting to run the Remote Poller installation again, it seems that not only the log path, but also local binaries paths are being replaced by the Main Poller ones.

This doesn't seems to be an expected behavior, because it breaks the Remote Poller setup (as could be seen on cacti.log file above) and also makes impossible have Remote Pollers that uses different file paths or different OSes (e.g. between Linux and Windows Cacti instances), as the file paths are obviously different.

## To Reproduce

1. Attempt to setup a new Remote Poller instance as of #5719 

2. It fails during the progress bar stage. Fix file log permission as of #5719 and applied 'mysql.time_zone_name' "SELECT" right as of #5720.

3. Continue setup as expected.

4. See local path overrides on Remote Poller caused by the failed Cacti Remote Poller setup (step 1) on "Critical Binary Locations and Versions" step.

## Expected behavior

The local binaries path shouldn't be overriden by Main Poller ones.

## Screenshots

<img width="1029" alt="image" src="https://github.com/Cacti/cacti/assets/2974895/3cd5dbb3-d9a3-4106-b04d-91ef4ffc25aa">

## Desktop (please complete the following information)

- OS: Windows Server 2012

- Browser Chrome

- Version 109

## Additional context

It would also be added to this bug report to check if after saving the config on Cacti Main Poller if it overrides the paths on Remote Poller ones.

**Comment by TheWitness** [comment]
We allow the remote poller to have different locations.  Most people use Linux for their main pollers and some use Windows for their remote pollers.  So, we want to be able to use Windows paths on the Windows boxes and Linux paths on the Linux boxes.  Make sense?

**Comment by eduardomozart** [comment]
Yes, it makes sense but it's not what happening on Cacti 1.2.26. When setting up a Remote Poller connection, it's overriding the Remote Poller paths with the Cacti Data Poller (Main Poller) instead.

**Comment by TheWitness** [comment]
Try this with the current 1.2.x branch and see if the defaults are correct anyway.

**Comment by TheWitness** [comment]
Where do you have the Net-SNMP installed?  By default it's C:/usr/bin these days sadly.

**Comment by TheWitness** [comment]
Fixed here: 477ab30410aab3e8fbb566f4a61eddd92e2768ef

**Comment by eduardomozart** [comment]
Hello @TheWitness,
I'm not sure if this bugfix is enough to fix this issue.
This issue happens after installing the Remote Poller. During the Remote Poller install, it seems that it replicates the file path from Main Poller, instead of using the local file paths. E.g., my Main Poller uses Apache, the Remote Poller uses IIS. After deploying the Remote Poller, the Remote Poller fails to load the Web UI because there was no access to the ``C:\Apache24\htdocs\cacti\log\cacti.log`` file (#5719), which doesn't make any sense because my instance uses IIS and it was writing the log to ``C:\inetpub\wwwroot\cacti\log\cacti.log`` as expected and no permissions error was being thrown during the initial setup. It seems that Remote Poller is overriding it's file paths accordingly to the Main Poller, which shouldn't be happening. To fix this issue, I needed to deploy my Remote Poller as Apache too and reinstalled the Net-SNMP on Main Poller on the default path (``C:\usr``), so the folder paths between Main Poller and Remote Poller matches.

**Comment by TheWitness** [comment]
That's possible.  I know we covered the binaries, and any setting with '%path%' in it.  So, the cacti.log should have been covered.  But the initial value may be assumed otherwise. It's fixable of course.
