### ISSUE TITLE
Unable to edit Remote Data Collectors settings

### ISSUE THREAD

**Issue by eduardomozart** [Cacti/cacti#5724]
# Describe the bug

When attempting to rename and change the timezone of an existing Remote Poller, the following error is thrown:

<img width="1440" alt="image" src="https://github.com/Cacti/cacti/assets/2974895/c57d1a5d-cedc-418a-9672-4b52a67fb5c1">

## To Reproduce

1. Go to Data Collection > Data Collector and change Remote Poller name and timezone.

2. Click on 'Save'

3. See error

## Expected behavior

The new Remote Poller name and time zone should be saved as expected.

## Screenshots

Above.

## Desktop (please complete the following information)

- OS: macOS 14

- Browser Chrome

- Version 123

## Additional context

I removed a previous Remote Poller with same name before on Data Collectors page using the "Delete" option (did a reinstall of Cacti on the same host).

I also noticed that on "Remote Database Connection", the information listed are from local "cactiuser" instead the remote user I setup following the https://www.seanmancini.com/2019/07/cacti-remote-poller-setup/ tutorial, not sure if it's the intended behavior or not.

I was able to edit directly on Cacti Data Collector ``poller`` db table. Also, I noticed that on Cacti Data Collector, the table ``poller`` stores the local "cactiuser" local password from Remote Data Collector as plaintext (non-encrypted), which seems to be a security risk.

**Comment by TheWitness** [comment]
See my comments on collectors and remote collectors.  A database query you can use is the following:

```sql
MariaDB [cacti]> select id, name, hostname, dbhost from poller;
+----+---------------+----------+---------+
| id | name          | hostname | dbhost  |
+----+---------------+----------+---------+
|  1 | Main Poller   | vmhost3  | vmhost3 |
| 20 | Remote Poller | vmhost1  | vmhost1 |
+----+---------------+----------+---------+
2 rows in set (0.000 sec)

MariaDB [cacti]>
```

**Comment by TheWitness** [comment]
The main poller will always have an id of 1.

**Comment by TheWitness** [comment]
In my case vmhost1 needs to be able to talk to vmhost3 via the mysql/mariadb protocol (3306), and vice versa.  Until that two way handshake is right, things will not work as expected.

**Comment by eduardomozart** [comment]
I see. I noticed that what originated this issue is that after Cacti installation, it saves on DB the Local Database username/password and used the non-FQDN hostname of the original host (e.g. ``thor``), which isn't accessible by my Cacti Data Collector instance, but I was unable to edit the preferences as there was no connection between these databases. The fact that Cacti uses the Local Database credentials (``$database`` parameters on Remote Data Collector ``config.php``) instead of the Remote ones (``$rdatabase`` parameters on Remote Data Collector ``config.php``) seems a bug for me because from what I saw, when I changed the credentials on Cacti database to use the ``$rdatabase`` one, the communication worked as expected. I also have to replace the **Hostname** DB parameter directly on database because I was unable to change it through UI. I believe that during the installer, Cacti should ask the Hostname instead of falling back to the non-FQDN hostname, which works fine on a local network, but when the Cacti Data Collector and Cacti Remote Collector are on different networks, this makes the connection between them fail after the installation and unable to change them through UI. Even if the connection between them fails, I believe the user should be able to edit these parameters locally through Cacti Data Collector (master) even if the Remote Data Collector is unavailable.

**Comment by TheWitness** [comment]
Yea, that'll be a problem for a remote install using the Windows installer.  In the 1.3 version, maybe we prompt for that on windows.  It's an enhancement anyway.  For now, before you start the web install, edit the config.php.

**Comment by eduardomozart** [comment]
Editing the ``config.php`` isn't enough to make the Remote Data Collector works, as it's not possible to provide the remote IP address/hostname during Remote Data Collector setup. I believe this enhancement should be made on Cacti itself, and this information be saved directly on Cacti Data Collector (Main Poller) DB during Remote Poller setup instead of relying on falling back to non-FQDN hostname, because it makes editing the poller settings failling, and it's also a bug because the info being saved on Cacti Data Poller (Main Poller) DB isn't the remote user credentials to remotely connecting to Remote Poller DB (``$rdatabase*`` params on ``config.php``), instead are being saved the ``$database*`` params on Cacti Data Poller (Main Poller) ``poller`` DB table. I can comprehend that hostname can be an enhancement, but saving the wrong credentials for DB connections seems like a bug for me. The only way to not having to edit them is if I use the same user to local and remote connections on Remote Poller DB actually.

**Comment by TheWitness** [comment]
I'm going to close this one as it was more of a setup error.  If you plan on using a remote poller, you must always setup the config.php before you start the GUI install.  We will consider an enhancement under a separate enhancement bug for future release though.

**Comment by eduardomozart** [comment]
The file ``config.php`` was configured as expected, I believe you didn't understand the main issue (the connection settings is wrongly saved on Main Poller DB, it will fail EVERY TIME, not about the HOSTNAME, but the connection settings that are being saved are the ones that Remote Poller uses to connect to DB locally instead of the remote ones, forcing the sysadmin to have knowledge about DB to change the settings directly on Main Poller because it's impossible to edit them if there's no Remote Poller connectivity). The only way to prevent this issue from happening is that the local and remote DB user uses the same credentials.

**Comment by TheWitness** [comment]
Let's see what happens with a fresh install.  It was working perfectly for me.  Keep in mind, there is a Full Sync option from the main poller that pushes the relevant information to the remote data collectors if things ever get out of sync.  This is what you do to heal as situation where the remote pollers were offline for some time.
