### ISSUE TITLE
Poller cache may not always update if hostname changes

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#5726]
1.) Add a device to cacti
2.) change the hostname of the device 
![image](https://github.com/Cacti/cacti/assets/13388748/39657ef2-3b72-405d-b40e-29bfd4e3031c)

3.) Observe the poller_cache and notice that atleast for a script server item the poller_cache is not updated

![image](https://github.com/Cacti/cacti/assets/13388748/8f6c8c13-8833-4dab-ab6a-367cb726858c)

No errors logged

**Comment by bmfmancini** [comment]
Rebuild Poller cache does not correct the issue

**Comment by TheWitness** [comment]
@bmfmancini, You were modifying the 'description' and not the 'hostname'.  Try again :)

**Comment by TheWitness** [comment]
Oh, just confirming.  This is bad.
