### ISSUE TITLE
Dark Theme alternate row bgcolor

### ISSUE THREAD

**Issue by smiles1969** [Cacti/cacti#574]
The contrast of the background colors using form_alternate_row is nearly indistinguishable on the dark theme. I can see contrast in classic and other themes. Where is this alternate row color defined or adjusted so I can get better contrast?

**Comment by cigamit** [comment]
Suggestions are welcomed.

**Comment by smiles1969** [comment]
I would suggest a contrasting color that can be seen as clearly separating rows. If I knew where it is defined in the code I would change it myself. I've tried changing settings in dark theme css and tried to even pass arguments in my calls to form_alternate_row and form_alternate_row color (in lib/html_utility.php)  without any luck.

**Comment by cigamit** [comment]
Well, that is not the way to do it.  Edit main.css and look for 'even' and 'odd' classes.

**Comment by cigamit** [comment]
Then, open a pull request.

**Comment by smiles1969** [comment]
I guess I was in the right place to begin with by editing the main.css file in the dark theme. The changes just were not taking effect because I needed to refresh the style-sheet with CTRL-F5. I submitted a pull request #583
