### ISSUE TITLE
95th percentile incorrect when using max type for weekly/monthly graphs

### ISSUE THREAD

**Issue by jdimea** [Cacti/cacti#5740]
# Describe the bug

Using Cacti 1.2.26, the 95th percentile appears to be calculate incorrectly when using the max type for weekly/monthly graphs but other graphs appear to be working correctly.

Example of incorrect 95th percentile calculations:
![Screen Shot 2024-05-02 at 7 48 43 PM](https://github.com/Cacti/cacti/assets/85567451/5c803367-f9d2-4d11-802d-b7dec4c67f4b)

The values are way above the data shown in the graph.

## To Reproduce

Graph template is configured as follows for the 95th percentile:
<img width="678" alt="Screen Shot 2024-05-02 at 7 50 55 PM" src="https://github.com/Cacti/cacti/assets/85567451/559be2d8-0aad-4fb2-8f10-a1dd963a8f28">

**Comment by TheWitness** [comment]
@jdimea, we've made changes to the nth percentile in Cacti 1.2.27, but I'm uncertain if this will address your issue.  I think we will be doing a complete re-evaluation of Cacti's nth percentile work in the as of yet unreleased Cacti 1.3.

So, though I acknowledge that when zooming out the data is likely wrong, I'm going to close this one and suggest that you experiment with the use of VDEF's in Cacti that leverage RRDtools Nth Percentile.  I hope you are okay with his.
