### ISSUE TITLE
[CACTI 1.2.27 - latest source] Device --- status --- filter not working

### ISSUE THREAD

**Issue by anarkia1976** [Cacti/cacti#5741]
Hi Guys,

I have find a problem with device filter --- status --- not working as aspected:
![image](https://github.com/Cacti/cacti/assets/1744639/dd429805-7865-481b-a3e0-731f31a627e5)

thanks a lot
stefano

**Comment by seanmancini** [comment]
I am not able to verify this 

do you see any console errors in the browser?

**Comment by bmfmancini** [comment]
I can't reproduce this do you have any errors in the console. Of the browser?

**Comment by TheWitness** [comment]
Hey @anarkia1976.  First, thanks for testing with 1.2.27 before release.  Can I ask if you have Thold Installed?  Also, can you explain what is the issue?  Are you saying that you don't want to see the disabled device at the same time?  Please clarify.

**Comment by TheWitness** [comment]
@anarkia1976, I just put a device into down and can not get the Disabled to appear when down either.

**Comment by anarkia1976** [comment]
> Hey @anarkia1976. First, thanks for testing with 1.2.27 before release. Can I ask if you have Thold Installed? Also, can you explain what is the issue? Are you saying that you don't want to see the disabled device at the same time? Please clarify.

Hi @TheWitness , 

yes i have thold installed, but it isn't the latest develop release, we have Thold version: 1.7.

We have a mixed situation with some device with status "down" and some devices with status "disabled".

I have try also with others theme like "classic" one but the problem is the same:
![image](https://github.com/Cacti/cacti/assets/1744639/51a18e74-7f6c-48d8-84f5-d0415ba5d375)

thanks a lot
stefano

**Comment by anarkia1976** [comment]
I think the problem was related to my cacti device database. I have re-enabled all disabled devices and then i have diabled again devices and the problem with filter is gone, sorry guys.

**Comment by TheWitness** [comment]
Okay cool.  I'll keep this closed then.
