### ISSUE TITLE
In 1.2.27, about csv problems

### ISSUE THREAD

**Issue by aliuzzz** [Cacti/cacti#5753]
![image](https://github.com/Cacti/cacti/assets/43594093/0c1b01d8-8b9b-4b46-bfc5-16f8bf079ba5)
![image](https://github.com/Cacti/cacti/assets/43594093/9070442e-9123-4e5e-8a83-f313031e454a)
95 percentile  in graph is 12952.47
But 12952.47 is on line 16
Cacti get 288 or 289 values in a day, 288x0.05=14.4 289x0.05=14.45, why 16?

**Comment by TheWitness** [comment]
Coming back to Cacti as early as this weekend.  Spent a lot of time on Flowview over the last month.

**Comment by maojianyou** [comment]
> ![image](https://private-user-images.githubusercontent.com/43594093/331759426-0c1b01d8-8b9b-4b46-bfc5-16f8bf079ba5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NDM5OTUsIm5iZiI6MTcyMjg0MzY5NSwicGF0aCI6Ii80MzU5NDA5My8zMzE3NTk0MjYtMGMxYjAxZDgtOGI5Yi00YjQ2LWJmYzUtMTZmOGJmMDc5YmE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDA3NDEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyNDFjMGUyYTI3YzU1YTI4ZmQ5ZjkzNDQ4NWFmZWE5OTJhOWRhYTM0MGRlMTVhZjg1ZjM2MjRiYTM5MjNiZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wGReNptBQhhrV5Am0ujzJo-1RIML9z2tx1U6cZiD8qg) ![image](https://private-user-images.githubusercontent.com/43594093/331759481-9070442e-9123-4e5e-8a83-f313031e454a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NDM5OTUsIm5iZiI6MTcyMjg0MzY5NSwicGF0aCI6Ii80MzU5NDA5My8zMzE3NTk0ODEtOTA3MDQ0MmUtOTEyMy00ZTVlLThhODMtZjMxMzAzMWU0NTRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDA3NDEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5OTc3MTNlMmVkMzBhN2EyYjUzMjdkNzRkYjE4MDVjZjU4ZmM1MTNjNWJhMWVlZWJjNmEwYjk2NDA5ZjdkNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n_aSPvFaFcLLF7aSjOyoBWT1XjgeVy6T-OQoiJWRJX4) 95 percentile in graph is 12952.47 But 12952.47 is on line 16 Cacti get 288 or 289 values in a day, 288x0.05=14.4 289x0.05=14.45, why 16?

![image](https://github.com/user-attachments/assets/fe9ec863-731a-482c-bb3c-bc9fd67088db)
How do I adjust this alignment? Mine is not aligned properly.
![image](https://github.com/user-attachments/assets/8f7ef2aa-1ca0-4f8b-ac44-89032d819f27)

**Comment by TheWitness** [comment]
This looks more like a roundoff error, and that's not how 95th percentile works.
