### ISSUE TITLE
Unnecessary and confusing German translation

### ISSUE THREAD

**Issue by kersten-lohmeyer** [Cacti/cacti#5755]
Every time the word "Cacti" is used it's translated into the German "Kakteen". Since "Cacti" is the product name it should not be translated and it also sounds confusing when translated.

I understand this is a very minor issue, but also very easy to fix.

My Cacti version is 1.2.27

**Comment by TheWitness** [comment]
Can you go to https://translate.cacti.net and do the fix there.  Registering is easy.

**Comment by kersten-lohmeyer** [comment]
Thanks for the hint. I did (hope I did it right). Found a lot of other wrong translations. Might fix this if I find the time. Only fixed the ones from my previous post now.

**Comment by TheWitness** [comment]
Keep making your changes.  I have to unlock the repos, and then your changes will flow upstream.
