### ISSUE TITLE
Increasing Proc/Threads for decrease polling time

### ISSUE THREAD

**Issue by frankfer01** [Cacti/cacti#5756]
# Describe the bug
Hi, I had installed Cacti 1.2.27 using spine 1.2.25. I want to reduce the polling time increasing Proc/Threads. 
Using Proc/Threads=16/16 my polling time is about 58 seconds. If I increase to 32/32 I got this error: " '2024-05-23 11:00:04 - SPINE: Poller[Main Poller] PID[1851467] PT[140534884637568] ERROR: SS[9] Script Server did not start properly return message was: 'FATAL: Connection to Cacti database failed." and the pooling never end, until I change again. Cacti is running in a virtual machine with RockyLinux 9, has 32 GB of RAN and 32vCPU. What do you think is wrong? How I can reduce the polling time?

## Additional context

![poller](https://github.com/Cacti/cacti/assets/55502569/6d23d4d6-69b8-426c-8402-b38e794eb91b)

**Comment by TheWitness** [comment]
Well, what are the host polling times, and how many hosts?  Is boost enabled?

**Comment by TheWitness** [comment]
First thing to always do is enable boost from the Settings > Performance tab. Having more procs and threads does not always mean better performance.  With 196 threads on the collector side alone, your database will be overwhelmed.

For big systems I always recommend separating the database from the web server.

**Comment by frankfer01** [comment]
Hi, 
The boost was enable, but the poling time not change(about 58 seg). This is not a big system, actually I have just 20 host. The host with more graphs has higher poling time. 
![boost](https://github.com/Cacti/cacti/assets/55502569/02acc1c4-fb41-47fa-91cb-d20df4122ad8)
![host](https://github.com/Cacti/cacti/assets/55502569/0a231216-9fe4-4c01-9496-301345750106)

**Comment by arno-st** [comment]
What is the limitation of the number of connection allowed to your Database ? (max_connections)

**Comment by frankfer01** [comment]
This is the value of max_connections:
Database changed
MariaDB [cactidb]> SHOW GLOBAL VARIABLES LIKE 'max_connections';
+-----------------+-------+
| Variable_name   | Value |
+-----------------+-------+
| max_connections | 1000  |
+-----------------+-------+

**Comment by frankfer01** [comment]
Hi, in this cacti version I did'n see the option "Number of Collection Threads" in the device edit. I changed from 1 to 8 and the polling time decrease to about 20 seconds, with the double of graphs. Thanks for all.

![cacti](https://github.com/Cacti/cacti/assets/55502569/6b91ad9a-4a6b-4834-a9cd-90b9fa7cc2f7)
