### ISSUE TITLE
Why do some display ports while others do not

### ISSUE THREAD

**Issue by aliuzzz** [Cacti/cacti#5757]
How to solve this problem with the same template, only for H3C devices and Huawei devices? I hope all ports can be displayed
![image](https://github.com/Cacti/cacti/assets/43594093/2cf91928-dd80-4dd5-bbcf-207997baee1c)
![image](https://github.com/Cacti/cacti/assets/43594093/4c02406f-6c0e-4380-84cf-c261f23b70cc)

**Comment by xmacan** [comment]
Github issues are for development, reporting errors, ...
If you need help or support, please use https://forums.cacti.net
