### ISSUE TITLE
Devices that are discovered are not added to the correct default site

### ISSUE THREAD

**Issue by stormonts** [Cacti/cacti#576]
In the Cacti settings, I have set "Site - The default Site for all new Devices." to a site that I created called "Newly Discovered". However, when I run a discovery and new devices are discovered, they are automatically assigned to the first site alphabetically which is "Baltimore". Is this a bug or am I totally misunderstanding how this setting works?

**Comment by cigamit** [comment]
This was resolved yesterday in the development branch.
