### ISSUE TITLE
CactiEZ 1.2.27 CMDPHP Validation Error on import Templates and import packages 

### ISSUE THREAD

**Issue by tgreaser** [Cacti/cacti#5760]
# Describe the bug
CactiEZ straight out of the box with latest Rocky updates . 

Cannot import templates  and just get the error

Can export templates already on the newly setup setup system

Console Import/Export 

## To Reproduce

1. Go to Console Import/Export

2. Click on Import Templates 

(/templates_import.php[48]:import(), /templates_import.php[444]:get_filter_request_var(), /lib/html_utility.php[493]:die_html_input_error(), /lib/html_validate.php[64]:cacti_debug_backtrace())
Validation error for variable image_format with a value of on. See backtrace below for more details.

## Expected behavior
A page to allow one to upload the template.

## Screenshots
 
![Screenshot cacti error  2024-05-29 11-10-05](https://github.com/Cacti/cacti/assets/1334075/b7ab55e2-9cf3-405e-bcc0-9d776e50ec22)

## Desktop (please complete the following information)

- OS: Fedora 40

- Browser  chrome, fox 

- Version latest 

## Additional context

Error when using import packages

(/package_import.php[54]:package_import(), /package_import.php[930]:get_import_form(), /package_import.php[798]:get_filter_request_var(), /lib/html_utility.php[493]:die_html_input_error(), /lib/html_validate.php[64]:cacti_debug_backtrace())
Validation error for variable image_format with a value of on. See backtrace below for more details.

**Comment by TheWitness** [comment]
Can you please upload the XML file here.

**Comment by tgreaser** [comment]
Sorry I was not clear.  I dont ever get the opertunity to even chose a file. As soon as I click on the Import I get the 
error page .   
I get the same error in the logs too.
2024-06-07 16:56:16 - CMDPHP Validation Error, Variable:image_format, Value:on Backtrace: (/templates_import.php[48]:import(), /templates_import.php[444]:get_filter_request_var(), /lib/html_utility.php[493]:die_html_input_error(), /lib/html_validate.php[64]:cacti_debug_backtrace())

2024-06-07 16:56:15 - CMDPHP Validation Error, Variable:image_format, Value:on Backtrace: (/package_import.php[54]:package_import(), /package_import.php[930]:get_import_form(), /package_import.php[798]:get_filter_request_var(), /lib/html_utility.php[493]:die_html_input_error(), /lib/html_validate.php[64]:cacti_debug_backtrace())

![Screenshot from 2024-06-07 16-56-47](https://github.com/Cacti/cacti/assets/1334075/130acbfb-d38e-4ab8-ac83-0fa7afcb47dc)

**Comment by TheWitness** [comment]
I am unable to reproduce this one.

**Comment by TheWitness** [comment]
I've updated the CactiEZ as it was pretty old.  Try again with the latest version.  I'm going to go ahead and close now.  Re-open if it happens again with the 1.2.27 version of CactiEZ.

**Comment by tgreaser** [comment]
Will do, and I appreciate the effort .
FYI downloading CactiEZ-1.2.27-Rocky-9-4.iso  and since I seen it was
there  will lab CactiEZ-1.3.0-Rocky-9-4.iso as well.

**Comment by tgreaser** [comment]
I downloaded both 1.2.27, 1.3.0 and the  same issue .  CactiEZ will not
allow you to upload new templates.

**Comment by mvol01** [comment]
Same issue for me as well.
<html>
<body>

(/package_import.php[54]:package_import(), /package_import.php[930]:get_import_form(), /package_import.php[798]:get_filter_request_var(), /lib/html_utility.php[493]:die_html_input_error(), /lib/html_validate.php[64]:cacti_debug_backtrace())
--
<html>
<body>

(/templates_import.php[48]:import(), /templates_import.php[444]:get_filter_request_var(), /lib/html_utility.php[493]:die_html_input_error(), /lib/html_validate.php[64]:cacti_debug_backtrace())
--



</body>
</html>

</body>
</html>

**Comment by TheWitness** [comment]
I'll look at this this weekend.  Image format should be numeric.  Must be some html vovoo.
