### ISSUE TITLE
Authentication logging request

### ISSUE THREAD

**Issue by shifteynz** [Cacti/cacti#5761]
We're looking to send our Cacti logs to our SIEM. I'm currently assessing the authentication based logs.
We have DEBUG mode enabled.

I've noticed that:

- For successful logins, there is no IP address associated with the user authenticating. Example:
"AUTH LOGIN: User 'username' Authenticated via Authentication Cookie"
or
"AUTH LOGIN: User 'Username' authenticated"

- For failed logins, the username and IP address are contained within the same event:
"AUTH LOGIN FAILED: Local Login Failed for user 'username' from IP Address '1.2.3.4'"

Feature Request:
1) Can successful login events contain the same information as a failed login event? (Username and IP Address of user)
2) Can the logging format for failed and successful logins be consistent, with the field and values in the same order for both event types?

**Comment by bmfmancini** [comment]
Hey!all of those requirements are avaliable in the audit plugin 

Install  the audit plugin and in settings  there is a option to log to file  which can be
ingested via splunk or others

**Comment by shifteynz** [comment]
Thank you! I'll close the issue/feature request.
