### ISSUE TITLE
MySQL Templates missing in Cacti 1.3.0

### ISSUE THREAD

**Issue by JGitDG** [Cacti/cacti#5762]
In Previous versions i had Mysql Templates to make graphs of my databases:

The Graph Templates i used to have:
X MySQL Binary/Relay Logs GT	
X MySQL Command Counters GT	
X MySQL Connections GT	
X MySQL Files and Tables GT	
X MySQL Handlers GT	
X MySQL Network Traffic GT	
X MySQL Processlist GT	
X MySQL Query Cache GT	
X MySQL Query Cache Memory GT	
X MySQL Replication GT	
X MySQL Select Types GT	
X MySQL Sorts GT	
X MySQL Table Locks GT	
X MySQL Temporary Objects GT	
X MySQL Threads GT	
X MySQL Transaction Handler GT

Once i installed the newest cacti version i could, i encountered no possibility to make this kind of graphs.

It feels like it may be because it is not an stable version... Does it happen this to you? Or am i missing something?

**Comment by JGitDG** [comment]
If this happen to someone, i guess they were just imported Templates.

**Comment by TheWitness** [comment]
Yea, one of my summer projects is to write a plugin for monitoring MariaDB & MySQL servers. 

I'm using two variations of these at the office also, and I was so upset.  They are better than nothing, but have so long to go. 

So, the plan it to write a simple collector written in php and management interface. This way, the plugin can properly account for things like uptime.

**Comment by TheWitness** [comment]
I have a device package, but likely create more issues than it solves right now.
