### ISSUE TITLE
Cacti isn't generating graphs

### ISSUE THREAD

**Issue by foysalkhan1** [Cacti/cacti#5763]
I've installed cacti on centos7. But it's not generating any graphs.. It's showing -nan
![Screenshot 2024-06-02 173338](https://github.com/Cacti/cacti/assets/76809108/90c6cd1b-c554-4365-9bee-dfb019b92382)

Here is the poller configuration
![Screenshot 2024-06-02 173449](https://github.com/Cacti/cacti/assets/76809108/6d6149e0-f2e9-429a-8670-3b23cb00c22f)

How to solve it. I'm using spine and cacti 1.2.27.

**Comment by prottoy396** [comment]
![image](https://github.com/Cacti/cacti/assets/171273049/8b72555f-5e62-4eeb-8d5f-69f916ce22af)
![image](https://github.com/Cacti/cacti/assets/171273049/9f291300-3601-4880-bb9f-c5fab0327677)
Getting same issue, but graph debug is getting data from queries.

**Comment by foysalkhan1** [comment]
Are your from bangladesh? I can see you're using summit iig.

**Comment by TheWitness** [comment]
Can you please raise the issues on the forums before creating them here?
