### ISSUE TITLE
Reapply suggested name for DS doesn't work as expected

### ISSUE THREAD

**Issue by arno-st** [Cacti/cacti#5765]
I have 3 different name for the DS, define inside SNMP - Interface Statistics, for the traffic.
Those definition are:
``
 text 																			field_name 	
|host_description| - Traffic - |query_ifName| - |query_ifDescr| 				name
|host_description| - Traffic - |query_ifIP| - |query_ifName| - |query_ifAlias|	name
|host_description| - Traffic - |query_ifName| - |query_ifAlias| 				name
``
To reproduce I select on Management -> Data Source, then select my device, and filter on Template: Interface Traffic

The row display:
``
ipn_ch9_1-1 - Traffic - Ethernet1/1 - Ethernet1/1
``
Then I select this DS, and action: reapply suggested name,
the next windows ask me:
`
Click 'Continue' to re-apply the suggested name to the following Data Source.
ipn_ch9_1-1 - Traffic - Ethernet1/1 - To_SP_CH9_1101
`

So the name in this windows is different of the name display on the Management -> Data Source view.
1st: why is that ?
2nd: why the application of Reapply Suggested Name doesn't change the display name ?

I'm running cacti 1.2.27, on almalinux, and php 8.2

**Comment by TheWitness** [comment]
If the graph or data source are orphaned, the name does not change.  This is different from previous pre 1.x releases.

**Comment by arno-st** [comment]
No there not

**Comment by TheWitness** [comment]
@arno-st, can you upload a screen recording of the activity, and for the device, edit the Data Query and list the suggested names.  Finally, from the database:

```sql
select * from data_local where host_id = ? and snmp_query_id = ?
```

**Comment by maojianyou** [comment]
> 我有3个不同的名称为DS，定义内SNMP -接口统计，为交通. 这些定义是：第一名要重现，我选择管理->数据源，然后选择我的设备，并在模板上过滤：接口流量
> 
> 该行显示：二号然后我选择这个DS，然后操作：重新应用建议的名称，下一个窗口问我：`text field_name |host_description| - Traffic - |query_ifName| - |query_ifDescr| name |host_description| - Traffic - |query_ifIP| - |query_ifName| - |query_ifAlias|name |host_description| - Traffic - |query_ifName| - |query_ifAlias| name`
> 
> 因此，此窗口中的名称与Management - Data Source视图中显示的名称不同>。第一：为什么？第二：为什么重新应用建议名称的应用程序不改变显示名称？
> 
> 我在almalinux和php8.2上运行cacti1.2.27


I also noticed that I can't customize the graph name; it's always based on the graph template. One is the host name and description, and it's not possible to customize a separate display name for the graph.
![image](https://github.com/user-attachments/assets/0499aa45-61d5-4b05-b956-9a0458ca1056)

**Comment by TheWitness** [comment]
No feedback.

**Comment by arno-st** [comment]
Sorry for the delay, I was working on flowview ;) and other stuff since I'm back of vacation.

I can't do any video of my screen, so I will do it, with picture.
1: the record you ask from the DB:
`MariaDB [cacti_test]> select * from data_local where host_id = 23032 and snmp_query_id = 47;
+--------+------------------+---------+---------------+------------+--------+
| id     | data_template_id | host_id | snmp_query_id | snmp_index | orphan |
+--------+------------------+---------+---------------+------------+--------+
| 259402 |              206 |   23032 |            47 | 436346880  |      0 |
| 259405 |              206 |   23032 |            47 | 436350976  |      0 |
| 259408 |              218 |   23032 |            47 | 436346880  |      0 |
| 259411 |              218 |   23032 |            47 | 436350976  |      0 |
| 259657 |              206 |   23032 |            47 | 369098752  |      0 |
| 259660 |              206 |   23032 |            47 | 369098753  |      0 |
| 259663 |              218 |   23032 |            47 | 1073745920 |      0 |
| 259666 |              218 |   23032 |            47 | 1090523136 |      0 |
| 259669 |              206 |   23032 |            47 | 1073745920 |      0 |
| 259672 |              206 |   23032 |            47 | 1090523136 |      0 |
+--------+------------------+---------+---------------+------------+--------+
10 rows in set (0.001 sec)
`
The data query setup:
![2024-08-12 15_43_15-Clipboard](https://github.com/user-attachments/assets/70c5234a-520f-4f2b-a12e-98ff60b0a339)

Then the different step of my action:
![2024-08-12 15_51_10-Clipboard](https://github.com/user-attachments/assets/2227f910-1804-4ffa-888f-dac2b4d30f49)
![2024-08-12 15_51_37-Clipboard](https://github.com/user-attachments/assets/5b61c714-c882-48e8-82cd-8d1a6ca66d7b)
![2024-08-12 15_51_53-Clipboard](https://github.com/user-attachments/assets/4dc89e69-0d84-4236-88cb-6e7bc6a0acff)
![2024-08-12 15_52_09-Clipboard](https://github.com/user-attachments/assets/234c5ed3-5519-4927-8e68-371d8ddc448b)

**Comment by arno-st** [comment]
And on the DB it's the data_template_id 206
