### ISSUE TITLE
Graph debug report is ok, getting data but Graph is showing empty

### ISSUE THREAD

**Issue by prottoy396** [Cacti/cacti#5766]
![image](https://github.com/Cacti/cacti/assets/171273049/c2c530e8-52a0-4619-8dda-00b80199d75a)
Debug Result

![image](https://github.com/Cacti/cacti/assets/171273049/57281517-e639-4c62-8854-19623dda35ce)
The Graph 

Note : Getting data in another graph tool. Device Cisco, Interface type - Interface Vlan

**Comment by TheWitness** [comment]
Please raise this type of issue up on the forums before coming here.  Thanks.
