### ISSUE TITLE
Problem when updating from cacti version 1.2.25 to 1.2.27

### ISSUE THREAD

**Issue by oelagy** [Cacti/cacti#5767]
Hello, I am new to cacti, I have a problem with my cacti, after updating from version 1.2.25 to 1.2.27, the graphics do not paint after the update. I have been checking what polled devices are active. The only thing is that the graph doesn't look good to me.

**Comment by TheWitness** [comment]
Please take this issue up on the Cacti forums before bringing them up here.  Thanks!

**Comment by oelagy** [comment]
Yes, I have it created in the cacti forum, I have no answers. Thanks

**Comment by TheWitness** [comment]
What's the post link?
