### ISSUE TITLE
Edit tree refreshes to soon

### ISSUE THREAD

**Issue by reboot1983** [Cacti/cacti#577]
When I create a tree node, expand it (although it's still empty), and add a bunch of graphs by dragging them into the node, the tree window reloads and shows only a few of the graphs I just added. When I refresh (F5) the whole page, all the graphs are there.

It looks like the tree refreshes to soon and the process of adding the items into the node is not done yet. Not all the items are already stored into the tree node when the refresh starts resulting in not showing all items.

**Comment by cigamit** [comment]
Yea, this is a known issue.  Been avoiding it.

**Comment by cigamit** [comment]
Resolved, thanks for reporting.
