### ISSUE TITLE
1.2.26 -> 1.2.27 Upgrade problem

### ISSUE THREAD

**Issue by ISekan** [Cacti/cacti#5774]
cacti 1.2.26
Oracle Linux Server 9.3
11.2.3-MariaDB 

After selecting "Accept the GPL License Agreement", the option is automatically disabled and you cannot continue by clicking BEGIN

![image](https://github.com/Cacti/cacti/assets/17400240/7d8a5476-f6a0-41b3-8426-9c0a634d01ba)

**Comment by TheWitness** [comment]
Short-term in the CLI directory there is a script called upgrade_database.php.

Just run that for now.

**Comment by ISekan** [comment]
thanks, it works

**Comment by TheWitness** [comment]
I'm closing this as a support issue.  We already have a ticket for this issue.  Thanks for confirming.
