### ISSUE TITLE
When export to CSV, only the first line of notes is included

### ISSUE THREAD

**Issue by TalkingToes** [Cacti/cacti#5777]
# Feature Request

## Is your feature request related to a problem? Please describe
The resulting .CSV file only includes the 1st line of the Notes field.
## Describe the solution you'd like

Console \ Management \ Devices \ Export creates a .CSV file with many columns, but the Notes column only includes the 1st row of each device. I'm hoping it would include the whole Notes field as entered into Cacti. 

Maybe for each Notes, filter for Carriage Returns and any Comma and replace with a space?

Screenshots. Where is the 2nd line?
Cacti:
![Screenshot 2024-06-24 110254](https://github.com/Cacti/cacti/assets/69818508/1723714b-d3c6-4759-ac20-d98560c2f5be)

Excel:
![Screenshot 2024-06-24 110223](https://github.com/Cacti/cacti/assets/69818508/4b33217b-10ee-4c69-b324-c282512bdba5)

**Comment by TheWitness** [comment]
Yea, that's likely the issue.  Good catch.

**Comment by TheWitness** [comment]
I switched this to a bug from an enhancement.  The way I am dealing with it is to replace carriage returns and line feeds with a space.

**Comment by TalkingToes** [comment]
I added your change to my 1.2.27 locally, and it exports correctly. Thank you.

I get in the cacti.log this error for each host (I believe my line 600 is your line 616):
Jul-02-2024 12:00:10 - CMDPHP PHP ERROR Backtrace: (/host.php[60]:host_export(), /host.php[600]:strpos(), CactiErrorHandler())
Jul-02-2024 12:00:10 - ERROR PHP DEPRECATED: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in file: /var/www/html/cacti/host.php on line: 600

![Screenshot 2024-07-02 120944](https://github.com/Cacti/cacti/assets/69818508/c8fbccb0-a551-48cb-a3e8-b1f6199db46f)

I can ignore this, but it's still screens of bright red errors. Should I hide deprecated?

**Comment by TheWitness** [comment]
Okay, second issue is fixed now.  Just update your host.php.
