### ISSUE TITLE
Enhanced AUTH logs

### ISSUE THREAD

**Issue by shifteynz** [Cacti/cacti#5779]
Cacti contains AUTH logs of users logging in to Cacti. Unfortunately 1 login event is spread across multiple logs.

Examples: (User and IP info changed to generic for the example):
Event 1: 2024/06/26 12:08:37 - AUTH LOGIN: User 'user@example.com' authenticated
Event 2: 2024/06/26 12:08:37 - AUTH DEBUG: Using remote client IP Address found in header (REMOTE_ADDR): 192.168.1.2 (192.168.1.2)

We are sending the Cacti AUTH logs to our SIEM, however it is difficult to capture the username and users IP address as this is spread across multiple events.

In the CACTI GUI at Console > Utilities > System Utilities > View User Log, the user login info is displayed clearly as a single line, i.e
User / Full Name / Authentication Realm / Date / Result / IP Address

Feature Request:
Can the AUTH logs be updated so that 1 AUTH log contains the same information as displayed in "View User Log".

Additionally, I did investigate the Audit plugin, however this only applies to user behaviour within the portal, and not the login/auth attempts to Cacti.

Thanks.

**Comment by bmfmancini** [comment]
Check out the audit plugin most of this is addressed by that plugin with a specific export function for siem apps

**Comment by shifteynz** [comment]
> Check out the audit plugin most of this is addressed by that plugin with a specific export function for siem apps

Thanks for that. The audit plugin doesnt change the user login/auth behaviour, but only the activities done once the user is already logged in. Cacti has a great view of logins at the "View User Log" page, would be great if this was replicated into the AUTH logs

**Comment by bmfmancini** [comment]
It should show a login event with details
If not that would be a good feature please. Open a feature request I'll take a look

**Comment by shifteynz** [comment]
I was told this is where to log feature request. If not, where should a FR be logged?

**Comment by xmacan** [comment]
We did it for 1.2.x and for 1.3. We add IP address to success auth log message:
2024/06/26 12:08:37 - AUTH LOGIN: User '[user@example.com](mailto:user@example.com)' authenticated from IP address A.B.C.D
https://github.com/Cacti/cacti/pull/5772
https://github.com/Cacti/cacti/pull/5775

**Comment by shifteynz** [comment]
Hi there,
We are running version 1.2.27 and that doesnt seem to be the case. The username and IP are spread across events.
Please refer to the attached screenshots.
![Auth-logs](https://github.com/Cacti/cacti/assets/28241254/3d48c1ad-d748-444b-866e-226797ddf146)
![loggedinas](https://github.com/Cacti/cacti/assets/28241254/a70ce684-d617-40f3-839d-8d7e71c04bb4)

**Comment by xmacan** [comment]
Download the auth_login.php and include/auth.php files from branch 1.2.x and replace them in version 1.2.27.

**Comment by TheWitness** [comment]
duplicate.  Closing.

**Comment by shifteynz** [comment]
Thank you - once I overwrite these files (auth_login.php and include/auth.php)  do I need to restart Cacti? If yes, how would I do that?Sorry for the dumb question, I dont admin Cacti at all, I just collect its logs.

**Comment by xmacan** [comment]
@shifteynz - you don't neet restart

**Comment by shifteynz** [comment]
I copied auth_login.php to the cacti root directory and auth.php to the cacti/include directory. After refreshing Cacti in the browser I got an error. Am I supposed to perform other steps? Like reinstall 1.2.x again?

**Comment by xmacan** [comment]
Which error?
Didi you take files from github from 1.2.x branch?

**Comment by shifteynz** [comment]
Yes, I downloaded the files from the 1.2.x branch. When I copy the files and refresh the GUI console, I am greeted with the below. Would it be better to reinstall 1.2.7 again?

![auth php error](https://github.com/Cacti/cacti/assets/28241254/297e1b6d-fae4-49fc-ab09-cc619f6fa733)

**Comment by shifteynz** [comment]
I have this working now. We merged the diff. Thanks for your patience.

**Comment by TheWitness** [comment]
Glad to hear that.
