### ISSUE TITLE
CACTI.NET OFFLINE

### ISSUE THREAD

**Issue by Cyber5imon** [Cacti/cacti#5787]
# Describe the bug

https://www.cacti.net is offline and gives a 500 error

## To Reproduce

visit https://www.cacti.net

## Expected behavior

Default homepage

## Screenshots

![image](https://github.com/user-attachments/assets/6e989eb6-73a8-484d-8e71-f86b42df0e66)

## Desktop (please complete the following information)

N/A

## Smartphone (please complete the following information)

N/A

**Comment by TheWitness** [comment]
Yea, we were doing some maintenance.  It'll be back up soon.

**Comment by bmfmancini** [comment]
Site is back online )
