### ISSUE TITLE
No RRD file after upgrading cacti from 0.8.8h to 1.2.27

### ISSUE THREAD

**Issue by titouan-joseph** [Cacti/cacti#5789]
# Describe the bug

After an upgrade from 0.8.8h to 1.2.27 the rrd file are not created

## To Reproduce

1. Dump the old database ``mysqldump -l --add-drop-table --lock-tables=false cacti > mysql.cacti``
2. TAR the old files ``tar --exclude=*.rrd -zcf cacti_backup_YYYYMMDD.tgz cacti``
3. Export RRD as XML with `` find ./rra -maxdepth 2  -type f -name "*.rrd" | awk '{print "rrdtool dump "$1" > "$1".xml"}' | sh -x``
5. Create a fresh install on a new server (https://docs.cacti.net/Installing-Under-Ubuntu-Debian.md)
6. On the new server import the old file and database and RRD (`` sudo find ./rra -maxdepth 2  -type f -name "*.rrd.xml" | sed 's/\.xml//' | awk '{print "rrdtool restore "$1".xml "$1}' | sudo sh -x``)
7. Performe the upgrade with this
```bash
cd cacti-clone/
sudo git checkout release/1.0.0
cd ..
sudo /bin/cp -rpf cacti-clone/* cacti

# Follow the installation wizard on the web interface

cd cacti-clone/
sudo git checkout release/1.0.6
cd ..
sudo /bin/cp -rpf cacti-clone/* cacti


cd cacti-clone/
sudo git checkout release/1.1.0
cd ..
sudo /bin/cp -rpf cacti-clone/* cacti

# Follow the installation wizard on the web interface

cd cacti-clone/
sudo git checkout release/1.1.10
cd ..
sudo /bin/cp -rpf cacti-clone/* cacti

# Follow the installation wizard on the web interface

cd cacti-clone/
sudo git checkout release/1.1.20
cd ..
sudo /bin/cp -rpf cacti-clone/* cacti

# Follow the installation wizard on the web interface

cd cacti-clone/
sudo git checkout release/1.1.30
cd ..
sudo /bin/cp -rpf cacti-clone/* cacti

# Follow the installation wizard on the web interface

cd cacti-clone/
sudo git checkout release/1.1.38
cd ..
sudo /bin/cp -rpf cacti-clone/* cacti

# Follow the installation wizard on the web interface

cd cacti-clone/
sudo git checkout release/1.2.0
cd ..
sudo /bin/cp -rpf cacti-clone/* cacti

# Follow the installation wizard on the web interface

cd cacti-clone/
sudo git checkout release/1.2.5
cd ..
sudo /bin/cp -rpf cacti-clone/* cacti

# Follow the installation wizard on the web interface

cd cacti-clone/
sudo git checkout release/1.2.10
cd ..
sudo /bin/cp -rpf cacti-clone/* cacti

# Follow the installation wizard on the web interface

cd cacti-clone/
sudo git checkout release/1.2.20
cd ..
sudo /bin/cp -rpf cacti-clone/* cacti

# Follow the installation wizard on the web interface


cd cacti-clone/
sudo git checkout release/1.2.27
cd ..
sudo /bin/cp -rpf cacti-clone/* cacti

````
8. force the polling and no graph displayed 

## Expected behavior

Creation of RRD file and then graph

## Screenshots

![image](https://github.com/user-attachments/assets/a4c1c5c6-57b7-4d75-9206-3e27c6808a4b)

## Desktop (please complete the following information)

- OS: Debian 12

- Browser: Chrome

- Version: 1.2.27

### Links

- https://docs.cacti.net/Upgrading-Cacti.md
- https://docs.cacti.net/Installing-Under-Ubuntu-Debian.md

**Comment by titouan-joseph** [comment]
The permissions are good

From the cron job

![image](https://github.com/user-attachments/assets/74c9e384-f3db-414c-8d84-7c6e32ca0137)


And from the files

![image](https://github.com/user-attachments/assets/19e5f6ca-eb4b-4f3a-a696-eb1d33af89fa)

![image](https://github.com/user-attachments/assets/056a6f8f-13be-4ed3-8488-6fa463d466ea)

![image](https://github.com/user-attachments/assets/ed1b0ea3-726c-4fb3-8eed-468d75e93bf3)

**Comment by bmfmancini** [comment]
Are you using spine? If so checking spine.conf credentials 

Any errors  in your cacti log

**Comment by titouan-joseph** [comment]
Yes, I used spine,
![image](https://github.com/user-attachments/assets/9f97d856-72e2-4c6f-915e-f80236f7ff31)

``/usr/local/spine/etc/spine.conf`` have the correct db credentials


And for error in cacti log, I have this but nothing on the internet

![image](https://github.com/user-attachments/assets/3b3ec775-deac-4f01-8fdd-34c936ff8b87)

**Comment by titouan-joseph** [comment]
Another precision I don't say the graphs was not created are the new graphs. For a new host or for a new graph with an old host.

**Comment by TheWitness** [comment]
Check your poller_item table for the rrd_path's and see that they are valid.  One mistake that people use when migrating their systems is that the paths oftentimes change, and you have to ensure that all the paths are valid:

```sql
SELECT * FROM settings WHERE name LIKE '%path%' OR value LIKE '%/%';
```

Once you normalize things in your settings table, you can do something like this

```sql
UPDATE poller_item SET rrd_path=replace(rrd_path, "oldpath", "newpath") WHERE rrd_path LIKE '%oldpath%';
```

Don't take my word for it, lookup the MySQL/MariaDB `replace()` function.

**Comment by titouan-joseph** [comment]
HI @TheWitness,

Thank for you support, but I have already modify the rra_path in the table, here an export for the host 2814

|local_data_id|poller_id|host_id|last_updated|rrd_name|rrd_path|rrd_num|rrd_step|rrd_next_step|
|-------------|---------|-------|------------|--------|--------|-------|--------|-------------|
|46254|1|2814|2024-07-26 11:38:10|fm_SysCpuUsage|/var/www/html/cacti/rra/2814/46254.rrd|1|300|0|
|46255|1|2814|2024-07-26 11:38:10|fg_SysSesCount|/var/www/html/cacti/rra/2814/46255.rrd|1|300|0|
|46256|1|2814|2024-07-26 11:38:10|fm_SysCpuUsage|/var/www/html/cacti/rra/2814/46256.rrd|1|300|0|
|46257|1|2814|2024-07-26 11:38:10|fg_SysLowMemUsage|/var/www/html/cacti/rra/2814/46257.rrd|1|300|0|
|46258|1|2814|2024-07-26 11:38:10|fm_SysCpuUsage|/var/www/html/cacti/rra/2814/46258.rrd|1|300|0|
|46259|1|2814|2024-07-26 11:38:10|fg_SysCpuUsage|/var/www/html/cacti/rra/2814/46259.rrd|1|300|0|
|46260|1|2814|2024-07-26 12:06:59|fg_SysDiskCapacity|/var/www/html/cacti/rra/2814/46260.rrd|1|300|0|
|46261|1|2814|2024-07-26 11:38:10|fm_SysCpuUsage|/var/www/html/cacti/rra/2814/46261.rrd|1|300|0|
|46262|1|2814|2024-07-26 11:38:10|fg_SysDiskCapacity|/var/www/html/cacti/rra/2814/46262.rrd|1|300|0|
|46263|1|2814|2024-07-26 11:38:10|fg_SysDiskUsage|/var/www/html/cacti/rra/2814/46263.rrd|1|300|0|
|46264|1|2814|2024-07-26 11:38:10|fm_SysCpuUsage|/var/www/html/cacti/rra/2814/46264.rrd|1|300|0|
|46265|1|2814|2024-07-26 11:38:10|fg_SysMemUsage|/var/www/html/cacti/rra/2814/46265.rrd|1|300|0|
|46266|1|2814|2024-07-26 11:38:10|traffic_in|/var/www/html/cacti/rra/2814/46266.rrd|2|300|0|
|46266|1|2814|2024-07-26 11:38:10|traffic_out|/var/www/html/cacti/rra/2814/46266.rrd|2|300|0|
|46267|1|2814|2024-07-26 11:38:10|traffic_in|/var/www/html/cacti/rra/2814/46267.rrd|2|300|0|
|46267|1|2814|2024-07-26 11:38:10|traffic_out|/var/www/html/cacti/rra/2814/46267.rrd|2|300|0|
|46268|1|2814|2024-07-26 11:38:10|traffic_in|/var/www/html/cacti/rra/2814/46268.rrd|2|300|0|
|46268|1|2814|2024-07-26 11:38:10|traffic_out|/var/www/html/cacti/rra/2814/46268.rrd|2|300|0|
|46269|1|2814|2024-07-26 11:38:10|traffic_in|/var/www/html/cacti/rra/2814/46269.rrd|2|300|0|
|46269|1|2814|2024-07-26 11:38:10|traffic_out|/var/www/html/cacti/rra/2814/46269.rrd|2|300|0|
|46270|1|2814|2024-07-26 11:38:10|traffic_in|/var/www/html/cacti/rra/2814/46270.rrd|2|300|0|
|46270|1|2814|2024-07-26 11:38:10|traffic_out|/var/www/html/cacti/rra/2814/46270.rrd|2|300|0|
|46271|1|2814|2024-07-26 11:38:10|traffic_in|/var/www/html/cacti/rra/2814/46271.rrd|2|300|0|
|46271|1|2814|2024-07-26 11:38:10|traffic_out|/var/www/html/cacti/rra/2814/46271.rrd|2|300|0|
|46272|1|2814|2024-07-26 11:38:10|traffic_in|/var/www/html/cacti/rra/2814/46272.rrd|2|300|0|
|46272|1|2814|2024-07-26 11:38:10|traffic_out|/var/www/html/cacti/rra/2814/46272.rrd|2|300|0|
|46273|1|2814|2024-07-26 11:38:10|traffic_in|/var/www/html/cacti/rra/2814/46273.rrd|2|300|0|
|46273|1|2814|2024-07-26 11:38:10|traffic_out|/var/www/html/cacti/rra/2814/46273.rrd|2|300|0|
|46274|1|2814|2024-07-26 11:38:10|traffic_in|/var/www/html/cacti/rra/2814/46274.rrd|2|300|0|
|46274|1|2814|2024-07-26 11:38:10|traffic_out|/var/www/html/cacti/rra/2814/46274.rrd|2|300|0|
|46275|1|2814|2024-07-26 11:38:10|traffic_in|/var/www/html/cacti/rra/2814/46275.rrd|2|300|0|
|46275|1|2814|2024-07-26 11:38:10|traffic_out|/var/www/html/cacti/rra/2814/46275.rrd|2|300|0|
|46276|1|2814|2024-07-26 11:38:10|traffic_in|/var/www/html/cacti/rra/2814/46276.rrd|2|300|0|
|46276|1|2814|2024-07-26 11:38:10|traffic_out|/var/www/html/cacti/rra/2814/46276.rrd|2|300|0|
|46277|1|2814|2024-07-26 11:38:10|traffic_in|/var/www/html/cacti/rra/2814/46277.rrd|2|300|0|
|46277|1|2814|2024-07-26 11:38:10|traffic_out|/var/www/html/cacti/rra/2814/46277.rrd|2|300|0|

**Comment by titouan-joseph** [comment]
I have done a Data sources checking with the troubleshooting tool.

Here are the result after more than 10 poller run

![image](https://github.com/user-attachments/assets/6fb09e40-fa66-46dc-8d27-ae62a7d0d170)

And here some detailed run result : 
- RRDfile does not match Data Source
- Debug not completed after 5 pollings Failed fields: rra_timestamp, rra_timestamp2 RRDfile not update	

![image](https://github.com/user-attachments/assets/40574fcf-de73-43e3-8ba2-25f5d1f8448c)
=> I don't understand this, IF we check the datasource with the debug info mode, we have : ``The required RRDfile step size is '' but observed step is '300'``
![image](https://github.com/user-attachments/assets/57122e14-b7e6-48c7-a84c-c8a459497dae)
And if we check the rrd file with rrd tool, with have setp set to 300
In the database we have also step set to 300
|local_data_id|poller_id|host_id|rrd_name|rrd_path|rrd_num|rrd_step|rrd_next_step|
|-------------|---------|-------|------------|--------|--------|-------|--------|
|45685|1|2790|ucd_load1min|/var/www/html/cacti/rra/2790/45685.rrd|1|300|0|

```bash
cacti@localhost:/var/www/html$ rrdtool info /var/www/html/cacti/rra/2790/45685.rrd
filename = "/var/www/html/cacti/rra/2790/45685.rrd"
rrd_version = "0003"
step = 300
last_update = 1722509405
header_size = 2456
ds[ucd_load1min].index = 0
ds[ucd_load1min].type = "GAUGE"
ds[ucd_load1min].minimal_heartbeat = 600
ds[ucd_load1min].min = 0.0000000000e+00
ds[ucd_load1min].max = 5.0000000000e+02
ds[ucd_load1min].last_ds = "1.40"
ds[ucd_load1min].value = 7.0000000000e+00
ds[ucd_load1min].unknown_sec = 0
rra[0].cf = "AVERAGE"
rra[0].rows = 600
rra[0].cur_row = 554
rra[0].pdp_per_row = 1
rra[0].xff = 5.0000000000e-01
rra[0].cdp_prep[0].value = NaN
rra[0].cdp_prep[0].unknown_datapoints = 0
rra[1].cf = "AVERAGE"
rra[1].rows = 700
rra[1].cur_row = 109
rra[1].pdp_per_row = 6
rra[1].xff = 5.0000000000e-01
rra[1].cdp_prep[0].value = 5.3446000000e+00
rra[1].cdp_prep[0].unknown_datapoints = 0
rra[2].cf = "AVERAGE"
rra[2].rows = 775
rra[2].cur_row = 20
rra[2].pdp_per_row = 24
rra[2].xff = 5.0000000000e-01
rra[2].cdp_prep[0].value = 1.4063800000e+01
rra[2].cdp_prep[0].unknown_datapoints = 0
rra[3].cf = "AVERAGE"
rra[3].rows = 797
rra[3].cur_row = 627
rra[3].pdp_per_row = 288
rra[3].xff = 5.0000000000e-01
rra[3].cdp_prep[0].value = 1.0401573333e+02
rra[3].cdp_prep[0].unknown_datapoints = 0
rra[4].cf = "MIN"
rra[4].rows = 600
rra[4].cur_row = 570
rra[4].pdp_per_row = 1
rra[4].xff = 5.0000000000e-01
rra[4].cdp_prep[0].value = NaN
rra[4].cdp_prep[0].unknown_datapoints = 0
rra[5].cf = "MAX"
rra[5].rows = 600
rra[5].cur_row = 446
rra[5].pdp_per_row = 1
rra[5].xff = 5.0000000000e-01
rra[5].cdp_prep[0].value = NaN
rra[5].cdp_prep[0].unknown_datapoints = 0
rra[6].cf = "MAX"
rra[6].rows = 700
rra[6].cur_row = 392
rra[6].pdp_per_row = 6
rra[6].xff = 5.0000000000e-01
rra[6].cdp_prep[0].value = 1.3993000000e+00
rra[6].cdp_prep[0].unknown_datapoints = 0
rra[7].cf = "MAX"
rra[7].rows = 775
rra[7].cur_row = 125
rra[7].pdp_per_row = 24
rra[7].xff = 5.0000000000e-01
rra[7].cdp_prep[0].value = 1.8600000000e+00
rra[7].cdp_prep[0].unknown_datapoints = 0
rra[8].cf = "MAX"
rra[8].rows = 797
rra[8].cur_row = 634
rra[8].pdp_per_row = 288
rra[8].xff = 5.0000000000e-01
rra[8].cdp_prep[0].value = 3.0418000000e+00
rra[8].cdp_prep[0].unknown_datapoints = 0
rra[9].cf = "LAST"
rra[9].rows = 600
rra[9].cur_row = 466
rra[9].pdp_per_row = 1
rra[9].xff = 5.0000000000e-01
rra[9].cdp_prep[0].value = NaN
rra[9].cdp_prep[0].unknown_datapoints = 0
```


![image](https://github.com/user-attachments/assets/5d488438-af80-422d-9bbb-00e5bb593f75)
=> marked as root owner but no files here
![image](https://github.com/user-attachments/assets/5ea34298-43a7-4879-a440-2bc355f088ae)

**Comment by TheWitness** [comment]
So, there are a few questions.  I'll just ask a few here.  When you go to Console > Profiles > Data Source, what is the "default"?

What is your Cron and Poller interval?

It's likely for some of the data sources and graphs, you may have gotten a stray/ferrel * Template from the field that precipitated this.  In earlier versions of Cacti there wasn't as strong if a control on data source creation.

Anyway, get me those answers if you would.

**Comment by titouan-joseph** [comment]
Here the definition of default data source profile

![image](https://github.com/user-attachments/assets/3a00f073-4aee-4447-9e13-9353eab21684)


The poller interval is all 5 minutes
![image](https://github.com/user-attachments/assets/14081342-113c-4127-a248-64170ca13e98)

**Comment by titouan-joseph** [comment]
Ok, thank you
I have update the data source profile on all the data source, and now the graph are displayed

![image](https://github.com/user-attachments/assets/599088c3-65b3-45da-8e0a-b5a38567fd73)

![image](https://github.com/user-attachments/assets/85e8d197-b04e-44a9-81ee-bea557d7ca3c)

**Comment by TheWitness** [comment]
You should always also select one of those profiles and market default otherwise you'll continue to get those errors in the data source debug.
