### ISSUE TITLE
Login impossible

### ISSUE THREAD

**Issue by burnziii** [Cacti/cacti#579]
Running nginx and php7.0 after setup i get following error message:

Permission Denied
You are not permitted to access this section of Cacti.

Error log shows:

2017/04/18 20:15:03 [error] 18920#18920: *239 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: is_web in /var/www/html/cacti/include/global.php on line 177
PHP message: PHP Notice:  Undefined variable: is_web in /var/www/html/cacti/include/global.php on line 234
PHP message: PHP Notice:  Undefined variable: is_web in /var/www/html/cacti/include/global.php on line 236

**Comment by cigamit** [comment]
Must be an old 1.x version of Cacti.  Please update to 1.1.3.

**Comment by burnziii** [comment]
Cacti Version is 1.1.3 Cloned it yesterday from github..

**Comment by cigamit** [comment]
Let me review global.php.  There should be no way to do this.

**Comment by cigamit** [comment]
Please the following contents into a file in the cacti base, and then browse there with your browser.  Post the output:

vim test.php
<?php print "<pre>"; print_r($_SERVER);print "</pre>"; ?>

Thanks.

**Comment by cigamit** [comment]
You should goto this location after the file is created: http://yoursite/cacti/test.php.

**Comment by burnziii** [comment]
```
Array
(
    [USER] => www-data
    [HOME] => /var/www
    [HTTP_ACCEPT_LANGUAGE] => de-DE,de;q=0.8,en;q=0.6,en-US;q=0.4
    [HTTP_ACCEPT_ENCODING] => gzip, deflate
    [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
    [HTTP_USER_AGENT] => Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3074.0 Safari/537.36
    [HTTP_UPGRADE_INSECURE_REQUESTS] => 1
    [HTTP_CONNECTION] => keep-alive
    [HTTP_HOST] => 192.168.178.81
    [REDIRECT_STATUS] => 200
    [SERVER_NAME] => _
    [SERVER_PORT] => 80
    [SERVER_ADDR] => 192.168.178.81
    [REMOTE_PORT] => 57981
    [REMOTE_ADDR] => 192.168.178.61
    [SERVER_SOFTWARE] => nginx/1.10.0
    [GATEWAY_INTERFACE] => CGI/1.1
    [REQUEST_SCHEME] => http
    [SERVER_PROTOCOL] => HTTP/1.1
    [DOCUMENT_ROOT] => /var/www/html
    [DOCUMENT_URI] => /cacti/test.php
    [REQUEST_URI] => /cacti/test.php
    [SCRIPT_NAME] => /cacti/test.php
    [CONTENT_LENGTH] => 
    [CONTENT_TYPE] => 
    [REQUEST_METHOD] => GET
    [QUERY_STRING] => 
    [SCRIPT_FILENAME] => /var/www/html/cacti/test.php
    [PATH_INFO] => 
    [FCGI_ROLE] => RESPONDER
    [PHP_SELF] => 
    [REQUEST_TIME_FLOAT] => 1492607913.2374
    [REQUEST_TIME] => 1492607913
)
```

**Comment by burnziii** [comment]
php -v shows:
`PHP 7.0.15-0ubuntu0.16.04.4 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.15-0ubuntu0.16.04.4, Copyright (c) 1999-2017, by Zend Technologies`

**Comment by cigamit** [comment]
Should be resolved now.

**Comment by cigamit** [comment]
Just a note that with the PHP_SELF blank, there are ripple effects.  The PHP_SELF being blank is a documented issue on the web that can be fixed by configuration.  From Cacti 1.1.4 and beyond, we will be more tolerant with PHP_SELF being unset.  Plugin updates will happen after the release.
