### ISSUE TITLE
Can you recommend a hardware requirement for installing Cacti and label it in the manual

### ISSUE THREAD

**Issue by aliuzzz** [Cacti/cacti#5793]
For example, how many monitoring points are needed, how many CPU cores are needed, and how much memory is required.. I hope to migrate Cacti from a physical machine to a virtual machine

**Comment by TheWitness** [comment]
It's really tied to the plugins you have installed and the level of availability.  I've seen cacti installs with dozens of servers, some quite small. But to get a full ha for enterprise installs, having 6 servers is the entry point. 

It you don't have any uptime requirements (it's okay being down for a day or two waiting on hardware), then you can do with less.  If you have a tiny install of only a few thousand hosts, you can do with less.  It's really about the plugins these days.  Some generate a ton of data.

**Comment by aliuzzz** [comment]
I see that Cacti actually uses very little memory and cpu, But I am not sure about the memory and CPU requirements during high concurrency and when creating multiple graphs simultaneously.I only know the database requires a hard drive with fast read and write speeds. I am monitoring switches with over 5000 data sources and graphs. I want to create a virtual machine with 4 cores and 8 threads, and 16GB of memory,I am not sure if it satisfied

**Comment by TheWitness** [comment]
Lot of this has been talking about on the forums.  The size and memory needs to exceed the amount of space occupied by rrd files first of all.  Then you add to that whatever memory you've allocated for MariaDB and then on top of that whatever memory you have set up in your Apache configuration. Then finally leave some room for just normal operating system overhead. Apache can be configured in such a way that it occupies quite a bit of memory so you have to just watch that over time. 

The nice thing about a VM especially if it supports migration is you can migrate from one physical machine to another however you'd want to do that between pulling cycles if at all possible.

The downside of VM's is the noisy neighbor problem.  

We just had a ticket a few weeks ago where a user was complaining that there was something wrong with Cacti when in fact he was totally exceeding all of the available memory in the system by tens of gigabytes and was wondering why it was so slow.

**Comment by cigamit** [comment]
As TheWitness alluded to.  We can't put hard requirements (and we won't) because it completely depends on what you are monitoring, how often you are monitoring, how much data you are storing, and what additional plugins you are running.  We have systems that run with 2 CPUs / 4GB Ram and barely even use that, and we have systems that require a Fortune 500 budget and are still a bit strained.

**Comment by aliuzzz** [comment]
What is the noisy neighbor problem？For example..?

**Comment by TheWitness** [comment]
Having multiple VMs on a node and one  VM overloading the whole system, typically swapping and taking all io resources.
