### ISSUE TITLE
When editing the graph template and clicking save, a bug occurs.

### ISSUE THREAD

**Issue by maojianyou** [Cacti/cacti#5794]
# Describe the bug

On the console, after clicking on the graph, then clicking on the graph name, and editing the graph template, an error occurs when trying to save
![image](https://github.com/user-attachments/assets/ae4c745d-7bcd-4533-9c94-d41857a60222)

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///D:/Users/admin/temp/msohtmlclip1/01/clip.htm">
<link rel=File-List href="file:///D:/Users/admin/temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

Linux CentOS7.9  Operating System
Dependency | Cacti 1.2.27
-- | --
MySQL | 5.7.44
PHP | 7.3.33
RRDtool | 1.8.0
Net-SNMP | 5.7.3

</body>

</html>

Refer to the deployment documentation link
https://blog.luckykeeper.site:24680/article/68/

The system is set to Simplified Chinese. Is it possible that Cacti 1.2.27 is not very user-friendly for Simplified Chinese?

**Comment by TheWitness** [comment]
What did you do just before clicking save on the page?  Please download the locales directory from the 1.2.x branch in GitHub and replace the locales directory from the version in the 1.2.x branch.  We had some issues with the i18n() in 1.2.27.
