### ISSUE TITLE
Data-Collection does not work correctly

### ISSUE THREAD

**Issue by thomasbuesser** [Cacti/cacti#580]
Since i upgraded Cacti from version 0.8.8h to 1.1.3 for some devices i get wrong graphs. 
Only a few devices are affected. I collect 64Bit interface counters via SNMP. The graphs look "cut-off". 
![image](https://cloud.githubusercontent.com/assets/8829160/25164244/08e59198-24d0-11e7-8b39-1a6b7c4a3c52.png)

I don't get any errors or timeouts in the clog or the poller-log. Graphs look this with spine as a poller. 
Is there a problem with the new spine-verison (snmp-walk reports "Wrong Type (should be Counter64)").

**Comment by thomasbuesser** [comment]
Problem seems to be in the parsing of the snmpget output "Wrong Type (should be Counter64): Hex-STRING: 00 00 00 03 FA ED DF BF". If i replace the function format_snmp_string in lib/snmp.php everything is correct.

**Comment by cigamit** [comment]
This is an issue best handled on the forums.  This is not a support forum.

**Comment by cigamit** [comment]
I just saw your update.  What did you do to the lib/snmp.php?

**Comment by thomasbuesser** [comment]
i replaced the function format_snmp_string with the one from version 0.8.8g

**Comment by cigamit** [comment]
If you can please test with the version in the development branch and see if it properly handles a the problem that would be good.  Also, there is an issue that I closed the other day that I closed asking for a pull request.  Check that out too and let us know what works.

**Comment by cigamit** [comment]
here is the other issue https://github.com/Cacti/cacti/issues/561

**Comment by thomasbuesser** [comment]
unfortunatly no success with the developer-branch:

2017-04-19 15:05:04 - CMDPHP PHP ERROR WARNING Backtrace: (/cmd.php: 638 cacti_snmp_session_get)(/lib/snmp.php: 525 format_snmp_string)(/lib/snmp.php: 867 number_format)(CactiErrorHandler)(/lib/functions.php: 4264 cacti_debug_backtrace)
2017-04-19 15:05:04 - ERROR PHP WARNING: number_format() expects parameter 1 to be double, string given in file: /usr/local/www/apache24/data/cacti/lib/snmp.php on line: 867

**Comment by cigamit** [comment]
Did you test out the solution for issue #561.  It was not committed.  So, you have to implement manually.

**Comment by skyjou** [comment]
Hi, issue [#561](https://github.com/Cacti/cacti/issues/561) has been committed, and here is the pull request [#565.](https://github.com/Cacti/cacti/pull/565)

There is another suspicious problem in snmp.php.

In line #858, we can see a hex string which is not the MAC address will be translated to an ASCII character.

Sometimes, hex string will be IP address or other numerical value.

I do not modify this part. I think it may be difficult to determine the string should be converted to ASCII character or not.

**Comment by cigamit** [comment]
Yea, this whole issue is due to a limitation in php-snmp and also with Cacti.  When we are polling for data, we need to assume that a hex string is borked numeric data, and when we are querying we need to assume it's a string.  We also need to add an option to force a hex string output from Net-SNMP which is an open issue.  I think I'll be working on this today.  The fix to php-snmp is a little more significant.

**Comment by cigamit** [comment]
Hmm, relative to #561, I must have missed something as it is in.  Weird.

**Comment by cigamit** [comment]
Well, we are doing a release tomorrow night Ann Arbor, MI time, and we need help on this one.  Anyone have time on a Saturday or Sunday who has this issue and is willing to test?

**Comment by thomasbuesser** [comment]
Also with version 1.1.4 no success: 


2017-04-24 09:25:06 - POLLER: Poller[1] Device[4] Description[10.75.8.31] DS[1137] Graphs['10.75.8.31 - Traffic - 1/1/16/21'] WARNING: Result from SNMP not valid. Partial Result: U
2017-04-24 09:25:06 - CMDPHP PHP ERROR WARNING Backtrace: (/cmd.php: 636 cacti_snmp_session_get)(/lib/snmp.php: 525 format_snmp_string)(/lib/snmp.php: 867 number_format)(CactiErrorHandler)(/lib/functions.php: 4298 cacti_debug_backtrace)
2017-04-24 09:25:06 - ERROR PHP WARNING: number_format() expects parameter 1 to be double, string given in file: /usr/local/www/apache24/data/cacti/lib/snmp.php on line: 867

**Comment by cigamit** [comment]
Well the warning is gone, but I'm not sure the data is working well.

**Comment by cigamit** [comment]
Okay, I see the issue now.  Damn....

**Comment by cigamit** [comment]
Okay loosing track of things.  Was this issue corrected?

**Comment by cigamit** [comment]
Marking resolved.

**Comment by thomasbuesser** [comment]
Hi. sorry i was quiet bussy the last weeks. i just installed 1.1.13 and the problem seems not to be fixed...

**Comment by dschall** [comment]
I have the same problem on a newly installed v1.1.28.

**Comment by cigamit** [comment]
dschall, You should open a separate ticket.  Updating old tickets is NOT effective.  Make sure you include specific details.  Just pointing back to this ticket would be counter productive.

**Comment by dschall** [comment]
Will do, thanks!
