### ISSUE TITLE
Remove the Classic Theme in Cacti 1.3

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#5804]
# Feature Request

## Is your feature request related to a problem? Please describe

This theme holds back a number of big visualization changes in Cacti.  So, we will remove it.

## Additional context

Moving on...

**Comment by jdcoats** [comment]
I guess its time for me to pick another theme to base my customizations on. 👍

**Comment by TheWitness** [comment]
There are hacks in the code keyed on the 'cacti' theme.  We will remove those. This mostly means if you have the Cacti theme, you will get text tabs mostly.
