### ISSUE TITLE
Call to missing function in api_device.php, maybee missing include_once

### ISSUE THREAD

**Issue by arno-st** [Cacti/cacti#5807]
Cacti 1.2.27
In one of my plugin I call the function api_device_remove, but that give me the following error:
``
23/08/2024 09:40:01 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
23/08/2024 09:40:01 - ERROR PHP ERROR: Uncaught Error: Call to  undefined function api_delete_graphs() in  /usr/share/cacti/lib/api_device.php:82 Stack trace: #0  /usr/share/cacti/plugins/extenddb/setup.php(443): api_device_remove() #1  /usr/share/cacti/lib/plugins.php(282): extenddb_utilities_action() #2  /usr/share/cacti/lib/plugins.php(161):  api_plugin_run_plugin_hook_function() #3  /usr/share/cacti/utilities.php(115): api_plugin_hook_function() #4  {main} thrown in file: /usr/share/cacti/lib/api_device.php on line: 82
``

**Comment by TheWitness** [comment]
Well that's important.

**Comment by TheWitness** [comment]
You need to include in your plugin `lib/api_graphs.php` and some others if you are adding/removing things.  Check out the add_graphs.php CLI.

**Comment by TheWitness** [comment]
Going to close this one.
