### ISSUE TITLE
Missing SNMP Options in Automation

### ISSUE THREAD

**Issue by U-salbad** [Cacti/cacti#5809]
# Describe the bug

The "Default Option Set" is missing from the Automation tab on Cacti, where I cannot add or remove the SNMP option items.

## To Reproduce

Click on Automation in the side navigation bar, and you will not find the SNMP Options, where I can add or remove the Option sets for automation for adding devices

## Expected behavior

It should show to add or remove items for the option sets of SNMP

## Screenshots

<img width="113" alt="Screenshot 2024-08-25 151954" src="https://github.com/user-attachments/assets/7b3bd113-bd56-4314-abf5-7af147d6559c">

## Desktop (please complete the following information)

- OS: windows 10

- Browser Chrome and FireFox

- Version latest

## Additional context

Maybe it is related to when I was installing it, where I chose not to add devices through an automation process.

**Comment by U-salbad** [comment]
So it is not a bug, but the SNMP options has been moved!
Sorry for the inconvenience.

**Comment by TheWitness** [comment]
Yea, I moved them as it was more of a preset.
