### ISSUE TITLE
Scheduled reports (type "tree") not working.

### ISSUE THREAD

**Issue by bmcgoncalves** [Cacti/cacti#581]
Hi,

When i try to automaticaly send reports in a scheduled hour the report will come with no graphs.
This issue appens when the reporte items are from type "tree". If i click in "Send Report" the report works like a charm.
Reports works fine for individual  graphics.

LOG:
2017-04-19 08:41:48 - CMDPHP PHP ERROR NOTICE Backtrace: (/poller_reports.php: 156 generate_report)(/lib/reports.php: 401 session_start)(CactiErrorHandler)(/lib/functions.php: 4295 cacti_debug_backtrace)
2017-04-19 08:41:48 - ERROR PHP NOTICE: A session had already been started - ignoring session_start() in file: /data/gorv/prod/tools/gui/cacti/lib/reports.php on line: 401

**Comment by cigamit** [comment]
What version of Cacti?  This should not be happening.  Did you install from package?  If you are running anything 1.1.x and above, and it's from a package, the packager has created this problem.

**Comment by bmcgoncalves** [comment]
The version is 1.1.2.
We've downloaded the cacti from github and made de unzip directly on server. 
Then we upgraded the cacti.

**Comment by bmcgoncalves** [comment]
Yesterday i've downloaded the latest version of cacti (1.1.3 zip) from cacti website and then i've upgraded from 1.1.2 version.
The issue still remains. I dont know what do you mean about "package", i've downloaded a official release from your website. Now i dont see any errors in the log.

It's not a major issue, i can put the graphs in report individualy, but its much more praticaly to use a regex to select the graphs.
The very strange thing is if i click in "send report" i receive the email with the graphs. So i've discarded the possibility for the problem beeing in the email, or in the size of email or in the number of graphs.

**Comment by cigamit** [comment]
If you are using nginx, then I think this has been resolved in a separate bug report.

**Comment by cigamit** [comment]
I've cleared the session_start() warnings.  Still looking into the reasons that the tree is not functioning.

**Comment by The-Mafioso** [comment]
2017-04-22 22:20:07 - ERROR PHP NOTICE: A session had already been started - ignoring session_start() in file: /var/www/cacti-1.1.3/lib/reports.php on line: 401
2017-04-22 22:20:07 - CMDPHP PHP ERROR NOTICE Backtrace: (/reports_admin.php: 44 reports_send)(/lib/html_reports.php: 780 generate_report)(/lib/reports.php: 401 session_start)(CactiErrorHandler)(/lib/functions.php: 4262 cacti_debug_backtrace)

**Comment by cigamit** [comment]
You need to update lib/reports.php

**Comment by The-Mafioso** [comment]
i am using 
Cacti v 1.1.3
Ubuntu 16.04.2 LTS
Server version: Apache/2.4.18 (Ubuntu)
PHP 5.6.30-10+deb.sury.org~xenial+2 (cli) 
Still same error

**Comment by cigamit** [comment]
I've confirmed this is working now.  Therefore closing.

**Comment by bmcgoncalves** [comment]
Hi, 

Yesterday i've isntalled the 1.1.4 version and the reports are still empty.
My configuration is for a branch (cascade to branches) and not a device. 

The changelog for version 1.1.4 is for device i think:
issue#524: Reporting not working when Tree branch is device.

**Comment by cigamit** [comment]
What is your regular expression?

**Comment by bmcgoncalves** [comment]
Report #1: 
- Item #0: .*Global Active Local Contacts.*
- Item #1: .*Active Local Contacts \\(IPCx\\)

Report #2: 
- Item #0: .*CPU Utilization.*
- Item #1: .*Memory Utilization.*

The issue occurs in both reports.

**Comment by cigamit** [comment]
I can't reproduce this.  You are going to have to keep digging.  Attach some screen shot's and include screen shot's owning user's graph permissions filtered by CPU.  I'm guessing it maybe something permission related.  Though it could be a code defect.

**Comment by The-Mafioso** [comment]
Hi,
I have installed Cacti v1.1.5, Tree reports are now working i am able to get the email when i press on send report with full graphs (thumbnails) but when the report is set to scheduled i still get the email but no graphs inline. I have tried inline png/jpg/gif and attached as well, all not working. I just get the email but no content inline/attached (empty mail)

Cacti Log shows no issues except email was sent

**Comment by cigamit** [comment]
View the message source and post it here.

**Comment by The-Mafioso** [comment]
Hi,
This is a message source of a working email when i press on send report:
[original_msg.txt](https://github.com/Cacti/cacti/files/966052/original_msg.txt)

**Comment by The-Mafioso** [comment]
This is a message source of a scheduled report which has empty content:
[original_msg_empty.txt](https://github.com/Cacti/cacti/files/966057/original_msg_empty.txt)

**Comment by The-Mafioso** [comment]
The only difference i have noticed in the header of the message is when i press on send report the email is:
**Received: from beta.tesing.testing.com ([x.x.x.x])**

When the report is scheduled:
**Received: from CMain ([x.x.x.x])** 

Cmain is the localhost name of my server

**Comment by The-Mafioso** [comment]
I am not sure if this might help but i am attaching the preview/item edit from the report, so all looks good even when i press the send report tab i get all the graphs but the scheduled emails are the ones that has no content

![item](https://cloud.githubusercontent.com/assets/27900099/25697814/2019a0f6-30c5-11e7-9426-f39549ce57fc.png)
![preview](https://cloud.githubusercontent.com/assets/27900099/25697820/23f3c92c-30c5-11e7-8e9c-b6a9a047f2be.png)

**Comment by cigamit** [comment]
There is a size limit setting on the settings page.  Why don't your try increasing it and see if it makes a difference.  The message source included the attachments.  So, I'm uncertain what is going on.  Actually, I'm real short of time presently.  Also, reboot/Patrick has made some recent changes in lib/rrd.php, that when merged may fix this.  However, I still need to peer review his change.

**Comment by The-Mafioso** [comment]
Tried all the attachment sizes options and non worked. same behavior

**Comment by komathodivijay** [comment]
For me also same issue. I tried all possible way.:-(

**Comment by The-Mafioso** [comment]
HI
if it will help, I have tried the Cacti-Development version and still the issue exists with the new files

**Comment by The-Mafioso** [comment]
I did some debugging on mysql and i hope the output attached will help. 
force.txt --> is the output file when i press send report  int he reports tab and i get the email with the proper graphs for the tree attached

auto.txt --> is the output file when the report is scheduled to sent by the poller

[force.txt](https://github.com/Cacti/cacti/files/985291/force.txt)
[auto.txt](https://github.com/Cacti/cacti/files/985292/auto.txt)

**Comment by The-Mafioso** [comment]
any workaround please
