### ISSUE TITLE
IP address in script not updated

### ISSUE THREAD

**Issue by WirthmU** [Cacti/cacti#5818]
I had to transfer the whole cacti onto a new system (v1.2.27). Almost everything is running fine but I found the following bug:
One of the ping scripts uses the devices IP. After I had to change the devices IP-adress in the devices it still keeps the old IP in the script. The current IP-adress is 192.168.1.191, the one before was 196.168.1.194.

Management > Devices > Device (uRadMonitor A1 / 192.168.1.191)

The logfile shows:
`2024-09-09 16:47:11 - SPINE: Poller[Main Poller] PID[3330136] PT[140011739526720] WARNING: Invalid Response(s), Errors[1] Device[uRadMonitor A1] Thread[1] DS[uRadMonitor A1 - Ping Host] Graphs[uRadMonitor A1 - Ping Latency] `

The script in Systems Utilities > View Poller Cache shows:
for the ping template:
`Script: perl /var/www/html/cacti/scripts/ping.pl '192.168.1.194' `
the underlying script command in the Data Input Methods is:
`perl <path_cacti>/scripts/ping.pl <ip>`

for the advanced ping template:
`Script Server: /var/www/html/cacti/scripts/ss_fping.php ss_fping '192.168.1.191' '20' 'ICMP' '' `
the underlying script command in the Data Input Methods is:
`<path_cacti>/scripts/ss_fping.php ss_fping <hostname> <attempts> <protocol> <port>`

UBUNTU 22.04.4 LTS
Firefox

Where is the variable `<ip>` coming from? The one called `<hostname>` seems to be correct.

**Comment by TheWitness** [comment]
Is fping installed?

**Comment by WirthmU** [comment]
The problem has been solved.

The corresponding data source required an IP address as custom data. The IP address entered was not ping-able so the error in the log-file occurred.
