### ISSUE TITLE
When displaying graphs, default end time does not show full 24 hour period

### ISSUE THREAD

**Issue by dmitry-moiseenko** [Cacti/cacti#5819]
![graph_cacti](https://github.com/user-attachments/assets/b5e4c117-42fd-4db6-9757-3764ffa05fb1)

# Describe the bug

Console -> Management -> Graphs and select any graph, it opens, but the time is always 5 minutes behind the current time (I mean the last point on the graph).

In my understanding, it should automatically display a 24-hour interval, but in reality, it always shows 23:55.

Cacti Version 1.2.27
Oracle Linux 9

**Comment by TheWitness** [comment]
This is correct.  We may be well served by re-evaluating this.  We try to ensure we don't get the gaps at the end, but if you are polling at 30 seconds, it can be annoying.

**Comment by dmitry-moiseenko** [comment]
No, we do polling once a minute. We also use the weathermap plugin, and the delay is a bit annoying. It would be great if this could be re-evaluated.

**Comment by TheWitness** [comment]
@dmitry-moiseenko , please try the latest `lib/rrd.php`

**Comment by TheWitness** [comment]
@dmitry-moiseenko, I just made another small tweak for the timespan selector.  Looking good now there.

**Comment by dmitry-moiseenko** [comment]
Thank you so much for that fix. It works perfectly!

**Comment by dmitry-moiseenko** [comment]
Thank you so much for that fix. It works perfectly!

**Comment by TheWitness** [comment]
Perfect @dmitry-moiseenko.  Thanks for inspiring me to make the change.
