### ISSUE TITLE
graph per minute interval and refresh

### ISSUE THREAD

**Issue by stalker37** [Cacti/cacti#582]
Hi.

In cacti version ~0.8.8h I can click on graph title and view graph's
with minute, 5 minutes and some more interval.
After update to cacti version 1.1.3  this is  no longer available.
If I click to "Tine Graph View" icon I see  graph with 5 minutes and
some more interval, but not "one minutes" interval and after page in
browser it show main page with graphs, not refresh current page.

Live  view also does not provide the required functionality
![1](https://cloud.githubusercontent.com/assets/6966211/25173828/38de6752-24fe-11e7-8cb9-470b18cc1ca8.png)

Needed like this (one minute from older cacti and refresh in browser)

![2](https://cloud.githubusercontent.com/assets/6966211/25173840/3ee93172-24fe-11e7-8a29-c523013170c4.png)

**Comment by cigamit** [comment]
This is not a bug, this is a training issue that belongs on the Forums.  Please learn what Data Source Profiles are and how to use them.
