### ISSUE TITLE
Add Location and Site to Graph List View

### ISSUE THREAD

**Issue by Heydos** [Cacti/cacti#5828]
# Feature Request

## Is your feature request related to a problem? Please describe

I'm always frustrated when I want to search graphs by location or site.

## Describe the solution you'd like

Site and Location be added to the Graph List View and Graph Preview filters.

## Describe alternatives you've considered

NA

## Additional context

The Management Devices filter has Site and Location, but the Graph List View Filters and Graph Preview Filters do not.

**Comment by TheWitness** [comment]
Okay, this will make it into the 1.2.28 release.  Glad you logged it!
