### ISSUE TITLE
 gaps in the data on the graph

### ISSUE THREAD

**Issue by dmitry-moiseenko** [Cacti/cacti#5834]
![photo_2024-09-24_09-36-13](https://github.com/user-attachments/assets/57c69d62-938b-46e8-baa4-58764f35d9a8)

There are gaps in the data on the graph, even though the MAX line is higher, and logically there shouldn't be any gaps.

**Comment by TheWitness** [comment]
@dmitry-moiseenko ,

There is no issue here.  What is your polling interval?  What data source profile?  This is common for the 1 minute or 30bsecond poller intervals when the averages are less than the peaks.

**Comment by dmitry-moiseenko** [comment]
Changed avarage to max made it beautiful. Thank you.
