### ISSUE TITLE
graphs not updating

### ISSUE THREAD

**Issue by aqr199** [Cacti/cacti#5835]
## cacti info
CentOS7.9
version: 1.2.18
PHP 7.3.32
NET-SNMP version:  5.7.2
RRDtool 1.4.8

## issue
graphs not updating

## log
CMDPHP WARNING: cmd.php poller has run over its polling interval and therefore is ending
POLLER: Poller[1] PID[9848] Maximum runtime of 58 seconds exceeded. Exiting.
SYSTEM STATS: Time:59.4255 Method:cmd.php Processes:1 Threads:1 Hosts:133 HostsPerProcess:133 DataSources:2585 RRDsProcessed:2036

## how to do

when poller.php run will recover modify php file
need chang file own, other can read, can't write

REPLICATE INFO: Updating '/var/www/cacti-1.2.18/host.php' from Cache!
REPLICATE INFO: Updating '/var/www/cacti-1.2.18/poller.php' from Cache!

# modify poller.php

if $config['poller_id'] eq $poller_id
it will look like local

```
...
case '--poller':
        $poller_id = $value;
        $config['poller_id'] = $value;
        break;
...
```

# add poller.php crontab

```
* * * * * /usr/bin/php /var/www/cacti-1.2.18/poller.php
* * * * * /usr/bin/php /var/www/cacti-1.2.18/poller.php --poller=2
* * * * * /usr/bin/php /var/www/cacti-1.2.18/poller.php --poller=3
```

# modify host.php

when chang devices Poller Association
webpage show php info in div#ping_results

original: api_device_ping_device($host_id);
modify: api_device_ping_device($host_id, true);

```
...
case 'ping_host':
    $host_id = get_filter_request_var('id');
    api_device_ping_device($host_id, true);
    
    break;
...
```

# chang devices Poller Association

!!! can chang poller, but error msg show [Unable to establish MySQL connection with Remote Data Collector.]

## it's work

# log
SYSTEM THOLD STATS: Time:0.1298 Tholds:36 TotalDevices:133 DownDevices:0 NewDownDevices:0
SYSTEM STATS: Time:13.1330 Method:cmd.php Processes:1 Threads:1 Hosts:16 HostsPerProcess:16 DataSources:273 RRDsProcessed:0
SYSTEM STATS: Time:17.1285 Method:cmd.php Processes:1 Threads:1 Hosts:14 HostsPerProcess:14 DataSources:284 RRDsProcessed:0
SYSTEM STATS: Time:35.3619 Method:cmd.php Processes:1 Threads:1 Hosts:103 HostsPerProcess:103 DataSources:2005 RRDsProcessed:0

## can i have best solution?

Upgrade or any suggestions

**Comment by xmacan** [comment]
use spine instead of cmd poller. 

Github issues are for reporting bugs or feature requests. For similar questions, use forums.cacti.net.

**Comment by aqr199** [comment]
poller.php use multi threads is possible?

**Comment by xmacan** [comment]
**Method:cmd.php Processes:1 Threads:1**  - Try increase number of threads in Console -> Data collection -> Data Collectors -> edit your poller -> increase processes

**Comment by aqr199** [comment]
thanks a lot, it's work

SYSTEM STATS: Time:20.1343 Method:cmd.php Processes:1 Threads:1 Hosts:24 HostsPerProcess:24 DataSources:314 RRDsProcessed:0
SYSTEM STATS: Time:16.1626 Method:cmd.php Processes:1 Threads:1 Hosts:16 HostsPerProcess:16 DataSources:273 RRDsProcessed:0
SYSTEM STATS: Time:16.6573 Method:cmd.php Processes:4 Threads:1 Hosts:93 HostsPerProcess:24 DataSources:1975 RRDsProcessed:0
