### ISSUE TITLE
Reduce the number of default log from automation

### ISSUE THREAD

**Issue by arno-st** [Cacti/cacti#5838]
When you have some amount of automation, it can be annoying to log every event.

So I propose to add an option under Console -> Configuration -> Settings->General, section Automation
A flag of the style
Log Automation Automatic Creation Enable/Disable

And this will be used to log or not when an automation action is processed
But that will not touche the default logging of error detected by automation.

The goal is to avoid this kind of messages:
`
27/09/2024 12:10:53 - AUTOM8 NOTE: Graph Added - Device[], Graph[], DS[[Missing Datasource 30553](https://cacp.lausanne.ch/cacti/data_sources.php?action=ds_edit&id=30553)]
`
`
27/09/2024 12:10:53 - AUTOM8 NOTE: Data Check Succeeded for - Device[], GT[[Device - Polling Time](https://cacp.lausanne.ch/cacti/graph_templates.php?action=template_edit&id=118)]
`
`
27/09/2024 10:14:28 - AUTOM8 NOTE: Graph Added - Device[[se-pdp-05](https://cacp.lausanne.ch/cacti/host.php?action=edit&id=3244)], Graph[[se-pdp-05 - Traffic - Te1/1/4 - SE-PDP-04 / C9200L-24P-4X / Te1/1/1 ](https://cacp.lausanne.ch/cacti/graph_view.php?page=1&style=selective&action=preview&graph_add=29899)], DS[[se-pdp-05 - Traffic - Te1/1/4 - SE-PDP-04 / C9200L-24P-4X / Te1/1/1](https://cacp.lausanne.ch/cacti/data_sources.php?action=ds_edit&id=30550)] Graphs[[se-pdp-05 - Traffic - Te1/1/4 - SE-PDP-04 / C9200L-24P-4X / Te1/1/1 ](https://cacp.lausanne.ch/cacti/graph_view.php?page=1&style=selective&action=preview&graph_add=29899)], Rule[[Traffic uplink Port](https://cacp.lausanne.ch/cacti/automation_graph_rules.php?action=edit&id=12)]
`

But not for this kind of error:
`
27/09/2024 12:10:53 - AUTOM8 NOTE: Graph Added - Device[], Graph[], DS[Missing Datasource 30553]
`

**Comment by TheWitness** [comment]
This makes some sense.

**Comment by TheWitness** [comment]
This ticket was solved in this commit b85ce246f990902301a266126fb9b895ce14f434.
