### ISSUE TITLE
lib/boost.php variable is not in use $query_string_suffix = 'ORDER BY local_data_id ASC, timestamp ASC, rrd_name ASC';

### ISSUE THREAD

**Issue by MSS970** [Cacti/cacti#5841]
Cacti [1.3.0 Dev]

lib/boost.php variable is not in use line #737:
$query_string_suffix = 'ORDER BY local_data_id ASC, timestamp ASC, rrd_name ASC';

**Comment by TheWitness** [comment]
Thanks!
