### ISSUE TITLE
When using Preset Time to view graphs, it is using a fixed point rather than relative time

### ISSUE THREAD

**Issue by jabotteff** [Cacti/cacti#5847]
# Presets Time in Cacti 1.2.28 Not Automatically Updating

I'm currently using Cacti version 1.2.28 and have noticed something odd regarding the "Presets time" behavior. I expected that when I select a preset time (like "Last 24 hours"), it should display the most recent 24-hour period from the current moment when the page is viewed or refreshed. However, I’ve noticed that the time is only updated at login. After, say, 20 minutes of being logged in, the preset time doesn't refresh to show the most recent 24 hours. I have to log out and back in to get the correct time range again.

## To Reproduce

1. Install fresh instance Cacti 1.2.28

2. Log in and check Presets -> Last day

3. Wait few minutes

4. Refresh the page -> setting time “Last day” is counted from the time of login.

## Expected behavior

Refresh the page -> setting time “Last day” should be counted from the time of refresh the page.

## Serwer side

- OS: Linux Ubuntu server 22.04.5 LTS (Jammy Jellyfish)"
- Apache/2.4.52 (Ubuntu)
- PHP Version | 8.1.2-1ubuntu2.19
- SQL: Server version: 10.6.18-MariaDB-0ubuntu0.22.04.1 Ubuntu 22.04
- Cacti 1.2.28

## Client side 

- OS: Windows 10
- MS Edge (latest), Firefox (latest)

## Additional context

I did test. I have installed version 1.2.27 and and 1.2.28 (fresh installation).
On version 1.2.27 presets time behavior is correct and on the latest version it is wrong - as I described in the thread.

**Comment by KnoAll** [comment]
Chiming in as I've confirmed this also over in the forum thread.

**Comment by skyjou** [comment]
Does [this change](https://github.com/Cacti/cacti/commit/28d5c4a83de644fcc543c1183c851689c15b2bd0) cause the issue?

**Comment by KnoAll** [comment]
Yes, it would appear so. Based on your suggestion over in the forum thread, the fix appears to work.

**Comment by bmfmancini** [comment]
Confirmed this is fixed now

**Comment by expertimentor** [comment]
I am seeing this exact issue in my installation of version 1.2.28 - two weeks old on a fresh Debian 12. It includes the change of Commit 28d5c4a.
Graph Preset is set and saved to "Last Day". Page refresh, choosing different time preset, "Clear" (return to default time span) does not update the current time. But logging in or just hitting the "Save" button in the Console, i.e. in Configuration/Settings without any changes, does update the time.
