### ISSUE TITLE
Extra single quotes being added to data source

### ISSUE THREAD

**Issue by stormonts** [Cacti/cacti#585]
This is working fine in Cacti 0.8.8 and the extra single quotes shown in the images below do not show up.  The command needs to run as "python /usr/local/cacti-1.1.3/scripts/memcached.py -p 11211 127.0.0.1" with no quotes.  Neither the "input string" field on the Data Input Method, or the "Custom Data" field in the Data Source have the single quotes, but they show up in the poller cache.
![data_input_method](https://cloud.githubusercontent.com/assets/25824323/25197578/92d7d446-2512-11e7-8732-19835759350c.png)

![data_source](https://cloud.githubusercontent.com/assets/25824323/25197587/988c97e6-2512-11e7-846f-1313e43d50b6.png)

![poller_cache](https://cloud.githubusercontent.com/assets/25824323/25197620/a94ab46e-2512-11e7-8646-faf205b1e4bb.png)

**Comment by stormonts** [comment]
Never mind, I had to re-write the command in a different notation for 1.1.x.

python <path_cacti>/scripts/memcached.py -p <port> <hostname>

**Comment by cigamit** [comment]
You are correct.  We are performing escaping now, and what you had done originally was not correct.  Escaping protects the Cacti system.
