### ISSUE TITLE
When the traffic value is too high, the monitoring will show a broken image

### ISSUE THREAD

**Issue by aliuzzz** [Cacti/cacti#5853]
The monitored eth-trunk group cannot display traffic values exceeding 10G. I chose "in/out (bits, 64)", while the actual traffic of my eth-trunk group ranges from 60g to 100G.Here is my picture
The issue did not occur with version 0.8.8
for example
![image](https://github.com/user-attachments/assets/e503777a-6a90-427e-b45d-8c3dd6a70ae0)
![image](https://github.com/user-attachments/assets/fa3cc865-7a24-43d2-8104-c75d2c6c8ddb)

**Comment by aliuzzz** [comment]
I did not detect this issue while monitoring the ports of the switch. There have been instances of eth trunk and vlan being monitored

**Comment by TheWitness** [comment]
This is common for device interfaces that report a bogus ifHighSpeed.  If this is the case, report this first to the hardware provider and see if you can get them to fix this, and then increase the maximum value in the RRDfiles similar to this.

```sh
rrdtool tune /file/name.rrd -a traffic_in:newvalue -a traffic_out:newvalue
```

It's best not to use 'U', but a real value.  This is to prevent spikes.  If you are looking for a rule that does this automatically based upon an interface string match, log a new issue as a feature.

**Comment by TheWitness** [comment]
In that feature request, I would suggest you recommend a default regular expression.  Thanks!

**Comment by TheWitness** [comment]
In the develop version, I'm suggesting that we 'could' use the ifDescr or ifName regular expression match as a test field and then use the speed that is shown here.

![image](https://github.com/user-attachments/assets/257960c2-2d65-4671-927f-2102096ac9ee)

You should see if the ifSpeed and ifHighSpeed first have a null or 0 value.  In that case, you simply need to change the default in the settings and then run the rrdtool command to do the updates.

**Comment by TheWitness** [comment]
This dropdown is in 1.2.28, but the proposed feature enhancement would only go into 1.3.

**Comment by aliuzzz** [comment]
> This is common for device interfaces that report a bogus ifHighSpeed. If this is the case, report this first to the hardware provider and see if you can get them to fix this, and then increase the maximum value in the RRDfiles similar to this.
> 
> ```shell
> rrdtool tune /file/name.rrd -a traffic_in:newvalue -a traffic_out:newvalue
> ```
> 
> It's best not to use 'U', but a real value. This is to prevent spikes. If you are looking for a rule that does this automatically based upon an interface string match, log a new issue as a feature.

what means "not to use U",but a real value？
I hope you can tell me what factors were taken into account to make this feature usable in version 0.8.8 but not after version 1.2. x

**Comment by TheWitness** [comment]
It all depends on the version of the template you are using.  Some people are okay using 'U' as the max value.  That's your choice.  We prefer to go with a pre-defined max value as specified in that setting, which is NEW.  Closing this one now.
