### ISSUE TITLE
cacti 1.2.28  add host CS style is missing

### ISSUE THREAD

**Issue by wjl66880088** [Cacti/cacti#5863]
OS : Centos stream 8
php: 7.4
Mariadb :mariadb-server-10.3.28
apache : 2.4
cacti: 1.2.28

Problem description
Add host error, please see screenshot

![1](https://github.com/user-attachments/assets/71607cd4-cdc6-49a3-a7bc-de68f102e9d2)

**Comment by bmfmancini** [comment]
When is this happening ?
Is this when you are saving the device ?

**Comment by xmacan** [comment]
I think that it is old bug. I have met it sometimes. I'm not sure but maybe it is connected with upper device menu (enable debug for device, reindex device, ...)

**Comment by TheWitness** [comment]
I would recommend that the user run the following script as a start:

```sh
cd locales
./build_gettext.sh
```

**Comment by TheWitness** [comment]
The header=false is the big issue.  This generally happens when you hit F5 on the browser and for some reason the 'header=false' ends up in the refresh.

**Comment by TheWitness** [comment]
No feedback.

**Comment by chengjiangghr** [comment]
> I would recommend that the user run the following script as a start:
> 
> ```shell
> cd locales
> ./build_gettext.sh
> ```

I tried. It doesn't work.

**Comment by chengjiangghr** [comment]
> I think that it is old bug. I have met it sometimes. I'm not sure but maybe it is connected with upper device menu (enable debug for device, reindex device, ...)

1.2.27 1.2.28 They all have this problem.

**Comment by TheWitness** [comment]
So, the rebuild did not work or the rebuild worked, but it did not fix the issue?

What exact steps do you follow to reproduce?  Does it only happen with the Chinese language?

**Comment by wjl66880088** [comment]
> So, the rebuild did not work or the rebuild worked, but it did not fix the issue?
> 
> What exact steps do you follow to reproduce? Does it only happen with the Chinese language?

Yes, it only occurs in Chinese  language, English is normal

**Comment by TheWitness** [comment]
What steps?
