### ISSUE TITLE
The latest version of cacti has page confusion problem

### ISSUE THREAD

**Issue by chengjiangghr** [Cacti/cacti#5865]
环境：
http-apache 2.4.56
php-8.2.4
mysql-5.7.33
cacti(1.2.27  1.2.28都一样)

问题描述：
1、安装部署完cacti最新版本（1.2.27,1.2.28）后，登录系统后，点击页面右上角的个人配置文件，将语言改成中文

2、添加设备保存，会出现页面错乱情况，如下：
![image](https://github.com/user-attachments/assets/7be2b6ed-b5ed-48ee-8fcf-f7553c8a7c19)

3、我尝试过1.2.25的版本中文是正常的，但是1,2,27及最新的1.2.28都不行

**Comment by TheWitness** [comment]
Please recompile your language file and let us know if the problem fixes itself.

```sh
cd locales
./build_gettext.sh
```

**Comment by TheWitness** [comment]
Please try to submit in English @chengjiangghr

**Comment by TheWitness** [comment]
Closing.  Duplicate of @5863.
