### ISSUE TITLE
Allow IPv6 formats to use colons without port

### ISSUE THREAD

**Issue by xmacan** [Cacti/cacti#5874]
The problem is when the hostname of the device is in the format aaaa:bbbb:...This conflicts with cacti_snmp_get/walk functions due to the additional the port number
cacti_escapeshellarg($hostname) . ':' . $port . ' ' .

actual 1.2x branch

**Comment by TheWitness** [comment]
This issue was resolved here: https://github.com/Cacti/cacti/pull/5875
