### ISSUE TITLE
"Configuration -> Settings -> Paths" "Save" button doesn't work

### ISSUE THREAD

**Issue by morganfw** [Cacti/cacti#5878]
# Describe the bug

Hello,
we need to disable RRDfile Auto Clean from the GUI, but the 'Save' button doesn't work.

## To Reproduce

1. Go to 'Configuration' - 'Settings'

2. Click on 'Paths' tab and click on 'Save' button

3. The 'Save' action doesn't do anything

## Expected behavior

The "Save" button works

**Comment by xmacan** [comment]
Which cacti version? Cannot reproduce on actual 1.2.28

**Comment by morganfw** [comment]
> Which cacti version? Cannot reproduce on actual 1.2.28

1.2.28 version 5af8cb2 commit

**Comment by xmacan** [comment]
still cannot reproduce, any error in log?

**Comment by morganfw** [comment]
> still cannot reproduce, any error in log?

No errors in cacti.log

**Comment by xmacan** [comment]
theme? Different browser?

**Comment by morganfw** [comment]
> theme? Different browser?

After switching to default theme then switch again to my theme, the "Save" button now is working again.

Thank you for the support!
Regards

**Comment by TheWitness** [comment]
Likely a JavaScript error.  Which theme and language were you using when it was broken?
