### ISSUE TITLE
[1.1.3] Network Automation, auto-adds devices when sysDescr is blank. No matching rules

### ISSUE THREAD

**Issue by scline** [Cacti/cacti#588]
Messing with the network discovery rules. It appears if an SNMP device does not have a `sysDescr` (shows an N/A in the GUI) and auto-add device is enabled. Even with no rules matching a blank description the hosts are added with the lowest `host template`.

An example entry in the table `automation_devices`
`# id, network_id, hostname, ip, community, snmp_version, snmp_port, snmp_username, snmp_password, snmp_auth_protocol, snmp_priv_passphrase, snmp_priv_protocol, snmp_context, snmp_engine_id, sysName, sysLocation, sysContact, sysDescr, sysUptime, os, snmp, known, up, time
'2084', '3', 'test.drac.test.com', '10.150.4.56', 'public', '2', '161', 'admin', 'baseball', 'MD5', '', 'DES', '', '', 'testhost', 'unknown', 'support@dell.com', '', '4127510', '', '1', '0', '1', '1492700404'
`

**Comment by cigamit** [comment]
If you have an automation template with a 'blank' sysDescr, and there are no other matching rules, it will add the device using the blank system description.  This is as designed.  The design states that if you have a device template with a blank system description, it becomes the 'catch' all.  So, if you don't want them used that way, don't create an automation template with a blank system description.  If you think it's a bad design, suggestions would be welcomed.

**Comment by scline** [comment]
Well thats the thing :) I dont have any device templates with a 'blank' sysDescr. The only line for example under `automation_templates` table is :
`# id, host_template, availability_method, sysDescr, sysName, sysOid, sequence
'4', '3', '4', 'Juniper', '', '', '0'`

Where it should only match when sysDescr includes "Juniper". But it also matches against ""

**Comment by cigamit** [comment]
Should be resolved now.

**Comment by scline** [comment]
Thank you for all the fixes cigamit, you guys/girls are kicking butt!
