### ISSUE TITLE
No graphs show after login until "All Graphs & Templates" is reselected in the Graph Filters header

### ISSUE THREAD

**Issue by dallenk** [Cacti/cacti#5882]
# Describe the bug

Seems to have started with the last commit: https://github.com/Cacti/cacti/commit/8a8541d11dcf9c2205429f673eef41fc344ef820

## To Reproduce

1. Navigate to any tree item and view graphs, then Log out of current session

2. Log in with new session, click "Graphs"

3. go to "Graphs"  -> navigate to the tree item (if it didn't save your last selection), no graphs shown

4. In the "Graph Filters" header, click the select "All Graphs & Templates" to expand the list, then click again to close it.
5. Graphs are shown.

## Expected behavior

The template selection doesn't seem to be saved or re-read on new login.

## Screenshots
![step 1](https://github.com/user-attachments/assets/defccf78-b9e8-4f85-ba55-d34231b80c30)

![step 3](https://github.com/user-attachments/assets/97730129-b1cd-4a89-98b5-436fd86d1294)

![step 4](https://github.com/user-attachments/assets/cc85a8f2-d6c7-4fda-9f49-9a25dc170e92)

![step 5](https://github.com/user-attachments/assets/f14fb13f-7a8e-46da-889d-77152c8a8606)

**Comment by TheWitness** [comment]
Yea, I'm seeing that too.

**Comment by TheWitness** [comment]
Just getting back to things after a vacation.

**Comment by dallenk** [comment]
> Just getting back to things after a vacation.

Hope your vacation was good!   Mine never seem long enough.

**Comment by TheWitness** [comment]
Should be all fixed up now.
