### ISSUE TITLE
[QA 1.3] Sort by "Site" results in no devices shown

### ISSUE THREAD

**Issue by dallenk** [Cacti/cacti#5886]
# Describe the bug

When viewing all devices, sorting by "Site" hides all devices, but the count is correct

## To Reproduce

1 - Management / Devices
2 - Verify devices are shown
3 - Click "Site" in the header
4 - No devices are shown

## Screenshots

![image](https://github.com/user-attachments/assets/7ece1277-b540-4481-b2b8-c57e46c40b0c)

I think this is a CSS issue, and I tried to find the code that does this, but my skills are pretty lame.

**Comment by TheWitness** [comment]
@sgvfr, fixed now.  Thanks for reporting.  I'm all over the place right now.  Getting there.
