### ISSUE TITLE
 Automatic refresh for Time Graph View doesn't work after update

### ISSUE THREAD

**Issue by ISekan** [Cacti/cacti#5888]
Update from Cacti 1.2.25 to Version 1.2.28
PHP Version  8.1.27
Centos9
11.2.5-MariaDB

cacti logs is ok
![cacti2323](https://github.com/user-attachments/assets/88cc2212-5359-4c7a-8d41-88ff7fd55565)

**Comment by bmfmancini** [comment]
Do you see any browser console errors?
What browser are you using?

**Comment by ISekan** [comment]
no errors
tried Firefox, Chrome, Edge - all the same
page is refreshing, but the time counter does not increase and the graph is still in place

**Comment by bmfmancini** [comment]
Pull down the latest

lib/timespan_settings.php from the 1.2.x branch

**Comment by ISekan** [comment]
[bmfmancini](https://github.com/bmfmancini) thanx! the timespan_settings.php from v1.25 solved the problem!

**Comment by bmfmancini** [comment]
Glad your fixed up!
