### ISSUE TITLE
[Cacti 1.1.3] Automation discovery : Improvements

### ISSUE THREAD

**Issue by jhonnyx82** [Cacti/cacti#589]
When a device is discovered in Cacti I noticed some honest mistakes, so I am proposing :

- Discovered devices inserted in cacti automatically does not use the same poller used for the discovery, but the default one [should be used the poller used for the discovery]
- There is no option to configure the SITE the newly created device will be assigned to
- After the discovery even if the devices are created, they are not automatically inserted into a tree or subtree if not by manually applying the automation rules

**Comment by cigamit** [comment]
The first issue has been resolved separately and will be released as a part of 1.1.4.  The second point is valid, and will be corrected shortly.  Have to research the third.  Thanks.

**Comment by jhonnyx82** [comment]
Thanks,

Appreciate it really, if you need some testing please let me know

**Comment by cigamit** [comment]
Two of three now resolved.  Have to see about the last part now.

**Comment by cigamit** [comment]
I've performed a code review.  Tree creation should be working.  I did remove one un-needed function, but I'm pretty certain tree automation should fire in that when a device is saved, tree automation will take place.  If you are talking about devices that already exist, that would be a different story.

I'm going to close, but you still have an opportunity to clarify on that last point.

**Comment by jhonnyx82** [comment]
Thank you,

I will validate and reply with some info in 1 or 2 days.

**Comment by cigamit** [comment]
If you find that there are issues, let's open a fresh ticket.

**Comment by jhonnyx82** [comment]
I have created a new issue #602 

Thanks for looking into these features, I hope these can make it for rel 1.1.4

Let me know if you need some testing further on.
