### ISSUE TITLE
Tooltip remain on page after page is refreshed

### ISSUE THREAD

**Issue by dallenk** [Cacti/cacti#5899]
# Describe the bug

When mouseover on icons and buttons, the alt text is shown, but does not seem to clear (doesn't seem to happen every time, but pretty often)

## To Reproduce

Login, mouseover icons and buttons.   

## Expected behavior

the text should dissapear when the mouse leaves the icon/button area.

## Screenshots
![image](https://github.com/user-attachments/assets/14e0c602-7d97-4446-b525-d1a3a7256da3)

**Comment by TheWitness** [comment]
Should be fixed now.

**Comment by TheWitness** [comment]
Commit is here: 4a7b8d56ee92c452147f92ee400146d31adef855

**Comment by dallenk** [comment]
looks good here now ;)
