### ISSUE TITLE
Error variable definition on top_general_header.php

### ISSUE THREAD

**Issue by stokleyzhou** [Cacti/cacti#590]
Hi,

I tried the create a left navigation menu on my own plugin with the $user_menu and the general_header() function, but the top_general_header.php defined the $menu as the global variable, I have to change this file after i upgraded the Cacti version. please check.

I am using version 1.1.3.

**Comment by cigamit** [comment]
Resolved, please try again.  You simply need to define your $user_menu as a global in the plugin's setup.php.  Thanks for catching.
