### ISSUE TITLE
Please add the ability to select compiled RRDtool v1.9+

### ISSUE THREAD

**Issue by morganfw** [Cacti/cacti#5900]
# Feature Request

## Is your feature request related to a problem? Please describe

Not a problem, only an enhancement.

At the end of July 2024 the RRDtool stable v1.9.0 was released: https://github.com/oetiker/rrdtool-1.x/releases/tag/v1.9.0

May you check if it is safe to use compiled RRDtool v1.9.0 (https://github.com/oetiker/rrdtool-1.x/blob/master/doc/rrdbuild.pod#optimistic-build) in Cacti v1.2.x and allow to select RRDtool version 1.9+ from the dropdown menu in "Console - Settings - General" under the "Other Settings" section?

![image](https://github.com/user-attachments/assets/4253e762-62dc-450d-a711-eb7d4310520d)

## Describe the solution you'd like

If it is safe, the ability to select compiled RRDtool 1.9+ from dropdown menu

## Describe alternatives you've considered

A clear and concise description of any alternative solutions or features you've
considered.

**Comment by TheWitness** [comment]
The reason there is a plus is that I'm not sure what options are there that are new that we need to support.  Before 1.3, I'll do a review of new features to see if it's warranted.

The same is true for NetSNMP.  At version 5.8 and beyond, it really a complete tool.  Yes there are some wholesale changes from a security perspective like Diffie-Helman handshaking, but they are fairly exotic. 

With that said, I'll make a commitment to look at things.
