### ISSUE TITLE
Cacti 1.3.0 - Dev e8127b38 - Limited number or characters if you insert dash "-" symbol when trying to Duplicate a Graph Template

### ISSUE THREAD

**Issue by morganfw** [Cacti/cacti#5906]
Hi,
when trying to duplicate a Graph Template:

'Console - Templates - Graph' select a Graph then 'Duplicate' and click 'Go'

![image](https://github.com/user-attachments/assets/e7a8d7f6-b9b4-4bea-8a52-780e93255115)

if you try to insert dash symbol "-" in Title Format, the number of characters became limited

![image](https://github.com/user-attachments/assets/bd0eb9d0-3543-4ff0-84cb-277f087daaf3)

After clicking 'Continue' to save Graph Template then open duplicated template, you can insert "unlimited" characters separated by dash:

![image](https://github.com/user-attachments/assets/aec3e687-2926-4b15-936d-2c0287d16296)

**Comment by TheWitness** [comment]
It a size limit on the Title Format.  Minor fix.
