### ISSUE TITLE
[Cacti 1.1.3] Row selection in Device Automation Templates

### ISSUE THREAD

**Issue by reboot1983** [Cacti/cacti#591]
1. When I try to select a row in the automation templates module by clicking the row (not the checkbox) I get a cursor:move; I can click the row, it selects and is marked yellow, the checkbox is checked and ..... the page instantly reloads because he thinks I moved a row.

2. When I click the checkbox, the row is not marked yellow.

![schermafbeelding 2017-04-21 om 11 55 07](https://cloud.githubusercontent.com/assets/20405704/25272780/788860f6-2689-11e7-8420-4070ff6da57f.png)

**Comment by cigamit** [comment]
This is with Drag-N-Drop enabled right?

**Comment by cigamit** [comment]
Updating to jquery.tablednd.js version 0.9 fixed this.
