### ISSUE TITLE
Cacti 1.3.0 - Dev 75c85067 - Data Template is not duplicated

### ISSUE THREAD

**Issue by morganfw** [Cacti/cacti#5911]
Hi,
when I try to Duplicate a Data Source in 'Console - Templates - Data Source' by selecting Data Source to be Duplicated select 'Duplicate' action then click Go

![image](https://github.com/user-attachments/assets/69fbaca3-70d8-4059-b950-d65bea948950)

nothing happens, the page just reloads.

**Comment by TheWitness** [comment]
It's working, you likely have "Have Data Sources" checked.  So, it does not appear.  In other words, I was thinking the same thing till I checked in the database and found my error.

**Comment by morganfw** [comment]
I don't have "Has Data Sources" checked on, below a recording about the issue:


https://github.com/user-attachments/assets/653ddb90-55fd-4f25-8bad-0484d1f3b016

**Comment by morganfw** [comment]
After further investigations, even with different browsers, the Duplicate action was unblocked by clicking on "+" symbol like adding a new data template and then going back to previous page, selecting Data Template, Duplicate action and Go button.

Strange behaviour...
