### ISSUE TITLE
saw on graphs 

### ISSUE THREAD

**Issue by a-vasilishin** [Cacti/cacti#5918]
Hello! 
There is a problem with monitoring servers in remote data center. Periodically a saw appears on the graphs.
![saw on graphs](https://github.com/user-attachments/assets/86ec1004-487d-4df3-ab0d-d8407e23d8c4)

I think the problem is in the network between the data centers.
I wanted to try to switch from UDP to TCP, but I didn’t succeed.
I add 
`agentaddress udp:161,tcp:161`
to **snmpd.conf** on remote server and restart snmpd

```
# netstat -lnp | grep 161
tcp        0      0 0.0.0.0:161             0.0.0.0:*               LISTEN      48701/snmpd
udp        0      0 0.0.0.0:161             0.0.0.0:*                           48701/snmpd
```

After that I try to add tcp: to the host settings in cacti:
![cacti device conf](https://github.com/user-attachments/assets/19c354aa-f01d-4bef-9fa7-fafe2990046c)

And when saving I get an error:
System SNMP error - SNMP::get(): Could not open snmp connection: Unknown host (tcp) (Invalid argument)

![cacti error](https://github.com/user-attachments/assets/0619e2b7-2985-45dd-babe-7d12ff6a5040)

Cacti Version 1.2.26
RRDtool 1.7.1 

How to defeat a saw on graphs?
How to make cacti work on tcp?

**Comment by TheWitness** [comment]
Do you have php-snmp module installed?

**Comment by TheWitness** [comment]
Also, have you tested with snmpwalk from the command line?

**Comment by a-vasilishin** [comment]
> Do you have php-snmp module installed?

![зображення](https://github.com/user-attachments/assets/02e9f5c5-23e8-44a7-8021-277bd1b220ab)


> Also, have you tested with snmpwalk from the command line?

![зображення](https://github.com/user-attachments/assets/413321e9-999a-45e0-bf6f-3c8d4a2e436b)

**Comment by TheWitness** [comment]
Remove php-snmp and restart Apache and php-fpm.  Then try again.

**Comment by a-vasilishin** [comment]
> Remove php-snmp and restart Apache and php-fpm. Then try again.

Thank you! Works!
Maybe you also have any ideas about "saw"?

**Comment by TheWitness** [comment]
Remove php-snmp and restart Apache and php-fpm.just make sure the max values in your redfile are not causing the saw.  They should align with the ifHighSpeed on the interface.  If the ifHighSpeed is not accurate as it happens with VLAN, bond, and trunk interfaces, Cacti has a default, but you may have to run the rrdtool tune command to adjust.

**Comment by TheWitness** [comment]
I just closed.  If you have more questions on this topic, ask away.
