### ISSUE TITLE
1.1.3 Incorrectly formatted HTML 

### ISSUE THREAD

**Issue by devsys** [Cacti/cacti#592]
I have a fresh Cacti install, installed via my debian repo, then upgraded to 1.1.3. 

In Chrome 57.0.2987.133 the menu contents on the console, nectar, and clog tabs do not render. Logged in admin. Viewing the source, the menu items are there, Crome is having trouble rendering the HTML though. Firefox is able to display everything. I ran the HTML output thru a HTML linter and it pointed out, there is content below the </html> tag. I am unsure if this is the cause, but there is something wrong with the html output causing this to happen.

**Comment by cigamit** [comment]
Please upload some images and the console output from the developer tools to demonstrate the issues.  Otherwise this simply does not help.

**Comment by reboot1983** [comment]
@devsys do you mean this kind of scripts outside of the html tags (please see attached image)?
At my Chrome (same version as you have) everything seems to work fine (for Windows and Mac OS).

![cacti script outside html](https://cloud.githubusercontent.com/assets/20405704/25358874/49b4af48-2943-11e7-9a27-b47a9d514ba1.jpg)

**Comment by cigamit** [comment]
That message stuff should be before the bottom footer.  Reboot, if you find any that are dangling outside, submit a pull request.  We are planning a snap 1.1.5 on Wednesday night.  So, haste makes waste.

**Comment by reboot1983** [comment]
#618

**Comment by cigamit** [comment]
Closing.
