### ISSUE TITLE
When a plugin is disabled, unable to use GUI to enable it again

### ISSUE THREAD

**Issue by michael067** [Cacti/cacti#5927]
# Describe the bug

it's not possible to enable plugin after disabled it and not reinstall :

Correction change : 

		} elseif ($uninstall || $disable) {
			if ($disable) {
				print "NOTE: Disabling Plugin $plugin." . PHP_EOL;
				api_plugin_disable($plugin);
			}

			if ($uninstall) {
				print "NOTE: Uninstalling Plugin $plugin." . PHP_EOL;
				api_plugin_uninstall($plugin);
			}
		}

to : 

		} elseif ($uninstall || $disable || $enable) {
			if ($disable) {
				print "NOTE: Disabling Plugin $plugin." . PHP_EOL;
				api_plugin_disable($plugin);
			}

			if ($uninstall) {
				print "NOTE: Uninstalling Plugin $plugin." . PHP_EOL;
				api_plugin_uninstall($plugin);
			}

			if ($enable) {
				print "NOTE: Enabling Plugin $plugin." . PHP_EOL;
				api_plugin_enable($plugin);
			}
		}

**Comment by TheWitness** [comment]
This CLI does not look like a Cacti CLI.  Can you do a pull request an contribute it to the `develop` branch?

**Comment by TheWitness** [comment]
If not, please close this.
