### ISSUE TITLE
Text Not Displaying Correctly on Cacti Console

### ISSUE THREAD

**Issue by nakayama1869** [Cacti/cacti#5929]
■ Environment

Cacti Version: 1.2.28
PHP Version: 8.3
MariaDB Version: 10.5

■ Details
I am currently using Cacti with the above configuration, but I am facing an issue where text is not displayed correctly in the following two sections.
There are no errors logged, and I am struggling to resolve this issue.
Please help!

■Problem notation
New charts in [{0}] ({1}{2})
Cacti settings ({0}) {1}

![S__501284871_0](https://github.com/user-attachments/assets/f9d3c770-da6e-499f-9eca-154fb07c6dfa)
![S__501284873_0](https://github.com/user-attachments/assets/e12f1c4d-2f34-4548-8650-e1262c6445d8)

**Comment by TheWitness** [comment]
You need to be more specific in what it is that is wrong.

**Comment by nakayama1869** [comment]
Thank you for your comment.

As shown in the attached image, certain parts of the Cacti console are not displaying correctly.

![S__501284871_0](https://github.com/user-attachments/assets/98ba405e-3731-46e5-99f6-1bc760d9f405)

Have there been any similar incidents like this in the past?
I checked the logs but couldn’t find any relevant errors.
It’s unclear whether the issue is with the database (MariaDB) or with Cacti itself.

**Comment by TheWitness** [comment]
Japanese right?  You can fix by registering at https://translate.cacti.net. 

From there you can see the English words next to Japanese.  Note the format characters %s, %d, and %f which are replaced by certain device attributes.

You changes will be committed directly to either the 1.2.x, develop, and once you learn the interface, both at the same time.

Once complete, download the po and mo files on GitHub.

**Comment by TheWitness** [comment]
Here is a direct link.

https://translate.cacti.net/browse/cacti/core-v1-2-x/ja/

**Comment by nakayama1869** [comment]
Thank you!

I figured out how to fix it!

I really appreciate your help.

**Comment by TheWitness** [comment]
Appreciate all your contributions today as well.
