### ISSUE TITLE
Issue with data queries

### ISSUE THREAD

**Issue by marachcr36** [Cacti/cacti#5930]
# Describe the bug

When reindex the snmp data manually, the system automatically creates graphs of all the interfaces of my devices.

## To Reproduce

1. Go to 'Management'

2. Click on 'Devices'
3. Click on 'Network Element on device Description'
4. Scroll down to 'Associated Data Queries'
5. Over the line "SNMP - Interface Statistics" click to reindex SNMP data manually (green or yellow arrows)
6. automatically creates graphs of all the interfaces of my devices. The graphics created are of type "In/Out Bytes (64-bit)". This occurs using the "Generic SNMP Device" template on Huawei NE40 routers. I haven't tested with Cisco yet.

## Expected behavior

the system should execute the simple snmp query or a verbose query. 

## Screenshots

![imagen01](https://github.com/user-attachments/assets/7497b177-360b-4a66-a55d-2443b6e28d49)
![imagen02](https://github.com/user-attachments/assets/79110bde-8973-43e1-8e65-8fc301775861)
![imagen03](https://github.com/user-attachments/assets/a0e21123-515f-42e3-9479-807a8bcc1cdf)

## Desktop (please complete the following information)

- OS: Debian-Linux

- Browser firefox

- Version 1.2.26, 1.2.27, 1.2.28

## Additional context

I have tried versions 1.2.24, 1.2.26, 1.2.27 and 1.2.28. This problem does not occur on version 1.2.24. if I try with Huawei firewall E8000 it does not create graphic

**Comment by arno-st** [comment]
Can you show what is your automation rule (Console -> Automation -> Graph Rules)
It's look like one of the 2 default rules that come with Cacti.

**Comment by TheWitness** [comment]
Yea, this is a user error.  Please validate your automation rules.
