### ISSUE TITLE
Contribution by Others

### ISSUE THREAD

**Issue by dallenk** [Cacti/cacti#5950]
So, i install and blow away cacti often on a sandbox to test our networks, but sometimes forget the steps and what I need to do.  With the help of google and friends who are much smarter than me, i have a script that installs a complete and working cacti system with your choice of cmd or cactid/spine

https://github.com/dallenk/cacti-freshinstall

go easy on me.. I am not a developer and this literally took me over a month to get working.. and another couple weeks to make it work properly (for me)

it will install:
current distribution php/apache2
cacti-devel and all php dependancies
cmd poller OR cactid / spine (develop) and all dependencies
mariadb and headers

it will try to autotune mariadb with memory settings for the machine by detecting installed memory

Tested on a fresh install of Ubuntu 24.04.1 LTS and gives me a working cacti install in less than 5 minutes on a VM with a single sudo command

**Comment by dallenk** [comment]
next additions: hot sync of the database and rrd files from an old server to the new server.

**Comment by TheWitness** [comment]
Cool beans.  We have a contrib folder.  Feel free to contrib.

**Comment by TheWitness** [comment]
I have this little doohickey that I wrote that allows you to not just our rsync the files but to change from say 5 minute polling to 1 minute polling. 

And when you have 88k or 100k rrdfiles this can take a while so I integrated with a batch of scheduler such as LSF to do it via a cluster of nodes versus an individual host making all the changes.

With just a few 64 core batch servers I was able to speed up the stitching of the rrdfiles by 300X.

**Comment by TheWitness** [comment]
Feel free to post on the forums, or even contribute through a pull request.  I was a good script.  You know when you write a lot of bash, it just seem so much easier sometimes than doing PHP for system things.  For more technical, you can not beat PHP or a myriad of other more structured languages.
