### ISSUE TITLE
Fresh install error at step 7 - Default Profile

### ISSUE THREAD

**Issue by dallenk** [Cacti/cacti#5957]
http://10.52.101.252/install/install.php?data={"Step":7,"Eula":true}

fresh install:  Cacti Server v1.3.0 - Dev 87c9b17b @ 2024-12-04 18:46 - Installation Wizard

When choosing poller interval in the "Default Profile" page, selecting 1m intervals and "next" page reloads instead of advances.

sudo -u www-data git reset --hard 1a4f8c03bd1fc47200065d212cca54c0082b7bb3

Install will continue

**Comment by TheWitness** [comment]
Yea, update again.  I screwed up.  It should be fixed now.

**Comment by dallenk** [comment]
fixed, thanks!
