### ISSUE TITLE
Graph templates not showing, but total is counted

### ISSUE THREAD

**Issue by dallenk** [Cacti/cacti#5960]
Navigating to Templates / Graphs:

initial visit shows no templates found, no total.
![image](https://github.com/user-attachments/assets/98002053-03a7-4ef8-a36a-b3441060d566)

After clicking "go"
![image](https://github.com/user-attachments/assets/14dd72d5-3521-432f-be11-11eb9d8ab1cc)

shows the total, but none are displayed either.

**Comment by TheWitness** [comment]
This is a bug that I believe is corrected.  You need to reimport your packages to resolve the issue.  There is a client script called import_package.php.

Do that for each package, and the issue will be resolved.  There is another ticket opened on this already.  My hopes are that it's already fixed, but you need to restore the templates.

Have you ran the repair_database.php script recently?  Running it may have caused the problem.  I'll be confirming on my side once vertical.

**Comment by TheWitness** [comment]
It's likely that you got bit by the same bug I did.  It's not the repair process, but I'm still attempting to reproduce it.

**Comment by TheWitness** [comment]
Hrm.  I manually attempted to reproduce the problem and could not.  So, it's not the packages.  Let me make sure you have the latest updates.  Did you get any warnings in your Cacti.log?

**Comment by TheWitness** [comment]
Ope, you have an old version of the graph_templates.php.  I made updates :), and a mistake along the way.  Just update.

**Comment by TheWitness** [comment]
New version has this column...  I needed it for debugging.

![image](https://github.com/user-attachments/assets/874c58c7-48c9-4b40-a8c7-85bff9b6a72a)

**Comment by TheWitness** [comment]
Marking this one resolved and fixed.
