### ISSUE TITLE
Improve caching and syncing issues with replication

### ISSUE THREAD

**Issue by bernisys** [Cacti/cacti#5961]
# Describe the bug

When the poller replication is started, the "last sync" column is updated on the start of the script.
If the script is now terminated, the "last sync" is updated to the new timestamp, but the tables might not be replicated fully yet.
Constraint: I did the replication via the provided shell command in the .../cli/ folder , not sure if it's the same if we do it via the GUI!

Probably affects all Cacti versions up to 1.2.28 (the one we are using currently)

## To Reproduce

Choose a poller with many devices and start the sync process using the CLI script.
Break out of the script by pressing Ctrl-C.
Check the "Data Collectors" page immediately after that -> the "Last Sync" is updated already, even if the process is not finalized.

## Expected behavior

The "Last Sync" entry should be updated at the end of the replication process, not at the beginning.

**Comment by TheWitness** [comment]
Let me verify that.  I think if we spawn a process to do that, we can make that change.

**Comment by TheWitness** [comment]
Digging in I found other issues.

**Comment by TheWitness** [comment]
Fixed now.
