### ISSUE TITLE
CACTI 1.3 [Dev]: global_arrays.php, $domain_types has a "-" that causes "ERROR PHP WARNING: Undefined array key 0 in file: D:\cacti\apache\htdocs\cacti\user_domains.php on line: 716" when configuring AD domain.

### ISSUE THREAD

**Issue by MSS970** [Cacti/cacti#5962]
global_arrays.php line 942:
$domain_types = array(
	DOMAIN_TYPE_LDAP => __('LDAP'),-
	DOMAIN_TYPE_AD   => __('Active Directory')
);

as per the above, line 943 as a "-" which causes a problem when configuring AD domain.

ERROR PHP WARNING: Undefined array key 0 in file: D:\cacti\apache\htdocs\cacti\user_domains.php on line: 716

Solution:
remove the "-" from line 943.

**Comment by TheWitness** [comment]
Thanks for reporting!
