### ISSUE TITLE
Add a method to mark missing Data in all graphs globally

### ISSUE THREAD

**Issue by bernisys** [Cacti/cacti#5971]
# Feature Request

## Is your feature request related to a problem? Please describe

In all our templates i have added a "missing data" section that is simply creating an overlay area in a yellow-ish color, that marks sections where the data source has NaN fed into the RRD. I had to add it to all templates one by one, which is quite a cumbersome activity, specially if you have lots of graph templates (and i am pretty sure i missed some myself...)

## Describe the solution you'd like

This should be a global function and not part of a specific template, so you don't have to fiddle with all your templates to add this kind of quite important information. Also then you could define the color globally and the legend would always look identically.

If a graph contains more than one data row, then it should summarize in the legend, which DS contain streaks of NaN data.

Actually, thinking deeper about it, it would be great to have some kind of "overlay-templates" where you can define some kind of templates that you can overlay into all graphs, like:
  * the NaN markers
  * adding IP address information in the legend
  * ... you name it

Also you could add a way to suppress global items in specific graph templates, in case the info would be confusing. In this case it would be nice to have an overview in the graph templates page, which templates have any suppressions enabled, an icon (re-use the red/green LED-like icon from templates list or something like that) with on-hover info would be sufficient.

## Additional context

As discussed in the call.

**Comment by bernisys** [comment]
For the NaN area i use this approach to mark the unknown data:

1. add a color -> Name: "Unknown Data" / Hex Value: "ffffc0"
2. add a CDEF -> Name: "Unknown Data" / cdef=CURRENT_DATA_SOURCE,UN,INF,0,IF
3. in all graphs i added a section (that only covers the last used graph, based on the cdef)

Graph section:
 * Data Template: (the one you want to "monitor" for NaN data)
 * Type: Area
 * Data Source: (the one you want to "monitor" for NaN data)
 * Color: "Unknown Data" (as defined above)
 * Opacity: 100% (but i think less is better, though the base color needs to be edited then
 * Consolidation: AVERAGE
 * CDEF: "Unknown Data" (as defined above)
 * VDEF: None
 * Shift Data: off
 * Text-Format: "no data"
 * Insert hard return: On

**Comment by TheWitness** [comment]
This is done now.  Much simpler when you think about it.
