### ISSUE TITLE
Cacti 1.3.0 - Dev 21195d02 - "Template/Package Copyright" Tooltip wrong description

### ISSUE THREAD

**Issue by morganfw** [Cacti/cacti#5980]
`Console > Settings > General` under `Packaging Defaults` the tooltip have wrong description

![image](https://github.com/user-attachments/assets/c2bae24b-ae36-454b-9513-a17e8e8c3451)

**Comment by TheWitness** [comment]
Thanks for catching.  Half awake while honing this thing out.  More changes coming.

**Comment by TheWitness** [comment]
The next part is to allow archival and restore from Device Templates page.
