### ISSUE TITLE
[QA 1.3] - When you Logout Everywhere what should happend with TFA Tokens

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#6000]
# Describe the bug

This is more of a question than a bug.  Should logging out invalidate your 2FA token.  I don't think it should as that token my be used by multiple systems.  You should definitely be logged out everywhere though.

**Comment by TheWitness** [comment]
@netniV, what are your thoughts?

**Comment by netniV** [comment]
Depends how you are defining 2FA token. If you are referring to they stored against a user, no because that's what generates the one time codes to be able to login. 

If you are talking about as part of the login process, it should always be asked for if setup.

**Comment by TheWitness** [comment]
Okay, closing this one then.  The logout everywhere is strictly associated with Authentication Cookie support.
