### ISSUE TITLE
Extend SYSTEM STATS log entry

### ISSUE THREAD

**Issue by xmacan** [Cacti/cacti#6001]
Poller logs information about errors and warning like:
CMDPHP ERROR: Output from local_data_id 35606, for RRDfile DS Name 'client_queue', is invalid. It outputs was : ''. Please check your script or data input method for errors
WARNING: Invalid Response, Device[test3389] HT[1] DS[test3389 - CPU Usage - System] dsname: cpu_system, oid: .1.3.6.1.4.1.2021.11.52.0, value:

It would be great have in the stats log record number of warnings end errors, example:
2024-12-15 20:26:04 - SYSTEM STATS: Time:64.2557 Method:spine Processes:2 Threads:10 Hosts:425 HostsPerProcess:213 DataSources:19034 RRDsProcessed:0 **Warning:15 Errors:2**

We can use it for the dashboard or create a new Cacti graph. This could help identify a problem faster, such as an empty graph or U/NAN.

**Comment by TheWitness** [comment]
Might be a spine enhancement as well.

**Comment by xmacan** [comment]
The best way is have it for both pollers

**Comment by TheWitness** [comment]
Right.
