### ISSUE TITLE
1.3 - QA - The Button to delete a remote poller is missing 

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#6006]
I have checked the poller stats view and the individual poller view both have no delete option

![Screenshot from 2024-12-16 12-01-35](https://github.com/user-attachments/assets/712afc0b-444b-4c41-9f04-02c7e61574ce)

![Screenshot from 2024-12-16 12-02-23](https://github.com/user-attachments/assets/520acb0a-221b-4bbf-a030-2b52f03280f8)

**Comment by TheWitness** [comment]
The questions is was it ever there?

**Comment by bmfmancini** [comment]
for sure on 1.2.x it was in the actions menu 
Mark for 1.3 moved it to the poller edit page 
https://github.com/Cacti/cacti/issues/3677

**Comment by TheWitness** [comment]
Is it still there in the edit page?

**Comment by bmfmancini** [comment]
No it's not there anymore

**Comment by TheWitness** [comment]
Okay.

**Comment by TheWitness** [comment]
This one is messy.  I have to think about it.

**Comment by TheWitness** [comment]
Does not look too bad.

**Comment by TheWitness** [comment]
Okay, I think I have it fixed.  Please test...

**Comment by bmfmancini** [comment]
I still dont see the delete button

**Comment by TheWitness** [comment]
Fixed now.  Please test.
