### ISSUE TITLE
1.3 Dev fresh install WEBUI

### ISSUE THREAD

**Issue by didimau** [Cacti/cacti#6009]
Have after fresh install a WEBUI Warning that design files are missing ...

"WEBUI WARNING: Key Cacti Include File "all.css" missing. Please locate and replace this file as we checked in "/usr/share/cacti/siteinclude/fa/css/" "

Even after creating a "siteinclude" folder with all files, it happens .
Besides the warning, i cant see any webui problems.

and great work to all ! love to see 1.3 in full beauty

**Comment by TheWitness** [comment]
Looks like there is a slash missing in the path.  How did you install?

**Comment by TheWitness** [comment]
Develop is undergoing a lot of change right now.  So buckle up.  Just another two weeks. With next week off for the holidays.

**Comment by didimau** [comment]
i installed 1.2.28 with spine through a installscript in new vm with ubuntu 24.04LTS.
after that i copied the new 1.3 dev over it, changed some permissions and mariadb settings as installergui told me ...
everything looked good, except of the webui warning ... when i tried our custom theme in 1.3, i copied all the includes to the "siteinclude" folder to check it and figured out thats not the problem ... there is a path problem with the backslash somewhere else

till now i had no time to dig more into it .. but next week im building all new in this VM instance and test everything out.
ill keep u informed if i find something

**Comment by TheWitness** [comment]
We are not having this issue with clean installs, I suspect that it's something on your side.  But we appreciate any upgrade testing that you do.  BTW, when you upgrade, it's a good practice to clear your browser cache.  The browser manufacturers keep making it hard for us to force change.  We've done a number of things to trick the browsers to clear their cache over the years, but every time we think we have things addressed, they find a way to work around our workarounds.

So, I'm going to go ahead and close this for now.
