### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by jpobeda** [Cacti/cacti#601]
Hi there,

I've been testing the translation I've been working on and found a lot of strings that don't get translated and also some other strings that are not present to be translated.

How should I report this? See the attached screenshot.

![translation issues found](https://cloud.githubusercontent.com/assets/13456559/25308917/c1a7d150-2813-11e7-9b57-2a6844228992.png)

I haven't downloaded the latest cacti.pot so I'm working on the one I downloaded a couple of months ago. Not sure if it's got updated anyway.

**Comment by cigamit** [comment]
Resolved.  Thanks for catching this.  I'm sure there will be more.  Keep us posted.

**Comment by jpobeda** [comment]
Should I open new issues or add comments to this one?

**Comment by cigamit** [comment]
No, open new issues.  We are planning another release Wednesday night, so if (and more likely when), you find another issue.  Log it ASAP.
