### ISSUE TITLE
CACTI Dev 1.30, unable to create a new data collector, the "+" sign is not available

### ISSUE THREAD

**Issue by MSS970** [Cacti/cacti#6012]
CACTI Dev 1.30
OS: Windows 2019

In CACTI Dev 1.30, I am not able to add/create any new data collector, the "+" sign is not available, is there any configuration to enable me to add new poller/data collectors?

![cacti-main-poller](https://github.com/user-attachments/assets/68be0c69-d894-425b-952f-b8af52053abe)

**Comment by TheWitness** [comment]
This is how it works.  The data collector is created when you install it, not ahead of time.

**Comment by MSS970** [comment]
Do you mean that CACTI supports only one Data Collector?

**Comment by TheWitness** [comment]
No, you add data collectors by doing a cacti install somewhere else and pointing it back to the main collector as a part of the new install.  See the Video that @bmfmancini made on doing Remote Data Collector installs.

**Comment by MSS970** [comment]
Thank you for the clarification, so CACTI main installation will have on main data collector and every remote installation with 1 data collector can be pointed to the main data collector.
So my understanding is that CACTI supports one data collector per installation.
Is this correct?

**Comment by TheWitness** [comment]
There are some installs with over 40.

**Comment by MSS970** [comment]
Noted.
Much appreciated @TheWitness
