### ISSUE TITLE
[QA 1.3] - When cacti is set to lockout mode and admin surfs away from page admin is locked out

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#6017]
If you set cacti to maintenance mode as and admin and you surf away from the page or your browser crashes you will not be able to get back to the UI until the timer is lapsed

I think its better to simply deny any user except admins to login to cacti during the maintenance period

**Comment by TheWitness** [comment]
Well, you don't get locked out unless you are browsing from another Window or browser.  The lockout is tied to a session.

**Comment by seanmancini** [comment]
but say if the admin accidentally closes a window or the browser crashes then your cooked

**Comment by TheWitness** [comment]
For 30 minutes by default.  I've made a light update to this feature.  Going to close this one now.
