### ISSUE TITLE
[develop] right click "open in new tab"  redirects to login screen

### ISSUE THREAD

**Issue by dallenk** [Cacti/cacti#6018]
# Describe the bug

possibly a session issue?  When right clicking any menu item like weathermap / logs ect, the user is sent to a login screen to authenticate again.

## To Reproduce

1: Authenticate as a user
2: right click on a tab (Uptime/Weathermap/ect)  Select open in new tab
3: User is sent to a login screen.

I can open in new tab on fbcac6e7 but not b0b3fb7d

**Comment by TheWitness** [comment]
This is a new feature.  Each tab gets it's own login session.

**Comment by dallenk** [comment]
can I object to that change?  :)   I don't see that as a feature at all.    Maybe have an option to 'force auth on new tab' or allow existing sessions to work?

**Comment by TheWitness** [comment]
What type of login realm are you using?

**Comment by dallenk** [comment]
internal only for login.  Just curious, was there a security concern or a cross-site vulnerability for this change?

**Comment by TheWitness** [comment]
No, but if you are performing administrative functions in one tab, you don't want the second tab locking up.  The way around this is to enable Authentication Cookies.

**Comment by TheWitness** [comment]
![image](https://github.com/user-attachments/assets/6ae0dc0e-2f9a-4a4d-9f5b-52ec81fdbc23)

**Comment by dallenk** [comment]
> No, but if you are performing administrative functions in one tab, you don't want the second tab locking up. The way around this is to enable Authentication Cookies.

hmmm...  didn't consider that actually.  I'll play with it more and perhaps retract my objection another day :)

**Comment by TheWitness** [comment]
Okay, I'll close then for now.  We will certainly have a lot of comments on this and will note it in the release notes.
