### ISSUE TITLE
[1.3] - Session times out after any timer refresh

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#6019]
In the technical support page the user is able to view database queries
Upon refresh you will get punted to the login screen due to session timed out

**Comment by bmfmancini** [comment]
Hmm now its seems any refresh timer ends with a session time out 
Just experienced it in log

**Comment by dallenk** [comment]
I was just adding this one.   also happens when monitoring logs and setting an automatic refresh.

**Comment by bmfmancini** [comment]
Yea no console errors or PHP errors seen yet
