### ISSUE TITLE
[Cacti 1.1.4 - develop] Automation discovery : device rules & Tree creation issues

### ISSUE THREAD

**Issue by jhonnyx82** [Cacti/cacti#602]
This is re-queue for couple of items from issue #589 

- In 1.1.3 automation device rules using **System Name Match** worked correctly, in 1.1.4 develop it seems to not work at all (tried different expressions that worked in 1.1.3), also in the device automation templates list, "System name match" column shows no data even when populated for a rule (cosmetical issue that was also in 1.1.3 as I just noticed)

- When a device is discovered and added correctly to cacti device list, the Tree rules matches correctly but does not automatically add a device or graph entry under a selected (existing) tree or sub tree. It works only by applying the automation rules manually to the discovered devices in the devices list menu

Test was performed with last develop branch

Here some screenshot of my parameters : 
System name match is populated:
![image](https://cloud.githubusercontent.com/assets/26431888/25308960/989aaa60-27c0-11e7-9c5a-f6a92f966612.png)

But ignored in the device rules list and during discoveries : 
![image](https://cloud.githubusercontent.com/assets/26431888/25308982/da6a6502-27c0-11e7-863f-5888b7505806.png)

These are the parameters of the Tree Rule Selection that works only manually.
Interesting is that "Matching devices" list is populated (were discovered previously but using System Description Match, NOT System Name Match).
Please note that Tree and subtree are all existing (and insertion work manually).
![image](https://cloud.githubusercontent.com/assets/26431888/25309008/7263cfe2-27c1-11e7-85e4-d7f83155ef4f.png)

**Comment by cigamit** [comment]
First issue is now fixed.  I'm still perplexed on the second tree issue.

**Comment by jhonnyx82** [comment]
I haven't tried yet your last fix for the first item, but I can tell that I also ran another 2 tests just now for the tree creation/insertion with some changes from my initial test, but without success anyway: 

Info : All the folder structure is already created in my deployment scenario but here I tested with and without the selected subfolder. Also each time the test was performed the discovered devices were deleted to test a fresh discovery of the devices.

- Test 1 : I added the **Tree Creation Criteria** (Fixed String) when the Sub Tree is already existing (so just insertion of discovered devices and no tree creation (as it is already in the tree structure) : Fail, devices are discovered but only manually applying the automation rules from the device list makes possible to insert the devices

- Test 2: I deleted the "Access Switches" sub tree and I kept the **Tree Creation Criteria** in: Fail, devices are still discovered but again only by manually applying the automation rule in the device list menu actually creates now the subtree and insert the devices into that created "Access Switches" subtree.

I feel the problem looks to be not on the way the Tree rules works but when they get triggered, so to say that the the Tree Rules looks to be not called when a device is discovered and inserted into the device list.

Also consider that the automation options are enabled in the Settings TAB.

Let me give you here some screenshots:
![image](https://cloud.githubusercontent.com/assets/26431888/25313452/6fdfb786-282f-11e7-98e4-914bc9c958fc.png)



**_Test 1_**

![image](https://cloud.githubusercontent.com/assets/26431888/25313469/b38dc342-282f-11e7-8025-dae7457ac9d3.png)


![image](https://cloud.githubusercontent.com/assets/26431888/25313459/88872058-282f-11e7-8608-22c8a58f9caf.png)


**_Test 2_**

![image](https://cloud.githubusercontent.com/assets/26431888/25313477/c4a1f48c-282f-11e7-963c-f5a400fbda10.png)

![image](https://cloud.githubusercontent.com/assets/26431888/25313487/e3931aba-282f-11e7-9d5d-119c582bab11.png)

**Comment by cigamit** [comment]
Try again.  I moved the manual scanning functions into the automation loop, so the tree's should be created now.

**Comment by jhonnyx82** [comment]
Hi,

I downloaded the latest develop branch and unfortunately the situation got worse, let me recap

- Scheduled discovery does not start at the set time
- when clicking on "Now" during time selection for a scheduled discovery it accounts for browser client time rather than system time (my server is in UTC but returned CEST time)
- Device rules **System Description and System name** match does not work at all (they did in 1.1.3) and in the Device Automation Templates list the System name Match is still empty even if populated
- Now even applying manually the **Tree Rules** for devices discovered and added manually, does not work

**Comment by cigamit** [comment]
Yes, that was pretty crappy of me.  Just updated lib/api_automation.php.  Should discover and add now.  I moved the whole 'manual' discovery thing to a function.  So, what is done after discovery is 'identical' to what is done when manually running it.  So, that should work.

**Comment by jhonnyx82** [comment]
Thanks for the fix, now the manual discovery works fine but the scheduled discovery doesn't start.
Still it stands the problem for the tree insertion.

From what I can see, even in the Tree Rules "Matching devices" are not populated instantly.

**Comment by cigamit** [comment]
That very interesting, do your tree rules leverage any of the system mibs?

**Comment by jhonnyx82** [comment]
Let me paste here the tree rules:

Only one is active (New Device)

![image](https://cloud.githubusercontent.com/assets/26431888/25316813/773f2f28-286d-11e7-994c-52a73c12df03.png)


![image](https://cloud.githubusercontent.com/assets/26431888/25316820/8ea670a4-286d-11e7-9f01-efaf6eff1f71.png)

**Comment by cigamit** [comment]
Yea, that's it.  Committing shortly.  Thanks for staying on this over the weekend.

**Comment by cigamit** [comment]
Closed a little pre-maturely.  But fix is in now.

**Comment by jhonnyx82** [comment]
Thanks, will try and let you know later or tomorrow.

Appreciate YOU staying on this over the weekend :)

**Comment by jhonnyx82** [comment]
Hi,

Wanted to tell you that all works fine now :+1: 

a Big thank you
