### ISSUE TITLE
[1.3 QA] Incorrect stats if number of devices is 0

### ISSUE THREAD

**Issue by xmacan** [Cacti/cacti#6031]
SYSTEM STATS: Time:0.0031 Method:cmd.php Processes:1 Threads:1 **Hosts:-1 HostsPerProcess:-1** DataSources:0 RRDsProcessed:0 ErrorHosts:0 TotalErrors:0

It seems that the spine has the same issue.

**Comment by TheWitness** [comment]
Hosts -1.  Odd.
