### ISSUE TITLE
[develop]  graph selection from tree displayed many mutiples of times

### ISSUE THREAD

**Issue by dallenk** [Cacti/cacti#6035]
# Describe the bug
`b02c87cdc (HEAD -> v1.3, origin/develop, origin/HEAD) typos`

When choosing graphs to display in a tree, the available graphs are displayed many multiples of times, and the naming is weird.  I can't see any common pattern but perhaps the same graphs displayed multiplied by the amount of ports on the device??   Note when mouseover, all the graphs of the same name are highlighted.

## To Reproduce

1. Go to Console > Graph Trees > edit a tree

2. Select a site, filter by a device (i my case 100F) 

3. See the graph names in the list.  

## Expected behavior

A list of each graph associated with the selected device.

## Screenshots
![image](https://github.com/user-attachments/assets/537c8023-9f73-4383-8db5-5c83ade9f283)

**Comment by TheWitness** [comment]
@dallenk, thanks for reporting.  Should be fixed now.

**Comment by dallenk** [comment]
it blows me away how you write code like this as quick as you do.

**Comment by TheWitness** [comment]
They used to call me Iron Man in China.  Very flattering.
