### ISSUE TITLE
Unexpected Backtrace with Graph Filters Search for *

### ISSUE THREAD

**Issue by reubenfarrelly** [Cacti/cacti#604]
Looks like something isn't being escaped correctly...
If I go into the Graphs Tab, select a device, and then in Graph Filters so a Search of *router* (or anything else that starts with an asterisk) I get this output in the browser:

Validation error for variable rfilter, with value of "*router", and error:Compilation failed: nothing to repeat at offset 0. See backtrace below for more details.
(/graph_view.php: 240 html_validate_tree_vars)(/lib/html_tree.php: 533 validate_store_request_vars)(/lib/html_utility.php: 636 die_html_input_error)(/lib/html_validate.php: 60 cacti_debug_backtrace)

**Comment by cigamit** [comment]
We don't allow that character.  If you are looking for a wildcard, use the percent, though that would only be between words.

**Comment by cigamit** [comment]
I'm not sure *router is a valid regex anyway.

**Comment by reubenfarrelly** [comment]
I can't think of a valid regex either. In the past I have run Cacti installations where a filtered view was made visible to end customers - and I wouldn't expect them to know this.  I think the best way to handle this would be to print a warning that the * character is not valid in this context and has been ignored, rather than an ugly looking backtrace which looks more like a bug.

**Comment by cigamit** [comment]
Yea, true.  Let me see about that...

**Comment by cigamit** [comment]
Should be better now.  We just clear the filter when the regex is invalid.  Right now, there won't be an error message.

**Comment by reubenfarrelly** [comment]
Yep - looks better in the GUI now.

This is still logged in cacti.log though:

2017-04-23 22:56:18 - ERROR PHP WARNING: preg_match(): Compilation failed: nothing to repeat at offset 0 in file: /var/www/cacti.reub.net/htdocs/lib/html_utility.php  on line: 742
2017-04-23 22:56:18 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 240 html_validate_tree_vars)(/lib/html_tree.php: 533 validate_store_request_vars)(/lib/html_utility.php: 595 validate_is_regex)(/lib/html_utility.php: 742 preg_match)(CactiErrorHandler)(/lib/functions.php: 4299 cacti_debug_backtrace)

**Comment by cigamit** [comment]
Should be much better now.
