### ISSUE TITLE
Feature Request: use <path_php_binary> in data input methods

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#606]
I saw some discussion about this from a few years ago, and it wasn't clear what ended up happening. But I tried to use <path_php_binary> in a data input method today, and didn't have any luck. This would be very useful to have, but is there still a security concern in doing so?

**Comment by cigamit** [comment]
Resolved, please take a copy of the development branch and re-test and provide feedback.

**Comment by eschoeller** [comment]
Works perfectly, many thanks!
