### ISSUE TITLE
draw_menu function enhancement

### ISSUE THREAD

**Issue by stokleyzhou** [Cacti/cacti#607]
It would be good to add the feature for draw_menu function to fetch the HTTP request as the 'selected' CSS style.

I have a $user_menu defined as below:

$user_menu = array(
    __('Main') => array(
        'plugins/lum/lum.php?action=show_dashboard'   => __('Dashboard')
        ),   
    __('Usage') => array(
        'plugins/lum/lum.php?action=show_usage_daily'          => __('Daily Usage'),
        'plugins/lum/lum.php?action=show_usage_monthly'    => __('Monthly Usage'),
        )
);

When i click one of the menu item, all left navigation menu items have added the 'selected' CSS style since the URL are the same page.

**Comment by cigamit** [comment]
Please update lib/html.php.  This requires that the 'action' and basename be the same.  Let me know if it's working.

**Comment by stokleyzhou** [comment]
Hi Cigamit,

Thanks for your update.

Unfortunately, it's not working due to the 'strpos($url_array['query'], 'action=' . $url_parts['action'])' just compare the HTTP request not the $item_sub_url.

The $url_parts array just stored the $url_array['query'], I think we need to parse the URL of the menu item for $url_parts.

Thanks,
Stokley

**Comment by cigamit** [comment]
Tested as working now.  Please note that when using this paradigm, all entries must either have an action or an id.

**Comment by stokleyzhou** [comment]
Hi Cigamit,

I am using the loadPageNoHeader function to redirect the url, but the layout.js file added selected class for all menu items, the loadPageNoHeader should be changed as loadPage function.

And for the menu item with ?action/?id, I may pass other variables for HTTP request as below:
loadPageNoHeader(lum.php?action=show_usage_monthly&feature=111&user=admin);

Can you please update the layout.js for this case?

I am currently changed the layout.js as below, it's working fine.

        var hrefParts = href.split('?');
        pageName = basename(hrefParts[0]);
        var hrefId = href.split('&')[0];

        if (pageName != '') {
            if ($('#menu').find("a[href*='"+hrefId+"']").length > 0) { 
                $('#menu').find('.pic').removeClass('selected');
                $('#menu').find("a[href*='"+hrefId+"']").addClass('selected');
            }else{ 
                $('#menu').find('.pic').removeClass('selected');
                $('#menu').find("a[href*='/"+pageName+"']").addClass('selected');
            }    
        }

**Comment by cigamit** [comment]
Please create a pull request.
