### ISSUE TITLE
Spaces adjacent to double quotes are eliminated during data input method import

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#608]
I found that when a data input method is imported the spaces that once existed between double quotes are eliminated. They appear to be properly exported to the xml file, but are removed during the (re-)import process.

Here is an example:
Table: data_input, Column: input_string, New Value: '/usr/local/php/bin/php -q <path_cacti>/scripts/query_apc_rack_pdu.php current <hostname> <snmp_community> <snmp_version> <snmp_port> <snmp_timeout>"<snmp_username>""<snmp_password>""<snmp_auth_protocol>""<snmp_priv_passphrase>""<snmp_priv_protocol>"', Old Value: '/usr/local/php/bin/php -q <path_cacti>/scripts/query_apc_rack_pdu.php current <hostname> <snmp_community> <snmp_version> <snmp_port> <snmp_timeout> "<snmp_username>" "<snmp_password>" "<snmp_auth_protocol>" "<snmp_priv_passphrase>" "<snmp_priv_protocol>"'

**Comment by cigamit** [comment]
Hmm, that is very odd.  Thanks for reporting.

**Comment by cigamit** [comment]
Resolved, please take a copy of the development branch and re-test and provide feedback.
