### ISSUE TITLE
"Change Graph Template" action not availbale on graphs screen

### ISSUE THREAD

**Issue by dethmetaljeff** [Cacti/cacti#610]
In the graphs.php screen, the "Change Graph Template" action isn't showing up.  Looks like the logic is to check that a template_id is being specified as a filter but the way it's implemented doesn't work for non-numeric tamplate_id's...in graphs.php:

````
if (get_nfilter_request_var('template_id') > 0) {
        $graph_actions += array(
                2  => __('Change Graph Template'),
        );
}
````

but my template_id's are non-numeric:

````
<option value='cg_132'>Linux - UDP Input Errors</option>
<option value='cg_335'>PING - Advanced Ping</option>
<option value='dq_56'>Sentry CDU - Current</option>
<option value='cg_110'>Sentry CDU - Current - 30Amp</option>
<option value='dq_91'>Sentry CDU - Humidity</option>
````

so this is never true.  Perhaps we want != 0 instead?

**Comment by cigamit** [comment]
Good point.  Not sure how that happened.

**Comment by cigamit** [comment]
Resolved, thanks!
