### ISSUE TITLE
Duplicate Data Input Methods

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#614]
I believe it would be extremely useful to have an option to duplicate data input methods, similar to how you can duplicate so many other things in Cacti ... many thanks!

**Comment by jhonnyx82** [comment]
Please also Data queries!!! :)

**Comment by cigamit** [comment]
x82,. tell me why?  Its important.

**Comment by eschoeller** [comment]
I just looked through most of the data queries I have created in the past. I do see some instances where I would have benefited from having the ability to duplicate an existing data query. There are a few of these out there where I ended up needing to make 2-6 different data queries which were extremely similar to one another - save for perhaps using a different XML file. It may seem to defeat the purpose of using a data query in the first place, but it was necessary given the situations. 
If it's relatively easy to implement the functionality to duplicate a data query what harm would it do?
![image](https://cloud.githubusercontent.com/assets/12864741/25550487/af281a2c-2c36-11e7-9f1f-7c650bb4a1e8.png)
![image](https://cloud.githubusercontent.com/assets/12864741/25550497/c08b34de-2c36-11e7-831a-ad98954b94cf.png)

**Comment by jhonnyx82** [comment]
> x82,. tell me why? Its important.

In my case I am building up device templates that refers at different data profiles (30 sec - 1 min - 5 min).
This is to simplify the operations within my team or people that are less inclined to understand cacti's architecture. For them I would just have a "Cisco Router 30 secs" or "Cisco Router 1 min" template, this is why replicating Data queries may save me some time.

PS : I know that it's possible to select a specific data profile for each data source, making things even easier for me, but as I said, I need to build and let other people maintain it as they go.

But any customization for a specific purpose of a certain preset data query or template would benefit of a duplication function.

Thanks for looking into this

**Comment by cigamit** [comment]
Okay, but when duplicating a Data Query, what do you expect to be duplicated?  Does it cascade, to the Graph Templates and Data Template, or is it just the Data Query, the Graph Template associations, and Suggested Values?

**Comment by eschoeller** [comment]
I would say just the data query including the graph template associations and suggested values. It doesn't do anything to mess with actual graph templates and data templates downstream. I believe this is what I would expect to happen if I chose to duplicate a data query.

**Comment by cigamit** [comment]
I just discovered that if you make the Data Source Profile as per Data Source in the Data Source Template, that you will be prompted at create time for the Data Source Profile to use.  So, the only thing that is really required here is the ability to duplicate a Data Input method.  Otherwise, just enable the ability to specify the Data Source Profile at the Data Template level.  It works for normal Graph Templates and Data Queries.

**Comment by cigamit** [comment]
This is resolved now.  Thanks for everyone's patience.
