### ISSUE TITLE
Strange behavior with saving data input methods

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#615]
I have had this occur twice while making minor changes to a data input method. This has occurred after saving the input method when changing the command line and the Name. For some reason text gets chopped off the end of the data input method command line:

![image](https://cloud.githubusercontent.com/assets/12864741/25368881/22ebae44-293d-11e7-81c9-67fb9b24db9c.png)

I am trying to figure out how to reproduce it.

**Comment by cigamit** [comment]
That is due to the column width.  You can do this short term:
`mysql cacti
alter table data_input modify column input_string varchar(512) default null;`

**Comment by cigamit** [comment]
Resolved.
