### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by jpobeda** [Cacti/cacti#616]
Hi there,

I reported on #601 some issues and one of those hasn't been fixed.

Please also see that "All". Can't find it or it's missing.

![translation issue 616](https://cloud.githubusercontent.com/assets/13456559/25369543/c6ccf072-29d8-11e7-9627-7c1fdcd8a443.png)

Couldn't find any of these ones:

![translation issue 616_2](https://cloud.githubusercontent.com/assets/13456559/25371292/1cb8c136-29e4-11e7-88d7-5e6de57f1209.png)

Also check these ones

![translation issue 616_3](https://cloud.githubusercontent.com/assets/13456559/25371394/b7e59616-29e4-11e7-919c-9ebf84e8b525.png)

![translation issue 616_4](https://cloud.githubusercontent.com/assets/13456559/25371698/1062781c-29e6-11e7-9880-a7253a8cbd59.png)

Can you also please advise the meaning of "nuralize"?
There are:

> Nuralize: referenced by .../plugins/package/package.php:459
> Nuralize Templates: referenced by .../plugins/package/package.php:463

**Comment by cigamit** [comment]
* The "All 2 blah" is i18n'd in lib/html.php line 404, so your po file must be out of date.  
* Nuralize is a term from Men In Black.  That option is not used presently, and will be removed.  So no worries about that one.
* Data Source List is i18n'd in host.php line 624.  So, same issue as issue 1.
* Choose an action  is i18n'd in lib/html.php line 1165.  So, again same issue as 1.

On the help menu part, I have to contact Andi on that one.  So, I'll leave this open for that reason.  I will update the pot file this morning.

**Comment by reboot1983** [comment]
I've got a branch with [Dutch translations](https://github.com/reboot1983/cacti/tree/DutchTranslations) for Cacti.
I've just updated your committed cacti.pot into my branch and updated the Dutch.pot too. I'm at about 20% right now (1125 of 5551 rows are translated). Should I create a PR for this so others can help? Or should I keep this to my own branch? It's sometimes quite hard to find the correct translations.

**Comment by browniebraun** [comment]
Due to that reason I would suggest to create a PR.

Regards
-Andi

**Comment by jpobeda** [comment]
@cigamit you mean my .po translation file? or the cacti.pot one? Because I merged the .pot from 1.1.4 to my .po translation to test if issues from #601 were fixed.

I'm about 67% some plugins are a pain in the ass to translate <.<

**Comment by jpobeda** [comment]
@cigamit regarding the 'All' I found it, its translated but cacti is not taking it.

Choose an action, same thing.
Data Source List, same thing.
Device Monitoring Settings, same thing. This one in fact, is lower case but the html is changing it uper.

Can you double check those?

**Comment by cigamit** [comment]
That's real odd.  I'm going to defer to Andi who is coming back from vacation.  Andi, can you please investigate?

**Comment by browniebraun** [comment]
I've  just tried to verify that by updating my German language file referencing those items, but it works without issues. Did you probably not update / replace the related .mo? Cacti will only take those binary files into account.
Regards
-Andi

**Comment by browniebraun** [comment]
Strings within the dropdown menu that only the paper-plane theme contains can not be translated at the moment, because those entries will be generated at the client side with JS. But I will change that to support i18n for them as well.

**Comment by jpobeda** [comment]
I'm suspecting the file got broken/poisoned somehow when I merged them. I found strings that didn't match the previous translation quite a few, don't how that works for you..Also remember my translation dropped 2% after the merge.

But I'm updating the .mo every time to test the changes and I can see them ok, but those are not ok. And I'm also working with the 1.1.4 version of cacti so I guess I'm not missing the fixed code of cacti either.

Any suggestion on what to check?

mmm

**Comment by cigamit** [comment]
I've just updated the cacti.pot file again.  Our script had not been updated to ignore the plugin directories.  Hope it's not too much of a mess.

**Comment by jpobeda** [comment]
So the current won't have the plugins right? It has 3307 entries.

I'll work it in a different copy, merge them and see how it goes. 

Is it possible to generate different file(s) for the plugins and merge it to cacti.pot on demand? May be easier to work the translation.

**Comment by browniebraun** [comment]
The POT of Cacti should never keep any plugin stuff.
I wrote it in that way that plugins need to have their own domain. That means plugins will stay completely separately by having their own POT, POs and MOs. Cacti will automatically load, referring to the selected language, all matching MOs. Their is no merge against Cacti POT itself necessary.
Unfortunately we forgot to put the domain information in while doing the i18n for the plugins. This is necessary for GETTEXT to know in which "area" it should search the translation first. I will update all plugins step by step to take care of it, but this will not change their translation file itself.

Regards
-Andi

**Comment by jpobeda** [comment]
Well, sounds better. I'll see how I reuse those translation anyway but happy to finally finish the cacti one.

So in terms of this issue #616, close it and open a new if needed? lost the track really.

**Comment by browniebraun** [comment]
Totally agree. Thanks for all the effort you are investing to make Cacti better!
