### ISSUE TITLE
The poller_data_template_field_mappings table is filling with irrelevant/inaccurate data

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#620]
I'm in the process of creating some new templates, and throughout this process I've been tweaking a few aspects of my data sources along the way. Most notably, I have been changing the internal data source names. When I do this, obviously I understand it impacts the current data sources and graph templates. But after blowing away existing data sources and re-creating the graph templates, I'm still running into some strange problems, which are only resolved by blowing away the entire data source template and starting completely over. 
What I have found is that when I change an internal data source name in a data source template, it is reflected in the data_template_rrd table, but the poller_data_template_field_mappings table still has some remnants of the old internal data source name which is borking things up. 
Most notably, this is causing a problem:

```
+------------------+---------------------+---------------------+---------------------+
| data_template_id | data_name           | data_source_names   | last_updated        |
+------------------+---------------------+---------------------+---------------------+
|                5 | value1              | PhasePower1         | 2017-04-25 21:47:15 |
|                5 | value1              | PhaseStatusPower1   | 2017-04-24 23:12:47 |
|                5 | value2              | PhasePower2         | 2017-04-25 21:47:15 |
|                5 | value2              | PhaseStatusPower2   | 2017-04-25 21:07:18 |
|                5 | value3              | PhasePower3         | 2017-04-25 21:47:15 |
|                5 | value3              | PhaseStatusPower3   | 2017-04-25 21:07:27 |
|                5 | value4              | PhasePower4         | 2017-04-25 21:47:15 |
|                5 | value4              | PhaseStatusPower4   | 2017-04-25 21:07:35 |
|                5 | value5              | PhasePower5         | 2017-04-25 21:47:15 |
|                5 | value5              | PhaseStatusPower5   | 2017-04-25 21:07:42 |
|                5 | value6              | PhasePower6         | 2017-04-25 21:47:15 |
|                5 | value6              | PhaseStatusPower6   | 2017-04-25 21:07:49 |
|                5 | value7              | PhasePower7         | 2017-04-25 21:47:15 |
|                5 | value7              | PhaseStatusPower7   | 2017-04-25 21:07:57 |
|                5 | value8              | PhasePower8         | 2017-04-25 21:47:15 |
|                5 | value8              | PhaseStatusPower8   | 2017-04-25 21:08:04 |
|                5 | value9              | PhasePower9         | 2017-04-25 21:47:15 |
|                5 | value9              | PhaseStatusPower9   | 2017-04-25 21:08:12 |
+------------------+---------------------+---------------------+---------------------+
```
I changed the internal data source names from "PhaseStatusPowerN" to "PhasePowerN" to remain consistent with some other (too long) names, but after doing so things broke. I now know the only way to fix this is to create an entirely new data source template. Or remove these bad mappings by hand (haven't tried yet). 
These entries in the cacti.log tipped me off to the problem, so I went hunting through the database to see where these "PhaseStatusPowerN" entries were still present
```
2017-04-25 22:09:48 - POLLER: Poller[1] Parsed MULTI output field 'value2:215' [map value2->PhaseStatusPower2]
2017-04-25 22:09:48 - POLLER: Poller[1] Parsed MULTI output field 'value3:212' [map value3->PhaseStatusPower3]
2017-04-25 22:09:48 - POLLER: Poller[1] Parsed MULTI output field 'value4:202' [map value4->PhaseStatusPower4]
2017-04-25 22:09:48 - POLLER: Poller[1] Parsed MULTI output field 'value5:254' [map value5->PhaseStatusPower5]
2017-04-25 22:09:48 - POLLER: Poller[1] Parsed MULTI output field 'value6:193' [map value6->PhaseStatusPower6]
```

Rebuilding the poller cache was my first thought to fix this, but that doesn't work. Maybe it should? And under what circumstances would a "normal" user encounter this type of issue? I am not sure.

**Comment by eschoeller** [comment]
Confirmed that removing the bad mappings by hand (all the PhaseStatusPowerN entries) from the database resolves the issue. 
It should likely go without saying, but just in case not, I'm using a script/command data input method here.

**Comment by cigamit** [comment]
Yea, this is definitely a corner case and bug.  Resolved this morning.  Update data_templates.php and lib/utility.php

**Comment by eschoeller** [comment]
Will this fix retroactively clean up the mappings table or only prevent duplicates in the future?

**Comment by cigamit** [comment]
It is not retroactive.  However, when you re-populate the poller cache, they get fixed.  I figured it was a corner case and did not warrant a cleanup in the upgrade process.

**Comment by eschoeller** [comment]
Oh, ok but you've put a hook into the rebuild poller cache function so that's perfect.
