### ISSUE TITLE
Cannot use MySQL sockets

### ISSUE THREAD

**Issue by iokiok** [Cacti/cacti#622]
I have found that in Cacti 1.x I can no more configure MySQL access using sockets. 
In the past 0.x releases I have always set the database_host as localhost and database_port as /path/mysql.sock but now I have found that this is no more working.
I think that there is a mistake in the lib/database.php script. There is a  comment on line 45 and the conditional check from line 46 through 48 makes the socket configuration not working. 
I think you should rewrite the check using some smartest regular expression so that device is changed to "127.0.0.1" ONLY if "localhost" is used and port is different from "3306" AND from any non-numeric string (when using a path to a socket).
I have found this issue with Cacti 1.1.4 and 1.1.5, I have not tested it on previous 1.x releases.

**Comment by cigamit** [comment]
It's likely in all the 1.x releases. We have changed the database backend to sockets and 'assumed' but did not test sockets.  If you can do some research and resolve through a pull request, that would be good.  Should be something simple.

**Comment by iokiok** [comment]
I guess it can be fixed using a smart regular expression at line 46:  $port should be numeric only but different from 3306.
I'm not so smart in regular expressions, I guess you can do better than I could suggest. I can only tell you that I have tried commenting lines from 46 to 48 and it worked.

**Comment by cigamit** [comment]
I've just update lib/database.php in the development branch.  Please test it and provide feedback.  Should only take you a minute.

**Comment by cigamit** [comment]
Let me know if that fixes it.

**Comment by iokiok** [comment]
I have seen the lines you added around line 63, but unfortunately they don't fix the issue.
That is because, I guess, the check at line 46 has already changed $device to "127.0.0.1", so your condition is never matched or could not work because I think you cannot use sockets if device is an IP address and not localhost.

**Comment by cigamit** [comment]
The way it worked in the past was you would set $database_hostname = "/tmp/mysql.sock"; (or the correct location) if my memory serves me correctly.  Checking back, that is how spine works, and that is how I've updated cacti to work.  So, update your database.php and then attempt what I have described.  Let us know if it's working.

**Comment by iokiok** [comment]
Ok, I have tried the updated version of database.php configuring the socket connection as you suggested and I can confirm that it's working.
I'm sorry but I'm quite sure that in the past I have always set up the socket connection setting $database_hostname = "localhost" and $database_port = "/path/mysql.sock".

**Comment by cigamit** [comment]
Well, we changed the framework, so that is to be expected.  I'm going to go ahead and close.  We'll have an internal discussion about this.  The other option would to be to include a new optional parameter:

$database_socket = '/path/mysql.sock';
