### ISSUE TITLE
Default Graph Image Format does not change with settings change.

### ISSUE THREAD

**Issue by MoonDogg** [Cacti/cacti#624]
Settings
--Mail/Reporting/DNS
----Reporting Presets
------Default Graph Image Format

I have tried changing it to multiple different types and it never changes in the e-mails sent. I have changed setting as user and admin, even reset server no change. 

Cacti 1.1.3 (read change log on 1.1.4 and 1.1.5 and did not see anything for this but I can upgrade to test).

**Comment by cigamit** [comment]
That is the default for all new reports, but you set the actual format for each report.  Bottom of the page it is.  I did a code review and this is the only explanation.
