### ISSUE TITLE
1.1.5 upgrade not executing queries

### ISSUE THREAD

**Issue by reboot1983** [Cacti/cacti#625]
Just upgraded from 1.1.4 to 1.1.5 but the Cacti installer did not execute the upgrade-query defined in 1_1_4_to_1_1_5.php. It said:

> 
> Upgrade Results
> 
> You Cacti database has been upgraded. You can view the results below.
> 
> No SQL queries have been executed.

The query that should have been executed:
`ALTER TABLE data_input MODIFY COLUMN input_string varchar(512) default NULL`

When I check my database, the field length of input_string is still 255.

**Comment by cigamit** [comment]
That is annoying.

**Comment by cigamit** [comment]
This upgrade process is so error prone.  We need a project to fix it.  Updating the missed step...

**Comment by cigamit** [comment]
Fixed now, we will simply have to move that step to 1.1.6.  No harm done either way.  But we need to re-design the upgrade process.
