### ISSUE TITLE
Cacti upgrade process is complex and error prone to developers

### ISSUE THREAD

**Issue by cigamit** [Cacti/cacti#628]
The current Cacti upgrade process is somewhat complex to manage and needs simplification.

**Comment by dsclassen** [comment]
One thing that always confuses me are the changes to cacti.sql. I tend to pull changes from the develop branch every couple of days (living on the bleeding edge) and I think that sometimes I see changes to cacti.sql, but I'm not sure that they are being applied to my existing DB.

**Comment by cigamit** [comment]
Well keep us honest until someone volunteers to re-think this.

**Comment by jhonnyx82** [comment]
I think that if automation doesn't work, a clear step-by-step update process may be better, including also a customization option for personal installations (actually CACTI it's never a standard deployment isn't it? :) )

**Comment by cigamit** [comment]
PSR is on the roadmap.  We use some frameworks.  If we had to do it all over again, it would be heavy javascript, json and RESTful.

**Comment by cigamit** [comment]
Resolved.
