### ISSUE TITLE
Site reload after delete the last letter in the searchbar

### ISSUE THREAD

**Issue by DavidLiedke** [Cacti/cacti#629]
After i search a device or a graph in the list i want modify my search. 

I search the word "usv". I can delete the first two letters without any problems with the backspace. If i delete the last letter the site reloads and the complete search is back. 

![2017-04-27_14-16-58](https://cloud.githubusercontent.com/assets/25581728/25483089/afa255d6-2b54-11e7-8a63-b026c2deb3ce.gif)

**Comment by cigamit** [comment]
Ah yes, some things you love about Firefox, other things you don't.  Try and repeat that on Chrome.  It's a browser behavior that when you backspace beyond the end of a field, it executes a 'back' button on the browser.  If you can figure a way to fix it.  Update this ticket.  It's not an easy fix I think.  Though I'm closing this, if you find the answer, I'll reopen.
