### ISSUE TITLE
thumbnail checkbox does not change size of graphs

### ISSUE THREAD

**Issue by dsclassen** [Cacti/cacti#630]
The number of columns is changing, but not the size of the graphs. Even when the 'Thumbnails' checkbox is unchecked the graphs are still thumbnail sized.

![graph_w_thumb](https://cloud.githubusercontent.com/assets/8882563/25494936/395705bc-2b30-11e7-848a-340c49377345.png)
![graph_wo_thumb](https://cloud.githubusercontent.com/assets/8882563/25494937/397ae93c-2b30-11e7-9d1b-19b3287b2d7d.png)

**Comment by dsclassen** [comment]
Never mind. I had columns set to 3. Setting back to 1 returns graph size to that expected. Chalk this up to user error.

**Comment by cigamit** [comment]
What do you think about removing those section breaks so that the tree mode looks like the preview mode?  Otherwise, there is a big waste of space.

**Comment by dsclassen** [comment]
I would agree. I rarely have multiple graphs in a particular section, but maybe others do and would like them to stay....change it and see how many people complain ; )

**Comment by cigamit** [comment]
Okay, opened this one for tracking https://github.com/Cacti/cacti/issues/637
