### ISSUE TITLE
Graphs Tab wont display on Mobile devices - Cacti 1.1.5

### ISSUE THREAD

**Issue by The-Mafioso** [Cacti/cacti#634]
When opening cacti web portal from any mobile device, clicking on the graphs tab wont display any device/graphs 
![img_1870](https://cloud.githubusercontent.com/assets/27900099/25540612/64d9632c-2c54-11e7-911c-27eb3af93f4b.PNG)

**Comment by cigamit** [comment]
"Classic" is like your 57 Chevy, no frills.  Try modern or dark for better luck.  I prefer dark.

**Comment by The-Mafioso** [comment]
Hi, even with the new modern same issue 
![screenshot_2017-04-29-01-28-59](https://cloud.githubusercontent.com/assets/27900099/25549610/919dcfe8-2c7b-11e7-84e1-cf54d8fedbf4.png)

**Comment by cigamit** [comment]
I'm opening up again, not for what you think.  Click the graphs tab a second time, the tree will open up, then click to the graph tree branch you want, and graphs will open up.  The reason I'm opening this one again, is that the jstree should do a callback if there is not prior session saved, and get the default tree like old Cacti's did.

**Comment by cigamit** [comment]
This will be resolved in 1.1.6, which might end up being 1.2.0 due to the Responsive nature of the changes.
