### ISSUE TITLE
When Creating a Data Query Graph you should be able to select the Data Source Profile

### ISSUE THREAD

**Issue by jhonnyx82** [Cacti/cacti#636]
I am creating additional graph templates - Data queries - Device Templates based on different polling intervals.

When duplicating, if a graph template has a comment or H/V rule these keeps the reference of the previous data source

**Comment by cigamit** [comment]
Try to explain that in pictures please.

**Comment by jhonnyx82** [comment]
Let me add some pics to explain myself : 

- These are my data profiles : 
![image](https://cloud.githubusercontent.com/assets/26431888/25563553/7fad2fbc-2d9e-11e7-8238-141c589077d5.png)

- I have the following Graph template I want to duplicate and statically use it for **30 Seconds polling** data profile: 
![image](https://cloud.githubusercontent.com/assets/26431888/25563575/eaf46920-2d9e-11e7-936d-6608cc8a3be6.png)

- Duplicating the Graph template, I will change the Graph items:
![image](https://cloud.githubusercontent.com/assets/26431888/25563588/3d63a810-2d9f-11e7-9522-74457a8f9530.png)

From : 
![image](https://cloud.githubusercontent.com/assets/26431888/25563591/49eb42c8-2d9f-11e7-96ef-34303b26eb6e.png)

To:
![image](https://cloud.githubusercontent.com/assets/26431888/25563593/5b44b8d8-2d9f-11e7-817c-d8b042465132.png)

And everything is fine, the items 11 - 12 - 13 are the problem: 
![image](https://cloud.githubusercontent.com/assets/26431888/25563609/9111c870-2d9f-11e7-81c8-a78a15c1dfe0.png)

As I need to delete them and recreate them otherwise the result on creating a new data query pointing to this graph will be to have both Data Templates (the previous 5 minutes of the original and the new 1 minute I set as actual data profile for the items) and the only solution is to delete the comment/h-V rules items on the graph template, that way the data template on the data query is coherent

![image](https://cloud.githubusercontent.com/assets/26431888/25563646/993ecec0-2da0-11e7-890d-df9adedda314.png)

**Comment by cigamit** [comment]
I'm going to suggest that instead of doing thing this way, we should incorporate the Data Profile into the Data Query or the Data Query Graph Associations.  That way, you don't necessarily need to duplicate anything other than the Data Query, if even that.  What do you think about that?

So, there are two approaches as shown below:

![datasourceprofileprototype1](https://cloud.githubusercontent.com/assets/957322/25570469/2bf7c9e8-2deb-11e7-83f4-e074073bc0fb.png)

Or:

![datasourceprofileprototype2](https://cloud.githubusercontent.com/assets/957322/25570479/361796a6-2deb-11e7-8dff-76d9020c5558.png)

What do you think?

**Comment by jhonnyx82** [comment]
I think it makes more sense to have the **Data source profile** into the **Data Query Graph Associations**  with an override option by data source.

Just, do you see this as a disruptive migration from the current scenario? ( I am going to build soon our Device base with Automation), how should I migrate my current setup by this new method (for coherence )


I have Each Interface graph template for each of my data profiles: 

![image](https://cloud.githubusercontent.com/assets/26431888/25575259/f8b938ee-2e55-11e7-808d-4d51b38eb743.png)

They are using the current Data Templates:

![image](https://cloud.githubusercontent.com/assets/26431888/25575414/7d231306-2e57-11e7-821e-70440757f515.png)

And integrated into the current three Data Queries:

![image](https://cloud.githubusercontent.com/assets/26431888/25575427/a6e9cb12-2e57-11e7-9b2c-4b76a51074fd.png)


Also, Where the **Data Templates** (marked in Red) are defined?

![image](https://cloud.githubusercontent.com/assets/26431888/25575518/861e1d24-2e58-11e7-89cf-177f08be52fb.png)

**Comment by cigamit** [comment]
Well, it's on my list now.  But I can not promise you any dates.  There are a number of projects ahead of this.  So, if you are planning a deployment, keep doing what you are doing.  There will be some migration policy for sure.

**Comment by jhonnyx82** [comment]
Thanks, 

I will proceed with my deployment and will keep you updated in case something comes up.

Please consider all this enhancement requests as an option, for you to evaluate their quality and eventual improvement of CACTI.

If you find these of any use, I will be glad, but not pretend to see them necessarily any soon.

Thanks again for your effort!

**Comment by cigamit** [comment]
I'm going to rename this one.  The duplicate data source is some sort of duplicate anomaly, what we want to do is provide a way for Data Templates to choose a profile per Graph.

**Comment by cigamit** [comment]
Dang, this is already supported in 1.2.
