### ISSUE TITLE
rra not written or WARNING: Poller Output Table not Empty (own scripts as data source)

### ISSUE THREAD

**Issue by rcmcronny** [Cacti/cacti#642]
As #389 is now closed and i followed this issue and i dont want to chime in in that issue, I create this new issue, as i have a simular issue ,but no php graph errors or such as issue #389 was closed lastly.
I posted in the forum ( http://forums.cacti.net/viewtopic.php?f=2&t=56908 ), no response so far.
This setup worked all the 0.x Cacti Versions without any issues. The scripts generate the correct output, this is written to poller_output table correctly, but not processed. I have done all things i found in the forum and here on github, nothing helps so far.
I have this issue since 1.0.0 and hopefully did upgrade to latest 1.1.5, but this issue remains.

Here is 1 graph with all settings i hope in pictures  (1 wire temperatures), if there is something needed, please check the forum link for details, also i am happy to provide more details of course.

![cacti_datainputmethods](https://cloud.githubusercontent.com/assets/5807210/25567264/3838370c-2dea-11e7-9096-2da8ce77008a.png)
![cacti_datasources_fullpage](https://cloud.githubusercontent.com/assets/5807210/25567265/386b54de-2dea-11e7-840b-0b62ee6475f3.png)
![cacti_graphview-fullpage](https://cloud.githubusercontent.com/assets/5807210/25567266/386c1716-2dea-11e7-9757-06944b70c8d9.png)
![cacti_clog](https://cloud.githubusercontent.com/assets/5807210/25567267/386cab4a-2dea-11e7-9565-f28257a53bb5.png)

**Comment by cigamit** [comment]
Export your Graph template with dependencies and upload it and your data collection script.

**Comment by rcmcronny** [comment]
I am sorry, but i do nut use a graph template, its full manual process, (as in #389)

I have made a screen of the poller_output table, this visualizes the script outputs. I can upload, this 1 wire script, but it will not show you anything without 1wire sensors ;)
![poller_output_table_screen](https://cloud.githubusercontent.com/assets/5807210/25574598/26b008fa-2e50-11e7-92a2-cad6be69c06b.png)

**Comment by cigamit** [comment]
Please upload your script, and the output from the poller_items table for this data source.

**Comment by cigamit** [comment]
Also, please upload the rrdtool info from the RRDfile.

**Comment by rcmcronny** [comment]
rrdtool info:

rrdtool info /home/www/intranet/cacti/rra/indoor1_avr_54.rrd
filename = "/home/www/intranet/cacti/rra/indoor1_avr_54.rrd"
rrd_version = "0003"
step = 60
last_update = 1486062841
header_size = 5552
ds[indoor1_avr].index = 0
ds[indoor1_avr].type = "GAUGE"
ds[indoor1_avr].minimal_heartbeat = 600
ds[indoor1_avr].min = -5,0000000000e+01
ds[indoor1_avr].max = 1,5000000000e+02
ds[indoor1_avr].last_ds = "22.8"
ds[indoor1_avr].value = 2,2800000000e+01
ds[indoor1_avr].unknown_sec = 0
ds[outdoor1].index = 1
ds[outdoor1].type = "GAUGE"
ds[outdoor1].minimal_heartbeat = 600
ds[outdoor1].min = -5,0000000000e+01
ds[outdoor1].max = 1,5000000000e+02
ds[outdoor1].last_ds = "1.81"
ds[outdoor1].value = 1,8100000000e+00
ds[outdoor1].unknown_sec = 0
ds[wakue1].index = 2
ds[wakue1].type = "GAUGE"
ds[wakue1].minimal_heartbeat = 600
ds[wakue1].min = -5,0000000000e+01
ds[wakue1].max = 1,5000000000e+02
ds[wakue1].last_ds = "18.12"
ds[wakue1].value = 1,8120000000e+01
ds[wakue1].unknown_sec = 0
ds[aquarium].index = 3
ds[aquarium].type = "GAUGE"
ds[aquarium].minimal_heartbeat = 600
ds[aquarium].min = -5,0000000000e+01
ds[aquarium].max = 1,5000000000e+02
ds[aquarium].last_ds = "28.12"
ds[aquarium].value = 2,8120000000e+01
ds[aquarium].unknown_sec = 0
rra[0].cf = "AVERAGE"
rra[0].rows = 500
rra[0].cur_row = 283
rra[0].pdp_per_row = 1
rra[0].xff = 5,0000000000e-01
rra[0].cdp_prep[0].value = NaN
rra[0].cdp_prep[0].unknown_datapoints = 0
rra[0].cdp_prep[1].value = NaN
rra[0].cdp_prep[1].unknown_datapoints = 0
rra[0].cdp_prep[2].value = NaN
rra[0].cdp_prep[2].unknown_datapoints = 0
rra[0].cdp_prep[3].value = NaN
rra[0].cdp_prep[3].unknown_datapoints = 0
rra[1].cf = "AVERAGE"
rra[1].rows = 600
rra[1].cur_row = 269
rra[1].pdp_per_row = 1
rra[1].xff = 5,0000000000e-01
rra[1].cdp_prep[0].value = NaN
rra[1].cdp_prep[0].unknown_datapoints = 0
rra[1].cdp_prep[1].value = NaN
rra[1].cdp_prep[1].unknown_datapoints = 0
rra[1].cdp_prep[2].value = NaN
rra[1].cdp_prep[2].unknown_datapoints = 0
rra[1].cdp_prep[3].value = NaN
rra[1].cdp_prep[3].unknown_datapoints = 0
rra[2].cf = "AVERAGE"
rra[2].rows = 700
rra[2].cur_row = 318
rra[2].pdp_per_row = 6
rra[2].xff = 5,0000000000e-01
rra[2].cdp_prep[0].value = 4,5600000000e+01
rra[2].cdp_prep[0].unknown_datapoints = 0
rra[2].cdp_prep[1].value = 3,6200000000e+00
rra[2].cdp_prep[1].unknown_datapoints = 0
rra[2].cdp_prep[2].value = 3,6179000000e+01
rra[2].cdp_prep[2].unknown_datapoints = 0
rra[2].cdp_prep[3].value = 5,6242333333e+01
rra[2].cdp_prep[3].unknown_datapoints = 0
rra[3].cf = "AVERAGE"
rra[3].rows = 775
rra[3].cur_row = 187
rra[3].pdp_per_row = 24
rra[3].xff = 5,0000000000e-01
rra[3].cdp_prep[0].value = 4,5600000000e+01
rra[3].cdp_prep[0].unknown_datapoints = 0
rra[3].cdp_prep[1].value = 3,6200000000e+00
rra[3].cdp_prep[1].unknown_datapoints = 0
rra[3].cdp_prep[2].value = 3,6179000000e+01
rra[3].cdp_prep[2].unknown_datapoints = 0
rra[3].cdp_prep[3].value = 5,6242333333e+01
rra[3].cdp_prep[3].unknown_datapoints = 0
rra[4].cf = "AVERAGE"
rra[4].rows = 797
rra[4].cur_row = 595
rra[4].pdp_per_row = 288
rra[4].xff = 5,0000000000e-01
rra[4].cdp_prep[0].value = 4,5600000000e+01
rra[4].cdp_prep[0].unknown_datapoints = 0
rra[4].cdp_prep[1].value = 3,6200000000e+00
rra[4].cdp_prep[1].unknown_datapoints = 0
rra[4].cdp_prep[2].value = 3,6179000000e+01
rra[4].cdp_prep[2].unknown_datapoints = 0
rra[4].cdp_prep[3].value = 5,6242333333e+01
rra[4].cdp_prep[3].unknown_datapoints = 0
rra[5].cf = "MAX"
rra[5].rows = 500
rra[5].cur_row = 411
rra[5].pdp_per_row = 1
rra[5].xff = 5,0000000000e-01
rra[5].cdp_prep[0].value = NaN
rra[5].cdp_prep[0].unknown_datapoints = 0
rra[5].cdp_prep[1].value = NaN
rra[5].cdp_prep[1].unknown_datapoints = 0
rra[5].cdp_prep[2].value = NaN
rra[5].cdp_prep[2].unknown_datapoints = 0
rra[5].cdp_prep[3].value = NaN
rra[5].cdp_prep[3].unknown_datapoints = 0
rra[6].cf = "MAX"
rra[6].rows = 600
rra[6].cur_row = 303
rra[6].pdp_per_row = 1
rra[6].xff = 5,0000000000e-01
rra[6].cdp_prep[0].value = NaN
rra[6].cdp_prep[0].unknown_datapoints = 0
rra[6].cdp_prep[1].value = NaN
rra[6].cdp_prep[1].unknown_datapoints = 0
rra[6].cdp_prep[2].value = NaN
rra[6].cdp_prep[2].unknown_datapoints = 0
rra[6].cdp_prep[3].value = NaN
rra[6].cdp_prep[3].unknown_datapoints = 0
rra[7].cf = "MAX"
rra[7].rows = 700
rra[7].cur_row = 371
rra[7].pdp_per_row = 6
rra[7].xff = 5,0000000000e-01
rra[7].cdp_prep[0].value = 2,2800000000e+01
rra[7].cdp_prep[0].unknown_datapoints = 0
rra[7].cdp_prep[1].value = 1,8100000000e+00
rra[7].cdp_prep[1].unknown_datapoints = 0
rra[7].cdp_prep[2].value = 1,8119000000e+01
rra[7].cdp_prep[2].unknown_datapoints = 0
rra[7].cdp_prep[3].value = 2,8122333333e+01
rra[7].cdp_prep[3].unknown_datapoints = 0
rra[8].cf = "MAX"
rra[8].rows = 775
rra[8].cur_row = 283
rra[8].pdp_per_row = 24
rra[8].xff = 5,0000000000e-01
rra[8].cdp_prep[0].value = 2,2800000000e+01
rra[8].cdp_prep[0].unknown_datapoints = 0
rra[8].cdp_prep[1].value = 1,8100000000e+00
rra[8].cdp_prep[1].unknown_datapoints = 0
rra[8].cdp_prep[2].value = 1,8119000000e+01
rra[8].cdp_prep[2].unknown_datapoints = 0
rra[8].cdp_prep[3].value = 2,8122333333e+01
rra[8].cdp_prep[3].unknown_datapoints = 0
rra[9].cf = "MAX"
rra[9].rows = 797
rra[9].cur_row = 373
rra[9].pdp_per_row = 288
rra[9].xff = 5,0000000000e-01
rra[9].cdp_prep[0].value = 2,2800000000e+01
rra[9].cdp_prep[0].unknown_datapoints = 0
rra[9].cdp_prep[1].value = 1,8100000000e+00
rra[9].cdp_prep[1].unknown_datapoints = 0
rra[9].cdp_prep[2].value = 1,8119000000e+01
rra[9].cdp_prep[2].unknown_datapoints = 0
rra[9].cdp_prep[3].value = 2,8122333333e+01
rra[9].cdp_prep[3].unknown_datapoints = 0


![cacti_sql_polleritem_id54](https://cloud.githubusercontent.com/assets/5807210/25579958/d6fe33f4-2e7c-11e7-8da1-698716ea9472.png)

[cacti_1wire.pl.zip](https://github.com/Cacti/cacti/files/967860/cacti_1wire.pl.zip)

**Comment by cigamit** [comment]
Goto Data Sources and turn on Data Source Debug.  Copy the RRDtool create syntax and see if you can create the RRDfile manually.

**Comment by rcmcronny** [comment]
Yes this works, the file exists already, so I deleted the old and created it new with the data sources debug command:

` /usr/bin/rrdtool create /home/www/intranet/cacti/rra/indoor1_avr_54.rrd --step 60  DS:indoor1_avr:GAUGE:600:-50:150 DS:outdoor1:GAUGE:600:-50:150 DS:wakue1:GAUGE:600:-50:150 DS:aquarium:GAUGE:600:-50:150 RRA:AVERAGE:0.5:1:500 RRA:AVERAGE:0.5:1:600 RRA:AVERAGE:0.5:6:700 RRA:AVERAGE:0.5:24:775 RRA:AVERAGE:0.5:288:797 RRA:MAX:0.5:1:500 RRA:MAX:0.5:1:600 RRA:MAX:0.5:6:700 RRA:MAX:0.5:24:775 RRA:MAX:0.5:288:797`

 ls -lha /home/www/intranet/cacti/rra/indoor1_avr_54.rrd     -rw-r--r-- 1 apache apache 217K  2. Mai 07:00 /home/www/intranet/cacti/rra/indoor1_avr_54.rrd

 # rrdtool info /home/www/intranet/cacti/rra/indoor1_avr_54.rrd
filename = "/home/www/intranet/cacti/rra/indoor1_avr_54.rrd"
rrd_version = "0003"
step = 60
last_update = 1493701216
header_size = 5552
ds[indoor1_avr].index = 0
ds[indoor1_avr].type = "GAUGE"
ds[indoor1_avr].minimal_heartbeat = 600
ds[indoor1_avr].min = -5,0000000000e+01
ds[indoor1_avr].max = 1,5000000000e+02
ds[indoor1_avr].last_ds = "U"
ds[indoor1_avr].value = NaN
ds[indoor1_avr].unknown_sec = 16
ds[outdoor1].index = 1
ds[outdoor1].type = "GAUGE"
ds[outdoor1].minimal_heartbeat = 600
ds[outdoor1].min = -5,0000000000e+01
ds[outdoor1].max = 1,5000000000e+02
ds[outdoor1].last_ds = "U"
ds[outdoor1].value = NaN
ds[outdoor1].unknown_sec = 16
ds[wakue1].index = 2
ds[wakue1].type = "GAUGE"
ds[wakue1].minimal_heartbeat = 600
ds[wakue1].min = -5,0000000000e+01
ds[wakue1].max = 1,5000000000e+02
ds[wakue1].last_ds = "U"
ds[wakue1].value = NaN
ds[wakue1].unknown_sec = 16
ds[aquarium].index = 3
ds[aquarium].type = "GAUGE"
ds[aquarium].minimal_heartbeat = 600
ds[aquarium].min = -5,0000000000e+01
ds[aquarium].max = 1,5000000000e+02
ds[aquarium].last_ds = "U"
ds[aquarium].value = NaN
ds[aquarium].unknown_sec = 16
rra[0].cf = "AVERAGE"
rra[0].rows = 500
rra[0].cur_row = 391
rra[0].pdp_per_row = 1
rra[0].xff = 5,0000000000e-01
rra[0].cdp_prep[0].value = NaN
rra[0].cdp_prep[0].unknown_datapoints = 0
rra[0].cdp_prep[1].value = NaN
rra[0].cdp_prep[1].unknown_datapoints = 0
rra[0].cdp_prep[2].value = NaN
rra[0].cdp_prep[2].unknown_datapoints = 0
rra[0].cdp_prep[3].value = NaN
rra[0].cdp_prep[3].unknown_datapoints = 0
rra[1].cf = "AVERAGE"
rra[1].rows = 600
rra[1].cur_row = 56
rra[1].pdp_per_row = 1
rra[1].xff = 5,0000000000e-01
rra[1].cdp_prep[0].value = NaN
rra[1].cdp_prep[0].unknown_datapoints = 0
rra[1].cdp_prep[1].value = NaN
rra[1].cdp_prep[1].unknown_datapoints = 0
rra[1].cdp_prep[2].value = NaN
rra[1].cdp_prep[2].unknown_datapoints = 0
rra[1].cdp_prep[3].value = NaN
rra[1].cdp_prep[3].unknown_datapoints = 0
rra[2].cf = "AVERAGE"
rra[2].rows = 700
rra[2].cur_row = 0
rra[2].pdp_per_row = 6
rra[2].xff = 5,0000000000e-01
rra[2].cdp_prep[0].value = NaN
rra[2].cdp_prep[0].unknown_datapoints = 0
rra[2].cdp_prep[1].value = NaN
rra[2].cdp_prep[1].unknown_datapoints = 0
rra[2].cdp_prep[2].value = NaN
rra[2].cdp_prep[2].unknown_datapoints = 0
rra[2].cdp_prep[3].value = NaN
rra[2].cdp_prep[3].unknown_datapoints = 0
rra[3].cf = "AVERAGE"
rra[3].rows = 775
rra[3].cur_row = 670
rra[3].pdp_per_row = 24
rra[3].xff = 5,0000000000e-01
rra[3].cdp_prep[0].value = NaN
rra[3].cdp_prep[0].unknown_datapoints = 12
rra[3].cdp_prep[1].value = NaN
rra[3].cdp_prep[1].unknown_datapoints = 12
rra[3].cdp_prep[2].value = NaN
rra[3].cdp_prep[2].unknown_datapoints = 12
rra[3].cdp_prep[3].value = NaN
rra[3].cdp_prep[3].unknown_datapoints = 12
rra[4].cf = "AVERAGE"
rra[4].rows = 797
rra[4].cur_row = 578
rra[4].pdp_per_row = 288
rra[4].xff = 5,0000000000e-01
rra[4].cdp_prep[0].value = NaN
rra[4].cdp_prep[0].unknown_datapoints = 12
rra[4].cdp_prep[1].value = NaN
rra[4].cdp_prep[1].unknown_datapoints = 12
rra[4].cdp_prep[2].value = NaN
rra[4].cdp_prep[2].unknown_datapoints = 12
rra[4].cdp_prep[3].value = NaN
rra[4].cdp_prep[3].unknown_datapoints = 12
rra[5].cf = "MAX"
rra[5].rows = 500
rra[5].cur_row = 179
rra[5].pdp_per_row = 1
rra[5].xff = 5,0000000000e-01
rra[5].cdp_prep[0].value = NaN
rra[5].cdp_prep[0].unknown_datapoints = 0
rra[5].cdp_prep[1].value = NaN
rra[5].cdp_prep[1].unknown_datapoints = 0
rra[5].cdp_prep[2].value = NaN
rra[5].cdp_prep[2].unknown_datapoints = 0
rra[5].cdp_prep[3].value = NaN
rra[5].cdp_prep[3].unknown_datapoints = 0
rra[6].cf = "MAX"
rra[6].rows = 600
rra[6].cur_row = 369
rra[6].pdp_per_row = 1
rra[6].xff = 5,0000000000e-01
rra[6].cdp_prep[0].value = NaN
rra[6].cdp_prep[0].unknown_datapoints = 0
rra[6].cdp_prep[1].value = NaN
rra[6].cdp_prep[1].unknown_datapoints = 0
rra[6].cdp_prep[2].value = NaN
rra[6].cdp_prep[2].unknown_datapoints = 0
rra[6].cdp_prep[3].value = NaN
rra[6].cdp_prep[3].unknown_datapoints = 0
rra[7].cf = "MAX"
rra[7].rows = 700
rra[7].cur_row = 439
rra[7].pdp_per_row = 6
rra[7].xff = 5,0000000000e-01
rra[7].cdp_prep[0].value = NaN
rra[7].cdp_prep[0].unknown_datapoints = 0
rra[7].cdp_prep[1].value = NaN
rra[7].cdp_prep[1].unknown_datapoints = 0
rra[7].cdp_prep[2].value = NaN
rra[7].cdp_prep[2].unknown_datapoints = 0
rra[7].cdp_prep[3].value = NaN
rra[7].cdp_prep[3].unknown_datapoints = 0
rra[8].cf = "MAX"
rra[8].rows = 775
rra[8].cur_row = 728
rra[8].pdp_per_row = 24
rra[8].xff = 5,0000000000e-01
rra[8].cdp_prep[0].value = NaN
rra[8].cdp_prep[0].unknown_datapoints = 12
rra[8].cdp_prep[1].value = NaN
rra[8].cdp_prep[1].unknown_datapoints = 12
rra[8].cdp_prep[2].value = NaN
rra[8].cdp_prep[2].unknown_datapoints = 12
rra[8].cdp_prep[3].value = NaN
rra[8].cdp_prep[3].unknown_datapoints = 12
rra[9].cf = "MAX"
rra[9].rows = 797
rra[9].cur_row = 496
rra[9].pdp_per_row = 288
rra[9].xff = 5,0000000000e-01
rra[9].cdp_prep[0].value = NaN
rra[9].cdp_prep[0].unknown_datapoints = 12
rra[9].cdp_prep[1].value = NaN
rra[9].cdp_prep[1].unknown_datapoints = 12
rra[9].cdp_prep[2].value = NaN
rra[9].cdp_prep[2].unknown_datapoints = 12
rra[9].cdp_prep[3].value = NaN
rra[9].cdp_prep[3].unknown_datapoints = 12

**Comment by cigamit** [comment]
I think I figured it out.  All script server variables must start with alpha characters, name values must be delimited by a colon, and there can be only one space between name value pairs.  Item 54 in your poller output table begins with a numeric character.  You will have to change the output.  Does that make sense?

**Comment by rcmcronny** [comment]
Thanks, sorry for the delay, i will try to test it tomorrow and give feedback.

**Comment by rcmcronny** [comment]
ok, did the change for the output, but this did not solve anything, sorry.
Here is the poller output table:
![cacti_poller_output-20170508](https://cloud.githubusercontent.com/assets/5807210/25821045/d3b7c7de-3433-11e7-8bc2-cc05dbb08ae1.png)

Ahh i see, if the "start with alpha char" would be, then it should not affect the other scripts in this output, these have alpha characters on start. And this setup worked with 0.x Cacti without any problems.

**Comment by cigamit** [comment]
Very busy this week.  Can you run the poller in debug mode for one pass and attach the output.  You can setup poller.php in debug only from the Settings page.  That way you don't get any other GUI warnings.

**Comment by rcmcronny** [comment]
I have also a busy week, so all fine, nothing to stress on this. 

I uploaded the log to pastebin:  https://pastebin.com/38bcKbbC
Debug Mode for 1 run (i did it manually so ignore the cron error ;) )

**Comment by cigamit** [comment]
Are you sure you did not put Cacti into debug?  I only wanted cmd.php into debug.  The rest of cacti should be at 'Low'.  Please run again and upload the debug log.

**Comment by cigamit** [comment]
Sorry, should be poller.php into debug.

**Comment by rcmcronny** [comment]
ups, sorry my fault, thought developer debug mode. I created a new log with poller.php as debug choosen, hopefully this fits now ;) 
https://pastebin.com/kk14h2YJ

**Comment by cigamit** [comment]
What are your cron and poller interval set to?  YOu may have to run the command a few times.  I'm looking for the PARSED log entries.

**Comment by rcmcronny** [comment]
both set to 60 seconds
i have let it run for 5 minutes, so this should cover 5 runs

cacti.log: https://pastebin.com/m1mEtSFM
output poller.php run from cron:  https://pastebin.com/RxUwmsp9

**Comment by rcmcronny** [comment]
is anything from me needed for this ? 

(readded paste as the timeout was 1 month, now unlimited, new urls are:)
cacti.log: https://pastebin.com/H6Mxmikf
output poller.php run from cron: https://pastebin.com/zpz9Fh5J

**Comment by tomchiverton** [comment]
Similar issue here on 1.1.7 (Fedora 24). Worked fine in earlier versions.

the poller log says things like 

 2017-06-10 17:55:02 - POLLER: Poller[1] Device[3] Description[Other] DS[20] Graphs['ADSL Usage'] CMD: /bin/cat /opt/zen-usage, output: downloadAllowanceUsed:9.144 uploadAllowanceUsed:3.854 dailyAverageDownloadUsage:0.750 predictedDownloadUsage:24.146 

Yet the rrd file is not updated. No errors logged even at high debug levels.

**Comment by cigamit** [comment]
tomchiverton, is your graph templated or non-templated?

**Comment by tomchiverton** [comment]
@cigamit it's not templated.

**Comment by cigamit** [comment]
Finally figured this one out.  Resolved.  Will be part of the 1.1.11 release.

**Comment by tomchiverton** [comment]
Can you point out the commit so people can back port to their live systems? 
-- 
Tom

**Comment by tomchiverton** [comment]
Fix works here on 1.1.10 with the patch applied by hand. My graphs work again ! Hurrah ! 

Thanks !

**Comment by rcmcronny** [comment]
For me the graphs work again, also. Great ! THANK YOU @cigamit
