### ISSUE TITLE
Request: Plugin translation files

### ISSUE THREAD

**Issue by jpobeda** [Cacti/cacti#644]
Hi guys,

Any chance of getting the plugins files to keep translating them? Due to that little issue regarding the plugin exclusion from cacti.pot I've done a lot of work already for plugins as well and I could start merging translation.

No rush but a reminder for you.

**Comment by cigamit** [comment]
I'm not sure what you are looking for.  If you are looking for the PO files, you can create them yourself just by simply running the update_pot.sh script in the locales directory of the plugin, and then creating it using any one of dozens of free PO editors.  Then, you are off to the races creating your own translation.

Please refer to this page.  https://github.com/Cacti/cacti/wiki/How-to-Create-a-Translation.  Once you are done, you should create a pull request.

**Comment by jpobeda** [comment]
My bad, I've never read that doc sorry.

Thanks
