### ISSUE TITLE
Modify automation to test for data before creating graphs

### ISSUE THREAD

**Issue by cigamit** [Cacti/cacti#645]
Some templates and automation routines are quite ignorant of the fact that some OID's do not exist, but create the graphs anyway.  We should always test the data source before creating it.

**Comment by eschoeller** [comment]
Hey @TheWitness  maybe #4182 fixed this?

**Comment by TheWitness** [comment]
No, but give me few days, on a streak.

**Comment by eschoeller** [comment]
Lol yeah you are!

**Comment by TheWitness** [comment]
@eschoeller, can you please test these.  I need Data Queries tested.  I've tested script and snmp, and they both appear working just fine.  Note, remote agent is not functional yet.  So, no remote data collectors unless the main Cacti can reach the devices.

**Comment by anarkia1976** [comment]
Hi, i have these error:

2021-03-25  12:04:22 - CMDPHP PHP ERROR NOTICE Backtrace:   (/host.php[70]:form_actions(),  /host.php[327]:automation_update_device(),  /lib/api_automation.php[3953]:automation_execute_data_query(),  /lib/api_automation.php[2206]:create_dq_graphs(),  /lib/api_automation.php[2618]:test_data_sources(),  /lib/functions.php[1594]:test_data_source(),  /lib/functions.php[1784]:CactiErrorHandler())
2021-03-25 12:04:22 - ERROR PHP NOTICE: Undefined variable: outputs  in file: /var/www/html/cacti/lib/functions.php  on line: 1784

the problem arises when automation has to create graphs related the interfaces. (atuomation --> graphs rules).

thanks a lot.

**Comment by TheWitness** [comment]
@anarkia1976, thanks for testing.  Update soon.

**Comment by TheWitness** [comment]
Try again.

**Comment by anarkia1976** [comment]
Error attached:
![image](https://user-images.githubusercontent.com/1744639/112478972-d12c5b80-8d74-11eb-82c5-18829861e195.png)
thanks.

**Comment by eschoeller** [comment]
Sorry I'm not in the greatest position to test right now ... only have a prod environment that is ... running on questionable/overloaded hardware (I guess?). New hardware upgrade coming ...

**Comment by TheWitness** [comment]
One step closer.  Next commit should fix it the rest of the way.
