### ISSUE TITLE
2 Lines title with pango markup

### ISSUE THREAD

**Issue by jhonnyx82** [Cacti/cacti#652]
I am aware that pango markup are supported in Cacti but I think not totally in the title.

I would like to ask a support to use pango markup in the title for a 2 split and to have an automatic or manual sizing of the top border of a graph to support the 2+ lines of the title.

Possibly this is something more related to RRDtool than Cacti but I am not sure.

**Comment by jhonnyx82** [comment]
just a note : on the watermark the pango markup seems to be working (besides the 2 lines)

**Comment by cciethor** [comment]
Is there any progress on this ?  we need to have the option to include two lines graph titles .

**Comment by cigamit** [comment]
There is an RRDtool patch floating around out there that achieves this.  It may already be opened as a pull request out on Tobi's Github page.  It's not so much a Cacti issue.

**Comment by netniV** [comment]
@jhonnyx82  Did you try using pango text in the title? It's been supported in all graph text fields since 1.3, I can't see anything specifically about the title so if you added a <br /> between the two lines, it may work.

**Comment by cigamit** [comment]
I've tested the two line solution with Pango, and the spacing is all wrong.  There is a patch to RRDtool sources that adds a true two line solution.  I'll see if I can find it here shortly.

**Comment by cigamit** [comment]
Here is the patch.  @netniV can you do a pull request with this patch to RRDtool Git?

https://gist.github.com/petski/6240b64e527c821fc537e0d866cbeec1

**Comment by netniV** [comment]
If made my own variation of this into the 1.7 code: 

Type | Location
:--- | :---
Pull Request | https://github.com/oetiker/rrdtool-1.x/pull/897
Dev Code | https://github.com/netniV/rrdtool-1.x/tree/SplitTitle

**Comment by netniV** [comment]
Here is a screenshot showing the output:
![image](https://user-images.githubusercontent.com/9052188/43316289-c46237e0-9190-11e8-9a67-356bc30180ed.png)

**Comment by netniV** [comment]
I still feel that further work could be made on it for:

#### Possible Further Enhancements:
- Defining max lines as a parameter
- Defining split character as parameter
- Defining ability to use/not use `<br>`, `\n` or `\r` as split characters
- Defining the ability to trim/not trim line text

#### Known issues:
At the moment split titles will leave leading/trailing spaces if they are defined as such.  

The example above is that the graph title will have a trailing space on line 1 and a leading space on line 2 which distorts the output.  To correct, the title should have been defined as `|host_description|?Disk Space - |query_dskDevice|` in the current version:
![image](https://user-images.githubusercontent.com/9052188/43316449-5352faf2-9191-11e8-9f6a-19d722643a7f.png)

#### Comparison:
![image](https://user-images.githubusercontent.com/9052188/43316729-1c88390a-9192-11e8-88c5-3c75371dbc7f.png)

With single space, the different is subtle so not really an issue... but I noticed it ;-)

**Comment by netniV** [comment]
@jhonnyx82 I have a compilable repo that now allows this if you wish to have a custom build of 1.7.0 of RRDTool.  You can use \n, <br>, <br/> or a carriage return or line feed to create separate lines.

**Comment by netniV** [comment]
I'm going to close this now as 1.7.x now has support for this in the latest master branch of rrdtool on GitHub (see the [rrdtool repo](https://github.com/oetiker/rrdtool-1.x/pull/897) for more information).  

Not sure when this would appear into packages for Linux systems but it can be manually downloaded and compiled.
