### ISSUE TITLE
CMDPHP PHP ERROR WARNING Backtrace: (/cmd.php: 449 update_host_status)(/lib/functions.php: 893

### ISSUE THREAD

**Issue by wmoreno3** [Cacti/cacti#657]
My problem:
`ERROR PHP WARNING: A non-numeric value encountered in file: /usr/local/share/cacti/lib/functions.php  on line: 893`

`CMDPHP PHP ERROR WARNING Backtrace: (/cmd.php: 449 update_host_status)(/lib/functions.php: 893 CactiErrorHandler)(/lib/functions.php: 4296 cacti_debug_backtrace)`

`cmd.php` Line: 449;
`update_host_status(HOST_UP, $host_id, $hosts, $ping, $hosts[$host_id]['availability_method'], $print_data_to_stdout);`

`functions.php` line: 893;
`$hosts[$host_id]['avg_time'] = (($hosts[$host_id]['total_polls']-1-$hosts[$host_id]['failed_polls']) * $hosts[$host_id]['avg_time'] + $ping_time) / ($hosts[$host_id]['total_polls'] - $hosts[$host_id]['failed_polls']);`

My system:
`FreeBSD 11.0-RELEASE-p10 #2` `php71-7.1.4` `rrdtool-1.6.0_1` `cacti-1.1.5`

Can anybody tell me: where is "A non-numeric value" in the line code?

**Comment by cigamit** [comment]
Can you please, just before line 893 add the following:

cacti_log("The ping time is: $ping_time");

Let us know the output in the clog.  Also, what is your default language, and if this host is using an icmp ping, please send us the output of the ping of the host using the following syntax:

`ping -t 1000 -c 3 hostname`

Finally, let us know the version of FreeBSD, and the output of the following:

<?php print PHP_OS . "\n";?>

Thanks.

**Comment by wmoreno3** [comment]
Thanks for answer me.

File `/usr/local/share/cacti/lib/functions.php` edited

```
                /* average time */
                cacti_log("The ping time is: $ping_time");
                $hosts[$host_id]['avg_time'] = (($hosts[$host_id]['total_polls']-1-$hosts[$host_id]['failed_polls'])
                        * $hosts[$host_id]['avg_time'] + $ping_time) / ($hosts[$host_id]['total_polls'] - $hosts[$host_id]['failed_polls']);

```

log out just after add the line `cacti_log("The ping time is: $ping_time");` that you requested me

```
2017-05-06 15:40:00 - CMDPHP The ping time is: down
2017-05-06 15:40:00 - ERROR PHP WARNING: A non-numeric value encountered in file: /usr/local/share/cacti/lib/functions.php  on line: 894
2017-05-06 15:40:00 - CMDPHP PHP ERROR WARNING Backtrace: (/cmd.php: 449 update_host_status)(/lib/functions.php: 894 CactiErrorHandler)(/lib/functions.php: 4297 cacti_debug_backtrace)
2017-05-06 15:40:01 - SYSTEM STATS: Time:1.2401 Method:cmd.php Processes:1 Threads:N/A Hosts:1 HostsPerProcess:1 DataSources:6 RRDsProcessed:6
```

My default language is Latin Spanish but my FreeBSD Server is en_US

```
root@server:~ # ping -t 1000 -c 3 hostname
PING hostname (192.168.0.6): 56 data bytes
64 bytes from 192.168.0.6: icmp_seq=0 ttl=64 time=0.026 ms
64 bytes from 192.168.0.6: icmp_seq=1 ttl=64 time=0.055 ms
64 bytes from 192.168.0.6: icmp_seq=2 ttl=64 time=0.052 ms

--- hostname ping statistics ---
3 packets transmitted, 3 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.026/0.044/0.055/0.013 ms
root@server:~ #
root@server:~ # uname -a
FreeBSD hostname 11.0-RELEASE-p10 FreeBSD 11.0-RELEASE-p10 #2: Mon May  1 16:45:25 COT 2017     root@hostname:/usr/obj/usr/src/sys/TCPOPEN  amd64
root@server:~ #

```
`root@server:~ # cat test.php
<?php print PHP_OS . "\n";?>`
`root@server:~ # php test.php
FreeBSD
root@server:~ #`

P.S. hostname == myhost.mydomain

**Comment by cigamit** [comment]
Reopening.

**Comment by cigamit** [comment]
Okay, so I'm fixing the warning message, but if the host is reported as down when it's still up, open a new ticket.  We will start kind of where we left off.
