### ISSUE TITLE
Scheduled reports (type "tree") not working

### ISSUE THREAD

**Issue by komathodivijay** [Cacti/cacti#658]
Hi,
I have installed Cacti v1.1.2, Tree reports are now working( Resolving Issue #524). i am able to get the email when i press on send report with full graphs (thumbnails) but when the report is set to scheduled i still get the email but no graphs inline. I have tried inline png/jpg/gif and attached as well, all not working. I just get the email but no content inline/attached (empty mail).

Cacti Log show no information related to mail sent.

**Comment by cigamit** [comment]
Try using png.  Also, there are some fixes in 1.1.6 that may impact this

**Comment by cigamit** [comment]
You culd be hitting the size limit setting in the Mail settings too.

**Comment by komathodivijay** [comment]
I have tried both option. But no luck.  I'am just get the email but no content inline/attached (empty mail).

**Comment by komathodivijay** [comment]
Pls let us know any workaround to fix this issue.

**Comment by komathodivijay** [comment]
I should update  Cacti v1.1.2, to Cacti v1.1.6 to resolve this issue? . Pls confirm

**Comment by The-Mafioso** [comment]
Even with 1.1.6 i tested and its not working

**Comment by komathodivijay** [comment]
cigamit - is there anyway to sorted out this issue.??

**Comment by cigamit** [comment]
I've got only a few hours today.  Prioritizing my list now.

**Comment by cigamit** [comment]
Please upload an image of the General tab.  I need to see that, as this is working in my setup, and I need to see the General settings from your perspective to reproduce.

**Comment by cigamit** [comment]
Also, send me the output of 'php -m'.  Likely not the issue, but just in case.

**Comment by The-Mafioso** [comment]
[PHP -M.txt](https://github.com/Cacti/cacti/files/998779/PHP.-M.txt)
![untitled](https://cloud.githubusercontent.com/assets/27900099/26027195/657dd03c-3812-11e7-8f5a-88a52eb8cb4f.png)
![gen01](https://cloud.githubusercontent.com/assets/27900099/26027229/030f6144-3813-11e7-841e-93eb20d3b525.png)
![gen02](https://cloud.githubusercontent.com/assets/27900099/26027230/0310e01e-3813-11e7-8413-8bf299f5ae5d.png)
![gen03](https://cloud.githubusercontent.com/assets/27900099/26027231/0312183a-3813-11e7-8427-693e28d33ff9.png)
![gen04](https://cloud.githubusercontent.com/assets/27900099/26027232/0312ea08-3813-11e7-820e-b35967ef1c57.png)

**Comment by The-Mafioso** [comment]
cigamit, i can even provide you access to the platform if needed

**Comment by komathodivijay** [comment]
![1](https://cloud.githubusercontent.com/assets/26949629/26031388/afb09c62-388e-11e7-80d4-60e3f0258a66.JPG)
![2](https://cloud.githubusercontent.com/assets/26949629/26031389/b191e8e2-388e-11e7-93f8-fbb1d28431a9.JPG)
![3](https://cloud.githubusercontent.com/assets/26949629/26031392/b6dc1822-388e-11e7-8863-788849b98199.JPG)
[php output.txt](https://github.com/Cacti/cacti/files/999107/php.output.txt)

**Comment by cigamit** [comment]
My bad.  I need the main reporting page showing all the reports, and the Details tab in it's entirety.

**Comment by The-Mafioso** [comment]
No worries, Here you go. I hope you can help us resolve it even with a workaround 

![rep 01](https://cloud.githubusercontent.com/assets/27900099/26035358/817c010c-38d3-11e7-9321-98366fad23e8.png)
![rep 02](https://cloud.githubusercontent.com/assets/27900099/26035359/835bedca-38d3-11e7-98ab-beda4276249b.png)
![item](https://cloud.githubusercontent.com/assets/27900099/26035362/881f65e4-38d3-11e7-81ac-70ca819aee47.png)
![item details](https://cloud.githubusercontent.com/assets/27900099/26035364/8caf76bc-38d3-11e7-9928-b9199abf566b.png)
![preview](https://cloud.githubusercontent.com/assets/27900099/26035366/901c3f74-38d3-11e7-9e9e-5e8d125756fa.png)

**Comment by cigamit** [comment]
Since you are online, please update the following files, and test again right away:

include/global_constants.php
include/global_arrays.php
reports_user.php
reports_admin.php
lib/reports.php
lib/html_reports.php
lib/functions.php

Let us know.  For sure the 'Last Sent' should work.  I believe you should get data.  Note, that a report now owned by a user who has been deleted will be disabled.  If that is the case, you will have to take ownership of the report for it to show any data.

**Comment by The-Mafioso** [comment]
update the files above by downloading them from the development section?

**Comment by The-Mafioso** [comment]
I have downloaded the files from development section and replaced them. But still same behavior. Email received but no graphs 
![report](https://cloud.githubusercontent.com/assets/27900099/26035971/0921dc6c-38de-11e7-9c91-0f57d8bf2b54.png)
![preview](https://cloud.githubusercontent.com/assets/27900099/26035972/0bc1e7f0-38de-11e7-8a14-0dabeedff4a2.png)
![mail](https://cloud.githubusercontent.com/assets/27900099/26035975/1b3354c6-38de-11e7-9466-376b56298140.png)

**Comment by The-Mafioso** [comment]
I did a debug on mysql and please check the log below, maybe its the reason:
**4455 Query     SELECT id  FROM graph_tree_items   WHERE parent = '2'   AND host_id = 0 AND local_graph_id = 0  AND graph_tree_id = '2'  ORDER BY position**
4455 Query     SELECT cacti FROM version
4455 Query     SELECT value FROM settings WHERE name = 'settings_smtp_timeout'
4457 Query     SELECT pc.id, ph.name, ph.file, ph.function  FROM plugin_hooks AS ph  LEFT JOIN plugin_config AS pc  ON pc.directory = ph.name  WHERE ph.status = 1 AND hook = 'config_insert'  ORDER BY id ASC
4455 Query     SELECT value FROM settings WHERE name = 'settings_how'
4455 Query     SELECT value FROM settings WHERE name = 'settings_smtp_host'
4455 Query     SELECT value FROM settings WHERE name = 'settings_smtp_port'
4455 Query     SELECT value FROM settings WHERE name = 'settings_smtp_username'
4455 Query     SELECT value FROM settings WHERE name = 'settings_smtp_password'
4455 Query     SELECT value FROM settings WHERE name = 'settings_smtp_secure'
4455 Query     SELECT value FROM settings WHERE name = 'settings_wordwrap'

**Comment by The-Mafioso** [comment]
The line in bold returns empty set  in the database as the parent is always Zero, please see the output below:
**mysql> SELECT id  FROM graph_tree_items   WHERE parent = '2'   AND host_id = 0 AND local_graph_id = 0  AND graph_tree_id = '2'  ORDER BY position;
Empty set (0.00 sec)**


mysql> select * from graph_tree_items;
+----+--------+----------+---------------+----------------+-------+---------+---------+--------------------+--------------------+-------------+------------+
| id | parent | position | graph_tree_id | local_graph_id | title | host_id | site_id | host_grouping_type | sort_children_type | graph_regex | host_regex |
+----+--------+----------+---------------+----------------+-------+---------+---------+--------------------+--------------------+-------------+------------+
|  1 |      0 |        1 |             1 |              0 |       |       1 |       0 |                  1 |                  1 |             |            |
|  2 |      0 |        1 |             2 |              0 |       |       2 |       0 |                  1 |                  1 |             |            |
+----+--------+----------+---------------+----------------+-------+---------+---------+--------------------+--------------------+-------------+------------+

**Comment by cigamit** [comment]
Well, that is interesting.  Can you remove that branch, and re-add it to the report.  When doing so, do you still get the same query?

**Comment by cigamit** [comment]
Either way, I fixed a number of issues.  Digging into this further now.

**Comment by cigamit** [comment]
I think you nailed it.  Just checking now.

**Comment by The-Mafioso** [comment]
cigamit , Ok i think your changes made some modifications, please see below the mysql query, The host is incorrect though 

mysql> SELECT id  FROM graph_tree_items   **WHERE parent = '0'**   AND **host_id = 0** AND local_graph_id = 0  AND graph_tree_id = '2'  ORDER BY position;

![table](https://cloud.githubusercontent.com/assets/27900099/26036377/2e54cca4-38e5-11e7-86ef-6fcabfba3f55.png)
The host should be 1 or 2 instead of Zero

**Comment by cigamit** [comment]
Send me a screen show of your Report Items screen and a screen shot of your Graph tree's 1 and 2.

**Comment by The-Mafioso** [comment]
![report item](https://cloud.githubusercontent.com/assets/27900099/26036436/4a1cbe96-38e6-11e7-96a0-bfd948429993.png)
![graphs](https://cloud.githubusercontent.com/assets/27900099/26036437/4ccd9a34-38e6-11e7-8907-027f4acbaf05.png)

**Comment by cigamit** [comment]
I just updated lib/reports.php.  Please update, and run again.

**Comment by The-Mafioso** [comment]
Preview as well:
![preview](https://cloud.githubusercontent.com/assets/27900099/26036444/90a97962-38e6-11e7-8fb7-834f538dc78e.png)

**Comment by The-Mafioso** [comment]
SELECT id  FROM graph_tree_items   **WHERE parent = '2'**   AND local_graph_id = 0  AND graph_tree_id = '2'  ORDER BY position;

Parent changed to number two, also the email was not sent at all

**Comment by The-Mafioso** [comment]
mysql> SELECT id  FROM graph_tree_items   WHERE parent = '2'   AND local_graph_id = 0  AND graph_tree_id = '2'  ORDER BY position;
Empty set (0.00 sec)

**Comment by The-Mafioso** [comment]
I just tried the file you uploaded 12 minutes ago lib/reports.php. But still same issue No email/Parnet show as value 2

The SMTP lines disappeared


4566 Query     SELECT id  FROM graph_tree_items   WHERE parent = '2'   AND local_graph_id = 0  AND graph_tree_id = '2'  ORDER BY position
4566 Query     SELECT value    FROM settings_user    WHERE name = 'first_weekdayid'    AND user_id = '1'
4566 Query     SELECT value FROM settings WHERE name = 'log_destination'
4566 Query     SELECT value FROM settings WHERE name = 'path_cactilog'
4566 Quit

**Comment by The-Mafioso** [comment]
These errors as well appear in the log:

![error](https://cloud.githubusercontent.com/assets/27900099/26036741/34274cd6-38ec-11e7-852b-d806340668bf.png)

**Comment by cigamit** [comment]
You have to update lib/functions.php again.  There are other changes going on.  I also just updated lib/reports.php.  I was able to reproduce your simple case.  Sometimes the simplest cases cause all the to be reported bugs.

**Comment by The-Mafioso** [comment]
ok will try it now

**Comment by The-Mafioso** [comment]
![untitled](https://cloud.githubusercontent.com/assets/27900099/26036979/2f905e82-38f2-11e7-978c-9147dd4bf7fd.png)

**Comment by cigamit** [comment]
Goto the bottom of lib/functions.php, if you don't see a function called get_cacti_version(), please update your lib/functions.php.

**Comment by The-Mafioso** [comment]
It is there 

/** get_cacti_version    Generic function to get the cacti version */
function get_cacti_version() {
        static $version = '';

        if ($version == '') {
                $version = trim(db_fetch_cell('SELECT cacti FROM version LIMIT 1'));
        }

        return $version;
}

**Comment by The-Mafioso** [comment]
but still the email is blank, as per before. Same log from mysql (parent is fixed but host_id is zero)

SELECT id  FROM graph_tree_items   WHERE parent = '0'   AND host_id = 0  AND local_graph_id = 0  AND graph_tree_id = '2'  ORDER BY position

**Comment by cigamit** [comment]
That query is a red herring.  It happens after the device graphs are processed.  I've got what I think is your setup now, and still can not reproduce.

**Comment by The-Mafioso** [comment]
i can provide direct access to my setup for testing if that will help

**Comment by cigamit** [comment]
Nope, and you did not attach a screen shot of reports page.

**Comment by The-Mafioso** [comment]
cigamit, please find below all screenshots as well as graph tree screenshot 
![report](https://cloud.githubusercontent.com/assets/27900099/26037884/f0fee13e-3905-11e7-803b-b5a5a2aed60c.png)
![rep det](https://cloud.githubusercontent.com/assets/27900099/26037885/f4c23e74-3905-11e7-85bc-60e6f4ee1113.png)
![item](https://cloud.githubusercontent.com/assets/27900099/26037886/f7b57bc8-3905-11e7-97ed-1f739cda086b.png)
![item det](https://cloud.githubusercontent.com/assets/27900099/26037887/fb321522-3905-11e7-9665-b1a8b54f2d7b.png)
![tree](https://cloud.githubusercontent.com/assets/27900099/26037889/ff8a407c-3905-11e7-9ef5-c5e03750f34e.png)

**Comment by The-Mafioso** [comment]
Hi cigamit, I think there is a misunderstanding here and i think i know now the reason for this issue. The Tree in my case has no graph directly listed under it (check screenshot below). I have devices added directly under the tree as per the Management --> Tree Output below.
![tree](https://cloud.githubusercontent.com/assets/27900099/26040950/1923fc7c-3932-11e7-9c84-66a8b4e5dddc.png)


![mgmt tree](https://cloud.githubusercontent.com/assets/27900099/26040974/44ee878c-3932-11e7-9dff-ee537c767b3f.png)

**Comment by The-Mafioso** [comment]
So when i receive the email, its blank cause the Tree its self is empty and it doesn't send the cascaded devices.
I have tested my theory by adding graphs directly under the tree as well as a device using the same rule item i shared earlier in which i select all and cascade. the email arrived with only the graphs listed directly under the tree but not the device graphs

![test tree](https://cloud.githubusercontent.com/assets/27900099/26041049/cd9f0b4c-3932-11e7-995b-0ed042b317fa.png)
![item det](https://cloud.githubusercontent.com/assets/27900099/26041069/f4feb91c-3932-11e7-8883-f8feebce926d.png)

**Comment by cigamit** [comment]
My setup explicitly adds a single device with a single graph to a single tree, and the graph within the device renders properly.  For the report user, can you goto the User Management page filter on this devices graphs and post the content of the Graph Permissions page.

**Comment by The-Mafioso** [comment]
Here you go, please do let me know if any other screenshots are needed
![device permission](https://cloud.githubusercontent.com/assets/27900099/26043832/140e6256-3949-11e7-81f3-316ed33e3562.png)
![graph permission](https://cloud.githubusercontent.com/assets/27900099/26043834/14185680-3949-11e7-8a83-4fd96e59ce43.png)
![permissions](https://cloud.githubusercontent.com/assets/27900099/26043833/14167b4e-3949-11e7-87d9-8be3f212481e.png)

**Comment by The-Mafioso** [comment]
cigamit , where you able to replicate the issue

**Comment by cigamit** [comment]
No, I'm using the exact setup as yours and can not reproduce.  A Device is considered a branch, so you must Cascade to all Branches to get Device graphs.  Which through your screen shot, you checked.  I would say just wait till 1.1.7 this coming weekend.  It 'should' be fixed.  If there are no errors in your log, I would expect something in your environment is missing.

**Comment by The-Mafioso** [comment]
Hi cigamit, i have tried the cacti-development ver 1.1.7 and still the same issue exists. When i press on send reports (for a Tree report) i get the email with graphs. If i schedule it and wait till the time comes the email is received but blank with only the report name appearing

**Comment by cigamit** [comment]
Okay, going to look to the permissions api for effective user.  I am guessing the real issue is there.  There have been some optimizations.  Maybe something got optimized out.

**Comment by cigamit** [comment]
Test again, I made the GUI user the owner.  So, if it does not render via the GUI this time, then change the owner to your user.

**Comment by The-Mafioso** [comment]
It working thanks alot ::
