### ISSUE TITLE
[DEV - classic skin] Textarea placed over next row

### ISSUE THREAD

**Issue by reboot1983** [Cacti/cacti#659]
OS: Windows 10
Browser: Chrome 58.0.3029.96 (64-bit)

In the current develop branch the textarea is placed over the next row for the classic skin.

![image](https://cloud.githubusercontent.com/assets/20405704/25771393/de372686-324f-11e7-8c99-ca8eff2aaf6f.png)

**Comment by cigamit** [comment]
Argh.

**Comment by cigamit** [comment]
What browser version?  I can not reproduce.  Can you reload the css?

**Comment by reboot1983** [comment]
As mentioned:
OS: Windows 10
Browser: Chrome 58.0.3029.96 (64-bit)

BTW: Same thing on Mac OS X with Chrome AND Safari

![schermafbeelding 2017-05-06 om 13 16 15](https://cloud.githubusercontent.com/assets/20405704/25771906/4cf93556-325e-11e7-9fd0-60be9148d72a.png)

**Comment by cigamit** [comment]
Okay, reproduced now.  I had the inline help hidden.

**Comment by cigamit** [comment]
Resolved.
