### ISSUE TITLE
SNMP.php filtering of Hex-string on snmp_get to picky

### ISSUE THREAD

**Issue by arno-st** [Cacti/cacti#665]
Hi,
With the latest 1.1.6 I have an issue on format_snmp_string
Before this function my snmp_value is: Hex-STRING: 00 00 02 29
then after it its: string(0) ""

and the snmpget value is the following:
[root@:/usr/share/cacti-1/plugins/linkdiscovery] # snmpget -c telvlsn -v2c se-v.ch .1.3.6.1.4.1.9.9.23.1.2.1.1.9.63.33
SNMPv2-SMI::enterprises.9.9.23.1.2.1.1.9.63.33 = Hex-STRING: 00 00 02 29 

I track down the problem to here (inside function format_snmp_string($string, $snmp_oid_included). line 871 ):
		if (is_numeric($output)) {
			$string = number_format($output, 0, '', '');
		} else {
			$string = $output;
		}

before I have:
SNMP queries hex3: 00:00:02:29
and after
SNMP queries hex4: 
string(0) ""

**Comment by arno-st** [comment]
To be more precise here is my debuginput:
print "SNMP queries hex2: ". $string ."\n";
                /* convert the hex string into an ascii string */
                foreach($parts as $part) {
                        if ($mac == false) {
                                if ($part == '00') break;

                                $output .= chr(hexdec($part));
                        } else {
                                $output .= ($output != '' ? ':' : '') . $part;
                        }
                }
print "SNMP queries hex3: ". $string. "- " .$output. "\n";

                if (is_numeric($output)) {
print "SNMP queries num: ". $string ."\n";
                        $string = number_format($output, 0, '', '');
                } else {
                        $string = $output;
                }
print "SNMP queries hex4: ". $string ."\n";

and the output:
SNMP queries hex2: 00:00:02:29
SNMP queries hex3: 00:00:02:29 
SNMP queries hex4: 
string(0) ""


so the error come on the $string = $output
since $output is empty after the first return from the snmp queries
I think it's due of the break on the foreach loop after the first part is seeing as '00' (line 863)

**Comment by cigamit** [comment]
What do you expect the numeric output to be for this item?

`00:00:02:29`

Sorry about this one.  For the near term, just grab the 0.8.8h format_snmp_string() function.  This issue has been a problem for a little while.  There are two right answers, and some people want the first, and some the second....  I think I know the compromise, just have not coded it yet.  Thanks!

**Comment by arno-st** [comment]
Well the problem here is that you drop the whole string with this part:
if ($part == '00') break; // out of the loop, and $output is null
So later on  $string=$output, is null, instead of something

And for your answer, I just need a value, at least : 02:29 I don't care about the first '00:00' but I need something !
And I'm sure everyone will agree that a some point if a value is read, a value has to be return. then everyone who make a plugin has to handle the value as it need. Cacti can't just drop the value because it doesn't fix it's need. If I may speak like that !

**Comment by arno-st** [comment]
By the way you just drop the whole string when you find a 00, that mean reading any kind of value in hex can give a 00 in middle:
ipv6
ipv4 
Mac adress
in cdp equipment type (you should have some trouble with discovery plugin in that case)

And it' can't be right  to return just null in that case, i can't find any reason to do so!

**Comment by cigamit** [comment]
There have been two paths on this one over the years.  The original fix was for a Data Query that was obtaining actual Hex Strings where the string simply needed to be converted from Hex to ASCII.  However, this broke polling, where the Hex value needed to be converted to numeric data.  So, the check for '00' in a Hex String being a short circuit for a bogus string, or the end of one, is valid if it's ASCII, but the same test fails horribly if it needs to be converted to a number.

**Comment by arno-st** [comment]
And is that solving the issue:
$string = ($ouput==null)?$string:$output;

So if you drop the string because of '00', at least you store 'as is' into the output string, and let the end 'user' doing his stuff , and if it has a valid value you just store it and return it correctly?

but I have to admit, I don't know how it's handle on other place of cacti, neither on other plugin, if it return something 'as is' instead of a null in case of bad value; even if it's not bad value, just a value with a 00 on it

I will try to make some test on cacti with this idea, at least for me it works

**Comment by arno-st** [comment]
No dosen't work with just
$string = ($output==null)?$string:$output;
Since when I getting the IP address from CDP, it's replied with 0A 00 64 2E
So the break inside the foreach loop just get out after the 0A, and since $outpuit is not empty, I have only 0A into $string, instead of 0A:00:64:2E


So for now I will use my special snmp.php and just add a format_snmp_string taken from 0.8.8h!

**Comment by cigamit** [comment]
You still did not answer the original question, what numeric output would you expect from your example above?

**Comment by arno-st** [comment]
The Hex value: like that 00:00:02:29 or 0A:00:64:2E

I will adapt my code on whatever cacti will return, if it's decimal, it fine by me too.
Has for the separator anything will fit my need.
Like I said, return something valid, that mean reflect in any way what net-snmp return, and I will manage to extract what I need.
And I just hope it will stay stable between release !!

**Comment by cigamit** [comment]
Create a pull request.  That will help.

**Comment by cigamit** [comment]
I'm going to mark this closed.  Eventually, we are going to add two more options to the SNMP functions as follows:

1) Option to request output of HEX, for developers who wish to force HEX output.  Make this an input option for Data Query XML as well.
2) Built in behavior to not sanitize the 'walk' functions as they are primarily used for Data Query's, as we often times optimize out valuable information.
