### ISSUE TITLE
Validation error when you do "Change Graph Template" in Cacti-1.1.6

### ISSUE THREAD

**Issue by kaf3773** [Cacti/cacti#670]
I upgraded to Cacti-1.1.6 and from graphs.php screen when you hit "Go" for Change Graph Template the below error shows up

`Choose a Graph Template and click 'Continue' to change the Graph Template for the following Graph(s). Please note, that only compatible Graph Templates will be displayed. Compatible is identified by those having identical Data Sources.`

`ROUTER-C9001-1 - Traffic - BVI2233
New Graph Template
Validation error for variable template_id, with value of "cg_79". See backtrace below for more details.
(/graphs.php: 76 form_actions)(/graphs.php: 832 get_filter_request_var)(/lib/html_utility.php: 423 die_html_input_error)(/lib/html_validate.php: 60 cacti_debug_backtrace)`

Below is also a screen shot

![image](https://cloud.githubusercontent.com/assets/16928454/25824767/7e7dab00-340e-11e7-9e36-07e7fc8cb6c8.png)

**Comment by cigamit** [comment]
Yea, darn.

**Comment by cigamit** [comment]
Resolved, thanks for testing.

**Comment by kaf3773** [comment]
I am getting some issues after testing Cacti-1.1.7. I get the below after hitting "Go" to change the graph template

No graph templates are populated in the New Graph Template dialogue box indicated by red arrow

![image](https://cloud.githubusercontent.com/assets/16928454/26259976/87e2a78e-3c99-11e7-8b6b-ac12a8dded6f.png)

here is the URL i see

`http://IP_Address/new_cacti/graphs.php?host_id=15&rows=-1&page=1&rfilter=&template_id=dq_14&`
