### ISSUE TITLE
Error upgrading from 1.1.3 to 1.1.6 - Invalid version

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#671]
![image](https://cloud.githubusercontent.com/assets/12864741/25830531/bbe06c88-341a-11e7-9e33-33cca8a1afc5.png)

**Comment by eschoeller** [comment]
![image](https://cloud.githubusercontent.com/assets/12864741/25830814/e20ec3ee-341c-11e7-94a5-d16756145ee1.png)
Not really sure what the issue could be here ...

**Comment by eschoeller** [comment]
Somehow I got through this ... I hard-coded the $old_cacti_version variable (which didn't really fix it) but then made another debugging adjustment somewhere else to see where the code was failing, and it worked. Then I upgraded from 1.1.4 to 1.1.6, but none of the DB commands were executed. What is the best procedure to re-run the 1_1_6.php script which didn't appear to run?

**Comment by cigamit** [comment]
Have you tried the upgrade_database.php script?  You can say re-upgrade from 1.1.3 in that script.

**Comment by ronytomen** [comment]
@eschoeller Can you provide me with the mysql output of the following command executed in the mysql client while using the Cacti database?

```SQL
"SHOW CREATE TABLE `version`;
```

I'm wondering if there is an encoding issue that maybe adding multibyte characters or some oddity around the version string.

**Comment by ronytomen** [comment]
I added some "fixes" around this, I think I know what is happening, but I can not reproduce what you are seeing.

**Comment by eschoeller** [comment]
I might not be able to check on this for a couple of days, but I'll get back to you. Thanks for looking into it!!

**Comment by eschoeller** [comment]
mysql> SHOW CREATE TABLE `version`;
+---------+-------------------------------------------------------------------------------------------------+
| Table   | Create Table                                                                                    |
+---------+-------------------------------------------------------------------------------------------------+
| version | CREATE TABLE `version` (
  `cacti` char(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 |
+---------+-------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

**Comment by ronytomen** [comment]
If you are still experiencing this issue, please let me know!
