### ISSUE TITLE
Downtime/Recovery time/date is set wrong

### ISSUE THREAD

**Issue by thurban** [Cacti/cacti#673]
---

Seems like this is by purpose to only record the initial fail/recovery date. So closed this issue

---
In Line 818 of lib/functions.php ( https://github.com/Cacti/cacti/blob/develop/lib/functions.php#L818 ) it should read
`if ($hosts[$host_id]['status_event_count'] == $ping_failure_count ) {`
instead of
`if ($hosts[$host_id]['status_event_count'] == 1 ) {`

The code will nevery be called if $ping_failure_count is anything else then 1 due to the previous if statement.

The same is true for line 918 ( https://github.com/Cacti/cacti/blob/develop/lib/functions.php#L918)
where it should be
`if ($ping_recovery_count == $ping_recovery_count) {`
instead of
`if ($ping_recovery_count == 1) {`

**Comment by cigamit** [comment]
Thomas,  Why did you close?

**Comment by thurban** [comment]
Because I need to think about it more thoroughly. Somehow the code doesn't look "right".

In my case I have set the ping failure count to 1. In that case the else statements are never called, but the first if ( even_count >= failure count) is being called and then it will go into that if statement setting the failure_date.

If the ping failure count is something else, e.g. 3, then it will first (event_count=1) go into the else statement, setting the initial failure_date with the first event_count. Once the event_count will be 3, it will go into the first if and not reset the failure_date (due to the "event_count == 1").

Now in both cases it will set the failure_date, but it is redundant code and the else statement wouldn't be required at all,

Why not just have it this way:

```
/* determine if to send an alert and update remainder of statistics */
if ($hosts[$host_id]['status'] == HOST_UP) {
	/* increment the event failure count */
	$hosts[$host_id]['status_event_count']++;
	/* if it's time to issue an error message, indicate so */
	if ($hosts[$host_id]['status_event_count'] >= $ping_failure_count) {
		/* host is now down, flag it that way */
		$hosts[$host_id]['status'] = HOST_DOWN;
		$issue_log_message = true;
	/* host is down, but not ready to issue log message */
	}
	if ($hosts[$host_id]['status_event_count'] == 1) {
		$hosts[$host_id]['status_fail_date'] = date('Y-m-d H:i:s');
	}
/* host is recovering, put back in failed state */

```

**Comment by thurban** [comment]
... unless the original thinking was to set the failure_date only at the very last event_count, then the 1 should be $ping_failure_count in that last if ....

**Comment by thurban** [comment]
This is more for discussion, not a real issue.

**Comment by cigamit** [comment]
Okay, I finally had some time to review this, and I believe your initial perspective was the right one.  If someone want's the first date to be a 'down' condition, they should set the value to 1.  So, I'll be committing the original requested patch.

**Comment by cigamit** [comment]
Resolved.
