### ISSUE TITLE
1.1.6: api_plugin_hook_function('device_remove', $devices_to_act_on) empty param

### ISSUE THREAD

**Issue by arno-st** [Cacti/cacti#675]
My plugin need to be called when a device(s) is removed from cacti, but the call of 
api_plugin_hook_function('device_remove', $devices_to_act_on)

give an empty argument, instead of the list of device removed.
So I have a call of my hook, but no reference of any hosts

cacti_log("device: ". $selected_item, false, "MAP" ); // last line inside the foreach
2017-05-09 11:49:24 - MAP device: 9100
2017-05-09 11:49:24 - MAP device: 9101

cacti_log("devices: ". var_dump($devices_to_act_on), false, "MAP" ); // just after of the foreach
2017-05-09 11:49:24 - MAP devices:

**Comment by arno-st** [comment]
Well no so sure actually !
My hook function is:
function map_device_remove( $hosts_id ){
	//array(1) { [0]=> string(4) "1921" } device remove : 
	foreach( $hosts_id as $host_id) {
		map_log( "remove host: " . $host_id . "(".count($hosts_id).")" );
	}

	return;
}

and I got an error:
2017-05-09 13:16:38 - ERROR PHP WARNING in  Plugin 'map': Invalid argument supplied for foreach() in file: /usr/share/cacti-1/plugins/map/setup.php  on line: 356

But can't find why it give me an error for the argument

**Comment by cigamit** [comment]
A few things:

1) Always check the sizeof() on the array before you act on it.  It might have zero length which generates this warning.
2) Any plugin call that is made, you MUST return the passed array at at the end of the function, or the next plugin won't get it's copy of the array.

Relative to your case, the function would look better as follows:

`function map_device_remove( $hosts ) {
     if (sizeof($hosts)) {
        foreach( $hosts as $host_id) {
            map_log( "remove host: " . $host_id . "(".count($hosts_id).")" );
        }
    }
    return $hosts;
}`
