### ISSUE TITLE
Cacti 1.1.2  High CPU usages - RHEL 7.3

### ISSUE THREAD

**Issue by Kallyx** [Cacti/cacti#677]
Hello,
Please help if possible with below issue. Thank you!

Initial data:

Cacti 1.1.2; pooling interval 5 min.
Only 4 elements added to monitor + the VM on which cacti is running;
Method:spine Processes:1 Threads:1 Hosts:5 HostsPerProcess:5 DataSources:123 RRDsProcessed:88 
High CPU usages after added to monitor some more interfaces on one of NEs
The method Cacti will use to determine if a host is available for polling. SNMP uptime

**OS RHEL 7.3** 
Installed software:
MariaDB-server-10.1.22
php-5.4.45
net-snmp-devel-5.7.2-24.el7_2.1.x86_64
net-snmp-utils-5.7.2-24.el7_2.1.x86_64
php-snmp-5.4.45-13.el7.remi.x86_64
net-snmp-libs-5.7.2-24.el7_2.1.x86_64
net-snmp-agent-libs-5.7.2-24.el7_2.1.x86_64
net-snmp-5.7.2-24.el7_2.1.x86_64
httpd-2.4.6-45
rrdtool-1.4.8

VM# ps -eo pcpu,pid,user,args | sort -k1 -r | head -10
%CPU   PID      USER     COMMAND
99.8      27879 root     /bin/php -q /var/www/html/cacti/poller_automation.php -M
 0.8       6883   mysql    /usr/sbin/mysqld
 0.2       8016   apache   /usr/sbin/httpd -DFOREGROUND
 0.1       7966   apache   /usr/sbin/httpd -DFOREGROUND
 0.1       7952   apache   /usr/sbin/httpd -DFOREGROUND

VM# top
top - 14:49:27 up 20 days,  1:21,  2 users,  load average: 1.07, 1.23, 1.22
Tasks: 122 total,   3 running, 119 sleeping,   0 stopped,   0 zombie
%Cpu(s): 34.2 us, 16.0 sy,  0.0 ni, 49.8 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  1883608 total,   909068 free,   443896 used,   530644 buff/cache
KiB Swap:  2097148 total,  2097148 free,        0 used.  1203828 avail Mem

  PID USER        PR  NI    VIRT    RES        SHR S    %CPU   %MEM     TIME+ COMMAND
27879 root       20   0  330936  21764   8664 R  100.0     1.2          8603:18 php
 6883 mysql      20   0 2534252 247928  11884 S   0.3 13.2   0:19.52 mysqld
    1 root           20   0  125244   3736   2452 S   0.0  0.2   1:09.25 systemd
    2 root           20   0       0      0      0 S   0.0  0.0   0:00.17 kthreadd

VM# more /var/log/messages
May  7 03:50:01 aasvcac01 systemd: Started Session 5506 of user root.
May  7 03:50:01 aasvcac01 systemd: Starting Session 5506 of user root.
May  7 03:55:01 aasvcac01 systemd: Started Session 5507 of user root.
May  7 03:55:01 aasvcac01 systemd: Starting Session 5507 of user root.
May  7 04:00:01 aasvcac01 systemd: Started Session 5508 of user root.
May  7 04:00:01 aasvcac01 systemd: Starting Session 5508 of user root.
May  7 04:01:01 aasvcac01 systemd: Started Session 5509 of user root.
May  7 05:00:01 aasvcac01 systemd: Started Session 5521 of user root.
May  7 05:00:01 aasvcac01 systemd: Starting Session 5521 of user root.
May  7 05:01:01 aasvcac01 systemd: Started Session 5522 of user root.
May  7 05:01:01 aasvcac01 systemd: Starting Session 5522 of user root.
May  7 05:05:01 aasvcac01 systemd: Started Session 5523 of user root.
May  7 05:05:01 aasvcac01 systemd: Starting Session 5523 of user root.
May  7 05:10:01 aasvcac01 systemd: Started Session 5524 of user root.
May  7 05:10:01 aasvcac01 systemd: Starting Session 5524 of user root.
May  7 05:15:01 aasvcac01 systemd: Started Session 5525 of user root.
May  7 05:15:01 aasvcac01 systemd: Starting Session 5525 of user root.
May  7 05:20:01 aasvcac01 systemd: Started Session 5526 of user root.
May  7 05:20:01 aasvcac01 systemd: Starting Session 5526 of user root.
May  7 05:25:01 aasvcac01 systemd: Started Session 5527 of user root.
May  7 05:25:02 aasvcac01 systemd: Starting Session 5527 of user root.
May  7 05:30:01 aasvcac01 systemd: Started Session 5528 of user root.
May  7 05:30:01 aasvcac01 systemd: Starting Session 5528 of user root.
May  7 05:35:01 aasvcac01 systemd: Started Session 5529 of user root.
May  7 05:35:01 aasvcac01 systemd: Starting Session 5529 of user root.
May  7 05:40:01 aasvcac01 systemd: Started Session 5530 of user root.
May  7 05:40:01 aasvcac01 systemd: Starting Session 5530 of user root.
May  7 05:45:01 aasvcac01 systemd: Started Session 5531 of user root.
May  7 05:45:01 aasvcac01 systemd: Starting Session 5531 of user root.
May  7 05:50:01 aasvcac01 systemd: Started Session 5532 of user root.

**Comment by Kallyx** [comment]
The CPU is high even I disabled the Network Elements added in cacti

VM ps -eo pcpu,pid,user,args | sort -k1 -r | head -10
%CPU   PID USER     COMMAND
99.8 27879 root     /bin/php -q /var/www/html/cacti/poller_automation.php -M

 ps -ef | grep poller_automation.php

root     27879     1 99 May03 ?        6-00:39:49 /bin/php -q /var/www/html/cacti/poller_automation.php -M

**Comment by cigamit** [comment]
Please strace the poller_automation using the following command:

strace -p <pid> -s 2500

Post the results.

**Comment by Kallyx** [comment]
Hi,

Thanks very much for answer, but since the system has run about 3 days with hight cpu, I have restarted the OS to solve the problem and the poller_automation is no longer hanged up now; The CPU is back again to normal rates.
If the issue will reoccur, I will raise another case to you. Thank you! 
# ps -eLf | grep poller_automation
root     14804 14254 14804  0    1 08:30 pts/0    00:00:00 grep --color=auto poller_automation

# strace -p 14254 -s 2500
Process 14254 attached
wait4(-1, ^CProcess 14254 detached
 <detached ...>

# ps -eo pcpu,pid,user,args | sort -k1 -r
%CPU   PID USER     COMMAND
 0.2  1424 mysql    /usr/sbin/mysqld
 0.1 14811 apache   /usr/sbin/httpd -DFOREGROUND
 0.1 14722 apache   /usr/sbin/httpd -DFOREGROUND
 0.1 14694 apache   /usr/sbin/httpd -DFOREGROUND
 0.1 14597 apache   /usr/sbin/httpd -DFOREGROUND
 0.1 14563 apache   /usr/sbin/httpd -DFOREGROUND
 0.0     9 root     [rcu_sched]

**Comment by cigamit** [comment]
Yea, I can see no reason why the master automation service would take 100%.  I even looked into the Database API and I could not find a tight loop in the current 1.1.7 code base.
