### ISSUE TITLE
cacti db access not compatible with PHP 7

### ISSUE THREAD

**Issue by mortenstevens** [Cacti/cacti#687]
Hello, 

it seems that db access is managed via PDO. But mysql is still required?

lib/data_query.php:
   $iv = mysql_real_escape_string($matches[1]);

So cacti is NOT compatible with PHP 7. After asking the PHP maintainer for Fedora, I guess we should use PDO::quote() instead.

**Comment by dsclassen** [comment]
What version of cacti are you using? I'm running php 7.0.19 and it works great.

**Comment by mortenstevens** [comment]
@dsclassen 
Yeah, it works great. I'm using the latest version. But I think we have to change that anyway to stay 100% compatible with PHP7.

By the way I'm maintaining the cacti package for Fedora and Fedora-EPEL.

**Comment by cigamit** [comment]
Wow, that was embarrassing.

**Comment by mortenstevens** [comment]
Thank you for the fast fix.
