### ISSUE TITLE
"Show Exceptions" in User groups functionality seems to be odd

### ISSUE THREAD

**Issue by thurban** [Cacti/cacti#688]
I was looking into the User Groups and wanted to allow a device/graph or tree to a user group, but I was unable to see any data at all. Only after i unchecked the "Show Exceptions" checkbox the devices/trees/graphs/templates are being displayed.

Although from a wording point this is ok, it still seems to be odd to hide everything as a default.

For a newbie this will be confusing.    Would a "Hide Default Permissions" be a better wording, so it automatically shows that there may be something hidden to the user ?

**Comment by cigamit** [comment]
Yea, I agree.  Should be a drop down -> 'All', 'Allowed', 'Denied'

**Comment by cigamit** [comment]
Pull requests are welcomed BTW.  Just make sure you handle all cases.

**Comment by cigamit** [comment]
Thomas, I'm going to leave this as is for the time being.  People will get used to it.
