### ISSUE TITLE
More often availability checking than getting datas for graphs

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#695]
I would like to check avability more often than getting datas for graphs.

I would see that as another option on "devices".
Check avability by 15/30/60/120/180....sec.

Maybe there should be another daemon for checking avability?

**Comment by cigamit** [comment]
Seems like this would be better off as a plugin.   I don't think that Cacti itself really needs this functionality in the core. 
If you want to check more often than your default poller, I would recommend adding a single graph to each host that checks at that interval.  It pretty much has the same effect.

**Comment by interduo** [comment]
Yes that is some workaround for this functionality.

I don't want to mess my db with unneeded graphs. I want to only check avability UP/DOWN. I don't want to add unneeded work for my poller,db and don't want to create unneeded i/o operations.

**Comment by cigamit** [comment]
Yes, then I would recommend a plugin be written for this.

**Comment by ronytomen** [comment]
We discussed this today in a development meeting and the conclusion is this should be a plugin.

**Comment by cigamit** [comment]
interduo, open this in the monitor plugin.  I think that should be where it belongs.  The development team had some good ideas on how this might be accomplished with something like nmap.
