### ISSUE TITLE
RE#672 cannot enable snmp trap notification mibs

### ISSUE THREAD

**Issue by MyOwnMediaHub** [Cacti/cacti#696]
After adding updated managers.php in regards issue 672 the warnings have gone which is a bonus but the notification mibs will still not enable, I have attached a screen shot.. If you select all on page and change drop down to enable then proceed the monitored status stays disabled. the mysql table will not populate either. this means that cacti will not send snmptraps if a threshold is breached., 
![cacti snmp notification receivers](https://cloud.githubusercontent.com/assets/28554247/26040380/3009ad8e-3968-11e7-81d3-825418b8d5c3.png)

**Comment by cigamit** [comment]
Fixed now.
