### ISSUE TITLE
[1.1.6] ERROR PHP WARNING: socket_shutdown(): unable to shutdown socket

### ISSUE THREAD

**Issue by hackdefendr** [Cacti/cacti#699]
This seems to happen when using SNMP Uptime and PING for monitoring device up/down status. More specifically, this is happening when using TCP PING.

`2017-05-16 16:15:03 - CMDPHP PHP ERROR WARNING Backtrace: (/cmd.php: 447 ping)(/lib/ping.php: 564 ping_tcp)(/lib/ping.php: 492 close_socket)(/lib/ping.php: 52 socket_shutdown)(CactiErrorHandler)(/lib/functions.php: 4308 cacti_debug_backtrace)`

`2017-05-16 16:15:03 - ERROR PHP WARNING: socket_shutdown(): unable to shutdown socket [107]: Transport endpoint is not connected in file: /var/www/html/cacti/lib/ping.php on line: 52`

`2017-05-16 16:15:03 - CMDPHP PHP ERROR WARNING Backtrace: (/cmd.php: 447 ping)(/lib/ping.php: 564 ping_tcp)(/lib/ping.php: 467 socket_connect)(CactiErrorHandler)(/lib/functions.php: 4308 cacti_debug_backtrace)`

`2017-05-16 16:15:03 - ERROR PHP WARNING: socket_connect(): unable to connect [115]: Operation now in progress in file: /var/www/html/cacti/lib/ping.php on line: 467 `

**Comment by cigamit** [comment]
Please test the latest lib/ping.php and provide feedback.

**Comment by hackdefendr** [comment]
Ok that backtrace went away, but now I see an issue with a script. I will post another issue with that since its another file.
