### ISSUE TITLE
Cacti 1.1.7  Graph Tab issue with Firefox when in Tree Mode.

### ISSUE THREAD

**Issue by ikorzha** [Cacti/cacti#700]
When I use Cacti 1.1.7 with the latest firefox, I get an incorrect page rendering when I click on Graphs tab.
I get one of the 2 pictures I have attached below, I have tested it on multiple machines with same result.
Other browsers seems not to be affected by this issue.

![firefox](https://cloud.githubusercontent.com/assets/11211789/26156186/89e9210a-3ae3-11e7-9b88-9c7f3d1dea73.jpg)

![firefox2](https://cloud.githubusercontent.com/assets/11211789/26156234/a8ab2f8e-3ae3-11e7-9efc-2d72c01de09e.jpg)

**Comment by reboot1983** [comment]
Duplicate: #667

**Comment by cigamit** [comment]
Resolved
