### ISSUE TITLE
SMTP Emailing failure if SMTP host does not respond to ping

### ISSUE THREAD

**Issue by iokiok** [Cacti/cacti#701]
I'm using Cacti 1.1.6 and my ISP SMTP server is fully working but it's configured so that it does not answer to ping requests.
I have configured Cacti to use SMTP to send emails because I have a very minimal Linux configuration that only runs essential services and no mail/sendmail binary is installed.
It seems that before contacting the SMTP server by the SMTP protocol, some script in Cacti tries to ping it and if the ping fails than it reports that "Message Not Sent due to ping failure".
I think that this behaviour is not correct because it's not uncommon that hosts on the internet do not respond to ping.

**Comment by click0** [comment]
See issues #662.
You are not alone with this problem.

**Comment by cigamit** [comment]
Resolved
