### ISSUE TITLE
GUI: devices.php

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#703]
Version: 1.1.6
Internet Browser: Firefox, Chrome.

Sometimes it drops to this situation.

![cacti-1](https://cloud.githubusercontent.com/assets/17087236/26196555/9b577d2e-3bbf-11e7-80f2-f2e74441989d.png)

**Comment by cigamit** [comment]
Yea, if you can find a way to fix this, you will get the prize.  Chrome has many rendering issues, just goto their bug tracker.

**Comment by cigamit** [comment]
This appears to be resolved in Chrome 60.0.3112.50.
