### ISSUE TITLE
GUI enhancement wanted for generating graphs not belonging to a certain device

### ISSUE THREAD

**Issue by gmuellerfr** [Cacti/cacti#704]
Hello,

I had to reopen issue #560, because the reimplemented functions don't work.

In order to test the never used function 'convert graph to template' I've tried to construct a new graph of this type from the scratch. While constructing a test graph I've found that I won't be supported by the GUI. This graph shouldn't belong to a specific device, because I want to compare different devices. So I have to create a graph with device=none, template=none. As I found out earlier #305 this is only possible in expert mode. 
When I hit the add-button, I've been faced with an empty page. First time, I've thought, that something went wrong. Second time, I've noticed that there is a scrollbar. I have to use the scrollbar to find the field for the name of the graph to create the graph. The huge empty area is replaced by an empty item list.
Now I have to add items to my graph. It's clear, that I have to pick the device from the drop-down list.
But when I want to add a legend or another data-source for the same device, first of all I must pick the device from the huge drop-down list. For each item I must pick up the device. This is painful if I have many items. There is an example I've created with cacti 0.8 shown in issue #560 , which was not as painful as with the new GUI.

Is there a way to persist the last chosen device across the item list when adding a new item?

Kind regards
Guenter

**Comment by cigamit** [comment]
What theme?  Also, open the browsers debug window, goto the console, repeat that and look for something like a javascript error.

**Comment by gmuellerfr** [comment]
Running Firefox on Linux with modern theme. BTW, in Classic theme you can't add a device-less graph because the device field is filled with the first device from the drop-down button.

Nothing in console, but when I change to the dark theme, I see, what's written on the huge white area:


Notice: Undefined index: title in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1419

Notice: Undefined index: id in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1420

Notice: Undefined index: vertical_label in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1419

Notice: Undefined index: id in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1420

Notice: Undefined index: image_format_id in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1419

Notice: Undefined index: id in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1420

Notice: Undefined index: height in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1419

Notice: Undefined index: id in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1420

Notice: Undefined index: width in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1419

Notice: Undefined index: id in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1420

Notice: Undefined index: base_value in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1419

Notice: Undefined index: id in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1420

Notice: Undefined index: slope_mode in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1419

Notice: Undefined index: id in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1420

Notice: Undefined index: auto_scale in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1419

Notice: Undefined index: id in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1420

Notice: Undefined index: auto_scale_opts in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1419

Notice: Undefined index: id in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1420

Notice: Undefined index: auto_scale_log in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1419

Notice: Undefined index: id in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1420

Notice: Undefined index: scale_log_units in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1419

Notice: Undefined index: id in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1420

Notice: Undefined index: auto_scale_rigid in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1419

Notice: Undefined index: id in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1420

Notice: Undefined index: upper_limit in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1419

Notice: Undefined index: id in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1420

Notice: Undefined index: lower_limit in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1419

Notice: Undefined index: id in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1420

Notice: Undefined index: unit_value in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1419

Notice: Undefined index: id in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1420

Notice: Undefined index: unit_exponent_value in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1419

Notice: Undefined index: id in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1420

Notice: Undefined index: unit_length in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1419

Notice: Undefined index: id in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1420

Notice: Undefined index: no_gridfit in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1419

Notice: Undefined index: id in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1420

Notice: Undefined index: alt_y_grid in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1419

Notice: Undefined index: id in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1420

Notice: Undefined index: right_axis in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1419

Notice: Undefined index: id in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1420

Notice: Undefined index: right_axis_label in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1419

Notice: Undefined index: id in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1420

Notice: Undefined index: right_axis_format in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1419

Notice: Undefined index: id in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1420

Notice: Undefined index: right_axis_formatter in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1419

Notice: Undefined index: id in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1420

Notice: Undefined index: left_axis_formatter in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1419

Notice: Undefined index: id in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1420

Notice: Undefined index: auto_padding in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1419

Notice: Undefined index: id in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1420

Notice: Undefined index: dynamic_labels in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1419

Notice: Undefined index: id in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1420

Notice: Undefined index: force_rules_legend in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1419

Notice: Undefined index: id in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1420

Notice: Undefined index: tab_width in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1419

Notice: Undefined index: id in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1420

Notice: Undefined index: legend_position in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1419

Notice: Undefined index: id in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1420

Notice: Undefined index: legend_direction in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1419

Notice: Undefined index: id in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6/graphs.php on line 1420
Common Options

**Comment by cigamit** [comment]
I fixed the warnings, and the theme issues.  Can you please open a separate enhancement request for the filtering of the data sources.  Good idea, had thought of a long time ago, and never implemented it.
