### ISSUE TITLE
GUI: graph.php - Different graph sizes

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#705]
Version: 1.1.6
Firefox, Chrome

![cacti-2](https://cloud.githubusercontent.com/assets/17087236/26196749/2904cae6-3bc0-11e7-8650-79f7f536bb2b.png)

As You can see the very older created graphs are little smaller than newly created.
It's should be the same size.

**Comment by cigamit** [comment]
Nope, not true.  There is a default for graph width and height under settings, whatever you put there is the 'default' for new graphs based upon graph template.  You can modify your graph templates and resize graphs, or resync templates though.  Easy for you to fix.

**Comment by interduo** [comment]
Ok, Now I understand this.
Thanks.
