### ISSUE TITLE
Classic theme doesn't show external links on tab background

### ISSUE THREAD

**Issue by gmuellerfr** [Cacti/cacti#706]
Hello,

I'm using cacti 1.1.6. All new themes show external links correct integrated into theme.
In classic theme the link for the external links is shown, but not on a theme tab.

Thank you for listening.
Guenter

**Comment by cigamit** [comment]
Show an example.  The top tab shows just fine.  So, there must be a problem with your environment.  Maybe you are missing php-gd?

**Comment by gmuellerfr** [comment]
Hello,

here are two screen shots, taken at home with firefox 53.0.3 and windows.
My environment at work is latest firefox and linux with same behaviour.

![classic_theme](https://cloud.githubusercontent.com/assets/25848039/26275924/4d3316f4-3d6c-11e7-9cc9-350c7b439446.png)

![modern_theme](https://cloud.githubusercontent.com/assets/25848039/26275928/55e0fb22-3d6c-11e7-8639-cde0b05bd5e6.png)


 
Thank you for listening.
Guenter

**Comment by cigamit** [comment]
The tab images are dynamic created.  There should be two files in the Cacti images folder tab_template_[blue|red].gif.  Make sure the browser can read them.  Then, you should have in the includes directory two TTF fonts both starting with 'DejaVu*.ttf'.  Make sure again they are readable.

The image creation function relies on a few base gd functions, and I am hearing that on some Linux's, one function may be missing.  They are:

imagecreatefromgif()
imagecreatetruecolor()
imagecolortransparent()
imagecolorallocate()
imagettfbbox() - May not be present, or may simply not work

If you don't have permission, or these functions fail, you wont get a tab image.  Another check you can do it to open the browser debug window and see what comes back for these images.  You should find a few image tags that have a type: image/gif;base64:{data}.

I suspect as you dig in, you will find the issue.  If you wish to review the code, goto lib/functions.php at approximately line 4157, and you will find a function get_classic_tabimage().  Good luck.  Let us know what you find.

**Comment by gmuellerfr** [comment]
Hello,

the first assumption is not true!
There is no file of this kind in the actual cacti-tree (linux).

apache-host htdocs # cd -
/var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.6
apache-host cacti-1.1.6 # find . -name "*blue*"
apache-host cacti-1.1.6 # find . -name "tab_template_*"

apache-host images # ls -la
total 376
drwxr-xr-x  2 root root  4096 May 15 09:04 .
drwxr-xr-x 16 root root  4096 May 15 10:04 ..
-rw-r--r--  1 root root   781 May 15 09:04 accept.png
-rw-r--r--  1 root root   703 May 15 09:04 application_edit.png
-rw-r--r--  1 root root   859 May 15 09:04 arrow.gif
-rw-r--r--  1 root root 13882 May 15 09:04 auth_background.gif
-rw-r--r--  1 root root   201 May 15 09:04 bullet_arrow_down.png
-rw-r--r--  1 root root   201 May 15 09:04 bullet_arrow_up.png
-rw-r--r--  1 root root  8318 May 15 09:04 cacti_about_logo.gif
-rw-r--r--  1 root root  7228 May 15 09:04 cacti_backdrop.gif
-rw-r--r--  1 root root  4156 May 15 09:04 cacti_backdrop2.gif
-rw-r--r--  1 root root 10284 May 15 09:04 cacti_error_image.png
-rw-r--r--  1 root root  5641 May 15 09:04 cacti_logo.gif
-rw-r--r--  1 root root  6273 May 15 09:04 cacti_logo_new.gif
-rw-r--r--  1 root root   927 May 15 09:04 calendar.gif
-rw-r--r--  1 root root   823 May 15 09:04 chart_curve_go.png
-rw-r--r--  1 root root   512 May 15 09:04 cog.png
-rw-r--r--  1 root root   814 May 15 09:04 cog_add.png
-rw-r--r--  1 root root   847 May 15 09:04 cog_delete.png
-rw-r--r--  1 root root   869 May 15 09:04 cog_error.png
-rw-r--r--  1 root root   178 May 15 09:04 delete_icon.gif
-rw-r--r--  1 root root   170 May 15 09:04 delete_icon_large.gif
-rw-r--r--  1 root root   853 May 15 09:04 device_template.png
-rw-r--r--  1 root root  1083 May 15 09:04 disable_icon.png
-rw-r--r--  1 root root  1058 May 15 09:04 enable_icon.png
-rw-r--r--  1 root root  1041 May 15 09:04 enable_icon_disabled.png
-rw-r--r--  1 root root  1406 May 15 09:04 favicon.ico
-rw-r--r--  1 root root  1013 May 15 09:04 graph_page_top.gif
-rw-r--r--  1 root root   951 May 15 09:04 graph_properties.gif
-rw-r--r--  1 root root   782 May 15 09:04 graph_query.png
-rw-r--r--  1 root root   999 May 15 09:04 graph_zoom.gif
-rw-r--r--  1 root root    44 May 15 09:04 index.php
-rw-r--r--  1 root root  1089 May 15 09:04 install_icon.png
-rw-r--r--  1 root root  1013 May 15 09:04 install_icon_disabled.png
-rw-r--r--  1 root root    68 May 15 09:04 menuarrow.gif
-rw-r--r--  1 root root    75 May 15 09:04 move_down.gif
-rw-r--r--  1 root root    85 May 15 09:04 move_left.gif
-rw-r--r--  1 root root    86 May 15 09:04 move_right.gif
-rw-r--r--  1 root root    74 May 15 09:04 move_up.gif
-rw-r--r--  1 root root    67 May 15 09:04 reload_icon_small.gif
-rw-r--r--  1 root root 10300 May 15 09:04 rrd_not_found.png
-rw-r--r--  1 root root   530 May 15 09:04 server.png
-rw-r--r--  1 root root   673 May 15 09:04 server_chart.png
-rw-r--r--  1 root root   710 May 15 09:04 server_chart_curve.png
-rw-r--r--  1 root root  1321 May 15 09:04 server_dataquery.png
-rw-r--r--  1 root root   823 May 15 09:04 server_graph_template.png
-rw-r--r--  1 root root   683 May 15 09:04 server_table.png
-rw-r--r--  1 root root    90 May 15 09:04 shadow.gif
-rw-r--r--  1 root root    90 May 15 09:04 shadow_gray.gif
-rw-r--r--  1 root root   556 May 15 09:04 site.png
-rw-r--r--  1 root root   913 May 15 09:04 spikekill.gif
-rw-r--r--  1 root root   700 May 15 09:04 stop.png
-rw-r--r--  1 root root  2193 May 15 09:04 tab_cacti.gif
-rw-r--r--  1 root root  1328 May 15 09:04 tab_clog.png
-rw-r--r--  1 root root  1172 May 15 09:04 tab_clog_down.png
-rw-r--r--  1 root root  2244 May 15 09:04 tab_console.gif
-rw-r--r--  1 root root  2056 May 15 09:04 tab_console_down.gif
-rw-r--r--  1 root root  2150 May 15 09:04 tab_graphs.gif
-rw-r--r--  1 root root  2154 May 15 09:04 tab_graphs_down.gif
-rwxr-xr-x  1 root root   850 May 15 09:04 tab_list.gif
-rw-r--r--  1 root root  1492 May 15 09:04 tab_mode_list.gif
-rw-r--r--  1 root root  1471 May 15 09:04 tab_mode_list_down.gif
-rw-r--r--  1 root root  1501 May 15 09:04 tab_mode_preview.gif
-rw-r--r--  1 root root  1452 May 15 09:04 tab_mode_preview_down.gif
-rw-r--r--  1 root root  1521 May 15 09:04 tab_mode_tree.gif
-rw-r--r--  1 root root  1450 May 15 09:04 tab_mode_tree_down.gif
-rw-r--r--  1 root root  2334 May 15 09:04 tab_nectar.gif
-rw-r--r--  1 root root  1831 May 15 09:04 tab_nectar_down.gif
-rwxr-xr-x  1 root root   865 May 15 09:04 tab_preview.gif
-rw-r--r--  1 root root  2226 May 15 09:04 tab_settings.gif
-rw-r--r--  1 root root  1973 May 15 09:04 tab_settings_down.gif
-rwxr-xr-x  1 root root   866 May 15 09:04 tab_tree.gif
-rwxr-xr-x  1 root root   566 May 15 09:04 table.png
-rw-r--r--  1 root root   683 May 15 09:04 table_go.png
-rw-r--r--  1 root root  1174 May 15 09:04 timeview.png
-rw-r--r--  1 root root    55 May 15 09:04 transparent_line.gif
-rw-r--r--  1 root root   483 May 15 09:04 tree.png
-rw-r--r--  1 root root  1000 May 15 09:04 uninstall_icon.gif
-rw-r--r--  1 root root   444 May 15 09:04 view_aggregate_children.png
-rw-r--r--  1 root root   832 May 15 09:04 view_none.gif
-rw-r--r--  1 root root   480 May 15 09:04 view_page.png

Thank you for listening.
Guenter

**Comment by cigamit** [comment]
Okay, thanks for catching.  The files are there now.  Thanks for reporting.
