### ISSUE TITLE
[Cacti 1.1.4 - 1.1.6] Realtime not working on remote pollers for certain data query

### ISSUE THREAD

**Issue by jhonnyx82** [Cacti/cacti#711]
I am facing an issue with realtime graphing for an IP SLA template I have been using for some time.

Now while I reckon that this should be material for the forum I feel this is probably more related on how the realtime feature works:

I have 3 pollers (1 main and 2 remote) and I am using the attached template for IP SLA monitoring, the strange part is that:

- data is populated correctly from all the 3 pollers 
- realtime graph works only from the devices queried **directly** from the **main poller** (used also for management of course)
- other data queries (imported and cacti's native) are working correctly with realtime on the remote pollers

here the data template, if you feel like reviewing it 
(cisco_saa Copy to {cacti_root}/resource/snmp_queries/ )
(also rename them to .xml)

[cacti_data_query_cisco_ip_sla_statistics.txt](https://github.com/Cacti/cacti/files/1014246/cacti_data_query_cisco_ip_sla_statistics.txt)
[cisco_saa.txt](https://github.com/Cacti/cacti/files/1014247/cisco_saa.txt)

**Comment by cigamit** [comment]
Anything in the remote pollers cacti.log?

**Comment by jhonnyx82** [comment]
Unfortunately I could not see any error on the cacti log through the web interface, even setting the graph_realtime.php to debug mode.

Is there anyway I can collect some informative logs to help resolving this?

**Comment by cigamit** [comment]
Post some screen shot output from the poller cache for these broken data sources. Console -> System Utilities -> View Poller Cache

**Comment by jhonnyx82** [comment]
Hi, here the screenshot about one of these data sources poller cache:

![image](https://cloud.githubusercontent.com/assets/26431888/26281534/0bf4c69a-3dfa-11e7-9bf1-a3dd1568f16e.png)

Data is collected and graph is OK normally but not with realtime:

![image](https://cloud.githubusercontent.com/assets/26431888/26281540/61ed3fb4-3dfa-11e7-88d3-a02b817a21e6.png)

![image](https://cloud.githubusercontent.com/assets/26431888/26281553/bcb29070-3dfa-11e7-96d4-48baa04eae02.png)

**Comment by cigamit** [comment]
You should hand run these snmp queries from the command line on the remote poller.  Please verify that the values are increasing every time you run the query.  Some OID's only get updated every so many minutes instead of every time you poll them.  So, my guess, principally since these are SNMP items, that this is the case.  Comment back with what you experience when doing this test.

**Comment by jhonnyx82** [comment]
Thank you for the tip but I am not sure about it only because for realtime graph of the same type of data query on the main poller it works OK, so I think if that is the case it would happen only on data source collected directly from the main poller, right?

**Comment by jhonnyx82** [comment]
Hi, 

To provide un update, I ran the test that you requested: a bash script of one of my IP SLA queried from one of the remote poller with a 5 seconds wait interval and I can see data being populated ( I took 4 parameters from the IP SLA template I attached in the first message)

So as I can tell the data is populated and available in SNMP faily at least every 5 seconds (timestamps are included)

[ipslalog.txt](https://github.com/Cacti/cacti/files/1019171/ipslalog.txt)

**Comment by jhonnyx82** [comment]
In case the issue is still unclear please let me know and I will try to provide additional clues

**Comment by cigamit** [comment]
It's timing right now.  Summer has started, and there is a lot to do around the farm.  You might want to put cmd_realtime.php into debug and poller_realtime.php into debug and then render this graph in realtime.  You will want to upload the log from the remote poller (the section that includes realtime info).

**Comment by jhonnyx82** [comment]
Thank you, 

Unfortunately there is no chance to select cmd_realtime.php and/or poller_realtime.php for debug mode:

![image](https://cloud.githubusercontent.com/assets/26431888/26438364/d8bcb892-4122-11e7-9e38-48f858df8efc.png)

Maybe I can dig into the cacti.log or redirecting the logs through apache but let me know what do you think would be the best approach.

**Comment by cigamit** [comment]
Oh, well that alone is a bug.  Thanks for catching that.  You will have to wait till I get that bug fixed before you can enable it.

**Comment by cigamit** [comment]
Please update include/global_settings.php and then use the selective debug on those two files.

**Comment by jhonnyx82** [comment]
I have added your global_settings commit and ran a test with the debug options you asked:

- I ran the test requesting a realtime graph on the main poller
- I can see debug logs on the main poller but no related logs on the remote poller
- I ran the test requesting a realtime graph on the remote poller
- I can see the logs in that case on the remote poller

- Please consider this seems to be an issue on this data query that I have imported on all pollers, a more simple data query (like CPU usage, just one data source) seems to be working properly, this data query has multiple data sources, so my lucky guess is that this may be a performance issue (remote pollers are not on the same site, but performance are good, no much delay between 50 - 100 ms RTT)

Attached here the logs

[cacti_realtime_test_MAIN-POLLER.txt](https://github.com/Cacti/cacti/files/1031233/cacti_realtime_test_MAIN-POLLER.txt)

[cacti_realtime_test_REMOTE-POLLER.txt](https://github.com/Cacti/cacti/files/1031238/cacti_realtime_test_REMOTE-POLLER.txt)

**Comment by jhonnyx82** [comment]
I noticed that this thread has the **unverified** tag, I guess it will go back in the queue with minor attention.

Is this happening only to me? :)

**Comment by cigamit** [comment]
My cup overfloweth.  You should probably instrument the cmd_realtime.php on the main poller with some debug statements.  Within a polling interval or two, they will be replicated to the remote data collectors.  From there, you can review the output.  Let me know what you find.

**Comment by jhonnyx82** [comment]
Thank you, I will wait for when you will have time to follow this up.

I understand and appreciate your efforts.

**Comment by cigamit** [comment]
I just reviewed the remote pollers developer debug log.  It's gathering and inserting data, but that data is all zero's.  Are you using spine as your main data collector?

**Comment by jhonnyx82** [comment]
Yes we use SPINE

**Comment by cigamit** [comment]
Any feedback?  Can you test on the latest Cacti?

**Comment by jhonnyx82** [comment]
Will do next week (now on vacation) and let you know the outcome.

If you have any preference on which logs to produce and how to collect
them, let me know

**Comment by cigamit** [comment]
I would like you to simply, from the remote poller, run cmd.php against the host in debug mode and see what output you get.  I suspect the issue may be that cmd.php is not working on the device and data source in question, but spine is.  The Realtime Poller uses effectively cmd.php.  There have been some changes to the lib/snmp.php API since you submitted this which is why I would like to see you perform the test at Cacti 1.1.16+.

**Comment by cigamit** [comment]
No feedback.

**Comment by jhonnyx82** [comment]
I apologize for not being able to follow up actively on this but I believe the issue is still there as real time graphs works only on sources queried by the main poller.

Can we resume this topic, I think IP SLA realtime graphing is one main feature of CACTI.

Along that I have a feeling that with bigger cluster the way realtime graph works can be a bit daunting, it may be better to open directly an HTTP connection to the remote poller rather than on the main, indeed it would create a dependency but it would facilitate the traffic flow I believe
