### ISSUE TITLE
RE#670 No graph templates when you change graph template---[Cacti-1.1.7]

### ISSUE THREAD

**Issue by kaf3773** [Cacti/cacti#712]
Testing Cacti-1.1.7 after fix for issue #670 . I get the below after hitting "Go" to change the graph template

No graph templates are populated in the New Graph Template dialogue box indicated by red arrow

![image](https://cloud.githubusercontent.com/assets/16928454/26260486/6b3968d2-3c9b-11e7-9920-25ed4ca6ef2a.png)
 
here is the URL i see

http://IP_Address/new_cacti/graphs.php?host_id=15&rows=-1&page=1&rfilter=&template_id=dq_14&

**Comment by cigamit** [comment]
Resolved.  Need to do more QA.  Thanks for catching.
