### ISSUE TITLE
RE#696 Cannot disable snmp notifications after they are enabled---[Cacti-1.1.7]

### ISSUE THREAD

**Issue by kaf3773** [Cacti/cacti#713]
testing after fix for #696. snmp notifications cannot be disabled after they are enabled. 

![image](https://cloud.githubusercontent.com/assets/16928454/26261047/ab6e88b8-3c9d-11e7-9402-428088f586c4.png)

Go button either grayed out or does not respond at all

**Comment by cigamit** [comment]
Yea, lot's of issues on that page.  Should be all fixed up now.
