### ISSUE TITLE
GUI filtering enhancement wanted when generating graphs not belonging to a certain device

### ISSUE THREAD

**Issue by gmuellerfr** [Cacti/cacti#717]
Hello,

following my issue #704 I repeat my wish for an enhanced filtering.

I want to add a graph not belonging to a certain device. In expert mode I can add a graph with empty device name.

Now I have to add items to my graph. It's clear, that I have to pick the device from the drop-down list.
But when I want to add a legend or another data-source for the same device, first of all I must pick the device from the huge drop-down list. For each item I must pick up the device. This is painful if I have many items. There is an example I've created with cacti 0.8 shown in issue #560 , which was not as painful as with the new GUI.

Is there a way to persist the last chosen device across the item list when adding a new item?

Kind regards
Guenter

**Comment by cigamit** [comment]
Non template based graph items, when using the non-classic theme are now using callbacks.  Both device id, and task item id (data source).  So, the UI should be much more responsive now.

**Comment by gmuellerfr** [comment]
Hi,

after a long period of only using cacti version 1.1.6, I have migrated today to version 1.1.9.
Now I want to add a graph with "no device" and "no template".
After adding some items containing only background AREAs, I'm not able to add lines of real devices.
![graph_edit_screen](https://user-images.githubusercontent.com/25848039/28016488-d2751a62-6574-11e7-9e04-103bd4861863.png)
The screen shot shows the screen I'm faced to after hitting "add". I am not able to select the device.
![add_no_device_item](https://user-images.githubusercontent.com/25848039/28016318-2bed7d92-6574-11e7-9b9a-f1fa9a4b0b42.png)
The device can't be selected, because the drop down list stays empty, showing only "none".

Kind regards
Guenter

**Comment by cigamit** [comment]
Check the cacti log for SQL errors.  This dropdown is now auto-complete.  Simply use alt-print-screen to take the screen capture.

**Comment by gmuellerfr** [comment]
Hello,
I've just hit the add button and got an error in the log file:

![cacti_log_error](https://user-images.githubusercontent.com/25848039/28027839-dbda4750-659a-11e7-88fb-97b32960a29f.png)
Seems to be no sql-error.

Kind Regards
Guenter

**Comment by cigamit** [comment]
Please update lib/rrd.php from develop and see if this error disappears.  An update was just made to perform additional checks.  It appears that some Linux versions do not include True Type Font functions inside of the php-gd module.

**Comment by gmuellerfr** [comment]
Hello,

I've done so, but now I can't select any device in the graph management drop-down list where I want to select NONE. I get many errors.
![rrd_php](https://user-images.githubusercontent.com/25848039/28069863-3ae617e6-664b-11e7-8280-4d164648fdbd.png)
I must revert to the original 1.1.9 rrd.php
