### ISSUE TITLE
Issue with Real Time Graph

### ISSUE THREAD

**Issue by atleticoDC** [Cacti/cacti#718]
Dear Team,
We are facing an issue with real time graph.
We have several Cisco devices: some of those runs IOS and the others runs IOS XR.
If we choose Real Time graph for an interface from Cisco IOS Switch, the graph shows a continues traffic values, instead if we hoose Real Time graph for an interface from Cisco IOS XR Router (Cisco ASR 9000) the graph shows discontinues traffic values (several holes beetween data polled).

IOS XR real time graph:

![image](https://cloud.githubusercontent.com/assets/26479938/26277407/07c14ff8-3d87-11e7-9780-e6da8e09bab2.png)

IOS real time graph:

![image](https://cloud.githubusercontent.com/assets/26479938/26277417/2edc3102-3d87-11e7-8b8e-602d222a3bda.png)

We remain at your disposal for further information or debugs if required.

Regards

**Comment by cigamit** [comment]
Some devices only update their metrics every X seconds.  Old Cisco devices, for example, only updated their counters every 15 seconds.  It looks like that is your problem here.  Not a Cacti issue, but rather a device issue.

**Comment by atleticoDC** [comment]
Hello Jimmy, thanks for your reply, but I think that the problem cannot be on our device.
If we choose Daily Graph, the traffic value is continue and linear as you can show in the output below:

[cid:image005.jpg@01D2D264.BD302FA0]


Instead, Real time graph of the same interface shows several wholes during data polling:


[cid:image006.jpg@01D2D264.BD302FA0]



Do you have any suggestions?

Thanks in advance for your support.


[SUI-IT_eSig_Maurizio_Spanu]


Da: Jimmy Conner [mailto:notifications@github.com]
Inviato: domenica 21 maggio 2017 18:52
A: Cacti/cacti <cacti@noreply.github.com>
Cc: Support <support@supernap.it>; Author <author@noreply.github.com>
Oggetto: Re: [Cacti/cacti] Issue with Real Time Graph (#718)


Some devices only update their metrics every X seconds. Old Cisco devices, for example, only updated their counters every 15 seconds. It looks like that is your problem here. Not a Cacti issue, but rather a device issue.

**Comment by cigamit** [comment]
No suggestions other that testing this directly yourself.  It is not theory, but observations over several years of doing this and a deep understanding of rrdtool.

**Comment by browniebraun** [comment]
Does not sound like a Cacti to me. Are you probably using CoPP?

Regards
-Andi
