### ISSUE TITLE
Skip issue in aggregate template

### ISSUE THREAD

**Issue by nitzan-tz** [Cacti/cacti#719]
It looks like there is an issue with aggregate template
I have graph template that also show maximum value and utilization on regular area/line 1
When I am creating aggregate template I am setting skip for the maximum value and utilization but when I am creating aggregate graph with this template it create some wired gprints and comments for the items I skiped 

![image](https://cloud.githubusercontent.com/assets/7695109/26287142/96306796-3e7d-11e7-8d83-2b52348a544e.png)

![image](https://cloud.githubusercontent.com/assets/7695109/26287145/a7db6a68-3e7d-11e7-8c5d-8adca86ee335.png)

This is the rrd graph command

/bin/rrdtool graph - \
--imgformat=PNG \
--start='-180000' \
--end='-60' \
--pango-markup  \
--title='Test' \
--vertical-label='bits per second' \
--slope-mode \
--base=1000 \
--height=200 \
--width=700 \
--rigid \
--alt-autoscale-max \
--lower-limit='0' \
--color BACK#F3F3F3 \
--color CANVAS#FDFDFD \
--color SHADEA#CBCBCB \
--color SHADEB#999999 \
--color GRID#C4C4C4 \
--color MGRID#1A1C1C \
--color FONT#000000 \
--color AXIS#2C4D43 \
--color ARROW#2C4D43 \
--color FRAME#2C4D43 \
--border 1 --font TITLE:11:'Ariel' \
--font AXIS:8:'Ariel' \
--font LEGEND:8:'Courier' \
--font UNIT:8:'Ariel' \
--font WATERMARK:6:'Ariel' \
--slope-mode \
--watermark 'Copyright (C) 2004-2017 The Cacti Group' \
DEF:a='/var/www/html/cacti/rra/23/1454.rrd':'traffic_in':MAX \
DEF:b='/var/www/html/cacti/rra/23/1455.rrd':'traffic_in':MAX \
DEF:c='/var/www/html/cacti/rra/23/1454.rrd':'traffic_out':MAX \
DEF:d='/var/www/html/cacti/rra/23/1455.rrd':'traffic_out':MAX \
CDEF:cdefa='a,8,*' \
CDEF:cdefd='a,-8,*' \
CDEF:cdefe='b,8,*' \
CDEF:cdefh='b,-8,*' \
CDEF:cdefi='c,8,*' \
CDEF:cdefba='c,8,*,1000000,/,10000,/,100,*' \
CDEF:cdefbc='d,8,*' \
CDEF:cdefbe='d,8,*,1000000,/,10000,/,100,*' \
CDEF:cdefbh='TIME,1495397525,GT,a,a,UN,0,a,IF,IF,TIME,1495397525,GT,b,b,UN,0,b,IF,IF,+,8,*' \
CDEF:cdefca='TIME,1495397525,GT,a,a,UN,0,a,IF,IF,TIME,1495397525,GT,b,b,UN,0,b,IF,IF,+,-8,*' \
CDEF:cdefcb='TIME,1495397525,GT,c,c,UN,0,c,IF,IF,TIME,1495397525,GT,d,d,UN,0,d,IF,IF,+,8,*' \
AREA:cdefa#00CF00FF:'':STACK \
GPRINT:cdefa:LAST:'DC01-Leaf-2 xe-0/1/0 Current\:%8.2lf%s'  \
GPRINT:cdefa:AVERAGE:'Average\:%8.2lf%s'  \
AREA:cdefd#FF3932FF:'Maximum\:\n'  \
AREA:cdefe#00CF00FF:'':STACK \
GPRINT:cdefe:LAST:'DC01-Leaf-2 xe-0/1/1 Current\:%8.2lf%s'  \
GPRINT:cdefe:AVERAGE:'Average\:%8.2lf%s'  \
AREA:cdefh#FECEA8FF:'Maximum\:\n':STACK \
AREA:cdefi#002A97FF:'':STACK \
GPRINT:cdefi:LAST:'DC01-Leaf-2 xe-0/1/0 Current\:%8.2lf%s\n'  \
GPRINT:cdefba:AVERAGE:'DC01-Leaf-2 xe-0/1/0 Average\:%8.0lf%%'  \
GPRINT:cdefba:MAX:'Maximum\:%8.0lf%%\n'  \
AREA:cdefbc#002A97FF:'':STACK \
GPRINT:cdefbc:LAST:'DC01-Leaf-2 xe-0/1/1 Current\:%8.2lf%s\n'  \
GPRINT:cdefbe:AVERAGE:'DC01-Leaf-2 xe-0/1/1 Average\:%8.0lf%%'  \
GPRINT:cdefbe:MAX:'Maximum\:%8.0lf%%\n'  \
COMMENT:' \n'  \
LINE1:cdefbh#00CF00FF:''  \
GPRINT:cdefbh:LAST:'Total Current\:%8.2lf%s'  \
GPRINT:cdefbh:AVERAGE:'Average\:%8.2lf%s'  \
LINE1:cdefca#E97F02FF:'Maximum\:\n'  \
LINE1:cdefcb#002A97FF:''  \
GPRINT:cdefcb:LAST:'Total Current\:%8.2lf%s\n' 

If I am creating the same aggregate graph without template it looks good

**Comment by cigamit** [comment]
Please check again with the latest.  Some things have been reconciled now.  I'm thinking 'good enough' for now anyway.  Lot's of other stuff to work on.

**Comment by nitzan-tz** [comment]
With the latest clone from github I see the same issue 
I think some of it is related to the sequence in aggregate_graph_templates_item table

mariadb root@localhost:cacti> select * FROM aggregate_graph_templates_item;
+-------------------------+---------------------------+------------+------------------+-------------------+-----------------+-------------+-----------+-------------+--------------+
|   aggregate_template_id |   graph_templates_item_id |   sequence |   color_template | t_graph_type_id   |   graph_type_id | t_cdef_id   |   cdef_id | item_skip   | item_total   |
|-------------------------+---------------------------+------------+------------------+-------------------+-----------------+-------------+-----------+-------------+--------------|
|                       2 |                         9 |          1 |                4 |                   |               0 |             |         0 |             | on           |
|                       2 |                        10 |          2 |                0 |                   |               0 |             |         0 |             | on           |
|                       2 |                        11 |          3 |                0 |                   |               0 |             |         0 |             | on           |
|                       2 |                        12 |          4 |                0 |                   |               0 |             |         0 |             | on           |
|                       2 |                        13 |          5 |                4 | on                |               8 | on          |        53 |             | on           |
|                       2 |                        14 |          6 |                0 |                   |               0 |             |         0 |             | on           |
|                       2 |                        15 |          7 |                0 |                   |               0 |             |         0 |             | on           |
|                       2 |                        16 |          8 |                0 |                   |               0 |             |         0 |             | on           |
|                       2 |                       412 |          1 |                0 |                   |               0 |             |         0 | on          |              |
|                       2 |                       413 |          6 |                0 |                   |               0 |             |         0 | on          |              |
|                       2 |                       505 |          9 |                0 |                   |               0 |             |         0 | on          |              |
|                       2 |                       506 |         10 |                0 |                   |               0 |             |         0 | on          |              |
|                       2 |                       507 |         11 |                0 |                   |               0 |             |         0 | on          |              |
|                       2 |                       508 |         12 |                0 |                   |               0 |             |         0 | on          |              |
|                       2 |                       509 |         13 |                0 |                   |               0 |             |         0 | on          |              |
|                       2 |                       510 |         14 |                0 |                   |               0 |             |         0 | on          |              |
|                       2 |                       511 |         15 |                0 |                   |               0 |             |         0 | on          |              |
|                       2 |                       512 |         16 |                0 |                   |               0 |             |         0 | on          |              |
+-------------------------+---------------------------+------------+------------------+-------------------+-----------------+-------------+-----------+-------------+--------------+

BTW
The fact that you cannot clear both skip and total at the same time is BUG or feature ?

Thanks

Nitzan

**Comment by cigamit** [comment]
The current design is dependent on the sequencing of the graph items.  So, this is likely the source of the issue.  You should Re-Sync your Graph Templates.  Goto Console -> Templates -> Graph and 'Sync Graphs' for the template, and then resave your Aggregate.

I should put a change in for this before allowing the creation of an Aggregate against a template.

**Comment by nitzan-tz** [comment]
I did the following

Delete the aggregate
Delete the aggregate template
Re-sync the graphs
Create the aggregate template
Create the aggregate

But the graph looks the same
Again if it is not aggregate template it works fine
maybe something in the logic of the aggregate template 

This is the table now

mariadb root@localhost:cacti> select * FROM aggregate_graph_templates_item;
+-------------------------+---------------------------+------------+------------------+-------------------+-----------------+-------------+-----------+-------------+--------------+
|   aggregate_template_id |   graph_templates_item_id |   sequence |   color_template | t_graph_type_id   |   graph_type_id | t_cdef_id   |   cdef_id | item_skip   | item_total   |
|-------------------------+---------------------------+------------+------------------+-------------------+-----------------+-------------+-----------+-------------+--------------|
|                       3 |                         9 |          1 |                1 |                   |               0 |             |         0 |             | on           |
|                       3 |                        10 |          2 |                0 |                   |               0 |             |         0 |             | on           |
|                       3 |                        11 |          3 |                0 |                   |               0 |             |         0 |             | on           |
|                       3 |                        12 |          4 |                0 |                   |               0 |             |         0 |             | on           |
|                       3 |                        13 |          5 |                1 | on                |               7 | on          |        53 |             | on           |
|                       3 |                        14 |          6 |                0 |                   |               0 |             |         0 |             | on           |
|                       3 |                        15 |          7 |                0 |                   |               0 |             |         0 |             | on           |
|                       3 |                        16 |          8 |                0 |                   |               0 |             |         0 |             | on           |
|                       3 |                       412 |          1 |                0 |                   |               0 |             |         0 | on          |              |
|                       3 |                       413 |          6 |                0 |                   |               0 |             |         0 | on          |              |
|                       3 |                       505 |          9 |                0 |                   |               0 |             |         0 | on          |              |
|                       3 |                       506 |         10 |                0 |                   |               0 |             |         0 | on          |              |
|                       3 |                       507 |         11 |                0 |                   |               0 |             |         0 | on          |              |
|                       3 |                       508 |         12 |                0 |                   |               0 |             |         0 | on          |              |
|                       3 |                       509 |         13 |                0 |                   |               0 |             |         0 | on          |              |
|                       3 |                       510 |         14 |                0 |                   |               0 |             |         0 | on          |              |
|                       3 |                       511 |         15 |                0 |                   |               0 |             |         0 | on          |              |
|                       3 |                       512 |         16 |                0 |                   |               0 |             |         0 | on          |              |
+-------------------------+---------------------------+------------+------------------+-------------------+-----------------+-------------+-----------+-------------+--------------+

**Comment by cigamit** [comment]
Re-create the broken aggregate template and try again once 1.1.8 is released, or grab the lib/api_aggregate.php and lib/aggregate.php and do the same.

**Comment by nitzan-tz** [comment]
Hi,

Just upgrade to 1.1.9 and I see the same problem
What I did

1. delete aggregate template
2. save interface traffic graph template
3. resync interface traffic graph template
4. create aggregate template
5. create aggregate graph

I will upload the source graph template

This is the rrf graph command

/bin/rrdtool graph - \
--imgformat=PNG \
--start='-180000' \
--end='-60' \
--pango-markup  \
--title='Akamai' \
--vertical-label='bits per second' \
--slope-mode \
--base=1000 \
--height=120 \
--width=500 \
--rigid \
--alt-autoscale-max \
--lower-limit='0' \
--color BACK#F3F3F3 \
--color CANVAS#FDFDFD \
--color SHADEA#CBCBCB \
--color SHADEB#999999 \
--color GRID#C4C4C4 \
--color MGRID#1A1C1C \
--color FONT#000000 \
--color AXIS#2C4D43 \
--color ARROW#2C4D43 \
--color FRAME#2C4D43 \
--border 1 --font TITLE:11:'Ariel' \
--font AXIS:8:'Ariel' \
--font LEGEND:8:'Courier' \
--font UNIT:8:'Ariel' \
--font WATERMARK:6:'Ariel' \
--slope-mode \
--watermark 'Generated by Cacti®' \
DEF:a='/var/www/html/cacti/rra/12/915.rrd':'traffic_in':MAX \
DEF:b='/var/www/html/cacti/rra/12/915.rrd':'traffic_out':MAX \
DEF:c='/var/www/html/cacti/rra/13/1158.rrd':'traffic_in':MAX \
DEF:d='/var/www/html/cacti/rra/13/1158.rrd':'traffic_out':MAX \
CDEF:cdefa='a,8,*' \
CDEF:cdefd='a,-8,*' \
CDEF:cdefe='b,8,*' \
CDEF:cdefg='b,8,*,1000000,/,100000,/,100,*' \
CDEF:cdefi='c,8,*' \
CDEF:cdefbb='c,-8,*' \
CDEF:cdefbc='d,8,*' \
CDEF:cdefbe='d,8,*,1000000,/,100000,/,100,*' \
CDEF:cdefbh='TIME,1496697529,GT,a,a,UN,0,a,IF,IF,TIME,1496697529,GT,c,c,UN,0,c,IF,IF,+,8,*' \
CDEF:cdefca='TIME,1496697529,GT,a,a,UN,0,a,IF,IF,TIME,1496697529,GT,c,c,UN,0,c,IF,IF,+,-8,*' \
CDEF:cdefcb='TIME,1496697529,GT,b,b,UN,0,b,IF,IF,TIME,1496697529,GT,d,d,UN,0,d,IF,IF,+,8,*' \
AREA:cdefa#00CF00FF:'':STACK \
GPRINT:cdefa:LAST:'CORE-A-EX9204 ae0.108 Current\:%8.2lf%s'  \
GPRINT:cdefa:AVERAGE:'Average\:%8.2lf%s'  \
AREA:cdefd#FFF200FF:'Maximum\:\n'  \
AREA:cdefe#002A97FF:'':STACK \
GPRINT:cdefe:LAST:'CORE-A-EX9204 ae0.108 Current\:%8.2lf%s\n'  \
GPRINT:cdefg:AVERAGE:'CORE-A-EX9204 ae0.108 Average\:%8.0lf%%'  \
GPRINT:cdefg:MAX:'Maximum\:%8.0lf%%\n'  \
AREA:cdefi#00CF00FF:'':STACK \
GPRINT:cdefi:LAST:'CORE-B-EX9204 ae0.108 Current\:%8.2lf%s'  \
GPRINT:cdefi:AVERAGE:'Average\:%8.2lf%s'  \
AREA:cdefbb#FFD660FF:'Maximum\:\n':STACK \
AREA:cdefbc#002A97FF:'':STACK \
GPRINT:cdefbc:LAST:'CORE-B-EX9204 ae0.108 Current\:%8.2lf%s\n'  \
GPRINT:cdefbe:AVERAGE:'CORE-B-EX9204 ae0.108 Average\:%8.0lf%%'  \
GPRINT:cdefbe:MAX:'Maximum\:%8.0lf%%\n'  \
COMMENT:' \n'  \
LINE1:cdefbh#00CF00FF:''  \
GPRINT:cdefbh:LAST:'Total Current\:%8.2lf%s'  \
GPRINT:cdefbh:AVERAGE:'Average\:%8.2lf%s'  \
LINE1:cdefca#FFC73BFF:'Maximum\:\n'  \
LINE1:cdefcb#002A97FF:''  \
GPRINT:cdefcb:LAST:'Total Current\:%8.2lf%s\n' 


This is the DB table
mariadb root@localhost:cacti> select * FROM aggregate_graph_templates_item;
+-------------------------+---------------------------+------------+------------------+-------------------+-----------------+-------------+-----------+-------------+--------------+
|   aggregate_template_id |   graph_templates_item_id |   sequence |   color_template | t_graph_type_id   |   graph_type_id | t_cdef_id   |   cdef_id | item_skip   | item_total   |
|-------------------------+---------------------------+------------+------------------+-------------------+-----------------+-------------+-----------+-------------+--------------|
|                       5 |                         9 |          1 |                2 |                   |               0 |             |         0 |             | on           |
|                       5 |                        10 |          2 |                0 |                   |               0 |             |         0 |             | on           |
|                       5 |                        11 |          3 |                0 |                   |               0 |             |         0 |             | on           |
|                       5 |                        12 |          4 |                0 |                   |               0 |             |         0 |             | on           |
|                       5 |                        13 |          5 |                2 | on                |               7 | on          |        53 |             | on           |
|                       5 |                        14 |          6 |                0 |                   |               0 |             |         0 |             | on           |
|                       5 |                        15 |          7 |                0 |                   |               0 |             |         0 |             | on           |
|                       5 |                        16 |          8 |                0 |                   |               0 |             |         0 |             | on           |
|                       5 |                       412 |          1 |                0 |                   |               0 |             |         0 | on          |              |
|                       5 |                       413 |          6 |                0 |                   |               0 |             |         0 | on          |              |
|                       5 |                       505 |          9 |                0 |                   |               0 |             |         0 | on          |              |
|                       5 |                       506 |         10 |                0 |                   |               0 |             |         0 | on          |              |
|                       5 |                       507 |         11 |                0 |                   |               0 |             |         0 | on          |              |
|                       5 |                       508 |         12 |                0 |                   |               0 |             |         0 | on          |              |
|                       5 |                       509 |         13 |                0 |                   |               0 |             |         0 | on          |              |
|                       5 |                       510 |         14 |                0 |                   |               0 |             |         0 | on          |              |
|                       5 |                       511 |         15 |                0 |                   |               0 |             |         0 | on          |              |
|                       5 |                       512 |         16 |                0 |                   |               0 |             |         0 | on          |              |
+-------------------------+---------------------------+------------+------------------+-------------------+-----------------+-------------+-----------+-------------+--------------+
18 rows in set
Time: 0.007s
mariadb root@localhost:cacti>

**Comment by nitzan-tz** [comment]
Hi,

Any chance to fix this issue 
It is still open in 1.2

Regards

Nitzan

**Comment by cigamit** [comment]
Sorry, I lost track of this amongst all the other issues we've been working on.  Can you take a crack at it?

**Comment by cigamit** [comment]
Oh, it's actually a problem with your template.  You have the HR's in the wrong place.  They need to be at the last gprint for each line.  You have the HR's on some graph items.  That's wrong.  If you correct the Graph Template, this issue should go away.

**Comment by cigamit** [comment]
Please look at the attached image.  I'm going to close this, but there is a pretty major bug fix coming to aggregate.

![greengoogredbad](https://user-images.githubusercontent.com/957322/52156327-45fc2300-264d-11e9-81ac-6b2ffd3577d9.png)

**Comment by cigamit** [comment]
Green is good, red is bad.  &lt;hr&gt; in the wrong place.
