### ISSUE TITLE
Cacti 1.1.7 not compatible with latest Monitor & thold gits

### ISSUE THREAD

**Issue by jpobeda** [Cacti/cacti#720]
Latest git of Monitor and thold are not compatible with 1.1.7.

I went to a previous version and it works with 1.1.7

What's this validating against?

**Comment by cigamit** [comment]
Send screen shots of what you are talking about.  This does not make any sense.  You description is too vague.

**Comment by jpobeda** [comment]
Apologies, always forget to check selinux on this box. I moved from testing to preprod.

Btw, This was the screenshot:

![cacti_plugins](https://cloud.githubusercontent.com/assets/13456559/26327331/1a6326be-3f93-11e7-9729-dac96e39871c.png)

It doesn't give you any clue on why is it not compatible. 

Maybe adding an entry on clog will help people like me to check selinux before opening an issue.

Thanks
