### ISSUE TITLE
No data on graph after upgrade

### ISSUE THREAD

**Issue by amazen123** [Cacti/cacti#721]
Good Day,

I just upgraded my cacti to 1.1.7 from 1.1.3, after the upgrade the graph doesn't show old data except from the new data after the upgrade.
This is the steps I follow
1. disable cron job
2. rename cacti folder to cacti.old
3. rename cacti-1.1.7 to cacti
4. chown the log and scripts
5. copy all the rrd files from cacti.old to cacti/rra
6. enable cron job
7. rebuild poller cache

The upgrading process finished without a problem but when I clicked on graph it doesn't show old data.
Also here are some of the log after the upgrade

> CMDPHP WARNING: Poller has not created structured path '/usr/share/cacti/rra/72' yet. 
CMDPHP WARNING: Poller has not created structured path '/usr/share/cacti/rra/72' yet. 
CMDPHP WARNING: Poller has not created structured path '/usr/share/cacti/rra/73' yet.
CMDPHP WARNING: Poller has not created structured path '/usr/share/cacti/rra/73' yet. 

Any help is appreciated.

Thanks.

![no_old_data](https://cloud.githubusercontent.com/assets/23717456/26293522/eb887356-3eef-11e7-9e29-c9a8e1c8421a.png)

**Comment by reboot1983** [comment]
Chown your rra
Please see cacti upgrade manual

**Comment by reboot1983** [comment]
Please see step 9
http://www.cacti.net/downloads/docs/html/upgrade.html

**Comment by cigamit** [comment]
This seems to be a problem for the support forums.
