### ISSUE TITLE
unresponsive script editing graphic item list in 1.1.6

### ISSUE THREAD

**Issue by gmuellerfr** [Cacti/cacti#723]
Hello,

I want to change the colour of an item area. Under some circumstances the script loops.
Here is an example:
![unresponsive_script_item](https://cloud.githubusercontent.com/assets/25848039/26305326/21f4c9cc-3eef-11e7-9aec-a015c090861f.png)
Assume: I want to change item 16.
After waiting some time I get:
![unresponsive_script0](https://cloud.githubusercontent.com/assets/25848039/26305578/2fc0de00-3ef0-11e7-9ad8-c9c5707023f3.png)
I must hit the continue button. Maybe the script is stopped again at the same line or it's been stopped at:
![unresponsive_script](https://cloud.githubusercontent.com/assets/25848039/26305361/3e8b1aaa-3eef-11e7-8cf2-9783acdeaff8.png)
Stopped twice at this line number, then at first again, second again, first again and then after all the final page, where I can do what I want.

Each time I try to change the same item it's different how many times I must hit the continue button and how many times the browser shows the same line number where the continuation of the script is stopped.

When I hit the debug button I get:
![unresponsive_script_debug1](https://cloud.githubusercontent.com/assets/25848039/26306055/2d6c3e68-3ef2-11e7-8b81-2a0dc21934e4.png)
Then I hit a few times: step over and after some jumps through the code, the script seems to spend a very long time between
![unresponsive_script_debug2](https://cloud.githubusercontent.com/assets/25848039/26306093/622b2aa6-3ef2-11e7-8378-7e0fe760b0fc.png)
and
![unresponsive_script_debug3](https://cloud.githubusercontent.com/assets/25848039/26306104/6a5106b0-3ef2-11e7-9919-480ed08025ff.png)
I hope this will help to fix the problem.

Thank you for listening.
Guenter

**Comment by cigamit** [comment]
I think we need to change the Data Source dropdown to be a callback to prevent these issues for graphs that are non-templated.  Try the 'Classic' theme in the mean time.  How many Data Sources are on this system?

**Comment by gmuellerfr** [comment]
The data source window counts 4756 Data-Sources.
The log file shows:
2017-05-24 10:31:25 - SYSTEM STATS: Time:24.6487 Method:spine Processes:1 Threads:1 Hosts:148 HostsPerProcess:148 DataSources:10936 RRDsProcessed:4672
Thank you for listening.
Guenter

**Comment by cigamit** [comment]
This issue is resolved.
