### ISSUE TITLE
errors when snmp_sysLocation contains a single quote

### ISSUE THREAD

**Issue by acortiana** [Cacti/cacti#724]
It seems that there is a problem when the snmp_sysLocation of an host contains a single quote.
This morning an host that have this kind of configuration went down and now I continue to see this kind of error in the cacti.log:

`2017-05-22 14:55:05 - SPINE: Poller[1] ERROR: SQL Failed! Error:'1064', Message:'You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'text with a single quote inside' WHERE id='406'' at line 1', SQL Fragment:'UPDATE host SET status='3', status_event_count='1', status_fail_date='2017-05-22 14:55', status_rec_date='2017-05-19 01:19:00', status_last_error='Device did not respond to SNMP', min_time='3.924130', max_time='1506.493090', cur_time='9.284020', avg_time='6.096100', total_polls='985151', failed_polls='2891', availability='99.7065', snmp_sysDescr='sysdescr', snmp_sysObjectID='SNMPv2-SMI::enterprises.14988.1', snmp_sysUpTimeInstance='3507705100', snmp_sysContact='contact', snmp_sysName='sysname', snmp_sysLocation='text with a single quote inside' WHERE id='406''`

Cacti version: 1.1.7

**Comment by cigamit** [comment]
Please open this under the spine GitHub repository.  Thanks for reporting.
