### ISSUE TITLE
Schema change on Commit a559e60 breaks in MariaDB Galera cluster environment

### ISSUE THREAD

**Issue by JonBogan** [Cacti/cacti#725]
Since `ENGINE=MEMORY` is not replicated among nodes the `poller_output` table is inconsistent among them.  This causes Cacti in `poller.php` to indicate "WARNING: Poller Output Table not Empty" when the next query is made against a node where the table was not emptied.

This may also affect other tables set to `ENGINE=MEMORY`, but I don't have a use case to test against.

To correct this in my installation issued on one node, which replicated to the others:

```
use cacti;
ALTER TABLE `poller_output` ENGINE=InnoDB;
```

Subsequent polling with all nodes in rotation no longer shows the error.

**Comment by cigamit** [comment]
This is less of a bug than it is an implementation detail around Galera don't you think?

**Comment by JonBogan** [comment]
I am reporting that this breaks Cacti in certain installation scenarios.  I spent several hours tracking down why my graphs were not populating and why I was getting errors in my log.  Many would consider that a bug.

By "implementation detail" do you mean that the correct resolution to this is would be instructions for users of Galera that they need to modify `cacti.sql` prior to installation or alter the table after installation, or not use Galera?

**Comment by cigamit** [comment]
It would be greatly appreciated if you could make the updates to the documentation and submit a pull request with those changes.

**Comment by JonBogan** [comment]
Thanks for the merge @cigamit !
