### ISSUE TITLE
empty pop up field when discarding graph template from data query (1.1.6)

### ISSUE THREAD

**Issue by gmuellerfr** [Cacti/cacti#728]
Hello,

in cacti 1.1.6 I get an empty unnecessary pop up field, when I hit the delete button. I get this empty pop-up field in every theme. I have to destroy this pop-up field. Then I can hit continue to verify the delete.
![empty_pop_up](https://cloud.githubusercontent.com/assets/25848039/26344032/7bdd53b4-3f9e-11e7-8ed4-f9f322f10b55.png)
 
Thank you for listening.
Guenter

**Comment by cigamit** [comment]
Resolved.  Thanks for reporting.
