### ISSUE TITLE
User_admin.php - visual bug / ui

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#731]
![zrzut ekranu z 2017-05-23 14-15-32](https://cloud.githubusercontent.com/assets/17087236/26353889/bc2a2770-3fc2-11e7-9a9a-c42e7c714612.png)

White on gray, doesn't look fine.
Skin: Modern
Browser: Firefox
Branch: develop

**Comment by cigamit** [comment]
Resolved.
