### ISSUE TITLE
[Cacti 1.1.7] Data Template -> Data Source Profile change does not reflect poller time change

### ISSUE THREAD

**Issue by jhonnyx82** [Cacti/cacti#734]
- configured  **Templates** -> **data source template**  -> **Data source profile**  :  **Use Per-Data Source Value (Ignore this Value)**  **ENABLED**
- configured **Management** -> **Data Source** -> **Data Source Profile** _from a 5 minutes to 30 seconds DATA PROFILE_
- In **Management** -> **Data Sources** -> **Poller Interval** : _I can still see 5 minutes instead of 30 seconds_

- Cosmetical error or bug?

![image](https://cloud.githubusercontent.com/assets/26431888/26360163/b6542a52-3fd7-11e7-83c5-29076ef757ae.png)

![image](https://cloud.githubusercontent.com/assets/26431888/26360441/5f92afb2-3fd8-11e7-905d-8aa37e4479ad.png)

![image](https://cloud.githubusercontent.com/assets/26431888/26360630/da9ac94c-3fd8-11e7-9649-6fcd8a9780c2.png)

![image](https://cloud.githubusercontent.com/assets/26431888/26360707/1d0ed156-3fd9-11e7-96aa-743fc91c4a75.png)

**Comment by cigamit** [comment]
Please note that this only affects graphs created after the change in the default data source profile.  Please confirm that these data sources were created after the change.

**Comment by jhonnyx82** [comment]
Hi,

Here the steps:

- I tried again changing the **data source template** and **data query** to **user  Use Per-Data Source Value (Ignore this Value)**

- I then created a new device, when asked I applied the data profile by default (System Default) and created the graph

- I then changed the data profile to High Collection Rate for a datasource but still I can see that data source listed as a 5 minute poller one.

**Comment by cigamit** [comment]
You did it backwards.  The Data Profile must be elected at creation time.  After the Data Source is created, you can not just change the Profile.  That might be able to be supported, but not without deleting the RRDfile along with it.  Do you understand?

**Comment by jhonnyx82** [comment]
Thank you, I see it now.

My approach was with automation in mind, since I believe it cannot be selected during automated graph creation phase then I thought about changing it manually after their creation.

Anyway, by the way it works instead I think it's still better to create multiple profile data queries for this.

Thanks again

**Comment by cigamit** [comment]
It's on the to-do-list.  Just got a lot of other to-do's on the honeydo list.
