### ISSUE TITLE
Feature Request: Graph Template Item color drop-down changes

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#735]
I'm finding the color drop-down box for a graph template item difficult to work with. From years ago I have memorized several hex codes for my commonly used colors. In the past it was easy to punch these hex codes in and find the color I needed right away. Now, that's not possible. 
Moreover, the colors do not appear to be in any color-wheel centric order. In fact, I can't really tell how they are organized on the drop-down list at all. 

So,
1. Can we make this drop down searchable ... like the "device" drop-down, etc. where I can type in any search query? 
2. Is there some logic behind how the colors are currently organized? Can it be modified to get the colors in a more color-wheel centric order? Like, having all the purple colors together? 

Thanks!

**Comment by cigamit** [comment]
Great idea(s).  I hate the light colors coming first too.  If you can think of an order that works better, submit a pull request with it.  The function is called drop_color and can be found in lib/html_form.php.

What we need is a modify the drop color to use the autocomplete interface though.  You work on the pull request for the ordering, and I'll do the callback support.  Work?

**Comment by cigamit** [comment]
This issue has been resolved.
