### ISSUE TITLE
sequence number in edit graph item template not shown in modern theme (1.1.6)

### ISSUE THREAD

**Issue by gmuellerfr** [Cacti/cacti#736]
Hello

when I edit an item, the actual sequence number is not shown in modern theme:
![item_page_modern](https://cloud.githubusercontent.com/assets/25848039/26395117/6bbfb41e-406f-11e7-9c1d-98f051bfee4d.png)
Other themes show the number:
![item_page_paper-plane](https://cloud.githubusercontent.com/assets/25848039/26395191/994dfddc-406f-11e7-92cd-4ed95de99fa5.png)
![item_page_classic](https://cloud.githubusercontent.com/assets/25848039/26395192/9950f140-406f-11e7-8e3a-8701db7e7e42.png)
I think you should change the default colour for modern, because it's shown when selected:
![item_page_modern_selected](https://cloud.githubusercontent.com/assets/25848039/26395219/b52734f6-406f-11e7-809a-8ee55ab9bc8a.png)
Thank you for listening.
Guenter

**Comment by cigamit** [comment]
Thanks for pointing that out.  When we changed the forms to be responsive, a few of these CSS bugs passed by the QA team.  Wait, you are the QA team ;).  Thanks for using Cacti!

**Comment by cigamit** [comment]
Resolved thanks!
