### ISSUE TITLE
Graph template - multiple instances?

### ISSUE THREAD

**Issue by jayaich** [Cacti/cacti#737]
From the console tab, clicking on graph templates and selecting (for example) 'Interface - Traffic (bits/sec)', under the 'Template' section there is a checkbox for 'Multiple Instances'. The text along side it says 'Check this checkbox if there can be more than one Graph of this type per Device.'
The checkbox is unticked (by default it seems).
For a network device I would say that it is quite likely that there will be more than one network interface graph, using that template, for the device.
Is this a typo and it should say '...more than one Template of this type...'?
Does this relate to having different versions of a template?

Thanks.

**Comment by cigamit** [comment]
What this option controls is your ability, from the Graphs New UI, to create more than one of this type of Graph for a device.  It's not really intended for Data Query Templates as much as it is for Non-Data Query Templates.

Let me explain.  When you goto the Graphs New page, there is a dropdown below the Graph Templates.  As you add templates to the device, that dropdown will be reduced in number.  However, in the case of 'Multiple', you can continue to add Graphs of this type to a Device simply by selecting it from the dropdown, and pressing Create.  A good example of this is the Generic OID Template.

In the case of the Generic OID Template, you should be able to do this as many times as you wish without the dropdown item disappearing.

If you think the language is confusing, I would encourage you to submit a pull request with the revised language.  I additionally hope this explanation was clear.

**Comment by jayaich** [comment]
Okay, thanks for the explanation and example. It makes sense now.

> If you think the language is confusing...
To me, yes it is still a bit.

> I would encourage you to submit a pull request with the revised language
That's the problem. Trying to provide a clear, succinct description is a single short statement.
I can't think of one, so please feel free to close this issue if you prefer.

**Comment by cigamit** [comment]
Great.  I'll go ahead and close then.
