### ISSUE TITLE
Reporting: Duplicate Graph

### ISSUE THREAD

**Issue by smiles1969** [Cacti/cacti#74]
Choosing duplicate report option in drop down menu gives HTTP 500 error with this in the apache error log:

[Wed Nov 16 09:54:22.396052 2016] [:error] [pid 18278] [client 192.168.11.140:57265] PHP Fatal error:  Call to undefined function duplicate_report() in /var/www/html/cacti/lib/html_reports.php on line 596, referer: http://192.168.11.15/cacti/reports_admin.php

**Comment by cigamit** [comment]
Merged.
