### ISSUE TITLE
GUI doesn't remembers the open options in the graph item template option area (1.1.6)

### ISSUE THREAD

**Issue by gmuellerfr** [Cacti/cacti#740]
Hello,
the graph template allows to configure the 'Graph Template Options' in five different areas:
Common Options
Scaling Options
Grid Options
Axis Options
Legend Options
which can be all collapsed as shown below.
![graph_template_options](https://cloud.githubusercontent.com/assets/25848039/26402535/12a5a53e-408b-11e7-93e2-c31747ef757d.png)
If you collapse all and return to the previous screen, you will be faced with only the 'Common Options' heading next time you enter this sub-menu again.
![graph_template_options_collapsed](https://cloud.githubusercontent.com/assets/25848039/26402716/b4213e82-408b-11e7-9143-462646431cb7.png)
Now you can open the 'Common Options' area, but the other options stay hidden. You must return to the previous screen and open the sub-menu again to see the 'Common Options' and the 'Scaling Options' heading and so on until all 'Template Options' are visible again. Once all are visible they stay visible, but if you collapse only one you have to go again through the whole procedure. This is annoying.
This behaviour applies to all themes.
Thank you for listening.
Guenter

**Comment by cigamit** [comment]
Thanks for catching this Guenter.  Thought this was taken care of already.  Must have missed something somewhere.  This is another side affect of the responsive form re-design.

**Comment by cigamit** [comment]
Resolved, thanks for reporting.
