### ISSUE TITLE
SMTP Hostname cannot be an IP Address

### ISSUE THREAD

**Issue by iokiok** [Cacti/cacti#742]
I'm using Cacti 1.1.7.
In settings -> Mail/Reporting/DNS if I set "SMTP" for Mail Services, then in SMTP Options I have to set a hostname in the SMTP Hostname field. If I set an IP address there, then sending a test e-mail I get the error "SMTP connect() failed".
In the SMTP Hostname field description it is written that "This is the hostname/IP of the SMTP server" so I would expect that I could set a numeric IP address here...

**Comment by cigamit** [comment]
That is a red herring.  If you look at the error, the connect failed, which means you either have the wrong IP or the wrong set of ports.  If this was an issue, a real issue, we would be flooded with these bug reports already.

**Comment by iokiok** [comment]
I'm sure the IP address is correct. So even the port (465 in SSL) is correct. 
If I change the IP address with the hostname keeping the same port then it works.

**Comment by cigamit** [comment]
Attach a screen shot.  But I suspect the problem is on your side.  Not sure what it is.  You should tcpdump the connection too or even strace the php process.  That second recommendation could be messy though.

**Comment by iokiok** [comment]
I have attached a couple of screenshot and a packet capture.
If I set the hostname as an IP address you can see the error returned when I send a test email. If I set the hostname it works.
In the packet capture you can see that cacti actually contact the remote SMTP server, but something goes wrong and I get the error. 
At the beginning I thought there was an error in the php code when handling an IP address instead of a FQDN. But the packet capture shows that the hostname with the IP address is correctly handled. So now I guess the issue could be related to the SSL certificate CN that does not match the actual host name.
I could not verify it with a packet capture. I tried setting port 25 and SMTP Security = None, but the server issues STARTTLS and then the important messages are always encrypted.
