### ISSUE TITLE
Invisible login options for users

### ISSUE THREAD

**Issue by iokiok** [Cacti/cacti#743]
I'm using Cacti 1.1.7 (but I have seen the issue even in previous 1.x releases).
When I edit a user, in the General tab there is a section called "Login Options" where I can see three radio buttons without a description, so I cannot see what option I'm selecting.
I have attached a screenshot taken with Firefox 53.0.3. It seems that the description text is white or has the same colour of the background (I'm using the modern theme).
![cacti](https://cloud.githubusercontent.com/assets/28048841/26460940/a16003d2-417b-11e7-9b5b-5e53e09d977f.jpg)

**Comment by cigamit** [comment]
This is already resolved.  Just update the main.css from the modern theme and the lib/html_form.php file.
