### ISSUE TITLE
Changing graph template - legend incorrect and a spike

### ISSUE THREAD

**Issue by jayaich** [Cacti/cacti#745]
I have a standard (?) graph showing the network interface traffic bits/second in and out, and using the 64-bit counters. However, if I change the graph template to show (for example) the bytes per second, the graph legend gets messed up. It seems that the legend from both graphs are shown. The graph itself, and the vertical axis label are all correct.
I have found, however, that if I repeat the change of the graph template, to the same template again (so to bytes per second in the example above), then the graph legend gets sorted out correctly.
If I change the graph template again, back to bits per second, then the legend, graph and axes labels are all correct after the change. No need to run the change a further time.
In addition though, the graph seems to get a large spike in its data after each change. In the graph I looked at, it received a sudden 6Gb/s inbound spike. (This is the interface for a lightly used server, the interface typically shows around 100k bits/sec.) I have repeated this a few times, so my graph now has half a dozen large spikes.

I am still looking into the code for changing the graph template for another reason (it's not showing new graph templates that I have created), so if I can see what is wrong I'll put in a pull request. I'm suspecting that something is being set after the first change, but something else should also be done to the legend and it's not happening for some reason. Running the change a second time sorts the legend out because of whatever was set in the first change. Maybe :-)

**Comment by cigamit** [comment]
Well, when you change from a 32 bit to 64 bit template, you have to insure that that 'max value' is changed in the rrdfile to a good value.  We don't do that automatically.  You should edit the Data Sources and look at the max value in Info Debug mode, and if it's too low, use the RRDtool tune command to fix the RRDfile.

**Comment by jayaich** [comment]
Okay, thanks for that about the spike.
However, if I change the graph from 'In/Out Bits (64-bit Counters) to 'In/Out Bytes (64-bit Counters)' I still get the legend for both (bits and bytes) showing unless I run the change template a second time.
I'll see if I can take a further look at this tomorrow, but I already know that the code for sorting out the legends is a bit convoluted!

**Comment by cigamit** [comment]
When you change the template, we might want to force a sync template.  You can do this manually.  But before we go there, let's figure out about the RRDfiles.

**Comment by jayaich** [comment]
Quick question - for changing the graph template, and the requirement that the data sources are 'identical', do you consider (for a network interface graph) the 32-bit counters (as a data source) to be the same as the 64-bit counters - that is, these 2 are considered to be identical?
From your comment above (about using RRDtool), and from what I can see in the database, they seem to be considered identical.
