### ISSUE TITLE
Search results are not cleared on Aggregates

### ISSUE THREAD

**Issue by pautiina** [Cacti/cacti#748]
Hello.
On  Aggregates Management after searching the desired value I press `clear`. It throws me on the Details contribution. After that, I turn on the `Items tab` and look result search. 
The search results are not cleared.
![48](https://cloud.githubusercontent.com/assets/11805503/26493572/0bcdf060-4223-11e7-86ea-1eca5cad6b10.png)
![49](https://cloud.githubusercontent.com/assets/11805503/26493571/0bcbad5a-4223-11e7-83cf-a73e0d8b6c13.png)
![50](https://cloud.githubusercontent.com/assets/11805503/26493570/0bcaa658-4223-11e7-8951-6585bf190351.png)

**Comment by pautiina** [comment]
This bug also have issuse #739

**Comment by cigamit** [comment]
Resolved.
