### ISSUE TITLE
[SPINE] Compiling

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#75]
$ automake --add-missing
configure.ac:12: warning: AM_INIT_AUTOMAKE: two- and three-arguments forms are deprecated.  For more info, see:
configure.ac:12: http://www.gnu.org/software/automake/manual/automake.html#Modernize-AM_005fINIT_005fAUTOMAKE-invocation

Debian Jessie 
automake 1:1.15-5

**Comment by cigamit** [comment]
Resolved here: https://github.com/Cacti/spine/commit/f0ab801c70b4ec817c9c1c30795902d7bb393747
