### ISSUE TITLE
Validation error for variable 1.1.7

### ISSUE THREAD

**Issue by cciethor** [Cacti/cacti#765]
Hi Fresh installation of 1.1.7 

If i go to any graph then zooming and debugging button then zoomed any span then pressing ultuily view in order to reset the zoom level i get the below 
![capture](https://cloud.githubusercontent.com/assets/27223122/26619723/5d42394c-45e8-11e7-9ca0-5272bc798ccd.JPG)

Validation error for variable local_graph_id, with value of "nav". See backtrace below for more details.
(/graph.php: 38 get_filter_request_var)(/lib/html_utility.php: 423 die_html_input_error)(/lib/html_validate.php: 60 cacti_debug_backtrace)

**Comment by cigamit** [comment]
Can you explain how you got to this point?

**Comment by cciethor** [comment]
please follow the below snapshot 

1- Go to any graph and press zooming and debugging 
![1capture](https://cloud.githubusercontent.com/assets/27223122/26677164/5f7415b4-46d3-11e7-991b-e43e43152ccf.JPG)

2- zoom in to any period 
![2capture](https://cloud.githubusercontent.com/assets/27223122/26677205/8f5e24c2-46d3-11e7-9628-86458b4ac804.JPG)

3- press ultuily view  from top 
![3capture](https://cloud.githubusercontent.com/assets/27223122/26677220/a10e9864-46d3-11e7-8bc8-135be025d454.JPG)

4- error 
![4capture](https://cloud.githubusercontent.com/assets/27223122/26677226/a91f0200-46d3-11e7-822f-33398f65a868.JPG)

**Comment by cigamit** [comment]
Perfect thanks.

**Comment by cigamit** [comment]
Resolved.  Found additional issues on that page related to regressions associated ajaxQ implelmentation.
