### ISSUE TITLE
A question about Chinese characters

### ISSUE THREAD

**Issue by 311villagehead** [Cacti/cacti#768]
I am Chinese.  In cacti 1.1.7，as shown in Figure 1，the tree name  is incompatible with Chinese characters.It may come out “？？？”.  How can I solve it?
![image](https://cloud.githubusercontent.com/assets/29101156/26639880/9e61f910-4658-11e7-947d-eaaf0205f23c.png)

**Comment by cigamit** [comment]
Please dump your tables graph_tree and graph_tree_items and attach here.  Should include those characters.

**Comment by 311villagehead** [comment]
OK，for example  


![qq 20170601095425](https://cloud.githubusercontent.com/assets/29101156/26661449/5fbbcf80-46b0-11e7-80cc-1ff3f19f105a.png)

if press save，it come up “”？？？“”


![qq 20170601095604](https://cloud.githubusercontent.com/assets/29101156/26661585/33df8fc2-46b1-11e7-8740-51c24f4b5603.png)

**Comment by cigamit** [comment]
What version is this?  What is your database table charset?  What browser?  The attached are Firefox.  I don't know how to read it, but much of it looks Chinese.  The examples below are using charset UTF8 and Cacti 1.1.7+.

To change the charset from Linux, using a bash shell, you could run this command:

for table in `mysql -e "show tables in cacti" | grep -v Tables_in`;do echo "Convertaing $table";mysql -e "alter table $table charset=utf8" cacti;done

![treesinchinesework](https://cloud.githubusercontent.com/assets/957322/26752851/cce813a6-481e-11e7-8a23-d0f472255b74.PNG)
![treesinchinesework2](https://cloud.githubusercontent.com/assets/957322/26752856/d1db57c4-481e-11e7-99c9-355bfe0476cc.PNG)
