### ISSUE TITLE
Latest Cacti Build: Data Query under device doesn't properly display # of objects

### ISSUE THREAD

**Issue by ikorzha** [Cacti/cacti#769]
Latest Cacti Build: Data Query under device doesn't properly display # of objects
Please see screenshot below under "Success" Column"

![data-query](https://cloud.githubusercontent.com/assets/11211789/26641530/e85430f2-45f8-11e7-8a60-b8c5e989ba60.jpg)

**Comment by cigamit** [comment]
Resolved.  I marked it for the wrong issue though.  Thanks for catching this one.
