### ISSUE TITLE
After update 0.8.8b - 1.1.7  old graphs is ok, but after create new grpaph -  error

### ISSUE THREAD

**Issue by Izmenoff** [Cacti/cacti#772]
Cacti doesn't create a new graphs and rra files, but works fine with old
2017-06-01 12:34:04 - CMDPHP ERROR: There are no RRA's assigned to local_data_id: 21858.
2017-06-01 12:34:04 - CMDPHP ERROR: There are no RRA's assigned to local_data_id: 21853.
2017-06-01 12:34:04 - CMDPHP ERROR: There are no RRA's assigned to local_data_id: 21850.

**Comment by cigamit** [comment]
Is this happening all over the place, or sporadic?  Can you post a screen shot of your Data Source Profiles page?

**Comment by Izmenoff** [comment]
all over place. sorry, I droped the cacti and installed fresh with a new DB 02.06.2017, 02:12, "Jimmy Conner" <notifications@github.com>:Is this happening all over the place, or sporadic? Can you post a screen shot of your Data Source Profiles page?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by hb9xar** [comment]
I ran into the same issue. Seems that the update procedure does fail to populate/update  the data_source_profiles_rra table - it was empty in my case. This update failure was also mentioned in the web based DB update step.

After manually inserting 4 RRA definitions, creation of RRD files did work again - the missing RRD files were created as well.
`
> insert into data_source_profiles_rra (data_source_profile_id,name,steps,`rows`) values(1,'RRA 5min',1,600);
> insert into data_source_profiles_rra (data_source_profile_id,name,steps,`rows`) values(1,'RRA 30min',6,700);
> insert into data_source_profiles_rra (data_source_profile_id,name,steps,`rows`) values(1,'RRA 1d',288,600);
> insert into data_source_profiles_rra (data_source_profile_id,name,steps,`rows`) values(1,'RRA 2h',24,600);
`

**Comment by tosiara** [comment]
Same issue on 1.20. Manually created data source doesn't have rra
```
2017/09/05 10:15:03 - CMDPHP ERROR: There are no RRA's assigned to local_data_id: 20.
2017/09/05 10:15:03 - CMDPHP ERROR: There are no RRA's assigned to local_data_id: 21.
2017/09/05 10:15:03 - CMDPHP ERROR: There are no RRA's assigned to local_data_id: 22.
2017/09/05 10:15:03 - CMDPHP ERROR: There are no RRA's assigned to local_data_id: 23.
```
