### ISSUE TITLE
Under Graphs: "Device Tree" doesn't expand horizontally if device name doesn't fit in default pane size

### ISSUE THREAD

**Issue by ikorzha** [Cacti/cacti#774]
In the latest Cacti build 1.1.8 Under Graphs: "Device Tree" doesn't auto expand horizontally if device name doesn't fit in default pane size.
I have tested the same node functionally under 0.8.8h and it auto expands without an issue.
See screenshot below:
![tree-pane](https://cloud.githubusercontent.com/assets/11211789/26680791/b09fc5e4-46a8-11e7-8fd9-b7f342c5eeed.jpg)
Device: "Device:E1Z07R11U41-C3650-AWS-A" get cut off on the right hand side.
Please let me know if you have any clarification questions.

**Comment by cigamit** [comment]
I think this is by design.  Other themes allow changing the with.

**Comment by cigamit** [comment]
If you want this fixed, open a pull request with your changes.  I will close for now.  Looking forward to your pull request.
