### ISSUE TITLE
SQL Error with MariaDB 10.2

### ISSUE THREAD

**Issue by OUnagiles** [Cacti/cacti#777]
Hello,

We are experiencing the following SQL error with our installation, Cacti version 1.1.6:

> 2017-06-01 10:29:11 - DBCALL ERROR: SQL Assoc Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'rows FROM host_snmp_cache WHERE host_id = '2' GROUP BY snmp_query_id ' at line 1
>
>2017-06-01 10:29:11 - DBCALL ERROR: SQL Assoc Failed!, Error:1064, SQL:"SELECT snmp_query.id, snmp_query.name, host_snmp_query.reindex_method, items.items, rows.rows FROM snmp_query INNER JOIN host_snmp_query ON snmp_query.id = host_snmp_query.snmp_query_id AND host_snmp_query.host_id = ? LEFT JOIN ( SELECT snmp_query_id, COUNT(*) AS items FROM host_snmp_cache WHERE host_id = ? GROUP BY snmp_query_id ) AS items ON items.snmp_query_id = snmp_query.id LEFT JOIN ( SELECT snmp_query_id, COUNT(DISTINCT snmp_index) AS rows FROM host_snmp_cache WHERE host_id = ? GROUP BY snmp_query_id ) AS rows ON rows.snmp_query_id = snmp_query.id ORDER BY snmp_query.name"

The error appears to be generated by navigating to Console > Devices > SOME_DEVICE
Additionally, no values are populated under the "Associated Data Queries" header. 

Our instance is running on RHEL 7, and uses MariaDB 10.2.6

Thanks!

**Comment by cigamit** [comment]
Assuming this is resolved.  Thanks Patrick!

**Comment by reboot1983** [comment]
Would be nice if @OUnagiles could confirm if it's working now.

**Comment by OUnagiles** [comment]
The change appears to have fixed the problem. Thanks!

**Comment by reboot1983** [comment]
Nice! Thanks for your feedback.
