### ISSUE TITLE
Cacti 1.1.7 - Reporting issue (legend is not showed)

### ISSUE THREAD

**Issue by jpobeda** [Cacti/cacti#780]
Hi there,

As I understand (?) if select "thumbnails" the graph_nolegend is set to true BUT I'm not selecting thumbnails for my report and It's not showing the legends up.

I posted in the cacti forum looking for someone else to advise on this matter but nothing so far.

http://forums.cacti.net/viewtopic.php?f=21&t=57544

Looking at the first picture you see there is no legend even I haven't chose thumbnails.

![cacti_forum_1](https://cloud.githubusercontent.com/assets/13456559/26708693/8e1146c0-47a1-11e7-9284-b45d57deb25d.png)

Looking at this picture is what I'd thought It'd show

![cacti_forum_2](https://cloud.githubusercontent.com/assets/13456559/26708692/8e0d58c6-47a1-11e7-95a4-a2d653ab2c41.png)

If this is not a bug can we add the option?

**Comment by cigamit** [comment]
There is a thumbnail checkbox options on the Details tab, but it's not working.  So, this is a bug.

**Comment by cigamit** [comment]
Okay, it works in the actual emailed report, but not the preview.

**Comment by cigamit** [comment]
Resolved.  Nice graphs by the way.
