### ISSUE TITLE
polling interval

### ISSUE THREAD

**Issue by aivivanov** [Cacti/cacti#784]
Are we still supposed to set for the purpose of polling, a scheduled task executing /cacti/poller.php ? If that is the case how it is supposed to collect data at intervals less than a minute. I have played a lot and even though i am setting correctly a data profile with corresponding RRAs with first RRA at 15 seconds and then setting scheduled task to execute every 15 seconds it seems that the poller.php has some checks in the code and expects the cron interval to be either 60 or 300 seconds and does not collect data every 15 seconds. It measures the time between executions and does not allow collecting data at smaller intervals. From another perspective i see that with the default cacti installation are coming data profiles with polling interval set at 30 seconds. We even have the possibility to set it as less as 10 seconds. But how we are supposed to actually schedule getting data at intervals less than a minute? Please advise.

**Comment by cigamit** [comment]
This is more of a questions for the forums.  However, with that said.  First, assuming that you are starting from a new install, you need to establish a set of Data Source Profiles that provide the RRDfile setup that you are looking for including polling frequency, timespans (aka row count) for each profile.  Once you have this completed, you can change the default Data Source Profile for all of your Data Templates.  This can be done in batch.  Technically, a system can have Data Templates, and therefore Data Sources that can be set at various poller intervals.

Finally, before creating your first graph, set your poller interval to the minimum of all your Data Source Profiles expected poller interval, and insure that your cron interval is in line with the actual crontab.

From that point, you can create away.  It's very important to perform these planning steps before you go hog wild with creating graphs of course.  In this version of Cacti it's so easy just to point Cacti at a subnet and swallow all the devices whole, which you need hold off on till your system is ready.

Finally, if you wish to use differing Data Source Profiles per Data Template, make sure you click "Use Per-Data Source Value" when updating the Data Template.  And note that for Data Query Graph Templates, there is currently an enhancement request to place this default at the Data Query level.  This enhancement is still pending.

**Comment by aivivanov** [comment]
Thanks! Works perfect.
