### ISSUE TITLE
data profile rra aggregation 1 minute

### ISSUE THREAD

**Issue by aivivanov** [Cacti/cacti#786]
I do not see currently a possibility to add 2-nd level aggregation RRA with aggregation level of 1 minute, when for example the first RRA is set at every 15 seconds.

**Comment by ronytomen** [comment]
Please ask your question on the forums. :)

**Comment by cigamit** [comment]
Reopening.  This is a bug.

**Comment by cigamit** [comment]
This issue is resolved.  Thanks for reporting.

**Comment by aivivanov** [comment]
Thanks!
