### ISSUE TITLE
[1.1.8] Fails on PHP Fatal error if LDAP auth enabled

### ISSUE THREAD

**Issue by dtucny** [Cacti/cacti#788]
Commit ca8c8cd1233437be0b285ea0871c2d8febaa8b9b appears to have cause bad breakage in the 1.1.8 release.

A number of calls to version_compare have been updated to cacti_version_compare, a function that requires 3 args, but, calls to version_compare only pass 2. 500 Server Error is the result...

[04-Jun-2017 19:45:28 America/Los_Angeles] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function cacti_version_compare(), 2 passed in /var/www/pine.us.tucny.com/cacti-1.1.8/lib/auth.php on line 1799 and exactly 3 expected in /var/www/pine.us.tucny.com/cacti-1.1.8/lib/functions.php:4733
Stack trace:
#0 /var/www/pine.us.tucny.com/cacti-1.1.8/lib/auth.php(1799): cacti_version_compare('1.1.8', '1.0.0')
#1 /var/www/pine.us.tucny.com/cacti-1.1.8/lib/auth.php(571): user_perms_valid('1')
#2 /var/www/pine.us.tucny.com/cacti-1.1.8/include/global_arrays.php(1241): is_realm_allowed(22)
#3 /var/www/pine.us.tucny.com/cacti-1.1.8/include/global.php(322): include_once('/var/www/pine.u...')
#4 /var/www/pine.us.tucny.com/cacti-1.1.8/include/auth.php(27): include('/var/www/pine.u...')
#5 /var/www/pine.us.tucny.com/cacti-1.1.8/index.php(25): include('/var/www/pine.u...')
#6 {main}
  thrown in /var/www/pine.us.tucny.com/cacti-1.1.8/lib/functions.php on line 4733

**Comment by ronytomen** [comment]
Investigating...

**Comment by ronytomen** [comment]
What authentication method are you set to use?

**Comment by dtucny** [comment]
@ronytomen using local, but, I have LDAP enabled too.

**Comment by ronytomen** [comment]
Ok, that what I expected, I failed to test around LDAP being enabled.

Fixing and pushing another release.

**Comment by cigamit** [comment]
I would just add a default operator to make it more like PHPs version_compare.  Like this
`function cacti_version_compare($version1, $version2, $operator = '>') {`

**Comment by ronytomen** [comment]
@dtucny please try the commit in e7174c40461996b11abe0088c87e811164a22900 on your installation.

**Comment by dtucny** [comment]
@ronytomen successful auth and into the console... Looking good.

**Comment by ronytomen** [comment]
Ok, pushing 1.1.9, sorry for this mess...
