### ISSUE TITLE
[Cacti 1.1.9] "Clear button" with no function

### ISSUE THREAD

**Issue by DavidLiedke** [Cacti/cacti#789]
On following pages the "clear" button has no function:

Management:
Sites
Trees
Graphs
Data Sources
Aggregate

Data Collection:
*ALL*

Templates:
*ALL*

Presents:
*ALL*

![chrome_2017-06-05_10-40-59](https://cloud.githubusercontent.com/assets/25581728/26777074/28a160b2-49dc-11e7-925c-7b0aeaf7e980.png)

**Comment by jpobeda** [comment]
Agree. I found the same.

**Comment by cigamit** [comment]
Resolved.
