### ISSUE TITLE
DBCALL ERROR: SQL Assoc Failed!, Error: You have an error in your SQL syntax 1.1.9

### ISSUE THREAD

**Issue by cciethor** [Cacti/cacti#794]
Hi 

Version 1.1.9 whenever i want to create legacy graph and want to add items and data source i got 

Error: Save Failed: Field Input Error (Check Red Fields).

and below error in log .

2017/06/06 01:48:24 - CMDPHP SQL Backtrace: (/graphs.php: 76 form_actions)(/graphs.php: 793 db_fetch_assoc)(/lib/database.php: 343 db_fetch_assoc_prepared)(/lib/database.php: 384 cacti_debug_backtrace)
2017/06/06 01:48:24 - DBCALL ERROR: SQL Assoc Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') AND dtd.local_data_id > 0' at line 1
2017/06/06 01:48:24 - DBCALL ERROR: SQL Assoc Failed!, Error:1064, SQL:'SELECT DISTINCT dtd.local_data_id FROM data_template_data AS dtd INNER JOIN data_template_rrd AS dtr ON dtr.local_data_id=dtd.local_data_id INNER JOIN graph_templates_item AS gti ON dtr.id=gti.task_item_id WHERE gti.local_graph_id NOT IN(251) AND dtr.local_data_id IN() AND dtd.local_data_id > 0'

**Comment by cciethor** [comment]
It seems the issue from modern theme as i was able to create legacy graph from classic theme.

**Comment by cigamit** [comment]
Resolved.  Thanks for reporting.
