### ISSUE TITLE
Cacti-spine installed issue

### ISSUE THREAD

**Issue by cocke** [Cacti/cacti#795]
Before compile, you must manually change the username and password in spine.h to the correct local username and password. 

If you do not modify the file directly, the system will use the default username and password "cactiuser", 

even after installation, you modify the correct local username and password in the  spine. conf  file ,when you  use the spine engine, it will still use the default  username and password “cactiuser”，is it an issue？

**Comment by ronytomen** [comment]
Are you sure your spine.conf is in the correct location? 

This has never been reported as an issue before.

There are 4 config paths defined to be checked for the spine configuration file:
```#define CONFIG_PATHS 4
#define CONFIG_PATH_1 ""
#define CONFIG_PATH_2 "/etc/"
#define CONFIG_PATH_3 "/etc/cacti/"
#define CONFIG_PATH_4 "../etc/"```
*Note:* The first one is the location of the spine executable.

**Comment by cocke** [comment]
First of all, thank you for your reply!
I put the spine.conf file into the /etc and  /usr/local/spine/etc ，Put these two positions is ok?
If the compiler does not modify the spine.h file, even if the two configuration files are no problem, spine engine is still not normal use,
This phenomenon can be reproduced, I was in 1.1.7,1.1.9 version of the time have been reproduced

**Comment by ronytomen** [comment]
Please ask for support on the [forums](http://forums.cacti.net).

I would suggest only putting the confirmation file in one location and make sure SELinux is not causing you problems.

**Comment by cocke** [comment]
SElinux is disabled, I also tried only spine.conf configuration file on / etc, the result is the same.
If the decision is not a problem, then I will update each before the first spine.c file, and then compile.
