### ISSUE TITLE
Cacti 1.1.9 - Cosmetic issue when selecting devices

### ISSUE THREAD

**Issue by jpobeda** [Cacti/cacti#798]
Hi there,

Post in Cacti Forum: http://forums.cacti.net/viewtopic.php?f=21&t=57565

It seems to be buggy compared to other menus.

![cacti_devices_ 798](https://user-images.githubusercontent.com/13456559/26853636-e69018a8-4b66-11e7-82ee-d03aec200a61.gif)

**Comment by ronytomen** [comment]
Ok, I need to know how you created an animated GIF of a screen capture!   Very cool!

Yes, that is broken!

**Comment by jpobeda** [comment]
I downloaded this, for windows https://github.com/NickeManarin/ScreenToGif

**Comment by DavidLiedke** [comment]
A second tool is: 
https://getsharex.com/

**Comment by cigamit** [comment]
Resolved.
