### ISSUE TITLE
Cacti 1.1.9 - Validation error when creating new DS

### ISSUE THREAD

**Issue by jpobeda** [Cacti/cacti#799]
Hi,

When I try to add new data sources to a device I get this error. It was working on prior releases.

> Validation error for variable host_id, with value of "XXXXXf32". See backtrace below for more details.
> (/data_sources.php: 49 form_save)(/data_sources.php: 104 get_filter_request_var)(/lib/html_utility.php: 423 die_html_input_error)(/lib/html_validate.php: 60 cacti_debug_backtrace)

![cacti_ds_ 799_2](https://user-images.githubusercontent.com/13456559/26908591-a6971096-4c4f-11e7-8129-5a378ab1f51a.png)

I attached an screenshot with DS template, but I don't think there is something wrong with it since there are more than 300 DS associated.

![cacti_ds_ 799](https://user-images.githubusercontent.com/13456559/26854509-8e5c6a16-4b6a-11e7-927e-c5b169e55bf7.png)

Apart from that error, nothing on clog.

**Comment by cigamit** [comment]
This issue was resolved here: https://github.com/Cacti/cacti/commit/f613b6d20a1881bdfe4890bba96480716f806d02
