### ISSUE TITLE
Cacti 1.1.9 - Unchecked loop in lib/html_utility.php causing race condition

### ISSUE THREAD

**Issue by jpobeda** [Cacti/cacti#800]
Hi there,

I've just set longitude and latitude for a site and some how didn't like it.

I'm getting this in /var/log/httpd/error_log

> [Wed Jun 07 14:05:32.118863 2017] [:error] [pid 3045] [client XXX.YY.ZZ.128:63834] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /usr/share/cacti-1.1.9/lib/html_utility.php on line 70
> [Wed Jun 07 14:06:52.459845 2017] [:error] [pid 17526] [client XXX.YY.ZZ.128:63904] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /usr/share/cacti-1.1.9/lib/html_utility.php on line 67, referer: https://cacti2.xxx.yy.zz/cacti/sites.php
> [Wed Jun 07 14:14:19.274867 2017] [:error] [pid 27892] [client XXX.YY.ZZ..128:64118] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /usr/share/cacti-1.1.9/lib/html_utility.php on line 71, referer: https://cacti2.xxx.yy.zz/cacti/sites.php
> [Wed Jun 07 14:16:05.204863 2017] [:error] [pid 11871] [client XXX.YY.ZZ..128:64168] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /usr/share/cacti-1.1.9/lib/html_utility.php on line 70, referer: https://cacti2.xxx.yy.zz/cacti/sites.php

I have to wait until it gives up, otherwise I can't do anything and apache process goes to heaven.

Every time I try to edit that site happens the same, how can I safely undo this change?

It seems to only kill the session trying to access that site, I tried from 2 different browsers and when the first one was dying I could browse Cacti normally on the second one until I tried to edit that site on the second one..

Does this make any sense?

**Comment by ronytomen** [comment]
I was able to reproduce the problem.

```
2017/06/06 22:34:02 - ERROR PHP ERROR: Maximum execution time of 30 seconds exceeded in file: /home/troman/cacti/repo/git/cacti/lib/html_utility.php on line: 70
2017/06/06 22:34:02 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4402 cacti_debug_backtrace)
```

**Comment by cigamit** [comment]
Resolved.  Thanks for reporting!
