### ISSUE TITLE
Cacti 1.1.9 Can't export the Graph Rules and Tree Rules

### ISSUE THREAD

**Issue by stokleyzhou** [Cacti/cacti#801]
When i try to export the templates for Graph Rules and Tree Rules, the output file only contain:

< cacti>
< /cacti>

**Comment by cigamit** [comment]
Oops, those options slipped into the 1.1.9 release under the cover of darkness (in other words, I screwed up).  Thanks for noticing.  Now, I guess this feature goes to the top of the list.

Currently, those options are not functional.  Please be patient.

**Comment by cigamit** [comment]
I've rolled this back for now.

**Comment by stokleyzhou** [comment]
OK, thanks.
