### ISSUE TITLE
1.1.9 Authentication Cookies not working

### ISSUE THREAD

**Issue by cciethor** [Cacti/cacti#804]
Since upgraded to 1.1.9 Authentication Cookies are no longer working and i have to relogin again after a while .

**Comment by cigamit** [comment]
Are you accessing Cacti through a NAT?  Do you have a timezone sync issue on your client or server?  Nothing has changed in this part of cacti for a while.

**Comment by cciethor** [comment]
No i am not using NAT and no time sync issue on the server or client ,  it seems sometimes it's working and sometime it's not , i will try to get exactly how and when it's not working and reopen the issue

**Comment by cigamit** [comment]
The authentications cookies are cleared after 90 days of no user, and if you press the button 'Logout Everywhere' under the user profile.  It can also happen if you truncate the cookies table manually.  Also, if you clear your cookies, or you virus scanner clears cookies, or if you disable cookies, this feature does not work.  For example, if you are using an Incogneto Window and try to login, it won't work.
