### ISSUE TITLE
failed install Spine on MariaDB 10.2

### ISSUE THREAD

**Issue by Izmenoff** [Cacti/cacti#806]
discussion on the cacti forum - http://forums.cacti.net/viewtopic.php?f=2&t=57563

libtool: link: gcc -I/usr/include/mysql -g -O2 -o spine sql.o spine.o util.o snmp.o locks.o poller.o nft_popen.o php.o ping.o keywords.o error.o -L/usr/lib64 -lssl -lmysqlclient -lcrypto -lz -lpthread -lm
/usr/bin/ld: cannot find -lmysqlclient

but, all dependenses has been installed
CentOS 7
PHP 7.1.5
NET-SNMP 5.7.2
RRDTool 1.6
MariaDB-common-10.2.6-1.el7.centos.x86_64
MariaDB-client-10.2.6-1.el7.centos.x86_64
MariaDB-shared-10.2.6-1.el7.centos.x86_64
MariaDB-server-10.2.6-1.el7.centos.x86_64
MariaDB-compat-10.2.6-1.el7.centos.x86_64
MariaDB-devel-10.2.6-1.el7.centos.x86_64

See more at: https://mariadb.com/resources/blog/mariadb-102-beta
Other useful enhancements
libmysqlclient has been removed from the server. It has been replaced by MariaDB’s own Connector/C.
INFORMATION_SCHEMA includes USER_VARIABLES which lists all user defined variables.
EXPLAIN FORMAT=JSON has been expanded to include the used sort_key in filesort and outer_ref_condition in SELECTs.
Analytical query performance improvement - If a derived table, view or CTE includes a GROUP BY clause it would be internally processed with temporary tables, which would then be materialized and used by the parent query. If the parent query has restrictions on the GROUP BY columns, this new optimization applies them early to exclude non-matching groups from materialization.

**Comment by cigamit** [comment]
Please open this bug in the Spine area.  Thanks!
