### ISSUE TITLE
Multiple Instances checkbox in graph template seems to be broken

### ISSUE THREAD

**Issue by stormonts** [Cacti/cacti#807]
In various graph templates, I have checked the "Multiple Instances" checkbox, thinking that is what would allow Graph Templates on the "New Graphs" page to stay selectable after one had already been created, but they become greyed out after one graph is created.  Similarly, when using the command line "add graphs.php" to try and create two of the same graph, I have to use the --force option in order for more graphs using the same template to be created.  Am I totally misunderstanding how this feature works or is it broken?

![image](https://user-images.githubusercontent.com/25824323/26950069-6d24d8f0-4c6a-11e7-833a-4c0d73e8813b.png)

![image](https://user-images.githubusercontent.com/25824323/26950144-aa3b2992-4c6a-11e7-9bd9-4efdac30de42.png)

**Comment by cigamit** [comment]
Actually, the way it works is different, though this is a good idea.  Let me explain first how it works.  On the first graph instance, you will use the checkbox, on subsequent instances, you use the dropdown just below the non-query templates, select the graph template, and then click the Create Button.  Though I think it might be easier to enhance the graph creation the way you have described it for graphs with the 'Multiple' flag.

**Comment by stormonts** [comment]
So if the "multiple instance" template isn't checked in a graph, it won't even show up in the drop down, correct?

The way I described would definitely save some clicks, but since nothing is broken I guess I'll change my post to a "feature request".  Thanks for the explanation.


________________________________

**Comment by cigamit** [comment]
This issue is resolved in this commit https://github.com/Cacti/cacti/commit/f52e0834a4ff00ce9cd90ba330e2327cc9dfdbfa
