### ISSUE TITLE
cacti 1.1.9: scripts in packages have different content than in scripts directory

### ISSUE THREAD

**Issue by paulgevers** [Cacti/cacti#810]
While figuring out what to do in Debian with the default templates, I noticed that the content of the packages provided by cacti in install/templates/* isn't equal to the content of the scripts in the scripts directory. While this may be harmless in the one script I checked (ss_net_snmp_disk_io.php: only white spaces, including different line-ends), this suggests that the packages aren't recreated automatically when the source in the scripts directory changes.

**Comment by paulgevers** [comment]
This is causing automated tests in Debian to now fail (as I loaded the templates during installation). I'll need to prevent these files from changing during installation of the templates.

https://piuparts.debian.org/sid/fail/cacti_1.1.10+ds1-4.log

**Comment by cigamit** [comment]
I'm guessing the solution would be to simply remove the files from the default installation, and let the packages dictate.  Wouldn't you agree?

**Comment by paulgevers** [comment]
@cigamit I fixed the issue for Debian (I think I did it conceptually wrong to start with), but the bug for cacti still hold: shouldn't the content be the same?

**Comment by ronytomen** [comment]
@paulgevers is this still an issue for Debian?  If so, can you provide more detail so I can resolve this in the packaging process?

**Comment by paulgevers** [comment]
@ronytomen in Debian this isn't an issue anymore because I install the cacti package during install of the Debian package with the privileges of www-data. www-data doesn't have write permissions to the files and cacti is fine with it. If you still want to know if the files are different from me, I can do some experiments.

**Comment by paulgevers** [comment]
Additional to loads of white space, this is what I have after importing
install/templates/Local_Linux_Machine.xml.gz
install/templates/Generic_SNMP_Device.xml.gz
install/templates/NetSNMP_Device.xml.gz
install/templates/Cisco_Router.xml.gz

paul@testavoira /usr/share/cacti/site/scripts $ diff -rw . ~/cacti/scripts/
diff -rw ./ping.pl /home/paul/cacti/scripts/ping.pl
17c17
< ($host) = $host =~ /^([\w.-]+)$/;
---
> ($host) = $host =~ /^([\w.:-]+)$/;
24c24
< open(PROCESS, "ping -c 1 $host 2>&1 | grep -E '(icmp_[s|r]eq.*time|unknown host|Unknown host)' 2>/dev/null |");
---
> open(PROCESS, "ping -c 1 $host 2>&1 | grep -E '(icmp_[s|r]eq.*time|unknown host|Unknown host|not supported)' 2>/dev/null |");
29c29
< if (($ping =~ 'unknown host') || ($ping =~ 'Unknown host')) {
---
> if (($ping =~ 'unknown host') || ($ping =~ 'Unknown host') ||  ($ping =~ 'not supported')) {

**Comment by cigamit** [comment]
Okay, thanks for the details, resolved.
