### ISSUE TITLE
Strangely broken template

### ISSUE THREAD

**Issue by gerdesj** [Cacti/cacti#813]
(Cacti 1.1.9)

I've somehow managed to create a graph template that seems to include a data source template that does not appear in the GUI for the graph template's list of sources.  I'm not exactly sure how but this template was created by duplicating another one which did have that data source in it.

I ended up exporting the graph template plus deps and importing it into a clean install of Cacti system on my laptop, deleting the extra data source, and exporting the cleaned up template.  I then deleted any graphs based on the template from the original Cacti.  Finally I imported the cleaned up template and all is well (I think).  I did notice a red item in the import mentioning a missing data source but a graph based on the "new" template looks correct when I view the rrdgraph command line.

I did a diff on the before and after templates and I am none the wiser as to how it all hangs together. 

The graph template should simply have two data sources relating to local and remote VDSL power levels.  If you import it you will find that another data source relating to line speed is somehow linked and has a CDEF in the rrdgraph but it does not list as a data source in the graph definition in the GUI.

Edit:  I've removed the original .zip and added the graph template that the above was copied from - it seems to have an additional CDEF AVERAGE in it that only appears in the generated rrdgraph command but does not appear in the list of items that I added to the graph.   When I duplicated it, the new template inherited the extra bit, I think.

[original_problem_template.zip](https://github.com/Cacti/cacti/files/1073041/original_problem_template.zip)

**Comment by cigamit** [comment]
Can you please point out which items in the XML file are the ones that broke the template please.  Please indicate the specific hash.

**Comment by gerdesj** [comment]
Now I've actually read through the template I attached I can't seem to find it 8(  

I'm pretty sure I can recreate this problem from scratch.  It will take a while for me to spin up a new VM with a clean Cacti.  

I'll close this issue and open a new one with better information.
