### ISSUE TITLE
Allow 'Save' feature from New Graphs

### ISSUE THREAD

**Issue by TViktor** [Cacti/cacti#814]
Cannot set Default Graph type in New Graph section
I choose from drop-down list, click Set default button. But when I try to create graphs for another host, settings not remembered.

Cacti Version 1.1.10

**Comment by cigamit** [comment]
Please upload screen shots.  This is working perfectly in my environment.

**Comment by TViktor** [comment]
I open create graph, the type for network statistics is CBL APC Load
Then I select In/Out Bits and press "Set default" button
After page refresh the type is again CBL APC Load

The same problem with other type of graphs, like memory stats etc.

A tried to change default in IE and Mozilla FF browser.

My cacti was upgraded from 0.8.7i to 1.1.10

![1](https://user-images.githubusercontent.com/29289881/27572018-d4b691a2-5b4c-11e7-8de1-7357986dfa85.jpg)
![2](https://user-images.githubusercontent.com/29289881/27572019-d4b93380-5b4c-11e7-86a6-0245d9d22f0f.jpg)
![3](https://user-images.githubusercontent.com/29289881/27572020-d4dc5b26-5b4c-11e7-9329-02295eefa1ff.JPG)

**Comment by cigamit** [comment]
Are there any errors in the Cacti log after you press the set default button?  If you open the browsers Debug Console, can you see the callback being called when you press that button as well?

**Comment by TViktor** [comment]
There is nothing in log. I tried to put file graphs_new.php in debug mode, but no effect.

When a press save button browser detects GET request to server (on screenshot).
As I see in code, it calls save_default_query_option(); function, but its not show "Defaults Setting Saved".
It seems, call not working.

![button](https://user-images.githubusercontent.com/29289881/27775719-1a734682-5fe8-11e7-9901-ee853b84b2ba.JPG)

**Comment by TViktor** [comment]
In additional. When I have several drop-down lists on page, will save_default_query_option(); gather information correctly?
![lists](https://user-images.githubusercontent.com/29289881/27776241-47447768-5fec-11e7-855e-0dc86b138e41.JPG)

**Comment by cigamit** [comment]
The 'Set Default' only operates on the current Query.  Additionally, are you asking for a 'Save' button on that page to save the default 'View'?

**Comment by TViktor** [comment]
Ok, when I have only one 'Query' on page, 'Set Default' works! Thanks.
Yes, it will be great to save default 'View' via one Button on page.

**Comment by cigamit** [comment]
Resolved, thanks!
