### ISSUE TITLE
Five minutes of data can't be saved for one year

### ISSUE THREAD

**Issue by babyfenei** [Cacti/cacti#816]
**I want to save five minutes for six months to one year.
I need a RRAs has
Daily (5 Minute Average)
Weekly (5 Minute Average)
Monthly (5 Minute Average)
Yearly (5 Minute Average)**
![image](https://user-images.githubusercontent.com/22876759/27207646-0855b372-5273-11e7-8767-da165cbb338a.png)

**I created a New Profiles in the Console - preset - Data Profiles, and when I added RRAs, only the first line of RRAs's Aggregation Level chose Each Insert is New Row for five minutes.But when I add a second row of RRAs (for example, five minutes of data for a week),I can't choose for five minutes in the Aggregation Level, just over 10 minutes.**
![image](https://user-images.githubusercontent.com/22876759/27207771-cde170c2-5273-11e7-9c3b-8320ddb1e804.png)

**Comment by ronytomen** [comment]
This is not a coding issue.

Please ask on the [Forums](http://forums.cacti.net) for assistance.
