### ISSUE TITLE
1.1.10 [Discovery Automation]

### ISSUE THREAD

**Issue by scline** [Cacti/cacti#817]
This is an odd issue we just noticed when using THOLD + Cacti Automated network discovery.

We have several thold templates assigned to a device template and when scanning/inserting devices via Network Discovery some tholds are not created. All graphs that use `Data Queries` work fine, however any using a simple `Graph Query` never gets created.

If I navigate to the Device page and run `Apply Thresholds` this gets all the tholds we expect to see. There are no apparent errors in cacti log files to explain this behavior :(

**Comment by scline** [comment]
Figured a workaround, though unsure if this is by design. It looks like if the setting `Enable Automatic Graph Creation` is disabled we see the issue I explained above. With that enabled those tholds are created via network automation.

Feel free to close if this is expected, we originally had that option disabled since it appeared redundant when using network automation.

**Comment by ronytomen** [comment]
I am going to close this issue.

In the future, because the Plugin is involved, typically we like these issues to be posted with in the Plugins issue tracker.  And if a fix to Cacti is needed, then it will be done and committed or an issue in the Cacti issue tracker will be created.
