### ISSUE TITLE
Unable to save un-selected Spike Kill templates in Cacti settings

### ISSUE THREAD

**Issue by ikorzha** [Cacti/cacti#818]
In latest Cacti 1.1.10  in Console->Settings->Spikes-> Batch Spike Kill Settings
I am unable to to un-save previously selected templates. In other words once un-selected, and save bottom clicked, same templates that were previously selected come back.

![spikes](https://user-images.githubusercontent.com/11211789/27261533-c9457e0a-5412-11e7-82ae-e0fa6a1794ff.jpeg)

**Comment by cigamit** [comment]
Oh, that's bad.

**Comment by cigamit** [comment]
I have confirmed that I can un-select these in 1.1.10/1.1.11 without issue.  Are there any errors going into your cacti.log?  Can you run the following command and post the results:

`SELECT * FROM settings WHERE name='spikekill_templates';`

**Comment by ikorzha** [comment]
See output below. spike kill is aware of of selected templates.  (nothing in log file pertaining to this issue).

I have just re-tesed, I want to add that YES I can un-select and have minimum 1 template in spikekill.
___________________________________________________________________________________________________
## Correction to the original issue: I am unable to select "NONE" and save or unable to un-select the very last  checked template (in other words make it none).  Please test such scenario.   


mysql> SELECT * FROM settings WHERE name='spikekill_templates';
+---------------------+-------+
| name                | value |
+---------------------+-------+
| spikekill_templates | 38,36 |
+---------------------+-------+
1 row in set (0.00 sec)

**Comment by cigamit** [comment]
Okay, thanks for the corrected case.  I am now able to reproduce and it is now resolved.

**Comment by ikorzha** [comment]
Thank you cigamit, I tested the fix works perfectly now !
