### ISSUE TITLE
Customized timespan for graphs

### ISSUE THREAD

**Issue by hadeshimself** [Cacti/cacti#819]
Currently the graph timespan in graph.php for each RRA name is calculated according to the RRA properties (steps, rows, etc). Sometimes this is not a good reference, specially for high rate collection profiles or profiles with larger precision and faster polling rates (30 seconds, etc). It would be nice to have a configurable timespan parameter for each of those RRAs to allow a more customized presentation.

**Comment by ikorzha** [comment]
I agree with you hope Cacti team would address this deficiency
Here is my example, I have 1min RRA setup for 2 month pretension in RRDs.
Look what kind of mess it introduces when, the graph is called from THOLD:
It shows 2 month worth of graph data without any drill in ability instead of perhaps last 1hr or 2hr.
![mess](https://user-images.githubusercontent.com/11211789/27297444-e09da9f2-54f2-11e7-824d-abf6ed9c997a.jpeg)

**Comment by cigamit** [comment]
I actually de-contented that during the design of Data Source Profiles thinking that it was not too important.  After doing so, I realized that it was important for the MRTG view and could be useful in other areas as well.

**Comment by cigamit** [comment]
Resolved, please review the commit change very carefully.

**Comment by ikorzha** [comment]
Cigamit, I was able to test and validate the fix for customized time span!
Thank you so much, based on testing I have conducted so far, I do not see any issues with fix you have introduced customized time span works as expected.

Thank you once again for dedicated work.

**Comment by cigamit** [comment]
Good to know.  I also changed the form so that you can update the timespan when the profile is read only as updating the timespan does not alter the RRDfiles.

**Comment by ikorzha** [comment]
I have validated "the new edit timespan" commit. Yes I can click on it and see what is currently defined.
However when I change timespan lets say from 2hr to 4hr and click save, I get Error msg below.

![commit-819](https://user-images.githubusercontent.com/11211789/29003284-e9f04e06-7a81-11e7-9361-a95827a4a935.jpeg)

**Comment by cigamit** [comment]
Thanks for testing.  Fixed now.

**Comment by ikorzha** [comment]
Tested hot fix. Confirmed save now works!
Thanks.
