### ISSUE TITLE
Cacti creates rra file with incorect permissions

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#82]
Cacti do:
ls -la
-rw-------    1 root root     111392 lis 18 11:25 1013.rrd

instead of:

ls -la
-rw-r--r-- 1 www-data root 111392 lis 18 11:25 1013.rrd

Making imposible to view in UI.

Debian 8.6.

Temporarly I use crontab to check permisions and make it right when it's not propper but the solution is bad for long term.

**Comment by cigamit** [comment]
Cacti doesn't attempt to set the permissions, its done by your system config.  Most likely you have a umask of 077 or some such on your system.  I would check your /etc/login.prefs or /etc/profile or ~/.profile
