### ISSUE TITLE
Detecting resource change in /var/www/html/plugins  "error in logic" in multi poller setup

### ISSUE THREAD

**Issue by ikorzha** [Cacti/cacti#820]
Hi, I have introduced a single test weathermap into:  /var/www/html/plugins/weathermap/configs/
that runs on per min basis.  Because weathermap writes maps into output folder and has ability to write .html and .png /var/www/html/plugins/weathermap/ folder it introduces a per min cache updates that causes poller delay runs due to resource updates and replication of updated files to remote pollers.

2017/06/19 12:51:02 - POLLER: Poller[1] NOTE: Detecting Resource Change. Updating Resource Cache for '/var/www/html/plugins' 

I believe, this is a really bad approach to replicate weathermap data from primary poller to remote pollers.
Perhaps this folder /var/www/html/plugins/weathermap/ should be excluded from replication to avoid major performance hit on poller.

**Comment by ronytomen** [comment]
My first thought is adding a facility to allow the plugin developer to control what content of the plugin, if any, needs to be replicated to the remote poller.

**Comment by ikorzha** [comment]
That is a good approach, I can offer another approach from perspective of Cacti administrator:
Add a facility in Cacti settings where a cacti administrator such as myself can add a folder path "one per line"
to exclude from cache and replication to other pollers...

**Comment by cigamit** [comment]
What are the file extensions that get written to those paths?

**Comment by ikorzha** [comment]
Thank you so much for your consideration in this issue:
In folder "/plugins/weathermap/" extensions written are: .html and .png
In folder "/plugins/weathermap/configs/" extensions written are: .conf
In folder "/plugins/weathermap/output/" extensions written are: .html .png and .txt

**Comment by cigamit** [comment]
Yes, this is definitely something I think that plugins should handle themselves initially (otherwise every person that uses that plugin will have to add the paths).  But we can then also possibly add the option for custom paths (maybe via another plugin :) )

**Comment by ikorzha** [comment]
Sounds like all options on a table are "long term" solutions, however the issue is immediate and pressing.
Lots of people use weathermap plugin, once Howie completes the development of 1,0 weathermap it would be messy for many not just early adopters such as myself. Maybe least path of resistance would be exclude weathermap pluging from caching. The weathermap "tab" is not available/shown on remote pollers anyway.
Please let me know what is your consideration on this matter.

**Comment by cigamit** [comment]
We will be doing a release either Monday or Tuesday.  By then, this will be resolved.

**Comment by cigamit** [comment]
The exclusion of sub-directories is trivial, but the main plugin directory is a tough one.  Are you certain there are files written to the root of the weathermap directory?  If so, what is the frequency of that writing?

**Comment by ikorzha** [comment]
I am 100% percent certain that files are being written to weathermap root folder. Files are being written to root folder at same frequency as Cacti poller. So if poller set to 1 min than every min...

However this "feature" (writing of map compiled html and image file)  is an optional one in individual map configuration config and can be avoided by map creator.
I would be very happy if you can just exclude the output and configs folder it would be a very big win.

Below are the screenshot of my prod system showing maps being written to root:
![root](https://user-images.githubusercontent.com/11211789/27721472-87b95612-5d2e-11e7-9776-6e594b7175ce.jpeg)

This is a map configuration property screen:  If "Output Image Filename" and "Output HTML Filename" are filled in, then these files will be written to weathermap root at same frequency as cacti poller execution under normal circumstances..

![map-propoerties](https://user-images.githubusercontent.com/11211789/27721491-989947ee-5d2e-11e7-9dbf-a234a77a253e.jpeg)

**Comment by cigamit** [comment]
Sync the development branch and then add the following to the Weathermaps INFO file:

nosync: directory1, directory2, ..., *.extension1, *.extension2

Then, for good measure, run the following two queries to flush things out.  Try to do this between polling cycles:

DELETE FROM settings WHERE name LIKE 'md5%';
TRUNCATE TABLE poller_resource_cache;

Should be resolved after that.  Commit where this was fixed.  https://github.com/Cacti/cacti/commit/ac652e4df8f6e2d00e8a98f5b0af17273cc64bff

**Comment by cigamit** [comment]
Please inform Howie of this required change for his plugin.

**Comment by ikorzha** [comment]
Thank you so much I will work with Howie on changes to weathermap...
