### ISSUE TITLE
SNMP Error

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#821]
WARNING: Result from SNMP not valid. Partial Result: U
2017/06/20 09:30:04 - CMDPHP PHP ERROR WARNING Backtrace: (/cmd.php: 650 cacti_snmp_session_get)(/lib/snmp.php: 502 get)(CactiErrorHandler)(/lib/functions.php: 4363 cacti_debug_backtrace)
2017/06/20 09:30:04 - ERROR PHP WARNING: SNMP::get(): Invalid object identifier: ..1.3.6.1.4.1.14988.1.1.1.2.1.19.228.141.140.17.220.125.2 in file: /var/www/html/cacti/lib/snmp.php on line: 502 

What do You need for debuging?

**Comment by cigamit** [comment]
Looks like there are two dot's at the beginning of the OID.  Can you please check the poller cache?

**Comment by interduo** [comment]
Yes, thats right. The problem was doubled .. at OOID.

The template of the graph is 'Mikrotik - TX + RX signal'.

**Comment by cigamit** [comment]
If this is a problem with the formal plugin, please open a bug there.
