### ISSUE TITLE
aggregation graph (item - data source) [1.1.10]

### ISSUE THREAD

**Issue by dzemba1986** [Cacti/cacti#822]
I have problem with aggregation graph. Don't read data source. Details in the file.
![cacti](https://user-images.githubusercontent.com/8969907/27331873-aec013d4-55bf-11e7-986f-5b1636dc0ccd.png)

And no change after save (still none).

**Comment by cigamit** [comment]
Please explain how you got to this GUI?

**Comment by dzemba1986** [comment]
Aggregates -> click any"Graph Title" -> click "Graph Item".
![cacti](https://user-images.githubusercontent.com/8969907/27785361-a2f3ab42-5fdd-11e7-8d03-cf2db70f7249.png)

Even if I change something and save on this page, nothing change.

E.g. I try change "Opacity/Alpha Channel". When I click, it become disable. 
![cacti1](https://user-images.githubusercontent.com/8969907/27785726-cea5bf22-5fde-11e7-915a-ce7e0a63ddc8.png)

**Comment by cigamit** [comment]
Yea, after a code review, that is because in the current design, you were not supposed to be able to edit them.  Funny how in the redesign after 0.7.5, the author did not catch that one design mistake.  I guess we'll have to call it a bug.  Need to consult with the original authors on this one.

**Comment by cigamit** [comment]
For now, I am going to remove this feature as it has undefined behavior.  We are looking at a feature described as a 'Combined' graph that will look much like an Aggregate, but will be modifiable as a normal graph item.  You can track this feature here: https://github.com/Cacti/cacti/issues/793

**Comment by cigamit** [comment]
Resolved for now.
