### ISSUE TITLE
[Feature Request] - Parameter to hide Graph Filter and Tree List in Tree Mode

### ISSUE THREAD

**Issue by vvf7** [Cacti/cacti#823]
Hello,
In the Tree View there is no option to hide panel on the left side of view (with trees list) and Graph Filter panel. As a result it is impossible to show a tree on a screen that hangs on a wall because the panels occupy a lot of useful space.
In 0.8.x versions of cacti, for example, there is an option to show or hide Time Span selector.

**Comment by cigamit** [comment]
The tree itself can be hidden by simply clicking on the Graphs tab a second time, or resizing your browser.  On the filter side, there is a filter class under development that will allow the filter to be hidden.  I've simply had no time to finish the work.

**Comment by cigamit** [comment]
With the exception of the Classic theme, this has been resolved here: https://github.com/Cacti/cacti/commit/f8b5a058f5ce1f552a750a5193d365d5420c5acb
