### ISSUE TITLE
Any Method for Automating Installation Wizard?

### ISSUE THREAD

**Issue by alex-d-w4** [Cacti/cacti#826]
I am currently working on a kickstart file to setup a minimal CentOS 6 build with Cacti up and running with minimal to no user-side setup needed. Currently, I have all of the prerequisite items functional such as MySQL, snmp, PHP, and all of the command line stuff working. However, I need to figure out if there is a script way to get past the browser prompts, especially since most of the defaults will suffice. Additionally, if I could also set the new password through this method, that would also be ideal.

I have already tried and failed at using cURL with various approaches, and the lack of documentation and queries for anyone that wanted to do this is also not helping. Does anyone here have any insight or resource to solve this? I am not absolutely required to do this, but it would be of great benefit.

I am currently using Cacti 1.1.6.

**Comment by jhg03a** [comment]
Not a move in the right direction, but have you considered PhantomJS?

**Comment by cigamit** [comment]
Just like my old CactiEZ CD?  All I did was do a test install of Cacti, then export the DB, and used that one instead of the original cacti.sql.
You should look at the kickstart script on the CactiEZ CD also.

**Comment by alex-d-w4** [comment]
I didn't know about CactiEZ, I'll definitely take a look at the ks script there. Also I'm kinda new to MySQL so I didn't even think about exporting the database after install. Thanks!
