### ISSUE TITLE
HTTPD returns a 500 error code when accessing cacti after updating from 1.1.7 to 1.1.10

### ISSUE THREAD

**Issue by david-hill** [Cacti/cacti#829]
Description of problem:
Following latest update, cacti is returning a HTTP 500 error code

[Tue Jun 20 22:06:48.408807 2017] [php7:error] [pid 14032] [client 192.168.1.22:64944] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 262144 bytes) in /usr/share/cacti/lib/database.php on line 293
[Tue Jun 20 22:06:48.409168 2017] [php7:error] [pid 14032] [client 192.168.1.22:64944] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 262144 bytes) in Unknown on line 0
[Tue Jun 20 22:06:51.942498 2017] [php7:error] [pid 14031] [client 192.168.1.22:64945] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 262144 bytes) in /usr/share/cacti/lib/database.php on line 293
[Tue Jun 20 22:06:51.942905 2017] [php7:error] [pid 14031] [client 192.168.1.22:64945] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 262144 bytes) in Unknown on line 0

Version-Release number of selected component (if applicable):

How reproducible:
Always

Steps to Reproduce:
1. Upgrade from 1.1.7-1 to 1.1.10-1
2.
3.

Actual results:
See above logs
Jun 19 18:06:46 DEBUG ---> Package cacti.noarch 1.1.7-1.fc27 will be upgraded
Jun 19 18:06:46 DEBUG ---> Package cacti.noarch 1.1.10-1.fc27 will be an upgrade
 cacti          

Expected results:
no failures

Additional info:
trying to rollback now to previous known working version
rollbacking to 1.1.7 solves this issue
memory_limit was updated from 16M to 512M as a test
updating from 1.1.7 to 1.1.8 does the same thing.

cacti logs:
20170625 10:50:45 - DBCALL DEVEL: SQL Cell: "SELECT cacti FROM version LIMIT 1"
20170625 10:51:39 - DBCALL DEVEL: SQL Cell: "SELECT cacti FROM version LIMIT 1"

apache logs:

[Sun Jun 25 10:51:39.886511 2017] [php7:error] [pid 21862] [client 192.168.1.22:54330] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 262144 bytes) in /usr/share/cacti/lib/database.php on line 293
[Sun Jun 25 10:51:39.886924 2017] [php7:error] [pid 21862] [client 192.168.1.22:54330] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 262144 bytes) in Unknown on line 0

Code:

  if (!is_object($db_conn)) {
    $db_conn = $database_sessions["$database_hostname:$database_port:$database_default"];

    if (!is_object($db_conn)) {
      return false;
    }

See BZ [1] for original report.

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1463471

**Comment by cigamit** [comment]
I believe that this will be corrected in Cacti 1.1.11.  There was a feature introduced in 1.1.10 for the format of date output that caused a recursion loop in lib/functions.php.  This has subsequently been resolved.  If you update to the latest GitHub development branch, does the problem still exist?

**Comment by david-hill** [comment]
Hello sir,

    I've tested the 1.1.11 branch and I still get the 500 error code:

[Wed Jun 28 08:02:27.525607 2017] [php7:error] [pid 14519] [client 192.168.1.22:58904] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in /usr/share/cacti.git/lib/functions.php on line 225, referer: http://192.168.1.3/cacti/install/index.php


Thank you very much,

David Hill

On 6/28/2017 6:50 AM, Jimmy Conner wrote:

I believe that this will be corrected in Cacti 1.1.11. There was a feature introduced in 1.1.10 for the format of date output that caused a recursion loop in lib/functions.php. This has subsequently been resolved. If you update to the latest GitHub development branch, does the problem still exist?

**Comment by cigamit** [comment]
I just updated lib/functions.php a few minutes ago.  Please try again.  Sorry for the confusion.

**Comment by david-hill** [comment]
Hello sir,

   I just re-tested it with the latest commits and it still gives me a 500:


[Wed Jun 28 08:22:33.115963 2017] [php7:error] [pid 25948] [client 192.168.1.22:51625] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in /usr/share/cacti.git/lib/database.php on line 298
[Wed Jun 28 08:22:33.116258 2017] [php7:error] [pid 25948] [client 192.168.1.22:51625] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in /usr/share/cacti.git/lib/functions.php on line 4403

Thanks,

Dave

On 6/28/2017 8:16 AM, Jimmy Conner wrote:

I just updated lib/functions.php a few minutes ago. Please try again. Sorry for the confusion.

**Comment by cigamit** [comment]
What's in your cacti.log file?

**Comment by cigamit** [comment]
Could it be that you can't write to cacti.log?  Change permissions to 777 on it just in case.

**Comment by david-hill** [comment]
[root@zappa cacti]# ls -altr cacti.log
-rw-rw-r--. 1 cacti apache 3294401963 Jun 28 08:40 cacti.log


I have lots of data in cacti.log and this is the log found before the 500:

20170628 08:47:30 - DBCALL DEVEL: SQL Cell: "SELECT cacti FROM version LIMIT 1"
20170628 08:47:30 - DBCALL DEVEL: SQL Cell: "SELECT user_auth.id    FROM settings    INNER JOIN user_auth    ON user_auth.username = settings.value    WHERE settings.name = 'guest_user'"
20170628 08:47:30 - DBCALL DEVEL: SQL Cell: "SHOW TABLES LIKE 'settings_user'"
20170628 08:47:30 - DBCALL DEVEL: SQL Row: "SELECT value   FROM settings_user   WHERE name = ?   AND user_id = ?"
2017/06/28 08:47:30 - DBCALL DEVEL: SQL Cell: "SHOW TABLES LIKE 'plugin_hooks'"
2017/06/28 08:47:30 - DBCALL DEVEL: SQL Assoc: "SELECT pc.id, ph.name, ph.file, ph.function  FROM plugin_hooks AS ph  LEFT JOIN plugin_config AS pc  ON pc.directory = ph.name  WHERE ph.status = 1 AND hook = ?  ORDER BY id ASC"
2017/06/28 08:47:30 - DBCALL DEVEL: SQL Assoc: "SELECT * FROM plugin_realms ORDER BY plugin, display"
2017/06/28 08:47:30 - DBCALL DEVEL: SQL Assoc: "SELECT DISTINCT gt.id, gt.name FROM graph_templates AS gt INNER JOIN graph_templates_item AS gti ON gt.id=gti.graph_template_id INNER JOIN data_template_rrd AS dtr ON gti.task_item_id=dtr.id WHERE gti.local_graph_id=0 AND data_source_type_id IN (3,2) ORDER BY name"
2017/06/28 08:47:30 - DBCALL DEVEL: SQL Cell: "SHOW TABLES LIKE 'plugin_config'"
2017/06/28 08:47:30 - DBCALL DEVEL: SQL Assoc: "SELECT directory AS id, name  FROM plugin_config  WHERE status=1"
2017/06/28 08:47:30 - DBCALL DEVEL: SQL Cell: "SHOW TABLES LIKE 'plugin_hooks'"
2017/06/28 08:47:30 - DBCALL DEVEL: SQL Assoc: "SELECT pc.id, ph.name, ph.file, ph.function  FROM plugin_hooks AS ph  LEFT JOIN plugin_config AS pc  ON pc.directory = ph.name  WHERE ph.status = 1 AND hook = ?  ORDER BY id ASC"
2017/06/28 08:47:30 - DBCALL DEVEL: SQL Cell: "SHOW TABLES LIKE 'plugin_hooks'"
2017/06/28 08:47:30 - DBCALL DEVEL: SQL Assoc: "SELECT pc.id, ph.name, ph.file, ph.function  FROM plugin_hooks AS ph  LEFT JOIN plugin_config AS pc  ON pc.directory = ph.name  WHERE ph.status = 1 AND hook = ?  ORDER BY id ASC"
2017/06/28 08:47:30 - DBCALL DEVEL: SQL Cell: "SHOW TABLES LIKE 'plugin_hooks'"
2017/06/28 08:47:30 - DBCALL DEVEL: SQL Assoc: "SELECT pc.id, ph.name, ph.file, ph.function  FROM plugin_hooks AS ph  LEFT JOIN plugin_config AS pc  ON pc.directory = ph.name  WHERE ph.status = 1 AND hook = ?  ORDER BY id ASC"
2017/06/28 08:47:30 - DBCALL DEVEL: SQL Cell: "SHOW TABLES LIKE 'plugin_hooks'"
2017/06/28 08:47:30 - DBCALL DEVEL: SQL Assoc: "SELECT pc.id, ph.name, ph.file, ph.function  FROM plugin_hooks AS ph  LEFT JOIN plugin_config AS pc  ON pc.directory = ph.name  WHERE ph.status = 1 AND hook = ?  ORDER BY id ASC"
20170628 08:47:30 - DBCALL DEVEL: SQL Cell: "SELECT cacti FROM version LIMIT 1"
20170628 08:47:30 - DBCALL DEVEL: SQL Cell: "SELECT user_auth.id    FROM settings    INNER JOIN user_auth    ON user_auth.username = settings.value    WHERE settings.name = 'guest_user'"
20170628 08:47:30 - DBCALL DEVEL: SQL Cell: "SHOW TABLES LIKE 'settings_user'"
20170628 08:47:30 - DBCALL DEVEL: SQL Row: "SELECT value   FROM settings_user   WHERE name = ?   AND user_id = ?"
2017/06/28 08:47:30 - DBCALL DEVEL: SQL Assoc: "SELECT DISTINCT gt.id, gt.name FROM graph_templates AS gt INNER JOIN graph_templates_item AS gti ON gt.id=gti.graph_template_id INNER JOIN data_template_rrd AS dtr ON gti.task_item_id=dtr.id WHERE gti.local_graph_id=0 AND data_source_type_id IN (3,2) ORDER BY name"
2017/06/28 08:47:30 - DBCALL DEVEL: SQL Cell: "SHOW TABLES LIKE 'plugin_config'"
2017/06/28 08:47:30 - DBCALL DEVEL: SQL Assoc: "SELECT directory AS id, name  FROM plugin_config  WHERE status=1"
2017/06/28 08:47:31 - DBCALL DEVEL: SQL Cell: "SELECT cacti FROM version LIMIT 1"
20170628 08:47:33 - DBCALL DEVEL: SQL Cell: "SELECT cacti FROM version LIMIT 1"
20170628 08:47:33 - DBCALL DEVEL: SQL Cell: "SELECT user_auth.id    FROM settings    INNER JOIN user_auth    ON user_auth.username = settings.value    WHERE settings.name = 'guest_user'"
20170628 08:47:33 - DBCALL DEVEL: SQL Cell: "SHOW TABLES LIKE 'settings_user'"
20170628 08:47:33 - DBCALL DEVEL: SQL Row: "SELECT value   FROM settings_user   WHERE name = ?   AND user_id = ?"
2017/06/28 08:47:33 - DBCALL DEVEL: SQL Assoc: "SELECT DISTINCT gt.id, gt.name FROM graph_templates AS gt INNER JOIN graph_templates_item AS gti ON gt.id=gti.graph_template_id INNER JOIN data_template_rrd AS dtr ON gti.task_item_id=dtr.id WHERE gti.local_graph_id=0 AND data_source_type_id IN (3,2) ORDER BY name"
2017/06/28 08:47:33 - DBCALL DEVEL: SQL Cell: "SHOW TABLES LIKE 'plugin_config'"
2017/06/28 08:47:33 - DBCALL DEVEL: SQL Assoc: "SELECT directory AS id, name  FROM plugin_config  WHERE status=1"
2017/06/28 08:47:33 - DBCALL DEVEL: SQL Cell: "SELECT cacti FROM version LIMIT 1"
2017/06/28 08:47:33 - DBCALL DEVEL: SQL Assoc: "SHOW COLUMNS FROM mysql.time_zone_name"
2017/06/28 08:47:33 - DBCALL DEVEL: SQL Cell: "SELECT COUNT(*) FROM mysql.time_zone_name"
2017/06/28 08:47:33 - DBCALL DEVEL: SQL Assoc: "SHOW GLOBAL VARIABLES"
20170628 08:47:36 - DBCALL DEVEL: SQL Cell: "SELECT cacti FROM version LIMIT 1"
20170628 08:47:36 - DBCALL DEVEL: SQL Cell: "SELECT user_auth.id    FROM settings    INNER JOIN user_auth    ON user_auth.username = settings.value    WHERE settings.name = 'guest_user'"
20170628 08:47:36 - DBCALL DEVEL: SQL Cell: "SHOW TABLES LIKE 'settings_user'"
20170628 08:47:36 - DBCALL DEVEL: SQL Row: "SELECT value   FROM settings_user   WHERE name = ?   AND user_id = ?"
2017/06/28 08:47:36 - DBCALL DEVEL: SQL Assoc: "SELECT DISTINCT gt.id, gt.name FROM graph_templates AS gt INNER JOIN graph_templates_item AS gti ON gt.id=gti.graph_template_id INNER JOIN data_template_rrd AS dtr ON gti.task_item_id=dtr.id WHERE gti.local_graph_id=0 AND data_source_type_id IN (3,2) ORDER BY name"
2017/06/28 08:47:36 - DBCALL DEVEL: SQL Cell: "SHOW TABLES LIKE 'plugin_config'"
2017/06/28 08:47:36 - DBCALL DEVEL: SQL Assoc: "SELECT directory AS id, name  FROM plugin_config  WHERE status=1"
2017/06/28 08:47:36 - DBCALL DEVEL: SQL Cell: "SELECT cacti FROM version LIMIT 1"
20170628 08:47:38 - DBCALL DEVEL: SQL Cell: "SELECT cacti FROM version LIMIT 1"
20170628 08:47:38 - DBCALL DEVEL: SQL Cell: "SELECT user_auth.id    FROM settings    INNER JOIN user_auth    ON user_auth.username = settings.value    WHERE settings.name = 'guest_user'"
20170628 08:47:38 - DBCALL DEVEL: SQL Cell: "SHOW TABLES LIKE 'settings_user'"
20170628 08:47:38 - DBCALL DEVEL: SQL Row: "SELECT value   FROM settings_user   WHERE name = ?   AND user_id = ?"
2017/06/28 08:47:38 - DBCALL DEVEL: SQL Assoc: "SELECT DISTINCT gt.id, gt.name FROM graph_templates AS gt INNER JOIN graph_templates_item AS gti ON gt.id=gti.graph_template_id INNER JOIN data_template_rrd AS dtr ON gti.task_item_id=dtr.id WHERE gti.local_graph_id=0 AND data_source_type_id IN (3,2) ORDER BY name"
2017/06/28 08:47:38 - DBCALL DEVEL: SQL Cell: "SHOW TABLES LIKE 'plugin_config'"
2017/06/28 08:47:38 - DBCALL DEVEL: SQL Assoc: "SELECT directory AS id, name  FROM plugin_config  WHERE status=1"
2017/06/28 08:47:38 - DBCALL DEVEL: SQL Cell: "SELECT cacti FROM version LIMIT 1"
2017/06/28 08:47:38 - DBCALL DEVEL: SQL Cell: "SELECT `value` FROM `settings` WHERE name = 'graph_watermark'"
2017/06/28 08:47:38 - DBCALL DEVEL: SQL Cell: "SELECT status FROM plugin_config WHERE directory = ?"
2017/06/28 08:47:38 - DBCALL DEVEL: SQL Cell: "SELECT status FROM plugin_config WHERE directory = ?"
2017/06/28 08:47:38 - DBCALL DEVEL: SQL Cell: "SELECT status FROM plugin_config WHERE directory = ?"
2017/06/28 08:47:38 - DBCALL DEVEL: SQL Cell: "SELECT status FROM plugin_config WHERE directory = ?"
2017/06/28 08:47:38 - DBCALL DEVEL: SQL Cell: "SELECT status FROM plugin_config WHERE directory = ?"
2017/06/28 08:47:38 - DBCALL DEVEL: SQL Cell: "SELECT status FROM plugin_config WHERE directory = ?"
2017/06/28 08:47:38 - DBCALL DEVEL: SQL Cell: "SELECT status FROM plugin_config WHERE directory = ?"
2017/06/28 08:47:38 - DBCALL DEVEL: SQL Cell: "SELECT status FROM plugin_config WHERE directory = ?"
2017/06/28 08:47:38 - DBCALL DEVEL: SQL Cell: "SELECT status FROM plugin_config WHERE directory = ?"
2017/06/28 08:47:38 - DBCALL DEVEL: SQL Cell: "SELECT status FROM plugin_config WHERE directory = ?"
2017/06/28 08:47:38 - DBCALL DEVEL: SQL Cell: "SELECT status FROM plugin_config WHERE directory = ?"
2017/06/28 08:47:38 - DBCALL DEVEL: SQL Cell: "SELECT status FROM plugin_config WHERE directory = ?"
2017/06/28 08:47:38 - DBCALL DEVEL: SQL Cell: "SELECT status FROM plugin_config WHERE directory = ?"
2017/06/28 08:47:38 - DBCALL DEVEL: SQL Cell: "SELECT status FROM plugin_config WHERE directory = ?"
2017/06/28 08:47:38 - DBCALL DEVEL: SQL Cell: "SELECT status FROM plugin_config WHERE directory = ?"
2017/06/28 08:47:38 - DBCALL DEVEL: SQL Cell: "SELECT status FROM plugin_config WHERE directory = ?"
2017/06/28 08:47:38 - DBCALL DEVEL: SQL Cell: "SELECT status FROM plugin_config WHERE directory = ?"
2017/06/28 08:47:38 - DBCALL DEVEL: SQL Cell: "SELECT status FROM plugin_config WHERE directory = ?"
2017/06/28 08:47:38 - DBCALL DEVEL: SQL Cell: "SELECT status FROM plugin_config WHERE directory = ?"
2017/06/28 08:47:38 - DBCALL DEVEL: SQL Cell: "SELECT status FROM plugin_config WHERE directory = ?"
20170628 08:47:42 - DBCALL DEVEL: SQL Cell: "SELECT cacti FROM version LIMIT 1"
20170628 08:47:42 - DBCALL DEVEL: SQL Cell: "SELECT user_auth.id    FROM settings    INNER JOIN user_auth    ON user_auth.username = settings.value    WHERE settings.name = 'guest_user'"
20170628 08:47:42 - DBCALL DEVEL: SQL Cell: "SHOW TABLES LIKE 'settings_user'"
20170628 08:47:42 - DBCALL DEVEL: SQL Row: "SELECT value   FROM settings_user   WHERE name = ?   AND user_id = ?"
2017/06/28 08:47:42 - DBCALL DEVEL: SQL Assoc: "SELECT DISTINCT gt.id, gt.name FROM graph_templates AS gt INNER JOIN graph_templates_item AS gti ON gt.id=gti.graph_template_id INNER JOIN data_template_rrd AS dtr ON gti.task_item_id=dtr.id WHERE gti.local_graph_id=0 AND data_source_type_id IN (3,2) ORDER BY name"
2017/06/28 08:47:42 - DBCALL DEVEL: SQL Cell: "SHOW TABLES LIKE 'plugin_config'"
2017/06/28 08:47:42 - DBCALL DEVEL: SQL Assoc: "SELECT directory AS id, name  FROM plugin_config  WHERE status=1"
2017/06/28 08:47:42 - DBCALL DEVEL: SQL Cell: "SELECT cacti FROM version LIMIT 1"
2017/06/28 08:47:42 - DBCALL DEVEL: SQL Exec: "DELETE FROM version"
2017/06/28 08:47:42 - DBCALL DEVEL: SQL Exec: "INSERT INTO version (cacti) VALUES ('1.1.11')"
20170628 08:47:42 - DBCALL DEVEL: SQL Cell: "SELECT cacti FROM version LIMIT 1"
20170628 08:47:42 - DBCALL DEVEL: SQL Cell: "SELECT user_auth.id    FROM settings    INNER JOIN user_auth    ON user_auth.username = settings.value    WHERE settings.name = 'guest_user'"
20170628 08:47:42 - DBCALL DEVEL: SQL Cell: "SHOW TABLES LIKE 'settings_user'"
20170628 08:47:42 - DBCALL DEVEL: SQL Row: "SELECT value   FROM settings_user   WHERE name = ?   AND user_id = ?"
2017/06/28 08:47:42 - DBCALL DEVEL: SQL Cell: "SHOW TABLES LIKE 'plugin_hooks'"
2017/06/28 08:47:42 - DBCALL DEVEL: SQL Assoc: "SELECT pc.id, ph.name, ph.file, ph.function  FROM plugin_hooks AS ph  LEFT JOIN plugin_config AS pc  ON pc.directory = ph.name  WHERE ph.status = 1 AND hook = ?  ORDER BY id ASC"
2017/06/28 08:47:42 - DBCALL DEVEL: SQL Assoc: "SELECT * FROM plugin_realms ORDER BY plugin, display"
2017/06/28 08:47:42 - DBCALL DEVEL: SQL Assoc: "SELECT DISTINCT gt.id, gt.name FROM graph_templates AS gt INNER JOIN graph_templates_item AS gti ON gt.id=gti.graph_template_id INNER JOIN data_template_rrd AS dtr ON gti.task_item_id=dtr.id WHERE gti.local_graph_id=0 AND data_source_type_id IN (3,2) ORDER BY name"
2017/06/28 08:47:42 - DBCALL DEVEL: SQL Cell: "SHOW TABLES LIKE 'plugin_config'"
2017/06/28 08:47:42 - DBCALL DEVEL: SQL Assoc: "SELECT directory AS id, name  FROM plugin_config  WHERE status=1"
2017/06/28 08:47:42 - DBCALL DEVEL: SQL Cell: "SHOW TABLES LIKE 'plugin_hooks'"
2017/06/28 08:47:42 - DBCALL DEVEL: SQL Assoc: "SELECT pc.id, ph.name, ph.file, ph.function  FROM plugin_hooks AS ph  LEFT JOIN plugin_config AS pc  ON pc.directory = ph.name  WHERE ph.status = 1 AND hook = ?  ORDER BY id ASC"
2017/06/28 08:47:42 - DBCALL DEVEL: SQL Cell: "SHOW TABLES LIKE 'plugin_hooks'"
2017/06/28 08:47:42 - DBCALL DEVEL: SQL Assoc: "SELECT pc.id, ph.name, ph.file, ph.function  FROM plugin_hooks AS ph  LEFT JOIN plugin_config AS pc  ON pc.directory = ph.name  WHERE ph.status = 1 AND hook = ?  ORDER BY id ASC"
2017/06/28 08:47:42 - DBCALL DEVEL: SQL Cell: "SHOW TABLES LIKE 'plugin_hooks'"
2017/06/28 08:47:42 - DBCALL DEVEL: SQL Assoc: "SELECT pc.id, ph.name, ph.file, ph.function  FROM plugin_hooks AS ph  LEFT JOIN plugin_config AS pc  ON pc.directory = ph.name  WHERE ph.status = 1 AND hook = ?  ORDER BY id ASC"
2017/06/28 08:47:42 - DBCALL DEVEL: SQL Cell: "SHOW TABLES LIKE 'plugin_hooks'"
2017/06/28 08:47:42 - DBCALL DEVEL: SQL Assoc: "SELECT pc.id, ph.name, ph.file, ph.function  FROM plugin_hooks AS ph  LEFT JOIN plugin_config AS pc  ON pc.directory = ph.name  WHERE ph.status = 1 AND hook = ?  ORDER BY id ASC"
2017/06/28 08:47:42 - DBCALL DEVEL: SQL Cell: "SHOW TABLES LIKE 'plugin_hooks'"
2017/06/28 08:47:42 - DBCALL DEVEL: SQL Assoc: "SELECT pc.id, ph.name, ph.file, ph.function  FROM plugin_hooks AS ph  LEFT JOIN plugin_config AS pc  ON pc.directory = ph.name  WHERE ph.status = 1 AND hook = ?  ORDER BY id ASC"
2017/06/28 08:47:42 - DBCALL DEVEL: SQL Row: "SELECT id, username     FROM user_auth     WHERE username = ?"
2017/06/28 08:47:42 - DBCALL DEVEL: SQL Cell: "SELECT user_id       FROM user_auth_cache       WHERE user_id = ?      AND token = ?"
2017/06/28 08:47:42 - DBCALL DEVEL: SQL Cell: "SELECT id FROM user_auth WHERE username = ?"
2017/06/28 08:47:42 - DBCALL DEVEL: SQL Exec: "DELETE FROM user_auth_cache WHERE user_id = ? AND token = ?"
2017/06/28 08:47:42 - DBCALL DEVEL: SQL Exec: "REPLACE INTO user_auth_cache   (user_id, hostname, last_update, token)   VALUES   (?, ?, NOW(), ?)"
2017/06/28 08:47:42 - AUTH LOGIN: User 'admin' Authenticated via Authentication Cookie
2017/06/28 08:47:42 - DBCALL DEVEL: SQL Exec: "INSERT IGNORE INTO user_log        (username, user_id, result, ip, time)        VALUES        (?, ?, 2, ?, NOW())"

**Comment by david-hill** [comment]
And when I get the 500 after the update and no pollers are running, the only line I see in cacti.log is:

20170628 08:57:02 - DBCALL DEVEL: SQL Cell: "SELECT cacti FROM version LIMIT 1"

and then in apache access_log:

192.168.1.22 - - [28/Jun/2017:08:57:02 -0400] "GET /cacti/index.php HTTP/1.1" 500 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"

and in error_log:
[Wed Jun 28 08:57:03.030043 2017] [php7:error] [pid 30275] [client 192.168.1.22:50182] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 262144 bytes) in /usr/share/cacti.git/lib/database.php on line 298
[Wed Jun 28 08:57:03.030408 2017] [php7:error] [pid 30275] [client 192.168.1.22:50182] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 262144 bytes) in /usr/share/cacti.git/lib/functions.php on line 4403

**Comment by david-hill** [comment]
I don't know if this can help but when I upgrade, it says I have to update the database, click next and then it says nothing will be changed in the schema, click ok and then, bang 500 .  So as soon as the version is updated in the version table, it blows everything up in the air.

**Comment by smiles1969** [comment]
This is the same scenario I have been reporting, when you have the cacti log level set to Devel, there is a recursion loop with cacti log function and the date format function.

**Comment by david-hill** [comment]
So it should be fixed ?

David Hill

On Jun 29, 2017, at 12:54, smiles1969 <notifications@github.com<mailto:notifications@github.com>> wrote:


This is the same scenario I have been reporting, when you have the cacti log level set to Devel, there is a recursion loop with cacti log function and the date format function.

**Comment by cigamit** [comment]
Will be fixed later tonight.

**Comment by cigamit** [comment]
Resolved now.

**Comment by david-hill** [comment]
I confirm it is !!!

David Hill

On Jun 29, 2017, at 18:38, Jimmy Conner <notifications@github.com<mailto:notifications@github.com>> wrote:


Resolved now.
