### ISSUE TITLE
Unable to change Cacti Themes stuck at "classic", modern theme saved in settings

### ISSUE THREAD

**Issue by ikorzha** [Cacti/cacti#830]
I have a weird problem that I have encountered twice already on 2 different installs.
First time I upgraded 0.8.8h install to Cacti 1.1.7 and theme switch from classic never worked when logged out, a modern theme presented at login (if it was saved in config) and once logged in everything back to classic, I concluded that I better start fresh...

Then I did a fresh install starting 1.1.9  after fresh install theme switching worked but now a few weeks after initial install I'm stuck at classic theme. When theme is changed in settings and saved, nothing happens, however when I logout, the login screen presents a modern theme, once logged in "everything is in classic".  In settings "modern theme" is set and saved.
There is nothing in a log pertaining to issue when theme is switched..

See pics:
![modern-logo](https://user-images.githubusercontent.com/11211789/27617228-12b2c8aa-5b83-11e7-86bf-285d18e5aa13.jpeg)
![modern](https://user-images.githubusercontent.com/11211789/27617229-14986e2c-5b83-11e7-9fc1-895850c793ee.jpeg)

Unfortunately, I do not know "what chain of events"  broke theme switching I'm sure I won't be the only one with such problem.  
I'm looking for suggestions from developers on how to troubleshoot this issue to identify root cause.

**Comment by cigamit** [comment]
You likely don't have 'Edit Profile' permissions.  The System administrator can define a default theme, but the end user can change it under their profile.

**Comment by ikorzha** [comment]
You are right case closed. Under user settings, classic theme was devices. Not a bug, just end user error :)
