### ISSUE TITLE
Upgrade from 1.1.7 to 1.1.10 cannot add device from automation without SNMP Info

### ISSUE THREAD

**Issue by BigAl101** [Cacti/cacti#831]
Sorry if this is the incorrect place for this.

I recently upgrade my 1.1.7 cacti install on Centos 7 to 1.1.10 (originally installed with the EPEL rpms and upgraded through yum)

Since then when i try and add a discovered device which is not SNMP enabled but is responding to PING i get "Error: Save Failed: Field Input Error (Check Red Fields)" but there are no red fields.

I've enabled the developer mode and i can also see in the log "CMDPHP Form Validation Failed: Variable 'description' does not allow nulls and variable is null" when I try and add the device. 

This was working previously as i had a few remote servers which i was just graphing the ping on and they are not SNMP enabled, but I've tried adding two more today and it's failing. Discovered devices with SNMP enabled i'm able to add without error. 

If i manually create and add the non SNMP enabled device it still works, it's only with automation it fails.

**Comment by cigamit** [comment]
So, you are adding from the Discovered Devices page?

**Comment by BigAl101** [comment]
Hi

Yeah from Automation -> Discovered Devices

Select the device, -> Add Device -> Go

Select the Template and Availability Method and click continue.

Then it returns to the Discovered Devices page and has the error message at the top of the page in red.

**Comment by cigamit** [comment]
Resolved, thanks for reporting.
