### ISSUE TITLE
Wildcard search of graphs is not working

### ISSUE THREAD

**Issue by andermat8** [Cacti/cacti#832]
Upgraded from 0.8.8a to 1.1.9 (Windows 2012) and wildcard searching is not working under graphs. Example string nus%lcr0%-p%/%-%UVN works fine in older version but not in current one. Actually discovered the issue in version 1.1.1 but upgraded hoping this would resolve the issue.  Doesn't appear to be resolved in 1.1.10.

**Comment by cigamit** [comment]
Try using a regular expression.  We changed the method from simple SQL to regular expressions for several pages so that users can return a more diverse result set.

**Comment by andermat8** [comment]
Can you verify regex works with graph searches?  I can't get it to work and it strips out the ^ and $ or do you have an example as I may be applying it incorrectly?

**Comment by andermat8** [comment]
Hi Jimmy,

Not sure if you received my response to the close case or not but can you
verify regex works with graph searches? I can't get it to work and it
strips out the ^ and $ or do you have an example as I may be applying it
incorrectly?

**Comment by cigamit** [comment]
Which page specifically?  The validation on that page may be incorrect causing the search string to be sanitized.  We have a custom sanitization function that handles sanitizing regex.  That if we are using the wrong function, that would be a bug.

**Comment by andermat8** [comment]
Under the graphs tab the Graph Filter page if you enter a regex search I
can't get it to work.  Actually, I can't get any type of search to work.

**Comment by cigamit** [comment]
In Cacti 1.1.10, regular expressions work from the Graphs tab including all views (Tree, List, and Preview), and additionally work from Graph & Data Source management.  Additionally, the characters ^ and $ are not stripped.  In the past, if you used % characters, which were SQL wildcards, you should use the period character moving forward.  For example, in the case above:

`nus%lcr0%-p%/%-%UVN`

You would replace with:

`nus.lcr0.-p./.-.UVN`

That should work fine.
