### ISSUE TITLE
graph GUI - detail [1.1.10]

### ISSUE THREAD

**Issue by dzemba1986** [Cacti/cacti#834]
![cacti](https://user-images.githubusercontent.com/8969907/27786153-56fb3662-5fe0-11e7-9176-4c9c137e19e8.png)

**Comment by cigamit** [comment]
Can you please describe what you are asking for please?

**Comment by dzemba1986** [comment]
I mean these spacing between graphics. In earlier versions (1.1.6?) These spacing were visible and it looked nice. Now the graphs are displayed without spacing.

**Comment by cigamit** [comment]
Okay, resolved.
