### ISSUE TITLE
[Cacti 1.1.11] Plugin compatibility version issues

### ISSUE THREAD

**Issue by scline** [Cacti/cacti#836]
Looks like with the recent update, no mater what value I place under `compat` within the INFO plugin files cacti still refuses to install then. Continue to display the error `Not Compatible, Requires: Cacti >= x.x.xx`

Most recent test is using THOLD (from master) sticking everything from 1.0.0 -> 1.1.11 in that setting.

![capture](https://user-images.githubusercontent.com/4343127/27842581-04a5372e-60c0-11e7-9fe2-88372e9d0902.PNG)

**Comment by cigamit** [comment]
Yes, this was fixed via f163a142183636874d71454ea9e71280e9951d32 and released in 1.12
