### ISSUE TITLE
Missing backticks on column names that are reserved.

### ISSUE THREAD

**Issue by ShaunR** [Cacti/cacti#843]
Ran into an issue today while attempting to upgrade from ```0.8.8g``` to the latest version.  The issue I kept having was that the database upgrade was failing.  After taking a closer look I found that the upgrade script was not properly escaping the word ```rows``` in it's queries.  I have a feeling the word ```rows``` is reserved only on specific brands and/or versions (ex: MySQL vs MariaDB). My system is ```CentOS 7``` with ```MariaDB 10.2``` coming directly from MariaDB yum repo, and ```PHP 5.4.16```.

**Comment by ShaunR** [comment]
I'm having a hard time figuring out how to add my pull request to this issue.  I seam to remember it being easy.... Here's the direct link https://github.com/Cacti/cacti/pull/844

**Comment by ikorzha** [comment]
I believe cigamit actually resolved this issue in non released github cacti code
see: https://github.com/Cacti/cacti/issues/839
So clone or download Cacti from Github and try again

**Comment by cigamit** [comment]
This is a separate issue.  Thanks for the pull request.
