### ISSUE TITLE
[Reporting] Not allow new itens with aggregate graphs

### ISSUE THREAD

**Issue by gamineiro** [Cacti/cacti#850]
Ours aggregate graphs combine many graphs but not displayed when trying add new items.

In previous versions, 1.1.7 for example, the feature used to work.

![reporting](https://user-images.githubusercontent.com/13181685/28017875-68a5d0f4-6551-11e7-8a0f-6482cc665da1.PNG)

**Comment by cigamit** [comment]
There is a new feature request to build 'combined' graphs that will be free form.  More than likely by you editing the graph items, you broke the aggregate.  I suggest you recreate it.

**Comment by gamineiro** [comment]
@cigamit 
I created the new graph follow your instructions but had same problem.

**Comment by cigamit** [comment]
We are not permitting 'new' aggregate items with the current Aggregate plugin.  Please see the Feature request for combined graphs.  These are like the old 0.7.x Aggregate plugin.

**Comment by cigamit** [comment]
I get the bug now.  Damn.

**Comment by cigamit** [comment]
Resolved now.  Thanks for your patience.
