### ISSUE TITLE
[enchancement] support multiple plugin directories

### ISSUE THREAD

**Issue by sourcejedi** [Cacti/cacti#852]
Debian's packaging adds README.Plugins, pointing to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=681558

It would be nice, if README.Plugins could be removed.  But I think the facts that caused it to be written have not changed.

https://github.com/Cacti/cacti/blob/b6c412e41e9d1c863c4ad26a9f2ec9afa4fcdc60/lib/plugins.php#L68

The suggestion is that people should be able to install plugins which are not packaged by Debian, but under /usr/local instead of under the cacti directory in /usr.

AIUI, care would need to be taken, to ensure that if a plugin has been installed to `/usr/local`, it prevents _any_ hooks being run from a plugin of the same name in `/usr/`.

---

The original reporter described this as required by the FHS.

> Locally installed software must be placed within /usr/local rather than /usr unless it is being installed to replace or upgrade software in /usr... Software placed in / or /usr may be overwritten by system upgrades (though we recommend that distributions do not overwrite data in /etc under these circumstances). For this reason, local software must not be placed outside of /usr/local without good reason.

(although individual distributions may have policies which vary from the FHS.  "Since system upgrades from Red Hat are done safely with the RPM system and Gnome-RPM, you don't need to protect files by putting them in /usr/local." - public docs for various versions of RHEL including at least 5 and 6).

**Comment by cigamit** [comment]
Though I think that you could very easily have multiple plugin directories, I don't think it's possible to get beyond the name space limitations of the various hook functions which are tied to the plugins directory name.

Right now, I just don't want to move forward on this change.  However, if you have the energy, or want to engage another developer to deliver such functionality in the form of a pull request, we would welcome it.
