### ISSUE TITLE
Cacti 1.1.12 Automation Graph rule: clear filter does NOT work

### ISSUE THREAD

**Issue by jpobeda** [Cacti/cacti#853]
Hi, 

See attached GIF. The other filters on the same form work fine.

![2017-07-11_15-13-04](https://user-images.githubusercontent.com/13456559/28049683-f9e30194-664c-11e7-9eab-38a2e5c0f709.gif)

Thanks

**Comment by cigamit** [comment]
Resolved.  Thanks.
