### ISSUE TITLE
Multi Core CPU monitoring WMI and Cacti 1.1.12

### ISSUE THREAD

**Issue by MaxCordan** [Cacti/cacti#856]
**Hello colleagues!

I had a problem with the template for the CPU monitor on the server for each core separately. The template should display every 24 kernels as a separate line on my server. 

Now I see the following:**

[https://forums.cacti.net/download/file.php?id=33075](url)

**The data source in the graph is as follows:
PercentProcessorTime0 -> Total
PercentProcessorTime1 -> CPU1
PercentProcessorTime2 -> CPU2
PercentProcessorTime3 -> CPU3
...
...
...
PercentProcessorTime24 -> CPU24

After I turn on debug mode for this device:**

[https://forums.cacti.net/download/file.php?id=33076](url)

(Yes, I create 2 graphs for monitoring single CPU, but I see the same outputs on the graph)

After I set parameter in "Generic Log Level" as "DEBUG" I see the following:
[https://forums.cacti.net/download/file.php?id=33077](url)

(I do not have charts with more than 10 cores (except for this), so I can conclude that this part of the debug applies to this graph)

I have installed Cacti 1.1.12.

In Cacti 1.1.5, a similar problem was not observed. All 24 cores were recovered. Judging by the output debug, I can conclude that Cacti "forgot" to read long output lines. I checked that the number of characters with the output of PercentProcessorTime14: * inclusive, is 505 characters.

In Technical Support I have following:
[https://forums.cacti.net/download/file.php?id=33078](url)
[https://forums.cacti.net/download/file.php?id=33079](url)

**## Please help with this. I want look all cores on my graph :)**

**Comment by cigamit** [comment]
Having output that long is a big deal for larger cacti's.  You should instead use shorter data source names.  Cacti can not scale well when there is a single output column that is so long.  It negatively impacts memory table performance (wasted space).  I suggest you widen the output fields.  But you will have to do this for yourself.  We will not change the core.

alter table poller_output modify column output varchar(1024) not null default '';
alter table poller_output_boost modify column output varchar(1024) not null default '';
