### ISSUE TITLE
Pagination wrong on Automation SNMP Options

### ISSUE THREAD

**Issue by pautiina** [Cacti/cacti#858]
Hello.
On URL `/cacti/automation_snmp.php` I have only one configurstion, but pagination dispaly many page.
![59](https://user-images.githubusercontent.com/11805503/28187953-1adbddf2-6829-11e7-80af-18a8a9478416.png)

**Comment by cigamit** [comment]
Resolved in the 1.2 development branch.

**Comment by pautiina** [comment]
New version cacti? :) it's good
