### ISSUE TITLE
The search filter does not support Cyrillic on:

### ISSUE THREAD

**Issue by pautiina** [Cacti/cacti#861]
- /cacti/host.php

- /cacti/sites.php

- /cacti/tree.php

- /cacti/aggregate_graphs.php

- /cacti/pollers.php
And in other places.
![60](https://user-images.githubusercontent.com/11805503/28257548-655e942a-6ad4-11e7-925e-1d68f4af25e5.png)

In the plugins search in Cyrillic works and works on:

- /cacti/graphs.php

- /cacti/data_sources.php

**Comment by cigamit** [comment]
Should be resolved now.  Issue was larger than expected, but there are other things being resolved at the same time.  Please report findings.

**Comment by pautiina** [comment]
Hello.
I see a lot of work is done :)
Almost everything works.
The filter does not work only on `/cacti/automation_snmp.php` page, it does not work at all. After clicking on button search, the line is reset and becomes empty.

**Comment by cigamit** [comment]
Okay, I'll check that out, I'm going to revert a small piece in every file.  Let me know if the result is any different.

**Comment by pautiina** [comment]
Hello.
I have full retest search filter and seaech on Cyrillic. I dont find any problems and now all works fine.
You did a great job of code and now everything is fine. Thank you.
