### ISSUE TITLE
Automation - Graph Rules only In/Out Bits working or chosen

### ISSUE THREAD

**Issue by hiddenicon** [Cacti/cacti#862]
Fresh install of 1.1.13. 
Network discovery created in Automation.
Device Rules created in Automation.
Graph rule of In/Out Bits created in Automation.

Cannot create any other type of graph rule in automation. When choosing any other data query other than SNMP - Interface Statistics, the drop-down reverts back to SNMP - Interface Statistics after clicking on it. Same for the Graph Type, only the In/Out Bits can be chosen. Anything else chosen and it reverts back to In/Out Bits onclick.

**Comment by hiddenicon** [comment]
Seems to be a front-end UI issue. I've tried several different browsers and different versions. All appear to do the same thing though.

**Comment by cigamit** [comment]
Resolved, thanks.
