### ISSUE TITLE
Suspect typo error in cacti/auth_login.php for LDAP authentication

### ISSUE THREAD

**Issue by chtay** [Cacti/cacti#863]
Initially reported in:
https://forums.cacti.net/viewtopic.php?f=21&t=57713

In cacti/auth_login.php, under line 134 to 137 (in Cacti 1.1.13), the "realm" should be equal to 3 instead.
					$user = db_fetch_row_prepared('SELECT *
						FROM user_auth
						WHERE username = ? AND realm = 1',
						array($username));

By changing it to "realm = 3'", the LDAP authentication will work.

**Comment by cigamit** [comment]
Resolved, thanks.
