### ISSUE TITLE
Long OID support

### ISSUE THREAD

**Issue by ncansado** [Cacti/cacti#864]
Hi all,

I'm facing a issue snmp data query to F5 devices, which sometimes have very long oids.
example, data query on device returns 374 rows and verbose query a got 415. (same problem in cacti 0.8.8g and 1.1.7)

Ive tried to find what was the problem and find out that a least 3 database tables as a field with same name snmp_index is limited to char(255), and on my case some of oid reported on verbose query have more than 255, and those that have more than 255 are exactly 41 missing oids.
Ive change tables with the following:
ALTER TABLE graph_local MODIFY snmp_index varchar(320);
ALTER TABLE host_snmp_cache MODIFY snmp_index varchar(320);
ALTER TABLE data_local MODIFY snmp_index varchar(320);
This solves the missing oids problem, I can see all and create graphs but I loose capability of automatic naming to graphs( ex: host1 member - guest1) after change (I got host1 |query_hostame| -|query_guest|)

After return table field definitions back to default, automatic graph name starts to work again, but I cant monitor missing oids....
Of course there is something else to do, but my developer skills are very limited.

Can someone give a help?

Many thanks,
NC

**Comment by cigamit** [comment]
Someone I don't see you changing the column widths a problem.  You should re-index you device once you have re-indexed everything, and then 'Re-apply Suggested Names'.  Let me know how that works.

This size snmp_index is going to be a problem on utf8mb4, without some database changes.  Those tables may have to stay simple utf8 to support such wide indexes.

**Comment by cigamit** [comment]
Any updates?

**Comment by cigamit** [comment]
Closing due to lack of feedback.
