### ISSUE TITLE
UI visibiliti improvements: Paw Theme

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#87]
Thank You for that beautiful skin.

I would like to propose only few updates/improvements:
1. host.php <--- headers in `<div class="textSubHeaderDark">` are not centered.
2. in left menu `<ul id="menu_management_div" style="display:block;" role="menu"> `
I would like to add some  dots or some dash as like in picture.

![zrzut ekranu z 2016-12-21 13-28-48](https://cloud.githubusercontent.com/assets/17087236/21389426/f4ea23e4-c781-11e6-8fab-4ab68b0f103c.png)

It will look much more clear.

or if You don't like mine idea please add some other background color to all bold positions in menu.
<a class="menu_parent active" href="#">Management</a> 

3. Please add a 1px solid border in `<table id="host2_child" class="cactiTable" style="padding:3px;">` in Management-->Devices (host.php)

**Comment by browniebraun** [comment]
I didn't get what should be wrong within host.php - just searching the red line.
Regarding the second point I agree, that increasing left padding in CSS will do that trick easily. Without points or underlines. I would like to keep this theme flat and easy.

Regards
-Andi

**Comment by interduo** [comment]
I edited my first post - the code was not visible. Sorry for that.
