### ISSUE TITLE
Can't upgrade from 1.1.9 -> 1.1.14

### ISSUE THREAD

**Issue by gmuellerfr** [Cacti/cacti#870]
Fatal error: Cannot redeclare upgrade_to_1_1_11() (previously declared in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.14/install/upgrades/1_1_11.php:26) in /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.14/install/upgrades/1_1_14.php on line 26

**Comment by thurban** [comment]
The "function upgrade_to_1_1_11() {" needs to be renamed to "+function upgrade_to_1_1_14() {"

**Comment by gmuellerfr** [comment]
Today I've upgraded from 1.1.9 to 1.1.15.
The success screen told me, that I have upgraded to version 1.1.14.
Sorry, no screen shot available.

**Comment by ronytomen** [comment]
Cool!
