### ISSUE TITLE
The value of 95th Percentile can't cannot be calculated at 1024

### ISSUE THREAD

**Issue by babyfenei** [Cacti/cacti#871]
These two graphics are based on the same port, using different graphics templates, the left of the Base Value is 1024, the right Base Value is 1000, but the two graphics 95th, Percentile values are the same. Is it possible to add a function? When the Base Value of the graphics template is set to 1024, the 95 value is also calculated in accordance with 1024.
![image](https://user-images.githubusercontent.com/22876759/28558702-a2bf64a8-7145-11e7-88b3-62859e94ebe0.png)

**Comment by pautiina** [comment]
Hello.
I'm not sure, but it looks like my graphics relate to this problem.
![cacti_3264](https://user-images.githubusercontent.com/11805503/32418069-8a0025ac-c26b-11e7-9fb9-ac380e20c8fa.png)
![cacti_3263](https://user-images.githubusercontent.com/11805503/32418070-8a1d7f58-c26b-11e7-9372-968167b80506.png)

**Comment by cigamit** [comment]
We should be using vdef's for these things in todays world.  But we will keep this open for a time still.  I had a design, just fell to the bottom of the list of things to do.

**Comment by pautiina** [comment]
Someone might share a working template for the 95th percentile?

**Comment by cigamit** [comment]
Merry Christmas!  Please update lib/rrd.php and lib/graph_variables.php from develop.  If you are feeling in the Christmas Spirit, please donate to the team.

**Comment by pautiina** [comment]
Merry Christmas and you @cigamit ! 
Thank you for your work, I will definitely donate.
But it's still not working :)

**Comment by pautiina** [comment]
![cacti_3491](https://user-images.githubusercontent.com/11805503/34350502-c180eb66-ea1f-11e7-845e-c0c0890f9ce1.png)

```
RRDtool Command:
/usr/local/bin/rrdtool graph - \
--imgformat=PNG \
--start='1514269620' \
--end='1514273220' \
--pango-markup  \
--title='NRP-SWITCH - Traffic - PITLINE-10Gbit/s' \
--vertical-label='bits per second' \
--slope-mode \
--base=1000 \
--height=150 \
--width=550 \
--rigid \
--alt-autoscale-max \
--lower-limit='0' \
COMMENT:"From 2017/12/26 08\:27\:00 To 2017/12/26 09\:27\:00\c" \
COMMENT:"  \n" \
--color BACK#F3F3F3 \
--color CANVAS#FDFDFD \
--color SHADEA#CBCBCB \
--color SHADEB#999999 \
--color FONT#000000 \
--color AXIS#2C4D43 \
--color ARROW#2C4D43 \
--color FRAME#2C4D43 \
--border 1 --font TITLE:11:'Arial' \
--font AXIS:8:'Arial' \
--font LEGEND:8:'Courier' \
--font UNIT:8:'Arial' \
--font WATERMARK:6:'Arial' \
--slope-mode \
--watermark 'Copyright (C) 2004-2017 The ' \
DEF:a='/var/www/data/cacti/rra/527/3489.rrd':'traffic_in':MAX \
DEF:b='/var/www/data/cacti/rra/527/3489.rrd':'traffic_in':AVERAGE \
DEF:c='/var/www/data/cacti/rra/527/3489.rrd':'traffic_out':MAX \
DEF:d='/var/www/data/cacti/rra/527/3489.rrd':'traffic_out':AVERAGE \
CDEF:cdefa='a,8,*' \
CDEF:cdefb='b,8,*' \
CDEF:cdefg='d,8,*' \
LINE1:cdefa#00CF00FF:''  \
AREA:cdefb#00CF007F:'Inbound '  \
GPRINT:cdefb:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefb:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdefb:MAX:'Maximum\:%8.2lf %s\n'  \
LINE1:c#002A97FF:''  \
AREA:cdefg#002A977F:'Outbound'  \
GPRINT:cdefg:LAST:'Current\:%8.2lf %s'  \
GPRINT:cdefg:AVERAGE:'Average\:%8.2lf %s'  \
GPRINT:cdefg:MAX:'Maximum\:%8.2lf %s\n'  \
COMMENT:' \n'  \
HRULE:0#FF0000FF:'95th Percentile' \
COMMENT:'(0 mbit in+out)' 
RRDtool Says:
OK
```

**Comment by cigamit** [comment]
What is your LANG environment variable set to?

**Comment by pautiina** [comment]
LANG="ru_RU.UTF-8"

**Comment by cigamit** [comment]
Should be working after the last commit.  Please test and verify.  Requires a newer RRDtool.  RRDtool 1.4.8 did not work in my testing.

**Comment by pautiina** [comment]
![1](https://user-images.githubusercontent.com/11805503/34358419-549d45ec-ea58-11e7-9a8a-aca1fd920400.png)

After last commit works normally :)
Many thanks. Good job.

**Comment by cigamit** [comment]
Thanks for testing.  Have a great new year.  Just a few days from 1.1.29, which will include this patch.
