### ISSUE TITLE
Can't add device items to graphs generated with no device and no template in1.1.15

### ISSUE THREAD

**Issue by gmuellerfr** [Cacti/cacti#872]
Today I've upgraded to version 1.1.15.
Now I can select the device I want to add to the graph again, but the **Data Source** drop down area doesn't respect the **Data Template** chosen.

![active threads](https://user-images.githubusercontent.com/25848039/28588512-1aa2c21e-717b-11e7-85bd-68fda76ed0c6.png)
The number of shown items is limited to 20. There is no scrollbar. There is a text cursor shown on the button. But you can't type on this button to search for an item as it is possible in the colour button.
_(The number of shown colours is also limited and there is no scrollbar, too. But you can search!)_
![smtp rejects](https://user-images.githubusercontent.com/25848039/28588542-3237f91c-717b-11e7-85a6-51d2c1da8fa3.png)
There is no way to select a data source of **CGP - SMTP Rejects** template, which contains 7 data sources.
![smtp rejects definition](https://user-images.githubusercontent.com/25848039/28588998-95d60cec-717c-11e7-8c28-819457508cdf.png)
How can I select the needed data source? How will this be implemented (scrollbar, search)?
Thank you for listening.
Guenter

**Comment by cigamit** [comment]
Sorry about that.  I have to review the behavior of the code again.  This is an area that did not get a lot of focus before the release of 1.x.  However, we need lampoon this issue once and for all.

**Comment by gmuellerfr** [comment]
Never mind.
I've used this feature before 1.x extensively, and I will do so in future. That's one of the reasons I use cacti. It's able to compare apples with oranges. So I find all bugs you've coded. ;-)
I hope you will debug the bugs as soon as I find them. 👍

**Comment by gmuellerfr** [comment]
Reading the comments to #880 I've decided to test the classic theme whether it's possible to create the desired graphs in this theme.
Today I tried to change the theme of the admin account to classic and locked myself out #882.
After creating an admin account with no permissions to use link tabs, I've found, that I can create the graphs I wish. The limitations apply only to the modern themes.

**Comment by cigamit** [comment]
Yea, the other issue is a missing FreeType library.  I'll get to this issue hopefully before the next release.

**Comment by cigamit** [comment]
This issue is resolved now.  Thanks for reporting!
