### ISSUE TITLE
RRDTool error is shown in Graph Management after upgrading from 1.1.9 -> 1.1.15

### ISSUE THREAD

**Issue by gmuellerfr** [Cacti/cacti#873]
I have a graph, which I've created with 1.1.9. This graph shows only areas depending on CDEF.
After upgrading, I get the error message: _don't understand 'a,\*,IF,UNKN,a,\*,if'_
![graph item with error](https://user-images.githubusercontent.com/25848039/28590597-f6408bf6-7182-11e7-9d92-fd98a337eca1.png)
The same CDEF is used in all my graphs and gives no error message.
![graph item without error message](https://user-images.githubusercontent.com/25848039/28590652-35366c18-7183-11e7-82d9-c7c5b4ce2bf9.png)
Any idea what's going wrong now?
Thank you for listening.
Guenter

**Comment by cigamit** [comment]
I can not imagine that this upgrade caused the issue.  I would back off to a backup of the website and database and then setup a test system put the system into debug before you update so you can find the SQL statement that did that.  I don't recall any changes in DB schema that would cause a Data Source to be removed from a Graph.  Looks like human error actually.

There is an Audit plugin that you can install to find out the source of these king of things.  Not to repair, but rather to identify the source.

**Comment by gmuellerfr** [comment]
Sorry for confusing, that's not what I mean.

This particular graph has NO Data Source attached. Neither before upgrading nor after upgrading.
But before upgrading no Error message was displayed when no Data Source is attached.

Thank you for listening.
Guenter

**Comment by cigamit** [comment]
Okay, I don't see this as an issue.  It may have been that RRDtool was simply segfaulting in the past.  It's been known to do that over the years.
