### ISSUE TITLE
Cacti 1.1.12 PDOStatement::execute(): SQLSTATE[HY093] Warning

### ISSUE THREAD

**Issue by jpobeda** [Cacti/cacti#874]
Hi there,

Just playing with user rights it came out with this warning.

![firefox_2017-07-26_11-21-26](https://user-images.githubusercontent.com/13456559/28598011-27fca946-71f5-11e7-8c2c-27b85231123d.png)

User access is defined by group as follow

![chrome_2017-07-26_11-26-03](https://user-images.githubusercontent.com/13456559/28598039-49a360da-71f5-11e7-8e14-510bde4c16bc.png)

User realm is LDAP. Logging in with my ldap account (full access) haven't seen this warning before.

So far I can't tell is causing any issue...it really looks like a warning only.

System details are

Cacti 1.1.12
Centos 6 + MySQL 5.5.52-MariaDB + PHP 5.4.16

Let me know if you need any further details.

**Comment by cigamit** [comment]
There should be more information on this in the Cacti.log.  Please post it.

**Comment by jpobeda** [comment]
Actually there is not

I manually ran a cat at the cacti log file and nothing came up

Do you want to me to turn debug on and see what does come up ?

**Comment by jpobeda** [comment]
Found it on apache error_log

> [Wed Jul 26 11:12:48.510136 2017] [:error] [pid 8942] [client xxx.yyy.129.128:53177] PHP Warning:  PDOStatement::execute(): SQLSTATE[HY093]: Invalid parameter number: no parameters were bound in /usr/share/cacti-1.1.12/lib/database.php on line 244, referer: https://cacti2.xxx.yy.zz/cacti/index.php
> [Wed Jul 26 11:14:26.896377 2017] [:error] [pid 12255] [client xxx.yyy.129.128:53258] PHP Warning:  PDOStatement::execute(): SQLSTATE[HY093]: Invalid parameter number: no parameters were bound in /usr/share/cacti-1.1.12/lib/database.php on line 244, referer: https://cacti2.xxx.yy.zz/cacti/index.php
> [Wed Jul 26 11:18:17.390989 2017] [:error] [pid 10044] [client xxx.yyy.129.128:53428] PHP Warning:  PDOStatement::execute(): SQLSTATE[HY093]: Invalid parameter number: no parameters were bound in /usr/share/cacti-1.1.12/lib/database.php on line 244, referer: https://cacti2.xxx.yy.zz/cacti/index.php
> [Wed Jul 26 11:19:13.682607 2017] [:error] [pid 19277] [client xxx.yyy.129.128:53479] PHP Warning:  PDOStatement::execute(): SQLSTATE[HY093]: Invalid parameter number: no parameters were bound in /usr/share/cacti-1.1.12/lib/database.php on line 244, referer: https://cacti2.xxx.yy.zz/cacti/reports_admin.php
>

**Comment by cigamit** [comment]
Okay, so we know it's in reports_admin.php and index.php.  You should see something more details (a backtrace) in the cacti.log.  Look for it.

**Comment by jpobeda** [comment]
I've got two users with exactly the same permissions (1 local and 1 ldap), and this is only happening to the LDAP one.

**Comment by jpobeda** [comment]
OK, will turn debug on and see what I can find.

**Comment by cigamit** [comment]
Well, that is interesting.

**Comment by jpobeda** [comment]
Nothing..and it's focusing, so I'll try to explain it..

I browse cacti console so it is index.php right? if jump to graphs, I get the warning and apache error_logs shows: [Wed Jul 26 12:05:07.743273 2017] [:error] [pid 5713] [client 143.96.129.128:55483] PHP Warning:  PDOStatement::execute(): SQLSTATE[HY093]: Invalid parameter number: no parameters were bound in /usr/share/cacti-1.1.12/lib/database.php on line 244, referer: https://cacti2.cnw.co.nz/cacti/index.php

Then, if I browse to Reporting that is reports_admin.php right? nothing happens there BUT if go back to graphs, apache error_logs shows:
[Wed Jul 26 12:04:42.173934 2017] [:error] [pid 5776] [client 143.96.129.128:55473] PHP Warning:  PDOStatement::execute(): SQLSTATE[HY093]: Invalid parameter number: no parameters were bound in /usr/share/cacti-1.1.12/lib/database.php on line 244, referer: https://cacti2.cnw.co.nz/cacti/reports_admin.php

Does that make any sense O_o???

**Comment by cigamit** [comment]
disable plugins till the error goes away.  You don't have to uninstall, just disable.  Basically, there is a "db_*_prepared()" that has been converted from "db_*()", that did not pass in any variables.  Keep me posted.

**Comment by jpobeda** [comment]
bugger, before you posted that I gave it full access to that user and the issue went away and then I revoke admin privs.

I'm trying to reproduce it again.

**Comment by jpobeda** [comment]
well I reproduced it and I'm ashamed to say that I disabled four plugins before trying and it fixed it.

I'm sorry I didn't do it one by one =(

Plugins were Webseer, thold, weathermap, intropage, in that order.

Thanks for your help.

**Comment by cigamit** [comment]
It might be weathermap.  He is not using the Cacti database API.  So, you will have a more difficult time finding it with his API.  Either way, let me re-open so we don't loose track.

**Comment by cigamit** [comment]
Again, this is a db_*_prepared() call without a corresponding value array.  For example ,using the Cacti API you have two close functions:

`db_fetch_assoc("SELECT ... WHERE something = " . $something);`

and

`db_fetch_assoc_prepared("SELECT ... WHERE something = ?", array($something));`

However, when you have the following:

`db_fetch_assoc("SELECT ... WHERE something = " . $something);`

You get that warning message.  I'm thinking Weathermap or the intropage plugisn honestly.

**Comment by cigamit** [comment]
Slight typo, I've updated the last SQL statement.  The breaking case is when you use a prepared statement without a corresponding values array.

**Comment by jpobeda** [comment]
Well I did quick find in files and Intropage plugin has got lots of these call while weathermap had none.

I'll open an issue for intropage and point it to this issue.

Thanks for your help!

**Comment by cigamit** [comment]
Here are the others:

db_fetch_cell() -> db_fetch_cell_prepared()
db_fetch_row() -> db_fetch_row_prepared()
db_fetch_assoc() -> db_fetch_assoc_prepared()
db_execute() -> db_execute_prepared()

**Comment by cigamit** [comment]
Any luck?

**Comment by jpobeda** [comment]
Yep, he has replaced db_fetch_assoc and he's now replacing all of them.

https://github.com/earendilfr/plugin_intropage/issues/4

**Comment by cigamit** [comment]
Glad you traced it down.
