### ISSUE TITLE
When modifying Realm permissions realms listed more than once do not stay in sync

### ISSUE THREAD

**Issue by jpobeda** [Cacti/cacti#875]
Hi,

I couldn't give it a proper title because I don't really know but...look at the gif. Feel free to rename the title for me, please.

I'm click out of focus but I'd expected to actually tick the closest one or nothing.

![2017-07-26_11-50-35](https://user-images.githubusercontent.com/13456559/28598647-21cc4384-71f9-11e7-8ef2-a0fd70aad397.gif)

**Comment by cigamit** [comment]
Oh, geeze.  Not a plugin issue, but needs to be addressed. Thanks for reporting.

**Comment by cigamit** [comment]
Resolved.  Nice work identifying and thanks for all the help.
