### ISSUE TITLE
Reporting SQL Error

### ISSUE THREAD

**Issue by OUnagiles** [Cacti/cacti#879]
Hello,

We are experiencing the following SQL error with our installation, Cacti version 1.1.12:

>DBCALL ERROR: SQL Assoc Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND host_id=0 AND local_graph_id=0 GROUP BY name ORDER BY position) UNION ' at line 1
>  
>DBCALL ERROR: SQL Assoc Failed!, Error:1064, SQL:'(SELECT id, CONCAT('Branch: ', title) AS name FROM graph_tree_items WHERE graph_tree_id= AND host_id=0 AND local_graph_id=0 GROUP BY name ORDER BY position) UNION (SELECT graph_tree_items.id, CONCAT('Device: ', description) AS name FROM graph_tree_items INNER JOIN host ON host.id=graph_tree_items.host_id WHERE graph_tree_id= AND host.id IN(40,2,6,8,33,42,3,1) GROUP BY name) ORDER BY name' 

The error appears to be generated by navigating to Reporting > Some Report > Items > Add

Our instance is running on RHEL 7, and uses MariaDB 10.2.7

Thanks!

**Comment by cigamit** [comment]
Resolved, thanks for reporting.
