### ISSUE TITLE
Device drop down (graphs->List/Preview) is limited to 20 devices & lacks a scroll bar

### ISSUE THREAD

**Issue by misterjmw** [Cacti/cacti#880]
I have **far** greater than 20 devices in my infrastructure (as does nearly everyone running Cacti). Graph trees are great but sometimes you need to drill down to the graphs coming from a single device. 

The issue is that if it's past the 20 device limit we can't reliably filter to a single device. The time selection drop down has a scroll bar as does the template drop down. This 20 device limit seems inconsistent with page design and to hamper usefuleness. 

E.g. Here's the current (1.1.15) device drop down (Under Graphs->Preview) in one of my sites. This has been checked under all 1.1.15 themes to make sure it isn't a theme issue. 
![devicescrollbar](https://user-images.githubusercontent.com/1383647/28629240-1fcdc3a6-71e4-11e7-8d22-ff708bff9f95.jpg)

In the same view, here is the Time drop down. It has a scroll bar. Can we get the same element reused for the device drop down? This would fix the 20 cap and the minor inconsistencies of this page.
![toolbar-reuse](https://user-images.githubusercontent.com/1383647/28629246-235f5b92-71e4-11e7-915d-5aa0490a068e.jpg)

Thanks.

**Comment by gmuellerfr** [comment]
You can type letters into the field instead of ANY. It's a search field. Found it out by myself :)
Maybe it would be nice to have a scrollbar, too.
I have a similar problem with a missing scrollbar in issue #872 .

Guenter

**Comment by misterjmw** [comment]
That's something at least, thank you.
I'll keep this in mind and pass that tip along for user education. However it is still inconsistent when looked at from the perspective of the other fields on the page. Worst of all, the templates field which has an actual search box and a scroll bar. This would better than the simple scroll bar if something were reused come to think of it.  

![2017-07-26_121237](https://user-images.githubusercontent.com/1383647/28636564-c38e36f8-71fb-11e7-9ac1-508b3e557a8d.jpg)

**Comment by jpobeda** [comment]
Yep, as workaround it's ok but i rather get a scrollbar as well.

**Comment by jpobeda** [comment]
I vote number 2, the scrollbar when more than 20 will do it in my opinion.

**Comment by misterjmw** [comment]
@cigamit Is there a reason it doesn't have a similar feel to the Template dropdown? This seems like it gives a similar feel to a combination of  #1 and #2. (Allow configured num. of callbacks and a search field). 

In searching before creating this issue. I have only seen a smattering of comments regarding no scrollbar there, however equally, I was unaware I could search in that field. 

If I have to vote on an option; I'll pick #2 but with the new information I think features end up on the floor instead of purely beneficial.

**Comment by cigamit** [comment]
It does not have to be one or the other, it can be both.

**Comment by cigamit** [comment]
But you would pick one or the other as a configuration item.

**Comment by misterjmw** [comment]
Both options available would be beneficial (generally, imo.) to users of different preferences.  

I assume many of us carried over from the 0.8.8/older, which of course had it only as a drop down
such as: https://www.unixmen.com/wp-content/uploads/2015/02/cacti.png
 
With this in mind, the other idea I had was indicating that "devices" is a searchable field. This comes to mind: 
![image](https://user-images.githubusercontent.com/1383647/28746837-337f6d1a-744f-11e7-8902-f8a6a39d2627.png)

But that might also cause the reverse issue of new users not realizing it is a drop down as well.  Your options are fine, I just bring that as a comment.

**Comment by cigamit** [comment]
Okay, this is resolved now.  I have added two options under Settings > Visual.  One is to enable autocomplete, which will always be disabled for the Classic theme, and the other is for the number of callback rows to return on the dropdown.  The themes have been updated to present a scroll bar as well.
