### ISSUE TITLE
Cannot Sort Devices by Hostname & Errors in Log

### ISSUE THREAD

**Issue by stueh** [Cacti/cacti#881]
Hi all,

I just performed an upgrade from 1.1.10 to 1.1.15, and when I try to sort my hosts in the device panel of the console, it will sort for the first page, but if I go to the next page (or try to select a page number) the pages are blank (i.e. not displaying the hosts). To demonstrate:

Default devices page, showing fine (and if I go to other pages they show fine):
<a href="http://i.imgur.com/CvWJy7P.jpg"><img src="http://i.imgur.com/CvWJy7P.jpg"></a>

Devices page sorted by Hostname - this is directly after clicking the Hostname column header to sort by Hostname, seems to work:
<a href="http://i.imgur.com/BNwJ1PE.jpg"><img src="http://i.imgur.com/BNwJ1PE.jpg"></a>

After clicking either Next or a page number, to look at another page of devices, there are none displayed:
<a href="http://i.imgur.com/Agjsqsn.jpg"><img src="http://i.imgur.com/Agjsqsn.jpg"></a>

What is of interest it that, correlating with the times I'm trying to load the next page of devices, I am getting the following errors in the cacti log:
<a href="http://i.imgur.com/vUHEWaf.jpg"><img src="http://i.imgur.com/vUHEWaf.jpg"></a>

Looks like maybe a SQL syntax error with the host.php script? I'm no programmer, so troubleshooting that code is out of my league. Any ideas? Any easy known fix?

Thanks,

**Comment by stueh** [comment]
As a side note, I used the following list of commands to upgrade Cacti:

mkdir ~/www-backup-20170727
cd /var/www/html/
cp -Rfp * ~/www-backup-20170727/
cd ~
wget http://www.cacti.net/downloads/cacti-1.1.15.tar.gz
tar -xzf cacti-1.1.15.tar.gz
cd cacti-1.1.15
vi include/config.php
                                  Updated all settings to match config.php in production dir
cp ../www-backup-20170727/rra/* rra/
cp -u ../www-backup-20170727/scripts/* scripts/
cp -u -R ../www-backup-20170727/resource/* resource/
yes | cp -rf * /var/www/html/

**Comment by cigamit** [comment]
This is already fixed in the develop branch.  Just download html_utility.php from develop.  There were three commits.  This was the last one.

https://github.com/Cacti/cacti/commit/49143d2d994beab05ecc48e501492ee235055bc2

**Comment by stueh** [comment]
Beautiful, worked a treat. Thank you!
