### ISSUE TITLE
URGENT: Can't access admin page after switching from modern to classic theme in 1.1.15

### ISSUE THREAD

**Issue by gmuellerfr** [Cacti/cacti#882]
Hello,
I've just switched from modern to classic theme in the profile of admin.
At the moment I saved the profile, the theme changed and stays empty.
Even after successful login the screen stays empty.
No error message is presented on the screen (not even white letters on white screen).
How can I reconnect to the admin?

Log says:
2017/07/27 08:25:53 - AUTH LOGIN: User 'admin' Authenticated via Authentication Cookie
2017/07/27 08:26:05 - ERROR PHP ERROR: Call to undefined function imagettfbbox() in file: /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.15/lib/functions.php on line: 4268
2017/07/27 08:26:05 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4432 cacti_debug_backtrace)
2017/07/27 08:26:19 - ERROR PHP ERROR: Call to undefined function imagettfbbox() in file: /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.15/lib/functions.php on line: 4268
2017/07/27 08:26:19 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4432 cacti_debug_backtrace)
2017/07/27 08:26:34 - SYSTEM STATS: Time:32.8381 Method:spine Processes:1 Threads:1 Hosts:153 HostsPerProcess:153 DataSources:14052 RRDsProcessed:5911
2017/07/27 08:27:05 - AUTH LOGIN: User 'admin' Authenticated
2017/07/27 08:27:05 - ERROR PHP ERROR: Call to undefined function imagettfbbox() in file: /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.15/lib/functions.php on line: 4268
2017/07/27 08:27:05 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4432 cacti_debug_backtrace)
2017/07/27 08:28:02 - AUTH LOGIN: User 'admin' Authenticated
2017/07/27 08:28:02 - ERROR PHP ERROR: Call to undefined function imagettfbbox() in file: /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.15/lib/functions.php on line: 4268
2017/07/27 08:28:02 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4432 cacti_debug_backtrace)
2017/07/27 08:28:08 - ERROR PHP ERROR: Call to undefined function imagettfbbox() in file: /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.15/lib/functions.php on line: 4268
2017/07/27 08:28:08 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4432 cacti_debug_backtrace)
2017/07/27 08:28:11 - ERROR PHP ERROR: Call to undefined function imagettfbbox() in file: /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.15/lib/functions.php on line: 4268
2017/07/27 08:28:11 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4432 cacti_debug_backtrace)
2017/07/27 08:28:13 - ERROR PHP ERROR: Call to undefined function imagettfbbox() in file: /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.15/lib/functions.php on line: 4268
2017/07/27 08:28:13 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4432 cacti_debug_backtrace)
2017/07/27 08:28:15 - ERROR PHP ERROR: Call to undefined function imagettfbbox() in file: /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.15/lib/functions.php on line: 4268
2017/07/27 08:28:15 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4432 cacti_debug_backtrace)
2017/07/27 08:28:40 - ERROR PHP ERROR: Call to undefined function imagettfbbox() in file: /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.15/lib/functions.php on line: 4268
2017/07/27 08:28:40 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4432 cacti_debug_backtrace)
2017/07/27 08:29:04 - ERROR PHP ERROR: Call to undefined function imagettfbbox() in file: /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.15/lib/functions.php on line: 4268
2017/07/27 08:29:04 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4432 cacti_debug_backtrace)
2017/07/27 08:29:10 - ERROR PHP ERROR: Call to undefined function imagettfbbox() in file: /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.15/lib/functions.php on line: 4268
2017/07/27 08:29:10 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4432 cacti_debug_backtrace)
2017/07/27 08:30:10 - ERROR PHP ERROR: Call to undefined function imagettfbbox() in file: /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.15/lib/functions.php on line: 4268
2017/07/27 08:30:10 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4432 cacti_debug_backtrace)
2017/07/27 08:30:45 - ERROR PHP ERROR: Call to undefined function imagettfbbox() in file: /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.15/lib/functions.php on line: 4268
2017/07/27 08:30:45 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4432 cacti_debug_backtrace)
2017/07/27 08:30:56 - ERROR PHP ERROR: Call to undefined function imagettfbbox() in file: /var/www/cacti.fun.uni-freiburg.de/htdocs/cacti-1.1.15/lib/functions.php on line: 4268
2017/07/27 08:30:56 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4432 cacti_debug_backtrace)
2017/07/27 08:31:37 - SYSTEM STATS: Time:35.8517 Method:spine Processes:1 Threads:1 Hosts:153 HostsPerProcess:153 DataSources:14052 RRDsProcessed:5911

**Comment by gmuellerfr** [comment]
I dragged myself out of the swamp by my own hair:

MariaDB [cacti]> update settings_user set value = 'modern' where name = 'selected_theme' and user_id = 1;
Query OK, 1 row affected (0.00 sec)
Rows matched: 1  Changed: 1  Warnings: 0

**Comment by gmuellerfr** [comment]
I've played a little bit with permissions and found out, what happens.
If I have configured external links and those external links are enabled for the user, classic theme is not usable.
So only users under those conditions will loose connection to the gui!
Thank you for listening.
Guenter

**Comment by cigamit** [comment]
This is a requirement of FreeType.  Looks like some distributions are not requiring it.  Here are two articles.  Please follow, then you should be okay.

https://stackoverflow.com/questions/26732382/imagettftext-do-not-work

https://stackoverflow.com/questions/15000063/php-imagettftext-not-working-and-gd-installed

Once FreeType is properly installed, restart Apache.
