### ISSUE TITLE
Develop branch not update rrd and Poller Cache [1.1.15]

### ISSUE THREAD

**Issue by pautiina** [Cacti/cacti#884]
Hello.
Today I have pull develop branch. After this my rrd file not update and I lost many data.
On cacti log I dont find any error.
I noticed only that `Poller Cache`  not have snmp and have scipts and other cache that not use snmp. The graphs that used the different Data Queries from the snmp were updated and worked.
Realtime also not working
If you need a debug, let me know what you need to get.

**Comment by cigamit** [comment]
Yea, bit me too.  Resolving.
