### ISSUE TITLE
Graph generated with no device and no template in1.1.15 forgets device definitions if edited

### ISSUE THREAD

**Issue by gmuellerfr** [Cacti/cacti#885]
Today I've tried to change the header of a graph not belonging to a certain device and lost all customization. It was a graph with many areas and lines.
To show you what's happening, I've constructed a new simple example with only two devices showing stack area and legend for DEF "a" and DEF "b". Rather simple.
![before](https://user-images.githubusercontent.com/25848039/28710810-c001ce2e-7385-11e7-93a0-ae63342c599d.png)
When I edit the title and press the save button, all data definitions are lost except the last one, which becomes now DEF "a".
![after](https://user-images.githubusercontent.com/25848039/28711026-6ec8e6a4-7386-11e7-9bc8-e34a3a87e452.png)
This behavior is annoying. You must add the def references for all devices and legends again.
Thank you for listening.
Guenter

**Comment by cigamit** [comment]
This issue should be resolved now.  Thanks!
