### ISSUE TITLE
Unable to export templates with 1.1.15

### ISSUE THREAD

**Issue by tertius1** [Cacti/cacti#886]
Console->Import/Export->Export Templates: It's not possible to export any template except Device Templates.

If you choose a different template type in the first dropdown box, the chosen type flashes briefly but is immediately changed back to "Device Template". The second dropdown list now contains items according to the chosen type, but clicking on the export button yields nothing. In the cacti log, this error is logged: "WEBUI ERROR: Invalid Device Template found during Export. Please run database repair script to identify and/or correct."

I ran the database repair script, but no problems were found. I assume the issue is connected to the device type box always changing back to "Device Template", not due to errors in the database. I tried different skins, happens with all skins.

**Comment by cigamit** [comment]
Resolved, thanks!
