### ISSUE TITLE
Upgrade from 1.1.12 to 1.1.16 Issue

### ISSUE THREAD

**Issue by jpobeda** [Cacti/cacti#888]
Hi there,

Today I upgraded the 1.1.12 installation to 1.1.16 and it didn't go well. 

After the upgrade process I rebuilt the poller cache but these were the only lines on clog. 
Since there was a database upgrade related to some data source columns I wonder if it's related.

These are just 2 lines of lots of them. What I can tell you about these DSs is that they are all Externally updated Data Sources (updated by Munin).

> 2017/07/31 09:34:51 - CMDPHP WARNING: Repopulate Poller Cache found Data Input Missing for Data Source 3492. Database may be corrupted
> 2017/07/31 09:34:51 - CMDPHP WARNING: Repopulate Poller Cache found Data Input Missing for Data Source 3494. Database may be corrupted

So far I can't add any more data since I rolled it back but happy to reproduce it with your assistance.

**Comment by cigamit** [comment]
Yea, this looks like the one test case that I don't have working in my environment.  I suspect this is a non-issue, but I will check and if so, mute the error.

**Comment by cigamit** [comment]
False positive as a predicted.  Resolved.
