### ISSUE TITLE
ERROR: Installed RRDtool version does not match configured version. (Cacti1.1.15, RRDTool1.7, PHP71, MariaDB10.2, CentOS7x64Minimal)

### ISSUE THREAD

**Issue by mauagomes** [Cacti/cacti#889]
When I access "System Utilities" and visualize "Technical Support"  information, a message is shown as below in the section "RRDTool Version":
"RRDTool 1.4.x 
ERROR: Installed RRDtool version does not match configured version.
Please visit the Configuration Settings and select the correct RRDtool Utility Version."

By the way, everything is working fine, but I just thought it was a strange thing.
I've already set the "RRDTool 1.7.x" in the Cacti's settings section.

I'm using Linux CentOS 7 x64 Build 1611 Minimal Install, 	Cacti 1.1.15, Spine 1.1.15, PHP 7.1, MariaDB 10.2, RRDTool 1.7, Httpd 2.4.6 and NET-SNMP 5.7.2.

Here's some screenshots.
![rrdtool version 1 7](https://user-images.githubusercontent.com/30599854/28785414-c38e42b6-75ec-11e7-8a2e-081c6cedf398.png)
![summary_technical-support](https://user-images.githubusercontent.com/30599854/28785413-c38de2a8-75ec-11e7-8986-d69a31584696.png)

Thanks for any help.

**Comment by cigamit** [comment]
Please goto Console > Configuration > Settings > Paths and copy and past the RRDtool binary path and execute the path without any options.  Paste the value returned.  My guess it'll be 1.4.x.

**Comment by mauagomes** [comment]
Cigamit, yes, you are right. I don't know why, but I've downloaded and installed the 1.7 version. This is pretty weird. Well, I'll let this version anyway. Many thanks!

**Comment by mauagomes** [comment]
Solved, I discovered I have two versions installed in different folders. One in /usr/bin/rrdtool and another in /opt/rrdtool-1.7.0/bin/rrdtool.
The first one (1.4.x) maybe was installed automatically as a dependency of another app and I didn't notice.
Thanks again for your answer!
