### ISSUE TITLE
PHP NOTICE: Undefined index: task_item_id 

### ISSUE THREAD

**Issue by jsarmento** [Cacti/cacti#890]
We are having some issued since we upgraded our Cacti from version 0.8...
After multiple upgrades, nowadays we have Cacti version 1.1.15 installed but the issue continues.

![image](https://user-images.githubusercontent.com/25363908/28840646-8f4c6eb6-76ef-11e7-864f-7ea70249d8c2.png)

The dropdown boxes stopped having the correct item filled on them.
When we do "Unlock graph" and fill in the correct items, followed by Save, it comes back to the same screen and produced the following log:

```
ERROR: don't understand 'c,a,/'
ERROR: don't understand 'c,a,/'
ERROR: don't understand 'c,a,/'
ERROR: don't understand 'c,a,/'
ERROR: don't understand 'c,a,/'
ERROR: don't understand 'c,a,/'
[Tue Aug 01 17:10:31.470071 2017] [:error] [pid 29829] [client 10.33.19.165:24449] PHP Notice:  Undefined index: task_item_id in /var/www/html/cacti/lib/html_form_template.php on line 175, referer: http://10.35.81.176/cacti/graphs.php?host_id=-1&rows=-1&rfilter=PLS&template_id=-1&
[Tue Aug 01 17:10:31.470403 2017] [:error] [pid 29829] [client 10.33.19.165:24449] PHP Notice:  Undefined index: task_item_id in /var/www/html/cacti/lib/html_form_template.php on line 187, referer: http://10.35.81.176/cacti/graphs.php?host_id=-1&rows=-1&rfilter=PLS&template_id=-1&
[Tue Aug 01 17:10:31.471960 2017] [:error] [pid 29829] [client 10.33.19.165:24449] PHP Notice:  Undefined index: task_item_id in /var/www/html/cacti/lib/html_form_template.php on line 175, referer: http://10.35.81.176/cacti/graphs.php?host_id=-1&rows=-1&rfilter=PLS&template_id=-1&
[Tue Aug 01 17:10:31.472236 2017] [:error] [pid 29829] [client 10.33.19.165:24449] PHP Notice:  Undefined index: task_item_id in /var/www/html/cacti/lib/html_form_template.php on line 187, referer: http://10.35.81.176/cacti/graphs.php?host_id=-1&rows=-1&rfilter=PLS&template_id=-1&
ERROR: don't understand 'c,a,/'
[Tue Aug 01 17:10:40.893344 2017] [:error] [pid 29829] [client 10.33.19.165:24449] PHP Notice:  Undefined index: task_item_id in /var/www/html/cacti/lib/html_form_template.php on line 175, referer: http://10.35.81.176/cacti/graphs.php?action=graph_edit&id=124
[Tue Aug 01 17:10:40.893670 2017] [:error] [pid 29829] [client 10.33.19.165:24449] PHP Notice:  Undefined index: task_item_id in /var/www/html/cacti/lib/html_form_template.php on line 187, referer: http://10.35.81.176/cacti/graphs.php?action=graph_edit&id=124
[Tue Aug 01 17:10:40.895082 2017] [:error] [pid 29829] [client 10.33.19.165:24449] PHP Notice:  Undefined index: task_item_id in /var/www/html/cacti/lib/html_form_template.php on line 175, referer: http://10.35.81.176/cacti/graphs.php?action=graph_edit&id=124
[Tue Aug 01 17:10:40.895357 2017] [:error] [pid 29829] [client 10.33.19.165:24449] PHP Notice:  Undefined index: task_item_id in /var/www/html/cacti/lib/html_form_template.php on line 187, referer: http://10.35.81.176/cacti/graphs.php?action=graph_edit&id=124
ERROR: don't understand 'c,a,/'
[Tue Aug 01 17:10:45.651856 2017] [:error] [pid 29829] [client 10.33.19.165:24449] PHP Notice:  Undefined index: task_item_id in /var/www/html/cacti/lib/html_form_template.php on line 175, referer: http://10.35.81.176/cacti/graphs.php?action=graph_edit&id=124&nostate=true
[Tue Aug 01 17:10:45.652826 2017] [:error] [pid 29829] [client 10.33.19.165:24449] PHP Notice:  Undefined index: task_item_id in /var/www/html/cacti/lib/html_form_template.php on line 175, referer: http://10.35.81.176/cacti/graphs.php?action=graph_edit&id=124&nostate=true
ERROR: don't understand 'c,a,/'
[Tue Aug 01 17:11:07.336795 2017] [:error] [pid 3766] [client 10.33.19.165:24471] PHP Notice:  Undefined index: task_item_id in /var/www/html/cacti/lib/html_form_template.php on line 175, referer: http://10.35.81.176/cacti/graphs.php?action=graph_edit&id=124&nostate=true
[Tue Aug 01 17:11:07.337777 2017] [:error] [pid 3766] [client 10.33.19.165:24471] PHP Notice:  Undefined index: task_item_id in /var/www/html/cacti/lib/html_form_template.php on line 175, referer: http://10.35.81.176/cacti/graphs.php?action=graph_edit&id=124&nostate=true
ERROR: don't understand 'c,a,/'

```

**Comment by cigamit** [comment]
Can you dump and upload your before and after databases somewhere?  You should be able take a backup of the database, restore it to a new server, delete all but one graph/device that exhibits there error and anonymize that device information if concerned.

**Comment by cigamit** [comment]
I would also like to see a screen shot of a good graph using this template please.

**Comment by jsarmento** [comment]
I believe I can do this only for the after database... Unfortunately the database backups previous to the upgrade are not available anymore. Will it help?

This template was fetched from here:
https://www.percona.com/doc/percona-monitoring-plugins/LATEST/cacti/linux-templates.html

The image (from the documentation in Percona's website) is here:
![](https://www.percona.com/doc/percona-monitoring-plugins/LATEST/_images/linux_disk_read_write_time_per_io_request.png)

**Comment by cigamit** [comment]
I did an audit of those Percona templates.  Running those pmp-* commands on a Cacti 1.x system would not be advised without Percona doing some updates first as they are not compatible with Cacti 1.x.

Can you please send a note to the Percona team?  We no longer support the rra table for example.  So, running all those commands will likely, at a minimum, result in errors.

**Comment by jsarmento** [comment]
Thanks for your time/inputs.
Just sent Percona a message and I'll revert to this thread as soon as I have an answer.

**Comment by cigamit** [comment]
Please point them to the install_template.php file in the cli directory.  I think the best router to get this template to Cacti 1.x is to import it into a 0.8.x version. Then export the various Device Templates.

Those templates can be imported into Cacti 1.x using the import_template.php file.  They should avoid all their Database magic and leave it to the Cacti API.

**Comment by cigamit** [comment]
Any feedback from Percona?

**Comment by cigamit** [comment]
Please test by using the attached packages.  You can import them from `<path_cacti>/cli/import_packages.php`.  They were created by importing the XML files into a Cacti 0.8.8 box and upgrading to Cacti 1.x.  In hindsight, I could have simply imported the 0.8.6i+ XML files and copying the scripts to the Cacti scripts directory.

[Percona_GNULinux_Server_HT.xml.gz](https://github.com/Cacti/cacti/files/1213232/Percona_GNULinux_Server_HT.xml.gz)
[Percona_Redis_Server_HT.xml.gz](https://github.com/Cacti/cacti/files/1213234/Percona_Redis_Server_HT.xml.gz)
[Percona_OpenVZ_Server_HT.xml.gz](https://github.com/Cacti/cacti/files/1213235/Percona_OpenVZ_Server_HT.xml.gz)
[Percona_Nginx_Server_HT.xml.gz](https://github.com/Cacti/cacti/files/1213236/Percona_Nginx_Server_HT.xml.gz)
[Percona_MySQL_Server_HT.xml.gz](https://github.com/Cacti/cacti/files/1213237/Percona_MySQL_Server_HT.xml.gz)
[Percona_MongoDB_Server_HT.xml.gz](https://github.com/Cacti/cacti/files/1213239/Percona_MongoDB_Server_HT.xml.gz)
[Percona_Memcached_Server_HT.xml.gz](https://github.com/Cacti/cacti/files/1213240/Percona_Memcached_Server_HT.xml.gz)
[Percona_JMX_Server_HT.xml.gz](https://github.com/Cacti/cacti/files/1213241/Percona_JMX_Server_HT.xml.gz)
[Percona_Galera_Server_HT.xml.gz](https://github.com/Cacti/cacti/files/1213242/Percona_Galera_Server_HT.xml.gz)
[Percona_Amazon_RDS_Server_HT.xml.gz](https://github.com/Cacti/cacti/files/1213244/Percona_Amazon_RDS_Server_HT.xml.gz)
[Percona_Apache_Server_HT.xml.gz](https://github.com/Cacti/cacti/files/1213245/Percona_Apache_Server_HT.xml.gz)

**Comment by cigamit** [comment]
Any feedback?

**Comment by jsarmento** [comment]
Percona hasn't replied to my queries so far.... :(
I'll import the XML files in the next days and let you know how it went...

**Comment by jsarmento** [comment]
Just noticied that Percona Monitoring Plugins has a GitHub repo... :/
Created issue percona/percona-monitoring-plugins#66 on its repo

**Comment by cigamit** [comment]
I've uploaded version 1.1.7 of their Templates to the Cacti documentation site.  They still have not addressed the compatibility issue.
