### ISSUE TITLE
Database.php unable to connect to Mysql when using port different then 3306 in 1.1.16

### ISSUE THREAD

**Issue by LuAmRaTeu** [Cacti/cacti#891]
## Environment:

Centos 7 
Cacti 1.1.16 Stable
Mariadb 10.2.7
Php7

## Error:
Unable to connect to DB when using port different then 3306

## Issue:
in /lib/database.php you du some black magic

```
function db_connect_real($device, $user, $pass, $db_name, $db_type = 'mysql', $port = '3306', $db_ssl = false, $retries = 20) {
......
if ($device == 'localhost' && $port != '3306') {
	$device = '127.0.0.1';
}
...
$database_sessions["$device:$port:$db_name"] = $cnn_id;
```

So instead of saving connection to 
`'$database_sessions["'localhost':$port:$db_name"] = $cnn_id;'`
you save to
`'$database_sessions["'127.0.0.1':$port:$db_name"] = $cnn_id;'`

but later on fetch_call_prepared you access with:

`'$db_conn = $database_sessions["$database_hostname:$database_port:$database_default"];'`

which resolves to hostname to Localhost instead of 127.0.0.1

**Comment by cigamit** [comment]
Resolved, thanks for reporting!
