### ISSUE TITLE
Cacti ifAlias Not displaying last )

### ISSUE THREAD

**Issue by djamp42** [Cacti/cacti#892]
i'm on 1.1.16, i upgraded from 1.1.1. After the upgrade the ifindex ifAlias fails to grab the last **)**
Example:

`Found item [ifAlias='fa0/10:(Office Rack,Phone'] index: 10010 [from value]`

```
show int fa0/10
FastEthernet0/10 is up, line protocol is up (connected)
  Description: fa0/10:(Office Rack,Phone)
```

1.1.1 and lower i never had this issue.

**Comment by cigamit** [comment]
Which graph template is this, and what is the method for grabbing the ifAlias.  You can pull this from the resource XML file.  For that column, you will find an XML tag called "<method>".  Need to know it's value.  If it's set to 'get', change to 'walk'.  Then re-index.

**Comment by cigamit** [comment]
Closing due to lack of feedback.
