### ISSUE TITLE
Alias not displaying for some devices (Nexus)

### ISSUE THREAD

**Issue by andermat8** [Cacti/cacti#894]
I have some devices, appears to be all Nexus at this point, that don't show interface alias.  When I select the "Create Graphs for this Device" link I see columns like Index, Status, Name (IF-MIB), type, speed, etc. but Alias (IF-MIB) doesn't appear.  When creating interface graphs it will not pick up the alias either.  I can manually walk the OID .1.3.6.1.2.1.31.1.1.1.18 and see the aliases.  Also, I have one Nexus 7K with same IOS and it is displaying fine and another that is not so no consistency.  Running version 1.10 but noticed this with version 1.12.

**Comment by andermat8** [comment]
Issue appears to be with SNMP.  When I change it from v2 to v1 it will appear.  Doesn't make sense because when I walk with v2 it will display.  I also require 64-bit graphs : (
Still doing more testing but at least I have narrowed it down.

**Comment by cigamit** [comment]
Please try walking manually using snmpbulkwalk and snmpv2.  What is your maxoid's set to for this device?  When you perform your walk use 'snmpbulkwalk -C maxoids hostname .oid'.

**Comment by andermat8** [comment]
I'm assuming you wanted me to do snmpbulkwalk with -Cr parm (e.g. -Cr40).  
When I do this with the IF-MIB I get a response but it doesn't show the alias:
snmpbulkwalk -v 2c -c comstring -Cpr45 192.10.10.20 .1.3.6.1.2.1.2.2
Being that this is a Nexus I get over 9k variables found.  

If I do the specific OID for alias it will respond but I have to tweak the parms, changing -Cpr45 to -Cpr20:
snmpbulkwalk -v 2c -c comstring -Cpr20 192.10.10.20 .1.3.6.1.2.1.31.1.1.1.18

**Comment by andermat8** [comment]
My current workaround is to discover or reindex the device using snmp v1 and then change it to v2 so I can graph at 64bit.  Not ideal.  Nexus switches can have hundreds of interfaces, wondering if this is causing issues with polling.

**Comment by cigamit** [comment]
What if you simply perform a raw snmpbulk walk of the ifAlias OID and not use any -Cxxx options?  I have a sneaking suspicion that those options may be causing issues.

**Comment by andermat8** [comment]
Yup, that works for that specific OID.

**Comment by andermat8** [comment]
Our default Maximum SNMP OIDs Per SNMP Get Request is set to 40.  Once I change this on the Nexus to 1 it appears to work fine.

**Comment by cigamit** [comment]
Edit lib/snmp.php and delete line 699, and then tell us if the Re-Indexing is working as expected.

**Comment by andermat8** [comment]
This did not have any impact on adding a Nexus to the system or doing a walk.  I seem to have found a max oid number that will work (15) when adding a Nexus using v2.

**Comment by cigamit** [comment]
Okay, I'm going to close then
