### ISSUE TITLE
LDAP issue after upgrade from 1.1.12 to 1.1.16

### ISSUE THREAD

**Issue by allywilson1** [Cacti/cacti#895]
After upgrading from 1.1.12 to 1.1.16 user accounts configured with LDAP for Authentication Realm were unable to login, showing as "UNAVAILABLE" when viewing the Users page (although, not everyone  - just most).

Modifying each user to have the LDAP realm again, fixed the issue. Not a massive problem, we have a relatively low number of users afterall, but might affect others with huge numbers of users.

![screencap](https://user-images.githubusercontent.com/16580296/28961192-5c961e7a-78f9-11e7-83b1-c38128f9675a.png)

**Comment by cigamit** [comment]
Yea, there is something fundamental broken with the numbering between the GUI and the API.

**Comment by cigamit** [comment]
Okay, the fix will be to do the following:

`mysql cacti`
`update user_auth set realm=3 where realm=1;`
