### ISSUE TITLE
rrdtool 1.2

### ISSUE THREAD

**Issue by maforshaw** [Cacti/cacti#896]
NAS devices cannot use rrdtool versions higher than 1.2, see [here](https://github.com/Entware-ng/Entware-ng/issues/729)

Please can we re-instate support for 1.2? It works Ok with Cacti 0.8.8g but Cacti 1.1.16 gives this error:

`ERROR: unknown option --pango-markup`

Thanks.

**Comment by cigamit** [comment]
Easier said than done.  There are too many features dependent on RRDtool 1.3.x+ including one that is absolutely critical for things like Zoom.  Are you not able to get the vendor to compile anything newer?

**Comment by maforshaw** [comment]
That's a shame, I really liked what I saw of the new Cacti. Please see the linked issue above, the vendor said using rrdtool 1.3 and later is not possible because it needs Xlib. I think OpenWrt has to stay on 1.2 for the same reason.

I guess I'll have to downgrade to Cacti 0.8, sadly ;-(

**Comment by cigamit** [comment]
Yea, likely the Pango/Cairo stuff.  Sorry, there is really no option to backport Cacti features to support 1.2.x.  Someone would have to backport some features to RRDtool 1.2.  However, that won't be us.
