### ISSUE TITLE
1.1.6: graph search box reloads, and clears searchbox on any keypress [Debian]

### ISSUE THREAD

**Issue by paulgevers** [Cacti/cacti#897]
This is a copy of bug 871496¹ that was just filed against my Debian cacti package, but I believe the issue is generic (please just close if I judged this wrong and this is e.g. due to the version of jQuery in Debian).

¹ https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=871496

'===================
Dear Maintainer,

On the graphs page when trying to use the right hand side search box. the search box clears and reloads when I enter the first letter. This happens in all browsers I have tried. 

I tracked it down to line 1216 in /usr/share/cacti/site/include/layout.js 
```
$('#filter, #rfilter').bind('keypress', 'ctrl+shift+x', function() {
	$('#filter, #rfilter').val('').css('text-align', 'left').submit(); });
```

It looks to me like the bind keypress activates the ctrl+shift+x clear function on any keypress.  If I comment out the line 1216 it works for me. This of course disable the function, so there probably needs to be a proper fix.

**Comment by cigamit** [comment]
Seems it's completely broken at the moment.  I'm going to completely remove the shortcut.

**Comment by cigamit** [comment]
Resolved.  Firefox actually currently uses Ctrl-Shift-X to change a column from left to right to right to left orientation.
