### ISSUE TITLE
Ping with tcp and udp not work proper (funktion lib/ping.php)

### ISSUE THREAD

**Issue by bfek-18** [Cacti/cacti#898]
Hi, 
The ping (ping_tcp, ping_udp) in ping function lib / ping.php does not work properly.
With this code lines this works again.

cacti-1.1.6 el7 x86_64 (php-5.4.16)

[ping.php.txt](https://github.com/Cacti/cacti/files/1215082/ping.php.txt)

**Comment by cigamit** [comment]
Thanks.  Looks real good.  Resolved.  Next time open a pull request in the develop branch.
