### ISSUE TITLE
Graph Template Export/Import

### ISSUE THREAD

**Issue by smiles1969** [Cacti/cacti#899]
I created an updated DHCPD graph template that is working fully on the latest dev branch. 
I exported it (include dependancies checked) and it appeared to be successful with no issues.
I imported it into another Cacti instance on the same release, and it appears the Data Template and Graph Template name columns are not written correctly in the export file, see attachment.

![image](https://user-images.githubusercontent.com/17500126/29148199-8c74e126-7d31-11e7-9a73-b1a3cc2e2da9.png)

The resulting import will complete, but when you list templates, there is a line item with no name, and therefore no hyperlink to click on to edit it or view it.

**Comment by smiles1969** [comment]
This commit cc45ede bumped the hash version index up to 1.1.17, but my cacti version is still reporting 1.1.16.

Confirmed this by adding another cacti_log to dump the variables in function check_hash_version:


2017/08/10 12:29:35 - IMPORT ERROR: 0101 hash version if for a newer Cacti!
2017/08/10 12:29:35 - IMPORT ERROR: Hash version index = 63 ** Current version index = 62

Also assuming the first error should read "hash version IS for a newer Cacti!" as opposed to IF

**Comment by cigamit** [comment]
Was introduced in 101 in version 1.1.10.  You might want to remove that hash code.  Living on the edge has from time to time some drawbacks.  We will be releasing 1.1.17 this weekend.  Hoped to last weekend, but everyone was too busy.
