### ISSUE TITLE
Data Query Edit

### ISSUE THREAD

**Issue by smiles1969** [Cacti/cacti#90]
When saving new Suggested Values, the existing Data Source mappings get lost.

I wind up having to go back into the Data Query and re-map the Data Sources afterward as a work around.

**Comment by cigamit** [comment]
Any errors in the log?  Also, please provide a step by step as to how to reproduce.  Please be explicit.

**Comment by cigamit** [comment]
That's pretty significant.  Will look into this shortly.

**Comment by smiles1969** [comment]
I'm not able to re-produce it anymore. Not sure which commit may have fixed it.

It was happening after adding a new Suggested Value to Graph Names or Data Source Names.. All Data template mappings and check boxes would be lost. It was the same thing that was happening to aggregate graph template saving.

**Comment by cigamit** [comment]
I'm going to close this one for now.
