### ISSUE TITLE
Cacti 1.1.13 nectar - Unable to specify custom format file

### ISSUE THREAD

**Issue by glueguy** [Cacti/cacti#901]
Updated a legacy installation of 0.8.8h cacti to 1.1.13. Reports are unable to specify a custom Format File when setting up or changing a report.
Only formats available are:

cacti_group.format
cacti_group_dark.format
cacti_monitor.format
default.format
lotus_notes.format

**Comment by smiles1969** [comment]
The drop down will list any valid .format file contained in the /formats directory.

**Comment by cigamit** [comment]
The format file directory was changed to `<path_cacti>/formats`

**Comment by glueguy** [comment]
Sorry, but this is not working in our copy of 1.1.13. If it was fixed in a later release, I apologize.  This is the contents of the /var/www/html/cacti/formats directory:

`@ncs:/var/www/html/cacti/formats$ ls -al
total 36
drwxrwxr-x  2 www-data www-data 4096 Aug  7 11:34 .
drwxrwxr-x 17 www-data www-data 4096 Aug  8 09:38 ..

-rw-rw-r--  1 www-data www-data 1688 Jul 13 18:25 cacti_group_dark.format
-rw-rw-r--  1 www-data www-data 1685 Jul 13 18:25 cacti_group.format
-rw-rw-r--  1 www-data www-data 1645 Jul 13 18:25 cacti_monitor.format
-rw-rw-r--  1 www-data www-data  661 Jul 13 18:25 default.format
-rw-rw-r--  1 www-data www-data   44 Jul 13 18:25 index.php
-rw-rw-r--  1 www-data www-data 1561 Jul 13 18:25 lotus_notes.format
-rw-r--r--  1 www-data www-data 2692 Aug  7 11:33 sbsBasic.format
`
This is what is in the drop-down;
![nectar_format_issue](https://user-images.githubusercontent.com/30908761/29201844-e419cbe0-7e16-11e7-84c5-2b9c333e2ae8.PNG)

**Comment by glueguy** [comment]
Then there is something wrong with the 1.1.13 version? Maybe this was 
fixed in a later release?

This is the contents of the <cacti_path>/formats directory:

    @ncs:/var/www/html/cacti/formats$ ls -al
    total 36
    drwxrwxr-x  2 www-data www-data 4096 Aug  7 11:34 .
    drwxrwxr-x 17 www-data www-data 4096 Aug  8 09:38 ..
    -rw-rw-r--  1 www-data www-data 1688 Jul 13 18:25
    cacti_group_dark.format
    -rw-rw-r--  1 www-data www-data 1685 Jul 13 18:25 cacti_group.format
    -rw-rw-r--  1 www-data www-data 1645 Jul 13 18:25 cacti_monitor.format
    -rw-rw-r--  1 www-data www-data  661 Jul 13 18:25 default.format
    -rw-rw-r--  1 www-data www-data   44 Jul 13 18:25 index.php
    -rw-rw-r--  1 www-data www-data 1561 Jul 13 18:25 lotus_notes.format
    -rw-r--r--  1 www-data www-data 2692 Aug  7 11:33 sbsBasic.format

This is what shows on the drop-down:



The sbsBasic.format file is one that I built back in 0.8.8h and copied 
over. Did the format change or something else?

bp
<part15sbs{at}gmail{dot}com>

**Comment by cigamit** [comment]
You have to add the header to the file.  There are two header lines:

`# Description:`
`# Theme:`

If Cacti does not find at least the '# Description:' row at the beginning of the file, if will not identify the file as a Format file.
