### ISSUE TITLE
[Cacti 1.1.16] Errors

### ISSUE THREAD

**Issue by PonomarenkoVladimir** [Cacti/cacti#902]
**Cacti:**
Cacti-1.1.16

**OS:** 
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04

**PHP:**
PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
 with Zend OPcache v7.0.22-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies

**MySQL:**
mysqld  Ver 5.7.19-0ubuntu0.16.04.1 for Linux on x86_64 ((Ubuntu))

**# Errors:**

# 1.	White screen

Authentication
![default](https://user-images.githubusercontent.com/26214543/29248010-41554d12-8050-11e7-9688-f9b9c78f8285.png)

Press the Login button
Next  **White screen !!!**
![default](https://user-images.githubusercontent.com/26214543/29248013-6519569e-8050-11e7-8604-e4be37a543f9.png)

**MySQL   logs:**
2017-08-13T05:33:53.788114Z 16 [Note] Aborted connection 16 to db: 'cacti' user: 'cactiuser' host: 'localhost' (Got timeout reading communication packets)
2017-08-13T05:34:01.100050Z 15 [Note] Aborted connection 15 to db: 'cacti' user: 'cactiuser' host: 'localhost' (Got timeout reading communication packets)
2017-08-13T05:34:08.809376Z 17 [Note] Aborted connection 17 to db: 'cacti' user: 'cactiuser' host: 'localhost' (Got timeout reading communication packets)
2017-08-13T05:34:24.740737Z 18 [Note] Aborted connection 18 to db: 'cacti' user: 'cactiuser' host: 'localhost' (Got timeout reading communication packets)

Next   **Re-enter**

![default](https://user-images.githubusercontent.com/26214543/29248028-cfb46688-8050-11e7-8016-035d679300a7.png)

OK!

![default](https://user-images.githubusercontent.com/26214543/29248032-e68a5ea8-8050-11e7-96cb-932ea4951b55.png)

# 2. This error is observed in the themes: Dark, Modern, Paper-plane, Paw, Sanrise

**Only 30 devices are displayed, however in the database of devices more than 100**
![default](https://user-images.githubusercontent.com/26214543/29248049-52b32592-8051-11e7-818f-065848214363.png)

And

![default](https://user-images.githubusercontent.com/26214543/29248065-c4cde234-8051-11e7-81cb-cce5262a5c44.png)

And

![default](https://user-images.githubusercontent.com/26214543/29248069-df0a574a-8051-11e7-890f-37e5f8b060f9.png)

# 3.	 External Links
**This error is observed in the themes:  Classic**

![default](https://user-images.githubusercontent.com/26214543/29248074-fb23fc24-8051-11e7-83bd-50bfe5039536.png)

![default](https://user-images.githubusercontent.com/26214543/29248077-0f4ca890-8052-11e7-8e88-14e58737f088.png)

Result

![default](https://user-images.githubusercontent.com/26214543/29248081-1c036e20-8052-11e7-8401-14720cccbbe5.png)

![default](https://user-images.githubusercontent.com/26214543/29248085-2c435142-8052-11e7-8a3f-64e8d76d7ef1.png)

Result

![default](https://user-images.githubusercontent.com/26214543/29248088-3558fe62-8052-11e7-9d56-7d8a27c0c2cc.png)

![default](https://user-images.githubusercontent.com/26214543/29248090-3f07c984-8052-11e7-89e3-e0a6aa7d8c32.png)

Result

![default](https://user-images.githubusercontent.com/26214543/29248096-53511fda-8052-11e7-8146-8d38968f4f11.png)

**Comment by cigamit** [comment]
1) Is likely an upgrade issue.  Others see it once, and never again unless you have a plugin with a javascript error.  Look for javascript error.  If it's repeatable and the javascript error is coming from a Cacti component.  Please open a separate bug on that.
2) By design, you can set how many you see from Console > Settings > Visual
3a) Ordering issue looks like a real bug, but can you please open a separate bug on that
3b) Position for Entire Console area covering positioned below console menu.  Please log a separate bug on that.
