### ISSUE TITLE
[Cacti 1.1.15+] Disable plugins(real-time) for non admin users

### ISSUE THREAD

**Issue by randonhcb** [Cacti/cacti#906]
Now the plugins are embed but is there any 'permission settings' to disable it for any specific user like on the old cacti version plugin.
That would be very very useful.

**Comment by smiles1969** [comment]
Yes

Configuration->Users->Permissions Tab->Plugin Permissions.

**Comment by randonhcb** [comment]
Yes, but no... for the embed plugins (like real-time) there no permission option.. the plugin do not show like older versions (I have 0.8 and 1.1.15 installed)...  I tried a little php, but I'm shitty programer =//

**Comment by cigamit** [comment]
Resolved.  There is a new realm post 1.1.17.
