### ISSUE TITLE
Cacti GUI Issue @ cacti-1.1.12

### ISSUE THREAD

**Issue by jpobeda** [Cacti/cacti#909]
Hi there,

I recorded a GIF to show another GUI bug BUT since I'm running 1.1.12 I'm not sure if it's still present on later releases.

When you see the blank page, that's me hitting F5 to refresh the page. It happened also when updating Cache Directory as well.

In case this is useful to you:

/usr/share/cacti-1.1.12 is the absolute path
/usr/share/cacti1x is a symbolic link

![2017-08-16_10-14-24](https://user-images.githubusercontent.com/13456559/29338996-20c09b88-826c-11e7-8928-01684f87ebae.gif)

**Comment by cigamit** [comment]
Please update to 1.1.17, and then try again.  Also, if you are getting these errors, please check the Cacti log for messages.  There should be some there.  If not, review the apache Error log.

**Comment by jpobeda** [comment]
OK, I'll upgrade this installation this week, please keep this opened a couple of days.

**Comment by jpobeda** [comment]
Tested on 1.1.17 and works ok. Thanks.
