### ISSUE TITLE
Gexport plugin are getting installed.

### ISSUE THREAD

**Issue by komathodivijay** [Cacti/cacti#911]
Hi Team,

I'm unable to install the Gexport plugin in Cacti Version 1.1.2 . Details attached.

Regards
![gexport](https://user-images.githubusercontent.com/26949629/29362522-0052694c-82aa-11e7-9fa6-ffa714a39811.JPG)

Vijay Radhakrishnan

**Comment by jpobeda** [comment]
If you look at the INFO file, you'll see that is compatible with 1.1.10 and above. That's why.
Question is, how do you downgrade gexport version to make it 1.1.2 compatible..Should be a way to do it.

**Comment by cigamit** [comment]
There are new API calls in Gexport that were not available in 1.1.2.  So, upgrade.  It's quite easy once you have done it a time or two.  I think that the EPEL repo is at like 1.1.16 or 1.1.17.  That way it's a 'yum upgrade'.  There is a Debian repo at a pretty high version as well.  It's as easy as 'apt-get update'.
