### ISSUE TITLE
cacti 1, When I follow the github plugin installation instructions to install. In the plugin management has been shown: "no plugin found"

### ISSUE THREAD

**Issue by fanandactuaility** [Cacti/cacti#912]
cacti 1
1.git clone plugin_monitor and plugin_thold.
2.copy the plugin_monitor directory to Cacti's plugins directory
3. rename it to simply 'monitor'. 
4.goto Cacti's Plugin Management page,I can't found  plugin list .

cacti version 1.1.10

**Comment by cigamit** [comment]
You have to rename plugin_thold as well.  Also, check permissions, if the website can not read, they will not appear.  That is all I can think of.  Since this is more of a support request, I'm going to close.  Problems like this are best handled on the Forums.

**Comment by fanandactuaility** [comment]
The problem has been resolved because the database account did not create temporary table permissions.

**Comment by cigamit** [comment]
Good to know.
