### ISSUE TITLE
Dynamic poller scheduling based on device poll time

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#913]
I have a couple devices that take 30 seconds to poll. I'm running a 1 minute poller. Spine doesn't start polling these devices until halfway through the 1 minute polling cycle. As a result, I'm always waiting for these devices to finish polling at the end of the cycle and it affects the overall polling runtime pretty badly. Yes, I know ideally I would try to improve the polling time of these devices, but that isn't completely possible. IS there a way to force these devices to be polled first in the cycle? Or better yet, could spine intelligently schedule the slowest devices first based upon an historical average poll time? This would give them enough time to finish in the cycle. But I do get concerned that putting slowest devices first could mean that other queries stacked up behind those in the same thread would get left off to the end, and possibly skipped if the runtime is exceeded. So perhaps there would be a way to allocate a dedicated thread for specific 'problematic' devices? 
Hoping this makes sense ... !

**Comment by cigamit** [comment]
Are you polling the device with multiple threads?  There was a patch for spine some time ago that resorted the devices by polling time.  It was never merged to my knowledge.  Try device threads first though.

**Comment by cigamit** [comment]
I'm going to close.  Look for a spine commit shortly though as this is a spine issue.

**Comment by eschoeller** [comment]
Yes, the devices in question are using 6 device threads. I don't see any polling activity for these devices until :30 after the polling cycle starts. So getting them started at :05 would be much better! I'll look forward to a spine update:)

**Comment by cigamit** [comment]
The spine update last night should have achieved that.
