### ISSUE TITLE
Latest Cacti Github unable to purge Cacti log

### ISSUE THREAD

**Issue by ikorzha** [Cacti/cacti#914]
I am running the latest Version 1.1.17 I have noticed that I am no longer able to purge the log file.
I get a blank page with header when I attempt it, when I refresh the page and all entries still there.
![unable to clear log](https://user-images.githubusercontent.com/11211789/29432505-f3bceb06-8369-11e7-9f09-f4dbed8ade3c.jpg)

**Comment by cigamit** [comment]
I suspect that this is a permissions problem.

**Comment by ikorzha** [comment]
I wish you would be right. I have 3 servers all with identical issue: Master, and 2 pollers.
Here is a screenshot below from my favorite php shell.
Folder and files have full write permissions from apache:

![unable to clear log-1](https://user-images.githubusercontent.com/11211789/29440409-93031dd4-8392-11e7-8b04-083411227761.jpg)

**Comment by cigamit** [comment]
Open the browsers debug window and perform a purge and capture the details of the post from both the original action and the confirm action and post the contents of the post.

**Comment by ikorzha** [comment]
This is my first time "trying to do a debug" please dont judge me too harshly if I did it incorrectly :)
Below is a screenshot of post and response statements once I click purge:
 
![log-clear-request](https://user-images.githubusercontent.com/11211789/29441556-28ac298c-839a-11e7-8d26-59bafced6f72.jpg)
Please let me know if there is anything else I can do in this case.

**Comment by cigamit** [comment]
Are you removing from the log tab or from utilities??

**Comment by ikorzha** [comment]
I am purging from Utilities. (sorry didn't make it clear originally)

**Comment by cigamit** [comment]
Yea, I confirmed this as well just before you responded.  Thought I had verified both locations, but somehow I must have missed something.

**Comment by cigamit** [comment]
Resolved.
