### ISSUE TITLE
cacti 1.1.17 - ss_host_disk.php non-numeric value

### ISSUE THREAD

**Issue by neverstopdreaming** [Cacti/cacti#915]
Hi,
I see a lot of error lines in the cacti.log:
```
2017/08/18 14:20:09 - ERROR PHP WARNING: A non-numeric value encountered in file: /app/www/cacti/scripts/ss_host_disk.php  on line: 120
2017/08/18 14:20:09 - CMDPHP PHP ERROR WARNING Backtrace: (/script_server.php: 223 ss_host_disk)(/scripts/ss_host_disk.php: 120 CactiErrorHandler)(/lib/functions.php: 4416 cacti_debug_backtrace)
```
I'm not sure when it started since it's a secondary installation where I'm testing the upgrade to 1.x release.
Can you help me finding if it's a bug?
br

**Comment by cigamit** [comment]
Resolved, but you might want to check your indexes as the graph that was throwing this error is likely no longer rendering.
