### ISSUE TITLE
LDAP Auth

### ISSUE THREAD

**Issue by themha** [Cacti/cacti#916]
Hi,

I have used cacti 0.8 for years now i tried to setup a new one. Used same LDAP Settings as in the old one but alwas getting these errors.

cat /var/log/cacti/cacti.log
ERROR PHP WARNING: ldap_search(): Search: Protocol error in file: /usr/share/cacti/lib/ldap.php  on line: 471
2017/08/18 15:49:38 - CMDPHP PHP ERROR WARNING Backtrace: (/index.php: 25 include)(/include/auth.php: 82 include)(/auth_login.php: 109 cacti_ldap_search_dn)(/lib/ldap.php: 151 Search)(/lib/ldap.php: 471 ldap_search)(CactiErrorHandler)(/lib/functions.php: 4393 cacti_debug_backtrace)

I'm using RHEL 7.4
Installed cacti 1.1.16 from the epel repo --> should i use the github version?

Thank you in advance

**Comment by cigamit** [comment]
This is a error handler issue.  These errors should be trapped with an error presented to the user.  In this case it's a generalized protocol error.  Looks like you may be using the wrong ldap version.  I've masked the error in the pending 1.1.18 version.  If you update your lib/ldap.php to that version, your log will be missing those errors, but you will still have to address the issue.  You may want to not use searching, but rather if the bind is sucessfull, just continue onto login.

**Comment by cigamit** [comment]
I'm going to close this one.  If once you disable searching, you still have a problem, just update this ticket.

**Comment by themha** [comment]
This error still persists. It works if I use multiple AD with the same settings. Anyway just wanted to tell you, for me works with the multi version.

Greets and thanks for your work

**Comment by cigamit** [comment]
It looks like the domains implementation was flawed.  I'm re-opening and then patching.  Your setup is set to search.  Please leave the searching blank.

**Comment by cigamit** [comment]
Wait, stet that.  Re-opening the other issue due to this being marked closed and the issue resolved was with logging to the cacti log on this one.
