### ISSUE TITLE
Cacti 1.1.18

### ISSUE THREAD

**Issue by ekgermann** [Cacti/cacti#919]
Can't upgrade because second page confirming PHP params won't scroll to bottom to acknowledge.

Confirmed in Chrome, Mozilla, Opera, Vivaldi and IE.

![image](https://user-images.githubusercontent.com/9213892/29488774-67583ec6-84d7-11e7-8ea8-d5120dae5dcc.png)

EKG

**Comment by cigamit** [comment]
Resolved.
