### ISSUE TITLE
Vertical scrollbars disappeared on Graphs tab (theme - Modern)

### ISSUE THREAD

**Issue by sd3m0n** [Cacti/cacti#920]
After some latest updates (don't remember the exact one) vertical scrollbars on the Graphs tab disappeared. So now its impossible to scroll the graphs in the list at the right side of the screen. On the Logs tab everything is OK. Browser Chrome. Tested on the desktop and mobile version - the same situation.

Theme - Modern. Classic theme is alright.

**Comment by sd3m0n** [comment]
It seems that "Resolve issues with all themes and the graph page relative to size and scroll" commit fixed it.

**Comment by pautiina** [comment]
Hello.
Please reopen this issue.
I have pull from develop branch, remove browser cache, but **_verical_** and **_horisont_** scroll showing only when page is load, after this scroll bar hide. I have test on **Mozzila** and **Opera**

**Comment by sd3m0n** [comment]
Yes, there is no chance to scroll graphs vert or horiz after zooming for example. Both desktop and mobile browsers. I can scroll the page vertically but when scaling the page vertical scrollbar acts incorrectly and horiz scrollbar doesn't appear so I can't scroll the page horizontally at all...

I too think this issue must be reopened.

**Comment by cigamit** [comment]
Yea, there was a fix for External Links that caused all the rukkus.  Will be fixed this morning.  No need to re-open.

**Comment by pautiina** [comment]
Thanks for information :)

**Comment by sd3m0n** [comment]
I've updated to the latest developer repo. The issue still takes place. I don't know if it was already fixed, but I saw the commit on this issue...

**Comment by pautiina** [comment]
Commit 84015d917b5c4b08cecfb73eb1ad0ff0fd2408ba - not help.

**Comment by pautiina** [comment]
Hello. Latest develop branch resolve full scrolling on all page and plugins.
