### ISSUE TITLE
Graphs-> Tree Mode> no longer auto expands  to accomodate full device name.

### ISSUE THREAD

**Issue by ikorzha** [Cacti/cacti#921]
Hi just noticed in the latest 1.1.19 modern skin in graphs Graphs-> Tree Mode> device name cuts off on the right hand side. See picture please. It was auto expanding in previous Cacti 1.x.x releases.
![1 1 9](https://user-images.githubusercontent.com/11211789/29503702-3b75cd46-8608-11e7-9a71-9d373329a32a.jpg)

**Comment by cigamit** [comment]
Good to know.  I'm sure it affects the other themes too.

**Comment by ikorzha** [comment]
I have tested your latest fix pushed today. Problem has been fixed. Thank you.
