### ISSUE TITLE
When using LDAP domains some settings are not passed correctly to the LDAP library

### ISSUE THREAD

**Issue by themha** [Cacti/cacti#922]
This error still persists. It works if I use multiple AD with the same settings. Anyway just wanted to tell you, for me works fine with the multi AD version.

Greets and thanks for your work

**Comment by cigamit** [comment]
You could have asked for 916 to be re-opened.  I've found some discrepancies in the domains implementation that I'm fixing now under issue 916.

**Comment by cigamit** [comment]
Okay, update lib/ldap.php and auth_login.php and test again.  The behavior should be identical now.

**Comment by cigamit** [comment]
Any updates?

**Comment by themha** [comment]
Seems to be resolved thank you
