### ISSUE TITLE
Minor schema change to support XtraDB Cluster

### ISSUE THREAD

**Issue by thatcherhubbard** [Cacti/cacti#927]
Primarily for purposes of availability, I am experimenting with putting a multi-poller Cacti installation in front of a Percona XtraDB cluster rather than a standalone MySQL instance.  

Taking a dump of my production Cacti DB and restoring it to my test cluster results in a few errors, only one of which would require a schema change, and that's what I'm asking about here:

_ERROR 1105 (HY000) at line 4577: Percona-XtraDB-Cluster prohibits use of DML command on a table (cacti_test.snmpagent_cache_notifications) without an explicit primary key with pxc_strict_mode = ENFORCING or MASTER_

The snmp_agent_cache_notifications table has no primary key, which seems to be the issue:

_CREATE TABLE `snmpagent_cache_notifications` (
  `name` varchar(191) NOT NULL,
  `mib` varchar(255) NOT NULL,
  `attribute` varchar(255) NOT NULL,
  `sequence_id` smallint(6) NOT NULL,
  KEY `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Notifcations and related attributes'_

I'm wondering what the best solution to this problem is.  Would it be better to add an 'id' column that's numeric and can be a primary key, or just change the 'name' column to be the primary key?  Would either of those require changes outside of the cacti.sql script that creates the database initially?

**Comment by cigamit** [comment]
Resolved, there are some additional table changes.  Please apply them all.
