### ISSUE TITLE
1.1.19 Realtime missing

### ISSUE THREAD

**Issue by hiddenicon** [Cacti/cacti#928]
We just upgraded to 1.1.19 and the realtime icon is missing next to the graphs. I cleared cache from browser and restarted httpd service. Realtime options are still available and configured.

![image](https://user-images.githubusercontent.com/10273594/29674837-5615d9be-88c1-11e7-83e8-72eb3e07e1a2.png)

![image](https://user-images.githubusercontent.com/10273594/29674861-62fbaaf0-88c1-11e7-90b8-9489a2562f53.png)

**Comment by sam-san91** [comment]
Check the permissions :)

**Comment by hiddenicon** [comment]
Permissions on the cache/realtime directory are good. Haven't changed from before the upgrade.

**Comment by sam-san91** [comment]
I meant within the cacti webinterface, the permissions for your user to view the realtime graphs.
Ran into the same problem ;)

**Comment by hiddenicon** [comment]
OH got it. Yes you are right. I guess that got changed during the upgrade!

![image](https://user-images.githubusercontent.com/10273594/29677137-2ecf27a0-88c8-11e7-99b9-7a1c079e0742.png)

**Comment by paulcalabro** [comment]
Just ran into the same issue.  It would be nice if these existing settings were retained between upgrades.

**Comment by vancefan** [comment]
So do I. Upgrade the version caused the settings missing should be a problem.
