### ISSUE TITLE
Overlapping frames

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#929]
I'm on 1.1.19 and I've started to see problems with overlapping frames. See the screenshot:
![screenshot_2017-08-25_18-40-17](https://user-images.githubusercontent.com/12864741/29737077-542f157a-89c5-11e7-987a-10ce2d6cb2b2.png)

**Comment by eschoeller** [comment]
This is in firefox. Version 54

**Comment by mhoran** [comment]
In Chrome, my graphs are pushed down below the end of the sidebar. This happened since upgrading to 1.1.18. Thinking this may be related.

![screenshot at 2017-08-25 21-02-22](https://user-images.githubusercontent.com/5330/29737275-f2b3afea-89d8-11e7-820c-2dc85fbf98db.png)

**Comment by cigamit** [comment]
Sorry about they guys.  Fixing this morning.

**Comment by cigamit** [comment]
Fix part 1 of 2 in.  There is still an issue with Classic.  Working on it.

**Comment by cigamit** [comment]
Okay, these issues are resolved now.  Remember to refresh your theme main.css, main.js, and layout.js file in cache.  In Firefox and IE, simply using F5 will do this.  It's more complicated in Chrome or Chromium based browsers.
