### ISSUE TITLE
Trees do not show graphs not assigned to any host

### ISSUE THREAD

**Issue by scamp** [Cacti/cacti#930]
Cacti 1.1.19 from FreeBSD ports.
After upgrade the Graphs page does not display graph trees which contain graphs that are not assigned to any host.
Steps to reproduce:
- Create a custom graph using existing data source
- Choose Device None for this graph
- Create a new graph tree, add the created graph to this tree
- Navigate to Graphs page, it does not contain created tree.

Not reproduced on 1.1.15.

**Comment by eschoeller** [comment]
I think I might also have a similar issue here. I am missing entire trees in 1.1.19 - and I also think the graphs inside these trees are completely gone too  - In one case the tree was populated only with legacy Aggregate graphs created way back in 0.8.6 days. Our DNS admin notified me about this after my upgrade from 1.1.16 to 1.1.19. I tried looking for the graphs for a long time (not really knowing what they were called) and ended up having to recreate them. 
![image](https://user-images.githubusercontent.com/12864741/29744883-1bc948d0-8a6b-11e7-83ce-7505f67a6cc5.png)
![image](https://user-images.githubusercontent.com/12864741/29744888-2d788866-8a6b-11e7-8ccc-d1f6635b33e7.png)
In this case, the "Aggregate Service" leaf is completely gone - but still shows up under the graph trees management window, except it's empty. And the graphs that used to be under that leaf are nowhere to be found. I have *not* been backing up my database between upgrades. Our database people may have backups.

**Comment by scamp** [comment]
In my case, the database had the information about graph trees and their elements, but UI was not able to display them. Also some of the trees affected contain old aggregate graphs created by 0.8.6 plugin.
As a temporary solution I'd suggest to roll back cacti files and update version table in DB.

**Comment by cigamit** [comment]
This and #931 are both related to the remove Graphs for disabled devices.

**Comment by cigamit** [comment]
I'm pretty sure this one is resolved with the latest auth.php fix.

**Comment by eschoeller** [comment]
My issue is fixed in 1.1.20

**Comment by scamp** [comment]
verified as fixed in 1.1.20
