### ISSUE TITLE
Aggregates are missing from list view

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#931]
I create an Aggregate, but when I look for it in list view, I cannot find it. It shows up under Console/Management/Aggregates, and from here I can place it on a tree .. which allows me to view the graph - but I should also be able to get to it from a list view too, imho.

**Comment by cciethor** [comment]
i have the same issue , also from tree view if there is aggregate graph it will give you dont have permission to view this section

**Comment by cigamit** [comment]
Okay, please test the latest auth.php and tell me if the other issues are resolved as well.
