### ISSUE TITLE
Aggregates shows many pages of entries but no graphs

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#933]
Check this one out:
![image](https://user-images.githubusercontent.com/12864741/29745029-5f67797e-8a6e-11e7-8691-5d583f8096b1.png)
![image](https://user-images.githubusercontent.com/12864741/29745037-6dd6fa16-8a6e-11e7-965e-5dfc72c543bd.png)
It seems like maybe it's getting confused by all my old legacy Aggregate graphs from 0.8.6 - it thinks there are 223 of them (hence 8 pages) but only shows 3 that have actually been made in 1.x. All the subsequent pages show 'No Aggregate Graphs Found'.

**Comment by cigamit** [comment]
I thought this was fixed a long time ago.  Have to recheck.  This may also be related to #930, #931.

**Comment by cigamit** [comment]
Okay, was not related.  Found the incorrect SQL again.  Resolved.
