### ISSUE TITLE
Template names missing in graph management list

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#934]
I noticed some graphs are missing the "Template Name" when viewed in the Graph Management pane. I sorted by "Template Name" and found a few occurrences. I think Cacti still knows what the template name is since when sorted by template name they still show up in the proper order. In the first example the blanks should say "AKCP - Temperature". In the second example they should say "APC InRow - Group Cooling". 
![screenshot_20170826_150212](https://user-images.githubusercontent.com/12864741/29745165-232c89a6-8a71-11e7-827e-be4e4db273f5.png)
![screenshot_20170826_150248](https://user-images.githubusercontent.com/12864741/29745164-205fb2f2-8a71-11e7-8efa-b56bcd21e2e4.png)

**Comment by cigamit** [comment]
Is this new, or something that has been doing on for a while.  Also, if you can tell me if these are data query based or simply template based graphs?  Lastly, if you look at the local graph id's of the items in question, can you do the following:

select graph_template_id from graph_local where id = ?
select * from graph_templates where id = the graph template id from above

Let me know that you are getting good results with that.  This may be related to #930, #931.  Which I will be putting the patch in for shortly.

**Comment by eschoeller** [comment]
Not sure if it's new or not. I just noticed it. These are both data queries. Both the sql queries seem to come back OK:
mysql> select * from graph_templates where id = 301;
+-----+----------------------------------+---------------------------+----------+
| id  | hash                             | name                      | multiple |
+-----+----------------------------------+---------------------------+----------+
| 301 | e578eb31caaeea7b7cddce0a1353980d | APC InRow - Group Cooling |          |
+-----+----------------------------------+---------------------------+----------+
1 row in set (0.00 sec)

mysql> select * from graph_templates where id = 511;
+-----+----------------------------------+--------------------+----------+
| id  | hash                             | name               | multiple |
+-----+----------------------------------+--------------------+----------+
| 511 | 12f7f8b68b1bce7a00d7784e00cf7200 | AKCP - Temperature |          |
+-----+----------------------------------+--------------------+----------+
1 row in set (0.00 sec)

**Comment by eschoeller** [comment]
Don't see much of a difference with this one (which is displaying):
mysql> select * from graph_templates where id = 512;
+-----+----------------------------------+-----------------+----------+
| id  | hash                             | name            | multiple |
+-----+----------------------------------+-----------------+----------+
| 512 | 1f5f5646dc00094671cc5f9240143b14 | AKCP - Humidity |          |
+-----+----------------------------------+-----------------+----------+
1 row in set (0.00 sec)

Devices that have AKCP - Humidity associated with it are enabled, they're the same as AKCP - Temperature.

**Comment by cigamit** [comment]
Okay, that is perfect.  Can you please perform a 'SELECT * FROM graph_local WHERE id = ?' in your case.  Also, are these new graphs, or older ones?

**Comment by eschoeller** [comment]
`mysql> select * from graph_local where graph_template_id=511;
+-------+-------------------+---------+---------------+---------------------+------------+
| id    | graph_template_id | host_id | snmp_query_id | snmp_query_graph_id | snmp_index |
+-------+-------------------+---------+---------------+---------------------+------------+
| 17588 |               511 |      60 |            55 |                   0 | 0          |
| 17589 |               511 |      60 |            55 |                   0 | 1          |
| 17590 |               511 |      60 |            55 |                   0 | 2          |
| 17591 |               511 |      60 |            55 |                   0 | 3          |
| 18420 |               511 |     443 |            55 |                   0 | 0          |
| 18635 |               511 |      60 |            55 |                   0 | 4          |
| 29172 |               511 |     263 |            55 |                   0 | 0          |
| 29173 |               511 |     263 |            55 |                   0 | 3          |
| 29529 |               511 |     503 |            55 |                   0 | 21         |
| 29530 |               511 |     503 |            55 |                   0 | 23         |
| 29531 |               511 |     503 |            55 |                   0 | 25         |
| 29532 |               511 |     503 |            55 |                   0 | 30         |
| 29533 |               511 |     503 |            55 |                   0 | 31         |
| 29534 |               511 |     503 |            55 |                   0 | 32         |
| 43250 |               511 |     503 |            55 |                   0 | 35         |
| 43251 |               511 |     503 |            55 |                   0 | 37         |
| 43252 |               511 |     503 |            55 |                   0 | 39         |
| 47475 |               511 |     503 |            55 |                   0 | 44         |
| 47476 |               511 |     503 |            55 |                   0 | 45         |
| 47478 |               511 |     503 |            55 |                   0 | 47         |
| 47479 |               511 |     503 |            55 |                   0 | 48         |
| 47563 |               511 |     503 |            55 |                   0 | 50         |
| 47564 |               511 |     503 |            55 |                   0 | 51         |
| 47565 |               511 |     503 |            55 |                   0 | 52         |
| 47566 |               511 |     503 |            55 |                   0 | 53         |
+-------+-------------------+---------+---------------+---------------------+------------+
`

`mysql> select * from graph_local where graph_template_id=301;
+------+-------------------+---------+---------------+---------------------+------------+
| id   | graph_template_id | host_id | snmp_query_id | snmp_query_graph_id | snmp_index |
+------+-------------------+---------+---------------+---------------------+------------+
| 7664 |               301 |     269 |            40 |                   0 | 0          |
| 7751 |               301 |     275 |            40 |                   0 | 0          |
| 7838 |               301 |     281 |            40 |                   0 | 0          |
| 7925 |               301 |     287 |            40 |                   0 | 0          |
+------+-------------------+---------+---------------+---------------------+------------+`

I hope this is what you meant ... 

These are all old graphs from 0.8.6 days. Running on 1.1.20 now.

**Comment by eschoeller** [comment]
I am guessing here that the snmp_query_graph_id should not be 0 in these cases?

**Comment by cigamit** [comment]
You are correct.  Let me pull the SQL statement from one of the upgrade scripts.

Please see if this query fixes it.  Since you were on the bleeding edge, you may have not executed this one:

`UPDATE graph_local AS gl
		INNER JOIN (
			SELECT DISTINCT local_graph_id, task_item_id
			FROM graph_templates_item
		) AS gti
		ON gl.id=gti.local_graph_id
		INNER JOIN data_template_rrd AS dtr
		ON gti.task_item_id=dtr.id
		INNER JOIN data_template_data AS dtd
		ON dtr.local_data_id=dtd.local_data_id
		INNER JOIN data_input_fields AS dif
		ON dif.data_input_id=dtd.data_input_id
		INNER JOIN data_input_data AS did
		ON did.data_template_data_id=dtd.id
		AND did.data_input_field_id=dif.id
		INNER JOIN snmp_query_graph_rrd AS sqgr
		ON sqgr.snmp_query_graph_id=did.value
		SET gl.snmp_query_graph_id=did.value
		WHERE input_output='in'
		AND type_code='output_type'
		AND gl.snmp_query_id>0`

**Comment by cigamit** [comment]
Going to close this one due to lack of feedback.

**Comment by eschoeller** [comment]
My bad. I ran the query. Here is the result:
<pre>
Query OK, 0 rows affected (9.06 sec)
Rows matched: 19898  Changed: 0  Warnings: 0
</pre>

**Comment by eschoeller** [comment]
Still missing the names in the graph management GUI.

**Comment by cigamit** [comment]
Going to reopen.  This week is busy though.

**Comment by eschoeller** [comment]
Upgraded to 1.1.35. Still seeing the same behavior with the same template names not displaying

**Comment by eschoeller** [comment]
Here's another wrinkle on this one, again something I have been noticing for awhile. The "Template" drop-down within the Console->Management->Graphs is also acting funky. See these screenshots:

![screenshot_20180220_225815](https://user-images.githubusercontent.com/12864741/36465399-1395bb9a-1692-11e8-8621-ecda84f67656.png)
![screenshot_20180220_225734](https://user-images.githubusercontent.com/12864741/36465403-18c7b21c-1692-11e8-92da-91749dc54723.png)
![screenshot_20180220_225711](https://user-images.githubusercontent.com/12864741/36465404-1c94bea8-1692-11e8-9a62-8d77e0790c05.png)
![screenshot_20180220_225644](https://user-images.githubusercontent.com/12864741/36465416-235de02a-1692-11e8-842b-1ded361c30fb.png)

I think, as crazy as this sounds, in some cases the graph "Title" of the graph template is being used instead of the actual Graph Template Name. Like this one for the APC InRow:

![screenshot_20180220_230510](https://user-images.githubusercontent.com/12864741/36465501-8d9bac56-1692-11e8-8f60-be5d9fb5a74c.png)

Or this one for the Server Technology Voltage Deviation template, it looks like it's snagging the Name from the data query definition and not the graph template name ... or something ... I'm getting a bit confused!
![screenshot_20180220_230930](https://user-images.githubusercontent.com/12864741/36465618-30e36458-1693-11e8-9af3-21b2ab0984ab.png)

**Comment by cigamit** [comment]
Think I have it now.  Update lib/auth.php and let me know if it's working now.  Should perform well too.

**Comment by eschoeller** [comment]
I'm running on 1.1.36 and still seeing all the same issues I saw in the past :(

**Comment by netniV** [comment]
This may be related to #1614

**Comment by anarkia1976** [comment]
It's resolve into 1.1.38.

**Comment by eschoeller** [comment]
I’ll upgrade as soon as I can and report back

**Comment by eschoeller** [comment]
OK, I upgraded to 1.1.38. I still have the same problems outlined in my Feb 20th comment :( I tried going into one of the affected data queries, and the affected graph template to just hit "save" ... thinking it might give something a swift 'kick', but no luck.

**Comment by netniV** [comment]
The template system has undergone some changes in 1.2.  If there are still any issues, I would suggest opening a new ticket.

**Comment by eschoeller** [comment]
I'm sure it has ... but 1.2 hasn't been released yet so I can't verify that this has been fixed yet. Can you reopen this and I will evaluate when 1.2 is officially released?

**Comment by netniV** [comment]
I would create a test system to test out 1.2 as it stands and copy over your data to try it out.  As with any major upgrade, always worth testing things with your own data before jumping straight in.
