### ISSUE TITLE
v1.1.19 - sites.php - TimeZone failure / read_config_option

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#936]
I was trying to make sure my timezone information was correct and noticed that I couldn't set the timezone against a site.  On further investigation, I found constant errors being reported when in sites.php and narrowed it down to a bad functionn name.  Line 175 tries to use read_config_options() which is incorrect as the correct function name has no 's' on it and should be read_config_option().

Below is the corrected version:

```
        case 'ajax_tz':
                print json_encode(db_fetch_assoc_prepared('SELECT Name AS label, Name AS `value`
                        FROM mysql.time_zone_name
                        WHERE Name LIKE ?
                        ORDER BY Name
                        LIMIT ' . read_config_option('autocomplete_rows'),
                        array('%' . get_nfilter_request_var('term') . '%')));

                break;
```

**Comment by cigamit** [comment]
Resolved, thanks!
