### ISSUE TITLE
interfaces.xml - ifDescr causes no columns to appear

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#937]
I had to modify interfaces.xml so that ifDescr was at the end of the file because when on graphs_new.php, the Interfaces data query would only show the Index and whether it was Up.  Once I moved the description to towards the end, all columns suddenly reappeared.  I am not sure if this was because the description was just too long or not.

**Comment by cigamit** [comment]
This is likely due to your screen size.  Part of the responsive UI will be to hide columns when the length get's too long for the row.  Moving it to the right does make sense.  We could optionally limit the display length.  It'll be fixed more permanently after the 1.1.20 release.

**Comment by netniV** [comment]
Was this ever done?

**Comment by cigamit** [comment]
Yes, got rid of the nowrap css attribute for table data (td).
