### ISSUE TITLE
Problem with upgrade database to 1.1.20

### ISSUE THREAD

**Issue by pautiina** [Cacti/cacti#938]
Hello. 
I have  problem with applying a database update.
This SQL not apply.
```
ALTER TABLE snmpagent_cache_textual_conventions
MODIFY COLUMN name VARCHAR(50) NOT NULL,
MODIFY COLUMN mib VARCHAR(50) NOT NULL,
MODIFY COLUMN type VARCHAR(50) NOT NULL,
PRIMARY KEY (`name`,`mib`,`type`)
```
Problem on last line: ```PRIMARY KEY (`name`,`mib`,`type`)```
My configuration:

- Mysql-Server: 5.6.35

- Database encoding: utf8mb4_general_ci

**Comment by cigamit** [comment]
If you do the updates in two passes does it work?  50+50+50 is less than 191, that's why I'm wondering.  Also, what error did you receive?

**Comment by cigamit** [comment]
Oh, I think the issue should be that 'ADD PRIMARY KEY', and not 'PRIMARY KEY'.  Crap.  I could have sworn I tested this.

**Comment by pautiina** [comment]
Resolved. Problem was on `ADD PRIMARY KEY`
