### ISSUE TITLE
Links back to device/graphs

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#940]
Having first tried with the basic ubuntu package of Cacti, I must say that the 1.1.x versions is so much better.  One thing that I've also managed to do is get THOLD working with the version from github and emails are coming through nicely.

However, the links in the emails use https://<cacti_server>/cacti//graph.php?local_graph_id=1311 to display the graph of the threshold but there is no way to get back to other graphs for the device.  

In my cash, one CPU was flagging up at over 80% usage for an extended period.  I wanted to double check the rest to make sure that it was only that one (and therefore not likely to cause an actual problem) but there didn't appear to be a way without going the long way around.  There should be some from of navigation back to the device in question if you have the permission to it.

**Comment by cigamit** [comment]
This is a Thold feature request.  Can you open it there?

**Comment by netniV** [comment]
I would disagree because it’s the graphs page which is cacti itself. I’m not asking to go to the other thold monitoring.
