### ISSUE TITLE
database upgrade to cacti 1.1.20 throwing error

### ISSUE THREAD

**Issue by mahendrix** [Cacti/cacti#943]
When I try to upgrade to Cacti 1.1.20 I get an error when the code tries to do an upgrade to the database.  The following mysql command fails:

mysql> ALTER TABLE snmpagent_cache_textual_conventions
    -> MODIFY COLUMN name VARCHAR(50) NOT NULL,
    -> MODIFY COLUMN mib VARCHAR(50) NOT NULL,
    -> MODIFY COLUMN type VARCHAR(50) NOT NULL,
    -> PRIMARY KEY (`name`,`mib`,`type`);

I have had to modify the code to do the following so that it is successful and version 1.1.20 works:

mysql> ALTER TABLE snmpagent_cache_textual_conventions
    -> MODIFY COLUMN name VARCHAR(50) NOT NULL,
    -> MODIFY COLUMN mib VARCHAR(50) NOT NULL,
    -> MODIFY COLUMN type VARCHAR(50) NOT NULL,
    -> **ADD** PRIMARY KEY (`name`,`mib`,`type`);
         
had to put the 'ADD' in front of the last line for the primary key so that it would work correctly.  Hopefully that  is correct......thanks....

**Comment by reboot1983** [comment]
Your fix is correct. This issue has already been fixed in #938.
