### ISSUE TITLE
Not all script output parameters parsed by poller due to poller_output table output column limit

### ISSUE THREAD

**Issue by coozoo** [Cacti/cacti#944]
hi,
**Description:**
In my case there is a problem with custom script where 43 output parameters in total around 1300 characters.
In my case only first 17 parameter are parsed fine.

**Version:**
Fresh install. (I mean no upgrades)
1.1.16

**Problem:**
Dig into logs with no errors, lead me to check this poller_output table.
Inside poller_output, output column is limited with 512 bytes, suppose it's made for better performance (in memory engine), but this engine support only varchar I'm not sure about "new big varchar", but text as well blob definitely are not supported:
```
# table_name, column_name, type
'poller_output', 'output', 'varchar(512)'
```
So I've made some downgrade to myisam engine (for example) and set this column type as text:

```
ALTER TABLE `cacti`.`poller_output` 
ENGINE = MyISAM ,
CHANGE COLUMN `output` `output` TEXT NOT NULL ;
```

After that everything started to work fine and all parameters has been parsed fine.

As for me poller should work or at least notify why it's not working or show some error in logs, but not like this strangely cut of the big part of parameters.

**I see two ways to solve that:**

1. Add option inside settings to use in memory engine or "usual" engines. And sure add column length check before writing poller output to this table and show error in case of exceeding limit
2. Simply to make this table driven by on disk engine with no limit aka text type.

As for me second option the easiest...

thanks,
Yura

**Comment by cigamit** [comment]
I think the solution is compact row format in newer implementations of InnoDB.

**Comment by coozoo** [comment]
Sorry I'm not familiar about compact row format how it can help.
But really if use innoDB engine with column type "text" suppose it should work fine too because again there is no such . I can try if needed :)

**Comment by cigamit** [comment]
Text is a very inefficient storage method.  It will not scale to large sites.  Suggest a varchar(xxx).

**Comment by cigamit** [comment]
We will close this issue and continue to have it documented as a known issue, one where there is a known workaround.  We do not want to increase the column width by default to larger than where it is today.
