### ISSUE TITLE
boost not updating after mass add of devices

### ISSUE THREAD

**Issue by mp3merlin** [Cacti/cacti#947]
I have a Cacti 1.1.16 test install with about 10000 devices which has been working fine for about 3 weeks.
All polling is done from a single remote poller (in the same LAN).
I decided to add about 2000 devices using the `add_device.php` CLI script. After the successful add, boost isn't running anymore.
I can still run a `poller_boost.php --force` to update the RRDs.

In my cacti.log (on the main server) I have some messages like this :

> 2017-08-30 17:50:09 - SYSTEM STATS: Time:8.2158 Method:spine Processes:4 Threads:50 Hosts:0 HostsPerProcess:0 DataSources:0 RRDsProcessed:0
> 2017-08-30 17:53:10 - ERROR PHP ERROR: Maximum execution time of 299 seconds exceeded in file: /var/www/cacti/lib/database.php on line: 374
> 2017-08-30 17:53:10 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4432 cacti_debug_backtrace)
> 2017-08-30 17:55:04 - SYSTEM STATS: Time:3.1443 Method:spine Processes:4 Threads:50 Hosts:0 HostsPerProcess:0 DataSources:0 RRDsProcessed:0
> 2017-08-30 17:57:32 - ERROR PHP ERROR: Maximum execution time of 299 seconds exceeded in file: /var/www/cacti/lib/snmpagent.php on line: 0
> 2017-08-30 17:57:32 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4432 cacti_debug_backtrace)
> 2017-08-30 18:00:12 - SYSTEM STATS: Time:10.4571 Method:spine Processes:4 Threads:50 Hosts:0 HostsPerProcess:0 DataSources:0 RRDsProcessed:0
> 2017-08-30 18:03:18 - ERROR PHP ERROR: Maximum execution time of 299 seconds exceeded in file: /var/www/cacti/lib/snmpagent.php on line: 823
> 2017-08-30 18:03:18 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4432 cacti_debug_backtrace)
> 2017-08-30 18:05:09 - SYSTEM STATS: Time:7.7355 Method:spine Processes:4 Threads:50 Hosts:0 HostsPerProcess:0 DataSources:0 RRDsProcessed:0
> 2017-08-30 18:06:53 - ERROR PHP ERROR: Maximum execution time of 299 seconds exceeded in file: /var/www/cacti/lib/snmpagent.php on line: 449
> 2017-08-30 18:06:53 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4432 cacti_debug_backtrace)

No problems on the poller :

> 2017-08-30 18:16:51 - SYSTEM STATS: Time:107.8277 Method:spine Processes:4 Threads:50 Hosts:12387 HostsPerProcess:3097 DataSources:116298 RRDsProcessed:0

Is there anything I missed that could explain my problem ?

**Comment by cigamit** [comment]
You need to turn on the slow query log to get more information on what is hanging up.  This is a support issue though and belongs on the forums.

**Comment by mp3merlin** [comment]
Thanks for the tip about the slow query log. However, after my post in the forum, I tried updating to 1.1.21 following the advice of Osiris but I still have the problem. He suggested that I reopen this issue, as this is a performance bug.
[https://forums.cacti.net/viewtopic.php?f=21&t=57899](url)
