### ISSUE TITLE
Every time when creating new graph Cacti creates new datasource

### ISSUE THREAD

**Issue by coozoo** [Cacti/cacti#948]
Hi,
**Description:**
Pretty common situation for using custom script:
1. I have perl script
2. Data input methods "attached" to that script
3. Configured Data Source template "attached" to Data nput methods
4. set of graph templates that using this Data source
5. and device template where all graphs attached
Next closer to problem:
6. there is defined Device
7. and Data Source attached to this device
Here the problem:
**Result:**
8. Now adding graph to device
every time new data source created.

Very annoying bug:
- now I need to reopen graph;
- select proper datasource;
- and delete the one that was created automatically;

If somebody can verify that, please do.

A point me where to search problem. It will ease to me to identify it.

Thanks
yura

**Comment by cigamit** [comment]
Please attach an animation of video of the issue.

**Comment by paulcalabro** [comment]
I can confirm I've observed this behavior. I'll see if I can get a screenshot.

**Comment by cigamit** [comment]
Can someone please create an animation and attach it here.

**Comment by coozoo** [comment]
Sorry, have no possibility to add animation due to trip )
but here is animation, let me know if there is some problem with it.
thank you
[grid.ogv.tar.gz](https://github.com/Cacti/cacti/files/1309076/grid.ogv.tar.gz)

**Comment by cigamit** [comment]
Ok, you may be creating from a template, but you are not using New Graphs interface.  Can you test using that method and see if the second data source is created?

**Comment by coozoo** [comment]
Actually I've experienced that using new method ) when I saw it I thought oh cool, but when after creation bunch of graphs I've got a lot of new devices, those thoughts goes away :)

**Comment by cigamit** [comment]
The animation helps.  It won't make it into 1.1.24 though.

**Comment by coozoo** [comment]
Am I understood right that is fixed in 1.1.24? because I've tried and got the same result...

**Comment by cigamit** [comment]
Sorry, too many issues to pan through.  Lost sight of this one.

**Comment by cigamit** [comment]
Okay, this is resolved now.
