### ISSUE TITLE
Responsive design and graph resizing in 1.1.20

### ISSUE THREAD

**Issue by scamp** [Cacti/cacti#949]
Starting from 1.1.20 cacti does not scale graphs on smaller screens, so it is hardly usable from mobile devices.
On version 1.1.15 graph were scaled based on screen width.
Also tree view page has a 82 px indent on left side.

**Comment by cigamit** [comment]
Please refesh your css and javascript.  These issues are resolved.  If you still feel that they are not resolved, you need to upload screen captures.

**Comment by scamp** [comment]
Sure, 
Ive cleared my browser cache and created screenshots of tree and list view pages
![screenshot_20170902-010513](https://user-images.githubusercontent.com/30675/29989484-f037e580-8f7b-11e7-883f-e843e8dba9fb.jpeg)
![screenshot_20170902-010318](https://user-images.githubusercontent.com/30675/29989485-f040a6c0-8f7b-11e7-9f2f-7b32af14ff6e.jpeg)

**Comment by cigamit** [comment]
Hide the filter and see if you can reproduce this.  Also, what browser and mobile platform?

**Comment by scamp** [comment]
The indent disappeared after hiding filter pane.
Graph still do not fit the screen width.
My platform is Chrome 60.0 on Android 7.0,

**Comment by cigamit** [comment]
Update layout.js and try again.  Should resize with the screen and orientation.  Though at some point we will take a bootstrap type column grid.  But not for 1.1.21.

**Comment by scamp** [comment]
Thanks @cigamit, now the graph tree view graphs are fully responsive.
Could you please tale a look at Time Graph View also? It seems to be affected by the issue.
Filter section is not responsive too, the controls are not visible on small screens.
Graph ident with filter open is still an issue.

**Comment by scamp** [comment]
Verified as fixed.
