### ISSUE TITLE
Automation - New graph rule can't change query type

### ISSUE THREAD

**Issue by hiddenicon** [Cacti/cacti#950]
Similar to issue #862, when creating a new graph rule you cannot change the Data Query type. Whatever is first in the list is chosen by default and anything else you choose it reverts back to the first one in the list. Seems to be a front-end issue again. 

If you create the graph rule using that first item in the list, then go back in and edit it later you can change it. 

We saw this in 1.1.17 and upgraded to 1.1.20 today and still see the issue.
I tried this across a few themes and all seem to do the same thing.

**Comment by cigamit** [comment]
Screen capture or animation please.

**Comment by hiddenicon** [comment]
![graph_rule](https://user-images.githubusercontent.com/10273594/30118689-a8e81230-92f1-11e7-9637-06afd933cd9b.gif)

Anything you choose defaults it back to the first item in the list. 
If I create the graph rule with that first list item, then go back in and edit it, I can pick a different Data Query type.

**Comment by hiddenicon** [comment]
With Dev tools network tab open.

![dev_network](https://user-images.githubusercontent.com/10273594/30124541-7b72f7f4-9303-11e7-860e-e7b2438bc2a6.gif)

**Comment by cigamit** [comment]
Thanks for the animation.  It really helped.  Resolved.  Will be a part of 1.1.22.
