### ISSUE TITLE
Don't unnecessarily prompt to accept licence on every upgrade

### ISSUE THREAD

**Issue by gloomytrousers** [Cacti/cacti#951]
Every time I do a minor version upgrade I am prompted to re-accept the GPL in the upgrade wizard. After I've accepted it once I should not be asked in future upgrades (unless something has changed) - IANAL but it seems unnecessary.

I'd actually question the worth of requiring explicit license acceptance at all - I can't think of any other open source software which has such a thing. We're not Microsoft!

**Comment by ronytomen** [comment]
This was intentionally done as we wanted to make sure everyone is aware this software is GPLv2. It was also done as a reminder to those using Cacti in their products that it is GPLv2.

I agree it can be annoying, but at this time I'm not inclined to remove it unless someone can give me a compelling argument for the loss of 2 seconds of their life.

**Comment by gloomytrousers** [comment]
It's a question of annoyance factor/slick UX vs importance of telling people they're using a GPL'd app. That would be a religious argument - I've made my suggestion, but you're the one writing the code - your call ;-)

**Comment by cigamit** [comment]
I could write you a greasemonkey script that skips it if you want :)
