### ISSUE TITLE
1.1.21  CMDPHP Validation Error, Variable:local_graph_id

### ISSUE THREAD

**Issue by ikorzha** [Cacti/cacti#955]
After latest 1.2.21 upgrade I no longer able to view graph properties:

![graph-source](https://user-images.githubusercontent.com/11211789/30064934-4b7304dc-9221-11e7-8ae2-66dd44a83b8a.gif)

Errors in the log below:
2017/09/05  09:58:21 - CMDPHP Validation Error, Variable:local_graph_id,  Value:graph_296 Backtrace: (/graph.php: 38  get_filter_request_var)(/lib/html_utility.php: 435  die_html_input_error)(/lib/html_validate.php: 60 cacti_debug_backtrace)
--
2017/09/05 09:57:33 - CMDPHP Validation Error,  Variable:local_graph_id, Value:graph_11550 Backtrace: (/graph.php: 38  get_filter_request_var)(/lib/html_utility.php: 435  die_html_input_error)(/lib/html_validate.php: 60 cacti_debug_backtrace)

**Comment by cigamit** [comment]
Resolved.  Just update graph.php.  Thanks for catching.

**Comment by ikorzha** [comment]
Applied graph.php, all working now thank you.  If you have a chance, can we please finish off issue 109 in thold based on last update...
Thank you in advance,

**Comment by paulcalabro** [comment]
@cigamit I'm currently using `cacti-1.1.21`. I'm having this same issue. Looking to apply your fix. I noticed that the `graphs.php` in the repo seems different than what I have deployed. For example, 

I see all these includes in `graphs.php`:

```
include('./include/auth.php');
include_once('./lib/utility.php');
include_once('./lib/api_graph.php');
include_once('./lib/api_tree.php');
include_once('./lib/api_data_source.php');
include_once('./lib/api_aggregate.php');
include_once('./lib/api_automation.php');
include_once('./lib/template.php');
include_once('./lib/html_tree.php');
include_once('./lib/html_form_template.php');
include_once('./lib/rrd.php');
include_once('./lib/data_query.php');
```

However, I only see these includes in the `graphs.php` contained within the repo:

```
$guest_account = true;
include('./include/auth.php');
include_once('./lib/rrd.php');
```

Can you please explain why that is?

**Comment by paulcalabro** [comment]
Actually, I just figured it out. I was looking at **graphs.php** when I should have been looking at **graph.php**.

**Comment by paulcalabro** [comment]
Cool, that resolve my issue! Thanks for the fix!
