### ISSUE TITLE
cacti 1.1.21 how to install plugins

### ISSUE THREAD

**Issue by Initarts** [Cacti/cacti#957]
download plugins   /var/www/html/cacti/plugins/ 
No Plugins Found
![plugins](https://user-images.githubusercontent.com/8800508/30091661-574a417c-92ed-11e7-84d9-f904c62d6a42.png)
how to do ?

**Comment by paulcalabro** [comment]
What are the file and group ownerships set to? What are the file permissions set to?

**Comment by Initarts** [comment]
@paulcalabro  

chown -R apache:apache /var/www/html/cacti/
chmod -R 755 /var/www/html/cacti/

$database_type     = 'mysql';
$database_default  = 'cacti';
$database_hostname = 'localhost';
$database_username = 'cacti';
$database_password = 'password';
$database_port     = '3306';
$database_ssl      = false;

**Comment by cigamit** [comment]
What distro?  Did you install cacti from a Package or from source?  Which plugins?  Where did you download them?  Your not giving us a lot of info.

**Comment by paulcalabro** [comment]
Can you please run:

`ls -Al  /var/www/html/cacti/plugins/`

**Comment by Initarts** [comment]
@paulcalabro  
https://docs.cacti.net/plugins/
https://docs.cacti.net/plugins.install   &&  old version cacti  is ok!!but cacti 1.1.20/21 do no 


[root@lan-switch-cacti ~]# ls -Al /var/www/html/cacti/plugins/        
总用量 4
-rwxr-xr-x 1 apache apache  40 9月   5 04:37 index.php
drwxr-xr-x 4 apache apache 161 10月  6 2011 monitor
drwxr-xr-x 3 apache apache 125 7月  30 2010 ntop
drwxr-xr-x 3 apache apache 106 9月  25 2011 settings
drwxr-xr-x 5 apache apache 325 6月  10 2013 thold

**Comment by Initarts** [comment]
@paulcalabro  
now  here find three plugin,but is old time. it do not work. where is the plugin settings ?


Not Compatible, Legacy Plugin
--
![image](https://user-images.githubusercontent.com/8800508/30093192-4ebe2f10-92f6-11e7-9766-c622e63f66af.png)

If I want to use traffic monitoring, alarm functions like the old version, and send mail, please choose what plug-in or how to implement the function?

**Comment by paulcalabro** [comment]
It's considered a "Legacy Plugin" based on this code:

```
function plugin_is_compatible($plugin) {
	global $config;
	$info = plugin_load_info_file($config['base_path'] . '/plugins/' . $plugin . '/INFO');
	if ($info !== false) {
		if (!isset($info['compat']) || cacti_version_compare(CACTI_VERSION, $info['compat'], '<')) {
			return array('compat' => false, 'requires' => __('Requires: Cacti >= %s', $info['compat']));
		}
	} else {
		return array('compat' => false, 'requires' => __('Legacy Plugin'));
	}
	return array('compat' => true, 'requires' => __('Requires: Cacti >= %s', $info['compat']));
}
```
https://github.com/Cacti/cacti/blob/b6c412e41e9d1c863c4ad26a9f2ec9afa4fcdc60/lib/plugins.php#L783

Either: 
- The plugin has no info file 
- It has an info file, but the `compat` value is null
- The Cacti version is less than minimum `compat` value.

**Comment by Initarts** [comment]
@cigamit  now download https://codeload.github.com/Cacti/plugin_thold/zip/develop 
New problems
![image](https://user-images.githubusercontent.com/8800508/30094979-59e69e5c-9302-11e7-8494-374fd9274fc5.png)

error

Validation error for variable id with a value of plugin_thold-develop.  See backtrace below for more details.
(/plugins.php: 51 get_filter_request_var)(/lib/html_utility.php: 435 die_html_input_error)(/lib/html_validate.php: 60 cacti_debug_backtrace

**Comment by jpobeda** [comment]
Rename the dir to thold..

**Comment by cigamit** [comment]
Please note the following Wiki article: https://github.com/Cacti/cacti/wiki/PluginMigration
