### ISSUE TITLE
 Cacti 1.1.20 Group Tree permission issue

### ISSUE THREAD

**Issue by elwesingollo** [Cacti/cacti#958]
Hi,
as suggested in the forum, i'm opening an issue/question on graph trees permissions.
I would like to assign all permissions on user_group basis instead of having them on user basis.
this seems to work only for the list view tab and for the preview tab.
i've create this test user:
![capture1](https://user-images.githubusercontent.com/20436175/30155632-9c343d62-93bd-11e7-9ca1-27fa03d19f7b.JPG)
and I've assigned to this user group:
![capture3](https://user-images.githubusercontent.com/20436175/30155721-da32590a-93bd-11e7-8cf2-07f4b2a990d6.JPG)
So this is the sum of the permission:
![capture2](https://user-images.githubusercontent.com/20436175/30155683-bfba1fcc-93bd-11e7-9bab-d37b990fb015.JPG)
the results are that i can see all the graphs in the list view and in the preview but no tree in the tree view.
![capture4](https://user-images.githubusercontent.com/20436175/30155831-2f5a13b4-93be-11e7-9a2e-3970ecd78a29.JPG)
![capture5](https://user-images.githubusercontent.com/20436175/30155837-345a753e-93be-11e7-994c-3f7aadb46b9a.JPG)

It's a correct behaviour? how can i fix the tree view permissions on users groups?

Best Regards
Alessandro

**Comment by elwesingollo** [comment]
hello everibody,
i found that you can modify the function is_tree_allowed in file lib/auth.php.
you can add from row 445 onwards.
you have to add this query to check group trees perm:
`                /* check for group trees */
                $gtrees = db_fetch_assoc_prepared("SELECT uagm.user_id
                        FROM user_auth_group AS uag
                        INNER JOIN user_auth_group_members AS uagm
                        ON uag.id = uagm.group_id
                        INNER JOIN user_auth_group_perms as uagp
                        ON uagp.group_id = uag.id
                        WHERE uag.enabled = 'on'
                        AND uagm.user_id = ?
                        and uagp.item_id = ?",
                        array($user, $tree_id)
                );`

**Comment by cigamit** [comment]
So, the user has access to the tree but not seeing the graphs is that correct?

**Comment by elwesingollo** [comment]
hi,
no not exactly, user "test" should have the access to the tree inherited from group "NO SPD OSS" , but he doesn't see any tree.
![capture6](https://user-images.githubusercontent.com/20436175/30278190-1843c518-970a-11e7-9644-8e9f95c68159.JPG)

**Comment by cigamit** [comment]
Okay, we will have test this case and verify what is broken.

**Comment by cigamit** [comment]
I know it's a stupid question, but the group is enabled right?

**Comment by elwesingollo** [comment]
yes, the group is enabled, the group default tree policy is to "deny" and the group has single permissions on some trees.
![capture7](https://user-images.githubusercontent.com/20436175/30333787-17a43b4a-97de-11e7-93f3-a8e86eb59870.JPG)

**Comment by cigamit** [comment]
Thanks!

**Comment by cigamit** [comment]
Resolved.  Thanks for your patience.

**Comment by elwesingollo** [comment]
Thanks to you too!
