### ISSUE TITLE
Broken Reporting Emails

### ISSUE THREAD

**Issue by paulcalabro** [Cacti/cacti#959]
I've been experiencing an issue in the last couple releases (I upgraded to `1.1.21` to see if it would resolve it) where the reporting emails sent out daily contain broken HTML and/or images . I've tried pretty much all the templates (and no template) and each option seems to have its own set of issues.

**With template (Cacti Group Format):** 
<img width="833" alt="screen shot 2017-09-07 at 11 37 19 am" src="https://user-images.githubusercontent.com/585059/30180024-66ef9bfa-93c3-11e7-83d3-7a24f9e2e8b9.png">

<img width="1917" alt="screen shot 2017-09-07 at 12 05 35 pm" src="https://user-images.githubusercontent.com/585059/30180577-31e51d0c-93c5-11e7-9184-7610f83b6e51.png">

<img width="1920" alt="screen shot 2017-09-07 at 12 08 49 pm" src="https://user-images.githubusercontent.com/585059/30180710-aa2c31ec-93c5-11e7-90a7-34baea77689a.png">

**Without template (i.e. Without "Use Custom Format" selected):**
<img width="849" alt="screen shot 2017-09-07 at 12 12 12 pm" src="https://user-images.githubusercontent.com/585059/30180937-666cd6fe-93c6-11e7-9bb6-e26781c51285.png">

**Comment by paulcalabro** [comment]
p.s. I installed this via the tarball.

**Comment by paulcalabro** [comment]
Here's the HTML content of the email:

```html
<html>                                                                                                                                                                          <head>                                                                                                                                                                          <meta http-equiv="Content-Type" content="text/html; charset=utf-8">                                                                                                          <meta content="text/html; charset=utf-8">                                                                                                                                 </head>                                                                                                                                                                      <body>
      <table class="report_table">
         <tbody>
            <tr class="title_row">
               <td class="title" style="text-align:left; font-size:12pt"><REDACTED> </td>
            </tr>
            <tr class="image_row">
               <td style="text-align:left">
                  <table>
                     <tbody>
                        <tr>
                           <td style="padding:5px; text-align:left"><img src="cid:19000_0@localhost"> </td>
                        </tr>
                     </tbody>
                  </table>
               </td>
            </tr>
            <tr class="image_row">
               <td style="text-align:left">
                  <table>
                     <tbody>
                        <tr>
                           <td style="padding:5px; text-align:left"><img src="cid:19000_1@localhost"> </td>
                        </tr>
                     </tbody>
                  </table>
               </td>
            </tr>
            <tr class="image_row">
               <td>
                  <table>
                     <tbody>
                        <tr>
                           <td style="padding:5px; text-align:left"><img src="cid:19000_2@localhost"> </td>
                        </tr>
                     </tbody>
                  </table>
               </td>
               &lt; /tr&gt;
            </tr>
         </tbody>
      </table>
      <br>
   </body>
</htm
```

**Comment by paulcalabro** [comment]
I ran this through the W3C HTML5 validator and noticed what appears to be an errant `&lt; /tr&gt;` in the table.

**Comment by paulcalabro** [comment]
This issues gets more and more interesting. So using the Office 365 mail REST API, I've retrieved the inline attachments, extracted the content bytes, and  view the images using this convenient [Fiddle](https://jsfiddle.net/casiano/xadvz/). I was able to view all the attachments. 

So... images are being attached correctly...some of them just don't display. 

I'll try forwarding it to another email address.

**Comment by cigamit** [comment]
I'm suspecting this has just about everything to do with your mail client.  We are encoding the email now for UTF8 and foreign languages.  You might want to see if there is an update to the phpmailer and test using it.  That's all I can think of.  Maybe a bug in their encoder.

**Comment by paulcalabro** [comment]
Thanks @cigamit for checking into this! 

The mail clients I've tried so far are:

- Outlook Web Access (in both Safari and Chrome)
- Mac Mail

I'll try updating phpmailer as well as testing a few more clients.

**Comment by cigamit** [comment]
Any updates on this.  It's odd that the tr is handled using specialchars.  It has to be the encode/decode portion of the mailer as I don't think we are specialcharing the thing anywhere.

Can you test by looking for the following text in lib/functions.php "quoted-printable", and comment out that line.  Then resend.

**Comment by cigamit** [comment]
I just found an article on this that suggested we change the Encoding to 'base64' as it resolves the decoding issues in Outlook and other email clients.

**Comment by cigamit** [comment]
Resolving based upon recommendation from the phpmailer github issues database solution reported by others.
