### ISSUE TITLE
PAW Theme + Thold

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#96]
/plugins/thold/thold.php?action=add

Cannot add Threshold Template - because You Cannot choose nothing from filters.
![pawtheme_thold](https://cloud.githubusercontent.com/assets/17087236/21499758/e686d066-cc38-11e6-8725-2b45c9d3686e.png)

**Comment by interduo** [comment]
It's a bug not enhancement. I cannot use Paw theme because of that.

**Comment by cigamit** [comment]
This issue is resolved.
