### ISSUE TITLE
Error when open a device

### ISSUE THREAD

**Issue by vancefan** [Cacti/cacti#961]
When I open or create a new device, there is debug info shows in device info aera. Not sure my setup issue or the code issue, please investigate.

This issue occur when I upgrade from 1.1.16 to 1.1.20, 1.1.21 also got this issue.

![image](https://user-images.githubusercontent.com/15649628/30236888-a32f0c28-9557-11e7-8821-bbf30614b2b6.png)

**Comment by cigamit** [comment]
This looks like it might be related to a plugin.  Please provide more details, and an animation.  Also, what plugins are installed.  Disable one at a time to insure that this is not the problem.

**Comment by vancefan** [comment]
That was strange, it is recover automatically. Maybe it caused by my slave cacti server, I recently change from apache to nginx, after I change my master cacti server to nginx, the issue not exist any more.  
Anyway , thanks for help.

**Comment by cigamit** [comment]
Yea, that's it.  The remote_agent.php was simply opened like a file since you Apache configuration was not set properly.  Closing.
