### ISSUE TITLE
"DBCALL ERROR: SQL Assoc Failed!" after update to 1.1.22 from 1.1.21

### ISSUE THREAD

**Issue by sd3m0n** [Cacti/cacti#964]
![1](https://user-images.githubusercontent.com/25234512/30290107-f1604cbe-9736-11e7-9dbd-07ca304098ad.png)
Here are log messages:

2017/09/11 17:05:02 - CMDPHP SQL Backtrace: (/poller.php: 715 snmpagent_poller_bottom)(/lib/snmpagent.php: 464 table)(/lib/mib_cache.php: 136 columns)(/lib/mib_cache.php: 407 db_fetch_assoc_prepared)(/lib/database.php: 395 cacti_debug_backtrace)
2017/09/11 17:05:02 - DBCALL ERROR: SQL Assoc Failed!, Error: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'cactidb.snmpagent_cache.oid' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
2017/09/11 17:05:02 - DBCALL ERROR: SQL Assoc Failed!, Error:1055, SQL:'SELECT * FROM `snmpagent_cache` WHERE `oid` LIKE ? GROUP BY name ORDER BY oid'
2017/09/11 17:05:02 - CMDPHP SQL Backtrace: (/poller.php: 715 snmpagent_poller_bottom)(/lib/snmpagent.php: 372 table)(/lib/mib_cache.php: 136 columns)(/lib/mib_cache.php: 407 db_fetch_assoc_prepared)(/lib/database.php: 395 cacti_debug_backtrace)
2017/09/11 17:05:02 - DBCALL ERROR: SQL Assoc Failed!, Error: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'cactidb.snmpagent_cache.oid' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
2017/09/11 17:05:02 - DBCALL ERROR: SQL Assoc Failed!, Error:1055, SQL:'SELECT * FROM `snmpagent_cache` WHERE `oid` LIKE ? GROUP BY name ORDER BY oid'
2017/09/11 17:05:02 - CMDPHP SQL Backtrace: (/poller.php: 715 snmpagent_poller_bottom)(/lib/snmpagent.php: 353 table)(/lib/mib_cache.php: 136 columns)(/lib/mib_cache.php: 407 db_fetch_assoc_prepared)(/lib/database.php: 395 cacti_debug_backtrace)
2017/09/11 17:05:02 - DBCALL ERROR: SQL Assoc Failed!, Error: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'cactidb.snmpagent_cache.oid' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
2017/09/11 17:05:02 - DBCALL ERROR: SQL Assoc Failed!, Error:1055, SQL:'SELECT * FROM `snmpagent_cache` WHERE `oid` LIKE ? GROUP BY name ORDER BY oid'
2017/09/11 17:05:02 - CMDPHP SQL Backtrace: (/poller.php: 715 snmpagent_poller_bottom)(/lib/snmpagent.php: 312 table)(/lib/mib_cache.php: 136 columns)(/lib/mib_cache.php: 407 db_fetch_assoc_prepared)(/lib/database.php: 395 cacti_debug_backtrace)
2017/09/11 17:05:02 - DBCALL ERROR: SQL Assoc Failed!, Error: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'cactidb.snmpagent_cache.oid' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
2017/09/11 17:05:02 - DBCALL ERROR: SQL Assoc Failed!, Error:1055, SQL:'SELECT * FROM `snmpagent_cache` WHERE `oid` LIKE ? GROUP BY name ORDER BY oid'
2017/09/11 17:05:02 - CMDPHP SQL Backtrace: (/poller.php: 528 log_cacti_stats)(/poller.php: 678 snmpagent_cacti_stats_update)(/lib/snmpagent.php: 50 table)(/lib/mib_cache.php: 136 columns)(/lib/mib_cache.php: 407 db_fetch_assoc_prepared)(/lib/database.php: 395 cacti_debug_backtrace)
2017/09/11 17:05:02 - DBCALL ERROR: SQL Assoc Failed!, Error: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'cactidb.snmpagent_cache.oid' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
2017/09/11 17:05:02 - DBCALL ERROR: SQL Assoc Failed!, Error:1055, SQL:'SELECT * FROM `snmpagent_cache` WHERE `oid` LIKE ? GROUP BY name ORDER BY oid'
2017/09/11 17:05:02 - SYSTEM STATS: Time:1.2305 Method:spine Processes:1 Threads:1 Hosts:4 HostsPerProcess:4 DataSources:42 RRDsProcessed:40

**Comment by sd3m0n** [comment]
my SQL config does contain this option "sql_mode=only_full_group_by" but everything was OK until I've upgraded to *.22. Removing this option doesn't help, because there are no green (working) lines in log. Only the last one as in the text above.

**Comment by ikorzha** [comment]
I do have similar issue after upgrade to 1.1.22
![snmpagent](https://user-images.githubusercontent.com/11211789/30283825-2f52006c-96e7-11e7-81c9-e38fe68a8ea3.gif)

**Comment by Izmenoff** [comment]
solved in 1.1.23

**Comment by cigamit** [comment]
Yea, this was a horrible mistake on my part as it risks corrupting peoples databases.  We fixed it in 24 hours, but letting it out there was a bad things to begin with.

**Comment by The-Mafioso** [comment]
HI, I am facing this issue even with the latest version 1.1.26

![untitled](https://user-images.githubusercontent.com/27900099/31593745-3796b2a0-b239-11e7-8c07-6800957d60ae.png)

The below error message appear when i add a new device and there are no data sources displayed for the old devices/new (log below)

2017/10/16 06:09:10 - DBCALL ERROR: SQL Assoc Failed!, Error:1055, SQL:'SELECT    data_template.name AS data_template_name,    data_template_rrd.data_source_name,    data_template_data.*    FROM (data_template, data_template_rrd, data_template_data, graph_templates_item)    WHERE graph_templates_item.task_item_id = data_template_rrd.id    AND data_template_rrd.data_template_id = data_template.id    AND data_template_data.data_template_id = data_template.id    AND data_template_rrd.local_data_id = 0    AND data_template_data.local_data_id = 0    AND graph_templates_item.local_graph_id = 0    AND graph_templates_item.graph_template_id = ?    GROUP BY data_template.id    ORDER BY data_template.name'


2017/10/16 06:09:10 - DBCALL ERROR: SQL Assoc Failed!, Error: Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'cactidb.data_template_rrd.data_source_name' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

2017/10/16 06:09:10 - CMDPHP SQL Backtrace: (/graphs_new.php: 37 form_save)(/graphs_new.php: 123 host_new_graphs)(/graphs_new.php: 346 db_fetch_assoc_prepared)(/lib/database.php: 401 cacti_debug_backtrace)


2017/10/16 06:09:10 - DBCALL ERROR: SQL Assoc Failed!, Error:1055, SQL:'SELECT dt.id, dt.name, dtr.data_source_name  FROM data_template AS dt  INNER JOIN data_template_rrd AS dtr  ON dtr.data_template_id=dt.id  INNER JOIN graph_templates_item AS gti  ON gti.task_item_id=dtr.id  WHERE dtr.local_data_id=0  AND gti.local_graph_id=0  AND gti.graph_template_id = ?  GROUP BY dt.id  ORDER BY dt.name'


2017/10/16 06:09:10 - DBCALL ERROR: SQL Assoc Failed!, Error: Expression #3 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'cactidb.dtr.data_source_name' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by


2017/10/16 06:09:10 - CMDPHP SQL Backtrace: (/graphs_new.php: 37 form_save)(/graphs_new.php: 123 host_new_graphs)(/graphs_new.php: 395 host_new_graphs_save)(/graphs_new.php: 259 create_complete_graph_from_template)(/lib/template.php: 1114 db_fetch_assoc_prepared)(/lib/database.php: 401 cacti_debug_backtrace)


2017/10/16 06:09:10 - ERROR PHP NOTICE: Undefined index: local_data_id in file: /var/www/cacti/graphs_new.php  on line: 264


2017/10/16 06:09:10 - CMDPHP PHP ERROR NOTICE Backtrace: (/graphs_new.php: 37 form_save)(/graphs_new.php: 123 host_new_graphs)(/graphs_new.php: 395 host_new_graphs_save)(/graphs_new.php: 264 CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)
2017/10/16 06:09:10 - DBCALL ERROR: SQL Assoc Failed!, Error:1055, SQL:'SELECT dt.id, dt.name, dtr.data_source_name  FROM data_template AS dt  INNER JOIN data_template_rrd AS dtr  ON dtr.data_template_id=dt.id  INNER JOIN graph_templates_item AS gti  ON gti.task_item_id=dtr.id  WHERE dtr.local_data_id=0  AND gti.local_graph_id=0  AND gti.graph_template_id = ?  GROUP BY dt.id  ORDER BY dt.name'


2017/10/16 06:09:10 - DBCALL ERROR: SQL Assoc Failed!, Error: Expression #3 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'cactidb.dtr.data_source_name' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by


2017/10/16 06:09:10 - CMDPHP SQL Backtrace: (/graphs_new.php: 37 form_save)(/graphs_new.php: 123 host_new_graphs)(/graphs_new.php: 395 host_new_graphs_save)(/graphs_new.php: 259 create_complete_graph_from_template)(/lib/template.php: 1114 db_fetch_assoc_prepared)(/lib/database.php: 401 cacti_debug_backtrace)


2017/10/16 06:09:10 - ERROR PHP NOTICE: Undefined index: local_data_id in file: /var/www/cacti/graphs_new.php  on line: 264


2017/10/16 06:09:10 - CMDPHP PHP ERROR NOTICE Backtrace: (/graphs_new.php: 37 form_save)(/graphs_new.php: 123 host_new_graphs)(/graphs_new.php: 395 host_new_graphs_save)(/graphs_new.php: 264 CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)

**Comment by cigamit** [comment]
What is your database version type and version?

**Comment by cigamit** [comment]
Also, goto the mysql prompt, and run the following command:

`show global variables like '%mode%';`

Upload the results.  You have to turn a few things off.  We are supposed to do this in the database.php, but MariaDB/MySQL keeps adding more options.

**Comment by The-Mafioso** [comment]
Here is the log:

mysql> show global variables like '%mode%';
+--------------------------+-------------------------------------------------------------------------------------------------------------------------------------------+
| Variable_name            | Value                                                                                                                                     |
+--------------------------+-------------------------------------------------------------------------------------------------------------------------------------------+
| block_encryption_mode    | aes-128-ecb                                                                                                                               |
| gtid_mode                | OFF                                                                                                                                       |
| innodb_autoinc_lock_mode | 1                                                                                                                                         |
| innodb_strict_mode       | ON                                                                                                                                        |
| offline_mode             | OFF                                                                                                                                       |
| rbr_exec_mode            | STRICT                                                                                                                                    |
| slave_exec_mode          | STRICT                                                                                                                                    |
| sql_mode                 | ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+--------------------------+-------------------------------------------------------------------------------------------------------------------------------------------+
8 rows in set (0.00 sec)

MYSQL Ver.
![untitled](https://user-images.githubusercontent.com/27900099/31629299-e1bc4114-b2bb-11e7-9d91-134ff053db81.png)

**Comment by cigamit** [comment]
Edit /etc/my.cnf and change sql_mode to the following:

`sql_mode = NO_ENGINE_SUBSTITUTION`

Then restart mysql and start your install/upgrade again.

**Comment by welj** [comment]
I have too:


2017/10/17 10:49:37 - CMDPHP SQL Backtrace: (/pollers.php: 168 pollers)(/pollers.php: 601 db_fetch_assoc)(/lib/database.php: 360 db_fetch_assoc_prepared)(/lib/database.php: 401 cacti_debug_backtrace)
--
2017/10/17 10:49:37 - DBCALL ERROR: SQL Assoc Failed!, Error: Column 'hostname' in order clause is ambiguous
2017/10/17 10:49:37 - DBCALL ERROR: SQL Assoc Failed!, Error:1052, SQL:'SELECT poller.*, count(h.id) AS hosts FROM poller LEFT JOIN host AS h ON h.poller_id=poller.id GROUP BY poller.id ORDER BY INET_ATON(hostname) ASC LIMIT 0,30'
2017/10/17 10:49:22 - CMDPHP SQL Backtrace: (/pollers.php: 168 pollers)(/pollers.php: 601 db_fetch_assoc)(/lib/database.php: 360 db_fetch_assoc_prepared)(/lib/database.php: 401 cacti_debug_backtrace)
2017/10/17 10:49:22 - DBCALL ERROR: SQL Assoc Failed!, Error: Column 'hostname' in order clause is ambiguous
2017/10/17 10:49:22 - DBCALL ERROR: SQL Assoc Failed!, Error:1052, SQL:'SELECT poller.*, count(h.id) AS hosts FROM poller LEFT JOIN host AS h ON h.poller_id=poller.id GROUP BY poller.id ORDER BY INET_ATON(hostname) ASC LIMIT 0,30'
2017/10/17 10:49:18 - CMDPHP SQL Backtrace: (/pollers.php: 168 pollers)(/pollers.php: 601 db_fetch_assoc)(/lib/database.php: 360 db_fetch_assoc_prepared)(/lib/database.php: 401 cacti_debug_backtrace)
2017/10/17 10:49:18 - DBCALL ERROR: SQL Assoc Failed!, Error: Column 'hostname' in order clause is ambiguous
2017/10/17 10:49:18 - DBCALL ERROR: SQL Assoc Failed!, Error:1052, SQL:'SELECT poller.*, count(h.id) AS hosts FROM poller LEFT JOIN host AS h ON h.poller_id=poller.id GROUP BY poller.id ORDER BY INET_ATON(hostname) ASC LIMIT 0,30'

**Comment by hansenshi** [comment]
same error,
add content "sql_mode = NO_ENGINE_SUBSTITUTION" in /etc/my.cnf, It is solved. 
Thanks
