### ISSUE TITLE
SMTP security set to none but still trying to use TLS

### ISSUE THREAD

**Issue by andermat8** [Cacti/cacti#966]
Running version 1.1.10 and am unable to get emailing to work.  Did a wireshark and see it trying to use TLSv1.2, see EHLO, STARTTLS, etc.  I attempted to toggle between SSL, TLS, and none and I see a difference between SSL and TLS but when I select none it acts like TLS is selected.  We can't use encryption as the server is rejecting the cert from our email forwarder.

**Comment by paulcalabro** [comment]
I'm using `1.1.21` and I'm unable to reproduce this error. 
When I specify `TLS`, I see this: 

<img width="1608" alt="screen shot 2017-09-11 at 8 19 35 pm" src="https://user-images.githubusercontent.com/585059/30306993-3b63c2d4-9730-11e7-8568-f5916d1970fc.png">

When I specify `None, I see this:

<img width="1534" alt="screen shot 2017-09-11 at 8 25 51 pm" src="https://user-images.githubusercontent.com/585059/30307017-5878dd0a-9730-11e7-985d-637ef30497da.png">

Can you please provide a screenshot of your mail settings?

**Comment by paulcalabro** [comment]
Also, can you please show the value setting currently stored in your database:

<img width="750" alt="screen shot 2017-09-11 at 8 50 36 pm" src="https://user-images.githubusercontent.com/585059/30307434-01e588dc-9733-11e7-8014-e06f2d6ad81a.png">

**Comment by cigamit** [comment]
Thanks Paul.  If you could help here, that would be appreciated.

**Comment by andermat8** [comment]
I'm also running version 1.1.17 and getting the same issue.  Checked both DB's settings_smpt_secure and they are set to none.  Not sure if this may be a server setting.  Running Windows Server 2012.  
![cactimail](https://user-images.githubusercontent.com/29753529/30327085-cb89c328-9798-11e7-9541-2a33b892d1a4.png)

**Comment by andermat8** [comment]
Testing with the latest version (1.1.23) and it still tries to use TLS.  Used another program that sends emails and it does not use TLS and email sends just fine.  At a loss on how to prevent Cacti from using TLS.

**Comment by cigamit** [comment]
I did find an issue with security, though it was in the ping function, and I've committed that fix.

If this resolves the problem, please go ahead and close.  Also, please test ping true and false.  Lastly, for the self signed certificate on the Windows machine, there is a process for importing it.  You could find it if patient enough on the Cacti forums using google.  But if you follow this article, you might find a solution with SSL.  https://forums.cacti.net/about31293.html

**Comment by andermat8** [comment]
I had to comment out openssl in the php.ini file:

;extension=php_openssl.dll

Once this was done it stopped forcing an ssl smtp connection.  Running php 7.0.19 btw.  It appears that selecting none for smtp security doesn't work if this extension is enabled but if you specify TLS or SSL and have this commented out in php.ini you will get an error as well.

**Comment by cigamit** [comment]
Please try this, on lib/functions.php goto approximately line 3574.  Just below that line, is an 'if' block.  And an 'else' block below that and in that 'else' block, add make it like the following:

if (!empty($secure) && $secure != 'none') {
...
**} else {**
    **$mail->SMTPSecure** = false;**
}

Let us know if that resolves the issue.

**Comment by andermat8** [comment]
This did not work.  I noticed this line of code at 3574 and updated without success then also found it on line 3782 and did the same but no luck.

**Comment by cigamit** [comment]
Very odd.  I'm using SSL these days, so I really can't test with it off.  I guess I could do a pcap.

**Comment by pautiina** [comment]
I think this issue can be close. Double for #1155 and resolve.
