### ISSUE TITLE
Increase Data Source  Item Max Length

### ISSUE THREAD

**Issue by paulcalabro** [Cacti/cacti#967]
The max size of the data source name is 19 characters. This is somewhat limiting. Can this be increased to, perhaps, 250 characters?

**Comment by cigamit** [comment]
I think the reason it was at 19 at one time was due to the limit of RRDtool data sources.  If you can do some testing outside of Cacti and report back what you find, that would help.  Additionally, if you test, start with RRDtool 1.3 as it's the oldest we support.  Thanks.

**Comment by cigamit** [comment]
Any updates?

**Comment by netniV** [comment]
RRDTool's documentation says that it is still 19 characters:
https://oss.oetiker.ch/rrdtool/doc/rrdcreate.en.html

I have also confirmed this with their code which shows
```c++
#define DS_NAM_SIZE   20
```

https://github.com/oetiker/rrdtool-1.x/blob/3b0a32227371b21f71c4739de9866fb706007a4e/src/rrd_format.h#L164
