### ISSUE TITLE
Ping Latency shows wrong graph

### ISSUE THREAD

**Issue by Pheonixsolutionss** [Cacti/cacti#968]
Ping check to a machine from commandline shows 0.230 ms whereas cacti graph shows it as 230 ms. Is it a bug or any work around available ?

Cacti version : 1.1.21
PHP version : PHP 5.4.16

Any help would be much appreciated

Thanks

**Comment by cigamit** [comment]
What is the host's average ping time from the Cacti Graph?  Please attache the Cacti Graph too.  Thanks.  Which OS is this?

**Comment by Pheonixsolutionss** [comment]
OS : CentOS 7

Ping from commandline:-
--- xxx.xxx.xxx.xxx ping statistics ---
20 packets transmitted, 20 received, 0% packet loss, time 18999ms
rtt min/avg/max/mdev = 0.222/0.238/0.285/0.019 ms

Same device's ping latency Graph:-
![cacti-ping](https://user-images.githubusercontent.com/31878778/30360990-0db33940-9844-11e7-93c6-d476df3ce335.png)

Thanks

**Comment by cigamit** [comment]
Yea, this graph is a little misleading those are milli-milliseconds.  It's a rendering quirk with RRDtool.  So, this is really more of a RRDtool training issue.
