### ISSUE TITLE
Resource Change issue in Cacti multi-poller setup (with sub-folders)

### ISSUE THREAD

**Issue by ikorzha** [Cacti/cacti#970]
While updating plugins on "Master" server I have realized that if plugins have sub folders they do not get created and files copied on to "remote pollers"
This is screenshot from main poller: (notice that it didn't detect file changes in sub folders even though they are present)
![sync-issue-pr](https://user-images.githubusercontent.com/11211789/30324717-05ca8e68-9790-11e7-9be9-b4d4748892f9.gif)

This is same sync process on remote poller (no folders or files are are being updated in thold sub folders as an example)

![sync-issue](https://user-images.githubusercontent.com/11211789/30328978-fff8810c-979e-11e7-8ae8-b59c4504332b.gif)

The issue present a problem when new poller is installed. IF plugins not copied manually it results in many errors and leads to plugin disabled on master server.

**Comment by cigamit** [comment]
Yea, I noticed this too just before the release of 1.1.23.  Had not time to resolve it though, the database but was too critical.

**Comment by cigamit** [comment]
Resolved.  Will be included in 1.1.24.

**Comment by ikorzha** [comment]
Thank you for the fix. I have applied 1.1.24 and tested. SYNC is fully functional.
Cigamit, if you have a chance can you please revisit thold issue 115, since we last addressed thold daemon issue few days back , I have discovered a major issue issue with thold processing where it processes about 20% of thold per min, the rest never get processed.

https://github.com/Cacti/plugin_thold/issues/115
Thank you in advance..
