### ISSUE TITLE
Remote Poller efficiency questions/problem

### ISSUE THREAD

**Issue by ikorzha** [Cacti/cacti#974]
Hi to all, I have Cacti 1.1.23 master server and a remote poller that has a 65ms response time between them due to physical distance (no congestion or packet loss).

I only have 5 hosts configured on remote poller (these hosts are local to remote poller) and polling times are 33-34sec every min.

Is there a way to improve efficiency of remote poller with latency...I have a lot more hosts to add than just 5...
Remote Poller:
![remote](https://user-images.githubusercontent.com/11211789/30440401-690bfc72-9944-11e7-9c6a-e2c397224a52.gif)

**When I move these host to "master server" its performance doesn't even budge. Now the 5 hosts it polls are 2000 miles away with 65ms response time instead of the remote poller....**

Master poller after 5 device move:
![master](https://user-images.githubusercontent.com/11211789/30440468-9c16b12a-9944-11e7-8a56-ec86de41c5ee.gif)

Remote Poller after 5 device move:
![image](https://user-images.githubusercontent.com/11211789/30440496-b7a0638c-9944-11e7-99a9-59ff3afcadca.png)
________________________________________________________________________________________________________
Another interesting comparison:
Remote poller 65ms response from master. 1 Device added with single data source (network interface statistics): Poll time below: 30sec+
I think this type of "delay in remote polling" warrants a revisit from cacti team. Remote polling functionality is the selling point of Cacti 1.x and some attention needs to be paid how Cacti handles a remote poller with latency

![remote-poller-1-device](https://user-images.githubusercontent.com/11211789/30453347-9f125b3c-9966-11e7-96e5-d295db106153.gif)

P.S if there are any efficiency to be gained here, I would love to be a tester.

**Comment by cigamit** [comment]
That's just too many processes + threads times two servers.  In the current design, both the spines are hitting your primary database, which is crushing it.  Add your thold stuff, and you are simply overloading the database server.  It's plain and simple.

We are looking at moving the entire remote data collector polling process to the remote database all the time.  Once that is achieved, the remote data collectors will literally be stand alone.  This will be a much more scalable solution.

But, I know many people who poll literally thousands of devices with like 4 processes and 20 threads.  At some point, having all those threads add no additional value, and actually slows down data collection.  This new feature will not be available till at least 1.2.
