### ISSUE TITLE
no file or directory issue

### ISSUE THREAD

**Issue by rashid73** [Cacti/cacti#975]
RRDTool Says:
ERROR: opening '/usr/share/cacti/rra/local_machine_load_1min_7.rrd': No such file or directory
read the error and suggest any solution.

**Comment by rashid73** [comment]
created the above directory manually and found the following error.
RRDTool Says:
ERROR: mapping file '/usr/share/cacti/rra/local_machine_load_1min_7.rrd': No such device

**Comment by cigamit** [comment]
Sorry, this is best handled in the forums.
