### ISSUE TITLE
UI Behavior

### ISSUE THREAD

**Issue by jpobeda** [Cacti/cacti#980]
Hi there, please look at the attached animated gif.

Is it possible to change the behavior so we can put a name without having to rename it ?

This was tested on 1.1.21

![2017-09-18_09-25-55](https://user-images.githubusercontent.com/13456559/30525082-b7607918-9c53-11e7-99d5-e0ec09126f9d.gif)

**Comment by cigamit** [comment]
Resolved thanks!
