### ISSUE TITLE
RRDfile Size data missing in Data Source Profile details

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#982]
![image](https://user-images.githubusercontent.com/12864741/30526174-66377486-9bd3-11e7-8e77-7efb68992548.png)

I think this was working at one point ...

**Comment by cigamit** [comment]
Hold on.  Checking.  We are nearing a release.

**Comment by cigamit** [comment]
Open the Developer Debug window and goto the console and see if you have a JavaScript error somewhere.  This value is calculated using a callback.  That callback will fail if there is some JavaScript error on the page.  Might be a plugin interfering.  Past a screen shot

**Comment by eschoeller** [comment]
![image](https://user-images.githubusercontent.com/12864741/30526300-cd43ac1a-9bd5-11e7-8d20-4b985fd2fde9.png)
Haha ... it's just the wrong color text. I can highlight it.

**Comment by eschoeller** [comment]
But I dunno what the "$s Bytes" part is about... !

**Comment by cigamit** [comment]
Okay, got this one resolved.
