### ISSUE TITLE
Import Template Preview is misleading

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#983]
When you select "preview" (or even if you don't) the results are displayed, followed by the import dialog again. Especially when you preview, it seems as if you could just hit the "Import" button to "accept the changes" but this doesn't work and just shoots you back to the Import Template dialog again. I am pretty sure in 0.8.6 days the import results were just displayed here, and perhaps an OK button, which would then take you back to the dialog.
**
![image](https://user-images.githubusercontent.com/12864741/30526472-3a54a726-9bd8-11e7-93d1-eb0158668599.png)
**

**Comment by eschoeller** [comment]
Also, the "Select a File" button remains with the same text, even after you have selected a file. This is also a bit misleading ... making you think perhaps it didn't actually select it. I think in the past this actually showed the file you were importing once it had been selected.

**Comment by cigamit** [comment]
Okay, we should so some of this in a callback.  Won't make it to 1.1.24.  I'll mark this as an enhancement.  Really appreciate the constructive criticism.

**Comment by netniV** [comment]
I have just tested this in 1.2 and a filename appears to the right of the "Select a File" button so I'm going to close it.
