### ISSUE TITLE
UI Issues in Tree edit mode

### ISSUE THREAD

**Issue by jpobeda** [Cacti/cacti#984]
Hi there,

Please see attached GIF. It's a little bit longer but I wanted to be able to reproduce it.

So you'll see 2 different issues.

1.- If you've clicked another device AND you try do drag a different one, it'll show you the one you want to move but it actually moves the one you've clicked on before.

2.- Somehow the thing gets broken until you refresh the page some how or try a different device. you'll see that close to the end of the GIF when I'm trying to move device17 and it just disappears.

![2017-09-18_14-54-23](https://user-images.githubusercontent.com/13456559/30527918-fceb73b0-9c81-11e7-811d-aad384c4528a.gif)

Cheers

**Comment by cigamit** [comment]
Any errors in the Cacti log?

**Comment by jpobeda** [comment]
Nothing. I'm actually running 1.1.17 as prod and I reproduced it to record the GIF on a 1.1.21 test installation. Do you want me to turn debugs on and reproduce it again? Any special debug?

**Comment by cigamit** [comment]
I'll have to work on reproducing this from the video.

**Comment by netniV** [comment]
Hi @jpobeda, are you still running that older version? If you've upgraded are the errors still occurring?

**Comment by netniV** [comment]
No feedback, closing.

**Comment by cigamit** [comment]
I could never find a good resolution to this.  The drop area is constrained to the area around the tree and expanding that drop area takes away valuable screen real-estate.

**Comment by jpobeda** [comment]
@netniV , @cigamit, 
Sorry the lack of feedback. I've just reproduced this on a 1.1.38 installation. I'll see if I can still reproduce it on 1.2.x and update.
