### ISSUE TITLE
Mouse scroll wheel inoperative over graphs

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#985]
I mentioned this at the end of #932 but figured I'd open a new issue - since the original issue in #932 is fixed in 1.1.24. 

When your mouse is positioned over a graph the scroll wheel does not move the page up and down. You need to position your mouse within the frame, but not on any graphs. I have my graphs displayed as 2 columns, which reduces the amount of white "dead" space available to use the scroll feature of the mouse. There's actually barely any room, which is a good thing since there isn't any wasted screen real-estate. 
I think this has possibly been an issue for a long time - I just thought my wheel was finicky. Now I can reproduce it and understand what is going on.

**Comment by eschoeller** [comment]
Reproduced in Firefox and Chrome. 

![peek 2017-09-17 23-35](https://user-images.githubusercontent.com/12864741/30530125-4f573368-9c01-11e7-82bb-7b2d94a044d0.gif)

**Comment by browniebraun** [comment]
Update CSS of all three themes as well as /include/js/jquery.zoom.js

and verify that it is working in your environment, please.

Regards
-Andi
