### ISSUE TITLE
Very minor graphical issue in Modern theme (maybe others)

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#986]
There is a gray gradient near the top of the browser window which is overrun by the main frame when it is scrolled. This happens just about everywhere I can see. 
In this animation I'm circling my mouse around the gradient when it's present, and when it's missing. Again, very very minor, but fixing it would probably produce a more "polished" and intentional looking behavior. 
![peek 2017-09-17 23-43](https://user-images.githubusercontent.com/12864741/30530223-2903d13e-9c02-11e7-8e70-970b7ad68ab7.gif)

**Comment by cigamit** [comment]
This is not an easy fix.  It's best just to get rid of it on both the left and right.  What do you think?

**Comment by eschoeller** [comment]
I think it looks good, and would suggest keeping it, but I don't know what's involved with it. If you point me in the right direction I might be able to help fix it, especially if it's just tedious repetitive work. I'm in a good position to do that right now.

**Comment by cigamit** [comment]
Turned out to not be that difficult.
