### ISSUE TITLE
Unreliable Poller Features

### ISSUE THREAD

**Issue by OUnagiles** [Cacti/cacti#995]
Hello, 

We have noticed what appears to be a bug affecting some poller functionality.

It seems to affect features that rely on specific time intervals. For instance:
* Email reports are sent at highly irregular intervals, if at all
* Automated subnet scanning fails to trigger at the expected time

Through some experimentation, I believe we have traced the point of failure to the 'exec_background' function in the file lib/poller.php

```php
if (file_exists($filename)) {
                if ($config['cacti_server_os'] == 'win32') {
                        pclose(popen("start \"Cactiplus\" /I \"" . $filename . "\" " . $args, 'r'));
                } else {
                        exec($filename . ' ' . $args . ' > /dev/null &');
                }
        } elseif (file_exists_2gb($filename)) {
                exec($filename . ' ' . $args . ' > /dev/null &');
        }
```

It appears that altering the arguments of the 'exec' call to exclude the redirect to /dev/null fixes the issue

```php
if (file_exists($filename)) {
                if ($config['cacti_server_os'] == 'win32') {
                        pclose(popen("start \"Cactiplus\" /I \"" . $filename . "\" " . $args, 'r'));
                } else {
                        exec($filename . ' ' . $args . ' &');
                }
        } elseif (file_exists_2gb($filename)) {
                exec($filename . ' ' . $args . ' > /dev/null &');
        }
```
After this change, our instances started generating automated reports as expected and subnet scanning appeared to trigger correctly.

However, I am not familiar enough with the code in general to determine the significance of this "fix"

Some further details:
* We have experienced this problem on two machines:
  * First with both Cacti v1.1.16 and then v1.1.19 running on RHEL 7.4, php 5.4.16
  * Duplicated briefly with Cacti v1.1.21 running on Ubuntu 16.04, php 7.0.2

* Manually sending a report using the "send now" option works as expected

* Manually scanning a subnet using the "discover now" option appears to iterate through the address range but fails to detect any devices

* When the problem occurs, the cacti log does not appear to display any log messages indicating either the success or failure of the afflicted features 

* Our test case used a pair of email reports set to be generated on a 5-minute interval. The emails were generated very infrequently (e.g. seemingly random 5 minute - 8 hour intervals) and the second of the pair was generated even less frequently, if at all.

* The script cacti/poller.php is set to be invoked every 5 minutes. This appears to be functioning properly as we are regularly receiving data for our monitored devices.

**Comment by cigamit** [comment]
Can you please break your instance for just a short period of time.  This is what I would like you to do:

1) Edit the cron and redirect standard error to standard output similar to this (keep your cron frequency):

*/1 * * * * php -q poller.php --force >> /tmp/poller.log 2>&1

2) In the exec that you modified in your case, do the same.  Redirect the stadard error to standard output.

3) In /etc/php.ini or /etc/php5/cli/php.ini un-comment the error_log statement and move the that log to /tmp/error_log.log

Run a few passes of the poller and then share your findings.

**Comment by cigamit** [comment]
One last question, are you using Send Mail method or SMTP?

**Comment by cigamit** [comment]
I've committed the change, but still would like the output prior to closing this.  Thanks!

**Comment by OUnagiles** [comment]
Thank you for the help!

Regarding email configuration: the RHEL instance currently uses SMTP.

Regarding output from the poller into the log:
* In /tmp/poller.log, I noticed blocks of 
  ```
  Waiting on 1 of 2 pollers.
  Waiting on 1 of 2 pollers.
  Waiting on 1 of 2 pollers.   
  Waiting on 1 of 2 pollers.
  Waiting on 1 of 2 pollers.
  Waiting on 1 of 2 pollers.
  Waiting on 1 of 2 pollers.
  Waiting on 1 of 2 pollers.
  Waiting on 1 of 2 pollers.
  Waiting on 1 of 2 pollers.
  ```
  interspersed in the file (using the original exec call). These were absent with the altered version

  ```php
  exec($filename . ' ' . $args . ' 2>&1 &');
  ```
  
  There was also many lines of the form
  ```
  OK u:<numeral> s:<numeral> r:<numeral>
  ```
  which I assume is expected output. I didn't notice any explicit error messages.

* Despite altering php.ini to include the new defition for error_log, the file /tmp/error_log.log never appeared to be populated with any values

If I need to clarify something please let me know.

**Comment by cigamit** [comment]
I've reverted the original fix to this bug due to numerous errors in the past.  Sorry, to you and the others negatively impacted by this change.  Now to your problem...  Next post.

**Comment by cigamit** [comment]
You need to pose the last 1000 lines of your Cacti.log.  Thanks.

**Comment by OUnagiles** [comment]
Here is roughly 1000 lines from a couple of recent polls:

[cacti_log_sample.log](https://github.com/Cacti/cacti/files/1380097/cacti_log_sample.log)

**Comment by cigamit** [comment]
Done really need the debug information.  Try without it.

**Comment by OUnagiles** [comment]
Here's a recent section gathered with the log output set to "High": 

[cacti_log_sample_2.log](https://github.com/Cacti/cacti/files/1394556/cacti_log_sample_2.log)

**Comment by cigamit** [comment]
Okay, this ticket is a bit of a mess.  What I'm reading into this is that timing for certain reports are not working as expected.  Why don't you open separate tickets for each section that is experiencing the issue so that we can track and resolve independently.  Thanks for your patience on this matter.
