### ISSUE TITLE
Print all graphs to the Tree configuration dialog wo limits

### ISSUE THREAD

**Issue by nkozubsky** [Cacti/cacti#996]
File: tree.php
Function: display_graphs

Why you select from graph_templates_graph table with "LIMIT 20"?

If I delete "LIMIT 20", I've got a full list of my graphs, but I've lost a convenience to drag selected graph name to the Tree Items box. (I think, I need to use a find filter to decrease a choice array.)

Yet, I think, the list of graphs must be linked to the Device,  then the list will be smaller. 
All the best.
Nick

**Comment by cigamit** [comment]
We don't want to show all the graphs, since people with 200,000 graphs would fail to load the page.  Instead there is a search box there to allow you to narrow your selection down.
