### ISSUE TITLE
After php error in log ../lib/functions.php on line:1279 plugins msgs not reported to log

### ISSUE THREAD

**Issue by ikorzha** [Cacti/cacti#997]
In the latest cacti 1.1.24 and thold 1.0.4 I have observed the following behavior:
After php error in log ../lib/functions.php on line:1279 any stats msgs from Cacti plugins are no longer posted in the log file... 
Interestingly enough, if I turn on thold daemon, plugin msgs start to appear again in the log...So it probably has something to to with thold..
Screenshot below:

![latestlog](https://user-images.githubusercontent.com/11211789/30606383-90632e04-9d3f-11e7-86d0-a0a45f9da0cb.gif)

Additional log errors after server reboot, further observations show that problem only occurs when standard "thold poller is in use, not with daemon":
![latestlog-errors](https://user-images.githubusercontent.com/11211789/30614475-8268b08e-9d59-11e7-946a-efdfbbb7d72b.gif)

**Comment by cigamit** [comment]
Looks like a thold bug.  Can you move this to the thold plugin issue list?  Closing.
