### ISSUE TITLE
Can create external data source but can't delete it

### ISSUE THREAD

**Issue by david-hill** [Cacti/cacti#998]
Can create external data source but can't delete it  and here's how to reproduce this issue:

- Create a data source template and select "External" in Data Source Profile.
- Try to find it in "Data Source" when "Profile" is set to "All"

This is seen in 1.1.21

**Comment by cigamit** [comment]
I'm wondering if External is even a valid case for a template.  I think it's not.

**Comment by cigamit** [comment]
Resolved.  You should be able to delete it now, but you also won't be able to create additional ones.  I don't see a use case for that anyway.
